### PR TITLE
openapi-changes: init at v0.0.61

### PR DESCRIPTION
**Pull request by mguentner**
## Description of changes

init [openapi-changes](https://pb33f.io/openapi-changes/) at version 0.0.61

tested the `html-report` and `report` feature

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
Result of `nixpkgs-review pr 299859` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>openapi-changes</li>
  </ul>
</details>

**Comment by mguentner** [comment]
@teto: How did it fail? I believe that the derivation suffers from https://github.com/NixOS/nixpkgs/issues/8567.
Either we can disable the tests, thus can rely on the source archive instead of the git repository or fix the tests upstream so that they do not rely on the project repository itself any longer but create one instead in some temp directory.

**Comment by teto** [comment]
the link mentions doing
 ```
  postFetch = ''
    rm -rf $out/.git
  '';
  ```
  that seems like the most straightforward ?

**Comment by mguentner** [comment]
The tests require the project's `.git`:

```
Running phase: checkPhase
ok      github.com/pb33f/openapi-changes/builder        0.043s
--- FAIL: TestCheckLocalRepoAvailable (0.00s)
    read_local_test.go:15: 
                Error Trace:    /build/source/git/read_local_test.go:15
                Error:          Should be true
                Test:           TestCheckLocalRepoAvailable
--- FAIL: TestGetTopLevel (0.01s)
    read_local_test.go:87: 
                Error Trace:    /build/source/git/read_local_test.go:87
                Error:          Received unexpected error:
                                exit status 128
                Test:           TestGetTopLevel
    read_local_test.go:88: 
                Error Trace:    /build/source/git/read_local_test.go:88
                Error:          Should NOT be empty, but was 
                Test:           TestGetTopLevel
```
The tests assert that the application can create a report of changes made to a git repository and for that the project's own repository is used.

**Comment by teto** [comment]
ha I see. If possible I would disable only the affected tests, otherwise disable all (but comment why).  Are you affiliated with the project ? otherwise I guess it would be unreasonable to ask upstream for a chance, especially as it looks like the fault lies in git itself (and nix intolerance :) )

**Comment by teto** [comment]
I tried disabling tests and keepDotFolder but ` wget https://github.com/pb33f/openapi-changes/archive/v0.0.60.tar.gz` returns
`the given path has multiple possibilities: #<Git::Ref:0x00007f00ad7c4fc0>, #<Git::Ref:0x00007f00ad7c2950>`.

I had to specify a revision and this worked:
```
diff --git a/pkgs/by-name/op/openapi-changes/package.nix b/pkgs/by-name/op/openapi-changes/package.nix
index 0fed1751ee55..4a9aa9c22290 100644
--- a/pkgs/by-name/op/openapi-changes/package.nix
+++ b/pkgs/by-name/op/openapi-changes/package.nix
@@ -12,19 +12,23 @@ buildGoModule rec {
   src = fetchFromGitHub {
     owner = "pb33f";
     repo = pname;
-    rev = "v${version}";
-    hash = "sha256-THO1FNlnK3iRLJt0rlZBMLBom1FHVPBEQSgaKVGKWzA=";
+    rev = "62afb410701a9fbe25b51c58bff1d2c5e1286c0e";
+    hash = "sha256-c8Cu9DoUnm7jxUB2ekOq757NJTrlKUYhF6KHdFtPJRo=";
     # needed for tests
-    leaveDotGit = true;
+    # leaveDotGit = true;
   };
 
-  nativeCheckInputs = [ git makeWrapper ];
+  nativeBuildInputs = [makeWrapper ];
+  nativeCheckInputs = [ git ];
 
   postInstall = ''
     wrapProgram $out/bin/openapi-changes --prefix PATH : ${lib.makeBinPath [ git ]}
   '';
 
-  vendorHash = "sha256-gaBVwrSaIwe1eh8voq928cxM/d0urVUF0OUwWZb2fR8=";
+  vendorHash =
+  "sha256-gaBVwrSaIwe1eh8voq928cxM/d0urVUF0OUwWZb2fR8=";
+
+  doCheck = false;
 
   meta = with lib; {
     description = "The world's sexiest OpenAPI breaking changes detector";
```

**Comment by mguentner** [comment]
@teto, thanks. I am not affiliated with project and fully agree with your assessment (do not fix nix issues upstream).

Instead of disabling all tests, I simply delete the problematic test in the `patchPhase`.

**Review by teto — APPROVED** [review]

**Pull request merged**
