### PR TITLE
neovide: 0.8 -> 0.9

### PR DESCRIPTION
**Pull request by ck3d**
###### Description of changes

Update to latest release

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by teto — APPROVED** [review]

**Comment by pmiddend** [comment]
I can build this, but `result/bin/neovide` or `result/bin/neovide README.md` in my `nixpkgs` clone simply does nothing (exit code of the program is 0). Am I doing something wrong?

**Comment by ck3d** [comment]
It you be that you faced issue #168769.

What is the output when you run the command `neovide --nofork`?

**Comment by pmiddend** [comment]
@ck3d Correct, I'm getting:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([OsError("Could not create EGL display object"), OsError("`glXQueryExtensionsString` found no glX extensions")])', src/window/mod.rs:347:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pmiddend** [comment]
> The error is the same, OpenGL can not be initialized. Does neovide-0.8 from master branch show the same error?

Yes, same error. I might not be the best person to review this update then. ;)

**Comment by teto** [comment]
if the error was preexisting this PR which I think it does, let's merge. @ck3d you've got the permissions go ahead :)

**Comment by ck3d** [comment]
I don't have merge rights (but I requested them a few days ago), so can you please merge my PR.

**Comment by kirillrdy** [comment]
this change doesnt build on master here is a fix https://github.com/NixOS/nixpkgs/pull/179858

**Pull request merged**
