### PR TITLE
Update heimdall to 1.4.1

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by edwtjo** [comment]
You forgot to update the version in the name. Also, while you don't need to make that change, I would like it better if you used fetchFromGitHub(which fetches an archive from a rev) instead of fetchgit which fetches the whole repo. Other than that, confirmed working.

**Comment by DamienCassou** [comment]
@edwtjo fixed, thanks

**Comment by ryantm** [comment]
@edwtjo : @iElectric told me it's preferred to use tarball sources over git. For example, https://github.com/Benjamin-Dobell/Heimdall/archive/v1.4.1.tar.gz

**Comment by DamienCassou** [comment]
@edwtjo as far as I know, this is exactly what `fetchFromGitHub` does. Is there anything you would like me to change?

**Comment by edwtjo** [comment]
Personally I don't care much whether you use fetchFromGitHub or a github releaseball to download a tagged release, since both should have the same corresponding rev and download the same archive. That said some repo owners are sloppier than others and/or use github for development but not releases, and yes @iElectric is correct in that you should prefer to use the releaseball instead, since these might not be the same. It is also the case that you shouldn't packaged stuff without a release, though sometimes the version has been written in a commit message or an updated changelist, there wasn't a tag created and there wasn't a releaseball. Hence the need for fetchFromGitHub, which just downloads the archive, or fetchgit, which downloads any git repo.

Looking at Heimdall you can use either and there is no need for change, since the developer is not sloppy and both resolve to the same archive. You can verify this by looking at the fetchFromGithub function in all-packages.nix.

**Pull request merged**
