### PR TITLE
electron: Bump default version to v30

### PR DESCRIPTION
**Pull request by yayayayaka**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by yayayayaka** [comment]
Result of `nixpkgs-review pr 309248` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>itch</li>
  </ul>
</details>
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antares</li>
    <li>bilibili</li>
    <li>bitwarden-directory-connector</li>
    <li>breitbandmessung</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron</li>
    <li>electron-bin</li>
    <li>electron_29</li>
    <li>electron_29-bin</li>
    <li>fcast-receiver</li>
    <li>freetube</li>
    <li>geogebra6</li>
    <li>headset</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>nix-tour</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>sharedown</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Review by emilylange — DISMISSED** [review]
Blocking because of https://github.com/NixOS/nixpkgs/pull/309041#issuecomment-2094844146

**Comment by drupol** [comment]
Can we rebase this PR ?

**Comment by emilylange** [comment]
> Can we rebase this PR ?

Why? What would change?

**Comment by drupol** [comment]
> Blocking because of https://github.com/NixOS/nixpkgs/pull/309041#issuecomment-2094844146

This PR was merged , that's the reason why I requested the rebase. Am I misunderstanding something?

**Comment by emilylange** [comment]
> > Blocking because of [#309041 (comment)](https://github.com/NixOS/nixpkgs/pull/309041#issuecomment-2094844146)
> 
> This PR was merged , that's the reason why I requested the rebase. Am I misunderstanding something?

This PR here (#309248) was opened *after* #309041 had been merged.

And the reason I have a blocking review here, is because we need to fix https://github.com/NixOS/nixpkgs/pull/309041#issuecomment-2094844146 (something I commented after #309041 had already been merged).

The simplest would be simply reverting 6a7a561360b5593e70a8f8ab72393b13fb83dc8a for now, until a newer version of `electron_30` is released.
There is a whole history to it (unfortunately):
- fb10ea41b2a080cb4ecac34aa12cf056d8d3f90e
- 85dfe83a86658f3fba80c050a774195f08fb378d
- #306010

As of now, there is no consumer of `electron_30` in nixpkgs (except #308970 I suppose).
This would obviously drastically change with this PR here, which, well, changes the default to `electron_30`.

**Comment by teutat3s** [comment]
I tested starting [`element-desktop` with `electron_30`](https://github.com/NixOS/nixpkgs/pull/317579) under wayland (sway) and it works fine, looks like it uses [`--ozone-platform-hint=auto`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/instant-messengers/element/element-desktop.nix#L109).

**Review by yayayayaka — COMMENTED** [review]
Added pins to electron_29 on breitbandmessung and antares. The remaining applications seem to work fine (except for the ones being broken for unrelated reasons)

**Comment by yayayayaka** [comment]
Result of `nixpkgs-review pr 309248` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>itch</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antares</li>
    <li>bilibili</li>
    <li>bitwarden-directory-connector</li>
    <li>breitbandmessung</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron</li>
    <li>electron-bin</li>
    <li>fcast-receiver</li>
    <li>freetube</li>
    <li>headset</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>nix-tour</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>sharedown</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Pull request merged**
