### PR TITLE
Revert "riak-cs: add to nixpkgs"

### PR DESCRIPTION
**Pull request by falsifian**
Reverts NixOS/nixpkgs#20129

See my comment on the original pull request. I think it's messing up Travis.

### CODE REVIEW

**Comment by LnL7** [comment]
I'm pretty sure this is normal, unrill hydra has finished the build.

**Comment by mdaiter** [comment]
I'm pretty sure this error is normal. Look at this: https://travis-ci.org/NixOS/nixpkgs/jobs/177520347#L776-L783 . It simply exits because the package wasn't meant to be built with an i686 machine. I can check as to why the machine is attempting a build with an i686 machine.

**Comment by mdaiter** [comment]
@falsifian this shouldn't even trigger the i686 system. https://github.com/NixOS/nixpkgs/pull/20129/files#diff-9882359e392e39a6115bbac06b20b56eR63

**Comment by mdaiter** [comment]
@falsifian got it! Seems like it's a problem with adding a default package to the service module. https://github.com/NixOS/nixpkgs/blob/98a9d815e05dd56aba0f9040d96092335cd90444/nixos/modules/services/databases/riak.nix#L21-L27 <- if you look at this, there's a reason riak avoids a default: when generating the manual, the system attempts to reference derivations of packages that have already been built. On an i686 machine, this is impossible to perform; therefore, the i686 system fails.

I'll delete the `default` option within the package to make it congruent with the riak package.

**Comment by mdaiter** [comment]
@falsifian seems like the system should build now that the `default` option is removed. Weird that the system would respond as such with that...

**Comment by joachifm** [comment]
f7c097556ba96375bf69b13ed3b0613e59722011 has this issue as well, I think

**Comment by joachifm** [comment]
@mdaiter you ought to use `defaultText`

**Comment by mdaiter** [comment]
@joachifm but `stanchion` builds fine...hm.

I'll use `defaultText` and test

**Comment by mdaiter** [comment]
@joachifm just pushed with defaultText.

**Comment by LnL7** [comment]
Oh, that sucks. So we can't provide default options if they don't work on `i686` because of travis?
I want hydra pr support. 🙁

**Comment by mdaiter** [comment]
@joachifm how should I test against your TravisCI system? Should I open another PR?

**Comment by joachifm** [comment]
@mdaiter but it too adds a service module with a default value set to a package. Always use `defaultText` for stuff that shouldn't be evaled during manual build (really, anything but trivial data).

**Comment by mdaiter** [comment]
@joachifm I'll open another PR with my stanchion default -> defaultText change.

**Comment by joachifm** [comment]
@mdaiter to test, you can build the manual, as in `nix-build nixos/release.nix -A manual`

**Comment by mdaiter** [comment]
@joachifm I'll open that PR for stanchion asap

**Comment by mdaiter** [comment]
@joachifm https://github.com/NixOS/nixpkgs/pull/20597

Riak-CS is also up -- just on my branch. Let's get this merged in first.

**Comment by mdaiter** [comment]
@joachifm @LnL7 just merged in https://github.com/NixOS/nixpkgs/pull/20597 . Just pushed my Riak CS update to my nixpkgs. Should I open another PR?

**Comment by LnL7** [comment]
I think you can reopen the previous one, since it was reverted

**Comment by mdaiter** [comment]
@LnL7 GitHub isn't displaying the option. I'll just open another PR.

**Comment by mdaiter** [comment]
@LnL7 https://github.com/NixOS/nixpkgs/pull/20598 <- for the original `riak` package

**Comment by mdaiter** [comment]
@LnL7 @joachifm https://github.com/NixOS/nixpkgs/pull/20599 <- for the new PR

**Pull request merged**
