### PR TITLE
element-{web,desktop}: 1.8.4 -> 1.8.5

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Motivation for this change

https://github.com/vector-im/element-web/releases/tag/v1.8.5

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FlorianFranzen — CHANGES_REQUESTED** [review]
You will have to remove this now included patch:
```diff
--- a/pkgs/applications/networking/instant-messengers/element/element-desktop.nix
+++ b/pkgs/applications/networking/instant-messengers/element/element-desktop.nix
@@ -34,13 +34,6 @@ mkYarnPackage rec {
   name = "element-desktop-${version}";
   inherit version src;
 
-  patches = [
-    (fetchpatch {
-      url = "https://github.com/vector-im/element-desktop/commit/96e5389779f60c91b8fe80d7bd9af413d72ec61f.patch";
-      sha256 = "sha256-82I5BDNDWIfp+m2HpzTA5+39hMv2bTbmJlXfM4YUjDY=";
-    })
-  ];
-
   packageJSON = ./element-desktop-package.json;
   yarnNix = ./element-desktop-yarndeps.nix;
 ```

**Review by FlorianFranzen — APPROVED** [review]
Thanks, looks good. Builds and runs fine.

The only thing I would ask you is to squash the two commits into one.

**Comment by sumnerevans** [comment]
I disagree with squashing. These are two distinct changes.

**Comment by Ma27** [comment]
> I disagree with squashing. These are two distinct changes.

Since the patch is in 1.8.5, I assume that `element-desktop` doesn't build anymore with this patch being applied on top? If yes, then it should really be squashed.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
@sumnerevans would you mind taking care of the backport? :)

**Pull request merged**
