### PR TITLE
vala updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/57027

I feel like we have maybe one too many compiler versions here, so I'd like to know which one would be acceptable for removal.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Upstream usually supports three most recent branches so ideally, we would not keep more than these. Personally, I would just keep the latest branch but elementary probably depends on the ancient version in Ubuntu LTS and we also have a lot of Vala abandonware, so we might not afford to drop that much yet.

**Comment by worldofpeace** [comment]
> Upstream usually supports three most recent branches so ideally, we would not keep more than these. 

Exactly, hence my confusion in us keeping more than these

> Personally, I would just keep the latest branch but elementary probably depends on the ancient version in Ubuntu LTS

They actually, at least recently, push fixes for any breakage that they notice will happen with the latest vala. Ubuntu LTS is at `0.40`  but we should be able to use `0.44` for Pantheon.

Only thing that could be a large annoyance is the "third party apps" are tested against `0.40` so they'll slowly break as the LTS goes by.

**Comment by worldofpeace** [comment]
I've corrected the patches and added a patch so `libhttpseverywhere` can build with latest vala.

**Review by jtojnar — APPROVED** [review]

**Comment by worldofpeace** [comment]
@jtojnar I should merge this into the gnome branch?

**Comment by jtojnar** [comment]
I would just merge it to staging. And rebase gnome-3.32 onto that (since we already want that for gdk-pixbuf).

**Comment by dtzWill** [comment]
Should this use callPackages at the top-level?

**Comment by jtojnar** [comment]
Possibly, I am not sure what the difference is though.

Also, it would be nice if we could make `updateScript` work.

**Pull request merged**
