### PR TITLE
openmpi: 3.1.2 -> 3.1.3

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
Minor update. Refactor version string so that it can be picked up by the auto updater in the future. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build python36Packages.mpi4py

**Comment by timokau** [comment]
This isn't a blocker and I'm fine with merging this as-is, but if you refactor it to use a standard `version` attribute r-ryantm could do these updates in the future.

**Comment by markuskowa** [comment]
@timokau Thanks for pointing that out. That should work for the auto updater?

**Review by timokau — APPROVED** [review]
I think it should. As far as I know it basically `grep`s for the current version string and replaces that with the new version.

**Pull request merged**
