### PR TITLE
sage: misc fixes

### LINKED ISSUE #51326: SageMath 8.4 returns, in notebook interface, "Error typesetting mathematics" when one attempts to plot with Matplotlib
## Issue description
On NixOS 18.09, with SageMath 8.4, Matplotlib 2.2.3 (Python 2.7 version, in case you think I installed the wrong Matplotlib version) and Texlive 2018 (XeTex 3.0) I receive this error:

screenshot_20181130_233107

Why did I install Texlive and mention it? Because I thought given the error it might be needed, so I installed it and re-tried, receiving this same error. If you want the code (so you can test it yourself) and don't want to have to manually copy it from the shown screenshot here it is:

```sage
x,y,z=var('x,y,z')
# Next we define the parameters
sigma=10
rho=28
beta=8/3

# The Lorenz equations
lorenz=[sigma*(y-x),x*(rho-z)-y,x*y-beta*z]

# Time and initial conditions
N=250000
tmax=250
h=tmax/N
t=srange(0,tmax+h,h)
ics=[0,1,1]
sol=desolve_odeint(lorenz,ics,t,[x,y,z],rtol=1e-13,atol=1e-14)
X=sol[:,0]
Y=sol[:,1]
Z=sol[:,2]

# Plot the result
from mpl_toolkits.mplot3d import axes3d
from matplotlib import pyplot as plt

# Call the plot function if you want to plot the data
fig = plt.figure(num=None, figsize=(16, 12), dpi=120, facecolor='w', edgecolor='k')
ax = fig.gca(projection='3d')
ax.plot(X, Y, Z, lw=0.5)
ax.set_xlabel("X Axis")
ax.set_ylabel("Y Axis")
ax.set_zlabel("Z Axis")
ax.set_title("Lorenz Attractor")

plt.show()
```

Notebook was started by starting SageMath with `sage` and then at the `sage>` prompt I ran `notebook()`. 

All I saw at the `sage>` prompt, error-wise related to the fact xdg-open didn't seem to be working as it couldn't figure out how to open the notebook in my browser, I had to manually do it myself.

### Steps to reproduce
Install NixOS 18.09, with this config file: https://github.com/fusion809/NixOS-configs/master/NixOS-18.09/configuration.nix. Then per the [FAQ](https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F) add the nixos-unstable channel with:

```bash
sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
sudo nix-channel --update nixos-unstable
```

Then install SageMath with:

`nix-env -f '<nixos-unstable>' -iA sage texlive`

then, run:

```bash
nix-shell -p gobjectIntrospection gtk3 'python27.withPackages(ps : with ps; [ matplotlib sage ])' 
```

to hopefully get SageMath and Matplotlib built to work with one another (IIRC) in a GTK+ 3 environment. If this works I should get a GTK+ 3 Matplotlib window to show when this runs correctly. If you get the error:

```bash
building '/nix/store/xd2s5kj59zv2bi6gj7wzajrf7gwk5fs0-python-2.7.15-env.drv'...
collision between `/nix/store/wvwj4x34gv5wqmgq65i3x1x725kclfwm-python2.7-backports.ssl_match_hostname-3.5.0.1/lib/python2.7/site-packages/backports/__init__.py' and `/nix/store/37i3dxmd48f0mr5hilfp9s9iah7yz777-python2.7-backports.functools_lru_cache-1.5/lib/python2.7/site-packages/backports/__init__.py'
builder for '/nix/store/xd2s5kj59zv2bi6gj7wzajrf7gwk5fs0-python-2.7.15-env.drv' failed with exit code 25
```

then run:

```bash
nix-shell -p gobjectIntrospection gtk3 'python2.withPackages (ps: with ps; [ pygobject3 ])' --run "python -c \"import pygtkcompat; pygtkcompat.enable_gtk(version='3.0')\"
```

(which I also run to help with getting a GTK+ 3 Matplotlib window, as it has worked before on non-NixOS distros), then finally you're on the right track to emulating my local set up.

Now run `sage` and at the `sage>` prompt run `notebook()` and in the Notebook run:

```bash
x,y,z=var('x,y,z')
# Next we define the parameters
sigma=10
rho=28
beta=8/3

# The Lorenz equations
lorenz=[sigma*(y-x),x*(rho-z)-y,x*y-beta*z]

# Time and initial conditions
N=250000
tmax=250
h=tmax/N
t=srange(0,tmax+h,h)
ics=[0,1,1]
sol=desolve_odeint(lorenz,ics,t,[x,y,z],rtol=1e-13,atol=1e-14)
X=sol[:,0]
Y=sol[:,1]
Z=sol[:,2]

# Plot the result
from mpl_toolkits.mplot3d import axes3d
from matplotlib import pyplot as plt

# Call the plot function if you want to plot the data
fig = plt.figure(num=None, figsize=(16, 12), dpi=120, facecolor='w', edgecolor='k')
ax = fig.gca(projection='3d')
ax.plot(X, Y, Z, lw=0.5)
ax.set_xlabel("X Axis")
ax.set_ylabel("Y Axis")
ax.set_zlabel("Z Axis")
ax.set_title("Lorenz Attractor")

plt.show()
```

## Technical details

```bash
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.84, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(fusion809): `""`
 - channels(root): `"nixos-18.09.1446.db561c90ef3, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

Fixes #51326.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fusion809** [comment]
Sadly this didn't fix it for me. After my Sage script has successfully run, I now see absolutely nothing. No plot, no error, nothing at all. 

After it is run this is what I see:

screenshot_20181202_055609

**Comment by timokau** [comment]
This does fix the mathjax issue. I also added a commit to fix a jmol issue I noticed while playing with it (its a shame we can't properly automatically test the interactive things).

The empty display is because we actually build `matplotlib` without any graphical backend by default. Sage comes with `tkinter`, so you can explicitly set the backend with `plt.switch_backend("tkagg")`. We should probably change that.

In the jupyter notebook or the CLI you can select a backend using `%matplotlib tk` or `%matplotlib inline`.

**Comment by timokau** [comment]
Oops, meant to change the commit message first. I actually fixed the *mathjax* path, not matplotlib. Anyways, no big deal.

**Comment by timokau** [comment]
Follow-up: https://github.com/NixOS/nixpkgs/pull/51344

**Pull request merged**
