### PR TITLE
nixos/tests/installer: prevent race between parted and udev

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

Our installer tests still suffer from non-deterministic failure on Hydra ([18.09](https://hydra.nixos.org/jobset/nixos/release-18.09/jobs-tab?filter=nixos.tests.installer) and [master](https://hydra.nixos.org/jobset/nixos/trunk-combined/jobs-tab?filter=nixos.tests.installer)), which often delays channels.

One typical symptom of non-deterministic failure seems to be this: 

*Successful example:*

```
machine: must succeed: parted --script /dev/vda -- mkpart primary linux-swap 1M 1024M
machine# [    9.146921]  vda:
machine: exit status 0
machine: must succeed: parted --script /dev/vda -- mkpart primary ext2 1024M -1s
machine: exit status 0
```

*Failed example:*

```
machine: must succeed: parted --script /dev/vda -- mkpart primary linux-swap 1M 1024M
machine# [   10.560431]  vda: vda1
machine# Error: Partition(s) 1 on /dev/vda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
machine# [   10.572443]  vda: vda1
machine: exit status 1
machine: output: 
error: command `parted --script /dev/vda -- mkpart primary linux-swap 1M 1024M' did not succeed (exit code 1)
command `parted --script /dev/vda -- mkpart primary linux-swap 1M 1024M' did not succeed (exit code 1)
```

The failed example looks like `udev` recognizes the new partition before `parted` tries to tell the kernel about it.  I found some reports that confirm a race between `udev` and `parted`, [like this one](https://bugzilla.redhat.com/show_bug.cgi?id=1283112). This can happen between separate parted calls, so it is recommended to combine multiple parted commands into a single parted call to create the correct partition layout in one pass without udev interfering.

And that's what this PR does. The change itself is a series of trivial rewrites. 
It should eliminate this particular cause of non-deterministic failure (but probably there are others, so don't expect zero failures from now on :smile:).

Relevant for ZHF #45960, please backport to 18.09

~WIP because I still like to run all the tests locally once, which will take some time.~ done

###### Things done

- [x] run all installer tests locally

---

### CODE REVIEW

**Comment by dezgeg** [comment]
I've noticed the races myself at some point as well: 
https://github.com/NixOS/nixpkgs/pull/40230#issuecomment-388513572

I have a fear that even after this a similar race condition exists. Namely, udev can still be holding the partition devices open during the time mkfs programs or mdadm are run and want to open the partition for exclusive access, leading to `Device or resource busy` errors. See e.g. this thread: https://groups.google.com/forum/#!topic/scylladb-dev/u87yHgo3ylU

**Comment by xeji** [comment]
It will be difficult to eliminate all causes of such races. Just looking at how they [tried to fix this in parted](http://git.savannah.gnu.org/cgit/parted.git/commit/?h=v3.2&id=0f850220b3f26bb969a1a7ff78dc550691a89566) by "sleep-and-retry" doesn't look promising.

Two things we can do to further reduce the probability of failure:

- Wrap each `parted` (and maybe also `mkfs` etc.) call with `flock /dev/vda parted ...` to acquire an exclusive lock on the device. That's what `util-linux` [recommends for `sfdisk`](https://github.com/karelzak/util-linux/blob/78686983e072bfd405c56fe18a45331dfedaeeef/disk-utils/sfdisk.8#L71). Doesn't work with `device-mapper` devices like `md` though.

-  For the swraid test which is the only one using `mdadm`, disable udev queue execution with `udevadm control --stop-exec-queue` like mentioned in the google groups thread above.

**Comment by xeji** [comment]
We could also protect all calls to `mkfs/mkswap` in a similar way but I don't recall seeing these fail in our tests yet, so let's fix those failures when they happen.

**Comment by xeji** [comment]
Example data point: In the [latest 18.09 Hydra eval](https://hydra.nixos.org/build/81815038#tabs-constituents) there are 5 installer test failures blocking the channel, and all of them show the kind of error addressed by this PR. So these changes can really improve things.

**Comment by xeji** [comment]
backported:  35271fdb2fd..570ec19f391

**Pull request merged**
