### PR TITLE
MongoDB Tools and Go dependencies

### PR DESCRIPTION
**Pull request by mschristiansen**
Added the MongoDB tools and build dependencies.

@lethalman TODO: Rename build output to tool names.

### CODE REVIEW

**Comment by lethalman** [comment]
```
  buildPhase = ''
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongooplog; do
      echo Building $i
      go build -o go/bin/$i go/src/${goPackagePath}/$i/main/$i.go
    done
  '';
```

**Comment by lethalman** [comment]
Don't open a new PR when rebasing, you can force push your changes.

**Comment by mschristiansen** [comment]
Ok, thanks for the buildPhase code. Anything holding this back now?

**Comment by lethalman** [comment]
@mschristiansen I don't see any changes to your commits, your forgot to push?

**Comment by mschristiansen** [comment]
Sorry, this should now be it. Builds with Go v1.4., but not v1.3.

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
