### PR TITLE
python3Packages.kneed: init at 0.8.3

### PR DESCRIPTION
**Pull request by tm-drtina**
###### Description of changes
https://github.com/arvkevi/kneed

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 232086` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.kneed</li>
    <li>python310Packages.kneed.dist</li>
    <li>python311Packages.kneed</li>
    <li>python311Packages.kneed.dist</li>
  </ul>
</details>

**Comment by Janik-Haag** [comment]
Trying to import the kneed fails :( 
```
[nix-shell:~/.cache/nixpkgs-review/pr-232086]$ python3
Python 3.10.11 (main, Apr  4 2023, 22:10:32) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kneed
Traceback (most recent call last):
  File "/nix/store/yj4zv3jnklkmmwzmv72iqvfpnspkwk2k-python3.11-numpy-1.24.2/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/nix/store/yj4zv3jnklkmmwzmv72iqvfpnspkwk2k-python3.11-numpy-1.24.2/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/nix/store/yj4zv3jnklkmmwzmv72iqvfpnspkwk2k-python3.11-numpy-1.24.2/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/awh1zkxvn3xv3s7ax5m1smj45cy5pp4m-python3.11-kneed-0.8.3/lib/python3.11/site-packages/kneed/__init__.py", line 1, in <module>
    from .data_generator import DataGenerator
  File "/nix/store/awh1zkxvn3xv3s7ax5m1smj45cy5pp4m-python3.11-kneed-0.8.3/lib/python3.11/site-packages/kneed/data_generator.py", line 1, in <module>
    import numpy as np
  File "/nix/store/yj4zv3jnklkmmwzmv72iqvfpnspkwk2k-python3.11-numpy-1.24.2/lib/python3.11/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/nix/store/yj4zv3jnklkmmwzmv72iqvfpnspkwk2k-python3.11-numpy-1.24.2/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/bin/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Review by Janik-Haag — COMMENTED** [review]
Your other pr #232080 will probably get merged first, so as soon as it's merged you should rebase this pr and remove your maintainer init because defining it twice will lead to build errors.

**Comment by tm-drtina** [comment]
I can reproduce it on python3.10, works fine with python3.11.

When I start python3.10 it uses packages compiled for python3.11 (as seen in the log). Not sure if that is nix-review issue or an actual issue.

**Comment by tm-drtina** [comment]
Tested with nix-shell and imports work 🤷‍♂️ 

```
$ nix-shell -p 'python310.withPackages (ps: [ps.kneed])' -I nixpkgs=. --run 'python3 -c "import kneed; print(kneed.__version__)"'
0.8.3
$ nix-shell -p 'python311.withPackages (ps: [ps.kneed])' -I nixpkgs=. --run 'python3 -c "import kneed; print(kneed.__version__)"'
0.8.3
```

So I guess the actual issue is with nixpkgs-review shell

**Review by Janik-Haag — APPROVED** [review]
Everything looks fine except for the wired nixpkgs-review behavior.

**Comment by tm-drtina** [comment]
The nixpkgs-review shell explicitly sets PYTHONPATH to 3.11 packages 😕 

```
[nix-shell:~/.cache/nixpkgs-review/pr-232086-1]$ env | grep -E '^PYTHON'
PYTHONNOUSERSITE=1
PYTHONHASHSEED=0
PYTHONPATH=/nix/store/awh1zkxvn3xv3s7ax5m1smj45cy5pp4m-python3.11-kneed-0.8.3/lib/python3.11/site-packages:/nix/store/yj4zv3jnklkmmwzmv72iqvfpnspkwk2k-python3.11-numpy-1.24.2/lib/python3.11/site-packages:/nix/store/r7wqbdnn0af1s1p23n18pxf70crqqakg-python3-3.11.3/lib/python3.11/site-packages:/nix/store/kxjiwi815m4y8i6rhx9mla779qh9xgmq-python3.11-scipy-1.10.1/lib/python3.11/site-packages
```

so it makes sense that python3.10 is broken in that shell

**Comment by tm-drtina** [comment]
Looks like it is an open issue https://github.com/Mic92/nixpkgs-review/issues/194

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
please rebase

**Comment by SuperSandro2000** [comment]
@ofborg build python310Packages.kneed

**Pull request merged**
