### PR TITLE
 warp-terminal: 0.2024.04.16.08.02.stable_00 -> 0.2024.05.07.08.02.stable_02

### LINKED ISSUE #309938: warp-terminal: crash when opening on wayland
### Describe the bug
When I try to open the warp-terminal on wayland it crashes without opening any window and get the following logs:

```console
➜  ~ warp-terminal
/nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/nwsbnbj4xgfq2x45df9xg2b77953h2zz-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp)
21:34:28 [INFO] Spawning terminal server process...
21:34:28 [INFO] Running app with windowing system: Wayland
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:164:14:
should be able to create event loop: Os(OsError { line: 80, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
21:34:28 [INFO] Received empty message; assuming the connection has been closed.
➜  ~
```

### Steps To Reproduce
1. try to open warp-terminal
2. nothing happens

### Expected behavior
It should open the warp-terminal window and prompt.

### Notify maintainers

@angustrau @Enzime @imadnyc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05pre621993.25865a40d14b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 4evy**
## Description of changes

Fixes: https://github.com/NixOS/nixpkgs/issues/309938

Changelog: https://docs.warp.dev/getting-started/changelog#id-2024.05.02-v0.2024.04.30.08.02

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by imadnyc — APPROVED** [review]

**Review by JohnRTitor — APPROVED** [review]
LTGM, can you also update the commit messages to include "linux"/"darwin", so its more clear?

**Comment by imadnyc** [comment]
Could we squash the two hash commits into one?

**Comment by Mjb141** [comment]
Can this one receive some love and attention, the current version is weeks old. Need new maintainers perhaps?

**Review by JohnRTitor — APPROVED** [review]
Result of `nixpkgs-review pr 308877` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>warp-terminal</li>
  </ul>
</details>

**Comment by annaleeleaves** [comment]
> Can this one receive some love and attention, the current version is weeks old. Need new maintainers perhaps?

note that someone with the commit privileges needs to merge this change.

however, if the update bot `r-ryantm` submits the PR, any maintainer should be able to merge the change  using the merge-bot: https://github.com/NixOS/nixpkgs-merge-bot

also note that `r-ryantm` will not submit a PR to update if one is already open.

**Review by ghost — APPROVED** [review]

**Comment by JohnRTitor** [comment]
Will backport this.

**Pull request merged**
