### PR TITLE
obsidian: update hash

### PR DESCRIPTION
**Pull request by nyanotech**
## Description of changes

I don't know why, but it looks like they updated the linux builds on [the existing 1.6.3 release](https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.6.3) about an hour before i'm writing this.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by kashw2 — APPROVED** [review]
WFM, Thanks for the fix :smiley:

**Review by w-lfchen — APPROVED** [review]
darwin hash has seemingly not changed, weird
maybe this has something to do with [the alpha electron 30 version](https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.6.3-e30) being released?

**Comment by nyanotech** [comment]
one of their discord mods says 

> I'd guess part of it is https://forum.obsidian.md/t/snap-package-does-not-work-on-kubuntu-24-04-lts-after-update-to-version-1-6-2/83202

¯\\\_(ツ)\_/¯

**Comment by cig0** [comment]
Thanks for taking care of this!

**Review by IntentionalEntropy — COMMENTED** [review]
After this change a rebuild fails with hash mismatch for me on NixOS.

error: hash mismatch in fixed-output derivation '/nix/store/2z34q335crhssa2qjh3jf316wg2p9a1n-obsidian-1.6.3.tar.gz.drv':
         specified: sha256-okN5e2jvDgTlMX6Ut11eiEQtXxl18bD7nZvTEeO/Rsw=
            got:    sha256-ho8E2Iq+s/w8NjmxzZo/y5aj3MNgbyvIGjk3nSKPLDw=
error: 1 dependencies of derivation '/nix/store/kxlf9a2kbhbyh26p8ilyb51cflprzh4f-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9q75yl7lxq58aq0s4bqi2raf35ysgf7z-nixos-system-nixos-24.11pre637149.c7b821ba2e1e.drv' failed to build

When I manually wget obsidian-1.6.3.tar.gz and then hash it:
sha256sum = 868f04d88abeb3fc3c3639b1cd9a3fcb96a3dcc3606f2bc81a39379d228f2c3c
base32 =  0g1ciwi9sdrr3b42nvv0qgfa75nb7ydcvc9r6qygrcxyibc093w6

**Comment by w-lfchen** [comment]
> specified: sha256-okN5e2jvDgTlMX6Ut11eiEQtXxl18bD7nZvTEeO/Rsw=

@s2514 you are not building off of this commit since this changes the hash to `sha256-ho8E2Iq+s/w8NjmxzZo/y5aj3MNgbyvIGjk3nSKPLDw=`, which is the correct one, as can be observed from you error message:
>  got: sha256-ho8E2Iq+s/w8NjmxzZo/y5aj3MNgbyvIGjk3nSKPLDw=

**Comment by nyanotech** [comment]
Also, I don't think `sha256-okN5e2jvDgTlMX6Ut11eiEQtXxl18bD7nZvTEeO/Rsw=` was specified in any version of this in nixpkgs

**Comment by s2514** [comment]
I am really new to NixOS and programming in general so sorry if I am being stupid here.

when I put:

  environment.systemPackages = [
    pkgs.obsidian
  ];

In my configuration.nix it used to build without issue but after this commit last night I couldn't rebuild.  If I remove obsidian from my systemPackages it builds without issue. I am trying to figure out how to get it to build again any help would be greatly appreciated.

**Comment by cig0** [comment]
Hey @s2514, take a look at https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/applications/misc/obsidian/default.nix#L28 -- it has the correct hash for `x86_64-linux`. We need to wait until the CI pipeline finishes, and if everything's okay, it will be merged into `master` shortly after.

There are many strategies to a) minimize this from happening in the future and b) workaround the issue you have right now so you can go on with your life :)

I assume you're following the `nixos-unstable` release channel and using the default `configuration.nix` configuration file since you told us you are new to NixOS.

Check this fragment below:
```nix
{ config, pkgs, ... }:

let
  # Overlay to fetch and pin a specific commit of Nixpkgs
  pinnedOverlay = final: prev: {
    pinnedPkgs = import (fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/nixos-24.05.tar.gz";
    }) { config = {}; };

    # Override the package with the specific version
    obsidian = pinnedPkgs.obsidian;
  };
in
{
  # Add the overlay
  nixpkgs.overlays = [ pinnedOverlay ];

  # Use the overridden package
  environment.systemPackages = with pkgs; [
    ... # Your other packages
    pkgs.obsidian
  ];
}
```

What we are doing here is creating an overlay for the Obsidian package. Instead of looking for it on the `nixpkgs-unstable` release channel, we will pull it from the current stable release channel, `nixos-24.05`.

Now, try this for me:
1. Backup your `configuration.nix` file!
2. Add the block `let ... in` to your file, as shown above.
3. Create an overlay to replace the release channel for the Obsidian package.
4. Reference in the `nixpkgs.overlays` attribute the overlay we created.
5. Since you're already pointing to the Obsidian package as `pkgs.obsidian`, you don't need to do anything else.

Let's create a new generation: `nixos-rebuild switch --use-remote-sudo`. If everything goes well, you will end up with the Obsidian (installer) `v1.5.12`, pulled from the stable release channel :tada: 
You can still upgrade Obsidian to the latest version: `open Obsidian -> Settings -> Check for updates`.

**Please note** that I'm in a rush, and I haven't tried this, but it _should_ work :sweat_smile:

Remember to remove the overlay and its reference when the Obsidian package in `unstable` is updated. You can also start playing with that configuration; for example, by moving the overlay to its own module, you can import it later from the main configuration file.

But since we like doing things the right way, why not just move everything to a flake and empty that `/etc/nixos` directory!? :wink:

Feel free to contact me on Discourse (same handle) if you still have problems so we don't spam this issue.

**Pull request merged**
