### PR TITLE
python3Packages.astropy-extension-helpers: 0.1 -> 1.0.0

### PR DESCRIPTION
**Pull request by smaret**
###### Description of changes

Update astropy-extension-helpers to the latest upstream. This fixes the build on x86_64-darwin.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by smaret** [comment]
Result of `nixpkgs-review pr 167922` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python310Packages.asdf</li>
    <li>python310Packages.astroquery</li>
    <li>python310Packages.sunpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.astroquery</li>
    <li>python39Packages.sunpy</li>
  </ul>
</details>
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>python310Packages.aplpy</li>
    <li>python310Packages.astropy</li>
    <li>python310Packages.astropy-extension-helpers</li>
    <li>python310Packages.astropy-healpix</li>
    <li>python310Packages.casa-formats-io</li>
    <li>python310Packages.drms</li>
    <li>python310Packages.pyavm</li>
    <li>python310Packages.pyregion</li>
    <li>python310Packages.pytest-astropy</li>
    <li>python310Packages.pytest-astropy-header</li>
    <li>python310Packages.radio_beam</li>
    <li>python310Packages.reproject</li>
    <li>python310Packages.spectral-cube</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.astropy</li>
    <li>python39Packages.astropy-extension-helpers</li>
    <li>python39Packages.astropy-healpix</li>
    <li>python39Packages.casa-formats-io</li>
    <li>python39Packages.drms</li>
    <li>python39Packages.pyavm</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.radio_beam</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.spectral-cube</li>
  </ul>
</details>

**Comment by smaret** [comment]
The 3 packages failures are not related to this update.

**Review by rmcgibbo — APPROVED** [review]

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 167922` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python310Packages.asdf</li>
    <li>python310Packages.astroquery</li>
    <li>python310Packages.sunpy</li>
    <li>python39Packages.asdf</li>
    <li>python39Packages.astroquery</li>
    <li>python39Packages.sunpy</li>
  </ul>
</details>
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>python310Packages.aplpy</li>
    <li>python310Packages.astropy</li>
    <li>python310Packages.astropy-extension-helpers</li>
    <li>python310Packages.astropy-healpix</li>
    <li>python310Packages.casa-formats-io</li>
    <li>python310Packages.drms</li>
    <li>python310Packages.pyavm</li>
    <li>python310Packages.pyregion</li>
    <li>python310Packages.pytest-astropy</li>
    <li>python310Packages.pytest-astropy-header</li>
    <li>python310Packages.radio_beam</li>
    <li>python310Packages.reproject</li>
    <li>python310Packages.spectral-cube</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.astropy</li>
    <li>python39Packages.astropy-extension-helpers</li>
    <li>python39Packages.astropy-healpix</li>
    <li>python39Packages.casa-formats-io</li>
    <li>python39Packages.drms</li>
    <li>python39Packages.pyavm</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.radio_beam</li>
    <li>python39Packages.reproject</li>
    <li>python39Packages.spectral-cube</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Failures will be fixed with #168006 and #168048.

**Pull request merged**
