### PR TITLE
Auto-updated Gnome extensions using the update script.

### PR DESCRIPTION
**Pull request by alinanorakari**
Used the update-extensions script in pkgs/desktops/gnome/extensions to update extensions.json to the latest state since it has been 3 months out of date according to history and I was missing up-to-date versions for Gnome shell 46 of some of the extensions I rely on.

## Things done

none of the following apply really

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alinanorakari** [comment]
@jtojnar Hi. Do you think this auto update of the GNOME extensions can be considered for a merge? I think 3 months out of date extensions aren't a great look, especially with many that have since been updated to work with Gnome shell 46. I understand you are probably working on the upcoming stable release, perhaps you can consider merging these anyway.

**Comment by jtojnar** [comment]
Hi, we have already merged update in #333911

**Comment by alinanorakari** [comment]
Thank you. Would you still consider mregin this into master for current users of 46 who don't want to switch to 47 yet due to Extension incompatibilities?

**Comment by jtojnar** [comment]
I will leave up to @honnip as the maintainer if they want to deal with the conflict.

**Comment by honnip** [comment]
Sorry for late update. 

I believe this staging-next branch will be merged into master in few days, so I will not resolve the conflict manually.

@alinanorakari, we have `gnome46Extensions` package set. This would be better in that you'll get updates in the future.

**Comment by linsui** [comment]
https://github.com/NixOS/nixpkgs/pull/352798?

**Pull request closed without merging**
