### PR TITLE
gradle: 7.0 -> 7.1

### PR DESCRIPTION
**Pull request by liff**
###### Motivation for this change

[New Gradle release](https://docs.gradle.org/7.1/release-notes.html).

Not sure if separate `gradle_7_0` and `_7_1` attributes should be made available?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tricktron** [comment]
Result of `nixpkgs-review pr 128882` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gscan2pdf</li>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>scenic-view</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>gradle (gradle_7)</li>
    <li>jadx</li>
    <li>pdftk</li>
  </ul>
</details>

**Comment by liff** [comment]
I downloaded the [official binary distribution](https://gradle.org/releases/) and looked at the version of the included native-platform package files :)

The native platform has a [repository here](https://github.com/gradle/native-platform), which probably can tell you more about its purpose than I could.

It might be possible to be a bit cleverer about [this bit](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/development/tools/build-managers/gradle/default.nix#L33-L36) in such a way that it didn’t need to be told about the native version…

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128882` at ce426ba2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>gradle (gradle_7)</li>
    <li>gscan2pdf</li>
    <li>jadx</li>
    <li>pdftk</li>
    <li>scenic-view</li>
  </ul>
</details>

**Comment by tricktron** [comment]
Result of `nixpkgs-review pr 128882` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>diffoscope</li>
    <li>gradle (gradle_7)</li>
    <li>gscan2pdf</li>
    <li>jadx</li>
    <li>pdftk</li>
    <li>scenic-view</li>
  </ul>
</details>

@liff Thanks for the explanation.

**Comment by SuperSandro2000** [comment]
> Not sure if separate gradle_7_0 and _7_1 attributes should be made available?

I don't see a reason why we would need those. All packages continue to work with 7.1?

**Pull request merged**
