### PR TITLE
mangayomi: init at 0.1.61

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Related issue: https://github.com/NixOS/nixpkgs/issues/282266

This PR adds 1 package: `mangayomi`

This PR currently only supports `x86_64-linux`, as I am packaging the prebuilt binaries.

Packaging this was pretty similar to https://github.com/NixOS/nixpkgs/pull/282975

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nrabulinski** [comment]
Have you tried building it from source? If not, is that the same issue as in `spotube`?

**Comment by TomaSajt** [comment]
I tried and *almost* got it working ung yet-unused features in nixpkgs' dart support.
 However I couldn't get past one of the build steps, so I gave up. It's not at all out of the question, to build from source.

**Comment by nrabulinski** [comment]
Understood. Ideally we'd build from source if possible, and only turn to patching binaries as last resort. You can also open a draft PR with the package built from source which isn't yet building to possibly get help from people who have dealt with Dart already :)

**Comment by hacker1024** [comment]
I'm curious to see what the issue with one of the build steps is. If you have time to make a draft from-source PR, we'd very much appreciate it.

**Comment by TomaSajt** [comment]
> I'm curious to see what the issue with one of the build steps is. If you have time to make a draft from-source PR, we'd very much appreciate it. Hopefully we can get the Dart support to the point where anything can be built - I thought we were pretty much there already.

The main issue isn't with flutter/dart itself, but that fact that the `rinf` package is trying to interop with `rust`.

I have opened another PR

**Comment by TomaSajt** [comment]
I managed to build it from source, I'll continue in the other PR.

**Pull request closed without merging**
