### PR TITLE
kde-frameworks: 5.39 -> 5.40

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
Regular update.

@ttuegel @peterhoeg @adisbladis 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
I'm currently running ```nix-build nixos/tests/plasma5.nix``` against this.

**Comment by bkchr** [comment]
nox-review does not work for me. :( I just build it for my system.

**Comment by bkchr** [comment]
@peterhoeg did you found any problems?

**Comment by peterhoeg** [comment]
>   @peterhoeg did you found any problems?

I did - nox-review didn't finish due to heaptrack breaking but updating heaptrack as well at least allowed it to continue. I didn't get the chance to check after that though and will only be able to do so late tonight.

**Comment by disassembler** [comment]
If @peterhoeg approves the changes, this should be rebased on staging because of the number of rebuilds it causes.

**Comment by peterhoeg** [comment]
```nox-review``` is still failing here. I'll take a look tomorrow.

**Comment by bkchr** [comment]
I will push fixes for other packages that are affected by these changes to this pull request. After everything works, I will create new pull requests for these packages.

**Comment by bkchr** [comment]
Hmm, having again problems with digikam that it can not find gitversion.h

**Comment by bkchr** [comment]
Created a new pr for heaptrack: https://github.com/NixOS/nixpkgs/pull/31756

Nox-review worked now for me (building digikam 'manual' (nix-build))

**Comment by adisbladis** [comment]
`nox-review` passes and KDE is working fine :) 👍

**Comment by peterhoeg** [comment]
Please try to run ```nix-build nixos/tests/plasma5.nix```

**Comment by adisbladis** [comment]
@peterhoeg The tests are passing.

**Comment by orivej** [comment]
Thank you!

**Pull request merged**
