### PR TITLE
electron: Support updating electron-bin with update.py

### PR DESCRIPTION
**Pull request by yayayayaka**
## Description of changes
This PR extends the functionality of electron's update script by
- making it possible to update both binary and from source built releases.
- adding the `--source-only` and `--bin-only` options for limiting the
  update mechanism to source or binary releases.
- adding a `--commit` option to automatically commit the changes for
  you.
  
And since I have been updating electron for a while now, I am adding myself as maintainer.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
cc @yuka

**Comment by yayayayaka** [comment]
Marking as draft until I have integrated the switch to SRI hashes in chromium.

**Comment by yayayayaka** [comment]
Rebased. Update script still updating :)

**Review by yu-re-ka — APPROVED** [review]
I haven't looked at the update script changes in detail, but I approve of the idea

**Comment by yayayayaka** [comment]
Need to resolve the conflicts....

**Comment by yayayayaka** [comment]
Resolved the merge conflict. It was mostly just the outdated info.json.

`--commit` now adds all mentioned CVE numbers found in the release note to the commit message.

Since I am the only electron(-source) maintainer left at the moment, I am going to self-merge this one soon.

**Comment by yayayayaka** [comment]
Result of `nixpkgs-review pr 262136` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
