### PR TITLE
fleet: Update configuration generation.

### PR DESCRIPTION
**Pull request by kevincox**

### CODE REVIEW

**Comment by garbas** [comment]
@kevincox tnx!

**Comment by kevincox** [comment]
@garbas Thanks for merging however it looks like you missed the second commit which fixes a typo.

**Comment by garbas** [comment]
@kevincox both commits are in master: https://github.com/NixOS/nixpkgs/commit/d038464e6e6ed526ead07944395053b71531628f and https://github.com/NixOS/nixpkgs/commit/a2fb70b6dfad623f0bdacd1768659db4eac58c98

**Comment by kevincox** [comment]
@garbas Oh yes you are right, sorry. I was confused by github's UI.

**Pull request closed without merging**
