### PR TITLE
doc: include nixdoc for `lib.fetchers`

### PR DESCRIPTION
**Pull request by nicoonoclaste**
Add `lib.fetchers` to the `libset` in `lib-function-docs.nix`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] `nix-build doc`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hsjobeki** [comment]
I'll have a look.

**Comment by hsjobeki** [comment]
@GetPsyched It seems this is caused because of a missing entry in `redirects.json`
 
 @nbraud
 
  Steps to fix this
  
  - Remove the anchor from the description:
  `description = "functions which can be reused across fetchers`
  
  - Init a new anchor in the `redirects.json`
  ```json
    "sec-functions-library-fetchers": [
    "index.html#sec-functions-library-fetchers"
  ]
  ```
  
  It seems anchors cannot be used in the description.
  
  If you need more introduction sentences or links you should be able to add them to: /lib/fetchers.nix. (see lib/attrsets.nix for example)

**Comment by hsjobeki** [comment]
@GetPsyched.

I just found another bug.

Feeding this markdown file causes nrd to never terminate.

```md
# Heading{#1}

## heading [link](#somewhere) {#id}
```

**Comment by fricklerhandwerk** [comment]
Oof. Thanks for investigating @hsjobeki!

**Review by hsjobeki — APPROVED** [review]

**Pull request merged**
