### PR TITLE
snakemake: 8.0.1 -> 8.2.1

### PR DESCRIPTION
**Pull request by veprbl**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 280332` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>snakemake</li>
    <li>snakemake.dist</li>
  </ul>
</details>

**Comment by risicle** [comment]
Hmm

```
error: hash mismatch in fixed-output derivation '/nix/store/wpg1nxpqgvn8risk1rlxc03s2di62lsl-source.drv':
         specified: sha256-iP7CIpBCbXBzycYJ4nh5qXfKUt37U5HoeaEoZXSHWc8=
            got:    sha256-NhSLCZTd7+8OBb2YXbQ4rAUK/mYD/XTXEbgv45/plkE=
```

Have they updated the tag?

**Comment by kirillrdy** [comment]
> Hmm
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/wpg1nxpqgvn8risk1rlxc03s2di62lsl-source.drv':
>          specified: sha256-iP7CIpBCbXBzycYJ4nh5qXfKUt37U5HoeaEoZXSHWc8=
>             got:    sha256-NhSLCZTd7+8OBb2YXbQ4rAUK/mYD/XTXEbgv45/plkE=
> ```
> 
> Have they updated the tag?

i get same 

```
error: hash mismatch in fixed-output derivation '/nix/store/wpg1nxpqgvn8risk1rlxc03s2di62lsl-source.drv':
         specified: sha256-iP7CIpBCbXBzycYJ4nh5qXfKUt37U5HoeaEoZXSHWc8=
            got:    sha256-NhSLCZTd7+8OBb2YXbQ4rAUK/mYD/XTXEbgv45/plkE=
```

**Comment by veprbl** [comment]
```diff
diff -aru /nix/store/5n652pdgnymxd4rpkm4ajmxkbl3bb6ja-source/snakemake/_version.py /nix/store/m2iwb0cwy472bgzksrwjr9axghxmbhyv-source/snakemake/_version.py
--- /nix/store/5n652pdgnymxd4rpkm4ajmxkbl3bb6ja-source/snakemake/_version.py	1969-12-31 19:00:01.000000000 -0500
+++ /nix/store/m2iwb0cwy472bgzksrwjr9axghxmbhyv-source/snakemake/_version.py	1969-12-31 19:00:01.000000000 -0500
@@ -25,7 +25,7 @@
     # setup.py/versioneer.py will grep for the variable names, so they must
     # each be defined on a line of their own. _version.py will just call
     # get_keywords().
-    git_refnames = " (HEAD -> main, tag: v8.1.1)"
+    git_refnames = " (tag: v8.1.1)"
     git_full = "551cba1eb121bbafaf04c296e7c6863bb354bd89"
     git_date = "2024-01-11 12:23:59 +0100"
     keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}
```

https://github.com/snakemake/snakemake/blob/main/snakemake/_version.py
https://github.com/python-versioneer/python-versioneer/blob/master/_version.py
https://github.com/python-versioneer/python-versioneer/issues/217

**Pull request merged**
