### PR TITLE
buildMozillaMach: icu and distutils build fixes

### PR DESCRIPTION
**Pull request by mweinelt**
Pending https://bugzilla.mozilla.org/show_bug.cgi?id=1862601 and https://bugzilla.mozilla.org/show_bug.cgi?id=1743785

Tested the icu change for 127, not yet the distutils change for 115.

cc #322145 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
```
afdko-aarch64-linux> FAILED tests/proofpdf_test.py::test_glyphs_2_7[waterfallplot-font.otf] - AssertionError: assert False
afdko-aarch64-linux> FAILED tests/proofpdf_test.py::test_hinting_data[waterfallplot-font_noHints.otf] - AssertionError: assert False
afdko-aarch64-linux> FAILED tests/proofpdf_test.py::test_hinting_data[waterfallplot-font_noStems.otf] - AssertionError: assert False
afdko-aarch64-linux> FAILED tests/proofpdf_test.py::test_waterfallplot[SourceSansPro-Black] - AssertionError: assert False
afdko-aarch64-linux> FAILED tests/proofpdf_test.py::test_waterfallplot[SourceSansPro-BlackIt] - AssertionError: assert False
afdko-aarch64-linux> = 5 failed, 1204 passed, 6 skipped, 332 deselected, 8 xfailed, 4656 warnings in 222.53s (0:03:42) =

**Comment by vcunat** [comment]
Why did you drop the patch for ICU-22132?  I looked at the linked bug reports and noticed no mention of that one being resolved (in other way than applying that patch).

**Comment by vcunat** [comment]
`firefox-esr` doesn't build for me with this PR:
```
 1:22.31 make: Leaving directory '/build/firefox-115.12.0/objdir'
Running "pip check" to verify compatibility between the system Python and the "mach" site.
Running "pip check" to verify compatibility between the system Python and the "common" site.
Site not up-to-date reason: "/build/firefox-115.12.0/objdir/_virtualenvs/common" does not exist
Traceback (most recent call last):
  File "/build/firefox-115.12.0/./build/pgo/profileserver.py", line 19, in <module>
    from mozrunner import CLI, FirefoxRunner
  File "/build/firefox-115.12.0/testing/mozbase/mozrunner/mozrunner/__init__.py", line 6, in <module>
    import mozrunner.base
  File "/build/firefox-115.12.0/testing/mozbase/mozrunner/mozrunner/base/__init__.py", line 6, in <module>
    from .browser import BlinkRuntimeRunner, GeckoRuntimeRunner
  File "/build/firefox-115.12.0/testing/mozbase/mozrunner/mozrunner/base/browser.py", line 11, in <module>
    from ..application import DefaultContext, FirefoxContext
  File "/build/firefox-115.12.0/testing/mozbase/mozrunner/mozrunner/application.py", line 8, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

**Comment by mweinelt** [comment]
> Why did you drop the patch for ICU-22132? I looked at the linked bug reports and noticed no mention of that one being resolved (in other way than applying that patch).

Restored. Just say the Mozbz issue was closed after version 107.

**Comment by vcunat** [comment]
Not sure why, but `firefox-esr` still fails to find distutils.

**Comment by vcunat** [comment]
I merged the working parts, so that we have `firefox` and `thundebird` already.

**Pull request closed without merging**
