### PR TITLE
alt-ergo: 1.30->2.2.0, ocplib-simplex: 0.3->0.4

### PR DESCRIPTION
**Pull request by cocreature**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
The `meta.license` field of `alt-ergo` claims CÉCILL-C. Is that true?

**Comment by cocreature** [comment]
@vbgl Good catch! I missed that they updated the license. I’ve now changed it to properly reflect the current license.

**Comment by vbgl** [comment]
That’s a bit annoying to “update” to a non-free version. Moreover, they did mention that there should be a free version of Alt-Ergo 2 (https://lists.gforge.inria.fr/pipermail/why3-club/2017-November/001611.html).

**Comment by cocreature** [comment]
So how do we move forward here? That comment is about a year old, alt-ergo 2.0 has been released almost a year ago, alt-ergo 2.2 has been released in April and afaik there is still no free version. I’m not really fond of sticking with an old version forever in the hopes that at some point we might be able to upgrade it. I suppose another option would be to keep both 1.3 and 2.0 around but I doubt that alt-ergo is sufficiently popular to justify that.

**Comment by vbgl** [comment]
I’m convinced. Let’s acknowledge that Alt-Ergo is no longer free.

Can you please remove the overriding of `ocamlPackages` when calling the alt-ergo package in `all-packages.nix`? I think `num` is also missing from its build-inputs.

Also, what is the purpose of the patch? It seems enough to set `installFlags = "LIBDIR=$(OCAMLFIND_DESTDIR)";`.

**Comment by cocreature** [comment]
I’ve removed the patch (thanks for pointing this out, I wasn’t aware that you could override variables like that), removed the override and added `num` to the build-inputs.

**Comment by vbgl** [comment]
@GrahamcOfBorg build alt-ergo

**Comment by vbgl** [comment]
Merged as 6738033727ca7945f1465ad76492891489e133ce.

**Pull request closed without merging**
