### PR TITLE
Update nginx modules

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update nginx modules

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
Thanks! Please use the prefix `nginxModules.ipscrub: ` for the commit messages.

**Comment by fpletz** [comment]
Tested building all of the modules.

The `moreheaders` doesn't seem to work for both stable and mainline nginx versions though:

```
objs/addon/src/ngx_http_headers_more_filter_module.o:(.bss+0x0): multiple definition of `ngx_http_headers_more_location_hash'
objs/addon/src/ngx_http_headers_more_filter_module.o:(.bss+0x0): first defined here
objs/addon/src/ngx_http_headers_more_filter_module.o:(.data.rel.local+0x0): multiple definition of `ngx_http_headers_more_filter_module'
objs/addon/src/ngx_http_headers_more_filter_module.o:(.data.rel.local+0x0): first defined here
objs/addon/src/ngx_http_headers_more_headers_out.o: In function `ngx_http_headers_more_exec_cmd':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_out.c:112: multiple definition of `ngx_http_headers_more_exec_cmd'
objs/addon/src/ngx_http_headers_more_headers_out.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_out.c:112: first defined here
objs/addon/src/ngx_http_headers_more_headers_out.o: In function `ngx_http_headers_more_set_headers':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_out.c:500: multiple definition of `ngx_http_headers_more_set_headers'
objs/addon/src/ngx_http_headers_more_headers_out.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_out.c:500: first defined here
objs/addon/src/ngx_http_headers_more_headers_out.o: In function `ngx_http_headers_more_clear_headers':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_out.c:509: multiple definition of `ngx_http_headers_more_clear_headers'
objs/addon/src/ngx_http_headers_more_headers_out.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_out.c:509: first defined here
objs/addon/src/ngx_http_headers_more_headers_in.o: In function `ngx_http_headers_more_exec_input_cmd':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_in.c:172: multiple definition of `ngx_http_headers_more_exec_input_cmd'
objs/addon/src/ngx_http_headers_more_headers_in.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_in.c:172: first defined here
objs/addon/src/ngx_http_headers_more_headers_in.o: In function `ngx_http_headers_more_set_input_headers':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_in.c:462: multiple definition of `ngx_http_headers_more_set_input_headers'
objs/addon/src/ngx_http_headers_more_headers_in.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_in.c:462: first defined here
objs/addon/src/ngx_http_headers_more_headers_in.o: In function `ngx_http_headers_more_clear_input_headers':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_in.c:471: multiple definition of `ngx_http_headers_more_clear_input_headers'
objs/addon/src/ngx_http_headers_more_headers_in.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_headers_in.c:471: first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_parse_header':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:22: multiple definition of `ngx_http_headers_more_parse_header'
objs/addon/src/ngx_http_headers_more_util.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:22: first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_parse_statuses':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:164: multiple definition of `ngx_http_headers_more_parse_statuses'
objs/addon/src/ngx_http_headers_more_util.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:164: first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_parse_types':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:229: multiple definition of `ngx_http_headers_more_parse_types'
objs/addon/src/ngx_http_headers_more_util.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:229: first defined here
objs/addon/src/ngx_http_headers_more_util.o: In function `ngx_http_headers_more_rm_header_helper':
/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:268: multiple definition of `ngx_http_headers_more_rm_header_helper'
objs/addon/src/ngx_http_headers_more_util.o:/nix/store/jsqrk045m09i136mgcfjfai8i05nq14c-source/src/ngx_http_headers_more_util.c:268: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:396: objs/nginx] Error 1
make[1]: Leaving directory '/build/nginx-1.13.12'
make: *** [Makefile:8: build] Error 2
builder for '/nix/store/23q4dyyjhi927ahd2plr972vq2flaylp-nginx-1.13.12.drv' failed with exit code 2
```

**Comment by Izorkin** [comment]
Normal build
```
nox-review pr 43580
=== Reviewing PR 43580 : Update nginx modules
==> We're in a git repo, trying to fetch it
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
Автослияние pkgs/servers/http/nginx/modules.nix
Building in /run/user/1737/nox-review-2wghx5h_: nginxMainline nginxUnstable nginx devpi-client devpi-server nginxShibboleth
Invoking nix-build -A nginxMainline -A nginxUnstable -A nginx -A devpi-client -A devpi-server -A nginxShibboleth /home/lf/.nox/nixpkgs
/nix/store/c0z6hdm1vw3nhbznkpalniv8bjwc2nh9-nginx-1.15.1
/nix/store/c0z6hdm1vw3nhbznkpalniv8bjwc2nh9-nginx-1.15.1
/nix/store/ji8408na4br9np56j12pa208hlyslf9x-nginx-1.14.0
/nix/store/rz7137ylhimcp5v52p0qshqpdq2q5fan-devpi-client-3.1.0
/nix/store/sxjqxfxv6f6ccsw32f2pfski8l9hiwhw-devpi-server-4.4.0
/nix/store/xczawcvj0z4shg2scyhhsqj5lxpsmgz4-nginx-1.14.0
Result in /run/user/1737/nox-review-2wghx5h_
итого 0
lrwxrwxrwx 1 lf lf 56 июл 16 00:29 result -> /nix/store/c0z6hdm1vw3nhbznkpalniv8bjwc2nh9-nginx-1.15.1
lrwxrwxrwx 1 lf lf 56 июл 16 00:29 result-2 -> /nix/store/ji8408na4br9np56j12pa208hlyslf9x-nginx-1.14.0
lrwxrwxrwx 1 lf lf 62 июл 16 00:29 result-3 -> /nix/store/rz7137ylhimcp5v52p0qshqpdq2q5fan-devpi-client-3.1.0
lrwxrwxrwx 1 lf lf 62 июл 16 00:29 result-4 -> /nix/store/sxjqxfxv6f6ccsw32f2pfski8l9hiwhw-devpi-server-4.4.0
lrwxrwxrwx 1 lf lf 56 июл 16 00:29 result-5 -> /nix/store/xczawcvj0z4shg2scyhhsqj5lxpsmgz4-nginx-1.14.0

```

**Comment by Izorkin** [comment]
cc @fpletz 
Builded with modules -  
```
    modules = [
      nginxModules.rtmp
      nginxModules.dav
      nginxModules.moreheaders
      nginxModules.ipscrub
      nginxModules.lua
      nginxModules.develkit
      nginxModules.set-misc
      nginxModules.pam
      nginxModules.sla
      nginxModules.fancyindex
      nginxModules.statsd
      nginxModules.upstream-check
    ];
```
nix-build -A nginxMainline -A nginxUnstable -A nginx -A ~/.nox/nixpkgs
```
make[1]: Leaving directory '/tmp/nix-build-nginx-1.15.1.drv-0/nginx-1.15.1'
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1
patching script interpreter paths in /nix/store/zi1wilfd9a7nxl89d32vdlak7n2jdjx1-nginx-1.14.0
checking for references to /tmp/nix-build-nginx-1.14.0.drv-0 in /nix/store/zi1wilfd9a7nxl89d32vdlak7n2jdjx1-nginx-1.14.0...
shrinking /nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1/bin/nginx
strip is /nix/store/4qvrxzxa535y8304mk195x50b6p9607d-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1/bin
patching script interpreter paths in /nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1
checking for references to /tmp/nix-build-nginx-1.15.1.drv-0 in /nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1...
/nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1
/nix/store/k3fh6038g3s890i99hp87i8jkrdybg5b-nginx-1.15.1
/nix/store/zi1wilfd9a7nxl89d32vdlak7n2jdjx1-nginx-1.14.0
/nix/store/xczawcvj0z4shg2scyhhsqj5lxpsmgz4-nginx-1.14.0

```

**Comment by fpletz** [comment]
Ah, sorry, I actually listed `moreheaders` in the `modules` list two times (used override).

Looks fine, thanks! :+1:

**Pull request merged**
