### PR TITLE
[20.03] nautilus: 3.34.2 -> 3.34.3

### PR DESCRIPTION
**Pull request by dasj19**
###### Motivation for this change
Updated the package as promised https://github.com/NixOS/nixpkgs/issues/89542#issuecomment-657493466

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
See also https://github.com/NixOS/nixpkgs/pull/85974 – unfortunately stable branches are understaffed.

**Comment by dasj19** [comment]
@jtojnar Okay I see a huge update coming... wouldn't it be better to release smaller packages as we do in unstable ?

**Comment by jtojnar** [comment]
We usually group them in unstable too, since there are many packages released at approximately the same time.

https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+gnome+updates+staging+is%3Amerged+

For new major releases, we typically do a single mega-update since packages often depend on each other.

For point releases, where there are usually only non-breaking changes, we settled up on making two pull requests, one for master and one for staging to maximize update speed and minimize the effort. (https://github.com/NixOS/nixpkgs/issues/57609 can help a lot)

When we are busy @r-ryantm, makes an update before we do and it only [currently](https://github.com/ryantm/nixpkgs-update/issues/29) supports one pull request per update. This works for point releases, but when a new major release is approaching, we need to [blacklist](https://github.com/ryantm/nixpkgs-update/commit/639f5007cf43e2fed277cd79fa1d5a34b812611a) GNOME updates in the bot.

**Comment by flokli** [comment]
This seems to fix https://github.com/NixOS/nixpkgs/issues/89542 in stable without too much fuzz.

**Pull request merged**
