### PR TITLE
Add EventStore package

### PR DESCRIPTION
**Pull request by puffnfresh**
This also paramerises the V8 expression so that we can build with the required version.

---

https://geteventstore.com/

Would love to get feedback to see if this is an appropriate approach. I didn't want to duplicate the V8 expression since it compiles fine just with a different version and src.

Should we have a top-level `v8_3_24_10` attribute?

### CODE REVIEW

**Comment by puffnfresh** [comment]
This will conflict with #7739.

**Comment by codyopel** [comment]
Passing versions to the build is a bad way to handle this. It would be better to refactor v8 to use a generic build, or have a seperate build for each version.  Doing it the way you set it up, if some one makes changes to the v8 build it makes it hard to tell what arbitrary versions are being passed to the build other than the version defined in the build itself making it very easy to break build without knowing that you did.

**Comment by puffnfresh** [comment]
@codyopel that makes sense. How would I create a generic build for V8? I want to reduce code duplication, since this version seems to have the exact same build process.

**Comment by codyopel** [comment]
This is a simple example of a generic expression:
https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/botan

**Comment by jagajaga** [comment]
@puffnfresh, @codyopel is right. Please make separate versions of `v8`. Generic version is close to what you have now, I think.

**Comment by puffnfresh** [comment]
@codyopel @jagajaga does 057bd5726c5cc6c0fe9c04578faa8e66b6c778f3 turn it into a proper generic build?

**Comment by jagajaga** [comment]
Can you squash commits?

And you tested? (To be sure)

**Comment by puffnfresh** [comment]
@jagajaga squashed and rebased onto master.

I now had to include a patch since master just got upgraded to Mono 4 and EventStore incorrectly would detect it as Mono 2 and refuse to start.

I've tested that v8 doesn't even rebuild; and that both v8_3_24_10 and eventstore seem to work.

**Comment by codyopel** [comment]
Nice, I'll rebase the v8 fixes I had on top of the generic

**Pull request merged**
