### PR TITLE
lua: std._debug / std.normalize rename + move to automated.

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
see the commit message: Having a dot in the name prevents some changes to the lua infrastructure.
I also fixed a problem with the lua updater.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Do we want to have a std.debug attribute manually inserted that throws a warning about rename?

**Comment by teto** [comment]
it's a pretty new package with no dependency so I think that's fine. Or do you mean for package discovery ? a search on the name or a grep in nixpkgs should be enough

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.std__debug luaPackages.std_normalize

**Comment by 7c6f434c** [comment]
I meant to warn if someone uses the package (automatic reaction to renames), but maybe it is indeed new enough for people who knew it existed also keep track of your work on Lua support in Nixpkgs.

**Comment by teto** [comment]
as usual darwin fails which is kinda annoying as I don't get why this would behave differently than other apart from a luarocks bug ?
Maybe @LnL7 if you have some time, you can use your magic as you did in https://github.com/NixOS/nixpkgs/pull/55580 :)

**Comment by LnL7** [comment]
Not sure why it fails, but adding `preInstall = '' mkdir $out '';` seems to work.

FYI. there's a bunch of whitespace in generated-packages.nix

**Comment by 7c6f434c** [comment]
Re: whitespace — if packages were separated by empty lines, I would just say that whitespace improves human readability (having generated code readable is still good); as-is there is probably some space for improvement…

**Comment by LnL7** [comment]
I was referring to the trailing whitespace specifically.

**Comment by teto** [comment]
@LnL7 thanks for having a look at this. Strange that it happens only on darwin.
I've open an issue with https://github.com/luarocks/luarocks/issues/988
seems like a luarocks bug then if it expects a folder it doesn't create.

I don't follow the stable release but I think the first commit "fix version pinning" could be backported
https://github.com/NixOS/nixpkgs/pull/57945/commits/01e193b220ace2550e8b7bea6106d72f2cab6e12

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by teto** [comment]
I looked a bit into it and I think in the short term, just creating the directory is the best fix. I wonder if the luarocks check is correct or what happens during the installPhase 

The proposed alternative is to rework the buildLuarocks function to create a rock from a rockspec and then install it. While I like the split between build and install, it means compressing then uncompressing what we just compressed. So I will wait for an alternative that doesn't involve these unnecessary steps.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.std__debug luaPackages.std_normalize

**Comment by teto** [comment]
Luarocks checks that /nix/store is writable before writing (which fails on darwin but not on linux).
Thanks to sphalerite on irc, I believe the difference in behavior for luarocks + nix might stem from https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L2871-L2876 . I put it here as a reminder. I hope a darwin user can dig into this so that we can fix the luarocks check or the nix darwin path.

**Comment by teto** [comment]
@GrahamcOfBorg build luaPackages.std__debug luaPackages.std_normalize

**Comment by teto** [comment]
@7c6f434c everything passes. Hopefully the darwin fix (creating the folder) could unblock other Lua PRs.

**Pull request merged**
