### PR TITLE
rust: 1.47 -> 1.48

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Built `fd` on `x86_64-darwin`.

**Comment by turboMaCk** [comment]
(it tooke a while but) I was able to build rustc on nixos on this branch as well. I haven't tried to find & compile things depend on it though.

**Comment by Mic92** [comment]
I started `nix-review  pr -p firefox 104492`. I don't have my fancy server right now, so it might take a bit.

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 104492` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>thunderbird</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Firefox was not rebuild but thunderbird.

**Comment by Mic92** [comment]
Cherry picked in 9eb79c42eb8b6ea07add51d972de0df1d7383f71

**Pull request closed without merging**
