### PR TITLE
[24.05] simplex-chat-desktop: 5.8.1 -> 6.0.3

### PR DESCRIPTION
**Pull request by TerryGarcia**
(cherry picked from commit a852d3de67e7660446f61191739e88486eea9bed)

## Description of changes

Manual backport of  #325443 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TerryGarcia** [comment]
@NixOS/nixpkgs-merge-bot merge

**Review by cafkafk — COMMENTED** [review]
notice that according to `contributing.md`

```
The release branches should generally only receive backwards-compatible changes, both for the Nix expressions and derivations.
Here are some examples of backwards-compatible changes that are okay to backport:
- ✔️ New packages, modules and functions
- ✔️ Security fixes
- ✔️ Package version updates
  - ✔️ Patch versions with fixes
  - ✔️ Minor versions with new functionality, but no breaking changes

In addition, major package version updates with breaking changes are also acceptable for:
- ✔️ Services that would fail without up-to-date client software, such as `spotify`, `steam`, and `discord`
- ✔️ Security critical applications, such as `firefox` and `chromium`
```

This is a major version change, and doesn't obviously seem to be required, as the current version in stable builds fine. 

Also do note that the download page https://simplex.chat/downloads/ says that "The latest stable version is v5.8.`, but I'm pretty sure that is just outdated, they do seem to follow semver on their github repo.

Maybe this doesn't break anything and it's fine, even if it's a major version, and perhaps since it's a privacy chat tool, being up to date makes it a "security critical application".

Do you know if this introduced any breaking changes? (I don't know program this well enough to tell)

**Comment by TerryGarcia** [comment]
I use the program a lot on my computer and have upgraded to 6.0.3, and I haven't noticed any breaking changes.

**Review by cafkafk — APPROVED** [review]
Well, I think that's sufficient enough for backporting, LGTM, thanks for taking up maintainership of this!

(passthrough tests that haven't finished running are on unsupported targets, and this package doesn't have any passthrough tests, so doesn't seem like that should be a problematic to ignore)

**Pull request merged**
