### PR TITLE
nixos/binfmt: added assertion to prevent emulation of current system

### LINKED ISSUE #218465: current system in binfmt.emulatedSystems breaks with Too many levels of symbolic links
### Describe the bug
On `x` system, after setting `boot.binfmt.emulatedSystems = [ "x" ];`, bash stops working for any command:
```
-bash: /run/current-system/sw/bin/ls: Too many levels of symbolic links
```

### Steps To Reproduce
1. Given `aarch64-linux system`
2. `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];`
3. `nixos-rebuild switch`
4. bash breaks, unable to rollback from the terminal.

### Expected behaviour
Such values of `boot.binfmt.emulatedSystems` should be disallowed.

### PR DESCRIPTION
**Pull request by Ex-32**
## Description of changes

This PR should fix [issue #218464](https://github.com/NixOS/nixpkgs/issues/218465) with a simple assertion that none of the system(s) passed into `boot.binfmt.emulatedSystems` are the current system.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]
Looks good, and it's still relevant.

**Comment by RGBCube** [comment]
Accidentally locked myself out of my VPS by doing this (lmao). So yeah, vouch.

**Review by RGBCube — APPROVED** [review]

**Review by itslychee — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]

**Review by JohnRTitor — APPROVED** [review]

**Comment by NotAShelf** [comment]
Thank you @drupol

**Comment by drupol** [comment]
Can you take care of the backport?

**Comment by NotAShelf** [comment]
I've never done a backport before, but I am willing to learn. What should I be doing?

**Comment by drupol** [comment]
Do the same PR but instead of using `master` branch, use `release-23.11` branch and submit a new PR linking this PR in it.

**Comment by eclairevoyant** [comment]
BTW, this PR is broken, we should not use aliases within nixpkgs. `pkgs.system` is an alias for `pkgs.stdenv.hostPlatform.system`

**Comment by NotAShelf** [comment]
It is being addressed by #312169

**Pull request merged**
