### PR TITLE
python31{1,2}Packages.{comicon,mandown}: unbreak -- relax deps

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

relax pypdf dep -- comicon
relax lxml dep -- mandown (depends on comicon)

https://hydra.nixos.org/build/257567800
ZHF: https://github.com/NixOS/nixpkgs/issues/309482

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by annaleeleaves** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>comic-mandown</li>
    <li>comic-mandown.dist</li>
    <li>python311Packages.comicon</li>
    <li>python311Packages.comicon.dist</li>
    <li>python311Packages.mandown</li>
    <li>python311Packages.mandown.dist</li>
    <li>python312Packages.comicon</li>
    <li>python312Packages.comicon.dist</li>
    <li>python312Packages.mandown</li>
    <li>python312Packages.mandown.dist</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 310176` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>comic-mandown</li>
    <li>comic-mandown.dist</li>
    <li>python311Packages.comicon</li>
    <li>python311Packages.comicon.dist</li>
    <li>python311Packages.mandown</li>
    <li>python311Packages.mandown.dist</li>
    <li>python312Packages.comicon</li>
    <li>python312Packages.comicon.dist</li>
    <li>python312Packages.mandown</li>
    <li>python312Packages.mandown.dist</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
This builds fine, but it produces a runtime import error:

```console
$ comic-mandown/bin/mandown-gui 
Traceback (most recent call last):
  File "/nix/store/9xra83rr46ff3n5n78623kswfyc89qlp-python3.11-mandown-1.7.0/bin/.mandown-gui-wrapped", line 6, in <module>
    from mandown.ui.ui import main
  File "/nix/store/br2n23z4lh2kgv2ka88cp6zvqya9czwv-python3.12-mandown-1.7.0/lib/python3.12/site-packages/mandown/__init__.py", line 1, in <module>
    from .api import (
  File "/nix/store/br2n23z4lh2kgv2ka88cp6zvqya9czwv-python3.12-mandown-1.7.0/lib/python3.12/site-packages/mandown/api.py", line 7, in <module>
    import comicon
  File "/nix/store/nbmp31qdzaszwi0m466c8jb4igccl2vr-python3.12-comicon-1.0.1/lib/python3.12/site-packages/comicon/__init__.py", line 1, in <module>
    from .api import convert, convert_progress
  File "/nix/store/nbmp31qdzaszwi0m466c8jb4igccl2vr-python3.12-comicon-1.0.1/lib/python3.12/site-packages/comicon/api.py", line 5, in <module>
    from .inputs import create_cir_progress
  File "/nix/store/nbmp31qdzaszwi0m466c8jb4igccl2vr-python3.12-comicon-1.0.1/lib/python3.12/site-packages/comicon/inputs/__init__.py", line 5, in <module>
    from . import cbz, cir, epub, pdf
  File "/nix/store/nbmp31qdzaszwi0m466c8jb4igccl2vr-python3.12-comicon-1.0.1/lib/python3.12/site-packages/comicon/inputs/cbz.py", line 7, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/nix/store/p3gxjs6aqph6z20vj2pyblys0nkyg8g1-python3.12-lxml-5.1.0/lib/python3.12/site-packages/lxml/__init__.py)
```

**Comment by wegank** [comment]
> This builds fine, but it produces a runtime import error:

Does this also happen when running `/nix/store/9xra83rr46ff3n5n78623kswfyc89qlp-python3.11-mandown-1.7.0/bin/mandown-gui` outside the nixpkgs-review session?

**Comment by Scrumplex** [comment]
> > This builds fine, but it produces a runtime import error:
> 
> Does this also happen when running `/nix/store/9xra83rr46ff3n5n78623kswfyc89qlp-python3.11-mandown-1.7.0/bin/mandown-gui` outside the nixpkgs-review session?

It does not! I assume nixpkgs-review modifies `PYTHONPATH`?

Good to know though :D

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
