### PR TITLE
tests.cuda: inherit the ready cudaPackages_XX.cuda-samples

### PR DESCRIPTION
**Pull request by SomeoneSerge**
...fixing the broken eval

Hotfix for https://github.com/NixOS/nixpkgs/issues/280377 but should probably also move the `extension.nix` out of `pkgs/test` (https://github.com/NixOS/nixpkgs/issues/279703)

I don't know what the original purpose of `tests.cuda` was so I won't be deleting it yet

## Things done

```
❯ NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_BROKEN=1 nix-instantiate '.' -A tests.cuda
/nix/store/ypb8k50c80aqspndllkzxv35w8ix47q8-cuda-samples-11.8.drv
/nix/store/8wq9wwiqpfx2nw9lppfd8bw1pqyiligd-saxpy-unstable-2023-07-11.drv
/nix/store/r2sjw4gzalg64ycig2hlpj5q7ijr286w-cuda-samples-10.2.drv
/nix/store/0njpigfn8mw5pzyl614gppra1knia625-saxpy-unstable-2023-07-11.drv
/nix/store/bspyim2jhp20q7fn5fd00w4r65qb66ax-cuda-samples-10.0.drv
/nix/store/wqvv76vkl6afw593vajr24g5ixlflb19-saxpy-unstable-2023-07-11.drv
/nix/store/5wwm34igagw3dw9hv5534yk407kf28yi-cuda-samples-10.1.drv
/nix/store/anmhqzna231clgxn9p98cd0m7zrwjrkz-saxpy-unstable-2023-07-11.drv
/nix/store/ask5qjihgr5hh6vcfypsb3652rs3p6k0-cuda-samples-11.0.drv
/nix/store/4nbvhllxcdcks7rdljl1fx1n55wgv6yq-saxpy-unstable-2023-07-11.drv
/nix/store/dx0g58zn8d544p55h6kcghkg6d4ymm75-cuda-samples-11.1.drv
/nix/store/cvy3s1crn079cl5pjrnfrww6w40qc87w-saxpy-unstable-2023-07-11.drv
/nix/store/yx3x9nbd8qidzjddl4kpcfly0i0hvvlx-cuda-samples-11.2.drv
/nix/store/zm04jcp0ragz40p12qhkam70xijbdvij-saxpy-unstable-2023-07-11.drv
/nix/store/r0lksaapxv6iqxn87bwdk9jcd2zwpcsx-cuda-samples-11.3.drv
/nix/store/pvbbv91apfz0n05d67vmaph7x17ibhr8-saxpy-unstable-2023-07-11.drv
/nix/store/k52njhmxjs2fwhl2nlqvlr0gd5dshb60-cuda-samples-11.4.drv
/nix/store/5cxp98pxicv2mdihgkha4jci82mxr09z-saxpy-unstable-2023-07-11.drv
/nix/store/8d4y5h8azk34rwgycvqkwjfsdz9j784j-cuda-samples-11.5.drv
/nix/store/6qfsfxbkvc8f262llqk8nkx1q5s3i5hw-saxpy-unstable-2023-07-11.drv
/nix/store/af1dir2cnp2xsjk69d6lydpylx76g2d6-cuda-samples-11.6.drv
/nix/store/83vz29jarcknlnrcgl0kzs6lhjq56z68-saxpy-unstable-2023-07-11.drv
/nix/store/7ad9i66qm00zyp62h0lh3fl8kc23nlg6-saxpy-unstable-2023-07-11.drv
/nix/store/8x3k8p6dv2c4gsyhx1wqdgrq3530lvfm-cuda-samples-12.0.drv
/nix/store/bp6y6msd6n9vdb5yfzzrcbj54xn4ibnp-saxpy-unstable-2023-07-11.drv
/nix/store/pm2g3ync2x3r2rs840p90035ija2z6w8-cuda-samples-12.1.drv
/nix/store/l2cxaawhis7fnkf1qlsmrj4yb8ngp03x-saxpy-unstable-2023-07-11.drv
/nix/store/7dw9zyx9p0qi8f5s79034kdvi4m7v6sm-cuda-samples-12.2.drv
/nix/store/2mfsr2pa56b5flbsqi4pyv8fxfcy928g-saxpy-unstable-2023-07-11.drv
/nix/store/x4vzwhig1ki2k0jmdvqrsxyckr3i6drw-cuda-samples-12.3.drv
/nix/store/c0h5wlgrgnwmxy624xs2srzfggm0vxsn-saxpy-unstable-2023-07-11.drv
```

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ConnorBaker** [comment]
## `aarch64-darwin`

```console
PR=280386; \
SYSTEM="aarch64-darwin"; \
CUDA_SUPPORT="false"; \
CUDA_CAPABILITIES='[ ]'; \
nixpkgs-review pr "$PR" \
  --system "$SYSTEM" \
  --no-shell \
  --checkout commit \
  --allow aliases \
  --build-args "--max-jobs 1" \
  --skip-package-regex 'python3(\d){1,2}Packages\.(pytorch-pfn-extras|ffcv)' \
  --skip-package-regex 'python3(\d){1,2}Packages\.(shap|mlflow|optuna)' \
  --extra-nixpkgs-config "{
    allowUnfree = true;
    allowBroken = false;
    cudaSupport = ${CUDA_SUPPORT:-false};
    cudaCapabilities = ${CUDA_CAPABILITIES:-[]};
  }"
```

Result of `nixpkgs-review pr 280386 --extra-nixpkgs-config '{
    allowUnfree = true;
    allowBroken = false;
    cudaSupport = false;
    cudaCapabilities = [ ];
  }'` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>tests.cuda.cudaPackages.saxpy</li>
    <li>tests.cuda.cudaPackagesGoogle.saxpy</li>
    <li>tests.cuda.cudaPackages_10.saxpy</li>
    <li>tests.cuda.cudaPackages_10_0.saxpy</li>
    <li>tests.cuda.cudaPackages_10_1.saxpy</li>
    <li>tests.cuda.cudaPackages_10_2.saxpy</li>
    <li>tests.cuda.cudaPackages_11.saxpy</li>
    <li>tests.cuda.cudaPackages_11_0.saxpy</li>
    <li>tests.cuda.cudaPackages_11_1.saxpy</li>
    <li>tests.cuda.cudaPackages_11_2.saxpy</li>
    <li>tests.cuda.cudaPackages_11_3.saxpy</li>
    <li>tests.cuda.cudaPackages_11_4.saxpy</li>
    <li>tests.cuda.cudaPackages_11_5.saxpy</li>
    <li>tests.cuda.cudaPackages_11_6.saxpy</li>
    <li>tests.cuda.cudaPackages_11_7.saxpy</li>
    <li>tests.cuda.cudaPackages_11_8.saxpy</li>
    <li>tests.cuda.cudaPackages_12.saxpy</li>
    <li>tests.cuda.cudaPackages_12_0.saxpy</li>
    <li>tests.cuda.cudaPackages_12_1.saxpy</li>
    <li>tests.cuda.cudaPackages_12_2.saxpy</li>
    <li>tests.cuda.cudaPackages_12_3.saxpy</li>
  </ul>
</details>

## `x86_64-darwin`

```console
PR=280386; \
SYSTEM="x86_64-darwin"; \
CUDA_SUPPORT="false"; \   
CUDA_CAPABILITIES='[ ]'; \      
nixpkgs-review pr "$PR" \                                             
  --system "$SYSTEM" \       
  --no-shell \                                         
  --checkout commit \
  --allow aliases \
  --build-args "--max-jobs 1" \
  --skip-package-regex 'python3(\d){1,2}Packages\.(pytorch-pfn-extras|ffcv)' \
  --skip-package-regex 'python3(\d){1,2}Packages\.(shap|mlflow|optuna)' \
  --extra-nixpkgs-config "{
    allowUnfree = true;
    allowBroken = false;
    cudaSupport = ${CUDA_SUPPORT:-false};
    cudaCapabilities = ${CUDA_CAPABILITIES:-[]};
  }"
```

Result of `nixpkgs-review pr 280386 --extra-nixpkgs-config '{
    allowUnfree = true;
    allowBroken = false;
    cudaSupport = false;
    cudaCapabilities = [ ];
  }'` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>tests.cuda.cudaPackages.saxpy</li>
    <li>tests.cuda.cudaPackagesGoogle.saxpy</li>
    <li>tests.cuda.cudaPackages_10.saxpy</li>
    <li>tests.cuda.cudaPackages_10_0.saxpy</li>
    <li>tests.cuda.cudaPackages_10_1.saxpy</li>
    <li>tests.cuda.cudaPackages_10_2.saxpy</li>
    <li>tests.cuda.cudaPackages_11.saxpy</li>
    <li>tests.cuda.cudaPackages_11_0.saxpy</li>
    <li>tests.cuda.cudaPackages_11_1.saxpy</li>
    <li>tests.cuda.cudaPackages_11_2.saxpy</li>
    <li>tests.cuda.cudaPackages_11_3.saxpy</li>
    <li>tests.cuda.cudaPackages_11_4.saxpy</li>
    <li>tests.cuda.cudaPackages_11_5.saxpy</li>
    <li>tests.cuda.cudaPackages_11_6.saxpy</li>
    <li>tests.cuda.cudaPackages_11_7.saxpy</li>
    <li>tests.cuda.cudaPackages_11_8.saxpy</li>
    <li>tests.cuda.cudaPackages_12.saxpy</li>
    <li>tests.cuda.cudaPackages_12_0.saxpy</li>
    <li>tests.cuda.cudaPackages_12_1.saxpy</li>
    <li>tests.cuda.cudaPackages_12_2.saxpy</li>
    <li>tests.cuda.cudaPackages_12_3.saxpy</li>
  </ul>
</details>

## `x86_64-linux`

### CUDA (Non-Jetson)

Forthcoming.

### Non-CUDA

Forthcoming.

## `aarch64-linux`

### CUDA (Jetson)

Forthcoming.

### CUDA (Non-Jetson)

Forthcoming.

### Non-CUDA

Forthcoming.

**Comment by ConnorBaker** [comment]
A few things from the build summary above:

- Darwin skips them, which is good
- Jetson on `aarch64-linux` failure likely caused by output being unavailable on the Jetson devices -- need to confirm
- Unrelated to this PR other than the build errors for Saxpy when cudaSupport is false made me think to create the issue #280431

**Comment by SomeoneSerge** [comment]
I think jetson is out of scope for this PR? Has anyone previously ever built tests.cuda for jetsons or at all?

**Comment by ConnorBaker** [comment]
> I think jetson is out of scope for this PR? Has anyone previously ever built tests.cuda for jetsons or at all?

True, but I'm concerned that if we merge this as-is, `nixpkgs-review` won't work for `aarch64-linux` when targeting Jetsons. Although I suppose that could be a followup fix. What do you think?

**Comment by SomeoneSerge** [comment]
I skipped reading the error when I previously replied. It just a .dev -> lib.getDev, right? Can I ask you to push it? I've been pretending to be trying to sleep and don't want to go the pc xD

**Comment by ConnorBaker** [comment]
I will later tomorrow (today? ugh timezones); I also need to sleep :(

**Comment by SomeoneSerge** [comment]
@ConnorBaker leftover `throw`s:

```
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: autoAddCudaCompatRunpathHook: No cuda_compat for CUDA 11.4
```

**Pull request merged**
