### PR TITLE
kando: init at 1.4.0

### LINKED ISSUE #297267: Package request:  kando 🥧 The Cross-Platform Pie Menu.
**Project description**

Kando will be a pie menu for the desktop. It will be highly customizable and will allow you to create your own menus and actions. For instance, you can use it to control your music player, to open your favorite websites or to simulate shortcuts. It will be available for Windows, Linux and macOS.

**Metadata**

* homepage URL: https://ko-fi.com/post/Introducing-Ken-Do-L3L7L0FQ2
* source URL:  https://github.com/kando-menu/kando
* license: mit
* platforms:  linux, darwin

---

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/297267

This PR adds 1 package: `kando`

The build process uses `cmake-js` which wants to fetch the node headers. I patched that out, and instead I specified the headers manually using `NIX_CFLAGS_COMPILE`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by KingKrouch** [comment]
I tested this package out via the .tar.gz in the [issue ticket](https://github.com/NixOS/nixpkgs/issues/297267) for Kando, and I can confirm that this package works fine, at least from my experience. I'm running a x86_64 install of NixOS.

**Comment by dasj19** [comment]
Tested briefly on GNOME. Had to install `gnomeExtensions.kando-integration` first.
I am first time kand user and I do not know what to expect. However I found out that it kinda keeps selecting "Clipboard" automatically after Ctrl+Space.

There are also some messages in the console output:
```
Running on Linux (GNOME on wayland).
Loading settings from /home/daniel/.config/kando/config.json
Loading settings from /home/daniel/.config/kando/menus.json
[93944:0909/221028.882694:ERROR:atom_cache.cc(229)] Add _NET_WM_WINDOW_TYPE_DOCK to kAtomsToCache
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
did not find extension DRI_IMAGE_DRIVER version 2
failed to bind extensions
did not find extension DRI_Mesa version 2
failed to bind extensions
Kando 1.3.0 is ready.
Successfully loaded Kando's renderer process.
[93982:0909/221045.463697:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[93982:0909/221045.468060:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
You are running the latest version of Kando.
[93982:0909/221054.030865:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by Blezz-tech** [comment]
Tried to build a kendo in the current unstable channel

I failed.

Here's the log: https://gist.github.com/Blezz-tech/1de6a2fe8654ad16eb99b692c5d32574

Use this command for get log

```bash
nix log /nix/store/asx4wmxjmmjqvr7jmqnzqsdkaggdsac9-kando-1.3.0.drv > log
```

[log.txt](https://github.com/user-attachments/files/17011978/log.txt)

**Comment by Blezz-tech** [comment]
+ Kando is released in 1.4.0

https://github.com/kando-menu/kando/releases/tag/v1.4.0

**Comment by Blezz-tech** [comment]
I was able to build Kando by adding `wayland-scanner` in `nativeBuildInputs`, `buildInputs`

**Comment by TomaSajt** [comment]
I believe I saw a PR recently that reorganized how wayland-scanner is packaged (iirc it's no longer part of the wayland pacakage)

I'll swap it out when I get back home

**Review by dasj19 — COMMENTED** [review]
I have tried kando in my Gnome 46 and X11 vs Wayland.
As mentioned earlier after I run kando and firstly select one of its buttons, it keeps selecting one of the buttons after triggering the kando menu with Ctrl+Space. Instead of centering kando at the tip of the cursor, it has the cursor on some other button hence selecting it.

Note that this happens only on Wayland.

I do not know if it is a packaging issue or an upstream issue, but here are the output I get:

In X11:
```
Running on Linux (GNOME on x11).
Loading settings from /home/daniel/.config/kando/config.json
Loading settings from /home/daniel/.config/kando/menus.json
[41143:0921/143048.906245:ERROR:atom_cache.cc(229)] Add _NET_WM_WINDOW_TYPE_DOCK to kAtomsToCache
Kando 1.4.0 is ready.
Successfully loaded Kando's renderer process.
You are running the latest version of Kando.
```

In Wayland:
```
Running on Linux (GNOME on wayland).
Loading settings from /home/daniel/.config/kando/config.json
Loading settings from /home/daniel/.config/kando/menus.json
[60410:0921/143840.907569:ERROR:atom_cache.cc(229)] Add _NET_WM_WINDOW_TYPE_DOCK to kAtomsToCache
Kando 1.4.0 is ready.
Successfully loaded Kando's renderer process.
[60446:0921/143842.744036:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[60446:0921/143842.755449:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
You are running the latest version of Kando.
[60446:0921/143844.440516:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
I would like it working in Wayland but it has issues... I will wait for Gnome 47 to land and do a new round of testing.

**Comment by Blezz-tech** [comment]
I use Kando in KDE Plasma (Wayland)

I get some errors in the console, but everything seems to be working fine

```
~ ❯ kando
Running on Linux (KDE on wayland).
Loading settings from /home/jenya/.config/kando/config.json
Loading settings from /home/jenya/.config/kando/menus.json
[86749:0921/160330.211353:ERROR:atom_cache.cc(229)] Add _NET_WM_WINDOW_TYPE_TOOLBAR to kAtomsToCache
Kando 1.4.0 is ready.
Successfully loaded Kando's renderer process.
[86783:0921/160332.598393:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[86783:0921/160332.604663:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
You are running the latest version of Kando.
[86783:0921/160338.075179:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 337555`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>kando</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>kando</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>kando</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>kando</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Pull request merged**
