### PR TITLE
treewide: remove all empty lambda formals

### PR DESCRIPTION
**Pull request by inclyc**
These lambda formals are empty, remove them for code cleanup.

Changes were automatically performed by linter (nixf-tidy)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by inclyc** [comment]
Ahh, looks like the diff is too large, would you mind if I split them or just keep them as-is?

**Review by infinisil — CHANGES_REQUESTED** [review]
This does [not correspond to the official standard formatting](https://github.com/NixOS/nixfmt/blob/master/standard.md#function-declaration), so we shouldn't do this

**Review by K900 — CHANGES_REQUESTED** [review]
The tooling is good, but:
1) We should definitely not remove EVERY trailing comma, especially in multiline expressions
2) I'm pretty sure the rest of this will be covered by the eventual nixfmt implementation (ping @piegamesde for that)

**Comment by inclyc** [comment]
> This does [not correspond to the official standard formatting](https://github.com/NixOS/nixfmt/blob/master/standard.md#function-declaration), so we shouldn't do this

As per my understanding it says the comma should be placed at the front of the list, not the ending?

This is the example proposed in the RFC:

```nix
args@{
  some,
  argument,
  default ? value,
  ...
}:
```

I'm trying to automatically remove:

```nix
{
  lib,
  fetchFromGitHub,
  rustPlatform,
  pkg-config,
  openssl, # <--- this comma
}:

expr
```

**Comment by K900** [comment]
No, we want trailing commas on every line in multiline expressions, otherwise the line without the comma becomes a part of the diff.

For example,

```nix
{
  a, 
  b,
}:
```

to 

```nix
{
  a,
  b,
  c,
}
```

Is a one-line diff, but 

```nix
{
  a,
  b
}
```

to 

```
{
  a,
  b,
  c
}
```

is a two line diff, because the comma needs to be added to `b`.

**Comment by inclyc** [comment]
Thanks, I'll close this then!

**Comment by K900** [comment]
There may be some value to removing trailing commas from single line patterns still, e.g. `{ a, b, }` to `{ a, b }`, but those are much rarer and I'm pretty sure nixfmt will handle that.

**Comment by K900** [comment]
@piegamesde confirmed on Matrix that it will.

**Comment by inclyc** [comment]
Would you like to accept patches like removing unnecessary `rec` or unnecessary `(`  + `)` these are not covered by fmt (as per my understanding)?

**Comment by K900** [comment]
I think this just needs to be decided on a case by case basis. Sometimes parentheses are for readability, etc.

**Comment by inclyc** [comment]
I'll file PRs for your preview convenience, thanks!

**Pull request closed without merging**
