### PR TITLE
salt: fix darwin build by specifying dependency on tornado 4

### PR DESCRIPTION
**Pull request by mbode**
/cc ZHF #45961

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.tornado_4 python27Packages.tornado_4 salt

**Comment by xeji** [comment]
backported: 14ccf337ba2

**Comment by FRidh** [comment]
Please move Tornado 4.5 into the salt expression.

**Comment by xeji** [comment]
Yes, that's better. Sorry I missed that.

**Comment by dotlambda** [comment]
> Please move Tornado 4.5 into the salt expression.

Why hasn't this been done yet? It's now used by many more applications which all should use `packageOverrides` instead!

**Pull request merged**
