### PR TITLE
vimPlugins.jellybeans-vim: init at 2019-06-22

### PR DESCRIPTION
**Pull request by d-xo**
###### Motivation for this change

Add [`jellybeans.vim`](https://github.com/nanotech/jellybeans.vim)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
To adhere to https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs, do you mind separating this into two commits?

```
vimPlugins: update
vimPlugins.jellybeans-vim: init at 2019-06-22
```

the update command should also contain the reordering of elements :)

**Comment by xwvvvvwx** [comment]
done :slightly_smiling_face:

**Review by jonringer — APPROVED** [review]
diff LGTM

failure is due to an upstream issue, and I think it will resolve itself as they've had a lot of activity recently
```
[156 built (1 failed), 56 copied (836.9 MiB), 172.7 MiB DL]
error: build of '/nix/store/d3krwbrb3h1mdr5ids9wbvn32ffrgka4-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/79911
1 package failed to build:
vimPlugins.far-vim

80 package built:
vimPlugins.nerdtree vimPlugins.YouCompleteMe vimPlugins.airline vimPlugins.ale vimPlugins.ansible-vim vimPlugins.calendar vimPlugins.coc-eslint vimPlugins.coc-git vimPlugins.coc-go vimPlugins.coc-html vimPlugins.coc-lists vimPlugins.coc-metals vimPlugins.coc-snippets vimPlugins.coc-tsserver vimPlugins.coc-yaml vimPlugins.csv vimPlugins.ctrlp vimPlugins.defx-icons vimPlugins.defx-nvim vimPlugins.denite vimPlugins.deoplete-jedi vimPlugins.easymotion vimPlugins.falcon vimPlugins.fastfold vimPlugins.ferret vimPlugins.fugitive vimPlugins.fzf-vim vimPlugins.jedi-vim vimPlugins.jellybeans-vim vimPlugins.julia-vim vimPlugins.lh-brackets vimPlugins.lightline-vim vimPlugins.multiple-cursors vimPlugins.ncm2 vimPlugins.ncm2-jedi vimPlugins.neomake vimPlugins.neomru vimPlugins.neosnippet vimPlugins.nvim-gdb vimPlugins.nvim-lsp vimPlugins.open-browser vimPlugins.open-browser-github-vim vimPlugins.quickrun vimPlugins.rust-vim vimPlugins.snipmate vimPlugins.tender-vim vimPlugins.unicode-vim vimPlugins.vim-addon-actions vimPlugins.vim-addon-background-cmd vimPlugins.vim-addon-goto-thing-at-cursor vimPlugins.vim-addon-mru vimPlugins.vim-addon-mw-utils vimPlugins.vim-addon-nix vimPlugins.vim-addon-other vimPlugins.vim-addon-syntax-checker vimPlugins.vim-addon-toggle-buffer vimPlugins.vim-addon-xdebug vimPlugins.vim-airline-themes vimPlugins.vim-asterisk vimPlugins.vim-autoformat vimPlugins.vim-better-whitespace vimPlugins.vim-devicons vimPlugins.vim-dispatch vimPlugins.vim-elixir vimPlugins.vim-go vimPlugins.vim-gutentags vimPlugins.vim-html-template-literals vimPlugins.vim-lsc vimPlugins.vim-parinfer vimPlugins.vim-racer vimPlugins.vim-sandwich vimPlugins.vim-snippets vimPlugins.vim-terraform vimPlugins.vim-themis vimPlugins.vim-visual-multi vimPlugins.vim-wakatime vimPlugins.vimtex vimPlugins.vista-vim vimPlugins.xptemplate vimPlugins.zig-vim
```

**Comment by jonringer** [comment]
created an upstream issue https://github.com/brooth/far.vim/issues/84

**Pull request merged**
