### PR TITLE
obs-studio-plugins: normalized names and folders

### PR DESCRIPTION
**Pull request by superherointj**
obs-studio-plugins: normalized names and folders

### CODE REVIEW

**Review by AtilaSaraiva — COMMENTED** [review]
Thanks for the PR, looks good to me but one target failed to build:

Result of `nixpkgs-review pr 182401` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.ndi</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>obs-studio-plugins.gstreamer</li>
    <li>obs-studio-plugins.looking-glass</li>
    <li>obs-studio-plugins.move-transition</li>
    <li>obs-studio-plugins.multi-rtmp</li>
    <li>obs-studio-plugins.nvfbc</li>
    <li>obs-studio-plugins.pipewire-audio-capture</li>
    <li>obs-studio-plugins.vkcapture</li>
    <li>obs-studio-plugins.websocket</li>
  </ul>
</details>

**Comment by superherointj** [comment]
> * obs-studio-plugins.ndi

It fails because it is `unfree` and it needs to manually download a file. Try to build it yourself in isolation and see.

**Comment by 06kellyjac** [comment]
I have a bit of hesitation here. As long as these still show up in `nix search` and search.nixos.org when searching these names as you typically would then thats fine

We might need to put the original name in the description

**Comment by superherointj** [comment]
> I have a bit of hesitation here. As long as these still show up in `nix search` and search.nixos.org when searching these names as you typically would then thats fine

All packages have `obs-studio-plugins` in top-level name, which already includes 'obs'. Search for `obs` anything already lists them.

> $ nix search nixpkgs obs
image

> We might need to put the original name in the description

I'd prefer to avoid changing files to keep this as a 'git move'. Is it really necessary?

**Comment by superherointj** [comment]
> As long as these still show up in `nix search` and search.nixos.org when searching these names as you typically would then thats fine

image

> We might need to put the original name in the description

I've avoided making changes to keep it as a 'git move'.

Still, if the change is really necessary, how should I add the name, for example:

obs-ndi.description = "Network A/V plugin for OBS Studio";

How should it be instead?

**Comment by 06kellyjac** [comment]
well one option would be to leave the names as they are :shrug:
then every package has the name that they actually have for that project and it's just easier

If you *really* want normalized names then maybe leave the packages as-is but add normalized aliases

**Pull request closed without merging**
