### PR TITLE
nix-index: fix darwin build

### PR DESCRIPTION
**Pull request by periklis**
###### Motivation for this change
cc @Mic92 & @bennofs 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Can you provide the current failure build log? I have seen this now for many macOS rust packages.
Maybe we can fix this fundamentally.

**Comment by Mic92** [comment]
Is this the full log? I think the interesting part is above the message.

**Comment by Mic92** [comment]
@GrahamcOfBorg build nix-index

**Comment by Mic92** [comment]
So apparently the bundled llvm version also loads symbols from the external llvm version?
This seems wrong to me.

**Comment by LnL7** [comment]
@GrahamcOfBorg build nix-index

**Review by LnL7 — APPROVED** [review]
Lets put this in master and revert on staging, it might be a while before #49557 gets merged back.

**Pull request merged**
