### PR TITLE
libvirt: Use valid runstatedir for Darwin

### PR DESCRIPTION
**Pull request by danrabinowitz**
## Description of changes

Full disclosure: I'm a long-time Linux geek, but a nix newb.

Some use cases require libvirtd to be run as root on MacOS due to https://gitlab.com/qemu-project/qemu/-/issues/465

While the current libvirtd runs fine as non-root users, it fails when running as root:
```
bash-3.2# /nix/store/kvsnp7djkixm1qg7h1k70y44sk1jj94d-libvirt-9.9.0/bin/libvirtd
2024-03-31 22:47:20.715+0000: 8513944256: info : libvirt version: 9.9.0
2024-03-31 22:47:20.715+0000: 8513944256: info : hostname: Dans-MBP.localdomain
2024-03-31 22:47:20.715+0000: 8513944256: error : virPidFileAcquirePathFull:382 : Failed to open pid file '/run/libvirtd.pid': No such file or directory
```

Basically, it tried to access /run/libvirtd.pid, but on MacOS /run doesn't exist.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danrabinowitz** [comment]
Hey, @wegank , does this PR seem reasonable?

**Comment by wegank** [comment]
The PR does not pass the CI check. I'd suggest having a (shallow) clone of Nixpkgs, applying the patch of this PR and trying `nix-build -A virt-manager`.

**Comment by danrabinowitz** [comment]
Thanks, @wegank . Fixed.

**Comment by kirillrdy** [comment]
@danrabinowitz thank you for PR
can you update commit message to match contribution guidelines

https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

PR title should  also be updated, in this case it can be same as commit message

**Comment by kirillrdy** [comment]
@GrahamcOfBorg build libvirt

**Comment by danrabinowitz** [comment]
@kirillrdy Updated. Thanks!

**Review by wegank — APPROVED** [review]

**Pull request merged**
