### PR TITLE
pkgsStatic.llvmPackages_{5,6,7}.compiler-rt: fix musl patches after c…

### PR DESCRIPTION
**Pull request by trofi**
…yclades backport

Commit 199b7c50 "compiler-rt: remove <cyclades.h> from libsanitizer"
broke conditional conditional musl patches.

The change rebases them to drop cyclades.h related hunks.

### CODE REVIEW

**Comment by trofi** [comment]
Rebased against staging.

**Review by r-burns — APPROVED** [review]
Built pkgsMusl.llvmPackages_5.compiler-rt, and verified that patches now apply against 6 and 7.

**Comment by r-burns** [comment]
Indeed, sanitizers still fail to build if you try to turn them. And for llvm8+, we don't even try to apply this patch. There is some upstream progress for musl support as of llvm 12 (https://github.com/llvm/llvm-project/commit/7afdc89c2054d6fa3a6c2f2f24411becfc764676) but it seems other musl distros are still simply disabling the sanitizers.

So I think we should just drop this patch, and keep the sanitizers disabled on musl.

**Comment by trofi** [comment]
Sounds good. Dropped `sanitizers-nongnu.patch` from all `compiler-rt` versions.

**Review by r-burns — APPROVED** [review]
Nice work, looks great!

I see the darwin rebuilds are because the glibc-only sys-ustat.patch is now unconditional. The patch is appropriately guarded so it doesn't change the behavior on non-glibc systems, and we generally prefer unconditional patching (exactly to avoid issues like this PR is addressing!). So this looks good to me.

**Comment by trofi** [comment]
Sounds good. Rebased against `master`.

Apologies for review spam /o\. I tried to be smart to rebase against `git merge-base origin/{staging,staging-next,master}` but did something completely wrong. The history should be correct now.

**Pull request merged**
