### PR TITLE
bitwig-studio: 5.0.11 -> 5.1.2

### PR DESCRIPTION
**Pull request by bfortz**
## Description of changes

Version bump

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Philipp-M — APPROVED** [review]
Looks identical to my local update (which I use for some time already)

**Comment by Philipp-M** [comment]
It's easy to lock this to a version via an overlay, in case you only have a valid license until that upgrade.
Something like 

```nix
final: prev: (prev.bitwig-studio.overrideAttrs (oa: {
  inherit version;

  src = builtins.fetchurl {
    url = "https://downloads.bitwig.com/stable/${version}/bitwig-studio-${version}.deb";
    sha256 = "sha256-YRt99LlbiGbRSryMEl9e7U9ugb6++pfuazcpFkFb/mk=";
  };
})
```

or alternatively to a nixpkgs commit that supports that version.

**Comment by colons** [comment]
okay, yeah, that works. thank you

im curious, though; if it's possible to hold back releases like that, why make different packages for different 'major' versions at all? it seems like the difference between a major release and a point release is in marketing; certainly, they're treated the same for licensing purposes

**Comment by polygon** [comment]
Seems like we are at version 5.1.2 by now. Should we update this PR? No changes needed expect version and hash bump.

**Review by Nanotwerp — APPROVED** [review]
LGTM!

**Comment by bfortz** [comment]
Deprecated by #287959

**Comment by drupol** [comment]
Oh I wasn't aware of this PR, feel free to ping me next time!

**Pull request closed without merging**
