### PR TITLE
kodiPlugins: add YATP, drop exodus

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Continuation of #46196. A mass rebuild.

###### Things done

- [X] Builds and works without issues

Note: after adding `yatp` into `kodiWithPlugins` you have to enable YATP manually in Kodi UI.

Merge at will.

### CODE REVIEW

**Comment by xeji** [comment]
The mass rebuild seems to by caused by dropping the split outputs of `pythonPackages.requests`.
Is that really necessary to build the `kodi` plugins?

**Comment by oxij** [comment]
> The mass rebuild seems to by caused by dropping the split outputs of `pythonPackages.requests`.
> Is that really necessary to build the `kodi` plugins?

Hm. Looking at this with a fresh eye I now think I misunderstood what empty "dev" output of `pythonPackages.requests` on `master` did. It contains `nix-support/propagated-build-inputs` file, which now makes sense to me.

Removed that patch and fixed `yatp` expression instead. This should now go to `master`, as it no longer a mass rebuild.

But don't merge yet, I want to test this revision too.

**Comment by FRidh** [comment]
Yes, the `requests` thing is ugly, but its a consequence of Python packages unfortunately using `propagatedBuildInputs`.

**Comment by oxij** [comment]
Nope, unfortunately YATP doesn't start with multiple-output `requests`. :(

I'll investigate later this week.

**Comment by oxij** [comment]
After digging through the internals I came to the conclusion that the original approach was correct. See the commit messages. I think this need some more input from @FRidh.

**Comment by FRidh** [comment]
> Btw, after digging this I now feel like going through all multi-output python packages and removing multiple outputs from those that have dev output empty. What is the point of the empty dev output anyway?

Yes, we should remove multiple outputs in case of Python packages because it doesn't work. As soon as an output is defined, the `propagated-build-inputs` is no longer written it seems.

The original idea was to get certain build-time dependencies out of a closure if I understood correctly, but that seems to have been resolved elsewhere already.

**Comment by oxij** [comment]
So this should be good to merge to staging then, is it not?

**Comment by FRidh** [comment]
Note I suggest that Kodi packages are going to be put in a file of their own. That gives the possibility to use @r-ryantm

**Comment by oxij** [comment]
I see, I'll keep that in mind.

Anyway. Thanks!

**Pull request merged**
