### PR TITLE
perl.perl-cross-src: 2021-03-21 -> 1.3.6

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

This gets us onto a stable release, and also includes the support I added upstream for cross-compilation to NetBSD.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg build pkgsCross.aarch64-multiplatform.perl pkgsCross.x86_64-netbsd.perl

**Comment by alyssais** [comment]
(I don't think it'll actually _build_ for NetBSD in Nixpkgs yet, because we need https://github.com/Perl/perl5/commit/a313fe6ae7e17fd489233cbbb1dbda1d6bf25858, but it should get past configuring)

**Review by stigtsp — COMMENTED** [review]
Nice, however this breaks perldevel since 1.3.6 has removed support for perl 5.33.8.

Would you like to include a bump to perldevel in this PR as well?

```
  perldevel = common {
    perl = pkgs.perldevel;
    buildPerl = buildPackages.perldevel;
    version = "5.35.0";
    sha256 = "0217nbswhkjhw60kng2p64611xna7za681kk30fkriyicd3yph6n";
  };
```

**Review by zakame — COMMENTED** [review]
Can confirm it builds fine on plain NixOS, even on my old setup:

```
[nix-shell:~/.cache/nixpkgs-review/pr-125182]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.111, NixOS, 20.09.3881.d202d4e491a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3881.d202d4e491a"`
 - nixpkgs: `/home/nixos/.cache/nixpkgs-review/pr-125182/nixpkgs`
```

Result of `nixpkgs-review pr 125182` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>perldevel</li>
  </ul>
</details>

What can I do to test crossbuild on NetBSD?

**Review by stigtsp — APPROVED** [review]
LGTM

```
$ $(nix-build -A pkgsCross.aarch64-multiplatform.perldevel)/bin/perl -V | head
Summary of my perl5 (revision 5 version 35 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=current
    archname=aarch64-linux

```

**Comment by alyssais** [comment]
> What can I do to test crossbuild on NetBSD?

pkgsCross.x86_64-netbsd.perldevel

:)

**Pull request merged**
