### PR TITLE
yubikey-manager: 5.4.0 -> 5.5.1

### PR DESCRIPTION
**Pull request by afh**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Lassulus** [comment]
hmm, getting this error when running ykman-gui:
```
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:208: TypeError: Cannot read property 'success' of undefined
```

**Comment by afh** [comment]
Thanks for reporting, @Lassulus. When building `yubikey-manager` from this branch (`nix build .#yubikey-manager`) on `aarch64-darwin` no file named `ykman-gui` is found in the `result/` directory-tree.

Can you provide further info and context for the issue you posted?
* What command is used to run `ykman-gui`?
* Which command was used to install `ykman-gui`?
* On which system (version and arch) is `ykman-gui` run?

**Comment by Lassulus** [comment]
ah I ran nixpkgs-review pr 322907, which also builds the packages depending on yubikey-manager, which includes yubikey-manager-qt

**Comment by afh** [comment]
Result of `nixpkgs-review pr 322907` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager.dist</li>
  </ul>
</details>

**Comment by pinpox** [comment]
Result of `nixpkgs-review pr 322907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager-qt</li>
    <li>yubikey-manager.dist</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Comment by afh** [comment]
Result of `nixpkgs-review pr 322907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager-qt</li>
    <li>yubikey-manager.dist</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Comment by afh** [comment]
I'd be in favor of dropping `yubikey-manager-qt` if `yubioath-flutter` would build, unfortunately it fails for on both linux and darwin 😒

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 322907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager-qt</li>
    <li>yubikey-manager.dist</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Comment by Lassulus** [comment]
flutter seems to work here, we could mark -qt as broken though

**Comment by afh** [comment]
Thanks for testing, reviewing and merging this, @Lassulus, much appreciated 🙂

**Pull request merged**
