### PR TITLE
flare: init at 1.10

### PR DESCRIPTION
**Pull request by aanderse**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
flare-engine has a mod for like translations that we might have to
care for 
* https://github.com/flareteam/flare-engine/blob/c9c4bd4ee01cfc70e1ba49f4e17320f15c766872/mods/default/languages/regenerate_po.sh
* https://github.com/flareteam/flare-engine/blob/c9c4bd4ee01cfc70e1ba49f4e17320f15c766872/mods/default/languages/xgettext.py

Also see comments.

Other than that the game did appear to function :+1:

**Comment by aanderse** [comment]
@worldofpeace thank you for your helpful comments! Looks like I simply missed the tags on github :blush:
I didn't see any mention of running those scripts in the readme/install notes that you mentioned, nor have I worked with those sorts of translations before. I suppose I could just pass `python` or 'gettext' in the `nativeBuildInputs` and then run the script in the `preInstall` phase maybe?

**Comment by worldofpeace** [comment]
> I didn't see any mention of running those scripts in the readme/install notes that you mentioned, nor have I worked with those sorts of translations before.

Hmm, now I'm thinking that perhaps they just use them to regenerate them and commit it to the repo.
Probably don't need to do anything for those.

**Review by worldofpeace — APPROVED** [review]
LGTM :sparkles:

**Pull request merged**
