### PR TITLE
python3Packages.cozy: fix dependency name

### PR DESCRIPTION
**Pull request by Prillan**
###### Motivation for this change

`python-igraph` was recently renamed to `igraph`

ZHF #144627 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by risicle — APPROVED** [review]
LGTM, `nixpkgs-review` happy, macos 10.15, nixos x86_64 & aarch64 (emulated)

**Review by tomberek — CHANGES_REQUESTED** [review]
Fails to run due to module name mismatch?
```
[nix-shell:~/.cache/nixpkgs-review/pr-146799]$ ./results/python38Packages.cozy/bin/cozy
Traceback (most recent call last):
  File "/nix/store/r90d25xmkkpxx91gvfd42z2ax3d44xi0-python3.8-cozy-2.0a1/bin/.cozy-wrapped", line 6, in <module>
    from cozy.main import run
  File "/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages/cozy/main.py", line 22, in <module>
    from cozy import synthesis
  File "/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages/cozy/synthesis/__init__.py", line 1, in <module>
    from .impls import Implementation, construct_initial_implementation
  File "/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages/cozy/synthesis/impls.py", line 12, in <module>
    import igraph
  File "/nix/store/fy6zyak65vcx73z2snyx4acz5j47485y-python3.9-igraph-0.9.8/lib/python3.9/site-packages/igraph/__init__.py", line 26, in <module>
    from igraph._igraph import (
ModuleNotFoundError: No module named 'igraph._igraph'
```

**Comment by Prillan** [comment]
> Fails to run due to module name mismatch?
> 
> ```
> [nix-shell:~/.cache/nixpkgs-review/pr-146799]$ ./results/python38Packages.cozy/bin/cozy
> Traceback (most recent call last):
>   File "/nix/store/r90d25xmkkpxx91gvfd42z2ax3d44xi0-python3.8-cozy-2.0a1/bin/.cozy-wrapped", line 6, in <module>
>     from cozy.main import run
>   File "/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages/cozy/main.py", line 22, in <module>
>     from cozy import synthesis
>   File "/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages/cozy/synthesis/__init__.py", line 1, in <module>
>     from .impls import Implementation, construct_initial_implementation
>   File "/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages/cozy/synthesis/impls.py", line 12, in <module>
>     import igraph
>   File "/nix/store/fy6zyak65vcx73z2snyx4acz5j47485y-python3.9-igraph-0.9.8/lib/python3.9/site-packages/igraph/__init__.py", line 26, in <module>
>     from igraph._igraph import (
> ModuleNotFoundError: No module named 'igraph._igraph'
> ```

I don't get that error, hmm. It looks really weird that it's importing the python3.9 library from the python3.8 main...

**Comment by Prillan** [comment]
The `PYTHONPATH` is wrong when entering the `nixpkgs-review` shell:
```
$ echo $PYTHONPATH 
/nix/store/sjmk33x0n4sifz7abj821if8qkid0mdd-python3.9-cozy-2.0a1/lib/python3.9/site-packages:/nix/store/qa57rnfnq4c6q9r3sc2xs4m05rlfcjgg-python3.9-setuptools-57.2.0/lib/python3.9/site-packages:/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/site-packages:/nix/store/q9ki0qhqsn7kmpmmjz330jjrv3hn7l4a-z3-4.8.12-python/lib/python3.9/site-packages:/nix/store/hxvvakrf9q0qyrpm9ry4sr54c6avrf9m-python3.9-ply-3.11/lib/python3.9/site-packages:/nix/store/fy6zyak65vcx73z2snyx4acz5j47485y-python3.9-igraph-0.9.8/lib/python3.9/site-packages:/nix/store/sghhc5813z30nicgi8lc79fkgdxhd78i-python3.9-texttable-1.6.4/lib/python3.9/site-packages:/nix/store/cksaig9xfpl45w2lcz5q7qr7ccrwb7vj-python3.9-oset-0.1.3/lib/python3.9/site-packages:/nix/store/vsq4b9mxr5wam2g9kb72xk5jaiijgqr0-python3.9-ordered-set-4.0.2/lib/python3.9/site-packages:/nix/store/bbwfm77fvjl51zfjf4mws7ki47ad5gh7-python3.9-dictionaries-0.0.2/lib/python3.9/site-packages
```

Running it with no python path outside of that shell works, but not inside it:
```
~/.cache/nixpkgs-review/pr-146799-1/results/python38Packages.cozy/bin/cozy --help
usage: cozy [-h] .......
```

I'm not sure if it's something I've done wrong or if it's a bug in nixpkgs-review.

**Comment by risicle** [comment]
If you're building packages from multiple different python versions at the same time, the resulting shell will be pretty screwed up in my experience.

**Comment by Prillan** [comment]
> If you're building packages from multiple different python versions at the same time, the resulting shell will be pretty screwed up in my experience.

Aha, so nothing that can be done about it I guess?

@tomberek

**Comment by tomberek** [comment]
Agreed, this is just a nixpkgs-review quirk. Sorry.

**Review by tomberek — APPROVED** [review]

**Pull request merged**
