### PR TITLE
.github/workflows/check-commits.yml: check for the existence of fixup…

### PR DESCRIPTION
**Pull request by Artturin**
… commits

oftentimes people forget to either fixup the fixup! commits or forget to
squash merge

this should prevent that from happening

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Does this really happen that often that we need an action? Can you how some data from the git history?

**Comment by zowoq** [comment]
People probably won't like getting a ❌ on PRs that could be squashed.

**Comment by Artturin** [comment]
theres notice, warning, and error messages 
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-notice-message

i don't know if warnings show up as a red X
if they do then it could be a notice

**Comment by zowoq** [comment]
> theres notice, warning, and error messages

That is for the message, I'm talking about the check status. AFAIK is has to be either green or red.

**Comment by zowoq** [comment]
Looks like you're trying to test this here, it won't actually work unless it is on master. As it doesn't need any of the `nixpkgs` code I'd suggest creating a personal repo to test it in, that is what I usually do.

**Comment by zowoq** [comment]
There are other actions and apps on the marketplace that we could for this (and other commit lint/style checks) which may be better than writing and needing to maintain our own. 

Adding it to `ofborg` (which does support neutral check status) might be a better option as well.

**Pull request closed without merging**
