### PR TITLE
trezord: 2.0.14 -> 2.0.19 and nixos/trezord: revised and updated udev rules

### PR DESCRIPTION
**Pull request by 1000101**
###### Motivation for this change
I'd like to maintain the package up-to-date as we're the company releasing the original code.

###### Things done
Updated version from 2.0.14 to 2.0.19. Reviewed and updated the service policies and rights.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
https://github.com/NixOS/nixpkgs/pull/46658

**Comment by 7c6f434c** [comment]
@ryantm they have different target branches

**Comment by 1000101** [comment]
Target branch is 18.09, 18.03 (it's not a duplicate). Should I use some different method for pulling into different branch?

**Comment by ryantm** [comment]
Sorry, I didn't realize you had a different target branch!

**Comment by 1000101** [comment]
No worries! If there's a better/preferred way, just let me know!

**Comment by 1000101** [comment]
will require further testing for model T

**Pull request closed without merging**
