### PR TITLE
cmake: 3.15.4 -> 3.16.2

### PR DESCRIPTION
**Pull request by tobim**
###### Motivation for this change
The announcement: https://discourse.cmake.org/t/cmake-3-16-0-available-for-download/262
The release page: https://cmake.org/cmake/help/v3.16/release/3.16.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
needs rebase

**Review by ttuegel — APPROVED** [review]

**Review by jtojnar — CHANGES_REQUESTED** [review]
We have added a patch to CMake in https://github.com/NixOS/nixpkgs/pull/74282, this will need to be removed before merging.

**Comment by tobim** [comment]
> We have added a patch to CMake in #74282, this will need to be removed before merging.

Thanks, done.

**Comment by tobim** [comment]
@jtojnar would you mind having another look?

**Comment by jtojnar** [comment]
Looking at the changelog:

> The “CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY” variable has been
> deprecated. Use the “CMAKE_FIND_USE_PACKAGE_REGISTRY” variable
> instead.

```ShellSession
$ rg CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY
pkgs/development/libraries/quickder/default.nix
43:    "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON"

pkgs/development/tools/build-managers/cmake/setup-hook.sh
99:    cmakeFlags="-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON $cmakeFlags"
```

**Comment by tobim** [comment]
Good catch! Your feedback is integrated.

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
