### PR TITLE
nixos/lib: hash triggers after converting them to string in systemd-lib

### PR DESCRIPTION
**Pull request by wrvsrx**
###### Description of changes

This change is made for two reasons:

1.  If `toString config.restartTriggers` containes `\n`, systemd unit file will be ill-formed. Besides, we can inject a lot of things into it.
2.  This change can limit length of the trigger, although it doesn't matter in most cases.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
This is clever and certainly more functional. I don't know how I feel about losing the human-readability of `X-Restart-Triggers`, but I guess that's probably not important? Anyone else have thoughts on that?

**Comment by jian-lin** [comment]
I think human-readability of `X-Restart-Triggers` is important.

**Comment by wrvsrx** [comment]
@jian-lin At least we need to remove `\n` from X-Restart-Triggers. I'll edit the PR to preseve human-readability.

**Comment by ElvishJerricco** [comment]
@wrvsrx I don't think you should edit the PR. Escaping the contents of this value so that we can definitely have it represent what we want without keeping other encoding errors seems at least annoying, whereas this hashing idea is a remarkably simple and functional solution. Human readability doesn't seem important to me in this case, so I'd like to hear @jian-lin's reasoning for finding that important.

**Comment by wrvsrx** [comment]
Rename the commit and PR. I ignored the top-level path nixos for nixos/lib/systemd-lib, which resulted in an incorrect PR name.

**Comment by wrvsrx** [comment]
@ElvishJerricco You're right. It seems quite complex to transform a string through a one-to-one mapping to a space that does not include line breaks and is also a valid systemd string. Using a hash directly would be much simpler. If we only care about whether the inputs and outputs match and do not need to manually inspect the contents, this seems to be the simplest solution.

**Comment by jian-lin** [comment]
The human-readability of `X-Restart-Triggers` is important because if `re*Triggers` are hashed, the source code of a nixos config is the only way to find the meaning of those triggers, which is not convenient.

Keeping `X-Restart-Triggers` valid is necessary.  Before, this is done by users and this PR tries to let the module system do it, which is good in general.  However, the approach this PR chooses also damage the human-readability.

Actually, we can have our cake and eat it: instead of hashing triggers, we can write them into a file in the store and set `X-Restart-Triggers` to the the path of that file.  This works because if the content (triggers) the that file changes, the hash part in the file path will also changes.

**Comment by wrvsrx** [comment]
@jian-lin Now it store triggers' content into /nix/store and uses store path to trigger restarting or reloading.

**Review by jian-lin — APPROVED** [review]
LGTM

**Review by ElvishJerricco — APPROVED** [review]
LGTM as well. Does anyone have a convenient way to like... test this? I mean I'm confident it works, because the code does effectively the same thing but nicer. But still seems like someone should at least *try it* before merging :P

**Comment by jian-lin** [comment]
@ofborg test switchTest

**Pull request merged**
