### PR TITLE
pluma: init at 1.18.2

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Add Pluma package.

[Pluma](https://github.com/mate-desktop/pluma) is a powerful text editor for [MATE](http://www.mate-desktop.org).

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Infinisil** [comment]
I'm noticing that all the packages in pkgs/desktops/mate are using the same source, `"http://pub.mate-desktop.org/releases/${major-ver}/${name}.tar.xz"`, but there are currently 4 different (major, minor) versions being used (atril-1.19.0, caja-1.18.0, mate-common-1.18.0, mate-desktop-1.18.0, mate-icon-theme-faenza-1.18.0, mate-icon-theme-1.18.1, mate-terminal-1.18.0, pluma-1.18.2).

I think it would make sense to refactor it so that a single version is used for all the packages distributed by this Mate source

**Comment by romildo** [comment]
1.19.x seems to be development versions. Only `atril` is using it. It has been added by someone else. The other packages are at 1.18.x, which is the stable version. Some of them receive minor updates. Therefore the minor version _x_ is not the same for all of them.

So I agree to use the same major stable versions for the mate packages, with the latest minor version available for each of them. Therefore `atril` would be downgraded to version 1.18.0.

I want to (slowly) add more mate applications until the desktop is complete.

**Comment by Infinisil** [comment]
Oh I actual misread the download URL, I thought all packages were built from the same source tarball, which is not the case, sorry for that.

In that case it's not really bad with the versions, probably just updating them to v1.19 when it's out would be nice.

I tested the editor btw, works without problems (except some GTK messages on stdout regarding themes, but I think that's pretty standard to have).

**Comment by romildo** [comment]
@Mic92 Why a dependency on `gnome3.defaultIconTheme` is needed?

Should every application with icons depend on it?

Also when should `gnome3.defaultIconTheme` be prefferred over `hicolor_icon_theme`?

**Pull request merged**
