### PR TITLE
GNOME 3.16

### PR DESCRIPTION
**Pull request by lucabrunox**
Not yet ready to merge:
- [x] Test whether NM 1.0 still has the issue with many vbox interfaces on real hardware
- [x] NM 1.0 has been packaged stupidly, plugins won't work. The problem is the dependency cycle between the applet and the plugins. Easiest way to solve: create an applet wrapper with plugins. EDIT: turns out this shouldn't be needed, because the etc files refer to the plugin packages themselves. The nixos setup should be enough.
- [x] NM 1.0 must be tested with other desktops. If it doesn't work, I won't hesitate to add an `nmPackages`. That's however not easy, because nowadays many apps depend on NM libs even indirectly, e.g. webkitgtk.
- [ ] GDM 3.16 is a different beast, so we're now using GDM 3.14. I've put some files under 3.16-wip for people wanting to make it work.
- [x] gnome-music needs libmediaart typelib
- [ ] If the user waits too much to login in GDM, it seems the screen lock is broken and it's unable to restore the login window.
- [x] Let `gnome3.icon-themes` be a single derivation instead of a list. Also add gnome_icon_theme fallback to gnome 3.16.
- [ ] Allow the user to override the gdm config, so that we can support auto-login and add a nixos test.
- [x] Some icons like gnome-photos and gnome-documents are not showing up.
- [ ] openssh UI agent shows instead of gnome-keyring/seahorse.
- [x] Eventually update to 3.16.1
- [ ] Eventually add support for bluetooth. Partially done, gnome doesn't find any adapter.
- [ ] Eventually add support for colord
- [x] Haven't compiled empathy, yelp, evolution, bijiben because they need webkit 2.4. Done, compiled.
- [x] Fix tracker typelib to point to full nix store path of the .so and remove LD_LIBRARY_PATH from gnome-music
- [x] Remove LD_LIBRARY_PATH from gnome-documents
- [x] Evolution window doesn't move.
- [x] Before merging: remove possible testing stuff.

Various warnings in the journal:

**Tracker miner warnings**

```
machine# [   35.991244] gnome-session[1529]: (.tracker-miner-apps-wrapped:1718): Tracker-WARNIN
G **: File 'file:///run/current-system/sw/share/desktop-directories/X-GNOME-SystemSettings.dire
ctory' has been reenqueued more than 2 times. It will not be indexed.
machine# [   35.994815] gnome-session[1529]: (.tracker-miner-apps-wrapped:1718): Tracker-WARNIN
G **: Couldn't properly parse desktop file 'file:///run/current-system/sw/share/desktop-directo
ries': 'Couldn't load desktop file:'/run/current-system/sw/share/desktop-directories''
...
```

**Missing users**

```
machine# [    5.869526] dbus-daemon[1211]: Unknown username "pulse" in message bus configuration file
machine# [    5.873343] dbus-daemon[1211]: Unknown username "nm-openconnect" in message bus configuration file
```

**gnome-shell calendar**

```
machine# [   59.805873] org.gnome.Shell.CalendarServer[1572]: (.gnome-shell-calendar-server-wra
pped:1697): libecal-CRITICAL **: e_cal_client_set_default_timezone: assertion 'zone != NULL' fa
iled
```

**gnome-calculator shell search provider**

``` pkgs/desktops/gnome-3/3.16/apps/gnome-documents/default.nix
org.gnome.Calculator.SearchProvider[1483]: Error: ErrorCode.UNKNOWN_VARIABLE
```

But it works anyway in the activities.

**GDM pam_systemd uses consolekit???**

```
Apr 17 07:39:23 nixos gdm-session-worker[1279]: <5>GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
Apr 17 07:39:23 nixos gdm-session-worker[1279]: <3>GLib: g_variant_new_string: assertion 'string != NULL' failed
Apr 17 07:39:23 nixos gdm-launch-environment][1279]: pam_systemd(gdm-launch-environment:session): Failed to create session: No seat '/org/freedesktop/ConsoleKit/Seat1' known
```

**When locking the screen**

```
Apr 17 07:51:29 nixos org.gnome.Shell.CalendarServer[1654]: (.gnome-shell-calendar-server-wrapped:1724): libecal-CRITICAL **: e_cal_client_set_default_timezone: assertion 'zone != NULL' failed
Apr 17 07:51:29 nixos org.gnome.Shell.CalendarServer[1654]: (.gnome-shell-calendar-server-wrapped:1724): libecal-CRITICAL **: e_cal_client_set_default_timezone: assertion 'zone != NULL' failed
Apr 17 07:51:28 nixos gdm-password][2009]: gkr-pam: no password is available for user
```

### CODE REVIEW

**Comment by vcunat** [comment]
I believe the stable branches do NOT contain those fixes. I just checked yesterday and [asked upstream](https://bugzilla.gnome.org/show_bug.cgi?id=731014#c72). I judged by presence of 	``data/85-nm-unmanaged.rules``, which was added in one of the fixing commits.

**Comment by lethalman** [comment]
Lost a lot of time trying to make GDM 3.16, but it's a different beast so we're now using GDM 3.14.

**Comment by vcunat** [comment]
I believe NM-1.0 doesn't solve the issue with virtual interfaces (discussed link). The patches are nontrivial, so I'm not so confident just picking them, and upstream (or the patch author) haven't responded to backporting questions yet.

**Comment by lethalman** [comment]
@vcunat I think I'm just going stupid-patch mode, removing all unmanaged devices from the applet. We'll never move forward otherwise.

**Comment by domenkozar** [comment]
3.16.1 is out

**Comment by bendlas** [comment]
I did a minimal test build and it looks pretty good when booted on metal (even though in vm, it crashes a lot for me).
Now, when trying to build with more of my system packages, it pulls in a lot of gnome-3.12 (shell, config-center, aso...). I managed to get around this by setting gnome3 = pkgs.gnome3_16; in packageOverrides (in addition to environment.gnome3.packageSet = pkgs.gnome3_16), but then I also had to stub out gnome_icon_theme and gnome_icon_theme_symbolic. I'm not sure what could be done about this.

Thanks @lethalman for taking this on; please consider not force-pushing, it would make tracking your progress a lot easier. You can still squash the commits later, if nessecary.

**Comment by lethalman** [comment]
@bendlas thanks for the feedback. Ok I won't force-push. Yes using gnome3_16 in packageOverrides is the right thing to do. About gnome icon, either you also do a package override as you did, or otherwise I've added a icon-themes attribute to gnome. It's used for the nixos service, but it can be used as well by every other package.

It could be used like this: `buildInputs = [ ... ] ++ gnome3.icon-themes`.

**Comment by lethalman** [comment]
Did some fixes, now building 3.16.1.

**Comment by lethalman** [comment]
Updated to 3.16.1 but now gnome-shell doesn't start. Looks like they added a new dependency -.-'

**Comment by lethalman** [comment]
So I don't know if it's only gnome, but on bare metal with virtualbox host enabled, I don't see the vboxnet anymore. It looks all fine. Now we have to check other DE.

**Comment by lethalman** [comment]
Screenshot: http://i.imgur.com/XNBCDjD.png

**Comment by lethalman** [comment]
So I've tried nm-applet with xfce, it shows vboxnet0. It's no more a lot of interfaces, but I guess that's because we don't spawn a lot of interfaces like before. @aszlig I don't remember, maybe you can help, what's the reason we had a lot of vboxnet interfaces? Would this still be the case anyhow?

Other thing: lightdm seems broken with gnome 3.16, or don't know if it's glib 2.44 which breaks it, it seems to encounter some assertions when dealing with dbus/gvariant.

**Comment by lethalman** [comment]
Added gnome-bluetooth. bluez works per-se, I'm able to use bluetoothctl and all with my adapter, but gnome is unable to find any adapter. Tried both bluez4 and bluez5.

**Comment by lethalman** [comment]
@domenkozar @vcunat I'd like to merge this stuff in staging. About the NM issue, it only shows vboxnet0 now with nm-applet. I think that's acceptable?

**Comment by vcunat** [comment]
Certainly acceptable from my point of view (and better than delaying this because of it).

**Comment by bendlas** [comment]
@lethalman wow, great progress!

I saw the crashes in a qemu vm, by `nixos-rebuild build-vm`. I'm rebuilding now and see if it still happens.

I agree that using `packageOverrides` is the right thing for external packages depending on gnome3. Still, shouldn't one gnome3 package set be self-contained? I see a lot of older gnome3 bleeding into the build when I do `nix-env -f . -iA gnome3_16 --dry-run` without the override.

**Comment by lethalman** [comment]
@bendlas the nixos service is self-contained, other stuff is up to you.

**Comment by lethalman** [comment]
@bendlas should be better now

**Comment by domenkozar** [comment]
@lethalman sure, are NM VPN plugins working?

**Comment by lethalman** [comment]
@domenkozar never used it, but now that I think of, I should port some of the patches seen by gnome 3.12 to gnome 3.16, like a g-c-c patch for vpn plugins ;) thanks.

**Comment by bendlas** [comment]
yay, `nix-env --dry-run` looks good now. Still waiting on those webkitgtk builds ...

**Comment by lethalman** [comment]
So I never used a VPN plugin, but:
```
Apr 20 15:11:33 nixos gnome-session[13293]: Gjs-Message: JS LOG: Invalid VPN service type (cannot find authentication binary)
Apr 20 15:11:33 nixos NetworkManager[1136]: <error> [1429542693.165324] [vpn-manager/nm-vpn-connection.c:1899] get_secrets_cb(): Failed to request VPN secrets #2: (4) No agents were available for this request.
```

I've added some fake info to the VPN settings, but I guess that's not a wanted error.

**Comment by lethalman** [comment]
Getting an headache... now who is in charge of being a secret agent.... gnome-shell? gnome-keyring? seahorse? Who knows.

**Comment by lethalman** [comment]
Ok I think I got it, gnome-shell can't find some binaries, of course. Man this gnome stuff is endless.

**Comment by lethalman** [comment]
Ok openvpn should be fixed now. Let's see other plugins :S

**Comment by lethalman** [comment]
Other plugins look fine, but some of them (openconnect IIRC) have UI problems.

So here's the problem: the networkmanager plugins uses gnome 3.12 by default, but gtk 3.12 apps look like without a theme (e.g. transparent background) on gnome 3.16. So for the time being people should add a `gnome3 = gnome3_16;` override to have a working UI for the NM plugins on gnome 3.16.

But that means a lot of rebuild. What can we do about it? Drop gnome 3.12 forever, or let networkmanager nixos service use the chosen gnome3 environment?

**Comment by vcunat** [comment]
It would be nice to decouple the nixos from UI, but that's probably too time-consuming to do ATM. Does it break the other way around as well? (plugins built against 3.16 in 3.12)

**Comment by bendlas** [comment]
Couldn't those plugins be built against `config.environment.gnome3.packageSet`?

**Comment by bendlas** [comment]
Btw, I'm still getting crashes in a `build-vm` qemu. I don't think that should block this ticket, but here is the syslog, in case you are interested: https://gist.github.com/bendlas/3583234e048a5b3259ae

**Comment by vcunat** [comment]
@bendlas: that are kernel errors, and they mention memory allocation a lot &ndash; could it be that the VM got too little RAM?

**Comment by lethalman** [comment]
@bendlas yes I'm wondering if that's sensible, maybe it is. And yes, most probably 

@vcunat no idea, I haven't even tested whether 3.12 works. Well networkmanager plugins are compiled with gnome3 support, so. I think I will let the nixos NM use the gnome3 packageSet, test it and merge this stuff.

**Comment by vcunat** [comment]
@lethalman: OK, seems the best thing now.

**Comment by lethalman** [comment]
Ok so the last commit https://github.com/lethalman/nixpkgs/commit/71a6918a75fcaf5b36d64992e8b89a37d49ab310 is the best/easiest thing I could come up with.

If one enables gnome, then the `environment.gnome3.packageSet` will be used for the NM packages.

Now the openconnect plugin shows a decent UI.

**Comment by bendlas** [comment]
@vcunat that was indeed the issue. Thanks for glassballing that for me.

**Comment by bendlas** [comment]
@lethalman the current build looks fantastic. Would it be easy to set a default background image aswell?

When I take out the `gnome3 = gnome3_16` override (without any further `systemPackages`), there are still a couple of changes, that hint at improvable isolation:

- dconf `0.20.0` is used instead of `0.24.0`
- gnome-common `3.12` is used instead of `3.14`
- vala `23.2` is used instead of `26.2`

**Comment by vcunat** [comment]
:-) I wonder why a better error message couldn't be displayed...

**Comment by lethalman** [comment]
@bendlas I tried hard making a default background, even for kde... too hard :( Will retry some day. Anyway about those other versions I'd avoid complicating stuff if everything works somehow ;)

@vcunat @domenkozar @edolstra I'm going to test this against staging, then send an email to advise this PR could potentially break something, then merge.

**Comment by domenkozar** [comment]
:+1:

**Comment by lethalman** [comment]
Stuck at https://github.com/NixOS/nixpkgs/commit/35f1e07647fe26737ed6ed6f91043d9b237a7799 , cannot compile glib-networking :(

**Comment by vcunat** [comment]
I see a problem with ``webkitgtk24x``: it won't compile on staging, probably due to a glib update.
```
Source/WebCore/platform/graphics/gstreamer/VideoSinkGStreamer.cpp: In function 'gboolean webkitVideoSinkTimeoutCallback(gpointer)':
Source/WebCore/platform/graphics/gstreamer/VideoSinkGStreamer.cpp:121:5: error: reference to 'GMutexLocker' is ambiguous
     GMutexLocker lock(priv->bufferMutex);
     ^
In file included from /nix/store/a9k7gns05p61g090yy83vs9giysnn3jd-glib-2.44.0/include/glib-2.0/glib/gasyncqueue.h:32:0,
                 from /nix/store/a9k7gns05p61g090yy83vs9giysnn3jd-glib-2.44.0/include/glib-2.0/glib.h:32,
                 from /nix/store/a9k7gns05p61g090yy83vs9giysnn3jd-glib-2.44.0/include/glib-2.0/gobject/gbinding.h:28,
                 from /nix/store/a9k7gns05p61g090yy83vs9giysnn3jd-glib-2.44.0/include/glib-2.0/glib-object.h:23,
                 from Source/WebCore/platform/graphics/gstreamer/VideoSinkGStreamer.h:25,
                 from Source/WebCore/platform/graphics/gstreamer/VideoSinkGStreamer.cpp:29:
```

**Comment by vcunat** [comment]
I seem to have a fix for that (and some security updates for webkitgtk24x).

**Comment by lethalman** [comment]
@vcunat the fix is in my branch

On Thu, Apr 23, 2015 at 7:43 PM, Vladimír Čunát <notifications@github.com>
wrote:

> I seem to have a fix for that (and some security updates for webkitgtk24x).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/7357#issuecomment-95667438>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by vcunat** [comment]
Ah, sorry, I thought I searched for it in there, but I looked wrong. I wanted to cherry-pick it to staging, but I don't see it as a separate commit. Or do you think this PR would get to staging soon?

BTW, it surprises me that this PR is open against master and not staging.

**Comment by lethalman** [comment]
@vcunat yes, as long as I fix build issues and test it :D After the merge this PR would trigger another big rebuild, I wouldn't fix webkit now.

Because this PR has been tested on nixos unstable, not on staging.

**Comment by vcunat** [comment]
I just dislike leaving staging in a broken state for long. The branch was meant for *tested/safe* changes to avoid missing binaries on master.

**Comment by lethalman** [comment]
@vcunat ok feel free to extract the patch from the branch

**Comment by lethalman** [comment]
Trying with this now:
```
--- a/pkgs/development/libraries/gnutls/generic.nix
+++ b/pkgs/development/libraries/gnutls/generic.nix
@@ -23,10 +23,8 @@ stdenv.mkDerivation rec {
   # for the actual fix.
   enableParallelBuilding = !guileBindings;
 
-  buildInputs = [ lzo lzip nettle libtasn1 libidn p11_kit ]
+  buildInputs = [ lzo lzip nettle libtasn1 libidn p11_kit zlib gmp trousers unbound ]
     ++ stdenv.lib.optional guileBindings guile;
-  # The paths for these libraries are not specified in the .la and .pc files
-  propagatedBuildInputs = [ zlib gmp trousers unbound ];
 
   nativeBuildInputs = [ perl pkgconfig autoreconfHook ];
 
@@ -34,6 +32,14 @@ stdenv.mkDerivation rec {
   # http://hydra.nixos.org/build/2962084/nixlog/1/raw .
   doCheck = (!stdenv.isFreeBSD && !stdenv.isDarwin);
 
+  # Fixup broken libtool and pkgconfig files
+  preFixup = ''
+    sed -e 's,-ltspi,-L${trousers}/lib -ltspi,' \
+        -e 's,-lz,-L${zlib}/lib -lz,' \
+        -e 's,-lgmp,-L${gmp}/lib -lgmp,' \
+        -i $out/lib/libgnutls.la $out/lib/pkgconfig/gnutls.pc
+  '';
+
   meta = with stdenv.lib; {
     description = "The GNU Transport Layer Security Library";
```

cc @vcunat @wkennington

**Comment by lethalman** [comment]
But now NM doesn't compile:
``
make[4]: Entering directory '/tmp/nix-build-network-manager-1.0.0.drv-0/NetworkManager-1.0.0/li
bnm-core/tests'
  CC       test-compare.o
  CCLD     test-compare
/nix/store/sfb03nqk9gh67sika5l1f1ivvch0vklq-binutils-2.23.1/bin/ld: cannot find -lcrypto
/nix/store/sfb03nqk9gh67sika5l1f1ivvch0vklq-binutils-2.23.1/bin/ld: cannot find -lssl
```

**Comment by lethalman** [comment]
Ah because libgnutlsxx.la has `-lcrypto -lssl`, wondering where they come from.

**Comment by lethalman** [comment]
Now compiling webkit et all with the gnome 3.16 branch, will push the fixes for gnutls and trousers once I see everything compiles fine.

**Comment by vcunat** [comment]
At least from the point of multiple-output changes, using ``propagatedBuildInputs`` is better than putting library paths into build commands, as the paths may change... but it's not too much work to fix those references afterwards; at least ``${foo}`` occurrences are easy to find &ndash; not all path-making styles use ``${foo}``.

**Comment by vcunat** [comment]
@lethalman: if you're often slowed by webkitgtk*, I think it can be parallelized now 2c0db9ffbe9.

**Comment by lethalman** [comment]
@vcunat absolutely it's not better to use propagatedBuildInputs, because they are NOT propagatedBuildInputs. That trousers is needing libssl privately, and must not be propagated. It's just their .la file is broken, and that also breaks other builds.

So please, don't use propagatedBuildInputs when it's wrong.

**Comment by lethalman** [comment]
@vcunat not only, it's propagatedBuildInputs that should be worse for multi-outputs, because how do you choose which libs are propagated if you have more than 2 libs built? With fixed .la and .pc, that comes automatic, with nix-support and propagated build inputs you have a problem.

**Comment by lethalman** [comment]
Merged in staging.

**Comment by edolstra** [comment]
This PR added GTK+ 3.16. Is there any reason to keep 3.12 around (as the default, even)?

**Comment by lethalman** [comment]
@edolstra will work on removing 3.12 once we get an unstable release.

**Comment by vcunat** [comment]
What's the plan for release? Switch all to 3.16 or keep all on 3.12? If we switch, we should do it soon, so it's well-tested.

**Comment by lethalman** [comment]
After the nixos unstable channel updates (which did yesterday evening),
I'll work on dropping 3.12.

On Sun, May 17, 2015 at 10:11 AM, Vladimír Čunát <notifications@github.com>
wrote:

> What's the plan for release? Switch all to 3.16 or keep all on 3.12? If we
> switch, we should do it soon, so it's well-tested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/7357#issuecomment-102766750>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by obadz** [comment]
Thanks a lot for packaging it!

Small issues:
The gnome-tweak-tool refuses to save unless you mkdir ~/.config/gtk-3.0 first.
Also I think it's missing some options here and there:
image
(Had same problem with Gnome 3.12 so not really a regression..)

**Comment by lethalman** [comment]
About the config/gtk-3.0 that should be reported upstream.

**Comment by meteficha** [comment]
> Some icons like gnome-photos and gnome-documents are not showing up.

Both apps have icons on `nixos-15.09`, so I guess this checkbox can be marked.

> Eventually add support for bluetooth. Partially done, gnome doesn't find any adapter.

If you keep `bluetoothctl` open, you can see that GNOME is able to start and stop scanning for devices whenever you enter and exit the Bluetooth settings.  Also, if you, for example, set up a pairing with a smartphone via `bluetoothctl`, the smartphone will then appear on the top-right menu as a possible internet connection.

**Comment by meteficha** [comment]
It seems that you can't change the profile picture of a user on `gnome-control-center`.  It complains about not finding `/bin/cat`.  If you add a symlink (`ln -s  $(which cat) /bin/cat`), it works.

**Comment by meteficha** [comment]
Ok, sorry, I just saw that this issue is closed :disappointed:.  I was mislead by the `work-in-progress` label.  Should I open new issues for (a) the bluetooth bug and (b) the profile picture bug?

**Comment by lethalman** [comment]
@meteficha but why with gnome you have to run that `bluetoothctl`? I thought it should have been all magic. I guess there's something missing...

There's a more general GNOME issue here: https://github.com/NixOS/nixpkgs/issues/247

**Comment by meteficha** [comment]
@lethalman I don't have to. I did it in order to try to inspect what GNOME was trying to do :).

**Pull request closed without merging**
