### PR TITLE
Pulumi Update 1.12.0 > 2.2.1

### PR DESCRIPTION
**Pull request by mudrii**
###### Motivation for this change
Update pulumi to new version 2.2.1
Add new core cloud plugin for pulumi Azure

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @peterromfeldhk @jlesquembre

### CODE REVIEW

**Comment by prusnak** [comment]
Please read https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md and fix commit messages according to this document.

**Comment by MarcoPolo** [comment]
I thought pulumi downloads the plugins when needed. Do these included plugins actually get used by the main pulumi-bin? I'm worried that it involves unnecessary downloads.

**Comment by mudrii** [comment]
Maybe make sense to make modules separatly similar to terraform?

**Comment by mudrii** [comment]
I will close this PR and create separate OR for update and azure

**Comment by jlesquembre** [comment]
@mudrii some solution similar to terraform makes sense to me
@MarcoPolo pulumi downloads the plugins automatically, but they don't work in nix unless you patch them, see the comment in my PR #72373

**Pull request closed without merging**
