### PR TITLE
fluxcd: 0.38.3 -> 0.39.0

### PR DESCRIPTION
**Pull request by superherointj**
fluxcd: 0.38.3 -> 0.39.0

### CODE REVIEW

**Comment by matthewpi** [comment]
Result of `nixpkgs-review pr 214203` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fluxcd</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 214203` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fluxcd</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by alphabet5** [comment]
@superherointj could this be backported to release-22.11 by adding the `backport: release-22.11` tag?

**Comment by superherointj** [comment]
> @superherointj could this be backported to release-22.11 by adding the `backport: release-22.11` tag?

You can always add it as see how it goes. I personally only use unstable. (Nix has rollback in any issue.) IMO everyone should use it from unstable because using older versions is usually not desirable. Imagine, creating a cluster just to have to migrate it soon. I don't like that.

**Comment by superherointj** [comment]
> Backport failed for `release-22.11`, because it was unable to cherry-pick the commit(s).
> 
> Please cherry-pick the changes locally.
> 
> ```shell
> git fetch origin release-22.11
> git worktree add -d .worktree/backport-214203-to-release-22.11 origin/release-22.11
> cd .worktree/backport-214203-to-release-22.11
> git checkout -b backport-214203-to-release-22.11
> ancref=$(git merge-base b6f3d9cbeadb3b6364d479e848ca91cfd40b08f6 ec476eb0510a757297ac13ef66e49a459e0bfba2)
> git cherry-pick -x $ancref..ec476eb0510a757297ac13ef66e49a459e0bfba2
> ```

Previous PRs would have to be backported too. In sequence.
I suggest you don't bother about this.

**Pull request merged**
