### PR TITLE
Refactor pianoteq.

### PR DESCRIPTION
**Pull request by greydot**
Remove fetching binaries using provided login, because it's utterly inconvenient and exposes the password. Instead, require the user to manually download the inputs.

Also, add hash for Pianoteq STAGE 8.1.3.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mausch** [comment]
> Remove fetching binaries using provided login, because it's utterly inconvenient 

I went to great lengths to implement this because I find it utterly *convenient* :slightly_smiling_face: 

> exposes the password

This is done via environment variables just like `fetchFromGitHub` does (in fact I copied it from there), I don't see the problem?

> require the user to manually download the inputs.

I can see how some people would prefer this to having Nix downloading the binaries for them.
Instead of removing functionality I propose refactoring a bit to make the functions in here public (namely: `mkPianoteq`, `fetchPianoteqTrial`, `fetchPianoteqWithLogin`) so users can then easily build their own package in a couple lines instead of depending on nixpkgs being always up to date or needing to submit a PR for some version in particular.

**Comment by greydot** [comment]
> This is done via environment variables just like `fetchFromGitHub` does (in fact I copied it from there), I don't see the problem?

Sure, but how do you pass those variables? The only viable solution I found was to tweak nix-daemon systemd unit, which is also stored in /nix/store.

>Instead of removing functionality I propose refactoring a bit to make the functions in here public (namely: mkPianoteq, fetchPianoteqTrial, fetchPianoteqWithLogin) so users can then easily build their own package in a couple lines instead of depending on nixpkgs being always up to date or needing to submit a PR for some version in particular.

Not sure I follow how this would work. Could you provide an interface of what you want to see? For example, what should I put into configuration.nix in your version of things?

**Comment by mausch** [comment]
> Sure, but how do you pass those variables? The only viable solution I found was to tweak nix-daemon systemd unit, which is also stored in /nix/store.

```
nix.envVars = {
  NIX_MODARTT_USERNAME = "...";
  NIX_MODARTT_PASSWORD = "...";
};
```

Now that you mention it, it took me a while to figure this out too. I don't think this is well documented.

In practice I put those values in a gitignored file, but you can probably use some [secret-management solution](https://nixos.wiki/wiki/Comparison_of_secret_managing_schemes) too.

> Not sure I follow how this would work. Could you provide an interface of what you want to see? For example, what should I put into configuration.nix in your version of things?

Pretty much what you wrote in this PR:

```
environment.systemPackages = [
...
  (pkgs.pianoteq.mkPianoteq rec {
    name = "stage-8";
    mainProgram = "Pianoteq 8 STAGE";
    startupWMClass = "Pianoteq STAGE";
    version = "8.1.3";
    src = requireFile {
      name = "pianoteq_stage_linux_v813.7z";
      url = "https://www.modartt.com/download";
      sha256 = "1x70hl15ql8i7g78mmhsfn5z1w5y41lxi9w8fnw779wl7dywj1a6";
    };
  })
];
```

We just need to put `mkPianoteq` and the other functions in the final set to enable this I think.

**Comment by greydot** [comment]
> nix.envVars = {
>   NIX_MODARTT_USERNAME = "...";
>   NIX_MODARTT_PASSWORD = "...";
> };

Yeah, no. If your entire configuration.nix is stored in /nix/store (and it is), this will be too. I can imagine making a kind of `/secrets` directory, having the login there, and then setting `nix.settings.extra-sandbox-paths` to include that directory. But this is just a world of pain to manage.

> Pretty much what you wrote in this PR:
> 
> environment.systemPackages = [
> ...
>   (pkgs.pianoteq.mkPianoteq rec {
>     name = "stage-8";
>     mainProgram = "Pianoteq 8 STAGE";
>     startupWMClass = "Pianoteq STAGE";
>     version = "8.1.3";
>     src = requireFile {
>       name = "pianoteq_stage_linux_v813.7z";
>       url = "https://www.modartt.com/download";
>       sha256 = "1x70hl15ql8i7g78mmhsfn5z1w5y41lxi9w8fnw779wl7dywj1a6";
>     };
>   })
> ];
> 
> We just need to put mkPianoteq and the other functions in the final set to enable this I think.

Ok, will do. Should I also drop all those hardcoded Pianoteq versions in the meanwhile? Does anyone really need or want Pianoteq 6 here?

**Comment by mausch** [comment]
> Yeah, no. If your entire configuration.nix is stored in /nix/store (and it is), this will be too. I can imagine making a kind of /secrets directory, having the credentials in a file there, and then setting nix.settings.extra-sandbox-paths to include that directory. But this is just a world of pain to manage.
> As far as I gather, none of those work from inside nixpkgs. I.e. building a nixpkgs package using those isn't advisable.

Yeah secrets management is a pain in NixOS. 
Like I said I just copied that environment variable thing from [fetchFromGitHub](https://github.com/NixOS/nixpkgs/blob/f3719756b550113c1acbbab00c89a56fb77256f2/pkgs/build-support/fetchgithub/default.nix#L32-L44) so maybe try asking on https://discourse.nixos.org/ how people manage private repositories with that?

Personally I wouldn't want my private github credentials in the nix store but I don't think it's a big deal for some Modartt credentials on my personal laptop.

> Should I also drop all those hardcoded Pianoteq versions in the meanwhile? Does anyone really need or want Pianoteq 6 here?

Let's not delete anything... People have contributed the version of Pianoteq that they own. Personally I own and use Pianoteq 6.

**Comment by purepani** [comment]
Are there any other packages in the nix store that have to solve similar problems?

**Comment by purepani** [comment]
I also think there is another problem to point out here: 
If something goes wrong with the credentials, for whatever authentication reason, then it's possible for your entire configuration to stop building. 
There are some different use cases to keep in mind too.

1. Downloading and installing on the same computer. This is likely the most common usage, and in this case, the secrets will only need to be on one machine.
2. Downloading and installing on different computers. This might happen to someone who, say, uses a raspberry pi to use pianoteq, but wants to install it from their laptop. 

In case number 2, I think it makes sense to only have the secrets available in the build phase and not the installation phase. I.E. not storing the secrets in the nix store.

**Comment by mausch** [comment]
> Are there any other packages in the nix store that have to solve similar problems?
> In this case, the problem being, we can't even download the binary without credentials.

Yes like I said I roughly copied the solution here from [fetchFromGitHub](https://github.com/NixOS/nixpkgs/blob/f3719756b550113c1acbbab00c89a56fb77256f2/pkgs/build-support/fetchgithub/default.nix#L32-L44).
See also:
- https://github.com/NixOS/nixpkgs/blob/26a7cb60c57b9802da3eca617945feb04ef05fb5/pkgs/build-support/fetchurl/default.nix#L81
- https://nixos.org/manual/nix/stable/command-ref/conf-file.html?highlight=netrc#conf-netrc-file
- https://nixos.org/manual/nix/stable/language/advanced-attributes#adv-attr-impureEnvVars

It might be possible to use a netrc file to provide the credentials instead (though it seems to be designed for HTTP basic auth)

>  If something goes wrong with the credentials, for whatever authentication reason, then it's possible for your entire configuration to stop building.

Hmm tbh I don't see how this is an issue? I mean it's just like with any other package? If it fails to build you fix it :slightly_smiling_face: 

> Downloading and installing on different computers. This might happen to someone who, say, uses a raspberry pi to use pianoteq, but wants to install it from their laptop.

This is an interesting scenario :+1: 

For the scope of this PR I'd recommend sticking to exporting functions so people can use `requireFile` when necessary.

**Comment by greydot** [comment]
I decided in the end to just copy some code from this derivation into my personal flake, so there's no point in keeping this PR open.

**Pull request closed without merging**
