### PR TITLE
check-meta: Improve performance

### PR DESCRIPTION
**Pull request by Artturin**
See c3c31aa798551a2808981d14537d04de8f51dff8

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
Couldn't (and shouldn't) the `inherit` thing` be done as an optimization in the interpreter? That way all Nix files would benefit from it.

**Comment by Artturin** [comment]
> Couldn't (and shouldn't) the `inherit` thing` be done as an optimization in the interpreter? That way all Nix files would benefit from it.

Yes but I'm not that familiar with the nix codebase.

There was some discussion in https://github.com/NixOS/nixpkgs/pull/266886

**Comment by Artturin** [comment]
Round 1
image

**Comment by SuperSandro2000** [comment]
> Couldn't (and shouldn't) the `inherit` thing` be done as an optimization in the interpreter? That way all Nix files would benefit from it.

@roberth @Ericson2314 Could you bring that up into the nix repo? I do not think I can adequately describe it for an issue.

**Comment by roberth** [comment]
It's unclear how easily and broadly such a transformation can be applied. We don't want to accidentally make currently light weight closures heavier in places where we humans would not apply the rule. Here's an issue for it:
- https://github.com/NixOS/nix/issues/9592

**Pull request merged**
