### PR TITLE
mednaffe: GTK3, correct license, find mednafen w/o patching source

### PR DESCRIPTION
**Pull request by lukateras**
/cc @AmatCoder 

###### Motivation for this change

See https://github.com/NixOS/nixpkgs/pull/29855#issuecomment-333308467.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by sheenobu** [comment]
Thanks! Looks like a merge conflict in travis (but not in github which is weird).

**Comment by yegortimoshenko** [comment]
I've rebased on top of master (if that would help), with no conflicts.

**Comment by yegortimoshenko** [comment]
Another GitHub bug: I don't see my commit in this pull request.

**Comment by sheenobu** [comment]
@yegortimoshenko Looks like you amended the commit? I'm sure that causes some complications when cascading branch changes to their PRs.

**Comment by vcunat** [comment]
I see the commit here the same way as on your branch, as expected from GitHub.

**Review by vcunat — APPROVED** [review]

**Comment by AmatCoder** [comment]
Great! Thanks to @yegortimoshenko :)

**Pull request merged**
