### PR TITLE
cudaPackages: remove nsight-systems from cuda 10

### PR DESCRIPTION
**Pull request by jmbaur**
## Description of changes

CUDA's nsight-systems comes with its own version of libstdc++.so that conflicts with stuff compiled against nixpkgs libstdc++, so lets remove it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
Cuda 10 might just be relevant to people with quite old hardware. But did run into an issue where cudatoolkit was picking up these vendored libraries for some older jetpack builds.

Since we construct our own cudaPackages.backendStdenv, I don't think we have use for the nvidia vendored tools. Instead removing them here seems like the right path forward.

**Comment by jonringer** [comment]
cc @SomeoneSerge @ConnorBaker 

@NixOS/cuda-maintainers

**Review by samuela — COMMENTED** [review]
Let's add a comment (outside of nix strings) explaining the rationale here. 

O/w no objections from me. I don't think there's anyone wanting to use Nsight on CUDA 10, but if so they can always raise an issue.

**Comment by samuela** [comment]
Also why does this only impact CUDA 10?

**Comment by SomeoneSerge** [comment]
> CUDA's nsight-systems comes with its own version of libstdc++.so that conflicts with stuff compiled against nixpkgs libstdc++, so lets remove it.

We should just delete that old libstdc++. Autopatchelf will automatically put the nixpkgs' newer one in DT_RUNPATH, and that'll just work because you can always build with the old libstdc++ and use the newer one at runtime

There have been several issues before regarding e.g. the qt and wayland libraries also vendored in nsight-systems. They were addressed ad hoc.


We're looking for a more sustainable way of getting rid of the libraries vendored by nvidia, cf. e.g. https://github.com/ConnorBaker/cuda-redist-find-features/issues/11

**Comment by jmbaur** [comment]
@SomeoneSerge sounds good, changed to just remove libstdc++ instead of all of nsight-systems

**Comment by jmbaur** [comment]
> Also why does this only impact CUDA 10?

AFAIK it does not, we are also removing libstdc++ for CUDA 11 a few lines down.

**Comment by ConnorBaker** [comment]
> [!Important]
>
> This review was run against commit ebf185539f80684efbfdd4a6c5fbd5d50a4868f3

> [!Note]
>
> Template `nixpkgs-review` command:
>
> ```console
> PR="282170"; \
> SYSTEM="x86_64-linux"; \
> CUDA_SUPPORT="true"; \
> CUDA_CAPABILITIES='[ "7.5" ]'; \
> nix run "github:Mic92/nixpkgs-review/2.10.4" -- \
>   pr "${PR:?}" \
>   --system "${SYSTEM:?}" \
>   --no-shell \
>   --checkout merge \
>   --allow aliases \
>   --build-graph nix \
>   --extra-nixpkgs-config "{
>     allowUnfree = true;
>     allowBroken = false;
>     checkMeta = true;
>     cudaSupport = ${CUDA_SUPPORT:?};
>     cudaCapabilities = ${CUDA_CAPABILITIES:?};
>   }"
> ```
>
> Template log archival command:
>
> ```bash
> PR="282170"; \
> RUN_NUMBER=""; \
> SYSTEM="x86_64-linux"; \
> CUDA_CAPABILITIES="75"; \
> tar -cvf "${SYSTEM:?}-cap-${CUDA_CAPABILITIES:?}-pr-${PR:?}${RUN_NUMBER:+-$RUN_NUMBER}.tar.zst" \
>   -I "zstd -T0 --long=31 --ultra -22" \
>   -C "${HOME:?}/.cache/nixpkgs-review/pr-${PR:?}${RUN_NUMBER:+-$RUN_NUMBER}" \
>   .
> ```
>
> Logs are made available at <https://drive.google.com/drive/folders/1GgABhwa2ooKeZXMqf5He6PcyClNrE6cQ?usp=share_link>

Nothing unexpected with either of these. NCCL fails to build with earlier versions of CUDA (like 10) at the moment as we don't keep older versions of NCCL.

## :white_check_mark: `x86_64-linux`

### :white_check_mark: CUDA (Non-Jetson)

Result of `nixpkgs-review pr 282170 --extra-nixpkgs-config '{
    allowUnfree = true;
    allowBroken = false;
    checkMeta = true;
    cudaSupport = true;
    cudaCapabilities = [ "7.5" ];
  }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>66 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffe</li>
    <li>caffe.bin</li>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>cudaPackages_10.cuda-samples</li>
    <li>cudaPackages_10.cudnn_7_4</li>
    <li>cudaPackages_10.cudnn_7_4.dev</li>
    <li>cudaPackages_10.cudnn_7_4.lib</li>
    <li>cudaPackages_10.cudnn_7_4.static</li>
    <li>cudaPackages_10.cudnn_8_8</li>
    <li>cudaPackages_10.cudnn_8_8.dev</li>
    <li>cudaPackages_10.cudnn_8_8.lib</li>
    <li>cudaPackages_10.cudnn_8_8.static</li>
    <li>cudaPackages_10.cudnn_8_9</li>
    <li>cudaPackages_10.cudnn_8_9.dev</li>
    <li>cudaPackages_10.cudnn_8_9.lib</li>
    <li>cudaPackages_10.cudnn_8_9.static</li>
    <li>cudaPackages_10.tensorrt</li>
    <li>cudaPackages_10.tensorrt.bin</li>
    <li>cudaPackages_10.tensorrt.dev</li>
    <li>cudaPackages_10.tensorrt.lib</li>
    <li>cudaPackages_10.tensorrt.python</li>
    <li>cudaPackages_10.tensorrt.sample</li>
    <li>cudaPackages_10.tensorrt.static</li>
    <li>cudaPackages_10.tensorrt_8_0</li>
    <li>cudaPackages_10.tensorrt_8_0.bin</li>
    <li>cudaPackages_10.tensorrt_8_0.dev</li>
    <li>cudaPackages_10.tensorrt_8_0.lib</li>
    <li>cudaPackages_10.tensorrt_8_0.python</li>
    <li>cudaPackages_10.tensorrt_8_0.sample</li>
    <li>cudaPackages_10.tensorrt_8_0.static</li>
    <li>cudaPackages_10.tensorrt_8_2</li>
    <li>cudaPackages_10.tensorrt_8_2.bin</li>
    <li>cudaPackages_10.tensorrt_8_2.dev</li>
    <li>cudaPackages_10.tensorrt_8_2.lib</li>
    <li>cudaPackages_10.tensorrt_8_2.python</li>
    <li>cudaPackages_10.tensorrt_8_2.sample</li>
    <li>cudaPackages_10.tensorrt_8_2.static</li>
    <li>cudaPackages_10.tensorrt_8_4</li>
    <li>cudaPackages_10.tensorrt_8_4.bin</li>
    <li>cudaPackages_10.tensorrt_8_4.dev</li>
    <li>cudaPackages_10.tensorrt_8_4.lib</li>
    <li>cudaPackages_10.tensorrt_8_4.python</li>
    <li>cudaPackages_10.tensorrt_8_4.sample</li>
    <li>cudaPackages_10.tensorrt_8_4.static</li>
    <li>cudaPackages_10.tensorrt_8_5</li>
    <li>cudaPackages_10.tensorrt_8_5.bin</li>
    <li>cudaPackages_10.tensorrt_8_5.dev</li>
    <li>cudaPackages_10.tensorrt_8_5.lib</li>
    <li>cudaPackages_10.tensorrt_8_5.python</li>
    <li>cudaPackages_10.tensorrt_8_5.sample</li>
    <li>cudaPackages_10.tensorrt_8_5.static</li>
    <li>cudaPackages_10.tensorrt_8_6</li>
    <li>cudaPackages_10.tensorrt_8_6.bin</li>
    <li>cudaPackages_10.tensorrt_8_6.dev</li>
    <li>cudaPackages_10.tensorrt_8_6.lib</li>
    <li>cudaPackages_10.tensorrt_8_6.python</li>
    <li>cudaPackages_10.tensorrt_8_6.sample</li>
    <li>cudaPackages_10.tensorrt_8_6.static</li>
    <li>python311Packages.caffe</li>
    <li>python311Packages.caffe.bin</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>tests.cuda.cudaPackages_10.cuda-samples</li>
    <li>tests.cuda.cudaPackages_10_1.cuda-samples</li>
    <li>tests.cuda.cudaPackages_10_2.cuda-samples</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>cudaPackages_10.nccl</li>
    <li>cudaPackages_10.nccl-tests</li>
    <li>cudaPackages_10.nccl.dev</li>
    <li>dcgm</li>
    <li>prometheus-dcgm-exporter</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>cudaPackages_10.cudatoolkit</li>
    <li>cudaPackages_10.cudatoolkit.doc</li>
    <li>cudaPackages_10.cudatoolkit.lib</li>
    <li>cudaPackages_10.cudnn (cudaPackages_10.cudnn.dev ,cudaPackages_10.cudnn.lib ,cudaPackages_10.cudnn.static ,cudaPackages_10.cudnn_8_7 ,cudaPackages_10.cudnn_8_7.dev ,cudaPackages_10.cudnn_8_7.lib ,cudaPackages_10.cudnn_8_7.static)</li>
    <li>cudaPackages_10.cudnn_7_6 (cudaPackages_10.cudnn_7_6.dev ,cudaPackages_10.cudnn_7_6.lib ,cudaPackages_10.cudnn_7_6.static)</li>
    <li>cudaPackages_10.cudnn_8_0 (cudaPackages_10.cudnn_8_0.dev ,cudaPackages_10.cudnn_8_0.lib ,cudaPackages_10.cudnn_8_0.static)</li>
    <li>cudaPackages_10.cudnn_8_1 (cudaPackages_10.cudnn_8_1.dev ,cudaPackages_10.cudnn_8_1.lib ,cudaPackages_10.cudnn_8_1.static)</li>
    <li>cudaPackages_10.cudnn_8_2 (cudaPackages_10.cudnn_8_2.dev ,cudaPackages_10.cudnn_8_2.lib ,cudaPackages_10.cudnn_8_2.static)</li>
    <li>cudaPackages_10.cudnn_8_3 (cudaPackages_10.cudnn_8_3.dev ,cudaPackages_10.cudnn_8_3.lib ,cudaPackages_10.cudnn_8_3.static)</li>
    <li>cudaPackages_10.cudnn_8_4 (cudaPackages_10.cudnn_8_4.dev ,cudaPackages_10.cudnn_8_4.lib ,cudaPackages_10.cudnn_8_4.static)</li>
    <li>cudaPackages_10.cudnn_8_5 (cudaPackages_10.cudnn_8_5.dev ,cudaPackages_10.cudnn_8_5.lib ,cudaPackages_10.cudnn_8_5.static)</li>
    <li>cudaPackages_10.cudnn_8_6 (cudaPackages_10.cudnn_8_6.dev ,cudaPackages_10.cudnn_8_6.lib ,cudaPackages_10.cudnn_8_6.static)</li>
    <li>cudaPackages_10.cutensor (cudaPackages_10.cutensor.dev ,cudaPackages_10.cutensor.lib ,cudaPackages_10.cutensor.static ,cudaPackages_10.cutensor_1_7 ,cudaPackages_10.cutensor_1_7.dev ,cudaPackages_10.cutensor_1_7.lib ,cudaPackages_10.cutensor_1_7.static)</li>
    <li>cudaPackages_10.cutensor_1_3 (cudaPackages_10.cutensor_1_3.dev ,cudaPackages_10.cutensor_1_3.lib ,cudaPackages_10.cutensor_1_3.static)</li>
    <li>cudaPackages_10.cutensor_1_4 (cudaPackages_10.cutensor_1_4.dev ,cudaPackages_10.cutensor_1_4.lib ,cudaPackages_10.cutensor_1_4.static)</li>
    <li>cudaPackages_10.cutensor_1_5 (cudaPackages_10.cutensor_1_5.dev ,cudaPackages_10.cutensor_1_5.lib ,cudaPackages_10.cutensor_1_5.static)</li>
    <li>cudaPackages_10.cutensor_1_6 (cudaPackages_10.cutensor_1_6.dev ,cudaPackages_10.cutensor_1_6.lib ,cudaPackages_10.cutensor_1_6.static)</li>
    <li>cudaPackages_10.saxpy (tests.cuda.cudaPackages_10.saxpy ,tests.cuda.cudaPackages_10_2.saxpy)</li>
    <li>tests.cuda.cudaPackages_10_1.saxpy</li>
  </ul>
</details>

### :white_check_mark: Non-CUDA

Result of `nixpkgs-review pr 282170 --extra-nixpkgs-config '{
    allowUnfree = true;
    allowBroken = false;
    checkMeta = true;
    cudaSupport = false;
    cudaCapabilities = [ ];
  }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>63 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>cudaPackages_10.cuda-samples</li>
    <li>cudaPackages_10.cudnn_7_4</li>
    <li>cudaPackages_10.cudnn_7_4.dev</li>
    <li>cudaPackages_10.cudnn_7_4.lib</li>
    <li>cudaPackages_10.cudnn_7_4.static</li>
    <li>cudaPackages_10.cudnn_8_8</li>
    <li>cudaPackages_10.cudnn_8_8.dev</li>
    <li>cudaPackages_10.cudnn_8_8.lib</li>
    <li>cudaPackages_10.cudnn_8_8.static</li>
    <li>cudaPackages_10.cudnn_8_9</li>
    <li>cudaPackages_10.cudnn_8_9.dev</li>
    <li>cudaPackages_10.cudnn_8_9.lib</li>
    <li>cudaPackages_10.cudnn_8_9.static</li>
    <li>cudaPackages_10.nccl-tests</li>
    <li>cudaPackages_10.tensorrt</li>
    <li>cudaPackages_10.tensorrt.bin</li>
    <li>cudaPackages_10.tensorrt.dev</li>
    <li>cudaPackages_10.tensorrt.lib</li>
    <li>cudaPackages_10.tensorrt.python</li>
    <li>cudaPackages_10.tensorrt.sample</li>
    <li>cudaPackages_10.tensorrt.static</li>
    <li>cudaPackages_10.tensorrt_8_0</li>
    <li>cudaPackages_10.tensorrt_8_0.bin</li>
    <li>cudaPackages_10.tensorrt_8_0.dev</li>
    <li>cudaPackages_10.tensorrt_8_0.lib</li>
    <li>cudaPackages_10.tensorrt_8_0.python</li>
    <li>cudaPackages_10.tensorrt_8_0.sample</li>
    <li>cudaPackages_10.tensorrt_8_0.static</li>
    <li>cudaPackages_10.tensorrt_8_2</li>
    <li>cudaPackages_10.tensorrt_8_2.bin</li>
    <li>cudaPackages_10.tensorrt_8_2.dev</li>
    <li>cudaPackages_10.tensorrt_8_2.lib</li>
    <li>cudaPackages_10.tensorrt_8_2.python</li>
    <li>cudaPackages_10.tensorrt_8_2.sample</li>
    <li>cudaPackages_10.tensorrt_8_2.static</li>
    <li>cudaPackages_10.tensorrt_8_4</li>
    <li>cudaPackages_10.tensorrt_8_4.bin</li>
    <li>cudaPackages_10.tensorrt_8_4.dev</li>
    <li>cudaPackages_10.tensorrt_8_4.lib</li>
    <li>cudaPackages_10.tensorrt_8_4.python</li>
    <li>cudaPackages_10.tensorrt_8_4.sample</li>
    <li>cudaPackages_10.tensorrt_8_4.static</li>
    <li>cudaPackages_10.tensorrt_8_5</li>
    <li>cudaPackages_10.tensorrt_8_5.bin</li>
    <li>cudaPackages_10.tensorrt_8_5.dev</li>
    <li>cudaPackages_10.tensorrt_8_5.lib</li>
    <li>cudaPackages_10.tensorrt_8_5.python</li>
    <li>cudaPackages_10.tensorrt_8_5.sample</li>
    <li>cudaPackages_10.tensorrt_8_5.static</li>
    <li>cudaPackages_10.tensorrt_8_6</li>
    <li>cudaPackages_10.tensorrt_8_6.bin</li>
    <li>cudaPackages_10.tensorrt_8_6.dev</li>
    <li>cudaPackages_10.tensorrt_8_6.lib</li>
    <li>cudaPackages_10.tensorrt_8_6.python</li>
    <li>cudaPackages_10.tensorrt_8_6.sample</li>
    <li>cudaPackages_10.tensorrt_8_6.static</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>tests.cuda.cudaPackages_10.cuda-samples</li>
    <li>tests.cuda.cudaPackages_10_1.cuda-samples</li>
    <li>tests.cuda.cudaPackages_10_2.cuda-samples</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>cudaPackages_10.nccl</li>
    <li>cudaPackages_10.nccl.dev</li>
    <li>dcgm</li>
    <li>prometheus-dcgm-exporter</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>caffe</li>
    <li>caffe.bin</li>
    <li>cudaPackages_10.cudatoolkit</li>
    <li>cudaPackages_10.cudatoolkit.doc</li>
    <li>cudaPackages_10.cudatoolkit.lib</li>
    <li>cudaPackages_10.cudnn (cudaPackages_10.cudnn.dev ,cudaPackages_10.cudnn.lib ,cudaPackages_10.cudnn.static ,cudaPackages_10.cudnn_8_7 ,cudaPackages_10.cudnn_8_7.dev ,cudaPackages_10.cudnn_8_7.lib ,cudaPackages_10.cudnn_8_7.static)</li>
    <li>cudaPackages_10.cudnn_7_6 (cudaPackages_10.cudnn_7_6.dev ,cudaPackages_10.cudnn_7_6.lib ,cudaPackages_10.cudnn_7_6.static)</li>
    <li>cudaPackages_10.cudnn_8_0 (cudaPackages_10.cudnn_8_0.dev ,cudaPackages_10.cudnn_8_0.lib ,cudaPackages_10.cudnn_8_0.static)</li>
    <li>cudaPackages_10.cudnn_8_1 (cudaPackages_10.cudnn_8_1.dev ,cudaPackages_10.cudnn_8_1.lib ,cudaPackages_10.cudnn_8_1.static)</li>
    <li>cudaPackages_10.cudnn_8_2 (cudaPackages_10.cudnn_8_2.dev ,cudaPackages_10.cudnn_8_2.lib ,cudaPackages_10.cudnn_8_2.static)</li>
    <li>cudaPackages_10.cudnn_8_3 (cudaPackages_10.cudnn_8_3.dev ,cudaPackages_10.cudnn_8_3.lib ,cudaPackages_10.cudnn_8_3.static)</li>
    <li>cudaPackages_10.cudnn_8_4 (cudaPackages_10.cudnn_8_4.dev ,cudaPackages_10.cudnn_8_4.lib ,cudaPackages_10.cudnn_8_4.static)</li>
    <li>cudaPackages_10.cudnn_8_5 (cudaPackages_10.cudnn_8_5.dev ,cudaPackages_10.cudnn_8_5.lib ,cudaPackages_10.cudnn_8_5.static)</li>
    <li>cudaPackages_10.cudnn_8_6 (cudaPackages_10.cudnn_8_6.dev ,cudaPackages_10.cudnn_8_6.lib ,cudaPackages_10.cudnn_8_6.static)</li>
    <li>cudaPackages_10.cutensor (cudaPackages_10.cutensor.dev ,cudaPackages_10.cutensor.lib ,cudaPackages_10.cutensor.static ,cudaPackages_10.cutensor_1_7 ,cudaPackages_10.cutensor_1_7.dev ,cudaPackages_10.cutensor_1_7.lib ,cudaPackages_10.cutensor_1_7.static)</li>
    <li>cudaPackages_10.cutensor_1_3 (cudaPackages_10.cutensor_1_3.dev ,cudaPackages_10.cutensor_1_3.lib ,cudaPackages_10.cutensor_1_3.static)</li>
    <li>cudaPackages_10.cutensor_1_4 (cudaPackages_10.cutensor_1_4.dev ,cudaPackages_10.cutensor_1_4.lib ,cudaPackages_10.cutensor_1_4.static)</li>
    <li>cudaPackages_10.cutensor_1_5 (cudaPackages_10.cutensor_1_5.dev ,cudaPackages_10.cutensor_1_5.lib ,cudaPackages_10.cutensor_1_5.static)</li>
    <li>cudaPackages_10.cutensor_1_6 (cudaPackages_10.cutensor_1_6.dev ,cudaPackages_10.cutensor_1_6.lib ,cudaPackages_10.cutensor_1_6.static)</li>
    <li>cudaPackages_10.saxpy (tests.cuda.cudaPackages_10.saxpy ,tests.cuda.cudaPackages_10_2.saxpy)</li>
    <li>python311Packages.caffe</li>
    <li>python311Packages.caffe.bin</li>
    <li>tests.cuda.cudaPackages_10_1.saxpy</li>
  </ul>
</details>

**Review by ConnorBaker — APPROVED** [review]

**Comment by jonringer** [comment]
> > Also why does this only impact CUDA 10?

> AFAIK it does not, we are also removing libstdc++ for CUDA 11 a few lines down.

My apologies, I just had issues personally with cuda 10. Not to exclude other package sets.

**Pull request merged**
