### PR TITLE
Bmake updates

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Description of changes

https://github.com/NixOS/nixpkgs/pull/271621

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>kgt</li>
    <li>libfsm</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>bmake</li>
    <li>bozohttpd</li>
    <li>bozohttpd-minimal</li>
  </ul>
</details>

but neither failure looks bmake related

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 276934` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>bmake</li>
    <li>bozohttpd</li>
    <li>bozohttpd-minimal</li>
    <li>hikari</li>
    <li>kgt</li>
    <li>kgt.bin</li>
    <li>kgt.doc</li>
    <li>libfsm</li>
    <li>libfsm.dev</li>
    <li>libfsm.lib</li>
  </ul>
</details>

LGTM, but why not just let the r-ryantm PR stay open? Two sequential bump commits doesn't really seem to add any value

**Comment by AndersonTorres** [comment]
> LGTM, but why not just let the r-ryantm PR stay open? Two sequential bump commits doesn't really seem to add any value

To not lose track in things like regressions between versions.
Unfortunately (?) bmake is not such a case, however other examples like cmake and meson justify this to me.

Further, it can be useful for projects like [Nix Versions](https://lazamar.co.uk/nix-versions/).

**Comment by pbsds** [comment]
Perhaps petition for r-ryantm to not force-push unless a rebase is required?

**Pull request merged**
