### PR TITLE
docker-compose: 1.5.2 -> 1.6.2

### PR DESCRIPTION
**Pull request by ericsagnes**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). 

---

Also brings the following changes:
- cached-property: init at 1.3.0
- docker-py: 1.5.0 -> 1.7.2
- dockerpty: 0.3.4 -> 0.4.1

### CODE REVIEW

**Comment by joachifm** [comment]
Please de-compose this into separate commits

**Comment by ericsagnes** [comment]
@joachifm Thanks for pointing, done.

**Comment by domenkozar** [comment]
`py` fails to pass tests on py35, maybe also needs a bump?

**Comment by ericsagnes** [comment]
@domenkozar `cached-property` test was failing because of missing `freezegun`, I updated the PR so it should work now.
`docker-compose` support python 3 so I removed the `disabled = isPy3k || isPyPy;` line. (I am not sure if the `isPyPy` was ok to remove but it seems to work fine)

It is my first contribution to python packages so any review is welcome.

**Comment by joachifm** [comment]
@FRidh may be able to provide some feedback

**Comment by ericsagnes** [comment]
Thanks for merging!

**Pull request merged**
