### PR TITLE
pass: refactor extension packaging

### PR DESCRIPTION
**Pull request by tadfisher**
###### Motivation for this change

It was pointed out in a [`pass-otp` PR](https://github.com/NixOS/nixpkgs/pull/36308#issuecomment-380070642) that the `pass-otp` derivation doesn't actually work, because it's not included in the `pass` environment. For context, `pass` requires extension scripts to live in `${pass}/lib/password-store/extensions`, and those scripts can have external dependencies of their own.

I looked at adding `pass-otp` to the existing `pass` derivation but it was looking a bit nasty to hack in there, as the derivation built a set of extensions unconditionally and included them in the `pass` output.

So I refactored the derivation to clean up some things:

- Build a `pass-extensions-env` environment and link that output to `${pass}/lib/password-store/extensions/`.
- Split extension derivations into `extensions/*.nix`, which can include their own dependencies independently of the generic `pass` derivation.
- Add a `pass.withExtensions` passthru function which builds `pass` with a configurable extensions environment, as in

```nix
pass.withExtensions (ext: with ext; [ pass-otp pass-tomb pass-import pass-update ])
```

- Add a top-level `passExtensions` attribute to facilitate discovering extensions.
- Support the `pass-otp` attribute and the `tombPluginSupport ? false` argument for backwards-compatibility.
- Fix `pass-import`, as it doesn't work currently without a `python.withPackages` python environment.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tadfisher** [comment]
cc maintainers: @lovek323 @the-kenny @fpletz @jwiegley

**Comment by tadfisher** [comment]
@GrahamcOfBorg build pass pass-otp

**Comment by tadfisher** [comment]
@GrahamcOfBorg build passExtensions.import passExtensions.otp passExtensions.tomb passExtensions.update

**Comment by peterhoeg** [comment]
As the person who added the previous plugins, thank you for doing this properly. :+1:

**Comment by Mic92** [comment]
When I try to build this: 

(pass.withExtensions (ext: with ext; [ otp tomb import update ]))

I get:

```
error: value is a partially applied built-in function while a set was expected, at /home/joerg/git/nixpkgs/.review/pr-39121/pkgs/tools/security/pass/default.nix:28:35
(use '--show-trace' to show detailed location information)
```

**Comment by tadfisher** [comment]
Ah, that would be the `import` extension :)

@Mic92 Any suggestions for an alternative name?

**Comment by Mic92** [comment]
@tadfisher pass-import?

**Comment by tadfisher** [comment]
@Mic92 @etu Renamed packages, and moved `pkgs.pass-otp` to aliases.nix.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
