### PR TITLE
keybase,keybase-gui: 3.2.2 -> 4.0.0

### PR DESCRIPTION
**Pull request by madjar**
###### Motivation for this change

Upgrade keybase to 4.0.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ggPeti** [comment]
Doesn't build on Mojave.
image

**Comment by madjar** [comment]
Mmmm, I'm not able to reproduce on Mojave (10.14.5). I'm not sure what the difference could be.

**Comment by ggPeti** [comment]
Sorry, my bad. I was building from the wrong commit. It builds and works correctly.
image
Btw, why is the result called `result-bin`?

**Comment by madjar** [comment]
I think it might be because `buildGoPackage` defines multiple outputs (`outputs = [ "bin" "out" ];` in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-packages/generic/default.nix#L232), and the binary ends up in the `bin` one, which gets the `result-bin` symlink. I assume if we were building a go library, the library parts would end up in `bin` (symlinked in `result`).

Shall we merge this?

**Comment by ggPeti** [comment]
I support that motion. Not a contributor though. Yet.

**Pull request merged**
