### PR TITLE
gitleaks: 8.11.2 -> 8.12.0

### PR DESCRIPTION
**Pull request by superherointj**
gitleaks: 8.11.2 -> 8.12.0
* Fix version.
* Add version test.
* Add shell completion.

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 189817` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitleaks</li>
  </ul>
</details>

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 189817` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitleaks</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
This derivation exposes a `config` executable. Should we rename it to `gitleaks-config`?

**Comment by superherointj** [comment]
> This derivation exposes a `config` executable. Should we rename it to `gitleaks-config`?

I'd prefer to leave it as it is. Because I'm not aware of it's use/consequences.
Maybe package maintainer @fab can tell.

**Pull request merged**
