### PR TITLE
telegram-desktop.tg_owt: 0-unstable-2024-08-04 -> 0-unstable-2024-10-28

### PR DESCRIPTION
**Pull request by ilya-fedin**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Result of `nixpkgs-review pr 353220` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>materialgram</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>_64gram</li>
    <li>kotatogram-desktop</li>
    <li>kotatogram-desktop-with-webkit</li>
    <li>telegram-desktop</li>
  </ul>
</details>

**Comment by ilya-fedin** [comment]
It mostly just has the reordered_opaque patch integrated
```diff
 git diff dc17143230b5519f3c1a8da0079e00566bd4c5a8..8198c4d8b91e22d68eb5c7327fd408e3b6abcc79
diff --git a/cmake/init_target.cmake b/cmake/init_target.cmake
index f3d7ba9c..9fa33c87 100644
--- a/cmake/init_target.cmake
+++ b/cmake/init_target.cmake
@@ -44,23 +44,25 @@ function(init_target target_name) # init_target(my_target folder_name)
             HAVE_SSE2
         )
 
-        target_compile_options(${target_name}
-        PRIVATE
-            /W1
-            /wd4715 # not all control paths return a value.
-            /wd4244 # 'initializing' conversion from .. to .., possible loss of data.
-            /wd4838 # conversion from .. to .. requires a narrowing conversion.
-            /wd4305 # 'return': truncation from 'int' to 'bool'.
-            /wd4068 # unknown pragma 'clang'
+        if (MSVC) # implies not MINGW
+            target_compile_options(${target_name}
+            PRIVATE
+                /W1
+                /wd4715 # not all control paths return a value.
+                /wd4244 # 'initializing' conversion from .. to .., possible loss of data.
+                /wd4838 # conversion from .. to .. requires a narrowing conversion.
+                /wd4305 # 'return': truncation from 'int' to 'bool'.
+                /wd4068 # unknown pragma 'clang'
 
-            # C++20: enum-s used as constants in WebRTC code.
-            /wd5055 # operator 'X': deprecated between enumerations and floating-point types
+                # C++20: enum-s used as constants in WebRTC code.
+                /wd5055 # operator 'X': deprecated between enumerations and floating-point types
 
-            /MP     # Enable multi process build.
-            /EHsc   # Catch C++ exceptions only, extern C functions never throw a C++ exception.
-            # /Zc:wchar_t- # don't tread wchar_t as builtin type
-            /Zi
-        )
+                /MP     # Enable multi process build.
+                /EHsc   # Catch C++ exceptions only, extern C functions never throw a C++ exception.
+                # /Zc:wchar_t- # don't tread wchar_t as builtin type
+                /Zi
+            )
+        endif()
     else()
         if (APPLE)
             target_compile_options(${target_name}
@@ -105,7 +107,7 @@ function(init_feature_target target_name feature)
     init_target(${target_name})
 
     set(option "")
-    if (WIN32)
+    if (MSVC)
         if (${feature} STREQUAL "avx")
             set(option /arch:AVX)
         elseif (${feature} STREQUAL "avx2")
diff --git a/src/modules/congestion_controller/goog_cc/loss_based_bwe_v2.h b/src/modules/congestion_controller/goog_cc/loss_based_bwe_v2.h
index 34c96c66..52673c94 100644
--- a/src/modules/congestion_controller/goog_cc/loss_based_bwe_v2.h
+++ b/src/modules/congestion_controller/goog_cc/loss_based_bwe_v2.h
@@ -86,6 +86,7 @@ class LossBasedBweV2 {
   };
 
   struct Config {
+    Config() {};
     double bandwidth_rampup_upper_bound_factor = 0.0;
     double bandwidth_rampup_upper_bound_factor_in_hold = 0;
     double bandwidth_rampup_hold_threshold = 0;
diff --git a/src/modules/video_coding/codecs/h264/h264_decoder_impl.cc b/src/modules/video_coding/codecs/h264/h264_decoder_impl.cc
index 98c55a21..644c54f3 100644
--- a/src/modules/video_coding/codecs/h264/h264_decoder_impl.cc
+++ b/src/modules/video_coding/codecs/h264/h264_decoder_impl.cc
@@ -233,7 +233,6 @@ int H264DecoderImpl::AVGetBuffer2(AVCodecContext* context,
   int total_size = y_size + 2 * uv_size;
 
   av_frame->format = context->pix_fmt;
-  av_frame->reordered_opaque = context->reordered_opaque;
 
   // Create a VideoFrame object, to keep a reference to the buffer.
   // TODO(nisse): The VideoFrame's timestamp and rotation info is not used.
@@ -381,8 +380,6 @@ int32_t H264DecoderImpl::Decode(const EncodedImage& input_image,
     return WEBRTC_VIDEO_CODEC_ERROR;
   }
   packet->size = static_cast<int>(input_image.size());
-  int64_t frame_timestamp_us = input_image.ntp_time_ms_ * 1000;  // ms -> μs
-  av_context_->reordered_opaque = frame_timestamp_us;
 
   int result = avcodec_send_packet(av_context_.get(), packet.get());
 
@@ -399,10 +396,6 @@ int32_t H264DecoderImpl::Decode(const EncodedImage& input_image,
     return WEBRTC_VIDEO_CODEC_ERROR;
   }
 
-  // We don't expect reordering. Decoded frame timestamp should match
-  // the input one.
-  RTC_DCHECK_EQ(av_frame_->reordered_opaque, frame_timestamp_us);
-
   // TODO(sakal): Maybe it is possible to get QP directly from FFmpeg.
   h264_bitstream_parser_.ParseBitstream(input_image);
   absl::optional<int> qp = h264_bitstream_parser_.GetLastSliceQp();
```

**Comment by NickCao** [comment]
Can we have the update to https://github.com/telegramdesktop/tdesktop/releases/tag/v5.7.1 in the same PR?

**Comment by ilya-fedin** [comment]
It would be problematic due to ffmpeg... I just wanted to move the fetchpatch so it won't be needed for future updates backports from unstable to 24.11

**Comment by NickCao** [comment]
> It would be problematic due to ffmpeg...

Why?

**Comment by ilya-fedin** [comment]
> Why?

Upstream tests only with 6.1.1 and 5.7.x has lots of new ffmpeg code not ported to ffmpeg 7

**Comment by NickCao** [comment]
@ofborg build telegram-desktop kotatogram-desktop

**Review by NickCao — APPROVED** [review]
diff LGTM, waiting for build.

**Pull request merged**
