### PR TITLE
youtube-dl: 2019.07.12 -> 2019.07.16

### PR DESCRIPTION
**Pull request by xrelkd**
###### Motivation for this change
Update `youtube-dl` to the latest release.
https://github.com/ytdl-org/youtube-dl/releases/tag/2019.07.16
**NOTE**: Updates to `youtube-dl` should be backported, thanks!
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Yarny0** [comment]
Review per https://nixos.org/nixpkgs/manual/#sec-reviewing-contributions and top comment in https://raw.githubusercontent.com/NixOS/nixpkgs/master/.github/PULL_REQUEST_TEMPLATE.md .

##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on `x86_64-linux`
- [x] executables tested on `x86_64-linux`
- [ ] all depending packages build: *only `mpv`*

##### Comments

* Notifying maintainer @enzime (other are already listed in reviewer list).
* Successfully tested `${youtube-dl}/bin/youtube-dl` with a YouTube video.
* Successfully tested `${mpv}/bin/mpv` with a YouTube video.
* Not tested many other depending packages.
* I support the request for backporting.

**Comment by xrelkd** [comment]
Hello, @worldofpeace, `youtube-dl` has been updated again.
Could you review this PR?
Thank you very much!

**Comment by worldofpeace** [comment]
backported in 76cb4fe05f7c720d9991f038d6e6be6a7e15c254

**Comment by worldofpeace** [comment]
> Hello, @worldofpeace, `youtube-dl` has been updated again.
> Could you review this PR?
> Thank you very much!

feel free to ping me for merge/review

**Pull request merged**
