### PR TITLE
gimp: 2.10.20 -> 2.10.22

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
https://www.gimp.org/news/2020/10/07/gimp-2-10-22-released/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 99990` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>gimpPlugins.exposureBlend</li>
    <li>gimpPlugins.focusblur</li>
    <li>gimpPlugins.texturize</li>
    <li>gimpPlugins.ufraw</li>
    <li>ufraw</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>gimp</li>
    <li>gimp-with-plugins</li>
    <li>gimpPlugins.fourier</li>
    <li>gimpPlugins.gap</li>
    <li>gimpPlugins.gimplensfun</li>
    <li>gimpPlugins.gmic</li>
    <li>gimpPlugins.lightning</li>
    <li>gimpPlugins.lqrPlugin</li>
    <li>gimpPlugins.resynthesizer</li>
    <li>gimpPlugins.waveletSharpen</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Review by jtojnar — COMMENTED** [review]
> It is to be noted that, even though GIMP minimum requirement is babl 0.1.78, we advise to build against the latest version if possible, i.e. babl 0.1.82. This last version handles more complex parametric TRCs for ICCv4, which means that without these changes, your color profile conversion may be wrong in case you use a profile with these parameters.

**Comment by jtojnar** [comment]
Babl changes: https://gitlab.gnome.org/GNOME/babl/-/blob/BABL_0_1_82/NEWS#L6-9

**Review by jtojnar — APPROVED** [review]

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
