### PR TITLE
Fix several broken python packages

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

qutip takes 2 hours to run tests... what would be a better way? Otherwise full test suite enabled on broken packages and all tests pass.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by costrouc** [comment]
I opened an issue with qutip asking what would be the recommended subset of tests to run such that we can have it complete a build in around 10 minutes. https://github.com/qutip/qutip/issues/1147.

**Comment by akirakyle** [comment]
Any progress on this? It looks like qutip moved testing to pytest and have a faster subset of tests that can be run.

**Comment by tobiasBora** [comment]
Any update on that? I would need qutip.

**Comment by jonringer** [comment]
discordpy qutip and sparse have already been bumped, not sure about the other two

**Comment by tobiasBora** [comment]
What do you mean by bumped? You mean removed from nixpkgs? If yes any idea why? I'm thinking to bring qutip back.

**Comment by jonringer** [comment]
bumped means updated or brought attention to

they have not been removed

also, this PR is very old by python standards. We should probably close

**Comment by jonringer** [comment]
this has conflicts with most packages. going to close

**Pull request closed without merging**
