### PR TITLE
No more mass pings due to the wrong base branch [skip treewide]

### PR DESCRIPTION
**Pull request by infinisil**
This is an intentional final mass ping to make a PSA to everybody who's been plagued by unnecessary mass pings for all these years, because it won't happen any longer!

This is because [since](https://github.com/NixOS/nixpkgs/pull/336261) [recently](https://github.com/NixOS/nixpkgs/pull/347610), we're not using the GitHub-native `CODEOWNERS` file, but rather the custom [`ci/OWNERS`](https://github.com/NixOS/nixpkgs/blob/master/ci/OWNERS) and a smart [GitHub Action workflow](https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/codeowners.yml) to check it and request reviews based on it, with the major benefits of:
- When the wrong base branch is chosen, no mass ping is triggered, instead a [helpful message](https://github.com/NixOS/nixpkgs/pull/347626#issuecomment-2403675683) (and only if the user doesn't immediately fix it)
- Code owners don't need to have write access

Please spread the news that we can freely set and change the base branch now without worrying about filling up notification inboxes, and encourage more people to add themselves as code owners :rocket:

And if you spot any issues, let me know, I'll be tending to it

---

##### Original description:

Add support for Windows by changing all files to use CRLF as the file ending. Who knew it would be this simple!

---

This was sponsored by [Antithesis](https://antithesis.com/) and [Tweag](https://www.tweag.io/)! :sparkles:

### CODE REVIEW

**Comment by Frontear** [comment]
LGTM

**Review by Frontear — APPROVED** [review]

**Comment by Frontear** [comment]
On a serious note, awesome to see it worked!

**Comment by emilazy** [comment]
Please fix the `nixpkgs-vet` error. Otherwise LGTM.

**Comment by AndersonTorres** [comment]
LGTM (looks gore to me)

**Comment by infinisil** [comment]
Turns out it's not possible to request more than 15 people with normal means, so it's very much impossible to mass ping people now! This isn't great though, it's fair to mass ping if the relevant files are changed legitimately, so I'll look into how this can be addressed. To avoid further notifications, let's close and lock this now though

**Pull request closed without merging**
