### PR TITLE
rocm: 3.10.0 -> 4.0.0

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Updates the rocm stack from 3.10.0 to 4.0.0.

Please do not merge without approval from both @acowley and @Flakebi .

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I've changed the PR title to be more easily searchable.

**Comment by danieldk** [comment]
> I've changed the PR title to be more easily searchable.

Changed again, because the updated title suggests that this PR only modifies one package. If anything, the important package is `rocm-opencl-runtime` or `rocm-opencl-icd`.

**Review by Flakebi — APPROVED** [review]
Thanks! Looks and works good for me.

**Review by acowley — APPROVED** [review]
`clinfo` output looks good to me, and I've updated the overlay including `hip`.

**Comment by danieldk** [comment]
Thanks for the reviews!

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107136` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>rocclr</li>
    <li>rocm-cmake</li>
    <li>rocm-comgr</li>
    <li>rocm-device-libs</li>
    <li>rocm-opencl-icd</li>
    <li>rocm-opencl-runtime</li>
    <li>rocm-runtime</li>
    <li>rocm-smi</li>
    <li>rocm-thunk</li>
  </ul>
</details>

**Pull request merged**
