### PR TITLE
NetworkManager & plugins: upgrade to 1.2

### PR DESCRIPTION
**Pull request by obadz**
###### Motivation for this change

Upgrade NetworkManager and all its plugins to version 1.2.

Seems to work in a QEMU VM. Will test on real hosts over next few days. Help welcome.

cc maintainers @utdemir @Phreedom @rickynils @domenkozar @abbradar
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
  - [x] gnome3_18.bijiben
  - [x] gnome3_18.gdm
  - [x] gnome3_18.gnome-boxes
  - [x] gnome3_18.gnome_control_center
  - [x] gnome3_18.gnome-disk-utility
  - [x] gnome3_18.gnome-documents
  - [x] gnome3_18.gnome-music
  - [x] gnome3_18.gnome-online-miners
  - [x] gnome3_18.gnome-photos
  - [x] gnome3_18.gnome_session
  - [x] gnome3_18.gnome_settings_daemon
  - [x] gnome3_18.gnome_shell
  - [x] gnome3_18.gnome_terminal
  - [x] gnome3_18.gnome-tweak-tool
  - [x] gnome3_18.gnome-user-share
  - [x] gnome3_18.gpaste
  - [x] gnome3_18.grilo-plugins
  - [x] gnome3_18.nautilus
  - [x] gnome3_18.networkmanagerapplet
  - [x] gnome3_18.networkmanager_l2tp
  - [x] gnome3_18.networkmanager_openconnect
  - [x] gnome3_18.networkmanager_openvpn
  - [x] gnome3_18.networkmanager_pptp
  - [x] gnome3_18.networkmanager_vpnc
  - [x] gnome3_18.pomodoro
  - [x] gnome3_18.totem
  - [x] gnome3_18.tracker
  - [x] gnome3_20.bijiben
  - [x] gnome3_20.gdm
  - [x] gnome3_20.gnome-boxes
  - [x] gnome3_20.gnome_control_center
  - [x] gnome3_20.gnome-disk-utility
  - [x] gnome3_20.gnome-documents
  - [x] gnome3_20.gnome-music
  - [x] gnome3_20.gnome-online-miners
  - [x] gnome3_20.gnome-photos
  - [x] gnome3_20.gnome_session
  - [x] gnome3_20.gnome_settings_daemon
  - [x] gnome3_20.gnome_shell
  - [x] gnome3_20.gnome_terminal
  - [x] gnome3_20.gnome-tweak-tool
  - [x] gnome3_20.gnome-user-share
  - [x] gnome3_20.gpaste
  - [x] gnome3_20.grilo-plugins
  - [x] gnome3_20.nautilus
  - [x] gnome3_20.networkmanagerapplet
  - [x] gnome3_20.networkmanager_l2tp
  - [x] gnome3_20.networkmanager_openconnect
  - [x] gnome3_20.networkmanager_openvpn
  - [x] gnome3_20.networkmanager_pptp
  - [x] gnome3_20.networkmanager_vpnc
  - [x] gnome3_20.pomodoro
  - [x] gnome3_20.totem
  - [x] gnome3_20.tracker
  - [x] kde4.digikam
  - [x] kde4.kde_runtime
  - [x] kde4.kdevelop
  - [x] kde4.libnm-qt
  - [x] kde4.plasma-nm
  - [x] kde5.baloo-widgets
  - [x] kde5.dolphin
  - [x] kde5.dolphin-plugins
  - [x] kde5.gwenview
  - [x] kde5.kde-cli-tools
  - [x] kde5.kdelibs4support
  - [x] kde5.kdeplasma-addons
  - [x] kde5.kgamma5
  - [x] kde5.khelpcenter
  - [x] kde5.khotkeys
  - [x] kde5.kile
  - [x] kde5.kinfocenter
  - [x] kde5.kio-extras
  - [x] kde5.kmenuedit
  - [x] kde5.konsole
  - [x] kde5.kscreenlocker
  - [x] kde5.ksysguard
  - [x] kde5.kwin
  - [x] kde5.networkmanager-qt
  - [x] kde5.plasma-desktop
  - [x] kde5.plasma-nm
  - [x] kde5.plasma-workspace
  - [x] kde5.powerdevil
  - [x] kde5.startkde
  - [x] kde5.yakuake
  - [x] mailnag
  - [x] mkcast
  - [x] networkmanager
  - [x] networkmanagerapplet
  - [x] networkmanager_l2tp
  - [x] networkmanager_openconnect
  - [x] networkmanager_openvpn
  - [x] networkmanager_pptp
  - [x] networkmanager_vpnc
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
  - [x] Wired ethernet
  - [x] Wireless
    - [x] Add new network with password
    - [x] Delete network
  - [ ] PPTP VPN
  - [x] L2TP VPN
  - [ ] OpenVPN
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by obadz** [comment]
Checklist:

- [x] Wired ethernet
- [ ] Wireless
- [ ] PPTP VPN
- [x] L2TP VPN
- [ ] OpenVPN

**Comment by obadz** [comment]
cc @lethalman due to strong gnome dependency

**Comment by lethalman** [comment]
I can't test this atm. If it works for you or anybody else, feel free to merge.

**Comment by obadz** [comment]
@lethalman, thanks, waiting for nix-build of the nox deps to finish and will merge.

**Comment by groxxda** [comment]
@obadz great work :+1: 
You may want to cherry-pick my commits from https://github.com/groxxda/nixpkgs/commits/bump/networkmanager :

https://github.com/groxxda/nixpkgs/commit/522bf9a32f439e1db56e7451728aa574eb1a6b70 should work but i'm running into a linking failure: nmcli can't find expat (this previously got propagated from dbus through glib_dbus) - i can't find a mention of expat as a dependency though. Maybe I'm reading the changelog wrong here?

**Comment by obadz** [comment]
Hi @groxxda, those commits look good but could you put them in a separate PR and I will happily merge them once you indicate that they build & work!

**Pull request merged**
