### PR TITLE
staging-next 2023-12-01

### PR DESCRIPTION
**Pull request by vcunat**
The first past-23.11 iteration.

##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/263535
- - - 
##### Mass breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@vcunat I am getting very close to being ready with

- https://github.com/NixOS/nixpkgs/pull/268097

I would really like to merge it fairly soon, since right now I'm able to compare it against `release-23.11`.  If a job builds on `release-23.11` (in theory every job should) and also builds on the `gcc13` PR, but breaks when that PR is rebased to `staging`, then the culprit is in the ~week worth of commits between branchoff and current `staging`.

The longer I wait, the larger the divergence gets, and the harder it will be to figure out whether a failing job is due to `gcc13` or due to something that happened post-release.

Do you have any objections to me landing the `gcc13` version-bump soon?  Currently out of 51,255 jobs there are less than 412 failing jobs.  Most are leaf jobs (no referrers), so I've picked all the low-hanging fruit... at this point it's getting to the point of "one fix = one build succeeds".

**Comment by fabianhjr** [comment]
Fixed conflict with krita

    krita: 5.1.5 -> 5.2.0
    7a40fdc288e69ba94947c1c4ec29c0f24e461eef
    , and
    treewide: use kde mirror everywhere, don't use pname in download urls
    aa15f5066d695de4c4027bd8bdcf4cedcf58d058

**Comment by vcunat** [comment]
- [ ] `aacgain` fails with `autoreconf: error: 'configure.ac' is required`
  Perhaps the maintainer @robbinch can have a look?

**Comment by vcunat** [comment]
- `kbt` didn't survive rustct update, apparently.   (just individual package failing)
  maintainer: @figsoda
  https://hydra.nixos.org/build/243064048/nixlog/3/tail

**Comment by vcunat** [comment]
Uh, I checked NixOS -small but forgot about nixpkgs unstable job
- [ ] *-darwin stdenv bootstrap tools fail :-(
  https://hydra.nixos.org/build/243203890/nixlog/309/tail

**Pull request merged**
