### PR TITLE
sbcl: 1.4.4 -> 1.4.5

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were done:

- built on NixOS
- ran `/nix/store/60dxbmafhmx26c0nmbpqj182innp8hqg-sbcl-1.4.5/bin/sbcl --help` got 0 exit code
- ran `/nix/store/60dxbmafhmx26c0nmbpqj182innp8hqg-sbcl-1.4.5/bin/sbcl --version` and found version 1.4.5
- found 1.4.5 with grep in /nix/store/60dxbmafhmx26c0nmbpqj182innp8hqg-sbcl-1.4.5
- found 1.4.5 in filename of file in /nix/store/60dxbmafhmx26c0nmbpqj182innp8hqg-sbcl-1.4.5

cc @7c6f434c @tohl

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build lispPackages.iolib

**Comment by tohl** [comment]
Ryan Mulligan <notifications@github.com> writes:
> Semi-automatic update.

Semi-automatic?  How does this work?

Does it mean I don't have to submit patches anymore?

**Comment by ryantm** [comment]
@tohl I made a tool that finds outdated packages and tries to update them. It does it in a naive way though, so please check the results! https://github.com/ryantm/nix-update

**Comment by 7c6f434c** [comment]
On the other hand, SBCL is quite friendly to automated updates, after all, `meta.updateWalker=true;` was enough to make `update-walker` update the version in the rare cases when @tohl didn't submit a patch before I remembered to do updates…

**Comment by tohl** [comment]
Ryan Mulligan <notifications@github.com> writes:
> @tohl I made a tool that finds outdated packages and tries to update
> them. It does it in a naive way though, so please check the results!
> https://github.com/ryantm/nix-update

very good, thank you!

**Comment by tohl** [comment]
Michael Raskin <notifications@github.com> writes:
> On the other hand, SBCL is quite friendly to automated updates, after
> all, `meta.updateWalker=true;` was enough to make `update-walker`
> update the version in the rare cases when @tohl didn't submit a patch
> before I remembered to do updates…

is it described somewhere, how to do these updates?

there doesn't seem to be many packages with updateWalker=true.  Could it
be used for more packages?

**Comment by 7c6f434c** [comment]
>is it described somewhere, how to do these updates?

My specific updater is described in 
pkgs/build-support/upstream-updater/update-walker.txt

>there doesn't seem to be many packages with updateWalker=true.

It works only for packages where homepage/downloadPage is set and always
contains a direct link to the latest tarball, and the version in the 
package is specified separately. `.upstream` files for the same tool are
more flexible.

>Could it be used for more packages?

I think in general `updateScript` attribute has the best chance to 
become the dominating approach. I think this is invoked via
maintainers/scripts/update.nix
see also 
pkgs/tools/package-management/nix-update-source/default.nix
and
pkgs/os-specific/linux/tp_smapi/defailt.nix
pkgs/os-specific/linux/tp_smapi/update.nix
for a usage example and
pkgs/development/libraries/safefile/default.nix
for a hybrid approach of using my update-walker as updateScript.

**Comment by tohl** [comment]
thanks for the informative reply

**Comment by 7c6f434c** [comment]
Wait, how come it is towards staging?

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by ryantm** [comment]
I moved it to staging because OfBorg said it would affect a lot of Linux builds.

**Comment by 7c6f434c** [comment]
Less than 500. And these are fast builds, to be honest.

**Pull request closed without merging**
