### PR TITLE
python310Packages.fastapi: don't run databases tests

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Databases is incompatible with SQLAlchemy 2.0.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
OK, I guess.  I haven't really looked into other users of `.databases`, but hopefully that can be done independently.

**Comment by dotlambda** [comment]
> OK, I guess. I haven't really looked into other users of `.databases`, but hopefully that can be done independently.

Those will remain broken unless they override SQLAlchemy.

**Comment by dotlambda** [comment]
I only know of `python3.pkgs.orm`, `python3.pkgs.ormar`, and `python3.pkgs.slack-sdk` (and thus `ntfy`).
cc @jfrankenau @kamilchm @andreasfelix @fabaff @costrouc

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 220703` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.ormar</li>
    <li>python310Packages.pytest-ansible</li>
    <li>python311Packages.ormar</li>
    <li>python311Packages.pytest-ansible</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>parsedmarc (python310Packages.parsedmarc)</li>
    <li>python310Packages.slowapi</li>
    <li>python311Packages.parsedmarc</li>
    <li>python311Packages.slowapi</li>
    <li>python311Packages.sopel</li>
    <li>theharvester</li>
  </ul>
</details>
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>ansible (ansible_2_14 ,python310Packages.ansible-core)</li>
    <li>ansible-later (python310Packages.ansible-later)</li>
    <li>ansible-lint (python310Packages.ansible-lint)</li>
    <li>ansible_2_12</li>
    <li>ansible_2_13</li>
    <li>etebase-server (python310Packages.etebase-server)</li>
    <li>kargo</li>
    <li>khoj</li>
    <li>ntfy</li>
    <li>python310Packages.ansible</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.aria2p</li>
    <li>python310Packages.dependency-injector</li>
    <li>python310Packages.fastapi</li>
    <li>python310Packages.fastapi-mail</li>
    <li>python310Packages.geoip2</li>
    <li>python310Packages.mocket</li>
    <li>python310Packages.sopel</li>
    <li>ttp (python310Packages.ttp)</li>
    <li>python311Packages.ansible</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-later</li>
    <li>python311Packages.ansible-lint</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.aria2p</li>
    <li>python311Packages.dependency-injector</li>
    <li>python311Packages.etebase-server</li>
    <li>python311Packages.fastapi</li>
    <li>python311Packages.fastapi-mail</li>
    <li>python311Packages.geoip2</li>
    <li>python311Packages.mocket</li>
    <li>python311Packages.ttp</li>
    <li>soco-cli</li>
    <li>spotdl</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 220703` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.ormar</li>
    <li>python310Packages.pytest-ansible</li>
    <li>python311Packages.ormar</li>
    <li>python311Packages.pytest-ansible</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.slowapi</li>
    <li>python311Packages.slowapi</li>
    <li>python311Packages.sopel</li>
    <li>theharvester</li>
  </ul>
</details>
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>ansible (ansible_2_14 ,python310Packages.ansible-core)</li>
    <li>ansible-later (python310Packages.ansible-later)</li>
    <li>ansible-lint (python310Packages.ansible-lint)</li>
    <li>ansible_2_12</li>
    <li>ansible_2_13</li>
    <li>etebase-server (python310Packages.etebase-server)</li>
    <li>kargo</li>
    <li>khoj</li>
    <li>ntfy</li>
    <li>parsedmarc (python310Packages.parsedmarc)</li>
    <li>python310Packages.ansible</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.aria2p</li>
    <li>python310Packages.dependency-injector</li>
    <li>python310Packages.fastapi</li>
    <li>python310Packages.fastapi-mail</li>
    <li>python310Packages.geoip2</li>
    <li>python310Packages.mocket</li>
    <li>python310Packages.sopel</li>
    <li>ttp (python310Packages.ttp)</li>
    <li>python311Packages.ansible</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-later</li>
    <li>python311Packages.ansible-lint</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.aria2p</li>
    <li>python311Packages.dependency-injector</li>
    <li>python311Packages.etebase-server</li>
    <li>python311Packages.fastapi</li>
    <li>python311Packages.fastapi-mail</li>
    <li>python311Packages.geoip2</li>
    <li>python311Packages.mocket</li>
    <li>python311Packages.parsedmarc</li>
    <li>python311Packages.ttp</li>
    <li>soco-cli</li>
    <li>spotdl</li>
  </ul>
</details>

**Pull request merged**
