### PR TITLE
vimPlugins.floating-input-nvim: init at 2023-03-09

### PR DESCRIPTION
**Pull request by Kranzes**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 221001` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>75 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.falcon</li>
    <li>vimPlugins.flatten-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.floating-input-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nix-develop-nvim</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-luadev</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-rainbow2</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.onenord-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.satellite-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-manix</li>
    <li>vimPlugins.todo-comments-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.vim-snipmate</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vim-zettel</li>
    <li>vimPlugins.vimwiki</li>
  </ul>
</details>

**Comment by figsoda** [comment]
I know this is a trivial pull request, but please wait for the eval to the finish first

**Comment by Kranzes** [comment]
> I know this is a trivial pull request, but please wait for the eval to the finish first

I thought nixpkgs-review already evaluates it.

**Comment by figsoda** [comment]
I think CI is the biggest reason pushing directly to master is [not allowed, with some exceptions](https://github.com/NixOS/nixpkgs/issues/118661). I's able to catch some trivial errors that people make, which can happen even if the changes have been tested locally. There are also some related discussions [here](https://discourse.nixos.org/t/16957)

**Pull request merged**
