### PR TITLE
terragrunt: 0.25.4 -> 0.25.5

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

* remove `stdenv` (used for `stdenv.lib`) because we already have `lib`
* add myself as a maintainer
* bump terragrunt version to `0.25.5`

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS (x86_64)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 101448` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>terragrunt</li>
  </ul>
</details>

**Comment by endocrimes** [comment]
Result of `nixpkgs-review pr 101448` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>terragrunt</li>
  </ul>
</details>

**Review by endocrimes — APPROVED** [review]
works on my machine - and the lib cleanup is a nice improvement to the package

**Comment by 06kellyjac** [comment]
Thanks for the review @endocrimes 
If you're interested you can post to this Discourse thread of already reviewed PRs https://discourse.nixos.org/t/prs-already-reviewed/2617
Not sure what the protocol is with posting something that someone else has reviewed but I can post it in your stead if you'd prefer.

**Pull request merged**
