### PR TITLE
[staging] substitute() print warning if does nothing

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/21195
See discussion there

### CODE REVIEW

**Comment by Profpatsch** [comment]
It should really be an error, not a warning. There is no case in which having an empty substitution would be a sensible thing.

**Comment by Profpatsch** [comment]
It would be nice to have a comment explaining what the block of code does.

Slightly related: The nixpkgs manual for `substitute` still claims it uses `replace(1)`, when it’s actually pure bash.

**Comment by volth** [comment]
> It would be nice to have a comment explaining what the block of code does.

I commented the tricky part, the rest must be obvious.

> It should really be an error, not a warning. 

Then PR should come with the fixes of the error - with removal of fruitless ```substitute*```.
And it is not easy to fix without spotting them, which would require mass rebuild (>24h on my laptop - let hydra does it :)

**Comment by Profpatsch** [comment]
> I commented the tricky part, the rest must be obvious.

`# fail if no substitution is found (to prevent errors and unnecessary builder code)`
before the block should do the trick to gain an understanding without having to decipher cryptic bash code.

> mass rebuild (>24h on my laptop - let hydra does it :)

Yeah, let’s. I’ll create a test run on headcounter hydra against `release-small` so we get a feel for how much breaks.

**Comment by edolstra** [comment]
I disagree that it should be an error if there are no matches. There are legitimate cases where that can happen, e.g. when applying substitute to all files in a directory.

**Comment by Profpatsch** [comment]
> There are legitimate cases where that can happen, e.g. when applying substitute to all files in a directory.

Then there should be a function that takes multiple files and fails if there are no substitutions in any of them.

**Comment by volth** [comment]
> I disagree that it should be an error if there are no matches. There are legitimate cases where that can happen, e.g. when applying substitute to all files in a directory.

I guess ```substitute .... || true``` would help.

For example, ```rm``` fails when the file to delete is not exist, so we write ```rm .... || true``` to prevent the failure to propagate upwards

**Comment by Profpatsch** [comment]
Okay, if you take a look at how `substituteAll` is implemented, this is not going to work in this form:
https://headcounter.org/hydra/build/2252990/nixlog/3
(I added an exit 1 to short-circuit)

Each environment variable is tried in turn by the function, and most don’t replace anything of course. This would have to be refactored.

**Comment by volth** [comment]
So, enable it only for ```substituteInPlace``` ? 
Or only for the patterns explicitly given as params of ```--replace``` ?

**Comment by Profpatsch** [comment]
I’m not sure.
It looks to me like there’s other funny business going on, like `--subst-var` silently coercing to `""` if the variable does not exist.

**Comment by Profpatsch** [comment]
There’s also this issue: https://github.com/NixOS/nixpkgs/issues/28086

**Comment by knedlsepp** [comment]
How about introducing `maybeSubstitute` for the use case mentioned by edolstra with the current behaviour?

**Comment by volth** [comment]
That would be ```substitute .... || true```

**Comment by volth** [comment]
@GrahamcOfBorg build m4

**Comment by volth** [comment]
rebased and solved merge conflict.

I think it is safe to merge
if unnecessary ```substitute``` is found, only a warning is printed.

**Comment by volth** [comment]
This helped to spot a file rename [here](https://github.com/NixOS/nixpkgs/pull/43907/files#diff-751c255c32eeb99a6439112cf2816c0bL25)

**Comment by volth** [comment]
signatures?
Do you mean the number of arguments of ```substituteAllStream``` and ```substituteStream```.
I assume these function are internal, they have been added recently in a [refactoring commit](https://github.com/volth/nixpkgs/commit/34a3233a2e1e8ed2f005a3a86cfca02d5f2769ae).
Not sure if someone outside is using them.
cc @Ericson2314

**Comment by matthewbauer** [comment]
Ok maybe it is okay. I am just a little uncertain of this change. Maybe someone else can review it?

**Comment by Ericson2314** [comment]
Yeatg stream ones are internal. I should have given them an `_` or something. I am a bit confused on what the goal thing. I'd this the thing we'd *really* want to be an error is an unmatched `@...@`.

**Comment by volth** [comment]
At least it is useful to display the obsolete ```substituteInPlace```, those which do not match after package's version bumped.

**Comment by mboes** [comment]
There are many packages now with heaps of `substituteStream()` warnings. Like @edolstra said, there are  legitimate use cases for substitution having no effect. If I have a directory with thousands of files, many of whom do need a substitution and some do not - what should I used instead of `substituteInPlace` now? Listing explicitly all files that do need a substitution is both lots of busywork and brittle in the face of upgrades.

**Comment by matthewbauer** [comment]
> There are many packages now with heaps of substituteStream() warnings. Like @edolstra said, there are legitimate use cases for substitution having no effect. If I have a directory with thousands of files, many of whom do need a substitution and some do not - what should I used instead of substituteInPlace now? Listing explicitly all files that do need a substitution is both lots of busywork and brittle in the face of upgrades.

This warning has helped me out at least once so far. I still think it's useful to have. Perhaps we should have an option to ignore the warning though? I think that could be helpful in the case of recursive uses of ```substituteInPlace --replace```.

**Comment by Profpatsch** [comment]
We can still implement my idea from an earlier comment: 

> Then there should be a function that takes multiple files and fails if there are no substitutions in any of them.

@mboes would the above help your use-case? With a warning instead of an error, to be consistent (though I still think these should be errors).

**Pull request merged**
