### PR TITLE
tomb: add sudo to buildInputs

### PR DESCRIPTION
**Pull request by bricewge**
###### Motivation for this change
This fix the evaluation of tomb package as reported here: https://github.com/NixOS/nixpkgs/pull/57946#issuecomment-482501071.
In `installCheckPhase` stderr is not masked anymore, that way it's easier to understand why it fail.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by etu — COMMENTED** [review]
Don't we need to add sudo to the wrapProgram down on line 34 as well?

**Comment by bricewge** [comment]
No it works well without it.

**Comment by adisbladis** [comment]
@etu Wrapping sudo would not work anyway since it needs `setuid` to work.

**Comment by adisbladis** [comment]
@GrahamcOfBorg build tomb

**Pull request merged**
