### PR TITLE
dotnet-{sdk,runtime,aspnetcore}_{6,7}: mark as EOL

### PR DESCRIPTION
**Pull request by emilazy**
See <https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core>.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by JohnRTitor — APPROVED** [review]

**Comment by emilazy** [comment]
This should be backported to 24.05 too, but the more pressing issue there is that it seems like even security backports for the in‐support versions were not backported throughout the release cycle.

**Review by corngood — APPROVED** [review]

**Comment by corngood** [comment]
Is `knownVulnerabilities` going to have any impact on building or caching these packages (and dependencies), or is it just an informational thing?

> This should be backported to 24.05 too, but the more pressing issue there is that it seems like even security updates for the in‐support versions were not backported throughout the release cycle.

This is probably my fault for not being on top of backports.  Should I make a PR specifically to backport the updates with minimal changes?

**Comment by emilazy** [comment]
I’m worried about the blast radius too, but – .NET 6 has been end‐of‐life for half a year now, we can’t release 24.11 in a week’s time with versions of a complex JIT runtime that don’t have upstream security support and in the case of .NET 6 surely have known security issues that would have been fixed if they weren’t EOL. I’m not an expert in .NET, of course, so I’m not very well‐placed to coordinate a mass migration, but all the packages will still be possible to use past the security warning and migrating packages to supported versions can happen afterwards. Generally we try to remove stuff that is going to go EOL earlier in the release process than this, but I think nobody was aware of the situation here until it was [brought up on Matrix](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$UXz3-M3UdMEE73bIr9r7GVqxWMFkNyMSSxSqCtHl88I?via=nixos.org&via=matrix.org&via=tchncs.de).

As far as the targeting packages go – are those basically just interface definitions? I think those are fine, since in practice they’ll be running on a runtime that we can support.

**Comment by corngood** [comment]
> As far as the targeting packages go – are those basically just interface definitions? I think those are fine, since in practice they’ll be running on a runtime that we can support.

Yeah, that's right.  I agree, it just might slightly complicate how we tag things from nuget as EOL.

I'm not against merging this.  There aren't a lot of inter-dependencies in the dotnet packages, so most of them build relatively quickly.  I'll try to get rid of the unnecessary runtime/sdk dependencies in the near future.

**Comment by MikaelElkiaer** [comment]
I added a comment here: https://github.com/NixOS/nixpkgs/commit/65589eea8994dc9d8ea2b03d7161990b53adf402#commitcomment-149808683, but I guess this is a better place for it.

I have been searching far and wide, but I am still unsure how to properly handle this change.
Using home-manager, I just want to uninstall my 6.0 SDK and only install 8.0 and 9.0 - i. e.:

```diff
     (
       with pkgs.dotnetCorePackages;
       combinePackages [
         sdk_9_0
         sdk_8_0_3xx
-        sdk_6_0_1xx
       ]
     )
```

But I am met with `error: Package ‘dotnet-core-combined’ in /nix/store/ab78nf3ad8ly49zfyd3igw3f2n5q7fz4-source/pkgs/development/compilers/dotnet/build-dotnet.nix:212 is marked as insecure, refusing to evaluate.`.
So far I've had to either:

1. Add to my home-manager config:
    ```nix
    nixpkgs.config.permittedInsecurePackages = [
      "dotnet-core-combined"
      "dotnet-sdk-6.0.428"
      "dotnet-sdk-7.0.410"
      "dotnet-sdk-wrapped-6.0.428"
    ];
    ```
2. Run commands with `NIXPKGS_ALLOW_INSECURE=1` and `--insecure`

Anything to help me out or point me in the right direction?

**Comment by MikaelElkiaer** [comment]
> You are supposed to apply the environment variable and run the command with `--impure`, not insecure.

That was a typo, I was using `--impure`.
But, I need to do this going forward then, because even once I've removed 6.0 SDK, I still need to allow insecure/impure for 8.0 and 9.0 SDK installs.

**Comment by MikaelElkiaer** [comment]
> > But I am met with error: Package ‘dotnet-core-combined’ in /nix/store/ab78nf3ad8ly49zfyd3igw3f2n5q7fz4-source/pkgs/development/compilers/dotnet/build-dotnet.nix:212 is marked as insecure, refusing to evaluate..
> > So far I've had to either:
> 
> You shouldn't be seeing this after removing all references to 6/7. Maybe I don't understand exactly what you're doing. Could you share the command used to reproduce it?

A simple `home-manager build` or `home-manager switch` will do this.
My entire config can be seen here: https://github.com/MikaelElkiaer/dotfiles/blob/main/home/nixos/.config/home-manager/home.nix (note that this currently works as I have added the `nixpkgs.config.permittedInsecurePackages`).

**Comment by corngood** [comment]
Any chance you can get a full trace (`--show-trace`) of the evaluation error?  It sounds like something else in your environment is using the insecure SDKs.

**Comment by MikaelElkiaer** [comment]
> Any chance you can get a full trace (`--show-trace`) of the evaluation error? It sounds like something else in your environment is using the insecure SDKs.

Ahh yes, `--show-trace` revealed the actual culprit.
[roslyn-ls](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/ro/roslyn-ls/package.nix#L95) depends on these packages I was marking insecure, felt like bit of a curveball until seeing the extended log output.
Thanks a bunch @corngood! - and sorry for the confusion.

**Pull request merged**
