### PR TITLE
openiscsi: fix download url, add platforms

### PR DESCRIPTION
**Pull request by cleverca22**
###### Things done:
- [x] Built on platform(s): NixOS / Linux
- [x] Tested execution of all binary files (usually in `./result/bin/`)

### CODE REVIEW

**Comment by joachifm** [comment]
Looks good to me. By the way, I see that you are the only one to actually work on this package since 2010, would you consider adding yourself to the list of maintainers for this package?

**Comment by cleverca22** [comment]
i am wondering what i should do with it, the website the source was on has expired and been parked, so it looks like even the original devs have abandoned it

**Comment by joachifm** [comment]
@cleverca22 I think development has moved here https://github.com/mikechristie/open-iscsi

**Comment by cleverca22** [comment]
ah, i'll add it to my watch list

**Pull request merged**
