### PR TITLE
Fix scikit-build by removing no longer needed patch.

### PR DESCRIPTION
**Pull request by mildlyincompetent**
###### Motivation for this change

`scikit-build` is currently broken, as it attempts to apply a patch which was relevant for older version but is no longer required for `0.10.0`.

###### Things done

Removed the no longer necessary patch, the failure of which was preventing the package from being built. The package now builds and does not fail any tests.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @FlorianFranzen

### CODE REVIEW

**Comment by mildlyincompetent** [comment]
@GrahamcOfBorg build python37Packages.scikit-build python27Packages.scikit-build

**Comment by mildlyincompetent** [comment]
@GrahamcOfBorg build python37Packages.scikit-build

**Comment by FRidh** [comment]
@GrahamcOfBorg build python38Packages.scikit-build

**Comment by FlorianFranzen** [comment]
@mildlyincompetent You are correct. I upstreamed the patch (scikit-build/scikit-build#385) and it was included in the release 0.9.0, so it is no longer needed. Thank you for fixing this.

**Pull request merged**
