### PR TITLE
Drop Qt 5.5 and Qt 5.7 from master

### PR DESCRIPTION
**Pull request by ttuegel**
### Motivation

These releases are beyond their community support windows. Most packages can use Qt 5.6 (long-term support) or Qt 5.8 (latest).

### Testing

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Shouldn't we drop them in 17.03 then, too?

**Comment by periklis** [comment]
@ttuegel afaik there is an applied qt-5.7-patch which enables qtmultimedia on darwin. We should diff 5.7 and 5.8 for such patches and take them over to 5.8 in order to have proper darwin support. e.g. #24139

**Comment by abbradar** [comment]
@globin In 17.03 5.7 is the default Qt so we can't drop it at least. Maybe we can kill 5.5. though.

Very much yes for this, after it gets merged I want to make another attempt at unification of Qt builders (the lesser there are distinct versions the better). Currently I make a patch for current Qt and run `git diff HEAD~1 HEAD | sed 's,current_version,some_version,g | patch -p1` which is error-prone when I amend later (see for example https://github.com/NixOS/nixpkgs/commit/dd385d94684e7c09afd6ab3bd9ca19dd95bb5404).

**Comment by ttuegel** [comment]
> Shouldn't we drop them in 17.03 then, too?

Maybe. We can safely drop Qt 5.7 because the packages I pinned to Qt 5.6 seem to work fine (there were only three).

On the Qt 5.5 front, I fear I broke several packages upgrading them to Qt 5.6, like some of the proprietary packages. I will check this and see.

> The default was changed to 5.6, so this can be applied to release too. Yay!

Yes, sorry about that! I always intended 17.03 to be based on the Qt LTS release; I think that snuck into the release branch because I merged it to master right before the branch-off. 😄 

> afaik there is an applied qt-5.7-patch which enables qtmultimedia on darwin. We should diff 5.7 and 5.8 for such patches and take them over to 5.8 in order to have proper darwin support.

OK, I'll go back and pick that up. Thanks for pointing that out!

> Very much yes for this, after it gets merged I want to make another attempt at unification of Qt builders (the lesser there are distinct versions the better).

In one of my pending branches, I have eliminated the separation between Linux and Darwin setup hooks and the like. That doesn't address the differences between versions, but it's a start.

**Comment by periklis** [comment]
you missed `vogl`

**Comment by globin** [comment]
@ttuegel are you cherry-picking this to 17.03?

**Comment by ttuegel** [comment]
@globin Yes, I just did.

@periklis Taking care of that now.

**Pull request merged**
