### PR TITLE
gitrs: init at 0.3.6

### PR DESCRIPTION
**Pull request by mccurdyc**
It won't let me copy the PR description from https://github.com/NixOS/nixpkgs/pull/238858#issue-1766523680

### CODE REVIEW

**Comment by mccurdyc** [comment]
@emilylange sorry, I have no idea what happened in https://github.com/NixOS/nixpkgs/pull/238858. I just tried rebasing and it appeared that there were merge conflicts in the history or something.

I've addressed https://github.com/NixOS/nixpkgs/pull/238858#discussion_r1250911824.

Thank you for your patience! I didn't realize order mattered!

**Comment by mccurdyc** [comment]
@emilylange I think I tried rebasing and ended up doing something with `pkgs/top-level/all-packages.nix`. For some reason, I can't resolve this conflict.

**Comment by mccurdyc** [comment]
@emilylange sorry I didn't realize you marked this as draft again. Can you explain why?

Thanks!

**Comment by emilylange** [comment]
> @emilylange sorry, I have no idea what happened in #238858. I just tried rebasing and it appeared that there were merge conflicts in the history or something.

Yeah, it looks like you messed up that rebase.
Which then pinged a lot of Code Owners (a GitHub feature, which, while not strictly buggy, is certainly unwanted in such cases).
Happens quite a lot in nixpkgs, unfortunately.
Someone with committing rights then usually [locks the PR](https://github.com/NixOS/nixpkgs/pull/238858#event-9709769694), e.g.

> dasJ locked as too heated and limited conversation to collaborators

That's just to prevent any further interaction/comments on that PR, as each comment would yet another notification for all pinged (review requested) users.

No worries :)

> I didn't realize order mattered!

The nix language does not care about order.
But keeping `src` and e.g. `cargoHash` (or some other hash) below is more common in nixpkgs.
Mostly depends on who reviews your change :p

Should probably be documented somewhere, but oh well...

We are, however, working on an automatic formatter (and rules) for all of nixpkgs.
In case you are curious: https://github.com/NixOS/rfcs/pull/101

> @emilylange sorry I didn't realize you marked this as draft again. Can you explain why?

It's a precaution, that if a rebase goes sideways again, we won't ping code owners again.
PRs marked as draft only preview who would get pinged.

That's usually very helpful :)

**Comment by emilylange** [comment]
I can probably fix the merge conflict for you, if you want.

But with the PR marked as draft, feel free to try again -- without any risk involved :p

(Just make sure you don't accidentally click on "Ready for review", if there are review requests in the top right)

**Comment by mccurdyc** [comment]
@emilylange okay should be ready now! I think I rebased origin/master in the other PR instead of upstream/master.

I'll let you mark "Ready for review" 😄

**Review by emilylange — APPROVED** [review]
Awesome!

I will wait for ofborg to finish successfully and then merge :)

**Comment by mccurdyc** [comment]
Thank you so much for your patience and help!

**Pull request merged**
