### PR TITLE
vimPlugins.nvim-treesitter{,-textobjects}: use default branch and update

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change

The usage of `0.5-compat` branch is no longer needed per #148040.

Tested via `neovim`.

###### Things done

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>63 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-omni</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.compe-tmux</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-buffergator</li>
    <li>vimPlugins.vim-dispatch</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-liquid</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
as treesitter is bound to evolve, they should/will create an 0.6 branch. Let's update then

**Comment by oxalica** [comment]
> as treesitter is bound to evolve, they should/will create an 0.6 branch. Let's update then ?

In their [README](https://github.com/nvim-treesitter/nvim-treesitter), 
> Please consider the experience with this plug-in as experimental until Neovim 0.6 is released! 

I'd assume all their current development are based on Neovim 0.6, and there would be no such `0.6-compat` branch for compatibility reason. So as long as they are compatible, like other vim plugins all using HEAD, we should also switch them to `master` now.

**Comment by teto** [comment]
summoning neovim's tree-sitter specialist @vigoux !

**Comment by vigoux** [comment]
We did not update our README yet but the development of nvim-treesitter is on master only.
The 0.6-compat branche is going to be created soon.

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 148124` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-omni</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.compe-tmux</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-buffergator</li>
    <li>vimPlugins.vim-dispatch</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-liquid</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
