### PR TITLE
ion3: groff -> mandoc & fix build

### PR DESCRIPTION
**Pull request by RamKromberg**
1. didn't compile
2. had bad name/version
3. one of multiple groff -> mandoc test subjects

### CODE REVIEW

**Comment by LnL7** [comment]
can you give some context for the `groff` switch, in case I'm not the only one that's unfamiliar with it.

**Comment by RamKromberg** [comment]
@LnL7 mandoc is a light, man compiler and a man pager. It originates from the OpneBSD world and been used in Void and Alpine for a few years now.

It's more useful and efficient to compare the two "stacks":

The Man-db stack:
* Man-db: Man & mdoc pager with apropos database using Berkeley database.
* Groff: .roff to man\mdoc\pdf\html conversion. The pdf output is broken without ghostscript. The html output is broken without netpbm.
* Closure: Around 80mb not including glibc. Over 200mb when pulling for pdfs and html support.

The Mandoc stack:
* Mandoc: man & mdoc pager without apropos but with all the roff functionality necessary to do standalone man, mdoc, html and some pdf output. There's also a built-in apropos but it currently depends on mariadb so I didn't package it with that. Upstream already committed the patches for a standalone database in trunk.
* Closure: 1.3MB not including glibc. Might get to 2MB with the standalone apropos release.

So, while the real goal \ challenge is to use mandoc in the base system for Nix's man page creation, it's a fairly hard sell when no other package can demonstrate just how trivial the process can be. So, I'm starting off with a few unrelated packages to ease people into it.

Eventually, upstream will release the standalone apropos as well and that's when we'll drop man-db & groff altogether. But it will take months for that to happen so I'm focusing on getting as much as possible now even if it's just small packages that aren't really part of the base system. Again, to put a few test cases for people to feel comfortable.

Besides, it also lightens up the hydra recompilation loads: groff recompile more often then mandoc because of all it's dependencies which leads to all the other packages that depend on it going through recompilation...

Personally, I only learned about this issue when I addressed some issues with man-db and groff that lead to mass rebuilds and having to recompile systemd just to get groff to compile... I'm not expert in all of this so going at it package by package through normal reviewing (which in this case means running _man foobar_) is really the right thing to do I think.

**Comment by joachifm** [comment]
If you intend to do mandoc -> groff more generally, I think it'd be nice to perhaps raise it as an issue or post to the mailing list.

**Comment by RamKromberg** [comment]
@joachifm Raising an issue is precisely what I'm planning to do after this series of PRs. Like my motif series, I feel it's important to start by getting as many pieces into Nixpkgs as possible instead of opening a "wouldn't it be nice if we had X or did Y" kind of issue...

**Comment by joachifm** [comment]
Our default groff depends only on stdenv + perl, either of which cause huge rebuilds whenever they change, so I'm unconvinced that a switch to mandoc would help much in keeping rebuilds down. Nor am I convinced that groff greatly bloats the system closure (groff itself adds ~8MB, ~20MB if you include the doc output, the remaining stuff will be in your system closure anyway).

**Comment by RamKromberg** [comment]
@joachifm It's true that it's not a lot considering most of this stuff is in the base system already. But consider the recompilations and the travis\hydra pulls... Btw, this is the actual numbers from my mandoc PR (https://github.com/NixOS/nixpkgs/pull/18619):

```
23M /nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24
104K    /nix/store/b5mwbrx8cldkchiqgwgkaagw91xfjr89-zlib-1.2.8
1.2M    /nix/store/r6ihzh49yjhl10ignd3qgr6ags0p5w61-mandoc-1.13.4
24M total
```

```
23M /nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24
172K    /nix/store/scblgh0h3sh65s0rp0nv79rr82mjd6cm-attr-2.4.47
200K    /nix/store/6h29qi09p6p4kh04n3pyg7wa0sn7gryv-acl-2.2.52
4.7M    /nix/store/ly5dbisg2h0k3xnfdbk955m3pc4knvjk-gcc-5.4.0-lib
848K    /nix/store/n62975gpkckivvxvlhg9hjfknspxnkkm-gnused-4.2.2
832K    /nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46
11M /nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25
49M /nix/store/xcp6lrq3ynj75cqcyy7b32jgizf9jr4b-perl-5.22.2
8.6M    /nix/store/wrbnvl7f54g3dg6846c5fkx96br7z75a-groff-1.22.3
96M total
```

```
23M /nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24
172K    /nix/store/scblgh0h3sh65s0rp0nv79rr82mjd6cm-attr-2.4.47
200K    /nix/store/6h29qi09p6p4kh04n3pyg7wa0sn7gryv-acl-2.2.52
4.7M    /nix/store/ly5dbisg2h0k3xnfdbk955m3pc4knvjk-gcc-5.4.0-lib
848K    /nix/store/n62975gpkckivvxvlhg9hjfknspxnkkm-gnused-4.2.2
832K    /nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46
11M /nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25
49M /nix/store/xcp6lrq3ynj75cqcyy7b32jgizf9jr4b-perl-5.22.2
8.6M    /nix/store/72fi79z1bzx3dsi20b9yk9ji547rn4kz-groff-1.22.3
108K    /nix/store/glbqi0b5j96gs4mfkq2qsdmgamvifx5q-libpipeline-1.4.1
4.4M    /nix/store/xgaq1c135r0ibhl64s3bjjm4vcg0nmka-db-5.3.28
2.0M    /nix/store/gj8qyzznvz1clh6nz7054c5k37w0b16y-man-db-2.7.5
103M    total
```

Regarding the actual efforts involved, if it gets too troublesome I'll drop it. In the meantime, having a lighter dedicated man compiler isn't too bad a thing to have :) Especially when updating it doesn't mean recompiling systemd...

**Comment by joachifm** [comment]
> Especially when updating it doesn't mean recompiling systemd...

But wouldn't `mandoc` be used to generate `systemd`'s manual or whatever `groff` is doing now? If so, updating `mandoc` would still trigger a rebuild of `systemd`, like it would trigger a rebuild of any package that used `mandoc` as part of the build where they had previously relied on `groff`, or am I missing something?

Note that all the references `groff` picks up comes from `stdenv` or `perl`, nowhere else. Changing basically anything in `groff`'s transitive closure will probably imply a full rebuild, through no fault of `groff`'s. Changing `attr` or `acl` triggers `stdenv` rebuild just as much as bumping `glibc` does.

I just don't see the argument that `mandoc` reduces rebuilds nor that `groff` currently causes undue volalility.

Anyway, you can of course proceed as you like, but in your position I'd ask whether core people agree with the general idea first, to ensure that it's not all for naught. Also, for strategic reasons, I'd collect the work in a single series without unrelated changes thrown in, to facilitate review and testing.

**Comment by RamKromberg** [comment]
@joachifm Besides db and man-db, groff also depends on itself (https://hydra.nixos.org/build/40591698#tabs-build-deps).

More importantly, let say I fail and mandoc doesn't cover the base system: By removing groff from all those packages, we're avoiding recompiling them when groff \ systemd \ perl updates.

That is, worse case scenario is still a win-win. And a few month from now, upstream should cover a standalone apropos so that's man-db and db as well...

Btw, it's too early to say and I don't want to speculate, but it's possible we won't even need mandoc for the manuals using https://github.com/NixOS/nixpkgs/pull/18714. There's also a valid case for just duplicating the mandoc package under a different name for just the recompilation considering groff's self dependency and size... But again, this is all too early to say so I just want to get some things done now.

**Comment by joachifm** [comment]
@RamKromberg clearly I'm failing to get my point across here. The claim that groff is causing lots of unnecessary rebuilds that would magically disappear by slotting in a different man page compiler is not borne out by the evidence you have presented. I believe I have already explained why that is, so I'm not inclined to pursue this further.

**Comment by RamKromberg** [comment]
@joachifm This is my fault for wanting to get this merged and then opening an issue explaining everything. 

Here's the scenarios and possible end results I had in mind:
1. mandoc replaces groff in some packages; not the base system: The easiest and likest outcome. A change in groff or the systemd \ groff \ perl chain will still case a lot of recompilation, but a lot less.
2. mandoc replaces groff in some packages and man-db; not the base system: This might or might not happen depending on upstream. A little better the no.1 since it actually removes man-db and Berkeley database. It should happen eventually but I don't like speculating on when upstream tarballs it.
3. mandoc replaces groff in some packages, man-db and the base system: Harder to pull off. Might necessitate two mandoc derivations or a separate to-man converter from the current docbooks.

I guess your frustration is with me not detailing no.3 properly. But it's really just summing up the parts: groff is 8.6mb that are doubled because of it's self dependency. Then you have 2mb for man-db and 4mb for the db database itself. So, roughly 7 times bigger closure give or take future expansions and maybe those extra tools?

Regardless, even ignoring all of that, just switching packages to mandoc now means each package has less build dependencies.

Again, sorry for not breaking it down sooner. I was just hoping the individual PRs could stand on their own merit as pulling smaller and fewer build dependencies right now.

**Comment by RamKromberg** [comment]
Closed for now. When mandoc upstream gets the standalone database I'll update it's package and revisit the issue.

**Pull request closed without merging**
