### PR TITLE
django: add a django_gis variant which patches django to properly point ...

### PR DESCRIPTION
**Pull request by risicle**
...at its gis libs but therefore also has them as dependencies (gdal for one can be quite big)

I'm unsure as to whether this is the best way to expose this as a package, so I'm open to ideas, but this works for me.

### CODE REVIEW

**Comment by domenkozar** [comment]
Hmm, I don't see a reason our Django packages shouldn't have gis support by default.

**Comment by risicle** [comment]
Added dependencies (geos and gdal, together quite big)

**Comment by domenkozar** [comment]
@risicle could you rebase on top of master? I'd like to merge this.

**Comment by risicle** [comment]
I'll try and get it done this weekend.

**Pull request merged**
