### PR TITLE
Add an additional dependency for home-assistant

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
I've tried to set up my hue bridge with home-assistant but it failed. But then I've packaged this dep and now it works:

image

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @dotlambda @f-breidenstein

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build python27Packages.voluptuous-serialize python36Packages.voluptuous-serialize

**Comment by dotlambda** [comment]
> Ran 0 tests in 0.000s

Please specify an appropriate `checkPhase`, probably `${python.interpreter} -m unittest discover`. You might have to use `fetchFromGitHub`.

Also, do you want to maintain this package?

**Comment by etu** [comment]
@dotlambda 
I'm now marked as maintainer and fetch the source from github instead. And there's a tests directory present in the source that I get.

But I still get `Ran 0 tests in 0.000s` regardless if I add a `checkPhase` with `${python.interpreter} -m unittest discover` or not...

So not sure what to test now...

**Comment by etu** [comment]
I've tried the following, but none of them run any tests:
```diff
diff --git a/pkgs/development/python-modules/voluptuous-serialize/default.nix b/pkgs/development/python-modules/voluptuous-serialize/default.nix
index f899e869758..7954ab15155 100644
--- a/pkgs/development/python-modules/voluptuous-serialize/default.nix
+++ b/pkgs/development/python-modules/voluptuous-serialize/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, buildPythonPackage, fetchFromGitHub, voluptuous }:
+{ stdenv, buildPythonPackage, fetchFromGitHub, voluptuous, pytest, python }:
 
 buildPythonPackage rec  {
   pname = "voluptuous-serialize";
@@ -15,6 +15,20 @@ buildPythonPackage rec  {
     voluptuous
   ];
 
+  checkInputs = [
+    pytest
+  ];
+
+  checkPhase = ''
+    ${python.interpreter} -m unittest discover -s ./tests -p ./tests/test_lib.py
+    ${python.interpreter} -m unittest discover -p tests/test_lib.py
+    ${python.interpreter} -m unittest discover
+    ${python.interpreter} -m unittest tests/test_lib.py
+    ${python.interpreter} tests/test_lib.py
+    ${python.interpreter} -m unittest
+    exit 1
+  '';
+
   meta = with stdenv.lib; {
     homepage = https://github.com/balloob/voluptuous-serialize;
     license = licenses.asl20;
```

So I have no idea what more to try...

**Comment by dotlambda** [comment]
Looking at https://github.com/balloob/voluptuous-serialize/blob/master/requirements_test.txt, it seems like the pytest should be used. I've force-pushed an appropriate change and I disabled Python 2 support because the tests fail.

**Comment by etu** [comment]
@dotlambda My python knowledge is quite limited to writing basic python because I've never done any bigger projects with it.

But this looks fine to me :)

**Comment by etu** [comment]
@GrahamcOfBorg build python36Packages.voluptuous-serialize

**Comment by dotlambda** [comment]
@etu I just checked and I think I shouldn't have merged this. Did you read the first line of `component-packages.nix`?

**Comment by dotlambda** [comment]
As you can see in https://github.com/home-assistant/home-assistant/blob/dev/requirements_all.txt#L1336, this is not a dependency of the hue modules but of `config.config_entries`. Are you using the latter module?

**Comment by etu** [comment]
@dotlambda I have seen changes in `component-packages.nix` that have looked like manual edits before, I don't know how it would been generated.

Hmm, that might be the case that it's not specifically a hue dependency, I just know that it showed up in my logs when trying to use hue so I assumed it to be needed by hue.

Then I guess it should be a dep for home-assistant overall instead of hue to be able to use the config entries thingy?

**Comment by dotlambda** [comment]
It's always generated by `parse-requirements.py`, as stated in the first line.

I've no idea what config_entries is. Do you?

**Comment by etu** [comment]
No idea, but in the hass-config page there's a page named Integrations where it had discovered Hue. But when I pressed that button, nothing did happen because of this missing dependency. That's why I thought it was Hue related.

So this dependency is needed by something, but it should probably be put somewhere else.

**Comment by dotlambda** [comment]
I think it's loaded by https://github.com/home-assistant/home-assistant/blob/0.69.1/homeassistant/config_entries.py, so let's just add this as a dependency for Home Assistant directly. That's what I did in 47a08c1.

**Comment by etu** [comment]
Thanks, looks good :smile:

**Pull request merged**
