### PR TITLE
libfaketime: 0.9.9 -> 0.9.10

### PR DESCRIPTION
**Pull request by usertam**
###### Description of changes

Changelog: https://github.com/wolfcw/libfaketime/releases/tag/v0.9.10
Diff: https://github.com/wolfcw/libfaketime/compare/refs/tags/v0.9.9...v0.9.10

Drop patch `no-date-in-gzip-man-page.patch` as changes made upstream.

From https://github.com/NixOS/nixpkgs/pull/206845, _very very sorry_ for requesting reviews from everyone. Didn't close the PR when rebasing the branch D:

I did notice the change fails on `x86_64-darwin`, looking into it:
```
libfaketime.c:2345:29: error: use of undeclared identifier 'timespec_get'
  DONT_FAKE_TIME(result = (*timespec_get)(ts, base));
                            ^
libfaketime.c:4022:38: error: use of undeclared identifier 'timespec_get'
  DYLD_INTERPOSE(macos_timespec_get, timespec_get);
                                     ^
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by usertam** [comment]
Added patch [0001-libfaketime.c-wrap-timespec_get-in-TIME_UTC-macro.patch](https://github.com/NixOS/nixpkgs/pull/206860/commits/aa023bea56f9b5a7f8a6984ff0ff18b7c7713780#diff-1fc75addc9b6e0f7e011a9cffb5f500147df00040942071826f00b960c8c225a) to fix source not building on `x86_64-darwin`; but maybe it'd be better to wait for upstream to merge the [PR](https://github.com/wolfcw/libfaketime/pull/415).

**Comment by usertam** [comment]
PR just merged by upstream :D

**Comment by usertam** [comment]
ready for merge?
ping pong @bjornfor :D

**Comment by bjornfor** [comment]
Now that the patch was merged, perhaps fetch it from upstream instead of adding it verbatim to  nixpkgs?

**Comment by usertam** [comment]
> Now that the patch was merged, perhaps fetch it from upstream instead of adding it verbatim to nixpkgs?

It's done.

**Comment by bjornfor** [comment]
> Drop patch no-date-in-gzip-man-page.patch as changes made upstream.

Can you put that in the commit message please? And also in the commit message, why you're adding that new patch?

**Comment by usertam** [comment]
> > Drop patch no-date-in-gzip-man-page.patch as changes made upstream.
> 
> Can you put that in the commit message please? And also in the commit message, why you're adding that new patch?

Both done! Let me know if anything else is needed.

**Review by bjornfor — APPROVED** [review]

**Pull request merged**
