### PR TITLE
nextcloud: 23.0.6 -> 23.0.7

### PR DESCRIPTION
**Pull request by yayayayaka**
###### Description of changes
- https://nextcloud.com/changelog/#latest23

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yayayayaka** [comment]
The NixOS test failed.

Cannot build redis-7.0.4 on master:
```
[...]
redis> !!! WARNING The following tests failed:
redis> *** [err]: replica buffer don't induce eviction in tests/unit/maxmemory.tcl
redis> Expected 24624 > 2*1024*1024 (context: type eval line 78 cmd {assert {$slave_buf > 2*1024*1024} } proc ::test)
redis> *** [TIMEOUT]: clients state report follows.
redis> Cleanup: may take some time... OK
error: build of '/nix/store/bh3vhvsjnhq16idixwj75vfnaip5m7y8-redis-7.0.4.drv' failed: builder for '/nix/store/bh3vhvsjnhq16idixwj75vfnaip5m7y8-redis-7.0.4.drv' failed with exit code 1;
       last 10 log lines:
       >   119 seconds - integration/replication
       >   129 seconds - integration/aof-multi-part
       >   196 seconds - integration/replication-psync
       >
       > !!! WARNING The following tests failed:
       >
       > *** [err]: replica buffer don't induce eviction in tests/unit/maxmemory.tcl
       > Expected 24624 > 2*1024*1024 (context: type eval line 78 cmd {assert {$slave_buf > 2*1024*1024} } proc ::test)
       > *** [TIMEOUT]: clients state report follows.
       > Cleanup: may take some time... OK
       For full logs, run 'nix log /nix/store/bh3vhvsjnhq16idixwj75vfnaip5m7y8-redis-7.0.4.drv'.
error: builder for '/nix/store/bh3vhvsjnhq16idixwj75vfnaip5m7y8-redis-7.0.4.drv' failed with exit code 1;
       last 10 log lines:
       >   119 seconds - integration/replication
       >   129 seconds - integration/aof-multi-part
       >   196 seconds - integration/replication-psync
       >
       > !!! WARNING The following tests failed:
       >
       > *** [err]: replica buffer don't induce eviction in tests/unit/maxmemory.tcl
       > Expected 24624 > 2*1024*1024 (context: type eval line 78 cmd {assert {$slave_buf > 2*1024*1024} } proc ::test)
       > *** [TIMEOUT]: clients state report follows.
       > Cleanup: may take some time... OK
       For full logs, run 'nix log /nix/store/bh3vhvsjnhq16idixwj75vfnaip5m7y8-redis-7.0.4.drv'.
error: 1 dependencies of derivation '/nix/store/5ilmjj0mwjyzirvd64z170b8ywjhjab7-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hf642qjsrgainkgsjpkg8k008cjjvfv4-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/754l7n1yb1kmvq2nl59fk3d86pxvd9df-unit-redis.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7nz5s91dba1nyyn54jnrhmap6amlb602-nixos-system-nextcloud-22.11pre-git.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xyi4klmw8fy96avslsp4r8d85nc8c3h3-nixos-system-nextcloud-22.11pre-git.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gwbkj2x1n65ysabi4a5614p7y5xxklp3-nixos-vm.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xgq8lhs0rv2r4hi72rw6hqwwfys9zm89-nixos-vm.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4f4mgvfcif44gdqdmpwjy1dcag0jkh1n-nixos-test-driver-nextcloud-with-postgresql-and-redis.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h5c0cxclik0grv15j7jnyls2q4xcdc52-nixos-test-driver-nextcloud-with-postgresql-and-redis.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mrv2xsxkqqjvnvqhqs4idyh8nbpssgdd-vm-test-run-nextcloud-with-postgresql-and-redis.drv' failed to build
```

**Comment by lovesegfault** [comment]
Argh, I landed my bump of `nextcloud24` before seeing this. I had tested it before staging got merged and broke redis.

**Comment by yayayayaka** [comment]
Now that redis has been built by hydra, I was able to finish the NixOS test.

**Comment by Ma27** [comment]
@yayayayaka considering that @lovesegfault already merged their PR, would you mind removing the nextcloud24 change?:)

**Comment by yayayayaka** [comment]
sure!

**Pull request merged**
