### PR TITLE
discord: add a script to disable breaking updates

### PR DESCRIPTION
**Pull request by Artturin**
Check the docstring

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
i don't know if the script will work on darwin

**Comment by Infinidoge** [comment]
At a glance, this looks good to me, but testing it is slightly annoying so I haven't done that yet.

**Comment by Artturin** [comment]
To test check the settings.json ex `.config/discordcanary/settings.json`  before and after running `NIXPKGS_ALLOW_UNFREE=1 nix run --impure "github:Artturin/nixpkgs/discord-disable-breaking-updates#discord-canary.disableBreakingUpdates"`

**Review by benley — APPROVED** [review]
This is awesome, I was getting really tired of discord self-destructing so frequently when they push updates.

**Comment by Infinidoge** [comment]
> To test check the settings.json ex `.config/discordcanary/settings.json` before and after running `NIXPKGS_ALLOW_UNFREE=1 nix run --impure "github:Artturin/nixpkgs/discord-disable-breaking-updates#discord-canary.disableBreakingUpdates"`

I was more so referring to testing that older host versions then run properly, however yeah that should be good enough.

**Comment by Artturin** [comment]
> > To test check the settings.json ex `.config/discordcanary/settings.json` before and after running `NIXPKGS_ALLOW_UNFREE=1 nix run --impure "github:Artturin/nixpkgs/discord-disable-breaking-updates#discord-canary.disableBreakingUpdates"`
> 
> I was more so referring to testing that older host versions then run properly, however yeah that should be good enough.

```
# verify that there's no SKIP_HOST_UPDATE in settings.json and if there is then remove it and the last ','
# 7b38cb118ce is one commit before discord-canary: 0.0.139 -> 0.0.140
NIXPKGS_ALLOW_UNFREE=1 nix run "github:nixos/nixpkgs/7b38cb118ce#discord-canary" --impure
# observe that discord cannot start
NIXPKGS_ALLOW_UNFREE=1 nix run --impure "github:Artturin/nixpkgs/discord-disable-breaking-updates#discord-canary.disableBreakingUpdates"
NIXPKGS_ALLOW_UNFREE=1 nix run "github:nixos/nixpkgs/7b38cb118ce#discord-canary" --impure
# observe that discord starts

**Comment by Artturin** [comment]
backport https://github.com/NixOS/nixpkgs/pull/197266

**Pull request merged**
