### PR TITLE
freetds: 0.91 -> 1.00.70

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

While the library upgrade itself is fine, there is some fallout from this that I haven't fixed yet.

Cc: #31171 @ryantrinkle @c0bw3b 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
So this works now with 2 caveats:

a) We need a commit on master to make php work again
b) calligra2 breaks, but it is deprecated (based on kde4) and we already carry calligra3 (based on kf5)

**Comment by peterhoeg** [comment]
Cc @Phreedom and @ebzzry as calligra maintainers.

**Comment by c0bw3b** [comment]
Upstream current stable is now 1.00.70
Since this is going to rebuild lots of php things anyway... :)

**Comment by peterhoeg** [comment]
Thanks all!

**Pull request merged**
