### PR TITLE
Librenms sql socket

### PR DESCRIPTION
**Pull request by sgrimee**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by johannwagner** [comment]
Hey,

thanks for your contribution.
I am willing to support the changes regarding the `mysqld` socket usage.

The PR is not aligned with the CONTRIBUTING.md and also adds a lot of different changes, also for Nagios Plugins and so on. You at least need to split those changes in different commits and all your work should be aligned with the CONTRIBUTING.md.

**Comment by sgrimee** [comment]
@johannwagner thank you so much for reviewing! I am very new to this so I appreciate your guidance very much.
Looking at CONTRIBUTING.md, I saw that my commit messages were not aligned. I have tried to fix it now. I believe that was it, please kindly let me know if I am missing other guidelines.

I have combined other changes in the PR as they are small fixes that I believe are needed for the package to function properly. I am happy to move then to another PR if that is preferable?
Every change is in its own commit.

**Comment by johannwagner** [comment]
Hey,

thanks for your changes. We run this setup at @WOBCOM and it functions properly - but we are not using nagios. Since I do not have a lot experience for those wild PRs either, I would
like to ask @yu-re-ka for a review 👉👈

**Comment by sgrimee** [comment]
@johannwagner are you using Services in LibreNMS? Did your install render graphs correctly with `rrdtool` or did you have to install it separately, and graphviz?

The way I understand it, when you want to use services, you need to use nagios plugins. These are installed by package `monitoring-plugins`. LibreNMS uses the config variable `nagios_plugins` to know where to find all the check_* plugins binaries. When they are not installed, or the config points to the wrong path, you do not see any services in the `check type` drop down, as per attached image. 
missing_plugins

The current librenms package sets the default value for `nagios_plugins` config entry to the path of the monitoring-plugin incorrectly in the `installPhase`.
Also, since it is not in `buildInputs`, the `monitoring-plugins` package may not be present when LibreNMS tries to access it. I may be wrong there, but in my experiments when I remove it from buildInputs it breaks the Services.

So I have included one commit to make sure the package is installed, and one commit to fix the path.
As there are several other packages in that case rrdtool, graphviz, ...  I have included them as well if they are referenced in the buildInputs.

**Comment by johannwagner** [comment]
The tests are racey, not sure how to deal with those in terms of this PR. snmpd stops on the 2nd machine and then the test hangs. This is probably not related to this PR.

**Comment by johannwagner** [comment]
I fixed the racey tests, I hope, we can merge this afterwards :tada:

**Pull request merged**
