### PR TITLE
godot_4: 4.2.2-stable -> 4.3-stable

### PR DESCRIPTION
**Pull request by superherointj**
godot_4: 4.2.2-stable -> 4.3-stable

- migrate to pkgs/by-name
- refactor
- nixfmt
- order by phases order, alphabetical order
- fix cross compilation
  - Courtesy of @AndersonTorres

Fixes #334942

### CODE REVIEW

**Comment by superherointj** [comment]
> v4.3 was released [today](https://github.com/godotengine/godot/releases). Can you include that as well?

Goal was to do the refactor before the upgrade.

**Comment by superherointj** [comment]
@Haskellered Please review.

**Comment by Haskellered** [comment]
LGTM

**Review by AndersonTorres — APPROVED** [review]
Nice work!

**Pull request merged**
