### PR TITLE
openrgb: 0.6 -> 0.7

### PR DESCRIPTION
**Pull request by squarepear**
###### Motivation for this change
Update package for newest features.

I haven't contributed a package update before. I'm pretty sure I did the hash correctly, but please let me know if I missed something.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 152714` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>openrgb</li>
  </ul>
</details>

**Comment by SquarePear** [comment]
Hmm, I don't get this error locally when I run `nix-build -A openrgb`. Should I add mbedtls to nativeBuildInputs?

**Comment by SquarePear** [comment]
Odd, I just ran it again and now I am getting the error. Adding mbedtls seems to have fixed it

**Comment by Kranzes** [comment]
> Hmm, I don't get this error locally when I run `nix-build -A openrgb`. Should I add mbedtls to nativeBuildInputs?

I am not familiar with mbedtls, are you sure if it needs to be in nativeBuildInputs and not something like buildInputs?

**Comment by Kranzes** [comment]
I believe it should go in buildInputs rather than nativeBuildInputs.

**Comment by SquarePear** [comment]
Looking at it again that probably makes sense. Should I revert the commit or just make another to fix it?

**Comment by Kranzes** [comment]
just use good ol'  `--amend` and force push.

**Comment by Kranzes** [comment]
Perhaps you could also add the dependency addition commit to the version bump commit? So it's all nicely in a single commit.

**Comment by SquarePear** [comment]
Still getting used to the more "complicated" git commands, but this should be good now

**Comment by jonringer** [comment]
> Still getting used to the more "complicated" git commands, but this should be good now

Also everything can be fixed with git rebase -i

 `git rebase -i` is a powerful command which achieves this, I created a small video demonstrating it's use [here](https://www.youtube.com/watch?v=OR8Q-4PLalc). A more indepth text tutorial can be found [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Review by jonringer — APPROVED** [review]
diff LGTM
gui launches fine

```
https://github.com/NixOS/nixpkgs/pull/152714

1 package built:
openrgb
```

**Pull request merged**
