### PR TITLE
WIP KDE5: fix breakage due to set -u changes

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
I don't know why konsole was broken. It seems odd to me. Maybe the fix in the hook is not correct. Checking other KDE components now as well.

**Comment by FRidh** [comment]
Adding dependencies like I did is I think the wrong way because most KDE applications are now broken. That has to be due to propagation or the hook.

**Review by Ericson2314 — COMMENTED** [review]
Looks good. FWIW I've been trying to do `${foo-}` rather than `${foo:-}` as they are the same (only matters when something is right of the `-`), and I decided the latter is more complex for the same job.

**Comment by FRidh** [comment]
I've pushed the hooks to staging-next.

**Comment by Ericson2314** [comment]
Are these remaining changes `set -u` related?

**Comment by FRidh** [comment]
Well, nothing else has changed anywhere close to KDE packaging as far as I can tell.

**Comment by FRidh** [comment]
Bisecting with this large staging-next change is not going to be fun

**Comment by Ericson2314** [comment]
@FRidh Or simplier put, what is the symptom this fixes, and how do I reproduce this on mastertoday?

**Comment by jtojnar** [comment]
@Ericson2314 `nix-build -A kdeApplications.konsole`:

https://hydra.nixos.org/build/107199242/nixlog/1

**Comment by jtojnar** [comment]
git bisect points to 13bab298fc1ad49db5449b262125d25d849bc90e, perhaps the `hookName` should be properly escaped. Though I do not see how it is not a syntax error.

**Comment by FRidh** [comment]
Yes, it's missing the ''. Did a successful build with that fixed.

**Comment by jtojnar** [comment]
Are you pushing the fix?

**Comment by FRidh** [comment]
Done, c3c84bbb2cc6a2cc3d63e0a9efe815dc2650b462 and
c8acd481728c9e2bdbd68880e0c0e6dbad59a790

**Comment by Ericson2314** [comment]
Should use `[[` too as you will get a problem of too few args with empty string.

**Comment by Ericson2314** [comment]
Also consider plain `${foo-}` to rule out the URL possibility.

**Comment by worldofpeace** [comment]
Having problems with kwin like
```
building '/nix/store/svr5q5q3i7ja9wv0d23brbs2bdcp092c-kwin-5.16.5.drv'...
/nix/store/mq2hcss5fc5g3127z22abpy0a3lk9zk0-breeze-qt5-5.16.5-dev/nix-support/setup-hook: line 5: propagatedUserEnvPkgs: unbound variable
builder for '/nix/store/svr5q5q3i7ja9wv0d23brbs2bdcp092c-kwin-5.16.5.drv' failed with exit code 1
error: build of '/nix/store/svr5q5q3i7ja9wv0d23brbs2bdcp092c-kwin-5.16.5.drv' failed
```

currently blocking the channel.

**Comment by Ericson2314** [comment]
Well those responses were for the linked commits. This PR is fine; I still don't know why it became necessary, but the deep dives we've done into other issues didn't turn up fundimental problems, so I'll just let my lack of knowledge here slide.

**Comment by FRidh** [comment]
this should not have gone in because these changes were not needed

**Comment by Ericson2314** [comment]
Oh. I'm sorry, I thought they were. Should have remembered the WIP.

**Comment by FRidh** [comment]
latest fix 646b279c55780fa8cfe79b2a3b1e3ab53b445be7

**Pull request merged**
