### PR TITLE
python3Packages.mypy: 0.740 -> 0.750

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
looking through @r-ryantm logs

Also refactored expression to follow ordering of most other python packages
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

python38Packages.pyls-mypy is failing due to upstream python3.8 issue, unrelated to PR
```
https://github.com/NixOS/nixpkgs/pull/75738
1 package failed to build:
python38Packages.pyls-mypy

18 package were built:
git-revise mypy nix-pin python37Packages.algebraic-data-types python37Packages.ics python37Packages.pyls-mypy python37Packages.pynamodb python37Packages.pytest-mypy python37Packages.tatsu python38Packages.algebraic-data-types python38Packages.git-revise python38Packages.ics python38Packages.mypy python38Packages.pynamodb python38Packages.pytest-mypy python38Packages.tatsu thonny zfs-replicate
```

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build git-revise mypy nix-pin python37Packages.algebraic-data-types python37Packages.ics python37Packages.pyls-mypy python37Packages.pynamodb python37Packages.pytest-mypy python37Packages.tatsu python38Packages.algebraic-data-types python38Packages.git-revise python38Packages.ics python38Packages.mypy python38Packages.pynamodb python38Packages.pytest-mypy python38Packages.tatsu thonny zfs-replicate

**Comment by primeos** [comment]
Thanks for fixing the `ics` build :)

**Comment by teto** [comment]
python3.7-algebraic-data-types-0.1.1 looks like the culprit

**Comment by jonringer** [comment]
failures are outside of this PR, in different packages

**Pull request merged**
