### PR TITLE
sylkserver: init at 5.2.0

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
currently blocked on the following issue:
```
$ ./result/bin/sylk-server --runtime-dir=$PWD --no-fork
Traceback (most recent call last):
  File "/nix/store/9vlnmgwm912mdwv0bb1h0bk578k9dfw4-sylkserver-5.2.0/bin/.sylk-server-wrapped", line 76, in <module>
    from sylk.server import SylkServer, ServerConfig
  File "/nix/store/9vlnmgwm912mdwv0bb1h0bk578k9dfw4-sylkserver-5.2.0/lib/python2.7/site-packages/sylk/server.py", line 13, in <module>
    from sipsimple.account import Account, BonjourAccount, AccountManager
  File "/nix/store/sassdfqgry4jd6xawm6rs1f0rd0jcmf8-python2.7-sipsimple-3.1.1/lib/python2.7/site-packages/sipsimple/account/__init__.py", line 20, in <module>
    from gnutls.interfaces.twisted import X509Credentials
  File "/nix/store/1jf2jqcimrh6mwxpv43habpv4rchyvm9-python2.7-python-gnutls-3.1.2/lib/python2.7/site-packages/gnutls/interfaces/twisted/__init__.py", line 8, in <module>
    from twisted.python import failure
  File "/nix/store/q5ffyir8ai4bzmdfhh3yrbfylzfzhvgj-python2.7-python-application-2.0.2/lib/python2.7/site-packages/application/log/extensions/twisted/twisted.py", line 14, in <module>
    import twisted
TypeError: expected string or buffer
```

**Comment by zimbatm** [comment]
```
Read-only file system: '/var/log/sylkserver'
Read-only file system: '/var/spool'
```

**Comment by zimbatm** [comment]
missing: all the config files need to be configurable

**Comment by leenaars** [comment]
New version for https://pypi.org/project/python-application/2.8.0/ was the issue; 

hash = "sha256:1sv3hyv1lhny0w79smdik1k88v75wmz9jas08iavnwgizdl8n0kj";

**Comment by leenaars** [comment]
Small nit: the commit message for sipsimple is 1 off: should be 3.5.0. The commit itself is correct ;)

**Comment by SuperSandro2000** [comment]
This PR needs a major redone and has many merge conflicts and is also in draft state for years, so I am going to close it. Feel free to re-open it if you continue on it.

**Pull request closed without merging**
