### PR TITLE
python3Packages.localzone: revert dnspython downgrade and mark as broken

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/99496#pullrequestreview-501631571

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by FRidh — APPROVED** [review]

**Comment by mweinelt** [comment]
What about removing the `dnspython_1` alias which you proposed shortly in #99567?

**Comment by FRidh** [comment]
I removed that because, while it prevents people from using it in `python-packages.nix`, it is there for a reason, like many other `_<version>` attributes.

**Comment by jonringer** [comment]
This is the proper course of action until https://github.com/ags-slc/localzone/issues/1 gets resolved

**Review by jonringer — APPROVED** [review]
LGTM

I'll create another PR fixing lexicon

```
https://github.com/NixOS/nixpkgs/pull/99568
4 packages marked as broken and skipped:
ape lexicon python37Packages.localzone python38Packages.localzone
```

**Pull request merged**
