### PR TITLE
LLVM: mark as big-parallel

### PR DESCRIPTION
**Pull request by bennofs**
###### Motivation for this change

LLVM frequently times out (see https://hydra.nixos.org/job/nixos/release-20.03-aarch64/nixpkgs.llvm_9.aarch64-linux as an example), hopefully marking as big-parallel should give it enough resources to finish quicker. LLVM 5 was already marked as big-parallel, so I went and marked the newer versions big-parallel as well.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bennofs** [comment]
Question: should we only apply big-parallel on aarch64? This might reduce the rebuilt amount?

**Comment by bhipple** [comment]
With the number of rebuilds, this should go to `staging` I think.

**Comment by bennofs** [comment]
Rebased to staging, wasn't sure at first whether a change in enableParallelBuilding would cause rebuilds.

**Comment by FRidh** [comment]
Will this have any effect? As far as I know big-parallel is one of the "legacy" features that every Nix installation has on by default. https://github.com/NixOS/nixos-org-configurations/search?q=big-parallel&unscoped_q=big-parallel also doesn't yield anything interesting.

**Comment by bennofs** [comment]
@FRidh on #nixos-aarch64, @grahamc said:

> gchristensen: big-parallel jobs get 32 cores, and 2 jobs per machine, regular builds get 2 cores and 16 jobs per machine

**Comment by jonringer** [comment]
I think it's largely an infrastructure optimization, as the wiki section on distributed builds mentions it. https://nixos.wiki/wiki/Distributed_build

**Review by vcunat — APPROVED** [review]
:heart: except that llvm 10 is missing.  I think it's worth picking to `staging-20.03` as well, on the next big rebuild.

**Comment by bennofs** [comment]
llvm_10 added

**Review by jonringer — APPROVED** [review]

**Review by LnL7 — APPROVED** [review]

**Comment by jonringer** [comment]
unfortunately, these are all broken currently

```
[13:44:06] jon@nixos ~/projects/nixpkgs (staging)
$ nix build -f . llvm_{6,7,8,9,10} --keep-going
builder for '/nix/store/ajqw5mrccbf26axn1mcp39l8lmvxgx93-libbfd-2.34.drv' failed with exit code 1; last 10 log lines:
  patching file bfd/configure.ac
  Hunk #1 FAILED at 241.
  1 out of 1 hunk FAILED -- saving rejects to file bfd/configure.ac.rej
  patching file opcodes/Makefile.am
  Hunk #1 succeeded at 51 (offset -1 lines).
  Hunk #2 succeeded at 301 (offset -2 lines).
  Hunk #3 succeeded at 322 (offset -2 lines).
  patching file opcodes/configure.ac
  Hunk #1 succeeded at 86 (offset -3 lines).
  Hunk #2 succeeded at 138 (offset 3 lines).
cannot build derivation '/nix/store/fspqc2gbf618gqaqsfllysh0kkdjxcrg-llvm-10.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2rd1i67dwg5v380yg8c58y7g44lns19c-llvm-6.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qvhcq0v99cgjxjq6788ydps3d9gv6lfc-llvm-7.1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5w107rwvi902r1jsbff4b91rh96bzxpa-llvm-8.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jrwd4z8csc2l70fw92rd374q1vgnfv15-llvm-9.0.1.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/2rd1i67dwg5v380yg8c58y7g44lns19c-llvm-6.0.1.drv', '/nix/store/5w107rwvi902r1jsbff4b91rh96bzxpa-llvm-8.0.1.drv', '/nix/store/fspqc2gbf618gqaqsfllysh0kkdjxcrg-llvm-10.0.0.drv', '/nix/store/jrwd4z8csc2l70fw92rd374q1vgnfv15-llvm-9.0.1.drv', '/nix/store/qvhcq0v99cgjxjq6788ydps3d9gv6lfc-llvm-7.1.0.drv' failed
```

**Review by bhipple — APPROVED** [review]

**Pull request merged**
