### PR TITLE
Allow darwin to use binutils

### PR DESCRIPTION
**Pull request by manveru**
This fixes building bash and probably other packages under darwin.

### CODE REVIEW

**Comment by vcunat** [comment]
Hmm, darwin wraps it somehow, but anyway, the platforms should contain at least `unix`. (I'm not certain what cygwin uses ATM.) I pushed that instead. Thanks!

**Comment by manveru** [comment]
Thanks a lot :)

**Comment by vcunat** [comment]
:-)

**Comment by edolstra** [comment]
Hm, since when does `bash` depend on `binutils` on Darwin?

**Pull request closed without merging**
