### PR TITLE
python: h5py update and new package pkgconfig

### PR DESCRIPTION
**Pull request by FRidh**
Since I think 2.4 h5py introduced a new way to configure mpi. Therefore,
the BuildFlags are removed.

I built h5py and h5py-mpi packages successfully. Not sure though whether
the mpi version does actually work correctly since I don't use it.

### CODE REVIEW

**Comment by domenkozar** [comment]
if `h5py` is used as a library,we should pull it into `python-packages.nix`

**Comment by FRidh** [comment]
is it okay to have a named function in python-packages.nix, since we still want to have (at least) two different derivations, h5py and h5py-mpi.

**Comment by domenkozar** [comment]
Yeah we do the same for sqlalchemy

**Comment by FRidh** [comment]
Okay, I'll have a look at it.

Relevant issue regarding pkgconfig: https://github.com/matze/pkgconfig/issues/9

**Comment by FRidh** [comment]
@domenkozar could you merge this?

**Pull request merged**
