### PR TITLE
Migrate Agda infrastructure

### PR DESCRIPTION
**Pull request by abbradar**
This migrates Agda to haskell-ng. The patch consists of several parts:

1) jailbreak-cabal now happens postPatch. This may be a controversial thing (perhaps requiring its own PR) -- though in my opinion it's more logical. It allows us to apply patches which modify stock .cabal file before it's regenerated by jailbreak-cabal.
2) Adds backported patch https://github.com/agda/agda/commit/f41911c09ee8f8c81bde21710cc7ce205cda02f8 to Agda -- this fixes its compilation on GHC 7.8
3) Migrates agda builder and libraries to haskell-ng, per @Fuuzetsu 's guide on ML. Also cleaned up and updated few libraries.

@peti @Fuuzetsu

### CODE REVIEW

**Comment by peti** [comment]
I'm not particularly happy about the fact that the fix for Agda is mixed up with a structural change of the default builder that -- when merged -- causes a complete re-build of every single Haskell package. Can we make those changes separately?

**Comment by abbradar** [comment]
Oh, it somehow was off the top of my head that it would cause complete re-build, sorry! It would need this change to compile, though -- moved to separate PR.

**Comment by peti** [comment]
7355842 fixes the Agda build in haskell-ng. The goes to `master` in a moment.

**Comment by abbradar** [comment]
Thanks! Would you also pull https://github.com/abbradar/nixpkgs/commit/c6d9e0a829d5545c6cdc438b446c7b6cd0e4b7fb by yourself, or should I rebase and resubmit?

**Comment by peti** [comment]
Added to the update branch in 35f27c5. Thanks a lot, @abbradar!

**Comment by abbradar** [comment]
@peti, I cannot find `cabal2nix` patch which adds older dependencies.

**Comment by peti** [comment]
@abbradar, it's https://github.com/NixOS/cabal2nix/commit/1073701687b66f7da3a3b0bb64721e51ad37605d. I forgot to push my local changes to Github, that's why it didn't show up. Sorry.

**Pull request closed without merging**
