### PR TITLE
drogon: 1.6.0 -> 1.7.0

### PR DESCRIPTION
**Pull request by urlordjames**
###### Motivation for this change
new update released (https://github.com/an-tao/drogon/releases/tag/v1.7.0)

###### Things done
- bump version
- implement a workaround so I no longer need to disable parts of the test
- disable examples because they're no longer used for tests anymore
- swap from `libuuid` to `libossp_uuid` for darwin compatibility

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ethancedwards8** [comment]
Result of `nixpkgs-review pr 127436` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>drogon</li>
  </ul>
</details>

**Comment by urlordjames** [comment]
> Result of `nixpkgs-review pr 127436` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:

@ethancedwards8 I don't have a Mac to test this on, any chance you could send a gist of the log?  In the mean time I'll mark as broken on darwin.

**Comment by ethancedwards8** [comment]
> > Result of `nixpkgs-review pr 127436` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> > 1 package failed to build:
> 
> @ethancedwards8 I don't have a Mac to test this on, any chance you could send a gist of the log? In the meantime I'll mark as broken on darwin.

Sure thing. https://termbin.com/7c6r

**Comment by urlordjames** [comment]
> > > Result of `nixpkgs-review pr 127436` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> > > 1 package failed to build:
> > 
> > 
> > @ethancedwards8 I don't have a Mac to test this on, any chance you could send a gist of the log? In the meantime I'll mark as broken on darwin.
> 
> Sure thing. https://termbin.com/7c6r

Think I found the culprit:
https://github.com/NixOS/nixpkgs/blob/bad3ccd099ebe9a8aa017bda8500ab02787d90aa/pkgs/os-specific/linux/util-linux/default.nix#L72
Looks to me like `libuuid` on nixpkgs is provided by `util-linux` and thus doesn't support Darwin.  Thanks for bringing this to my attention.  I think I can fix this by using `libossp_uuid` instead.  I'll try this out when I get the chance.

**Comment by urlordjames** [comment]
@ethancedwards8 could you give this another test when you get the opportunity?  I just swapped out `libuuid`, hopefully this can make drogon accessible to more people.

**Comment by ethancedwards8** [comment]
> @ethancedwards8 could you give this another test when you get the opportunity? I just swapped out `libuuid`, hopefully this can make drogon accessible to more people.

Yup, got a notification, started compiling a few minutes ago.

**Comment by ethancedwards8** [comment]
Result of `nixpkgs-review pr 127436` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>drogon</li>
  </ul>
</details>


Yay!

**Comment by urlordjames** [comment]
Thanks so much!

**Pull request merged**
