### PR TITLE
cockroachdb: 1.1.5 -> 2.0.0

### PR DESCRIPTION
**Pull request by jbboehr**
###### Motivation for this change

Lots of shiny new features: https://www.cockroachlabs.com/docs/releases/v2.0.0.html#core-features

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

One of the dependencies failed to build without `-ltinfo`, so I've added `ncurses6` to the `buildInputs`.

### CODE REVIEW

**Comment by bdarnell** [comment]
This still needs a little work: the Go version pin in all-packages.nix needs to be removed, and on darwin it requires libedit (this is an undocumented dependency because we didn't contemplate darwin build environments that don't include things that are present in the default xcode install)

I'm working on an alternative PR that also refactors it to use stdenv.mkDerivation, since building cockroachdb from a source tarball is more like a standard tarball build that happens to depend on go than a typical go package.

**Comment by jbboehr** [comment]
To be fair, I changed the minimum possible to update the dependency - I would consider any changes to how the package is built not the scope of my PR.

**Comment by jbboehr** [comment]
@bdarnell I noticed in your PR you did not change `all-packages.nix` - I assume you were working off 18.03 and realized it wasn't necessary after rebasing onto master (like me)?

**Comment by bdarnell** [comment]
Yeah, I was looking at an old version of all-packages.nix that still had the Go pin. Sorry for the confusion.

**Comment by jbboehr** [comment]
@bdarnell I see you are a major contributor to CRDB - I would be interested if you had any comments on my other PR #38665 at least from the CRDB side of things.

**Comment by Mic92** [comment]
@GrahamcOfBorg build cockroachdb

**Pull request merged**
