### PR TITLE
add textlint to nodePackages

### PR DESCRIPTION
**Pull request by matthew-piziak**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/53781

> textlint "is an open source pluggable linting tool for natural language text".

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthew-piziak** [comment]
Okay this is my first contribution so it's gonna take me a bit to work through the checklist. I've never tested from a fork before so I'm going to work from [this](https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages), assuming that that's the right doc.

**Comment by 6AA4FD** [comment]
looks good to me, though i'm new to nix as well, so i don't know if it says much. you should be aware that a merge might take a while, because a few packages got bumped up in version, so anything they depend on will probably need to be tested. good luck!

**Comment by adisbladis** [comment]
Do you really need this available for all versions of nodejs?
Seems to me like the runtime version should not matter in this case.

**Comment by matthew-piziak** [comment]
@adisbladis No, I definitely don't. I just thought that that was best practice. Would it be better to just provide an update for v10?

**Comment by adisbladis** [comment]
I fixed up the commit message to match https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md.

Thank you :)

**Pull request merged**
