### PR TITLE
fetchYarnDeps: properly accept src argument

### PR DESCRIPTION
**Pull request by Infinidoge**
## Description of changes

`fetchYarnDeps` is supposed to accept the `src`, argument, defaulting to unpacking and getting the `yarn.lock` from `$src`. However, after checking if `src` exists for whether or not to run the `unpackPhase`, it drops `src` from the arguments, leading Nix to say `variable $src or $srcs should point to the source` despite (supposedly) being passed `src`.

This fixes that :)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
Somehow this causes a rebuild of electron?

**Comment by Infinidoge** [comment]
Wild.

I'll look into tracking down why it causes a rebuild later today.

**Comment by Infinidoge** [comment]
Oh I think I know why. It rebuilds because of the difference between `src` not existing and `src` being null.

**Comment by Atemu** [comment]
Result of `nixpkgs-review pr 319623` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>electron-fiddle</li>
    <li>itch</li>
  </ul>
</details>
<details>
  <summary>137 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>akkoma-frontends.admin-fe</li>
    <li>akkoma-frontends.akkoma-fe</li>
    <li>alice-lg</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>antares</li>
    <li>aws-azure-login</li>
    <li>bilibili</li>
    <li>bitwarden-desktop</li>
    <li>bitwarden-directory-connector</li>
    <li>breitbandmessung</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>das</li>
    <li>das.dist</li>
    <li>devcontainer</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_30)</li>
    <li>electron_29</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web (element-web-unwrapped)</li>
    <li>fcast-receiver</li>
    <li>feishin</li>
    <li>fernglas</li>
    <li>fixup-yarn-lock</li>
    <li>freetube</li>
    <li>gitlab</li>
    <li>gitlab-ee</li>
    <li>gitmoji-cli</li>
    <li>gotify-server</li>
    <li>grafana-agent</li>
    <li>grafana-alloy</li>
    <li>grocy</li>
    <li>headset</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>hydrogen-web (hydrogen-web-unwrapped)</li>
    <li>jitsi-meet-electron</li>
    <li>ki</li>
    <li>ki.dist</li>
    <li>koodo-reader</li>
    <li>kuro</li>
    <li>lxd-ui</li>
    <li>marp-cli</li>
    <li>mastodon</li>
    <li>matrix-appservice-irc</li>
    <li>mealie</li>
    <li>mealie.dist</li>
    <li>mermaid-cli</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>morgen</li>
    <li>muzika</li>
    <li>nix-tour</li>
    <li>node-hp-scan-to</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>outline</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>passky-desktop</li>
    <li>peertube</li>
    <li>peertube.cli</li>
    <li>peertube.runner</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>picosnitch</li>
    <li>picosnitch.dist</li>
    <li>podman-desktop</li>
    <li>prefetch-yarn-deps</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>pxder</li>
    <li>python311Packages.dash</li>
    <li>python311Packages.dash.dist</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.dash</li>
    <li>python312Packages.dash.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>ratman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>rmfakecloud</li>
    <li>sapling</li>
    <li>sapling.dist</li>
    <li>sharedown</li>
    <li>shepherd</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>tandoor-recipes</li>
    <li>teams-for-linux</li>
    <li>teleport (teleport_15)</li>
    <li>teleport.client (teleport_15.client)</li>
    <li>teleport_14</li>
    <li>teleport_14.client</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>textlint-rule-abbr-within-parentheses</li>
    <li>textlint-rule-common-misspellings</li>
    <li>textlint-rule-en-max-word-count</li>
    <li>textlint-rule-max-comma</li>
    <li>textlint-rule-no-start-duplicated-conjunction</li>
    <li>textlint-rule-period-in-list-item</li>
    <li>textlint-rule-preset-ja-technical-writing</li>
    <li>textlint-rule-unexpanded-acronym</li>
    <li>textlint-rule-write-good</li>
    <li>thedesk</li>
    <li>thelounge</li>
    <li>threema-desktop</li>
    <li>tilt</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vercel-pkg</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>your_spotify</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Review by Atemu — APPROVED** [review]

**Comment by Atemu** [comment]
For future reference, the rebuild was caused by an instance of https://github.com/NixOS/nixpkgs/issues/301014 which we fixed in 882cf1800592fa033666c47b5b0ce4a3435b5c64; causing one more rebuild but that should be the last.

**Pull request merged**
