### PR TITLE
racket: 7.4 -> 7.5

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
Release Announcement: https://download.racket-lang.org/v7.5.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by davidak — APPROVED** [review]
##### Reviewed points

- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package build on x86_64
- [X] executables tested on x86_64
- [X] all depending packages build

##### Possible improvements

##### Comments

Thanks for your contribution! :sparkles: 

I have tested this binaries:

racket: racket, drracket
racket-minimal: racket, raco

cc maintainers @henrytill @vrthra

**Review by davidak — CHANGES_REQUESTED** [review]
From your release link:

>Almost all of Racket version 7.5 is distributed under a new,
  less-restrictive license: either the Apache 2.0 license or the MIT
  license. See https://blog.racket-lang.org/2019/11/completing-racket-s-relicensing-effort.html
  for more details.

Please change the license to MIT and Apache2!

**Review by Br1ght0ne — APPROVED** [review]
What @davidak said, besides that - LGTM.

**Comment by marsam** [comment]
@davidak good catch, I've updated the licence field. Thanks!

**Pull request merged**
