### PR TITLE
gccgo: wrap go binary

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
This PR [blocks](https://github.com/NixOS/nixpkgs/pull/207681#issuecomment-1371144146) `pkgMusl.go` which blocks ALL Go projects for Musl. Which blocks generating smaller container images using Nix (by using Musl). Would be really good to have it reviewed.

I'm pinging other contributors for feedback and hopefully a review.
@matthewbauer @shlevy @thefloweringash @oxij @volth @FRidh @fpletz @dezgeg

Thanks!

**Comment by superherointj** [comment]
@yu-re-ka Any problem?

**Comment by yu-re-ka** [comment]
I don't really appreciate it when people express an urgency about something that is done by others in their free time, but themselves don't put much effort into solving the problem.

**Comment by superherointj** [comment]
> I don't really appreciate it when people express an urgency about something that is done by others in their free time, but themselves don't put much effort into solving the problem.

:(

Meant to clarify purpose/meaning/relevance of this PR. Note: this PR has no description. I said why it is meaningful, on my words.

Pinged **new** contributions because I have already reviewed/approved this same code at PR #207681, you said it needed `someone qualified to judge changes to the cc-wrapper` (which implied was not me). Two weeks passed waiting for a review, no one volunteered. As I am not qualified (per comment) I cannot see how I can put more effort into solving this problem.

On `lack of effort`, it is exactly because of this sort of situation that I stopped contributing to nixpkgs. No matter what I do, people are always unhappy, throwing shit and I end up having to excuse myself for doing nothing bad. Likely my contributions are bad. I get it, I'm not contributing anymore.

Anyway, thanks for solving the problem. Have a nice day.

**Comment by superherointj** [comment]
> I don't really appreciate it when people express an urgency about something that is done by others in their free time

Thanks for speaking your mind.

Meant to clarify PR purpose. Note: this PR has no description.

Pinged **new** contributors because:
- I have already reviewed/approved this same code at PR #207681, but you disqualified me ([per comment](https://github.com/NixOS/nixpkgs/pull/207681#issuecomment-1371144146)) when said was necessary `someone qualified to judge changes to the cc-wrapper`.
- Two weeks passed waiting for a review, no one volunteered.
- Maybe someone else has availability or interest? Who knows.

> but themselves don't put much effort into solving the problem.

I cannot put (more) effort into solving a problem that is already solved (by you, thanks!). And my review is disqualified.

I don't have your expertise/knowledge. I actually tried to move things forward but it went nowhere. And your answers helped clarify how things worked. Instead of implying laziness, think of incompetence. Then, I agree. :-)

**Comment by zowoq** [comment]
> https://github.com/NixOS/nixpkgs/pull/207681#issuecomment-1371144146
> The content of that should still be reviewed by someone qualified to judge changes to the cc-wrapper.

Wouldn't say that I'm qualified but as no one else has I think it's fine to merge. The changes are small, limited to gccgo and easy enough to revert if it is problematic for some reason.

**Pull request merged**
