### PR TITLE
packer: 1.7.2 -> 1.7.3

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
ChangeLog: https://github.com/hashicorp/packer/blob/v1.7.3/CHANGELOG.md#173-june-15-2021

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 127057` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>packer</li>
  </ul>
</details>

**Comment by happysalada** [comment]
The only thing that seems odd to me was the fact that the vendorSha256 was set to null. Perhaps there was some kind of thing that made it not deterministic?
The PR looks good though.

**Comment by Ma27** [comment]
`vendorSha256 = null` is IIRC only needed when `vendor/` already exists and it doesn't exist anymore in 1.7.3.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 127057` at f99afba1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>cryptomator</li>
    <li>packer</li>
  </ul>
</details>

**Pull request merged**
