### PR TITLE
Create service abstraction layer (proposal, prototype)

### PR DESCRIPTION
**Pull request by offlinehacker**
## Idea

Let's abstract services, so they can be used independently by different process manager like supervisord, docker,... and not only by systemd.
## Preface

I really like nixos and module definition schema, and i really like to write nixos services. As a developer i want to make these services portable betwene systems independently of process managers if that is possible for speciffic service. Current systemd interface is not right approach and only results in hacks to support its interface(like https://github.com/kiberpipa/nix-rehash/tree/master/nix-services).
## Problems with using systemd interface

Problem with using systemd interface as a base for service definitions for other process managers is that service definitions use all features of systemd, even that other process managers do not support them. There are not sufficient nixos options to support lack or presence of if:
- process manager can handle forking services
- process manager handles logs
- process manager handler logs from syslog
- ... your use case ...
## Implementation

Prototype implementation present in this pull request wants to solve this by abstracting services out of nixos. The reason for abstracting out is that services will not be only used in nixos, but also in other scearios with other process manager and with abscence of nixos on different systems, distros, process virtualization solutions like docker.

Because of lack of better idea i defined `sal`(service abstraction layer) interface abstracted into new `service` directory tree. There, service options/configurations are defined and process manager options are present. Real implementation of this schema is present in nixos systemd, which uses `sal` as a base for services.

I should mention that proposed solution is not usefull for all services and is not ment to replace systemd interface, which is by the way really nice and has a lot of features.
## Alternative implemenations

More straightforward solution would be to make something like `users.services` interface, for defining services. This has a downside, and does not take in account which features different process managers support.
## I would really need this now

I want to ask you, whether you like the proposed implementation or if you have any better idea how to implement this. I would really like to solve the problem, because i need it to make user services and docker implementation using this or similar interface. Without this i can only make hacked implementations(that people use and depend on), like https://github.com/kiberpipa/nix-rehash/tree/master/nix-services, that i later don't want to support, because of hackiness involved.

**So please review the prototype and please propose better implementations and let's make nix services as portable as possible :)**

@edolstra @rbvermaa @nbp @iElectric @lethalman @wmertens

### CODE REVIEW

**Comment by ktosiek** [comment]
The most interesting effect of having SAL for me would be running Nix-managed services on Ubuntu. Right now I'm looking at nix-rehash, but this looks much more promising.

There are environments where I can't change the base OS (because of existing procedures, other users, or just no support from cloud provider), but I'd still like to use Nix for parts of it. Right now I can only use it for packages, but not really for services configuration.

**Comment by offlinehacker** [comment]
I'm actively working on this, currently on sal+docker and later on user
services, this will prove that sal is good enough design. I still have to
figure out how to deal with multiple identical services in one
configuration definition namespace.

**Comment by offlinehacker** [comment]
A bit of progress has been made, added docker and supervisor process managers. There are still bugs, don't expect it to work.

**Comment by copumpkin** [comment]
:+1:, I want launchd support someday :smile:

**Comment by offlinehacker** [comment]
I'm planning also launchd, I might need help also from osx devs. Btw,
supervisord also works on osx.

**Comment by offlinehacker** [comment]
Fixed bugs with supervisord and docker. Assertions are now handled properly(and better) and not dependant on nixos assertions.

You can test now with going to `services/process-managers/supervisord` and running:

```
nix-build default.nix --argstr configuration $PWD/test.nix --show-trace --argstr name test
```

This will create configuration and supervisord wrapper scripts in bin directory:

```
test-start-services
test-control-services
test-stop-services
```

You can do the same with docker+fig by going to `services/process-managers/docker` and running:

```
nix-build fig.nix --argstr configuration $PWD/test.nix --show-trace --argstr name test
```

To run: `fig -f result up`

**Comment by offlinehacker** [comment]
Do you have some ideas how services with different process managers(nixos+systemd, supervisord, docker+fig...) could be tested on all of them(format of tests, debugging of tests,...) ? Testing is really critical feature that has to be in service abstraction layer.

**Comment by jzellner** [comment]
Hey @offlinehacker this is also something I'd really like to see. How can I help?

**Comment by copumpkin** [comment]
Any progress on this?

**Comment by garbas** [comment]
@offlinehacker is this something you're still working on, or this became stale?

**Comment by offlinehacker** [comment]
I'm closing this pull request, as after two years of dealing with docker, kubernetes and other containarized environments, i have much better idea how nix-services should be designed. Now all i need is a bit of time, which i would have to take, because it's something we need quite urgent on gatehub and proteuslabs. This work is from my perspecitve obsolete.

**Comment by copumpkin** [comment]
@offlinehacker if it's obsolete, do you have something better? Curious where we should take this going forward

**Comment by offlinehacker** [comment]
@copumpkin yes we should, I have some cool ideas, especially related with docker/kubernetes and other cluster technologies. I have built nix-kubernetes, but this is just abstraction over kubernetes. I want to make nix-services environment independant and cluster aware. The only problem is limited amount of time I have,  if you have some time we can discuss how to push this forward.

**Comment by copumpkin** [comment]
Yeah, I'll check out your nix-kubernetes to see what you've done. It's mostly just been frustrating me to use `dockerTools` to build service containers knowing that we have lots of nicely modeled services sitting in NixOS, but we can't use any of them because they're expressed in a language that's too specific to systemd.

**Comment by domenkozar** [comment]
I hope you all saw https://github.com/LnL7/nix-darwin

**Comment by offlinehacker** [comment]
@domenkozar nice General idea is abstraction for different runtime environments, we could reuse module systems as backends for these environments.

**Pull request closed without merging**
