### PR TITLE
ddnet: init at 15.5.4

### PR DESCRIPTION
**Pull request by SirSeruju**
### Done:
- Add me to maintainers.
- Add DDNet to games.

### CODE REVIEW

**Review by legendofmiracles — CHANGES_REQUESTED** [review]
I've packaged a from-source expression in my dotfiles (started it a while back, didn't work but you gave me the motivation to finish it 😄 ), which are generally preferred in nixpkgs. 

https://github.com/legendofmiracles/dotnix/blob/c2b5d68612d2ded26b4528062032a54633529a57/overlays/ddnet/default.nix

Feel free to copy it

**Review by legendofmiracles — APPROVED** [review]

**Review by figsoda — CHANGES_REQUESTED** [review]
please squash your `games: ddnet` commits into one commit: `ddnet: init at 15.5.4`

**Review by figsoda — CHANGES_REQUESTED** [review]
aside from that lgtm

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 141815` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ddnet</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
