### PR TITLE
eduke32: 20210910 -> 20221026

### LINKED ISSUE #189158: eduke32 update available
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: [eduke32](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/eduke32/default.nix)

current version: 20210910
desired version: [20220726](https://dukeworld.com/eduke32/synthesis/latest/)

###### Notify maintainers
@mikroskeem 
@svanderburg (hope you are the correct maintainer, sorry if not)

maintainers:

mikroskeem
sander

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by wamserma**
###### Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/189158

ZHF: #199919 (see discussion below)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 197798"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 197798` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>eduke32</li>
  </ul>
</details>

**Comment by trofi** [comment]
Does it build for you? Fails here as:

```
build flags: -j16 SHELL=/nix/store/dd3713mm8wql4r2d5jxx0f58g16nfm4h-bash-5.1-p16/bin/bash SDLCONFIG=/nix/store/7j59kg0bsr5
9k7bqp0s4h5gybbqd160z-SDL2-2.24.0/bin/sdl2-config
Building object obj/duke3d/astub.o...^MBuilding object obj/duke3d/sounds_mapster32.o...^MBuilding object obj/duke3d/build_
icon.o...^MBuilding object obj/duke3d/m32common.o...^MBuilding object obj/duke3d/m32def.o...^MBuilding object obj/duke3d/m
32exec.o...^MBuilding object obj/duke3d/m32vars.o...^MBuilding object obj/build/build.o...^MBuilding object obj/build/conf
ig.o...^MBuilding object obj/build/startgtk.editor.o...^MBuilding: make  - -j16 --jobserver-auth=4,5 -- SDLCONFIG=/nix/sto
re/7j59kg0bsr59k7bqp0s4h5gybbqd160z-SDL2-2.24.0/bin/sdl2-config SHELL=/nix/store/dd3713mm8wql4r2d5jxx0f58g16nfm4h-bash-5.1
-p16/bin/bash
Building object obj/duke3d/actors.o...^MBuilding object obj/duke3d/anim.o...^MBuilding object obj/duke3d/cheats.o...^MBuil
ding object obj/duke3d/cmdline.o...^MBuilding object obj/duke3d/config.o...^MIn file included from source/duke3d/rsrc/eduk
e32_icon.c:2,
                 from source/duke3d/rsrc/build_icon.c:1:
source/build/include/sdl_inc.h:17:12: fatal error: SDL2/SDL.h: No such file or directory
   17 | #  include <SDL2/SDL.h>
      |            ^~~~~~~~~~~~
compilation terminated.
Failed building obj/duke3d/build_icon.o from source/duke3d/rsrc/build_icon.c!
```

**Comment by wamserma** [comment]
It builds when I check out d2325a46aff and there is no commit mentioning SDL2 since then...
But if fails when I do a `nixpkgs-review`...

**Comment by trofi** [comment]
Ah, it's because `eduke32` is already broken on `master`. bisect says it was broken by  commit 0bea4a194f7103fcedc0226a74e50657875a7c4d `cc-wrapper/setup-hook.sh: remove duplicate flags in NIX_CFLAGS_COMPILE`.

**Comment by trofi** [comment]
Proposed https://github.com/NixOS/nixpkgs/pull/198019 to remove unused `SDL2/` include offsets. It also happens to workaround build failure for `eduke32`. Should unbock this PR once merged.

**Comment by wamserma** [comment]
Result of `nixpkgs-review pr 197798` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>eduke32</li>
  </ul>
</details>

**Comment by trofi** [comment]
AFAIU `SDL`/`SDL2` headers should always be included as `<SDL/SDL.h>` / `<SDL2/SDL.h>`. Sometimes build systems avoid `SDL{,2}/` prefix by extending the include search path. Not sure where it's supposed to happen in `eduke32`.

I suggest fixing headers locally as:

```diff
--- a/pkgs/games/eduke32/default.nix
+++ b/pkgs/games/eduke32/default.nix
@@ -57,6 +57,11 @@ in stdenv.mkDerivation rec {
       substituteInPlace source/glad/src/$f \
         --replace libGL.so ${libGL}/lib/libGL.so
     done
+
+    substituteInPlace source/imgui/src/imgui_impl_sdl.cpp \
+        --replace '#include <SDL.h>' '#include <SDL2/SDL.h>' \
+        --replace '#include <SDL_syswm.h>' '#include <SDL2/SDL_syswm.h>' \
+        --replace '#include <SDL_vulkan.h>' '#include <SDL2/SDL_vulkan.h>'
   '';

   makeFlags = [
```

WDYT?

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 197798` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>eduke32</li>
  </ul>
</details>

**Comment by wamserma** [comment]
@trofi now ;)

**Comment by wamserma** [comment]
Result of `nixpkgs-review pr 197798` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>eduke32</li>
  </ul>
</details>

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 197798` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>eduke32</li>
  </ul>
</details>

**Review by trofi — APPROVED** [review]

**Comment by trofi** [comment]
Pulled. Thank you!

Apologies for so many sidetracks with include headers.

**Comment by revuwa** [comment]
Big thanks @ all of you ❤️

**Pull request merged**
