### PR TITLE
xpadneo: 0.9.6 -> 0.9.6-unstable-2024-03-10

### PR DESCRIPTION
**Pull request by tengkuizdihar**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tengkuizdihar** [comment]
Wanted to ask the maintainer here first, @kira-bruneau, is it alright to bump the version to unstable? Currently, there are fixes towards gulikit that finally enables rumble for bluetooth. I've tried the commit hash manually by using overrideAttrs. Is there any concern about bumping this version?

**Comment by kira-bruneau** [comment]
I can't think of anything specific, but I'm a bit wary of using an unstable version that might break something unexpectedly.

Do you know the commit that introduced the fix? I think it would just be better to manually patch in the fix, or just wait for the next release.

**Comment by anthr76** [comment]
I'm also interested in this. Is it possible to overlay while using nixos option to enable xpad neo?

**Comment by tengkuizdihar** [comment]
You can refer to https://nixos.wiki/wiki/Linux_kernel and search for
xpadneo in the page

**Comment by anthr76** [comment]
I have but haven't had much luck.

I tried something akin to this:

```nix
    nixpkgs.overlays = [
      (final: prev: {
        linux_xanmod_latest_snowflake = prev.pkgs.linuxPackagesFor
          (prev.pkgs.linux_xanmod_latest.override (old:
            with prev.lib; {
              ignoreConfigErrors = true;
              suffix = "xanmod1";
              version = "6.6.25";
              modDirVersion = "6.6.25-xanmod1";
              src = pkgs.fetchFromGitHub {
                owner = "xanmod";
                repo = "linux";
                rev = "df32b000046c82c315edc9420daa399341b2efb3";
                hash = "sha256-f375jX0BTlccJoeEFDQ2ZaVWQhcnWqcSNYHzGjS2DQo=";
              };
            }));
        linuxPackages_xanmod_latest = final.linux_xanmod_latest.extend (self: super: {
          xpadneo = super.xpadneo.overrideAttrs (o: rec {
            src = pkgs.fetchFromGitHub {
              owner = "xanmod";
              repo = "linux";
              rev = "df32b000046c82cf15edc9420daa399341b2efb3";
              hash = "sha256-f375jfsBTlccJoeEFDQ2ZaVWQhcnWqcSNYHzGjS2DQo=";
            };
          });
        });
      })
    ];
```

**Comment by tengkuizdihar** [comment]
I don't understand, why is xpadneo src is replaced with xanmod/linux repository?

**Comment by anthr76** [comment]
I'm almost using xanmod kernel.


My kernel selection looks like

`boot.kernelPackages = lib.mkForce pkgs.linux_xanmod_latest_snowflake;`

**Comment by anthr76** [comment]
Oh sorry that was a typo xpadneo as the source makes no difference.

**Comment by anthr76** [comment]
This actually seemingly works!

```nix
    nixpkgs.overlays = [
      (final: prev: {
        linux_xanmod_latest_snowflake_packages = final.linux_xanmod_latest_snowflake.extend (self: super: {
          xpadneo = super.xpadneo.overrideAttrs (o: rec {
            src = final.fetchFromGitHub {
              owner = "atar-axis";
              repo = "xpadneo";
              rev = "be25f7ba836fba99def5d7bc85fcf26696a2fbf9";
              hash = "sha256-l8O6rNbA7xn/zZWaccyr2M4ZkcSHxPH1ohptW+UFgxo=";
            };
          });
        });
        linux_xanmod_latest_snowflake = prev.pkgs.linuxPackagesFor
          (prev.pkgs.linux_xanmod_latest.override (old:
            with prev.lib; {
              ignoreConfigErrors = true;
              suffix = "xanmod1";
              version = "6.6.25";
              modDirVersion = "6.6.25-xanmod1";
              src = pkgs.fetchFromGitHub {
                owner = "xanmod";
                repo = "linux";
                rev = "df32b000046c82c315edc9420daa399341b2efb3";
                hash = "sha256-f375jX0BTlccJoeEFDQ2ZaVWQhcnWqcSNYHzGjS2DQo=";
              };
            }));
      })
    ];
```

**Pull request closed without merging**
