### PR TITLE
nixos/nats: Implemented configuration verification

### PR DESCRIPTION
**Pull request by jpds**
## Description of changes

Adds configuration verification to the NATS module.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by bbigras** [comment]
This seems to break when using a resolver.

```
building '/nix/store/516la877am25wh7szpd4j784r5i30jjd-unit-systemd-journald-.service.drv'...
error: builder for '/nix/store/sd7asy4kwyqjzyzvz8wvp94czgzhbqp5-validate-nats-conf.drv' failed with exit code 1;
       last 2 log lines:
       > nats-server: /nix/store/f1fsjxp8ksjrfx8kc6xb0ymvjz1m8v16-nats.conf:12:4: mkdir /var: permission denied
       >
       For full logs, run 'nix log /nix/store/sd7asy4kwyqjzyzvz8wvp94czgzhbqp5-validate-nats-conf.drv'.
```

to test:

```patch
diff --git a/nixos/tests/nats.nix b/nixos/tests/nats.nix
index c650904e53...2679cfe46b 100644
--- a/nixos/tests/nats.nix
+++ b/nixos/tests/nats.nix
@@ -26,6 +26,14 @@
               inherit password;
             }];
           };
+
+            resolver = {
+                type = "full";
+                dir = "/var/lib/nats/jwt";
+                allow_delete = false;
+                interval = "2m";
+                timeout = "1.9s";
+          };
         };
       };
     };
```

The [documentation](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt/resolver) mentions `dir: './jwt'`, but I got a similar error.
```
nats-server[897]: nats-server: /nix/store/5ggrpiqs09627hlxlyhhnqpgz2q0cc7m-validate-nats-conf:12:4: mkdir ./jwt: read-only file system
```

**Comment by krostar** [comment]
This also break when setting path for tls config like

```nix
{
  services.nats.settings.tls = let 
    certDir = config.security.acme.certs."nats.example.tld".directory;
  in {
    cert_file = "${certDir}/cert.pem";
    key_file = "${certDir}/key.pem";
  };
}
```

result during build to the following error :
```
$> nix build --print-build-logs .#'nixosConfigurations.host42.config.system.build.toplevel'
validate-nats-conf> nats-server: /nix/store/waryqcg992bjz746xbb0wirr5niq2myg-nats.conf:62:6: error parsing X509 certificate/key pair: open /var/lib/acme/nats.example.tld/cert.pem: no such file or directory
validate-nats-conf> /nix/store/waryqcg992bjz746xbb0wirr5niq2myg-nats.conf:78:4: error parsing X509 certificate/key pair: open /var/lib/acme/nats.example.tld/cert.pem: no such file or directory
error: build of '/nix/store/bc1mdh5ky4fpvl5iyzgg6jqd7yk3dbxs-validate-nats-conf.drv' on 'ssh-ng://builder@linux-builder' failed: builder for '/nix/store/bc1mdh5ky4fpvl5iyzgg6jqd7yk3dbxs-validate-nats-conf.drv' failed with exit code 1;
       last 3 log lines:
       > nats-server: /nix/store/waryqcg992bjz746xbb0wirr5niq2myg-nats.conf:62:6: error parsing X509 certificate/key pair: open /var/lib/acme/nats.example.tld/cert.pem: no such file or directory
       > /nix/store/waryqcg992bjz746xbb0wirr5niq2myg-nats.conf:78:4: error parsing X509 certificate/key pair: open /var/lib/acme/nats.example.tld/cert.pem: no such file or directory
       >
       For full logs, run 'nix-store -l /nix/store/bc1mdh5ky4fpvl5iyzgg6jqd7yk3dbxs-validate-nats-conf.drv'.
perl> created 183 symlinks in user environment
error: builder for '/nix/store/bc1mdh5ky4fpvl5iyzgg6jqd7yk3dbxs-validate-nats-conf.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/ra79qwbppcmp1pygyjhzjnx9yqsilwmi-unit-nats.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/40zir33qc33h5ypgb0rrfvvvi5h2n73i-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gazyxg7mi9h3xb7b8yr6s1n2kfdx7czx-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/21fa0j8lhxnzkyw8vx33svwd232z8fk2-nixos-system-host42-24.11.20250120.ae584d9.drv' failed to build
```

which should be expected, as the acme certificate would only exists after retrieving the certificates, which wont happen at build time.

**Comment by truh** [comment]
@jpds @derekcollison @tomberek Would it be possible to revert this PR given that it breaks multiple people's setups in multiple different ways.

I don't see a way of working around problems caused by the validation short of `disabledModules` + importing my own copy of this module.

**Comment by tomberek** [comment]
Yeah, either approach of a revert or making validation optional seems fine.

**Comment by truh** [comment]
I've opened a PR to add a validateConfig option https://github.com/NixOS/nixpkgs/pull/387048

I hope that's a solution everyone can be happy with.

**Pull request merged**
