### PR TITLE
nixos-rebuild, nixos-install: backport to 20.09: pass through impure flag

### PR DESCRIPTION
**Pull request by ShamrockLee**
Backport of #99038 and #100136
(cherry picked from commit bb61cce82abc6f692548d6831960e455766c898c)

###### Motivation for this change
`nixos-rebuild --impure` is necessary for using flake to manage impure `configuration.nix`, and should be backported to the stable version (19.09).

This backport should work out of the box, but I'm not sure how to test it. It would be great if someone can help testing it before merge.
Update: Tested with tests.installer

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShamrockLee** [comment]
@GrahamcOfBorg test installer

**Comment by ShamrockLee** [comment]
@worldofpeace Could you help take a look?

**Comment by Ma27** [comment]
@ShamrockLee  I think you missed the manpage update for `nixos-rebuild`. Apart from that, LGTM.

**Comment by ShamrockLee** [comment]
> I think you missed the manpage update for `nixos-rebuild`.

It is missed in the original commit, and I'm not sure if it is okay to commit new changes like this to the stable version.

**Comment by Ma27** [comment]
I don't see why it's wrong to backport 3ad3041918cdde96ddda60fc0950a13c7d48f954 as well though.

**Comment by ShamrockLee** [comment]
> I don't see why it's wrong to backport [3ad3041](https://github.com/NixOS/nixpkgs/commit/3ad3041918cdde96ddda60fc0950a13c7d48f954) as well though.

I just missed it. Thanks for reminding!

Have it added now.

**Comment by Ma27** [comment]
@worldofpeace @jonringer  any remarks? From my PoV this is good to go.

**Review by roberth — APPROVED** [review]

**Pull request merged**
