### PR TITLE
Pantheon updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test pantheon

**Comment by primeos** [comment]
@worldofpeace this might have broken `pantheon.appcenter`: https://hydra.nixos.org/job/nixpkgs/trunk/pantheon.appcenter.x86_64-linux/all

Just as a quick FYI in case you have time ;)

**Comment by worldofpeace** [comment]
> @worldofpeace this might have broken `pantheon.appcenter`: https://hydra.nixos.org/job/nixpkgs/trunk/pantheon.appcenter.x86_64-linux/all
> 
> Just as a quick FYI in case you have time ;)

Yep, I did notice this. It seems they've opted to require a newer libhandy in appcenter, for reasons I cannot remember.
Thanks for the heads up :sparkles:

**Comment by worldofpeace** [comment]
thanks @primeos, fixed in d74da4fe5273a3350719a07ae230e92dcc705de1 and on 20.03

**Pull request merged**
