### PR TITLE
ryujinx: 1.1.181 -> 1.1.213

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Description of changes

This update brings the long-awaited [Vulkan support](https://blog.ryujinx.org/vulkan/) ([full changelog](https://github.com/Ryujinx/Ryujinx/wiki/Changelog)). Tested on the Steam Deck with [Jovian-NixOS](https://github.com/Jovian-Experiments/Jovian-NixOS):

Screenshot_20220807_175238

Note that all existing shader caches created before 1.1.200 will be invalidated.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zhaofengli** [comment]
@sbruder Could you try adding `ffmpeg` to `runtimeDeps` and see if that works? It should have the same effect as adding to `LD_LIBRARY_PATH`. Also for future reference, it would be nice to figure out when Ryujinx stopped using the ffmpeg CLI.

**Review by sbruder — APPROVED** [review]
Thanks! It works great now.

**Review by IvarWithoutBones — APPROVED** [review]
Looks good to me, thanks! Nice to see the ffmpeg inclusion being fixed too.


I'll merge this in a few days when I get back to my computer, if no one else beats me to it :)

**Comment by IvarWithoutBones** [comment]
Works perfectly here as well :+1: 

Result of `nixpkgs-review pr 185617` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ryujinx</li>
  </ul>
</details>

**Pull request merged**
