### PR TITLE
dwarf-fortress-packages.dwarf-fortress_0_47_01: init

### LINKED ISSUE #78791: Dwarf Fortress Package is vastly behind, update.sh just creates empty game.json file
**Describe the bug**
Dwarf Fortress 0.47.01 was released today, and I was quite excited to play it
only to remember I'd likely have to package it. Ready to just throw a new hash in and be
done with it, I didn't realize I'd be spending my entire evening sitting there manually throwing hashes
in when an `update.sh` script was supposed to handle that all on it's own. I also realized that the last
version of Dwarf Fortress on NixOS was 0.44, is that not quite old by now?

**To Reproduce**
1. Clone Nix Repo
2. `nix-shell -p jq nix coreutils curl`
3. `sh update.sh`
3. `cat game.json`
**Expected behavior**
Functioning update script

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.13, NixOS, 19.09.1926.5d6da42cf79 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
until dfhack has support for the latest release, I'm not going to bump `dwarf-fortress` default.

However, you should be able to do `dwarf-fortress-packages.dwarf-fortress_0_47_01` and play the game.

closes: #78791
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by shazow** [comment]
Confirmed that this works for me (on NixOS). Thank you!

**Comment by shazow** [comment]
Btw, we could also update some of the themes. Here's pheobus which I use:

```patch
diff --git a/pkgs/games/dwarf-fortress/themes/themes.json b/pkgs/games/dwarf-fortress/themes/themes.json
index f2cc4ed3ac7..f4c47cce372 100644
--- a/pkgs/games/dwarf-fortress/themes/themes.json
+++ b/pkgs/games/dwarf-fortress/themes/themes.json
@@ -26,8 +26,8 @@
   },
   {
       "name": "phoebus",
-      "version": "44.10",
-      "sha256": "1fvl5251wzjns159snhw01p214k53vpdlyj7piv545r23q7wg2ji"
+      "version": "47.01",
+      "sha256": "1rf47p6a4f6scpzlmy9q3v1pakdjs06f9aingajpaia44lmjdfn6"
   },
   {
       "name": "obsidian",
```

Happy to make a separate PR if that's easier, let me know.

**Review by tomberek — APPROVED** [review]
Builds and runs on NixOS. Losing is fun.

**Comment by jonringer** [comment]
I was able to build and run the programs, and it appears others have tested.

**Comment by jonringer** [comment]
@shazow @tomberek thanks for the reviews!

**Pull request merged**
