### PR TITLE
vimPlugins.modus-themes-nvim: init at 2023-11-07

### PR DESCRIPTION
**Pull request by ambroisie**
## Description of changes

Adds https://github.com/miikanissi/modus-themes.nvim.

## Things done

### CODE REVIEW

**Comment by ambroisie** [comment]
Adding @GaetanLepage who seems to have been involved with merging `vimPlugins` PRs lately.

**Comment by GaetanLepage** [comment]
What we usually do after adding a plugin to `vim-plugin-names` is to run the updater script to update all the plugins.

**Comment by ambroisie** [comment]
I specifically did not do that to avoid merge conflicts.

**Comment by ambroisie** [comment]
Examples of other PRs that only added their plug-in to `generated.nix`:

* #262532 (not one of mine),
* A bunch of mine: #258774, #247233, #243474, #215736, #191478, #189117.

**Comment by GaetanLepage** [comment]
Ok thank you ! Very good to know indeed.
Everything looks good to me then !

**Review by GaetanLepage — APPROVED** [review]

**Pull request merged**
