### PR TITLE
[WIP] spotifyd: init at 0.2.2

### PR DESCRIPTION
**Pull request by bobvanderlinden**
###### Motivation for this change

Spotifyd is a daemon for Spotify. It is especially useful for headless servers that need to be able to play songs from Spotify.

This PR includes a basic implementation for a spotifyd module.

This PR is WIP because the package was not able to build. This problem is related to https://github.com/NixOS/nixpkgs/issues/30742.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by anderslundstedt** [comment]
Any progress on this? On the unstable channel, I was able to successfully build. But on execution it aborts as soon as I try to connect over Spotify Connect—`illegal hardware instruction`.

**Comment by bobvanderlinden** [comment]
I still cannot get this to build. What have you done specifically to get the binaries?

**Comment by anderslundstedt** [comment]
I checked out the `nixos-unstable` branch (at commit `bc41317e24317b0f506287f2d5bab00140b9b50e`). I then manually copied your spotifyd package (https://github.com/NixOS/nixpkgs/pull/47172/commits/714034d8c9cee30c3c713ccec53256fe96196f3f), manually commenting out the `cargoBuildFlags` line. Then `nix-env -iA nixpkgs.spotifyd` worked.

**Comment by flokli** [comment]
closing in favor of https://github.com/NixOS/nixpkgs/pull/55923.

**Pull request closed without merging**
