### PR TITLE
gnucash: 2.4.15 -> 3.1-1

### PR DESCRIPTION
**Pull request by mnacamura**
###### Motivation for this change

I would like to use GNU Cash with GTK3.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
## Things to be fixed
- [x] Google test fails with the following error messages:
```
/nix/store/05ckbdakp3jmrfymv44wzq1g0awdsdmw-gtest-1.8.0/lib/libgtest_main.a(gtest_main.cc.o): In function `main':
(.text.startup+0x21): undefined reference to `testing::InitGoogleTest(int*, char**)'
(.text.startup+0x26): undefined reference to `testing::UnitTest::GetInstance()'
(.text.startup+0x2e): undefined reference to `testing::UnitTest::Run()'
collect2: error: ld returned 1 exit status
```
This is fixed by adding `export NIX_CFLAGS_LINK="-lgtest -lgtest_main"` before checkPhase.
- [ ] Pass all tests. For the moment 9/108 fail.
- [x] Cannot change settings in `Edit > Preferences`; fixed by adding `dconf` to `propagatedUserEnvPkgs`

## Things that could be done in other PRs
- Install python binding 
- Install documents/helps
- Build with Ninja

### CODE REVIEW

**Comment by mnacamura** [comment]
For those using GNU Cash 2.4.x, is it better to keep version 2.4.15 and create a new package of version 3.0?

**Comment by regnat** [comment]
Amazing, just as I wanted to try to update gnucash, I realise someone's already done it, thanks @mnacamura .

I tried building it, it only works if I add `gettext` to the `buildInputs`, otherwise it fails with the error
```
  CMake Error at CMakeLists.txt:262 (message):
    Note the build can be configured with an older version of gettext by
    setting ALLOW_OLD_GETTEXT=ON but then some files will not be translated:
            - gnucash.desktop (requires at least gettext 0.19)
            - gnucash.appdata.xml (requires at least gettext 0.19.6)
  -- Configuring incomplete, errors occurred!
```

**Comment by regnat** [comment]
The tests also seem to pass for me

**Comment by mnacamura** [comment]
@regnat Thank you for reporting. Do you pass the tests even if you set `doCheck = true;` in `default.nix`?

**Comment by mnacamura** [comment]
Google test now runs correctly. Here is the test result:
```
40% tests passed, 65 tests failed out of 108

Total Test time (real) =  12.61 sec

The following tests FAILED:
          3 - test-print-parse-amount (Failed)
          5 - test-sx (Failed)
         10 - test-date-converting (Failed)
         11 - test-dom-converters1 (Failed)
         12 - test-kvp-frames (Failed)
         13 - test-load-backend (Failed)
         14 - test-load-xml2 (Failed)
         16 - test-string-converters (Failed)
         17 - test-xml-account (Failed)
         18 - test-xml-commodity (Failed)
         19 - test-xml-pricedb (Failed)
         20 - test-xml-transaction (Failed)
         21 - test-xml2-is-file (Failed)
         22 - test-real-data (Failed)
         23 - test-backend-dbi (Failed)
         24 - test-column-types (Failed)
         25 - test-sqlbe (Failed)
         26 - test-gnc-glib-utils (Failed)
         27 - test-resolve-file-path (Failed)
         28 - test-userdata-dir (Failed)
         29 - test-userdata-dir-invalid-home (Failed)
         31 - test-link (Failed)
         32 - test-load-engine (Failed)
         33 - test-guid (Failed)
         34 - test-date (Failed)
         35 - test-object (Failed)
         36 - test-commodities (Failed)
         37 - test-qof (Failed)
         38 - test-engine (Failed)
         39 - test-account-object (Failed)
         40 - test-group-vs-book (Failed)
         41 - test-lots (Failed)
         42 - test-querynew (Failed)
         43 - test-query (Failed)
         44 - test-split-vs-account (Failed)
         45 - test-transaction-reversal (Failed)
         46 - test-transaction-voiding (Failed)
         47 - test-recurrence (Failed)
         48 - test-business (Failed)
         49 - test-address (Failed)
         50 - test-customer (Failed)
         51 - test-employee (Failed)
         52 - test-job (Failed)
         53 - test-vendor (Failed)
         54 - test-numeric (Failed)
         55 - test-gnc-guid (Failed)
         56 - test-kvp-value (Failed)
         57 - test-qofsession (Failed)
         61 - test-gnc-timezone (Failed)
         63 - test-import-map (Failed)
         64 - test-qofquerycore (Failed)
         70 - test-load-c (Failed)
         71 - test-modsysver (Failed)
         72 - test-incompatdep (Failed)
         73 - test-agedver (Failed)
         74 - test-dynload (Failed)
         77 - test-gnc-module-swigged-c (Failed)
         78 - test-gnc-module-load-deps (Failed)
         80 - test-gnc-module-scm-module (Failed)
         81 - test-gnc-module-scm-multi (Failed)
         86 - test-link-generic-import (Failed)
         87 - test-import-pending-matches (Failed)
         88 - test-aqb (Failed)
         89 - test-tokenizer (Failed)
         90 - test-tx_import (Failed)
```

**Comment by mnacamura** [comment]
Test results for the moment:
```
92% tests passed, 9 tests failed out of 108

Total Test time (real) =  23.44 sec

The following tests FAILED:
         61 - test-gnc-timezone (Failed)
         70 - test-load-c (Failed)
         71 - test-modsysver (Failed)
         72 - test-incompatdep (Failed)
         73 - test-agedver (Failed)
         77 - test-gnc-module-swigged-c (Failed)
         78 - test-gnc-module-load-deps (Failed)
         80 - test-gnc-module-scm-module (Failed)
         81 - test-gnc-module-scm-multi (Failed)
```

**Comment by mnacamura** [comment]
Detailed results of the above 9 failed tests:
```
=== RUN test-gnc-timezone ===
Running main() from gtest_main.cc
[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from gnc_timezone_constructors
[ RUN      ] gnc_timezone_constructors.test_default_constructor
[       OK ] gnc_timezone_constructors.test_default_constructor (0 ms)
[ RUN      ] gnc_timezone_constructors.test_pacific_time_constructor
/home/mnacamura/repos/nixpkgs/pkgs/applications/office/gnucash/gnucash-3.1/libgnucash/engine/test/gtest-gnc-timezone.cpp:54: Failure
Value of: tz->std_zone_abbrev() == "PST"
  Actual: false
Expected: true
/home/mnacamura/repos/nixpkgs/pkgs/applications/office/gnucash/gnucash-3.1/libgnucash/engine/test/gtest-gnc-timezone.cpp:55: Failure
Value of: tz->dst_zone_abbrev() == "PDT"
  Actual: false
Expected: true
/home/mnacamura/repos/nixpkgs/pkgs/applications/office/gnucash/gnucash-3.1/libgnucash/engine/test/gtest-gnc-timezone.cpp:57: Failure
      Expected: -8
To be equal to: tz->base_utc_offset().hours()
      Which is: 9
/home/mnacamura/repos/nixpkgs/pkgs/applications/office/gnucash/gnucash-3.1/libgnucash/engine/test/gtest-gnc-timezone.cpp:59: Failure
      Expected: -7
To be equal to: dst_offset.hours()
      Which is: 9
unknown file: Failure
C++ exception with description "Year is out of valid range: 1400..10000" thrown in the test body.
[  FAILED  ] gnc_timezone_constructors.test_pacific_time_constructor (0 ms)
[ RUN      ] gnc_timezone_constructors.test_posix_timezone
[       OK ] gnc_timezone_constructors.test_posix_timezone (0 ms)
[ RUN      ] gnc_timezone_constructors.test_gmt_timezone
[       OK ] gnc_timezone_constructors.test_gmt_timezone (0 ms)
[ RUN      ] gnc_timezone_constructors.test_GMT_plus_7_timezone
/home/mnacamura/repos/nixpkgs/pkgs/applications/office/gnucash/gnucash-3.1/libgnucash/engine/test/gtest-gnc-timezone.cpp:96: Failure
      Expected: tz->std_zone_abbrev()
      Which is: "JST"
To be equal to: "-07"

...

[  FAILED  ] gnc_timezone_constructors.test_IANA_Minsk_tz (5 ms)
[ RUN      ] gnc_timezone_constructors.test_bogus_time_constructor
[       OK ] gnc_timezone_constructors.test_bogus_time_constructor (0 ms)
[----------] 9 tests from gnc_timezone_constructors (24 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test case ran. (24 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] gnc_timezone_constructors.test_pacific_time_constructor
[  FAILED  ] gnc_timezone_constructors.test_GMT_plus_7_timezone
[  FAILED  ] gnc_timezone_constructors.test_IANA_Belize_tz
[  FAILED  ] gnc_timezone_constructors.test_IANA_Perth_tz
[  FAILED  ] gnc_timezone_constructors.test_IANA_Minsk_tz

 5 FAILED TESTS

=== RUN test-load-c ===
<WARNING> (gnc.module) Could not locate module gnucash/foo interface v.0

=== RUN test-modsysver ===
  ok

=== RUN test-incompatdep ===
  ok

=== RUN test-agedver ===
<WARNING> (gnc.module) Could not locate module gnucash/agedver interface v.5
 failed

=== RUN test-gnc-module-swigged-c ===
./test.sh: line 6: ./bin/test-gnc-module-swigged-c: No such file or directory

=== RUN test-gnc-module-load-deps ===
./test.sh: line 6: ./bin/test-gnc-module-load-deps: No such file or directory

=== RUN test-gnc-module-scm-module ===
./test.sh: line 6: ./bin/test-gnc-module-scm-module: No such file or directory

=== RUN test-gnc-module-scm-multi ===
./test.sh: line 6: ./bin/test-gnc-module-scm-multi: No such file or directory
```

**Comment by mnacamura** [comment]
Although some tests fail, the built binary works fine for me. So, I would like to disable test for now and wait for review.

**Comment by regnat** [comment]
My bad for the tests, I though `doCheck = true` was the default so I just commented out the line. It indeed fails with `doCheck = true`.

I agree that this shouldn't block the merge as the tool itself runs fine

**Review by thufschmitt — APPROVED** [review]

**Comment by mnacamura** [comment]
What if open your file with `gnucash26` and then with `gnucash`? webkitgtk-2.4 may be whitelisted by adding the following snippet to `~/.config/nixpkgs/config.nix`:
```
permittedInsecurePackages = [
         "webkitgtk-2.4.11"
       ];
```

**Comment by emmanuelrosa** [comment]
That's what I tried, and is the correct upgrade path. But right now it's not possible because webkitgtk-2.4.11, a dependency of gnucash 2.6, doesn't build due to missing `xdamage`.

**Comment by emmanuelrosa** [comment]
Assuming gnucash 3 will be the default, the NixOS release notes need to be updated to inform users of the upgrade instructions; Which of course means 2.6 needs to stick around (and be functional) for the Jackrabbit release.

**Pull request merged**
