### PR TITLE
darwin.libiconv: switch to libiconvReal and add to darwin-aliases

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

With https://github.com/NixOS/nixpkgs/pull/238993 and https://github.com/NixOS/nixpkgs/pull/299360, it is now possible to deprecate darwin.libiconv and switch Darwin to using upstream libiconv with a compatible ABI. This PR does that and updates packages that were using `darwin.libiconv` to use just `libiconv`.

Since this affects the stdenv, I’m targeting staging. I tested by building the stdenv on both platforms and GHC on aarch64-darwin. GHC uses `install_name_tool` to swap libiconv from the system one to the one in nixpkgs, so that it built successfully is a good test of the ABI compatibility implemented. I also confirmed eval locally using ofborg’s `outpaths.nix`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
@ofborg eval

**Review by ghost — COMMENTED** [review]
looks like this is the first use of the darwin compatibility abi in libiconv. I think that the substituteInPlace should be changed to `replace-fail` . looking over the headers it seems that defining `LIBICONV_PLUG` almost has the same effect except that the extensions are not defined. 
https://github.com/NixOS/nixpkgs/blob/bc061915ac2cf395e4d1f021cb565f495edfa24a/pkgs/development/libraries/libiconv/default.nix#L38-L45

looks good otherwise.

**Comment by reckenrode** [comment]
> looks like this is the first use of the darwin compatibility abi in libiconv.

I’m not surprised. I added it in anticipation of doing this PR. I originally had it build the compatible ABI unconditionally on Darwin, but it was desired to keep the upstream one the default so that `libiconvReal` would still correspond to it, so the feature flag was added.

> I think that the substituteInPlace should be changed to replace-fail .

I can add it as clean up when I get home.

> looking over the headers it seems that defining LIBICONV_PLUG almost has the same effect except that the extensions are not defined.

I think I looked at that, but it didn’t do what we need. Darwin needs a stand alone build with system symbol names (for compatibility with what Apple ships). It also needs to reexport `libcharset.dylib`, which is a platform peculiarity due to a historical accident.

**Comment by reckenrode** [comment]
I didn’t do a full bootstrap, but I did confirm libiconv built after changing it to use `--replace-fail`.

**Review by ghost — APPROVED** [review]

**Pull request merged**
