### PR TITLE
titanion: init at 0.3

### PR DESCRIPTION
**Pull request by fgaz**
###### Description of changes

More stuff from Kenta Cho :)

cc @aidalgol 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by necrophcodr** [comment]
Just tested it and the game runs perfectly fine on x86_64-linux NixOS. However, since this is a fully fledged game, I might suggest also adding a desktop item using the makeDesktopItem and copyDesktopItems commands. For examples on how this can be done, check out https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/assaultcube/default.nix#L49-L59

**Comment by fgaz** [comment]
Good point, and all other kenta cho games lack those too. I'd like to add them in another pr, so I opened #177193 to track the issue

**Comment by fgaz** [comment]
@necrophcodr @aidalgol if you think the package is ok could you approve the pr?

**Comment by aidalgol** [comment]
I don't appear to be able to approve PRs in this project. :confused:

**Review by necrophcodr — APPROVED** [review]
Looks good, I don't see any flaws by now.

**Pull request merged**
