### PR TITLE
Python: update pandas, and other packages

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform(s): NixOS / OSX / Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
9cc5857 might solve #13163  @bjornfor 
Need to build and test scikitlearn to be sure we don't get segfaults again.

**Comment by lancelotsix** [comment]
Is there a strong reason to keep pandas_17? It is never used as a dependency here. From a maintenance point of view, having only one version within nixpkgs seems easier. Keeping multiple versions can make sense if a recent version of the lib breaks existing software, but it do not seem to be applicable here.

**Comment by FRidh** [comment]
Some time ago there was a discussion about keeping some older versions of
numpy, scipy and pandas. The reason being that sometimes behaviour changed
or bugs were introduced. Numpy updates occasionally broke Scipy. And also
in the case of a Pandas update, the Darwin Nix expression broke several
times now.

I am now keeping one older version in, so that people will always have one
working version.

**Comment by lancelotsix** [comment]
@FRidh do you mainain the WIP  flag? It looks good to me.

Will you follow up on the openblas to integrate the next non-rc release?

**Comment by FRidh** [comment]
I split off the commit with numpy+openblas_2_16.

**Pull request merged**
