### PR TITLE
Backport: callHackage: Keep deriver, like callCabal2nix

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Motivation for this change

@vcunat Not sure if this sort of thing is appropriate to backport to 18.03 from master, but it's just adding functionality to nix stuff, not changing any package versions or anything.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
@ElvishJerricco, did you test whether the new code works fine in the `18.03` branch?

**Review by peti — APPROVED** [review]
If it works okay, then I think that change is fine to backport.

**Comment by ElvishJerricco** [comment]
@peti Yea I'm using on my desktop on 18.03. Really great to not have to recheck all-cabal-hashes after garbage collection every day :P

**Comment by vcunat** [comment]
> If it works okay, then I think that change is fine to backport.

:+1:

**Pull request merged**
