### PR TITLE
buildPythonPackage: always export `LANG=C.UTF-8`

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Now that C.UTF-8 is available, let's use it in Python packages.

https://github.com/NixOS/nixpkgs/issues/20192

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Note I will need to clean up the expressions a bit (used `git grep` and `sed` here).

**Comment by Mic92** [comment]
As I said in https://github.com/NixOS/nixpkgs/pull/54485#issuecomment-461748252
we also need to support this for the macOS stdenv as well or 
else we would break macOS support horrible.
It is probably just a simple patch. However I can not test it, since
I don't have access to the hardware/software. If somebody wants to help me out on that, let me know. Also I would move this to stdenv actually since also other application can profit from that.

**Comment by FRidh** [comment]
I see, so we're blocked then.

**Comment by FRidh** [comment]
For Darwin we can use the approach as in https://github.com/NixOS/nixpkgs/commit/8220b5bac8e934e8d6c6cc3510f3ed33b1bd2a50 for now.

**Comment by FRidh** [comment]
Included https://github.com/NixOS/nixpkgs/commit/1fccd255953b6025a4d0342c2cf5641e5b6b6ced in `staging-next`. Cleaning up expressions is for another time.

**Pull request closed without merging**
