### PR TITLE
rPackages: cleaned up iconv dependencies of inputs to synthpop

### PR DESCRIPTION
**Pull request by nviets**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin

### CODE REVIEW

**Review by jbedo — CHANGES_REQUESTED** [review]
Could you fix the typo in the commit message? Otherwise, is this aarch64 specific? Synthpop seems to load for me without this patch on x86_64.

**Comment by nviets** [comment]
Done - thanks. Yes, you're right about this only being needed for aarch64. Synthpop already built fine on x86 for me too. I didn't dig too deep on the root cause, but something was missing libiconv on aarch64-darwin. With this patch, the library continues to build fine on x86.

**Comment by jbedo** [comment]
This seems darwin specific as aarch64-linux builds fine: https://hydra.nixos.org/job/nixpkgs/r-updates/rPackages.synthpop.aarch64-linux. Do you know if this is a problem on x86_64-darwin? There are a handful of other packages that have iconv dependencies on darwin specifically, e.g.,: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/r-modules/default.nix#L502. Perhaps we should add iconv to the general builder for darwin systems instead.

**Comment by nviets** [comment]
I don't have an x86_64-darwin machine to test on, sorry. Upon closer inspection of my error log, it looks like it's actually synthpop's dependency libcoin that's failing so the buildInput should really be for it if we keep it at the package level.

That said, I think you may be right about adding iconv as a general builder on all darwin systems, including x86_64. Some googling turned up [this post](https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx), which suggests the issue is common on all darwin systems.

**Comment by nviets** [comment]
Added libiconv to the general builder for darwin systems: https://github.com/NixOS/nixpkgs/pull/214866. Let me know if it should go elsewhere.

**Pull request closed without merging**
