### PR TITLE
urbit: 0.6.0 -> 0.7.2

### PR DESCRIPTION
**Pull request by dpc**
###### Motivation for this change

I just updated https://github.com/NixOS/nixpkgs/pull/55100 to see it will be OK now.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dpc** [comment]
@GrahamcOfBorg build urbit

**Comment by dotlambda** [comment]
@GrahamcOfBorg build urbit

**Comment by bsima** [comment]
The latest is actually v0.7.3 now...

**Comment by dpc** [comment]
I guess until https://github.com/urbit/urbit/issues/1206 is done, there's no point in trying.

**Pull request closed without merging**
