### PR TITLE
graph-cli: fix runtime crash, 0.1.18 -> 0.1.19

### LINKED ISSUE #215079: `graph-cli` crashes at runtime
### Describe the bug
The package `graph-cli` (binary `graph`) is unusable at runtime: it always crashes.

### Steps To Reproduce
1.
```
$ cat test-graph-cli.csv
date,added,deleted,commits
2019-05-17,445,0,2
2019-05-20,155,3,2
```
2.
```
$ graph test-graph-cli.csv
```
results in an error:
```
Traceback (most recent call last):
  File "/nix/store/1l26pvib4gzjpn1gfaajkqwhzi40pjql-graph-cli-0.1.18/bin/.graph-wrapped", line 9, in <module>
    sys.exit(main.main())
  File "/nix/store/1l26pvib4gzjpn1gfaajkqwhzi40pjql-graph-cli-0.1.18/lib/python3.10/site-packages/graph_cli/main.py", line 17, in main
    create_graph(graphs)
  File "/nix/store/1l26pvib4gzjpn1gfaajkqwhzi40pjql-graph-cli-0.1.18/lib/python3.10/site-packages/graph_cli/graph.py", line 261, in create_graph
    fig, ax = plt.subplots(figsize=(Graph.figsize))
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1442, in subplots
    fig = figure(**fig_kw)
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 783, in figure
    manager = new_figure_manager(
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 358, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 336, in _warn_if_gui_out_of_main_thread
    if _get_required_interactive_framework(_get_backend_mod()):
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 207, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/pyplot.py", line 265, in switch_backend
    backend_mod = importlib.import_module(
  File "/nix/store/sp5x6s8n36gjlwck74xhj1i61p66vcpa-python3-3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/nix/store/fq03dka9ivs40a4hjn0aajl7m5az48g0-python3.10-matplotlib-3.6.2/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    raise ImportError(
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
```

### Expected behavior
The application works.

### Screenshots
N/A.

### Notify maintainers
* @leungbk 
* Maybe @kilianar ? As they committed a version upgrade

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 23.05 (Stoat), 23.05.20221229.677ed08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/store/7m0y4s8bd0pj7mazwdxrwa2m14hplims-source`
```

### PR DESCRIPTION
**Pull request by sir4ur0n**
Fixes https://github.com/NixOS/nixpkgs/issues/215079

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kilianar** [comment]
Thank you for addressing this issue, although the proposed solution is not optimal as it results in double wrapping.

**Comment by sir4ur0n** [comment]
@kilianar I tried your method, it works but I still had to keep these 2 changes:
```nix
  nativeBuildInputs = [ qt5.wrapQtAppsHook ];

    (matplotlib.override { enableQt = true; })
```

So compared to my original PR, I added your 2 changes and removed this one:
```nix
  postInstall = "wrapQtApp $out/bin/graph";
```

I trust you that it is better :sweat_smile: 

I tested with:
```
$ nom-shell -I nixpkgs=./ -p graph-cli
[]$ graph ~/sandbox/test-graph-cli.csv
```
and it works :+1:

**Comment by kilianar** [comment]
Thank you for including those changes. Version [0.1.19](https://pypi.org/project/graph-cli/) was released two weeks ago. Would it be possible for you to update the package as well? Additionally, when updating, consider changing `sha256` = to `hash =`.

**Comment by sir4ur0n** [comment]
@kilianar done

**Review by kilianar — APPROVED** [review]
Changes LGTM and they do indeed resolve the issue

**Pull request merged**
