### PR TITLE
gcc-arm-embedded: 5.2 -> 5.4

### PR DESCRIPTION
**Pull request by rasendubi**
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
I think the move of the default gcc version from 4.9 to 5.4 deserves its own commit.

**Comment by bjornfor** [comment]
A comment about the license change (in the commit message)?

**Comment by rasendubi** [comment]
@bjornfor done

**Comment by bjornfor** [comment]
@rasendubi: Thanks!

I see that up to now we've kept all the old versions (4.7, 4.8, 4.9, ...). So I don't think we should remove 5.2, one of the "middle" versions. Maybe this PR can just *add* 5.4 (and move the default version)?

Unless some of those old versions are long-term-support versions, I think we should remove packages in chronological order and not create "holes".

Thoughts?

**Comment by rasendubi** [comment]
gcc-arm-embedded projects has next [series](https://launchpad.net/gcc-arm-embedded/+series): 4.6, 4.7, 4.8, 4.9, 5.0 (which actually includes 5.x gcc versions) and 6.0 (not yet released). So available nix expressions follow these series (except 4.6 is missing). I think that makes sense as 5.4 _is_ an update for 5.2.

**Comment by rasendubi** [comment]
That was my reasoning. If you think keeping 5.2 makes sense, I'm okay with that.

**Comment by bjornfor** [comment]
@rasendubi: Ah, right, it comes back to me now: gcc 5 changed the version number scheme. No, with this new information, I don't think we should keep 5.2.

**Comment by bjornfor** [comment]
I'll push when local build tests pass (nox-review).

**Comment by bjornfor** [comment]
Pushed to master (34b5d283cd2a8bbc05b798599120e53024865f08 and parents). Thanks!

**Pull request closed without merging**
