### PR TITLE
gcc: Simplify configure flags

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

No more `crossAttrs.configureFlags`, simplified platform flags, and more tool env vars.

The history is intentionally complicated; it will assist me with bisecting various cross related regressions (especially the build != host == target GCC builds).

###### Things done

No native hashes should be changed. The first commits, "morally equivalent" to the final diff, are tested at https://hydra.nixos.org/jobset/nixpkgs/ericson2314-old-cross-known-good .

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @bgamari

### CODE REVIEW

**Comment by orivej** [comment]
Could you explain why changing env vars does not rebuild anything? Is it important that your new simple commits are before merge commits (possibly breaking eval or build between the first and the last merge commit, unless you have confirmed that they don't)?

**Comment by orivej** [comment]
> Could you explain why changing env vars does not rebuild anything?

Ah, because it only affects cross builds.

> The history is intentionally complicated; it will assist me with bisecting various cross related regressions (especially the build != host == target GCC builds).

I'm not sure it will. Bisection with `git bisect run` between the base revision of this PR and the future master will be impractical after a few merges of staging into master. Manual bisection with `git bisect good/bad` does not seem to benefit from this PR: you are better off either with tagging the milestone revisions (8f970d09fe8e895b6bb7dbf52f80411a45504b19 198dceccbe5414a5fd72ca83624c0cc715db1aad 71186e73455a4e06e96a31da34b76f84e545ba1f ab77a6bb1e7d2ff475210ad392f1a9bd1bb6ba3a 703a9f93c1254f7bdf0350ca0462de0d78033c62) as `cross1` .. `cross5`, or with keeping the merges of these revisions in a private branch.

**Comment by Ericson2314** [comment]
Ah sorry, I didn't mean bisection so much as what one does after.

From https://hydra.nixos.org/jobset/nixpkgs/ericson2314-cross-trunk I already know what went wrong when. I'm trying to make changes to working commits such that they keep  working, and when with later commits, they are less broken.

In this case, I'm mostly simplifying things, but through that method I know the change is valid. Next up, I have some changes to `builder.sh` that actually fix things, which I'll want to likewise repeatedly merge against these merge commits.

Back to the bisecting part, if my new fix doesn't fix all of the new merge commits, I can see roughly where some thing went wrong. I can also bisect the original history, merging the bisect commits with the most recent merge commit for a sort of virtual linear history.

That's all quite complex. Probably the simplest way to look at it is I'm trying to make there be at least one path on the history with no regressions. I'm breaking off chunks of history to get to the present while fixing any breakage along the way.

**Comment by Ericson2314** [comment]
It might just be easier to explain after I make the next PR, which is now ready. Merging this so that makes sense.

**Pull request merged**
