### PR TITLE
Tilix 1.8.1, gtkd 3.8.3

### LINKED ISSUE #33288: Tilix segfaults when trying to change the window name by clicking on it
## Issue description

Tilix allows changing its window title by simply clicking on the title itself in the titlebar. Then the title must be replaced by an input box.
Instead of that, Tilix segfaults.

### Steps to reproduce

Install Tilix. Launch Tilix. Click on Tilix titlebar.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.73, NixOS, 18.03.git.0bbf671 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by hedning**
###### Motivation for this change

Update tilix to the newest version (the current version is quite old). Required updating gtkd too.

fixes  #33288

###### Things done

Build and tested tilix successfully with the updated gtkd. Searching for packages that depend on gtkd only surfaces tilix.

cc @ThomasMader in case I've done something silly with gtkd

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
Looks good to me.

**Comment by ThomasMader** [comment]
@GrahamcOfBorg build gtkd tilix

**Comment by hedning** [comment]
Added release build flags in accordance with https://github.com/gnunn1/tilix/wiki/Building-with-Autotools

**Comment by ThomasMader** [comment]
@GrahamcOfBorg build tilix

**Comment by ThomasMader** [comment]
Ok someone else has to merge it because I don't have the rights.

**Pull request merged**
