### PR TITLE
linuxKernels.linux_lqx: fix build by removing SCHED_CLASS_EXT option

### PR DESCRIPTION
**Pull request by thiagokokada**
Fix issue #365136.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @GGG-KILLER for testing.

**Comment by thiagokokada** [comment]
@ofborg build linuxKernels.linux_lqx

**Comment by GGG-KILLER** [comment]
@ofborg build linux_lqx

**Comment by GGG-KILLER** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365166`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 38 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_lqx.can-isotp</li>
    <li>linuxKernel.packages.linux_lqx.dddvb</li>
    <li>linuxKernel.packages.linux_lqx.isgx</li>
    <li>linuxKernel.packages.linux_lqx.ivsc-driver</li>
    <li>linuxKernel.packages.linux_lqx.ixgbevf</li>
    <li>linuxKernel.packages.linux_lqx.mxu11x0</li>
    <li>linuxKernel.packages.linux_lqx.ndiswrapper</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidiabl</li>
    <li>linuxKernel.packages.linux_lqx.phc-intel</li>
    <li>linuxKernel.packages.linux_lqx.r8125</li>
    <li>linuxKernel.packages.linux_lqx.r8168</li>
    <li>linuxKernel.packages.linux_lqx.sysdig</li>
    <li>linuxKernel.packages.linux_lqx.tbs</li>
    <li>linuxKernel.packages.linux_lqx.zfs_2_1</li>
    <li>linuxPackages_lqx.can-isotp</li>
    <li>linuxPackages_lqx.dddvb</li>
    <li>linuxPackages_lqx.isgx</li>
    <li>linuxPackages_lqx.ivsc-driver</li>
    <li>linuxPackages_lqx.ixgbevf</li>
    <li>linuxPackages_lqx.mxu11x0</li>
    <li>linuxPackages_lqx.ndiswrapper</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta_open</li>
    <li>linuxPackages_lqx.nvidiabl</li>
    <li>linuxPackages_lqx.phc-intel</li>
    <li>linuxPackages_lqx.r8125</li>
    <li>linuxPackages_lqx.r8168</li>
    <li>linuxPackages_lqx.sysdig</li>
    <li>linuxPackages_lqx.tbs</li>
    <li>linuxPackages_lqx.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>:x: 23 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_lqx.asus-ec-sensors (linuxKernel.packages.linux_lqx.asus-ec-sensors)</li>
    <li>linuxPackages_lqx.ax99100 (linuxKernel.packages.linux_lqx.ax99100)</li>
    <li>linuxPackages_lqx.digimend (linuxKernel.packages.linux_lqx.digimend)</li>
    <li>linuxPackages_lqx.fwts-efi-runtime (linuxKernel.packages.linux_lqx.fwts-efi-runtime)</li>
    <li>linuxPackages_lqx.hid-tmff2 (linuxKernel.packages.linux_lqx.hid-tmff2)</li>
    <li>linuxPackages_lqx.ithc (linuxKernel.packages.linux_lqx.ithc)</li>
    <li>linuxPackages_lqx.linux-gpib (linuxKernel.packages.linux_lqx.linux-gpib)</li>
    <li>linuxPackages_lqx.liquidtux (linuxKernel.packages.linux_lqx.liquidtux)</li>
    <li>linuxPackages_lqx.lttng-modules (linuxKernel.packages.linux_lqx.lttng-modules)</li>
    <li>linuxPackages_lqx.mba6x_bl (linuxKernel.packages.linux_lqx.mba6x_bl)</li>
    <li>linuxPackages_lqx.mbp2018-bridge-drv (linuxKernel.packages.linux_lqx.mbp2018-bridge-drv)</li>
    <li>linuxPackages_lqx.mwprocapture (linuxKernel.packages.linux_lqx.mwprocapture)</li>
    <li>linuxPackages_lqx.prl-tools (linuxKernel.packages.linux_lqx.prl-tools)</li>
    <li>linuxPackages_lqx.qc71_laptop (linuxKernel.packages.linux_lqx.qc71_laptop)</li>
    <li>linuxPackages_lqx.rtl8189es (linuxKernel.packages.linux_lqx.rtl8189es)</li>
    <li>linuxPackages_lqx.rtl8189fs (linuxKernel.packages.linux_lqx.rtl8189fs)</li>
    <li>linuxPackages_lqx.rtl8192eu (linuxKernel.packages.linux_lqx.rtl8192eu)</li>
    <li>linuxPackages_lqx.rtl8821au (linuxKernel.packages.linux_lqx.rtl8821au)</li>
    <li>linuxPackages_lqx.system76 (linuxKernel.packages.linux_lqx.system76)</li>
    <li>linuxPackages_lqx.system76-acpi (linuxKernel.packages.linux_lqx.system76-acpi)</li>
    <li>linuxPackages_lqx.universal-pidff (linuxKernel.packages.linux_lqx.universal-pidff)</li>
    <li>linuxPackages_lqx.veikk-linux-driver (linuxKernel.packages.linux_lqx.veikk-linux-driver)</li>
    <li>linuxPackages_lqx.vendor-reset (linuxKernel.packages.linux_lqx.vendor-reset)</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 95 packages built:</summary>
  <ul>
    <li>linux_lqx (linuxPackages_lqx.kernel)</li>
    <li>linux_lqx.dev (linuxPackages_lqx.kernel.dev)</li>
    <li>linuxPackages_lqx.acpi_call (linuxKernel.packages.linux_lqx.acpi_call)</li>
    <li>linuxPackages_lqx.akvcam (linuxKernel.packages.linux_lqx.akvcam)</li>
    <li>linuxPackages_lqx.amneziawg (linuxKernel.packages.linux_lqx.amneziawg)</li>
    <li>linuxPackages_lqx.apfs (linuxKernel.packages.linux_lqx.apfs)</li>
    <li>linuxPackages_lqx.asus-wmi-sensors (linuxKernel.packages.linux_lqx.asus-wmi-sensors)</li>
    <li>linuxPackages_lqx.batman_adv (linuxKernel.packages.linux_lqx.batman_adv)</li>
    <li>linuxPackages_lqx.bbswitch (linuxKernel.packages.linux_lqx.bbswitch)</li>
    <li>linuxPackages_lqx.broadcom_sta (linuxKernel.packages.linux_lqx.broadcom_sta)</li>
    <li>linuxPackages_lqx.ch9344 (linuxKernel.packages.linux_lqx.ch9344)</li>
    <li>linuxPackages_lqx.chipsec (linuxKernel.packages.linux_lqx.chipsec)</li>
    <li>linuxPackages_lqx.chipsec.dist (linuxKernel.packages.linux_lqx.chipsec.dist)</li>
    <li>linuxPackages_lqx.corefreq (linuxKernel.packages.linux_lqx.corefreq)</li>
    <li>linuxPackages_lqx.cryptodev (linuxKernel.packages.linux_lqx.cryptodev)</li>
    <li>linuxPackages_lqx.ddcci-driver (linuxKernel.packages.linux_lqx.ddcci-driver)</li>
    <li>linuxPackages_lqx.decklink (linuxKernel.packages.linux_lqx.decklink)</li>
    <li>linuxPackages_lqx.deepin-anything-module (linuxKernel.packages.linux_lqx.deepin-anything-module)</li>
    <li>linuxPackages_lqx.dpdk-kmods (linuxKernel.packages.linux_lqx.dpdk-kmods)</li>
    <li>linuxPackages_lqx.drbd (linuxKernel.packages.linux_lqx.drbd)</li>
    <li>linuxPackages_lqx.ena (linuxKernel.packages.linux_lqx.ena)</li>
    <li>linuxPackages_lqx.evdi (linuxKernel.packages.linux_lqx.evdi)</li>
    <li>linuxPackages_lqx.facetimehd (linuxKernel.packages.linux_lqx.facetimehd)</li>
    <li>linuxPackages_lqx.fanout (linuxKernel.packages.linux_lqx.fanout)</li>
    <li>linuxPackages_lqx.framework-laptop-kmod (linuxKernel.packages.linux_lqx.framework-laptop-kmod)</li>
    <li>linuxPackages_lqx.gasket (linuxKernel.packages.linux_lqx.gasket)</li>
    <li>linuxPackages_lqx.gcadapter-oc-kmod (linuxKernel.packages.linux_lqx.gcadapter-oc-kmod)</li>
    <li>linuxPackages_lqx.hid-ite8291r3 (linuxKernel.packages.linux_lqx.hid-ite8291r3)</li>
    <li>linuxPackages_lqx.hid-t150 (linuxKernel.packages.linux_lqx.hid-t150)</li>
    <li>linuxPackages_lqx.hpuefi-mod (linuxKernel.packages.linux_lqx.hpuefi-mod)</li>
    <li>linuxPackages_lqx.ipu6-drivers (linuxKernel.packages.linux_lqx.ipu6-drivers)</li>
    <li>linuxPackages_lqx.it87 (linuxKernel.packages.linux_lqx.it87)</li>
    <li>linuxPackages_lqx.jool (linuxKernel.packages.linux_lqx.jool)</li>
    <li>linuxPackages_lqx.kvmfr (linuxKernel.packages.linux_lqx.kvmfr)</li>
    <li>linuxPackages_lqx.lenovo-legion-module (linuxKernel.packages.linux_lqx.lenovo-legion-module)</li>
    <li>linuxPackages_lqx.lkrg (linuxKernel.packages.linux_lqx.lkrg)</li>
    <li>linuxPackages_lqx.msi-ec (linuxKernel.packages.linux_lqx.msi-ec)</li>
    <li>linuxPackages_lqx.mstflint_access (linuxKernel.packages.linux_lqx.mstflint_access)</li>
    <li>linuxPackages_lqx.nct6687d (linuxKernel.packages.linux_lqx.nct6687d)</li>
    <li>linuxPackages_lqx.netatop (linuxKernel.packages.linux_lqx.netatop)</li>
    <li>linuxPackages_lqx.new-lg4ff (linuxKernel.packages.linux_lqx.new-lg4ff)</li>
    <li>linuxPackages_lqx.nullfs (linuxKernel.packages.linux_lqx.nullfs)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11 ,linuxPackages_lqx.nvidia_x11_beta)</li>
    <li>linuxPackages_lqx.nvidia_x11.bin (linuxKernel.packages.linux_lqx.nvidia_x11.bin ,linuxPackages_lqx.nvidia_x11_beta.bin)</li>
    <li>linuxPackages_lqx.nvidia_x11.firmware (linuxKernel.packages.linux_lqx.nvidia_x11.firmware ,linuxPackages_lqx.nvidia_x11_beta.firmware)</li>
    <li>linuxPackages_lqx.nvidia_x11.lib32 (linuxKernel.packages.linux_lqx.nvidia_x11.lib32 ,linuxPackages_lqx.nvidia_x11_beta.lib32)</li>
    <li>linuxPackages_lqx.nvidia_x11_beta_open (linuxKernel.packages.linux_lqx.nvidia_x11_beta_open ,linuxPackages_lqx.nvidia_x11_stable_open)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy535 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy535)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy535.bin (linuxKernel.packages.linux_lqx.nvidia_x11_legacy535.bin)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy535.firmware (linuxKernel.packages.linux_lqx.nvidia_x11_legacy535.firmware)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy535.lib32 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy535.lib32)</li>
    <li>linuxPackages_lqx.nvidia_x11_production (linuxKernel.packages.linux_lqx.nvidia_x11_production)</li>
    <li>linuxPackages_lqx.nvidia_x11_production.bin (linuxKernel.packages.linux_lqx.nvidia_x11_production.bin)</li>
    <li>linuxPackages_lqx.nvidia_x11_production.firmware (linuxKernel.packages.linux_lqx.nvidia_x11_production.firmware)</li>
    <li>linuxPackages_lqx.nvidia_x11_production.lib32 (linuxKernel.packages.linux_lqx.nvidia_x11_production.lib32)</li>
    <li>linuxPackages_lqx.nvidia_x11_production_open (linuxKernel.packages.linux_lqx.nvidia_x11_production_open)</li>
    <li>linuxPackages_lqx.openafs (linuxKernel.packages.linux_lqx.openafs ,linuxPackages_lqx.openafs_1_8)</li>
    <li>linuxPackages_lqx.openrazer (linuxKernel.packages.linux_lqx.openrazer)</li>
    <li>linuxPackages_lqx.opensnitch-ebpf (linuxKernel.packages.linux_lqx.opensnitch-ebpf)</li>
    <li>linuxPackages_lqx.rr-zen_workaround (linuxKernel.packages.linux_lqx.rr-zen_workaround)</li>
    <li>linuxPackages_lqx.rtl8188eus-aircrack (linuxKernel.packages.linux_lqx.rtl8188eus-aircrack)</li>
    <li>linuxPackages_lqx.rtl8723ds (linuxKernel.packages.linux_lqx.rtl8723ds)</li>
    <li>linuxPackages_lqx.rtl8812au (linuxKernel.packages.linux_lqx.rtl8812au)</li>
    <li>linuxPackages_lqx.rtl8814au (linuxKernel.packages.linux_lqx.rtl8814au)</li>
    <li>linuxPackages_lqx.rtl8821ce (linuxKernel.packages.linux_lqx.rtl8821ce)</li>
    <li>linuxPackages_lqx.rtl8821cu (linuxKernel.packages.linux_lqx.rtl8821cu)</li>
    <li>linuxPackages_lqx.rtl8852au (linuxKernel.packages.linux_lqx.rtl8852au)</li>
    <li>linuxPackages_lqx.rtl8852bu (linuxKernel.packages.linux_lqx.rtl8852bu)</li>
    <li>linuxPackages_lqx.rtl88x2bu (linuxKernel.packages.linux_lqx.rtl88x2bu)</li>
    <li>linuxPackages_lqx.rtl88xxau-aircrack (linuxKernel.packages.linux_lqx.rtl88xxau-aircrack)</li>
    <li>linuxPackages_lqx.rtw88 (linuxKernel.packages.linux_lqx.rtw88)</li>
    <li>linuxPackages_lqx.rust-out-of-tree-module (linuxKernel.packages.linux_lqx.rust-out-of-tree-module)</li>
    <li>linuxPackages_lqx.ryzen-smu (linuxKernel.packages.linux_lqx.ryzen-smu)</li>
    <li>linuxPackages_lqx.shufflecake (linuxKernel.packages.linux_lqx.shufflecake)</li>
    <li>linuxPackages_lqx.shufflecake.bin (linuxKernel.packages.linux_lqx.shufflecake.bin)</li>
    <li>linuxPackages_lqx.system76-io (linuxKernel.packages.linux_lqx.system76-io)</li>
    <li>linuxPackages_lqx.systemtap (linuxKernel.packages.linux_lqx.systemtap)</li>
    <li>linuxPackages_lqx.tp_smapi (linuxKernel.packages.linux_lqx.tp_smapi)</li>
    <li>linuxPackages_lqx.trelay (linuxKernel.packages.linux_lqx.trelay)</li>
    <li>linuxPackages_lqx.tuxedo-drivers (linuxKernel.packages.linux_lqx.tuxedo-drivers)</li>
    <li>linuxPackages_lqx.v4l2loopback (linuxKernel.packages.linux_lqx.v4l2loopback)</li>
    <li>linuxPackages_lqx.v4l2loopback.bin (linuxKernel.packages.linux_lqx.v4l2loopback.bin)</li>
    <li>linuxPackages_lqx.v86d (linuxKernel.packages.linux_lqx.v86d)</li>
    <li>linuxPackages_lqx.vhba (linuxKernel.packages.linux_lqx.vhba)</li>
    <li>linuxPackages_lqx.virtio_vmmci (linuxKernel.packages.linux_lqx.virtio_vmmci)</li>
    <li>linuxPackages_lqx.virtualbox (linuxKernel.packages.linux_lqx.virtualbox)</li>
    <li>linuxPackages_lqx.virtualboxGuestAdditions (linuxKernel.packages.linux_lqx.virtualboxGuestAdditions)</li>
    <li>linuxPackages_lqx.vmm_clock (linuxKernel.packages.linux_lqx.vmm_clock)</li>
    <li>linuxPackages_lqx.vmware (linuxKernel.packages.linux_lqx.vmware)</li>
    <li>linuxPackages_lqx.xone (linuxKernel.packages.linux_lqx.xone)</li>
    <li>linuxPackages_lqx.xpadneo (linuxKernel.packages.linux_lqx.xpadneo)</li>
    <li>linuxPackages_lqx.zenergy (linuxKernel.packages.linux_lqx.zenergy)</li>
    <li>linuxPackages_lqx.zenpower (linuxKernel.packages.linux_lqx.zenpower)</li>
    <li>linuxPackages_lqx.zfs (linuxKernel.packages.linux_lqx.zfs ,linuxPackages_lqx.zfs_2_2)</li>
    <li>linuxPackages_lqx.zfs_unstable (linuxKernel.packages.linux_lqx.zfs_unstable)</li>
  </ul>
</details>

**Review by GGG-KILLER — APPROVED** [review]
Fixes the issue I was having and other issues don't seem to be related.
Thank you very much!

**Pull request merged**
