### PR TITLE
iproute2: Dont hardcode gcc

### PR DESCRIPTION
**Pull request by Artturin**
`nix build --impure --expr 'with import ./. { config = { replaceStdenv = ({ pkgs }: pkgs.clangStdenv); }; }; kexec-tools'`## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Seems to have broken cross:

```
aarch64-unknown-linux-gnu-gcc  -I../include -o maketable maketable.c -lm
aarch64-unknown-linux-gnu-gcc  -I../include -o normal normal.c -lm
aarch64-unknown-linux-gnu-gcc  -I../include -o pareto pareto.c -lm
aarch64-unknown-linux-gnu-gcc  -I../include -o paretonormal paretonormal.c -lm
./normal > normal.dist
./pareto > pareto.dist
/nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/bash: line 1: ./normal: cannot execute binary file: Exec format error
make[1]: *** [Makefile:17: normal.dist] Error 126
make[1]: *** Waiting for unfinished jobs....
/nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/bash: line 1: ./pareto: cannot execute binary file: Exec format error
make[1]: *** [Makefile:17: pareto.dist] Error 126
make: *** [Makefile:76: all] Error 2
```

**Comment by Artturin** [comment]
> Seems to have broken cross:
> 
> ```
> aarch64-unknown-linux-gnu-gcc  -I../include -o maketable maketable.c -lm
> aarch64-unknown-linux-gnu-gcc  -I../include -o normal normal.c -lm
> aarch64-unknown-linux-gnu-gcc  -I../include -o pareto pareto.c -lm
> aarch64-unknown-linux-gnu-gcc  -I../include -o paretonormal paretonormal.c -lm
> ./normal > normal.dist
> ./pareto > pareto.dist
> /nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/bash: line 1: ./normal: cannot execute binary file: Exec format error
> make[1]: *** [Makefile:17: normal.dist] Error 126
> make[1]: *** Waiting for unfinished jobs....
> /nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/bash: line 1: ./pareto: cannot execute binary file: Exec format error
> make[1]: *** [Makefile:17: pareto.dist] Error 126
> make: *** [Makefile:76: all] Error 2
> ```

both
```
pkgsCross.aarch64-multiplatform.kexec-tools
pkgsCross.aarch64-multiplatform.iproute2
```
build

**Comment by Artturin** [comment]
ah the change is not in master yet

**Comment by Artturin** [comment]
```
CC ?= aarch64-unknown-linux-gnu-gcc
HOSTCC ?= $(CC)
```
I do wonder how it used to know to use the cross compiler

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/253854/commits/e270be8f44a36a24be946107479c8b2f1bfcc082

**Pull request merged**
