### PR TITLE
puppy: init at 0.0.7

### PR DESCRIPTION
**Pull request by 9999years**
Adds @eiais' [puppy](https://github.com/eiais/puppy.rs/) program to nixpkgs.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] ~~Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~~ N/A
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] ~~Determined the impact on package closure size (by running `nix path-info -S` before and after)~~
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by eiais — APPROVED** [review]
thanks for upstreaming this!

**Comment by 9999years** [comment]
Mind merging?

**Comment by neonfuz** [comment]
Not to be discouraging, but upstream doesn't even have a readme. What does this program do? Why would somebody want this program? The only documentation I see is your description string saying it's like fortune. Linux distros need some quality control, they can't accept every little program in existence. I'm not a nixpkgs maintainer so I can't merge or choose not to, but I suggest at least adding a readme to upstream so people can know why they would want this package.

**Comment by SuperSandro2000** [comment]
Upstream project got deleted.

**Pull request closed without merging**
