### PR TITLE
nixos/ausweisapp: init module with firewall option

### PR DESCRIPTION
**Pull request by wamserma**
###### Motivation for this change

Optional functionality of AusweisApp2 requires an UDP port to be opened.
The module allows for convenient configuration and serves as documentation.
See also https://github.com/NixOS/nixpkgs/issues/136269

Addition to release notes was omitted as this is only a trivial module.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wnklmnn — APPROVED** [review]

**Comment by wamserma** [comment]
ping @SuperSandro2000 can you have a look & merge?

**Review by Shawn8901 — APPROVED** [review]
lgfm.
works without any issue and i dont see any open change requests, it there something blocking this for being merged?

**Comment by mweinelt** [comment]
Requires a changelog entry for the added module, looks good to me otherwise.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by wamserma** [comment]
@SuperSandro2000 Thanks for taking care of the Changelog entries.

**Pull request merged**
