### PR TITLE
terraform-provider-kafka: init at v0.2.12

### PR DESCRIPTION
**Pull request by rguevara84**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build terraform.full

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111301` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>terraform-full</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>terraform-providers.kafka: log <a href="https://termbin.com/wvsu">https://termbin.com/wvsu</a></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111301` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>terraform-full: log was empty</li>
<li>terraform-providers.kafka: log <a href="https://termbin.com/6hei">https://termbin.com/6hei</a></li>
  </ul>
</details>

**Comment by rguevara84** [comment]
What's the process for this case where the vendor files are missing, locally I had to run `go mod vendor`, I see there is an option for go modules to force the dependencies to be downloaded, but that kind of applies to all providers, how can I enable that flag just for a single provider. https://nixos.org/manual/nixpkgs/stable/#ex-buildGoModule
`runVend = true;`

**Comment by timstott** [comment]
@rguevara84 You may override attributes for a specific provider as it is done with `acme`, see

https://github.com/nixos/nixpkgs/blob/993bbf7581527a8be13713e34d495127a9fc88d9/pkgs/applications/networking/cluster/terraform-providers/default.nix#L48-L54

**Comment by rguevara84** [comment]
what attribute should I override? I tried 
```
kafka = automated-providers.kafka.overrideAttrs (attrs: {
      deleteVendor = true;
      runVend = true;
    });
```
Aren't those at the same level as prepatch, postBuild, and friends attributes?
While debugging the build I can see some attributes but not the ones I'm looking for, is any of those equivalent to `deleteVendor` and `runVend` ?
Any advice I'm kind of lost here :_( 
```
processing attribute 'allowSubstitutes'
processing attribute 'args'
processing attribute 'buildCommand'
processing attribute 'buildInputs'
processing attribute 'builder'
processing attribute 'configureFlags'
processing attribute 'depsBuildBuild'
processing attribute 'depsBuildBuildPropagated'
processing attribute 'depsBuildTarget'
processing attribute 'depsBuildTargetPropagated'
processing attribute 'depsHostHost'
processing attribute 'depsHostHostPropagated'
processing attribute 'depsTargetTarget'
processing attribute 'depsTargetTargetPropagated'
processing attribute 'doCheck'
processing attribute 'doInstallCheck'
processing attribute 'executable'
processing attribute 'name'
processing attribute 'nativeBuildInputs'
processing attribute 'outputs'
processing attribute 'passAsFile'
processing attribute 'patches'
processing attribute 'preferLocalBuild'
processing attribute 'propagatedBuildInputs'
processing attribute 'propagatedNativeBuildInputs'
processing attribute 'stdenv'
processing attribute 'strictDeps'
processing attribute 'system'
processing attribute 'text'
processing attribute 'CGO_ENABLED'
processing attribute 'GO111MODULE'
processing attribute 'GO386'
processing attribute 'GOARCH'
processing attribute 'GOARM'
processing attribute 'GOFLAGS'
processing attribute 'GOHOSTARCH'
processing attribute 'GOHOSTOS'
processing attribute 'GOOS'
processing attribute 'args'
processing attribute 'buildInputs'
processing attribute 'buildPhase'
processing attribute 'builder'
processing attribute 'checkPhase'
processing attribute 'configureFlags'
processing attribute 'configurePhase'
processing attribute 'depsBuildBuild'
processing attribute 'depsBuildBuildPropagated'
processing attribute 'depsBuildTarget'
processing attribute 'depsBuildTargetPropagated'
processing attribute 'depsHostHost'
processing attribute 'depsHostHostPropagated'
processing attribute 'depsTargetTarget'
processing attribute 'depsTargetTargetPropagated'
processing attribute 'disallowedReferences'
processing attribute 'doCheck'
processing attribute 'doInstallCheck'
processing attribute 'enableParallelBuilding'
processing attribute 'enableParallelChecking'
processing attribute 'goPackagePath'
processing attribute 'installPhase'
processing attribute 'name'
processing attribute 'nativeBuildInputs'
processing attribute 'outputs'
processing attribute 'patches'
processing attribute 'pname'
processing attribute 'postBuild'
processing attribute 'propagatedBuildInputs'
processing attribute 'propagatedNativeBuildInputs'
processing attribute 'renameImports'
processing attribute 'shellHook'
processing attribute 'src'
processing attribute 'SSL_CERT_FILE'
processing attribute 'args'
processing attribute 'buildInputs'
processing attribute 'builder'
processing attribute 'configureFlags'
processing attribute 'curlOpts'
processing attribute 'depsBuildBuild'
processing attribute 'depsBuildBuildPropagated'
processing attribute 'depsBuildTarget'
processing attribute 'depsBuildTargetPropagated'
processing attribute 'depsHostHost'
processing attribute 'depsHostHostPropagated'
processing attribute 'depsTargetTarget'
processing attribute 'depsTargetTargetPropagated'
processing attribute 'doCheck'
processing attribute 'doInstallCheck'
processing attribute 'downloadToTemp'
processing attribute 'executable'
processing attribute 'impureEnvVars'
processing attribute 'mirrorsFile'
processing attribute 'name'
processing attribute 'nativeBuildInputs'
processing attribute 'nixpkgsVersion'
processing attribute 'outputHash'
processing attribute 'outputHashAlgo'
processing attribute 'outputHashMode'
processing attribute 'outputs'
processing attribute 'patches'
processing attribute 'postFetch'
processing attribute 'postHook'
processing attribute 'preferHashedMirrors'
processing attribute 'preferLocalBuild'
processing attribute 'propagatedBuildInputs'
processing attribute 'propagatedNativeBuildInputs'
processing attribute 'showURLs'
processing attribute 'stdenv'
processing attribute 'strictDeps'
processing attribute 'system'
processing attribute 'urls'
processing attribute 'userHook'
```

**Comment by kalbasit** [comment]
@rguevara84 not sure if you can override these attributes. I think that you'll have to add it as a custom package or add support for passing these attributes in the json.

**Comment by timstott** [comment]
@rguevara84 Sorry for pointing you in the wrong direction. I thought we could override these attribute but as @kalbasit points out, and having looked at the [Go module builder](https://github.com/nixos/nixpkgs/tree/993bbf7581527a8be13713e34d495127a9fc88d9/pkgs/development/go-modules/generic/default.nix) source, it doesn't seem to be the case.

Providing support to these attributes in the JSON would be nice as I'm sure other providers will have this issue. You will have to update the function to accept the attributes [here](https://github.com/nixos/nixpkgs/blob/993bbf7581527a8be13713e34d495127a9fc88d9/pkgs/applications/networking/cluster/terraform-providers/default.nix#L19), and their default value [here](https://github.com/nixos/nixpkgs/blob/993bbf7581527a8be13713e34d495127a9fc88d9/pkgs/development/go-modules/generic/default.nix#L21-L25).

**Comment by rguevara84** [comment]
@GrahamcOfBorg build terraform.full

**Review by kalbasit — APPROVED** [review]

**Pull request merged**
