### PR TITLE
kube3d 1.7.0 -> 3.0.0

### PR DESCRIPTION
**Pull request by blaggacao**
As [small-big](https://github.com/rancher/k3d/releases/tag/v3.0.0) step.

### CODE REVIEW

**Comment by blaggacao** [comment]
\marvin opt-in

**Comment by blaggacao** [comment]
Result of `nixpkgs-review pr 93680` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- kube3d
</details>

**Comment by blaggacao** [comment]
```console
[nix-shell:~/.cache/nixpkgs-review/pr-93680-1]$ ./results/kube3d/bin/k3d --helphttps://k3d.io/
k3d is a wrapper CLI that helps you to easily create k3s clusters inside docker.
Nodes of a k3d cluster are docker containers running a k3s image.
All Nodes of a k3d cluster are part of the same docker network.

Usage:
  k3d [flags]
  k3d [command]

Available Commands:
  cluster     Manage cluster(s)
  completion  Generate completion scripts for [bash, zsh, powershell | psh]
  help        Help about any command
  image       Handle container images.
  kubeconfig  Manage kubeconfig(s)
  node        Manage node(s)
  version     Show k3d and default k3s version

Flags:
  -h, --help      help for k3d
      --verbose   Enable verbose output (debug logging)
      --version   Show k3d and default k3s version

Use "k3d [command] --help" for more information about a command.
```

**Comment by blaggacao** [comment]
Validated `k3d --version` is set (introduced `v3` suffice to the module path)

**Comment by blaggacao** [comment]
- [x] `k3d cluster create` successfully creates a cluster

**Review by kuznero — APPROVED** [review]
LGTM

**Comment by blaggacao** [comment]
Skaffold has an optional dependency on k3d. Yesterday compatibility with k3d v3 was merged and will be the only supported version going forward, so ahortly after skaffold cuts a releas I'll update skaffold as well.

**Comment by blaggacao** [comment]
Could we merge this?

**Review by jlesquembre — APPROVED** [review]

**Comment by jlesquembre** [comment]
LGTM!

**Comment by timokau** [comment]
You probably want to set your PR to `needs_reviewer` after opting-in @blaggacao :) That way you could theoretically get an assigned reviewer (though there currently aren't enough of those).

**Comment by timokau** [comment]
Thanks @blaggacao @jlesquembre!

**Pull request merged**
