### PR TITLE
bazel_6: 6.4.0 -> 6.5.0

### LINKED ISSUE #273500: bazel_6: `MODULE.bazel.lock` file is empty
### Describe the bug
Using Bazel from nixpkgs in a project with bzlmod enabled, and `--lockfile_mode=update` the generated `MODULE.bazel.lock` file does only contain an empty JSON object.

### Steps To Reproduce
1. `git clone https://github.com/bazelbuild/examples.git`
2. `cd examples/bzlmod/01-depend_on_bazel_module`
3. `rm .bazelversion`
4. `nix run nixpkgs#bazel_6 -- mod deps --lockfile_mode=update`

```console
$ nix run nixpkgs#bazel_6 version
Build label: 6.4.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
$ ls -lh MODULE.bazel.lock
-rw-r--r-- 1 claudio users 3 Dec 11 09:02 MODULE.bazel.lock
$ head MODULE.bazel.lock
{}
```

### Expected behavior

The generated lock file should be equivalent to the file generated by a vanilla Bazel distribution binary:
```console
$ bazel version
Bazelisk version: v1.16.0
Starting local Bazel server and connecting to it...
Build label: 6.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 17:07:43 2023 (1697735263)
Build timestamp: 1697735263
Build timestamp as int: 1697735263
$  bazel mod deps --lockfile_mode=update
<root> (example@0.0.1)

 checking cached actions
$ ls -lh ls -lh MODULE.bazel.lock 
-rw-r--r-- 1 root root 75K Dec 11 08:07 MODULE.bazel.lock
$ head MODULE.bazel.lock
{
  "lockFileVersion": 3,
  "moduleFileHash": "47f831d13c88b71ebfb233245e6e8c208f8d2e09b51e780699178a31ccf165dd",
  "flags": {
    "cmdRegistries": [
      "https://bcr.bazel.build/"
    ],
    "cmdModuleOverrides": {},
    "allowedYankedVersions": [],
    "envVarAllowedYankedVersions": "",
```

### Additional context

See also https://github.com/bazelbuild/bazel/issues/19672 where the same problem was reported for Bazel from homebrew.

The formula from homebrew is here:
https://github.com/Homebrew/homebrew-core/blob/fda88ddb4c8ea04adcfa001c56a1b35aebd64e86/Formula/b/bazel.rb

### Notify maintainers

@NixOS/bazel 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20231128.7c4c205`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-21.11.336182.a25df4c2b79"`
 - nixpkgs: `/etc/nixpkgs`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by avdv**
## Description of changes

Upgrades to the latest 6.x release. Fixes #273500

- bazel_6: 6.4.0 -> 6.5.0
- bazel_6: Add check to assert GSON serialization works

https://github.com/bazelbuild/bazel/releases/tag/6.5.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by avdv** [comment]
@ofborg build envoy python3Packages.jaxlib  python3Packages.jaxlibWithCuda python3Packages.tensorflow-probability

**Comment by avdv** [comment]
This is almost ready, but unfortunately tests fail for Darwin. If somebody could have a look there, that would be great.

**Comment by avdv** [comment]
Now, the builds on Darwin aarch64 and x86_64 are failing as follows, respectively:
```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/9jda53vr01g2ma3kp0n46cn4m9s8gsh8-append-initrd-secrets.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```
```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/rsjmz848mv48kil2s92vnzy4n7q53rcz-builder.pl.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```
What gives? Especially that for the x86_64-darwin build, the error mentions that it actually is an aarch64 machine is quite a bit surprising. But at least this would explain Bazel test failures I have seen before where it would fail because it was looking for a cc-compiler-darwin-aarch64 but the local-config-cc only configured a cc toolchain for x86-64_darwin...

**Review by marsam — APPROVED** [review]

**Comment by vcunat** [comment]
FYI, [review tools](https://malob.github.io/nix-review-tools-reports/) say that many builds regressed due to this merge with log like
https://hydra.nixos.org/build/257642087/nixlog/5/tail

**Comment by avdv** [comment]
> FYI, [review tools](https://malob.github.io/nix-review-tools-reports/) say that many builds regressed due to this merge with log like [hydra.nixos.org/build/257642087/nixlog/5/tail](https://hydra.nixos.org/build/257642087/nixlog/5/tail)

I have created a PR to fix that: https://github.com/NixOS/nixpkgs/pull/306940

**Comment by samuela** [comment]
Hi folks, this PR broke `python3Packages.jaxlib` and consequnetly the rest of the JAX ecosystem. Could you please patch jaxlib or revert this?

**Pull request merged**
