### PR TITLE
uiua: 0.13.0 -> 0.14.0-dev.5

### PR DESCRIPTION
**Pull request by amatgil**
## Description
[uiua-lang/uiua 0.13.0 -> 0.14.0-dev.5](https://github.com/uiua-lang/uiua/compare/0.13.0...0.14.0-dev.5)
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TomaSajt** [comment]
While I agree that the new features are useful, the `-dev` versions are coming out so fast that by the time it gets cached on master a new version is already out.
Also, many new symbols added in a `-dev` version get removed by the time there's a stable version.

My personal opinion is that you should just override your local uiua version until a stable release.

I probably won't merge it, but I won't stop others from deciding to do it, though.

**Comment by cafkafk** [comment]
> While I agree that the new features are useful, the `-dev` versions are coming out so fast that by the time it gets cached on master a new version is already out. Also, many new symbols added in a `-dev` version get removed by the time there's a stable version.
> 
> My personal opinion is that you should just override your local uiua version until a stable release.
> 
> I probably won't merge it, but I won't stop others from deciding to do it, though.

I agree, this shouldn't be merged, but if someone wanted to make an `uiua-unstable` package I'd probably support it, as long as we always have a stable version.

**Review by cafkafk — CHANGES_REQUESTED** [review]
> While I agree that the new features are useful, the `-dev` versions are coming out so fast that by the time it gets cached on master a new version is already out. Also, many new symbols added in a `-dev` version get removed by the time there's a stable version.
> 
> My personal opinion is that you should just override your local uiua version until a stable release.
> 
> I probably won't merge it, but I won't stop others from deciding to do it, though.

I agree, this shouldn't be merged, but if someone wanted to make an `uiua-unstable` package I'd probably support it, as long as we always have a stable version.

**Comment by Defelo** [comment]
closing since #362951 has been merged

**Pull request closed without merging**
