### PR TITLE
nixos/sourcehut: refactor according to coding standards

### PR DESCRIPTION
**Pull request by nessdoor**
## Description of changes
Just a light refactor aimed at:
- removing the lingering `with lib;` expressions, which are the target of a tree-wide refactoring campaign (see #208242);
- enforcing the coding standards mandated by `nixpkgs-fmt`.

Consider this a prerequisite for more profound and thoughtful refactoring to come in the near future, as this module is bound to be modified following the discussion in #245394.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by christoph-heiss — APPROVED** [review]
LGTM. 

AFAICS this really just replaces the `with lib;` with appropriate scoped `inherit`s, and otherwise only contains mechanical whitespace changes using `nixpkgs-fmt`. 

Also ran `nix-build -A nixosTests.sourcehut` to be sure; no changes there either.

**Review by AndersonTorres — DISMISSED** [review]
Ping me after 24h to merge.

**Comment by AndersonTorres** [comment]
@nessdoor please rebase

**Review by christoph-heiss — APPROVED** [review]

**Comment by nessdoor** [comment]
@AndersonTorres sorry for coming back after all this time, but: is it me or the first commit of this PR didn't get merged?

**Comment by AndersonTorres** [comment]
Why? There is no "partial merge" on github interface...

**Comment by nessdoor** [comment]
Sure, actually it was _my_ bad, sorry. Just noticed that the reformatting of an **entire file** (`default.nix`) went missing after the forced push. I noticed only now because the auto-formatter triggered while rebasing some other changes...

Sorry to have troubled you, I will amend my mistake in the future.

**Comment by tomberek** [comment]
@nessdoor @AndersonTorres thank you both for the continued maintenance.

**Pull request merged**
