### PR TITLE
pythonPackages.pycodestyle: improve tests

### PR DESCRIPTION
**Pull request by kamadorueda**
- This commit adjust the tests to the ones that are found in the
  tox.ini file for the specified version of the module
- This means we'll have 3 tests in adition to the default one

###### Motivation for this change

found it while doing other things and wanted to contribute it

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
over 5000 rebuilds, please target staging branch

**Comment by kamadorueda** [comment]
> over 5000 rebuilds, please target staging branch

is it `r'^staging$'` branch ? there are many `r'^staging.*$'` branches

**Comment by jonringer** [comment]
correct, `staging` is what you want. The other's are in case there's need for a "workspace" for stabilizing packages on a given release channel

**Comment by lovesegfault** [comment]
You need to rebase and filter out all this stuff you picked up when changing the base on GH

**Comment by kamadorueda** [comment]
> You need to rebase and filter out all this stuff you picked up when changing the base on GH

thanks, I've rebased and force-pushed the branch

**Comment by jonringer** [comment]
@GrahamcOfBorg build pythonPackages.pycodestyle 
@GrahamcOfBorg build python35Packages.pycodestyle  
@GrahamcOfBorg build python36Packages.pycodestyle  
@GrahamcOfBorg build python37Packages.pycodestyle 
@GrahamcOfBorg build python38Packages.pycodestyle 
@GrahamcOfBorg build python39Packages.pycodestyle

**Comment by kamadorueda** [comment]
what is to do next in order to have it in master ?

**Comment by jonringer** [comment]
wait.

staging is to collect many packages which introduce large changes, then it goes to a branch in staging-next where stabilization occurs (fixing issues), once stable enough, it gets merged into master

**Pull request merged**
