### PR TITLE
[staging] perlPackages.CatalystXScriptServerStarman: fix build

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

fix build

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.CatalystXScriptServerStarman

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by volth** [comment]
@GrahamcOfBorg build nix-serve

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by rycee** [comment]
Tried a few builds and this patch seems to work fine. Thanks for the quick fix!

**Pull request merged**
