### PR TITLE
spotdl: 4.1.10 -> 4.1.11

### LINKED ISSUE #239733: Build failure: nixos-23.05 -> spotdl
### Steps To Reproduce

https://hydra.nixos.org/job/nixos/release-23.05/nixpkgs.spotdl.x86_64-linux

Failure happens locally as well when trying to build spotdl on the nixos-23.05 branch.

### Logs:

this the tail of the log:
```
=========================== short test summary info ============================
FAILED tests/providers/audio/test_youtube.py::test_yt_search - spotdl.providers.audio.base.AudioProviderError: YT-DLP download error - htt...
=========== 1 failed, 49 passed, 14 deselected, 5 warnings in 8.88s ============
/nix/store/5wdlffjhcr4i43sfajxcvx3lvnkryh5y-stdenv-linux/setup: line 1604: pop_var_context: head of shell_variables not a function context
```
The last line is apparently unrelated:
https://github.com/NixOS/nixpkgs/issues/214822

### Notify maintainers

@dotlambda (maintainer) @fabaff (recent bumps)

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/spotDL/spotify-downloader/compare/refs/tags/v4.1.10...v4.1.11

Changelog: https://github.com/spotDL/spotify-downloader/releases/tag/v4.1.10

###### Description of changes
Fix build (https://hydra.nixos.org/build/225101216)

Fixes #239733

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
@ofborg build spotdl

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 239813` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>spotdl</li>
    <li>spotdl.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
@ofborg build yt-dlp

**Review by ckiee — APPROVED** [review]
Builds x86_64-linux with nixpkgs-review here too, ffmpeg reads .mp3 out, all is happy. Merging.

Thank you (:

**Comment by maralorn** [comment]
Thank you!

**Pull request merged**
