### PR TITLE
flameshot: 0.9.0 -> 0.10.0

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130631` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flameshot</li>
  </ul>
</details>

**Comment by chuahou** [comment]
Should this be backported to 21.05 given at least one critical bug (https://github.com/flameshot-org/flameshot/issues/1730) present in 0.9.0 (the current version in nixos-21.05) that is fixed in 0.10.0 (the current nixpkgs-unstable version)?

If yes, is it possible to use the "backport release-21.05" label or should I [manually file such a PR](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes)?

**Comment by rhoriguchi** [comment]
> Should this be backported to 21.05 given at least one critical bug ([flameshot-org/flameshot#1730](https://github.com/flameshot-org/flameshot/issues/1730)) present in 0.9.0 (the current version in nixos-21.05) that is fixed in 0.10.0 (the current nixpkgs-unstable version)?
> 
> If yes, is it possible to use the "backport release-21.05" label or should I [manually file such a PR](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes)?

Does the bug exist in [0.6.0](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/tools/misc/flameshot/default.nix#L10)?

**Comment by chuahou** [comment]
> Does the bug exist in [0.6.0](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/tools/misc/flameshot/default.nix#L10)?

Just grabbed 0.6.0 from nixos-20.09, and nope, the bug I linked earlier does not occur there.

**Comment by rhoriguchi** [comment]
> Just grabbed 0.6.0 from nixos-20.09, and nope, the bug I linked earlier does not occur there.

Good to hear, so I guess a backport is not necessary.

**Pull request merged**
