### PR TITLE
nixos/hardware/printers: fix empty ppdOptions

### PR DESCRIPTION
**Pull request by rhoriguchi**
## Description of changes

When not setting `ppdOptions` you get a dangling `\` which makes the command fail
https://github.com/NixOS/nixpkgs/blob/b98a4e1746acceb92c509bc496ef3d0e5ad8d4aa/nixos/modules/hardware/printers.nix#L9-L16

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rnhmjoj** [comment]
This is already an improvement, but the command can still break if any of the values contain single quotes.
I think the proper way to handle this would be to wrap everything in `lib.escapeShellArg`, or perhaps building the command using `lib.cli.toGNUCommandLine`.

**Comment by rhoriguchi** [comment]
> This is already an improvement, but the command can still break if any of the values contain single quotes. I think the proper way to handle this would be to wrap everything in `lib.escapeShellArg`, or perhaps building the command using `lib.cli.toGNUCommandLine`.

Thank you for the info `lib.cli.toGNUCommandLineShell` works great.

**Comment by rnhmjoj** [comment]
It looks fine but for some reason `nixosTests.printing-service` is failing after your change.
I compared the previous and current ensure-printers.service file and the only reason I can think of is that the arguments of `lpadmin` are in a different order. This normally shouldn't matter, though.

**Comment by rnhmjoj** [comment]
> -E   When specified before the -d, -p, or -x options, forces the use of TLS
> encryption on the connection to the scheduler. Otherwise, enables the
> destination and accepts jobs; this is the same as running the cupsaccept(8)
> and cupsenable(8) programs on the destination.

**Review by rnhmjoj — CHANGES_REQUESTED** [review]

**Comment by rhoriguchi** [comment]
> > -E   When specified before the -d, -p, or -x options, forces the use of TLS
> > encryption on the connection to the scheduler. Otherwise, enables the
> > destination and accepts jobs; this is the same as running the cupsaccept(8)
> > and cupsenable(8) programs on the destination.
> > The double meaning of the -E option is an unfortunate historical oddity.

Nice find, thank you for the help.

**Comment by rnhmjoj** [comment]
@grahamcOfBorg test printing-service

**Review by rnhmjoj — APPROVED** [review]
All clear. Thank you!

**Pull request merged**
