### PR TITLE
nixos/libinput: update horizontalScrolling description

### LINKED ISSUE #54449: libinput.horizontalscrolling has incorrect description
https://github.com/NixOS/nixpkgs/blob/c076bd22338f1c31ee09fb8b4123407ee14337e8/nixos/modules/services/x11/hardware/libinput.nix#L134

should be **enables** horizontal scrolling

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Description of changes

Fixes #54449.

### CODE REVIEW

**Review by jian-lin — COMMENTED** [review]
FYI, the old description just follows `man libinput`.

**Comment by SuperSamus** [comment]
Should this PR be closed, then?
(And the issue linked too)

**Comment by jian-lin** [comment]
The old description is indeed a bit confusing.

> Should this PR be closed, then?

I do not have a strong opinion on this.  Lets see what others say.

**Comment by SuperSamus** [comment]
The description was updated upstream.
https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/commit/dfc5e204268473b89c1b93075595182750fe4bea

**Review by jian-lin — APPROVED** [review]
Could you change your commit message to `nixos/libinput: ...`?

**Pull request merged**
