### PR TITLE
meson: fix unknown compiler error

### LINKED ISSUE #73417: meson builds failing on i686-linux
**Describe the bug**
The channel is currently blocked on the i686-linux minimal ISO not building.
https://hydra.nixos.org/build/106718862

It's both failing at `xorg.xorgproto` and `gtk-doc`

Both of these packages use the meson build system and produce a similar output on failure
```
Project name: xorgproto
Project version: 2019.1

meson.build:21:0: ERROR: Unknown compiler(s): [['/nix/store/38rh09iclvs97fisbgy8fg6wxr33ijr1-gcc-wrapper-8.3.0/bin/cc']]
```

```
Project name: gtk-doc
Project version: 1.32

meson.build:1:0: ERROR: Unknown compiler(s): [['/nix/store/38rh09iclvs97fisbgy8fg6wxr33ijr1-gcc-wrapper-8.3.0/bin/cc']]
```

cc @jtojnar @Ericson2314 @matthewbauer 

---

It's another topic entirely if i686-linux should be able to block channels.
In my opinion, it's not at the same tier of support to be able to have a channel blocking job like this.

### PR DESCRIPTION
**Pull request by jtojnar**
Closes: https://github.com/NixOS/nixpkgs/issues/73417

### CODE REVIEW

**Comment by worldofpeace** [comment]
This blocks the channel, should we promote this change to merge to master?

While I don't really agree with the i686 minimal iso blocking the channel https://github.com/NixOS/nixpkgs/commit/93aa83deb4923a2362814d952495aeab3ec49288, I'm guessing we might also need to change nixos-channel-scripts.

**Review by worldofpeace — APPROVED** [review]
gtk-doc builds on i686-linux.
Also reviewed patch upstream, lgtm.

**Comment by jtojnar** [comment]
Probably. Will deal with the merge conflict later.

**Comment by worldofpeace** [comment]
Another thing is we don't even CI i686-linux. So we don't even check we're breaking things, while having this artifact being a channel blocker.

**Comment by FRidh** [comment]
Still having it as a channel blocker was kind of a trade-off. We did not really want to drop i686 entirely, but still have a minimum set of packages working. See https://github.com/NixOS/nixpkgs/pull/27923 and the references in it.

**Comment by FRidh** [comment]
That's over 2 years ago already. Maybe we can revisit it again. Somehow I think there is still a userbase for i686.

**Pull request merged**
