### PR TITLE
consul: 0.9.3 -> 1.0.6; also upgrade python-consul...

### PR DESCRIPTION
**Pull request by nh2**
... to a version that can handle Consul >= 1.0.

See https://github.com/NixOS/nixpkgs/pull/35602#issuecomment-368486246

Upgrading consul also requires upgrading the Ruby deps, see
https://github.com/NixOS/nixpkgs/pull/41239#issuecomment-393000879

Also add instructions on how to do that, and a small patch
to improve the error message when it is forgotten.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This is intended to replace and improve upon PRs #35602 and #41239.

First check with their corresponding authors that they agree, then merge this one.

### CODE REVIEW

**Comment by nh2** [comment]
Hmm I get an error with the `json` gem now. Hang on.

**Comment by xeji** [comment]
In addition, #41268 created some merge conflicts.

**Comment by xeji** [comment]
Closes #35602

**Comment by c0bw3b** [comment]
Closing in favor of #48714

**Pull request closed without merging**
