### PR TITLE
paper-icon-theme: 2017-02-13 -> 2017-11-20

### PR DESCRIPTION
**Pull request by romildo**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
@GrahamcOfBorg build paper-icon-theme

**Comment by Mic92** [comment]
@GrahamcOfBorg build paper-icon-theme

**Comment by Mic92** [comment]
Strange, is there some file name that is a victim of unicode normalisation on darwin?

**Comment by romildo** [comment]
I don't think so. I have recursively listed all file names and counted characters with code not in the range 0 to 127. The result is 0.

``` c
#include <stdio.h>

int main(void) {
   char c;
   int counter = 0;
   while ((c = getchar()) != EOF)
      if (c < 0 || c > 127)
         counter++;
   printf("total: %i\n", counter);
   return 0;
}

```

```
$ find | ./checkfilenames
total: 0
```

**Comment by Mic92** [comment]
Since this is a fixed input derivation, darwin should eventually be able to use the source fetched from cache

**Pull request merged**
