### PR TITLE
Set CMAKE_SYSTEM_* for cross compiling

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change
This sets some new variables in make-derivation for cross compiling with CMAKE. Here is the list:

- CMAKE_SYSTEM_NAME
- CMAKE_SYSTEM_PROCESSOR
- CMAKE_SYSTEM_VERSION
- CMAKE_HOST_SYSTEM_NAME
- CMAKE_HOST_SYSTEM_PROCESSOR
- CMAKE_HOST_SYSTEM_VERSION

To do this, we need to start keeping track of uname values, respectively:

- uname -s (stdenv.buildPlatform.uname.system)
- uname -p (stdenv.buildPlatform.uname.processor)
- uname -r (stdenv.buildPlatform.uname.release)

We don't really have a way to get the last one, so leave it null for now.

Also remove some old hacks setting CMAKE_SYSTEM_NAME ad-hoc. And also add some windows doubles (were strangely missing).

### CODE REVIEW

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build pkgs.pkgsCross.mingwW64.brotli

**Comment by matthewbauer** [comment]
@ericson2314 This avoids having to create a wrapper for Cmake and should work just as good... Does it look right to you?

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build pkgsCross.mingwW64.nix

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build pkgsCross.mingwW64.nix

**Comment by Ericson2314** [comment]
Awesome!! Small nit, the "doubles" changes can be tested in `lib/tests/systems.nix`

I was about to mention `lib/systems/for-meta.nix`, too, but turns out you are just cleaning up after my sloppiness! https://github.com/NixOS/nixpkgs/commit/d9a1800239620425ef3608487f87002b1a4d1437

CC @aneeshusa, let's use your nix-level hook for this next!

**Comment by Ericson2314** [comment]
Oh, even more awesome. Thanks @matthewbauer!

**Review by Ericson2314 — APPROVED** [review]

**Pull request merged**
