### PR TITLE
bcompare - 4.3.2.24472 -> 4.3.4.24657

### PR DESCRIPTION
**Pull request by CloudArtAdmins**
Current version's URL doesn't function currently.

###### Motivation for this change

Did a full build of packages and found this one. Just wanting to clean the build, basically.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ktor — APPROVED** [review]

**Comment by ktor** [comment]
I've only reviewed bcompare part.

**Comment by privateseabass** [comment]
Oh, hold on, that merge went in the wrong repository!

**Review by ktor — APPROVED** [review]
review OK

**Comment by ktor** [comment]
It should not only be merged to master but to 19.03 channel as well. How do we do that?

**Comment by ktor** [comment]
I've tested resulting binary in 20.03 and it works.

**Comment by ktor** [comment]
review OK

**Review by ktor — APPROVED** [review]

**Comment by Ekleog** [comment]
Squash-merged and backported to 20.03 at 42b96df6bdb84297f7dcf2d57084ec299fff80cf :)

Thank you both for the PR and the review!

**Pull request merged**
