### PR TITLE
protobuf: 3.17.3 -> 3.18.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://github.com/protocolbuffers/protobuf/releases/tag/v3.18.0
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 138091` at 5ea11a23 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>libnats-c</li>
    <li>linuxKernel.packages.hardkernel_4_14.sysdig</li>
    <li>linuxPackages_hardkernel_latest.sysdig</li>
    <li>odpdown</li>
    <li>termplay</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/578ba3f4782e7a0b4754a3b617a1c4cb">postgresqlPackages.cstore_fdw</a> (postgresql13Packages.cstore_fdw)</li>
    <li><a href="https://gist.github.com/a34496d0f430d98d65961f885c7d7a60">python38Packages.mypy-protobuf</a></li>
    <li><a href="https://gist.github.com/e648d7034ec1b6e24aef93db5269fe04">python39Packages.libarcus</a></li>
    <li><a href="https://gist.github.com/a105a1c7cb99ca708cf180105e7c25b2">python39Packages.mypy-protobuf</a></li>
  </ul>
</details>
<details>
  <summary>1208 packages skipped due to time constraints:</summary>
  <ul>
    <li>MIDIVisualizer</li>
    <li>adapta-gtk-theme</li>
    <li>alfis</li>
    <li>almanah</li>
    <li>amarok (amarok-kf5)</li>
    <li>anbox</li>
    <li>android-tools</li>
    <li>angelfish</li>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>30 packages built successfully:</summary>
  <ul>
    <li>charge-lnd</li>
    <li>grpc</li>
    <li>libphonenumber</li>
    <li>nanopb</li>
    <li>protobuf (protobuf3_18)</li>
    <li>protobufc</li>
    <li>python38Packages.google-cloud-audit-log</li>
    <li>python38Packages.googleapis-common-protos</li>
    <li>python38Packages.grpcio</li>
    <li>python38Packages.protobuf</li>
    <li>python38Packages.protobuf3-to-dict</li>
    <li>python38Packages.pycomfoconnect</li>
    <li>python38Packages.s2clientprotocol</li>
    <li>python38Packages.snakebite</li>
    <li>python39Packages.chainer</li>
    <li>python39Packages.google-cloud-audit-log</li>
    <li>python39Packages.googleapis-common-protos</li>
    <li>python39Packages.grpcio</li>
    <li>python39Packages.mysql-connector</li>
    <li>python39Packages.proto-plus</li>
    <li>python39Packages.protobuf</li>
    <li>python39Packages.protobuf3-to-dict</li>
    <li>python39Packages.pycomfoconnect</li>
    <li>python39Packages.python-axolotl</li>
    <li>python39Packages.s2clientprotocol</li>
    <li>python39Packages.snakebite</li>
    <li>python39Packages.tensorboard-plugin-profile</li>
    <li>quill</li>
    <li>riemann_c_client</li>
    <li>yara</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by trofi** [comment]
Looks like it broke `opencv` build in `staging`:

```
/build/source/modules/dnn/src/caffe/caffe_io.cpp: In function 'bool cv::dnn::ReadProtoFromBinary(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::Message*)':
/build/source/modules/dnn/src/caffe/caffe_io.cpp:1114:67: error: no matching function for call to 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit(const int&, int)'
 1114 |     coded_input.SetTotalBytesLimit(kProtoReadBytesLimit, 536870912);
      |                                                                   ^
```

**Comment by marsam** [comment]
@trofi sorry about that. It should be fixed by https://github.com/NixOS/nixpkgs/pull/138237

**Comment by trofi** [comment]
Another victim is `ddar` (in `master` this time): https://hydra.nixos.org/build/154341974

```
basic
  it_shows_usage_1:                                [FAIL]
     ddar -h
    Traceback (most recent call last):
      File "/nix/store/0rf53s4qk8avc99i77v04iwdg8x5qdyj-ddar-1.0/bin/.ddar-wrapped", line 21, in <module>
        import synctus.ddar_pb2, synctus.dds
      File "/nix/store/0rf53s4qk8avc99i77v04iwdg8x5qdyj-ddar-1.0/lib/python2.7/site-packages/synctus/ddar_pb2.py", line 5, in <module>
        from google.protobuf import descriptor as _descriptor
      File "/nix/store/3cy0bc77n9z0a92arsk1mdjkx9wyarij-python2.7-protobuf-3.18.0/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
        class DescriptorBase(metaclass=DescriptorMetaclass):
                                      ^
```

**Pull request merged**
