### PR TITLE
add mutt-kz: a fork of mutt with sidebar and notmuch support.

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by lethalman** [comment]
Can you cleanup those comments?

**Comment by magnetophon** [comment]
@lethalman :  done

**Comment by lethalman** [comment]
Sorry this PR can't be merged cleanly.

**Comment by lethalman** [comment]
Tried merging manually, indeed it does conflict on master. Try rebasing your changes on master.

**Comment by magnetophon** [comment]
Rebase done in: https://github.com/NixOS/nixpkgs/pull/6975

**Pull request closed without merging**
