### PR TITLE
nixos/ups: add envvars for interactive use

### PR DESCRIPTION
**Pull request by bjornfor**
## Description of changes

Set environment variables that fix running upsdrvctl interactively.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
Sure. It seems like this should be in the derivation for nut itself, but sure.

**Review by Majiir — APPROVED** [review]
> Sure.

My thought exactly. :smile: 

Out of curiosity, what does "running upsdrvctl interactively" look like?

**Comment by bjornfor** [comment]
> > Sure.
> 
> My thought exactly. 😄
> 
> Out of curiosity, what does "running upsdrvctl interactively" look like?

I'd paste the output, but I'm actually upgrading hardware tonight, so I don't have it readily available.

For example, see "Testing shutdown" from https://networkupstools.org/docs/user-manual.chunked/ar01s06.html. You'd run `upsdrvctl -t shutdown` and it logs what it'll do. Before this PR it would fail, after it succeeds.

**Comment by bjornfor** [comment]
> It seems like this should be in the derivation for nut itself, but sure.

Yes, that might be a good idea.

**Comment by bjornfor** [comment]
> Out of curiosity, what does "running upsdrvctl interactively" look like?

For example:

Before:

```
$ upsdrvctl -t shutdown
Network UPS Tools - UPS driver controller 2.8.2
*** Testing mode: not calling exec/kill/signal
   0.000000     [D2] 
If you're not a NUT core developer, chances are that you're told to enable debugging
to see why a driver isn't working for you. We're sorry for the confusion, but this is
the 'upsdrvctl' wrapper, not the driver you're interested in.

Below you'll find one or more lines starting with 'exec:' followed by an absolute
path to the driver binary and some command line option. This is what the driver
starts and you need to copy and paste that line and append the debug flags to that
line (less the 'exec:' prefix).

Alternately, provide an additional '-d' (lower-case) parameter to 'upsdrvctl' to
pass its current debug level to the launched driver, and '-B' keeps it backgrounded.

   0.000030     Can't open /nix/store/qbb38bmhb74qad66xarnh26wms6rfawr-nut-2.8.2/etc/ups.conf: Can't open /nix/store/qbb38bmhb74qad66xarnh26wms6rfawr-nut-2.8.2/etc/ups.conf: No such file or directory
   0.000034     [D1] Completed the job of upsdrvctl tool, cleaning up and exiting now
   0.000036     [D1] Completed the job of upsdrvctl tool, clean-up finished, exiting now
[...error exit code 1...]
```

After:

```
$ upsdrvctl -t shutdown
Network UPS Tools - UPS driver controller 2.8.2
*** Testing mode: not calling exec/kill/signal
   0.000000     [D2] 
If you're not a NUT core developer, chances are that you're told to enable debugging
to see why a driver isn't working for you. We're sorry for the confusion, but this is
the 'upsdrvctl' wrapper, not the driver you're interested in.

Below you'll find one or more lines starting with 'exec:' followed by an absolute
path to the driver binary and some command line option. This is what the driver
starts and you need to copy and paste that line and append the debug flags to that
line (less the 'exec:' prefix).

Alternately, provide an additional '-d' (lower-case) parameter to 'upsdrvctl' to
pass its current debug level to the launched driver, and '-B' keeps it backgrounded.

   0.000046     [D1] upsdrvctl commanding all drivers (1 found): (null)
   0.000049     [D1] Shutdown UPS: eaton3s
   0.000051     [D2] exec:  /nix/store/qbb38bmhb74qad66xarnh26wms6rfawr-nut-2.8.2/bin/usbhid-ups -a eaton3s -k
   0.000054     [D1] upsdrvctl: successfully finished
   0.000056     [D1] Completed the job of upsdrvctl tool, cleaning up and exiting now
   0.000059     [D1] Completed the job of upsdrvctl tool, clean-up finished, exiting now
[...successful exit code...]
```

**Pull request merged**
