### PR TITLE
oh-my-zsh: cleanups, don't require perl in pygmalion theme anymore

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
After switching to latest nixpkgs unstable, I ran into some error messages in my prompt:

```
prompt_setup_pygmalion:9: command not found: perl
prompt_setup_pygmalion:10: command not found: perl
perl: command not found  
```

This was due to https://github.com/NixOS/nixpkgs/pull/91213 removing `perl` from `$PATH`.

There's no reason `oh-my-zsh` needs to use perl for the regexp substitution, so I opened https://github.com/ohmyzsh/ohmyzsh/pull/9210 upstream, and fetch the patch here.

I did some cleanup in the `oh-my-zsh` derivation before, so patching is actually possible :-)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
@flokli Will this patch work with BSD/macOS `sed`? Not sure about `-eE` there...

**Comment by flokli** [comment]
There was another (preferrable IMHO) approach proposed in https://github.com/ohmyzsh/ohmyzsh/pull/9210#issuecomment-682890219, which doesn't need to shell out to anything anymore.

**Comment by flokli** [comment]
I pushed updated this PR with the proposed solution, if people want to tinker with it.

@NeQuissimus I'll leave it on you to decide on whether to merge this before it's merged upstream, or wait what happens there.

**Comment by scolobb** [comment]
Thank you @flokli for the PR.  I don't have any particular issues with it.

Upstream for Oh My Zsh seems to move quite quickly and this Nix package is automatically updated, so I'd say that applying the patch won't be necessary very soon.  Maybe add a TODO comment reminding to remove the patch application once your change is merged upstream.

**Review by scolobb — CHANGES_REQUESTED** [review]
Add a TODO comment reminding to remove the patch application once the change is merged upstream.

**Comment by flokli** [comment]
I updated the comment linking to the PR to become a TODO once this is merged.

**Review by scolobb — APPROVED** [review]

**Pull request merged**
