### PR TITLE
gnupg: remove warning printed on systems without procfs

### PR DESCRIPTION
**Pull request by veprbl**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rbreslow** [comment]
It looks like this has already been resolved in GnuPG 2.3.33: 

- https://dev.gnupg.org/rGbcd8f0239dfc36f99fbbb8ee309828ccee8974c0
- https://dev.gnupg.org/T5656

Is there anything stopping us from just bringing in this new version?

**Comment by veprbl** [comment]
> https://dev.gnupg.org/rGbcd8f0239dfc36f99fbbb8ee309828ccee8974c0

Yes, this is an upstreamed patch. Unfortunately diff files from phabricator have too much context to be applied.

**Comment by sequencer** [comment]
related to #151872, I'll close mine

**Comment by rbreslow** [comment]
> Yes, this is an upstreamed patch. Unfortunately diff files from phabricator have too much context to be applied.

Can you elaborate on this? It looks like that patch will make it into the 2.2.33 release of GnuPG. Is there something in the way of bumping the whole package to 2.2.33?

**Comment by veprbl** [comment]
> > Yes, this is an upstreamed patch. Unfortunately diff files from phabricator have too much context to be applied.
> 
> Can you elaborate on this? It looks like that patch will make it into the 2.2.33 release of GnuPG. Is there something in the way of bumping the whole package to 2.2.33?

Someone would need to submit a PR for that.

**Pull request merged**
