### PR TITLE
nixVersions.stable: 2.8.0 -> 2.9.0

### PR DESCRIPTION
**Pull request by Artturin**
https://github.com/NixOS/nix/blob/master/doc/manual/src/release-notes/rl-2.9.md

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
We should probably also bump nixUnstable

**Comment by Artturin** [comment]
> We should probably also bump nixUnstable

https://github.com/NixOS/nixpkgs/pull/175492

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 175541` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>nixui</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>colmena</li>
    <li>nix-doc</li>
    <li>nix-eval-jobs</li>
    <li>nix-plugins</li>
  </ul>
</details>
<details>
  <summary>59 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>comma</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.nvfetcher</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>libnixxml</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixVersions.nix_2_9 ,nixVersions.stable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixStatic</li>
    <li>nixos-generators</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>node2nix</li>
    <li>npins</li>
    <li>nuget-to-nix</li>
    <li>nvfetcher</li>
    <li>prefetch-yarn-deps</li>
    <li>python310Packages.nix-kernel</li>
    <li>python39Packages.nix-kernel</li>
    <li>rnix-lsp</li>
    <li>terranix</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>wp4nix</li>
    <li>yarn2nix</li>
  </ul>
</details>

```
error: builder for '/nix/store/dlc0mk3knwaa432aqrr34zr73yshv4la-nix-plugins-9.0.0.drv' failed with exit code 2;
       last 10 log lines:
       >                  from /nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix/primops.hh:3,
       >                  from /build/source/extra-builtins.cc:2:
       > /nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix/eval-inline.hh: In instantiation of 'void nix::EvalState::forceValue(nix::Value&, Callable) [with Callable = nix::Pos]':
       > /build/source/extra-builtins.cc:56:25:   required from here
       > /nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix/eval-inline.hh:106:30: error: no match for call to '(nix::Pos) ()'
       >   106 |         throwEvalError(getPos(), "infinite recursion encountered");
       >       |                        ~~~~~~^~
       > make[2]: *** [CMakeFiles/nix-extra-builtins.dir/build.make:76: CMakeFiles/nix-extra-builtins.dir/extra-builtins.cc.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/nix-extra-builtins.dir/all] Error 2
       > make: *** [Makefile:136: all] Error 2
       For full logs, run 'nix log /nix/store/dlc0mk3knwaa432aqrr34zr73yshv4la-nix-plugins-9.0.0.drv'.
error: builder for '/nix/store/rl8sc0r4gfxhfkm84ghccw53kp92ridi-nix-eval-jobs-0.0.6.drv' failed with exit code 1;
       last 10 log lines:
       > In file included from /nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix/eval.hh:3,
       >                  from ../src/nix-eval-jobs.cc:8:
       > /nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix/attr-set.hh:98:31: note: candidate: 'std::vector<const nix::Attr*> nix::Bindings::lexicographicOrder(const nix::SymbolTable&) const'
       >    98 |     std::vector<const Attr *> lexicographicOrder(const SymbolTable & symbols) const
       >       |                               ^~~~~~~~~~~~~~~~~~
       > /nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix/attr-set.hh:98:31: note:   candidate expects 1 argument, 0 provided
       > ../src/nix-eval-jobs.cc:297:66: error: no match for 'operator*' (operand type is 'nix::PosIdx')
       >   297 |                         recurse = state.forceBool(*attrv->value, *attrv->pos);
       >       |                                                                  ^~~~~~~~~~~
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/rl8sc0r4gfxhfkm84ghccw53kp92ridi-nix-eval-jobs-0.0.6.drv'.
error: 1 dependencies of derivation '/nix/store/s8s7lkfw3b7km23p46v82l92zn79ssgp-colmena-0.3.0.drv' failed to build
error: builder for '/nix/store/rjmb5cb1gdsvmsp00jkxirg9ybixpa87-nix-doc-0.5.3.drv' failed with exit code 101;
       last 10 log lines:
       >   exit status: 1
       >
       >   --- stderr
       >
       >
       >   error occurred: Command "/nix/store/r7r10qvsqlnvbzjkjinvscjlahqbxifl-gcc-wrapper-11.3.0/bin/c++" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-shared" "-Wall" "-Wextra" "-std=c++17" "-isystem" "/nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix" "-isystem" "/nix/store/xfia8xaq94slxmh5phqddqd8s1vcm7kg-boehm-gc-8.0.6-dev/include" "-L\"/nix/store/59galnfxqfih6146d1x32f3wdfv5cvxr-nix-2.9.0/lib\"" "-L\"/nix/store/xjiixs863ck3lkv1k1izw9rlipx6jscl-boehm-gc-8.0.6/lib\"" "-lnixexpr" "-lnixstore" "-lnixutil" "-lgc" "-lpthread" "-ldl" "-isystem" "/nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix" "-L\"/nix/store/59galnfxqfih6146d1x32f3wdfv5cvxr-nix-2.9.0/lib\"" "-lnixstore" "-lnixutil" "-isystem" "/nix/store/rslfmai8503xhyz8b5hb2qdxv2vgjfnb-nix-2.9.0-dev/include/nix" "-L\"/nix/store/59galnfxqfih6146d1x32f3wdfv5cvxr-nix-2.9.0/lib\"" "-lnixmain" "-DNIX_2_4_0" "-DNIX_2_6_0" "-o" "/build/source/target/x86_64-unknown-linux-gnu/release/build/nix-doc-plugin-a2f7562d43b72495/out/plugin.o" "-c" "plugin.cpp" with args "c++" did not execute successfully (status code exit status: 1).
       >
       >
       > warning: build failed, waiting for other jobs to finish...
       > error: build failed
       For full logs, run 'nix log /nix/store/rjmb5cb1gdsvmsp00jkxirg9ybixpa87-nix-doc-0.5.3.drv'.
       ```

**Comment by NickCao** [comment]
Since nix-eval-jobs and hydra-eval-jobs share a similar codebase, here's some fix foe reference: https://github.com/NickCao/nixpkgs/commit/dcdeb606e7d99735959103dba7e543c54c06801a

**Comment by lf-** [comment]
Thank you so much for the ping. I'll look into this today or tomorrow if I can.

**Comment by vcunat** [comment]
Perhaps separate adding 2.9 and switching default?  Addition could surely be merged and backported immediately.

**Comment by Mic92** [comment]
It would be great if nixUnstable would be bumped before merging this. Our ci in nix-eval-jobs automatically bumps the nixpkgs and tests against this version. This pr updates nix to a newer version than nixUnstable currently is.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by kubukoz** [comment]
Result of `nixpkgs-review pr 175541` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>crystal2nix</li>
  </ul>
</details>
<details>
  <summary>50 packages failed to build:</summary>
  <ul>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>colmena</li>
    <li>comma</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>go2nix</li>
    <li>libnixxml</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixStatic)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-eval-jobs</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixos-generators</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>node2nix</li>
    <li>npins</li>
    <li>nuget-to-nix</li>
    <li>nvfetcher</li>
    <li>prefetch-yarn-deps</li>
    <li>python310Packages.nix-kernel</li>
    <li>python39Packages.nix-kernel</li>
    <li>terranix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>yarn2nix</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nixVersions.nix_2_8</li>
  </ul>
</details>

**Comment by Artturin** [comment]
> Result of `nixpkgs-review pr 175541` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 1 package marked as broken and skipped:
> 50 packages failed to build:
> 1 package built:

that's not useful as there's no logs and it builds on ofborg

**Comment by kubukoz** [comment]
> > Result of `nixpkgs-review pr 175541` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> > 1 package marked as broken and skipped:
> > 50 packages failed to build:
> > 1 package built:
> 
> that's not useful as there's no logs and it builds on ofborg

@Artturin I got this before the result was posted:

```
error: build log of '/nix/store/1plc1skyvmzk1vdahim9gw3pqanpra6l-bundix-2.5.1.drv' is not available
error: build log of '/nix/store/56m7xadnvdwjys522zjwpq0lbnvav482-bundix-2.5.1' is not available
error: build log of '/nix/store/ayhs0a03iwvrrq6iri92da5ibgb6dics-cabal2nix-2.18.0.drv' is not available
error: build log of '/nix/store/d1lbq1rrc5kd8jg916wl4kv5dq2iylna-cabal2nix-2.18.0' is not available
error: build log of '/nix/store/6abw1qqmmf9z0hiszc6a7drlidqagz9w-colmena-0.3.0.drv' is not available
error: build log of '/nix/store/r5kzmgh7dnl0mks05r445lci5wl95h0q-colmena-0.3.0' is not available
error: build log of '/nix/store/g51dwwpcgy88kc6g27llq38ik4fdcr5s-comma-1.2.3.drv' is not available
error: build log of '/nix/store/xm8sp68ixkayj71pf5lj2wqhlkmzqc8l-comma-1.2.3' is not available
error: build log of '/nix/store/inqblhylmjbqhz87kbhvc3n78ipgax4v-common-updater-scripts.drv' is not available
error: build log of '/nix/store/6c3mdqgpsj3z4p1j59cj8mq9xkh58spz-common-updater-scripts' is not available
error: build log of '/nix/store/fhjv13h0dgpz3qa0zsscbk8wr5zrpa5j-crate2nix-0.10.0.drv' is not available
error: build log of '/nix/store/i9ardc9pfkbkyahygdxdnl1clknna5kd-crate2nix-0.10.0' is not available
error: build log of '/nix/store/5w0j7rjgf9n5s35zhajxgnrqgvhdbygr-dep2nix-unstable-2019-04-02.drv' is not available
error: build log of '/nix/store/cpzczzdfmvf0lw6avxx4hv8lm1yrzqka-dep2nix-unstable-2019-04-02' is not available
error: build log of '/nix/store/7fnpyxrbycx026lim136cbcfbr3il88z-dydisnix-unstable-2020-11-02.drv' is not available
error: build log of '/nix/store/q6bblssjn5dyxz492wmhkxwlkk7irnj1-dydisnix-unstable-2020-11-02' is not available
error: build log of '/nix/store/qy06lsjm82akl0vbgladhbcpd6l2vlhx-go2nix-1.3.0.drv' is not available
error: build log of '/nix/store/ilili2j56bvhwagmnm0wsvs28k6j44fp-go2nix-1.3.0' is not available
error: build log of '/nix/store/2k2k8cidm15snb211vy0k6hndqx5wlfd-libnixxml-unstable-2020-06-25.drv' is not available
error: build log of '/nix/store/r8anynpkj4q3wccg72qjc5fa4mpa309w-libnixxml-unstable-2020-06-25' is not available
error: build log of '/nix/store/j0sqyhlwljbr5lv86d2x573q84pqqz4b-quicklisp-to-nix-1.0.0.drv' is not available
error: build log of '/nix/store/8imhi2b7k6s9mpdnjh0qzmljhkxk3jq7-quicklisp-to-nix-1.0.0' is not available
error: build log of '/nix/store/5g9d26rnz0id9y6wjhsz6ckmjq2h8hdw-quicklisp-to-nix-system-info-1.0.0.drv' is not available
error: build log of '/nix/store/5ln7mbi2riqmgj1kgx7gc9j91afp8zzm-quicklisp-to-nix-system-info-1.0.0' is not available
```

no clue what happened here

**Comment by Artturin** [comment]
@edolstra you forgot to tag 2.9.1 https://github.com/NixOS/nix/commits/2.9-maintenance

**Comment by vcunat** [comment]
To me that doesn't seem like meant to be a release yet.  I see e.g. the previous bump looong before release: https://github.com/NixOS/nix/commits/master/.version

**Comment by Artturin** [comment]
only nix-plugins fails to compile

**Comment by adisbladis** [comment]
@Artturin I pushed a patch to fix the nix-plugins build.

**Comment by Artturin** [comment]
thanks

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
wait, we wanted to wait for 2.9.1

**Comment by Artturin** [comment]
i applied the segfault fix as a patch

**Comment by SuperSandro2000** [comment]
Missed that, sorry

**Comment by zowoq** [comment]
2.9.1: https://github.com/NixOS/nixpkgs/pull/176827

**Comment by Ma27** [comment]
Any reason why this is not backported to 22.05? Of course only the addition of `nix_2_9`, the default can remain 2.8.

**Comment by vcunat** [comment]
@Ma27: you're looking for https://github.com/NixOS/nixpkgs/pull/177377

**Pull request merged**
