### PR TITLE
ipu6  webcam support

### PR DESCRIPTION
**Pull request by mweinelt**
###### Description of changes

Playing around with ipu6 stack to get the webcam on my 12th gen laptop going.

The overall versioning of things is pretty odd, so I went off of the latest commits.

- [x] kernel driver `linuxPackages.ipu6-drivers`
  - https://github.com/intel/ipu6-drivers
  - [x] can hopefully reuse the `ivsc-driver` source?
- [x] firmware `ipu6-camera-bin`, `ipu6ep-camera-bin`
  - https://github.com/intel/ipu6-camera-bins
  - top-level attributes for tiger lake (11th gen: `ipu6-camera-bin`) and alder lake (12th gen: `ipu6ep-camera-bin`)
- [x] userspace hal `ipu6-camera-hal`, `ipu6ep-camera-hal`
  - https://github.com/intel/ipu6-camera-ha
- [x] gstreamer plugin `gst_all_1.istreamersrc`
  - https://github.com/intel/icamerasrc/tree/icamerasrc_slim_api
  - [x] fails to build: `gstcamerawfovinterface.h:159:70: error: 'camera_view_rotation_t' has not been declared`
    - https://github.com/intel/ipu6-camera-hal/issues/1
    - not sure if putting it below `gst_all_1` is correct
 - [x] kernel driver `ivsc-driver`
   - https://github.com/intel/ivsc-driver
 - [x] firmware `ivsc-firmare`
   - https://github.com/intel/ivsc-firmware

I still need to understand how to install the individual bits and pieces. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
       > /nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wl,-z,relro -Wl,-z,now -version-info 1:0:0  -o libgsticamerainterface-1.0.la -rpath /nix/store/h2p5v5s0jf2xkrypsv7rxcs47fw5km64-icamerasrc-20221209/lib libgsticamerainterface_1.0_la-gstcamera3ainterface.lo libgsticamerainterface_1.0_la-gstcameraispinterface.lo libgsticamerainterface_1.0_la-gstcameradewarpinginterface.lo libgsticamerainterface_1.0_la-gstcamerawfovinterface.lo -L/nix/store/librhg1f9zg03nmm9bf066vvlmqdsflq-gstreamer-1.20.3/lib -L/nix/store/i4dqcpppyyq5yqcvw95mv5s11yfyy8pf-glib-2.74.3/lib -lgstbase-1.0 -lgstcontroller-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -LREFIX/lib -lcamhal
       > ../../libtool: line 7756: cd: REFIX/lib: No such file or directory
       > libtool:   error: cannot determine absolute directory name of 'REFIX/lib'
       > make[3]: *** [Makefile:499: libgsticamerainterface-1.0.la] Error 1
````

This looks like the libcamhal (`ipu6-camera-hal`) pkgconfig file is screwed up, but it isn't as far as I can tell.

````
prefix=/nix/store/2vr5faw6s8lk33za75x90w2291i6kb34-ipu6-camera-hal-unstable-2023-01-09
exec_prefix=$PREFIX
libdir=$PREFIX/lib
includedir=$PREFIX/include/libcamhal

Name: libcamhal
Description: Camera HAL Library
URL:
Version: 
Libs: -L${libdir} -lcamhal
Cflags: -I${includedir} -I${includedir}/api -I${includedir}/utils
```

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 212799` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_14.ivsc-driver</li>
    <li>linuxKernel.packages.linux_4_14_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_14_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_4_19.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_19.ivsc-driver</li>
    <li>linuxKernel.packages.linux_4_19_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_19_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_5_10.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_10.ivsc-driver</li>
    <li>linuxKernel.packages.linux_5_10_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_10_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_5_4.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_4.ivsc-driver</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>gst_all_1.icamerasrc</li>
    <li>ipu6-camera-bin</li>
    <li>ipu6-camera-hal</li>
    <li>ipu6ep-camera-bin</li>
    <li>ipu6ep-camera-hal</li>
    <li>ivsc-firmware</li>
    <li>linuxKernel.packages.linux_5_15.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_15.ivsc-driver</li>
    <li>linuxKernel.packages.linux_hardened.ipu6-drivers (linuxKernel.packages.linux_5_15_hardened.ipu6-drivers)</li>
    <li>linuxKernel.packages.linux_hardened.ivsc-driver (linuxKernel.packages.linux_5_15_hardened.ivsc-driver)</li>
    <li>linuxKernel.packages.linux_6_1.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_6_1.ivsc-driver</li>
    <li>linuxKernel.packages.linux_6_1_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_6_1_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_latest_libre.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_latest_libre.ivsc-driver</li>
    <li>linuxKernel.packages.linux_libre.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_libre.ivsc-driver</li>
    <li>linuxKernel.packages.linux_lqx.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_lqx.ivsc-driver</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ivsc-driver</li>
    <li>linuxKernel.packages.linux_xanmod.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_xanmod.ivsc-driver</li>
    <li>linuxKernel.packages.linux_xanmod_latest.ipu6-drivers (linuxKernel.packages.linux_xanmod_stable.ipu6-drivers)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.ivsc-driver (linuxKernel.packages.linux_xanmod_stable.ivsc-driver)</li>
    <li>linuxKernel.packages.linux_zen.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_zen.ivsc-driver</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Disabled the kernel drivers for kernels before 5.15.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 212799` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_14.ivsc-driver</li>
    <li>linuxKernel.packages.linux_4_14_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_14_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_4_19.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_19.ivsc-driver</li>
    <li>linuxKernel.packages.linux_4_19_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_4_19_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_5_10.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_10.ivsc-driver</li>
    <li>linuxKernel.packages.linux_5_10_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_10_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_5_4.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_4.ivsc-driver</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>gst_all_1.icamerasrc</li>
    <li>ipu6-camera-bin</li>
    <li>ipu6-camera-hal</li>
    <li>ipu6ep-camera-bin</li>
    <li>ipu6ep-camera-hal</li>
    <li>ivsc-firmware</li>
    <li>linuxKernel.packages.linux_5_15.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_5_15.ivsc-driver</li>
    <li>linuxKernel.packages.linux_hardened.ipu6-drivers (linuxKernel.packages.linux_5_15_hardened.ipu6-drivers)</li>
    <li>linuxKernel.packages.linux_hardened.ivsc-driver (linuxKernel.packages.linux_5_15_hardened.ivsc-driver)</li>
    <li>linuxKernel.packages.linux_6_1.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_6_1.ivsc-driver</li>
    <li>linuxKernel.packages.linux_6_1_hardened.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_6_1_hardened.ivsc-driver</li>
    <li>linuxKernel.packages.linux_latest_libre.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_latest_libre.ivsc-driver</li>
    <li>linuxKernel.packages.linux_libre.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_libre.ivsc-driver</li>
    <li>linuxKernel.packages.linux_lqx.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_lqx.ivsc-driver</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ivsc-driver</li>
    <li>linuxKernel.packages.linux_xanmod.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_xanmod.ivsc-driver</li>
    <li>linuxKernel.packages.linux_xanmod_latest.ipu6-drivers (linuxKernel.packages.linux_xanmod_stable.ipu6-drivers)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.ivsc-driver (linuxKernel.packages.linux_xanmod_stable.ivsc-driver)</li>
    <li>linuxKernel.packages.linux_zen.ipu6-drivers</li>
    <li>linuxKernel.packages.linux_zen.ivsc-driver</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
### How to install?

This is an idea of how to set these packages up.

```nix
{
  boot.extraModulePackages = with config.boot.kernelPackages; [
    ipu6-drivers
    ivsc-firmware
  ];

  hardware.firmware = with pkgs; [
    # alder lake (12th gen)
    ipu6ep-camera-bin
    # tiger lake (11th gen)
    #ipu6-camera-bin
    ivsc-firmware
  ];

  environment.systemPackages = with pkgs; [
    # needs to expose the library below /run/current-system/sw/lib/gstreamer-1.0/ I think
    gst_all_1.istreamersrc
  ];
}
```

**Comment by mweinelt** [comment]
Merging, so the packages can receive some exposure by other interested parties.

I can try fixing things, once concrete issues come up.

**Comment by gunar** [comment]
Pardon my ignorance but how would I go about using this? I've written the nix expression below but it doesn't work. Says `kernelPackages` not found.


```nix
  boot.extraModulePackages = let 
    unstable = import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz") {
      config = config.nixpkgs.config;
    }; 
  in with unstable.boot.kernelPackages; [
    ipu6-drivers
    ivsc-driver
  ];
```

**Comment by umazalakain** [comment]
> Installing both ipu6-drivers and ivsc-drivers in parallel leads to a collision.
> 
> ```
> error: builder for '/nix/store/gf2i6gxalmb4phphla1cx8620w4n3ljx-kernel-modules.drv' failed with exit code 25;
>        last 1 log lines:
>        > error: collision between `/nix/store/7srcn7k9kh5w4fkbark6b9ppky95jcjc-ivsc-drivers-unstable-2023-01-06/lib/modules/6.2.6/updates/mei-vsc.ko.xz' and `/nix/store/8mdgyiixan3c61cb7cngsc1cpzx7rn6s-ipu6-drivers-unstable-2023-01-17/lib/modules/6.2.6/updates/mei-vsc.ko.xz'
>        For full logs, run 'nix log /nix/store/gf2i6gxalmb4phphla1cx8620w4n3ljx-kernel-modules.drv'.
> ```

Should we open an issue with this? I might be misunderstanding something, but aren't both packages needed to make the webcam work?

**Comment by mweinelt** [comment]
One is for the camera, the other for the vision sensing controller. I don't think you actually need both.

Note that I had to copies files from the ivsc-driver over into the ipu-driver build. That could be the culprit.

https://github.com/NixOS/nixpkgs/pull/212799/files#diff-16caa0d6bb3233fd6904419a535861b204b336e74db2bbd74d09964381a8aac9R19-R25

**Comment by umazalakain** [comment]
> ```
> (gst-plugin-scanner:240643): GStreamer-WARNING **: 20:46:41.716: Failed to load plugin '/run/current-system/sw/lib/gstreamer-1.0/libgsticamerasrc.so': libia_bcomp.so: cannot open shared object file: No such file or directory
> ERROR: pipeline could not be constructed: no element "icamerasrc".
> ```
Same here

**Comment by betaboon** [comment]
I'll just leave this here for now:
```
ldd /run/current-system/sw/lib/gstreamer-1.0/libgsticamerasrc.so
	linux-vdso.so.1 (0x00007f336502a000)
	libgstallocators-1.0.so.0 => /nix/store/sns39igm2zidkaibkaxcf5kj1g45pq5i-gst-plugins-base-1.20.3/lib/libgstallocators-1.0.so.0 (0x00007f3364fe3000)
	libgstvideo-1.0.so.0 => /nix/store/sns39igm2zidkaibkaxcf5kj1g45pq5i-gst-plugins-base-1.20.3/lib/libgstvideo-1.0.so.0 (0x00007f3364f19000)
	libgsticamerainterface-1.0.so.1 => /nix/store/6dxxglqkkann38nwzzwp8vzkvv0anx18-icamerasrc-unstable-2023-03-09/lib/libgsticamerainterface-1.0.so.1 (0x00007f3364f14000)
	libgstbase-1.0.so.0 => /nix/store/18y1a9hr56dx4cz7rpl59s8b8swlb5mr-gstreamer-1.20.3/lib/libgstbase-1.0.so.0 (0x00007f3364e8d000)
	libgstcontroller-1.0.so.0 => /nix/store/18y1a9hr56dx4cz7rpl59s8b8swlb5mr-gstreamer-1.20.3/lib/libgstcontroller-1.0.so.0 (0x00007f3364e79000)
	libgstreamer-1.0.so.0 => /nix/store/18y1a9hr56dx4cz7rpl59s8b8swlb5mr-gstreamer-1.20.3/lib/libgstreamer-1.0.so.0 (0x00007f3364d28000)
	libgobject-2.0.so.0 => /nix/store/5fk74drrnrhgmcwxvsnmv2lx1srgdfkp-glib-2.74.5/lib/libgobject-2.0.so.0 (0x00007f3364cc7000)
	libglib-2.0.so.0 => /nix/store/5fk74drrnrhgmcwxvsnmv2lx1srgdfkp-glib-2.74.5/lib/libglib-2.0.so.0 (0x00007f3364b8b000)
	libdrm_intel.so.1 => /nix/store/wm7z7ny9p30471bgws2sh9zxrvxdmc9j-libdrm-2.4.115/lib/libdrm_intel.so.1 (0x00007f3364b65000)
	libdrm.so.2 => /nix/store/wm7z7ny9p30471bgws2sh9zxrvxdmc9j-libdrm-2.4.115/lib/libdrm.so.2 (0x00007f3364b4c000)
	libcamhal.so => /nix/store/35qybxcij7ak51m804b8snn9gzcm5z3j-ipu6-camera-hal-unstable-2023-02-08/lib/libcamhal.so (0x00007f3364600000)
	libstdc++.so.6 => /nix/store/shasq3azl2298vqkvq5mc7vivdqp3yrj-gcc-12.2.0-lib/lib/libstdc++.so.6 (0x00007f3364200000)
	libm.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libm.so.6 (0x00007f3364a6c000)
	libc.so.6 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libc.so.6 (0x00007f3363e00000)
	libgcc_s.so.1 => /nix/store/shasq3azl2298vqkvq5mc7vivdqp3yrj-gcc-12.2.0-lib/lib/libgcc_s.so.1 (0x00007f3364a49000)
	liborc-0.4.so.0 => /nix/store/vv845kr9gzpm9ixk0z7nn607gdpzfi2g-orc-0.4.33/lib/liborc-0.4.so.0 (0x00007f3364567000)
	libgmodule-2.0.so.0 => /nix/store/5fk74drrnrhgmcwxvsnmv2lx1srgdfkp-glib-2.74.5/lib/libgmodule-2.0.so.0 (0x00007f3364a42000)
	libunwind.so.8 => /nix/store/n67pfjnhhxb495kjjhgwplb21fhs8i0d-libunwind-1.6.2/lib/libunwind.so.8 (0x00007f3364a28000)
	libdw.so.1 => /nix/store/q40pj3swjqgsjql70l548pq1snbk7n6w-elfutils-0.189/lib/libdw.so.1 (0x00007f33644ca000)
	libffi.so.8 => /nix/store/gy3i9akr5w2dqdzjijcn0nv1df93bnw8-libffi-3.4.4/lib/libffi.so.8 (0x00007f3364a19000)
	libpcre2-8.so.0 => /nix/store/d1i7s6kv9qb6bbnzc0m27lzrrrmhlixn-pcre2-10.42/lib/libpcre2-8.so.0 (0x00007f336442f000)
	libpciaccess.so.0 => /nix/store/kldzcblc7z1hgm80gj3g20kivd4zm36j-libpciaccess-0.16/lib/libpciaccess.so.0 (0x00007f3364a0d000)
	libdl.so.2 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libdl.so.2 (0x00007f3364a08000)
	libexpat.so.1 => /nix/store/hlvahl71n1jjdr7jlqpxwzcjpb6kwaf9-expat-2.5.0/lib/libexpat.so.1 (0x00007f33649db000)
	librt.so.1 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/librt.so.1 (0x00007f33649d6000)
	libia_cca.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_cca.so (0x00007f33641e7000)
	libia_aiq.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_aiq.so (0x00007f3364126000)
	libia_aiqb_parser.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_aiqb_parser.so (0x00007f33649cc000)
	libia_cmc_parser.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_cmc_parser.so (0x00007f336410e000)
	libia_exc.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_exc.so (0x00007f3364427000)
	libia_mkn.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_mkn.so (0x00007f3364108000)
	libia_emd_decoder.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_emd_decoder.so (0x00007f3364103000)
	libia_nvm.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_nvm.so (0x00007f33640fd000)
	libia_log.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_log.so (0x00007f33640f6000)
	libia_dvs.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_dvs.so (0x00007f33640d6000)
	libia_coordinate.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_coordinate.so (0x00007f33640d1000)
	libia_ltm.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_ltm.so (0x00007f33640a0000)
	libia_lard.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_lard.so (0x00007f336409b000)
	libia_isp_bxt.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libia_isp_bxt.so (0x00007f3364065000)
	libbroxton_ia_pal.so => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libbroxton_ia_pal.so (0x00007f3363a00000)
	libgcss.so.0 => /nix/store/zydi4jn6h9hp80d37dvp8wyw9r5azc1k-ipu6-camera-bin-unstable-2023-02-08/lib/libgcss.so.0 (0x00007f3363992000)
	/nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib64/ld-linux-x86-64.so.2 (0x00007f336502c000)
	liblzma.so.5 => /nix/store/skd2pbqccdddfxv3spqq0qlpcp4a7f8w-xz-5.4.1/lib/liblzma.so.5 (0x00007f3364036000)
	libelf.so.1 => /nix/store/q40pj3swjqgsjql70l548pq1snbk7n6w-elfutils-0.189/lib/libelf.so.1 (0x00007f3364019000)
	libz.so.1 => /nix/store/xfkzh15vxmxhiza2s2din1az0vzfaf56-zlib-1.2.13/lib/libz.so.1 (0x00007f3363de2000)
	libzstd.so.1 => /nix/store/scl69wk3mswn05bhdxwvrlbkvq53a5ib-zstd-1.5.4/lib/libzstd.so.1 (0x00007f33638cb000)
	libbz2.so.1 => /nix/store/fhy0p7rapikn15bx7rv797k7fl0shm7n-bzip2-1.0.8/lib/libbz2.so.1 (0x00007f33638b8000)
	libpthread.so.0 => /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libpthread.so.0 (0x00007f3364014000)
	libia_bcomp.so => not found
	libia_ccat.so => not found
```

**Comment by betaboon** [comment]
i got the previous error sorted out by adding `autopatchelf` for the bins. see [here](https://github.com/NixOS/nixpkgs/compare/master...betaboon:nixpkgs:wip-ipu6)

now trying to tackle this:

```sh
$ sudo rm -rf ~/.cache/gstreamer-1.0/
$ GST_DEBUG=2 sudo -E gst-launch-1.0 icamerasrc device-name=tpg_ipu6 ! video/x-raw,format=YUY2,width=1280,height=720 ! videoconvert ! ximagesink
0:00:00.172710684 63864       0xa34730 WARN                  ladspa gstladspa.c:508:plugin_init:<plugin118> no LADSPA plugins found, check LADSPA_PATH

(gst-plugin-scanner:63864): GLib-GObject-WARNING **: 17:39:57.551: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:63864): GLib-GObject-CRITICAL **: 17:39:57.552: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:63864): GLib-GObject-CRITICAL **: 17:39:57.552: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:63864): GLib-GObject-WARNING **: 17:39:57.575: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:63864): GLib-GObject-CRITICAL **: 17:39:57.575: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:63864): GLib-GObject-CRITICAL **: 17:39:57.575: g_type_set_qdata: assertion 'node != NULL' failed
0:00:00.297162744 63864       0xa34730 WARN                 nvcodec gstcudaloader.c:144:gst_cuda_load_library: Could not open library libcuda.so.1, /run/opengl-driver/lib/libcuda.so.1: cannot open shared object file: No such file or directory
0:00:00.297183211 63864       0xa34730 WARN                 nvcodec plugin.c:73:plugin_init: Failed to load cuda library
0:00:00.394583836 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x120000: 'AVR (Audio Visual Research)' is not mapped
0:00:00.394597036 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x180000: 'CAF (Apple Core Audio File)' is not mapped
0:00:00.394602230 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x100000: 'HTK (HMM Tool Kit)' is not mapped
0:00:00.394606747 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0xc0000: 'MAT4 (GNU Octave 2.0 / Matlab 4.2)' is not mapped
0:00:00.394611793 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0xd0000: 'MAT5 (GNU Octave 2.1 / Matlab 5.0)' is not mapped
0:00:00.394614989 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x210000: 'MPC (Akai MPC 2k)' is not mapped
0:00:00.394619990 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0xe0000: 'PVF (Portable Voice Format)' is not mapped
0:00:00.394625176 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x160000: 'SD2 (Sound Designer II)' is not mapped
0:00:00.394629772 63864       0xa34730 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x190000: 'WVE (Psion Series 3)' is not mapped
0:00:00.397870154 63864       0xa34730 WARN               souputils gstsoupelement.c:61:soup_element_init: Failed to load libsoup library
0:00:00.397969483 63864       0xa34730 WARN               souputils gstsoupelement.c:61:soup_element_init: Failed to load libsoup library
0:00:00.427630563 63864       0xa34730 WARN               vadisplay gstvadisplay.c:347:gst_va_display_initialize:<vadisplaydrm0> vaInitialize: unknown libva error
0:00:00.560534014 63862      0x1b808a0 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:701:gst_element_factory_make_with_properties: no such element factory "capsfilter"!
0:00:00.560551047 63862      0x1b808a0 ERROR                default gstutils.c:2161:gst_element_link_pads_filtered: Could not make a capsfilter
0:00:00.560646570 63862      0x1b808a0 ERROR           GST_PIPELINE gst/parse/grammar.y:767:gst_parse_perform_link: could not link camerasrc0 to videoconvert0 with caps video/x-raw, format=(string)YUY2, width=(int)1280, height=(int)720
WARNING: erroneous pipeline: could not link camerasrc0 to videoconvert0 with caps video/x-raw, format=(string)YUY2, width=(int)1280, height=(int)720
```

**Comment by betaboon** [comment]
update regarding the above error:

- the `capsfilter` element is missing
- it is contained in gstreamer-core
- it will not be available in `/run/current-system/sw/lib/gstreamer-1.0` when adding `pkgs.gstreamer` to `systemPackages`
- you have to add `pkgs.gstreamer.out` to `systemPackages`

**Pull request merged**
