### PR TITLE
ticktick: init at 1.0.40

### PR DESCRIPTION
**Pull request by spebern**
###### Description of changes

Add ticktick package https://ticktick.com/about/download

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by farcaller** [comment]
Looks like that extra empty line breaks the fast-forward:

```
$ git merge --no-commit --no-ff 12b47608a536af24d04e2636334451fc795cca25
Auto-merging maintainers/maintainer-list.nix
Auto-merging pkgs/top-level/all-packages.nix
CONFLICT (content): Merge conflict in pkgs/top-level/all-packages.nix
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by farcaller** [comment]
Result of `nixpkgs-review pr 206518` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ticktick</li>
  </ul>
</details>

**Comment by farcaller** [comment]
Result of `nixpkgs-review pr 206518` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ticktick</li>
  </ul>
</details>

**Review by farcaller — COMMENTED** [review]
It looks like it needs some deps specified to work proper:

```
$ ticktick
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: Cannot load default config file: No such file: (null)
Trace/breakpoint trap
```

**Comment by spebern** [comment]
Thanks for the review!
Could you help me to reproduce this?

What I tried is:

```
nixpkgs-review pr 206518
results/ticktick/bin/ticktick
```

This works for me without any problems.

**Comment by farcaller** [comment]
My machine has no X11 packages installed at all (but it has a valid `$DISPLAY`). I'd think there is some indirect dependency on fontconfig or the like which isn't globally present on my box.

**Comment by Emiller88** [comment]
Duplicate of #253113

Looks like it might be able to pull somethings from this PR though

**Comment by MikaelFangel** [comment]
Closed this PR because https://github.com/NixOS/nixpkgs/pull/253113 has been merged

**Pull request closed without merging**
