### PR TITLE
nixos/filesystems: don't silently ignore label when device is set

### PR DESCRIPTION
**Pull request by r-vdp**
## Things done

Before this change, when both device and label were set, the label would be silently ignored. This is especially problematic when the device is set in another module, and it's not immediately obvious why the label is not having any effect.

Additionally, some other modules use the device option to get the device of a filesystem, but this option is not populated when only the label is set, causing those modules to conclude that the filesystem does not have a backing device.

With this change, we populate the device option using the label when the label is set. This means that we get a clear error message when both the device and label are set, and that the device is properly populated whenever the label is used to specify the backing device.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NotAShelf** [comment]
I'm not sure if this change reaches the goal of providing a "clean" error message.

Example:

```
┃        error: The option `fileSystems."/home/notashelf/Media/Music".device' has conflicting definition values:
┃        - In `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/nixos/modules/tasks/filesystems.nix': "/dev/disk/by-label/Music"
┃        - In `/nix/store/k0dhwh76kdmpdn5wjza3grr34ghwy060-source/hosts/enyo/fs/external.nix': "/dev/disk/by-uuid/68a2203f-5ecd-4ddb-b66a-76eb8dcf328c"
┃        Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.

This implies a value has been set in nixpkgs itself and points me to `mkForce` while the issue is that I've set both `device` and `label`, and therefore the proposed solution will not remedy the issue. Maybe an assertion would fit better?

**Comment by r-vdp** [comment]
Yeah, I found it obvious enough what's going on in that case, but indeed an assertion might be even better.

**Comment by NotAShelf** [comment]
Would you like me to submit a pull request to change this to an assertion or a mkDefault + warning?

**Comment by r-vdp** [comment]
Yeah sure, I think an assertion is probably the way to go here, because `mkDefault` would probably get us the silent overriding behaviour again.

**Pull request merged**
