### PR TITLE
octoprint: freeze deps and fix build

### PR DESCRIPTION
**Pull request by elohmeier**
###### Motivation for this change
Octoprint requires an older version of Werkzeug than in nixpkgs, causing a build failure. This pins the dependency version using the already established approach in the octoprint package and fixes the build.
Also the other build dependencies were fixed.

###### Things done
Pinned and fixed dependencies.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gebner** [comment]
@elohmeier Does `uvloop` build for you?  For me it hangs in the `test_sock_cancel_add_reader_race` test.

**Comment by jonringer** [comment]
@elohmeier that's been an issue with that package for months.

I disabled python38 since it was causing me to not be able to review many packages.

https://github.com/NixOS/nixpkgs/commit/367193218862bb927d13e20235fb60a92fc51d9a

but was effective reverted https://github.com/NixOS/nixpkgs/commit/364909d53558ccd6adb5cf135992c6f318d6e80a , although i think it was able to build fine after this ... not sure when it started pausing again

**Comment by gebner** [comment]
@jonringer I don't think disabling `uvloop` on 3.8 is a workable solution.  Lots of stuff depends on it and 3.8 is now the default.  We should either fix it or disable the tests completely.

**Comment by gebner** [comment]
Sorry, didn't mean to close the PR.  Just clicked on the wrong button.

@jonringer This should fix uvloop: https://github.com/NixOS/nixpkgs/pull/91440

**Comment by jonringer** [comment]
> @jonringer I don't think disabling `uvloop` on 3.8 is a workable solution. Lots of stuff depends on it and 3.8 is now the default. We should either fix it or disable the tests completely.

The commit was from January, long before the (python3 -> python38) switch. And I did it so that I could review other packages, I agree it's not a great fix eitiher

**Comment by gebner** [comment]
I've merged master.  Now it fails in `sentry-sdk`..

**Comment by jonringer** [comment]
please avoid merge conflicts, it prefered to do:
```
git pull -r origin master
git push .. .. --force
```
over 
```
git pull origin master
git push
```

**Comment by elohmeier** [comment]
@gebner Thanks for the fix to uvloop, I've rebased onto the latest master containing your changes.
I've also fixed the sentry-sdk and trytond dependencies.

The octoprint build still fails because of conflicting dependency versions, e.g.:
```
pythonCatchConflictsPhase
Found duplicated packages in closure for dependency 'Werkzeug':
  Werkzeug 0.16.1 (/nix/store/ljzw6hh28lvg5jiclwk697slarrjdlcf-python3.8-Werkzeug-0.16.1/lib/python3.8/site-packages)
  Werkzeug 1.0.1 (/nix/store/2yp5874nib71k55984nsac0hdpbbfh7d-python3.8-Werkzeug-1.0.1/lib/python3.8/site-packages)
```

I'm not sure how to override them correctly so that they are modified in the transient dependencies. @jonringer do you have an idea how to do that?

**Comment by jonringer** [comment]
> I'm not sure how to override them correctly so that they are modified in the transient dependencies. @jonringer do you have an idea how to do that?

You can look at https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/awscli/default.nix . This might cause issues, as the package that's bringing in the other werkzeug version likely will needed be patch to accept a different version range.

**Comment by elohmeier** [comment]
Got it fixed now. I had to introduce trytond as a python package, so that the packageOverrides can be applied to it.

The PR should be ready to be merged now.

**Comment by elohmeier** [comment]
Thanks for your help @gebner & @jonringer!

**Comment by ruuda** [comment]
Adding `trytond` as a propagated build input causes everything that depends on `sentry-sdk` to acquire a transitive dependency on `simplejson` though `trytond`. The presence of `simplejson` [then causes `requests` to be have differently](https://github.com/psf/requests/blob/2d39c0db054e158767ab4a755476844fe40787e7/requests/compat.py#L28-L31).

Is it possible to make the `trytond` dependency optional? As far as I understand, Sentry has special support for it if you happen to use Tryton, but if you don’t, Sentry should work fine without.

**Pull request merged**
