### PR TITLE
Add notifier configs to grafana provisioning

### PR DESCRIPTION
**Pull request by ivanbakel**
Based on #53874

###### Motivation for this change

Similar to dashboards and datasources, notifiers in Grafana can also be provisioned. Currently, there is no easy way to configure notifiers through Nix.

See: https://grafana.com/docs/grafana/latest/administration/provisioning/#alert-notification-channels

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
I didn't really review but I happened to notice option descriptions are missing a trailing period.

**Comment by ivanbakel** [comment]
Should I add periods to all the other option descriptions in the file as well?

**Comment by ivanbakel** [comment]
Alright, that's done.

**Comment by petabyteboy** [comment]
This broke the build for me:

```
builder for '/nix/store/wbwsdbqjk9l0flwwzigka4dpbgs7vyal-grafana-provisioning.drv' failed with exit code 1; last 1 log lines:
  ln: failed to create symbolic link '/nix/store/rdl0pzjyxv27gm4ps93wnc3r6bsya3ks-grafana-provisioning/notifiers/notifier.yaml': No such file or directory
```

The target directory for the symlink is not created.
I will push a fix to master since this is trivial.

**Pull request merged**
