### PR TITLE
vips: 8.13.3 -> 8.14.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/libvips/libvips/compare/v8.13.3...v8.14.1

Changelog: https://github.com/libvips/libvips/blob/v8.14.1/ChangeLog

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by urandom2 — APPROVED** [review]
I am assuming tests are not passing on darwin without `__darwinAllowLocalNetworking = true;`? assuming it is required, I do not oppose it, but I have not tested it with and without myself.

also, are we sure that the imaginary change should not be a separate pr?

**Comment by superherointj** [comment]
> I am assuming tests are not passing on darwin without `__darwinAllowLocalNetworking = true;`? assuming it is required, I do not oppose it, but I have not tested it with and without myself.
> 
> also, are we sure that the imaginary change should not be a separate pr?

No. It is a separate commit, that is fine.
But ideally it should be one commit per package for an upgrade with details being part of commit message.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 215074` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>photoflow</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>faircamp</li>
    <li>grafana-image-renderer</li>
    <li>haskellPackages.gi-vips</li>
    <li>imaginary</li>
    <li>imgproxy</li>
    <li>joplin</li>
    <li>nip2</li>
    <li>python310Packages.pyvips</li>
    <li>python310Packages.pyvista</li>
    <li>python310Packages.scooby</li>
    <li>python310Packages.sfepy</li>
    <li>python311Packages.pyvips</li>
    <li>python311Packages.scooby</li>
    <li>rubyPackages.ruby-vips (rubyPackages_2_7.ruby-vips)</li>
    <li>rubyPackages_3_0.ruby-vips</li>
    <li>rubyPackages_3_1.ruby-vips</li>
    <li>vips</li>
    <li>vipsdisp</li>
  </ul>
</details>

**Comment by risicle** [comment]
Yup, just the photoflow failure on macos 10.15 too

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
