### PR TITLE
fishPlugins.sponge: init at 1.1.0

### PR DESCRIPTION
**Pull request by quantenzitrone**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSamus** [comment]
It doesn't seem to work on my end.
Did I forget to configure something? Or should I open an issue here?

**Comment by Quantenzitrone** [comment]
are you sure? no you don't need to configure anything

**Comment by SuperSamus** [comment]
Yes: no matter how wrong failing commands I input, they all stay in the history.
I added the plugin through `environment.systemPackages`, just like the other ones (and these other ones work).

**Comment by SuperSamus** [comment]
In order for Sponge to work, I have to manually call `_sponge_on_prompt`.

**Comment by Quantenzitrone** [comment]
ok, i actually got it working by setting `set sponge_allow_previously_successful false`, otherwise sponge would just remove all my new history
i actually stopped using sponge after a while, because i ran into the same problem of it removing all new history and i didn't find it that useful after all, because even before it started removing all new history, it annoyed me more than feeling useful
maybe sponge is a bit buggy 😬

**Pull request merged**
