### PR TITLE
sleek-grub-theme: unstable-2022-06-04 -> unstable-2024-06-16

### PR DESCRIPTION
**Pull request by mf81234**
## Description of changes

Updated to latest source commit. Includes fixes and additional icons. Edited withStyle to match.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mf81234** [comment]
So sorry for the mass ping on my first attempt, [https://github.com/NixOS/nixpkgs/pull/330644](https://github.com/NixOS/nixpkgs/pull/330644). I believe I've done correctly this time.

**Comment by mf81234** [comment]
Pinging maintainer: @luochen1990

**Comment by luochen1990** [comment]
LGTM, although there is still [issue not fixed](https://github.com/sandesh236/sleek--themes/pull/25), merging this first is not a bad idea.

**Comment by mf81234** [comment]
Sorry for all the mess with my force pushed commits, trying to keep the commit to be merged in one. Changes below:

- Due to known fetchpatch/fetchpatch2 issues with renaming/moving files (https://github.com/NixOS/nixpkgs/issues/266556), I implemented https://github.com/sandesh236/sleek--themes/pull/25 in the prePatch with a simple `mv`.
 - Applied https://github.com/sandesh236/sleek--themes/pull/22 with fetchpatch2
 - Changed version to match date of last patch https://github.com/sandesh236/sleek--themes/pull/25/commits/ac3eca3ed91bac9233948e7ea5dea295a79694a1

**Comment by luochen1990** [comment]
Upstream merged the fix just now. and the patch is no needed here

**Comment by luochen1990** [comment]
Just confirm that this is still active ...

**Pull request closed without merging**
