### PR TITLE
webkitgtk: 2.18 -> 2.20

### PR DESCRIPTION
**Pull request by bendlas**
see https://webkitgtk.org/2018/03/12/webkitgtk2.20.0-released.html
cc @hamishmack @groxxda

### Update: as of second patch, build on nixos succeeds

~The build fails with~
```
...
[ 79%] Generating ../../DerivedSources/WebKit/WebInspectorUIMessageReceiver.cpp, ../../DerivedSources/WebKit/WebInspectorUIMessages.h
[ 79%] Generating ../../DerivedSources/WebKit/LegacyCustomProtocolManagerMessageReceiver.cpp, ../../DerivedSources/WebKit/LegacyCustomProtocolManagerMessages.h
[ 79%] Generating ../../DerivedSources/WebKit/StorageAreaMapMessageReceiver.cpp, ../../DerivedSources/WebKit/StorageAreaMapMessages.h
[ 79%] Generating ../../DerivedSources/WebKit/LegacyCustomProtocolManagerProxyMessageReceiver.cpp, ../../DerivedSources/WebKit/LegacyCustomProtocolManagerProxyMessages.h
[ 79%] Generating ../../inspector-resources.stamp
No such file or directory
make[2]: *** [Source/WebKit/CMakeFiles/WebKit.dir/build.make:2191: inspector-resources.stamp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1239: Source/WebKit/CMakeFiles/WebKit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 79%] Linking CXX static library ../../lib/libWebCoreTestSupport.a
[ 79%] Built target WebCoreTestSupport
make: *** [Makefile:152: all] Error 2
builder for '/nix/store/0303qc28jl5h5bv9rbxjhp4ir54bvil3-webkitgtk-2.20.0.drv' failed with exit code 2
error: build of '/nix/store/0303qc28jl5h5bv9rbxjhp4ir54bvil3-webkitgtk-2.20.0.drv' failed: builder for '/nix/store/0303qc28jl5h5bv9rbxjhp4ir54bvil3-webkitgtk-2.20.0.drv' failed with exit code 2
error: build of '/nix/store/0303qc28jl5h5bv9rbxjhp4ir54bvil3-webkitgtk-2.20.0.drv' failed
```

### Darwin support:

None of the Darwin patches apply any more, and since I don't own a Mac
to test new ones, I deleted them from the build. Please re-add as
necessary.
The patch expression also likely needs updating.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Can this be the issue https://bugs.webkit.org/show_bug.cgi?id=181040? I would like to merge this to #36893.

**Comment by bendlas** [comment]
Awesome find. It seems that patch has already landed, however, when sneaking a `patchShebangs .` into `postPatch`, it found two more cases of `/bin/bash`, in something called `generate-parser.sh`. Running the build now ...

**Comment by bendlas** [comment]
Great Success! The error generating `inspector-resources.stamp` was fixed. Let's see, if the build comes through ...

**Comment by bendlas** [comment]
It worked. Binaries seem to run.
Since there don't seem to be any critical security fixes, I'll leave this till the weekend to see if somebody wants to take care of darwin support. If nobody shows up, I'll re-add the 2.18 file for Darwin.

**Comment by jtojnar** [comment]
For some reason, it does not build for me without `libgcrypt` on unstable.

**Comment by bendlas** [comment]
> For some reason, it does not build for me without libgcrypt on unstable.

On NixOS? How does this manifest? Does it suffice to add to build inputs?

**Comment by jtojnar** [comment]
Yes. The following error: 
```
CMake Error at /nix/store/9bhialxbn35a1vlgjbvn6nwjgs54cl19-cmake-3.10.2/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibGcrypt (missing: LIBGCRYPT_LIBRARY LIBGCRYPT_INCLUDE_DIR)
  (Required is at least version "1.6.0")
Call Stack (most recent call first):
  /nix/store/9bhialxbn35a1vlgjbvn6nwjgs54cl19-cmake-3.10.2/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  Source/cmake/FindLibGcrypt.cmake:74 (find_package_handle_standard_args)
  Source/cmake/OptionsGTK.cmake:25 (find_package)
  Source/cmake/WebKitCommon.cmake:61 (include)
  CMakeLists.txt:152 (include)


-- Configuring incomplete, errors occurred!
```

Yes, it is enough.

**Comment by hedning** [comment]
I'm unable to build this (this exact commit, and on top of master). The error:
```
[ 25%] Building CXX object Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/llint/LLIntOffsetsExtractor.cpp.o
In file included from /build/webkitgtk-2.20.0/Source/JavaScriptCore/heap/HeapFinalizerCallback.h:28:0,
                 from /build/webkitgtk-2.20.0/Source/JavaScriptCore/heap/Heap.h:33,
                 from /build/webkitgtk-2.20.0/Source/JavaScriptCore/heap/DeferGC.h:29,
                 from /build/webkitgtk-2.20.0/Source/JavaScriptCore/runtime/ConcurrentJSLock.h:28,
                 from /build/webkitgtk-2.20.0/Source/JavaScriptCore/bytecode/ArrayProfile.h:28,
                 from /build/webkitgtk-2.20.0/Source/JavaScriptCore/llint/LLIntOffsetsExtractor.cpp:28:
/build/webkitgtk-2.20.0/Source/JavaScriptCore/API/JSHeapFinalizerPrivate.h:29:41: fatal error: JavaScriptCore/JSContextRef.h: No such file or directory
 #include <JavaScriptCore/JSContextRef.h>
                                         ^
```
Full log from hydra: https://nix-cache.s3.amazonaws.com/log/xfy72vycyzrb0rg39s32gq92dmdbkprv-webkitgtk-2.20.0.drv

**Comment by hedning** [comment]
Hydra have managed to build it now: https://nix-cache.s3.amazonaws.com/log/6qghl7v3bzdq1gpvdf16ankcmr3v6c22-webkitgtk-2.20.0.drv

Not sure what the problem was.

**Comment by jtojnar** [comment]
Merged as part of #36893

**Comment by bendlas** [comment]
Thanks for taking care of this, @jtojnar!

I've even got 2 commits sitting in my repo: one to add libgcrypt and one to restore 2.18 for Darwin, but I got completely distracted due to release week at work :-/

**Comment by bendlas** [comment]
oh jeez, I'm really glad we already updated https://webkitgtk.org/security/WSA-2018-0003.html

**Comment by hedning** [comment]
We really should backport it then though.

**Comment by bendlas** [comment]
Thanks again!

**Comment by bendlas** [comment]
OK, two more fixes: For enchant2 not being backported and for a `propagatedBuildInput` fix, that was already in master. Build should come through now ...

**Comment by bendlas** [comment]
@hedning btw, do you think, that, with your determinism fix, we could also try to enable parallel builing again?

**Comment by jtojnar** [comment]
cmake should build in parallel by default: https://github.com/NixOS/nixpkgs/pull/32271

**Pull request closed without merging**
