### PR TITLE
[19.09] nixos/release-combined; migrate constituents list to strings

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

As of a few days ago hydra has a different GC configuration that leads
to eval failures when the tested job has a direct dependency on all
the tests. This is an attempt at migrating the old list of jobs to the
new format while keeping the logic and the tests the same.

Currently channel bumps of nixos-19.09 are being blocked. This should unblock it.

###### Things done
Testing eval for the new format doesn't seem to be straight forward from my point of view and my laptop lacks enough memory to do it..

Hopefully someone with the right flavor and version of nix installed can use the new `nix hydra-eval-jobs` command to test this.

----
cc @edolstra

### CODE REVIEW

**Comment by edolstra** [comment]
We also need 895042956f279ae8ebc9fd026664cea8198f71ec, since the `tested` job of the small channel also takes 20 GiB to evaluate.

**Comment by edolstra** [comment]
I also noticed `tested` in `release-combined` is returning some nested lists, which `nix eval-hydra-jobs` doesn't support:
```
$ nix eval --json --file nixos/release-combined.nix tested.constituents | jq .
[
  "nixos.channel",
  [
    "nixos.dummy.x86_64-linux"
  ],
  [
    "nixos.manual.x86_64-linux"
  ],
...
```
Could you `flatten` the list?

**Comment by vcunat** [comment]
Wait with this, please.  On master and 20.03 the lists seem flat but Hydra aborts them anyway and thus channels are blocked (even -small ones).

**Comment by andir** [comment]
@edolstra list has been flattend and the small set has been added as well.

We should probably address the point that @vcunat raised.

**Comment by vcunat** [comment]
That one's probably solved.  -small `tested` jobs succeeded already, so I expect the big ones will do the same once their dependencies have finished.

**Comment by andir** [comment]
Any objections to merging this in? Anything else to be done?

**Comment by vcunat** [comment]
I see no objections.

The 19.09 jobset has been unable to evaluate for a week; I'm not sure why, perhaps this is "the error"?
> error: unexpected EOF reading a line

Perhaps it is some kind of resource exhaustion and merging this will fix that :woman_shrugging:

**Comment by andir** [comment]
That is  the error that made me open this. Eelco suggested that we do this
change on IRC.

**Comment by edolstra** [comment]
Thanks!

`error: unexpected EOF reading a line` probably means one of the evaluator worker processes died with an OOM.

**Pull request merged**
