### PR TITLE
pipewire: 0.3.56 -> 0.3.57

### PR DESCRIPTION
**Pull request by K900**
- libcamera: unstable-2022-07-15 -> unstable-2022-09-03
  - https://github.com/libcamera-org/libcamera/compare/e9b6b362820338d0546563444e7b1767f5c7044c...f1776100f55e70320a8938586bc8bf2f242addd4
- pipewire: 0.3.56 -> 0.3.57
  - https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.57
  - https://github.com/pipewire/pipewire/compare/0.3.56...0.3.57

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — CHANGES_REQUESTED** [review]
libcamera
- no longer needs boost: https://github.com/libcamera-org/libcamera/commit/c1597f989654618f782012104f547b367082fa3e
- replaces sdl_image by libjpeg: https://github.com/libcamera-org/libcamera/commit/dc1f4a91dfefa9f86202ab148e05fb901b6e3e73 (not sure why we do not have that)
- we can use openssl instead of gnutls: https://github.com/libcamera-org/libcamera/commit/12f48aa65e45a50bba6df07db56b77ccfbdb3f77 (not sure if it makes sense)

pipewire: changes look okay

**Comment by mweinelt** [comment]
> we can use openssl instead of gnutls: libcamera-org/libcamera@12f48aa (not sure if it makes sense)

Yes, please!

**Comment by K900** [comment]
Updated libcamera. libjpeg is only used by the Android bits, which we don't build.

**Review by jansol — COMMENTED** [review]
I'm not particularly enthusiastic about having openssl both in native and build dependencies but libcamera does not seem to build without both so it is what it is.

As for actual functionality, everything seems fine based on rebuilding my desktop with this PR applied and playing random stuff in firefox, tauon and mpv.

**Review by jansol — APPROVED** [review]

**Comment by K900** [comment]
They use the openssl tool at build time, so we do need it in both.

**Comment by K900** [comment]
Should be OK to merge now? Want to get it in the next staging before we have to figure out LC3 for 0.3.58. 
@jtojnar @jansol

**Comment by jansol** [comment]
No objections.

**Pull request merged**
