### PR TITLE
treewide: avoid string-concatenating cmakeFlags

### PR DESCRIPTION
**Pull request by ShamrockLee**
## Description of changes

This PR replaces string-concatenated cmakeFlags operations with `cmakeFlags` attribute elements or `prependToVar` or `appendToVar`.

Cc:
@moni-dz `molsketch` maintainer
@nim65s `python3Packages.pymeshlab` maintainer
@nico202 `yarp` maintainer
@orivej @edolstra @r-burns `aws-c-common` maintainers
@deepfire `openwsman` maintainer
@viric `vigra` original package author and previous maintainer
@costrouc `python3Packages.hoomd-blue` original package author and previous maintainer
@rmcgibbo @natsukium `python3Packages.rdkit` maintainers
@hce `commandergenius` maintainer
@bzizou `irods` maintainer

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/READvME.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage) (The evaluation passes, and there are 491 changed reverse dependencies. I didn't test building because the build dependencies require at least 65GB of disk space.)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ShamrockLee** [comment]
@ofborg build molsketch
@ofborg build python310Packages.pymeshlab python311Packages.pymeshlab
@ofborg build yarp
@ofborg build aws-c-common
@ofborg build openwsman
@ofborg build vigra
@ofborg build python311Packages.hoomd-blue python312Packages.hoomd-blue
@ofborg build python311Packages.rdkit python312Packages.rdkit
@ofborg build commandergenius
@ofborg build irods

**Comment by ShamrockLee** [comment]
@ofborg build molsketch
@ofborg build python310Packages.pymeshlab python311Packages.pymeshlab
@ofborg build yarp
@ofborg build aws-c-common
@ofborg build openwsman
@ofborg build vigra
@ofborg build python311Packages.hoomd-blue python312Packages.hoomd-blue
@ofborg build python311Packages.rdkit python312Packages.rdkit
@ofborg build commandergenius
@ofborg build irods

**Review by bzizou — APPROVED** [review]
Successfully built and locally tested irods binaries

**Review by nim65s — COMMENTED** [review]
diff LGTM, but I guess you should do this in separate commits. the vigra reformat should also be in a separate commit I think.

**Comment by ShamrockLee** [comment]
> diff LGTM, but I guess you should do this in separate commits. the vigra reformat should also be in a separate commit I think.

I split the changes into commits while keeping the diff unchanged.

**Review by nim65s — APPROVED** [review]
thanks !

**Comment by ShamrockLee** [comment]
The pkgs/by-name check failure may result from GitHub's internal issue.

**Comment by ShamrockLee** [comment]
@ofborg build python311Packages.pymeshlab python311Packages.pymeshlab.tests python312Packages.pymeshlab python312Packages.pymeshlab.tests
@ofborg build python310Packages.pymeshlab python310Packages.pymeshlab.tests python312Packages.rdkit python312Packages.rdkit.tests

**Review by nim65s — APPROVED** [review]

**Review by moni-dz — APPROVED** [review]

**Review by jopejoe1 — APPROVED** [review]

**Pull request merged**
