### PR TITLE
kbd: Renamed norwegian dvorak keymap to dvorak-no.

### PR DESCRIPTION
**Pull request by plutotulp**
This brings it in line with all the other dvorak map names, and keeps
it from hogging the "no" name from the qwery map.

###### Motivation for this change
Issue  #47877; would get dvorak instead of qwerty keymap for "no" map.

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
There are quite a few duplicates: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kbd

**Comment by Mic92** [comment]
Do you mind adding those as well?

**Comment by Mic92** [comment]
Looks good. Can you change the branch from staging to master? This might require a rebase + force push on your site.

**Comment by plutotulp** [comment]
Rebased to master, rewrote as a single commit on top of that, then force pushed.

**Comment by Mic92** [comment]
@plutotulp never mind I actually meant the opposite. Did you were on staging before. I will push it to staging now. I must have been confused.

**Comment by Mic92** [comment]
added in f1987fb58f57828944ca822bbb39b3de87f01863

**Comment by Mic92** [comment]
At least I was able to test the pull request more easily on master.

**Comment by plutotulp** [comment]
Great, thanks!

**Pull request closed without merging**
