### PR TITLE
firefox: default to speech synthesis enabled

### LINKED ISSUE #259497: Firefox Speech Synthesis option should be enabled by default
Firefox's speech synthesis got added as support in #210453, but it's disabled by default. I'm suggesting here that since speech synthesis is an accessibility feature, it should be enabled by default and then opted out by the user if the user doesn't require or need speech synthesis.

### PR DESCRIPTION
**Pull request by cafkafk**
## Description of changes
Closes: #259497 

ping @nyabinary

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 259534` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>betterbird</li>
    <li>dropbox</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>firefox</li>
    <li>firefox-beta</li>
    <li>firefox-beta-bin</li>
    <li>firefox-bin</li>
    <li>firefox-devedition</li>
    <li>firefox-devedition-bin</li>
    <li>firefox-esr</li>
    <li>firefox-mobile</li>
    <li>librewolf</li>
    <li>mate.caja-dropbox</li>
    <li>midori</li>
    <li>sitespeed-io</li>
    <li>slimerjs</li>
    <li>thunderbird</li>
    <li>thunderbird-bin</li>
    <li>vimb</li>
  </ul>
</details>

**Comment by cafkafk** [comment]
`nix-build -A nixosTests.firefox` worked

**Comment by ju1m** [comment]
Thanks for this PR. However, could we have a closure size delta? Is this PR indeed increasing the closure size by ~0.7G as @vcunat [suggested](https://github.com/NixOS/nixpkgs/issues/248179#issuecomment-1704712177)?
A quick `nix path-info -rsS nixpkgs#speechd | sort -n -k2` points to ~644M for `mbrola-voices`:
```
/nix/store/qvq40jin7j7j6fpravnq04f4gj4vqmib-mbrola-voices-3.3            	  675956120	  675956120
```

**Comment by mweinelt** [comment]
It's a trade-off, really. The interesting question is what Mozilla does to control the closure size.

**Comment by ju1m** [comment]
Yes, precisely, that's why I'm asking, knowing the closure size delta would have been helpful to make an informed trade-off. Maybe, like for `ffmpeg`, we should have more `wrapFirefox` derivations in `all-packages.nix` to let end-users make their own trade-offs.

**Comment by Nyabinary** [comment]
We shouldn't turn this off by default because it quite literally an accessibility, that my thought process at least.

**Comment by ju1m** [comment]
And I am happy to have `speechd` enabled by default, as a matter of fact I landed here because firefox told me "You cannot use speech synthesis because the Speech Dispatcher library is missing", which displeased me.

Yet, the [closure size delta no longer being a requirement of the PR template](https://github.com/NixOS/nixpkgs/issues/51368#issuecomment-1030844926), and reading a message warning about it, it would have been good to confirm it.

This could have given both a reason and a start for another PR to make `-full` and/or `-small` variants to select the closure size (which, security-wise, is also impacting the attack surface), to follow a pattern found elsewhere in Nixpkgs. Because there is reason to wager that recompiling `firefox` is not pratical for most users, hence the default is the only pratical choice.

**Comment by vcunat** [comment]
This setting does not cause any recompilation.

**Comment by ju1m** [comment]
Oh, great, then everything is fine to me, sorry for the noise.

**Comment by SuperSandro2000** [comment]
> It's a trade-off, really.

A really bad one which costs us 0.7 GB of extra storage.

without:
```
 ➜ nix path-info -hS $(which firefox)
/nix/store/n5vdac59hffc8bvsy0yjbg4h61rp3349-firefox-bin-118.0.1    2.1G
```

with:
```
 ➜ nix path-info -hS $(which firefox)
/nix/store/36gd5ak5kzj99fla99mbnsw1bwja2820-firefox-bin-118.0.1    2.8G
```

Which is mostly caused by mbrola-voices as analyzed already. We are installing all voices available. For example Arch Linux by default doesn't use mbrola for speech-dispatcher and then if you want to us mbrola you need to install the voices you are interested in manually. 

We should really split up mbrola-voices at least into one package per language and then make it configurable. Maybe depended on the configured locale.

The current trade off is not acceptable, 25% of the closure size is used by an optional feature which not a majority of the users are using.

> The interesting question is what Mozilla does to control the closure size.

They made this an optional feature people can opt in. Other distros are doing similar things by marking speech-dispatcher as optional and the message in firefox tells you, if you want to use that feature, install speech-dispatcher.

> We shouldn't turn this off by default because it quite literally an accessibility, that my thought process at least.

All accessibility features I can think of right now are turned off by default. Be it the narrator on Windows, bigger text, high contrast, etc because if you are not depended on them they are distracting.

**Comment by SuperSandro2000** [comment]
Created a revert in #261058 because IMO this is not justifiable.

**Comment by vcunat** [comment]
A partial/independent improvement: https://github.com/NixOS/nixpkgs/pull/261619

**Pull request merged**
