### PR TITLE
[WIP/RFC] update firefox on 17.09

### PR DESCRIPTION
**Pull request by pbogdan**
##### Motivation for this change

Update firefox to the most recent stable release, fixes https://github.com/NixOS/nixpkgs/issues/32655.

https://www.mozilla.org/en-US/firefox/57.0/releasenotes/
https://www.mozilla.org/en-US/firefox/57.0.1/releasenotes/
https://www.mozilla.org/en-US/firefox/57.0.2/releasenotes/

Notably:

> Firefox now exclusively supports extensions built using the WebExtension API, and unsupported legacy extensions will no longer work. Learn more about our efforts to improve the performance and security of extensions

has potential to break many commonly used extensions. OTOH the latest release incorporates a number of security fixes that may be difficult to backport individually on top of current firefox included in 17.09.

Note this uses a binary distribution of rust / cargo as I can't figure out how to bootstrap a recent enough version of cargo without either:

- breaking backward compatibility of `buildRustPackage`
- breaking something else in the process
- breaking i686-linux support

(or a combination of any of the above). My rust packing knowledge is severely lacking though.

This uses rust 1.19.0 but we could perhaps jump straight to 1.22.1 (latest upstream stable release) which should cover minimum required rust version for firefox build for the whole of 17.09 supported lifetime - https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox#Schedule.

I'm also unsure if it makes sense to expose the new rust version attribute as top-level as it's only meant to be consumed by firefox.

I have not yet tested build of all dependent packages as the nss / nspr update required by firefox triggers quite a rebuild and I wanted to check first the overall direction of this PR was acceptable.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
FWIW Some form of this patch must be applied to 17.09, thank you so so much for taking the initiative. I know this is a big job. 17.09 must be updated to FF57+.

**Comment by pbogdan** [comment]
I have seemingly managed to build rust 1.20.0 and cargo 0.22.0 from source (bootstrapping from 1.19.0 binary dist as is done for other rust versions) in a way that doesn't impact the current versions and keeps `buildRustPackage` unchanged in terms of `depsSha256` (for cases where the hash isn't broken already..). 

Before I try to test it further - would this be strongly preferred over just using binary distribution for firefox builds as it's currently done in this PR? (I'm yet to push the "build rust from source" changes).

**Comment by grahamc** [comment]
IMO, preferable yes, but most preferable is getting ff57 applied to 17.09. I'm testing what you have now (waiting on the FF build ...) if you're interested in getting the from-source going, could you do a separate branch from this one?

**Comment by pbogdan** [comment]
For now changes pertaining to building newer rust and cargo from source are in https://github.com/pbogdan/nixpkgs/compare/ecff1df7f2b84ccde9744c9deb2fbc0fde830fcf...pbogdan:update-rust?expand=1 in case anyone has any comments (in particular if that looks like an acceptable solution at all). Again, my rust / cargo machinery knowledge is very limited..

**Comment by pbogdan** [comment]
Ah, didn't see your comment before posting mine, I can create a separate branch, including firefox-related commits, based on what I have in the previous comment.

**Comment by grahamc** [comment]
OK I'm using this build right now. I'd love to merge this ~now.

**Comment by pbogdan** [comment]
It would be great if we could see the impact of nss / nspr update but it's a very heavy rebuild. FTR I built and used both x86_64-linux and i686-linux versions of firefox built from this PR, but not all of the dependent packages (which, among a whole bunch of others, include firefox-esr, torbrowser, chromium).

WIP label was added on the account of not having ran a full rebuild and the changes I anticipated might be required to build rust from source.

**Comment by vcunat** [comment]
Thanks.  I had run it briefly on both platforms without noticing any problems (only I didn't manage to report it timely and merge).

**Pull request merged**
