### PR TITLE
tbb: 2018_U5 -> 2018_U6

### PR DESCRIPTION
**Pull request by fadenb**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build tbb

**Comment by fadenb** [comment]
@markuskowa The GitHub releases page ( https://github.com/01org/tbb/releases ) lists 2018_U6 as "latest release".
I do not know that package very well, should I package the 2019_U1 instead?

**Comment by markuskowa** [comment]
I would give 2019_U1 a try. I was not listed as unstable on the homepage. We just need to check if all packages that depend on tbb still compile.

**Comment by markuskowa** [comment]
`2019_U2` is now marked as latest release. We should use that one.

**Review by markuskowa — CHANGES_REQUESTED** [review]
update to `2019_U2`

**Comment by markuskowa** [comment]
2019_U3 is already out. Closing this PR so that the auto updater can pick it up in the next run.

**Pull request closed without merging**
