### PR TITLE
fluidasserts: 20.1.22554 -> 20.1.28253

### PR DESCRIPTION
**Pull request by kamadorueda**
- bumps the fluidasserts version to 20.1.28253
- in this version the build process is deterministic and
  reproducible (you'll get the same hash on multiple builds)
- refactored the tests accordingly to a maintainer suggestion in last PR
- added many new tests :)
- see: https://gitlab.com/fluidattacks/asserts/issues/873

###### Motivation for this change

- Reproducible builds

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM
commit LGTM

```
[3 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/78111
1 package built:
fluidasserts
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build fluidasserts

**Comment by jonringer** [comment]
darwin builds are timing out, if it's broken, we will revisit it :)

**Comment by kamadorueda** [comment]
@jonringer gonna inspect it https://gitlab.com/fluidattacks/asserts/issues/875

**Pull request merged**
