### PR TITLE
doc: fix nixos-rebuild

### PR DESCRIPTION
**Pull request by happysalada**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by pennae — APPROVED** [review]
the with removal is unrelated, might be nicer to split it out. eval is fixed, currently running the tests to see if they run too.

**Comment by happysalada** [comment]
I've split it out in 2 commits. Feel free to merge when the tests ran satisfactorily.
(happy to merge as well if you would rather not).

**Comment by happysalada** [comment]
@pennae btw, I'm grateful that you made the change you did. nixpkgs needs more love, and not so many people want to undertake more involved changes.
Thanks again!

**Comment by happysalada** [comment]
for other people coming here, there is one more reference in one of home-manager's dependency
https://git.sr.ht/~rycee/nmd/tree/master/item/lib/manual-docbook.nix#L37
this will likely take a couple of days to get fixed.

**Comment by piegamesde** [comment]
Was this change time critical in any way justifying a (self-)merge after not even fifteen minutes?

**Comment by happysalada** [comment]
@piegamesde thanks for coming by!
The change was small and it was something that was forgotten in the original PR causing breakage. I didnt see much harm here.
(I came to the original PR not being able to switch to the latest nixpkgs, so i thought it did warrant fast action)
What do you suggest in the future ?

**Comment by piegamesde** [comment]
Personally, I'd like to have all pull requests open for at least 24 hours (with an exception for security relevant ones and maybe quick-reverts), and if it was technically possible I would even like to enforce that. Most of the time waiting a couple of extra hours does is not that bad, especially given since channels have a similar delay already.

**Pull request merged**
