### PR TITLE
python310Packages.playwright: set meta.platforms

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
We no longer need to rely on throw. See https://github.com/NixOS/nixpkgs/pull/215721#issuecomment-1426856654.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
error: hash mismatch in fixed-output derivation '/nix/store/zdxjpar970s2z1sfslcqc0ca7l3lqapx-playwright-browsers-base.drv':
         specified: sha256-KtCkLgDvaVRlbVyhqfiWcx3kSYpKfGP5/DH4FQnnU3w=
            got:    sha256-TzprR95KHYBu9SruI4BgwCaqI7KKe3HuzgCO1A5YFiM=
error: 1 dependencies of derivation '/nix/store/axb7gqw8hk3ca5fhi1wmryxix4v64k1j-playwright-browsers-1.27.1.drv' failed to build
```

for x86_64-darwin

**Comment by dotlambda** [comment]
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/zdxjpar970s2z1sfslcqc0ca7l3lqapx-playwright-browsers-base.drv':
>          specified: sha256-KtCkLgDvaVRlbVyhqfiWcx3kSYpKfGP5/DH4FQnnU3w=
>             got:    sha256-TzprR95KHYBu9SruI4BgwCaqI7KKe3HuzgCO1A5YFiM=
> error: 1 dependencies of derivation '/nix/store/axb7gqw8hk3ca5fhi1wmryxix4v64k1j-playwright-browsers-1.27.1.drv' failed to build
> ```
> 
> for x86_64-darwin via [d0bf6d9](https://github.com/NixOS/nixpkgs/commit/d0bf6d9d630fa40f84bec9dc2047761d66116863)

Looks like macOS filesystem nondeterminacy.
cc @SuperSandro2000

**Comment by dotlambda** [comment]
Maybe this has to do with using Rosetta?

**Comment by mweinelt** [comment]
Getting `sha256-KtCkLgDvaVRlbVyhqfiWcx3kSYpKfGP5/DH4FQnnU3w=` via rosetta. Maybe some has access to a native x86_64-darwin machine to confirm? @NixOS/darwin-maintainers

**Comment by yrd** [comment]
I can have a look at the end of next week, but maybe someone else is quicker ;)

**Comment by stephank** [comment]
On `x86_64-darwin`:

```sh
[nix-shell:~/.cache/nixpkgs-review/pr-215873]$ nix-build ./nixpkgs -A python310Packages.playwright.browsers.src
this derivation will be built:
  /nix/store/zdxjpar970s2z1sfslcqc0ca7l3lqapx-playwright-browsers-base.drv
building '/nix/store/zdxjpar970s2z1sfslcqc0ca7l3lqapx-playwright-browsers-base.drv'...
Downloading Chromium 107.0.5304.18 (playwright build v1028) - 125.7 Mb [...snip...]
Chromium 107.0.5304.18 (playwright build v1028) downloaded to /nix/store/1sjxrdfc6yggl23radzjaadgy0nkkca6-playwright-browsers-base/chromium-1028
Downloading FFMPEG playwright build v1007 - 1.1 Mb [...snip...]
FFMPEG playwright build v1007 downloaded to /nix/store/1sjxrdfc6yggl23radzjaadgy0nkkca6-playwright-browsers-base/ffmpeg-1007
Downloading Firefox 105.0.1 (playwright build v1357) - 73.7 Mb [...snip...]
Firefox 105.0.1 (playwright build v1357) downloaded to /nix/store/1sjxrdfc6yggl23radzjaadgy0nkkca6-playwright-browsers-base/firefox-1357
Downloading Webkit 16.0 (playwright build v1724) - 57.8 Mb [...snip...]
Webkit 16.0 (playwright build v1724) downloaded to /nix/store/1sjxrdfc6yggl23radzjaadgy0nkkca6-playwright-browsers-base/webkit-1724
error: hash mismatch in fixed-output derivation '/nix/store/zdxjpar970s2z1sfslcqc0ca7l3lqapx-playwright-browsers-base.drv':
         specified: sha256-KtCkLgDvaVRlbVyhqfiWcx3kSYpKfGP5/DH4FQnnU3w=
            got:    sha256-TzprR95KHYBu9SruI4BgwCaqI7KKe3HuzgCO1A5YFiM=
```

Also, is it intended that there's no hash here for `aarch64-darwin`? https://github.com/NixOS/nixpkgs/blob/95b0856179ba4ac8ef21a5d82b34f6b97c17dd43/pkgs/development/python-modules/playwright/default.nix#L89-L91

**Comment by yrd** [comment]
More or less, I don't have access to an `aarch64-darwin` machine, so it wasn't included in the original PR. Suggestions welcome!

**Comment by stephank** [comment]
So, this appears to work on the platforms natively:

```diff
--- a/pkgs/development/python-modules/playwright/default.nix
+++ b/pkgs/development/python-modules/playwright/default.nix
@@ -87,7 +87,8 @@ let
       outputHashMode = "recursive";
       outputHashAlgo = "sha256";
       outputHash = {
-        x86_64-darwin = "0z2kww4iby1izkwn6z2ai94y87bkjvwak8awdmjm8sgg00pa9l1a";
+        x86_64-darwin = "08qnb07d93h0rvp72ywan8isl9n0c2027viaymp807aavr3nnfjg";
+        aarch64-darwin = "0gapngcn56h7647hhflww048yl45m0l32c2cidl6hajgk81w25az";
       }.${system} or throwSystem;
     } ''
       export PLAYWRIGHT_BROWSERS_PATH=$out
```

But, it appears there's some detection going no when building `x86_64-darwin` via Rosetta, and it's downloading the `aarch64-darwin`  variants in that case. Trouble is that Hydra is already all `aarch64-darwin` hardware using Rosetta. However, I don't think Hydra builds these passthroughs? If it just needs to work for users, then the above diff is fine.

**Review by SuperSandro2000 — APPROVED** [review]
fine for me but I don't have the time to dig into darwin's FS shenanigans

**Comment by dotlambda** [comment]
I get
```
         specified: sha256-TzprR95KHYBu9SruI4BgwCaqI7KKe3HuzgCO1A5YFiM=
            got:    sha256-XxXBA5pPKmhoi0wwMSiohVCPCOCcOggPMQeaYtmzVz0=
```
Let's deal with these hashes in another PR.

**Pull request merged**
