### PR TITLE
tailscale: 1.36.2 -> 1.38.1

### PR DESCRIPTION
**Pull request by drupol**
Link to the release: https://github.com/tailscale/tailscale/releases/tag/v1.38.1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by 06kellyjac — APPROVED** [review]
no upstream 1.37 releases for some reason

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 221279` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tailscale</li>
  </ul>
</details>

**Comment by 06kellyjac** [comment]
I've added the backport label just so we can hopefully keep this up to date with each update rather than block backports

https://github.com/NixOS/nixpkgs/pull/220127#issuecomment-1468676951

**Comment by danderson** [comment]
No 1.37 because odd version numbers are unstable builds for tailscale. Nixpkgs should only expect to see even-numbered versions.

**Review by danderson — APPROVED** [review]

**Comment by 06kellyjac** [comment]
> No 1.37 because odd version numbers are unstable builds for tailscale. Nixpkgs should only expect to see even-numbered versions.

TIL, thanks

I'm surprised I've not noticed that so far

**Pull request merged**
