### PR TITLE
prusa-slicer: Fix STEP format support

### PR DESCRIPTION
**Pull request by mweinelt**
By disabling the automatic wrapping of the GAppsHook we prevent wrapping of the OCCTWrapper.so library, which prevents it from being imported.

Previously the library load would fail on STEP imports like this:

> /nix/store/4j1rm3sqjvfii68kb51ccvynzvll0jna-prusa-slicer-2.5.0/bin/OCCTWrapper.so: cannot dynamically load executable

because when wrapped it is not a library any more.

> OCCTWrapper.so: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/ld-linux-x86-64.so.2, BuildID\[sha1\]=28396fb28c32d0ec7bb75ea5c550760186b86c20, for GNU/Linux 2.6.32, not stripped

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Moredread — CHANGES_REQUESTED** [review]
I think this also changed those attributes for the `super-slicer` packages. While I haven't build it yet, I expect the postFixup step to fail for super-slicer, as the binary has a different name.

Has the library to be in `bin`? I guess that it is installed there by the upstream install script, but is it actually dynamically loaded from there during STEP imports or does it look in the typical paths like LD_LIBRARY_PATHS?

**Comment by mweinelt** [comment]
Looking into whether we can move it out into a better location.

https://github.com/prusa3d/PrusaSlicer/blob/stable/src/libslic3r/Format/STEP.cpp#L38-L43

**Comment by Moredread** [comment]
It looks like the path is hard coded

https://github.com/prusa3d/PrusaSlicer/blob/ec2f533e3a355a2452bf6bd551da84020c69d8f8/src/libslic3r/Format/STEP.cpp#L60-L61

And dlopen(3) says:

```
If filename contains a slash ("/"), then it is interpreted as a (relative or absolute) pathname. Otherwise, the dynamic linker searches for the library as follows (see [ld.so](https://linux.die.net/man/8/ld.so)(8) for further details):
```
I.e. with the relative path specified the dynamic linker step is skipped. We'd either need to patch https://github.com/prusa3d/PrusaSlicer/blob/ec2f533e3a355a2452bf6bd551da84020c69d8f8/src/libslic3r/Format/STEP.cpp#L60 to an equal assignment, so that the dynamic linker is used, and/or we could request a fix from upstream so that it respects the `SLIC3R_FHS flag`.

**Comment by mweinelt** [comment]
I think bringing this to upstreams attention is worthwhile.

**Comment by Moredread** [comment]
I've added the changes to my branch: https://github.com/Moredread/nixpkgs/tree/prusa-slicer-step-fix

**Comment by mweinelt** [comment]
Can you push to this branch or should I pick it?

**Comment by Moredread** [comment]
> Can you push to this branch or should I pick it?

I tried to push to your branch, but it didn't work. I'm not sure if I have configured it correctly.

It would likely be easiest if you pull it. Sorry :(

**Comment by mweinelt** [comment]
No worries.

Basically you have to add my remote `git remote add mweinelt git@github.com:mweinelt/nixpkgs.git`, fetch the branch `git fetch mweinelt prusa-slicer-step-fix` and check it out `git checkout prusa-slicer-step-fix`. Then in theory you should have the correct upstream already configured to push.

**Comment by mweinelt** [comment]
Both prusa-slicer and super-slicer womm. Good to merge?

**Pull request merged**
