### PR TITLE
python3Packages.mediafile: 0.6.0 -> 0.8.0

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 136955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>beets</li>
    <li>beetsExternalPlugins.alternatives</li>
    <li>beetsExternalPlugins.copyartifacts</li>
    <li>beetsExternalPlugins.extrafiles</li>
    <li>python38Packages.mediafile</li>
    <li>python39Packages.mediafile</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 136955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>beets</li>
    <li>beetsExternalPlugins.alternatives</li>
    <li>beetsExternalPlugins.copyartifacts</li>
    <li>beetsExternalPlugins.extrafiles</li>
    <li>python38Packages.mediafile</li>
    <li>python39Packages.mediafile</li>
  </ul>
</details>

**Review by fabaff — COMMENTED** [review]
The module is [Python > 3.6](https://github.com/beetbox/mediafile/blob/master/pyproject.toml#L15). `enum34` could be dropped.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 136955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>beets</li>
    <li>beetsExternalPlugins.alternatives</li>
    <li>beetsExternalPlugins.copyartifacts</li>
    <li>beetsExternalPlugins.extrafiles</li>
    <li>python38Packages.mediafile</li>
    <li>python39Packages.mediafile</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
