### PR TITLE
Jetbrains with plugins: build fix

### PR DESCRIPTION
**Pull request by GenericNerdyUsername**
###### Description of changes

Due to a lack of tests, a patch broke jetbrains ides with declarative plugins. This PR fixes that and adds a simple test to prevent this happening in the future.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pbek** [comment]
Building <https://github.com/NixOS/nixpkgs/pull/244500/commits/cc102eb91666baefab71c1cd715fa1724e751d12> I got:

```
error: output '/nix/store/0zy8scz3i3g1rjsy3l5y4fncw47xrhav-phpstorm-with-plugins-2023.1.4' is not allowed to refer to the following paths:
         /nix/store/cfww2c9vqhi86ic1796k59sh37y8qmkk-phpstorm-2023.1.4
error: 1 dependencies of derivation '/nix/store/6vw08r8qbyyphv1qkg1yp0krq5a1ab25-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/761b8pf975s6cc40y0i0msj458mgwrvq-phpstorm-with-plugins-2023.1.4_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5wlcim5djrfp7x8bbfggjxxvkkv27dim-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xmwk4xgg7293ihjlxz9rzlgssvrvip72-nixos-system-pluto-23.11.20230718.684c17c.drv' failed to build

```

**Review by pbek — APPROVED** [review]
Sorry, that was the first commit. https://github.com/NixOS/nixpkgs/pull/244500/commits/151c175a8528864be449ba30df62ef4c2c93a25d does work! Thank you very much!

**Review by x418 — APPROVED** [review]

**Review by Janik-Haag — APPROVED** [review]

**Review by dritter — APPROVED** [review]

**Comment by Janik-Haag** [comment]
I will merge this since it works fine locally and ci won't run thorough anyways because of unfree packages.

**Comment by pbek** [comment]
Thank you very much everyone!

**Pull request merged**
