### PR TITLE
reposurgeon: init at 3.28

### PR DESCRIPTION
**Pull request by dfoxfranke**
This also packages its (optional) dependencies `cvs-fast-export` and `hglib`.

### CODE REVIEW

**Comment by lethalman** [comment]
The build files because there's no `/usr/bin/env` in the nix-build chroot. You are probably running `nix-build` without chroot enabled. Please enable it.

```
/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash: /tmp/nix-build-cvs-fast-export-1.32.drv-0/cvs-fast-export-1.32/tests/../cvsconvert: /usr/bin/env: bad interpreter: No such file or directory
/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash: /tmp/nix-build-cvs-fast-export-1.32.drv-0/cvs-fast-export-1.32/tests/../cvsconvert: /usr/bin/env: bad interpreter: No such file or directory
/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash: /tmp/nix-build-cvs-fast-export-1.32.drv-0/cvs-fast-export-1.32/tests/../cvsconvert: /usr/bin/env: bad interpreter: No such file or directory
...
```

**Comment by dfoxfranke** [comment]
@lethalman I've enabled chroot and I'm reproducing the failure. I'll look into it this evening.

**Comment by dfoxfranke** [comment]
@lethalman Ok, [0912bdf](https://github.com/dfoxfranke/nixpkgs/commit/0912bdfa925e423106f487dcda0afa5673bb0c59) fixes the `/usr/bin/env` issue. Not sure what's up with the current Travis failure, where it appears to hang after everything's finished — looks like a transient issue on their end? WFM locally.

**Comment by lethalman** [comment]
Built locally thanks.

**Pull request merged**
