### PR TITLE
config.rocmSupport: init option

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes

Add a nixpkgs config option to enable rocmSupport in packages that support it. This is for example useful to get a coherent python package set, when using torch with other dependencies that may otherwise introduce a different torch package.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SomeoneSerge — APPROVED** [review]
I think this change, a global option analogous to `config.cudaSupport`, is a very natural step towards a reasonable level of ROCm support in nixpkgs, and can be merged as is.

We'll also be needing an analogue of `config.cudaCapabilities`, from which we could populate e.g. `gpuTargets` in `torch` whenever `rocmSupport` is `true`.

In future we might want to rename this option and the cuda options for better grouping and to warn users about incompatible combinations. When we get to that, it should be perfectly fine for us to setup the aliases that'd ensure backward compatibility.

CC @NixOS/rocm-maintainers


EDIT: For the sake of avoiding bike-shedding discussions about the exact structure of submodules and interactions betweeen the options, I think we can afford a deprecation cycle

**Comment by Madouura** [comment]
I'm all for this, but I tried to add this in #261578 and we may want to look at the potential pitfalls mentioned there.
cc @lovesegfault

**Comment by Madouura** [comment]
> We'll also be needing an analogue of `config.cudaCapabilities`, from which we could populate e.g. `gpuTargets` in `torch` whenever `rocmSupport` is `true`.

We could probably move ``rocmPackages.clr.passthru.gpuTargets`` to it's own ``.nix`` file like ``cudaPackages`` does.
So we'd have ``rocmPackages_5.rocmCapabilities``, or we could just keep it as ``rocmPackages_5.gpuTargets``.
We could also place it [here](https://github.com/Madouura/nixpkgs/blob/5b347f1fcebcb522b056d9ab9f7c023cc3bfa48a/pkgs/development/rocm-modules/5/utilities.nix) in this very in-dev upcoming PR.

**Review by Madouura — APPROVED** [review]
At any rate, I see no reason this can't be merged as-is.

**Comment by mweinelt** [comment]
> I'm all for this, but I tried to add this in #261578 and we may want to look at the potential pitfalls mentioned there. [`01bcd69` (commits)](https://github.com/NixOS/nixpkgs/commits/01bcd69ed8cb13f38c5fc7cd23a7250b5c594e49) cc @lovesegfault

Making cuda and rocm mutually exclusive is not something I want to get into.

**Comment by ConnorBaker** [comment]
I think having these top-level options to gate features is essential to being able to push down other configuration options into a set of modules (like what I've been working on with #256324).

I adore @SomeoneSerge's idea of eventually moving to a more general `accelerators` attribute set similar to

```nix
config.accelerators.cuda.enable # config.coprocessor, whatever
config.accelerators.cuda.gencodes
config.accelerators.rocm.enable
config.accelerators.rocm.targets
```

because there are so many more wonderful accelerators than just CUDA and ROCm (like Intel's GPUs!).

That said, I think this is great first step!

**Comment by Madouura** [comment]
> I think having these top-level options to gate features is essential to being able to push down other configuration options into a set of modules (like what I've been working on with #256324).
> 
> I adore @SomeoneSerge's idea of eventually moving to a more general `accelerators` attribute set similar to
> 
> ```nix
> config.accelerators.cuda.enable # config.coprocessor, whatever
> config.accelerators.cuda.gencodes
> config.accelerators.rocm.enable
> config.accelerators.rocm.targets
> ```
> 
> because there are so many more accelerators than just CUDA and ROCm (like Intel's GPUs!).
> 
> That said, I think this is great first step!

Agreed. Generalizing the config GPU options (and maybe more?) into ``config.accelerators`` would be preferable to the current situation.

**Comment by Madouura** [comment]
> > I'm all for this, but I tried to add this in #261578 and we may want to look at the potential pitfalls mentioned there. [`01bcd69` (commits)](https://github.com/NixOS/nixpkgs/commits/01bcd69ed8cb13f38c5fc7cd23a7250b5c594e49) cc @lovesegfault
> 
> Making cuda and rocm mutually exclusive is not something I want to get into.

It's just kind of an iffy situation, because the majority of projects I've seen that use cuda or rocm tend to not compile them both.

**Comment by mweinelt** [comment]
Once we make this assertion at the nixpkgs.config level it is hard to get around it, once someone decides to do such an experiment.

I think it's fine to let people hurt themselves trying, or succeed if it's possible.

**Pull request merged**
