### PR TITLE
Submit/new maintainer netforce explorer

### PR DESCRIPTION
**Pull request by NetForceExplorer**
Hello,

the nix package manager is a fascinating project and I want to get involved in the future starting with adding and maintaining grace. As this package derivation is my first contribution ever to an open-source project I value every feedback and criticism even more so I can learn and grow.

### CODE REVIEW

**Comment by Artturin** [comment]
add it as a commit in #134067 instead of in a separate commit

**Comment by davidak** [comment]
@NetForceExplorer welcome!

**Comment by happysalada** [comment]
Welcome!

one more tiny nit if you are interested, but no need to include merge commits from master in a PR. You can just force push your single reworked commit to keep history "cleaner".

**Comment by SuperSandro2000** [comment]
Please cherry-pick the commit into the PR where you are adding yourself as a maintainer to a package. This makes sure all maintainers entries are actually used and we do not collect stale ones.

**Pull request closed without merging**
