### PR TITLE
sweethome3d: 6.2 -> 6.3

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

unfortunately still needs me to manually roll back the mesa version
from 20.0.2 (or 20.0.4) to 19.3.3 as discussed in
https://discourse.nixos.org/t/glx-not-recognised-after-mesa-update/6753

using 'sweethome3.application'

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@raboof so is this WIP, waiting on some fixes in `mesa`?

**Comment by raboof** [comment]
@aanderse it's 'equally broken' for me on 6.2 and 6.3, so I'd say the update and the mesa problem are independent

**Review by aanderse — COMMENTED** [review]
Merging based on the good word of @raboof :+1: 
Thanks @raboof :tada:

**Comment by aanderse** [comment]
@GrahamcOfBorg build sweethome3d

**Pull request merged**
