### PR TITLE
nixos/systemd: Consolidate the wantedBy of user and system units behind a autoStart boolean option

### PR DESCRIPTION
**Pull request by lucasew**
The problem: I have a minecraft server that I don't want to run every time, only when I am going to play with the boys and the module doesn't allow easily to disable the server so it doesn't start automatically. Yeah, there is mkForce in wantedBy but it's less user friendly. This PR fixes that adding the option `autoStart` in all systemd services. It decides automatically if it should add either `multi-user.target` or `default.target`.

**NOTE**: this PR must not change any derivation. It's basically another way to do the same thing. The only difference would be the NixOS test that is basically eval only.

## Things done
- Add `autoStart` option in both system and user services
- Migrated the whole nixpkgs to use it using naive text substitutuion
  - `substituteInPlace nixos/**/*.nix --replace 'wantedBy = [ "default.target" ];' 'autoStart = true;'` for the first commit
  - `substituteInPlace nixos/**/*.nix --replace 'wantedBy = [ "multi-user.target" ];' 'autoStart = true;'` for the second commit
  - substituteInPlace is available in the stdenv so nix-shell any package to enter a shell that provides it, it's safer than plain sed

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353371`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Comment by ElvishJerricco** [comment]
I'm generally against this. First of all, the point about `mkForce` not being user friendly doesn't make sense given that you will still have to `autoStart = mkForce false` to override the module. But also, I don't think it's good to obfuscate something as simple as `wantedBy = [ "multi-user.target" ];` behind an abstraction. It just leads to people not actually understanding what they're seeing and creating more confusion, when the alternative is not an obstruction to anything. Finally, this is a far too unimportant change to be doing tree-wide find-and-replaces on. Every time we do these, something ends up being replaced that shouldn't have been because it's difficult to comprehensively review.

So I disagree with this PR on its premise, on its consequences, and on its method.

**Comment by lucasew** [comment]
Yeah. One would have to use `mkForce false` but that would only change that one entry. If someone adds more than one item to wanredBy it will still be there if autoStart is false.

I found a few targets missreplaced and fixed them tho.

**Comment by arianvp** [comment]
Alternative proposal which aligns more with what upstream does:

Give an option that `install = true / false` that  either processes the `[Install]` section (i.e. the `wantedBy`, `requiredby` optiosn)  in full or not at all.   

It's a bit of a shame that we already  use the option `enable` to `mask` units.   Otherwise I would've proposed naming it `enable`.    (aligning with the upstream terminology).

I think the term `autoStart` is too overloaded.

**Comment by lucasew** [comment]
This name is not final. I can change it. I'm bad at naming things tho.

**Comment by arianvp** [comment]
The problem is not the name. It's the semantics. The point is I'm not fan of `defaultAutostartTarget`.  I think we should have a toggle that enables/disables processing the `wantedBy` and friends sections completely.    Not have an option that modifies `wantedBy`. 

Some untis don't even use `wantedBy` for startup. Some use `upholdsBy` or `requiredBy`.

Hence me suggesting that this option should affect all of them or non at all. 

Similar to how upstream systemd has the https://www.freedesktop.org/software/systemd/man/latest/systemd.preset.html file (which we don't have on NixOS).

If a unit is enabled every option `[Install]` is applied. If it's disabled none is applied.


e.g. your usecase could be done with:

```
systemd.services.minecraft = {
  wantedBy = ["multi-user.target" "some-other-thing.target" ];
  install = false;    # minecraft.service is still on the machine; but the  `multi-user.target.wants.d` and `some-other-thing.target.wants.d` directories don't get a symlink to `minecraft.service`
  script = "my-server";
};
```

**Comment by ElvishJerricco** [comment]
@arianvp I do think a proposal like that makes significantly more sense. Currently we just don't process `[Install]` sections from upstream `systemd.packages` units, and we implement `wantedBy` and friends for nixos-defined units manually. Putting the nixos options in the `[Install]` section and processing it correctly seems wise to me. And I like the idea of units having an `install` or `doInstall` boolean option to control whether this is done. This way the original intent of this PR can still be achieved.

For compatibility's sake, we'd want this to be true by default for nixos-defined units, and we'd want the `generateUnits` script to behave as though it's false for `systemd.packages` units, otherwise we'll get units newly pulled in that weren't before. Over time, we can gradually move away from replicating upstream `[Install]` sections by replacing our manual `wantedBy`s with `doInstall = true`, but I would strongly suggest against trying to automate this conversion tree-wide.

**Comment by lucasew** [comment]
So it seems that this option would be kinda irrelevant because one could just mkForce the stuff out and that would result in the same thing.

**Pull request closed without merging**
