### PR TITLE
python3Packages.nilearn: 0.6.2 -> 0.7.0

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [NA] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104101` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.nilearn</li>
    <li>python38Packages.nilearn</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Fails to build on darwin:
https://termbin.com/byeff

**Comment by bcdarwin** [comment]
@SuperSandro2000 -- I have disabled the single failing test (`test_clean_confounds`) on all architectures as the upstream bug suggests it is quite possibly a numerical issue (https://github.com/nilearn/nilearn/issues/2608).

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104101` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.nilearn</li>
    <li>python38Packages.nilearn</li>
  </ul>
</details>

**Pull request merged**
