### PR TITLE
mbedtls: 2.16.9 -> 2.26.0

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
Progress in the julia packaging (https://github.com/NixOS/nixpkgs/pull/117881) has revealed that nixpkg's version of mbedtls is a few months old. Julia 1.6 now requires >= 2.24.0.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119838` at ac271763 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>belle-sip</li>
    <li>haxe_3_2</li>
    <li>haxe_3_4</li>
    <li>liblinphone</li>
    <li>lime</li>
    <li>linphone</li>
    <li>obs-ndi</li>
  </ul>
</details>
<details>
  <summary>22 packages built successfully:</summary>
  <ul>
    <li>bctoolbox</li>
    <li>belcard</li>
    <li>belr</li>
    <li>bzrtp</li>
    <li>dislocker</li>
    <li>gauche</li>
    <li>gaucheBootstrap</li>
    <li>haxe (haxe_4_2)</li>
    <li>hxcpp (haxePackages.hxcpp)</li>
    <li>haxePackages.hxcs</li>
    <li>haxePackages.hxjava</li>
    <li>haxePackages.hxnodejs_4</li>
    <li>hiawatha</li>
    <li>mbedtls</li>
    <li>mediastreamer</li>
    <li>mediastreamer-openh264</li>
    <li>msilbc</li>
    <li>neko</li>
    <li>ortp</li>
    <li>privoxy</li>
    <li>shadowsocks-libev</li>
    <li>trx</li>
  </ul>
</details>

**Comment by lukegb** [comment]
Can you leave a comment next to the `no auto update` comment indicating that it's disabled due to repology listing dev releases as release versions (from 0ee02a9d42b5fe1825b0f7cee7a9986bb4ba975d) - was wondering if there was some structural reason that had been done.

Otherwise, seems reasonable to me.

**Comment by samuela** [comment]
On my machine (x86-64):
```
> nix-shell -p nixpkgs-review --run "nixpkgs-review pr 119838"
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/119838/head:refs/nixpkgs-review/1
From https://github.com/NixOS/nixpkgs
 + fe938d5ab5f...ac271763167 refs/pull/119838/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/skainswo/.cache/nixpkgs-review/pr-119838/nixpkgs 5cacbc77323d3871c2fbdad33f6f216bd65bfdaf
Preparing worktree (detached HEAD 5cacbc77323)
Updating files: 100% (25459/25459), done.
HEAD is now at 5cacbc77323 Merge pull request #119823 from dotlambda/pytest-subprocess-1.1.10
$ nix-env -f /home/skainswo/.cache/nixpkgs-review/pr-119838/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit ac27176316752d40f61e29f6efbfd9932e384746
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/skainswo/.cache/nixpkgs-review/pr-119838/nixpkgs -qaP --xml --out-path --show-trace --meta
41 packages updated:
bctoolbox belcard belle-sip belr bzrtp dislocker dolphin-emu dolphin-emu gauche gauche-bootstrap haxe haxe haxe hiawatha hxcpp hxcs hxjava hxnodejs liblinphone lime linphone-desktop lutris lutris polarssl (2.16.9 → 2.26.0) mbedtls (2.16.9 → 2.26.0) mediastreamer2 msilbc msopenh264-unstable neko obs-gstreamer obs-move-transition obs-multi-rtmp obs-ndi obs-studio obs-v4l2sink obs-wlrobs ortp privoxy shadowsocks-libev trx yojimbo

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/skainswo/.cache/nixpkgs-review/pr-119838/build.nix
error: builder for '/nix/store/m7hb15a97j5mzlfsl5bqj3vwic5fnyl3-InstallNDISDK_v4_Linux.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       >
       >   https://ndi.tv/sdk/
       >
       > Once you have downloaded the file, please use the following command and
       > re-run the installation:
       >
       >   $ nix-prefetch-url file://$PWD/InstallNDISDK_v4_Linux.tar.gz
       >
       > ***
       >
       For full logs, run 'nix log /nix/store/m7hb15a97j5mzlfsl5bqj3vwic5fnyl3-InstallNDISDK_v4_Linux.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/m8pmsh9l5w1ah8mv58lbcr8dvda27sbx-ndi-4.drv' failed to build
error: builder for '/nix/store/rzzsfw4b3aq2i2vvycfxk072vwdps8md-scout-runtime-0.20201203.1.tar.gz.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://repo.steampowered.com/steamrt-images-scout/snapshots/0.20201203.1/steam-runtime.tar.xz
       > curl: Can't open
       > curl: '/nix/store/0yd9cm656yl63q2wg76il267l9gcnac6-scout-runtime-0.20201203.1.t
       > curl: ar.gz'!
       > curl: (23) Failed writing received data to disk/application
       > error: cannot download scout-runtime-0.20201203.1.tar.gz from any mirror
       For full logs, run 'nix log /nix/store/rzzsfw4b3aq2i2vvycfxk072vwdps8md-scout-runtime-0.20201203.1.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/i13s2dq882k0c02ibxlys2l2wch1ibj3-steam-runtime-0.20201203.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2269pg5x87hizl7qllchajy1r7s8w8hp-steam-runtime-wrapped.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g6s53zsrdlia2q4np3chb3iycmv6a7x4-steam-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vvwm6yzwjbp358msvzxy8947lhhqar9y-obs-ndi-4.9.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p33my824kcshkqmqd1dj19dmn8gxx4hw-steam-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mflgg9vld7hk7zva7zvmvvxd8vssyk3h-steam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4ydlpqzajcm2jkhil6sscj70ab95804h-steam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n91mi1vl30m7h6kkl2s9hr47pi7657mz-lutris-usr-target.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v1jaa0hagapcavjxd336913hyd20f7sy-lutris-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0xf095vw99bqkd4mm3v8nd9z31yyzyxq-lutris.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j3gq6plkvhh8vncdlm066fc2fzi43wmm-lutris.drv' failed to build
error: 2 dependencies of derivation '/nix/store/kjbydgl6kws71lyn24m8ajdw1jn21bgs-env.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/119838

2 packages failed to build:
lutris obs-ndi

38 packages built:
bctoolbox belcard belle-sip belr bzrtp dislocker dolphinEmu dolphinEmuMaster gauche gaucheBootstrap haxe haxePackages.hxcpp haxePackages.hxcs haxePackages.hxjava haxePackages.hxnodejs_4 haxe_3_2 haxe_3_4 hiawatha liblinphone lime linphone lutris-free mbedtls mediastreamer mediastreamer-openh264 msilbc neko obs-gstreamer obs-move-transition obs-multi-rtmp obs-studio obs-v4l2sink obs-wlrobs ortp privoxy shadowsocks-libev trx yojimbo

error: build log of '/nix/store/j3gq6plkvhh8vncdlm066fc2fzi43wmm-lutris.drv' is not available
error: build log of '/nix/store/vvwm6yzwjbp358msvzxy8947lhhqar9y-obs-ndi-4.9.1.drv' is not available
$ nix-shell /home/skainswo/.cache/nixpkgs-review/pr-119838/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-119838]$ 
```

Looks like the obs-ndi failure is due to it requiring a license to be accepted or something. `lutris` seems to be due to a network error.

**Comment by samuela** [comment]
> Can you leave a comment next to the `no auto update` comment indicating that it's disabled due to repology listing dev releases as release versions (from [0ee02a9](https://github.com/NixOS/nixpkgs/commit/0ee02a9d42b5fe1825b0f7cee7a9986bb4ba975d)) - was wondering if there was some structural reason that had been done.
> 
> Otherwise, seems reasonable to me.

Should be resolved in https://github.com/NixOS/nixpkgs/pull/119838/commits/ffe009394a8537c18daffebde3d6ff282b4d196a!

**Comment by OPNA2608** [comment]
This broke compilation on x86_64-darwin for me.

```
building
build flags: -j12 -l12
[1/608] Building C object CMakeFiles/mbedtls_test.dir/tests/src/drivers/size.c.o.oKt.c.o
/nix/store/2pb1r2zgw6yiabv4v3d4j66d3vwgdd5q-clang-wrapper-7.1.0/bin/clang  -I../tests/include -I../include -I../library -Wall -Wextra -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wvla -Wformat=2 -Wno-format-nonliteral -Werror -O2 -MD -MT CMakeFiles/mbedtls_test.dir/tests/src/drivers/size.c.o -MF CMakeFiles/bmedtls_test.dir/tests/src/drivers/size.c.o.d -o CMakeFiles/mbedtls_test.dir/tests/src/drivers/size.c.o -c ../tests/src/drivers/size.c
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
…
ninja: build stopped: subcommand failed.
builder for '/nix/store/86bic0lk75x13sknvbnm9j8935rks12g-mbedtls-2.26.0.drv' failed with exit code 1
```

**Comment by samuela** [comment]
I think this is a clang/gcc flag inconsistency issue. I think I know the fix but I'm stuck unable to install nix on my macbook at the moment (https://discourse.nixos.org/t/installation-issues-on-macos-catalina/12560).

**Comment by samuela** [comment]
@OPNA2608 Ok, I created https://github.com/NixOS/nixpkgs/pull/119923 to resolve the build on x86_64-darwin.

@rmcgibbo Is there any way that we could get darwin/macOS builds on the nixpkgs-review bot in order to mitigate these kinds of issues in the future? I understand macOS machines are not as easy to come by as Linux ones on the cloud, but maybe we could pool resources from community somehow? Or just run a macOS VM inside a linux host? Anyhow, I'd be willing to pitch in to make it happen!

**Comment by rmcgibbo** [comment]
@samuela: This is a great idea, but it's not trivial to pull off. I can prototype a bit on some old / under-powered mac hardware that I have in my closet, but we should discuss better options.

**Pull request merged**
