### PR TITLE
nodePackages.makam: init at 0.7.17

### PR DESCRIPTION
**Pull request by teofr**
###### Motivation for this change
makam is a tool for rapid language prototyping. It's developed by Antonis Stampoulis.

The package is distributed through npm, so this is to have it easily installed in Nix.

More info: https://github.com/astampoulis/makam

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gilligan** [comment]
Hey @teofr , congrats for making your first contribution to nixpkgs :+1: :tada: 
Could you please squash your 2 commits? No need to have the "fix" commit separately.

**Comment by teofr** [comment]
@gilligan thanks, I squashed the two commits.

**Comment by prusnak** [comment]
Please rework your PR. It now has a merge conflict after PR https://github.com/NixOS/nixpkgs/pull/89184 has been merged

**Comment by ryantm** [comment]
merged via https://github.com/NixOS/nixpkgs/pull/100606

**Pull request closed without merging**
