### PR TITLE
[backport] renpy: 7.1.3 -> 7.2.0

### PR DESCRIPTION
**Pull request by erosennin**
###### Motivation for this change

Ren'Py build is currently broken in release-19.03 due to the failing pygame_sdl2 dependency:

https://hydra.nixos.org/build/91927653
https://hydra.nixos.org/build/91927830

This has already been fixed in master by upgrading renpy and pygame_sdl2 to newer versions. Let's backport that.

cc #56826

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build renpy pythonPackages.pygame_sdl2

**Review by worldofpeace — CHANGES_REQUESTED** [review]
@erosennin The commit should be picked with
```
git cherry-pick -xe
```
> https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches
>

**Comment by erosennin** [comment]
@worldofpeace OK, done.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build renpy pythonPackages.pygame_sdl2

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
Thanks @erosennin

**Pull request merged**
