### PR TITLE
processing: 2.2.1 -> 3.3.6

### PR DESCRIPTION
**Pull request by roosemberth**
Signed-off-by: Roosembert Palacios <roosembert.palacios@epfl.ch>

###### Motivation for this change
Update processing version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
Does OpenGL works?
Menu: File -> Example, than SimpleExport

I had to build ```jogl``` from the sources to make it works in https://github.com/NixOS/nixpkgs/pull/36851

**Comment by roosemberth** [comment]
Hi, actually it's not working for me either. I realized when I tryed to run my sketch. I'll close this in favor of #36851

**Comment by volth** [comment]
BTW, what JDK have you used ?
I failed to run in with anything but GraalVM

**Comment by roosemberth** [comment]
oraclejvm, as stated in their website.

**Pull request closed without merging**
