### PR TITLE
python3.tensorflow_2: 2.1.0 -> 2.3.0

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

Make tensorflow available on python3 (the previous version was disabled for python 3.8 and later)

WIP: the build currently fails because it specifically requires Bazel 3.1.0, while nixpkgs ships Bazel 3.3.1.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raboof** [comment]
The build currently fails because it tries to download `rules_cc` during the build:

```
Repository rule tf_http_archive defined at:
  /build/source/third_party/repo.bzl:134:19: in <toplevel>
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package ... (2 packages)
    Fetching @rules_cc; fetching
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_cc/archive/01d4a48911d5e7591ecb1c06d3b8af47fe872371.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: storage.googleapis.com
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package ... (2 packages)
WARNING: Download from https://github.com/bazelbuild/rules_cc/archive/01d4a48911d5e7591ecb1c06d3b8af47fe872371.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: github.com
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package ... (2 packages)
ERROR: An error occurred during the fetch of repository 'rules_cc':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_cc/archive/01d4a48911d5e7591ecb1c06d3b8af47fe872371.zip, https://github.com/bazelbuild/rules_cc/archive/01d4a48911d5e7591ecb1c06d3b8af47fe872371.zip] to /build/output/external/rules_cc/01d4a48911d5e7591ecb1c06d3b8af47fe872371.zip: Unknown host: github.com
Loading: 0 packages loaded
```

**Comment by Wulfsta** [comment]
Does adding 
```
bazel-build = buildBazelPackage {
    ...
    removeRulesCC = false;
    ...
}
```
fix the issue?

**Comment by matthewbauer** [comment]
I have a working version now in https://github.com/NixOS/nixpkgs/pull/95824 ,could you try that out?

**Comment by Wulfsta** [comment]
I don't have a Nvidia card to test with at the moment, but I might be able to try a build later.

**Pull request closed without merging**
