### PR TITLE
minio/minio-client: update

### PR DESCRIPTION
**Pull request by tilpner**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build minio minio-client

**Comment by tilpner** [comment]
**Don't merge yet**, might just be misconfigured, but with the current minio module this causes too many redirects

**Comment by tilpner** [comment]
Previously mentioned bug was reported and is now fixed. Do we wait for the next release or package an intermediate revision?

**Comment by tilpner** [comment]
Uhhh, that is not what I wanted. I'll try to undo it

**Comment by tilpner** [comment]
@GrahamcOfBorg build minio minio-client

**Comment by tilpner** [comment]
All the above noise was because of a git mistake I made. I didn't click any buttons to request a review, or close the PR. Sorry about that.

**Comment by flokli** [comment]
backported to 18.09 in ac184eea4a3 and b690ab173bf

**Pull request merged**
