### PR TITLE
vagrant: 2.1.2 -> 2.2.0 + vagrant-libvirt: init at 2.2.0

### PR DESCRIPTION
**Pull request by calbrecht**
###### Motivation for this change
* Newer vagrant version available.
* libvirt support was already tried to achieve like in  #19202, also this PR partly obsoletes #26202 with the difference that this does not build and install the vagrant-libvirt plugin but enables one to install it by ```vagrant plugin install vagrant-libvirt``` 
###### Things done
* closure size
  * vagrant without libvirt
  ```
  nix path-info -rS $(which vagrant) | awk '{print $2}' | paste -sd+ | bc
  6355939856
  nix path-info -S $(which vagrant) | awk '{print $2}' | paste -sd+ | bc
  252213208
  ```
  * vagrant with libvirt
  ```
  nix path-info -rS $(which vagrant) | awk '{print $2}' | paste -sd+ | bc
  11342383160
  nix path-info -S $(which vagrant) | awk '{print $2}' | paste -sd+ | bc
  551161720
  ```

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip --against 591ba7335bae245733777c1c4eeedb4d34ef57af"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by calbrecht** [comment]
@aneeshusa, @globin please review.

**Comment by calbrecht** [comment]
Perhaps it is not needed/wanted to add the withLibvirt flag and always prepare vagrant to be able to run with libvirt, idk, please advice.

**Comment by lheckemann** [comment]
@GrahamCOfBorg build libvirt vagrant-libvirt

**Comment by calbrecht** [comment]
Like discussed with @globin and @lheckemann i changed the derivation to default to ```withLibvirt = true``` and removed the extra package attribute ```vagrant-libvirt```.

**Comment by Ma27** [comment]
awesome work @calbrecht!

**Comment by lheckemann** [comment]
This does double the closure size of vagrant. Not sure if that's a problem.
```
# before
/nix/store/2kv4z9c3d7p8k3ssvx85wsspfslfhvrd-vagrant-2.1.2         250885416
# after
/nix/store/832z67mz9z1sq6zxh0zym2xyz44s7g7p-vagrant-2.2.0         551210856
```

**Comment by globin** [comment]
I don't think that should be too critical for vagrant since it will never be a light-weight application and it is possible to disable it easily.

**Comment by mat8913** [comment]
How does this work? I tried running `vagrant plugin install vagrant-libvirt`, but I just got
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching: excon-0.62.0.gem (100%)
Fetching: formatador-0.2.5.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: fog-json-1.2.0.gem (100%)
Fetching: mini_portile2-2.3.0.gem (100%)
Fetching: fog-xml-0.1.3.gem (100%)
Fetching: ruby-libvirt-0.7.1.gem (100%)
Building native extensions. This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /home/matthew/.vagrant.d/gems/2.5.3/gems/ruby-libvirt-0.7.1/ext/libvirt
/nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/bin/ruby -r ./siteconf20181215-20807-bw4rki.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
/nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:541:in `try_link0'
	from /nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:559:in `try_link'
	from /nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:661:in `try_ldflags'
	from /nix/store/8wg1if3a1krbwwi85cvkv8xagcrzdsrb-ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:1821:in `pkg_config'
	from extconf.rb:72:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/matthew/.vagrant.d/gems/2.5.3/extensions/x86_64-linux/2.5.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/matthew/.vagrant.d/gems/2.5.3/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/matthew/.vagrant.d/gems/2.5.3/extensions/x86_64-linux/2.5.0/ruby-libvirt-0.7.1/gem_make.out
```

**Comment by booxter** [comment]
@mat8913 with the PR, libvirt plugin is already installed with vagrant itself. But please make sure that you build from master branch of nixpkgs because the PR was not backported to stable.

**Comment by mat8913** [comment]
@booxter I know, I wrote the PR that did that (#52413) :laughing:

**Comment by booxter** [comment]
@mat8913 Epic. Thanks for your work then. :)

**Pull request merged**
