### PR TITLE
Make urbit vera 3.0 be the latest on nixos

### PR DESCRIPTION
**Pull request by JackPala**
Make Urbit Vera 3.0 work with NixOS

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JackPala** [comment]
Did I do this right? I have never contributed before to Nix

**Review by uncenter — CHANGES_REQUESTED** [review]
The title should follow https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions, and the base branch (the branch this PR is merging into) should be `master` not `nixos-23.11`.

**Comment by uncenter** [comment]
Also you should try to check some of the boxes in the pull request template. Some easy ones are: were you able to build it (and on what platform)? Does the compiled binary work? Did you follow the contributing guidelines? Etc.

image

**Comment by pluiedev** [comment]
Result of `nixpkgs-review pr 310890` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>urbit</li>
  </ul>
</details>

**Review by pluiedev — CHANGES_REQUESTED** [review]
Looks like you got the hash for x86_64-linux wrong:
```
error: hash mismatch in fixed-output derivation '/nix/store/qvynrkgbwmg626v2lqq3cb1brbix5cb8-source.drv':
         specified: sha256-wQY3I/HM816vI2NYAvtaYDga64n3nkUEtNd6G8w3hgU=
            got:    sha256-ip35d9YgwFEkNb+1h+8WYBgUm+QlckvHhlAT69TpeYg=
```

**Comment by JackPala** [comment]
> Looks like you got the hash for x86_64-linux wrong:
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/qvynrkgbwmg626v2lqq3cb1brbix5cb8-source.drv':
>          specified: sha256-wQY3I/HM816vI2NYAvtaYDga64n3nkUEtNd6G8w3hgU=
>             got:    sha256-ip35d9YgwFEkNb+1h+8WYBgUm+QlckvHhlAT69TpeYg=
> ```

Those were the hashes I got when I downloaded the zip. What is the best way to get the hash correctly for Nix? I'll go back and I'll do it the right way

**Comment by pluiedev** [comment]
> > Looks like you got the hash for x86_64-linux wrong:
> > ```
> > error: hash mismatch in fixed-output derivation '/nix/store/qvynrkgbwmg626v2lqq3cb1brbix5cb8-source.drv':
> >          specified: sha256-wQY3I/HM816vI2NYAvtaYDga64n3nkUEtNd6G8w3hgU=
> >             got:    sha256-ip35d9YgwFEkNb+1h+8WYBgUm+QlckvHhlAT69TpeYg=
> > ```
> 
> Those were the hashes I got when I downloaded the zip. @pluiedev What is the best way to get the hash correctly for Nix? I'll go back and I'll do it the right way. I am very new to this language..

There's a bunch of different options, in order of convenience (IMO):
- Using [nurl](https://github.com/nix-community/nurl) tool to prefetch the hash. This works great for things like `fetchFromGitHub` where it would essentially give you exactly how `src` should look like, but at the moment it doesn't support `fetchzip`, so you can't use this in this specific case.
- Using [nix-prefetch](https://github.com/msteen/nix-prefetch), which is significantly clunkier to use IMO (I still haven't figured out how to use it myself) but it does support a lot more fetchers than nurl.
- Using the built in [nix-prefetch-url](https://nixos.org/manual/nix/stable/command-ref/nix-prefetch-url.html), which is simple to use but quite annoying as it outputs a base-32 hash instead of the more modern base-64 hash, and there's quite literally no way to change that.
- And finally, not prefetching at all, and just setting the hash to an empty string, `lib.fakeHash`, `lib.fakeSha256` or `sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=`. All of them are equivalent and just supply a fake hash for Nix to validate against. Nix would then tell you the right hash as it tries to build the package, which you then can paste into the expression.

**Comment by oneingan** [comment]
https://github.com/NixOS/nixpkgs/pull/295278

**Pull request closed without merging**
