### PR TITLE
arcanist: 20220517 -> 20230401, switch to PHP 8.1

### PR DESCRIPTION
**Pull request by LeSuisse**
###### Description of changes

It seems that most issues related to PHP 8.1 have been fixed according to the issue tracker: https://secure.phabricator.com/T13588

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>arcanist</li>
  </ul>
</details>

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by Patryk27** [comment]
I can confirm this works on aarch64-darwin as well.

**Comment by LeSuisse** [comment]
Thanks for the confirmation, I'm merging this :tada:

**Comment by Patryk27** [comment]
Uh, I might've been too quick - it looks like `arc diff` can sometime fail 😅 

In my case I've got:

```
Launching editor "vim"...
Supply commit message for uncommitted changes, then save and exit.
Launching editor "vim"...
Provide the details for a new revision, then save and exit.
Linting...
 Exception 
Some linters failed:
    - RuntimeException: strlen(): Passing null to parameter #1 ($string) of type string is deprecated
(Run with `--trace` for a full exception trace.)
```

It looks like the newest-newest version of Arcanist fixes that (they've got a new commit four days ago) :smile:

**Comment by Patryk27** [comment]
kk, lemme just double-check that version works and we'll do

**Pull request merged**
