### PR TITLE
uim: 1.8.6 -> 1.8.6-20180501-git, switch to fetchFromGitHub

### PR DESCRIPTION
**Pull request by oxij**
Because the old version fails to build.

- [X] Typing using this です
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxij** [comment]
@Ericson2314, how do I disable this, but only on aarch64 via meta?

```nix
platforms = filter (p: p != "aarch64-linux") platforms.unix;
```

worked before, but not now after platforms became "patterns".

**Comment by Ericson2314** [comment]
@oxij The easiest thing to do is  
```
meta.broken = stdenv.hostPlatform.isAarch64;
```
And anyways, there's no good reason it *shouldn't* work on that platform, right :)

**Comment by Ericson2314** [comment]
(Otherwise, patterns are just nested attersets, so you can use the `lib.recursiveIForgetExactly` to merge `lib.patterns.{isUnix,isx86}`.

**Comment by oxij** [comment]
> meta.broken = stdenv.hostPlatform.isAarch64;

Added.

> And anyways, there's no good reason it *shouldn't* work on that platform, right :)

Maybe, maybe not. But it is not a maintainer's problem that it (`libgcroots`) doesn't build on aarch64.

**Pull request merged**
