### PR TITLE
virtualbox-guest nixos module: fix VBoxService systemd service

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by lethalman** [comment]
cc @aszlig

**Comment by ts468** [comment]
@aszlig Could you please review the changes?

Maybe https://github.com/NixOS/nixops/issues/332 is related to it.

**Comment by aszlig** [comment]
Thanks, merging this in along with my other changes.

**Comment by ts468** [comment]
@aszlig So I leave it up to you then to merge it together with your other changes. Do you think it could help with the remaining issue in https://github.com/NixOS/nixpkgs/issues/9471 ?

**Comment by domenkozar** [comment]
@ts468 how does error manifest currently?

**Comment by ts468** [comment]
@domenkozar I had problems creating a VirtualBox with nixops, the error was `waiting for IP address` as in https://github.com/NixOS/nixops/issues/332. It seemed as `VirtualBox Guest Services` were not executed within the `http://nixos.org/releases/nixos/virtualbox-nixops-images/virtualbox-nixops-${name}.vdi.xz` image that is provided for the initial deployment, at least when executed on VirtualBox 5.0.4 with host extensions. Within the provided virtuabox-nixops image, `systemd-detect-virt` returned `kvm` instead of the `oracle` that would be required for the systemd `VirtualBox Guest Services` to run. As `VirtualBox Guest Services` is responsible for writing to `/VirtualBox/GuestInfo/Net/1/V4/IP`, nixops hangs with `waiting for IP address`.
With the change of the PR and a locally created `virtualbox-nixops.vid.xz` nixops worked as expected again.

**Comment by domenkozar** [comment]
Awesome, thanks for catching that Thomas. /cc @aszlig @rbvermaa

**Comment by aszlig** [comment]
Okay, I'm going a different route and try to fix (or backport) `systemd-detect-virt`.

**Comment by aszlig** [comment]
Okay, fix is on its way, currently running tests... (could take a while because I need to recompile `qt4`)...

**Pull request closed without merging**
