### PR TITLE
Update cups to 2.0.2

### PR DESCRIPTION
**Pull request by jgeerds**
This is the second attempt to update cups to the latest version. I've tested these changes on my machine and it works fine.

This also solves my issue in detecting remote printers via DNSSD. It doesn't suffice to build `cups-filters` (`cups-browsed`) with DNSSD support. We need to build cups with DNSSD support as well. Otherwise the detected printers won't show up in the web interface.
- update to 2.0.2
- rename `cups.service` to `cupsd.service` because it's the official name and it makes it simpler to reuse official systemd service files thanks to 179acfb664ed06519ac515eada7bbef677cbee87
- refactor meta attributes, remove deprecated config options from cupsd.conf, ...

However, there is still a strange problem with our printing test (already mentioned in #7083 by @vcunat):

```
nix-build nixos/tests/printing.nix
[...]
client: exit status 0
client: must succeed: lpstat -a
client: exit status 0
client: must succeed: lpstat -h server -a
client: exit status 0
error: Died at (eval 13) line 21, <__ANONIO__> line 256.
Died at (eval 13) line 21, <__ANONIO__> line 256.
cleaning up
killing client (pid 4437)
killing server (pid 4447)
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: Could not remove ctl dir '/tmp/nix-build-vm-test-run-printing.drv-0/vde1.ctl': Directory not empty
builder for ‘/nix/store/q1kvd0km864cr5cd790x3yki4z5j39qj-vm-test-run-printing.drv’ failed with exit code 255
error: build of ‘/nix/store/q1kvd0km864cr5cd790x3yki4z5j39qj-vm-test-run-printing.drv’ failed
```

```
      $client->succeed("lpstat -a") =~ /DeskjetRemote accepting requests/ or die;
      $client->succeed("lpstat -h server -a") =~ /DeskjetLocal accepting requests/ or die;
```

The second line let our test fail. If I replace `/DeskjetLocal accepting requests/` with `/DeskjetRemote accepting requests/` (like one line above) then the test doesn't fail. I don't understand the problem here because if I run this test manually then the output looks good to me. It should work.

I think this is a Perl related issue or something like that? Any idea?

CC: @wkennington @edolstra

### CODE REVIEW

**Comment by geerds** [comment]
I didn't know that `Died at (eval 13) line 21, <__ANONIO__> line 256` just mean that a test is failed. I thought it's a Perl related issue or something like that. Anyway, I've found the reason and fixed the test.

It seems like there's an upstream bug in the "lpstat" command. We need
to specify the server's port.

Further information: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=711327
```
[root@client:~]# lpstat -H
/var/run/cups/cups.sock

[root@client:~]# lpstat -h server -H
/var/run/cups/cups.sock:631

[root@client:~]# CUPS_SERVER=server lpstat -H
server:631

[root@client:~]# lpstat -h server:631 -H
server:631
```

@domenkozar

**Comment by domenkozar** [comment]
@kirelagin renamed cupsd to cups, so we have to decide :)

**Comment by kirelagin** [comment]
> This also solves my issue in detecting remote printers via DNSSD. It doesn't suffice to build `cups-filters` (`cups-browsed`) with DNSSD support. We need to build cups with DNSSD support as well. Otherwise the detected printers won't show up in the web interface.

I’m not really sure about this, but this sounds suspicious. All `cups-browsed` does is add a remote IPP printer. Why would CUPS need avahi to use it, when it’s just IPP?

**Comment by kirelagin** [comment]
> rename `cups.service` to `cupsd.service` because it's the official name

What do you mean by _official name_?

It seems that CUPS started shipping systemd units with 2.0, that’s great. In this case we should try to use their units as much as possible. But the _official name_ in this case is `org.cups.cupsd.service`, not `cupsd.service`.

There are two ways to proceed with the naming issue.

*   Stick to the upstream name `org.cups.cupsd.service`. That’s :scream_cat: but [Apple doesn’t care](http://cups.org/pipermail/cups-devel/2014-October/015372.html).

    * Arch [decided](https://bugs.archlinux.org/task/42231#comment128929) to go this way.

*   Do as everyone else does — rename it to `cups.service` to save extra typing.

    * [Fedora](http://pkgs.fedoraproject.org/cgit/cups.git/tree/cups.spec?id=48ae2e18ed65b87a31695e2b2625772ad154a18d#n332)
    * [Gentoo](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/net-print/cups/files/cups-2.0.2-rename-systemd-service-files.patch)
    * Debian (no idea how their packaging works, so the best link I have is [this Changelog](http://metadata.ftp-master.debian.org/changelogs//main/c/cups/cups_2.0.2-2_changelog))

**Comment by geerds** [comment]
@domenkozar I think he renamed `cupsd.service` to `cups.service` because our `cups-browsed.service` already used `cups.service` in the `wants` and `after` section.

@kirelagin I didn't know that Fedora, Gentoo and Debian uses `cups.service`. I renamed the service because I use some parts of the official systemd files provided by CUPS. I find it simpler to strip of `cups.org.` from the beginning of the filenames instead of strip of `cups.org.` **and** rename it to `cups.service`:

```
-r--r--r-- 4 root nixbld 113 Jan  1  1970 org.cups.cupsd.path
-r--r--r-- 2 root nixbld 227 Jan  1  1970 org.cups.cupsd.service
-r--r--r-- 4 root nixbld 116 Jan  1  1970 org.cups.cupsd.socket
-r--r--r-- 2 root nixbld 201 Jan  1  1970 org.cups.cups-lpd@.service
-r--r--r-- 4 root nixbld 115 Jan  1  1970 org.cups.cups-lpd.socket
```

but sure I can rename the service back to `cups.service` :)

I don't know the reason for the avahi stuff. All I know is that CUPS doesn't show up my printer in the web interface even if `cups-browsed` finds these printers according to the logs.

```
    printing.browsedConf = ''
      CreateIPPPrinterQueues Yes
    '';
```

This option is my current workaround. Printers found by `cups-browsed` are automatically added to CUPS. They're not in the "Discovered remote printers" section in CUPS' web interface but rather directly added to the configured printers. You can also change the configuration of these printers (e.g. PPD file) **but** as soon as the printer disappeared (e.g unplug it), CUPS will forget the printer's configuration. This option is only designed for temporary printers with automatic configuration. You don't even need a matching PPD file for the printer because it uses some kind of generic interface. However, not all printers support this method.

When I build CUPS with avahi this problem is solved. CUPS find **all** my printers and they're show up in the web interface. Printer configuration is also persistent.

I think this is the reason why Debian, Arch Linux and co build CUPS with avahi as well.

**Comment by geerds** [comment]
I'll fix the service name in a few hours and clean up the history.

**Comment by geerds** [comment]
I've renamed the service back to `cups.service` and cleaned up the history. To be sure I've tested the current state again on my local machine (took some time to rebuild qt and so on :sleeping: )

Should be ready to merge

**Comment by geerds** [comment]
I've rebased the PR against our current nixos-unstable release and added the `defaultShared`, `browsing` and `webInterface` configuration options.

**Comment by geerds** [comment]
Oh and a short changelog entry :smiley:

**Comment by kirelagin** [comment]
Otherwise :+1: :exclamation:

**Comment by geerds** [comment]
I'll merge this PR in the next 24 hours. Last chance to say something about it

**Comment by kirelagin** [comment]
:cool: stuff, bro! :sunglasses:

**Comment by kirelagin** [comment]
happy_printer

**Comment by domenkozar** [comment]
Tested (ran printing test) and pushed to master. More user testing shall be done by early adopters of master branch.

**Comment by geerds** [comment]
:beers:

**Comment by domenkozar** [comment]
Hmm, there are some errors in tests: http://hydra.nixos.org/build/22117790/nixlog/31/raw

I didn't see that when I tested locally

**Comment by kirelagin** [comment]
Do those errors have anything to do with CUPS at all?

**Comment by kirelagin** [comment]
So what happens is it tries to print `cups.png` ensures that the file is spooled, invokes `lpq -a` which succeeds and then it should call `lprm` to remove the job but I can’t tell from the log what actually happens. Anyway, the subtest fails and it proceeds to the next one: prints `pcre.txt`, runs `lpq` and then fails at the `waitForFile` step.

Is there a way to find out what _actually_ failed? The log is not very helpful :disappointed:.

**Comment by geerds** [comment]
I'll look into it but the error message isn't really helpful

**Comment by domenkozar** [comment]
Best to setup and try locally - note that this is now blocking channel update.

**Comment by geerds** [comment]
Fixed: http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents

**Pull request closed without merging**
