### PR TITLE
coreterminal: init at 4.2.0

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dan4ik605743** [comment]
@SuperSandro2000 So, everything did it.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130737` at 2c7919b8 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/7cb48b30a470ac331177602b59a7aa7d">coreterminal</a></li>
    <li><a href="https://gist.github.com/e854f60661dcec251a0dc34373018a85">libcprime</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please do one commit per package.

**Comment by dan4ik605743** [comment]
> Please do one commit per package.

Understood

**Comment by dan4ik605743** [comment]
@SuperSandro2000 Ready!

**Comment by SuperSandro2000** [comment]
I meant one commit for libcprime and one for coreterminal.

**Comment by dan4ik605743** [comment]
> I meant one commit for libcprime and one for coreterminal.

A..On again rearranged PR

**Comment by dan4ik605743** [comment]
@SuperSandro2000 Done.

**Pull request merged**
