### PR TITLE
jackett: 0.21.1588 -> 0.21.1658

### PR DESCRIPTION
**Pull request by XenGi**
## Description of changes

Changelog: https://github.com/Jackett/Jackett/releases/tag/v0.21.1658

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by h7x4** [comment]
Hello @XenGi, welcome to nixpkgs!

We have a few [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) to ensure a clean git history. Could you redo the commit message to say `jackett: 0.21.1588 -> 0.21.1658` (and maybe the PR title as well)?

**Comment by h7x4** [comment]
Compare changes: https://github.com/Jackett/Jackett/compare/v0.21.1588...v0.21.1658
Release notes: https://github.com/Jackett/Jackett/releases

Doesn't seem like any of the deps has been updated, nor anything else that would need us to change the build instructions, so hash bump only is probably fine.

**Review by yayayayaka — APPROVED** [review]

**Comment by XenGi** [comment]
Thx for the help @h7x4 and thx for merging @yayayayaka. One last question, how does this end up in 23.11 and unstable?

**Comment by yayayayaka** [comment]
See [CONTRIBUTING.md#flow-of-merged-pull-requests](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#flow-of-merged-pull-requests).

In short, they become available once built by the CI. For 23.11, it also needs to be backported to the `release-23.11` branch. The status of merged PRs can be tracked via [PR tracker](https://nixpk.gs/pr-tracker.html?pr=285679)

**Pull request merged**
