### PR TITLE
pythonPackages.atom: init at 0.4.1

### PR DESCRIPTION
**Pull request by bhipple**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bhipple** [comment]
@GrahamcOfBorg build python2Packages.atom python3Packages.atom

**Comment by bhipple** [comment]
I spent a long while trying to figure out how to get it to run the tests; it seems to still be running them but not find anything?  

Seems upstream is using `py.test`, but they also have a `Makefile` deployed, which I think is why the build function is getting confused?
https://github.com/nucleic/atom/blob/master/.travis.yml#L31

**Comment by costrouc** [comment]
It is running `py.test` but the pypi release did not include the `tests` so none are run see contents of [0.4.1 release](https://files.pythonhosted.org/packages/21/8d/a4edf3f7b8a93e8d20f6dba989f49469b002f63fc372ae331d6223a9437b/atom-0.4.1.tar.gz) also at https://pypi.org/project/atom/#files. This is common that users don't package the tests in the release.

**Comment by bhipple** [comment]
Indeed, I had tried using `fetchFromGitHub` instead of `fetchPypi`, and while that does indeed include the tests in the tarball it still wasn't running them.

**Pull request merged**
