### PR TITLE
deepin-image-viewer: init at 1.2.23

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Add [deepin-image-viewer](https://github.com/linuxdeepin/deepin-image-viewer) (Image Viewer for Deepin Desktop Environment).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
@GrahamcOfBorg build deepin.deepin-image-viewer

**Comment by xeji** [comment]
Please have a look at the aarch64 failure.

**Comment by romildo** [comment]
@GrahamcOfBorg build freeimage

**Comment by romildo** [comment]
@GrahamcOfBorg build freeimage

**Comment by romildo** [comment]
@GrahamcOfBorg build deepin.deepin-image-viewer

**Comment by romildo** [comment]
> Please have a look at the aarch64 failure.

This compilation error message is:

```
/nix/store/8pr84c6dgljrjafzw3bqqc1246avy52f-freeimage-3.18.0/lib/libfreeimage.so: undefined reference to `png_init_filter_functions_neon'
```

It seems that in the `libpng` package (which is bundled with `freeimage') `neon` is not available on the platform, but is detected as being available.

I tried to upgrade to `freeimage-1.18.0`, which does not seem to fix this issue, and also does not build on darwin (I do not have a darwin system to test).

All distributions I have looked at unbundle the system libraries (like `png` and others) from `freeimage`. Maybe this is something that the maintainer could look at. 

cc @viric

**Comment by xeji** [comment]
Thank you for investigating.  So let's merge the new package `deepin-image-viewer` (without updating `freeimage`) now, and aarch64 can be fixed later.

**Comment by xeji** [comment]
applied https://github.com/NixOS/nixpkgs/pull/46463/commits/e9e4cac457c2bec2b689debfea7180f29e74efa0 to master as  5efede93d2707b0b4a28366f6f13ae053a3447e4.

**Pull request closed without merging**
