### PR TITLE
buildPythonPackage: add support for setupPyGlobalFlags (2)

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
I think this is a good time to also rename the two options to get rid of the `setupPy` part.

**Review by abbradar — APPROVED** [review]
Small moment: the commit message is still about `setupPyDistFlags` ;)

Didn't actually test it now because I'll die rebuilding all the world _and_ Tensorflow. Testing it on `virt-manager` would be easier. @aske?

**Comment by abbradar** [comment]
BTW we'll also need to test pyproject-using packages with flags - maybe they actually needed global flags all along.

**Comment by FRidh** [comment]
There are not that many upstreams that already use `pyproject`, let alone those that require these flags.

**Comment by FRidh** [comment]
I would like to rename the options to `buildOptions`, `globalOptions` and `installOptions` to match with `pip`. This will however break backwards compatibility for `setupPyBuildFlags` and `installFlags`.

**Comment by abbradar** [comment]
Sounds good to me! We could leave old options too but with `builtins.trace` for a while, to give people time to move.

**Comment by FRidh** [comment]
Some bike-shedding: `Options` or `Flags`? The latter is used more commonly in Nixpkgs, but the former matches with pip.

**Comment by abbradar** [comment]
I'd say `Options` because otherwise we'll have collisions with `buildFlags` etc from autoconf/make-based builds, and we may want to use both for.... I'm not sure we actually want to :D

**Comment by abbradar** [comment]
Anyway, `buildOptions` is better to be visibly different from usual `buildFlags` so people distinguish them easier.

**Comment by FRidh** [comment]
I will keep the renaming for another time.

**Pull request merged**
