### PR TITLE
odbc: begin generalizing over different driver managers

### PR DESCRIPTION
**Pull request by Profpatsch**
- [x] built on nixos
- [x] checked mssql .so with `ldd`
- [x] activated new functionality on system and tested various combinations
- [x] tested that the assertions fire

ODBC drivers are managed by driver managers. Driver managers provide the same
ABI, but driver’s shared objects need to have their dm’s .so baked in.

The nixos module is changed to allow choosing between the older unixODBC dm and
libiodbc. The drivers are then compiled with the correct references.

Additionally, this adds the non-free mssql driver (too many changes, it’s hard
to put in a separate commit).

### CODE REVIEW

**Comment by Profpatsch** [comment]
I added two more commits that change the interface somewhat. Some external input about the API would be nice nonetheless.

**Comment by Profpatsch** [comment]
Anyone willing to review?

**Comment by knedlsepp** [comment]
I'm also currently coming to the conclusion that there is currently a bit of a mixture of libiodbc and unixodbc, which causes me pain on a non-NixOS installation, since they are based on different environment variables to specify the drivers.
I think your effort is great! Do you think that this could also be done without nixOS-modules? I'd love to make this work also on non-nixOS.

**Review by Profpatsch — COMMENTED** [review]
> Do you think that this could also be done without nixOS-modules?

It’s been a while so I don’t remember the whole setup in this PR, but e.g. in [the last argument of the MS ODBC package](https://github.com/NixOS/nixpkgs/pull/20960/files#diff-228143944a0d290d4c035df721aec06b) you can see there is a way to override the driver on a package level (aka. a level that doesn’t need modules).

**Comment by Profpatsch** [comment]
I’m sad to see this work go to waste, but I don’t use ODBC at the moment, so let’s close this PR for now.

**Pull request closed without merging**
