### PR TITLE
python3Packages.denonavr: 0.9.10 -> 0.10.6

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.10.5

Change log: https://github.com/scarface-4711/denonavr/releases/tag/0.10.6

- Related Home Assistant change: https://github.com/home-assistant/core/pull/49984
- Target Home Assistant release: 2021.5.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Check if you can enable the tests. The package bump was https://github.com/home-assistant/core/pull/47920 and came with a bunch of code changes moving the component to async.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121153` at ab012688 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>python38Packages.async-lru</li>
    <li>python38Packages.denonavr</li>
    <li>python39Packages.async-lru</li>
    <li>python39Packages.denonavr</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Looks like we could enable the tests after Home Assistant 2021.5.

**Comment by mweinelt** [comment]
Let's drop async-lru and updated to https://github.com/scarface-4711/denonavr/releases/tag/0.10.6.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 121153` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.asyncstdlib</li>
    <li>python38Packages.denonavr</li>
    <li>python39Packages.asyncstdlib</li>
    <li>python39Packages.denonavr</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
Test failures are unrelated.

**Pull request merged**
