### PR TITLE
slskd: 0.21.3 -> 0.21.4

### PR DESCRIPTION
**Pull request by melvyn2**
## Description of changes
https://github.com/slskd/slskd/releases/tag/0.21.4
Some fixes involving user blocklists, and updates to dependencies on the frontend.
Nothing worthy of a changelog note here.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by melvyn2** [comment]
Thanks @getchoo for merging the two derivations into a single one

**Review by getchoo — APPROVED** [review]
Result of `nixpkgs-review pr 344958` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>slskd</li>
  </ul>
</details>

```console
$ nix-build nixpkgs -A slskd.passthru.tests
this derivation will be built:
  /nix/store/wgcgazp59ppcvflipyzfklrd7hr3nllg-slskd-0.21.4-test-version.drv
building '/nix/store/wgcgazp59ppcvflipyzfklrd7hr3nllg-slskd-0.21.4-test-version.drv'...
0.21.4 (0.21.4)
/nix/store/3xq8d8ar2a0qadvllvp8s3r62g2gfa88-slskd-0.21.4-test-version
```

**Comment by ppom0** [comment]
Looks very good to me. I'm curious, why merging the derivations? Thanks!

**Review by ppom0 — APPROVED** [review]

**Comment by getchoo** [comment]
> I'm curious, why merging the derivations?

It's mainly to simplify the expression, but also make it a bit more efficient by not having basically two versions of the web frontend made during the build (along with the other overhead of a derivation duplicated like fixup phase, stripping, evaluation, etc)

**Review by fpletz — APPROVED** [review]

**Comment by melvyn2** [comment]
Oops, forgot that https://github.com/NixOS/nixpkgs/pull/334090 hasn't been merged yet

**Comment by melvyn2** [comment]
Ah, 2641d97cbf96e0b4caf1733edc47cf1298de0960 isn't in `release-24.05`... I'll make a manual PR

**Pull request merged**
