### PR TITLE
qemu: fix wrong localstatedir

### LINKED ISSUE #113909: QEMU Agent module on unstable is broken
**Describe the bug**
The QEMU Agent NixOS module cannot work properly as the `statedir` is incorrectly set.

**To Reproduce**
1. Run the QEMU Agent NixOS on latest version.
2. See failure of the unit.
3. Also, `nix-shell -p qemu.ga --run "qemu-ga --help"` proves the same thing.

**Expected behavior**
Either, the package does not embed the Nix path in the configuration, either it is passed `-t` to the module.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.16-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixpkgs-21.05pre271547.a964d7094a3"`
 - channels(raito): `"nixpkgs-21.05pre271547.a964d7094a3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
attribute: qemu.ga
module: services.qemuGuest
```

cc @andir @teto

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Motivation for this change
Closes https://github.com/NixOS/nixpkgs/issues/113909

###### Things done

Not sure if this is the fix and I couldn't test it as the build runs out of space. 

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

The easiest way to see if the fix worked is to use 
`nix-build -A nixosTests.qemu-guest-agent`

### CODE REVIEW

**Comment by SCOTT-HAMILTON** [comment]
If this doesn't work, we can always use this fix
```patch
diff --git a/nixos/modules/virtualisation/qemu-guest-agent.nix b/nixos/modules/virtualisation/qemu-guest-agent.nix
index 6a735f451a7..b6caaa7be1d 100644
--- a/nixos/modules/virtualisation/qemu-guest-agent.nix
+++ b/nixos/modules/virtualisation/qemu-guest-agent.nix
@@ -30,7 +30,7 @@ in {
       systemd.services.qemu-guest-agent = {
         description = "Run the QEMU Guest Agent";
         serviceConfig = {
-          ExecStart = "${cfg.package}/bin/qemu-ga";
+          ExecStart = "${cfg.package}/bin/qemu-ga -t /var/run";
           Restart = "always";
           RestartSec = 0;
         };
```

**Comment by sorki** [comment]
I'm testing this with simplified version of the test from https://github.com/NixOS/nixpkgs/issues/113909#issuecomment-783412094 w/o `serviceConfig.ExecStart` wrapper and getting 

```
qemu-ga[748]: 1614073191.10500: critical: unable to create state file at path /var/run/run/qga.state
```

Looking at code I'm no wiser what is happening but found a [socket activation example](https://github.com/qemu/qemu/commit/26de229657b943b7a59ad79c387506f6f33ff963) in one of the older commits which might be worth integrating.

It might be easier to avoid fiddling with `CONFIG_QEMU_LOCALSTATEDIR` and just pass flags via `ExecStart` but fixing the root cause would possibly fix two other uses of it in `tools/virtiofsd/fuse_virtio.c` and `scsi/qemu-pr-helper.c` (via `qemu_get_local_state_pathname` pathname).

**Comment by SCOTT-HAMILTON** [comment]
@sorki I've implemented the socket activation example, could you try it and maybe gist the full logs?

**Comment by sorki** [comment]
Here you go https://gist.github.com/sorki/01da186d0b07b00aa6427e5929698fc9

I've had to remove `-l /var/run/qga.log` as that hides the error output to file.

**Comment by SCOTT-HAMILTON** [comment]
Ok, I understand the state file is written to localstatedir/relative_statedir/qga.state, with some random suffix-extensions with
localstatedir=/var/run and relative_statedir = run see https://github.com/qemu/qemu/blob/master/qga/main.c#L50.
So either I change localestatedir to /var or I set relative_statedir to "". I'll patch against the first option and let you try it.

**Comment by sorki** [comment]
Test passes now though there is

`machine # [    4.111376] systemd[1]: /nix/store/85z84afn6d2fkmr4swimvl3fnzhmq0r8-unit-qemu-guest-agent.socket/qemu-guest-agent.socket:6:` `ListenStream= references a path below legacy directory /var/run/, updating /var/run/qga.sock → /run/qga.sock; please update the unit file accordingly.`

**Comment by SCOTT-HAMILTON** [comment]
I guess the fix is easy.

**Comment by SCOTT-HAMILTON** [comment]
The test seems to pass without any error or warning. Though I had to build it with ccache, as I couldn't wait 2h for each build. Now it takes ~10min. I think it's ready for reviewing.

**Comment by SCOTT-HAMILTON** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/112886.

**Pull request closed without merging**
