### PR TITLE
ghc prebuilt: Add 7.8.4, 7.10.3 and 8.2.1, and make consistent style

### PR DESCRIPTION
**Pull request by domenkozar**
Builds on top of https://github.com/NixOS/nixpkgs/pull/29688 and addresses the blocker to build ghcs on linux.

### CODE REVIEW

**Comment by domenkozar** [comment]
@GrahamcOfBorg build ghc6102Binary ghc7103Binary ghc821Binary ghc784Binary

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.compiler.ghc6102Binary haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by domenkozar** [comment]
Huh, it works for me locally:

```
$ nix-build -A haskell.compiler.ghc7103Binary
/nix/store/z3k8y3x9hdz1m2a3c002z21qi7hlly5v-ghc-7.10.3-binary
```

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by LnL7** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by domenkozar** [comment]
I consider this ready, it builds on my darwin machine. Once this is merged I can replace the boot packages and ghc for sets and thus get rid of long current ghc cycles.

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by LnL7** [comment]
@GrahamcOfBorg build haskell.compiler.ghc7103Binary haskell.compiler.ghc821Binary haskell.compiler.ghc784Binary

**Comment by Ericson2314** [comment]
Yayayayay thanks for finishing! This should be staging, or @peti's staging branch though?

**Comment by peti** [comment]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates.

**Comment by domenkozar** [comment]
@peti seems to not break anything. I have a follow-up PR that wires up boot packages (and thus removes long ghc chain). But currently ghcjs fails on master: https://hydra.nixos.org/job/nixpkgs/trunk/haskell.compiler.ghcjs.x86_64-linux

I think we should add `haskell.compiler` to the release set when testing new changes.

**Comment by domenkozar** [comment]
@peti also let me know if you'd like to include changing of bootstrapped ghc in this PR or as a separate thing. I have changes ready. There are no regressions, but some older and very new GHCs fail to build, prior to the change.

**Comment by peti** [comment]
@domenkozar, I'd prefer to merge the additional changes in a separate PR. Let's make small, continuous steps. If something goes wrong, a sequence of small incremental is easier to bisect and to find the cause of the issue.

**Pull request merged**
