### PR TITLE
azure-cli: 0.10.17 -> 2.0.27

### PR DESCRIPTION
**Pull request by lamdor**
###### Motivation for this change

The azure-cli that was here before was very outdated. It's now written in python3 and has a mess of new python packages.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks for the PR. This is a huge change, and would be very hard to maintain I'm afraid. How do you plan to maintain this?

**Comment by colemickens** [comment]
I'm also curious how you made this change. I've not been able to get `pypi2nix` to work with it, and I'm interested in having this available and possibly maintaining.

**Comment by rubbish** [comment]
Yeah, I agree that this will be painful to maintain. The way I created them was a lot of checking pypi.org for packages and figuring out the dependencies from there. It took a few hours. I would've liked to have to tried pypi2nix, but I also couldn't get it to work, but I'm a python noob.

I'll come back to this and see figure out some path forward.

**Comment by colemickens** [comment]
cc: @garbas for any input/suggestions, also ref: https://github.com/garbas/pypi2nix/issues/194

**Comment by flokli** [comment]
Has the situation gotten any better? `azure-cli` is at 2.0.61 by now…

**Comment by matthiasbeyer** [comment]
This is stalled and should probably be closed. @FRidh

**Comment by jonringer** [comment]
the azure-{,mgmt}-* packages have been added by #60435 (rotting a huge portion of this PR)

recently, the azure-cli consolidated/flattened a lot of their namespace packages into the azure-cli package https://github.com/Azure/azure-cli/pull/9590

Also, the azure-cli is meant to be a "flexible" interactive tool, in which the surface API isn't stable at all. See https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest for "removed" or "BREAKING CHANGE" entries.

At the very least, I would recommend closing this ticket @FRidh

**Comment by flokli** [comment]
Let's close this, we can always resume from what's in this PR. Thanks!

**Pull request closed without merging**
