### PR TITLE
vala_0_26: remove

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

get rid of old vala version
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

**imho it's very advisable to use all gnome packages from the same package set to ensure they are compatible and avoid depending on two different builds of the same package**

when vanubi is updated to compile with a current vala, https://github.com/NixOS/nixpkgs/commit/c82b9738fbc747d55445b369177042f21918b472 should be reverted.

@lethalman for vanubi

### CODE REVIEW

**Review by fpletz — APPROVED** [review]

**Comment by lethalman** [comment]
The next gnome release those packages will probably break due to a Vala upgrade.

**Comment by lethalman** [comment]
See https://github.com/NixOS/nixpkgs/pull/17898 . Closing this.

**Comment by groxxda** [comment]
@lethalman we can nevertheless get rid of vala 0.26 ;-)

**Comment by lethalman** [comment]
@groxxda sure feel free to send a PR only for that

**Pull request closed without merging**
