### PR TITLE
nodePackages.musescore-downloader: init

### PR DESCRIPTION
**Pull request by legendofmiracles**
###### Motivation for this change
Updates all nodePackages as well

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131382` at 5179b72d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/425b3f5e2f38d9919ca409d5eaf6af37">timedoctor</a></li>
  </ul>
</details>
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>lumo</li>
    <li>n8n</li>
  </ul>
</details>
<details>
  <summary>32 packages built successfully:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>castnow</li>
    <li>create-cycle-app</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flood</li>
    <li>fx</li>
    <li>hyperspace-cli</li>
    <li>joplin</li>
    <li>mirakurun</li>
    <li>mx-puppet-discord</li>
    <li>netlify-cli</li>
    <li>nixos-install-tools</li>
    <li>parity-ui</li>
    <li>postcss-cli</li>
    <li>redoc-cli</li>
    <li>slack</li>
    <li>teams</li>
    <li>teleprompter</li>
    <li>thelounge</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-git</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>zerobin</li>
  </ul>
</details>
<details>
  <summary>26 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:71081:5:
```
      |
71081 |     version = "0.6.0";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

nodePackages.node-pre-gyp is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:402:7:
```
    |
402 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

nodePackages.node-gyp-build is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:402:7:
```
    |
402 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/node-packages/node-env.nix:451:7:
```
    |
451 |       meta = {
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:106802:5:
```
       |
106802 |     version = "0.12.2";
       |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:84926:5:
```
      |
84926 |     version = "4.6.1";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:66178:5:
```
      |
66178 |     version = "2.3.4";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:69359:5:
```
      |
69359 |     version = "10.7.1";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:97089:5:
```
      |
97089 |     version = "5.2.3";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:114837:5:
```
       |
114837 |     version = "4.2.0";
       |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `nix-gitignore`.
Near pkgs/development/node-packages/node-packages.nix:3:31:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                               ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:85359:5:
```
      |
85359 |     version = "20.0.2";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:82674:5:
```
      |
82674 |     version = "3.0.1";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:96481:5:
```
      |
96481 |     version = "3.7.0";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/development/node-packages/node-env.nix:451:7:
```
    |
451 |       meta = {
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:104040:5:
```
       |
104040 |     version = "8.3.1";
       |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/node-packages/node-env.nix:410:14:
```
    |
410 |       inherit dontNpmInstall preRebuild unpackPhase buildPhase;
    |              ^
```
</li>
    <li>warning: unused-argument

Unused argument: `stdenv`.
Near pkgs/development/node-packages/node-packages.nix:3:46:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                                              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:66678:5:
```
      |
66678 |     version = "2.0.0";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall`.

Near pkgs/development/node-packages/node-env.nix:417:7:
```
    |
417 |       installPhase = ''
    |       ^
```
</li>
    <li>warning: unused-argument

Unused argument: `lib`.
Near pkgs/development/node-packages/node-packages.nix:3:54:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                                                      ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:75813:5:
```
      |
75813 |     version = "5.0.0";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:89904:5:
```
      |
89904 |     version = "2.1.2";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

util-linux is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:402:7:
```
    |
402 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by legendofmiracles** [comment]
I want to add another node-package - is it ok if I close and then reopen this PR with the other package added as well. If I don't the generated node-packages.nix file will be completely broken and require me to resolve dozens of merge conflicts.

**Comment by SuperSandro2000** [comment]
and merge conflict.

**Comment by legendofmiracles** [comment]
Fixed @SuperSandro2000

**Pull request merged**
