### PR TITLE
xtensor & xsimd updates

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
I checked this change upon master at https://github.com/NixOS/nixpkgs/pull/312745, and CI is even green for x86_64-linux . I feel comfortable to let this cook in `staging`.

**Comment by vcunat** [comment]
xsimd now fails on *-darwin:
https://hydra.nixos.org/build/262200221/nixlog/1/tail
https://hydra.nixos.org/build/262148581/nixlog/1/tail

/cc the staging-next PR https://github.com/NixOS/nixpkgs/pull/316075
nix-review-tools report hundreds of builds blocked by that

**Comment by doronbehar** [comment]
Aish it's weird, this build passed when it was applied on branch `master`, here is the proof:

https://github.com/NixOS/nixpkgs/pull/312745/checks?check_run_id=25145368265

I opened an new upstream issue regarding this: https://github.com/xtensor-stack/xsimd/issues/1030 .

Let's see if they will reply quick. If not, I have a Nixpkgs commit that disables the failing test for Darwin, that I will add to the staging-next PR (https://github.com/NixOS/nixpkgs/pull/316075).

**Comment by vcunat** [comment]
Oh, maybe interaction with some other change.  I just assumed that the update triggered the failure.

**Comment by doronbehar** [comment]
Fix is in https://github.com/NixOS/nixpkgs/pull/317969 .

**Pull request merged**
