### PR TITLE
firmware-linux-nonfree: 2021-03-15 -> 2021-05-11

### PR DESCRIPTION
**Pull request by domenkozar**
I have no idea how to produce SRI hashes.

### CODE REVIEW

**Review by ymatsiuk — APPROVED** [review]

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122583` at 9380cb33 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>firmwareLinuxNonfree</li>
    <li>microcodeAmd</li>
  </ul>
</details>

**Comment by TredwellGit** [comment]
`nixUnstable` produces SRI hashes by default.

**Review by TredwellGit — APPROVED** [review]
I recommend using the `firmwareLinuxNonfree` attribute rather than the `firmware-linux-nonfree` pname but this is good otherwise.

**Comment by jonringer** [comment]
should we backport this for hardware enablement?

**Comment by TredwellGit** [comment]
Seems like a good idea.

**Pull request merged**
