### PR TITLE
dotnet.sdk: 2.2.6 -> 3.0.100

### PR DESCRIPTION
**Pull request by ezemtsov**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by prusnak** [comment]
Please also change homepage to:

```
homepage = "https://dotnet.microsoft.com/";
```

**Comment by prusnak** [comment]
@GrahamcOfBorg build dotnet-sdk

**Comment by kuznero** [comment]
Looks good to me. @jonringer what do you mean by odd behavior?

**Review by kuznero — APPROVED** [review]

**Comment by jonringer** [comment]
Currently the dotnet executable will check to see if it has a given dotnet runtime, if it doesn't, then it tries to download it into the nix store causing issues when you do a `dotnet restore`

**Comment by jonringer** [comment]
Thank you for submitting a PR, however, this is surpassed by #73262 which also enabled combining many sdk's into a single environment.

**Pull request closed without merging**
