### PR TITLE
dd-agent: added pg8000 python module as dependency

### PR DESCRIPTION
**Pull request by rohitasva**
Updated dd-agent.nix to include pg8000 python dependency.
Updated postgresql prestart to create '.first_startup' file

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide in `CONTRIBUTING.md`

**Comment by rohitasva** [comment]
dd-agent:
  NixOS version: 15.07pre66213.9d5508d (Dingo)
  Git version: 2.4.6
When I install dd-agent as a module and provide the configuration for postgres, "dd-agent info" command complains about "no pg8000 module found"

posgresql:
  NixOS version: 15.07pre66213.9d5508d (Dingo)
  Git version: 2.4.6
On a fresh deploy the module doesn't run the script mentioned in initialScript section of the module.

**Comment by rohitasva** [comment]
Any update on this pull request.
thanks

**Comment by domenkozar** [comment]
@rbvermaa

**Comment by rbvermaa** [comment]
This PR seems to contain 2 changes, can you make separate changed for the dd-agent, and for the postdresql one. I don't mind merging the pg8000 dependency, but cannot judge the postgresql change completely.

**Pull request closed without merging**
