### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
`pkgsi686Linux.openssl_1_0_2` regression https://github.com/NixOS/nixpkgs/issues/71786.

**Comment by dtzWill** [comment]
Forgive the offtopic comment, but just wanted to say :+1: THANK YOU @FRidh for your constant work tackling these staging->staging-next->master monsters (well, sometimes monsters)! That's all! Your efforts are appreciated! :heart:

**Comment by FRidh** [comment]
Thanks @dtzWill ! If you keep pushing those core package updates, then I'll handle these monsters ;-)

**Comment by FRidh** [comment]
Linux builds look good and are ready to go. Will wait till tomorrow for Darwin to catch up.
https://hydra.nixos.org/eval/1550390

**Comment by jonringer** [comment]
oops, looks like I accidentally merged a conflict

**Comment by jonringer** [comment]
scared to push the merge conflict change, don't want to kick off another hydra job

**Comment by FRidh** [comment]
This hydra jobset evaluates only every 12 hours. 

Tomorrow morning when more Darwin builds are finished I will solve the merge conflicts and merge it into master.

**Pull request merged**
