### PR TITLE
apparmor: make apparmor cross-compile

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
###### Motivation for this change

`apparmor` assumes that the archiver always has no target platform prefix, which is not true when cross compiling. This PR fixes this, so that `apparmor-parser` in particular will cross compile.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Has this been reported upstream?

**Comment by dingxiangfei2009** [comment]
@FRidh unfortunately, no. I will try to, though.

**Comment by dingxiangfei2009** [comment]
@FRidh cross referenced here: https://gitlab.com/apparmor/apparmor/issues/41

**Comment by joachifm** [comment]
Please change the target branch to staging.

**Comment by dingxiangfei2009** [comment]
@joachifm Okay

**Comment by joachifm** [comment]
@dingxiangfei2009 for changes that incur a massive rebuilds, to avoid unduly delaying channels built from master.

**Comment by joachifm** [comment]
@GrahamcOfBorg build systemd apparmor-parser

**Review by joachifm — APPROVED** [review]

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
