### PR TITLE
treewide: move NIX_CFLAGS_COMPILE to the env attrset 

### PR DESCRIPTION
**Pull request by Artturin**
###### Description of changes

with structuredAttrs lists will be bash arrays which cannot be exported
which will be a issue with some patches and some wrappers like cc-wrapper

Previous unmerged structuredAttrs and env PRs have done the same thing https://github.com/NixOS/nixpkgs/pull/76732

other variables that will have to be transferred (in separate PRs)

```
NIX_CFLAGS_LINK
NIX_LDFLAGS
NIX_PATH
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
Looks like passing `env.NIX_CFLAGS_COMPILE` through `overrideDerivation` is causing errors:

```bash
$ nix-build -A rPackages.data_table
error: cannot coerce a set to a string

       at /.../nixpkgs/pkgs/development/r-modules/default.nix:978:7:

          977|     data_table = old.data_table.overrideDerivation (attrs: {
          978|       env.NIX_CFLAGS_COMPILE = attrs.NIX_CFLAGS_COMPILE + " -fopenmp";
             |       ^
          979|       patchPhase = "patchShebangs configure";
(use '--show-trace' to show detailed location information)
```

Also for `emscriptenPackages.json_c`.

**Comment by Artturin** [comment]
They should be changed to use overrideAttrs https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideDerivation

> Do not use this function in Nixpkgs as it evaluates a Derivation before modifying it, which breaks package abstraction and removes error-checking of function arguments

**Comment by 7c6f434c** [comment]
>          978|       env.NIX_CFLAGS_COMPILE = attrs.NIX_CFLAGS_COMPILE + " -fopenmp";
>             |       ^

Hm, why this «env.»? It is a plain top-level string in attrs, so it should be a plain top-level string in the output of your override function.

**Comment by wegank** [comment]
Aha! `attrs.NIX_CFLAGS_COMPILE` should be `attrs.env.NIX_CFLAGS_COMPILE` instead.

**Comment by Artturin** [comment]
> ```
> $ nix-build -A glm
> error: The ‘env’ attribute set can only contain derivation, string, boolean or integer attributes. The ‘NIX_CFLAGS_COMPILE’ attribute is of type list.
> (use '--show-trace' to show detailed location information)
> ```
> 
> I take it this makes it impossible to use a list of strings for cflags?

see commit messages

**Comment by Artturin** [comment]
rPackages emscriptenPackages fixes https://github.com/NixOS/nixpkgs/pull/217870

**Comment by Artturin** [comment]
with https://github.com/NixOS/nixpkgs/pull/217962 this commits other than ` treewide: move NIX_CFLAGS_COMPILE to the env attrset` could be reverted (other than some manual fixups

**Pull request merged**
