### PR TITLE
grub2: separateDebugInfo = true

### PR DESCRIPTION
**Pull request by symphorien**
###### Description of changes

I need to debug an issue with grub-mount as called by os-prober

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
@ofborg test

**Comment by Mindavi** [comment]
@ofborg test

**Comment by symphorien** [comment]
The failures are on
* the grub1 test, which should not be impacted by this change
* simpleUefiGrubSpecialisation which fails on hydra https://hydra.nixos.org/build/177754537/log, a failure that I cannot even reproduce locally because of a deadlock in nix
```
subtest: Perform the installation
machine: must succeed: nixos-install < /dev/null >&2
machine # copying channel...
machine # querying info about missing paths...
machine # starting pool of 24 threads
machine # checking substituter 'local' for path '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM'
machine # this path will be fetched (0.00 MiB download, 111.99 MiB unpacked):
machine #   /nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': created
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': woken up
machine # querying info about missing paths...
machine # starting pool of 24 threads
machine # checking substituter 'local' for path '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM'
machine # entered goal loop
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': init
machine # acquiring write lock on '/mnt/nix/var/nix/temproots/1160'
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': trying next substituter
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': all references realised
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': woken up
machine # substitution of '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM': trying to run
machine # waiting for children
machine # copying path '/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM' to 'local'...
machine # locking path '/mnt/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM'
machine # lock acquired on '/mnt/nix/store/1giyv268xaf2b2r8imqhv48x3r47b9qj-nixos-22.05.git.efea022d6feM.lock'
<HANG FOR SEVERAL MINUTES>
```

**Comment by Mindavi** [comment]
Possibly related: https://hydra.nixos.org/build/177814314

**Pull request merged**
