### PR TITLE
awscli: 1.18.150 -> 1.18.181

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Currently, awscli & botocore & boto3 have incompatible versions, so they won't build. This syncs and updates the versions.

Also, pyspark is fixed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jluttine** [comment]
I don't understand why `nixpkgs-review pr 104297` fails:

```
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/104297/head:refs/nixpkgs-review/1
$ git worktree add /home/jluttine/.cache/nixpkgs-review/pr-104297-1/nixpkgs 4718ba1ab10d109e2383854c5c56c2c2340c00c1
Preparing worktree (detached HEAD 4718ba1ab10)
Updating files: 100% (23247/23247), done.
HEAD is now at 4718ba1ab10 ocamlPackages.ca-certs: 0.1.2 → 0.1.3
$ nix-env -f /home/jluttine/.cache/nixpkgs-review/pr-104297-1/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 97b08ef4c2d0163119e51f42045247991ef5af8f
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/jluttine/.cache/nixpkgs-review/pr-104297-1/nixpkgs -qaP --xml --out-path --show-trace --meta
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/cli/__init__.py", line 228, in main
    args.func(args)
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/cli/pr.py", line 60, in pr_command
    contexts.append((pr, review.build_pr(pr)))
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 185, in build_pr
    return self.build_commit(base_rev, pr_rev)
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 139, in build_commit
    merged_packages = list_packages(str(self.worktree_dir()), check_meta=True)
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 287, in list_packages
    return parse_packages_xml(nix_env.stdout)
  File "/nix/store/x0m9wx890fj7fdg16ph94c6ifw9gjzb3-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 228, in parse_packages_xml
    for (event, elem) in context:
  File "/nix/store/18656kvqazm74bj7k3mdkwmdlqfyf581-python3-3.8.6/lib/python3.8/xml/etree/ElementTree.py", line 1233, in iterator
    root = pullparser._close_and_return_root()
  File "/nix/store/18656kvqazm74bj7k3mdkwmdlqfyf581-python3-3.8.6/lib/python3.8/xml/etree/ElementTree.py", line 1280, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1386851, column 0
```

**Comment by jonringer** [comment]
> I don't understand why `nixpkgs-review pr 104297` fails:

I usually get that if the underlying nix commands got killed (e.g. OOM killed)

**Comment by jluttine** [comment]
> > I don't understand why `nixpkgs-review pr 104297` fails:
> 
> I usually get that if the underlying nix commands got killed (e.g. OOM killed)

@jonringer Ok! Is there something I could do about it or just ignore `nixpkgs-review`?

**Comment by jonringer** [comment]
> @jonringer Ok! Is there something I could/should do about it or just ignore `nixpkgs-review`?

nixpkgs-reviews is still hugely benefecial. I would still try to enable it. You can add additional swapspace

**Comment by utdemir** [comment]
It also works on my nixos system where without this PR the build fails.

**Comment by terlar** [comment]
I also got errors building awscli and had to downgrade the python package `rsa` as well. Since this awscli version seems to have a requirement on:

```
        rsa>=3.1.2,<=4.0.0; python_version=='3.4'
        rsa>=3.1.2,<=4.5.0; python_version!='3.4'
```

https://github.com/aws/aws-cli/blob/1.18.181/setup.cfg

**Comment by jonringer** [comment]
the pyspark commit might no longer be needed, and currently provides a merge conflict

**Comment by SuperSandro2000** [comment]
Version on master is newer.

**Pull request closed without merging**
