### PR TITLE
new package: pybcrypt

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
@iElectric I tested this locally and it builds fine for Python 2.7 and 3.4.

I was informed in #nixos that Travis-CI has limited sources
and the build may have failed because of that. Can you take a look at this ?

**Comment by iElectric** [comment]
it fails due to Nix. I'll restart it once it's fixed.

**Comment by psibi** [comment]
@iElectric I have a bunch of packages depending upon pybcrypt. Shall I send those patches as pull requests separately or wait till this gets merged ?

**Comment by iElectric** [comment]
tested locally, all good.

**Pull request merged**
