### PR TITLE
nixUnstable: pre20210326_dd77f71 -> pre20210429_d15a196

### PR DESCRIPTION
**Pull request by thufschmitt**
###### Motivation for this change

(amongst other things) several fixes to make the `ca-derivations` experimental feature usable on a daily basis

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121263` at 5ce13431 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/35f8de1223afcf6ab73c7c23da6709ec">dydisnix</a></li>
    <li><a href="https://gist.github.com/2143e6fe14ee6e397383ec517e4f8abc">hydra-unstable</a></li>
  </ul>
</details>
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>disnix</li>
    <li>disnixos</li>
    <li>nix-direnv</li>
    <li>nix-update</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by SuperSandro2000** [comment]
Not sure if we want to upgrade if a lot of tests are failing https://github.com/NixOS/nix/runs/2470165209

**Comment by regnat** [comment]
> Not sure if we want to upgrade if the tests didn't fully run https://github.com/NixOS/nix/runs/2470165209

That test is a know flaky test (see for example https://github.com/NixOS/nix/runs/2419910217 for another instance of it failing on master).

I’ve updated hydra too to catch-up with the Nix update. The dydisnix failure seems unrelated − the failure comes from `libnixxml` which doesn’t depend on `nixUnstable`

**Comment by Ma27** [comment]
@regnat OK, this shouldn't be merged as-is. `nix-shell` currently fails like this for me on `nixpkgs` on 78effd79f10:
```
→ ./result/bin/nix-shell -A hello                                                           [78effd79f10]
error: derivation '/nix/store/zipc1j00q8i30xaylg0fz64lf2ypx752-bash-interactive-4.4-p23.drv' does not have wanted outputs '*'
```

**Comment by Ma27** [comment]
According to git bisect the commit 255d145ba7ac907d1cba8d088da556b591627756 is the problem.

**Comment by Ma27** [comment]
Opened https://github.com/NixOS/nix/pull/4759 to fix this.

**Comment by Ma27** [comment]
Ok, seemed to be false alarm. You have to update your nix-daemon as well for getting this to work. New `nix` and 2.3 daemon appears to work, but not older(tm) unstable daemon & newer CLI. As this is still unstable software, this seems OK to me.

**Comment by regnat** [comment]
Thanks for catching that @Ma27. Let’s wait for https://github.com/NixOS/nix/pull/4763 to be merged first then

**Comment by regnat** [comment]
Just updated Nix with the fix mentionned above, should be good now!

**Pull request merged**
