### PR TITLE
kavita: 0.7.1.4 -> 0.7.3.1

### PR DESCRIPTION
**Pull request by karlprieb**
###### Description of changes

changelog: https://github.com/Kareadita/Kavita/releases/tag/v0.7.3.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Misterio77** [comment]
Hi! Thanks for this!

The NixOS test is failing, as apparently kavita has increased the minimum jwt key length.

The module doc currently instructs the user to generate a 32-byte token, which is now not long enough, so this (as well as the test's key) should be updated. This should do the trick: `head -c 64 /dev/urandom | base64 -w0` (the `-w0` is to avoid breaking lines)

Could you please update the doc (`nixos/modules/services/web-apps/kavita.nix:27`) and the test (`nixos/tests/kavita.nix:12`)?

Thank you!

**Comment by Misterio77** [comment]
With that said, this could perhaps be a (silent-ish) breakage for people currently using the module; as kavita 7.3.1 will start but auth won't work unless they re-generate their secrets.

We can't catch this during evaluation as the secret is only read at runtime, perhaps we could add a preStart check to the systemd module to verify the key is long enough?

**Comment by karlprieb** [comment]
Thanks for catching that. As I tested with a bigger key I didn't notice the issue.

I like the idea of a `preStart` key length check and I'll try to implement it and update docs and test key this weekend.

**Comment by Misterio77** [comment]
I believe this has been superseded by https://github.com/NixOS/nixpkgs/pull/281236

**Comment by luzpaz** [comment]
Indeed. Should be closed.

**Comment by wegank** [comment]
Done in #281236.

**Pull request closed without merging**
