### PR TITLE
Androidndk standalone toolchain support

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

I wanted to use the android standalone toolchain ;)

Now a standalone toolchain is available via:
```
    let
      toolchain = (androidenv.androidndk.makeStandaloneToolchain 24 "arm64");
    in
    ...
```

CC @matthewbauer 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bkchr** [comment]
@matthewbauer ping

**Comment by matthewbauer** [comment]
Sorry

@grahamcofborg build pkgsCross.androidndk.android64.gmp

**Comment by matthewbauer** [comment]
Sorry

@grahamcofborg build pkgsCross.android64.gmp

**Comment by matthewbauer** [comment]
@grahamcofborg build pkgsCross.aarch64-android-prebuilt.hello

**Comment by Ericson2314** [comment]
[IMO it would have been ever so slightly nice to just inline the thing into `passthru` and not need to reindent. I just hit some merge conflicts because of this, and it shows the the derivation itself doesn't depend on what's in the let-binding. Of course, this is all NBD :).]

**Pull request merged**
