### PR TITLE
 firefox-bin: 66.0.3 -> 66.0.4,  firefox-esr: 60.6.1esr -> 60.6.2esr 

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Repaired certificate chain to re-enable web extensions that had been disabled

https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/
https://www.mozilla.org/en-US/firefox/60.6.2/releasenotes/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested only `firefox-bin`.

`firefox` is updated by 1f6ddfc7e039e0f1003116b8e9e7110f363e26e2.

---

### CODE REVIEW

**Comment by andir** [comment]
@taku0  Did it compile for you?

The `-esr` variant doesn't compile for me:

```
collect2: error: ld returned 1 exit status
make[3]: *** [/build/firefox-60.6.2/config/rules.mk:709: libxul.so] Error 1
make[3]: Leaving directory '/build/firefox-60.6.2/obj-x86_64-pc-linux-gnu/toolkit/library'
make[2]: *** [/build/firefox-60.6.2/config/recurse.mk:73: toolkit/library/target] Error 2
make[2]: Leaving directory '/build/firefox-60.6.2/obj-x86_64-pc-linux-gnu'
make[1]: *** [/build/firefox-60.6.2/config/recurse.mk:33: compile] Error 2
make[1]: Leaving directory '/build/firefox-60.6.2/obj-x86_64-pc-linux-gnu'
make: *** [/build/firefox-60.6.2/config/rules.mk:442: default] Error 2
```

https://gist.githubusercontent.com/andir/31a91c88f420e5ddd0afc68936d607b1/raw/857a55c3e78b836ec43a66b5c8a3a370b2d05507/build.log

**Comment by taku0** [comment]
I have successfully compiled it.

```
$ nix-build -I nixpkgs=. -o firefox-esr -A pkgs.firefox-esr
/nix/store/g4m3ww4ccy8ws85x8xxm1yi1vim7shyj-firefox-60.6.2esr

$ firefox-esr/bin/firefox --version
Mozilla Firefox 60.6.2

```

**Comment by timokau** [comment]
I can't find the actual error message in the log. Did you maybe run out of `/tmp` space?

@taku0 fyi: `nix-build` defaults to building from the current directory, so `-I` isn't necessary.

**Review by timokau — APPROVED** [review]
Don't have hardware to test this right now, but since @taku0 said they tested it and this has quite some urgency I'd be in favor of merging.

**Comment by thefloweringash** [comment]
It also builds for me.
```
$ nix-build -j8 -A firefox-esr
/nix/store/g4m3ww4ccy8ws85x8xxm1yi1vim7shyj-firefox-60.6.2esr
$ ./result/bin/firefox --version
Mozilla Firefox 60.6.2
```

**Comment by timokau** [comment]
Thanks!

**Comment by andir** [comment]
Same here.. Not sure why it initially failed. Might have been due to the invocation of `nix-review pr ...`. Did a normal build afterwards (which took a while since my build machines are busy) that was okay.

**Comment by andir** [comment]
Backported to 19.03 in e7924d3ec8f77be51d41f08c58bd53db035dfcc9 & 6ec0970062c62935da71e6dbd3576bbbdcbfa10c

**Pull request merged**
