### PR TITLE
treewide: remove unused occurence of stdenv (and other) arguments

### PR DESCRIPTION
**Pull request by Sigmanificient**
## Description of changes

- #313981

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by corngood — APPROVED** [review]

**Comment by mweinelt** [comment]
@corngood Are you aware that this PR breaks eval?

**Comment by corngood** [comment]
Sorry, I realised that after I submitted my review.  I just wanted to indicate that I'm okay with the changes to the packages I maintain.

**Comment by Sigmanificient** [comment]
Not sure why some dont get catch by nixpkgs-review :<

**Comment by Sigmanificient** [comment]
Result of `nixpkgs-review pr 324767` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by Sigmanificient** [comment]
(no rebuild :tada:)

**Comment by Sigmanificient** [comment]
Can we gets this merged before more conflicts needs to be sorted?

**Review by corngood — APPROVED** [review]

**Comment by mweinelt** [comment]
Please remove the merge commit.

**Comment by Sigmanificient** [comment]
@mweinelt done

**Comment by tomberek** [comment]
Due to https://github.com/NixOS/nixpkgs/blob/c8427f5017070086009c975f30b7a487e73502c0/pkgs/development/python-modules/pillow/generic.nix#L12 the default.nix needs stdenv.

**Review by Aleksanaa — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
This breaks tests. https://github.com/NixOS/nixpkgs/blob/091d8370a215b384b6cdb5448e5c7110ada9d32b/pkgs/test/default.nix#L24

Log: https://gist.github.com/GrahamcOfBorg/d10d6215fb90d00c3fdc950c77c5f143

Discovered in:  #313539

**Comment by Aleksanaa** [comment]
@RossComputerGuy I saw you in my email here. Is that still related and should we deal with it immediately?

**Comment by RossComputerGuy** [comment]
> Is that still related and should we deal with it immediately?

No, it looked a lot like it was a regression but just an issue with a PR after I read more of the nix code which is why I deleted it.

**Pull request merged**
