### PR TITLE
dbus: docs: make id's reproducible

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

With this parameter, generating docs from the same sources will produce the
same 'bit-by-bit' result each time.

This is particularly important since dbus is part of the 'minimal' testset at
https://r13y.com/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested for reproducibility with 'nix-build -A dbus --check'

Also submitted for upstream master (though it's a bit different there due to changes since the last stable release): https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/189

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Thank you soo much. I was just looking at this the other day and noticed the ids.
Could you add a comment with links to the documentation on the flag?

**Comment by raboof** [comment]
Sure - in the patch or on the derivation?

**Review by worldofpeace — APPROVED** [review]
Perfect

**Comment by worldofpeace** [comment]
I'm cool backporting this to 20.09 if that's desired.

**Pull request merged**
