### PR TITLE
Revert "electron_25: eol"

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This reverts commit 9652f98da0717bbd5a8e1166196e13dd9f7b25b6.

## Description of changes

Currently testing locally. This revives the electron desktop application. @dotlambda 

Also see this thread https://github.com/NixOS/nixpkgs/pull/271677#discussion_r1417189161

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by yu-re-ka — CHANGES_REQUESTED** [review]
> This is garbage. We must stop doing this. Just because something is EOL we cannot gate all the people not using it and requiring them to buy very good PCs.

You are entirely ignoring that we did not remove electron-bin 25.x from the tree. The user can simply opt in to using the insecure electron 25 bin package using `nixpkgs.config.permittedInsecurePackages`, which **the evalution failure message will spit out a snippet for you on how to do that**.

Besides that, it should be a motivation to interact with bitwarden upstream to get their electron dependency updated.

When we added electron built from source, it was already controversial if we should add so many expensive hydra jobs, and then we got the green light based on only having the _supported_ (meaning the last 3) versions built in hydra. We can not build 6+ chromium derivations for each staging cycle, especially on aarch64-linux this will kill hydra and even worse backfire into not being able to have Electron built from source at all.

**Comment by SuperSandro2000** [comment]
> Besides that, it should be a motivation to interact with bitwarden upstream to get their electron dependency updated.

The Electron 26 update was reverted because it caused an issue https://github.com/bitwarden/clients/issues/6560

I've asked if there is some progress we can follow https://github.com/bitwarden/clients/pull/6573#issuecomment-1845271282



> We can not build 6+ chromium derivations for each staging cycle, especially on aarch64-linux this will kill hydra and even worse backfire into not being able to have Electron built from source at all.

but since then we removed the chromium dev/beta variants. Can't hydra hold this extra package for a month longer? Having to rely on binary packages because of that is not a resolution I want to accept.

**Comment by yu-re-ka** [comment]
Thank you for looking into the upstream issues.

> but since then we removed the chromium dev/beta variants. Can't hydra hold this extra package for a month longer?

The chromium dev/beta variants were never built by hydra, so removing these variants does not reduce load on hydra.

If you can get a confirmation from one of the people who are able to judge the Hydra capacity, and with the statement that the intention is not to keep around old electron releases around forever, I will retract my veto from adding back the source-built derivation for electron_25, however I still think using the electron 25 package (both bin and source) should throw at least an eval warning at users.

> Having to rely on binary packages because of that is not a resolution I want to accept.

I'm totally on the same side here as not wanting to have binary packages on my system was the original motivation for packaging electron from source. I just disagree on how this should be achieved in this specific case. In the best case, a NixOS+bitwarden user would use the ability to build Electron with their own patchsets to contribute a fix for the underlying issue, and make it possible to run bitwarden using the latest Electron versions.

**Comment by dotlambda** [comment]
Has anyone tried running Bitwarden under `electron_26`?

**Pull request closed without merging**
