### PR TITLE
sherlock: 0-unstable-2024-06-04 -> 0-unstable-2024-06-09

### PR DESCRIPTION
**Pull request by applePrincess**
## Description of changes
Update to 2024-06-09
- Move to pytest/tox based testing.

https://github.com/sherlock-project/sherlock/compare/ef124acf34e90626f4e59ab88bba1ed6141a4126...d678908c00f16c7f6c44efc0357cef713fa96739

I am notified by the upstream as sherlock-project/sherlock/issues/2111 and sherlock-project/sherlock/issues/2127 are almost ready which will use tox and poetry instead.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ppfeister** [comment]
@applePrincess Upstream merged.

Not sure if your build needs builds to succeed offline or not, but in case they do (as with rpms)...
`tox -e offline` will exclude those unit tests that require an internet connection.
If running pytest directly, rather than through tox, `pytest -m "not online"` will achieve the same.

**Comment by applePrincess** [comment]
Indeed it needs to be offline to successfully build a package. (at least on Nixpkgs' GitHub Action and on Nixpkgs' hydra CI system)

**Comment by applePrincess** [comment]
Result of `nixpkgs-review pr 313395` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>sherlock</li>
    <li>sherlock.dist</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]
Approved. 

Perhaps move it to pkgs/by-name as well?

So when ryantm bot ends up bumping this, you can merge it using nixpkgs-merge-bot, as you are the maintainer.

**Comment by JohnRTitor** [comment]
When you move a package to `pkgs/by-name`, you should also remove its entry from all-packages.nix.

Else eval will fail. 

In addition moving to pkgs/by-name should be done in a seperate commit like https://github.com/NixOS/nixpkgs/pull/317382/commits/96f6a37b84a5f028aff95f96213853197beee4a2.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 313395` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>sherlock</li>
    <li>sherlock.dist</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]

**Comment by ppfeister** [comment]
Didn't expect this in my notifications today

We've just adopted properly tagged releases [[ref]](https://github.com/sherlock-project/sherlock/releases/tag/v0.15.0), in case that makes it easier for y'all to maintain. No more nonsense version numbers or git refs are needed, with some better feature/bug consistency across package managers.

A bit easier to see when updates are needed as well, probably.

**Pull request merged**
