### PR TITLE
Backport 21.05 emacs pkgs updates

### PR DESCRIPTION
**Pull request by afrepues**
###### Motivation for this change

These commits contain fixes of known issues affecting 21.05. By updating to newer versions, it should solve Magit's interactive rebase not working, quite similar to magit/magit#4319.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
That'ts quite a lot of changes just to fix magit. Is there a way of just backporting the fix?

**Comment by afrepues** [comment]
> That'ts quite a lot of changes just to fix magit. Is there a way of just backporting the fix?

The initial motivation was fixing Magit, I found that the update was embedded within an update to the whole MELPA archive packages, and it would be more work to fix _only_ Magit, as its dependencies need updating too, and some transitive ones might need it as well.

The initial motivation was fixing Magit, but after looking at al the changes that had gone into master after the creation of the release branch I decided for cherry-picking all these changes because:

- it would be more work to extract just Magit and its dependencies, mainly because some of the transitive dependencies might need updating
- doing the above and/or picking only a few commits _could_ make harder to backport other updates/fixes in the future
- there are other important fixes, like making the `overrideScope` work

The only commit that worries me is the one changing the build phases, it is tree wide, but not including it could make backporting harder in the future. Alternatively, I could modify that commit to leave only the changes that affect the Emacs packages, or even remove it completely.

**Comment by afrepues** [comment]
BTW, do you know how to re-run the checks that failed?

**Comment by adisbladis** [comment]
This is _way_ to big in scope. If you have some specific issue with Magit you could create a PR for that to 21.05.

**Comment by afrepues** [comment]
@adisbladis would it help cutting it down to less files affected? one commit I mentioned before touched a lot of files, by editing that commit to leave only changes to Emacs packages it results in:

https://github.com/NixOS/nixpkgs/compare/release-21.05...afrepues:backport-21.05-emacs-pkgs-updates-v1

**Pull request closed without merging**
