### PR TITLE
android-studio: Fix the license (unfree)

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

I just noticed that Android Studio states that it contains proprietary code so this obviously requires an update to the licensing situation.

Screenshot:
help-licenses

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]

**Comment by hedning** [comment]
Hmm, are we certain that applies to the things distributed in the derivation and not just the things that are downloaded after accepting the license? (IIRC the build is fairly significant, so if it's to keep the core build free that would be optimal).

**Comment by primeos** [comment]
> Hmm, are we certain that applies to the things distributed in the derivation and not just the things that are downloaded after accepting the license?

I'm not that familiar with the Android Studio licencing, but that's definitely what `NOTICE.txt` tells us.
The additional downloads are covered by the (also unfree) [Android SDK license](https://developer.android.com/studio/terms).

> IIRC the build is fairly significant, so if it's to keep the core build free that would be optimal

We don't build Android Studio from source (if we did this the result would most likely be open-source without the proprietary extras). Therefore this shouldn't really affect build times at all (apart from possibly differing server bandwidths, but this shouldn't make a noticeable difference).

**Comment by primeos** [comment]
I've had another look:
- Most/all other distributions only use the Apache-2.0 license
- But:
  - Android Studio requires one to download the Android SDK (I could neither skip this step on a new installation nor deselect core components) which is under a proprietary license (as linked above)
  - `NOTICE.txt` is included in the distribution from Google that we ship: `at $(nix-build --no-out-link -A android-studio.unwrapped)/NOTICE.txt` (i.e. not from any additional downloads)
  - There are some CLion references (which is proprietary) and the Android Studio NDK plugin (which is based on CLion) might be bundled by default (see e.g. https://twitter.com/clion_ide/status/603993226400399360?lang=en).

So the licensing situation isn't really clear but IMO it would be best to assume an unfree license (proprietary parts) as that would be way less problematic than the other way around (and since the Android SDK is unfree it's not possible to use Android Studio under a free license anyway as those extra downloads are required by default).

**Comment by hedning** [comment]
> We don't build Android Studio from source

Right, I could've sworn I had to do large build at some point after modifying the android studio derivation, but must've confused it with something else.

Disregard me then, not a big deal marking it as unfree then.

**Review by hedning — APPROVED** [review]

**Pull request merged**
