### PR TITLE
ollama: 0.1.26 -> 0.1.27

### PR DESCRIPTION
**Pull request by abysssol**
## Description of changes
Ollama 0.1.27 seems to be a rather minor release, the most notable change being the version update of the vendored llama.cpp, which improved performance with the gemma model.

### What changed

<details><summary>

#### release [0.1.27](https://github.com/ollama/ollama/releases/tag/v0.1.27)

</summary>

- Performance improvements (up to 2x) when running [Gemma](https://ollama.com/library/gemma) models
- Fixed performance issues on Windows without GPU acceleration. Systems with AVX and AVX2 instruction sets should be 2-4x faster.
- Reduced likelihood of false positive Windows Defender alerts on Windows.

</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Can you please undo the changes in the nixos module or use a separate commit for it ?

**Comment by abysssol** [comment]
Sorry about that, I'll keep that in mind in the future.
It simply didn't strike me as necessary to have multiple commits, since the change was rather trivial and was directly related to ollama.
I split the commit, but if you still want to, I can remove it entirely. It just seems to me like a waste of effort to open a separate pull request and pollute the list of pull requests with something rather unimportant.

**Review by drupol — APPROVED** [review]

**Comment by DuckyBlender** [comment]
Does this have a service? Sorry for the dumb quesion, I am extremely new to this.

**Comment by drupol** [comment]
> Does this have a service? Sorry for the dumb quesion, I am extremely new to this.

https://search.nixos.org/options?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=ollama

**Comment by abysssol** [comment]
@DuckyBlender yes, there's a service, but only on `nixos-unstable` so far. I'm currently creating a backport to stable, but some modifications are necessary, and I haven't had as much free time recently as I'm used to. I'm hopeful that the backport will be ready within a week.

Here are some relevant links that may be helpful:
[information on channels](https://nixos.wiki/wiki/Nix_channels)
[more details](https://discourse.nixos.org/t/differences-between-nix-channels/13998)
[updating channels](https://nixos.org/manual/nixos/stable/index.html#sec-upgrading)

**Pull request merged**
