### PR TITLE
jackett: 0.21.2831 -> 0.22.893

### LINKED ISSUE #353063: Update request: jackett 0.21.2831 → 0.22.879
- Package name: jackett
- Latest released version: [0.22.879](https://github.com/Jackett/Jackett/releases/tag/v0.22.879)

- Current version on the unstable channel: 0.21.2831
- Current version on the stable/release channel: 0.21.2831

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@edwtjo
@nyanloutre
@purcell

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by ghost**
## Description
- Updated Jackett to version 0.22.893.
- Upgraded the .NET SDK to version 8.0 for improved compatibility.

Closes #353063

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Atemu — APPROVED** [review]
Diff LGTM.

Does it work as expected in your testing?

**Comment by TanvirOnGH** [comment]
Yes

**Comment by Atemu** [comment]
Is the dotnet update applicable to the old version? If it's only necessary for the updated version and the old version doesn't work with it, please squash those two commits as that's one logical step. Any changes to the derivation done to make the update possible are typically included in the update commit.

**Comment by Atemu** [comment]
Did the latest update you pushed not require a re-generation of the deps?

**Comment by TanvirOnGH** [comment]
yes

**Review by Atemu — APPROVED** [review]
Alright, diff LGTM and it builds.

**Comment by XenGi** [comment]
Can this also be backported to 24.11? The build is broken because of a datetime constraint in their test suite.

**Comment by Atemu** [comment]
If the build is broken, sure.

Please test the backport PR that will appear shortly.

**Comment by Atemu** [comment]
Welp, you're going to have to backport manually; resolving conflicts.

**Pull request merged**
