### PR TITLE
linux: add 6.1

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

New kernel. No Rust yet because it's not used for anything and doesn't work with split debuginfo.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Rust commit: https://github.com/K900/nixpkgs/commit/605ed1beea2d478dd47ef05f1388e6c64ea83c98

Probably shouldn't merge it yet because it's not useful and breaks split BTFs.

**Comment by alyssais** [comment]
@OfBorg test latestKernel.login

**Review by alyssais — APPROVED** [review]

**Comment by K900** [comment]
Also run-tested on my GA402RJ.

**Comment by alyssais** [comment]
The following kernel modules need attention, but it shouldn't hold up this PR:

```
┃ ⚠︎ rtl8189es-6.1-2022-08-30 failed with exit code 2 after ⏱︎ 1m12s
┃ ⚠︎ rtl8812au-6.1-unstable-2022-08-22 failed with exit code 2 after ⏱︎ 31s
┃ ⚠︎ rtl8723ds-6.1-unstable-2022-10-20 failed with exit code 2 after ⏱︎ 26s
┃ ⚠︎ ddcci-driver-6.1-0.4.2 failed with exit code 2 after ⏱︎ 6s
┃ ⚠︎ lttng-modules-6.1-2.13.4 failed with exit code 2 after ⏱︎ 46s
┃ ⚠︎ ena-2.8.0-6.1 failed with exit code 2 after ⏱︎ 3s
┃ ⚠︎ apfs-unstable-2022-08-15-6.1 failed with exit code 2 after ⏱︎ 30s
┃ ⚠︎ rtl88x2bu-6.1-unstable-2022-08-18 failed with exit code 2 after ⏱︎ 30s
┃ ⚠︎ rtl8814au-6.1-unstable-2022-08-18 failed with exit code 2 after ⏱︎ 28s
┃ ⚠︎ rtl8821cu-6.1-unstable-2022-05-07 failed with exit code 2 after ⏱︎ 30s
┃ ⚠︎ rtl8189fs-6.1-2022-05-20 failed with exit code 2 after ⏱︎ 1m11s
┃ ⚠︎ rtl8821ce-6.1-unstable-2022-06-01 failed with exit code 2 after ⏱︎ 29s
┃ ⚠︎ rtl8821au-6.1-unstable-2022-08-22 failed with exit code 2 after ⏱︎ 31s
┃ ⚠︎ evdi-1.12.0 failed with exit code 2 after ⏱︎ 26s
┃ ⚠︎ VirtualBox-GuestAdditions-6.1.40-6.1 failed with exit code 2 after ⏱︎ 38s
┃ ⚠︎ mba6x_bl-unstable-2016-12-08 failed with exit code 2 after ⏱︎ 3s
```

Usually I go through and look for updates / patches, write them if they're simple, and otherwise mark the modules broken, but I'm not sure I'll have time to do that for this one.

**Comment by alyssais** [comment]
Yeah, that's what I meant by "it shouldn't hold up this PR" :)

**Pull request merged**
