### PR TITLE
python3: 3.10 -> 3.11

### PR DESCRIPTION
**Pull request by mweinelt**
Updates the default python version to 3.11, while keeping 3.10 around until after the NixOS 23.11 release.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]
Because, why not?

**Comment by NickCao** [comment]
Shall we also update `doc/languages-frameworks/python.section.md` and the release note?

**Review by lukegb — APPROVED** [review]

**Comment by raboof** [comment]
> Shall we also update `doc/languages-frameworks/python.section.md` and the release note?

I've created a commit proposing those updates in https://github.com/NixOS/nixpkgs/commit/4b0b9d00fd2a1d323a2df7d7c1c8cfc4dfa19993 . I expect there will be some review comments / iteration on getting this 'just right'.

I would propose we merge this PR as-is so we can start ironing out any bugs with python 3.11 ASAP, and iterate on the messaging in parallel.

**Comment by mweinelt** [comment]
This should go through python-updates, so we can inspect and iterate on the fallout before it hits staging.

cc @tjni do you want to drive this?

**Comment by tjni** [comment]
Sure thing!

**Comment by tjni** [comment]
I have been working on addressing some fallout from https://github.com/NixOS/nixpkgs/pull/248866, but I'll start working on this tomorrow.

**Comment by mweinelt** [comment]
Continues on python-updates.

**Pull request closed without merging**
