### PR TITLE
ghcjs-ng: unbreak - Backport from master

### PR DESCRIPTION
**Pull request by FPtje**
###### Motivation for this change
Backport of https://github.com/NixOS/nixpkgs/pull/58192
ghcjs is marked broken in release-19.03. This is undesirable.
CC from previous pull request: @vaibhavsagar @Ericson2314 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FPtje** [comment]
CC @basvandijk as Haskell maintainer

**Comment by basvandijk** [comment]
@GrahamcOfBorg build haskell.compiler.ghcjs

**Comment by basvandijk** [comment]
Dank je @FPtje! 

Please use the `-x` flag when cherry-picking next time. This ensures that a line is appended that says "(cherry picked from commit ...)" to the original commit message in order to indicate which commit this change was cherry-picked from. I've now forced pushed a commit which has this line.

I'll merge when the checks are green.

**Comment by FPtje** [comment]
Will do next time! Thanks!

**Comment by FPtje** [comment]
```
building of '/nix/store/q73fa6zmsz1g4a91b2y3x530pikfqnvc-ghc-api-ghcjs-8.6.2.drv' timed out after 3600 seconds
```
Yeah, ghcjs needs more than an hour to compile.
If it's any help, it #WorksForMe:
2019-04-22-100824_1529x290_scrot

Though I cannot test darwin. With aarch64-linux I'm not sure whether that's supposed to work yet.

**Comment by FPtje** [comment]
Any update on this?

**Pull request merged**
