### PR TITLE
Python: package set updates before branch-off

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Update all packages before branching off.

https://hydra.nixos.org/jobset/nixpkgs/python-unstable

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@dotlambda flake8 update is included here

**Comment by dotlambda** [comment]
@FRidh The flake8 bump required bumping pyflakes, pycodestyle, entrypoints and configparser as well. I did some more than just bumping these packages so I replaced your commits by mine.

**Comment by FRidh** [comment]
I already did those updates.

**Comment by dotlambda** [comment]
Feel free to force-push your branch again if you think that's the most sensible thing to do.

**Comment by FRidh** [comment]
Looks like we made the same changes more or less. I'll indeed force-push again, and then won't force push anymore until we're ready to merge.

**Comment by dotlambda** [comment]
That's a pity. Waisted some time on it :(

**Comment by Ericson2314** [comment]
@FRidh just wanted so say I'm overjoyed your doing `strictDeps` as part of this!

**Comment by dotlambda** [comment]
Do you have an idea how to solve that `jaraco_collections` and `jaraco_text` now depend on each other? If not, we can remove them if @fpletz and @globin agree to remove IRC support from `errbot`. Otherwise, I suggest they open an upstream issue about this problem.

**Comment by FRidh** [comment]
Circular dependencies should be avoided so I suggest informing upstream. I however think they're aware of this. 

If I am correct, `pip` can handle this by first building the wheels, and then installing them in a single invocation. We can do that as well:
```nix
let
  jaraco_text_wheel = buildPythonPackage {
      name = "${pname}-${version}-wheel"
      ...
    installPhase = ''
      mkdir -p $out
      cp dist/* $out/
    '';
  };
  jaraco_collections_wheel = buildPythonPackage {
      name = "${pname}-${version}-wheel"
      ...
    installPhase = ''
      mkdir -p $out
      cp dist/* $out/
    '';
  };
  jaraco_collections_text = buildPythonPackage {
    unpackPhase = "true";
    buildPhase = ''
      mkdir -p dist
      cp ${jaraco_collections_wheel} dist/
      cp ${jaraco_text_wheel} dist/
    '';
  };
in {
  jaraco_text = jaraco_collections_text;
  jaraco_collections = jaraco_collections_text;
}
```

**Comment by FRidh** [comment]
Just merged staging. I intend to merge this into staging soon, despite a 200+ increase in broken packages.

**Comment by dotlambda** [comment]
I'm getting
```
$ nix-shell -I nixpkgs=. -p "python3.withPackages (ps: with ps; [ pykerberos ])" --run "python -c 'import kerberos'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /nix/store/77n1k65iv1ihk8j3jbz78rzl477p3qlr-python3-3.7.2-env/lib/python3.7/site-packages/kerberos.cpython-37m-x86_64-linux-gnu.so: undefined symbol: gss_nt_service_name
```
Any idea what's happening?
cc @catern

**Comment by catern** [comment]
I believe that's caused by pykerberos having krb5 listed as a buildInput, when it should be a nativeBuildInput. I guess something was changed about buildInput handling in Python-land in this PR, since that worked before.

Fixed here: https://github.com/NixOS/nixpkgs/pull/56268

**Comment by timokau** [comment]
Is there any kind of policy on how to handle the fallout of breaking changes? I just spent quite some time bisecting the rpy2 failure to the strictDeps commit. I realize that it may not be realistic to expect the committer to fix all downstream issues, but I think doing nothing and hoping for maintainers / end-users to figure out the root cause of failures isn't optimal.

Maybe we could at least notify maintainers / post about changes with big breaking potential on nixos-weekly / post on discourse.

**Comment by catern** [comment]
Uh, hmm, actually that pykerberos fix seems really weird. https://github.com/NixOS/nixpkgs/pull/56268 pykerberos links against krb5, so shouldn't krb5 be in buildInputs? But when krb5 is in buildInputs, the built binary doesn't properly link against krb5. But it *does* work if krb5 is in nativeBuildInputs. Huh?

**Comment by dotlambda** [comment]
Maybe the following would make more sense.
```diff
diff --git a/pkgs/development/python-modules/pykerberos/default.nix b/pkgs/development/python-modules/pykerberos/default.nix
index 994ba059f9e..ca1fda884d5 100644
--- a/pkgs/development/python-modules/pykerberos/default.nix
+++ b/pkgs/development/python-modules/pykerberos/default.nix
@@ -9,7 +9,9 @@ buildPythonPackage rec {
     sha256 = "0v47p840myqgc7hr4lir72xshcfpa0w8j9n077h3njpqyn6wlbag";
   };
 
-  nativeBuildInputs = [ krb5 ];
+  #nativeBuildInputs = [ krb5 ]; # for krb5-config
+
+  buildInputs = [ krb5 ];
 
   # there are no tests
   doCheck = false;
```
I have no idea though why it works without `buildInputs` nor do I get what their code at https://github.com/02strich/pykerberos/blob/v1.2.1/setup.py#L38 is supposed to do. The `except` certainly doesn't trigger when `krb5-config` is not present. Maybe we should report that upstream.

**Comment by FRidh** [comment]
@dotlambda that's correct, it needs to be in both. `strictDeps` only handles the things on `PATH`, but it doesn't consider distinguishing whether the libraries need to be available for the host machine or not.

**Comment by dotlambda** [comment]
> that's correct, it needs to be in both. strictDeps only handles the things on PATH, but it doesn't consider distinguishing whether the libraries need to be available for the host machine or not.

I know, but `nix-shell -I nixpkgs=. -p "python3.withPackages (ps: with ps; [ pykerberos ])" --run "python -c 'import kerberos'"` works without having it in `buildInputs`. That's what I don't get. Maybe the library is only used at a later point.

**Comment by FRidh** [comment]
When not cross-compiling, there is no difference between `buildInputs ` and `nativeBuildInputs`.

**Comment by dotlambda** [comment]
I pushed the fix in 82b38923c26d99196f62b9cea444f5d68258462c.

**Comment by flokli** [comment]
The [`python: azure-mgmt-compute: 0.20.1 -> 4.4.0` bump](https://github.com/NixOS/nixpkgs/commit/7f80b2fda5637b0a95cef05564278bcdddfc12f6) also broke nixops.

**Comment by flokli** [comment]
backported the nixops fix (https://github.com/NixOS/nixpkgs/pull/56775) to 19.03 in 17a5b644249ef82f714e0e4150dbd019df273a52.

**Comment by bendlas** [comment]
> The [`python: azure-mgmt-compute: 0.20.1 -> 4.4.0` bump](https://github.com/NixOS/nixpkgs/commit/7f80b2fda5637b0a95cef05564278bcdddfc12f6) also broke nixops.

`azure-mgmt-compute` doesn't build anymore at all, but there's a [PR](https://github.com/NixOS/nixpkgs/pull/52550#issuecomment-469006544) for that.

@FRidh? If you don't want to rebase #52550, you can always just pin the older version.

**Pull request merged**
