### PR TITLE
Add namespace support to Wireguard module

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

Adds support for creating a Wireguard interface in a network namesapce, or moving it post-creation.

inspired by [this unmerged PR](https://github.com/NixOS/nixpkgs/pull/60983), which only allowed specifying a destination namespace to move the Wireguard interface to, whereas this PR also allows specifying where the interface should be created in the first place, so that both the usecases outlined [here](https://www.wireguard.com/netns/) can be supported.

Things to note:

* Does note create the network namespaces (must be created/removed separately in `Pre`/`Post` directives)
* Special-cases the `init` string to mean "move the interface back to the init namespace"
* Defaults for both new option mean: create interface in init namespace, and don't move it
* ~No additional tests. Happy to write some, but wanted to receive feedback on the general approach first.~ Tests added.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @fpletz @Mic92 @globin @zx2c4

### CODE REVIEW

**Comment by xwvvvvwx** [comment]
Tested on nixos-unstable (cherry-picked onto `1c40ee6fc44f7eb474c69ea070a43247a1a2c83c`). 

I am successfully using this PR to spawn a wireguard device with the socket end in a "physical" namespace, and the interface end in the "init" namespace as described [here](https://www.wireguard.com/netns/#the-new-namespace-solution).

**Review by endocrimes — APPROVED** [review]
This works for me on nixos-unstable - thanks for this! - I was looking at adding it myself sometime this weekend.

**Comment by Mic92** [comment]
cc @zx2c4 regarding user-interface & documentation of this feature.

**Review by fpletz — COMMENTED** [review]
Haven't tested it yet but the implementation and the configuration interface looks straightforward and understandable to me.

**Comment by asymmetric** [comment]
Added a few tests around namespaces.

**Review by 0x4A6F — APPROVED** [review]

**Comment by asymmetric** [comment]
Renamed the options:

* `creationNamespace` -> `socketNamespace`
* `destinationNamespace` -> `interfaceNamespace`

The naming [comes from](https://github.com/NixOS/nixpkgs/pull/60983#issuecomment-493675579) @zx2c4 himself, and trades visual descriptiveness for technical accuracy.

**Review by fpletz — APPROVED** [review]

**Pull request merged**
