### PR TITLE
Update and add new ZNC modules

### PR DESCRIPTION
**Pull request by hrdinka**
Currently most ZNC modules won't even build with the current ZNC release. That's fixed with these commits. Further clientbuffer and playback modules are added.

@viric @offlinehacker

### CODE REVIEW

**Comment by hrdinka** [comment]
The last commit deletes the old ZNC version 1.4.

@lethalman added it cause xchat does not support TLS. I don't know if this still is the case. However if someone really wants to use an insecure protocol it can be turned on in znc 1.6. Have a look at `SSLProtocols` over here http://wiki.znc.in/Configuration.

**Comment by lethalman** [comment]
It was mostly because 1.6 state is incompatible with 1.4, so it erased all of the configs. However I will take a look at this later.

**Comment by jagajaga** [comment]
LGTM
@lethalman?

**Comment by zimbatm** [comment]
LGTM

**Pull request merged**
