### PR TITLE
Fix gitlab

### PR DESCRIPTION
**Pull request by brainrake**
###### Motivation for this change

There were several mistakes in the setup script, including hardcoded values and secret generation that didn't work.
I'm trying to get the gitlab nixos test running again but RoR is very slow in qemu. So I'm submitting these in the mean time.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by bjornfor — CHANGES_REQUESTED** [review]
The content looks good, but I'd like to see an explanation (in the commit message) which problem the last commit fixes.

**Comment by manveru** [comment]
Can you maybe try running the `nix-build nixos/tests/gitlab.nix`?

**Comment by brainrape** [comment]
@bjornfor updated, thanks

**Comment by brainrape** [comment]
Yeah as I said I updated the gitlab test (needs a lot of updating), but the gitlab service doesn't start in 30 min in qemu... bundle runs for a long time. I'll check back if I get it up.

**Comment by bjornfor** [comment]
Do the VM tests pass --enable-kvm to QEMU? (Speed up.)

**Review by fpletz — APPROVED** [review]
The fixes are correct and valid. Thanks!

**Comment by globin** [comment]
I have tried making the test work again a few times, but currently gitlab is doing too much I/O for 9pfs to cope, I'd be really happy if someone fixes that but I can't see us blocking a merge on that..

**Pull request merged**
