### PR TITLE
yazi: clean up wrapper, add options and format 

### PR DESCRIPTION
**Pull request by eljamm**
## Description of changes

~~Add exiftool, which is needed for showing EXIF data when interactively opening images with `O`~~

- Remove redundant `withPackage` options
- Add `optionalDeps` for packages that provide additional features
- Add `extraPackages` for user-defined packages
- Format with nixfmt

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eljamm** [comment]
Result of `nixpkgs-review pr 321076` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>yazi</li>
  </ul>
</details>

**Comment by XYenon** [comment]
I don't think we should add exiftool to the wrapper. Unlike other tools which are used to provide yazi functions in rust or lua codes, the only usage of exiftool is in the [default opener config](https://github.com/sxyazi/yazi/blob/1f562031f433df53a065e5315bd10ad13e43bd2f/yazi-config/preset/yazi.toml#L44). And I don't think we should add tools only in config to the wrapper, because config can and usually be changed.

**Review by matthiasbeyer — APPROVED** [review]

**Comment by eljamm** [comment]
@XYenon As a new user, I expect things to work out of the box without me having to configure anything. Also, looking at the history of that config file, `exiftool` has always been there, so I don't think it's likely to change in the future.

That being said, if you still don't want to add it, how about adding an `extraPackages` option, instead?

That way, users will easily be able to simply add the tools they need to the wrapper.

**Comment by linsui** [comment]
What's the benefit to add packages to the wrapper instead of globally?

**Comment by eljamm** [comment]
@linsui Well, the main benefit is making sure those packages are installed/deleted with the program and that it functions as it should out of the box.

For example, say that I want to try yazi but `unar` has not been added to the wrapper. This means I also need to install `unar` in order to preview archive files. As such, I need to remember to remove `unar` when I no longer want to use yazi, else I'd have a package I don't need in my PATH, which also won't be cleaned up by the GC.

Therefore, by adding the tools we need to the wrapper, we're effectively coupling them to the main program.

**Comment by XYenon** [comment]
mpv, mediainfo, and even vscode are in the default openers, I don't think exiftool is special. Add a `extraPackages` is fine for me.

**Comment by eljamm** [comment]
Alright, should I open a new PR or do I force push here?

**Review by XYenon — APPROVED** [review]

**Comment by eljamm** [comment]
Tested the change with:

```console
$ nix-build -E 'with import ./. {}; (yazi.override { extraPackages = [ exiftool ]; })'
```

And everything works correctly.

**Comment by linsui** [comment]
Maybe we should unify those options. E.g.

```
extraPackages ? [ file jq ... ]
```

**Comment by eljamm** [comment]
That won't work because those packages are essential for running the program, while the `extraPackages` option is meant for users to add their own **extra** packages.

From the example above, having `extraPackages = [ exiftool ];` will replace just `[ file jq ... ]`.

That said, we already have all the tools grouped together in `runtimePaths`, both the default and user-defined ones.

**Comment by linsui** [comment]
None of those packages except file is needed to run yazi.

> From the example above, having extraPackages = [ exiftool ]; will just replace [ file jq ... ].

This is what I want. What should a user do if they only need file?

```nix
yazi.override {
  withJq = false;
  withPoppler = false;
  withUnar = false;
  withFfmpegthumbnailer = false;
  withFd = false;
  withRipgrep = false;
  withFzf = false;
  withZoxide = false;
}
```

or

```nix
yazi.override { withRuntimeDeps = false; }
```

then install file globally. What a bad UX.

**Comment by XYenon** [comment]
> What should a user do if they only need file?

I think few users really want this. Most users want a fully functional yazi.

**Comment by linsui** [comment]
> Most users want a fully functional yazi.

They can get a full-featured yazi by default. When they want to override yazi they can keep what they want. The benefit is that we have less options.

**Comment by eljamm** [comment]
Technically, we could control all optional deps using another option `enableOptional`, for example, which can disable them all at once, but this won't work if you also want to enable specific ones.

In that case, you'd need to pass them with `extraPackages`:

```nix
yazi.override {
  enableOptional = false;
  extraPackages = [ jq fd rg ];
}
```

The UX of `"all on, few off"` is better to me as it's more realistic to disable what you don't need, for example:

```nix
yazi.override {
  # I don't like PDF and Archive previews
  withPoppler = false;
  withUnar = false;
}
```

However, if you'd like to discuss this further, I believe we can do so in a new PR.

**Comment by XYenon** [comment]
> They can get a full-featured yazi by default. When they want to override yazi they can keep what they want. The benefit is that we have less options.

But if a user want to remove, for example, unar, maybe because a build failure, they have to add all others to `extraPackages` manually.

**Comment by teto** [comment]
I find @linsui 's suggestion simpler and more tractable from an implementation point of view. Having all those `withX` is a recipe for errors. Having a simple list makes for clearer code, easier overrriding and so on.

On the question of adding exif by default, I dont really mind but the more you add, the harder it becomes to maintain (you get tickets because the dependency failed while it is not very impactful) and the closure increases. I would like to use yazi on servers as well where exif files is not required but space is limited so I would favor not including it

**Comment by eljamm** [comment]
Thanks @teto, you make some valid points there. I went ahead and implemented @linsui 's idea in https://github.com/eljamm/nixpkgs/commit/2fb8165db07cf58000847c59e94b70877e0d9cf4 and I gotta say that it does look cleaner and more readable.

I'm personally okay with this as it doesn't change much for me. How does everyone else feel about this?

**Review by XYenon — APPROVED** [review]

**Comment by linsui** [comment]
How about putting file in optionalDeps and removing withRuntimeDeps?

**Comment by eljamm** [comment]
According to the [yazi docs](https://yazi-rs.github.io/docs/installation/), file is not optional.

**Comment by linsui** [comment]
Without file yazi can still run and browse files though previewer doesn't work. I feel that it doesn't worth adding withRuntimeDeps only for that. withRuntimeDeps becomes useless anyway.

**Comment by eljamm** [comment]
I don't mind removing `withRuntimeDeps` if its usefulness is limited, but I prefer to keep `file` as a non-optional dependency since that's what upstream considers it.

**Comment by eljamm** [comment]
Does it make sense to add `extraPackages` or `optionalDeps` to the yazi module or should the package just be overwritten?

Also, are these changes considered a breaking API change and thus can't be backported to the stable branch?

**Comment by sxyazi** [comment]
> Without file yazi can still run and browse files though previewer doesn't work

It can also cause files to be unable to open - I think being able to open files is a baseline for a file manager, so it's worth mentioning here.

**Comment by linsui** [comment]
> I don't mind removing withRuntimeDeps if its usefulness is limited, but I prefer to keep file as a non-optional dependency since that's what upstream considers it.

Sounds good to me.

**Review by XYenon — APPROVED** [review]

**Review by linsui — APPROVED** [review]

**Pull request merged**
