### PR TITLE
gnome3.rygel: fix build

### LINKED ISSUE #59815: rygel fails to build
## Issue description

rygel fails to build due to a valadoc error when generating docs. The error is:
`error: Package 'gupnp-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories`

This prevents gnome3 from being built unless `services.gnome3.rygel.enable` is set to `false`.

### Steps to reproduce

`nix-build '<nixpkgs>' -A gnome3.rygel ~/repos/nixpkgs`

Tested against `7f2f8f359fe`, which at the time of writing is the HEAD of `nixos-unstable-small`.

## Technical details

System info:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.35, NixOS, 19.09pre176459.7f2f8f359fe (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre176459.7f2f8f359fe"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by worldofpeace**
Fixes #59815

* add patch for installation sysconfdir
* disable api docs

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Hmm, I must have forgotten to test Rygel once I started focusing on GUPnP.  Otherwise, I do not understand how could I have missed this.

The issue with docs is that they still depend on old GUPnP:

```
error: Package `gupnp-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `gupnp-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
```

Can you add the following patch https://gitlab.gnome.org/GNOME/rygel/issues/132#note_457444

and `docbook_xsl` and `docbook_xml_dtd_43`?

**Comment by worldofpeace** [comment]
I've done those exact things manually and things at like 
`result-devdoc/share/gtk-doc/html/librygel-core` were empty directories...

**Comment by lightbulbjim** [comment]
I might be doing something wrong but I still get the same build failure with your branch.

**Comment by jtojnar** [comment]
I will take a look on complete fix later. This should be good to go  for now.

**Comment by jtojnar** [comment]
Though maybe we need to link the etc file in rygel module.

**Comment by lightbulbjim** [comment]
Here is my failed build output: https://hastebin.com/inomojigis.sql

**Comment by worldofpeace** [comment]
> I will take a look on complete fix later. This should be good to go for now.

I've runtime tested and it does load `/etc/rygel.conf`.

> Here is my failed build output: https://hastebin.com/inomojigis.sql

The command you used to build was incorrect
```
nix-build '<nixpkgs>' -A gnome3.rygel ~/repos/nixpkgs
```

should be
```
nix-build ~/repos/nixpkgs -A gnome3.rygel
```

By doing `<nixpkgs>` you just built this from nixpkgs of your current system.

**Comment by lightbulbjim** [comment]
> The command you used to build was incorrect
Thanks for the pointer! That did the trick, and it's now building correctly.

I'm new to NixOS and sometimes these things aren't obvious :).

**Comment by worldofpeace** [comment]
> > The command you used to build was incorrect
> 
> Thanks for the pointer! That did the trick, and it's now building correctly.
> 
> I'm new to NixOS and sometimes these things aren't obvious :).

I understand. Thanks for testing :sparkle:

**Pull request merged**
