### PR TITLE
ddclient module: fix module

### PR DESCRIPTION
**Pull request by eduarrrd**
- rewrite to systemd.services
- disable forking to give systemd better control
- verifiably run as ddclient user
- expose ssl option
- unset default value for dyndns server
- rename option "web" to "use" to be consistent with ddclient docs
- add descriptions
- add types to options
- clean up formatting

### CODE REVIEW

**Comment by eduarrrd** [comment]
Anyone willing to review this?

**Comment by bjornfor** [comment]
I had a quick look.

types.string is deprecated; use either 'str' or 'lines'. There is one "ddclient" string literal that can be replaced with ddclientUser attribute. Systemd service descriptions should be capitalized. I suggest "Dynamic DNS Client".

Was the service forking before? (I don't know the "jobs" interface that well.) Well anyway, I was just going to say that forking is just one of the ways systemd can use to know when a service has finished initializing itself and is fully started. Systemd "simple" services (the default type if no Type= is set) are assumed to be ready immediately. That is seldom correct. If another service depend on ddclient, it may be started too early. So be careful with Type=simple.

Otherwise, +1.

**Comment by eduarrrd** [comment]
@bjornfor fixed everything but the type=simple. Reason is that ddclient is by nature async. The moment it forks off it's not "ready" in the sense that it updated the dynamic ip so simple should be appropriate.

Travis failure unrelated as always.

**Comment by lethalman** [comment]
It shouldn't fork at all? I see a `-foreground` option there. So Type=simple is fine.

**Comment by eduarrrd** [comment]
I intentionally disabled forking behavior to get getter log capture. What I was trying to say is that IF forking behavior was kept the point at which it forks is still no indicator of readiness.

**Comment by lethalman** [comment]
@eduarrrd was replying to @bjornfor . It's preferable to use foreground processes for systemd exactly for better logging, so it's fine what you did.

**Comment by bjornfor** [comment]
@lethalman: Huh? How does Type=simple (foreground) help with logging in systemd? Doesn't systemd log everything always, no matter what Type= is? Or were you talking specifically about ddclient, and that it may behave differently (logs more?) when given the -foreground flag?

**Comment by lethalman** [comment]
Usually when forking, daemons do not log to stdout. Systemd benefits from stdout logging if the software doesn't use syslog but it's own log. Also tracing the PID is easier. Don't know specifically about ddclient. But certainly nowadays the pattern is: just make the master process run in foreground, and let the supervisor take care of daemonization.

**Comment by lethalman** [comment]
Merging this. After all ddclient was using `-foreground` before this PR. Let's see how it goes.

**Pull request merged**
