### PR TITLE
kexectools: fix build on i686

### PR DESCRIPTION
**Pull request by worldofpeace**
https://hydra.nixos.org/build/99957229
See: https://src.fedoraproject.org/rpms/kexec-tools/c/cb1e5463b5298b064e9b6c86ad6fe3505fec9298

###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/68361
(maybe gnome3 tests failing on i686)

Not sure how to verify my change on that platform.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by ivan** [comment]
@GrahamcOfBorg build kexectools

**Review by ivan — APPROVED** [review]
I tested this with `nix-env --argstr system i686-linux -iA kexectools` on release-19.09 and confirm that it unbreaks the build.

**Comment by worldofpeace** [comment]
Merged to staging in dc051dfdef1ec4c9bdd90b228764b6c24372597e
and staging-19.09 in b0b3b29e20dd41cd4d7d5af6072f2424f1b11026

**Comment by delroth** [comment]
Can this be moved to staging-next or considered for a fast merge to master? There's quite a lot that's broken without this fix (e.g. any desktop config with 32 bit support enabled, or steam).

**Comment by worldofpeace** [comment]
cc @FRidh @vcunat for staging manipulations.

**Comment by vcunat** [comment]
Worked around the temporary "rebuild conflict" by a715aa7073.

**Pull request closed without merging**
