### PR TITLE
bcachefs-tools: unvendor Cargo.lock

### PR DESCRIPTION
**Pull request by chayleaf**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]
I saw your comment in #267640; thanks. LGTM.

**Comment by chayleaf** [comment]
is Ofborg failing because of import from derivation? is it allowed in nixpkgs?

**Comment by thoughtpolice** [comment]
Ahhh yes, I remember the details of `Cargo.lock` for `buildRustPackage` now. No, IFD is not allowed in Nixpkgs itself, so we have to forbid this. That's my fault for not remembering this gotcha, because...

Normally, this *could* be supported without the lockfile, but the problem is that you need `Cargo.lock` whenever the package in question has Git dependencies. Which the `bch-bindgen` library does, and is required as a dependency of the `rust-src` crate, now that I'm looking at the source.

So, I'm afraid this will have to go on hold. Instead, we should modify `bcachefs-tools` to use a custom update script that can update the version, src hash, cargoHash, *and* the lock file all at once. There are some examples of this stuff around, but I can write a patch for this.

In the meantime, I'm afraid this will have to be held here.

**Review by thoughtpolice — CHANGES_REQUESTED** [review]
(See prior comment.)

**Pull request closed without merging**
