### PR TITLE
mealie: 1.12.0 -> 2.2.0

### LINKED ISSUE #353395: Update request: mealie 1.12.0 → 2.1.0
- Package name: mealie
- Latest released version: 2.1.0

- Current version on the unstable channel: 1.12.0
- Current version on the stable/release channel: 1.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@litchipi 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by litchipi**
Closes #353395 

Didn't test it yet on my home server, for now it builds and nixosTests are OK, but I wan't to be sure it works well (and there's no data lost)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ambroisie** [comment]
From the 2.0 release:

> More details can be found on each PR. Most of these will only be breaking changes for people who are doing custom work with our APIs, and shouldn't impact someone who is just using Mealie as is.

Nonetheless, until the release branch off, we should hold off from merging breaking changes. This doesn't mean we can't review them in the meantime :-).

**Review by anoadragon453 — APPROVED** [review]
Tested on my live `x86-64_linux` deployment and it looks good! -> https://r.amorgan.xyz

I was able to add a recipe from URL, poked around and had a look through the logs for any errors.

No errors are being reported. There's just the `/run/secrets` warning which we're familiar with from previous versions:

```
Nov 16 11:51:31 plonkie mealie[1561880]: WARNING  2024-11-16T11:51:31 - Secrets directory '/run/secrets' cannot be read from. Check permissions
Nov 16 11:51:31 plonkie mealie[1561880]: WARNING  2024-11-16T11:51:31 - Secrets directory '/run/secrets' cannot be read from. Check permissions
```

but this upgrade is unrelated to that.

**Review by ambroisie — APPROVED** [review]
LGTM. I believe the branch off is done, we can merge whenever @litchipi feels ready (ping if I don't notice).

**Comment by litchipi** [comment]
Did some testing too on my side, didn't have any issues, so I think it's safe to merge :smile:

**Pull request merged**
