### PR TITLE
jetbrains: avoid LD_LIBRARY_PATH leaks

### LINKED ISSUE #141593: jetbrains.clion: `$LD_LIBRARY_PATH` leaks into projects as path to search libraries to link
### Describe the bug

JetBrains editors run with `$LD_LIBRARY_PATH=${stdenv.cc.cc.lib}:...` which result in project built under the editors (i.e. `make` in `clion`'s terminal) always picks up `libstdc++.so.6` from `stdenv.cc.cc.lib`.
Even if the project is using for example `gcc11Stdenv`.
This result in ABI conflict when the build executable runs, because other components - which built using `nix-build`, outside clion - use `libstdc++.so.6` from `gcc11Stdenv.cc.cc.lib`

```
/nix/store/7zrjn2j9z86s2ba6gw9dcj1g96crg1xz-gcc-9.2.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/7rf5ciclwwzig5fjiv6bxnprbk9xb1ag-gtest-1.11.0/lib/libgtest.so.1.11.0)
```

https://github.com/NixOS/nixpkgs/blob/5724f5205cce3470f877ae3b807ea459c820ecd9/pkgs/applications/editors/jetbrains/common.nix#L79-L82

### Steps To Reproduce
well, this might be tricky to prepare a small project

### Expected behavior
`stdenv.cc.cc.lib` needed to support `clion` itself, should not leak into projects it edits

### Additional context
I suspect `libsecret` and `libnotify` in `$LD_LIBRARY_PATH` are problematic too

introduced in https://github.com/NixOS/nixpkgs/pull/24526 https://github.com/NixOS/nixpkgs/pull/36246 https://github.com/NixOS/nixpkgs/pull/47656 https://github.com/NixOS/nixpkgs/pull/134616

### Notify maintainers
@miltador @edwtjo 

```

### PR DESCRIPTION
**Pull request by nixdrin**
## Description of changes

See the ~~two~~ three commit messages. I also fixed Rider to properly patch binaries instead of relying on LD_LIBRARY_PATH.

Fixes #141593

I have tested this with CLion, I would appreciate help with testing other IDEs as well to be sure. Expectation is that everything should work as before, but now Nix can be properly used within the IDE terminal.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
  - [x] CLion
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
  - [x] CLion
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LoveIsGrief** [comment]
I'm willing to test this, but I'm not sure how. `nix repl` and `nix-shell -p bash` work without a problem in Pycharm Pro 2023.2.1

**Comment by nixdrin** [comment]
@LoveIsGrief Thanks! You need to run something that conflicts with the libraries that are put into the LD_LIBRARY_PATH (`stdenv.cc.cc.lib libsecret e2fsprogs libnotify udev`). This happens mainly when using packages that are from a much older (or much newer) branch.

For example when I try to run clang from nixos-23.05 inside the CLion terminal it works:

```
$ nix run nixpkgs/nixos-23.05#clang -- -v
clang version 11.1.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/1xga93m9zknb33f2knvykhf09y5994m1-clang-11.1.0/bin
```

but the clang from nixos-22.11 doesn't:

```
$ nix run nixpkgs/nixos-22.11#clang -- -v
/nix/store/8j5j1imf5q913mm0f5yn34nbvr16m1dc-clang-11.1.0/bin/clang: /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/xq05361kqwzcdamcsxr4gzg8ksxrb8sg-gcc-12.3.0-lib/lib/libstdc++.so.6)
```

With the changes in this PR both should work:

```
$ nix run nixpkgs/nixos-22.11#clang -- -v
clang version 11.1.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/8j5j1imf5q913mm0f5yn34nbvr16m1dc-clang-11.1.0/bin
```

There are probably many other examples that are similarly affected, but it varies a lot of course.

**Comment by autrimpo** [comment]
Unfortunately breaks Rider:
```
/nix/store/k8pzjkvfprrfv16hshzyca6w0zplgc3h-rider-2023.2.1/rider/lib/ReSharperHost/linux-x64/Rider.Backend --runtimeconfig /nix/store/k8pzjkvfprrfv16hshzyca6w0zplgc3h-rider-2023.2.1/rider/lib/ReSharperHost/Rider.Backend.netcore.runtimeconfig.json --Port=43143 --enablecpp
/nix/store/k8pzjkvfprrfv16hshzyca6w0zplgc3h-rider-2023.2.1/rider/lib/ReSharperHost/linux-x64/Rider.Backend: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by autrimpo** [comment]
Wow, this works, thank you!

Some other fixes I've tried would run Rider just fine but fail to build anything as they'd conflict with Dotnet loaded from a devshell, but this seems to work well even in that scenario. I've managed to successfully build a project with this :)

**Comment by nixdrin** [comment]
@raphaelr FYI I made some changes to the Rider package to fix the report above (see commit message). The bot didn't ping you automatically for some reason. :)

**Review by raphaelr — APPROVED** [review]
IntelliJ community and Rider work, LGTM. I did also run into this issue in the past, but I didn't know about `jna.library.path`.

`icu` in LD_LIBRARY_PATH used to be required some major versions of rider/dotnet ago, but not anymore it seems.

**Comment by LoveIsGrief** [comment]
I confirm the commands you provided first failed in CLion and now they work with the one from your PR :+1:  Good job :slightly_smiling_face:

**Review by ghost — APPROVED** [review]
Works for me!

**Review by wegank — APPROVED** [review]

**Pull request merged**
