### PR TITLE
haskellPackages.haskell-language-server: Fix build

### PR DESCRIPTION
**Pull request by maralorn**
In preparation of the upcoming 0.6.0 release I wanted to fix hls.

It introduces two new plugin packages, which are not on hackage yet.

I remove apply-refact overrides, because current apply-refact versions
are compatible with all ghcs we support, according to their changelog.

I override more of the hls dependencies globally on the whole package
set, to avoid a lot of duplicate compilations. And because @peti changed
my mind about this being a good practice.

hls now uses a released version of ghcide

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
@GrahamcOfBorg build haskell-language-server
@GrahamcOfBorg build haskellPackages.ghcide
@GrahamcOfBorg build haskellPackages.brittany

**Comment by maralorn** [comment]
@ofBorg eval

**Review by cdepillabout — APPROVED** [review]
This looks pretty reasonable.

**Comment by maralorn** [comment]
Okay, then I'll merge now and monitor hydra closely until friday, to see if it had any unintended side-effects.

**Comment by maralorn** [comment]
Everything builds fine. We now have hls 0.6.0 which was released a few hours ago. Can‘t wait to have it in unstable.

**Pull request merged**
