### PR TITLE
home-assistant: 0.93.2 -> 0.96.2

### PR DESCRIPTION
**Pull request by delroth**
###### Motivation for this change
0.93.2 is currently broken on master because it uses an old version of pyyaml that seems to have incompatibilities with recent Python interpreters. 0.96.2 has a fix for this, so bumping seems valuable.

This also bumps a few Python dependencies of home-assistant. While not technically necessary since the home-assistant derivation has version overrides anyway, I would feel bad having newer versions pinned in home-assistant that aren't available in nixpkgs natively.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by delroth** [comment]
FYI @f-breidenstein @dotlambda HASS maintainers.

**Comment by delroth** [comment]
@GrahamcOfBorg test home-assistant

**Comment by andir** [comment]
I added a change that updates the maintainer handle of @f-breidentein to @fleaz. He changed that a while ago.

**Comment by oscarcarlsson** [comment]
How is this PR going? I'd love to see it merged.

**Comment by FRidh** [comment]
Some relevant updates are in staging. It's best rebased onto staging at this point.

**Comment by lheckemann** [comment]
Fixes #66510

**Pull request merged**
