### PR TITLE
sbcl: make deriv options overridable attributes

### PR DESCRIPTION
**Pull request by hraban**
## Description of changes

This also makes the options available for reading by other derivations which depend on SBCL. This is useful for derivations who want to evaluate differently based on the capabilities of the SBCL derivation they're passed. Eexample: bordeaux-threads depends on a specific feature of SBCL (threads): having the `.threadSupport` value readable from the derivation at runtime allows bordeaux-thread to set `meta.broken = true` for an SBCL without thread support.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by kini — APPROVED** [review]
LGTM, thanks!

**Comment by Uthar** [comment]
Hmm - I would put the options in passthru - this is how the Emacs package does it for checking "withNativeCompilation".

**Comment by hraban** [comment]
> Hmm - I would put the options in passthru - this is how the Emacs package does it for checking "withNativeCompilation".

Interesting. Any particular reason? Passthru isn't available to the actual derivation in the end which makes sense for non-fundamental types but I'm curious what the motivation is for putting regular flags on passthru. Maybe I'm personally a bit too jaded by the emacs derivation to take much stock in it as prior art 😂 I looked around at other derivations but I have a feeling it's quite haphazard across the board.

**Comment by Uthar** [comment]
It's only my taste :-)

We could make all assertions at the start (kind of like check-type/declare in lisp) - which feels more "organized" - assertions are separate from build logic. For example:

```
{

...

# Build options  
, threadSupport ? (stdenv.hostPlatform.isx86 || "aarch64-linux" == stdenv.hostPlatform.system || "aarch64-darwin" == stdenv.hostPlatform.system)
, linkableRuntime ? stdenv.hostPlatform.isx86
, disableImmobileSpace ? false
, purgeNixReferences ? false
, coreCompression ? true
, markRegionGC ? threadSupport
}:

assert coreCompression -> !purgeNixReferences;
assert markRegionGC -> threadSupport;

let ...
```

Similarly - build-time env variables inside mkDerivation  are separate from build options. These options can be used to decide on those flags/vars, but themselves are "metadata". Then it's more immediately visible, what is build-internal and what is "exported". (in passthru attrset).

**Comment by Uthar** [comment]
SO perhaps a reason is to keep overrideAttrs for attrs specific to mkDerivation , and use override for customizations on top of that. But it's hard to find the one true convention in nixpkgs (-:

> Feels like we want the opposite for these values, right? Definitely trigger a rebuild--that's kinda the point. Fundamentally different derivation.

I think it's for cases with `.pkgs` style sets, so as not to cause havoc. In the case if it's referenced inside mkDerivation it will re-build correctly.

**Comment by hraban** [comment]
> > Feels like we want the opposite for these values, right? Definitely trigger a rebuild--that's kinda the point. Fundamentally different derivation.
> 
> I think it's for cases with `.pkgs` style sets, so as not to cause havoc. In the case if it's referenced inside mkDerivation it will re-build correctly.

That's a totally fair point!

Re the assertions sprinkled throughout: I've kept them close to the point of use so they don't trip people up who want to override them, e.g.:

https://github.com/NixOS/nixpkgs/blob/1acef6e636e4111933dfd0213ee20ffaafe997c7/pkgs/development/compilers/sbcl/default.nix#L86-L93

I thought this would strike a nice balance between failing loud, but leaving the ultimate decision with the user. I like the idea of leaving the user in charge if they insist on using incompatible flags, e.g. to test a build which does in fact support that combination. What do you think?

Re the derivation: I think I see why you prefer passthru. I realize I see derivations as more bespoke and case-by-case, where `mkDerivation` (and on a lower level `stdenv`) is just a framework _on top_ of which you build your derivation. I also thought that any value stored as a direct property on the derivation itself (i.e. passed as a env to the builder) would also be available after an `import my-derivation.drvPath`, which was already abstruse enough but also turns out to be entirely wrong. So there goes that.

I guess all I have to go off of is a "feeling" that it's nice to have the flags which control the build process live directly on the derivation rather than incidentally in an `override` tacked on to the object which represents the derivation. It's a very weak intuition so I'm happy to go your way!

**Comment by Uthar** [comment]
ah - I see - yes like this the asserts can be overridden out, unlike on top-level - quite nice.

>  I also thought that any value stored as a direct property on the derivation itself (i.e. passed as a env to the builder) would also be available after an import my-derivation.drvPath

Theoretically one could `builtins.readFile x.drvPath` and parse it - I don't know about "pure evaluation mode" though. (One might get dark side points for this).

Hmm a little bit out of scope - but regarding the zstd case - for linux we could allow compression + purge by using a static libzstd.a - I don't know about macos.

> I guess all I have to go off of is a "feeling" that it's nice to have the flags which control the build process live directly on the derivation 

heh, they say one should follow their gut feeling - go for it (-:

**Comment by hraban** [comment]
@7c6f434c what are your thoughts? Ready to merge?

**Comment by 7c6f434c** [comment]
I am honestly a bit confused that `mkDerivation` now allows this! But yeah, any other option is prone to forgetting to inherit something…

**Pull request merged**
