### PR TITLE
eclipses: 2023-09 -> 2023-12

### PR DESCRIPTION
**Pull request by jerith666**
## Description of changes

As usual I'd appreciate if someone could test on `aarch64-linux`.  Will use for a couple of days at work next week and report back here.

Previous update is #258421.

cc @rycee @OPNA2608 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 277241` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>eclipses.eclipse-dsl</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>eclipses.eclipse-committers</li>
    <li>eclipses.eclipse-cpp</li>
    <li>eclipses.eclipse-java</li>
    <li>eclipses.eclipse-jee</li>
    <li>eclipses.eclipse-modeling</li>
    <li>eclipses.eclipse-platform</li>
    <li>eclipses.eclipse-rcp</li>
    <li>eclipses.eclipse-sdk</li>
  </ul>
</details>
<hr/>



```
error: hash mismatch in fixed-output derivation '/nix/store/p9p5syvilry2jq5ldgz5w126sfal1gb8-eclipse-dsl-2023-12-R-linux-gtk-aarch64.tar.gz.drv':
         specified: sha256-GPgD29d81YFtHtqqb66io1BwbNuHTqVZYrY4Oh4MojQ=
            got:    sha256-wuh6IZtRPDNJAVcfukFjZfuOVJgfj2zI616YNDnRgWM=
error: 1 dependencies of derivation '/nix/store/nf4w0j6ya45xm8ag4bk29rchq18lspms-eclipse-dsl-4.30.drv' failed to build

```

**Comment by OPNA2608** [comment]
Your branch lacks https://github.com/NixOS/nixpkgs/commit/b18f8aa7040ead350d5da0b0ee07c2d596d6ebd3 so the new `eclipses.eclipse-dsl` didn't get updated hashes.

**Comment by kirillrdy** [comment]
> Your branch lacks [b18f8aa](https://github.com/NixOS/nixpkgs/commit/b18f8aa7040ead350d5da0b0ee07c2d596d6ebd3) so the new `eclipses.eclipse-dsl` didn't get updated hashes.

i assume this meant for @jerith666 

nixpkgs-review usually evaluates against a merge of PR and tracking remote

**Comment by jerith666** [comment]
Ugh, sorry -- will fix tonight!

**Comment by OPNA2608** [comment]
`dsl` variant launches fine under my Wayland compositor of choice on x86_64-linux. On X11 Pantheon all variants fail spectacularly, I think just like they did the last time I tried to check `eclipses.*` on this system?

1. Window decorations disappear, all workspaces are merged into one, nightmode deactivates
2. A second or so later, everything returns to normal (except nightmode, which stays broken)
3. No window is being shown for eclipse, even though terminal output indicates that it's still running
4. Ctrl+C & attempting to launch it again crashes the whole session for good

For your issue, maybe it's picking up some config from another eclipse version that's causing issues with it? You could try overriding `HOME` or whatever it uses to find the user's eclipse configurations and check if that fixes your issue.

I'll give it a try on aarch64-linux tonight.

**Comment by jerith666** [comment]
Ah, you're right -- blowing away `~/.eclipse` got rid of that error, so false alarm -- sorry!

Eclipse has always worked fine for me under X11 + KDE with Intel graphics, and continues to do so with this update.

**Review by OPNA2608 — APPROVED** [review]
Checked building all of the available variants, as well as running `eclipse-dsl`, `eclipse-java` and `eclipse-cpp`, on `aarch64-linux`. LGTM.

**Pull request merged**
