### PR TITLE
libxml2: 2.10.0 → 2.10.2

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

Without this, parsing HTML using `DomDocument` when running a script using `mod_php` on Apache seems to create an empty document: https://gitlab.gnome.org/GNOME/libxml2/-/issues/399

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Nice !

**Comment by mweinelt** [comment]
Doesn't break any of postgresql's tests, so I think we'll give it a shot.

**Comment by vcunat** [comment]
Broke stdenv bootstrapping on darwin:
https://hydra.nixos.org/log/c1xy2yq1rglnahjzgkrb2g2hg6y8rr5k-libxml2-2.10.2.drv
https://hydra.nixos.org/log/qv843asd2ddf7f3l04kgcqcg89iwrxzp-libxml2-2.10.2.drv

/cc PR #195862

**Comment by jtojnar** [comment]
This is probably caused by the [removal of generated files from the tarball](https://gitlab.gnome.org/GNOME/libxml2/-/commit/b706824b612adb2c8255819c9a55e78b52774a3c) requiring us to build them ourselves. And that likely fails because expat is not available in the python used for the build.

**Pull request merged**
