### PR TITLE
nano-wallet: init at 12.1

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

~~**NOTE: This is work in progress. Hope to get some help and feedback here.**~~

**Ready to merge now**

This is a wallet for the Nano cryptocurrency (previously known as Raiblocks).
- https://nano.org/en/wallet/
- https://github.com/nanocurrency/raiblocks

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jluttine** [comment]
I updated cmake to 3.11.1 but still got the same error.

**Comment by jluttine** [comment]
It looks as if those libraries don't exist in boost 1.66, only in other versions:

```
$ nix-locate boost_date_time
boost.out                                             0 s /nix/store/jyqzqqlz6xflv17k96m10qh8r8625274-boost-1.65.1/lib/libboost_date_time.so
boost.out                                        93,528 x /nix/store/jyqzqqlz6xflv17k96m10qh8r8625274-boost-1.65.1/lib/libboost_date_time.so.1.65.1
boost159.out                                          0 s /nix/store/wxxbx95qx911zmid07my7l6ng9272lyp-boost-1.59.0/lib/libboost_date_time.so
boost159.out                                     97,496 x /nix/store/wxxbx95qx911zmid07my7l6ng9272lyp-boost-1.59.0/lib/libboost_date_time.so.1.59.0
boost164.out                                          0 s /nix/store/xkbgk23p15fbng3594wl9mj2951jayjs-boost-1.64.0/lib/libboost_date_time.so
boost164.out                                     93,344 x /nix/store/xkbgk23p15fbng3594wl9mj2951jayjs-boost-1.64.0/lib/libboost_date_time.so.1.64.0
boost155.out                                          0 s /nix/store/g9cnchkmqn0ad4qh2rnnj27fr8yggndh-boost-1.55.0/lib/libboost_date_time.so
boost155.out                                     97,256 x /nix/store/g9cnchkmqn0ad4qh2rnnj27fr8yggndh-boost-1.55.0/lib/libboost_date_time.so.1.55.0
boost160.out                                          0 s /nix/store/dwnn9wpzcqph9337bv7k59b1q28zxxh0-boost-1.60.0/lib/libboost_date_time.so
boost160.out                                     93,272 x /nix/store/dwnn9wpzcqph9337bv7k59b1q28zxxh0-boost-1.60.0/lib/libboost_date_time.so.1.60.0
boost162.out                                          0 s /nix/store/argiiirlbch51dnmv9jagc9741fridmq-boost-1.62.0/lib/libboost_date_time.so
boost162.out                                     93,272 x /nix/store/argiiirlbch51dnmv9jagc9741fridmq-boost-1.62.0/lib/libboost_date_time.so.1.62.0
boost163.out                                          0 s /nix/store/012czf6nbqqk3mjyd4qz39nwv9lqfq5i-boost-1.63.0/lib/libboost_date_time.so
boost163.out                                     93,344 x /nix/store/012czf6nbqqk3mjyd4qz39nwv9lqfq5i-boost-1.63.0/lib/libboost_date_time.so.1.63.0
python36Packages.boost.out                            0 s /nix/store/g2ia26w0y81jhb83950ggflqiw7bmgjr-boost-1.65.1/lib/libboost_date_time.so
python36Packages.boost.out                       93,528 x /nix/store/g2ia26w0y81jhb83950ggflqiw7bmgjr-boost-1.65.1/lib/libboost_date_time.so.1.65.1
autoconf-archive.out                              4,510 r /nix/store/6hskp2vbvvbz2lz5cvvp6wj9yz9gmxip-autoconf-archive-2017.03.21/share/aclocal/ax_boost_date_time.m4
```

However, build requires boost 1.66, it raises an error otherwise..

**Comment by jluttine** [comment]
I guess the problem is that the nano wallet is forcing static libraries: https://github.com/nanocurrency/raiblocks/blob/V12.1/CMakeLists.txt#L122

I'll try patching that line and see if I can then set `Boost_USE_STATIC_LIBS` to `OFF`.

**Comment by jluttine** [comment]
Yes! That was it! So that is solved. Now I'm getting the following error:

```
CMake Error at CMakeLists.txt:356 (qt5_add_resources):
  Unknown CMake command "qt5_add_resources".


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
See also "/build/source/build/CMakeFiles/CMakeError.log".
builder for '/nix/store/2z1c5w329c9x0n31q6z882af86cw9r7j-nano-wallet-12.1.drv' failed with exit code 1
error: build of '/nix/store/2z1c5w329c9x0n31q6z882af86cw9r7j-nano-wallet-12.1.drv' failed
```

Gotta see how to add those Qt5 resources some other day. Any pointers are appreciated, because I have no idea at the moment but will of course dig into it.

**Comment by jluttine** [comment]
Ok, solved that one and a bunch of other failures. Now I'm getting this error:
```

[ 94%] Building CXX object CMakeFiles/qt.dir/rai/qt/qt.cpp.o
In file included from /nix/store/8ba9lhzdr13w4vqpam9ss52cq5svrpbk-qtbase-5.10.1-dev/include/QtGui/QtGui:43:0,
                 from /build/source/rai/qt/qt.hpp:9,
                 from /build/source/rai/qt/qt.cpp:1:
/nix/store/8ba9lhzdr13w4vqpam9ss52cq5svrpbk-qtbase-5.10.1-dev/include/QtGui/qopengl.h:141:13: fatal error: GL/gl.h: No such file or directory
 #   include <GL/gl.h>
             ^~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/qt.dir/build.make:63: CMakeFiles/qt.dir/rai/qt/qt.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:634: CMakeFiles/qt.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:693: CMakeFiles/nano_wallet.dir/rule] Error 2
make: *** [Makefile:381: nano_wallet] Error 2
builder for '/nix/store/zbljdf8kx5nz404ki99aln0rjzh1ds6h-nano-wallet-12.1.drv' failed with exit code 2
error: build of '/nix/store/zbljdf8kx5nz404ki99aln0rjzh1ds6h-nano-wallet-12.1.drv' failed
```

I don't understand. As far as I understand, I've added GL/gl.h to include path...

**Comment by jluttine** [comment]
Ok, thanks to some tips, that's solved too. Needed to add `mesa` as a build input instead. Continuing now with other build failures...

**Comment by jluttine** [comment]
The name is now `nano-wallet`. Should it be `nano_wallet` or `nanoWallet`? The executable is `nano_wallet`.

**Comment by srhb** [comment]
I'm afraid this had sat long enough that it no longer evaluates on master due to the mesa changes. Can you try and rebase and look into that?

**Comment by jluttine** [comment]
@srhb Thanks, should be fixed now! (I rebased on nixos-unstable..)

**Comment by srhb** [comment]
@GrahamcOfBorg build nano-wallet

**Comment by jluttine** [comment]
I have no idea how to fix that build error on Darwin...

**Comment by srhb** [comment]
@jluttine OK, could you limit meta.platforms to linux then? Should be good to go then. :)

**Comment by jluttine** [comment]
@srhb Ok, done!

**Pull request merged**
