### PR TITLE
linux-testing-bcachefs: 4.11.2017.08.23 -> 4.13.2018.01.03

### PR DESCRIPTION
**Pull request by dywedir**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dywedir** [comment]
cc @davidak

**Comment by davidak** [comment]
@dywedir thank you very much. I still had no time to test it.

Have you tested creating a bcachefs filesystem with the kernel?

Could you update it again to include the latest changes?

https://www.patreon.com/posts/filesystem-is-16192149

**Comment by dywedir** [comment]
@davidak yes, works fine for me

Just compiled from the latest commit, I'll post update after a little testing

**Comment by dywedir** [comment]
Done!

**Comment by Chiiruno** [comment]
Any updates on this?

**Comment by dywedir** [comment]
@Chiiruno I would like to wait for relocation to 4.15

**Comment by dywedir** [comment]
cc @Mic92

**Comment by davidak** [comment]
Why have you closed it?

**Comment by dywedir** [comment]
Just impulsively recreated PR :)
https://github.com/NixOS/nixpkgs/pull/34792

**Pull request closed without merging**
