### PR TITLE
portaudio: apple-sdk migration

### PR DESCRIPTION
**Pull request by matteo-pacini**
- Migrated `portaudio` to the new implicit `apple-sdk` (references to Darwin frameworks have been removed)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matteo-pacini** [comment]
@emilazy Should I use `apple-sdk` or `apple-sdk_11` here (in lieu of #352129)?

**Comment by doronbehar** [comment]
Hmm maybe the musescore change can be decoupled from the portaudio change? Although they are related? It's just that changes to musescore alone don't need to go through `staging`, and not only that, I'm updating musescore in #353207 , so there's a small chance of merge conflicts.

**Comment by emilazy** [comment]
There is never any reason to specify plain `apple-sdk` as a dependency; it is implicit in all builds. The 11.3 PR will rebuild every single package, so there is no concern there. Just add whatever is required for full functionality. I see no availability conditionals or SDK checks in PortAudio so it probably needs no SDK dependency at all. Since it depends on Qt, however, it will inherit the macOS 12 SDK anyway.

Grepping for `__builtin_available` in the MuseScore repository turns up a few `__builtin_available(macOS 11.0, *)` results, so it wants `apple-sdk_11`.

**Comment by matteo-pacini** [comment]
@doronbehar Works for me, I've just dropped the commit re MuseScore

@emilazy thanks for the wisdom 🙏🏻

**Comment by emilazy** [comment]
PortAudio doesn’t seem to need any SDK override at all, per my previous comment. It can just be dropped entirely.

**Comment by doronbehar** [comment]
> @doronbehar Works for me, I've just dropped the commit re MuseScore

But will it be required once this `portaudio` commit reaches `master`? Or perhaps I can cherry pick that lost `musescore` commit to `master` right now? Even without the change to `portaudio`?

**Comment by emilazy** [comment]
No coupling at all. Both can happen at any point.

**Comment by emilazy** [comment]
Oh, `musescore` does overrides… Then yes, they’ll both need adjusting, since those overrides are now pointless.

**Comment by matteo-pacini** [comment]
[According to the docs,](https://github.com/NixOS/nixpkgs/blob/master/doc/stdenv/platform-notes.chapter.md) if I add another `apple-sdk_*` to the build inputs, the highest SDK is selected.

Would this patch do for `musescore`?

```patch
diff --git a/pkgs/applications/audio/musescore/default.nix b/pkgs/applications/audio/musescore/default.nix
index 6f28bf98a1b1..64fd9456da22 100644
--- a/pkgs/applications/audio/musescore/default.nix
+++ b/pkgs/applications/audio/musescore/default.nix
@@ -31,24 +31,14 @@
 , qtnetworkauth
 , qttools
 , nixosTests
-, darwin
+, apple-sdk_11
 }:
 
 let
-  stdenv' = if stdenv.hostPlatform.isDarwin then darwin.apple_sdk_11_0.stdenv else stdenv;
-  # portaudio propagates Darwin frameworks. Rebuild it using the 11.0 stdenv
-  # from Qt and the 11.0 SDK frameworks.
-  portaudio' = if stdenv.hostPlatform.isDarwin then portaudio.override {
-    stdenv = stdenv';
-    inherit (darwin.apple_sdk_11_0.frameworks)
-      AudioUnit
-      AudioToolbox
-      CoreAudio
-      CoreServices
-      Carbon
-    ;
-  } else portaudio;
-in stdenv'.mkDerivation (finalAttrs: {
+  portaudio' = if stdenv.hostPlatform.isDarwin then portaudio.overrideAttrs(oldAttrs: {
+    buildInputs = oldAttrs.buildInputs ++ [ apple-sdk_11 ];
+  }) else portaudio;
+in stdenv.mkDerivation (finalAttrs: {
   pname = "musescore";
   version = "4.4.2";
 
@@ -145,7 +135,7 @@ in stdenv'.mkDerivation (finalAttrs: {
     alsa-lib
     qtwayland
   ] ++ lib.optionals stdenv.hostPlatform.isDarwin [
-    darwin.apple_sdk_11_0.frameworks.Cocoa
+    apple-sdk_11
   ];
 
   postInstall = ''
```

**Comment by doronbehar** [comment]
> I add another `apple-sdk_*` to the build inputs, the highest SDK is selected.

Sounds like an unnecessary risk, why not simply `.override` it ?

**Comment by matteo-pacini** [comment]
@doronbehar  `apple-sdk` is coming from Darwin's `stdenv` itself now, as @emilazy pointed out,  it's an `extraBuildInput` according to this (hopefully I am looking at the right bit):

https://github.com/NixOS/nixpkgs/blob/2f45b7ffd7297dd721a747e8d8399abb84ccf1ab/pkgs/stdenv/darwin/default.nix

In other packages requiring `apple-sdk_11` (i.e. games that require Metal), I add that to the build inputs, and it overrides `apple-sdk`, so I think this approach would work.

Tagging also @reckenrode as he may have more insights - what would be the idiomatic/recommended  way to override the implicit `apple-sdk` with `apple-sdk_11` in derivations?


Sorry for the chaos, just trying to understand what the best pattern would be with

**Comment by reckenrode** [comment]
I apologize for the lack of clarity. I’m working on a documentation update for the new SDK, and I’ll add this situation. The recommended pattern is to add the SDK to your `buildInputs`. It is not necessary or recommended to override the one in the `stdenv`.

Unlike the old SDK pattern, there’s no risk from having multiple SDKs in your inputs. In fact, the SDK is designed with that situation in mind (because it turns out that it’s impossible to avoid in the general case). If there are multiple ones (from the `stdenv`, propagation, your inputs, etc), the highest version is chosen. The SDK uses a hook to do that.

https://github.com/NixOS/nixpkgs/blob/a86d06940e17a4c236d9ea3cefdd323cad362679/pkgs/by-name/ap/apple-sdk/setup-hooks/sdk-hook.sh

If you _really_ need to ensure that derivations using your package as a dependency use at least a certain version, you can add it as a `propagatedBuildInput`. If your package is expected to be added as a `nativeBuildInput`, use `depsTargetTargetPropagated` instead.

However, other than compilers, it’s usually a bad idea to propagate the SDK. It becomes part of your package’s public API, making changing the propagated SDK version becomes a potentially breaking change. (The current version of the documentation suggests otherwise, but it is being revised to reflect this new guidance.)

**Comment by doronbehar** [comment]
> Unlike the old SDK pattern, there’s no risk from having multiple SDKs in your inputs. In fact, the SDK is designed with that situation in mind (because it turns out that it’s impossible to avoid in the general case). If there are multiple ones (from the `stdenv`, propagation, your inputs, etc), the highest version is chosen.

So is it possible (as in the musescore case) to build a package using an old SDK and building the dependencies of it with the same old SDK?

**Comment by emilazy** [comment]
You don't need to do anything fancy. Just use PortAudio as a normal dependency, no overrides, no propagation. The override stuff was hacking around flaws of the old pattern.

**Comment by reckenrode** [comment]
> So is it possible (as in the musescore case) to build a package using an old SDK and building the dependencies of it with the same old SDK?

To elaborate on @emilazy’s comment, the legacy SDK had problems with propagated packages, which is what Qt did. It propagated a bunch of different frameworks. In the legacy, frameworks were normal packages. If you had CoreAudio 11.0 and CoreAudio 12.3, you’d have to versions of effectively the same framework. These would get mixed, and your build would break (usually with an error related to punctuation).

The solution for the legacy SDK was to do a bunch of hackery (using `overrideSDK`) to replace those propagated frameworks with the ones for the preferred SDK. Qt (for example) would still be built with whatever SDK it used, but you would get the frameworks you needed for your package. Usually. Unfortunately, there are ways to propagate packages that are invisible from Nix (e.g., setup hooks, interpolating a package’s path in a phase script, etc).

The new SDK works by defining the SDK as a sysroot at `SDKROOT` (and a path to all the SDK bits at `DEVELOPER_DIR`). There can only ever be one sysroot at that environment variable. If you add every single SDK to your `buildInputs`, their hooks will cause `SDKROOT` to point to the SDK with the highest version (probably 15.0). Both cc-wrapper and bintools-wrapper as well as some tooling understand this variable (e.g., CMake will pick it up and do the right thing).

That’s why there’s no risk from having multiple SDKs. The hooks resolve them to one SDK always. The issue with propagation caused by Qt (and other libraries) is being avoided by advising against it for all but language implementations that require it. musecore and portaudio can use whatever SDKs that are appropriate for them even if those are different versions. The goal is for packages not to have to care about SDKs except when they need to use a non-default one.

**Comment by matteo-pacini** [comment]
I'm now trying to rebuild `musescore` without the `portaudio` override, to see if it works.

SDK versions:
`portaudio` -> `apple-sdk` (implicit)
`musescore` ->  `apple-sdk_11` (explicit)
 
Going to report here once it's done building.

```patch
diff --git a/pkgs/applications/audio/musescore/default.nix b/pkgs/applications/audio/musescore/default.nix
index 6f28bf98a1b1..100034b998e4 100644
--- a/pkgs/applications/audio/musescore/default.nix
+++ b/pkgs/applications/audio/musescore/default.nix
@@ -31,24 +31,10 @@
 , qtnetworkauth
 , qttools
 , nixosTests
-, darwin
+, apple-sdk_11
 }:
 
-let
-  stdenv' = if stdenv.hostPlatform.isDarwin then darwin.apple_sdk_11_0.stdenv else stdenv;
-  # portaudio propagates Darwin frameworks. Rebuild it using the 11.0 stdenv
-  # from Qt and the 11.0 SDK frameworks.
-  portaudio' = if stdenv.hostPlatform.isDarwin then portaudio.override {
-    stdenv = stdenv';
-    inherit (darwin.apple_sdk_11_0.frameworks)
-      AudioUnit
-      AudioToolbox
-      CoreAudio
-      CoreServices
-      Carbon
-    ;
-  } else portaudio;
-in stdenv'.mkDerivation (finalAttrs: {
+stdenv.mkDerivation (finalAttrs: {
   pname = "musescore";
   version = "4.4.2";
 
@@ -129,7 +115,7 @@ in stdenv'.mkDerivation (finalAttrs: {
     libpulseaudio
     libsndfile
     libvorbis
-    portaudio'
+    portaudio
     portmidi
     flac
     libopusenc
@@ -145,7 +131,7 @@ in stdenv'.mkDerivation (finalAttrs: {
     alsa-lib
     qtwayland
   ] ++ lib.optionals stdenv.hostPlatform.isDarwin [
-    darwin.apple_sdk_11_0.frameworks.Cocoa
+    apple-sdk_11
   ];
 
   postInstall = ''

```

**Comment by matteo-pacini** [comment]
Screenshot 2024-11-05 at 10 59 36

Took ages, but I'm happy to report that removing the `portaudio` override from `musescore`, and migrating `musescore` to the `apple-sdk` pattern, yields a usable build.

@doronbehar please have a look at my latest commit - the `portaudio` override is not needed anymore 

@emilazy @reckenrode thanks for input, really appreciate it

**Review by doronbehar — APPROVED** [review]
Changes look very good! Very happy to finally see how these apple stuff become so much cleaner.

**Review by emilazy — APPROVED** [review]

**Pull request merged**
