### PR TITLE
Gambit 4.9.5

### PR DESCRIPTION
**Pull request by fare**
## Description of changes

Update Gambit stable and unstable respectively to latest release 4.9.5 and a commit shortly after said release.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Hm, does Gerbil need either update or an older pinned version of Gambit?

**Comment by fare** [comment]
Yes, Gerbil most certainly needs an update, but then I must refactor POP out of it, and/or move POP from lib/ to pkgs/development/compilers/gerbil/lib or some such in my branch (suggestions welcome).

**Comment by 7c6f434c** [comment]
Hm, if it uses enough POP that refactoring it out would be nontrivial, I guess in my current state of annoyance with various things I will just personally merge the inclusion POP as support scaffolding for Gerbil and then complain about the many drawbacks of the module system at anyone who'd say I shouldn't have merged…

**Comment by fare** [comment]
I'll be removing POP from the gerbil nix configuration and using more primitive ways to extend my private nix configurations. Not worth the fight.

**Pull request merged**
