### PR TITLE
[21.11] perlPackages.CompressRawZlib: doCheck = false; for now

### PR DESCRIPTION
**Pull request by vcunat**
Failure triggered by the (security) zlib update in PR #166610.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
- I'm filing this at 21.11, as that's about to be finished, but soon we'll also want to address it in staging-next (or master later).  It's possible that upstream will better analyze the failure in the meantime.
- I checked building `libreoffice` and `hydra-unstable`.  Missing `libreoffice*` would surely cause upgrading issues to many users, perhaps leaving their systems with insecure zlib instead.

**Review by trofi — APPROVED** [review]

**Comment by stigtsp** [comment]
https://github.com/pmqs/Compress-Raw-Zlib/issues/7
https://github.com/pmqs/Compress-Raw-Zlib/issues/6

**Comment by stigtsp** [comment]
Result of `nixpkgs-review pr 166910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>odpdown</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>jpsxdec</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>unoconv</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>hydra-unstable</li>
    <li>perl532Packages.CompressRawZlib</li>
    <li>perl532Packages.IOCompress (perl532Packages.CompressZlib)</li>
    <li>perl534Packages.CompressRawZlib</li>
    <li>perl534Packages.IOCompress (perl534Packages.CompressZlib)</li>
  </ul>
</details>

I'm getting build failures in `libreoffice`, checking if they are related:

```
[PKG] canvas_opengl_shader
[GPF] CustomTarget/oox/generated/tokenhash.inc
[PKG] UIConfig/modules/schart
[XCM] connectivity/registry/calc/org/openoffice/Office/DataAccess/Drivers-calc.xcu
[XCU] connectivity/registry/calc/org/openoffice/Office/DataAccess/Drivers.xcu
java.util.zip.ZipException: invalid entry CRC (expected 0x499bcaae but got 0xb38376cd)
        at java.base/java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:409)
        at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:198)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at jdk.jartool/sun.tools.jar.Main.copy(Main.java:1233)
        at jdk.jartool/sun.tools.jar.Main.update(Main.java:962)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:338)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1665)
[LNK] StaticLibrary/libtransex.a
[UPK] 17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip
make[1]: *** [/build/libreoffice-7.2.5.2/ridljar/Jar_unoloader.mk:10: /build/libreoffice-7.2.5.2/instdir/program/classes/unoloader.jar] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:289: build] Error 2
```

**Comment by stigtsp** [comment]
@GrahamcOfBorg build libreoffice

**Comment by stigtsp** [comment]
I'm speculating that the build failures in `libreoffice` may be caused by some incompatibility with the bundled zlib in `libreoffice`, seeing that both the `fresh` and `still` variants reference a zlib-1.2.11 tarball. Maybe not related to `perlPackages.CompressRawZlib`. Cc: @7c6f434c 

https://github.com/NixOS/nixpkgs/blob/2cecd003b5d0694422ebb3eedfecfb5064260567/pkgs/applications/office/libreoffice/src-fresh/download.nix#L863-L869
https://github.com/NixOS/nixpkgs/blob/2cecd003b5d0694422ebb3eedfecfb5064260567/pkgs/applications/office/libreoffice/src-still/download.nix#L877-L883

**Comment by stigtsp** [comment]
@GrahamcOfBorg build libreoffice-fresh
@GrahamcOfBorg build libreoffice-still

**Comment by 7c6f434c** [comment]
Hm, and presumably the same will happen on `staging-next` once the tests are also disabled there?

**Comment by vcunat** [comment]
But why did the `libreoffice` build succeed for me then?

**Comment by 7c6f434c** [comment]
Could we try applying https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 to zlib as seems to be recommended in https://github.com/madler/zlib/issues/613 to work around a `jar` bug (which sounds very relevant)? Maybe even the tests here would pass then…

**Comment by mweinelt** [comment]
> Could we try applying https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 to zlib as seems to be recommended in https://github.com/madler/zlib/issues/613 to work around a `jar` bug (which sounds very relevant)? Maybe even the tests here would pass then…

Tried yesterday, didn't fix this problem.

**Comment by vcunat** [comment]
It might be relevant to the `libreoffice` fail above.  Though I didn't reproduce it, and `libreoffice-fresh` also succeed for me.

**Comment by vcunat** [comment]
OfBorg confirmed successful build of both on x86_64-linux, too.  Let me merge, as the failure really will cause issues to users.

**Pull request merged**
