### PR TITLE
buildbot: use python3Packages

### LINKED ISSUE #45782: buildbot broken by pylint upgrade
## Issue description

Following [this commit](https://github.com/NixOS/nixpkgs/commit/7f698253346ab5d24e2461ca86aad06a264ff70a) to upgrade `pylint`, `buildbot` no longer builds -- it uses Python 2.7, depends on `pylint`, and the latest `pylint` has `disabled = pythonOlder "3.4"`.

### Steps to reproduce

Try to install the `buildbot` package.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.5-arch1-1-ARCH, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(iross): `"nixpkgs-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/home/iross/.nix-defexpr/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
fixes #45782 

Some tests are still failing, but I don't have enough time right now to fix this. Help is very welcome.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @ian-ross

### CODE REVIEW

**Comment by lopsided98** [comment]
I've been running buildbot using Python 3 for nearly a year (see: https://github.com/lopsided98/nixpkgs/compare/7db611f2af869bac6e31ba814a5593c52d54ec19...8853014ef965eee7d0ea0223a7b6c3292e2a4b89), but I never submitted the code upstream because I couldn't get tests to pass and also I wrote it when I wasn't very experienced with Nix and never got around to cleaning it up.

Yesterday I submitted #45763, which updates sphinx-jinja and adds Python 3 support (mostly the same as your commit).

I also updated tempita to use a fork that fixes the tests with Python 3 (see #39692), because tempita is seemingly abandoned. This fork is also used by the official Arch Linux package.

Switching to Python 3 has the potential to break deployments because buildbot's configuration files are written in Python. That was why I tried to make the Python version configurable.

**Comment by FRidh** [comment]
> Switching to Python 3 has the potential to break deployments because buildbot's configuration files are written in Python. That was why I tried to make the Python version configurable.

These configuration files are typically quite small and trivial, I suppose?

**Comment by lopsided98** [comment]
Not necessarily, they can get pretty long and complicated.
These examples are some of the simplest: https://github.com/buildbot/buildbot/tree/master/master/docs/examples
This is the configuration I use: https://github.com/lopsided98/aur-buildbot/blob/master/master/master.cfg
This is one of the most complicated I've found, used by buildbot themselves: https://github.com/buildbot/metabbotcfg

**Comment by FRidh** [comment]
In that case we may need to provide version for 2 and 3. Do our maintainers want that? If so, we might want to pull it into `python-packages.nix`. Regardless, this is going to require a mention in the changelog.

**Comment by lopsided98** [comment]
I can move the package to `pythonPackages`. Does that mean we want to support both versions and make it configurable in the module?

**Comment by dotlambda** [comment]
Yes, we can make it configurable using the usual `package` option found in many modules.

Citing from https://github.com/NixOS/nixpkgs/issues/45782#issuecomment-417371669
> I think we should provide indeed provide pylint 1.9 as `python2Packages.pylint` until support ends. I also think we should move buildbot to `pythonPackages` as @FRidh suggested.
@lopsided98 Do you want to continue my work?

**Comment by lopsided98** [comment]
See #45890

**Comment by lopsided98** [comment]
#45890 was merged a while ago, so this can be closed

**Pull request closed without merging**
