### PR TITLE
lib: rename maintainers-list.nix into maintainers/maintainer-list.nix

### PR DESCRIPTION
**Pull request by oxij**
Much saner `git log ./lib`.

### CODE REVIEW

**Comment by oxij** [comment]
The ofborg error is pretty interesting. What is this? I don't even.

**Comment by Profpatsch** [comment]
Maybe it has something to do with the change to `checkMeta`? I’d put that into a separate commit anyway.

**Comment by oxij** [comment]
Nah, now it's bugs in derivations. Will fix one by one as obborg finds them.

**Comment by Profpatsch** [comment]
Ah, but then this should be two PRs, really.

**Comment by grahamc** [comment]
The error is on master, not on your branch. The original PR didn't pass checks, and ofborg doesn't handle it well when master is already broken.

**Comment by oxij** [comment]
All the things evaluate here. @grahamc or @Profpatsch can you pick up two top commits from here to master? I will then rebase to clean this up to match the topic.

**Comment by grahamc** [comment]
I pushed the last two, but I think you meant the last three?

**Comment by oxij** [comment]
Rebased onto #36279.

**Comment by grahamc** [comment]
cc https://github.com/NixOS/nixpkgs/pull/36279

**Comment by oxij** [comment]
@grahamc Well, yes (I need to go to sleep ASAP, I guess). Anyway, this branch looks good to me. Waiting for ofborg.

**Comment by oxij** [comment]
Yay! This now closes #36279, I guess.

**Comment by Profpatsch** [comment]
Okay, the broken evaluations have been fixed in #36279.

**Comment by oxij** [comment]
I wonder why it worked without f56dc5213adaa51c854b6889f77be40bc9ddf7a4.

**Comment by oxij** [comment]
Updated a bit. Why? Because `find . -iname '*-list*.nix'` now shows this:

```
./maintainers/maintainer-list.nix
./lib/tests/modules/define-value-list.nix
./nixos/modules/module-list.nix
```

**Comment by oxij** [comment]
ping

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg eval

**Pull request merged**
