### PR TITLE
age-plugin-tpm: init at unstable-2023-05-02

### PR DESCRIPTION
**Pull request by Kranzes**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 237801` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>age-plugin-tpm</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
@ofborg build age-plugin-tpm

**Comment by Kranzes** [comment]
@ofborg build age-plugin-tpm

**Comment by Foxboron** [comment]
@Kranzes I would prefer if you didn't package non-stable releases of software I write with a clear disclaimer of "experimental" in the `README.md`.

**Comment by Kranzes** [comment]
> @Kranzes I would prefer if you didn't package non-stable releases of software I write with a clear disclaimer of "experimental" in the `README.md`.

I didn't know if there will be a stable release any time soon. Also, people know it's unstable/experimental by the version name (`unstable-*`). And you kinda just expect people to go to the software's page and read about it and its state before using it, especially for security related software.

**Comment by Foxboron** [comment]
>I didn't know if there will be a stable release any time soon.

You can just ask. I'm *extremely* reachable over email, matrix, IRC and whatever platform. This is a bad reason for packaging experimental software.

>Also, people know it's unstable/experimental by the version name (unstable-*). 

Unstable/experimental implies the distro is unstable or experimental, not that the packaged software is.

>And you kinda just expect people to go to the software's page and read about it and its state before using it, especially for security related software.

I... think this is bogus. nixpkgs works as a software library and framework. People are using code to interface with the software. There is already code using age for credential encryption in NixOS and if people add `tpm = true;` to a config they would not be able to figure out the intent of `age-plugin-tpm`.

**Comment by Kranzes** [comment]
> You can just ask. I'm extremely reachable over email, matrix, IRC and whatever platform. This is a bad reason for packaging experimental software.

Will do next time. 

> Unstable/experimental implies the distro is unstable or experimental, not that the packaged software is.

I am talking about the package's version itself (`unstable-2023-05-02`), a version like that means that this software is in an experimental/unstable state and the source code for it is just the latest commit from its main branch.

> I... think this is bogus. nixpkgs works as a software library and framework. People are using code to interface with the software. There is already code using age for credential encryption in NixOS and if people add tpm = true; to a config they would not be able to figure out the intent of age-plugin-tpm.

I think this can be said about literally anything if users don't read or look up the thing they are about the run on their system.

**Comment by Foxboron** [comment]
> I am talking about the package's version itself (unstable-2023-05-02), a version like that means that this software is in an experimental/unstable state and the source code for it is just the latest commit from its main branch.

So you decided to package an untagged version of experimental software at the latest git master? :upside_down_face: 
I frankly thought it was the `v0.0.1` version but this is just even worse.

>I think this can be said about literally anything if users don't read or look up the thing they are about the run on their system.

Nobody is reading the description of all the software they end up using. Putting this as the users responsibility is not great.

**Comment by Kranzes** [comment]
We can agree to disagree and I will respect your work by no longer adding new experimental security related software without discussing it before with the author.

Moving on from this fuck up, I created this PR https://github.com/NixOS/nixpkgs/pull/244160 that adds a description, which also many people don't read, do you want me to also add a warning in red text that will pop-up when this package is being installed?

**Pull request merged**
