### PR TITLE
wayfireApplications,wayfirePlugins: recurseIntoAttrs

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112345` at e3497fbc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>wayfireApplications-unwrapped.wcm</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>wayfirePlugins.wayfire (wayfireApplications-unwrapped.wayfire)</li>
    <li>wayfirePlugins.wf-shell (wayfireApplications-unwrapped.wayfirePlugins.wf-shell)</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112345` at e3497fbc run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>wayfireApplications-unwrapped.wcm</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>wayfirePlugins.wayfire (wayfireApplications-unwrapped.wayfire)</li>
    <li>wayfirePlugins.wf-shell (wayfireApplications-unwrapped.wayfirePlugins.wf-shell)</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
```
hash mismatch in fixed-output derivation '/nix/store/lbyaykpqg15k20v18qvmmzyar7vdd3w6-source':                                                                                                wanted: sha256:1b22gymqfn0c49nf39676q5bj25rxab874iayiq31cmn14r30dyg
  got:    sha256:0xdjrmpdwag2d7bhqa2iall0rdsqpzfgix279lp2zy1ldw9gzg1n
cannot build derivation '/nix/store/0851b7lkx5lr9vp1x4xlg70rd1w0ka89-wcm-0.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2hza3f77vm7flg5m2p1vjrq0lpy64xq0-env.drv': 1 dependencies couldn't be built
```

**Comment by alyssais** [comment]
> hash mismatch in fixed-output derivation '/nix/store/lbyaykpqg15k20v18qvmmzyar7vdd3w6-source':                                                                                                wanted: sha256:1b22gymqfn0c49nf39676q5bj25rxab874iayiq31cmn14r30dyg
>   got:    sha256:0xdjrmpdwag2d7bhqa2iall0rdsqpzfgix279lp2zy1ldw9gzg1n
> cannot build derivation '/nix/store/0851b7lkx5lr9vp1x4xlg70rd1w0ka89-wcm-0.6.0.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/2hza3f77vm7flg5m2p1vjrq0lpy64xq0-env.drv': 1 dependencies couldn't be built

This will be fixed by #112345.

**Pull request merged**
