### PR TITLE
[release-24.05] Treewide Nix reformat pass 1 [skip treewide]

### PR DESCRIPTION
**Pull request by infinisil**
> [!Note]
> This depends on https://github.com/NixOS/nixpkgs/pull/364004

This is the 24.05 "backport" of https://github.com/NixOS/nixpkgs/pull/322537, see its description for more info. These PRs will be merged together to avoid backporting problems.

> [!Note]
> While 24.05 doesn't have the CI action enforcing formatting on new/already-formatted files, this is okay, because nobody's actively developing on 24.05, and the main reason we're doing this is to avoid backporting problems.

### Verification

The reformatting commit is fully auto-generated by the code in https://github.com/infinisil/treewide-nixpkgs-reformat-script, see the commit message on how to do a complete verification.

---

This work is funded by [Tweag](https://tweag.io) and [Antithesis](https://antithesis.com/) :sparkles:

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
I believe this merge blocked the `release-24.05-small` channel (and others).  See
https://hydra.nixos.org/build/282045490

**Comment by infinisil** [comment]
Yeah in hindsight that probably would've been a bit better, doesn't matter much though

**Comment by vcunat** [comment]
We'll know next time when we change the format :trollface:  (just kidding)

**Comment by vcunat** [comment]
So, any plans what to do about this blocker?  Should I simply revert this PR?

**Comment by infinisil** [comment]
@vcunat Ahh sorry I somehow overlooked your comment pointing that out, thanks for the reminder. I'll make a PR today to fix it, it's an easy fix

**Comment by infinisil** [comment]
@vcunat https://github.com/NixOS/nixpkgs/pull/364553

**Pull request merged**
