### PR TITLE
php82: 8.2.2 -> 8.2.3, php81: 8.1.15 -> 8.1.16, php80: 8.0.27 -> 8.0.28

### PR DESCRIPTION
**Pull request by drupol**
Since this is a security update, I'm providing the update instead of waiting for ryantm to pick it up.

- PHP82: Security update. News: https://www.php.net/archive/2023.php#2023-02-14-2
- PHP81: Security update: News: https://www.php.net/archive/2023.php#2023-02-14-3
- PHP80: Security update. News: https://www.php.net/archive/2023.php#2023-02-14-1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
@GrahamcOfBorg build php80 php81 php82

**Comment by etu** [comment]
@drupol Well, it doesn't seem to build at all

**Review by bachp — CHANGES_REQUESTED** [review]
I get the following error when trying to build:

```
error: hash mismatch in fixed-output derivation '/nix/store/zyl3gi5rvydz7rbd5499ll369qbgwndc-php-8.1.16.tar.bz2.drv':
         specified: sha256-lfLk8lApBqwjMheESAYBjoiBNfBxhkn0oKZ+QORQ/6E=
            got:    sha256-zZ8OoU2C2UVVh6SaC2yAKnuNj/eXA/n0ixfbAQ+2M84=
```

**Comment by drupol** [comment]
> I get the following error when trying to build:
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/zyl3gi5rvydz7rbd5499ll369qbgwndc-php-8.1.16.tar.bz2.drv':
>          specified: sha256-lfLk8lApBqwjMheESAYBjoiBNfBxhkn0oKZ+QORQ/6E=
>             got:    sha256-zZ8OoU2C2UVVh6SaC2yAKnuNj/eXA/n0ixfbAQ+2M84=
> ```

Yes, this was expected, see: https://news-web.php.net/php.announce/349

I just pushed the proper hash.

That said, I need now to find why we are unable to build them.

**Comment by drupol** [comment]
I did a rebase and it seems that now the builds are working. I guess it's related to the recent `openssl`  update.

**Pull request merged**
