### PR TITLE
skypeforlinux: 8.11.0.4 -> 8.11.76.8

### PR DESCRIPTION
**Pull request by rycee**
###### Motivation for this change

Bump Skype to the latest version. This may have to be backported to 17.09 because the 5.5.0.1 version appears to be disabled 🙁

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rycee** [comment]
Maintainer CC: @panaeon @jraygauthier

**Comment by jraygauthier** [comment]
@rycee The change seems fine to me. Any reason for the bump feature-wise?

**Comment by rycee** [comment]
The 8.11.0.4 to 8.11.76.8 bump was mainly because I happened to notice that the new version was available. I don't know if this bump actually adds any major benefit. I did try running the new version, though, and everything seems to work OK.

The 5.5.0.1 in stable needs to be bumped to a later version because the Skype people changed the 5.5.0.1 deb archive in-place to a version that just prints something along the lines of "you are running an old version of skype, please upgrade" ☹️

**Comment by orivej** [comment]
The `x.y.0.z` versions proved to be much more stable than `x.y.76.z` (even counting the recent rebuild, fixed in #32667), so the reasoning from https://github.com/NixOS/nixpkgs/pull/31129#discussion_r148616508 still stands and Skype should not be updated to 8.11.76.8.

**Comment by orivej** [comment]
@Mic92 Sorry, I misremembered your comment.

`x.y.0.z` are more stable in the sense that they persist upstream for longer, and they are published in the `stable` dist:
https://repo.skype.com/deb/dists/stable/main/binary-amd64/Packages
https://repo.skype.com/deb/dists/unstable/main/binary-amd64/Packages

**Comment by Mic92** [comment]
I guess we should not merge this one then.

**Comment by rycee** [comment]
Fair enough. Thanks for the clarification. I will close this ticket and merge #32684.

**Pull request closed without merging**
