### PR TITLE
Kernels 2021-07-20

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
Built linux_latest
- [x] Tested execution of all binary files (usually in `./result/bin/`)
Tested linux_latest
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ymatsiuk — APPROVED** [review]

**Comment by TredwellGit** [comment]
Also merge https://github.com/NixOS/nixpkgs/pull/130292 so that https://github.com/NixOS/nixpkgs/pull/130635 and this can be backported.

**Review by Atemu — APPROVED** [review]

**Comment by maxeaubrey** [comment]
Minus the hardened patches, this duplicates #130807.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/130879

**Comment by Ma27** [comment]
I merged the previous backport PR. Can we somehow re-trigger the bot?

**Pull request merged**
