### PR TITLE
zeroad: 0.0.25 -> 0.0.25b

### PR DESCRIPTION
**Pull request by chvp**
###### Motivation for this change

Version bump.

###### Things done

Started a game, everything ran fine.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136105` at 740b698e run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/54ff8095e66638bd8547e31b51e042f6">zeroadPackages.zeroad-unwrapped</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by mweinelt** [comment]
Can we build this without `nvidia-texture-tools` on aarch64? It is marked as broken and the upstream has already archived the project. 

https://github.com/castano/nvidia-texture-tools

**Comment by Mindavi** [comment]
I can confirm that this builds for me and that at least the title screen works for me. Will play a game in a bit to see if everything is ok, but I don't expect much issues since 0.0.25 seemed to work fine (enough, had 2 multiplayer crashes, but probably not related to packaging).

As for nvidia-texture-tools, that should probably be reported upstream so they can get rid of it or replace it with something else.

**Comment by zeri42** [comment]
Tested 740b698 on x86_64 (git fetch/checkout nix-env -iA zeroad -f path/to/nixpkgs/repo) builds without hickups and runs nicely spectated a game in the lobby and played a short match against AI.

**Review by zeri42 — APPROVED** [review]
Tested 740b698 on x86_64 (git fetch/checkout nix-env -iA zeroad -f path/to/nixpkgs/repo) builds without hickups and runs nicely spectated a game in the lobby and played a short match against AI.

looks good to me, ship it : )

**Pull request merged**
