### PR TITLE
Improve mingw support sdl2

### PR DESCRIPTION
**Pull request by seanybaggins**
## Description of changes
Improve mingw support sdl2
Part of a larger effort to get mingw support for qtmultimedia
Relevant for https://github.com/NixOS/nixpkgs/issues/274274
SDL2 will cross compile to mingw but will fail to be found when added as a dependency for ffmpeg. This PR makes it such that SDL2 can be found by ffmpeg.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by seanybaggins** [comment]
@ofborg build pkgs.pkgsCross.mingw32.SDL2

**Comment by seanybaggins** [comment]
@ofborg build pkgs.pkgsCross.mingwW64.SDL2

**Comment by seanybaggins** [comment]
@wegank @Artturin @bjornfor

**Comment by bjornfor** [comment]
Is there a dependee PR that makes the commit message part `ffmpeg will fail to compile without this change` actually true? (Because `nix-build -A pkgsCross.mingw32.ffmpeg` throws eval errors before and after this PR.)

**Comment by bjornfor** [comment]
Also, please write commit message bodies as full sentences (capitalize first word and end with dot).

**Comment by seanybaggins** [comment]
> Is there a dependee PR that makes the commit message part `ffmpeg will fail to compile without this change` actually true? (Because `nix-build -A pkgsCross.mingw32.ffmpeg` throws eval errors before and after this PR.)

Yes. This is one of many dependee's of ffmpeg that causes the ffmpeg mingw32 build to fail.

**Comment by seanybaggins** [comment]
> Also, please write commit message bodies as full sentences (capitalize first word and end with dot).

Fixed

**Review by bjornfor — APPROVED** [review]

**Pull request merged**
