### PR TITLE
cawbird: 1.1.0 -> 1.2.1

### PR DESCRIPTION
**Pull request by schmittlauch**
###### Motivation for this change

- regular version bump
- changes: see https://github.com/IBBoard/cawbird/releases/tag/v1.2.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x]] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by schmittlauch** [comment]
@GrahamcOfBorg build cawbird

**Comment by schmittlauch** [comment]
If this isn't merged before the 20.09 branch-off, it also needs a backport to release-20.09.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 97230` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- cawbird
</details>

**Comment by tomberek** [comment]
builds and runs on NixOS. did not test functionality. Version bump and additional dependency.

**Comment by schmittlauch** [comment]
rebased on latest master and bumped to bugfix release 1.2.1 instead of 1.2.0

**Comment by schmittlauch** [comment]
@GrahamcOfBorg build cawbird

**Comment by schmittlauch** [comment]
backport: 98326

**Pull request merged**
