### PR TITLE
nixos/soju: migrate to a static user

### LINKED ISSUE #353554: soju NixOS module should support ACME
### Describe the bug

The soju module doesn't support loading an ACME certificate...

### Steps To Reproduce
1. Set

```nix
{ config, lib, ... }:

let
  hostName = "...";
  certDir = config.security.acme.certs.${hostName}.directory;
in
{
  services.soju = {
    tlsCertificate = "${certDir}/fullchain.pem";
    tlsCertificateKey = "${certDir}/key.pem";
    # ...
  };
}

```
2. Activate the connection
3. Soju fails to start, because it does not have permissions to access the TLS cert/key (whose ownership is `acme:nginx`).

### Expected behavior
There should be some endorsed mechanism to get an ACME certificate for the Soju server, ideally without interfering with nginx serving on the same hostname.

### Additional context
As a workaround, I set:

```nix
{ lib, ... }:

let
  hostName = "...";
in
{
  services.nginx.group = "acme";

  systemd.services.soju = {
    requires = [ "acme-finished-${hostName}.target" ];
    after = [ "acme-finished-${hostName}.target" ];
    serviceConfig = {
      DynamicUser = lib.mkForce false;
      User = "soju";
      Group = "soju";
    };
  };

  users = {
    users.soju = {
      isSystemUser = true;
      group = "soju";
      extraGroups = [ "acme" ];
    };
    groups.soju = { };
  };
}
```

I'm not thrilled with this, though...

### Notify maintainers

@malte-v

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.87, NixOS, 24.05 (Uakari), 24.05.20241009.d51c286`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `""`
 - nixpkgs: `/nix/store/19l2iplgd8kw8b1il0sl8wv9cv725w4f-source`

### PR DESCRIPTION
**Pull request by malte-v**
This makes it easy to give soju access to TLS certificates by adding the "soju" user to the "acme" group. Closes #353554

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xanderio** [comment]
Can't we make use of `SupplementaryGroups`?

**Comment by malte-v** [comment]
Good point, though likely not everyone who wants to use the module knows about this systemd feature, whereas the `extraGroups = [ "acme" ]` thing is kind of standard. tbh I also dislike the DynamicUser feature because I've found it very hard to restore a backup of the StateDirectory for a service with dynamically allocated uid in a way that makes systemd happy, but this is besides the point.

**Comment by emilazy** [comment]
There’s an accepted RFC [specifically advising the use of `DynamicUser` whenever possible](https://github.com/NixOS/rfcs/blob/25c3f524631000b851375e7b96223a56e71cc0e2/rfcs/0052-dynamic-ids.md), and having to add supplementary groups is a standard part of using the ACME module. `DynamicUser` avoids additional unnecessary state management and also dovetails well with the various systemd service hardening options. If you want a static user it’s easy to override the systemd service in your own configuration, but I don’t think that we should regress things for the sake of users not having to learn about systemd features when we gain so many advantages from our deep systemd integration; if anything we should perhaps provide an easier interface to integrate ACME directly with arbitrary services. I also worry this would likely be backwards‐incompatible with existing users of the module in its current state as I don’t know if the owner would be automatically migrated?

**Comment by winterqt** [comment]
> I don’t know if the owner would be automatically migrated?

systemd does some magic here in the case of `DynamicUser = true` that I forget the details of, specifically wrt setting perms, and I'm not sure if this carries over to when it's disabled (I doubt it).

**Comment by malte-v** [comment]
> There’s an accepted RFC [specifically advising the use of DynamicUser whenever possible](https://github.com/NixOS/rfcs/blob/25c3f524631000b851375e7b96223a56e71cc0e2/rfcs/0052-dynamic-ids.md), and having to add supplementary groups is a standard part of using the ACME module. DynamicUser avoids additional unnecessary state management and also dovetails well with the various systemd service hardening options. If you want a static user it’s easy to override the systemd service in your own configuration, but I don’t think that we should regress things for the sake of users not having to learn about systemd features when we gain so many advantages from our deep systemd integration; if anything we should perhaps provide an easier interface to integrate ACME directly with arbitrary services.

Fair enough.

**Pull request closed without merging**
