### PR TITLE
Updates and fixes for Quake 3

### PR DESCRIPTION
**Pull request by abbradar**
This does several enhancements for our Quake packages:
1. Adds `ioquake3-git`, which doesn't suffer from compilation problems with new `gcc`, is ported to SDL2 and has other niceties.
2. Splits our data files into two parts -- Quake point release (common for all Quake games) and demo files.
3. Adds `quake3wrapper` for easy wrapping of Quake `pak`s.
4. Fixes it for the case of multiple `pak`s.

It also switches to the new mirrors for data files, adds `platforms` where applicable to build things on Hydra and has other minor enhancements.

I've also renamed `quake3game` to `ioquake3` for consistency (what if we add other engines in future?) and reworked directory structure.

This allows one to, for example, play full `Quake 3 Arena` with new `ioquake3-git` using:

```
{ nixpkgs ? import <nixpkgs> { } }:

let
  paks = nixpkgs.stdenv.mkDerivation {
    name = "quake3-arena";
    pak0 = ./baseq3/pak0.pk3;
    buildCommand = ''
      install -D -m644 $pak0 $out/baseq3/pak0.pk3
    '';
  };
in nixpkgs.quake3wrapper {
  game = nixpkgs.ioquake3-git;
  paks = [ paks nixpkgs.quake3pointrelease ];
}
```

cc @edolstra (maintainer of `ioquake`)

### CODE REVIEW

**Comment by edolstra** [comment]
Do we need to keep the old ioquake?

**Comment by abbradar** [comment]
I personally don't need it, but maybe for instance it is required to have a particular (stable) version to able to connect to public servers. I haven't tried to play different versions in multiplayer simultaneously, so I have no idea.

**Comment by abbradar** [comment]
According to [this wiki article](http://wiki.ioquake3.org/Sys_Admin_Guide#Is_ioquake3_network_compatible_with_the_final_id_point_release_.281.32c.29_of_Quake_III:_Arena.3F), all releases of `ioquake3` should be fully compatible with the latest official Quake 3 Arena code. I say let's drop the old ioquake then!

**Comment by abbradar** [comment]
I'm going to merge this in several days if we don't catch any other issues.

**Comment by nckx** [comment]
:beers:

**Comment by vcunat** [comment]
I expect this PR is what made it start failing on i686-linux: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.quake3game.i686-linux

**Pull request merged**
