### PR TITLE
python3Packages.pylxd: init at 2.3.0

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by petabyteboy** [comment]
@pstch tested this before

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 111728` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.pylxd</li>
    <li>python38Packages.pylxd</li>
    <li>python39Packages.pylxd</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111728` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.pylxd</li>
<li>python38Packages.pylxd</li>
<li>python39Packages.pylxd</li>
</ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [x] package build (see https://github.com/NixOS/nixpkgs/pull/111728#issuecomment-772648789)
- [ ] all depending packages build
- [x] library tested on x86_64

```bash
...ew/pr-111728/results/python38Packages.pylxd/lib/python3.8/site-packages]$ python
Python 3.7.9 (default, Aug 15 2020, 06:36:35) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylxd
>>> client = pylxd.Client()
>>> client = pylxd.Client(endpoint='http://192.168.1.192:8443')
[..]
pylxd.exceptions.ClientConnectionFailed: HTTPConnectionPool(host='192.168.1.192', port=8443): Max retries exceeded with url: /1.0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff49f35fe90>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[...]
```

Looks good to me.

**Pull request merged**
