### PR TITLE
haskellPackages.cabal-plan-bounds: Unbreak, add myself as maintainer

### PR DESCRIPTION
**Pull request by nomeata**
###### Description of changes

The package could easily be unbroken by passing a new version of Cabal-syntax.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
#240387 updates the default GHC to 9.4 which uses 3.8 by default. Can you rebase your PR on `haskell-updates` and try unbreaking it there (seems like there is a new bounds problem).

**Comment by nomeata** [comment]
> seems like there is a new bounds problem

Indeed, not with cabal-plan-bounds, but its dependency `cabal-plan`. It has an upper bound on `base-compat`.

I tried to see if jailbreaking helps, but oddly, this doesn’t work:
```
--- a/pkgs/development/haskell-modules/configuration-common.nix
+++ b/pkgs/development/haskell-modules/configuration-common.nix
@@ -2168,10 +2168,8 @@ self: super: {
     Cabal-syntax = self.Cabal-syntax_3_10_1_0;
   }));

+  # 2023-07-10: cabal-plan needs newer base-compat
+  cabal-plan = doJailbreak super.cabal-plan;

   large-hashable = lib.pipe (super.large-hashable.override {
     # https://github.com/factisresearch/large-hashable/commit/5ec9d2c7233fc4445303564047c992b693e1155c
```
I still get
```
       > Error: Setup: Encountered missing or private dependencies:
       > base-compat >=0.13.0 && <0.14
       >
       For full logs, run 'nix log /nix/store/gz3rkv8p8j159s0sx78113y59pam6w6n-cabal-plan-0.7.3.0.drv'.
```
I wonder what I am doing wrong.
```

**Comment by nomeata** [comment]
Maybe that’s it, although I find it strange that the log doesn’t state anything about jailbreaking:
```
~/build/nixpkgs $ nix-build -A haskellPackages.cabal-plan .
this derivation will be built:
  /nix/store/gz3rkv8p8j159s0sx78113y59pam6w6n-cabal-plan-0.7.3.0.drv
building '/nix/store/gz3rkv8p8j159s0sx78113y59pam6w6n-cabal-plan-0.7.3.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/3a62qjab6drfg81317srgf23hlqzmny6-ghc-9.4.5.
unpacking sources
unpacking source archive /nix/store/bf5bixs3fiyviwpskrm3sf5zrkdjjs6q-cabal-plan-0.7.3.0.tar.gz
source root is cabal-plan-0.7.3.0
setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file cabal-plan-0.7.3.0/src-exe/ProcessLazyByteString.hs
patching sources
Replace Cabal file with edited version from mirror://hackage/cabal-plan-0.7.3.0/revision/1.cabal.
Run jailbreak-cabal to lift version restrictions on build inputs.
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/tmp.0Xxl8Fzogx/setup-package.conf.d -j8 +RTS -A64M -RTS -threaded -rtsopts
[1 of 2] Compiling Main             ( Setup.hs, /build/tmp.0Xxl8Fzogx/Main.o )
[2 of 2] Linking Setup
updateAutotoolsGnuConfigScriptsPhase
configuring
configureFlags: --verbose --prefix=/nix/store/inn19ng84cbrpfrw06db1h1nvbd32y3m-cabal-plan-0.7.3.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/fvhrw3zln8k0vnrdyhrma6n85wd4k7jd-cabal-plan-0.7.3.0-doc/share/doc/cabal-plan-0.7.3.0 --with-gcc=gcc --package-db=/build/tmp.0Xxl8Fzogx/package.conf.d --ghc-options=-j8 +RTS -A64M -RTS --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --ghc-options=-haddock -fexe --extra-lib-dirs=/nix/store/00914xy1p14vd8qy23lrjd165rnxy3h2-ncurses-6.4/lib --extra-lib-dirs=/nix/store/g8l012l0q2xbl27da8zipg39mnpf40gb-libffi-3.4.4/lib --extra-lib-dirs=/nix/store/c6v3ix7r8gy6fgq1jssswkdk4xnk8fwk-gmp-with-cxx-6.2.1/lib
Using Parsec parser
Configuring cabal-plan-0.7.3.0...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
base-compat >=0.13.0 && <0.14
```
despite it being enabled in `postPatch`:
```
~/build/nixpkgs $ nix show-derivation /nix/store/gz3rkv8p8j159s0sx78113y59pam6w6n-cabal-plan-0.7.3.0.drv|grep -i postPatch
      "postPatch": "echo \"Run jailbreak-cabal to lift version restrictions on build inputs.\"\n/nix/store/6vm5k6dbl14ya3i6jsf23gpqs5swlznj-jailbreak-cabal-1.4/bin/jailbreak-cabal cabal-plan.cabal\n",
```
```

**Comment by nomeata** [comment]
Yes, that’s it. Annoying.

**Comment by nomeata** [comment]
Looks like there is a new revision of `cabal-plan` on hackage that should fix this.

**Comment by sternenseemann** [comment]
You can pick new revision early like this or, of course, wait for the next hackage bump.

```nix
overrideCabal (drv: {
  revision = assert drv.revision == "1"; "2";
  editedCabalFile = "sha256-…";
})
```

**Comment by nomeata** [comment]
> wait for the next hackage bump.

That was my plan :-D

**Comment by nomeata** [comment]
Just had a look, the latest revision is in, but `cabal-plan` depends on `base-compat-0.13.0`. This works great on GHC-9.6, but on GHC-9.4, `base-compat` is still 0.12, and overriding it gives
```
Warning:
    This package indirectly depends on multiple versions of the same package. This is very likely to cause a compile failure.
      package topograph (topograph-1.0.0.2-3tHBQRic9TSABtFXcNsl6C) requires base-compat-0.12.3-EzIEO7DrtWn73MXq9N0DKk
      package base-compat-batteries (base-compat-batteries-0.12.3-8cIdD6XdBQgJ5TQIiFvwZ0) requires base-compat-0.12.3-EzIEO7DrtWn73MXq9N0DKk
      package cabal-plan (cabal-plan-0.7.3.0) requires base-compat-0.13.0-Cvz3167VMpo6rdOohSlum3
```

Not sure what to do about it.

**Comment by flokli** [comment]
In that specific instance, it's `cabal-plan` as a CLI tool, not the library.

**Comment by sternenseemann** [comment]
I think it is probably easiest and most worthwhile making cabal-plan compatible with Stackage LTS 21 upstream which would help everyone out.

**Comment by nomeata** [comment]
Using cabal-plan 0.7.2.3 instead of 0.7.3.0 might be lts-compatible

**Comment by nomeata** [comment]
New attempt at https://github.com/NixOS/nixpkgs/pull/261261

**Pull request closed without merging**
