### PR TITLE
caligula: mark darwin as no longer broken

### PR DESCRIPTION
**Pull request by ifd3f**
## Description of changes

The issue was fixed in 0.4.7. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Tested to work on MacOS:
```
nix run nixpkgs#caligula --impure -- burn test.img
```

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
DontEatOreo could you test this?

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 321426` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by DontEatOreo** [comment]
Error Log (`nix-build -A caligula`):

```console
The following warnings were emitted during compilation:

warning: caligula@0.4.7: native/darwin/REDiskList.m:30:13: warning: 'NSArray' may not respond to 'sortUsingSelector:'
warning: caligula@0.4.7:     [_disks sortUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
warning: caligula@0.4.7:      ~~~~~~ ^
warning: caligula@0.4.7: 1 warning generated.

error: failed to run custom build command for `caligula v0.4.7 (/private/tmp/nix-build-caligula-0.4.7.drv-0/source)`

Caused by:
  process didn't exit successfully: `/private/tmp/nix-build-caligula-0.4.7.drv-0/source/target/release/build/caligula-9e3751de27258196/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=native/darwin/enumdisk.h
  cargo:rerun-if-changed=native/darwin/enumdisk.m
  cargo:rustc-link-search=native/darwin
  cargo:rustc-link-lib=caliguladarwin
  cargo:rustc-link-lib=framework=Cocoa
  cargo:rustc-link-lib=framework=IOKit
  cargo:rustc-link-lib=framework=Foundation
  cargo:rustc-link-lib=framework=DiskArbitration
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("2")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = Some("/nix/store/c1ib07kj7baid3s3wf5m98hcpbvgs8mk-clang-wrapper-16.0.6/bin/cc")
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=native/darwin/REDiskList.m:30:13: warning: 'NSArray' may not respond to 'sortUsingSelector:'
  cargo:warning=    [_disks sortUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
  cargo:warning=     ~~~~~~ ^
  cargo:warning=1 warning generated.
  cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
  AR_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
  AR_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = Some("ar")
  cargo:rerun-if-env-changed=ARFLAGS_aarch64-apple-darwin
  ARFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64_apple_darwin
  ARFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rustc-link-lib=static=caliguladarwin
  cargo:rustc-link-search=native=/private/tmp/nix-build-caligula-0.4.7.drv-0/source/target/aarch64-apple-darwin/release/build/caligula-57495cc3b485df2d/out

  --- stderr
  thread 'main' panicked at /private/tmp/nix-build-caligula-0.4.7.drv-0/caligula-0.4.7-vendor.tar.gz/bindgen/./lib.rs:2393:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.dylib'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by DontEatOreo** [comment]
I tested the `nix run nixpkgs#caligula --impure -- burn test.img` with `2024-03-15-raspios-bookworm-arm64.img` but same error as comment above...

**Comment by DontEatOreo** [comment]
```diff
diff --git a/pkgs/by-name/ca/caligula/package.nix b/pkgs/by-name/ca/caligula/package.nix
index 8deb9c61a113..46bd86607063 100644
--- a/pkgs/by-name/ca/caligula/package.nix
+++ b/pkgs/by-name/ca/caligula/package.nix
@@ -1,6 +1,7 @@
 { lib
 , rustPlatform
 , fetchFromGitHub
+, llvmPackages
 , stdenv
 , darwin
 }:
@@ -18,6 +19,10 @@ rustPlatform.buildRustPackage rec {
 
   cargoHash = "sha256-ma7JVbWSiKfkCXCDwA8DFm2+KPrWR+8nSdgGSqehNg8=";
 
+  env = {
+    LIBCLANG_PATH = "${llvmPackages.libclang.lib}/lib";
+  };
+
   buildInputs = lib.optionals stdenv.isDarwin (
     with darwin.apple_sdk.frameworks; [
       Cocoa
```

It seems like this diff resolves the issue

```
Input file: 2024-03-15-raspios-bookworm-arm64.img
Detected compression format: no compression
> Is this okay? Yes
> What is the file's hash? skip
? Select target disk
  <Refresh devices>
> <Show all disks, removable or not>
[Only displaying removable disks.]
Operation was interrupted by the user
```

I don't have any removable devices at the moment to test this, but I would imagine everything is working if I can get this far.

**Review by sodiboo — COMMENTED** [review]
Given that i don't own a `*-darwin` and that's the focus of this PR, i won't leave explicit approval as i can't test it on `*-darwin`. But the package built fine and i tested it just now on a removable device and it burnt `nixos-minimal-24.05.1695.dd457de7e08c-x86_64-linux.iso` just fine.

**Comment by JohnRTitor** [comment]
@ifd3f it builds, have you tested it? I'll merge once you do

**Review by marcusramberg — APPROVED** [review]
Tested this on aarch64-darwin now, works to burn an image.
image

**Pull request merged**
