### PR TITLE
libretro: improve update_cores.py script

### PR DESCRIPTION
**Pull request by thiagokokada**
## Description of changes

- Add support for multiple fetchers (for now `fetchFromGitHub` is still the only supported one)
- Use `--meta` from `nix-prefetch-github` to extract the date
- Show errors in `nix-prefetch-github` if they occur

This PR will stay in draft until https://github.com/seppeljordan/nix-prefetch-github/pull/64 is released and `nix-prefetch-github` derivation is updated, so we can avoid needing to call GitHub twice for each core CC @seppeljordan.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thiagokokada** [comment]
@seppeljordan would it be sufficient to pin an unstable version of `nix-prefetch-github` in this PR and modify my code so I use this feature and give some feedback in case of any issue I have?

**Comment by thiagokokada** [comment]
CC @seppeljordan, it is working fine now. Can you review the bump PR for the `nix-prefetch-github`?

CC @aanderse to review the changes in the update script.

**Review by aanderse — APPROVED** [review]
took a quick look at the diff and looks fine to me 👍 

as always thanks @thiagokokada

**Comment by thiagokokada** [comment]
> @thiagokokada What bump PR? Can you link it here?

Sorry, it was supposed to say bump commit (it is in this PR): https://github.com/NixOS/nixpkgs/pull/287812/commits/30344b2c7545d952855ab85aefc1a84f2b765fa1

**Pull request merged**
