### PR TITLE
python3Packages.pytest-httpx: 0.15.0 -> 0.17.3

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
https://github.com/Colin-b/pytest_httpx/releases

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 153406` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages failed to build:</summary>
  <ul>
    <li>lexicon</li>
    <li>odoo</li>
    <li>python38Packages.aiocurrencylayer</li>
    <li>python38Packages.cirq</li>
    <li>python38Packages.cirq-rigetti</li>
    <li>python38Packages.denonavr</li>
    <li>python38Packages.devolo-plc-api</li>
    <li>python38Packages.glances-api</li>
    <li>python38Packages.luftdaten</li>
    <li>python38Packages.netdata</li>
    <li>python38Packages.pyrmvtransport</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.total-connect-client</li>
    <li>python38Packages.zeep</li>
    <li>python39Packages.aiocurrencylayer</li>
    <li>python39Packages.cirq</li>
    <li>python39Packages.cirq-rigetti</li>
    <li>python39Packages.denonavr</li>
    <li>python39Packages.devolo-plc-api</li>
    <li>python39Packages.glances-api</li>
    <li>python39Packages.luftdaten</li>
    <li>python39Packages.netdata</li>
    <li>python39Packages.pyrmvtransport</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.total-connect-client</li>
    <li>python39Packages.zeep</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python38Packages.elmax</li>
    <li>python38Packages.pyquil</li>
    <li>python38Packages.pytest-httpx</li>
    <li>python39Packages.elmax</li>
    <li>python39Packages.pyquil</li>
    <li>python39Packages.pytest-httpx</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 153406` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.cirq</li>
    <li>python38Packages.cirq-rigetti</li>
    <li>python38Packages.denonavr</li>
    <li>python38Packages.devolo-plc-api</li>
    <li>python38Packages.pyrmvtransport</li>
    <li>python39Packages.cirq</li>
    <li>python39Packages.cirq-rigetti</li>
    <li>python39Packages.denonavr</li>
    <li>python39Packages.devolo-plc-api</li>
    <li>python39Packages.pyrmvtransport</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>lexicon</li>
    <li>odoo</li>
    <li>python38Packages.aiocurrencylayer</li>
    <li>python38Packages.elmax</li>
    <li>python38Packages.glances-api</li>
    <li>python38Packages.luftdaten</li>
    <li>python38Packages.netdata</li>
    <li>python38Packages.pyquil</li>
    <li>python38Packages.pytest-httpx</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.total-connect-client</li>
    <li>python38Packages.zeep</li>
    <li>python39Packages.aiocurrencylayer</li>
    <li>python39Packages.elmax</li>
    <li>python39Packages.glances-api</li>
    <li>python39Packages.luftdaten</li>
    <li>python39Packages.netdata</li>
    <li>python39Packages.pyquil</li>
    <li>python39Packages.pytest-httpx</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.total-connect-client</li>
    <li>python39Packages.zeep</li>
  </ul>
</details>

**Comment by fabaff** [comment]
- `cirq-rigetti` fix: #153500

**Comment by fabaff** [comment]
- python3Packages.pyrmvtransport: https://github.com/cgtobi/PyRMVtransport/issues/56
- python3Packages.denonavr: https://github.com/ol-iver/denonavr/issues/228 
- python39Packages.devolo-plc-api: https://github.com/2Fake/devolo_plc_api/issues/72

**Comment by mweinelt** [comment]
As home-assistant currently uses package overrides to have compatible httpx, httpcore and pytest-httpx packages, this change updates home-assistant dependencies (yet again) towards unsupported versions and applies patches that don't work in that environment. That would be fine if home-assistant weren't the only reverse dependency of most of these packages, but it is.

This clearly reveals that you in fact *did not* test home-assistant before going for a self-merge only *one minute* after marking this PR as ready for review.

Please take a step back from quick self-merges and give others some time to review your changes. https://discourse.nixos.org/t/merge-fast-and-break-things/16957

**Pull request merged**
