### PR TITLE
gn: generate last_commit_position.h without git

### PR DESCRIPTION
**Pull request by YorikSar**
###### Motivation for this change

For Git to work properly, I used fetchgit with leaveDotGit. This seems
to be causing hash to change on different systems in different times.
I've replaced generation of last_commit_position.h in tools/gen.py with
just plain nix template. "gn --version" will loose a bit (just commit
hash, without commit height in front of it), but I hope noone relies on
it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Related PRs: #46328 #46718
CC @volth @eadwu @7c6f434c @Mic92

### CODE REVIEW

**Comment by volth** [comment]
it might be better to fix non-determinism in ```leaveDotGit``` 

This .nix file will be shorter and also there could be other files using ```leaveDotGit```

As far as I remember ```.git``` is not just left as it is after ```git clone```, there is clean-up step which should bring ```.git``` to canonical form; that seems broken after some ```git``` version bump

**Comment by YorikSar** [comment]
We definitely should fix this in fetchgit too, but I still find it cleaner not having to drag whole repo as build source here.

**Comment by 7c6f434c** [comment]
I agree that fixing `leaveDotGit` is useful, but I also agree that avoiding it can be useful even if it works.

**Comment by volth** [comment]
> I don't see how ```leaveDotGit``` could be made deterministic, when we update git. Every version could change the internal format.

Currently we have non-determinism even within the same git version.
Both https://github.com/NixOS/nixpkgs/pull/46328 and https://github.com/NixOS/nixpkgs/pull/46718 succeeded on Hydra with different hashes.

But in long run across different versions of git it is a problem.
We might, for example, fix git version when ```leaveDotGit=true``` assuming that the newer git is able to read format of the older.

**Pull request merged**
