### PR TITLE
ytcc: 2.0.1 -> 2.1.0

### PR DESCRIPTION
**Pull request by joachimschmidt557**
###### Motivation for this change

The `ytcc` package in unstable is outdated and has the wrong hash (https://github.com/NixOS/nixpkgs/pull/109088 forgot to update the hash)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by sbruder — APPROVED** [review]
It works. Thanks for updating it!

**Comment by JoshuaFern** [comment]
This is a breaking update, new versions of ytcc require a database migration process that you can read more about here: https://github.com/woefe/ytcc/blob/master/doc/migrate.md

**Comment by joachimschmidt557** [comment]
@JoshuaFern This PR only updated from 2.0.1 to 2.1.0. I think the procedure described in the documentation you linked only applies when upgrading from pre-2.0.0 to 2.0.0 or higher.

**Comment by JoshuaFern** [comment]
@joachifm I think you're right, but my NixOS unstable only recently updated to v2+

**Pull request merged**
