### PR TITLE
python3Packages.certbot-dns-ovh: init at 2.6.0 (follows python3Packages.certbot)

### PR DESCRIPTION
**Pull request by aviallon**
## Description of changes

~~Blocked by: https://github.com/NixOS/nixpkgs/pull/255084 (needs to be merged first).~~
After `dns-lexicon` is merged, we can finally add `certbot-dns-ovh` wirth some trivial additions.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aviallon** [comment]
Result of `nixpkgs-review pr 255362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>certbot-full</li>
    <li>python310Packages.certbot-dns-ovh</li>
    <li>python310Packages.certbot-dns-ovh.dist</li>
    <li>python310Packages.dns-lexicon</li>
    <li>python310Packages.dns-lexicon.dist</li>
    <li>python311Packages.certbot-dns-ovh</li>
    <li>python311Packages.certbot-dns-ovh.dist</li>
    <li>python311Packages.dns-lexicon</li>
    <li>python311Packages.dns-lexicon.dist</li>
  </ul>
</details>

**Comment by aviallon** [comment]
@domenkozar  It should be good now (barring any formatting / code quality issues).

**Comment by aviallon** [comment]
Result of `nixpkgs-review pr 255362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>certbot-full</li>
    <li>python310Packages.certbot-dns-ovh</li>
    <li>python310Packages.certbot-dns-ovh.dist</li>
    <li>python311Packages.certbot-dns-ovh</li>
    <li>python311Packages.certbot-dns-ovh.dist</li>
  </ul>
</details>

**Comment by aviallon** [comment]
@NixOS/acme would it be possible to merge this before 23.11 branching?

**Review by aanderse — APPROVED** [review]
took a brief look over... i think everything is in order here

and for future reference a change like this can probably be backported without a problem because it's a new leaf package

**Pull request merged**
