### PR TITLE
net-snmp: split outputs

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Mic92** [comment]
I tested all packages directly depending on net-snmp.

**Review by c0bw3b — COMMENTED** [review]
`keepalived` bump to v2.x requires a revamp of the associated service module too. See previous discussion in #72278 for example.

**Comment by c0bw3b** [comment]
cc @thoughtpolice for `h2o`, maybe the choice of building against libressl was deliberate?

**Comment by Mic92** [comment]
dnsdist is the only package in nixpkgs that uses it and it already caused problems to mix ssl libraries.

**Comment by Mic92** [comment]
Keepalived works fine. Added a NixOS test.

**Comment by thoughtpolice** [comment]
> cc @thoughtpolice for `h2o`, maybe the choice of building against libressl was deliberate?

No, this was probably an error on my part, and it should be fine to change it.

**Pull request merged**
