### PR TITLE
hare: refactor `harePackages` into `hareThirdParty`

### PR DESCRIPTION
**Pull request by onemoresuza**
## Description of changes

The name `harePackages` may give thet impression that programs written in
Hare should be added to its scope, which is not true: its purpose is to
encapsulate Hare third party libraries.

Thus, changing it to `hareThirdParty` makes it clear what its purpose
is --- just like renaming `hare-packages.nix` to `hare-third-party.nix`
on `pkgs/top-level`.

Moreover, remove the `hare` and `harec` packages from the newly renamed
`hareThirdParty` scope, since they are not Hare libraries.

Finally, remove the inheritance of `harePackages.hare` on `himitsu` and
`himitsu-firefox`, the two programs using `hare` on nixpkgs: both `hare`
and `harec` are directly accessible since [12449072][1], when they were
moved from `aliases.nix` to `all-packages.nix`, with the difference now
that they do not belong anymore to `harePackages` --- now `hareThirdParty`.

[1]: https://github.com/NixOS/nixpkgs/commit/1244907222bc7dc5cf4396544796afa6c14c2e52

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onemoresuza** [comment]
# Reviewed points

Result of `nixpkgs-review pr 267244` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>doge</li>
    <li>doge.dist</li>
  </ul>
</details>

- [X] package name fits guidelines
- [ ] package version fits guidelines
	- I've never seen a version like so: `${version}+prN` --- `rg --
	'version.*=.*\\+pr' pkgs/*` returns nothing.

	The [`vlc`][vlc] package, for example, fetches a patch, but does not mention
	it on its version.
- [X] package builds on x86_64-linux
- [X] executables tested on x86_64-linux
- [X] all depending packages build
- [X] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [X] patches that are remotely available are fetched rather than vendored

[vlc]: <https://github.com/NixOS/nixpkgs/blob/1a0ebc9b6a392c30b2b0fbb007540bf556587382/pkgs/applications/video/vlc/default.nix#L216>

**Comment by pbsds** [comment]
Do you have packages planned you want to go into `hareThirdParty`? Committing an empty set otherwise strikes me as silly.

**Comment by onemoresuza** [comment]
> However, the other language packages such as `python` and `nodejs` are naming this way and has no issues with `nodePackages` naming.

I think it's because they are interpreted languages. A better comparison to `Hare` would be `Nim`, which had a `nimPackages` and latter [removed it](https://github.com/NixOS/nixpkgs/pull/268685#issue-2001867929).

> 
> Also, it should be name `hareLibraries`, `hareExetended` or something else because in there website they call it this way[1], `hareThirdParty` is can be also confuse with [hare-third-party-support](https://harelang.org/platforms#third-party-support) and [third-party-tool](https://harelang.org/tools/)
> 
> [1] - https://harelang.org/extended/

I've used `hareThirdParty` because `Hare` uses the directory `<prefix>/src/hare/third-party` for libraries which are not part of it's standard library: see [`hare-json`](https://git.sr.ht/~sircmpwn/hare-json/tree/e24e5dceb8628ff569338e6c4fdba35a5017c5e2/item/Makefile#L11), a third party extended support library, and [`hare-toml`](https://codeberg.org/lunacb/hare-toml/src/commit/6f367d45ee743581d14cae53587ba571882808f9/Makefile#L12), a third party library, which is not part of the extended support.

**Comment by pbsds** [comment]
As long as the package set name makes sense to the Hare community I'm good with mostly anything. Feel free to rename set the in #268982 @starzation :)

**Pull request merged**
