### PR TITLE
jetbrains-jdk: 17.0.11 -> 21.0.3

### LINKED ISSUE #315563: Package request: jetbrains.jdk21 / jetbrains runtime 21
JetBrains publishes their own JDK. We currently have packaged the one based on OpenJDK 17. They now also have one based on OpenJDK 21 that supports wayland :3

I also tried to package it, but don't have enough java knowledge :D

**Metadata**

* homepage URL: 
* source URL: https://github.com/JetBrains/JetBrainsRuntime
* license: gpl2Only
* platforms: unix
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by herberteuler**
## Description of changes

Some features of JetBrains IDEs only work with JetBrainsRuntime. For example, Typography Settings in Editor > Font does not work properly with JDK 21, which is the JDK currently used for JetBrains IDEs in unstable. This PR updates JBR to 21.0.3 to fix this issue.

Closes #315563

## Things done

JBR is updated from 17.0.11 to 21.0.3.
JCEF is updated from 767 to 867.
The inputs `jdk` are changed from specific names like `openjdk17` to the more generic `jdk`. Finally, the bootstrapping JDK is changed to `jdk` as it is defined similarly for OpenJDK 21 in `java-packages.nix`.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Infinidoge** [comment]
I always forget just how ugly the package update process for the JetBrains stuff is. Such a pain.

Running nixpkgs review, will approve once that finishes.

**Comment by herberteuler** [comment]
> I always forget just how ugly the package update process for the JetBrains stuff is. Such a pain.

I agree. IMO, this package demonstrates what bad practice of incorporating a package might look like. Copying chunks of scripts from upstream makes it hard for newcomers to know the intricate details of how to make the configure/build/install process right, which only becomes worse when upgrading to a newer version involves merging updated scripts. In this case, it takes hours to diagnose the issue caused by the additional dependency to the apache thrift module introduced in JCEF 867.

> Also, are the unsigned/unverified commits intentional?

No. I will have to check my settings some time.

**Review by leona-ya — APPROVED** [review]
Oh thanks a lot! I also tried this update, but failed to my ... mediocre java knowledge and skills.

Diff looks good to me and I tried this (also in wayland mode) and it seems to work \o/ I'll still wait for a few days with the merge if someone else with more deep knowledge of java wants to take a look.

**Comment by jys1670** [comment]
I've tried this in Clion, everything seems to work fine (including markdown previews). Thanks!

**Comment by ShadowRZ** [comment]
Unfortunealy bumping JetBrains JDK to 21 breaks source-building IDEA Community: https://github.com/NixOS/nixpkgs/pull/316185#issuecomment-2169346817

IDEA sources seems requires building with JDK 17 as:

1. IDEA source has modules with language level of Java 1.7 which seems to be not supported by JDK 21;
2. Bumping such modules to Java 1.8 did't work properly and may requires non trivial changes IMO.

**Comment by leona-ya** [comment]
That's interesting. I'm against reverting this PR, but we can probably introduce a new derivation `jetbrains.jdk_17` and pin the source-built IntelliJ on it.

**Comment by herberteuler** [comment]
@ShadowRZ If I understand correctly, JBR 17 without JCEF is only required to build from source code, but the built executables can work with JBR 21, right?

I understand this is because JDK 17 is [a LTS version](https://en.wikipedia.org/wiki/Java_version_history). I checked [the last time when the JDK required for building was bumped (to 17)](https://github.com/JetBrains/intellij-community/commit/a1c88260765a4e72e5ebf4ce6de3ef9de921e27e), which was in August 2022. It was about a year after JDK 17 had been released in September 2021. JDK 21 was released in September 2023. This provides an estimation of when the next bump could happen.

> introduce a new derivation jetbrains.jdk_17 and pin the source-built IntelliJ on it.

Another way is to provide `jdk_21` as an option and use `jdk_17` as the default. Whichever we decide, I can work on a PR of it.

**Comment by ShadowRZ** [comment]
> @ShadowRZ If I understand correctly, JBR 17 without JCEF is only required to build from source code, but the built executables can work with JBR 21, right?

Yes that work indeed.

**Comment by leona-ya** [comment]
I'm for defaulting to jdk 21, because as mentioned on https://github.com/jetbrains/jetbrainsruntime?tab=readme-ov-file#releases-based-on-jdk-21, IntelliJ _should_ now (or at least in the 2024.2 release, which should be right around the corner) use JDK21.

**Comment by herberteuler** [comment]
> I'm for defaulting to jdk 21, because as mentioned on https://github.com/jetbrains/jetbrainsruntime?tab=readme-ov-file#releases-based-on-jdk-21, IntelliJ _should_ now (or at least in the 2024.2 release, which should be right around the corner) use JDK21.

OK. I will create a new PR later.

**Comment by raboof** [comment]
hmm, even the regular `jetbrains.idea-community` no longer builds on the merge commit for this PR (bac3e72), filed #320782 .

**Comment by herberteuler** [comment]
> @herberteuler do you want to add the additional jdk_17 and default src to it?

Yes, I am working on it.

**Comment by danielgafni** [comment]
I've updated `pycharm-professional` and it doesn't launch on Wayland: 

```
› pycharm-professional
[0.004s][warning][cds] Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

Start Failed
Failed to initialize graphics environment

java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:65)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
	at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:68)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:103)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:88)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:116)
	at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:513)
	at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:74)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:595)
	at com.intellij.platform.ide.bootstrap.UiKt$initAwtToolkit$2.invokeSuspend(ui.kt:161)
	at com.intellij.platform.ide.bootstrap.UiKt$initAwtToolkit$2.invoke(ui.kt)
	at com.intellij.platform.ide.bootstrap.UiKt$initAwtToolkit$2.invoke(ui.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
	at com.intellij.platform.ide.bootstrap.UiKt.initAwtToolkit(ui.kt:160)
	at com.intellij.platform.ide.bootstrap.UiKt.access$initAwtToolkit(ui.kt:1)
	at com.intellij.platform.ide.bootstrap.UiKt$scheduleInitAwtToolkit$task$1$1.invokeSuspend(ui.kt:123)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

-----
Your JRE: 21.0.3+35-nixos amd64 (JetBrains s.r.o.)
/nix/store/k7sikwd5ml1y8ss77mzgg8c8xh0f6v87-jetbrains-jdk-jcef-21.0.3-b465.3/lib/openjdk
```

is there anything special I should do to launch it correctly?

**Comment by leona-ya** [comment]
You need to set `-Dawt.toolkit.name=WLToolkit` in the vmoptions file of the IDE because wayland support is still beta/in development.

**Comment by danielgafni** [comment]
Thanks, it worked!

**Comment by klDen** [comment]
More info about this new flag discussed in the comments section here: https://blog.jetbrains.com/platform/2023/08/wayland-support/

**Pull request merged**
