### PR TITLE
Python: package set updates primarily for Python 3.8 support

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by jonringer** [comment]
im working on textacy, aiohttp, numpydoc, pybind11 right now. Just a heads up

**Comment by jonringer** [comment]
also, it seems like zope_exceptions is a common failing package for a lot of other packages..... it seems to build fine, looks like the site-packges installs fine... but none of the other packages seem to be able to import it

**Comment by FRidh** [comment]
probably a namespace package using the wrong namespace implementation

**Comment by jonringer** [comment]
that's what i thought as well, but if i load up the package is a pure nix-shell it seems to not be able to find it, even though it's on the PYTHONPATH

**Comment by FRidh** [comment]
but let's ignore it, it was broken already if I am correct. I recall having looked at it before

**Comment by jonringer** [comment]
do you care for maintaining python2 support?

**Comment by FRidh** [comment]
I don't. I try to keep the core packages functioning but aside from that, no. It's really up to individual maintainers. Given that python2 is EOL by the time we release 20.03 it is even less relevant.

**Comment by jonringer** [comment]
That's what I thought, was just curious about freezing packages for python2, but I'll stop doing that as it is kind of time consuming

**Comment by FRidh** [comment]
About zope. I checked, and it seems they're migrating to the correct approach using `__import__('pkg_resources').declare_namespace(__name__)` but not all packages are using it yet it seems.

**Comment by jonringer** [comment]
That's the correct approach for python2... but now i dont remember where I saw the error messages.

**Comment by jonringer** [comment]
i want to say the pkg_util is supposed to be python2 and python3 compatible:
https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by FRidh** [comment]
`zope_testrunner` is not failing. I am now collecting for all our zope packages the methods they use.

**Comment by jonringer** [comment]
yea, i noticed that it built fine, just didn't seem to "exist" when propagated to other packages

**Comment by jonringer** [comment]
do you mind if we revert setuptools to 41.0.0? it does seem to fix the
```
    AttributeError: 'SpecifierSet' object has no attribute 'split'
```
issue

**Comment by FRidh** [comment]
See https://github.com/pypa/setuptools/issues/1869#issuecomment-542929338. I prefer not too.

**Comment by FRidh** [comment]
About zope. All packages use the same `__init__.py` and same `namespace_packages=['zope'],` in `setup.py`. Checked with

```nix
with import ../nixpkgs {};
with lib;

let
  isZope = k: v: hasPrefix "zope" k;
  pkgs = filterAttrs isZope python3.pkgs;
  srcs = catAttrs "src" (attrValues pkgs);

  builder = src: stdenv.mkDerivation {
    name = src.name;
    inherit src;
    dontBuild = true;
    nativeBuildInputs = [ unzip ];

    installPhase = ''
      mkdir -p $out
      cp src/zope/__init__.py  $out/__init__.py
      cat setup.py | grep namespace > $out/setup.py
    '';

  };

  copies = map builder srcs;

in runCommand "zope" {
} ''
  mkdir -p $out
  pushd $out
  for copy in ${concatStringsSep " " copies}; do
    ln -s $copy .
  done
''
```

**Comment by jonringer** [comment]
ah, interesting, I'll open up tickets to the related projects when I'm awake again.

**Comment by jonringer** [comment]
deluge, blink, bitcoinarmory, vncdo, winswitch all got disabled by various upgrades, they will need to be bumped to using python3 to be re-enabled.

**Comment by dasj19** [comment]
this also broke the package `syncserver` as it is dependent on `webtest` which is no longer built using python2. There is a python2 webtest package in stable but none in unstable.

**Pull request merged**
