### PR TITLE
Documentation: nixpkgs manual: move Python reference to the top of Python chapter

### PR DESCRIPTION
**Pull request by alejandrosame**
This PR implements the first phase of https://github.com/NixOS/nixpkgs/issues/246234 by:

- moving non-reference content out of the `Reference` subsection of the `Python` section.
- moving the `Reference` subsection to the top of the `Python` section.

### CODE REVIEW

**Comment by alejandrosame** [comment]
Force pushed after rebasing to include recent master changes.

**Comment by alejandrosame** [comment]
@FRidh and @mweinelt, friendly ping: do you find anything problematic with these changes?

**Comment by FRidh** [comment]
Why are specifically these parts moved to FAQ? This seems to reframe content into question form.

**Comment by alejandrosame** [comment]
@FRidh and @mweinelt, ping: any further comments or objections? Do you see any problem with the general framing of https://github.com/NixOS/nixpkgs/issues/246234?

**Comment by FRidh** [comment]
> In summary, I'm proposing changes to the subsection to make the docs easier to navigate and consult. The framework being used is [Diátaxis](https://diataxis.fr/) and its definition of [reference](https://diataxis.fr/reference/). This PR aims to emphasize the content that it's closest to "pure reference". In any case, the docs need further editing efforts (incoming in future PRs) to achieve such goal.

I'm all for following the framework, and keeping reference reference only.

> I found it to be least problematic to move this non-reference content to the FAQ at this point. The questions would draw more attention for people looking for recipes, advice and explanations (which is what most of their content refers to). After moving them to the FAQ, the headings had to change to fit in and draw this attention.

I get your point of moving parts to FAQ. I'd rather had the content was written in such a way that it would be part of the reference but that is more effort. And, writing reference material for Nixpkgs is extremely hard given we do not have any framework for say extracting docstrings (because you can't have those either).

Thus, I understand the changes, and I agree with the general direction and won't oppose it, however, I am afraid that more ends up in FAQ's which tend to be unorganized instead of structured reference material.

**Pull request merged**
