### PR TITLE
nixos/libvirtd: improved swtpm support

### PR DESCRIPTION
**Pull request by witchof0x20**
###### Motivation for this change
As-is, libvirt will fail to initialize an emulated tpm. This patch provides a mechanism to fix that.
Related to #141224 

###### Things done
Added configuration option to virtualisation.libvirt for enabling software TPM.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]
Just minor comestic changes, but otherwise LGTM.

**Comment by thiagokokada** [comment]
> I'm not sure if this is the proper solution? The prefix given be `--localstatedir` ends up getting used as a prefix in the generated`$out/etc/swtpm-localca.conf`. Preferably, this prefix should be `/var`

Ah ok, now I understood the issue. The issue is just the generated path on `$out/etc/swtpm-localca.conf`, everything else seems fine. Another option maybe would be to do something like this:

```
cat  > $out/etc/swtpm-localca.conf <<EOF
statedir = /var/lib/swtpm-localca
signingkey = /var/lib/swtpm-localca/signkey.pem
issuercert = /var/lib/swtpm-localca/issuercert.pem
certserial = /var/lib/swtpm-localca/certserial
EOF
```

Would be slightly clear what is happening, but I think the proposed fix is fine.

WDYT @sternenseemann?

**Comment by thiagokokada** [comment]
> IMO `$out/etc/swtpm-localca.conf` already makes very little sense, we use `/etc` on NixOS. Ideally we fix this by preventing `swtpm` from looking into `$out` for configuration and state files altogether and instead provide a proper configuration in the nixos module which points it to a proper state directory (created by `systemd.tmpfiles`?) via `environment.etc` or a file passed at the command line (if possible).

Makes sense. However I think this PR is mostly for the `virtualisation.libvirtd` module changes than the `swtpm` changes (that are the bare minimum to make it work correctly).

Maybe we could just add a TODO comment on the `swtpm` derivation that we need to create a proper module later, and this could be created in another PR?

**Comment by thiagokokada** [comment]
@witchof0x20 Now that #141771 is merged, can you modify your PR to just keep the modules change?

**Comment by witchof0x20** [comment]
Can do!

**Comment by Luflosi** [comment]
I don't think `qemuSwtpm` is a good name for the option. Maybe a name such as `enableTPM` or `tpmSupport` would be better. Does anyone have any better suggestions?

**Review by thiagokokada — APPROVED** [review]

**Comment by Luflosi** [comment]
Ok, fair enough.

**Review by Luflosi — APPROVED** [review]
LGTM.

**Comment by witchof0x20** [comment]
resolved the merge conflict

**Pull request merged**
