### PR TITLE
neofetch: set meta.mainProgram

### PR DESCRIPTION
**Pull request by legendofmiracles**
###### Motivation for this change
I'm adding these whenever i see a package that doesn't work with `nix run`.
`nix run` is the fastest way to run neofetch, and it broke with https://github.com/NixOS/nixpkgs/pull/120434

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Hmm, `unstable-` is actually part of the version, but still taken into account for the executable name. While this is fine to merge, this actually seems like a bug in Nix to me.

**Comment by legendofmiracles** [comment]
If you search for neofetch on nixpkgs search it's name is `neofetch-unstable`
image
The version isn't taken into account :thinking:

**Comment by Ma27** [comment]
Well, the `pname` is `neofetch`, the `version` is `unstable-2020-11-26`. Even though both are concatenated with a `-` to `name`, this behavior seems wrong to me.

**Comment by lukegb** [comment]
Yeah, unfortunately this is what happens, because that's generated by taking the name (aka ${pname}-${version}), then running it through builtins.parseDrvName and getting the name and version back out again...

which puts -unstable on the end of the name part.

**Pull request merged**
