### PR TITLE
headphones-toolbox: 0.0.4 -> 0.0.5

### PR DESCRIPTION
**Pull request by nyabinary**
## Description of changes
Update headphones-toolbox to 0.0.5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lambdachad — APPROVED** [review]

**Comment by cab404** [comment]
@nyabinary does it work for you? even after adding udev rules it still doesn't show amp config.


i've checked and it works fine under ubuntu and macos

**Comment by cab404** [comment]
I've bumped to https://github.com/george-norton/headphones-toolbox/releases/tag/v0.0.6 and that doesn't resolve this problem

**Comment by cab404** [comment]
```diff
diff --git a/pkgs/by-name/he/headphones-toolbox/package.nix b/pkgs/by-name/he/headphones-toolbox/package
.nix
index 9f520d7c4875..56d6ca9c9401 100644
--- a/pkgs/by-name/he/headphones-toolbox/package.nix
+++ b/pkgs/by-name/he/headphones-toolbox/package.nix
@@ -8,11 +8,11 @@

 stdenv.mkDerivation (finalAttrs: {
   name = "headphones-toolbox";
-  version = "0.0.5";
+  version = "0.0.6";

   src = fetchurl {
-    url = "https://github.com/ploopyco/headphones-toolbox/releases/download/app-v${finalAttrs.version}/ploopy-headphones-toolbox_${finalAttrs.version}_amd64.deb";
-    hash = "sha256-lWjmpybGcL3sbBng8zCTUtwYhlrQ6cCrKkhiu+g9MsE=";
+    url = "https://github.com/george-norton/headphones-toolbox/releases/download/v${finalAttrs.version}/ploopy-headphones-toolbox_${finalAttrs.version}_amd64.deb";
+    hash = "sha256-iE3K2lmVuTbsOhE9b3WKFRErE4SFxa73YbxcElTUc0s=";
   };

   nativeBuildInputs = [
```

**Comment by nyabinary** [comment]
> @nyabinary does it work for you? even after adding udev rules it still doesn't show amp config.
> 
> i've checked and it works fine under ubuntu and macos

Last time I tried it, it did work for me, maybe ask around in the ploopy discord/

**Comment by cab404** [comment]
> > @nyabinary does it work for you? even after adding udev rules it still doesn't show amp config.
> > i've checked and it works fine under ubuntu and macos
> 
> Last time I tried it, it did work for me, maybe ask around in the ploopy discord/

Already did

Does it have GStreamer errors in your output?
e.g
```
GStreamer element autoaudiosink not found. Please install it
```

**Pull request merged**
