### PR TITLE
pijul: 1.0.0-alpha.53 → 1.0.0-alpha.54

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Use -> instead of →

**Comment by fabianhjr** [comment]
Have been using unicode right arrow for a while now: https://github.com/NixOS/nixpkgs/commits?author=fabianhjr

**Comment by Artturin** [comment]
It's in contributing.md and it'd be nice to stay consistent with all the other commits

**Comment by fabianhjr** [comment]
I am looking for documentation on Unicode right arrow vs ASCII right arrow since I remember to have checked before switching.

https://discourse.nixos.org/t/vs-in-a-commit-message/11180

AFAIK it is widely used but hasn't been included in contributing guidelines.

**Pull request merged**
