### PR TITLE
python3Packages.poetry: 1.1.4 -> 1.1.5

### PR DESCRIPTION
**Pull request by austinbutler**
###### Motivation for this change

Upgrade package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119091` at 45e3b793 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.datashader</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.optuna</li>
    <li>python38Packages.pymc3</li>
    <li>python38Packages.shap</li>
    <li>python38Packages.skorch</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.ignite</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>148 packages skipped due to time constraints:</summary>
  <ul>
    <li>aiodnsbrute</li>
    <li>apache-airflow</li>
    <li>backblaze-b2</li>
    <li>check_systemd</li>
    <li>checkov</li>
    <li>conan</li>
    <li>deja-dup</li>
    <li>dpt-rp1-py</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>66 packages built successfully:</summary>
  <ul>
    <li>ansible-lint (python38Packages.ansible-lint)</li>
    <li>archivy</li>
    <li>cmake-language-server</li>
    <li>home-assistant</li>
    <li>jrnl</li>
    <li>lexicon</li>
    <li>piston-cli</li>
    <li>python38Packages.aioeafm</li>
    <li>python38Packages.aioguardian</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.aioswitcher</li>
    <li>python38Packages.aria2p</li>
    <li>python38Packages.backoff</li>
    <li>python38Packages.censys</li>
    <li>python38Packages.enrich</li>
    <li>python38Packages.hypothesis-auto</li>
    <li>python38Packages.labelbox</li>
    <li>python38Packages.myfitnesspal</li>
    <li>python38Packages.myjwt</li>
    <li>python38Packages.ndjson</li>
    <li>python38Packages.perfplot</li>
    <li>python38Packages.plexapi</li>
    <li>python38Packages.poetry</li>
    <li>python38Packages.pyairnow</li>
    <li>python38Packages.pysnow</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.questionary</li>
    <li>python38Packages.rich</li>
    <li>python38Packages.roombapy</li>
    <li>staticjinja (python38Packages.staticjinja)</li>
    <li>python38Packages.surepy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python38Packages.tinydb</li>
    <li>python38Packages.toonapi</li>
    <li>python38Packages.tqdm</li>
    <li>python38Packages.twine</li>
    <li>python38Packages.url-normalize</li>
    <li>python38Packages.wled</li>
    <li>python39Packages.aioeafm</li>
    <li>python39Packages.aioswitcher</li>
    <li>python39Packages.ansible-lint</li>
    <li>python39Packages.backoff</li>
    <li>python39Packages.censys</li>
    <li>python39Packages.enrich</li>
    <li>python39Packages.hypothesis-auto</li>
    <li>python39Packages.labelbox</li>
    <li>python39Packages.myfitnesspal</li>
    <li>python39Packages.myjwt</li>
    <li>python39Packages.ndjson</li>
    <li>python39Packages.perfplot</li>
    <li>python39Packages.poetry</li>
    <li>python39Packages.pyairnow</li>
    <li>python39Packages.pysnow</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.questionary</li>
    <li>python39Packages.rich</li>
    <li>python39Packages.staticjinja</li>
    <li>python39Packages.surepy</li>
    <li>python39Packages.teslajsonpy</li>
    <li>python39Packages.tinydb</li>
    <li>python39Packages.toonapi</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.twine</li>
    <li>python39Packages.url-normalize</li>
    <li>python39Packages.wled</li>
    <li>spotdl</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 119091` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.optuna</li>
    <li>python38Packages.pymc3</li>
    <li>python38Packages.shap</li>
    <li>python38Packages.skorch</li>
    <li>python38Packages.textacy</li>
    <li>python39Packages.optuna</li>
    <li>python39Packages.skorch</li>
    <li>python39Packages.textacy</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>python38Packages.pywick</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.pywick</li>
    <li>python39Packages.transformers</li>
  </ul>
</details>
<details>
  <summary>217 packages built:</summary>
  <ul>
    <li>aiodnsbrute</li>
    <li>ansible-lint (python38Packages.ansible-lint)</li>
    <li>archivy</li>
    <li>backblaze-b2</li>
    <li>check_systemd</li>
    <li>checkov</li>
    <li>cmake-language-server</li>
    <li>conan</li>
    <li>deja-dup</li>
    <li>dpt-rp1-py</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>evdevremapkeys</li>
    <li>evillimiter</li>
    <li>ffmpeg-normalize</li>
    <li>gdown (python38Packages.gdown)</li>
    <li>gnome-keysign</li>
    <li>home-assistant</li>
    <li>jellyfin-mpv-shim</li>
    <li>jrnl</li>
    <li>kaggle (python38Packages.kaggle)</li>
    <li>keepkey_agent (python38Packages.keepkey_agent)</li>
    <li>ldeep</li>
    <li>ledger_agent (python38Packages.ledger_agent)</li>
    <li>lexicon</li>
    <li>lieer</li>
    <li>luigi</li>
    <li>magic-wormhole (python38Packages.magic-wormhole)</li>
    <li>manim</li>
    <li>mathlibtools (python38Packages.mathlibtools)</li>
    <li>mnemosyne</li>
    <li>noto-fonts-emoji</li>
    <li>nrfutil</li>
    <li>ocrmypdf</li>
    <li>papis (python38Packages.papis)</li>
    <li>past-time</li>
    <li>piston-cli</li>
    <li>plex-mpv-shim</li>
    <li>python38Packages.afdko</li>
    <li>python38Packages.aioeafm</li>
    <li>python38Packages.aioguardian</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.aiosmb</li>
    <li>python38Packages.aioswitcher</li>
    <li>python38Packages.ansible-kernel</li>
    <li>python38Packages.ansible-runner</li>
    <li>python38Packages.aria2p</li>
    <li>python38Packages.b2sdk</li>
    <li>python38Packages.backoff</li>
    <li>python38Packages.baselines</li>
    <li>python38Packages.censys</li>
    <li>python38Packages.cirq</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.dipy</li>
    <li>python38Packages.dnachisel</li>
    <li>python38Packages.enrich</li>
    <li>python38Packages.genome-collector</li>
    <li>python38Packages.gradient</li>
    <li>python38Packages.gradient-utils</li>
    <li>python38Packages.graphtage</li>
    <li>python38Packages.gtts</li>
    <li>python38Packages.holoviews</li>
    <li>python38Packages.huggingface-hub</li>
    <li>python38Packages.hvplot</li>
    <li>python38Packages.hyperopt</li>
    <li>python38Packages.hypothesis-auto</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.internetarchive</li>
    <li>python38Packages.labelbox</li>
    <li>python38Packages.libagent</li>
    <li>python38Packages.lsassy</li>
    <li>python38Packages.mesa</li>
    <li>python38Packages.moviepy</li>
    <li>python38Packages.msldap</li>
    <li>python38Packages.myfitnesspal</li>
    <li>python38Packages.myjwt</li>
    <li>python38Packages.nagiosplugin</li>
    <li>python38Packages.nbsmoke</li>
    <li>python38Packages.ndjson</li>
    <li>python38Packages.nltk</li>
    <li>python38Packages.nototools</li>
    <li>python38Packages.panel</li>
    <li>python38Packages.papermill</li>
    <li>python38Packages.parfive</li>
    <li>python38Packages.perfplot</li>
    <li>python38Packages.plexapi</li>
    <li>python38Packages.poetry</li>
    <li>python38Packages.proglog</li>
    <li>python38Packages.pyairnow</li>
    <li>python38Packages.pyppeteer</li>
    <li>python38Packages.pypykatz</li>
    <li>python38Packages.pyro-ppl</li>
    <li>python38Packages.pysnow</li>
    <li>python38Packages.python-daemon</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.python-mpv-jsonipc</li>
    <li>python38Packages.pytorch-lightning</li>
    <li>python38Packages.pytorch-metric-learning</li>
    <li>python38Packages.questionary</li>
    <li>python38Packages.rbtools</li>
    <li>python38Packages.rich</li>
    <li>python38Packages.rising</li>
    <li>python38Packages.roombapy</li>
    <li>python38Packages.sacremoses</li>
    <li>python38Packages.salmon-mail</li>
    <li>python38Packages.spacy</li>
    <li>staticjinja (python38Packages.staticjinja)</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.surepy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python38Packages.thinc</li>
    <li>python38Packages.tinydb</li>
    <li>python38Packages.toggl-cli</li>
    <li>python38Packages.toonapi</li>
    <li>python38Packages.tqdm</li>
    <li>trezor_agent (python38Packages.trezor_agent)</li>
    <li>python38Packages.tubeup</li>
    <li>python38Packages.twine</li>
    <li>python38Packages.url-normalize</li>
    <li>python38Packages.wled</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.aioeafm</li>
    <li>python39Packages.aiosmb</li>
    <li>python39Packages.aioswitcher</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.ansible-lint</li>
    <li>python39Packages.ansible-runner</li>
    <li>python39Packages.b2sdk</li>
    <li>python39Packages.backoff</li>
    <li>python39Packages.baselines</li>
    <li>python39Packages.censys</li>
    <li>python39Packages.cirq</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.dipy</li>
    <li>python39Packages.dnachisel</li>
    <li>python39Packages.enrich</li>
    <li>python39Packages.gdown</li>
    <li>python39Packages.genome-collector</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.gradient-utils</li>
    <li>python39Packages.graphtage</li>
    <li>python39Packages.gtts</li>
    <li>python39Packages.holoviews</li>
    <li>python39Packages.huggingface-hub</li>
    <li>python39Packages.hvplot</li>
    <li>python39Packages.hyperopt</li>
    <li>python39Packages.hypothesis-auto</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.internetarchive</li>
    <li>python39Packages.kaggle</li>
    <li>python39Packages.keepkey_agent</li>
    <li>python39Packages.labelbox</li>
    <li>python39Packages.ledger_agent</li>
    <li>python39Packages.libagent</li>
    <li>python39Packages.lsassy</li>
    <li>python39Packages.magic-wormhole</li>
    <li>python39Packages.mathlibtools</li>
    <li>python39Packages.mesa</li>
    <li>python39Packages.moviepy</li>
    <li>python39Packages.msldap</li>
    <li>python39Packages.myfitnesspal</li>
    <li>python39Packages.myjwt</li>
    <li>python39Packages.nagiosplugin</li>
    <li>python39Packages.nbsmoke</li>
    <li>python39Packages.ndjson</li>
    <li>python39Packages.nltk</li>
    <li>python39Packages.nototools</li>
    <li>python39Packages.panel</li>
    <li>python39Packages.papermill</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.parfive</li>
    <li>python39Packages.perfplot</li>
    <li>python39Packages.plexapi</li>
    <li>python39Packages.poetry</li>
    <li>python39Packages.proglog</li>
    <li>python39Packages.pyairnow</li>
    <li>python39Packages.pyppeteer</li>
    <li>python39Packages.pypykatz</li>
    <li>python39Packages.pyro-ppl</li>
    <li>python39Packages.pysnow</li>
    <li>python39Packages.python-daemon</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.python-mpv-jsonipc</li>
    <li>python39Packages.pytorch-lightning</li>
    <li>python39Packages.pytorch-metric-learning</li>
    <li>python39Packages.questionary</li>
    <li>python39Packages.rbtools</li>
    <li>python39Packages.rich</li>
    <li>python39Packages.rising</li>
    <li>python39Packages.sacremoses</li>
    <li>python39Packages.salmon-mail</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.staticjinja</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.surepy</li>
    <li>python39Packages.teslajsonpy</li>
    <li>python39Packages.thinc</li>
    <li>python39Packages.tinydb</li>
    <li>python39Packages.toonapi</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.trezor_agent</li>
    <li>python39Packages.tubeup</li>
    <li>python39Packages.twine</li>
    <li>python39Packages.url-normalize</li>
    <li>python39Packages.wled</li>
    <li>r128gain</li>
    <li>sacad</li>
    <li>spotdl</li>
    <li>tartube</li>
    <li>theharvester</li>
    <li>tinyprog</li>
    <li>tts</li>
    <li>twitter-color-emoji</li>
    <li>urlwatch</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Confirmed that the five packages that failed to build also fail to build on master.

**Comment by fabaff** [comment]
At least `python38Packages.transformer` looks like an easy fix: https://github.com/NixOS/nixpkgs/pull/119106

**Pull request merged**
