### PR TITLE
erlang_21: remove, erlang_22: remove

### PR DESCRIPTION
**Pull request by superherointj**
* erlang_22: remove
* erlang_21: remove

CC @wegank @happysalada

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 222436` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>ejabberd</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>erlang_24</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Looks like there is still a ci failure

https://gist.github.com/GrahamcOfBorg/80b43076a4cc64ce9739276bf7630901

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 222436` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by wegank — APPROVED** [review]

**Comment by DianaOlympos** [comment]
Wait we still had them? I thought I had cleaned that up a long time ago?

You may want to update the nixos release documentation also noting that we removed them, but I thought I had done it already multiple time oO what happened there oO

**Review by DianaOlympos — APPROVED** [review]

**Pull request merged**
