### PR TITLE
Added Numix/Numix-Circle icon theme and Numix GTK theme

### PR DESCRIPTION
**Pull request by taktoa**

### CODE REVIEW

**Comment by taktoa** [comment]
Yes, GPLv3. Sorry about the incorrect metadata.

**Comment by iyzsong** [comment]
Merged, thanks!

**Comment by iyzsong** [comment]
oops, these should be installed into `$out/share` instead of `$out/usr/share`,
and commit rev shouldn't used as package version (it break update).

I have pushed fixes.

**Comment by taktoa** [comment]
Thanks, sorry for the trouble; this is my first time contributing a Nix package

**Comment by iyzsong** [comment]
Nevermind, you're welcome.

**Pull request merged**
