### PR TITLE
unifi: introduce unifiTesting and upgrade unifiLTS and unifiStable

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Regular package updates as well as making the test version available.

The suffix for the testing download can be obtained after signing up for their beta program. I haven't tried this package admittedly.

Cc: @badi @wkennington 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Forgot to mention - I find the ```callPackages``` with a generic builder far easier to maintain and read than using a boolean flag which obviously also limits the options to 2...

**Comment by badi** [comment]
This is great!
If you'd like, I'm willing to test `unifiStable` and possible `unifiTesting` on my network and report back.

**Comment by peterhoeg** [comment]
Please do.

**Comment by badi** [comment]
No problems so far with `unifiStable` or `unifiTesting`.

**Pull request merged**
