### PR TITLE
Django: 2.2.19 -> 2.2.20; 3.1.7 -> 3.2; asgiref: 3.3.1 -> 3.3.2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://www.djangoproject.com/weblog/2021/apr/06/security-releases/
https://www.djangoproject.com/weblog/2021/apr/06/django-32-released/

Django 3.2 required an asgiref update.
https://github.com/django/asgiref/blob/34d1602c90ff1f5f0ca70919bc9c6a268285f80a/CHANGELOG.txt#L1-L14

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
build home-assistant until pandas.

**Comment by lsix** [comment]
Hi,

Given that django-3.2 is the new LTS, when do we want to update `pkgs.django` to use it ? I think the safe approach will be to change that after 21.05 branchoff.

I’ll test & review the PR ASAP.

Thanks!

**Comment by SuperSandro2000** [comment]
> I think the safe approach will be to change that after 21.05 branchoff.

We should do that before that it lands in 21.05.

**Comment by mweinelt** [comment]
> > I think the safe approach will be to change that after 21.05 branchoff.
> 
> We should do that before that it lands in 21.05.

So exactly the opposite of what the maintainer proposed, why?

**Comment by SuperSandro2000** [comment]
> So exactly the opposite of what the maintainer proposed, why?

I thought it still points to 3.1 for which support ended today and the bump to 3.2 would be logically to do but apparently it still points to 2.X which has support until mid 2022 so we can also bump it after the branch off.

**Comment by lsix** [comment]
I do not really have a big problem bumping the main `django` attribute to 3.2. I just expect a fair amount of breakage, and considering 2.2 is still maintained for quite some time (longer than our next release) I do not necessarily see a need to rush it.

**Comment by risicle** [comment]
`python38Packages.django_2`, `python38Packages.django_3` & `python38Packages.asgiref` build happily, macos 10.14

**Comment by mweinelt** [comment]
@lsix Merge at your own discretion.

**Comment by lsix** [comment]
It looks good to me.

I am currently rebuilding a stack of mine with those patches applied just for a quick test and I’ll merge just after that!

**Comment by lsix** [comment]
Actually, I just realised thas `asgiref` had 2 fast releases yesterday. @mweinelt do you mind bumping it directly to 3.3.4 ?

Changelog: https://github.com/django/asgiref/blob/main/CHANGELOG.txt#L1-L12

**Comment by risicle** [comment]
I'm curious how this becomes 5000 rebuilds :thinking:

**Comment by mweinelt** [comment]
@lsix Done!

**Comment by lsix** [comment]
All good!

I’ll prepare the backport for django_2 probably tomorrow (unless someone does it before of course).

Thanks!!!

**Pull request merged**
