### PR TITLE
vscode: cleanup closure

### LINKED ISSUE #115033: vscode requires both gtk2 and gtk3 while the binary needs only gtk3
**Describe the bug**
Running `readelf -d` on vscode binary says that it depends only on gtk3:
```
[nix-shell:~]$ readelf -d /nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/code

Dynamic section at offset 0x7916000 contains 64 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/nwpwnz9ghydmqiic0psjc8gl4jlw9fmc-systemd-247.2/lib:/nix/store/z8fj0cn39f3had3ln5mfpljc6wk677n2-fontconfig-2.13.92-lib/lib:/nix/store/4n8pxndg55cfff17cvq807244z7imp8j-libdbusmenu-glib-16.04.0/lib:/nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode:/nix/store/hnk0s558k2h4v8abjzagagflvw1l0cb2-glib-2.66.4/lib:/nix/store/hnk0s558k2h4v8abjzagagflvw1l0cb2-glib-2.66.4/lib:/nix/store/hnk0s558k2h4v8abjzagagflvw1l0cb2-glib-2.66.4/lib:/nix/store/21rvs9iwalprxr5nav363hxm1pvx7776-nss-3.60/lib:/nix/store/21rvs9iwalprxr5nav363hxm1pvx7776-nss-3.60/lib:/nix/store/21rvs9iwalprxr5nav363hxm1pvx7776-nss-3.60/lib:/nix/store/yh01im65a1bzg7v510vjrb179skqy3f5-nspr-4.29/lib:/nix/store/49p0rmg683iyd23bn72mm2k1xajxfg42-atk-2.36.0/lib:/nix/store/c142a5ljsxag2qn1x5378aazw7lh1z72-at-spi2-atk-2.38.0/lib:/nix/store/6y53vmypx0lmd0r43sa8qsd026yqfsmz-libX11-1.7.0/lib:/nix/store/6y53vmypx0lmd0r43sa8qsd026yqfsmz-libX11-1.7.0/lib:/nix/store/0k01pc905yqyyg0fc8c9p400vizwwcdj-libxcb-1.14/lib:/nix/store/svvxq196imx6n9kv8alb9v7mh6j0lawd-dbus-1.12.20-lib/lib:/nix/store/d3fsl9w5x6z29jr2j08qsj16p5wyhz39-gdk-pixbuf-2.42.2/lib:/nix/store/8pidhwid3ww58wlq705irf48c01dr0hv-gtk+3-3.24.24/lib:/nix/store/8pidhwid3ww58wlq705irf48c01dr0hv-gtk+3-3.24.24/lib:/nix/store/8p69v6c3rwb9rql2v58cwg7r6ss6f54q-pango-1.47.0/lib:/nix/store/zkcm2zq8bxj70jcllyb1hfbihg52lid2-cairo-1.16.0/lib:/nix/store/2lgzq28ksvrkg1sb243q3922vbjz7yll-libXcomposite-0.4.5/lib:/nix/store/w1c4hsx5sgaj5x7k89mhn9brakrsfyrr-libXdamage-1.1.5/lib:/nix/store/dm9k4ryj2dykk32z560a0mfnlf9c3pb8-libXext-1.3.4/lib:/nix/store/711rkgxcxns81vv9m8cdr0kxav0v7xr0-libXfixes-5.0.3/lib:/nix/store/vfplfil999jhafr73ykag0g76dagcf7h-libXrandr-1.5.2/lib:/nix/store/555f8kb8pz5iqaww6wj05xqw8vi0cwpx-expat-2.2.10/lib:/nix/store/10drv240gc5fkxdwm2zrsdgx355jqfsd-libdrm-2.4.104/lib:/nix/store/d9m2izbizzzg183a8hx7i5vid2xp971n-libxkbcommon-1.0.3/lib:/nix/store/d5i3myxprqjw09rgihh1wc1sdmvwikc4-mesa-20.3.3/lib:/nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib:/nix/store/kry0rgsqqd7r9370yx67jci6zn785bcr-at-spi2-core-2.38.0/lib]
 0x0000000000000001 (NEEDED)             Shared library: [libffmpeg.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgio-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libnss3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libnssutil3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsmime3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libnspr4.so]
 0x0000000000000001 (NEEDED)             Shared library: [libatk-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libatk-bridge-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libX11-xcb.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libxcb.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdbus-1.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk_pixbuf-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgtk-3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk-3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpango-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcairo.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdamage.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrandr.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libexpat.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libxkbcommon.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgbm.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libasound.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libatspi.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000001e (FLAGS)              BIND_NOW STATIC_TLS
 0x000000006ffffffb (FLAGS_1)            Flags: NOW PIE
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000007 (RELA)               0x14e670
 0x0000000000000008 (RELASZ)             10755144 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          448062
 0x0000000000000017 (JMPREL)             0xb902b8
 0x0000000000000002 (PLTRELSZ)           33720 (bytes)
 0x0000000000000003 (PLTGOT)             0x773ebd0
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x78c3000
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x7916410
 0x000000000000000a (STRSZ)              909548 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x59770
 0x0000000000000019 (INIT_ARRAY)         0x72db8a8
 0x000000000000001b (INIT_ARRAYSZ)       232 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x72db898
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000000000000c (INIT)               0x72d13ec
 0x000000000000000d (FINI)               0x72d1404
 0x000000006ffffff0 (VERSYM)             0x526b0
 0x000000006ffffffe (VERNEED)            0x5944c
 0x000000006fffffff (VERNEEDNUM)         12
 0x0000000000000000 (NULL)               0x0
```

While the package depends on both gtk2 and gtk3:
```
   nix-store -q --references /nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2
/nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35
/nix/store/0k01pc905yqyyg0fc8c9p400vizwwcdj-libxcb-1.14
/nix/store/10drv240gc5fkxdwm2zrsdgx355jqfsd-libdrm-2.4.104
/nix/store/sipmc4wnbcws4vahqlf5i06zz7xgnp23-gcc-10.2.0-lib
/nix/store/yh01im65a1bzg7v510vjrb179skqy3f5-nspr-4.29
/nix/store/21rvs9iwalprxr5nav363hxm1pvx7776-nss-3.60
/nix/store/6y53vmypx0lmd0r43sa8qsd026yqfsmz-libX11-1.7.0
/nix/store/2lgzq28ksvrkg1sb243q3922vbjz7yll-libXcomposite-0.4.5
/nix/store/34pxya806cmz0y4mcajcdbz6jzm9k6m2-libxkbfile-1.1.0
/nix/store/hnk0s558k2h4v8abjzagagflvw1l0cb2-glib-2.66.4
/nix/store/49p0rmg683iyd23bn72mm2k1xajxfg42-atk-2.36.0
/nix/store/4n8pxndg55cfff17cvq807244z7imp8j-libdbusmenu-glib-16.04.0
/nix/store/555f8kb8pz5iqaww6wj05xqw8vi0cwpx-expat-2.2.10
/nix/store/711rkgxcxns81vv9m8cdr0kxav0v7xr0-libXfixes-5.0.3
/nix/store/cwnwyy82wrq53820z6yg7869z8dl5s7g-bash-4.4-p23
/nix/store/nwpwnz9ghydmqiic0psjc8gl4jlw9fmc-systemd-247.2
/nix/store/svvxq196imx6n9kv8alb9v7mh6j0lawd-dbus-1.12.20-lib
/nix/store/7h1dszghc86ra1n0265ji5hyxc1k6b0q-gconf-3.2.6
/nix/store/7nphq5g2ydk8mwk4qavyh0m65ag44c7r-libgnome-keyring-3.12.0
/nix/store/wbdlg8p4ikn3xa0g5qcbbxzrx5rc7xgg-harfbuzz-2.7.2
/nix/store/z8fj0cn39f3had3ln5mfpljc6wk677n2-fontconfig-2.13.92-lib
/nix/store/dm9k4ryj2dykk32z560a0mfnlf9c3pb8-libXext-1.3.4
/nix/store/zkcm2zq8bxj70jcllyb1hfbihg52lid2-cairo-1.16.0
/nix/store/8p69v6c3rwb9rql2v58cwg7r6ss6f54q-pango-1.47.0
/nix/store/kiv7lblf1wdy1ygqj91brfb5jaymgjrp-dconf-0.38.0-lib
/nix/store/zd6fx5lka49c66fr5iq2a9flh0mdzzrh-gsettings-desktop-schemas-3.38.0
/nix/store/kry0rgsqqd7r9370yx67jci6zn785bcr-at-spi2-core-2.38.0
/nix/store/c142a5ljsxag2qn1x5378aazw7lh1z72-at-spi2-atk-2.38.0
/nix/store/d3fsl9w5x6z29jr2j08qsj16p5wyhz39-gdk-pixbuf-2.42.2
/nix/store/d9m2izbizzzg183a8hx7i5vid2xp971n-libxkbcommon-1.0.3
/nix/store/vfplfil999jhafr73ykag0g76dagcf7h-libXrandr-1.5.2
/nix/store/w1c4hsx5sgaj5x7k89mhn9brakrsfyrr-libXdamage-1.1.5
/nix/store/8pidhwid3ww58wlq705irf48c01dr0hv-gtk+3-3.24.24
/nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4
/nix/store/9fyhdgrnzksir17bhksvjbqzw80f98h9-gtk+-2.24.32
/nix/store/9kbpdsvs9i3snk2x7yzwsfl4g85lbw2p-code-url-handler.desktop
/nix/store/b7mqqqqn6fqa36bf9gsharj1h1kfy31j-libsecret-0.20.4
/nix/store/cjds3hyvqyk9nlhy12nvf8rrcq5wvzll-code.desktop
/nix/store/d5i3myxprqjw09rgihh1wc1sdmvwikc4-mesa-20.3.3
/nix/store/lhkxz0srn9i8r4hmw0x883micp4dsy4r-librsvg-2.50.1
/nix/store/rj52rhryvyna9wbryh4n1d3lj3lzq0cd-gobject-introspection-1.66.1
/nix/store/sljhsq3696pazcdhw2xjaj1cicysw5gj-libnotify-0.7.9
/nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2
```

Probably there are some packaging issue?

**To Reproduce**
1. Install vscode

**Expected behavior**
It depends only on gtk3

**Notify maintainers**
@eadwu @Synthetica9 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.10-zen1, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/run/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [vscode]
# a list of nixos modules affected by the problem
module: []
```

### PR DESCRIPTION
**Pull request by ilya-fedin**
###### Description of changes
Fixes #115033 (I also found a bug of pulling all the build dependencies due to a `cp ./*` command)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
@ofborg test vscode

**Comment by turion** [comment]
I don't understand why ofborg doesn't run the tests.

**Comment by turion** [comment]
@ofborg test vscodium

**Comment by Synthetica9** [comment]
Fails to build vscode on my machine with 

```
/nix/store/zgmfwb9wxi6dwczlw43j52rrj7295rn1-vscode-1.65.2.drv
```

**Comment by ilya-fedin** [comment]
Is there a blocker?

**Comment by SuperSandro2000** [comment]
> Is there a blocker?

No, just someone needs to say this a okay.

**Review by eadwu — APPROVED** [review]
Dropping `gtk2` is fine as far as I can tell.

Never experienced the `env-vars` issue. Build still works for me.

**Comment by ilya-fedin** [comment]
> Never experienced the `env-vars` issue. Build still works for me.

I can reproduce it only with VSCodium, because it builds on Hydra while VSCode is not I guess

**Pull request merged**
