### PR TITLE
gpu-screen-recorder{-,gtk}: 4.2.1 -> 4.2.3

### LINKED ISSUE #349648: gpu-screen-recorder: fails to record
### Describe the bug

gpu-screen-recorder after latest bump/module change does not record.

### Steps To Reproduce
1. Enable gpu-screen-recorder module. `programs.gpu-screen-recorder.enable = true;`
2. Run a command like: `gpu-screen-recorder -w DP-1 -c mkv -q ultra -f 60 -k av1 -o ~/Videos`
3. See error that program is not in PATH.
4. Add `gpu-screen-recorder` to `environment.systemPackages`, rebuild
5. Run command again and see:

```
┌───────────────────>
│keenan in ~
❌255 ❄️ zsh ›
└─>gpu-screen-recorder -w DP-1 -c mkv -q ultra -f 60 -k av1 -o /home/keenan/Videos
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
gsr error: gsr_kms_client_init: gsr-kms-server is not installed (/nix/store/pw1kisi5r82ck96f46lqggbxlvklarmm-gpu-screen-recorder-4.2.1/bin/.wrapped/gsr-kms-server not found)
gsr error: gsr_capture_start failed
```
### Expected behavior

Should start recording.

### Screenshots

image

### Additional context

I didn't see this behavior in testing the changes, so I must've done something wrong.

### Notify maintainers
@DontEatOreo
@dec05eba (tagging for GSR knowledge)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.3, NixOS, 24.11 (Vicuna), 24.11.20241016.5785b6b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/w7nfn4lcfisddz14b0y8n05rjf0dl5lq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by keenanweaver**
Closes https://github.com/NixOS/nixpkgs/issues/349648

Bumps to 4.2.3, fixing nix specific issues. See discussion in linked issue.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
@ofBorg eval

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349665 --extra-nixpkgs-config '{ allowAliases = false; allowBroken = false; allowUnfree = true; checkMeta = true; cudaSupport = true; cudaCapabilities = [ "7.5" ]; }'`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>gpu-screen-recorder</li>
    <li>gpu-screen-recorder-gtk</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
Checking out the PR, and building with both `gpu-screen-recorder` and `gpu-screen-record-gtk` using `nix-build -A ...` works fine, and the program functions as expected

**Comment by DontEatOreo** [comment]
## Using `--eval local`

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349665 --extra-nixpkgs-config '{ allowAliases = false; allowBroken = false; allowUnfree = true; checkMeta = true; cudaSupport = true; cudaCapabilities = [ "7.5" ]; }'`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>gpu-screen-recorder</li>
    <li>gpu-screen-recorder-gtk</li>
  </ul>
</details>

**Pull request merged**
