### PR TITLE
citra: nightly 1873 -> 1907, canary 2440 -> 2484

### LINKED ISSUE #216744: Update request: citra-nightly 1765 → 1843
- Package name: citra-nightly
- Latest released version: 1843

- Current version on the unstable channel: 1765
- Current version on the stable/release channel:1765

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@abbradar @kira64xyz @IvarWithoutBones 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #216745: Update request: citra-canary 2146 → 2399
- Package name: citra-canary
- Latest released version: 2399

- Current version on the unstable channel: 2146
- Current version on the stable/release channel: 2146

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@abbradar @kira64xyz @IvarWithoutBones 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #225633: citra and yuzu-ea conflict
### Describe the bug
Attempting to install `citra` (3DS Emulator) and `yuzu-ea` (Switch Emulator) at the same time is not currently possible without changing the priority of one of the packages.

 > error: collision between `'/nix/store/80nnwn3v1h5rcwkg06h9mgwcc5y8vrc9-yuzu-ea-2945/share/cmake/tsl-robin-map/tsl-robin-mapTargets.cmake'`and `'/nix/store/zsk1n9q57cg3b3ygd3y7p64h9sakf5m0-citra-nightly-1873/share/cmake/tsl-robin-map/tsl-robin-mapTargets.cmake'`

Correct me if I'm wrong, but shouldn't the cmake files not be included in the final output, for either package?

### Steps To Reproduce
1. Attempt to install both packages side by side

### Expected behavior
They install and work side by side. (They did previously, I'm not sure exactly when that stopped being the case)

### Additional context
I'm installing both via Home Manager, but afaik that shouldn't cause any huge issues.

### Notify maintainers

Both packages seem to be maintained by the same four people:

     ashley / @kira64xyz 
     ivar / @IvarWithoutBones 
     joshuafern / @JoshuaFern 
     sbruder / @sbruder 
     

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.105, NixOS, 22.11 (Raccoon), 22.11.20230409.48dcbaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/40w1i37kf1s1ljj3a22ngi5b66bsd225-source`
```

### PR DESCRIPTION
**Pull request by lasers**
###### Description of changes
Bump versions.

Closes https://github.com/NixOS/nixpkgs/issues/216744 `via #224337`.
Closes https://github.com/NixOS/nixpkgs/issues/216745 `via #224337`.
Closes https://github.com/NixOS/nixpkgs/issues/225633 `(no cmake stuff)`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dixslyf — APPROVED** [review]
Result of `nixpkgs-review pr 225744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>citra-canary</li>
    <li>citra-nightly</li>
  </ul>
</details>

**Comment by PlayerNameHere** [comment]
Result of `nixpkgs-review pr 225744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>citra-canary</li>
    <li>citra-nightly</li>
  </ul>
</details>

**Comment by lasers** [comment]
Weird thing. I can't compile canary 2475. OK. Now, I can't compile 2474 too (one release behind, successfully built). I keep nightly at latest (successfully built) while leaving canary few releases behind.

**Comment by PlayerNameHere** [comment]
Result of `nixpkgs-review pr 225744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>citra-canary</li>
    <li>citra-nightly</li>
  </ul>
</details>

I'm getting a hash mismatch on `compat-list`.

```
error: hash mismatch in fixed-output derivation '/nix/store/a2gm2xgfjp874cnlvkvh9rzbxafjv11v-citra-compat-list.drv':
         specified: sha256-qQkFRlIQcXToKShWilwNLR0AcENyTf073hTfvj9RNeQ=
            got:    sha256-J+zqtWde5NgK2QROvGewtXGRAWUTNSKHNMG6iu9m1fU=
error: 1 dependencies of derivation '/nix/store/zvwm0hz1xypwf79d2iycpmrd82lamlih-citra-canary-2478.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cynwnjvvwy6ga8n7rmppan1l63kqyv27-citra-nightly-1902.drv' failed to build
error: 2 dependencies of derivation '/nix/store/ziirff01zbxcqxrhcrbbc46maakrbrzh-review-shell.drv' failed to build
```

**Comment by PlayerNameHere** [comment]
@ofborg build citra-nightly citra-canary

**Comment by lasers** [comment]
Same `compat-list`, new hash. Who dis?
```
trying https://web.archive.org/web/20230428030454/https://api.citra-emu.org/gamedb/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
remote: Enumerating objects: 2046, done.
remote: Counting objects: 100% (2046/2046), done.
100 13356    0 13356    0     0  36446      0 --:--:-- --:--:-- --:--:-- 36392
error: hash mismatch in fixed-output derivation '/nix/store/7frsxj6gr92mala5zymmzzs5xx5fpacl-citra-compat-list.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-iOMzlvQznLTFdo6MqL60N0ON6HlrWZEe1srWtYLi5m4=
```

**Comment by PlayerNameHere** [comment]
@ofborg build citra-nightly citra-canary

**Comment by PlayerNameHere** [comment]
Result of `nixpkgs-review pr 225744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>citra-canary</li>
    <li>citra-nightly</li>
  </ul>
</details>

```
error: hash mismatch in fixed-output derivation '/nix/store/lvd0m2a9r00rgw0nmwzwbgq5ybx3dh4m-citra-compat-list.drv':
         specified: sha256-iOMzlvQznLTFdo6MqL60N0ON6HlrWZEe1srWtYLi5m4=
            got:    sha256-J+zqtWde5NgK2QROvGewtXGRAWUTNSKHNMG6iu9m1fU=
error: 1 dependencies of derivation '/nix/store/968jpqmm9rrnhs1g1ll2hrdaqd7qyz0g-citra-canary-2479.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ppb1pczc2qc13638xaxclq6mk2kw282c-citra-nightly-1903.drv' failed to build
error: 2 dependencies of derivation '/nix/store/hcmqhlmawrjj05f5rmajj6r3v1jq456z-review-shell.drv' failed to build
```

I'm still getting a hash mismatch, but I got the same hash as my build attempt from yesterday. [ofborg's build](https://logs.ofborg.org/?key=nixos/nixpkgs.225744&attempt_id=f827c8ab-e76d-4315-83bd-e9aa45a21b00) is getting this hash as well.

How are you building it on your end?

**Comment by lasers** [comment]
>How are you building it on your end?

I follow the documentation. Basically, I go in `nixpkgs` folder and do `nix-build -A <pkg>`. I assume it had nothing to do with my end because this is related to `compat-list`. I try a new snapshot. Never ran into this issue with hash changing before.

**Comment by PlayerNameHere** [comment]
@ofborg build citra-nightly citra-canary

**Comment by PlayerNameHere** [comment]
Result of `nixpkgs-review pr 225744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>citra-canary</li>
    <li>citra-nightly</li>
  </ul>
</details>

> Never ran into this issue with hash changing before.

Same. Strange issue, but it builds successfully now, so I guess all's well that ends well.

**Comment by lasers** [comment]
This should get reviewed and merged. The next citra versions will need to be looked at again... due to new vulkan backend support (currently in canary and eventually nightly) and possibly other stuff.

**Comment by PlayerNameHere** [comment]
Result of `nixpkgs-review pr 225744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>citra-canary</li>
    <li>citra-nightly</li>
  </ul>
</details>

@ofborg build citra-nightly citra-canary

**Comment by PlayerNameHere** [comment]
> This should get reviewed and merged. The next citra versions will need to be looked at again... due to new vulkan backend support (currently in canary and eventually nightly) and possibly other stuff.

Agreed.

Friendly ping @abbradar @IvarWithoutBones @kira64xyz

**Comment by lasers** [comment]
Friendly ping @NickCao

**Pull request merged**
