### PR TITLE
zrythm: 1.0.0-alpha.26.0.13 -> 1.0.0-alpha.28.1.3

### PR DESCRIPTION
**Pull request by magnetophon**
###### Motivation for this change

Note: this PR neds https://github.com/NixOS/nixpkgs/pull/146864 to be merged first.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tshaynik — COMMENTED** [review]
I'm trying to build from this PR and I'm getting this error:

```
A full log can be found at /build/source/build/meson-logs/meson-log.txt
error: builder for '/nix/store/gxj2mr16wzp09r9kjfwcimm6bvsi6s0g-zrythm-1.0.0-alpha.28.1.3.drv' failed with exit code 1;
       last 10 log lines:
       > Program /nix/store/hh9wkdk2q8grgfgn42iwss1yq4mf73g3-carla-2.4.1/lib/carla/carla-bridge-lv2-x11 found: YES (/nix/store/hh9wkdk2q8grgfgn42iwss1yq4mf73g3-carla-2.4.1/lib/carla/carla-bridge-lv2-x11)
       > Checking for function "carla_get_native_patchbay_cv8_plugin" with dependency carla-host-plugin: NO
       > Checking for function "carla_get_audio_port_hints" with dependency carla-host-plugin: NO
       > Dependency rtmidi found: NO found 4.0.0 but need: '>= 5.0.0'
       > Run-time dependency rtmidi found: NO (tried pkgconfig and cmake)
       > Looking for a fallback subproject for the dependency rtmidi
       >
       > meson.build:1151:0: ERROR: Automatic wrap-based subproject downloading is disabled
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/gxj2mr16wzp09r9kjfwcimm6bvsi6s0g-zrythm-1.0.0-alpha.28.1.3.drv'.
 ```
 
 I guess we should try to bump rtmidi to 5.0.0 in nixpkgs before we can merge this.

**Comment by magnetophon** [comment]
@tshaynik 

> I guess we should try to bump rtmidi to 5.0.0 in nixpkgs before we can merge this.

Yes, as mentioned in the first comment:  "Note: this PR needs #146864 to be merged first."    :)

**Comment by tshaynik** [comment]
> @tshaynik
> 
> > I guess we should try to bump rtmidi to 5.0.0 in nixpkgs before we can merge this.
> 
> Yes, as mentioned in the first comment: "Note: this PR needs #146864 to be merged first." :)

Sorry about that! I missed it.

**Comment by tshaynik** [comment]
I saw that #146864 has been merged, and building and running this PR rebased onto nixpkgs/master worked great for me.
I think this is change can be merged.

**Comment by Artturin** [comment]
@ofborg eval

**Review by tshaynik — APPROVED** [review]

**Pull request merged**
