### PR TITLE
python3Packages.lark: 1.0.0 -> 1.1.2

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Review by cpcloud — APPROVED** [review]
Seems reasonable!

**Comment by drewrisinger** [comment]
I left it as draft b/c I found some downstream build errors, and was trying to fix those. Haven't run a full nix-review.

**Comment by jonringer** [comment]
for the kaldi packages, we should really upsteam some options to not follow their VCS-based dependency management.

**Comment by drewrisinger** [comment]
> for the kaldi packages, we should really upsteam some options to not follow their VCS-based dependency management.

I don't have the time or interest to do that currently. Pinging maintainer @ckiee

**Comment by drewrisinger** [comment]
No changes, just squashed commits.

**Comment by ckiee** [comment]
I have been summoned! FYI there's already someone who was working on fixing the build but didn't open a PR. (I'd ping them but I don't know their GH handle)

> for the kaldi packages, we should really upstream some options to not follow their VCS-based dependency management.

I suffered so much while hacking that mess (sorry daanzu!) into working order. I do not want to touch their mess of a build system ever again.

..but it'd be nice.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 162429` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
37 packages built:
</summary>
<ul>
<li>ansible (python39Packages.ansible-core)</li>
<li>ansible_2_11</li>
<li>charliecloud</li>
<li>home-assistant-component-tests.homekit_controller</li>
<li>pdm</li>
<li>python310Packages.aiohomekit</li>
<li>python310Packages.ansible-core</li>
<li>python310Packages.cassandra-driver</li>
<li>python310Packages.cirq</li>
<li>python310Packages.cirq-rigetti</li>
<li>python310Packages.commentjson</li>
<li>python310Packages.dragonfly</li>
<li>python310Packages.flake8-bugbear</li>
<li>python310Packages.gdtoolkit</li>
<li>python310Packages.gremlinpython</li>
<li>python310Packages.hypothesmith</li>
<li>python310Packages.kaldi-active-grammar</li>
<li>python310Packages.lark</li>
<li>python310Packages.pyquil</li>
<li>python310Packages.radish-bdd</li>
<li>python310Packages.resolvelib</li>
<li>python39Packages.aiohomekit</li>
<li>python39Packages.cassandra-driver</li>
<li>python39Packages.cirq</li>
<li>python39Packages.cirq-rigetti</li>
<li>python39Packages.commentjson</li>
<li>python39Packages.dragonfly</li>
<li>python39Packages.flake8-bugbear</li>
<li>python39Packages.gdtoolkit</li>
<li>python39Packages.gremlinpython</li>
<li>python39Packages.hypothesmith</li>
<li>python39Packages.kaldi-active-grammar</li>
<li>python39Packages.lark</li>
<li>python39Packages.pyquil</li>
<li>python39Packages.radish-bdd</li>
<li>python39Packages.resolvelib</li>
<li>terraform-compliance</li>
</ul>
</details>

**Pull request merged**
