### PR TITLE
conan: 1.27.0 -> 1.35.0

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Version bump. I don't have any of the history on this package so I wrote this PR with a completely green (fresh?) set of eyes. Please let me know if I'm doing something terrible wrong!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118702` at 3a6c4072 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>conan</li>
  </ul>
</details>
<details>
  <summary>6 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'cryptography>=1.3.4, <2.4.0' doesn't match anything in file 'conans/requirements.txt'
Near pkgs/development/tools/build-managers/conan/default.nix:101:0:
```
    |
101 |     description = "Decentralized and portable C/C++ package manager";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'PyYAML>=3.11, <3.14.0' doesn't match anything in file 'conans/requirements.txt'
Near pkgs/development/tools/build-managers/conan/default.nix:101:0:
```
    |
101 |     description = "Decentralized and portable C/C++ package manager";
    | ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/development/tools/build-managers/conan/default.nix:1:59:
```
  |
1 | { lib, stdenv, python3, fetchFromGitHub, git, pkg-config, fetchpatch }:
  |                                                           ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'pyOpenSSL>=16.0.0, <19.0.0' doesn't match anything in file 'conans/requirements.txt'
Near pkgs/development/tools/build-managers/conan/default.nix:101:0:
```
    |
101 |     description = "Decentralized and portable C/C++ package manager";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'idna==2.6' doesn't match anything in file 'conans/requirements.txt'
Near pkgs/development/tools/build-managers/conan/default.nix:101:0:
```
    |
101 |     description = "Decentralized and portable C/C++ package manager";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'six>=1.10.0,<=1.14.0' doesn't match anything in file 'conans/requirements.txt'
Near pkgs/development/tools/build-managers/conan/default.nix:101:0:
```
    |
101 |     description = "Decentralized and portable C/C++ package manager";
    | ^
```
</li>
  </ul>
</details>

**Comment by aanderse** [comment]
What a wonderful bot. I took a deeper dive, reviewing, researching, and applying the suggestions, followed by another round of testing.

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds via ``nix-review`` on x86-64-linux

```
1 package built:
conan
```

**Review by marsam — APPROVED** [review]
LGTM

**Review by HaoZeke — APPROVED** [review]
LGTM, this was written in a sloppy manner previously, thanks @aanderse !

**Comment by aanderse** [comment]
Thanks everyone!

**Pull request merged**
