### PR TITLE
scorecard: add developer-guy to maintainers list

### PR DESCRIPTION
**Pull request by developer-guy**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I made several contributions to scorecard project here is the list of my contributions:

> https://github.com/ossf/scorecard/pulls?q=author%3Adeveloper-guy+sort%3Aupdated-desc

I've added myself to the maintainers list of the scorecard package, I'd love love help to maintain that package.

PTAL @06kellyjac

### CODE REVIEW

**Comment by bobby285271** [comment]
You probably want to find the correct github handle in [`maintainers/maintainer-list.nix`](https://github.com/NixOS/nixpkgs/blob/b453fb34c23ccf8b8f366990d7357a9ae065988c/maintainers/maintainer-list.nix#L7106-L7112) btw :-)

**Comment by developer-guy** [comment]
thank you so much for the suggestion, it seems so cool!

**Comment by 06kellyjac** [comment]
Also the link uses `@me` so for me it just shows [my PRs](https://github.com/ossf/scorecard/pulls?q=author%3A06kellyjac) rather than yours :sweat_smile: 

https://github.com/ossf/scorecard/pulls?q=author%3Adeveloper-guy

**Comment by developer-guy** [comment]
> Also the link uses `@me` so for me it just shows [my PRs](https://github.com/ossf/scorecard/pulls?q=author%3A06kellyjac+sort%3Aupdated-desc) rather than yours 😅
> 
> [ossf/scorecard/pulls (author:developer-guy)](https://github.com/ossf/scorecard/pulls?q=author%3Adeveloper-guy+sort%3Aupdated-desc)

my bad 🤦 I fixed it, thanks for the warning 😅

**Pull request merged**
