### PR TITLE
elm.elmPackages: Update elm-analyse and node2nix

### PR DESCRIPTION
**Pull request by turboMaCk**
###### Motivation for this change
Newer node2nix has fix for the issue that prevented latest `elm-analyse` version to be installed. 

###### Things done
1. Remove version constrain for `elm-analyse`
2. run `./generate-node-packages.sh`

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @svanderburg

**Comment by turboMaCk** [comment]
is there something I should do to increase probability of this being merged? I have no problem with investing more time to this.

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages.elm-analyse

**Comment by turboMaCk** [comment]
thanks!

**Pull request merged**
