### PR TITLE
rocprim: init at 2.11.0-5.3.1

### PR DESCRIPTION
**Pull request by Madouura**
###### Description of changes
Tracking: #197885
First part in a whole bunch of porting...
``rocprim.passthru.tests`` will likely always fail due to it being in a vm, but I have confirmed the tests generated do work on hardware.
Depends on  #197838

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Madouura** [comment]
Cleaned up some things.

**Comment by Madouura** [comment]
Now depends on  #197838

**Comment by Flakebi** [comment]
Sorry, I didn’t have much time yet to look at all the PRs, I hope I get more time next week.

One thing, that I was missing for a long time is running tests for gpu packages (ROCm, amdvlk, etc.). As you noted, using the nixos test framework doesn’t work, because the VM can’t access GPUs.

However, we can also run tests outside a VM and make hardware accessible to derivations with `--option extra-sandbox-paths '/sys'`.

Here’s an example for a simple OpenCL test. I guess it would benefit from pulling part of that out into a “framework” like `make-test-python.nix`.
The test can be run with `sudo nix-build --option extra-sandbox-paths '/sys' nixos/tests/rocm-opencl.nix`.
```nix
{
  system ? builtins.currentSystem,
  pkgs ? import ../.. { inherit system; },
  ...
} @ args:
let
  lib = pkgs.lib;
in
pkgs.stdenv.mkDerivation {
  # name = "test-run-${config.name}";
  name = "test-run-rocm-opencl";

  requiredSystemFeatures = [ "nixos-test" ];

  # TODO Use callPackage so we can take packages as arguments?
  nativeBuildInputs = with pkgs; [ clinfo ];

  OCL_ICD_VENDORS = "${pkgs.rocm-opencl-icd}/etc/OpenCL/vendors/";

  # TODO Testing graphics drivers also needs /dev/dri, so make this configurable?
  buildCommand = ''
    mkdir -p $out

    if [[ ! -e /sys ]]; then
      echo 'Run this test as *root* with `--option extra-sandbox-paths '/sys'` and a GPU'
      exit 1
    fi

    # Run test
    # Test fails if the number of platforms is 0
    clinfo | grep -E 'Number of platforms * [1-9]'
  '';

  # passthru = config.passthru;

  meta = with lib.maintainers; {
    maintainers = [ Flakebi ];
  };
}
```

**Comment by Madouura** [comment]
@Flakebi That's gonna take some doing, and may be better suited to a bigger PR concerning rocm packages.
Should we just remove the nixosTests commits for now and later on try that?

**Comment by Flakebi** [comment]
> Should we just remove the nixosTests commits for now and later on try that?

Yes, that sounds good to me.

**Comment by Madouura** [comment]
Rolled into #198770

**Pull request closed without merging**
