### PR TITLE
graalvm-ce: 21.2.0 -> 21.3.0

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

- Drop graalvm8 since it was removed by upstream
- Add update.sh script to make it easier to generate hashes for all   platforms
- Fix GraalPython, broken since #141825 (sorry)
- Small refactorings and fixes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
Code-wise LGTM

**Review by babariviere — APPROVED** [review]

**Review by glittershark — APPROVED** [review]

**Comment by glittershark** [comment]
Tested build on linux and that also LGTM

**Review by glittershark — APPROVED** [review]
x86_64-darwin builds and LGTM too - checked graalvm11-ce and babashka

**Comment by thiagokokada** [comment]
I just realized that the `update.sh` script may generate unnecessary downloads of big chunks of tarballs because it doesn't check first if there is an update.

Let me fix this first.

**Comment by thiagokokada** [comment]
> I just realized that the `update.sh` script may generate unnecessary downloads of big chunks of tarballs because it doesn't check first if there is an update.
> 
> Let me fix this first.

Fixed.

**Pull request merged**
