### PR TITLE
kbd: 2.0.3 -> 2.0.4

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Resuming PR #22793:
The unicode_{start,stop} scripts fail due to a hardcoded path.
I patched that and also updated the package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using (nope, it's a mass rebuild)
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @grahamc @therealpxc @matthiasbeyer @pSub

### CODE REVIEW

**Comment by grahamc** [comment]
LGTM but I don't feel especially qualified to review this.

**Comment by abbradar** [comment]
Tested this on a local VM; works fine. Thank you!

**Comment by FRidh** [comment]
There's a test failure: 
```
substitute(): ERROR: Invalid command line argument: /nix/store/8f42syfzv3cpw3jjq96sdzvnclivi783-kbd-2.0.4/bin/unicode_stop
```
Check staging.

**Comment by FRidh** [comment]
Reverted it for now 00bf3a9dcaffedc4eaf244848a2a3f84e648bdba.

**Comment by therealpxc** [comment]
That's weird. What kind of test is this? The `unicode_start` and `unicode_stop` scripts never worked before. Is this problem from the `substituteInPlace` command, or an error when running the scripts?

**Comment by FRidh** [comment]
Here is the log:
https://nix-cache.s3.amazonaws.com/log/0vnj58ifhc8b4kpkaq777a7ahp1mcsb8-kbd-2.0.4.drv

It fails in the tests:
```
Making install in tests
make[1]: Entering directory '/build/kbd-2.0.4/tests'
make[2]: Entering directory '/build/kbd-2.0.4/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/build/kbd-2.0.4/tests'
make[1]: Leaving directory '/build/kbd-2.0.4/tests'
make[1]: Entering directory '/build/kbd-2.0.4'
make[2]: Entering directory '/build/kbd-2.0.4'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/build/kbd-2.0.4'
make[1]: Leaving directory '/build/kbd-2.0.4'
substitute(): ERROR: Invalid command line argument: /nix/store/8f42syfzv3cpw3jjq96sdzvnclivi783-kbd-2.0.4/bin/unicode_stop
builder for ‘/nix/store/0vnj58ifhc8b4kpkaq777a7ahp1mcsb8-kbd-2.0.4.drv’ failed with exit code 1
```

**Comment by abbradar** [comment]
Fixed by 69e24c044aba1c0a3dc4e70d0f988ec1f3e6fb73

**Pull request merged**
