### PR TITLE
cointop: unstable -> 1.2.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

**This errors on startup** - I'm not sure why the app crashes on startup. I will file a bug upstream in a few moments.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Bug filed in https://github.com/miguelmota/cointop/issues/32

**Comment by JohnAZoidberg** [comment]
Works for me. What's your error?

**Comment by matthiasbeyer** [comment]
See the issue description in miguelmota/cointop#32

**Comment by JohnAZoidberg** [comment]
I don't really see one. I just see their place holder text. Or am I missing something?

**Comment by matthiasbeyer** [comment]
oh, I don't know why the paste went wrong. Damn.

**Review by tomberek — APPROVED** [review]
Builds, runs, functions on Ubuntu. No reverse dependencies.

**Comment by marsam** [comment]
I took the liberty to update it to [`buildGoModule`](https://nixos.org/nixpkgs/manual/#ssec-go-modules). I hope you don't mind.

**Pull request merged**
