### PR TITLE
pithos: add gdk-pixbuf2.0 dependency, update maintainers

### PR DESCRIPTION
**Pull request by zaporter**
###### Description of changes

This updates pithos to use gdk-pixbuf2.0. Without this package, pithos crashes when trying to load album art (on x11 and wayland). This commit also sets myself as the maintainer. I reached out to the previous maintainer (obadz) over email and he says that he has not used pithos in around 5 years and that the package also crashes on his system. I am a big fan of the pithos project and would be interested in helping to maintain this package.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zaporter** [comment]
Does anyone know why the ofborg-eval failed? I am having trouble understanding the error message. Multiple other packages import python3Packages. Thanks in advance!

**Comment by cole-h** [comment]
It's because `pythonPackages` was set to `python3Packages` in `all-packages.nix`: https://github.com/NixOS/nixpkgs/blob/4c5c82e9cdb35494ae243ffe42f156269904d457/pkgs/top-level/all-packages.nix#L32374

If you remove that line from `all-packages.nix`, ofborg-eval will succeed.

**Comment by bobby285271** [comment]
Hmmm, probably you also need to add yourself to `maintainers/maintainer-list.nix` file ([as a separate commit](https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers) `maintainers: add zaporter`, just push the commit in this PR) .

Why adding `rubyPackages.gdk_pixbuf2` to a python application? Did you try just adding `gdk-pixbuf` (which is propagated by the former)?

**Comment by zaporter** [comment]
Ahh, sorry! For some reason I missed that part of the documentation. Will do.

Also, I am using the ruby version because the normal one doesn't work. I have spent a fair bit of time digging into this and I've realized that pithos doesn't need rubyPackages.gdk_pixbuf, but its dependency, rubyPackages.gio2.

This led me to look into using the nixpkgs.glib package because that builds gio, however that doesn't work. At this point, I suspect it is because the ruby gio2 package exports the linkable libraries whereas the nixpkgs.glib package doesn't seem to export gio2.so. I will be looking into this more. Right now I am considering three options:
1) Update the nixpkgs.glib package to include an option to export the gio (and possibly other .so files) so that nixpkgs.pithos can just rely on that.
2) Create nixpkgs.gio after I rip apart the ruby module and convert it to a nix package
3) Just keep the ruby import 

Unless anyone else has any advice, I will probably look into moving forward with option 2. 


Thank everyone for you help! I really appreciate it.

**Pull request closed without merging**
