### PR TITLE
perlPackages.CompressRawZlib: 2.101 -> 2.103

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/pmqs/Compress-Raw-Zlib/releases/tag/v2.103

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg build hydra-unstable

**Comment by mweinelt** [comment]
And we're back to the C++ build error. I think this works.

**Comment by wamserma** [comment]
for some reason upstream skipped  2.102, but the changelog is very short - LGTM

**Review by vcunat — APPROVED** [review]
The upstream commits look OK.

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.CompressRawZlib

**Comment by stigtsp** [comment]
The bundled zlib for this module contains a patch to deal with crc errors. Should we consider https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 in our `zlib` as well?

**Comment by mweinelt** [comment]
Actually, there is no reason for this to go through staging-next. Rebasing onto master.

**Comment by mweinelt** [comment]
> The bundled zlib for this module contains a patch to deal with crc errors. Should we consider https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 in our `zlib` as well?

I'm not sure how we want to progreaa with staging-next, but another patch would throw us back quite a bit, so I have to wonder if that is worth it, or if we can address this with the next staging-next.

**Comment by vcunat** [comment]
I haven't noticed any regressions on Hydra from that on 21.11.

**Comment by vcunat** [comment]
https://hydra.nixos.org/eval/1752919?compare=1752194#tabs-now-fail

**Comment by wamserma** [comment]
Result of `nixpkgs-review pr 167080` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>odpdown</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>hydra-unstable</li>
    <li>python310Packages.paperwork-backend</li>
    <li>python310Packages.paperwork-shell</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>jpsxdec</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>paperwork</li>
    <li>perl532Packages.CompressRawZlib</li>
    <li>perl532Packages.IOCompress (perl532Packages.CompressZlib)</li>
    <li>perl534Packages.CompressRawZlib</li>
    <li>perl534Packages.IOCompress (perl534Packages.CompressZlib)</li>
    <li>python39Packages.paperwork-backend</li>
    <li>python39Packages.paperwork-shell</li>
    <li>unoconv</li>
  </ul>
</details>

**Pull request merged**
