### PR TITLE
grsecurity_testing: 4.7.10 -> 4.8.7

### PR DESCRIPTION
**Pull request by spacekitteh**
Works for me, assuming I manually set boot.kernelPackages = pkgs.linuxPackages_latest;
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by spacekitteh** [comment]
@grahamc security (also it's good to merge)

**Comment by joachifm** [comment]
Note that this breaks all grsec packages ...

**Comment by spacekitteh** [comment]
@joachifm can you elaborate?

**Comment by joachifm** [comment]
See https://hydra.nixos.org/eval/1303671

**Comment by spacekitteh** [comment]
@joachifm those builds were failing from the previous commit, though? https://hydra.nixos.org/eval/1303645

**Comment by joachifm** [comment]
I'm referring to the fact that there are *no* grsec packages in the eval I linked, they've all been removed.

**Comment by spacekitteh** [comment]
What does being removed mean?

**Comment by joachifm** [comment]
No longer built.

**Comment by spacekitteh** [comment]
Why are they no longer built? Poking around the hydra page I can't see any reason for it

**Comment by joachifm** [comment]
The patch needs to be updated in tandem with the kernel it applies to.

I have an update pending, but it appears the mirror is serving a different file than upstream, so I won't push until I figure out why that is.

**Pull request merged**
