### PR TITLE
kmail: init at 17.04.0

### PR DESCRIPTION
**Pull request by vandenoever**
###### Motivation for this change

Package kdepim for kde-5.

This PR replaces https://github.com/NixOS/nixpkgs/pull/20531

Most executables work except kmail, kontact. blogilo and akregator.
These problems seem all due to QtWebEngine.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vandenoever** [comment]
@viric, @ttuegel and @zraexy: please try this patch and see if it works for you.
It does not work well for me and I've exhausted my time on this PR for now.

**Comment by ttuegel** [comment]
KMail starts for me, but I still have problems with Akonadi. I'm blocked on #20585 at the moment.

One thing to note: because Akonadi registers a D-Bus service, it will not work correctly unless installed into the user or system environment, i.e. kdepim applications cannot be run from the store.

**Comment by vandenoever** [comment]
I've done my testing with `nix-env -f. -i kde5.kdepim` which if I understand correctly should be fine.

I'm also seeing that mariadb error (#20585) when first starting akonadi (via kmail). Some akonadi functionality like storing calendar items (korganizer), addresses (kaddressbook) and notes (knotes) works fine.

On my normal install kmail starts but shows no messages. On a clean desktop, kmail crashes on startup (but the initial config dialog does show).

**Comment by vandenoever** [comment]
If i install kde5.kdepim and kde5.kdepim-runtime, I can create a maildir agent in akonadiconsole. Mail that are copied in that directory are picked up. So that part seems to work.

Starting the gui for kmai, akregator or kontact still does not work.

**Comment by vandenoever** [comment]
It seems QtWebEngine is not properly installed. It is not in `/nix/store/<HASH>-qt-5.6.1-1/lib/`.

**Comment by vandenoever** [comment]
> It seems QtWebEngine is not properly installed. It is not in /nix/store/<HASH>-qt-5.6.1-1/lib/.

which is fixed by https://github.com/NixOS/nixpkgs/pull/20569

**Comment by vandenoever** [comment]
kmail, akregator and kontact all crash in [the same line in grantleethemes](https://cgit.kde.org/grantleetheme.git/tree/src/grantleetheme.cpp?h=v16.08.3#n217).

**Comment by vandenoever** [comment]
This PR depends on https://github.com/NixOS/nixpkgs/pull/20569

**Comment by vandenoever** [comment]
Cleaned up the PR.

**Comment by grahamc** [comment]
What is the status here?

**Comment by vandenoever** [comment]
It builds for me with master. Yet on my machine kmail does not run. I believe the situation might be better for @ttuegel .
It seems I'll have to make debug build to figure out the problem for my situation. Due to the large number of packages, that does not seem an easy endeavor.

**Comment by lprndn** [comment]
Is there some news on that project?

**Comment by vandenoever** [comment]
No, I've not looked at it for a while. The packages have been reshuffled since the last work on this.
I'm still on KMail 1 for now.

**Comment by vandenoever** [comment]
Now that 17.03 has plasma5 this has higher urgency, I guess.

**Comment by vandenoever** [comment]
Now that 17.03 has plasma5 this has higher urgency, I guess. especially since kmail seems to be gone from 17.03.

**Comment by vandenoever** [comment]
messagelib in applications 16.12.3 still requires WebKitWidgets

https://cgit.kde.org/messagelib.git/tree/CMakeLists.txt?h=v16.12.3

This requirement is gone in v17.03.80.

**Comment by vandenoever** [comment]
@grahamc @lprndn @ttuegel 
This patch is now updated to work with NixOS 17.03.

**Comment by vandenoever** [comment]
starting kmail in a clean nixos 17.03 gives this:
```
ERROR: Caught a segmentation fault while loading plugin file:
/nix/store/zz6zv5kq75h2d0ma7xg452wm1wbx7llx-gst-plugins-base-1.10.4//lib/gstreamer-1.0/libgsttypefindfunctions.so
```

**Comment by vandenoever** [comment]
The current version can run kaddressbook, but kmail, kontact and akregator crash on startup.

**Comment by vandenoever** [comment]
@ttuegel  do you have an opinion on the patch set as it is now?

**Comment by ttuegel** [comment]
The only comments I have are:

1. Try to remove extraneous imports like `kdeWrapper` (which is not needed for the libraries).
1. Please add the libraries to the list in [all-packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L9531).

**Comment by vandenoever** [comment]
With the patch to avoid a crash in Grantlee, KMail does not crash, but it does terminate with an error.

```bash
$ kmail
org.kde.pim.kidentitymanagement: IdentityManager: There was no default identity. Marking first one as default.
sonnet.core: No language dictionaries for the language: "en"
sonnet.core: deleting 0x1ecdef0 for "en"
sonnet.core: Unhandled script 126
sonnet.core: Unhandled script 127
sonnet.core: Unhandled script 128
sonnet.core: Unhandled script 129
sonnet.core: Unhandled script 130
sonnet.core: No language dictionaries for the language: "en"
sonnet.core: No language dictionaries for the language: "en"
sonnet.core: No language dictionaries for the language: "en"
sonnet.core: No language dictionaries for the language: "en"
sonnet.core: deleting 0x2136b30 for "en"
sonnet.core: deleting 0x2136968 for "en"
sonnet.core: No language dictionaries for the language: "en"
sonnet.ui: No dictionary for " "en" " staying with the current language.
sonnet.core: No language dictionaries for the language: "en"
this does not work on a KActionCollection containing actions!
org.kde.akonadi.ETM: GEN true false false
org.kde.akonadi.ETM: collection: QVector()
org.kde.akonadi.ETM: 
grantlee.template: "Plugin library 'kde_grantlee_plugin' not found."
org.kde.akonadi.ETM: Subtree:  4 QSet(14, 13, 12, 11, 6, 5, 4)
org.kde.akonadi.ETM: Fetch job took  264 msec
org.kde.akonadi.ETM: was collection fetch job: collections: 7
org.kde.akonadi.ETM: first fetched collection: "Local Folders"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.akonadi.ETM: collection: QVector()
org.kde.akonadi.ETM: Fetch job took  499 msec
org.kde.akonadi.ETM: was collection fetch job: collections: 6
org.kde.akonadi.ETM: first fetched collection: "Search"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.akonadi.ETM: Fetch job took  44 msec
org.kde.akonadi.ETM: was collection fetch job: collections: 0
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.akonadicore: "Unable to obtain agent type ''."
org.kde.pim.akonadicore: Failed SpecialCollectionsRequestJob::slotResult "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
org.kde.pim.mailcommon: "The Email program encountered a fatal error and will terminate now.\nThe error was:\nUnable to obtain agent type ''."
org.kde.pim.akonadicore: Failed to request resource "" : "Cannot connect to the Akonadi service. (Unable to obtain agent type ''.)"
sonnet.core: Removing loader:  Sonnet::Loader(0x7fee1bd65190)
```
A dialog shows this message:

```
The Email program encountered a fatal error and will terminate now.
The error was:
Unable to obtain agent type ''.
```

**Comment by vandenoever** [comment]
Updated to 17.04.0 but still crashing kmail on startup when running in NixOS 17.03.

**Comment by ttuegel** [comment]
The crash is at least in part due to Akonadi trying to compare timestamps to a file in the Nix store; of course that isn't going to be helpful! I'm trying to patch around it now.

**Comment by ttuegel** [comment]
KMail is working on my [branch](https://github.com/ttuegel/nixpkgs/tree/kde-applications), but I haven't had a chance to look at the rest of the PIM suite yet.

**Comment by vandenoever** [comment]
@ttuegel I'm looking forward to trying your branch tomorrow

**Comment by vandenoever** [comment]
@ttuegel how should one install kmail at the moment? I'm testing on a system with no system-wide kde, but a different desktop and run `nix-env -f. -i kmail`.

**Comment by ttuegel** [comment]
@vandenoever It should work with `nix-env -i`. It does depend on some KDE services, but those should be automatically installed by `nix-env`. You may need to run `akonadictl start` before `kmail`; it can start Akonadi itself, but I noticed that the first-run wizard gets confused if KMail has to start Akonadi.

**Comment by vandenoever** [comment]
kmail runs and does not crash as easily. (I can make it crash by doing 'Save as draft' on a mail when no account is set up.)

An issue is that no icons are visible except two envelopes in the 'Help' menu. Installing oxygen-icons5 does not help, not even when it is followed by `kbuildsycoca5`.

**Comment by ttuegel** [comment]
> I can make it crash by doing 'Save as draft' on a mail when no account is set up.

That may--or may not--be a packaging problem. The KDE PIM team *really* loves null pointers. 😉 

> Installing oxygen-icons5 does not help, not even when it is followed by kbuildsycoca5.

The default icon theme is `breeze-icons`; does it help to install those? It is also possible that Qt is trying to imitate your GTK theme, which seems to be its fallback if KDE is not running.

**Comment by vandenoever** [comment]
Adding `breeze-icons` does not help. I'm not running gtk, but luminence desktop. That is just to see if kmail works fine in a non-kde environment. Normally, I do run kmail under plasma.

I'm now recompiling akonadi with a oxygen-icons5 as a propagated build input.

**Comment by vandenoever** [comment]
Including `oxygen-icons5` with akondi does not solve the icon problem.

I've now tried to run kmail from @ttuegel's branch with stable nixos 17.03. That fails with this error:

```
$ kmail
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "/nix/store/ssk5scyy69zzzwlmbqvp74383vch01if-qtbase-5.8.0/lib/qt5/plugins".

Available platform plugins are: wayland-org.kde.kwin.qpa, minimal, offscreen, xcb, vnc.

Reinstalling the application may fix this problem.
Aborted
```

That's probably caused by the fact that @ttuegel's branch uses Qt 5.8.0 and NixOS 17.0.3 is on Qt 5.6.2.

**Comment by ttuegel** [comment]
> Including oxygen-icons5 with akondi does not solve the icon problem.

Try running with the environment variable `XDG_CURRENT_DESKTOP=KDE`.

> That's probably caused by the fact that @ttuegel's branch uses Qt 5.8.0 and NixOS 17.0.3 is on Qt 5.6.2.

That isn't supposed to happen anymore because the QPA plugin path is hardcoded. I will investigate.

**Comment by vandenoever** [comment]
> Try running with the environment variable XDG_CURRENT_DESKTOP=KDE.
That makes no difference. Still no icons in kmail from your branch.
breeze and oxygen icons are installed, kbuildsycoca5 was run.

**Comment by vandenoever** [comment]
On `nixos-unstable` konsole also does not show icons when not running under plasma. Even with `XDG_CURRENT_DESKTOP=KDE`.

Excerpt from `configuration.nix`:
```
  # Enable the KDE Desktop Environment.
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.lumina.enable = true;
#  services.xserver.displayManager.sddm.enable = true;
#  services.xserver.desktopManager.plasma5.enable = true;
```

```bash
$ nix-env -q
breeze-icons-5.33.0
firefox-52.0.1esr
git-2.12.2
kmail-17.04.0
konsole-17.04.0
oxygen-icons5-5.33.0
pstree-2.39
```

When I install plasma from nixos-unstable, konsole and kmail have icons. They also have the same Qt version.

Account assistant shows triple and double entries.

account_assistant

Nice that it works on unstable. I'm not willing to make that my daily work environment though.

**Comment by ttuegel** [comment]
> On nixos-unstable konsole also does not show icons when not running under plasma. Even with XDG_CURRENT_DESKTOP=KDE.

No icons when Plasma is installed, but not running? Or no icons when Plasma is not installed?

**Comment by vandenoever** [comment]
When plasma is installed and running, icons are visible. Otherwise they are not.

When plasma is installed, but the running desktop is lumina, then kde applications (dolphin, konsole) do not show icons.

**Comment by ttuegel** [comment]
@vandenoever I opened #25762 to track the problem with the icons.

**Comment by ttuegel** [comment]
> I've now tried to run kmail from @ttuegel's branch with stable nixos 17.03. That fails with this error:

The problem of missing platform plugins is something that I fixed in master, but I had to rollback slightly to get Akonadi working, so I need to fine-tune this more.

**Comment by vandenoever** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/28418

**Pull request closed without merging**
