### PR TITLE
sgx-sdk: 2.21 -> 2.23

### PR DESCRIPTION
**Pull request by phlip9**
## Description of changes

Updates the sgx-* package family to the latest 2.23 release. These packages are used (1) by devs to build Intel SGX enclaves and (2) by operators running the NixOS `aesmd` service to easily run enclaves on servers. Intel SGX is a Confidential Computing technology for running enclaves and confidential VMs (Intel TDX) on Intel server CPUs alongside an untrusted hypervisor/Linux/userspace software stack.

These changes were tested on an Azure gen2 VM (DCSv3) running NixOS.

- sgx-sdk/ipp-crypto: 2021.9.0 -> 2021.10.0
  - gcc 13 still failing to compile w/o warnings...
  - Diff: <https://github.com/intel/ipp-crypto/compare/ippcp_2021.9.0...ippcp_2021.10.0>
  - Changelog: <https://github.com/intel/ipp-crypto/blob/ippcp_2021.10.0/CHANGELOG.md>
- sgx-sdk: 2.21 -> 2.23
  - `make preparation` step keeps changing; use a more maintainable .patch
    approach instead of copying over steps from Makefile.
  - Remove stale patch.
  - Add build reproducibility patch for binary-bundled zip files, courtesy of @haraldh <3
  - Diff: <https://github.com/intel/linux-sgx/compare/sgx_2.21...sgx_2.23>
  - Changelog (2.22): <https://github.com/intel/linux-sgx/releases/tag/sgx_2.22>
  - Changelog (2.23): <https://github.com/intel/linux-sgx/releases/tag/sgx_2.23>
- sgx-psw: 2.21 -> 2.23
- sgx-azure-dcap-client: 1.12.1 -> 1.12.3
  - Diff: <https://github.com/microsoft/Azure-DCAP-Client/compare/1.12.1...1.12.3>
- sgx-ssl: 1.1.1u -> 3.0.12
  - Extract tests into separate build-only derivation, since SIM mode tests don't work on non-Intel hardware.
  - Diff: <https://github.com/intel/intel-sgx-ssl/compare/lin_2.21_1.1.1u...3.0_Rev2>
- sgx-sdk: add 'phlip9' as maintainer of sgx packages

For additional context, see also my previous update PR (2.16 -> 2.21): <https://github.com/NixOS/nixpkgs/pull/254845>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by blitz — APPROVED** [review]
Looks very reasonable to me. And with the upside of removing the old OpenSSL dependency this is even sweeter!

**Comment by haraldh** [comment]
Nice! Looks a lot like https://github.com/NixOS/nixpkgs/pull/243098

**Review by haraldh — APPROVED** [review]

**Comment by haraldh** [comment]
Seems like this runs also into https://github.com/NixOS/nixpkgs/pull/243098#issuecomment-1910248447

**Comment by haraldh** [comment]
> On a related note, I don't actually use this `sgx-ssl` package and I'm wondering how people are using this.

Currently I use `sgx-ssl` to build
https://github.com/intel/SGXDataCenterAttestationPrimitives
here: 
https://github.com/haraldh/nixsgx/tree/main/packages/sgx-dcap

As soon, as I cleaned it up, I will upstream `sgx-dcap`

**Comment by phlip9** [comment]
Added a commit that (1) pulls out the tests from `sgx-ssl` into a separate derivation, (2) we only _build_ but not _run_ the tests, since only real Intel HW can run (both SIM and HW!), and (3) added a Intel SGX `HW` test variant like the others.

You can run the tests (only on real Intel hardware) with:

```bash
$ nix run .#sgx-ssl.tests.HW
$ nix run .#sgx-ssl.tests.SIM
```

OfBorg is now finally green on x86_64-linux : ) <https://github.com/NixOS/nixpkgs/pull/283405/checks?check_run_id=21114692010>

**Review by sbellem — COMMENTED** [review]
Looks good!

Ran `nixpkgs-review` on my machine, and all packages were built.
```shell
$ nix run 'nixpkgs#nixpkgs-review' pr 283405
...
4 packages built:
sgx-azure-dcap-client sgx-psw sgx-sdk sgx-ssl
...
```

**Comment by sbellem** [comment]
> ```shell
> $ nix run .#sgx-ssl.tests.SIM
> ```
Tests passed on my machine.

<details>
<summary>Output of nix run .#sgx-ssl.tests.SIM </summary>

```shell
$ nix run .#sgx-ssl.tests.SIM                                                                                                                                                                                 [179/207]
[1/3/12 built, 1/163/165 copied (1224.4/1434.1 MiB), 281.4/327.4 MiB DL] building ipp-crypto-2021.10.0 (configurePhase): -- ASM object forma
token_path: /home/sylvain/enclave.token                                                                                                     
Start tests                                                                                                                                 
{"public":"3082020a0282020100bdaf4e5f1a49323c373442ed2d6c834944901809a16cec2cfa7bef01e7dc85a563af7566966011ae20964c0be83275fe0916905d50022d29dd32ea887e867f9eeb6519eee88ccedd983de985a8c5480c12034abcdd0bc796d56bd4cae6b2e9b42c74a3a9d3d2396ee3e16d3920a5a816
9f5b67e4da618b58f44fb59eae83478506d40e6960c5505ed042c002cca810ad67e3e65e9fbe5243073ac8b0cbeed4c550258c31403ee892520121a62087a9958c17116aee8b6bca18a64afbdb3042133bc65d4421d762a46973096bb882592efac57517ca1c702896d9e24cedbd322893de7236192680f4033168e5a2f3f
612efcc5b51332d918ea94e704bb7cfe2e147e24613475c9a1b38a2fc901d9036bf9fc3b78f8adcc4089f1c20c7e97232e86ccfeb52c9ab3689307ab9d814825ad4f44da38d0011e08d1cca8ea7fa5e72812821fb99f3cb414523af72e6a22c23f8f39bafa0f095e64278cb4f25f53e186f9e4d4c8cff3c1b602cff9f2f57
858226c5abfd018e05fb6c3fb89ea305b5047fec62d8b8d42d29ed2ae76e0fde7ade20845fa4d735da89233e6cd05c53b9b48a9d17dea74b14e1317d27195f69d9ecd7e9e9d306a3293ffdd43229f947a29c6625af98cb71c34d5b2d7dc32b679a40df0a4bbc14984a0d13dffd8f830b78b71fdd6bd4ec0bdfa005c0863ab
8bbe2a292a7acf20871525b6fa55a85122790e4130203010001"}                                                                                                                                                                                                        
{"private":"308209280201000282020100bdaf4e5f1a49323c373442ed2d6c834944901809a16cec2cfa7bef01e7dc85a563af7566966011ae20964c0be83275fe0916905d50022d29dd32ea887e867f9eeb6519eee88ccedd983de985a8c5480c12034abcdd0bc796d56bd4cae6b2e9b42c74a3a9d3d2396ee3e16d392
0a5a8169f5b67e4da618b58f44fb59eae83478506d40e6960c5505ed042c002cca810ad67e3e65e9fbe5243073ac8b0cbeed4c550258c31403ee892520121a62087a9958c17116aee8b6bca18a64afbdb3042133bc65d4421d762a46973096bb882592efac57517ca1c702896d9e24cedbd322893de7236192680f4033168
e5a2f3f612efcc5b51332d918ea94e704bb7cfe2e147e24613475c9a1b38a2fc901d9036bf9fc3b78f8adcc4089f1c20c7e97232e86ccfeb52c9ab3689307ab9d814825ad4f44da38d0011e08d1cca8ea7fa5e72812821fb99f3cb414523af72e6a22c23f8f39bafa0f095e64278cb4f25f53e186f9e4d4c8cff3c1b602cf
f9f2f57858226c5abfd018e05fb6c3fb89ea305b5047fec62d8b8d42d29ed2ae76e0fde7ade20845fa4d735da89233e6cd05c53b9b48a9d17dea74b14e1317d27195f69d9ecd7e9e9d306a3293ffdd43229f947a29c6625af98cb71c34d5b2d7dc32b679a40df0a4bbc14984a0d13dffd8f830b78b71fdd6bd4ec0bdfa005
c0863ab8bbe2a292a7acf20871525b6fa55a85122790e413020301000102820200125054314370f0bc369a41a1f3a247f4b17d760cabfcbfbac1fe683f975ac7be85a6e19f63826802975bdb80c4cce66e7e0323321730f69a55a47e576a5be3037d77b7eec49e1fb4ee677fddeb430ce7396ffeedc82bc47bf0242699e67
73cb02c20a0d29b446f4e210b5947cc3aa24578e252e01a2393d8255272d71cc3490af37352e6e2b47a438539049fe0919376a292b2e1cceb8bb6b4027d70f067a13c61b6165884faedea7ea7644fcd513bd2d8013c29c65948b16cfad53f86d49c748def637eda03991f059d593a00c8f9025bace7d6c1a9483ceaffa365
4908dcc8652a737d7ca5268b28a9c31674cab825f0e81aa2f6dd7df1b7affe9098f125d6ee85885c506ba9e8ba5a20e03187082a4c44461b62f406cb7f309adf510e6cc1a588beef3865527e36c2a8fc952c4c1482194d12229c2913b7d06708f6bc18fe13ee98adcfa89ce17e1f8cbc24ef5b2b325551944f809d7d47038
ddb7020b60fbe7ee2eb4b9a7f5caf34c5d0ceebc9abe41922331aa34a13dadd2398f6f7726bcf1d0bdfa676161eef0306eb7a07deebecd6ab6695ae3943b563eebcca59ecb4aa324b65b1ecfde52c4aa0a6f84eacc8309a2301e2ed9568bec5b3f96b7ceed7faab32d4505ecefb5e95f88fc61aaf4362a03128d2ad43622a
181a0a7e845b3590a014f903d27114deb85e98d86b6ac2d0297d2275ae5030c20c7467597875550282010100f873d87606fcad48e9c51999ea96e25cb80076c20c4c02eb2c0ebdfacc579404db9d9b60a0b7827312323f5d84cb813607021be4a1c9e6d06c485b6c1d3c1dd494d17ccb8e79fb8da0329a4fbc43eda89cce3
39beffb5ae6364d3127ddaa841e28daa26c3b991a8dba14dfec818cf1b99b1b14c868f544e1d6ae8b681ecbc8d6d190e2f3164b3ed39be38a75481004edf288559b9d85ea36136e1d76cabbed35ca5f4b4a9c6681153d4d61fd80f1573df7df8735e79c63fe3c64d231a5e2635fc3c5e7b6a3585a8aa7ab911a2a077b2450
59026c2059653cefbdc888863d5bf4706a8ae4248cef3233d9ccfb476881d90e78740f0430f30b3e59cef021534eb70282010100c3727035b50eb111a7bd3f6a8a79e5fb845031ddfa8db0910f47286c4cc10db38d373aafbbf9cc041aa59fab9c5266edea207486030922de2c538ecbe26e812bd1e57a8579e9f0b07e72e
b5582b40976b187a2fef3561c0600a22159d4f9dedd4cf6ce0c30b3545c730f7121fe8bf865a67d26c31d3dac7b1e93791ec2b9845a92e2d4e98dd423942eb4aca94bd18369f7824c018de66a218e21df453727da5d0517df148837cca213f61473ef8481d29cae20af946346599afaedef9600f150ed29c71c3e19164a0e
8943745b4fd6e6b0560f202bcb450b17140e7c1b27fcd820fa58bbca2253a36453b0d4dc04fe63055153ad5f43321820f5f8c1650ff985028201002b2834598c2d280c9a4eda7b99fc4ba5bf7095306fe2643f658fca005eae77cfc036485f288bb7e5352bf545d1636836725133772b835ecca5828c1ee39525b95f80642
517c2a8a7994430f9d8c213ee4e0ea3785adf5692d6abe1f602d333cfe958d10debec54687a02564346ddacbf88e9d35a5ca0fe2e1c948532b8e6bd245392cf595a6e07a3ca58641cab3fdd1b581dc6811983c183532cb5818505cfd6a0289d7380676dd4baa94e743289b995d210c9f3db1f975efa2ea9346694449ec5eb
02acff02c1f783d89183f1f90ab2ec220a01ae3cd91114b3eab98c57ec3931add0228116da15e65bd6f76f1800362c055063ab5eb55926a38306c3432d510282010023b34ca1d2cfbb3251647527fde1644bfc1035fba91fa687e8b583c1bc876afc48283575122dffc12428eab08b1e5624d1265a827c1d781c0316c437a
3c5b19c927b8b54c43f2232eaf60cdc92c25614333b665f918d42132a9c72e118d1078f7ed67a2ea9daa7e7373133e614bbf68482d3cb77ca68908ff0b6d961f009b90e5e5446b5dead484e71f598b057e40e5015e0dc0750a72cedb22ba7bfd9e252b5b90f72352ae89e5d60ae0b705de8e359d83aca47a820362279f7a9
eca086cd8d8db49ae522c6ac569caf1ffe2a0bbc6269055f3fee1ff41da17a8d66c80316e157acc2f6926690c680b5f4cffcdc80a70fba9a4149ec5943250a29051273c78d0282010100e10e835110996100f73aaaab01cb559ae9bc7ac60489c8fa05bedb77667731f11588bce3a881e017064fbd30e45c9c6cbb87e2990
99a3fde9210511f66ea088cb0b8b58e15081e8bce8a90065f9836010a8ec41bd54ffd08063eeb26d1c665665091b1bd2bbb36d49a8a95888ddd888d5dce4679a57a0c41f84de9ed983a74c3e7d6aab71a946898ee230a017e7fa0f43346e4174d67eb9679f0bd90f7101d7eabdf12596c09c3c356f6d7a5b962f98329eb11
fac7e9998c76826bb88c5562a7cef1bf516dafce949ccb6709c0ca2067f1a5eab21e43418dd46b1b33c64e1f98c82d1546ccff97915cc1b9435c0af2c6ea466f7d72b25de7e22f019fddb05659"}
test rsa_key_gen completed                                     
{"public":"046a598e18717b8a4892e0aa98d7a3cab7eea6c013df97f534e98df4c6f24738c0d982336179f159c8328e98d277a25e67e264c5804699c5d3cfe4efd4b449f9a7e9e064e197cddae8c2d9671aaade0d4932a5850f8ca5f3e77423ef6a83f7757c"}                                              
{"private":"3081a40201010430712bd422ae9f865a282d556245f03299397f3369ab874b6c3c1ae69f479ca741037869ab562a67833ab7e1cd60d52500a00706052b81040022a164036200046a598e18717b8a4892e0aa98d7a3cab7eea6c013df97f534e98df4c6f24738c0d982336179f159c8328e98d277a25e67e26
4c5804699c5d3cfe4efd4b449f9a7e9e064e197cddae8c2d9671aaade0d4932a5850f8ca5f3e77423ef6a83f7757c"}                               
test ec_key_gen completed                                      
test rsa_test completed                                        
     y^2 = x^3 + a*x + b (mod p)                               
A cyclic subgroup:                                             
     point at infinity                                         
combined multiplication ...                                    
 ok                                                            

NIST curve P-224 (optimised implementation):                                                                                                                                                                       
NIST test vectors ...                                                                                    
NIST curve P-256 (optimised implementation):                                                             
NIST test vectors ...                                                                                    
NIST curve P-521 (optimised implementation):                                                             
NIST test vectors ...                                                                                    
Curve secp112r1                                                                                          
Curve secp112r2                                                                                          
Curve secp128r1                                                                                          
Curve secp128r2                                                                                          
Curve secp160k1                                                                                          
Curve secp160r1                                                                                          
Curve secp160r2                                                                                          
Curve secp192k1                                                                                                                                               
Curve secp224k1                                                                                                                                                                                                    
Curve secp224r1                                                                                                                                               
Curve secp256k1                                                                                                                                                                                                    
Curve secp384r1                                                                                                                                               
Curve secp521r1                                                                                                                                                                                                    
Curve prime192v1                                                                                         
Curve prime192v2                                                                                         
Curve prime192v3                                                                                         
Curve prime239v1                                                                                         
Curve prime239v2                                                                                                                                                                                                   
Curve prime239v3                                                                                                                                                                                                   
Curve prime256v1                                                                                         
Curve wap-wsg-idm-ecid-wtls6                                                                             
Curve wap-wsg-idm-ecid-wtls7                                                                             
Curve wap-wsg-idm-ecid-wtls8                                                                             
Curve wap-wsg-idm-ecid-wtls9                                                                                                                                                                                       
Curve wap-wsg-idm-ecid-wtls12                                                                                                                                 
Curve brainpoolP160r1                                                                                                                                         
Curve brainpoolP160t1                                                                                                                                         
Curve brainpoolP192r1                                                                                                                                         
Curve brainpoolP192t1                                                                                                                                         
Curve brainpoolP224r1                                                                                                                                         
Curve brainpoolP224t1                                                                                                                                         
Curve brainpoolP256r1                                                                                                                                         
Curve brainpoolP256t1                                                                                                                                         
Curve brainpoolP320r1                                                                                                                                         
Curve brainpoolP320t1                                                                                                                                         
Curve brainpoolP384r1                                                                                                                                         
Curve brainpoolP384t1                                                          
Curve brainpoolP512r1                                                          
Curve brainpoolP512t1                                                          
Curve SM2                                                                      
Curve secp112r1                                                                
Curve secp112r2                                                                
Curve secp128r1                                                                
Curve secp128r2                                                                
Curve secp160k1                                                                
Curve secp160r1                                                                
Curve secp160r2                                                                
Curve secp192k1                                                                
Curve secp224k1                                                                
Curve secp224r1                                                                
Curve secp256k1                                                                
Curve secp384r1                                                                
Curve secp521r1                                                                
Curve prime192v1                                                               
Curve prime192v2                                                               
Curve prime192v3                                                               
Curve prime239v1                                                               
Curve prime239v2                                                               
Curve prime239v3                                                               
Curve prime256v1                                                               
Curve wap-wsg-idm-ecid-wtls6                                                   
Curve wap-wsg-idm-ecid-wtls7                                                   
Curve wap-wsg-idm-ecid-wtls8                                                   
Curve wap-wsg-idm-ecid-wtls9                                                   
Curve wap-wsg-idm-ecid-wtls12            
Curve brainpoolP160r1                                                                                                                                                                                                                                                                                               [54/188]
Curve brainpoolP160t1                                                          
Curve brainpoolP192r1                                                          
Curve brainpoolP192t1                                                          
Curve brainpoolP224r1                                                          
Curve brainpoolP224t1                                                          
Curve brainpoolP256r1                                                          
Curve brainpoolP256t1                                                          
Curve brainpoolP320r1                                                          
Curve brainpoolP320t1                                                          
Curve brainpoolP384r1                                                          
Curve brainpoolP384t1                                                          
Curve brainpoolP512r1                                                          
Curve brainpoolP512t1                                                          
Curve SM2                                                                      
Curve secp112r1                                                                
Curve secp112r2                                                                
Curve secp128r1                                                                
Curve secp128r2                                                                
Curve secp160k1                                                                
Curve secp160r1                                                                
Curve secp160r2                                                                
Curve secp192k1                                                                
Curve secp224k1                                                                
Curve secp224r1                                                                
Curve secp256k1                                                                
Curve secp384r1                                                                
Curve secp521r1                                                                
Curve prime192v1                                                               
Curve prime192v2                                                               
Curve prime192v3                                                               
Curve prime239v1                                                               
Curve prime239v2                                                               
Curve prime239v3                                                               
Curve prime256v1                                                               
Curve wap-wsg-idm-ecid-wtls6                                                   
Curve wap-wsg-idm-ecid-wtls7                                                   
Curve wap-wsg-idm-ecid-wtls8                                                   
Curve wap-wsg-idm-ecid-wtls9                                                   
Curve wap-wsg-idm-ecid-wtls12                                                  
Curve brainpoolP160r1                                                          
Curve brainpoolP160t1                                                          
Curve brainpoolP192r1                                                          
Curve brainpoolP192t1                                                          
Curve brainpoolP224r1                                                          
Curve brainpoolP224t1                                                          
Curve brainpoolP256r1                                                          
Curve brainpoolP256t1                                                          
Curve brainpoolP320r1                                                          
Curve brainpoolP320t1                                                          
Curve brainpoolP384r1                                                          
Curve brainpoolP384t1                                                          
Curve brainpoolP512r1                                                          
Curve brainpoolP512t1                                                          
Curve SM2                                                                      
SKIP: custom params not supported with SM2           
test ec_test completed                                                         
test ecdh_test completed                                                       
all ecdsa cases passed.                                                        
test ecdsa_test completed                                                      
test BN_add                                                                    
test BN_sub                                                                    
test BN_lshift1                                                                
test BN_lshift (fixed)                                                         
test BN_lshift                                                                 
test BN_rshift1                                                                
test BN_rshift                                                                 
test BN_sqr                                                                    
test BN_mul                                                                    
test BN_div                                                                    
test BN_div_word                                                               
test BN_div_recp                                                               
test BN_mod                                                                    
test BN_mod_mul                                                                
test BN_mont                                                                   
test BN_mod_exp                                                                
test BN_mod_exp_mont_consttime                                                 
test BN_exp                                                                    
test BN_kronecker                                                              
.........................++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                                     
....................................................................................................                                                          
test BN_mod_sqrt                                                               
.....                                                                          
.....                                                                          
.....                                                                          
.....                                                                          
.....                                                                          
.....                                                                          
.....                                                                          
.....                                                                          
..++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++             
.....                                                                          
.++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++              
.....                                                                          
...............................++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                               
.....                                                                          
..............++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                                                
.....                                                                          
.......................++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                                       
.....                                                                          
...++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++            
.....                                                                          
...++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++            
.....                                                                          
......++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++         
.....                                                                          
test Small prime generation                                                    
test bn_test completed                                                         
test dhtest completed                                                          
AES CCM test PASSED                                                            
test aesccm_test completed                                                     
test aesgcm_test completed                                                     
Testing SHA-256 ... passed.                                                    
Testing SHA-224 ... passed.                                                    
test sha256_test completed                                                     
test 1 ok                                                                      
test 2 ok                                                                      
test 3 ok                                                                      
test sha1_test completed                                                       
test hmac_test completed                                                       
original thread, id: 139734949441536                                           
in new thread, id: 139734948962304                                             
in new thread, id: 139734948483072                                             
PASS                                                                           
test threads_test completed                                                    
test evp_sm2_sign_verify completed                                             
test evp_sm2_encrypt_decrypt completed                                         
test evp_sm3 completed                                                         
test evp_sm4_cbc completed                                                     
test evp_sm4_ctr completed                                                     
```
</details>

**Comment by sbellem** [comment]
> ```shell
> $ nix run .#sgx-ssl.tests.HW
> ```

What is required to run the sgx-ssl hardware tests? I have the out-of-tree sgx driver installed, on an SGX -cacpable machine, and get the following error:

```shell
$ nix run .#sgx-ssl.tests.HW
token_path: /home/sylvain/enclave.token
Error: Unexpected error occurred.
```

**Comment by phlip9** [comment]
> What is required to run the sgx-ssl hardware tests? I have the out-of-tree sgx driver installed, on an SGX -cacpable machine (...)

Unfortunate that it gives such a useless error message. My understanding is that the out-of-tree driver is deprecated and not-guaranteed-compatible (?) now that SGX support is upstreamed to Linux proper, so I'd recommend trying on a recent kernel with the in-tree driver.

Assuming your kernel is setup properly, you should see some evidence like:

```bash
$ journalctl --dmesg --grep=sgx
Jan 24 03:18:51 kernel: sgx: EPC section 0x2c0000000-0x3bfffffff

$ ls -l /dev | grep sgx
drwxr-xr-x  2 root root          80 Jan 24 03:18 sgx
crw-rw----  1 root sgx      10, 125 Jan 24 03:18 sgx_enclave
crw-rw----  1 root sgx_prv  10, 126 Jan 24 03:18 sgx_provision
```

You'll also want the user running tests to be a member of the `sgx` group (or just run as root).

If this still doesn't work, you could try our nix-packaged [`sgx-detect`](https://github.com/lexe-app/lexe-public/blob/master/nix/pkgs/sgx-detect.nix) for more detailed debugging:

```rust
$ nix run github:lexe-app/lexe-public#packages.x86_64-linux.sgx-detect

Detecting SGX, this may take a minute...
✔  SGX instruction set
  ✔  CPU support
  ✔  CPU configuration
  ✔  Enclave attributes
  ✔  Enclave Page Cache
  SGX features
    ✔  SGX2  ✔  EXINFO  ✘  ENCLV  ✘  OVERSUB  ✔  KSS
    Total EPC size: 4.0GiB
✔  Flexible launch control
  ✔  CPU support
  ✔  CPU configuration
  ✔  Able to launch production mode enclave
✔  SGX system software
  ✔  SGX kernel device (/dev/sgx_enclave)
  ✘  libsgx_enclave_common
  ✔  AESM service
  ✔  Able to launch enclaves
    ✔  Debug mode
    ✔  Production mode
    ✔  Production mode (Intel whitelisted)

You're all set to start running SGX programs!
```

**Comment by phlip9** [comment]
Rebased on latest nixos-unstable

**Review by haraldh — APPROVED** [review]

**Review by pbsds — APPROVED** [review]
LGTM, but there seems to some missing dynamic linking.

<details>

```
$ fd --no-ignore --hidden -L . result* --type x -x bash -c 'ldd {} >&/dev/null && ( ldd {} | grep -q " not found"  ) && ( echo {} ; ldd {} | grep " not found" )'
results/sgx-psw/aesm/aesm_service
	libCppMicroServices.so.4.0.0 => not found
	libutils.so => not found
	libipc.so => not found
	liboal.so => not found
results/sgx-psw/aesm/libdcap_quoteprov.so
	libsgx_default_qcnl_wrapper.so => not found
	liboal.so => not found
results/sgx-psw/aesm/libutils.so
	liboal.so => not found
results/sgx-psw/aesm/libsgx_default_qcnl_wrapper.so
	liboal.so => not found
results/sgx-psw/aesm/bundles/libecdsa_quote_service_bundle.so
	libCppMicroServices.so.4.0.0 => not found
	libutils.so => not found
	libsgx_qe3_logic.so => not found
	liboal.so => not found
results/sgx-psw/aesm/bundles/liblinux_network_service_bundle.so
	libCppMicroServices.so.4.0.0 => not found
	libutils.so => not found
	liboal.so => not found
results/sgx-psw/aesm/bundles/libepid_quote_service_bundle.so
	libCppMicroServices.so.4.0.0 => not found
	libutils.so => not found
	liburts_internal.so => not found
	liboal.so => not found
results/sgx-psw/aesm/bundles/libpce_service_bundle.so
	libCppMicroServices.so.4.0.0 => not found
	liboal.so => not found
	libsgx_pce_logic.so.1 => not found
results/sgx-psw/aesm/bundles/libquote_ex_service_bundle.so
	libCppMicroServices.so.4.0.0 => not found
	libutils.so => not found
	liboal.so => not found
results/sgx-psw/aesm/bundles/lible_launch_service_bundle.so
	libCppMicroServices.so.4.0.0 => not found
	libutils.so => not found
	liburts_internal.so => not found
	liboal.so => not found

$ nix-locate libutils.so
pgmodeler.out                                         0 s /nix/store/s7dm0l5ylvmv7d61572f7d331imj55xy-pgmodeler-1.1.2/lib/pgmodeler/libutils.so
pgmodeler.out                                         0 s /nix/store/s7dm0l5ylvmv7d61572f7d331imj55xy-pgmodeler-1.1.2/lib/pgmodeler/libutils.so.1
pgmodeler.out                                         0 s /nix/store/s7dm0l5ylvmv7d61572f7d331imj55xy-pgmodeler-1.1.2/lib/pgmodeler/libutils.so.1.0
pgmodeler.out                                   202,888 x /nix/store/s7dm0l5ylvmv7d61572f7d331imj55xy-pgmodeler-1.1.2/lib/pgmodeler/libutils.so.1.0.0

$ nix-locate libipc.so
wayfire.out                                     287,160 x /nix/store/3dp3hr5zqmbwm0bq222fk70kmanh0vrj-wayfire-0.8.1/lib/wayfire/libipc.so

```
</details>

I assume this is fine?

**Comment by phlip9** [comment]
> @pbsds 
>
> LGTM, but there seems to some missing dynamic linking.
> 
> ...
> 
> I assume this is fine?

Right, the `aesm_service` binary wrapper sets the `LD_LIBRARY_PATH` to include these libs.

```bash
makeWrapper $out/aesm/aesm_service $out/bin/aesm_service \
  --suffix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ protobuf ]}:$out/aesm \
  --chdir "$out/aesm"
```

**Pull request merged**
