### PR TITLE
fmt_9: init at 9.0.0

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

* upstream release with [new features and many bugfixes](https://github.com/fmtlib/fmt/releases/tag/9.0.0)
* fix for the homepage (was a http-only server which redirects to the current homepage)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
Hmm, creating seperate attribute paths for all new releases doesn't seem the greatest. It was originally done for version 8 as many packages broke with the update, but (AFAIK?) that shouldn't be the case with this update.

The packages still using version 7 should get updated to the latest, so that we can remove it.

For now I suppose this is fine, maybe we should also introduce a temporary `fmt_latest` attribute which we can switch other packages to?

**Comment by panicgh** [comment]
Thanks for the comment. I updated the commit as per your suggestion to `fmt_latest`.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fmt_latest</li>
  </ul>
</details>

I tried also `fmt_8` -> `fmt_latest` and did a nixpkgs-review, but many packages would become broken (it may look similar for `fmt_7`). So I think it must be done gradually and per package:

```
3 packages marked as broken and skipped:
libsForQt512.plasma-vault libsForQt514.plasma-vault lizardfs

51 packages failed to build:
contour cryfs gerbera gnss-sdr gnuradio gnuradioMinimal gnuradio3_9Packages.gnuradio hal-hardware-analyzer irods irods-icommands kodi kodi-gbm kodi-wayland kodiPackages.a4ksubtitles kodiPackages.archive_tool kodiPackages.iagl kodiPackages.inputstream-adaptive kodiPackages.inputstream-ffmpegdirect kodiPackages.inputstream-rtmp kodiPackages.invidious kodiPackages.joystick kodiPackages.kodi-platform kodiPackages.libretro kodiPackages.libretro-genplus kodiPackages.libretro-mgba kodiPackages.libretro-snes9x kodiPackages.netflix kodiPackages.pvr-hdhomerun kodiPackages.pvr-hts kodiPackages.pvr-iptvsimple kodiPackages.steam-controller kodiPackages.vfs-libarchive kodiPackages.vfs-sftp libsForQt5.plasma-vault openroad python310Packages.qiskit python310Packages.qiskit-aer python310Packages.qiskit-finance python310Packages.qiskit-ibmq-provider python310Packages.qiskit-ignis python310Packages.qiskit-nature python310Packages.qiskit-optimization python39Packages.qiskit python39Packages.qiskit-aer python39Packages.qiskit-finance python39Packages.qiskit-ibmq-provider python39Packages.qiskit-ignis python39Packages.qiskit-nature python39Packages.qiskit-optimization vowpal-wabbit waybar

27 packages built:
ananicy-cpp bear cherrytree coeurl dwarfs easyeffects far2l fmt_latest folly furnace mariadb_107 mariadb_108 micromamba mtxclient nheko nrfutil pc-ble-driver pynitrokey python310Packages.pc-ble-driver-py python310Packages.vowpalwabbit python39Packages.pc-ble-driver-py python39Packages.vowpalwabbit spdlog wasmedge wdt yuzu-early-access yuzu-mainline
```

Should `fmt_latest` and the possible bumps fmt_x -> fmt_latest in various packages be backported to 22.05?

**Comment by bachp** [comment]
What about adding `fmt_9` and then at some point do `fmt = fmt_9`?

**Comment by panicgh** [comment]
Ok, now I'm trying to satisfy both sides: I reintroduced `fmt_9` and made an `fmt_latest = fmt_9` alias.

New packages can start using `fmt_latest`. Then later, someone makes a new PR for 

- going through all packages with `fmt` and pin them in `.overrides` to `fmt = fmt_(7|8|9|latest)` (similar to #89731)
- point `fmt = fmt_(9|latest)` in all-packages.nix
- remove `fmt_latest` and replace every usage with `fmt` or remove the override

**Review by bachp — APPROVED** [review]

**Pull request merged**
