### PR TITLE
[WIP] all-packages.nix: Use pkgs ("self") instead of res (next stage super)

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

`res` is redundant. The goal of this PR is to run it on ofborg so [changes](https://gist.github.com/GrahamcOfBorg/2e3b568727ac6443314a5ffdc5209cdc) can be triaged.

@Ericson2314 have a look :)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danbst** [comment]
`pkgs.` is redundant as well

**Comment by roberth** [comment]
@danbst you can arrange it such that it is, but I don't know whether that's an improvement. It may make conforming with nbp's security idea easier, but otherwise it just obfuscates the still existing possibility of depending on arbitrary parts of the final package set.

**Comment by roberth** [comment]
@Ericson2314 did you make any progress on the drv differences from these changes?

**Comment by Infinisil** [comment]
@roberth Not sure what you mean. There's a `with pkgs;` at the very top of all-packages.nix so everything is in scope already and you don't need to use `pkgs.`. It's what is being done in the rest of that file as well.

**Comment by danbst** [comment]
@roberth the nbp's security proposal forbids this:
```
pkgs: super:
rec {
  ...
}
```
but it is not a case for all-packages.nix now (like @Infinisil mentioned). It is:
```
pkgs: super:
with pkgs; {
  ...
}
```
And this is fine

**Comment by roberth** [comment]
@danbst, I read that as deleting the whole `pkgs` parameter, perhaps relying on `callPackage`.

I prefer to avoid the `with` keyword with the repl as the only exception, because it makes finding a declaration harder and it makes static scope checking impossible.

My original goal was to solve the previous inconsistent naming as done in #51401.
I don't feel very strongly about this pr, so feel free to improve it as you please.

**Comment by danbst** [comment]
closing in favor of https://github.com/NixOS/nixpkgs/pull/55061

**Pull request closed without merging**
