### PR TITLE
nixos/systemd-boot: avoid expensive mypy builds on configuration changes

### PR DESCRIPTION
**Pull request by Mic92**
* Mypy dependencies pull in quite a few packages, which makes it harder to create offline installers.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JulienMalka** [comment]
@ofborg test systemd-boot

**Review by JulienMalka — APPROVED** [review]
LGTM thanks

**Comment by spiage** [comment]
@Mic92 
Hi! I have something strange with package name, maybe after this commit:
```
[A.]  #8  x95gq7vjlzrp2k67n95mgs37by7v1aa8-systemd-boot  <none>
Removed packages:
[R.]  #1  systemd-boot  <none>
```

**Comment by JulienMalka** [comment]
> @Mic92 Hi! I have something strange with package name, maybe after this commit:
> 
> ```
> [A.]  #8  x95gq7vjlzrp2k67n95mgs37by7v1aa8-systemd-boot  <none>
> Removed packages:
> [R.]  #1  systemd-boot  <none>
> ```

@spiage what is this the output of ?

**Comment by spiage** [comment]
@JulienMalka output of nvd diff /run/booted-system /run/current-system

nix profile diff-closures --profile /nix/var/nix/profiles/system
output is:
```
Version 8929 -> 8930:
  nixos-system-nixos: 24.05.20240429.bb54a0c → 24.05.20240429.3d7b4b7
  systemd: -15.5 KiB
  x95gq7vjlzrp2k67n95mgs37by7v1aa8-systemd: ∅ → ε, +15.2 KiB
```

**Comment by Mic92** [comment]
It's this source: https://github.com/NixOS/nixpkgs/pull/306339/files#diff-6c7419829c336dc7d2e0be0c7ab29dcc159b84151835735276aba0a85374038bR13

**Comment by spiage** [comment]
Thank you!

**Pull request merged**
