### PR TITLE
1password: 0.4.1 -> 0.5.1

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by rossabaker** [comment]
There is already an 0.5.1.  Hashes:

```bash
$ for i in linux_386 linux_amd64 darwin_amd64; do nix-prefetch-url --unpack https://cache.agilebits.com/dist/1P/op/pkg/v0.5.1/op_${i}_v0.5.1.zip; done
unpacking...
path is '/nix/store/3hiwj9wby836rhdsqqn69946zbc076a2-op_linux_386_v0.5.1.zip'
08kzjilxpkvlwqjyxnic1n6xiy6gkndijwxdksm59k7c56mdawsz
unpacking...
path is '/nix/store/g6lvv12rzfk47qys7fd5ghn3lkym272p-op_linux_amd64_v0.5.1.zip'
1bsbzaqws0z991r6rkjrxay74fj4g5ld4d748ygr0950zwi1m3h7
unpacking...
path is '/nix/store/f6v0rbmxl2j2v4z2sjd59fbz324y38x2-op_darwin_amd64_v0.5.1.zip'
1dhr8m9icip27v802gxl1vhl9rf0jq5awirdm72lqmlypj86df0g
```

**Comment by marsam** [comment]
@rossabaker thanks! updated

**Comment by xeji** [comment]
Built locally on x86_64-linux and manually verified the binary's signature.

**Pull request merged**
