### PR TITLE
Fix graphite crash by upgrading from 0.9.15 -> 1.0.2

### PR DESCRIPTION
**Pull request by basvandijk**
~~**Please don't merge yet since this is Work In Progress!**~~

This is an attempt to solve https://github.com/NixOS/nixpkgs/issues/29961 by upgrading graphite to its latest version.

One problem that remains is that graphite_web doesn't serve its static files like .css and .js. Who can help me fix that?

You can play with graphite in a virtual machine that you can start using:

```
$(nix-build nixos/tests/graphite.nix -A driver --no-out-link)/bin/nixos-run-vms
```

This will boot a virtual machine with graphite enabled. The machine will start an X server with xmonad as your window manager. Firefox is installed so that it's easy to see if graphite_web is operating correctly.

* Press Alt-Shift-Enter to open a terminal.
* Run firefox
* Open the network inspector using Ctrl-Shift-C
* Select the "Network" tab
* Open graphite_web on `http://localhost:8080` 
* Observe that all static files return 404s

### CODE REVIEW

**Comment by lsix** [comment]
Hi,

I will have a look ASAP, but probably not before the beginning of next week.

I have not looked at this packaging yet, but usually here is what is done for django apps:
- a site is usually composed of multiple [django] applications, each of them having static files stored along with them
- before deploying, all those static files should be collected into one common static folder (usually using `django-manage.py collectstatic`) for the web server to be able to find them. It knows how to load applications since they are python modules available to it, but the static files themselves are expected to be stored all together.

I guess that here either this step is missing or the server does not know where to find the collected files.

See here for some general documentation: https://docs.djangoproject.com/en/1.8/howto/static-files/deployment/

Again, I have not looked at it yet, and have never deployed graphite. This is basically what I will look at first.

**Comment by basvandijk** [comment]
@lsix these pointers are helpful, thanks. I just [tried](https://github.com/NixOS/nixpkgs/pull/30166/commits/afe062665d581aca223e2b79f02de15d38c8d084) setting `STATIC_ROOT` and calling `django-admin.py collectstatic` but I have no luck so far getting static files to serve.

**Comment by basvandijk** [comment]
I [fixed](https://github.com/NixOS/nixpkgs/pull/30166/commits/11cbeff4f773b30f876d3e85ab84d2264b5ae7b8) it.

I'm going to squash my commits into one then this PR could be merged.

**Comment by basvandijk** [comment]
The PR is now ready to be reviewed and merged.

@FRidh could you remove the `work in progress` label please?

**Comment by makefu** [comment]
@basvandijk I just wanted to thank you for your efforts. Finally i can upgrade my machines to the latest stable release, broken graphite was a major blocker for me. 👍

**Comment by basvandijk** [comment]
@makefu, my pleasure!

**Pull request merged**
