### PR TITLE
anytype: Added option to disable the Wayland wrapper

### PR DESCRIPTION
**Pull request by Reikimann**
## Description of changes
Attribute set argument `enableWayland` added defaulting to `true`, meaning no change for existing users.
This option is added to allow Anytype launcing in X11 environments. Setting the option to false circumvents Nvidia pascal card issues with EGL drivers.

May provide a fix for  #286733.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — CHANGES_REQUESTED** [review]
This is unnecssary because those flags are locked behind _two_ different envvars, NIXOS_OZONE_WL and WAYLAND_DISPLAY, and I would be shocked if both are set in an X session.

(Also for future reference, we don't use "conventional commits", please refer to our contributing guide or previous PRs for the format.)

**Comment by Reikimann** [comment]
Hey :)
The reason I added the option is because I get the following error when running the program:
`libEGL warning: egl: failed to create dri2 screen`. I get only a window border with my wallpaper visible in the window.
I run the Nvidia Pascal 1080 card on wayland and after some research it seemed to be a videodriver issue on old Nvida cards. Disabling the Wayland wrapper seemed to be the way to go; running in xwayland fixed my issue.

> (Also for future reference, we don't use "conventional commits", please refer to our contributing guide or previous PRs for the format.)

I read the Contributing.md guide, could you please expand on what you mean my "conventional commits"? (This is my first PR related to the NixOS project) 😄

**Comment by eclairevoyant** [comment]
> I read the Contributing.md guide, could you please expand on what you mean my "conventional commits"?

[This](https://www.conventionalcommits.org/en/v1.0.0/) is conventional commits. We don't use those. Our conventions are described [here instead](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions).

> running in xwayland fixed my issue.

You can use `NIXOS_OZONE_WL= anytype` to provide the exact same effect as this PR would (with wayland support off).

**Comment by Reikimann** [comment]
Oh, well in that case I'll thank you for your time and help :)

**Pull request closed without merging**
