### PR TITLE
bruno: 1.17.0 -> 1.18.0

### PR DESCRIPTION
**Pull request by gepbird**
## Description of changes

Release: https://github.com/usebruno/bruno/releases/tag/v1.18.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by kashw2 — APPROVED** [review]
WFM x86_64-linux

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 313904` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>bruno</li>
  </ul>
</details>

**Comment by mattpolzin** [comment]
I got a hash mismatch building on `aarch64-darwin`.
```
specified: sha256-vYN245vMt/NjISaaFSXOkELONVld6knaKbi5FiN/0tA=
got:    sha256-RwTJhMMdJHgsJYaFSRgdyFEOOosgIkQArUs+6iYXNnE=
```

Not sure why...

**Comment by mattpolzin** [comment]
Something strange is that gepbird and kashw2 were able to build on Linux; lucasew hit a failure when running nixpkgs-review on Linux; I failed to build on Darwin; and lastly, I was able to build on Linux as well.

**Comment by mattpolzin** [comment]
I wonder if this is related to something in `master` but not merged into this branch. It crops up for a nixpkgs-review` but not a regular build against this branch.

**Comment by lucasew** [comment]
> I wonder if this is related to something in `master` but not merged into this branch. It crops up for a `nixpkgs-review` but not a regular build against this branch.

It fixes the package.lock at fetch time. It's a workaround but it normally works.


Screenshot_20240523-155301

**Comment by mattpolzin** [comment]
Not sure if I was saying what I meant clearly; I wonder if between when this branch was created and now, a change to a derivation or tool on `master` caused the hash generated by pulling the source & fixing the lock file to be different.

**Comment by lucasew** [comment]
> Not sure if I was saying what I meant clearly; I wonder if between when this branch was created and now, a change to a derivation or tool on `master` caused the hash generated by pulling the source & fixing the lock file to be different.

Not sure but I don't think so. BTW normally r-ryantm does the job on this package and we only test if it runs then merge using the bot if OK.

**Comment by gepbird** [comment]
> BTW normally r-ryantm does the job on this package and we only test if it runs then merge using the bot if OK.

@lucasew If r-ryantm works I'll stop doing manual version bumps on bruno. But when the bot fails to build the updated package for some reason and doesn't post a PR, how do we know it happened and we need to fix something? Is there some hydra-like UI for the bot that shows which packages it failed to build?

I see that @mattpolzin got `sha256-RwTJhMMdJHgsJYaFSRgdyFEOOosgIkQArUs+6iYXNnE=` on aarch64-darwin and @lucasew got `sha256-QIew...` (on aarch64-darwin too or x86_64-darwin?) hashes which are different. Do you consistently get those hashes or they are different every time? If they are consistent, we could provide different hashes for different architectures, just like how binary packages do it.

It builds on both linux arches for me, so it must be a darwin issue, but I don't have that to test it. Can you check the diff of the generated `package-lock.json` files?

Result of `nixpkgs-review pr 313904` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bruno</li>
  </ul>
</details>

Result of `nixpkgs-review pr 313904` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bruno</li>
  </ul>
</details>

**Comment by lucasew** [comment]
> @lucasew If r-ryantm works I'll stop doing manual version bumps on bruno. But when the bot fails to build the updated package for some reason and doesn't post a PR, how do we know it happened and we need to fix something? Is there some hydra-like UI for the bot that shows which packages it failed to build?

https://r.ryantm.com/log/bruno/

**Comment by mattpolzin** [comment]
FWIW, I just rebuilt on `aarch64-darwin` off of `master` post merge of this PR and it worked. I'm confused, but not disappointed.

**Pull request merged**
