### PR TITLE
[Backport release-24.05] Update open-webui to 0.3.12

### PR DESCRIPTION
**Pull request by shivaraj-bh**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Pretty good job so far!

**Comment by shivaraj-bh** [comment]
Result of `nixpkgs-review pr 332915` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>62 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>minari</li>
    <li>minari.dist</li>
    <li>python311Packages.ale-py</li>
    <li>python311Packages.ale-py.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.minari</li>
    <li>python311Packages.minari.dist</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python311Packages.treeo</li>
    <li>python311Packages.treeo.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python312Packages.ale-py</li>
    <li>python312Packages.ale-py.dist</li>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.ctranslate2</li>
    <li>python312Packages.ctranslate2.dist</li>
    <li>python312Packages.faster-whisper</li>
    <li>python312Packages.faster-whisper.dist</li>
    <li>python312Packages.gymnasium</li>
    <li>python312Packages.gymnasium.dist</li>
    <li>python312Packages.minari</li>
    <li>python312Packages.minari.dist</li>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.tensorflow-bin</li>
    <li>python312Packages.tensorflow-bin.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
    <li>python312Packages.treeo</li>
    <li>python312Packages.treeo.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python312Packages.cartopy</li>
    <li>python312Packages.cartopy.dist</li>
    <li>python312Packages.opensfm</li>
    <li>python312Packages.opensfm.dist</li>
    <li>python312Packages.pvextractor</li>
    <li>python312Packages.pvextractor.dist</li>
    <li>python312Packages.spectral-cube</li>
    <li>python312Packages.spectral-cube.dist</li>
    <li>python312Packages.wrf-python</li>
    <li>python312Packages.wrf-python.dist</li>
  </ul>
</details>
<details>
  <summary>291 packages built:</summary>
  <ul>
    <li>authentik</li>
    <li>cura</li>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>moonraker</li>
    <li>nominatim</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>osm2pgsql</li>
    <li>paperless-ngx</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>pgcli (python311Packages.pgcli)</li>
    <li>pgcli.dist (python311Packages.pgcli.dist)</li>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python311Packages.aeppl</li>
    <li>python311Packages.aeppl.dist</li>
    <li>python311Packages.aesara</li>
    <li>python311Packages.aesara.dist</li>
    <li>python311Packages.aplpy</li>
    <li>python311Packages.aplpy.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.asf-search</li>
    <li>python311Packages.asf-search.dist</li>
    <li>python311Packages.augmax</li>
    <li>python311Packages.augmax.dist</li>
    <li>python311Packages.avwx-engine</li>
    <li>python311Packages.avwx-engine.dist</li>
    <li>python311Packages.awkward</li>
    <li>python311Packages.awkward.dist</li>
    <li>python311Packages.basemap</li>
    <li>python311Packages.basemap.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cf-xarray</li>
    <li>python311Packages.cf-xarray.dist</li>
    <li>python311Packages.chex</li>
    <li>python311Packages.chex.dist</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.correctionlib</li>
    <li>python311Packages.correctionlib.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.ctranslate2.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.dm-haiku</li>
    <li>python311Packages.dm-haiku.dist</li>
    <li>python311Packages.duckduckgo-search</li>
    <li>python311Packages.duckduckgo-search.dist</li>
    <li>python311Packages.equinox</li>
    <li>python311Packages.equinox.dist</li>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.faster-whisper.dist</li>
    <li>python311Packages.flask-admin</li>
    <li>python311Packages.flask-admin.dist</li>
    <li>python311Packages.flax</li>
    <li>python311Packages.flax.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geoalchemy2</li>
    <li>python311Packages.geoalchemy2.dist</li>
    <li>python311Packages.geodatasets</li>
    <li>python311Packages.geodatasets.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.glueviz</li>
    <li>python311Packages.glueviz.dist</li>
    <li>python311Packages.jax</li>
    <li>python311Packages.jax.dist</li>
    <li>python311Packages.jaxlib (python311Packages.jaxlib-build ,python311Packages.jaxlibWithoutCuda)</li>
    <li>python311Packages.jaxlib.dist (python311Packages.jaxlib-build.dist ,python311Packages.jaxlibWithoutCuda.dist)</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.jmp</li>
    <li>python311Packages.jmp.dist</li>
    <li>python311Packages.labelbox</li>
    <li>python311Packages.labelbox.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langfuse</li>
    <li>python311Packages.langfuse.dist</li>
    <li>python311Packages.libpysal</li>
    <li>python311Packages.libpysal.dist</li>
    <li>python311Packages.llama-index-vector-stores-postgres</li>
    <li>python311Packages.llama-index-vector-stores-postgres.dist</li>
    <li>python311Packages.mapclassify</li>
    <li>python311Packages.mapclassify.dist</li>
    <li>python311Packages.mayim</li>
    <li>python311Packages.mayim.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.objax</li>
    <li>python311Packages.objax.dist</li>
    <li>python311Packages.opensfm</li>
    <li>python311Packages.opensfm.dist</li>
    <li>python311Packages.optax</li>
    <li>python311Packages.optax.dist</li>
    <li>python311Packages.optax.testsout</li>
    <li>python311Packages.orbax-checkpoint</li>
    <li>python311Packages.orbax-checkpoint.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.owslib</li>
    <li>python311Packages.owslib.dist</li>
    <li>python311Packages.pgspecial</li>
    <li>python311Packages.pgspecial.dist</li>
    <li>python311Packages.pgvector</li>
    <li>python311Packages.pgvector.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.preprocess-cancellation</li>
    <li>python311Packages.preprocess-cancellation.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
    <li>python311Packages.psycopg</li>
    <li>python311Packages.psycopg.dist</li>
    <li>python311Packages.psycopg.doc</li>
    <li>python311Packages.pvextractor</li>
    <li>python311Packages.pvextractor.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pyosmium</li>
    <li>python311Packages.pyosmium.dist</li>
    <li>python311Packages.pyproj</li>
    <li>python311Packages.pyproj.dist</li>
    <li>python311Packages.pyreqwest-impersonate</li>
    <li>python311Packages.pyreqwest-impersonate.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
    <li>python311Packages.pytest-postgresql</li>
    <li>python311Packages.pytest-postgresql.dist</li>
    <li>python311Packages.qcodes</li>
    <li>python311Packages.qcodes-contrib-drivers</li>
    <li>python311Packages.qcodes-contrib-drivers.dist</li>
    <li>python311Packages.qcodes.dist</li>
    <li>python311Packages.rapidocr-onnxruntime</li>
    <li>python311Packages.rapidocr-onnxruntime.dist</li>
    <li>python311Packages.rasterio</li>
    <li>python311Packages.rasterio.dist</li>
    <li>python311Packages.shapely</li>
    <li>python311Packages.shapely.dist</li>
    <li>python311Packages.spectral-cube</li>
    <li>python311Packages.spectral-cube.dist</li>
    <li>python311Packages.tensorflow-bin</li>
    <li>python311Packages.tensorflow-bin.dist</li>
    <li>python311Packages.translatehtml</li>
    <li>python311Packages.translatehtml.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.uranium</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python311Packages.vqgan-jax</li>
    <li>python311Packages.vqgan-jax.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
    <li>python311Packages.wrf-python</li>
    <li>python311Packages.wrf-python.dist</li>
    <li>python312Packages.aplpy</li>
    <li>python312Packages.aplpy.dist</li>
    <li>python312Packages.asf-search</li>
    <li>python312Packages.asf-search.dist</li>
    <li>python312Packages.avwx-engine</li>
    <li>python312Packages.avwx-engine.dist</li>
    <li>python312Packages.awkward</li>
    <li>python312Packages.awkward.dist</li>
    <li>python312Packages.basemap</li>
    <li>python312Packages.basemap.dist</li>
    <li>python312Packages.bsuite</li>
    <li>python312Packages.bsuite.dist</li>
    <li>python312Packages.cf-xarray</li>
    <li>python312Packages.cf-xarray.dist</li>
    <li>python312Packages.chex</li>
    <li>python312Packages.chex.dist</li>
    <li>python312Packages.coffea</li>
    <li>python312Packages.coffea.dist</li>
    <li>python312Packages.correctionlib</li>
    <li>python312Packages.correctionlib.dist</li>
    <li>python312Packages.dask-awkward</li>
    <li>python312Packages.dask-awkward.dist</li>
    <li>python312Packages.duckduckgo-search</li>
    <li>python312Packages.duckduckgo-search.dist</li>
    <li>python312Packages.easyocr</li>
    <li>python312Packages.easyocr.dist</li>
    <li>python312Packages.equinox</li>
    <li>python312Packages.equinox.dist</li>
    <li>python312Packages.flask-admin</li>
    <li>python312Packages.flask-admin.dist</li>
    <li>python312Packages.folium</li>
    <li>python312Packages.folium.dist</li>
    <li>python312Packages.geoalchemy2</li>
    <li>python312Packages.geoalchemy2.dist</li>
    <li>python312Packages.geodatasets</li>
    <li>python312Packages.geodatasets.dist</li>
    <li>python312Packages.geopandas</li>
    <li>python312Packages.geopandas.dist</li>
    <li>python312Packages.jax</li>
    <li>python312Packages.jax.dist</li>
    <li>python312Packages.jaxlib (python312Packages.jaxlib-build ,python312Packages.jaxlibWithoutCuda)</li>
    <li>python312Packages.jaxlib.dist (python312Packages.jaxlib-build.dist ,python312Packages.jaxlibWithoutCuda.dist)</li>
    <li>python312Packages.jmp</li>
    <li>python312Packages.jmp.dist</li>
    <li>python312Packages.labelbox</li>
    <li>python312Packages.labelbox.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langfuse</li>
    <li>python312Packages.langfuse.dist</li>
    <li>python312Packages.libpysal</li>
    <li>python312Packages.libpysal.dist</li>
    <li>python312Packages.llama-index-vector-stores-postgres</li>
    <li>python312Packages.llama-index-vector-stores-postgres.dist</li>
    <li>python312Packages.mapclassify</li>
    <li>python312Packages.mapclassify.dist</li>
    <li>python312Packages.mayim</li>
    <li>python312Packages.mayim.dist</li>
    <li>python312Packages.mplhep</li>
    <li>python312Packages.mplhep.dist</li>
    <li>python312Packages.numpyro</li>
    <li>python312Packages.numpyro.dist</li>
    <li>python312Packages.optax</li>
    <li>python312Packages.optax.dist</li>
    <li>python312Packages.optax.testsout</li>
    <li>python312Packages.orbax-checkpoint</li>
    <li>python312Packages.orbax-checkpoint.dist</li>
    <li>python312Packages.osmnx</li>
    <li>python312Packages.osmnx.dist</li>
    <li>python312Packages.owslib</li>
    <li>python312Packages.owslib.dist</li>
    <li>python312Packages.pgcli</li>
    <li>python312Packages.pgcli.dist</li>
    <li>python312Packages.pgspecial</li>
    <li>python312Packages.pgspecial.dist</li>
    <li>python312Packages.pgvector</li>
    <li>python312Packages.pgvector.dist</li>
    <li>python312Packages.plotnine</li>
    <li>python312Packages.plotnine.dist</li>
    <li>python312Packages.preprocess-cancellation</li>
    <li>python312Packages.preprocess-cancellation.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
    <li>python312Packages.psycopg</li>
    <li>python312Packages.psycopg.dist</li>
    <li>python312Packages.psycopg.doc</li>
    <li>python312Packages.pyosmium</li>
    <li>python312Packages.pyosmium.dist</li>
    <li>python312Packages.pyproj</li>
    <li>python312Packages.pyproj.dist</li>
    <li>python312Packages.pyreqwest-impersonate</li>
    <li>python312Packages.pyreqwest-impersonate.dist</li>
    <li>python312Packages.pytest-postgresql</li>
    <li>python312Packages.pytest-postgresql.dist</li>
    <li>python312Packages.qcodes</li>
    <li>python312Packages.qcodes-contrib-drivers</li>
    <li>python312Packages.qcodes-contrib-drivers.dist</li>
    <li>python312Packages.qcodes.dist</li>
    <li>python312Packages.rapidocr-onnxruntime</li>
    <li>python312Packages.rapidocr-onnxruntime.dist</li>
    <li>python312Packages.rasterio</li>
    <li>python312Packages.rasterio.dist</li>
    <li>python312Packages.shapely</li>
    <li>python312Packages.shapely.dist</li>
    <li>python312Packages.uproot</li>
    <li>python312Packages.uproot.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
    <li>python312Packages.wktutils</li>
    <li>python312Packages.wktutils.dist</li>
    <li>qgis</li>
    <li>qgis-ltr</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
  </ul>
</details>

**Comment by drupol** [comment]
Do you know why the CI job "Cherry-picks" is failing?

**Comment by shivaraj-bh** [comment]
> Do you know why the CI job "Cherry-picks" is failing?

I had to resolve conflicts in two packages: `jaxlib` and `duckduckgo-search`. These are the two packages that the CI is complaining about as well. Looks like that is why it failed, but the check also says "_Note this should not necessarily be treated as a hard fail, but a reviewer's attention should be drawn to it and github actions have no way of doing that but to raise a ‘failure’_".

**Comment by shivaraj-bh** [comment]
> Result of `nixpkgs-review pr 332915` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 62 packages marked as broken and skipped:
> 2 packages blacklisted:
> 12 packages failed to build:
> 291 packages built:

<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python312Packages.cartopy</li>
    <li>python312Packages.cartopy.dist</li>
    <li>python312Packages.opensfm</li>
    <li>python312Packages.opensfm.dist</li>
    <li>python312Packages.pvextractor</li>
    <li>python312Packages.pvextractor.dist</li>
    <li>python312Packages.spectral-cube</li>
    <li>python312Packages.spectral-cube.dist</li>
    <li>python312Packages.wrf-python</li>
    <li>python312Packages.wrf-python.dist</li>
  </ul>
</details>

Note: The packages failing above also fail on `release-24.05` and are not introduced as part of this PR.

**Comment by shivaraj-bh** [comment]
Result of `nixpkgs-review pr 332915` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.opensfm</li>
    <li>python311Packages.opensfm.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.wrf-python</li>
    <li>python311Packages.wrf-python.dist</li>
    <li>python312Packages.bsuite</li>
    <li>python312Packages.bsuite.dist</li>
    <li>python312Packages.opensfm</li>
    <li>python312Packages.opensfm.dist</li>
    <li>python312Packages.plotnine</li>
    <li>python312Packages.plotnine.dist</li>
    <li>python312Packages.wrf-python</li>
    <li>python312Packages.wrf-python.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python312Packages.cartopy</li>
    <li>python312Packages.cartopy.dist</li>
    <li>python312Packages.pvextractor</li>
    <li>python312Packages.pvextractor.dist</li>
    <li>python312Packages.spectral-cube</li>
    <li>python312Packages.spectral-cube.dist</li>
  </ul>
</details>
<details>
  <summary>169 packages built:</summary>
  <ul>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>nominatim</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>osm2pgsql</li>
    <li>paperless-ngx</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>pgcli (python311Packages.pgcli)</li>
    <li>pgcli.dist (python311Packages.pgcli.dist)</li>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python311Packages.aplpy</li>
    <li>python311Packages.aplpy.dist</li>
    <li>python311Packages.asf-search</li>
    <li>python311Packages.asf-search.dist</li>
    <li>python311Packages.avwx-engine</li>
    <li>python311Packages.avwx-engine.dist</li>
    <li>python311Packages.basemap</li>
    <li>python311Packages.basemap.dist</li>
    <li>python311Packages.cf-xarray</li>
    <li>python311Packages.cf-xarray.dist</li>
    <li>python311Packages.duckduckgo-search</li>
    <li>python311Packages.duckduckgo-search.dist</li>
    <li>python311Packages.flask-admin</li>
    <li>python311Packages.flask-admin.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geoalchemy2</li>
    <li>python311Packages.geoalchemy2.dist</li>
    <li>python311Packages.geodatasets</li>
    <li>python311Packages.geodatasets.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.glueviz</li>
    <li>python311Packages.glueviz.dist</li>
    <li>python311Packages.labelbox</li>
    <li>python311Packages.labelbox.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langfuse</li>
    <li>python311Packages.langfuse.dist</li>
    <li>python311Packages.libpysal</li>
    <li>python311Packages.libpysal.dist</li>
    <li>python311Packages.llama-index-vector-stores-postgres</li>
    <li>python311Packages.llama-index-vector-stores-postgres.dist</li>
    <li>python311Packages.mapclassify</li>
    <li>python311Packages.mapclassify.dist</li>
    <li>python311Packages.mayim</li>
    <li>python311Packages.mayim.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.owslib</li>
    <li>python311Packages.owslib.dist</li>
    <li>python311Packages.pgspecial</li>
    <li>python311Packages.pgspecial.dist</li>
    <li>python311Packages.pgvector</li>
    <li>python311Packages.pgvector.dist</li>
    <li>python311Packages.preprocess-cancellation</li>
    <li>python311Packages.preprocess-cancellation.dist</li>
    <li>python311Packages.private-gpt</li>
    <li>python311Packages.private-gpt.dist</li>
    <li>python311Packages.psycopg</li>
    <li>python311Packages.psycopg.dist</li>
    <li>python311Packages.psycopg.doc</li>
    <li>python311Packages.pvextractor</li>
    <li>python311Packages.pvextractor.dist</li>
    <li>python311Packages.pyosmium</li>
    <li>python311Packages.pyosmium.dist</li>
    <li>python311Packages.pyproj</li>
    <li>python311Packages.pyproj.dist</li>
    <li>python311Packages.pyreqwest-impersonate</li>
    <li>python311Packages.pyreqwest-impersonate.dist</li>
    <li>python311Packages.pytest-postgresql</li>
    <li>python311Packages.pytest-postgresql.dist</li>
    <li>python311Packages.qcodes</li>
    <li>python311Packages.qcodes-contrib-drivers</li>
    <li>python311Packages.qcodes-contrib-drivers.dist</li>
    <li>python311Packages.qcodes.dist</li>
    <li>python311Packages.rapidocr-onnxruntime</li>
    <li>python311Packages.rapidocr-onnxruntime.dist</li>
    <li>python311Packages.rasterio</li>
    <li>python311Packages.rasterio.dist</li>
    <li>python311Packages.shapely</li>
    <li>python311Packages.shapely.dist</li>
    <li>python311Packages.spectral-cube</li>
    <li>python311Packages.spectral-cube.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
    <li>python312Packages.aplpy</li>
    <li>python312Packages.aplpy.dist</li>
    <li>python312Packages.asf-search</li>
    <li>python312Packages.asf-search.dist</li>
    <li>python312Packages.avwx-engine</li>
    <li>python312Packages.avwx-engine.dist</li>
    <li>python312Packages.basemap</li>
    <li>python312Packages.basemap.dist</li>
    <li>python312Packages.cf-xarray</li>
    <li>python312Packages.cf-xarray.dist</li>
    <li>python312Packages.duckduckgo-search</li>
    <li>python312Packages.duckduckgo-search.dist</li>
    <li>python312Packages.easyocr</li>
    <li>python312Packages.easyocr.dist</li>
    <li>python312Packages.flask-admin</li>
    <li>python312Packages.flask-admin.dist</li>
    <li>python312Packages.folium</li>
    <li>python312Packages.folium.dist</li>
    <li>python312Packages.geoalchemy2</li>
    <li>python312Packages.geoalchemy2.dist</li>
    <li>python312Packages.geodatasets</li>
    <li>python312Packages.geodatasets.dist</li>
    <li>python312Packages.geopandas</li>
    <li>python312Packages.geopandas.dist</li>
    <li>python312Packages.labelbox</li>
    <li>python312Packages.labelbox.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langfuse</li>
    <li>python312Packages.langfuse.dist</li>
    <li>python312Packages.libpysal</li>
    <li>python312Packages.libpysal.dist</li>
    <li>python312Packages.llama-index-vector-stores-postgres</li>
    <li>python312Packages.llama-index-vector-stores-postgres.dist</li>
    <li>python312Packages.mapclassify</li>
    <li>python312Packages.mapclassify.dist</li>
    <li>python312Packages.mayim</li>
    <li>python312Packages.mayim.dist</li>
    <li>python312Packages.osmnx</li>
    <li>python312Packages.osmnx.dist</li>
    <li>python312Packages.owslib</li>
    <li>python312Packages.owslib.dist</li>
    <li>python312Packages.pgcli</li>
    <li>python312Packages.pgcli.dist</li>
    <li>python312Packages.pgspecial</li>
    <li>python312Packages.pgspecial.dist</li>
    <li>python312Packages.pgvector</li>
    <li>python312Packages.pgvector.dist</li>
    <li>python312Packages.preprocess-cancellation</li>
    <li>python312Packages.preprocess-cancellation.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
    <li>python312Packages.psycopg</li>
    <li>python312Packages.psycopg.dist</li>
    <li>python312Packages.psycopg.doc</li>
    <li>python312Packages.pyosmium</li>
    <li>python312Packages.pyosmium.dist</li>
    <li>python312Packages.pyproj</li>
    <li>python312Packages.pyproj.dist</li>
    <li>python312Packages.pyreqwest-impersonate</li>
    <li>python312Packages.pyreqwest-impersonate.dist</li>
    <li>python312Packages.pytest-postgresql</li>
    <li>python312Packages.pytest-postgresql.dist</li>
    <li>python312Packages.qcodes</li>
    <li>python312Packages.qcodes-contrib-drivers</li>
    <li>python312Packages.qcodes-contrib-drivers.dist</li>
    <li>python312Packages.qcodes.dist</li>
    <li>python312Packages.rapidocr-onnxruntime</li>
    <li>python312Packages.rapidocr-onnxruntime.dist</li>
    <li>python312Packages.rasterio</li>
    <li>python312Packages.rasterio.dist</li>
    <li>python312Packages.shapely</li>
    <li>python312Packages.shapely.dist</li>
    <li>python312Packages.wktutils</li>
    <li>python312Packages.wktutils.dist</li>
  </ul>
</details>

**Comment by drupol** [comment]
0.3.12 is now available, see #333008

**Comment by nixupp** [comment]
should this package be available in the tree now?
I cannot see it: https://search.nixos.org/packages?channel=24.05&type=packages&query=open-webui

**Comment by drupol** [comment]
Just give it one or two more days and it will show up.

**Comment by developomp** [comment]
Started getting a [build failure](https://github.com/NixOS/nixpkgs/issues/349432) after this got merged.

**Comment by dotlambda** [comment]
Why the heck was this merged? At least half of those commits are unsuitable for backporting.

**Comment by dotlambda** [comment]
After a careful analysis with the help of @Artturin and @emilazy all backports but the one to open-webui seem to be allowed under the backport guidelines. We weren't able to judge the open-webui bump.
In the future please provide a rationale for why such backports are acceptable. Nixpkgs-review not showing any failures is not sufficient. See https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases.

**Comment by shivaraj-bh** [comment]
> Started getting a [build failure](https://github.com/NixOS/nixpkgs/issues/349432) after this got merged.

Are you sure? it seems to build fine on `release-24.05`?

```sh
# On `x86_64-linux`
❯ nix build github:nixos/nixpkgs/release-24.05#python3Packages.pyreqwest-impersonate --no-link --print-out-paths
/nix/store/8a0xq27sg3x40xhkw6zsca7gfd63610i-python3.11-pyreqwest-impersonate-0.4.9
```

**Comment by shivaraj-bh** [comment]
> Why the heck was this merged? At least half Some of those commits are unsuitable for backporting.
> EDIT: They only looked bad and it took a while to figure out that they are probably fine.
>
> After a careful analysis with the help of @Artturin and @emilazy all backports but the one to open-webui seem to be allowed under the backport guidelines. We weren't able to judge the open-webui bump. In the future please provide a rationale for why such backports are acceptable. Nixpkgs-review not showing any failures is not sufficient. See https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases.

I did go through the guidelines. The only unacceptable commit seemed to be `duckduckgo-search` and when I went through the changelog, the only breaking change was the change in a dependency but I didn’t see anything about breaking API’s. 

The bumps to packages other than `open-webui` are in the same PR and not separated into their individual PR’s because these commits to `master` were also done alongside `open-webui` bump.

I apologise, I should have mentioned all of this in the PR description to avoid wasting all of your time. I will keep that in mind from next time.

**Pull request merged**
