### PR TITLE
glava: 1.5.1 -> 1.5.5

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build glava

**Comment by xeji** [comment]
hash mismatch (in a git submodule?)

**Comment by eadwu** [comment]
With versions 1.5.4+, the glad submodule isn't needed anymore, though I'll just use the hash generated from `--fetch-submodules` then.

**Comment by xeji** [comment]
@GrahamcOfBorg build glava

**Comment by xeji** [comment]
> With versions 1.5.4+, the glad submodule isn't needed anymore, though I'll just use the hash generated from --fetch-submodules then.

That's fine for now. We generally prefer `fetchFromGitHub` (which does not fetch submodules by default) for fetching from Github repos. I suggest you change that with the next update.

**Pull request merged**
