### PR TITLE
bugfix: fix broken java paths in codeql environment and update to v2.11.4

### PR DESCRIPTION
**Pull request by anticomputer**
###### Description of changes

This is both a functionality fix and a version update. The current package is broken beyond the superficial use cases of the codeql CLI package. The current package does NOT allow you to create databases because it does not account for the codeql language extractors and how they are invoked.

Many of the codeql extractors use CODEQL_DIST + CODEQL_PLATFORM to resolve java home, so to be able to create databases, we want to make sure that they point somewhere sane/usable since we can not autopatch the codeql packaged java dist, but we DO want to patch the extractors as well as the builders which are ELF binaries for the most part.

This commit replaces the embedded codeql java interpreter, which is not NixOS compatible, with the NixOS jdk11 version entirely via a symlink in the codeql operating environment.

I've attempted to get these changes merged for the 22.05 release back in April, but they never got accepted. If there's any additional requirements for review please let me know.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jollheef — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
> I've attempted to get these changes merged for the 22.05 release back in April, but they never got accepted. If there's any additional requirements for review please let me know.

Oof, sorry about that...

I ran into the same problem and fixed it in #238934 before I found your PR :/

If you fix the conflict in this PR and can explain why adding autopatchelf is needed here I'd be happy to test and merge yours.

**Review by Janik-Haag — CHANGES_REQUESTED** [review]
Can you please rename the commit doing the version updated to:
`codeql: 2.11.0 -> 2.11.4`
and the java paths fix to:
`codeql: fix broken java paths`

other wise this looks good.

**Comment by raboof** [comment]
superseded by #238934

**Pull request closed without merging**
