### PR TITLE
spotifyd: 0.2.19 -> 0.2.20 (mpris enabled)

### PR DESCRIPTION
**Pull request by MtP76**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by rasendubi — CHANGES_REQUESTED** [review]

**Review by anderslundstedt — COMMENTED** [review]
I get the following error:

```
[ERROR] Caught panic with message: Failed to initialize DBus connection: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)
```

Use `withDBUS ? false` instead of `withDBUS ? true`?

**Comment by anderslundstedt** [comment]
With this version bump my `spotifyd` service failed with

```
[ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
```

The fix was to clear out the `/var/spotifyd/cache` directory. I guess the old cache was not compatible with the new version. Is there any way we can ensure that the cache is cleared when upgrading versions?

**Review by rasendubi — COMMENTED** [review]
The cache issue is not Nix-specific, so I would go for upstream.

The dbus start issue seems to be caused by spotifyd not running with X11. Not sure how much of an issue that is as I don't use spotifyd.

@MtP76 what do you think?

**Review by rasendubi — DISMISSED** [review]

**Comment by anderslundstedt** [comment]
> The cache issue is not Nix-specific, so I would go for upstream.

Will do. If upstream fixes this issue then I would vote for skipping the 0.2.20 version, so as to not break the spotifyd service for people.

> The dbus start issue seems to be caused by spotifyd not running with X11. Not sure how much of an issue that is as I don't use spotifyd.

Definitely an issue since one use case (for example, my use case) is running spotifyd as a headless Spotify Connect client.

**Comment by anderslundstedt** [comment]
> > The cache issue is not Nix-specific, so I would go for upstream.
> 
> Will do.

https://github.com/Spotifyd/spotifyd/issues/433

**Comment by anderslundstedt** [comment]
After clearing the cache I cannot reproduce the cache problem (see https://github.com/Spotifyd/spotifyd/issues/433 for more details). Upstream will not fix the problem unless it happens more often. I guess we will have to accept that this version bump might break the spotifyd service? I would still need to see the DBUS without X11 problem solved before approving this pull request, though.

**Comment by rasendubi** [comment]
As a quick fix, we could encode spotifyd version in the cache directory name? Instead of `/var/cache/spotifyd`, it would be `/var/cache/spotifyd-0.2.20`

**Comment by anderslundstedt** [comment]
That would indeed solve the problem. But there are the obvious disadvantages to clearing the cache: songs need to be recached and credentials need to be added again. If the problem I ran into is rare enough then perhaps such a quickfix is not worth it? I do not know what to prefer here.

**Pull request closed without merging**
