### PR TITLE
python.pkgs: pip 9.0.3 -> 10.0.1

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Pip 10 has been released. I think the most interesting improvement for us is that the `RECORD` file in `dist-info` is now generated deterministically.

https://hydra.nixos.org/eval/1448410

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
This breaks `docker-py` which in effect breaks moto -> pandas -> other stuff.

https://nix-cache.s3.amazonaws.com/log/kaw1dwx9x5qzp7xad2d8576ad8ksnxis-python2.7-docker-3.2.1.drv

https://github.com/docker/docker-py/issues/1993

**Review by dotlambda — APPROVED** [review]
Should be ready to go.

**Comment by dotlambda** [comment]
Isn't that the one updated in 6d2dd3307060a0a9dc3532e123726c8657ba6c98?

**Comment by FRidh** [comment]
No, @colemickens refers to the 0.31.0 wheel release of April 1st. I intend to include that as well.

Waiting for my internet connection at home to get fixed though...

@dotlambda we can then also include the Python 2.7.15 release and possibly some other Python interpreter PR's from last week.

**Comment by dotlambda** [comment]
@FRidh I just spotted

> TODO: Shouldn't be necessary anymore for pip >= 10!

**Comment by FRidh** [comment]
yea...I did not dare removing it just yet. It was added if I recall correctly to prevent certain occasional and hard-to-reproduce errors. We could remove it, as a separate commit, but within this PR.

**Pull request merged**
