### PR TITLE
Update protobuf and remove old versions

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

First motivation was to update protobuf to 3.4 so that TensorFlow 1.3 could be used. Later I updated all nixpkgs to use protobuf 3.4 (the latest version), sans one package that needs an old version (3.1).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Remaining packages which don't build with this change seem to fail because of unrelated reason.

### CODE REVIEW

**Comment by FRidh** [comment]
Do you think we should backport (some) of this? Maybe not the removal of the older versions, but the addition and changing the default we might.

**Comment by abbradar** [comment]
Hm, if we backport at least the addition I can then also backport new TensorFlow, maybe along with my other ML-related commits (current packages are somewhat outdated). Not sure about the default (but it'd make backporting other things easier).

**Comment by bjornfor** [comment]
Please fix https://github.com/NixOS/nixpkgs/commit/6589ee83c2264d88ea3277186e239039e8818aae#commitcomment-24187697 before backporting.

**Comment by abbradar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/0d558049cf68e98108df67495e02b27fca0c357b, thanks again.

**Comment by roconnor-blockstream** [comment]
trezord depends on protobuf 2.6 and is broken by this change.  Please restore protobuf2_6.

(cc @jb55)

**Comment by abbradar** [comment]
Fixed in 27a4820c748d5e970b8e1abd4dba9b31ce00e850 by rebuilding protobuf files like described in https://github.com/trezor/trezord. Sorry for the breakage!

**Comment by volth** [comment]
hadoop (2.7, 2.8) depends on ```protobuf2_5```, it does not work even with ```protobuf2_6```

**Pull request merged**
