### PR TITLE
automake: 1.15 -> 1.15.1

### PR DESCRIPTION
**Pull request by wizzup**
###### Motivation for this change
[automake 1.15.1](https://lists.gnu.org/archive/html/automake/2017-06/msg00003.html)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Thanks, but is already on staging: 60730cb04351a4ab3ecde1d36b2d441762defb6e

**Comment by wizzup** [comment]
@globin Could you give a brief explain about relation between `master` and `staging` or point me to documentation to learn more?

**Comment by vcunat** [comment]
@wizzup: https://nixos.org/nixpkgs/manual/#idm140737317567504  (the anchor in the link is unstable but you can find it without it easily)

**Comment by vcunat** [comment]
Any ideas why the update would make multiple packages start reporting a version mismatch?  Example: https://hydra.nixos.org/build/58675314

**Comment by wizzup** [comment]
hard-code automake version I think , maybe you have to patch them,  example: colord, configure.am line 12

AM_INIT_AUTOMAKE([1.9 no-dist-gzip dist-xz tar-ustar foreign])

**Comment by wizzup** [comment]
running `autoreconf` before configuring seem to fix the problem adc2dc8

**Pull request closed without merging**
