### PR TITLE
local-ai: init at 2.10.1

### LINKED ISSUE #269582: Package request: LocalAI
**Project description**

The free, Open Source OpenAI alternative. Self-hosted, community-driven and local-first. Drop-in replacement for OpenAI running on consumer-grade hardware. No GPU required. Runs ggml, gguf, GPTQ, onnx, TF compatible models: llama, llama2, rwkv, whisper, vicuna, koala, cerebras, falcon, dolly, starcoder, and many others

**Metadata**

* homepage URL: https://localai.io/
* source URL: https://github.com/mudler/LocalAI
* license: mit
* platforms: linux

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ck3d**
## Description of changes

Add local-ai to nixpkgs.

I took #288269 over, to increase progress.
Fixes #269582

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by KiaraGrouwstra** [comment]
i can build it with this, tho it now still gives me `error loading config files: open /home/kiara/.cache/nixpkgs-review/pr-291647/models: no such file or directory`. (i didn't have previous experience with localAI, mind.)

**Comment by ck3d** [comment]
You should follow https://localai.io/docs/getting-started/manual/ to get `local-ai` running.
Following NixOS module could also give some hints: https://github.com/jakehamilton/config/blob/main/modules/nixos/services/local-ai/default.nix

**Comment by KiaraGrouwstra** [comment]
hm, i might not really get the RFC yet:

```
$ nix-build -A localai --with-tts
error: unexpected argument '--with-tts'
$ nix run nixpkgs#nixpkgs-review -- pr 291647 --with-tts
usage: /nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/bin/nixpkgs-review
$ nix run nixpkgs#nixpkgs-review -- pr 291647 --extra-nixpkgs-config '{ with_tts = true; }'
1 package built:
local-ai
$ ./results/local-ai/bin/.local-ai-wrapped
http://localhost:8080
$ curl http://localhost:8080/tts -H "Content-Type: application/json" -d '{
  "input": "Hello world",
  "model": "tts"
}'
{"error":{"code":500,"message":"grpc process not found: /tmp/localai/backend_data/backend-assets/grpc/piper. some backends(stablediffusion, tts) require LocalAI compiled with GO_TAGS","type":""}}
```

moreover tho, would it be possible to get `BUILD_TYPE=clblas` supported here as well by say a `with_clblas` maybe?

**Comment by ck3d** [comment]
I used the RFC 169 only for the naming scheme "with_...". I think no CLI tool allows setting these flags. Please change with_tts to true in the Nix expression. But, as defined in the meta set, with_tts is currently broken.

Regarding build type clblas, I update the PR, which allows setting with_clblas.

**Comment by ck3d** [comment]
I
- rebased PR to latest nixos-unstable
- added version test
- fixed cublas build error

for detailed commit view, see https://github.com/ck3d/nix-local-ai/commits/main/

**Comment by ck3d** [comment]
updated to latest version 2.10.0 and got backend stablediffusion build

**Comment by DavHau** [comment]
@ck3d This commit (https://github.com/NixOS/nixpkgs/commit/8f4f4ab6f672ab0483e3fe7ba6a75f4f1772839c) restores some of the original setup.sh buildPhase behavior and enables parallel building. Feel free to cherry-pick.

**Comment by DavHau** [comment]
If i build this package and then execute `local-ai models list`, I get this error:
```
4:37PM ERR unable to load galleries: unexpected end of JSON input
```

**Comment by ck3d** [comment]
I think the list of modules only works when a gallery is provided, see:
https://localai.io/models/

Thanks for the code example. I took it over to my working branch:
https://github.com/ck3d/nix-local-ai/blob/work/local-ai/default.nix#L361

**Review by DavHau — APPROVED** [review]
I can confirm this package works. I was successful in running some local interference via this command:

```command
local-ai --models-path ~/.local/share/localai/models --upload-path /tmp/upload --backend-assets-path /tmp/assets --threads 16  --preload-models '[{"url": "github:go-skynet/model-gallery/mistral.yaml"}]'
```

It would be nice if the default location for all these state directories wouldn't point to the store, but since its easy to fix this by passing the right flags, fixing this is not a requirement to get this merged IMO.

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 291647` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>local-ai</li>
  </ul>
</details>

**Comment by ck3d** [comment]
I created a followup PR #298112  to finish my development on localai.

**Pull request merged**
