### PR TITLE
bsd treewide: Run RFC formatter

### PR DESCRIPTION
**Pull request by Ericson2314**
## Description of changes

There is a lot of BSD work happening lately, including moving things around between various files, so I think this is a good time to enforce the new format. Explicitly:

- We're getting churn either way
- Makes it easier for different people to adopt the same style

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
Look rather uncontroversial; will merge after the CI succeeds.

**Comment by Ericson2314** [comment]
I had wanted to ask the others because I think some things do look worse, but yes I think it is worth it too. Ultimately text is bad, the AST is what matters, and auto-formatting is just a way of "letting go" of what the text looks like.

**Comment by alyssais** [comment]
Is there any reason not to wait for the treewide autoformatting?

**Comment by Ericson2314** [comment]
@alyssais I wanted to run the formatting on this and the version 14 stuff in order to reduce the diff between them. (As opposed to hand revert some things that don't need to change to save for a future PR.)

**Comment by annaleeleaves** [comment]
can add path to check-nix-format.yml workflow https://github.com/NixOS/nixpkgs/blob/e577daf8ba32782c5ef85b5635733902bbf85e53/.github/workflows/check-nix-format.yml#L32-L44

**Comment by alyssais** [comment]
Okay, makes sense.

**Comment by Ericson2314** [comment]
(last commit did not change any nix code, ofborg-eval already passed)

**Pull request merged**
