### PR TITLE
dwm: 6.0 -> 6.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Test builded. I'm not using dwm, so I didn't test.

### CODE REVIEW

**Comment by joachifm** [comment]
No checksum change?

**Comment by matthiasbeyer** [comment]
whoa. Try it yourself... I just re-checked, yes, there is no checksum change... Compiling dwm takes less then two seconds, so feel free to build yourself!

**Comment by joachifm** [comment]
That is odd. Given that at least one file in the source archive contains a version string, I'd expect a different checksum even if nothing else changed between versions.
```
$ wget http://dl.suckless.org/dwm/dwm-6.{0,1}.tar.gz
$ sha256sum *.tar.gz
b2b9483de69259eeea56844899bb2385158d3e79a42d82b10c142099fc8eeb56  dwm-6.0.tar.gz
c2f6c56167f0acdbe3dc37cca9c1a19260c040f2d4800e3529a21ad7cce275fe  dwm-6.1.tar.gz
```

**Comment by joachifm** [comment]
Even odder is that it appears travis is not actually building version 6.1:

```
unpacking source archive /nix/store/s0f8fl3rqg329lwsbmds34zs5sfbwy90-dwm-6.1.tar.gz
source root is dwm-6.0
[...]
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Os -I. -I/usr/include -I/usr/X11R6/include -DVERSION="6.0" -DXINERAMA
```
Note that it says `source root is dwm-6.0` and `-DVERSION="6.0"`.

**Comment by matthiasbeyer** [comment]
Okay, seems it did the same thing locally.

Hash is now updated and new dependency is added. Please test build as well, so we can be sure I didn't mess up again! :-)

**Pull request merged**
