### PR TITLE
rnote: 0.5.16 -> 0.5.17

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/flxzt/rnote/compare/v0.5.16...v0.5.17

Changelog: https://github.com/flxzt/rnote/releases/tag/v0.5.17

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
The Darwin build fails with
```
fatal error: 'AudioUnit/AudioUnit.h' file not found
```
while compiling coreaudio-sys.

**Comment by abathur** [comment]
Built for me (and earlier this afternoon I was able to reproduce the failure you saw):

Result of `nixpkgs-review pr 221519` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rnote</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@abathur Did you try running rnote?

**Comment by abathur** [comment]
I'm not familiar with it, but I did try a `--help`:
 $ rnote --help
Usage:
  rnote [OPTION…]

Help Options:
  -h, --help                 Show help options
  --help-all                 Show all help options
  --help-gapplication        Show GApplication options
  ```

I do still have the review shell open if there's anything specific you'd like me to run.

**Comment by abathur** [comment]
Ah. I guess there may be an issue. 

The first time I ran it bare and it just spun for several seconds and I assumed it just wasn't going to do anything smart without specific input and canceled. I did try it again just now:

```
$ rnote
(rnote:57955): GLib-GIO-ERROR **: 23:39:36.894: Settings schema 'com.github.flxzt.rnote' is not installed
Trace/BPT trap: 5
```

**Comment by dotlambda** [comment]
> ```
> $ rnote
> (rnote:57955): GLib-GIO-ERROR **: 23:39:36.894: Settings schema 'com.github.flxzt.rnote' is not installed
> Trace/BPT trap: 5
> ```

Accoding to https://github.com/flxzt/rnote/blob/7e17354f7c0e0d54cb090ee0cea02be1ce670e2d/misc/building/rnote-macos-build.md#building-and-installing-the-project you have to set `$GSETTINGS_SCHEMA_DIR` manually. But I doubt that's the case for other Gtk apps on macOS.
I also noticed that, unlike on Linux, `$out/share/gsettings-schemas/rnote-0.5.17/glib-2.0/schemas/gschemas.compiled` doesn't exist for the Darwin build.

**Comment by dotlambda** [comment]
> I also noticed that, unlike on Linux, `$out/share/gsettings-schemas/rnote-0.5.17/glib-2.0/schemas/gschemas.compiled` doesn't exist for the Darwin build.

I fixed that by applying https://github.com/flxzt/rnote/pull/569. Can you try again?

**Comment by dotlambda** [comment]
@abathur Thank you!

**Comment by dehesselle** [comment]
> [...] you have to set `$GSETTINGS_SCHEMA_DIR` manually. But I doubt that's the case for other Gtk apps on macOS.

That is absolutely the case for all Gtk apps if you wish to make them relocatable. You do have different options though, e.g. I prefer setting `XDG_DATA_DIRS` instead.

**Comment by dotlambda** [comment]
> That is absolutely the case for all Gtk apps (that use GSettings) if you wish to make them relocatable on macOS.

I see. But apps installed with Nix can't be relocated.

**Pull request merged**
