### PR TITLE
cachix: compose overrides

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/57529

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
cc @domenkozar

**Comment by domenkozar** [comment]
cc @srhb does this address the issue? :) 

Thanks @vaibhavsagar !

**Comment by srhb** [comment]
cc @basvandijk @peti

**Comment by srhb** [comment]
What happens if we simply use `.extend` internally instead? As far as I know, it'll always be there, and as long as we don't export the changed `haskellPackages` to the users, there's no nasty surprise. Does that make sense, or did I forget something here?

**Comment by roberth** [comment]
`extend` picks up the `overrides` as well. sgtm

**Comment by vaibhavsagar** [comment]
Updated!

**Comment by domenkozar** [comment]
I've pushed 4c6be1f00c337e15c176b932deb687221f1c4bf0 as those overrides are not needed anymore. I'll make sure I use `extend` next time. Thank you!

**Pull request closed without merging**
