### PR TITLE
mpfr: 4.1.0 -> 4.1.1

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://www.mpfr.org/mpfr-4.1.0/#fixed

While at it added trivial updater script.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
`julia` regressed: https://hydra.nixos.org/log/pr2mwrbaz0pi2z34li09rgx2064326vw-julia-1.8.3.drv

```
Test Failed at /build/julia-1.8.3/usr/share/julia/stdlib/v1.8/MPFR_jll/test/runtests.jl:7
  Expression: vn == v"4.1.0"
   Evaluated: v"4.1.1" == v"4.1.0"
ERROR: LoadError: Test run finished with errors
```

Proposed possible fix as: https://github.com/NixOS/nixpkgs/pull/203497

**Comment by LunNova** [comment]
This caused a build failure in openscad/cgal.

Looks like there is a patch but not a fixed release. https://github.com/CGAL/cgal/issues/7064

**Comment by trofi** [comment]
Which branch did you observe it in? There was at least cfe4a8d8702a18389e95c81d89c15adf87bc1b40 in `staging` to fix a bit of fallout.

**Comment by LunNova** [comment]
Looks like that hit staging too late, it's failing in nixos-unstable-small

**Comment by trofi** [comment]
I don't know what `stableBranch=false` is https://hydra.nixos.org/jobset/nixos/unstable-small#tabs-configuration. Does it mean  `staging` branch? Grepping `hydra` git repository does not yield any details.

**Comment by LunNova** [comment]
changes pass from master -> nixos-unstable-small -> nixos-unstable as different sets of hydra jobs pass.

If it's broken in nixos-unstable-small it's broken in master.

**Comment by LunNova** [comment]
I guess this has way too many rebuilds to do anything other than wait for the next staging merge.

**Comment by trofi** [comment]
Sounds about right. I can confirm `staging` can build `openscad` successfully and `master` and `staging-next` do fail it the same way.

**Pull request merged**
