### PR TITLE
ldc: 1.10.0 -> 1.11.0, dmd: 2.081.1 -> 2.081.2, dtools: 2.081.1 -> 2.081.2

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Update to latest stable releases.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
The Linux build error can be ignored because there is something wrong with the build machine GrahamcOfBorg is running on.
The problem it's running into is documented in https://github.com/NixOS/nix/issues/2155 and was last seen in https://github.com/NixOS/nixpkgs/pull/44904#issuecomment-413348452

So this is ready to be merged.

**Comment by Mic92** [comment]
While reviewing this I noticed that Literate is broken that was submitted by @RocketPuppy:

```
Linking...
bin/tangle -odir source lit/*.lit
dub build --build=release
Package dmarkdown not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirr
or2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): Couldn't resolve host name on handle D72200
Performing "release" build using dmd for x86_64.
dmarkdown ~master: building configuration "library"...
lit/markdown/source/dmarkdown/markdown.d(820,10): Deprecation: module `std.ascii` is not accessible here, perhaps add `static import std.ascii;`
literate ~master: building configuration "application"...
source/globals.d(19,1): Error: Implicit string concatenation is deprecated, use "Lit: Literate Programming System\x0a" ~ "\x0a" instead
source/globals.d(20,1): Error: Implicit string concatenation is deprecated, use "\x0a" ~ "Usage: lit [options] <inputs>\x0a" instead
source/globals.d(21,1): Error: Implicit string concatenation is deprecated, use "Usage: lit [options] <inputs>\x0a" ~ "\x0a" instead
source/globals.d(22,1): Error: Implicit string concatenation is deprecated, use "\x0a" ~ "Options:\x0a" instead
source/globals.d(23,1): Error: Implicit string concatenation is deprecated, use "Options:\x0a" ~ "--help       -h         Show this help text\x0a" instead
source/globals.d(24,1): Error: Implicit string concatenation is deprecated, use "--help       -h         Show this help text\x0a" ~ "--tangle     -t         Only compile code files\x0a" inste
ad
source/globals.d(25,1): Error: Implicit string concatenation is deprecated, use "--tangle     -t         Only compile code files\x0a" ~ "--weave      -w         Only compile HTML files\x0a" i
nstead
source/globals.d(26,1): Error: Implicit string concatenation is deprecated, use "--weave      -w         Only compile HTML files\x0a" ~ "--no-output  -no        Do not generate any output fil
es\x0a" instead
source/globals.d(27,1): Error: Implicit string concatenation is deprecated, use "--no-output  -no        Do not generate any output files\x0a" ~ "--out-dir    -odir DIR  Put the generated fil
es in DIR\x0a" instead
source/globals.d(28,1): Error: Implicit string concatenation is deprecated, use "--out-dir    -odir DIR  Put the generated files in DIR\x0a" ~ "--compiler   -c         Report compiler errors
(needs @compiler to be defined)\x0a" instead
source/globals.d(29,1): Error: Implicit string concatenation is deprecated, use "--compiler   -c         Report compiler errors (needs @compiler to be defined)\x0a" ~ "--linenums   -l    STR
 Write line numbers prepended with STR to the output file\x0a" instead
source/globals.d(30,1): Error: Implicit string concatenation is deprecated, use "--linenums   -l    STR  Write line numbers prepended with STR to the output file\x0a" ~ "--md-compiler COMPILE
R  Use COMPILER as the markdown compiler instead of the built-in one\x0a" instead
source/globals.d(31,1): Error: Implicit string concatenation is deprecated, use "--md-compiler COMPILER  Use COMPILER as the markdown compiler instead of the built-in one\x0a" ~ "--version
 -v         Show the version number and compiler information" instead
source/weaver.d(299,18): Error: Implicit string concatenation is deprecated, use "<!DOCTYPE html>\x0a" ~ "<html>\x0a" instead
source/weaver.d(300,18): Error: Implicit string concatenation is deprecated, use "<html>\x0a" ~ "<head>\x0a" instead
source/weaver.d(301,18): Error: Implicit string concatenation is deprecated, use "<head>\x0a" ~ "<meta charset=\"utf-8\">\x0a" instead
source/weaver.d(302,18): Error: Implicit string concatenation is deprecated, use "<meta charset=\"utf-8\">\x0a" ~ "<title>" instead
source/weaver.d(307,18): Error: Implicit string concatenation is deprecated, use "</style>\x0a" ~ "</head>\x0a" instead
source/weaver.d(311,15): Error: Implicit string concatenation is deprecated, use "<body onload=\"prettyPrint()\">\x0a" ~ "<section>\x0a" instead
dmd failed with exit code 1.
make: *** [Makefile:3: release] Error 2
builder for '/nix/store/x2i0rsa60hy3199c91jy7j0yd6hy6ckv-Literate-2017-05-28.drv' failed with exit code 2
```

**Comment by ThomasMader** [comment]
> While reviewing this I noticed that Literate is broken that was submitted by @RocketPuppy:

There are only 4 new commits to the repo at https://github.com/zyedidia/Literate/commits/master.
Current Nix package is at https://github.com/zyedidia/Literate/commit/23928d64bb19b5101dbcc794da6119beaf59f679.
The 4 new commits don't seem to be fixing any of the deprecation errors.

@zyedidia Could you please fix the compilation with newest compilers upstream?

**Comment by Mic92** [comment]
We could mark it as broken in the meantime.

**Comment by ThomasMader** [comment]
Yes that's the way to go.

**Comment by Mic92** [comment]
done in https://github.com/NixOS/nixpkgs/commit/bbf5f232e0bf1a7dab8043ea670735fa7e6181a7

**Comment by zyedidia** [comment]
I believe these errors have been fixed with the latest commit to zyedidia/Literate.

**Comment by ThomasMader** [comment]
Yes that fixes the build, thanks.
There are still some deprecation warnings though:

lit/tangle/src/parser.d(212,14): Deprecation: package `std.regex` is not accessible here, perhaps add `static import std.regex;`
lit/tangle/src/util.d(48,25): Deprecation: `parser.matchAll` is not visible from module `util`
lit/tangle/src/util.d(48,45): Deprecation: `parser.regex` is not visible from module `util`
lit/tangle/src/util.d(48,68): Deprecation: `parser.matchAll` is not visible from module `util`
lit/tangle/src/util.d(48,88): Deprecation: `parser.regex` is not visible from module `util`
lit/tangle/src/util.d(50,29): Deprecation: `parser.matchAll` is not visible from module `util`
lit/tangle/src/util.d(50,49): Deprecation: `parser.regex` is not visible from module `util`
lit/tangle/src/util.d(54,41): Deprecation: `parser.canFind` is not visible from module `util`
lit/tangle/src/util.d(54,89): Deprecation: `parser.canFind` is not visible from module `util`
lit/tangle/src/util.d(69,24): Deprecation: `parser.canFind` is not visible from module `util`
lit/tangle/src/util.d(77,31): Deprecation: `parser.canFind` is not visible from module `util`

I might update the package in another PR.

**Pull request merged**
