### PR TITLE
installer: fixup sd-card folder move from #110827

### PR DESCRIPTION
**Pull request by blaggacao**
This is a coverup operation for #110827.

### CODE REVIEW

**Review by mohe2015 — COMMENTED** [review]
Does https://github.com/NixOS/nixpkgs/blob/9710ecf15e5f6e7513894c9e592853f8c8c62196/nixos/modules/installer/sd-card/sd-image-aarch64-new-kernel-installer.nix also need the `installer.cloneConfig`?

**Comment by blaggacao** [comment]
@mohe2015 Thanks, I wast staring to getting confused :smile:

**Comment by blaggacao** [comment]
@roberth Sorry to bother you with a fix-up. I'm somehow not able to do proper tests in my setup (lack of knowledge). But this should be fine(er), now.

**Review by roberth — APPROVED** [review]
Congruent with the docs

> On images where the installation media also becomes an installation target,
  copying over <literal>configuration.nix</literal> should be disabled by
  setting <literal>installer.cloneConfig</literal> to <literal>false</literal>.
  For example, this is done in <literal>sd-image-aarch64.nix</literal>.

**Comment by roberth** [comment]
Progress :rocket:

**Comment by roberth** [comment]
> Progress

Oh wait, I don't mean the Russian progress spacecraft; just celebrating progress here.

**Comment by blaggacao** [comment]
> Congruent with the docs

Actually it wasn't. I forced pushed, [now it is](https://github.com/NixOS/nixpkgs/pull/113944/files#diff-e1840a5d8599b8e0611048b54fba69f6c55832cd82fdf098cd5d8e4e88d409ea).

**Review by mohe2015 — APPROVED** [review]
Just did a short glance but assuming only the requested changes were done, LGTM!

**Pull request merged**
