### PR TITLE
R: 3.6.3 --> 4.0.0 & update packages

### PR DESCRIPTION
**Pull request by jabranham**
###### Motivation for this change
Upstream release. Needed to backport a fix for a test which should be removed next time R gets updated. @peti I also updated the packages from CRAN and bioconductor.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bcdarwin** [comment]
Commit looks OK.

```
1 package marked as broken and skipped:
spark

6 package failed to build:
python37Packages.rpy2 python38Packages.rpy2 rstudio rstudioWrapper sage sageWithDoc
```

I think `rpy2` is already broken and `sage` is probably unrelated.  Any idea about `rstudio`?

**Comment by jabranham** [comment]
No, I'm not an Rstudio user so I'm not very familiar with it. Did you get an error message?

**Comment by bcdarwin** [comment]
It seems like the major version bump may have introduced a breaking change to the R CPP API:

```
[53%] Building CXX object src/cpp/desktop/CMakeFiles/rstudio.dir/DesktopSubMenu.cpp.o
/build/source/src/cpp/r/session/REmbeddedPosix.cpp: In function 'void rstudio::r::session::runEmbeddedR(const rstudio::core::FilePath&, const rstudio::core::FilePath&, bool, bool, SA_TYPE, const rstudio::r::session::Callbacks&, rstudio::r::session::InternalCallbacks*)':
/build/source/src/cpp/r/session/REmbeddedPosix.cpp:107:8: error: 'struct structRstart' has no member named 'R_Slave'
  107 |    Rp->R_Slave = FALSE ;
      |
```

**Comment by jabranham** [comment]
Thanks. I found https://github.com/rstudio/rstudio/pull/6017 which seems geared towards fixing the issue but it was later reverted.

**Comment by bcdarwin** [comment]
Can we just use `fetchpatch` to bring in this commit?  (I don't see where it was reverted.)

**Comment by jabranham** [comment]
Thanks, trying now. It was reverted here: https://github.com/rstudio/rstudio/commit/82599490e75f0d21c89a0fbd3410f1e08fcfceb6 and I'm using what seems to be the replacement: https://github.com/rstudio/rstudio/commit/3fb2397c2f208bb8ace0bbaf269481ccb96b5b20

**Comment by jabranham** [comment]
Rstudio compiled successfully so pushed here

**Comment by bcdarwin** [comment]
Would you also update the comment to describe what this patch is for/when it can be removed?  Otherwise looks good.

**Comment by jabranham** [comment]
Done

**Comment by bcdarwin** [comment]
@GrahamcOfBorg build rstudio rstudioWrapper

**Review by peti — COMMENTED** [review]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates.

**Comment by jabranham** [comment]
Hydra build of R packages looks good to me

**Review by bcdarwin — APPROVED** [review]

**Review by ciil — APPROVED** [review]
RStudio build lgtm as well.

**Pull request merged**
