### PR TITLE
ocamlPackages.xmlm: 1.3.0 -> 1.4.0

### PR DESCRIPTION
**Pull request by superherointj**
ocamlPackages.xmlm: 1.3.0 -> 1.4.0

* fixes license (bsd3 -> isc)

### CODE REVIEW

**Comment by vbgl** [comment]
This seems to require OCaml ≥ 4.03. Please set `minimalOCamlVersion` accordingly.

**Comment by superherointj** [comment]
> This seems to require OCaml ≥ 4.03. Please set `minimalOCamlVersion` accordingly.

I have set to `4.05` to comply with: https://github.com/ocaml/opam-repository/blob/master/packages/xmlm/xmlm.1.4.0/opam#L20

**Comment by vbgl** [comment]
My bad. This derivation does not use `buildDunePackage` so the `minimalOCamlVersion` attribute is ignored. You should leave the test that is already there and raise the lower bound.

**Comment by superherointj** [comment]
> My bad. This derivation does not use `buildDunePackage` so the `minimalOCamlVersion` attribute is ignored. You should leave the test that is already there and raise the lower bound.

Done. The sad part is not noticing it on my own.

**Pull request merged**
