### PR TITLE
python3Packages.msgpack: 1.0.0 -> 1.0.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.0.2

Changelog: https://github.com/msgpack/msgpack-python/blob/master/ChangeLog.rst

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 107350` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>pepper</li>
  </ul>
</details>
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>lexicon</li>
    <li>python37Packages.channels-redis</li>
    <li>python37Packages.datashader</li>
    <li>python37Packages.dftfit</li>
    <li>python37Packages.flower</li>
    <li>python37Packages.hypothesis-auto</li>
    <li>python37Packages.labelbox</li>
    <li>python37Packages.pymatgen-lammps</li>
    <li>python38Packages.channels-redis</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.dftfit</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.hypothesis-auto</li>
    <li>python38Packages.labelbox</li>
    <li>python38Packages.pymatgen-lammps</li>
    <li>python39Packages.channels-redis</li>
    <li>python39Packages.wordfreq</li>
    <li>sourcehut.metasrht</li>
  </ul>
</details>
<details>
  <summary>150 packages built:</summary>
  <ul>
    <li>ansible-lint (python38Packages.ansible-lint)</li>
    <li>archivy</li>
    <li>calibre</li>
    <li>calibre-py2</li>
    <li>cmake-language-server</li>
    <li>cura</li>
    <li>etesync-dav</li>
    <li>gns3-gui</li>
    <li>gns3-server</li>
    <li>gnvim</li>
    <li>matrix-synapse</li>
    <li>mitmproxy (python38Packages.mitmproxy)</li>
    <li>neovim</li>
    <li>neovim-qt</li>
    <li>neovim-remote</li>
    <li>octoprint</li>
    <li>pinnwand</li>
    <li>python37Packages.Pyro4</li>
    <li>python37Packages.alerta-server</li>
    <li>python37Packages.ansible-lint</li>
    <li>python37Packages.aria2p</li>
    <li>python37Packages.backoff</li>
    <li>python37Packages.bravado-core</li>
    <li>python37Packages.cachecontrol</li>
    <li>python37Packages.cachy</li>
    <li>python37Packages.celery</li>
    <li>python37Packages.dask-gateway</li>
    <li>python37Packages.dask-jobqueue</li>
    <li>python37Packages.dask-ml</li>
    <li>python37Packages.dask-mpi</li>
    <li>python37Packages.dask-xgboost</li>
    <li>python37Packages.distributed</li>
    <li>python37Packages.django-raster</li>
    <li>python37Packages.django_redis</li>
    <li>python37Packages.djmail</li>
    <li>python37Packages.etebase</li>
    <li>python37Packages.fluent-logger</li>
    <li>python37Packages.goobook</li>
    <li>python37Packages.influxdb</li>
    <li>python37Packages.influxgraph</li>
    <li>python37Packages.intake</li>
    <li>python37Packages.kombu</li>
    <li>python37Packages.lammps-cython</li>
    <li>python37Packages.mapbox</li>
    <li>python37Packages.mitmproxy</li>
    <li>python37Packages.monty</li>
    <li>python37Packages.msgpack</li>
    <li>python37Packages.msgpack-numpy</li>
    <li>python37Packages.myfitnesspal</li>
    <li>python37Packages.numcodecs</li>
    <li>python37Packages.perfplot</li>
    <li>python37Packages.poetry</li>
    <li>python37Packages.pyairvisual</li>
    <li>python37Packages.pymatgen</li>
    <li>python37Packages.pynvim</li>
    <li>python37Packages.pysnow</li>
    <li>python37Packages.rich</li>
    <li>python37Packages.scikit-bio</li>
    <li>python37Packages.sentry-sdk</li>
    <li>python37Packages.streamz</li>
    <li>python37Packages.stumpy</li>
    <li>python37Packages.sumo</li>
    <li>python37Packages.tinydb</li>
    <li>python37Packages.wled</li>
    <li>python37Packages.wordfreq</li>
    <li>python37Packages.xdg</li>
    <li>python37Packages.zarr</li>
    <li>python37Packages.zerorpc</li>
    <li>python38Packages.Pyro4</li>
    <li>python38Packages.alerta-server</li>
    <li>python38Packages.aria2p</li>
    <li>python38Packages.backoff</li>
    <li>python38Packages.bravado-core</li>
    <li>python38Packages.cachecontrol</li>
    <li>python38Packages.cachy</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.django-raster</li>
    <li>python38Packages.django_redis</li>
    <li>python38Packages.djmail</li>
    <li>python38Packages.etebase</li>
    <li>python38Packages.fluent-logger</li>
    <li>python38Packages.goobook</li>
    <li>python38Packages.influxdb</li>
    <li>python38Packages.influxgraph</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.kombu</li>
    <li>python38Packages.lammps-cython</li>
    <li>python38Packages.mapbox</li>
    <li>python38Packages.monty</li>
    <li>python38Packages.msgpack</li>
    <li>python38Packages.msgpack-numpy</li>
    <li>python38Packages.myfitnesspal</li>
    <li>python38Packages.numcodecs</li>
    <li>python38Packages.perfplot</li>
    <li>python38Packages.poetry</li>
    <li>python38Packages.pyairvisual</li>
    <li>python38Packages.pymatgen</li>
    <li>python38Packages.pynvim</li>
    <li>python38Packages.pysnow</li>
    <li>python38Packages.rich</li>
    <li>python38Packages.scikit-bio</li>
    <li>python38Packages.sentry-sdk</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.sumo</li>
    <li>python38Packages.tinydb</li>
    <li>python38Packages.wled</li>
    <li>python38Packages.wordfreq</li>
    <li>python38Packages.xdg</li>
    <li>python38Packages.zarr</li>
    <li>python38Packages.zerorpc</li>
    <li>python39Packages.Pyro4</li>
    <li>python39Packages.bravado-core</li>
    <li>python39Packages.cachecontrol</li>
    <li>python39Packages.cachy</li>
    <li>python39Packages.django_redis</li>
    <li>python39Packages.etebase</li>
    <li>python39Packages.fluent-logger</li>
    <li>python39Packages.influxdb</li>
    <li>python39Packages.influxgraph</li>
    <li>python39Packages.kombu</li>
    <li>python39Packages.mapbox</li>
    <li>python39Packages.mitmproxy</li>
    <li>python39Packages.monty</li>
    <li>python39Packages.msgpack</li>
    <li>python39Packages.msgpack-numpy</li>
    <li>python39Packages.numcodecs</li>
    <li>python39Packages.pynvim</li>
    <li>python39Packages.zarr</li>
    <li>python39Packages.zerorpc</li>
    <li>salt</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>tebreak</li>
    <li>termpdfpy</li>
    <li>vimPlugins.sved</li>
    <li>zeronet</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Depends on #107390

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.msgpack

**Comment by prusnak** [comment]
Failing packages from review also fail on the master. LGTM

**Pull request merged**
