### PR TITLE
ocamlformat: 0.20.0 and 0.20.1

### PR DESCRIPTION
**Pull request by rgrinberg**
###### Motivation for this change

To include ocamlformat 0.20.0 and 0.20.1 in nixpkgs

###### Things done

Added the mentioned packages and upgraded odoc-parser and ocaml-version to allow for this.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rgrinberg** [comment]
cc @vbgl

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlformat_0_20_0

**Review by vbgl — CHANGES_REQUESTED** [review]
`ocamlformat_0_20_0` fails to build.

**Comment by rgrinberg** [comment]
Good catch. I fixed the 0.20.0 build.

Rudi.

**Comment by rgrinberg** [comment]
gentle ping @vbgl

**Comment by vbgl** [comment]
The second before last commit (https://github.com/NixOS/nixpkgs/pull/152199/commits/70d44a70864ec2f0bac8c21a2270f04ff8c22ac6) is broken but fixed by the next one. Do you want to squash these two changes together or may I squash the whole PR into a single patch?

**Comment by rgrinberg** [comment]
Feel free to squash everything. The separate commits are only to make it easy for reviewers.

**Pull request merged**
