### PR TITLE
awscli2: 2.0.26 -> 2.0.36

### PR DESCRIPTION
**Pull request by davegallant**
###### Motivation for this change

- API changes
- bugfix for `s3 cp`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by endgame — APPROVED** [review]
Tested by running `nix-build -A awscli2 https://github.com/davegallant/nixpkgs/archive/5e11e57c61cd9af4d9d8db62ded55bf948fcc4cb.tar.gz` and then running a couple of commands against my AWS account.

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 94635` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- awscli2
</details>

**Comment by davegallant** [comment]
> Result of `nixpkgs-review pr 94635` [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> - awscli2

Fixed the constraint on the [cryptography](https://pypi.org/project/cryptography/#history) package.

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 94635` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- awscli2
</details>

**Review by bhipple — APPROVED** [review]

**Pull request merged**
