### PR TITLE
Update jetbrains IDEs

### PR DESCRIPTION
**Pull request by dritter**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 223149` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jetbrains.goland</li>
  </ul>
</details>

**Review by Alizter — APPROVED** [review]

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 223149` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Comment by stepech** [comment]
CLion 2023.1 works without flaws!

**Comment by siph** [comment]
Intellij CE working fine on `x86_64-linux`.

**Comment by stepech** [comment]
Datagrip works well on x86_64-linux too.

**Review by fabianhjr — APPROVED** [review]
Tested IDEA 2023.1, have a weird glitch around creating new projects from existing sources otherwise works fine.

**Review by stepech — APPROVED** [review]

**Comment by dev-null-undefined** [comment]
I am not sure if it works, but @stepech told me that I should say: "It works on my machine" so here I am.

**Comment by dev-null-undefined** [comment]
Result of `nixpkgs-review pr 223149` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Review by dev-null-undefined — APPROVED** [review]
LGTM!

**Comment by SuperSandro2000** [comment]
Please follow the [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes) when naming your commits.

**Comment by fabianhjr** [comment]
Seems like historically these has used a `jetbrains: [update-msg]` format

```
commit e1fa54a56982c5874f6941703c8b760541e40db1

    jetbrains: build and minor version updates

commit f6aa4144d0c38231d8c383facf40f63b13759bb5

    jetbrains: 2022.3.2 -> 2022.3.3

commit 8476f94720f51ee030a8bc9cb3fbae31f12ba979

    update jetbrains IDEs

commit 40ef3bb63d4b6cf66aeb8468a0e8349cbc5aa5ca


    jetbrains: update

commit 8c46c7ae2397286f1b3a0fd8fe0af4aef19800e9

    jetbrains.gateway: Switch to release channel

commit 52ac262ebd702efe00031e5ce84f2f5d63c5b2d0

    jetbrains.idea-ultimate: Update download link

commit 26534bf9fd519240cca86c49394e6a137b920a71

    jetbrains: update to latest release
```

**Comment by dritter** [comment]
@SuperSandro2000 I fixed the commit message.

@fabianhjr Yes, this package has not the best commit messages. I guess this is because it is not a single product, but multiple ones. Hence, it is not always easy to find a good commit message. In this case most of the products switched from 2022.3 to 2023.1 (as Jetbrains - the company - follows a quarterly release cycle), but goland went from 2022.3.3 to 2022.3.4.. It would be easier if we create one PR per product, but that would lead to a lot of new PRs.

@SuperSandro2000 @fabianhjr Would a commit message `jetbrains: update` (without version number) be ok?

**Pull request merged**
