### PR TITLE
zulip: 4.0.0 -> 5.0.0

### PR DESCRIPTION
**Pull request by alevy**
###### Motivation for this change

Zulip 5.0 fixes multiple security issues <https://blog.zulip.org/2020/04/01/zulip-desktop-5-0-0-security-release/>

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alevy** [comment]
FYI, I was not able to run `nix path-info -S` without an error (I'm sure I'm invoking it incorrectly), and  `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` dropped me into a nix-shell with a bunch of files I didn't know how to make left and right of.

I'm happy to try to complete these tests, but just wasn't able to find documentation on them

**Review by jonafato — APPROVED** [review]
Ran `zulip` via `nixpkgs-review`. The app launches and seems to work just fine.

**Comment by alevy** [comment]
Is there more to the process for this to be merged? Or just waiting for some sort of roll-up?

**Comment by ryantm** [comment]
- [x] built on NixOS
- [x] nix-review passed
- [x] tested basic help messages of all binaries
- [x] leaf package
- [x] checked OfBorg all green

**Pull request merged**
