### PR TITLE
pango: support cross-compilation by disabling docs and introspection

### PR DESCRIPTION
**Pull request by Mindavi**
###### Motivation for this change

Support cross-compilation for pango. One step further towards getting sway (and other things depending on pango) cross-compiling.

It disables some features, but we can't get around that for now. Cross-compiling gobject-introspection is not yet supported.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS (for aarch64-multiplatform)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]
Looks good. I assume gi-docgen fails for the same reasons as in https://github.com/NixOS/nixpkgs/pull/123927.

**Comment by Mindavi** [comment]
Yes, gi-docgen indeed fails for the same reason as that other PR. I guess that's worth looking into at some point, but I think it's not _that_ big of a deal to miss some documentation when cross-compiling -- for now.

**Comment by Mindavi** [comment]
Can this go through?

**Pull request merged**
