### PR TITLE
Pantheon: prepare for meson 0.61

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

I am not sure whether upstream will make some release for these fixes before elementary OS 7 so I opened this just to make sure if someone wants to bump meson, it won't break Pantheon. To build Pantheon with meson 0.61, apply [this patch](https://gist.github.com/bobby285271/078f88b6f9f9ba85bd68ff942f82d5a2) on top of this PR.

Packages mostly fails with "Function does not take positional arguments" when using meson 0.61. As what upstream change says, `i18n.merge_file` has been ignoring positional arguments for a time and explicitly rejects with error since meson 0.61, and actually this has been marked as deprecated in 0.60. So it is still a good idea to fetch these fixes in advance.

To make sure at least nixosTests.pantheon passes:

- [x] https://github.com/elementary/screenshot/commit/80a5d942e813dd098e1ef0f6629b81d2ccef05ae
- [x] https://github.com/elementary/capnet-assist/commit/0e77bf8023ba1b35e3a5badb72c246cabf6552b9
- [x] https://github.com/elementary/files/commit/28428fbda905ece59d3427a3a40e986fdf71a916
- [x] https://github.com/elementary/camera/commit/ead143b7e3246c5fa9bb37c95d491fb07cea9e04
- [x] https://github.com/elementary/code/commit/a2607cce3a6b1bb62d02456456d3cbc3c6530bb0
- [x] https://github.com/elementary/mail/commit/bbadc56529276d8e0ff98e9df7d9bb1bf8fc5783
- [x] https://github.com/elementary/music/commit/fb3d840049c1e2e0bf8fdddea378a2db647dd096
- [x] https://github.com/elementary/terminal/commit/15e3ace08cb25e53941249fa1ee680a1e2f871b4
- [x] https://github.com/elementary/switchboard/commit/ecf2a6c42122946cc84150f6927ef69c1f67c909
- [x] https://github.com/elementary/greeter/commit/a4b25244058fce794a9f13f6b22a8ff7735ebde9
- [x] https://github.com/elementary/shortcut-overlay/commit/130f78eb4b7770586ea98ba0a5fdbbf5bb116f3f

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by bobby285271** [comment]
I am still testing this, to build Pantheon with meson 0.61, apply https://gist.github.com/bobby285271/078f88b6f9f9ba85bd68ff942f82d5a2 on top of this PR.

**Comment by NickCao** [comment]
With one last patch applied on elementary-screenshot, the test passed.

**Comment by bobby285271** [comment]
@ofborg test pantheon
@ofborg build pantheon.elementary-music pantheon.elementary-camera pantheon.elementary-mail pantheon.elementary-terminal pantheon.elementary-shortcut-overlay pantheon.elementary-code pantheon.elementary-greeter pantheon.switchboard pantheon.elementary-capnet-assist pantheon.elementary-files pantheon.elementary-screenshot

**Pull request merged**
