### PR TITLE
gitignore: add .envrc

### PR DESCRIPTION
**Pull request by psydvl**
###### Motivation for this change
`direnv` provide some useful things which may be stored in `.envrc`

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
Maybe we should have a standard `.envrc` in Nixpkgs.
What's in yours, @psydvl?

cc @zimbatm

**Comment by psydvl** [comment]
I have a small one file: 
``` "console"
export NIXPKGS_GIT=$PWD
```

And using it like this: `nix-shell -I nixpkgs=$NIXPKGS_GIT -p programToTest`
So, mine, probably, not best to start
Also, I think each maintainer may have different values for packages in their interest

**Comment by zimbatm** [comment]
mine looks like this:
```sh
export NIX_PATH=nixpkgs=$PWD/nixpkgs
export GITHUB_TOKEN=<redacted>
export GITHUB_AUTH=zimbatm:$GITHUB_TOKEN
```

**Comment by roberth** [comment]
> ```shell
> export NIX_PATH=nixpkgs=$PWD/nixpkgs
> ```

I care most about that line. I specify it manually sometimes, with `-I nixpkgs=`, but that's a pain.

I suppose there may be some variability and personal preferences in the rest of the file. Perhaps we could source an optional `.envrc.local` file for personal purposes, which we do gitignore?

I'd also like to have `nixpkgs-fmt` in there by default, but it's unclear where it should come from, as the one in nixpkgs itself is subject to all changes you make to the nixpkgs project, which may not be buildable at all stages. We should probably leave nix-shell-like functionality out of scope.

@psydvl Sorry for scope-jacking your PR, but perhaps you'll be happy to know that you can also add non-committed ignores in `.git/info/exclude`

**Comment by Lassulus** [comment]
So should we merge or close this?

**Comment by roberth** [comment]
The problem is already solvable with non-committed ignore rules in `.git/info/exclude` or user-level ignore rules.

There's nothing to do here and an actual envrc would be better to put in a new PR.

**Pull request closed without merging**
