### PR TITLE
pwgen_secure: fix missing words.txt

### LINKED ISSUE #161552: pwgen-secure fails to find its word list
### Describe the bug
```bash
$ spwgen -d w
Debug mode enabled. Verbosity = 11
Arguments:
{'-a': False,
 '-d': True,
 '-n': None,
 '-t': False,
 '-v': 0,
 '<class-option>': None,
 '<class>': 'w'}
Password count: 1
Generating passphrase
Traceback (most recent call last):
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/bin/.spwgen-wrapped", line 123, in <module>
    r.render_password()
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 361, in render_password
    passwords.append(self.generate_password())
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 352, in generate_password
    return self.generate_pass_phrase()
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 323, in generate_pass_phrase
    with open(word_list_path) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/words.txt'
```

### Steps To Reproduce
1. Install `pwgen-secure` nixpkgs pkg from nixpkgs rev `74b10859829153d5c5d50f7c77b86763759e8654` or later.
2. Invoke `pwgen-secure w` in terminal.

### Expected behavior
For the tool to output a password (read: passphrase) of words.

### Additional context
```bash
$ tree -I *.pyc /nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure
/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure
├── fileRandomizer.py
├── __init__.py
├── __pycache__
├── rpg.py
└── search_space_calculator.py
```

### Notify maintainers
@peterhoeg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Fixes #161552

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by x10an14** [comment]
I'm unable to help test this bugfix =/ This is the only way I know how to test such PRs:
```bash
nix run github:peterhoeg/nixpkgs/f/pwgen_secure#spwgen w
error: cannot find flake attribute 'github:peterhoeg/nixpkgs/f/pwgen_secure#spwgen'
```

This is how I've helped testing #157907, if you've got another equally simple/flaked way, please let me know!

Hypothesis: It's because of your `f/` branch prefix?

**Comment by LunNova** [comment]
@x10an14 try 'github:nixos/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen`. That's the commit hash at the HEAD of the PR branch, you can get it on the commits tab.

**Comment by LunNova** [comment]
@peterhoeg Could also add missing meta.mainProgram attribute so that `nix run nixpkgs#pwgen-secure` starts the right bin.

**Comment by x10an14** [comment]
> @LunNova: github:nixos/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen

Nice, thanks! =D Didn't think of that, d'uh.

> @LunNova:  edit: That's not the problem, spwgen isn't the right attr. It's at pwgen-secure.

Not sure if we're looking at the same package then?
```bash
[2022-02-24 23:09:57] 1 x10an14@home-desktop:~
-> $ pwgen-secure
pwgen-secure: command not found
[2022-02-24 23:10:01] 127 x10an14@home-desktop:~
-> $ nix-locate --top-level spwgen
pwgen-secure.out                                  5,493 x /nix/store/kjbmkx9n0rxf7sggzy3rk12rc36aab4d-pwgen-secure-0.9.1/bin/.spwgen-wrapped
pwgen-secure.out                                    367 x /nix/store/kjbmkx9n0rxf7sggzy3rk12rc36aab4d-pwgen-secure-0.9.1/bin/spwgen
[2022-02-24 23:10:26] 0 x10an14@home-desktop:~
-> $ type -a pwgen-secure
bash: type: pwgen-secure: not found
[2022-02-24 23:10:33] 1 x10an14@home-desktop:~
-> $ type -a spwgen
spwgen is /home/x10an14/.nix-profile/bin/spwgen
spwgen is /run/current-system/sw/bin/spwgen
[2022-02-24 23:10:38] 0 x10an14@home-desktop:~
-> $ spwgen --help
usage: spwgen [ -v ... ] [options] <class> [<class-option>]

options:
    -v          Be verbose.
    -d          Debug mode. Same as -vvvvvvvvvvv
    -t          Show how long it took to generate that password.
    -n=<count>  Generate n passwords.
    -a          Show strength analysis of the generated password

classes:
(....)
```

**Comment by x10an14** [comment]
I think this pretty much settles it that it's `spwgen` I believe we're supposed to use:
https://github.com/mjmunger/pwgen_secure/blob/master/spwgen.py#L3

That repo certainly matches the nixpkg's source =)
https://github.com/NixOS/nixpkgs/pull/161585/files#diff-204286d476a0729ddd56a9bae79a43f5420198bb6c452b21da8227f36d0df63eR16

**Comment by x10an14** [comment]
> > @LunNova: github:nixos/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen
> 
> Nice, thanks! =D Didn't think of that, d'uh.

Hmm... can't get it to work =/
```
[2022-02-24 23:14:44] 0 x10an14@home-desktop:~
-> $ nix run github:peterhoeg/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen w
error: cannot find flake attribute 'github:peterhoeg/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen'
[2022-02-24 23:15:27] 1 x10an14@home-desktop:~
-> $ nix run github:nixos/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen
error: cannot find flake attribute 'github:nixos/nixpkgs/5a91b5d84bb1ca505d0503dc3d06bc3e7307368c#spwgen'
[2022-02-24 23:16:24] 1 x10an14@home-desktop:~
-> $
```

**Comment by LunNova** [comment]
The binary is called `spwgen`. The path/attribute name of the package is `pwgen-secure`.

This so the path is `/nix/store/path-to-pwgen-secure/bin/spwgen`.

Because the meta.mainProgram attribute isn't set, you can't use nix run. You can however use `nix shell`.

```
$ nix run pkgs#pwgen-secure
error: unable to execute '/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/bin/pwgen-secure': No such file or directory
$ nix shell nixpkgs#pwgen-secure -c spwgen                                                       
usage: spwgen [ -v ... ] [options] <class> [<class-option>]
```

**Comment by peterhoeg** [comment]
I'll squash and merge when you confirm all is OK @x10an14

**Review by x10an14 — APPROVED** [review]
Never got the `nix run` syntax to work, but @LunNova gave a nice tip with the `nix shell` syntax.

So below is a test I believe shows it worked on my PC too! (As it should, since it's Nix):
```
[2022-02-25 16:38:45] 1 x10an14@home-desktop:~
-> $ nix run github:peterhoeg/nixpkgs/f1b5163b50b431c1c10970f7c7c9264be9fac970#spwgen w
error: cannot find flake attribute 'github:peterhoeg/nixpkgs/f1b5163b50b431c1c10970f7c7c9264be9fac970#spwgen'
[2022-02-25 16:39:09] 1 x10an14@home-desktop:~
-> $ nix run github:peterhoeg/nixpkgs/f/pwgen_secure#spwgen w
error: cannot find flake attribute 'github:peterhoeg/nixpkgs/f/pwgen_secure#spwgen'
[2022-02-25 16:40:27] 1 x10an14@home-desktop:~
-> $ nix shell github:peterhoeg/nixpkgs/f1b5163b50b431c1c10970f7c7c9264be9fac970
error: flake 'github:peterhoeg/nixpkgs/f1b5163b50b431c1c10970f7c7c9264be9fac970' does not provide attribute 'packages.x86_64-linux.defaultPackage.x86_64-linux', 'legacyPackages.x86_64-linux.defaultPackage.x86_64-linux' or 'defaultPackage.x86_64-linux'
[2022-02-25 16:41:24] 1 x10an14@home-desktop:~
-> $ nix shell github:peterhoeg/nixpkgs/f1b5163b50b431c1c10970f7c7c9264be9fac970#pwgen-secure
[2022-02-25 16:41:41] 0 x10an14@home-desktop:~
-> $ type -a spwgen
spwgen is /nix/store/qixa6wy5ahdr0m7bm3rx0i73xcx9zfzd-pwgen-secure-0.9.1/bin/spwgen
spwgen is /home/x10an14/.nix-profile/bin/spwgen
spwgen is /run/current-system/sw/bin/spwgen
[2022-02-25 16:41:47] 0 x10an14@home-desktop:~
-> $ spwgen w
deligation clench-built paraphoniac twofer bullionism nasillate Vorlage tendersome Non-baptist atomically arthrorrhagia diastaltic vibraharpist Antimasonic Sheri Hejazi
[2022-02-25 16:41:52] 0 x10an14@home-desktop:~
-> $ spwgen w
stalkiness trunkfuls doesn't miffing self-governed missyllabifying approbator Beauvoir myelin Opulaster Pharbitis myelomere nirvana duennas throwbacks esothyropexy
[2022-02-25 16:41:54] 0 x10an14@home-desktop:~
-> $
exit
[2022-02-25 16:41:57] 0 x10an14@home-desktop:~
-> $ spwgen w
Traceback (most recent call last):
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/bin/.spwgen-wrapped", line 123, in <module>
    r.render_password()
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 361, in render_password
    passwords.append(self.generate_password())
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 352, in generate_password
    return self.generate_pass_phrase()
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 323, in generate_pass_phrase
    with open(word_list_path) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/words.txt'
[2022-02-25 16:42:02] 1 x10an14@home-desktop:~
-> $
```

**Pull request merged**
