### PR TITLE
dolphin-emu-{beta,primehack}: cleanup

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Description of changes

Cleanups `dolphin-emu-beta` and `dolphin-emu-beta` by removing useless dependencies and adding some that would otherwise be bundled (not all of them are packaged on nixpkgs).
Briefly tested by playing a game, with Vulkan and a Bluetooth gamepad.

Some questions:

- Should all Darwin stuff stay there? Dolphin has been marked broken on it for 4 years.
-  On `primehack.nix` there is one dependency per line. Should I do the same on `master.nix`? (And maybe reordering it too?)
- Should I also remove `-DENABLE_LTO=ON`?
- Finally, I changed the way that "DISTRIBUTOR" ([this thing](https://github.com/dolphin-emu/dolphin/blob/master/CMakeLists.txt#L37)) is set. Since I'm ignorant of CMake, does it work? (Taken from the AUR)

EDIT: Not updating anymore because of #180608.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sugar700 — COMMENTED** [review]
Please update the commit title to mention `16793` rather than `16792`.

Otherwise, this change appears to work fine, I got one segfault when starting a game, but it did not occur on later attempts, so I have no idea what's up with that.

I think `-DDISTRIBUTOR=NixOS` is fine, albeit I have no real way of testing whether this works because all it does is affect telemetry, and there is no preview of submitted telemetry in an emulator.

**Comment by SuperSamus** [comment]
Is there anything left to do for this to be merged?

**Comment by xfix** [comment]
You may want to change the version numbers in commit description from 16380 to 5.0-16380 to be more accurate. This isn't version 16380, it's version 5.0-16380.

**Comment by SuperSamus** [comment]
Tested briefly PrimeHack (Prime 1 from Prime Trilogy), it seems it's running fine.

**Review by sugar700 — APPROVED** [review]
Didn't test primehack, otherwise looks fine.

**Comment by SuperSamus** [comment]
Is there anything else to do for this to be merged?

**Pull request closed without merging**
