### PR TITLE
WIP: Hatchling backport

### LINKED ISSUE #171447: Hatchling backport
I cannot use hatchling as part of `poetry2nix` from nixos-21.11, because it's only in nixpkgs-unstable.
Is there any chance it could be backported?

The question came from here: https://github.com/nix-community/poetry2nix/issues/605

### PR DESCRIPTION
**Pull request by NorfairKing**
###### Description of changes

This is an attempt to backport to fix https://github.com/NixOS/nixpkgs/issues/171447#issuecomment-1117260205

I cherry-picked all the commits in the history of hatchling from here:
https://github.com/NixOS/nixpkgs/commits/235eee5537f37bbc721cd120b6c0fa66bfe763e4/pkgs/development/python-modules/hatchling/default.nix

I haven't been able to figure out whether this will work. Would like to make this PR a draft but I can't figure out how.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arianvp** [comment]
Perhaps it's due to https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging ?

**Comment by NorfairKing** [comment]
@arianvp Oh gosh I'm so sorry. It must be because I've changed the base branch after creating the PR.
I guess closing this PR won't really help with the notifications now..

**Comment by NorfairKing** [comment]
https://pastebin.com/0JjBWFk1
@SuperSandro2000 It looks like this doesn't "Just work".
Shall we give up on this or try anything else?

**Comment by arianvp** [comment]
I'm going to pre-emptively close this to stop the accidental maintainer spam. let's open up a new pr

**Comment by NorfairKing** [comment]
@arianvp we can keep it closed, this didn't look like it was going to work anyway :)

**Pull request closed without merging**
