### PR TITLE
nodejs-10_x: remove 

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
https://endoflife.date/nodejs

###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Wasn't there something about kibana 6 being the last version under a foss license?

**Comment by ajs124** [comment]
So?

**Comment by aaronjheng** [comment]
Related to https://github.com/NixOS/nixpkgs/issues/173449

**Comment by Mic92** [comment]
If someone wants an old kibana, they can use an old nixpkgs revision.

**Comment by dotlambda** [comment]
This breaks Nixpkgs evaluation if aliases are disabled:
```
$ rg nodejs-10_x
pkgs/top-level/aliases.nix
939:  nodejs-10_x = throw "nodejs-10_X has been removed. Use a newer version instead."; # Added 2022-05-31

pkgs/servers/web-apps/cryptpad/generate.sh
9:nix-shell -I nixpkgs=../../../.. -p '(nodePackages.override { nodejs = nodejs-10_x; }).bower2nix' --run "bower2nix $cryptpadSrc/bower.json bower-packages.nix"

pkgs/applications/networking/cluster/spacegun/node-composition.nix
5:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-10_x"}:

pkgs/misc/base16-builder/node-packages.nix
5:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-10_x"}:

pkgs/tools/networking/airfield/node.nix
5:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-10_x"}:
```

**Pull request merged**
