### PR TITLE
[staging] tzdata: 2019c -> 2020c

### PR DESCRIPTION
**Pull request by ajs124**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]
LGTM.

**Comment by ajs124** [comment]
Release notes: https://mm.icann.org/pipermail/tz-announce/2020-October/000059.html

**Comment by ajs124** [comment]
https://mm.icann.org/pipermail/tz-announce/2020-October/000060.html

**Comment by ajs124** [comment]
Perfect timing, [2020d](https://mm.icann.org/pipermail/tz-announce/2020-October/000062.html) just got released.

Then again, it only moves DST in Palestine around by a week. Assuming we have any users in that timezone, they'll probably just have to live with that.

**Comment by mweinelt** [comment]
Let's just do the update and not assume where our users are.

**Pull request merged**
