### PR TITLE
miracle-wm: init at 0.3.0

### LINKED ISSUE #303476: Package request: miracle-wm
**Project description**

A Mir-based Wayland compositor like [Miriway](https://github.com/Miriway/Miriway), but tiling instead of floating.

image

More Mir testers, more better. Requesting this from *myself* so I don't forget about this. Needs a very new Mir, newer than we currently provide (depends on https://github.com/NixOS/nixpkgs/pull/270760).

**Metadata**

* homepage URL: https://github.com/mattkae/miracle-wm
* source URL: https://github.com/mattkae/miracle-wm
* license: gpl3+
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by OPNA2608**
## Description of changes

Closes #303476

Bildschirmfoto_2024-06-10_16-19-46

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by OPNA2608** [comment]
aarch64 VM test fails, but so does our miriway one since the mir 2.15 -> 2.17 bump (will trigger a run here to show). Still debugging this, but current miriway works fine on actual hardware so I think this should be *okay*.

@ofborg build miriway miriway.passthru.tests

**Comment by OPNA2608** [comment]
VM failures are due to a mesa bug in llvmpipe: https://github.com/canonical/mir/issues/3442#issuecomment-2195785722

**Comment by JohnRTitor** [comment]
> VM failures are due to a mesa bug in llvmpipe: [canonical/mir#3442 (comment)](https://github.com/canonical/mir/issues/3442#issuecomment-2195785722)

Can we backport that patch for Mesa in nixpkgs?

**Comment by OPNA2608** [comment]
Not sure if it makes sense to go through the process of an entire staging cycle for this. Considering how frequent mesa releases are, maybe we should just ask them for a backport to 24.1 (in case that's not already being backported, iunno how they handle such things) and wait for the next bump to get the usual merge into staging?

**Review by JohnRTitor — COMMENTED** [review]
Looks like 24.0.4 made it to master and I am not inclined to hold this back any longer, unless there is a reason to :) @OPNA2608

**Comment by OPNA2608** [comment]
Test works on aarch64 now. :partying_face:

**Pull request merged**
