### PR TITLE
lp_solve: fixed build error due to defining isnan

### PR DESCRIPTION
**Pull request by taku0**
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Fixes #14037.

cc: @joachifm @vcunat @zimbatm

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks. Is the source containing another tarball ? I don't really understand what' going on with the double unpacking.

**Comment by taku0** [comment]
This package does not use standard `setup.nix` for some reason, so it unpacks the tarball manually in `buildCommand`.

**Comment by joachifm** [comment]
I'm not competent to comment on the fix here. But, I wonder, if you're already touching this, perhaps you could 1. change the src url to use  a mirror and 2. fixup the description (removing the package name).

If you're not keen on doing those, I'm fine with taking this as-is, if it works for you.

**Comment by taku0** [comment]
Updated.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
