### PR TITLE
 ceph: Fix kmod/modprobe path 

### PR DESCRIPTION
**Pull request by covert8**
###### Description of changes
~~- Update Ceph to 17.5.2~~
- Fix kmod path 
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
Please align the commit messages with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md)

**Comment by name-snrl** [comment]
Hello, I opened a PR to upgrade ceph to version 17.2.5. #206396

I tried to build your version but you made a typo in the version value (17.5.2 instead of 17.2.5) so nix can't even load the source code. I suggest to leave in your PR only the changes concerning kmod

**Comment by covert8** [comment]
> Hello, I opened a PR to upgrade ceph to version 17.2.5. #206396
> 
> I tried to build your version but you made a typo in the version value (17.5.2 instead of 17.2.5) so nix can't even load the source code. I suggest to leave in your PR only the changes concerning kmod

Cheers will do.

**Comment by covert8** [comment]
> Please align the commit messages with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md)

Is the current commit message sufficient?

**Comment by thomaslepoix** [comment]
Hello, would it not be better to make the modprobe's path available to ceph by adding `kmod` as a dependency (through `buildInputs` I guess) instead of hardcoding its path in the source code?

**Comment by covert8** [comment]
> Hello, would it not be better to make the modprobe's path available to ceph by adding `kmod` as a dependency (through `buildInputs` I guess) instead of hardcoding its path in the source code?

Yes it would. Pr has been updated

**Comment by edwtjo** [comment]
Please get rid of the merge commit and rebase onto the merged 18.2.0 expression

**Comment by trevorriles** [comment]
Is this just waiting on a rebase? I would love to see this get merged.

**Comment by covert8** [comment]
done

**Comment by trevorriles** [comment]
Looks like this was fixed in https://github.com/NixOS/nixpkgs/pull/270444

**Pull request closed without merging**
