### PR TITLE
raspberry pi 4 updates - eeprom, fw, armstubs, linux-rpi

### PR DESCRIPTION
**Pull request by colemickens**
###### Motivation for this change

I think I need to update the linux-rpi kernel as well, to match the firmware update.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
Sometimes I really with the rpi folks made it just a bit easier to consume their work: https://github.com/raspberrypi/linux/issues/4819

**Comment by colemickens** [comment]
I don't know why the CI is failing, these sha256 have been reconfirmed, that's what I get locally. Something odd is up maybe.

**Comment by colemickens** [comment]
@ofborg rerun

**Comment by colemickens** [comment]
Weird, the foundation kernel doesn't boot when going from u-boot -> grub -> kernel:

```
[    0.000000] CPU: 0 PID: 0 Comm: swapper Not tainted 5.10.89 #1-NixOS                                          
[    0.000000] Hardware name: Raspberry Pi 4 Model B Rev 1.1 (DT)                                                
[    0.000000] pstate: 80000085 (Nzcv daIf -PAN -UAO -TCO BTYPE=--)                                              
[    0.000000] pc : kthread_should_stop+0x20/0x48                                                                
[    0.000000] lr : add_hwgenerator_randomness+0x4c/0x140                                                        
[    0.000000] sp : ffffffe159ca3d90                                                                             
[    0.000000] x29: ffffffe159ca3d90 x28: 0000000014117380                                                       
[    0.000000] x27: 000000002386f040 x26: fffffffefe4bc050                                                       
[    0.000000] x25: 0000000000000018 x24: 0000000000000040                                                       
[    0.000000] x23: fffffffefe4fc044 x22: 0000000000000200                                                       
[    0.000000] x21: ffffffe159cb7c40 x20: fffffffefe4fc040                                                       
[    0.000000] x19: ffffffe159cb3178 x18: 0000000000000020                                                       
[    0.000000] x17: 0000000000001400 x16: 0000000000001c00                                                       
[    0.000000] x15: ffffffe159cb8190 x14: 52455345524d454d                                                       
[    0.000000] x13: 2030343030373833 x12: 3278303d474e5220                                                       
[    0.000000] x11: ffffffe159d473e0 x10: ffffffe159d2f3a0                                                       
[    0.000000] x9 : ffffffe159d2f3f8 x8 : 0000000000017fe8                                                       
[    0.000000] x7 : c0000000ffffefff x6 : 0000000000000001                                                       
[    0.000000] x5 : 0000000000000000 x4 : 0000000000000000                                                       
[    0.000000] x3 : 0000000000000001 x2 : 0000000000000000                                                       
[    0.000000] x1 : 0000000000200000 x0 : 0000000000000000                                                       
[    0.000000] Call trace:                                                                                       
[    0.000000]  kthread_should_stop+0x20/0x48                                                                    
[    0.000000]  add_bootloader_randomness+0x20/0x30                                                              
[    0.000000]  efi_config_parse_tables+0x148/0x270                                                              
[    0.000000]  efi_init+0x174/0x24c                                                                             
[    0.000000]  setup_arch+0x260/0x630                                                                           
[    0.000000]  start_kernel+0x98/0x574                                                                          
[    0.000000] Code: d503233f 36a800c1 f9431000 d50323bf (f9400000)                                              
[    0.000000] random: get_random_bytes called from print_oops_end_marker+0x34/0x60 with crng_init=1             
[    0.000000] ---[ end trace affd80da8a5899f8 ]---                                                              
[    0.000000] Kernel panic - not syncing: Attempted to kill the idle task!                                      
[    0.000000] ---[ end Kernel panic - not syncing: Attempted to kill the idle task! ]---   
```

**Comment by colemickens** [comment]
Okay, I think the kernel is fine:

```
Linux rpifour1 5.10.89 #1-NixOS SMP Tue Jan 1 00:00:00 UTC 1980 aarch64 GNU/Linux                                                                             
```

When I boot via tow-boot -> extlinux, it's fine.

**Comment by colemickens** [comment]
@ofborg eval

**Comment by zhaofengli** [comment]
Could you cherry-pick the missing updates and Pi Zero 2 W-related commits from #156005, or should I do the opposite from my PR?

**Comment by colemickens** [comment]
I think I'd prefer to merge yours and then rebase mine, especially since I'm toying with the idea of trying to write a script to update these similar to how I do updates in nixpkgs-wayland.

**Pull request closed without merging**
