### PR TITLE
tree-wide: unify Bash completions outputs

### PR DESCRIPTION
**Pull request by zimbatm**
Use `$out/share/bash-completion/completions` to store Bash completions

###### Motivation for this change

Unify the outputs. Some derivations were outputting the completions in `$out/etc/bash_completion.d` for example.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

--- Packages building ---

* [x] gammu
* [x] prevo-tools
* [x] todo-txt-cli
* [x] gitAndTools.git-bug
* [x] gitAndTools.git-stree
* [x] gitAndTools.git
* [x] gitAndTools.top-git
* [x] purescript
* [x] backblaze-b2
* [ ] ceph-client - was already broken
* [x] trace-cmd
* [x] awscli
* [x] awscli2
* [x] google-cloud-sdk
* [x] tarsnap
* [x] btrfs-progs
* [x] yandex-disk
* [x] gibo
* [x] powerline-rs
* [x] pass.extensions.pass-import
* [x] pass.extensions.pass-update
* [x] awsebcli
* [x] nixos-container
* [x] perlPackages.AppClusterSSH

### CODE REVIEW

**Comment by zimbatm** [comment]
Once this has been merged, I will use nix-locate to find the reminding ones. And then finally add a postInstall check so that the convention gets enforced.

**Comment by zimbatm** [comment]
Replaced by https://github.com/NixOS/nixpkgs/pull/103421 that targets staging.

**Comment by flokli** [comment]
I don't understand https://github.com/NixOS/nixpkgs/pull/103315#event-3982817319 - did this mean it was merged to master or not?

**Comment by marsam** [comment]
I didn't merge it, I guess the github ui is buggy.

**Comment by zimbatm** [comment]
I think it's a bug. It happened when I pushed the merge-base between staging and master.

**Pull request merged**
