### PR TITLE
add cross-compilation support for go compiler

### PR DESCRIPTION
**Pull request by cstrahan**
This adds cross-compilation support to the Go compiler.

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@cstrahan ?

**Comment by 7c6f434c** [comment]
@cstrahan So? Or is there another solution committed by now?

**Comment by jcumming** [comment]
@cstrahan ping?

**Comment by cstrahan** [comment]
I tried applying the changes to our Go 1.4, but it fails on the first cross-compiler:

```
# Building packages and commands for darwin/386.
runtime
errors
sync/atomic
unicode
unicode/utf8
math
sort
encoding
unicode/utf16
container/list
crypto/subtle
runtime/cgo
container/ring
image/color
sync
runtime/race
container/heap
image/color/palette
io
syscall
hash
crypto/cipher
hash/crc32
crypto/hmac
hash/adler32
hash/crc64
hash/fnv
# runtime/cgo
In file included from /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/include/features.h:389:0,
                 from /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/include/errno.h:28,
                 from runtime/cgo/cgo.go:46:
/nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
```

I don't know why this stopped working, nor how to pull in a 32-bit glibc. If someone can lend a hand here, I can wrap this up and merge it.

On the other hand, Go 1.5 (supposedly) supports cross compilation by default, and since we have Go 1.5, I don't see how cross-compilation is important for Go 1.4 - unless someone actually has a use case for it. So, I'm of the opinion that we should just close this PR.

Thoughts?

**Comment by jagajaga** [comment]
Any further ideas? :(

**Comment by cstrahan** [comment]
I *think* this is resolved, thanks to the latest Go releases; closing.

**Pull request closed without merging**
