### PR TITLE
hledger_1_29_2: fix dependency toward hledger-lib

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Description of changes

hledger version X always depends on hledger-lib version X.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sternenseemann — CHANGES_REQUESTED** [review]
hackage-packages.nix is generated and will be rolled back.

Such changes need to be implemented using an override in one of the overlays applied to the package set.

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 233623` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by DamienCassou** [comment]
I think we should merge that quickly to be on time for the release. If nobody reviews, I will just merge.

**Comment by sternenseemann** [comment]
@ofborg build haskellPackages.hledger_1_29_2

**Review by sternenseemann — APPROVED** [review]

**Comment by sternenseemann** [comment]
Can you target haskell-updates? For 23.05 a backport is required anyways.

**Comment by DamienCassou** [comment]
> Can you target haskell-updates? For 23.05 a backport is required anyways.

I changed the target branch. Anything else I should do?

**Pull request merged**
