### PR TITLE
zed-editor: 0.137.6 -> 0.138.6

### PR DESCRIPTION
**Pull request by Mic92**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jansol** [comment]
There are several issues with the current upstream desktop file generation: zed-industries/zed#12707

**Comment by jansol** [comment]
Also, the upstream desktop file is referring to the binary from the `cli` package, which is currently not getting built. We'll need to build both the `cli` and `zed` packages, but buildRustPackage currently does not support that. I see two options for this: either update `buildRustPackage` with a list of targets to build (it already passes the `--package` flag to cargo) or split this derivation into two derivations that share the same source and are both dependencies of a metapackage, say `zed-editor -> {zed-editor-gui, zed-editor-cli}`.

**Comment by Mic92** [comment]
> There are several issues with the current upstream desktop file generation: [zed-industries/zed#12707](https://github.com/zed-industries/zed/issues/12707)

Ok. But this does not look like regression from what we currently have:

This is what the old file was:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Zed
GenericName=Text Editor
Comment=A high-performance, multiplayer code editor.
TryExec=zed
StartupNotify=true
Exec=zed
Icon=zed
Categories=TextEditor;Development;IDE;
Keywords=zed;
MimeType=text/plain;inode/directory;
```

And the new zed desktop file seems to be the same

```
 [Desktop Entry]
 Version=1.0
 Type=Application
 Name=Zed
 GenericName=Text Editor
 Comment=A high-performance, multiplayer code editor.
 TryExec=zed
 StartupNotify=true
 Exec=zed 
 Icon=zed
 Categories=Utility;TextEditor;Development;IDE;
 Keywords=zed;
 MimeType=text/plain;inode/directory;
```

I would like to limit the scope on updating zed and not fixing upstream bugs.

**Comment by Mic92** [comment]
> Also, the upstream desktop file is referring to the binary from the `cli` package, which is currently not getting built. We'll need to build both the `cli` and `zed` packages, but buildRustPackage currently does not support that. I see two options for this: either update `buildRustPackage` with a list of targets to build (it already passes the `--package` flag to cargo) or split this derivation into two derivations that share the same source and are both dependencies of a metapackage, say `zed-editor -> {zed-editor-gui, zed-editor-cli}`.

Maybe someone else can work on this....

**Pull request closed without merging**
