### PR TITLE
btrfs-dedupe: remove broken and abandoned package

### PR DESCRIPTION
**Pull request by bhipple**
This package was last released in 2017, and no longer compiles with the latest
Rust compiler. It has just 1 commit from someone other than the original author
and appears to be a dead project.

ZHF: https://github.com/NixOS/nixpkgs/issues/80379

Also removes a legacy cargo fetcher call for https://github.com/NixOS/nixpkgs/issues/79975

### CODE REVIEW

**Comment by marsam** [comment]
cc: @ikervagyok

**Comment by ikervagyok** [comment]
please have a look at this as well: https://github.com/NixOS/nixpkgs/pull/67705

**Comment by bhipple** [comment]
Usually, the release notes are mainly targeted towards NixOS modules and big packages within. Since this has been broken for 1+ years and is clearly abandoned upstream, I doubt anyone's really using it and we can probably just nuke it without even leaving an alias behind.  What do you think?

**Comment by ikervagyok** [comment]
wanted to do that forever, then i got sidetracked - go for it ;)

**Comment by ikervagyok** [comment]
to clarify: you can either drop a note in the release notes or not, since as you said, it's broken beyond repair.
the alias is also more or less useless, so if it's needed you can copy that stuff, otherwise leave it as is and just remove the package...

**Comment by bhipple** [comment]
Ok, I'd say we go for no alias and no release notes, for this particular one, since it's so clear no one has used this for 1+ years.  In the unlikely event someone is disrupted, they'd need to run `git log` anyways to find a historical checkout of NixPkgs where this still built.

**Comment by bhipple** [comment]
@marsam mind giving this (and the ZFH 20.03 backport) a merge?

**Comment by marsam** [comment]
Sorry for the delay. Backported to 20.03 in https://github.com/NixOS/nixpkgs/commit/e4844bd69d1

**Pull request merged**
