### PR TITLE
Fix channel blockers for Rust 1.80

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

Rust 1.80.0 contains a major unfixable compilation [regression](https://github.com/rust-lang/rust/issues/127343) that affects all but recent versions of the widely-used "time" crate.  This is going to impact a lot of Rust software in Nixpkgs.  In this PR, I've focused on identifying packages that would block the channels if we updated to Rust 1.80 without updating them.  I can't yet confirm that this is an exhaustive list, but I don't think it's far off.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by flokli** [comment]
Ack on the nsncd change.

**Comment by picnoir** [comment]
I'm not 100% sure this is fixed on Nsncd. See https://github.com/twosigma/nsncd/issues/117#issuecomment-2267504568 and https://github.com/srd424/nsncd/actions/runs/10235189099/job/28315666470#step:6:83 .

That's a lot to rebuild, I'll wait for hydra to rebuild everything. I'll fix that upstream if the issue is still here.

**Comment by alyssais** [comment]
Hmm, I thought I built it with 1.80, but it's of course possible I could have made a mistake!

**Comment by picnoir** [comment]
Okay, I get it. The 1.4.1 release dates from May 2023 and do not contain the latest network fixes we pushed late 2023. 1.4.1 can be considered as broken for NixOS. We did a rollback here.

However, 1.4.1 do not depend on time yet (through the term crate).

I'll fix that tonight and ask upstream to cut a new release.

**Comment by alyssais** [comment]
Oh no, I must have missed the year!

**Comment by picnoir** [comment]
No worries, mistakes happen. This one is on us: we should cut out a new release.

**Comment by picnoir** [comment]
Upstream issue: https://github.com/twosigma/nsncd/issues/118

**Pull request merged**
