### PR TITLE
Cardinal: 22.12 -> 23.02

### LINKED ISSUE #222223: Update request: cardinal v22.12 → v23.02
- Package name: cardinal
- Latest released version: [v23.02](https://github.com/DISTRHO/Cardinal/releases/tag/23.02)
- Current version on the unstable channel: v22.12
- Current version on the stable/release channel: v22.10

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@magnetophon 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by magnetophon**
###### Description of changes

To test using real jack, just run ``Cardinal``.
If you use pipewire, use this function:
```bash
function unwrap { "$(dirname $(realpath "$(which $1)"))/.$1-wrapped"; }
```
and run ``unwrap Cardinal``.

Any ideas on how to make it work on both?
I guess I could make a wrapper that tests if we are running jack or pipewire, but that feels hacky, and I have no idea how it would affect nixpkgs users outside of NixOS.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

closes https://github.com/NixOS/nixpkgs/issues/222223

### CODE REVIEW

**Comment by PowerUser64** [comment]
Tested with ardour and bespokesynth, as well as standalone cardinal. Everything works fine except for the lv2 plugins, but that doesn't bother me too much and I'm pretty sure they weren't working before. It would be nice if the lv2 plugins worked, but otherwise, looks good to me!

**Comment by PowerUser64** [comment]
Oh, also, I noticed the new Mini variant isn't showing up in Ardour. Not sure why, seems like it should be there.

**Comment by magnetophon** [comment]
@PowerUser64 Thanks for testing.

The LV2 works here, always has, afaik.
Could you investigate if it's an issue with your setup or an issue with the pkg?

The missing mini is a known issue and has been fixed for the next release: https://github.com/DISTRHO/Cardinal/issues/528

**Review by PowerUser64 — APPROVED** [review]
LGTM!

I tested the LV2 version in a different plugin host than I did before and it worked fine.

**Pull request merged**
