### PR TITLE
cudatext: 1.169.2 → 1.170.5, fix build

### PR DESCRIPTION
**Pull request by sikmir**
###### Description of changes
Fix build: https://hydra.nixos.org/build/190390354

Fix build error:
```
/build/source/app/formmain_py_api.inc(264,16) Error: (5038) identifier idents no member "AddHTMLTagListForValidation"
```
`AddHTMLTagListForValidation` added in https://github.com/Alexey-T/Emmet-Pascal/commit/ffe7a1a4bfdd0605dc90549790142069c1971338, so Emmet-Pascal update is required.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Is this a manual edit or updated via `update.sh`? Has this been reported upstream?

**Comment by sikmir** [comment]
> Is this a manual edit or updated via `update.sh`? Has this been reported upstream?

There is nothing to report, upstream doesn't pin exact versions of dependencies, but uses latest ones. In this case Cudatext 1.169.2 requires Emmet-Pascal 2022.08.28 and doesn't compile with 2022.01.17. I guess the reason is that 2022.08.28 tag created after 1.169.2 release, so `update.sh` not updated it.

**Comment by onny** [comment]
> > Is this a manual edit or updated via `update.sh`? Has this been reported upstream?
> 
> There is nothing to report, upstream doesn't pin exact versions of dependencies, but uses latest ones. In this case Cudatext 1.169.2 requires Emmet-Pascal 2022.08.28 and doesn't compile with 2022.01.17. I guess the reason is that 2022.08.28 tag created after 1.169.2 release, so `update.sh` not updated it.

So if `update.sh` is run again this change will be reverted?

**Comment by sikmir** [comment]
> So if `update.sh` is run again this change will be reverted?

No, `update.sh` will not update dependencies if there is no new CudaText release.

**Comment by sikmir** [comment]
1.170.0 is just released.

**Comment by onny** [comment]
Result of `nixpkgs-review pr 189229` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>cudatext (cudatext-qt)</li>
    <li>cudatext-gtk</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Pull request merged**
