### PR TITLE
apparmor: 2.12.0 -> 2.13.1

### PR DESCRIPTION
**Pull request by joachifm**
Mass rebuild via systemd et al.

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg eval

**Comment by joachifm** [comment]
@GrahamcOfBorg build systemd apparmor-parser

**Comment by joachifm** [comment]
@GrahamcOfBorg build systemd apparmor-parser

**Comment by joachifm** [comment]
@vcunat could this be included in the next batch of staging changes? I expect it to be safe, judging by the changelog.

**Comment by vcunat** [comment]
We use [staging-next](https://github.com/NixOS/rfcs/pull/26), so merges to staging don't need to be batched.

**Pull request merged**
