### PR TITLE
cuda: make cudatoolkit & cudnn packages overrideable

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

I currently need to override some aspects of a specific cudatoolkit and cudnn packages. The current mechanism doesn't allow overriding any of the dependencies. By adding a `cudaPackages` and `cudnnPackages` attribute we are at least able to override the inputs of those packages and pick packages from the resulting attribute set as needed.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by knedlsepp** [comment]
I'm interested in how you would now override stuff. Maybe a short example in the commit message?

**Comment by andir** [comment]
> I'm interested in how you would now override stuff. Maybe a short example in the commit message?

What I've done in a local repo today was:

```nix
{
  nixpkgs.overlays = [
    (self: super: { inherit (super.callPackage (super.path + "/pkgs/…/cudatoolkit") {
        addOpenGLRunpath = …;
     }) cudatoolkit_10; })
  ];
}
```

The probably ugliest part about this is that `super.path` has to be used and I've to re-import the package definition. Ideally each of the derivations would allow overriding.

Instead of the above `super.path` hack you can now do:

```nix
{
  nixpkgs.overlays = [
    (self: super: { inherit (super.cudatoolkitPackages.override {
        addOpenGLRunpath = …;
     }) cudatoolkit_10; })
  ];
}
```

Ideally we would be able to override each package. That is something I will work on in the next days once the more pressuring work has been done.

**Comment by andir** [comment]
@knedlsepp I did the overridable changes for cudaPackages. Does that look good to you? I am going to do the same for cudnn as soon as you confirm that it is okay-ish :)

**Comment by gilligan** [comment]
That's useful! LGTM

**Comment by andir** [comment]
Looking at cudnn it actually looks fine already. I am merging this in as it.

**Comment by eadwu** [comment]
Getting a build error
```
builder for '/nix/store/88l0mjgisahp4qrpymwm5nzal07iykdz-cudatoolkit-10.1.243.drv' failed with exit code 1; last 3 log lines:
  unpacking sources
  Creating directory pkg
  /nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 1301: cd: pkg/run_files: No such file or directory
```

**Comment by knedlsepp** [comment]
Just saw that also. All the conditionals were removed from the file. I'm sorry that I didn't review this PR before.

**Comment by andir** [comment]
Thanks. I am sorry. I just pushed a revert: 464ff0aa2436d38ab0c4efe2daccaccab21678df

Will look into the issue now and open another PR.

**Comment by andir** [comment]
Looks like I lost a few changes during the rebase. I have an updated branch and will open a PR once the local builds are successful.

**Comment by knedlsepp** [comment]
Thank you! 👍

**Pull request merged**
