### PR TITLE
networkmanager: 1.10.0 -> 1.10.2, update users

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

http://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/NEWS?h=1.10.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Trying to reduce the number of open PR's I have, let's wait on this until there's a motivation for the bump.

**Review by orivej — APPROVED** [review]

**Comment by orivej** [comment]
The CFLAGS fixes may be forgotten if the update happens in another PR.

The amount of the rebuilt packages allows this to be merged to master.

**Comment by dtzWill** [comment]
@adisbladis committed most of this in 405e53ab711cb7abf96332a458082478f3d03836, other than the update to `networkmanagerapplet` (which is probably a good idea but seems to not be strictly required).  Not sure if independent, hopefully not since that would be silly waste of (minor) effort :).

If not, check PR's please! :3.

Either way, suppose this can be closed now!

**Comment by adisbladis** [comment]
@dtzWill Sorry for not checking open PRs :/

Cherry picked `networkmanagerapplet` in 15aa4fcf753994c8a22f3ff09bb98d0934c5f288

**Pull request closed without merging**
