### PR TITLE
qemu: 3.1.0 -> 4.0.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://lists.gnu.org/archive/html/qemu-devel/2019-04/msg03851.html

Middle of rebuild, haven't tried this yet --
hopefully we only need to remove any patches no longer needed
and lots of testing :).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alyssais** [comment]
I've successfully built this locally on Darwin fyi

**Comment by dtzWill** [comment]
aarch64 failure unrelated (dependency), this seems good to go from my standpoint.  Thoughts?

**Review by andir — APPROVED** [review]
Looks good to me.

Ran a few nixos tests and an Ubuntu 18.04 VM with this branch :+1:.

(On NixOS / x86-64)

**Comment by volth** [comment]
@GrahamcOfBorg build qemu

**Comment by volth** [comment]
@GrahamcOfBorg build pkgsCross.armv7l-hf-multiplatform.qemu

**Comment by ar1a** [comment]
any update? keen for the new version!

**Comment by Chiiruno** [comment]
Still working on this?
Would love to enjoy the upgrades!

**Comment by dtzWill** [comment]
LGTM (x86_64 as well), and if no one has any objections I'll merge this later today, if no one beats me to it ;).

**Pull request merged**
