### PR TITLE
Revert "xonsh: set dontWrapPythonPrograms"

### LINKED ISSUE #301444: Xonsh no longer start
### Describe the bug
After a recent `nixos-unstable` update, xonsh is no longer able to launch.

```
Traceback (most recent call last):
  File "/nix/store/ghr6zvrvjcww884wrcj0pimmpjs2kx61-xonsh-0.15.1/bin/xonsh", line 5, in <module>
    from xonsh.main import main
ModuleNotFoundError: No module named 'xonsh'
```

### Steps To Reproduce
Launch `xonsh`

### Expected behavior
Xonsh should start without issue

### Additional context
I've found a change of python env that reached `nixos-unstable` recently (https://github.com/NixOS/nixpkgs/pull/297628). Perhaps it is the change that breaks xonsh.

### Notify maintainers
@AndersonTorres 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22-xanmod1, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SamLukeYes**
This reverts commit b6403710df19244480866612437f434601491311.

## Description of changes

A quick fix that resolves https://github.com/NixOS/nixpkgs/issues/301444

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SamLukeYes** [comment]
It shouldn't be necessary tho -- why do we need to re-introduce wrappers to xonsh-unwrapped :confused:

**Comment by LordGrimmauld** [comment]
running into this myself. Sadly the unwrapped xonsh isn't available by itself so overriding `dontWrapPythonPrograms = false` in an overlay is bothersome. Ideally xonsh-unwrapped would be available as a package itself....

The reason xonsh is wrapped in the first place os https://github.com/NixOS/nixpkgs/pull/240246, providing a way to add extra python packages that can be imported. The base package was pretty much kept without major changes that would allow it to not be wrapped at all.

**Comment by FlyingWombat** [comment]
> Sadly the unwrapped xonsh isn't available by itself so overriding...

Agreed, xonsh wrapper needs re-work. Since xonsh-unwrapped is unavailable, I can't build my own version from git in an overlay, only by editing nixpkgs.

**Comment by FlyingWombat** [comment]
This changes builds and works for me.

**Review by LordGrimmauld — APPROVED** [review]
Fix is needed. Seeing as you were the one removing the wrapping, i see no issue with you putting it back. But eventually xonsh-unwrapped should be available by itself and maybe less hacky too...

**Review by wineee — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Likely this is caused by #297628

**Pull request merged**
