### PR TITLE
haskellPackages: unbreak bloodhound

### PR DESCRIPTION
**Pull request by TristanCacqueray**
###### Description of changes

Unbreak bloodhound as it seems to build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Hi, first time contributor, please let me know if something is missing :)

**Comment by expipiplus1** [comment]
Welcome!

Seem that a dependency, `quickcheck-arbitrary-template` is still broken (requiring a template haskell version too old). 

This is the upstream issue: https://github.com/plow-technologies/quickcheck-arbitrary-template/issues/10

**Comment by TristanCacqueray** [comment]
Oh thanks, thus I built using dontCheck. I see that this is not exclusive to broken package, so can we just drop the change in configuration-common.nix?

**Comment by expipiplus1** [comment]
Yeah, sounds good to me.

**Comment by Artturin** [comment]
@ofborg build haskellPackages.bloodhound

**Pull request merged**
