### PR TITLE
llvm: 3.7.0 -> 3.7.1

### PR DESCRIPTION
**Pull request by globin**
This obsoletes a backport for rust.

### CODE REVIEW

**Comment by vcunat** [comment]
The rebuild impact is nontrivial due to mesa, so I think it might be better to go through staging. I tested noveau against 3.7.1 yesterday, so it probably won't introduce new mesa problems even though it won't solve [some other one](https://github.com/NixOS/nixpkgs/pull/11367#issuecomment-169450819).

**Comment by globin** [comment]
Shall I open a new PR targeting staging? Or can you just merge into staging and close this?

**Comment by vcunat** [comment]
No need to open another one.

**Comment by vcunat** [comment]
Pushed to staging.

**Pull request closed without merging**
