### PR TITLE
python310Packages.shapely: 1.8.4 -> 2.0.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
https://shapely.readthedocs.io/en/latest/release/2.x.html#version-2-0-0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cpcloud** [comment]
Can you run nixpkgs-review?.

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 207410` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages marked as broken and skipped:</summary>
  <ul>
    <li>easyocr</li>
    <li>flatcam</li>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.descartes</li>
    <li>python310Packages.easyocr</li>
    <li>python310Packages.mask-rcnn</li>
    <li>python310Packages.opensfm</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.wrf-python</li>
    <li>python39Packages.bsuite</li>
    <li>python39Packages.descartes</li>
    <li>python39Packages.easyocr</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.opensfm</li>
    <li>python39Packages.rlax</li>
    <li>python39Packages.wrf-python</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.osmnx</li>
    <li>python39Packages.osmnx</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>mapproxy</li>
    <li>pgcli (python310Packages.pgcli)</li>
    <li>python310Packages.aplpy</li>
    <li>python310Packages.asf-search</li>
    <li>python310Packages.basemap</li>
    <li>python310Packages.cartopy</li>
    <li>python310Packages.flask-admin</li>
    <li>python310Packages.geoalchemy2</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.labelbox</li>
    <li>python310Packages.owslib</li>
    <li>python310Packages.pgspecial</li>
    <li>python310Packages.plotnine</li>
    <li>python310Packages.preprocess-cancellation</li>
    <li>python310Packages.psycopg</li>
    <li>python310Packages.pyosmium</li>
    <li>python310Packages.pyproj</li>
    <li>python310Packages.rasterio</li>
    <li>python310Packages.shapely</li>
    <li>python310Packages.spectral-cube</li>
    <li>python310Packages.wktutils</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.asf-search</li>
    <li>python39Packages.basemap</li>
    <li>python39Packages.cartopy</li>
    <li>python39Packages.flask-admin</li>
    <li>python39Packages.geoalchemy2</li>
    <li>python39Packages.geopandas</li>
    <li>python39Packages.labelbox</li>
    <li>python39Packages.owslib</li>
    <li>python39Packages.pgcli</li>
    <li>python39Packages.pgspecial</li>
    <li>python39Packages.plotnine</li>
    <li>python39Packages.preprocess-cancellation</li>
    <li>python39Packages.psycopg</li>
    <li>python39Packages.pyosmium</li>
    <li>python39Packages.pyproj</li>
    <li>python39Packages.rasterio</li>
    <li>python39Packages.shapely</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.wktutils</li>
  </ul>
</details>

**Comment by tjni** [comment]
`osmnx` is getting ready for a new release which will support `shapely` 2.0.

**Comment by dotlambda** [comment]
> `osmnx` is getting ready for a new release which will support `shapely` 2.0.

The osmnx bump will have to wait for a pandas bump. See #207463.

**Comment by risicle** [comment]
@ofborg build python310Packages.pgcli

Trouble building on macos 10.15

**Comment by risicle** [comment]
Must be a quirk on my machine.

Other than `osmnx`, `nixpkgs-review` reveals no new failures on macos 10.15 & nixos x86_64.

**Pull request merged**
