### PR TITLE
pylint: 2.13.5 -> 2.13.8

### PR DESCRIPTION
**Pull request by totoroot**
###### Description of changes

Update pylint from 2.13.5 to 2.13.8
Update astroid from 2.11.2 to 2.11.4 (tested compatibility with pylint)
Add top-level package reference for pylint
Add longDescription with included commands (pyreverse, epylint and symilar)
Disable failing tests on x86_64-darwin. Enable formerly non-working tests.
Add myself as maintainer (totoroot)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by totoroot** [comment]
@fabaff Could you review please

**Comment by totoroot** [comment]
> Should target staging https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

Thanks, @Artturin! I followed the guide and updated the PR.

**Comment by mweinelt** [comment]
I'm reluctant to accept another update to pylint/astroid before the branch off, since they can be quite problematic.

**Comment by mweinelt** [comment]
Yes, these are totally fine.

**Comment by dotlambda** [comment]
Most of the commit messages should start with `python3Packages.`

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by mweinelt** [comment]
@SuperSandro2000 Approving the changes with my veto on the version bumps, not sure what point you're trying to make.

**Comment by SuperSandro2000** [comment]
We can merge it as is after the branch off.

**Comment by mweinelt** [comment]
We can merge parts of it before the branch off.

**Comment by SuperSandro2000** [comment]
#172087

**Comment by totoroot** [comment]
Closing this as newer version was merged with PR #175773 and @SuperSandro2000 is now maintaining the package

**Pull request closed without merging**
