### PR TITLE
gitlab-runner: 14.5.2 -> 14.6.0

### PR DESCRIPTION
**Pull request by max-wittig**
###### Motivation for this change

https://gitlab.com/gitlab-org/gitlab-runner/blob/v14.6.0/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

/cc @bachp @zimbatm @globin @dlouzan

### CODE REVIEW

**Comment by bachp** [comment]
@max-wittig The shell patch doesn't apply anymore when I try to build it.

**Comment by max-wittig** [comment]
@bachp makes sense. Patch removed.

**Comment by yu-re-ka** [comment]
This broke the gitlab-runner build, as the other patch doesn't apply either. Please revert or fix the patch.

**Comment by zimbatm** [comment]
Reverted for now. I should have run `nixpkgs-review` on the PR before merging.

**Comment by max-wittig** [comment]
Is there a way to build just one package and test it? Or do you always need to build the whole os?

**Pull request merged**
