### PR TITLE
[20.09] Update step certificates and cli #124347

### PR DESCRIPTION
**Pull request by mohe2015**
###### Motivation for this change
Manually backport #124347 as there *could* be security updates.

###### Things done
I failed to use dep2nix and it seems to not work with go modules anyways so I changed to the approach of the current master.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124594` at a90b738d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>step-ca</li>
    <li>step-cli</li>
  </ul>
</details>

**Comment by mohe2015** [comment]
@SuperSandro2000 Should i also add a reference to the backported commits and is so how exactly. Because these are created completely manually so there are not simple cherry-picks.

**Comment by risicle** [comment]
I personally wouldn't bother.

**Comment by risicle** [comment]
`nixpkgs-review` happy for me, macos 10.15, nixos x86_64.

**Pull request merged**
