### PR TITLE
mesa: 21.1.5 -> 21.2.0

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg test sway

**Comment by alyssais** [comment]
> 2021-08-06T16:27:24.1544621Z ##[error]fatal: couldn't find remote ref refs/pull/132914/merge

editorconfig failure seems to be spurious.

**Comment by maxeaubrey** [comment]
Not an expert in mesa, but considering that every `.0` release has a "this is a development release" notice, maybe it'd be better if we bumped to `21.1.6` until `21.2.1` becomes available, as suggested by upstream? While I'm keen to stay on latest for many things on my own systems, I don't love the idea of bumping everyone to a dev release :sweat_smile:

**Comment by alyssais** [comment]
Hi, I'm not sure it's a development release?

What the announcement says is:

> As usual, this is a .0 release, and those of
> you seeking stability over features likely want to wait 2 weeks for
> 21.2.1.

That sounds fine for unstable nixpkgs imo.

But since it seems that @primeos is already taking care of it and has made a different call, I'm happy to defer to them.

**Comment by maxeaubrey** [comment]
The language in the changelog is a bit different, which is what I was going by:

> Mesa 21.2.0 is a new development release. People who are concerned with stability and reliability should stick with a previous release or wait for Mesa 21.2.1.

**Pull request closed without merging**
