### PR TITLE
appimage: replace radare2+jq with readelf+awk+sha256sum

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

radare2 does not play nicely with filenames containing spaces: https://github.com/radareorg/radare2/issues/16958

so I replaced radare2+jq with readelf+awk+sha256sum

I also cleaned up default.nix with nixpkgs-fmt and removed bashisms from appimage-exec.sh

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Pacman99** [comment]
I tried to build some appimage packages from your code and I get `readelf: command not found`
I don't know why that would happen, since it looks like binutils is in the path for the appimage-exec.sh. Maybe it's called wrong or needs to be included as a input somewhere.

I'm just curious about the problem your solving, when would the existing radare based code fail? Would it happen from spaces in the name of the appimage or package name or something else?

**Comment by prusnak** [comment]
> when would the existing radare based code fail?

$ appimage-run "Any Filename With Spaces.AppImage"
sha256 = "aab46b385ff90486013b44e719e12f4f351dbe125d7a3124569b9fba3bbfd9b8";
Cannot find 'elf_header' format.

**Comment by prusnak** [comment]
> I don't know why that would happen, since it looks like binutils is in the path for the appimage-exec.sh. 

Is the issue fixed when you replace `binutils` with `binutils-unwrapped` in the `default.nix`?

**Comment by Pacman99** [comment]
> Is the issue fixed when you replace `binutils` with `binutils-unwrapped` in the `default.nix`?
Yup works perfectly now.

And I tested all of my appimage packages and they work perfectly. The PR is perfect with the change.

**Comment by prusnak** [comment]
Changed `binutils` to `binutils-unwrapped` in 56ec381dad348ae63b8aca09d403a555093de598

**Review by Mic92 — APPROVED** [review]
I very much prefer that. radare2 has quite frequent releases, which I need to test and sometimes break the API.

**Pull request merged**
