### PR TITLE
ansible: 2.7.6 -> 2.8.0

### PR DESCRIPTION
**Pull request by gabibbo97**
###### Motivation for this change

Update ansible

###### Things done

Updated Ansible to 2.8.0

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
commit msg version is incorrect. Does it build with the current versions of botocore and such?

**Comment by costrouc** [comment]
Also this file will need to be updated as well to reflect the new version. https://github.com/costrouc/nixpkgs/blob/master/pkgs/tools/admin/ansible/default.nix

**Comment by gabibbo97** [comment]
Hello, I have updated the pkgs/tools/admin/ansible/default.nix file

**Comment by marsam** [comment]
I took the liberty to bump it to `2.8.1`, I hope you don't mind
@GrahamcOfBorg build ansible_2_6 ansible_2_7 ansible

**Comment by marsam** [comment]
Tested locally on darwin and NixOS
Thanks @gabibbo97! btw feel free to ping me if any PR gets stuck :)

**Pull request merged**
