### PR TITLE
wire-desktop: init at 3.0.2816

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by davidak** [comment]
I'm a Wire user and had to use the browser version on NixOS, so i'm very happy about this PR.
Thanks for your contribution!

It also builds successfully on my system, but something weird is going on with the text:
untitled
(I'm using Xfce)

**Comment by davidak** [comment]
It would also be cleaner to "compile from source" than extracting the deb file. But i think it's ok for now, so people can actually use it and that can be improved later.

**Comment by worldofpeace** [comment]
@davidak 
> I'm a Wire user and had to use the browser version on NixOS, so i'm very happy about this PR.
Thanks for your contribution!

I actually couldn't believe nix didn't have this package :).

> It would also be cleaner to "compile from source" than extracting the deb file. But i think it's ok for now

I think so too.

> It also builds successfully on my system, but something weird is going on with the text:

Might be missing a dependency. I'm using gnome and it has a similar yet more subtle distortion.
the


> Also, i'm not able to login, either with e-mail or username.

I can log in?

**Comment by davidak** [comment]
I think emoji support is quiet important for a chat app.

I stall cant login with username or e-mail, only phone number.

And i don't see notifications.

**Comment by worldofpeace** [comment]
I'll have all that in sec. 

I have no idea what's up with the font's though.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build

**Comment by worldofpeace** [comment]
@GrahamcOfBorg  eval

**Comment by antonsamoziv** [comment]
@GrahamcOfBorg build wire-desktop

**Comment by davidak** [comment]
Still login problems.

When i set wire to english (what is also my system language), i can activate "Check spelling when typing" in Edit menu. But i don't get any feedback when typing. I can't activate when wire lang is german.

**Comment by worldofpeace** [comment]
That has to with hunspellDicts. Are you suggesting I pull in all the dictionaries for all languages regardless of the system language? I think that's excessive for a communication app if so.

**Comment by davidak** [comment]
@worldofpeace i think it's ok when only the system language is supported. But even then spell check has no function. Does it work on your system?

**Comment by worldofpeace** [comment]
Yes. I think it's an english thing :)

**Comment by worldofpeace** [comment]
@davidak What's the status on this? Any other requested changes?

**Comment by davidak** [comment]
I still can't log in with username or e-mail. I asked wire for details why that happens.

`description` should not start with the package name.

And can you please squash the wire commits into one?

**Comment by worldofpeace** [comment]
> `description` should not start with the package name.

It doesn't start with the package name.
The packages name is wire-desktop and the description starts with Wire.
Am I correct in thinking that's okay? :grin: 

> I asked wire for details why that happens.

Good that you did that. I have multiple accounts and I've logged in and it works fine. I hope you figure that out.

> And can you please squash the wire commits into one?

Yep :smile:

**Comment by worldofpeace** [comment]
Lol I changed my response after reading the description again. Not very descriptive.
How's  "A cross-platform, encrypted instant messaging client"?

Also squash commit done.

**Comment by worldofpeace** [comment]
Can somebody please merge this? I think this meets all the requirements.

**Comment by davidak** [comment]
What about "A modern, secure messenger"? It differentiate it to other programs and is less technical.

I got this response from the Wire support:

>Sadly I can't be of much help. We do not support Linux officially.  

Let's see if more people have any issues with this package. This state is good for now since there is a workaround.

**Comment by worldofpeace** [comment]
> Sadly I can't be of much help. We do not support Linux officially.

Really? I don't even think that's true. How do you "unofficially" support Linux and have downloads to binaries and releases just for it. I've contacted support before and they were very helpful and never said that "Linux" was a problem.

> What about "A modern, secure messenger"? It differentiate it to other programs and is less technical.

That is less technical and I'll most likely change it to that.

> Let's see if more people have any issues with this package.

Does Nix in general require x amount of reviewers and testers for a package as simple as this?

**Comment by davidak** [comment]
>Does Nix in general require x amount of reviewers and testers for a package as simple as this?

No, it just takes some time to review about >1000 PRs :D

**Comment by worldofpeace** [comment]
@matthewbauer Can this get backported into 18.03?

**Pull request merged**
