### PR TITLE
glibmm: fix darwin build

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
See https://github.com/NixOS/nixpkgs/pull/54007#issuecomment-456122303

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by hedning** [comment]
There's a few more failures ([the full list of](https://hydra.nixos.org/eval/1501286?filter=x86_64-darwin&compare=1501262&full=#tabs-now-fail)):

- [`gtk2-x11`](https://hydra.nixos.org/build/87683679) and it's gtk3 variant, not sure if these make sense on darwin?
- [`libfm`](https://hydra.nixos.org/build/87684553)

**Review by hedning — APPROVED** [review]

**Comment by hedning** [comment]
Thanks :)

**Comment by hedning** [comment]
Hmm, should probably go to master though (didn't look closely at the base).

**Comment by jtojnar** [comment]
I pushed it to staging since the glib patch is there as well.

Here is an issue for libfm https://github.com/lxde/libfm/issues/44

**Comment by hedning** [comment]
Ah, https://github.com/NixOS/nixpkgs/pull/54007 went to master though :)

**Comment by jtojnar** [comment]
:woman_shrugging:

**Comment by hedning** [comment]
I'll cherry pick and fix, it's blocking nixpkgs-unstable.

**Comment by jtojnar** [comment]
I do not see logs for `gtk3-x11` or `gtk2-x11`. Maybe we should just use Cocoa GTK on Darwin.

**Comment by hedning** [comment]
Yeah, the logs broke for some reason :(

> Maybe we should just use Cocoa GTK on Darwin.

Yeah, there aren't that many packages that use the x11 variant.

**Comment by jtojnar** [comment]
cc @johbo 8a7d373795f197dbc492ad95e3ad4d1b60ba0d07

cc @LnL7 cfc3d7c9181f543ddb2cf4aa61112957f58e4a4a

**Comment by hedning** [comment]
cherry pick: c9bd2dee0e0a49cfa50b9b29ccf2b2a6cf1c3b03

**Pull request merged**
