### PR TITLE
sqitch: package cleanup

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Package cleanup.

I'm not a user of `sqitch` so I only did minimal testing (ran a migration with `mysql`). I was specifically hoping for some `darwin` testing (@marsam ?) to make sure I didn't break anything there.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

ping @datafoo for possible testing too :heart:

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg build sqitchMysql sqitchPg

**Review by marsam — APPROVED** [review]
Tested on Darwin and NixOS

**Comment by aanderse** [comment]
Thank you very much @marsam! Given basic testing on NixOS and your test on Darwin are you happy to merge?

**Review by matt-snider — APPROVED** [review]
LGTM @aanderse - this is much cleaner.

**Pull request merged**
