### PR TITLE
bazel: Fix bazel query and provide a default java toolchain

### PR DESCRIPTION
**Pull request by mfarrugi**
###### Motivation for this change

These are fixes for problems I ran into with:
- `bazel test //example:cpp-test`
This needed `build --host_javabase='@local_jdk//:jdk'`

- `bazel query 'deps(//example:cpp-test)'`
This needed the same flags as `build`. (Trying to get a sense of why the cpp-test needs java!)

Is it contentious to (partially?) configure the default java toolchain? I don't see it as much different than providing the bazel server's java.
It would continue to be configurable/overridable by overriding the flags. 
https://github.com/NixOS/nixpkgs/issues/86410 is related.

(will rewrite commit later, web ui is tricky :))

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

And a random notes from this escapade, but https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L144-L308 looks a little different from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/bazel_3/src-deps.json so one of them is probably wrong :)

### CODE REVIEW

**Comment by Infinisil** [comment]
Could this be related to https://github.com/tweag/rules_haskell/issues/1414? In my quick testing, this PR's bazel didn't fix that issue, so maybe not.

**Comment by mfarrugi** [comment]
It looks like the same sort of problem. In your case none of the .bazelrc
flags apply to query which might be the source of the problem.

**Comment by Profpatsch** [comment]
@aherrmann does this look familiar to you?

**Comment by aherrmann** [comment]
The problem with `bazel query` is that it doesn't take configuration into account. Meaning it won't evaluate `select`s or apply platform constraints to select a toolchain. The `cquery` command is an alternative that does take configuration into account. In the `rules_haskell/tutorial` example it seems to work without error (cc @Infinisil)
```
$ nix-shell --pure ../shell.nix --run 'bazel cquery --nohost_deps --noimplicit_deps "deps(//main:demorgan)"'
...
//main:demorgan (e05802078203a74d9644c5b7ab2f441c7edc77c7cf9c943d34e190a170d74972)
//lib:booleans (e05802078203a74d9644c5b7ab2f441c7edc77c7cf9c943d34e190a170d74972)
//main:Main.hs (null)
//main:base (e05802078203a74d9644c5b7ab2f441c7edc77c7cf9c943d34e190a170d74972)
//lib:Bool.hs (null)
...
```

**Comment by Profpatsch** [comment]
So sounds to me like this is a “works as intended” situation? It is confusing, but we can’t really compensate for it.

**Comment by mfarrugi** [comment]
If you use bazel with internet access, it will download the other platforms' java_tools to resolve the query. Given that nix is doing the fetching, I think this makes sense. The cost to this fix is downloading two extra .zip files that total ~100mb.

I can see the argument that a person shouldn't be using `bazel query` over `bazel cquery`, but I see no plans to remove the former and as long as it's there it should work out of the box.

Separately, any thoughts on the `--host_javabase` change? This seems strictly better for users.

**Comment by Profpatsch** [comment]
I am not deep enough into the bazel build anymore to have much of an opinion on whether this change is correct, it is all very confusing and you never know if things have to be there because of a bug in bazel or a works-as-intended.

So I’d say let’s merge this and see what breaks.

**Comment by Profpatsch** [comment]
> And a random notes from this escapade, but https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L144-L308 looks a little different from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/bazel_3/src-deps.json so one of them is probably wrong :)

I nearly missed this, but I don’t understand what you mean by that? Can you elaborate?

**Comment by mfarrugi** [comment]
Nixpkgs' list of bazels' dependencies is different from upstream's, but I
assume ours is a superset so it's not a real problem.

**Comment by Profpatsch** [comment]
If you look into the code definition there’s an update which the
maintainers run when updating bazel:
https://github.com/NixOS/nixpkgs/blob/7e757502e95a2a22522151f9036da7db161f0ef9/pkgs/development/tools/build-managers/bazel/bazel_3/default.nix#L290-L297

it will use the exact version of the WORKSPACE from that release, so it
should always correspond exactly to it.

**Comment by mfarrugi** [comment]
https://github.com/NixOS/nixpkgs/blob/7e757502e95a2a22522151f9036da7db161f0ef9/pkgs/development/tools/build-managers/bazel/update-srcDeps.py
is parsing the entire WORKSPACE file, so it is indeed a superset. It could
probably just read  additional_distfiles from bazel, but I'm not interested
in pursuing this further.

**Comment by Profpatsch** [comment]
> is parsing the entire WORKSPACE file, so it is indeed a superset. It could probably just read additional_distfiles from bazel, but I'm not interested in pursuing this further.
> [](#)

I’m sorry, I still don’t understand what you mean. What exactly is the problem here?

**Comment by mfarrugi** [comment]
It's not relevant to this PR.

https://docs.bazel.build/versions/master/guide.html#running-bazel-in-an-airgapped-environment suggests that bazel should only need https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L144-L308 to work airgapped.  We are doing something different than `bazel build @additional_distfiles//:archives.tar` that, if the docs are to be believed, are downloading a superset of the necessary files.

**Comment by Profpatsch** [comment]
Oh, but nix won’t download any artifacts from the lock file that are not
actually needed, so the most we are optimizing here is for code bloat in
the repository, and I think it’s not relevant to spend any time on that tbh.

**Comment by Profpatsch** [comment]
Okay, I merged under the assumption that this PR does set a sensible default. We’ll see if any complaints come in.

**Pull request merged**
