### PR TITLE
glibc-2.26-75

### PR DESCRIPTION
**Pull request by vcunat**
Largest expected caveat: upstream bumped the minimal supportable kernel to 3.2.0.  That's the oldest kernel still supported upstream, released in Jan 2012, but most notably RHEL 6 and derivates still use a heavily patched 2.6.32 kernel and those systems are still supported and in use (production support is scheduled to last till the end of 2020!).

Therefore, I suggest to postpone this after branching 17.09, at least; it won't be nice even after that, but I fail to see a better option ATM.

### CODE REVIEW

**Comment by vcunat** [comment]
A single coreutils test started failing :-/
> test-getopt.h:754: assertion 'strcmp (argv[1], "donald") == 0' failed

It seems no use to rush merging this.

**Comment by vcunat** [comment]
Now there are some CVE fixes in this PR.  I won't keep it waiting long, just let 17.09 rebuild first with glibc patches.

**Comment by vcunat** [comment]
Hmm, this will cause relatively lots of build-time breakages.  I will try to patch some, mainly older versions of gcc and llvm, and anything blocking "important" packages, but I can't manage everything.

**Comment by vcunat** [comment]
@7c6f434c, @asppsa: do you think that `pure` can be migrated to some newer llvm?  So far I only bothered to fix 3.7 and newer branches...

**Comment by 7c6f434c** [comment]
Technical answer: still no, https://bitbucket.org/purelang/pure-lang/issues/36/port-pure-to-the-mcjit-in-order-to-support

**Comment by asppsa** [comment]
@vcunat, yeah dependency on old LLVM is unfortunately an ongoing problem for Pure.  My guess is that this will not be fixed any time soon.

**Comment by vcunat** [comment]
OK.  It's similar for `llvm-general`, though there are branches for newer LLVM versions.

**Comment by vcunat** [comment]
I will probably fix llvm-3.5 within a week, but certainly feel free to beat me.

**Comment by vcunat** [comment]
Support for RHEL 6 and friends: https://github.com/NixOS/nixpkgs/pull/32954

**Pull request merged**
