### PR TITLE
WIP: automagically format the docs

### PR DESCRIPTION
**Pull request by grahamc**
don't merge me, but here is what the docs look like auto-formatted.

Prior to merging, I would of course have to document the tool, config, and methods of how I did it.

Any opinions?

**NOTE: Please say on this PR if you like it! Otherwise I may not merge it, since it is so big.**

### CODE REVIEW

**Comment by grahamc** [comment]
cc https://github.com/NixOS/nixpkgs/pull/39649 and @jcrben

**Comment by grahamc** [comment]
See also: https://discourse.nixos.org/t/can-we-auto-format-the-documentation-docbook-xml/121/2

**Review by Mic92 — APPROVED** [review]
Open manual pull requests should be merge ahead of this (I don't expect to many open ones though).
Some test would be nice to check if the formatting was applied in pull requests.

**Comment by grahamc** [comment]
I've only seen positive-or-neutral (after clarifying with Eelco on IRC) feedback on this, so I think this is a go. I'll document how I did this and send that as a separate PR.

Beyond the top ... few ... here I'm not sure I should go back and ensure they can merge first: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+label%3A%228.has%3A+documentation%22

**Comment by vcunat** [comment]
As for open PRs, they should be solvable after this reformat as well &ndash; they can run the formatting tool on the old state and just verify the diff against the newly formatted master.  I suppose 18.03 cherry-picks of docs will also find some way, and I don't expect many of them.  In the "worst" case we can just run the reformating on all docs in 18.03 as well, as that doesn't seem as such a breaking change :-)

**Comment by grahamc** [comment]
>  In the "worst" case we can just run the reformating on all docs in 18.03 as well

I was thinking I would just go ahead and do that :)

I've been making a bit of an effort to backport 18.03-relevant doc improvements, too.

**Comment by grahamc** [comment]
on master, nixpkgs: 77161de4546697f9bf2da6d081eeba4c399b3313
on master, nixos: eca5c99bf8a115ffd9513f91decc064a5bb3ff6d
on release-18.03, nixpkgs: 5eae581d52714b23b0ff8e8e73651a044327721f 
on release-18.03, nixos: d3644fc26ad4c5a4570a70669d850acc25ae0f6a

**Pull request closed without merging**
