### PR TITLE
binutils: 2.31.1 -> 2.34

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Noticed it was out of date and that #78204 was out of date.

cc. @guibou who did the original PR
cc. @flokli for review
c.f. https://sourceware.org/pipermail/binutils/2020-April/110818.html for discussion on the coreutils test failures reported in #78204 in the binutils ML.

Closes #78204

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

Seems to have stalled. Retry!

**Comment by zimbatm** [comment]
nixpkgs-review is evaluating fine here. Is it possible that ofborg is running out of memory since the updated graph is so large?

**Comment by grahamc** [comment]
It is unfortunate I didn't notice at the time, but the evaluation tests should never build anything because of precisely this problem: the evaluators are supposed to succeed even in the case of mass rebuilds. @infinisil, maybe you have ideas on ways the lib tests could be evaluation _only_? Otherwise, I think we'll have to drop that check until it can be made a builder check.

**Comment by lovesegfault** [comment]
This causes the build of `rhash` to fail with the weirdest issue I've seen in Nix so far. I'd appreciate someone with more experience taking a look:
```
❯ nix build -f. --arg overlays '[]' -L rhash
rhash> unpacking sources
rhash> unpacking source archive /nix/store/ljybrllcm43yyabb7dqb768y92zknsmx-source
rhash> cp: setting permissions for 'source': Function not implemented
rhash> do not know how to unpack source archive /nix/store/ljybrllcm43yyabb7dqb768y92zknsmx-source
builder for '/nix/store/sylw6x6r4ph2hdjlzqhfzs4ficy6jxam-rhash-1.3.9.drv' failed with exit code 1; last 4 log lines:
  unpacking sources
  unpacking source archive /nix/store/ljybrllcm43yyabb7dqb768y92zknsmx-source
  cp: setting permissions for 'source': Function not implemented
  do not know how to unpack source archive /nix/store/ljybrllcm43yyabb7dqb768y92zknsmx-source
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/sylw6x6r4ph2hdjlzqhfzs4ficy6jxam-rhash-1.3.9.drv' failed
```

**Comment by Infinisil** [comment]
Oh yeah that's a problem.. Lemme think about that..

**Comment by Infinisil** [comment]
See above two PR's which should fix the eval problem for ofborg

**Comment by flokli** [comment]
Regarding https://github.com/NixOS/nixpkgs/pull/85951#issuecomment-619412670, I spent some time with @LnL7 and @lovesegfault yesterday to debug this. 

The failing command here is https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L813, which handles the case when `src` is a directory. It's not specific to rhash, but to all packages where `src` is provided as a directory.

Apparently, with this `binutils` bump, `cp -pr` suddenly forgets how to copy over files inside directories that don't have the `w` chmod set.

I don't really understand why it's the `binutils` bump  that's breaking this, and not `coreutils`…

**Comment by pbogdan** [comment]
I also don't understand why it's specifically `binutils` that triggers it but it seems like instance of https://bugzilla.redhat.com/show_bug.cgi?id=1811038 Indeed applying https://src.fedoraproject.org/rpms/coreutils/c/acfa9e81ec1baeea27c2c12f04b5b56c260a3af7?branch=master does fix the issue on the `rhash` archive.

The difference can be seen in the `config.log` of coreutils
- master
  ```
  configure:8523: checking for lchmod
  configure:8523: gcc -o conftest -g -O2   conftest.c  >&5
  conftest.c:84:1: error: unknown type name 'choke'
     84 | choke me
        | ^~~~~
  conftest.c:84:9: error: expected ';' before 'int'
     84 | choke me
        |         ^
        |         ;
  ......
     87 | int
        | ~~~      
  configure:8523: $? = 1
  ```
- this branch:
  ```
  configure:8523: checking for lchmod
  configure:8523: gcc -o conftest -g -O2   conftest.c  >&5
  /nix/store/1hf9d291zalp1c5ywx41ij09b88fdv54-binutils-2.34/bin/ld: /build/ccqVNKSd.o: in function `main':
  /build/coreutils-8.31/conftest.c:90: warning: lchmod is not implemented and will always fail
  configure:8523: $? = 0
  configure:8523: result: yes
  ```

I also guess something similar may affect other packages as well 
but again no clue how this is related to `binutils` upgrade ¯\_(ツ)_/¯ or why the problem only shows up now.

**Comment by lovesegfault** [comment]
@pbogdan you did it! That was the issue! me and @flokli just verified that setting `ac_cv_func_lchmod=no` fixes the issues we had seen.

**Comment by cole-h** [comment]
Pinged on IRC, but posting here for prosperity: the `build-components-separately.patch` is used by `libopcodes` and `libbfd` and as such should not be removed from the tree.

**Comment by lovesegfault** [comment]
Good catch, thanks @cole-h!

I reverted that deletion

**Comment by thefloweringash** [comment]
I looked in to what's going on here. I think the root cause is mixing binutils 2.31 with binutils >= 2.32.

Some details:

Various downstream builds seem to fail due to using `lchmod`, and can be fixed by specifying `set ac_cv_func_lchmod=no` as in c5e3472e2072ed0998571ce3961b8df65e2862cc. In the version of glibc we use, `lchmod` is not implemented and should always result in `checking for lchmod... no`. Even though glibc doesn't implement `lchmod`, it does provide a stub for it. When a function is stubbed, an entry is written into `stubs.h` that autoconf uses to exclude stubs from its results. This file lives at `${glibc.dev}/include/gnu/stubs-64.h` (on x86_64, it differs per platform). In this branch this file contains no stubs and the incorrect `yes` result is returned.

So why does this file contain no stubs? The build log for a failed glibc shows:
```
(cd /build/build/csu/.; objdump -h init-first.o libc-start.o sysdep.o version.o [...]
gawk '/\.gnu\.glibc-stub\./ { \
          sub(/\.gnu\.glibc-stub\./, "", $2); \
          stubs[$2] = 1; } \
        END { for (s in stubs) print "#define __stub_" s }' > /build/build/csu/stubsT
objdump: init-first.o: unable to initialize decompress status for section .debug_info
objdump: init-first.o: unable to initialize decompress status for section .debug_info
objdump: init-first.o: file format not recognized
objdump: libc-start.o: unable to initialize decompress status for section .debug_info
objdump: libc-start.o: unable to initialize decompress status for section .debug_info
objdump: libc-start.o: file format not recognized
objdump: sysdep.o: unable to initialize decompress status for section .debug_info
objdump: sysdep.o: unable to initialize decompress status for section .debug_info
objdump: sysdep.o: file format not recognized
objdump: version.o: unable to initialize decompress status for section .debug_info
objdump: version.o: unable to initialize decompress status for section .debug_info
objdump: version.o: file format not recognized
[...]
```

A shell pipeline has masked a critical error in the glibc build.

The [internet says](https://wiki.gentoo.org/wiki/Binutils_2.32_upgrade_notes/elfutils_0.175:_unable_to_initialize_decompress_status_for_section_.debug_info) this is a mutual incompatibility between binutils 2.31 and binutils >= 2.32 due to a bug fix appearing in binutils 2.32.

I'm not yet familiar with how stdenv bootstrapping transitions from bootstrap binary binutils (ie, 3.21, I assume) to the in-tree version (3.24, as of this PR). A simple resolution would be a synchronized update of the bootstrap binaries and the in-tree version such that old and new never mix. I'm hoping there's a simpler resolution from tweaking the bootstrapping.

**Comment by lovesegfault** [comment]
cc. @matthewbauer for bootstrapping questions

**Comment by lovesegfault** [comment]
Continued in https://github.com/NixOS/nixpkgs/pull/86954

**Pull request merged**
