### PR TITLE
pkgsStatic: Allow commutation with pkgsLLVM

### PR DESCRIPTION
**Pull request by pwaller**
Prior to this commit, pkgsStatic.pkgsLLVM.hello would give a static
binary built with LLVM, but pkgsLLVM.pkgsStatic would not.

The reason is that pkgsStatic would not supply the LLVM attributes into
the crossSystem, but pkgsLLVM on top of pkgsStatic does.

This can be confusing to users, since if they pick the wrong ordering,
they may conclude that these two don't compose, when they do.

Before commit:

```
$ nix eval --system x86_64-linux -f . pkgsStatic.pkgsLLVM.hello.outPath
"/nix/store/4b2fmnp5ishi4jzm2hhfs5a7gpj2ig6p-hello-static-x86_64-unknown-linux-musl-2.12.1"
$ nix eval --system x86_64-linux -f . pkgsLLVM.pkgsStatic.hello.outPath
"/nix/store/al3jmj73mczwlc9adbcy3ljxxvn99jam-hello-static-x86_64-unknown-linux-musl-2.12.1"
```

(The other is not built with LLVM).

After commit, they're the same:

```
$ nix eval --system x86_64-linux -f . pkgsStatic.pkgsLLVM.hello.outPath
"/nix/store/4b2fmnp5ishi4jzm2hhfs5a7gpj2ig6p-hello-static-x86_64-unknown-linux-musl-2.12.1"
$ nix eval --system x86_64-linux -f . pkgsLLVM.pkgsStatic.hello.outPath
"/nix/store/4b2fmnp5ishi4jzm2hhfs5a7gpj2ig6p-hello-static-x86_64-unknown-linux-musl-2.12.1"
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pwaller** [comment]
Ping @Ericson2314 / @RossComputerGuy / @emilazy , should be quick/easy win.

**Comment by pwaller** [comment]
Discovered https://github.com/NixOS/nixpkgs/pull/365057 which is reworking stuff. @RossComputerGuy is it worth taking this PR as a stepping stone, or closing it (assuming 365057 might land in the feature)?

**Comment by RossComputerGuy** [comment]
This PR probably could use a rework once the new attributes land.

**Comment by pwaller** [comment]
Unless #365057 is about to land very imminently, please can this PR land first? I will fix things up after #365057 if it regresses.

**Comment by RossComputerGuy** [comment]
I could merge this but we also have #303849, both PR's are awaiting review and I'm not sure what we want to land. Either way, well have conflicts.

**Comment by pwaller** [comment]
Thanks for pointing out https://github.com/NixOS/nixpkgs/pull/303849, which I can see has unfortunately been open quite a while.

An argument in favour of taking this fix now is that it is trivial, and it's trivial to rebase around, so it represents an immediate fix for a problem. I appreciate that it piles more difficulties into already harder and bigger work; but those things also have a risk of being stalled and not making forward progress as well.

Either way I'm happy though, so long as we can get this fixed somehow.

**Comment by pwaller** [comment]
Thanks @wolfgangwalther for your efforts, glad to see it move forward!

**Pull request closed without merging**
