### PR TITLE
nextcloud24: init at 24.0.0

### PR DESCRIPTION
**Pull request by urandom2**
###### Description of changes

Added Nextcloud 23 and set it as the default Nextcloud version for the
NixOS module. Added PHP 8.1 as an option for phpPackage and default for
Nextcloud ≥ 24.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by danth — APPROVED** [review]
LGTM.

I've successfully built the Nextcloud 24 package and ran the "basic" NixOS test.

**Review by Ma27 — CHANGES_REQUESTED** [review]
An eval-warning for Nextcloud 23 would be now needed. I'm happy to implement this, but I won't make it before the weekend.

**Comment by aidalgol** [comment]
> An eval-warning for Nextcloud 23 would be now needed. I'm happy to implement this, but I won't make it before the weekend.

Do you mean 22?  23 should still be supported by upstream for a while longer.

**Comment by AkechiShiro** [comment]
Is it safe to upgrade from 23 to 24 ? Like won't the database schema for Nextcloud be changed and rolling back using generation on NixOS would still fail, should backups be made before ?

**Comment by Ma27** [comment]
Yes it usually is on major changes.

**Comment by AkechiShiro** [comment]
Thanks, @Ma27, so it is usually safe, but making a backup of some of the databases I guess isn't bad practice, just in case, but so far I've never had any major upgrade break on me as long as I go from one major to another consecutive major version, like going from Nextcloud18 to Nextcloud24 would be breaking things but from 23 to 24 would be alright.

**Comment by Ma27** [comment]
Nextcloud would refuse to go straight from e.g. 18 to 24.
Btw, busy weekend, please be a bit patient with me, will try to take care of getting this ready this week.

**Comment by AkechiShiro** [comment]
Oh, I wasn't aware that Nextcloud would refuse to do so, no worries on time for this PR, I won't be upgrading my instance any time soon this coming week, take all the time you need.

**Comment by arnottcr** [comment]
I have never had luck downgrading nextcloud, even for minor versions; their docs recommend backup as the only rollback strategy.

**Comment by arnottcr** [comment]
> An eval-warning for Nextcloud 23 would be now needed. I'm happy to implement this, but I won't make it before the weekend.

I am unclear on the reason for the eval-warning, but if you mean the one for nextcloud21 in [`default.nix`](https://github.com/arnottcr/nixpkgs/blob/nextcloud/pkgs/servers/nextcloud/default.nix#L36), that is there due to end of life. As such, @aidalgol is correct in stating that you meant 22, not 32, but even then 22 is not yet eol, see the [upstream support matrix](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule). I would rather wait until july to execute that change.

**Review by Ma27 — APPROVED** [review]
Did some minor fixups, successfully deployed v24 to my personal instance... Going to merge as soon as CI is green :)

**Comment by Ma27** [comment]
> @Ma27, I am unclear on the reason for the eval-warning, but if you mean the one for nextcloud21 in default.nix, that is there due to end of life. As such, @aidalgol is correct in stating that you meant 22, not 32, but even then 22 is not yet eol, see the upstream support matrix. I would rather wait until july to execute that change.

Heh, now I see our misunderstanding :) 

I meant the change I did in e46bff9 .

Still, we should drop nextcloud22 rather soonish (i.e. before 22.05, otherwise we'll have EOLed software in 22.05 which is supported until the end of 2022).

**Comment by Ma27** [comment]
@arnottcr thanks! Going to backport nextcloud24 (without the breaking changes such as changed efaults) to 21.11 later today.

**Comment by arnottcr** [comment]
already started that in #173094; feel free to polish and merge

**Comment by Ma27** [comment]
Oh, very nice, thanks a lot! :)

**Comment by alarsyo** [comment]
After a few attempts at fixing this:

- setting `nextcloud.phpPackage = pkgs.php80;` works, although I had to remove the twofactor_totp app and reinstall it manually
- manually editing `/var/lib/nextcloud/store-apps/twofactor_totp/appinfo/info.xml` and bumping the maximum supported php version to 8.1 also works

**Comment by Ma27** [comment]
Oof Nextcloud again :( 

I assume that the issue occurred because you already deployed PHP 8.1 and thus the app was marked as broken. Because of that we should make PHP 8.0 the default for each Nextcloud until this issue is fixed.

@alarsyo do you want to file a PR for that? :)

**Comment by arnottcr** [comment]
you can always use nixtcloud24 with php80 via phpPackage

**Pull request merged**
