### PR TITLE
tut: 0.0.46 -> 1.0.13

### PR DESCRIPTION
**Pull request by equirosa**
###### Description of changes

new release made: https://github.com/RasmusLindroth/tut/releases/tag/1.0.0
https://github.com/RasmusLindroth/tut/releases/tag/1.0.13

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
:eyes: Please also update the hashes and re-test the build

**Review by Mindavi — CHANGES_REQUESTED** [review]
Needs hash update

**Comment by equirosa** [comment]
Oh! Weird. I'll update it to the newer version (Rasmus is releasing them hella fast) and push the updated hash too :)

**Comment by Mindavi** [comment]
Next time you can just update this PR rather than making a new one.

**Comment by equirosa** [comment]
> Next time you can just update this PR rather than making a new one.

My bad, I rebased onto master and mistakenly pushed to my branch without the commit, which closed the PR, I'll reopen it

**Comment by equirosa** [comment]
Hold up. It's failing to build...

**Comment by equirosa** [comment]
I'm getting the following error:
```
error: builder for '/nix/store/vh7kx4807lw5dbgyh6qiql93gxa87inx-tut-1.0.10.drv' failed with exit code 1;
       last 10 log lines:
       > net/http
       > github.com/gorilla/websocket
       > github.com/RasmusLindroth/go-mastodon
       > github.com/RasmusLindroth/tut/util
       > github.com/RasmusLindroth/tut/auth
       > github.com/RasmusLindroth/tut/api
       > github.com/RasmusLindroth/tut/feed
       > # github.com/RasmusLindroth/tut/feed
       > feed/feed.go:124:28: f.loadingNewer.mux.TryLock undefined (type sync.Mutex has no field or method TryLock)
       > feed/feed.go:142:28: f.loadingOlder.mux.TryLock undefined (type sync.Mutex has no field or method TryLock)
       For full logs, run 'nix log /nix/store/vh7kx4807lw5dbgyh6qiql93gxa87inx-tut-1.0.10.drv'.
```

unsure about how to procedd

**Pull request merged**
