### PR TITLE
nvidia_x11_legacy340: remove

### PR DESCRIPTION
**Pull request by Mic92**
Apparently broken on all kernel versions: https://github.com/NixOS/nixpkgs/pull/49470#issuecomment-442785553

### CODE REVIEW

**Comment by Mic92** [comment]
I just saw @volth @florianjacob in the git history maintaining these packages.
If there are still kernels where these works can we get an upper bound on the kernel version?

**Comment by volth** [comment]
I still have 2 videocards in use, one of them (NVS440) requires ```nvidiaLegacy304``` and another (8800GT) ```nvidiaLegacy340```.
The first is difficult to replace, it is a 4 heads PCI card, so I will have to support ```nvidiaLegacy304``` in my fork.

**Comment by c0bw3b** [comment]
340 was recently updated in #50841 to prevent build failure with newer kernels
(and backported in #51014)

**Comment by florianjacob** [comment]
304 was discontinued end of 2017 and won't get updates for newer kernel / X.org versions by nvidia anymore. In theory, it should still work with 4.14, though. @volth can you confirm that? Not sure whether that failed as well in Mic's build failure list.
We could then whitelist it for 4.14 and drop it when NixOS drops 4.14, it will definitely never gain support for newer kernels, and will probably break with a future X.org version as well.

340 will still be updated by nvidia until the end of 2019 to support new kernels and X.org versions. With the recent update & backport, it *should* work across all kernels again, I have it running here based on 4.19. I'll try to provide the nvidia updates until then.

Source: https://nvidia.custhelp.com/app/answers/detail/a_id/3142

**Comment by volth** [comment]
> it should still work with 4.14, though. @volth can you confirm that?

I am mostly on 4.4 and 4.9 anyway

**Comment by Mic92** [comment]
@c0bw3b I tested the build with the compilation fix included.

**Comment by Mic92** [comment]
I made a new pull request that marks nvidia 304 as broken on newer kernels.

**Comment by florianjacob** [comment]
Fix for the patch failing to be applied to 340.107 with kernel 4.14 kindly provided by @binarin in #51457, by removing it completely.

**Pull request closed without merging**
