### PR TITLE
Backport: Bump GolLand and Datagrip

### PR DESCRIPTION
**Pull request by drupol**
Backport of #128190 

**Do not merge this before #128185 !**

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128191` at 708abd52 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/0f67ab42b85ed33d18077ffad552c4d1">jetbrains.clion</a></li>
    <li><a href="https://gist.github.com/bf344cbf113e29da94826c6b374d9a27">jetbrains.datagrip</a></li>
    <li><a href="https://gist.github.com/11ab322d945a26f13601e4db420fc945">jetbrains.goland</a></li>
    <li><a href="https://gist.github.com/d784e2bad368837ad26844f465dd919f">jetbrains.rider</a></li>
    <li><a href="https://gist.github.com/59346a0afb3880acf6a190d2a33cee3a">jetbrains.webstorm</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by jonringer** [comment]
some conflicts, please resolve

**Comment by drupol** [comment]
@jonringer Job done!

**Comment by drupol** [comment]
@jonringer all good now?

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 128191 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>jetbrains.datagrip</li>    <li>jetbrains.goland</li>  </ul></details>

**Comment by drupol** [comment]
Thanks!

**Pull request merged**
