### PR TITLE
Nixos tests build discrepancy

### PR DESCRIPTION
**Pull request by majiru**
## Description of changes

Some tests are unable to be run with 'nix build' due to the use of builtin.currentSystem. This PR fixes each instance of this and removes the default that uses this from make-test-python.nix. Marked as draft until CI confirms this

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
LGTM assuming that nothing broke in the transition

**Review by philiptaron — APPROVED** [review]
Nifty.

**Comment by Ma27** [comment]
@majiru

> Some tests are unable to be run with 'nix build' due to the use of builtin.currentSystem

`nix build -f nixos/tests/kernel-generic.nix linux_6_1` works fine. What exactly is breaking?

That said, this breaks calling `nix-build nixos/tests/foo.nix` on numerous occasions (tested `kernel-generic.nix`, but I'm pretty sure every instance where `{ system ? builtins.currentSystem }@args: import ./make-test-python.nix ({ ... }: { /* test */ }) args` is used because in that case `args` doesn't contain `system` unless specified via `--arg` on the CLI.

So I'm inclined to revert this.

**Comment by majiru** [comment]
> @majiru
> 
> > Some tests are unable to be run with 'nix build' due to the use of builtin.currentSystem
> 
> `nix build -f nixos/tests/kernel-generic.nix linux_6_1` works fine. What exactly is breaking?
> 

The issue is specifically when tests are invoked like so:
```
nix build  '.#nixosTests.opensearch.opensearch'
nix build '.#nixosTests.vscodium.xorg'
...
```

For the specific test you name, kernel-generic, I can reproduce this causing an issue running it how you described but neither of the typical way I know of running tests seems to work:
```
nix-build -A nixosTests.kernel-generic # fails with 'error: linux 4.14 was removed because it will reach its end of life within 23.11'
nix build '.#nixosTests.kernel-generic' # fails to find the derivation
```

My apologies I was not aware tests were invoked with how you described.

> That said, this breaks calling `nix-build nixos/tests/foo.nix` on numerous occasions (tested `kernel-generic.nix`, but I'm pretty sure every instance where `{ system ? builtins.currentSystem }@args: import ./make-test-python.nix ({ ... }: { /* test */ }) args` is used because in that case `args` doesn't contain `system` unless specified via `--arg` on the CLI.
> 

If you have an enumeration of tests that are broken, complete or not, it would be nice to have the list for a future change.

> So I'm inclined to revert this.

We can revert the default for this function, but I would like to keep the other refactors to tests, they do help resolve the issue described at the top of this reply. I can open a PR for that or I can approve one that you open, whichever you like.

**Comment by majiru** [comment]
@Ma27 
I have opened a PR for reverting this change to the default arguments https://github.com/NixOS/nixpkgs/pull/299501.

**Comment by Ma27** [comment]
> My apologies I was not aware tests were invoked with how you described.

To be fair, there are several ways of invoking those tests. Sorry if my reply sounded harsh, that was not my intention btw!

> If you have an enumeration of tests that are broken, complete or not, it would be nice to have the list for a future change.

So, unfortunately a few tests don't work with `nix-build` already, but basically anything using returning an invocation of `make-test-python.nix` should be affected.

Regarding `kernel-generic.nix`: what I usually do is enumerating the kernels that have changed in the PR I'm currently reviewing. I.e. if 6.1 and 6.6 got updated, I do `nix-build nixos/tests/kernel-generic.nix -A linux_6_{1,6}`.

That said, didn't the issue happen because a few tests were invoking the function from `make-test-python` with `{}` (which you also fixed in here)? AFAIU that's the only case where this function is invoked w/o `system` being passed down.

Also, just as a general recommendation, I'd suggest to not use the flake-style interface here: as long as we don't have lazy trees, this means that on each change, a new nixpkgs will be copied to your store when invoking `nix build`. That doesn't invalidate the issue you've had of course and it's still worth fixing, but for active development on nixpkgs using the non-flake variant is probably more developer friendly currently.

**Comment by majiru** [comment]
> > My apologies I was not aware tests were invoked with how you described.
> 
> To be fair, there are several ways of invoking those tests. Sorry if my reply sounded harsh, that was not my intention btw!
> 

I didn't take your reply as being harsh and hope my reply doesn't come off as harsh either! I just wanted to state all of my assumptions about how these things work. I'm still somewhat new to all this so I appreciate being corrected about how these things work.

> > If you have an enumeration of tests that are broken, complete or not, it would be nice to have the list for a future change.
> 
> So, unfortunately a few tests don't work with `nix-build` already, but basically anything using returning an invocation of `make-test-python.nix` should be affected.

Ah okay. Probably good to leave this reverted as is then. I had briefly discussed this in element when I found it and there was a very light agreement that this might be warranted to change. Looking at things now I'm probably not comfortable enough with this portion of the repo to have suggested this change, sorry.

> 
> Regarding `kernel-generic.nix`: what I usually do is enumerating the kernels that have changed in the PR I'm currently reviewing. I.e. if 6.1 and 6.6 got updated, I do `nix-build nixos/tests/kernel-generic.nix -A linux_6_{1,6}`.

Ah okay this makes sense, thank you.

> 
> That said, didn't the issue happen because a few tests were invoking the function from `make-test-python` with `{}` (which you also fixed in here)? AFAIU that's the only case where this function is invoked w/o `system` being passed down.
> 

Yes that was indeed the cause of the issue here as far as I understand, and the attempt I did was to pause up the function without invoking it where possible for these cases that I found.

> Also, just as a general recommendation, I'd suggest to not use the flake-style interface here: as long as we don't have lazy trees, this means that on each change, a new nixpkgs will be copied to your store when invoking `nix build`. That doesn't invalidate the issue you've had of course and it's still worth fixing, but for active development on nixpkgs using the non-flake variant is probably more developer friendly currently.

Thank you for the advice. It's no wonder why some of these went unnoticed then.

**Comment by philiptaron** [comment]
I'm learning a lot reading this conversation. Thank you both!

**Pull request merged**
