### PR TITLE
[20.09] brave: 1.17.73 -> 1.18.70

### PR DESCRIPTION
**Pull request by buckley310**
###### Motivation for this change
Backport https://github.com/NixOS/nixpkgs/pull/106718

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by JeffLabonte — APPROVED** [review]
LGTM

**Comment by prusnak** [comment]
Please cherry-pick from master using `git cherry-pick -x` so the commit message contains the reference to the original commit (see CONTRIBUTORS.md where this is described).

**Comment by buckley310** [comment]
Sorry about that, there was some weirdness with this one and I thought I would just squash them.
I redid the PR just using direct cherry-picks (with -x). The actual code is unchanged.

**Comment by prusnak** [comment]
Please fix this PR. You are trying to merge 10.000+ commits into the release branch, which is not what you want.

**Comment by buckley310** [comment]
Abort!

**Pull request closed without merging**
