### PR TITLE
[release-24.05] forgejo: 7.0.6 -> 7.0.7

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

https://codeberg.org/forgejo/forgejo/releases/tag/v7.0.7

https://codeberg.org/forgejo/forgejo/src/branch/forgejo/RELEASE-NOTES.md#7-0-7

https://codeberg.org/forgejo/forgejo/milestone/7683

https://codeberg.org/forgejo/forgejo/compare/v7.0.6...v7.0.7

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilylange** [comment]
Why did you open a PR targeting `release-24.05`?
`master` needs that version as well.

**Comment by emilylange** [comment]
This is fine, especially considering that this would have been a manual backport anyway.

It's just really confusing.

At any rate, thanks for the links in the opening PR comment.
Next time, please add them to the commit message body as well, thanks.

And, also for the future, tick the checkboxes in the PR template that you think apply instead of leaving all empty.

**Comment by emilylange** [comment]
Opened #333489 targeting `master` in the meantime :)

**Comment by vrifox** [comment]
> This is fine, especially considering that this would have been a manual backport anyway.
> 
> It's just really confusing.

I'll try to open both PRs next time and the master targeting one first. :)

> At any rate, thanks for the links in the opening PR comment. Next time, please add them to the commit message body as well, thanks.

I didn't realize that I should add them to the commit message body. Thanks for the tip. :+1: 

> And, also for the future, tick the checkboxes in the PR template that you think apply instead of leaving all empty.

None of these seemed to be correct. I'm still not firm in testing. I hope that is okay? :see_no_evil: 

> Opened https://github.com/NixOS/nixpkgs/pull/333489 targeting master in the meantime :)

Thank you! :tada: :)

**Comment by adamcstephens** [comment]
❯ nix-build -A forgejo.passthru.tests --argstr system aarch64-linux
/nix/store/gxkmzvh2dh5xzfybfnrp4xpw2ps12zyj-vm-test-run-forgejo-mysql
/nix/store/h1xqvbjf5whaihwb9l052sdsn6sc9g68-vm-test-run-forgejo-postgres
/nix/store/dcly6006n7lj5ffqqg5z7x0bb4br20wi-vm-test-run-forgejo-sqlite3

**Pull request merged**
