### PR TITLE
solvespace: remove

### PR DESCRIPTION
**Pull request by whitequark**
###### Motivation for this change

I'm the current maintainer of solvespace. The version in nixpkgs is a very outdated port that should have never been merged by then-maintainer in the state that it was in, and is completely unusable for real-world work. Since I do not use NixOS, I cannot provide an updated recipe. However, on multiple occasions people ran this broken port with the expectation that it is usable software, and at least I'd like to prevent that.

### CODE REVIEW

**Review by thoughtpolice — CHANGES_REQUESTED** [review]
This can't be merged as it must also be removed from `all-packages.nix`, or it will break everything.

That said, I'm using solvespace myself now since recently, so I'm willing to take a whack at just fixing this.

**Comment by whitequark** [comment]
cc @edef1c @ben0x539

**Comment by whitequark** [comment]
If you want to package something stable you want the last commit from the 2.x branch (now b1d87bf284b32e875c8edba592113e691ea10bcd), that includes the glibc fix as well.

**Comment by ben0x539** [comment]
Sounds like @edef1c might have some work towards packaging a more recent version already.

**Comment by edef1c** [comment]
PR coming in a few minutes or so, just gonna the version upgrade first and some minor changes to my build process.

**Comment by edef1c** [comment]
https://github.com/NixOS/nixpkgs/pull/25570

**Pull request closed without merging**
