### PR TITLE
yabause: Qt4 -> Qt5, disable emu-compatibility.com in About menu

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Yabause 0.9.15 requires OpenGL 3.2 or later, and master branch requires OpenGL 3.3 or later. That's too restrictive. See: https://github.com/Yabause/yabause/issues/349

emu-compatibility.com is now defunct and thus should not be in About menu.

Other minor changes:
* linkage-rwx-linux-elf.diff -> linkage-rwx-linux-elf.patch
* Mark some inputs as optional
* Do not build with Doxygen by default: it does not produce any outputs
* Do not build with OpenAL by default: SDL2 handles sound when present
* Do not build with FreeGLUT by default: deprecated at upstream

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
If doxygen, openal and freeglut aren't used, I would say "rip them out" instead of nulling them.

**Comment by yegortimoshenko** [comment]
One might still want to build the package with OpenAL if they don't like SDL handling sound for whatever reason. I'd leave FreeGLUT as well. Since Doxygen presumably isn't used (but still recognized by the build system) I'll drop it from inputs.

**Comment by peterhoeg** [comment]
In that case the nicer option is to add a ```useSDL``` flag (in the SDL case) and avoid passing the ```null```s.

**Comment by yegortimoshenko** [comment]
It's semantically redundant, and it'd require one flag for every optional dependency, which doesn't scale well.

**Comment by peterhoeg** [comment]
I beg to differ. Let's say you use "useSDL" as an example, so you end up with 

```nix
   buildInputs = [ some package and another ] 
  ++ lib.optionals useSDL [ one or more sdl packages ]
  ++ lib.optional (!useSDL) [ openal ];
```

That is far cleaner than having to remember which attributes to null for the various combinations.

**Comment by yegortimoshenko** [comment]
Your example presumes that SDL and OpenAL can't be built at the same time. That isn't true, most emulators that have multiple audio/video backends allow to choose which one to use in preferences.

**Comment by peterhoeg** [comment]
Ah, I didn't know you would build it with multiple options - then your way is definitely better than mine.

**Pull request merged**
