### PR TITLE
neovim: old-version -> new-version

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by jagajaga** [comment]
Please notice that there is `version`.

**Comment by expipiplus1** [comment]
oops, I forgot to check that line in *again* :/

**Comment by jagajaga** [comment]
Why do you close? Just edit, rebase and force push.

**Comment by expipiplus1** [comment]
oh, I wasn't sure how github's pull requests handled force pushes. I know that was a bit flaky in the past.

**Pull request closed without merging**
