### PR TITLE
python3Packages.azure*: bump

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
noticed that a lot were out of date

closes: #92425 #92418 #92417 #92411 #92408
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Seems that the maintainer of most of the packages is @mwilsoninsight - but he does not seem active on Github = 0 contributions last year. Maybe we should remove him as a maintainer from these packages?

**Comment by jonringer** [comment]
@prusnak you're right, but I'll wait for him to comment. I think he made a post in discourse recently....

The post is here https://discourse.nixos.org/t/nixops-travis-ci-test-failure-on-azure-private-ip-pr/2441/16

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/92486
45 packages built:
azure-cli python27Packages.azure-mgmt-compute python27Packages.azure-mgmt-containerinstance python27Packages.azure-mgmt-containerservice python27Packages.azure-mgmt-datafactory python27Packages.azure-mgmt-iotcentral python27Packages.azure-mgmt-media python27Packages.azure-mgmt-network python27Packages.azure-mgmt-recoveryservicesbackup python27Packages.azure-mgmt-resource python27Packages.azure-mgmt-sql python27Packages.azure-mgmt-storage python27Packages.azure-mgmt-subscription python37Packages.azure-mgmt-appconfiguration python37Packages.azure-mgmt-compute python37Packages.azure-mgmt-containerinstance python37Packages.azure-mgmt-containerservice python37Packages.azure-mgmt-datafactory python37Packages.azure-mgmt-hdinsight python37Packages.azure-mgmt-iotcentral python37Packages.azure-mgmt-media python37Packages.azure-mgmt-network python37Packages.azure-mgmt-recoveryservicesbackup python37Packages.azure-mgmt-resource python37Packages.azure-mgmt-sql python37Packages.azure-mgmt-storage python37Packages.azure-mgmt-subscription python37Packages.azure-multiapi-storage python37Packages.azure-storage-file-share python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-media python38Packages.azure-mgmt-network python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-multiapi-storage python38Packages.azure-storage-file-share
```

going to merge this soon, to prevent `nixpkgs-update` from spamming more PRs

**Comment by jonringer** [comment]
with `azure-cli` bump
```
https://github.com/NixOS/nixpkgs/pull/92486
45 packages built:
azure-cli python27Packages.azure-mgmt-compute python27Packages.azure-mgmt-containerinstance python27Packages.azure-mgmt-containerservice python27Packages.azure-mgmt-datafactory python27Packages.azure-mgmt-iotcentral python27Packages.azure-mgmt-media python27Packages.azure-mgmt-network python27Packages.azure-mgmt-recoveryservicesbackup python27Packages.azure-mgmt-resource python27Packages.azure-mgmt-sql python27Packages.azure-mgmt-storage python27Packages.azure-mgmt-subscription python37Packages.azure-mgmt-appconfiguration python37Packages.azure-mgmt-compute python37Packages.azure-mgmt-containerinstance python37Packages.azure-mgmt-containerservice python37Packages.azure-mgmt-datafactory python37Packages.azure-mgmt-hdinsight python37Packages.azure-mgmt-iotcentral python37Packages.azure-mgmt-media python37Packages.azure-mgmt-network python37Packages.azure-mgmt-recoveryservicesbackup python37Packages.azure-mgmt-resource python37Packages.azure-mgmt-sql python37Packages.azure-mgmt-storage python37Packages.azure-mgmt-subscription python37Packages.azure-multiapi-storage python37Packages.azure-storage-file-share python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-media python38Packages.azure-mgmt-network python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-multiapi-storage python38Packages.azure-storage-file-share
```

**Pull request merged**
