### PR TITLE
xfce4-13: 4.13.x -> 4.14pre1

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

version update
@vcunat @yegortimoshenko 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
The next stem might be to rename it to ```xfce4-14``` and set as the default ```xfce``` (keeping ```xfce4-12``` for some time as ```xfce-legacy```).
So there will be some time to test before ```NixOS 19.09``` release
```Xfce``` promises to release ```4.14``` in August, just few weeks before ```NixOS 19.09```

**Comment by volth** [comment]
@romildo

**Comment by romildo** [comment]
Looks good to me. Tested on a VM with https://github.com/NixOS/nixpkgs/pull/37594 included.

**Comment by volth** [comment]
up

**Pull request merged**
