### PR TITLE
goPackages.gore: init at 0.2.5

### PR DESCRIPTION
**Pull request by chris-martin**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Gore is a REPL that works with Go 1.5.

### CODE REVIEW

**Comment by joachifm** [comment]
LGTM. Would you like to add yourself as the maintainer for these packages?

**Comment by chris-martin** [comment]
I will if I should, though I'm just getting start in Go and I'm not really sure how much I'll continue to be involved with it in the future.

**Comment by joachifm** [comment]
Alright, you can always claim maintainership later, it's just that adding orphan packages is a bit odd, but whatever.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
