### PR TITLE
Staging next 2022-02-03

### PR DESCRIPTION
**Pull request by jonringer**
Major changes:
- Mass python pkgs update
- llvm bump for linux: 7 -> 11
- ~ffmpeg default bumped to 5.x~

-----

workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
constitutents: https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next

Previous staging-next: #157215

### CODE REVIEW

**Comment by zowoq** [comment]
2000 line diff in `pkgs/top-level/aliases.nix`?

**Comment by jonringer** [comment]
> 2000 line diff in `pkgs/top-level/aliases.nix`?

Someone did a major refactoring, I tried to sort it as best I could

**Comment by fabianhjr** [comment]
Bumping fish from 3.3.1 (July 2021) to a snapshot from fish-shell fixes the issue, test pass and nixos switches/boots into staging-next.

```
Author: Fabián Heredia Montiel <fabianhjr@protonmail.com>
Date:   Wed Feb 9 10:13:31 2022 -0600

    fish: 3.3.1 → unstable-2022-02-09

diff --git a/pkgs/shells/fish/default.nix b/pkgs/shells/fish/default.nix
index cf264f11de8..dc7e6c9b893 100644
--- a/pkgs/shells/fish/default.nix
+++ b/pkgs/shells/fish/default.nix
@@ -1,6 +1,6 @@
 { stdenv
 , lib
-, fetchurl
+, fetchFromGitHub
 , coreutils
 , which
 , gnused
@@ -133,17 +133,13 @@ let
 
   fish = stdenv.mkDerivation rec {
     pname = "fish";
-    version = "3.3.1";
-
-    src = fetchurl {
-      # There are differences between the release tarball and the tarball GitHub
-      # packages from the tag. Specifically, it comes with a file containing its
-      # version, which is used in `build_tools/git_version_gen.sh` to determine
-      # the shell's actual version (and what it displays when running `fish
-      # --version`), as well as the local documentation for all builtins (and
-      # maybe other things).
-      url = "https://github.com/fish-shell/fish-shell/releases/download/${version}/${pname}-${version}.tar.xz";
-      sha256 = "sha256-tbTuGlJpdiy76ZOkvWUH5nXkEAzpu+hCFKXusrGfrok=";
+    version = "unstable-2022-02-09";
+
+    src = fetchFromGitHub {
+      owner = "fish-shell";
+      repo = "fish-shell";
+      rev = "210e7a9cc989d18fc4b62a0328451cef39770fbc";
+      hash = "sha256-8gum2v61ZBs/SyI/K+Kpe0cyqEY1OkaZTd7WaDZu33M=";
     };
 
     # Fix FHS paths in tests
@@ -173,6 +169,9 @@ let
 
       # tests/checks/complete.fish
       sed -i 's|/bin/ls|${coreutils}/bin/ls|' tests/checks/complete.fish
+
+      # Prerelease
+      rm tests/checks/version.fish
     '' + lib.optionalString stdenv.isDarwin ''
       # Tests use pkill/pgrep which are currently not built on Darwin
       # See https://github.com/NixOS/nixpkgs/pull/103180
```

Unsure if appropriate since it is very used and low level (a shell)

There is a tracking issue for the next release: https://github.com/fish-shell/fish-shell/issues/8092

**Comment by fabianhjr** [comment]
@trofi, the gcc12 patch does no longer apply on webkitgtk-2.35.5, seems like it has been upstreamed and the new version has just been committed to the main branch.

Might need to revert a74a1f32517b61107bd28f3b54cd49a6fc8db82c here on staging-next.

**Comment by trofi** [comment]
> @trofi, the gcc12 patch does no longer apply on webkitgtk-2.35.5, seems like it has been upstreamed and the new version has just been committed to the main branch.
> 
> Might need to revert [a74a1f3](https://github.com/NixOS/nixpkgs/commit/a74a1f32517b61107bd28f3b54cd49a6fc8db82c) here on staging-next.

Revert sounds fine. Out of my curiosity: `2.35.5` is not yet in any `nixpkgs` branches, right? How will it get to `nixpkgs`? Via `staging-next` as well?

**Comment by fabianhjr** [comment]
> 2.35.5 is not yet in any nixpkgs branches, right? How will it get to nixpkgs?

It is on the main branch via https://github.com/NixOS/nixpkgs/pull/158751

**Comment by trofi** [comment]
Proposed the revert of `gcc-12` patches for `webkitgtk` as https://github.com/NixOS/nixpkgs/pull/158814

**Comment by Synthetica9** [comment]
I'm not sure if this is warranted, but I'd really like #157631 to get in master ASAP. A lot of people's sound is broken atm. Is there some way I could speed that up (just merge it directly into master as well?)

**Comment by jonringer** [comment]
> I'm not sure if this is warranted, but I'd really like #157631 to get in master ASAP. A lot of people's sound is broken atm. Is there some way I could speed that up (just merge it directly into master as well?)

I think we could cherry-pick it to staging-next. We seem to have a lot of non-big-parallel capacity for x86_64-linux

**Comment by Synthetica9** [comment]
> > I'm not sure if this is warranted, but I'd really like #157631 to get in master ASAP. A lot of people's sound is broken atm. Is there some way I could speed that up (just merge it directly into master as well?)
> 
> I think we could cherry-pick it to staging-next. We seem to have a lot of non-big-parallel capacity for x86_64-linux

Okay, see https://github.com/NixOS/nixpkgs/pull/158949

**Comment by zowoq** [comment]
> I think we could cherry-pick it to staging-next. 

I think may have meant to cherry pick it from `staging` to `staging-next`, not `staging-next` to `master`.

**Comment by Synthetica9** [comment]
> > I think we could cherry-pick it to staging-next.
> 
> I think may have meant to cherry pick it from `staging` to `staging-next`, not `staging-next` to `master`.

Oh I assumed he meant _from_ staging-next since it's already _in_ staging-next

**Comment by vcunat** [comment]
@fabianhjr: `fish` resolved without updating.

**Review by fabianhjr — APPROVED** [review]
Builds and boots in my config, haven't noticed any issues.

**Comment by jonringer** [comment]
Newly succeeding is about even with newly failing:
https://hydra.nixos.org/eval/1743207?filter=x86_64-linux&compare=1743148&full=#tabs-now-fail

I'm going to consider this acceptable; as I already spent three nights getting the major regressions.

**Comment by vcunat** [comment]
Overall I saw quite a lot "regressions" that seemed like they will disappear on restarting the build.  And then various python-related regressions...

**Comment by zowoq** [comment]
The `tomlkit` bump looks like it broke `remarshal` which is used by `pkgs.formats.{toml,yaml}` so there is probably a few broken modules and tests.

PR: https://github.com/NixOS/nixpkgs/pull/159074

**Comment by vcunat** [comment]
In trunk-combined the numbers aren't even, as many `nixos.tests.**` joined the regressions, but it's still probably not too bad.  https://hydra.nixos.org/eval/1743296?compare=1743083

**Pull request merged**
