### PR TITLE
gtk3: fix build on darwin

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
`gdkquartz-gtk-only.h` is now included in distribution tarballs https://gitlab.gnome.org/GNOME/gtk/-/commit/235d28f02d54e6601cef51fec91d46961f64009e

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Hm, should this be staging, I wonder? @LnL7 maybe you have some advice?

**Comment by marsam** [comment]
I think it's safe to go to master, since it only affects darwin, and those packages are currently broken

**Comment by worldofpeace** [comment]
Yeah, nixpkgs-unstable is blocked https://hydra.nixos.org/build/113759839

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build gtk3

this didn't build on darwin for some reason

**Comment by worldofpeace** [comment]
Confirmed this wasn't a problem on stable https://hydra.nixos.org/job/nixpkgs/nixpkgs-20.03-darwin/gtk3.x86_64-darwin

**Pull request merged**
