### PR TITLE
prusa-slicer: renamed from slic3r-prusa3d and updated 1.41.3 -> 2.0.0

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

<strike>It seems likely to me that there will be a new stable release of slic3r-prusa3d soon. There have been quite a few changes, esp. the rewrite of components in Perl.

To avoid duplicated work, I already create this PR with a working update for `1.42.0-alpha5`, so others can build on it.</strike>

Updated to the latest stable version, 2.0.0.

The slic3r-prusa3d package was renamed by upstream to PrusaSlicer with
the 2.0.0 release to reduce confusion with the slic3r package.

cc @thorstenweber83

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Moredread** [comment]
@grahamcofborg build slic3r-prusa3d

**Comment by Moredread** [comment]
The package was renamed to PrusaSlicer by upstream.

I'm not sure what we should call it. PrusaSlicer is the official name but the binary is named prusa-slicer.

**Comment by thorstenweber83** [comment]
The manual says not to use uppercase letter for the attribute name: https://nixos.org/nixpkgs/manual/#sec-package-naming

So prusa-slicer is the right way to go, I think.

**Comment by Moredread** [comment]
Updated to the latest stable version, 2.0.0.

It is ready for merge now. :)

@thorstenweber83 @mweinelt

**Comment by mweinelt** [comment]
Builds and runs, thanks!

**Comment by thorstenweber83** [comment]
Yes, looks good! thank you!

**Comment by ArdaXi** [comment]
I added these changes into my overlay and ran into a crash issue in the GUI. I'm not sure if it's because of upstream changes or issues with the package, so I'm linking it here just in case:

https://github.com/prusa3d/PrusaSlicer/issues/2360

**Comment by mweinelt** [comment]
I see GUI freezes when I leave the window idling for some minutes in the background with some model loaded and sliced. No particular error relates to that afaict.

<details>
  <summary>stdout/stderr</summary>
```
[nix-shell:~/.cache/nix-review/pr-55475]$ prusa-slicer 
04:43:13 PM: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
Multisample enabled

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:13.674: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:13.674: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.269: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.269: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.282: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.450: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.450: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.469: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.469: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.470: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.470: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.470: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:14.471: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.796: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.796: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.796: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.798: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.798: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.852: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:15.853: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-WARNING **: 16:43:20.369: Could not find the icon 'application-xml'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:26.770: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:26.770: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:26.781: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:26.782: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:43:26.782: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:44:02.557: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:44:02.558: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:44:02.558: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:44:02.559: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.376: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.377: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.379: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.379: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.379: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.878: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:18.878: IA__gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:21.636: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:21.636: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:21.647: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:21.647: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed

(prusa-slicer:10968): Gtk-CRITICAL **: 16:45:21.648: IA__gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed
```
</details>

**Comment by Moredread** [comment]
I've changed the PR to compile against wxGTK 3.0, as I only see the bug in https://github.com/prusa3d/PrusaSlicer/issues/2360 with 3.1.

**Comment by mweinelt** [comment]
Yes, that fixes "Add instance" for me.

**Comment by ArdaXi** [comment]
Confirmed, the new version does not display this behaviour. Thanks!

**Comment by baracoder** [comment]
Tested yesterday with `nix-env -iA prusa-slicer -f https://github.com/Moredread/nixpkgs/archive/slic3r.tar.gz`
Everything expect add instance worked. 
To get custom profiles from the older version, you need to use *Export config bundle* from slic3r-pe and imported it to prusa-slicer

**Comment by ArdaXi** [comment]
On a hunch I updated wxWidgets to 3.1.2 and the issue disappeared as well. It might be worth upgrading wxWidgets, considering 3.1.2 came out in December, then this package can be built against 3.1 as well.

**Comment by Moredread** [comment]
> 
> 
> On a hunch I updated wxWidgets to 3.1.2 and the issue disappeared as well. It might be worth upgrading wxWidgets, considering 3.1.2 came out in December, then this package can be built against 3.1 as well.

+1 :)

Do you want to create the PR for wxWidgets 3.1.2? I think it would be better to review it on it's own terms, as I guess there a few packages that depend on it that need to be checked.

Should we wait before we merge this PR, or can we merge the version with wxGTK 3.0?

**Comment by ArdaXi** [comment]
I feel like the wxGTK update is a pretty significant PR which might take a while to merge. I don't personally think that there's a huge loss in having this PR build against 3.0, so I would vote to go ahead and update later.

**Comment by thorstenweber83** [comment]
I also think we shouldn't wait for wxGTK to be updated. Let's just move to 3.1.2 later when the pull request is through.

**Comment by Moredread** [comment]
In that case I think we are basically ready for merging. :) 

Can somebody with commit access please remove the WIP tag?

**Comment by Moredread** [comment]
@GrahamcOfBorg build prusa-slicer

**Comment by teto** [comment]
trusting previous reviews

**Pull request merged**
