### PR TITLE
torbrowser: 6.0.4 -> 6.0.5

### PR DESCRIPTION
**Pull request by sternenseemann**
Note: This is a security update, so it should be backported to stable?!

### CODE REVIEW

**Comment by joachifm** [comment]
Thank you. I'll handle it.

**Comment by sternenseemann** [comment]
Thank you!

**Comment by joachifm** [comment]
Tested briefly on x86_64, works for me.

**Comment by joachifm** [comment]
Picked to release at 24a7e80e69e276bc167677425833c0c25e5e3015

**Pull request merged**
