### PR TITLE
buildGo115Module: Remove

### PR DESCRIPTION
**Pull request by c00w**
This is no longer needed - we have one 115 package.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by c00w** [comment]
Tested via grep buildGo115Module.

**Comment by zowoq** [comment]
I'd very strongly prefer to remove all of `go_1_15` at once, it's odd to remove `buildGo115Module` and keep the rest.

**Comment by zowoq** [comment]
It looks like there is only 3 packages left using `go_1_15` or `buildGo115Package`.

**Comment by c00w** [comment]
Huh - I didn't realize there were packages which used go 1.15 directly. coyim is a mess (doesn't build with 0.16, 0.17, and the new prerelease is also unbuildable), so i wasn't going to touch it. Let me poke the others.

**Comment by zowoq** [comment]
> coyim is a mess ..

I'll drop the `115` override and mark it as broken: https://github.com/NixOS/nixpkgs/pull/157319

**Comment by zowoq** [comment]
There are some patches that can be removed with `go_1_15`, I can open a PR for it or you can copy/cherrypick the changes from https://github.com/qowoz/nixpkgs/commit/c0b59071a0a39e5fa1e040caab315a7eff8ecc61 to this PR if you prefer.

**Comment by zowoq** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/157460.

Thanks for cleaning up the 1.15 packages.

**Pull request closed without merging**
