### PR TITLE
pygments: 2.1.3 -> 2.2.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

A new version has been released.

[Changes:](http://pygments.org/docs/changelog/)

**Version 2.2.0**

(release Jan 22, 2017)

-    Added lexers:
     -   AMPL
     -   TypoScript (#1173)
     -   Varnish config (PR#554)
     -   Clean (PR#503)
     -   WDiff (PR#513)
     -   Flatline (PR#551)
     -   Silver (PR#537)
     -   HSAIL (PR#518)
     -   JSGF (PR#546)
     -   NCAR command language (PR#536)
     -   Extempore (PR#530)
     -   Cap’n Proto (PR#595)
     -   Whiley (PR#573)
     -   Monte (PR#592)
     -   Crystal (PR#576)
     -   Snowball (PR#589)
     -   CapDL (PR#579)
     -   NuSMV (PR#564)
     -   SAS, Stata (PR#593)
-    Added the ability to load lexer and formatter classes directly from files with the -x command line option and the lexers.load_lexer_from_file() and formatters.load_formatter_from_file() functions. (PR#559)
-    Added lexers.find_lexer_class_by_name(). (#1203)
-    Added new token types and lexing for magic methods and variables in Python and PHP.
-    Added a new token type for string affixes and lexing for them in Python, C++ and Postgresql lexers.
-    Added a new token type for heredoc (and similar) string delimiters and lexing for them in C++, Perl, PHP, Postgresql and Ruby lexers.
-    Styles can now define colors with ANSI colors for use in the 256-color terminal formatter. (PR#531)
-    Improved the CSS lexer. (#1083, #1130)
-    Added “Rainbow Dash” style. (PR#623)
-    Delay loading pkg_resources, which takes a long while to import. (PR#690)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
I did a Hydra run on this, and this breaks at least `pelican` and `searx`. 

- Pelican is not that important; because it is typically used as an application it is straightforward to use an older version of `pygments` for it.
- `searx` seems to pin exact versions (sigh). @fpletz , is `searx` used as a Python library, or not? If not, then we can keep the current version of `pygments` for `searx`.

If we solve these two issues then I think we can use the latest version of `pygments`. 

The latest version of `pygments` adds some new features (and one [nice fix](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/690/delay-loading-pkg_resources-until-it-is/diff). I'm not sure whether its worth merging for 17.30. What do you think @romildo ?

**Comment by globin** [comment]
@FRidh you can simply `sed` out the hard dependency in `searx` (done for some of the other dependencies, too)

**Comment by FRidh** [comment]
@globin yes but will it still function properly? That's a risk one takes when removing the hard dependency. This isn't a maintenance bump either but a new feature release.

**Comment by fpletz** [comment]
@FRidh It will probably just work. I'll give it a try. In the meantime this PR can be merged. Searx is in fact an application and is not used a library.

**Comment by fpletz** [comment]
Works. :smiley:

**Comment by FRidh** [comment]
Great, thanks.

**Pull request merged**
