### PR TITLE
deltachat-cursed: 0.7.1 -> 0.7.2

### LINKED ISSUE #196371: deltachat-cursed immediately crash at runtime
### Describe the bug

deltachat-cursed immediately crash at runtime

### Steps To Reproduce

1. `nix-shell -p deltachat-cursed`
2. `delta`
3. get an error message
```
Traceback (most recent call last):
  File "/nix/store/wdv9b22xrcjbrzwp27misw4zj2cpx703-deltachat-cursed-0.7.1/bin/.delta-wrapped", line 6, in <module>
    from deltachat_cursed.main import main
  File "/nix/store/wdv9b22xrcjbrzwp27misw4zj2cpx703-deltachat-cursed-0.7.1/lib/python3.10/site-packages/deltachat_cursed/main.py", line 13, in <module>
    from .application import Application
  File "/nix/store/wdv9b22xrcjbrzwp27misw4zj2cpx703-deltachat-cursed-0.7.1/lib/python3.10/site-packages/deltachat_cursed/application.py", line 25, in <module>
    from .widgets.composer import ComposerWidget
  File "/nix/store/wdv9b22xrcjbrzwp27misw4zj2cpx703-deltachat-cursed-0.7.1/lib/python3.10/site-packages/deltachat_cursed/widgets/composer.py", line 9, in <module>
    from emoji.unicode_codes import EMOJI_UNICODE_ENGLISH
ImportError: cannot import name 'EMOJI_UNICODE_ENGLISH' from 'emoji.unicode_codes' (/nix/store/djhzlhsqrwwa4ncal1fsd2jwqq74dqn1-python3.10-emoji-2.1.0/lib/python3.10/site-packages/emoji/unicode_codes/__init__.py)
```

### Expected behavior

it shouldn't crash

### Notify maintainers

@dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.0-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20221013.ba187fb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - nixpkgs: `/nix/store/9z3mf509n245ydbsx13ygcp7w4yc3s5g-source`

```

### PR DESCRIPTION
**Pull request by rapenne-s**
###### Description of changes

deltachat-cursed is currently broken, see #196371 updating to last commit fix it

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

fixes https://github.com/NixOS/nixpkgs/issues/196371

### CODE REVIEW

**Comment by rapenne-s** [comment]
Result of `nixpkgs-review pr 196401` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>deltachat-cursed</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
https://github.com/adbenitez/deltachat-cursed/releases/tag/v0.7.2

**Comment by rapenne-s** [comment]
> https://github.com/adbenitez/deltachat-cursed/releases/tag/v0.7.2

when using 0.7.2 instead of the commit, I have the following issue. Any idea why? I suppose another package need to be updated, but it seems deltachat components are scattered across a few places and I don't know how they articulate.

```
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./deltachat_cursed-0.7.2-py3-none-any.whl
       > Requirement already satisfied: urwid-readline>=0.13 in /nix/store/17k9pv2rcs4vxs6c7zgk31m6rbfwrznx-python3.10-urwid_readline-0.13/lib/python3.10/site-packages (from deltachat-cursed==0.7.2) (0.13)
       > Requirement already satisfied: urwid>=2.1.2 in /nix/store/6z0i4fvl24l9zc1ap7i6f0wlg2apfp5n-python3.10-urwid-2.1.2/lib/python3.10/site-packages (from deltachat-cursed==0.7.2) (2.1.2)
       > Requirement already satisfied: notify-py>=0.3.3 in /nix/store/vrmj7a6n3qfyp0rcg8cfhw7vfpy131da-python3.10-notify-py-0.3.3/lib/python3.10/site-packages (from deltachat-cursed==0.7.2) (0.3.3)
       > Requirement already satisfied: emoji>=2.0.0 in /nix/store/djhzlhsqrwwa4ncal1fsd2jwqq74dqn1-python3.10-emoji-2.1.0/lib/python3.10/site-packages (from deltachat-cursed==0.7.2) (2.1.0)
       > ERROR: Could not find a version that satisfies the requirement deltachat>=1.97.0 (from deltachat-cursed) (from versions: none)
       > ERROR: No matching distribution found for deltachat>=1.97.0
```

**Comment by dotlambda** [comment]
> `ERROR: No matching distribution found for deltachat>=1.97.0`

We have to update `python3.pkgs.deltachat` (and thus `libdeltachat`) to 1.97.0. I added a commit that does so.

**Comment by rapenne-s** [comment]
Result of `nixpkgs-review pr 196401` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>deltachat-cursed</li>
    <li>kdeltachat</li>
    <li>libdeltachat</li>
    <li>python310Packages.deltachat</li>
    <li>python39Packages.deltachat</li>
  </ul>
</details>

**Comment by rapenne-s** [comment]
works for me :+1:

**Pull request merged**
