### PR TITLE
Revert "LTS Haskell 14.0"

### PR DESCRIPTION
**Pull request by timokau**
Reverts NixOS/nixpkgs#66468. Breaks eval, reverting for now. CC @peti.

### CODE REVIEW

**Comment by grahamc** [comment]
cc @worldofpeace

**Comment by grahamc** [comment]
note ofborg will probably fail anyway, since it first checks master.

**Comment by worldofpeace** [comment]
Could we manually edit the file? I'm guessing something's up with the generation.
If not revert is fine, I'd expect @peti to respond accordingly.

cc @Infinisil

**Comment by timokau** [comment]
Its most likely c4d321494e993365621a9844e930f87df0d87a00 in particular, so maybe its enough to revert that. But that could lead to regressions. Seems safest to revert completely until @peti can look into it.

**Comment by Infinisil** [comment]
I'll take a look to see if it's easily fixable

**Comment by Infinisil** [comment]
Ah, the problem is that while @peti fixed the package being broken with https://github.com/NixOS/nixpkgs/commit/c4d321494e993365621a9844e930f87df0d87a00, he didn't remove `hpack` from the list of packages marked as broken, meaning when `hackage-packages.nix` was regenerated, it still ended up being marked as broken

I can fix this manually, PR(s) incoming in a bit

**Comment by timokau** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/66495.

**Pull request closed without merging**
