### PR TITLE
python3Packages.sunpy: fix build

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
noticed it  was broken during a review

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 94113` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
<br>- python27Packages.towncrier
<br>- python37Packages.sunpy
</details>
<details>
  <summary>3 packages built:</summary>
<br>- python37Packages.towncrier
<br>- python38Packages.sunpy
<br>- python38Packages.towncrier
</details>


<pre>
error: build of '/nix/store/zbdwgjx7251z41l9nlpz32br2y7ichld-python3.7-asynctest-0.13.0.drv' on 'ssh://hexa@phoibe.cysec.de' failed: builder for '/nix/store/zbdwgjx7251z41l9nlpz32br2y7ichld-python3.7-asynctest-0.13.0.drv' failed with exit code 1
builder for '/nix/store/zbdwgjx7251z41l9nlpz32br2y7ichld-python3.7-asynctest-0.13.0.drv' failed with exit code 1; last 10 log lines:
      return await coroutine(*args, **kwargs)
    File "/build/asynctest-0.13.0/asynctest/mock.py", line 985, in patched_factory
      patching.__exit__(*exc_info)
    File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/unittest/mock.py", line 1437, in __exit__
      return exit_stack.__exit__(*exc_info)
    File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/contextlib.py", line 482, in __exit__
      received_exc = exc_details[0] is not None
  IndexError: tuple index out of range

  ======================================================================
cannot build derivation '/nix/store/gsi09jx8clv9sghab7m94s2shdpv8f5h-python3.7-aioresponses-0.6.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bp3ffc9jgaqsjyjvrarav89112qzx2gd-python3.7-zeep-3.4.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/bxvli87kk2sckdhg7xqcg0dmjzx5vs2g-python2.7-towncrier-19.2.0.drv' on 'ssh://hexa@phoibe.cysec.de' failed: builder for '/nix/store/bxvli87kk2sckdhg7xqcg0dmjzx5vs2g-python2.7-towncrier-19.2.0.drv' failed with exit code 2
builder for '/nix/store/bxvli87kk2sckdhg7xqcg0dmjzx5vs2g-python2.7-towncrier-19.2.0.drv' failed with exit code 1; last 10 log lines:
  /nix/store/11m6l05aqmh81mdxlyjwbq0r4xk1g8xa-python2.7-Twisted-20.3.0/lib/python2.7/site-packages/twisted/trial/unittest.py:12: in <module>
      from twisted.trial._synctest import (
  /nix/store/11m6l05aqmh81mdxlyjwbq0r4xk1g8xa-python2.7-Twisted-20.3.0/lib/python2.7/site-packages/twisted/trial/_synctest.py:17: in <module>
      from twisted.python import failure, log, monkey
  /nix/store/11m6l05aqmh81mdxlyjwbq0r4xk1g8xa-python2.7-Twisted-20.3.0/lib/python2.7/site-packages/twisted/python/log.py:17: in <module>
      from zope.interface import Interface
  E   ImportError: No module named zope.interface
  !!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!
  =========================== 6 error in 0.59 seconds ============================
  builder for '/nix/store/bxvli87kk2sckdhg7xqcg0dmjzx5vs2g-python2.7-towncrier-19.2.0.drv' failed with exit code 2
</pre>

**Comment by jonringer** [comment]
rebased on latest master

**Comment by jonringer** [comment]
disabled tests for `python2Packages.towncrier`

**Comment by mweinelt** [comment]
LGTM.

Result of `nixpkgs-review pr 94113` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
<br>- python27Packages.towncrier
<br>- python37Packages.sunpy
<br>- python37Packages.towncrier
<br>- python38Packages.sunpy
<br>- python38Packages.towncrier
</details>

**Pull request merged**
