### PR TITLE
anbox: init at 2018-10-07

### PR DESCRIPTION
**Pull request by edwtjo**
###### Motivation for this change

"Android in a box" for NixOS.

Status:

- Launches activities, i.e. runs installed apks
- Able to install apks using `adb install`
- Current image cannot route to the default gateway set, i.e. not a real failure of the module but the image.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Maybe the third attempt will go in. Feel free to borrow code from the previous version: https://github.com/NixOS/nixpkgs/pull/42076/files

**Comment by edwtjo** [comment]
@Mic92 Thanks for the heads up! I will try to coalesce the different efforts as soon as I get time.

**Comment by peterhoeg** [comment]
@edwtjo, any progress on this?

**Comment by gebner** [comment]
Superceded by #57826.

**Pull request closed without merging**
