### PR TITLE
DCGM: 3.1.8 -> 3.2.5

### PR DESCRIPTION
**Pull request by de11n**
## Description of changes

This is prompted by #258919.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by de11n** [comment]
@amaxine [asked for a comment](https://github.com/NixOS/nixpkgs/pull/258919#issuecomment-1753650238) in `dcgm` and `prometheus-dcgm-exporter` explaining that their versions need to correspond. I added that comment in this PR.

**Comment by Kiskae** [comment]
Since the dcgm version is embedded in the version of dcgm-exporter, perhaps it would be an idea to add a test to dcgm-exporter that verifies the dcgm version it uses matches that version?

Maybe something like:
```nix
testDcgmVersion = testers.testVersion {
  package = dcgm;
  version = lib.elem (lib.splitString "-" version) 0;
  command = "dcgmi -v";
};
```

Then importing that test for `dcgm` as well will cause test failure if either is updated without the other.

**Comment by de11n** [comment]
@Kiskae I've considered that, but I don't have concrete evidence that things are sure to fail when the versions aren't aligned. It's *probably* safe to say that `prometheus-dcgm-exporter` won't support *newer* versions of `dcgm` but may support older ones.

Also worth noting is that `prometheus-dcgm-exporter` can sometimes lag behind `dgcm` by several weeks or more. Do we want to systematically force `dcgm` to only update with or after `prometheus-dcgm-exporter`?

Perhaps the *best* solution is to get `prometheus-dcgm-exporter`s tests working somehow so that we can simply let failing tests tell us when something is actually broken.

**Review by samuela — APPROVED** [review]
diff LGTM

**Pull request merged**
