### PR TITLE
solanum: remove obsolete BANDB settings/patches

### PR DESCRIPTION
**Pull request by Lassulus**
###### Motivation for this change

well for whatever reason, the BANDB stuff doesn't have any effect anymore. so I guess we can just remove it

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124263` at 8eb5701a run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>solanum</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/servers/irc/solanum/default.nix:25:5:
```
   |
25 |     ./dont-create-logdir.patch
   |     ^
```
</li>
  </ul>
</details>

**Comment by Lassulus** [comment]
@4z3 @mweinelt

**Comment by mweinelt** [comment]
Can we test this holds true? Like oper up, resv a nick, check if it flushes the reservation to the right place on disk.

**Comment by Lassulus** [comment]
I removed the ban.db and restarted solanum and the file reappeared in /var/lib/solanum

**Comment by mweinelt** [comment]
Fair enough, whats the matter with the aarch64 build though?

**Pull request merged**
