### PR TITLE
mongodb: add new dependencies for bundled enterprise modules

### LINKED ISSUE #281416: Build failure: mongodb-4_4
### Steps To Reproduce

``git checkout c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370``
``nix build --impure .#mongodb-4_4``

### Build log

```
error: builder for '/nix/store/75hslk6nvmfryrjxy0k27nsmqakir8dd-mongodb-4.4.27.drv' failed with exit code 1;
       last 10 log lines:
       > Checking if std::atomic<int64_t> works... yes
       > Checking if std::atomic<uint64_t> works... yes
       > Checking if std::atomic<int32_t> works... yes
       > Checking if std::atomic<uint32_t> works... yes
       > Checking for extended alignment 64 for concurrency types... yes
       > Checking for mongoc_get_major_version() in C library mongoc-1.0... no
       > configuring module: enterprise
       > Checking for C++ header file net-snmp/net-snmp-config.h... no
       > Could not find <net-snmp/net-snmp-config.h>, required for enterprise build.
       > See /build/mongodb-src-r4.4.27/build/scons/config.log for details
       For full logs, run 'nix log /nix/store/75hslk6nvmfryrjxy0k27nsmqakir8dd-mongodb-4.4.27.drv'.
```

### Additional context

nixos-unstable c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370

### Notify maintainers

@bluescreen303  @offlinehacker 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.11, NixOS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by hughobrien**
## Description of changes

Closes [281416](https://github.com/NixOS/nixpkgs/issues/281416)

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hughobrien** [comment]
Result of `nixpkgs-review pr 281440` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>mongodb (mongodb-6_0)</li>
    <li>mongodb-4_4</li>
    <li>mongodb-5_0</li>
  </ul>
</details>

**Comment by hughobrien** [comment]
Result of `nixpkgs-review pr 281440` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mongodb (mongodb-6_0)</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mongodb-4_4</li>
    <li>mongodb-5_0</li>
  </ul>
</details>

**Comment by hughobrien** [comment]
I don't believe this failure is a result of these changes.

`nix log /nix/store/nlv9px9m8vlhd0d3ckbrkzfp3yncx80v-mongodb-6.0.12.drv`
```
In file included from src/mongo/db/query/analyze_regex.cpp:34:
src/mongo/util/ctype.h:75:15: error: found ‘:’ in nested-name-specifier, expected ‘::’
   75 | enum ClassBit : uint16_t {
      |               ^
      |               ::
src/mongo/util/ctype.h:75:6: error: ‘ClassBit’ has not been declared
   75 | enum ClassBit : uint16_t {
      |      ^~~~~~~~
src/mongo/util/ctype.h:75:26: error: expected unqualified-id before ‘{’ token
   75 | enum ClassBit : uint16_t {
      |                          ^
src/mongo/util/ctype.h:91:11: error: ‘uint16_t’ does not name a type
   91 | constexpr uint16_t calculateClassBits(unsigned char c) {
      |           ^~~~~~~~
```

**Comment by devusb** [comment]
> I don't believe this failure is a result of these changes.
> 
> `nix log /nix/store/nlv9px9m8vlhd0d3ckbrkzfp3yncx80v-mongodb-6.0.12.drv`
> 
> ```
> In file included from src/mongo/db/query/analyze_regex.cpp:34:
> src/mongo/util/ctype.h:75:15: error: found ‘:’ in nested-name-specifier, expected ‘::’
>    75 | enum ClassBit : uint16_t {
>       |               ^
>       |               ::
> src/mongo/util/ctype.h:75:6: error: ‘ClassBit’ has not been declared
>    75 | enum ClassBit : uint16_t {
>       |      ^~~~~~~~
> src/mongo/util/ctype.h:75:26: error: expected unqualified-id before ‘{’ token
>    75 | enum ClassBit : uint16_t {
>       |                          ^
> src/mongo/util/ctype.h:91:11: error: ‘uint16_t’ does not name a type
>    91 | constexpr uint16_t calculateClassBits(unsigned char c) {
>       |           ^~~~~~~~
> ```

Agree, it also fails on master branch.

**Comment by hughobrien** [comment]
Yup, just saw that while debugging
```
hugh@noir /data/nixpkgs master
❯ git pull; git status; git rev-parse HEAD
Already up to date.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
9cd077109869bcc37eefe263b877c865181b6bba
```

```
       > build/nixos/mongo/db/query/analyze_regex.o failed: Error 1
```

```
src/mongo/util/ctype.h:75:15: error: found ‘:’ in nested-name-specifier, expected ‘::’                                                             
   75 | enum ClassBit : uint16_t {                                                                                                                 
      |               ^                                                                                                                            
      |               ::                                                                                                                           
src/mongo/util/ctype.h:75:6: error: ‘ClassBit’ has not been declared                                                                               
   75 | enum ClassBit : uint16_t {                                                                                                                 
      |      ^~~~~~~~                                                                                                                              
src/mongo/util/ctype.h:75:26: error: expected unqualified-id before ‘{’ token                                                                      
   75 | enum ClassBit : uint16_t {                                                                                                                 
      |                          ^                                                                                                                 
src/mongo/util/ctype.h:91:11: error: ‘uint16_t’ does not name a type                                                                               
   91 | constexpr uint16_t calculateClassBits(unsigned char c) {                                                                                   
      |           ^~~~~~~~                                                                                                                         
src/mongo/util/ctype.h:70:1: note: ‘uint16_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?                            
   69 | #include <array>                                                                                                                           
  +++ |+#include <cstdint>                                                                                                                         
   70 |                                                                                                                                            
src/mongo/util/ctype.h: In lambda function:                                                                                                        
src/mongo/util/ctype.h:124:16: error: ‘uint16_t’ was not declared in this scope                                                                    
  124 |     std::array<uint16_t, 256> arr{};                                                                                                       
      |                ^~~~~~~~                                                                                                                    
src/mongo/util/ctype.h:124:16: note: ‘uint16_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?                          
src/mongo/util/ctype.h:124:29: error: template argument 1 is invalid                                                                               
  124 |     std::array<uint16_t, 256> arr{};                                                                                                       
      |                             ^                                                                                                              
src/mongo/util/ctype.h:125:32: error: request for member ‘size’ in ‘arr’, which is of non-class type ‘int’                                         
  125 |     for (size_t i = 0; i < arr.size(); ++i)                                                                                                
      |                                ^~~~                                                                                                        
src/mongo/util/ctype.h:126:12: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript                                      
  126 |         arr[i] = calculateClassBits(i);                                                                                                    
      |            ^                                                                                                                               
src/mongo/util/ctype.h:126:18: error: ‘calculateClassBits’ was not declared in this scope                                                          
  126 |         arr[i] = calculateClassBits(i);                                                                                                    
      |                  ^~~~~~~~~~~~~~~~~~                                                                                                        
src/mongo/util/ctype.h: At global scope:                                                                                                           
src/mongo/util/ctype.h:128:2: error: ‘mongo::ctype::detail::<lambda()>’ called in a constant expression                                            
  123 | constexpr auto chClassTable = [] {                                                                                                         
      |                               ~~~~                                                                                                         
  124 |     std::array<uint16_t, 256> arr{};                                                                                                       
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                       
  125 |     for (size_t i = 0; i < arr.size(); ++i)                                                                                                
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                
  126 |         arr[i] = calculateClassBits(i);                                                                                                    
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                    
  127 |     return arr;                                                                                                                            
      |     ~~~~~~~~~~~                                                                                                                            
  128 | }();                                                                                                                                       
      | ~^~
src/mongo/util/ctype.h:123:31: note: ‘mongo::ctype::detail::<lambda()>’ is not usable as a ‘constexpr’ function because:
  123 | constexpr auto chClassTable = [] {
      |                               ^
src/mongo/util/ctype.h:125:5: error: ‘goto’ is not a constant expression
  125 |     for (size_t i = 0; i < arr.size(); ++i)
      |     ^~~
src/mongo/util/ctype.h:130:33: error: ‘uint16_t’ has not been declared
  130 | constexpr bool isMember(char c, uint16_t mask) {
      |                                 ^~~~~~~~
src/mongo/util/ctype.h: In function ‘constexpr bool mongo::ctype::detail::isMember(char, int)’:
src/mongo/util/ctype.h:131:24: error: invalid types ‘const int[unsigned char]’ for array subscript
  131 |     return chClassTable[static_cast<unsigned char>(c)] & mask;
      |                        ^
src/mongo/util/ctype.h: In lambda function:
src/mongo/util/ctype.h:138:30: error: ‘kLower’ was not declared in this scope
  138 |         arr[i] = isMember(i, kLower) ? 'A' + (i - 'a') : i;
      |                              ^~~~~~
```

**Review by devusb — APPROVED** [review]

**Review by puffnfresh — APPROVED** [review]

**Comment by kfiz** [comment]
This breaks aarch64-darwin as `net-snmp` is only available on linux.

**Comment by devusb** [comment]
Opened #284605

**Pull request merged**
