### PR TITLE
build-fhsenv-bubblewrap: remove /usr/lib and /usr/lib32 from LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by LunNova**
## Description of changes

#262775

#262080

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LunNova** [comment]
Result of `nixpkgs-review pr 263201` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>ciscoPacketTracer7</li>
    <li>flexoptix-app</li>
    <li>houdini</li>
    <li>pureref</li>
    <li>radicle-upstream</li>
  </ul>
</details>
<details>
  <summary>157 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>android-studio</li>
    <li>androidStudioPackages.beta</li>
    <li>androidStudioPackages.canary</li>
    <li>androidStudioPackages.dev</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>arduino</li>
    <li>arduino-ci</li>
    <li>arduino-cli</li>
    <li>arduino-core</li>
    <li>beekeeper-studio</li>
    <li>beeper</li>
    <li>betterdiscord-installer</li>
    <li>beyond-identity</li>
    <li>bitscope.chart</li>
    <li>bitscope.console</li>
    <li>bitscope.display</li>
    <li>bitscope.dso</li>
    <li>bitscope.logic</li>
    <li>bitscope.meter</li>
    <li>bitscope.proto</li>
    <li>bitscope.server</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>bottles</li>
    <li>burpsuite</li>
    <li>buttercup-desktop</li>
    <li>caprine-bin</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>cockroachdb-bin</li>
    <li>codux</li>
    <li>conda</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>davinci-resolve</li>
    <li>devdocs-desktop</li>
    <li>dropbox</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>esphome</li>
    <li>esphome.dist</li>
    <li>expressvpn</li>
    <li>fahclient</li>
    <li>firefly-desktop</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>fspy</li>
    <li>game-rs</li>
    <li>hamsket</li>
    <li>hifile</li>
    <li>hover</li>
    <li>immersed-vr</li>
    <li>insync</li>
    <li>irccloud</li>
    <li>jbrowse</li>
    <li>jetbrains-toolbox</li>
    <li>joplin-desktop</li>
    <li>keet</li>
    <li>kingstvis</li>
    <li>kodiPackages.steam-launcher</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>left4gore-bin</li>
    <li>lens</li>
    <li>lightworks</li>
    <li>localsend</li>
    <li>losslesscut-bin</li>
    <li>lunar-client</li>
    <li>lunatask</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>marktext</li>
    <li>mate.caja-dropbox</li>
    <li>mathpix-snipping-tool</li>
    <li>mendeley</li>
    <li>minigalaxy</li>
    <li>minigalaxy.dist</li>
    <li>mobilecoin-wallet</li>
    <li>mockoon</li>
    <li>molotov</li>
    <li>motrix</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>nextflow</li>
    <li>notable</li>
    <li>notesnook</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>onlyoffice-bin_7_4</li>
    <li>openlens</li>
    <li>osu-lazer-bin</li>
    <li>p3x-onenote</li>
    <li>pdfstudio2021</li>
    <li>pdfstudio2022</li>
    <li>pdfstudio2023</li>
    <li>pdfstudioviewer</li>
    <li>platformio</li>
    <li>playonlinux</li>
    <li>plex</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>protontricks</li>
    <li>protontricks.dist</li>
    <li>protonup-qt</li>
    <li>quartus-prime-lite</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>remnote</li>
    <li>requestly</li>
    <li>saleae-logic-2</li>
    <li>session-desktop</li>
    <li>shticker-book-unwritten</li>
    <li>sidequest</li>
    <li>simplex-chat-desktop</li>
    <li>sonixd</li>
    <li>space-station-14-launcher</li>
    <li>sparrow</li>
    <li>ssb-patchwork</li>
    <li>station</li>
    <li>steam</li>
    <li>steam-rom-manager</li>
    <li>steam-run</li>
    <li>steam-small</li>
    <li>steam-tui</li>
    <li>steamPackages.steam-fhsenv-without-steam</li>
    <li>steamPackages.steamcmd</li>
    <li>teensyduino</li>
    <li>timeular</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>typora</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>unityhub</li>
    <li>unvanquished</li>
    <li>upscayl</li>
    <li>via</li>
    <li>vial</li>
    <li>vmware-workstation</li>
    <li>vscode-fhs</li>
    <li>vscodium-fhs</li>
    <li>wootility</li>
    <li>xivlauncher</li>
    <li>xlights</li>
    <li>ytmdesktop</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zettlr-beta</li>
    <li>zulip</li>
  </ul>
</details>

**Review by Atemu — APPROVED** [review]
We'll have to check whether this breaks the Steam runtime but otherwise, I don't see why we should have the lib dirs in LD_LIBRARY_PATH.

This was taken over from the old chroot made by @abbradar. Do you know why you added these in 3e395b71da1f99eb5ace8d99adb4b1f76424c3d6?

To get this merged quickly without testing steam, you could add these paths back in the Steam package (and verify `LD_LIBRARY_PATH` is still the same inside `steam-run`) and we can do that later.

**Comment by Atemu** [comment]
Btw, have you ran a sample of dependant packages to check whether they still work? They should but you never know..

**Comment by Atemu** [comment]
Mangohud just stopped working but that happens regardless of your change and I doubt it'd cause that too.

**Comment by LunNova** [comment]
I've been running it for a few days but hadn't tested steam. Quick check now and it still opens but haven't tested any games.

**Comment by Atemu** [comment]
@sbourdeauducq I'd recommend you to add the paths back for that particular package then.

**Comment by bjornfor** [comment]
Wasn't the premise for this PR that /usr/lib was in the search path already? Why do packages need fixes after this PR? (E.g. cdc306ebe6c383346b0aa31b6d760fb7da447bda.)

Can we fix this centrally (without relying on $LD_LIBRARY_PATH)? (I wonder what percentage of FHS env packages need fixes after this PR.)

**Comment by Atemu** [comment]
If an FHS program requires default FHS library paths in LD_LIBRARY_PATH in order to run inside an FHS, it's quite honestly broken.

**Comment by bjornfor** [comment]
> If an FHS program requires default FHS library paths in LD_LIBRARY_PATH in order to run inside an FHS, it's quite honestly broken.

Can you elaborate? I thought that on normal FHS distros /usr/lib was in the dynamic linker search path, so that you could do `LD_PRELOAD=foo.so` and it'd find /usr/lib/foo.so (if existing). That used to work in nixpkgs FHS envs too, but not since this PR. I don't see how the program being run inside the FHS can be at fault.

**Comment by bjornfor** [comment]
> If an FHS program requires default FHS library paths in LD_LIBRARY_PATH in order to run inside an FHS, it's quite honestly broken.

Can you elaborate? I thought that on normal FHS distros /usr/lib was in the dynamic linker search path, so that you could do `LD_PRELOAD=foo.so` and it'd find /usr/lib/foo.so (if existing). That used to work in nixpkgs FHS envs too, but not since this PR. I don't see how the program being run inside the FHS can be at fault.

**Comment by LunNova** [comment]
LD_LIBRARY_PATH takes precedence over /nix/store deps in non-FHS executables, which was too high a priority and causes programs to run against unexpected library versions. That caused #262080 which reported widespread breakage inside FHS envs on the stable release.

I suggest raising new issues with specific breakages that you find since it's unlikely this will be reverted.

**Pull request merged**
