### PR TITLE
[20.09] libguestfs: unmark broken

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
wrong variant was marked broken

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
> wrong variant was marked broken

This should probably be part of the commit message for libguestfs, as it explains why this change happened.

**Comment by cole-h** [comment]
FWIW, I was able to build `libguestfs-with-appliance` on the latest commit of `release-20.09`, da973f9971ef1a01645214ffa02a6c8d8a453be8, just now.

**Comment by jonringer** [comment]
@cole-h that's valid.

However, it fails on hydra because the output size is too big. The expression seems to correctly state `hydraPlatforms = [];`, but it's not being respected

**Comment by jonringer** [comment]
I think I figured it out:
```
  libguestfs-with-appliance = libguestfs.override { appliance = libguestfs-appliance; };
```
it overrides the base libguestfs derivation. So the meta isn't respect from libguestfs-appliance.

This also explains why we don't see `libguestfs-appliance` in hydra outputs.

**Review by cole-h — APPROVED** [review]
Diff LGTM, thanks! I think this should be forward-ported, right? (At least, the `hydraPlatforms` change -- I don't think `libguestfs` was marked broken on `master`.)

**Comment by jonringer** [comment]
> Diff LGTM, thanks! I think this should be forward-ported, right? (At least, the `hydraPlatforms` change -- I don't think `libguestfs` was marked broken on `master`.)

agreed

**Comment by jonringer** [comment]
hmm, we need a "needs port to unstable" label

**Comment by jonringer** [comment]
waiting on ofborg

**Comment by jonringer** [comment]
looks like referencing the meta of an override causes infinite recursion:
```
while evaluating 'g' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/lib/attrsets.nix:276:19, called from undefined position:
while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/pkgs/top-level/release-lib.nix:144:38, called from undefined position:
while evaluating the attribute 'meta.hydraPlatforms' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/pkgs/development/libraries/libguestfs/default.nix:93:5:
infinite recursion encountered, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/pkgs/development/libraries/libguestfs/default.nix:91:17
```

**Comment by jonringer** [comment]
nevermind, it was the combination of `rec` + `platforms`

```
[12:15:28] jon@jon-desktop /home/jon/projects/nixpkgs (correct-libguestfs)
$ nix eval -f default.nix libguestfs.meta.hydraPlatforms
[ "aarch64-linux" "armv5tel-linux" "armv6l-linux" "armv7a-linux" "armv7l-linux" "mipsel-linux" "i686-linux" "x86_64-linux" "powerpc64le-linux" "riscv32-linux" "riscv64-linux" ]
[12:15:41] jon@jon-desktop /home/jon/projects/nixpkgs (correct-libguestfs)
$ nix eval -f default.nix libguestfs-with-appliance.meta.hydraPlatforms
[ ]
```

**Comment by jonringer** [comment]
waiting on ofborg

**Comment by cole-h** [comment]
Darwin isn't going to run since the builder is dead, aarch isn't supported because `xen` isn't, and the rest is green. I think this is good to go.

**Pull request merged**
