### PR TITLE
rspamd: 1.6.6 -> 1.7.4

### PR DESCRIPTION
**Pull request by oxij**
Picked from #40434 as other changes there need feedback.

Closes #40414.

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Did rspamd work on aarch64 before?

**Comment by 7c6f434c** [comment]
Interesting. Should I just merge the reduced-ambitions version?

**Comment by oxij** [comment]
We can also do this properly :)

**Comment by 7c6f434c** [comment]
(I look at aarch64 build, at glib declaring an array of size -1 in some error case, and I am not sure how this even works on x86_64)

**Pull request merged**
