### PR TITLE
httpie: 1.0.3 -> 2.0.0

### PR DESCRIPTION
**Pull request by bbigras**
###### Motivation for this change
update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)

I only tested http-prompt quickly. A simple GET worked.

$ nix path-info -h -S /nix/store/zakzw9m8pcp1z2lf7i4lvk34naybx9na-httpie-1.0.3
/nix/store/zakzw9m8pcp1z2lf7i4lvk34naybx9na-httpie-1.0.3	 115.8M

$ nix path-info -h -S /nix/store/jscqy7pkcqrj9zhy1rjshhsz7vhj99z2-httpie-2.0.0
/nix/store/jscqy7pkcqrj9zhy1rjshhsz7vhj99z2-httpie-2.0.0	 115.9M

### CODE REVIEW

**Review by lsix — APPROVED** [review]
Built and tested !

All fine for me.

Thanks

**Comment by c0bw3b** [comment]
Just done a quick reading of upstream changelog, it mentions:
> Added tests/ to the PyPi package for the convenience of downstream package maintainers.

Does it change our test phase? Maybe there is more or better testing available.

**Comment by bbigras** [comment]
> Does it change our test phase? Maybe there is more or better testing available.

I would guess it only affects people using the pypi package (like if we used fetchPypi instead of fetchFromGitHub). We currently got tests running from the `tests` folder when building the package.

But it seems we can remove the disabledTests. `test_current_version` doesn't seem to exist anymore and `test_error` seems to pass.

`tests/test_docs.py` seems to be skipped even with `export PATH=${docutils}/bin:$PATH`.

**Comment by bbigras** [comment]
It seems the problem is that httpie now use a virtual env (venv) which I is not set up in our case.

Should we set up that env or patch it out?

**Comment by Mic92** [comment]
> `tests/test_docs.py` seems to be skipped even with `export PATH=${docutils}/bin:$PATH`.

What if you add docutils to `checkInputs`?

**Comment by bbigras** [comment]
> Does it work if you add docutils to checkInputs?

No. I think it's because python's path is hardcoded:
https://github.com/jakubroztocil/httpie/blob/a7e52287129a8f61826b9c1e6b4c61ab11861b1f/tests/test_docs.py#L42-L51

I added a patch to fix that but for some reason the test doesn't fail if I remove `export PATH=${docutils}/bin:$PATH`.

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
