### PR TITLE
python35Packages.pandas: fix build

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
It's great being able to switch between interpreter versions effortless in nix, but still need some packages in older interpreter versions.

pin version was determined to be the last stable release which supported python3.5
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
[14:31:58] jon@jon-desktop /home/jon/projects/nixpkgs (fix-pandas-py3.5)
$ NIX_BUILD_CORES=16 nix-build -A python35Packages.pandas
/nix/store/5w5178ax15hqjd3gxr1rh7karm1z1zsf-python3.5-pandas-0.25.3
```

**Comment by marsam** [comment]
I'm not sure whether we should still maintain Python3.5 since it reaches EOL in a few weeks https://devguide.python.org/#status-of-python-branches (September 13th, 2020)

**Comment by jonringer** [comment]
we've been maintaining python2 8 months past it's EOL, not sure if that's a strong argument. However, the bump from 3.5 to 3.6 is much less than 2.7 to 3.5

**Comment by FRidh** [comment]
For Python 3 we typically keep several versions. My idea is still to drop 3.5 for 20.09 so that we have 3.6 through 3.8 and the 3.9 beta. Python 2 really cannot be compared.

**Comment by jonringer** [comment]
@worldofpeace and I will be meeting friday to go over roadmap. But given the current date, branchoff will be soon, so maybe I'll just remove this.

**Comment by FRidh** [comment]
@jonringer we spoke earlier about a major package set update. I'll be away on holidays soon and won't find the time to look into that.

**Comment by jonringer** [comment]
@FRidh if you want to initiate one, I can stabilize it. Once I get it to mostly leaf packages are broken, then you can make the determination to merge it then.

**Comment by jonringer** [comment]
should we bump setuptools? not sure how i feel about that package

**Pull request closed without merging**
