### PR TITLE
openmodelica: 1.17.0 -> 1.18.0

### PR DESCRIPTION
**Pull request by balodja**
###### Motivation for this change
Continuation of  #122828 . Now update the OpenModelica version and add myself to openmodelica maintainers.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by balodja** [comment]
@siraben , it seems that @grwlf is inactive. Could you accept the PR please? I want the new version of OpenModelica to be included in 21.11 release.

**Comment by risicle** [comment]
@ofborg build openmodelica

**Comment by risicle** [comment]
`nixpkgs-review` is happy for me on nixos x86_64

**Review by SuperSandro2000 — APPROVED** [review]
ping me in a few days

**Pull request merged**
