### PR TITLE
[Backport release-23.11] jellyfin, jellyfin-web: 10.9.1 -> 10.9.3, 10.9.2 -> 10.9.3

### PR DESCRIPTION
**Pull request by minijackson**
## Description of changes

Backport of #314775

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by minijackson** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
CI isn't green, not sure why...

**Comment by minijackson** [comment]
Not sure why it fails on darwin, also…

**Comment by scaredmushroom** [comment]
The failure is due to a note thrown inside the test:
```
2024-05-28T08:00:49.1667448Z ##[warning]Difference between e67051c92aebf9acd7522dd346e3a713544d4457 and original a7441feb23f2ba370fb3ae130f51113c5c72b8f2 may warrant inspection:
2024-05-28T08:00:49.1718261Z [31m1:  a7441feb23f2 [m[33m![m[32m 1:  e67051c92aeb[m[33m jellyfin: 10.9.1 -> 10.9.3[m
2024-05-28T08:00:49.1719095Z     [7m[36m@@[m [mCommit message[m
2024-05-28T08:00:49.1719549Z      [m
2024-05-28T08:00:49.1720131Z          The `default.nix` was also formatted with `nixfmt-rfc-style` to be `RFC 166`-compliant.[m
2024-05-28T08:00:49.1720848Z      [m
2024-05-28T08:00:49.1721498Z     [7m[32m+[m[1m    (cherry picked from commit a7441feb23f2ba370fb3ae130f51113c5c72b8f2)[m
2024-05-28T08:00:49.1722271Z     [7m[32m+[m
2024-05-28T08:00:49.1732078Z       ## pkgs/servers/jellyfin/default.nix ##[m
2024-05-28T08:00:49.1732732Z     [36m @@[m
2024-05-28T08:00:49.1733050Z     [31m -{ lib[m
2024-05-28T08:00:49.1733874Z     [31m -, fetchFromGitHub[m
2024-05-28T08:00:49.1734315Z     [7m[32m+[m[1;31m-, fetchurl[m
2024-05-28T08:00:49.1734713Z     [31m -, nixosTests[m
2024-05-28T08:00:49.1735201Z     [31m -, stdenv[m
2024-05-28T08:00:49.1735614Z     [31m -, dotnetCorePackages[m
2024-05-28T08:00:49.1736207Z     [7m[36m@@[m [mpkgs/servers/jellyfin/default.nix: buildDotnetModule rec {[m
2024-05-28T08:00:49.1736907Z     [32m +      purcell[m
2024-05-28T08:00:49.1737295Z     [32m +      jojosch[m
2024-05-28T08:00:49.1737640Z     [32m +    ];[m
2024-05-28T08:00:49.1738175Z     [7m[31m-[m[2m     mainProgram = "jellyfin";[m
2024-05-28T08:00:49.1738740Z     [7m[32m+[m[1;32m+    mainProgram = "jellyfin";[m
2024-05-28T08:00:49.1739569Z           platforms = dotnet-runtime.meta.platforms;[m
2024-05-28T08:00:49.1740182Z         };[m
2024-05-28T08:00:49.1740525Z     [7m[32m+[m[1m }[m
2024-05-28T08:00:49.1741552Z Note this should not necessarily be treated as a hard fail, but a reviewer's attention should be drawn to it and github actions have no way of doing that but to raise a 'failure'
[…]
2024-05-28T08:00:50.5631838Z ##[error]Process completed with exit code 1.
2024-05-28T08:00:50.5735042Z Post job cleanup.
```
Please check for yourself by opening the details of the check and than opening the raw log (cogwheel on the right upper side > "View raw logs"), but it seems to be fine?! Dunno though, how to let it pass.

**Comment by minijackson** [comment]
I was more talking about why jellyfin doesn't build on darwin, more than the backport action. I know that the backport action fails because I had to fix a merge conflict during the cherry-pick.

**Comment by minijackson** [comment]
@reckenrode can I ask for your help on this?

**Comment by reckenrode** [comment]
Something seems to be going wrong with the regex source generator. According to the log message, the regex is invalid. I don’t know why it would be failing on Darwin if it’s being accepted on Linux.

**Comment by wegank** [comment]
As NixOS 23.11 reaches end-of-life today, this PR is closed as part of the [EOL cleanup](https://nixos.github.io/release-wiki/EOL-Cleanup.html).

**Pull request closed without merging**
