### PR TITLE
osquery: Apply unreleased upstream patch to build using Clang 16

### PR DESCRIPTION
**Pull request by mfrischknecht**
osquery uses vendored boost libraries that still rely on old standard types like `std::unary_function` (deprecated since C++11, removed in C++17) which breaks the build with current Clang.

There already is an upstream patch for this  [1], but it hasn't been released yet.
[1]: https://github.com/osquery/osquery/commit/222991a15b4ae0a0fb919e4965603616536e1b0a

## Description of changes

<details>
  <summary>Fetch and apply the unreleased upstream patch during nix builds.</summary>

Fetch and apply the unreleased upstream patch during nix builds. This should be revertible as soon as upstream releases the patch and the new version is packaged.

Hydra build: https://hydra.nixos.org/build/241362794#tabs-details
Hydra log: https://hydra.nixos.org/build/241362794/nixlog/3

Relevant log excerpt:

```
In file included from /build/source/libraries/cmake/source/boost/src/libs/thread/src/pthread/thread.cpp:11:
In file included from /build/source/libraries/cmake/source/boost/src/libs/thread/include/boost/thread/thread_only.hpp:22:
In file included from /build/source/libraries/cmake/source/boost/src/libs/thread/include/boost/thread/detail/thread.hpp:41:
In file included from /build/source/libraries/cmake/source/boost/src/libs/container_hash/include/boost/functional/hash.hpp:6:
/build/source/libraries/cmake/source/boost/src/libs/container_hash/include/boost/container_hash/hash.hpp:131:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
/nix/store/wh3jv0niw62xfngky1lhi4sfnjrgyqg6-libcxx-16.0.6-dev/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
```
  
</details>

<details>
  <summary>Changed locale.h header patch to also apply to aarch64</summary>

The package already includes a [patch for x86_64](https://github.com/NixOS/nixpkgs/blob/a0393ca30c4a4595ef3afa2bd3cd3e9ce49d182a/pkgs/tools/system/osquery/Use-locale.h-instead-of-removed-xlocale.h-header.patch) that fixes broken builds due to a broken include in a vendored library. The same error also broke the build on aarch64, so I extended the patch to extend to that architecture, too.

Hydra build: https://hydra.nixos.org/build/241365529
Hydra log: https://hydra.nixos.org/build/241365529/nixlog/3

Relevant log excerpt:

```
In file included from /build/source/libraries/cmake/source/augeas/gnulib/src/lib/hard-locale.c:23:
/build/source/libraries/cmake/source/augeas/gnulib/generated/linux/aarch64/lib/locale.h:53:11: fatal error: 'xlocale.h' file not found
# include <xlocale.h>
          ^~~~~~~~~~~
1 error generated.
```
  
</details>

#ZurichZHF

ZHF: https://github.com/NixOS/nixpkgs/issues/265948

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mfrischknecht** [comment]
I got some advice from @infinisil and switched to applying the upstream patch instead of downgrading the compiler toolchain.

**Comment by delroth** [comment]
@ofborg build osquery

**Comment by mfrischknecht** [comment]
I just ran `nix-build -A osquery.tests`. Worked on my setup.

**Comment by delroth** [comment]
@ofborg build osquery
@ofborg test osquery

**Pull request merged**
