### PR TITLE
Jupyter

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abbradar** [comment]
re: dateparser: awesome! Have you reported this upstream?

**Comment by FRidh** [comment]
@abbradar actually, I didn't feel like fixing dateparser. We had an old version, and a new version required adding new packages.

**Comment by FRidh** [comment]
Now I need to cherry-pick most of this to 17.03...

**Comment by abbradar** [comment]
Sorry, I was sleepy and meant "configparser".

**Comment by FRidh** [comment]
@abbradar no I haven't reported the issue because I am not sure whether what they use is still supposed to work not. In any case, we could make a mention of it.

**Comment by FRidh** [comment]
Testing these commits (except typed-ast) on 17.03.

**Comment by abbradar** [comment]
You'd also need https://github.com/NixOS/nixpkgs/commit/648db95651e99e5e2ce938bf5e776fc9f512c81a.

**Comment by FRidh** [comment]
[Discussion regarding configparser](https://bitbucket.org/ambv/configparser/issues/17/importerror-when-used-with-other-backports)

**Pull request merged**
