### PR TITLE
lumo: remove

### PR DESCRIPTION
**Pull request by armeenm**
###### Description of changes
Hasn't seen a commit in [2 years](https://github.com/anmonteiro/lumo/commits/master) and depends on python2.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by davidak** [comment]
Looks good

Please rebase

cc maintainer @hlolli

**Comment by hlolli** [comment]
I approve

**Review by hlolli — APPROVED** [review]

**Comment by armeenm** [comment]
Rebased.

**Review by davidak — APPROVED** [review]

**Comment by malob** [comment]
Heads up that this causes an error evaluating `nodePackages` due to: https://github.com/NixOS/nixpkgs/blob/c7b10b6df9f3d2b1c9833db13aa53d9973b0f030/pkgs/development/node-packages/node-packages.json#L197

That line should be removed and `./generate.sh` re-run to update the package set.

**Comment by davidak** [comment]
Strange that ofborg didn't catch that.

@armeenm can you do that?

**Comment by SuperSandro2000** [comment]
nodePackages is not evaluted by ofborg.

**Comment by armeenm** [comment]
Please review #172759

**Pull request merged**
