### PR TITLE
treewide: lib.concatStrings (lib.intersperse ...) -> lib.concatStringsSep …

### PR DESCRIPTION
**Pull request by polykernel**
Update all usage of lib.concatStrings (lib.intersperse ...) to
lib.concatStringsSep. This produces the same result as per https://github.com/NixOS/nixpkgs/pull/135843,
however it yields a performance benefit on Nix versions that
support the builtins.concatStringsSep primop.

###### Motivation for this change
The `concatStrings (intersperse ...)` effectively produces an intermediate result(which has to be strict) of what `builtins.concatStringsSep` does internally then proceeds to concatenate it using `concatStringsSep` using an empty string as the separator, this is wasteful on Nix versions with support for `builtins.concatStringsSep` which can inline this iteratively without an intermediate result.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Since which nix version is this supported?

**Comment by polykernel** [comment]
I believe it is supported since v1.10.

**Comment by r-burns** [comment]
It looks like the builtin has been available for 6 years: https://github.com/NixOS/nix/commit/2e8fd4c5cdeb59ae2bd403aa5069993303e8388e https://github.com/NixOS/nixpkgs/commit/6f6f66ac98218ed3061c75375784d12c5fceb687
and the lib function was added in 2007: https://github.com/NixOS/nixpkgs/commit/c5e1ae5eaf0cc67f3ea626bd4160150fa6ba6d7b#diff-4aecbadc9933d0cd7e981c6f8589433c9b828e9d0db237151592010b5a5dbc4eR41

**Comment by Mindavi** [comment]
That's a lot earlier than I thought. Sounds like a good idea to do this then 👍.

**Review by r-burns — APPROVED** [review]
Most of these could be further refactored to concatMapStringsSep, but not necessary of course.

0 rebuilds so LGTM

**Comment by polykernel** [comment]
> Most of these could be further refactored to concatMapStringsSep, but not necessary of course.
> 

I was going to do another treewide PR for that, but I wasn't sure as there is then a tradeoff for performance(specifically env allocations). I think it is better for the individual maintainer to balance maintainability and performance. What do you think?

**Comment by r-burns** [comment]
I assume the performance impact would be negligible, but we could always take a look at ofborg's performance report if that's a concern.

**Review by roberth — APPROVED** [review]
The performance benefit is tiny, but the change is good.

**Pull request merged**
