### PR TITLE
ida-free: remove icon due to hash mismatch

### PR DESCRIPTION
**Pull request by yadobler**
The "icon_free.png" that this derivative tries to pull for the shortcut icon keeps changing, causing different SHA values.

```
error: hash mismatch in fixed-output derivation '/nix/store/XXX-icon_free.png.drv':
         specified: sha256-widkv2VGh+eOauUK/6Sz/e2auCNFAsc8n9z0fdrSnW0=
            got:    sha256-oK++vjT4W+XsutWfR0hJeTxqoy4cdEqHBKEdZX2ylUI=
```

```
error: hash mismatch in fixed-output derivation '/nix/store/0pk9h8vvqxr4lcv6whnsgncdfdq6bjsp-icon_free.png.drv':
         specified: sha256-widkv2VGh+eOauUK/6Sz/e2auCNFAsc8n9z0fdrSnW0=
            got:    sha256-2PTGTOqYPyufIoosf3jmbJRrlpDJj+O1f593ZtN3spc=
```

I removed the fetching of the icon temporarily, but perhaps a better source can be used. Might be related to caching?

(apologies if I did not do this correctly, I did read through the contributing guidelines but might be lost a bit)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Shawn8901** [comment]
Hi, 
Thank you for your contribution.
About the contribution guidelines:
* PRs should target master branch, so please re base against it and change the target branch of the PR. https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#branch-conventions
* Commit messages should follow a structure https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions , so in your case something like `ida-free: remove icon` should fit the guidelines (tho I would add into the commit body why it's removed so that people can understand without opening a PR)

**Comment by Mindavi** [comment]
We sometimes use the internet archive or related services to pull a snapshot of things that keep changing, that might be a good alternative.

**Comment by msanft** [comment]
This is caused by the web archive being down, and Hex-Rays updating the icon on their site due to the IDA 9 release. I'm against removing the icon, but would favor if we removed the web archive mirror as long as it's down (due to the [attack](https://www.theverge.com/2024/10/9/24266419/internet-archive-ddos-attack-pop-up-message) on them) for the time being, until we can mirror the new icon again.

**Comment by yadobler** [comment]
> This is caused by the web archive being down, and Hex-Rays updating the icon on their site due to the IDA 9 release. I'm against removing the icon, but would favor if we removed the web archive mirror as long as it's down (due to the [attack](https://www.theverge.com/2024/10/9/24266419/internet-archive-ddos-attack-pop-up-message) on them) for the time being, until we can mirror the new icon again.

Ah makes sense. Yes I don't like it either. I was contemplating using another website but I don't want to without making sure I'm not breaking any copyright / permission issues. 

> Also, please remove the merge commit and rebase c8b5e9352ef81a2f65c57961b4c503aa9eea2ddf onto master instead.

My bad. Shouldn't have tried to sneak around rebasing - would be good if github allowed rebasing on the website.

 Will do so when back home!

**Comment by yadobler** [comment]
> We sometimes use the internet archive or related services to pull a snapshot of things that keep changing, that might be a good alternative.
> 
> I see actually that there's an archive service url inside already. What if only that one is kept?

I believe right now the first url retrieves the 404 page (which is causing the different `SHA256`), while the second one (archive) times out.

> due to the [attack](https://www.theverge.com/2024/10/9/24266419/internet-archive-ddos-attack-pop-up-message) on them) for the time being, until we can mirror the new icon again.

hm I just realised something. The installation packages are also [sourcing from archive](https://github.com/yadobler/nixpkgs/blob/patch-1/pkgs/by-name/id/ida-free/srcs.json). I just tried using this patch and it does error out as expected:
```
curl: (28) Failed to connect to web.archive.org port 443 after 135261 ms: Could not connect to server
error: cannot download idafree84_linux.run from any mirror
```

**Comment by msanft** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/349440

**Pull request closed without merging**
