### PR TITLE
pythonPackages: Add version and pname attributes to packages

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Adding `pname` and `version` attributes to `pythonPackages`.

A few days ago I wanted to check how up to date things were in `pythonPackages` so I split out the version into a separate attribute to be more easily parsable.
After seeing https://github.com/NixOS/nixpkgs/pull/31173 I did the same for pname. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
...and I was just rebasing this :)

**Comment by adisbladis** [comment]
@FRidh I'm happy to reopen.  :)
Just thought that three weeks and no feedback meant not much interest.

**Comment by FRidh** [comment]
Well, its quite a large PR and I don't have so much time anymore to spend on Nixpkgs. 

I've cherry-picked all the non-`python-packages.nix` changes for now. Its building at https://hydra.nixos.org/eval/1413023.

**Comment by FRidh** [comment]
@adisbladis if you like to do regexes, you up for one removing `name = ...;` from `python-modules`?

**Comment by FRidh** [comment]
Closing because the PR is by now outdated. I think we shouldn't bother with `python-packages.nix` as packages are being moved, and what is left in `python-packages.nix` is mostly unused packages.

**Pull request closed without merging**
