### PR TITLE
python3Packages.mpv: 1.0.1 -> 1.0.4

### PR DESCRIPTION
**Pull request by onny**
## Description of changes

Changes: https://github.com/jaseg/python-mpv/compare/v1.0.1...v1.0.4

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
@ofborg build python310Packages.mpv

**Comment by minijackson** [comment]
This PR broke the build of the `jellyfin-mpv-shim` package:

```
ERROR: Could not find a version that satisfies the requirement python-mpv (from jellyfin-mpv-shim) (from versions: none)
ERROR: No matching distribution found for python-mpv
```

Please be careful to run `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` to check for downstream breakage.

I think it has to do with https://github.com/jaseg/python-mpv/commit/d34b6252f7c3a02e9bcde8f690c0c8e941ef898d, where they renamed the package name, which is a breaking change.

@onny can you revert the changes? And check if other downstream user of python-mpv packages need contributions / patching before applying this update?

**Comment by onny** [comment]
Or we patch / update the broken packages?

**Comment by minijackson** [comment]
If this doesn't take too long, this works too.

I'm not sure how you can easily find packages depending on python-mpv easily without `nixpkgs-review`, though.

**Comment by marsam** [comment]
Sorry about that, it should be fixed by https://github.com/NixOS/nixpkgs/pull/247805

**Pull request merged**
