### PR TITLE
Beautify aliases

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@AndersonTorres please do major  0 rebuild refactors to master, doing merge conflicts on staging is incredibly error prone and exhausting. 

related: https://github.com/NixOS/nixpkgs/pull/158080
https://github.com/NixOS/nixpkgs/pull/158080/commits/46fd0afcb3474714eb73ab9ae576cfa1530afbcb
https://github.com/NixOS/nixpkgs/pull/158080/commits/9a16965c751b90e2674ba8bb8ec25582cf631f29

Also, looks like the sorting algorithm you used is different from `sort`, which I'm using to do merge conflicts

**Comment by jonringer** [comment]
https://github.com/NixOS/nixpkgs/pull/158080/commits/ac5b189b0c81ae0197d29964342808577d585f9f

**Comment by AndersonTorres** [comment]
Oh hell. I initially thought it would generate various useless rebuilds, therefore staging would be better than master.

**Comment by jonringer** [comment]
https://github.com/NixOS/nixpkgs/pull/158080/commits/5df08e00cd308a9a1630656d02ef75ba89b861ed

**Comment by jonringer** [comment]
https://github.com/NixOS/nixpkgs/pull/158080/commits/39669ea2b6de398c6bacee1e653a27934c5e1c3b

**Pull request merged**
