### PR TITLE
pipewire: 0.3.36 -> 0.3.38

### PR DESCRIPTION
**Pull request by jansol**
###### Motivation for this change

https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.37
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.38

Now with a correct version number.

Bugfixes, DSD passthrough support.

Bluetooth hardware db is now treated as a data file instead of media-session config and installed to the pipewire lib output. This should benefit wireplumber down the line.

This also updates libcamera to a commit that pipewire builds against (there were some header changes since the last packaged commit [that would break builds](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1435)) and add it to the pipewire build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jansol** [comment]
Not sure about backporting the libcamera stuff, it works if you add  but seems a bit wonky still and there hasn't been a stable release of libcamera yet anyway.

Libcamera node(s) show up with this in configuration.nix, if you have supported devices connected:
```
    services.pipewire.media-session.config.media-session."session.modules".default = [
      "flatpak"
      "portal"
      # "v4l2" # this is the default and the same devices should show up via this plugin
      "libcamera"
      "suspend-node"
      "policy-node"
    ];
```

**Review by Kranzes — APPROVED** [review]
Diff looks fine, haven't tested the changes.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 139451` at 44881966 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>easyeffects</li>
    <li>obs-studio-plugins.obs-ndi</li>
  </ul>
</details>
<details>
  <summary>68 packages skipped due to time constraints:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>chromium</li>
    <li>empathy (gnome.empathy)</li>
    <li>fast-cli</li>
    <li>firefox-esr-unwrapped (firefox-esr-78-unwrapped ,firefoxPackages.firefox-esr-78)</li>
    <li>firefox-esr-91-unwrapped (firefoxPackages.firefox-esr-91)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>kdev-php</li>
    <li>kdev-python</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>47 packages built successfully:</summary>
  <ul>
    <li>chrome-gnome-shell</li>
    <li>gnome.cheese</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-control-center (gnome.gnome_control_center)</li>
    <li>gnome.gnome-remote-desktop</li>
    <li>gnome.gnome-session (gnome.gnome_session)</li>
    <li>gnome.gnome-shell (gnome.gnome_shell)</li>
    <li>gnome.gnome-terminal (gnome.gnome_terminal)</li>
    <li>gnome.gnome-tweaks (gnome.gnome-tweak-tool)</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter338 (pantheon.mutter)</li>
    <li>gnome.pomodoro</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>helvum</li>
    <li>libsForQt5.kwin (libsForQt515.kwin ,plasma5Packages.kwin)</li>
    <li>libsForQt5.xdg-desktop-portal-kde (libsForQt515.xdg-desktop-portal-kde ,plasma5Packages.xdg-desktop-portal-kde)</li>
    <li>monitor</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>phoc</li>
    <li>pipewire</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
    <li>xdg-desktop-portal</li>
    <li>xdg-desktop-portal-gtk</li>
    <li>xdg-desktop-portal-wlr</li>
  </ul>
</details>

**Comment by jansol** [comment]
Haven't encountered any regressions in the past few days of using this.

**Comment by jansol** [comment]
For some reason readline doesn't seem to install a `.pc` file so it doesn't actually get picked up by meson? This causes pw-cli to not be built.

**Comment by jtojnar** [comment]
For some reason `readline` attribute points to readline6`. Pkg-config file is only available in ≥ 7.0.

**Comment by jansol** [comment]
Changed to `readline81` for now, that seems to be the latest one on unstable and 21.05. With this pw-cli builds again & works as far as I can tell.

I also dropped the explicit build flag for examples now that pipewire-media-session has been split out to its own component (controlled by the session-manager build flag).

**Pull request merged**
