### PR TITLE
haskell.compiler.ghc94: 9.4.4 -> 9.4.5

### PR DESCRIPTION
**Pull request by sternenseemann**
https://www.haskell.org/ghc/blog/20230418-ghc-9.4.5-released.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
```diff
--- pkgs/development/compilers/ghc/9.4.4.nix	2023-04-07 12:43:14.925903790 +0200
+++ pkgs/development/compilers/ghc/9.4.5.nix	2023-04-20 15:19:01.688124715 +0200
@@ -177,12 +177,12 @@
 assert stdenv.targetPlatform.isDarwin -> buildTargetLlvmPackages.clang == llvmPackages.clang;
 
 stdenv.mkDerivation (rec {
-  version = "9.4.4";
+  version = "9.4.5";
   pname = "${targetPrefix}ghc${variantSuffix}";
 
   src = fetchurl {
     url = "https://downloads.haskell.org/ghc/${version}/ghc-${version}-src.tar.xz";
-    sha256 = "e8cef25a6ded1531cda7a90488d0cfb6d780657d16636daa59430be030cd67e2";
+    sha256 = "6256cf9caf6d6dc7b611dcfbb247df2d528e85aa39d22a698e870e5a590e8601";
   };
 
   enableParallelBuilding = true;
```

**Comment by maralorn** [comment]
Is there a reason we are keeping and testing derivations for every minor version? I vaguely remember we didn’t do that for older ghc versions.

**Comment by sternenseemann** [comment]
@maralorn we only build the compilers for the 9.4 series. Doing a round of GHC removals is probably prudent (maybe after branch-off), but I want to do it independently of updating the GHCs. The 9.2 series has kind of confirmed this approach for me — we had a lot of bad bugs forcing us to roll back, still having the old versions is very useful then while the brave can use the most recent one anyways.

Built `haskell.packages.ghc945.haskell-language-server`, seems to work.

**Review by maralorn — APPROVED** [review]

**Comment by sternenseemann** [comment]
Great, wrong target; let's hope everything is okay.

**Pull request merged**
