### PR TITLE
[Backport master] tree-sitter: 0.20.8 -> 0.20.9

### PR DESCRIPTION
**Pull request by Kranzes**
## Description of changes

This is a backport of #284045 to master.

I accidentally sent it to staging instead of master after deciding with other contributors/maintainers that it should actually go straight to master. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
I think the decision referred to was [here](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$n2JOK3y1GcjgqAn04wxa5bbdiu40v3-TZUPXb5P8teg).

**Comment by vcunat** [comment]
> this is a blocker for neovim nightly for over 2 weeks now

Current nixpkgs master contains everything that was on `staging` branch 10 days ago, so I'm not sure where this "over 2 weeks" comes from.

**Comment by vcunat** [comment]
So far I'm inclined to say it's basically the same as Emacs packages, even with a large overlap in the rebuilt package sets at a quick glance:
https://github.com/NixOS/nixpkgs/pull/276943#issuecomment-1871165714

**Comment by Kranzes** [comment]
> > this is a blocker for neovim nightly for over 2 weeks now
> 
> Current nixpkgs master contains everything that was on `staging` branch 10 days ago, so I'm not sure where this "over 2 weeks" comes from.

I don't think you understood. neovim-nightly does not build without this tree-sitter version.

**Comment by Kranzes** [comment]
I decided to send it to master after discussing with a couple of other nixpkgs comitters/maintainers/contributors in the Matrix channel about it. They said that if since these PRs were usually sent to master (previous tree-sitter updates) and that almost all of the rebuilds are just text editor plugins then it should be fine. I can defer though.

**Comment by vcunat** [comment]
> They said that if since these PRs were usually sent to master (previous tree-sitter updates)

Big tree-sitter rebuilds merged to master recently?  I failed to find them quickly, but maybe I searched wrong
https://github.com/NixOS/nixpkgs/pulls?q=base%3Amaster+in%3Atitle+tree-sitter+is%3Amerged

**Comment by Kranzes** [comment]
For example: https://github.com/NixOS/nixpkgs/pull/225148

**Comment by vcunat** [comment]
That was in my listing.  But that was a year ago which doesn't match my "recently".

I let it pass.  But I'd really dislike such merges to become common, at least unless we have evidence that they really are cheap for the infra (I don't think they are).

**Pull request merged**
