### PR TITLE
Export haskellSrc2nix, hackage2nix. Prefer local builds. Name arg optional.

### PR DESCRIPTION
**Pull request by k0001**
###### Motivation for this change

See issue https://github.com/NixOS/nixpkgs/pull/22427 and https://github.com/NixOS/nixpkgs/pull/22469

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @peti @3noch

### CODE REVIEW

**Comment by peti** [comment]
I am not fond of the notion of exporting `hackage2nix` et al as-is. First of all, there is a Haskell program called `hackage2nix` which may very well get it's own package on Hackage, too, so would definitely have to think about other appropriate names for this function (and probably the other, too). Secondly, I have the impression that the architecture of those functions is not well though-out yet and I planned to make quite a few changes to them (which is why I did not expose them in the first place).

I guess we can expose those functions now and just break backwards-compatibility in the future if we want to. There's probably only a handful of people in the world who care about them, so it's not that big a deal. If we do, then we should definitely choose better names though.

**Comment by k0001** [comment]
@peti good points, and I agree that there are some naming issues, and we should definitely avoid name collisions. `nixFromHackage` and `nixFromCabal` maybe (c.f., `builtins.fromJSON`)?  

I think these functions are useful, though. I've used variants of the one currently called `haskellSrc2nix` in many of my Haskell projects, and it would be nice if it was exported here so that I don't have to redefine it over and over again. 

I can take a stab at those changes, if you care to share  your concerns with me.

**Comment by peti** [comment]
> `nixFromHackage` and `nixFromCabal`

Yes, I like those names much better than the ones we currently have. I'd be fine with exporting those.

**Comment by peti** [comment]
> I can take a stab at those changes, if you care to share your concerns with me.

The most important improvement is that I want to get rid of the dependency on the `all-cabal-hashes` repository. Instead of downloading all Cabal and JSON files for all versions of all Hackage packages at once, I'd rather download that *one* particular Cabal and JSON file that is needed to run `cabal2nix`. I'm not sure whether it's possible to pull that off, but it would be great if it were.

Another issue is that the `cabal2nix` binary used by these derivations is `pkgs.cabal2nix`, which has dependencies on stuff that we don't need in this context, like `nix-prefetch-scripts`, and I'd like to see a different `cabal2nix` used here that has a smaller closure. Maybe there should be a `cabal2nix-mini` or something.

**Comment by 3noch** [comment]
I like all your proposed changes. Go for it.

**Comment by mmahut** [comment]
Any update on this pull request?

**Comment by mmahut** [comment]
Closing due to lack of activity, feel free to reopen this if needed.

**Pull request closed without merging**
