### PR TITLE
python312Packages.matplotlib: 3.9.0 -> 3.9.1

### PR DESCRIPTION
**Pull request by doronbehar**
Changelog: https://github.com/matplotlib/matplotlib/releases/tag/v3.9.1

See also:

https://github.com/matplotlib/matplotlib/issues/28660#issuecomment-2268469345

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by doronbehar** [comment]
Evaluation seems to be broken on `staging` unrelated to this patch. I built all derivations in `python312Packages.matplotlib.passthru.tests` and I encountered this slightly related issue with `python312Packages.watchfiles`:

```
=================================== FAILURES ===================================
__________________________ test_watch_polling_not_env __________________________

self = <MagicMock name='RustNotify' id='140737314886896'>
args = (['.'], False, False, 300, True, False), kwargs = {}
expected = call(['.'], False, False, 300, True, False)
actual = call(['.'], False, True, 300, True, False)
_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x7ffff5aa87c0>
cause = None

    def assert_called_with(self, /, *args, **kwargs):
        """assert that the last call was made with the specified arguments.
    
        Raises an AssertionError if the args and keyword args passed in are
        different to the last call to the mock."""
        if self.call_args is None:
            expected = self._format_mock_call_signature(args, kwargs)
            actual = 'not called.'
            error_message = ('expected call not found.\nExpected: %s\n  Actual: %s'
                    % (expected, actual))
            raise AssertionError(error_message)
    
        def _error_message():
            msg = self._format_mock_failure_message(args, kwargs)
            return msg
        expected = self._call_matcher(_Call((args, kwargs), two=True))
        actual = self._call_matcher(self.call_args)
        if actual != expected:
            cause = expected if isinstance(expected, Exception) else None
>           raise AssertionError(_error_message()) from cause
E           AssertionError: expected call not found.
E           Expected: RustNotify(['.'], False, False, 300, True, False)
E             Actual: RustNotify(['.'], False, True, 300, True, False)

/nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/unittest/mock.py:944: AssertionError

During handling of the above exception, another exception occurred:

self = <MagicMock name='RustNotify' id='140737314886896'>
args = (['.'], False, False, 300, True, False), kwargs = {}

    def assert_called_once_with(self, /, *args, **kwargs):
        """assert that the mock was called exactly once and that that call was
        with the specified arguments."""
        if not self.call_count == 1:
            msg = ("Expected '%s' to be called once. Called %s times.%s"
                   % (self._mock_name or 'mock',
                      self.call_count,
                      self._calls_repr()))
            raise AssertionError(msg)
>       return self.assert_called_with(*args, **kwargs)
E       AssertionError: expected call not found.
E       Expected: RustNotify(['.'], False, False, 300, True, False)
E         Actual: RustNotify(['.'], False, True, 300, True, False)
E       
E       pytest introspection follows:
E       
E       Args:
E       assert (['.'], False..., True, False) == (['.'], False..., True, False)
E         
E         At index 2 diff: True != False
E         Use -v to get more diff

/nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/unittest/mock.py:956: AssertionError

During handling of the above exception, another exception occurred:

mocker = <pytest_mock.plugin.MockerFixture object at 0x7ffff5a918b0>

    def test_watch_polling_not_env(mocker):
        m = mocker.patch('watchfiles.main.RustNotify', return_value=MockRustNotify())
    
        for _ in watch('.'):
            pass
    
>       m.assert_called_once_with(['.'], False, False, 300, True, False)
E       AssertionError: expected call not found.
E       Expected: RustNotify(['.'], False, False, 300, True, False)
E         Actual: RustNotify(['.'], False, True, 300, True, False)
E       
E       pytest introspection follows:
E       
E       Args:
E       assert (['.'], False..., True, False) == (['.'], False..., True, False)
E         
E         At index 2 diff: True != False
E         Use -v to get more diff

tests/test_force_polling.py:32: AssertionError
=========================== short test summary info ============================
FAILED tests/test_force_polling.py::test_watch_polling_not_env - AssertionError: expected call not found.
============ 1 failed, 149 passed, 3 skipped, 1 deselected in 3.94s ============
/nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux/setup: line 1655: pop_var_context: head of shell_variables not a function context
```

Then, I disabled `test_watch_polling_not_env` test and I encountered this error:

```
=================================== FAILURES ===================================
_________________________________ test_awatch __________________________________

tmp_path = PosixPath('/build/pytest-of-nixbld/pytest-0/test_awatch0')
write_soon = <function write_soon.<locals>.start at 0x7ffff5630540>

    async def test_awatch(tmp_path: Path, write_soon):
        sleep(0.05)
        write_soon(tmp_path / 'foo.txt')
        async for changes in awatch(tmp_path, debounce=50, step=10, watch_filter=None):
>           assert changes == {(Change.added, str(tmp_path / 'foo.txt'))}
E           AssertionError: assert {(<Change.add...est_awatch0')} == {(<Change.add...ch0/foo.txt')}
E             
E             Extra items in the left set:
E             (<Change.modified: 2>, '/build/pytest-of-nixbld/pytest-0/test_awatch0')
E             Use -v to get more diff

tests/test_watch.py:42: AssertionError
------------------------------ Captured log call -------------------------------
watchfiles.main INFO: 2 changes detected
=========================== short test summary info ============================
FAILED tests/test_watch.py::test_awatch - AssertionError: assert {(<Change.add...est_awatch0')} == {(<Change.add...ch...
============ 1 failed, 148 passed, 3 skipped, 2 deselected in 3.81s ============
/nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux/setup: line 1655: pop_var_context: head of shell_variables not a function context
```

So I disabled `test_awatch` too. All this was done in [my `pkg/matplotlib@master` branch](https://github.com/NixOS/nixpkgs/compare/master...doronbehar:nixpkgs:pkg/matplotlib%40master?expand=1). CCing @fabaff as the maintainer of `python312Packages.watchfiles`.

**Comment by doronbehar** [comment]
Also, `sage-tests` fails:

```
sage-tests> ----------------------------------------------------------------------
sage-tests> sage -t --long --random-seed=59065449193823043700069897869983817452 /nix/store/g64qyrrhp5vigv3rna443dxbmw5j82cf-sage-src-10.3/src/sage/plot/plot.py  # 1 doctest failed
sage-tests> ----------------------------------------------------------------------
sage-tests> Total time for all tests: 1437.0 seconds
sage-tests>     cpu time: 17407.8 seconds
sage-tests>     cumulative wall time: 21175.3 seconds
sage-tests> Features detected for doctesting: conway_polynomials,cvxopt,database_ellcurves,database_graphs,fpylll,gap_package_atlasrep,gap_package_polycyclic,gfan,jmol,lrcalc_python,mpmath,nauty,networkx,numpy,palp,pexpect,pillow,polytopes_db,pplpy,primecountpy,ptyprocess,pyparsing,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.libs.braiding,sage.libs.ecl,sage.libs.flint,sage.libs.gap,sage.libs.linbox,sage.libs.m4ri,sage.libs.ntl,sage.libs.pari,sage.libs.singular,sage.misc.cython,sage.modular,sage.modules,sage.numerical.mip,sage.plot,sage.rings.complex_double,sage.rings.finite_rings,sage.rings.function_field,sage.rings.number_field,sage.rings.padics,sage.rings.polynomial.pbori,sage.rings.real_double,sage.rings.real_mpfr,sage.schemes,sage.symbolic,scipy,singular,sphinx,sympy,threejs
sage-tests> pytest is not installed in the venv, skip checking tests that rely on it
```

Which is also peculiar, as it is unrelated to matplotlib... ccing also @timokau @omasanori @7c6f434c & @collares .

**Comment by doronbehar** [comment]
@ofborg eval

**Comment by 7c6f434c** [comment]
Now aarch64-linux looks like a failure withing matplotlib tests? Not sure how fragile this test should be normally

**Comment by doronbehar** [comment]
> Now aarch64-linux looks like a failure withing matplotlib tests? Not sure how fragile this test should be normally

Oh I think this test failed also with 3.9.0 , and yes these tests are a bit fragile, but it's OK, this `passthru.tests.withOutdatedFreetype` derivation is not meant to be used by anyone, but rather only show us how much we are good. I'll leave it as is, since the fact that the other other tests pass and the fact even `sage` is green on x86_64-linux is good enough at this point.

**Pull request merged**
