### PR TITLE
perf-linux: fix error running python scripts by patching

### PR DESCRIPTION
**Pull request by aaronjheng**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aaronjheng** [comment]
Result of `nixpkgs-review pr 200473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.perf</li>
    <li>linuxKernel.packages.linux_4_14.perf</li>
    <li>linuxKernel.packages.linux_4_14_hardened.perf</li>
    <li>linuxKernel.packages.linux_4_19.perf</li>
    <li>linuxKernel.packages.linux_4_19_hardened.perf</li>
    <li>linuxKernel.packages.linux_4_9.perf</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>cargo-flamegraph</li>
    <li>linuxKernel.packages.linux_5_10.perf (linuxKernel.packages.linux_5_10_hardened.perf)</li>
    <li>linuxKernel.packages.linux_5_15.perf (linuxKernel.packages.linux_5_15_hardened.perf ,linuxKernel.packages.linux_hardened.perf)</li>
    <li>linuxKernel.packages.linux_5_4.perf</li>
    <li>linuxKernel.packages.linux_5_4_hardened.perf</li>
    <li>linuxKernel.packages.linux_6_0.perf (linuxKernel.packages.linux_6_0_hardened.perf)</li>
    <li>linuxKernel.packages.linux_latest_libre.perf</li>
    <li>linuxKernel.packages.linux_libre.perf</li>
    <li>linuxKernel.packages.linux_lqx.perf</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.perf</li>
    <li>linuxKernel.packages.linux_xanmod.perf</li>
    <li>linuxKernel.packages.linux_xanmod_latest.perf (linuxKernel.packages.linux_xanmod_stable.perf)</li>
    <li>linuxKernel.packages.linux_zen.perf</li>
    <li>qtcreator</li>
  </ul>
</details>

**Comment by trofi** [comment]
I would prefer pulling this patch from the upstream repository. Does it have a chance to be upstreamed?

**Comment by aaronjheng** [comment]
I'm learning to contribute to linux. :)

**Comment by aaronjheng** [comment]
But no promises. As far as I know, email is the only way to contributing kernel patches. I really don't like it.

**Pull request closed without merging**
