### PR TITLE
Update to openjdk8u31b13

### PR DESCRIPTION
**Pull request by cocreature**
If anybody happens to know how to keep track of openjdk releases, it would be great if they could tell me how. There doesn't seem to be anything apart from hg tags and there I am too stupid to figure out which ones are the stable ones. Anyway until I manage to find a better way I'll just track the arch pkgs.

### CODE REVIEW

**Comment by cocreature** [comment]
Travis failure is unrelated.

**Comment by cocreature** [comment]
I added a fix for i686 builds. Currently they fail.

**Comment by cocreature** [comment]
I also added the patch many distros use to get nonreparenting wms to work better.

**Comment by cocreature** [comment]
I think the travis failure is due to a timeout.

**Comment by shlevy** [comment]
I assume you've tested that this builds and everything?

**Comment by cocreature** [comment]
Yeah I'm actually using it right now.

**Pull request merged**
