### PR TITLE
nodePackages.perlnavigator: init at 0.6.0

### PR DESCRIPTION
**Pull request by WolfangAukang**
## Description of changes

Also tested on aarch64-darwin, only that I cannot post the results from nixpkgs-review as it is a work laptop.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 252821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>perlnavigator</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 252821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>perlnavigator</li>
  </ul>
</details>

**Review by lucasew — APPROVED** [review]

**Comment by lucasew** [comment]
Tested with helix (basically opened a perl file with helix inside nixpkgs-review shell)

Everything seems to be working as expected. Diagnostics, autocomplete and so on.

**Comment by natsukium** [comment]
Can we switch to a derivation using buildNpmPackage?

**Comment by WolfangAukang** [comment]
> Can we switch to a derivation using buildNpmPackage?

To be honest with you, I have no idea. Basically what I did to package this was pick ideas from some other LSPs (`nodePackages.{bash,yaml}-language-server`) I use with Helix. Is it the common standard now?

**Comment by WolfangAukang** [comment]
Also, I'm trying to use buildNpmPackage:
```
{ lib, buildNpmPackage, fetchFromGitHub }:

buildNpmPackage rec {
  pname = "perlnavigator";
  version = "0.6.0";

  src = fetchFromGitHub {
    owner = "bscan";
    repo = "PerlNavigator";
    rev = "v${version}";
    hash = "sha256-RMxM8g3ZdSt1B8WgwmcQgjpPZOCrVYYkhOt610SgbIw=";
  };

  npmDepsHash = "sha256-nEinmgrbbFC+nkfTwu9djiUS+tj0VM4WKl2oqKpcGtM=";

  dontNpmBuild = true;

  env = {
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = 1;
  };
}
```

From there, I get this:
```
npm ERR! code 1
npm ERR! path /build/source
npm ERR! command failed
npm ERR! command sh -c npm run-script install-client && npm run-script install-server && npm run-script install-browser
npm ERR! > perlnavigator@0.6.0 install-client
npm ERR! > cd client && npm install
npm ERR! npm ERR! code ENOTCACHED
npm ERR! npm ERR! request to https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm ERR!
npm ERR! npm ERR! Log files were not written due to an error writing to the directory: /nix/store/67jrd7g3psrarpiqm772axirk25dv865-perlnavigator-0.6.0-npm-deps/_logs
npm ERR! npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

npm ERR! Log files were not written due to an error writing to the directory: /nix/store/67jrd7g3psrarpiqm772axirk25dv865-perlnavigator-0.6.0-npm-deps/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

I really have no clue of what can be done so on, not even with the [documentation](https://nixos.org/manual/nixpkgs/stable/#javascript-tool-specific).

**Comment by dotlambda** [comment]
You should use separate derivations for the client, server, and browser-ext subdirectories. Then you should be able to link their `node_modules` into the correct place.

**Comment by WolfangAukang** [comment]
> You should use separate derivations for the client, server, and browser-ext subdirectories. Then you should be able to link their `node_modules` into the correct place.

This is still unclear to me. For example, if I build the derivation for the server by running `npm run install-server` on the `buildPhase`, I get the same error as pointed above. My doubt is: how can I add `wrappy`?

**Comment by dotlambda** [comment]
You have to use `buildNpmPackage` four times.

**Comment by WolfangAukang** [comment]
> You have to use `buildNpmPackage` four times. And then you probably have to remove the postinstall script from package.json.

I know this, and I'm only interested on the server part. What I'm on doubt is how to install something that is not listed on the `package.json`, which is the point where I was stuck in the beginning.

For example, I can ignore the scripts with `npmFlags = "--ignore-scripts"` and from there I don't have to consider the `postinstall` part, but now I get another package that is not listed on the `package.json` (`vscode-uri`). Should I patch the `package.json`?

**Comment by dotlambda** [comment]
> I know this, and I'm only interested on the server part.

Then you need an extra `buildNpmPackage` for the server subdirectory.



> now I get another package that is not listed on the `package.json` (`vscode-uri`).

That's used in the server subdirectory.

**Pull request closed without merging**
