### PR TITLE
kde-frameworks: 5.34 -> 5.36

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
KDE bugfix release

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
I applied this and https://github.com/NixOS/nixpkgs/pull/27532 and ran nix-build ./nixos/tests/plasma5.nix and it worked great. Any reason to not  merge this @ttuegel?

**Comment by ttuegel** [comment]
> I applied this and #27532 and ran nix-build ./nixos/tests/plasma5.nix and it worked great. Any reason to not merge this @ttuegel?

@grahamc Did you check this with #27491 too? I am building all three together to check; I would like to merge them simultaneously so they hit the channel at once. Let me know if you have already tested all three and I will go ahead and merge.

**Comment by grahamc** [comment]
I have not but could in a few hours.

**Comment by adisbladis** [comment]
@ttuegel I have built them all together and have been running it as my desktop for the last 9 days with no issues.

**Comment by ttuegel** [comment]
Merged via 2b29c893c12386b36a9cf9116eb6263b64bd470a.

**Pull request merged**
