### PR TITLE
Aws updates

### PR DESCRIPTION
**Pull request by Artturin**
Pr is on the staging master merge-base so target can be switched over to staging if needed.

Diff: https://www.github.com/awslabs/aws-c-auth/compare/v0.7.25...v0.7.29## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Artturin** [comment]
@ofborg build aws-sdk-cpp.passthru.tests

**Comment by Artturin** [comment]
`pkgsCross.aarch64-multiplatform.nix` on `x86_64-linux` passes.
`aws-sdk-cpp.passthru.tests` on `aarch64-linux` passes.

`aws-sdk-cpp.passthru.tests`  fails on `aarch64-darwin` with a flaky error same error as in https://github.com/NixOS/nixpkgs/issues/340087 which occurs before this PR

**Comment by r-burns** [comment]
Thanks for taking care of this update. Looks like it needs a merge conflict resolution, and while you're at it would you mind adding `# nixpkgs-update: no auto update` to all the packages so we don't need to keep fighting r-ryantm on these? https://github.com/NixOS/nixpkgs/pull/342725#issuecomment-2466547587 Happy to do this myself if you don't have time at the moment.

**Comment by Artturin** [comment]
But the news sdk update needs https://github.com/NixOS/nixpkgs/pull/350863 so I didn't update 5 days ago

**Comment by r-burns** [comment]
Ok sounds good, just let me know when you need a review. And again, happy to help out with anything here.

**Comment by Artturin** [comment]
cherry-pick the s2n-tls update if you want to checkout this branch locally and build because the merge-base is master staging
`git cherry-pick e65ff18e52b093cda46d922521778d1aea9e97c0`

**Comment by Artturin** [comment]
All `aws-sdk-cpp.tests` pass

**Review by r-burns — COMMENTED** [review]
Looks good and downstream dependers such as Nix still build (with s2n-tls cherry-picked). Would be nice to add `# nixpkgs-update: no auto update` to these if you're up for it.

**Pull request merged**
