### PR TITLE
emscripten: 3.1.45 -> 3.1.47, binaryen: 114 -> 116

### PR DESCRIPTION
**Pull request by willcohen**
## Description of changes

Bumped emscripten and binaryen to latest releases.
I've been having trouble with the `acorn` dependency on emscripten 3.1.45, something about it not being found as a dependency. Bumping these packages to latest versions as a first step. Requires an adjustment to lld 16 to accommodate 3.1.46+.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [X] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by willcohen** [comment]
@RaitoBezarius solving the missing acorn dependency required putting emscripten-node-modules's output inside emscripten directory, so that things like `tools/acorn-optimizer.js` have access to those modules.

**Comment by willcohen** [comment]
@RaitoBezarius does this look okay? There won't be any more point releases to LLVM 16, so I don't think any of that can get backported at this point, and LLVM 17 is a ways off for stability in nix, I assume.

**Comment by RaitoBezarius** [comment]
Yes, will try to review this in the next hours / days.

**Review by RaitoBezarius — APPROVED** [review]

**Comment by willcohen** [comment]
Thank you!

**Comment by RaitoBezarius** [comment]
Thank YOU as always for your patience and your help. :)

**Pull request merged**
