### PR TITLE
adapta-gtk-theme: 3.21.2 -> 3.21.3.1

### PR DESCRIPTION
**Pull request by severen**
###### Motivation for this change

New release of package.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X (N/A)
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by SShrike** [comment]
Hmm, turns out there are some new dependencies, I'll have to package the Ruby sass package as well.

Any recommendations on what the package name should be for the Sass RubyGem package? ruby-sass?

**Comment by SShrike** [comment]
The above commit isn't intended to fix the build BTW, still need to package the Sass RubyGem.

**Comment by zimbatm** [comment]
Is it a build time or runtime requirement?

**Comment by SShrike** [comment]
Build time, it's used for compiling SASS to CSS I believe (GTK+ uses CSS for theming).

**Comment by zimbatm** [comment]
Did you try adding sass to the buildInputs ? Looks like it's already been packaged.

**Comment by SShrike** [comment]
Yep, maybe there's a problem with the packaging?

**Comment by zimbatm** [comment]
I got it a bit further (see 42e579622fc43d4e09df2921d89a2ff68271dacc). The "bundle exec" would use the version in the project instead of the provided-one. I also had to bump the version to solve encoding issues in the sass files.

Now it's complaining that some files cannot be copied:
```
cp: cannot stat './asset/assets-gtk3/calendar-day-selected@2.png': No such file or directory
cp: cannot stat './asset/assets-gtk3/calendar-day-selected.png': No such file or directory
cp: cannot stat './asset/assets-gtk3/checkbox-active-selectionmode@2.png': No such file or directory
```

**Comment by SShrike** [comment]
Is it only certain files, or all of them?

**Comment by zimbatm** [comment]
There are some assets copying successfully

**Comment by SShrike** [comment]
I wonder if it's a problem with the projects Makefiles and such?

**Comment by SShrike** [comment]
Perhaps this [script](https://github.com/tista500/Adapta/blob/master/autogen.sh) does something special?

**Comment by SShrike** [comment]
#16988 has obsoleted this PR.

**Pull request closed without merging**
