### PR TITLE
Kernels 2021-03-31

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Updates

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Waiting for hardened patch set

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login kernel-latest-ath-user-regd latestKernel.hardened

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login kernel-latest-ath-user-regd latestKernel.hardened

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Comment by ivan** [comment]
5.10.27-hardened1 seems to work fine in my two vmware NixOS master machines.

**Comment by NeQuissimus** [comment]
Backport in 20.09 in b103839d00505bbaa9f9beff26e3d0f6a3abf6df...e67e6a0e8a269a2b4d2ecbaec779f05dece6e089

**Pull request merged**
