### PR TITLE
nixos: doc module: add devdoc

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Discussion in #11501. This is a continuation of #38114.

###### Things done

- [X] It works.
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxij** [comment]
ping

**Review by Profpatsch — APPROVED** [review]
Looks good to me!
Care has to be taken that not too many dependencies are pulled in (do we need `texinfoInteractive`)?

**Comment by oxij** [comment]
> Care has to be taken that not too many dependencies are pulled in (do we need `texinfoInteractive`)?

1) It was there before even before I started.

Indeed, it is kinda questionable whenever we actually want to build two `texinfo`s for every system (for `stdenv` and the interactive one), but we do that for a bunch of other stuff too (e.g. `bash` and `w3m`). Changing this policy is out of scope of this PR.

2) It is optional. If you disable `.info.enable` it won't be pulled in.
3) How are you going to read the info files without it?

**Comment by Profpatsch** [comment]
> 3) How are you going to read the info files without it?

That’s a good point. :)

LGTM!

**Pull request merged**
