### PR TITLE
python3Packages.somajo: init at 2.0.4

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

SoMaJo is a tokenizer for German and English web text and is quite popular in the German NLP community. Including this package is very low-impact, since it only relies on the Python `regex` package.

The sources are retrieved from GitHub (rather than PyPI), so that we can run its test suite.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
the python38 tests seem to hang, not sure if upstream is aware

**Comment by danieldk** [comment]
> the python38 tests seem to hang, not sure if upstream is aware

Strange! Works without issues on my machine (with sandboxing).

**Comment by jonringer** [comment]
hmm, the other two completed in 1-2 minutes, killed python38 after 10

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.somajo python38Packages.somajo

**Comment by jonringer** [comment]
if ofborg can build it, then I'm okay with it

**Comment by danieldk** [comment]
Updated to 2.0.4. @jonringer , this version fixes a race condition https://github.com/tsproisl/SoMaJo/commit/fa67aa70a208316378940a872083bd2282927ad4 , maybe this was the hang that you ran into?

**Comment by jonringer** [comment]
could have been

**Review by jonringer — APPROVED** [review]
LGTM
commit LGTM
has test :+1: 

```
[4 built, 1 copied (1.3 MiB), 0.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/81279
2 package built:
python37Packages.somajo python38Packages.somajo
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build python37Packages.somajo python38Packages.somajo

**Pull request merged**
