### PR TITLE
python3Packages.pyads: 3.2.2 -> 3.3.7

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 3.3.7

Change log: https://github.com/stlehmann/pyads/releases/tag/3.3.7

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125932` at e7dfc3b4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.pyads</li>
    <li>python39Packages.pyads</li>
  </ul>
</details>

**Comment by risicle** [comment]
This package is another case where the tests pass on macos as long as they're not run at the same time as another instance, exposing the weakness of sandboxing there. If e.g. the 3.8 and 3.9 packages are built in parallel they compete for the same port number and fail with:

```
>       self.server.bind((self.ip_address, self.port))
E       OSError: [Errno 48] Address already in use
```

One solution might be to fix it to choose a random port number in the tests.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 125932` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.pyads</li>
    <li>python39Packages.pyads</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 125932` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.pyads</li>
    <li>python39Packages.pyads</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Going to ignore the darwin parallel failure for now because it would probably require bigger code changes.

**Pull request merged**
