### PR TITLE
tinymist: 0.11.1 -> 0.11.2

### PR DESCRIPTION
**Pull request by LamprosPitsillos**
Diff: https://github.com/Myriad-Dreamin/tinymist/compare/v0.11.1...v0.11.2

## Description of changes
bumped tinymist to 0.11.2

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by LamprosPitsillos** [comment]
Doesn't build with the following error...
```
❯ nix build .#tinymist
error: builder for '/nix/store/hdk5crswdwk3qw10m58gm77cgvdg85b3-cargo-vendor-dir.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/4ggdwd0rk0yqp6lzrk5101v7d40kx4js-cargo-vendor-dir/typst-syntax-0.11.0/2k92nkhkr4d1f7wx9ldbbxq1dwnydf80-typst-syntax-0.11.0': Permission denied
       For full logs, run 'nix log /nix/store/hdk5crswdwk3qw10m58gm77cgvdg85b3-cargo-vendor-dir.drv'.
error: 1 dependencies of derivation '/nix/store/xq5a5b1v41xl4vlykkv32cmrhhyhcqm6-tinymist-0.11.2.drv' failed to build
```

**Comment by LamprosPitsillos** [comment]
Result of `nixpkgs-review pr 300279` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>tinymist</li>
    <li>vscode-extensions.myriad-dreamin.tinymist</li>
  </ul>
</details>

**Review by drupol — CHANGES_REQUESTED** [review]
@LamprosPitsillos Have you updated the corresponding VSCode extension? (look at the comment on top of line 16)

**Comment by LamprosPitsillos** [comment]
> * vscode-extensions.myriad-dreamin.tinymist

No i didn't know the VScode plugin existed.
I will try to as soon as the main package builds

**Comment by drupol** [comment]
Closed in favor of #302085

**Pull request closed without merging**
