### PR TITLE
buildDotnetPackage: fix nativeBuildInputs

### PR DESCRIPTION
**Pull request by Artturin**
the nativeBuildInputs of the derivation that uses buildDotnetPackage overshadowed the nativeBuildInputs of buildDotnetPackage
so pkg-config wasn't getting added to the path

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by taktoa — APPROVED** [review]

**Review by layus — APPROVED** [review]

**Comment by Artturin** [comment]
btw the keepass build is not reproducible because something saves the timestamp. and the lib version changes randomly?
```
--- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1
+++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check
│   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib
├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib
│ │   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/dotnet
│ ├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib/dotnet
│ │ │   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/dotnet/keepass
│ │ ├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib/dotnet/keepass
│ │ │ │   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/dotnet/keepass/KeePass.exe
│ │ │ ├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib/dotnet/keepass/KeePass.exe
│ │ │ │ ├── pedump {}
│ │ │ │ │ @@ -1,12 +1,12 @@
│ │ │ │ │  
│ │ │ │ │  COFF Header:
│ │ │ │ │  	                Machine: 0x014c
│ │ │ │ │  	               Sections: 0x0003
│ │ │ │ │ -	             Time stamp: 0x618d7e37
│ │ │ │ │ +	             Time stamp: 0x618d7e48
│ │ │ │ │  	Pointer to Symbol Table: 0x00000000
│ │ │ │ │  	   	   Symbol Count: 0x00000000
│ │ │ │ │  	   Optional Header Size: 0x00e0
│ │ │ │ │  	   	Characteristics: 0x0022
│ │ │ │ │  
│ │ │ │ │  PE Header:
│ │ │ │ │  	         Magic (0x010b): 0x010b
│ │ │ │   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/dotnet/keepass/KeePassLib.dll
│ │ │ ├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib/dotnet/keepass/KeePassLib.dll
│ │ │ │ ├── pedump {}
│ │ │ │ │ @@ -1,12 +1,12 @@
│ │ │ │ │  
│ │ │ │ │  COFF Header:
│ │ │ │ │  	                Machine: 0x014c
│ │ │ │ │  	               Sections: 0x0003
│ │ │ │ │ -	             Time stamp: 0x618d7e33
│ │ │ │ │ +	             Time stamp: 0x618d7e45
│ │ │ │ │  	Pointer to Symbol Table: 0x00000000
│ │ │ │ │  	   	   Symbol Count: 0x00000000
│ │ │ │ │  	   Optional Header Size: 0x00e0
│ │ │ │ │  	   	Characteristics: 0x2022
│ │ │ │ │  
│ │ │ │ │  PE Header:
│ │ │ │ │  	         Magic (0x010b): 0x010b
│ │   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/pkgconfig
│ ├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib/pkgconfig
│ │ │   --- /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/pkgconfig/KeePassLib.pc
│ │ ├── +++ /nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1.check/lib/pkgconfig/KeePassLib.pc
│ │ │ @@ -1,6 +1,6 @@
│ │ │  Libraries=/nix/store/n9ayklqngh4byr7ybgclydxi3wl6x0mn-keepass-2.48.1/lib/dotnet/keepass/KeePassLib.dll
│ │ │  
│ │ │  Name: KeePassLib
│ │ │  Description: KeePassLib
│ │ │ -Version: 2.48.1.37017
│ │ │ +Version: 2.48.1.37026
│ │ │  Libs: -r:KeePassLib.dll
```

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 145533` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gdata-sharp</li>
    <li>monodevelop</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>eventstore</li>
  </ul>
</details>
<details>
  <summary>58 packages built:</summary>
  <ul>
    <li>alttpr-opentracker</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>dafny</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnetPackages.FuzzyLogicLibrary</li>
    <li>dotnetPackages.MaxMindDb</li>
    <li>dotnetPackages.MaxMindGeoIP2</li>
    <li>dotnetPackages.MonoAddins</li>
    <li>dotnetPackages.MonoNat</li>
    <li>dotnetPackages.NUnit</li>
    <li>dotnetPackages.NUnit3</li>
    <li>dotnetPackages.NUnitConsole</li>
    <li>dotnetPackages.NUnitRunners</li>
    <li>dotnetPackages.NewtonsoftJson</li>
    <li>dotnetPackages.Nuget</li>
    <li>dotnetPackages.OpenNAT</li>
    <li>dotnetPackages.Paket</li>
    <li>dotnetPackages.RestSharp</li>
    <li>dotnetPackages.SharpFont</li>
    <li>dotnetPackages.SharpZipLib</li>
    <li>dotnetPackages.SmartIrc4net</li>
    <li>dotnetPackages.StyleCopMSBuild</li>
    <li>dotnetPackages.StyleCopPlusMSBuild</li>
    <li>github-runner</li>
    <li>jellyfin</li>
    <li>keepass</li>
    <li>midisheetmusic</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>openraPackages.engines.bleed</li>
    <li>openraPackages.engines.playtest</li>
    <li>openraPackages.mods.ca</li>
    <li>openraPackages.mods.d2</li>
    <li>openraPackages.mods.dr</li>
    <li>openraPackages.mods.gen</li>
    <li>openraPackages.mods.kknd</li>
    <li>openraPackages.mods.mw</li>
    <li>openraPackages.mods.ra2</li>
    <li>openraPackages.mods.raclassic</li>
    <li>openraPackages.mods.rv</li>
    <li>openraPackages.mods.sp</li>
    <li>openraPackages.mods.ss</li>
    <li>openraPackages.mods.ura</li>
    <li>openraPackages.mods.yr</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pash</li>
    <li>pinta</li>
    <li>python-language-server</li>
    <li>python38Packages.pythonnet</li>
    <li>python39Packages.pythonnet</li>
    <li>ryujinx</li>
    <li>wasabibackend</li>
  </ul>
</details>
only pre-existing failures

**Review by layus — APPROVED** [review]
Still okay for me, in the absence of a way to know if it breaks cross compilation. I would expect mono to be a buildInput too.

**Comment by Artturin** [comment]
> Still okay for me, in the absence of a way to know if it breaks cross compilation. I would expect mono to be a buildInput too.

This actually fixes cross compilation (if everything g up to this crosscompiles and mono works when crosscompiling)

**Pull request merged**
