### PR TITLE
uhd: 3.14.0.0 -> 3.15.0.0

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Update + Make uhd's build more configurable.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]
Nit: I don't see why we need uhd to be so configurable (i.e. all the device flags), but it's not important.

**Comment by tomberek** [comment]
Some of the options make the ensuing binary much smaller. Like removing
some of the X300 images. This can matter when trying to deploy to small
distributed systems.

**Comment by doronbehar** [comment]
Thanks for your approval @bjornfor , `nixpkgs-review` says:

```
https://github.com/NixOS/nixpkgs/pull/84183
21 package built:
cubicsdr gnss-sdr gnuradio gr-ais gr-gsm gr-limesdr gr-nacl gr-osmosdr gr-rds gnuradio-with-packages gqrx inspectrum python27Packages.soapysdr-with-plugins python37Packages.soapysdr-with-plugins python38Packages.soapysdr-with-plugins qradiolink rtl_433 soapysdr-with-plugins soapyuhd uhd welle-io
```

**Comment by doronbehar** [comment]
The build results nixpkgs-review produced  are available via cachix - https://app.cachix.org/cache/r-doronbehar . These are the store paths :

```
/nix/store/a1mfghg17c35zjymw94ss6gjv6ld3cav-cubicsdr-0.2.5
/nix/store/6lv58x9irx3s0z9f8pks2dd857sx6p71-gnss-sdr-0.0.12
/nix/store/rhz0rhh0cwsn0jr72062lpzy777v91w8-gnuradio-3.7.13.4
/nix/store/jfa970wxbgcd40cpwlk6i3g465lyb9f5-gnuradio-with-packages-3.7.13.4
/nix/store/89ra553vr0wji38v7mjxsy2a1pkz3ny1-gqrx-2.12.1
/nix/store/mzhckdi2z168ca08i4xn35p40hx9qq2g-gr-ais-2015-12-20
/nix/store/57vmp2mpn9wfxy8ghpzxymsjhwjkq77k-gr-gsm-2016-08-25
/nix/store/n4gabmh92jxyi4j6qqvb8nm4pkp717ly-gr-limesdr-2.0.0
/nix/store/y8fcwca9wya3m7wwcgv3rs4c5cmxy48h-gr-nacl-2017-04-10
/nix/store/lmjf3nyzjhiyg309qd318aasih810lmc-gr-osmosdr-0.1.5
/nix/store/va8fp58n6w3lnjhi3j6j50nj9p84vzgp-gr-rds-1.1.0
/nix/store/8mqhgi3pc4xb0hf5rb1pjk2i6lp0frj8-inspectrum-unstable-2017-05-31
/nix/store/61rv46l61zrrm0krsf80zg9c7l365hr0-soapysdr-0.7.2
/nix/store/x4rahjk1kjsqb70fp8vcy14wkkkz17ps-soapysdr-0.7.2
/nix/store/jhxbk7x4isgl9zvgrmyjpsb6y23jg8as-soapysdr-0.7.2
/nix/store/vz3drcqyalk7fjcsapm0hsfli5kgkqdd-qradiolink-0.5.0
/nix/store/mhgj435889mcqw2s82zj192h5p0zyj7i-rtl_433-20.02
/nix/store/2032nydl2xss7a88mcnsr2vmw31dipvq-soapysdr-0.7.2
/nix/store/h5s8y981i24hbdwxbm3faj1rilc54d4m-soapyuhd-0.3.6
/nix/store/5cp9kbk9ssy777azygi3fcnfp79xf349-uhd-3.15.0.0
/nix/store/hvxw09f2ifb0ppq3awaz9krzxmlvzlhp-welle-io-2.1
```

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Review by bjornfor — APPROVED** [review]

**Pull request merged**
