### PR TITLE
incus: 6.5.0 -> 6.6.0

### PR DESCRIPTION
**Pull request by bbigras**
https://github.com/lxc/incus/releases/tag/v6.6.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bbigras** [comment]
```
       > (finished: must succeed: incus admin init --minimal, in 1.97 seconds)
       > subtest: Container image can be imported
       > machine: must succeed: incus image import /nix/store/9740vmwys36c9i9nw1sk9qv24gzw0l0c-tarball/tarball/nixos-system-x86_64-linux.tar.xz /nix/store/9xnkfwani933jgjyfrf9gicp0715jzjs-nixos-lxc-image-x86_64-linux/nixos-lxc-image-x86_64-linux.squashfs --alias nixos
       > machine # Error: read unix @->/var/lib/incus/unix.socket: i/o timeout
       >
       > Test "Container image can be imported" failed with error: "command `incus image import /nix/store/9740vmwys36c9i9nw1sk9qv24gzw0l0c-tarball/tarball/nixos-system-x86_64-linux.tar.xz /nix/store/9xnkfwani933jgjyfrf9gicp0715jzjs-nixos-lxc-image-x86_64-linux/nixos-lxc-image-x86_64-linux.squashfs --alias nixos` failed (exit code 1)"
       > cleanup
       > kill machine (pid 10)
       > qemu-kvm: terminating on signal 15 from pid 7 (/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/bin/python3.12)
       > (finished: cleanup, in 11.55 seconds)
       > kill vlan (pid 8)
       For full logs, run 'nix log /nix/store/ba50k8wjalh771747lnhbf6z8x334bna-vm-test-run-container-legacy-init.drv'.
```

**Comment by bbigras** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346210`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>incus</li>
    <li>incus.agent_loader</li>
  </ul>
</details>

**Comment by adamcstephens** [comment]
x86
/nix/store/1g43pqcjbpy08qnvqwcglp6lvjsycd27-vm-test-run-container-legacy-init
/nix/store/pgv8kcblq4cwhig4av5fga983zfxqznl-vm-test-run-container-systemd-init
/nix/store/y0kypvwh6jpfrsfch83svr9wb9rzm110-vm-test-run-incusd-options
/nix/store/dkrkqwkq771zwl29c1m99qx9y82w2hm3-vm-test-run-lxd-to-incus
/nix/store/cmp8cklg39qpsipzx9kp62k2ar3fch58-vm-test-run-incus-openvswitch
/nix/store/dh6rpnl8kdfch4zpz35hlfblmcaam8hm-vm-test-run-incus-socket-activated
/nix/store/law4h9imhg85z4sz6vx3dmvizqp6f2ww-vm-test-run-incus-storage
/nix/store/v3074lpjcc7k5a7dvrw74ald3fpccv1m-vm-test-run-incus-ui
/nix/store/nn5anbqy04vwaz77jxv9vgw4if3ngi8j-vm-test-run-incus-virtual-machine

aarch64
/nix/store/82j8zga99hk0wv3qy40nakvh9h9kdx1g-vm-test-run-container-legacy-init
/nix/store/04185yga2zrfrg0kbq3v986r70fh3fx6-vm-test-run-container-systemd-init
/nix/store/mh1m6h2fj8nkshfs6r8ins7l660ya2bv-vm-test-run-incusd-options
/nix/store/1w0yqla342bcpzd2mqhpliq16sri7jag-vm-test-run-lxd-to-incus
/nix/store/y01z0fa9ydgb0n01f50v9p2a3akgiilw-vm-test-run-incus-openvswitch
/nix/store/k18wvyf8x8rkrf3q5aiyvn3v4z5a58gw-vm-test-run-incus-socket-activated
/nix/store/6i72csyvnmzvjqc4qrfn42p6mkdgpjsc-vm-test-run-incus-storage
/nix/store/6890bd8bpvl8rwnwp77r0h116ywwnnd6-vm-test-run-incus-ui

**Comment by adamcstephens** [comment]
The tests are much more important than a review of downstream packages :)

**Pull request merged**
