### PR TITLE
python311Packages.jedi: disable some tests

### PR DESCRIPTION
**Pull request by tjni**
###### Description of changes

Disabling tests that fail in Python 3.11 until https://github.com/davidhalter/jedi/issues/1858 is resolved. We can also enable "test_completion" since it now passes in 0.18.2 (I believe it's due to https://github.com/davidhalter/jedi/commit/78a53bf005e45df295109d7a04da893bfa646eb6).

Needed by https://github.com/NixOS/nixpkgs/issues/198533#issuecomment-1296918471.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The passthrough test needs a format set.

**Comment by tjni** [comment]
> The passthru test derivation needs a format set.

I don't see a passthru test derivation on `jedi`. I updated the one in my separate PR for `attrs`.

**Comment by mweinelt** [comment]
I read the eval-lib-tests log and it was probably for some other package. *sigh*

**Comment by mweinelt** [comment]
Cherry-picked into python-updates.

**Pull request closed without merging**
