### PR TITLE
Update Keybase software

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Requested in https://github.com/NixOS/nixpkgs/issues/50999

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by c0bw3b — APPROVED** [review]

**Comment by worldofpeace** [comment]
cc @colemickens @jonafato (for testing)

**Review by rvolosatovs — APPROVED** [review]
`kbfs` and `keybase` CLI seem to work fine. Didn't try the GUI.

**Comment by worldofpeace** [comment]
Sounds good, merging.

**Comment by devhell** [comment]
Got a message from keybase telling me that this needs updating to 2.11 (apparently they'll disable old version access, or so they claim). I'm currently in no position to do any testing, which is why I'm mentioning it here.

**Comment by jonafato** [comment]
It looks like this change is already on `nixos-unstable`, `nixos-unstable-small`, `nixos-18.09`, and `nixos-18.09-small`, but it still needs to be added to `nixpkgs-unstable`.

**Pull request merged**
