### PR TITLE
discord: 0.0.14 -> 0.0.15

### PR DESCRIPTION
**Pull request by wearemnr**
###### Motivation for this change
Update Discord: 0.0.14 -> 0.0.15

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124336` at bc170801 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>discord</li>
    <li>discord-canary</li>
    <li>discord-ptb</li>
  </ul>
</details>

**Review by Atemu — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 124336 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>3 packages built:</summary>  <ul>    <li>discord</li>    <li>discord-canary</li>    <li>discord-ptb</li>  </ul></details>

**Comment by ldesgoui** [comment]
I think we want to backport this to 20.09, should I create the PR or can we use #124273 already?

**Comment by domenkozar** [comment]
It won't work if the base branch doesn't have the action yet.

**Comment by JulesdeCube** [comment]
probably propagate it to the unstable branch to ?

**Comment by Atemu** [comment]
What do you mean by that?

**Comment by ldesgoui** [comment]
@JulesdeCube it's propagating https://nixpk.gs/pr-tracker.html?pr=124336

**Comment by JulesdeCube** [comment]
thanks

**Comment by jonringer** [comment]
The linking errors were fixed in https://github.com/NixOS/nixpkgs/pull/124425
https://nixpk.gs/pr-tracker.html?pr=124425

**Pull request merged**
