### PR TITLE
inboxer: 1.0.0 -> 1.0.2

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 1.0.2 with grep in /nix/store/r58bhh86hprpzb4fh5xk0snaqgbqa8vy-inboxer-1.0.2
- found 1.0.2 in filename of file in /nix/store/r58bhh86hprpzb4fh5xk0snaqgbqa8vy-inboxer-1.0.2

cc "@mgttlinger"

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build inboxer

**Comment by mgttlinger** [comment]
Does the bot not evaluate the `platforms` field or why does it try to build on all platforms?

**Comment by ryantm** [comment]
@grahamc ^

**Comment by ryantm** [comment]
@mgttlinger In one sense, it's nice because it reminds us it doesn't work cross platform yet.

**Comment by mgttlinger** [comment]
@ryantm yeah but trying to start a build that immediately fails because the platform isn't in the list doesn't seem like the most efficient way to accomplish that.

**Pull request merged**
