### PR TITLE
[20.09] firefox: 84.0.2 -> 85.0; firefox-esr: 78.6.1esr -> 78.7.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://www.mozilla.org/en-US/firefox/85.0/releasenotes/

Backport #110984 

###### Things done

- [x] Ran the nixos test for stable and esr
- [x] Tested on x86_64-linux Wayland with Pipewire
- [x] Tested on x86_64-linux X11
- [ ] Tested on aarch64

cc @ajs124 @taku0 @vcunat @lovesegfault

### CODE REVIEW

**Comment by taku0** [comment]
`nix-build -I nixpkgs=. -A pkgs.firefox` results in `ERROR: Rust compiler 1.44.1 is too old.`. It requires `1.47.0` or newer.

**Comment by mweinelt** [comment]
I have no experience backporting rustc, can someone recommend how to proceed?

**Comment by lovesegfault** [comment]
Pinging rustc maintainers: @madjar @cstrahan @globin @Havvy

**Review by vcunat — APPROVED** [review]
- aarch64: verified the build on `aarch64.nixos.community`  (EDIT: finished after original post)
- x86_64: `nixosTests.firefox` builds, switched my main browser to this build a while ago (X11 NixOS)

**Comment by mweinelt** [comment]
- x86_64: `firefox-wayland` builds, run testing it now, but looks to be working (yt, pipewire, cam, mic).

**Comment by lovesegfault** [comment]
I was about to merge this, but noticed the `Merge branch 'release-20.09'` commit, are we okay with merging these commits back?

Idk what the policy is

**Pull request merged**
