### PR TITLE
haskellPackages.hercules-ci-agent: nixPackage 2.14 -> 2.16, haskellPackages.{cachix,hercules-ci-agent}: fix build

### PR DESCRIPTION
**Pull request by Kranzes**
###### Description of changes
[haskellPackages.hercules-ci-agent: nixPackage 2.14 -> 2.16](https://github.com/NixOS/nixpkgs/pull/240532/commits/ca0091f00ba635f486185f2613face27c5699052)
[haskellPackages.{cachix,hercules-ci-agent}: fix build](https://github.com/NixOS/nixpkgs/pull/240532/commits/65f90b5469e0b036262d21822c942f71274f897a)

###### Things done

-  <details>
   <summary>Tested hercules-ci-agent:</summary>
    
   </details>
- Tested `hci`
- Tested Cachix

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
@ofborg eval

**Comment by cdepillabout** [comment]
`haskellPackages.hercules-ci-agent` doesn't appear to build because it depends on `cachix`, which is currently broken.  Would you be able to fix `cachix`?

**Comment by Kranzes** [comment]
> `haskellPackages.hercules-ci-agent` doesn't appear to build because it depends on `cachix`, which is currently broken. Would you be able to fix `cachix`?

I don't have prior experience with that, but I can give it a try!

cc. @domenkozar

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 240532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>cachix</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>hercules-ci-agent.data</li>
  </ul>
</details>

**Pull request merged**
