### PR TITLE
nodejs-argon: init at 2.4.1, nodejs-4_1: renamed to nodejs-stable

### PR DESCRIPTION
**Pull request by Havvy**
I'm currently trying to get this to build, but waiting on gcc. ;.;  I think it'll build properly though, since it's just pulling the current nodejs default.nix into its own package.

I also replaced the nodejs-4_1 package with a nodejs-stable package, since tracking each individual minor release seems like it's not worth it, and the nodejs-4_1 package is pointing at 4.2.1 right now (which is the same as argon, but nodejs-stable will be updated to 5.0.0 at some point)

These changes (along with the removal of io.js awhile back) should be documented somewhere.

I'm not sure what to put in the commit message for this.

### CODE REVIEW

**Comment by Havvy** [comment]
TravisCI failed because of the 10,000 line console output limit.

**Comment by Havvy** [comment]
Couldn't build locally because the `openssl = openssl_2_0_1;` got removed at some point. Also removed `v8` as an argument to `argon.nix` since we let Node.js use its own version of v8 which has its own backported patches. Should also be removed from nodejs-stable, but I'll do that when I update it to v5.0.0.

**Comment by Havvy** [comment]
TravisCI failed because of the 10,000 line console output limit (again).

**Comment by lethalman** [comment]
I'd prefer using version numbers instead of codenames...

**Comment by garbas** [comment]
i think this PR is obsolete. please reopen if i'm wrong

**Pull request closed without merging**
