### PR TITLE
rustc: 1.72.1 -> 1.73.0

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

This upgrade unfortunately removes MIPS support, as it has been [dropped to Tier 3][1] and so bootstrap tarballs are no longer provided.

It looks like it was dropped due to multiple codegen bugs, and lack of maintenance, so bringing it back would probably involve engaging with Rust/LLVM upstream on those.

[1]: https://github.com/rust-lang/compiler-team/issues/648

- [x] fd on x86_64-darwin
- [x] fd on x86_64-linux
- [x] fd on aarch64-linux
- [x] firefox on x86_64-linux
- [x] thunderbird on x86_64-linux

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]
LGTM.

**Comment by alyssais** [comment]
Oh, one thing — usually we stick to the same LLVM as Rust upstream, but we don't have LLVM 17 yet (see https://github.com/NixOS/nixpkgs/pull/258614).  IIRC we've been an LLVM behind for Rust before and it hasn't caused any problems.

**Comment by workingjubilee** [comment]
> Oh, one thing — usually we stick to the same LLVM as Rust upstream, but we don't have LLVM 17 yet (see #258614). IIRC we've been an LLVM behind for Rust before and it hasn't caused any problems.

Yes, in the general case we have tried to support using "today's LLVM and yesterday's LLVM" with rustc, with a "maybe" on yesteryear's LLVM. This has been really inconvenient sometimes with certain major LLVM changes like the opaque pointers or pass manager updates, but it seems nothing earthshattering is in LLVM 17, by comparison.

This is also part of why it's undesirable to have a mostly-unmaintained target being advertised as tier 2: even if all the codegen problems got patches in flight _right now_, they might not see a release until LLVM 18, depending on LLVM's patch cycle. So we'd only be confident we wouldn't get reports for them after we updated to LLVM 19 and then dropped LLVM 17.

**Review by figsoda — APPROVED** [review]
tried testing on darwin, but the build box kept running out of disk space, lgtm on linux

**Comment by evanrichter** [comment]
> tried testing on darwin, but the build box kept running out of disk space, lgtm on linux

works for me on my aarch64-darwin host

**Comment by amjoseph-nixpkgs** [comment]
> This upgrade unfortunately removes MIPS support, as it has been [dropped to Tier 3](https://github.com/rust-lang/compiler-team/issues/648) and so bootstrap tarballs are no longer provided.

:sob:

**Comment by amjoseph-nixpkgs** [comment]
Heads up, this bump breaks cross compilation of `crate2nix`-driven projects in a very weird way:

- https://github.com/nix-community/crate2nix/issues/313

If you use crate2nix to cross compile you might need to stick to 1.72.1 until we figure out what went wrong here.

**Pull request merged**
