### PR TITLE
vimPlugins.vim-pets: init

### PR DESCRIPTION
**Pull request by heywoodlh**
## Description of changes

Added [vim-pets](https://github.com/MeF0504/vim-pets)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
Please fix the merge conflict by regenerating this.

**Comment by heywoodlh** [comment]
I didn't realize you were waiting on me for this @superherointj, I apologize. I've rebased off of latest main and have re-run `nix run .#vimPluginsUpdater`. Please let me know what else you need from me on this.

**Comment by superherointj** [comment]
@heywoodlh Please ask for a review from someone related to the Vim ecosystem. I suggest you use git history and add reviewers that have altered the vim files. I won't be proceeding with review here since my familiarity in vim ecosystem is limited. And also, the delays between your answers leads me to lose context.

**Comment by PerchunPak** [comment]
> Please ask for a review from someone related to the Vim ecosystem.

I am willing to review

---

Please, drop the last 3 commits and include changes only related to this plugin:

```nix
  # generated.nix
  vim-pets = buildVimPlugin {
    pname = "vim-pets";
    version = "2024-07-26";
    src = fetchFromGitHub {
      owner = "MeF0504";
      repo = "vim-pets";
      rev = "17d33f160c8fd3fb6492e7cd76f397ddaa26ad8d";
      sha256 = "0zn6kf088kqfdf5y0x6sd8rr3skrjwppsdfxmf044qk1h07lcgcc";
    };
    meta.homepage = "https://github.com/MeF0504/vim-pets/";
  };
```

**Comment by heywoodlh** [comment]
@PerchunPak, I believe I have done what you requested on the latest push, please let me know if you need any further follow up from me.

**Comment by PerchunPak** [comment]
Result of `nixpkgs-review pr 260055` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.vim-pets</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by PerchunPak — APPROVED** [review]
LGTM! Thanks!

[CC](https://github.com/NixOS/nixpkgs/pull/333817#issuecomment-2294798601) @GaetanLepage

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 260055` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.vim-pets</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Pull request merged**
