### PR TITLE
treewide: fix buildGoModule packages on darwin

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/82787 enabled strictDeps for buildGoModule expressions which broke a few packages

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build act aerc age amass archiver argo argocd atlantis aws-vault awsweeper azure-storage-azcopy bazelisk berglas caddy caddy2 cassowary certigo chezmoi circleci-cli clair clash conftest coredns corerad croc ctop cue dbmate dive dnsproxy docui documize-community dolt drone-cli drone echoip editorconfig-checker eksctl elvish exercism fluxctl fly flyctl frp geoipupdate ghq gitAndTools.gh gitAndTools.ghq gitAndTools.git-bug gitAndTools.git-subtrac gitAndTools.lab gitAndTools.lefthook glow go-ethereum go-license-detector go-tools gobetween gobuster golangci-lint gomuks gortr gotify-cli gotify-server grpcui hcloud hetzner-kube hey hugo hydroxide iamy imgproxy ipfs-cluster ipfs joker jx k9s kcli kepubify kubeprompt kubernetes-helm kubeseal kubeval kustomize lefthook lego linkerd lnd matterbridge mautrix-whatsapp minify minikube minio-client minio mkcert mod mtail mutagen mynewt-newt nebula obfs4 packr pet pgcenter pgmetrics prometheus-dnsmasq-exporter prometheus-mikrotik-exporter prometheus-varnish-exporter proto-contrib protoc-gen-doc prototool prow qbec reviewdog saml2aws sensu-go-agent sensu-go-backend sensu-go-cli shadowfox shiori smimesign sops syncthing-cli syncthing-discovery syncthing-relay syncthing tendermint termshark terracognita terraform-providers.elasticsearch tflint thanos todoist victoriametrics websocketd wtf yggdrasil zsh-history

**Comment by marsam** [comment]
@GrahamcOfBorg build act aerc age amass archiver argo argocd atlantis aws-vault awsweeper azure-storage-azcopy bazelisk berglas caddy caddy2 cassowary certigo chezmoi circleci-cli clair clash conftest coredns corerad croc ctop cue dbmate dive dnsproxy docui documize-community dolt drone-cli drone echoip editorconfig-checker eksctl elvish exercism fluxctl fly flyctl frp geoipupdate ghq gitAndTools.gh gitAndTools.ghq gitAndTools.git-bug gitAndTools.git-subtrac gitAndTools.lab gitAndTools.lefthook glow go-ethereum go-license-detector go-tools gobetween gobuster golangci-lint gomuks gortr gotify-cli gotify-server grpcui hcloud hetzner-kube hey hugo hydroxide iamy ipfs-cluster ipfs joker jx k9s kcli kepubify kubeprompt kubernetes-helm kubeseal kubeval kustomize lefthook lego linkerd lnd matterbridge mautrix-whatsapp minify minikube minio-client minio mkcert mod mtail mutagen mynewt-newt nebula obfs4 packr pet pgcenter pgmetrics prometheus-dnsmasq-exporter prometheus-mikrotik-exporter prometheus-varnish-exporter proto-contrib protoc-gen-doc prototool prow qbec reviewdog saml2aws sensu-go-agent sensu-go-backend sensu-go-cli shadowfox shiori smimesign sops syncthing-cli syncthing-discovery syncthing-relay syncthing tendermint termshark terracognita terraform-providers.elasticsearch tflint thanos todoist victoriametrics websocketd wtf yggdrasil zsh-history

**Comment by Mic92** [comment]
This was caused by propagatedBuildInputs not propagating from nativeBuildInputs.
We propagate those frameworks from the go compiler over buildGoModule to the packages.

**Comment by Mic92** [comment]
We could add them to `buildGoModule` instead since most go packages need them anyway.

**Comment by Mic92** [comment]
cc @LnL7 @Ericson2314

**Comment by Mic92** [comment]
On the other hand they are now included explicitly which may also be an advantage.

**Comment by Ericson2314** [comment]
You can use `depsTargetTargetPropagated` to do this if you like.

> On the other hand they are now included explicitly which may also be an advantage.

Is this a dependency of the go standard library, or a more optional go library?

**Comment by Mic92** [comment]
> You can use `depsTargetTargetPropagated` to do this if you like.
> 
> > On the other hand they are now included explicitly which may also be an advantage.
> 
> Is this a dependency of the go standard library, or a more optional go library?

It comes from the go standard library, when TLS is used in the application.

**Comment by Ericson2314** [comment]
Well, unless there is an upstream way for go packages to declare they only will use parts of the standard library, I'd think the `depsTargetTargetPropagated` way is better.

**Pull request merged**
