### PR TITLE
Update io.js

### PR DESCRIPTION
**Pull request by valeriangalliat**
Update io.js to 1.3.0 (and update nightly version too).

I also added a script to automatically find the latest io.js stable/nightly versions and update the Nix expression (including hashs). Is `mainteners/scripts` the ritgh place for this?

### CODE REVIEW

**Comment by lethalman** [comment]
maintainers/scripts is more for general tools, and nobody will find your script for iojs. Put it in the same dir of iojs.

**Comment by valeriangalliat** [comment]
Updated!

**Comment by valeriangalliat** [comment]
Updated again, just a fix in the update script because it was only working when run from the root of nixpkgs directory (now can be called from anywhere).

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
