### PR TITLE
[Backport release-22.05] openssl_3: enable KTLS only on Linux

### PR DESCRIPTION
**Pull request by vcunat**
This fixes build on *-darwin.

### CODE REVIEW

**Comment by vcunat** [comment]
Opening just to get more verification from ofBorg.
@OfBorg build openssl_3

**Comment by vcunat** [comment]
Hmm, let me promote this to a normal backport PR now (though not automatic).

**Comment by vcunat** [comment]
Example failure log: https://hydra.nixos.org/log/595waz9gzlbkmvx2qfc5pflb9x8791iq-openssl-3.0.7.drv

**Comment by zach-sherman** [comment]
What's the status on merging this? I would really appreciate having a working openssl_3 on my mac again! Thanks for all the work you do and fixing this quickly :)

**Comment by vcunat** [comment]
Ah well, I'm not fond of self-merging very fast without getting any reviews.

**Pull request merged**
