### PR TITLE
darwin.stdenv: drop curl from the bootstrap

### PR DESCRIPTION
**Pull request by reckenrode**
The Darwin bootstrap currently requires curl, but it is not strictly required. The bootstrap requires it for two things:

* Fetchers; and
* As a transitive dependency of llvm-manpages (via Sphinx).

For the fetchers, the bootstrap curl can be used. For hatch-vcs, the dependency, its tests can be disabled. Doing this allows curl to be dropped from the Darwin stdenv bootstrap.

Closes #276762.

Tested by building the stdenvs against staging. I then changed the name of `curl` and did a new build, confirming that it only triggered a rebuild of curl and not the whole stdenv.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by reckenrode** [comment]
The evaluation issue should be fixed once https://github.com/NixOS/nixpkgs/pull/295557 is merged.

**Comment by a-n-n-a-l-e-e** [comment]
So i think you could move forward with this change by removing the overlay https://github.com/NixOS/nixpkgs/blob/3551c607f454ee855e54db5686464c8dcf83ceae/pkgs/stdenv/darwin/make-bootstrap-tools.nix#L3-L18 which is causing the eval failure and then you won't be depending on my change.

**Comment by reckenrode** [comment]
> So i think you could move forward with this change by removing the overlay
> 
> https://github.com/NixOS/nixpkgs/blob/3551c607f454ee855e54db5686464c8dcf83ceae/pkgs/stdenv/darwin/make-bootstrap-tools.nix#L3-L18
> 
> which is causing the eval failure and then you won't be depending on my change.

Would changing the overlay affect your PR? If you’re getting close, this one can wait for it.

**Comment by a-n-n-a-l-e-e** [comment]
> Would changing the overlay affect your PR? If you’re getting close, this one can wait for it.

it will not conflict as i remove the overlay as well. my PR is ready to go but i'd like to resolve the open comments before committing.

**Comment by reckenrode** [comment]
@ofborg eval

**Review by ghost — APPROVED** [review]

**Pull request merged**
