### PR TITLE
ghc 8.8.3, 8.8.4, 8.10.1: disable profiled builds on aarch64 to avoid 2GB output limit (backport)

### PR DESCRIPTION
**Pull request by ggreif**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build haskell.compiler.ghc883 haskell.compiler.ghc884 haskell.compiler.ghc8101

**Comment by ggreif** [comment]
@domenkozar Is this a good idea? Can it break stuff on the release branch?

**Comment by domenkozar** [comment]
Yeah, for those that rely on profiled builds it will.

**Comment by ggreif** [comment]
OfBorg is not particularly happy with aarch64...

**Comment by ggreif** [comment]
@vcunat any idea why this is going wrong? Is GHC supported for aarch64 at all on the 20.03 release branch?

**Comment by vcunat** [comment]
These ghc branches apparently aren't supported there.  They're bootstrapped from 8.6.3-binary which does not have aarch64 version.  On master that was solved by 5180ec350 (after 3c7ef6bc).

**Comment by ggreif** [comment]
Thanks @vcunat, closing this PR as pointless then.

**Pull request closed without merging**
