### PR TITLE
urbit: 0.7.4 -> 0.8.0

### PR DESCRIPTION
**Pull request by jtobin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtobin** [comment]
Does anyone have any advice re: the CI failure here?

In particular, I don't know why the following should be failing like it is (I can't replicate it locally): 

```
cannot import '/nix/store/2jh23bskfidsxs3qcfcahm9kim7d5v7i-source', since path '/nix/store/fg9c5ffzm245w8xpdwryr5k2rgvq5fdr-source.drv' is not valid, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-0-gleber.ewr1.nix.ci/pkgs/misc/urbit/default.nix:16:11
```

**Comment by msutherl** [comment]
@jtobin the error seems to reference 'not listing outputs', and I noticed there are no outputs declared at all. The workings of this thing are a lot more complicated than I have time to figure out, but it would appear [each of these](https://github.com/urbit/urbit/tree/master/pkg) might be construed as an output?

https://nixos.org/nixpkgs/manual/#chap-multiple-output

**Comment by jtobin** [comment]
@msutherl I think the CI error message might be a bit misleading; the overall check is an "output path comparison," but it doesn't seem to get far enough to actually check any output paths (which shouldn't be problematic).  The problem *appears* to be in importing the derivation retrieved via `fetchFromGitHub` -- but this seems to be a CI-only issue, because it works fine locally.

I'll take a look for other derivations in nixpkgs that use this kind of pattern and see if they have any information to add.

**Comment by jtobin** [comment]
@GrahamcOfBorg build urbit

**Comment by msutherl** [comment]
This now needs to be bumped to `0.8.1`

**Comment by jtobin** [comment]
(Closing this one pending resolution of urbit/urbit#1369)

**Pull request closed without merging**
