### PR TITLE
llvm_39: fix on darwin

### PR DESCRIPTION
**Pull request by acowley**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

We need xpc, to pin down which libtool to use (to avoid an Xcode
dependency), and ensure that the build does not try to produce i386
binaries.

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]

**Comment by matthewbauer** [comment]
I think something similar would also work to get "rust" working again on Darwin.

**Review by LnL7 — APPROVED** [review]
I prefer to inherit specific darwin derivations into the callPackage scope, instead of using the `darwin` attribute directly.

**Comment by acowley** [comment]
I, too, used to prefer that, but one can run into name collisions (or near collisions), so I've been trying out maintaining the name hierarchy for the past few months and found it easier to work with.

**Review by globin — APPROVED** [review]

**Comment by vcunat** [comment]
Can you re-test this after d2965a7d8 from staging? (It also introduces a simple merge conflict.)

**Comment by LnL7** [comment]
@vcunat master looks good, but staging fails with https://gist.github.com/LnL7/9097f240bdb67d4686bcdfc72b0efd09

**Comment by vcunat** [comment]
I wasn't really paying attention to Darwin code before. Perhaps with this atop:
```diff
diff --git a/pkgs/development/compilers/llvm/3.9/llvm.nix b/pkgs/development/compilers/llvm/3.9/llvm.nix
index 22dea61..bf154d1 100644
--- a/pkgs/development/compilers/llvm/3.9/llvm.nix
+++ b/pkgs/development/compilers/llvm/3.9/llvm.nix
@@ -86,8 +86,9 @@ in stdenv.mkDerivation rec {
       --replace "\''${_IMPORT_PREFIX}/lib/libLLVM-" "$lib/lib/libLLVM-"
   ''
   + stdenv.lib.optionalString (stdenv.isDarwin && enableSharedLibraries) ''
-    install_name_tool -id $out/lib/libLLVM.dylib $out/lib/libLLVM.dylib
-    ln -s $out/lib/libLLVM.dylib $out/lib/libLLVM-${version}.dylib
+    moveToOutput "lib/libLLVM.dylib" "$lib"
+    install_name_tool -id "$lib/lib/libLLVM.dylib" "$lib/lib/libLLVM.dylib"
+    ln -s "$lib/lib/libLLVM.dylib" "$lib/lib/libLLVM-${version}.dylib"
   '';
 
   enableParallelBuilding = true;
```

**Comment by acowley** [comment]
I'll have to start this over again at some point and try to get it merged more quickly so it doesn't get clobbered.

**Pull request closed without merging**
