### PR TITLE
bottomify: init at 1.2.0

### PR DESCRIPTION
**Pull request by bootstrap-prime**
###### Motivation for this change
A meme was missing.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121446` at 1e15d843 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/ec8f25768266b69846127245d5951bf5">bottomify</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by bootstrap-prime** [comment]
ofborg and my machine disagree on what hash should be used here, so something is weird. I'll give up and if someone more talented than I wishes to mess with it, feel free.

**Comment by jonringer** [comment]
> ofborg and my machine disagree on what hash should be used here, so something is weird. I'll give up and if someone more talented than I wishes to mess with it, feel free.

2 things could be happening. Files with unicode characters will create different sha when using HPFS (Apple) vs other file systems. Or, your sha is out of date, however, since there's already an FOD with that sha locally, nix isn't pulling in the latest FOD because there's "already one in the cache".

**Comment by bootstrap-prime** [comment]
even after setting the hash to what ofborg complains it isn't, and nix-collect-garbage -d'ing, it demands the hash that I changed it from. the ofborg message I pulled the hash from says its x86-linux and I'm on ntfs so it shouldn't be that either.

**Pull request closed without merging**
