### PR TITLE
Update my pkgs

### PR DESCRIPTION
**Pull request by matthiasbeyer**
**NOTE**: Some of these packages do not yet build. If someone could help me investigate, I'd appreciate that. AFAICS, `dulwich` does not build and this also causes `klaus` to fail building.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
If you require help to get things building, please provide a paste of the build error you're seeing.

**Comment by matthiasbeyer** [comment]
```
======================================================================
ERROR: test_non_ascii (dulwich.tests.test_refs.DiskRefsContainerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-dulwich-0.13.0.drv-0/dulwich-0.13.0/dulwich/tests/test_refs.py", line 443, in test_non_ascii
    encoded_ref = u'refs/tags/schön'.encode(sys.getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 13: ordinal not in range(128)

----------------------------------------------------------------------
Ran 1062 tests in 64.837s

FAILED (errors=1, skipped=13)
builder for ‘/nix/store/vjw5iijhy9zhzci26vbk5c6msimd7wla-python2.7-dulwich-0.13.0.drv’ failed with exit code 1
error: build of ‘/nix/store/vjw5iijhy9zhzci26vbk5c6msimd7wla-python2.7-dulwich-0.13.0.drv’ failed
```

**Comment by DamienCassou** [comment]
Try to add that to your failing derivation:

```nix
{
    LC_ALL = "en_US.UTF-8";
    buildInputs = with self; [ pkgs.glibcLocales ];
}
```

**Comment by joachifm** [comment]
Suggestion: factor out the updates that do build so we can merge them.

**Comment by matthiasbeyer** [comment]
Will do this tomorrow, to tired right now.

**Comment by FRidh** [comment]
progress?

**Comment by matthiasbeyer** [comment]
Ups, forgot about this one. Will do today, as I have a build machine at hand anyways, so I might be able to figure out what's going on.

**Comment by matthiasbeyer** [comment]
Rebased, the updates build on my build machine (debian 8 with nix installed) on master (as the commits are).

**Pull request merged**
