### PR TITLE
Enforce nixfmt on new files and changed files that were already formatted

### PR DESCRIPTION
**Pull request by infinisil**
## Description of changes

This is a big step towards full implementation of NixOS/rfcs#166, see also https://github.com/NixOS/nixfmt/issues/153. This is split off from https://github.com/NixOS/nixpkgs/pull/322537 (the first big treewide reformatting), because there's no need to have it be in the same PR. This PR should be reviewed/merged by the @NixOS/nix-formatting team.

This PR makes the Nix format workflow check _all_ new files and changed files (that were already formatted) to be formatted.

## Things done
- [x] Check that it works: https://github.com/tweag/nixpkgs/pull/95
- [ ] Optionally have a pre-commit/push hook, see https://github.com/NixOS/nixfmt/issues/221
- [x] Make a Discourse post announcing this: https://discourse.nixos.org/t/enforcing-nix-formatting-in-nixpkgs/49506

---

This work is sponsored by [Antithesis](https://antithesis.com/) :sparkles:

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Pandapip1** [comment]
> This PR should only be merged after the other one is merged. 

Shouldn't this be the other way round? First, nixfmt is enforced for new files, then the treewide PR is merged?

**Comment by infinisil** [comment]
@Pandapip1 If we first require all new/changed files to be formatted without doing the treewide format, anybody branching off master would have to format all of the files they're touching to make their PR valid.

The other way around is also not entirely great, because we shouldn't merge PRs that mess up the newly-formatted files either.

Really, these two PRs should be merged around the same time so that both of these problems can be avoided. Splitting it into two PRs is mainly done to make reviewing easier, because the other one is so big (and entirely automated), whereas this one is more tricky.

**Comment by infinisil** [comment]
Oh, just noticing a problem: If we start doing this, we need to have `all-packages.nix` (and similarly often updated files) formatted, because otherwise somebody else will have to format it and cause merge conflicts for everybody else. https://github.com/NixOS/nixpkgs/pull/322537 is "smart" by avoiding any conflicts, but for the case of often updated files this backfires.

My proposed solution to this is to change this PR to enforce formatting of changed files only if they were previously formatted already, so that e.g. it wouldn't be enforced for all files that aren't part of the treewide reformat, including `all-packages.nix`. We can deal with these special files in the future at some point instead.

**Comment by Pandapip1** [comment]
> @Pandapip1 If we first require all new/changed files to be formatted without doing the treewide format, anybody branching off master would have to format all of the files they're touching to make their PR valid.

How about this: CI checks if files that are already nixfmt-rfc-style-compliant have become non-compliant, or if a new non-compliant file has been added?

**Comment by MattSturgeon** [comment]
I think https://github.com/NixOS/nixfmt/issues/179 may block this and https://github.com/NixOS/nixpkgs/pull/322537, because the `/* lang */` tagging pattern is [apparently](https://github.com/NixOS/nixfmt/issues/179#issuecomment-2031258187) used a lot in the test suite.

e.g:

https://github.com/NixOS/nixpkgs/blob/0bf815b4fc91e03d7247e9a21740678b1fac961d/nixos/tests/switch-test.nix#L8-L10

**Comment by infinisil** [comment]
@MattSturgeon This isn't relevant for this PR, since it wouldn't enforce formatting on files that have `/* foo */` comments in them. Furthermore, I don't think it's a blocker for the treewide format PR either, because treesitter also supports `# foo`-style comments for syntax hints.

**Review by tomberek — APPROVED** [review]

**Comment by felbinger** [comment]
These changes seam to break https://github.com/NixOS/nixpkgs/pull/313671.

image

Running the suggested command (see below) resolves in no changes. I tried using `nixfmt` and `nixfmt-rfc-style`.
```
nixfmt 'nixos/modules/services/networking/suricata/default.nix' 'nixos/modules/services/networking/suricata/settings.nix' 'nixos/tests/suricata.nix'
```
Any idea how I could fix this problem?

**Comment by MattSturgeon** [comment]
> Running the suggested command (see below) resolves in no changes

Are you doing this in the nix shell introduced in #322512? That should provide a `nixpkgs` on your PATH locked to the same version used by the CI.

Also, just to eliminate the obvious, are you running the command from the right location for those relative paths?

**Comment by MattSturgeon** [comment]
> Even though i don't really understand whats the difference between it and `nix-shell -p nixfmt-rfc-style`

In most cases there should be no tangible difference, afaik. However in some cases the version used by the shell (and CI) may be different to the version in nixos-unstable.

**Pull request merged**
