### PR TITLE
nuspell: 4.0.1 -> 4.2.0

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by omasanori — APPROVED** [review]
Result of `nix path-info -S`
```
/nix/store/kp07g7dikb9my3x67l43zqpp1z4w2jp6-nuspell-4.0.1	   92477088
/nix/store/6sq7cx9vzdxzjppsnpkl4w7c9w32irhc-nuspell-4.1.0	   92504448
```
Result of `nixpkgs-review pr 104291` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nuspell</li>
  </ul>
</details>

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.155-1.pvops.qubes.x86_64, Fedora, 32 (Thirty Two)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201118_79aa7d9`
 - channels(user): `"nixpkgs-21.03pre252431.4f3475b113c"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

**Comment by bbigras** [comment]
Updated to 4.2.0. Boost is not needed anymore

**Comment by avdv** [comment]
Result of `nixpkgs-review pr 104291` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nuspell</li>
  </ul>
</details>

**Review by avdv — APPROVED** [review]
LGTM

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104291` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nuspell</li>
  </ul>
</details>

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
