### PR TITLE
python3Packages.django_3: 3.2.9 -> 3.2.10; python3Packages.django_2: 2.2.24 -> 2.2.25

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://www.djangoproject.com/weblog/2021/dec/07/security-releases/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Will need to do the backport for nixos-21.05 by hand, since django_3 is on 3.2.5 there.

**Comment by mweinelt** [comment]
Classified as low severity, so fine to go via staging.

**Comment by mweinelt** [comment]
@ofBorg test paperless-ng

**Comment by risicle** [comment]
(tested when this was on `master`)

`nixpkgs-review` revealed no new failures for packages matching `.*django.*` on macos 10.15, nixos x86_64 and aarch64 emulated.

**Review by jonringer — APPROVED** [review]
LGTM

```
[17:55:28] jon@nixos ~/projects/nixpkgs (python/django)
$ nix-build -A nixosTests.paperless-ng
/nix/store/psvgf5bcfz7j8jdl3c8lyzl7zmfayckc-vm-test-run-paperless-ng
```

**Pull request merged**
