### PR TITLE
[Backport release-23.11]: Rust 1.75.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Description of changes

This packages the rust toolchain for 1.75.0 for the stable channel.

Rationale is that I'd like to see a fair number of packages being backported to the stable nixos release, though they do not build with older rust toolchains, for example:

* https://github.com/NixOS/nixpkgs/pull/292569
* https://github.com/NixOS/nixpkgs/pull/291580
* https://github.com/NixOS/nixpkgs/pull/291071
* https://github.com/NixOS/nixpkgs/pull/290447
* https://github.com/NixOS/nixpkgs/pull/289518
* https://github.com/NixOS/nixpkgs/pull/288298

The idea here is to package 1.75.0, then backport the packages and modify them to be built with that newer version of the rust toolchain.
The idea is _not_ to alter the default rust toolchain on stable.

---

If this gets rejected for whatever reason (please tell tho), I am fine with that, since I learned a lot writing these patches :laughing: 

---

FWIW, the `rust_1_75.packages.stable.rustc` attribute has been test-built by me on `x86_64-linux`.
I also tried to backport https://github.com/NixOS/nixpkgs/pull/290447 and modify it to build with that newer toolchain, but for whatever reason I did not yet understand it tries to rebuild the toolchain (although it has been built already) and then fails with

```
       > error: the argument '--jobs <JOBS>' cannot be used multiple times
       >
       > Usage: x.py build [OPTIONS] [PATHS]... [-- <ARGS>...]
       >
       > For more information, try '--help'.
       > Build completed unsuccessfully in 0:00:12
       > make: *** [Makefile:19: all] Error 1
```

:eyes: 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilylange** [comment]
Would be cool if someone could review and merge this, since #297543 (chromium backport, security) depends on this now :)

**Review by RaitoBezarius — CHANGES_REQUESTED** [review]
Commits does not adhere to CONTRIBUTING guide.

**Comment by matthiasbeyer** [comment]
Updated the commit messages a bit, but I am still not happy with them (and they probably do not adhere to the guide still).

Either way, this does not work anyways, I PRd this for someone to look at and help.

**Comment by emilylange** [comment]
Closing since #298206 has been merged instead.

**Pull request closed without merging**
