### PR TITLE
scilab-bin: refactor

### LINKED ISSUE #210916: Scilab unable to load shared library libtinfo.so.5
### Describe the bug
When I run Scilab it shows this error and does not run:
```console
scilab-bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
This fixed when I installed `libtinfo5` from APT.

### Steps To Reproduce
1. Install `scilab-bin`
2. Run `scilab`

### Expected behavior
Run.

### Additional context
`libtinfo` is not in nix repository.

### Notify maintainers

@wegank

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-1-amd64, Debian GNU/Linux, noversion, nobuild`
```

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Closes #210916.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NickCao — APPROVED** [review]

**Comment by NickCao** [comment]
@mskf1383 would you like to check if everything works fine now?

**Comment by mskf1383** [comment]
How can I check?

**Comment by NickCao** [comment]
`nix run "github:NixOS/nixpkgs?ref=pull/211867/head#scilab-bin"` if you are using flake.

**Comment by mskf1383** [comment]
I get this error:
```
SCI environment variable not defined.
```

**Comment by wegank** [comment]
> `nix run "github:NixOS/nixpkgs?ref=pull/211867/head#scilab-bin"` if you are using flake.

Should I set `mainProgram` to `scilab`? I don't think `scilab-bin` is directly callable.

**Comment by wegank** [comment]
> I get this error:
> 
> ```
> SCI environment variable not defined.
> ```

So the `libtinfo.so.5` error is gone. Could you test `nix build "github:NixOS/nixpkgs?ref=pull/211867/head#scilab-bin"`, and then check which binaries under `result/bin` run?

**Comment by mskf1383** [comment]
> Could you test nix build "github:NixOS/nixpkgs?ref=pull/211867/head#scilab-bin", and then check which binaries under result/bin run?

Main file is `scilab`.

These files has shortcut in graphical environment programs menu:
`scilab`, `scinotes`, `xcos`, `scilab-cli` and `scilab-adv-cli`

these are only available from command line:
`modelicac`, `modelicat` and `XML2Modelica`

**Comment by mskf1383** [comment]
Thank you, it now run

But there is some problems:
- It doesn't use my system theme (that is not important).
- And graphs doesn't show. In prevouse version (and the binary provided in their website), I shoul'd run it with my Nvidia to work. But now it doesn't work anyway.

I think it has problem with using local/system/environment variables.

**Comment by wegank** [comment]
> I think it has problem with using local/system/environment variables.

I guess it is rather that the previous package does not expose `scilab-bin` and other binaries, which are called by `scilab` or other wrappers and shouldn't be run directly.

For the other issues, this could be related to the fact that `autoPatchelfHook` removes all references to FHS libraries. So fixing NixOS support may break support for other Linux...

**Comment by wegank** [comment]
I finally got an x86_64 machine to test, and I am now able to confirm the problem on NixOS, which is actually the same as in #51173. @mskf1383 Would you please test if [the workaround](https://github.com/NixOS/nixpkgs/issues/51173#issuecomment-723044947) works on your system?

**Comment by mskf1383** [comment]
It works with scilab in NixOS repository, but not with this pull request.

**Comment by wegank** [comment]
I've now conditioned `autoPatchelfHook` after the `isNixOS` flag, which now defaults to `true`. Would you please test again?

**Comment by mskf1383** [comment]
Error of libtinfo5 is back. I also found that this error is available in the compiled binary provided in Scilab website. so I do not think this is a packaging problem. It is a Scilab bug.

I tried to check this bug is also available in NixOS or it is only available in Debian, but in NixOS installed on a virtual machine, it completely does not run!
نماگرفت از 2023-02-15 17-15-08

Thank you for your efforts.

**Comment by wegank** [comment]
> Error of libtinfo5 is back. I also found that this error is available in the compiled binary provided in Scilab website. so I do not think this is a packaging problem. It is a Scilab bug.
> 
> I tried to check this bug is also available in NixOS or it is only available in Debian, but in NixOS installed on a virtual machine, it completely does not run! نماگرفت از 2023-02-15 17-15-08
> 
> Thank you for your efforts.

Indeed, you need to set `isNixOS` to true for it to run on NixOS.

**Comment by mskf1383** [comment]
> Indeed, you need to set `isNixOS` to true for it to run on NixOS.

I wasn't understand. This error is available in scilab-bin in NixOS repo too.

**Comment by wegank** [comment]
> > Indeed, you need to set `isNixOS` to true for it to run on NixOS.
> 
> I wasn't understand. This error is available in scilab-bin in NixOS repo too.

I mean, you won't get these errors under NixOS if you set `isNixOS` to true in addition to my PR.

**Comment by wegank** [comment]
Anyway, this PR fixes scilab on NixOS apart from the problems on `plot()`. If no one objects, I'll merge it very soon.

**Pull request merged**
