### PR TITLE
UNTESTED / possibly a bad idea: nixos/tinc: Don't generate an ed25519 key if an RSA key is already prese...

### PR DESCRIPTION
**Pull request by falsifian**
@wkennington, this is what I was suggesting in https://github.com/NixOS/nixpkgs/issues/6195. But I haven't been able to test it. If you prefer to keep the current behaviour, just go ahead and close this request.

### CODE REVIEW

**Comment by wkennington** [comment]
The problem is that with tinc_pre, it has ExperimentalProtocol = yes | no (yes). This requires ed25519 keys to be present for all of the hosts. I assume if there is no private key it must disable this behavior?

**Comment by falsifian** [comment]
Ah, that probably explains why tinc_pre wasn't working for me. I'm going to close this for now, as it sounds like it's a bit more complicated than this.

Still, the existing logic in ```tinc.nix``` is a bit strange: it looks like it always (in the tinc 1.1+ case) makes sure both an ed25519 key and an RSA key are present, even though it sounds like only the ed25519 key is used. Or maybe both are used, in which case the comments are confusing.

**Comment by wkennington** [comment]
Tinc only uses the ed25519 key with the experimental protocol enabled but
still requires the rsa key to exist for some reason.

**Comment by falsifian** [comment]
Ah, that explains it. Thanks for being patient with me :-)

**Pull request closed without merging**
