### PR TITLE
Codeowners: update teams and add entry for GNOME

### PR DESCRIPTION
**Pull request by piegamesde**
###### Motivation for this change

Alas, we need to manually keep our teams in sync with this file. See #124085. Also added an entry for GNOME and the extensions.

- @saschagrunert, @adisbladis, @vdemeester: Heads up, you just got added to the file.
- @jtojnar, @hedning: I added the GNOME team to `/pkgs/desktops/gnome` and myself for `/pkgs/desktops/gnome/extensions`. 
- @NixOS/darwin-maintainers: You are the only team left whose entries are broken. This affects `/pkgs/stdenv/darwin` and `/pkgs/os-specific/darwin`. I did not want to add over 30 people to the list, so please deal with this in a separate PR.

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by domenkozar** [comment]
> I did not want to add over 30 people to the list, so please deal with this in a separate PR.

Isn't it then just better to grant write access for the team?

**Review by vdemeester — APPROVED** [review]
LGTM 👍🏼

**Comment by piegamesde** [comment]
> Isn't it then just better to grant write access for the team?

Maybe? I don't know what the policies on this are. I know that teams with write access can only have members with write access, and that only the security team has write access at the moment.

**Comment by toonn** [comment]
I'm working on the Darwin stdenv but I don't have write-access so I can't be a codeowner. Maybe @thefloweringash, @copumpkin, @LnL7? I'm not sure anyone has time for the responsibility though.

**Comment by piegamesde** [comment]
Apparently @saschagrunert and @vdemeester don't have commit access at the moment. How should we deal with this?

**Comment by Zimmi48** [comment]
FWIW, our experience with the Coq project has been to define a `pushers` team (equivalent to the `committers` team here) which has as many subteams as there are components (and being a member of a subteam automatically grants you write access). For a screenshot illustrating this, see Figure 3.4 in Section 3.7 of my [PhD thesis](https://hal.inria.fr/tel-02451322/document). A benefit of this approach is that when one of the team members reviews a PR, the review request disappears for all the team members.

**Pull request merged**
