### PR TITLE
Kde 16.08.1

### PR DESCRIPTION
**Pull request by phunehehe**
###### Motivation for this change

Update KDE to 16.08.1

Somewhat personal use case: `konsole` has a [bug](https://bugs.kde.org/show_bug.cgi?id=366368) that has been fixed in the new version. Perhaps also backport to 16.09 if this is good?
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS) -- just `konsole`
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`) -- again just `konsole`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
cc @ttuegel

**Review by ttuegel — CHANGES_REQUESTED** [review]
This looks good, except the actual update commit should be titled `kde5.applications: 16.08.0 -> 16.08.1` to comply with our contributor guidelines. Thanks!

**Comment by phunehehe** [comment]
@ttuegel updated

**Review by ttuegel — APPROVED** [review]

**Comment by ttuegel** [comment]
Thanks!

**Comment by phunehehe** [comment]
\o/
Can this also go to 16.09? It's broken there too.

**Comment by ttuegel** [comment]
> Can this also go to 16.09? It's broken there too.

Done!

**Pull request merged**
