### PR TITLE
[needs help] mindustry-bin: init at 5.0 v99

### PR DESCRIPTION
**Pull request by wamserma**
Note: Game launches but sound does not work yet (some OpenAL issue).

###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/72001

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by wamserma** [comment]
The jar includes some libraries in binary form, so this requires an extra step to extract the libs from the jar, path them and repack the jar.
Building from source is complicated due to the use of the gradle warpper.

**Comment by deliciouslytyped** [comment]
Oh no, JAR packaging strikes again....
I played this on my phone from fdroid, it's certainly worth packaging.

I wonder how crazy it would be to just depend on steam-run...

**Comment by wamserma** [comment]
`steam-run` would certainly be a way to go as Mindustry is also distributed on Steam, but building from source would be better. 

I wasn't aware of https://github.com/NixOS/nixpkgs/issues/17342#issuecomment-506920779 and will give it a try.

**Comment by MicrosoftTakeover** [comment]
#72306

**Comment by wamserma** [comment]
Closed in favour of https://github.com/NixOS/nixpkgs/pull/72306.

**Pull request closed without merging**
