### PR TITLE
ghc: update 8.10.1 pre-release to rc1

### PR DESCRIPTION
**Pull request by ggreif**
https://mail.haskell.org/pipermail/ghc-devs/2020-January/018530.html

###### Motivation for this change

The version previously fetched was `8.10.0.20200108`. This MR updates to the _announced_ `rc1`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@ggreif Could you target the `haskell-updates` branch for this instead of `master`?

**Comment by ggreif** [comment]
Good point! Let me see...

**Comment by ggreif** [comment]
This is somehow messed up. Closing.

**Comment by ggreif** [comment]
> @ggreif Could you target the `haskell-updates` branch for this instead of `master`?

#78468

**Comment by peti** [comment]
Please dont just close the PR. This issue could have been fixed.

**Comment by ggreif** [comment]
Sorry for that, I had a slight confusion with the remotes on my side,
which made me panic a bit. Now I know how to fix such a situation for
sure. Keeping learning.

Thanks for the constructive feedback!

**Pull request closed without merging**
