### PR TITLE
searxng: move to pkgs/by-name, unstable-2023-07-19 -> unstable-2023-10-01

### PR DESCRIPTION
**Pull request by 999eagle**
## Description of changes

The most important change in this update is https://github.com/searxng/searxng/pull/2848 for adding the new `server.public_instance` setting for configuring the bot limiter.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Do we need to move it? I don't want to have to deal with that experimental feature.

**Comment by 999eagle** [comment]
We don't really need to move it right now but as `searxng` in its current state does not support automatic migration to the new by-name hierarchy and I'm updating it anyway, I think it's appropriate to migrate it manually.

**Comment by SuperSandro2000** [comment]
whatever, fine for me if you take care of it but if it doesn't work we just revert it.

**Comment by 999eagle** [comment]
I've updated this to unstable-2023-10-01 now to include a fix for the new limiter: https://github.com/searxng/searxng/commit/d56b31d67473e0970bc457469b0cbec2e35f8b10. I've also added myself as maintainer to take care of possible future issues with the by-name hierarchy.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
