### PR TITLE
dafny: 4.7.0 -> 4.8.0

### PR DESCRIPTION
**Pull request by whonore**
## Description of changes

4.8 changelog: https://github.com/dafny-lang/dafny/releases/tag/v4.8.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by layus** [comment]
The state of this package is getting worse. Now it does not compile to csharp anymore.
I do not think it is required, or due to this PR, but I wanted to leave a note here about that.


```
dafny build test.dfy 

Dafny program verifier finished with 4 verified, 0 errors
Failed to compile C# source code using 'dotnet build /home/layus/.cache/nixpkgs-review/pr-340877-3/test.csproj -o /home/layus/.cache/nixpkgs-review/pr-340877-3'. Command output was:
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

**Comment by layus** [comment]
Thanks !

**Comment by corngood** [comment]
> The state of this package is getting worse. Now it does not compile to csharp anymore.

Can we get a test for this?  This looks like something I might have broken with dotnet infrastructure changes.

**Comment by layus** [comment]
Yes, I could wrap something up.

But realistically knowing dafny this is more about having a csharp compiler in the PATH.

Le 25 novembre 2024 14:39:37 GMT+01:00, David McFarland ***@***.***> a écrit :

**Comment by corngood** [comment]
I'm just not familiar with this tool at all.  Even if you could just share the `test.dfy` you used, I could probably figure it out.

**Comment by layus** [comment]
@corngood Turns out I had tests lying around in a PR already: https://github.com/NixOS/nixpkgs/pull/300009

Dafny "works" because it is able to verify code, but it cannot be executed because it cannot find a dotnet framework and thus cannot compile csharp. See the commented-out "run" test in the above PR for an example that should work.

**Pull request merged**
