### PR TITLE
btop: enable amd gpu support

### PR DESCRIPTION
**Pull request by Flakebi**
## Description of changes

Equivalent of #283509 for AMD GPUs.
To try it out in a nixpkgs checkout: `nix-build --arg config '{ rocmSupport = true; }' -A btop`

cc @NixOS/rocm-maintainers

btop-amd-screenshot

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by lovesegfault — APPROVED** [review]

**Comment by Shawn8901** [comment]
Haven't tested it, but doesn't this already bring and GPU support? https://github.com/NixOS/nixpkgs/pull/296468

**Comment by Slime90** [comment]
I have tried to build and use this derivation on my 6550U APU and get the same issues as described in #297487.

**Comment by Slime90** [comment]
Sorry everyone, 

I had a typo (rcom instead of rocm) in my nixpkgs option setting, and did not realize that this is not checked against an options list, and silently fails. 

Now that I have the above PR building locally, it seems to error when running `patchelf` after the wrapping phase. If I comment out the `patchelf` step this actually builds and works correctly for me. Are both of these stages really needed?

**Comment by Shawn8901** [comment]
so both does not work either the one or the other otherwise it will try to patch the wrapper.

**Comment by mguentner** [comment]
@Slime90 so is the issue described in https://github.com/NixOS/nixpkgs/issues/297487 also resolved by correcting the typo?

**Comment by Tungsten842** [comment]
> so both does not work, either the one or the other otherwise it will try to patch the wrapper.

Is this needed considering that the version in nixpkgs already supports rocm?

**Comment by Slime90** [comment]
Confirmed after further testing that my typo is what led to neither version working for me.  After it was corrected this specific PR failed to build due to patchelf trying to patch the wrapped binary

**Comment by mguentner** [comment]
Thanks for clearing it up, @Slime90!
Given that `makeWrapper` vs `patchelf` was already discussed in https://github.com/NixOS/nixpkgs/pull/296468, this is a duplicate.

**Comment by Flakebi** [comment]
Yup, didn’t see another PR went already in.

**Pull request closed without merging**
