### PR TITLE
pythonPackages: add a bunch

### PR DESCRIPTION
**Pull request by oxij**
###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by oxij** [comment]
The first error seems to be a bug in travis build script.
The second is a test fail on OSX which I don't ever touch.

**Comment by FRidh** [comment]
Did you check whether tests were run? If you get something like 0 tests found it is not yet good.
Did you check with all interpreter versions?

**Comment by oxij** [comment]
Frederik Rietdijk <notifications@github.com> writes:

> Did you check whether tests were run?If you get something like 0 tests found it is not yet good.

Even if it has no tests in the source?

Fixed python3 tests for plyvel, others (and python2 plyvel) seem to have
no tests whatsoever.

> Did you check with all interpreter versions?

Only the default python2 and python3.

**Comment by FRidh** [comment]
@oxij if no tests are provided the tests shoudl be disabled. Furthermore, when tests are disabled, include a comment explaining why.

**Comment by oxij** [comment]
> @oxij if no tests are provided the tests shoudl be disabled. Furthermore, when tests are disabled, include a comment explaining why.

Done.

I suggest enforcing this property in the package builder somewhere: "code is law".

**Comment by FRidh** [comment]
Pytest 2.9 and up exit with code 1 when tests aren't found. Unfortunately the other test runners do not.

**Comment by oxij** [comment]
What's holding this up?

**Pull request merged**
