### PR TITLE
platformio: add git, cleanup derivation

### PR DESCRIPTION
**Pull request by lukeadams**
###### Motivation for this change
* Clean up platformio FHSUserEnv builder
* add Git input to platformio python module to allow pulling arduino libraries from git

###### Other notes
- may add a note to remind users to add themselves to `dialout` group to allow serial port access
- may be better to build a python.withPackages env

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lukeadams** [comment]
Use with Parallels: manual remount of shared folder is required.
1. Stop `prlfsmountd.service` (`systemctl stop prlfsmountd.service`)
2. `mount -t prl_fs ${share_name} ${desired/mnt/path}`
apparently prlfsmountd monitors fs mounts and remounts all shares if the mount options are modified
Optionally run `nixos-generate-config` to add fs mount to `/etc/nixos/hardware-config.nix`, and maybe disable prlfsmountd entirely.

**Comment by FRidh** [comment]
can you rebase

**Comment by lukeadams** [comment]
@FRidh 👍

**Comment by mogorman** [comment]
looks good to me

**Comment by FRidh** [comment]
Pushed 677aa175a79c9e7cd07a9444e0a3740c7c16d30b

**Pull request closed without merging**
