### PR TITLE
qt6.qtwebengine: mark as broken on darwin

### PR DESCRIPTION
**Pull request by wegank**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Strum355** [comment]
> Not compatible with macOS 11

`stdenv.hostPlatform.darwinMinVersion` returns 11 on (I believe) pretty much all current darwin versions, even on my existing 14.4 macbook, resulting in this package not building on any mac that Im aware of. Is this intentional? Doesnt seem to match what the comment states about it being specific to macOS 11

cc @reckenrode on how these variables are defined/what they mean

**Comment by K900** [comment]
Yes, that is intentional. We currently only have 10.x and 11.0 SDKs. @reckenrode is working on updating us to newer versions, which should unblock Qt again.

**Comment by reckenrode** [comment]
> > Not compatible with macOS 11
> 
> 
> 
> `stdenv.hostPlatform.darwinMinVersion` returns 11 on (I believe) pretty much all current darwin versions, even on my existing 14.4 macbook, resulting in this package not building on any mac that Im aware of. Is this intentional? Doesnt seem to match what the comment states about it being specific to macOS 11
> 
> 
> 
> cc @reckenrode on how these variables are defined/what they mean

`hostPlatform.darwinMinVersion` set the deployment target.

Did upstream drop support for macOS 11, or do they simply require a newer SDK (that is not yet available in nixpkgs)? It is possible to use or require a newer SDK and support older OS deployment using availability checks and other techniques.

The currently available SDKs in nixpkgs are 10.12 and 11.0. After the ld64 and Darwin cross stuff lands, I will be working on an SDK refactor that will make changing the SDK more robust and adding new ones easier. There is no ETA on that except for `by 24.11`.

**Comment by Strum355** [comment]
Im presuming the qtwebengine doc may be out of date then, it still states SDK 11 for 6.7.x 🤔 https://github.com/qt/qtwebengine/blob/v6.7.1/src/core/doc/src/qtwebengine-platform-notes.qdoc#L90
and the website version of it https://doc.qt.io/qt-6/qtwebengine-platform-notes.html#macos

**Comment by reckenrode** [comment]
> Im presuming the qtwebengine doc may be out of date then, it still states SDK 11 for 6.7.x 🤔

It’s possible to support deploying to an older release while requiring a newer SDK to build. The 12.3 SDK was added to nixpkgs recently, so I wonder if it’s possible to build QtWebEngine again. It’s also possible there was an incompatibility with the old tooling. cctools and ld64 were both updated recently to the same versions that are shipped in Xcode 15.

**Pull request merged**
