### PR TITLE
apache-airflow: fix dependencies

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
chardet update likely breaks things

**Comment by SuperSandro2000** [comment]
I have locally run ``git rebase --onto=upstream/staging --onto=upstream/master HEAD~2`` to prevent a ping to many people but somehow it still happened.

> chardet update likely breaks things

Which packages would be most likely affected? I could split out the version if required.

**Review by dotlambda — CHANGES_REQUESTED** [review]
Chardet has license `lgpl21Plus` and needs to be disabled for Python < 3.6.
We would need to add a version for Python 2.7:
```
36 packages removed:
buttersink (†0.6.9) carddav (†0.1-2014-02-26) cloudmonkey (†5.3.3) datadog-agent (†6.11.2) dd-agent (†5.11.2) euca2ools (†2.1.4) fMBT (†0.42) gmvault (†1.9.1) gnss-sdr (†0.0.13) gnuradio (†3.7.14.0) gnuradio-wrapped (†3.7.14.0) gnuradio-wrapped (†3.7.14.0) gr-ais (†2015-12-20) gr-ais (†2015-12-20) gr-gsm (†2016-08-25) gr-gsm (†2016-08-25) gr-limesdr (†2.0.0) gr-limesdr (†2.0.0) gr-nacl (†2017-04-10) gr-nacl (†2017-04-10) gr-osmosdr (†0.1.5) gr-osmosdr (†0.1.5) gr-rds (†1.1.0) gr-rds (†1.1.0) natron (†2.3.15) ocropus (†1.3.3) opae (†1.0.0) python2.7-bitbucket-cli (†0.5.1) python2.7-deluge (†1.3.15) python2.7-rainbowstream (†1.5.2) python2.7-yubikey-neo-manager (†1.4.0) python2nix (†20140927) qradiolink (†0.5.0) qweechat-unstable (†2016-07-29) tsung (†1.7.0) zabbix-cli (†2.2.1)
```

**Comment by SuperSandro2000** [comment]
@dotlambda Thanks! Applied all your suggestions.

After #115375 I want to check how big the breakage will be for the chardet update by building some packages eg home-assistant.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by dotlambda** [comment]
@SuperSandro2000 Why was this closed?

**Comment by SuperSandro2000** [comment]
Because I didn't feel like fixing apache-airflow which I am not using and regularly breaks.

**Pull request closed without merging**
