### PR TITLE
Cassandra

### PR DESCRIPTION
**Pull request by cransom**
###### Motivation for this change

I was glad to see Cassandra already in NixOS, however when I went to spin them up, I found a missing dependency on the packages, no module, and no tests. I updated packages to fix a missing glibc depend/clean up the code between versions, add a nixos module to help with configuration (thanks for the help, @thedebugger ), and added some tests to do some typical cluster operations.
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by NeQuissimus** [comment]
LGTM

**Comment by FRidh** [comment]
so somewhere this broke evaluation

**Comment by FRidh** [comment]
Manual seems to build locally without problems.

**Comment by domenkozar** [comment]
Fixed in 5ccfe7e8f281dd93b0e34b53a463149e0859ff17 -  manual shouldn't depend on any package.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/commit/52f21069d0495b4ea216909f9624d12cffe55fdf

**Pull request merged**
