### PR TITLE
kops: 1.19.2 -> 1.20.1

### PR DESCRIPTION
**Pull request by yurrriq**
###### Motivation for this change

Add 1.20.x version, and update `kops` to it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yurrriq** [comment]
fwiw we've been using a similar expression at work for about a week

**Comment by zimbatm** [comment]
Do you mind dropping a few older versions? We should keep at most 3 of every tools in nixpkgs. Otherwise LGTM

**Comment by yurrriq** [comment]
Good call, @zimbatm. I've dropped 1.16 and 1.17.

**Comment by zimbatm** [comment]
thanks. Do you mind re-checking the hashes? It looks like there is a mismatch on 1.20.1

**Comment by yurrriq** [comment]
> thanks. Do you mind re-checking the hashes? It looks like there is a mismatch on 1.20.1

Done. Thanks. I'm not sure how that happened...

**Comment by zimbatm** [comment]
Result of `nixpkgs-review pr 123751` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kops (kops_1_20)</li>
  </ul>
</details>

**Pull request merged**
