### PR TITLE
pnpm: 9.12.3 -> 9.14.2

### PR DESCRIPTION
**Pull request by gepbird**
Releases:
- https://github.com/pnpm/pnpm/releases/tag/v9.13.0
- https://github.com/pnpm/pnpm/releases/tag/v9.13.1
- https://github.com/pnpm/pnpm/releases/tag/v9.13.2
- https://github.com/pnpm/pnpm/releases/tag/v9.14.1
- https://github.com/pnpm/pnpm/releases/tag/v9.14.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355664`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 54 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wealthfolio</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

`gitbutler` fails on master too.

I'm not sure why ofborg-eval [falied](https://gist.github.com/GrahamcOfBorg/3923439680a74d759ad5a5934e4bb469), maybe just needs a rebase?

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355664`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 54 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wealthfolio</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
  </ul>
</details>
<details>
  <summary>:x: 6 packages failed to build:</summary>
  <ul>
    <li>en-croissant</li>
    <li>gitbutler</li>
    <li>pot</li>
    <li>surrealist</li>
    <li>wealthfolio</li>
    <li>wrangler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 44 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>webcord-vencord</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 9 packages failed to build:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>cdxgen</li>
    <li>gitbutler</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 23 packages built:</summary>
  <ul>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>en-croissant</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>cdxgen</li>
    <li>gitbutler</li>
    <li>n8n</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 29 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>en-croissant</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
For some reason Tauri packages are failing with nixpkgs-review, but not when built individually. We can observe the same behavior in #346277

**Comment by Scrumplex** [comment]
https://github.com/pnpm/pnpm/releases/tag/v9.13.1

**Comment by Scrumplex** [comment]
> For some reason Tauri packages are failing with nixpkgs-review, but not when built individually. We can observe the same behavior in #346277

It seems like this is some problem when running cargo-tauri.hook in an emulated environment.

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355664`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 54 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wealthfolio</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355664`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 59 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>deltachat-desktop</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>python311Packages.django-filingcabinet</li>
    <li>python311Packages.django-filingcabinet.dist</li>
    <li>python312Packages.django-filingcabinet</li>
    <li>python312Packages.django-filingcabinet.dist</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wealthfolio</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zenn-cli</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]

**Comment by MisileLab** [comment]
https://github.com/pnpm/pnpm/releases/tag/v9.14.2

**Pull request merged**
