### PR TITLE
pypy: 4.0.1 -> 5.1.1

### PR DESCRIPTION
**Pull request by bendlas**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The update commit also disables a test, for which the fix is already in upstream, after I pinged #pypy on IRC.
The revised - test commit enables a couple of non-network related tests, that I have observed passing, but that has to be verified on hydra ...

cc @domenkozar

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks! Testing locally now.

**Comment by FRidh** [comment]
I got one failure
```
======================================================================
ERROR: testStored (test.test_zipfile64.TestsWithSourceFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_zipfile64.py", line 83, in testStored
    self.zipTest(f, zipfile.ZIP_STORED)
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_zipfile64.py", line 56, in zipTest
    zipfp.writestr("testfn%d" % num, self.data)
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/zipfile.py", line 1248, in writestr
    self.fp.write(bytes)
IOError: [Errno 28] No space left on device: '<fdopen>'

----------------------------------------------------------------------
Ran 4 tests in 186.267s

FAILED (errors=1)
Traceback (most recent call last):
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/pypy/tool/pytest/run-script/regrverbose.py", line 14, in <module>
    indirect_test()
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_zipfile64.py", line 156, in test_main
    run_unittest(TestsWithSourceFile, OtherTests)
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_support.py", line 1450, in run_unittest
    _run_suite(suite)
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_support.py", line 1404, in _run_suite
    raise TestFailed(err)
TestFailed: Traceback (most recent call last):
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_zipfile64.py", line 83, in testStored
    self.zipTest(f, zipfile.ZIP_STORED)
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/test/test_zipfile64.py", line 56, in zipTest
    zipfp.writestr("testfn%d" % num, self.data)
  File "/tmp/nix-build-pypy-5.1.1.drv-0/pypy-pypy-b0a649e90b66/lib-python/2.7/zipfile.py", line 1248, in writestr
    self.fp.write(bytes)
IOError: [Errno 28] No space left on device: '<fdopen>'
```

**Comment by bendlas** [comment]
did you run out of space on `/tmp`?

**Comment by FRidh** [comment]
@bendlas that indeed could have happened. My tmp is 6 GB and only 10% was in use. I don't know what size file they test with. If it is large it might be good to disable that test.

**Pull request merged**
