### PR TITLE
mypy-boto3-*: init at 1.26.0.post1

### PR DESCRIPTION
**Pull request by l0b0**
###### Description of changes

Motivation: #205083. Includes the following new packages:

<details>

- mypy-boto3-batch
- mypy-boto3-dynamodb
- mypy-boto3-events
- mypy-boto3-lambda
- mypy-boto3-s3control
- mypy-boto3-sns
- mypy-boto3-sqs
- mypy-boto3-ssm
- mypy-boto3-stepfunctions
- mypy-boto3-sts

</details>

@fabaff Are you OK to be listed as the maintainer of these, or should I instead add myself?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux (`nix-build nixos --attr pkgs.python39Packages.mypy-boto3-accessanalyzer --attr pkgs.python39Packages.mypy-boto3-account …`)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
We need a very good reason to add those 300+ packages because it is nice to have it does not cut it here.

**Comment by l0b0** [comment]
> We need a very good reason to add those 300+ packages because it is nice to have it does not cut it here.

OK, I've cut it down to just [the ones I'm using](https://github.com/linz/geostore/blob/a88250565928c7b61cc65065b6fd44f6e0aae9f8/pyproject.toml#L107), and which would help with replacing poetry2nix with just Nix in that project.

> Also generating nix code with bash is not doing nix justice. We can generate those packages in a subset from json file in a tiny fraction of the code proposed here.

I'm sorry I'm such a bad developer, I just wanted to get the job done. I've removed the offending script.

**Comment by SuperSandro2000** [comment]
If you need packages for your projects the best solution would be to maintain in your repository. Then you have full control over them and we don't mass bump them and break your things.

Also I cannot recommend to replace pip, poetry and npm because nix uses them behind the back and for local development using them is way faster especially if you only want to try things.

**Comment by l0b0** [comment]
Thanks for the advice @SuperSandro2000! I'll take it into consideration, but managing multiple package managers in parallel is a huge pain compared to just relying on what's in nixpkgs.

**Pull request closed without merging**
