### PR TITLE
x11 service: bspwm limit sxhkd freqency

### PR DESCRIPTION
**Pull request by Pleune**
allow sxhkd to behave well in more situations (w/ bspwm as WindowManager)

add '-f 100' as an argument to sxhkd to keep it from flooding bspwm

add SXHKD_SHELL=/bin/sh to help default to a faster shell than what may
be set in $SHELL (example: with zsh)

Things done:
- [x] Tested via nix.useChroot. 
- [x] Built on platform(s): NixOS x86_64
- [x] Tested compilation of all pkgs that depend on this change.
- [x] Tested execution of binary products.
- [x] Fits CONTRIBUTING.md.

### CODE REVIEW

**Comment by fpletz** [comment]
cc @meisternu @epitrochoid

**Comment by joachifm** [comment]
This looks good to me. I have never experienced the flooding issue you describe, however, could you elaborate?

**Comment by Pleune** [comment]
I have experienced this both on Arch Linux and NixOS.
Currently, I am using lightdm, and my default shell is zsh

The main problem seems to be that in certain scenarios, buffers between sxhkd and bspwm fill, thus creating a lag. 

https://github.com/baskerville/bspwm/issues/197 explains the solution fairly well, but with fish instead of, in my case, zsh. 

> bspc pointer with button 1-3 extremely slow when using fish

> That's because sxhkd will re-execute your shell (which will run the specified command command) for every input event and fish probably has a long startup time. You can start sxhkd with the -f FREQUENCY option to reduce motion event frequency but you should really just set a faster shell (I'd just use sh). You can set sxhkd's shell independently using the SXHKD_SHELL environment variable.

Please note, in my experience, no matter how how I set SXHKD_SHELL (sxhkd falls back to SHELL if SXHKD_SHELL is empty), running sxhkd from withing X11 never results in an issue.

If you're looking to recreate the issue, run sxhkd with `SXHKD_SHELL=/run/current-system/sw/bin/zsh sxhkd` in your .xprofile. This seems to be a "worst case."

Why the solution works:
- the -f argument on sxhkd limits how quickly it will run commands, allowing bspwm to react to any commands before more get queued up. _On my moderately powerful desktop, this made the huge difference._
- setting SXHKD_SHELL to /bin/sh creates a much more consistent and reliable environment for sxhkd. _On my slow laptop, this made the huge difference, where zsh was used by default._

**Comment by joachifm** [comment]
@Pleune Thank you for taking the time to elaborate, makes sense.

**Pull request merged**
