### PR TITLE
dotnet-sdk: 6.0.410 -> 6.0.411, dotnet-sdk_7: 7.0.304 -> 7.0.305

### PR DESCRIPTION
**Pull request by mdarocha**
###### Description of changes

https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.19/6.0.19.md

https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.8/7.0.8.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by corngood** [comment]
What led you to update the space-station-14-launcher deps, and how did you do it?  I ask because I'm currently writing a helper to run all the `fetch-deps`.

**Review by corngood — APPROVED** [review]

**Comment by felschr** [comment]
Result of `nixpkgs-review pr 239426` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>67 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>audiobookshelf</li>
    <li>azure-functions-core-tools</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>commitizen</li>
    <li>commitizen.dist</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore</li>
    <li>dotnet-aspnetcore_7</li>
    <li>dotnet-runtime</li>
    <li>dotnet-runtime_7</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk_7</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>git-credential-manager</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>kavita</li>
    <li>lidarr</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>ps3-disc-dumper</li>
    <li>python310Packages.clr-loader</li>
    <li>python310Packages.clr-loader.dist</li>
    <li>python310Packages.pythonnet</li>
    <li>python310Packages.pythonnet.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>radarr</li>
    <li>readarr</li>
    <li>roslyn</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>space-station-14-launcher</li>
    <li>tone</li>
    <li>wasabibackend</li>
    <li>wasabiwallet</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Comment by felschr** [comment]
> What led you to update the space-station-14-launcher deps, and how did you do it? I ask because I'm currently writing a helper to run all the `fetch-deps`.

The build fails if the `deps.nix` isn't updated due to some .NET dependencies with versions that depend on the .NET SDK.
The issue is tracked here: https://github.com/NixOS/nixpkgs/issues/237779

**Review by felschr — APPROVED** [review]

**Review by raphaelr — APPROVED** [review]
LGTM

**Comment by corngood** [comment]
> Overall fetch-deps for a package should only be called when that specific package is updated and it's dependencies change, so I don't see much value in a script to globally run fetch-deps for all packages.

It's useful for testing changes to fetch-deps.  As far as I know there's nothing ensuring that fetch-deps can still generate working deps for all packages.  It's definitely broken things in the past.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 239426` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.writers</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>audiobookshelf</li>
    <li>azure-functions-core-tools</li>
    <li>boogie (dotnetPackages.Boogie)</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>commitizen</li>
    <li>commitizen.dist</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore (dotnet-aspnetcore_6 ,dotnetCorePackages.aspnetcore_6_0)</li>
    <li>dotnet-aspnetcore_7 (dotnetCorePackages.aspnetcore_7_0)</li>
    <li>dotnet-runtime (dotnet-runtime_6 ,dotnetCorePackages.runtime_6_0)</li>
    <li>dotnet-runtime_7 (dotnetCorePackages.runtime_7_0)</li>
    <li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0)</li>
    <li>dotnet-sdk_7 (dotnetCorePackages.sdk_7_0)</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>git-credential-manager</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>kavita</li>
    <li>lidarr</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>ps3-disc-dumper</li>
    <li>python310Packages.clr-loader</li>
    <li>python310Packages.clr-loader.dist</li>
    <li>python310Packages.pythonnet</li>
    <li>python310Packages.pythonnet.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>radarr</li>
    <li>readarr</li>
    <li>roslyn</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>space-station-14-launcher</li>
    <li>tests.dotnet.project-references</li>
    <li>tone</li>
    <li>wasabibackend</li>
    <li>wasabiwallet</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Pull request merged**
