### PR TITLE
php: 7.2.8 -> 7.2.10, 7.1.21 -> 7.1.22

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
This should *not* be backported due to flag changes due to upstream bugs.

Changelog 7.2.9: http://php.net/ChangeLog-7.php#7.2.9
Changelog 7.2.10: http://php.net/ChangeLog-7.php#7.2.10
Changelog 7.1.22: http://php.net/ChangeLog-7.php#7.1.22

If someone could trigger a borg build for darwin as well it would be great since 7.2.9 seemed to fail on darwin in the 7.2.9 PR that never got merged due to darwin failure #45159.

This fixes #45159.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @xeji @globin

### CODE REVIEW

**Comment by xeji** [comment]
@grahamcofborg build php

**Comment by xeji** [comment]
Unfortunately the same darwin error as in #45159

**Comment by xeji** [comment]
There's an upstream bug: https://bugs.php.net/bug.php?id=76826 . Apparently this is about the intl extension. Maybe we can disable it on Darwin until this bug is fixed?

**Comment by etu** [comment]
@xeji We could do that workaround for unstable, but I'm not comfortable with changing the flags for stable. But I'll update my this PR and not the other (#46697) , but both will be fixed whenever merged.

**Comment by etu** [comment]
@xeji I have pushed an update of my commit with a change of intl, please trigger the darwin build (I don't have any darwin systems to test on anyways).

But I don't think that we should backport this to stable until the upstream issue is fixed.

**Comment by xeji** [comment]
@GrahamcOfBorg build php php71

**Comment by xeji** [comment]
@etu let's not backport this to 18.09 for now but wait until upstream fixes the darwin bug. We can reconsider if they don't fix it soon.

**Comment by etu** [comment]
@xeji Yeah, I agree. I will keep track of the upstream issue and try to restore the defaults whever the next release happens :+1:

**Comment by xeji** [comment]
Thanks!

**Pull request merged**
