### PR TITLE
tensorflow-lite: add missing source file

### PR DESCRIPTION
**Pull request by cpcloud**
###### Motivation for this change

This PR adds a patch to include a source file that contains code
used in libcoral, but is for whatever reason not included in the tensorflow-lite `Makefile`.

This (a file being incorrectly included/not included) has historically happened a number of
times in the upstream repository.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you upstream this patch?

**Comment by cpcloud** [comment]
> Can you upstream this patch?

I can certainly try.

**Comment by cpcloud** [comment]
Let me see if it's already in master first.

**Comment by cpcloud** [comment]
Alright, I attempted to upstream it: https://github.com/tensorflow/tensorflow/pull/50240

**Comment by cpcloud** [comment]
@SuperSandro2000 Can we merge this in the meantime? I will shepherd the upstream patch to make sure it gets in.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Can we merge this in the meantime? I will shepherd the upstream patch to make sure it gets in.

Sure but can we fetch the patch via fetchpatch? We don't actually need the file in the nixpkgs repo.

**Comment by cpcloud** [comment]
@SuperSandro2000 This is ready to go, as the upstream patch has been merged.

**Pull request merged**
