### PR TITLE
owncloud-client: 2.4.3 -> 2.5.3.11470

### PR DESCRIPTION
**Pull request by das-g**
###### Motivation for this change

latest stable according to https://owncloud.com/download/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

<del>Unfortunately, source download URLs without build numbers or whatever these are don't seem to be available for versions after 2.4.3, so I guess we won't have automatic updates by @r-ryantm for this package anymore?</del> (see comments below)

### CODE REVIEW

**Comment by ryantm** [comment]
If you add the build into the version as one string, it will keep working.

**Comment by das-g** [comment]
> If you add the build into the version as one string, it will keep working.

Is it acceptable to become part of the derivation name (currently defined as `"owncloud-client-${version}"`), too, or would it have to be stripped out of that?

**Comment by ryantm** [comment]
I think that's fine. Arch, Gento, and Debian consider it to be part of the version https://repology.org/metapackage/owncloud-client/versions

**Comment by das-g** [comment]
OK, I've adapted the PR accordingly.

**Comment by ryantm** [comment]
Looks good! @GrahamcOfBorg build owncloud-client

**Comment by ryantm** [comment]
@GrahamcOfBorg build owncloud-client

**Comment by ryantm** [comment]
Darwin was already failing before this change.

**Comment by das-g** [comment]
Should this be backported to NixOS 18.09?

**Comment by ryantm** [comment]
I think we can skip it. It will be in 19.03. If someone really wants it in 18.09, they can ask for it and say why they need it.

**Pull request merged**
