### PR TITLE
drawio: update license

### PR DESCRIPTION
**Pull request by alyssais**
Link: https://github.com/jgraph/drawio/discussions/4623

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]

**Comment by danjl1100** [comment]
I am curious on the upstream details of the license change to `unfree`, but the discussion link in the OP has since been broken.
Do you recall the gist of the linked discussion? (what changed in `jgraph/drawio-desktop` licensing)

I was trying to dig up any changes in the repo linked by this package, but just seeing the Apache License 2.0
https://github.com/jgraph/drawio-desktop/blob/v24.7.17/LICENSE
^ it's saying the license was last modified 7 years ago.

Is there some distinction I'm missing between the license of the source, and building/deploying as an application on nixos/nixpkgs?

**Comment by mweinelt** [comment]
https://web.archive.org/web/20241003003512/https://github.com/jgraph/drawio/discussions/4623

**Comment by DPDmancul** [comment]
1. That discussion was from [drawio](https://github.com/jgraph/drawio), but this is [drawio-desktop](https://github.com/jgraph/drawio-desktop), whose license is Apache 2 since 8 years
2. Last December also the license of drawio returned Apache 2 ([commit](https://github.com/jgraph/drawio/commit/5b2e73471e4fea83d681f0cec5d1aaf7c3884996))

In any case point 1 should be enough to say this package is Apache 2 licensed

**Comment by alyssais** [comment]
But great, if they've undone the license change we can update our metadata.

**Comment by alyssais** [comment]
Wait, no, because still:

> The minified code authored by us in this repo is licensed under an Apache v2 license, but the sources to build those files are not in this repo. This is not an open source project.

We can't consider that to be free.

**Comment by DPDmancul** [comment]
> drawio is part of drawio-desktop, and not packaged separately.

As I understand, but maybe I'm wrong, drawio is the website (webapp), while drawio-desktop is the elctron app (the one packaged).

> The minified code authored by us in this repo is licensed under an Apache v2 license, but the sources to build those files are not in this repo. This is not an open source project.

This refers to drawio, not drawio-desktop

**Pull request merged**
