### PR TITLE
pythonPackages.accupy: init at 0.1.4

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Heard a great talk at pycon about accurate floating point math wanted to play with package.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
nix-review passes

Result of `nix-review pr 61753` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>6 package were build:</summary>

  - python27Packages.pipdate
  - python27Packages.pyfma
  - python37Packages.accupy
  - python37Packages.perfplot
  - python37Packages.pipdate
  - python37Packages.pyfma
</details>

**Comment by costrouc** [comment]
`HOME` is required in some of the build steps (not only in tests)

**Comment by marsam** [comment]
@GrahamcOfBorg build python3Packages.accupy

**Comment by marsam** [comment]
Tested locally on NixOS and darwin
Thanks!

**Pull request merged**
