### PR TITLE
texlive: fix licensing information for doc-only-packages

### PR DESCRIPTION
**Pull request by apfelkuchen6**
###### Description of changes

Some packages that only consist of documentation have had invalid license information which resulted in evaluation failures when documentation was allowed in a custom `pkgFilter`.

 - [lshort-german](https://github.com/dante-ev/l2kurz) is licensed under the OPUBL, which this adds to licenses.nix
 - [npp-for-context](https://github.com/luigiScarso/context-npp) is licensed under the GPL3 (only?). This overrides the incorrect tlpdb metadata which says "noinfo".

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by xworld21 — APPROVED** [review]
npp-for-context is technically not GPL3 (the license was added one week *after* uploading to CTAN) but the intent seems clear, and the package will disappear anyway - go for it!

(PS: @apfelkuchen6 you might want to report the license mismatches to CTAN, I am sure they will appreciate it.)

**Review by wentasah — APPROVED** [review]
This fixes my problem. Thank you!

**Comment by drupol** [comment]
This PR fix https://github.com/NixOS/nixpkgs/pull/238456#issuecomment-1605282479

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Sorry for the squashed merge, I shouldn't have squashed it, I saw it a bit too late.

**Pull request merged**
