### PR TITLE
bazel: 5.2.0 -> 5.3.2

### PR DESCRIPTION
**Pull request by dmivankov**
###### Description of changes

https://blog.bazel.build/2022/08/23/bazel-5.3.html

to supersede https://github.com/NixOS/nixpkgs/pull/187943 (5.3.0) and https://github.com/NixOS/nixpkgs/pull/192089 (5.3.1)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
This PR broke the build of jax, jaxlib (https://github.com/NixOS/nixpkgs/issues/199430), augmax and a bunch of others, likely including tensorflow. @dmivankov could you please revert this PR or follow-up with fixes for the now-broken packages?

**Comment by samuela** [comment]
Thanks so much @uri-canva, I really appreciate it!

**Comment by dmivankov** [comment]
So then all `fetchAttrs` in `buildBazelPackage` using `bazel_5` should've been updated?
Also do they need to first be replaced with `lib.fakeHash` to force rebuilds? I remember testing `tensorflow` build on several platforms (fails on darwin due to other issues though).
And should `nixpkgs-review` be reporting those packages? Here again I tried it before and `jaxlib` wasn't listed

**Comment by samuela** [comment]
Yeah nixpkgs-review should absolutely catch those. If not that's a bug in nixpkgs-review

**Pull request merged**
