### PR TITLE
llvmPackages_{12,13,14,15,16,17,18,git}: Simplify argument passthrough

### PR DESCRIPTION
**Pull request by pwaller**
## Description of changes

This patch is not intended to introduce any functional change. drvPaths
should remain unchanged; if they do change, it's a bug (note: this revealed
a bug in the derivation's source paths for LLVM 13 which I've preserved
to avoid a rebuild).

Prior to this patch, a set of packages gets passed through from the
llvmPackages top level function to the individual packages via
callPackages, which is a newScope constructed with some specific
arguments.

As it stands this makes it harder to override dependencies of LLVM; for
example take ncurses. If you want to override it, it is an argument to
libllvm, however, if you override libllvm you then have to write a lot
of code to have correctly overridden clang.

Instead, I propose to make sure that all the dependencies of all
llvmPackages are listed as an inputs to the top level llvmPackages,
and then the resulting newScope will contain all of them. This in
turn will make `llvmPackages.override` work as expected for any
input to each of the llvm packages.

We'll achieve this by simplifying the code a bit and ensuring that all
arguments to llvmPackage get forwarded to all packages (via `{}@args`).

This represents a chance to simplify things a bit so I propose doing it
in two steps:

1. This patch: Simplify argument pass through.
2. (Later): Ensure all arguments to each llvm package are listed in the
   top level `llvm/X/default.nix`.

Once 2 lands, this means that `(llvmPackages.override { ncurses =
myncurses; }).clang` would consist of a clang whose libllvm had the
ncurses overridden. This is not the case prior to this patch.

~For v1 draft of this patch I have only fixed llvmPackages 18 to keep the
first pass review simple. If others agree this is a good way forward, I
will fix up all the other llvmPackages revision.~

(No longer draft after getting some preliminary private approval from a maintainer)

Signed-off-by: Peter Waller <p@pwaller.net>

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pwaller** [comment]
This refactor found a bug in LLVM 13, that monorepoSrc wasn't being consistently passed through. (Search for the term 'bug' in the patch). I preserved the bug during this refactor since we're in/approaching a stablisation phase I don't want to cause any rebuilds.

In order to test this I generated the complete set of drvPaths for all attributes of `llvmPackages_*` which have a `drvPath`. I diff'd the output before and after and confirmed they are the unchanged.

```
 genDrvPaths = nixpkgs: let
    allLLVMPackagesNames = lib.filter (lib.hasPrefix "llvmPackages") (builtins.attrNames nixpkgs);
    allLLVMPackages' = lib.genAttrs allLLVMPackagesNames (e:
      (builtins.tryEval (builtins.attrNames (nixpkgs.${e})))
    );
    mkAttrs = pkgSet: pkg:
      builtins.tryEval (nixpkgs.${pkgSet}.${pkg}.drvPath or null);
    genSet = k: v: lib.filterAttrs (k: v: v != null)
      (mapValue (removeFailed (lib.genAttrs v.value (mkAttrs k))));
    filterSet = k: v:  v.success != false;
    mapValue = lib.mapAttrs (k: v: v.value);
    removeFailed = attrs: lib.filterAttrs filterSet attrs;
    allLLVMPackages = lib.mapAttrs genSet (removeFailed allLLVMPackages');
  in allLLVMPackages;
```

**Review by RossComputerGuy — APPROVED** [review]

**Comment by pwaller** [comment]
Thanks for the approval @RossComputerGuy. I don't have merge permissions, can someone please merge for me?

**Comment by pwaller** [comment]
Rebased. I don't have merge permissions, please can someone merge?

**Review by RossComputerGuy — APPROVED** [review]

**Pull request merged**
