### PR TITLE
luaPackages.llscheck: init at 0.5.0-1

### PR DESCRIPTION
**Pull request by mrcjkb**
## Description of changes

This package provides a wrapper around lua-language-server to use it for static type checking, with
human-readable and CI friendly output.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mrcjkb** [comment]
Result of `nixpkgs-review pr 330645` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>lua52Packages.llscheck</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>nixpkgs-manual</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
The `vimPluginsUpdater` failure on darwin is quite weird:
```
sourcing setup hook '/nix/store/afp5p3i50sfvx70nc4v7zmy76xhjp5c4-ruby-3.1.6/nix-support/setup-hook'
sourcing setup hook '/nix/store/5a3qq4isbj5wl1wvzf302z2hjyb7rbdy-sdkroot-10.12.4/nix-support/setup-hook'
sourcing setup hook '/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh'
sourcing setup hook '/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh'
sourcing setup hook '/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh'
sourcing setup hook '/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh'
sourcing setup hook '/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh'
sourcing setup hook '/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh'
sourcing setup hook '/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh'
sourcing setup hook '/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh'
sourcing setup hook '/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh'
sourcing setup hook '/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh'
sourcing setup hook '/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh'
sourcing setup hook '/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh'
sourcing setup hook '/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh'
calling 'envHostTargetHook' function hook 'addGemPath' /nix/store/ag3zgvy4r4yq98ra41i4qy4nglihg52h-apple-framework-CoreFoundation
calling 'envHostTargetHook' function hook 'addRubyLibPath' /nix/store/ag3zgvy4r4yq98ra41i4qy4nglihg52h-apple-framework-CoreFoundation
calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/ag3zgvy4r4yq98ra41i4qy4nglihg52h-apple-framework-CoreFoundation
patching script interpreter paths in /nix/store/db9i1s6yhb24kg4s8lwmg3f0cp3bgqrx-gen-bin-stubs
/nix/store/db9i1s6yhb24kg4s8lwmg3f0cp3bgqrx-gen-bin-stubs: interpreter directive changed from "#!/usr/bin/env ruby" to "/nix/store/afp5p3i50sfvx70nc4v7zmy76xhjp5c4-ruby-3.1.6/bin/ru>
sed: couldn't open temporary file /nix/store/sedVn4wbd: Operation not permitted
```

Also, `nix build github:mrcjkb/nixpkgs/llscheck#vimPluginsUpdater --system aarch64-darwin` succeeds so I don't know what is happening there.

**Comment by teto** [comment]
> The `vimPluginsUpdater` failure on darwin is quite weird:
> 
> ```
> sourcing setup hook '/nix/store/afp5p3i50sfvx70nc4v7zmy76xhjp5c4-ruby-3.1.6/nix-support/setup-hook'
> sourcing setup hook '/nix/store/5a3qq4isbj5wl1wvzf302z2hjyb7rbdy-sdkroot-10.12.4/nix-support/setup-hook'
> sourcing setup hook '/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh'
> sourcing setup hook '/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh'
> sourcing setup hook '/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh'
> sourcing setup hook '/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh'
> sourcing setup hook '/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh'
> sourcing setup hook '/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh'
> sourcing setup hook '/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh'
> sourcing setup hook '/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh'
> sourcing setup hook '/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh'
> sourcing setup hook '/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh'
> sourcing setup hook '/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh'
> sourcing setup hook '/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh'
> sourcing setup hook '/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh'
> calling 'envHostTargetHook' function hook 'addGemPath' /nix/store/ag3zgvy4r4yq98ra41i4qy4nglihg52h-apple-framework-CoreFoundation
> calling 'envHostTargetHook' function hook 'addRubyLibPath' /nix/store/ag3zgvy4r4yq98ra41i4qy4nglihg52h-apple-framework-CoreFoundation
> calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/ag3zgvy4r4yq98ra41i4qy4nglihg52h-apple-framework-CoreFoundation
> patching script interpreter paths in /nix/store/db9i1s6yhb24kg4s8lwmg3f0cp3bgqrx-gen-bin-stubs
> /nix/store/db9i1s6yhb24kg4s8lwmg3f0cp3bgqrx-gen-bin-stubs: interpreter directive changed from "#!/usr/bin/env ruby" to "/nix/store/afp5p3i50sfvx70nc4v7zmy76xhjp5c4-ruby-3.1.6/bin/ru>
> sed: couldn't open temporary file /nix/store/sedVn4wbd: Operation not permitted
> ```
> 
> Also, `nix build github:mrcjkb/nixpkgs/llscheck#vimPluginsUpdater --system aarch64-darwin` succeeds so I don't know what is happening there.

@GaetanLepage How come this involves the vimPluginsUpdater ? no vim files were touched .

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>nixpkgs-manual</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 330645` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>lua51Packages.llscheck</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>lua53Packages.llscheck</li>
    <li>lua54Packages.llscheck</li>
    <li>luajitPackages.llscheck</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> @GaetanLepage How come this involves the vimPluginsUpdater ? no vim files were touched .

I don't really know why, but it came as an upstream dependency of the review shell.
Anyway, it builds just fine now.

**Pull request merged**
