### PR TITLE
home-assistant: 2021.2.0 -> 2021.2.1 

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.2.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112038` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python37Packages.pyicloud</li>
    <li>python38Packages.awesomeversion</li>
    <li>python38Packages.pyhaversion</li>
    <li>python38Packages.pyicloud</li>
    <li>python39Packages.awesomeversion</li>
    <li>python39Packages.pyhaversion</li>
  </ul>
</details>

**Comment by fabaff** [comment]
I'm getting:

```bash
[...]
      warnings.warn(
  
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  ERROR tests/components/ssdp/test_init.py::test_scan_match_st[pyloop] - Runtim...
  ====== 2978 passed, 1 skipped, 11 warnings, 1 error in 129.76s (0:02:09) =======
cannot build derivation '/nix/store/c6l1dl6ac0w74pax975vflqga6795wlv-env.drv': 1 dependencies couldn't be built
[...]
```

**Comment by mweinelt** [comment]
> I'm getting:
> 
> ```shell
> [...]
>       warnings.warn(
>   
>   -- Docs: https://docs.pytest.org/en/stable/warnings.html
>   =========================== short test summary info ============================
>   ERROR tests/components/ssdp/test_init.py::test_scan_match_st[pyloop] - Runtim...
>   ====== 2978 passed, 1 skipped, 11 warnings, 1 error in 129.76s (0:02:09) =======
> cannot build derivation '/nix/store/c6l1dl6ac0w74pax975vflqga6795wlv-env.drv': 1 dependencies couldn't be built
> [...]
> ```

I disabled that test 8 minutes ago. It is racy. Do you have an idea why this happens for us, but not for the upstream project? My current assumption is higher concurrency.

**Comment by mweinelt** [comment]
It looks like `--dist loadfile` improves things considerably.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112038` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>home-assistant: log was empty</li>
  </ul>
</details>
<details>
<summary>
6 packages built:
</summary>
<ul>
<li>python37Packages.pyicloud</li>
<li>python38Packages.awesomeversion</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyicloud</li>
<li>python39Packages.awesomeversion</li>
<li>python39Packages.pyhaversion</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.pyicloud:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.pyicloud:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by mweinelt** [comment]
Fixed the tests in pyicloud.

**Comment by mweinelt** [comment]
@fabaff Please give this another try.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112038` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages built:
</summary>
<ul>
<li>home-assistant</li>
<li>python37Packages.pyicloud</li>
<li>python38Packages.awesomeversion</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyicloud</li>
<li>python39Packages.awesomeversion</li>
<li>python39Packages.pyhaversion</li>
</ul>
</details>

**Comment by fabaff** [comment]
> Do you have an idea why this happens for us, but not for the upstream project?

Sorry, I can't help here.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112038` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python37Packages.pyicloud</li>
    <li>python38Packages.awesomeversion</li>
    <li>python38Packages.pyhaversion</li>
    <li>python38Packages.pyicloud</li>
    <li>python39Packages.awesomeversion</li>
    <li>python39Packages.pyhaversion</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
> Result of `nixpkgs-review pr 112038` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> 6 packages built:
> 
> I guess that's an issue at my end as @SuperSandro2000's report show no failure.
> 
> ```shell
>   ERROR tests/components/sun/test_init.py::test_setting_rising[pyloop] - Runtim...
> ```

How many test jobs does it start for you?

**Comment by SuperSandro2000** [comment]
> How many test jobs does it start for you?

If I read it correctly it starts 4 and I have cores set to 4 in nix.conf.

```
============================= test session starts ==============================                                                                                                            platform linux -- Python 3.8.7, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/source, configfile: pyproject.toml
plugins: aiohttp-0.3.0, xdist-2.1.0, forked-1.3.0, requests-mock-1.8.0
gw0 [3033] / gw1 [3033] / gw2 [3033] / gw3 [3033]
........................................................................ [  2%]
```

**Pull request merged**
