### PR TITLE
[WIP] libreoffice,libreoffice-fresh: fix build on Darwin

### PR DESCRIPTION
**Pull request by alyssais**
Months of work later, there are lots of nice fixes here that are useful not just for LibreOffice, but for Darwin builds in general.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alyssais** [comment]
The very large number of additions is due to 15815aedb00873aa593f887b8f555a810ca3b1de.

**Review by grahamc — DISMISSED** [review]
Requesting changes to ensure my note doesn't get lost. I'm looking in to the S3 bucket we can put unstable sources in to.

**Comment by alyssais** [comment]
I'm going to break out some smaller PRs.

**Comment by alyssais** [comment]
I'm going to break out some smaller PRs.

**Comment by 7c6f434c** [comment]
In general seems reasonable on first reading

**Comment by alyssais** [comment]
Looks like the net_snmp upgrade already has a PR: https://github.com/NixOS/nixpkgs/pull/51683

**Review by 7c6f434c — APPROVED** [review]

**Comment by alyssais** [comment]
Just need either #51683 or #54616 to be merged, and then I think this is ready.

**Comment by 7c6f434c** [comment]
@alyssais Indeed one of them was merged

**Comment by alyssais** [comment]
So I saw! But unfortunately this doesn't build on latest staging, so now I need to fix that up.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by alyssais** [comment]
> Are there any updates on this pull request, please?

I'm afraid I'm no longer using Darwin regularly, so won't be able to
make further progress on this PR.

If somebody else wants to pick it up, I'm happy to try to answer questions.

**Pull request closed without merging**
