### PR TITLE
zola: 0.18 -> 0.19.1

### PR DESCRIPTION
**Pull request by SIGSTACKFAULT**
## Description of changes

My first nixpkgs contribution so please be gentle. Skipping 0.19 because it had a bug in `zola watch`.
Requires Rust 1.79 #320250.

Changelog: [here](https://github.com/getzola/zola/blob/master/CHANGELOG.md#0191-2024-06-24)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
> Requires rust 1.79 which hasn't shipped in nixpkgs yet so used rust-overlay.

So let's wait an update on Rust instead.
We do not bring external dependencies this way.

**Comment by SIGSTACKFAULT** [comment]
> We do not bring external dependencies this way.

the matrix told me to do it

**Comment by AndersonTorres** [comment]
Show them the log  :)

https://github.com/NixOS/nixpkgs/actions/runs/9830902488/job/27137607321?pr=325370

> 
> Run if result/bin/nixpkgs-check-by-name --base "$base" .; then
> pkgs/by-name/zo/zola: File package.nix at line 1 contains the nix search path expression "<nixpkgs>" which may point outside the directory of that package.
> This PR introduces the problems listed above. Please fix them before merging, otherwise the base branch would break.
> To run locally: ./maintainers/scripts/check-by-name.sh master https://github.com/NixOS/nixpkgs.git
> Error: Process completed with exit code 1.

**Review by Frontear — CHANGES_REQUESTED** [review]
This is not the correct way to pull in dependencies.

From what I can gather from [this pr](https://github.com/NixOS/nixpkgs/pull/320250), rust 1.79 has already hit master. I haven't personally verified it but do check this out.

**Comment by AndersonTorres** [comment]
>  rust 1.79 has already hit master.

In mere two days??

**Comment by Frontear** [comment]
> > rust 1.79 has already hit master.
> 
> In mere two days??

hah, just realized both that it targeted staging and that it was only 2 days ago.

**Comment by SIGSTACKFAULT** [comment]
> rust 1.79 has already hit master.

didn't work when i tried it, but maybe that's because I was doing the build wrong. `nix-build -A zola`

**Comment by AndersonTorres** [comment]
Let's wait a bit more.

**Comment by SIGSTACKFAULT** [comment]
Y'all want me to mark it as draft, or do you have a "blocked" label, or what?

**Review by Frontear — APPROVED** [review]
Looks great! Waiting on Rust 1.79 to hit mainline before it can be merged. Congrats on the new PR!

**Comment by AndersonTorres** [comment]
> Y'all want me to mark it as draft, or do you have a "blocked" label, or what?

We usually ask to mark as draft to indicate a "waiting state".

**Comment by alyssais** [comment]
1.79 is already in staging-next, so this could be merged there now.  (But if you do change the base branch, make sure you follow the documentation for how to do so without accidentally mass pinging people.)

**Comment by honnip** [comment]
rust 1.79 is on master now

Result of `nixpkgs-review pr 325370` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zola</li>
  </ul>
</details>

**Comment by AndersonTorres** [comment]
@SIGSTACKFAULT feel free to undraft.

**Comment by donovanglover** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/332403.

**Comment by SIGSTACKFAULT** [comment]
@AndersonTorres sorry, wasn't checking GH due to finals

**Pull request closed without merging**
