### PR TITLE
pythonPackages.junos_eznc: fix build by packaging missing dependencies

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

ZHF #97479 

https://hydra.nixos.org/build/126782361

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 98253` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>python27Packages.textfsm</li>
    <li>python27Packages.yamlordereddictloader</li>
    <li>python37Packages.junos-eznc</li>
    <li>python37Packages.ntc-templates</li>
    <li>python37Packages.textfsm</li>
    <li>python37Packages.yamlordereddictloader</li>
    <li>python38Packages.junos-eznc</li>
    <li>python38Packages.ntc-templates</li>
    <li>python38Packages.textfsm</li>
    <li>python38Packages.yamlordereddictloader</li>
  </ul>
</details>

**Comment by risicle** [comment]
LGTM, WFM macos 10.14 & linux x86_64

@ofborg build python37Packages.junos_eznc python38Packages.junos_eznc python27Packages.textfsm python27Packages.yamlordereddictloader

**Comment by mweinelt** [comment]
Fixed up meta.maintainer**s** in textfsm and yamlordereddictloader.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 98253 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>10 packages built:</summary>  <ul>    <li>python27Packages.textfsm</li>    <li>python27Packages.yamlordereddictloader</li>    <li>python37Packages.junos-eznc</li>    <li>python37Packages.ntc-templates</li>    <li>python37Packages.textfsm</li>    <li>python37Packages.yamlordereddictloader</li>    <li>python38Packages.junos-eznc</li>    <li>python38Packages.ntc-templates</li>    <li>python38Packages.textfsm</li>    <li>python38Packages.yamlordereddictloader</li>  </ul></details>

**Pull request merged**
