### PR TITLE
Backport: vscodium 1.56.2 -> 1.57.0 -> 1.57.1 -> 1.58.0

### PR DESCRIPTION
**Pull request by drupol**
Related to #129901

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
Wow... I never request reviews from so many of you !

**Comment by happysalada** [comment]
I think I messed up the automatic backport of vscodium. I thought it was just a matter of adding the tag, but it looks like the bot is not creating the PR.

On another note, it looks like your branch has a litte too many unrelated commits.

**Comment by drupol** [comment]
> I think I messed up the automatic backport of vscodium. I thought it was just a matter of adding the tag, but it looks like the bot is not creating the PR.
> 
> On another note, it looks like your branch has a litte too many unrelated commits.

Indeed, I created the PR against the master branch... this is why I guess it created so much mess.

I changed the base to `release-21.05` and everything seems to be fine.

**Comment by happysalada** [comment]
@drupol do you know how the automatic backport system works? (just curious)
I tried applying the backport label to the other PR but that didn't work.
I thought you might know since you asked about automatic backport in the previous PR.

**Comment by drupol** [comment]
> @drupol do you know how the automatic backport system works? (just curious)
> I tried applying the backport label to the other PR but that didn't work.
> I thought you might know since you asked about automatic backport in the previous PR.

No, I don't know how to automatize that. Is there documentation about it somewhere?

**Comment by happysalada** [comment]
@GrahamcOfBorg eval

**Comment by happysalada** [comment]
For the automatic backport, I found this https://github.com/NixOS/nixpkgs/pull/124273/files
Which links to some documentation in nixpkgs. Maybe the bot is a little slow to react, that is why it didn't do it.

Also, there is a weird failure on the CI checks, I'm not really sure why it is.

The commits themselves look good IMO.

**Comment by drupol** [comment]
> For the automatic backport, I found this https://github.com/NixOS/nixpkgs/pull/124273/files
> Which links to some documentation in nixpkgs. Maybe the bot is a little slow to react, that is why it didn't do it.

Thanks I will read that.
 
> Also, there is a weird failure on the CI checks, I'm not really sure why it is.

Same here, I asked on Matrix but got no feedback.

> The changes themselves look good IMO.

yep, I just cherry-picked the 3 missing backports.

**Comment by happysalada** [comment]
I don't really see the point of waiting for the other CI tests.
It's not like any other packages depend on vscodium.

**Comment by drupol** [comment]
Thanks :)

**Pull request merged**
