### PR TITLE
rust-analyzer: 2021-02-01 -> 2021-02-08

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112389` at cad9457f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>rust-analyzer</li>
    <li><a href="https://gist.github.com/89718ec319965da1aee5ca53e9158666">rust-analyzer-unwrapped</a></li></li>
    <li><a href="https://gist.github.com/8ca0e56e6b4f69eab467be4110b5119d">vscode-extensions.matklad.rust-analyzer</a></li></li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112389` at cad9457f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>rust-analyzer</li>
    <li><a href="https://gist.github.com/19477f902a0bbe165afe9167f96ec853">rust-analyzer-unwrapped</a></li></li>
    <li><a href="https://gist.github.com/ba34d2c0fa8498cbf167a9756a37e2e8">vscode-extensions.matklad.rust-analyzer</a></li></li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112389` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>rust-analyzer</li>
    <li>rust-analyzer-unwrapped</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package build (see https://github.com/NixOS/nixpkgs/pull/112389#issuecomment-775220698)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-112389]$ ./results/rust-analyzer/bin/rust-analyzer --version
rust-analyzer 2021-02-08
```

Looks good to me.

**Pull request merged**
