### PR TITLE
hplip: 3.17.11 -> 3.18.3

### PR DESCRIPTION
**Pull request by bgamari**
###### Motivation for this change

Improved hardware support

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
I get:

```console
$ nix-review pr 39625
...
these derivations will be built:
  /nix/store/vq381g9yb9baizlv36lbz8rqjg70yw31-hplip-3.18.4-plugin.run.drv
  /nix/store/0s67dwzvigpcrf5m1c1j1600cnilvzm3-hplip-3.18.4.drv
building '/nix/store/vq381g9yb9baizlv36lbz8rqjg70yw31-hplip-3.18.4-plugin.run.drv'...
trying https://www.openprinting.org/download/printdriver/auxfiles/HP/plugins/hplip-3.18.4-plugin.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download hplip-3.18.4-plugin.run from any mirror
builder for '/nix/store/vq381g9yb9baizlv36lbz8rqjg70yw31-hplip-3.18.4-plugin.run.drv' failed with exit code 1
cannot build derivation '/nix/store/0s67dwzvigpcrf5m1c1j1600cnilvzm3-hplip-3.18.4.drv': 1 dependencies couldn't be built
error: build of '/nix/store/0s67dwzvigpcrf5m1c1j1600cnilvzm3-hplip-3.18.4.drv' failed
The invocation of 'nix-shell --no-out-link --keep-going --max-jobs 4 --option build-use-sandbox true --run true -p hplipWithPlugin_3_16_11 -p hplip -p hplipWithPlugin' failed
```

**Comment by davidak** [comment]
I was able to build and execute. Maybe just a small outage of the website.

**Review by davidak — APPROVED** [review]

**Comment by Mic92** [comment]
@GrahamcOfBorg build hplipWithPlugin_3_16_11 hplip hplipWithPlugin

**Comment by bgamari** [comment]
Hmm, odd. I suppose we could either just wait for a 3.18.4 release or bump this down to 3.18.3. Opinions?

**Comment by davidak** [comment]
>wait for a 3.18.4 release

How long could that take? Maybe ask and decide respectively.

**Comment by xeji** [comment]
> I suppose we could either just wait for a 3.18.4 release or bump this down to 3.18.3. 

I'm fine either way. Marking this as WIP until resolved.

**Comment by bgamari** [comment]
Honestly I have no idea; I've ping `#openprinting` but I don't hold out much hope for getting a response.

**Comment by xeji** [comment]
@GrahamcOfBorg build hplip hplipWithPlugin hplipWithPlugin_3_16_11

**Comment by xeji** [comment]
> The following builds were skipped because they don't evaluate on x86_64-linux: hplipWithPlugin, hplipWithPlugin_3_16_11

Don't understand this. Everythin evaluates and builds locally.

**Comment by xeji** [comment]
There's a (previously existing) bug in `top-level/all-packages.nix`:
```
hplipWithPlugin_3_16_11 = hplip.override { withPlugin = true; };
```
is wrong, it should be 
```
hplipWithPlugin_3_16_11 = hplip_3_16_11.override { withPlugin = true; };
```

@bgamari can you please fix that as well so we can get this merged?

**Comment by xeji** [comment]
Thank you for fixing this!
 
@GrahamcOfBorg build hplip hplipWithPlugin hplip_3_16_11 hplipWithPlugin_3_16_11

**Comment by xeji** [comment]
> The following builds were skipped because they don't evaluate on x86_64-linux: hplipWithPlugin, hplipWithPlugin_3_16_11

Still no idea what's going on here but it should be ok since everything builds fine after merging locally.

**Pull request merged**
