### PR TITLE
AusweisApp2: 1.26.7 -> 2.0.1

### PR DESCRIPTION
**Pull request by B4dM4n**
## Description of changes

Update AusweisApp2. 

https://github.com/Governikus/AusweisApp2/releases/tag/2.0.0

- Rename package to `AusweisApp`
- Add an alias to the old name
- Enable Wayland support
- Update metadata (description and homepage)

## Things done

- Tested "Smartphone as Card Reader" function

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kilianar** [comment]
The name change from AusweisApp2 to AusweisApp should probably also be done in the module (`nixos/modules/programs/ausweisapp.nix`).

**Comment by kilianar** [comment]
Since the pull request already introduces a substantial number of changes to the package, this presents a great opportunity to align with best practices. Consider replacing `rec` with the `finalAttrs` pattern and eliminating the need for `with lib;` by utilizing `lib.*` directly.

**Comment by kilianar** [comment]
By the way, I just checked to see if there are any conventions regarding the use of capital letters in package names.
https://github.com/NixOS/nixpkgs/blob/eb2f8aa686fe22faf939f3ef158f9062f908e6e2/pkgs/README.md?plain=1#L330

**Comment by B4dM4n** [comment]
Thank you for the feedback. I was not aware of the "no uppercase letters" rule, but I agree that it looked wrong.

I have updated all names and removed the `rec` and `with lib;` uses.

**Comment by kilianar** [comment]
[2.0.1](https://github.com/Governikus/AusweisApp2/releases/tag/2.0.1) has just been released, which includes a minor fix for MacOS.

**Comment by B4dM4n** [comment]
Pushed a new update with version 2.0.1.

I also added a `version` test, to ensure the binary version matches the expected one (I forgot to change the src hash and used the old one for some time).

**Review by kilianar — APPROVED** [review]
Looks good to me! Tried it out real quick with a smartphone as a card reader, and everything went as expected.

**Comment by Shawn8901** [comment]
Result of `nixpkgs-review pr 266228` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ausweisapp</li>
  </ul>
</details>

**Review by Shawn8901 — APPROVED** [review]
I did mainly check for functionality, refactored app works fine for me.
Did read out the id card by the app and tried browser login with firefox (login to elster (taxes in germany))
I used also a smartphone as card reader, like kilianar.

**Review by yayayayaka — APPROVED** [review]

**Pull request merged**
