### PR TITLE
Dpdk: backport to Release 16.03

### PR DESCRIPTION
**Pull request by abuibrahim**
###### Motivation for this change

Refactor DPDK to allow building out-of-tree external apps.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Could you use a more descriptive issue subject?

cc maintainer @domenkozar

**Comment by domenkozar** [comment]
Very cool :)

**Comment by abuibrahim** [comment]
Thanks for merging it Domen! And sorry about the missing issue subject. I didn't realize I had to create an issue first before sending PR.

Now that these commits made it into release-16.03, how do you recommend to get them into master? Do you want me to send another PR on master?

**Comment by domenkozar** [comment]
@abuibrahim yes please :)

**Comment by danbst** [comment]
@abuibrahim Would you mind to look at 16.03 failure https://hydra.nixos.org/build/36571197 ?

**Pull request merged**
