### PR TITLE
[python-updates] 2024/03/07 - major updates

### PR DESCRIPTION
**Pull request by mweinelt**
This is a bulk update of python packages, that includes major version bumps.

### Known Issues:
- [x] fonttools fails some tests; cc @sternenseemann 
- [x] trio has a broken test environment
- These packages are getting stuck on hydra
  - [x] [asks](https://hydra.lossy.network/log/p6khini84wd0sidl8qmp91skf48pyi5r-python3.12-asks-3.0.0.drv) 
  - [x] caldav
  - [x] connexion
  - [x] [pyinsteon](https://hydra.lossy.network/log/ig2gk6j3sizmrb0l6hnlvlisw81z5xby-python3.12-pyinsteon-1.5.3.drv)
  - [ ] [clustershell](https://hydra.lossy.network/log/r6d056j02dv1kv3fy569bq1pjh56g000-python3.11-ClusterShell-1.9.2.drv)

### Latest eval report

- https://hydra.lossy.network/jobset/nixpkgs/python-updates
- https://shells.darmstadt.ccc.de/~hexa/137.html

---

Closes #287619
Closes #292435 
Closes #292778
Closes #285504
Closes #282252
Closes #282458
Closes #283022
Closes #287356
Closes #292088
Closes #292849
Closes #285273

### CODE REVIEW

**Review by lukegb — APPROVED** [review]
`buildcatrust` looks fine, :shipit:

**Comment by kirillrdy** [comment]
fix trio build https://github.com/NixOS/nixpkgs/pull/294368

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/122.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/125.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/126.html (+127)

**Comment by mweinelt** [comment]
@natsukium matrix just went :boom:. Please use `pytest_7` as needed.

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/127.html (+2109)

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/129.html (+400)

**Comment by mweinelt** [comment]
Rebased to include a fix for ffmpeg, which would previously skew the build results.

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/131.html (+52)

**Comment by mweinelt** [comment]
@dotlambda pytest-asyncio was another 12.5k rebuilds after the rebase, so not ideal at this time.

**Comment by dotlambda** [comment]
> @dotlambda pytest-asyncio was another 12.5k (of 17k) rebuilds after the rebase. Could've been timed better.

Feel free to remove that commit.

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/136.html

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/137.html (+11)

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/138.html (+75)

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/144.html (+801)

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/147.html (+867)

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/150.html (+61)

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/153.html (+244)

**Comment by sternenseemann** [comment]
@mweinelt do you know the status of fonttools on merge?

**Comment by hacker1024** [comment]
This broke `weaviate-client`. It's also a major API change - should v3 be kept?

**Comment by DontEatOreo** [comment]
Closes #291917

**Pull request merged**
