### PR TITLE
osu-lazer: 2020.725.0 -> 2020.801.0

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — APPROVED** [review]
Built with `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 94468"`. Builds and runs just fine.

You can thick the 3rd checkbox in the description-

**Comment by dasj19** [comment]
This PR is aiming for the same thing as : https://github.com/NixOS/nixpkgs/pull/94542

**Comment by ryantm** [comment]
Looks like I need to work on my PR duplicate checking for updateScript updates!

**Comment by oxalica** [comment]
@ryantm Thanks for the bot update. Does all packages from GitHub with `updateScript` handled by the bot?

**Comment by ryantm** [comment]
@oxalica I just started doing updateScript updates, so I can't comment on how well it works yet.

**Comment by oxalica** [comment]
Merged in #94542

**Pull request closed without merging**
