### PR TITLE
make-derivation.nix: allow equality-test of meta-check-failing derivations

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

This allows checking the equality of derivations whose meta-checks fail.

A `throw` still occurs if you try to instantiate or build a meta-check-failing derivation, or a derivation which uses such a derivation as an `inputDrv`.

This PR is a more general fix for the issue that #212832 solves; both of them result in the following no longer incorrectly failing:

```
nix-instantiate -A pkgsCross.x86_64-freebsd.__splicedPackages.docutils.__spliced.buildHost
```

#212832 also cleans up some really hard-to-read expressions in `interpreters/python`, so this is not a replacement for it.  However this PR will prevent similar problems from arising in the future.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] powerpc64le-linux
  - [ ] aarch64-linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
This also improves the [eval report](https://github.com/NixOS/nixpkgs/pull/213096/checks?check_run_id=10945518541) numbers by 5%-10%, which is totally plausible.

The only [eval changes](https://gist.github.com/GrahamcOfBorg/3bd797445c5328ff0e94f37ad9da373c) are:

- `nixos-install-tools`, since it is a verbatim copy of `nixpkgs/lib`
- `tests.nixos-functions.nixos-test`, since it depends on `nixos-install-tools`

**Comment by alyssais** [comment]
> This also improves the [eval report](https://github.com/NixOS/nixpkgs/pull/213096/checks?check_run_id=10945518541) numbers by 5%-10%, which is totally plausible.

Wow!

**Review by alyssais — APPROVED** [review]
LGTM but I'm hoping for more eyes in case there's some non-obvious problem with this a non-expert like me would miss.

**Comment by amjoseph-nixpkgs** [comment]
> Wow!

Yeah, that was too good to be true.  Disabling the meta checks entirely [gives about the same improvement](https://github.com/NixOS/nixpkgs/pull/213146/checks?check_run_id=10947411947).  I thought it was much worse.

I need to take a closer look at this.

**Comment by alyssais** [comment]
I did some investigation of how many packages would have their evaluation fixed when cross-compiling:

This fixes evaluation of 3066 packages when cross-compiling from `{ system = "x86_64-linux"; }` to `{ system = "x86_64-freebsd"; useLLVM = true; }`.  Mine only fixes eval of 254.

For a cross case that's more typical of most Nixpkgs users, `{ system = "x86_64-linux"; }` to `{ system = "aarch64-linux"; }`, there are still 941 packages that can now be evaluated as a result of this change.

**Comment by alyssais** [comment]
When this is ready, it should include a revert of https://github.com/NixOS/nixpkgs/commit/b682fef8e96996812fd95fe033b58cf4545e2a70, which it will obsolete.

**Comment by amjoseph-nixpkgs** [comment]
Yeah unfortunately I fear that this PR's fix might just be skipping some of the meta checks entirely.

I'm about to leave town so I won't be able to investigate this with the care it deserves for another week or two.  You should definitely merge your PR.

**Comment by alyssais** [comment]
> You should definitely merge your PR.

Already done. :)

**Comment by alyssais** [comment]
@amjoseph-nixpkgs are you still planning on looking at this? Just hit a case where it would be useful (`lib.meta.availableOn stdenv.hostPlatform pkgsStatic.stdenv.cc.libc`).

**Comment by amjoseph-nixpkgs** [comment]
I do plan on coming back to this, but not until after 23.05 branches off, and didn't plan on making it a particularly high priority.  But I can adjust that.  What did you have in mind?

**Comment by alyssais** [comment]
> What did you have in mind?

Just that it would be useful to be able to check whether Musl is supported on the current architecture, to opportunistically use static builds in some [special cases](https://github.com/NixOS/nixpkgs/pull/228712#issuecomment-1527459471).

**Pull request closed without merging**
