### PR TITLE
sqlite: 3.37.2 -> 3.38.0

### PR DESCRIPTION
**Pull request by williballenthin**
###### Description of changes

[https://www.sqlite.org/releaselog/3_38_0.html](https://www.sqlite.org/releaselog/3_38_0.html)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by williballenthin** [comment]
I haven't tried to touch/update any core nixpkg like sqlite before. I'm just copying what I've seen done before in the git logs for sqlite. Please let me know if there are further steps I should be taking.

I'm currently running `nixpkgs-review`. I'm not sure if it will/won't take a long time due to the number of packages that depend on sqlite.


```console
$ nix-env --option system aarch64-darwin -f /Users/user/.cache/nixpkgs-review/rev-7e387dd41d831e58e7d5b1fcdef1795227695525/nixpkgs -qaP --xml --out-path --show-trace --meta
17996 packages updated:
0verkill-unstable 1password-cli 20kly 2bwm 2fa 3mux [...]
```

**Comment by williballenthin** [comment]
```console
$ nix --experimental-features nix-command build --no-link --keep-going -f /Users/user/.cache/nixpkgs-review/rev-7e387dd41d831e58e7d5b1fcdef1795227695525/build.nix
[0/45496 built, 1/0/26904 copied (0.0/136520.6 MiB), 21.8/56482.3 MiB DL]
[...]
```

I'm not going to be able to run all of these builds, but I'll do a few to ensure there are no obvious breaks.

**Comment by zowoq** [comment]
3.38.1 is in staging next: https://nixpk.gs/pr-tracker.html?pr=164381
https://github.com/NixOS/nixpkgs/pull/161429
https://github.com/NixOS/nixpkgs/pull/164381

3.38.2 is in staging: https://nixpk.gs/pr-tracker.html?pr=166316
https://github.com/NixOS/nixpkgs/pull/166316

**Comment by williballenthin** [comment]
Ah, thank you @zowoq! I appreciate your patience pointing out the duplication to me. I’ll know for next time to also check staging for updates, too.

**Pull request closed without merging**
