### PR TITLE
colorls: init at 1.2.0

### PR DESCRIPTION
**Pull request by lukebfox**
###### Motivation for this change

`colorls` is a tool which beautifies the terminal's ls command, with color and icons.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
I'm probably missing something, but why is ` pkgs/tools/system/colorls/colorls` needed? It appears to be pretty similar to `pkgs/tools/system/colors`, right?

**Comment by lukebfox** [comment]
Please correct me if I am wrong, but the only package named "colors" is related to haskell development found in `pkgs/development/haskell-modules/hackage-packages`. I can't see a `pkgs/tools/system/colors` at all.

**Comment by Ma27** [comment]
> Please correct me if I am wrong, but the only package named "colors" is related to haskell development found in pkgs/development/haskell-modules/hackage-packages. I can't see a pkgs/tools/system/colors at all.

That's been a typo of mine - sorry! I actually meant `colorls`. What I'm trying to understand is why there's another `colorls` directory in `pkgs/tools/system/colorls`.

**Comment by lukebfox** [comment]
Ah, you have missed nothing; well spotted. This was my mistake and I have now removed it, thanks!

**Comment by Ma27** [comment]
Built and tested locally :+1:

**Comment by Ma27** [comment]
@lukebfox thanks!

**Pull request merged**
