### PR TITLE
python311Packages.geoalchemy2: 0.14.1 -> 0.14.2

### PR DESCRIPTION
**Pull request by tu-maurice**
## Description of changes

This fixes the build of geoalchemy2 and also updates it to the latest minor version because why not.

ZHF: #265948

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by natsukium — COMMENTED** [review]
Could you please change the commit message and the PR title to `python311Packages` from `pythonPackages`?
`pythonPackages` means the packages for `Python2`.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 266114` at fd42e1df run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.flask-admin</li>
    <li>python311Packages.flask-admin</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python310Packages.geoalchemy2</li>
    <li>python311Packages.geoalchemy2</li>
  </ul>
</details>

**Comment by tu-maurice** [comment]
> Could you please change the commit message and the PR title to `python311Packages` from `pythonPackages`? `pythonPackages` means the packages for `Python2`.

I'm pretty sure changing this file updates geoalchemy2 for any python*Packages, so imho pythonPackages was the most neutral choice. Would you be fine with python*Packages ?

**Comment by natsukium** [comment]
Of course, I know that it is not limited to python311. However, since ofborg cannot automatically build packages with python3Packages, which is the alias, I recommend using the default python311Packages.

**Comment by tu-maurice** [comment]
I see.

**Review by natsukium — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
