### PR TITLE
Remove unnecessary overrides

### PR DESCRIPTION
**Pull request by ysangkok**
###### Description of changes

These overrides shouldn't be necessary any more since the packages on Hackage are now compatible. I couldn't test this because I don't have enough disk space.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by roberth — CHANGES_REQUESTED** [review]
I'm in favor of the cleanup but the build failed and GitHub is showing a ton of green-ness on this page :confused: hence this silly request for changes.

**Comment by maralorn** [comment]
Apparently there is still a need for the overrides?

Are we already testing the versions of the packages which should include the fixes?

**Comment by ysangkok** [comment]
@maralorn The newest versions of these packages indeed work on GHC 9.2, which I have tested locally with cabal-install. But it seems like the 'base' versions of these aren't the newest, since I see e.g. memory 0.16 in the test failures. So I was thinking of redoing this PR such that it selects the newer versions instead of patching the packages or jailbreaking them (I see this is what is being done with `hashable`). But maybe a better solution would be to update the base versions, since the new versions should work for older GHC's too? I am a bit new to all of this.

**Comment by maralorn** [comment]
@ysangkok We regularly update the versions of packages released to stackage or hackage on the haskell-updates branch.

Since we have working fixes for the packages currently, I recommend waiting until we automatically pull in the newest version and then drop the overrides.

My suggestion if you want to make sure this happens is, that we add assert statements to the overrides.

e.g. `memory = assert super.memory.version == 0.16.0; appendPatch ...`
with a comment `# drop overrides when assert fails`.

This way as soon as the bump automatically happens one of our routine maintainers will see the eval error and can quickly drop those overrides.

**Comment by ysangkok** [comment]
@maralorn Ok, I have adopted your suggested approach. I got NixOS installed and I discovered some other packages that really didn't need any overrides any more. I tested this using `nix-shell -p haskellPackages.ghc922.{semigroupoids,witherable,tasty-hedgehog,lucid,hedgehog,cryptohash-sha1,cryptohash-md5,scientific,hashtables,these,split,tar,vector,zlib,retry,mono-traversable,cryptonite,memory,aeson-diff}` . I can't get the `nixpkgs-review` line from the template to work, it seems to want to build everything, even stuff that is completely unrelated to Haskell.

**Comment by sternenseemann** [comment]
@ysangkok `nix-shell -p` won't pick up on changes to a local nixpkgs checkout unless told so via `-I`.

Use `nix-build -A <attr path>` from the local repository root instead.

`nixpkgs-review` won't work for testing changes to the 9.2.2 package set anyways.

**Comment by ysangkok** [comment]
@sternenseemann I have set `NIX_PATH` accordingly, and it I have errors, it saw them. So I think it loaded the local nixpkgs as intended. But thank you for the tips.

**Comment by maralorn** [comment]
Thank you so much! I have built all touched attributes locally and everything works.

**Pull request merged**
