### PR TITLE
discord: 0.0.16 -> 0.0.17

### PR DESCRIPTION
**Pull request by shlevy**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sersorrel** [comment]
Does this need backporting to 21.11?

**Comment by Kranzes** [comment]
I believe so, check what was done on the older PRs

**Comment by MikulasVanousek** [comment]
I hope you don't mind me asking here, but if I am on the unstable channel and I run `sudo nixos-rebuild --upgrade-all switch`, discord should get updated to `0.0.17`, right? It is still at version `0.0.16` and I can't figure out why.

**Comment by mohe2015** [comment]
> I hope you don't mind me asking here, but if I am on the `nixos-unstable` channel and I run `sudo nixos-rebuild --upgrade-all switch`, discord should get updated to `0.0.17`, right? It is still at version `0.0.16` and I can't figure out why.

I think the channels haven't advanced yet as there currently are unrelated issues that block this. See https://status.nixos.org/ and https://nixpk.gs/pr-tracker.html?pr=160499

You could use `master` but this is probably not a good idea. Other than that you could override the package manually.

**Comment by mohe2015** [comment]
See e.g. https://nixos.wiki/wiki/Nixpkgs/Reviewing_changes

**Pull request merged**
