### PR TITLE
python3Packages.wxPython_4_0: build on darwin

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/97101

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@fricklerhandwerk Well, I could not get it to work.

```
../../../sip/cpp/sip_webkitwxWebKitCtrl.cpp:50:35: error: unknown class name 'wxWebKitCtrl'; did you mean 'sipwxWebKitCtrl'?
class sipwxWebKitCtrl : public  ::wxWebKitCtrl
```
and 20 more of such errors.

I tried differnet versions and compile flags and fetching from GitHub but everything failed with similar errors but at different positions.

@LnL7 Do you have any idea?

**Comment by fricklerhandwerk** [comment]
You have to add WebKit at pkgs/top-level/all-packages.nix:761
Please check my old PR.

**Comment by SuperSandro2000** [comment]
> You have to add WebKit at pkgs/top-level/all-packages.nix:761
> Please check my old PR.

Forgot to push that. Still fails with the above error.

**Comment by fricklerhandwerk** [comment]
Now I'm confused, because something you did with force-pushing made [this change, which should fix the `wxmac` build](https://github.com/NixOS/nixpkgs/commit/0ee3ef03cf73e91aef887bd1b64da9b62cf24fb0) disappear. I suggest not force-pushing at all, if we work on small changes like this one and the repository allows for squash merging.

**Comment by fricklerhandwerk** [comment]
@SuperSandro2000 Are you still available for finishing this? I'm quite disappointed now, because I was ready to complete the original PR back then, but handed it over because you asked, and now this one is stuck. :(

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Are you still available for finishing this? I'm quite disappointed now, because I was ready to complete the original PR back then, but handed it over because you asked, and now this one is stuck. :(

Sorry about this. I thought this would be a very quick fix and I would be able to finish it in an evening but the building time is way to high to comfortable debug this. I'll reopen your PR.

**Pull request closed without merging**
