### PR TITLE
ocamlPackages.ppx_deriving_rpc: init at 5.9.0

### PR DESCRIPTION
**Pull request by vyorkin**
###### Motivation for this change

Adds [ppx_deriving_rpc](https://github.com/mirage/ocaml-rpc/blob/v5.9.0/ppx_deriving_rpc.opam) -- Ppx deriver for ocaml-rpc.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

So I've just inherited the `src` and `version` attributes since this seems a right thing to do in such cases.

### CODE REVIEW

**Comment by vbgl** [comment]
The build inputs you’ve listed look strange. Here is a possible patch:

~~~
--- a/pkgs/development/ocaml-modules/ppx_deriving_rpc/default.nix
+++ b/pkgs/development/ocaml-modules/ppx_deriving_rpc/default.nix
@@ -1,15 +1,15 @@
-{ stdenv, buildDunePackage, rpclib, rresult, result, ppxfind, ppx_tools, ppx_deriving, cppo }:
+{ lib, buildDunePackage, rpclib, ppxfind, ppx_deriving, cppo }:
 
 buildDunePackage rec {
   pname = "ppx_deriving_rpc";
 
   inherit (rpclib) version src;
 
-  buildInputs = [ rpclib ppx_tools ppx_deriving ppxfind cppo ];
+  buildInputs = [ ppxfind cppo ];
 
-  propagatedBuildInputs = [ result rresult ];
+  propagatedBuildInputs = [ rpclib ppx_deriving ];
 
-  meta = with stdenv.lib; {
+  meta = with lib; {
     homepage = "https://github.com/mirage/ocaml-rpc";
     description = "Ppx deriver for ocaml-rpc";
     license = licenses.isc;
~~~

**Comment by vyorkin** [comment]
Thank you @vbgl! Just to clarify (because I'm going to contribute more of OCaml packages to nixpkgs for sure): I've taken the build inputs from here https://github.com/mirage/ocaml-rpc/blob/2525190d7c95c4ad19f90e0d90796a59fa320847/ppx_deriving_rpc.opam#L14, is this a right thing to do?. For example, in the suggested patch there is no `ppx_tools`, is that correct?

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.ppx_deriving_rpc

**Comment by vbgl** [comment]
Here `ppx_tools` is implicitly brought by `ppx_deriving`. Adding it explicitly to the `buildInputs` of this package is up to you. I don’t have a strong opinion about this: I tend to prefer minimality.

**Comment by vyorkin** [comment]
Thank you for the explanation! Yeah, I agree about minimality

**Pull request merged**
