### PR TITLE
steamPackages.steam-runtime: 0.20210317.0 -> 0.20210527.0

### LINKED ISSUE #124308: Steam startup fails on missing `libpipewire-0.3.so.0` library
I have `pkgs.steam` installed, and as of 24-05-2021 it fails with the following output:

```
Running Steam on nixos 20.09.4169.ac60476ed94 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Error: You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0
Can't find 'steam-runtime-check-requirements', continuing anyway
…
[elided for brevity]
…
Failed to load steamui.so - dlerror(): libpipewire-0.3.so.0: cannot open shared object file: No such file or directory
[2021-05-24 17:47:57] Shutdown
```

**To Reproduce**

1. install `pkgs.steam` on stable channel 21.05
2. execute `steam`

**Notes and findings**

- I do not use pipewire. This bug seems to happen regardless.
- This bug seems fresh. See [a corresponding discussion](https://forum.manjaro.org/t/steam-beta-client-fails-to-start-since-today-32-bit-pipewire-support-missing/67780/2) on the Manjaro forums.
- As far as I can tell, `libpipewire-0.3.so.0` is not available in nixpkgs.
- This may be fixed in the new Steam runtime. 

**Notify maintainers**

@jagajaga. Thank you!

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.119, NixOS, 20.09.4169.ac60476ed94 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixpkgs-20.09.4169.ac60476ed94"`
 - channels(matt): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.steam
```

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Closes #124308

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 126138` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>kodiPackages.steam-launcher</li>
    <li>lutris</li>
    <li>protontricks</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steamcmd</li>
  </ul>
</details>

**Review by dominikh — APPROVED** [review]

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 126138` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>kodiPackages.steam-launcher</li>
    <li>lutris</li>
    <li>protontricks</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steam-tui</li>
    <li>steamcmd</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks sane

I can confirm this fixes the issue.

Thanks a lot to @dominikh and @Artturin for creating the fix! :sparkles:

**Comment by jonringer** [comment]
I don't think this fixed the pipewire issue
```
$ ls $(nix-build -A steamPackages.steam-runtime)/lib/{i386,x86_64}-linux-gnu/lib* | wc -l
98
$ ls $(nix-build -A steamPackages.steam-runtime)/lib/{i386,x86_64}-linux-gnu/lib* | grep pipe | wc -l
0
```

**Comment by jonringer** [comment]
guess git was playing tricks on me, i did a pull after it was merged, but it didn't actually update

**Comment by jonringer** [comment]
actually, no, it wasn't I'm guessing valve rolled out an update, which required it, but then reverted the requirement.

**Comment by Artturin** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/7807#issuecomment-847306383

**Comment by jonringer** [comment]
Ah, my cognitive dissonance was correct :)

**Comment by Artturin** [comment]
#126147

**Pull request merged**
