### PR TITLE
bazel: 0.13.0 -> 0.15.0

### PR DESCRIPTION
**Pull request by mboes**
###### Motivation for this change

Upgrade to latest Bazel.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jdanekrh** [comment]
What's the policy on upgrading of things in nixpkgs/pkgs/development/tools/build-managers/bazel/buildtools/? Is it preferred to keep it current with the bazel version as a matter of principle, or is it touched only if truly needed?

**Comment by jdanekrh** [comment]
Cannot compile envoy with this 0.15

    $ git clone git@github.com:envoyproxy/envoy.git
    $ cd envoy

    $ bazel build --verbose_failures --worker_verbose
    INFO: Analysed 0 targets (0 packages loaded).
    INFO: Found 0 targets...
    ERROR: Process exited with status 126: Process exited with status 126
    /bin/sh: bazel/get_workspace_status: /bin/bash: bad interpreter: No such file or directory
    INFO: Elapsed time: 0.110s, Critical Path: 0.01s
    FAILED: Build did NOT complete successfully

**Comment by xeji** [comment]
That issue is not directly related to this PR. 
`envoy` in nixpkgs is still pinned to `bazel_0_4` because apparently it does not compile with newer versions. Don't know why though.

**Comment by xeji** [comment]
@GrahamcOfBorg build bazel

**Review by xeji — COMMENTED** [review]
Build fails, please fix

**Comment by kalbasit** [comment]
@mboes Have you been able to debug this issue? It's blocking me from moving to NixOS as we rely on Bazel 0.14 at work :disappointed:

**Comment by jdanekrh** [comment]
@Profpatsch Thanks for the explanation. I knew about the sandbox (from the default github issue template) but I did not realize it blocks network, too, I thought it is only to restrict access to random files in the filesystem.

**Comment by Profpatsch** [comment]
Okay, this small patch makes bazel fail before it starts the build in case there’s still dependencies missing.

`tools/cpp/cc_configure` and a few others reference a project called `@bazel_tools`, which doesn’t seem to be mentioned in the `WORKSPACE` file, so perhaps this is an oversight of upstream.
Will try to fix this tomorrow.

**Comment by Profpatsch** [comment]
I think I have a pretty good grasp on the bootstrap now, and the build should be fixed by tomorrow. In the meantime, have some debugging notes:

```org
   - Yet another try at fixing the bazel build
     - https://github.com/bazelbuild/bazel/pull/4860/commits/5d4a78883393ad411e1dfb9671581fab6b5519f1
       looked promising, but was not it.
     - The internal module `@bazel_tools` is not recognized in the last step of
       the bootstrap.
     - Bootstrap: first compile bazel once with javac
       (~scripts/bootstrap/compile.sh~), then set everything up, so it can be
       compiled again with itself; ~libblaze.jar~ is the output (~blaze~ is the
       name of bazel’s server part).
       In this it fails to setup the bazel_tools repository to the correct path,
       so bazel doesn’t know where to find these repositories when no fetching
       is allowed (which was not set by default!)
     - If ~$BAZEL~ is set it will use the given bazel, otherwise it will use
       ~libbblaze.jar~ in the function ~run_bazel_jar~ at the bottom of
       ~scripts/bootstrap/compile.js~.
     - bazel takes an ~install_base~ argument. This is where the bazel
       distribution should be located.
     - The ~tools.WORKSPACE~ file for ~bazel_tools~ contains the directive
       ~local_repository(name = "bazel_tools", path = __embedded_dir__ + "/embedded_tools")~
       with the magic symbol ~__embedded_dir__~. This symbol is replaced in
       ~WorkspaceFactory.java~ by the actual path of
       ~$install_base/_embedded_binaries"~, so the combined path where bazel
       searches for ~bazel_tools~ should be
       ~$install_base/_embedded_binaries/embedded_tools~
     - If all of that sounds a little ad-hoc, it is because it is. Also, it is
       wrapped in a few hundred lines of ad-hoc shell code.
```

**Comment by Profpatsch** [comment]
cross ref: https://github.com/bazelbuild/bazel/pull/4860#issuecomment-404485804

There should probably be an issue upstream about adding `fetch=no` to the bootstrap and why it can’t find builtin packages if that’s set, which looks like a bug.

@GrahamcOfBorg build bazel

**Comment by Profpatsch** [comment]
Uh, merge conflict because the file got 300% larger in the meantime. https://github.com/NixOS/nixpkgs/pull/42832

I think that should be reverted and reworked.

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build bazel

**Comment by Profpatsch** [comment]
Will smuggle this in here, since ofborg doesn’t work on issues (yet):
https://github.com/NixOS/nixpkgs/issues/30590#issuecomment-404817016

@GrahamcOfBorg build bazel_0_4

**Comment by Profpatsch** [comment]
Oh, and
@GrahamcOfBorg eval

**Comment by kalbasit** [comment]
I would wait on merging this anyway until Bazel [0.15.1](https://github.com/bazelbuild/bazel/issues/5591) is released. Bazel 0.15.0 is broken on Mac. See https://github.com/bazelbuild/bazel/issues/5468 for context.

**Comment by Profpatsch** [comment]
@kalbasit Nice catch. It looks like the patch version might be released today or tomorrow. I’d merge this now and do the transition to `0.15.1` as soon as it comes out. Then we see whether we can apply a cleaned up Mac support.

**Comment by Profpatsch** [comment]
@mboes should we merge?

**Comment by mboes** [comment]
If merging this doesn't introduce any regressions for anyone, then yes. But if macOS used to work but now can't because of an upstream bug then let's wait for 0.15.1.

**Comment by mboes** [comment]
@Profpatsch FYI I found a way to be `--sandbox` compliant without disabling bash autocompletion. The trick is to use the `--experimental_distdir` flag (which incidentally, will be renamed to `--distdir` in v0.16).

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build bazel

**Comment by kalbasit** [comment]
Bazel [0.15.1](https://github.com/bazelbuild/bazel/releases/tag/0.15.1) is now out, can we get this PR updated and merged?

**Comment by Profpatsch** [comment]
@kalbasit I did push the update to the branch a few minutes ago, but it didn’t appear here. I think Github was unavailable a few minutes ago, maybe the servers are still catching up.

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build bazel

**Comment by Profpatsch** [comment]
Okay, I think we are ready to merge!

**Comment by Profpatsch** [comment]
cc @uri-canva Now we can try to fix the Darwin build, it should in principle work with `0.15.1`.

**Pull request merged**
