### PR TITLE
discourse: 3.1.0 <- 3.2.0.beta1

### LINKED ISSUE #286332: Build failure: discourse
### Steps To Reproduce

1. build discourse

Hydra has it failing at https://hydra.nixos.org/build/247921046

### Build log
The pertinent bit seems to be:

```
yarn run v1.22.19
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ /build/source/app/assets/javascripts/node_modules/.bin/patch-package
patch-package 8.0.0
Applying patches...
@ember/jquery@2.0.0 ✔
@ember/legacy-built-in-components@0.4.2 ✔
babel-plugin-debug-macros@0.3.4 ✔
ember-source@3.28.12 ✔
ember-this-fallback@0.3.1 (1 initial) ✔
ember-this-fallback@0.3.1 (2 themes) ✔
virtual-dom@2.1.1 ✔
Done in 0.15s.
Waiting for Redis and PostgreSQL to be ready..
2024-02-04 17:50:39.591 UTC [798] LOG:  starting PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.2.0, 64-bit
2024-02-04 17:50:39.591 UTC [798] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-02-04 17:50:39.591 UTC [798] LOG:  listening on Unix socket "/build/.s.PGSQL.5432"
2024-02-04 17:50:39.593 UTC [803] LOG:  database system was shut down at 2024-02-04 17:50:39 UTC
2024-02-04 17:50:39.595 UTC [798] LOG:  database system is ready to accept connections
CREATE ROLE
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> Seeding theme and color schemes
Couldn't connect to Redis
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
```
### Additional context

Nothing in particular

### Notify maintainers

@talyz 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.2, NixOS, 24.05 (Uakari), 24.05.20240204.0bb0d40`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

The beta doesn't build, revert to a release.

Fix #286332

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Lets wait a couple of days so that the maintainers can answer and maybe fix this

**Comment by drupol** [comment]
How about switching to 3.2.0 stable? Perhaps that will fix the issue?

**Comment by wegank** [comment]
@ofborg build discourse discourse.passthru.tests

**Comment by drupol** [comment]
> How about switching to 3.2.0 stable? Perhaps that will fix the issue?

@wegank thanks for merging without addressing the question I asked.

**Comment by wegank** [comment]
I'm sorry I didn't address your question. I suppose so, but since the question was asked for over a week, and discourse has been [broken for months](https://hydra.nixos.org/job/nixpkgs/trunk/discourse.x86_64-linux/all?page=2), I can only assume that the package is unmaintained and no one would do anything (or do you want to create a PR to do the upgrade?).

**Comment by drupol** [comment]
I just see your reply now. Thanks for replying to it. I wish I could do the upgrade to 3.2.0, but I don't know anything about the Ruby ecosystem and Discourse.

**Pull request merged**
