### PR TITLE
nixos/tests: add forgotten xrdp.nix

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

nixos/tests: add forgotten xrdp.nix

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg test xrdp

**Comment by volth** [comment]
seems like the CI bot gives up even before the test starts.

**Comment by dtzWill** [comment]
LGTM on the surface.  Looks good on x86_64-linux, trying on aarch64 now as well....

**Comment by dtzWill** [comment]
Not looking good on aarch64, waiting for "session opened"? Will let it time out completely...

Should this perhaps be limited to x86_64-linux, then? Seems like a shame but is better than not testing xrdp at all.

**Comment by volth** [comment]
```xrdp``` should work on ```aarch64-linux```, I have been using it.
The options are:
1. regression on ```aarch64-linux``` (I used ```0.9.3```, the current master has ```0.9.5```)
2. something wrong with the test, it have not been tested on ```aarch64-linux```

**Comment by dtzWill** [comment]
Are you able to investigate on your aarch64 machines?

FWIW, here's what I'm seeing: https://gist.github.com/dtzWill/53d4dae1afb2d1b6a8b1033545e4e0b0

**Comment by dtzWill** [comment]
I'm seeing this for sddm.nix as well, probably others.

**Comment by volth** [comment]
> Are you able to investigate on your aarch64 machines?

packet.net gives $25 credit with coupon "nixos"

> FWIW, here's what I'm seeing: https://gist.github.com/dtzWill/53d4dae1afb2d1b6a8b1033545e4e0b0

It is in ```waitForX``` function
https://github.com/NixOS/nixpkgs/blob/814b38541f666febaa5d344eeb512f6ef8b68803/nixos/lib/test-driver/Machine.pm#L615
So, yes, not specific to this test

**Pull request merged**
