### PR TITLE
nixos: release.nix: add `configuration` parameter

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

I wanted to build stuff in `release.nix` with `doCheckByDefault` of #39464 enabled.

###### Things done

- [X] It works as expected when needed.
- [X] Noop by default.

### CODE REVIEW

**Comment by oxij** [comment]
ping?

**Comment by oxij** [comment]
ping ping?

**Comment by oxij** [comment]
@vcunat @xeji @7c6f434c ping^3

**Review by xeji — APPROVED** [review]
LGTM, I can see no downside.

**Pull request merged**
