### PR TITLE
ammonite_2_xx: 2.3.8 -> git, ammonite_3_00: init at 3.0.0-M3

### LINKED ISSUE #113923: ammonite: need to build from git sources
###### Checklist

`pkgs.ammonite` uses binary distribution, which is problematic:

1. binary distributions are released not often and lag behind Scala progress. Both `pkgs.ammonite_2_12` and `pkgs.ammonite_2_13` use older Scala than ones in `pkgs.scala_2_12` and `pkgs.scala_2_13`
2. the sources needs patches for nix ("/usr/bin/tput" -> "${ncurses}/bin/tput", etc): https://github.com/lihaoyi/Ammonite/blob/4bd225eb73802285ff4c77056594c196d1685c5e/terminal/src/main/scala/ammonite/terminal/Utils.scala#L89-L99
3. There is unrealized yet `ammonite` for Scala 3 (https://github.com/lihaoyi/Ammonite/pull/1150), which would be easier to pack having in `nixpkgs` established procedure of building `ammonite` from git sources 

###### Project name
`nix search` name: ammonite

current version:
desired version:

###### Notify maintainers
maintainers: @NeQuissimus 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by vobloeb**
###### Motivation for this change

1. update to actual Scala versions (the latest binary release `2.3.8` uses outdated Scala and it lags always)
2. patch `/usr/bin/...`-paths to Nix Store paths

Fixes #113923
Related #110517

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113967` at d2b46ff6 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/92753fdbe5f2430e7490542ad092220d">ammonite</a></li> (ammonite_2_13)</li>
    <li><a href="https://gist.github.com/89f5dfcb9c7ba9783de4ee0898524f38">ammonite_2_12</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/ammonite/default.nix:63:7:
```
   |
63 |       buildPhase = ''
   |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/ammonite/default.nix:81:7:
```
   |
81 |       installPhase = ''
   |       ^
```
</li>
  </ul>
</details>

**Comment by NeQuissimus** [comment]
I would really not want to lose track of the tagged versions here.
It is fine to actually build from source but we should not just use the git HEAD if actual tags are available.
Anybody is free to create an overlay to use any git commit but an unstable version should not be in nixpkgs.

**Comment by kvtb** [comment]
> I would really not want to lose track of the tagged versions here.
> It is fine to actually build from source but we should not just use the git HEAD if actual tags are available.
> Anybody is free to create an overlay to use any git commit but an unstable version should not be in nixpkgs.

1. What is wrong with tagged versions: tags are set rarely and they do not follow Scala development. The latest tagged Ammonite is for Scala 2.12.10, the latest Scala is 2.12.13. (2.13.x lags too). And there is no tagged version for Dotty at all.
2. I am not looking for any sort of inclusion into nixpkgs (why should I care?), I am looking for code review and feedback from expediences devs.

**Comment by JonathanReeve** [comment]
How is this going? I'd like to be able to use Ammonite with Scala 3, but there appears to be no easy way to do that on NixOS at the moment.

**Pull request closed without merging**
