### PR TITLE
r8125: 9.003.02 -> 9.003.05

### PR DESCRIPTION
**Pull request by notpeelz**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested the kernel module ~~Tested execution of all binary files (usually in `./result/bin/`)~~
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
Maybe this should target staging because it forces a rebuild of the Linux kernel?? Not honestly sure about how the process for getting driver updates accepted works. Working on building locally in meantime, but running into a few build problems, looks like it's due to my machine though (e.g. running out of space).

**Comment by LouisTakePILLz** [comment]
Not sure, perhaps @jonringer would know.

Also note that 9.003.04 is broken on the latest kernel (5.6) and Realtek hasn't released a new version yet.

**Comment by drewrisinger** [comment]
Here's the result of my ``nixpkgs-review pr 85669``. Take some of this with a grain of salt b/c of the "out of space" issue mentioned above.

```
https://github.com/NixOS/nixpkgs/pull/85669
2 package marked as broken and skipped:
linuxPackages_hardkernel_4_14.r8125 linuxPackages_hardkernel_latest.r8125

6 package failed to build:
linuxPackages_5_6.r8125 linuxPackages_latest-libre.r8125 linuxPackages_latest_hardened.r8125 linuxPackages_latest_xen_dom0.r8125 linuxPackages_latest_xen_dom0_hardened.r8125 linuxPackages_xen_dom0_hardened.r8125

10 package built:
linuxPackages-libre.r8125 linuxPackages.r8125 linuxPackages_4_14.r8125 linuxPackages_4_19.r8125 linuxPackages_4_4.r8125 linuxPackages_4_9.r8125 linuxPackages_5_5.r8125 linuxPackages_hardened.r8125 linuxPackages_testing_bcachefs.r8125 linuxPackages_xen_dom0.r8125
```

**Comment by LouisTakePILLz** [comment]
All of the `linuxPackages_latest` and `linuxPackages_5_6` are expected to fail because r8125 hasn't been updated for that kernel yet. Not sure about `linuxPackages_xen_dom0_hardened`.

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds cleanly via nix-review (except for marked broken, see below)
* [ ] NOT TESTED. Not sure how to test.

**Review by danieldk — APPROVED** [review]
LGTM. @LouisTakePILLz  thanks for the update, @drewrisinger thanks for the review :+1:

Result of `nixpkgs-review pr 85669` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
<br>- linuxPackages_hardkernel_4_14.r8125
<br>- linuxPackages_hardkernel_latest.r8125
</details>
<details>
  <summary>16 packages built:</summary>
<br>- linuxPackages-libre.r8125
<br>- linuxPackages.r8125 (linuxPackages_5_4.r8125)
<br>- linuxPackages_4_14.r8125
<br>- linuxPackages_4_19.r8125
<br>- linuxPackages_4_4.r8125
<br>- linuxPackages_4_9.r8125
<br>- linuxPackages_5_6.r8125
<br>- linuxPackages_5_7.r8125 (linuxPackages_latest.r8125)
<br>- linuxPackages_hardened.r8125
<br>- linuxPackages_latest-libre.r8125
<br>- linuxPackages_latest_hardened.r8125
<br>- linuxPackages_latest_xen_dom0.r8125
<br>- linuxPackages_latest_xen_dom0_hardened.r8125
<br>- linuxPackages_testing_bcachefs.r8125
<br>- linuxPackages_xen_dom0.r8125
<br>- linuxPackages_xen_dom0_hardened.r8125
</details>

**Pull request merged**
