### PR TITLE
smarty3: Init at 3.1.32

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

I'm currently packaging [FusionDirectory](https://www.fusiondirectory.org/), and this is a dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dasJ** [comment]
Failing check unrelated

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Comment by xeji** [comment]
@GrahamcOfBorg  build smarty3

**Pull request merged**
