### PR TITLE
gitlab: 12.4.3 -> 12.5.0

### PR DESCRIPTION
**Pull request by talyz**
###### Things done

- Tested locally in a VM

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli @petabyteboy @globin @fpletz @krav

### CODE REVIEW

**Comment by talyz** [comment]
@GrahamcOfBorg test gitlab

**Comment by mweinelt** [comment]
Meanwhile 12.5.1 is out. It's a security release.

https://about.gitlab.com/blog/2019/11/27/security-release-gitlab-12-5-1-released/?utm_medium=social&utm_source=twitter&utm_campaign=securityrelease

**Comment by flokli** [comment]
pushed an update to 12.5.2, another security release from 2 hours ago.

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
backported to 19.09 in e5820bd73f920428e6f60d6bf61093e45bdc1768, 6aaa42746c90a019aa71a1aaa94cf6600501f6ea, 839b01b7ffc462a1bd89523fbcef9854bccf759e, 73fb59dbb89ed5f754249761dcd99c6ccbd24bb5.

**Review by talyz — COMMENTED** [review]
Hm, I don't think this is right... `moretea.yarn2nix` was recently renamed to `yarn2nix`; maybe your nix-shell was using an old version of nixpkgs?

**Comment by flokli** [comment]
@talyz `yarn2nix-moretea.yarn2nix` should still work on master, but you're right - we should just call it `yarn2nix` if possible. Reverted in b5cbd819545.

**Pull request merged**
