### PR TITLE
alsa-scarlett-gui: fix path of alsactl

### LINKED ISSUE #312436: alsa-scarlett-gui can't save configuration state
There is an option to save the configuration state that does not work because it tries to run `/usr/sbin/alsactl` which is not located at this path in NixOS

### Steps To Reproduce
1. Open the GUI
2. Go to File -> Save Configuration
3. Enter filename and click save

### Expected behavior
It should save a file to the filesystem with the current configuration state.

@mdorman 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source`
```

### PR DESCRIPTION
**Pull request by chewblacka**
## Description of changes
Change `alsactl` executable from `/usr/sbin/alsactl` to `alsactl` nix store path in source code

Minor changes:
- `repo = pname` is an anti-pattern. replaced with fixed string.
- replaced deprecated `sha256` with `hash`
- replaced deprecated `--replace`with `--replace-fail`

Closes https://github.com/NixOS/nixpkgs/issues/312436

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mdorman — APPROVED** [review]
Our of four changes, only one is mentioned in the MR description; I'm not saying they're bad choices, but lack of documentation for the reasoning behind changes becomes a burden over time.

I think it would also be a gift to future maintainers if you documented that the reason you're confident that just using the bare call to `alsactl` will work is because you know the wrapper will guarante that it is in the path.

**Comment by chewblacka** [comment]
> Our of four changes, only one is mentioned in the MR description; I'm not saying they're bad choices, but lack of documentation for the reasoning behind changes becomes a burden over time.

I've changed the description. `repo = pname` is an anti-pattern, and `sha256 =` and `--replace` are deprecated.

> I think it would also be a gift to future maintainers if you documented that the reason you're confident that just using the bare call to `alsactl` will work is because you know the wrapper will guarante that it is in the path.

I'm happy to change to the full nix store path. Let me know which you would prefer.

**Comment by mdorman** [comment]
> > Our of four changes, only one is mentioned in the MR description; I'm not saying they're bad choices, but lack of documentation for the reasoning behind changes becomes a burden over time.
> 
> I've changed the description. `repo = pname` is an anti-pattern, and `sha256 =` and `--replace` are deprecated.

Thanks; I know it's a small thing, but with so many people involved in the project, anything that can clarify intent is helpful.
 
> > I think it would also be a gift to future maintainers if you documented that the reason you're confident that just using the bare call to `alsactl` will work is because you know the wrapper will guarante that it is in the path.
> 
> I'm happy to change to the full nix store path. Let me know which you would prefer.

Full store path or bare command with comment, I honestly don't have a preference, I just care about documentation; I guess you could say I have a bias because I consider using the store path to be self-documenting, but I don't feel that's the only way to do it.

I guess using the store path means you don't have to worry about me bikeshedding any comment. :)  (Not that I would likely do that anyway).

**Comment by mdorman** [comment]
Regardless, I'm happy for you to merge whenever you're ready.

**Comment by chewblacka** [comment]
> Regardless, I'm happy for you to merge whenever you're ready.

Thanks. I've replaced with the full nix store path for simplicity. I don't have merge privileges so will let the next person to check this merge.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
