### PR TITLE
rocksdb: 6.4.6 -> 6.6.4

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

https://github.com/facebook/rocksdb/releases

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg build rocksdb

**Comment by nh2** [comment]
`nix-review` output:

```
1 package marked as broken and skipped:
bareos

1 package failed to build:
sortmerna

11 package built:
blockbook ceph ceph-client haskellPackages.corenlp-parser haskellPackages.rocksdb-haskell haskellPackages.rocksdb-query libceph rocksdb rocksdb_lite sambaFull zeek
```

`sortmerna` fails with:

```
-- Configuring done
CMake Error at src/sortmerna/CMakeLists.txt:78 (add_executable):
  Target "sortmerna" links to target "snappy::snappy" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/sortmerna/CMakeLists.txt:78 (add_executable):
  Target "sortmerna" links to target "lz4::lz4" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at src/sortmerna/CMakeLists.txt:78 (add_executable):
  Target "sortmerna" links to target "zstd::zstd" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/sortmerna/CMakeLists.txt:54 (add_library):
  Target "smr_objs" links to target "snappy::snappy" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/sortmerna/CMakeLists.txt:54 (add_library):
  Target "smr_objs" links to target "lz4::lz4" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at src/sortmerna/CMakeLists.txt:54 (add_library):
  Target "smr_objs" links to target "zstd::zstd" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

That is probably not related to `rocksdb`.

**Comment by nh2** [comment]
> That is probably not related to `rocksdb`.

Actually, looks like it is: Cherry-picking this PR on top of current `staging` commit 16516cec8235a7f1ac63a668ee626534a39d481c (where `sortmerna` builds) makes the build break!

**Comment by nh2** [comment]
cc @luispedro as `sortmerna` maintainer

**Comment by luispedro** [comment]
I wonder if these dependencies (`zstd`, `snappy`,...) should not move to `propagatedBuildInputs`?

**Comment by prusnak** [comment]
@basvandijk can you please modify the PR to include the latest RocksDB 6.10.2?

**Comment by prusnak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/93363

**Pull request closed without merging**
