### PR TITLE
iperf3: symlink manpage to iperf & split man output

### LINKED ISSUE #62255: iperf manpage missing
## Issue description

iperf has a manpage according to https://linux.die.net/man/1/iperf, but it’s not in the nix package.

### Steps to reproduce

```
nix-shell -p iperf --run 'man iperf'
```

cc @fpletz as maintainer.

### PR DESCRIPTION
**Pull request by Profpatsch**
Closes: https://github.com/NixOS/nixpkgs/issues/62255

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
Won't it collide with iperf2 ? like right now it's possible to run `nix run nixpkgs.iperf2 nixpkgs.iperf3`. Is it after your PR ?

**Review by fpletz — CHANGES_REQUESTED** [review]
If we change the iperf3 binary to iperf, we also need the iperf2 binary to be called iperf2 with an iperf symlink. `meta.priority` can be used to modify which iperf symlink will be use when both are in the same environment.

**Comment by Profpatsch** [comment]
Ah, then that was an oversight in a previous change. I’ll add a commit that does that.

**Comment by Profpatsch** [comment]
Okay, changed.

**Review by fpletz — APPROVED** [review]
Thanks!

**Pull request merged**
