### PR TITLE
python312Packages.plotly: 5.23.0 -> 5.24.0 and some TLC

### PR DESCRIPTION
**Pull request by Pandapip1**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Pandapip1** [comment]
Result of `nixpkgs-review pr 341141` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.pymatgen</li>
    <li>python311Packages.pymatgen.dist</li>
    <li>python311Packages.sumo</li>
    <li>python311Packages.sumo.dist</li>
    <li>python312Packages.pymatgen</li>
    <li>python312Packages.pymatgen.dist</li>
    <li>python312Packages.sumo</li>
    <li>python312Packages.sumo.dist</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>apkleaks</li>
    <li>apkleaks.dist</li>
    <li>jadx</li>
  </ul>
</details>
<details>
  <summary>115 packages built:</summary>
  <ul>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>cve-bin-tool</li>
    <li>cve-bin-tool.dist</li>
    <li>das</li>
    <li>das.dist</li>
    <li>deeptools</li>
    <li>deeptools.dist</li>
    <li>hp2p</li>
    <li>python311Packages.ax-platform</li>
    <li>python311Packages.ax-platform.dist</li>
    <li>python311Packages.catboost</li>
    <li>python311Packages.catboost.dist</li>
    <li>python311Packages.chart-studio</li>
    <li>python311Packages.chart-studio.dist</li>
    <li>python311Packages.compressai</li>
    <li>python311Packages.compressai.dist</li>
    <li>python311Packages.cufflinks</li>
    <li>python311Packages.cufflinks.dist</li>
    <li>python311Packages.dash</li>
    <li>python311Packages.dash-bootstrap-components</li>
    <li>python311Packages.dash-bootstrap-components.dist</li>
    <li>python311Packages.dash.dist</li>
    <li>python311Packages.experiment-utilities</li>
    <li>python311Packages.experiment-utilities.dist</li>
    <li>python311Packages.explorerscript</li>
    <li>python311Packages.explorerscript.dist</li>
    <li>python311Packages.igraph</li>
    <li>python311Packages.igraph.dist</li>
    <li>python311Packages.kmapper</li>
    <li>python311Packages.kmapper.dist</li>
    <li>python311Packages.leidenalg</li>
    <li>python311Packages.leidenalg.dist</li>
    <li>python311Packages.meshtastic</li>
    <li>python311Packages.meshtastic.dist</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.optuna.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
    <li>python311Packages.plotly</li>
    <li>python311Packages.plotly.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pyannote-pipeline</li>
    <li>python311Packages.pyannote-pipeline.dist</li>
    <li>python311Packages.reflex</li>
    <li>python311Packages.reflex.dist</li>
    <li>python311Packages.scikit-tda</li>
    <li>python311Packages.scikit-tda.dist</li>
    <li>python311Packages.skytemple-dtef</li>
    <li>python311Packages.skytemple-dtef.dist</li>
    <li>python311Packages.skytemple-files</li>
    <li>python311Packages.skytemple-files.dist</li>
    <li>python311Packages.skytemple-ssb-debugger</li>
    <li>python311Packages.skytemple-ssb-debugger.dist</li>
    <li>python311Packages.synergy</li>
    <li>python311Packages.synergy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python312Packages.ax-platform</li>
    <li>python312Packages.ax-platform.dist</li>
    <li>python312Packages.catboost</li>
    <li>python312Packages.catboost.dist</li>
    <li>python312Packages.chart-studio</li>
    <li>python312Packages.chart-studio.dist</li>
    <li>python312Packages.compressai</li>
    <li>python312Packages.compressai.dist</li>
    <li>python312Packages.cufflinks</li>
    <li>python312Packages.cufflinks.dist</li>
    <li>python312Packages.dash</li>
    <li>python312Packages.dash-bootstrap-components</li>
    <li>python312Packages.dash-bootstrap-components.dist</li>
    <li>python312Packages.dash.dist</li>
    <li>python312Packages.experiment-utilities</li>
    <li>python312Packages.experiment-utilities.dist</li>
    <li>python312Packages.explorerscript</li>
    <li>python312Packages.explorerscript.dist</li>
    <li>python312Packages.igraph</li>
    <li>python312Packages.igraph.dist</li>
    <li>python312Packages.kmapper</li>
    <li>python312Packages.kmapper.dist</li>
    <li>python312Packages.leidenalg</li>
    <li>python312Packages.leidenalg.dist</li>
    <li>python312Packages.meshtastic</li>
    <li>python312Packages.meshtastic.dist</li>
    <li>python312Packages.optuna</li>
    <li>python312Packages.optuna.dist</li>
    <li>python312Packages.orange3</li>
    <li>python312Packages.orange3.dist</li>
    <li>python312Packages.plotly</li>
    <li>python312Packages.plotly.dist</li>
    <li>python312Packages.pyannote-audio</li>
    <li>python312Packages.pyannote-audio.dist</li>
    <li>python312Packages.pyannote-pipeline</li>
    <li>python312Packages.pyannote-pipeline.dist</li>
    <li>python312Packages.reflex</li>
    <li>python312Packages.reflex.dist</li>
    <li>python312Packages.scikit-tda</li>
    <li>python312Packages.scikit-tda.dist</li>
    <li>python312Packages.skytemple-dtef</li>
    <li>python312Packages.skytemple-dtef.dist</li>
    <li>python312Packages.skytemple-files</li>
    <li>python312Packages.skytemple-files.dist</li>
    <li>python312Packages.skytemple-ssb-debugger</li>
    <li>python312Packages.skytemple-ssb-debugger.dist</li>
    <li>python312Packages.synergy</li>
    <li>python312Packages.synergy.dist</li>
    <li>quark-engine</li>
    <li>quark-engine.dist</li>
    <li>skytemple</li>
    <li>skytemple.dist</li>
    <li>theharvester</li>
    <li>theharvester.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
  </ul>
</details>

**Comment by Pandapip1** [comment]
Both `apkleaks` and `jadx` appear to be broken on `master`.

**Comment by pbsds** [comment]
If you want to enable the checkPhase, please make sure it actually runs the tests. I enabled pytest and ran through a couple of the errors, but there are lots more to figure out :)

```patch
diff --git a/pkgs/development/python-modules/plotly/default.nix b/pkgs/development/python-modules/plotly/default.nix
index 0ca2cc6c08a0..e94ce037258c 100644
--- a/pkgs/development/python-modules/plotly/default.nix
+++ b/pkgs/development/python-modules/plotly/default.nix
@@ -6,6 +6,20 @@
   packaging,
   tenacity,
   kaleido,
+  pytestCheckHook,
+  pandas,
+  requests,
+  matplotlib,
+  xarray,
+  pillow,
+  scipy,
+  psutil,
+  statsmodels,
+  ipython,
+  which,
+  orca,
+  nbformat,
+  scikit-image,
 }:

 buildPythonPackage rec {
@@ -20,9 +34,9 @@ buildPythonPackage rec {
     hash = "sha256-frSUybQxst4wG8g8U43Nay9dYCUXuR3dBealwPVyFdI=";
   };

-  postPatch = ''
-    cd packages/python/plotly
+  sourceRoot = "${src.name}/packages/python/plotly";

+  postPatch = ''
     substituteInPlace pyproject.toml \
       --replace-fail "\"jupyterlab~=3.0;python_version>='3.6'\"," ""
   '';
@@ -37,6 +51,23 @@ buildPythonPackage rec {
     kaleido
   ];

+  nativeCheckInputs = [
+    pytestCheckHook
+    pandas
+    requests
+    matplotlib
+    xarray
+    pillow
+    scipy
+    psutil
+    statsmodels
+    ipython
+    which
+    orca
+    nbformat
+    scikit-image
+  ];
+
   pythonImportsCheck = [ "plotly" ];

   meta = {
```

**Comment by Pandapip1** [comment]
I enabled `checkPhase` for the `pythonImportsCheckHook`, but I'll apply your diff and test it out.

**Comment by pbsds** [comment]
please review https://github.com/NixOS/nixpkgs/pull/347567

> I enabled checkPhase for the pythonImportsCheckHook, but I'll apply your diff and test it out.

pythonImportsCheckHook is gated by doInstallCheck. :)

**Pull request merged**
