### PR TITLE
[Backport release-22.11] tailscale 1.32.3 -> 1.36.2

### PR DESCRIPTION
**Pull request by blitz**
###### Description of changes

This PR backports a whole slew of tailscale updates to 22.11. This also contains at least [one security fix](https://tailscale.com/security-bulletins/#ts-2023-002) and [impressive performance improvements](https://tailscale.com/blog/throughput-improvements/).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by blitz** [comment]
Result of `nixpkgs-review pr 220127` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tailscale</li>
  </ul>
</details>

**Comment by blitz** [comment]
The "Build NixOS manual" CI failure looks unrelated.

I've tested this on my work laptop without issues. This also resolves a network throughput issue for me. :rocket:

**Review by xanderio — APPROVED** [review]

**Review by twitchyliquid64 — APPROVED** [review]

**Comment by twitchyliquid64** [comment]
LGTM on the backport, looks like the docstring needs updating to get CI passing (or maybe its flaky / ignorable?)

**Comment by blitz** [comment]
> LGTM on the backport, looks like the docstring needs updating to get CI passing (or maybe its flaky / ignorable?)

Do you know what it is complaining about? It's not like this PR touched any docs.

**Comment by blitz** [comment]
@danderson Do you see anything that would be problematic here?

**Comment by qbit** [comment]
FWIW I  have been running 1.36.2 on stable for ~3 weeks now with no issues.

**Comment by RaitoBezarius** [comment]
According to acceptable criteria for backports ([21.7.4.3. Acceptable backport criteria](https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches)), this can be considered as a client which require to be up-to-date regardless.

Therefore, I am okay with merging it as-is, except if Tailscale team says otherwise, cc @danderson @Xe ?

**Review by 06kellyjac — APPROVED** [review]
LGTM @RaitoBezarius 's queries withstanding

**Comment by danderson** [comment]
Yeah this is fine. Tailscale tries hard to not break compat, so it should always be safe and better to be on the latest version.

**Comment by danderson** [comment]
From the acceptable backporting criteria, I think the ones that apply to tailscale are new functionality or patch release, with no breaking changes. We don't require clients to be up to date the way e.g. discord does, newer clients just usually have more nice things.

**Review by RaitoBezarius — APPROVED** [review]

**Pull request merged**
