### PR TITLE
zotero: 4.0.29 -> 5.0.25

### PR DESCRIPTION
**Pull request by timor**
This uses buildFHSUserenv.  The source installation probably does not work until
node2nix supports nodejs-8.x.

###### Motivation for this change
Zotero does not come bundled with newer firefox versions anymore, only standalone is supported.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timor** [comment]
See also #31479

**Comment by c0bw3b** [comment]
This would also close #10355 presumably

**Comment by orivej** [comment]
This package should also install a menu entry (a desktop file) and icons (they are available in `data/chrome/icons/default/`). @timor Would you do this?

**Comment by timor** [comment]
@c0bw3b I have not tested all the things mentioned in #10355

@orivej Haven't done this before, is there a good example package?  Also, how to test that, I am not using a desktop environment?

**Comment by orivej** [comment]
I don't know how to test this without a desktop environment, so I've pushed a commit with the desktop entry.

**Review by orivej — APPROVED** [review]

**Comment by devhell** [comment]
This is amazing, thank you @timor! 🍻

**Pull request merged**
