### PR TITLE
Fix supercollider

### LINKED ISSUE #15797: supercollider does not build on unstable
### Steps to reproduce

nix-shell -p supercollider

## Technical details

[anders@gurney:~]
$ nixos-version
16.09.git.ef7e753 (Flounder)
[anders@gurney:~]
$ nix-env --version
nix-env (Nix) 1.11.2
[anders@gurney:~]
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.git.ef7e753M"

## Error message

```
...
[ 34%] Linking CXX executable scsynth
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)@GLIBCXX_3.4.21'
/nix/store/jdix6k80a74a4548m9rzxaq1llm64vs6-libjack2-1.9.10/lib/libjack.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
server/scsynth/CMakeFiles/scsynth.dir/build.make:101: recipe for target 'server/scsynth/scsynth' failed
make[2]: *** [server/scsynth/scsynth] Error 1
CMakeFiles/Makefile2:3331: recipe for target 'server/scsynth/CMakeFiles/scsynth.dir/all' failed
make[1]: *** [server/scsynth/CMakeFiles/scsynth.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/a2hyjaz0nh2vzdnxn5938gkrjw63qc6f-supercollider-3.6.6.drv’ failed with exit code 2
error: build of ‘/nix/store/a2hyjaz0nh2vzdnxn5938gkrjw63qc6f-supercollider-3.6.6.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Closes #15797 and maybe also #16143 

My build is still in progress, but the error reported in #15797 wasn't thrown, so I guess this fixes it.

Please suggest changes to the commits or how to do it in a clean way.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux (Debian)
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This PR is clearly not ready yet, as the commit messages and everything else looks rather ugly, but I'm opening it anyways, so people can argue and test out.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
This does indeed close #16143

**Comment by matthiasbeyer** [comment]
Ping @henrytill , @lethalman , @wkennington

**Comment by matthiasbeyer** [comment]
Another week, nothing happened. Randomly pinging @svanderburg @pSub and @qknight now...

**Comment by matthiasbeyer** [comment]
Rebased on latest master.

**Comment by qknight** [comment]
looks alright, please do this:
rebase -i HEAD~3 and compress your two commits into one. afterwards i will merge.

**Comment by matthiasbeyer** [comment]
Did this. Let me test build again, just to be sure. Will report back in 20 mins.

**Comment by matthiasbeyer** [comment]
Builds fine for me on a debian with nix 1.11.2 installed.

**Comment by magnetophon** [comment]
@qknight could you put this in 16.03 as well?
Tested under ``nixos-version
16.03.1073.73e28bc (Emu)``

**Pull request merged**
