### PR TITLE
mission-center: 0.2.5 -> 0.3.1

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://gitlab.com/mission-center-devs/mission-center/-/releases/v0.3.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GaetanLepage** [comment]
@Kranzes @9p4 I am not able to make it work.
Actually, the compilation succeeds, the main binary seems to work fine, however, the `missioncenter-gatherer` one is crashing.
It silently crashes with exit code 1.

**Comment by 9p4** [comment]
You might wanna replace the proxy Cargo.toml with the gatherer cargo.toml

Also, that behaviour is intended.

```rust
    let args = std::env::args().collect::<Vec<_>>();
    if args.len() < 3 {
        std::process::exit(ExitCode::MissingProgramArgument as i32);
    }
```

**Comment by 9p4** [comment]
https://gitlab.com/mission-center-devs/mission-center/-/tags/v0.3.1

**Comment by GaetanLepage** [comment]
Thanks @9p4 !
It works fine now !

Only problem: it spams the following error:
```
(missioncenter:31136): MissionCenter::SysInfo-CRITICAL **: 23:36:16.938: Gatherer is no longer running: (Unknown, 127). Restarting...
sh: line 1: missioncenter-gatherer: command not found
```
However, the data is properly displayed and updated in the application, so maybe we should not bother...

**Comment by 9p4** [comment]
I think that the best solution would be to wrap the program. This would get rid of the dmidecode trickery too.

**Comment by 9p4** [comment]
yes, and dmidecode too (and remove the sed)

**Comment by GaetanLepage** [comment]
> yes, and dmidecode too (and remove the sed)

All right !
It seems to work now :)

**Comment by 9p4** [comment]
It doesn't look like dmidecode is being wrapped?

**Comment by 9p4** [comment]
Use this instead:

```sh
wrapProgram $out/bin/missioncenter --prefix PATH : $out/bin:${dmidecode}/bin
```

**Comment by GaetanLepage** [comment]
Done :)

> Use this instead:

Done :)

**Comment by GaetanLepage** [comment]
@SuperSandro2000 I guess that we are now ready for a merge :)
Anything that you would like me to change ?

**Review by SuperSandro2000 — APPROVED** [review]

**Review by RaitoBezarius — APPROVED** [review]
Tested.

**Pull request merged**
