### PR TITLE
nodePackages: update all

### PR DESCRIPTION
**Pull request by arcnmx**
###### Description of changes

Ran `./pkgs/development/node-packages/generate.sh` after applying #224677, as it seems to have been broken for a little while.

###### Things done

nothing - this is untested, just figured I'd throw the results somewhere in case a treewide update is wanted

### CODE REVIEW

**Comment by happysalada** [comment]
hey, would you mind rebasing on master and regenerating the update ?
We haven't had an update for a while, so would be happy to merge.

**Comment by arcnmx** [comment]
> We haven't had an update for a while, so would be happy to merge.

it looks like both this and #224677's fixes snuck in as part of #226095 (432cd8cfae04221330411d10f58815da9f7be2a7), so I don't think that's true anymore. I can however run it again, sure.

**Comment by happysalada** [comment]
Of course, this just needs periodical updates, i thought your machine might be powerful enough that this wasnt going to be a problem
Plus its a good way to close one more open PR.

**Comment by arcnmx** [comment]
> Of course, this just needs periodical updates, i thought your machine might be powerful enough that this wasnt going to be a problem Plus its a good way to close one more open PR.

Done! Targeting master because the gap isn't months large anymore, but can rebase to staging if requested.

**Comment by happysalada** [comment]
Thank you!

**Pull request merged**
