### PR TITLE
bison: Update to 3.0.4.

### PR DESCRIPTION
**Pull request by ambrop72**
I need this because cross-compile is fixed in this version.
Test: Nix and all other stuff that ends up depending on it build successfully.

### CODE REVIEW

**Comment by peti** [comment]
That change triggers a re-build of `stdenv`. I suppose that means we'll need some testing beforehand because almost everything depends on this package, and after testing has succeeded, we should merge it by way of `staging` -- not directly to `master`.

**Comment by vcunat** [comment]
It's just bugfix updates, so it shouldn't cause problems (moreover you say you tested some builds), but I agree it should go through staging at least.

**Comment by peti** [comment]
I've added the patch to http://hydra.nixos.org/jobset/nixpkgs/mass-rebuild-updates.

**Comment by ambrop72** [comment]
I've rebuilt my desktop system with this and do not observe any problems.

**Comment by peti** [comment]
The results from Hydra look fine. There are additional failures compared to trunk, but those appear to be unrelated to this patch, i.e. most failures occur because our revision has an invalid URL for `imagemagick`. I believe this patch can go to `staging`. Does anyone disagree?

**Comment by ambrop72** [comment]
It is already in staging, see https://github.com/NixOS/nixpkgs/commit/4b9729f9d9eea4feb751565370a3dd1d4197f88f

**Comment by peti** [comment]
Nice to know ...

**Pull request closed without merging**
