### PR TITLE
clipster: 1.4.1 -> 1.5.0

### PR DESCRIPTION
**Pull request by magnetophon**
###### Motivation for this change

the previous version is broken, when you run the daemon, it says:

```
Traceback (most recent call last):
  File "/nix/store/bzxnrc2lzcd8d8zbfx65vxypijjkhya6-clipster-1.4.1/bin/.clipster-wrapped", line 21, in <module>
    require_version("Gtk", "3.0")
  File "/nix/store/s5a6d9v9m939kw6ih9mq9v2bcnbi7cdv-python3-3.6.4-env/lib/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by magnetophon** [comment]
Any news on this?

**Comment by magnetophon** [comment]
Added an upgrade to this branch.

**Comment by adisbladis** [comment]
Thanks :)

**Comment by magnetophon** [comment]
@adisbladis Thank **you**!
I was starting to think this would never get merged...

**Pull request merged**
