### PR TITLE
haskell.compiler.ghc8{22,41}: Fix abi-depends non-determinism.

### PR DESCRIPTION
**Pull request by shlevy**
See https://github.com/haskell/cabal/issues/4728 for symptoms,
https://phabricator.haskell.org/D4159 for the base of the fix.

### CODE REVIEW

**Comment by shlevy** [comment]
@GrahamcOfBorg build haskell.compilers.ghc822 haskell.compilers.ghc841

**Comment by oxij** [comment]
This fails to build out of hydra because the patch URL is non-deterministic (oh, the irony). Clicking "Download Raw Diff" at https://phabricator.haskell.org/D4159 produces a URL every single time.

**Comment by shlevy** [comment]
@oxij Fantastic :joy: Looking into it.

**Comment by shlevy** [comment]
OK, uploading the patch to tarballs.nixos.org

**Comment by shlevy** [comment]
Fixed in fbe8deb2827759f459815da3f06e0e3353019cb8 and ba717c5471f426b45351f46eb953c81a1d6e5b51

**Comment by oxij** [comment]
Thanks!

**Pull request merged**
