### PR TITLE
simutrans: update, refactor, improve, add paksets

### LINKED ISSUE #6719: simutrans prints errors (it couldn't load wav files)
All I know:

```
could not load wav (Couldn't open /nix/store/fcx78g7di8vcbwpi3a6g7i7979adaaq2-simutrans-112.3/share/simutrans//nix/store/chx28dwb988m1y7hys7vq13qk63wkrcb-simutra)
```

It's not that important to me... but should be reported, I guess.

### PR DESCRIPTION
**Pull request by vcunat**
- update all, and add more paksets
- add config.simutrans.paksets, multiple are possible now
- fix #6719: missing sounds
- move user settings from ~/simutrans to ~/.simutrans
- darwin support is untested (but claimed upstream)

### CODE REVIEW

**Comment by vcunat** [comment]
Comments and testers are welcome, otherwise I'm merging in a few days.

Perhaps interested: @linquize, @matthiasbeyer (but the maintainer seems to have no github account).

**Comment by matthiasbeyer** [comment]
Hi!

I'm really interested in this. Unfortunately I cannot test right now, I'm rather busy atm. Please leave this open until at least next weekend, I think I will be able to test it until then!

**Comment by matthiasbeyer** [comment]
@vcunat Can you maybe tell me a way how to test-install this update without re-installing my world (Step by step if possible)?

**Comment by joachifm** [comment]
@matthiasbeyer, something like the following should work (adapt as needed)
1. Checkout vcunat's branch
2. `nix-build /path/to/nixpkgs/pkgs/top-level/all-packages.nix -A simutrans`
This produces a symlink `results` pointing to the build output. Alternatively, you can `nix-env -iA pkgs.simutrans -f /path/to/nixpkgs` to install simutrans into your user's environemnt.

**Comment by vcunat** [comment]
Yes (nit-picky edit to the command above), or alternatively you can apply the patch atop any commit you like by ``curl https://github.com/NixOS/nixpkgs/pull/7019.patch | git am``, and then use step 2 as above.

**Comment by matthiasbeyer** [comment]
Tested (pak128). Works for me, no errors related to sound output (no errors at all for me, actually). 

If you care, I'd like you to add a 

```
Tested-by: Matthias Beyer <mail@beyermatthias.de>
```

or

```
Signed-off-by: Matthias Beyer <mail@beyermatthias.de>
```

Tag in the commit. Would be nice.

**Pull request closed without merging**
