### PR TITLE
bumping ATS2 version form 0.3.7 to 0.3.9

### PR DESCRIPTION
**Pull request by bbarker**
###### Motivation for this change

Updating ATS2

###### Things done

Minor version bump

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@bbarker are you going to try building it just in case (I know, it does take a lot)? Otherwise I guess I will build it at some point and then merge in case of success.

**Comment by bbarker** [comment]
@7c6f434c I have to plead lack of time and ready knowledge for the moment, but if I get to it I will update here. I'm using nix on ubuntu; I do not see that i have a `nix.conf` anywhere. If there is a recipe for doing this sort of thing using nix.conf, I would like to make the suggestion that the recipe be posted above in the PR template, rather than just a URL to the nix.conf documentation.

**Comment by 7c6f434c** [comment]
@bbarker well, notice there are _separate_ checkboxes for sandbox and for platforms, i.e. it is normal to say «built on Ubuntu without sandbox» (this means ticking «other Linux» without ticking «sandbox»). Then it depends on the package — for ATS2 I will just assume that they don't add new impurities in minor releases.

Often  change can be properly built by asking the Borg bot, but I will not even try for ATS2.

By the way, the standard commit message for such a change is «ats2: 0.3.7 -> 0.3.9» (with extra information, if any, added afterwards, possibly on a new line).

As for recipe for sandboxing — this is different for NixOS (generated config), so the full description could be slightly too large for the template. Do you have `$NIX_CONF_DIR` environment variable? The default location should be `/etc/nix/nix.conf`, and it might need to be created.

**Comment by bbarker** [comment]
Thanks @7c6f434c ,

1. Right, I had only meant to do Ubuntu at the time.
2. I'll try to remember to revise the commit message
3. I had in fact already checked for `NIX_CONF_DIR` and `/etc/nix/nix.conf`; the former wasn't set and the latter didn't exist - so it sounds like I'll need to make one. Regarding the template, I just meant include a link to something to get one up to speed quickly on what they need to do to test pkg changes locally. I hope that makes sense.

**Comment by bbarker** [comment]
Can/should we add a shellhook to set `PATSHOME`?

**Comment by 7c6f434c** [comment]
Should it be a hook or as `makeWrapper`?

Hm, surprisingly, it doesn't seem to recheck the library during the build anymore.  Seems to build and start fine. But making a wrapper might be a good idea.

**Pull request merged**
