### PR TITLE
wine unstable: 1.9.1 -> 1.9.2

### PR DESCRIPTION
**Pull request by a1russell**
For #12687

### CODE REVIEW

**Comment by vcunat** [comment]
This seems to implicitly update `staging.version` as well, but the hash isn't changed.

**Comment by a1russell** [comment]
I can see from the build failure what the hash would be, but how would I normally know? Why is it related?

**Comment by vcunat** [comment]
Perhaps there is a reason to keep the unstable and staging branches in sync. I personally don't really know what these branches should mean.

**Comment by a1russell** [comment]
Yeah, this build takes a long time I guess. Awaiting @bendlas I suppose.

**Comment by bendlas** [comment]
Staging needs to match unstable, because it's maintained as a patchset on top of the regular unstable sources. Thanks for the PR, @a1russell, I'll test build it. If the download/patch phase finishes, it should be alright.

**Comment by bendlas** [comment]
+1 builds and runs for me

**Comment by a1russell** [comment]
Thanks @bendlas! For future reference, how would I know what the hash should be for staging (preferably without waiting for a build failure)?

**Comment by vcunat** [comment]
Thank you both!

**Comment by bendlas** [comment]
@a1russel, I updated wine packaging in #12817 to allow usage of the hash update feature in nix 1.11: `nix-prefetch-url pkgs/misc/emulators/wine/sources.nix -A staging`

**Pull request closed without merging**
