### PR TITLE
binutils: 2.30 -> 2.31.1

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done
Tested transitively by running a few select nixos tests (`postgresql`, `openssh`, `installer`) on `x86_64-linux`.
`aarch64` not yet tested.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @Ericson2314 @ckauhaus

### CODE REVIEW

**Comment by vcunat** [comment]
/cc https://github.com/NixOS/nixpkgs/issues/47128
Some CVEs are apparently fixed, but I haven't looked how severe they are.

**Comment by ckauhaus** [comment]
> Some CVEs are apparently fixed, but I haven't looked how severe they are.

See #47122, #47121, #42882, #41748, #40765, and #38993 for candidates. Needs to be reviewed.

**Comment by NeQuissimus** [comment]
@adisbladis Can you rebase this, please?

**Comment by dtzWill** [comment]
Ping! :)

**Comment by ThomasMader** [comment]
binutils 2.32 is out.

**Comment by NeQuissimus** [comment]
There is a 2.32 branch but I see no such tag or release in https://ftp.gnu.org/gnu/binutils/

**Comment by NeQuissimus** [comment]
53e1db960a0663313e950f4ad45c98a82ad7d2c3

**Pull request closed without merging**
