### PR TITLE
filezilla: 3.46.3 -> 3.48.0

### PR DESCRIPTION
**Pull request by peterhoeg**
Also moves from gtk2 to gtk3.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cole-h — CHANGES_REQUESTED** [review]
This fails to  build for me; `nixpkgs-review pr 86217` gave me the following:

```
builder for '/nix/store/ybar8pvx0pr5kwhcm7s3c6w4j69gf7k0-wxwidgets-3.0.4.drv' failed with exit code 1; last 10 log lines:
  *** your path, or set the GTK_CONFIG environment variable to the
  *** full path to gtk-config.
  configure: error:
  The development files for GTK+ were not found. For GTK+ 2, please
  ensure that pkg-config is in the path and that gtk+-2.0.pc is
  installed. For GTK+ 1.2 please check that gtk-config is in the path,
  and that the version is 1.2.3 or above. Also check that the
  libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
  --libs' are in the LD_LIBRARY_PATH or equivalent.
cannot build derivation '/nix/store/6r4xgnpizsp6l0al3mpkpghigc3h4p4m-filezilla-3.48.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/96mqgazay6srsnzpw453ci2xdq7xsnph-env.drv': 1 dependencies couldn't be built
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/96mqgazay6srsnzpw453ci2xdq7xsnph-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/86217
1 package failed to build:
filezilla

1 package built:
libfilezilla
```

**Comment by peterhoeg** [comment]
Try again - I was just pushing some fixes.

**Comment by peterhoeg** [comment]
It builds and runs here.

**Comment by cole-h** [comment]
It looks like borg has the same problem as I do: https://logs.nix.ci/?attempt_id=38a8d984-199f-4154-a029-44c5c661958e&key=nixos%2Fnixpkgs.86217 (x86_64-linux) and https://logs.nix.ci/?attempt_id=910b5dbf-37bf-4803-9a2e-6db0690beacf&key=nixos%2Fnixpkgs.86217 (aarch64-linux, error is at the bottom here).

**Comment by peterhoeg** [comment]
Ah, so I was building against unstable (where it works) whereas master breaks due to af87f13d0c9 as `meson.build` in the upstream gtk package wasn't updated. Great.

If you want to try it out, you need to rebase against unstable. We need to get gtk3 fixed.

**Comment by peterhoeg** [comment]
And here's the ticket: https://gitlab.gnome.org/GNOME/gtk/-/issues/2632

**Comment by peterhoeg** [comment]
OK, so here we go - now with a patch to gtk3.

Looping in @worldofpeace and @jtojnar who are interested in gtk3 (the tl;dr: gtk3 3.24.18 breaks downstream consumers as it advertises the wrong version).

**Comment by peterhoeg** [comment]
@cole-h if you want to try it out, you can still build this branch. I'll drop my gtk3 patch when gtk3 is fixed.

**Comment by FRidh** [comment]
please rebase onto staging.

**Comment by peterhoeg** [comment]
I dropped the gtk3 change now that gtk3 has been fixed in staging so this should be good to go when the checks pass.

**Pull request merged**
