### PR TITLE
hydrasect: init at unstable-2022-05-30

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

Just trying it out.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sersorrel** [comment]
I don't suppose you plan to revisit this any time soon? it seems like an extremely useful tool to have in nixpkgs.

**Comment by jtojnar** [comment]
I did not merge this because I figured there might be a reason @alyssais did not want to package this yet (the repo is marked wip).

**Comment by alyssais** [comment]
Does it even still work?  It uses channels.nix.gsc.io, which stopped updating mid last year.

**Comment by sersorrel** [comment]
...that would explain why I couldn't get anything useful out of it at the weekend! ah well.

(if you know of any alternative, I'd be grateful; [nixpkgs-staging-bisecter](https://github.com/symphorien/nixpkgs-staging-bisecter) seemed promising, but wanted to examine _way_ too many commits to run in a plausible amount of time.)

**Comment by eclairevoyant** [comment]
Closing this per the comments above. Feel free to reopen if the repo is ever worked on again or if a viable fork shows up.

**Pull request closed without merging**
