### PR TITLE
mautrix-meta: 0.3.2 -> 0.4.0

### PR DESCRIPTION
**Pull request by eyJhb**
## Description of changes
Same changes as https://github.com/NixOS/nixpkgs/pull/342374 , just with correct commit message.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SigmaSquadron — CHANGES_REQUESTED** [review]
As this is a cherry-pick of @Rutherther's commit, I'd rather see their authorship information included in the commit message.

**Comment by eyJhb** [comment]
> As this is a cherry-pick of @Rutherther's commit, I'd rather see their authorship information included in the commit message.

That should be reflected now + contained the original commit message. Is this acceptable? Unsure how I should do it any other way :)

**Comment by Rutherther** [comment]
Thank you, I have other stuff at mind these days so I didnt get to this.

**Review by SigmaSquadron — APPROVED** [review]
The git convention is to use `Authored-by: Name Lastname <email@example.com>`, but this is good enough, as you have the author's acknowledgement.

**Comment by eyJhb** [comment]
> Thank you, I have other stuff at mind these days so I didn't get to this.

No worries. I was unsure if I should open this PR, and how it might be perceived. Feel free to reach out another time :)



> The git convention is to use `Authored-by: Name Lastname <email@example.com>`, but this is good enough, as you have the author's acknowledgement.

I just used the line from the other PR to get name and email, so that it preserves the original committer. I have however changed the prefix to `Authored-by:` now, thanks! I just looked at other commits, and couldn't find much.

**Review by Mindavi — APPROVED** [review]
LGTM but ofborg hasn't built it yet

**Review by Rutherther — APPROVED** [review]

**Comment by eyJhb** [comment]
> LGTM but ofborg hasn't built it yet

It's not going to build them because of olm being marked as insecure, I think.

```
       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘olm-3.2.16’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "olm-3.2.16"
              ];
            }
```

**Pull request merged**
