### PR TITLE
fcron: 3.1.2 -> 3.2.1

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change
Update

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ndowens** [comment]
I removed:
      "--with-username=root"
-      "--with-groupname=root"
Because fcron will no longer build using root as a user

**Comment by Mic92** [comment]
The module fails to start on my system:

```
Mar 02 10:37:31 turingmachine systemd[1]: Starting fcron daemon...
Mar 02 10:37:31 turingmachine fcron-pre-start[9395]: 2017-03-02 10:37:31 ERROR user "fcron" is not in passwd file. Aborting.: Success
Mar 02 10:37:31 turingmachine fcron-pre-start[9395]: 2017-03-02 10:37:31 ERROR fcron child aborted: this does not affect the main fcron daemon, but
Mar 02 10:37:31 turingmachine systemd[1]: Started fcron daemon.

```

**Comment by ndowens** [comment]
Hmm have to look at the module I guess. Because I had to remove root, wonder if hat caused the error

**Comment by Mic92** [comment]
@ndowens the modules needs to add a `fcron` user I guess.

**Comment by ndowens** [comment]
@Mic92 #23413 fixes this

**Comment by Mic92** [comment]
@ndowens not really, Please test if your changes actually work before opening pull requests

**Comment by ndowens** [comment]
@Mic92 I did; I used build-vm; the first time I seen error in the log by journalctl and then I updated the module, by adding fcron user and I seen no error in the journal and it seemed as fcron was running when I looked at ps -a

**Comment by Mic92** [comment]
`/var/spool/fcron` was not owned by the fcron users for instance. So adding new crontabs would not have worked.

**Comment by ndowens** [comment]
Sorry, I thought it worked, I tested it as much I understood it; I never really experienced cron jobs or anything; so I have very limited experience in that area. I just knew that before I added the user, journal had red error for it, and after I added user I didnt see any error; so thought it was fixed

**Pull request closed without merging**
