### PR TITLE
nixos/qemu-vm: use persistent block device names

### PR DESCRIPTION
**Pull request by nikstur**
###### Description of changes

This change removes the bespoke logic around identifying block devices. Instead of trying to find the right device by iterating over `qemu.drives` and guessing the right partition number (e.g. /dev/vda{1,2}), devices are now identified by persistent names provided by udev in /dev/disk/by-*.

Before this change, the root device was formatted on demand in the initrd. However, this makes it impossible to use filesystem identifiers to identify devices. Now, the formatting step is performed before the VM is started. Because some tests, however, rely on this behaviour, a utility function to replace this behaviour in added in /nixos/tests/common/auto-format-root-device.nix.

Devices that contain neither a partition table nor a filesystem are identified by their hardware serial number which is injecetd via QEMU (and is thus persistent and predictable). PCI paths are not a reliably way to identify devices because their availability and numbering depends on the QEMU machine type.

This change makes the module more robust against changes in QEMU and the kernel (non-persistent device naming) and by decoupling abstractions (i.e. rootDevice, bootPartition, and bootLoaderDevice) enables further improvement down the line.

~~For all the tests to succeed, depends on https://github.com/NixOS/nixpkgs/pull/234030.~~

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
This is beautiful. :)

**Comment by RaitoBezarius** [comment]
> Could this solve the issue trying to be solved in #233847 ?

Only partially, here's the issue is related to Nix closures I believe

**Comment by roberth** [comment]
I'm not familiar with this part and I can't do a deep dive now, but the idea seems good and I don't see any problems besides breaking tests that depend on these details, which you've already identified and I think is worth breaking.

**Comment by RaitoBezarius** [comment]
Once we are done with directBoot, I can push your branch to our Hydra jobset.

**Comment by RaitoBezarius** [comment]
Pushing 532ea30c52b9562bf3aab2d04b9ccbbcc9ccb1b9 as a baseline evaluation.

**Comment by RaitoBezarius** [comment]
Hello hello, I bring the failures: https://hydra.nixos.org/eval/1796336#tabs-now-fail — :D

**Comment by nikstur** [comment]
I think I fixed all deterministic failures. @RaitoBezarius can you push another eval?

**Comment by RaitoBezarius** [comment]
Pushed ee60d305d7151a33570e6bfe3e155b51c9b2b699

**Comment by nikstur** [comment]
Looks like only unrelated failures are left: https://hydra.nixos.org/eval/1796429?compare=-184800&full=0

**Comment by RaitoBezarius** [comment]
*nods*

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
Please write a release note for this, maybe introduce a nixpkgs internal change section based on what we have done for 23.05.

**Comment by nikstur** [comment]
> Please write a release note for this

Done

**Review by RaitoBezarius — APPROVED** [review]

**Comment by emilazy** [comment]
This broke `darwin.builder`; `mkfs.ext4` cannot be run on Darwin hosts. I don't see any way to make it work with this approach.

cc @Gabriella439

**Comment by emilazy** [comment]
Ah, after reading the commit more, maybe it's as simple as turning off `useDefaultFilesystems` and using `autoFormat`? I thought the `mkfs.ext4` was being added unconditionally.

**Comment by alyssais** [comment]
Why can't mkfs.ext4 run on Darwin?

**Comment by emilazy** [comment]
Hmm, I wasn't expecting `e2fsprogs` to be portable enough to build on Darwin but apparently it is, except that all the tests fail horribly. Not sure if it's just a matter of skipping the tests on Darwin or if something is more fundamentally broken there.

The actual observed issue is that the VM run script references a Linux `mkfs.ext4` (but Darwin versions of all other tools), I guess because `pkgs` here is for the guest system?

**Comment by emilazy** [comment]
Unfortunately it is not that simple:

```
emily@yuyuko ~> /nix/store/66wby349s40sp4pyzj40s01kzrxhpc7f-e2fsprogs-1.47.0-bin/bin/mkfs.ext4 test.img
mke2fs 1.47.0 (5-Feb-2023)
dyld[13680]: missing symbol called
fish: Job 1, '/nix/store/66wby349s40sp4pyzj40…' terminated by signal SIGABRT (Abort)
```

I don't really have any idea where to start debugging it. Homebrew has a package that apparently works, so it should be possible to fix. I'll try to take a look tomorrow.

**Comment by alyssais** [comment]
[Apparently](https://github.com/NixOS/nixpkgs/pull/229454#issuecomment-1606104550) e2fsprogs built for Darwin until the recent upgrade, so bisecting might be an option?

**Comment by emilazy** [comment]
I tracked it down to https://github.com/NixOS/nixpkgs/issues/238791 which will be fixed with the upcoming Darwin stdenv rework; sorry for not linking back.

**Comment by symphorien** [comment]
This broke `nixos-rebuild build-vm`: https://github.com/NixOS/nixpkgs/issues/292156

**Comment by symphorien** [comment]
My bad, I need to remove the old `nixos.qcow2` image in the current directory. The new code does not handle old images.

**Pull request merged**
