### PR TITLE
[WIP] nextcloud-client: 2.3.2 -> 2.5.0-rc1

### PR DESCRIPTION
**Pull request by caugner**
###### Motivation for this change

This updates the nextcloud-client from `2.3.2` (which was the `owncloud-client` with a nextcloud theme) to `2.5.0` (which is now an independent fork of the `owncloud-client`).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by caugner** [comment]
I'm trying to build it locally, but it's taking *a lot* of time, whereas the Drone CI builds of [nextcloud/desktop](https://github.com/nextcloud/desktop) are [significantly fastler](https://drone.nextcloud.com/nextcloud/desktop/729)).

Maybe we're compiling more than we need to?

**Comment by caugner** [comment]
@GrahamcOfBorg build nextcloud-client

**Comment by alexeymuranov** [comment]
#50463

**Comment by Ma27** [comment]
@caugner @eqyiel would you mind testing my patch (#50463)? It seems to properly migrate the patch and you don't have to recompile anymore when enabling `gnome-keyring` support :)

**Comment by caugner** [comment]
@Ma27 Thanks, I'm closing my PR in favor of yours (#50463) and will try to test your patch in the next couple of days.

**Pull request closed without merging**
