### PR TITLE
(vscodium|vscode): add automated aarch64-linux support

### PR DESCRIPTION
**Pull request by colemickens**
###### Motivation for this change

* add `aarch64-linux` as a supported platform for `vscodium`
* add `aarch64-linux` as a supported platform for `vscode`
* add support for auto-updating both

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zakame** [comment]
Does this supersede #100586?

**Comment by samuela** [comment]
> Does this supersede #100586?

Yes, I believe so. The hashes match.

**Review by samuela — APPROVED** [review]
LGTM

do you have any sense what would be required to do the same for vscode? it would be great to have that done as well!

**Comment by Synthetica9** [comment]
> LGTM
> 
> do you have any sense what would be required to do the same for vscode? it would be great to have that done as well!

Microsoft recently started providing binaries for aarch64, so it should be a similar level of effort.

**Comment by samuela** [comment]
The vscodium update to 1.50.1 is conflicting now that https://github.com/NixOS/nixpkgs/pull/98088 has landed I think.

**Comment by colemickens** [comment]
I'll try to add VSCode aarch64 support and rebase this. Hopefully today.

**Comment by colemickens** [comment]
I attempted the change. Due to where `nixos-unstable` is, it's not perfectly easy for me to test the VSCode addition e2e, but I suspect it works.

**Review by samuela — APPROVED** [review]

**Comment by colemickens** [comment]
```

[colemickens@aarch64:~/nixpkgs]$ nixpkgs-review pr 100641
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/100641/head:refs/nixpkgs-review/1
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 7 (delta 6), reused 7 (delta 6), pack-reused 0
Unpacking objects: 100% (7/7), 1.32 KiB | 338.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
 + 22aae49f10a...8fbc86e9b3f refs/pull/100641/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/colemickens/.cache/nixpkgs-review/pr-100641-1/nixpkgs e80b5cdf7a28f55a600643eeb58696c0727d833d
Preparing worktree (detached HEAD e80b5cdf7a2)
Updating files: 100% (23271/23271), done.
HEAD is now at e80b5cdf7a2 Merge pull request #104618 from sevenfourk/patch-3
$ nix-env -f /home/colemickens/.cache/nixpkgs-review/pr-100641-1/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 8fbc86e9b3ff5e5a08a6ef85c04483b4fa054492
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/colemickens/.cache/nixpkgs-review/pr-100641-1/nixpkgs -qaP --xml --out-path --show-trace --meta
3 packages added:
vscode (init at 1.51.1) vscode-with-extensions (init at 1.51.1) vscodium (init at 1.51.1)

$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/colemickens/.cache/nixpkgs-review/pr-100641-1/build.nix
[4 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/100641
3 packages built:
vscode vscode-with-extensions vscodium

[0.0 MiB DL]
$ nix-shell /home/colemickens/.cache/nixpkgs-review/pr-100641-1/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-100641-1]$ exit
exit
$ git worktree prune

[colemickens@aarch64:~/nixpkgs]$ 
```

**Comment by Mic92** [comment]
superseeded by https://github.com/NixOS/nixpkgs/pull/107052

**Pull request closed without merging**
