### PR TITLE
wlopm: init at 0.1.0

### PR DESCRIPTION
**Pull request by arjan-s**
###### Description of changes
https://sr.ht/~leon_plickat/wlopm/
Simple client implementing zwlr-output-power-management-v1.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by robockie** [comment]
Result of `nixpkgs-review pr 175473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wlopm</li>
  </ul>
</details>

**Comment by ckiee** [comment]
Builds fine, but no tests and I cannot test manually (X11 here) so waiting on someone else to test.

**Comment by RicArch97** [comment]
we can bump this to 0.1.0 now. I've built and tested 0.1.0 on Sway (multi monitor setup), and it seems to work nicely. It's nice to have more generic output power management instead of having to rely on something like `swaymsg` which is obviously not available on other wlroots compositors.

**Comment by arjan-s** [comment]
@ckiee Another tester has commented. Do you think it's ready to merge now?

**Comment by ckiee** [comment]
@ofborg eval

**Comment by ckiee** [comment]
You forgot to update the `sha256` :P

**Comment by arjan-s** [comment]
Result of `nixpkgs-review pr 175473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wlopm</li>
  </ul>
</details>

**Comment by arjan-s** [comment]
Weird... I'm sure it was correct before. Well, I've updated it now and it works perfectly.

**Comment by RicArch97** [comment]
Result of `nixpkgs-review pr 175473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wlopm</li>
  </ul>
</details>

Did a quick test as well; `./results/wlopm/bin/wlopm --toggle DP-2` toggled the power of correct output.

**Pull request merged**
