### PR TITLE
yquake2: migrate from cmake to gnumake

### PR DESCRIPTION
**Pull request by astro**
###### Motivation for this change
See: https://github.com/yquake2/yquake2/commit/fb1a2b0ce7b249cd50990225cc484dc2a9f965de

Fixes finding libcurl.so. Moves yq2.cfg into baseq2/ so that it can be found.

Also includes the update to 8.01 just like #156280.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

closes #156895

### CODE REVIEW

**Review by tadfisher — APPROVED** [review]

**Comment by max-niederman** [comment]
Result of `nixpkgs-review pr 156360` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>yquake2</li>
    <li>yquake2-all-games</li>
    <li>yquake2-ctf</li>
    <li>yquake2-ground-zero</li>
    <li>yquake2-the-reckoning</li>
  </ul>
</details>

**Review by max-niederman — COMMENTED** [review]
Code changes look good to me, but trying to run the binary I get the following error:
```

Yamagi Quake II v8.01
=====================
Client build options:
 + cURL HTTP downloads
 + OpenAL audio
 + Systemwide installation
Platform: Linux
Architecture: x86_64
Byte ordering: little endian

No Ogg Vorbis music tracks have been found, so there will be no music.
Using '/home/max/.yq2/baseq2' for writing.
couldn't exec default.cfg
execing yq2.cfg.
couldn't exec config.cfg
couldn't exec autoexec.cfg
Console initialized.

------- sound initialization -------
Loading library: libopenal.so.1
Sys_LoadLibrary failed: libopenal.so.1: cannot open shared object file: No such file or directory
Loading libopenal.so.1 failed! Disabling OpenAL.
ERROR: OpenAL failed to initialize.
Starting SDL audio callback.
SDL audio driver is "alsa".
SDL audio initialized.
Sound sampling rate: 44100
------------------------------------

-------- vid initialization --------
SDL version is: 2.0.14
SDL video driver is "x11".
SDL display modes:
 - Mode  0: 2560x1440@144
 - Mode  1: 2560x1440@120
 - Mode  2: 2560x1440@100
 - Mode  3: 2560x1440@60
 - Mode  4: 1920x1200@60
 - Mode  5: 1920x1080@120
 - Mode  6: 1920x1080@60
 - Mode  7: 1920x1080@50
 - Mode  8: 1680x1050@60
 - Mode  9: 1600x1200@60
 - Mode 10: 1440x900@60
 - Mode 11: 1280x1440@60
 - Mode 12: 1280x1024@75
 - Mode 13: 1280x1024@60
 - Mode 14: 1280x800@60
 - Mode 15: 1280x720@60
 - Mode 16: 1280x720@50
 - Mode 17: 1024x768@120
 - Mode 18: 1024x768@100
 - Mode 19: 1024x768@75
 - Mode 20: 1024x768@70
 - Mode 21: 1024x768@60
 - Mode 22: 832x624@75
 - Mode 23: 800x600@120
 - Mode 24: 800x600@100
 - Mode 25: 800x600@75
 - Mode 26: 800x600@72
 - Mode 27: 800x600@60
 - Mode 28: 800x600@56
 - Mode 29: 720x576@50
 - Mode 30: 720x480@60
 - Mode 31: 720x400@70
 - Mode 32: 640x480@120
 - Mode 33: 640x480@100
 - Mode 34: 640x480@75
 - Mode 35: 640x480@73
 - Mode 36: 640x480@67
 - Mode 37: 640x480@60
------------------------------------

----- refresher initialization -----
Loading library: ref_gl1.so
Byte ordering: little endian

Refresh: Yamagi Quake II OpenGL Refresher
Client: 8.01

Closing SDL audio device...
SDL audio device shut down.
Cmd_RemoveCommand: force_centerview not added
Cmd_RemoveCommand: +mlook not added
Cmd_RemoveCommand: -mlook not added
Shutting down input.
Cmd_RemoveCommand: modellist not added
Cmd_RemoveCommand: screenshot not added
Cmd_RemoveCommand: imagelist not added
Cmd_RemoveCommand: gl_strings not added
recursive shutdown
Error: Couldn't load pics/colormap.pcx
```
This may not be related to the package though.

**Comment by astro** [comment]
@max-niederman By error, do you mean the following?
```
Loading library: libopenal.so.1
Sys_LoadLibrary failed: libopenal.so.1: cannot open shared object file: No such file or directory
Loading libopenal.so.1 failed! Disabling OpenAL.
ERROR: OpenAL failed to initialize.
```

Does the old version exhibit the same problem?

**Comment by legendofmiracles** [comment]
The current version in nixpkgs also has the same problem, I'm guessing you have to download the level data somewhere...

But the current version doesn't have the libopenal.so.1 error

**Comment by ryantm** [comment]
closes #156895

**Comment by astro** [comment]
@legendofmiracles I've added a remedy for the libopenal.so.1 path.

Could you please obtain a copy of the game data (perhaps you have uploaded a backup to archive.org before disposing of your original disc), place `baseq2/` in the current directory, and retry?

**Review by Lassulus — APPROVED** [review]

**Pull request merged**
