### PR TITLE
nixos/venus: drop module since quite old and gets no updates

### PR DESCRIPTION
**Pull request by Scriptkiddi**
Closes #111440 

###### Motivation for this change
Venus has no maintainer, uses python 2.7 and as far as I can tell gets no updates from its developers. So I would suggest to just drop it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Scriptkiddi** [comment]
https://github.com/NixOS/nixpkgs/pull/111440 can be closed after

**Comment by SuperSandro2000** [comment]
Do we want to add an alias?

**Comment by cole-h** [comment]
Rather than an alias, it would go inside `nixos/modules/rename.nix` and be a `mkRemovedOptionModule`.

**Comment by Scriptkiddi** [comment]
@cole-h added the mkRemovedOption

**Review by cole-h — CHANGES_REQUESTED** [review]
Since we're removing the module and the package, I'd rather those be in two separate commits. First, the package removal, then the module removal. Also, there should be an `aliases.nix` addition for the package that `throw`s.

**Comment by Scriptkiddi** [comment]
@cole-h Done, but in a different order. I figured first removing the module and then removing the package does not break things, since the module depends on the package. 
Happy to change the order though if I missed something

**Review by cole-h — APPROVED** [review]

**Pull request merged**
