### PR TITLE
freebayes: 1.1.0 -> 2017-08-23

### PR DESCRIPTION
**Pull request by disassembler**
###### Motivation for this change
Per @fpletz switching to timestamp. This should be ready to merge.

Related to #28643

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
upstream request: https://github.com/ekg/freebayes/issues/419

**Comment by disassembler** [comment]
No response on getting a release from freebayes. Should we just switch freebayes to a dated commit hash version?

**Comment by ciil** [comment]
+1 for the dated version. Don't think we can expect a bump before the 17.09 release and the current HEAD seems to build alright.

**Comment by fpletz** [comment]
@disassembler Please use a timestamp as version and let's get this merged. :)

**Comment by disassembler** [comment]
whoops, updated derivation and never updated the commit message or PR title @fpletz

**Pull request merged**
