### PR TITLE
backport keybase from unstable

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

I received an email from Keybase that the version 2.6.0 that's currently on 18.09 has reach EOL and will no longer be maintained soon.

Fixes https://github.com/NixOS/nixpkgs/issues/50999

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @carlsverre @np @rvolosatovs @puffnfresh

### CODE REVIEW

**Comment by kalbasit** [comment]
I'm currently testing the PR on my NixOS and Darwin machines and will remove the label `2.status: work-in-progress` once I am satisfied with it.

**Comment by kalbasit** [comment]
I completed the round of tests on Darwin and I'm comfortable with the backport. This PR is now ready for review.

**Review by Mic92 — APPROVED** [review]

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build keybase keybase-gui

**Comment by c0bw3b** [comment]
The `kbfs` package does not need to be updated along with KeyBase client?

**Comment by kalbasit** [comment]
@c0bw3b you're right, I missed that one.

@GrahamcOfBorg build keybase keybase-gui kbfs

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
