### PR TITLE
2019 05 15 patchwork

### PR DESCRIPTION
**Pull request by thedavidmeister**
###### Motivation for this change

same as #59111 with different commit history

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by exarkun** [comment]
This looks approximately correct to me.  In fact, I just packaged patchwork as well and was about to submit a PR when I found this one.  My packaging is almost exactly like this package.  I also tried this out on my nixos and it seems to work.

So please consider this a +1 from me.

**Comment by livnev** [comment]
Tested, it works great for me! 👍

**Comment by octalsrc** [comment]
I have also tested it, with no problems (NixOS).

**Comment by matthiasbeyer** [comment]
Awesome

**Comment by tilpner** [comment]
This is very similar to #53156, in which I requested not to use appimage-run. Unfortunately I didn't see this PR in time.

**Pull request merged**
