### PR TITLE
pipewire: 0.3.43 -> 0.3.45

### PR DESCRIPTION
**Pull request by jansol**
###### Motivation for this change

https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.44
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.45

It is now possible to use pipewire without a session manager (to some extent).
Audible bell from X11 terminals should work with the new X11 module. (seems to be commented out in the default config though)

Lots of bluetooth and pulse-server fixes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Synthetica9** [comment]
@ofborg test installed-tests.pipewire

**Comment by berbiche** [comment]
Pipewire 0.3.45 was just released (in the upstream `next` branch).

**Comment by K900** [comment]
0.3.45 officially out now.

**Comment by jansol** [comment]
Still complains about the reference cycle, still haven't found where it is.

**Comment by K900** [comment]
Probably libcanberra?

**Comment by jansol** [comment]
Well the error specifically claims the cycle is between the `jack` and `lib` outputs but 
```
grep -r $lib $jack
grep -r $jack $lib
```
only mentions that `$jack/lib/libjack.so` and `$jack/lib/libjackserver.so` depend on `$lib/lib/libpipewire.so` but that's only one direction, no mentions of anything the other way around.

I'm not sure why libcanberra would be related? It is only used in the x11 module and has no explicit dependency on pipewire.

**Comment by K900** [comment]
After some staring into `nix build -vvvvvvvv(etc)`, I think I found it. The dependency cycle isn't actually `lib` -> `jack`, it's `lib` -> `out` -> `jack`, where `lib` pulls in `out` because `share/pipewire/minimal.conf` references binaries in `out`, and `out` pulls in `jack` because `pw-jack` adds it to `LD_LIBRARY_PATH`. I'm guessing the easiest way might be to just move the configs into `out` instead of `lib`, because they're only used by the daemon anyway.

**Comment by K900** [comment]
This seems to be enough to untangle everything: https://github.com/K900/nixpkgs/commit/4c4aa837eefadffb96ab6133cfe2d3bbdc2b4ba6

**Comment by jansol** [comment]
Ohhhh it's that thing again. We even have a patch for removing a similar reference from the default config. In both instances the reference doesn't actually do anything since it is commented out.

**Comment by K900** [comment]
Oh yeah, I see the patch now. I guess it's a better idea to update that then.

**Comment by jansol** [comment]
Updated the patch, not sure if it is the most elegant workaround or if something with substituteInPlace could work better.

**Comment by K900** [comment]
I think I like the patch more, `substituteInPlace` can accidentally substitute a useful reference.

**Comment by jansol** [comment]
Uhh why does ofborg try to run passthru tests on darwin when the derivation has `platforms = linux`

**Comment by jansol** [comment]
All peachy on my system now.

**Comment by K900** [comment]
Same.

**Pull request merged**
