### PR TITLE
python37: get it to build again on darwin

### PR DESCRIPTION
**Pull request by domenkozar**
Address https://github.com/NixOS/nixpkgs/issues/56826#issuecomment-481630412 with a workaround.

### CODE REVIEW

**Comment by domenkozar** [comment]
@GrahamcOfBorg build python3

**Comment by domenkozar** [comment]
- noop on linux/aarch
- fixes python build on darwin

**Comment by jhenahan** [comment]
I have an ugly patch in my personal config that lets the existing patch apply cleanly by stripping out the AIX logic that got added in 3.7.3.

https://gist.github.com/jhenahan/da79b184bbe8cfbc330d88a671f04848

**Comment by strager** [comment]
Commit fdbcf5ba36709b108302ae27c63e2c7be4e6bf05 (on master) includes an updated distutils patch. Should we backport that commit (and maybe commit 0bf2d63366cab1b006366831e581d52f5579090d too) to release-19.03?

**Comment by LnL7** [comment]
Did I not backport it?

**Comment by strager** [comment]
@LnL7, my bad, it has been backported into release-19.03!

**Pull request merged**
