### PR TITLE
texlivePackages: init

### PR DESCRIPTION
**Pull request by xworld21**
## Description of changes
Export all TeX Live packages at the top level under `texlivePackages`.

Advantages:
- all fixed output containers will be built by Hydra (including the doc containers), even if they are not included in `texliveFull` or in other schemes
- corollary of the above, all container tarballs will get cached
- packages appear in search
- the fake multi-output hack is still in place, so that `texlive.withPackages` depends directly on the containers, but it is much more restricted and should not cause problems with the builders

Disadvantages:
- ~Hydra ends up building the source containers, which seems wasteful (we could hardcode `texsource` away so that it's present, but not automatically built)~ edit: I removed the source containers from the Hydra build
- TeX Live updates will figure as mass rebuilds
- `tlpdb.nix` increases by ~260k uncompressed to accommodate the package descriptions
- users may be tempted to install the packages directly; I tried to mitigated that with a comment in `meta.longDescription`, and `meta.outputsToInstall = [ ]`

**IMPORTANT**: this should not change the evaluation of existing packages, only introduce new ones.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
LGTM

**Comment by veprbl** [comment]
On #307739, perhaps we could apply  some low`meta.prioriy` as a bandaid?

**Comment by xworld21** [comment]
Ah, so I *did* break something! What's the idiomatic approach to packages with the same name? Surely this is not the first time. We could go back to prefixing the TeX Live package names with `texlive-`, `texliveYYYY-` or `texliveYYYY.rNNNNN-`. It is how e.g. perl, python, etc packages are set up.

> On #307739, perhaps we could apply some low`meta.prioriy` as a bandaid?

Also good, we must find ways to discourage installing those packages directly.

**Comment by xworld21** [comment]
Well, Hydra is building the texdoc containers successfully, but they do not make it to the binary cache, which was the entire point of this PR!

Weirdly enough, packages that are *only* documentation have made it to the binary cache (e.g. amsmath-it). My current theory is that Hydra confuses `texlivePackages.XXX` with `texlivePackages.XXX.tex`, sees that the latter is already in the cache, and does not bother to copy the new outputs.

**Comment by dramforever** [comment]
> Well, Hydra is building the texdoc containers successfully, but they do not make it to the binary cache, which was the entire point of this PR!

As may be expected, this caused a similar symptom described in https://github.com/NixOS/infra/issues/309 again...

@xworld21 Do you have any more specific references I can link to on this problem? I've send the TUNA people a link to this PR comment for now.

**Comment by xworld21** [comment]
> @xworld21 Do you have any more specific references I can link to on this problem? I've send the TUNA people a link to this PR comment for now.

Unfortunately no. The issue must originate from the fact that these derivations have outputs `tex`, `texdoc` which are simply links to separate FODs; to make it harder, I set `passthru.tex`, `passthru.texdoc` to those FODs. It would be good to know if the problem comes from the symlink or from `passthru.tex`, and if creating an additional output first (e.g. `outputs = [ "donotinstall" "tex" "texdoc" ]`) is a plausible workaround.

By the way I noticed recently that there has been a discussion going on about 'package' vs 'derivation' which is very related to the issues I have been having https://github.com/NixOS/nix/issues/6507 – here TeX Live packages are unavoidably made of multiple FODs but should also be treated as single entities.

**Pull request merged**
