### PR TITLE
scons: Switch to Python 3

### PR DESCRIPTION
**Pull request by primeos**
~~This should be merged after #75875 and~~ many build failures have to be resolved first.

### Build logs

Results from `nix-review`: [Gist](https://gist.github.com/primeos/170da8f86041023474736f14ba78d850) (incomplete).

Old logs:
- 2019-12-18: [Gist](https://gist.github.com/primeos/2e2037ef087e5acbcbc69872d99bf259)

### Current status

Done (:heavy_check_mark:):
- bombono: `@symphorien` (https://github.com/NixOS/nixpkgs/pull/75877/commits/a33e63b90142d111b8f0c6134de4e0cc66dfc446)
- fceux: `@scubed2` (https://github.com/NixOS/nixpkgs/pull/78943 ~~no meta.maintainers~~)
- mypaint: `@cillianderoiste @jtojnar` (https://github.com/NixOS/nixpkgs/pull/54677)
- dxx-rebirth: `@peterhoeg`

WIP (:hourglass_flowing_sand:):
- gringo: `@hakuch` (no longer required for `opam` -> probably safe to mark it as broken and remove it if no-one want's to maintain it)
- nsis: `@pedropombeiro` (https://github.com/NixOS/nixpkgs/pull/79083, version 3.05 should support Python 3 but additional changes are required ([debug](https://github.com/kichik/nsis/blob/9ee3275cc54bf3da7f93a3cefd1744f1b58ff91c/SConstruct#L388)))

Unresolved (:negative_squared_cross_mark:):
- [x] btanks: `@viric` (no meta.maintainers)
- [x] globulation2 (glob2): `@7c6f434c`
- [x] gpsd: `@bjornfor @rasendubi`
- [x] jackmix: `@kampfschlaefer`
- [x] lprof: `@marcweber`
- [x] mongodb: `@bluescreen303 @offlinehacker @cstrahan`
- [x] rhvoice: `@berce`
- [x] serf: `@orivej @7c6f434c`
- [x] swift-im: `@orivej`
- [x] tdm: `@cizra`
- [x] vdrift: `@viric`
- [x] xboxdrv: `@fuuzetsu` (no meta)
- [x] ffado: `@cillianderoiste` (`AttributeError: module 'posixpath' has no attribute 'walk'`)
- [x] toluapp: `@vrthra` (`AttributeError: '_io.TextIOWrapper' object has no attribute 'xreadlines'`)

Marked as broken:
- mesos: `@cstrahan @offlinehacker`
- pingus: `@7c6f434c`
- swiften: `@twey`

Unrelated:
- mixxx
- descent12

### Proposed resolution

CC the maintainers of all packages that fail due to Python 3.x and ask them if they could have a look. I.e.:
- Check if a new version is available that supports Python 3
- Check if an upstream PR/issue already exits
  - If there is a stale PR/issue it would probably make sense to add a comment
- Optional: Check if a trivial patch can be written to support Python 3
- Open an upstream issue (https://pythonclock.org/)

TODO: If it's not possible to support Python 3 the packages should override scons to use Python 2.7.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Not sure why I was pinged here?

**Comment by primeos** [comment]
@leahneukirchen Oh, sorry, I probably added you on accident due to the GH auto-completion without noticing it... :o (IMO that feature can be quite a bit annoying as the suggestions only disappear via escape or de-focusing)

**Comment by jonringer** [comment]
the other PR got merged, do you mind rebasing?

**Comment by primeos** [comment]
@jonringer did a rebase but unfortunately this is far from being ready to merge anyway :o

@FRidh @jonringer: What do you think of my [proposal to resolve this](https://github.com/NixOS/nixpkgs/pull/75877#issue-354670615)? Currently the switch to Python 3 causes ~22 builds to fail (there could be more failures in transient dependencies later). IMO it would be best to notify the maintainers of these packages as they're the most familiar with it (e.g. also with testing if it still works correctly with Python 3 at runtime). Do you have any suggestions, changes, etc. regarding this proposal (before I ping the maintainers)?

**Comment by jonringer** [comment]
I'll have to look more into this later, will be pretty busy the next week

**Comment by FRidh** [comment]
@primeos I think that's a good approach. Otherwise, maybe adding a Python2 version of scons as well. E.g. in its `passthru` so it won't show up in the top-level package set.

**Comment by primeos** [comment]
Dear maintainers,
you're cc'd in this issue because at least one of the packages you maintain (s.
list below) will fail to build after switching SCons to Python 3.

If you're still actively using/maintaining your package it would be nice if you
could try to make the build work e.g. by following these steps:
- Check if a new version is available that supports Python 3
- Check if an upstream PR/issue already exits
  - If there is a stale PR/issue it would most likely make sense to add a
    comment (triage)
- Optional: Check if a trivial patch can be written to support Python 3 (e.g. if
  it only fails due to a few "print" statements)
- Open an upstream issue (https://pythonclock.org/)
- Report the results back to this PR
  - Feel free to reply very briefly, but a link to the PR/commit would be nice
  - If e.g. the new version / patch doesn't work with Python 2 anymore you can
    either provide a link to the commit and I'll cherry-pick it into this PR or
    we can already merge a version of SCons that uses Python 3 into Nixpks.

Please also reply here if you're not maintaining your package anymore or if
there isn't an easy solution to make it work with Python 3.

Thanks in advance :heart: :)

### List of packages that don't build with Python 3

**[Link to the build log](https://gist.github.com/primeos/170da8f86041023474736f14ba78d850)**

- btanks: @viric (no `meta.maintainers`)
- bombono: @symphorien
- dxx-rebirth: @peterhoeg
- fceux: @scubed2 (no `meta`)
- globulation2 (glob2): @7c6f434c
- gpsd: @bjornfor @rasendubi
- gringo: @hakuch
- jackmix: @kampfschlaefer
- lprof: @marcweber
- mongodb: @bluescreen303 @offlinehacker @cstrahan
- mypaint: @cillianderoiste @jtojnar
- nsis: @PombeirP
- pingus: @7c6f434c
- rhvoice: @berce
- serf: @orivej @7c6f434c
- swift-im / swiften: @orivej @twey
- tdm: @cizra
- vdrift: @viric
- xboxdrv: @fuuzetsu (no `meta`)
- ffado: @cillianderoiste (`AttributeError: module 'posixpath' has no attribute 'walk'`)
- toluapp: @vrthra (`AttributeError: '_io.TextIOWrapper' object has no attribute 'xreadlines'`)

**Comment by jtojnar** [comment]
Mypaint 2 is scheduled to release soon https://github.com/NixOS/nixpkgs/pull/54677

**Comment by pedropombeiro** [comment]
nsis seems to still be using Python 2: https://github.com/kichik/nsis/blob/master/INSTALL#L8

If this is a blocker, I suggest removing the NSIS expression from all-packages.

**Comment by primeos** [comment]
@pedropombeiro I've had a look and it seems like a patch already exists: https://github.com/kichik/nsis/commit/9ee3275cc54bf3da7f93a3cefd1744f1b58ff91c

By looking at the dates this patch should already be in version 3.05: https://sourceforge.net/projects/nsis/files/NSIS%203/

Could you try updating to version 3.05?

**Comment by scubed2** [comment]
Sent https://github.com/NixOS/nixpkgs/pull/78943 for fceux.

**Comment by pedropombeiro** [comment]
> Could you try updating to version 3.05?

That's what I tried with but I got some weird error.

**Comment by hakuch** [comment]
Hello, and thank you for the clear message and instructions. I'm no longer actively maintaining the `gringo` package: as of version 2, `opam` no longer requires an external solver and so the dependency on `gringo` is not necessary.

**Comment by primeos** [comment]
@pedropombeiro what does "weird error" mean? It didn't build or there where errors at run-time? And what would you recommend to do regarding this PR? (fix the build, mark it as broken, use Python 2 for now, etc.)

@hakuch ok, thanks for the information :)

I'll collect all information in the PR description (current status). Thanks `@everyone` for the updates.

**Comment by pedropombeiro** [comment]
@primeos I've fixed this permissions error:

```
Checking for C library z... (cached) yes
Checking for C++ library cppunit... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [/nix/store/lkcib3zdqd1q4n250ny5wl4vpz5z4zl1-nsis-3.05/share/nsis/Stubs/uninst] /nix/store/lkcib3zdqd1q4n250ny5wl4vpz5z4zl1-nsis-3.05/share/nsis/Stubs/uninst: Permission denied
scons: building terminated because of errors.
builder for '/nix/store/563ygbxywfmh3yxpssd2bl2dmzbrk9mp-nsis-3.05.drv' failed with exit code 2
error: build of '/nix/store/563ygbxywfmh3yxpssd2bl2dmzbrk9mp-nsis-3.05.drv' failed
nix-build default.nix -A nsis  21.48s user 2.16s system 99% cpu 23.652 total
```

However SCons is now complaining that it doesn't know the `install-compiler` even though that's still part of the documentation:

```
Checking for C++ library cppunit... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
scons: *** Do not know how to make File target `install-compiler' (/build/nsis-3.05-src/install-compiler).  Stop.
scons: building terminated because of errors.
```

This is the diff I have:

```patch
diff --git a/pkgs/development/tools/nsis/default.nix b/pkgs/development/tools/nsis/default.nix
index 0539e8de92b..25b8c9257a0 100644
--- a/pkgs/development/tools/nsis/default.nix
+++ b/pkgs/development/tools/nsis/default.nix
@@ -2,23 +2,24 @@
 
 stdenv.mkDerivation rec {
   pname = "nsis";
-  version = "3.04";
+  version = "3.05";
 
   src =
     fetchurl {
       url = "mirror://sourceforge/project/nsis/NSIS%203/${version}/nsis-${version}-src.tar.bz2";
-      sha256 = "1xgllk2mk36ll2509hd31mfq6blgncmdzmwxj3ymrwshdh23d5b0";
+      sha256 = "1sbwx5vzpddharkb7nj4q5z3i5fbg4lan63ng738cw4hmc4v7qdn";
     };
   srcWinDistributable =
     fetchzip {
       url = "mirror://sourceforge/project/nsis/NSIS%203/${version}/nsis-${version}.zip";
-      sha256 = "1g31vz73x4d3cmsw2wfk43qa06bpqp5815fb5qq9vmwms6hym6y2";
+      sha256 = "0i3pzdilyy5g0r2c92pd2jl92ji9f75vv98mndzq8vw03a34yh3q";
     };
 
   postUnpack = ''
     mkdir -p $out/share/nsis
     cp -avr ${srcWinDistributable}/{Contrib,Include,Plugins,Stubs} \
       $out/share/nsis
+    chmod -R u+w $out/share/nsis
   '';
 
   nativeBuildInputs = [ scons ];
@@ -46,6 +47,6 @@ stdenv.mkDerivation rec {
     homepage = https://nsis.sourceforge.io/;
     license = licenses.zlib;
     platforms = platforms.linux;
-    maintainers = with maintainers; [ pombeirp ];
+    maintainers = with maintainers; [ pedropombeiro ];
   };
 }
```

**Comment by symphorien** [comment]
A commit to fix bombono: https://github.com/NixOS/nixpkgs/commit/431094f540f7d6636cfe8e6bfd14d1811d1b2da3

**Comment by jonringer** [comment]
diff LGTM, let me know when you feel comfortable enough for me to test

**Comment by primeos** [comment]
Unfortunately this didn't work as well as I hoped.

My new approach is to switch SCons to Python 3 but continue to build all failing packages with Python 2 for now. Then we can use subsequent PRs to either mark deprecated/unmaintained packages as broken or fix the build with Python 3 if the package is still relevant.

I used the suggestion of @FRidh:
> Otherwise, maybe adding a Python2 version of scons as well. E.g. in its passthru so it won't show up in the top-level package set.

Though my implementation is a bit hacky :o

@jonringer @FRidh: Is the current approach still ok? If so I could run `nixpkgs-review` again to verify this doesn't cause any additional build regressions and run a few manual tests and then it should basically be ready to be merged.

@jonringer if your testing offer still stands that'd be welcome :)

**Review by FRidh — APPROVED** [review]

**Comment by jonringer** [comment]
I don't have enough context to know what ramifications moving to python3 will do. However, I think it's a good idea to move away from python2 anyway.

**Comment by jonringer** [comment]
> I don't have enough context to know what ramifications moving to python3 will do. However, I think it's a good idea to move away from python2 anyway.

I'm okay with this

**Pull request merged**
