### PR TITLE
Opensmtpd dovecot fix backport

### PR DESCRIPTION
**Pull request by Ekleog**
###### Motivation for this change

This is a backport of the 6.0.3p1 update made by @obadz (with the parts dropping support of `tag_char` removed for retrocompatibility), as well as the backport of https://github.com/NixOS/nixpkgs/pull/42139. Should fix interaction with dovecot.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ekleog** [comment]
Thanks!

**Comment by obadz** [comment]
> with the parts dropping support of tag_char removed for retrocompatibility

This isn't backward compatible, it silently ignores the arg. I think we should put in the `throw` as well rather than risk having servers that are silently misconfigured.

**Comment by Ekleog** [comment]
Oh. I checked validity by building it with a defined `tag_char` and verifying it builds, and I must have been too tired to notice it wasn't a patch, and thus would fail silently if it no longer applied… sorry! Thanksfully there hasn't been a bump of 18.03 yet, so it's still time to fix this before anyone gets burned, hopefully.

I've opened #42322 to fix it, by backporting the `Return-Path` fix to 6.0.2p1 instead of trying to repair `tag_char`. Sorry for the mistake!

**Comment by obadz** [comment]
Cheers

**Pull request merged**
