### PR TITLE
Revert "nodejs-10_x: remove"

### PR DESCRIPTION
**Pull request by dotlambda**
Reverts NixOS/nixpkgs#175637 because that broke evaluation when aliases are disabled.

### CODE REVIEW

**Comment by ajs124** [comment]
Interesting… why would this break eval, if trying to evaluate `nodejs-10_x` was already `throw`ing, since it was marked as insecure :thinking:

IMO we should just `sed -i 's/nodejs-10_x/nodejs-12_x/g` for these files :shrug:

**Comment by dotlambda** [comment]
> Interesting… why would this break eval, if trying to evaluate `nodejs-10_x` was already `throw`ing, since it was marked as insecure thinking

Idk, but you can try it out by running `nixpkgs-review rev HEAD`.

> IMO we should just `sed -i 's/nodejs-10_x/nodejs-12_x/g` for these files shrug

Sure, feel free to open a PR.

**Comment by dotlambda** [comment]
For some reason I don't get an error when running `nixpkgs-review rev HEAD --disable-aliases`.

**Comment by marsam** [comment]
Alternative solution https://github.com/NixOS/nixpkgs/pull/177006

**Comment by domenkozar** [comment]
I merged PR that removes references as it goes into the right direction, thanks for a quick response!

**Pull request closed without merging**
