### PR TITLE
darktable: 2.6.3 -> 3.0.0

### PR DESCRIPTION
**Pull request by AmineChikhaoui**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by mrVanDalo — APPROVED** [review]
`nix-review pr 76491` seem to work just fine.

**Comment by markuskowa** [comment]
@GrahamcOfBorg build darktable

**Comment by markuskowa** [comment]
Would you mind removing darwin from the platform flags (or repairing it on darwin)? According to hydra the darwin build is broken since Nov 2018.

**Comment by AmineChikhaoui** [comment]
@markuskowa Ok removed darwin from the list of supported platforms.

**Comment by markuskowa** [comment]
Thanks! Looks good now.

**Pull request merged**
