### PR TITLE
gnomeExtensions: 41 → 42 updates

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Description of changes

- GSConnect v50 works for 42 (v51, v52, v53 are for previous versions of gnome)
- Freon has an unreleased snapshot with 42 support
- Several extensions are updated via script.

Only tested GSConnect and Freon

/cc @jtojnar targeting #160343

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by piegamesde — CHANGES_REQUESTED** [review]
Please use the correct attribute names in the commit messages.

**Comment by fabianhjr** [comment]
Hi @piegamesde, just to confirm, would that be `gnomeExtensions`?

So:

 - `freon` → `gnomeExtensions.freon`
 - `gsconnect` → `gnomeExtensions.gsconnect`
 - `gnome.extensions` → `gnomeExtensions`

**Comment by rhoriguchi** [comment]
Could `freon` not be packaged with [extensionOverrides.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/extensionOverrides.nix) since you only need to apply a patch?

**Comment by fabianhjr** [comment]
> Could `freon` not be packaged with [extensionOverrides.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/extensionOverrides.nix) since you only need to apply a patch?

Unsure, afaik it has some nix specific overrides for the extension to work but I have neven tried to move it back to the extensions.json mechanism.

**Comment by justinas** [comment]
I will try to test freon once I have some time (in the coming days). Not sure I can get any meaningful readings from the sensors in VM, but at least any hard errors should be obvious.

Might also try to re-package using the JSON mechanism.

**Comment by jtojnar** [comment]
Thanks, I have merged as is, the freon issue can be solved separately.

**Pull request merged**
