### PR TITLE
nixos/gnupg: use better trick to update the agent TTY

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Description of changes

Long story short: the SSH agent protocol doesn't support telling from
which tty the request is coming from, so the the pinentry curses prompt
appears on the login tty and messes up the output and may hang.

The current trick to workaround this is informing the gnupg agent every
time you start a shell: this assumes you will run `ssh` in the latest
tty, if you don't the latest tty will be messed up this time.
The ideal solution would be updating the tty exactly when (and where)
you run `ssh`. This is actually possible using a catch-all Match block
in ssh_config and using the `exec` feature that hooks a command to the
current shell.

Source for the new trick: https://unix.stackexchange.com/a/499133/110465

###### Things done

- [x] Tested change (on NixOS 21.05)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fpletz — APPROVED** [review]
Awesome! Gonna test later today and merge if no one beats me to it.

**Comment by SuperSandro2000** [comment]
Any idea how to prevent the following when building on remove builders?

```
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: failed to create temporary file '/root/.gnupg/.#lk0x0000000001848200.magnesium.1064540': No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: can't connect to the gpg-agent: No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: error sending standard options: No agent running
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: failed to create temporary file '/root/.gnupg/.#lk0x0000000000b95200.magnesium.1064542': No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: can't connect to the gpg-agent: No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: error sending standard options: No agent running
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: failed to create temporary file '/root/.gnupg/.#lk0x0000000001c3f200.magnesium.1064545': No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: can't connect to the gpg-agent: No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: error sending standard options: No agent running
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: failed to create temporary file '/root/.gnupg/.#lk0x000000000128c200.magnesium.1064547': No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: can't connect to the gpg-agent: No such file or directory
wezterm-20220903-194523-3bb1ed61-vendor.tar.gz> gpg-connect-agent: error sending standard options: No agent running
```

**Comment by rnhmjoj** [comment]
Are you doing remote builds on a system with `programs.gpg.agent.enable = true`?

**Comment by SuperSandro2000** [comment]
Yes. #189711

**Pull request merged**
