### PR TITLE
convos: 6.26 -> 6.42

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

Bugfixes and fixes for security issues

https://github.com/convos-chat/convos/blob/v6.42/Changes

dependencies:
perlPackages.TextMarkdownHoedown: init at 1.03
perlPackages.MojoliciousPluginSyslog: 0.04 -> 0.05
perlPackages.CryptPassphraseBcrypt: init at 0.001
perlPackages.CryptPassphraseArgon2: 0.002 -> 0.003

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
This is quite a big bump to backport to stable, and it also has the effect of bumping `CryptPassphraseArgon2`

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15, nixos x86_64 & aarch64. `nixosTests.convos` passes on x86_64

**Comment by risicle** [comment]
https://github.com/convos-chat/convos/commit/a2d26518330a23a5a663116f3d5c9e1cc426492d appears to be the fix commit

**Comment by mohe2015** [comment]
Result of `nixpkgs-review pr 150538` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>convos</li>
    <li>hydra-unstable</li>
    <li>perl532Packages.CryptPassphraseArgon2</li>
    <li>perl532Packages.CryptPassphraseBcrypt</li>
    <li>perl534Packages.CryptPassphraseArgon2</li>
    <li>perl534Packages.CryptPassphraseBcrypt</li>
  </ul>
</details>

**Comment by mohe2015** [comment]
`convos daemon` - the web application seemed to work and also connected to some irc

**Comment by stigtsp** [comment]
> This is quite a big bump to backport to stable

convos 6.26 -> 6.40 contains mostly bugfixes and shouldn't cause any regressions and should be within the criteria for backporting. Meanwhile, 6.42 is out with additional bugfixes so I'll update this PR to 6.42

> and it also has the effect of bumping `CryptPassphraseArgon2`

Crypt::Passphrase::Argon2 0.002 -> 0.003 appears to contain only documentation changes.

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.TextMarkdownHoedown perlPackages.MojoliciousPluginSyslog perlPackages.CryptPassphraseBcrypt perlPackages.CryptPassphraseArgon2

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.TextMarkdownHoedown perlPackages.MojoliciousPluginSyslog perlPackages.CryptPassphraseBcrypt perlPackages.CryptPassphraseArgon

**Comment by stigtsp** [comment]
@GrahamcOfBorg build hydra-unstable

**Pull request merged**
