### PR TITLE
nextcloud: add option to configure bulk upload

### PR DESCRIPTION
**Pull request by skvl**
###### Description of changes

The new option allows to enable bulk upload if needed. See https://github.com/nextcloud/desktop/issues/5094 before enabling it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Is it possible to enable this via `extraOptions` too?
```
services.nextcloud = {
  extraOptions = {
    bulkUpload.enable = true;
  };
};
```

I would be really happy to keep the Nextcloud module slim and only add options which are reused in the module somewhere else. There are some other options in the Nextcloud module too which could be handled by `extraOptions` now and might not be required anymore ...

**Comment by skvl** [comment]
> Is it possible to enable this via `extraOptions` too?
> 
> ```
> services.nextcloud = {
>   extraOptions = {
>     bulkUpload.enable = true;
>   };
> };
> ```
> 
> I would be really happy to keep the Nextcloud module slim and only add options which are reused in the module somewhere else. There are some other options in the Nextcloud module too which could be handled by `extraOptions` now and might not be required anymore ...

I don't yet know. I'm newbie in NixOS and Nixpkgs.

With this patch I fixed my client<>server problem

**Comment by onny** [comment]
And does it work adding this option in extraOptions too? If yes we could skip this PR if its okay for you :)

**Comment by skvl** [comment]
> And does it work adding this option in extraOptions too? If yes we could skip this PR if its okay for you :)

No. This doesn't work

**Comment by SuperSandro2000** [comment]
I am going to close this since the feature seems not to be stable yet and for testing it can be enabled via extraOptions.

**Comment by LAK132** [comment]
> This doesn't work: nothing has appeared in `/var/lib/nextcloud/config/override.config.php`

It appeared in `config/config.php` for me

**Pull request closed without merging**
