### PR TITLE
Revert (parts of) "Treewide cleanup meta description" 

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

This reverts https://github.com/NixOS/nixpkgs/pull/317959

That PR does not clearly indicate that it adds a new rule, and does not put the modifications to the document in a separate commit, thus avoiding the discussion of adding a new rule. Such rules obviously deserve more discussion.

> Add recommendation to avoid meta.description to start with the definite or an indefinite article to pkgs/README.md
Remove the definite or an indefinite article from the beginning of meta.description

Personally, I don't think this modification makes any sense, and often makes reading descriptions less intuitive. Some people also noted that this is not grammatically appropriate, or is unnecessarily too strict.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Please includes reasons for reverts in commit messages.

**Comment by marcusramberg** [comment]
I think the more succinct descriptions are an improvement for the wast majority of cases, so I'm opposed to this revert.

**Comment by eclairevoyant** [comment]
I agree that sneaking in a rule is not ideal, but indefinite articles are quite redundant IMO. Not sure why it'd be "grammatically incorrect" either, as it's not a full sentence, merely a fragment.

**Comment by Aleksanaa** [comment]
> In any case, the only thing sillier than adding this rule is reverting it IMO

It doesn't seem to matter whether it's grammatically correct or not, but I'm curious, does this mean we're on a good start for more of these modifications that don't need to be discussed? Have we given voice to those who want to speak?

**Comment by eclairevoyant** [comment]
It's a low-stakes change, not like (say) enforcing a new rule about maintainership or such. Talking about "giving voice to those who want to speak" sounds quite dramatic for this specific scenario.

**Comment by Aleksanaa** [comment]
> It's a low-stakes change, not like (say) enforcing a new rule about maintainership or such.

Some reviewers have previously requested that articles be added. Some distributions enforce the article and some don't. You have also found that after making such changes, it becomes more difficult to undo.

> Talking about "giving voice to those who want to speak" sounds quite dramatic for this specific scenario.
Also it's up to reviewers to catch these changes as well, if it's that important.

This is merged faster than most "add new package" PRs I've seen. And it merges even faster than parts of my simple upgrades by-hand. Such speed itself is inappropriate. This means that, before the merge, its visibility did not match the scope of its changes.

**Comment by ocfox** [comment]
> This is merged faster than most "add new package" PRs I've seen. And it merges even faster than parts of my simple upgrades by-hand.

Agree that but it is not the reason to revert. #317959 is a good change for me, if a revert is needed we could discuss under that.

**Comment by adamcstephens** [comment]
Without a linter these rules will only be weakly enforced, even if widely desirable. Inevitably they will be violated as nixpkgs progresses.

**Comment by K900** [comment]
Can we not have a policy conversation on a PR that has more than a screen's height of reviewers?

**Comment by eclairevoyant** [comment]
> Some reviewers have previously requested that articles be added. Some distributions enforce the article and some don't.

And I've been nitted in both directions; that's the strongest indicator to just add a rule to stop the nits. At least this direction has precedent from other distros and has some logic.

> This is merged faster than most "add new package" PRs I've seen.

I can't argue with that, I guess, since some package inits  (even those in good shape) have never been merged, so merging at all is faster than never. I can only assume that since 5 different committers commented (which is also quite rare, usually everyone ignores treewides for weeks) and dozens of reviewers tagged and no one raised an objection, it was considered uncontroversial.

**Comment by Aleksanaa** [comment]
I don't think this PR will lead to any meaningful conclusion.

**Pull request closed without merging**
