### PR TITLE
openssh*: 9.4p1 -> 9.5p1

### PR DESCRIPTION
**Pull request by dasJ**
## Description of changes

Changelog: https://www.openssh.com/releasenotes.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wahjava — APPROVED** [review]
Thank you!

**Review by 6t8k — APPROVED** [review]
On `x86_64-linux`, I manually tested basic functionality of all resulting binary files of `openssh`, `openssh_hpn` and `openssh_gssapi` on this branch with a positive result. 

Did not specifically test the unique features of `openssh_hpn` or `openssh_gssapi`.

`nix-build -A nixosTests.openssh` succeeds.

**Comment by K900** [comment]
The test seems to be flaky on Hydra recently, maybe related?

```
server_localhost_only: output: 
Test "localhost-only" failed with error: "command `ss -nlt | grep '127.0.0.1:22'` failed (exit code 1)"
```
cleanup

**Comment by cdepillabout** [comment]
When updating from nixos-23.05 to nixos-23.11, I found that commit 2d99e37a9b78efe8aefdc77d2c7e6cb50896e70a (bumping openssh from 9.4p1 to 9.5p1) causes _significant_ slowness with X11 forwarding over SSH.

With 9.4p1, X11 forwarding over SSH seemed mostly instant (as if I was just using an X11 application on my local machine), while with 9.5p1, X11 forwarding is unbearably slow (as if I was using an X11 forwarding to a machine on the other side of the world, over a very slow link).  When testing this, I was SSH'ing to the same machine on my local network.

I need to check the release notes for 9.5p1, and possibly the commit history to see if anything pops out.  But I wanted to leave a comment in case anyone else noticed this and was experiencing a similar slowness.

**Pull request merged**
