### PR TITLE
swig1, swig2: remove

### PR DESCRIPTION
**Pull request by bcdarwin**
swig2: remove at 2.0.12
swig1: remove at 1.3.40
python312Packages.lttng: swig2 -> swig4
gpgme: apply nixfmt
gpgme: swig2 -> swig4
babeltrace: swig2 -> swig4
soapysdr: apply nixfmt
soapysdr: swig2 -> swig3

## Description of changes

Remove swig version 1, which has no uses in tree and had its last release in 2009, and swig version 2, moving all uses of swig2 to swig4 except for soapysdr, whose optional python build is broken, so conservatively move to swig3 for now.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by bjornfor — COMMENTED** [review]
LGTM, but would like to see the build results: how many/which packages break from this change?

**Comment by bcdarwin** [comment]
> LGTM, but would like to see the build results: how many/which packages break from this change?

on x64-linux (no new failures according to Hydra):

```
5 packages marked as broken and skipped:

netbox_3_6 python311Packages.subunit2sql python311Packages.subunit2sql.dist syncall syncall.dist

6 packages failed to build:

devpi-client devpi-client.dist python311Packages.jenkins-job-builder python311Packages.jenkins-job-builder.dist python312Packages.soapysdr python312Packages.soapysdr-with-plugins

187 packages built:

alot alot.dist barbicanclient barbicanclient.dist breezy breezy.dist cabal2nix caerbannog calendar-cli calendar-cli.dist dvc dvc-with-remotes dvc-with-remotes.dist dvc.dist errands errbot errbot.dist flatpak-builder flatpak-builder.doc flatpak-builder.installedTests flatpak-builder.man glanceclient glanceclient.dist gnome-keysign gnome-keysign.dist gtg haskellPackages.cabal2nix-unstable heatclient heatclient.dist home-assistant-component-tests.caldav hydra_unstable ironicclient ironicclient.dist klaus klaus.dist kolla kolla.dist luarocks-packages-updater manilaclient manilaclient.dist netbox nix-prefetch-bzr nix-prefetch-scripts nix-update-source nix-update-source.dist openstackclient openstackclient-full openstackclient-full.dist openstackclient.dist poetry poetry.dist poetryPlugins.poetry-audit-plugin poetryPlugins.poetry-audit-plugin.dist poetryPlugins.poetry-plugin-up poetryPlugins.poetry-plugin-up.dist python311Packages.babeltrace python311Packages.breezy python311Packages.breezy.dist python311Packages.caldav python311Packages.caldav.dist python311Packages.check-manifest python311Packages.check-manifest.dist python311Packages.cliff python311Packages.cliff.dist python311Packages.debtcollector python311Packages.debtcollector.dist python311Packages.dulwich python311Packages.dulwich.dist python311Packages.dvc python311Packages.dvc-gdrive python311Packages.dvc-gdrive.dist python311Packages.dvc-hdfs python311Packages.dvc-hdfs.dist python311Packages.dvc-studio-client python311Packages.dvc-studio-client.dist python311Packages.dvc.dist python311Packages.dvclive python311Packages.dvclive.dist python311Packages.gpgme  python311Packages.gto python311Packages.gto.dist python311Packages.hacking python311Packages.hacking.dist python311Packages.hg-git python311Packages.hg-git.dist python311Packages.keystoneauth1 python311Packages.keystoneauth1.dist python311Packages.klaus python311Packages.klaus.dist python311Packages.lttng python311Packages.multiscale-spatial-image python311Packages.multiscale-spatial-image.dist python311Packages.netbox-reorder-rack python311Packages.netbox-reorder-rack.dist python311Packages.openstackdocstheme python311Packages.openstackdocstheme.dist python311Packages.openstacksdk python311Packages.openstacksdk.dist python311Packages.openstacksdk.man python311Packages.osc-lib python311Packages.osc-lib.dist python311Packages.oslo-concurrency python311Packages.oslo-concurrency.dist python311Packages.oslo-config python311Packages.oslo-config.dist python311Packages.oslo-context python311Packages.oslo-context.dist python311Packages.oslo-db python311Packages.oslo-db.dist python311Packages.oslo-i18n python311Packages.oslo-i18n.dist python311Packages.oslo-log python311Packages.oslo-log.dist python311Packages.oslo-serialization python311Packages.oslo-serialization.dist python311Packages.oslo-utils python311Packages.oslo-utils.dist python311Packages.python-cinderclient python311Packages.python-cinderclient.dist python311Packages.python-designateclient python311Packages.python-designateclient.dist python311Packages.python-jenkins python311Packages.python-jenkins.dist python311Packages.python-keystoneclient python311Packages.python-keystoneclient.dist python311Packages.python-novaclient python311Packages.python-novaclient.dist swiftclient swiftclient.dist python311Packages.scmrepo python311Packages.scmrepo.dist python311Packages.simplekv python311Packages.simplekv.dist python311Packages.soapysdr python311Packages.soapysdr-with-plugins python311Packages.stestr python311Packages.stestr.dist python311Packages.tempest python311Packages.tempest.dist python311Packages.xarray-datatree python311Packages.xarray-datatree.dist python312Packages.babeltrace python312Packages.caldav python312Packages.caldav.dist python312Packages.check-manifest python312Packages.check-manifest.dist python312Packages.dulwich python312Packages.dulwich.dist python312Packages.dvc-gdrive python312Packages.dvc-gdrive.dist python312Packages.dvc-hdfs python312Packages.dvc-hdfs.dist python312Packages.dvc-studio-client python312Packages.dvc-studio-client.dist python312Packages.dvclive python312Packages.dvclive.dist python312Packages.gpgme  python312Packages.gto python312Packages.gto.dist python312Packages.hg-git python312Packages.hg-git.dist python312Packages.lttng python312Packages.multiscale-spatial-image python312Packages.multiscale-spatial-image.dist python312Packages.netbox-reorder-rack python312Packages.netbox-reorder-rack.dist python312Packages.scmrepo python312Packages.scmrepo.dist python312Packages.simplekv python312Packages.simplekv.dist python312Packages.xarray-datatree python312Packages.xarray-datatree.dist reno reno.dist sherlock sherlock.dist silver-platter silver-platter.dist vcstool vcstool.dist xandikos xandikos.dist zeyple
```

**Review by bjornfor — APPROVED** [review]
Patches look good and according to https://github.com/NixOS/nixpkgs/pull/336845#issuecomment-2307819452 there are no new build errors.

**Comment by wentasah** [comment]
Result of `nixpkgs-review pr 336845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>netbox_3_6</li>
    <li>python311Packages.subunit2sql</li>
    <li>python311Packages.subunit2sql.dist</li>
    <li>syncall</li>
    <li>syncall.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>devpi-client</li>
    <li>devpi-client.dist</li>
    <li>python311Packages.jenkins-job-builder</li>
    <li>python311Packages.jenkins-job-builder.dist</li>
    <li>python312Packages.soapysdr</li>
    <li>python312Packages.soapysdr-with-plugins</li>
  </ul>
</details>
<details>
  <summary>187 packages built:</summary>
  <ul>
    <li>alot</li>
    <li>alot.dist</li>
    <li>barbicanclient (python311Packages.python-barbicanclient)</li>
    <li>barbicanclient.dist (python311Packages.python-barbicanclient.dist)</li>
    <li>breezy (python312Packages.breezy)</li>
    <li>breezy.dist (python312Packages.breezy.dist)</li>
    <li>cabal2nix</li>
    <li>caerbannog</li>
    <li>calendar-cli</li>
    <li>calendar-cli.dist</li>
    <li>dvc (python312Packages.dvc)</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>dvc.dist (python312Packages.dvc.dist)</li>
    <li>errands</li>
    <li>errbot</li>
    <li>errbot.dist</li>
    <li>flatpak-builder</li>
    <li>flatpak-builder.doc</li>
    <li>flatpak-builder.installedTests</li>
    <li>flatpak-builder.man</li>
    <li>glanceclient (python311Packages.python-glanceclient)</li>
    <li>glanceclient.dist (python311Packages.python-glanceclient.dist)</li>
    <li>gnome-keysign</li>
    <li>gnome-keysign.dist</li>
    <li>gtg</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>heatclient (python311Packages.python-heatclient)</li>
    <li>heatclient.dist (python311Packages.python-heatclient.dist)</li>
    <li>home-assistant-component-tests.caldav</li>
    <li>hydra_unstable</li>
    <li>ironicclient (python311Packages.python-ironicclient)</li>
    <li>ironicclient.dist (python311Packages.python-ironicclient.dist)</li>
    <li>klaus (python312Packages.klaus)</li>
    <li>klaus.dist (python312Packages.klaus.dist)</li>
    <li>kolla</li>
    <li>kolla.dist</li>
    <li>luarocks-packages-updater</li>
    <li>manilaclient (python311Packages.python-manilaclient)</li>
    <li>manilaclient.dist (python311Packages.python-manilaclient.dist)</li>
    <li>netbox (netbox_3_7)</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>openstackclient (python311Packages.python-openstackclient)</li>
    <li>openstackclient-full</li>
    <li>openstackclient-full.dist</li>
    <li>openstackclient.dist (python311Packages.python-openstackclient.dist)</li>
    <li>poetry</li>
    <li>poetry.dist</li>
    <li>poetryPlugins.poetry-audit-plugin</li>
    <li>poetryPlugins.poetry-audit-plugin.dist</li>
    <li>poetryPlugins.poetry-plugin-up</li>
    <li>poetryPlugins.poetry-plugin-up.dist</li>
    <li>python311Packages.babeltrace</li>
    <li>python311Packages.breezy</li>
    <li>python311Packages.breezy.dist</li>
    <li>python311Packages.caldav</li>
    <li>python311Packages.caldav.dist</li>
    <li>python311Packages.check-manifest</li>
    <li>python311Packages.check-manifest.dist</li>
    <li>python311Packages.cliff</li>
    <li>python311Packages.cliff.dist</li>
    <li>python311Packages.debtcollector</li>
    <li>python311Packages.debtcollector.dist</li>
    <li>python311Packages.dulwich</li>
    <li>python311Packages.dulwich.dist</li>
    <li>python311Packages.dvc</li>
    <li>python311Packages.dvc-gdrive</li>
    <li>python311Packages.dvc-gdrive.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.dvc-studio-client</li>
    <li>python311Packages.dvc-studio-client.dist</li>
    <li>python311Packages.dvc.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
    <li>python311Packages.gpgme</li>
    <li>python311Packages.gpgme.dev</li>
    <li>python311Packages.gpgme.info</li>
    <li>python311Packages.gto</li>
    <li>python311Packages.gto.dist</li>
    <li>python311Packages.hacking</li>
    <li>python311Packages.hacking.dist</li>
    <li>python311Packages.hg-git</li>
    <li>python311Packages.hg-git.dist</li>
    <li>python311Packages.keystoneauth1</li>
    <li>python311Packages.keystoneauth1.dist</li>
    <li>python311Packages.klaus</li>
    <li>python311Packages.klaus.dist</li>
    <li>python311Packages.lttng</li>
    <li>python311Packages.multiscale-spatial-image</li>
    <li>python311Packages.multiscale-spatial-image.dist</li>
    <li>python311Packages.netbox-reorder-rack</li>
    <li>python311Packages.netbox-reorder-rack.dist</li>
    <li>python311Packages.openstackdocstheme</li>
    <li>python311Packages.openstackdocstheme.dist</li>
    <li>python311Packages.openstacksdk</li>
    <li>python311Packages.openstacksdk.dist</li>
    <li>python311Packages.openstacksdk.man</li>
    <li>python311Packages.osc-lib</li>
    <li>python311Packages.osc-lib.dist</li>
    <li>python311Packages.oslo-concurrency</li>
    <li>python311Packages.oslo-concurrency.dist</li>
    <li>python311Packages.oslo-config</li>
    <li>python311Packages.oslo-config.dist</li>
    <li>python311Packages.oslo-context</li>
    <li>python311Packages.oslo-context.dist</li>
    <li>python311Packages.oslo-db</li>
    <li>python311Packages.oslo-db.dist</li>
    <li>python311Packages.oslo-i18n</li>
    <li>python311Packages.oslo-i18n.dist</li>
    <li>python311Packages.oslo-log</li>
    <li>python311Packages.oslo-log.dist</li>
    <li>python311Packages.oslo-serialization</li>
    <li>python311Packages.oslo-serialization.dist</li>
    <li>python311Packages.oslo-utils</li>
    <li>python311Packages.oslo-utils.dist</li>
    <li>python311Packages.python-cinderclient</li>
    <li>python311Packages.python-cinderclient.dist</li>
    <li>python311Packages.python-designateclient</li>
    <li>python311Packages.python-designateclient.dist</li>
    <li>python311Packages.python-jenkins</li>
    <li>python311Packages.python-jenkins.dist</li>
    <li>python311Packages.python-keystoneclient</li>
    <li>python311Packages.python-keystoneclient.dist</li>
    <li>python311Packages.python-novaclient</li>
    <li>python311Packages.python-novaclient.dist</li>
    <li>swiftclient (python311Packages.python-swiftclient)</li>
    <li>swiftclient.dist (python311Packages.python-swiftclient.dist)</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python311Packages.simplekv</li>
    <li>python311Packages.simplekv.dist</li>
    <li>python311Packages.soapysdr</li>
    <li>python311Packages.soapysdr-with-plugins</li>
    <li>python311Packages.stestr</li>
    <li>python311Packages.stestr.dist</li>
    <li>python311Packages.tempest</li>
    <li>python311Packages.tempest.dist</li>
    <li>python311Packages.xarray-datatree</li>
    <li>python311Packages.xarray-datatree.dist</li>
    <li>python312Packages.babeltrace</li>
    <li>python312Packages.caldav</li>
    <li>python312Packages.caldav.dist</li>
    <li>python312Packages.check-manifest</li>
    <li>python312Packages.check-manifest.dist</li>
    <li>python312Packages.dulwich</li>
    <li>python312Packages.dulwich.dist</li>
    <li>python312Packages.dvc-gdrive</li>
    <li>python312Packages.dvc-gdrive.dist</li>
    <li>python312Packages.dvc-hdfs</li>
    <li>python312Packages.dvc-hdfs.dist</li>
    <li>python312Packages.dvc-studio-client</li>
    <li>python312Packages.dvc-studio-client.dist</li>
    <li>python312Packages.dvclive</li>
    <li>python312Packages.dvclive.dist</li>
    <li>python312Packages.gpgme</li>
    <li>python312Packages.gpgme.dev</li>
    <li>python312Packages.gpgme.info</li>
    <li>python312Packages.gto</li>
    <li>python312Packages.gto.dist</li>
    <li>python312Packages.hg-git</li>
    <li>python312Packages.hg-git.dist</li>
    <li>python312Packages.lttng</li>
    <li>python312Packages.multiscale-spatial-image</li>
    <li>python312Packages.multiscale-spatial-image.dist</li>
    <li>python312Packages.netbox-reorder-rack</li>
    <li>python312Packages.netbox-reorder-rack.dist</li>
    <li>python312Packages.scmrepo</li>
    <li>python312Packages.scmrepo.dist</li>
    <li>python312Packages.simplekv</li>
    <li>python312Packages.simplekv.dist</li>
    <li>python312Packages.xarray-datatree</li>
    <li>python312Packages.xarray-datatree.dist</li>
    <li>reno</li>
    <li>reno.dist</li>
    <li>sherlock</li>
    <li>sherlock.dist</li>
    <li>silver-platter</li>
    <li>silver-platter.dist</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>xandikos</li>
    <li>xandikos.dist</li>
    <li>zeyple</li>
  </ul>
</details>

**Review by wentasah — APPROVED** [review]
LGTM.

I was confused by build failure of `soapysdr`, but it turns out that only Python 3.12 build fails. It fails even without this PR due to removal of distutils. `soapysdr` for Python 3.11 builds fine.

**Comment by emilazy** [comment]
Thank you! Do `swig3` next! :)

**Pull request merged**
