### PR TITLE
[20.03] ghc: add new version 8.8.4

### PR DESCRIPTION
**Pull request by ggreif**
(cherry picked from commit dd6ce8c8799130f388cac697eb0e1d7dffa63d3f)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build haskell.compiler.ghc884

**Comment by ggreif** [comment]
@peti which one did you mean is needing a backport?
- 6d54b2f918c ghc 8.8.4, 8.10.1: disable profiled builds on aarch64 to avoid 2GB output limit
- 8ffedd83693 haskellPackages: bump default compiler to ghc-8.8.4

**Comment by peti** [comment]
> * [6d54b2f](https://github.com/NixOS/nixpkgs/commit/6d54b2f918cf583ac7d909d6bf5ccd63d5be44b5) ghc 8.8.4, 8.10.1: disable profiled builds on aarch64 to avoid 2GB output limit

Back-porting this commit feels like a good idea. I'm not sure how to test whether the change actually works for aarch64, but Hydra might do that verification for us for free, maybe? I suppose @vcunat might be able to advice.

> * [8ffedd8](https://github.com/NixOS/nixpkgs/commit/8ffedd83693d6effd1c271f3ad17c38f7dcecf42) haskellPackages: bump default compiler to ghc-8.8.4

This commit should NOT be back-ported. Users of a stable release branch probably don't want their default compiler to be updated.

**Comment by ggreif** [comment]
@peti what about switching the default package set from `8.8.3` to `8.8.4`?

**Review by peti — APPROVED** [review]
:+1:

**Comment by vcunat** [comment]
The [community aarch64 box](https://github.com/nix-community/aarch64-build-box) would probably be well usable for this.  I can run builds there, in case you don't have an account.  Actually the borg also runs them there IIRC.

**Comment by vcunat** [comment]
Follows on: https://github.com/NixOS/nixpkgs/pull/94372

**Pull request merged**
