### PR TITLE
freecad: 0.20.2 -> 0.21.0

### PR DESCRIPTION
**Pull request by pinpox**
Fixes #249109

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 250956` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>freecad</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
```
│       last 10 log lines:                                                                                                                                    │
│       >   Build step for fmt failed: 1                                                                                                                      │
│       > Call Stack (most recent call first):                                                                                                                │
│       >   /nix/store/p4yxdhbwfijv7yfakvs6xxsmxwgqxy7g-cmake-3.26.4/share/cmake-3.26/Modules/FetchContent.cmake:1762:EVAL:2 (__FetchContent_directPopulate)  │
│       >   /nix/store/p4yxdhbwfijv7yfakvs6xxsmxwgqxy7g-cmake-3.26.4/share/cmake-3.26/Modules/FetchContent.cmake:1762 (cmake_language)                        │
│       >   /nix/store/p4yxdhbwfijv7yfakvs6xxsmxwgqxy7g-cmake-3.26.4/share/cmake-3.26/Modules/FetchContent.cmake:1976 (FetchContent_Populate)                 │
│       >   cMake/FreeCAD_Helpers/SetupLibFmt.cmake:40 (FetchContent_MakeAvailable)                                                                           │
│       >   CMakeLists.txt:52 (SetupLibFmt)                                                                                                                   │
│       >                                                                                                                                                     │
│       >                                                                                                                                                     │
│       > -- Configuring incomplete, errors occurred!     
```

**Comment by pinpox** [comment]
Comit above should fix the build, there was a dependency missing. My computer is not powerful enough to run the full build of freecad, please let the CI rebuild it.

**Comment by luzpaz** [comment]
@pinpox thanks so much. Do you mind also changing another small issue: 

https://github.com/NixOS/nixpkgs/blob/9c8d4dea55f430fbbceef2edb578808fdc37b269/pkgs/applications/graphics/freecad/default.nix#L151

Should be `https://www.freecad.org`

**Comment by pinpox** [comment]
> Should be `https://www.freecad.org`

done.

**Comment by nagy** [comment]
@pinpox can you squash the two new commits?

**Comment by flosse** [comment]
@pinpox Thanks for the update! :pray: 

BTW:
Works perfect for me (NixOS 23.05. @ x86_64) :smile:

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
@pinpox squash the commits

**Comment by luzpaz** [comment]
JFYI, https://github.com/FreeCAD/FreeCAD/releases/tag/0.21.1 was just released

**Comment by pinpox** [comment]
Sorry was away for some time, but I guess it was fixed.

**Pull request closed without merging**
