### PR TITLE
python310Packages.wand: run tests

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pborzenkov** [comment]
Fails on `aarch64-darwin`:

```
=================================== FAILURES ===================================
____________________________ test_encipher_decipher ____________________________

    def test_encipher_decipher():
        with Image(filename='rose:') as img:
            img.depth = 8  # Safety
            was = img.signature
            img.encipher(passphrase='secret')
            assert was != img.signature
            img.decipher(passphrase='secret')
>           assert was == img.signature
E           AssertionError: assert 'fb6fc68beb3b...508f77723cc52' == '5e83d69b350a...e673ed074375e'
E             - 5e83d69b350a3774ea853182093fbf80aa0f0b25613f919e85ee673ed074375e
E             + fb6fc68beb3b1001c5ebaa671c8ac8fddea06995027127765ff508f77723cc52

tests/image_methods_test.py:748: AssertionError
________________________________ test_depth_set ________________________________

fx_asset = local('/private/tmp/nix-build-python3.10-wand-0.6.7.drv-0/Wand-0.6.7/tests/assets')

    def test_depth_set(fx_asset):
        """Sets the image depth"""
        with Image(filename=str(fx_asset.join('mona-lisa.jpg'))) as img:
            img.depth = 16
>           assert img.depth == 16
E           AssertionError: assert 5082168976 == 16
E            +  where 5082168976 = <wand.image.Image: af53380 'JPEG' (402x599)>.depth

tests/image_properties_test.py:198: AssertionError
```

I might be able to investigate on the weekend.

**Comment by dotlambda** [comment]
ping @pborzenkov

**Comment by pborzenkov** [comment]
> ping @pborzenkov

Hi @dotlambda
Sorry it took me so long, just had a bit of free time to take a look at this PR.

So indeed it's a problem in the `Wand` itself that just happens to trigger on Darwin arm64.

`Image.depth(depth)` method has incorrect `cdef` and, thus, uses some random data from stack when called from Python and corrupts memory. This this PR that fixes the issue: https://github.com/emcconville/wand/pull/577
Both tests fail because of this problem.

Surprisingly, there is also an issue with `encipher`/`decipher`, as both `encihper` and `decipher` call `C`'s `Decipher` method. But looks like they are completely symmetrical and still work fine. Anyway, here is the PR that fixes this as well: https://github.com/emcconville/wand/pull/578

You can pull the fixes as patches until the new release is available.

**Comment by onny** [comment]
Please rebase PR

**Review by pborzenkov — APPROVED** [review]

**Comment by onny** [comment]
Thank you all :)

**Pull request merged**
