### PR TITLE
indilib: 1.1.0 -> 1.8.6

### PR DESCRIPTION
**Pull request by hjones2199**
###### Motivation for this change
Receive upstream bugfixes and new astronomical equipment support.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102385` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>kstars</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>indilib</li>
  </ul>
</details>

**Comment by hjones2199** [comment]
> Result of `nixpkgs-review pr 102385` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> 1 package built:
> 
> ```
> -- Found OpenGL: /nix/store/qmh5qmrxml57pmm156vrbbxh1pyygrgn-libGL-1.3.2/lib/libOpenGL.so
> -- Looking for drand48
> -- Looking for drand48 - found
> -- Found ZLIB: /nix/store/63x53nvrc8f3g302ral5sczhjqc5pf0d-zlib-1.2.11/lib/libz.so (found version "1.2.11")
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> CMake Error at cmake/modules/FindNova.cmake:56 (message):
>   libnova not found.  Please install libnova development package.
> Call Stack (most recent call first):
>   kstars/CMakeLists.txt:1064 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/tmp/nix-build-kstars.drv-0/kstars-7acc527/build/CMakeFiles/CMakeOutput.log".
> See also "/tmp/nix-build-kstars.drv-0/kstars-7acc527/build/CMakeFiles/CMakeError.log".
> builder for '/nix/store/sa1n9zgzhpf1jr2jcs2wykizmlhc7aqc-kstars.drv' failed with exit code 1
> ```

Latest commit fixes kstars, and applies patches to support telescope control via the indilib binaries in the nix store.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102385` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>indilib</li>
    <li>kstars</li>
  </ul>
</details>

**Review by TimPut — APPROVED** [review]
Looks good and works for me.

**Pull request merged**
