### PR TITLE
crawl: 0.21.1 -> 0.22.0

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

crawl update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Both **crawl** and **crawl-tiles** binaries works (**crawl** and **crawlTiles** packages).
@abbradar

### CODE REVIEW

**Comment by timokau** [comment]
While you're at it, would you mind quoting the variable in `patchShebangs $i`? Also just in case you know what the purpose of the patch is, it would be nice to document that.

**Comment by nonfreeblob** [comment]
@timokau I'm sorry, but my time was only enough to update the version :)
**crawl_purify.patch** changes **SQLITE_INCLUDE_DIR**  in **/crawl-ref/source/Makefile**
It also changes **/crawl-ref/source/util/find_font** script (**FONTDIRS** value, **find** now has an **-L** flag)

**Comment by timokau** [comment]
Well I would appreciate if you make the change once you find the time :)

Now that I think about it that for loop should be unnecessary anyways, `patchShebangs 'util'` should work just as well. Please also add an explanation comment to the patch ("Patch hard-coded paths in the makefile"). If you want to go the extra mile, it would be best to contact upstream and ask them about configurability. But that's not a hard requirement for me to merge this.

**Comment by nonfreeblob** [comment]
I've made some changes (including changes to all-packages.nix).

In fact, I used to be a crawl contributor.  But now I'm much more interested in roguelikes such as IVAN or NetHack. So I wouldn't want to spend a lot of time on crawl. However, this time (0.22.0) the crawl-tiles interface looks great  :smiley: 

The serious problem is that the file **init.txt**, which defines the crawl configuration (including language), is loading from the nix store.  Thus, it is not possible to play with a configuration other than the default configuration :cry:

**Comment by timokau** [comment]
From: Timo Kaufmann <timokau@zoho.com>
To: NixOS/nixpkgs <reply+0039f9228dd708e7c233d1a96408be1119f2ce1045d0400392cf000000011786c48d92a169ce14d73ee8@reply.github.com>
Cc:
Bcc:
Subject: Re: [NixOS/nixpkgs] crawl: 0.21.1 -> 0.22.0 (#44882)
Reply-To:
In-Reply-To: <NixOS/nixpkgs/pull/44882/c412282760@github.com>

On 18-08-11 08:36, nonfreeblob wrote:
> I've made some changes (including changes to all-packages.nix).

Thanks :)

> The serious problem is that the file **init.txt**, which defines the crawl configuration (including language), is loading from the nix store.  Thus, it is not possible to play with a configuration other than the default configuration :cry:

That sounds like it really should be a user-configuration and not part of the package. It would be best to fix that. But if its not a regression and you don't want to spend the time, I'm happy with the PR as-is.

I'm not sure why you made the `all-packages.nix` change, but I don't have much of an opinion about that either way. The old way had the advantage/disadvantage that an override to `crawl` would automatically propagate to `crawl-tiles`.

> **init.txt**

By the way, stuff like code, filenames etc. is usually enclosed in backticks in markdown, like this: \`init.txt\` (`init.txt`). You can also enclose larger code segments in three backticks:

```
multi
line
```

@grahamcofborg build crawl crawl-tiles

**Comment by nonfreeblob** [comment]
Thanks! :)

> I'm not sure why you made the all-packages.nix change, but I don't have much of an opinion about that either way. The old way had the advantage/disadvantage that an override to crawl would automatically propagate to crawl-tiles.

We had some discussion on this topic: https://github.com/NixOS/nixpkgs/pull/42766 (outdated branch).
Although I personally have no preference on how it will be better. But if crawl be deleted or renamed, crawlTiles is also unavailable, I think.

> By the way, stuff like code, filenames etc. is usually enclosed in backticks in markdown, like this: `init.txt` (init.txt). You can also enclose larger code segments in three backticks:

Thanks! I'll keep that in mind. I'm just a little lazy for quality markup  :smiling_imp:

> That sounds like it really should be a user-configuration and not part of the package. It would be best to fix that. But if its not a regression and you don't want to spend the time, I'm happy with the PR as-is.

I'm afraid I'm not ready to do that :expressionless:

**Comment by nonfreeblob** [comment]
Maybe I did misunderstand him  :disappointed:  Fortunately, all this can be easily fixed at any time.

Thanks for merging the pull requests and for your patience! :ok_hand:

**Pull request merged**
