### PR TITLE
nixosTests.virtualbox: fix

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

This test has been lacking in maintenance, and hasn't worked at all for some time.  These changes bring it to the point where all the tests work, but only on Intel CPUs.  There's a [longstanding bug](https://github.com/NixOS/nixpkgs/pull/94858#issuecomment-680228645) making it not work properly on AMD, which I have not been able to fix as part of this work.

Details in commit messages.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg test virtualbox

**Comment by alyssais** [comment]
(OfBorg is demonstrating one of the AMD issues)

**Comment by teutat3s** [comment]
Your comment regarding build failures on AMD CPUs got me curious and I started a build on my Ryzen CPU. To my surprise, it didn't fail. Do you know if the failures occurred on each build before or only sometimes?
Repro:
```
git fetch origin pull/179235/head:virtualbox-tests && git checkout virtualbox-tests && cd nixos/tests

vim virtualbox.nix
# change this line
-      virtualisation.qemu.options = ["-cpu" "kvm64,vmx=on"];
+     virtualisation.qemu.options = ["-cpu" "kvm64,svm=on"];

nix-build virtualbox.nix

[...]
machine: must succeed: rm -rf /home/alice/vboxshare-test2
(finished: must succeed: rm -rf /home/alice/vboxshare-test2, in 0.02 seconds)
machine: must succeed: mkdir -p /home/alice/vboxshare-test2
(finished: must succeed: mkdir -p /home/alice/vboxshare-test2, in 0.02 seconds)
machine: must succeed: chown alice:users /home/alice/vboxshare-test2
(finished: must succeed: chown alice:users /home/alice/vboxshare-test2, in 0.02 seconds)
machine: must succeed: su - alice -c 'VBoxManage unregistervm test2 --delete'
machine # [  163.484701] su[1686]: Successful su for alice by root
machine # [  163.486364] su[1686]: pam_unix(su:session): session opened for user alice(uid=1000) by (uid=0)
machine # 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
machine # [  163.563312] su[1686]: pam_unix(su:session): session closed for user alice
(finished: must succeed: su - alice -c 'VBoxManage unregistervm test2 --delete', in 0.10 seconds)
(finished: run the VM test script, in 163.94 seconds)
test script finished in 163.97s
cleanup
kill machine (pid 8)
machine # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/6wiycdxh63mk4krdd75db0hshicna6yy-python3-3.10.4/bin/python3.10)
(finished: cleanup, in 0.03 seconds)
kill vlan (pid 7)
/nix/store/sczf21n8cz1wjmbldh2z1m2f99xr3zzi-vm-test-run-virtualbox-headless
/nix/store/5k2dxz4mfy5zlihc7ny37vi06frn4li8-vm-test-run-virtualbox-host-usb-permissions
/nix/store/52pq8r9db69p006plqkayg1swcv5icbn-vm-test-run-virtualbox-net-hostonlyif
/nix/store/mm5lx9b4abh5qvfpx6kpx9qx6j8qlaiw-vm-test-run-virtualbox-simple-cli
/nix/store/d83b3kz4jiql6crazccy4w78p4mxpcbp-vm-test-run-virtualbox-simple-gui
/nix/store/v7zbg666yrp6016vghg33a2m1azh0zhr-vm-test-run-virtualbox-systemd-detect-virt
```

```
AMD Ryzen 7 3700X 8-Core Processor
Linux 5.15.47
```

**Review by teutat3s — APPROVED** [review]

**Comment by flokli** [comment]
Like @teutat3s, I also had success running this on a `AMD EPYC 7502P 32-Core Processor` after updating `virtualisation.qemu.options`.

It seems it's possible to just set `kvm64,svm=on,vmx=on` to get to work on both AMD and Intel?

**Comment by alyssais** [comment]
On the AMD machine I tried it on, it just times out.  But that machine is stuck on an ancient kernel, and I'm not able to update it, so plausibly it's just some old kernel bug that was since fixed.  I'll update the QEMU options.

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
