### PR TITLE
codimd: 1.5.0 -> 1.6.0

### PR DESCRIPTION
**Pull request by WilliButz**
###### Motivation for this change
https://github.com/codimd/server/releases/tag/1.6.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WilliButz** [comment]
@GrahamcOfBorg test codimd

**Review by Ma27 — COMMENTED** [review]
I can reproduce ofborg's hash-mismatch locally as well:

```
js-sequence-diagrams-b9afa03> removing `.git'...
hash mismatch in fixed-output derivation '/nix/store/0h754dqachgmhs9pasv4i4fs0i0iwi3s-js-sequence-diagrams-b9afa03':
  wanted: sha256:1fg3xsyndh7lnd9hqxazv2p01l2p6q5pv72scrcrrf2arbizgk35
  got:    sha256:12v57bdld5a2550xvqh1rcinpld48awgd1s0gbny7z0b0z827ggw
cannot build derivation '/nix/store/m254cqvk82fq5wv6dhh2l5s1i347nki5-js-sequence-diagrams.git.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mzdxk9jlgbgn5xj2v3rd0x13gxlp2wan-offline.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jp6gkgri19107rjzq73i2bi6ca9g3gvx-CodiMD-modules-1.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wcqxgvk65g06h1pwg9vm0p28agz6m0sc-codimd.drv': 1 dependencies couldn't be built
[265 built (1 failed), 1219 copied (103.5 MiB), 59.7 MiB DL]
error: build of '/nix/store/wcqxgvk65g06h1pwg9vm0p28agz6m0sc-codimd.drv' failed
```

**Comment by WilliButz** [comment]
Oh, I can confirm it as well. I'll check for a successful build on another host first and will update the PR after that.

**Comment by WilliButz** [comment]
@GrahamcOfBorg test codimd

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
