### PR TITLE
azure-cli: fix build failure

### LINKED ISSUE #263510: Build failure: python3.11-azure-cli
### Steps To Reproduce

1. build azure-cli

### Build log

```
error: builder for '/nix/store/qbk4jfwi7gyhfy5qdynwl52fsgh3flnm-python3.11-azure-cli-core-2.53.0.drv' failed with exit code 1;
       last 50 log lines:
       > azure/cli/core/tests/test_aaz_operation.py:402
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:402: DeprecationWarning: invalid escape sequence '\['
       >     with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find 'o' in 'l\[0\]'. Available options: \['p', 's'\]"):
       >
       > azure/cli/core/tests/test_aaz_operation.py:444
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:444: DeprecationWarning: invalid escape sequence '\['
       >     with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find 't' in 'l\[1\]'. Available options: \['p', 's'\]"):
       >
       > azure/cli/core/tests/test_aaz_operation.py:464
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:464: DeprecationWarning: invalid escape sequence '\('
       >     with self.assertRaisesRegex(InvalidArgumentValueError, "Expect <class 'str'>, got 3 \(<class 'int'>\)"):
       >
       > azure/cli/core/tests/test_aaz_operation.py:484
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:484: DeprecationWarning: invalid escape sequence '\['
       >     with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find '\[10\]' in 'd'. Available options: \['a', 'b', 'c'\]"):
       >
       > azure/cli/core/tests/test_aaz_operation.py:495
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:495: DeprecationWarning: invalid escape sequence '\('
       >     with self.assertRaisesRegex(InvalidArgumentValueError, "Expect <class 'int'>, got a \(<class 'str'>\)"):
       >
       > azure/cli/core/extension/__init__.py:11
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/extension/__init__.py:11: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
       >     from distutils.sysconfig import get_python_lib  # pylint: disable=deprecated-module
       >
       > azure/cli/core/extension/__init__.py:11
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/extension/__init__.py:11: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
       >     from distutils.sysconfig import get_python_lib  # pylint: disable=deprecated-module
       >
       > azure/cli/core/tests/test_help_loaders.py:13
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_help_loaders.py:13: PytestCollectionWarning: cannot collect test class 'TestCommandLoader' because it has a __init__ constructor (from: azure/cli/core/tests/test_help_loaders.py)
       >     class TestCommandLoader(AzCommandsLoader):
       >
       > azure/cli/core/tests/test_application.py::TestApplication::test_client_request_id_is_refreshed_after_execution
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_application.py:56: DeprecationWarning: Please use assertNotEqual instead.
       >     self.assertNotEquals(old_id, cli.data['headers']['x-ms-client-request-id'])
       >
       > azure/cli/core/tests/test_application.py::TestApplication::test_client_request_id_is_refreshed_correctly
       >   /build/azure-cli-2.53.0-src/src/azure-cli-core/azure/cli/core/tests/test_application.py:35: DeprecationWarning: Please use assertNotEqual instead.
       >     self.assertNotEquals(old_id, cli.data['headers']['x-ms-client-request-id'])
       >
       > azure/cli/core/tests/test_command_registration.py: 10 warnings
       >   /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/unittest/case.py:1176: DeprecationWarning: assertDictContainsSubset is deprecated
       >     warnings.warn('assertDictContainsSubset is deprecated',
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED azure/cli/core/tests/test_command_registration.py::TestCommandRegistration::test_command_index - AttributeError: <MagicMock id='140737265805712'> does not have the attribut...
       > FAILED azure/cli/core/tests/test_command_registration.py::TestCommandRegistration::test_command_index_always_loaded_extensions - AssertionError: [] != 'FAKE_HANDLER'
       > FAILED azure/cli/core/tests/test_parser.py::TestParser::test_parser_error_spellchecker - AssertionError: 0 != 5
       > =========== 3 failed, 237 passed, 3 deselected, 22 warnings in 6.15s ===========
       For full logs, run 'nix log /nix/store/qbk4jfwi7gyhfy5qdynwl52fsgh3flnm-python3.11-azure-cli-core-2.53.0.drv'.
error: 1 dependencies of derivation '/nix/store/2fnf2n69hxkair57l0jm4fjxlsbn3s4a-python3.11-azure-cli-2.53.0.drv' failed to build

```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
🔨 Welcome to khanelinix
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

```

### PR DESCRIPTION
**Pull request by mdarocha**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/263510

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AkechiShiro** [comment]
Thanks a lot for having done this PR, I will do some check, and approve it soon if everything goes well !

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 263637` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]

**Comment by natsukium** [comment]
feel free to ping me to merge this

**Comment by mdarocha** [comment]
> feel free to ping me to merge this

@AkechiShiro mentioned that he wanted to do some checks (can you elaborate on that? maybe we can add them to install tests?)

Other than that, I consider this ready to merge

**Comment by AkechiShiro** [comment]
@natsukium 
It's all good to me, it works, I won't be writing more checks for now (only wanted to run nixpkgs-review on it, but it's been done).

@mdarocha I was wondering if specific Azure CLI extensions are usable but these are not installed by default with the azure-cli package, **this is out of the scope of this PR**.

Maybe those extensions must be packaged at some point (https://github.com/Azure/azure-cli-extensions) and a flag must expose them, once that's done, I may add tests for these (I should open an issue to track the support of those).
<details>
 <summary>Debug output of the az extension add --name bastion</summary>
<pre>
cli.azure.cli.core.extension.operations: Extension source is url? True
cli.azure.cli.core.extension.operations: Downloading https://azcliprod.blob.core.windows.net/cli-extensions/bastion-0.2.5-py3-none-any.whl to /run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl
urllib3.connectionpool: Starting new HTTPS connection (1): azcliprod.blob.core.windows.net:443
urllib3.connectionpool: https://azcliprod.blob.core.windows.net:443 "GET /cli-extensions/bastion-0.2.5-py3-none-any.whl HTTP/1.1" 200 35827
cli.azure.cli.core.extension.operations: Downloaded to /run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl
cli.azure.cli.core.extension.operations: Validating the extension /run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl
cli.azure.cli.core.extension.operations: Checksum of /run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl is OK
cli.azure.cli.core.extension.operations: Validation successful on /run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl
cli.azure.cli.core.extension.operations: Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
cli.azure.cli.core.extension.operations: Linux distro check: An error occurred while checking linux distribution version source list consistency.
cli.azure.cli.core.extension.operations: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/azure-cli.list'
cli.azure.cli.core.extension.operations: Executing pip with args: ['install', '--target', '/home/akechi/.azure/cliextensions/bastion', '/run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl']
cli.azure.cli.core.extension.operations: Running: ['/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/bin/python3.11', '-m', 'pip', 'install', '--target', '/home/akechi/.azure/cliextensions/bastion', '/run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
cli.azure.cli.core.extension.operations: /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/bin/python3.11: No module named pip

cli.azure.cli.core.extension.operations: Command '['/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/bin/python3.11', '-m', 'pip', 'install', '--target', '/home/akechi/.azure/cliextensions/bastion', '/run/user/1003/tmpwe9p6shh/bastion-0.2.5-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /home/akechi/.azure/cliextensions/bastion
cli.azure.cli.core.azclierror: Traceback (most recent call last):
....
</pre>
</details>

They don't work as of right now/cannot be installed/upgraded as they're installed outside the /nix/store I believe (in $HOME/.azure/cliextensions), not sure of the way forward to fix this.

**Review by AkechiShiro — APPROVED** [review]
It looks like it does fix the build, there is also an upstream issue opened about Python 3.11 live testing being broken, they mention a temporary fix at the moment : https://github.com/Azure/azure-cli/issues/27641

I will try and test if this workaround still works for version 2.53.1 (which is the latest to this day) however it'd be best to do the latest release test, after merging #263909

**Pull request merged**
