### PR TITLE
fetchgit: output improvements

### PR DESCRIPTION
**Pull request by timbertson**
I use fetchgit a lot, but scrubbing through the output to copy/paste out the revision hash and the digest hash (both long hashes) can be tedious. So I thought perhaps `nix-prefetch-git` should just print out a valid nix expression, like so:

```
$ nix-prefetch-git $PWD --quiet
{
  url = "/home/tim/dev/nix/nixpkgs";
  rev = "d27f16399d9e5459bf7a829b7f18e8a7eee314be";
  sha256 = "453b04608f0ca057e26f9c45cfa65630f09bfb3d5492ae338801bd4b14befd68";
}
```

This is very easy to copy/paste, and you can even redirect the result into a file and then directly import it as e.g. `fetchgit (import ./git-rev.nix)` (obviously you'd need to use a public URL instead of a local path in that case)

This patch also implements the `--qiet` flag. It previously respected an inherited `$QUIET` var, but this wasn't used consistently.

Any scripts relying on the old output will break, but I don't know how common that is likely to be.

I haven't touched any of the other `prefetch` scripts yet, but if this goes ahead I expect I'd like to at least do the same to the `url` fetcher, since that is the other main one I use myself.

### CODE REVIEW

**Comment by bjornfor** [comment]
I like your idea! I guess originally the script was supposed to print only the hash on stdout. Now it prints a bit more (that's partly my fault I think):

```
$ nix-prefetch-git https://github.com/user/repo 2>/dev/null
git revision is f5398075290171eb18760aac7e6067211400d67f
Commit date is 2015-12-08 22:50:24 +0100
74c27aec2b447809a6f6e15fda438811c70b6824569f55fda97fa7929f2e7ed2
```

But it prints a lot to stderr, especially for big repos with lots of refs. But it may come in handy when debugging, so not sure if we should remove that...

About about changing the _default_ output format, not so sure. Maybe it should be configurable?

Suggestion:

```
  -o --output=STRING       Change output mode (simple, shell, nix, json)
```

simple prints just the hash. shell prints
```
REV="abcd1234"
HASH="2137..."
```

and the rest should be self explanatory.

Thoughts?

**Comment by timbertson** [comment]
Ahh, I shoud have clarified - I kept pretty much the same stderr output, if you don't use `--quiet`:

```
/home/tim/dev/nix/nixpkgs/pkgs/build-support/fetchgit/nix-prefetch-git (pwd)
Initialized empty shared Git repository in /tmp/git-checkout-tmp-Scpm4PZP/git-export/.git/
remote: Counting objects: 15505, done.
remote: Compressing objects: 100% (11031/11031), done.
remote: Total 15505 (delta 662), reused 11697 (delta 429)
Receiving objects: 100% (15505/15505), 10.93 MiB | 6.23 MiB/s, done.
Resolving deltas: 100% (662/662), done.
From /home/tim/dev/nix/nixpkgs
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is d27f16399d9e5459bf7a829b7f18e8a7eee314be
path is /nix/store/3adww6zk3pzqhb748cx8vxgl6ijqk5pj-git-export
git human-readable version is -- none --
Commit date is 2015-12-13 17:22:59 +1100
hash is 453b04608f0ca057e26f9c45cfa65630f09bfb3d5492ae338801bd4b14befd68
{
  url = "/home/tim/dev/nix/nixpkgs";
  rev = "d27f16399d9e5459bf7a829b7f18e8a7eee314be";
  sha256 = "453b04608f0ca057e26f9c45cfa65630f09bfb3d5492ae338801bd4b14befd68";
}
```

I thought about `--expr` which is equivalent to your `--output=nix` option, and that would definitely be an improvement. But unless anyone actually actively prefers the current output, I'd like to make this the default so that it's better for everyone, not just those who know about or think to look for the flag.

**Comment by bjornfor** [comment]
I have no strong opinion on changing the output format. I don't rely on the current format and I think what you propose is better.

**Comment by timbertson** [comment]
Ping, anyone?

**Comment by zimbatm** [comment]
Yes ! Do you care to rebase the change ?

**Comment by timbertson** [comment]
Yup, rebased :)

**Comment by zimbatm** [comment]
Thanks !

**Pull request merged**
