### PR TITLE
pythonPackages.uproot: 3.4.19 -> 3.7.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Noticed it was broken when doing a nix-review of another package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
$ nix path-info -Sh ./result
/nix/store/7cvvcs0j7xh10w2aq1a4852p5yzf25vg-python3.7-uproot-3.7.0       155.5M

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.uproot python3Packages.uproot

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.uproot python3Packages.uproot

**Review by veprbl — APPROVED** [review]

**Comment by veprbl** [comment]
@jonringer Thank you!

**Comment by jonringer** [comment]
Thanks for fixing the python2 build :) @veprbl

**Pull request merged**
