### PR TITLE
Revert "cabal: enable multi-threaded builds with GHC 7.8.x or later"

### PR DESCRIPTION
**Pull request by shlevy**
This likely exacerbates the non-determinism in ghc package ids, so until
that is fixed let's live with the slow builds.

This reverts commit 817c0e41443a5176baf6dd9b422878fdccecd266.

### CODE REVIEW

**Comment by puffnfresh** [comment]
It seems like GHC's non-determinism problems have been mostly solved. Can we enable parallel builds again?

**Comment by puffnfresh** [comment]
Looks like this might have been re-enabled already: I can see an `enableParallelBuilding` attribute.

**Comment by sternenseemann** [comment]
No, it hasn't: The [builder](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix#L89) only enables it for ghc 7.8.x or older.

**Comment by peti** [comment]
@puffnfresh, could you please clarify what you mean by these problems being "mostly solved"? I am not aware of any solutions to GHC's non-determinism issues whatsoever.

**Comment by peti** [comment]
@sternenseemann, the generic builder enables parallel builds for packages that have no library if GHC 7.8 or later is used.

**Comment by puffnfresh** [comment]
@peti there was a talk at Haskell Implementors Workshop about all of the work put into [GHC #4012](https://ghc.haskell.org/trac/ghc/ticket/4012). Supposedly most of the problems have been solved as of 8.0.2 - especially since the removal of `Ord Unique`.

**Comment by peti** [comment]
Well, what exactly does it mean that "most" problems have been solved? Can you please be more specific?

**Comment by sternenseemann** [comment]
@peti, oh I see.

**Comment by jb55** [comment]
[8.0.2rc1](http://downloads.haskell.org/~ghc/8.0.2-rc1/) just released, might be a good time to test parallel builds again

**Comment by puffnfresh** [comment]
Looks like 8.0.2rc1 has a fix for "Interface file build determinism" - might be good to try it out!

https://mail.haskell.org/pipermail/glasgow-haskell-users/2016-November/026410.html

**Comment by peti** [comment]
@jb55, @puffnfresh, how do you suggest we test it?

**Comment by jb55** [comment]
> While GHC 8.0.2 builds interface files deterministically, there's still some work left with making it hard to break in the future.[1]

Hmm it looks like we don't have strong guarantees that it won't break for future versions at this time unfortunately. So even if we did enable parallel builds it might bite us again.

[1] https://ghc.haskell.org/trac/ghc/ticket/4012#comment:235

**Comment by jb55** [comment]
@peti in the meantime, is it possible to expose "enableParallelBuilding" as an overridable option in the generic builder? I have a large project that I deploy frequently that would benefit greatly from this. Otherwise I could make a generic builder and use the `package.env` + `make` to build directly. Slightly annoying but not too bad.

**Comment by jb55** [comment]
I ended up going with something like this to enable parallel builds in one of my large projects:

```nix
let projectEnv = (haskellPackages.callPackage ./haskell-project.nix { }).env;
in
stdenv.mkDerivation rec {
  name = "project-${version}";
  version = "3.0";
  src = ./.;
  makeFlags = "PREFIX=$(out)";
  buildPhase = ''
    ${projectEnv.shellHook}

    make -j$NIX_BUILD_CORES
  '';
  buildInputs = projectEnv.nativeBuildInputs;
}
```

hacky, but works.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/21214

**Pull request merged**
