### PR TITLE
lib.systems: Avoid allocating intermediate attrset when parsing skeleton list

### PR DESCRIPTION
**Pull request by adisbladis**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Do we do this frequently enough to care about that allocation cost? I wouldn't think so.

**Comment by adisbladis** [comment]
> Do we do this frequently enough to care about that allocation cost? I wouldn't think so.

Not really, no. But it looks ugly for no reason.

**Comment by Ericson2314** [comment]
I prefer "switch case" to "chained if" :)

**Comment by adisbladis** [comment]
I think `{ "1" = ...; }.${toString (length l)}` constructs like is an anti-pattern & an eye sore that possibly encourages others to build in the same style.
It doesn't matter (much) for performance in this instance, but it does in general.

**Comment by Ericson2314** [comment]
Yeah it's not as nice for numbers as for string version, but I still think it is a fine style because it is closer to pattern matching, and pattern matching is good.

Maybe someone else will chime and and agree with you I'm being nuts :)

**Review by ghost — CHANGES_REQUESTED** [review]
Since this is just cleanup, could it please wait for

- https://github.com/NixOS/nixpkgs/pull/235230

to merge first?  That PR contains the test suite for the code that's being modified here -- right now we have no test coverage for it at all.

**Comment by adisbladis** [comment]
> Since this is just cleanup, could it please wait for
> 
> - https://github.com/NixOS/nixpkgs/pull/235230
> 
> to merge first?  That PR contains the test suite for the code that's being modified here -- right now we have no test coverage for it at all.

Yeah, no worries.

**Comment by adisbladis** [comment]
Can't be bothered arguing about this one.

**Pull request closed without merging**
