### PR TITLE
python3PackagesWithNumpy2: init

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
We want a version of the Python package set using numpy_2 to be available in the cache. Recursing into the attribute set makes Hydra build it.

This should make a non-solution like https://github.com/NixOS/nixpkgs/pull/338334 unnecessary.
closes https://github.com/NixOS/nixpkgs/pull/338334

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
Can't say I'm a fan of another python package set. I'd much rather keep numpy_1 for 24.11 and evaluate moving to numpy_2 after.

**Comment by natsukium** [comment]
I am not really excited about it.
I don't have the time or computing resources to maintain a numpy2 tree, and it would push a huge cost on all the maintainers associated with python ecosystem.

**Comment by infinisil** [comment]
Doing some quick checks, I'm getting that 3660 additional derivations would be built by Hydra, that's about 39.4% of python3Packages, definitely not insignificant.

<details><summary>Code</summary>

```nix
let
  pkgs = import ./. {};
  inherit (pkgs) lib;
  all = lib.attrNames pkgs.python3Packages;
  grouped = lib.partition (name:
    builtins.tryEval (pkgs.python3Packages.${name}.outPath or null)
    == builtins.tryEval (pkgs.python3PackagesWithNumpy2.${name}.outPath or null)
  ) all;

  additional = lib.length grouped.wrong;
  total = lib.length all;
in
"${toString additional} additional derivations would be built by Hydra, about ${toString (100.0 / total * additional)}% of the python3Packages"
```

</details>

**Comment by infinisil** [comment]
Are there a lot of expected breakages from the Numpy 2 upgrade? In that case this package set might also be a great to have so that breakages can be seen on Hydra. People depending  on Numpy 2 would be incentivised to use it and submit fixes for breakages.

**Comment by doronbehar** [comment]
This solution is still a bit weird, but a bit more acceptable, and definitely better then some other proposals that were raised. I wonder if @mweinelt can share with us how severe were the breakages in the last python updates cycle? Since these changes have to go through staging anyway, why not make `numpy = numpy_2` and see how many new failures we see Hydra in the upcoming `staging-next` cycle?

**Comment by dotlambda** [comment]
I assume removing `python311Packages` is not an option because ML stuff depends on it, in particular tensorflow? I think if we could remove it and add `python3PackagesWithNumpy2` instead this might not be the worst idea.

**Comment by emilazy** [comment]
There’s quite a few packages pinning 3.11 right now. I think we always carry one version back?

**Comment by doronbehar** [comment]
I took the first 4 commits to an external PR which can be merged a bit quicker, because it seems we agree upon them: https://github.com/NixOS/nixpkgs/pull/340832

**Comment by dotlambda** [comment]
Numpy was updated to v2 in https://github.com/NixOS/nixpkgs/pull/354627.

**Pull request closed without merging**
