### PR TITLE
specup: init

### PR DESCRIPTION
**Pull request by danielrolls**
## Description of changes

A command line tool for cases where you want to generate markup from yaml. This is common for web development but using a command line tool saves building and maintaining a framework in your favorite programming language.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by danielrolls** [comment]
I checked closures by running the following commands. I'm just preempting a request from a similar PR.

```
$ nix path-info -Sh .#specup
/nix/store/npwb53371yb2ya0zvjx9igkbv0nnxx6x-specup-0.1.0.1-bin	  63.2M
```

```
$ nix path-info -r .#specup
evaluating derivation 'git+file:///home/dan/repos/nixpkgs#specup'/nix/store/bncqz1jnd3mkssg2rbx3qgqy55bi0m7g-xgcc-13.2.0-libgcc
/nix/store/mgkvalznvc8ik2r9p93445vjbd80ax00-libunistring-1.1
/nix/store/x3wc0s3165pfcakkbbc22j7k5hndc73k-libidn2-2.3.4
/nix/store/7jiqcrg061xi5clniy7z5pvkc4jiaqav-glibc-2.38-27
/nix/store/1l3a02nqq5b5v7rhchj89hi7plmbza5r-openssl-3.0.12
/nix/store/4znq11s8j9d29kj2l4qivl5pyhbbzy8q-zlib-1.3
/nix/store/4hdjb7r9k0dpcyk11k568c6y9kdgf6zc-libssh2-1.11.0
/nix/store/4z9wwg9lgdy30drvizy891zisj2makq4-nghttp2-1.57.0-lib
/nix/store/9nsd8bhgzb7ar3366lvlycj9lr0wldpx-brotli-1.1.0-lib
/nix/store/kbsb6s8djydiawgswnm8j5bwn1yxaqb7-gcc-13.2.0-libgcc
/nix/store/np3cndfk53miqg2cilv7vfdxckga665h-gcc-13.2.0-lib
/nix/store/b5r5rikbdpr6qs4wfm6dxz9dbrmyvps6-gmp-with-cxx-6.3.0
/nix/store/c5gp1vii3qmma428db3gyyb91p710whs-zstd-1.5.5
/nix/store/cjbyb45nxiqidj95c4k1mh65azn1x896-bash-5.2-p21
/nix/store/d3jhphmgval3c9hhvmz04qj3qavy8hns-keyutils-1.6.3-lib
/nix/store/dx65xxpnmcb4a3pjkqp74zibxd7wb16x-xz-5.4.5
/nix/store/jqcm3z315k4dx4qqdcvvs3b80fganpbr-libkrb5-1.21.2
/nix/store/l5rgcblia1bvrhp8p7s9xbyhf25alnpy-curl-8.5.0
/nix/store/npfpil5nswlaqy7y56dwp0csj91pjiyd-libffi-3.4.4
/nix/store/rmnl7cvvr3gfx4g821xbcaqy3x0g6v6r-bzip2-1.0.8
/nix/store/qnlgnpvh94xw2j3pm5f02iw102lx6llc-elfutils-0.190
/nix/store/npwb53371yb2ya0zvjx9igkbv0nnxx6x-specup-0.1.0.1-bin
```

**Comment by maralorn** [comment]
LGTM, thank you!

**Comment by sternenseemann** [comment]
Can we add this to `release-haskell.nix` as well?

**Comment by danielrolls** [comment]
> Can we add this to `release-haskell.nix` as well?

Sure thing. I raised this as https://github.com/NixOS/nixpkgs/pull/287824.

**Pull request merged**
