### PR TITLE
[21.11] collectd: disable xen plugin after xen was marked as insecure.

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

xen was marked as insecure #156915 which breaks collectd because of its xen plugin, so disable this plugin. This is a breaking change, cc @NixOS/nixos-release-managers for validation.

To test it I added a backport of a nixos tests for collectd. I can remove it if you prefer.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by astro — APPROVED** [review]

**Review by thefloweringash — APPROVED** [review]
I'm eager to see this merged since it's currently causing nixos-upgrade to fail on one of my machines. I tried enabling only the plugins I used, but the build failed and I didn't investigate too much further.

Removing the `xencpu` from the list of plugins that are known makes it slightly harder for someone who relies on this plugin to build collectd with xencpu support (nixpkgs won't automatically provide the dependency). I'm personally ok with this, since xen isn't as relevant as it once was, but I'm lightly concerned that we're breaking someone's workflow.

**Comment by bjornfor** [comment]
The 2nd commit lacks a cherry pick -x commit reference. Is it backported from master? If so, please use git cherry-pick -x, else please comment why it is a direct commit to release-21.11 and not going through master.

**Comment by symphorien** [comment]
> The 2nd commit lacks a cherry pick -x commit reference. Is it backported from master? If so, please use git cherry-pick -x, else please comment why it is a direct commit to release-21.11 and not going through master.

It is not a backport. xen is not marked as insecure on unstable.

**Comment by symphorien** [comment]
I pushed a new version that only disables xen from the default list of plugins, so that one can reenable it easily.

@GrahamcOfBorg tests collectd

**Comment by bjornfor** [comment]
@symphorien:

Two things, first it seems xen *is* marked as insecure on unstable (so we should fix that there first and then backport to release-21.11):

```
$ git checkout nixpkgs-unstable && git pull
[...]
$ nix-build ./nixos/tests/collectd.nix
error: Package ‘xen-4.10.4’ in /home/bf/nixpkgs/pkgs/applications/virtualization/xen/generic.nix:248 is marked as insecure, refusing to evaluate.
[...]
```

And secondly, when not backporting, please add a comment in the git commit message about that, not just here in a github thread. (This is a moot point now that we've established that all commits in this PR should be `git cherry-pick -x`ed.)

**Review by bjornfor — CHANGES_REQUESTED** [review]
Please fix `nix-build ./nixos/tests/collectd.nix` on master first, then `git cherry-pick -x` the fixes.

**Comment by bjornfor** [comment]
https://github.com/NixOS/nixpkgs/pull/157931 seems to be a fix (which can then be backported).

**Comment by symphorien** [comment]
> Two things, first it seems xen is marked as insecure on unstable

My bad

https://github.com/NixOS/nixpkgs/pull/158353

**Comment by peterhoeg** [comment]
Waiting for #158352 to finish eval.

**Comment by symphorien** [comment]
The PR now backports #158353 and is ready.

**Review by bjornfor — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 157292 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>collectd</li>  </ul></details>

**Pull request merged**
