### PR TITLE
oci-seccomp-bpf-hook: move to linuxPackages

### PR DESCRIPTION
**Pull request by zowoq**
###### Motivation for this change

Needs to be built against the system kernel.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by saschagrunert** [comment]
Thank you for the draft: I tried to run it in a nixos-shell like this vm.nix:
```
{ pkgs, ... }:
{
  boot.kernelPackages = pkgs.linuxPackages_latest;

  virtualisation = {
    podman.enable = true;
    containers.containersConf.extraConfig = ''
      [engine]
      hooks_dir = [
        "${pkgs.linuxPackages.oci-seccomp-bpf-hook}",
      ]
    '';
  };
}
```

```
> export NIX_PATH=nixpkgs=$PWD && nixos-shell
```

When applying the patch from https://github.com/NixOS/nixpkgs/pull/96761#issuecomment-684510297, then it sill complains to lookup the old kernel sources on runtime:
```
> podman run --annotation io.containers.trace-syscall="of:/tmp/out.json" -it alpine echo hi
…
Error: chdir(/nix/store/37fqbzwkv23r3c340jw7bcy2zl3yn98i-linux-5.4.61-dev/lib/modules/5.8.4/build):
```

If we do not change the kernel packages and remote the 
```
  #boot.kernelPackages = pkgs.linuxPackages_latest;
```
from vm.nix, then it works as expected.

**Comment by zowoq** [comment]
I think this should work:
```nix

{ config, pkgs, ... }:
{
  boot.kernelPackages = pkgs.linuxPackages_latest;

  virtualisation = {
    podman.enable = true;
    containers.containersConf.extraConfig = ''
      [engine]
      hooks_dir = [
        "${config.boot.kernelPackages.oci-seccomp-bpf-hook}",
      ]
    '';
  };
}
```

**Comment by saschagrunert** [comment]
> I think this should work:
> 
> ```nix
> { config, pkgs, ... }:
> {
>   boot.kernelPackages = pkgs.linuxPackages_latest;
> 
>   virtualisation = {
>     podman.enable = true;
>     containers.containersConf.extraConfig = ''
>       [engine]
>       hooks_dir = [
>         "${config.boot.kernelPackages.oci-seccomp-bpf-hook}",
>       ]
>     '';
>   };
> }
> ```

Yep, this works! Thank you again I'll update my PR to use the new config.

**Comment by saschagrunert** [comment]
Requires https://github.com/NixOS/nixpkgs/pull/96761

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]

**Comment by zowoq** [comment]
@saschagrunert Does this have a minimum kernel version that we need to set?

**Comment by saschagrunert** [comment]
> @saschagrunert Does this have a minimum kernel version that we need to set?

I think so, but I'm not sure which one exactly. For sake of security we could go with the current NixOS 20.03 default. This one should at least work.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
