### PR TITLE
dotnetCorePackages.{aspnetcore,net,sdk}_5_0: 5.0 -> 5.0.102

### PR DESCRIPTION
**Pull request by mfocko**
###### Motivation for this change

security patch for .NET 5

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112582` at 78908af0 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/2590009498b7bb93b043e4759777bb25">osu-lazer</a></li></li>
    <li><a href="https://gist.github.com/95e44925128302a24af4ed1b37a773ba">ryujinx</a></li></li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/92d73dc0ffb4ddffe44f02744457aba0">dotnet-sdk_5</a></li> (dotnetCorePackages.sdk_5_0)</li>
    <li><a href="https://gist.github.com/201c3cf290c53b65c0f27a759e18125e">dotnetCorePackages.aspnetcore_5_0</a></li></li>
    <li><a href="https://gist.github.com/5a68d12f9a8b93a982de2c09537121a7">dotnetCorePackages.net_5_0</a></li></li>
    <li><a href="https://gist.github.com/e845216e3a27b84dcb5b549285cb9476">opentabletdriver</a></li></li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112582` at 78908af0 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/fa96593e684c7b084b9ac5ba3325f0da">dotnet-sdk_5</a></li> (dotnetCorePackages.sdk_5_0)</li>
    <li><a href="https://gist.github.com/6c633f8d8ba9530d59cb7c66d4a88434">dotnetCorePackages.aspnetcore_5_0</a></li></li>
    <li><a href="https://gist.github.com/1a0a9a3997b07bc0817683e2820a6046">dotnetCorePackages.net_5_0</a></li></li>
    <li><a href="https://gist.github.com/de39e4408b1a7f9c0efc5f983a471119">opentabletdriver</a></li></li>
  </ul>
</details>

**Comment by felschr** [comment]
Instead of adding new targets we should fix the packages that break due to the update:
See https://github.com/NixOS/nixpkgs/pull/97803 where this was done for `ryujinx` & `osu-lazer` as part of a previous update.

**Comment by avdv** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/138296

**Pull request closed without merging**
