### PR TITLE
openscenegraph: 3.4.0 -> 3.6.2

### PR DESCRIPTION
**Pull request by aanderse**
Looking for approval by @7c6f434c as they are the maintainer.

###### Motivation for this change
version bump

###### Things done
 bumped openscenegraph version from 3.4 to 3.6.2 and added more options for building it

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build openmodelica

**Comment by xeji** [comment]
This depends on `openmodelica` which is marked as broken, so you would have to un-break that first.

**Comment by aanderse** [comment]
@xeji I'm sorry I'm not seeing what is pulling in this openmodelica dependency?

I tried adding openscenegraph_3_6_2 as the package in my ~/.config/nixpkgs/config.nix and then calling nix-store --query --references (nix-instantiate '<nixpkgs>' -A openscenegraph_3_6_2) but I still don't see what is pulling it in... Any help?

**Comment by 7c6f434c** [comment]
No, that was my attempt to test a random rev-dep, I guessed wrong

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build openmw

**Comment by 7c6f434c** [comment]
Maybe better luck this way?

**Pull request merged**
