### PR TITLE
dolibarr: remove myself from maintainers

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

It's a tiring piece of software, and it seems like people who may merge things on it does not share the same definition of the word maintenance, unfortunately.

Paging the people who touched it last time to give an opportunity for someone to step up and take over maintenance.

cc @schoettl @jian-lin @h7x4 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by flokli** [comment]
@aanderse considering you initially landed this, would you be willing to pick up maintainership? I'd rather have it deleted than having it in nixpkgs without someone maintaining it.

**Comment by schoettl** [comment]
Can we see how many downloads the Dolibarr package has from the binary cache? If it is still being used I think deleting it would be very annoying for current users.

I personally won't use it in near future because I will go with a manual installation for simpler code patching.

**Comment by aanderse** [comment]
> @aanderse considering you initially landed this, would you be willing to pick up maintainership? I'd rather have it deleted than having it in nixpkgs without someone maintaining it.

i assume i was simply lending a helping hand in the initial packing of this because i've never used the software nor have any recollection of it at all... i have no interest or objection to removal :man_shrugging:

**Comment by RaitoBezarius** [comment]
> Can we see how many downloads the Dolibarr package has from the binary cache? If it is still being used I think deleting it would be very annoying for current users.
> 
> I personally won't use it in near future because I will go with a manual installation for simpler code patching.

It doesn't make sense to keep something, no matter how popular it is, if it's a piece of leaf software.

**Comment by jian-lin** [comment]
@flokli

> I'd rather have it deleted than having it in nixpkgs without someone maintaining it.

In general, an empty `maintainers` list will not cause the deletion of a package because
1. an empty `maintainers` list does not mean no maintenance
2. an empty `maintainers` list is totally valid
3. non-empty `maintainers` list does not mean good maintenance.

For 1, reasons are as follows:
- More maintenance/contribution are done by non-maintainers.  During 2023, there are [24409][2] PRs by non-maintainers, which is 1.46 times of [16674][3] PRs by maintainers.
- New maintainers are added to `maintainers` list.
- Previous PRs leading to an empty `maintainers` list do not delete the related package.  I have seen many those PRs and here is an [example][4].

For 2, our doc [says][1] `meta.maintainers` should be set.  Well, https://github.com/NixOS/nixpkgs/pull/262143 changed `should` to `must` for only new packages  three months ago without enough discussion.

For 3, here is an [example][5].  I think it is totally valid for the maintainer to not do much maintenance because he does not use the package any more.  Also, my friends and I have seen some (many?) irresponsive maintainers.


Even broken packages with an empty `maintainers` can remain in Nixpkgs.  I think that is what `meta.broken` exists for.  Users interested in a broken package will fix it and the broken one gives them a starting point.  Here is an [example][5].

---

@RaitoBezarius 
> It doesn't make sense to keep something, no matter how popular it is, if it's a piece of leaf software.

I do not think there is a policy about removing packages from Nixpkgs now.  Removing all leaf packages with an empty `maintainers` list does not look good to me.

A policy for that would be great.  The core of Nixpkgs, i.e., Nix, is much better than any other distributions (except Guix).  However, there are still things to learn from other distributions.  For example, this is how Gentoo [removes][6] a [package][7].

> Paging the people who touched it last time to give an opportunity for someone to step up and take over maintenance.

I only add myself to `maintainers` of packages which I use.  I do not use this package so I won't help here.

> it seems like people who may merge things on it does not share the same definition of the word maintenance, unfortunately

The context can be found [here][8].  He refers to me and I admit that I made a mistake.

Fortunately, I think we share the same definition of the word maintenance now.

[1]: https://github.com/NixOS/nixpkgs/commit/64db4d240e8f199e9f44fe1e4d0a1a297a98e76a
[2]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+-label%3A%2211.by%3A+package-maintainer%22++merged%3A2023-01-01..2024-01-01+-author%3Ar-ryantm+
[3]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+label%3A%2211.by%3A+package-maintainer%22++merged%3A2023-01-01..2024-01-01+-author%3Ar-ryantm+
[4]: https://github.com/NixOS/nixpkgs/pull/270662/files#diff-7872d30f561334b2bea308e9ae37530b1c1ebafd2a999b49e1045d27dd5d6b1fR47
[5]: https://github.com/NixOS/nixpkgs/pull/270344
[6]: https://wiki.gentoo.org/wiki/Project:Treecleaner/Policy
[7]: https://devmanual.gentoo.org/ebuild-maintenance/removal/index.html
[8]: https://github.com/NixOS/nixpkgs/pull/264661#issuecomment-1902744822

**Review by jian-lin — APPROVED** [review]

**Comment by flokli** [comment]
The maintainership definition is independent of this PR (so let's merge this and get @RaitoBezarius off the hook).

I however still think things in nixpkgs should be maintained, so yes, in my personal opinion I'd rather have unmaintained packages removed, rather than them staying in nixpkgs around, giving a false sense of quality.

Of course, the pros and cons need to be looked at, and removal might not be an option for non-leaf packages. In any case, this discussion is something for another forum, not this PR, so let's resurrect this somewhere else.

**Pull request merged**
