### PR TITLE
staging-next 2023-10-26

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/257792
- - - 
##### Mass breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by vcunat** [comment]
Oh, code owners.  I guess by definition they want to be notified on staging-next PRs as well?

**Comment by vcunat** [comment]
- [ ] `postgresql*_jit` have issues after LLVM update (all platforms)
  https://hydra.nixos.org/build/239477682/nixlog/1/tail

**Comment by stigtsp** [comment]
Fix for perlPackages.IOTty on Darwin:
- https://github.com/NixOS/nixpkgs/pull/264014 (Thanks, @tssm)

**Comment by vcunat** [comment]
- [ ] libepoxy regressed on `*-darwin`, blocking ~0.9k builds
  test `cgl_epoxy_api` fails
  https://hydra.nixos.org/build/239598678#tabs-buildsteps
  https://hydra.nixos.org/build/239584561#tabs-buildsteps

**Comment by Ma27** [comment]
>  postgresql*_jit have issues after LLVM update (all platforms)

FYI I'm working on it.

**Comment by reckenrode** [comment]
> * [ ]  libepoxy regressed on `*-darwin`, blocking ~0.9k builds
>   test `cgl_epoxy_api` fails
>   https://hydra.nixos.org/build/239598678#tabs-buildsteps
>   https://hydra.nixos.org/build/239584561#tabs-buildsteps

I can’t reproduce the failure locally. 😬

**Comment by reckenrode** [comment]
> I can’t reproduce the failure locally. 😬

The test wasn’t being disabled and just happens to work locally but not on Hydra. I’ve opened a PR to fix.

**Comment by vcunat** [comment]
- [ ] `python3*Packages.aiobotocore` fails tests (on all platforms), blocking ~2.8k builds
  https://hydra.nixos.org/build/239657361/nixlog/1/tail
  Maintainer: @teh

**Comment by stigtsp** [comment]
Fix for perlPackages.XMLLibXML on darwin/clang:
- https://github.com/NixOS/nixpkgs/pull/265003

**Comment by stigtsp** [comment]
- https://github.com/NixOS/nixpkgs/pull/265043

**Comment by stigtsp** [comment]
Fixes darwin build of perlPackages.CryptOpenSSLAES:
- https://github.com/NixOS/nixpkgs/pull/265491

**Comment by fabianhjr** [comment]
Hi @amjoseph-nixpkgs, that is ok though seems like the conflict resolution wasn't succesful since that doesn't eval either :C


```
       error: undefined variable 'pythonForBuild'

       at /home/fabian/Development/Open/nixpkgs/main/pkgs/development/interpreters/python/hooks/default.nix:232:26:

          231|       substitutions = {
          232|         sphinxBuild = "${pythonForBuild.pkgs.sphinx}/bin/sphinx-build";
             |                          ^
          233|       };
```

**Comment by amjoseph-nixpkgs** [comment]
> Hi @amjoseph-nixpkgs, that is ok though seems like the conflict resolution wasn't succesful since that doesn't eval either :C

Dammit, I hate github's web-based merge-conflict resolver thing.

**Comment by amjoseph-nixpkgs** [comment]
@vcunat are there plans to merge this soon?

I think this PR is the "2023-11-06 Wait for staging-next merge into master" from https://github.com/NixOS/nixpkgs/issues/258640 that ZHF was supposed to wait for (but didn't?)

The upgrade of Rust to 1.73 is on this branch, but not on `master`, and it has new warnings which break a bunch of packages... I worry that people haven't noticed that because it hasn't merged back to `master` yet and most people develop against `master` rather than `staging`.  Most of the fixes don't cause mass-rebuilds so they can be done on `master` once this merges back.

If there are specific obstacles preventing this from merging to `master` that I can help with, let me know what they are.

**Comment by reckenrode** [comment]
#266172 is waiting review from @sternenseemann. I believe the Haskell maintainers would prefer this not wait for the next cycle due to possible impact on end-users without the fix (even though applying it will cause a lot of rebuilds on Darwin).

**Comment by amjoseph-nixpkgs** [comment]
I guess this PR will be the final `staging -> master` merge before 23.11?

**Comment by vcunat** [comment]
Probably.  The schedule anticipated that moment to happen tomorrow.  We could manually pick whatever if important.

**Comment by marsam** [comment]
Fix for PostgreSQL JIT https://github.com/NixOS/nixpkgs/pull/267055

**Comment by amjoseph-nixpkgs** [comment]
Hooray!

**Comment by vcunat** [comment]
I forgot to check.  `nixpkgs-unstable` will be apparently blocked by darwin's stdenv bootstrap tools:
https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

**Comment by amjoseph-nixpkgs** [comment]
> I forgot to check. `nixpkgs-unstable` will apparently get blocked by darwin's stdenv bootstrap tools:
> https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

https://github.com/NixOS/nixpkgs/pull/241692#issuecomment-1801171586

**Comment by vcunat** [comment]
Maybe it's notable that `zpool-auto-expand-partitions` broke due to rustc update? https://hydra.nixos.org/build/241313798

/cc (some of) maintainers: @cole-h, @lheckemann, @Hoverbear.

**Comment by cole-h** [comment]
> Maybe it's notable that `zpool-auto-expand-partitions` broke due to rustc update? [hydra.nixos.org/build/241313798](https://hydra.nixos.org/build/241313798)

It was only tangentially related to the rustc update; the true culprit was actually the LLVM update (according to some searching). Fix is here: https://github.com/NixOS/nixpkgs/pull/268562.

**Pull request merged**
