### PR TITLE
imagemagick: 7.1.0-2 -> 7.1.0-4

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
@ofborg eval
@ofborg build imagemagick

**Comment by SuperSandro2000** [comment]
@ofborg eval
@ofborg build imagemagick
@ofborg test imagemagick

**Comment by mweinelt** [comment]
This update broke tests in perl532Packages.PerlMagick (staging-next) and perl530Packages.PerlMagick (staging-next-21.05). Probably should've been updated together.

**Comment by erictapen** [comment]
Mh, that's bad. Latest version in the [source the PerlMagick derivation in Nixpkgs uses](https://www.cpan.org/authors/id/J/JC/JCRISTY/) is 7.0.11-1, so strictly following the Imagemagick version seems impractical here. Or we manage to use the IM github repo for PerlMagick, but the author seems to run some extra steps before releasing the PerlMagick tarball.

I could try to become maintainer for PerlMagick, but I'm afraid I couldn't do anything but updating the package and see if it still builds. The perl ecosystem is a complete miracle for me and I'm not too willing to go into that rabbit hole atm.

**Pull request merged**
