### PR TITLE
flightgear: bump version to 3.4

### PR DESCRIPTION
**Pull request by robberer**
- openscenegraph: bump version to 3.2.1: http://www.openscenegraph.org/index.php/download-section/stable-releases
- remove obsolete patch
- simgear: bump version to 3.2.0

### CODE REVIEW

**Comment by cocreature** [comment]
As 3.4 got released, how about updating directly to that?

**Comment by robberer** [comment]
Indeed. This PR is updated and tested.

Flightgear 3.4.0 now depends on QT5.

**Comment by offlinehacker** [comment]
Update commit message please, i will merge then.

**Comment by robberer** [comment]
done

**Comment by robberer** [comment]
@offlinehacker

**Pull request closed without merging**
