### PR TITLE
fix: update sgx packages

### PR DESCRIPTION
**Pull request by haraldh**
###### Description of changes

- updated azure-dcap-client from `1.12.1` to `1.12.3`
- updated sgx-sdk from `2.21.100.1` to `2.23.100.2`
- updated sgx-ssl from `2.21` to `3.0_Rev2`
- updated ipp-crypto from `2021.9.0` to `2021.10.0`
- sgx-psw also updated automatically
- also tested for reproducible builds

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sbellem** [comment]
Hey @haraldh! For the sdk & psw there's already a PR at #236815.

**Comment by haraldh** [comment]
@sbellem ah, cool ... will rebase

**Comment by haraldh** [comment]
@phlip9 rebased to the most recent versions with additional reproducibility patches

**Comment by haraldh** [comment]
hmm.. the sgx-ssl tests may use ASM ops, which are not available in the build environment, but on any SGX capable CPU..

In
https://logs.ofborg.org/?attempt_id=9985ec19-8124-40a4-8162-2979e89c4839&key=nixos%2Fnixpkgs.243098
it fails with `Illegal instruction`

On my machine:

```
INFO: Enclave configuration 'MiscSelect' and 'MiscSelectMask' will prevent enclave from using dynamic features. To use the dynamic features on SGX2 platfo>
The required memory is 25116672B.
The required memory is 0x17f4000, 24528 KB.
handle_compatible_metadata: Overwrite with metadata version 0x100000004
Succeed.
SIGN =>  TestEnclave.signed.so
make[3]: Leaving directory '/build/source/Linux/sgx/test_app'
make -f sgx_u.mk test
make[3]: Entering directory '/build/source/Linux/sgx/test_app'
token_path: /build/enclave.token
Start tests
{"public":"3082020a0282020100aa412a0365a79908265cdba52ad5e61db77dd7ad823828f27f4950e3685788cb328928f3909e53ff4b3eac66408dce1b0f96dfade21ceac02a93b1217e2dd>
{"private":"308209270201000282020100aa412a0365a79908265cdba52ad5e61db77dd7ad823828f27f4950e3685788cb328928f3909e53ff4b3eac66408dce1b0f96dfade21ceac02a93b1>
test rsa_key_gen completed
{"public":"045da1d897b35fbdf5e1a736788a742f9e800669c0aaf11285be5a2d040859bb9dc82d88db35b46899b2ca0d3c63f34a53f47eb9cc7701e5fef1095c87610f9f61745c33c0b4b84>
{"private":"3081a40201010430d98c24b2e29c53a4fd9395126ec69870063a7b4f9e17a3143b3f0c61f66cf6c7733c650b1ba4017e7349d03fa047eccba00706052b81040022a16403620004>
test ec_key_gen completed
test rsa_test completed
     y^2 = x^3 + a*x + b (mod p)
A cyclic subgroup:
     point at infinity
combined multiplication ...
 ok
[...]
RUN  =>  TestApp [SIM|x64, OK]
make[3]: Leaving directory '/build/source/Linux/sgx/test_app'
make[2]: Leaving directory '/build/source/Linux/sgx/test_app'
make[1]: Leaving directory '/build/source/Linux/sgx'
make: Leaving directory '/build/source/Linux'
```

**Comment by haraldh** [comment]
Covered by https://github.com/NixOS/nixpkgs/pull/283405

**Pull request closed without merging**
