### PR TITLE
mix2nix: 0.1.8 -> 0.1.9

### PR DESCRIPTION
**Pull request by ydlr**
Adds a package-specific workaround for grpcbox.
Adds flake.nix.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes) *No significant or breaking change*
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
hey thanks a lot for contributing!

would you mind just changing the commit message to be 
`mix2nix: 0.1.8 -> 0.1.9`
(I can change the PR title, don't worry about that).
appart from that, LGTM.

**Comment by camelpunch** [comment]
@ydlr looks like we need to resolve a minor conflict in `all-packages.nix`:

```
diff --cc pkgs/top-level/all-packages.nix
index e5e355660a49,0b3b10b6f58b..000000000000
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@@ -744,9 -750,12 +744,18 @@@ with pkgs
      inherit (darwin) DarwinTools;
    };
  
++<<<<<<< HEAD
 +  mix2nix = callPackage ../development/tools/mix2nix {
 +    elixir = elixir_1_14;
 +  };
++=======
+   rtthost = callPackage ../development/tools/rust/rtthost {
+     inherit (darwin.apple_sdk.frameworks) AppKit;
+     inherit (darwin) DarwinTools;
+   };
+ 
+   mix2nix = callPackage ../development/tools/mix2nix { };
++>>>>>>> ydlr/mix2nix_0.1.9
  
    n98-magerun = callPackage ../development/tools/misc/n98-magerun { };
```

Could potentially move to a [name-based directory package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/README.md), and remove the entry from `all-packages.nix`. I did that for [another package](https://github.com/NixOS/nixpkgs/pull/278461/files).

**Comment by happysalada** [comment]
I missed your change after it was made. Feel free to tag me after you've resolved the conflict, this is good to merge.

**Comment by ydlr** [comment]
@happysalada I fixed the conflict.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 281029` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mix2nix</li>
  </ul>
</details>

**Pull request merged**
