### PR TITLE
grocy, limesurvey: mark as broken due to lack of PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by LeSuisse**
###### Description of changes

PHP 8.0 will be end-of-life during the next release cycle (and it also needs OpenSSL 1.1 which will be marked as insecure #210452). Those packages have not yet released or started working on the compatibility so they are mark as broken.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LeSuisse** [comment]
Moving this to draft until 23.05 branch-off, this is a breaking change. They will be considered insecure due to their usage of OpenSSL 1.1. We might be able to bump them to PHP 8.1 during the release cycle if new versions are released.

**Comment by sreichel** [comment]
There was some progress during last two days ;)

**Comment by LeSuisse** [comment]
Branch-off is done, this can be reviewed.

**Review by drupol — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]

**Comment by Sup3Legacy** [comment]
The Grocy README does advertise a PHP 8.1 compatibility. Maybe it can be marked as unbroken, or is there another reason?

**Comment by LeSuisse** [comment]
Their development branch announce support of PHP 8.1 since https://github.com/grocy/grocy/commit/38a4ad8ec480c29a1bff057b3482fd103b036848 but they did not release it.

**Pull request merged**
