### PR TITLE
claws-mail: remove claws-mail-gtk2 version

### PR DESCRIPTION
**Pull request by oxzi**
###### Motivation for this change
The GTK+ 2 version of Claws Mail, major version number three, relies on Python 2, which is end-of-life and might be dropped in the nixpkgs.

In favour of #148779, this older branch of Claws Mail was removed.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ajs124 — APPROVED** [review]
Changes LGTM, but didn't test.

Do you remember why we kept the gtk2 version in the first place?

**Comment by Artturin** [comment]
Gtk3 variant was added in https://github.com/NixOS/nixpkgs/commit/b0d9764c721c3f998f685e87eaec2fc70e2778fb#diff-d9036335b5ae580ad9137f12608725c778230c2cedcd55638fc1df45ff9f027c

**Comment by oxzi** [comment]
@ajs124: I recall the following, adding to @Artturin's comment:

- First, the then experimental GTK+ 3 version of Claws Mail 3.17.5 was
  added as its own derivation; b0d9764c721c3f998f685e87eaec2fc70e2778fb.
- Those two packages then both received updates, but of different
  quality, and started to diverged.
- Thus, the two packages were merged in
    - 553ad198c2005468a024e554776efd5587999261,
    - bf925400978d361e62f9d5210a6e5d620d2be050,
    - c2349bf052456733017396696286627fd061a800, and
    - e37e954d71350c1356ce381abcc7861391ff342b.
- With the [double release](https://claws-mail.org/NEWS) of Claws Mail
  3.18.0 and the first version of the GTK+ 3 branch, Claws Mail 4.0.0,
  the former experimental `claws-mail-gtk3` package became `claws-mail`,
  while the other branch became `claws-mail-gtk2`;
  26f52bf6b5d32ebdfc799a6cefc0c1d37700b67.

Maybe we should have dropped the old version right away when 4.0.0 was
released, since it probably is not used anyway. Imho, now is the second
best time to clean it up a bit again.

**Comment by oxzi** [comment]
Result of `nixpkgs-review pr 148783` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

**Pull request merged**
