### PR TITLE
switch users of "gnupg1" to plain "gnupg"

### PR DESCRIPTION
**Pull request by catern**
gnupg is gnupg 2.2. gnupg1 is also gnupg 2.2, just with a few extra
symlinks in the bin directory. None of these packages need those
symlinks, and it's confusing for them to say they're depending on
"gnupg1", so switch their dep to plain "gnupg".

I have not built any of these packages, I'm hoping to rely on ofborg.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
@GrahamcOfBorg build gnupg

**Review by matthewbauer — APPROVED** [review]

**Comment by matthewbauer** [comment]
Nice work! I am glad people are handling these. I would consider moving gnupg1 to aliases.nix if possible.

Another one that I've wanted to rename is mesa_noglu (should just be mesa).

**Comment by catern** [comment]
Yeah, ideally gnupg1 would point to what we currently call "gnupg1orig". Not sure what's the best transition strategy there. Should I delete the current gnupg1, wait a bit, and then later on rename gnupg1orig to gnugp1? Or should I do that in a single commit?

**Comment by catern** [comment]
(With either transition approach I think it's best to leave gnupg1 as it is for this change - maybe something will come up after this)

**Pull request merged**
