### PR TITLE
llvmPackages: 11 -> 16 on Darwin and Linux

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

This bumps llvmPackages on Darwin and Linux to 16, making LLVM 16.0.6 the version used by the Darwin stdenv

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by reckenrode** [comment]
I’m pretty sure it wasn’t doing that when I opened this PR, but I’ll dig into the ofborg eval failure. Fortunately, I can reproduce it locally using `outpaths.nix`.

**Comment by reckenrode** [comment]
#247066 fixes the evaluation error causing the infinite recursion. I ran `outPaths.nix` locally with that PR cherry-picked, and it evaluates correctly now.

**Comment by reckenrode** [comment]
@ofborg eval

**Comment by reckenrode** [comment]
@ofborg eval

**Comment by reckenrode** [comment]
@ofborg eval

**Comment by reckenrode** [comment]
@ofborg eval

**Comment by pwaller** [comment]
Does this need a rebase after https://github.com/NixOS/nixpkgs/pull/246577 landed a couple of day ago?

**Comment by reckenrode** [comment]
> Does this need a rebase after #246577 landed a couple of day ago?

It shouldn’t. This PR doesn’t touch any of the files that were modified in that PR, and staging should have the changes from #246577 already merged into it anyway.

**Review by phaer — APPROVED** [review]

**Comment by yu-re-ka** [comment]
What is still missing for this to be viable?

**Comment by tobim** [comment]
I guess this should get a Hydra jobset. What do you think, @vcunat?

**Comment by reckenrode** [comment]
A jobset makes sense. I’ve been trying to proactively address problems, but there’s only so much I can do building locally, and having the jobset would give visibility to the things being fixed.

I’d really hate for this to slip past 23.11. I’ve been working on it since May, and it would be great to make some progress on getting things fixed and this merged. Things are starting to have problems with the current stdenv and clang. I’m aware of three (darktable, Wine, and ladybird), but there are probably others. Getting Darwin on a regular update cycle for clang would help alleviate these problems in the long run (which is what the stdenv rework is meant to do).

Now if only clang could avoid annoyingly breaking changes in new releases ….

**Comment by tobim** [comment]
@reckenrode can you rebase onto 53bbb203e013e8fbbcddd9f205e73674475f129a for the jobset?

**Comment by reckenrode** [comment]
> @reckenrode can you rebase onto [53bbb20](https://github.com/NixOS/nixpkgs/commit/53bbb203e013e8fbbcddd9f205e73674475f129a) for the jobset?

Done.

**Comment by vcunat** [comment]
darwin still has a long queue, so only x86_64-linux for now: https://hydra.nixos.org/eval/1798976

**Comment by vcunat** [comment]
Which darwin platform do you prefer for the testing jobset?

**Comment by reckenrode** [comment]
> Which darwin platform do you prefer for the testing jobset?

x86_64-darwin. Of the PRs I’ve opened, most of the ones for architecture-specific issues were for x86_64. #253040 might have been the first one with a fix for aarch64-darwin.

**Comment by reckenrode** [comment]
I’ve started looking at the failing builds on Hydra for ones that weren’t already caught by the open PRs linked in #234710 and submitting PRs to fix them.

**Comment by reckenrode** [comment]
How frequently should I be rebasing this PR? Some of the fixes have been merged.

**Comment by vcunat** [comment]
Probably not too often, as it would cause a full rebuild.

**Comment by reckenrode** [comment]
> Probably not too often, as it would cause a full rebuild.

Right, but there’s stuff that could build now that’s broken. Aside from finding breakage, I’m assuming one of the other reasons for having a builder is to have a publicly visible way to see what builds or not to inform when to merge this.

Is as staging-next lands a good rule of thumb to avoid too many rebuilds?

**Comment by vcunat** [comment]
`staging-next` merges will be the main events bringing new rebuilds to this jobset.  They will almost always rebuild everything of "the diff" (~45k on x86_64-darwin, ~17k x86_64-linux).  Doing it on every `staging-next` merge would probably be excessive, but I think you've already skipped one, so some time this week sounds OK to me if you think it's useful.

**Comment by tobim** [comment]
Would it make sense to switch the strategy to cherry-picking the merged fixes into this branch at some point?

**Comment by vcunat** [comment]
LLVM 17 is here 🎉 
_Just a tangent; no impact on this PR expected whatsoever._

**Comment by reckenrode** [comment]
I rebased on a8be39d4a9124d113edcd15bc8bace3804d51872. When I updated my local branch, it dropped about 20+ commits I’d cherry-picked from fixes.

**Review by toonn — APPROVED** [review]
LGTM

**Comment by trofi** [comment]
`git bisect` says that `firefox` on `x86_64-linux` fails to build on `staging` and `staging` next due to `pkgsCross.wasi32.stdenv` build failure:

```
$ nix build --no-link -f. pkgsCross.wasi32.stdenv
...
error: builder for '/nix/store/5vj8p42his10xf8s2wp1ddc4aam87r5r-compiler-rt-static-wasm32-unknown-wasi-16.0.6.drv' failed with exit code 1;
       last 10 log lines:
       > [147/148] Building C object lib/builtins/CMakeFiles/clang_rt.builtins-wasm32.dir/clear_cache.c.obj
       > clang-16: warning: argument unused during compilation: '-nostartfiles' [-Wunused-command-line-argument]
       > [148/148] Linking C static library lib/wasi/libclang_rt.builtins-wasm32.a
       > installing
       > install flags: -j16 install
       > [0/1] Install the project...
       > -- Install configuration: "Release"
       > -- Installing: /nix/store/fmry8zba9lydj5zllfawqdx4wfpcqwqr-compiler-rt-static-wasm32-unknown-wasi-16.0.6/lib/wasi/libclang_rt.builtins-wasm32.a
       > ln: failed to create symbolic link './crtbeginS.o': File exists
       > /nix/store/4ly5ar302prwivx61qac1s672if8y5v9-stdenv-linux/setup: line 133: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/5vj8p42his10xf8s2wp1ddc4aam87r5r-compiler-rt-static-wasm32-unknown-wasi-16.0.6.drv'.
error: 1 dependencies of derivation '/nix/store/1ip32z2qbqw67x4bbvz635ix57m580ki-wasm32-unknown-wasi-clang-wrapper-16.0.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xd3p6kc0yi31664jcbr37p7b7vys28gc-stdenv-linux.drv' failed to build
```

**Comment by reckenrode** [comment]
I’ll take a look at the Firefox issue later today when I have some bandwidth.

**Comment by reckenrode** [comment]
> The lines at issue are these ones:
> 
> https://github.com/NixOS/nixpkgs/pull/246577/files#diff-74e339544ee34942416cbd283da8e713600dbf0f7e0a97e43a9a5d4e54777351R131-R132
> 
> I think maybe this needs protecting with a `&& !stdenv.hostPlatform.isWasm`, because clang_rt.crt*.o don't appear to exist if I build it manually.

I tried that, but it didn’t actually work (see below).

> I don't know why it worked before the 11 -> 16 migration though, since llvmPackages_11.compiler-rt also appears to have these symlinks commands in it.

Something changed LLVM-side. The failure appears to be coming from their build system. I dug into it a bit over lunch but ran out of time. I’ll have some more bandwidth later today to look at it more closely. I plan to do that first before getting back to some of the other failures in Hydra.

**Comment by alyssais** [comment]
I've looking at a couple of regressions from this:

- pkgsCross.x86_64-freebsd.stdenv can no longer build, due to compiler-rt failing
- spirv-llvm-translator no longer cross compiles

I'd appreciate any help anybody could give.  Usually I'd try bisecting LLVM, but the GNU install dirs patches make inter-version bisects of LLVM quite difficult.

**Comment by alyssais** [comment]
Found a fix for spirv-llvm-translator: #265107

**Comment by reckenrode** [comment]
@alyssais The FreeBSD failure looks like the same one as the wasi32 failure (fixed in #263876)

**Comment by amjoseph-nixpkgs** [comment]
The Darwin `stdenvBootstrapTools` are not regenerating on Hydra; @reckenrode do you have any insights?

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

https://hydra.nixos.org/build/239434541

Logfile: https://hydra.nixos.org/log/6dk492xqalbr20m5r6y54h36x27jmm0v-test.drv

```
ar cr lib/libhello.a lib/basename-lgpl.o lib/c-ctype.o lib/c-strcasecmp.o lib/c-strncasecmp.o lib/cloexec.o lib/close-stream.o lib/closeout.o lib/dirname.o lib/basename.o lib/dirname-lgpl.o lib/stripslash.o lib/exitfail.o lib/fd-hook.o lib/getprogname.o lib/hard-locale.o lib/localcharset.o lib/malloca.o lib/mbchar.o lib/mbiter.o lib/mbslen.o lib/mbsstr.o lib/mbuiter.o lib/progname.o lib/propername.o lib/quotearg.o lib/setlocale_null.o lib/stat-time.o lib/striconv.o lib/strnlen1.o lib/trim.o lib/unistd.o lib/unistr/u8-mbtoucr.o lib/unistr/u8-uctomb.o lib/unistr/u8-uctomb-aux.o lib/uniwidth/width.o lib/version-etc.o lib/version-etc-fsf.o lib/wctype-h.o lib/xmalloc.o lib/xalloc-die.o lib/xstriconv.o lib/xstrndup.o lib/error.o lib/fpending.o lib/getopt.o lib/getopt1.o lib/open.o lib/setlocale-lock.o lib/stat.o lib/strerror.o lib/strerror-override.o lib/wcwidth.o
dyld[74464]: missing symbol called
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ar cr lib/libhello.a lib/basename-lgpl.o lib/c-ctype.o lib/c-strcasecmp.o lib/c-strncasecmp.o lib/cloexec.o lib/close-stream.o lib/closeout.o lib/dirname.o lib/basename.o lib/dirname-lgpl.o lib/stripslash.o lib/exitfail.o lib/fd-hook.o lib/getprogname.o lib/hard-locale.o lib/localcharset.o lib/malloca.o lib/mbchar.o lib/mbiter.o lib/mbslen.o lib/mbsstr.o lib/mbuiter.o lib/progname.o lib/propername.o lib/quotearg.o lib/setlocale_null.o lib/stat-time.o lib/striconv.o lib/strnlen1.o lib/trim.o lib/unistd.o lib/unistr/u8-mbtoucr.o lib/unistr/u8-uctomb.o lib/unistr/u8-uctomb-aux.o lib/uniwidth/width.o lib/version-etc.o lib/version-etc-fsf.o lib/wctype-h.o lib/xmalloc.o lib/xalloc-die.o lib/xstriconv.o lib/xstrndup.o lib/error.o lib/fpending.o lib/getopt.o lib/getopt1.o lib/open.o lib/setlocale-lock.o lib/stat.o lib/strerror.o lib/strerror-override.o lib/wcwidth.o 
0  libLLVM.dylib            0x00000001097b3264 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 68
1  libLLVM.dylib            0x00000001097b2220 llvm::sys::RunSignalHandlers() + 112
2  libLLVM.dylib            0x00000001097b3aec SignalHandler(int) + 388
3  libsystem_platform.dylib 0x000000018dc1ea24 _sigtramp + 56
4  dyld                     0x000000018d910d7c abort_with_payload_wrapper_internal + 104
5  dyld                     0x000000018d910db0 dyldVersionString + 0
6  dyld                     0x000000018d89c8a8 dyld4::CacheFinder::~CacheFinder() + 0
7  dyld                     0x000000018d8d2770 dyld4::APIs::_tlv_atexit(void (*)(void*), void*) + 0
8  ar                       0x0000000104acb3bc
9  ar                       0x0000000104ac904c
10 dyld                     0x000000018d897f28 start + 2236
make[2]: *** [Makefile:2161: lib/libhello.a] Killed: 9
make[2]: Leaving directory '/private/tmp/nix-build-test.drv-0/hello-2.12.1'
make[1]: *** [Makefile:2496: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-test.drv-0/hello-2.12.1'
make: *** [Makefile:1899: all] Error 2
```

**Comment by reckenrode** [comment]
@amjoseph-nixpkgs No, not off hand. I’d need to reproduce the failure locally and check if it’s linked to the wrong dylibs or something to that effect. The Darwin stdenv doesn’t require updated bootstrap tools for an LLVM update anymore, so this shouldn’t affect the update, but it’s still something that should be looked at and fixed.

**Comment by toonn** [comment]
@amjoseph-nixpkgs, looked into the issue, I'll be opening a PR shortly if the fix works.

**Comment by szlend** [comment]
Nickel (a Rust project with some c++ deps) is failing to link some really basic symbols like `"operator new(unsigned long)"` after the upgrade to LLVM 16 on Darwin (https://github.com/NixOS/nixpkgs/issues/268777). Any advice on what to look for? I'm looking at the `NIX_DEBUG=1` output and it does appear to be linking with `libcxx`/`libcxxabi` so I'm not sure what else to check for.

**Pull request merged**
