### PR TITLE
uwsgi: fix cross-compilation

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Allows uwsgi to be cross-compiled. I've built and tested the python3 plugin.

cc @abbradar @schneefux @globin 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113242` at 1e54261f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/c989d67ff42435891664c791d51a7c62">uwsgi</a></li></li>
  </ul>
</details>
<details>
  <summary>7 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/uwsgi/default.nix:70:9:
```
   |
70 |         ./no-ext-session-php_session.h-on-NixOS.patch
   |         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/uwsgi/default.nix:71:9:
```
   |
71 |         ./additional-php-ldflags.patch
   |         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/servers/uwsgi/default.nix:116:3:
```
    |
116 |   buildPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/servers/uwsgi/default.nix:101:3:
```
    |
101 |   configurePhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/servers/uwsgi/default.nix:122:3:
```
    |
122 |   installPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/servers/uwsgi/default.nix:130:5:
```
    |
130 |     license = licenses.gpl2;
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `libmysqlclient`.
Near pkgs/servers/uwsgi/default.nix:8:14:
```
  |
8 | , ruby, php, libmysqlclient
  |              ^
```
</li>
  </ul>
</details>

**Comment by lopsided98** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.uwsgi

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113242` at 1e54261f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/97e7805c46296fb049116734c26d3be1">cutelyst</a></li></li>
    <li><a href="https://gist.github.com/587212479bdaaab0590dd404cebb937e">uwsgi</a></li></li>
    <li><a href="https://gist.github.com/0860d24370693da3af42ac9fbfa5e3ac">virtlyst</a></li></li>
  </ul>
</details>
<details>
  <summary>7 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/uwsgi/default.nix:70:9:
```
   |
70 |         ./no-ext-session-php_session.h-on-NixOS.patch
   |         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/uwsgi/default.nix:71:9:
```
   |
71 |         ./additional-php-ldflags.patch
   |         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/servers/uwsgi/default.nix:116:3:
```
    |
116 |   buildPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/servers/uwsgi/default.nix:101:3:
```
    |
101 |   configurePhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/servers/uwsgi/default.nix:122:3:
```
    |
122 |   installPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/servers/uwsgi/default.nix:130:5:
```
    |
130 |     license = licenses.gpl2;
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `libmysqlclient`.
Near pkgs/servers/uwsgi/default.nix:8:14:
```
  |
8 | , ruby, php, libmysqlclient
  |              ^
```
</li>
  </ul>
</details>

**Review by SuperSandro2000 — COMMENTED** [review]
diff LGTM and cross compiles from amd64.

**Pull request merged**
