### PR TITLE
rustc: 1.66.1 -> 1.67.0

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html

built fd and dump_syms on {aarch64,x86_64}-linux
built fd on master on {aarch64,x86_64}-darwin without the llvm update

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/blob/2d449e846ab662913b79e351e70546bf94857232/pkgs/development/compilers/rust/1_67.nix#L10

These won't build on master with 1.67.0, `dump_syms` build failure?

**Comment by winterqt** [comment]
Got logs, @zowoq? (How long does it take to bail out, anyways?)

**Comment by figsoda** [comment]
```
   Compiling dump_syms v2.1.1 (/build/source)
error: failed to parse bitcode for LTO module: Explicit gep type does not match pointee type of pointer operand (Producer: 'LLVM14.0.6' Reader: 'LLVM 14.0.6')

error: could not compile `reqwest` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `dump_syms` due to previous error
```
it doesn't take long to bail out if you build `dump_syms` directly

**Comment by figsoda** [comment]
I can reproduce this outside of nix sandbox with `cargo build --release` in the dump_syms repo

**Comment by figsoda** [comment]
some searching lead me to https://github.com/rust-lang/rust/issues/100474
this might require llvm 15, I can't reproduce this error with binarily distributed rust 1.67.0 with fenix (updated locally, not upstream yet) that has llvm 15

not sure if there is a good way to fix this other than waiting for #191132, I have not seen a `dump_syms` issue which suggests that this update could break other packages as well

**Comment by zowoq** [comment]
cc @mweinelt `dump_syms` / `firefox`

**Comment by lblasc** [comment]
I can confirm working firefox build on 1.67+llvm15(#191132).

**Comment by winterqt** [comment]
We should probably switch to LLVM 15 (which is what upstream uses) now anyways, so let's just do it.

**Comment by mweinelt** [comment]
Please make sure both go into the same staging cycle, as otherwise firefox will rightfully block the channel.

**Comment by winterqt** [comment]
> Please make sure both go into the same staging cycle, as otherwise firefox will rightfully block the channel.

(I don't see why we shouldn't just put them both in this PR, unless you think otherwise?)

**Comment by mweinelt** [comment]
I have no strong feelings about how to handle the two, feel free to do what works best for you.

**Comment by figsoda** [comment]
> I don't see why we shouldn't just put them both in this PR

Did you mean including the llvm update in this PR, or switching to llvm 15 in this PR once it has been added. I am thinking that we do the latter instead

**Comment by winterqt** [comment]
> > I don't see why we shouldn't just put them both in this PR
> 
> Did you mean including the llvm update in this PR, or switching to llvm 15 in this PR once it has been added. I am thinking that we do the latter instead

Sorry, was under the impression that we landed the bump already. What I meant was the latter, yup.

I think we should mark this as draft until the bump has landed in staging, which should be very soon judging by the recent discussions over there.

**Comment by figsoda** [comment]
rebased and updated to llvm 15, trying to build dump_syms

**Comment by trofi** [comment]
Bisect says 63f869f5ff10b570fcf3a0d002a7aa25938f6f9f `rustc: 1.66.1 -> 1.67.0` broke `mesa` build as:

```
mesa> FAILED: src/gallium/frontends/rusticl/libmesa_rust_gen.rlib
mesa> rustc -C linker=gcc --color=always --crate-type rlib --edition=2021 -g -C relocation-model=pic --crate-name mesa_rust_gen --emit dep-info=src/gallium/frontends/rusticl/mesa_rust_gen.d --emit link -Aclippy::all -Anon_snake_case -Anon_camel_case_types -Anon_upper_case_globals -o src/gallium/frontends/rusticl/libmesa_rust_gen.rlib -l static=gallium -l static=libclc -l dylib=drm -L/nix/store/b1wsi4cgaa8z2shavljy6b2xgv0ry4f8-llvm-15.0.7-lib/lib -l dylib=LLVM-15 -l dylib=m -l dylib=z -l dylib=clang-cpp -L/nix/store/b1wsi4cgaa8z2shavljy6b2xgv0ry4f8-llvm-15.0.7-lib/lib -l dylib=LLVM-15 -l dylib=LLVMSPIRVLib -l dylib=z -l dylib=m -L src/gallium/auxiliary -L src/compiler/clc -L /nix/store/fi50i5ylcyivbhhycsaz3jrxlr7zqm5v-libdrm-2.4.114/lib -L /nix/store/h5cq2sbsmhlpl2apg4dw4hvksrg8adwx-zlib-1.2.13/lib -L /nix/store/ingcnm6snwasnis754fxdfnmfa0fl80p-clang-15.0.7-lib/lib -L /nix/store/94hkq499qbg2zhks6y9zd8z3m32h3smb-SPIRV-LLVM-Translator-15.0.0/lib src/gallium/frontends/rusticl/rusticl_mesa_bindings.rs
mesa> error: failed to add native library src/gallium/auxiliary/libgallium.a: Unsupported archive identifier
mesa> error: aborting due to previous error
```

**Comment by trofi** [comment]
https://github.com/rust-lang/rust/issues/107334 looks related (rust-1.67 regressed in thin static archive handling, fixed in `master`).

**Comment by figsoda** [comment]
https://github.com/NixOS/nixpkgs/pull/213873

**Pull request merged**
