### PR TITLE
python3Packages.tzlocal: 2.1 -> 4.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Version 4 is compatible with APScheduler again: https://github.com/regebro/tzlocal#api-change

`python38Packages.pytz-deprecation-shim` fails to build due to a lot of flaky tests. Should we mark it as broken or try to disable all tests that we ever see fail?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@NixOS/nixops-committers This will disable the `nixops` package. Feel free to push a fix to my branch.

**Comment by dotlambda** [comment]
@roberth Why did you modify `default.nix`? Also note that you should use `python2-packages.nix` and use a proper commit message.

**Comment by roberth** [comment]
Well I was trying to be helpful but I messed up.
I'm not familiar with python packaging. I only maintain NixOps 2, which doesn't use pythonPackages. It's probably faster for you to do it than to correct my mistakes. I've removed my bad commit.

**Comment by dotlambda** [comment]
ping @mweinelt @jonringer

**Comment by pjjw** [comment]
for the record, this broke the package on aarch64-darwin

**Comment by mweinelt** [comment]
> for the record, this broke the package on aarch64-darwin

Please provide a log of the resulting breakage.

**Pull request merged**
