### PR TITLE
perlPackages.TextBibTeX: fix dylib path for Darwin

### PR DESCRIPTION
**Pull request by boronine**
###### Motivation for this change

The package `pkgs.perlPackages.TextBibTeX` didn't work on Darwin due to the (common) dylib location issue.

###### Things done

This package comes with a 1 dylib and 3 executables. I used `install_name_tool` to patch the binaries to switch the dylib location from the build directory (wrong) to the final Nix store directory (right).

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by boronine** [comment]
Forgot to patch `.bundle` file in original commit. Fixed and re-tested.

**Comment by boronine** [comment]
@vcunat

**Comment by vcunat** [comment]
I'm no good with Darwin stuff.

**Comment by vcunat** [comment]
@GrahamcOfBorg perlPackages.TextBibTeX

**Comment by vcunat** [comment]
@GrahamcOfBorg build perlPackages.TextBibTeX

**Pull request merged**
