### PR TITLE
kproperty,kreport,kexi: 3.1.0 -> 3.2.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
Does it build for you?
I get:

```
CMake Error at CMakeLists.txt:159 (find_package):
  Could not find a configuration file for package "KDb" that is compatible
  with requested version "3.1.91".

  The following configuration files were considered but not accepted:

    /nix/store/c1k1ajs9r720wn0r7gd2v0ynlp7zcfbw-kdb-3.1.0/lib/cmake/KDb3/KDbConfig.cmake, version: 3.1.0
```

**Comment by JohnAZoidberg** [comment]
Still failing, even after the other upgrade :P

```
  Could not find a configuration file for package "KReport" that is
  compatible with requested version "3.1.91".

  The following configuration files were considered but not accepted:

    /nix/store/jaz8ph7hl24v7gsl8gvdqnavkzram7h1-kreport-3.1.0/lib/cmake/KReport3/KReportConfig.cmake, version: 3.1.0



CMake Error at CMakeLists.txt:179 (find_package):
  Could not find a configuration file for package "KPropertyWidgets" that is
  compatible with requested version "3.1.91".

  The following configuration files were considered but not accepted:

    /nix/store/j0l85n15kpj3dgdq9l6jpw5bm6zc60qi-kproperty-3.1.0/lib/cmake/KPropertyWidgets3/KPropertyWidgetsConfig.cmake, version: 3.1.0                                                                                                      
```

**Comment by dtzWill** [comment]
D'oh, sorry i tested mostly with the entire upgrade stack and split for PR's.

From the posted log, looks like also needs #60047 and #60048 ?

**Comment by JohnAZoidberg** [comment]
Yeah, looks like it.
Hmm, if they're all that interdependent would upgrading these packages break other packages?

**Comment by dtzWill** [comment]
Hmm, don't think so re:breakage-- quick grep suggests kreport and kproperty are only used in calligra (long since broken) and this package, kexi.  So maybe they should be all upgraded together, yes! :).

**Comment by dtzWill** [comment]
@GrahamcOfBorg kexi

**Comment by JohnAZoidberg** [comment]
`nix-review` says it's fine now :)
Builds fine but can't find the `breeze-icons`.
I think #54525 would fix that.

**Comment by dtzWill** [comment]
Agreed, runs fine here.  Thanks for testing!

**Pull request merged**
