### PR TITLE
ccl and sbcl updated, tested on nixos x86_64

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build ccl sbcl

**Comment by tohl** [comment]
@GrahamcOfBorg you can add x86_64-darwin and i686-darwin to options in a
similar way as x86_64-linux and i686-linux are set up, e.g.:

    x86_64-darwin = {
      arch = "darwinx86";
      sha256 = "0f8rcklw6279p88zmk60d3s48f31qs0zfhfi62pjjbjaicyymnss";
      runtime = "dx86cl64";
      kernel = "darwinx8664";
    };
    i686-darwin = {
      arch = x86_64-darwin.arch;
      sha256 = x86_64-darwin.sha256;
      runtime = "dx86cl";
      kernel = "darwinx8632";
    };

arch, sha256 and runtime should be correct, don't know about kernel.

I have no way to test this, so I will not add darwin support to ccl.

**Comment by Mic92** [comment]
@tohl this is not an actual person but our CI.

**Comment by tohl** [comment]
@Mic92 cool, that's new to me.  good to know, thanks

**Pull request merged**
