### PR TITLE
nixos/bcachefs: skip loading key if we already have it

### PR DESCRIPTION
**Pull request by lheckemann**
## Description of changes

This approach isn't ideal, but I'm not aware of any way of checking if the correct key for a filesystem is already loaded. I've asked about this on the bcachefs IRC and maybe we'll have something at some point, but until then maybe this approach makes sense.

This also still produces multiple prompts if the same filesystem is mounted in multiple places, though unlocking the filesystem succeeds if the passphrase is typed in the first time and the remaining prompts are dismissed with a blank entry. Maybe it would make more sense to have an unlock service per device rather than per mountpoint?

Thoughts?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
This ^ and I believe on non-encrypted systems, this should not be trying to unlock it in the first place.

```
❯  journalctl -b | grep stage-1-init
May 29 00:25:18 Ainz-NIX stage-1-init: [Tue May 28 18:55:08 UTC 2024] Starting systemd-udevd version 255.6
May 29 00:25:18 Ainz-NIX stage-1-init: [Tue May 28 18:55:08 UTC 2024] starting device mapper and LVM...
May 29 00:25:18 Ainz-NIX stage-1-init: [Tue May 28 18:55:09 UTC 2024] waiting for device to appear UUID=7594aea3-de1f-466c-8420-3c7e4997fb34
May 29 00:25:18 Ainz-NIX stage-1-init: [Tue May 28 18:55:09 UTC 2024] Cannot unlock device 7594aea3-de1f-466c-8420-3c7e4997fb34 with path /dev/nvme0n1p7
May 29 00:25:18 Ainz-NIX stage-1-init: [Tue May 28 18:55:09 UTC 2024] mounting UUID=7594aea3-de1f-466c-8420-3c7e4997fb34 on /...
```

**Comment by lheckemann** [comment]
@JohnRTitor indeed, it won't prompt for unencrypted filesystems due to the `ExecCondition` on the unit. This PR is meant to address filesystems that are encrypted, but mounted to multiple mount points. These currently result in a prompt per mount point, when one for the whole filesystem would be enough.

Also, your logs suggest that you're not using systemd stage-1, and I've only touched the systemd stage-1 implementation here.

**Comment by JohnRTitor** [comment]
Mount bcachefs root in systemd-stage-1 does not even work on my system. Is it working for you?

I am using a pretty [simple setup](
https://github.com/JohnRTitor/nix-conf/blob/hyprland/default-host/hardware-configuration.nix#L20-L23) with `defaults` and `noatime` mount options.

**Comment by JohnRTitor** [comment]
Identified the problem, [changing the fstab](https://github.com/JohnRTitor/nix-conf/commit/70df9aa2825839c9c6af0411af859152d9fa6979) to use `/dev/disk/by-uuid/UUID` format successfully lets systemd-initrd mount a bcachefs partition.

```patch
diff --git a/default-host/hardware-configuration.nix b/default-host/hardware-configuration.nix
index 0305bb69..ce093690 100644
--- a/default-host/hardware-configuration.nix
+++ b/default-host/hardware-configuration.nix
@@ -18,7 +18,7 @@
   boot.extraModulePackages = [];
 
   fileSystems."/" = {
-    device = "UUID=7594aea3-de1f-466c-8420-3c7e4997fb34";
+    device = "/dev/disk/by-uuid/7594aea3-de1f-466c-8420-3c7e4997fb34";
     fsType = "bcachefs";
   };
```

This might not be related to this particular PR, but I hope affected bcachefs users will find this fix helpful.

**Comment by lheckemann** [comment]
That's a systemd bug which will be fixed in v256: https://github.com/systemd/systemd/issues/28989

**Comment by ElvishJerricco** [comment]
@lheckemann Kind of... I just made an issue about why that's not really going to fix things: https://github.com/NixOS/nixpkgs/issues/317901

**Review by ElvishJerricco — CHANGES_REQUESTED** [review]
> but I'm not aware of any way of checking if the correct key for a filesystem is already loaded.

Do you think we could check the kernel keyring somehow? I'm *very* inexperienced with the keyring. If not, this is a case where I honestly think we should fix it upstream and add the necessary flag / command to bcacehfs.

**Comment by JohnRTitor** [comment]
Related PR which got merged upstream: https://github.com/koverstreet/bcachefs-tools/pull/263

**Comment by ElvishJerricco** [comment]
Oh, well there we go. I was about to say that you *can* actually check with `keyctl`, but it seemed frustrating to parse out and all that so I'd rather just fix it upstream. But we don't have to! Nice.

@JohnRTitor Any chance of getting a subcommand or `unlock` flag to do this check? It'd be great to have that in the `ExecCondition`. As is we'll still needlessly re-invoke clevis, which might be troublesome.

**Comment by lheckemann** [comment]
> > but I'm not aware of any way of checking if the correct key for a filesystem is already loaded.
> 
> Do you think we could check the kernel keyring somehow? I'm _very_ inexperienced with the keyring. If not, this is a case where I honestly think we should fix it upstream and add the necessary flag / command to bcacehfs.

We could, using keyctl, but I'm not sure the key description (~name), which is something like `bcachefs:bde20fb2-d752-4610-8147-83fb54a81146`, is a "public API". This is probably worth discussing with the bcachefs people as well; it would also be nice if `bcachefs unlock` could [optionally] be a no-op if the key is already loaded.

**Comment by JohnRTitor** [comment]
> @JohnRTitor Any chance of getting a subcommand or `unlock` flag to do this check? 

Good idea, perhaps Tom (upstream contributor) can chip in @tmuehlbacher

**Comment by tmuehlbacher** [comment]
Yes, I plan to add something like `unlock --dry-run` or as a separate command when I convert the unlock subcommand to Rust.
(It's not like I am a huge contributor though, just btw. But hoping I'll get to it soon.)

**Pull request closed without merging**
