### PR TITLE
Mark packages as broken for 18.03 (generic+x86_64)

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

Cleanup for 18.03, see ZHF #36453 - please backport.

Mark remaining packages that haven't built on 18.03 for a while as broken.
This PR only includes packages that don't build on master either, hence it targets master.
Any packages that build on master but not on 18.03 will be dealt with separately.

Packages will be incrementally added here.

/cc @vcunat @fpletz

### CODE REVIEW

**Comment by xeji** [comment]
@vcunat I'm done with this for now - please review.

**Comment by xeji** [comment]
rebased because of merge conflict

**Review by peti — APPROVED** [review]
The Haskell-related part looks good to me.

**Review by zimbatm — APPROVED** [review]
:+1:

**Comment by vcunat** [comment]
Pushed to both branches.  Thanks!

**Pull request merged**
