### PR TITLE
kdepim: init at 16.04.2

### PR DESCRIPTION
**Pull request by vandenoever**
###### Motivation for this change

Add kdepim (kontact, kmail) to kde5.

This patch is not yet ready. It does not even compile. There is a large issue: qtwebkit is required which was available until qt 5.6. Currently, NixPkgs master uses Qt 5.6 for KDE which makes it impossible to compile kdepim. Explicitly linking to qt55.qtwebkit does not work either.

TODO: check licenses on the new packages.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/pull/13462.

**Comment by vandenoever** [comment]
These packages need qtwebkit: kdepimlibs, messagelib, kdepim, libksieve. They might all work with
```
  cmakeFlags = [ "-DQTWEBENGINE_EXPERIMENTAL_OPTION=True" ];
```

**Comment by FRidh** [comment]
Did you intend to close this?

**Comment by vandenoever** [comment]
yes, continuing on #16537. Doing the whole kdepim in one go is very many packages and qtwebengine is required. While that is now enabled in master, it's still not working well. So I prefer to let people take a serious look at only the packages that do build fine. The downside is that, apart from akonadi, it is only libraries.

**Pull request closed without merging**
