### PR TITLE
tdesktop: 2.8.3 -> 2.8.4

### PR DESCRIPTION
**Pull request by Kranzes**
###### Motivation for this change
Update to the latest version at the time of making this PR.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@Kranzes would you also be interested to become a maintainer for `tdestkop` (i.e. regularly performing updates and respoinding to issues/PRs)?

**Comment by Kranzes** [comment]
I have got the time to update tdesktop, but i dont have the knowledge to tinker with it and fix bugs of tdesktop in nixpkgs.

**Comment by primeos** [comment]
Ok, thanks for the quick reply and this PR :) In that case it's probably best to wait for another maintainer as this package can sometimes be tricky to maintain.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 129134` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tdesktop</li>
  </ul>
</details>

**Comment by siraben** [comment]
I'll leave the PR open, another maintainer for a (guessing here) popular package would be nice.

**Review by primeos — APPROVED** [review]

**Comment by primeos** [comment]
> I'll leave the PR open, another maintainer for a (guessing here) popular package would be nice.

Unfortunately that approach doesn't really seem to work (at lest for me so far) and we should probably not delay this PR. But I agree with the idea and thanks for the review.

**Comment by DearRude** [comment]
@primeos tdesktop only uses mono-spaced fonts after this update...

**Comment by Kranzes** [comment]
From my testing it is not related to to this update, Its something with the unstable channel.
image
image

**Comment by primeos** [comment]
Could be triggered by some Fontconfig change (seems a likely candidate), see https://github.com/NixOS/nixpkgs/issues/129733#issuecomment-877287221. Shouldn't be related to this update (@Kranzes and I tested it).

**Pull request merged**
