### PR TITLE
pythonPackages.swagger-spec-validator: init at 2.4.3

### PR DESCRIPTION
**Pull request by vanschelven**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
Again, as in https://github.com/NixOS/nixpkgs/pull/62668, this isn't actually picking up any tests.

```
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by vanschelven** [comment]
Tests are not packaged (excluded in `setup.py`); I've switched to `doCheck=false`

**Comment by risicle** [comment]
> Tests are not packaged

In these cases I tend to use `fetchFromGitHub` to grab the source instead - usually the authors keep tags corresponding to version numbers.

**Comment by worldofpeace** [comment]
I'd like to also mention, if the recent python packaging pr's are for a common feature or goal you can group them into one pr. That allows the reviews to converge quickly.

**Comment by vanschelven** [comment]
> > Tests are not packaged
> 
> In these cases I tend to use `fetchFromGitHub` to grab the source instead - usually the authors keep tags corresponding to version numbers.

Done, with running tests now.

**Review by worldofpeace — APPROVED** [review]
Builds on all interpreters in nixpkgs, pushed nitpicks.

**Pull request merged**
