### PR TITLE
staging-next 2024-03-13

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/292500
- - - 
##### Mass breakages

### CODE REVIEW

**Comment by vcunat** [comment]
- [ ] `python311Packages.debugpy` regressed tests on *-darwin (but it's OK on 3.12 and on *-linux)
  https://hydra.nixos.org/build/253166753
  https://hydra.nixos.org/build/253209428
  Maintainer: @kira-bruneau
  Possibly due to the patch-level update in 120667371dfe6 from @mweinelt.

**Comment by mweinelt** [comment]
The debugpy tests are a mess. They don't fail on linux right now because you disabled them in the last staging cycle. Kira does not seem to have time to look into them right now, so we should disable them altogether for now.

**Comment by kira-bruneau** [comment]
Yeah I've found the debugpy tests to be pretty flaky. Every time I've thought I've tackled the flakiness, the tests pass on my machine, but then often time out (and now hang) when other people try to build it.

For 1.8.1, I think it's just failing because it's [missing numpy](https://github.com/microsoft/debugpy/commit/b9b09e662fc6e8aa69de611d28e40b61137288cb#diff-27c5febcc9ce93e8e5341f263b7d68962733b8a2a86c583723d025a1db39d7a3R18). Maybe it would be best to disable the tests altogether though? It's been frustrating to have it build on my machine, and then see a bunch of people run into issues when I can't consistently reproduce them myself.

**Comment by kira-bruneau** [comment]
I've opened a separate PR here that should fix debugpy 1.8.1: https://github.com/NixOS/nixpkgs/pull/296478, and also more generally disables attach_pid tests.

**Comment by vcunat** [comment]
We still have significant amount of regressions:
https://hydra.nixos.org/eval/1805057?compare=1805055#tabs-now-fail

At a quick glance, lots due to the `python-updates` merge.

**Pull request merged**
