### PR TITLE
nodejs: use .finalPackage for ease of overriding

### PR DESCRIPTION
**Pull request by bryango**
## Description of changes

**Note:** This _should_ be a trivial refactor with no rebuild (tested locally). Ofborg agrees.

Previously, the nodejs `passthru.pkgs` attribute refers to the package fixed point derived in the current context, without considering potential overrides to the main nodejs package.

This is fixed here with the `.finalPackage` attribute, which refers to the final package fixed point, after potential overrides.

For example, previously, after overriding nodejs with `nodejs.override`, `nodejs.pkgs` would still refer to the original package, instead of the overridden one. After this fix, `nodejs.pkgs` would be correctly based on the overridden `nodejs` package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bryango** [comment]
The patch is designed to have minimal code changes so that it would not interfere with ongoing projects such as #327653.

**Review by doronbehar — COMMENTED** [review]
Looks good and well done for making the diff so small. However, I personally think the final result will look better if you'd replace the `self` usages with `finalAttrs.finalPackage`. I understand that this will enlarge the diff, so probably it will be better to do it after https://github.com/NixOS/nixpkgs/pull/327653 is merged, or perhaps ask the author of https://github.com/NixOS/nixpkgs/pull/327653 to add such a change to their PR.

**Comment by tie** [comment]
>However, I personally think the final result will look better if you'd replace the `self` usages with `finalAttrs.finalPackage`. I understand that this will enlarge the diff, so probably it will be better to do it after https://github.com/NixOS/nixpkgs/pull/327653 is merged, […]

The aforementioned PR already removes unnecessary uses of `self`, leaving us with `pkgs` attribute and tests. For this, I’ve been thinking that we could use `nodejs` argument from `callPackage` (perhaps with an explicit `__splicedPackages` where needed) because splicing does not work for `finalAttrs.finalPackage`. That said, splicing also doesn’t for with `self`, so this change looks OK to me. And thanks for making this change small!

**Comment by bryango** [comment]
Thank you! If the related changes can be directly incorporated into #327653, that would be great! This PR simply serves as a proof that such change would lead to no rebuild, as confirmed by ofborg.

**Comment by doronbehar** [comment]
If this PR is urgent for you @bryango we can merge this, and at https://github.com/NixOS/nixpkgs/pull/327653 they would deal with potential merge conflicts / rebasing issues after `master` will be merged into `staging`.

**Comment by bryango** [comment]
I am okay with either way! I do need this PR right now, but I can easily work around the issue by manually overriding `passthru.pkgs`, therefore it is not so urgent. I will leave you (tie and doron) to decide whether to merge this as-is or to wait for a better version later on! :wink:

**Comment by tie** [comment]
I’m OK with merging this now, doesn’t look like there would be any conflicts. I’d like to avoid PR #327653 becoming de-facto fork of Node.js package, even if temporarily 😅
Nixpkgs review process for non-trivial changes is already slow as hell and occasionally adding small changes on top wouldn’t help with that.

**Review by aduh95 — APPROVED** [review]

**Comment by doronbehar** [comment]
> I’d like to avoid PR #327653 becoming de-facto fork of Node.js package, even if temporarily 😅

What do you mean by making the PR a de-facto fork? Do you mean you use a Nixpkgs fork with #327653 applied to it?

**Comment by tie** [comment]
>What do you mean by making the PR a de-facto fork?

This PR significantly improves build times and fixes some platform support issues we’ve had before (i.e. being unable to compile between platforms with different bitness), so I assume that some people might rely on it.

**Pull request merged**
