### PR TITLE
Add 'target' parameter for GRUB installation chain

### PR DESCRIPTION
**Pull request by ts468**
Allow GRUB 2 to be installed as EFI and non-EFI target at the same time.

### CODE REVIEW

**Comment by ts468** [comment]
PLEASE check the changes carefully before merging!
I've tested grub locally where it builds and installs properly. But I don't want to ruin someone else's system.

**Comment by MP2E** [comment]
Travis failed due to a build timeout, so it can be safely disregarded.

I have tested this change locally on my BIOS machine and everything is working as it was before, and everything looks good to me. This also only causes grub to rebuild.

I'd like a second opinion before merging, just to be safe, so I've marked this as feedback-requested.

**Comment by jagajaga** [comment]
Tested locally: works and boots fine.

**Comment by nslqqq** [comment]
:+1:

**Comment by ts468** [comment]
@wkennington, I saw that you've been among the last people who updated nixos/modules/system/boot/loader/grub/install-grub.pl a little more, and that you've been also involved in GRUB+EFI things.

Could you maybe have a look at this PR, please? I'm trying to get it merged and now I'm looking for someone who feels confident enough to merge it.

Many thanks!
Thomas

**Comment by wkennington** [comment]
LGTM

**Comment by ts468** [comment]
@wkennington, thank you so much for reviewing and merging the PR!

**Pull request merged**
