### PR TITLE
microsoft-edge: fix file picker and `substituteInPlace`

### PR DESCRIPTION
**Pull request by rikhuijzer**
###### Description of changes

This fixes Microsoft Edge crashing if someone tries to open or save a file via the file picker. For example, to debug the functionality, I went to:

> <https://drive.google.com> -> New -> File upload

Also, I've removed the `substituteInPlace` for the `xdg-settings` file because it appears that they don't substitute anything. Maybe another argument for a `--fail-on-no-subst` flag (https://discourse.nixos.org/t/when-to-use-substituteinplace-functions-vs-a-patch/11073/11).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rikhuijzer** [comment]
I see you, @JonaEnz and @puffnfresh are also working on `microsoft-edge`. Mind taking a look at this PR?

**Comment by JonaEnz** [comment]
The `--replace "''${XDG...` commands seem to break substituteInPlace silently. Adding a backslash like `--replace "\''${XDG...` solves this issue.
The same problem exists in the substituteInPlace command for xdg-mime.
I don't know what the substitutions do and for what system configurations they are relevant, they have been there since the initial commit, maybe they have always been broken.

**Comment by rikhuijzer** [comment]
Thank you for your review @JonaEnz. I've implemented your suggestion (well spotted by the way) and confirmed that the substitutions now work. The substitutions are to functions such as `binary_to_desktop_file()` inside `xdg-mime`. I have no idea when those functions are used, so I don't know how to test the behavior. Therefore, I fixed the substitution in 9cfc523 in the hope that it is useful for some configurations.

At the same time, I also confirmed that the `postFixup` wrapper that I added is required. Without it, `microsoft-edge` will still crash on opening a file.

**Review by JonaEnz — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> The `--replace "''${XDG...` commands seem to break substituteInPlace silently.

It is not broken, it just needs to be escaped properly.

**Review by SuperSandro2000 — COMMENTED** [review]
Whats with this dangling symlink?

```
 ▶ ls -lah result/bin/microsoft-edge-stable
lrwxrwxrwx root root 36 B Thu Jan  1 01:00:01 1970  result/bin/microsoft-edge-stable ⇒ /opt/microsoft/msedge/microsoft-edge
```

**Comment by rikhuijzer** [comment]
> > The `--replace "''${XDG...` commands seem to break substituteInPlace silently.
> 
> It is not broken, it just needs to be escaped properly.

Yes. Didn't we fix that?

**Comment by rikhuijzer** [comment]
> Whats with this dangling symlink?
> 
> ```
>  ▶ ls -lah result/bin/microsoft-edge-stable
> lrwxrwxrwx root root 36 B Thu Jan  1 01:00:01 1970  result/bin/microsoft-edge-stable ⇒ /opt/microsoft/msedge/microsoft-edge
> ```

I have no idea. I considered it out of scope for this PR.

**Comment by GabrielDougherty** [comment]
Successfully uploaded and downloaded an image to Bing image search with this PR using the file picker.

image

Result of `nixpkgs-review pr 219170` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>microsoft-edge-beta</li>
    <li>microsoft-edge-dev</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>microsoft-edge</li>
  </ul>
</details>

**Review by GabrielDougherty — APPROVED** [review]

**Pull request merged**
