### PR TITLE
moodle: 3.11.6 -> 4.0.1

### PR DESCRIPTION
**Pull request by freezeboy**
###### Description of changes

Software update which contains fixes to several security issues + features
I could not run the nixosTests.moodle in my qemu vm (timeout), so please try it on a nixos system

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
The module does not evaluate after 9ec41c8875c00d230f2461f3dce1d16e24070015, so I cannot run the test, either.

**Comment by freezeboy** [comment]
Can you give me more details please, I can't run the module currently as I am running a mac and aarch64-linux (where apparently nixosTests are just failing)

**Comment by freezeboy** [comment]
Ok found the problem, PHP extensions json and xmlrpc have been removed by the commit you mention and they are required by moodle.

xmlrpc has been moved to PECL
json on the other hand is now always part of PHP (if not disabled on build)

I was able to install and run moodle on my aarch64 vm removing the missing dependencies.

Currently the service is not functional as opcache seems broken, still investigating

**Comment by freezeboy** [comment]
Looks like the extensions are being looked at in a wrong directory from phpfpm, I don't understand why it changed recently, any other changes @etu ?

**Comment by etu** [comment]
The major changes we did to PHP recently  was to drop PHP 7.4 and to
promote 8.1 to be default.

**Comment by freezeboy** [comment]
After some more checks, in fact Moodle requires php7.4 atm they don't support PHP 8

**Comment by etu** [comment]
Wow... We had to remove it due to the fact that it's not supported for the
next stables lifecycle.

We also rather remove it early after previous branchoff rather than late
just before branchoff to not risk breaking things like this just before the
release is created.

https://www.php.net/supported-versions.php

**Comment by freezeboy** [comment]
Yes I understand, if moodle is still not compatible for 22.10, we'll have to mark the app broken I guess (better than ship an outdated language)

**Comment by Kloenk** [comment]
xmlrpc got removed as dependency (as far as I understand jira). And php 8.0 is supported since Moodle 4

**Comment by Kloenk** [comment]
Have a moodle now running from this branch. Had to bump to 4.0.2 and use php 8.0 instead of 8.1. Don't have time currently to clean it up for a pr. If anyone wants to do that, feel free

**Comment by alyssais** [comment]
Fixed by #182674.

**Pull request closed without merging**
