### PR TITLE
python-modules.weasyprint: 50 -> 52

### PR DESCRIPTION
**Pull request by ali-abrar**
###### Motivation for this change

Updating weasyprint to the latest major upstream version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
Rename commit to `pythonPackages.weasyprint: 50 -> 52`.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 107976` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python37Packages.xml2rfc</li>
    <li>xml2rfc (python38Packages.xml2rfc)</li>
    <li>python39Packages.weasyprint</li>
    <li>python39Packages.xml2rfc</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.weasyprint</li>
    <li>python38Packages.weasyprint</li>
    <li>sourcehut.metasrht</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107976` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>python37Packages.weasyprint</li>
    <li>python37Packages.xml2rfc</li>
    <li>python38Packages.weasyprint</li>
    <li>xml2rfc (python38Packages.xml2rfc)</li>
    <li>python39Packages.weasyprint</li>
    <li>python39Packages.xml2rfc</li>
    <li>sourcehut.metasrht</li>
  </ul>
</details>

weasyprint:

File "/nix/store/1pmbm2hpjvll1kmaz8c5njkh753sqfkj-python3.7-pytest-6.1.2/bin/.pytest-wrapped", line 9 in <module>
/nix/store/2kq3igrr75pj6nay6phchgn5x1z1f30z-stdenv-darwin/setup: line 1317: 49611 Segmentation fault: 11  pytest -k 'not test_font_stretch'

python3.8-pgpy:
tests fail on sandbox due to network access

python-3.8-cfn-lint:
FAILED test/integration/test_quickstart_templates.py::TestQuickStartTemplates::test_templates
FAILED test/integration/test_quickstart_templates_non_strict.py::TestQuickStartTemplates::test_module_integration
FAILED test/integration/test_quickstart_templates_non_strict.py::TestQuickStartTemplates::test_templates
================== 3 failed, 497 passed, 1 warning in 59.83s ===================

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107976` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.xml2rfc</li>
<li>xml2rfc</li>
<li>(python38Packages.xml2rfc)</li>
<li>python39Packages.weasyprint</li>
<li>python39Packages.xml2rfc</li>
<li>sourcehut.metasrht</li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python37Packages.weasyprint</li>
<li>python38Packages.weasyprint</li>
</ul>
</details>

ERROR: Could not find a version that satisfies the requirement configargparse>=1.2.3 (from xml2rfc)
ERROR: No matching distribution found for configargparse>=1.2.3

ERROR: Could not find a version that satisfies the requirement appdirs>=1.4.4 (from xml2rfc)
ERROR: No matching distribution found for appdirs>=1.4.4


builder for '/nix/store/kmal5zpm1217y34316g3gcq8c2w3avs1-python3.8-cfn-lint-0.35.1.drv' failed with exit code 1; last 10 log lines:
  test/unit/rules/functions/test_sub_needed.py:30
      /build/source/test/unit/rules/functions/test_sub_needed.py:30: DeprecationWarning: invalid escape sequence \$
	        {'custom_excludes': '^\${self.+}$'}, 0

			  -- Docs: https://docs.pytest.org/en/stable/warnings.html
			    =========================== short test summary info ============================
				  FAILED test/integration/test_quickstart_templates.py::TestQuickStartTemplates::test_templates
				    FAILED test/integration/test_quickstart_templates_non_strict.py::TestQuickStartTemplates::test_module_integration
					  FAILED test/integration/test_quickstart_templates_non_strict.py::TestQuickStartTemplates::test_templates
					    ================== 3 failed, 497 passed, 1 warning in 48.01s ===================
						cannot build derivation '/nix/store/65crvik6h3fh53fdi79p87xvwpcqmvm8-python3.8-moto-1.3.14.drv': 1 dependencies couldn't be buil

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107976` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.xml2rfc</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>python39Packages.weasyprint: log was empty</li>
  </ul>
</details>
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>python37Packages.weasyprint</li>
<li>python37Packages.xml2rfc</li>
<li>python38Packages.weasyprint</li>
<li>xml2rfc (python38Packages.xml2rfc)</li>
<li>sourcehut.metasrht</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

sourcehut.metasrht:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Pull request merged**
