### PR TITLE
varnish72: init at 7.2.0

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
see https://varnish-cache.org/releases/rel7.2.0.html

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
There may not be an explicit nixos test for this (would be lovely to have one though) but we could still add `nixosTests.prometheus-exporters.varnish` to `passthru.tests` - it does at least appear to spin it up.

**Comment by ajs124** [comment]
True. Then again, we still have the "`varnish60.passthru.tests` actually tests `varnish71`" issue, if we're not really careful.

For this expression I'm not even sure how to best achieve this. Maybe somehow with an overlay?

**Comment by risicle** [comment]
Is this problem not solved by the `finalAttrs` feature? https://nixos.org/manual/nixpkgs/unstable/#mkderivation-recursive-attributes

**Comment by ajs124** [comment]
Maybe? Do you have an example where it's used to solve this problem for a different package?

**Comment by risicle** [comment]
Hmm.. doesn't look like many nixos tests have been built with the idea of being able to easily override package versions...

**Comment by ajs124** [comment]
how about this?

**Comment by risicle** [comment]
Neat.

Except

> varnish: ass passthru.tests

**Review by risicle — APPROVED** [review]
LGTM, WFM, macos 10.15 & nixos x86_64. All variants of `nixosTests` pass.

**Pull request merged**
