### PR TITLE
19.09 mutter backports

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Same motivation as https://github.com/NixOS/nixpkgs/pull/85966, but we just use patches in `gnome3.mutter`. 
I do updates from `gnome-3-28` branch anyways, so I did the same for `gnome3.mutter328`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test pantheon gnome3 gnome3-xorg

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/85969
31 package built:
adapta-gtk-theme arc-theme chrome-gnome-shell gnome3.gnome-control-center gnome3.gnome-session gnome3.gnome-shell gnome3.gnome-terminal gnome3.gnome-tweaks gnome3.gpaste gnome3.mutter pantheon.mutter gnome3.pomodoro gnomeExtensions.gsconnect pantheon.elementary-greeter pantheon.elementary-gsettings-schemas pantheon.elementary-session-settings pantheon.gala pantheon.switchboard-plug-pantheon-shell pantheon.switchboard-with-plugs pantheon.wingpanel pantheon.wingpanel-applications-menu pantheon.wingpanel-indicator-bluetooth pantheon.wingpanel-indicator-datetime pantheon.wingpanel-indicator-keyboard pantheon.wingpanel-indicator-network pantheon.wingpanel-indicator-nightlight pantheon.wingpanel-indicator-notifications pantheon.wingpanel-indicator-power pantheon.wingpanel-indicator-session pantheon.wingpanel-indicator-sound pantheon.wingpanel-with-indicators
```

**Comment by jonringer** [comment]
I don't see the `cherry-pick -x` messages though

**Comment by worldofpeace** [comment]
@jonringer Right, I backported db49d6ffc885a05cc30ee349ed222e7bcb3844f9 from master. The other one is divergence.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 85969 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>31 package built:</summary>  - adapta-gtk-theme  - arc-theme  - chrome-gnome-shell  - gnome3.gnome-control-center (gnome3.gnome_control_center)  - gnome3.gnome-session (gnome3.gnome_session)  - gnome3.gnome-shell (gnome3.gnome_shell)  - gnome3.gnome-terminal (gnome3.gnome_terminal)  - gnome3.gnome-tweaks (gnome3.gnome-tweak-tool)  - gnome3.gpaste  - gnome3.mutter  - pantheon.mutter (gnome3.mutter328)  - gnome3.pomodoro  - gnomeExtensions.gsconnect  - pantheon.elementary-greeter  - pantheon.elementary-gsettings-schemas  - pantheon.elementary-session-settings  - pantheon.gala  - pantheon.switchboard-plug-pantheon-shell  - pantheon.switchboard-with-plugs  - pantheon.wingpanel  - pantheon.wingpanel-applications-menu  - pantheon.wingpanel-indicator-bluetooth  - pantheon.wingpanel-indicator-datetime  - pantheon.wingpanel-indicator-keyboard  - pantheon.wingpanel-indicator-network  - pantheon.wingpanel-indicator-nightlight  - pantheon.wingpanel-indicator-notifications  - pantheon.wingpanel-indicator-power  - pantheon.wingpanel-indicator-session  - pantheon.wingpanel-indicator-sound  - pantheon.wingpanel-with-indicators</details>

**Pull request merged**
