### PR TITLE
closure-size: Mass-replace 'pkg}/lib'-style references to correct outputs

### PR DESCRIPTION
**Pull request by dezgeg**
A work of a bunch of hacky shell scripts.... hopefully that didn't change something weird that I didn't notice.

### CODE REVIEW

**Comment by deepfire** [comment]
@dezgeg, holding my breath, as I wait for this branch to be merged : -)

**Comment by domenkozar** [comment]
@vcunat

**Comment by deepfire** [comment]
what prevents this from being merged?

**Comment by vcunat** [comment]
I haven't had time to read it yet, and I don't merge (myself) before doing that :-)

**Comment by vcunat** [comment]
It seems all good. Thanks!

**Pull request merged**
