### PR TITLE
fcitx5: 5.0.19 -> 5.0.20 and its plugins.

### PR DESCRIPTION
**Pull request by Vonfry**
###### Things done

changelog: https://groups.google.com/g/fcitx/c/CUj2s1W6h0g
- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

测试测试，fcitx5-rime 可以正常输入中文。

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build fcitx5-unikey fcitx5-table-extra fcitx5-rime libsForQt5.fcitx5-qt fcitx5-m17n fcitx5-gtk fcitx5-configtool fcitx5-chinese-addons fcitx5-chewing fcitx5 xcb-imdkit libime

**Comment by Vonfry** [comment]
I never used this feature. How do I test this module?

**Comment by bobby285271** [comment]
To be honest I also don't know much about it, I guess to test this you will need the keyboard module, since I have no idea whether standalone emoji support is added elsewhere, e.g. maybe there is [such support](https://github.com/fcitx/fcitx5-chinese-addons/blob/5.0.16/im/pinyin/emoji.txt) in fcitx5-chinese-addons, I don't know:

**1** Make sure you have enabled the emoji module (it is [translated](https://github.com/fcitx/fcitx5/blob/5.0.20/po/zh_CN.po#L674) as 颜文字 in zh_CN) in the addons list. Restart fcitx after you enable / disable some modules.



... and make sure you have American English keyboard added as an input method



... and make sure you have emoji enabled in the keyboard module settings




</details>

**2** Now use the American English keyboard, enable completion with Ctrl + Alt + H (or something according to your settings).



... and type `smile`. You should see an emoji in the candidate list

**Comment by Vonfry** [comment]
@bobby285271 Tested. With cldr, emoji can work as well.

**Comment by bobby285271** [comment]
@ofborg build fcitx5 fcitx5-chewing fcitx5-chinese-addons fcitx5-configtool fcitx5-gtk fcitx5-hangul fcitx5-lua fcitx5-m17n fcitx5-mozc fcitx5-rime fcitx5-table-extra fcitx5-table-other fcitx5-unikey libime libsForQt5.fcitx5-qt xcb-imdkit

**Pull request merged**
