### PR TITLE
lisp-modules: Add coalton

### PR DESCRIPTION
**Pull request by Michal-Atlas**
## Description of changes

Add the coalton functional typesystem library for Common Lisp.

Happens to also need fset, so #318943 gets solved I think?
And fset needed a newer misc-extensions, since the one from QuickLisp didn't provide the constant symbol in GMap which fset uses.

FSet is probably a big breaking update: https://github.com/slburson/fset/releases/tag/v1.4.0
With misc-extensions I'm not sure, they don't seem to have a comprehensive list anywhere, but it doesn't look like there's anything being taken out.

Sorry for the ping, I didn't realize nyxt references self and so would be affected by the fset update.
I moved the rev in cl-gobject-introspection to the commit that explicitly fixed the change in SBCL, this should've probably been another pull request, but I wanted to make sure none of these changes broke nyxt in the end, so it now compiles and runs.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
  - I ran it and about 11 packages failed, all of which were already failing so I guess that's fine, the rest build.
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nagy** [comment]
Thank you very much for doing this. I wanted to look at coalton for a long time and this makes it easier. But I do get stuck on testing this:

```
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/pull/319688/head.tar.gz -p 'sbcl.withPackages (ps: [ps.coalton])' --run "sbcl --eval '(require :asdf)' --eval '(require :coalton)'"
...
* (in-package :coalton-user)
#<COMMON-LISP:PACKAGE "COALTON-USER">
* (coalton (EConst 1))

debugger invoked on a COALTON-IMPL/TYPECHECKER/BASE:TC-ERROR in thread
#<THREAD tid=114149 "main thread" RUNNING {10003E0143}>:
  error: Unknown variable
  --> COALTON (NIL):1:10
   |
 1 |  (COALTON (ECONST 1))
   |            ^^^^^^ unknown variable


Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(COALTON-IMPL/TYPECHECKER/TC-ENV:TC-ENV-LOOKUP-VALUE #S(COALTON-IMPL/TYPECHECKER/TC-ENV:TC-ENV :ENV #<COALTON-IMPL/TYPECHECKER/ENVIRONMENT:ENVIRONMENT {100BAA5463}> :TY-TABLE #<COMMON-LISP:HASH-TABLE :TEST COMMON-LISP:EQ :COUNT 0 {100BB25503}>) #S(COALTON-IMPL/PARSER/EXPRESSION:NODE-VARIABLE :SOURCE (10 . 16) :NAME ECONST) #S(COALTON-IMPL/ERROR:COALTON-FILE :STREAM #<SB-IMPL::STRING-INPUT-STREAM {7FB9B428F833}> :NAME "COALTON (NIL)"))
   error finding frame source: Package PARSER does not exist.

                                 Stream: #<SB-SYS:FD-STREAM for "file /nix/store/zx2l81lw8hqrg6rh4f0my6rw7h4aj5ax-source/src/typechecker/tc-env.lisp" {100BB39C63}>
   source: COMMON-LISP:NIL
0]
```
Any idea what I am doing wrong ?

**Comment by Michal-Atlas** [comment]
`EConst` isn't part of the language itself, it's an example from a snippet just above the [block](https://github.com/coalton-lang/coalton/blob/38b8cf0cf6b41f93a19e66ef5221d48b5affd1e3/examples/small-coalton-programs/src/diff.lisp#L20) where I presume you took it from, if you load in that code then the example works as it should.

```lisp
* (load "expr.lisp")
* (in-package #:coalton-user)
* (coalton-toplevel (define (square x) (E* x x)))

* (coalton (dt (E+ (square (EVar t)) (Econst 1))))

#.(E+ #.(E+ #.(E* #.(ECONST 1) #.(EVAR :|t|)) #.(E* #.(EVAR :|t|) #.(ECONST 1))) #.(ECONST 0))
* (type-of 'square)

∀ :A. ((EXPR :A) → (EXPR :A))
```

Thanks for checking it out, the `Package PARSER does not exist.
` isn't exactly calming, but I'm not sure if that's an issue.

**Review by nagy — APPROVED** [review]
Great, that has worked thanks. We just have to keep an eye on these overrides, that once we update the quicklisp distributions, that they do not cause problems. But otherwise it looks great. Thanks again for the package.

**Comment by Michal-Atlas** [comment]
You're welcome, cheers, thanks for the aproove.
Btw, I noticed #197694 just now which can probably be closed, strange I didn't notice it earlier.

**Comment by 7c6f434c** [comment]
@ofborg build nyxt

**Pull request merged**
