### PR TITLE
imagemagick: 7.0.10-61 -> 7.0.11-3

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

Also added myself as maintainer.

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@ofborg eval

@erictapen Could you base your commits on e.g.`e3e59d4ab7b9e353d1762100dfeafff66a4118ee`? That commit is in `master` and `staging`, which makes reviewing much easier?

**Comment by erictapen** [comment]
@dotlambda Ah good to know, will try to do that in the future!

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
@ofborg build imagemagick

**Comment by erictapen** [comment]
Backport in faf316fd5a1642e5eae70d500f06384a28bfdd6c, 9c34c8620db2bcaf591d562b1d784f610c248de8.

Tested with `nix build .#imagemagick7 .#vapoursynth .#python3Packages.Wand .#knightos-kimg`

**Pull request merged**
