### PR TITLE
gitlab: fix module and corresponding test

### PR DESCRIPTION
**Pull request by binarin**
###### Motivation for this change

This fixes some things I've encountered while trying to use this module:
- uploads symlink from store was broken, causing migrations on fresh
  installation to fail
- Get `lib` folder from configured package, not from a global `gitlab`
  one
- Increase memory limit, so the test will be able to pass

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Ah, you can then uncomment this: https://github.com/NixOS/nixpkgs/blob/5f5e3434874c6757504cbd5d48c02678e9851913/nixos/release.nix#L292-L294, was disabled since 61816b06e7f908c1f33c01312218e495f23426f1

**Comment by binarin** [comment]
@GrahamcOfBorg test gitlab

**Comment by Infinisil** [comment]
@GrahamcOfBorg test gitlab

Currently only trusted users can run builds through ofborg, see https://github.com/NixOS/ofborg#trusted-users-vs-known-users

**Comment by binarin** [comment]
The test fails because systemd for some reason decides to enforce start timeout, despite it being explicitly set to `infinity`. Didn't saw this myself as I was testing on a faster machine. 

So what to do now? Disable the test back again?

**Comment by flokli** [comment]
@binarin that's not systemd , but a hard-coded timeout in `nixos-test-driver`:

https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/test-driver/Machine.pm#L231

**Comment by Mic92** [comment]
I think we had problems with this test inside a VM because the p9 filesystem used to passthrough the nix store is not fast enough to load all ruby gems from gitlab in time.

**Comment by flokli** [comment]
That's really weird, `ExecStartPre` commands [should also use `timeout_start_usec`](https://github.com/systemd/systemd/blob/master/src/core/service.c#L2021)…

**Comment by binarin** [comment]
Searching around the internet showed that `infinity` was incompatible with older versions of systemd. Looks like this should be already fixed/implemented in the version that is currently used, but as I have no other ideas, I'm changing this timeout to 1day. Can someone please kick-off the tests again?

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
@binarin can you rebase?

**Comment by binarin** [comment]
@flokli I've tried to do so half an hour ago, but `master` was broken. Will try one more time.

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
Uff, 16 minutes is quite a long time.

Do you see what's taking so long here?
If it's I/O on the database, can we mount it with a tmpfs as storage for example?

**Comment by Mic92** [comment]
@flokli it is loading ruby files from p9 file system which is super slow.

**Comment by binarin** [comment]
The longest part of a test in applying all the migrations. I don't think that applying them on bare-metal was much faster.

**Comment by binarin** [comment]
OK, I've found why systemd was killing a unit while despite of `infinity` timeout. It's because the test was overriding that `infinity` to 10 minutes.

I've pushed a change increasing this to 30 minutes, let's try again - maybe it'll be able to finish when not experiencing random kills.

**Comment by flokli** [comment]
@binarin ping ;-)

**Comment by binarin** [comment]
@flokli I hope I'll be able to get back to this issue within a few weeks.

**Comment by globin** [comment]
superseded by #49658

**Pull request closed without merging**
