### PR TITLE
Plasma: 5.10.4 -> 5.10.5

### PR DESCRIPTION
**Pull request by bkchr**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bkchr** [comment]
nix-shell -p nox --run "nox-review wip" showed some errors, I fixed these errors in the following pull requests: #28500 #28498 #28499

**Comment by ttuegel** [comment]
I am getting the following hash error:
```
output path ‘/nix/store/ca745axwm2qzy1f0fvyvmqbqjygpg0v2-kdeplasma-addons-5.10.5.tar.xz’ has 
sha256 hash ‘03a1l3yqf72l9w93i9f3q6wrh41ri37c11rfxrfs8ya97x2qnk5d’ when 
‘1xdsa38i60x24p6xiv4x1cqd7f2xijs15c19qsjv594lnmbizbr5’ was expected
```

**Comment by bkchr** [comment]
Weird... 
I re-executed ./maintainers/scripts/fetch-kde-qt.sh pkgs/desktops/plasma-5, but my srcs.nix did not change in the current run.

**Comment by ttuegel** [comment]
I re-ran the build several times and it eventually succeeded. Probably, some mirror has a bad version.

**Comment by bkchr** [comment]
Thx for retrying! :)

**Comment by ttuegel** [comment]
Looks good here. Thanks!

**Pull request merged**
