### PR TITLE
avidemux: make install path match rpath; fix runtime

### LINKED ISSUE #239424: Avidemux startup error, missing library (libADM_coreVideoCodec6.so)
### Describe the bug
[avidemux](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/video/avidemux/default.nix) could not be started since a few days/weeks. (Worked well before).

### Steps To Reproduce
1. nix-shell -p avidemux
2. avidemux
3. message: avidemux: error while loading shared libraries: libADM_coreVideoCodec6.so: cannot open shared object file: No such file or directory

### Expected behavior
The application starts without any problems, as it does some days (and `nixos-rebuild switch --upgrade`) cycles before.

### Additional context
I sadly have no idea, since when the error occurs exactly, and why. Because the package itself wasn't touched for a while:
https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/applications/video/avidemux/default.nix
and it definitely worked with this last [commit](https://github.com/NixOS/nixpkgs/commit/a5a292c7a82c694129c1045a4ee8a5078db37d71). So something other have to be changed, or it is just on my side. Hopefully someone could verify it the 'steps to reproduce' works for other people?

I searched for the missing library in the path where it seems to be missed:
"**/nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1**/bin/avidemux: error while loading shared libraries: libADM_coreVideoCodec6.so: cannot open shared object file: No such file or directory"
and found it two times:
* /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1/lib/libADM_coreVideoEncoder6.so (symlinked from lib64)
* /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1/lib64/libADM_coreVideoCodec6.so

### Notify maintainers
@abbradar 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8, NixOS, 23.11 (Tapir), 23.11pre496992.e603dc5f061`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels({user}): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Thanks in advance for any support ❤️

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes
cmake installs into $out/lib64 but the rpath is set to $out/lib. this creates a problem as the fixupPhase will remove $out/lib from the rpath as it doesn't exist. This change moves lib64 to lib so the fixup phase will not remove the rpath. 

superseeds #265545
fixes https://github.com/NixOS/nixpkgs/issues/239424

Result of `nixpkgs-review pr 281173` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>avidemux</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jerith666 — APPROVED** [review]
builds and launches fine for me on `x86_64` -- thanks!

**Review by doronbehar — COMMENTED** [review]
Looks good to me. Could we please also handle the double wrapping issue while at it? I think that we simply need a `dontWrapQtApps = true;`.

**Comment by doronbehar** [comment]
Looks great now. Feel free to merge when CI is green.

**Comment by a-n-n-a-l-e-e** [comment]
> Looks great now. Feel free to merge when CI is green.

if you could approve the commit that would be great, so it doesn't look like i am doing self merges the first day i get the commit bit.

**Comment by doronbehar** [comment]
LOL congratulations :) If you are motivated, in a 2nd thought perhaps it'd be perfect to have that `dontWrapQtApps` change be part of a separate commit in the PR - as it doesn't related to the main fix, and it was probably an issue before the package got broken.

**Pull request merged**
