### PR TITLE
smlnj: 110.95 -> 110.99.6.1

### PR DESCRIPTION
**Pull request by Skyb0rg007**
## Description of changes

Standard ML of New Jersey is updated to 110.99.6.1.
Change log can be found on the [smlnj.org website](https://www.smlnj.org/dist/working/110.99.5/HISTORY.html).

Outside of updating hashes, this version bump allows the removal of the `heap2exec.diff` file, since the build system issue was fixed. It also requires a slightly different regex to pass to `sed` during patching.

The compiler binary and libraries have been extensively tested. The other binaries all run but have not yet been as extensively tested.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by smancill — APPROVED** [review]
LGTM

**Comment by jasoncarr0** [comment]
@thoughtpolice Can this be merged?

**Comment by smancill** [comment]
> @thoughtpolice Can this be merged?

No, there are merge conflicts.

**Comment by Skyb0rg007** [comment]
One remaining issue is the use of a timestamp in the build process.
There is a call to the SML function `Time.now` during build, which is output on startup. This means that the build is currently not fully reproducible.

If this is an issue, I could try to add a patch that fixes the date of the version release.

**Comment by jasoncarr0** [comment]
> One remaining issue is the use of a timestamp in the build process. There is a call to the SML function `Time.now` during build, which is output on startup. This means that the build is currently not fully reproducible.
> 
> If this is an issue, I could try to add a patch that fixes the date of the version release.

I'm not the maintainer but I think adding a small patch to fix this would be the best. If it must be a time/date it's typically the unix epoch and that is overall pretty straightforwardly clear where it's coming from / if it's in nixpkgs the user can check the path to determine what build it was from nonetheless.

**Comment by Skyb0rg007** [comment]
Although the call to `Time.now` is in a specific file (base/system/smlnj/internal/version.template), that code is ran by the boot file which is downloaded as binary. I can try to get a change made upstream but it will take time, and the existing nixpkgs derivation has this same issue, so I do not think it should block merging.

**Comment by Skyb0rg007** [comment]
I got verbal confirmation that this will be fixed in the next upstream release. I think it doesn't make sense to implement the patch in Nix since it cannot be done via `patch`, especially since it already exists in the current nixpkgs version.

**Comment by Skyb0rg007** [comment]
110.99.6.1 fixes a bug, but also changes removes the build-time dependency. This should fix the non-reproducibility issue.

**Review by thoughtpolice — CHANGES_REQUESTED** [review]
This looks fine, but collapse these commits into one; that's a typical policy for many packages here. There is no reason to have the intermediate updates when they will be immediately superseded anyway due to bugfixes or whatnot.

**Comment by Skyb0rg007** [comment]
Should be squashed now. Do I need to document the changelog, or link to the changelog on smlnj.org anywhere?

**Comment by thoughtpolice** [comment]
No. If you write an update script so that updates are automatic, then the @r-ryantm can normally do the links and stuff for you. But I wouldn't worry about it for now.

**Review by thoughtpolice — APPROVED** [review]
Approved, but needs a rebase after the maintainer update.

**Comment by Skyb0rg007** [comment]
Should be fixed now.
Regarding the update script, I have a Perl script that I can use to manually update the nix file, but unfortunately there aren't many examples of packages with update scripts which have multiple hashes to update. Can take a look [here](https://github.com/Skyb0rg007/nixpkgs/blob/smlnj-updater/pkgs/development/compilers/smlnj/updater.pl) if that's something worthwhile to add, though with SML/NJ only updating once a month it's fine to keep it manual for now.

**Pull request merged**
