### PR TITLE
lanraragi: refactor, apply patches, add 23.11 release notes

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

This PR does several things, the most important ones being applying a security patch and fixing the build for darwin.

---
Changes:

Add a security patch that fixes an issue with secrets not being unique. I'd advise against using the previous version for production

Use more upstreamed patches.

Fix the darwin build:
The shebang in Cpanminus's script wasn't working properly (idk why, darwin is weird), so I made it so that it explicitly runs it with perl.
(Cpanminus is not required, because nix already downloaded and built all perl packages, however it is nice that there is a way to check whether all dependencies are present.)

Remove all Cpanminus related stuff from the upstream install helper script. (Now it only does some basic checks and then copies the required files from `node_modules`)

Add release notes for LANraragi.

Add a bit more types of characters into the password nixos tests. (redis can't take special chars, so nothing crazy there)

Add a helper script to `$out/bin/helpers` (maybe there's a better place?) which generates a hash from a password. Previously, the nixos module was doing this itself, but I think this is slightly better.

Change how the perl packages are included when running the program: now it doesn't use `perl.withPackages` and just uses the fact that having `perl` in `nativeBuildInputs` together with perl packages sets the `$PERL5LIB` env-var.

Make the program run without requiring the user to create lrr.conf for themselves now. It will now copy the default config file from the store to the working directory if the file doesn't exist yet.

---

Another thing I want to do is add support for supplying SSL sertificates and maybe also add support for having `redis` not locally running.
However that's beyond this PR, and will probably come together with the next version upgrade.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TomaSajt** [comment]
@ofborg build lanraragi

**Comment by stigtsp** [comment]
@ofborg eval

**Comment by TomaSajt** [comment]
Ofborg's check-meta seems to be broken right now (fixed in https://github.com/NixOS/nixpkgs/pull/264290).

**Comment by TomaSajt** [comment]
Closing this, as there has been a newer version released.

**Pull request closed without merging**
