### PR TITLE
polkadot: 0.8.29 -> 0.8.30

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

Version bump.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
[Looks like](https://hydra.nixos.org/job/nixpkgs/trunk/polkadot.x86_64-linux) this bump broke it:
```
hash mismatch in fixed-output derivation '/nix/store/qc3dla2iwhh2bdnsbdq6l96n6kd03zh6-polkadot-0.8.30-vendor.tar.gz':
  wanted: sha256:1xcadx5vnnaygqksyh58qc2jjgpg7hfgi3149l64aaf72316vi84
  got:    sha256:18hfv4vn48g9b9hkdvqihy76mm212m7qz9yin4i4j270m9qrnsm5
```

**Comment by asymmetric** [comment]
@vcunat hmm interesting. Any idea why the @GrahamcOfBorg tests would have passed then? It also built on my machine, FWIW.

**Comment by andresilva** [comment]
Probably due to the rust 1.50 -> 1.51 update that was merged today.

**Comment by asymmetric** [comment]
@andresilva does a rust version bump break (all) pre-existing `buildRustPackage` packages? Or just this one?

Cause if I understand the timeline correctly, the rust bump came after my bump, so it seems it would have broken this package regardless of my bump.

**Comment by andresilva** [comment]
I think in general no. With Rust 1.51.0 a new feature was introduced in Cargo which affects how crate features are resolved (https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver). I suspect that due to this with 1.51.0 polkadot resolves dependencies slightly different which leads to the vendoring hash mismatch. I'm speculating here a bit though, I didn't check that this is what happened.

**Pull request merged**
