### PR TITLE
gruvbox-gtk-theme: 0-unstable-2024-06-27 -> 0-unstable-2024-07-22

### PR DESCRIPTION
**Pull request by D3vil0p3r**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by D3vil0p3r** [comment]
I just don't know why it creates `$out/share/icons/hicolor` folder symlink...

**Comment by frisodubach** [comment]
Various previously available variants of the gtk theme disappeared with this PR.
As indicated by @D3vil0p3r, this could be due to upstream changes. For my system only Light & Dark variants remain.

**Comment by D3vil0p3r** [comment]
> Various previously available variants of the gtk theme disappeared with this PR. As indicated by @D3vil0p3r, this could be due to upstream changes. For my system only Light & Dark variants remain.

How are you building the package? In this PR all the variants offered by the upstream have been added.

**Comment by frisodubach** [comment]
> > Various previously available variants of the gtk theme disappeared with this PR. As indicated by @D3vil0p3r, this could be due to upstream changes. For my system only Light & Dark variants remain.
> 
> How are you building the package? In this PR all the variants offered by the upstream have been added.

I'm only installing it like this:
```nix
  environment.systemPackages = with pkgs; [
    gruvbox-gtk-theme
  ];
```
Then checking with `themechanger` I can only see light and dark variants of the theme.

**Comment by gador** [comment]
I tested this in a VM as well. I can only choose between dark and light. Is this intentional? Do we have to override/pass the variants manually and rebuild the system to get another theme?

**Comment by D3vil0p3r** [comment]
> I tested this in a VM as well. I can only choose between dark and light. Is this intentional? Do we have to override/pass the variants manually and rebuild the system to get another theme?

By default yes because it is the default behavior of the upstream. If a user wants more variants, it must specify them according to the attributes specified in the .nix file.

**Comment by gador** [comment]
I guess there is no way to install all variants by default and let the user choose at runtime?

**Comment by D3vil0p3r** [comment]
> I guess there is no way to install all variants by default and let the user choose at runtime?

Mmh I think that the best option is to allow this behavior upstream, so by contacting the theme developer and asking for it.

**Comment by gador** [comment]
This needs to be rebased due to a merge conflict by https://github.com/NixOS/nixpkgs/commit/2638e899c07ebe8e41dea7960e2704d3419d0cc1
I re-tested it in a VM and when using 
```nix
environment.systemPackages = with pkgs; [
  (gruvbox-gtk-theme.override { themeVariants = [ "all" ]; })
 themechanger
];
```
I see all the variants and can choose from them with `themechanger`.
Since this seems to be an upstream decision and the rest of this PR looks good, I'm fine with merging this after the rebase.

**Comment by kirillrdy** [comment]
@D3vil0p3r can you remove merge commit

**Comment by D3vil0p3r** [comment]
@gador @kirillrdy sorry for my naive question: I solved the conflict by web GitHub. On my host, I tried to rebase but after my last commits (above) I see a further commit (25aaa8171) that creates conflicts when I run `git rebase -i`. So I cannot squash my commits. How can I deal with it? Should I just `git rebase --continue` and ignore those messages?

**Comment by D3vil0p3r** [comment]
What I'm trying is to squash my 2 commits, and when I get the conflict messages from the other two commits, I run:
```
git rebase --continue
git add -A
```
but I don't know if it is the right path. If I push it, I expect this PR could have also those changes of
```
a46c4c831 espflash: 3.1.0 -> 3.1.1
7f2b9c10d Revert "bandwhich: 0.22.2 -> 0.22.2-unstable-2024-08-13"
```

**Comment by gador** [comment]
I just rebased it myself. I hope thats ok. What I did (assuming `origin` is `NixOS/nixpkgs` and `D3vil0p3r` is your fork):
```shell
git checkout master
git pull origin master
git checkout patch-3
git reset --hard HEAD~1 # get rid of the merge conflict
git rebase -i HEAD~2 # interactively squash your two commits
git rebase master
git push D3vil0p3r patch-3 --force
```

**Pull request merged**
