### PR TITLE
mesa: 21.0.3 -> 21.1.1

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
`@@j_dri.so`: that looks like some bad substitution during patching.

**Comment by primeos** [comment]
Yeah, I wish... :) Unfortunately the `@@` is likely only some coincidence. I forgot to include a hexdump but when I viewed that file with Vim inside a virtual terminal I got some additional "garbage" (very strange/exotic characters). So I've got the feeling that something's terribly going wrong (memory corruption?) and some "random garbage" will end up being used (also forgot / didn't have enough time to check if it's a constant value or if it changes every time - but something's definitely very broken).

**Comment by primeos** [comment]
I did briefly re-test it with RC3 and the driver name does indeed change every time, e.g.:
- C
- (empty)
- 9`L
- /h
- k2
- ?
- o9޺
- ?we
- {
- /į

So yeah, unfortunately something's seriously broken. Likely a memory corruption bug that ends up as random garbage as the driver name.

**Comment by primeos** [comment]
@GrahamcOfBorg test sway

**Comment by vcunat** [comment]
21.1.1 should be available in two weeks, but so far the issues don't make it sound like this will make it to NixOS 21.05.

**Comment by primeos** [comment]
From my perspective it doesn't seem like a good idea for NixOS 21.05.

Interestingly the VM test for Sway (https://github.com/NixOS/nixpkgs/pull/119558/checks?check_run_id=2519144774) did succeed and reports:
```
GL_VERSION: 3.1 Mesa 21.1.0
GL_RENDERER: llvmpipe (LLVM 11.1.0, 256 bits)
GL_VENDOR: Mesa/X.org
```

So I gave it another go on my system and `glinfo` as well as `glxgears` worked as expected in my running Sway session (using Mesa 21.1.0) but after quitting Sway I couldn't launch it anymore (with the same errors as above). I could really use some help on this as I'm out of ideas (don't even know a good way to debug/analyze this without a lot of effort).

If someone in this thread could test this update as well that would be helpful (doesn't have to be Sway - it'd be useful to see if other Wayland/X11 software is affected by this as well).

I'm using something like `hardware.opengl.package = (import /srv/nixpkgs/mesa { }).pkgs.mesa.drivers;` to test updates where `/srv/nixpkgs/mesa` points to a Git worktree with the 4 commits of this PR applied on top of `nixos-unstable`. So far that has worked fine for testing.

**Comment by primeos** [comment]
Huh, interesting, it seems like `hardware.opengl.package = (import /srv/nixpkgs/mesa { }).pkgs.mesa.drivers;` isn't usable for testing anymore... I finally decided to rebuild Sway based on `/srv/nixpkgs/mesa` and launching that binary works as expected.

**Comment by primeos** [comment]
@vcunat are 1001-2500 rebuilds on Darwin and Linux still fine for `master` (https://github.com/NixOS/nixpkgs/pull/118479#issuecomment-813586306, https://github.com/NixOS/nixpkgs/pull/118753#issuecomment-818977245) and is it ok to merge all Mesa updates via `master` or should we merge some of them via `staging`?

@ofborg test sway

**Comment by vcunat** [comment]
I think the rebuild amount is OK-ish to push directly to master, though it's a bit more than I originally thought (maybe some of the later changes).  And we're in period where I expect to have higher Hydra load continuously... perhaps staging-next as a compromise?

**Comment by primeos** [comment]
@vcunat sounds good, that's also what I thought, thanks for the reply!

If I have time for it I'll try to investigate if we can avoid some of the rebuilds (AFAIK the build capacity on Darwin is more limited and it's also strange that there are more rebuilds on Darwin than on Linux - not sure if the Mesa dependencies are even needed on Darwin).

**Comment by vcunat** [comment]
darwin is because `libGL` is "intentionally" affected in there (see `pkgs/development/libraries/mesa/stubs.nix`).

**Comment by vcunat** [comment]
I don't dare trying to improve that.

And `x86_64-darwin` is the main reason why I suggested not using master now, as it's quite loaded on Hydra now and probably will remain so for at least a week.  On `staging-next` most builds haven't finished yet (especially on "slower" platforms), so most should be saved.

**Comment by vcunat** [comment]
This still can't be merged as-is (to staging-next) due to containing extra commits from staging.

**Comment by primeos** [comment]
> This still can't be merged as-is (to staging-next) due to containing extra commits from staging.

Oh boy, I really messed that one up... :o First I forgot to specify `staging-next` when rebasing (and my remote tracking / ustream branch was `staging`) and when I noticed this I accidentally pushed to `primeos:staging-next` instead of `primeos:mesa-next` (which I didn't realize and explains why the extra commits where still in there). Seems like I was lacking some attention...

Anyway, sorry about that, it's fixed now.

**Pull request merged**
