### PR TITLE
[21.05] nixos/kresd: tell resolveconf to use local resolver

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
backport https://github.com/NixOS/nixpkgs/pull/124391

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]

**Comment by vcunat** [comment]
I wonder if this is small enough not to have a changelog mention.  I'd probably leave it without any.  (say, bind would be different because you can use it as authoritative-only server)

**Comment by ajs124** [comment]
this broke my setup. kthxbye.

for real though, not everyone has kresd listening on localhost.

**Comment by vcunat** [comment]
Yes, I [was](https://github.com/NixOS/nixpkgs/pull/124391#pullrequestreview-667950510) aware that it isn't 100%, but it's not just kresd and it's trivial to override.

In any case, I'm curious about possible motivation to run a resolver but _not_ use it for the local system.

**Comment by ajs124** [comment]
It is used on the local system, just not through `127.0.0.1`.

**Pull request merged**
