### PR TITLE
staging-next: 21.11 iteration 5 - 2022-01-11

### LINKED ISSUE #152902: qt5.qtsvg fails to build on x86_64-darwin [21.11]
https://hydra.nixos.org/build/162054046
This blocks the `nixpkgs-21.11-darwin` channel.

It was retried a few times on Hydra.  Someone with a compatible machine needs to look into this, I expect.  I tried simple manual eval-only bisection (hopefully without a mistake):

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 6e0b7f0c7a779fb2f14bab2621861169525c6e67
> 065d1fad7a538e178260137b2c042d3348821798
> 4ce0b95905b039ae9e1dfdb59e8bae85f41fc06a
> ee8ff1d8282629d8ea90ae8770e97c65c062cc10
> 017fb54c28a3b4c703d4364dc611a3079b8ba48c
> 4ef54c9d1c07e7b1cf0004cb57233dff10fea033
> 5a9a0b1e33953251e2d239bb689625f2653fda2f
> 717b53d52f6f5c2a5a2a6d4496d19df07da4b4e2
> 6eb08df677ffd83643c830bb48603eec808fa45a
> ba906044ba5481bc5ff881b232b339c6173511d0
> 0350e81da5ed0569b2ac4e521517909a3649acd6
> 72121eb172199373efb89cc1b23cc5e0c540d0cd
> 0f4ec0a1b296a690749986f07f70b4a0f13677db
> 9eeff7536cd622661e1a5d26f806053c322958a5
> 66d2a5c98ce874f8e03d3ae049ded1c4b8385bea
> 9ce2035e4d1e0c358e6760e5c00d1302fc546e7c
> 8c68c6fa969d887f49a51cc784bce92d3a9e5c16
> c0ce302c5668539b3c4300f81e3cbb30a2d3a280
> 065fec456ff09d0ee34b1ea8564fe052e791602e
> 72ac7ea6a66f05e3efe4137466e3ae2d7b97ca6c
> c1968ed909b94f63a10aa7f460c798aedad6fce7
> a4a044265616155eb63dbd81a450cb174808561f
> We cannot bisect more!

and I can't see a clear candidate on the list of commits.

### PR DESCRIPTION
**Pull request by vcunat**
Documentation here: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch

https://hydra.nixos.org/job/nixpkgs/staging-next-21.11/unstable#tabs-constituents

Previous staging-next PR: #151587

### CODE REVIEW

**Comment by vcunat** [comment]
I'm sorry, me forgetting to change the target branch created quite a mess.

**Comment by sternenseemann** [comment]
unstable currently fails to evaluate with:

```
in job ‘unstable’:
error: unsupported libc for bootstrap tools
```

I'm pretty sure I am to blame for this and will look into it.

I also noticed that `x86_64-darwin` is disabled for the jobset at the moment, we may want to flick that back on?

**Comment by vcunat** [comment]
I did it seconds after eval was triggered (noticed too late), so let me just re-trigger it.

**Comment by sternenseemann** [comment]
> I'm pretty sure I am to blame for this and will look into it.

Turns out I am innocent in this case! In any case fix for `master` at: #154506, for staging-next-21.11 at #154507.

**Review by jonringer — APPROVED** [review]
local [test suite](https://github.com/jonringer/nix-test-staging-next/blob/main/test-staging.nix) passed.

Still need to check regressions, and waiting for rebuild count to go to 0

**Comment by vcunat** [comment]
Also Hydra succeeded on restarting [the build](https://hydra.nixos.org/build/163804604).  I poked upstream: https://github.com/libuv/libuv/issues/2235#issuecomment-1012086927

**Comment by vcunat** [comment]
Merged in a bit earlier phase due to #154931, to avoid more rebuilds in the big 21.11 jobsets.  I trust these backports won't cause significant regressions.

**Comment by vcunat** [comment]
And the `nixos-21.11` channel updated now 🎉

**Pull request merged**
