### PR TITLE
gtk3: 3.24.27 -> 3.24.30

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
Version bump. I don't see anything of concern in the changelogs.

https://ftp.fau.de/gnome/sources/gtk+/3.24/gtk+-3.24.28.news
https://ftp.fau.de/gnome/sources/gtk+/3.24/gtk+-3.24.29.news
https://ftp.fau.de/gnome/sources/gtk+/3.24/gtk+-3.24.30.news

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
> - Remove the Google Cloud Print backend, since the service was shut down

Maybe we can remove librest dependency now?

**Comment by jtojnar** [comment]
Weird, we do not depend on librest here. Perhaps that was not enabled.

**Comment by jtojnar** [comment]
What about json-glib? https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3729

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129896` at 0be86875 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages marked as broken and skipped:</summary>
  <ul>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-openj9-bin-13</li>
    <li>adoptopenjdk-jre-openj9-bin-14</li>
    <li>adoptopenjdk-openj9-bin-13</li>
    <li>adoptopenjdk-openj9-bin-14</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>epsxe</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>googleearth-pro</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>impressive</li>
    <li>invoice2data</li>
    <li>jboss</li>
    <li>keyfinder</li>
    <li>linuxPackages_hardkernel_4_14.akvcam</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.akvcam</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>obinskit</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pig</li>
    <li>spark</li>
    <li>termplay</li>
    <li>tvheadend</li>
    <li>twinkle</li>
    <li>unicap</li>
    <li>vdrPlugins.xineliboutput</li>
    <li>xpdf</li>
  </ul>
</details>
<details>
  <summary>4235 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>MIDIVisualizer</li>
    <li>OSCAR</li>
    <li>R</li>
    <li>Sylk</li>
    <li>_1password-gui</li>
    <li>abcl</li>
    <li>abiword</li>
    <li>adapta-gtk-theme</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>31 packages built successfully:</summary>
  <ul>
    <li>adoptopenjdk-bin (adoptopenjdk-hotspot-bin-11 ,openjdk11-bootstrap)</li>
    <li>openjdk16-bootstrap (adoptopenjdk-hotspot-bin-15)</li>
    <li>openjdk8-bootstrap (adoptopenjdk-hotspot-bin-8)</li>
    <li>cinnamon.bulky</li>
    <li>enpass</li>
    <li>fsearch</li>
    <li>gnome.gnome-session-ctl</li>
    <li>gtk3 (gnome.gtk ,gtk3-x11)</li>
    <li>gnome.zenity</li>
    <li>gssdp</li>
    <li>gupnp</li>
    <li>gupnp-igd</li>
    <li>libappindicator (libappindicator-gtk3)</li>
    <li>libcanberra-gtk3</li>
    <li>libdbusmenu-gtk3</li>
    <li>libindicator (libindicator-gtk3)</li>
    <li>libnice</li>
    <li>libwnck</li>
    <li>openconnect (openconnect_gnutls)</li>
    <li>pantheon.elementary-icon-theme</li>
    <li>songrec</li>
    <li>stoken</li>
    <li>sublime3 (sublime3Packages.sublime3)</li>
    <li>sublime3-dev (sublime3Packages.sublime3-dev)</li>
    <li>sublime4</li>
    <li>sublime4-dev</li>
    <li>tuna</li>
    <li>vimPlugins.vCoolor-vim</li>
    <li>wrapGAppsHook</li>
    <li>xfce.xfce4-dev-tools (xfce.xfce4_dev_tools)</li>
    <li>xsnow</li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `gmp`.
Near pkgs/development/libraries/gtk/3.x.nix:31:3:
```
   |
31 | , gmp
   |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `x11Support`.
Near pkgs/development/libraries/gtk/3.x.nix:37:3:
```
   |
37 | , x11Support ? stdenv.isLinux
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/libraries/gtk/3.x.nix:79:5:
```
   |
79 |     ./patches/3.0-immodules.cache.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/libraries/gtk/3.x.nix:81:5:
```
   |
81 |     (fetchpatch {
   |     ^
```
</li>
  </ul>
</details>

**Comment by maxeaubrey** [comment]
> What about json-glib? https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3729

Good catch, thanks! At a glance it seems fine.

**Comment by Mindavi** [comment]
According to the bot gmp and x11support are unused arguments. Good to remove them too.

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
