### PR TITLE
ldc: 0.17.1

### PR DESCRIPTION
**Pull request by Nekroze**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This adds a package for `ldc` the llvm based d compiler.

I have made a small change to the `dub` (the d build/dependency manager) package to allow it to detect whichever d compiler you give to the environment. In the past `dmd` was passed as via `propagatedBuildInputs` which means that when the `dub` and `ldc` packages are used together, `dub` uses `dmd` to compile when your package may have `buildInputs = [dub ldc];` which would be unexpected.

For some reason I could not get this to compile with anything older than `gcc6` and `clang` just would not compile it at any version.

### CODE REVIEW

**Comment by Nekroze** [comment]
Looks like travis failed because the hash for the source was `12xbzc9b0hhgda8n0125yn4g545qpazhfpv8hjr26pc8qjg9rlq4` rather than the expected (what my test environment got) `1jbvl4iv7r50lxrdiqpdgp5b0kv3igy9sz12cyr3nkjs0fkr54sx`.

How can I resolve this for the PR?

**Comment by joachifm** [comment]
Please squash when you're ready to integrate.

**Comment by Nekroze** [comment]
@joachifm I would be happy to... how would one do that?

**Comment by Nekroze** [comment]
While testing this by using it to build dub I have not been able to run the resulting application in my test environment, when running `dub fetch dcd` compiled with this ldc it just throws a segmentation fault.

I am trying to resolve the issue and if I can soon I will add the commits to fix it but if not I will close this PR and #15574 until I fix this.

Can anyone test to confirm my results? My test environment is not the best, nix single user setup and sometimes things don't go as expected.

**Comment by Nekroze** [comment]
closed for the same reasons as #15574

**Pull request closed without merging**
