### PR TITLE
python3Packages.python_magic: 0.4.22 -> 0.4.24

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.4.24

Change log: https://github.com/ahupp/python-magic/blob/master/CHANGELOG

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132000` at ac99e746 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>49 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/957967b52a9718f3e79ee9e77edb51b1">alot</a> (python39Packages.alot)</li>
    <li><a href="https://gist.github.com/1748b4f3435caf608c4a286ae280b037">ansible</a> (ansible_2_11 ,python39Packages.ansible-core)</li>
    <li><a href="https://gist.github.com/28860776315619cfafdb8cab6bb20021">ansible-lint</a> (python39Packages.ansible-lint)</li>
    <li><a href="https://gist.github.com/54e8948cbc5fd62feba17f0c4a561954">ansible_2_10</a> (python39Packages.ansible-base)</li>
    <li><a href="https://gist.github.com/eaab7e92c27fb5bb0c2b5bab03cb5fca">beancount</a> (python39Packages.beancount)</li>
    <li><a href="https://gist.github.com/dfbf91bf5d6cb2d4c400938baa17a6e1">diffoscopeMinimal</a></li>
    <li><a href="https://gist.github.com/a5f4731e00c53a3331239474d6ae711d">fava</a></li>
    <li><a href="https://gist.github.com/50b945a0e6fd538f783bacca6e9372d2">hfinger</a></li>
    <li><a href="https://gist.github.com/7bdc6730c3410b24a6a7c3e89a2de71b">home-assistant</a></li>
    <li><a href="https://gist.github.com/3e442e31e7f5eb91a3a9d517cae9f587">ledger2beancount</a></li>
    <li><a href="https://gist.github.com/4c64044ca84372d2bab44a014bf3b37d">mastodon-archive</a></li>
    <li><a href="https://gist.github.com/6b7b3195e2860b5df05544373f3994e2">mautrix-signal</a></li>
    <li><a href="https://gist.github.com/a749b58795857c071c5987b21511305e">mautrix-telegram</a></li>
    <li><a href="https://gist.github.com/d8f1f532267a2c4eeb71d9fcf1084ac8">passExtensions.pass-import</a></li>
    <li><a href="https://gist.github.com/ef3318407a902a8228bd77f65f010a76">python38Packages.alot</a></li>
    <li><a href="https://gist.github.com/0a7acaa5e787c6d1702f18a109e86477">python38Packages.ansible-base</a></li>
    <li><a href="https://gist.github.com/d69906320801e4ca71dd6c0781c49064">python38Packages.ansible-core</a></li>
    <li><a href="https://gist.github.com/44c61e427e08cac78b4a466d02c38ad8">python38Packages.ansible-lint</a></li>
    <li><a href="https://gist.github.com/6af4183ec9ae9b2ae6be552cba714da7">python38Packages.beancount</a></li>
    <li><a href="https://gist.github.com/b02d8abbd2e275f03b8bb0cb08d7ed67">python38Packages.beancount_docverif</a></li>
    <li><a href="https://gist.github.com/5634329e3e815ceb7f1ab6f870d72864">python38Packages.django-versatileimagefield</a></li>
    <li><a href="https://gist.github.com/269fb5ae15d5aca3b3738276f86e5ec9">python38Packages.geoip2</a></li>
    <li><a href="https://gist.github.com/4087a88012c198c7adc0fdc349e99208">python38Packages.karton-classifier</a></li>
    <li><a href="https://gist.github.com/1ac453077ce1ae560f7908cc90b2c69c">python38Packages.mastodon-py</a></li>
    <li><a href="https://gist.github.com/ea419c243a5ad9b5c7bb53ae891b8cdf">python38Packages.mocket</a></li>
    <li><a href="https://gist.github.com/53aeaab07bfdc1e5ff63eafaef5a237d">python38Packages.pushbullet</a></li>
    <li><a href="https://gist.github.com/b8b0cb1897ecafdfe12132c99a0e4bc5">python38Packages.pysnow</a></li>
    <li><a href="https://gist.github.com/a0240eb83a8125e845ad5079a64ea14d">python38Packages.python_magic</a></li>
    <li><a href="https://gist.github.com/1e076ff5d0501bd8dcaba58c33ceb29f">python38Packages.relatorio</a></li>
    <li><a href="https://gist.github.com/4394e88a8003686cbac032502345bf11">python38Packages.sopel</a></li>
    <li><a href="https://gist.github.com/7cee34eb78a13663e43d035c8d442e6a">python38Packages.trytond</a></li>
    <li><a href="https://gist.github.com/ea230bd714ae2896e986faa500d40ba6">python38Packages.ttp</a></li>
    <li><a href="https://gist.github.com/4a3b39ffa6ddfb2292890b4c80c256d6">python39Packages.beancount_docverif</a></li>
    <li><a href="https://gist.github.com/d1041f4497efc27479b89e00a9135a96">python39Packages.django-versatileimagefield</a></li>
    <li><a href="https://gist.github.com/bf822cc14bdd14fa200104f624e2c40a">python39Packages.geoip2</a></li>
    <li><a href="https://gist.github.com/a3874fe3da29e597c5bff884c5ffc443">python39Packages.karton-classifier</a></li>
    <li><a href="https://gist.github.com/85abeca847e6bad1315bfb55d9886a7c">python39Packages.mastodon-py</a></li>
    <li><a href="https://gist.github.com/e91487fc64d9d1d3fa66eadcaec191fc">python39Packages.mocket</a></li>
    <li><a href="https://gist.github.com/87a5d5892491b1adaf91dfc7f7cbaa05">python39Packages.pushbullet</a></li>
    <li><a href="https://gist.github.com/21fcf72bd82cf6d7634fffbf0507c99f">python39Packages.pysnow</a></li>
    <li><a href="https://gist.github.com/7acdb3dfd25c1e76f7d82fe78ac0d3bc">python39Packages.python_magic</a></li>
    <li><a href="https://gist.github.com/cd0d58e4e78866253968bf9bf3e52441">python39Packages.relatorio</a></li>
    <li><a href="https://gist.github.com/e08e1ae0642d20bef0171a74c379edf8">python39Packages.sopel</a></li>
    <li><a href="https://gist.github.com/a0b528699acb501f6b658a0e759cdefe">trytond</a> (python39Packages.trytond)</li>
    <li><a href="https://gist.github.com/1fbd06311e8f777f1f3329ec424312ff">ttp</a> (python39Packages.ttp)</li>
    <li><a href="https://gist.github.com/a1a749311f69c0176b6fc3ba3a52a74c">s3cmd</a></li>
    <li><a href="https://gist.github.com/3d83f2e2ab353e379e7173c0bc386ffa">steck</a></li>
    <li><a href="https://gist.github.com/0da55a5e2c4758fb97fbadbdc5dc3adb">urlwatch</a></li>
    <li><a href="https://gist.github.com/34d623e64d06181d400ab1144ed7f092">weechatScripts.weechat-matrix</a></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/python-magic/default.nix:35:3:
```
   |
35 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/python-modules/python-magic/default.nix:23:5:
```
   |
23 |     (substituteAll {
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by alyssais** [comment]
```
patching file magic/loader.py
Hunk #1 FAILED at 5.
1 out of 1 hunk FAILED -- saving rejects to file magic/loader.py.rej
builder for '/nix/store/hxxv5igl5imsw0dw8hkmc3wvhx5bzcfi-python3.9-python-magic-0.4.24.drv' failed with exit code 1
```

**Comment by alyssais** [comment]
Haven't tested, but I think this should do the trick:

```diff
diff --git i/magic/loader.py w/magic/loader.py
index 931f161..b8096d1 100644
--- i/magic/loader.py
+++ w/magic/loader.py
@@ -35,16 +35,12 @@ def _lib_candidates():
 
 
 def load_lib():
+  lib = '@libmagic@'
 
-  for lib in _lib_candidates():
-    # find_library returns None when lib not found
-    if lib is None:
-      continue
-    try:
-      return ctypes.CDLL(lib)
-    except OSError:
-      pass
-  else:
-    # It is better to raise an ImportError since we are importing magic module
-    raise ImportError('failed to find libmagic.  Check your installation')
+  try:
+    return ctypes.CDLL(lib)
+  except OSError:
+    pass
 
+  # It is better to raise an ImportError since we are importing magic module
+  raise ImportError('failed to find libmagic.  Check your installation')
```

**Comment by fabaff** [comment]
Thanks for rewriting the patch.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132000` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
    <li>home-assistant</li>
    <li>python38Packages.sopel</li>
    <li>python38Packages.trytond</li>
    <li>python39Packages.sopel</li>
    <li>trytond (python39Packages.trytond)</li>
  </ul>
</details>
<details>
  <summary>46 packages built:</summary>
  <ul>
    <li>alot (python39Packages.alot)</li>
    <li>ansible (ansible_2_11 ,python39Packages.ansible-core)</li>
    <li>ansible-lint (python39Packages.ansible-lint)</li>
    <li>ansible_2_10 (python39Packages.ansible-base)</li>
    <li>beancount (python39Packages.beancount)</li>
    <li>fava</li>
    <li>hfinger</li>
    <li>ledger2beancount</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>mastodon-archive</li>
    <li>mautrix-signal</li>
    <li>mautrix-telegram</li>
    <li>passExtensions.pass-import</li>
    <li>python38Packages.alot</li>
    <li>python38Packages.ansible-base</li>
    <li>python38Packages.ansible-core</li>
    <li>python38Packages.ansible-lint</li>
    <li>python38Packages.beancount</li>
    <li>python38Packages.beancount_docverif</li>
    <li>python38Packages.django-versatileimagefield</li>
    <li>python38Packages.geoip2</li>
    <li>python38Packages.karton-classifier</li>
    <li>python38Packages.mastodon-py</li>
    <li>python38Packages.mocket</li>
    <li>python38Packages.pushbullet</li>
    <li>python38Packages.pysnow</li>
    <li>python38Packages.python_magic</li>
    <li>python38Packages.relatorio</li>
    <li>python38Packages.ttp</li>
    <li>python39Packages.beancount_docverif</li>
    <li>python39Packages.django-versatileimagefield</li>
    <li>python39Packages.geoip2</li>
    <li>python39Packages.karton-classifier</li>
    <li>python39Packages.mastodon-py</li>
    <li>python39Packages.mocket</li>
    <li>python39Packages.pushbullet</li>
    <li>python39Packages.pysnow</li>
    <li>python39Packages.python_magic</li>
    <li>python39Packages.relatorio</li>
    <li>ttp (python39Packages.ttp)</li>
    <li>s3cmd</li>
    <li>steck</li>
    <li>urlwatch</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>

**Pull request merged**
