### PR TITLE
python310Packages.albumentations: init at 1.3.1

### PR DESCRIPTION
**Pull request by natsukium**
###### Description of changes

Fast image augmentation library and an easy-to-use wrapper around other libraries. Documentation: https://albumentations.ai/docs/ Paper about the library: https://www.mdpi.com/2078-2489/11/2/125

https://github.com/albumentations-team/albumentations

This is a cutout of the [discarded PR](https://github.com/NixOS/nixpkgs/pull/240836#issuecomment-1615999468).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bcdarwin** [comment]
Note that `imgaug` will be an undefined attribute after #242752 is merged, so should be removed.

**Comment by natsukium** [comment]
Good catch, I just made sure that imgaug is not used in other existing packages and forgot about this PR.
Thanks!

**Comment by bcdarwin** [comment]
Results of `nixpkgs-review` on x86_64-NixOS:

```
8 packages built:
python310Packages.albumentations python310Packages.albumentations.dist python310Packages.qudida python310Packages.qudida.dist python311Packages.albumentations python311Packages.albumentations.dist python311Packages.qudida python311Packages.qudida.dist
```

**Review by bcdarwin — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
