### PR TITLE
update fishnet to 2.9.3, use pre-compiled binaries

### PR DESCRIPTION
**Pull request by ornicar**
## Description of changes

Update fishnet to latest version 2.9.3:
https://github.com/lichess-org/fishnet/releases/tag/v2.9.3

Also switch to pre-compiled binaries. Compiling fishnet and its stockfish flavours takes 6 minutes on a powerful PC.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

### CODE REVIEW

**Comment by ornicar** [comment]
@tu-maurice hi, this is my first nixpkgs contribution. I would appreciate if you found the time to take a look, as the original author of the fishnet derivation.

**Comment by tu-maurice** [comment]
Also who is "thibaultd", if you're ornicar :)

**Comment by SuperSandro2000** [comment]
> Compiling fishnet and its stockfish flavours takes 6 minutes on a powerful PC.

That's not to long. You know how long electron takes?

**Comment by ornicar** [comment]
> Also who is "thibaultd", if you're ornicar :)

oops, fixed the contributor key.

**Comment by ornicar** [comment]
> I'd rather vote to keep fishnet source based, maybe you could provide it as fishnet-bin instead?
> 
> Edit: like there's also "firefox" and "firefox-bin"

Sounds like double the work to maintain :) I don't mind keeping it source-based, and I can update this PR to make it so.
But I'm curious as to why it's preferred?

**Comment by SuperSandro2000** [comment]
NixOS is a source based distro and we only really want to fallback to binaries if there are big issues which make source builds unviable or impossible.

**Comment by tu-maurice** [comment]
Given what @SuperSandro2000 said, it seems we do not want to merge this. Neither as a replacement to fishnet nor as fishnet-bin. So I think we can close this.

If you really need this there are ways to have a local overlay. Or if you want to maintain this separately from nixpkgs for others to use you can look into flakes.

**Pull request closed without merging**
