### PR TITLE
tree-wide: pkgs: /var/run -> /run

### LINKED ISSUE #51800: Deprecated /var/run being used for tmpfiles.d
## Issue description

Currently there are a number of services that define something inside `/var/run` inside `/etc/tmpfiles.d/*.conf`. One example I ran into was kubernetes. Upon running `nixos-rebuild` it would show the following warning:

```
setting up tmpfiles
[/etc/tmpfiles.d/nixos.conf:6] Line references path below legacy directory /var/run/, updating /var/run/kubernetes → /run/kubernetes; please update the tmpfiles.d/ drop-in file accordingly.
```

`/etc/tmpfiles/nixos.conf` contained the following lines:

```
# This file is created automatically and should not be modified.
# Please change the option ‘systemd.tmpfiles.rules’ instead.

D! /tmp 1777 root root
d /opt/cni/bin 0755 root root -
d /var/run/kubernetes 0755 kubernetes kubernetes -
d /var/lib/kubernetes 0755 kubernetes kubernetes -
d /var/cache 0755 root root -
```

Apparently `/var/run/kubernetes` is deprecated and should be `/run/kubernetes`. I'll make a PR for this particular instance, but there are probably more instances of this happening.

Alternatively, #40594 might help in this regard as well as upstream projects will run into the same issue and will resolve this for themselves. We currently cannot always ride along with them.

## Steps to reproduce

`/etc/nixos/configuration.nix`:

```
...
  services.kubernetes.roles = ["master" "node"];
...
```

Run `nixos-rebuild switch` and notice the warning.

### PR DESCRIPTION
**Pull request by bobvanderlinden**
Fixes #51800
In response to https://github.com/NixOS/nixpkgs/pull/51918#issuecomment-475983551 this PR is split off from https://github.com/NixOS/nixpkgs/pull/51918. This PR only includes changes to `pkgs/`.

See #51918

> `/var/run` is deprecated in `tmpfiles.d` and `/run` should be used. Currently this produces a warning every time `nixos-rebuild switch` runs for each service that uses `tmpfiles.d` with an entry for `/var/run`.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
evaluation error seems unrelated: @GrahamcOfBorg eval

**Comment by Infinisil** [comment]
Huh, still eval issues, that *really* doesn't look related, gonna try again

@GrahamcOfBorg eval

**Comment by bobvanderlinden** [comment]
Was hoping it might help to rebase to latest staging. We'll see what @GrahamcOfBorg will do.

**Comment by bobvanderlinden** [comment]
@GrahamcOfBorg eval

Hopefully this works? Otherwise, could someone else give this a go?

I tried building this on OSX, but for the package it tried to build OSX is indeed not supported. I'm still not sure why grahamcofborg tried to evaluate.

**Comment by bobvanderlinden** [comment]
Everything seems fine. Could someone have a look?

**Review by infinisil — APPROVED** [review]
LGTM

**Comment by bobvanderlinden** [comment]
Thank you!

**Pull request merged**
