### PR TITLE
graylog: 3.1.0 -> 3.1.2

### PR DESCRIPTION
**Pull request by fadenb**
###### Motivation for this change
New Graylog release containing bugfixes
(fixes the issue that dashboard widget editing was not possible due to problems focusing the input field!)

###### Things done
* Bump Graylog
* Bump SSO plugin (forgot to do this when updating Graylog to 3.1.x)

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Ma27

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build graylog

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by Mic92** [comment]
Since it is a bugfix release, should I backport graylog?

**Comment by fadenb** [comment]
> Since it is a bugfix release, should I backport graylog?

Yes, that would be great. Thanks!

**Pull request merged**
