### PR TITLE
staging-next 2023-08-11

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/245935
- - - 
##### Mass breakages
(will be edited based on progress)
- [x] [`swift`](#issuecomment-1676831102)
- [ ] [`(lib)tensorflow`](#issuecomment-1680148545)

### CODE REVIEW

**Comment by tobim** [comment]
I have fixes for [grpc](https://github.com/NixOS/nixpkgs/pull/248532) and [google-cloud-cpp](https://github.com/NixOS/nixpkgs/pull/248536).

**Comment by tjni** [comment]
https://github.com/NixOS/nixpkgs/pull/246931 is needed to fix `gupnp` after the meson update.

**Comment by fabianhjr** [comment]
Due to gupnp 1.4 breakage: https://github.com/NixOS/nixpkgs/pull/248622

**Comment by fabianhjr** [comment]
https://github.com/NixOS/nixpkgs/pull/234433

Needed for i686 like steam due to breakage of basement.

**Comment by vcunat** [comment]
@fabianhjr basement has been broken for way longer time than this staging-next AFAIK.  How does it relate to steam (apart from i686?.

**Comment by fabianhjr** [comment]
Here is the related error:

```
error: builder for '/nix/store/y1a6anshdi0y81nwbrwqb5r5y2psdd0l-basement-0.0.16.drv' failed with exit code 1;
       last 10 log lines:
       >
       > Basement/Numerical/Conversion.hs:29:1: error:
       >     Could not find module ‘GHC.IntWord64’
       >     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
       >    |
       > 29 | import GHC.IntWord64
       >    | ^^^^^^^^^^^^^^^^^^^^
       > [20 of 84] Compiling Basement.Numerical.Number ( Basement/Numerical/Number.hs, dist/build/Basement/Numerical/Number.o, dist/build/Basement/Numerical/Number.dyn_o )
       > [22 of 84] Compiling Basement.Types.Char7 ( Basement/Types/Char7.hs, dist/build/Basement/Types/Char7.o, dist/build/Basement/Types/Char7.dyn_o )
       > [23 of 84] Compiling Basement.Base16  ( Basement/Base16.hs, dist/build/Basement/Base16.o, dist/build/Basement/Base16.dyn_o )
       For full logs, run 'nix log /nix/store/y1a6anshdi0y81nwbrwqb5r5y2psdd0l-basement-0.0.16.drv'.
error: 1 dependencies of derivation '/nix/store/wkp4wvw0v7i6p2x2vj138czv2882c2zn-foundation-0.0.30.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rv3iz1s15lb4m6yf01zx46x5qi60bzas-socks-0.6.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/ylyd8i6jx4x7ywgfkyv3xm4vjk3y3bm8-memory-0.17.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y0v5xxa8802v0m9rczhh03prpwqhwwjw-asn1-types-0.3.4.drv' failed to build
error: 2 dependencies of derivation '/nix/store/dxxmm34jsm9v8lfd403xdakl95idnvdq-cryptonite-0.30.drv' failed to build
error: 2 dependencies of derivation '/nix/store/j8jr5bf7k9pqajshaknld0qyvl0f334w-pem-0.2.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h6izca3d5g8a9rhj4mlzmkbz91zy5h8v-asn1-encoding-0.9.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b6a3fcln14v7cbqxgzkdlc1lxw7sdfdx-http2-3.0.3.drv' failed to build
error: 2 dependencies of derivation '/nix/store/3q6pdacjq5ww33r549p45szfsbh3x6lb-asn1-parse-0.9.5.drv' failed to build
error: 6 dependencies of derivation '/nix/store/4zdmwjp2whf41kyyxrmdh3c7q25k871c-x509-1.7.7.drv' failed to build
error: 2 dependencies of derivation '/nix/store/rjn1ibzmb34v71i7zp9ff3w0nna099xn-warp-3.3.23.drv' failed to build
error: 5 dependencies of derivation '/nix/store/x8ihl783x2ln77kka4bwvi2zczx910i9-x509-store-1.6.9.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c5yp3wpzqjg0n3g3arcsy77n3xkchaqk-wai-extra-3.1.13.0.drv' failed to build
error: 3 dependencies of derivation '/nix/store/aj13ay776l4wrfgkrfzaqxy6rqhd3pld-x509-system-1.6.7.drv' failed to build
error: 7 dependencies of derivation '/nix/store/wfx5l7ag58v7c5z11729cin1wba64c0f-x509-validation-1.6.12.drv' failed to build
error: 1 dependencies of derivation '/nix/store/va1ilj5ja7f05rxdflf0f67zm51ydbf0-hspec-wai-0.11.1.drv' failed to build
error: 7 dependencies of derivation '/nix/store/36sajpc66ckcxld5lnjfgygkrgk73r35-tls-1.5.8.drv' failed to build
error: 4 dependencies of derivation '/nix/store/p2g82ykyf19sv0ny3wxykkw35ki6xfid-wai-app-static-3.1.7.4.drv' failed to build
error: 7 dependencies of derivation '/nix/store/jmfbq7x623jr9mk4w4diacl5qfry403p-connection-0.3.1.drv' failed to build
error: 4 dependencies of derivation '/nix/store/66p8gm5i3jv6gl9n1wr6rgbpk83ibd5l-servant-server-0.19.2.drv' failed to build
error: 4 dependencies of derivation '/nix/store/ib0gb782sdwgn3175l1fnysqvkam1iwh-http-client-tls-0.3.6.1.drv' failed to build
error: 5 dependencies of derivation '/nix/store/nv35kwkqnnff11pd9a6zgzs164cvhqyk-pandoc-2.19.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vhds2xmidg4kpi4cwiczal7gkap1n43w-gssdp-1.6.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cqwn1w8v8ywzq74bs8k6kycc7605fhn0-gupnp-1.6.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9r67yzfn8mkk4l39n2zaxzlvpy63cv9f-gupnp-igd-1.6.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3f13xl9qnm4lrf3szw5j6xk72xgl8bzv-libnice-0.1.21.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f760zrj30y8l4s1wgi42jqsgpqr71lzx-gst-plugins-bad-1.22.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wylnp8dpg4najmv9yabqrf5xbb8s844s-nvidia-vaapi-driver-0.0.10.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5m2flcllf2pzibfgnmgyz75gqd9a8yc5-opengl-drivers-32bit.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8d71vyy40yky12qdvn2g6mnycaxy7nj8-steam-run-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pfrcsp0fnxi83cppbxzlfsgrcjyh170h-steam-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vind0y1x203xn71q4zhzz7n896rpg4sj-nixos-tmpfiles.d.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kh2wbab981bqr2pj8rn9720v2k30hi7l-steam-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9lknz8h7cys7xnyzqcldm8rbhw5ikxwy-steam-run-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l1fxh2ajypw10ha6b6zpkw4h8czzpcgy-steam-bwrap.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gc0hhkq4iw71pf3kylv6mps1zjibf2q9-steam-run-bwrap.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6n2xnzc7jg70w5f04vsg32j4gv24ws6x-tmpfiles.d.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b4j4kb3qc9r0gb153syhzx42ni5qs69a-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fhdr1qnrjbb0110ld2aabgnsz82a6jqf-steam.drv' failed to build
```

**Comment by vcunat** [comment]
Some bigger regressions:
- [ ] `opencv3` `opencv4`: some issue with C++ version  (all platforms)
  https://hydra.nixos.org/build/231540730
  https://hydra.nixos.org/build/231464517
  maintainer: @basvandijk
- [ ] `python3Packages.rapidfuzz`
  https://hydra.nixos.org/build/231491195/nixlog/1/tail
  maintainer: @dotlambda
- [ ] `swift` (all platforms): possibly also C++ version issues
  https://hydra.nixos.org/build/231401105/nixlog/1/tail
  maintainers: @dtzWill, @trepetti, @dduan, @trundle, @stephank

**Comment by tobim** [comment]
The opencv failures are also fallout from protobuf now exposing cxxStandard sensitive abseil types in it's public headers. I believe the best way to solve this would be #196718 (or just building abseil with c++17 on all platforms). Just building opencv with c++17 does not work, because `libopencv_dnn` hardcodes c++11 and fails.

I think for the scope of this staging cycle we should try to pin opencv to use `protobuf3_21`.

**Comment by tobim** [comment]
`grpc` failed `x86_64-darwin`: https://hydra.nixos.org/build/231544801/nixlog/1

I'm not sure how to resolve, maybe `-mmacosx-version-min=10.14` does the trick (@marsam?)

**Comment by reckenrode** [comment]
> `grpc` failed `x86_64-darwin`: https://hydra.nixos.org/build/231544801/nixlog/1
> 
> I'm not sure how to resolve, maybe `-mmacosx-version-min=10.14` does the trick (@marsam?)

Set the deployment target to 10.13+. You may need to override `darwinMinVersion` in the stdenv.

The problem is clang has a hardcoded check for the OS version when using aligned allocations even though libc++ has an implementation using `posix_memalign` that should work back to 10.6. The check is for 10.13 because that is when Apple shipped a libc++ with support for aligned allocations nixpkgs is not using the system libc++, so just lie to clang about the deployment target to work around the check.

**Comment by tobim** [comment]
> ```
> /build/source/build/modules/dnn/opencv-caffe.pb.h:13:2: error: #error "This file was generated by a newer version of protoc which is"
>    13 | #error "This file was generated by a newer version of protoc which is"
>       |  ^~~~~
> ```

Assuming this comes from `opencv4`, this is probably because `buildPackages.protobuf` is used in the derivation. After changing all occurrences to `protobuf3_21` in `pkgs/development/libraries/opencv/4.x.nix` it worked for me.

**Comment by marsam** [comment]
>`grpc` failed `x86_64-darwin`: https://hydra.nixos.org/build/231544801/nixlog/1

Thanks for the heads up!  Fix for grpc on `x86_64-darwin` https://github.com/NixOS/nixpkgs/pull/249249

**Comment by vcunat** [comment]
`opencv`: thanks, my brain wasn't working properly at that point.  Pushed.

BTW closures, the 6.5M of `include/` in .out of one opencv + abseil, those would be candidates for .dev.

**Comment by marsam** [comment]
>`arrow-cpp` remains broken on `*-darwin`

`arrow-cpp` should be also fixed by https://github.com/NixOS/nixpkgs/pull/249249

**Comment by tobim** [comment]
> > arrow-cpp remains broken on *-darwin
>
> arrow-cpp should be also fixed by https://github.com/NixOS/nixpkgs/pull/249249

I'm not sure, the log hints that Arrow's cmake scaffold runs into conflicts because it finds protobuf once in module mode and then later transitively through config mode. I expect it to fail on linux as well.

**Comment by reckenrode** [comment]
I was worried that #245641 might have been what broke Swift, but reverting it didn’t make a difference. I’ve started a `git bisect`, but it’s probably going to take a little while.

**Comment by vcunat** [comment]
- [ ] `libtensorflow` broke, apparently due to update of default protobuf
  https://hydra.nixos.org/build/231679140/nixlog/1/tail
  However I noticed that more recent versions announced several security fixes; @abbradar (meta.maintainer): so perhaps it will be better to try updating first anyway?

**Comment by vcunat** [comment]
Uh, on a "random" sample there are still lots of regressions that look like due to protobuf/abseil
https://hydra.nixos.org/eval/1798576?compare=1798563#tabs-now-fail

**Comment by sternenseemann** [comment]
Everything up to pandoc can be built on i686-linux now, but pandoc's test suite fails for still unknown reasons specifically on i686.

**Comment by reckenrode** [comment]
I ran `git bisect` twice to be sure, but 6f2b3ba027f0d74614ba1b21f15ea45b0beb0385 is what broke Swift. The problem is in in `makeClangWrapper`. It tries to modify the wrapper, which doesn’t work as expected because the `exec` statement is gone. 
 https://github.com/NixOS/nixpkgs/blob/0b6f3e17dda02c9cf1e8edc6e411ba37093f09e2/pkgs/development/compilers/swift/compiler/default.nix#L126_L138

I think I have a fix. It’s building right now. It accommodates 6f2b3ba027f0d74614ba1b21f15ea45b0beb0385 without reverting it (since it’s needed by Darwin for clang 16).

**Pull request merged**
