### PR TITLE
crystal: 0.23.1 -> 0.24.1

### PR DESCRIPTION
**Pull request by sifmelcara**
###### Motivation for this change

New stable release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

* upstream renamed `doc` target to `docs`
* upstream now provides statically linked version of prebuilt compiler, so there is no need to fix binary anymore
* I use my own `unpackPhase` because upstream provided archives (source and the compiler binary) have the same top directory name

### CODE REVIEW

**Comment by sifmelcara** [comment]
I found that we need to update `shards` to support `crystal 0.24.1`, so the package is updated.

**Comment by grahamc** [comment]
@GrahamcOfBorg eval
@GrahamcOfBorg build shards crystal

**Comment by grahamc** [comment]
@sifmelcara the package says it supports darwin, but the build suggests it doesn't. Since you're a maintainer: should the build get fixed for darwin? should the package say it doesn't support darwin? should we ignore the error for now?

**Comment by sifmelcara** [comment]
Yes it should build on darwin.
It seems like a llvm issue which causes `darwin_x86_64`'s prebuilt binary not working correctly.
upstream discussion is here: https://github.com/crystal-lang/crystal/issues/4719

I just took crystal maintainer's latest suggestion in `https://github.com/Homebrew/homebrew-core/pull/22091` (suggests to add `--no-debug` to crystal flags) and force updated this pr.

@grahamc could you please tell @GrahamcOfBorg to try again? thank you very much

**Comment by orivej** [comment]
@GrahamcOfBorg build shards crystal

**Pull request merged**
