### PR TITLE
jetbrains.idea-ultimate: 2017.1.4 -> 2017.1.5

### PR DESCRIPTION
**Pull request by uskudnik**
###### Motivation for this change
New version got released

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bennofs** [comment]
Should probably update `jetbrains.idea-community` as well (in a separate commit)

**Comment by bennofs** [comment]
Merged, thanks!

**Comment by uskudnik** [comment]
@bennofs I'm probably missing something - I don't see any PR that would update the rest?

**Comment by bennofs** [comment]
@uskudnik https://github.com/NixOS/nixpkgs/compare/master~5...master

**Comment by uskudnik** [comment]
@bennofs Ah, my bad, didn't check master, only looked at PRs :)

**Pull request closed without merging**
