### PR TITLE
pam_mount: do not re-prompt for password

### LINKED ISSUE #44586: nixos-rebuild test (and switch) causes pam_mount to remount
## Issue description

Within the last couple of weeks, doing ```nixos-rebuild test``` causes pam_mount to remount encrypted home directories and thus asking for passwords. This wasn't the case in the past.

Relevant output:
```
building '/nix/store/p6bflh7n5zy2dql8l45mix9qnzq65hbk-nixos-system-mildred-18.09.git.98592c5da79M.drv'...
activating the configuration...
setting up /etc...
reenter password for pam_mount:
(mount.c:68): Messages from underlying mount program:
(mount.c:72): crypt_activate_by_passphrase: File exists
(pam_mount.c:522): mount of /dev/mapper/vg0-lv_home_peter failed
kbuildsycoca5 running...
```

### Steps to reproduce

1. Set ```users.users.some_user.cryptHomeLuks = "/dev/mapper/some_lv";```
2. Execute ```nixos-rebuild test```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.11, NixOS, 18.09.git.98592c5da79M (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`
 - channels(peter): `""`
 - nixpkgs: `/home/peter/src/active/nixpkgs_unstable`

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

nixos-rebuild test causes pam_mount to prompt for a password when running with
an encrypted home:

```
building '/nix/store/p6bflh7n5zy2dql8l45mix9qnzq65hbk-nixos-system-mildred-18.09.git.98592c5da79M.drv'...
activating the configuration...
setting up /etc...
reenter password for pam_mount:
(mount.c:68): Messages from underlying mount program:
(mount.c:72): crypt_activate_by_passphrase: File exists
(pam_mount.c:522): mount of /dev/mapper/vg0-lv_home_peter failed
kbuildsycoca5 running...
```

This change makes pam_mount not prompt. It still tries to remount (and fails in
the process) but that message can be ignored.

Fixes: #44586

Reference: https://unix.stackexchange.com/a/273894

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Cc @samueldr

**Comment by samueldr** [comment]
Any difference in behaviour between `switch` and `test`, and if so, why would there be?

Additionally, most mounting-related tasks are applied live with `test` and `switch`, (which is a bit annoying when failing and systemd kicks you to the rescue mode!)

**Comment by peterhoeg** [comment]
> Any difference in behaviour between switch and test, and if so, why would there be?

No difference

> Do I misunderstand that this would break the assumption of mounting un-mounted devices during switch and test?

With ```disable_interactive```, we are dependent on the login manager passing down the password to ```pam_mount```. So if you add an encrypted device which wasn't there at the time of session start and do ```nixos-rebuild```, it would not be available.

The problem without the option is the repeated prompts which happen *all* the time.

**Comment by peterhoeg** [comment]
@samueldr any thoughts on how we can move this forward?

**Comment by peterhoeg** [comment]
@samueldr - do you still have any concerns?

**Pull request merged**
