### PR TITLE
shogun: remove non-distributable SVMlight code

### PR DESCRIPTION
**Pull request by smancill**
###### Motivation for this change

Shogun is using non-distributable SVMLight code that should be removed from the package.

SVMLight uses a [non-standard license](https://github.com/shogun-toolbox/shogun/blob/shogun_6.1.4/doc/license/LICENSE_SVMlight.md) that doesn't allow distribution without the author's permission:

> The software must not be modified and distributed without prior permission of the author.

----

I am working on a PR to fix Shogun on Darwin and add it as a Python module, and that's why I found that currently it is built with SVMLight, which should not be packaged on a distribution. Upstream's own Debian package, Fedora, Conda, they all remove it.

I think this had to be its own PR, and maybe backported to 21.05.

###### Things done

Remove all SVMLight code when building the binary package.

Use upstream's own script to do it (which they use to create and distribute their own Debian package), with a few fixes (see added patch file).

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin (currently broken on Darwin, I will send the fix in a new PR)
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
> Shogun is using non-distributable SVMLight code that should be removed from the package.
> 
> SVMLight uses a [non-standard license](https://github.com/shogun-toolbox/shogun/blob/shogun_6.1.4/doc/license/LICENSE_SVMlight.md) that doesn't allow distribution without the author's permission:

Seems like it would also be a good idea to set `meta.license = if withSvmLight then licenses.unfree else licenses.gpl3` so that it isn't redistributed by hydra.

**Comment by smancill** [comment]
> > Shogun is using non-distributable SVMLight code that should be removed from the package.
> > SVMLight uses a [non-standard license](https://github.com/shogun-toolbox/shogun/blob/shogun_6.1.4/doc/license/LICENSE_SVMlight.md) that doesn't allow distribution without the author's permission:
> 
> Seems like it would also be a good idea to set `meta.license = if withSvmLight then licenses.unfree else licenses.gpl3` so that it isn't redistributed by hydra.

That's a good catch, I didn't think about it.

Fixed on latest force-push.

**Review by r-burns — APPROVED** [review]
Changes LGTM

Result of `nixpkgs-review pr 136526` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>shogun</li>
  </ul>
</details>

**Comment by smancill** [comment]
Should it be backported to 21.05, or there is no need since 21.11 is close?

**Pull request merged**
