### PR TITLE
Revert "buildDotnetModule: add passthru.fetch-deps"

### PR DESCRIPTION
**Pull request by legendofmiracles**
###### Motivation for this change
Reverts https://github.com/NixOS/nixpkgs/pull/150587 for now, since it breaks functionality needed by https://github.com/NixOS/nixpkgs/pull/148541. 
A quick recursive grep made me fairly certain that no package relies on the fetcher script yet. 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
I'd be better if we tried to fix the problem instead of just reverting the commit.

**Comment by legendofmiracles** [comment]
Agreed, I talked with Ivar, and they said that they would try to find a fix in the next few days. Until then they agreed that it would be best to revert it. 

If I knew why this would be happening I would have submitted a patch for that, but this code is definitely at fault. When I uncommented it, then my own passthru attribute worked as expected

**Comment by legendofmiracles** [comment]
Although I'm not betting on the the ASF PR being merged within the next days, we can probably leave it in a broken state until a fix is found, without anyone really caring.

I suppose we could just merge this when ASF gets merged, if a fix is found until then, great! If not, not a big deal for now.

**Comment by IvarWithoutBones** [comment]
I PR'd a proper (i hope) fix to this in #152758 :)

**Pull request closed without merging**
