### PR TITLE
asterisk: Bump all packages

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

Packages were out of date

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
What do you think about adding yourself as maintainer to this? Since you've been adding new branches, removing old ones and just doing general maintenance on this, lately?

**Comment by dasJ** [comment]
Idk. I have no idea on how to configure/use Asterisk, I just provide the package for someone else to use and configure (as you know). I don't think I'm the right person to maintain this. Maybe ask again in 3 releases or so :D

**Review by yorickvP — APPROVED** [review]

**Comment by yorickvP** [comment]
I also don't currently use asterisk. I may again in the future, but for now, maybe we should find a user.

**Comment by dasJ** [comment]
Result of `nixpkgs-review pr 103201` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103201` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>asterisk (asterisk-lts ,asterisk-stable ,asterisk_18)</li>
    <li>asterisk-module-sccp</li>
    <li>asterisk_13</li>
    <li>asterisk_16</li>
    <li>asterisk_17</li>
  </ul>
</details>

**Comment by erictapen** [comment]
Backported in a7334d2499f73fb4ff5733642e711e7c840abd66.

**Pull request merged**
