### PR TITLE
zarf: add shell completion

### PR DESCRIPTION
**Pull request by a1994sc**
## Description of changes

Added shell complete settings for the package `zarf`.

cc-ing: @ragingpastry

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SFrijters** [comment]
Could you guard the generation of the completions for cross-compilation, e.g. `lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform)`?

Also, the most common practice is to generate and install shell completions in one step, without temp files, see for example https://github.com/NixOS/nixpkgs/pull/327130 .

**Comment by a1994sc** [comment]
> Could you guard the generation of the completions for cross-compilation, e.g. `lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform)`?

I'm not 100% sure you mean by this, do you mind elaborating?

> Also, the most common practice is to generate and install shell completions in one step, without temp files, see for example #327130 .

Sure, I can update the PR in a little bit, thank you.

**Comment by SFrijters** [comment]
> > Could you guard the generation of the completions for cross-compilation, e.g. `lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform)`?
> 
> I'm not 100% sure you mean by this, do you mind elaborating?

If you build the executable for a platform that cannot be run from the build platform itself, the generation of the shell completion files will fail. For example, if you run this on the current state of the PR:

```
$ nix build .#pkgsCross.aarch64-multiplatform.zarf -L
[...]
Running phase: installPhase
evaling implicit 'postInstall' string hook
/nix/store/wnbrksan5znxv61w053kvq0n980yvhs2-stdenv-linux/setup: line 178: /nix/store/m6ngbcd95zxzn28kml1wm50bhkf656rx-zarf-aarch64-unknown-linux-gnu-0.35.0/bin/zarf: cannot execute binary file: Exec format error
```
 
The PR I linked should have a clear example how to use the condition.

> > Also, the most common practice is to generate and install shell completions in one step, without temp files, see for example #327130 .
> 
> Sure, I can update the PR in a little bit, thank you.

Another small nitpick, there is some (not very clearly defined) order that people like to see in the attributes (https://github.com/jtojnar/nixpkgs-hammering/blob/0c54b7121a21f79e580773a46fc8d51482dc1d1c/explanations/attribute-ordering.md); in this case `nativeBuildInputs` should probably come between `proxyHash` and `preBuild`.

**Comment by a1994sc** [comment]
Ah ok, sure I will take a look at that and update my PR. Thank you very much!

**Comment by a1994sc** [comment]
@SFrijters Updated the PR

**Review by SFrijters — APPROVED** [review]
Tested build with `nix build .#zarf` and `nix build .#pkgsCross.aarch64-multiplatform.zarf` from `x86_64-linux`.

Note that you could avoid the intermediate `zarf.$shell` file, following the "named fd" method described in https://nixos.org/manual/nixpkgs/unstable/#installshellfiles , but I'll leave that to the package maintainer to decide.

**Comment by Aleksanaa** [comment]
Yes, would be better to

**Comment by a1994sc** [comment]
Updated the PR to simplify the `installShellCompletion` step

**Comment by Aleksanaa** [comment]
Also please reword commit message to `zarf: add shell completion`

**Comment by a1994sc** [comment]
Updated

**Comment by a1994sc** [comment]
Thank you @Aleksanaa and @SFrijters !

**Pull request merged**
