### PR TITLE
Netbox 3.7.1

### PR DESCRIPTION
**Pull request by minijackson**
## Description of changes

- add `netbox_3_7` at 3.7.1
- make it the default `netbox` package
- make it the default for NixOS if `stateVersion >= 24.05`
- make the "netbox-upgrade" NixOS test test the upgrade from 3.6 to 3.7
- remove `netbox_3_5`
- mark `netbox_3_6` as EOL

cc @RaitoBezarius 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
You can ignore the `pkgs/by-name` check failure, this is not a problem of this PR, the check itself needs to be adjusted. Merging this PR won't be a problem for `pkgs/by-name`.

**Comment by lukegb** [comment]
In your description you write

> add netbox_3_4 at 3.7.1

Did you mean `netbox_3_7`?

**Comment by minijackson** [comment]
@lukegb yes that's a typo. Fixed it, thanks!

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 282929` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.netbox_3_7</li>
  </ul>
</details>

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 282929` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>netbox_3_6</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>netbox (netbox_3_7)</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
I tested also the upgrade, seems to work fine, but I don't have permissions to deploy my non-trivial production Netbox, so I cannot test there. I think we can move on.

**Comment by infinisil** [comment]
> You can ignore the `pkgs/by-name` check failure, this is not a problem of this PR, the check itself needs to be adjusted. Merging this PR won't be a problem for `pkgs/by-name`.

Will be fixed with https://github.com/NixOS/nixpkgs/pull/285089

**Pull request merged**
