### PR TITLE
zed-editor: add fhs passthru

### LINKED ISSUE #309662: Zed Editor package can't use language servers
### Describe the bug
Zed has the same issue as many other editors where it tries to run dynamically-linked libraries. A FHS chroot like `vscode-fhs` would probably fix this.

### Steps To Reproduce
1. Open Zed
2. Attempt to use any language server

### Expected behavior
Zed is able to download and execute the language server of choice.

### Additional context
Here is the log entry:
```
2024-05-06T18:29:14-04:00 [INFO] starting language server. binary path: "/home/jack/.local/share/zed/languages/rust-analyzer/rust-analyzer-2024-05-06", working directory: "/home/jack/Code/Rust/CodeCheck", args: []
2024-05-06T18:29:14-04:00 [ERROR] crates/lsp/src/lsp.rs:352: cannot read LSP message headers
2024-05-06T18:29:14-04:00 [ERROR] failed to start language server "rust-analyzer": server shut down
2024-05-06T18:29:14-04:00 [ERROR] server stderr: Some("Could not start dynamically linked executable: /home/jack/.local/share/zed/languages/rust-analyzer/rust-analyzer-2024-05-06\nNixOS cannot run dynamically linked executables intended for generic\nlinux environments out of the box. For more information, see:\n")
```

### Notify maintainers
@GaetanLepage 
@niklaskorz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05pre621993.25865a40d14b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by niklaskorz**
## Description of changes

Closes #309662 

This adds an [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) compliant environment for zed-editor as a passthru variable (`zed-editor.fhs` and `zed-editor.fhsWithPackages`).
The definition is based on [`vscode.fhs`](https://github.com/NixOS/nixpkgs/blob/ad416d066ca1222956472ab7d0555a6946746a80/pkgs/applications/editors/vscode/generic.nix#L64), but I have kept the packages to a minimum for now.
We can extend it in the future if we get reports of commonly needed packages missing.
I have also left out `dieWithParent = false;` from `vscode.fhs` as it does not seem to be needed for Zed.
I'm not sure if we want or need a top-level package declaration à la `zed-editor-fhs` so this PR only adds them to the package's passthru,

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by k3yss** [comment]
Result of `nixpkgs-review pr 339852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by k3yss** [comment]
Result of `nixpkgs-review pr 339852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by GaetanLepage — APPROVED** [review]
LGTM !

**Comment by GaetanLepage** [comment]
Just to be sure, has anyone actually tested the feature locally ?

**Comment by niklaskorz** [comment]
> Just to be sure, has anyone actually tested the feature locally ?

I've tested it with the Zed Python extension, which doesn't work without the FHS but works without. I'd be happy the hear about other extensions to know if we have to add more packages than glibc.

**Comment by GaetanLepage** [comment]
Ok great !
As there is no real risk, I will go and merge this now. Thanks for the implem :)

**Comment by k3yss** [comment]
@niklaskorz @GaetanLepage 

I can't use `rust-analyzer` with this package, I tried these things:
1: Let `zed-editor` install `rust-analyzer` by itself; stuck on retrying
2: Specify the `rust-analyzer` lsp, manually by doing 
```json
  "lsp": {
    "rust-analyzer": {
      "binary": {
        "path": "/nix/store/9yy1qvl2w9pwxdddvf2gmq903fjabqkx-rust-analyzer-2024-03-25/bin/rust-analyzer"
      }
    }
```
The logs can be found [here](https://gist.github.com/k3yss/9e44c25fd8582289b50d0c29e6e14ea9 )


Both of which doesn't seem to work, is there something missing here

**Comment by jansol** [comment]
My solution is to have `rustup` in my user environment (and used that to install rust-analyzer) and this in zed's config, which is working beautifully:
```json
  "lsp": {
    "rust-analyzer": {
      "binary": {
        "path": "/run/current-system/sw/bin/bash",
        "arguments": ["-c", "if [ -e flake.nix ]; then nix develop --command rust-analyzer; else rust-analyzer; fi"]
      }
    }
  }
```

Rust-analyzer in particular is problematic since the rustup version at least is just a shim that invokes rustup to first locate/update the binary corresponding to the right toolchain for the project. The indirection through bash is so that I can run rust-analyzer in a nix dev shell that contains system dependencies (since I usually set up a flake.nix whenever I have external deps).

I'm not sure how rust-analyzer behaves if you don't use rustup for it though.

**Comment by k3yss** [comment]
@jansol This works for me as well, thank you so much! I wonder if there is a better way for zed to handle this

**Comment by PedroHLC** [comment]
Mind if I push a PR adding a `withFHS ? true` here? I don't need this at all…

**Pull request merged**
