### PR TITLE
flask: 0.10.1 -> 0.11.1

### PR DESCRIPTION
**Pull request by rasendubi**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lsix** [comment]
`octoprint` seems to be broken by this update (it specifically requires `flask<0.11,>=0.9`).

**Comment by rasendubi** [comment]
What's the correct way to resolve the issue? I would add another version of the Flask besides current one.

**Comment by lsix** [comment]
Usually, we have 2 options:

- Check if the broken package have an update available that would work with the updated dependency
- Introduce a new attribute in the package set pinning the currently working vresion (`flask_0_10_1`), use that as dependency for the broken derivation and update the main attribute (`flask`). This can be used until the broken package have an update that can follow upstream flask.

**Comment by rasendubi** [comment]
I've checked the broken package before asking—it does not have an update.

I'll update the PR during the week.

**Comment by FRidh** [comment]
Apparently octoprint devs choose to always pin a flask version. They've introduced 0.10 in https://github.com/foosel/OctoPrint/commit/261f6709a319b8464148a52fb233e7171988ee70, which is well before 0.11 was released. 

A quick scan of the 0.11 release notes doesn't show any real changes, just new features. Therefore, I think patching the setup.py to allow any flask version will result in a working octoprint.

**Comment by lsix** [comment]
Fixing the `setup.py` file works for me in such situation.

**Comment by rasendubi** [comment]
I have updated octoprint to build against any flask version.

/cc octoprint maintainer @abbradar.

**Comment by abbradar** [comment]
Have you tried to run OctoPrint with this patch? If it runs and shows status page it should be fine. I can run it myself, but much later this new week -- I don't have much time now.

**Comment by rasendubi** [comment]
@abbradar just ran it. Status page is fine.

**Review by abbradar — APPROVED** [review]

**Comment by abbradar** [comment]
(and thanks for the test!

**Pull request merged**
