### PR TITLE
grub: support initrd secrets

### LINKED ISSUE #26175: Support initrd secrets in GRUB
## Issue description

Ditto. I have noticed this accidentially whily working at #26165.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 65477dcd341dcdcdc58b01e362e18a903bf94874

cc @shlevy

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

This PR fixes #26175 by adding support for `boot.initrd.secrets` to grub. 

###### Things done

The Grub specific option `boot.loader.grub.extraInitrd` (#22969) is removed in favor of the generic `boot.initrd.secrets` option. My implementation is similar to how `extraInitrd` was implemented, except it runs `append-initrd-secrets` instead of using a user supplied initrd. I use a separate second initrd, rather than appending to the main initrd (as is done for systemd-boot), because grub allows the option of not copying the initrd from the nix store, so it may be immutable.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lopsided98** [comment]
There doesn't seem to be a single maintainer for grub so I'll just cc @joachifm. Let me know if someone else would be better to review this.

**Comment by joachifm** [comment]
Looks okay to me. A changelog entry would be nice.

**Comment by lopsided98** [comment]
I added a changelog entry.

**Comment by lopsided98** [comment]
Is there anything preventing this from being merged?

**Comment by lopsided98** [comment]
@joachifm Can this be merged?

**Pull request merged**
