### PR TITLE
python311Packages.astropy: 5.2.1 -> 5.2.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Fix build (https://hydra.nixos.org/build/219153243)

ZHF: #230712

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 231817` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python310Packages.astroquery</li>
    <li>python310Packages.astroquery.dist</li>
    <li>python310Packages.hickle</li>
    <li>python310Packages.hickle.dist</li>
    <li>python310Packages.pywick</li>
    <li>python310Packages.pywick.dist</li>
    <li>python310Packages.spectral-cube</li>
    <li>python310Packages.spectral-cube.dist</li>
    <li>python310Packages.sunpy</li>
    <li>python310Packages.sunpy.dist</li>
    <li>python311Packages.astroquery</li>
    <li>python311Packages.astroquery.dist</li>
    <li>python311Packages.hickle</li>
    <li>python311Packages.hickle.dist</li>
    <li>python311Packages.spectral-cube</li>
    <li>python311Packages.spectral-cube.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
  </ul>
</details>
<details>
  <summary>44 packages built:</summary>
  <ul>
    <li>python310Packages.aplpy</li>
    <li>python310Packages.aplpy.dist</li>
    <li>python310Packages.asdf</li>
    <li>python310Packages.asdf.dist</li>
    <li>python310Packages.astropy</li>
    <li>python310Packages.astropy-healpix</li>
    <li>python310Packages.astropy-healpix.dist</li>
    <li>python310Packages.astropy.dist</li>
    <li>python310Packages.casa-formats-io</li>
    <li>python310Packages.casa-formats-io.dist</li>
    <li>python310Packages.drms</li>
    <li>python310Packages.drms.dist</li>
    <li>python310Packages.pyavm</li>
    <li>python310Packages.pyavm.dist</li>
    <li>python310Packages.pyregion</li>
    <li>python310Packages.pyregion.dist</li>
    <li>python310Packages.pyvo</li>
    <li>python310Packages.pyvo.dist</li>
    <li>python310Packages.radio_beam</li>
    <li>python310Packages.radio_beam.dist</li>
    <li>python310Packages.reproject</li>
    <li>python310Packages.reproject.dist</li>
    <li>python311Packages.aplpy</li>
    <li>python311Packages.aplpy.dist</li>
    <li>python311Packages.asdf</li>
    <li>python311Packages.asdf.dist</li>
    <li>python311Packages.astropy</li>
    <li>python311Packages.astropy-healpix</li>
    <li>python311Packages.astropy-healpix.dist</li>
    <li>python311Packages.astropy.dist</li>
    <li>python311Packages.casa-formats-io</li>
    <li>python311Packages.casa-formats-io.dist</li>
    <li>python311Packages.drms</li>
    <li>python311Packages.drms.dist</li>
    <li>python311Packages.pyavm</li>
    <li>python311Packages.pyavm.dist</li>
    <li>python311Packages.pyregion</li>
    <li>python311Packages.pyregion.dist</li>
    <li>python311Packages.pyvo</li>
    <li>python311Packages.pyvo.dist</li>
    <li>python311Packages.radio_beam</li>
    <li>python311Packages.radio_beam.dist</li>
    <li>python311Packages.reproject</li>
    <li>python311Packages.reproject.dist</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
Alternative: https://github.com/NixOS/nixpkgs/pull/255124 .

**Comment by doronbehar** [comment]
I'm closing this, there's a merge conflict, and this update should be revised...

**Comment by doronbehar** [comment]
> Astropy builds for me on macos 10.15 & nixos x86_64 with this.

The point of this PR was to update `python3.pkgs.astropy` so that `python3.pkgs.astroquery` won't fail to build. This PR didn't succeed in that.

**Pull request closed without merging**
