### PR TITLE
pkgs/development/{node-packages,web}: stdenv.lib -> lib

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

Part of #108938

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Is any of those files generated by node2nix?

**Comment by prusnak** [comment]
> Is any of those files generated by node2nix?

Most probably yes. 

> Is any of those files generated by node2nix?

Yes, but I tried to reproduce the changes the same way they were introduced in https://github.com/svanderburg/node2nix/pull/224

**Comment by SuperSandro2000** [comment]
> Some of them yes. But I tried to reproduce the changes the same way they were introduced in svanderburg/node2nix#224

Would it be feasible to track that patch if it takes upstream a while to merge it?

**Comment by prusnak** [comment]
I will close this PR for now. We can reopen/rebase this later if still needed.

**Pull request closed without merging**
