### PR TITLE
git: 2.17.1 -> 2.18.0, round 2

### PR DESCRIPTION
**Pull request by dtzWill**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
@layus is the hero behind this! See: https://github.com/NixOS/nixpkgs/pull/42376#issuecomment-399989290

Anyway I haven't tested this with the breakage it caused on various PR's, will do so shortly.

**Comment by dtzWill** [comment]
LGTM -- tried `nix-build -A lollypop.src --check` (might need to run without `--check` first time) with/without the fix from @layus, seems to work with and fails without. \o/

**Comment by dtzWill** [comment]
LGTM but I'd prefer someone else to merge / confirm since I/we got it "wrong" the first time around :).

**Comment by worldofpeace** [comment]
I tested it too and it seems to work :hand:

**Comment by ciil** [comment]
lgtm

**Comment by xeji** [comment]
the chicken says: staging, maybe?

**Comment by dtzWill** [comment]
Sounds like a plan, no rush here AFAIK anyway.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build git gitFull

**Comment by FRidh** [comment]
What was causing the failures with the last major bump causing it to be reverted 3 times? Is it a reasonable risk here as well? Is it perhaps an idea to test it by building a smaller job?

**Pull request merged**
