### PR TITLE
ffcast: fix cross-compilation

### PR DESCRIPTION
**Pull request by sikmir**
###### Description of changes
* Fix cross-compilation
* Update download url
* Fix wrapping
* Fix license

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux (cross)
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mindavi — APPROVED** [review]

**Comment by Mindavi** [comment]
Cleanup looks nice too.

**Comment by guyonvarch** [comment]
@sikmir Feel free to take over the maintenance of `xrectsel` and `ffcast` if you’d like, as I am no longer using these.

**Comment by Mindavi** [comment]
Oops, I overlooked that .ffcast-wrapped has #!/bin/bash in it's script. You need to add bash to buildInputs to ensure the shebang is properly rewritten.

**Comment by sikmir** [comment]
> Oops, I overlooked that .ffcast-wrapped has #!/bin/bash in it's script. You need to add bash to buildInputs to ensure the shebang is properly rewritten.

But it's properly rewritten:
```
$ cat result/bin/.ffcast-wrapped | grep "bin/bash"
#!/nix/store/3j18grljsyy4nxc078g00sy4cx6cf16g-bash-5.1-p16/bin/bash
```

What is wrong with it?

**Comment by Mindavi** [comment]
That's not the aarch bash, is it?

**Comment by sikmir** [comment]
I see, you're right. I will create another PR to fix it. Thanks.

**Pull request merged**
