### PR TITLE
[WIP] pythonPackages.numpy-mkl: refactor adding mkl support

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Would love to see packaging python applications with mkl support similar to how `conda` packages `mkl`. I realize that this pull request is very trivial and probably not the correct approach to packaging mkl into numpy and would love any input. Hopefully this pull request gets enough input that it can be used as a guide on how to integrate mkl with python packages. Packages that I would like to eventually target are `NumExpr`, `SciPy`, and `Scikit-Learn`.

I would like to especially thank @bhipple for the `mkl` PR! I have been wanting that for a long time but did not know how to do it. If at all possible I  would like to hear input from @bhipple and @markuskowa. @smaret you provided great input making sure that it works with darwin and since I do not have a mac I would appreciate any help.

I am aware that this will cause mass rebuilds and will eventually move to staging when it is working. Currently if it is on staging it will require mass rebuilds making it harder to test.

###### Things done

Adding mkl support for `numpy`. As of now this PR does not succeed in building. The numpy tests fail.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks. I've pushed 277b73ab6fecd5c8f76b8eb9cc2fc1e036aee0db to staging.

**Comment by costrouc** [comment]
@FRidh this pull request is not complete sorry and it won't build properly. I'll add the WIP headline

**Comment by FRidh** [comment]
I made some more modifications and now the packages that I tested seem to work with it.

**Comment by costrouc** [comment]
Oh great and thank you! I look forward to benchmarking the performance differences between the two builds `numpy` and `numpy-mkl`.

**Comment by bhipple** [comment]
Thanks for this work @costrouc and @FRidh!  I have a bit of a side project to package as much of the Anaconda distribution as possible in Nix, so that scientific computing users have more choices on how to install and distribute their packages.  It's great to see others are interested in this as well!  CC @jluttine

**Comment by costrouc** [comment]
@bhipple this is a goal of mine as well. I am happy to help in any way to help theses goals.

You may be interested that I have [a PR that will add binderhub](https://github.com/jupyter/repo2docker/pull/407) support for `nix`. This will mean that any nix repository can be turned into an interactive notebook.

Goals for me include: 
  - adding `mkl` support to necessary packages (scipy and scikit-learn)
  - cleaning up the python ecosystem in `nix`
  - add support for jupyterlab extensions lots of javascript...
  - adding ways to benchmark different package configurations (e.g. openblas vs mkl)

**Pull request closed without merging**
