### PR TITLE
keepass-keefox: 1.5.4 -> 1.6.0b1

### PR DESCRIPTION
**Pull request by anicole**
Bump plugin version to 1.6.0b1

### CODE REVIEW

**Comment by MindTooth** [comment]
Push a beta version?  Maybe wait for stable 1.6 release?

**Comment by zimbatm** [comment]
@anicole we try to keep the stable version current. You can always submit a _HEAD or Unstable version in parallel or wait for 1.6 to be released.

**Comment by anicole** [comment]
Understood, sorry for the extra noise. Closing this for now. :)

**Comment by zimbatm** [comment]
no worries :)

**Pull request closed without merging**
