### PR TITLE
ledger-live-desktop: 2.34.3 -> 2.34.4

### PR DESCRIPTION
**Pull request by andresilva**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Does this package actually work for you? I've tried it a couple times out of curiosity and it fails every time:

```
❯ ./result/bin/ledger-live-desktop 
Ledger Live 2.34.4
init
Checking for update
Generated new staging user ID: e82b9733-e858-5fa0-aa2c-bf9f564aa81c
spawned internal process 143
Update for version 2.34.4 is not available (latest version: 2.34.4, downgrade is disallowed).
internal process 143 got killed by signal SIGSEGV
```

**Comment by andresilva** [comment]
Seems to be working fine for me, I'm on nixos-unstable though.

**Comment by lovesegfault** [comment]
> Seems to be working fine for me, I'm on nixos-unstable though.

Same here, I wonder why it segfaults here every time :P

**Comment by andresilva** [comment]
Does the current version work for you? I really have no clue tbh.

**Pull request merged**
