### PR TITLE
nix: 2.4 -> 2.5.1

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

 - Get the new release out there and tested.
 - Clean up the expression a bit

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lourkeur** [comment]
Seems like this causes nix-2.3.16 to rebuild. It's not a huge deal but what is that due to and can it be avoided?

**Comment by roberth** [comment]
> Seems like this causes nix-2.3.16 to rebuild. It's not a huge deal but what is that due to and can it be avoided?

9848c378ed3df76a2ccb4c8be9f131c1635371e6 causes this one final time.

We should only add `derivation` arguments that are used by the build. Otherwise, the hash becomes sensitive to things it shouldn't.

**Review by kubukoz — APPROVED** [review]

**Comment by lourkeur** [comment]
Result of `nixpkgs-review pr 151419` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ovftool</li>
  </ul>
</details>
<details>
  <summary>3 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>nix-eval-jobs</li>
    <li>nixStatic</li>
  </ul>
</details>
<details>
  <summary>72 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.hercules-ci-cli</li>
    <li>haskellPackages.hercules-ci-cnix-expr</li>
    <li>haskellPackages.hercules-ci-cnix-store</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.nvfetcher</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>hubstaff</li>
    <li>hydra-unstable</li>
    <li>libnixxml</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixStable ,nix_2_5)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixUnstable</li>
    <li>nix_2_3</li>
    <li>nix_2_4</li>
    <li>nixos-generators</li>
    <li>nixos-option</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nixui</li>
    <li>nvfetcher</li>
    <li>prefetch-yarn-deps</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>rnix-lsp</li>
    <li>terranix</li>
    <li>tests.trivial-builders.references</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>yarn2nix</li>
  </ul>
</details>

**Comment by lourkeur** [comment]
> > Seems like this causes nix-2.3.16 to rebuild. It's not a huge deal but what is that due to and can it be avoided?
> 
> [9848c37](https://github.com/NixOS/nixpkgs/commit/9848c378ed3df76a2ccb4c8be9f131c1635371e6) causes this one final time.
> 
> We should only add `derivation` arguments that are used by the build. Otherwise, the hash becomes sensitive to things it shouldn't.

Thank you, I am satisfied with this answer

**Comment by lourkeur** [comment]
- `nixStatic` is broken due to a pre-existing failure in a dependency
- `nix-eval-jobs` is new:
```
FAILED: src/nix-eval-jobs.p/nix-eval-jobs.cc.o 
g++ -Isrc/nix-eval-jobs.p -Isrc -I../src -I/nix/store/w639nhbzmil3g061if2rnjhbfngqw6rf-nix-2.5.1-dev/include/nix -I/nix/store/ql99k1yggw3gkpka7bp6zqvkn8fsv6xx-boehm-gc-8.0.6-de>
../src/nix-eval-jobs.cc:32:8: warning: base class 'struct nix::MixEvalArgs' has accessible non-virtual destructor [-Wnon-virtual-dtor]
   32 | struct MyArgs : MixEvalArgs, MixCommonArgs
      |        ^~~~~~
../src/nix-eval-jobs.cc:32:8: warning: base class 'class nix::MixCommonArgs' has accessible non-virtual destructor [-Wnon-virtual-dtor]
../src/nix-eval-jobs.cc:32:8: warning: 'struct MyArgs' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
../src/nix-eval-jobs.cc: In function 'void worker(nix::EvalState&, nix::Bindings&, nix::AutoCloseFD&, nix::AutoCloseFD&, const Path&)':
../src/nix-eval-jobs.cc:191:72: error: no matching function for call to 'printValueAsJSON(nix::EvalState&, bool, nix::Value&, std::stringstream&, nix::PathSet&)'
  191 |                   printValueAsJSON(state, true, *metaValue, ss, context);
      |                                                                        ^
In file included from ../src/nix-eval-jobs.cc:20:
/nix/store/w639nhbzmil3g061if2rnjhbfngqw6rf-nix-2.5.1-dev/include/nix/value-to-json.hh:13:6: note: candidate: 'void nix::printValueAsJSON(nix::EvalState&, bool, nix::Value&, co>
   13 | void printValueAsJSON(EvalState & state, bool strict,
      |      ^~~~~~~~~~~~~~~~
/nix/store/w639nhbzmil3g061if2rnjhbfngqw6rf-nix-2.5.1-dev/include/nix/value-to-json.hh:13:6: note:   candidate expects 6 arguments, 5 provided
/nix/store/w639nhbzmil3g061if2rnjhbfngqw6rf-nix-2.5.1-dev/include/nix/value-to-json.hh:16:6: note: candidate: 'void nix::printValueAsJSON(nix::EvalState&, bool, nix::Value&, co>
   16 | void printValueAsJSON(EvalState & state, bool strict,
      |      ^~~~~~~~~~~~~~~~
/nix/store/w639nhbzmil3g061if2rnjhbfngqw6rf-nix-2.5.1-dev/include/nix/value-to-json.hh:16:6: note:   candidate expects 6 arguments, 5 provided
ninja: build stopped: subcommand failed.
```

**Comment by lourkeur** [comment]
eval-jobs fixed :ballot_box_with_check:

**Review by bbjubjub2494 — APPROVED** [review]
LGTM

**Comment by lovesegfault** [comment]
I'm going to land this, but I suggest we, in the next release, just get rid of `nix_2_x` attrs altogether given the new release scheme.

We should have `nix_2_3`, `nix-unstable` (unfortunately named `nixUnstable`), and `nix-stable` aka. `nix`. Otherwise we'll have an billion Nix packages soon.

**Comment by roberth** [comment]
@lovesegfault I don't think they're particularly harmful, in fact they're quite useful for things that use the C++ interface. By the time it reaches a billion, I think the software it's building will take care of that nuisance all by itself. :robot:

**Comment by Mic92** [comment]
I already bumped nix-eval-jobs because I of nix 2.5, but I did not want to handle the nix upgrade completely. Thanks for updating.

**Comment by vcunat** [comment]
Part of this will get picked to 21.11, right?

**Pull request merged**
