### PR TITLE
maintainers: prefix number with underscore

### PR DESCRIPTION
**Pull request by zowoq**
This is the same pattern that is already used for packages, I think it makes sense to reuse it here.

https://github.com/NixOS/nixpkgs/blob/4789d6feafd9ba0613b9f1fd4dcd6b1ed0572f4b/pkgs/top-level/all-packages.nix#L531-L545

GitHub doesn't allow usernames with underscores so these won't collide with another user.

### CODE REVIEW

**Review by samueldr — DISMISSED** [review]
I don't think this is necessary. Though, other Nixpkgs maintainers can agree or disagree, and my judgement shouldn't be a blocker.

The reason it is required for packages is that on the command-line, `--attr` can't work with leading numbers:

```
~/tmp/nixpkgs/nixpkgs 1 $ nix-build -A 0x0
error: syntax error, unexpected INT, at /Users/samuel/tmp/nixpkgs/nixpkgs/pkgs/top-level/all-packages.nix:531:3
```

(You can modify `all-packages.nix` to provide a 0x0 if you want, but the result is the same if it isn't there.)

I don't think we're expected to interact with maintainers using `--attr`; at the time we will, this could be re-considered. After all, this is a relatively minor mechanical change, so hopefully this is a triviality.

In addition, `handle` is not forcibly the same as a GitHub alias. It is possible a user uses Nixpkgs without a GitHub account, even contributes without a GitHub account (yes, technically things are in place for that), and has a prefixed underscore for their handle. In that instance it becomes a bit annoying :) Though we're erring in the world of [aggravating edge cases](https://twitter.com/badedgecases), so don't mind that last point too much.

**Comment by samueldr** [comment]
Sorry, now I see why this is relevant. And this is using an existing precedent.

**Comment by jonringer** [comment]
cc @0x4A6F @1000101

**Review by FRidh — APPROVED** [review]

**Comment by mmahut** [comment]
Oh, not this again, I feel like I spend hours on discussing this trivial case. I don't think
this is a solution, unless it is agreed as a standard (which is in packages names, because there is a real
technical reason for this, not that someone is not paying and testing their changes introducing introduces a bug).

But if feel like this is a trip wire, let's create a meta data check in ofborg, that will be beneficial in the future as well.

**Comment by zowoq** [comment]
> let's create a meta data check in ofborg

Not exactly easy to actually get it done and we might end up moving some checks away from ofborg anyway.

**Comment by worldofpeace** [comment]
cc @0x4A6F @1000101

**Review by worldofpeace — APPROVED** [review]

**Review by 1000101 — CHANGES_REQUESTED** [review]
Fine by me. It's been fun, but became very tiring eventually. It pisses off too many people and since there is no simple solution, it's not worth arguing over.

Let's change it and, ideally, document the need for an underscore somewhere - maybe [here](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix#L27)?

**Review by 1000101 — APPROVED** [review]

**Comment by FRidh** [comment]
I suggest also mapping over the keys and asserting none start with a number.

**Review by 0x4A6F — CHANGES_REQUESTED** [review]
Please use the common pattern ```with maintainers; [ _0x4A6F ];```.

**Comment by zowoq** [comment]
> I suggest also mapping over the keys and asserting none start with a number.

Can you elaborate please?

**Comment by jonringer** [comment]
I'm assuming having CI do something to the effect of:
```
  lib.mapAttrs (name: assert (builtins.match "^([0-9]).*" == null)) lib.maintainers
```
where there's a check that a new maintainer doesn't start with a number.

**Comment by zowoq** [comment]
I don't think adding it to ofborg is a productive use of time as there has been some discussions about moving things away from ofborg. Bus factor is also an issue so I don't want to add more things there anyway.

I don't want to add it as a check that runs on hydra as that depends on someone noticing and caring about it enough to unbreak it, I think we have enough things already that we don't know are broken until after a PR is merged (e.g. the manuals).

I'm happy to implement this and other maintainer checks (e.g. check `github` has a matching `githubId`) via an action that actually catches the errors before merge, when we can actually use actions.

**Comment by jonringer** [comment]
> I'm happy to implement this and other maintainer checks (e.g. check `github` has a matching `githubId`) via an action that actually catches the errors before merge, when we can actually use actions.

I think this would be easy enough to implement as a github action.

**Comment by zowoq** [comment]
Just to be clear about the current status of actions: we can't use them at the moment.

We were using two actions but they were removed because they caused too much disruption. We're now waiting for a couple of things to be resolved before we try them again, I don't really have a timeframe for when that will happen.

I'd want to have those actions running for a couple of weeks without causing any problems before we start adding more.

I see this PR as a slight improvement over the status quo even without a way of enforcing it, I don't think having a check should be a blocker.

**Comment by FRidh** [comment]
I am not suggesting an explicit test, but having the `map` @jonringer wrote directly in the maintainers file. Eval errors *are* noticed.

**Comment by jonringer** [comment]
how did you want to expose this? doing the evaluation on just `lib.maintainers` would mean evaluating all 1000+ entries any time you want to access a given maintainer. Something like `lib.maintainers._verifyNames`? Couldn't think of any good names

**Review by 0x4A6F — APPROVED** [review]

**Comment by FRidh** [comment]
Actually, `lib/tests/release.nix` is already executed by `ofborg` and that includes `lib/tests/maintainers.nix`. That will be cheaper than directly in `maintainer-list.nix`.

**Comment by zowoq** [comment]
Sorry but I'm not going to implement what has been requested.

Should I close this PR?

**Comment by jonringer** [comment]
I think the PR is fine as is.

The check can happen in a different PR

**Review by jonringer — APPROVED** [review]

**Comment by 1000101** [comment]
> Sorry but I'm not going to implement what has been requested.
> 
> Should I close this PR?

Don't you dare! :smile:

**Pull request merged**
