### PR TITLE
pythonPackages.graphviz: 0.14.1 -> 0.16

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Could you change the PR title and commit message to ``pythonPackages.graphviz: 0.14.1 -> 0.16``? It is more common and easily searchable.

**Comment by dotlambda** [comment]
@SuperSandro2000 I think this is ready to be merged.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109507` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages marked as broken and skipped:
</summary>
<ul>
<li>pepper</li>
<li>python37Packages.optuna</li>
<li>python38Packages.optuna</li>
<li>python39Packages.pyalgotrade</li>
<li>python39Packages.pyro-ppl</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.dask-xgboost: log was empty</li>
<li>python37Packages.xgboost: log was empty</li>
<li>python38Packages.dask-xgboost: log was empty</li>
<li>python38Packages.xgboost: log was empty</li>
  </ul>
</details>
<details>
<summary>
52 packages built:
</summary>
<ul>
<li>beets</li>
<li>flexget</li>
<li>mnemosyne</li>
<li>python37Packages.WSME</li>
<li>python37Packages.cherrypy</li>
<li>python37Packages.graphviz</li>
<li>python37Packages.heudiconv</li>
<li>python37Packages.ibis-framework</li>
<li>python37Packages.mxnet</li>
<li>python37Packages.nipype</li>
<li>python37Packages.objgraph</li>
<li>python37Packages.prov</li>
<li>python37Packages.pyalgotrade</li>
<li>python37Packages.pydotplus</li>
<li>python37Packages.pyro-ppl</li>
<li>python37Packages.pysonos</li>
<li>python37Packages.skidl</li>
<li>python37Packages.soco</li>
<li>python37Packages.streamz</li>
<li>python37Packages.ws4py</li>
<li>python37Packages.xdot</li>
<li>python37Packages.zerobin</li>
<li>python38Packages.WSME</li>
<li>python38Packages.cherrypy</li>
<li>python38Packages.graphviz</li>
<li>python38Packages.mxnet</li>
<li>python38Packages.nipype</li>
<li>python38Packages.objgraph</li>
<li>python38Packages.prov</li>
<li>python38Packages.pyalgotrade</li>
<li>python38Packages.pydotplus</li>
<li>python38Packages.pyro-ppl</li>
<li>python38Packages.pysonos</li>
<li>python38Packages.skidl</li>
<li>python38Packages.soco</li>
<li>python38Packages.streamz</li>
<li>python38Packages.ws4py</li>
<li>xdot (python38Packages.xdot)</li>
<li>python38Packages.zerobin</li>
<li>python39Packages.cherrypy</li>
<li>python39Packages.graphviz</li>
<li>python39Packages.mxnet</li>
<li>python39Packages.objgraph</li>
<li>python39Packages.prov</li>
<li>python39Packages.pydotplus</li>
<li>python39Packages.skidl</li>
<li>python39Packages.soco</li>
<li>python39Packages.ws4py</li>
<li>python39Packages.xdot</li>
<li>python39Packages.zerobin</li>
<li>sabnzbd</li>
<li>tribler</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.mxnet:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'numpy<=1.15.2,' doesn't match anything in file 'python/setup.py'
substituteStream(): WARNING: pattern 'requests<2.19.0,' doesn't match anything in file 'python/setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python37Packages.prov:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'six==1.10.0' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python37Packages.pydotplus:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.mxnet:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'numpy<=1.15.2,' doesn't match anything in file 'python/setup.py'
substituteStream(): WARNING: pattern 'requests<2.19.0,' doesn't match anything in file 'python/setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python38Packages.prov:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'six==1.10.0' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python38Packages.pydotplus:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.mxnet:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'numpy<=1.15.2,' doesn't match anything in file 'python/setup.py'
substituteStream(): WARNING: pattern 'requests<2.19.0,' doesn't match anything in file 'python/setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python39Packages.prov:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'six==1.10.0' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python39Packages.pydotplus:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by dotlambda** [comment]
cc @abbradar regarding the useless `substituteInPlace` in `pythonPackages.mxnet`. You could file an issue upstream to loosen the bound on the remaining `graphviz`.

**Comment by dotlambda** [comment]
I think it's a good idea to drop `pythonPackages.pydotplus` since `pythonPackages.pydot` is a maintained drop-in replacement.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109507` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>pepper</li>
<li>python39Packages.pyalgotrade</li>
<li>python39Packages.pyro-ppl</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>mnemosyne: log was empty</li>
  </ul>
</details>
<details>

  <summary>48 packages failed to build and are new build failures:</summary>
  <ul>
<li>flexget: log was empty</li>
<li>python37Packages.WSME: log was empty</li>
<li>python37Packages.cherrypy: log was empty</li>
<li>python37Packages.dask-xgboost: log was empty</li>
<li>python37Packages.graphviz: log <a href="https://termbin.com/omdk">https://termbin.com/omdk</a></li>
<li>python37Packages.heudiconv: log was empty</li>
<li>python37Packages.ibis-framework: log was empty</li>
<li>python37Packages.nipype: log was empty</li>
<li>python37Packages.objgraph: log was empty</li>
<li>python37Packages.prov: log <a href="https://termbin.com/9jbl">https://termbin.com/9jbl</a></li>
<li>python37Packages.pyalgotrade: log was empty</li>
<li>python37Packages.pyro-ppl: log was empty</li>
<li>python37Packages.pysonos: log was empty</li>
<li>python37Packages.skidl: log was empty</li>
<li>python37Packages.soco: log was empty</li>
<li>python37Packages.streamz: log was empty</li>
<li>python37Packages.ws4py: log was empty</li>
<li>python37Packages.xdot: log was empty</li>
<li>python37Packages.xgboost: log was empty</li>
<li>python37Packages.zerobin: log was empty</li>
<li>python38Packages.WSME: log was empty</li>
<li>python38Packages.cherrypy: log was empty</li>
<li>python38Packages.dask-xgboost: log was empty</li>
<li>python38Packages.graphviz: log <a href="https://termbin.com/13c1j">https://termbin.com/13c1j</a></li>
<li>python38Packages.nipype: log was empty</li>
<li>python38Packages.objgraph: log was empty</li>
<li>python38Packages.prov: log <a href="https://termbin.com/mvjt">https://termbin.com/mvjt</a></li>
<li>python38Packages.pyalgotrade: log was empty</li>
<li>python38Packages.pyro-ppl: log was empty</li>
<li>python38Packages.pysonos: log was empty</li>
<li>python38Packages.skidl: log was empty</li>
<li>python38Packages.soco: log was empty</li>
<li>python38Packages.streamz: log was empty</li>
<li>python38Packages.ws4py: log was empty</li>
<li>xdot: log was empty</li>
<li>(python38Packages.xdot): log was empty</li>
<li>python38Packages.xgboost: log was empty</li>
<li>python38Packages.zerobin: log was empty</li>
<li>python39Packages.cherrypy: log was empty</li>
<li>python39Packages.graphviz: log <a href="https://termbin.com/i0si">https://termbin.com/i0si</a></li>
<li>python39Packages.nipype: log was empty</li>
<li>python39Packages.objgraph: log was empty</li>
<li>python39Packages.prov: log <a href="https://termbin.com/esuf">https://termbin.com/esuf</a></li>
<li>python39Packages.skidl: log was empty</li>
<li>python39Packages.soco: log was empty</li>
<li>python39Packages.ws4py: log was empty</li>
<li>python39Packages.xdot: log was empty</li>
<li>python39Packages.zerobin: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109507` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages marked as broken and skipped:
</summary>
<ul>
<li>pepper</li>
<li>python37Packages.optuna</li>
<li>python38Packages.optuna</li>
<li>python39Packages.pyalgotrade</li>
<li>python39Packages.pyro-ppl</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.dask-xgboost: log was empty</li>
<li>python37Packages.xgboost: log was empty</li>
<li>python38Packages.dask-xgboost: log was empty</li>
<li>python38Packages.xgboost: log was empty</li>
  </ul>
</details>
<details>
<summary>
49 packages built:
</summary>
<ul>
<li>beets</li>
<li>flexget</li>
<li>mnemosyne</li>
<li>python37Packages.WSME</li>
<li>python37Packages.cherrypy</li>
<li>python37Packages.graphviz</li>
<li>python37Packages.heudiconv</li>
<li>python37Packages.ibis-framework</li>
<li>python37Packages.mxnet</li>
<li>python37Packages.nipype</li>
<li>python37Packages.objgraph</li>
<li>python37Packages.prov</li>
<li>python37Packages.pyalgotrade</li>
<li>python37Packages.pyro-ppl</li>
<li>python37Packages.pysonos</li>
<li>python37Packages.skidl</li>
<li>python37Packages.soco</li>
<li>python37Packages.streamz</li>
<li>python37Packages.ws4py</li>
<li>python37Packages.xdot</li>
<li>python37Packages.zerobin</li>
<li>python38Packages.WSME</li>
<li>python38Packages.cherrypy</li>
<li>python38Packages.graphviz</li>
<li>python38Packages.mxnet</li>
<li>python38Packages.nipype</li>
<li>python38Packages.objgraph</li>
<li>python38Packages.prov</li>
<li>python38Packages.pyalgotrade</li>
<li>python38Packages.pyro-ppl</li>
<li>python38Packages.pysonos</li>
<li>python38Packages.skidl</li>
<li>python38Packages.soco</li>
<li>python38Packages.streamz</li>
<li>python38Packages.ws4py</li>
<li>xdot (python38Packages.xdot)</li>
<li>python38Packages.zerobin</li>
<li>python39Packages.cherrypy</li>
<li>python39Packages.graphviz</li>
<li>python39Packages.mxnet</li>
<li>python39Packages.objgraph</li>
<li>python39Packages.prov</li>
<li>python39Packages.skidl</li>
<li>python39Packages.soco</li>
<li>python39Packages.ws4py</li>
<li>python39Packages.xdot</li>
<li>python39Packages.zerobin</li>
<li>sabnzbd</li>
<li>tribler</li>
</ul>
</details>

**Review by ashgillman — APPROVED** [review]
I agree. Pydotplus is no longer used by prov or anywhere else, and pydot, I think, is being maintained again so no need for the former.

**Pull request merged**
