### PR TITLE
xapianBindings: remove

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

- no package uses it
- uses composable derivation, and some changes are needed for python 3
support

### CODE REVIEW

**Comment by grahamc** [comment]
Not to mention xapianBindings are a PITA and break so easy!

**Comment by grahamc** [comment]
LGTM

**Comment by oxij** [comment]
Are there alternatives? What am I supposed to use instead in my own
python scripts?

**Comment by FRidh** [comment]
@oxij if you need them you can become maintainer of them. In any case, it is going to need a rewrite.

**Pull request merged**
