### PR TITLE
gdal: 2.2.1 -> 2.2.3

### PR DESCRIPTION
**Pull request by lsix**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by globin** [comment]
Could you change the base to staging and rebase?

**Comment by lsix** [comment]
@globin done.

**Comment by globin** [comment]
@GrahamcOfBorg build gdal

**Comment by globin** [comment]
@GrahamcOfBorg eval

**Comment by orivej** [comment]
I'm going to merge this to `master` (after testing), since it rebuilds just 27 packages on Linux. /cc @globin

**Comment by orivej** [comment]
Sorry, this was merged in #33390.

**Pull request closed without merging**
