### PR TITLE
btcpayserver: 1.7.2 -> 1.7.3

### PR DESCRIPTION
**Pull request by prusnak**
###### Description of changes

- version update: https://github.com/btcpayserver/btcpayserver/releases/tag/v1.7.3

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@erikarvstedt Ideas why `deps.nix` now have different whitespace formatting? (I just run the update script like we always do ...)

**Comment by prusnak** [comment]
Ah, I now see the issue - the `deps.nix` files were manually re-formatted via https://github.com/NixOS/nixpkgs/pull/194276

I will update our update script to use the new format ...

**Comment by prusnak** [comment]
Hm, however, when I try to build I see the following failures:

```
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.any.System.Collections. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.unix.Microsoft.Win32.Primitives. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.unix.System.Console. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.unix.System.Diagnostics.Debug. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.any.System.Diagnostics.Tools. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.any.System.Diagnostics.Tracing. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.any.System.Globalization. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.any.System.Globalization.Calendars. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.any.System.IO. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer.Rating/BTCPayServer.Rating.csproj : error NU1101: Unable to find package runtime.unix.System.IO.FileSystem. No packages exist with this id in source(s): nugetSource [/private/tmp/nix-build-btcpayserver-1.7.3.drv-0/source/BTCPayServer/BTCPayServer.csproj]
...
```

Can you please advise @IvarWithoutBones @corngood ?

**Comment by erikarvstedt** [comment]
The build fails. Could this be related to changes in `build-dotnet-module`?
Hint: [This](https://github.com/NixOS/nixpkgs/pull/206951) might be helpful for your macOS build workflow.

Maybe we should switch the update scripts to use [`build-dotnet-module.fetch-deps`](https://github.com/NixOS/nixpkgs/blob/b651d2fa21ad751cc8441b9a7d57e61bd1f69e44/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L164).

**Comment by prusnak** [comment]
> Maybe we should switch the update scripts to use [`build-dotnet-module.fetch-deps`](https://github.com/NixOS/nixpkgs/blob/b651d2fa21ad751cc8441b9a7d57e61bd1f69e44/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L164).

Yeah, that would be ideal, but I am afraid I won't have time to study how to do it. :-/

**Comment by corngood** [comment]
I didn't realise these things had custom update scripts instead of `passthru.fetch-deps`.  I'll take a look.

**Comment by corngood** [comment]
@prusnak #207450 should do it.  I'm able to update and build 1.7.3, but I've only tried on x64 linux.  Perhaps you could give it a try on aarch64-darwin?

**Comment by prusnak** [comment]
> @prusnak #207450 should do it.

Cherry-picked the change from this PR into this PR. 

@nixbitcoin Can you still comment on whether it's necessary to add `"/p:Configuration="Altcoins-Release"` when generating the dependencies? It does seem to me that this is not required and `btcpayserver.override { altcoinSupport = true; }'` still builds successfully.

**Comment by corngood** [comment]
Perhaps altcoin support should be enabled by default?  Does it bring in more dependencies?

**Comment by prusnak** [comment]
> Perhaps altcoin support should be enabled by default?  Does it bring in more dependencies?

I am not sure this is a good idea since it does not receive enough testing upstream (as in most of the upstream maintainers care only about bitcoin and don't test other coins regularly).

**Review by corngood — APPROVED** [review]

**Comment by erikarvstedt** [comment]
Currently blocked by https://github.com/NixOS/nixpkgs/pull/209357.

**Comment by corngood** [comment]
@erikarvstedt are you not able to run the update script with `TMPDIR=/tmp`?  that's worked for me in the past

**Comment by prusnak** [comment]
> Currently blocked by #209357.

PR merged.

@erikarvstedt could you please confirm that the altcoinSupport functionality was not broken by this refactor?

**Comment by erikarvstedt** [comment]
Needs rebase.
On my rebase, all tests succeed, including `btcpayserver-altcoins`.

**Comment by erikarvstedt** [comment]
- [x] `refetch=1 pkgs/applications/blockchains/btcpayserver/update.sh` produces the same content as this PR.
- [x] Pkgs `btcpayserver`, `btcpayserver-altcoins` build on `x86_64-linux`
- [x] The [nix-bitcoin VM test](https://gist.github.com/cd529147465fe1da92d8c4b1971f8c9e) succeeds on `x86_64-linux`.

**Review by erikarvstedt — APPROVED** [review]

**Pull request merged**
