### PR TITLE
xfce4-13: 4.14pre1 -> 4.14pre2

### PR DESCRIPTION
**Pull request by volth**
version bump

@yegortimoshenko @romildo

### CODE REVIEW

**Comment by romildo** [comment]
Tested in a VM using the desktop service module from https://github.com/NixOS/nixpkgs/pull/37594.

I have found a problem: launching _Desktop_ from the _Settings Manager_ is not working. The frame of a window is displayed momentarily and it quickly disappears, without showing any dialog. Running `xfdesktop-settings` from a terminal works, though.

**Comment by volth** [comment]
> I have found a problem: launching Desktop from the Settings Manager is not working. The frame of a window is displayed momentarily and it quickly disappears, without showing any dialog. Running ```xfdesktop-settings``` from a terminal works, though.

From whisker menu it quickly disappears as well, both ```Desktop``` shortcut and  ```Run xfdesktop-settings```. It seems that it needs tty for some weird reason

**Comment by volth** [comment]
fixed

**Comment by volth** [comment]
ping

**Comment by romildo** [comment]
Looks good to me.

**Comment by FRidh** [comment]
why does the -13 attribute point to a .14?

**Comment by romildo** [comment]
> why does the -13 attribute point to a .14?

13 is the development (unstable) version leading to the 14 stable version. It should be updated.

**Comment by romildo** [comment]
> 13 is the development (unstable) version leading to the 14 stable version. It should be updated.

See https://github.com/NixOS/nixpkgs/pull/64702

**Comment by ivan** [comment]
pre2 regressed hidpi window titles, they are misaligned vertically, stuck to the top

**Comment by volth** [comment]
> pre2 regressed window titles in window manager style Default-xhdpi, they are misaligned vertically, stuck to the top

Hm, works for me: https://i.imgur.com/wVYKsWz.png

**Pull request merged**
