### PR TITLE
 openresty: make compatible with nixos nginx module

### PR DESCRIPTION
**Pull request by JJJollyjim**
##### Motivation for this change

Openresty currently fails to start when provided to services.nginx, as it can't load fastcgi.conf.

This PR resolves that, and adds a test to ensure that all nginx variants in nixpkgs (or at least the ones I'm aware of...) can start and serve a simple request.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JJJollyjim** [comment]
@ofborg test nginx-variants

**Comment by Izorkin** [comment]
Please add to this test check with tengine.

**Comment by JJJollyjim** [comment]
@ofborg test nginx-variants

@Izorkin done :+1:

**Pull request merged**
