### PR TITLE
@electron-forge/cli: init at 6.0.0-beta.54

### PR DESCRIPTION
**Pull request by CMCDragonkai**
###### Motivation for this change

Adding @electron-forge/cli which is used to build electron applications into various distribution formats.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Depends on this PR: https://github.com/NixOS/nixpkgs/pull/115174

**Comment by CMCDragonkai** [comment]
```
»» ~/Projects/nixpkgs
 ♖ ./result/bin/electron-forge -h     (electron-forge) pts/9 18:27:51
✔ Checking your system
Usage: electron-forge [options] [command]

Options:
  -V, --version  output the version number
  --verbose      Enables verbose mode
  -h, --help     output usage information

Commands:
  init           Initialize a new Electron application
  import         Attempts to navigate you through the process of
                 importing an existing project to "electron-forge"
  lint           Lints the current Electron application
  package        Package the current Electron application
  make           Generate distributables for the current Electron
                 application
  start          Start the current Electron application
  publish        Publish the current Electron application to GitHub
  install        Install an Electron application from GitHub
  help [cmd]     display help for [cmd]
```

**Comment by CMCDragonkai** [comment]
Strange problem but the nixpkgs packaged ones seems to be creating files with read permission only. This is different from the npm installed one:

```
> nix-env -f ./default.nix -iA 'nodePackages.@electron-forge/cli'
> mkdir test/a
> cd test/a
> electron-forge init --template=typescript-webpack
✔ Checking your system
✔ Initializing Project Directory
✔ Initializing Git Repository
✔ Locating custom template: "typescript-webpack"
✔ Copying Starter Files
✔ Initializing NPM Module
✔ Setting up Forge configuration
✖ Setting up TypeScript configuration

An unhandled error has occurred inside Forge:
EACCES: permission denied, open '/test/a/src/index.html'
Error: EACCES: permission denied, open '/test/b/src/index.html'
```

The reason is that the files here are generated with only the read permission:

```
> ls -l /test/a/src
total 14K
-r--r--r-- 1 cmcdragonkai operators  162 Mar  6 18:30 index.css
-r--r--r-- 1 cmcdragonkai operators  253 Mar  6 18:30 index.html
-r--r--r-- 1 cmcdragonkai operators 1.5K Mar  6 18:30 index.js
```

When using the `electron-forge` from NPM, this doesn't occur.

**Comment by CMCDragonkai** [comment]
The other usages of `electron-forge` does work, and I'm able to build and package electron apps with it.

The above error is strange, why would electron-forge end up creating files that are read-only? Is this due to being put inside the `/nix/store`?

**Review by doronbehar — APPROVED** [review]

**Comment by doronbehar** [comment]
Tested to be functional. Didn't test any other package changed by this commit. Currently there's also https://github.com/NixOS/nixpkgs/pull/114574 which changes files in `node-packages.nix` and it has merge conflicts already. @CMCDragonkai would you like to get past the read only permissions issue before merging?

**Comment by CMCDragonkai** [comment]
No idea what is causing that read issue. But the other stuff is all working. Can build windows and Linux packages.

**Comment by SuperSandro2000** [comment]
> The above error is strange, why would electron-forge end up creating files that are read-only? Is this due to being put inside the `/nix/store`?

Does it copy files from the nix store?

**Comment by CMCDragonkai** [comment]
@SuperSandro2000 oh maybe that is the reason... in that case, how can we fix this? Will it need a source code patch? Maybe an upstream fix that ensures that the generated files are read write.

**Comment by CMCDragonkai** [comment]
Posted an upstream issue here: https://github.com/electron-userland/electron-forge/issues/2190

I think an upstream fix will eventually fix the whole problem and then there will be no problems using `electron-forge` in Nixpkgs.

Also in the future, I think `electron-packager` and `electron-rebuild` should also be packaged in Nixpkgs as well but so far it is not needed.

Furthermore the `@electron-forge/maker-*` dependencies don't need to be packaged in Nix yet, `electron-forge` here will make use of it by checking `package.json` in the `devDependencies`... but in the future these might be packaged in Nix as well, but we will need a more sophisticated electron ecosystem in nixpkgs to do this...

**Comment by SuperSandro2000** [comment]
> in that case, how can we fix this? Will it need a source code patch? Maybe an upstream fix that ensures that the generated files are read write.

A patch would probably be the easiest.

> we will need a more sophisticated electron ecosystem in nixpkgs to do this...

yeah, someone needs to do that.

**Pull request merged**
