### PR TITLE
vmware-horizon-client: enable audio redirection

### PR DESCRIPTION
**Pull request by buckley310**
###### Motivation for this change
These library additions allow audio output and microphone input to work with remote desktops.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by buckley310** [comment]
:-1: My apologies for creating extra work by just missing the branch-off

**Comment by buckley310** [comment]
Actually, since the branch-off is already missed, and nobody seems to be looking at this yet, I'm going to close. I have some other tweaks i'd like to add, so I'll just combine them and re-PR after.

**Comment by aaronchall** [comment]
I've been looking at how to enable my microphone to connect to my remote desktop myself on weekends, wondering if there's some kind of config change I needed to do on my own machine or if this was something that required revision in nixpkgs.

I got to page 9 of https://www.vmware.com/pdf/horizon-view/horizon-view-client-linux-document.pdf where I see that certain .so files are required as well as Video4Linux2 and libv4l - and I'm not entirely sure how to detect if those libs are there or not. I decided to open a ticket but it looks like this is attempting to get there, so I'm looking for the next issue on this. Thank you buckley310 for your contributions here.

**Comment by buckley310** [comment]
This pr should make audio/video conferencing work out of the box. https://github.com/NixOS/nixpkgs/pull/149713

**Pull request closed without merging**
