### PR TITLE
knot-resolver: fix LUA_{PATH,CPATH}

### PR DESCRIPTION
**Pull request by eadwu**
`LUA_PATH` and `LUA_CPATH` were both blank beforehand.

###### Motivation for this change
Enabling `DNSSEC`, `trust_anchors.add_file('/var/cache/kresd/root.keys')`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Hmm, I suppose some lua infra changes have broken this.  I'll have a closer look later.

BTW, you don't need to add custom root trust anchor file or explicitly enable DNSSEC validation &ndash; you get all that by default without these extra lua packages.

**Comment by vcunat** [comment]
This was broken by #63108.  Unfortunately this PR isn't a full fix, because it doesn't address dependency propagation, in particular some lua dependencies of `http` are missing.

**Review by teto — CHANGES_REQUESTED** [review]
let's fix the original issue. A quickfix might be to use a lua.withPackages as a buildInput ?

**Comment by vcunat** [comment]
Thanks a lot for reporting this!   I pushed a quick-fix in the meantime, and I agree we need to resolve the underlying issue anyway.

**Pull request closed without merging**
