### PR TITLE
obs-studio: use wrapGAppsHook to add required org.gtk.Settings.ColorChooser schema

### LINKED ISSUE #145661: obs-studio crashes trying to start the color selector
`obs-studio` from the current `nixos-unstable` crashes when you use a function that starts up a gtk color chooser. The error message I see in syslog is:

~~~
.obs-wrapped[24019]: Settings schema 'org.gtk.Settings.ColorChooser' is not installed
kernel: traps: .obs-wrapped[24019] trap int3 ip:7f077b7d09f7 sp:7ffd8c425e80 error:0 in libglib-2.0.so.0.7000.0[7f077b793000+8b000]
systemd[1]: Started Process Core Dump (PID 24041/UID 0).
systemd-coredump[24042]: [🡕] Process 24019 (.obs-wrapped) of user 1000 dumped core.
~~~

I suppose this means that OBS needs `wrapGAppsHook` in `nativeBuildInputs`?

### PR DESCRIPTION
**Pull request by peti**
Fixes https://github.com/NixOS/nixpkgs/issues/145661.

### CODE REVIEW

**Comment by Artturin** [comment]
Line 124

**Comment by Artturin** [comment]
Oops looks like I left that in there https://github.com/NixOS/nixpkgs/commit/4807351d123543270d90da5a1100afd294ee9020#diff-63965a04dab0dc3cf800c36e5989e328cac6cf436e76b0484fdf7df881111b63

But how is that even working as there's no qtwraphook in args 🤔

**Comment by SuperSandro2000** [comment]
Are the binaries now double wrapped?

**Comment by peti** [comment]
> Are the binaries now double wrapped?

Yes, they are. They work fine, though.

**Comment by Artturin** [comment]
this fixes double-wrapping 
```diff
diff --git a/pkgs/applications/video/obs-studio/default.nix b/pkgs/applications/video/obs-studio/default.nix
index 7454cc1eb29..31f478c47c0 100644
--- a/pkgs/applications/video/obs-studio/default.nix
+++ b/pkgs/applications/video/obs-studio/default.nix
@@ -21,7 +21,6 @@
 , curl
 , wayland
 , xorg
-, makeWrapper
 , pkg-config
 , libvlc
 , mbedtls
@@ -67,7 +66,6 @@ mkDerivation rec {
     addOpenGLRunpath
     cmake
     pkg-config
-    makeWrapper
     wrapGAppsHook
   ]
   ++ optional scriptingSupport swig;
@@ -121,9 +119,13 @@ mkDerivation rec {
     "-DCEF_ROOT_DIR=../../cef"
   ];
 
-  qtWrapperArgs = [
-    "--prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ xorg.libX11 libvlc ]}"
-  ];
+  dontWrapGApps = true;
+  preFixup = ''
+    qtWrapperArgs+=(
+      --prefix LD_LIBRARY_PATH : "${lib.makeLibraryPath [ xorg.libX11 libvlc ]}"
+      ''${gappsWrapperArgs[@]}
+    )
+  '';
 
   postFixup = lib.optionalString stdenv.isLinux ''
     addOpenGLRunpath $out/lib/lib*.so
```

**Comment by peti** [comment]
> this fixes double-wrapping [...]

Added to this PR in 90af5cacfbcf6b3c57a33feb1e19be797b27e7e8. Thank you very much!

**Comment by peti** [comment]
@GrahamcOfBorg build obs-studio

**Pull request merged**
