### PR TITLE
Mattermost-desktop: 4.2.3 -> 4.3.1

### PR DESCRIPTION
**Pull request by evils**
###### Motivation for this change
mattermost-desktop crashed on opening the file chooser

###### Things done
add wrapGAppsHook and pass dependencies
bump version (unrelated)

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jokogr

### CODE REVIEW

**Review by lsix — APPROVED** [review]
Built and tested locally. Good for me.

**Review by jokogr — APPROVED** [review]
Built and tested, too, thanks for the fix and the update! :+1:

**Comment by knedlsepp** [comment]
@jokogr: Could we get this backported to 19.09?

**Comment by knedlsepp** [comment]
Does this work for anybody? I'm still having issues with that on 20.03

**Pull request merged**
