### PR TITLE
stage-1: fix hibernation

### LINKED ISSUE #6617: Resume from Hibernation Fails
I haven't been able to resume from hibernation since 3bcd3ed01 and 448c6fc317 (I tried setting the resumeDevice to /dev/sdb3 and leaving it empty). Reverting these commits and using the device major and minor numbers works for me. It would be great to restore the option to specify the resumeDevice by major and minor numbers and also to support specifying the device by path. 

@abbradar have you got some thought on this?

Related to #5219 #4995

### PR DESCRIPTION
**Pull request by abbradar**
Fixes https://github.com/NixOS/nixpkgs/issues/6617 . @cillianderoiste , please, test if this fixes the problem for you.

### CODE REVIEW

**Comment by vcunat** [comment]
So this tries to fix the case of setting ``boot.resumeDevice = "/dev/sda3";``, right?

**Comment by abbradar** [comment]
Not only, when detecting too -- in my test (#6679) hibernation haven't worked until I've explicitly used minor/major numbers. That's strange -- it has worked for me some time ago, but anyway this seems more reliable too.

**Comment by abbradar** [comment]
Basically what this does is gets minor/major device numbers from udev and uses them, both when autodetecting resume partition and when having it explicitly set.

**Comment by vcunat** [comment]
Heh, the [kernel docs](https://www.kernel.org/doc/Documentation/power/swsusp.txt) seem sparse on this, saying just "echo into /sys/power/resume" but not saying what. I found someone claiming that this usage is discouraged and therefore deliberately undocumented https://lkml.org/lkml/2007/5/27/49.

I meant to say this PR still doesn't allow one to set ``boot.resumeDevice = "8:3";``, but that's probably fine. I wonder if the real cause of that specific case #6617 could be somewhere else.

**Comment by edolstra** [comment]
Yeah, we shouldn't support major/minor notation since it's a) user-unfriendly and b) not guaranteed to be the same across reboots.

**Comment by abbradar** [comment]
@vcunat They indeed were very sparse, I have found nearly nothing ot possible usages and so jumped into the kernel code to find it out ^^.

Yeah, it doesn't allow one to do this (though now it's simpler to fix, but as @edolstra I'm somewhat opposed to supporting them). At least during my testing in VM this fixed things -- let's wait for user to confirm it. I can't say _why_ this helped, though -- from what I've read looking at the code, minor-major numbers are what's needed in the end -- but I haven't understood good enough how are device paths resolved to them internally.

**Comment by cillianderoiste** [comment]
Thanks @abbradar! I've tested by having no resumeDevice set, it correctly used my swap partition and resumed successfully. I also tested by setting resumeDevice to /dev/sdb3 and /dev/disk/by-uuid/blah-blah ... and in all cases it works correctly for me. :beers:

**Comment by vcunat** [comment]
Merged to master. I see only tiny differences in this file against 14.12, so I expect the release is affected by the same problems and this PR should be picked (maybe the whole file), right?

**Comment by abbradar** [comment]
Yes, thanks!

**Pull request closed without merging**
