### PR TITLE
bcunit: 3.0 -> 3.0.2

### PR DESCRIPTION
**Pull request by ryantm**
- [x] built on NixOS

### CODE REVIEW

**Comment by adisbladis** [comment]
@GrahamcOfBorg build bcunit

**Comment by peti** [comment]
This commit broke the build of `bctoolbox`, which in turn is a dependency of `linphone`, a rather nice VoIP software I frequently use.

@GrahamcOfBorg build linphone

**Comment by ryantm** [comment]
@peti Okay, I started updating Linphone and its many dependency libraries.

**Comment by adisbladis** [comment]
Fixed the `linphone` build in https://github.com/NixOS/nixpkgs/pull/34800

**Pull request merged**
