### PR TITLE
[20.03] pythonPackages.{namedlist, ludios_wpull}: mark broken only on Python 3.8

### PR DESCRIPTION
**Pull request by ivan**
###### Motivation for this change

This undoes some of 5fe104de46afa84f317247f9e62794c15611a66c - these libraries work fine on Python 3.7 and are used by grab-site.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Can you use `disabled = isPy38`?

**Comment by ivan** [comment]
@worldofpeace fixed, thanks.

**Review by FRidh — CHANGES_REQUESTED** [review]
`disabled` needs to be passed to `buildPythonPackage`, but not as part of `meta`.

**Comment by ivan** [comment]
@FRidh sorry about that, fixed, and tested the evals on Linux

**Pull request merged**
