### PR TITLE
[20.09] Staging

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Gather and deliver staging changes.

###### Things done

  - [x] [base:staging](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Astaging-20.09)
  - [x] [base:release](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Arelease-20.09) (if mass-rebuild)
  - [x] [base: wrong branch](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Anixos-20.09)
  - [ ] let it build on hydra

https://hydra.nixos.org/jobset/nixpkgs/staging-20.09

### CODE REVIEW

**Comment by roberth** [comment]
@jluttine `python37Packages.salmon-mail` fails on `staging-20.09` https://hydra.nixos.org/build/138491114/nixlog/1

**Comment by jluttine** [comment]
@roberth Hmm.. This builds fine:

```
nix-build '<nixpkgs>' -I https://github.com/NixOS/nixpkgs/archive/staging-20.09.tar.gz -A python37Packages.salmon-mail
```

(Not quite sure if that was the correct way to build on that branch though. But I built it also by explicitly setting that branch as my nixpkgs and got the same result.)

Or, well, it doesn't build it from source, just fetches from the cache, but then it has built just fine on hydra.

**Comment by jluttine** [comment]
Also, I don't see the package failing in that hydra link.. It says OK and completes all the phases. So, I'm not quite sure what's the issue..

**Comment by roberth** [comment]
@jluttine It must have been restarted. Next time I'll copy the log. It was probably just a flaky test, but it would be nice to figure out so this doesn't happen again. Next time...

**Comment by jluttine** [comment]
@roberth Ah, ok! :+1:

**Pull request merged**
