### PR TITLE
GZDoom 4.3.3 -> 4.4.2

### PR DESCRIPTION
**Pull request by Derpford**
4.4.0 increased the ZScript version number, GZDoom 4.4.1 and 4.4.2 have some bugfixes. I was unable to test this at all because I can't figure out how to get home-manager to install GZDoom with a specified version attribute.

###### Motivation for this change
Keeping up with current release version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by iblech** [comment]
Hello Derpford and congratulations on your first pull request! You are welcome! :-)

I also don't know about home-manager, but you can test your update by:

    nix-shell -I nixpkgs=https://github.com/Derpford/nixpkgs/archive/patch-1.tar.gz -p gzdoom

I'll do this now and report back my findings. :-)

**Review by cole-h — CHANGES_REQUESTED** [review]
Hi, welcome! Thanks for contributing! There are a couple problems with your PR, however:

* Sorry, update what to 4.4.2? ;)

    Please change your commit message to follow our contributing guidelines (located [here](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)): `gzdoom: 4.3.3 -> 4.4.2`.

* Additionally, how did you get that sha256? I get a hash mismatch:

    ```
    hash mismatch in fixed-output derivation '/nix/store/b7pajg3z67jnsqj5656cclv154ninxjr-source':
      wanted: sha256:0x06069ywl3mndspyi4pq91myivpf3jkclwagbcvcd48zapfkvfh
      got:    sha256:1xkkmbsdv64wyb9r2fv5mwyqw0bjryk528jghdrh47pndmjs9a38
    cannot build derivation '/nix/store/sfr086iqh5kczy7lsxrnr7fb4nyk0yg8-gzdoom-4.4.2.drv': 1 dependencies couldn't be built
    cannot build derivation '/nix/store/a2szlx675q1669ppd9fgil20j0yxfli3-env.drv': 1 dependencies couldn't be built
    [0 built (1 failed), 7 copied (145.8 MiB), 115.0 MiB DL]
    error: build of '/nix/store/a2szlx675q1669ppd9fgil20j0yxfli3-env.drv' failed
    https://github.com/NixOS/nixpkgs/pull/90690
    1 package failed to build:
    gzdoom
    ```

---

And to answer your question on how to build this yourself:

1. `cd /path/to/your/nixpkgs/checkout`
2. Make your changes
3. `nix-build -A gzdoom` to verify that the gzdoom attr still builds after your change

This will create a `result` symlink to the built store path, where you can then run the binary from `result/bin/binary`.

**Comment by Derpford** [comment]
Re: that hash mismatch, I grabbed the hash by running nix-prefetch-url on this URL:
`https://github.com/coelckers/gzdoom/archive/g4.4.2.tar.gz`

**Comment by cole-h** [comment]
Ah, yeah. That's because `nix-prefetch-url` only hashes the resulting tarball, whereas `fetchFromGitHub` will extract it and then hash it. To get the proper hash, you should use `nix-prefetch-url --unpack https://github.com/coelckers/gzdoom/archive/g4.4.2.tar.gz` (`--unpack` is key).

**Comment by iblech** [comment]
I confirm that I get the same hash mismatch which cole-h reported. Fixing that, I run into an error concerning `libraries/zmusic/mididevices/music_fluidsynth_mididevice.cpp`. Apparently since the previously packaged version, zmusic was made into its own repository on GitHub, with gzdoom depending on it. Hence we'll require a little more changes to the Nix package.

As I understand it, `git-prefetch-url` may only be used if the Nix package actually references the tarball by URL. If instead `fetchFromGitHub` is used, as it is here, you need to use `git-prefetch-git https://github.com/coelckers/gzdoom g4.4.2`. I'm sorry that you ran into this problem. I'm also just a random passer-by, but I guess that a patch to fix the documentation to be more clear on this point will be gladly appreciated, if you'd like to contribute in this fashion!

**Comment by Derpford** [comment]
I'm in over my head on this, I'm afraid. Let me link this to some friends of mine, who've been teaching me how to work with Nix.

**Comment by Derpford** [comment]
Finally got back to this. Apparently `zmusic` isn't actually a submodule, which is annoying. I'm told I can pass it in as a `buildInput` instead, so I'll try that next...

**Comment by Derpford** [comment]
Well, I've tried handling zmusic as a separate derivation, I've tried merging it into the source tree, but each time I get the same "no such file or directory" error.

**Comment by Derpford** [comment]
Open Skies worked out a possible solution, testing it now...

**Comment by Derpford** [comment]
Successfully built this version on nixos! It's working perfectly, from what I've seen.

**Comment by Lassulus** [comment]
nice! thanks!

**Pull request merged**
