### PR TITLE
nccl: 2.16.5-1 -> 2.18.3-1

### PR DESCRIPTION
**Pull request by ConnorBaker**
## Description of changes

Version bump.

@NixOS/cuda-maintainers

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ConnorBaker** [comment]
I was able to successfully `nccl-test-suite` with https://github.com/ConnorBaker/nix-cuda-test using this PR.

Currently trying to run `nix-cuda-test` to train the small model I have in that repo.

**Review by samuela — APPROVED** [review]
diff LGTM

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 250888 --extra-nixpkgs-config '{ allowUnfree = true; cudaSupport = true; cudaCapabilities = [ "8.9" ]; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.tensorflowWithCuda</li>
    <li>python310Packages.tensorflowWithCuda.dist</li>
    <li>python311Packages.tensorflowWithCuda</li>
    <li>python311Packages.tensorflowWithCuda.dist</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>cudaPackages.nccl</li>
    <li>cudaPackages.nccl-tests</li>
    <li>cudaPackages.nccl.dev</li>
    <li>python310Packages.cupy</li>
    <li>python310Packages.cupy.dist</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python310Packages.jaxlibWithCuda.dist</li>
    <li>python310Packages.torchWithCuda</li>
    <li>python310Packages.torchWithCuda.dev</li>
    <li>python310Packages.torchWithCuda.dist</li>
    <li>python310Packages.torchWithCuda.lib</li>
    <li>python311Packages.cupy</li>
    <li>python311Packages.cupy.dist</li>
    <li>python311Packages.jaxlibWithCuda</li>
    <li>python311Packages.jaxlibWithCuda.dist</li>
    <li>python311Packages.torchWithCuda</li>
    <li>python311Packages.torchWithCuda.dev</li>
    <li>python311Packages.torchWithCuda.dist</li>
    <li>python311Packages.torchWithCuda.lib</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
@mdaiter @orivej-nixos @SomeoneSerge would one of you have a chance to provide a second review?

**Comment by ConnorBaker** [comment]
@ConnorBaker: TODO: bump to newest release https://github.com/NVIDIA/nccl/releases/tag/v2.18.5-1

**Review by SomeoneSerge — APPROVED** [review]
Looks safe 🤷🏻

**Comment by ConnorBaker** [comment]
I’m going to merge this and then make a separate PR for the other version bump. Hopefully also make an update script so a bot will pick it up.

**Pull request merged**
