### PR TITLE
ungoogled-chromium: init at 58.0.3029.110-1

### PR DESCRIPTION
**Pull request by ylwghst**
###### Motivation for this change

This Chromium contains very interesting patches improving privacy, removing Google integrations and services brought by https://github.com/Eloston/ungoogled-chromium

> ungoogled-chromium is a set of configuration flags, patches, and custom scripts. These components altogether strive to accomplish the following:
> 
>- Disable or remove offending services and features that communicate with Google or weaken privacy
>- Strip binaries from the source tree, and use those provided by the system or build them from source
>- Add, modify, or disable features that inhibit control and transparency (these changes are minor and
do not have significant impacts on the general user experience)

I slightly modified nix declarations from generic chromium package available in master to be able to get and build the older release of chromium source code used by ungoogled-chromium project together with ungoogled-chromium patches.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
Are patches here differ from those in https://github.com/Eloston/ungoogled-chromium/tree/master/resources/patches/ungoogled-chromium ?
Should they land in nixpkgs or be fetched from that repo?

**Comment by FRidh** [comment]
Patches should be fetched when possible.

**Comment by ylwghst** [comment]
@volth patches are exactly same
@FRidh  ok

**Comment by volth** [comment]
stalled? :(

**Comment by bendlas** [comment]
Please try to minimize copy-pasting, by either
a) modifying the regular chromium package, to accept an `enableUngoogled` flag, or
b) creating a separate package, by using `overrideDerivation` on regular chromium

if you copy-paste the whole chromium derivation as a starting point, please do so a separate commit, so that changes can be picked out later.

**Review by matthewbauer — CHANGES_REQUESTED** [review]
See @bendlas comments

**Comment by Chiiruno** [comment]
Still working on this?

**Comment by c0bw3b** [comment]
Stalled

**Pull request closed without merging**
