### PR TITLE
nixos/podman: add autoPrune option

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Description of changes
simple copy of the docker option: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/docker.nix#L211

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]

**Comment by zowoq** [comment]
@thiagokokada Next time I'd appreciate having more than an hour window to review a PR before it gets merged.

**Comment by thiagokokada** [comment]
> @thiagokokada Next time I'd appreciate having more than an hour window to review a PR before it gets merged.

It was a pretty trivial change that was copied from another service, defaults to false and it is something that I know and use.

If it was something bigger from an area I don't understand I would wait other reviewers, but definitely not this case.

**Comment by zowoq** [comment]
So you completely disregard maintainers and codeowners and just merge stuff straight away?

Not wait a few days or even just 24hrs as a courtesy to the people who do actually maintain it?

You're kidding me right?

**Comment by thiagokokada** [comment]
> So you completely disregard maintainers and codeowners and just merge stuff straight away?
> 
> Not wait a few days or even just 24hrs as a courtesy to the people who do actually maintain it?
> 
> You're kidding me right?

I didn't mean to be disrespectful, I was just justifying why I did what I did.

Let's be technical instead of trying to do personal attacks. Did this change actually cause some issues? If not, I think that is it.

**Comment by thiagokokada** [comment]
BTW, to be clear, it is not that I disregard maintainers and codeowners and as such. It is just for us commiters, this is not something enforced. It is always something that is done in a "best effort" basis, and even then it doesn't work the majority of time since most maintainers are inactive or very slow to respond. The cases where the maintainers are responsible like you @zowoq is very rare.

For anything that you said about a period of waiting to give reviewers the opportunity to review and such: maybe we should, but this should be documented and ideally automated in some way (like disabling the commit button if there is no reviews from a committer in at least a few days). If you feel really strong about this I would recommend trying to open a RFC. I am not the first committer to merge trivial things fast and I will not be the last.

**Comment by zowoq** [comment]
> Let's be technical instead of trying to do personal attacks.

I apologise for the unnecessary "You're kidding me right?" but I don't see how any of this is a personal attack. You aren't the maintainer and yet you merged it very, very quickly.

> it is not that I disregard maintainers and codeowners and as such. It is just for us commiters, this is not something enforced.

A couple of committers have been warned by org owners because of merging stuff to fast.

**Comment by thiagokokada** [comment]
> I apologise for the unnecessary "You're kidding me right?" but I don't see how any of this is a personal attack. You aren't the maintainer and yet you merged it very, very quickly.

You could have said the same thing without being passive aggressive.

> A couple of committers have been warned by org owners because of merging stuff to fast.

Having a proper rule with enforcement from some form of automation would be much better than having org owners manually warn a committer every time this happens.

**Comment by zimbatm** [comment]
@thiagokokada maintainers should be given enough time to review their packages, no matter how small the change. It's not the first time "trivial" changes had deeper implications that only the maintainer would know about. I believe that this is a common etiquette, that might not have been properly transmitted. I agree that this should be documented or automated away if possible.

**Pull request merged**
