### PR TITLE
mopidy-moped: 0.6.0 -> 0.7.0

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 0.7.0 with grep in /nix/store/snl5lx0r61cdy7q0csvwynbn6bbr6ynw-mopidy-moped-0.7.0
- found 0.7.0 in filename of file in /nix/store/snl5lx0r61cdy7q0csvwynbn6bbr6ynw-mopidy-moped-0.7.0

cc "@rickynils"

### CODE REVIEW

**Comment by dotlambda** [comment]
@FRidh Is it okay to change the capitalization of the package name like that?

**Comment by FRidh** [comment]
PyPI needs to have the actual name of the file, which is case-sensitive. While that is the case, yes. The attributes are preferable normalized names. In the long term, the actual names will also be normalized (https://github.com/pypa/warehouse/issues/2537).

**Comment by dotlambda** [comment]
Yeah, but I meant the package name in Nixpkgs, which changes from mopidy-moped to Mopidy-Moped. WIll that for example be a problem for people who installed it using `nix-env -i` and is it nevertheless okay to change the name?

**Comment by FRidh** [comment]
Yes, that can be a problem. Personally, I don't care so much about that.

**Pull request merged**
