### PR TITLE
gImageReader fixed missing Icons

### PR DESCRIPTION
**Pull request by alex-ameen**
###### Motivation for this change

Previous package forgot to properly install UI Icons.

###### Things done

The issue was fixed by adding `gnome3.defaultIconTheme` to buildInputs.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
I believe this is the case for several packages. What if I use a different Gtk theme ? There might be some hook to add this automatically @jtojnar I think you are the gtk specialist ?!

**Comment by jtojnar** [comment]
This is currently not settled issue. On one hand, having `adwaita-icon-theme` in the expression will make the icons work even when the user has no icons installed; on the other hand, it will require people using different theme to have Adwaita in the closure. See also discussion in https://github.com/NixOS/nixpkgs/pull/43150

Also, if you choose the first option, `defaultIconTheme` is deprecated alias, you should use `adwaita-icon-theme` directly.

**Comment by BadDecisionsAlex** [comment]
> This is currently not settled issue. On one hand, having `adwaita-icon-theme` in the expression will make the icons work even when the user has no icons installed; on the other hand, it will require people using different theme to have Adwaita in the closure. See also discussion in #43150
> 
> Also, if you choose the first option, `defaultIconTheme` is deprecated alias, you should use `adwaita-icon-theme` directly.

Do you have a suggestion for a more holistic fix?

**Comment by jtojnar** [comment]
Currently there are these two options and you need to choose based on your priorities.

**Comment by worldofpeace** [comment]
Closing due to inactivity.

The solutions provided by jtojnar still stand though, but I feel in the future we're going to prefer having an icon theme just installed globally.

**Pull request closed without merging**
