### PR TITLE
qt5: inherit from __splicedPackages to fix cross

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thank you so much for this.  The splicing voodoo is still a total mystery to me.  I read the comments in `splice.nix` four or five times and still can't figure out what's going on there.

**Comment by SuperSandro2000** [comment]
The following overlay now causes an infinite recursion

``` 
  plasma5Packages = prev.plasma5Packages.overrideScope (final2: prev2: {
    okular = prev2.okular.override { withSpeech = false; };

    plasma-workspace = prev2.plasma-workspace.overrideAttrs (oldAttrs: {
      buildInputs = oldAttrs.buildInputs or [ ] ++ (with prev2; [ qtimageformats ]);
    });
  });
```
I only changed overrideScope' to overrideScope after seeing the warning and thought that is unexpected.

**Comment by Artturin** [comment]
plasma5Packages is a different set and different file and it doesn't use makeScopeWithSplicing so the overrideScope you're using is the deprecated overrideScope which has the arguments flipped and thats why you're getting the infinite recursion

**Comment by SuperSandro2000** [comment]
plasma5Packages is more or less just an alias for libsForQt5. 
```
  # plasma5Packages maps to the Qt5 packages set that is used to build the plasma5 desktop
  plasma5Packages = libsForQt5;
```
I don't get the warning right now anymore but I forgot which shenanigans I did to get it.

**Comment by Izorkin** [comment]
@Artturin this change may cause murmur to rebuild QT5 unnecessarily again if set to `environment.noXlibs = true;`?

**Comment by Artturin** [comment]
> @Artturin this change may cause murmur to rebuild QT5 unnecessarily again if set to `environment.noXlibs = true;`?

it shouldn't

**Pull request merged**
