### PR TITLE
neomutt: 20211022 -> 20211029

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
ChangeLog: https://github.com/neomutt/neomutt/releases/tag/20211029

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
@flatcap?

**Comment by flatcap** [comment]
Today's been a bit of a \*\*\*\* up.
I pushed a release, then decided against all sense to push a last-minute fix and update the release.

**Then**, I had to revert the "fix".

If you can, please use commit: https://github.com/neomutt/neomutt/commit/4242a31313e0b600693215c01047bbda8a6dd25a
rather than the actual release.

Hopefully it won't affect many people either way.
At the worst case, I'll have to make **another** release :-(

**Comment by Ma27** [comment]
@flatcap thanks for your openness and no worries, I guess we all have days where we make suboptimal decisions!

@flokli I'd update the hash now that we know how it happened and apply https://github.com/neomutt/neomutt/commit/4242a31313e0b600693215c01047bbda8a6dd25a on top. Are you OK with this approach? :)

**Comment by flokli** [comment]
@Ma27 I'm fine with that, even though one could argue other distros will most likely package 20211029.

@flatcap If you don't want that commit to be part of a release, you probably should do another release, and tell people explicitly that the old release shouldn't be used. In general, release artifacts should be immutable once published.

**Comment by Ma27** [comment]
@flokli updated accordingly :)

**Pull request merged**
