### PR TITLE
graalvm8: 19.1.1 -> 19.2.1

### PR DESCRIPTION
**Pull request by hlolli**
###### Motivation for this change
Bumping graalvm8

###### Things done

I fixed fastr and truffleruby so these are now included. I was planing to make it work for darwin, but I'll have to find time later for that, next weekend or next week. I refactored the cache generation into the postUnpack phase. I guess I could refactor some of the patching from the mxgitcaches into the postPatch phase later on.

- [ x ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ x ] NixOS
   - [ x ] macOS
   - [ ] other Linux distributions
- [ x ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @volth

### CODE REVIEW

**Comment by hlolli** [comment]
I'm noticing some hash mismatches as I'm trying to implement for darwin. Please wait with reviewing.

**Comment by hlolli** [comment]
I'll have to admit my inability to get it running on darwin. I was able to get svm running, but I realized that I compiled with clang and not gcc, I asked on graalvm slack, and they re-iterated that graalvm relies on gcc. And while trying to get this running, the gcc call, which is coming from `substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/codegen/CCompilerInvoker.java` doesn't seem to take anything from the environment into account, hence these CoreFoundation patches, because it seemed, no matter how hard I tried or how much gcc manual I read, I couldn't make CoreFoundation.h discoverable (except with direct reference but then all the other headers which CoreFoundation imports will fail).

So anybody with darwin experience, please help. The current error message is

```
 [lli:32101]    classlist:   3,945.83 ms
[polyglot:32100]    classlist:   3,986.76 ms
[polyglot:32100]        (cap):     617.01 ms
[polyglot:32100]        setup:   1,097.46 ms
Error: Error compiling query code (in /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives.c). Compiler command  /nix/store/by6a964hw1pcx2mwg8782096vi7b8jw8-gcc-8.3.0/bin/gcc -F /nix/store/732051j6rg2p3zb3nr5crfqlpaib158z-apple-framework-CoreFoundation/Library/Frameworks -framework CoreFoundation /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives.c -o /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives output included error: /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives.c:78:10: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
    C file contents around line 78:
    /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives.c:77: #include </nix/store/701x446sv332xjff12adla3dvzpf53hk-zlib-1.2.11-dev/include/zlib.h>
    /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives.c:78: #include <CoreFoundation/CoreFoundation.h>
    /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-13236726821528075/PosixDirectives.c:79: #include <sys/event.h>
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[lli:32101]        (cap):     646.13 ms
[lli:32101]        setup:   1,169.34 ms
Error: Error compiling query code (in /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-4470645386342471800/LibCHelperDirectives.c). Compiler command  /nix/store/by6a964hw1pcx2mwg8782096vi7b8jw8-gcc-8.3.0/bin/gcc -F /nix/store/732051j6rg2p3zb3nr5crfqlpaib158z-apple-framework-CoreFoundation/Library/Frameworks -framework CoreFoundation /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-4470645386342471800/LibCHelperDirectives.c -o /var/folders/9k/hr12t49132lgnpzq88w_h6740000gn/T/SVM-4470645386342471800/LibCHelperDirectives output included error: collect2: error: ld returned 1 exit status
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Process Process-362:
```

@volth 

The current head on my PR is in a messed state, I'll either stop trying to get it running on darwin and clean it up for linux and submit this PR that way. Or I find a way to solve it and I keep this PR open.

**Comment by volth** [comment]
> @volth
> The current head on my PR is in a messed state, I'll either stop trying to get it running on darwin and clean it up for linux and submit this PR that way. Or I find a way to solve it and I keep this PR open.

I am happy without Darwin support, it was @regadas who wanted GraalVM on Nix/Darwin

**Comment by arturovm** [comment]
Hi, I'm interested in getting this working on Darwin as well. I could take a look! I'm pretty new to Nix so this might take a little while. If this is a blocker for this PR, then I could do this on a separate branch.

**Comment by hlolli** [comment]
I'm pretty close to getting this done on Darwin. Still an unrelated gcc problem in the way.

**Comment by regadas** [comment]
That’s nice! I actually ended up creating a custom pkg with the pre built Graal binaries (easier and kinda online with other jdk packages)

**Comment by volth** [comment]
@regadas 
Prebuilt binaries are here as well (https://github.com/NixOS/nixpkgs/pull/74010), and they lack Darwin support too.
It would be nice it someone add Darwin binaries (I just have no Darwin hardware to test).

**Comment by hlolli** [comment]
I successfully got all the polyglots working with Darwin, it's quite invasive, becuase the changes to libdispatch, which is required by System framework, requires absolutely everything to be rebuilt. Also I needed to add Java frameworks which weren't implemented.

Anyway, a quick question, I'm back on linux verifying that everything still works as expected, but I'm encountering

```
/nix/store/30b80ymkvhryc8kkifc93psy7mppwz3q-jvmci-19.3-b04/nix-support/setup-hook: line 1: JAVA_HOME: unbound variable
```

Which is strange since the setup-hook is everywhere the same for java

```
$ cat /nix/store/30b80ymkvhryc8kkifc93psy7mppwz3q-jvmci-19.3-b04/nix-support/setup-hook
if [ -z "$JAVA_HOME" ]; then export JAVA_HOME=/nix/store/30b80ymkvhryc8kkifc93psy7mppwz3q-jvmci-19.3-b04; fi
```

I'm super happy to see it working on darwin after 24 days of struggling.

Could you start @GrahamcOfBorg @volth ? This JAVA_HOME error is most likely some strangeness happening for me locally.

**Comment by volth** [comment]
No, if you mean Darwin's @GrahamcOfBorg

My letters to ofborg start only Linux builders. This is not very
useful, because they run implicitly on every PR change :
https://github.com/NixOS/nixpkgs/pull/72331/checks?check_run_id=318228537

**Comment by hlolli** [comment]
sorry, I always had the idea that @GrahamcOfBorg didn't try to built unless instructed to. I fixed that hash mismatch, crossing fingers.

**Comment by hlolli** [comment]
I did screw up the linux build after working with Darwin, but I've fixed all the build errors for linux, but @GrahamcOfBorg doesn't go all the way trough.

```
building of '/nix/store/j5658lwxd2yjc9ip52vp9b9nqyip5ghg-graal-19.2.1.drv' timed out after 3600 seconds
error: build of '/nix/store/j5658lwxd2yjc9ip52vp9b9nqyip5ghg-graal-19.2.1.drv' failed
```

I thought we were mostly dealing with memory problems :)

Otherwise, if anyone has the ability to start a Darwin build on @GrahamcOfBorg, now would be a good time.

**Comment by d-goldin** [comment]
@GrahamcOfBorg build graalvm8

**Comment by hlolli** [comment]
Thanks @d-goldin

strange thing just happened, linux timed out, not surprising. But so did Darwin too, but I guess Darwin wasn't behaving well to the stop sign ( so it's still running, and realistically, it will run for another 4-6 Hours).

```
building of '/nix/store/xsx87x54cshn80i7560wgzqww80y8nga-llvm-7.1.0.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/5379f0fgblwbi0cpigdb5sf2cd441q3l-compiler-rt-7.1.0.drv': 1 dependencies couldn't be built
[ 25%] Building CXX object lib/Transforms/IPO/CMakeFiles/LLVMipo.dir/Internalize.cpp.o
```

is this expected?

**Comment by d-goldin** [comment]
@hlolli:

> strange thing just happened, linux timed out, not surprising. But so did Darwin too, but I guess Darwin wasn't behaving well to the stop sign ( so it's still running, and realistically, it will run for another 4-6 Hours).

Yeah, there is a timeout of 3600 secs configured in ofBorg. I'm not sure if there is a way to disable it. 
How long does the graalvm build itself take? Here it looks like it starts building llvm and what not, which of course cuts into the time. 

If the build itself is not too crazy heavy, it might help to just wait for the dependencies to appear in the binary caches. Otoh, if it times out on amd64, it's unlikely going to be faster.

> ADDED: Darwin timed out as well. So I guess ofborg isn't of much use here.

Maybe there is some way to invoke that differently or some other resources one could use to test.
Let's see. Maybe @grahamc or @NixOS/darwin-maintainers can help out here.

**Comment by d-goldin** [comment]
@hlolli: Meanwhile, here is a build on NixOS: https://gist.github.com/d-goldin/39c9baf677d0b8ea15a5e9e543dfb44a

**Comment by hlolli** [comment]
> @hlolli: Meanwhile, here are the last 1000k lines of a build on NixOS/amd64: https://gist.github.com/d-goldin/39c9baf677d0b8ea15a5e9e543dfb44a

Thanks, 100k lines, WOW

exit code status 137 seems to indicate memory problems. Which is what we were used to. Where could I access these logs?

**Comment by hlolli** [comment]
Btw it takes around 40-55 minutes to build graal8 on my gamer Lenovo Legion laptop. On my brand new MacBook, it takes even shorter, but in this PR I'm adding a patch that causes ~3 hour rebuild from scratch (gcc/llvm/clang are all recompiled), so this PR will be exceptionally long for Darwin.

**Comment by d-goldin** [comment]
@hlolli: That's from a local build. Too big for most paste services, so I dropped it here: https://github.com/d-goldin/random_stash/blob/master/pr_72331_5fbd9fbd7908289b1d72df18f5a2c735178b82be.log

**Comment by hlolli** [comment]
The same thing happening here, exiting with 137. Since I was on the train,
I destroyed my fingers scrolling to the bottom of that page on my phone.

I wonder if there’s any precedence for adding swap file while building a
derivation?

**Comment by hlolli** [comment]
@volth is this merge-able? Is there something I need to do?

**Comment by volth** [comment]
> @volth is this merge-able? Is there something I need to do?

Maybe `19.3.0` ?
Which is LTS and has Java 11, so it could stay for few months

**Comment by hlolli** [comment]
I'll start working on 19.3.0, but that shouldn't prevent this PR from being merged? Can't this be merged?

**Comment by Mic92** [comment]
I can be merged, but since this is a mass-rebuild on macOS, we need this to go through staging. Can you rebase your pull request onto the `staging` branch?

**Comment by hlolli** [comment]
> It can be merged, but since this is a mass-rebuild on macOS, we need this to go through staging. Can you rebase your pull request onto the `staging` branch?

done

**Comment by eraserhd** [comment]
We're ready to merge this to staging, yeah?  Somebody want to hit the button?

**Comment by Mic92** [comment]
Sorry. I missed that. Can you fix the merge conflict?

**Comment by hlolli** [comment]
@Mic92 done

**Comment by hlolli** [comment]
sorry was rebased against master, changed it to staging @Mic92

**Pull request merged**
