### PR TITLE
Kernel 6.6

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

Shadow stacks are opt-in for userspace, so nothing will use them yet, but we should have them for the future. 

RANDOM_KMALLOC_CACHES adds some minimal overhead, but seems worth it: https://lwn.net/Articles/938246/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by alyssais — APPROVED** [review]

**Review by RaitoBezarius — APPROVED** [review]

**Comment by K900** [comment]
Runs fine on my Hetzner box and laptop.

**Comment by andrevmatos** [comment]
I'm experiencing some issues with kernel 6.6 and framebuffer console. On an amdgpu machine, it goes black during boot, and I need to log in and startx blindly (I don't use a graphical login manager). On a virtio-vga/virgl qemu VM, it freezes when loading modules, and I need to also continue blindly.
Most relevant difference I could find between boot dmesg on 6.5.x  and 6.6 in both machines is `kernel: fbcon: amdgpudrmfb (fb0) is primary device` / `kernel: fbcon: virtio_gpudrmfb (fb0) is primary device` lines, present in 6.5 and absent in 6.6.
I'm investigating, but [Arch seems to have changed some CONFIG_FB Kconfigs](https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/commit/af4715d5ae0910a63a02c57c80f25737c8811fde#dfba7aade0868074c2861c98e2a9a92f3178a51b_6888_6919) which may be related.

**Comment by alyssais** [comment]
This sounds very much like [this issue](https://lore.kernel.org/lkml/ZQf-4r1K1Dx_LQ5t@debian.me/) being discussed upstream.

**Comment by andrevmatos** [comment]
Hmm, the effects seem similar, but on NixOS's `/proc/config.gz`, `# CONFIG_DRM_SIMPLEDRM is not set`;

OTOH, diff'ing 6.5 and 6.6's configs, I see `# CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY is not set` only in the later, which may be caused by this big FB refactor in 6.6 (e.g. torvalds/linux@bb6c4507fe825f1b4904fc3ffd329ab196c5e645), which affected Kconfig default options detection and may have gotten that option disabled in our config.

I'm rebuilding 6.6 now with `structuredExtraConfig`, to see if this fixes the issue.

**Comment by alyssais** [comment]
Sounds like it needs a bisect then.

**Comment by andrevmatos** [comment]
I think I found the culprit, it was indeed `CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY`, but together with another option which depended on it, `DRM_FBDEV_EMULATION`, and ended up disabled as well in the 6.5 -> 6.6 transition;
this snippet fixed the issue for me in both systems:
```

**Comment by andrevmatos** [comment]
If anyone can review, please: #264832

**Pull request merged**
