### PR TITLE
libsodium: 1.0.17 -> 1.0.18

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://github.com/jedisct1/libsodium/releases/tag/1.0.18-RELEASE

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
Are you sure about the branch, though?

**Comment by dtzWill** [comment]
Oh, yikes, rebuilds are higher than I expected/realized.  Definitely staging first, don't believe anything critical here so that seems pretty clearly not appropriate for master :).  Sorry for missing that, thanks!

**Comment by dtzWill** [comment]
Sigh.  Wish github had a UI for rebase --onto or someting O:).  Anyway sorry for the above madness.

Looks like this is already on staging, so all is well and nothing more to do here I think!

Thanks for the feedback regardless! <3

**Comment by 7c6f434c** [comment]
@dtzWill I think `libsodium` aims to be «the default choice when you need crypto and sane defaults but nothing fancy», and they are succeeding in selling this narrative… so — a lot of rev-deps.

**Comment by 7c6f434c** [comment]
«Wish that GitHub would have a consistent or at least working UI for _any_ of the obviously needed features» — oh well

**Pull request closed without merging**
