### PR TITLE
nats-server: 2.6.3 -> 2.7.0

### PR DESCRIPTION
**Pull request by derekcollison**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by swdunlop — APPROVED** [review]

**Comment by ipetkov** [comment]
Result of `nixpkgs-review pr 155150` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python310Packages.asyncio-nats-client</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nats-server</li>
    <li>python39Packages.asyncio-nats-client</li>
  </ul>
</details>

**Comment by derekcollison** [comment]
Not even sure why it is building a client along with this..

Do I need to resolve python310Packages.asyncio-nats-client before merging?

**Comment by swdunlop** [comment]
`nats-server` is a check input of `python310Packages.asyncio-nats-client`, which appears to be failing its tests with many variations of the following:

```
=== RUN ProtocolParserTest.test_parse_pong
__________________ ProtocolParserTest.test_parse_split_msg_op __________________

test_case = <tests.parser_test.ProtocolParserTest testMethod=test_parse_split_msg_op>
args = (), kw = {}

    @wraps(test_case_fun)
    def wrapper(test_case, *args, **kw):
        return test_case.loop.run_until_complete(
>           asyncio.wait_for(
                test_case_fun(test_case, *args, **kw),
                timeout,
                loop=test_case.loop
            )
        )
E       TypeError: wait_for() got an unexpected keyword argument 'loop'

tests/utils.py:449: TypeError
```

This failure occurs with this PR, but it also fails with the master branch, as of 73757db5fbf4e970e6b75256424d3060a0f71ba7.  This suggests the issue is not with nats-server 2.7.0 or this PR, but with Python 3.10 and Asyncio.  The same package failed to build [here](https://github.com/NixOS/nixpkgs/pull/154059#pullrequestreview-848454579), suggesting all is not right with Python 3.10.

**Comment by bobby285271** [comment]
@ofborg build python39Packages.asyncio-nats-client nats-server

**Pull request merged**
