### PR TITLE
R: Use HTTPS for package generation, check BIOC version, use MRAN packages

### PR DESCRIPTION
**Pull request by abbradar**
Re https://github.com/NixOS/nixpkgs/issues/11243.

### CODE REVIEW

**Comment by abbradar** [comment]
BTW we might want to disable R packages builds on Hydra again now.

**Comment by peti** [comment]
Test builds are running at http://hydra.cryp.to/jobset/nixpkgs/r-updates. We have one evaluation error so far:

~~~
in job ‘rPackages.tikzDevice.x86_64-linux’:
assertion failed at [1m/nix/store/6wvqixpyqpn0ppkk95wk9yaprh6a3v9z-git-export/pkgs/tools/typesetting/tex/texlive/default.nix[0m:11:9
~~~

**Comment by peti** [comment]
OK, the evaluation error is fixed by f46b1a34989ef4b4e29fdccb293e5fc33cc1b7ce. I think it was completely unrelated to your patches.

**Comment by peti** [comment]
OK. Now there are more errors at http://hydra.cryp.to/jobset/nixpkgs/r-updates#tabs-errors. I suppose the `default.nix` file needs updating.

**Comment by peti** [comment]
All issue fixed and patches merged now.

**Comment by abbradar** [comment]
Thanks, I was somewhat busy and planned to do this later today but you outran me ^_^
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by abbradar** [comment]
BTW, do we want to have Hydra package builds for R packages now? I assumed that they were enabled only because of the issue, although I see no harm in this (apart from maybe free space issues)...

**Comment by peti** [comment]
I'll disable the R builds if it turns out that they cause trouble.

**Comment by vcunat** [comment]
Cause trouble? Like taking lots of space on HDD?

**Comment by peti** [comment]
Yes, that would be the kind of trouble that would give us a reason to disable the builds again, although disabling the R builds is not going to have much of an effect on the space requirements as the installed packages are small.

**Pull request closed without merging**
