### PR TITLE
libunistring: 1.2 -> 1.3

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://savannah.gnu.org/news/?id=10682

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jopejoe1 — APPROVED** [review]
Build a few packages with this.

**Comment by ofalvai** [comment]
FYI `guile` is broken on staging on Darwin with this error:

```
guile> checking whether libunistring was built with iconv support... no
guile> configure: error: No iconv support.  Please recompile libunistring with iconv enabled.
```

and git bisect confirmed that this PR caused it.

**Comment by trofi** [comment]
Thank you for the report! Looking.

**Comment by paparodeo** [comment]
this test is failing with libunistring 1.3 but passes with 1.2
```c

#include <uniconv.h>
#include <unistring/iconveh.h>
int
main (int argc, char *argv[])
{
size_t result_size;
return (NULL == u32_conv_from_encoding ("ASCII", iconveh_question_mark,
                                        "a", 1,
                                        NULL, NULL, &result_size));
}
```

**Comment by trofi** [comment]
Is it a build failure or runtime failure?

**Comment by paparodeo** [comment]
> Is it a build failure or runtime failure?

runtime failure. 1.3 added a check for macOS 14 libiconv bugs which fails.
https://lists.gnu.org/archive/html/bug-gnulib/2024-05/msg00375.html
see also some discussion in the matrix macOS channel.

**Comment by trofi** [comment]
Aha, nice! Thank you! Does passing `am_cv_lib_iconv=no` to `configureFlags` help by chance?

**Comment by trofi** [comment]
Sorry, should probably be `am_cv_func_iconv_works=no`.

**Comment by paparodeo** [comment]
> Sorry, should probably be `am_cv_func_iconv_works=no`.

`am_cv_func_iconv_works=yes` works  I assume `am_cv_func_iconv_works=no` has the same effect as the configure test failing.

`doCheck = false;` so we don't notice that the tests fail with the macOS 15 libiconv.

**Comment by paparodeo** [comment]
https://github.com/NixOS/nixpkgs/pull/364495 uses gnu libiconv for darwin. if tests were enabled they would pass

**Pull request merged**
