### PR TITLE
quake3e: 2019-11-29 -> 2020-01-23

### PR DESCRIPTION
**Pull request by pmiddend**
###### Motivation for this change

Regular update. I've tested this by starting the game and playing a round.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

```
[3 built, 1 copied (0.0 MiB), 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/79999
1 package built:
quake3e
```

**Comment by jonringer** [comment]
actually, do you mind adding:
```
  meta = {
    ...
   badPlatforms = [ lib.platforms.aarch64 ];
```
to prevent hydra trying to build this

**Comment by pmiddend** [comment]
@jonringer Thanks for the suggestion, I added the `badPlatforms` bit.

**Comment by jonringer** [comment]
@GrahamcOfBorg build quake3e

**Pull request merged**
