### PR TITLE
openssl: upgrade to 1.0.1m

### PR DESCRIPTION
**Pull request by paraseba**
This is a critical security update, see
https://www.openssl.org/news/secadv_20150319.txt

It will fail patching for kfreebsd, I don't know how to test it and the patch
is not trivial

### CODE REVIEW

**Comment by paraseba** [comment]
I don't think the travis failure is related to the change

**Comment by iElectric** [comment]
It's already in `staging` branch

**Comment by peti** [comment]
Already in 2fe351c7e31f47400d752a59ab7b1e2e89acf392.

**Comment by vcunat** [comment]
I think that's four times today, at least :-)

**Pull request closed without merging**
