### PR TITLE
CODEOWNERS: Track owners and followers

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Let's have our cake and eat it too?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Profpatsch** [comment]
I recently noticed that the `CODEOWNERS` file is more integrated into Github than I initially thought. People can request reviews from code owners, and apparently this is actively proposed by the PR process.

**Comment by Ericson2314** [comment]
@Profpatsh I believe the reviews are requested unconditionally.

**Comment by NeQuissimus** [comment]
I am bit concerned with the maintainability of the indentation.

Is it possible to list paths twice? i.e.

```
=== Owners ===
lib/* @User1 @User2

===Followers===
lib/* @User3 @User4 @User5
```

**Comment by FRidh** [comment]
@NeQuissimus 
From the example:
```
# Order is important; the last matching pattern takes the most
# precedence. When someone opens a pull request that only
# modifies JS files, only @js-owner and not the global
# owner(s) will be requested for a review.
*.js    @js-owner
```

**Comment by NeQuissimus** [comment]
That is unfortunate...

**Comment by Ericson2314** [comment]
https://github.com/NixOS/rfcs/pull/19 however it lands will obsolete this.

**Pull request closed without merging**
