### PR TITLE
Organize KDE packages correctly

### LINKED ISSUE #23041: KDE5 Doesn't Exist
Apparently there is no such thing as KDE5, it is now

 - Frameworks
 - Plasma
 - Applications

each versioned separately. KDE is the community.

I was talking on IRC (#kde on freenode) and was asked to have the references to KDE4 and KDE5 fixed, as there is no KDE5 and it has not been called KDE4 in some time.

tosky provided these links:

 - https://dot.kde.org/2014/06/26/where-kde-going-part-1
 - https://dot.kde.org/2014/07/02/where-kde-going-part-2
 - http://tsdgeos.blogspot.cz/2014/08/kde-releases-in-future.html

and offered the following resources to help distros / packagers:

 - #kde-devel on freenode
 - this ML for distributions: https://mail.kde.org/mailman/listinfo/distributions
 - this ML for packagers and packaging issues: https://mail.kde.org/mailman/listinfo/kde-distro-packagers

and noted that we can register for pre-releases for Frameworks, Plasma, and Applications for pre-testing by filing a "sysadmin" ticket here: https://phabricator.kde.org/maniphest/task/edit/form/2/ (requires registration: https://identity.kde.org/index.php?r=registration/index) and providing evidence that you're coming from NixOS.

When we have a plan, we might want to stop by #kde-devel on Freenode and have them check it out.

cc @ttuegel

### PR DESCRIPTION
**Pull request by ttuegel**
### Problem

Fixes #23041: KDE 5 does not exist.

### Solution

- Split the top-level package set `kde5` up into `kdeFrameworks`, `kdeApplications`, and `plasma5`.
- Rename the desktop environment from `kde5` to `plasma5`.
- Separate packages that are part of Qt 5 (`qt5`) from libraries that only depend on it (`libsForQt5`).
- Make libraries from `kdeApplications` and `plasma5` available in `libsForQt5` alongside libraries from `kdeFrameworks`.
- Make user-facing KDE applications available at top-level.
- Update the documentation for Qt 5 and KDE.
- Remove the Qt dependency from KDE build tools that do not actually require it.
- Fix several Qt-based packages that were not importing dependencies correctly.
- Update `qt5` to point at `qt57`. (It should always be the latest version.)

### Testing

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Is it unreasonable to mark this as a blocker for 17.03?

**Comment by grahamc** [comment]
@copumpkin is building this PR with nox-review on a big server.

**Comment by ttuegel** [comment]
@grahamc No, wait! It's not done yet :(

**Comment by ttuegel** [comment]
Also, how big? I can manage 16 builds at once on my workstation.

**Comment by grahamc** [comment]
Can you hop on IRC to discuss?

**Comment by ttuegel** [comment]
I tested evaluation locally, everything looks good. I also rebuilt everything KDE-related (thanks @grahamc and @copumpkin!). For some reason, I had difficulty getting `nox-review` to work on the test box, so there may be a few packages that are not OK with the Qt 5.6 to Qt 5.7 upgrade. I'm checking that now, but I can cherry-pick fixes as needed; it would be best to get Hydra on this ASAP.

**Comment by vcunat** [comment]
Hydra eval: http://hydra.nixos.org/eval/1336834

**Comment by ttuegel** [comment]
Thanks; it looks like most of the new failures are trivially either:
- Doesn't build with Qt 5.7 and needs to be pinned to Qt 5.6, or
- No longer inherit Qt dependencies from build tools that didn't actually need them, in which case the package simply needs an explicit Qt dependency.

**Comment by tosky** [comment]
Thanks for this work!

**Comment by orivej** [comment]
When a package provides a program (not a library) and needs qt5 (not KDE libraries), is the choice to use `libsForQt5.callPackage` rather than `callPackage` just stylistic, or is it consequential?

**Comment by ttuegel** [comment]
> When a package provides a program (not a library) and needs qt5 (not KDE libraries), is the choice to use libsForQt5.callPackage rather than callPackage just stylistic, or is it consequential?

Whether KDE is needed or not, `libsForQt5.callPackage` guarantees that all dependencies are built with the same version of Qt. Using `callPackage`, one must check this condition by hand; in most cases that is quite simple, but I have seen a few cases that are not.

**Pull request merged**
