### PR TITLE
xxdiff: drop the old qt4 version in favour of qt5

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

We have been carrying the qt5 version for a long time (which works fine), so let's just drop the old qt4 variant. Also use the proper qt5 ```mkDerivation```.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @psub @7c6f434c

### CODE REVIEW

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build xxdiff xxdiff-tip

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build xxdiff

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build xxdiff

**Comment by 7c6f434c** [comment]
What's going on with the source?

**Comment by peterhoeg** [comment]
> What's going on with the source?

Do you mind trying to do nix-prefetch-url on your side? When I do it here, I get the same sum as as in the PR.

**Comment by 7c6f434c** [comment]
Wait, `nix-prefetch-url` on what? The new expression uses `fetchFromBitbucket`, which unpacks.

Local build produces the same hash mismatch error as ofBorg.

**Comment by peterhoeg** [comment]
> Wait, nix-prefetch-url on what? The new expression uses fetchFromBitbucket, which unpacks.
> Local build produces the same hash mismatch error as ofBorg.

That's so strange - it works perfectly fine here.

**Comment by 7c6f434c** [comment]
And if you GC the output of `xxdiff.src`, does everything still build afterwards?

**Comment by peterhoeg** [comment]
> And if you GC the output

You're a star! That did it.

**Comment by 7c6f434c** [comment]
Why build-time `sourceRoot` is any different from doing `cd src` in `preConfigure`?

**Comment by peterhoeg** [comment]
> Why build-time ```sourceRoot``` is any different from doing ```cd src``` in preConfigure?

Because if we set ```sourceRoot```, only the ```src``` directory gets copied over to the build directory so we no longer have access to the README that needs copying in at install time. Additionally, we would have to patch the make files to not place the output in ```../bin```.

**Comment by 7c6f434c** [comment]
>Because if we set ```sourceRoot```, only the ```src``` directory gets copied over to the build directory so we no longer have access to the README that needs copying in at install time. 

This is not what is defined in `setup.sh`, and not what happens in practice if I set `sourceRoot` to be `source/src`

>Additionally, we would have to patch the make files to not place the output in ```../bin```.

Ah right, writing outside `sourceRoot` is a problem as it is still read-only. But I guess this is what the comment should say, because right now it looks strange.

**Comment by peterhoeg** [comment]
> This is not what is defined in `setup.sh`

Which ```setup.sh```?

> and not what happens in practice if I set `sourceRoot` to be `source/src`

The README file is outside the source directory after it has been unpacked/copied over, but we can still get to it via ```${src}/README```.

> Additionally, we would have to patch the make files to not place the output in ```../bin```.
> Ah right, writing outside `sourceRoot` is a problem as it is still read-only. But I guess this is what the comment should say, because right now it looks strange.

I've cleaned it up. Let me know what you think.

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
> > This is not what is defined in `setup.sh`
> Which `setup.sh`?

`pkgs/stdenv/generic/setup.sh`
 
> > and not what happens in practice if I set `sourceRoot` to be `source/src`
> The README file is outside the source directory after it has been unpacked/copied over, but we can still get to it via `${src}/README`.

Actually, `../README` also works, but whatever you consider cleaner.

Unpack phase copies entire `${src}`, but then only `./${sourceRoot}` is made writeable.

> I've cleaned it up. Let me know what you think.

Nice, thanks.

**Comment by peterhoeg** [comment]
> Unpack phase copies entire ${src}, but then only ./${sourceRoot} is made writeable.

I must have missed something then. I'm sure I tried the ```../README.md``` bit as well. Oh well. It works, everybody is happy! Thanks man!

**Pull request merged**
