### PR TITLE
nixos/httpd: replace ssmtp with system-sendmail

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Currently mod_php won't work with postfix.

cc @Ekleog as the maintainer of system-sendmail

###### Things done
Tested using php mail function in mod_php using both networking.defaultMailServer and services.postfix.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by Ekleog — APPROVED** [review]
Looks good to me!

cc @globin @etu as maintainers for PHP if you know whether there would be issues with a `sendmail` in path that always fail.

Context: currently if `directDelivery` isn't set then there is no `sendmail` in path. Following this change, even if `directDelivery` is set, there will be a `sendmail` in path, but it will fail unless there is a `sendmail` globally installed.

**Comment by aanderse** [comment]
@Ekleog if no real sendmail is installed the apache error logs simply output the error from system-sendmail.

**Comment by Ekleog** [comment]
OK, let's merge, then. Thank you!

**Comment by aanderse** [comment]
Great thanks! Can we cherry pick to 19.03? If not now then after the freeze/release?

**Comment by Ekleog** [comment]
Right, it's now in 19.03 67bc63f9a7ac1b4d1a7114c88ca1a4df03bfdb0e :)

I haven't backported to 18.09 as it sounds like too much risk for the benefit, given everyone has been living with the issue for months now :)

**Comment by aanderse** [comment]
Agreed, thanks!

**Pull request merged**
