### PR TITLE
urbit: 0.4.5 -> 0.6.0

### PR DESCRIPTION
**Pull request by bsima**
###### Motivation for this change

Updated to latest released version, verified working with the latest network breach.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
@GrahamcOfBorg build urbit

**Comment by timokau** [comment]
Great first contribution, I couldn't find a single thing to complain about :smile: Keep up the good work!

**Comment by timokau** [comment]
I just noticed that this PR was based on `release-18.03`. It should have been based on master.

`release-18.03` is a release support branch. Only minor package updates and bugfixes should be pushed there. `master` is the "rolling release" branch from which the next release will be cut.

I'll fix this for you, no big deal. I should have paid more attention before merging. Just remember it next time :)

**Comment by bsima** [comment]
Thanks for letting me know, and thanks for merging this! 

I did try to rebase onto master but there were a ton of conflicts to resolve and I wasn’t sure what to do. Rebasing to release-18.03 worked without a conflict. 

Sorry I should have explained, but honestly I didn’t expect this to be merged so quickly :)

**Comment by samueldr** [comment]
@timokau maybe this message slipped under the cracks earlier today

```
[09:45:43] <samueldr> timokau[m]: urbit is already 0.6.0 on master it looks like; this feels more like an issue with how the user attempted the backport
[09:46:23] <samueldr> as for whether this was fine to backport, rules are still fuzzy :/
```

[Current master has 0.6.0 already](https://github.com/NixOS/nixpkgs/blob/d2b08c432cc9ec35691ab27085dfc7c6f404448b/pkgs/misc/urbit/default.nix#L7)

@bsima was it your intent to backport 0.6.0 to 18.03?

**Comment by bsima** [comment]
>@bsima was it your intent to backport 0.6.0 to 18.03?

No that was not my intent. I just didn't realize that urbit was already bumped
to 0.6.0 in master, sorry! This PR can be ignored.

Although if backporting is an option, I would volunteer to do it if someone can
point me to docs on what the process is. I haven't seen docs on this in the
parts of the manual that I've read.

**Comment by timokau** [comment]
@samueldr oh yeah I missed that, thanks for repeating it here.

@bsima basically for backporting the rule number 1 is to not break anything. The releases should be stable. So the api should not have any backwards incompatible changes and you should be reasonable sure to not break any reverse dependencies.

**Comment by timokau** [comment]
With semver a good rule of thumb is to backport only patch releases. Of course that goes out of the window with `0.x` versions.

**Comment by bsima** [comment]
Okay, then I'll leave this as it is. For the record, urbit-0.6.0 does work on
NixOS 18.03 (I'm running it now), so if anyone wants to they can build it from
one of the nix expressions on master or my branch in this PR.

**Pull request merged**
