### PR TITLE
samba: 4.7.10 -> 4.10.2

### PR DESCRIPTION
**Pull request by aneeshusa**
Release notes: https://www.samba.org/samba/history/samba-4.10.2.html
Notably, Samba 4.10.0 is the first with Python 3 support,
and the 4.10 line will be the last supporting Python 2,
so switch to Python 3.

Add myself as a maintainer.

###### Motivation for this change

I set up Samba and wanted to use an up-to-date version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [WIP] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [WIP] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aneeshusa** [comment]
@grahamcofborg test samba

**Comment by xeji** [comment]
@GrahamcOfBorg build samba sambaFull

**Comment by xeji** [comment]
Local build of `sambaFull` on x86_64-linux fails in configurePhase with
`Samba AD DC and --enable-selftest requires lmdb 0.9.16 or later`
(based on master 180aa2125 with this PR)

**Review by xeji — CHANGES_REQUESTED** [review]
fix build, see comments and ofborg logs

**Comment by bachp** [comment]
There is already Samba 4.10.2 with two additional CVE fixes: https://www.samba.org/samba/history/samba-4.10.2.html

**Comment by bachp** [comment]
`samba` is sucessfully building and working. Tested it on my server.

`sambaFull` fails with the message mentioned by @xeji.  Adding `lmdb` and `gpgme` to `buildInputs` makes it compile.

**Comment by aneeshusa** [comment]
@GrahamcOfBorg build samba sambaFull

**Comment by aneeshusa** [comment]
@GrahamcOfBorg test samba

**Comment by aneeshusa** [comment]
Thanks for the reviews @xeji @bachp, updated to 4.10.2 and added the missing deps. (I didn't even realize we had a `sambaFull`!)

**Review by bachp — APPROVED** [review]
Both `samba` and `sambaFull` are now working

**Review by xeji — APPROVED** [review]

**Pull request merged**
