### PR TITLE
python3Packages.qiskit: 0.32.0 -> 0.32.1

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change
﻿
Update python3Packages.qiskit ot latest version.
- python3Packages.yfinance: 0.1.66 -> 0.1.67
- python3Packages.qiskit-ibmq-provider: 0.18.0 -> 0.18.1
- python3Packages.qiskit: 0.32.0 -> 0.32.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
So far I see failing tests of `qiskit-aqua`:

```bash
error: builder for '/nix/store/nh72xi92vw8wfckvv6p9p6h2q1yr06qq-python3.8-qiskit-aqua-0.9.5.drv' failed with exit code 1;
       last 10 log lines:
       > 18.46s call     test/aqua/test_rmg.py::TestRandomMatrixGenerator::test_random_unitary_3__1000_
       > 17.81s call     test/aqua/test_iqpe.py::TestIQPE::test_iqpe_3___QUBIT_OP_H2_WITH_2_QUBIT_REDUCTION____statevector_simulator___1__6__True_
       > 15.80s call     test/aqua/test_rmg.py::TestRandomMatrixGenerator::test_random_hermitian_3__1000_
       > 14.82s call     test/optimization/test_qaoa.py::TestQAOA::test_qaoa_qc_mixer_4
       > 11.16s call     test/aqua/test_amplitude_estimation_circuitfactory.py::TestBernoulli::test_statevector_07
       > 9.77s call     test/chemistry/test_bosonic_transformation.py::TestBosonicTransformation::test_with_numpy_minimum_eigensolver
       > =========================== short test summary info ============================
       > FAILED test/chemistry/test_driver_methods_fcidump.py::TestDriverMethodsFCIDump::test_lih
       > FAILED test/chemistry/test_driver_methods_fcidump.py::TestDriverMethodsFCIDump::test_lih_freeze_core
       > = 2 failed, 1494 passed, 278 skipped, 206 deselected, 5237 warnings in 728.55s (0:12:08) =
```

**Comment by drewrisinger** [comment]
Huh, interesting. I get clean build of ``qiskit-aqua``, on ``x86-64-linux`` (non-NixOS)
```
10 packages built:
python38Packages.qiskit python38Packages.qiskit-aqua python38Packages.qiskit-finance python38Packages.qiskit-ibmq-provider python38Packages.yfinance python39Packages.qiskit python39Packages.qiskit-aqua python39Packages.qiskit-finance python39Packages.qiskit-ibmq-provider python39Packages.yfinance
```

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 147048 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>10 packages built:</summary>  <ul>    <li>python38Packages.qiskit</li>    <li>python38Packages.qiskit-aqua</li>    <li>python38Packages.qiskit-finance</li>    <li>python38Packages.qiskit-ibmq-provider</li>    <li>python38Packages.yfinance</li>    <li>python39Packages.qiskit</li>    <li>python39Packages.qiskit-aqua</li>    <li>python39Packages.qiskit-finance</li>    <li>python39Packages.qiskit-ibmq-provider</li>    <li>python39Packages.yfinance</li>  </ul></details>

**Comment by drewrisinger** [comment]
Ah, I think the build errors @fabaff had are due to long-running tests in ``qiskit-aqua``, per https://hydra.nixos.org/build/158873896/nixlog/1. They are set to timeout at 30s (I did this because I had some tests NEVER timeout, and didn't want to do that to the hydra machine/users). Your system must be slower/more heavily-loaded than mine, so you're hitting the timeout limit. I'll take a closer look at if those tests should be disabled b/c they're consistently slow, or just extend the timeout (separate PR)

**Comment by fabaff** [comment]
It seems that way as the tests are passing for Jon.

**Pull request merged**
