### PR TITLE
inotify-tools: 3.21.9.5 -> 3.21.9.6

### PR DESCRIPTION
**Pull request by trofi**

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build CuboCore.coretoppings appimagekit dovecot dovecot_fts_xapian dovecot_pigeonhole fragments gerbera git-sync inotify-tools libtransmission llpp nextcloud-client sshlatex torrential transmission transmission-gtk transmission-qt

**Comment by bobby285271** [comment]
Ooops, the sha256 needs update...

**Comment by trofi** [comment]
> Ooops, the sha256 needs update...

Great catch! Updated hash with updater script. Added trivial updater script to avoid manual version patching.

**Comment by bobby285271** [comment]
@ofborg build CuboCore.coretoppings appimagekit dovecot dovecot_fts_xapian dovecot_pigeonhole fragments gerbera git-sync inotify-tools libtransmission llpp nextcloud-client sshlatex torrential transmission transmission-gtk transmission-qt

**Pull request merged**
