### PR TITLE
mysql-workbench: 8.0.21 -> 8.0.30

### PR DESCRIPTION
**Pull request by dotNox**
###### Description of changes

Changes:
* Updated MySQL-Workbench version from 8.0.21 to 8.0.30
* Updated versions of some dependencies, including Python packages

This pull request might fix the following two issues:
* #163258
* #160455

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LeSuisse** [comment]
@ofborg eval

**Review by LeSuisse — COMMENTED** [review]
Builds and works on x64_64.

Result of `nixpkgs-review pr 191174` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mysql-workbench</li>
  </ul>
</details>

**Review by anthonyroussel — APPROVED** [review]
Result of nixpkgs-review pr 191174 run on x86_64-linux 1

<details>
<summary>
1 package built:
</summary>
<ul>
<li>mysql-workbench</li>
</ul>
</details>

Build & run OK on x86_64-linux

**Comment by lucasew** [comment]
Captura de tela de 2022-10-27 19-11-45

Captura de tela de 2022-10-27 19-23-30

Captura de tela de 2022-10-27 19-25-56

Tested it with the following docker command: `docker run -e MYSQL_ROOT_PASSWORD=my-secret-pw -p 3306:3306 -d mysql`

Working nice on GNOME running latest unstable and on i3wm running latest stable.

**Review by lucasew — APPROVED** [review]

**Review by thiagokokada — APPROVED** [review]

**Comment by machadofguilherme** [comment]
It didn't work here. I executed the following command :

`nix-env -iA nixos.mysql-workbench`

**Comment by lucasew** [comment]
Your nixpkgs channel might be outdated

Em qui., 24 de nov. de 2022 22:53, Guilherme Machado <
***@***.***> escreveu:

**Pull request merged**
