### PR TITLE
kismet: 2016-07-R1 -> 2019-09-R1

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
noticed @r-ryantm couldn't update this

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build kismet

**Review by Lassulus — CHANGES_REQUESTED** [review]
currently fails during nix-review with
```
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/7520z75qzn1dj3frd2q83k1f8b753zv7-kismet-2019-09-R1.drv' failed with exit code 2; last 10 log lines:
  
    https://setuptools.readthedocs.io/en/latest/easy_install.html
  
  Please make the appropriate changes for your system and try again.
  
  make[2]: *** [Makefile:14: install] Error 1
  make[2]: Leaving directory '/build/kismet-2019-09-R1/capture_sdr_rtl433'
  make[1]: *** [Makefile:336: commoninstall] Error 2
  make[1]: Leaving directory '/build/kismet-2019-09-R1'
  make: *** [Makefile:448: install] Error 2
cannot build derivation '/nix/store/bj56fqdm4g6dvghi1486pah51f08vrqd-env.drv': 1 dependencies couldn't be built
[2 built (1 failed), 8 copied (2.8 MiB), 0.9 MiB DL]
error: build of '/nix/store/bj56fqdm4g6dvghi1486pah51f08vrqd-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/72846
1 package failed to build:
kismet
```

**Comment by jonringer** [comment]
unfortunately while building the wheel for the package, it fails

**Comment by jonringer** [comment]
I don't have energy to fix this unfortunately :(

**Pull request closed without merging**
