### PR TITLE
jc: 1.13.4 -> 1.14.0

### PR DESCRIPTION
**Pull request by Atemu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108257` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>jc (python38Packages.jc)</li>
<li>python37Packages.jc</li>
<li>python39Packages.jc</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108257` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>jc (python38Packages.jc)</li>
<li>python37Packages.jc</li>
<li>python39Packages.jc</li>
</ul>
</details>

**Comment by Atemu** [comment]
@SuperSandro2000 I really appreciate the auto-nixpkgs-review but it's a bit verbose IMO. Might be better to group your automated replies into one comment for all platforms and only add a link to an explanation.

Even better would be an optional GitHub actions check like ofBorg's if that's possible.

Thank you!

**Comment by SuperSandro2000** [comment]
> Might be better to group your automated replies into one comment for all platforms

I have no idea how to easily to this when the command is run on two machines. I would need to parse the comments and edit one. Sounds a bit tricky.

> and only add a link to an explanation.

I can probably remove some of the explanations when I finalized the readme in the repo.

> Even better would be an optional GitHub actions check like ofBorg's if that's possible.

Github actions are nice if you run Shellcheck over your code but not when you done a gigabyte repo which takes 3 minutes and then build up to a hundred packages. Also the free tier is probably not enough for my usage.

**Pull request merged**
