### PR TITLE
glamoroustoolkit: 1.0.11 -> 1.0.42

### PR DESCRIPTION
**Pull request by akgrant43**
Changes:

- Work around an issue with patchelf 0.12 and later by using patchelf 0.11 (see https://github.com/NixOS/patchelf/issues/546)
- Set "dontStrip = true" as patchelf 0.11 corrupts libWinit.so
- Add dependencies for new library libWebView
- Add zenity to $PATH (used for GlamorousToolkit file open dialog)

## Description of changes

See https://github.com/feenkcom/gtoolkit-vm/releases/tag/v1.0.42

## Things done

This is a resubmission of https://github.com/NixOS/nixpkgs/pull/339546 (where I accidentally did a mass ping, sorry!).

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by akgrant43** [comment]
This is a replacement for https://github.com/NixOS/nixpkgs/pull/339546

**Comment by qbit** [comment]
```
       error: attribute 'zenity' missing
       at /home/qbit/.cache/nixpkgs-review/pr-339709-1/nixpkgs/pkgs/development/tools/glamoroustoolkit/default.nix:90:7:
           89|     binPath = lib.makeBinPath [
           90|       pkgs.gnome.zenity   # File selection dialog
             |       ^
           91|     ];
```

Something else is amiss :D

**Comment by akgrant43** [comment]
> ```
>        error: attribute 'zenity' missing
>        at /home/qbit/.cache/nixpkgs-review/pr-339709-1/nixpkgs/pkgs/development/tools/glamoroustoolkit/default.nix:90:7:
>            89|     binPath = lib.makeBinPath [
>            90|       pkgs.gnome.zenity   # File selection dialog
>              |       ^
>            91|     ];
> ```
> 
> Something else is amiss :D

Right.  Running

```
nix-env --query --available --out-path --file ./. --show-trace
```

suggests that `pkgs.gnome.zenity` should be replaced with `pkgs.zenity`, however doing that causes the build to fail (as opposed to just OfBorg complaining).

**Comment by suhr** [comment]
A little suggestion:

```diff
diff --git a/pkgs/development/tools/glamoroustoolkit/default.nix b/pkgs/development/tools/glamoroustoolkit/default.nix
index dc057c7dc700..7410fdc7617b 100644
--- a/pkgs/development/tools/glamoroustoolkit/default.nix
+++ b/pkgs/development/tools/glamoroustoolkit/default.nix
@@ -1,5 +1,5 @@
 { lib
-, pkgs
+, zenity
 , stdenv
 , fetchzip
 , fetchurl
@@ -87,7 +87,7 @@ preFixup = let
       stdenv.cc.cc.lib
     ];
     binPath = lib.makeBinPath [
-      pkgs.gnome.zenity   # File selection dialog
+      zenity   # File selection dialog
     ];
   in ''
     chmod +x $out/lib/*.so
```

**Comment by akgrant43** [comment]
> A little suggestion:
> ...

```
> nix-build -E '((import <nixpkgs> {}).callPackage(import ./default.nix) {})'                                                        3:16PM
error:
       … while calling the 'abort' builtin

         at /nix/store/1h99qq6970gkx3j0m9w4yrrl9y99y1nk-source/lib/customisation.nix:269:13:

          268|        # which is especially relevant with allowAliases = false
          269|        else abort "lib.customisation.callPackageWith: ${error}";
             |             ^
          270|

       error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "zenity" at /home/alistair/nixos/nixpkgs/pkgs/development/tools/glamoroustoolkit/default.nix:2, did you mean "zenith" or "zinit"?'
```

I wonder if this is an issue with zenity being moved from `pkgs.gnome.zenity` to a by-name package `pkgs.zenity`?

**Comment by suhr** [comment]
Weird, I was able to build this with `nix build '.#glamoroustoolkit'` in the nixpkgs repo.

**Comment by suhr** [comment]
Indeed, the package was moved three months ago: https://github.com/NixOS/nixpkgs/commit/b69ed4249d7ad2266043a7c16cf0b0cca7af08f6.
I believe rebasing against the latest master will fix the problem.

**Comment by akgrant43** [comment]
> Weird, I was able to build this with `nix build '.#glamoroustoolkit'` in the nixpkgs repo.

Ahh, I've been using:

```
nix-build -E '((import <nixpkgs> {}).callPackage(import ./default.nix) {})'
```

`nix build '.#glamoroustoolkit'` also works for me.

I'll try updating the PR and see if it makes OfBorg happy.

Thanks for clarifying!

**Comment by akgrant43** [comment]
> Indeed, the package was moved three months ago: [b69ed42](https://github.com/NixOS/nixpkgs/commit/b69ed4249d7ad2266043a7c16cf0b0cca7af08f6). I believe rebasing against the latest master will fix the problem.

I'm currently committing on top of:

```
commit 13c7cdc211e375ead8b14a78448b8512161e934e (origin/master, origin/HEAD)
Merge: 233f326a0056 09850cda27f7
Author: Masum Reza <50095635+JohnRTitor@users.noreply.github.com>
Date:   Thu Sep 5 09:51:58 2024 +0530
```

so I don't think rebasing will help.  I'm a bit nervous trying to rebase as last time I did that it resulted in a mass ping. :-)

I'll see how your previous suggestion goes first.

Thanks!

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 339709` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>glamoroustoolkit</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Comment by akgrant43** [comment]
Closing as this has been stuck in checks since last week and there has been a new release of the GlamorousToolkit VM since then.  Replaced by https://github.com/NixOS/nixpkgs/pull/341311.

**Pull request closed without merging**
