### PR TITLE
marktext: 0.16.0-rc.2 -> 0.16.1

### PR DESCRIPTION
**Pull request by nh2**
##### Motivation for this change

Changelog: https://github.com/marktext/marktext/blob/v0.16.1/.github/CHANGELOG.md#0161

Follow-up to #77694.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
Builds on and runs on my machine.

Opening the file open dialog crashes it for me with

```
(marktext:21502): GLib-GIO-ERROR **: 19:13:11.316: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
```

but that also happens on the current version (when I on my 19.09 machine start the same `marktext` version from nixpkgs `master`) so I suspect that just happens when trying to run `master` things on my 19.09.

**Comment by srhb** [comment]
On my 20.03, this crashes with:

```
(marktext:45852): GLib-GIO-ERROR **: 20:36:48.243: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

But maybe that's just a normal impurity?

**Comment by nh2** [comment]
> On my 20.03, this crashes with

Same on Ubuntu  now.

I found the solution:

```diff
   profile = ''
     export LC_ALL=C.UTF-8
+  ''
+  # Fixes file open dialog error
+  #     GLib-GIO-ERROR **: 20:36:48.243: No GSettings schemas are installed on the system
+  # See https://github.com/NixOS/nixpkgs/pull/83701#issuecomment-608034097
+  + ''
+    export XDG_DATA_DIRS=${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas.name}:${gtk3}/share/gsettings-schemas/${gtk3.name}:$XDG_DATA_DIRS
   '';
```

I copied this solution from: https://github.com/NixOS/nixpkgs/blob/d986fccd9d8873131ff16eda16a17772e1488a16/pkgs/applications/misc/devdocs-desktop/default.nix#L21 after googling around and then searching for `git grep -C 1000 XDG_DATA_DIRS pkgs/ | grep -i appimage` in nixpkgs.

I've also upgraded to the latest point release.

@srhb please retest :)

**Comment by srhb** [comment]
Looks good!

**Pull request merged**
