### PR TITLE
rust-analyzer: 2020-11-09 -> 2020-12-21

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

New version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC @oxalica @jonringer

### CODE REVIEW

**Comment by oxalica** [comment]
`vscode-extensions.matklad.rust-analyzer` failed to build for me.

```
node_rust-analyzer> > tsc && rollup -c
node_rust-analyzer> sh: tsc: command not found
```

Do you forget to update package.json and node-packages simultaneously?
You can reset to master and run `pkgs/development/tools/rust/rust-analyzer/update.sh`, which will update all of them.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107347` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vscode-extensions.matklad.rust-analyzer</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>rust-analyzer</li>
    <li>rust-analyzer-unwrapped</li>
  </ul>
</details>

**Comment by bkchr** [comment]
> `vscode-extensions.matklad.rust-analyzer` failed to build for me.
> 
> ```
> node_rust-analyzer> > tsc && rollup -c
> node_rust-analyzer> sh: tsc: command not found
> ```
> 
> Do you forget to update package.json and node-packages simultaneously?
> You can reset to master and run `pkgs/development/tools/rust/rust-analyzer/update.sh`, which will update all of them.

Ahh did not tried this. I just have seen that the vscode version is too old.

**Comment by SuperSandro2000** [comment]
> Ahh did not tried this. I just have seen that the vscode version is too old.

I would be fine if this would be bumped in this PR.

**Pull request closed without merging**
