### PR TITLE
solc: 0.5.2 -> 0.5.3

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

New release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ivegotasthma** [comment]
I build this using `nix-review`. It seems that the hash doesn't match.

```
[asthma@dev:~/work/nixpkgs]$ nix-review pr 54497
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0
pull/54497/head:refs/nix-review/1
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/NixOS/nixpkgs
+ 3a99772d07a...be1b20ba93f refs/pull/54497/head -> refs/nix-review/1  (forced
update)
$ git worktree add /home/asthma/.cache/nix-review/pr-54497/nixpkgs
8ee43e01fad4dc7578a99e8db0a02a5d62054f82
Preparing worktree (detached HEAD 8ee43e01fad)
Checking out files: 100% (18063/18063), done.
HEAD is now at 8ee43e01fad linux: 4.9.151 -> 4.9.152
$ git merge --no-commit be1b20ba93f3dfa643bf09e3979d35f9fc0464ed
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --max-jobs 4 --option build-use-sandbox
true -f /home/asthma/.cache/nix-review/pr-54497/build.nix
fixed-output derivation produced path
'/nix/store/yqsgrbwqglb46bj3zmrryspqqvvqj36z-source' with sha256 hash
'009kjyb3r2p64wpdzfcmqr9swm5haaixbzvsbw1nd4wipwbp66y0' instead of the expected
hash '1jq41pd3nj534cricy1nq6wgk4wlwg239387n785aswpwd705jbb'
cannot build derivation
'/nix/store/9ir2xb05sw42a32xfqr4sk1hb2bibdrs-solc-0.5.3.drv': 1 dependencies
couldn't be built
cannot build derivation
'/nix/store/kpbi3ly02x63l4izxicwmn0a3ii34x6c-python3.7-slither-analyzer-0.3.0.drv':
1 dependencies couldn't be built
cannot build derivation '/nix/store/ssms918830ly7w2gs0sh2xdqqvia4y6i-env.drv':
2 dependencies couldn't be built
[0 built (1 failed), 22 copied (294.0 MiB), 45.9 MiB DL]
error: build of '/nix/store/ssms918830ly7w2gs0sh2xdqqvia4y6i-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/54497
2 package failed to build:
slither-analyzer solc

No packages were successfully build, skip nix-shell
$ git worktree prune

 [asthma@dev:~/work/nixpkgs]$
```

**Comment by asymmetric** [comment]
Which hash specifically?

```
❯ nix-prefetch-github ethereum solidity --rev v0.5.3
{
    "owner": "ethereum",
    "repo": "solidity",
    "rev": "v0.5.3",
    "sha256": "1jq41pd3nj534cricy1nq6wgk4wlwg239387n785aswpwd705jbb"
}
```

Not sure why it's trying to build `slither-analyzer` either. Maybe cause I'm the maintainer?

**Comment by asymmetric** [comment]
@ivegotasthma you were right, the `rev` hadn't been updated, force-pushed.

**Comment by asymmetric** [comment]
cc @akru @lionello

**Comment by lionello** [comment]
LGTM

**Pull request merged**
