### PR TITLE
coreutils: 8.29 -> 8.30

### PR DESCRIPTION
**Pull request by dtzWill**
http://savannah.gnu.org/forum/forum.php?forum_id=9187

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Whoops, tests fail on x86_64-unknown-linux-gnu (and perhaps others?).

**Comment by dtzWill** [comment]
Bah, anyone know what's going on with `env-S.pl`?

**Comment by xeji** [comment]
> Bah, anyone know what's going on with env-S.pl?

Not yet but I just found out that the tests pass with sandboxing disabled, so at least we have a hint what to look for.

**Comment by xeji** [comment]
The `env -S` option and  corresponding `env-S.pl` test were newly added in coreultils 8.30.

**Comment by xeji** [comment]
@vcunat does it build now?

**Comment by vcunat** [comment]
Yes, I disabled the test.

**Comment by vcunat** [comment]
Eww, but it broke generation of new stdenv bootstrap tools :-/

**Comment by xeji** [comment]
let's revert, this is too risky one day before branch-off

**Comment by vcunat** [comment]
Staging has no chance to get to master that fast anyway.

**Pull request merged**
