### PR TITLE
thrift: fix build

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Fixes the build of `thrift` (and `pycassa`) by specifying proper constraints and adding missing dependencies.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
Although I can't reproduce the issue in the manual example with `list_keyspaces` with a local `cassandra` instance, I guess it's better to not break the constraint then. Should we simply override `thrift` in the `pycassa` expression accordingly?

**Comment by worldofpeace** [comment]
> Although I can't reproduce the issue in the manual example with `list_keyspaces` with a local `cassandra` instance, I guess it's better to not break the constraint then. Should we simply override `thrift` in the `pycassa` expression accordingly?

I think we should do that, though there's usually not much else we can do with these kind of issues.

**Comment by Ma27** [comment]
@worldofpeace fixed and tested with a local cassandra instance. Anything else to add? :)

**Comment by worldofpeace** [comment]
> @worldofpeace fixed and tested with a local cassandra instance. Anything else to add? :)

Nope, looks great. Built it locally with success.

**Pull request merged**
