### PR TITLE
ocamlPackages.torch: init at 0.8

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [NA] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [NA] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bcdarwin** [comment]
@grahamcofborg build ocamlPackages.torch

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 87447` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
<br>- linuxPackages_4_9.sysdig
<br>- linuxPackages_hardkernel_4_14.nvidia_x11_legacy390
<br>- linuxPackages_hardkernel_4_14.nvidiabl
<br>- php73Extensions.zmq
<br>- php74Extensions.pcs
<br>- php74Extensions.zmq
<br>- python37Packages.pyblock
</details>
<details>
  <summary>1 package built:</summary>
<br>- ocamlPackages.torch
</details>

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 87447` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages marked as broken and skipped:</summary>
<br>- digitalbitbox
<br>- gdata-sharp
<br>- glibcCross
<br>- iterm2
<br>- linuxPackages_4_4.evdi
<br>- linuxPackages_hardkernel_4_14.bcc
<br>- linuxPackages_hardkernel_4_14.bpftrace
<br>- linuxPackages_hardkernel_4_14.can-isotp
<br>- linuxPackages_hardkernel_4_14.chipsec
<br>- linuxPackages_hardkernel_4_14.digimend
<br>- linuxPackages_hardkernel_4_14.evdi
<br>- linuxPackages_hardkernel_4_14.mba6x_bl
<br>- linuxPackages_hardkernel_4_14.nvidia_x11
<br>- linuxPackages_hardkernel_4_14.nvidia_x11_legacy390
<br>- linuxPackages_hardkernel_4_14.nvidiabl
<br>- newlibCross
<br>- nix-linter
<br>- octave-jit
<br>- php73Extensions.pcs
<br>- php74Extensions.pcs
<br>- php74Extensions.pthreads
<br>- php74Extensions.zmq
<br>- python27Packages.caffe
<br>- python27Packages.flitBuildHook
<br>- python27Packages.libmodulemd
<br>- python38Packages.libselinux
</details>
<details>
  <summary>1 package built:</summary>
<br>- ocamlPackages.torch
</details>

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 87447` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
<br>- linuxPackages_hardkernel_4_14.nvidia_x11
<br>- linuxPackages_hardkernel_4_14.nvidiabl
<br>- php72Packages.phpmd
<br>- php73Extensions.pcs
<br>- php74Extensions.pcs
<br>- python38Packages.notify
<br>- python38Packages.pyblock
</details>
<details>
  <summary>1 package built:</summary>
<br>- ocamlPackages.torch
</details>

**Review by bhipple — APPROVED** [review]

**Pull request merged**
