### PR TITLE
[21.11] php81: init at 8.1.6

### PR DESCRIPTION
**Pull request by urandom2**
###### Description of changes

Backport #149584, #147411, #156179, #161038, #164576, #168514, and #172814 to release-21.11. We have multiple attributes for different majors, so this is technically a new package that can be backported.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arianvp** [comment]
Please see https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging for changing base branches without mass-notifying everyone

**Comment by arnottcr** [comment]
terribly sorry for the noise, I submitted this without changing the target branch, so it defaulted to master. I corrected it as soon as possible, but the bots beat me to it. Is there anything else i can do in the future?

**Comment by talyz** [comment]
The APCu extension tests fail. Can you try backporting the update to 5.1.21?

**Comment by arnottcr** [comment]
fyi @Ma27, this one goes with the nextcloud change, #173094, but no rush

**Review by drupol — APPROVED** [review]

**Comment by arnottcr** [comment]
sorry for trying to shoe horn 01af290983978131b957f521dce4159c581652f1 in, something is falling out in adding the `php81` lines to `nextcloud.nix`, but that is out of scope for this change, so I will open up another.

**Pull request merged**
