### PR TITLE
Revert "logseq: Fix publishing graph"

### PR DESCRIPTION
**Pull request by kilianar**
###### Description of changes
This reverts commit 7db6808335f5307f94f0f49d73669e565f526f46.

Revert the changes introduced in #205057 (as requested in https://github.com/NixOS/nixpkgs/issues/218471#issuecomment-1447688562) because they caused some issues (#218471, #217320).

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LoveIsGrief** [comment]
Thanks! I had a quick look (am on my phone). Will run it when I'm on my computer to verify it works and fixes opening links.

I might also have the right to merge it, but that would be new.

**Comment by LoveIsGrief** [comment]
Works for me and #6880 is broken again (as expected). I can't merge it, but hopefully somebody else can.

**Comment by weihua-lu** [comment]
> Works for me and [logseq/logseq#6880](https://github.com/logseq/logseq/issues/6880) is broken again (as expected). I can't merge it, but hopefully somebody else can.

@LoveIsGrief Would you like to take over as the maintainer this case? I barely touch Logseq these days and am going to retire this github account soon.

**Review by ghost — APPROVED** [review]

**Comment by LoveIsGrief** [comment]
Funny, I can close the PR, but not merge it... Dunno if adding myself as a maintainer would change that.

@kilianar maybe try sharing this PR on https://discourse.nixos.org/t/prs-already-reviewed/2617 as I don't think I'll be able to merge.

**Comment by AndersonTorres** [comment]
Why a ghost approved this?

**Comment by LoveIsGrief** [comment]
That used to be the maintainer. He quit.

**Comment by SuperSandro2000** [comment]
> Funny, I can close the PR, but not merge it... Dunno if adding myself as a maintainer would change that. I wonder what the point of being a package maintainer is if one cannot merge PRs related to the package 🤷

This is normal when you do not have permissions to merge. It is really hard to prove that you are only touching your package, so it is not really possible to give every maintainer permissions for their own packages only.

I assume the ghost is the maintainer still in meta.maintainers? If so I am going to drop them treewide.

**Comment by kilianar** [comment]
Yes, the ghost is the GitHub user formerly known as weihua-lu (listed as weihua in `maintainer-list.nix`). `logseq` is the only package for which they are listed as a maintainer.

**Comment by AndersonTorres** [comment]
Remember to remove him.

**Pull request merged**
