### PR TITLE
nixos/nginx: enable service/config reload

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by bjornfor** [comment]
How does config reload work when NixOS always restarts the service if there are config changes?

**Comment by offlinehacker** [comment]
I need this for external config which is auto generated using confd. I'm using this for dynamic reverse proxy on kubernetes.

**Comment by lethalman** [comment]
:+1: it's indeed needed for dynamic config, why not merge directly?

**Comment by bjornfor** [comment]
So you mkForce serviceConfig.ExecStart and pass in /etc/myconfig or something? So that nixos won't automatically restart your service?

**Comment by lethalman** [comment]
@bjornfor just include /etc/nginx/myfile.conf :)

**Comment by bjornfor** [comment]
Ok :-)

**Comment by offlinehacker** [comment]
Yeah, i just include it :)

**Comment by offlinehacker** [comment]
Ok i'm merging this as it does not affect nginx restarts in any way.

**Pull request merged**
