### PR TITLE
vagrant: 2.2.19 -> 2.3.4

### PR DESCRIPTION
**Pull request by jerith666**
required for ruby 3.1 compatibility

three hand-edits to the regenerated gemset.nix were required:

* fix the hashes for google-protobuf and gprc

* remove the 'vagrant' entry

https://github.com/hashicorp/vagrant/compare/v2.2.19...v2.3.4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
So... mark as broken on darwin?

**Comment by jerith666** [comment]
I don't know --  I don't have a darwin machine to test on.  I don't have any reason to believe 2.3.4 would be any more or less broken on darwin than 2.2.19 was, though.

**Comment by wegank** [comment]
2.2.19 actually built on darwin (https://hydra.nixos.org/job/nixpkgs/trunk/vagrant.aarch64-darwin), so the upgrade definitely leads to a regression there.

**Comment by jerith666** [comment]
Okay, sorry, I'm not very practiced at reading the ofborg PR checks.

I found the log at https://logs.ofborg.org/?key=nixos/nixpkgs.228969&attempt_id=4e885d98-2038-4077-832b-3f96f0517818, and I don't know nearly enough about darwin or ruby to make much sense of that.

I just pushed a version that removes `darwin` from `meta.platforms`.  :(

**Comment by wegank** [comment]
> I just pushed a version that removes `darwin` from `meta.platforms`. :(

Nope, please just mark darwin as broken instead. `meta.platforms` is perfectly valid.

**Comment by risicle** [comment]
It's also worth searching for existing PRs before you create one - this is the third attempted bump to vagrant 2.3, the previous two (#219237, #225136) having stalled because of the darwin breakage.

**Comment by jerith666** [comment]
Closing in favor of #225136, which has the most discussion.

**Pull request closed without merging**
