### PR TITLE
nginx: 1.14.2 -> 1.16.0

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update nginxStable and nginxMainline to 1.16.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg build nginx
@GrahamcOfBorg test nginx
cc @Mic92

**Review by tomberek — APPROVED** [review]
builds/runs on Ubuntu. Basic runtime functions look good, but I'd prefer a few more diverse runtime checks by others as well.

**Review by fpletz — APPROVED** [review]
It's fine to merge to master for testing. We should probably also set `nginxMainline` to this version since there probably were some fixes for the final stable version.

**Comment by Izorkin** [comment]
Add update nginxMainline to 1.16.0
@GrahamcOfBorg build nginx
@GrahamcOfBorg test nginx

**Comment by fpletz** [comment]
Thanks! :+1:

**Pull request merged**
