### PR TITLE
feishin: 0.10.1 -> 0.11.1

### PR DESCRIPTION
**Pull request by jlbribeiro**
**Diff:** https://github.com/jeffvli/feishin/compare/v0.10.1...v0.11.1
**Changelog:**
- https://github.com/jeffvli/feishin/releases/tag/v0.11.0
- https://github.com/jeffvli/feishin/releases/tag/v0.11.1

**Maintainers:** @onny (and @jlbribeiro, me)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eljamm** [comment]
Feishin [v0.11.1](https://github.com/jeffvli/feishin/releases/tag/v0.11.1) is out with mostly UI changes and a subsonic server fix: https://github.com/jeffvli/feishin/compare/v0.11.0...v0.11.1

I've used `0.11.0` for a bit these past days and it seems to be working fine.

**Comment by jlbribeiro** [comment]
@eljamm Thank you for the heads-up! (I had received the notification but hadn't managed to reach my personal laptop.)
Also, thank you for the upvote and feedback; just updated the PR.

Would appreciate if you could give it a test, to ease the reviewing process and to get this landed :)

/cc @onny

**Review by eljamm — COMMENTED** [review]
I don't know how separate update commits are handled by hypra/ofborg, but I think it would be better to squash them since we're essentially updating from `0.10.1` to `0.11.1`.

If this was done to include `diff` and `changelog`, we can perhaps combine them in the message:

```
Diff: https://github.com/jeffvli/feishin/compare/v0.10.1...v0.11.1
Changelog:
- https://github.com/jeffvli/feishin/releases/tag/v0.11.0
- https://github.com/jeffvli/feishin/releases/tag/v0.11.1
```

**Comment by jlbribeiro** [comment]
@eljamm
> I don't know how separate update commits are handled by hypra/ofborg, but I think it would be better to squash them since we're essentially updating from `0.10.1` to `0.11.1`.
>
> If this was done to include diff and changelog, we can perhaps combine them in the message:

Thanks for the suggestion; I've done that in the past ([for this exact package](https://github.com/NixOS/nixpkgs/commit/bd6cce921864449860b6681fdb52df52e4a0cb45)); recently I've been [purposefully](https://github.com/NixOS/nixpkgs/pull/347364) keeping version bumps separate in order to allow users wanting to pin individual versions (when searching for specific versions using websites like [Nixhub.io](https://www.nixhub.io) or [Lazamar](https://lazamar.co.uk/nix-versions/)'s) to be able to do so without resorting to package overrides + overlays - although since "inner" commits will never be the `HEAD` of `nixos-unstable`/`nixpkgs-unstable`/..., it will be unlikely they'll be in public caches (which will cause a local build).

As for
> I don't know how separate update commits are handled by hypra/ofborg

_as far as I'm aware_, having two separate commits pushed at once vs. 1 squashed commit results roughly in the same amount of work.
(that was not the case here because this push was after the first one, but squashing + re-pushing rn would trigger yet another build, with ~the same amount of work as this one. I might be wrong, though.)

With this said, do you find this to be a blocker?
(I've searched for any official recommendations on either direction in the past, and couldn't find any; so I ended up leaning towards keeping all the versions' corresponding hashes in the history. If there's a technical reason this is not recommended, I'll squash from now on.)

**Comment by eljamm** [comment]
Thanks for the explanation @jlbribeiro 

> With this said, do you find this to be a blocker?

No, it's just that I didn't think there was any real use in keeping the intermediate commits before, but doing it for the purpose of pinning versions is certainly a valid point.

> If there's a technical reason this is not recommended, I'll squash from now on.

Personally, I think it's more of a matter of when to do this, as it doesn't always make sense to keep the intermediate versions. For example, I wouldn't imagine somebody choosing to pin `0.11.0` over `0.11.1` as the latter only adds fixes to the former and doesn't break functionality.

That said, I don't think keeping the commits will be a problem.

**Review by eljamm — APPROVED** [review]
Everything seems fine with `0.11.1`.

**Pull request merged**
