### PR TITLE
Revert "i3: add `configFile` to enable cutom configuration locations"

### PR DESCRIPTION
**Pull request by grahamc**
Reverts NixOS/nixpkgs#26983

This was unneeded:

```
  services = {
    xserver = {
      windowManager.i3 = {
        enable = true;
        configFile = ./i3.config;
      };
```

Note, searching for i3 in the options shows this: https://nixos.org/nixos/options.html#i3

cc @Ma27 @bennofs

### CODE REVIEW

**Comment by Ma27** [comment]
I agree with you that we don't need two ways of setting the configuration file for `i3`.

However I'd rather drop the `configFile` option because of the following reasons:

- people using `Nix` without `NixOS` have the possibility to amend the configuration file using `config.nix`
- the change is analogous to the structure of packages like `termite` (optional `configFile` argument, `symlinkJoin` expression)

just my 2 cents...

**Comment by Ma27** [comment]
btw if you agree with this, I'd also open a PR to remove the `i3.configFile` option from the module :-)

**Comment by grahamc** [comment]
I don't agree. Will explain fully in a few hours.

**Comment by grahamc** [comment]
>  people using Nix without NixOS have the possibility to amend the configuration file using config.nix

Users can configure i3 by making a wrapper script which passes `-c`.

> the change is analogous to the structure of packages like termite (optional configFile argument, symlinkJoin expression), so this would be more consistent

I'm not convinced termite is consistent with the rest of nixpkgs. There are a few cases like this, but they are few. Most notable ones embed their config at compile time, making it mandatory. The advantages here, minimal.

I'm a fairly firm -1 on your change, and a hard -1 on removing the nixos option.

One notable huge advantage to something like:

```
  environment.etc."my-i3-config".source = ./myconfig;
  services.xserver.windowManager.i3 = {
    enable = true;
    configFile = "/etc/my-i3-config";
  };
```

is a nixos-rebuild switch can take effect without restarting display-manager, just via `$mod+Shift+p`.

**Comment by Ma27** [comment]
> Users can configure i3 by making a wrapper script which passes `-c`.

well, I did something similar in my change, so we support such a behavior natively ATM :-)

> Most notable ones embed their config at compile time, making it mandatory

this is exactly what I and @bennofs wanted to avoid

> One notable huge advantage to something like [...] is a nixos-rebuild switch can take effect without restarting display-manager, just via `$mod+Shift+p`.

could you elaborate? I'm not 100% sure what you mean with this (AFAIK the `windowManager` session requires a restart when changes were applied, e.g. by a `nixos-rebuild`, right?)

**Comment by grahamc** [comment]
Because i3 is looking at a mutable path, and the config is written to an etc path, a rebuild updates the config in /etc, and mod-shift-p reloads it without a restart.

I reached out to a few other people to get their feeling on this PR, to see if I'm deviating from the norms of nixpkgs. They've all agreed that this PR should be reverted.

NixOS concerns itself primarily with configuration and service management, and nixpkgs users wanting to manage system services should likely look elsewhere (like NixOS :)) for that support.

**Comment by joachifm** [comment]
@Ma27 see `dwm` and `st` for canonical  examples of mandatory compile-time config.

**Comment by Mic92** [comment]
A work-around is to use a wrapper if somebody wants for convenience:

```
(pkgs.writeScriptBin "i3" ''
   #! ${pkgs.stdenv.shell} -e
   exec  "${i3.doc}/bin/i3" -c ${./config}
'')
```

**Comment by Ma27** [comment]
@grahamc @joachifm thanks for the clarification and sorry for the unnecessary change :-)

**Pull request merged**
