### PR TITLE
go_1_15: 1.15.8 -> 1.15.10, go_1_16: 1.16 -> 1.16.2

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
Version bump, security releases.

https://groups.google.com/g/golang-announce/c/MfiLYjG-RAw/m/zzhWj5jPAQAJ

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mdlayher — APPROVED** [review]
LGTM.

**Comment by SuperSandro2000** [comment]
Do we want to target staging?

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115962` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>go_1_15</li>
<li>go_1_16</li>
</ul>
</details>

**Comment by maxeaubrey** [comment]
> Do we want to target staging?

At least for the last major bump, go went straight into master: https://github.com/NixOS/nixpkgs/pull/113230#issuecomment-782445651

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115962` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>go_1_15</li>
<li>go_1_16</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
go_1_15:
<details>

warning: EvalError
Cannot evaluate attribute ‘go_1_15’ in ‘/nix/store/z4775fy02myl6j3yzz1zw1mss3cjyr8b-nixpkgs’.
</details>
</details>

**Review by rvolosatovs — APPROVED** [review]

**Comment by zowoq** [comment]
Upstream has new releases, 1.16.2 and 1.15.10

**Comment by maxeaubrey** [comment]
Cool, will bump.

**Comment by maxeaubrey** [comment]
Bumped to 1.15.10 and 1.16.2.

**Comment by terinjokes** [comment]
LGTM

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 115962` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>babelfish</li>
    <li>bat-extras.prettybat</li>
    <li>bazel-buildtools</li>
    <li>bazel-gazelle</li>
    <li>bazel-kazel</li>
    <li>bazel-remote</li>
    <li>bazel-watcher</li>
    <li>bazelisk</li>
    <li>bee</li>
    <li>bee-clef</li>
    <li>bee-unstable</li>
    <li>berglas</li>
    <li>bettercap</li>
    <li>brig</li>
    <li>brillo</li>
    <li>brook</li>
    <li>browserpass</li>
    <li>browsh</li>
    <li>caddy</li>
    <li>cadvisor</li>
    <li>captive-browser</li>
    <li>cassowary</li>
    <li>cayley</li>
    <li>certigo</li>
    <li>certmgr</li>
    <li>certmgr-selfsigned</li>
    <li>certstrap</li>
    <li>cri-o</li>
    <li>cri-o-unwrapped</li>
    <li>cri-tools</li>
    <li>crlfuzz</li>
    <li>croc</li>
    <li>crun</li>
    <li>cryptomator</li>
    <li>dapper</li>
    <li>dapr-cli</li>
    <li>dasel</li>
    <li>dashing</li>
    <li>datadog-agent</li>
    <li>datadog-process-agent</li>
    <li>deadcode</li>
    <li>deepsea</li>
    <li>deis</li>
    <li>deisctl</li>
    <li>delve</li>
    <li>demoit</li>
    <li>dep</li>
    <li>dep2nix</li>
    <li>desync</li>
    <li>devd</li>
    <li>dex-oidc</li>
    <li>drive</li>
    <li>drone</li>
    <li>drone-cli</li>
    <li>drone-runner-exec</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]
Set of non-trivial reverse dependencies build without issues. Assorted functionality testing didn't reveal any issues.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 115962` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>bazel-remote</li>
    <li>bazel-watcher</li>
    <li>datadog-agent</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dep2nix</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>babelfish</li>
    <li>bat-extras.prettybat</li>
    <li>bazel-buildtools</li>
    <li>bazel-gazelle</li>
    <li>bazel-kazel</li>
    <li>bazelisk</li>
    <li>bee</li>
    <li>bee-clef</li>
    <li>bee-unstable</li>
    <li>berglas</li>
    <li>bettercap</li>
    <li>brig</li>
    <li>browserpass</li>
    <li>browsh</li>
    <li>caddy</li>
    <li>captive-browser</li>
    <li>cassowary</li>
    <li>cayley</li>
    <li>certigo</li>
    <li>certstrap</li>
    <li>cri-tools</li>
    <li>crlfuzz</li>
    <li>croc</li>
    <li>dapr-cli</li>
    <li>dasel</li>
    <li>dashing</li>
    <li>datadog-process-agent</li>
    <li>deadcode</li>
    <li>deepsea</li>
    <li>deis</li>
    <li>deisctl</li>
    <li>delve</li>
    <li>demoit</li>
    <li>dep</li>
    <li>desync</li>
    <li>devd</li>
    <li>dex-oidc</li>
    <li>drive</li>
    <li>drone</li>
    <li>drone-cli</li>
    <li>drone-runner-exec</li>
  </ul>
</details>

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 115962` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>bazel-remote</li>
    <li>bazel-watcher</li>
    <li>datadog-agent</li>
  </ul>
</details>
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>babelfish</li>
    <li>bat-extras.prettybat</li>
    <li>bazel-buildtools</li>
    <li>bazel-gazelle</li>
    <li>bazel-kazel</li>
    <li>bazelisk</li>
    <li>bee</li>
    <li>bee-clef</li>
    <li>bee-unstable</li>
    <li>berglas</li>
    <li>bettercap</li>
    <li>brig</li>
    <li>browserpass</li>
    <li>browsh</li>
    <li>caddy</li>
    <li>captive-browser</li>
    <li>cassowary</li>
    <li>cayley</li>
    <li>certigo</li>
    <li>certstrap</li>
    <li>cri-tools</li>
    <li>crlfuzz</li>
    <li>croc</li>
    <li>dapr-cli</li>
    <li>dasel</li>
    <li>dashing</li>
    <li>datadog-process-agent</li>
    <li>deadcode</li>
    <li>deepsea</li>
    <li>deis</li>
    <li>deisctl</li>
    <li>delve</li>
    <li>demoit</li>
    <li>dep</li>
    <li>dep2nix</li>
    <li>desync</li>
    <li>devd</li>
    <li>dex-oidc</li>
    <li>drive</li>
    <li>drone</li>
    <li>drone-cli</li>
    <li>drone-runner-exec</li>
  </ul>
</details>

**Comment by tomberek** [comment]
Darwin failures seem to be cases where builder is overloaded with too many jobs.

**Comment by yurrriq** [comment]
I'm not quite sure, but it seems this might have broken my `crossSystem.config = "x86_64-linux-musl"` builds:

```
...
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile, doing nothing
Building Go cmd/dist using /nix/store/zqxddsxd8966icxc5x3iaz6py941r3h1-go-bootstrap/share/go. (go1.16 linux/amd64)
Building Go toolchain1 using /nix/store/zqxddsxd8966icxc5x3iaz6py941r3h1-go-bootstrap/share/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /build/go
Installed commands in /build/go/bin

The binaries expect /build/go to be copied or moved to /nix/store/7wxa60hfzvjsg9nsgndbfkjgmsp1cga6-go-1.16.2-x86_64-linux-musl/share/go
@nix { "action": "setPhase", "phase": "installPhase" }
installing
mv: missing destination file operand after 'bin'
Try 'mv --help' for more information.
```

**Pull request merged**
