### PR TITLE
mesa: 22.2.1 -> 22.2.2

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

> Mesa 22.2.2 is a bug fix release which fixes bugs found since the 22.2.1 release.

More on https://docs.mesa3d.org/relnotes/22.2.2.html

I've also removed some unused args. ~(**EDIT**: Moved it to a different "lint" commit)~

###### Things done

Absolutely nothing.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
The update should be fine.  I have no strong opinion on the lint changes.

**Comment by LunNova** [comment]
IIRC there was some sort of push to move away from with rather than using it more, but I couldn't find a reference for it.

Hard to search for because most fulltext search engines have `with` ignored. :(

Building this to test is taking forever as usual due to other changes in staging that aren't in the cache, so will take a while to report back on that.

**Comment by vcunat** [comment]
Yes, some people prefer to avoid `optional` and use `optionals` everywhere.  I'm not sure how "strong this trend" is.

**Comment by LunNova** [comment]
Finally built, vkcube's working and desktop apps and browsers seem to be working. Launched ffxiv and it runs as far as the title screen, don't have time to test further.

**Comment by PedroHLC** [comment]
I've removed the lint commit, the inconsistencies may hurt my reading, but I'm totally not the right person to judge what style is better.

**Review by LunNova — APPROVED** [review]
Tested some OpenGL apps too and been running this for a few hours so LGTM :rocket:

**Review by nrdxp — APPROVED** [review]

**Pull request merged**
