### PR TITLE
bpf-linker: 0.9.5 -> 0.9.10, and add an option to use Rust LLVM instead of system LLVM

### PR DESCRIPTION
**Pull request by nbdd0121**
Update to 0.9.10. The system-llvm feature is removed, and no-default-features is sufficient for using system-llvm.

However, even with this update, bpf-linker won't work with latest nightly rustc, because rustc is already on LLVM 18, and LLVM 16 is too old to consume the output. The upstream bpf-linker have a feature to use Rust LLVM (enabled by default), so I also added an overridable option to do the same, although I am not sure if it should be on or off by default.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nbdd0121** [comment]
Result of `nixpkgs-review pr 292566` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bpf-linker</li>
  </ul>
</details>

**Comment by nbdd0121** [comment]
ping @NickCao @figsoda

**Comment by NickCao** [comment]
Shall we wait for a new release? They've updated to llvm 18 on master: https://github.com/aya-rs/bpf-linker/blob/1e70f60759e97a10dbcc1158ddf9b08bc8b603be/Cargo.toml#L31

**Comment by nbdd0121** [comment]
It seems that both 0.9.11 and 0.9.12 are tagged but they don't appear in GitHub releases.

**Comment by cpick** [comment]
I've been using the build from [my pull request](https://github.com/NixOS/nixpkgs/pull/324671) which builds `bpf-compiler` 0.9.10 against llvm 18 with rust nightly-2024-07-02 and it's been working well.

**Comment by NickCao** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/328224

**Pull request closed without merging**
