### PR TITLE
melpa: use newer `package-build.el` to work around a breaking change in Emacs 30

### PR DESCRIPTION
**Pull request by leungbk**
package--prepare-dependencies has been renamed in a recent revision of
Emacs 30.

-------

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by leungbk** [comment]
Are we still allowed to target `master` with Elisp updates, or do we now have to target `staging`?

**Comment by AndersonTorres** [comment]
Use staging until we have a less worse idea.

(yes I am still disappointed on this...)

**Comment by leungbk** [comment]
@AndersonTorres OK, done.

**Comment by leungbk** [comment]
I have pushed an additional commit to avoid using patches entirely and instead use the latest upstream `package-build` (which now has the appropriate workaround for Emacs 30).

There have been multiple incompatible changes in upstream `package-build`; I noticed that `package-build--package` will, unlike before, call `package-build-checkout-function` and `package-build-cleanup-function`. I set them both to `ignore` in order to preserve the semantics of what we had before (I assume Nix takes care of both fetching/checkout and cleanup).

I tested briefly by building Emacs 30 with some packages across a couple of revisions of the overlay.

**Comment by Vonfry** [comment]
conflict and duplicate with #276943?

**Pull request closed without merging**
