### PR TITLE
spacevim: fix #110407

### LINKED ISSUE #110407: spacevim: onboarding script errors
**Describe the bug**
Each time spacevim is started, the "startify" onboarding prompt is displayed, followed by an error message.

**To Reproduce**
1. `nix run nixpkgs#spacevim`
2. see prompt
3. press `1` (or `2` or `enter`)
4. script fails to proceed
5. exit (`space` `q` `q`)
6. start over to confirm the bug persists

**Expected behavior**
The prompt should be shown at most once at first startup. Upstream behavior would be to show it once and save `init.toml` in the user's home directory, nixified behavior would be to never show this and get customized configuration information from the derivation.

**Screenshots**
Capture d’écran de 2021-01-21 23-45-20
Capture d’écran de 2021-01-21 23-47-07

**Additional context**

Inspection reveals that the [spacevim derivation](https://github.com/NixOS/nixpkgs/blob/3893d6c6d76ca2b51ef3694a6c0f27dc8eb01ef5/pkgs/applications/editors/spacevim/default.nix#L13) sets `$SPACEVIMDIR` to point to the generated toml *file* instead of a directory containing it. One approach would be to synthesize that directory with a small derivation.

AFAICT `$SPACEVIMDIR` does not host anything else but I could be mistaken. That being said, [upstream says](https://github.com/SpaceVim/SpaceVim/blob/29b3dcc45ec728668b059a50119298300a41f15c/docs/documentation.md#custom-configuration) it gets added to `&runtimepath` ([code](https://github.com/SpaceVim/SpaceVim/blob/71754c14ab7f3371567086800de387fd86f72c62/autoload/SpaceVim/custom.vim#L238)) so this could be used to symlink plugins maybe...?

The error message is
```
Error detected while processing function SpaceVim#custom#autoconfig[6]..<SNR>202_menu[39]..<SNR>42_basic_mode[4]..<SNR>42_write_to_config:
line   11:
E739: Cannot create directory: /nix/store/9z5j460l405caisaw7n4lf0crbjd7pcb-init.toml

```

Also [referenced](https://github.com/NixOS/nixpkgs/pull/93365#issuecomment-742207109) last month.

**Notify maintainers**

@fzakaria 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.91, NixOS, 20.09.20210121.2eaeea7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `""`
 - channels(louis): `""`
 - nixpkgs: `/nix/store/1hc9xw84dnm3dbkvj32nk3g5sy37gcil-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - spacevim
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by bbjubjub2494**
###### Motivation for this change
Fix bug in derivation

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
LGTM, Waiting borg

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113762` at b76056ae run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/5461646efd03e80dbcbc2c46e2ac4a04">spacevim</a></li></li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/applications/editors/spacevim/default.nix:35:15:
```
   |
35 |   patches = [ ./helptags.patch ];
   |               ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/editors/spacevim/default.nix:30:3:
```
   |
30 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/editors/spacevim/default.nix:37:3:
```
   |
37 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by fzakaria — APPROVED** [review]

**Comment by AndersonTorres** [comment]
@lorkeur can you fix the issues raised by the bot?

**Comment by lourkeur** [comment]
> @lourkeur can you fix the issues raised by the bot?

Done.

Can I get some attention on #109983 in return? Thanks!

**Review by fzakaria — APPROVED** [review]
Thank you for your contributions to making spacevim a reality.

**Review by AndersonTorres — APPROVED** [review]

**Pull request merged**
