### PR TITLE
flatpak: Preserve pixbuf path in validate-icon

### PR DESCRIPTION
**Pull request by mat8913**
###### Motivation for this change

Without this, `flatpak-validate-icon` fails on SVG files and I can't build any flatpaks which have SVG icons.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I tested with:

```
$ git checkout 46e1c7f17aafaab18091f8fe04c1586f4ab932af^; nix-build . -A flatpak; ./result/libexec/flatpak-validate-icon --sandbox 16 16 ~/.local/share/flatpak/exports/share/icons/hicolor/symbolic/apps/org.gnome.Boxes-symbolic.svg; echo $?
HEAD is now at 29dc0ba6577 vimPlugins: update (#63119)
/nix/store/5nw27q7hb34a9bd49zdpg44fc8p1kh0k-flatpak-1.2.4
Format not recognized
1
$ git checkout 46e1c7f17aafaab18091f8fe04c1586f4ab932af; nix-build . -A flatpak; ./result/libexec/flatpak-validate-icon --sandbox 16 16 ~/.local/share/flatpak/exports/share/icons/hicolor/symbolic/apps/org.gnome.Boxes-symbolic.svg; echo $?
Previous HEAD position was 29dc0ba6577 vimPlugins: update (#63119)
HEAD is now at 46e1c7f17aa flatpak: Preserve pixbuf path in validate-icon
/nix/store/4a8j3i5k7d0f9skxwwfknsk7czk1ndfv-flatpak-1.2.4
0
```

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Not sure if we should pick it up from environment or wrap it with librsvg, see https://github.com/NixOS/nixpkgs/pull/59665

**Comment by mat8913** [comment]
The environment will have the correct value since it's already set by the wrapper.

```
$ grep GDK_PIXBUF_MODULE_FILE ./result/libexec/flatpak-validate-icon
export GDK_PIXBUF_MODULE_FILE='/nix/store/n26qkqmargjvb1pd0fdjp9qxh38g1zsr-librsvg-2.44.14/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
```

**Comment by jtojnar** [comment]
Cool.

Could you add `librsvg # for flatpak-validate-icon` to `buildInputs` anyway to make the dependency explicit?

**Review by jtojnar — APPROVED** [review]

**Review by hedning — APPROVED** [review]
LGTM

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
