### PR TITLE
Speed up parsing @args.rsp compiler arguments

### PR DESCRIPTION
**Pull request by orivej**
Improves upon #25205.

https://gist.github.com/pbogdan/9d6986bf931b58a70d75e14eb40ee8a1 parsing time is
reduced from one minute to one second.

### CODE REVIEW

**Comment by pbogdan** [comment]
Thank you! I started a build for a Haskell project to test this PR. Being a big rebuild it will likely take a while to complete but will post results once it finishes (unless this gets merged first).

**Comment by pbogdan** [comment]
I seem to be getting a failure building ghc-7.10.3  https://gist.github.com/pbogdan/9f40ebd95cdbbba3e7408ac18c8327a4 😕 Can't debug further right now but looks like something related to treatment of arguments enclosed within escaped quotes.

**Comment by pbogdan** [comment]
I straced the failing command, abbreviated output below:

- strace - https://gist.github.com/pbogdan/f87860a722c88fefb5ef91f02f1f96a5
- generated rsp file - https://gist.github.com/pbogdan/30a17e3e415fe99d2803433bc4a1d97e

My current reading of what's happening is:

1. GHC gets invoked with `"inplace/bin/ghc-stage1" ... -optc-DProjectVersion=\"7.10.3\" ...` meaning `ProjectVersion`  macro should evaluate to  `"7.10.3"` with the quotes included (https://stackoverflow.com/questions/26213071/change-a-string-macro-at-compilation-time)
2. This gets translated to ["-DProjectVersion=\\"7.10.3\\""](https://gist.github.com/pbogdan/30a17e3e415fe99d2803433bc4a1d97e#file-build-failure-rsp-L29) within the generated rsp file.
3. `utils.sh` translates that entry into `-DProjectVersion="7.10.3"` (note lack of escaped quotes).
4. As `RtsUtils.c` uses `ProjectVersion` as a string so it must contain the quotes:

    ```
    static void mkRtsInfoPair(char *key, char *val) {
        /* XXX should check for "s, \s etc in key and val */
        printf(" ,(\"%s\", \"%s\")\n", key, val);
    }
    ....
    void printRtsInfo(void) {
        ...
        mkRtsInfoPair("GHC version",             ProjectVersion);
    ```

    so the compilation fails.

**Comment by orivej** [comment]
Thank you! I had to add `-r` to read, now it should work.

**Comment by pbogdan** [comment]
I have another build running with the updated PR. It's unlikely to finish before I head to bed so might take some time before I can report back.

**Comment by pbogdan** [comment]
The following [test build](https://gist.github.com/pbogdan/60239ec35776f30a32bc8d317872f395) succeeded. Built on top of master @ 90cf4cfabecad2b4e04d1c018f862868bb59b0ca.

The timings for building just the Haskell project once all dependencies are built:

before:

```
real    19m26.297s
user    19m5.064s
sys     1m20.928s
```

after:

```
real    2m16.866s
user    2m50.204s
sys     0m44.228s
```

That's on a project with 13 modules in the library component, 3 executables, a dummy test suite and sizeable dependency footprint.
Test was done in a VM but even on my desktop some of the rsp files involved would take close to 3 minutes to parse which is now down to 2.5s 😄

**Comment by domenkozar** [comment]
I don't know how many times the wrapper is called, but it's still in almost two orders of magnitude slower than in release-17.03 branch (using the above gist as a test).

rsp branch:

```
$ time expandResponseParams @blabla.rsp

real    0m0.848s
user    0m0.834s
sys     0m0.012s
```

release-17.03 branch:

```
$ time expandResponseParams @blabla.rsp

real    0m0.019s
user    0m0.018s
sys     0m0.001s

```

**Comment by orivej** [comment]
It certainly is slower than parsing with eval in the release:
```sh
args=$(<"${p:1}")
eval 'for arg in '${args//$/\\$}'; do params+=("$arg"); done'
```
This incorrectly parses some files with '$' and '\'. (Correct parsing is documented [here](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#index-fdump-go-spec). In fact [this](https://github.com/NixOS/nixpkgs/commit/175461e09b4631d87716308431b5f83fb2db396e) workaround fixed some cases and broke the one that I noticed in #25205.)

**Comment by domenkozar** [comment]
I think we should merge this and open an issue to rewrite the parsing in C++.

**Pull request merged**
