### PR TITLE
pdm: 2.19.3 -> 2.22.1, add misilelab to maintainers

### LINKED ISSUE #352669: Update request: pdm 2.19.3 -> 2.20.1
- Package name: pdm
- Latest released version: 2.20.0.post1

- Current version on the unstable channel: 2.19.3
- Current version on the stable/release channel: 2.15.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

@cpcloud @natsukium

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MisileLab**
- resolvelib
  - https://github.com/sarugaku/resolvelib/blob/1.1.0/CHANGELOG.rst
- pdm
  - https://github.com/pdm-project/pdm/releases/tag/2.20.0.post1
  - https://github.com/pdm-project/pdm/releases/tag/2.20.1
  - https://github.com/pdm-project/pdm/releases/tag/2.21.0
  - https://github.com/pdm-project/pdm/releases/tag/2.22.0
  - https://github.com/pdm-project/pdm/releases/tag/2.22.1

## Things done

closes https://github.com/NixOS/nixpkgs/issues/352669 and https://github.com/NixOS/nixpkgs/pull/353056

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by natsukium — CHANGES_REQUESTED** [review]
The resolvelib bump breaks ansible.

**Comment by MisileLab** [comment]
> The resolvelib bump breaks ansible.

maybe we need to add this commit to ansible packge?
https://github.com/ansible/ansible/commit/771f7ad29ca4d259761eaa88673c2e32f6412bbe#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

**Comment by natsukium** [comment]
I don't think we should patch it because we won't be able to update automatically.
Instead, it is better to override resolvelib in pdm. Feel free to take my code from https://github.com/NixOS/nixpkgs/pull/353056 .

**Comment by natsukium** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368557`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
