### PR TITLE
fast-downward: 2019-05-13 -> 19.12, build on darwin, fix runtime issues

### PR DESCRIPTION
**Pull request by purcell**
###### Motivation for this change

This package also builds happily on Darwin.

Update:
- Fixed issue where `fast-downward` program in existing derivation failed on both platforms due to not finding the release directory. Freezing the libexec subdir as the default release dir in `arguments.py` resolves this.
- Updated to latest stable release
- Use upstream's standard "build.py" configuration mechanism instead of working around it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by purcell** [comment]
Hmm, bear with me, testing this a little more first.

**Comment by purcell** [comment]
The existing package is broken even on Linux, in fact:
```
nix run -f '<nixpkgs>'  fast-downward -c fast-downward domain.pddl problem-1.pddl --search "astar(add())"                                                                         /tmp
INFO     Running translator.
Could not find build 'release' at /nix/store/d0xizg2aqqar6g1ls9mjmzj38z67r422-fast-downward-2019-05-13/lib/python3.7/site-packages/builds/release/bin. Please run './build.py release'.
```
I'm having a quick look at fixing this.

**Comment by purcell** [comment]
Fixed now, updated and improved.

**Comment by purcell** [comment]
Also /cc @ocharles, who may well be using this.

**Comment by ocharles** [comment]
I actually had no idea we had this in `nixpkgs`! At work we have our own derivation to build this.

**Comment by purcell** [comment]
> I actually had no idea we had this in `nixpkgs`! At work we have our own derivation to build this.

I'm guessing your own derivation would put `downward` in `$out/bin`, since that's what you're calling directly from the Haskell wrapper. I believe in this one it ends up in libexec.

**Comment by purcell** [comment]
Bump! Nobody seems to have strong feelings either way about this, so I might suggest we err on the side of merging this, since it fixes a concrete pre-existing issue.

**Comment by purcell** [comment]
cc @marsam: this is another PR that's a bit stuck.

**Review by marsam — APPROVED** [review]

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
