### PR TITLE
use consistently user alice for examples

### PR DESCRIPTION
**Pull request by olafklingt**
###### Description of changes

most examples use the user *alice*. some examples use the user *jane*. The aim of this PR is to make consistently use of the user alice.

Please tell me which tests would be needed for this small PR. 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by roberth — APPROVED** [review]
Sorry `jane` ;)

`alice` and `bob` have the benefit of being the default examples in cryptosystems and their names start with the first letters of the alphabet, as opposed to `jane` and `joe`. Furthermore, they are already more common.

Speaking of `joe` though, did you check for that one?

**Comment by olafklingt** [comment]
joe is even less popular than jane :-P ... 
there are some john does

there is one file where i lift jane and joe because it seem that alice and bob are used differently:
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/nginx-auth.nix

**Comment by roberth** [comment]
> there is one file where i lift jane and joe because it seem that alice and bob are used differently:
> https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/nginx-auth.nix

That's weird. Those are passwords. Maybe replace those by some random characters?

**Comment by roberth** [comment]
@ofborg test docker-tools nginx-auth sympa systemd-nspawn

**Comment by roberth** [comment]
Thanks @olafklingt!

**Pull request merged**
