### PR TITLE
kdeFrameworks: 5.37 -> 5.38

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
Nox-review is still running.
@ttuegel 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bkchr** [comment]
nox-review does not reported any errors :)

**Comment by ttuegel** [comment]
If `nox-review` didn't get stuck on an unrelated change, that itself is a small miracle! I'm checking the NixOS tests now.

**Comment by bkchr** [comment]
Yeah, miracles! :D I took quite a lot of time to compile all these dependent packages on my laptop^^ Is there a specific test for the kde frameworks stuff? If yes, how can I run this test locally?

**Comment by ttuegel** [comment]
There is no Frameworks-specific test, but the Plasma tests should exercise the important parts:
```
nix-build nixos/release-combined.nix -A nixos.tests.plasma5.x86_64-linux
```

**Review by ttuegel — APPROVED** [review]

**Comment by bkchr** [comment]
Ahh nice, ty.

**Pull request merged**
