### PR TITLE
ffmpeg: 2.8.5 -> 3.0

### PR DESCRIPTION
**Pull request by andrewrk**
Tested with `nix-build -A ffmpeg`

cc @codyopel @Fuuzetsu

### CODE REVIEW

**Comment by codyopel** [comment]
Just a heads up that there will be a bit of fallout with this ffmpeg update.  3.x introduces numerous API changes.  It still should be the default, but applications such as vlc & mixxx are tied to 2.x  at the moment.  I know there were others I came across, but I don't have a list. However most everything works with 3.x.

**Comment by andrewrk** [comment]
Cody, what do you think about notifying everyone who is a maintainer of a package that breaks with this new version ffmpeg and politely asking them if they would like to A) update and/or fix it, or B) lock in to ffmpeg 2.x?

**Comment by zimbatm** [comment]
As a first step this PR should probably explicitly set all the broken packages by passing `ffmpeg = ffmpeg_2;` and then notify their maintainers. That way they can update their packages at their own pace.

**Comment by andrewrk** [comment]
Good idea. I'll try that nox-review thing.

**Comment by bjornfor** [comment]
Yes, please keep master buildable at all times. I know it is tempting to update first and fix the breakage later... but please don't :-)

**Comment by vcunat** [comment]
I'll test a little and merge to master *without* changing the default for now.

**Comment by Profpatsch** [comment]
Beautiful, thanks!

On a related note: If I’m marked as the maintainer of a package, can I be notified if packages break because of my updates (commits)?

**Comment by vcunat** [comment]
I don't know a way. AFAIK there's a problem to know automatically which change exactly could break a package, as Hydra doesn't evaluate each commit.

**Pull request merged**
