### PR TITLE
calibre: 3.47.1 -> 4.1.0

### PR DESCRIPTION
**Pull request by esclear**
###### Motivation for this change
The calibre ebook management software [has been updated to version 4.1.0](https://calibre-ebook.com/new-in/thirteen).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @domenkozar @pSub @AndersonTorres

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]
LGTM!

**Comment by AndersonTorres** [comment]
Remember me when it reaches 15 days!

**Comment by esclear** [comment]
I got to do some research about calibre's executables.
Some will throw exceptions, since some environment variables are not set (which was already the case before the update), but if one supplies the correct variables, they seem to work properly.

**Comment by ari-becker** [comment]
@esclear anything new?
I'm actively waiting on this because I have a shared library where the calibre on other machines is already updated to 4+, and the database format changed between 3.x and 4.x, so it's keeping me from using calibre on my NixOS machine.
Thanks

**Comment by Lassulus** [comment]
needs rebasing

**Comment by callahad** [comment]
Looks like this has been superseded by https://github.com/NixOS/nixpkgs/pull/77616

Can someone please close this PR?

**Pull request closed without merging**
