### PR TITLE
gitlab: refactor and fix test

### PR DESCRIPTION
**Pull request by globin**
###### Motivation for this change

Fix all the shit.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @flokli @krav

### CODE REVIEW

**Comment by globin** [comment]
@GrahamcOfBorg test gitlab

**Comment by globin** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
Thanks a lot for taking care of this! :tada: 

Test looks good. I also instantiated manually, and tinkered around in the web interface a bit.

Did not yet test cloning via ssh/https (which we could probably do in the test as well, depending on how complex it is to add a test project), but the tests now do something, and don't fail anymore.

GitLab complained I should update from 11.4.3 to 11.4.4: https://about.gitlab.com/2018/11/01/critical-security-release-gitlab-11-dot-4-dot-4-released/ - will do that in a followup PR.

**Comment by flokli** [comment]
@globin Is that necessary to be able to authenticate with the api, to create a dummy project?

I didn't check if and how gitlab itself does this in their integration tests, but I guess that might be useful upstream, too.

**Comment by globin** [comment]
Well to create a project, we'll need to authenticate with the API, I can't see how to create a project otherwise.

**Comment by flokli** [comment]
yes, and the API only seems to support authentication via oauth tokens and personal access tokens, so having a rake task to create these seems to be a sensible thing to do…

**Pull request merged**
