### PR TITLE
cura: Re-enable OpenMP. Fixes #59901.

### LINKED ISSUE #59901: cura: weird non-deterministic corruption of larger meshes
## Issue description

When loading larger STL files, cura sometimes corrupts them in seemingly random ways (every time different, very rarely the import works successfully):

mutilated_benchy1
mutilated_benchy2

This is not just an OpenGL rendering problem, it also affects the sliced output:

sliced_benchy1

For comparison, this is how it should look like:

expected_benchy

 - I cannot reproduce this issue on either ubuntu (with the PPA version of cura) or windows.
 - At first I thought this might be a problem with our OpenBLAS version (e.g. like #50407).  However there are no problems on ubuntu, which uses the same numpy and openblas versions.
 - The larger the STL file, the more likely the problems.  For example I could not succesfully import a larger STL file with 3 million faces at all.  (The same file shows no issues in either ubuntu or windows.)
 - The issue also occurs with 3MF files instead of STL.
 - I can also reproduce the issue with cura 3.6 on the stable channel.

This is the relevant part of the cura log output:
```
2019-04-19 20:31:01,074 - INFO - [Thread-3] STLReader.STLReader.load_file [46]: Using NumPy-STL to load STL data.
/nix/store/wmy9m8lam3ja21khh2yfp3crh4lb6pml-python3.7-uranium-4.0.0/lib/python3.7/site-packages/UM/Mesh/MeshData.py:436: RuntimeWarning: invalid value encountered in true_divide
  n[:, 0] /= l
/nix/store/wmy9m8lam3ja21khh2yfp3crh4lb6pml-python3.7-uranium-4.0.0/lib/python3.7/site-packages/UM/Mesh/MeshData.py:437: RuntimeWarning: invalid value encountered in true_divide
  n[:, 1] /= l
/nix/store/wmy9m8lam3ja21khh2yfp3crh4lb6pml-python3.7-uranium-4.0.0/lib/python3.7/site-packages/UM/Mesh/MeshData.py:438: RuntimeWarning: invalid value encountered in true_divide
  n[:, 2] /= l
2019-04-19 20:31:01,505 - DEBUG - [Thread-3] UM.Mesh.MeshData.calculateNormalsFromVertices [444]: Calculating normals took 0.03203701972961426 seconds
2019-04-19 20:31:01,519 - DEBUG - [Thread-3] STLReader.STLReader._read [97]: Loaded a mesh with 677118 vertices
2019-04-19 20:31:02,156 - DEBUG - [Thread-3] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.635796308517456 seconds. 21245 input vertices. 21245 output vertices.
/nix/store/rxvw3i2kmnjc3yc41xg4xfc0k2sygr2c-python3.7-numpy-1.16.1/lib/python3.7/site-packages/numpy/linalg/linalg.py:2480: RuntimeWarning: overflow encountered in multiply
  s = (x.conj() * x).real
/nix/store/wmy9m8lam3ja21khh2yfp3crh4lb6pml-python3.7-uranium-4.0.0/lib/python3.7/site-packages/UM/Mesh/MeshData.py:333: RuntimeWarning: invalid value encountered in true_divide
  data[:, 0] /= lengths
/nix/store/wmy9m8lam3ja21khh2yfp3crh4lb6pml-python3.7-uranium-4.0.0/lib/python3.7/site-packages/UM/Mesh/MeshData.py:334: RuntimeWarning: invalid value encountered in true_divide
  data[:, 1] /= lengths
/nix/store/wmy9m8lam3ja21khh2yfp3crh4lb6pml-python3.7-uranium-4.0.0/lib/python3.7/site-packages/UM/Mesh/MeshData.py:335: RuntimeWarning: invalid value encountered in true_divide
  data[:, 2] /= lengths
2019-04-19 20:31:02,280 - DEBUG - [Thread-3] UM.FileHandler.ReadFileJob.run [69]: Loading file took 1.2 seconds
```

Compared to ubuntu, the only differences are the `RuntimeWarning` and `Thread-3` (on ubuntu it's `Thread-1`).  The number of imported faces is also the same.

cc @abbradar @orivej 

### Steps to reproduce

1. Download a [benchy](https://www.thingiverse.com/download:1223854).
2. `nix-shell -p cura --run cura`
3. File/Open
4. Look at the corrupted model (you might need to repeat, sometimes it works)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.19, NixOS, 19.09pre174426.acbdaa569f4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(gebner): `""`
 - channels(root): `"nixos-19.09pre174426.acbdaa569f4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/59901#issuecomment-599234731

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gebner** [comment]
I played a bit with it, and I still get corrupted meshes.  This bug typically happens with large files, but unfortunately I can't reproduce it reliable.  Sometimes it works, sometimes it doesn't.  Here is a 150M STL file that triggers it almost every time: https://1drv.ms/u/s!Au1u53SHpLowjGhzY5Npp1DNAW6k?e=LYbvEk

**Comment by nh2** [comment]
>  Sometimes it works, sometimes it doesn't.

@gebner 

1. Statistically how many times do you have to try to get corruption? Just so I know how much time to spend to repro it.
2. Do you need to quit Cura in between?
3. Is there an upstream bug report?

**Comment by nh2** [comment]
Still important, but knowing whether there's an associated upstream bug report would be very useful.

**Comment by gebner** [comment]
> Still important, but knowing whether there's an associated upstream bug report would be very useful.

I'm not aware of any upstream bug about this issue, or even what upstream is in this case:

 - Cura only accepts bugs that are reproducible with their appimage.  And they build openblas without openmp, thereby avoiding this bug.
 - It's possible that the bug is due to how PyQt sets up threads, who knows?
 - The other options are scipy or openblas.  However they likely want a small testcase triggering the bug (i.e. not involving cura).   I simply don't have the time to minimize this in the foreseeable future.

> Statistically how many times do you have to try to get corruption? Just so I know how much time to spend to repro it.

It happens more than 50% of the time, larger meshes are more likely to be corrupted.

> Do you need to quit Cura in between?

No.

**Pull request closed without merging**
