### PR TITLE
nimPackages.pixie: 1.1.3 -> 3.1.2

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Pixie has had API major changes.
https://github.com/treeform/pixie/releases

This break the `hottext` package, but that is broken regardless because `pixie` is broken due to dependency updates (#153221).

There is also a commit here to merge `buildInputs` and `propagagedBuildInputs` in the Nim bulider.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ehmry** [comment]
@Ericson2314 I cannot figure out how to get `propagatedBuildInputs` to be recursively collected for the Nim builder, do you know what I might be missing?

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/nim-packages/build-nim-package/default.nix
https://github.com/ehmry/nixpkgs/blob/pixie/pkgs/development/nim-packages/nim_builder/nim_builder.nim#L100

**Comment by schnusch** [comment]
It seems for `propagatedBuildInputs` `$input/nix-support/propagated-build-inputs` has to be read, see <https://nixos.org/guides/nix-pills/basic-dependencies-and-hooks.html#idm140737319455152>. I don't think [findInputs](https://github.com/NixOS/nixpkgs/blob/2ebeb02a99aab4fc6813fe401e2d375a5c00bc8a/pkgs/stdenv/generic/setup.sh#L379) is doing any work for nim.

I don't know much about nim in general, but the way I understand it the nim_builder points to all the dependencies' source directories in the `config.nims` and bypasses nimble completely, correct? Before I saw that nitter was packaged I tried to hack around nimble with <https://github.com/schnusch/nimble2nix>.

**Comment by ehmry** [comment]
I figured it out, I need to use the `pkgsHostTarget` array to get dependencies.

**Comment by ehmry** [comment]
> I don't know much about nim in general, but the way I understand it the nim_builder points to all the dependencies' source directories in the config.nims and bypasses nimble completely, correct?

Correct, I decided it was more maintainable to re-implement Nimble than to make it work in the sandbox.

**Pull request merged**
