### PR TITLE
nixos/proxmox-image: don't assume virtio0 is using local-lvm storage

### PR DESCRIPTION
**Pull request by alan-strohm**
###### Description of changes

Infer the storage for virtio0 from the qemuConf entry.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alan-strohm** [comment]
@illustris Does this look like a reasonable way to handle proxmox instances without storage named local-lvm?

**Review by Guekka — APPROVED** [review]

**Comment by illustris** [comment]
Thanks! Looks like this should work. I'll verify in a couple of hours.

**Comment by illustris** [comment]
I tried restoring a backup without this patch on a node with ZFS storage. The `local-lvm` line in the config file doesn't seem to cause any issues. I agree that this change ought to be merged anyway, but are you running into any issues that this patch fixes?

**Review by illustris — APPROVED** [review]

**Comment by alan-strohm** [comment]
Did your node also have local-lvm storage?  With 2022.11 I get the following error:

TASK ERROR: command 'set -o pipefail && zstd -q -d -c /var/lib/vz/dump/vzdump-qemu-202-slim.vma.zst | vma extract -v -r /var/tmp/vzdumptmp1192287.fifo - /var/tmp/vzdumptmp1192287' failed: storage 'local-lvm' does not exist

For the command:
qm create 202 --archive /var/lib/vz/dump/vzdump-qemu-202-slim.vma.zst

**Comment by illustris** [comment]
okay, I am able to reproduce the issue now. I was using the UI to restore the backup earlier.

```
root@pve:~# qm create 205 --archive ./vzdump-qemu-nixos-23.05pre-git.vma.zst
restore vma archive: zstd -q -d -c /root/vzdump-qemu-nixos-23.05pre-git.vma.zst | vma extract -v -r /var/tmp/vzdumptmp8564.fifo - /var/tmp/vzdumptmp8564
CFG: size: 289 name: qemu-server.conf
DEV: dev_id=1 size: 2591031296 devname: drive-virtio0
CTIME: Sun Apr  2 03:53:35 2023
error before or during data restore, some or all disks were not completely restored. VM 205 state is NOT cleaned up.
command 'set -o pipefail && zstd -q -d -c /root/vzdump-qemu-nixos-23.05pre-git.vma.zst | vma extract -v -r /var/tmp/vzdumptmp8564.fifo - /var/tmp/vzdumptmp8564' failed: storage 'local-lvm' does not exist
```
Passing storage explicitly works
```
root@pve:~# qm create 206 --archive ./vzdump-qemu-nixos-23.05pre-git.vma.zst --storage local-zfs
restore vma archive: zstd -q -d -c /root/vzdump-qemu-nixos-23.05pre-git.vma.zst | vma extract -v -r /var/tmp/vzdumptmp8675.fifo - /var/tmp/vzdumptmp8675
CFG: size: 289 name: qemu-server.conf
DEV: dev_id=1 size: 2591031296 devname: drive-virtio0
CTIME: Sun Apr  2 03:53:35 2023
new volume ID is 'local-zfs:vm-206-disk-0'
map 'drive-virtio0' to '/dev/zvol/rpool/data/vm-206-disk-0' (write zeros = 0)
progress 1% (read 25952256 bytes, duration 1 sec)
progress 2% (read 51838976 bytes, duration 1 sec)
```

**Comment by alan-strohm** [comment]
Oh, perfect.   That means I don't need this.  Do you think it's still worth committing or does it just complicate things?

**Comment by illustris** [comment]
Yes, this patch is definitely worth applying. If you know for sure that you'rebuilding the image for a target that only has zfs or xfs, this will make restoring the backup a little more convenient.

**Pull request merged**
