### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Need to push the CPython updates here as well.

**Comment by flokli** [comment]
It seems the sqlalchemy test is broken in here:

```
FAILED test/dialect/mssql/test_engine.py::ParseConnectTest::test_pyodbc_extra_connect_azure
========== 1 failed, 10256 passed, 1156 skipped in 435.61s (0:07:15) ===========
builder for '/nix/store/10p9ni3gc9ccnygfxaxcw1xi9349wq5s-python3.8-SQLAlchemy-1.3.20.drv' failed with exit code 1
cannot build derivation '/nix/store/7s9kqmaq1sb5rbrc2gsrys2q637mr7qa-python3.8-factory_boy-3.2.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2kjdlbarj89h3mrr7i1nq3lkfcibwm1w-python3.8-pytest-randomly-3.5.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/72lm08l962frmw53cnb49jpcrarcf56a-python3.8-fonttools-4.20.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rjv9npxhhlx5j2hjgglp9zsfbzczfvrg-liberation-fonts-2.1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/c1rd7lf9f0yb70nfy1m4hksz1i4smzg3-python3-3.8.8-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xxkdfydrzpvb7g1brwwiil4s3icig0wg-fc-00-nixos-cache.conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/297kckfjz43q4a1kynsalwz6ciaskvvy-xserver.conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/adq4f1gw1c2azddq16d8zfrqsg9vb8ca-fontconfig-conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xv8vkqhg5ni71h9psrw8kvgsmpcrra3i-xserver-wrapper.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zy1ivk39zy2g8xsmqwnfd7i4w6wvpdbz-fontconfig-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xzvvzzr0kmx1rfz5pgki01bpsd1zmwvn-lightdm.conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hhsp1n97yrg1zdxaz1s2l281by07z8sc-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/b1cl3mays2ci3rq234j11i3m6dgqh3ap-nixos-system-machine-21.05.git.62f8f3674ea.drv': 1 dependencies couldn't be built
```

**Comment by flokli** [comment]
The sqlalchemy issue seems to be fixed.

**Comment by r-burns** [comment]
The libcdr issue on darwin has an upstream fix: https://cgit.freedesktop.org/libreoffice/libcdr/commit/?id=bf3e7f3bbc414d4341cf1420c99293debf1bd894

**Comment by FRidh** [comment]
- pytest-timeout blocks https://hydra.nixos.org/build/137344189 and fails many other jobs
- tarball fails because of an eval error https://hydra.nixos.org/build/137507384

**Comment by FRidh** [comment]
Accidentally pushed python-unstable to staging-next :(

**Comment by FRidh** [comment]
Merged staging-next before this push (c456a25) into master. `pytest-timeout` still needs fixing, but that can be done on master.

**Comment by FRidh** [comment]
`python-unstable` was almost done and meant for the next iteration anyway, along with staging, so that's fine

**Pull request closed without merging**
