### PR TITLE
nixos/restic: fix static paths when not using dynamic parts

### PR DESCRIPTION
**Pull request by pks-t**
## Description of changes

When all of the following conditions are true:

    - `backup.initialize` is not true, so the backup repository shall
      not be initialized.

    - `backup.dynamicFilesFrom` is unset, so that we only back up static
      paths.

    - `backup.backupPrepareCommand` is unset, so that there is no
      preparatory logic.

Then we won't use a pre-start command in the generated Restic service
unit at all. This results in a bug though in case the backup is only
configured to use static paths, because the pre-start command is also
used to write the static paths into a temporary file that Restic will
then use via `--files-from=/run/restic-backups-name/includes`. The
result is that the service will fail:

```
systemd[1]: Starting restic-backups-name.service...
restic[1181]: open /run/restic-backups-name/includes: no such file or directory
systemd[1]: restic-backups-name.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: restic-backups-name.service: Failed with result 'exit-code'.
systemd[1]: Failed to start restic-backups-name.service.
```

Fix this bug by using the static paths file written to the Nix store
directly in case we're not using dynamic paths. Add a test to verify
that this works.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pbsds** [comment]
related? #264882

**Comment by robryk** [comment]
> related?

Yes.

Please note that this PR would silently break the functionality of providing both dynamic and static paths.

**Comment by pks-t** [comment]
On Wed, Nov 01, 2023 at 02:11:53PM -0700, Robert Obryk wrote:
> > related?
> 
> Yes.
> 
> Please note that this PR would silently break the functionality of
> providing both dynamic and static paths.

Does it? I think it shouldn't, as we now conditionally either:

    - Use the static file from the Nix store in case no dynamic paths
      are requested.

    - Or we keep on concatenating both static and dynamic paths to the
      temporary file in case they have been requested. 

I thought the testcase for "remote-from-file-backup" would exercise this
logic, as it has both static and dynamic paths configured. But I realize
that we only verify whether that job produces a snapshot, we don't
verify that the created snapshot contains all expected paths.

I'll amend that testcase to verify that things do continue to work
alright once I get to it.

**Comment by robryk** [comment]
I was wrong and edited the comment.

Patrick Steinhardt ***@***.***> schrieb am Do., 2. Nov. 2023,
12:59:

**Comment by pks-t** [comment]
> I was wrong and edited the comment.

@robryk Ah, didn't see the edit.

> I'll amend that testcase to verify that things do continue to work
> alright once I get to it.

I also had a second look at the test, and we do indeed already verify that both static and dynamic paths end up in the backup. So nothing to amend there.

> Still, I prefer my version, because it makes for fewer different variants of how the paths can get passed in (the code paths for paths = foo; and paths = foo; dynamicFilesFrom = "${pkgs.coreutils}/bin/true"; are very similar).

True. Mine has the benefit that there is no need for a pre-command though. Whether that is worth the additional complexity... dunno. I ultimately don't mind much which of both PRs gets accepted.

**Comment by pbsds** [comment]
I'm leaning towards robryks fix due to the lower complexity in terms of code paths. My domain knowledge may be lacking, but could the added tests from both PRs be merged?

**Comment by pks-t** [comment]
I'm closing this MR as https://github.com/NixOS/nixpkgs/pull/264882 has been merged.

**Pull request closed without merging**
