### PR TITLE
python311Packages.huggingface-hub: 0.20.2 -> 0.20.3

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog `huggingface-hub`: https://github.com/huggingface/huggingface_hub/releases/tag/v0.20.3
cc @kira-bruneau 

Changelog `huggingface-hub`: https://github.com/huggingface/transformers/releases/tag/v4.37.0
cc @pashashocky @happysalada 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
I've got a nixpkgs running and so far I have 10 failures that seem unrelated
```
├─ ⏸ python3.11-spacy-transformers-1.3.4
┃    │  ┌─ ⚠ python3.11-flax-0.7.5 failed with exit code 1 after ⏱ 6s in pythonRuntimeD…
┃    ├─ ⏸ python3.11-dalle-mini-0.1.5
┃    │  ┌─ ⚠ python3.11-sudachidict-core-20230927 failed with exit code 1 after ⏱ 14s i…
┃    ├─ ⏸ python3.11-sudachipy-0.6.7
┃    ├─ ⚠ tts-0.20.2 failed with exit code 1 after ⏱ 8s in pythonRuntimeDepsCheckHook
┃    ├─ ⏵ python3.11-shap-0.43.0 (pytestCheckPhase) ⏱ 1h28m26s
┃    ├─ ⚠ rclip-1.7.6 failed with exit code 1 after ⏱ 0s in pythonRuntimeDepsCheckHook
┃    ├─ ⚠ python3.11-libretranslate-1.5.2 failed with exit code 1 after ⏱ 1s in patchPh…
┃    ├─ ⚠ wyoming-faster-whisper-1.0.2 failed with exit code 1 after ⏱ 3s in pythonRunt…
┃    ├─ ⚠ khoj-1.0.1 failed with exit code 1 after ⏱ 3s in pythonRuntimeDepsCheckHook
┃    ├─ ⚠ python3.11-cleanlab-2.5.0 failed with exit code 2 after ⏱ 30s in pytestCheckP
```
the runtimedepscheck is failures because of multiple outdated depedencies.

my review appears to be stuck on shap pytestCheckPhase.

**Comment by GaetanLepage** [comment]
> my review appears to be stuck on shap pytestCheckPhase.

Yes, stuck on `shap` as well...

**Comment by happysalada** [comment]
I'm personally fine with merging this. I'm going to leave it open for a few more days to give people time to have a look, just in case.

**Comment by GaetanLepage** [comment]
> I'm personally fine with merging this. I'm going to leave it open for a few more days to give people time to have a look, just in case.

Yes, there is nothing amazing in this update. I would be very surprised if it would break anything.

**Pull request merged**
