### PR TITLE
electron: support v29 binary option

### PR DESCRIPTION
**Pull request by mattpolzin**
## Description of changes

Add binary support for newest Electron version. Electron binary support is important for Darwin systems currently.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mattpolzin** [comment]
I built and tested this on both Darwin architectures by way of Bruno which requires Electron and happens to be part of my current nix-darwin.

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 296218` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>drawio</li>
    <li>electron</li>
    <li>freetube</li>
    <li>nix-tour</li>
    <li>pritunl-client</li>
    <li>r2modman</li>
    <li>uivonim</li>
    <li>vieb</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

The failing package (`podman-desktop`) already failed to build just prior to the introduction of Electron v29, so that failure is unrelated to the update.

**Comment by mattpolzin** [comment]
@yu-re-ka would you be interested in reviewing this PR?

**Review by yu-re-ka — DISMISSED** [review]
The latest version is [29.1.4](https://releases.electronjs.org/release/v29.1.4) not 29.0.0

**Comment by mattpolzin** [comment]
> The latest version is 29.1.4

Ah, thanks!

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 296218` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>drawio</li>
    <li>electron</li>
    <li>freetube</li>
    <li>nix-tour</li>
    <li>pritunl-client</li>
    <li>r2modman</li>
    <li>uivonim</li>
    <li>vieb</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Pull request merged**
