### PR TITLE
 gitlab-runner: 11.11.2 -> 12.0.2

### PR DESCRIPTION
**Pull request by bachp**
###### Motivation for this change

Update to latest version: https://gitlab.com/gitlab-org/gitlab-runner/blob/v12.0.0/CHANGELOG.md

The major version bump is not a significant change from the runners perspective.

The removed config options were not used in the nix module so there is no change to the service required.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`$ nix-review pr 63771` passed on NixOS
Diff LGTM

```
[5 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/63771
1 package were build:
gitlab-runner
```

**Comment by bachp** [comment]
12.0.1 was released with a fix for a submodule fetch issue

**Comment by bachp** [comment]
@Infinisil ping

**Comment by bachp** [comment]
@fpletz can you merge this? I'm using it since almost a week without issue.

**Comment by max-wittig** [comment]
@fpletz @Infinisil What's the status here?

**Comment by bachp** [comment]
12.0.2 was released and includes a fix for a concurrent update issue: https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/1447

**Comment by max-wittig** [comment]
@flokli Can you help here?

**Comment by flokli** [comment]
Vacation-induced slackness, sorry for the delay ;-)

LGTM, merging.

**Comment by flokli** [comment]
Backported to 19.03 in d10e680168d8b27b7ef5605926507b9bb1735211.

**Comment by max-wittig** [comment]
Thanks :+1:

**Pull request merged**
