### PR TITLE
vala: 0.36, 0.38 and 0.40 update point releases

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Regular updates and drop packages no longer in use.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
I think we have decided to provide the versions supported by upstream (last three) but cannot find the discussion now.

**Comment by jtojnar** [comment]
I think we have decided to provide the versions supported by upstream (last three) but cannot find the discussion now.

**Comment by jtojnar** [comment]
I think we have decided to provide the versions supported by upstream (last three) but cannot find the discussion now.

**Comment by xeji** [comment]
@GrahamcOfBorg  build vala_0_36 vala_0_40

**Pull request merged**
