### PR TITLE
galaxy-buds-client: 4.5.4 -> 5.1.0

### LINKED ISSUE #306670: Update request: galaxy-buds-client 4.5.4 → 5.1.0
- Package name: galaxy-buds-client
- Latest released version: 5.1.0

- Current version on the unstable channel: 4.5.4
- Current version on the stable/release channel: 4.5.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Icy-Thought

-----

Note for maintainers: Please tag this issue in your PR.

---
4.6.0 announces macos support, so maybe this package can add darwin

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Icy-Thought**
Resolves #306670 and #306671

###### Changelog

- https://github.com/timschneeb/GalaxyBudsClient/releases/tag/4.6.0
- https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0
- https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.1
- https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.1.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
> Executing dotnetConfigureHook
       >   Determining projects to restore...
       >   Restored /build/source/GalaxyBudsClient.Platform.Linux/GalaxyBudsClient.Platform.Linux.csproj (in 626 ms).
       >   Restored /build/source/ThePBone.BlueZNet/ThePBone.BlueZNet.csproj (in 605 ms).
       >   Restored /build/source/GalaxyBudsClient.Platform/GalaxyBudsClient.Platform.csproj (in 605 ms).
       >   Restored /build/source/ThePBone.MprisClient/ThePBone.MprisClient.csproj (in 605 ms).
       >   Restored /build/source/GalaxyBudsClient.Generators/GalaxyBudsClient.Generators.csproj (in 682 ms).
       > /build/source/GalaxyBudsClient/GalaxyBudsClient.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.linux-x64. No packages exist with this id in source(s): _nix
       >   Failed to restore /build/source/GalaxyBudsClient/GalaxyBudsClient.csproj (in 1.54 sec).
       For full logs, run 'nix log /nix/store/cjgg2aznjh2zswgdf7xwrhsdlk3vr0w4-galaxy-buds-client-5.1.0.drv'.

**Comment by Icy-Thought** [comment]
Alright, dotnet is a bit confusing. Because I am using `nix-build -A galaxy-buds-client` locally and the package builds just fine..

**Comment by khaneliman** [comment]
> Alright, dotnet is a bit confusing. Because I am using `nix-build -A galaxy-buds-client` locally and the package builds just fine..

This is the error thrown by the ofborg aarch64-linux check. I haven't looked if it was already broken on aarch64-linux, yet.

**Review by khaneliman — APPROVED** [review]
LGTM, aarch64-linux currently broken so it isn't a new error.

**Comment by Icy-Thought** [comment]
It is! Reason behind that is, I haven't fiddled with darwin since 2010. Apologies for that lack fellas.

**Comment by Icy-Thought** [comment]
Thank you for the quick replies and merger!
Have a nice weekend! :)

**Pull request merged**
