### PR TITLE
dokuwiki: 2023-04-04a -> 2023-04-04b

### PR DESCRIPTION
**Pull request by e1mo**
Fixes an XSS Vulnerability reported in dokuwiki/dokuwiki#4305

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onny** [comment]
Trying to build the tests, it seems that PHP is currently broken 
```
error: builder for '/nix/store/qhz26ig0n0d43xapgjwp2rj1nllfi133-php-simplexml-8.1.29.drv' failed with exit code 2;
       last 10 log lines:
       > ---------------------------------------------------------------------
       > Time taken      :    1 seconds
       > =====================================================================
       >
       > =====================================================================
       > FAILED TEST SUMMARY
       > ---------------------------------------------------------------------
       > Bug #79971 (special character is breaking the path in xml function) [tests/bug79971_1.phpt]
       > =====================================================================
       > make: *** [Makefile:136: test] Error 1
       For full logs, run 'nix log /nix/store/qhz26ig0n0d43xapgjwp2rj1nllfi133-php-simplexml-8.1.29.drv'.
error: builder for '/nix/store/izdn6yzbyjb20dgih5lmvn5b4mvghhwq-php-dom-8.1.29.drv' failed with exit code 2;
       last 10 log lines:
       > Test DOMDocument::loadHTMLFile when the file doesn't exist [tests/DOMDocument_loadHTMLfile_error1.phpt]
       > Test DOMDocument::loadXML() detects not-well formed XML [tests/DOMDocument_loadXML_error2_gte2_12.phpt]
       > Test DOMDocument::load() detects not-well formed [tests/DOMDocument_load_error2_gte2_12.phpt]
       > DOMDocument::relaxNGValidate() should fail on invalid RelaxNG file source [tests/DOMDocument_relaxNGValidate_error2.phpt]
       > DOMDocument::saveHTMLFile() should dump the internal document into a file using HTML formatting [tests/DOMDocument_saveHTMLFile_basic.phpt]
       > DOMDocument::saveHTMLFile() should format output on demand [tests/DOMDocument_saveHTMLFile_formatOutput.phpt]
       > DomDocument::schemaValidate() - non-existent schema file [tests/DOMDocument_schemaValidate_error5.phpt]
       > Test 1: Creating Elements with and without Namespaces [tests/dom_create_element.phpt]
       > =====================================================================
       > make: *** [Makefile:136: test] Error 1
       For full logs, run 'nix log /nix/store/izdn6yzbyjb20dgih5lmvn5b4mvghhwq-php-dom-8.1.29.drv'.
```
Probably already fixed in staging-next?

**Comment by piotrkwiecinski** [comment]
@onny php81 fix is in master.

**Comment by piotrkwiecinski** [comment]
@ofborg test dokuwiki

**Comment by onny** [comment]
@e1mo could you please rebase this PR?

**Comment by e1mo** [comment]
@onny Rebased on master

**Comment by onny** [comment]
Result of `nixpkgs-review pr 332804` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.dokuwiki</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Pull request merged**
