### PR TITLE
amass: init at 2.8.3

### PR DESCRIPTION
**Pull request by kalbasit**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
There seems to be v2.8.3 already on https://github.com/OWASP/Amass/releases
It's not properly tagged on GH but seems like a stable release (already on BlackArch)

**Comment by kalbasit** [comment]
@c0bw3b yes I saw that but v2.8.3 does not compile so I went with the [latest release](
https://github.com/OWASP/Amass/releases) instead of the latest tag.

**Review by c0bw3b — APPROVED** [review]
```shell
$ ./result-bin/bin/amass -version
version 2.8.3

$ ./result-bin/bin/amass -v -ip -brute -min-for-recursive 3 -d somedomain.tld
[...]
OWASP Amass v2.8.3                                https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
44 names discovered - api: 15, scrape: 11, brute: 1, dns: 2, cert: 15
--------------------------------------------------------------------------------
```

Running great. I wondered if we should ship the wordlists with it but it would increase the closure size significantly and by default if `-brute` is passed the tool will just use https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/namelist.txt

**Comment by kalbasit** [comment]
@c0bw3b thx for merging! w.r.t the wordlist, we could write a wrapper around the binary to download the wordlist from master and caches it by the commit hash somewhere in XDG_CACHE? That way we always get the freshest set and the closure size would not increase by more than the wrapper itself.

**Comment by c0bw3b** [comment]
Humm XDG_CACHE_HOME is user-specific and we want to share an identical set of wordlists among users. There is XDG_DATA_DIRS maybe...
But the XDG spec is not ubiquitous and not cross-platform (not followed on Darwin or Windows FWIW).
This is how `restic` deals with this for example: https://github.com/restic/restic/pull/1287

The nix way would really be to install it into `$out/share/amass/`
_Or_ maybe make a multi-output package and install it into `$doc` or something...

**Comment by caffix** [comment]
@c0bw3b Perhaps we can bring that wordlist into the source code

**Comment by c0bw3b** [comment]
Oh hey! nice to see the original author here :) (btw nice tool)

For you upstream I guess it's good to keep the wordlists as separate data. Plus it allows distro packagers to choose whether they want to ship it or not (or just a subset of it).
Our main issue for nixpkgs/nixos is not that is is separate, but more the size it adds if we decide to ship it along with the tool. 

Another random idea: ship the wordlists compressed (.txt.gz) and `zcat` them at runtime? I don't even know if it's even a practical idea in Go. Don't mind me if it's too far-fetched. :p

**Comment by kalbasit** [comment]
@c0bw3b I like the idea of shipping the wordlist gzipped but we will have to send a patch upstream (or maybe @caffix can help us with it) to first un-gzip the file if it ends with `.gz` [here](https://github.com/OWASP/Amass/blob/935e6d5a0b80b1763609373482c0ee1b87bb745a/cmd/amass/main.go#L230-L250).

**Comment by caffix** [comment]
@kalbasit I'd be happy to receive your contribution. Thank you!

**Comment by kalbasit** [comment]
@caffix thx for merging https://github.com/OWASP/Amass/pull/56!

@c0bw3b should I simply put the wordlist under `$out/share` and have the user explicitly find where it is or should I implement a wrapper to always use the wordlist regardless?

**Comment by c0bw3b** [comment]
There is multiple wordlists and I think we should let the user decides when to use one, and which one.
So just install in `$out\share`

You can explain this in `meta.longDescription` so users could be aware of it

**Pull request merged**
