### PR TITLE
php: added argon2 option for php 7.2+

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
The Argon2 algorithm is not enabled in php on NixOS.
I would like this change to be included with 18.09 if possible.

http://php.net/manual/en/password.constants.php
https://bugs.php.net/bug.php?id=76360

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @etu

**Comment by etu** [comment]
@GrahamcOfBorg build php72

**Comment by etu** [comment]
@GrahamcOfBorg build php71

**Comment by etu** [comment]
@Mic92 Looks good to me, I'm fine with backporting this since it's supported by upstream and is in general a good feature. I don't know about other's opinions though.

If you backport this, make sure to not bring the php72 and php71 updates to 7.1.10 and 7.1.22 because of this: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/default.nix#L40-L43

**Comment by etu** [comment]
@aanderse One note though, it would be nice if you can amend the commit message to something like `php: add option to enable argon2`

**Comment by aanderse** [comment]
> 
> 
> @Mic92 Looks good to me, I'm fine with backporting this since it's supported by upstream and is in general a good feature. I don't know about other's opinions though.
> 
> If you backport this, make sure to not bring the php72 and php71 updates to 7.1.10 and 7.1.22 because of this: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/default.nix#L40-L43

Just to be sure, I should be basing this change against the staging-18.09 branch, not the release-18.09 branch?

**Comment by aanderse** [comment]
> 
> 
> @aanderse One note though, it would be nice if you can amend the commit message to something like `php: add option to enable argon2`

OK should be good to go. You're happy to merge?

**Comment by etu** [comment]
@aanderse Now you have three commits instead of one https://github.com/NixOS/nixpkgs/pull/46785/commits

You seem to have keeped your original commit instead of amending it and then causing a merge.

I don't have merge rights, that's why I ping @Mic92 about merging/backporting things. But he can probably sort out your commits as well unless you do it.

**Pull request merged**
