### PR TITLE
codimd: 1.4.0 -> 1.5.0

### PR DESCRIPTION
**Pull request by WilliButz**
###### Motivation for this change
[New release](https://github.com/codimd/server/releases/tag/1.5.0)

###### Things done
Successfully tested everything under /features.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS (x86_64-linux & aarch64-linux)
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WilliButz** [comment]
@GrahamcOfBorg test codimd

**Comment by Ma27** [comment]
The change itself seems fine (especially happy about getting rid of phantomjs), however I can't give explicit approval as I have a pretty poor uplink (vacation, heh ^^) and can't test it (since I'm not that interested in downloading half the internet today).

Feel free to merge, if you want me to test it, you'd have to wait until tuesday evening :)

**Review by Ma27 — APPROVED** [review]
As already mentioned, the diff looks fine to me. Just built and tested locally, also created a simple NixOS container by running ``sudo nixos-container create snens --nixos-path `pwd`/nixos --config-file container.nix --local-address 10.242.1.2 --host-address 10.242.1.1`` with the following config to test CodiMD 1.5 in the browser:

``` nix
{
  services.codimd = {
    enable = true;
    configuration.dbURL = "sqlite:///var/lib/codimd/codimd.db";
    configuration.host = "0.0.0.0"; # just for testing purposes %) 
  };
  networking.firewall.allowedTCPPorts = [ 3000 ];
}
```

Oh and thanks a lot for your patience :D

**Comment by Ma27** [comment]
@WilliButz thanks :tada:

**Pull request merged**
