### PR TITLE
openbazaar: init at 0.14.2

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

This PR adds OpenBazaar - Decentralized Peer to Peer Marketplace for Bitcoin.

Both daemon (openbazaaar) and client (openbazaar-client) are included.

Sadly I was not able to build daemon from source because of broken dependencies on GitHub. :-/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build openbazaar openbazaar-client

**Comment by prusnak** [comment]
Fixed darwin in 731cbde2c044aa71757ea87d6c5f566dfd9f8797

**Comment by prusnak** [comment]
@GrahamcOfBorg build openbazaar openbazaar-client

**Comment by mmahut** [comment]
@GrahamcOfBorg build openbazaar openbazaar-client

**Comment by prusnak** [comment]
@GrahamcOfBorg build openbazaar openbazaar-client

**Pull request merged**
