### PR TITLE
nixosTests.nscd: init, remove nixosTests.resolv

### PR DESCRIPTION
**Pull request by flokli**
nixosTests.systemd is quite heavy, it requires a full graphical system, which is quite a big of a rebuild if the only thing you want to test is whether dynamic users work.

This is now moved to an `nscd` test, which tests various NSS lookups, making extra sure that the nscd path is tested, not the fallback path (by hiding /etc/nsswitch.conf and /etc/hosts for getent).

nixosTests.resolv is removed. It didn't check for reverse lookups, didn't catch nscd breaking halfway in between, and also had an unabiguous reverse lookup - 192.0.2.1 could either reverse lookup to host-ipv4.example.net, or host-dual.example.net.

This also tests unscd, at least the parts that are known to work (see #193535).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by picnoir — APPROVED** [review]

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test nscd

**Comment by NinjaTrappeur** [comment]
Hmm, the `_gateway` hostname resolution seems to fail on aarch64.

**Review by picnoir — CHANGES_REQUESTED** [review]
We have an issue with  AARCH64 don't merge yet.

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test nscd

**Comment by flokli** [comment]
Apparently, the `getent' ahosts _gateway` fails, but only when run via the non-interactive test runner, from the test script, and only on aarch64. :thinking:

**Comment by NinjaTrappeur** [comment]
Okay, it's actually flaky, not always failing.

@GrahamcOfBorg test nscd

**Comment by flokli** [comment]
Running this multiple times exposed it seems to be some flakyness in that lookup call, and it might not be limited to aarch64.

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test nscd

**Review by picnoir — APPROVED** [review]

**Pull request merged**
