### PR TITLE
rocmPackages_5: pin stdenv to GCC 12

### LINKED ISSUE #271943: rocm-runtime is still using gcc, is about to become broken by gcc13
Heads up: even though it tries to `overrideCC` with `clang`, our `rocm-runtime` expression still uses `gcc` for a ton of stuff.

Try changing `default-gcc-version` in `pkgs/top-level/all-packages.nix` to `13` and you'll see the breakage.  I'm about to merge

- https://github.com/NixOS/nixpkgs/pull/268097

which does this, and it's going to break `rocmPackages`.  I tried to fix it, but the problem is very deep: you guys think you're using only clang, but in fact you're not.

Wanted to give you a heads-up.

cc: @lovesegfault @Madouura  @Flakebi

### PR DESCRIPTION
**Pull request by Madouura**
## Description of changes
Lazy fix for the linked issue that I have not tested, as I do not have much time currently.
Only merge once #268097 is merged.

There is a lot more I can do here, there was a ``rocmPackages`` rework I was working on, ~~which I think I accidentally just killed with this branch~~ thankfully github is smart (https://github.com/Madouura/nixpkgs/tree/dev/rocm-rework). Oh well. Any further improvements/nitpicks should go to that, this is just a quick fix.

Fixes: #271943

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@amjoseph-nixpkgs can we just cherry-pick this into your PR?

**Comment by amjoseph-nixpkgs** [comment]
Could you switch the base branch to `staging`?  Since the `gcc13` upgrade is going to `staging` there isn't really any need for this on `master`.

Once my build finishes I'll merge this and rebase https://github.com/NixOS/nixpkgs/pull/268097

**Comment by amjoseph-nixpkgs** [comment]
Thanks, I got build failures in `rocm-llvm-libc` but I think the first commit in this PR fixes it:

- https://github.com/NixOS/nixpkgs/pull/272190

The second commit in that PR might not be necessary; checking that right now.

**Review by ghost — APPROVED** [review]
This is 99% of the solution; the other 1% is in

- https://github.com/NixOS/nixpkgs/pull/272190

**Comment by amjoseph-nixpkgs** [comment]
Will merge as soon as ofborg finishes CI.

**Comment by amjoseph-nixpkgs** [comment]
```
error: builder for '/nix/store/bgj8mchi88pzgs9c24xb0kivlmglfmhp-nix-2.3.17.drv' failed with exit code 2;
       last 10 log lines:
       > ran test tests/gc.sh... [PASS]
       > ran test tests/gc-runtime.sh... [PASS]
       > ran test tests/binary-cache.sh... [PASS]
       > ran test tests/user-envs.sh... [PASS]
       > ran test tests/remote-store.sh... [PASS]
       > ran test tests/lang.sh... [PASS]
       > ran test tests/fixed.sh... [PASS]
       > ran test tests/timeout.sh... [PASS]
       > ran test tests/gc-auto.sh... [PASS]
       > ran test tests/gc-concurrent.sh... [PASS]
       For full logs, run 'nix log /nix/store/bgj8mchi88pzgs9c24xb0kivlmglfmhp-nix-2.3.17.drv'.
```

wat.

**Comment by amjoseph-nixpkgs** [comment]
@ofborg eval

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build

**Comment by amjoseph-nixpkgs** [comment]
Rebased in order to make ofborg re-eval.

**Comment by amjoseph-nixpkgs** [comment]
I have built both of these derivations locally:

```
/nix/store/bgj8mchi88pzgs9c24xb0kivlmglfmhp-nix-2.3.17.drv
/nix/store/c076ydrflsfx4p849f810mmidpzi6yq2-nixpkgs-lib-tests.drv
```

The first derivation is the one that @ofborg choked on.  The second derivation is `eval-lib-tests` for this PR.

Therefore, I am going to merge this.

Good thing we can run CT locally!

**Pull request merged**
