### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by l0b0**
###### Motivation for this change

Enforced by `editorconfig-checker`, resulting in [false positives](https://github.com/NixOS/nixpkgs/runs/4201526554)).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
ci fails. `vanity.sh` is not completely fixed.

**Comment by l0b0** [comment]
> ci fails. `vanity.sh` is not completely fixed.

I left it like that because the "indentation" is inside strings. I've added a separate commit changing that, but it's more risky. We shouldn't really use literal tabs inside Bash scripts in any case; it's really easy to mess up without noticing.

**Comment by roberth** [comment]
SPARQL doesn't seem to be indentation sensitive and it was already using mixed indentation, so this seems to be an improvement. It also isn't a critical script, so both probability and impact are low => lgtm.

**Comment by roberth** [comment]
OfBorg is ok. Staging will [not](https://discourse.nixos.org/t/lets-have-a-great-21-11-release-cycle/15262/8?u=roberth) make it into the release, so no need for extra concern.

**Pull request merged**
