### PR TITLE
mate: 1.20 -> 1.22

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update the [MATE Desktop Environment](https://mate-desktop.org) to version 1.22.

[MATE 1.22 released](https://mate-desktop.org/blog/2019-03-18-mate-1-22-released/)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Infinisil** [comment]
Currently kio-extras fails to build on master (https://hydra.nixos.org/job/nixpkgs/trunk/kdeApplications.kio-extras.x86_64-linux), and `services.xserver.desktopEnvironment.mate.enable` depends on it, so trying to test it with this option enabled fails. Would be a good idea to fix kio-extras.

**Comment by romildo** [comment]
> Currently kio-extras fails to build on master (https://hydra.nixos.org/job/nixpkgs/trunk/kdeApplications.kio-extras.x86_64-linux), and `services.xserver.desktopEnvironment.mate.enable` depends on it, so trying to test it with this option enabled fails. Would be a good idea to fix kio-extras.

I am not seeing how MATE depends on `kio-extras`. What depends on it seems to be `plasma5`.

**Comment by Infinisil** [comment]
Oh, I'm stupid, I used the `demo.nix` profile, which apparently sets `plasma5.enable = true`. Sorry! I'll try again without this.

**Review by infinisil — APPROVED** [review]
Tested this in a VM with `desktopEnvironments.mate.enable = true`, works well :)

**Pull request merged**
