### PR TITLE
gede: 2.6.1 -> 2.10.9

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

reverting to qt 5.9 fixed the build.
cc https://github.com/NixOS/nixpkgs/issues/45960

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build gede

**Comment by xeji** [comment]
This never built on darwin: https://hydra.nixos.org/job/nixpkgs/trunk/gede.x86_64-darwin/all
So please restrict to `platforms.linux` to get rid of another failure :smile:

**Comment by symphorien** [comment]
done :)

**Comment by xeji** [comment]
backported in f391f6fe7331141a06ef631a4e24c9833736d27f

**Pull request merged**
