### PR TITLE
emacs: mark meta.broken if cross

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by adisbladis** [comment]
What aspect of cross compilation is broken?
If it's related to native compilation we should just disable that by default on cross.

**Comment by amjoseph-nixpkgs** [comment]
> What aspect of cross compilation is broken?
> If it's related to native compilation we should just disable that by default on cross.

Unfortunately it isn't just `nativeComp`.

As far as I can tell, nobody has ever been able to make emacs cross-compile without extremely invasive wizardry which would be a maintenance burden for nixpkgs.  The biggest stumbling block is emacs' "dumper", which fundamentally requires executing `hostPlatform` code in order to create the dump image.

Because of this obstacle there are a large number of other cross-compilation bugs in emacs that nobody is motivated to fix.  They are small ones, but because of the dumper problem nobody bothers to work on them.

It's a somewhat depressing situation :(

**Comment by adisbladis** [comment]
> The biggest stumbling block is emacs' "dumper", which fundamentally requires executing hostPlatform code in order to create the dump image.

Right, I didn't think about that.
Marking it as broken is the right call.

**Comment by amjoseph-nixpkgs** [comment]
> The biggest stumbling block is emacs' "dumper", which fundamentally requires executing `hostPlatform` code in order to create the dump image.

In case anybody's curious: gentoo comes closest to cross-compiling emacs, but it still requires the user to run a "finish up the build process" script (which generates the dump) on the `hostPlatform`:

https://gitweb.gentoo.org/repo/gentoo.git/tree/app-editors/emacs/emacs-30.0.9999.ebuild#n532

**Pull request merged**
