### PR TITLE
edgedb: 5.3.0 -> 5.4.1

### LINKED ISSUE #345808: Update request: edgedb 5.3.0 -> 5.4.1
- Package name: edgedb
- Latest released version: 5.4.1

- Current version on the unstable channel: 5.3.0
- Current version on the stable/release channel: 4.1.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

@ahirner @kirillrdy 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jfvillablanca**
## Things done
Closes #345808

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
hashes don't match https://github.com/NixOS/nixpkgs/pull/346876/checks?check_run_id=31139219366

**Comment by jfvillablanca** [comment]
> hashes don't match https://github.com/NixOS/nixpkgs/pull/346876/checks?check_run_id=31139219366

it seems like the hash mismatch happens when building on `aarch64-linux`

what's the course of action here

**Comment by kirillrdy** [comment]
I've tested on two different aarch64-linux machines, and I don't get hash mismatch,

lets try again :shrug: 

@ofborg test edgedb

**Review by kirillrdy — DISMISSED** [review]

**Comment by kirillrdy** [comment]
@jfvillablanca sorry forgot formalities

PR description and commit message should acompany link to release notes and or diff

https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by jfvillablanca** [comment]
> @jfvillablanca sorry forgot formalities
> 
> PR description and commit message should acompany link to release notes and or diff
> 
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

i think upstream for `edgedb-cli` doesn't provide release notes; only the main `edgedb` repo provides one and it's only up to the minor version

**Comment by kirillrdy** [comment]
when no change log available link to diff is usually added something like 648806da1f2eb4e70e9d1d88847c0377722643f0

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 346876` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>edgedb</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
@mattpolzin not sure what is meant by "allowance for the MIT license"

https://github.com/edgedb/edgedb-cli/blob/master/README.md#license does that answer your question ?

**Comment by mattpolzin** [comment]
> https://github.com/edgedb/edgedb-cli/blob/master/README.md#license does that answer your question ?

It does! Thanks. I made the mistake of visiting their homepage, then hitting the GitHub icon, and then noting that the `edgedb/edgedb` repository is only licensed under Apache 2. I failed to notice the derivation was pulling from a different repository under that org.

**Pull request merged**
