### PR TITLE
eask: init at 0.6.43

### PR DESCRIPTION
**Pull request by jcs090218**
###### Description of changes

Alternative to Emacs [Cask](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/cask/default.nix)

Eask is a command-line tool that helps you build, lint, and test Emacs Lisp packages. It creates a clean environment to sandbox your elisp code without influencing your personal configuration.

#### Metadata

homepage URL: https://emacs-eask.github.io/
source URL: https://github.com/emacs-eask/eask
license: GPL3.0
platforms: Unix, Linux, Darwin

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jcs090218** [comment]
Sorry I am new to this community. I wonder how do I progress and move forward with this PR? 😅 

Any suggestions are welcome! 🙏 ❤️

**Review by thiagokokada — CHANGES_REQUESTED** [review]
Unless there is a good reason, we generally prefer Node packages to be added in our monolith Node file. See details on how to use it here: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#adding-and-updating-javascript-packages-in-nixpkgs.

Also, please follow the [Contributing](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) guidelines for formatting your commits.

**Comment by jcs090218** [comment]
> Unless there is a good reason, we generally prefer Node packages to be added in our monolith Node file.

I have few questions,

1. I have planned to use deno in the future (not sure if this affect the decision making)
2. So we simply add it to [pkgs/development/node-packages/node-packages.json](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages.json). Some reference PRs I found:
  - https://github.com/NixOS/nixpkgs/pull/186921
  - https://github.com/NixOS/nixpkgs/pull/172883
3. Should I still add myself as a maintainer?

> Also, please follow the [Contributing](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) guidelines for formatting your commits.

I have tried rebase the previous commits into `1`. Does that work? It might be easier for me to create another PR? 😅 

---

Thank you very much for the review! ❤️ 🙏

**Comment by thiagokokada** [comment]
> I have planned to use deno in the future (not sure if this affect the decision making)

Not sure how packaging Deno is different from Node, but if you switch you should update the package anyway. So this is not reason enough to not use it.

> So we simply add it to [pkgs/development/node-packages/node-packages.json](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages.json). Some reference PRs I found:

You also need to run the script to generate a new lock file and test your changes.

> Should I still add myself as a maintainer?

I don't think we have maintainers for Node packages. You can still add yourself to the maintainer list if you want, but I think it would be strange to have a maintainer in the list not being referenced anywhere.

> I have tried rebase the previous commits into 1. Does that work? It might be easier for me to create another PR? sweat_smile

The commits still looks wrong, now I see 8 separate commits.

Our workflow here in nixpkgs is heavily rebase centric (for PRs, we do merges in `master` branch), so if you plan to contribute in the future this is a good opportunity to learn how to do rebase properly.

But yeah, you can create another PR since you're probably going to change everything. Just keep in mind that you can't run from rebasing forever.

**Comment by jcs090218** [comment]
> Not sure how packaging Deno is different from Node, but if you switch you should update the package anyway. So this is not reason enough to not use our monolith Node.

👌 

> Our workflow here in nixpkgs is heavily rebase centric (for PRs, we do merges in master branch), so if you plan to contribute in the future this is a good opportunity to learn how to do rebase properly.

Thanks for the advice! ❤️ 

> But yeah, you can create another PR since you're probably going to change everything. Just keep in mind that you can't run from rebasing forever.

I have opened up another PR in #189789.

**Pull request closed without merging**
