### PR TITLE
libsigrok: fix c++ bindings

### PR DESCRIPTION
**Pull request by hrhino**
Doxygen and Python are needed as `nativeBuildInputs` (according to this project's `configure`).

Add a tiny `installCheck` for this.

###### Motivation for this change

`pulseview` is broken because of missing C++ headers.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hrhino** [comment]
```
/marvin opt-in
/status needs_reviewer
```

**Comment by hrhino** [comment]
Result of `nixpkgs-review pr 131998` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>libsigrok</li>
    <li>libsigrok_0_3</li>
    <li>pulseview</li>
    <li>sigrok-cli</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131998` at 6a9f8681 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>libsigrok</li>
    <li>libsigrok_0_3</li>
    <li>pulseview</li>
    <li>sigrok-cli</li>
  </ul>
</details>

**Review by bjornfor — APPROVED** [review]

**Comment by hrhino** [comment]
(woops, actually added the `installCheck`)

**Review by bjornfor — APPROVED** [review]

**Comment by eadwu** [comment]
Seems like it still isn't generating?

```bash
shrinking RPATHs of ELF executables and libraries in /nix/store/pylj96k51xz7yhsnxk0zwbq6hdrhv12x-libsigrok-0.3.0
shrinking /nix/store/pylj96k51xz7yhsnxk0zwbq6hdrhv12x-libsigrok-0.3.0/lib/libsigrok.so.2.0.0
strip is /nix/store/hy3lz2vfv9qq2v5jz9nzlx6mmiaq79rj-binutils-2.35.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/pylj96k51xz7yhsnxk0zwbq6hdrhv12x-libsigrok-0.3.0/lib 
patching script interpreter paths in /nix/store/pylj96k51xz7yhsnxk0zwbq6hdrhv12x-libsigrok-0.3.0
checking for references to /build/ in /nix/store/pylj96k51xz7yhsnxk0zwbq6hdrhv12x-libsigrok-0.3.0...
running install tests
C++ bindings were not generated; check configure output
```

**Comment by bjornfor** [comment]
It builds here on tip of master (3473915a71a5b2d2b576742097c5f41b75c60889).

```
$ nix-build -A libsigrok
/nix/store/l0v89igq1m5idis3hgcxvv1mamvgbprs-libsigrok-0.5.1
```

**Comment by hrhino** [comment]
Aaaaaargh there's an older one (0.3) without the bindings. I'll fix the check when I get back. Thanks @eadwu!

**Pull request merged**
