### PR TITLE
nixos/fontconfig: harmonize with penultimate

### PR DESCRIPTION
**Pull request by jtojnar**
Makes the differences easier to spot when diffing

### CODE REVIEW

**Comment by jtojnar** [comment]
```
$ git checkout channels/nixos-unstable
$ git diff --shortstat --no-index nixos/modules/config/fonts/fontconfig{,-penultimate}.nix
 1 file changed, 231 insertions(+), 408 deletions(-)
$ git diff --shortstat --ignore-all-space --no-index nixos/modules/config/fonts/fontconfig{,-penultimate}.nix
 1 file changed, 122 insertions(+), 299 deletions(-)

$ git checkout fontconfig-harmonization
$ git diff --shortstat --no-index nixos/modules/config/fonts/fontconfig{,-penultimate}.nix
 1 file changed, 85 insertions(+), 252 deletions(-)
$ git diff --shortstat --ignore-all-space --no-index nixos/modules/config/fonts/fontconfig{,-penultimate}.nix
 1 file changed, 82 insertions(+), 249 deletions(-)
```

It can be harmonized even more but I am tired of it now.

cc @worldofpeace

**Comment by jtojnar** [comment]
I tried running a system with fontconfig-penultimate and without it and this did not seem to have broken anything.

**Comment by worldofpeace** [comment]
Why is penultimate default, is it defunct?

**Comment by jtojnar** [comment]
No idea.

**Pull request merged**
