### PR TITLE
solaar: unstable -> 1.0.1

### PR DESCRIPTION
**Pull request by ysndr**
###### Motivation for this change

Keep track with the releases that were continued to be [issued](https://github.com/pwr-Solaar/Solaar/releases) by the solaar devs and contain the recent development.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ysndr

### CODE REVIEW

**Comment by ysndr** [comment]
@spinus Do you need to have a look at this?

**Review by spinus — APPROVED** [review]
looks good, thank you for taking care of this @ysndr !

**Comment by spinus** [comment]
@ysndr actually I spot small issue, but it was not in the change so I didn't spot at first. Could you update homepage as well?

**Comment by spinus** [comment]
and potentially commit description should match pattern when you upgrade version. https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

**Comment by ysndr** [comment]
> Could you update homepage as well?
 Yeah totally missed that as well

**Review by spinus — APPROVED** [review]

**Comment by spinus** [comment]
good stuff, cheers

**Comment by bjornfor** [comment]
This needs a rebase.

**Comment by ysndr** [comment]
so finally after struggling with getting my local fork up to date I guess this will work now
@bjornfor / @spinus who is responsible for getting this merged?

**Comment by spinus** [comment]
@ysndr I have no merge writes

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
