### PR TITLE
vim-prosession: add vim plugin

### PR DESCRIPTION
**Pull request by GovanifY**
This adds https://github.com/dhruvasagar/vim-prosession to vimPlugins.

#### Motivation for this change
Wanted better session management in vim which this plugin provides

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ N/A ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ N/A ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ N/A ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by timokau** [comment]
This does not quite fit [Contributing.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). Please revisit the section about commit message formatting. You could also compare with prior commits that have added vim plugins: https://github.com/NixOS/nixpkgs/commits/master/pkgs/misc/vim-plugins/vim-plugin-names

**Review by timokau — CHANGES_REQUESTED** [review]
See comment above. Sorry if it comes over as snarky, it isn't intended that way.

**Comment by GovanifY** [comment]
@timokau it does not come as starky, don't worry! I based myself on this vimPlugins PR https://github.com/NixOS/nixpkgs/pull/69418 but it seems like I took the only one misformatted^^".
Either way the commit message is now changed.

**Review by jonringer — COMMENTED** [review]
diff LGTM
commit LGTM

```
[3 built, 2 copied (32.9 MiB), 6.9 MiB DL]
https://github.com/NixOS/nixpkgs/pull/78656
1 package were built:
vimPlugins.vim-prosession
```

**Comment by timokau** [comment]
Thank  you!

**Pull request merged**
