### PR TITLE
Backport google-chrome and chromium to release-17.03

### PR DESCRIPTION
**Pull request by ryantm**
###### Motivation for this change

Issue #25880 

###### Things done
- built pkgs.google-chrome on NixOS

This probably needs some more testing, and I haven't built chromium with it yet.

### CODE REVIEW

**Comment by ryantm** [comment]
pkgs.chromium built successfully too

**Comment by joachifm** [comment]
cc @bendlas

**Comment by bjornfor** [comment]
Backport commits should be done with "git cherry-pick -x ...", so we know where they come from and that they don't have to be forward ported to master.

**Comment by joachifm** [comment]
Also, how does this relate to https://github.com/NixOS/nixpkgs/pull/28170, if at all?

**Comment by bendlas** [comment]
First off, thanks for taking this on.

The `chromium: add build flags and system libs` commit should not be necessary for a successful build. Since this is going to stable, consider dropping that commit (instead of adding it two times ;-) )

I don't know about `chromium: Allow to put extensions in system path`, but #28170 seems to do without it. Overall, #28170 seems to be more minimal and focussed, which is what we are looking for in stable. Also, it's over a week older.

**Comment by joachifm** [comment]
Per @bendlas's feedback I've merged the older PR instead. If there are any remaining patches that ought to be backported, please do not hesitate to submit them for consideration. Thank you.

**Pull request closed without merging**
