### PR TITLE
briar-desktop: 0.5.0-beta -> 0.6.0-beta

### PR DESCRIPTION
**Pull request by jaki161**
## Description of changes

[https://code.briarproject.org/briar/briar-desktop/-/wikis/Changelog](https://code.briarproject.org/briar/briar-desktop/-/wikis/Changelog)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by BenediktBroich** [comment]
I cant add my phone as a contact. And i do get the following error: 
```
2023-10-13 11:39:45,890 [main] INFO  org.briarproject.briar.desktop.Main - This is briar-desktop version 0.6.0-beta
2023-10-13 11:39:45,892 [main] INFO  org.briarproject.briar.desktop.Main - Build info:
2023-10-13 11:39:45,892 [main] INFO  org.briarproject.briar.desktop.Main -   Git hash 4cfd685a108890a47a100310204f8a9b450e3087
2023-10-13 11:39:45,893 [main] INFO  org.briarproject.briar.desktop.Main -   Commit time 2023-08-31 15:38:18
2023-10-13 11:39:45,893 [main] INFO  org.briarproject.briar.desktop.Main -   Tag 0.6.0-beta
2023-10-13 11:39:48,311 [AWT-EventQueue-0] INFO  o.b.b.d.n.l.LibnotifyNotificationProvider - Notification server capabilities: actions, body, body-markup, icon-static, persistence, sound
2023-10-13 11:39:56,841 [pool-1-thread-3] WARN  o.b.bramble.plugin.PluginManagerImpl - Plugin org.briarproject.bramble.tor did not start
2023-10-13 11:39:56,842 [pool-1-thread-3] WARN  o.b.bramble.plugin.PluginManagerImpl - org.briarproject.bramble.api.plugin.PluginException: java.io.IOException: Cannot run program "/home/bene/.briar/desktop/tor/tor" (in directory "/home/bene/.briar/desktop/tor"): error=2, No such file or directory
org.briarproject.bramble.api.plugin.PluginException: java.io.IOException: Cannot run program "/home/bene/.briar/desktop/tor/tor" (in directory "/home/bene/.briar/desktop/tor"): error=2, No such file or directory
	at org.briarproject.bramble.plugin.tor.TorPlugin.start(TorPlugin.java:204)
	at org.briarproject.bramble.plugin.PluginManagerImpl$PluginStarter.run(PluginManagerImpl.java:232)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.io.IOException: Cannot run program "/home/bene/.briar/desktop/tor/tor" (in directory "/home/bene/.briar/desktop/tor"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.briarproject.onionwrapper.AbstractTorWrapper.start(AbstractTorWrapper.java:156)
	at org.briarproject.onionwrapper.UnixTorWrapper.start(UnixTorWrapper.java:14)
	at org.briarproject.bramble.plugin.tor.TorPlugin.start(TorPlugin.java:198)
	... 4 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 8 common frames omitted
```

**Comment by das-li** [comment]
I can reproduce that. I think @onny should look at this.

**Comment by snowc0de** [comment]
I think it would be a good idea to merge this because the briar 0.5.0-beta is simply blocked and requires an upgrade now.

image

**Comment by s1ls** [comment]
I think this could be merged if meta.broken is set to true

**Comment by onny** [comment]
Result of `nixpkgs-review pr 260649` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>briar-desktop</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Comment by niklaskorz** [comment]
FYI @onny this PR included a merge commit (https://github.com/NixOS/nixpkgs/pull/260649/commits/753c94245e4e3e2c72d759db5d67af3a9bc6571d) and should not have been merged in this state (although now it's far too late to address anyway).

**Pull request merged**
