### PR TITLE
GNOME updates 2024-01-09

### PR DESCRIPTION
**Pull request by bobby285271**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build gnome.rygel mm-common folks libdex gnome.mutter gnome.gnome-shell
@ofborg test gnome gnome-xorg

**Comment by bobby285271** [comment]
@ofborg build gnome.rygel mm-common folks gnome.mutter gnome.gnome-shell
@ofborg test gnome gnome-xorg

**Comment by bobby285271** [comment]
I moved the libdex bump to https://github.com/NixOS/nixpkgs/pull/279847 because the [newly added](https://gitlab.gnome.org/GNOME/libdex/-/commit/659078d1159222330d054b347693f3549efdb703) test is probably [flaky](https://github.com/NixOS/nixpkgs/runs/20304452294).

**Comment by bobby285271** [comment]
@ofborg build folks

**Review by amaxine — APPROVED** [review]
Diff and upstream changes look good to me.

**Comment by amaxine** [comment]
We might want to disable `doCheck` for `folks` again, I'm getting timeouts under busier circumstances than when just building this PR. That, or increasing the timeout multiplier more, I guess?

**Comment by bobby285271** [comment]
> We might want to disable doCheck for folks again

Fine for me.

Is that a specific subtest that stuck? It would be really weird if it randomly stuck at 31/32 as said in https://github.com/NixOS/nixpkgs/commit/3d6f2ec9e800d52c3b82d440c147bf2963803548

**Comment by amaxine** [comment]
No, 6 tests timed out for me on the first run. I'm having trouble reproing again but I can hammer things with a webkit rebuild I guess to try and recreate the conditions again 😅

**Comment by amaxine** [comment]
Disabling checks again for `folks` in #280909.

**Pull request merged**
