### PR TITLE
Rustfmt: 0.9.0 -> 0.99.5

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change
the current version of rustfmt is unable to parse code accepted by our current version of rustc.
Also enable tests in `rustc-bindgen` (they were disabled because our version of rustfmt was too old)

cc @Ralith and @globin as maintainers.
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`): tested `cargo fmt` and `rustfmt`
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by symphorien** [comment]
Ah and I forgot to mention: I know that 1.0 is released, but our rustc is not nightly enough to build this version. I packaged the latest version I could.

**Comment by symphorien** [comment]
The ofborg failure seems unrelated. Is master broken ?

**Comment by globin** [comment]
@GrahamcOfBorg build rust-bindgen

**Comment by c0bw3b** [comment]
(typo in your commit short message - `rustmft` instead of `rustfmt`)

@GrahamcOfBorg eval

**Comment by symphorien** [comment]
Sorry for the spurious review, I messed up my rebase.
* typo fixed
* bindgen test fixed with patchShebang
* tentative fix for the darwin issue.

**Comment by Mic92** [comment]
The rust error is hopefully fixed, when we merge: https://github.com/NixOS/nixpkgs/pull/50876

**Comment by edolstra** [comment]
Merged, thanks.

**Pull request merged**
