### PR TITLE
freeimage: unstable-2020-07-04 -> unstable-2021-11-01

### PR DESCRIPTION
**Pull request by L-as**
###### Motivation for this change

FreeImage has been updated. LibRaw also needed to be updated, since FreeImage depends on a commit from 2021-10-26.

In addition, many security vulnerabilities have been fixed:
```
drolon (41):
      improved Targa plugin against malicious images
      FreeImage now uses LibWebP 1.2.0 (GIT patch 2021-03-14)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-04-02)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-04-02)
      remove .vs directory
      removed the 32-bit build option from the MSVC build options
      removed the 32-bit build option from the MSVC build options
      What's new
      FreeImage now uses LibTIFF 4.1.0 (GIT patch 2021-03-10)
      FreeImage now uses LibTIFF 4.1.0 (GIT patch 2021-03-10)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-04-02)
      FreeImage now uses LibTIFF 4.1.0 (GIT patch 2021-03-10)
      updated Linux makefile
      What's new
      improved PCX plugin against malicious images
      improved PNM plugin against malicious images
      improved J2K plugin against malicious images
      improved DDS plugin against malicious images
      improved TIFF plugin against malicious images
      FreeImage now uses LibWebP 1.2.0 (GIT patch 2021-07-14)
      FreeImage now uses LibTIFF 4.3.0 (GIT patch 2021-07-09)
      FreeImage now uses LibJXR 1.2 (fixed FreeImage version)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-06-02)
      improved error handler
      git-svn-id: svn://svn.code.sf.net/p/freeimage/svn@1884 f6e0daa0-2725-47c6-9c0b-5e6e9cdd0720
      fixed a comment
      What's new
      TIFF images saved with TIFF_DEFLATE compression are saved to images with TIFF_ADOBE_DEFLATE compresssion (TIFF_DEFLATE is obsolete)
      TIFF images saved with TIFF_DEFLATE compression are saved to images with TIFF_ADOBE_DEFLATE compresssion (TIFF_DEFLATE is obsolete)
      What's new
      FreeImage now uses LibWebP 1.2.1 (GIT patch 2021-10-29)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-10-26)
      FreeImage now uses LibTIFF 4.3.0 (GIT patch 2021-10-26)
      fixed FreeImage_FlipVertical behavior with very large images
      fixed FreeImage_SeekMemory behavior with 64-bit malicious images
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-10-26)
      fixed C++11 warnings
      fixed C++11 warnings
      What's new
      fixed FreeImage_Paste behavior with very large images
      What's new
```

###### Things done

`imv` works for me.

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by L-as** [comment]
Nevermind, `imv` fails to build:
```
/nix/store/5rs0jfwgffx4cizpsn7ffhhisl22bxh0-binutils-2.35.2/bin/ld: /nix/store/bg1hvjpii0946f75hwhavymn7pwz52k9-freeimage-unstable-2021-11-01/lib/libfreeimage.so: undefined reference to `FreeImage_ZLibCRC32'
collect2: error: ld returned 1 exit status
```
Wonder why.

**Comment by L-as** [comment]
`imv` works fine.

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/4nvm2qiir0k6qbvym04vvayj7m8rz0fa-gegl-0.4.32.drv' failed with exit code 1; last 10 log lines:
  clang-7: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
  [432/735] Compiling C object operations/external/raw-load.dylib.p/raw-load.c.o
  FAILED: operations/external/raw-load.dylib.p/raw-load.c.o 
  clang -Ioperations/external/raw-load.dylib.p -Ioperations/external -I../operations/external -I. -I.. -Igegl -I../gegl -Igegl/buffer -I../gegl/buffer -Igegl/graph -I../gegl/graph -Igegl/module -I../gegl/module -Igegl/opencl -I../gegl/opencl -Igegl/operation -I../gegl/operation -Igegl/process -I../gegl/process -Igegl/property-types -I../gegl/property-types -Igegl/ctx -I../gegl/ctx -I/nix/store/kmpqkci0mkssppcy3v4fx9kyqszk4mym-babl-0.1.88-dev/include/babl-0.1 -I/nix/store/yj922jnfm4p4mhx645slls316653bhis-glib-2.70.1-dev/include -I/nix/store/yj922jnfm4p4mhx645slls316653bhis-glib-2.70.1-dev/include/glib-2.0 -I/nix/store/gwism9abmrb9sxx74md6d5k3769ya1hb-glib-2.70.1/lib/glib-2.0/include -I/nix/store/yj922jnfm4p4mhx645slls316653bhis-glib-2.70.1-dev/include/gio-unix-2.0 -I/nix/store/hrhmj48qyka7fxb1zy3ryfikkvgrwsag-lcms2-2.12-dev/include -I/nix/store/0mmliqcljpvjalrdkzv2zjx38nfkiyqy-libraw-unstable-2021-12-03-dev/include/libraw -I/nix/store/0mmliqcljpvjalrdkzv2zjx38nfkiyqy-libraw-unstable-2021-12-03-dev/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -std=gnu11 -MD -MQ operations/external/raw-load.dylib.p/raw-load.c.o -MF operations/external/raw-load.dylib.p/raw-load.c.o.d -o operations/external/raw-load.dylib.p/raw-load.c.o -c ../operations/external/raw-load.c
  clang-7: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
  ../operations/external/raw-load.c:117:29: error: no member named 'shot_select' in 'libraw_output_params_t'
            p->LibRaw->params.shot_select = o->image_num;
            ~~~~~~~~~~~~~~~~~ ^
  1 error generated.
  ninja: build stopped: subcommand failed.
```

**Comment by L-as** [comment]
This is *gegl*. @risicle What are you trying to build?

**Comment by risicle** [comment]
`nixpkgs-review`. The `libraw` bump breaks `gegl`.

**Comment by L-as** [comment]
`gegl` seems not to support the newest `libraw`. We'll probably have to make a new `libraw` attribute. What should it be called?

**Comment by risicle** [comment]
That's an option.

It might be easier to feed `freeimage` an overridden `libraw` just meant for freeimage, though that solution could lead to diamond problems for people using both libraries down the line.

Another option would be to just.. wait a bit? Is there a particular hurry to get this `freeimage` update out? Everything might just work out if we wait for `libraw` to actually make a release with their new changes and we give gegl a chance to catch up with the changed interface.

**Comment by L-as** [comment]
```
drolon (41):
      improved Targa plugin against malicious images
      FreeImage now uses LibWebP 1.2.0 (GIT patch 2021-03-14)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-04-02)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-04-02)
      remove .vs directory
      removed the 32-bit build option from the MSVC build options
      removed the 32-bit build option from the MSVC build options
      What's new
      FreeImage now uses LibTIFF 4.1.0 (GIT patch 2021-03-10)
      FreeImage now uses LibTIFF 4.1.0 (GIT patch 2021-03-10)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-04-02)
      FreeImage now uses LibTIFF 4.1.0 (GIT patch 2021-03-10)
      updated Linux makefile
      What's new
      improved PCX plugin against malicious images
      improved PNM plugin against malicious images
      improved J2K plugin against malicious images
      improved DDS plugin against malicious images
      improved TIFF plugin against malicious images
      FreeImage now uses LibWebP 1.2.0 (GIT patch 2021-07-14)
      FreeImage now uses LibTIFF 4.3.0 (GIT patch 2021-07-09)
      FreeImage now uses LibJXR 1.2 (fixed FreeImage version)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-06-02)
      improved error handler
      git-svn-id: svn://svn.code.sf.net/p/freeimage/svn@1884 f6e0daa0-2725-47c6-9c0b-5e6e9cdd0720
      fixed a comment
      What's new
      TIFF images saved with TIFF_DEFLATE compression are saved to images with TIFF_ADOBE_DEFLATE compresssion (TIFF_DEFLATE is obsolete)
      TIFF images saved with TIFF_DEFLATE compression are saved to images with TIFF_ADOBE_DEFLATE compresssion (TIFF_DEFLATE is obsolete)
      What's new
      FreeImage now uses LibWebP 1.2.1 (GIT patch 2021-10-29)
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-10-26)
      FreeImage now uses LibTIFF 4.3.0 (GIT patch 2021-10-26)
      fixed FreeImage_FlipVertical behavior with very large images
      fixed FreeImage_SeekMemory behavior with 64-bit malicious images
      FreeImage now uses LibRaw 0.20.2 (GIT patch 2021-10-26)
      fixed C++11 warnings
      fixed C++11 warnings
      What's new
      fixed FreeImage_Paste behavior with very large images
      What's new
```

Seems quite important.

**Comment by L-as** [comment]
I added a `libraw_0_20`.

**Comment by risicle** [comment]
I think the release version should remain the default and if anything you should add a `libraw_unstable`, or even make it anonymous.

**Comment by L-as** [comment]
I did this because in https://github.com/LibRaw/LibRaw/blob/master/Changelog.txt it notes that some potential vulnerabilities fixed since its last release over a year ago, e.g.
>   * fixed possible 1-byte stack underrun while handling text tags with zero lengh [sic]

Is there any policy for when an unstable version is preferred?

**Comment by risicle** [comment]
That's not something we normally do. If it's an important vulnerability we try to identify the fixing commit(s) and apply them as a patch.

**Comment by vcunat** [comment]
@OfBorg build freeimage
(in case something's changed)

**Comment by vcunat** [comment]
🤔 I was too optimistic.  There are quite a few others that don't support the new libraw: https://hydra.nixos.org/eval/1757498#tabs-now-fail

**Comment by vcunat** [comment]
Upstreams might be lazy about adapting to new API before it gets into a libraw release.

**Comment by L-as** [comment]
I made https://github.com/LibRaw/LibRaw/issues/457

Since we merged this, should we just make those packages point at the old libraw?

**Comment by vcunat** [comment]
More likely put 0.20 as default and use unstable just for freeimage.  (And perhaps try patching the stack underflow in 0.20.)

**Comment by L-as** [comment]
Apparently it's already been backported, we should just switch around the libraws.

**Comment by hamburger1984** [comment]
Probably a good idea to switch libraws - libkdcraw and krita were/are broken due to this change already.

**Pull request merged**
