### PR TITLE
util-linux: try to fix parallel build failures

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

Difficult to know if these actually fix it, since it only happens sometimes.

See https://github.com/NixOS/nixpkgs/pull/309805#issuecomment-2109348209.

Should be backported to 24.05 once possible.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
I was now trying to reproduce the failure on the community 80-core aarch64 (without these patches), but I failed, even though the machine was almost idle.  So I don't know.

**Comment by alyssais** [comment]
I've seen it locally before too.  I didn't realise it was transient at the time, because it went away after I did some other work on the package.

**Comment by vcunat** [comment]
If I didn't mess up something, this (i686) build used the patches and failed apparently in the same way again:
https://hydra.nixos.org/build/260133082

**Comment by alyssais** [comment]
> If I didn't mess up something, this (i686) build used the patches and failed apparently in the same way again:
> https://hydra.nixos.org/build/260133082

[Reported](https://lore.kernel.org/util-linux/87v83auc95.fsf@alyssa.is/)

**Comment by sternenseemann** [comment]
I think [this](https://hydra.nixos.org/build/260727109/nixlog/4) was an instance of this problem? Restarted the build.

**Comment by alyssais** [comment]
Looks like it.

**Comment by sternenseemann** [comment]
Unfortunately, restarting doesn't seem to help at all with that particular build…

**Comment by alyssais** [comment]
The util-linux upgrade has been reverted in staging, if that's helpful.

**Pull request closed without merging**
