### PR TITLE
impy,evilpixie: init

### PR DESCRIPTION
**Pull request by fgaz**
##### Motivation for this change

Cool pixel-oriented image editor. We're missing those.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
Ran nix-review, executed evilpixie in an empty PATH, checked that the open dialog does not crash, checked that the icon of the desktop file is found in rofi, saved an image successfully.

/marvin needs_merge

**Review by symphorien — APPROVED** [review]

**Comment by timokau** [comment]
Thanks @fgaz @symphorien. I couldn't find a single nit to pick and the review is great. Really nothing to do for me except pressing the merge button. Keep up the good work :)

**Pull request merged**
