### PR TITLE
spyder: withPackages passthru for python console (closes #70986)

### LINKED ISSUE #70986: spyder exec python processes which don't inherit the python path
**Describe the bug**

Spyder is unable to start IPython console because it cannot find the `spyder_kernel` module.

The exact error message is

```
/nix/store/...‑python3𔂭.7.4/bin/python3.7: Error while finding module specification for 'spyder_kernels.console' (ModuleNotFoundError: No module named 'spyder_kernels')
```

Digging into this reveals the issue is that the python module path for spyder3 is set by the injection of some python specific code at the start of it

```
import sys
import site
import functools
sys.argv[0] = '/nix/store/...-spyder-3.3.3/bin/spyder3'
functools.reduce(lambda k, p: site.addsitedir(p, k), [...big long list of paths...], site._init_pathinfo())
```

Paths set this way are not inherited by the python processes that the spyder3 program executes python process. Specifically, `strace -o log -ff -s 4096 spyder3` reveals

```
execve("/nix/store/...-python3-3.7.4/bin/python3.7", ["/nix/store/...-python3-3.7.4/bin/python3.7", "-m", "spyder_kernels.console", "-f", "/run/user/1000/jupyter/kernel-5a6e5c644048.json"], 0x4b2f4b0 /* 104 vars */) = 0
```

**To Reproduce**

```
$ nix run nixpkgs.spyder
$ spyder3
```

The IPython console window will come up with a bright red box with the error message

```
/nix/store/...‑python3𔂭.7.4/bin/python3.7: Error while finding module specification for 'spyder_kernels.console' (ModuleNotFoundError: No module named 'spyder_kernels')
```

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.69, NixOS, 19.03.173408.bd6ba87381e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173408.bd6ba87381e, unstable-19.09pre182724.3674ff05ecd"`
 - channels(tyson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by twhitehead**
###### Motivation for this change

Address the issue in #70986. That is, the python process spyder spawned for the ipython console didn't have the required `spyder-kernels` module to interface with `spyder`.

It also builds a bit on top of that by adding a `withPackages` override that is essentially used in a `python.withPackages` statement for building the python process that spyder spawns for the ipython console. This lets the user add whatever packages they need to work with their code.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @gebner

### CODE REVIEW

**Comment by twhitehead** [comment]
Been a couple of weeks now. Wondering if you guys might have a quick chance to give it a quick go over before any merge incompatibilities creep in between it and HEAD.  Thanks.  :smiley:

**Comment by jonringer** [comment]
Is this package meant to be used by other python packages?

**Comment by twhitehead** [comment]
I don't believe so. It a [scientific python IDE](https://www.spyder-ide.org/). The `withPackages` addition is so you can specify what packages are available in its interactive sessions.

**Comment by jonringer** [comment]
Then I would highly recommend removing it from python-modules and putting it into applications/scientific or something simliar

**Comment by gebner** [comment]
You can use it as a library to e.g. embed the `spyder` editor widget in another application, like CQ-editor.  (See PR #65830.)  That's why I've made spyder a python module in the first place.

**Comment by FRidh** [comment]
I'll have a look today

**Comment by jonringer** [comment]
interesting, I'm not super familiar with spyder, but if you did want to use it as a dependency in other packages, then I would recommend against doing the withPackages, as this might break composibility with other python packages.

I will defer to @FRidh though, as he's more familiar with withPackages and it's implications

**Comment by FRidh** [comment]
I think this is no longer needed, see https://github.com/NixOS/nixpkgs/issues/70986#issuecomment-552395377.

**Comment by twhitehead** [comment]
I think `withPackages` shouldn't conflict as it is a python `passthru` (i.e., as in `python.withPackages ...`) and not a python packages `passthru`. That is, using `nix repl`

```
nix-repl>  :l <nixpkgs>
nix-repl> lib.attrNames python.passthru
[ "buildEnv" "executable" "implementation" "interpreter" "isPy2" "isPy27" "isPy3" "isPy33" "isPy34" "isPy35" "isPy36" "isPy37" "isPy3k" "isPyPy" "libPrefix" "pkgs" "pythonAtLeast" "pythonForBuild" "pythonOlder" "pythonVersion" "sitePackages" "sourceVersion" "ucsEncoding" "withPackages" ]
```

while

```
nix-repl> lib.attrNames pythonPackages.nltk.passthru
[ "pythonModule" "pythonPath" "requiredPythonModules" ]
```

**Comment by twhitehead** [comment]
My understanding of 6e9743f is that it addresses the fact that IPython wouldn't start, but it doesn't address the need to be able to specify the packages that are available in that IPython session (which would be whatever the code you are working on requires).

**Comment by FRidh** [comment]
imports work fine.

**Comment by twhitehead** [comment]
Existing way to do this was given at end of issue #70986.

**Pull request closed without merging**
