### PR TITLE
ceph: 12.2.7 -> 14.2.1

### PR DESCRIPTION
**Pull request by johanot**
###### Motivation for this change
Make ceph up-to-date and not broken.
This PR probably has a better chance of being merged before 19.09 than #49866.
It includes all commits from #49866 , plus:

- 13.2.2 -> 14.2.1 upgrade
- python2 -> python3
- more cherrypy version check patching
- more pythonpath hardcoding
- use of in-tree rocksdb, since ceph 14 is not compatible with rockdb 6, introduced here:
https://github.com/NixOS/nixpkgs/commit/b54b5f9ad88b5138e4e4ca4a49cbd2d89559e897

**Result:**
It has been rebased with master, and It builds! :tada: 

**Dashboard:**
Not included yet. Working on it. That's the WIP part. If we decide not to include that, we can probably skip all the cherrypy patches.

**Testing:**
Real-life testing has been performed with 14.2.1 already. 
The use of in-tree rocksdb however has not. 
Will deploy this addition to my own ceph environment soon.

A bunch of squashing is probably also needed before merging.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
Good work! (And to all of the people involved earlier as well!)

Refresh my memory though; if we decided not to ship the dashboard for now, do we even need the cerrypy hackery?

**Comment by lejonet** [comment]
Since 14.2.0, they've broken out the dashboard to its own package. So we shouldn't need to have to have anything to do with it in the ceph build henceforth. (reference: "Also, the Ceph Dashboard is now split into its own package named
ceph-mgr-dashboard." [1](https://ceph.com/releases/v14-2-0-nautilus-released/))

I'm actually going to prime and install a new ceph node this weekend, I'll do it with this PR to give it some more testing.

**Comment by srhb** [comment]
<itshappening.gif>

**Comment by johanot** [comment]
@srhb 
> Refresh my memory though; if we decided not to ship the dashboard for now, do we even need the cerrypy hackery?

`Module 'prometheus' has failed dependency: No module named 'cherrypy'` #sadface :(

**Comment by johanot** [comment]
Update: We've just deployed this branch to our production env. at my day job, today. So far no issues.

Ok. Even though we can't get rid of cherrypy, we can still decide to merge this for 19.09? What do you say @lejonet @srhb? :-) I removed the "WIP" in the title here. What else is required before we can merge this?

**Comment by srhb** [comment]
The two of you use it actively and I'll be okay with your decision. However, it looks like the dashboard is now enabled by default -- is that safe? I don't recall whether the interface is protected initially or whether it even matters. Other than that: Are any release notes required?

**Comment by johanot** [comment]
> However, it looks like the dashboard is now enabled by default

Ah.. You mean, in the test? (https://github.com/NixOS/nixpkgs/pull/65470/files#diff-07c1a40dbc7cbf287840ba0dbbf4cd10R44)
I suspect that what happens silently in the mgr-daemons is similar to what happens when you try enabling it manually:

```
$ ceph mgr module enable dashboard
Error ENOENT: module 'dashboard' reports that it cannot run on the active manager daemon: No module named 'jwt' (pass --force to force enablement)
```
and then the dashboard just stays disabled, with the cluster still being healthy.

What I don't know though; is why the dashboard code is even still in tree and still exist in the mgr-module namespace? I've read the same release note as @lejonet, hence I would have expected something like: `Error ENOENT: all mgr daemons do not support module 'dashboard'`.

Anyway. We can of course remove the attempted dashboard enabling from the test, and we should be able to remove the cherrypy patches on `dashboard/module.py` as well, since we don't use/support the dashboard.

Also; The NixOS test fails for other reasons. Pretty embarrassing. I'll have a look at that as well. :)

**Comment by lejonet** [comment]
I never managed to deploy a ceph node with this PR because systemd-242 (the version "locked" in, in the PR branch) not liking my epyc SoC.
I'm going to fiddle with that this weekend, to retrofit 239 and hope for the best.

I'm also a bit confused why the dashboard is still in the codebase and all. The dashboard present in the 11-12 releases was completely without auth and such but iirc the biggest change outside of breaking it out to its own package in 14.2.x is that they've fitted a much more comprehensive dashboard, with auth, acls and other bells and whistles.

Thus I would defer the decision to @johanot, because he have the version actually running. Tho it would be prudent to note the cherrypy problem as a heads up to those that actually use modules.

**Comment by johanot** [comment]
Added 3 new commits, including test fixes and rel note text. also, rebased with master. But after the rebase, ceph doesn't build anymore; because: https://github.com/NixOS/nixpkgs/pull/67676 . Don't have time to try and upgrade kinetic-cpp-client today.

**Comment by globin** [comment]
Merged the kinetic-cpp-client openssl pinning to not block this.

**Comment by johanot** [comment]
Almost certain this will timeout. But let's try.
@GrahamcOfBorg test ceph

**Comment by srhb** [comment]
I'm inclined to drop kinetic support due to the potential headache of mixed openssl versions.
Other than that, I think I'm good with this I would like to get it rolling so we don't accumulate even more at this point. Can you squash it down as well? :smile:

**Comment by srhb** [comment]
Looks like there's some bootstrap permission errors in the test as well.

**Comment by johanot** [comment]
Ok @srhb. Rebased with master again, conflicts fixed. Squashed from 20 down to 12 commits. Have a look at the latest 3 commits on the branch, those are the fixes for the newest issues.

I believe the decision to remove kinetic is correct, since the project seems to be abandoned by Seagate anyway. I wrote on the ceph mailing list yesterday trying to get a current status of kinetic support in ceph - still waiting for a response on that one.

Still Ceph doesn't build, because of cherrypy now. Feel free to cherrypick (no pun intended) this: https://github.com/NixOS/nixpkgs/pull/68001 for testing.

**Comment by srhb** [comment]
Maybe we should just throw pyjwt at the dashboard anyway, and see what sticks.

**Comment by globin** [comment]
Rebased again, as a fix for cherrypy was pushed to master, tests succeed locally.

**Review by globin — APPROVED** [review]

**Comment by srhb** [comment]
Dashboard working now, will squash, rearrange and merge tonight, hopefully. :)

**Comment by srhb** [comment]
Thanks everyone involved for the hard work!

**Comment by ivan** [comment]
@srhb this broke the manual in master

```
# nixos-rebuild switch --builders '' --keep-going
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/0b7w7s7x56imv25spsb8kf1xxsg2s7z5-nixos-manual-combined.drv
  /nix/store/cxdad32g4iayp0syaph0bdr13dy8z57p-manual-olinkdb.drv
  /nix/store/xdr72sjjz5p875g4rljlakidn660ag9r-nixos-manual-html.drv
  /nix/store/lyfajhgsp5b1sglx3cnk3wd9xyb53rnf-nixos-help.drv
  /nix/store/r3wmc21fcpaj4pwic2w45499119y7kkl-nixos-manpages.drv
  /nix/store/xah07113shrf245qs98xv1zqy0j0lbpd-nixos-manual.desktop.drv
  /nix/store/kf2474dr1jflnm32i6yj4yb3v32r5385-system-path.drv
  /nix/store/07q8i3gf2i25sbc0z7jiyf7wii0h7kw0-dbus-1.drv
  /nix/store/8l60l5h40q097qkzd0ladiklnnwvrzdx-unit-dbus.service.drv
  /nix/store/a4mpj2mg91b46knp82ps60ls7cqppg7z-unit-systemd-fsck-.service.drv
  /nix/store/lz1frqf79f2gn4n9vxj6dmy0njzbklj3-unit-polkit.service.drv
  /nix/store/s0zql3ii9plkijlsb23fav9c1lz3ihg9-unit-accounts-daemon.service.drv
  /nix/store/08vh2g65vd444kw9qfdgcrhs2nk56mf9-system-units.drv
  /nix/store/r82h49yag17rmm45b39nwx2pbkx23mfa-unit-dbus.service.drv
  /nix/store/65hhbjxn75k4g4rkhhiix0d24763dxsp-user-units.drv
  /nix/store/r9h4r11y5vrgwj2dcwkw35i82wh2cz3g-etc.drv
  /nix/store/y48lplsama5qb5hmn0ihavp0m87xfdg6-nixos-system-ra-19.09.git.76d3b14.drv
building '/nix/store/0b7w7s7x56imv25spsb8kf1xxsg2s7z5-nixos-manual-combined.drv'...

manual-combined.xml:73339: element listitem: Relax-NG validity error : Did not expect element text there
 73335       </para>
 73336     </listitem>
 73337     <listitem>
 73338       Ceph has been upgraded to v14.2.1.
 73339       See the <link xlink:href="https://ceph.com/releases/v14-2-0-nautilus-released/">release notes</link> for details.
 73340       The mgr dashboard as well as osds backed by loop-devices is no longer explicitly supported by the package and module.
 73341       Note: There's been some issues with python-cherrypy, which is used by the dashboard

manual-combined.xml:72647: element section: Relax-NG validity error : Did not expect element section there
 72643    This section lists the release notes for each stable version of NixOS and
 72644    current unstable revision.
 72645   </para>
 72646   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-19.09">
 72647   <title>Release 19.09 (&#x201C;Loris&#x201D;, 2019/09/??)</title>
 72648
 72649   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-19.09-highlights">

manual-combined.xml:72647: element section: Relax-NG validity error : Element appendix has extra content: section
 72643    This section lists the release notes for each stable version of NixOS and
 72644    current unstable revision.
 72645   </para>
 72646   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-19.09">
 72647   <title>Release 19.09 (&#x201C;Loris&#x201D;, 2019/09/??)</title>
 72648
 72649   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-19.09-highlights">

manual-combined.xml:3: element info: Relax-NG validity error : Element book has extra content: info
     1  <?xml version="1.0"?>
     2  <book xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="book-nixos-manual">
     3   <info>
     4    <title>NixOS Manual</title>
     5    <subtitle>Version 19.09
     6    </subtitle>
     7   </info>

manual-combined.xml fails to validate
builder for '/nix/store/0b7w7s7x56imv25spsb8kf1xxsg2s7z5-nixos-manual-combined.drv' failed with exit code 3
cannot build derivation '/nix/store/cxdad32g4iayp0syaph0bdr13dy8z57p-manual-olinkdb.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r3wmc21fcpaj4pwic2w45499119y7kkl-nixos-manpages.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/xdr72sjjz5p875g4rljlakidn660ag9r-nixos-manual-html.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/lyfajhgsp5b1sglx3cnk3wd9xyb53rnf-nixos-help.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xah07113shrf245qs98xv1zqy0j0lbpd-nixos-manual.desktop.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kf2474dr1jflnm32i6yj4yb3v32r5385-system-path.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/07q8i3gf2i25sbc0z7jiyf7wii0h7kw0-dbus-1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s0zql3ii9plkijlsb23fav9c1lz3ihg9-unit-accounts-daemon.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lz1frqf79f2gn4n9vxj6dmy0njzbklj3-unit-polkit.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/a4mpj2mg91b46knp82ps60ls7cqppg7z-unit-systemd-fsck-.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8l60l5h40q097qkzd0ladiklnnwvrzdx-unit-dbus.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r82h49yag17rmm45b39nwx2pbkx23mfa-unit-dbus.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/08vh2g65vd444kw9qfdgcrhs2nk56mf9-system-units.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/65hhbjxn75k4g4rkhhiix0d24763dxsp-user-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r9h4r11y5vrgwj2dcwkw35i82wh2cz3g-etc.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/y48lplsama5qb5hmn0ihavp0m87xfdg6-nixos-system-ra-19.09.git.76d3b14.drv': 2 dependencies couldn't be built
error: build of '/nix/store/y48lplsama5qb5hmn0ihavp0m87xfdg6-nixos-system-ra-19.09.git.76d3b14.drv' failed
```

**Comment by srhb** [comment]
My bad. I'll fix it right away.

**Comment by lordcirth** [comment]
Has anyone looked at updating this to 14.2.3? Both .2 and .3 had critical fixes that we needed at $WORK (Not running NixOS)

**Comment by johanot** [comment]
@lordcirth it is done :) https://github.com/NixOS/nixpkgs/pull/68138

**Comment by lordcirth** [comment]
@johanot  Thanks! I guess I forgot to search for closed issues.

**Pull request merged**
