### PR TITLE
docker-compose: 2.19.1 -> 2.20.2

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Diff: https://github.com/docker/compose/compare/v2.19.1...v2.20.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LeSuisse** [comment]
@SuperSandro2000 Do you mind bumping to the freshly released 2.20.1? It includes a fix for Go 1.20.6 https://github.com/docker/compose/releases/tag/v2.20.1

**Comment by SuperSandro2000** [comment]
sure but as far as I can tell that's just bumping their docker image, so it shouldn't matter to much to us.

**Comment by LeSuisse** [comment]
It is not directly listed in the release notes (the PR listed for the Go 1.20.6 mention it) but it also contains https://github.com/docker/compose/commit/ce8a09b53f4bb87a207bdb03a0137d60c851f71a

**Comment by Frostman** [comment]
Result of `nixpkgs-review pr 244013` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
    <li>apx</li>
    <li>charliecloud</li>
    <li>docker (docker_20_10)</li>
    <li>docker-client</li>
    <li>docker-client.man</li>
    <li>docker-compose</li>
    <li>docker-gc</li>
    <li>docker.man (docker_20_10.man)</li>
    <li>fn-cli</li>
    <li>nvidia-docker</li>
    <li>pipework</li>
    <li>python310Packages.jupyter-repo2docker</li>
    <li>python310Packages.jupyter-repo2docker.dist</li>
    <li>python311Packages.jupyter-repo2docker</li>
    <li>python311Packages.jupyter-repo2docker.dist</li>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Review by Frostman — APPROVED** [review]

**Pull request merged**
