### PR TITLE
feishin: 0.5.1 -> 0.6.1, build from source

### LINKED ISSUE #262739: Build failure: feishin
feishin fails to build as it depends on `electron_24`, which is now EOL

### Steps To Reproduce

1. build feishin

### Notify maintainers

@onny 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.05 (Stoat), 23.05.20231015.0e1cff5`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(lunik1): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### LINKED ISSUE #287765: Update request: feishin 0.5.1 → 0.5.3
- Package name: feishin
- Latest released version: 0.5.3

- Current version on the unstable channel: 0.5.1
- Current version on the stable/release channel: 0.5.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@onny

-----

Note for maintainers: Please tag this issue in your PR.

---

Version 0.5.1 is using Electron 25, leading to build issues, as it is deprecated. The upstream package has since upgraded to Electron 27. 

There is an issue tracking package regressions with electron 25: https://github.com/NixOS/nixpkgs/issues/265125

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jlbribeiro**
## Description of changes

Addresses https://github.com/NixOS/nixpkgs/issues/296939 by building Feishin from source. /cc @YoshiRulz
Fixes https://github.com/NixOS/nixpkgs/issues/287765 (package update request). /cc @nadir-ishiguro
Addresses https://github.com/NixOS/nixpkgs/issues/295770 (outdated Electron). /cc @yu-re-ka
Should also fix https://github.com/NixOS/nixpkgs/issues/262739 (build failure). /cc @lunik1 

This PR continues the work started by @dotlambda in https://github.com/NixOS/nixpkgs/pull/288210.
(@dotlambda, I hope you don't mind I've added you as a `Co-authored-by` of the first commit; can remove if necessary.)

Couldn't test this on `darwin`, so I'm unsure how the desktop entry plays out in MacOS systems.

Maintainer: @onny 

(while it is mostly ready to review, I did accidentally press the "ready to review" button, since I assumed I'd be force-pushing some changes after review, maybe. speaking of which... I sincerely apologize for the absolute spam in all the mentioned issues and pull-requests...)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nadir-ishiguro** [comment]
Well, this is great. Builds and runs fine on my system:

```
nix-shell -p nix-info --run "nix-info -m"                         
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5-cachyos, NixOS, 24.05 (Uakari), 24.05.20240410.1042fd8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by lunik1** [comment]
Stellar work. Build and runs fine for me on linux.

Unfortunately I have a build failure on my M1 mac. Log is [here](https://gist.github.com/lunik1/973421517e52d13ff25b0c321c94542a).

**Comment by jlbribeiro** [comment]
@lunik1 First of all, thank you for having provided your [NUR feishin package](https://github.com/lunik1/nur-packages/tree/master/pkgs/feishin-appimage) (which I noticed just now is marked as `x86_64-linux` only :stuck_out_tongue:) to the community; I never got to use it because I focused on getting this to work out of stubbornness, but it was nice there was/is an alternative. (It's actually how I found out about NUR in the first place.)

Thank you so much for having tested this package on `darwin`; as I mentioned on the PR description, I couldn't test it on `darwin`, so I apologize for having broken it. I'll probably need to get a VM with MacOS working for testing this.

A quick `NixOS/nixpkgs` search based on "corrupted Electron dist" (from your logs) lead me to [this issue/comment](https://github.com/NixOS/nixpkgs/pull/224319#issuecomment-1493303894), which seems to point in the right direction.

**Comment by lunik1** [comment]
No worries! Thanks for actually putting in the work and getting the source build working! It not working on `darwin` isn't a huge issue for me since that's my work machine (hence why my NUR package was x86_64 linux only), but I just wanted to help out by checking the build since you couldn't.

**Pull request merged**
