### PR TITLE
[staging] coreutils: 9.1 -> 9.3 and re-enable hole seeking on Darwin

### PR DESCRIPTION
**Pull request by dasJ**
###### Description of changes
The changes are mostly minor; numerous bugs have been fixed and a few new command-line options have been added.

Changelog: https://lists.gnu.org/archive/html/coreutils-announce/2023-03/msg00000.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
Padraig said it should be better now ;)

**Comment by vcunat** [comment]
I don't expect this is suitable for 23.05 anymore.

**Comment by alyssais** [comment]
Any objections to merging now?

**Comment by dasJ** [comment]
I dont have any ;)

**Comment by tpwrules** [comment]
This seems to have caused a regression in `cp` with older kernels with a problematic `copy_file_range` call. A fix is mentioned in the latest changelogs: https://github.com/coreutils/coreutils/commit/3621d51c9d7afd87c092abb1db32188ce0d1023d

**Comment by vcunat** [comment]
Oh no, impurity in the form of build-time kernel version detection?

**Comment by tpwrules** [comment]
It's unclear, it looks like version 9.1 on my kernel handles the response from `copy_file_range` more gracefully instead of dying.

**Comment by vcunat** [comment]
@tpwrules: perhaps 9.4 will help with that?  (PR #252165)
>  -  cp, mv, and install now avoid copy_file_range on linux kernels before 5.3 irrespective of which kernel version coreutils is built against, reinstating that behavior from coreutils-9.0.

**Pull request merged**
