### PR TITLE
go_1_13: 1.13.7 -> 1.13.8, go_1_12: 1.12.16 -> 1.12.17

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

https://github.com/golang/go/releases/tag/go1.12.17
https://github.com/golang/go/releases/tag/go1.13.8

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/80165)

### CODE REVIEW

**Comment by Frostman** [comment]
`nixpkgs-review` build 746 packages and 4 failed to build: `blsd`, `gitAndTools.grv`, `gitaly`, `python38Packages.aria2p` with unrelated reasons.

**Comment by Frostman** [comment]
@FRidh how can I determine when such change should go to the staging instead of the master? thank you

**Comment by FRidh** [comment]
When there is more than 500 rebuilds, it should target staging. 

When a PR is opened, you can have a look at the labels that ofborg placed. Offline you could do this with a tool such as `nix-review`.

**Comment by kalbasit** [comment]
@FRidh I don't see a reason to merge it to staging first. Go packages are generally quick and as resource-intensive as other languages. I've been merging Go prs to master directly.

**Pull request merged**
