### PR TITLE
python312Packages.email-validator: 2.1.2 -> 2.2.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/JoshData/python-email-validator/releases/tag/v2.2.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@ofborg build python3Packages.email-validator python311Packages.email-validator

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
please check why the nix manual is failing. I have the feeling that it's the same error I had in https://github.com/NixOS/nixpkgs/pull/329464

**Comment by SuperSandro2000** [comment]
It fails because of pydantic test failures

``` 
=================================== FAILURES ===================================
_ test_address_invalid[foobar-The email address is not valid. It must have exactly one @-sign.] _

value = 'foobar'

    def validate_email(value: str) -> tuple[str, str]:
        """Email address validation using [email-validator](https://pypi.org/project/email-validator/).
    
        Note:
            Note that:
    
            * Raw IP address (literal) domain parts are not allowed.
            * `"John Doe <local_part@domain.com>"` style "pretty" email addresses are processed.
            * Spaces are striped from the beginning and end of addresses, but no error is raised.
        """
        if email_validator is None:
            ('foobar <foobar<@example.com>', None),
            ('foobar <foobar@example.com>>', None),
            ('foobar <<foobar<@example.com>', None),
            ('foobar <>', None),
            ('first.last <first.last@example.com>', None),
            pytest.param('foobar <' + 'a' * 4096 + '@example.com>', 'Length must not exceed 2048 characters', id='long'),
        ],
    )
    def test_address_invalid(value: str, reason: Union[str, None]):
        with pytest.raises(PydanticCustomError, match=f'value is not a valid email address: {reason or ""}'):
>           validate_email(value)

tests/test_networks.py:953: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = 'foobar'

    def validate_email(value: str) -> tuple[str, str]:
        """Email address validation using [email-validator](https://pypi.org/project/email-validator/).
    
        Note:
            Note that:
    
            * Raw IP address (literal) domain parts are not allowed.
            * `"John Doe <local_part@domain.com>"` style "pretty" email addresses are processed.
            * Spaces are striped from the beginning and end of addresses, but no error is raised.
        """
        if email_validator is None:
            import_email_validator()
    
        if len(value) > MAX_EMAIL_LENGTH:
            raise PydanticCustomError(
                'value_error',
                'value is not a valid email address: {reason}',
                {'reason': f'Length must not exceed {MAX_EMAIL_LENGTH} characters'},
            )
    
        m = pretty_email_regex.fullmatch(value)
        name: str | None = None
        if m:
            unquoted_name, quoted_name, value = m.groups()
            name = unquoted_name or quoted_name
    
        email = value.strip()
    
        try:
            parts = email_validator.validate_email(email, check_deliverability=False)
        except email_validator.EmailNotValidError as e:
>           raise PydanticCustomError(
                'value_error', 'value is not a valid email address: {reason}', {'reason': str(e.args[0])}
            ) from e
E           pydantic_core._pydantic_core.PydanticCustomError: value is not a valid email address: An email address must have an @-sign.

pydantic/networks.py:744: PydanticCustomError

During handling of the above exception, another exception occurred:

value = 'foobar'
reason = 'The email address is not valid. It must have exactly one @-sign.'

    @pytest.mark.skipif(not email_validator, reason='email_validator not installed')
    @pytest.mark.parametrize(
        'value,reason',
        [
            ('@example.com', 'There must be something before the @-sign.'),
            ('f oo.bar@example.com', 'The email address contains invalid characters before the @-sign'),
            ('foobar', 'The email address is not valid. It must have exactly one @-sign.'),
            ('foobar@localhost', 'The part after the @-sign is not valid. It should have a period.'),
            ('foobar@127.0.0.1', 'The part after the @-sign is not valid. It is not within a valid top-level domain.'),
            ('foo.bar@exam\nple.com ', None),
            ('foobar <foobar@example.com', None),
            ('foobar@.example.com', None),
            ('foobar@.com', None),
            ('foo bar@example.com', None),
            ('foo@bar@example.com', None),
            ('\n@example.com', None),
            ('\r@example.com', None),
            ('\f@example.com', None),
            (' @example.com', None),
            ('\u0020@example.com', None),
            ('\u001f@example.com', None),
            ('"@example.com', None),
            (',@example.com', None),
            ('foobar <foobar<@example.com>', None),
            ('foobar <foobar@example.com>>', None),
            ('foobar <<foobar<@example.com>', None),
            ('foobar <>', None),
            ('first.last <first.last@example.com>', None),
            pytest.param('foobar <' + 'a' * 4096 + '@example.com>', 'Length must not exceed 2048 characters', id='long'),
        ],
    )
    def test_address_invalid(value: str, reason: Union[str, None]):
>       with pytest.raises(PydanticCustomError, match=f'value is not a valid email address: {reason or ""}'):
E       AssertionError: Regex pattern did not match.
E        Regex: 'value is not a valid email address: The email address is not valid. It must have exactly one @-sign.'
E        Input: 'value is not a valid email address: An email address must have an @-sign.'

tests/test_networks.py:952: AssertionError
______________________________ test_string_fails _______________________________

    @pytest.mark.skipif(not email_validator, reason='email_validator not installed')
    def test_string_fails():
        class MoreStringsModel(BaseModel):
            str_regex: constr(pattern=r'^xxx\d{3}$') = ...
            str_min_length: constr(min_length=5) = ...
            str_email: EmailStr = ...
            name_email: NameEmail = ...
    
        with pytest.raises(ValidationError) as exc_info:
            MoreStringsModel(
                str_regex='xxx123xxx',
                str_min_length='1234',
                str_email='foobar<@example.com',
                name_email='foobar @example.com',
            )
        # insert_assert(exc_info.value.errors(include_url=False))
>       assert exc_info.value.errors(include_url=False) == [
            {
                'type': 'string_pattern_mismatch',
                'loc': ('str_regex',),
                'msg': "String should match pattern '^xxx\\d{3}$'",
                'input': 'xxx123xxx',
                'ctx': {'pattern': '^xxx\\d{3}$'},
            },
            {
                'type': 'string_too_short',
                'loc': ('str_min_length',),
                'msg': 'String should have at least 5 characters',
                'input': '1234',
                'ctx': {'min_length': 5},
            },
            {
                'type': 'value_error',
                'loc': ('str_email',),
                'msg': (
                    'value is not a valid email address: The email address contains invalid '
                    "characters before the @-sign: '<'."
                ),
                'input': 'foobar<@example.com',
                'ctx': {'reason': "The email address contains invalid characters before the @-sign: '<'."},
            },
            {
                'type': 'value_error',
                'loc': ('name_email',),
                'msg': (
                    'value is not a valid email address: The email address contains invalid characters '
                    'before the @-sign: SPACE.'
                ),
                'input': 'foobar @example.com',
                'ctx': {'reason': 'The email address contains invalid characters before the @-sign: SPACE.'},
            },
        ]
E       assert [{'ctx': {'pa...SPACE.', ...}] == [{'ctx': {'pa...SPACE.', ...}]
E         
E         At index 2 diff: {'type': 'value_error', 'loc': ('str_email',), 'msg': 'value is not a valid email address: An open angle bracket at the start of the email address has to be followed by a close angle bracket at the end.', 'input': 'foobar<@example.com', 'ctx': {'reason': 'An open angle bracket at the start of the email address has to be followed by a close angle bracket at the end.'}} != {'type': 'value_error', 'loc': ('str_email',), 'msg': "value is not a valid email address: The email address contains invalid characters before the @-sign: '<'.", 'input': 'foobar<@exam...
E         
E         ...Full output truncated (2 lines hidden), use '-vv' to show

tests/test_types.py:1862: AssertionError
=========================== short test summary info ============================
FAILED tests/test_networks.py::test_address_invalid[foobar-The email address is not valid. It must have exactly one @-sign.] - AssertionError: Regex pattern did not match.
FAILED tests/test_types.py::test_string_fails - assert [{'ctx': {'pa...SPACE.', ...}] == [{'ctx': {'pa...SPACE.', ...}]
==== 2 failed, 4485 passed, 98 skipped, 2 deselected, 12 xfailed in 18.39s =====
/nix/store/jmbs9r5wjaak8qrdf444qpr9v1npyg61-stdenv-linux/setup: line 1655: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/ijyxhfkmilwqqd4rdr9yjqnq8jz9sjzd-python3.12-pydantic-2.7.4.drv' failed with exit code 1;
```

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Closing in favor of #329464

**Pull request closed without merging**
