### PR TITLE
chirp: 20211016 -> 20220823

### PR DESCRIPTION
**Pull request by pkharvey**
###### Description of changes
Updated chirp package to latest version after much inactivity

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Python 2 will be soon deprecated, is there any way to update this to python 3?

**Comment by MatthewCroughan** [comment]
@onny This program will not be updated, upstream, to Python 3 unless the original upstream maintainers decide to update it. Why does this mean we cannot bump the version in nixpkgs? Does it mean this program will be removed from nixpkgs altogether? I do not think this is reasonable.

**Comment by onny** [comment]
> @onny This program will not be updated, upstream, to Python 3 unless the original upstream maintainers decide to update it. Why does this mean we cannot bump the version in nixpkgs? Does it mean this program will be removed from nixpkgs altogether? I do not think this is reasonable.

Could you open an issue upstream for Python 3 support and link it in your PR?

Yeah we can do the version bump but Python 2 will soon be dropped because it is EOF

**Comment by MatthewCroughan** [comment]
@onny I'm confused? Is Python 2 being removed from Nixpkgs? Can you link to an RFC or piece of documentation that suggests that it is?

**Comment by adisbladis** [comment]
Chirp is _already_ packaged an has an update. This is not an avenue to discuss any potential Python2 deprecation.

**Comment by MatthewCroughan** [comment]
@onny just as a note, there is already sort-of an issue upstream here https://chirp.danplanet.com/issues/10001

**Pull request merged**
