### PR TITLE
ipfs: 0.3.8 -> 0.3.9

### PR DESCRIPTION
**Pull request by devhell**
Built and tested locally.

The changelog is quite large, so I'm going to link it instead:
https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by devhell** [comment]
Glorious OOM travis.

**Comment by domenkozar** [comment]
fails to build: http://hydra.nixos.org/build/27355729/nixlog/2/raw

**Comment by devhell** [comment]
Builds fine with Go 1.5. Fails with Go 1.4. Dunno why.

**Comment by domenkozar** [comment]
Could you disable build for 1.4? Thanks

**Comment by devhell** [comment]
@domenkozar how?

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/go-packages.nix#L258

**Comment by devhell** [comment]
@domenkozar cheers buddy, will do a PR in a minute.

**Comment by domenkozar** [comment]
:+1:

**Comment by devhell** [comment]
@domenkozar When applying your disable example I get this now:
`error: go-ipfs-2015-10-30 not supported for go 1.5`

Which is wrong, as I have `go15Packages.ipfs` in my configuration, and it builds just fine.

**Comment by domenkozar** [comment]
ah you have to reverse the logic. So `disabled = isGo14;`

**Comment by devhell** [comment]
Ah, god dammit. Sorry, I'm not fully awake. :-/

**Comment by edolstra** [comment]
Please move such packages out of `go-packages.nix` and out of the `goPackages` attribute set. Exposing the fact that they're written in Go is an implementation detail irrelevant to users.

**Pull request merged**
