### PR TITLE
Python: last major updates package set

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

This is the last set of major upgrades for the package set before we branch off.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
I just wanted to update botocore as well :D

**Comment by FRidh** [comment]
We have to see what the implications are of the botocore and boto3 bump. We might have to revert them or make them private to awscli.

**Comment by FRidh** [comment]
That looks good enough to me.

**Comment by dotlambda** [comment]
Only positive implications it seems :tada:

**Comment by FRidh** [comment]
We can create a new PR with `python-unstable` branch and push fixes there.

**Pull request merged**
