### PR TITLE
Update vim.section.md

### PR DESCRIPTION
**Pull request by gkb**
###### Description of changes

This is just a minor correction of a verb in documentation.

###### Things done

Nothing in particular needs to be tested here.

### CODE REVIEW

**Comment by bobby285271** [comment]
Hi! Please target `master` branch first, we can backport the change to 22.05 later. **Note:** Please don't directly change the merge base - [follow this guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging) instead or just make a new PR otherwise you will ping lots of CODEOWNERS.

**Comment by teto** [comment]
could you rebase on master ?

**Comment by gkb** [comment]
Yep, I can do that. Let me back to you soon.

**Comment by mweinelt** [comment]
Rebasing is where things often go wrong in nixpkgs. It is recommended to set the PR to draft status before rebasing, so codeowners aren't inadvertently requested for review.

Please open a new PR with your changes and make sure to target the master branch.

**Pull request closed without merging**
