### PR TITLE
pkgsStatic.slstatus: fix build

### PR DESCRIPTION
**Pull request by KAction**
maintainers: @oxzi

### CODE REVIEW

**Review by oxzi — CHANGES_REQUESTED** [review]
While the current `master` builds for me, your change fails for me due to missing `-lXau` and `-llXdcmp`:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/881bsjyn3bpm6xpf3qfvd6hxc2vvf2rp-slstatus-b14e039
source root is slstatus-b14e039
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: SHELL=/nix/store/qqa28hmysc23yy081d178jfd9a1yk8aw-bash-5.2-p15/bin/bash LDLIBS=-lX11\ -lxcb\ -lXau\ -lXdmcp CC=gcc
cp config.def.h config.h
gcc -o slstatus.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os slstatus.c
gcc -o components/battery.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/battery.c
gcc -o components/cpu.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/cpu.c
gcc -o components/datetime.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/datetime.c
gcc -o components/disk.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/disk.c
gcc -o components/entropy.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/entropy.c
gcc -o components/hostname.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/hostname.c
gcc -o components/ip.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/ip.c
gcc -o components/kernel_release.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/kernel_release.c
gcc -o components/keyboard_indicators.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/keyboard_indicators.c
gcc -o components/keymap.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/keymap.c
gcc -o components/load_avg.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/load_avg.c
gcc -o components/netspeeds.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/netspeeds.c
gcc -o components/num_files.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/num_files.c
gcc -o components/ram.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/ram.c
gcc -o components/run_command.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/run_command.c
gcc -o components/swap.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/swap.c
gcc -o components/temperature.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/temperature.c
gcc -o components/uptime.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/uptime.c
gcc -o components/user.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/user.c
gcc -o components/volume.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/volume.c
gcc -o components/wifi.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os components/wifi.c
gcc -o util.o -c -I/usr/X11R6/include -D_DEFAULT_SOURCE -std=c99 -pedantic -Wall -Wextra -Os util.c
gcc -o slstatus -L/usr/X11R6/lib -s components/battery.o components/cpu.o components/datetime.o components/disk.o components/entropy.o components/hostname.o components/ip.o components/kernel_release.o components/keyboard_indicators.o components/keymap.o components/load_avg.o components/netspeeds.o components/num_files.o components/ram.o components/run_command.o components/swap.o components/temperature.o components/uptime.o components/user.o components/volume.o components/wifi.o util.o slstatus.o -lX11 -lxcb -lXau -lXdmcp
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: cannot find -lXau: No such file or directory
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: cannot find -lXdmcp: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:43: slstatus] Error 1
```

**Comment by KAction** [comment]
This is curious, it builds find for me and libX11 pulls everything else. I can add Xaux and Xdmcp explicity into buildDepends, jus tin case

**Comment by KAction** [comment]
Weird. It builds fine on my branch, but fails on `nixpkgs-review`.

**Comment by KAction** [comment]
Result of `nixpkgs-review pr 216541` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>slstatus</li>
  </ul>
</details>

**Comment by KAction** [comment]
Ah, nevermind. I understand what I did wrong. Fixed.

**Review by oxzi — APPROVED** [review]
Looks good to me.

Thanks for your PR.

**Pull request merged**
