### PR TITLE
libdrm: 2.4.117 -> 2.4.118

### PR DESCRIPTION
**Pull request by Lenchog**
Hyprland requires version 2.4.118 as a dependency

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Reword the commit:

> libdrm: 2.4.117 -> 2.4.118

Also rebase to staging.
Read the docs on how to do this - or else the world will be pinged.

**Comment by Lenny0939** [comment]
I only forked master, should I delete this fork and start again?

**Comment by AndersonTorres** [comment]
> I only forked master, should I delete this fork and start again?

This is the easiest form. Feel free if you are not feeling so brave.

Usually the change to staging requires a cherry-pick and a modification here in GitHub.

However, when done wrong it injects too many commits from other branches, and the planet is pinged.

**Comment by Lenny0939** [comment]
Alright, I'll delete this and start again. To clarify, I fork the whole repo and then make changes to the "staging" branch, right? This is my first time contributing to any kind of open source, thanks for helping

**Review by oxalica — CHANGES_REQUESTED** [review]
Please update the hash for the new version. Or it's still using the old src.

**Comment by Lenny0939** [comment]
ok, how do I do that?

**Comment by qubitnano** [comment]
This was already updated and is now in master and unstable

- https://github.com/NixOS/nixpkgs/pull/269129

**Comment by Lenny0939** [comment]
Oh, great. Thanks

**Comment by Lenny0939** [comment]
I'll delete this pr then

**Pull request closed without merging**
