### PR TITLE
perl: fix modules for compatibility with miniperl

### LINKED ISSUE #66741: perlPackages.ModuleBuild (a dependency of git) fails to cross-compile
`perlPackages.ModuleBuild` fails to cross-compile, which prevents `git` from cross-compiling (unless `perlSupport = false`). I don't have much experience with Perl, but my understanding is that `Scalar::Util` is trying to load an XS module. I'm not sure how to work around this.

```
unpacking sources
unpacking source archive /nix/store/jwpgfd4pziwrrx2hywr9ckf9xil7aizc-Module-Build-0.4229.tar.gz
source root is Module-Build-0.4229
setting SOURCE_DATE_EPOCH to timestamp 1555368693 of file Module-Build-0.4229/t/xs.t
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
patching ./t/properties/share_dir.t...
patching ./t/compat/exit.t...
patching ./t/xs.t...
patching ./t/write_default_maniskip.t...
patching ./t/versions.t...
patching ./t/use_tap_harness.t...
patching ./t/unit_run_test_harness.t...
patching ./t/tilde.t...
patching ./t/test_types.t...
patching ./t/test_type.t...
patching ./t/test_reqs.t...
patching ./t/test_file_exts.t...
patching ./t/signature.t...
patching ./t/script_dist.t...
patching ./t/runthrough.t...
patching ./t/ppm.t...
patching ./t/pod_parser.t...
patching ./t/parents.t...
patching ./t/par.t...
patching ./t/notes.t...
patching ./t/new_from_context.t...
patching ./t/mymeta.t...
patching ./t/metadata2.t...
patching ./t/metadata.t...
patching ./t/manifypods.t...
patching ./t/install_extra_target.t...
patching ./t/install.t...
patching ./t/help.t...
patching ./t/files.t...
patching ./t/extend.t...
patching ./t/ext.t...
patching ./t/destinations.t...
patching ./t/debug.t...
patching ./t/compat.t...
patching ./t/basic.t...
patching ./t/add_property_hash.t...
patching ./t/add_property_array.t...
patching ./t/add_property.t...
patching ./t/PL_files.t...
patching ./bin/config_data...
# running Build.PL --prefix /nix/store/9lm1ijj01kmimdplwrs77faflwzxjir3-perl5.28.2-Module-Build-0.4229-armv6l-unknown-linux-gnueabihf --installdirs site --config perl=/nix/store/dv4w3l6jclic0wqbkpwv6m79wbfkvk9n-perl-5.28.2-armv6l-unknown-linux-gnueabihf-dev/bin/perl --fullperl "/nix/store/by0xi2dd0aha8armhbkd2a3zdqzrjnmi-perl-5.28.2/bin/perl"
Checking prerequisites...
  test_requires:
    !  Couldn't find a $VERSION in prerequisite File::Temp

Checking optional features...
inc_bundling_support....disabled
  requires:
    ! inc::latest is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Attempt to reload Scalar/Util.pm aborted.
Compilation failed in require at /nix/store/81lwy2awhy4fqxxiyqcc9jflslrzl2bm-perl-5.28.2-armv6l-unknown-linux-gnueabihf/lib/perl5/5.28.2/armv6l-linux/Data/Dumper.pm line 312.
Couldn't run Build.PL: No such file or directory at lib/Module/Build/Compat.pm line 341.
```

Maintainer information:
```yaml
attribute:
  - perlPackages.ModuleBuild
  - git
```

cc @shlevy @volth because you've worked on Perl cross-compiling

### PR DESCRIPTION
**Pull request by ck3d**
###### Description of changes

When perl modules are cross-compiled, miniperl is used which do not allow dynamic loading.
This PR adds compatibitly for miniperl to following modules:

- CPAN::Meta
- JSON::PP
- Data::Dumper

Additionally, this PR fixes #66741, the cross compilation for Perl module ModuleBuild. Following command will succeed:

```sh
nix-build -A pkgsCross.aarch64-multiplatform.perlPackages.ModuleBuild
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by G3zz** [comment]
I can help test this on aarch64. What commands should I run?

**Comment by G3zz** [comment]
I rebased over mastet on my nixpkgs fork: https://github.com/G3zz/nixpkgs/commit/f5c7e6e55860a9d43d9d7eb8896e867122205bf4

**Comment by ck3d** [comment]
The compilation of ModuleBuild give confidence for the patch. Thanks for your offer, but I do not know what else could be tested.

**Comment by stigtsp** [comment]
Hi there! 

I think this looks like an interesting fix to issues with cross build. Planning on looking at this when perl-5.38.0 drops next week. The patches might need some work for 5.38.0 though.

**Comment by avnik** [comment]
I tried it on recent nixos-23.05 branch (with minimal required change -- one file renamed), it works and even allow me to build `nix-build -A pkgsCross.aarch64-multiplatform.xdg-utils`

**Comment by ck3d** [comment]
Thanks for testing. I updated this PR to the latest version of branch _statging_.

**Comment by stigtsp** [comment]
I've included these commits, and updated them for perl-5.38.0 in:
- https://github.com/NixOS/nixpkgs/pull/241848

**Comment by ck3d** [comment]
Great, thanks. I will close this PR.

**Comment by stigtsp** [comment]
>     * [[staging] perl: 5.36.0 -> 5.38.0 #241848](https://github.com/NixOS/nixpkgs/pull/241848)

This has now been merged into staging, if anyone would like to test cross-builds

**Pull request closed without merging**
