### PR TITLE
terraform-providers.equinix: init at 1.5.0

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
@ofborg eval

**Comment by zimbatm** [comment]
getting a hash mismatch with nixpkgs-review:
```
error: hash mismatch in fixed-output derivation '/nix/store/s9aadlk0hnnp211dps9wwyh7mr6dyx6c-source-v1.5.0.drv':
         specified: sha256-+NrEP5x9/ymNb2qSdMyHNu7rjUtYxDT5Nv70vMxfTJw=
            got:    sha256-Ll+1g8MBmTiuNn7i+fZuCKJUoi3w5nRO0Co2GhcnArE=
```

**Comment by zowoq** [comment]
`/nix/store/s9aadlk0hnnp211dps9wwyh7mr6dyx6c-source-v1.5.0.drv` doesn't have the overridden `postFetch`. Not sure why it doesn't work with `nixpkgs-review`?

**Comment by zimbatm** [comment]
There must be a reference to the original derivation somewhere (but I couldn't find it).

What do you think of turning this around and passing the override directly to the mkTerraformProvider constructor somehow? `special-providers` is only containing a bunch of overrides and is mostly a historical artefact now.

**Comment by zowoq** [comment]
> What do you think of turning this around and passing the override directly to the mkTerraformProvider constructor somehow? `special-providers` is only containing a bunch of overrides and is mostly a historical artefact now.

Not sure I understand what you are proposing? The overrides need to go somewhere, I don't think trying to put them in json is a good idea. Doesn't that leave us with needing to have something like `special-providers` anyway?

**Comment by zimbatm** [comment]
I'm thinking of something similar to

**Comment by zowoq** [comment]
TBH that seems kind of complex for the simple (and usually temporary) overrides that we need here, I don't really see that we would gain much benefit by switching from what we have currently.

**Comment by zowoq** [comment]
I can't reproduce the `nixpkgs-review` problem.

Merging this as it is the replacement for the now deprecated `metal` provider and I think changing how the overrides themselves work is tangential to this PR.

While I don't see much benefit in changing away from what we have currently I'm not opposed to it so feel free to open a PR for it or we can keep talking here.

**Pull request merged**
