### PR TITLE
command-not-found: Add ZSH Support

### PR DESCRIPTION
**Pull request by spwhitt**
I took the liberty of moving command-not-found out of the bash folder since this change makes it no longer bash specific.

### CODE REVIEW

**Comment by offlinehacker** [comment]
+1 Looks good to me

**Comment by iElectric** [comment]
Couldn't we use the same function as for bash? It's one line difference.

**Comment by spwhitt** [comment]
It's actually 4 lines difference. ZSH's command_not_found_handler falls back on its default handler when you return an error code (which is typically printing: "zsh: command not found: <program>", where Bash's doesn't. This is why I needed to remove the echo statement in the final else clause, otherwise you could get redundant output like this:

```
make: command not found
zsh: command not found: make
```

The 'else return 127' in the nested if had to removed for a similar reason, otherwise you'd get output like this:

```
The program ‘make’ is currently not installed. You can install it by typing:
  nix-env -i gnumake
zsh: command not found: make
```

I understand the desire for DRY, but in this case it just seems simpler to separate them since the semantics of command-not-found are different in bash and zsh. Additionally, ZSH is a special case in that its syntax is somewhat compatible with Bash. If we support other shells like Fish in the future, they will have to be separate anyway, so the benefit of abstracting here is marginal.

**Comment by puffnfresh** [comment]
:fireworks:

**Pull request merged**
