### PR TITLE
python3Packages.mir_eval: init at 0.7, add carlthome as maintainer 

### PR DESCRIPTION
**Pull request by carlthome**
###### Description of changes

Add mir_eval for MIR R&D evaluation.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Janik-Haag — CHANGES_REQUESTED** [review]

**Comment by Janik-Haag** [comment]
If you rebase the two commits into one I will approve it.

**Comment by Janik-Haag** [comment]
Ah sorry should have been a bit more specific you had 3 commits and now you should have 2. One that's adding you as a maintainer, and one doing the python3Packaes.mir_eval: init

For an example see https://github.com/NixOS/nixpkgs/pull/209733/commits ignore the releasenotes and module commits ^^
Can you also rename the PR?

Sorry for the trouble :see_no_evil:

**Comment by carlthome** [comment]
Done!

TBH this strikes me as commit history vanity but I'll assume there's good reasons for being this strict with the history. However, noticed that maintainers.nix doesn't follow this convention, e.g. https://github.com/NixOS/nixpkgs/commit/5914055503bea117a4db49a7013ae04688804b7b

**Comment by Janik-Haag** [comment]
To be Honest I don't know the reason for being that strict with the histroy, that would probably be a question for the nixpkgs matrix channel or for discourse, might also be documented in the nixpkgs manual.

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Comment by carlthome** [comment]
Status on this?

**Comment by Janik-Haag** [comment]
Merged this since no one complaint in over a month.

**Comment by Janik-Haag** [comment]
Thank you for your contributions, keep them coming :D

**Pull request merged**
