### PR TITLE
libuv: disable flaky darwin test and enable some tests on x64 darwin

### PR DESCRIPTION
**Pull request by paparodeo**
test fails on darwin sometimes but will pass eventually

https://hydra.nixos.org/build/281912463/nixlog/234

enable x64 darwin tests that were disabled due to using an sdk < 10.15 now that it uses sdk 11

remove conditionally disabled tests which are already disabled by default

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]

**Comment by alyssais** [comment]
Reported upstream?

**Comment by paparodeo** [comment]
> Reported upstream?

quite a number of tests seem quite unreliable and there are something like 50 tests disabled with a comment.
```
    # Sometimes: timeout (no output), failed uv_listen. Someone
          # should report these failures to libuv team. There tests should
          # be much more robust.
```

I don't want to volunteer to be the libuv maintainer at this time but perhaps will circle back at some point.

**Comment by paparodeo** [comment]
https://github.com/libuv/libuv/issues/4650

**Comment by juanarbol** [comment]
Intended to be fixed in https://github.com/libuv/libuv/pull/4652, sorry for the inconveniences.

**Comment by paparodeo** [comment]
should disable test in the meantime -- while the failure rate on my machine is low it seems to fail regularly on hydra.

**Comment by alyssais** [comment]
Would be better to backport the patch — it'll be noticed when updating, whereas a manually disabled test is unlikely to be.

**Comment by paparodeo** [comment]
> Would be better to backport the patch — it'll be noticed when updating, whereas a manually disabled test is unlikely to be.

it will prevent the auto-updater from updating the package as the patch will conflict

**Comment by alyssais** [comment]
Thanks a lot for the cleanup!

**Pull request merged**
