### PR TITLE
Create CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by hiiruki**
Add CONTRIBUTION.md

### CODE REVIEW

**Comment by Synthetica9** [comment]
Don't like it, this sort of thing should:

1. Be discussed first, probably via an RFC
2. Not be done before we see what sort of fallout the exact same thing will have on the Linux project.

**Comment by matthewbauer** [comment]
There is alread a .github/CONTRIBUTING.md file:

https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md

**Comment by Ma27** [comment]
> Be discussed first, probably via an RFC

:+1:. Although this means a lot more work for the author I think that altering contribution guidelines is a fundemental change where an RFC is appropriate.

I think that the contributing guidelines you're adding/modifying here should mention that as well.

**Comment by FRidh** [comment]
As pointed out by @matthewbauer the file already exists. If you can think of improvements, please go ahead and open a PR, issue, or RFC depending on the scope of the changes.

**Pull request closed without merging**
