### PR TITLE
doc/default.nix: make the manual build on more than one core

### PR DESCRIPTION
**Pull request by ghost**
Let's build the manual with more than one core.  Maybe people will take better care of it now that it is less painful to build.

### CODE REVIEW

**Comment by Artturin** [comment]
Can't test

`nix build ".#htmlDocs.nixpkgsManual"`

```
nixpkgs-manual> cp -r doc-support/result/highlightjs/highlight.pack.js highlightjs/
nixpkgs-manual> cp: cannot stat 'doc-support/result/highlightjs/highlight.pack.js': No such file or directory
```

**Comment by amjoseph-nixpkgs** [comment]
> But yeah we should give the manual an entry in `pkgs/top-level/all-packages.nix`

- https://github.com/NixOS/nixpkgs/pull/226064

**Comment by fricklerhandwerk** [comment]
@pennae you're certainly more qualified than me to assess this.

**Comment by amjoseph-nixpkgs** [comment]
Latest push implements @pennae's suggestion.

**Review by pennae — APPROVED** [review]

**Comment by fricklerhandwerk** [comment]
Thanks a lot, everyone!

**Pull request merged**
