### PR TITLE
opencv4: 4.1.2 -> 4.3.0

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Noticed it was out of date.

This still does not work, the build fails with a cryptic linker error that I am unsure how to debug. Figured I'd open this draft and ask the maintainers (cc. @mdaiter @basvandijk) for help.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
```
opencv> Scanning dependencies of target opencv_xphoto
opencv> [ 70%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/bm3d_image_denoising.cpp.o
opencv> [ 70%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/inpainting.cpp.o
opencv> [ 70%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/dct_image_denoising.cpp.o
opencv> [ 71%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/learning_based_color_balance.cpp.o
opencv> [ 71%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/grayworld_white_balance.cpp.o
opencv> [ 71%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/oilpainting.cpp.o
opencv> [ 71%] Linking CXX executable ../../bin/opencv_annotation
opencv> [ 71%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/simple_color_balance.cpp.o
opencv> [ 71%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/tonemap.cpp.o
opencv> /nix/store/p1y0xl8dp4s1x1vvxxb5sn84wj6lsh8s-binutils-2.31.1/bin/ld: ../../lib/libopencv_imgcodecs.so.4.3.0: undefined reference to `Imf_opencv::Chromaticities::Chromaticities(Imath_2_3::Vec2<float> const&, Imath_2_3::Vec2<float> const&, Imath_2_3::Vec2<float> const&, Imath_2_3::Vec2<float> const&)'
opencv> /nix/store/p1y0xl8dp4s1x1vvxxb5sn84wj6lsh8s-binutils-2.31.1/bin/ld: ../../lib/libopencv_imgcodecs.so.4.3.0: undefined reference to `Imf_opencv::Header::Header(int, int, float, Imath_2_3::Vec2<float> const&, float, Imf_opencv::LineOrder, Imf_opencv::Compression)'
opencv> collect2: error: ld returned 1 exit status
opencv> make[2]: *** [apps/annotation/CMakeFiles/opencv_annotation.dir/build.make:106: bin/opencv_annotation] Error 1
opencv> make[1]: *** [CMakeFiles/Makefile2:5380: apps/annotation/CMakeFiles/opencv_annotation.dir/all] Error 2
opencv> make[1]: *** Waiting for unfinished jobs....
opencv> [ 71%] Linking CXX executable ../../bin/opencv_visualisation
opencv> /nix/store/p1y0xl8dp4s1x1vvxxb5sn84wj6lsh8s-binutils-2.31.1/bin/ld: ../../lib/libopencv_imgcodecs.so.4.3.0: undefined reference to `Imf_opencv::Chromaticities::Chromaticities(Imath_2_3::Vec2<float> const&, Imath_2_3::Vec2<float> const&, Imath_2_3::Vec2<float> const&, Imath_2_3::Vec2<float> const&)'
opencv> /nix/store/p1y0xl8dp4s1x1vvxxb5sn84wj6lsh8s-binutils-2.31.1/bin/ld: ../../lib/libopencv_imgcodecs.so.4.3.0: undefined reference to `Imf_opencv::Header::Header(int, int, float, Imath_2_3::Vec2<float> const&, float, Imf_opencv::LineOrder, Imf_opencv::Compression)'
opencv> collect2: error: ld returned 1 exit status
opencv> make[2]: *** [apps/visualisation/CMakeFiles/opencv_visualisation.dir/build.make:106: bin/opencv_visualisation] Error 1
opencv> make[1]: *** [CMakeFiles/Makefile2:5411: apps/visualisation/CMakeFiles/opencv_visualisation.dir/all] Error 2
opencv> [ 71%] Linking CXX shared library ../../lib/libopencv_bioinspired.so
opencv> [ 71%] Built target opencv_bioinspired
opencv> [ 71%] Linking CXX shared library ../../lib/libopencv_dnn.so
opencv> [ 71%] Built target opencv_dnn
opencv> [ 71%] Linking CXX shared library ../../lib/libopencv_calib3d.so
opencv> [ 71%] Built target opencv_calib3d
opencv> [ 71%] Linking CXX shared library ../../lib/libopencv_xphoto.so
opencv> [ 71%] Built target opencv_xphoto
opencv> make: *** [Makefile:180: all] Error 2
builder for '/nix/store/yx0hv8h3mjfq19z5prm07l8mfvsbd37c-opencv-4.3.0.drv' failed with exit code 2; last 10 log lines:
  make[1]: *** [CMakeFiles/Makefile2:5411: apps/visualisation/CMakeFiles/opencv_visualisation.dir/all] Error 2
  [ 71%] Linking CXX shared library ../../lib/libopencv_bioinspired.so
  [ 71%] Built target opencv_bioinspired
  [ 71%] Linking CXX shared library ../../lib/libopencv_dnn.so
  [ 71%] Built target opencv_dnn
  [ 71%] Linking CXX shared library ../../lib/libopencv_calib3d.so
  [ 71%] Built target opencv_calib3d
  [ 71%] Linking CXX shared library ../../lib/libopencv_xphoto.so
  [ 71%] Built target opencv_xphoto
  make: *** [Makefile:180: all] Error 2
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/yx0hv8h3mjfq19z5prm07l8mfvsbd37c-opencv-4.3.0.drv' failed
```

**Comment by lovesegfault** [comment]
@flokli figured out how to correctly get OpenCV to detect OpenEXR, this is now ready to go!

**Comment by flokli** [comment]
Can you do a nix-review to see if this introduced any breakages in reverse dependencies?

**Comment by lovesegfault** [comment]
> Can you do a nix-review to see if this introduced any breakages in reverse dependencies?

Running :)

**Comment by lovesegfault** [comment]
Eh, I don't have enough disk space to build all the reverse dependencies :(

**Comment by flokli** [comment]
Alright, let's merge this.

**Comment by vcunat** [comment]
Cross-link: https://github.com/NixOS/nixpkgs/pull/86405

**Pull request merged**
