### PR TITLE
python3Packages.pyhomematic: init at 0.1.38

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Useful for #33675.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
ping @FRidh

**Comment by FRidh** [comment]
@GrahamcOfBorg build python2.pkgs.pyhomematic python3.pkgs.pyhomematic

**Comment by dotlambda** [comment]
"Compatibility currently is only given for Python 3, since this library is primarily intended to add Homematic to https://home-assistant.io/, wich is written in Python 3."

**Comment by dotlambda** [comment]
@FRidh You might have to trigger the build again.

**Comment by dotlambda** [comment]
ping @FRidh

**Comment by FRidh** [comment]
@GrahamcOfBorg build python2.pkgs.pyhomematic python3.pkgs.pyhomematic

**Comment by dotlambda** [comment]
It's still Python 3 only :)

**Comment by dotlambda** [comment]
Updated to version 0.1.38

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python3Packages.pyhomematic

**Comment by FRidh** [comment]
```
Ran 0 tests in 0.000s
```
No tests are found. Either the test runner cannot find tests and needs to be patched, or there simply are no tests in which case the tests need to be disabled. Do include a comment explaining why the tests are disabled.

**Comment by dotlambda** [comment]
Disbled tests because they require network access and a Homematic device called CCU:
https://github.com/danielperna84/pyhomematic/blob/0.1.38/test.py

**Pull request merged**
