### PR TITLE
curl: Use CA bundle in nix default profile by default

### PR DESCRIPTION
**Pull request by shlevy**
@copumpkin

### CODE REVIEW

**Comment by shlevy** [comment]
If this is acceptable I'd like to get it in 16.09 and 17.03 as well

**Comment by copumpkin** [comment]
Why would NixOS releases make a difference to Darwin stuff? Otherwise it looks fine

**Comment by shlevy** [comment]
@copumpkin Because we have some users who use those as stable nix channels.

**Comment by LnL7** [comment]
I hope not, I thought that darwin fixes where never ported to release branches.

**Comment by shlevy** [comment]
OK, I'll tell them to switch to unstable

**Comment by domenkozar** [comment]
Doesn't this collide with @edolstra patch at https://github.com/NixOS/nixpkgs/issues/23605

**Comment by shlevy** [comment]
Not really, no. This is for cases where the env var isn't set at all. If it is, nix indeed overrides the default cert path already.

**Comment by domenkozar** [comment]
So this is for the cases when Nix profile is not sourced? Makes sense. But we'd need to patch git, etc as well then.

**Pull request merged**
