### PR TITLE
super-productivity: 1.10.45 -> 6.5.2

### PR DESCRIPTION
**Pull request by cheriimoya**
###### Motivation for this change
The current version of the package in the nixpkgs segfaults

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Why is this not targeting master?

**Comment by Mic92** [comment]
cherry-picked into master: 92ec5c8583f7f710816100433d21b12d0db8e6c8

**Comment by cheriimoya** [comment]
@SuperSandro2000 actually because i don't quite get when to target master and when to target staging...

**Comment by Mic92** [comment]
When the package triggers a lot of rebuild of dependent packages it should go to staging.

**Comment by cheriimoya** [comment]
@Mic92 okay, thanks! just for further reference, (how) can i check the amount of rebuilds my changes will trigger locally? i've looked into nixpkgs-review and niff, am i on the right track here?

**Pull request closed without merging**
