### PR TITLE
awscli: 1.18.150 -> 1.18.184

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

awscli was broken

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you please target staging?

**Comment by zimbatm** [comment]
Less than 500 packages, I think it's fine

**Comment by zimbatm** [comment]
Result of `nixpkgs-review pr 104784` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>43 packages marked as broken and skipped:</summary>
  <ul>
    <li>mlflow-server</li>
    <li>nixops</li>
    <li>nixopsUnstable</li>
    <li>nixops_1_6_1</li>
    <li>python27Packages.aws-sam-translator</li>
    <li>python27Packages.aws-xray-sdk</li>
    <li>python27Packages.bkcharts</li>
    <li>python27Packages.boto3</li>
    <li>python27Packages.botocore</li>
    <li>python27Packages.cfn-lint</li>
    <li>python27Packages.chalice</li>
    <li>python27Packages.credstash</li>
    <li>python27Packages.drms</li>
    <li>python27Packages.duckdb</li>
    <li>python27Packages.fiona</li>
    <li>python27Packages.flammkuchen</li>
    <li>python27Packages.fs-s3fs</li>
    <li>python27Packages.imbalanced-learn</li>
    <li>python27Packages.mapbox</li>
    <li>python27Packages.mapsplotlib</li>
    <li>python27Packages.moto</li>
    <li>python27Packages.pandas</li>
    <li>python27Packages.rasterio</li>
    <li>python27Packages.s3transfer</li>
    <li>python27Packages.sapi-python-client</li>
    <li>python27Packages.seaborn</li>
    <li>python27Packages.serverlessrepo</li>
    <li>python27Packages.tiros</li>
    <li>python27Packages.trackpy</li>
    <li>python27Packages.vega_datasets</li>
    <li>python27Packages.vidstab</li>
    <li>python27Packages.warrant</li>
    <li>python27Packages.yfinance</li>
    <li>python37Packages.arviz</li>
    <li>python37Packages.mlflow</li>
    <li>python37Packages.optuna</li>
    <li>python37Packages.pymc3</li>
    <li>python37Packages.qasm2image</li>
    <li>python37Packages.rl-coach</li>
    <li>python37Packages.trackpy</li>
    <li>python38Packages.mlflow</li>
    <li>python38Packages.qasm2image</li>
    <li>python38Packages.trackpy</li>
  </ul>
</details>
<details>
  <summary>319 packages failed to build:</summary>
  <ul>
    <li>apache-airflow (python37Packages.apache-airflow)</li>
    <li>aws-google-auth</li>
    <li>aws-sam-cli</li>
    <li>awslogs</li>
    <li>barman</li>
    <li>buildbot (python38Packages.buildbot)</li>
    <li>buildbot-full (python38Packages.buildbot-full)</li>
    <li>buildbot-ui (python38Packages.buildbot-ui)</li>
    <li>certbot-full</li>
    <li>cloud-custodian</li>
    <li>cq-editor</li>
    <li>credstash (python38Packages.credstash)</li>
    <li>csvs-to-sqlite (python38Packages.csvs-to-sqlite)</li>
    <li>cura</li>
    <li>dvc-with-remotes</li>
    <li>elasticsearch-curator</li>
    <li>gns3-gui</li>
    <li>gns3-server</li>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>luigi</li>
    <li>octoprint</li>
    <li>python37Packages.Quandl (python37Packages.quandl)</li>
    <li>python37Packages.acoustics</li>
    <li>python37Packages.alerta-server</li>
    <li>python37Packages.altair</li>
    <li>python37Packages.aplpy</li>
    <li>python37Packages.apptools</li>
    <li>python37Packages.atomman</li>
    <li>python37Packages.awkward</li>
    <li>python37Packages.aws-sam-translator</li>
    <li>python37Packages.batchgenerators</li>
    <li>python37Packages.bkcharts</li>
    <li>python37Packages.boto3</li>
    <li>python37Packages.buildbot</li>
    <li>python37Packages.buildbot-full</li>
    <li>python37Packages.buildbot-ui</li>
    <li>python37Packages.caffe</li>
    <li>python37Packages.cartopy</li>
    <li>python37Packages.celery</li>
    <li>python37Packages.certbot-dns-route53</li>
    <li>python37Packages.cfn-lint</li>
    <li>python37Packages.cirq</li>
    <li>python37Packages.clifford</li>
    <li>python37Packages.cnvkit</li>
    <li>python37Packages.colorcet</li>
    <li>python37Packages.credstash</li>
    <li>python37Packages.csvs-to-sqlite</li>
    <li>python37Packages.cufflinks</li>
    <li>python37Packages.dask</li>
    <li>python37Packages.dask-gateway</li>
    <li>python37Packages.dask-glm</li>
    <li>python37Packages.dask-image</li>
    <li>python37Packages.dask-jobqueue</li>
    <li>python37Packages.dask-ml</li>
    <li>python37Packages.dask-mpi</li>
    <li>python37Packages.dask-xgboost</li>
    <li>python37Packages.datasets</li>
    <li>python37Packages.datashader</li>
    <li>python37Packages.dftfit</li>
    <li>python37Packages.distributed</li>
    <li>python37Packages.django-anymail</li>
    <li>python37Packages.django-raster</li>
    <li>python37Packages.djmail</li>
    <li>python37Packages.drms</li>
    <li>python37Packages.duckdb</li>
    <li>python37Packages.envisage</li>
    <li>python37Packages.fastparquet</li>
    <li>python37Packages.fiona</li>
    <li>python37Packages.flammkuchen</li>
    <li>python37Packages.flower</li>
    <li>python37Packages.flowlogs_reader</li>
    <li>python37Packages.fs-s3fs</li>
    <li>python37Packages.gensim</li>
    <li>python37Packages.geopandas</li>
    <li>python37Packages.glymur</li>
    <li>python37Packages.google_cloud_automl</li>
    <li>python37Packages.google_cloud_bigquery</li>
    <li>python37Packages.google_cloud_monitoring</li>
    <li>python37Packages.graspologic</li>
    <li>python37Packages.hass-nabucasa</li>
    <li>python37Packages.heudiconv</li>
    <li>python37Packages.holoviews</li>
    <li>python37Packages.hvplot</li>
    <li>python37Packages.ibis-framework</li>
    <li>python37Packages.image-match</li>
    <li>python37Packages.imagecorruptions</li>
    <li>python37Packages.imbalanced-learn</li>
    <li>python37Packages.imgaug</li>
    <li>python37Packages.intake</li>
    <li>python37Packages.ipydatawidgets</li>
    <li>python37Packages.labelbox</li>
    <li>python37Packages.lammps-cython</li>
    <li>python37Packages.mapbox</li>
    <li>python37Packages.mask-rcnn</li>
    <li>python37Packages.mayavi</li>
    <li>python37Packages.mesa</li>
    <li>python37Packages.moto</li>
    <li>python37Packages.nbsmoke</li>
    <li>python37Packages.nilearn</li>
    <li>python37Packages.nipype</li>
    <li>python37Packages.osmnx</li>
    <li>python37Packages.osmpythontools</li>
    <li>python37Packages.pandas</li>
    <li>python37Packages.pandas-datareader</li>
    <li>python37Packages.paperspace</li>
    <li>python37Packages.partd</li>
    <li>python37Packages.phik</li>
    <li>python37Packages.pims</li>
    <li>python37Packages.pvlib</li>
    <li>python37Packages.pyarrow</li>
    <li>python37Packages.pybids</li>
    <li>python37Packages.pycognito</li>
    <li>python37Packages.pyfftw</li>
    <li>python37Packages.pygmt</li>
    <li>python37Packages.pymatgen</li>
    <li>python37Packages.pymatgen-lammps</li>
    <li>python37Packages.pytrends</li>
    <li>python37Packages.pywick</li>
    <li>python37Packages.qiskit</li>
    <li>python37Packages.qiskit-aer</li>
    <li>python37Packages.qiskit-aqua</li>
    <li>python37Packages.qiskit-ibmq-provider</li>
    <li>python37Packages.qiskit-ignis</li>
    <li>python37Packages.qiskit-terra</li>
    <li>python37Packages.rasterio</li>
    <li>python37Packages.rpy2</li>
    <li>python37Packages.runway-python</li>
    <li>python37Packages.s3fs</li>
    <li>python37Packages.sapi-python-client</li>
    <li>python37Packages.scikit-bio</li>
    <li>python37Packages.scikitimage</li>
    <li>python37Packages.seaborn</li>
    <li>python37Packages.sentry-sdk</li>
    <li>python37Packages.serverlessrepo</li>
    <li>python37Packages.skorch</li>
    <li>python37Packages.smart_open</li>
    <li>python37Packages.snowflake-connector-python</li>
    <li>python37Packages.snowflake-sqlalchemy</li>
    <li>python37Packages.sparse</li>
    <li>python37Packages.spectral-cube</li>
    <li>python37Packages.spyder-kernels_0_5</li>
    <li>python37Packages.spyder_3</li>
    <li>python37Packages.statsmodels</li>
    <li>python37Packages.streamz</li>
    <li>python37Packages.stumpy</li>
    <li>python37Packages.stytra</li>
    <li>python37Packages.sumo</li>
    <li>python37Packages.sunpy</li>
    <li>python37Packages.tablib</li>
    <li>python37Packages.tensorboardx</li>
    <li>python37Packages.tensorly</li>
    <li>python37Packages.test-tube</li>
    <li>python37Packages.tiledb</li>
    <li>python37Packages.tiros</li>
    <li>python37Packages.traittypes</li>
    <li>python37Packages.uproot</li>
    <li>python37Packages.uproot-methods</li>
    <li>python37Packages.vega</li>
    <li>python37Packages.vega_datasets</li>
    <li>python37Packages.vidstab</li>
    <li>python37Packages.warrant</li>
    <li>python37Packages.wrf-python</li>
    <li>python37Packages.xarray</li>
    <li>python37Packages.xgboost</li>
    <li>python37Packages.yfinance</li>
    <li>python38Packages.Quandl (python38Packages.quandl)</li>
    <li>python38Packages.acoustics</li>
    <li>python38Packages.alerta-server</li>
    <li>python38Packages.altair</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.apptools</li>
    <li>python38Packages.atomman</li>
    <li>python38Packages.awkward</li>
    <li>python38Packages.aws-sam-translator</li>
    <li>python38Packages.batchgenerators</li>
    <li>python38Packages.bkcharts</li>
    <li>python38Packages.boto3</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.cartopy</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.certbot-dns-route53</li>
    <li>python38Packages.cfn-lint</li>
    <li>python38Packages.cirq</li>
    <li>python38Packages.clifford</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.colorcet</li>
    <li>python38Packages.cufflinks</li>
    <li>python38Packages.dask</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-glm</li>
    <li>python38Packages.dask-image</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.dftfit</li>
    <li>python38Packages.distributed</li>
    <li>python38Packages.django-anymail</li>
    <li>python38Packages.django-raster</li>
    <li>python38Packages.djmail</li>
    <li>python38Packages.drms</li>
    <li>python38Packages.duckdb</li>
    <li>python38Packages.envisage</li>
    <li>python38Packages.fastparquet</li>
    <li>python38Packages.fiona</li>
    <li>python38Packages.flammkuchen</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.flowlogs_reader</li>
    <li>python38Packages.fs-s3fs</li>
    <li>python38Packages.gensim</li>
    <li>python38Packages.geopandas</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.google_cloud_automl</li>
    <li>python38Packages.google_cloud_bigquery</li>
    <li>python38Packages.google_cloud_monitoring</li>
    <li>python38Packages.graspologic</li>
    <li>python38Packages.hass-nabucasa</li>
    <li>python38Packages.holoviews</li>
    <li>python38Packages.hvplot</li>
    <li>python38Packages.image-match</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.imbalanced-learn</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.intake</li>
    <li>python38Packages.ipydatawidgets</li>
    <li>python38Packages.labelbox</li>
    <li>python38Packages.lammps-cython</li>
    <li>python38Packages.mapbox</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.mayavi</li>
    <li>python38Packages.mesa</li>
    <li>python38Packages.moto</li>
    <li>python38Packages.nbsmoke</li>
    <li>python38Packages.nilearn</li>
    <li>python38Packages.nipype</li>
    <li>python38Packages.osmnx</li>
    <li>python38Packages.osmpythontools</li>
    <li>python38Packages.pandas</li>
    <li>python38Packages.pandas-datareader</li>
    <li>python38Packages.paperspace</li>
    <li>python38Packages.partd</li>
    <li>python38Packages.phik</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pvlib</li>
    <li>python38Packages.pyarrow</li>
    <li>python38Packages.pybids</li>
    <li>python38Packages.pycognito</li>
    <li>python38Packages.pyfftw</li>
    <li>python38Packages.pygmt</li>
    <li>python38Packages.pymatgen</li>
    <li>python38Packages.pymatgen-lammps</li>
    <li>python38Packages.pytrends</li>
    <li>python38Packages.pywick</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.qiskit-ignis</li>
    <li>python38Packages.qiskit-terra</li>
    <li>python38Packages.rasterio</li>
    <li>python38Packages.rpy2</li>
    <li>python38Packages.runway-python</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.sapi-python-client</li>
    <li>python38Packages.scikit-bio</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.seaborn</li>
    <li>python38Packages.sentry-sdk</li>
    <li>python38Packages.serverlessrepo</li>
    <li>python38Packages.skorch</li>
    <li>python38Packages.smart_open</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
    <li>python38Packages.sparse</li>
    <li>python38Packages.spectral-cube</li>
    <li>python38Packages.spyder-kernels_0_5</li>
    <li>python38Packages.spyder_3</li>
    <li>python38Packages.statsmodels</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.sumo</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.tablib</li>
    <li>python38Packages.tensorboardx</li>
    <li>python38Packages.tensorly</li>
    <li>python38Packages.test-tube</li>
    <li>python38Packages.tiledb</li>
    <li>python38Packages.tiros</li>
    <li>python38Packages.traittypes</li>
    <li>python38Packages.uproot</li>
    <li>python38Packages.uproot-methods</li>
    <li>python38Packages.vega</li>
    <li>python38Packages.vega_datasets</li>
    <li>python38Packages.vidstab</li>
    <li>python38Packages.warrant</li>
    <li>python38Packages.wrf-python</li>
    <li>python38Packages.xarray</li>
    <li>python38Packages.xgboost</li>
    <li>python38Packages.yfinance</li>
    <li>s3bro</li>
    <li>s4cmd</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>streamlit</li>
    <li>tebreak</li>
    <li>truvari</li>
    <li>visidata</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>aws-adfs (python38Packages.aws-adfs)</li>
    <li>awscli</li>
    <li>awsebcli</li>
    <li>bash-my-aws</li>
    <li>gitAndTools.git-remote-codecommit</li>
    <li>iceshelf</li>
    <li>python37Packages.aws-adfs</li>
    <li>python37Packages.aws-xray-sdk</li>
    <li>python37Packages.botocore</li>
    <li>python37Packages.chalice</li>
    <li>python37Packages.kombu</li>
    <li>python37Packages.pynamodb</li>
    <li>python37Packages.s3transfer</li>
    <li>python37Packages.scrapy</li>
    <li>python37Packages.scrapy-deltafetch</li>
    <li>python37Packages.scrapy-fake-useragent</li>
    <li>python37Packages.scrapy-splash</li>
    <li>python38Packages.aws-xray-sdk</li>
    <li>python38Packages.botocore</li>
    <li>python38Packages.chalice</li>
    <li>python38Packages.kombu</li>
    <li>python38Packages.pynamodb</li>
    <li>python38Packages.s3transfer</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
    <li>ssm-session-manager-plugin</li>
  </ul>
</details>

**Comment by zimbatm** [comment]
was updated independently in 360a14dcf098642aba17221b698522af4c62aa0b

**Pull request closed without merging**
