### PR TITLE
helix-gpt: init at 0.15

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

draft PR for helix-gpt. this is a bun package, so I'm experimenting here. This probably won't be very pretty, but I personally think an amount of experimentation is healthy.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by happysalada** [comment]
I'm going to go ahead and use this package as a test bed for future bun packaging features in the nix eco-system.
Anyone is of course welcome to suggest any improvements if they see any.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 283643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by jpaju** [comment]
Awesome stuff! Would supporting `aarch64-darwin` be possible in the future?

**Comment by happysalada** [comment]
@jpaju sure! I didn't know if anyone was interested. If you have a bit of time on the next PR I can add it and you can just try to build it locally and it will give you the hash, I can add it in the PR.
The one problem that I have right now with bun is that with the current package method you need the platform to be able to get the content hash, I haven't figured out a way around it yet.

**Comment by jpaju** [comment]
I'm more than interested to help! Ping me when you need me to try stuff out locally 👍

**Comment by happysalada** [comment]
see https://github.com/NixOS/nixpkgs/pull/286046 for an update and the addition of aarch64-darwin, in case you have time to help.

**Pull request merged**
