### PR TITLE
emacs-packages: remove obsolete dash package

### PR DESCRIPTION
**Pull request by aycanirican**

### CODE REVIEW

**Comment by copumpkin** [comment]
Not clear what makes this obsolete (but I don't know anything about dash). Is it that there's an adjacent expression for nearly the same thing? What's the difference between dash-functional and dash?

**Comment by aycanirican** [comment]
@copumpkin "nixos/nixpkgs/pkgs/applications/editors/emacs-modes/dash/default.nix" obsoleted this definition which provides "nixos.emacs24PackagesNg.dash"

**Comment by copumpkin** [comment]
Oh okay, thanks for the clarification!

**Comment by ttuegel** [comment]
Merged, thanks!

**Pull request merged**
