### PR TITLE
nvidia_x11: fix suspend script paths since 470.57.02

### PR DESCRIPTION
**Pull request by andrevmatos**
###### Motivation for this change
`nvidia 470.57.02` (#130664) changed the path of `nvidia-sleep.sh` and systemd scripts, making `builder.sh` miss them and suspend-to-ram on systems where `hardware.nvidia.powerManagement.enable = true` is set to fail.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andrevmatos** [comment]
@SuperSandro2000 since you reviewed last PR, could you please give a look at this one?

**Comment by baracoder** [comment]
I would prefer adding
```
if [ -e systemd/nvidia-sleep.sh ]; then
  mv systemd/nvidia-sleep.sh ./
fi
if [ -e systemd/system-sleep/nvidia ]; then
  mv systemd/system-sleep/nvidia ./
fi
```
to move the files to the location, where the rest of the script expects them.
The builder is used for a range of different versions (beta, legacy_340, legacy_390, stable, vulkan_beta) and older ones using the old path would break otherwise.

**Comment by andrevmatos** [comment]
@baracoder You're right. I'm amending my commit, to avoid polluting the commit-history with 2LoC fixups. Thanks for your feedback!

**Review by baracoder — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
Works for me.

@SuperSandro2000 could you merge this?

**Comment by nh2** [comment]
I believe this should be backported to 21.05, because that one also offers the problematic version in the beta driver:

https://github.com/NixOS/nixpkgs/blob/b09c989b82f7a4f7319802a1dcf8bfe859d65362/pkgs/os-specific/linux/nvidia-x11/default.nix#L29-L30

See #127693

Do you agree?

**Comment by andrevmatos** [comment]
Yes, I'd think so. It seems the patch matches for `465`, but I'm sure about `390` https://github.com/NixOS/nixpkgs/pull/127711#issuecomment-867204803

**Comment by veprbl** [comment]
This will require a manual backport, it seems.

**Comment by andrevmatos** [comment]
I think #133036 already backported this commit.

**Comment by veprbl** [comment]
Oh, I even saw that before, thanks for pointing that out

**Pull request merged**
