### PR TITLE
Vault: fix config when file backend is used

### PR DESCRIPTION
**Pull request by jpotier**
When the option services.vault.storageBackend is set to "file", a
systemd.tmpfiles.rules was added, with extraneous []. These are not
needed and have been removed.

Fixes issue #72786

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @volth, @aanderse, @endocrimes, @LnL7, @flokli

### CODE REVIEW

**Review by MasseR — APPROVED** [review]
Looks good to me.

I identified this same problem on my machine and verified with a similar fix.

**Review by endocrimes — APPROVED** [review]
LGTM 👍

**Comment by flokli** [comment]
rebased on latest master and converted vault vm test to python /cc #72828

**Comment by flokli** [comment]
@GrahamcOfBorg test vault

**Comment by flokli** [comment]
ran tests manually.

**Pull request merged**
