### PR TITLE
plymouth: 0.9.3 -> 0.9.4

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://cgit.freedesktop.org/plymouth/tag/?h=0.9.4

Note: I haven't tested this personally (other than build testing).
Since proper integration is what makes or breaks this,
someone should at least check a boot or two?

But thought I'd get it ready for our tester ;).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]
I've deployed this to one of my machines and it boots up fine. :+1:

**Comment by lheckemann** [comment]
Wanted to test this in a VM, but apparently build-vm-with-bootloader is broken. @worldofpeace did it show the fancy boot graphics? If so I'd say we should merge.

**Comment by worldofpeace** [comment]
> did it show the fancy boot graphics? If so I'd say we should merge.

@lheckemann I've been running it on a machine and it's quiet pretty :smile: 

I think it's good to merge.

**Comment by worldofpeace** [comment]
:sparkles:

**Pull request merged**
