### PR TITLE
fetchgitPrivate: Remove fetcher

### PR DESCRIPTION
**Pull request by adisbladis**
Since Nix 2.0 we have `builtins.fetchGit` which is a much better
option since it runs in the evaluator and has access to the regular
users ssh keys.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by grahamc — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
only mention is the package itself
```
[09:33:24] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ rg fetchgitPrivate
pkgs/top-level/all-packages.nix
253:  fetchgitPrivate = callPackage ../build-support/fetchgit/private.nix { };
```

**Comment by c0bw3b** [comment]
I guess there may be some private (sic) use of it out of nixpkgs. Maybe a mention of the alternative in 20.03 release note would be good.

**Comment by jonringer** [comment]
probably more correct, would be make an alias of builtins.fetchgit

**Comment by takeda** [comment]
@adisbladis So I just learned that this removal happened, I used `fetchgitPrivate` in combination with `buildGoPackage` like this:
```nix
  buildGoPackage = pkgs.buildGoPackage.override {
    go = pkgs.go_1_13;
    fetchgit = x: builtins.fetchGit { url = x.url; ref = x.rev; };
  };
```

like this and it allowed me to use nix with packages that had private repos, any idea how I can do that without it? If there's a way to do it with `buildGoModule` that would be even better.

**Comment by jonringer** [comment]
@takeda 
```  
  buildGoPackage = pkgs.buildGoPackage.override {
    go = pkgs.go_1_13;
    fetchgit = builtins.fetchGit;
  };
```

**Comment by takeda** [comment]
@jonringer I tried it, but unfortunately that doesn't work.

`fetchGit` doesn't expect sha256 parameter, when I write a wrapper that that removes that parameter I also need to rewrite that `rev` parameter is mapped to `ref`. But then there is an issue because I need to distinguish between hash and a tag. With a tag it supposed to be "refs/tags/${x.rev}" (example of repo: `github.com/BurntSushi/toml` rev `v0.3.1`), the problem though is when hash is given I need to provide that hash supposed to be provided as `rev` parameter, which makes things more complex. To make things worse, hashes generated by `vgo2nix` are short (I guess because go.mod only stores short version), but `builtins.fetchGit` expects the entire length. Example of repo: `github.com/PagerDuty/go-pagerduty` rev `94ee1c55dbdb`.

**Comment by jonringer** [comment]
your package might be private, but the dependencies should be public (unless go implemented private repo references that I'm unaware of (I don't mess much with go)). just use builtins.fetchGit on the `src` of your private go package, instead of editing how all go packages are built

**Comment by takeda** [comment]
Go uses git for fetching internally there are two ways to make it work with private repos:

One way (most convenient) to make it work with private repo is to add this to the configuration:
```ini
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
```

Then it will fall back to ssh and be able to access all private repos.

(this is also how `fetchgitPrivate` was working by passing ssh-agent socket)

Another way is to create `.netrc` file (I see that's what fetchFromGithub supports now) but it requires to generate a token and it is not as straight forward.

**Comment by jonringer** [comment]
beyond me, sorry ;(

**Comment by takeda** [comment]
Would this be a good reason to restore `fetchgitPrivate`?

Alternatively is there a way for `builtins.fetchGit` have a wrapper that could be a drop-in replacement for `fetchgit`? Or (maybe even better) `fetchgit` use `builtins.fetchGit`? In last case that would make `fetchgit` and `fetchFromGithub` automatically work with private repos.

**Comment by tekeri** [comment]
As a side note, I use `fetchgitPrivate` as much as possible. Because:
- building on remote server with fast connection,
- suffers low-speed Wi-Fi,
- `fetchGit` is slow since cloning and uploading some big and frequently changing repositories takes extra time.

I wish we could have fetch and build remotely with local ssh keys...

**Pull request merged**
