### PR TITLE
vimPlugins: fixup rnvimr branch, add some plugins

### PR DESCRIPTION
**Pull request by moni-dz**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122152` at 75b0c715 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/89d3b5e77ae2ebff0357ca9539b6a67f">vimPlugins.vim-clap</a></li>
  </ul>
</details>
<details>
  <summary>105 packages built successfully:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.asyncomplete-vim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.csv-vim</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.denite-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.git-messenger-vim</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lightline-ale</li>
    <li>vimPlugins.lsp-colors-nvim</li>
    <li>vimPlugins.lsp-trouble-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vimPlugins.mkdx</li>
    <li>vimPlugins.neosnippet-snippets</li>
    <li>vimPlugins.nerdcommenter</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-bufferline-lua</li>
    <li>vimPlugins.nvim-compe</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-toggleterm-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-refactor</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.one-nvim</li>
    <li>vimPlugins.onedark-vim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.sideways-vim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.supertab</li>
    <li>vimPlugins.swift-vim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-beancount</li>
    <li>vimPlugins.vim-crates</li>
    <li>vimPlugins.vim-css-color</li>
    <li>vimPlugins.vim-dadbod</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-gruvbox8</li>
    <li>vimPlugins.vim-jsdoc</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-lsp-cxx-highlight</li>
    <li>vimPlugins.vim-lua</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-monokai</li>
    <li>vimPlugins.vim-pandoc</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-signify</li>
    <li>vimPlugins.vim-smali</li>
    <li>vimPlugins.vim-startuptime</li>
    <li>vimPlugins.vim-table-mode</li>
    <li>vimPlugins.vim-wayland-clipboard</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimsence</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.vimux</li>
    <li>vimPlugins.which-key-nvim</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fortuneteller2k** [comment]
fixed vim-clap

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 122152 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>106 packages built:</summary>  <ul>    <li>spacevim</li>    <li>vimPlugins.Coqtail</li>    <li>vimPlugins.LeaderF</li>    <li>vimPlugins.YouCompleteMe</li>    <li>vimPlugins.ale</li>    <li>vimPlugins.asyncomplete-vim</li>    <li>vimPlugins.auto-session</li>    <li>vimPlugins.barbar-nvim</li>    <li>vimPlugins.chadtree</li>    <li>vimPlugins.coc-lua</li>    <li>vimPlugins.coc-nvim</li>    <li>vimPlugins.completion-treesitter</li>    <li>vimPlugins.csv-vim</li>    <li>vimPlugins.defx-nvim</li>    <li>vimPlugins.denite-nvim</li>    <li>vimPlugins.deol-nvim</li>    <li>vimPlugins.deoplete-fish</li>    <li>vimPlugins.deoplete-khard</li>    <li>vimPlugins.deoplete-nvim</li>    <li>vimPlugins.diffview-nvim</li>    <li>vimPlugins.fern-vim</li>    <li>vimPlugins.friendly-snippets</li>    <li>vimPlugins.fzf-vim</li>    <li>vimPlugins.git-messenger-vim</li>    <li>vimPlugins.git-worktree-nvim</li>    <li>vimPlugins.gitsigns-nvim</li>    <li>vimPlugins.glow-nvim</li>    <li>vimPlugins.gruvbox-community</li>    <li>vimPlugins.gruvbox-nvim</li>    <li>vimPlugins.lf-vim</li>    <li>vimPlugins.lightline-ale</li>    <li>vimPlugins.lsp-colors-nvim</li>    <li>vimPlugins.lsp-trouble-nvim</li>    <li>vimPlugins.lualine-nvim</li>    <li>vimPlugins.lush-nvim</li>    <li>vimPlugins.markdown-preview-nvim</li>    <li>vimPlugins.mkdx</li>    <li>vimPlugins.neosnippet-snippets</li>    <li>vimPlugins.nerdcommenter</li>    <li>vimPlugins.nvim-autopairs</li>    <li>vimPlugins.nvim-base16</li>    <li>vimPlugins.nvim-bqf</li>    <li>vimPlugins.nvim-bufferline-lua</li>    <li>vimPlugins.nvim-compe</li>    <li>vimPlugins.nvim-dap</li>    <li>vimPlugins.nvim-gdb</li>    <li>vimPlugins.nvim-hlslens</li>    <li>vimPlugins.nvim-jdtls</li>    <li>vimPlugins.nvim-lspconfig</li>    <li>vimPlugins.nvim-scrollview</li>    <li>vimPlugins.nvim-toggleterm-lua</li>    <li>vimPlugins.nvim-treesitter</li>    <li>vimPlugins.nvim-treesitter-context</li>    <li>vimPlugins.nvim-treesitter-refactor</li>    <li>vimPlugins.nvim-ts-rainbow</li>    <li>vimPlugins.one-nvim</li>    <li>vimPlugins.onedark-vim</li>    <li>vimPlugins.packer-nvim</li>    <li>vimPlugins.playground</li>    <li>vimPlugins.plenary-nvim</li>    <li>vimPlugins.rnvimr</li>    <li>vimPlugins.rust-tools-nvim</li>    <li>vimPlugins.sideways-vim</li>    <li>vimPlugins.sonokai</li>    <li>vimPlugins.supertab</li>    <li>vimPlugins.swift-vim</li>    <li>vimPlugins.telescope-frecency-nvim</li>    <li>vimPlugins.telescope-fzf-writer-nvim</li>    <li>vimPlugins.telescope-fzy-native-nvim</li>    <li>vimPlugins.telescope-nvim</li>    <li>vimPlugins.telescope-symbols-nvim</li>    <li>vimPlugins.telescope-z-nvim</li>    <li>vimPlugins.vim-airline</li>    <li>vimPlugins.vim-airline-themes</li>    <li>vimPlugins.vim-autoformat</li>    <li>vimPlugins.vim-beancount</li>    <li>vimPlugins.vim-clap</li>    <li>vimPlugins.vim-crates</li>    <li>vimPlugins.vim-css-color</li>    <li>vimPlugins.vim-dadbod</li>    <li>vimPlugins.vim-floaterm</li>    <li>vimPlugins.vim-flog</li>    <li>vimPlugins.vim-fugitive</li>    <li>vimPlugins.vim-git</li>    <li>vimPlugins.vim-go</li>    <li>vimPlugins.vim-gruvbox8</li>    <li>vimPlugins.vim-jsdoc</li>    <li>vimPlugins.vim-lsp</li>    <li>vimPlugins.vim-lsp-cxx-highlight</li>    <li>vimPlugins.vim-lua</li>    <li>vimPlugins.vim-matchup</li>    <li>vimPlugins.vim-monokai</li>    <li>vimPlugins.vim-pandoc</li>    <li>vimPlugins.vim-plug</li>    <li>vimPlugins.vim-rails</li>    <li>vimPlugins.vim-signify</li>    <li>vimPlugins.vim-smali</li>    <li>vimPlugins.vim-startuptime</li>    <li>vimPlugins.vim-table-mode</li>    <li>vimPlugins.vim-wayland-clipboard</li>    <li>vimPlugins.vim-which-key</li>    <li>vimPlugins.vimsence</li>    <li>vimPlugins.vimspector</li>    <li>vimPlugins.vimtex</li>    <li>vimPlugins.vimux</li>    <li>vimPlugins.which-key-nvim</li>  </ul></details>

**Comment by SenchoPens** [comment]
Hi, markdown-preview-nvim fails with an error, probably because it requires some [runtime dependencies](https://github.com/iamcco/markdown-preview.nvim#install--usage).

```
internal/modules/cjs/loader.js:892
  throw err;
  ^
Error: Cannot find module 'tslib'
Require stack:
- /nix/store/505hlpv26bwz3f6gf8vmw4irl697csb6-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/lib/app/index.js
- /nix/store/505hlpv26bwz3f6gf8vmw4irl697csb6-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/nix/store/505hlpv26bwz3f6gf8vmw4irl697csb6-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/lib/app/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/505hlpv26bwz3f6gf8vmw4irl697csb6-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/lib/app/index.js',
    '/nix/store/505hlpv26bwz3f6gf8vmw4irl697csb6-vimplugin-markdown-preview-nvim-2021-03-10/share/vim-plugins/markdown-preview-nvim/app/index.js'
  ]
}
```

**Pull request merged**
