### PR TITLE
nvidia_x11_beta: 450.66 -> 440.66.14

### PR DESCRIPTION
**Pull request by expipiplus1**
This is fetched from a different URL, so allow passing that explicitly.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by expipiplus1** [comment]
Sorry, this makes no sense, it's a driver downgrade! I rebased it without looking!

**Comment by expipiplus1** [comment]
Actually, I shouldn't have closed this, 440.66 has extensions which 450.66 lacks such as VK_KHR_ray_tracing.

**Comment by expipiplus1** [comment]
The custom URL is no longer necessary after the bump to 450.51, I left it in anyway but happy to remove.

**Review by baracoder — APPROVED** [review]

**Comment by expipiplus1** [comment]
Thanks for approving @baracoder. Is it possible to get this merged?

**Comment by Lassulus** [comment]
@eadwu pinging you here cause you changed the beta attribute to stable.

**Comment by eadwu** [comment]
Is this the vulkan driver? I'm not sure how that is handled here, generally I have never seen any version bumps to the vulkan version here (I believe).

**Comment by eadwu** [comment]
Wait I'm not sure what's the point of this, why do you want 450.51?

**Comment by eadwu** [comment]
Not sure why you would want to downgrade.

Diffed 450.57 and 450.51 release notes and I don't see any differences from 450.51 content besides additions.

**Comment by expipiplus1** [comment]
I think I may have made a mistake in using 450.51 as this wasn't a beta driver (not sure how I got that confused), thanks for catching that, @eadwu 

I've bumped my branch to 450.56.11. This version does contain extensions which 450.57 doesn't. 

One significant wart is that there aren't releases of nvidia-persistenced and nvidia-settings for the beta releases (issues raised: https://github.com/NVIDIA/nvidia-persistenced/issues/8 https://github.com/NVIDIA/nvidia-settings/issues/52) so I've had to add some functionality to use a different version of these than the driver; this is certainly not a configuration supported by Nvidia. However it seems to be working for me using a close but not exact version for these tools :/

**Comment by expipiplus1** [comment]
Ah, I'm unable to reopen this PR as I forced pushed to my branch. The diff is here https://github.com/expipiplus1/nixpkgs/commit/31f1e6ab9c0c3defe724f4306b87717a651d90f8. If the weird version mix is acceptable for the beta driver then I can reopen

**Comment by eadwu** [comment]
It's probably better to include it as `vulkan_beta` or something similar, if I'm not mistaken, I believe `beta` just refers to the short-lived branch for nvidia while the vulkan beta can be considered another branch.

Keep in mind you'll probably need to update the module `nvidia.nix` to include something like `nvidiaVulkan` that references `nvidia_x11.vulkan_beta`.

**Pull request closed without merging**
