### PR TITLE
nixos/n8n: correct configuration, webhookUrl type

### PR DESCRIPTION
**Pull request by gmemstr**
###### Description of changes

(okay attempt 3. I'm really sorry for the confusion from the last PR that requested a review from everyone. I can't git at the moment apparently)

I realised in https://github.com/NixOS/nixpkgs/pull/240189 I made some minor errors in the service definition. The webhook URL configuration option wasn't properly passed through to the systemd configuration, and we can use the better `types.str` type over `types.string`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabianhjr — APPROVED** [review]
Fixes a warning on `nixos-rebuild`

LGTM

**Review by Janik-Haag — COMMENTED** [review]
Can you add a test that would have caught this to `nixos/tests/n8n.nix`?

**Comment by gmemstr** [comment]
@Janik-Haag How would you recommend testing for something like this? I've gone through a few of the existing test files but I'm unsure how to test that the environment variable is correctly set in the systemd unit.

**Comment by Janik-Haag** [comment]
You can check if the string of `cfg.webhookUrl` is in the systemd file which gets placed in `/etc/systemd/system/`

**Comment by gmemstr** [comment]
Gave it my best shot :D Fairly straightforward

**Review by Janik-Haag — APPROVED** [review]
Noice, thanks for adding the testcase :D

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 241783` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 241783` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

**Pull request merged**
