### PR TITLE
minecraft-server: 1.14.4 -> 1.15.2

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

Switch to the latest version of `minecraft-server`: https://www.minecraft.net/en-us/download/server/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/78514)

### CODE REVIEW

**Review by tomberek — COMMENTED** [review]
Is the “nix-prefetch-url” in the url field a copy paste error or a feature I’m not aware of?

**Comment by Frostman** [comment]
@tomberek yeah, that's a copy-paste... Strange thing is that it works fine for me as I'm using it already. Pushed fixed commit.

**Comment by tomberek** [comment]
The builder for fetchurl does some parsing and splitting. Perhaps the first word got dropped somehow. Might be worth investigating.

**Review by tomberek — APPROVED** [review]
Builds and runs.

**Review by tomberek — APPROVED** [review]

**Pull request merged**
