### PR TITLE
ffmpeg_5: 5.0.1 -> 5.1

### PR DESCRIPTION
**Pull request by zowoq**
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/90810bb37cf7076074acf5a9c5a24feaaaf87bc9:/Changelog#l9

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
```
builder for '/nix/store/sihd6b4mnibpfr1rcjjp25plhshvw75d-ffmpeg-full-5.1.drv' failed with exit code 2; last 10 log lines:
  CC  tests/api/api-threadmessage-test.o
  STRIP      tests/checkasm/x86/checkasm.o
  skipping strip -x tests/checkasm/x86/checkasm.o
  CC    tests/api/api-flac-test.o
  CC  tests/api/api-seek-test.o
  HOSTCC      tests/audiogen.o
  HOSTCC       tests/videogen.o
  fate-imf-cpl-with-repeat requires external samples and SAMPLES not specified
  make: *** [tests/Makefile:285: fate-imf-cpl-with-repeat] Error 1
  make: *** Waiting for unfinished jobs....
```

**Comment by risicle** [comment]
Think we'll just have to delete the line https://github.com/FFmpeg/FFmpeg/blob/77b529fbd228fe30a870e3157f051885b436ad92/tests/Makefile#L201 in `postPatch` for now, will open an issue upstream. Looks like they've just missed this one in their mechanism that skips certain tests if `SAMPLES` isn't specified.

**Comment by risicle** [comment]
https://trac.ffmpeg.org/ticket/9841

**Comment by zowoq** [comment]
@ofborg build ffmpeg-full

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures, macos 10.15 & nixos x86_64

**Pull request merged**
