### PR TITLE
frostwire: mark broken

### PR DESCRIPTION
**Pull request by superherointj**
frostwire: mark broken
* error with changing hash

### CODE REVIEW

**Comment by figsoda** [comment]
> I don't know if this problem will come back.

well, i guess that answers your question

**Comment by superherointj** [comment]
> > I don't know if this problem will come back.
> 
> well, i guess that answers your question

That what? Did you reproduce the hash problem?

**Comment by figsoda** [comment]
ofborg ran into a hash mismatch

**Comment by superherointj** [comment]
> ofborg ran into a hash mismatch

I see. Mark broken then?

**Comment by figsoda** [comment]
seems like the only "solution" right now

**Review by figsoda — APPROVED** [review]

**Comment by superherointj** [comment]
Thanks!

**Pull request merged**
