### PR TITLE
Vulkan 1.3.268

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

Bumps everything to latest SDK. `vulkan-tools` currently broken on Darwin.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Tested everything affected on Linux on top of master and it builds fine. Darwin `vulkan-tools` patch needs a rebase.

**Comment by K900** [comment]
Force-pushed to fix vulkan-tools-lunarg.

**Comment by Ralith** [comment]
As discussed previously at length, we should stick to SDK versions.

**Comment by K900** [comment]
Renormalized everything to use SDK tags and updated to 1.2.268. @reckenrode wanted to handle vulkan-tools on Darwin and MoltenVK.

**Review by Ralith — APPROVED** [review]

**Review by PedroHLC — APPROVED** [review]

**Comment by K900** [comment]
Force pushed again because nix-update screwed up the hashes. Verified everything builds again.

**Comment by reckenrode** [comment]
I pushed a commit with the fixes to vulkan-tools on Darwin.

**Comment by reckenrode** [comment]
To clarify, the new SDK version is 1.**3**.268, right?

**Comment by K900** [comment]
Yes.

**Comment by PedroHLC** [comment]
Thanks for the hard work @K900 😊

**Pull request merged**
