### PR TITLE
nixos/httpd: rename apache log files to have a .log file extension

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
I'd like to be able to easily logrotate apache logs. Other main distros give their apache logs a .log file extension so easy logrotate rules can be written (like /var/log/httpd/*.log). Currently with the way virtual host logs are named there is no straight forward way to logrotate files.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
Discussion on discourse about moving to journald for apache logging, so putting this on hold for now.

**Comment by danbst** [comment]
Moving to journald is completely different issue (and, I'd say, optional one!). I'd merge this, but I wonder if it requires release notes.

Also, logrotate should understand `/var/log/httpd/*`, why not?

**Comment by aanderse** [comment]
@danbst sure logrotate understands it, but then logrotate will start rotating the rotation files as they end up in the same directory.

Yeah mod_journald isn't out until apache 2.5 and this change would sure make things better until then...

Let me write up some release notes mentioning the change in file names and we can leave the journald stuff alone until 2.5 is out.

Sound reasonable?

**Comment by danbst** [comment]
Oh, right, but what about `/var/log/httpd/*_log`?

> Sound reasonable?

yeah

**Comment by aanderse** [comment]
That doesn't account for virtual hosts as those log files don't end in _log but instead the host name.

**Comment by danbst** [comment]
oh crap. Ok then, waiting for release doc and then can be merged.

**Comment by aanderse** [comment]
@danbst let me know if this works for you. Thanks!

**Comment by danbst** [comment]
@aanderse thanks!

**Pull request merged**
