### PR TITLE
git: patch in completion scripts references to environment utilities

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

Prevent the Bash completion scripts from depending on command-line utilities from the environment.

This implementation utilize the existing Perl-based patching commands currently used to patch the git core scripts.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andersk** [comment]
This has regressed `git show <TAB>`:

```console
$ git show bash: local: `/nix/store/db6bfy1czsrfddhcb9xwcx9vb5aahv9c-coreutils-9.1/bin/ls': not a valid identifier
```

by breaking `__git_complete_revlist_file`:

```diff
 
 __git_complete_revlist_file ()
 {
-	local dequoted_word pfx ls ref cur_="$cur"
+	local dequoted_word pfx /nix/store/db6bfy1czsrfddhcb9xwcx9vb5aahv9c-coreutils-9.1/bin/ls ref cur_="$cur"
 	case "$cur_" in
 	*..?*:*)
 		return
```

That `ls` is a variable name, not a command.

**Comment by ShamrockLee** [comment]
@andersk Thank you for finding it out and sorry for the trouble.

I'll revert 820dc2a56057bcc396dbddbff6be91e1cec73f6f (the commit that adds `ls` to the list. I could hardly imagine an interactive CLI environment without `ls` anyway.

**Comment by ShamrockLee** [comment]
BTW, should the fix goes to staging as well?

**Comment by andersk** [comment]
My read of [RFC 26](https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md) is that `staging-next` may be appropriate for mass-rebuild regression fixes, but someone should feel free to correct me.

**Comment by ncfavier** [comment]
Would be nice to have a more robust solution than this dumb search-and-replace... Maybe modify PATH at the top of the scripts?

**Comment by ncfavier** [comment]
Then we may want to look at [patsh](https://github.com/nix-community/patsh) or [resholve](https://github.com/abathur/resholve).

**Comment by andersk** [comment]
It would be nice to separate the Git installed by users from the Git used only for build dependencies, anyway. This would allow us to provide much faster updates (including security updates) to the former without provoking mass rebuilds.

**Comment by vcunat** [comment]
By the naming, I wouldn't expect `gitMinimal` to have such luxuries like good shell completion.

**Comment by ShamrockLee** [comment]
BTW, why do we choose to patch the git core scripts by command name instead of prefixing the `PATH`?

**Comment by andersk** [comment]
Well a more general argument against prefixing `PATH` is that it would infect all subprocesses launched by Git, such as your editor for commit messages. A common annoyance for me is when various Nix wrappers insert a non-interactive `bash` into my `PATH` and break interactive shells launched from within other programs.

**Comment by ShamrockLee** [comment]
> patsh should be able to handle this, though it wouldn't work for `gitMinimal` because patsh depends on it through `rustPlatform.importCargoLock`

The last time I tried `patsh`, it doesn't work for commands after pipes (`|`).

**Pull request merged**
