### PR TITLE
pythonPackages.python-prctl: init at 1.7

### PR DESCRIPTION
**Pull request by catern**
###### Motivation for this change

I want to use this package.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg build pythonPackages.python-ptrcl python3Packages.python-ptrcl

**Comment by catern** [comment]
Sorry, typo'd in the commit message and PR name

**Comment by FRidh** [comment]
Rebase needed.

**Comment by ryantm** [comment]
@GrahamcOfBorg build python2.pkgs.python-ptrcl python3.pkgs.python-ptrcl

**Comment by ryantm** [comment]
@GrahamcOfBorg build python2.pkgs.python-prctl  python3.pkgs.python-prctl

**Review by ryantm — APPROVED** [review]
Looks good to me!

**Pull request merged**
