### PR TITLE
nixos/clamav: use StateDirectory to ensure creation

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

upon first starting clamav with the following settings
```
      clamav = {
        daemon.enable = true;
        updater.enable = true;
      };
```

I got the following error
```
ystemd[1]: Starting ClamAV daemon (clamd)...
ystemd[1]: Started ClamAV daemon (clamd).
lamd[3312752]: LibClamAV Error: cl_load(): No such file or directory: /var/lib/clamav
lamd[3312752]: ERROR: Can't get file status
ystemd[1]: clamav-daemon.service: Main process exited, code=exited, status=1/FAILURE
ystemd[1]: clamav-daemon.service: Failed with result 'exit-code'.
```

I'm not sure why StateDirectory isn't used here. That would ensure that the statedirectory is created before boot.

2. Another thing that I wanted to do was to make the user a dynamic user (I don't see a need IMO for creating a user and groupid here). However that would be a breaking change, so I'm refraining from doing that here and just seeing if anyone involved with the PR would be ok with it.
```

## Things done

<!-- Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers. -->

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

<!--
To help with the large amounts of pull requests, we would appreciate your
reviews of other pull requests, especially simple package updates. Just leave a
comment describing what you have tested in the relevant package/service.
Reviewing helps to reduce the average time-to-merge for everyone.
Thanks a lot if you do!

List of open PRs: https://github.com/NixOS/nixpkgs/pulls
Reviewing guidelines: https://nixos.org/manual/nixpkgs/unstable/#chap-reviewing-contributions
-->

### CODE REVIEW

**Comment by mweinelt** [comment]
I suspect that the clamav-daemon might want root access, but you could try `DynamicUser` and  `CAP_DAC_READ_OVERRIDE` instead.

**Comment by happysalada** [comment]
upon testing I realised that clamav-daemon also needs RuntimeDirectory.
I've added it to clamav-freshclam as well to keep the config exactly like it was before.
(we can remove it in another PR of course).
I've just tested this and it worked perfectly.
I had to `systemctl restart clamav-daemon` for the changes to actually take effect though.

**Comment by bjornfor** [comment]
Am I understanding this correctly?
* clamav is running as root but with /var/lib/clamav owned by the clamav user (in master branch)?
* This PR changes it to run as clamav user instead of root (and systemd automatically handles the /var/lib/clamav ownership)?

**Comment by happysalada** [comment]
@bjornfor this is also my understanding.
So far i havent gotten any errors running clamav with this configuration.

**Comment by bjornfor** [comment]
> @bjornfor this is also my understanding. So far i havent gotten any errors running clamav with this configuration.

Ok. Then I think the commit message should mention this. It's (IMHO) the bigger functional change than what mechanism is used to create the state directory. Or better, it should be two different commits.

**Comment by happysalada** [comment]
I understand your point, I've split it in 2 commits.
Let me know of course if I there is anything else.

**Comment by happysalada** [comment]
After reading the arch linux documentation https://wiki.archlinux.org/title/ClamAV, here is the tldr of what I learned.
- the clamav daemon is not supposed to run as root.
- The normal database of viruses is not enough, that is unfortunate.
- The scanning is supposed to be done by the user, and the thing doing the scanning needs to have the permissions and pass those with a file descriptor to the daemon.

I'm now more confident in this change.

**Pull request merged**
