### PR TITLE
odroid xu4: kernel + uboot + platform (should also work on xu3)

### PR DESCRIPTION
**Pull request by qknight**

### CODE REVIEW

**Comment by joachifm** [comment]
Ping

**Comment by qknight** [comment]
pong: what's up?

**Comment by joachifm** [comment]
Just wondering what the status is

**Comment by qknight** [comment]
i'm using this branch on two odroid xu4 boards. back in Dec 2015 i asked @viric to review and merge but it appears that there was no interest.

i could port this patch to master if anyone is interested in reviewing this and merging it later on.

**Comment by joachifm** [comment]
On Fri, Mar 4, 2016, at 01:54 AM, Joachim Schiele wrote:
> i'm using this branch on two odroid xu4 boards. back in Dec 2015 i asked
> @viric to review and merge but it appears that there was no interest.
> 
> i could port this patch to master if anyone is interested in reviewing
> this and merging it later on.
I can't give any useful feedback, but this sounds like a worthwhile
patch, would be too bad to see it go to waste.

**Comment by Shados** [comment]
I'd be interested in taking a look at it, as I have an odroid xu3 to test on.

**Comment by sorki** [comment]
Tried rebasing this onto master, getting infinite recursion http://lpaste.net/353456

I'm trying to do nixos-rebuild on your image with 15.09. I'm definitely interested in xu4 support as it's a quite powerful board for building nixos for armv7.

**Comment by sorki** [comment]
Rebased version 
https://github.com/sorki/nixpkgs/commit/f65f143c74b9a64eff17e56574639dc9bb06c4e1

No way to test as I need to figure out how to switch from 15.09 to master

**Comment by traverseda** [comment]
Bump

**Comment by sorki** [comment]
I have this running pretty fine now, I'm about to create my first pull requests to nixpkgs so I'll take look at this as wel.

**Comment by roosemberth** [comment]
Hi, what needs to be done to merge this?

**Comment by roosemberth** [comment]
Hi, what needs to be done to merge this?

**Comment by sorki** [comment]
I've updated this to 4.14 kernel which seems to run fine. Will rebase again to recent nixpkgs and publish this.

**Pull request closed without merging**
