### PR TITLE
awscli: upgrade to 1.7.32

### PR DESCRIPTION
**Pull request by ericbmerritt**
As a consequence this also upgrades bcdoc to 0.15.0 (single point upgrade) and botocore to 1.0.0b1.

### CODE REVIEW

**Comment by garbas** [comment]
looks like this breaks virtualenvwrapper

**Comment by ericbmerritt** [comment]
garbas

**Comment by garbas** [comment]
@ericbmerritt you can update PR and look what Travis rebuilds. you can also install ``nox`` and run ``nox-review wip --against origin/master`` command. it is what Travis does

**Comment by ericbmerritt** [comment]
@garbas that is very useful. Thank you.

**Comment by garbas** [comment]
if you get stuck, just ping me on irc and i'll try to help you. 

also once you get PR done please ping me via comment since github doesnt notify
when code changes.


--
Rok Garbas - http://www.garbas.si

**Comment by ericbmerritt** [comment]
Will do Rick. It may be a day or two before I can get back to this.

**Comment by lethalman** [comment]
Obsolete, nixpkgs has now 1.7.41. Closing, please reopen if needed.

**Pull request closed without merging**
