### PR TITLE
[20.09] ghc:8.10.2Binary bootstrap for 8.8 on aarch64 (NixOS#97407) #101214

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Fix the GHC build on aarch64-linux. Backport of #101214 

Refs #97407

Feel free to close if it's better merged via staging-20.09.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cdepillabout — APPROVED** [review]
@roberth Thanks for backporting this.

I'm fine with merging this in as-is, but on the previous PR, @vcunat recommended that it should be merged into `staging-next` instead of `master` because there were a huge backlog of aarch builds on hydra.

However, as of right now, there are only 420 packages in the backlog for aarch64 (on https://hydra.nixos.org/queue-summary):

image

@vcunat Is this a lot?  Or is 420 small?  Can this be merged directly into `release-20.09`?

**Comment by roberth** [comment]
Oddly, the https://hydra.nixos.org/queue-summary page doesn't show me a row for `aarch64-linux`.
@vcunat Did it change for you?

I'm also seeing a lot of aborted build like this https://hydra.nixos.org/build/129460097, so I'm not sure if those builds can even succeed at this time.

**Comment by vcunat** [comment]
It's empty now.   Partially thanks to many builds [being blocked](https://github.com/NixOS/nixos-org-configurations/issues/128) (including `staging-next`'s llvm and thus ghc).   So I guess it's convenient to utilize the window and binaries now, as ghc _itself_ shouldn't be blocked by that Hydra problem.

On this commit the build seems OK &ndash; on the community machine (someone's cached it there already).

**Comment by roberth** [comment]
It seems to be ok. My build agent is currently 18 drvs away from `cabal2nix` so I'm quite confident about this PR. It's definitely an improvement over the current state.

**Comment by vcunat** [comment]
OK, after fixing the missing maintainer it started to build: https://hydra.nixos.org/eval/1623733#tabs-unfinished

**Comment by vcunat** [comment]
Aah right, I forgot to check... we're back at the "Output limit exceeded" problem.

**Comment by roberth** [comment]
Stripping the docs and profiling from the bootstrapping compiler may work. https://github.com/NixOS/nixpkgs/pull/102504

The eventual compiler fits well within the limits.

**Comment by lostnet** [comment]
@roberth It still seems to be around the 2gb limit(?), but I think `*_p.a` files are for profiling with static linking, are larger than the dynamic libraries and could be removed at the same time.

**Comment by roberth** [comment]
That's what I did in https://github.com/NixOS/nixpkgs/pull/102504#issuecomment-721976049

**Pull request merged**
