### PR TITLE
ycmd: Init at 2016-01-12

### PR DESCRIPTION
**Pull request by rasendubi**
Tested on Linux.

### CODE REVIEW

**Comment by bjornfor** [comment]
Are you aware of the existing YouCompleteMe Vim plugin?

https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/default.nix#L879-L923

(I don't know how much overlap there is in these expressions.)

**Comment by rasendubi** [comment]
I know about vim youcompleteme plugin, but I want a standalone ycmd server to work with emacs. Unfortunately, I don't see a way to reuse the same nix-expression as vim plugin seem to hard-code ycmd location.

**Comment by bjornfor** [comment]
Ok, just checking :-)

**Comment by rasendubi** [comment]
The Travis build has timed out, but I don't understand what's the reason. Can someone help me out?

**Comment by lethalman** [comment]
Fails to build for me:
```
/nix/store/9ndszsw5gziw31xx9d9bc3bfxk1x5bmm-stdenv/setup: ./build.py: /usr/bin/env: bad interpreter: No such file or directory
```

Please make sure you enable nix chroot.

**Comment by rasendubi** [comment]
@lethalman could you please explain how can I do that? Can't google anything out.

**Comment by fpletz** [comment]
@rasendubi Just set `nix.useChroot = true` in your `confguration.nix`.

**Comment by rasendubi** [comment]
Thanks! Now fixed

**Comment by rasendubi** [comment]
Can this be merged now?

**Comment by fpletz** [comment]
Thanks!

**Comment by fpletz** [comment]
Had to push a fix for this as frozendict was added in the meantime: https://travis-ci.org/NixOS/nixpkgs/builds/103104625, fixed in ca3af3ce88b95f878f048c71285382de0da011a8

Rebasing to current master is always a good idea. :)

**Pull request merged**
