### PR TITLE
vimPlugins.vim-svelte: init at 2022-02-17, vimPlugins.coc-svelte: init at 2022-03-14, vimPlugins.coc-svelte: init at 2022-03-14

### LINKED ISSUE #154289: Add following vim plugins
**Project description**
Various vim plugins

* iamcco/coc-tailwindcss
* coc-extensions/coc-svelte
* evanleck/vim-svelte

### PR DESCRIPTION
**Pull request by pyrox0**
###### Description of changes
Fixes #154289. Also, how can I add myself to be a maintainer for the `vimPlugins` set?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 165948` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.mkdx</li>
    <li>vimPlugins.vim-clap</li>
  </ul>
</details>
<details>
  <summary>89 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.Navigator-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.coc-svelte</li>
    <li>vimPlugins.coc-tailwindcss</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.ctrlp-vim</li>
    <li>vimPlugins.dracula-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.embark-vim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.ghcid</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.hoon-vim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.onedark-vim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.papercolor-theme</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.typescript-vim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-dadbod</li>
    <li>vimPlugins.vim-endwise</li>
    <li>vimPlugins.vim-eunuch</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-obsession</li>
    <li>vimPlugins.vim-oscyank</li>
    <li>vimPlugins.vim-sleuth</li>
    <li>vimPlugins.vim-surround</li>
    <li>vimPlugins.vim-svelte</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-visual-multi</li>
    <li>vimPlugins.vim-xkbswitch</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Please rebase on master.

**Comment by ModdedGamers** [comment]
@SuperSandro2000 Done!

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 165948` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.coc-svelte</li>
    <li>vimPlugins.coc-tailwindcss</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.vim-svelte</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Pull request merged**
