### PR TITLE
nixos/tests/k3s: add a single-node docker test, tweak the existing test

### PR DESCRIPTION
**Pull request by euank**
###### Motivation for this change

There's a PR against k3s that I suspect might not play nice with docker (https://github.com/NixOS/nixpkgs/pull/134365).

Add a test so that we can do some minimal verification of PRs of that sort.

Also polish the existing test a little.

I'd still like a multi-node cluster test, but that'll come separately, and this seems reasonable to land in the meanwhile.

###### Things done

- [x] Tested via one or more NixOS tests: yes, they both pass

### CODE REVIEW

**Comment by euank** [comment]
I nixpkgs-fmt'd it too, so there's a bunch of whitespace changes. Apologies for all the extra noise here. The files are pretty short, so I think it's still reasonable readable.

**Review by roberth — COMMENTED** [review]
Some suggestions and ideas.

**Review by superherointj — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg eval
@ofborg test k3s

**Comment by zowoq** [comment]
`nixos/tests/all-tests.nix` needs to be updated when adding and removing tests.

The new tests were added to `all-tests.nix` in https://github.com/NixOS/nixpkgs/commit/fd6b95db2263e80269834e2508302de4aed025d7

Still need to remove the previous test:
https://github.com/NixOS/nixpkgs/blob/6c7fd66b5b60df3411a23b0df1de766d24df701d/nixos/tests/all-tests.nix#L240-L242

**Pull request merged**
