### PR TITLE
vagrant: 1.8.5 -> 1.8.6

### PR DESCRIPTION
**Pull request by kamilchm**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Thank you!

**Comment by peterhoeg** [comment]
@copumpkin, the vagrant project embeds a whole bunch of ruby gems instead of using the normal channels. From the installation guide:

```
Vagrant 1.0.x had the option to be installed as a RubyGem. 
This installation method is no longer supported.
```

**Comment by aneeshusa** [comment]
Vagrant still seems to [support building from source](https://github.com/mitchellh/vagrant#installing-the-gem-from-git), so I think the main reason is that no one has done the work to convert Vagrant to source-based installation. I'd love to see that, but I have ~0 Ruby knowledge.

**Comment by Mic92** [comment]
It seems doable, I can take a look at it.

**Comment by Mic92** [comment]
I hate vendoring and hashicorp software: https://github.com/mitchellh/vagrant-installers

**Comment by copumpkin** [comment]
Yeah, it's sad that so much of the world is moving in that direction.

**Comment by Mic92** [comment]
https://github.com/Mic92/nixpkgs/commit/18bfdcdc2a9f05bea357d0e353a3b652fbc1e9f7 <- this builds
and works to a certain point, but some dependencies (rubygems) may require a different version.

**Pull request merged**
