### PR TITLE
scli: 0.6.1 -> 0.6.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by ethancedwards8** [comment]
Result of `nixpkgs-review pr 127797` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>scli</li>
  </ul>
</details>

**Review by endocrimes — APPROVED** [review]
tested, works, diff lgtm

**Comment by dotlambda** [comment]
> works

Really? You didn't hit https://github.com/AsamK/signal-cli/issues/315?

**Comment by endocrimes** [comment]
@dotlambda weirdly, no, but my dbus setup is cursed (and i didn't go too deep into learning how it works beyond rudimentary can i get it to run)

**Comment by dotlambda** [comment]
@endocrimes If you feel like sharing the setup, I'd be interested.

**Comment by alexeyre** [comment]
this has been on my todo list for a bit but I've been a bit snowed under at work, thank you for getting round to it.

In regards to using ` { python3, ... }` as an argument and using `python3.pkgs`, I was specifically advised by @jonringer to not do that, and I'm a bit alarmed that you changed it back just for bumping the version number. Read the original PR for some more context: https://github.com/NixOS/nixpkgs/pull/122315

**Pull request merged**
