### PR TITLE
gnat-wrapper/cc-wrapper cleanup and fixes.

### PR DESCRIPTION
**Pull request by kquick**
###### Motivation for this change

Observation of https://github.com/NixOS/nixpkgs/pull/98274 which fixed the gnat issue I also encountered led to some additional cleanup and corner-case fixes in both the gnat-wrapper, the cc-wrapper, and the role.bash setup hook.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
     * Since this changes the core stdenv wrappers, everything rebuilds.  I've run several hundred package rebuilds, along with gcc/gnat builds, but don't have the machine power or time to wait for *every* package to rebuild.  :-)
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lucus16** [comment]
I must admit my understanding of these scripts do not go beyond "it works or it doesn't". I don't see anything problematic. Given you're changing cc-wrapper though, I believe this PR should target `staging` rather than `master`.

**Comment by kquick** [comment]
Good point.  I've opened https://github.com/NixOS/nixpkgs/pull/99027 against staging to replace this PR.

**Comment by Lucus16** [comment]
For future reference, you can change the target branch without creating a
new PR.

**Comment by kquick** [comment]
How?  I looked for a way to do that and didn't find anything, but I would have liked  to do that.

**Comment by Lucus16** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Pull request closed without merging**
