### PR TITLE
flameshot: 0.10.0 -> 0.10.1

### PR DESCRIPTION
**Pull request by chuahou**
###### Motivation for this change

Update flameshot from 0.10.0 to [0.10.1](https://github.com/flameshot-org/flameshot/releases/tag/v0.10.1), mainly containing quick patches and bugfixes.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Kranzes — APPROVED** [review]
Diff looks good.

**Comment by SebTM** [comment]
LGTM 👍🏻  (see #131610)

**Comment by chuahou** [comment]
I hope asking this isn't out of line—are there any more changes or things I could do to try and get this merged faster? Currently both 0.9.0 and 0.10.0 (on nixos-21.05 and nixpkgs-unstable respectively) are pretty critically broken, so I'd hope to merge this and then begin backporting to 21.05 sooner rather than later.

**Comment by Kranzes** [comment]
> I hope asking this isn't out of line—are there any more changes or things I could do to try and get this merged faster? Currently both 0.9.0 and 0.10.0 (on nixos-21.05 and nixpkgs-unstable respectively) are pretty critically broken, so I'd hope to merge this and then begin backporting to 21.05 sooner rather than later.

@SuperSandro2000

**Comment by Kranzes** [comment]
Thanks @SuperSandro2000 <3

**Pull request merged**
