### PR TITLE
python3Packages.pyflunearyou: switch to disabledTestPaths

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The home-assistant tests are failing now.

```
____________________________ test_step_user[pyloop] ____________________________
[gw15] linux -- Python 3.8.8 /nix/store/qc8pkj3ypmgs1izgq70z7p9vbzanxxbc-python3-3.8.8/bin/python3.8
hass = <homeassistant.core.HomeAssistant object at 0xffff50cfc220>
    async def test_step_user(hass):
        """Test that the user step works."""
        conf = {CONF_LATITUDE: "51.528308", CONF_LONGITUDE: "-0.3817765"}
    
        with patch(
            "homeassistant.components.flunearyou.async_setup_entry", return_value=True
        ), patch("pyflunearyou.cdc.CdcReport.status_by_coordinates"):
>           result = await hass.config_entries.flow.async_init(
                DOMAIN, context={"source": SOURCE_USER}, data=conf
            )
tests/components/flunearyou/test_config_flow.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
homeassistant/data_entry_flow.py:133: in async_init
    result = await self._async_handle_step(
homeassistant/data_entry_flow.py:216: in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <homeassistant.components.flunearyou.config_flow.FluNearYouFlowHandler object at 0xffff50e2fb20>
user_input = {'latitude': '51.528308', 'longitude': '-0.3817765'}
    async def async_step_user(self, user_input=None):
        """Handle the start of the config flow."""
        if not user_input:
            return self.async_show_form(step_id="user", data_schema=self.data_schema)
    
        unique_id = f"{user_input[CONF_LATITUDE]}, {user_input[CONF_LONGITUDE]}"
    
        await self.async_set_unique_id(unique_id)
        self._abort_if_unique_id_configured()
    
        websession = aiohttp_client.async_get_clientsession(self.hass)
>       client = Client(websession)
E       TypeError: __init__() takes 1 positional argument but 2 were given
homeassistant/components/flunearyou/config_flow.py:44: TypeError
```

```
__________________________ test_general_error[pyloop] __________________________
[gw15] linux -- Python 3.8.8 /nix/store/qc8pkj3ypmgs1izgq70z7p9vbzanxxbc-python3-3.8.8/bin/python3.8
hass = <homeassistant.core.HomeAssistant object at 0xffff50ca42e0>
    async def test_general_error(hass):
        """Test that an error is shown on a library error."""
        conf = {CONF_LATITUDE: "51.528308", CONF_LONGITUDE: "-0.3817765"}
    
        with patch(
            "pyflunearyou.cdc.CdcReport.status_by_coordinates",
            side_effect=FluNearYouError,
        ):
>           result = await hass.config_entries.flow.async_init(
                DOMAIN, context={"source": SOURCE_USER}, data=conf
            )
tests/components/flunearyou/test_config_flow.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
homeassistant/data_entry_flow.py:133: in async_init
    result = await self._async_handle_step(
homeassistant/data_entry_flow.py:216: in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <homeassistant.components.flunearyou.config_flow.FluNearYouFlowHandler object at 0xffff50c90100>
user_input = {'latitude': '51.528308', 'longitude': '-0.3817765'}
    async def async_step_user(self, user_input=None):
        """Handle the start of the config flow."""
        if not user_input:
            return self.async_show_form(step_id="user", data_schema=self.data_schema)
    
        unique_id = f"{user_input[CONF_LATITUDE]}, {user_input[CONF_LONGITUDE]}"
    
        await self.async_set_unique_id(unique_id)
        self._abort_if_unique_id_configured()
    
        websession = aiohttp_client.async_get_clientsession(self.hass)
>       client = Client(websession)
E       TypeError: __init__() takes 1 positional argument but 2 were given
homeassistant/components/flunearyou/config_flow.py:44: TypeError
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 117075` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.pyflunearyou</li>
    <li>python39Packages.pyflunearyou</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117075` at d6f7f8a3 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build (new failures):</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/7e32b1d8db0184366df05c3387c7f4d6">python38Packages.pyflunearyou</a></li></li>
    <li><a href="https://gist.github.com/af9faa452ed533d885e86e189b7b348d">python39Packages.pyflunearyou</a></li></li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Home-Assistant pins `pyflunearyou==1.0.7`, so we likely need an override inside home-assistant, if feasible.

**Comment by mweinelt** [comment]
@fabaff Can you push the override?

**Comment by fabaff** [comment]
> @fabaff Can you push the override?

Not, at the moment. `pyflunearyou` > 2.0 now uses poetry while older releases were setuptools-based. Need to figure out how this is handled or it's even possible and make sense.

**Comment by Mic92** [comment]
> > @fabaff Can you push the override?
> 
> Not, at the moment. `pyflunearyou` > 2.0 now uses poetry while older releases were setuptools-based. Need to figure out how this is handled or it's even possible and make sense.

Maybe using the wheel also would work? https://pypi.org/project/pyflunearyou/#files
It does not bundle pre-compiled files.

**Comment by dotlambda** [comment]
This has made it to master: c4b8252c7fb5fe112b54ff205699913c8271ef04 and 27cc2b105f94

**Pull request closed without merging**
