### PR TITLE
python3Packages.dm-tree: Fix build

### PR DESCRIPTION
**Pull request by Jingles52**
###### Description of changes

This fixes the build failure described in #210796, but `nixpkgs-review` shows that downstream dependencies still do not build. This is probably for unrelated causes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The commit message should read something like `python3Packages.dm-tree: Fix build`.

@ofborg build python3.pkgs.dm-tree

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 211301` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.distrax</li>
    <li>python310Packages.rlax</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.chex</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dm-env</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.flax</li>
    <li>python310Packages.optax</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.tensorflow-probability</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.trfl</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python311Packages.chex</li>
    <li>python311Packages.dm-env</li>
    <li>python311Packages.optax</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.dm-tree</li>
    <li>python311Packages.dm-tree</li>
  </ul>
</details>

**Comment by samuela** [comment]
nixpkgs-review failures look unrelated: https://gist.github.com/samuela/b26dd542a45daaf832d98e39aed38381

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 211301` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.distrax</li>
    <li>python310Packages.rlax</li>
  </ul>
</details>
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>python310Packages.chex</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.flax</li>
    <li>python310Packages.optax</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.tensorflow-probability</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.trfl</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python311Packages.chex</li>
    <li>python311Packages.optax</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.dm-env</li>
    <li>python310Packages.dm-tree</li>
    <li>python311Packages.dm-env</li>
    <li>python311Packages.dm-tree</li>
  </ul>
</details>

**Comment by samuela** [comment]
nixpkgs-review log with 938b7ae included: https://gist.github.com/samuela/fb3e446c281cf2b43b7fcc3b28658a16

**Pull request merged**
