### PR TITLE
libsForQt5.messagelib: add patch for compatibility with cmake 3.24

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
What a bad timing, right after the nodejs bump, now building qtwebengine in nixpkgs-review.

**Review by vcunat — APPROVED** [review]
`libsForQt5.mailcommon` builds for me.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 186967` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>akregator</li>
    <li>kaddressbook</li>
    <li>kmail</li>
    <li>kontact</li>
    <li>libsForQt512.akonadi-import-wizard</li>
    <li>libsForQt512.akonadiconsole</li>
    <li>libsForQt512.akregator</li>
    <li>libsForQt512.kaddressbook</li>
    <li>libsForQt512.kalarm</li>
    <li>libsForQt512.kdepim-addons</li>
    <li>libsForQt512.kmail</li>
    <li>libsForQt512.kontact</li>
    <li>libsForQt512.mailcommon</li>
    <li>libsForQt512.mbox-importer</li>
    <li>libsForQt512.messagelib</li>
    <li>libsForQt512.pim-data-exporter</li>
    <li>libsForQt514.akonadi-import-wizard</li>
    <li>libsForQt514.akonadiconsole</li>
    <li>libsForQt514.akregator</li>
    <li>libsForQt514.kaddressbook</li>
    <li>libsForQt514.kalarm</li>
    <li>libsForQt514.kdepim-addons</li>
    <li>libsForQt514.kmail</li>
    <li>libsForQt514.kontact</li>
    <li>libsForQt514.mailcommon</li>
    <li>libsForQt514.mbox-importer</li>
    <li>libsForQt514.messagelib</li>
    <li>libsForQt514.pim-data-exporter</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>libsForQt5.akonadi-import-wizard</li>
    <li>libsForQt5.akonadiconsole</li>
    <li>libsForQt5.akregator</li>
    <li>libsForQt5.kaddressbook</li>
    <li>libsForQt5.kalarm</li>
    <li>libsForQt5.kdepim-addons</li>
    <li>libsForQt5.kmail</li>
    <li>libsForQt5.kontact</li>
    <li>libsForQt5.mailcommon</li>
    <li>libsForQt5.mbox-importer</li>
    <li>libsForQt5.messagelib</li>
    <li>libsForQt5.pim-data-exporter</li>
  </ul>
</details>

**Comment by NickCao** [comment]
```
minQtVersion = "5.15";
broken = lib.versionOlder libsForQt5.qtbase.version minQtVersion;
```
Most of them should be correct, the first four evaluate correctly manually, maybe nixpkgs-review got it wrong.

**Pull request merged**
