### PR TITLE
webkitgtk 2.4: fixup build by using older icu again

### PR DESCRIPTION
**Pull request by jerith666**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Isn't webkitgtk 2.4 horribly insecure and unsupported? I was of the impression that we should be getting rid of it. @grahamc?

**Comment by vcunat** [comment]
Well, yes, migration away from it should be the first thing to try.   I think it's been discussed multiple times, e.g. in https://github.com/NixOS/nixpkgs/issues/18312

**Comment by jerith666** [comment]
Right -- when it was removed as a dependency of `eclipse` (in 49ea0e27363e5ab5cb3b4e86f6531e799e43dabd), I noticed because it significantly degraded the usability of its javadoc browsing.  I tried updating to a newer version at that point, but it didn't work.  So I'm just preserving the status quo here.  :-/

**Comment by bjornfor** [comment]
@jerith666: Perhaps we can tell eclipse to use $BROWSER instead?

**Comment by jerith666** [comment]
I've read https://www.eclipse.org/swt/faq.php, but still don't really understand if that's feasible or how eclipse finds and loads the webkitgtk library.  I would say that "remove eclipse dependency on webkitgtk24" should really be opened as a separate issue, though -- while webkitgtk24 remains in nixpkgs, I think it ought to build.  :)

**Comment by peterhoeg** [comment]
Using this version for an internal doc browser like eclipse does should be OK but having (multiple) mail clients and browsers exposed to the internet using this version makes me quite uneasy.

I'll merge this to fix the build for now but what is the proper way to mark the externally facing applications that depend on this? Just ```broken = true;``` ?

**Pull request merged**
