### PR TITLE
wrangler: 3.62.0 -> 3.66.0

### PR DESCRIPTION
**Pull request by ryand56**
## Description of changes

Diff: https://github.com/cloudflare/workers-sdk/compare/wrangler%403.62.0...wrangler%403.66.0
Changelog: https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.66.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ryand56** [comment]
Result of `nixpkgs-review pr 328855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wrangler</li>
  </ul>
</details>

**Review by dezren39 — APPROVED** [review]

**Comment by seanrmurphy** [comment]
Thanks for this @ryand56 - would you also like to become a maintainer? That way, there would be 3 folks maintaining this which is probably a good thing....

**Comment by ryand56** [comment]
> Thanks for this @ryand56 - would you also like to become a maintainer? That way, there would be 3 folks maintaining this which is probably a good thing....

Sure, I wouldn't mind maintaining this package :)

**Comment by seanrmurphy** [comment]
@ryand56 - I'm not exactly sure what the expectations of the commiters are here tbh, but perhaps it would be better if this comprised 2 commits, one with the commit message `wrangler: add maintainer ryand56` and the other one with the version bump.

Would you mind doing this? Thanks!

**Comment by ryand56** [comment]
Weird eval error? https://gist.github.com/GrahamcOfBorg/0096b791c888fa036cd6de74486f54b5

**Comment by ryand56** [comment]
@ofborg eval

**Comment by seanrmurphy** [comment]
Result of `nixpkgs-review pr 328855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wrangler</li>
  </ul>
</details>

**Review by seanrmurphy — APPROVED** [review]

**Comment by ryand56** [comment]
@seanrmurphy I updated the PR to version 3.66.0.

**Comment by seanrmurphy** [comment]
Result of `nixpkgs-review pr 328855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wrangler</li>
  </ul>
</details>

**Review by seanrmurphy — APPROVED** [review]

**Comment by seanrmurphy** [comment]
@ryand56 - I  guess it's not realistic to always keep nixpkgs up to date with wrangler - I think wrangler just moves a bit faster; I mentioned to @dezren39 that a reasonable solution might be to aim for say monthly updates on nixpkgs and, say, have a flake, perhaps on flakehub, which could be updated more frequently. Wdyt?

**Comment by ryand56** [comment]
> @ryand56 - I guess it's not realistic to always keep nixpkgs up to date with wrangler - I think wrangler just moves a bit faster; I mentioned to @dezren39 that a reasonable solution might be to aim for say monthly updates on nixpkgs and, say, have a flake, perhaps on flakehub, which could be updated more frequently. Wdyt?

Yeah, I agree, that would be way easier to maintain.

**Comment by seanrmurphy** [comment]
> > @ryand56 - I guess it's not realistic to always keep nixpkgs up to date with wrangler - I think wrangler just moves a bit faster; I mentioned to @dezren39 that a reasonable solution might be to aim for say monthly updates on nixpkgs and, say, have a flake, perhaps on flakehub, which could be updated more frequently. Wdyt?
> 
> Yeah, I agree, that would be way easier to maintain. I published a flake to flakehub already: https://flakehub.com/flake/ryand56/wrangler
> 
> Let me know if it looks good! I can also invite you both to contribute to it

Looks great! I'd be happy to contribute to this.

**Pull request merged**
