### PR TITLE
mime-types: drop, gentoo replaced it with mailcap, marked for removal

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
 https://github.com/cachix/nixpkgs-unfree-redistributable

https://packages.gentoo.org/packages/app-misc/mime-types

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by c0bw3b — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@jonringer can you take a look at this?

**Review by jonringer — APPROVED** [review]
diff LGTM

**Comment by jonringer** [comment]
since this change causes over 500 rebuilds, do you mind targeting the staging branch

```
# finding the common merge base will avoid pinging all CODEOWNERs
common=$(git merge-base origin/master origin/staging)
git rebase --onto=$common HEAD~1 # or however many commits you want to pull
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch

**Comment by jonringer** [comment]
looks like go uses this package

**Comment by SuperSandro2000** [comment]
> since this change causes over 500 rebuilds, do you mind targeting the staging branch
> 
> ```
> # finding the common merge base will avoid pinging all CODEOWNERs
> common=$(git merge-base origin/master origin/staging)
> git rebase --onto=$common HEAD~1 # or however many commits you want to pull
> git push .. ... --force
> ```
> 
> then change the base branch in the github PR from `master` -> `staging`
> 
> See [nixos.org/nixpkgs/manual/#submitting-changes-staging-branch](https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch) for more details on staging branch

That wasn't working because the merge conflict is/was on staging.

**Comment by SuperSandro2000** [comment]
> looks like go uses this package

go is already using mailcap, yes. They are technically mostly identically and mime-types can be replaced with mailcap. The only difference is that mailcap is more up to date and also has two or three other files.

**Review by nlewo — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
LGTM

doing a quick scan of `rg mime-types` I think you got all of the references. Hard to tell with all of the auto-generated lock files

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 156082 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>go</li>  </ul></details>

**Pull request merged**
