### PR TITLE
wasmtime: 0.1.0 -> 20190521

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

Update to latest unstable. The 0.1.0 version used by the previous version of the package was incorrect, as that's just a placeholder that Cargo adds by default.

Spoke to one of the maintainers and they've made no releases to date, and he mentioned that now would be a good time to package since things are relatively stable.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build wasmtime

**Comment by nomeata** [comment]
I found that this version regresses in how `wasmtime` handles trapping code. Before it said:
```
error while processing main module _out/issue36.wasm: Instantiation error: Trap occurred while invoking start function: wasm trap at 0x___:
```
and afterwards it said
```
thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I guess I shouldn’t report this bug here, but maybe someone would mind bumping `wasmtime` to a newer version so that I can see if these problems disappear?

Also, the darwin build fails, but that is not a regression over the previous version bump here.

**Comment by nomeata** [comment]
Latest `wasmtime` `master` has fixed this:
```
error: failed to process main module `_out/issue36.wasm`
    caused by: Instantiation error: Trap occurred while invoking start function: wasm trap: unreachable, source location: @2eb9
```
I will see if I upgrade nixpkgs and maybe provide a patch.

**Comment by nomeata** [comment]
It has, but the `darwin` build still fails
```
  = note: Undefined symbols for architecture x86_64:
            "_utimensat", referenced from:
                wasi_common::sys::unix::hostcalls_impl::fs::path_filestat_set_times::h9202e1bd89d768f0 in wasi_common-373cfd6ebb1545cd.wasi_common.av4m7sfr-cgu.5.rcgu.o
            "_futimens", referenced from:
                wasi_common::sys::unix::hostcalls_impl::fs::fd_filestat_set_times::hd2eb8b4bd780a131 in wasi_common-373cfd6ebb1545cd.wasi_common.av4m7sfr-cgu.5.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nomeata** [comment]
> I will see if I upgrade nixpkgs and maybe provide a patch.

https://github.com/NixOS/nixpkgs/pull/71316

**Pull request merged**
