### PR TITLE
thunderbird: clean up, make flags closer to default, official branding

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Clean up derivation, strip away flags that upstream is not happy with (such as `--disable-alsa`), enable official Thunderbird branding.

Superset of #38943, #36449.

cc @jerith666 @vcunat

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
@sylvestre: Could you look at this again?

Section with flags is: https://github.com/NixOS/nixpkgs/blob/37e8462c4d1a4714cf2013c85f6f66f4abfd01d2/pkgs/applications/networking/mailreaders/thunderbird/default.nix#L96-L122

This has been largely based off Debian mozconfig. We can't run tests since all builds are sandboxed, and system libs contain Nix-specific patches.

**Comment by ryantm** [comment]
@yegortimoshenko Is this waiting on review from Mozilla?

**Comment by vcunat** [comment]
@ryantm: the `enableOfficialBranding ? true` part should work for them, I believe.  The rest can most likely be done independently.

**Comment by lovesegfault** [comment]
I suggest this be superseded by #75328

**Comment by ryantm** [comment]
Sure. yegortimoshenko can always reopen if he disagrees.

**Comment by vcunat** [comment]
We did not advance the issue **branding** by default. @sylvestre: can you suggest how to proceed with that?  (I.e. whether it's OK or what's the problem with our current state.  Or how to find this out.)

**Comment by jerith666** [comment]
for the record, official branding was enabled in #94880.

**Comment by sylvestre** [comment]
@jerith666 could you please tell me who reviewed the nix patches on top of tb?
Thanks

**Comment by jerith666** [comment]
I don't know -- I only noticed #94880 because I had official branding enabled locally and got a merge conflict with it.  You've already commented on #94880 so I think you probably know more than I do.  :)

**Pull request closed without merging**
