### PR TITLE
apache-httpd: 2.4.28 -> 2.4.29

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
latest minor of 2.4

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
The [travis error](https://travis-ci.org/NixOS/nixpkgs/jobs/291657625#L8410) is weird and I get another error trying to build `perlPackages.ApacheTest`:

```
…
cp lib/Apache/TestConfigParrot.pm blib/lib/Apache/TestConfigParrot.pm
cp lib/Apache/TestPerlDB.pm blib/lib/Apache/TestPerlDB.pm
cp lib/Apache/Test5005compat.pm blib/lib/Apache/Test5005compat.pm
Manifying 15 pod documents
running tests
"/nix/store/raylbbdkg4yz21c44fwcv63bzvj7a1i1-perl-5.24.2/bin/perl" -Iblib/arch -Iblib/lib \
t/TEST  -clean
[warning] setting ulimit to allow core files
ulimit -c unlimited; /nix/store/raylbbdkg4yz21c44fwcv63bzvj7a1i1-perl-5.24.2/bin/perl /tmp/nix-build-perl-Apache-Test-1.40.drv-0/Apache-Test-1.40/t/TEST -clean
Use of uninitialized value $proto in socket at lib/Apache/TestServer.pm line 383.
make: *** [Makefile:973: test_clean] Error 2
builder for ‘/nix/store/9gw0rxighxfj18rmpkv45iaxad2h1ycl-perl-Apache-Test-1.40.drv’ failed with exit code 2
error: build of ‘/nix/store/9gw0rxighxfj18rmpkv45iaxad2h1ycl-perl-Apache-Test-1.40.drv’ failed
```

**Comment by efx** [comment]
Odd, I'm testing now with sandbox enabled using the appliance linked from https://nixos.org/nixos/download.html

**Comment by efx** [comment]
So it looks like the errror comes from this line: https://metacpan.org/source/SHAY/Apache-Test-1.40/lib/Apache/TestServer.pm#L383. I've reproduced the fatal by running `nix-shell -p gzip --run "nix-env -f https://github.com/NixOS/nixpkgs/archive/master.tar.gz -iA perlPackages.libapreq2"` from within a docker container. The error looks like it is unable to spin up a test server or something. I think this issue may have been lurking in master and not necessarily related to the bump to 2.4.29. I am going to see about a patch or something.

**Comment by globin** [comment]
Merged since this failure already exists on master and shouldn't block this, but feel free to fix this nonetheless :)

**Pull request merged**
