### PR TITLE
vector: 0.34.2 → 0.35.0

### PR DESCRIPTION
**Pull request by jpds**
## Description of changes

- https://vector.dev/releases/0.35.0/

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
hey, I've converted this to draft because I noticed a linux ofborg failure and wanted this to not be merged wrongfully.
doing a brief check, this looks likes some jemalloc related error ?
Are you interested in trying to understand and fix the issue ? (just wondering, no problem either way).

**Comment by jpds** [comment]
Not sure what's happening there - I did another build on a separate box with:

```
$ nix build -I nixpkgs=channel:nixos-unstable --impure --expr "with import <nixpkgs> {}; callPackage ./nixpkgs/pkgs/tools/misc/vector/default.nix { CoreServices = null; Security = null; rust-jemalloc-sys = null; SystemConfiguration = null; }"
```

...and that succeeded. Just rebase'd `master` on top in case it was a transitory blip.

**Comment by jpds** [comment]
Commented out the change from https://github.com/vectordotdev/vector/pull/19340 and it built locally.

**Comment by happysalada** [comment]
alright, I've got it to compile on local by replacing
rust-jemalloc-sys with , rust-jemalloc-sys-unprefixed
with that change, no patch is needed, do you want to test that on your end too to make sure I'm not halucinating ?
if the change works for you, feel free to push that and I can run nixpkgs-review on the PR.

**Comment by lblasc** [comment]
Master is now using rustc 1.75 which brakes vector build, I've extracted relevant changes from upstream PR https://github.com/vectordotdev/vector/pull/19518, feel free to cherry-pick https://github.com/tvbeat/nixpkgs/commit/a1104bbb559cd72aea3cbc0ec6472605098fd87a

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 280027` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vector</li>
  </ul>
</details>

**Comment by happysalada** [comment]
thank you both!

**Pull request merged**
