### PR TITLE
gitlab: 14.1.2 -> 14.2.1

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
Update GitLab to the latest version.

###### Notable packaging changes
- The `grpc` patch used for the `gitlab` and `gitaly` packages is removed, since the problem is fixed upstream
- `gitlab-workhorse` changed its binary name to `workhorse` (see https://gitlab.com/gitlab-org/gitlab/-/merge_requests/65593)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
There's something wrong with 14.2.x:

screenshot1

```
Sep 03 08:38:16 nixos gitaly[964]: time="2021-09-03T08:38:16Z" level=error msg="finished streaming call with code Unknown" branch_name="[109 97 115 116 101 114]" command.count=4 command.inblock=0 command.majflt=0 command.maxrss=40516 command.minflt=594 command.oublock=0 command.real_time_ms=11 command.system_time_ms=9 command.user_time_ms=0 correlation_id=01FENCXYNVWZWHHWJMTRVT9Q10 error="commit: GitCommand: start [/nix/store/vrz93bnflsblfkq637d56fwd3zjhwbvw-gitaly-14.2.1/bin/gitaly-git2go- commit]: fork/exec /nix/store/vrz93bnflsblfkq637d56fwd3zjhwbvw-gitaly-14.2.1/bin/gitaly-git2go-: no such file or directory" force=false grpc.code=Unknown grpc.meta.auth_version=v2 grpc.meta.client_name=gitlab-web grpc.meta.deadline_type=regular grpc.meta.method_type=client_stream grpc.method=UserCommitFiles grpc.request.deadline="2021-09-03T08:39:11.049Z" grpc.request.fullMethod=/gitaly.OperationService/UserCommitFiles grpc.service=gitaly.OperationService grpc.start_time="2021-09-03T08:38:16.749Z" grpc.time_ms=83.756 peer.address=@ pid=964 remote_ip=127.0.0.1 repository_relative_path=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git repository_storage=default span.kind=server start_branch_name="[109 97 115 116 101 114]" start_repository_relative_path=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git start_repository_storage=default start_sha= system=grpc username=root
```

screenshot1


```
Sep 03 08:34:34 nixos puma[2075]: I, [2021-09-03T08:34:34.041274 #2075]  INFO -- : Completed 500 Internal Server Error in 739ms (ActiveRecord: 100.9ms | Elasticsearch: 0.0ms | Allocations: 45149)
Sep 03 08:34:34 nixos puma[2075]: F, [2021-09-03T08:34:34.051437 #2075] FATAL -- :
Sep 03 08:34:34 nixos puma[2075]: GRPC::Internal (13:13:GitCommand: start [/nix/store/vrz93bnflsblfkq637d56fwd3zjhwbvw-gitaly-14.2.1/bin/gitaly-git2go- conflicts -request eyJyZXBvc2l0b3J5IjoiL3Zhci9naXRsYWIvc3RhdGUvcmVwb3NpdG9yaWVzL0BoYXNoZWQvZDQvNzMvZDQ3MzVlM2EyNjVlMTZlZWUwM2Y1OTcxOGI5YjVkMDMwMTljMDdkOGI2YzUxZjkwZGEzYTY2NmVlYzEzYWIzNS5naXQiLCJvdXJzIjoiZGI3YzhhZDRiOGU5MzE2NGRkODBmZTlkZmQ1YzE3MzkzMjBjMzRiNiIsInRoZWlycyI6IjAxM2MzMzA5M2YxOTBhMDllNzY4NWRlMGJkNjdmMDBkMzllZjZlOWIifQ==]: fork/exec /nix/store/vrz93bnflsblfkq637d56fwd3zjhwbvw-gitaly-14.2.1/bin/gitaly-git2go-: no such file or directory. debug_error_string:{"created":"@1630658074.002399648","description":"Error received from peer unix:/var/gitlab/state/tmp/sockets/gitaly.socket","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"GitCommand: start [/nix/store/vrz93bnflsblfkq637d56fwd3zjhwbvw-gitaly-14.2.1/bin/gitaly-git2go- conflicts -request eyJyZXBvc2l0b3J5IjoiL3Zhci9naXRsYWIvc3RhdGUvcmVwb3NpdG9yaWVzL0BoYXNoZWQvZDQvNzMvZDQ3MzVlM2EyNjVlMTZlZWUwM2Y1OTcxOGI5YjVkMDMwMTljMDdkOGI2YzUxZjkwZGEzYTY2NmVlYzEzYWIzNS5naXQiLCJvdXJzIjoiZGI3YzhhZDRiOGU5MzE2NGRkODBmZTlkZmQ1YzE3MzkzMjBjMzRiNiIsInRoZWlycyI6IjAxM2MzMzA5M2YxOTBhMDllNzY4NWRlMGJkNjdmMDBkMzllZjZlOWIifQ==]: fork/exec /nix/store/vrz93bnflsblfkq637d56fwd3zjhwbvw-gitaly-14.2.1/bin/gitaly-git2go-: no such file or directory","grpc_status":13}):
```

Unless someone can figure it out, I would suggest we revert to 14.1.x and package 14.1.4 instead.

**Comment by dasJ** [comment]
I have just the hack for you…

Add this to your gitaly `postInstall`:
```
mv $out/bin/gitaly-git2go $out/bin/gitaly-git2go-
```

**Comment by yu-re-ka** [comment]
The git2go binary problem is most likely caused by this upstream change:
https://gitlab.com/gitlab-org/gitaly/-/commit/e7f8fe4f6759669c24b2fd216beaab4a477c5b3d

I'll try your workaround and if that turns out to be the only issue we can find a proper fix for it without reverting to 14.1.x.

**Comment by talyz** [comment]
I've created #136569, which should be a slightly more proper fix for the issue. As a bonus, it also makes gitaly report its version correctly.

**Pull request merged**
