### PR TITLE
whipper: fix

### LINKED ISSUE #124745: whipper is broken on nixos-unstable
**Describe the bug**
`whipper cd info` throws an error when attempting to generate the musicbrainz disc id:
```
Traceback (most recent call last):
  File "/nix/store/gpi71wal8fckk9i35islgjibx42ksi0p-whipper-0.10.0/bin/.whipper-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/gpi71wal8fckk9i35islgjibx42ksi0p-whipper-0.10.0/lib/python3.8/site-packages/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/nix/store/gpi71wal8fckk9i35islgjibx42ksi0p-whipper-0.10.0/lib/python3.8/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/nix/store/gpi71wal8fckk9i35islgjibx42ksi0p-whipper-0.10.0/lib/python3.8/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/nix/store/gpi71wal8fckk9i35islgjibx42ksi0p-whipper-0.10.0/lib/python3.8/site-packages/whipper/command/cd.py", line 116, in do
    self.mbdiscid = self.ittoc.getMusicBrainzDiscId()
  File "/nix/store/gpi71wal8fckk9i35islgjibx42ksi0p-whipper-0.10.0/lib/python3.8/site-packages/whipper/image/table.py", line 368, in getMusicBrainzDiscId
    from discid import put
ModuleNotFoundError: No module named 'discid'
```

**Notify maintainers**
@bjornfor recently updated the package in #123387
@emilazy listed as maintainer

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: whipper
```

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
fixes https://github.com/NixOS/nixpkgs/issues/124745

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124747` at fcbeecfc run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>whipper</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `util-linux`.
Near pkgs/applications/audio/whipper/default.nix:9:3:
```
  |
9 | , util-linux
  |   ^
```
</li>
  </ul>
</details>

**Review by bjornfor — APPROVED** [review]

**Review by jansol — APPROVED** [review]
`cd info` and `cd rip` completed successfully

**Comment by bjornfor** [comment]
Thanks @dotlambda!

**Comment by jansol** [comment]
Thanks for the quick fix!

**Pull request merged**
