### PR TITLE
python3Packages.phonenumbers: 8.12.25 -> 8.12.26

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 8.12.26

- Enable tests
- Run `nixpkgs-fmt`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 129545` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mautrix-signal</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>hydrus</li>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>python38Packages.httmock</li>
    <li>python38Packages.phonenumbers</li>
    <li>python39Packages.httmock</li>
    <li>python39Packages.phonenumbers</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129545` at ea12772d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/02e9355169334d2c569ee52267c0672a">mautrix-signal</a></li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>hydrus</li>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>python38Packages.httmock</li>
    <li>python38Packages.phonenumbers</li>
    <li>python39Packages.httmock</li>
    <li>python39Packages.phonenumbers</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/129545

1 package failed to build:
mautrix-signal

7 packages built:
hydrus matrix-synapse matrix-synapse-plugins.matrix-synapse-mjolnir-antispam python38Packages.httmock python38Packages.phonenumbers python39Packages.httmock python39Packages.phonenumbers
```

**Comment by jonringer** [comment]
hmm, do you mind dropping the httmock changes?

**Comment by fabaff** [comment]
> hmm, do you mind fixing the httmock conflicts?

Thanks for checking. That changes ended in this PR by accident.

**Pull request merged**
