### PR TITLE
libvirt: 5.4.0 -> 5.6.0

### PR DESCRIPTION
**Pull request by volth**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build libvirt
@GrahamcOfBorg build libguestfs
@GrahamcOfBorg build python2Packages.libvirt
@GrahamcOfBorg build python3Packages.libvirt
@GrahamcOfBorg build perl528Packages.SysVirt
@GrahamcOfBorg build perl530Packages.SysVirt

**Comment by risicle** [comment]
`nix-review` is happy for me apart from packages that are already failing on the parent commit. Non-nixos linux x86_64

**Comment by risicle** [comment]
Same goes for macos 10.13

**Comment by volth** [comment]
On NixOS it works

**Comment by volth** [comment]
One of the servers halts during boot after this upgrade, I suspect something with `virbr0` settings, but it is difficult to debug because the server has no IPMI.
So i just downgraded via `initrd-ssh`

**Comment by risicle** [comment]
Oh, so are we just going to stay at 5.4.0 forever then?

**Comment by Izorkin** [comment]
I have freezes when I reboot the server:
```
[  OK  ] Started DHCP Client.
[     *] A start job is running for Bridge Interface br0 (38s / no limit)
```
Error startup bridge interface.

**Comment by Izorkin** [comment]
Error start this script nixos/modules/tasks/network-interfaces-scripted.nix
```
              ${optionalString config.virtualisation.libvirtd.enable ''
                  # Enslave dynamically added interfaces which may be lost on nixos-rebuild
                  for uri in qemu:///system lxc:///; do
                    for dom in $(${pkgs.libvirt}/bin/virsh -c $uri list --name); do
                      ${pkgs.libvirt}/bin/virsh -c $uri dumpxml "$dom" | \
                      ${pkgs.xmlstarlet}/bin/xmlstarlet sel -t -m "//domain/devices/interface[@type='bridge'][source/@bridge='${n}'][target/@dev]" -v "concat('ip link set ',target/@dev,' master ',source/@bridge,';')" | \
                      ${pkgs.bash}/bin/bash
                    done
                  done
                ''}
```

```
авг 26 11:13:47 elven.pw b0x3dh2lkvr0g9yr282kh1x1a1lnqbmh-unit-script-br0-netdev-start[4669]: ошибка: не удалось подключиться к гипервизору
авг 26 11:13:47 elven.pw b0x3dh2lkvr0g9yr282kh1x1a1lnqbmh-unit-script-br0-netdev-start[4669]: ошибка: Cannot recv data: Connection reset by peer
```

**Comment by wedens** [comment]
Are there any similar issues when using networkd?

**Comment by Izorkin** [comment]
@volth is this an variant will fit?
```
diff --git a/nixos/modules/tasks/network-interfaces-scripted.nix b/nixos/modules/tasks/network-interfaces-scripted.nix
index 1726d05115e..f10b831b429 100644
--- a/nixos/modules/tasks/network-interfaces-scripted.nix
+++ b/nixos/modules/tasks/network-interfaces-scripted.nix
@@ -289,17 +289,6 @@ let
                 ${i}
               '')}" > /run/${n}.interfaces

-              ${optionalString config.virtualisation.libvirtd.enable ''
-                  # Enslave dynamically added interfaces which may be lost on nixos-rebuild
-                  for uri in qemu:///system lxc:///; do
-                    for dom in $(${pkgs.libvirt}/bin/virsh -c $uri list --name); do
-                      ${pkgs.libvirt}/bin/virsh -c $uri dumpxml "$dom" | \
-                      ${pkgs.xmlstarlet}/bin/xmlstarlet sel -t -m "//domain/devices/interface[@type='bridge'][source/@bridge='${n}'][target/@dev]" -v "concat('ip link set ',target/@dev,' master ',source/@bridge,';')" | \
-                      ${pkgs.bash}/bin/bash
-                    done
-                  done
-                ''}
-
               # Enable stp on the interface
               ${optionalString v.rstp ''
                 echo 2 >/sys/class/net/${n}/bridge/stp_state
@@ -328,6 +317,17 @@ let
                 ${i}
               '')}" > /run/${n}.interfaces

+              ${optionalString config.virtualisation.libvirtd.enable ''
+                  # Enslave dynamically added interfaces which may be lost on nixos-rebuild
+                  for uri in qemu:///system lxc:///; do
+                    for dom in $(${pkgs.libvirt}/bin/virsh -c $uri list --name); do
+                      ${pkgs.libvirt}/bin/virsh -c $uri dumpxml "$dom" | \
+                      ${pkgs.xmlstarlet}/bin/xmlstarlet sel -t -m "//domain/devices/interface[@type='bridge'][source/@bridge='${n}'][target/@dev]" -v "concat('ip link set ',target/@dev,' master ',source/@bridge,';')" | \
+                      ${pkgs.bash}/bin/bash
+                    done
+                  done
+                ''}
+
               # (Un-)set stp on the bridge
               echo ${if v.rstp then "2" else "0"} > /sys/class/net/${n}/bridge/stp_state
             '';

```

**Pull request closed without merging**
