### PR TITLE
python3Packages.slackclient: disable tests on darwin

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
https://hydra.nixos.org/build/157250130

#144627

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by misuzu** [comment]
@GrahamcOfBorg eval

**Comment by misuzu** [comment]
@GrahamcOfBorg build python3Packages.slackclient

**Comment by risicle** [comment]
I still get webhook tests failing on macos 10.15, e.g. `TestWebhook.test_send_attachments`:

```
...
>               return self._sock.recv_into(b)
E               ConnectionResetError: [Errno 54] Connection reset by peer

/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/socket.py:669: ConnectionResetError
----------------------------- Captured stderr call -----------------------------
127.0.0.1 - - [06/Nov/2021 13:36:35] "POST / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51525)
Traceback (most recent call last):
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/nix/store/9h7xr11my83hh41m5p1cidnjywa67i2p-python3-3.8.12/lib/python3.8/http/server.py", line 416, in handle_one_request
    self.wfile.flush() #actually send the response if not already done.
ValueError: I/O operation on closed file.
----------------------------------------
------------------------------ Captured log call -------------------------------
2021-11-06 13:36:35 DEBUG Sending a request - url: http://localhost:8888, body: {"text": "hello!", "attachments": [{"color": "#f2c744", "blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"}}, {"type": "divider"}, {"type": "section", "text": {"type": "mrkdwn", "text": "Pick a date for the deadline."}, "accessory": {"type": "datepicker", "initial_date": "1990-04-28", "placeholder": {"type": "plain_text", "text": "Select a date"}}}]}], "response_type": "ephemeral"}, headers: {'Content-Type': 'application/json;charset=utf-8', 'User-Agent': 'Python/3.8.12 slackclient/2.9.3 Darwin/19.6.0'}
2021-11-06 13:36:35 ERROR Failed to send a request to Slack API server: [Errno 54] Connection reset by peer
```

**Comment by risicle** [comment]
It looks like this issue is not completely unknown upstream: https://github.com/slackapi/python-slack-sdk/issues/808

**Comment by misuzu** [comment]
> I still get webhook tests failing on macos 10.15, e.g. `TestWebhook.test_send_attachments`:

Yeah, they all seem flaky on darwin. Disabled tests entirely.

**Comment by risicle** [comment]
I haven't seen any failures of the _unit_ tests on darwin and those would give at least some coverage.

**Comment by jonringer** [comment]
does this need `__darwinAllowLocalNetworking = true;`?

**Comment by risicle** [comment]
I'm not sure it'll make any difference, I'm not even building with the sandbox.

**Comment by misuzu** [comment]
Result of `nixpkgs-review pr 144840` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>opsdroid</li>
    <li>python38Packages.slackclient</li>
    <li>python39Packages.slackclient</li>
  </ul>
</details>

**Comment by misuzu** [comment]
@GrahamcOfBorg build python3Packages.slackclient

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 144840` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 144840` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>opsdroid</li>
    <li>python38Packages.slackclient</li>
    <li>python39Packages.slackclient</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
