### PR TITLE
imagemagick: 7.1.1-30 -> 7.1.1-32

### PR DESCRIPTION
**Pull request by trofi**
Changes:
- https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.1-31
- https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.1-32

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by uncenter** [comment]
https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.1-32 was just released yesterday by the way, we can update to that instead of 7.1.1-31?

**Comment by trofi** [comment]
Sounds good. Updated to `7.1.1-32`.

**Comment by uncenter** [comment]
Result of `nixpkgs-review pr 307309` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>68 packages marked as broken and skipped:</summary>
  <ul>
    <li>almanah</li>
    <li>arcan</li>
    <li>blockbench</li>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>calibre</li>
    <li>enigma</li>
    <li>farge</li>
    <li>fgallery</li>
    <li>fontpreview</li>
    <li>freedroid</li>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>gimp-with-plugins</li>
    <li>gscan2pdf</li>
    <li>gscan2pdf.man</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>mate.caja-extensions</li>
    <li>mate.mate-utils</li>
    <li>mojave-gtk-theme</li>
    <li>nulloy</li>
    <li>openspades</li>
    <li>perl536Packages.Gtk3ImageView</li>
    <li>perl536Packages.Gtk3ImageView.devdoc</li>
    <li>perl536Packages.ImageOCRTesseract</li>
    <li>perl536Packages.ImageOCRTesseract.devdoc</li>
    <li>perl536Packages.NetCUPS</li>
    <li>perl536Packages.NetCUPS.devdoc</li>
    <li>perl538Packages.Gtk3ImageView</li>
    <li>perl538Packages.Gtk3ImageView.devdoc</li>
    <li>perl538Packages.ImageOCRTesseract</li>
    <li>perl538Packages.ImageOCRTesseract.devdoc</li>
    <li>perl538Packages.NetCUPS</li>
    <li>perl538Packages.NetCUPS.devdoc</li>
    <li>pict-rs</li>
    <li>portmod</li>
    <li>portmod.dist</li>
    <li>python311Packages.llama-index-readers-s3</li>
    <li>python311Packages.llama-index-readers-s3.dist</li>
    <li>python311Packages.pytikz-allefeld</li>
    <li>python311Packages.pytikz-allefeld.dist</li>
    <li>python311Packages.qtile-extras</li>
    <li>python311Packages.qtile-extras.dist</li>
    <li>python312Packages.llama-index-readers-s3</li>
    <li>python312Packages.llama-index-readers-s3.dist</li>
    <li>python312Packages.pytikz-allefeld</li>
    <li>python312Packages.pytikz-allefeld.dist</li>
    <li>python312Packages.qtile-extras</li>
    <li>python312Packages.qtile-extras.dist</li>
    <li>rcu</li>
    <li>remmina</li>
    <li>rofi-screenshot</li>
    <li>rtfm</li>
    <li>shutter</li>
    <li>toppler</li>
    <li>unbook</li>
    <li>variety</li>
    <li>variety.dist</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
    <li>xarcan</li>
    <li>xyce</li>
    <li>xyce-parallel</li>
    <li>xyce-parallel.doc</li>
    <li>xyce.doc</li>
    <li>yosys-bluespec</li>
    <li>yubikey-personalization-gui</li>
  </ul>
</details>
<details>
  <summary>324 packages failed to build:</summary>
  <ul>
    <li>advi</li>
    <li>apkleaks</li>
    <li>apkleaks.dist</li>
    <li>asc-key-to-qr-code-gif</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>asymptote</li>
    <li>asymptote.doc</li>
    <li>asymptote.info</li>
    <li>asymptote.man</li>
    <li>asymptote.tex</li>
    <li>auto-multiple-choice</li>
    <li>autotrace</li>
    <li>ballerburg</li>
    <li>beamerpresenter (beamerpresenter-mupdf)</li>
    <li>bite</li>
    <li>blahtexml</li>
    <li>blahtexml.doc</li>
    <li>blockhash</li>
    <li>btc-rpc-explorer</li>
    <li>cadzinho</li>
    <li>calibre-web</li>
    <li>calibre-web.dist</li>
    <li>cd-hit</li>
    <li>chafa</li>
    <li>collision</li>
    <li>conjure</li>
    <li>converseen</li>
    <li>dblatexFull</li>
    <li>deltachat-desktop</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>dmtx-utils</li>
    <li>dsview</li>
    <li>electrum</li>
    <li>electrum-grs</li>
    <li>electrum-grs.dist</li>
    <li>electrum-ltc</li>
    <li>electrum-ltc.dist</li>
    <li>electrum.dist</li>
    <li>faircamp</li>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
    <li>fastqc</li>
    <li>fheroes2</li>
    <li>foxtrotgps</li>
    <li>gcs</li>
    <li>gimp (gimpPlugins.gimp)</li>
    <li>gimp.dev (gimpPlugins.gimp.dev)</li>
    <li>gimpPlugins.gmic</li>
    <li>goattracker</li>
    <li>goattracker-stereo</li>
    <li>gogui</li>
    <li>gopro</li>
    <li>gpscorrelate</li>
    <li>grandorgue</li>
    <li>hackneyed</li>
    <li>haskellPackages.gi-vips</li>
    <li>haskellPackages.gi-vips.doc</li>
    <li>healthchecks</li>
    <li>hikounomizu</li>
    <li>imagemagick</li>
    <li>imagemagick.dev</li>
    <li>imagemagick.doc</li>
    <li>imagemagickBig</li>
    <li>imagemagickBig.dev</li>
    <li>imagemagickBig.doc</li>
    <li>imagemagick_light</li>
    <li>imagemagick_light.dev</li>
    <li>imagemagick_light.doc</li>
    <li>imaginary</li>
    <li>img2pdf (python311Packages.img2pdf)</li>
    <li>img2pdf.dist (python311Packages.img2pdf.dist)</li>
    <li>imgproxy</li>
    <li>inkscape</li>
    <li>inkscape-extensions.textext</li>
    <li>inkscape-extensions.textext.dist</li>
    <li>inkscape-with-extensions</li>
    <li>invoice2data</li>
    <li>invoice2data.dist</li>
    <li>jadx</li>
    <li>joplin</li>
    <li>jupyter-all</li>
    <li>k40-whisperer</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>kitty</li>
    <li>kitty.kitten</li>
    <li>kitty.shell_integration</li>
    <li>kitty.terminfo</li>
    <li>lanraragi</li>
    <li>lemmy-ui</li>
    <li>libpst</li>
    <li>librum</li>
    <li>libsForQt5.libopenshot (plasma5Packages.libopenshot)</li>
    <li>libwmf</li>
    <li>libwmf.dev</li>
    <li>lilypond</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lilypond-with-fonts</li>
    <li>llpp</li>
    <li>logisim</li>
    <li>logisim-evolution</li>
    <li>lsix</li>
    <li>lua51Packages.image-nvim</li>
    <li>luaPackages.image-nvim (lua52Packages.image-nvim)</li>
    <li>lua53Packages.image-nvim</li>
    <li>lua54Packages.image-nvim</li>
    <li>luajitPackages.image-nvim</li>
    <li>mars-mips</li>
    <li>mcomix</li>
    <li>mcomix.dist</li>
    <li>mediainfo-gui</li>
    <li>movim</li>
    <li>mupdf</li>
    <li>mupdf.bin</li>
    <li>mupdf.dev</li>
    <li>mupdf.doc</li>
    <li>mupdf.man</li>
    <li>ne</li>
    <li>netbeans</li>
    <li>nhentai</li>
    <li>nhentai.dist</li>
    <li>nip2</li>
    <li>nixos-icons</li>
    <li>noteshrink</li>
    <li>noteshrink.dist</li>
    <li>noto-fonts-color-emoji</li>
    <li>numix-cursor-theme</li>
    <li>nuweb</li>
    <li>ocrmypdf (python311Packages.ocrmypdf)</li>
    <li>ocrmypdf.dist (python311Packages.ocrmypdf.dist)</li>
    <li>opcua-client-gui</li>
    <li>opcua-client-gui.dist</li>
    <li>openshot-qt</li>
    <li>openshot-qt.dist</li>
    <li>paperless-ngx</li>
    <li>pdf2odt</li>
    <li>perl536Packages.BarcodeZBar</li>
    <li>perl536Packages.BarcodeZBar.devdoc</li>
    <li>perl536Packages.PerlMagick (perl536Packages.ImageMagick)</li>
    <li>perl536Packages.PerlMagick.devdoc (perl536Packages.ImageMagick.devdoc)</li>
    <li>perl536Packages.LaTeXML</li>
    <li>perl536Packages.LaTeXML.tex</li>
    <li>perl538Packages.BarcodeZBar</li>
    <li>perl538Packages.BarcodeZBar.devdoc</li>
    <li>perl538Packages.PerlMagick (perl538Packages.ImageMagick)</li>
    <li>perl538Packages.PerlMagick.devdoc (perl538Packages.ImageMagick.devdoc)</li>
    <li>perl538Packages.LaTeXML</li>
    <li>perl538Packages.LaTeXML.tex</li>
    <li>phash</li>
    <li>pict-rs_0_3</li>
    <li>psitransfer</li>
    <li>pstoedit</li>
    <li>pstoedit.dev</li>
    <li>pulseview</li>
    <li>python311Packages.abjad</li>
    <li>python311Packages.abjad.dist</li>
    <li>python311Packages.aiounifi</li>
    <li>python311Packages.aiounifi.dist</li>
    <li>python311Packages.devolo-plc-api</li>
    <li>python311Packages.devolo-plc-api.dist</li>
    <li>python311Packages.diagrams</li>
    <li>python311Packages.diagrams.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.matplotlib-sixel</li>
    <li>python311Packages.matplotlib-sixel.dist</li>
    <li>python311Packages.osc-diagram</li>
    <li>python311Packages.osc-diagram.dist</li>
    <li>python311Packages.pdf2docx</li>
    <li>python311Packages.pdf2docx.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.py-pdf-parser</li>
    <li>python311Packages.py-pdf-parser.dist</li>
    <li>python311Packages.pymupdf</li>
    <li>python311Packages.pymupdf.dist</li>
    <li>python311Packages.python-zbar</li>
    <li>python311Packages.python-zbar.dist</li>
    <li>python311Packages.pyvips</li>
    <li>python311Packages.pyvips.dist</li>
    <li>python311Packages.pyvista</li>
    <li>python311Packages.pyvista.dist</li>
    <li>pywal (python311Packages.pywal)</li>
    <li>pywal.dist (python311Packages.pywal.dist)</li>
    <li>python311Packages.pyzbar</li>
    <li>python311Packages.pyzbar.dist</li>
    <li>python311Packages.scooby</li>
    <li>python311Packages.scooby.dist</li>
    <li>python311Packages.segno</li>
    <li>python311Packages.segno.dist</li>
    <li>python311Packages.sfepy</li>
    <li>python311Packages.sfepy.dist</li>
    <li>python311Packages.wagtail</li>
    <li>python311Packages.wagtail-factories</li>
    <li>python311Packages.wagtail-factories.dist</li>
    <li>python311Packages.wagtail-localize</li>
    <li>python311Packages.wagtail-localize.dist</li>
    <li>python311Packages.wagtail-modeladmin</li>
    <li>python311Packages.wagtail-modeladmin.dist</li>
    <li>python311Packages.wagtail.dist</li>
    <li>python311Packages.wand</li>
    <li>python311Packages.wand.dist</li>
    <li>python311Packages.willow</li>
    <li>python311Packages.willow.dist</li>
    <li>python312Packages.abjad</li>
    <li>python312Packages.abjad.dist</li>
    <li>python312Packages.aiounifi</li>
    <li>python312Packages.aiounifi.dist</li>
    <li>python312Packages.devolo-plc-api</li>
    <li>python312Packages.devolo-plc-api.dist</li>
    <li>python312Packages.diagrams</li>
    <li>python312Packages.diagrams.dist</li>
    <li>python312Packages.img2pdf</li>
    <li>python312Packages.img2pdf.dist</li>
    <li>python312Packages.layoutparser</li>
    <li>python312Packages.layoutparser.dist</li>
    <li>python312Packages.llama-index</li>
    <li>python312Packages.llama-index-readers-file</li>
    <li>python312Packages.llama-index-readers-file.dist</li>
    <li>python312Packages.llama-index.dist</li>
    <li>python312Packages.matplotlib-sixel</li>
    <li>python312Packages.matplotlib-sixel.dist</li>
    <li>python312Packages.ocrmypdf</li>
    <li>python312Packages.ocrmypdf.dist</li>
    <li>python312Packages.osc-diagram</li>
    <li>python312Packages.osc-diagram.dist</li>
    <li>python312Packages.pdf2docx</li>
    <li>python312Packages.pdf2docx.dist</li>
    <li>python312Packages.pdfplumber</li>
    <li>python312Packages.pdfplumber.dist</li>
    <li>python312Packages.py-pdf-parser</li>
    <li>python312Packages.py-pdf-parser.dist</li>
    <li>python312Packages.pymupdf</li>
    <li>python312Packages.pymupdf.dist</li>
    <li>python312Packages.pyvips</li>
    <li>python312Packages.pyvips.dist</li>
    <li>python312Packages.pyvista</li>
    <li>python312Packages.pyvista.dist</li>
    <li>python312Packages.pywal</li>
    <li>python312Packages.pywal.dist</li>
    <li>python312Packages.pyzbar</li>
    <li>python312Packages.pyzbar.dist</li>
    <li>python312Packages.scooby</li>
    <li>python312Packages.scooby.dist</li>
    <li>python312Packages.segno</li>
    <li>python312Packages.segno.dist</li>
    <li>python312Packages.sfepy</li>
    <li>python312Packages.sfepy.dist</li>
    <li>python312Packages.wagtail</li>
    <li>python312Packages.wagtail-factories</li>
    <li>python312Packages.wagtail-factories.dist</li>
    <li>python312Packages.wagtail-localize</li>
    <li>python312Packages.wagtail-localize.dist</li>
    <li>python312Packages.wagtail-modeladmin</li>
    <li>python312Packages.wagtail-modeladmin.dist</li>
    <li>python312Packages.wagtail.dist</li>
    <li>python312Packages.wand</li>
    <li>python312Packages.wand.dist</li>
    <li>python312Packages.willow</li>
    <li>python312Packages.willow.dist</li>
    <li>qalculate-gtk</li>
    <li>quark-goldleaf</li>
    <li>ranger</li>
    <li>ranger.dist</li>
    <li>rubyPackages.rmagick (rubyPackages_3_1.rmagick)</li>
    <li>rubyPackages.ruby-vips (rubyPackages_3_1.ruby-vips)</li>
    <li>rubyPackages_3_2.rmagick</li>
    <li>rubyPackages_3_2.ruby-vips</li>
    <li>rubyPackages_3_3.rmagick</li>
    <li>rubyPackages_3_3.ruby-vips</li>
    <li>saga</li>
    <li>sgfutils</li>
    <li>signaturepdf</li>
    <li>sioyek</li>
    <li>skribilo</li>
    <li>smuview</li>
    <li>spatialite_gui</li>
    <li>supersonic</li>
    <li>t-rec</li>
    <li>termpdfpy</li>
    <li>termpdfpy.dist</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ImageMagick</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.MagickWand</li>
    <li>texliveFull</li>
    <li>texliveFull.info</li>
    <li>texliveFull.man</li>
    <li>texliveMedium</li>
    <li>texliveMedium.info</li>
    <li>texliveMedium.man</li>
    <li>tijolo</li>
    <li>timelapse-deflicker</li>
    <li>ttygif</li>
    <li>ueberzugpp</li>
    <li>vcs</li>
    <li>viking</li>
    <li>vips</li>
    <li>vips.bin</li>
    <li>vips.dev</li>
    <li>vips.man</li>
    <li>vipsdisp</li>
    <li>virt-manager</li>
    <li>virt-manager.dist</li>
    <li>volantes-cursors</li>
    <li>wallust</li>
    <li>win2xcur</li>
    <li>win2xcur.dist</li>
    <li>wv</li>
    <li>xfig</li>
    <li>ytfzf</li>
    <li>yunfaavatar</li>
    <li>zbar</li>
    <li>zbar.dev</li>
    <li>zbar.doc</li>
    <li>zbar.lib</li>
    <li>zbar.man</li>
  </ul>
</details>

**Comment by trofi** [comment]
> Result of `nixpkgs-review pr 307309` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 68 packages marked as broken and skipped:
> 324 packages failed to build:

Looks like the review tool did not manage to build even `imagemagic` for you. Can you have a look if those are legitimate failures or those are some generic darwin failures?

**Comment by uncenter** [comment]
Probably just generic failures 😅. Last time I tried it was taking forever to build so I left this running overnight to see if it could finish.

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please target master.

**Comment by JohnRTitor** [comment]
@ofborg build imagemagick

**Review by dotlambda — APPROVED** [review]
The pkg-config test fails and will be fixed by https://github.com/NixOS/nixpkgs/pull/311820.

**Pull request merged**
