### PR TITLE
teamviewer: 13.1.3026 -> 14.1.3399

### LINKED ISSUE #51059: Package update required: Teamviewer 13 -> Teamviewer 14
## Issue description
Teamviewer has *no* backwards compatibility between releases, which means that if I upgrade Teamviewer on one operating system (because of other incompatibilities, not because I want to) I also require an upgrade on NixOS. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.82, NixOS, 18.09.git.51076ed (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by DrWowa**
teamviewer: 13.1.3026 -> 14.1.3399
###### Motivation for this change
Update teamviewer from 13.1.3026 to 14.1.3399

Fixes #51059

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) (not found any)
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date (not found any)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
@DrWowa You may notice that a maintainer modified your pr title.

That is because it doesn't match the [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes).
You should also change your commit msg to this.

Aside from that you have performed this update correctly.

**Comment by worldofpeace** [comment]
Changelog: https://community.teamviewer.com/t5/Linux/Update-14-1-3399-TeamViewer-14/m-p/46523#

> We updated our dependencies to Qt 5.5 and might go to 5.6 within the next year. This gives us many new options to create a good UI, and can help us to improve HighDPI suport.
On the other hand, we are aware that some of our customers are still on systems that don't sport Qt 5.5 (or 5.6). 

I'm not familiar with qt, but I'd think this might be a problem for stable, as a backport is needed.
@Mic92 Any comments?

**Comment by Mic92** [comment]
@worldofpeace that should work as we have qt 5.11 already. Should be tested though.

**Comment by worldofpeace** [comment]
Currently executes fine on my machine running off of master.

**Comment by Mic92** [comment]
Here is a report that it might segfaults with the latest qt.
 https://github.com/NixOS/nixpkgs/pull/53117

Using `libsForQt56` should be a safer choice.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
In `all-packages.nix` call `teamviewer` with `libsForQt56.callPackage`.
```
teamviewer = libsForQt56.callPackage ...
```

**Comment by Mic92** [comment]
merged in:

[detached HEAD 2a858b3f766] teamviewer: 13.1.3026 -> 14.1.3399
 Author: Vladimir Mosienko <vm.drwowa@gmail.com>
 Date: Fri Jan 18 11:39:42 2019 +0500
 2 files changed, 4 insertions(+), 4 deletions(-)

**Comment by Mic92** [comment]
backport: c7ae9a29ffac1e23a55ba5570a30f47553567c79

**Pull request closed without merging**
