### PR TITLE
Update android sdk, add license config option and selectable build tools

### PR DESCRIPTION
**Pull request by nicknovitski**
I followed #36112 and some other license-requiring packages.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Do you have an example project I could use to test this?

**Comment by nicknovitski** [comment]
That's a great idea, I'll try to find one or set one up.

**Review by matthewbauer — APPROVED** [review]

**Comment by Mic92** [comment]
I had to set ANDROID_HOME instead of ANDROID_SDK_ROOT, but it worked out in the end:

```nix
 with import <nixpkgs> {
    config = {
      allowUnfree = true;
      android_sdk.accept_license = true;
    };
  };

  let
    sdk = androidenv.androidsdk {
       platformVersions = [ "26" ];
       buildToolsVersions = [ "27.0.3" ];
       abiVersions = [ "x86" "x86_64"];
       useGoogleAPIs = true;
     };
  in mkShell {
    LANG="en_US.UTF-8";
    ANDROID_HOME="${sdk}/libexec";

    nativeBuildInputs = [
      nodejs-8_x
      openjdk8
      sdk
    ];
  }
```

**Comment by myguidingstar** [comment]
this seems to work but the command `emulator` fails in my machine:
```
/nix/store/2gngv0lf60ibbgzp9wj54fsyncbbb0y3-android-sdk-26.1.1/bin/emulator: line 5: /nix/store/2gngv0lf60ibbgzp9wj54fsyncbbb0y3-android-sdk-26.1.1/libexec/tools/.emulator-wrapped: No such file or directory
```
can you have a look at that? @nicknovitski

**Comment by nicknovitski** [comment]
@myguidingstar Good catch, thank you. #49564

**Comment by nicknovitski** [comment]
@Mic92 The android infrastructure could definitely benefit from a section in the manual.

**Comment by Mic92** [comment]
@nicknovitski I invite you to do that. If docbook is not your thing there is also markdown supported. (see python.md)

**Comment by myguidingstar** [comment]
@nicknovitski @Mic92 this pull request also breaks `androidenv.emulateApp` because older versions use `/libexec/tools/android create avd` to create a new virtual device. Now it yells `Error: Flag '-t' is not valid for 'create avd'.`
The command also says `The "android" command is deprecated.` and suggests android studio, `sdkmanager` and `avdmanager` instead.

**Comment by myguidingstar** [comment]
if I run `avdmanager` to create a virtual device myself, I get these warning.
```
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/android/m2repository/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/android/support/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/google/google_play_services/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/google/m2repository/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/platform-tools/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/platforms/android-26/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/sources/android-26/package.xml. Probably the SDK is read-only
Info: Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/system-images/android-26/x86_64/package.xml. Probably the SDK is read-only
Warning: Observed package id 'system-images;android-26;default;x86_64' in inconsistent location '/nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/system-images/android-26/x86_64' (Expected '/nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/system-images/android-26/default/x86_64')
Parsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/build-tools/26.0.3Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/build-tools/26.0.3/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/android/m2repositoryException while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/android/m2repository/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/android/supportException while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/android/support/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/google/google_play_servicesException while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/google/google_play_services/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/google/m2repositoryException while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/extras/google/m2repository/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/platform-toolsException while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/platform-tools/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/platforms/android-26Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/platforms/android-26/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/sources/android-26Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/sources/android-26/package.xml. Probably the SDK is read-onlyParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/supportParsing legacy package: /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/system-images/android-26/x86_64Exception while marshalling /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/system-images/android-26/x86_64/package.xml. Probably the SDK is read-onlyParsing /nix/store/dfv8mxsjfh4mghawqrpa31a28b5wwdns-android-sdk-26.1.1/libexec/tools/package.xmlAuto-selecting single ABI x86_64
```
It also says `Copying files` then `null` but no virtual device is created.

**Comment by myguidingstar** [comment]
I also got this error when trying to run `emulator`:

```
[140623058774912]:ERROR:android/android-emu/android/qt/qt_setup.cpp:28:Qt library not found at /nix/store/ks3zbnxm0kaq1js6cdzxi1ji3q52h6r7-android-sdk-26.1.1/emulator/lib64/qt/lib
Could not launch '/nix/store/ks3zbnxm0kaq1js6cdzxi1ji3q52h6r7-android-sdk-26.1.1/emulator/qemu/linux-x86_64/qemu-system-x86_64': No such file or directory
```

**Comment by Mic92** [comment]
@myguidingstar this will be fixed with: https://github.com/NixOS/nixpkgs/pull/49515

**Comment by myguidingstar** [comment]
@Mic92 actually I've picked that patch, and the above warnings and errors are made with that branch

**Comment by Mic92** [comment]
Ah right. Did not pay enough attention. `autoPatchelfHook` might be a better fix since it will automatically detect missing libraries at build time.

**Comment by svanderburg** [comment]
Hi,

I am working on a revised implementation of the Android SDK that fixes most of our current problems, and provides several kinds of new facilities that make maintenance a lot easier.

More information can be found here: https://discourse.nixos.org/t/my-revised-experimental-android-build-functions/923

My revised implementation lives in a separate repository, but I intend to soon work on a reintegration strategy.

**Pull request merged**
