### PR TITLE
nixos/varnish: change default stateDir to /run

### PR DESCRIPTION
**Pull request by laalsaas**
## Description of changes
The stateDir, or as varnish calls it, the workdir should always be a tmpfs. Otherwise, performance issues may occur. See:

- https://varnish-cache.org/docs/trunk/reference/varnishd.html#opt-n

- https://github.com/varnishcache/varnish-cache/issues/4121

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ctheune — APPROVED** [review]
LGTM.

**Comment by leona-ya** [comment]
@ofborg eval

**Review by leona-ya — CHANGES_REQUESTED** [review]

**Comment by leona-ya** [comment]
@ajs124: Not sure if you're the right person to review this. Nobody really touched the module in the last time, but you seem to have some interest in varnish. Please ignore if I'm wrong :)

**Comment by ajs124** [comment]
My interest was only during previous employment. Maybe @LeSuisse?

**Review by leona-ya — APPROVED** [review]

**Comment by LeSuisse** [comment]
My interest was security related, I'm not a user of Varnish I just spotted it was vulnerable at some point in the past.

I have no strong opinion on the patch but the same comment as @leona-ya 😉

I'm AFK so I cannot test but feel free to merge.

**Review by ctheune — APPROVED** [review]

**Pull request merged**
