### PR TITLE
xen: 4.17.4 -> 4.17.5, 4.18.2 -> 4.18.3

### PR DESCRIPTION
**Pull request by SigmaSquadron**
## Description of changes

- Updates the 4.17 branch to 4.17.5.
- Updates the 4.18 branch to 4.18.3.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested, as applicable:
  - Both boot and pass XTF.
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 341132"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] Updated release notes in the [associated module PR](https://github.com/NixOS/nixpkgs/pull/324911).
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SigmaSquadron** [comment]
Result of `nixpkgs-review pr 341132` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>qemu_xen_4_17</li>
    <li>qemu_xen_4_17.debug</li>
    <li>qemu_xen_4_17.ga</li>
    <li>qemu_xen_4_18</li>
    <li>qemu_xen_4_18.debug</li>
    <li>qemu_xen_4_18.ga</li>
    <li>xenPackages.xen_4_17</li>
    <li>xenPackages.xen_4_17-slim</li>
    <li>xenPackages.xen_4_17-slim.boot</li>
    <li>xenPackages.xen_4_17-slim.dev</li>
    <li>xenPackages.xen_4_17-slim.doc</li>
    <li>xenPackages.xen_4_17-slim.man</li>
    <li>xenPackages.xen_4_17.boot</li>
    <li>xenPackages.xen_4_17.dev</li>
    <li>xenPackages.xen_4_17.doc</li>
    <li>xenPackages.xen_4_17.man</li>
    <li>xenPackages.xen_4_18</li>
    <li>xenPackages.xen_4_18-slim</li>
    <li>xenPackages.xen_4_18-slim.boot</li>
    <li>xenPackages.xen_4_18-slim.dev</li>
    <li>xenPackages.xen_4_18-slim.doc</li>
    <li>xenPackages.xen_4_18-slim.man</li>
    <li>xenPackages.xen_4_18.boot</li>
    <li>xenPackages.xen_4_18.dev</li>
    <li>xenPackages.xen_4_18.doc</li>
    <li>xenPackages.xen_4_18.man</li>
  </ul>
</details>

**Review by emilazy — APPROVED** [review]
Result of `nixpkgs-review pr 341132` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>qemu_xen_4_17</li>
    <li>qemu_xen_4_17.debug</li>
    <li>qemu_xen_4_17.ga</li>
    <li>qemu_xen_4_18</li>
    <li>qemu_xen_4_18.debug</li>
    <li>qemu_xen_4_18.ga</li>
    <li>xenPackages.xen_4_17</li>
    <li>xenPackages.xen_4_17-slim</li>
    <li>xenPackages.xen_4_17-slim.boot</li>
    <li>xenPackages.xen_4_17-slim.dev</li>
    <li>xenPackages.xen_4_17-slim.doc</li>
    <li>xenPackages.xen_4_17-slim.man</li>
    <li>xenPackages.xen_4_17.boot</li>
    <li>xenPackages.xen_4_17.dev</li>
    <li>xenPackages.xen_4_17.doc</li>
    <li>xenPackages.xen_4_17.man</li>
    <li>xenPackages.xen_4_18</li>
    <li>xenPackages.xen_4_18-slim</li>
    <li>xenPackages.xen_4_18-slim.boot</li>
    <li>xenPackages.xen_4_18-slim.dev</li>
    <li>xenPackages.xen_4_18-slim.doc</li>
    <li>xenPackages.xen_4_18-slim.man</li>
    <li>xenPackages.xen_4_18.boot</li>
    <li>xenPackages.xen_4_18.dev</li>
    <li>xenPackages.xen_4_18.doc</li>
    <li>xenPackages.xen_4_18.man</li>
  </ul>
</details>

**Comment by emilazy** [comment]
Good timing :)

**Comment by SigmaSquadron** [comment]
I do have a confession to make: these updates were released three weeks ago, but I didn't notice them as Xen didn't make an announcement in the mailing list!

**Comment by emilazy** [comment]
At least they weren’t security updates…

**Comment by SigmaSquadron** [comment]
_[Something is wrong. Very wrong.](https://hydra.nixos.org/build/272178486/nixlog/6)_

**Pull request merged**
