### PR TITLE
ati-drivers :  15.7 -> 15.12

### PR DESCRIPTION
**Pull request by heydojo**
This update and set of patches enables the latest AMD radeon driver in nixos.
The patches mainly allow building upto (and hopefully beyond) linux kernel 4.3.
While this all seems good and well - there is a matter which will need discussion or a solution to.
As of this update, AMD are dropping support for pre-GCN cards - mainly
the Radeons of series 5000 and 6000. Those cards are about 5 years old now.
In order for nixos to continue to support those cards, the version of this package
previous will still work with those cards but that version does not compile past linux 4.1.
So - does this update need forking out into a new package in order to continue support for
pre-GCN cards? (linux 4.1 is a long term support kernel.)
Is the extra work worth it or should the pre-GCN support be dropped?
If pre-GCN support is to be dropped, please take this merge as is.
If support for pre-GCN is to be maintained, would one of the maintainers of this package please
come up with a solution?

### CODE REVIEW

**Comment by jagajaga** [comment]
Please properly name commit to follow our rules in `CONTRIBUTING.md`

**Comment by pSub** [comment]
@heydojo You have only changed the title of the pull request. Use `git commit --amend` to change the commit message and force push to heydojo:ati_unfree-crimson.

**Comment by heydojo** [comment]
@pSub Thanks for the hint. I guess this is OK now?
Am I doing it right XD ?

**Comment by pSub** [comment]
Nearly, instead of merging you should do a rebase. (This saves one unnecessary commit)

**Comment by heydojo** [comment]
Clearly my git fu is not up to par... XD

**Comment by heydojo** [comment]
I believe that at least part of the issue (possibly all of) this patch tries to fix is linked to https://github.com/NixOS/nixpkgs/issues/8676
and as a result I won't be pulling or rebuilding until it is confirmed as fixed.
I am closing this commit as a result and will review again in due course.

**Pull request closed without merging**
