### PR TITLE
ronn: 0.7.3 → 0.9.1

### LINKED ISSUE #168103: Switch ronn to a maintained fork
The [original ronn](https://github.com/rtomayko/ronn) has long been unmaintained. There is [a fork](https://github.com/apjanke/ronn-ng) that introduces new command-line arguments, that are already being used in the wild (e.g. #168089). We might want to switch our package to that fork like [Alpine and Debian already did](https://repology.org/project/ronn/versions).

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: ronn

current version: 0.7.3
desired version: 0.9.0

###### Notify maintainers

maintainers: @nicknovitski @zimbatm 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

The original ronn has long been unmaintained. Let’s switch to the same fork Alpine and Debian use, since there are projects expecting ronn to support command-line arguments introduced by this fork.

Fixes: https://github.com/NixOS/nixpkgs/issues/168103

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by nicknovitski — APPROVED** [review]

**Comment by andrewchambers** [comment]
I would have appreciated if you had changed the name to ronn-ng - this upgrade seems to have broken some of my work flow.

**Comment by jtojnar** [comment]
@andrewchambers Could you be more specific? I believe I checked the supported flags and did not notice any incompatible changes. Was there some other breakage?

**Comment by andrewchambers** [comment]
I am debugging now, but it seems I had some markdown that used github style raw triple quotes and they no longer render the same way. I can see that ronn didn't support those to begin with so my guess is ronn treats them as 3 different quote blocks while ronn-ng doesn't treat them as a quote block at all.

**Comment by andrewchambers** [comment]
I have made my own copy of the old ronn package until I can debug this later.

**Comment by jtojnar** [comment]
If we wanted to guarantee backwards compatibility we could not ever remove anything, which would soon make Nixpkgs unmaintainable. Unless the fork obviously means to go a separate way, it is really no different from the upstream project changing maintainers, so it makes little sense to preserve the old version with defunct upstream. Especially when we had an evidence of the fork being compatible in the form of other distros making the switch a long time ago without any reported issues.

**Comment by andrewchambers** [comment]
I don't disagree - though in my opinion it would have been better to deprecate ronn with a warning and introduce the new name ronn-ng. Finally you can delete the old ronn once it stops working or is no longer needed.

**Comment by andrewchambers** [comment]
Another thing this change did was silently break the man pages of bupstash in nixpkgs, trying to work out the best way to resolve it.

**Pull request merged**
