### PR TITLE
inkscape-extensions.inkstitch: init at 3.1.0

### LINKED ISSUE #133180: Package request: Ink/Stitch
**Project description**
Ink/Stitch is an extension for inkscape to generate files for use in embroidery machines

This seems like a real challenge to package: https://inkstitch.org/developers/inkstitch/manual-setup/
needs python, node, and electron. Probably quite a bit over my head

**Metadata**

* homepage URL: https://inkstitch.org/
* source URL: https://github.com/inkstitch/inkstitch
* license: gpl3Only
* platforms: linux, windows, darwin (?)

### PR DESCRIPTION
**Pull request by pluiedev**
Closes #133180 after over 3 years (!)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by felbinger** [comment]
How can I use this package until merged? I cherry picked the two commits into nixos-24.11, but opening inkscape from `.#inkscape-with-extensions` still doesn't show the extension

**Review by getchoo — APPROVED** [review]
Feel free to ping me in a couple day if another review doesn't come along

**Comment by pluiedev** [comment]
I wasn't aware of anything that needs fixing, but I'll take a look

**Comment by SuperSandro2000** [comment]
Did you try using the extension in inkscape? I am pretty sure tropf told me that it wasn't really working at all without those.

**Comment by pluiedev** [comment]
OK so I took a look at tropf's repo and... I don't really know how many of them are applicable, but I'm going to try them out either way. What is certain is that Ink/Stitch isn't showing up with `inkscape-with-extensions`, which is a problem...

**Comment by tropf** [comment]
@SuperSandro2000: The cruft I've been complaining about mostly relates to since-removed electron, inkscape 1.3.2 bundling inkex 1.3.1 (still, wtf), and inkstitch doing dirty, dirty tinkering with the python path.

For Inkscape 1.4 I expect only the invocation to maybe be relevant, but I have not checked. (Some parts of inkstitch assume the source files to be stand-alone bundled python scripts, and others may consider the source directory writeable.)

We might have to check manually on updates though, as upstream inkstitch used pinned, non-release versions of libraries in the past.

**Comment by tropf** [comment]
> OK so I took a look at tropf's repo and... I don't really know how many of them are applicable, but I'm going to try them out either way. What is certain is that Ink/Stitch isn't showing up with `inkscape-with-extensions`, which is a problem...

That's an error in inkscape-with-extensions; I proposed a fix in #366537.

**Pull request merged**
