### PR TITLE
pythonPackages.python_magic: fix build and run tests

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/112786 is not moving forward

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115260` at 6c3b5c19 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/2c54b6f7f596d5e9632625d391d33f53">python37Packages.geoip2</a></li></li>
    <li><a href="https://gist.github.com/f13eaadde0c598c74416e9269e66bccb">python37Packages.mocket</a></li></li>
    <li><a href="https://gist.github.com/c4e31c903e14cbdc228b3084f7dc6e36">python37Packages.sopel</a></li></li>
    <li><a href="https://gist.github.com/8816ec8afacb58b7a5f78e4a104f4f75">python38Packages.geoip2</a></li></li>
    <li><a href="https://gist.github.com/160ccf723b5e8ec13779544c5417faf0">python38Packages.mocket</a></li></li>
    <li><a href="https://gist.github.com/3a0190ec4c107d61a9f61f3a6c152a35">python38Packages.sopel</a></li></li>
    <li><a href="https://gist.github.com/80b90541e8849c732bd047e4cb152077">python39Packages.geoip2</a></li></li>
    <li><a href="https://gist.github.com/07110d466fb46b62e22e46814d588bdc">python39Packages.mocket</a></li></li>
    <li><a href="https://gist.github.com/d0f49b2637a85dea2a872212de6d3008">python39Packages.sopel</a></li></li>
  </ul>
</details>
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/1a17cbfa3b700ce6fa5e831665da8683">alot</a></li> (python38Packages.alot)</li>
    <li><a href="https://gist.github.com/b36b482a072cd132ff7cc39e30c40cf1">beancount</a></li> (python38Packages.beancount)</li>
    <li><a href="https://gist.github.com/5e5e05fdfda038477e052683ce193e71">diffoscope</a></li></li>
    <li><a href="https://gist.github.com/6f4fad6ece6cad52860c992bf008f6d4">fava</a></li></li>
    <li><a href="https://gist.github.com/453a5fbb0f633a1e8489976373634d83">ledger2beancount</a></li></li>
    <li><a href="https://gist.github.com/aed3346a68857dc1747b3601da4f0cdd">mautrix-telegram</a></li></li>
    <li><a href="https://gist.github.com/e20e24a2e9133c38b0eaa4d251241497">python37Packages.alot</a></li></li>
    <li><a href="https://gist.github.com/21c598e43586cf0ae99ba3143c7a3013">python37Packages.beancount</a></li></li>
    <li><a href="https://gist.github.com/f80aa553dfe35f44913f15177d170dc5">python37Packages.beancount_docverif</a></li></li>
    <li><a href="https://gist.github.com/f582a9cfa72a68a1cb6c9bc106ed7b8d">python37Packages.django-versatileimagefield</a></li></li>
    <li><a href="https://gist.github.com/fdacd3428afec1e144bf99ef31e30bd8">python37Packages.pushbullet</a></li></li>
    <li><a href="https://gist.github.com/bf848ec56024c8e415ce02d98f2a63fa">python37Packages.pysnow</a></li></li>
    <li><a href="https://gist.github.com/51a6654e352ec3b9a97742897663a06c">python37Packages.python_magic</a></li></li>
    <li><a href="https://gist.github.com/a282d5c87dc229e8a8cf941105c16c32">python37Packages.relatorio</a></li></li>
    <li><a href="https://gist.github.com/cf6791552a801a43b66a6a622a5d0ae2">python37Packages.trytond</a></li></li>
    <li><a href="https://gist.github.com/65cd325a2e9f725498d8f2c8a1b2805c">python38Packages.beancount_docverif</a></li></li>
    <li><a href="https://gist.github.com/a7f045253460303001aa9a48fd9232f1">python38Packages.django-versatileimagefield</a></li></li>
    <li><a href="https://gist.github.com/6a6b07ea140c4e5f78abc3d863721352">python38Packages.pushbullet</a></li></li>
    <li><a href="https://gist.github.com/0aab167330a7cea0683b1b4d23087655">python38Packages.pysnow</a></li></li>
    <li><a href="https://gist.github.com/70c13f31543033d97ffb40923cbc3917">python38Packages.python_magic</a></li></li>
    <li><a href="https://gist.github.com/3dd7b65bcb5a1944a624fada64e8e79a">python38Packages.relatorio</a></li></li>
    <li><a href="https://gist.github.com/be93b0cfa0ff6d068e50c87c3607931e">trytond</a></li> (python38Packages.trytond)</li>
    <li><a href="https://gist.github.com/4d75655504beac20f90042cc882d3666">python39Packages.alot</a></li></li>
    <li><a href="https://gist.github.com/d128f479c8d452909051cdca77a3027e">python39Packages.beancount</a></li></li>
    <li><a href="https://gist.github.com/0affe55435e44c6cecf0e71ca4777465">python39Packages.beancount_docverif</a></li></li>
    <li><a href="https://gist.github.com/5cde491cfe272635d6ac6bad96cce600">python39Packages.django-versatileimagefield</a></li></li>
    <li><a href="https://gist.github.com/4c248c6b3668fad2fb2a6dea6cb942f7">python39Packages.pushbullet</a></li></li>
    <li><a href="https://gist.github.com/2d8e4a91d8840ab759230800495f87e7">python39Packages.python_magic</a></li></li>
    <li><a href="https://gist.github.com/805e83102ede08d8cf0a74f67d222088">python39Packages.relatorio</a></li></li>
    <li><a href="https://gist.github.com/a4b0a7824fe9dad1ca9ff8b81de5d8fc">python39Packages.trytond</a></li></li>
    <li><a href="https://gist.github.com/85b9c730688f89905acd50c7d81656a6">s3cmd</a></li></li>
    <li><a href="https://gist.github.com/666506b48f593a3e06346764e6ddd39b">steck</a></li></li>
    <li><a href="https://gist.github.com/a63d65abf896641c61e511396a2aefee">weechatScripts.weechat-matrix</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/python-magic/default.nix:35:3:
```
   |
35 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/python-modules/python-magic/default.nix:23:5:
```
   |
23 |     (substituteAll {
   |     ^
```
</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
geoip2, mocket and sopel on python39 are unrelated.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>6 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python38Packages.geoip2: log was empty</li>
<li>python38Packages.mocket: log was empty</li>
<li>python38Packages.sopel: log was empty</li>
<li>python39Packages.geoip2: log was empty</li>
<li>python39Packages.mocket: log was empty</li>
<li>python39Packages.sopel: log was empty</li>
  </ul>
</details>
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.geoip2: log was empty</li>
<li>python37Packages.mocket: log was empty</li>
<li>python37Packages.sopel: log was empty</li>
  </ul>
</details>
<details>
<summary>
33 packages built:
</summary>
<ul>
<li>alot (python38Packages.alot)</li>
<li>beancount (python38Packages.beancount)</li>
<li>diffoscope</li>
<li>fava</li>
<li>ledger2beancount</li>
<li>mautrix-telegram</li>
<li>python37Packages.alot</li>
<li>python37Packages.beancount</li>
<li>python37Packages.beancount_docverif</li>
<li>python37Packages.django-versatileimagefield</li>
<li>python37Packages.pushbullet</li>
<li>python37Packages.pysnow</li>
<li>python37Packages.python_magic</li>
<li>python37Packages.relatorio</li>
<li>python37Packages.trytond</li>
<li>python38Packages.beancount_docverif</li>
<li>python38Packages.django-versatileimagefield</li>
<li>python38Packages.pushbullet</li>
<li>python38Packages.pysnow</li>
<li>python38Packages.python_magic</li>
<li>python38Packages.relatorio</li>
<li>trytond (python38Packages.trytond)</li>
<li>python39Packages.alot</li>
<li>python39Packages.beancount</li>
<li>python39Packages.beancount_docverif</li>
<li>python39Packages.django-versatileimagefield</li>
<li>python39Packages.pushbullet</li>
<li>python39Packages.python_magic</li>
<li>python39Packages.relatorio</li>
<li>python39Packages.trytond</li>
<li>s3cmd</li>
<li>steck</li>
<li>weechatScripts.weechat-matrix</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
alot:
<details>


warning: unclear-gpl
`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/alot/default.nix:66:5:

```
   |
66 |     license = licenses.gpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: python-include-tests
Add a `checkPhase` for tests, or at least `pythonImportsCheck`.

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md
warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/alot/default.nix:1:53:

```
  |
1 | { lib, buildPythonPackage, python, fetchFromGitHub, fetchpatch, isPy3k
  |                                                     ^
```
</details>
</details>

**Comment by mweinelt** [comment]
> 3 packages failed to build and are new build failures:

Not true.

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
