### PR TITLE
nixos/plasma6: add qtimageformats to the requiredPackages

### LINKED ISSUE #304523: Plasma 6 packages do not handle webp or avif image formats
### Describe the bug

Multiple Plasma 6 packages cannot use webp or avif images

So far I've found the following problems:
- Dolphin does not show previews for webp images
- Cannot use a webp or avif image as a wallpaper
- Spectacle offers an option to save image as a webp image or avif image; but selecting this options results in error in Spectacle 

Probably there are other packages affected by the same issue

The problem is similar to https://github.com/NixOS/nixpkgs/issues/292375

### Expected behavior
Plasma 6 apps should handle supported image formats other than .jpg and .png

### Screenshots
image

### Notify maintainers

@k900

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4-zen1, NixOS, 24.05 (Uakari), 24.05.20240412.cfd6b5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/yy5l09gfsagkv8rswblknmsjc2gyr20d-source`
```

nixpkgs from `flakes.lock`: 
```json
"nixpkgs": {
  "locked": {
    "lastModified": 1712963716,
    "narHash": "sha256-WKm9CvgCldeIVvRz87iOMi8CFVB1apJlkUT4GGvA0iM=",
    "owner": "nixos",
    "repo": "nixpkgs",
    "rev": "cfd6b5fc90b15709b780a5a1619695a88505a176",
    "type": "github"
  },
  "original": {
    "owner": "nixos",
    "ref": "nixos-unstable",
    "repo": "nixpkgs",
    "type": "github"
  }
},
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by chermnyx**
## Description of changes

This is needed for qt6 apps to be able to work with certain image formats such as .webp and .avif

Closes https://github.com/NixOS/nixpkgs/issues/304523

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [x] `nixosTests.plasma6` is passed
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by chermnyx** [comment]
@ofborg test plasma6

**Comment by chermnyx** [comment]
Result of `nixpkgs-review pr 306227` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

**Comment by fin444** [comment]
I'm unable to replicate this as a fix on my machine. By default, I am able to open WEBP images in Gwenview but not AVIF. I tried adding both `kdePackages.kimageformats` and `kdePackages.qtimageformats` to `environment.systemPackages`, but this did not change.

I also see that Gwenview is already compiled with `qtimageformats`
https://github.com/NixOS/nixpkgs/blob/18536bf04cd71abd345f9579158841376fdd0c5a/pkgs/kde/gear/gwenview/default.nix#L18-L22

**Comment by chermnyx** [comment]
> I'm unable to replicate this as a fix on my machine. By default, I am able to open WEBP images in Gwenview but not AVIF. I tried adding both `kdePackages.kimageformats` and `kdePackages.qtimageformats` to `environment.systemPackages`, but this did not change.
> 
> I also see that Gwenview is already compiled with `qtimageformats`
> 
> https://github.com/NixOS/nixpkgs/blob/18536bf04cd71abd345f9579158841376fdd0c5a/pkgs/kde/gear/gwenview/default.nix#L18-L22

The fix from this PR is currently broken due to https://bugreports.qt.io/browse/QTBUG-130109

**Review by fin444 — CHANGES_REQUESTED** [review]
Sorry for forgetting about this. Now that Qt has been patched, I've done some more looking into this (see [here](https://github.com/NixOS/nixpkgs/issues/304523#issuecomment-2477281751)). I approve this PR, but needs to be rebased for merge conflicts.

**Comment by K900** [comment]
Sorry, this completely fell off my radar too. We should probably put kimageformats and qtimageformats into the same category, though - either both optional or both required.

**Pull request merged**
