### PR TITLE
{ruby,neovim}: fix build with content-addressed derivations

### PR DESCRIPTION
**Pull request by tie**
## Description of changes

This PR fixes some packages that were broken after https://github.com/NixOS/nixpkgs/pull/211783 with `contentAddressedByDefault`. See https://github.com/NixOS/nixpkgs/pull/211783#discussion_r1090028466, https://github.com/NixOS/nixpkgs/pull/211783#issuecomment-1412043477, and https://github.com/NixOS/nixpkgs/pull/214044#issuecomment-1413447043

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tie** [comment]
Wrt https://github.com/NixOS/nixpkgs/pull/211783, I think this should be a separate parameter for `mkDerivation` instead of overriding the meaning of `(dis)allowed{References,Requisites}` by discarding the context (breaking content-addressed derivations along the way).

**Comment by Artturin** [comment]
Must target staging, follow contributing.md to rebase.

**Comment by tie** [comment]
I don’t think a rebase is necessary.
```
$ git rebase --onto upstream/staging... upstream/master
Current branch fix-ca-derivations-disallowed is up to date.
```

**Comment by ConnorBaker** [comment]
This is kind of difficult to review due to the number of rebuilds. Any suggestions for a more limited way to run `nixpkgs-review` which verifies that this 1) fixes the problem and 2) doesn't break anything else?

**Comment by r-vdp** [comment]
Why do we have `stdenv.cc` for neovim and `stdenv.cc.cc` for ruby, in `disallowedRequisites` ?

**Comment by pillowtrucker** [comment]
fwiw I've been testing the ruby side of this for 2 days and haven't had any issues

**Review by marsam — APPROVED** [review]
Thank you!

**Pull request merged**
