### PR TITLE
razergenie: init at 0.8.1

### PR DESCRIPTION
**Pull request by f4814**
###### Motivation for this change
Add razergenie, a frontend for the openrazer daemon. To the best of my knowledge there is no openrazer frontend in nixpkgs at the moment, which renders nixos `hardware.openrazer` functionality almost useless. I also added myself as contributor and notified the RazerGenie maintainers here: https://github.com/z3ntu/RazerGenie/issues/70

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Emantor** [comment]
Hi, this needs a rebase onto master to resolve the merge conflict.

**Comment by f4814** [comment]
Okay. This was not what I intended to to. I'll just close this PR and create a new clean one.

**Comment by Emantor** [comment]
@f4814 Unfortunately you didn't rebase, you merged the amster branch into your branch. https://git-rebase.io/ has a great description on how to do rebases.

**Comment by f4814** [comment]
Thanks for the link. I am fairly new to contributing in such a way. I'll quickly create a new, clean PR.

**Comment by f4814** [comment]
Okay. New, clean PR is https://github.com/NixOS/nixpkgs/pull/84812 Thanks for your patience.

**Pull request closed without merging**
