### PR TITLE
stfl: link with libiconv on darwin

### PR DESCRIPTION
**Pull request by paparodeo**
https://hydra.nixos.org/build/275236623/log/tail
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — CHANGES_REQUESTED** [review]
The tarball URL has been taken over by a casino spam site that is seemingly mirroring content from the former version of the website(!) but not the tarball, which is now only being kept alive by Hydra.

We could switch to a Wayback Machine version but perhaps we should just point this to https://github.com/newsboat/stfl from the Newsboat folks which seems to have received marginally more maintenance.

**Comment by Artturin** [comment]
Either that fork or https://ponce.cc/slackware/sources/repo/stfl-0.24.tar.gz
 which arch uses https://gitlab.archlinux.org/archlinux/packaging/packages/stfl/-/blob/main/PKGBUILD?ref_type=heads#L14

**Comment by emilazy** [comment]
Newsboat is one of three packages that use this library, and it seems like it’s had a couple of fixes since the fork, so it seems like a decent choice. I’d rather rely on Wayback Machine than a random Slackware mirror if we don’t switch, I think.

**Comment by paparodeo** [comment]
updates are pretty minor: https://github.com/newsboat/stfl/compare/d8ea471d46192fff5e726db2fe4d966b83bd0e0f...master

**Review by emilazy — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351499`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.stfl</li>
    <li>newsboat</li>
    <li>smuxi</li>
    <li>stfl</li>
  </ul>
</details>

and it builds on `x86_64-darwin`. LGTM

**Pull request merged**
