### PR TITLE
nixos/no-x-libs: fix infinite recursion with ffmpeg

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

Regression from #211834

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
Not too familiar with no-x-libs but why does that result in an infinite recursion? `ffmpeg_4-minimal` is defined as `ffmpeg_4.override { ffmpegVariant = "headless"; }`.

If that fixes it, go for it but I really don't understand why it's necessary.

**Comment by Artturin** [comment]
> Not too familiar with no-x-libs but why does that result in an infinite recursion? `ffmpeg_4-minimal` is defined as `ffmpeg_4.override { ffmpegVariant = "headless"; }`.
> 
> If that fixes it, go for it but I really don't understand why it's necessary.

The overlay overrides ffmpeg_4 so ffmpeg_4-minimal is overriding the override here

This is why overrides in all-packages.nix should be avoided

**Comment by Atemu** [comment]
Shouldn't the proper fix be to use `final`/`self` rather than `prev`/`super` then?

But I can see where you're coming from and sort of agree with the caveat that we still need to inherit Darwin frameworks and I don't like the idea of duplicating that code for every ffmpeg "invocation".

**Comment by SuperSandro2000** [comment]
Would using final interfere with other overlays?

**Comment by Atemu** [comment]
Not sure. How can I test that without evaluating a whole NixOS system?

**Comment by Artturin** [comment]
> Not sure. How can I test that without evaluating a whole NixOS system?

its just a normal overlay so it can be tested like normal

> Shouldn't the proper fix be to use final/self rather than prev/super then?

that would be a double infinite recursion :P

**Comment by Artturin** [comment]
See this discussion https://github.com/NixOS/nixpkgs/pull/204287#discussion_r1038935853

**Comment by SuperSandro2000** [comment]
So, do I need to do anything here or can we merge this?

**Pull request merged**
