### PR TITLE
mermaid-filter: init at 1.4.6

### PR DESCRIPTION
**Pull request by chasecaleb**
https://github.com/raghur/mermaid-filter

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

FYI @nyarly I see that you requested this in #173666... here you go!

### CODE REVIEW

**Comment by nyarly** [comment]
Thanks, @chasecaleb - I'll look forward to this getting merged. Looks like there's a conflict?

**Comment by chasecaleb** [comment]
@nyarly Yup, that's unsurprising since it's a month and a half old now with the way the massive `node-packages.nix` file works. I'll regenerate it. The script takes a while to run so I'll have a new commit pushed in a couple hours.

**Comment by chasecaleb** [comment]
@nyarly Ready for review/merge now. I rebased onto master and re-ran `./pkgs/development/node-packages/generate.sh` to regenerate `node-packages.nix`.

**Comment by chasecaleb** [comment]
Well... clearly no one is interesting in reviewing or merging this, so I'm not going to spend time regenerating `node-packages.nix` again. If anyone is interested in the future, feel free to take over this and use my work as a starting point.

**Comment by chasecaleb** [comment]
@Luflosi Thanks for pointing that out! However I figured out I can use mermaid's CLI directly to do what I needed so I'm not personally using mermaid-filter anymore.

**Pull request closed without merging**
