### PR TITLE
[Backport release-21.05] Jetbrains products: version bump

### PR DESCRIPTION
**Pull request by drupol**
Backporting to this branch [the commit](https://github.com/NixOS/nixpkgs/commit/57baa7efb78d8eda38ca8955bea1f14e144353b8) that was directly committed to master branch.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128185` at 1282f7e0 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d86e1761dc81899a92a6390e3fc535fb">jetbrains.clion</a></li>
    <li><a href="https://gist.github.com/f22cdf8a2bd2ec26412952ecb7e6b423">jetbrains.datagrip</a></li>
    <li><a href="https://gist.github.com/a0f318576d06d54d89f3f838ddbc4608">jetbrains.goland</a></li>
    <li><a href="https://gist.github.com/b5f91013c1cb16c91e13669453686819">jetbrains.rider</a></li>
    <li><a href="https://gist.github.com/811784bc76b1a5d39b94822af366b0c6">jetbrains.webstorm</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by drupol** [comment]
@edwtjo Can you help on this? Is there a way to trigger again the build?

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 128185 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>7 packages built:</summary>  <ul>    <li>jetbrains.clion</li>    <li>jetbrains.datagrip</li>    <li>jetbrains.goland</li>    <li>jetbrains.idea-community</li>    <li>jetbrains.idea-ultimate</li>    <li>jetbrains.rider</li>    <li>jetbrains.webstorm</li>  </ul></details>

**Comment by drupol** [comment]
Thanks !

What about the next one ?

https://github.com/NixOS/nixpkgs/pull/128191

**Pull request merged**
