### PR TITLE
imagemagick: 7.1.0-6 -> 7.1.0-8

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
Just realised that 7.1.0-7 contains a [security fix](https://github.com/ImageMagick/ImageMagick/blob/071274b98aa4f12844595d8f14d667406069ef22/ChangeLog#L18):

```
2021-09-11  7.1.0-7  Dirk Lemstra <dirk@lem.....org>
  * Fixed incorrect check when module is used as the domain in policy.xml
    that could allow the use of a disabled module. (reference
    https://github.com/ImageMagick/ImageMagick/security/advisories/GHSA-qvhr-jj4p-j2qr).
```

**Comment by SuperSandro2000** [comment]
@ofborg eval
@ofborg build imagemagick

**Comment by dotlambda** [comment]
I went ahead and fixed the hash.

**Comment by dotlambda** [comment]
@ofborg build imagemagick_light imagemagick imagemagickBig python38.pkgs.Wand python39.pkgs.Wand

**Pull request merged**
