### PR TITLE
opam: 2.0.8 -> 2.1.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://github.com/ocaml/opam/releases/tag/2.1.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131572` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dune-release</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>opam</li>
    <li>opam-installer</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
[nix-shell:~/.cache/nixpkgs-review/pr-131572]$ nix log /nix/store/7vsd8z0f3jzgv1kqj86fy5hn0qj1rshl-ocaml4.12.0-opam-repository-2.1.0.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/47az795pg0k6mm127pxkj0n5lpdmjrrz-2.1.0.zip
source root is opam-2.1.0
setting SOURCE_DATE_EPOCH to timestamp 1626964667 of file opam-2.1.0/tests/reftests/var-option.test
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/59w8zqg7cqglx1y5ls35bkc2r2ivca82-download-tool.patch
patching file src/repository/opamRepositoryConfig.ml
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file src/repository/opamRepositoryConfig.ml.rej
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131572` at e7121571 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/23997b6eaf969dedaeaeb79ce6b30b9a">dune-release</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>opam</li>
    <li>opam-installer</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by marsam** [comment]
@GrahamcOfBorg build opam-installer dune-release

**Comment by marsam** [comment]
@GrahamcOfBorg build opam-installer dune-release

**Comment by sternenseemann** [comment]
With these two small fixes to the test suite `dune-release` builds for me. You'll probably want to squash them into your commit.

@ofborg build dune-release

**Review by sternenseemann — APPROVED** [review]

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 131572` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>dune-release</li>
    <li>opam</li>
    <li>opam-installer</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131572` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>dune-release</li>
    <li>opam</li>
    <li>opam-installer</li>
  </ul>
</details>

**Pull request merged**
