### PR TITLE
GNOME 3.14

### PR DESCRIPTION
**Pull request by lucabrunox**
Was closed by github after a merge, bleh. Was #5192

### CODE REVIEW

**Comment by bjornfor** [comment]
Sigh, NM regression still not fixed...

**Comment by domenkozar** [comment]
Upstream merged the patches, we should look into testing those.

**Comment by vcunat** [comment]
Hmm, now it's rather gnome-3.16 being released, but update to that might need more work. 3.14 hopefully only needs the NM fix.

**Comment by lethalman** [comment]
Closed in favor of GNOME 3.16: https://github.com/NixOS/nixpkgs/pull/7357

**Pull request closed without merging**
