### PR TITLE
texlive package list: 2015-09-17 -> 2016-05-15

### PR DESCRIPTION
**Pull request by laMudri**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Supersedes #15292. Followed approach in [default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L35). `nix-build -E 'with import <nixpkgs> {}; texlive.combine { inherit (texlive) scheme-full; }'` runs successfully. Adding updated packages to `fixedHashes.nix` missed out on new packages, but I don't know whether there's some other recommended way of adding new packages.

cc @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
This PR **removes** whole `fixedHashes.nix`.

**Comment by vcunat** [comment]
And I don't understand the connection with the recent 7abe192b0. That one claims to "fix" the problems.

**Comment by laMudri** [comment]
I don't understand `fixedHashes.nix`, or more specifically, why we would want it. With it, building `texlive.scheme-full` complained about lots of incorrect hashes, presumably from packages that have been updated since their entry in `fixedHashes.nix` was last edited. It seems easier to just update `pkgs.nix` whenever someone finds a wrong hash. 7abe192 doesn't appear to add any new packages, so has no `mathpartir`, for example. This PR should supersede it.

**Comment by vcunat** [comment]
`fixedHashes.nix` contains hashes of the resulting store paths (for non-binary packages). That way you won't get rebuild even if stdenv changes. Without it, all texlive packages will get redownloaded/rebuilt every now and then, consuming space again.

**Comment by laMudri** [comment]
Okay. I don't understand how that works, but I can believe it. So how should new packages be added?

**Comment by vcunat** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/16391. Some things are easier done than explained...

**Pull request closed without merging**
