### PR TITLE
ns-usbloader: fix dependencies for gtk file picker

### LINKED ISSUE #272798: ns-usbloader crashes when trying to open file picker
### Describe the bug
when i click on any button that would open a file picker the program crashes with these errors
```
(java:61243): GLib-GIO-ERROR **: 01:08:49.051: No GSettings schemas are installed on the system
fish: Job 1, 'sudo ns-usbloader' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### Steps To Reproduce
1. add `programs.ns-usbloader.enable = true` to your system configuration and rebuild
2. launch `ns-usbloader`
3. click on "select files"

### Expected behavior
a file picker should open

### Screenshots
N/A

### Additional context
I am using a the `plasmawayland` session

### Notify maintainers

@soupglasses 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.3-zen1, NixOS, 24.05 (Uakari), 24.05.20231201.91050ea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by soupglasses**
## Description of changes

Adds in the relevant dependencies for the GTK file picker for non-GNOME users. This also fixes running `ns-usbloader` with sudo, but this is really not recommended.

Closes #272798 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by soupglasses** [comment]
I would love @NekoNoor to test this package before it gets merged. While from my testing it should fix their issue, I do not have a plasma desktop and may still be pulling items from GNOME by accident.

**Comment by soupglasses** [comment]
If you have flakes enabled, it can be run by `nix run github:soupglasses/nixpkgs/ns-usbloader/fix-file-picker#ns-usbloader`.

**Comment by NekoNoor** [comment]
> If you have flakes enabled, it can be run by `nix run github:soupglasses/nixpkgs/ns-usbloader/fix-file-picker#ns-usbloader`.

it works! :)

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 272882` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ns-usbloader</li>
  </ul>
</details>


LGTM!

**Pull request merged**
