### PR TITLE
mcaselector: move makeWrapper to preFixup

### PR DESCRIPTION
**Pull request by MathiasSven**
## Description of changes

Add missing `gappsWrapperArgsHook` to fix crash when trying to open files.

Follow-up from https://github.com/NixOS/nixpkgs/pull/280536

@Scrumplex @Aleksanaa

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Aleksanaa — APPROVED** [review]
Forgot it, thanks

**Review by eclairevoyant — COMMENTED** [review]
This seems clunky, can we not use `fixupPhase` to do the wrapping instead? The hook is already implicitly run prior to fixup:

https://github.com/NixOS/nixpkgs/blob/0538b69494d17c75765b5096c4f9d94825fa4ace/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L37

Besides, the fixup phase is meant for such wrapping.

**Comment by MathiasSven** [comment]
> This seems clunky, can we not use `fixupPhase` to do the wrapping instead? The hook is already implicitly run prior to fixup:
> 
> https://github.com/NixOS/nixpkgs/blob/0538b69494d17c75765b5096c4f9d94825fa4ace/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L37
> 
> Besides, the fixup phase is meant for such wrapping.

Would that not incur double wrapping? Aleksanaa had raised concerns on the previous PR about avoiding that, as it is also clunky. Is there a solution that makes use of `fixupPhase` and also avoids double wrapping?

We are already making a wrapper in the `installPhase`, and moving that to the `fixupPhase` would not be appropriate I think. So the `fixupPhase` would have to fix the wrapper already made in the `installPhase`.

**Comment by eclairevoyant** [comment]
> Would that not incur double wrapping?

No, why would it?

**Comment by MathiasSven** [comment]
> > Would that not incur double wrapping?
> 
> No, why would it? Automatic wrapping is disabled, and you are wrapping manually.

Oh, you meant move the whole `makeWrapper` command from `installPhase` to fixup. I find that a bit odd for a fixup. I have force-pushed the changes.

**Review by eclairevoyant — APPROVED** [review]
wrapping seems fine now
```
# The C-code for this binary wrapper has been generated using the following command:
makeCWrapper '/nix/store/ns7vswbn2xd04n2fp2c3d1vli895gbnh-openjdk-21+35/bin/java' \
    --add-flags '-jar /nix/store/zzrvyysdnf8srkh2qjc2f77bl8nqhqj7-mcaselector-2.4/lib/mcaselector/mcaselector.jar' \
    --prefix 'GIO_EXTRA_MODULES' ':' '/nix/store/r2b8ri3mv9py2k1pidnjf40y65zlfdwn-dconf-0.40.0-lib/lib/gio/modules' \
    --prefix 'GIO_EXTRA_MODULES' ':' '/nix/store/r2b8ri3mv9py2k1pidnjf40y65zlfdwn-dconf-0.40.0-lib/lib/gio/modules' \
    --set 'GDK_PIXBUF_MODULE_FILE' '/nix/store/kiw21a3r5dbr60x7f3hw4xxs4926380a-librsvg-2.58.0/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache' \
    --prefix 'XDG_DATA_DIRS' ':' '/nix/store/a2xf8sr12rcps2175198hhy5n2z3ifl1-gsettings-desktop-schemas-46.0/share/gsettings-schemas/gsettings-desktop-schemas-46.0:/nix/store/5vsqfbim3kvkhinmw0shv9a4ag2dwkd4-gtk+3-3.24.41/share/gsettings-schemas/gtk+3-3.24.41'
# (Use `nix-shell -p makeBinaryWrapper` to get access to makeCWrapper in your shell)
```

**Pull request merged**
