### PR TITLE
Unbreak cabal-plan-bounds on 9.6, add myself as maintainer

### PR DESCRIPTION
**Pull request by nomeata**
Replaces https://github.com/NixOS/nixpkgs/pull/242609

### CODE REVIEW

**Comment by nomeata** [comment]
Not quite sure if this is a sensible thing to do, but these build fine with 9.6.

**Comment by maralorn** [comment]
Sorry, for not reacting earlier.
unmarkBroken is more of a tool for downstream users, we use it rarely in nixpkgs.

The workflow here is: 
1. Remove the package names from our broken.yaml file.
2. Run maintainers/scripts/haskell/regenerate-hackage-packages.sh
3. To fit the contributors guide prefix your commit with "haskellPackages.cabal-plan-bounds" or something similar.

**Comment by nomeata** [comment]
Right, but how do I mark it broken on just GHC-9.6 - it's broken on the default GHC because of the base-compat version there (IIRC)

**Comment by maralorn** [comment]
Oooh, I was too tired reviewing this. Yeah, no, let’s leave it like this. I can reword the commit message when merging.

**Comment by maralorn** [comment]
Merged in 2d4a6546e7b113f8780f4e65b2dc47ab1f021e2f.

**Comment by maralorn** [comment]
@nomeata, note that, I think, currently there is no hydra job for these packages on ghc 9.6. So we will not automatically notice and inform you if they break.

**Pull request closed without merging**
