### PR TITLE
GHC-9.6 fgl and warp

### PR DESCRIPTION
**Pull request by np**
## Description of changes

Fix build for GHC-9.6 for fgl and warp

## Things done

- Built on platform(s)
  - [x] x86_64-linux

### CODE REVIEW

**Comment by cdepillabout** [comment]
@np Could you rebase this on the `haskell-updates` branch?  We generally ask that all Haskell-related changes go to the `haskell-updates` branch.

Other than that, this LGTM.

**Comment by np** [comment]
Thanks for the review, I hope it's good now.

**Comment by np** [comment]
Rebased again.

**Comment by cdepillabout** [comment]
@ofborg build haskell.packages.ghc96.fgl haskell.packages.ghc96.fourmolu haskell.packages.ghc96.servant haskell.packages.ghc96.warp_3_3_28

**Comment by cdepillabout** [comment]
Looks good, thanks!

**Pull request merged**
