### PR TITLE
torchtext: init at 0.4.0

### PR DESCRIPTION
**Pull request by vladmaraev**
###### Motivation for this change
Add torchtext: https://torchtext.readthedocs.io/en/latest/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jyp

### CODE REVIEW

**Review by nlewo — CHANGES_REQUESTED** [review]
Could you create two commits, one for adding yourself in the maintainer list (with a commit message such as: `maintainers: add vladmaraev`) and another one with the package?

Otherwise, looks good to me:)
And thanks for your contribution!

**Comment by mmahut** [comment]
@GrahamcOfBorg build pythonPackages.torchtext python3Packages.torchtext

**Comment by vladmaraev** [comment]
@nlewo thanks for your feedback, I have made a change that you requested.

**Comment by mmahut** [comment]
@GrahamcOfBorg build pythonPackages.torchtext python3Packages.torchtext

**Comment by Lassulus** [comment]
fails to build for me:
```
builder for '/nix/store/1qz3pvwcsacyn6vn0ijml2zvzkw2y067-python3.7-torchtext-0.4.0.drv' failed with exit code 1; last 10 log lines:
      tests = self.loadTestsFromModule(package, pattern=pattern)
    File "/nix/store/3n4mnz8acknbgydi3dx15jmjns55avjf-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
      tests.append(self.loadTestsFromName(submodule))
    File "/nix/store/c2n0xp0j3nacr1l17lmrdzwp16ljsvll-python3-3.7.5/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
      return self.loadTestsFromModule(obj)
    File "/nix/store/3n4mnz8acknbgydi3dx15jmjns55avjf-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
      tests.append(self.loadTestsFromName(submodule))
    File "/nix/store/c2n0xp0j3nacr1l17lmrdzwp16ljsvll-python3-3.7.5/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
      test = obj()
  TypeError: batch() missing 2 required positional arguments: 'data' and 'batch_size'
cannot build derivation '/nix/store/3bdv4w02sh9cv3qc99s2c8b8h0z7gk2r-env.drv': 1 dependencies couldn't be built
[3 built (1 failed), 13 copied (27.7 MiB), 7.8 MiB DL]
error: build of '/nix/store/3bdv4w02sh9cv3qc99s2c8b8h0z7gk2r-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/70655
1 package failed to build:
python37Packages.torchtext
```

**Pull request closed without merging**
