### PR TITLE
vscode-extensions.jnoortheen.nix-ide: 0.1.23 -> 0.2.1

### PR DESCRIPTION
**Pull request by ryoku-cha**
###### Description of changes

Updated VS Code Extension - Nix IDE to the current version
https://github.com/nix-community/vscode-nix-ide/releases/tag/v0.2.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryoku-cha** [comment]
I'm new to NixOS and this is my first Package Update. Not sure i did everything right. 
I built the package but i currently have no idea how to test it (it's a VS Code Extension, not a executable that can be executed directly).

**Comment by SuperSamus** [comment]
```bash
nix-shell -p "(vscode-with-extensions.override {vscodeExtensions = with vscode-extensions; [ jnoortheen.nix-ide ]; })" -I nixpkgs=.
```

(`nixpkgs=.` assumes that you are in your local nixpkgs directory, if you are not, replace the period with its absolute path)

**Comment by ryoku-cha** [comment]
@SuperSamus thanks for the hint.
I just tried it. There was no Output, not sure if it did something. The Extension did not show up in VS Code afterwards. But that's probably because of my current lack of understanding how NixOS works and how exactly I have to define it.

I need some Rest and then learn more about NixOS and try again ...

**Comment by SuperSamus** [comment]
Did you open `code` from the shell you ran the command on?
`nix-shell` doesn't "install" programs the traditional way, it creates a temporary environment. You have (at least) two VS Code installed: the "regular" one (from `configuration.nix`), which is the one opened by launching it normally, and the one opened only by launching it inside the `nix-shell`.
Or maybe you had multiple instances of VS Code opened: Nix programs aren't sandboxed, and having different versions of VS Code open at the same time can cause problems with the extensions.

Anyway, I tested it myself, it seems to work fine.
image

**Comment by SuperSandro2000** [comment]
Title should be ``vscode-extensions.jnoortheen.nix-ide``.

**Comment by ryoku-cha** [comment]
Thanks for all the help and testing the package @SuperSamus .

@SuperSandro2000 right thanks, I updated the PR title to the correct name.

**Comment by SuperSandro2000** [comment]
You forgot the commit.

@ofborg build vscode-extensions.jnoortheen.nix-ide

**Pull request merged**
