### PR TITLE
Zrythm: 1.0.0-alpha.28.1.3 -> 1.0.0.beta.2.2.2 

### PR DESCRIPTION
**Pull request by FedX-sudo**
###### Description of changes
This is a work in progress to update Zrythm from 1.0.0-alpha.28.1.3 to 1.0.0.beta.2.2.2. However, beta.2.2.2 is incompatible with NixOS as it requires libadwaita 1.1.2, but Nix only has 1.1.1. Therefore I am pushing the version in the file to beta.2.0, as it is libadwaita 1.1.1 compatible. 

I am also trying to debug an issue I have found with the NixOS build of Zrythm before merge: It hangs on the initial boot wizard and does not proceed. I am unsure why this is occurring, but I would like to attempt to fix the bug before merging. 

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FedX-sudo** [comment]
EDIT: There is another bug as well, on Gnome Zrythm will not launch at all because it cannot find icons. I am not sure if this bug is related to the first one or not, but nevertheless, I believe it would be beneficial to get to the bottom of one (or both) of these bug before merge.

**Comment by ajs124** [comment]
> as it requires libadwaita 1.1.2, but Nix only has 1.1.1

maybe we should update libadwaita then

**Comment by alex-tee** [comment]
> I think we need to reach out to the creator of Zrythm about a few of these dependencies. `libadwaita` 1.1.2 hasn't been released yet. Also `libpanel`, which has been added, is an alpha library releases at all. I've been working on a PR fixing all of the broken dependencies as well, but a lot of stuff has changed with zrythm recently and I haven't been able to get it to build.

I suggest packaging the previous release before the libadwaita version bump and the addition of libpanel

**Comment by magnetophon** [comment]
@alex-tee Thanks!

In case it wasn't clear to everyone: Alex is the main author.

**Comment by FedX-sudo** [comment]
This PR has what appears to be the latest version that will build against the required dependencies. Unfortunately, I have been seeing some bugs with Zrythm that leave me tentative to merge it. Namely, it appears that (under Plasma at least) dconf is not working for some reason, causing the initial wizard to loop, and never save the user settings.

**Pull request closed without merging**
