### PR TITLE
Nvidia x86 64 vulkan icd

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
related: https://github.com/NixOS/nixpkgs/pull/135024#issuecomment-1030030941

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
The commit messages got swapped

**Comment by jonringer** [comment]
lol, thanks

**Comment by LunNova** [comment]
https://www.githubstatus.com/incidents/vvthhf8gxt80 maybe? seeing some issues elsewhere

**Comment by Baughn** [comment]
Could we perhaps roll this back?

Steam has been mostly broken since it was merged, and #157907 looks like it has some distance to go. If the change in this PR is necessary, then it'd be better to revert the revert as part of #157907.

**Comment by tfmoraes** [comment]
@Baughn I'm using this workaround https://discourse.nixos.org/t/steam-proton-games-1-fps/17794/2

**Comment by Baughn** [comment]
And I'm using a different workaround. But we shouldn't require every nixos user to find their own workarounds...

**Pull request merged**
