### PR TITLE
Remove smos

### PR DESCRIPTION
**Pull request by NorfairKing**
###### Motivation for this change

* This package is outdated.
* The static build that was used didn't actually work.
* There is no more static build for smos.

### CODE REVIEW

**Comment by bobby285271** [comment]
Please add a throw in `pkgs/top-level/aliases.nix`.

**Comment by NorfairKing** [comment]
@bobby285271 I can, but I'm pretty sure that there are 0 users because this didn't work.

**Comment by NorfairKing** [comment]
If anyone finds this PR because they still wanted to use smos via Nix, they can look at the docs here: https://docs.smos.online/building-installation

**Comment by thiagokokada** [comment]
> @bobby285271 I can, but I'm pretty sure that there are 0 users because this didn't work.

Adding an aliases is still a good idea, because if someone wants to look why this package was removed there is generally an explanation inside the the alias (like `this package was removed because it was outdated and the static build didn't work`).

**Pull request merged**
