### PR TITLE
winePackages.{stable,unstable,staging}: cleanups

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

- Make util-linux conditional in wine-staging due to `uuid.h` conflicts;
- Remove `lib.overrideDerivation`, allowing wine-staging overrides;
- Use `overrideSDK` to build with the 11.0 SDK with a 10.7 deployment target, matching the deployment target of the unofficial Mac packages;
- Drop all Darwin-related patches. They’re not needed with the 11.0 SDK;
- Switch to conditionally using `badPlatforms` instead of using a mix of `broken` and filtering Darwin from `meta.platforms`; and
- Remove unnecessary rpath references to Darwin frameworks.

I confirmed that my FFXIV derivation works with these changes, and I can use `overrideAttrs` with wine-staging.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

---
###### Maintainer pings

cc @avnik @7c6f434c @bendlas @jmc-figueira

### CODE REVIEW

**Comment by reckenrode** [comment]
Fixed evaluation on Linux and added some comments.

**Comment by 7c6f434c** [comment]
Just in case, if the patches are being cleaned up: is the certificate patch applied to stable but not unstable?

**Comment by reckenrode** [comment]
> Just in case, if the patches are being cleaned up: is the certificate patch applied to stable but not unstable?

I only dropped the Darwin-specific patches. The certificate patch is still applied (to stable, unstable, and staging). I’ll clarify the commit message to make that clear.

**Comment by 7c6f434c** [comment]
Then I don't undertand what happens (possibly it's my failure to see some effect — or a preexisting problem). The patch is mentioned once, in `sources.nix`, only for «stable», and I found no logic that would apply it to «unstable». What am I missing?

**Comment by reckenrode** [comment]
> Then I don't understand what happens (possibly it's my failure to see some effect — or a preexisting problem). The patch is mentioned once, in `sources.nix`, only for «stable», and I found no logic that would apply it to «unstable». What am I missing?

Unstable inherits the patch from stable. Because staging is defined as an override/overrideAttrs of unstable, it also picks up the patch from stable.

https://github.com/NixOS/nixpkgs/blob/5038fa2ce11a8306a25cc9e98df36c6ae5776285/pkgs/applications/emulators/wine/sources.nix#L70-L75

**Comment by reckenrode** [comment]
Is there anything else needed to move this forward? It would be nice if it could make 24.05, so 24.05 can get the improvements to overriding wine-staging.

**Pull request merged**
