### PR TITLE
pinball: fix build error

### PR DESCRIPTION
**Pull request by sophrosyne97**
###### Motivation for this change
ZHF: #122042
cc @NixOS/nixos-release-managers
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by risicle — APPROVED** [review]
WFM nixos x86_64

**Comment by SuperSandro2000** [comment]
autoreconfHook already includes automake https://github.com/NixOS/nixpkgs/blob/c83536ebca78b481059c9f11920d86a5612d2919/pkgs/top-level/all-packages.nix#L144

**Comment by sophrosyne97** [comment]
It won't build for me unless I pull in automake directly; it depends on aclocal and cannot find it through autoreconfHook for some reason, and the build fails if I don't have automake.

**Comment by sophrosyne97** [comment]
Sorry did not mean to reopen, is there some other approach that I might not be considering? From my testing I cannot seem to make it build without including automake.

**Pull request closed without merging**
