### PR TITLE
gitlab:12.8.8 -> 12.8.9

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change

  - gitaly: 12.8.8 -> 12.8.9
  - gitlab-workhorse: 8.21.1 -> 8.21.2
  - gitlab: 12.8.8 -> 12.8.9
    See
    https://about.gitlab.com/releases/2020/04/14/critical-security-release-gitlab-12-dot-9-dot-3-released/
    for details.
  - gitlab: support passing --rev to the `update-all` script
    While it's already possible to invoke `update-data` with the `--rev`
    argument, one still needs to run all later phases manually.
    Fix this, by having `update-all` also accept a `--rev` argument, and
    pass it down to `update-data`.
    Also, make the help text a bit more usable, by suggesting the usual
    versioning scheme used these times.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Hm, there seems to be some bundler version incompatibilities in our bundlerEnv:

```
bundler: failed to load command: rake (/nix/store/xkqpm8v228zsk16qprf5hxc3yw2jnr2b-gitlab-env-12.8.9/lib/ruby/gems/2.6.0/bin/rake)
Gem::LoadError: You have already activated bundler 1.17.2, but your Gemfile requires bundler 2.1.4. Since bundler is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports bundler as a default gem.
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:312:in `check_for_activated_spec!'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:31:in `block in setup'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:147:in `each'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:147:in `each'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:26:in `map'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:26:in `setup'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `block in <top (required)>'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /nix/store/hindv16l90d7i4n3hk5l1x73nj068kyp-bundler-2.1.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `<top (required)>'
builder for '/nix/store/djq9vpdl88p5g6y78kh4r8cfrq3gv1wx-gitlab-assets-12.8.9.drv' failed with exit code 1
```

**Comment by flokli** [comment]
This seems to be another invocation of https://github.com/nix-community/bundix/issues/63. pinging @manveru.

**Comment by manveru** [comment]
@flokli is there a specific reason to use bundler 1.x here?

**Comment by flokli** [comment]
@manveru we just invoke `bundix` - see https://github.com/NixOS/nixpkgs/pull/85623/files#diff-e8f8af88c7b2537de05e9e8bbcd945ccL138.

**Comment by manveru** [comment]
It's important that you use bundix from the same nixpkgs version, so bundler won't differ.

**Comment by flokli** [comment]
I did set `NIX_PATH=nixpkgs=/path/to/nixpkgs-gitlab`, and then invoked `update.py`, which uses a nix-shell to provide bundix.

This should be correct, shouldn't it?

**Comment by manveru** [comment]
I changed the `update.py` to call `bundix -l` instead, to force writing the lockfile. There's still a problem with Bundix treating the warning that bundler emits about upgrading the lockfile version as an error.
To work around that, I invoke `bundle lock` separately, and then run a simple `bundix` afterwards:

```
diff --git a/pkgs/applications/version-management/gitlab/update.py b/pkgs/applications/version-management/gitlab/update.py
index a2a3a6d05b7..29a0ddee757 100755
--- a/pkgs/applications/version-management/gitlab/update.py
+++ b/pkgs/applications/version-management/gitlab/update.py
@@ -1,5 +1,5 @@
 #!/usr/bin/env nix-shell
-#! nix-shell -i python3 -p bundix common-updater-scripts nix nix-prefetch-git python3 python3Packages.requests python3Packages.lxml python3Packages.click python3Packages.click-log vgo2nix yarn2nix
+#! nix-shell -i python3 -p bundix bundler common-updater-scripts nix nix-prefetch-git python3 python3Packages.requests python3Packages.lxml python3Packages.click python3Packages.click-log vgo2nix yarn2nix
 
 import click
 import click_log
@@ -135,6 +135,7 @@ def update_rubyenv():
         with open(rubyenv_dir / fn, 'w') as f:
             f.write(repo.get_file(fn, rev))
 
+    subprocess.check_output(['bundle', 'lock'], cwd=rubyenv_dir)
     subprocess.check_output(['bundix'], cwd=rubyenv_dir)
 
 
@@ -174,7 +175,8 @@ def update_gitaly():
         with open(gitaly_dir / fn, 'w') as f:
             f.write(repo.get_file(fn, f"v{gitaly_server_version}"))
 
-    subprocess.check_output(['bundix'], cwd=gitaly_dir)
+    subprocess.check_output(['bundle', 'lock'], cwd=gitaly_dir)
+    subprocess.check_output(['bundix'], cwd=gitaly_dir)
 
     os.environ['GOROOT'] = ""
     subprocess.check_output(['vgo2nix'], cwd=gitaly_dir)
```

There's still an error from vgo2nix, but I think that's out of scope for me :)

**Comment by flokli** [comment]
@manveru thanks for taking a look!

I didn't run into the `vgo2nix` error, and applied your suggestion as a commit in the (now updated) PR.

I successfully managed to build gitlab with it, currently running the tests.

Is there a bug report open about `bundix -l` misinterpreting the warning as an error?

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
Thanks @petabyteboy for merging this! Did you also backport to 20.03?

**Comment by petabyteboy** [comment]
I just did so in https://github.com/NixOS/nixpkgs/commit/9153c23157a

**Comment by flokli** [comment]
The backport was missing the other commits in here.

Backported in c69934e1b946dbe7eea6986777c5004349a91400, 0364b92be6d2a6c0ad5acb08641b168e22eea73a, e2650954d3e2f9ff380bd0a93c63c7b762133c84 and e97d89fde2e4dc67a50e4414a2e1265a223ec60c.

Will do 19.09 shortly.

**Comment by flokli** [comment]
Backported to 19.09 in 7b9f3c89f35, 57df0aad151, 767ca3624c5, 68169a7ffa6 and a7ceb2536ab.

**Comment by petabyteboy** [comment]
Thanks for fixing my mistake with the other commits.

**Pull request merged**
