### PR TITLE
krb5: add support for building with LDAP database

### PR DESCRIPTION
**Pull request by nessdoor**
## Description of changes
The derivation for the MIT Kerberos implementation includes OpenLDAP in its closure, but the switch to actually build the LDAP database backend and utilities had not been flipped.

This PR introduces the ability to specify `withLdap = true`  as an argument to the derivation, so that an LDAP-enabled MIT Kerberos can be built.
The LDAP flag is turned off by default as a precaution (couldn't really wrap my head around the implications for the `libOnly` build), but I would be happy to see this changed in the future.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
This will need to be retargeted at staging using the technique outlined in https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by risicle** [comment]
Total guess but it's possible ldap support used to be enabled by default in previous versions and we bumped past a version disabling it without realizing the package didn't have ldap support anymore..

**Comment by nessdoor** [comment]
> This will need to be retargeted at staging

Sure thing, I will try to do it tomorrow (I hope I can pull that off, sounds kind of scary).

> One thing you may discover though is that without a version of this package building with ldap support anymore, it may get broken without anyone noticing.

I think this needs a proper NixOS test in the future, but I will leave that for another PR. If your guess is true, then the lack of an integration test is exactly the reason why LDAP support got disabled without anyone noticing.

**Comment by nessdoor** [comment]
@risicle I think I managed.

As soon as this commit gets merged into master, I will try and see if I can come up with a simple and effective OpenLDAP/MIT Kerberos integration test (my own infrastructure depends on it, after all).

I would be glad if you could point at any other changes you think I should be making. Thank you!

**Comment by risicle** [comment]
Cool, I think this is quite a safe change - I managed to build it myself on macos and nixos.

**Review by risicle — APPROVED** [review]

**Pull request merged**
