### PR TITLE
Altcoins - a new category of applications

### PR DESCRIPTION
**Pull request by AndersonTorres**
Here, I present a new level of hierarchy on Nixpkgs: the Altcoins.

The idea is to put a single cryptocurrency per file, and build them
using expressions like altcoins.bitcoin. I believe this ordering is
clearer and more maintainable that the current one.

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Why Travis is failing so much? :(

**Comment by vcunat** [comment]
The last one doesn't seem an error but rather a timeout (50 minutes). @offlinehacker: ping.

**Comment by vcunat** [comment]
It makes much sense to me to group these packages in that way (but I don't really use any of them).

**Comment by AndersonTorres** [comment]
How about that commit? I wanna add some other altcoins to it.

**Comment by copumpkin** [comment]
Seems weird to stick bitcoin under altcoins, when the "alt" is in reference to being an alternative to bitcoin.

**Comment by copumpkin** [comment]
Would make more sense to me to make the category called "cryptocurrencies", and then there's not an implied bitcoin-centrism.

@roconnor @oconnorr you have opinion?

**Comment by copumpkin** [comment]
Oh, I see you commented on this already in the outdated diff:

> Well, think they are all "altcoins", because the "default coins" are the physical ones, like American dollar and Brazilian real. And all these coins are similar in concept, so putting them in a hierarchy like this is more interesting than to split in separate files of Nixpkgs tree.

I don't think that's true. If you look in common usage, the "alt" is clearly in reference to bitcoin. People say things like "litecoin is the biggest altcoin", and altcoin listings (almost?) never include bitcoin.

**Comment by vcunat** [comment]
Hmm, correct according to [wikipedia](https://en.wikipedia.org/wiki/Altcoin) (and the source). Something like "cryptocurrencies" sounds a better name, although it's a bit long to type :-)

**Comment by AndersonTorres** [comment]
IN fact, Wikipedia says this in a confused manner: Wiki admits cryptocurrencies are alternatives to physical money, but says altcoins as all digital currencies except BTC.

Well, maybe we can just use digitalCurrency instead of altcoin?

**Pull request merged**
