### PR TITLE
Remove unmaintained npm2nix; node2nix is now

### LINKED ISSUE #64739: npm2nix should be removed from nixpkgs
## Issue description

[npm2nix](https://github.com/NixOS/npm2nix) is unmaintained, superseded by node2nix and should therefore be removed from nixpkgs

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

### PR DESCRIPTION
**Pull request by chaoflow**
###### Motivation for this change

close #64739 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jb55 — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]
When I worked on getting rid of `npm2nix` builds in `nixpkgs` about two years ago I kept this alias for backwards compatibility in case someone uses it for personal stuff. As it's unmaintained for some time now and shouldn't be used anymore, I'm all in favor of dropping this :+1:

**Comment by Ma27** [comment]
Oh and can you please resolve the merge conflict? :)

**Comment by chaoflow** [comment]
@Ma27 Done

**Comment by Ma27** [comment]
Updated the commit message to match the requirements in CONTRIBUTING.md.

**Comment by Ma27** [comment]
@chaoflow thanks!

**Pull request merged**
