### PR TITLE
New Haskell package: yesod-markdown

### PR DESCRIPTION
**Pull request by nkaretnikov**

### CODE REVIEW

**Comment by ocharles** [comment]
It looks like that wasn't generated by `cabal2nix` - could you please install that and use it to generate the `default.nix` file?

**Comment by nkaretnikov** [comment]
It was, but I had to edit the license field myself because the
auto-generated one said just "GPL", which is not correct, so I didn't
include the "auto-generated by cabal2nix" comment.

However, I now see that I picked the wrong license.  I've thought that
if there are no license headers anywhere, one can assume the "or any
later version" clause, which is not true.  So, I regenerated the file
with cabal2nix from Nixpkgs, changed the license to gpl2 manually,
removed the "auto-generated" comment again, and force-pushed.  I hope
this version is fine.

**Comment by ocharles** [comment]
@peti I'm unclear of what should be done here - could you chime in whether or not @nkaretnikov needs to do anything more?

**Comment by ryantm** [comment]
It looks like this is a fundamental incompatibility with how Cabal and Nix are managing licenses, if this is the type of licenses in a Cabal file https://github.com/haskell/cabal/blob/ea8735aafc301b3726a3c959130cb20441b38461/Cabal/Distribution/Simple/GHC/IPI642.hs#L79 . It seems better to use cabal2nix without manual intervention and address this incompatibility separately.

**Comment by peti** [comment]
Personally, I stopped updating Haskell packages outside of `pkgs/development/haskell-modules` because I don't use them any more. So unless someone else picks up the task of running `hackage4nix` on that tree once in a while, those Haskell expressions will no longer be re-generated automatically, which means that you're free to edit them as you please. It's the wild west out there now. :-)

@nkaretnikov, if you feel that the license of that package is not properly specified in the Cabal file, then IMHO the best thing to do is to inform the upstream author about this issue so that he can fix his package. Ultimately, editing these files manually is not going to scale with 8000 Haskell packages out there. We have a strong interest in helping to make the Cabal files consistent (and other distributions have the same interest).

**Comment by nkaretnikov** [comment]
@ryantm FWIW, cabal init allows to select GPL-2 and GPL-3.

@peti I pushed the patch upstream, the maintainer bumped the version and uploaded it to Hackage, I force-pushed again. Now cabal2nix parses the license field correctly.

**Comment by peti** [comment]
Very cool, thank you for taking care of this issue!

**Pull request merged**
