### PR TITLE
ollama: 0.3.5 -> 0.3.9

### PR DESCRIPTION
**Pull request by abysssol**
## Description of changes

Multiple recent versions have been failing to build (0.3.2, 0.3.3, 0.3.6, and 0.3.8), but it's strangely inconsistent, with 0.3.4, 0.3.5, and 0.3.9 all building without any failures.

@mastoca said [here](https://github.com/NixOS/nixpkgs/pull/336964#issuecomment-2323028955) that the problem appears to be the unit test `TestHomogeneousGPUs`, which is failing on some versions but not others without any currently discernible cause. It's currently unknown whether this is due to actual incorrect code triggering test failures, or spurious test failures due to unrelated code or system incompatibilities.

[changelog 0.3.6](https://github.com/ollama/ollama/releases/tag/v0.3.6)
[changelog 0.3.7](https://github.com/ollama/ollama/releases/tag/v0.3.7)
[changelog 0.3.8](https://github.com/ollama/ollama/releases/tag/v0.3.8)
[changelog 0.3.9](https://github.com/ollama/ollama/releases/tag/v0.3.9)
diff: https://github.com/ollama/ollama/compare/v0.3.5...v0.3.9

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [x] `nix build -f default.nix ollama.tests`
  - [x] `nix build -f pkgs/top-level/release.nix release-checks`
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix run nixpkgs#nixpkgs-review -- rev HEAD`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
  - [x] ollama-rocm: works for me with `HSA_OVERRIDE_GFX_VERSION=10.3.0`
  - [x] ollama-cuda: @mastoca confirmed that cuda works correctly [here](https://github.com/NixOS/nixpkgs/pull/336964#issuecomment-2323090254)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Parsifa1** [comment]
I encountered mismatched hashes when using version 0.3.1

image

Do you know any solutions :(

**Comment by JaviMerino** [comment]
> I encountered mismatched hashes when using version 0.3.1
> 
> image
> 
> Do you know any solutions :(

As a hack, you can work around it by using a version of nixpkgs before the merge:

```
nix shell github:nixos/nixpkgs/18951e72698a#ollama
```

The proper fix is this PR though: update ollama to 0.3.2.

**Comment by abysssol** [comment]
> I encountered mismatched hashes when using version 0.3.1
> Do you know any solutions :(

I apologize for letting this through; it appears that upstream ollama changed the `v0.3.1` tag (which _is_ bad practice), breaking the build. I'll be more careful in the future.

I've created pull request #331780 to fix it.

**Comment by d4g** [comment]
FYI version 0.3.3 is already out.

**Comment by miku86** [comment]
v0.3.4 was also released: https://github.com/ollama/ollama/releases/tag/v0.3.4

**Comment by drupol** [comment]
See https://github.com/NixOS/nixpkgs/pull/333223

**Comment by terlar** [comment]
So was it the params patch that was problematic?

**Comment by drupol** [comment]
How do you want me to find it out by just looking at the two PR?

The issue was most probably coming from upstream, not on us.

**Comment by terlar** [comment]
Ah, I see now, that patch is not in the upstream source anymore. I thought you removed it first. Glad they fixed it upstream and thanks for your work.

**Comment by abysssol** [comment]
> So was it the params patch that was problematic?

I just tried removing `10-params.diff` from my 0.3.2 branch, but the same problem occurred, so I don't think that was the problem.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 331585` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>alpaca</li>
    <li>chatd</li>
    <li>ollama</li>
    <li>ollama-cuda</li>
    <li>ollama-rocm</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]
Runs and operates as expected.

**Pull request merged**
