### PR TITLE
navidrome: 0.47.5 -> 0.48.0

### PR DESCRIPTION
**Pull request by squalus**
###### Description of changes

Updates Navidrome to 0.48.0. Remove the hack added in #191467 as it's no longer necessary.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by isker** [comment]
Tried this out locally and things worked in general, but I had some really strange opus transcode regressions:  on multiple clients transcodes from flac -> opus would hang forever, but only for certain files.  flac -> mp3 (or flac without transcoding) on the same files was fine.  Turned up logging to the highest level and got nothing interesting, navidrome was indicating that it was transcoding/streaming the files as normal.

I'd guess this has to be an ffmpeg problem?  Not sure what to think.

**Comment by squalus** [comment]
Does this happen with the upstream binaries? I've been testing it too and it's working fine for me. But I don't think I'm using the transcoding features.

**Comment by isker** [comment]
This does not happen when I run 48.0 in docker.

Just to clarify, I've been reproducing this by importing a local nixpkgs repo with your branch checked out and using an overlay, like this: 
```
let
  local = import </path/to/squalus/branch> {};
in
{
# . . .
  nixpkgs.overlays =
    [ (self: super:
      {
        navidrome = local.navidrome;
      })
    ];
# . . .
}
```
If I should be doing it some other way, let me know.  I don't have a great understanding of nix.

You can try out the transcoding feature by logging in as an admin user and setting your web browser's player to use opus, so that you have an entry in the players config like this:
Screen Shot 2022-10-23 at 22 25 40

When I do that, and go to play songs, the `/rest/stream` request (which normally downloads the entire audio file) often ends up "succeeding" with a `Content-Length` of 0, or failing with HTTP 416 (which is, I think, a weird equivalent of the former case, given that the requested `Range` is `0-`, i.e. all bytes).  The end result is that the web player UI hangs in the loading state, with a spinner in place of the play button.

I verified that my DB isn't the problem, by starting your branch's 48.0 with an empty data directory such that I get a new DB; transcoding still fails.

This happens with something like half of all the flacs that I try to play.  I could share some if needed over matrix.

**Comment by isker** [comment]
Ah, and navidrome caches transcodings in the data dir.  These size-0 files are probably related:

```
sudo fd -lp --type f 'trans' /var/lib/private/navidrome
-rw------- 1 navidrome navidrome    0 Oct 23 22:27 /var/lib/private/navidrome/cache/transcoding/04/16/0416475a15647fe3e09a8ca41eec044b0745f0b1
-rw------- 1 navidrome navidrome 2.2M Oct 23 23:28 /var/lib/private/navidrome/cache/transcoding/05/cc/05ccd5ab7459ca74e39d3eefe8d896777afbcf5b
-rw------- 1 navidrome navidrome    0 Oct 23 22:27 /var/lib/private/navidrome/cache/transcoding/06/37/0637505ab7b929951a6ee93b3fd463dc6daaa13c
-rw------- 1 navidrome navidrome 3.8M Oct 22 11:12 /var/lib/private/navidrome/cache/transcoding/07/30/07301e0c8d9455760ad2dbf46e93be78238e5122
-rw------- 1 navidrome navidrome 5.2M Oct 22 11:11 /var/lib/private/navidrome/cache/transcoding/0b/77/0b77b0ff470d880b9e0f4c9e0a96d64af3226272
-rw------- 1 navidrome navidrome 2.4M Oct 23 23:28 /var/lib/private/navidrome/cache/transcoding/0b/bb/0bbbf10b19df4245dfa0bba5931f028a6e502326
-rw------- 1 navidrome navidrome 2.2M Oct 23 23:27 /var/lib/private/navidrome/cache/transcoding/12/af/12af5bcc98dc5177179a67d24b9ba6ecf4f225c0
-rw------- 1 navidrome navidrome 5.6M Oct 22 11:12 /var/lib/private/navidrome/cache/transcoding/18/f1/18f19455fc36953ad3c51d1507edbdc16b61cd05
-rw------- 1 navidrome navidrome    0 Oct 23 22:40 /var/lib/private/navidrome/cache/transcoding/19/a0/19a026f748c9f7c8b7989b62d6afe2a57e33f9bd
# . . .
```

**Comment by squalus** [comment]
Thanks for the testing and the info on how to use transcoding! I reproduced the problem as well.

According to strace, navidrome runs a command like this: `ffmpeg -i test.mp3 -map 0:0 -b:a 128k -v 0 -c:a libopus -f opus -`. That works fine when run manually.

But ffmpeg fails with SIGSYS when navidrome runs it. According to the core dump, it dies in numa_init in numactl. The strace log shows set_mempolicy as the last call before the SIGSYS: `set_mempolicy(MPOL_PREFERRED_MANY, [0x0000000000000001], 17) = 5`.

So the module's systemd system call filter is too aggressive. It's set to disallow the @resources set, which includes set_mempolicy. Removing the @resources set lets it run properly for me. Unclear if this happened in the previous version as well, and if so, why the behavior changed.

Updated the PR to fix the system call filters.

**Comment by squalus** [comment]
For testing, files that errored out before will continue to error until you clear your database.

Several upstream bugs that I can see:
- No logging for a dying ffmpeg process
- Zero length file in transcoding cache when ffmpeg dies
- Database permanently thinks there's something in the transcoding cache even if the files go away. Didn't see an obvious way to repair this.

**Comment by isker** [comment]
Wow, thanks for figuring that out.  I tested with your branch's module and everything works for me; thanks for that manual link.

No idea why this worked with the 47.5 module, but it does.  And maybe the ones that were succeeding for me on 48.0 before your fix were hitting the cache from 47.5...

All of the bugs you pointed out are pretty bad.  I'll look into improving it upstream. These are definitely not the first problems I've encountered in this vein.  48.0 is the first version where [the service exits 1 if binding to the configured port fails, instead of hanging around forever](https://github.com/navidrome/navidrome/pull/1638) 🌞.

**Comment by isker** [comment]
I filed https://github.com/navidrome/navidrome/issues/1950 to capture the first and second problem you reported.

**Comment by squalus** [comment]
Removed the module change, since #197476 beat me to it.

**Pull request merged**
