### PR TITLE
quassel-webserver: 2.1.1 -> 2.2.8

### PR DESCRIPTION
**Pull request by uwap**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by uwap** [comment]
@Mic92 Please Review :)

**Comment by joachifm** [comment]
Why add 3000+ lines for this?

**Comment by uwap** [comment]
Because npm2nix is still not a good tool. Is there a better way to package npm projects?

**Comment by uwap** [comment]
@joachifm @mic92 ping?

**Comment by joachifm** [comment]
Too much for one package for my tastes, sorry.

**Comment by joachifm** [comment]
Maybe some of it could be moved to the global nodejs package set or whatever, to reduce the footprint.

**Comment by uwap** [comment]
I will look into it. Thanks.

**Comment by c0bw3b** [comment]
Closing this : `quassel-wbeserver` has been updated to 2.2.8 in #31655

**Pull request closed without merging**
