### PR TITLE
Revert "ncdu: 2.2.2 -> 2.3"

### PR DESCRIPTION
**Pull request by tarc**
This reverts commit 0b6d395909219e21fbd55dd6b321fc1f06a424ab.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Shawn8901** [comment]
not sure if you want to commit to that branch, for nixos branches they are advanced by stuff from the master when builds are successful. likely thats also the case for nixpkgs-unstable, also it would be nice to give some motivation why you want to revert that commit. 

i am not using ncdu, so idk whats going on there, but thats what i recognize when scrolling over the PR

**Comment by ajs124** [comment]
no reasoning given for revert. wrong branch. feel free to fix and reopen, but this change isn't useful, as is.

**Comment by tarc** [comment]
Hi, @Shawn8901 and @ajs124 .

Sorry for the trouble, I was just doing some experiments here, and I thought that marking my PR as a draft wouldn't draw any moderation attention.

By the way, this revert was indeed motivated by a problem I'm facing with `ncdu` on a home-manager setup for macOS, but this is most likely an issue with how I'm setting things.

**Comment by Shawn8901** [comment]
all okay, to get something to build for yourself your dont really need a PR, PRs are more to get some feedback from the community or maintainer on the change request, the draft then basically represents, that you are not yet ready. But thats the reason i gave already feedback, that i thought that you are doing something not intended :slightly_smiling_face:

**Pull request closed without merging**
