### PR TITLE
python3Packages.tensorflow: 2.10.0 -> 2.11.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0

Currently fails to build due to a missing dependency:
```
ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem>=0.23.1; platform_machine != "arm64" or platform_system != "Darwin" (from tensorflow) (from versions: none)
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
I just ended up making the missing dependency optional again: https://github.com/Mic92/nixpkgs/commit/b41f743b50d7c43557430c5fbde671037c6c502f

**Comment by SomeoneSerge** [comment]
I tried looking into packaging `tensorflow-io`, but I'm failing already at fecthing the bazel deps.
Commit: https://github.com/SomeoneSerge/nixpkgs/commit/06a64bdcbd29091a6fc98919d05c8cbdac7fe925
Error: https://gist.github.com/SomeoneSerge/c9cad38bf446126cf5d5cbd09e54925e

**Comment by mweinelt** [comment]
Got the cpu variant to build on x86_64-linux.

**Comment by mweinelt** [comment]
Merging to fix tensorflow cpu usage. Please test cuda support etc. and then we can work on potential issues that are still relevant.

**Pull request merged**
