### PR TITLE
gitlab: 14.1.0 -> 14.1.1

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Motivation for this change

https://about.gitlab.com/releases/2021/07/28/gitlab-14-1-1-released/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131952` at 5a69fb93 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>gitlab</li>
    <li>gitlab-ee</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>gitaly</li>
    <li>gitlab-workhorse</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/version-management/gitlab/gitaly/default.nix:18:23:
```
   |
18 |           patches = [ ../fix-grpc-ar.patch ];
   |                       ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchFromGitHub`.
Near pkgs/applications/version-management/gitlab/gitaly/default.nix:1:25:
```
  |
1 | { lib, fetchFromGitLab, fetchFromGitHub, buildGoModule, ruby
  |                         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

git is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/version-management/gitlab/gitlab-workhorse/default.nix:20:3:
```
   |
20 |   buildInputs = [ git ];
   |   ^
```
</li>
  </ul>
</details>

**Comment by yu-re-ka** [comment]
The NixOS test fails because #132295, but this is unrelated to the changes and it succeeds when removing gitlab pages from the test.

**Comment by flokli** [comment]
> The NixOS test fails because #132295, but this is unrelated to the changes and it succeeds when removing gitlab pages from the test.

Does the test fail before this bump?
I'd prefer if we could keep the tests working. Worst case, comment out these lines in the PR here, and link to the other issue.

**Comment by yu-re-ka** [comment]
> Does the test fail before this bump?

Yes. This bump has nothing to do with it.

> I'd prefer if we could keep the tests working. Worst case, comment out these lines in the PR here, and link to the other issue.

Will do

**Comment by yu-re-ka** [comment]
The CI runners time out, but on a fast machine the test passes.

**Comment by flokli** [comment]
I ran the tests on an EPYC 7502 32-Core Processor, but it fails, being unable to reach the gitaly unix socket:

```
gitlab # [   51.878745] gitaly[1299]: time="2021-08-02T21:44:56Z" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {/tmp/gitaly-internal751169466/ruby.0 /tmp/gitaly-internal751169466/ruby.0 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial unix /tmp/gitaly-internal751169466/ruby.0: connect: no such file or directory\". Reconnecting..." pid=1299 system=system
gitlab # [   51.894352] gitaly[1299]: time="2021-08-02T21:44:56Z" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {/tmp/gitaly-internal751169466/ruby.1 /tmp/gitaly-internal751169466/ruby.1 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial unix /tmp/gitaly-internal751169466/ruby.1: connect: no such file or directory\". Reconnecting..." pid=1299 system=system
gitlab # [   66.894312] gitaly[1299]: time="2021-08-02T21:45:11Z" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {/tmp/gitaly-internal751169466/ruby.0 /tmp/gitaly-internal751169466/ruby.0 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial unix /tmp/gitaly-internal751169466/ruby.0: connect: no such file or directory\". Reconnecting..." pid=1299 system=system
gitlab # [   66.913544] gitaly[1299]: time="2021-08-02T21:45:11Z" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {/tmp/gitaly-internal751169466/ruby.1 /tmp/gitaly-internal751169466/ruby.1 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial unix /tmp/gitaly-internal751169466/ruby.1: connect: no such file or directory\". Reconnecting..." pid=1299 system=system
gitlab # [   76.673333] dovecot[877]: imap-login: Login: user=<alice>, method=PLAIN, rip=::1, lip=::1, mpid=1531, secured, session=<pmFhfJrIPpAAAAAAAAAAAAAAAAAAAAAB>
```

**Comment by flokli** [comment]
I was wrong. The test output was just super super long stuck on that position, but eventually succeeded. Sorry for the noise, let's get this in.

**Pull request merged**
