### PR TITLE
Update libgpiod from 1.6.4 to 2.0.1

### PR DESCRIPTION
**Pull request by adminy**
Bump version of libgpiod

### CODE REVIEW

**Comment by adminy** [comment]
good to merge @expipiplus1 ?

**Comment by expipiplus1** [comment]
Thanks!

**Comment by sigprof** [comment]
Looks like there is a problem with the source hash:
```
2023-07-31T07:44:46.2695270Z error: hash mismatch in fixed-output derivation '/nix/store/5m4ipp546z1rw5dvq409bjary6mm28y9-libgpiod-2.0.1.tar.gz.drv':
2023-07-31T07:44:46.2696207Z          specified: sha256-M68o6YheNXZrDYu6u7pEvyPt2tXhTkVZD3Kv/AXYXA8=
2023-07-31T07:44:46.2697395Z             got:    sha256-tu2lU1YWCo5zkG49SOlZ74EpZ4fXZJdbEPJX6WYGaOk=
```

**Comment by kirillrdy** [comment]
just linking hash was fixed here https://github.com/NixOS/nixpkgs/pull/246252

**Pull request merged**
