### PR TITLE
Fix build of  classy prelude yesod and esqueleto

### PR DESCRIPTION
**Pull request by pSub**
###### Motivation for this change

* classy-prelude-yesod: Running haddock fails due to https://github.com/haskell/haddock/issues/979 ; fixed by skipping Haddock
* esqueleto: Tests expect a postgresql instance and Haddock fails because of https://github.com/haskell/haddock/issues/979 ; fix by skipping tests and Haddock

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pSub** [comment]
I think those fixes should be applied to master as well. However I haven't looked into the state of the master branch yet.

**Review by peti — CHANGES_REQUESTED** [review]
Please also remove those packages from the list of broken builds in `pkgs/development/haskell-modules/configuration-hackage2nix.yaml`. You'll also need to remove the `broken = true` attributes in `hackage-packages.nix`. Without those changes, users won't be able to build the fixed packages.

**Comment by pSub** [comment]
Thank you @peti. I've removed the broken attributes from `hackage-packages.nix` and `configuration-hackage2nix.yaml`.

**Comment by pSub** [comment]
@GrahamcOfBorg build haskellPackages.classy-prelude-yesod
@GrahamcOfBorg build haskellPackages.esqueleto

**Pull request merged**
