### PR TITLE
hackage: update snapshot of 'all-cabal-hashes' repo for callHackage

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Motivation for this change

As discussed in #30832.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
cc @peti

**Comment by vaibhavsagar** [comment]
Thanks!

**Comment by sgraf812** [comment]
I'm not sure what's the process here, but can we have a more automatic update of these hashes? It's extremely annoying that things are always out of date. Or is there some work-around I can install arbitrary newer versions of hackage packages?

**Comment by vaibhavsagar** [comment]
I would also like to see `all-cabal-hashes` get more frequently updated. In the meantime you can override it in an overlay [like this](https://github.com/vaibhavsagar/experiments/blob/d942002b29d806576aee18108b31169c936d98ad/idris/shell.nix#L4-L7).

**Pull request merged**
