### PR TITLE
WIP: allow bgSupport for windowManagers as well

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

see #25978 

I'd like to have some configurable background for windowManagers as well.

This isn't mergable right now, here's a TODO list:

- [x] basic implementation for background-image support
- [ ] test windowManagers
  - [x] i3
  - [ ] XMonad
  - [x] ~Awesome~ :warning: No support for backgrounds with `feh`
  - ...
- [ ] allow directory as well (using `feh --randomize` for multiple backgrounds)
- [x] avoid code duplication (this is stolen from `display-managers/default.nix`, could be moved into a general function to avoid duplicated code)
- [ ] beautify commit history
- [ ] fix merge conflict
- [ ] confirm that desktopManagers still work

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
```icewm``` may require ```${icewm}/bin/icewmbg``` to run always just before ```${icewm}/bin/icewm``` in order to set the background (the settings read from the icewm's preferences file). I have it done in my fork but made no PR expecting no interest.

**Comment by bennofs** [comment]
Why do you need this? If you're running a window manager without a large desktop (like gnome or kde), it IMO still makes sense to at least have a custom desktop session for which you can then use the existing attribute (like https://github.com/bennofs/etc-nixos/blob/61a5014477176ce40bbb7f04cc3d7241a22199c0/conf/desktop.nix#L63-L92)

**Comment by Ma27** [comment]
@bennofs you're right actually. This was just a first idea I wanted to work on (and I always try to contribute such things back to NixOS to support the project), but your approach with a custom desktopManager seems fine as well.

If everybody is fine with this, I'll close this tonight...

**Comment by Ma27** [comment]
ok, closing for now

**Pull request closed without merging**
