### PR TITLE
consul: 0.9.3 -> 1.3.0

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

###### Motivation for this change

Bump consul to a more recent version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Please have a look at #44192 #41243 and #35602 and check questions raised before regarding `consul`.

`python-consul` has been updated in #43972 at least
Terraform and Vault should be ok / Prometheus too
Maybe `confd` is still going to be broken here but the package needs refreshing anyway...

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build consul

**Comment by nh2** [comment]
@c00w A couple questions:

* The stuff I did in https://github.com/NixOS/nixpkgs/pull/41243/files, is any of that still necessary?
* Specifically, should we include the `README` I added that describes how to update consul in nixpkgs?
* Did you try whether the consul UI works?
* Can you let me know what from https://github.com/NixOS/nixpkgs/pull/43972 I have to cherry-patch in order to test this with `python-consul`?

Thanks!

**Comment by nh2** [comment]
Oops, I missed that these questions should go to @vdemeester, not @c0bw3b.

**Comment by arianvp** [comment]
The UI actually breaks with this update.   we either have to explicitly enable `LEGACY_UI`  or do the same as this PR: https://github.com/NixOS/nixpkgs/pull/49082

**Comment by c0bw3b** [comment]
😅 but I do think your README from #41243 should be kept @nh2

**Comment by arianvp** [comment]
Some context: They switched to a `yarn` based UI instead of the current `ruby` based build process. And that's enabled by default in `1.3.0`

**Comment by nh2** [comment]
Hmm, just tried out this PR's consul-1.3.0, but I'm a bit confused: The UI works for me as before, but doesn't look at all like the new UI on https://demo.consul.io/ui/dc1/services (which as per https://www.consul.io/intro/getting-started/ui.html is the default since 1.2.0), but instead looks like the old UI. That desipte I cannot find `CONSUL_UI_LEGACY` being set anywhere.

Why is that?

**Comment by arianvp** [comment]
We currently do not at all build the new UI. We need some extra patches for that.  So (Guesswork here) maybe it fallbacks to the old UI if the new UI isn't found?  In that case, we can just merge this as is, and add another patch later to add the new UI.

**Comment by nh2** [comment]
> We currently do not at all build the new UI. We need some extra patches for that.

@arianvp I don't understand that comment. Consul upstream docs say the new UI is built by default in 1.3.0, and `nixpkgs` doesn't seem to have anything that disables that. So the new UI should be built.

**Comment by arianvp** [comment]
@nh2 yes this is indeed the case. See https://github.com/hashicorp/consul/blob/25f04fbd21f6a8cc63385cba80092c8c8b1223b2/agent/config/flags.go#L106-L107

We enable `-ui-dir` in the configuration of `consul` and thus it uses the legacy UI https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/consul.nix#L10

So.. we can merge this as is, without breaking the UI. and we can later create a PR for adding the `v2 UI`

**Comment by nh2** [comment]
Ah, here is more info:

Specifying `ui_dir` seems to disable the new UI and enable the legacy UI.

We do that here: https://github.com/NixOS/nixpkgs/blob/1a539e87619f5b7703780cf853dc0629ed56ce60/nixos/modules/services/networking/consul.nix#L10

Switching that to `ui = true` enables the new UI and it seems to work as expected out of the box.

[I've asked on the Consul gitter](https://gitter.im/hashicorp-consul/Lobby?at=5bd32dc06e5a401c2dd3dc66) whether this behavoiur is intended, it doesn't seem to be documented.

**Comment by arianvp** [comment]
I think when we switch from `ui _dir = ${cfg.package.ui}`  (which is defined here https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/consul/ui.nix)  to `ui = true` we'll have to adjust the  build so that it  actually builds the `ui-v2` project and includes it in the consul static binary. (which requires yarn, and will require some patching on our side, just like vault).

**Comment by nh2** [comment]
> we'll have to adjust the build so that it actually builds the `ui-v2` project and includes it in the consul static binary. (which requires yarn, and will require some patching on our side, just like vault).

@arianvp It doens't seem to need anything extra for me (see above): It works out of the box for me if I use

```diff
-    (if cfg.webUi then { ui_dir = "${cfg.package.ui}"; } else { }) //
+    (if cfg.webUi then { ui = true; } else { }) //
```

**Comment by arianvp** [comment]
That's... very surprising.  as `buildGoPackage` only does `go specific` things, and doesn't call the `Makefile` of the `consul` project which actually takes care of building the UI...

**Comment by nh2** [comment]
We found the solution.

Apparently (and apparently starting with 1.2.0), for the purpose of bundling the UI into the binary, Consul started pre-building all UI stuff and putting it hex-encoded into https://github.com/hashicorp/consul/commit/e8757838a49feeb682c7e6ad6b78694a78b2096b#diff-a10b38c8ecb31208b7f65fa239f23226. They seem to generate that file with every release commit.

This means we can throw away my README and all Ruby related UI building stuff, and we only keep `(if cfg.webUi then { ui = true; } else { })`

**Comment by c0bw3b** [comment]
Ok good! That would make the service module compatible with v1.3.0 with minimal changes.
-> Do we embed that change in this PR? (adding a commit to @vdemeester branch)

Also: the build failure on aarch64 seems to be just a thread number limitation on ofBorg ARM build server but if anyone can double check

**Comment by nh2** [comment]
> Do we embed that change in this PR?

No, I made #49165 instead. We should close this.

**Comment by vdemeester** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/49165 :wink:

**Pull request closed without merging**
