### PR TITLE
spidermonkey_68: drop

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ajs124 — APPROVED** [review]
LGTM

**Comment by jtojnar** [comment]
libproxy does not support spidermonkey other than 68. It builds with a different version because the cmake flag is broken and pacrunner_mozjs is not built: https://github.com/libproxy/libproxy/issues/153

**Comment by lostnet** [comment]
Maybe it would make sense to remove js support in libproxy outside of darwin since it doesn't build anyway.

- It is misleading since it doesn't do anything.
- If the prediction that the next version supports esr78 is right, it is already out of esr maintenance.
- If the reference is optimistically changed to esr91 it will add a lot of build dependencies for esr updates in the interim for something non-functional.
- The Duktape pacrunner is already integrated so it should be evaluated and might be the better choice when the next version releases.

**Comment by jtojnar** [comment]
cc @zhaofengli who implemented the Duktape support.

**Comment by zhaofengli** [comment]
I agree with @lostnet. It doesn't make sense to have a mozjs dependency that isn't actually used. For Duktape, maybe we can ask the upstream to cut a release.

**Comment by zhaofengli** [comment]
I asked upstream [here](https://github.com/libproxy/libproxy/pull/161#issuecomment-1007844386).

**Pull request merged**
