### PR TITLE
discourse: 2.9.0.beta14 -> 3.1.0.beta2

### PR DESCRIPTION
**Pull request by talyz**
###### Description of changes
Update Discourse and all its plugins to the latest version.

This also includes a few minor formatting fixes and adds documentation on how to update discourse, which was missing.

cc @pdg137

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by talyz** [comment]
I've tested this manually on my deployment and can't find any breakages. It would be good if someone with a more substantial deployment could also try it out, however.

**Comment by pdg137** [comment]
I have deployed this in a couple of small places ([rebased onto a 22.11 release version](https://github.com/pdg137/nixpkgs/tree/discourse-3.1.0.beta2-22.11)) and at first glance it seems to work.

**Comment by dpausp** [comment]
I can try this out tomorrow.

**Review by dpausp — APPROVED** [review]
Looks good, thanks! Updated my test system and NixOS Discourse staging from 2.9.0.beta14 on NixOS 22.11. Tested basic posting functionality, backups and the following plugins: discourse-assign, discourse-canned-replies, discourse-checklist, discourse-docs, discourse-solved, discourse-spoiler-alert, discourse-voting.

**Pull request merged**
