### PR TITLE
[20.03] pythonPackages.stem: unbroken

### PR DESCRIPTION
**Pull request by ryneeverett**
###### Motivation for this change

A third attempt after #85642 which I hadn't recognized as a backport
of #81679. Same diff, brand new history.

The bug is just with the test suite on python 3.8 which was fixed in 1.8.0.
See bug report: https://trac.torproject.org/projects/tor/ticket/30847.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build python37Packages.stem python38Packages.stem

**Comment by worldofpeace** [comment]
@ryneeverett It still appears to be broken on darwin. Can we fix that or mark it broken on that platform?

**Comment by ryneeverett** [comment]
@worldofpeace This is the first time I've seen that particular error and I'm pretty sure it built on darwin when this identical diff was built by ofborg in #85642. Any chance this is an unrelated CI error?

**Comment by worldofpeace** [comment]
> @worldofpeace This is the first time I've seen that particular error and I'm pretty sure it built on darwin when this identical diff was built by ofborg in #85642. Any chance this is an unrelated CI error?

I could try it again, be since this is now on `release-20.03` it's going to be different.

@GrahamcOfBorg build python37Packages.stem python38Packages.stem

**Comment by worldofpeace** [comment]
> @worldofpeace This is the first time I've seen that particular error and I'm pretty sure it built on darwin when this identical diff was built by ofborg in #85642. Any chance this is an unrelated CI error?

We're in luck, it worked :sparkles:

**Pull request merged**
