### PR TITLE
lisp-modules: mass updates - including new quicklisp dist

### PR DESCRIPTION
**Pull request by Uthar**
## Things done

- updated to new quicklisp release
- removed unneeded pins for packages that are now in quicklisp
- updated other non-quicklisp packages to the latest versions

Future things to do: 

- add tests to lisp packages
- add meta to lisp packages
- remove build-with-compile-into-pwd and fix packages to use output translations instead

Unsure about the use of throw for renamed packages.

PTAL @NixOS/lisp 

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by HeitorAugustoLN** [comment]
I don't know if this is related to this PR, but nixpkgs-review is now failing because of an infinite recursion in lisp-modules
[Infinite recursion](https://github.com/user-attachments/assets/cfaf3c70-2dff-49fd-833f-005969febd72)

**Comment by Uthar** [comment]
yes... it seems a bug in upstream quicklisp, which we haven't handled.

can you check as well?

```
mv ~/quicklisp ~/_quicklisp
wget https://beta.quicklisp.org/quicklisp.lisp
sbcl
(load "quicklisp.lisp")
(quicklisp-quickstart:install)
(ql:quickload "cl-quil")
...
debugger invoked on a SB-KERNEL::CONTROL-STACK-EXHAUSTED
```

**Comment by HeitorAugustoLN** [comment]
After running these commands this is what was returned to me:
```
* (ql:quickload "cl-quil")
fatal error encoutered in SBCL pid 244308 tid 244308:
Control stack exausted while pseudo-atomic, fault 0x7f0f2b20fff8, PC: 0x44abb8
```

**Comment by mrgiles** [comment]
> I don't know if this is related to this PR, but nixpkgs-review is now failing because of an infinite recursion in lisp-modules [Infinite recursion](https://github.com/user-attachments/assets/cfaf3c70-2dff-49fd-833f-005969febd72)

Getting the same `error: infinite recursion encountered` while running `nixpkgs-review`. 

Glad to know it's not just me. It was driving me nuts, almost reinstalled the whole system!

Thanks for checking, guys!

**Comment by Uthar** [comment]
Seems to work now, right? Sorry for the trouble (-: I'll share a patch to detect future circular dependencies soon.

**Pull request merged**
