### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #321948. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by maralorn** [comment]
### [haskell-updates build report from hydra](https://hydra.nixos.org/jobset/nixpkgs/haskell-updates)
*evaluation [1807887](https://hydra.nixos.org/eval/1807887) of nixpkgs commit [574f1a6](https://github.com/NixOS/nixpkgs/commits/574f1a6205e63e9870c6e6132c393f9082d58d2a) as of 2024-07-26 06:12 UTC*

🔴 **Branch not mergeable**
  * `mergeable` jobset failed.
  * `maintained` jobset failed.

#### Build summary

 | Platform | Failed ❌ | DependencyFailed ❗ | TimedOut ⌛🚫 | Unfinished ⏳ | Success ✅ | 
 | --- | --- | --- | --- | --- | --- | 
 | [aarch64-darwin 🍏](https://hydra.nixos.org/eval/1807887?filter=.aarch64-darwin) | 79 | 53 | 3 |  | 6354 | 
 | [aarch64-linux 📱](https://hydra.nixos.org/eval/1807887?filter=.aarch64-linux) | 25 | 20 | 2 |  | 6508 | 
 | [x86_64-darwin 🍎](https://hydra.nixos.org/eval/1807887?filter=.x86_64-darwin) | 69 | 49 | 2 | 3 | 6380 | 
 | [x86_64-linux 🐧](https://hydra.nixos.org/eval/1807887?filter=.x86_64-linux) | 13 | 21 | 2 | 71 | 6493 | 
#### Maintained Linux packages with build failure
- [ ] [[📱❌]](https://hydra.nixos.org/build/267371179) [[🐧❌]](https://hydra.nixos.org/build/267371031) [haskellPackages.proto3-suite](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.proto3-suite) @alexfmpe
- [ ] [[🐧❌]](https://hydra.nixos.org/build/266397929) [tests.haskell.upstreamStackHpackVersion](https://hydra.nixos.org/eval/1807887?filter=tests.haskell.upstreamStackHpackVersion) @cdepillabout
#### Maintained Linux packages with failed dependency
- [ ] [cachix](https://hydra.nixos.org/eval/1807887?filter=cachix) @domenkozar
  - [[📱❗]](https://hydra.nixos.org/build/266552534) [[🐧❗]](https://hydra.nixos.org/build/266552626) [toplevel](https://hydra.nixos.org/eval/1807887?filter=cachix)
  - [[📱❗]](https://hydra.nixos.org/build/266552620) [[🐧❗]](https://hydra.nixos.org/build/266552622) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.cachix)
- [ ] [git-annex](https://hydra.nixos.org/eval/1807887?filter=git-annex) @peti @roosemberth
  - [[📱❗]](https://hydra.nixos.org/build/267371050) [[🐧❗]](https://hydra.nixos.org/build/267370976) [toplevel](https://hydra.nixos.org/eval/1807887?filter=git-annex)
  - [[📱❗]](https://hydra.nixos.org/build/267371173) [[🐧❗]](https://hydra.nixos.org/build/267371213) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.git-annex)
- [ ] [[📱❗]](https://hydra.nixos.org/build/266552609) [[🐧❗]](https://hydra.nixos.org/build/266552443) [hci](https://hydra.nixos.org/eval/1807887?filter=hci) @roberth
- [ ] [hercules-ci-agent](https://hydra.nixos.org/eval/1807887?filter=hercules-ci-agent) @roberth
  - [[📱❗]](https://hydra.nixos.org/build/266552464) [[🐧❗]](https://hydra.nixos.org/build/266552629) [toplevel](https://hydra.nixos.org/eval/1807887?filter=hercules-ci-agent)
  - [[📱❗]](https://hydra.nixos.org/build/266552657) [[🐧❗]](https://hydra.nixos.org/build/266552542) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.hercules-ci-agent)
- [ ] [[📱❗]](https://hydra.nixos.org/build/266552523) [[🐧❗]](https://hydra.nixos.org/build/266552495) [haskellPackages.hercules-ci-cli](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.hercules-ci-cli) @roberth
- [ ] [[🐧❗]](https://hydra.nixos.org/build/267371338) [maintained](https://hydra.nixos.org/eval/1807887?filter=maintained) @cdepillabout @expipiplus1 @maralorn @ncfavier @sternenseemann
- [ ] [[🐧❗]](https://hydra.nixos.org/build/267371061) [mergeable](https://hydra.nixos.org/eval/1807887?filter=mergeable) @cdepillabout @expipiplus1 @maralorn @ncfavier @sternenseemann
#### Maintained Darwin packages with build failure
<details><summary>6 job(s) </summary>

- [ ] [[🍏❌]](https://hydra.nixos.org/build/267370948) [[🍎✅]](https://hydra.nixos.org/build/267371277) [echidna](https://hydra.nixos.org/eval/1807887?filter=echidna) @arcz @hellwolf
- [ ] [[🍏❌]](https://hydra.nixos.org/build/266382528) [[🍎❌]](https://hydra.nixos.org/build/266378657) [haskellPackages.gcodehs](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.gcodehs) @sorki
- [ ] [[🍏❌]](https://hydra.nixos.org/build/266371306) [[🍎✅]](https://hydra.nixos.org/build/266386605) [haskellPackages.ghcjs-dom-hello](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.ghcjs-dom-hello) @alexfmpe
- [ ] [[🍏❌]](https://hydra.nixos.org/build/266371870) [[🍎❌]](https://hydra.nixos.org/build/266376198) [haskellPackages.kmonad](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.kmonad) @slotThe
- [ ] [[🍏❌]](https://hydra.nixos.org/build/267371150) [[🍎❌]](https://hydra.nixos.org/build/267371156) [haskellPackages.proto3-suite](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.proto3-suite) @alexfmpe
- [ ] [[🍏❌]](https://hydra.nixos.org/build/267079135) [[🍎❌]](https://hydra.nixos.org/build/267079149) [wstunnel](https://hydra.nixos.org/eval/1807887?filter=wstunnel) @NeverBehave @R-VdP
</details>

#### Maintained Darwin packages with failed dependency
<details><summary>49 job(s) </summary>

- [ ] [cabal2nix](https://hydra.nixos.org/eval/1807887?filter=cabal2nix) @sternenseemann
  - [[🍏✅]](https://hydra.nixos.org/build/267340797) [[🍎✅]](https://hydra.nixos.org/build/267340744) [toplevel](https://hydra.nixos.org/eval/1807887?filter=cabal2nix)
  - [[🍏❗]](https://hydra.nixos.org/build/266392194) [[🍎✅]](https://hydra.nixos.org/build/266378026) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc8107.cabal2nix)
  - [[🍏❗]](https://hydra.nixos.org/build/266384969) [[🍎✅]](https://hydra.nixos.org/build/266389478) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc902.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266398292) [[🍎✅]](https://hydra.nixos.org/build/266391020) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc925.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266376537) [[🍎✅]](https://hydra.nixos.org/build/266384008) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc926.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266382266) [[🍎✅]](https://hydra.nixos.org/build/266386403) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc927.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266397795) [[🍎✅]](https://hydra.nixos.org/build/266384658) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc928.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266375493) [[🍎✅]](https://hydra.nixos.org/build/266390933) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc945.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266396588) [[🍎✅]](https://hydra.nixos.org/build/266391442) [haskell.packages.ghc946](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc946.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266373864) [[🍎✅]](https://hydra.nixos.org/build/266392218) [haskell.packages.ghc947](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc947.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266382871) [[🍎✅]](https://hydra.nixos.org/build/266384415) [haskell.packages.ghc948](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc948.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266396365) [[🍎✅]](https://hydra.nixos.org/build/266384422) [haskell.packages.ghc963](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc963.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266390165) [[🍎✅]](https://hydra.nixos.org/build/266375445) [haskell.packages.ghc964](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc964.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266378852) [[🍎✅]](https://hydra.nixos.org/build/266385617) [haskell.packages.ghc965](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc965.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266373916) [[🍎✅]](https://hydra.nixos.org/build/266394639) [haskell.packages.ghc966](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc966.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266389733) [[🍎✅]](https://hydra.nixos.org/build/266396035) [haskell.packages.ghc981](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc981.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266387374) [[🍎✅]](https://hydra.nixos.org/build/266389975) [haskell.packages.ghc982](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc982.cabal2nix)
  - [[🍏✅]](https://hydra.nixos.org/build/266394142) [[🍎✅]](https://hydra.nixos.org/build/266384206) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.cabal2nix)
- [ ] [cachix](https://hydra.nixos.org/eval/1807887?filter=cachix) @domenkozar
  - [[🍏❗]](https://hydra.nixos.org/build/266552616) [[🍎❗]](https://hydra.nixos.org/build/266552564) [toplevel](https://hydra.nixos.org/eval/1807887?filter=cachix)
  - [[🍏❗]](https://hydra.nixos.org/build/266552515) [[🍎❗]](https://hydra.nixos.org/build/266552507) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.cachix)
- [ ] [[🍏❗]](https://hydra.nixos.org/build/266381330) [[🍎✅]](https://hydra.nixos.org/build/266394054) [elmPackages.elmi-to-json](https://hydra.nixos.org/eval/1807887?filter=elmPackages.elmi-to-json) @turboMaCk
- [ ] [git-annex](https://hydra.nixos.org/eval/1807887?filter=git-annex) @peti @roosemberth
  - [[🍏❗]](https://hydra.nixos.org/build/267370970) [[🍎❗]](https://hydra.nixos.org/build/267370898) [toplevel](https://hydra.nixos.org/eval/1807887?filter=git-annex)
  - [[🍏❗]](https://hydra.nixos.org/build/267371272) [[🍎❗]](https://hydra.nixos.org/build/267371123) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.git-annex)
- [ ] [[🍏❗]](https://hydra.nixos.org/build/266552599) [[🍎❗]](https://hydra.nixos.org/build/266552624) [hci](https://hydra.nixos.org/eval/1807887?filter=hci) @roberth
- [ ] [hercules-ci-agent](https://hydra.nixos.org/eval/1807887?filter=hercules-ci-agent) @roberth
  - [[🍏❗]](https://hydra.nixos.org/build/266552582) [[🍎❗]](https://hydra.nixos.org/build/266552475) [toplevel](https://hydra.nixos.org/eval/1807887?filter=hercules-ci-agent)
  - [[🍏❗]](https://hydra.nixos.org/build/266552592) [[🍎❗]](https://hydra.nixos.org/build/266552456) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.hercules-ci-agent)
- [ ] [[🍏❗]](https://hydra.nixos.org/build/266552637) [[🍎❗]](https://hydra.nixos.org/build/266552517) [haskellPackages.hercules-ci-cli](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.hercules-ci-cli) @roberth
- [ ] [weeder](https://hydra.nixos.org/eval/1807887?filter=weeder) @maralorn
  - [[🍏❗]](https://hydra.nixos.org/build/266397841) [[🍎✅]](https://hydra.nixos.org/build/266392359) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc8107.weeder)
  - [[🍏❗]](https://hydra.nixos.org/build/266375413) [[🍎✅]](https://hydra.nixos.org/build/266378099) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc902.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266380426) [[🍎✅]](https://hydra.nixos.org/build/266375419) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc925.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266386060) [[🍎✅]](https://hydra.nixos.org/build/266392404) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc926.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266382446) [[🍎✅]](https://hydra.nixos.org/build/266372789) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc927.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266378520) [[🍎✅]](https://hydra.nixos.org/build/266390987) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc928.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266376349) [[🍎✅]](https://hydra.nixos.org/build/266373794) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc945.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266379600) [[🍎✅]](https://hydra.nixos.org/build/266388825) [haskell.packages.ghc946](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc946.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266379451) [[🍎✅]](https://hydra.nixos.org/build/266374476) [haskell.packages.ghc947](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc947.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266371640) [[🍎✅]](https://hydra.nixos.org/build/266384622) [haskell.packages.ghc948](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc948.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266393527) [[🍎✅]](https://hydra.nixos.org/build/266379308) [haskell.packages.ghc963](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc963.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266389922) [[🍎✅]](https://hydra.nixos.org/build/266385976) [haskell.packages.ghc964](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc964.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266388073) [[🍎✅]](https://hydra.nixos.org/build/266386246) [haskell.packages.ghc965](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc965.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266372763) [[🍎✅]](https://hydra.nixos.org/build/266381564) [haskell.packages.ghc966](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc966.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266394445) [[🍎✅]](https://hydra.nixos.org/build/266390521) [haskell.packages.ghc981](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc981.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266383350) [[🍎✅]](https://hydra.nixos.org/build/266387150) [haskell.packages.ghc982](https://hydra.nixos.org/eval/1807887?filter=haskell.packages.ghc982.weeder)
  - [[🍏✅]](https://hydra.nixos.org/build/266396055) [[🍎✅]](https://hydra.nixos.org/build/266393119) [haskellPackages](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.weeder)
</details>

**Comment by domenkozar** [comment]
Any idea why tasty fails?

**Comment by peti** [comment]
https://github.com/UnkindPartition/tasty/issues/426

**Comment by r-vdp** [comment]
Maybe we should drop the Haskell implementation of wstunnel, the author rewrote it in rust and doesn't maintain the Haskell implementation anymore.

We have packaged the new rust implementation and that's what the top-level attribute is also pointing at. This package does indeed fail to build on Darwin because of a missing Darwin-specific dependency. I'm on holidays without my laptop for two weeks, I can fix that when I'm back home.

**Comment by slotThe** [comment]
>     * [ ]  [[🍏❌]](https://hydra.nixos.org/build/266371870) [[🍎❌]](https://hydra.nixos.org/build/266376198) [haskellPackages.kmonad](https://hydra.nixos.org/eval/1807887?filter=haskellPackages.kmonad) @slotThe

This would be "fixed" (is that the right word to use? I guess not :) by https://github.com/NixOS/nixpkgs/pull/305823 since I don't know how to test something on a system I don't have access to

**Comment by roberth** [comment]
ptal

- https://github.com/NixOS/nixpkgs/pull/330643

**Comment by hellwolf** [comment]
https://github.com/NixOS/nixpkgs/pull/331080

**Pull request merged**
