### PR TITLE
rust: 1.9.0 -> 1.10.0

### PR DESCRIPTION
**Pull request by the-kenny**
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by the-kenny** [comment]
I want to squash some of these commits later, just keeping them separate for review.

**Comment by dvc94ch** [comment]
@Ericson2314: ping!

@the-kenny: Don't forget to remove snapshot.nix, remove-unneeded-git.patch and use-rust-1.9.0.patch

**Comment by the-kenny** [comment]
@dvc94ch I think that's it. Cargo works, `rustRegistry` is updated, the only thing left is wait for your guys' feedback and squashing the commits. The latter shouldn't trigger a rebuild anymore.

Note that I just force-pushed the branch after rebasing against latest master.

**Comment by dvc94ch** [comment]
What about updating beta and master? It is quite a bit of additional work dough, so maybe we should remove them after all if no one want's to maintain it.

**Comment by the-kenny** [comment]
I actually like having `beta` and `unstable` in nixpkgs. It's useful when you can't live without one of the unstable features. I'll take a look at them after this is merged. I'd rather not add the changes for these to this PR.

**Comment by dvc94ch** [comment]
ok, just thought it would save some bandwidth on hydra in case an adjustment has to be made to rustc.nix

**Comment by dvc94ch** [comment]
building it now

**Comment by Ericson2314** [comment]
Looks great! :)

**Comment by dvc94ch** [comment]
looks good to me too

**Comment by rardiol** [comment]
head.nix is broken, missing the use 1.9.0 patch. Also version is now wrong.

**Comment by Ericson2314** [comment]
head and beta are intentionally broken for the time being. If you need nightly try https://github.com/Ericson2314/nixos-configuration/blob/nixos/user/.nixpkgs/rust-nightly.nix for the time being.

**Comment by the-kenny** [comment]
:confetti_ball: :tada: :beers:

**Comment by the-kenny** [comment]
Oh sorry. The "is broken" comments didn't load for me. I'll fix head and beta some time today.

**Comment by dvc94ch** [comment]
@the-kenny: where there any complications? =)

**Comment by the-kenny** [comment]
Sorry, got busy with work and forgot about it :/ I've got a working `rustc-1.11.0-beta` but iirc cargo makes issues. I'll push what I have in a few minutes.

**Comment by the-kenny** [comment]
Current status is in https://github.com/the-kenny/nixpkgs/tree/rustc-beta-1.11.0 - I'll open an issue for it.

**Comment by the-kenny** [comment]
Tracking issue: https://github.com/NixOS/nixpkgs/issues/17097

**Pull request merged**
