### PR TITLE
jetbrains: 2019.2.*

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build jetbrains

**Comment by mmahut** [comment]
1 package failed to build:
jetbrains.webstorm


```
builder for '/nix/store/n332j1m0m89mmwrw88n1317wpxamhi3i-webstorm-2019.2.1.drv' failed with exit code 1; last 6 log lines:
  unpacking sources
  unpacking source archive /nix/store/fx6wrmms8aalapfxxwjybk889nfr9azj-WebStorm-2019.2.1.tar.gz
  source root is WebStorm-192.6262.59
  setting SOURCE_DATE_EPOCH to timestamp 1566316279 of file WebStorm-192.6262.59/product-info.json
  patching sources
  rm: cannot remove 'jre64': No such file or directory
cannot build derivation '/nix/store/h3869vark9813cff1s0qwa7n1sigywkj-env.drv': 1 dependencies couldn't be built
```

**Comment by mmahut** [comment]
Thank you, all of the above builds fine.

**Comment by DavidDudson** [comment]
@eadwu @mmahut See https://github.com/NixOS/nixpkgs/pull/65383 For how webstorm can be resolved

**Pull request merged**
