### PR TITLE
cmake/setup-hook.sh: Don't skip build-RPATH

### LINKED ISSUE #22060: No in-build execution for CMake managed builds
## Issue description
I try to migrate a library written in C++ build via CMake to Nix. The test executables also written in C++ are part of this project. CMake allows in-build execution (and therefor in-build testing), because it sets the RPATH for the build executable.

Nixpkgs skips adding this RPATH by setting [CMAKE_SKIP_BUILD_RPATH`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L52). This behavior breaks the possibility to test the library or call built executables during build.

### Workarounds
* Expand LD_LIBRARY_PATH; Following command gives an overview how many derivations tackle this issue.
`.../nixpkgs $ git grep -E "LD_LIBRARY_PATH.*pwd"`
* Install before checking/install project before checking/testing

## Proposal
The canonical behavior of CMake should be preserved and CMAKE_SKIP_BUILD_RPATH should not be set.

What do you think about this issue?

### PR DESCRIPTION
**Pull request by knedlsepp**
###### Motivation for this change

This should simplify using `nix-shell -A` or `nix develop` to develop
CMake based projects. CMake features a mechanism to use a different
RPATH for all executables in the build directory and only rewrite these
RPATHs on installation. This makes it possible to run executables
already from the build directory without having to set LD_LIBRARY_PATH.
This should simplify the checkPhase for cmake based projects and
hopefully not break anything.

Fixes: #22060

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
This needs to go through staging.

**Comment by knedlsepp** [comment]
> This needs to go through staging.

👍 Currently stuck at building bluez with this anyway.

**Comment by r-burns** [comment]
Darwin stdenv still builds with this fyi

**Comment by knedlsepp** [comment]
> Darwin stdenv still builds with this fyi

Thanks for the heads up. I'll try to figure out what was my issue with the bluez build then we can move this forward.

**Comment by knedlsepp** [comment]
After https://github.com/NixOS/nixpkgs/pull/123011 was merged I can build bluez and continue with this.

**Comment by knedlsepp** [comment]
For reference. The last attempt was reverted because of #15881

**Comment by knedlsepp** [comment]
cc @ttuegel You once tried to drop the SKIP_BUILD_RPATH in 8ec5adc953d6bbabbe62d7f7229f146202704e53, which had to be reverted in d5d4606190fc951b421e2bbd47585b99c46bf6bf because of a broken Darwin stdenv.
I'd like to try again to get rid of it since it's somewhat of an inconvenience that by default tests in cmake builds don't work unless you set LD_LIBRARY_PATH or disable the SKIP_BUILD_RPATH.

I tried nixpkgs-review on this, but it requires downloading 128GB of stuff, so I just rebuilt the projects on a best effort basis and everything seems to work fine on x86_64-linux.

**Comment by ttuegel** [comment]
I agree that it's pretty inconvenient, but we still need to not break Darwin. I don't have any capability to test on that platform.

**Comment by r-burns** [comment]
I'm willing to test on darwin if it will help get this merged.

**Comment by knedlsepp** [comment]
> I'm willing to test on darwin if it will help get this merged.

Thanks! I don't have merge permissions, but I think we could get someone to sign this off if we can prove that Darwin stdenv still works.

**Comment by r-burns** [comment]
Sounds good, darwin stdenv still builds on 7affe0cd8ac5442a4448babfca1d51e6a7159b55. I'll try again on the merge commit 5c8f127438ae022affc4327f66d3680a60025d63 just to be sure. Let me know if there are any potentially problematic packages beyond stdenv we should check up on.

**Comment by smancill** [comment]
I've encountered this problem trying to fix `shogun` tests and I decide to investigate if setting `-DCMAKE_SKIP_BUILD_RPATH=OFF` may cause any strange issues.

But first, I don't think this PR is properly created. It just merged `staging` back instead of rebasing, and it shouldn't modify all derivations setting `-DCMAKE_SKIP_BUILD_RPATH=OFF`, at least not in the same commit. It just makes hard to track the main change with all the noise of the modified derivations.

(And removing the flag from `cmake/setup-hook.sh` doesn't change anything for those derivations because the default is `OFF`. It should be left to the maintainers to remove, as the maintainers that set `LD_LIBRARY_PATH` to run the tests should also remove that. And the maintainers that set `doCheck = false` should see if now the tests work.)

------

I've created a simple CMake project to test the different settings: https://github.com/smancill/nix-cmake-rpath. Much more simple to build and modify than using a real Cmake project from nixpkgs.

It creates a library with a nixpkgs dependency, and an executable that depends on the library.

Note that the project does define `CMAKE_INSTALL_RPATH` with the recommended `$ORIGIN $ORIGIN/../lib` (`@loader_path @loader_path/../lib`) value, as many other projects following CMake practices may do.


#### `-DCMAKE_SKIP_BUILD_RPATH=OFF -DCMAKE_SKIP_INSTALL_RPAH=OFF` (this PR)

I don't see anything wrong. The tests work, the installed executable runs and the dependencies are listed just fine. But note that the project-defined RPATH is prepended on Linux and appended on macOS. I don't know at what point and what hook or wrapper adds the Nix store paths to RPATH.

Linux:

```
$ readelf -d ./result/bin/hello
 0x0000000000000001 (NEEDED)             Shared library: [libhello.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib:/nix/store/l2c2yjc3jflp165hi0jr7k4phl0j3w3x-cmake-rpath-test-1/lib:/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib:/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib/lib]

$ readelf -d ./result/lib/libhello.so
 0x0000000000000001 (NEEDED)             Shared library: [libjsoncpp.so.22]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib:/nix/store/z0vyrjz2sr6i1af690li3kma3mm04m9a-jsoncpp-1.9.2/lib:/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib:/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib/lib]
```

macOS:

```
$ otool -L ./result/bin/hello
./result/bin/hello:
        /nix/store/7rnk68d1m18sqkcny9jq9kzqb1mdyk9c-cmake-rpath-test-1/lib/libhello.dylib (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/my1n5lz1d0f6asj5a44vzp5pyf8ws869-jsoncpp-1.9.4/lib/libjsoncpp.24.dylib (compatibility version 24.0.0, current version 1.9.4)
        /nix/store/fsz5rxl37pamwhqkmp9w4jryfc4pfky3-libcxx-7.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

$ otool -l ./result/bin/hello | grep -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 96
         path /nix/store/w9vgngyar0ykvmamm6k0bf5k9yn9kbhb-swift-corefoundation/Library/Frameworks (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)

$ otool -D ./result/lib/libhello.dylib
./result/lib/libhello.dylib:
/nix/store/7rnk68d1m18sqkcny9jq9kzqb1mdyk9c-cmake-rpath-test-1/lib/libhello.dylib

$ otool -L ./result/lib/libhello.dylib
./result/lib/libhello.dylib:
        /nix/store/7rnk68d1m18sqkcny9jq9kzqb1mdyk9c-cmake-rpath-test-1/lib/libhello.dylib (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/my1n5lz1d0f6asj5a44vzp5pyf8ws869-jsoncpp-1.9.4/lib/libjsoncpp.24.dylib (compatibility version 24.0.0, current version 1.9.4)
        /nix/store/fsz5rxl37pamwhqkmp9w4jryfc4pfky3-libcxx-7.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

$ otool -l ./result/lib/libhello.dylib | grep -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 96
         path /nix/store/w9vgngyar0ykvmamm6k0bf5k9yn9kbhb-swift-corefoundation/Library/Frameworks (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
```

#### `-DCMAKE_SKIP_BUILD_RPATH=OFF -DCMAKE_SKIP_INSTALL_RPAH=ON`

Maybe what is really wanted is `-DCMAKE_SKIP_INSTALL_RPAH=ON`? The build RPATH is still set so the tests work, but the install RPATH is not modified with the project-defined RPATH. Nix dependencies still appear in the RPATH just fine.

Linux:

```
$ readelf -d ./result/bin/hello
 0x0000000000000001 (NEEDED)             Shared library: [libhello.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/b2hiir3xszfl6cwzf3naz1zgbhfyw7j3-cmake-rpath-test-1/lib:/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib:/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib/lib]

$ readelf -d ./result/lib/libhello.so
 0x0000000000000001 (NEEDED)             Shared library: [libjsoncpp.so.22]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/z0vyrjz2sr6i1af690li3kma3mm04m9a-jsoncpp-1.9.2/lib:/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib:/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib/lib]
```

macOS:

```
$ otool -L ./result/bin/hello
./result/bin/hello:
        /nix/store/iv98gr32ffxvsg10q1104bp1m6rqbywi-cmake-rpath-test-1/lib/libhello.dylib (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/my1n5lz1d0f6asj5a44vzp5pyf8ws869-jsoncpp-1.9.4/lib/libjsoncpp.24.dylib (compatibility version 24.0.0, current version 1.9.4)
        /nix/store/fsz5rxl37pamwhqkmp9w4jryfc4pfky3-libcxx-7.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

$ otool -l ./result/bin/hello | grep -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 96
         path /nix/store/w9vgngyar0ykvmamm6k0bf5k9yn9kbhb-swift-corefoundation/Library/Frameworks (offset 12)

$ otool -D ./result/lib/libhello.dylib
./result/lib/libhello.dylib:
/nix/store/iv98gr32ffxvsg10q1104bp1m6rqbywi-cmake-rpath-test-1/lib/libhello.dylib

$ otool -L ./result/lib/libhello.dylib
./result/lib/libhello.dylib:
        /nix/store/iv98gr32ffxvsg10q1104bp1m6rqbywi-cmake-rpath-test-1/lib/libhello.dylib (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/my1n5lz1d0f6asj5a44vzp5pyf8ws869-jsoncpp-1.9.4/lib/libjsoncpp.24.dylib (compatibility version 24.0.0, current version 1.9.4)
        /nix/store/fsz5rxl37pamwhqkmp9w4jryfc4pfky3-libcxx-7.1.0/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

$ otool -l ./result/lib/libhello.dylib | grep -A2 LC_RPATH
          cmd LC_RPATH
      cmdsize 96
         path /nix/store/w9vgngyar0ykvmamm6k0bf5k9yn9kbhb-swift-corefoundation/Library/Frameworks (offset 12)
```

----

My GitHub repo allows to try different combinations of settings to see how they affect the RPATH. Or the `CMakeLists.txt` can be directly modified with other RPATH related variables.

I am not sure about that Darwin `stdenv` error of previous PR or how to test it. Just build the `stdenv`?

**Comment by r-burns** [comment]
@smancill Agree w.r.t. separate commits and the staging merge, but I assume @knedlsepp was planning to do that cleanup before the PR is merged.

I am not sure why you are bringing up the install RPATH here as this PR only affects the build RPATH.

> It should be left to the maintainers to remove

Why? If the behavior is unchanged and we're just removing these now-redundant statements, that seems like due diligence to me, in line with other treewide cleanups.

**Comment by smancill** [comment]
> Why? If the behavior is unchanged and we're just removing these now-redundant statements, that seems like due diligence to me, in line with other treewide cleanups.

Well, I understand that it were the maintainers that started adding the flag to make their derivations work and pass the tests. I just though we should let them see that everything works as expected by removing the flag.

**Comment by knedlsepp** [comment]
Thx for the thorough analysis @smancill.

> But first, I don't think this PR is properly created. It just merged staging back instead of rebasing

This comes from me fixing a merge conflict via the webinterface while on a train on my phone. 😄

> and it shouldn't modify all derivations setting -DCMAKE_SKIP_BUILD_RPATH=OFF, at least not in the same commit. It just makes hard to track the main change with all the noise of the modified derivations.

That's a valid point. I'll split that from the setup-hook change. (I do however think that a treewide change to clean up all of these would be fine)

**Comment by knedlsepp** [comment]
Note: I'm currently rebuilding to verify that 199be771c1f5954aba841ec38977490364ac4740 is working.

**Comment by nh2** [comment]
We hit another instance of this issue in https://github.com/NixOS/nixpkgs/pull/144561#pullrequestreview-797266245

**Comment by Artturin** [comment]
resolved conflicts.

**Comment by Artturin** [comment]
and removed new `CMAKE_SKIP_BUILD_RPATH=OFF`s

**Review by ttuegel — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says f7414e2b3ac69f220e19b1ef9ddfe8d64650c5ca `cmake/setup-hook.sh: Don't skip build-RPATH` broke `metis` in `staging` and `staging-next`:

```
$ nix build -f. -L metis
...
metis> CMake Error at programs/cmake_install.cmake:55 (file):
metis>   file RPATH_CHANGE could not write new RPATH:
metis>   to the file:
metis>     /nix/store/9dvvz70jchfzg066yfscbxb3j0czi6h0-metis-5.1.0/bin/gpmetis
metis>   The current RUNPATH is:
metis>     /nix/store/9dvvz70jchfzg066yfscbxb3j0czi6h0-metis-5.1.0/lib64:/nix/store/9dvvz70jchfzg066yfscbxb3j0czi6h0-metis-5.1.0/lib:/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib:/nix/store/xjmm9xg5sq47q63cbf447qalz9fmwp0v-gcc-11.3.0-lib/lib
metis>   which does not contain:
metis>     /home/karypis/local/lib:
metis>   as was expected.
metis> Call Stack (most recent call first):
metis>   cmake_install.cmake:49 (include)
metis>
metis> make: *** [Makefile:100: install] Error 1
```

**Comment by Artturin** [comment]
Metis hasnt been updated in nixpkgs since 2015 so either lets mark it broken or try updating it or set the cmake flag removed here for it 

@danshapero also @jtojnar due to him having created an issue in https://github.com/KarypisLab/METIS

**Comment by Artturin** [comment]
https://github.com/KarypisLab/METIS/commit/521a2c360dc21ace5c4feb6dc0b7992433e3cb0f fixed it

**Comment by trofi** [comment]
Bisect says f7414e2b3ac69f220e19b1ef9ddfe8d64650c5ca `cmake/setup-hook.sh: Don't skip build-RPATH` broke `spirv-llvm-translator` in `staging` and `staging-next` (a popular dependency):

```
$ nix build -f. spirv-llvm-translator -L
...
SPIRV-LLVM-Translator-unstable> post-installation fixup
SPIRV-LLVM-Translator-unstable> shrinking RPATHs of ELF executables and libraries in /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04
SPIRV-LLVM-Translator-unstable> shrinking /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04/lib/libLLVMSPIRVLib.so.11
SPIRV-LLVM-Translator-unstable> shrinking /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04/bin/llvm-spirv
SPIRV-LLVM-Translator-unstable> strip is /nix/store/6mx62f4mdv5y1awi7y2mp23a76gg0ba7-gcc-wrapper-11.3.0/bin/strip
SPIRV-LLVM-Translator-unstable> stripping (with command strip and flags -S) in /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04/lib  /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04/bin
SPIRV-LLVM-Translator-unstable> patching script interpreter paths in /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04
SPIRV-LLVM-Translator-unstable> checking for references to /build/ in /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04...
SPIRV-LLVM-Translator-unstable> RPATH of binary /nix/store/8x0j0ivggqri5ncdp2lmw4ngpr12gaqj-SPIRV-LLVM-Translator-unstable-2022-05-04/bin/llvm-spirv contains a forbidden reference to /build/
```

**Comment by MatthewCroughan** [comment]
I can confirm that `spirv-llvm-translator` was broken on staging-next, as I ran into this specific issue when trying to use staging-next to cross compile an sdImage for riscv64.

**Comment by trofi** [comment]
A few more RPATH-related failures:
- [ ] btor2tools: https://hydra.nixos.org/build/183515853
- [ ] codec2: https://hydra.nixos.org/build/183567456
- [ ] ctpp2: https://hydra.nixos.org/build/183527915
- [ ] seexpr: https://hydra.nixos.org/build/183564961
- [ ] waifu2x-converter-cpp (maybe?): https://hydra.nixos.org/build/183518934
- [ ] xc3sprog: https://hydra.nixos.org/build/183532528
- [ ] zig: https://hydra.nixos.org/build/183576840

**Comment by MatthewCroughan** [comment]
It also appears that bcd70459981a6411418c2d8b0c13039270bdbf30 has broken `graphite2`

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/181243

**Comment by Artturin** [comment]
files which still set LD_LIBRARY_PATH to pwd

```
pkgs/development/compilers/ldc/generic.nix
pkgs/development/libraries/hotpatch/default.nix
pkgs/development/libraries/grpc/default.nix
pkgs/development/libraries/eccodes/default.nix
```

```
rg "LD_LIBRARY_PATH.+pwd" --files-with-matches | xargs rg "cmake" --files-with-matches
```

**Comment by trofi** [comment]
Skimming through `staging-next` hydra failures there still seem to be more of these:

- [ ] edgetx: https://hydra.nixos.org/build/183627478
- [ ] fltk14: https://hydra.nixos.org/build/183595917
- [ ] libvisio2svg: https://hydra.nixos.org/build/183546265
- [ ] mapserver: https://hydra.nixos.org/build/183721865
- [ ] monosat: https://hydra.nixos.org/build/183556642
- [ ] openhmd: https://hydra.nixos.org/build/183737176
- [ ] opentx: https://hydra.nixos.org/build/183630860
- [ ] resim: https://hydra.nixos.org/build/183564728
- [ ] shadowsocks-libev: https://hydra.nixos.org/build/183503776
- [ ] simgrid: https://hydra.nixos.org/build/183546679
- [ ] sipp: https://hydra.nixos.org/build/183517097

A few mor will probably pop up when qt fixes will get grabbed by hydra.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/181540

**Comment by trofi** [comment]
A few more RPATH-related failures from `staging-next`:

- [ ] tenacity: https://hydra.nixos.org/build/183731168
- [ ] mudlet: https://hydra.nixos.org/build/183869387
- [ ] linphone: https://hydra.nixos.org/build/183744709
- [ ] in-formant: https://hydra.nixos.org/build/183626680
- [ ] ccextractor: https://hydra.nixos.org/build/183754104
- [ ] audacity: https://hydra.nixos.org/build/183740213

**Comment by vcunat** [comment]
- [ ] some clang for `qtcreator`: https://hydra.nixos.org/build/184037130
- `simgrid` tests regressed by the "fix", so I unchecked it above

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/182097

**Comment by strager** [comment]
My program (`quick-lint-js`) successfully installs with Nix on Linux. However, due to this patch, the installed executable can't find `libstdc++.so.6`.

I don't know if this bug happens with other programs.

How should I work around this problem?

---

Notice how the `gcc-11.3.0-lib` runpath entry is missing from the executable after this patch:

Nixpkgs commit e1e0d5d51352ffcae90efb19063dd28a4949e9cc (after this patch was merged):

```
$ nix-shell -I ~/Projects/ -p quick-lint-js --run 'quick-lint-js --version'
quick-lint-js: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

$ readelf -a "$(nix-shell -I ~/Projects/ -p quick-lint-js --run 'which quick-lint-js')" | egrep -i 'r(un)?path'
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib]
```

Nixpkgs commit de1ff46f80dfdf565a1c77086d22f3721181f01b (before this patch was merged):

```
$ nix-shell -I ~/Projects/ -p quick-lint-js --run 'quick-lint-js --version'
quick-lint-js version 2.6.0

$ readelf -a "$(nix-shell -I ~/Projects/ -p quick-lint-js --run 'which quick-lint-js')" | egrep -i 'r(un)?path'
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/xjmm9xg5sq47q63cbf447qalz9fmwp0v-gcc-11.3.0-lib/lib:/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib]
```

**Comment by r-burns** [comment]
@strager sorry to hear that, I don't see why this change should have broken that. For now, you can manually revert to the old behavior on a per-package basis, which seems to fix the rpath:

```diff
--- a/pkgs/development/tools/quick-lint-js/default.nix
+++ b/pkgs/development/tools/quick-lint-js/default.nix
@@ -15,6 +15,10 @@ stdenv.mkDerivation rec {
   nativeBuildInputs = [ cmake ninja ];
   doCheck = true;
 
+  cmakeFlags = [
+    "-DCMAKE_SKIP_BUILD_RPATH=ON"
+  ];
```

Turning on `CMAKE_BUILD_WITH_INSTALL_RPATH` also seems to fix it, so it seems there is something wrong with the rpath rewriting for this package.

**Comment by Artturin** [comment]
> @strager sorry to hear that, I don't see why this change should have broken that. For now, you can manually revert to the old behavior on a per-package basis, which seems to fix the rpath:
> 
> ```diff
> --- a/pkgs/development/tools/quick-lint-js/default.nix
> +++ b/pkgs/development/tools/quick-lint-js/default.nix
> @@ -15,6 +15,10 @@ stdenv.mkDerivation rec {
>    nativeBuildInputs = [ cmake ninja ];
>    doCheck = true;
>  
> +  cmakeFlags = [
> +    "-DCMAKE_SKIP_BUILD_RPATH=ON"
> +  ];
> ```
> 
> Turning on `CMAKE_BUILD_WITH_INSTALL_RPATH` also seems to fix it, so it seems there is something wrong with the rpath rewriting for this package.


i tried `autoPatchelfHook` and first got

```
quick-lint-js> setting interpreter of /nix/store/1yn1yg8xyc9w1wv897444hasj5j1zlh1-quick-lint-js-2.6.0/bin/quick-lint-js
quick-lint-js> searching for dependencies of /nix/store/1yn1yg8xyc9w1wv897444hasj5j1zlh1-quick-lint-js-2.6.0/bin/quick-lint-js
quick-lint-js>     libstdc++.so.6 -> not found!
quick-lint-js> auto-patchelf: 1 dependencies could not be satisfied
quick-lint-js> error: auto-patchelf could not satisfy dependency libstdc++.so.6 wanted by /nix/store/1yn1yg8xyc9w1wv897444hasj5j1zlh1-quick-lint-js-2.6.0/bin/quick-lint-js
quick-lint-js> auto-patchelf failed to find all the required dependencies.
quick-lint-js> Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
```

then added `stdenv.cc.cc.lib` to `buildInputs` and then it works

```
setting interpreter of /nix/store/nipi33sz18117nvzpjz2svg4cm813dym-quick-lint-js-2.6.0/bin/quick-lint-js
searching for dependencies of /nix/store/nipi33sz18117nvzpjz2svg4cm813dym-quick-lint-js-2.6.0/bin/quick-lint-js
    libstdc++.so.6 -> found: /nix/store/xjmm9xg5sq47q63cbf447qalz9fmwp0v-gcc-11.3.0-lib/lib
setting RPATH to: /nix/store/xjmm9xg5sq47q63cbf447qalz9fmwp0v-gcc-11.3.0-lib/lib
auto-patchelf: 0 dependencies could not be satisfied
```

`autoPatchelfHook` is usually used for random binaries from other distros so its not the proper fix for this case

Looking in to finding a proper fix

**Pull request merged**
