### PR TITLE
linux_testing_bcachefs: 5.3 -> 5.7

### PR DESCRIPTION
**Pull request by cidkidnix**
###### Motivation for this change
Update bcachefs kernel to 5.7.0 so bcachefs users aren't stuck on 5.3

NOTE: I'm new to contributing to nixpkgs, so I'm sorry in advanced
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srhb** [comment]
Hi and thank you! Looks all good to me. There's actually a small test suite you can run from your checkout like this, if you didn't know: `nix-build ./nixos/test/bcachefs.nix` -- mine's still building.

cc @eadwu as the last person who touched this -- any reason not to bump from 5.3 -> 5.7?

**Comment by srhb** [comment]
The test does not succeed for me.

**Comment by cidkidnix** [comment]
I'll take a look in that case when I get a chance, everything should work as I'm running bcachefs as my rootfs right now but I'll take a look

**Comment by cidkidnix** [comment]
hmm we might also want to look to change how stage-1 mounts the rootfs if it's bcachefs if possible, since bcachefs doesn't seem to make entries in /dev/disk/by-uuid/ but there is the tool that allows you to mount by uuid which is https://github.com/yshui/bcachefs-mount

**Comment by cidkidnix** [comment]
hmm, I think the test may be messed up, as this `BCH_IOCTL_DEV_USAGE ioctl error: Inappropriate ioctl for device` always happens for some reason, it's probably a bcachefs issue not a implement issue on my end

**Comment by eadwu** [comment]
I currently don't use bcachefs much anymore (or at least not as my main filesystem).

If you're upgrading bcachefs, you should also fix the version at bcachefs-tools. On the same note, the latest commit of the source tree used in bcachefs-tools should be what bcachefs points towards for basic sanity. Note that it doesn't ensure that they work but that the tool/kernel is compatible.

**Comment by cidkidnix** [comment]
I've updated bcachefs-tools to the latest working commit, the latest commit works in theory but a pytest that fails, makes it fail to build even though it's non fatal, I aslo updated the kernel commit for some improvements that just got pushed

**Comment by cidkidnix** [comment]
I'm not sure why ofborg is failing in this case

**Comment by jnsaff** [comment]
I've updated this https://github.com/NixOS/nixpkgs/pull/96251 to the latest commits both on the kernel and bcachefs-tools side. On the tools side I also fixed the pytest issue upstream and got it merged so this should not fail any more (at least it doesn't on my machine and also in Travis connected to the upstream repo). I totally ripped off the other improvements from this PR.

**Comment by jnsaff** [comment]
Also the IOCTL error for me was a mismatch between the tools version and the kernel version. When kernel was newer than tools this error was persistent, when updated to tools it went away.

**Pull request closed without merging**
