### PR TITLE
perlPackages.MojoliciousPluginAssetPack: init at 2.08

### PR DESCRIPTION
**Pull request by stigtsp**
This adds the `Mojolicious::Plugin::AssetPack` perl module.

`JavaScriptMinifierXS`, `CSSMinifierXS` are not strictly dependencies, but the module is not particularly useful without them.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg build perlPackages.CSSSass perlPackages.MojoliciousPluginAssetPack
@GrahamcOfBorg build perldevelPackages.CSSSass perldevelPackages.MojoliciousPluginAssetPack

**Comment by stigtsp** [comment]
Darwin fails, I'll update with a fix

**Comment by stigtsp** [comment]
Dropped the `CSS::Sass` dependency as it needs some work on darwin.

**Comment by aanderse** [comment]
@GrahamcOfBorg build perlPackages.MojoliciousPluginAssetPack perldevelPackages.MojoliciousPluginAssetPack

**Comment by stigtsp** [comment]
`CSS::Minifier::XS` and `JavaScript::Minifier::XS` fails on darwin as well, I'll set up a separate PR that fixes those.

**Pull request merged**
