### PR TITLE
 vimPlugins.defx-nvim: init at 2019-08-19

### PR DESCRIPTION
**Pull request by ldelelis**
###### Things done
Comparing my changes to similar plugin init PRs, I see I somehow got a lot more automatic changes applied to `generated.nix`. I prepared this following the steps outlined in [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs). Is this correct?

- [ x ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by timokau** [comment]
Why is the commit message saying `init at 1.0`? Is there an actual 1.0 release? Otherwise it should just  be `init at 2019-08-19`.

> Comparing my changes to similar plugin init PRs, I see I somehow got a lot more automatic changes applied to generated.nix
It looks like this just happened to be an unusually active week for vim plugin maintainers. Also for some reason `readline-vim` got reordered in `generated.nix`, not sure what's up with that. But it seems harmless.

**Comment by timokau** [comment]
Since vim plugins usually don't have releases and are intended to be shipped straight from master, the nixpkgs vim infrastructure doesn't look from releases but instead takes the lastest master commit. If you want to use versions instead, you have to side-step the automated infrastructure. Please try to find out (or ask) if this plugin is intended to be used from master or from the tagged version.

**Comment by ldelelis** [comment]
@timokau 

I've tried getting in contact with Shougo multiple times through email now, but I can't get ahold of them. However, after confirming in a different distro how plugin managers handle it, they all pull from master, rather than one of the releases. What should I do here regarding the commit message?

**Comment by timokau** [comment]
When we track master instead of releases, we usually use the date of the latest commit as the version. So you need to find out when the latest commit on master was made and then amend the commit to `init at 2019-xx-xx`.

**Comment by ldelelis** [comment]
Is this ok now? I've rebased to an updated master, amended my last commit to fix the init message, and force-pushed the result to my current branch

**Review by timokau — APPROVED** [review]
Yes, looks good now. Thank you!

**Pull request merged**
