### PR TITLE
perlPackages.TestPerlTidy: 20200412 -> 20200930

### PR DESCRIPTION
**Pull request by zakame**
###### Motivation for this change

https://metacpan.org/release/SHLOMIF/Test-PerlTidy-20200930
https://metacpan.org/release/SHANCOCK/Perl-Tidy-20201001

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101550` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>freecell-solver</li>
    <li>gnome3.aisleriot</li>
    <li>kdeApplications.kpat</li>
    <li>perl530Packages.TaskFreecellSolverTesting</li>
    <li>perl530Packages.TestPerlTidy</li>
    <li>perl532Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl532Packages.DistZillaPluginTestCompile</li>
    <li>perl532Packages.TaskFreecellSolverTesting</li>
    <li>perl532Packages.TestPerlTidy</li>
    <li>pysolfc</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>perl530Packages.CLIHelpers</li>
    <li>perl530Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl530Packages.DistZillaPluginTestCompile</li>
    <li>perl530Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl530Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl530Packages.PerlCritic</li>
    <li>perl530Packages.PerlCriticMoose</li>
    <li>perl530Packages.PerlMinimumVersion</li>
    <li>perl530Packages.PerlTidy</li>
    <li>perl530Packages.TestMinimumVersion</li>
    <li>perl530Packages.TestPerlCritic</li>
    <li>perl532Packages.CLIHelpers</li>
    <li>perl532Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl532Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl532Packages.PerlCritic</li>
    <li>perl532Packages.PerlCriticMoose</li>
    <li>perl532Packages.PerlMinimumVersion</li>
    <li>perl532Packages.PerlTidy</li>
    <li>perl532Packages.TestMinimumVersion</li>
    <li>perl532Packages.TestPerlCritic</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/sdy9qh6q1h9svqdl64zqjcj4342jmcsr-Test-PerlTidy-20200412.tar.gz
source root is Test-PerlTidy-20200412
setting SOURCE_DATE_EPOCH to timestamp 1586674761 of file Test-PerlTidy-20200412/xt/release/trailing-space.t
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
patching ./xt/release/trailing-space.t...
patching ./xt/author/pod-coverage.t...
patching ./xt/author/pod-syntax.t...
patching ./t/exclude_perltidy.t...
patching ./t/exclude_files.t...
patching ./t/is_file_tidy.t...
patching ./t/list_files.t...
patching ./t/perltidy.t...
patching ./t/critic.t...
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Test::PerlTidy
Writing MYMETA.yml and MYMETA.json
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Test-PerlTidy' version '20200412'
Building Test-PerlTidy
@nix { "action": "setPhase", "phase": "checkPhase" }
running tests
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/00-compile.t ........ 
t/00-compile.t ........ 1/1 
                             
t/00-compile.t ........ ok
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/critic.t ............ 
                             
t/critic.t ............ skipped: Set $ENV{TEST_AUTHOR} to a true value to run critic tests.
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/exclude_files.t ..... 
t/exclude_files.t ..... 1/1 
                             
t/exclude_files.t ..... ok
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/exclude_perltidy.t .. 
t/exclude_perltidy.t .. 1/7 
t/exclude_perltidy.t .. 2/7 
                             
t/exclude_perltidy.t .. ok
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/is_file_tidy.t ...... 
t/is_file_tidy.t ...... 1/3 
#   Failed test 't/tidy_file.txt'
#   at t/is_file_tidy.t line 17.

t/is_file_tidy.t ...... 3/3 
#   Failed test 'pass perltidy_options perltidyrc named param'
#   at t/is_file_tidy.t line 25.
# Looks like you failed 2 tests of 3.

                             
t/is_file_tidy.t ...... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/list_files.t ........ 
t/list_files.t ........ 1/1 
                             
t/list_files.t ........ ok
Can't exec "/bin/sh": No such file or directory at /nix/store/38vxlxrvg3yji3jms44qn94lxdysbj5j-perl-5.32.0/lib/perl5/5.32.0/Test/Harness.pm line 306.
t/perltidy.t .......... 
t/perltidy.t .......... 1/8 
t/perltidy.t .......... 2/8 
                             
t/perltidy.t .......... ok

Test Summary Report
-------------------
t/is_file_tidy.t    (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1, 3
  Non-zero exit status: 2
Files=7, Tests=21,  4 wallclock secs ( 0.05 usr  0.02 sys +  3.17 cusr  0.92 csys =  4.16 CPU)
Result: FAIL
Failed 1/7 test programs. 2/21 subtests failed.
```

**Comment by zakame** [comment]
That's an interesting lot of packages that failed to build, hmmm...

**Comment by zakame** [comment]
@SuperSandro2000 thanks, `perlPackage.TestPerlTidy` does need an upgrade too https://metacpan.org/release/SHLOMIF/Test-PerlTidy-20200930 that could probably go ahead in a separate PR?

**Comment by zakame** [comment]
I'll revise this PR so it goes the other way, as TestPerlTidy requires the newest PerlTidy:

```
perlPackages.TestPerlTidy: 20200412 -> 20200930

dependencies:
perlPackages.PerlTidy: 20200110 -> 20201001
```

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.TestPerlTidy perlPackages.PerlTidy
@GrahamcOfBorg build perldevelPackages.TestPerlTidy perldevelPackages.PerlTidy

**Comment by stigtsp** [comment]
@zakame Could you split the two bumps into two commits?

**Comment by zakame** [comment]
@stigtsp done :muscle:

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101550` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>freecell-solver</li>
    <li>perl530Packages.CLIHelpers</li>
    <li>perl530Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl530Packages.DistZillaPluginTestCompile</li>
    <li>perl530Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl530Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl530Packages.PerlCritic</li>
    <li>perl530Packages.PerlCriticMoose</li>
    <li>perl530Packages.PerlMinimumVersion</li>
    <li>perl530Packages.PerlTidy</li>
    <li>perl530Packages.TaskFreecellSolverTesting</li>
    <li>perl530Packages.TestMinimumVersion</li>
    <li>perl530Packages.TestPerlCritic</li>
    <li>perl530Packages.TestPerlTidy</li>
    <li>perl532Packages.CLIHelpers</li>
    <li>perl532Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl532Packages.DistZillaPluginTestCompile</li>
    <li>perl532Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl532Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl532Packages.PerlCritic</li>
    <li>perl532Packages.PerlCriticMoose</li>
    <li>perl532Packages.PerlMinimumVersion</li>
    <li>perl532Packages.PerlTidy</li>
    <li>perl532Packages.TaskFreecellSolverTesting</li>
    <li>perl532Packages.TestMinimumVersion</li>
    <li>perl532Packages.TestPerlCritic</li>
    <li>perl532Packages.TestPerlTidy</li>
  </ul>
</details>

**Comment by zakame** [comment]
Result of `nixpkgs-review pr 101550` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>freecell-solver</li>
    <li>gnome3.aisleriot</li>
    <li>kdeApplications.kpat</li>
    <li>perl530Packages.CLIHelpers</li>
    <li>perl530Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl530Packages.DistZillaPluginTestCompile</li>
    <li>perl530Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl530Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl530Packages.PerlCritic</li>
    <li>perl530Packages.PerlCriticMoose</li>
    <li>perl530Packages.PerlMinimumVersion</li>
    <li>perl530Packages.PerlTidy</li>
    <li>perl530Packages.TaskFreecellSolverTesting</li>
    <li>perl530Packages.TestMinimumVersion</li>
    <li>perl530Packages.TestPerlCritic</li>
    <li>perl530Packages.TestPerlTidy</li>
    <li>perl532Packages.CLIHelpers</li>
    <li>perl532Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl532Packages.DistZillaPluginTestCompile</li>
    <li>perl532Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl532Packages.DistZillaPluginTestPerlCritic</li>
    <li>perlcritic (perl532Packages.PerlCritic)</li>
    <li>perl532Packages.PerlCriticMoose</li>
    <li>perl532Packages.PerlMinimumVersion</li>
    <li>perl532Packages.PerlTidy</li>
    <li>perl532Packages.TaskFreecellSolverTesting</li>
    <li>perl532Packages.TestMinimumVersion</li>
    <li>perl532Packages.TestPerlCritic</li>
    <li>perl532Packages.TestPerlTidy</li>
    <li>pysolfc</li>
  </ul>
</details>

**Review by stigtsp — APPROVED** [review]
Looks good to me

Result of `nixpkgs-review pr 101550` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>freecell-solver</li>
    <li>gnome3.aisleriot</li>
    <li>kdeApplications.kpat</li>
    <li>perl530Packages.CLIHelpers</li>
    <li>perl530Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl530Packages.DistZillaPluginTestCompile</li>
    <li>perl530Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl530Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl530Packages.PerlCritic</li>
    <li>perl530Packages.PerlCriticMoose</li>
    <li>perl530Packages.PerlMinimumVersion</li>
    <li>perl530Packages.PerlTidy</li>
    <li>perl530Packages.TaskFreecellSolverTesting</li>
    <li>perl530Packages.TestMinimumVersion</li>
    <li>perl530Packages.TestPerlCritic</li>
    <li>perl530Packages.TestPerlTidy</li>
    <li>perl532Packages.CLIHelpers</li>
    <li>perl532Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl532Packages.DistZillaPluginTestCompile</li>
    <li>perl532Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl532Packages.DistZillaPluginTestPerlCritic</li>
    <li>perlcritic (perl532Packages.PerlCritic)</li>
    <li>perl532Packages.PerlCriticMoose</li>
    <li>perl532Packages.PerlMinimumVersion</li>
    <li>perl532Packages.PerlTidy</li>
    <li>perl532Packages.TaskFreecellSolverTesting</li>
    <li>perl532Packages.TestMinimumVersion</li>
    <li>perl532Packages.TestPerlCritic</li>
    <li>perl532Packages.TestPerlTidy</li>
    <li>pysolfc</li>
  </ul>
</details>

**Comment by stigtsp** [comment]
Built OK on `darwin x64` on my mac
@aanderse can you trigger a build to test darwin on Ofborg?

**Comment by aanderse** [comment]
@GrahamcOfBorg build perlPackages.TestPerlTidy

No problem. Is the bot working on `darwin`again?

**Comment by stigtsp** [comment]
> No problem. Is the bot working on `darwin`again?

Thx! Hm, don't seem like it.

**Comment by zakame** [comment]
Thank you everyone! :+1:

**Pull request merged**
