### PR TITLE
Flexibee accounting system, initial commit

### PR DESCRIPTION
**Pull request by petrkr**
###### Motivation for this change
Have accounting system which we use at our company

###### Things done

This initial commit support only client of this accounting system. TAR Package itself contains also server side, but we do not need it at this time, so package is not done. It can be done if someone needs it later anyway.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by petrkr** [comment]
Added new version. Tested. Rebased to latest release 18.09

**Comment by Mic92** [comment]
We usually add packages to master first and then backport them as needed.

**Comment by petrkr** [comment]
> We usually add packages to master first and then backport them as needed.

How to do ? Rebase to master?

**Comment by petrkr** [comment]
Rebased to master

**Comment by FRidh** [comment]
We typically don't have a `/usr` folder. Likely it should be fine to just move it's contents (`share`) directly into `$out`.

**Comment by petrkr** [comment]
This software is custom made and it's somehow magic it works in NixOS where nothing is on standard paths. I can try move it outside of it, but they have lot's of hard-coded. Anyway it's not actual now because my collage already installed that software through WINE.

so now it's only nice2have.

**Comment by petrkr** [comment]
Moved usr/share to root of package. Moved usr/bin to bin as hidden with postfix -wrapped (as makewrapper do). Rebased to latest master. Tested - works fine

**Pull request closed without merging**
