### PR TITLE
python3Packages.blis: 0.7.3 -> 0.7.4

### PR DESCRIPTION
**Pull request by danieldk**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106429` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python37Packages.blis</li>
    <li>python37Packages.spacy</li>
    <li>python37Packages.textacy</li>
    <li>python37Packages.thinc</li>
    <li>python38Packages.blis</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.blis</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.textacy</li>
    <li>python39Packages.thinc</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106429` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python37Packages.blis</li>
    <li>python37Packages.spacy</li>
    <li>python37Packages.textacy</li>
    <li>python37Packages.thinc</li>
    <li>python38Packages.blis</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.blis</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.textacy</li>
    <li>python39Packages.thinc</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106429` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python37Packages.blis</li>
    <li>python37Packages.spacy</li>
    <li>python37Packages.textacy</li>
    <li>python37Packages.thinc</li>
    <li>python38Packages.blis</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.blis</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.textacy</li>
    <li>python39Packages.thinc</li>
  </ul>
</details>

**Comment by drewrisinger** [comment]
I tried to review this PR myself, but the tests were taking a long time (I'm not 100% sure, but at an initial glance it seemed that it was recompiling the source via ``gcc`` during ``setuptoolsCheckPhase``?). @danieldk maybe you could consider converting to ``pytestCheckHook`` and disabling a few slow tests?

**Pull request merged**
