### PR TITLE
rustPlatform.cargoBuildHook: do not use when buildPhase is set

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

See #114659.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by collares** [comment]
Would it be appropriate to land this on master instead of staging, since it fixes a channel blocker?

**Comment by worldofpeace** [comment]
@collares I think this change make sense, but I think we're agreed on that packages like `gnome-tour` and `fractal` should add `rustc` and `cargo` to `nativeBuildInputs`, the meson files try to do this anyway, and just use `cargoSetupHook`. We were only hacking around to just use it for setup anyway (IIRC).

**Comment by worldofpeace** [comment]
i.e I can just deliver those smaller fixes to master, and this can go through staging. But if @danieldk disagrees with what I just said than I would reconsider.

**Comment by collares** [comment]
@worldofpeace That's even better! I just suggested landing this on master because it would reduce the urgency of fixing it the "proper" way for all affected packages (`gnome-podcasts`, `shortwave`, `contrast`, `fractal`, `newsflash`, `gnome-tour`, `sequoia`), but if you were planning to fix the channel-blocking ones quickly then it's definitely the best approach. Thanks a lot!

**Comment by danieldk** [comment]
> i.e I can just deliver those smaller fixes to master, and this can go through staging. But if @danieldk disagrees with what I just said than I would reconsider.

I fully agree.

**Comment by SuperSandro2000** [comment]
> Would it be appropriate to land this on master instead of staging, since it fixes a channel blocker? There are 9 packages that use `buildRustPackage` and do `buildPhase = null;` in nixpkgs.

No, because then everyone would need to rebuild all rust and python packages for the next half day or day.

**Comment by jonringer** [comment]
I think this is superceded by #114716

**Comment by danieldk** [comment]
> I think this is superceded by #114716

Yep, that's a superset. Closing this.

**Pull request closed without merging**
