### PR TITLE
flutter: revert remove usages of aliases {build,host,target}Platform

### PR DESCRIPTION
**Pull request by RossComputerGuy**
PR #350299 broke Flutter's update script with how it handled getting the platform. Furthermore, the problem was made worse in the last update to Flutter which had to work around that problem. We'll just revert it for now and do a proper fix once we can figure out how to satify setting the different platforms without causing any more problems.

Will backport this so 24.11 doesn't ship with a broken Flutter.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Isn’t this going to break eval because you’re using aliases?

**Comment by RossComputerGuy** [comment]
It shouldn't with the inherits and explicit passthroughs. If that doesn't work then we'd need to find another solution since right now it downloads the source as the host you run the script on and not the source for the specific architectures.

**Comment by emilazy** [comment]
I missed the `inherit (stdenv)`. I guess it should be fine then.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 357173` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>flutterPackages-source.beta (flutterPackages-source.v3_27)</li>
    <li>flutterPackages-source.v3_24 (flutterPackages-source.stable)</li>
    <li>flutterPackages-source.v3_26</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]
builds, not sure what else to test here

**Comment by RossComputerGuy** [comment]
I'll merge this and work through any other problems.

**Pull request merged**
