### PR TITLE
tremor-rs: 0.11.1 -> 0.11.2

### PR DESCRIPTION
**Pull request by akshatagarwl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123700` at 363b53ff run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/9e3f7c570f81a5c898dad529710fab46">tremor-rs</a></li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>tests.trivial</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by mfelsche** [comment]
This can be updated to v0.11.4 @humancalico.

The errors might be coming from us switching to rust 1.52.1. Can the tremor-rs pkg express the requirement for a minimum rust toolchain?

**Comment by humancalico** [comment]
> This can be updated to v0.11.4 @humancalico.
> 
> The errors might be coming from us switching to rust 1.52.1. Can the tremor-rs pkg express the requirement for a minimum rust toolchain?

The 1.52 version is in the staging branch right now (https://github.com/NixOS/nixpkgs/blob/staging/pkgs/development/compilers/rust/1_52.nix). So I guess we'll just have to wait :man_shrugging:

**Pull request merged**
