### PR TITLE
JabRef: 5.7 -> 5.8

### PR DESCRIPTION
**Pull request by MrTarantoga**
###### Description of changes

Simple version update.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
You need to update the hash.

**Comment by MrTarantoga** [comment]
Yep, something failed during PR request.

I am not a java programmer and I tried to update JabRef, a tool what I use for a long time.

Do someone know, what the problem could be here? 

```
<======-------> 50% CONFIGURING [24s]> root project > Compiling build file 'build.gradle'<======-------> 50% CONFIGURING [25s]> root project> root project > Compiling script 'eclipse.gradle'> root project> root project > Compiling script 'eclipse.gradle'> root project> root project > Resolve dependencies of :xjc<======-------> 50% CONFIGURING [26s]> root project<=============> 100% CONFIGURING [26s]> IDLE<-------------> 0% EXECUTING [26s]> :generateBibtexmlSource<-------------> 6% EXECUTING [26s]> :generateBstGrammarSource > Resolve files of :antlr4> :generateBstGrammarSource<-------------> 6% EXECUTING [27s]<==-----------> 18% EXECUTING [27s]> :generateEndnoteSource<===----------> 25% EXECUTING [27s]> :generateMedlineSource<====---------> 31% EXECUTING [27s]> :generateModsSource<====---------> 31% EXECUTING [28s]<====---------> 37% EXECUTING [28s]> :generateSearchGrammarSource<======-------> 50% EXECUTING [28s]> :compileJava<======-------> 50% EXECUTING [29s]> :compileJava > Resolve dependencies of :compileClasspath> :compileJava > Resolve files of :compileClasspath> :compileJava<======-------> 50% EXECUTING [30s]<======-------> 50% EXECUTING [31s]<======-------> 50% EXECUTING [32s]<======-------> 50% EXECUTING [33s]<======-------> 50% EXECUTING [34s]<======-------> 50% EXECUTING [35s]<======-------> 50% EXECUTING [36s]<======-------> 50% EXECUTING [37s]<======-------> 50% EXECUTING [38s]<======-------> 50% EXECUTING [39s]<======-------> 50% EXECUTING [40s]
> Task :compileJava
/build/source/src/main/java/org/jabref/gui/mergeentries/newmergedialog/cell/FieldValueCell.java:89: error: cannot find symbol
        label.setBackground(Background.fill(Color.TRANSPARENT));
                                      ^
  symbol:   method fill(Color)
  location: class Background


<======-------> 50% EXECUTING [40s]> :compileJava<======-------> 50% EXECUTING [41s]<======-------> 50% EXECUTING [42s]Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


<======-------> 50% EXECUTING [42s]> :compileJava
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 43s
11 actionable tasks: 11 executed


<=======------> 56% EXECUTING [42s]> IDLE<-------------> 0% WAITING
error: builder for '/nix/store/q9972qf4s1bvsk49y23fcmy878jmr958-jabref-5.8.drv' failed with exit code 1;
       last 10 log lines:
       >
       > You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
       >
       > See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
       >
       > BUILD FAILED in 43s
       > 11 actionable tasks: 11 executed
       > 
       > 
       > <=======------> 56% EXECUTING [42s]> IDLE<-------------> 0% WAITING
       For full logs, run 'nix log /nix/store/q9972qf4s1bvsk49y23fcmy878jmr958-jabref-5.8.drv'.

```

**Comment by linsui** [comment]
I also got this error so I didn't update it... Maybe you need to report it upstream.

**Comment by MrTarantoga** [comment]
A similar error has been detected in Arch Linux and they reported it. It seems to be a Problem with the Java 18 JDK and they are using the JDK Version 17. How do I use the 17 version of the JDK in NixPkgs?

**Comment by linsui** [comment]
See https://github.com/NixOS/nixpkgs/pull/205299. But I get the same error with jdk 17. Where is the upstream issue? Is there a link?

**Comment by MrTarantoga** [comment]
Thank you for the link. I compared it and the reported error does not cover the same issue. They released a new [version](https://github.com/JabRef/jabref/releases/tag/v5.9) (5.9) yesterday. I close the PR

**Pull request closed without merging**
