### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
please fix conflicts

**Comment by FRidh** [comment]
Made two reverts of master changes to avoid merge conflicts. 
- gitlab 309711c4b4b665f47876f2a113d3872237467784 
- openexr f855e591929018eb7ad2e3532960b52d122a7f77

**Comment by flokli** [comment]
Is this ready to be merged?

**Comment by vcunat** [comment]
Hydra shows that 37k jobs are remaining, so I'd say it's too early.

**Comment by lblasc** [comment]
@vcunat ￼`gst_all_1.gst-plugins-bad` is already fixed is staging

**Comment by vcunat** [comment]
Oh, I looked bad (missed the PR somehow; probably ignored merged ones).  I'll take care of conflict resolution.

**Pull request merged**
