### PR TITLE
update ingen

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by cillianderoiste** [comment]
Great! But do we really need all the svn versions?

**Comment by magnetophon** [comment]
@cillianderoiste: the svn versions are needed: ingen wanted versions of these pkgs that where not released yet. Ingen gets developed in parallel with some of them I think.

Maybe we should include the ones that have wider usage (lilv and sord) as secondary versions?

**Comment by cillianderoiste** [comment]
> Maybe we should include the ones that have wider usage (lilv and sord) as secondary versions? 
That sounds good to me.

**Comment by magnetophon** [comment]
@cillianderoiste: like this?

**Pull request merged**
