### PR TITLE
webcord: init at 4.1.1

### LINKED ISSUE #183061: WebCord
**Project description**
Alternate Discord and Fosscord client made to be private, secure, customizable, and Linux friendly.

**Metadata**

* homepage URL: https://github.com/SpacingBat3/WebCord
* source URL: https://github.com/SpacingBat3/WebCord
* license: MIT
* platforms: x86_64 and aarch64 on linux, darwin, windows

### PR DESCRIPTION
**Pull request by huantianad**
###### Description of changes
Resolves #183061

[WebCord](https://github.com/SpacingBat3/WebCord) is a Discord and [Fosscord](https://fosscord.com/) client implemented directly without [Discord API](https://discord.com/developers/docs/reference). Made with the [Electron](https://www.electronjs.org/) framework.

Note WebCord has ARM and Darwin support; however, I have not done any testing on those platforms as I don't have any devices available to test with. Any help would be appreciated!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dev-null-undefined** [comment]
Cool, any chance on adding pipewire lib to support screen share on wayland?
https://github.com/NixOS/nixpkgs/commit/561f8e9dd1313807b193d3d9046096b0b24a16cb
this seems to be working but I am not sure if that's the correct way to do that on nix.

**Comment by dev-null-undefined** [comment]
And also maybe pulseaudio?
https://github.com/dev-null-undefined/nixpkgs/commit/3d76fbfef82f3518ceb6f47219d034fd15998997
since microphone was not working without it.

I inspired my self from official discord package.

**Comment by huantianad** [comment]
@dev-null-undefined thanks for the bug fixes!

**Comment by dev-null-undefined** [comment]
There seems to be a bug with version 3.10.1
https://github.com/SpacingBat3/WebCord/issues/328
reverting to 3.10.0 fixes it 5db3ec23757c1582c161cd80f2cfa06bb9e9c683

**Comment by GameWizard5000** [comment]
On Wayland at least, screen sharing crashes on the `electron` package (which uses v22) but works on the `electron_21` package, this was tested on v3.10.2.

**Comment by huantianad** [comment]
Ok, I'll pin it to electron 21 for now then

**Comment by spikespaz** [comment]
Are you aware of <https://github.com/fufexan/webcord-flake>

**Comment by huantianad** [comment]
@spikespaz yes, I still think it's better to have it officially packaged in Nixpkgs though, and the flake uses dream2nix which won't work in Nixpkgs.

**Comment by dev-null-undefined** [comment]
> @spikespaz yes, I still think it's better to have it officially packaged in Nixpkgs though, and the flake uses dream2nix which won't work in Nixpkgs.

Looking at their package tho they are adding even more libraries for example one for notifications (electron dependency).
Maybe it would be worth to merge those changes into this PR? Just to make sure everything works.

**Comment by x10an14** [comment]
> Looks like this package needs `xdg-utils` in the $PATH or else links won't open.

Also the case for "normal"/original discord in nixpkgs, ref: https://github.com/NixOS/nixpkgs/pull/160462#issuecomment-1044304955

**Comment by huantianad** [comment]
@GameWizard5000 @x10an14 thanks for the heads up! I haven't encountered this myself, it could be because I already have `xdg-utils` installed outside of webcord though.

**Comment by GameWizard5000** [comment]
For me, audio (and possibly screen sharing on Wayland) on pipewire doesn't work without `--prefix LD_LIBRARY_PATH : ${libPath}:$out/opt/webcord` in `makeWrapper`.

**Comment by huantianad** [comment]
> For me, audio (and possibly screen sharing on Wayland) on pipewire doesn't work without `--prefix LD_LIBRARY_PATH : ${libPath}:$out/opt/webcord` in `makeWrapper`.

Wups that's a my bad, I forgot to add that when I added `libPath` :facepalm:.

Adding a `binPath` might be helpful, but I think it's fine to leave that until we need it, as I doubt there will be any other things needed in that way.

**Comment by x10an14** [comment]
Executing `nix run github:huantianad/nixpkgs/webcord#webcord` on my machine permitted me to log-in, text chat, voice communication, and screenshare =)

I vote merge.

**Review by x10an14 — APPROVED** [review]
Executing `nix run github:huantianad/nixpkgs/webcord#webcord` on my machine permitted me to log-in, text chat, voice communication, and screenshare =)

**Comment by x10an14** [comment]
> @GameWizard5000 @x10an14 thanks for the heads up! I haven't encountered this myself, it could be because I already have `xdg-utils` installed outside of webcord though.

I would have liked to see `xdg-utils` added to `binPath`, ref my comments in the merged PR here https://github.com/NixOS/nixpkgs/pull/160462#issuecomment-1044304955.

I don't think this should be a blocker for merge though.

**Comment by huantianad** [comment]
If using a `binPath` variable is the main conversation I'm happy to do it, will take a bit to get back on my PC tho

**Comment by x10an14** [comment]
> If using a `binPath` variable is the main conversation I'm happy to do it, will take a bit to get back on my PC tho

If this is in reference to my comment here: https://github.com/NixOS/nixpkgs/pull/204031#issuecomment-1365716196, `xdg-open` being made available to webcord (in the built derivation) is "the main conversation" for me. If I understood correctly what you meant by that term.

But as I also said, I don't consider it a blocker.

**Comment by huantianad** [comment]
Ah I meant "main convention" not conversation, typo. 

There's two topics here, the first is adding `xdg-utils` to the PATH which I have already done.

The second is exactly how to do so in the derivation. The suggestion was to make a variable called `binPath` to store the path in, which is then used later.

**Comment by x10an14** [comment]
> There's two topics here, the first is adding `xdg-utils` to the PATH which I have already done.

/embarrassed, I thought it wasn't added, even though Issee now it was in what I added an approval for. My bad!

> The second is exactly how to do so in the derivation. The suggestion was to make a variable called `binPath` to store the path in, which is then used later.

I vote wait for it to be needed (once more derivations must be added to "binPath").

**Comment by SeineEloquenz** [comment]
Webcord released another update to [4.1.1](https://github.com/SpacingBat3/WebCord/releases/tag/v4.1.1), which could maybe be integrated directly before this gets merged

**Comment by spikespaz** [comment]
> I vote wait for it to be needed (once more derivations must be added to "binPath"). 

Seems like bikeshedding here. My argument would be: have the variable there so that new contributors don't just add dependencies to the shell code directly. If it were my code I would agree, an extra variable with a single element array is frivolous, but for the sake of providing training wheels I think it should be included.

**Comment by huantianad** [comment]
I've extracted the `binPath` into it's own variable and updated WebCord. Based on patch notes, WebCord on Electron 22 should be working so I've bumped that as well. If there are any issues with that, I'll downgrade Electron again.

**Comment by x10an14** [comment]
> Can anyone on Wayland confirm that the new update has not broke voice chat and screenshare?

I can give it a go Monday or Wednesday.

**Comment by SeineEloquenz** [comment]
I tested the current version right now on on Gnome Wayland.
Voice Chat works fine, desktop streaming as well. The only caveat is that I'm not able to select specific windows for sharing, only whole screens, but I do not know if this is intended behavior or not

**Comment by huantianad** [comment]
I think not being able to share one specific application on Wayland is a known limitation, as far as I know.

**Comment by SeineEloquenz** [comment]
Is there anything that is still blocking this package from being merged and needs more work?

**Comment by huantianad** [comment]
I don't think there are any remaining issue, just waiting for a merge rn. 

Not sure if there's anything I should do other than adding the approval label to get this merged.

**Pull request merged**
