### PR TITLE
tauon: 6.7.1 -> 7.0.1

### LINKED ISSUE #158150: Request < tauon > package update from 6.7.1 to 7.01
Hi, hope I have completed the correct fields!

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

[tauon](https://search.nixos.org/packages?channel=unstable&show=tauon&from=0&size=50&sort=relevance&type=packages&query=tauon)
The Linux desktop music player from the future

    Name: tauonVersion: 6.7.1Licenses: [GNU General Public License v3.0](https://spdx.org/licenses/GPL-3.0.html)[Homepage](https://tauonmusicbox.rocks/)[Source](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/tauon/default.nix#L104)

nix-env -iA nixos.tauon

current version: 6.7.1
desired version: 7.0.1

###### Notify maintainers

HI @SuperSandro2000 any update to tauon if you have time, would be greatly appreciated :)

I also do not get a tauon icon showing up in gnome 4.x.x and have to exec from the command line instead...wondered if this was by design :)

### PR DESCRIPTION
**Pull request by jansol**
Fixes #158150 

###### Motivation for this change

https://github.com/Taiko2k/TauonMusicBox/releases/tag/v7.0.1
https://github.com/Taiko2k/TauonMusicBox/releases/tag/v7.0.0
https://github.com/Taiko2k/TauonMusicBox/releases/tag/v6.8.0

NOTE: 6.8.0 breaks backwards-compatibility of config files

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mannp** [comment]
Tested basic functionality with `nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/158266`

Loads and execs fine and takes my existing v7 config file with no issue.

Unable to test if the icons now appears, as not sure how to do it from nixpkgs-review.

**Comment by jansol** [comment]
Installed this PR with nix-env and after restarting plasma the icon shows up for me.

**Comment by jansol** [comment]
Needs librsvg when it has to re-render icons for a new size from svg, adding that in a bit.

**Comment by mannp** [comment]
> Installed this PR with nix-env and after restarting plasma the icon shows up for me.

Care to share how for us nixnoobs 😁

**Comment by jansol** [comment]
`nix-env -f /path/to/nixpkgs/checkout -i tauon`

**Comment by mannp** [comment]
> `nix-env -f /path/to/nixpkgs/checkout -i tauon`

I see thanks, assumes you have the local checkout.

**Pull request merged**
