### PR TITLE
spring-boot-cli: 2.1.9->2.2.6

### PR DESCRIPTION
**Pull request by moaxcp**
###### Motivation for this change

rename package to match repology.org and update version

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
You renamed a package: please add an alias to avoid making this a breaking change.
Aliases are defined in`pkgs/top-level/aliases.nix` and have a comment of the date when added.

**Comment by moaxcp** [comment]
The alias is added. The purpose is to match the package names in repology.

**Review by rnhmjoj — APPROVED** [review]
Thank you.

**Comment by rnhmjoj** [comment]
Can you do a rebase? There is a conflict apparently.

**Comment by moaxcp** [comment]
Ok I think this is fixed now. I also fixed pname and the PATH so it has the other dependencies.

**Review by rnhmjoj — APPROVED** [review]
Looks good, thank you.

**Pull request merged**
