### PR TITLE
Icoutils 0.31.3

### PR DESCRIPTION
**Pull request by armijnhemel**
###### Motivation for this change

New upstream version

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by armijnhemel** [comment]
Urgh. Seems my git-foo fails me.

**Comment by 7c6f434c** [comment]
I hadn't noticed you were back! Does my cherry-pick correctly correspond to your intent? (also added the accidentally missing package name in the commit message)

**Comment by armijnhemel** [comment]
Yes it does. Sorry for the noise, I had messed up my Git config and...well...sigh... ;-)

**Comment by 7c6f434c** [comment]
You say it as if Git config can have a non-messed up state!

**Pull request closed without merging**
