### PR TITLE
rust: 1.29.1 -> 1.30.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

builds on x86_64 linux

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]
Still building some other stuff, but rustc looks good.

**Comment by Mic92** [comment]
aarch64-linux works!

**Comment by Mic92** [comment]
@LnL7 from my side everything looks good. You can merge it, when your other builds work.

**Comment by LnL7** [comment]
Looks like cargo failed, working on a fix.

**Comment by andir** [comment]
Cargo was working fine for me on linux. Was that cargo failure specific to darwin?

**Comment by LnL7** [comment]
Yeah, linux is fine.

**Review by andir — APPROVED** [review]
Works fine for me on linux (x86-64)

**Pull request merged**
