### PR TITLE
kdePackages.oxygen: fix build

### PR DESCRIPTION
**Pull request by rafameou**
## Description of changes

Basically copied breeze's default.nix and added KF5I18n, KF5Service and KF5Completion.
I have tested compilation against nixpkgs-unstable since my computer can't handle compiling the entire qtbase, please comment if you see anything wrong, Thanks!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
There is no Oxygen theme for Qt6, so building the Qt5 variant from an otherwise Qt6 package set doesn't really make sense. You can keep using the 5.27 version of the Oxygen style if you want it for Qt5 apps.

**Comment by rafameou** [comment]
> There is no Oxygen theme for Qt6, so building the Qt5 variant from an otherwise Qt6 package set doesn't really make sense. You can keep using the 5.27 version of the Oxygen style if you want it for Qt5 apps.

 I thought it had, because both KDE Neon and Arch Linux ships a package called "Oxygen" with version 6 that works fine on QT6 and even fixes some weird wayland behaviours on it, I haven't manage to get oxygen working on plasma 6. Sorry.

**Comment by K900** [comment]
Hm, looks like it did get updated for Qt6 between the time it was announced that it wasn't going to be and now. There is, however, no _Plasma_ Oxygen theme anymore, just the widget style. I'll have to test if this works.

**Comment by rafameou** [comment]
> Hm, looks like it did get updated for Qt6 between the time it was announced that it wasn't going to be and now. There is, however, no _Plasma_ Oxygen theme anymore, just the widget style. I'll have to test if this works.

The plasma oxygen theme is aparently shipped with plasma 6 already? Since it's installed already on my system, even without the oxygen package.

**Comment by K900** [comment]
OK, looks like the Plasma theme was moved into libplasma. This is all very confusing. I'll have to double check with upstream whether they want this shipped and whether it actually works.

**Comment by rafameou** [comment]
Okay, I had left my computer building it and after fixing some oopsies I did on the original commit (sorry for commit spamming by the way), it seems to work fine both on QT5 and QT6 apps.

image

**Comment by K900** [comment]
There's still qt5 references leaking into the main output. Can you take a look at why?

**Comment by rafameou** [comment]
> There's still qt5 references leaking into the main output. Can you take a look at why?

We can force oxygen to compile only QT6 using `-DBUILD_QT5=OFF` should I do that instead and leave libsForQt5.oxygen for QT5 (I have not tested if KDE would recognize the QT5 package correctly)? In that case we would not even need the KF5's dependencies. Looking at Arch Linux's PKGBUILD, they compile oxygen 2 times, one with `-DBUILD_QT5=OFF` and one with `-DBUILD_QT6=OFF`, however i'm not even sure if that's possible (or needed) here.

**Comment by K900** [comment]
No, but we should move all the stuff that depends on Qt5 to the qt5 output.

**Comment by rafameou** [comment]
> No, but we should move all the stuff that depends on Qt5 to the qt5 output.

Sorry I misunderstood your other comment, basically we should move `liboxygenstyle5` (and config) into `${libsForQt5.qtbase.bin}/lib/` (I think that's the correct path) as well?

**Comment by K900** [comment]
No, we should move it to `$qt5`.

**Comment by K900** [comment]
I'm pushing a fix to correctly separate outputs to your branch now, and will merge in a bit.

**Pull request merged**
