### PR TITLE
ocamlPackages: stdenv.lib → lib

### PR DESCRIPTION
**Pull request by sternenseemann**
This change was produced by searching for remaining occurrences of
stdenv.lib and replacing them manually.

Reference #108938.

Will need to verify the change now.

* [ ] Run ofborg checks locally

cc @Profpatsch @vbgl

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by alyssais — APPROVED** [review]
LGTM assuming OfBorg finds it to be rebuild-0.

**Comment by alyssais** [comment]
Eval failed.

**Comment by sternenseemann** [comment]
@alyssais thx for the heads up, forgot to check back here. Let's see which error crops up now.

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by sternenseemann** [comment]
Also evaluated `ocamlPackages` manually with this (crude) script refusing no evaluation errors (except errors about incompatibilities which are expected):

```bash
#!/usr/bin/env nix-shell
#! nix-shell -i bash -p jq

if test -z "$1"; then
  echo "Usage: $1 NIXPKGS [ocamlPackages set]"
  exit 1
fi

NIXPKGS=$1
shift

SET="ocaml-ng.$1"

if test -z "$1"; then
  SET="ocamlPackages"
fi

expr="$(mktemp --suffix=.nix)"

cat > "$expr" <<EOF
let
  pkgs = import $NIXPKGS {};
in
  builtins.toJSON (builtins.attrNames pkgs.$SET)
EOF

nix eval --raw "(import $expr)" | jq .[] | while read pkg; do
  echo -n $pkg: 
  nix-instantiate -A $SET.$pkg --indirect --add-root "$TMPDIR/tmp-ocaml-drv"
done

rm "$expr"
```

**Review by Profpatsch — APPROVED** [review]

**Comment by Profpatsch** [comment]
merging to avoid merge conflicts.

**Pull request merged**
