### PR TITLE
Make gprbuild build on Darwin

### PR DESCRIPTION
**Pull request by boeyms**
###### Description of changes

- Enable gprbuild to build and run on Darwin

This indirectly enables multiple other Ada-related packages to build on (x86-64) Darwin that previously could not.  gnatcoll-python3 still fails to build on Darwin, but it could not do so before, so strictly more packages build after this PR than before it.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by boeyms** [comment]
Result of `nixpkgs-review pr 211526` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gnatcoll-python3</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>emacsPackages.ada-mode</li>
    <li>gnatcoll-core</li>
    <li>gnatcoll-db2ada</li>
    <li>gnatcoll-gmp</li>
    <li>gnatcoll-iconv</li>
    <li>gnatcoll-lzma</li>
    <li>gnatcoll-omp</li>
    <li>gnatcoll-postgres</li>
    <li>gnatcoll-readline</li>
    <li>gnatcoll-sql</li>
    <li>gnatcoll-sqlite</li>
    <li>gnatcoll-syslog</li>
    <li>gnatcoll-xref</li>
    <li>gnatcoll-zlib</li>
    <li>gnatinspect</li>
    <li>gprbuild</li>
    <li>spark2014</li>
    <li>xmlada</li>
  </ul>
</details>

**Comment by sternenseemann** [comment]
The patches should be unconditional, since that makes maintenance considerably easier. In particular, I will know when the patches need to rebase even though I can not test on darwin hardware. This means that we'd have to express the conditionals in the `gpr` files instead. Any patch we can apply unconditionally, we can also get upstream to merge and we'll no longer need to care about that problem.

Another thing is, that it seems to be possible to build `gprbuild` on macOS (I think there are even prebuilt binaries), so maybe something else is wrong?

**Comment by Et7f3** [comment]
> Another thing is, that it seems to be possible to build `gprbuild` on macOS (I think there are even prebuilt binaries), so maybe something else is wrong?

With the current master yes we can build gprbuild but it can't run:

```
$ /nix/store/b3n6r92f3c2cn9gjmxw31plvq0zdszqc-gprbuild-23.0.0/bin/gprbuild
dyld[3732]: Library not loaded: @rpath/libgpr.dylib
  Referenced from: <no uuid> /nix/store/b3n6r92f3c2cn9gjmxw31plvq0zdszqc-gprbuild-23.0.0/bin/gprbuild
  Reason: tried: '/nix/store//gpr/lib/production/relocatable/libgpr.dylib' (no such file),
  ```
  
rpath has bad value `/nix/store/b3n6r92f3c2cn9gjmxw31plvq0zdszqc-gprbuild-23.0.0/lib/libgpr.dylib` exists. the issue might be visible on linux with .so instead try to build `gnatcoll-core` with current master. @sternenseemann

**Comment by sternenseemann** [comment]
@Et7f3 Aha! So it is *that* problem (which doesn't occur on Linux). Can you try if the following patch fixes it?

```diff
diff --git a/pkgs/development/tools/build-managers/gprbuild/default.nix b/pkgs/development/tools/build-managers/gprbuild/default.nix
index 3155151ae0f..0677dc8262c 100644
--- a/pkgs/development/tools/build-managers/gprbuild/default.nix
+++ b/pkgs/development/tools/build-managers/gprbuild/default.nix
@@ -6,6 +6,7 @@
 , which
 , gnat
 , xmlada
+, fixDarwinDylibNames
 }:
 
 stdenv.mkDerivation {
@@ -25,7 +26,7 @@ stdenv.mkDerivation {
     gnat
     gprbuild-boot
     which
-  ];
+  ] ++ lib.optional stdenv.hostPlatform.isDarwin [ fixDarwinDylibNames ];
 
   propagatedBuildInputs = [
     xmlada
```

**Review by Et7f3 — COMMENTED** [review]
I have tested the patch pkgs/development/tools/build-managers/gprbuild/darwin-dylib-install-name.patch and confirmed with `otool -lL` it does fix the running problem. I don't see where the second patch is needed.

**Comment by sternenseemann** [comment]
@Et7f3 *Just* use the patch I posted applied on current master. That fix is significantly simpler and does not require messing with upstream's code. It may be that we also need to apply a similar fix for reverse dependencies of gprbuild, but we'll see.

**Comment by Et7f3** [comment]
configurePhase buildPhase checkPhase

> @Et7f3 Aha! So it is _that_ problem (which doesn't occur on Linux). Can you try if the following patch fixes it?
> 
> ```diff
> diff --git a/pkgs/development/tools/build-managers/gprbuild/default.nix b/pkgs/development/tools/build-managers/gprbuild/default.nix
> index 3155151ae0f..0677dc8262c 100644
> --- a/pkgs/development/tools/build-managers/gprbuild/default.nix
> +++ b/pkgs/development/tools/build-managers/gprbuild/default.nix
> @@ -6,6 +6,7 @@
>  , which
>  , gnat
>  , xmlada
> +, fixDarwinDylibNames
>  }:
>  
>  stdenv.mkDerivation {
> @@ -25,7 +26,7 @@ stdenv.mkDerivation {
>      gnat
>      gprbuild-boot
>      which
> -  ];
> +  ] ++ lib.optionals stdenv.hostPlatform.isDarwin [ fixDarwinDylibNames ];
>  
>    propagatedBuildInputs = [
>      xmlada
> ```

This patch doesn't fix the issue.

**Comment by sternenseemann** [comment]
What is the new error message? And building what?

**Comment by Et7f3** [comment]
> What is the new error message? And building what?

The same thing before the patch: `gnatcoll-core` that require `gprbuild`.

Full error log with the proposed patch gprbuild:

<details>
<summary>nix build .#gnatcoll-core 2>&1 | pbcopy</summary>

```
this derivation will be built:
  /nix/store/7mny5501s80yznrk238lcvzzswaivwjm-gnatcoll-core-23.0.0.drv
building '/nix/store/7mny5501s80yznrk238lcvzzswaivwjm-gnatcoll-core-23.0.0.drv'...
error: builder for '/nix/store/7mny5501s80yznrk238lcvzzswaivwjm-gnatcoll-core-23.0.0.drv' failed with exit code 2;
       last 10 log lines:
       > source root is source
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > build flags: SHELL=/nix/store/1r1zhjpzpwr0m8w3di7n8phympxw2d3d-bash-5.2-p15/bin/bash prefix=/nix/store/cc55mib9l5mdp8zscbarxq4sqlsfykb7-gnatcoll-core-23.0.0 PROCESSORS=\$\(NIX_BUILD_CORES\) TARGET=x86_64-apple-darwin
       > dyld[98900]: Library not loaded: @rpath/libgpr.dylib
       >   Referenced from: <no uuid> /nix/store/0f0bv3bz99zc1hrb638bacvvhsjp2fw8-gprbuild-23.0.0/bin/gprconfig
       >   Reason: tried: '/nix/store//gpr/lib/production/relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_schema.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_dom.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_sax.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_input.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_unicode.relocatable/libgpr.dylib' (no such file), '/nix/store//obj/production/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adainclude/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adalib/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/libgpr.dylib' (no such file), '/nix/store/1ah9yw235zi4mq8c3zqip4jrvzpdnz0y-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libgpr.dylib' (no such file), '/nix/store//gpr/lib/production/relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_schema.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_dom.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_sax.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_input.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_unicode.relocatable/libgpr.dylib' (no such file), '/nix/store//obj/production/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adainclude/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adalib/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/libgpr.dylib' (no such file), '/nix/store/1ah9yw235zi4mq8c3zqip4jrvzpdnz0y-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libgpr.dylib' (no such file), '/usr/local/lib/libgpr.dylib' (no such file), '/usr/lib/libgpr.dylib' (no such file, not in dyld cache)
       > Makefile:71: *** No toolchain found for target "x86_64-apple-darwin".  Stop.
       For full logs, run 'nix log /nix/store/7mny5501s80yznrk238lcvzzswaivwjm-gnatcoll-core-23.0.0.drv'.
```

it build fine but at runtime we get the same error that without your path.
</details>

and without

<details>
<summary>nix build .#gnatcoll-core 2>&1 | pbcopy</summary>

```
this derivation will be built:
  /nix/store/81xbiwkahcyanzm7ma2cd233aqf7zx33-gnatcoll-core-23.0.0.drv
building '/nix/store/81xbiwkahcyanzm7ma2cd233aqf7zx33-gnatcoll-core-23.0.0.drv'...
error: builder for '/nix/store/81xbiwkahcyanzm7ma2cd233aqf7zx33-gnatcoll-core-23.0.0.drv' failed with exit code 2;
       last 10 log lines:
       > source root is source
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > build flags: SHELL=/nix/store/1r1zhjpzpwr0m8w3di7n8phympxw2d3d-bash-5.2-p15/bin/bash prefix=/nix/store/17nrswbk8l8r0y77y5vi6rwba1c0njd3-gnatcoll-core-23.0.0 PROCESSORS=\$\(NIX_BUILD_CORES\) TARGET=x86_64-apple-darwin
       > dyld[96270]: Library not loaded: @rpath/libgpr.dylib
       >   Referenced from: <no uuid> /nix/store/b3n6r92f3c2cn9gjmxw31plvq0zdszqc-gprbuild-23.0.0/bin/gprconfig
       >   Reason: tried: '/nix/store//gpr/lib/production/relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_schema.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_dom.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_sax.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_input.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_unicode.relocatable/libgpr.dylib' (no such file), '/nix/store//obj/production/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adainclude/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adalib/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/libgpr.dylib' (no such file), '/nix/store/1ah9yw235zi4mq8c3zqip4jrvzpdnz0y-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libgpr.dylib' (no such file), '/nix/store//gpr/lib/production/relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_schema.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_dom.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_sax.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_input.relocatable/libgpr.dylib' (no such file), '/nix/store/dnjk3lr022ndrjfawz72zycbnjhnvrfm-xmlada-23.0.0/lib/xmlada/xmlada_unicode.relocatable/libgpr.dylib' (no such file), '/nix/store//obj/production/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adainclude/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/gcc/x86_64-apple-darwin/12.2.0/adalib/libgpr.dylib' (no such file), '/nix/store/4fs2skzm9pkjrsrpykxlidvl8mf82i12-gnat-12.2.0/lib/libgpr.dylib' (no such file), '/nix/store/1ah9yw235zi4mq8c3zqip4jrvzpdnz0y-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libgpr.dylib' (no such file), '/usr/local/lib/libgpr.dylib' (no such file), '/usr/lib/libgpr.dylib' (no such file, not in dyld cache)
       > Makefile:71: *** No toolchain found for target "x86_64-apple-darwin".  Stop.
       For full logs, run 'nix log /nix/store/81xbiwkahcyanzm7ma2cd233aqf7zx33-gnatcoll-core-23.0.0.drv'.
```
</details>

When I see the linked script I think it is too late because grr is already linked with wrong dylib and the hook doesn't fix MACH-O executable (I don't know a automated way to find this maybe a combination of find+file 🤷).

With `git grep fixDarwinDylibNames` I see some patterns with `stdenv.isDarwin` instead of `stdenv.hostPlatform.isDarwin`

```
pkgs/development/compilers/llvm/13/libcxx/default.nix:    ++ lib.optional stdenv.isDarwin fixDarwinDylibNames;
```

Which style is advised ? I think the explicit one is better for cross-compilation ?



@boeyms I launched `nix run nixpkgs#nixpkgs-review rev HEAD` without your first commit and it build fine. Can you explain where the first commit is needed ? Also can you review my [PR](https://github.com/boeyms/nixpkgs/pull/1) opened on your fork (I think it is ok if you fix all gnatcoll package at the same time). One patch is more upstreamable is to use @executable_file/../lib/libgpr.dylib (maybe guarded with a flag so we can enable the flag here) or maybe use prefix variable passed to make if you see a way to query it. This way we avoid keeping the patch forever and it will improve upstream.

**Comment by boeyms** [comment]
Apologies for replying in a piecemeal manner: I'm having trouble with writing a unified explanation for everything.

### On pre-built Darwin GPRBuild binaries

> Another thing is, that it seems to be possible to build gprbuild on macOS (I think there are even prebuilt binaries), so maybe something else is wrong?

The Darwin GPRBuild binaries that are downloadable from the Alire project (e.g. [Alire project gprbuild-22.0.0-1](https://github.com/alire-project/GNAT-FSF-builds/releases/tag/gprbuild-22.0.0-1)) appear to me to only be builds of the bootstrap version of GPRBuild, since I have only found them able to build XML/Ada and the full version of GPRBuild, not other packages that require GPRBuild.  Their behaviour with respect to building XML/Ada and the full GPRBuild appears to be the same as that of the existing bootstrap GPRBuild Nix package (gprbuild-boot).

### On dylib install names

In the following, you can read "dylib" as short hand for "Darwin/macOS dynamic shared library".

`fixDarwinDylibNames` doesn't currently fix the problem here because the only dylib dependencies that it rewrites into absolute Nix store paths are those that are purely basenames (e.g. `libfoo.1.1.0.dylib`); it does not touch any references with any additional path components, be they relative (e.g. `dir1/dir2/libfoo.1.1.0.dylib`) or absolute (e.g. `/root/dir1/libfoo.1.1.0.dylib`).  Before any changes, GPRbuild gives us dylib references of the form `@rpath/<dylib_basename>`, e.g. `@rpath/libfoo.1.1.0.dylib`.

These arise because the default GPRBuild configuration contains the following, which tells GPRBuild what install name to embed in a dylib when it links it:

```xml
  <!--  Darwin (MacOS): not applicable to iOS  -->
  <configuration>
    <compilers negate="true">
       <compiler runtime="ios-simulator" />
    </compilers>
    <targets>
       <target name="^i.86-.*darwin.*$" />
       <target name="^powerpc-.*darwin.*$" />
       <target name="^x86_64-.*darwin.*$" />
       <target name="^aarch64-.*darwin.*$" />
    </targets>
    <config>
    <!-- ... -->
   for Library_Install_Name_Option use "-Wl,-install_name,@rpath";
    <!-- ... -->
    </config>
  </configuration>
```

(The above comes from https://github.com/AdaCore/gprconfig_kb/blob/v23.0.0/db/linker.xml, which the `gprbuild-boot` and `gprbuild` packages install into `<nix_store_package_root>/share/gprconfig/linker.xml`.)

**Comment by boeyms** [comment]
### Some changes that don't work

If the GPRBuild default configuration has
```
   for Library_Install_Name_Option use "-Wl,-install_name,";
```
instead of the above, the install name given to a dylib when it is linked becomes `/<dylib_basename>`, e.g. `/libfoo.1.1.0.dylib`.

If `Library_Install_Name_Option` is not set at all (i.e. in neither the GPRBuild default config nor the project-specific config), the install name given to a dylib when it is linked is the absolute path to the dylib at the time (i.e. the build-time location, not the future install location).

### An alternative that might work, but that currently seems inadvisable

We could try to modify GPRBuild's default config to make GPRBuild generate install names with absolute paths, but this looks like it would not be clean, and certainly not suitable for upstream.

- We need to be able to specify a runtime variable substitution to be able to have something like
  ```
     for Library_Install_Name_Option use "-Wl,-install_name,${dylib_dir}";
  ```
  in GPRBuild config files.
- Since none of the predefined variables do what we need, we would have to use a [custom GPRBuild config variable](https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/companion_tools.html#gprconfig-variable-substitution), and those are:
  - definable only on _compiler definitions_, so we would need to add something like
    ```xml
    <variable name="dylib_dir">
      <external>echo ${out}/lib</external>
    </variable>
    ```
    to the definition for _each compiler_ used by _any Nix package_ built with GPRBuild; and
  - when referred to outside a compiler definition, scoped _per source code language_, so we would have to have an Ada copy of the config using `${dylib_dir(Ada)}`, a C copy using `${dylib_dir(C)}`, and so on for any other language used in a Nix package built with GPRBuild.

We could try to teach some combination of GPRBuild and/or GPRInstall to do what we need in a cleaner way, but it appears me that that would require a non-trivial extension to what they currently support.

**Comment by Et7f3** [comment]
> Alternatively, we could add a new package (e.g. fixGPRBuildDarwinDylibNames) that just does replaces @rpath/<dylib_basename> references, and depend on that. That avoids the mass rebuild, but means a second package that wouldn't really be warranted were it not for the mass rebuild consideration.

What you can do is define `fixGPRBuildDarwinDylibNames` so you can have a quicker feedback loop and afterward you can rename it and PR staging (it is dedicated for mass re build) and then we can come back with this PR. You can ping at NixOS/darwin-maintainers for this.

**Comment by sternenseemann** [comment]
See #230847, #230710.

**Comment by sternenseemann** [comment]
@boeyms You may still want to look over the merged changes, seems like the setup hooks you came up with independently handles a few more edge cases.

**Pull request closed without merging**
