### PR TITLE
shellhub-agent: add update.sh script

### PR DESCRIPTION
**Pull request by otavio**
###### Motivation for this change

I am learning more about how to ease the maintainer's life and I am then adding the new script here so we can easily upgrade to the new releases when they are made.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
genericUpdater does most of this and can easily be added in a few lines. Please use this.

Also there is nix-update  which can do this in one command without any extra scripts like so: ``nix-update shellhub-agent``

**Comment by jonringer** [comment]
you will probably just want to add this to the derivation:
```
  passthru = {
    updateScript = nix-update-script {
      attrPath = pname;
    };
  };
```

**Comment by otavio** [comment]
Thanks @SuperSandro2000 and @jonringer. The hint about the `generic-updater` was great. I reworked the commit with it.

**Comment by thiagokokada** [comment]
Fix the commit text, since now you're not adding a `update.sh` script.

**Comment by otavio** [comment]
Thanks @thiagokokada, please recheck it.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
