### PR TITLE
ns-3: 3.35 -> 3.37

### PR DESCRIPTION
**Pull request by rgrunbla**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rgrunbla** [comment]
So this is a work in progress for packaging ns-3 3.37, which changed of build system from waf to a cmake based one, but with an helper python script for the cmake configuration. I will probably need some help regarding this packaging.

**Comment by nixinator** [comment]
This doesn't seem to build the actualy ns3 binary, but just seems to build
```

ls /nix/store/...-ns-3-35/bin]

ns3.35-bench-packets-debug    ns3.35-print-introspected-doxygen-debug  ns3.35-tap-creator-debug
ns3.35-bench-simulator-debug  ns3.35-raw-sock-creator-debug            ns3.35-tap-device-creator-debug
```

**Comment by rgrunbla** [comment]
Ns-3 is a library to do network simulation, not a binary. Arguably, the most important thing is stuff in /lib/, not even stuff in /bin/ (but it's still important to check whether the simulator works as expected).

**Comment by nixinator** [comment]
Must of got confused with this,  https://www.nsnam.org/docs/release/3.37/tutorial/html/quick-start.html#brief-summary

which mentioned ./ns3 

But i think this package is something different.

**Comment by teto** [comment]
sry this got forgotten ('cos of draft status maybe). Closing in favor of more uptodate https://github.com/NixOS/nixpkgs/pull/242131/

**Pull request closed without merging**
