### PR TITLE
bird-lg: unstable-2022-05-08 -> 1.2.0 

### PR DESCRIPTION
**Pull request by e1mo**
###### Description of changes

Notable Changes from https://github.com/xddxdd/bird-lg-go/releases:

- Use MTR for traceroute
- usage of local whois command
- more bird commands

The new traceroute-flags argument is now present in the module and for good measure the combined derivation now also has a version and meta tags.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Tchekda — COMMENTED** [review]
Looks good to me. 
Although I would suggest waiting for #226169 to be merged since it refactors the whole argument logic

**Comment by Tchekda** [comment]
For github reference #226169

**Comment by e1mo** [comment]
To me the order doesn't matter that much. I'll have to rebase in both cases and in the end it'll only be a couple of lines for me to copy and paste / play merge conflict resolve with.

**Review by Tchekda — APPROVED** [review]

**Review by Tchekda — APPROVED** [review]

**Comment by yu-re-ka** [comment]
Please rebase :)

**Comment by e1mo** [comment]
Done! Thanks for the merge @yu-re-ka :)

**Review by Tchekda — APPROVED** [review]
Looks good to me ! :+1:

**Pull request merged**
