### PR TITLE
 binutils-unwrapped: expose if built with ld.gold 

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

ld.gold is “A new, faster, ELF only linker”. Thus we only should pass
the configure flag --with-gold if our target platform will actually
support gold (in which case binutil's configure script silently
disables it).

With this change, not only will configureFlags represent the actual
configuration more closely, but we can also expose if the binutils
derivation contains ld.gold via a passthru attr. Specifically this
means that:

    nix-repl> pkgsCross.mingwW64.stdenv.cc.bintools.bintools.hasGold
    false

The intended way to use this is to check
`stdenv.cc.bintools.bintools or false` which returns accurate results
regardless of the actual linker derivation.

TODO: maybe also add hasGold to binutils wrapper as it also symlinks
ld.gold in?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132538` at c664979c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>simavr</li>
    <li>tinygo</li>
  </ul>
</details>
<details>
  <summary>19 packages built successfully:</summary>
  <ul>
    <li>armTrustedFirmwareAllwinner</li>
    <li>armTrustedFirmwareQemu</li>
    <li>armTrustedFirmwareRK3328</li>
    <li>armTrustedFirmwareRK3399</li>
    <li>armTrustedFirmwareS905</li>
    <li>gnuk</li>
    <li>ubootBananaPim64</li>
    <li>ubootNanoPCT4</li>
    <li>ubootOdroidC2</li>
    <li>ubootOrangePiZeroPlus2H5</li>
    <li>ubootPine64</li>
    <li>ubootPine64LTS</li>
    <li>ubootPinebook</li>
    <li>ubootPinebookPro</li>
    <li>ubootROCPCRK3399</li>
    <li>ubootRock64</li>
    <li>ubootRockPi4</li>
    <li>ubootRockPro64</li>
    <li>ubootSopine</li>
  </ul>
</details>

**Comment by alexfmpe** [comment]
I dunno what's idiomatic with passthru and all that, but this is much better than the special-casing I was doing for gold on windows in https://github.com/NixOS/nixpkgs/pull/132199.

**Comment by alexfmpe** [comment]
Do `8.6.5-binary.nix` & `8.10.2-binary.nix` not need this?

**Comment by sternenseemann** [comment]
> Do `8.6.5-binary.nix` & `8.10.2-binary.nix` not need this?

No, I don't think we can influence the linker they use anyways. I assume they always call plain `ld`.

**Comment by sternenseemann** [comment]
What uses GNU `binutils` on darwin? These rebuilds confuse me a bit, seems like we need to do some testing there.

**Comment by alexfmpe** [comment]
> No, I don't think we can influence the linker they use anyways. 

Yeah, I don’t see a gold flag or such.
> I assume they always call plain `ld`.

Almost always, it seems.
https://github.com/NixOS/nixpkgs/blob/4643bd80bd4401046fcca0bc4e35f4c2e41082b4/pkgs/development/compilers/ghc/8.10.2-binary.nix#L240-L243

**Comment by sternenseemann** [comment]
I'm pretty sure `LD` refers to the build linker here, maybe @expipiplus1 or @Ericson2314 can confirm this? What confuses me here is the use of `targetPlatform`, maybe it was a bit overeager?

Maybe we should be more eager to use gold here anyways, since it likely speeds up linking?!

**Review by Ericson2314 — COMMENTED** [review]
I would do `gold ? execFormatIsELF` and `assert gold -> execFormatIsELF`, as explicitly asking for gold when it won't build should be an error.

**Comment by sternenseemann** [comment]
Makes sense yeah, but I wouldn't remove the `hasGold` thing. Although it is unlikely to ever change that `hasGold` -> `execFormatIsELF`, it makes code easier to understand and requires less special knowledge.

**Comment by Ericson2314** [comment]
Yeah I would expose `hasGold = gold` in passthru but not bother let-binding it.

**Comment by sternenseemann** [comment]
Done in 4c75874560d114032e3d3ee0e6ffe9dd880a3859.

**Pull request merged**
