### PR TITLE
ceph: 15.2.6 -> 15.2.7

### PR DESCRIPTION
**Pull request by srhb**
Bugfix release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srhb** [comment]
@ofborg test ceph-single-node ceph-multi-node

**Comment by SuperSandro2000** [comment]
Please create the backport after the inital PR is merged.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106271` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106271` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>libceph</li>
    <li>sambaFull (samba4Full)</li>
  </ul>
</details>

**Comment by srhb** [comment]
@SuperSandro2000 

> Please create the backport after the inital PR is merged.

Why is that? I'm taking care not to muddle the history, not rebasing, and including the correct cherry message. If there's some problem with this procedure, I must be missing it. :) It's a semi-big build, so I usually prefer things tested for both branches when I have the time.

**Pull request merged**
