### PR TITLE
iamy: 2.1.1 -> 2.3.2

### PR DESCRIPTION
**Pull request by suvash**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build eval
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Review by marsam — COMMENTED** [review]
Looks like upstream uses go modules, would you mind updating the expression to [`buildGoModule`](https://nixos.org/nixpkgs/manual/#ssec-go-modules)?

**Review by dtzWill — CHANGES_REQUESTED** [review]
Instead of `deps.nix` (bit of a pain to maintain and sometimes significant in size), it looks like upstream moved to new go mod goodness (`go.mod` and `go.sum` indicate this), so instead of `buildGoPackages` and `deps.nix` you can use `buildGoModule` and `modSha256`.  Bonus is we aren't duplicating upstream's information about pinned dependencies :).

EDIT: oops missed @marsam's comment, which suggests this as well :).

**Comment by suvash** [comment]
@marsam @dtzWill finally had the time to look into this again. Tested on my local nixOS installation, and works fine. Let me know if I've missed sth elle.

**Comment by kalbasit** [comment]
@GrahamcOfBorg build iamy

**Review by kalbasit — APPROVED** [review]

**Pull request merged**
