### PR TITLE
blender: 3.3.1 -> 3.4.1

### PR DESCRIPTION
**Pull request by dritter**
This is based on #207284 and thus targeted at staging. I included the commit from #207284 here for easier testing.

Caveat:
On my machine blender wouldn't start because of:
image

Hopefully this is an issue on my machine only.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
patching file CMakeLists.txt
Hunk #1 succeeded at 1731 with fuzz 1 (offset -163 lines).
patching file build_files/cmake/platform/platform_apple.cmake
Hunk #1 succeeded at 68 with fuzz 1 (offset 8 lines).
Hunk #2 succeeded at 110 (offset 13 lines).
Hunk #3 FAILED at 113.
Hunk #4 succeeded at 129 (offset -13 lines).
Hunk #5 succeeded at 141 (offset -13 lines).
Hunk #6 succeeded at 243 (offset -23 lines).
Hunk #7 succeeded at 329 (offset -65 lines).
1 out of 7 hunks FAILED -- saving rejects to file build_files/cmake/platform/platform_apple.cmake.rej
```

**Comment by dritter** [comment]
@risicle Thanks for the helpful feedback. I hopefully fixed the darwin.patch. Could you please try again?

**Comment by risicle** [comment]
That improves the situation.

My testing may be invalidated by me cherry-picking this to master for easier testing (building staging on darwin is a big build) but now I get:

```
...
-- Using pre-compiled LIBDIR: /does-not-exist
-- Found Alembic: /nix/store/bnq6w5g121fkw6xw2qdv2rsyzr8acckc-alembic-1.8.3-lib/lib/libAlembic.dylib  
CMake Error at /nix/store/89yf6kmmlkij79p7nzh145x12bad8hc9-cmake-3.24.3/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find USD (missing: USD_LIBRARY USD_INCLUDE_DIR)
Call Stack (most recent call first):
  /nix/store/89yf6kmmlkij79p7nzh145x12bad8hc9-cmake-3.24.3/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  build_files/cmake/Modules/FindUSD.cmake:56 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  build_files/cmake/platform/platform_apple.cmake:99 (find_package)
  CMakeLists.txt:1079 (include)
```

**Comment by dritter** [comment]
Not sure if it is better to enable or disable USD. I now went with enabling it. Could you try again?

**Comment by risicle** [comment]
Well, setting `-DWITH_USD=OFF` lets it get further, to show it having problems finding `libharu` now:

```
CMake Error at /nix/store/89yf6kmmlkij79p7nzh145x12bad8hc9-cmake-3.24.3/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Haru (missing: HARU_LIBRARY)
Call Stack (most recent call first):
  /nix/store/89yf6kmmlkij79p7nzh145x12bad8hc9-cmake-3.24.3/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  build_files/cmake/Modules/FindHaru.cmake:50 (find_package_handle_standard_args)
  build_files/cmake/platform/platform_apple.cmake:355 (find_package)
  CMakeLists.txt:1079 (include)
```

**Comment by risicle** [comment]
Guessing USD is https://github.com/PixarAnimationStudios/USD

**Comment by risicle** [comment]
BTW I think what might be happening here is just blender having different cmake defaults on darwin. Guess is that the "working" builds on linux are just not _looking_ for libharu?

**Comment by phpcitizen** [comment]
Sorry to cloud this conversation, but I am curious what is holding the 3.4.1 update?

**Comment by dritter** [comment]
Sorry for the late response. I hadn't had time to continue my work on this. Plus: it is not very fruitful not being able to execute on my machine. I would be happy if anybody would take this as a starting point and continues from here on.

Regarding libharu:
That should be investigated. I saw #196599 , but I don't know if this fixes the libharu build.

@phpcitizen: Does this PR work on your machine?

**Comment by SuperSandro2000** [comment]
already updated by #223478

**Comment by phpcitizen** [comment]
Blender is already 3.5 for a month now.

**Comment by Pauan** [comment]
@phpcitizen There are some errors with Blender 3.5 that I wasn't able to fix:

```
Failed to open dir (No such file or directory): /run/user/1000/gvfs/
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_anim_bvh'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_curve_svg'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_mesh_ply'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_mesh_stl'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_mesh_uv_layout'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_scene_fbx'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_scene_gltf2'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_scene_obj'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_scene_x3d'
Traceback (most recent call last):
  File "/nix/store/12flyagsl093mcny0xbaj6250b7qlb3b-blender-3.5.0/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'pose_library'
```

So if anybody has any ideas on what's going on or how to fix it, that would be great.

**Comment by Pauan** [comment]
@phpcitizen I still have no idea what causes those errors, but they seem to be fixed by Blender 3.5.1, so I made a PR: https://github.com/NixOS/nixpkgs/pull/229570

**Pull request closed without merging**
