### PR TITLE
Merge pull request #63447 from jtojnar/sublime-cleanup

### PR DESCRIPTION
**Pull request by jtojnar**
cc @Ma27

### CODE REVIEW

**Comment by Ma27** [comment]
I'm absolutely in favor of dropping Sublime.

Btw does this also fix the problem with saving as root or is my `libredirect` patch still needed for that?

**Comment by jtojnar** [comment]
No, sublime switched to `posix_spawnp` so we still need the patch.

**Comment by Ma27** [comment]
> No, sublime switched to posix_spawnp so we still need the patch.

Ack. I mainly asked because I didn't test the `pkexec` case on my PR as mentioned there and I wanted to ensure that this is still relevant then :)

The patch itself seems fine, I'd test my branch with this PR (or master if this gets merged before I get to testing :D) by the end of the week.

**Comment by jtojnar** [comment]
Looking at the binaries with `objdump` they appear to have switched from `posix_spawn` to `posix_spawnp` for all programs. I verified that pkexec works so this should be good to merge.

**Pull request merged**
