### PR TITLE
vimPlugins.mediawiki-vim: init at 2015-11-15

### PR DESCRIPTION
**Pull request by tomodachi94**
###### Description of changes

Add the [mediawiki-vim](https://github.com/chikamichi/mediawiki.vim) plugin to the Vim plugins list and update said plugin list.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tomodachi94** [comment]
Whoops, forgot to update the grammars. Thank you for doing that.

**Comment by figsoda** [comment]
the update script should automatically update nvim-treesitter grammars too, did any thing crash for you by any chance?

**Comment by tomodachi94** [comment]
I didn't get any errors when I ran the script; I'm not sure why they didn't run automatically.

**Comment by figsoda** [comment]
no worries, I will investigate this and try to fix this some other time

**Review by figsoda — APPROVED** [review]
Result of `nixpkgs-review pr 208658` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>130 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ai-vim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-checkout-vim</li>
    <li>vimPlugins.fzf-hoogle-vim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.jedi-vim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.kotlin-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.mediawiki-vim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nginx-vim</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nui-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-biscuits</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-go</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-scrollbar</li>
    <li>vimPlugins.nvim-snippy</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-context-commentstring</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.onenord-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.ssr-nvim</li>
    <li>vimPlugins.tabnine-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.urlview-nvim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-dadbod</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-fzf-coauthorship</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-racket</li>
    <li>vimPlugins.vim-sensible</li>
    <li>vimPlugins.vim-signify</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vim-wayland-clipboard</li>
    <li>vimPlugins.vim-zettel</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.zenbones-nvim</li>
    <li>vimPlugins.zephyr-nvim</li>
    <li>vimPlugins.zig-vim</li>
  </ul>
</details>

**Pull request merged**
