### PR TITLE
helm: 2.11.0 -> 2.13.0

### PR DESCRIPTION
**Pull request by markus1189**
Reverting back to binary download, because generating nix build from
source does not work with current state of `helm` and `dep init`

###### Motivation for this change

The current helm version was quite old (`2.11.0`).
This *reverts back to downloading the pre-built binary*, because I couldn't get a working build from source.

It seems like there is a bug in `dep` that leads to a problem when calling `dep init` on the downloaded `helm` repository: https://github.com/golang/dep/issues/1841

Instead of waiting for all the possible upstream fixes (fix in dep, helm switching from glide to dep, ...) I decided to revert back to the binary download.  Maybe at a later time we can re-introduce a source-build.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lightbulbjim** [comment]
Note this package is actually named `kubernetes-helm` in `pkgs/top-level/all-packages.nix`. `helm` is a different package altogether.

**Comment by brodul** [comment]
Current `2.11.0` helm in `nixpkgs` is quite buggy. 

For example the `version` does not match semver scheme. 
```
helm version
Client: &version.Version{SemVer:"v2.11.0+unreleased", GitCommit:"", GitTreeState:""} 
```
That leads to errors:
```
brodul:code/ $ helm tiller install
Installed Helm version &version.Version{SemVer
Installed Tiller version v2.11.0+unreleased
Installing Tiller v&ersion.Version{SemVer ...
version &ersion.Version{SemVer does not match the semver scheme 'X.Y.Z(-PRERELEASE)(+BUILD)'. See help for more information.                                            
Error: plugin "tiller" exited with error

```

**Comment by yurrriq** [comment]
:+1: to this, but I'd recommend [v2.14.1](https://github.com/helm/helm/releases/tag/v2.14.1) now.

**Comment by aanderse** [comment]
triage: What is the state of this PR? Still waiting on upstream?

**Comment by yurrriq** [comment]
In my opinion, the binary approach here is solid, but the version should be [2.14.2](https://github.com/helm/helm/releases/tag/v2.14.2) at this point.

**Comment by aanderse** [comment]
@markus1189 Are you able to continue working on this PR and update as requested?

**Comment by markus1189** [comment]
I'll have a look!

**Comment by markus1189** [comment]
Updated with the binary build of `2.14.2` .  I did not check whether source build would work again though

**Comment by aanderse** [comment]
@edude03 @teozkr @nlewo @yurrriq Can I get one or more of you to either approve or approve and merge this PR?

**Comment by teozkr** [comment]
@aanderse I'm not familiar enough with the Go ecosystem to have a strong opinion on this. I'd generally prefer to stick to source builds but if that's not viable for now then staying up to date probably takes precedence.

**Comment by edude03** [comment]
I think we should stick with the source build and figure out the dep issue if possible. I managed to get it to work before and I'm sure I could again, although I won't have time to look at it until friday most likely.

**Comment by aanderse** [comment]
We're at 4 months on this PR already so waiting for @edude03 to take a look on Friday seems reasonable to me. Thanks for your offer!

**Pull request closed without merging**
