### PR TITLE
[Backport release-24.05] opensc: 0.25.1 -> 0.26.0

### PR DESCRIPTION
**Pull request by michaeladler**
Backport of https://github.com/NixOS/nixpkgs/pull/345666

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by numinit** [comment]
Rename this to `[Backport release-24.05] opensc: 0.25.1 -> 0.26.0`

**Comment by numinit** [comment]
Do you mind doing the same cherry picks against 24.11?

Anyway, LGTM:

Result of `nixpkgs-review pr 355910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>chrome-token-signing</li>
    <li>hw-probe</li>
    <li>libdigidocpp</li>
    <li>libdigidocpp.bin</li>
    <li>libdigidocpp.dev</li>
    <li>libdigidocpp.lib</li>
    <li>opensc</li>
    <li>pkcs11-provider</li>
    <li>qdigidoc</li>
    <li>rng-tools</li>
    <li>step-kms-plugin</li>
    <li>tpm2-pkcs11</li>
    <li>tpm2-pkcs11.bin</li>
    <li>tpm2-pkcs11.dev</li>
    <li>vmware-horizon-client</li>
  </ul>
</details>

**Review by numinit — APPROVED** [review]

**Comment by michaeladler** [comment]
> Do you mind doing the same cherry picks against 24.11?

@numinit If you mean `release-24.11` then I think there's nothing to do because the branch already contains the relevant commits

**Comment by numinit** [comment]
Ah, I must have misread. Thanks for checking.

**Review by numinit — APPROVED** [review]

**Review by LeSuisse — COMMENTED** [review]
Looks good, looks like one driver was disabled which might not be suitable for a backport to stable. Could we maybe revert https://github.com/OpenSC/OpenSC/pull/3152?


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355910`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 15 packages built:</summary>
  <ul>
    <li>chrome-token-signing</li>
    <li>hw-probe</li>
    <li>libdigidocpp</li>
    <li>libdigidocpp.bin</li>
    <li>libdigidocpp.dev</li>
    <li>libdigidocpp.lib</li>
    <li>opensc</li>
    <li>pkcs11-provider</li>
    <li>qdigidoc</li>
    <li>rng-tools</li>
    <li>step-kms-plugin</li>
    <li>tpm2-pkcs11</li>
    <li>tpm2-pkcs11.bin</li>
    <li>tpm2-pkcs11.dev</li>
    <li>vmware-horizon-client</li>
  </ul>
</details>

**Comment by michaeladler** [comment]
Good catch. I guess the patch is simple enough to maintain it. Note that support for these MICARDO cards is still around if you add `old` to `card_drivers` in the configuration file. So technically it's not necessary but the user experience is nicer for sure if you don't have to change your configuration file.

**Review by LeSuisse — APPROVED** [review]
Changes look good.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355910`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 15 packages built:</summary>
  <ul>
    <li>chrome-token-signing</li>
    <li>hw-probe</li>
    <li>libdigidocpp</li>
    <li>libdigidocpp.bin</li>
    <li>libdigidocpp.dev</li>
    <li>libdigidocpp.lib</li>
    <li>opensc</li>
    <li>pkcs11-provider</li>
    <li>qdigidoc</li>
    <li>rng-tools</li>
    <li>step-kms-plugin</li>
    <li>tpm2-pkcs11</li>
    <li>tpm2-pkcs11.bin</li>
    <li>tpm2-pkcs11.dev</li>
    <li>vmware-horizon-client</li>
  </ul>
</details>

**Pull request merged**
