### PR TITLE
n2: init at unstable-2022-12-21

### PR DESCRIPTION
**Pull request by fgaz**
###### Description of changes

A ninja compatible build system

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by robert-manchester** [comment]
Q: are new packages supposed to go into [pkgs/by-name](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/README.md)?

**Comment by fgaz** [comment]
It's not mandatory and this PR predates by-name. Though I can change it if you think I should

**Comment by robert-manchester** [comment]
another Q: is n2 used in any projects? it looks like just someones hobby project.

**Comment by fgaz** [comment]
> reviews for other packages request it -- given that you're listed as a maintainer on 120 other projects it's up to you

I still make many mistakes ;)

I moved the package to by-name

> is n2 used in any projects?

It's a ninja drop-in replacement, so it's used in zero projects and at the same time it can be used in all projects that use ninja

> it looks like just someones hobby project.

Yes, except that someone is Evan Martin, the author of ninja :)

**Review by ghost — APPROVED** [review]

**Comment by robert-manchester** [comment]
if you don't mind taking a look I have 2 PRs I'm trying to get merged.
#260423 and #259340
thx!

**Pull request merged**
