### PR TITLE
 thunderbird, thunderbird-bin: 60.8.0 -> 68.0 

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

Many updates and fixes.

https://www.thunderbird.net/en-US/thunderbird/68.0/releasenotes/

Unsolved problem: when you upgrade from older version, the old profile is ignored and a new profile is created.
Workaround: launch Thunderbird with `-P` option and select the old profile. This is only needed for the first time.
https://bugzilla.mozilla.org/show_bug.cgi?id=1542025

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @nbp @edolstra @Fuuzetsu

### CODE REVIEW

**Comment by vcunat** [comment]
Isn't that the same problem as we patched in Firefox?

**Comment by taku0** [comment]
> Isn't that the same problem as we patched in Firefox? (Perhaps it might even apply the same?)

Applied the fix.

**Comment by mweinelt** [comment]
I've tested this changeset, I started Thunderbird via `./thunderbird -P` and I can still up/downgrade to/from 60.8.0. All in all it seem to work well.

**Comment by vcunat** [comment]
I wonder how we should communicate this (one-time) workaround or do something else about it, especially e.g. for the stable 19.03 branch.

**Comment by vcunat** [comment]
Oh, I missed that you applied the workaround.  I do not need to use the `-P` step for `thunderbird` (without `-bin`).  I suspect `thunderbird-bin` requires it in my case because it's really considered a different version?

**Comment by taku0** [comment]
I have applied `SNAP_NAME` trick to both `thunderbird` and `thunderbird-bin`, though I didn't tested it works.

**Review by vcunat — APPROVED** [review]
Works fine for me.

**Pull request merged**
