### PR TITLE
Darwin misc. fixes

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

These are some more fixes I've put together. Make sure they build on nox-review under Linux before merging, just in case they break something.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
I also recently broke mariadb on Darwin and I don't know a good way to fix it, I'm sorry. http://hydra.nixos.org/build/38458779/nixlog/1/raw (There should be some fixed vulnerabilities in the updates.)

**Comment by matthewbauer** [comment]
@vcunat it looks like jemalloc is not being built correctly

**Comment by copumpkin** [comment]
This is awesome. I haven't tested any of it, but really appreciate people putting work against darwin.

**Comment by vcunat** [comment]
> it looks like jemalloc is not being built correctly

If some of you who do have a Darwin access could fix it, it would be nice, as Qt is blocked by that.

**Comment by vcunat** [comment]
Maybe I'll get lucky now: 1c9307d34.

**Comment by copumpkin** [comment]
I'm looking at the `jemalloc` issue. It seems that `mariadb` is looking for `malloc_stats_print` but that `libjemalloc` sticks `je_` prefix on its symbols by default (on Darwin at least) so `mariadb` fails to find the symbol. Anyone know what's up with that, and why it doesn't seem to affect linux?

**Comment by copumpkin** [comment]
Aha, https://github.com/jemalloc/jemalloc/blob/0c5cec833fb2b075222ee19a41c03f32178d3be1/INSTALL. I'll fix.

**Comment by copumpkin** [comment]
@matthewbauer do any of these cause a mass [darwin] rebuild? What's a sensible way to test these changes? I'd like to merge wholesale but am not sure how to be responsible about it.

@vcunat I think `jemalloc` is good again, as of https://github.com/NixOS/nixpkgs/commit/1f0df5f21fa038eb27e1a02ed47141d2d6fa214f. That was half of what was wrong with `mariadb`, and I fixed the rest in https://github.com/NixOS/nixpkgs/commit/ccd16f87d545448ad8c3b5037d191d1994226a67.

**Comment by matthewbauer** [comment]
@copumpkin stdenv should be unaffected if that's what you mean by mass rebuild.

Here's what's affected on Darwin:

bs1770gain gegl libsecret glew110 unrtf geany stm32flash smartmontools gimpPlugins.gap gpshell john tie fontforge-gtk libfreefare stfl boringssl mosquitto dog cwebbin mg gppcscconnectionplugin gpicview newsbeuter-dev cccc sailsd genromfs tm hardlink unclutter gimpPlugins.lqrPlugin runningx libstatgrab gimp nss dclxvi odt2txt openct cddiscid libykneomgr rakudo gimpPlugins.waveletSharpen setroot yubico-piv-tool nspr gimpPlugins.texturize globalplatform dumptorrent newsbeuter sl stricat fox svrcore nssTools erlangR16 gkrellm opensc pcsclite pond

and this is what's affected on Linux:

gnome3.networkmanager_pptp eclipses.eclipse-sdk-422 gnome3.networkmanager_vpnc awesome jumanji python27Packages.redNotebook hardlink stm32flash gnome3.pomodoro tuxguitar gnome3.gnome-online-miners vimb networkmanager_openvpn networkmanager_openconnect cccc eclipses.eclipse-sdk-431 gnome3.gnome_terminal beets gnome3.networkmanagerapplet stfl gnome3.geary miro dwb gnome3.webkitgtk mg eclipses.eclipse-sdk-421 pond guitarix pytrainer dclxvi eclipses.eclipse-cpp-37 eclipses.eclipse-cpp-36 gnome3.grilo-plugins xiphos genromfs eclipses.eclipse-sdk-451 evince eclipses.eclipse-cpp-44 eclipses.eclipse-sdk-35 newsbeuter gnucash26 font-manager dwb-unwrapped gnome3.networkmanager_openvpn eclipses.eclipse-sdk-442 gnome3.gnome-music mkcast sailsd openmodelica eclipses.eclipse-sdk-36 gnome3.california gnome3.devhelp gnome3.gnome-tweak-tool stricat tie runningx gnome3.vino gnome3.bijiben mu osmo unclutter gnome3.gnome-maps eclipses.eclipse-scala-sdk-40 liferea uzbl eclipses.eclipse-platform-452 eclipses.eclipse-sdk-46 gnome3.networkmanager_openconnect gnome3.gnome-photos gnome3.gnome_online_accounts gnome3.folks gnome3.tracker gnome3.sushi eclipses.eclipse-sdk-452 edit gnome3.libgdata gnome3.gnome-contacts vimprobable2-unwrapped areca networkmanagerapplet gnome3.gnome-calendar unrtf webkitgtk210x eclipses.eclipse-platform-451 webkitgtk2 gnome3.yelp gnome3.gfbgraph gnome3.gnome_shell gnome3.libzapojit surf eclipses.eclipse-platform-45 azureus gnome3.gnome_control_center gnome3.networkmanager_l2tp eclipses.eclipse-cpp-42 darktable gnome3.gnome-user-docs tm vimprobable2 gnome3.seahorse eclipses.eclipse-cpp-43 recoll python27Packages.pywebkitgtk dog networkmanager_l2tp eclipses.eclipse-cpp-45 gnome3.evolution eclipses.eclipse-platform gitg eclipses.eclipse-sdk-45 dumptorrent sl bs1770gain networkmanager_pptp gpicview shotwell gnome3.nautilus evolution_data_server cwebbin odt2txt networkmanager_vpnc gnome3.vinagre gnome3.totem eclipses.eclipse-sdk-37 eclipses.eclipse-sdk-44 gnome3.file-roller epiphany gnome3.gpaste ekiga newsbeuter-dev gnome3.gnome-user-share eclipses.eclipse-modeling-36 midori-unwrapped gnome3.gnome-boxes gnome3.gnome-documents midori boringssl swt vimb-unwrapped libsecret gnome3.webkitgtk24x setroot luakit gnome3.gnome-disk-utility

It might seem weird to have so many affected on Linux but they're good improvement AFAICT. Most are from patching build scripts to use "cc" instead of "gcc". If we ever want to switch Linux from "gcc" to "clang" these changes will make things easier.

**Comment by copumpkin** [comment]
Sounds good to me. Anyone have objections to merging?

**Comment by matthewbauer** [comment]
@copumpkin While you're merging stuff, could you also look at merging #17642 into staging or master?

**Comment by copumpkin** [comment]
Running `nox-review` on linux now. Holy shit there are a lot of large source downloads involved (mostly eclipse-related crap?). Not sure how long this will take...

**Comment by copumpkin** [comment]
Still building `webkit` 😴

**Comment by dezgeg** [comment]
I wonder if we could just set `CC=cc` in the stdenv to avoid most of these.

**Comment by copumpkin** [comment]
I thought we already did that. But many builds still go out of their way to
set gcc

**Comment by copumpkin** [comment]
Okay, my linux box ran out of disk space after several hours of `nox-review` on this, so I can't really test it right now. I'll pass this to someone else who either has the confidence to merge it without rebuilding half of the linux GUI world (including two separate versions of webkit for some reason) or who has a beefier machine than I do.

**Comment by dezgeg** [comment]
Right, we do set it. Maybe an implicit `CC=$(CC)` in `makeFlags`, or something...

**Comment by matthewbauer** [comment]
@dezgeg The one thing I'd warn of with that is sometime Makefiles will be set CC to something weird like `gcc -pthread`. Changing that to just "$(CC)" will break. In that case, we can't really just overwrite it in makeFlags.

**Comment by jb55** [comment]
I'm running nox-review tonight on one of my beefy machines. will report back.

**Comment by jb55** [comment]
Hmm looks like it [failed](https://gist.github.com/jb55/12626623fc58e77010a8071dfd678341)

**Comment by dezgeg** [comment]
That one is already failing: http://hydra.nixos.org/build/38535205

**Comment by jb55** [comment]
rerunning without that one...

**Comment by jb55** [comment]
weird, getting a segfault in gcc now https://gist.github.com/jb55/90e3bf2b9bfc9049285534c87780c17c

**Comment by matthewbauer** [comment]
@copumpkin Can you merge this? There may still be issues but AFAICT no new errors are introducd.

**Comment by copumpkin** [comment]
@matthewbauer if you're sure that @jb55's gcc segfault doesn't stem from this, sure. Leaves me feeling a little uneasy to blindly merge a big lump of stuff like this with the last message being "I got a segfault in my compiler after merging this" 😄

**Comment by jb55** [comment]
The segfaulting seemed non-deterministic, I didn't have much time to look into it further :(

**Pull request merged**
