### PR TITLE
rabbitmq_server: Don't use getconf optimization on non-Linux systems

### PR DESCRIPTION
**Pull request by jwiegley**
This makes it impossible to build rabbitmq_server on Darwin, for example.

###### Motivation for this change

Without it, I cannot build `rabbitmq_server` on macOS.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Profpatsch** [comment]
Looks feasible; however I think the more sensible change is renaming `stdenv.lib.getBin stdenv.cc.libc` to `stdenv.lib.getBin getconf` (which is defined in `all-packages`) and changing that so it references the correct `getconf` path on Darwin.

**Comment by jwiegley** [comment]
@Profpatsch I'm not 100% clear on what you're proposing, can you show the changes needed?

**Comment by Profpatsch** [comment]
Here’s the first part of the necessary patch: https://github.com/NixOS/nixpkgs/compare/master...Profpatsch:rabbitmq-getconf-darwin

Can you look up which package your `getconf` binary comes from?

**Comment by matthewbauer** [comment]
Is it okay to hold off on this? In staging, we have a getconf provided by unix-tools.nix:

https://github.com/NixOS/nixpkgs/blob/staging/pkgs/top-level/unix-tools.nix#L50-L54

It should be a drop-in replacement, not needing the "small" hacks. unixtools.* should just be single binaries - no runCommand needed.

**Comment by Profpatsch** [comment]
> unixtools.* should just be single binaries - no runCommand needed.

Oh right, I forgot about that. @Ericson2314, do those tools work well with the cross system? That is, can we use the `getconf` from there? Maybe point the `getconf` in `all-packages` to that as well?

**Comment by Ericson2314** [comment]
Yes. @matthewbauer's unixtools looks wonderful to me.

**Comment by Profpatsch** [comment]
Yeah, on staging it’s already implemented, and rabbitmq fixed to the single-binary getconf.

**Pull request closed without merging**
