### PR TITLE
Revert "linux-firmware: 20230625 -> unstable-2023-07-24"

### PR DESCRIPTION
**Pull request by chayleaf**
This reverts commit 0c75a062bb27b20fc6003e4f7f8a4f093ed80676.

Newer firmware broke boot on my system (checked with a bisect):

IMG_2023-08-05-02-20-38-801

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Uhh what. Can you try https://github.com/NixOS/nixpkgs/pull/247097?

**Comment by chayleaf** [comment]
yes, it works fine, so I'm closing this in favor of your PR

**Comment by K900** [comment]
Honestly what the fuck is even happening here. Literally none of those changes should break boot. Can you try bisecting the individual commits in linux-firmware? I'd really want to take whatever we find here upstream.

**Comment by chayleaf** [comment]
ok, I'll try it later

**Comment by chayleaf** [comment]
The bad commit is [0bc3126c9cfa0b8c761483215c25382f831a7c6f](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=0bc3126c9cfa0b8c761483215c25382f831a7c6f) - "Update AMD fam17h cpu microcode"

**Comment by K900** [comment]
Wow, this is bad. Can you report it upstream?

**Comment by chayleaf** [comment]
Yes, but I'm not sure where I can report it (there are a bunch of docs for reporting Linux kernel issues, but I can't find any info on where to report linux-firmware issues, and the linux-firmware mailing list seems to basically only have patches

**Comment by chayleaf** [comment]
ok it's not as simple as I thought, my workaround doesn't even work... heisenbugs in this area are just the worst

**Pull request closed without merging**
