### PR TITLE
Update seafile-shared hash

### PR DESCRIPTION
**Pull request by jonafato**
###### Motivation for this change

`seafile-client` does not build successfully because of a hash mismatch in `seafile-shared`. The old hash appears to point to commit `b7f2be78c1d979ff1242c3b65b41228e31427843` rather than `ea8f5e2b45612d77fee9934f942d1d7d55560dad`, which is the commit that the `v6.2.10` tag currently references.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
That's a shame. We should open an upstream issue to tell them that's not okay at all.

**Comment by dotlambda** [comment]
Also. I'm stepping down as maintainer because I don't want to maintain software created by such incompetent people. I refrain from quoting the old Linus.

**Comment by jonafato** [comment]
>That's a shame. We should open an upstream issue to tell them that's not okay at all.

Good point, [done](https://github.com/haiwen/seafile/issues/2158). If / once I get an answer there, I'll follow up with a description of why this was a bad thing and how it'll end with package managers dropping the package entirely if this is a common occurrence.

**Comment by dotlambda** [comment]
Just checked in my RSS reader's cache and the entry used to be titled `v6.2.10: Merge pull request #2157 from haiwen/update_version_to_6.2.10`, which is not `b7f2be78c1d979ff1242c3b65b41228e31427843` but also definitely not `ea8f5e2b45612d77fee9934f942d1d7d55560dad`. Weird.
What I can confirm is that the entry changed upon reloading the RSS feed.

**Pull request merged**
