### PR TITLE
python310Packages.{nbclassic,notebook-shim,notebook,einops,xarray-einstats,arviz}: unbreak

### LINKED ISSUE #210793: `python310Packages.notebook` build failure on x86_64-linux as of `2da37482`
## Issue description
Build of `python310Packages.notebook` failed on x86_64-linux as of 2da37482b1c5d99851dc683c714429734cba4191. This is currently breaking `python3Packages.einops`.

```
error: builder for '/nix/store/10ngsxc808z7xs5vvbvgvjxr8hq2d5kb-python3.10-notebook-6.5.2.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'notebook-6.5.2.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > ~/notebook-6.5.2/dist ~/notebook-6.5.2
       > Processing ./notebook-6.5.2-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement nbclassic>=0.4.7 (from notebook) (from versions: none)
       > ERROR: No matching distribution found for nbclassic>=0.4.7
       > 
       For full logs, run 'nix log /nix/store/10ngsxc808z7xs5vvbvgvjxr8hq2d5kb-python3.10-notebook-6.5.2.drv'.
error: 1 dependencies of derivation '/nix/store/3iyalvdnnpjfp2arx6hrc25kwb9hk1h3-python3.10-jupyter-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b0l44wy0sqjkmiaa4a6gafwqhhiqqijg-python3.10-einops-0.6.0.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/3920896263)

python3Packages.einops maintainers cc: @yl3dy
python310Packages.notebook maintainers cc: @FRidh
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 2da37482b1c5d99851dc683c714429734cba4191
2. Run `nix-build -A python310Packages.notebook`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1030-azure, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/store/85kimkz0rlm1r7pv3w04sllbad0dcbkp-source`
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/3920896263) that created this issue.
- Internal tags: -257658660787171465 7411411812702024353

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Description of changes

Fixes #210793.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bcdarwin** [comment]
`python310Packages.aesara` (and hence `pymc`) is now broken as well as its tests fail due to a disagreement with `jax`, which is quite suspicious.

**Comment by bcdarwin** [comment]
`pynrrd` and `monai` are also broken; please merge #205721 and #205731

**Comment by samuela** [comment]
> `pynrrd` and `monai` are also broken; please merge #205721 and #205731

Are those prerequisites for merging this PR or can they be done independently?

**Comment by bcdarwin** [comment]
> > `pynrrd` and `monai` are also broken; please merge #205721 and #205731
> 
> Are those prerequisites for merging this PR or can they be done independently?

They can be done separately.

**Review by yl3dy — APPROVED** [review]
LGTM about einops

**Comment by risicle** [comment]
Named packages build for me (python 3.10 only) on aarch64-linux (apart from arviz, which is `broken` on aarch64)

**Comment by FRidh** [comment]
In the future a single commit per package please.

**Pull request merged**
