### PR TITLE
CuboCore.packages: 4.2.0 -> 4.3.0

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dan4ik605743 — COMMENTED** [review]
Works.

**Comment by bobby285271** [comment]
@ofborg build CuboCore.corekeyboard
@ofborg build CuboCore.corepdf
@ofborg build CuboCore.corestuff

**Comment by bobby285271** [comment]
The above 3 packages failed to build on x86_64-linux:

corekeyboard https://logs.nix.ci/?key=nixos/nixpkgs.152579&attempt_id=f5b4c2e6-f423-46b9-9b31-0489d4593cba
corepdf https://logs.nix.ci/?key=nixos/nixpkgs.152579&attempt_id=ad9bf2cf-be56-4270-af86-7e12322305d4
corestuff https://logs.nix.ci/?key=nixos/nixpkgs.152579&attempt_id=25998c4d-497e-4ea1-9b22-25a73072dabd

**Comment by dan4ik605743** [comment]
Strange, I checked everything was build.. I don't have a laptop with me right now. I can fix it only in a week.

**Comment by dan4ik605743** [comment]
> The above 3 packages failed to build on x86_64-linux:
> 
> corekeyboard https://logs.nix.ci/?key=nixos/nixpkgs.152579&attempt_id=f5b4c2e6-f423-46b9-9b31-0489d4593cba corepdf https://logs.nix.ci/?key=nixos/nixpkgs.152579&attempt_id=ad9bf2cf-be56-4270-af86-7e12322305d4 corestuff https://logs.nix.ci/?key=nixos/nixpkgs.152579&attempt_id=25998c4d-497e-4ea1-9b22-25a73072dabd

I did not have a lot of delayed, now I will try to solve the problem, generally strange I kind of when I felt the commote checked all the packages all mischilding.

**Comment by dan4ik605743** [comment]
All fixed.

**Review by dan4ik605743 — COMMENTED** [review]
@bobby285271 
image

**Review by c0bw3b — APPROVED** [review]
Result of `nixpkgs-review pr 152579` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>CuboCore.coreaction</li>
    <li>CuboCore.corearchiver</li>
    <li>CuboCore.corefm</li>
    <li>CuboCore.coregarage</li>
    <li>CuboCore.corehunt</li>
    <li>CuboCore.coreimage</li>
    <li>CuboCore.coreinfo</li>
    <li>CuboCore.corekeyboard</li>
    <li>CuboCore.corepad</li>
    <li>CuboCore.corepaint</li>
    <li>CuboCore.corepdf</li>
    <li>CuboCore.corepins</li>
    <li>CuboCore.corerenamer</li>
    <li>CuboCore.coreshot</li>
    <li>CuboCore.corestats</li>
    <li>CuboCore.corestuff</li>
    <li>CuboCore.coreterminal</li>
    <li>CuboCore.coretime</li>
    <li>CuboCore.coretoppings</li>
    <li>CuboCore.coreuniverse</li>
    <li>CuboCore.libcprime</li>
    <li>CuboCore.libcsys</li>
  </ul>
</details>

**Pull request merged**
