### PR TITLE
strongswan: add TNC build option

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
@shlevy @ip1981 Are you fine with the change?---It should not affect anything. I'm just asking as you integrated strongswan initially or modified it recently.

**Comment by ip1981** [comment]
Why not? Yet `enable-tnc` looks better to me ;-)

**Comment by shlevy** [comment]
Fine by me

**Comment by ts468** [comment]
Thanks!

**Pull request merged**
