### PR TITLE
gradle: 8.7 → 8.8

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
## Description of changes

https://docs.gradle.org/8.8/release-notes.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lorenzleutgeb** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>gscan2pdf</li>
    <li>gscan2pdf.man</li>
    <li>mindustry</li>
    <li>mindustry-server</li>
    <li>mindustry-wayland</li>
  </ul>
</details>
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>apkleaks</li>
    <li>apkleaks.dist</li>
    <li>apksigcopier</li>
    <li>apksigcopier.dist</li>
    <li>apksigner</li>
    <li>cie-middleware-linux</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>experienced-pixel-dungeon</li>
    <li>fdroidserver</li>
    <li>fdroidserver.dist</li>
    <li>ghidra-extensions.gnudisassembler</li>
    <li>ghidra-extensions.machinelearning</li>
    <li>ghidra-extensions.sleighdevtools</li>
    <li>gradle</li>
    <li>jabref</li>
    <li>jadx</li>
    <li>javaPackages.openjfx22</li>
    <li>jextract</li>
    <li>jextract-21</li>
    <li>kotlin-language-server</li>
    <li>moneydance</li>
    <li>pdf-sign</li>
    <li>pdfchain</li>
    <li>pdftk</li>
    <li>pidginPackages.purple-signald</li>
    <li>rat-king-adventure</li>
    <li>rkpd2</li>
    <li>shattered-pixel-dungeon</li>
    <li>shorter-pixel-dungeon</li>
    <li>signald</li>
    <li>signaturepdf</li>
  </ul>
</details>

[gscan2pdf.man.log](https://github.com/user-attachments/files/15532261/gscan2pdf.man.log)
[mindustry-wayland.log](https://github.com/user-attachments/files/15532262/mindustry-wayland.log)
[mindustry-server.log](https://github.com/user-attachments/files/15532263/mindustry-server.log)
[mindustry.log](https://github.com/user-attachments/files/15532264/mindustry.log)
[gscan2pdf.log](https://github.com/user-attachments/files/15532265/gscan2pdf.log)

**Review by liff — APPROVED** [review]
The Mindustry build failure needs to be addressed before merging, I suppose. Looks OK otherwise.

Can we get #277721 in before or after maybe? 😊

**Comment by fgaz** [comment]
> The Mindustry build failure needs to be addressed before merging, I suppose.

Until https://github.com/Anuken/Arc/issues/169 is fixed we can switch to gradle_7

**Comment by C0D3-M4513R** [comment]
It would be nice to get this in, as currently we have jdk22 in nixos but  no gradle, that supports jdk22 properly.

Full support for jdk22 in gradle was only added in gradle 8.8.

(I discovered that in https://github.com/Col-E/Recaf/pull/805)

**Comment by fgaz** [comment]
> Until [Anuken/Arc#169](https://github.com/Anuken/Arc/issues/169) is fixed we can switch to gradle_7 which still works

Now there is also a patch: https://github.com/Anuken/Arc/commit/d7f8ea858c425410dbd43374271a703d4443b432

**Comment by lorenzleutgeb** [comment]
@fgaz sure, but how long will it take until there is a new release of Mindustry that depends on a patched version of Arc and you found time to bump `pkgs.mindustry`? Months? I'd rather ask for you to pin `gradle = pkgs.gradle_7` in `pkgs.mindustry` in the meantime, which I expect to be a simple change. Thanks!

**Review by JohnRTitor — APPROVED** [review]
LGTM

**Comment by SuperSandro2000** [comment]
> Months? I'd rather ask for you to pin `gradle = pkgs.gradle_7` in `pkgs.mindustry` in the meantime, which I expect to be a simple change. Thanks!

This should have been ammended to this PR

**Pull request merged**
