### PR TITLE
staging-next 2024-08-06

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/328673
##### Mass breakages
_nothing notable so far_

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
psqlodbc fails to build which is a dep of qtbase:

```
@nix {"action":"setPhase","phase":"buildPhase"}
build flags: SHELL=/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash
make  all-am
make[1]: Entering directory '/build/psqlodbc-10.01.0000'
/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.   -I/nix/store/0hbam1jm78njnky9
nyk3z2gjmvvabajz-unixODBC-2.3.12/include -I/nix/store/1l4ybz2g8mz31m5pg1y7s1qq0kd9i1n5-postgresql-16.3/include -I/nix/store/1l4ybz2g8mz31m5pg1y7s1qq0kd9i1n5-
postgresql-16.3/include/internal -DUNICODE_SUPPORT  -g -O2 -Wall -c -o psqlodbcw_la-info.lo `test -f 'info.c' || echo './'`info.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/nix/store/0hbam1jm78njnky9nyk3z2gjmvvabajz-unixODBC-2.3.12/include -I/nix/store/1l4ybz2g8mz31m5pg1y7s1qq0kd9i1n
5-postgresql-16.3/include -I/nix/store/1l4ybz2g8mz31m5pg1y7s1qq0kd9i1n5-postgresql-16.3/include/internal -DUNICODE_SUPPORT -g -O2 -Wall -c info.c  -fPIC -DPI
C -o .libs/psqlodbcw_la-info.o
In file included from connection.h:14,
                 from info.c:34:
/nix/store/1l4ybz2g8mz31m5pg1y7s1qq0kd9i1n5-postgresql-16.3/include/internal/pqexpbuffer.h:168:8: error: unknown type name 'bool'
  168 | extern bool appendPQExpBufferVA(PQExpBuffer str, const char *fmt, va_list args) pg_attribute_printf(2, 0);
      |        ^~~~
make[1]: *** [Makefile:661: psqlodbcw_la-info.lo] Error 1
make[1]: Leaving directory '/build/psqlodbc-10.01.0000'
make: *** [Makefile:479: all] Error 2
```

**Comment by vcunat** [comment]
That should be https://github.com/NixOS/nixpkgs/pull/332329

**Comment by mhorbul** [comment]
After this merge awscli2-2.17.18 build started to fail 

```
building '/nix/store/a36sqbcyv57lgkv6kw1494n8zm95x1i0-awscli2-2.17.18.drv'...
error: builder for '/nix/store/a36sqbcyv57lgkv6kw1494n8zm95x1i0-awscli2-2.17.18.drv' failed with exit code 1;
       last 10 log lines:
       > tests/unit/customizations/logs/test_startlivetail.py::LiveTailKeyBindingsTest::test_t_key_binding
       >   /nix/store/kcm5282kss1mnil624lccr7y8wqg75vk-python3-3.11.9/lib/python3.11/enum.py:714: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
       >     return cls.__new__(cls, value)
       >   Enable tracemalloc to get traceback where the object was allocated.
       >   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/unit/customizations/cloudtrail/test_validation.py::TestSha256RSADigestValidator::test_validates_digests - ValueError: key_size must be at least 1024-bits.
       > ======= 1 failed, 4097 passed, 1 skipped, 2 warnings in 81.00s (0:01:20) =======
       For full logs, run 'nix log /nix/store/a36sqbcyv57lgkv6kw1494n8zm95x1i0-awscli2-2.17.18.drv'.
```

**Comment by kirillrdy** [comment]
awscli2 fixed https://github.com/NixOS/nixpkgs/pull/334858

**Comment by maralorn** [comment]
It seems like the periodic merges master -> staging-next, staging-next -> staging. Are somehow happening in my name. See e.g. here: https://github.com/NixOS/nixpkgs/actions/runs/10489420359

I currently get one alert every 6h because staging-next -> staging gives a merge conflict.

I think this has been going on for ages, but I recently changed the way I engage with GitHub notifications and no this alerts are a bit annoying to me.

According to this help article https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/notifications-for-workflow-runs
I assume this is happening because I renamed the workflow and therefor apparently count as it’s creator, even though there have been a lot of later changes to the workflow, but none of those changed the schedule or the name.

If anyone is interested in receiving these alerts, then according to the above help article they need to disable and reenable the workflow in the GitHub ui, making them the "actor" of the workflow.

Otherwise I am trying to figure out how to silence them for me, but I am not completely optimistic that I can.

**Comment by maralorn** [comment]
Yeah, as far as I can tell, I can just disable workflow notifications globally for all of GitHub which would not make my employer happy.

So if anyone would be willing to take this from me, because they either deal with staging more than I do or because they don’t care much about GitHub notifications anyway, I would be very thankful.

**Pull request merged**
