### PR TITLE
git-town: 7.2.0 -> 7.3.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
just going through r-ryantm logs

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

```
https://github.com/NixOS/nixpkgs/pull/84080
1 package built:
git-town
```

### CODE REVIEW

**Review by jollheef — CHANGES_REQUESTED** [review]
Should a cosmetic change of the code be in a separate commit?

**Comment by alyssais** [comment]
> Should a cosmetic change of the code be in a separate commit?

It’s clear enough from the message what changed, I think. (And theres always `-w`)

**Comment by jollheef** [comment]
> > Should a cosmetic change of the code be in a separate commit?
> 
> It’s clear enough from the message what changed, I think. (And theres always `-w`)

It's not only about "what changed", but also because it makes `git revert`, `git blame` and `git bisect` less useful. So that's why usually in development it's considered as a bad practice.

**Comment by jonringer** [comment]
> > > Should a cosmetic change of the code be in a separate commit?
> > 
> > 
> > It’s clear enough from the message what changed, I think. (And theres always `-w`)
> 
> It's not only about "what changed", but also because it makes `git revert`, `git blame` and `git bisect` less useful. So that's why usually in development it's considered as a bad practice.

I was just making it look like most other expressions. Which won't have much of an effect. You could argue that it should have been corrected on the initial commit.

**Comment by alyssais** [comment]
> It's not only about "what changed", but also because it makes `git
> revert`, `git blame` and `git bisect` less useful. So that's why
> usually in development it's considered as a bad practice.

"usually" is quite the weasel word.

I don't see how it meaningfully interferes with revert or bisect, and
blame takes -w to ignore whitespace.

**Comment by jollheef** [comment]
> I don't see how it meaningfully interferes with revert or bisect

If you need to revert, you cannot revert only functional changes, but you'll also revert refactoring.

**Comment by alyssais** [comment]
>> It's not only about "what changed", but also because it makes `git
>> revert`, `git blame` and `git bisect` less useful. So that's why
>> usually in development it's considered as a bad practice.
>
> "usually" is quite the weasel word.
>
> I don't see how it meaningfully interferes with revert or bisect, and
> blame takes -w to ignore whitespace.

I'd like to apologise for this comment.  It was unnecessarily rude.  I
was feeling upset at the time for other reasons, and I shouldn't have
taken it out on you.  I'm sorry.

**Pull request merged**
