### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
I think it would be better for these to be seperate PRs, so it was clear what each reviewer had to review, and discussion could be focused on one topic at a time.

**Comment by siraben** [comment]
```
error: value is a string with context while a list was expected

       at /home/siraben/.cache/nixpkgs-review/pr-132391/nixpkgs/pkgs/development/compilers/ecl/default.nix:56:14:

           55|   postInstall = let
           56|     ldArgs = lib.strings.concatMapStringsSep " "
             |              ^
           57|       (l: ''--prefix NIX_LDFLAGS ' ' "-L${l.lib or l.out or l}/lib"'')

       … while evaluating the attribute 'postInstall' of the derivation 'ecl-21.2.1'

       at /home/siraben/.cache/nixpkgs-review/pr-132391/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while querying the derivation named 'ecl-21.2.1'
https://github.com/NixOS/nixpkgs/pull/132391 failed to build
```

**Comment by SuperSandro2000** [comment]
> I think it would be better for these to be seperate PRs, so it was clear what each reviewer had to review, and discussion could be focused on one topic at a time.

I don't think this needs a code review from specific people. I mostly cleaned things up which don't require any discussion.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 132391` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>9 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>afew: log was empty</li>
<li>alot: log was empty</li>
<li>lieer: log was empty</li>
<li>meli: log was empty</li>
<li>python38Packages.alot: log was empty</li>
<li>python38Packages.notmuch: log was empty</li>
<li>python38Packages.notmuch2: log was empty</li>
<li>python39Packages.notmuch: log was empty</li>
<li>python39Packages.notmuch2: log was empty</li>
  </ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>(python39Packages.alot): log was empty</li>
  </ul>
</details>
<details>
<summary>
12 packages built:
</summary>
<ul>
<li>aerc</li>
<li>astroid</li>
<li>dune-release</li>
<li>haskellPackages.notmuch</li>
<li>i3status-rust</li>
<li>keynav</li>
<li>mgba</li>
<li>muchsync</li>
<li>neomutt</li>
<li>notmuch</li>
<li>notmuch-addrlookup</li>
<li>tahoe-lafs</li>
</ul>
</details>

**Pull request merged**
