### PR TITLE
libchop: fix package

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
See #23418 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by vcunat — APPROVED** [review]

**Comment by rnhmjoj** [comment]
Merge?

**Comment by rnhmjoj** [comment]
@7c6f434c Can you port this to release-17.03 as well?

**Comment by vcunat** [comment]
Done.

**Comment by rnhmjoj** [comment]
Thanks!

**Pull request merged**
