### PR TITLE
Update to 0.2024.05.07.08.02.stable_02

### PR DESCRIPTION
**Pull request by soggywhale**
## Description of changes

2024.05.09 (v0.2024.05.07.08.02)

Bug fixes

   - Vim-related settings no longer appear in the Command Palette when editing with Vim keybindings is disabled

   - Warp's Input Editor now immediately reflects any changes to the Vim status bar settings

   - Fixed a bug when handling URLs with parentheses in notebooks and Warp AI

## Things done

changed the version.json for the linux version, I havent tested on the darwin version for MacOS.

I build it with ```nix-build -A warp-terminal``` and it worked on my machine. NixOS btw

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Reword the commits according to the contribution guidelines.

**Comment by annaleeleaves** [comment]
duplicate of https://github.com/NixOS/nixpkgs/pull/308877

also note that the darwin version was updated and not the hash. to update, should use the update script:
```
nix-shell -I nixpkgs=. maintainers/scripts/update.nix --argstr path warp-terminal
```

**Comment by soggywhale** [comment]
> Reword the commits according to the contribution guidelines.

I just read the guidelines and before I make other commits can you please elaborate on what can be improved on my commits ? do I need to be more precise ?

**Comment by DontEatOreo** [comment]
> I just read the guidelines and before I make other commits can you please elaborate on what can be improved on my commits ? do I need to be more precise ?

Please read this specific section here as well: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

```
(pkg-name): (from -> to | init at version | refactor | etc)

(Motivation for change. Link to release notes. Additional information.)
```

In your case, you should have had one commit, and it should have been named: `warp-terminal: 0.2024.04.16.08.02.stable_00 -> 0.2024.05.07.08.02.stable_02`

Since #308877 has already been merged, I will close this PR, wishing you luck on future PR's!

**Pull request closed without merging**
