### PR TITLE
buildbot: add www-react plugin

### PR DESCRIPTION
**Pull request by lopsided98**
###### Description of changes

https://github.com/buildbot/buildbot/releases/tag/v3.7.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Heads up: Buildbot is currently broken on staging-next because the tests fail due to usage of deprecated twisted things.

**Comment by lopsided98** [comment]
That looks like a problem with autobahn, not buildbot itself:
```
Traceback (most recent call last):
  File "/nix/store/mabzmwj5r6m0irifijxyvqrqxshwhqba-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/trial/runner.py", line 616, in loadPackage
    module = modinfo.load()
  File "/nix/store/mabzmwj5r6m0irifijxyvqrqxshwhqba-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/python/modules.py", line 388, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/nix/store/mabzmwj5r6m0irifijxyvqrqxshwhqba-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/python/reflect.py", line 297, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/nix/store/mabzmwj5r6m0irifijxyvqrqxshwhqba-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/python/reflect.py", line 238, in _importAndCheckStack
    return __import__(importName)
  File "/build/buildbot-3.6.1/buildbot/test/integration/test_virtual_builder.py", line 19, in <module>
    from buildbot.test.util.integration import RunMasterBase
  File "/build/buildbot-3.6.1/buildbot/test/util/integration.py", line 33, in <module>
    from buildbot.master import BuildMaster
  File "/build/buildbot-3.6.1/buildbot/master.py", line 55, in <module>
    from buildbot.www import service as wwwservice
  File "/build/buildbot-3.6.1/buildbot/www/service.py", line 46, in <module>
    from buildbot.www import ws
  File "/build/buildbot-3.6.1/buildbot/www/ws.py", line 19, in <module>
    from autobahn.twisted.resource import WebSocketResource
  File "/nix/store/p6ssdf941964ld5kcla0bxnhi44vy7vh-python3.10-autobahn-22.7.1/lib/python3.10/site-packages/autobahn/twisted/resource.py", line 36, in <module>
    from twisted.web.resource import NoResource
  File "/nix/store/mabzmwj5r6m0irifijxyvqrqxshwhqba-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/python/deprecate.py", line 471, in __getattribute__
    value = deprecatedAttribute.get()
  File "/nix/store/mabzmwj5r6m0irifijxyvqrqxshwhqba-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/python/deprecate.py", line 526, in get
    warn(message, DeprecationWarning, stacklevel=3)
builtins.DeprecationWarning: twisted.web.resource.NoResource was deprecated in Twisted 22.10.0: Use twisted.web.pages.notFound instead, which properly escapes HTML.
```

**Comment by Mic92** [comment]
buildbot fix: https://github.com/NixOS/nixpkgs/pull/205663

**Comment by Mic92** [comment]
Does this plugin work for you at all?
After enabling it I just get a blank page.

```diff
diff --git a/nixos/eve/modules/buildbot/master.py b/nixos/eve/modules/buildbot/master.py
index 0b366728..7acf19cc 100644
--- a/nixos/eve/modules/buildbot/master.py
+++ b/nixos/eve/modules/buildbot/master.py
@@ -148,7 +148,8 @@ def build_config() -> dict[str, Any]:
                 util.AnyControlEndpointMatcher(role="admins"),
             ],
         ),
-        "plugins": dict(waterfall_view={}, console_view={}, grid_view={}),                            
+        #"plugins": dict(waterfall_view={}, console_view={}, grid_view={}),                           
+        "plugins": dict(base_react={}),                                                               
```

**Pull request closed without merging**
