### PR TITLE
llvmPackages_latest: 14 -> 15

### PR DESCRIPTION
**Pull request by rrbutani**
###### Description of changes

Follow up to #194634 that targets `staging` and bumps `llvmPackages_latest`.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rrbutani** [comment]
@vcunat Can we have a [separate Hyrda jobset](https://github.com/NixOS/nixpkgs/pull/194634#issuecomment-1333385053) for this PR?

**Review by inclyc — APPROVED** [review]

**Comment by wegank** [comment]
I don't think there should be as many rebuilds, since mesa now points to llvmPackages_15 in staging. Could you push the commit again?

**Comment by vcunat** [comment]
Oh, I didn't notice my subscription here was because of a mention.

This doesn't cause that many rebuilds, but it's based on some staging commit for which we don't have binaries, so the jobset would be rebuilding everything (most likely).  What about basing this on current `staging-next`?  For example, this particular commit and eval as comparison base: https://hydra.nixos.org/eval/1789916#tabs-inputs

**Comment by vcunat** [comment]
Now `mesa` is using `llvmPackages_15` in nixpkgs master already.

**Comment by vcunat** [comment]
OfBorg still [showed](https://gist.github.com/5ec0c89b02c77fe611a423284164121f) around 4.7k rebuilds (total summed over all platforms).

Anyway, for fixing regressions I rebased on an OK `master` commit and here's Hydra's comparison: https://hydra.nixos.org/eval/1790712?compare=1790698  (`*-linux` only, at least for now)

**Comment by rrbutani** [comment]
It looks like a lot of the failures are coming [from `libclc`](https://hydra.nixos.org/build/209475622/nixlog/1); looks like some kind of LLVM version mismatch. I can take a look later today.

@vcunat is it okay if I hack on stuff on this branch for now? Not sure if the Hydra jobset was a one-off thing or if it'll trigger on updates to this PR.

**Comment by vcunat** [comment]
Yes, I meant for this branch to keep getting fixes on top, and Hydra picking them up.

**Comment by rrbutani** [comment]
[Current status](https://hydra.nixos.org/eval/1791006?compare=1790698): 35 new failures.

---

Pretty much all of these (excluding timeouts) look like they're coming [from `swift`](https://hydra.nixos.org/build/209420110) which looks like its failing [because of compiler lints](https://hydra.nixos.org/build/209420110/nixlog/1) (unused variables). It [doesn't look like the lint in question is new to LLVM 15](https://github.com/llvm/llvm-project/commit/cf49cae278b4e972cd2547d72f9ee7d9d69a3af4) so I'm not totally sure why we're only seeing this error now; will investigate.

**Comment by rrbutani** [comment]
@vcunat still waiting on Hydra to confirm but I _think_ all the new failures caused by this PR have been resolved.

How should we proceed from here? Should we have Hydra test `*-darwin` next or is it time to rebase and merge into `staging`, etc.

**Comment by vcunat** [comment]
OK, jobset reevaluated with full platform list.

**Comment by yu-re-ka** [comment]
@rrbutani may I push a fix for "swift-corelibs-libdispatch" on *-linux to your branch?

**Comment by rrbutani** [comment]
@yu-re-ka Yes, definitely; thank you!

I'm sorry I haven't had time to work on this recently; please feel free to make any changes you feel are appropriate.

**Comment by rrbutani** [comment]
Latest run: https://hydra.nixos.org/eval/1792520?compare=1792488#tabs-now-fail

It looks like all of the remaining (38) failures can be traced back to:
  - [`swiftPackages.XCTest` on `aarch64-darwin`](https://hydra.nixos.org/build/213746341) (seems to have timed out but there's no log output..)
  - [`swiftPackages.swift-unwrapped` on `x86_64-darwin`](https://hydra.nixos.org/build/213756623): log [here](https://hydra.nixos.org/build/213798518/nixlog/1), missing intrinsics for `__builtin_elementwise_add_sat`/`__builtin_elementwise_sub_sat`

**Comment by RaitoBezarius** [comment]
> Latest run: https://hydra.nixos.org/eval/1792520?compare=1792488#tabs-now-fail
> 
> It looks like all of the remaining (38) failures can be traced back to:
> 
> * [`swiftPackages.XCTest` on `aarch64-darwin`](https://hydra.nixos.org/build/213746341) (seems to have timed out but there's no log output..)
>   
>   * edit: when building locally this (or swift anyways) does fail to build
> * [`swiftPackages.swift-unwrapped` on `x86_64-darwin`](https://hydra.nixos.org/build/213756623): log [here](https://hydra.nixos.org/build/213798518/nixlog/1), missing intrinsics for `__builtin_elementwise_add_sat`/`__builtin_elementwise_sub_sat`

Is there an upstream issue on those missing intrinsics? We can keep LLVM14 for them I guess.

**Comment by rrbutani** [comment]
> Is there an upstream issue on those missing intrinsics? We can keep LLVM14 for them I guess.

I'm not sure the intrinsics are actually missing from LLVM15 or anything (still appear to be there in source, etc). I don't have a good understanding of how the swift build process works (the error messages actually do reference clang-14 but it's not obvious to me how/where that's coming from) and I've been dragging my feet on digging deeper.

I'll take another look tonight though.

**Comment by yu-re-ka** [comment]
> the error messages actually do reference clang-14 but it's not obvious to me how/where that's coming from

swift seems to build its own llvm/clang from the apple's llvm fork?

**Comment by RaitoBezarius** [comment]
@rrbutani I suggest cutting off here and get this PR into staging so we can have this in NixOS 23.05.

**Comment by yu-re-ka** [comment]
At this point I suggest pinning swift to LLVM 14

**Comment by RaitoBezarius** [comment]
This should target staging I think?

**Comment by rrbutani** [comment]
Apologies for the delay; I'm okay with pinning Swift to LLVM14 and moving on.

---

@gloaming @K900 There are changes to `libclc` (moved to within `llvmPackages`) and `spirv-llvm-translator` (misc fixes) within; can y'all verify that these are okay?

**Comment by vcunat** [comment]
FYI, swift on nixpkgs master [is now broken](https://hydra.nixos.org/build/215518955) for `*-linux` since glibc upgrade.

**Comment by K900** [comment]
Unfortunately the primary consumer of libclc in Mesa is Intel and I don't have the hardware to test it on, but as long as it builds, it should be fine.

**Comment by vcunat** [comment]
I could test Intel (Tiger Lake) if it doesn't need restart of X and someone tells me what to test.

**Comment by K900** [comment]
Basically anything involving OpenCL compute. Raytracing would also be nice but you don't have that.

**Comment by RaitoBezarius** [comment]
Swift pinned to LLVM14, testing the OpenCL stuff and merging into staging if it's okay with everyone?

**Comment by RaitoBezarius** [comment]
We decided to wait probably past 23.05 for this PR, it could be eventually backported if we justify security benefits or important fixes.

**Comment by rrbutani** [comment]
Assuming #229852 goes through I'll update this PR to bump the now pinned LLVM version in all the packages that successfully built with `llvmPackages_latest = llvmPackages_15`.

There are also a few extant changes to the LLVM package sets on this branch that we do actually want (and that should be applied to LLVM 16).

**Comment by reckenrode** [comment]
After this is merged, is it planned to bump llvmPackages from 11 to 15 on Linux?

**Comment by wegank** [comment]
By the way, the title is no longer accurate: `llvmPackages_latest` is already at 16.

**Comment by Et7f3** [comment]
The jobsets is still present and not disabled in [Hydra](https://hydra.nixos.org/project/nixpkgs)

**Comment by vcunat** [comment]
OK, thanks.  I cleaned that up now.  (disabled + hidden;  hydra doesn't really do deletions)

**Pull request closed without merging**
