### PR TITLE
Emacs lsp-mode: 20190926 -> 20191004

### PR DESCRIPTION
**Pull request by matthuszagh**
###### Motivation for this change
This fixes a problem with the master branch of Emacs.

[This](https://github.com/emacs-lsp/lsp-mode/pull/1052) is the relevant issue addressed.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by adisbladis** [comment]
While I appreciate the PR we usually (ever?) don't bump emacs packages one-by-one.

We have various auto-update scripts for the various emacs package sources in `pkgs/applications/editors/emacs-modes`, I recommend that you use `update-from-overlay` that will pull from https://github.com/nix-community/emacs-overlay and shouldn't take more than a minute to run.

**Comment by matthuszagh** [comment]
@adisbladis thanks for the info! I'll do that instead.

**Comment by matthuszagh** [comment]
@adisbladis, I've run the script. In order to avoid force-pushing, I didn't remove the first commit. Let me know if this is an issue and I'll fix it. For my own understanding, when is it ok to submit a PR to update emacs package recipes? Anytime someone wants an upstream change? Or, anytime there's a bug fix in one of the packages? Something else? Thanks.

**Comment by matthuszagh** [comment]
Closing this as it seems another PR has been merged which updates the packages.

**Pull request closed without merging**
