### PR TITLE
pazi: 0.2.0 -> 0.3.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fixing builds that @r-ryantm can't update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @bbigras 

```
$ nix path-info -Sh ./result
/nix/store/bl4jsq7xin3vbpdbvbx37qviharl4w37-pazi-0.2.0    28.7M
$ nix path-info -Sh ./result
/nix/store/kbr3c6gma7nzngn82g6x6c3zwlg88by1-pazi-0.3.0    28.6M
```
```
[1 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/66639
1 package were build:
pazi
```

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build pazi

**Comment by bbigras** [comment]
Looks fine for me. I tested with `nix-review pr 66639` on NixOS 19.09.git.4557b9f. :+1:

**Comment by mmahut** [comment]
@GrahamcOfBorg build pazi

**Comment by mmahut** [comment]
@GrahamcOfBorg build pazi

**Comment by bbigras** [comment]
thanks @jonringer

**Pull request merged**
