### PR TITLE
julia_17-bin: add support for aarch64-darwin

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
Add support for Julia on aarch64-darwin. Unfortunately the upstream test suite is failing even outside the nix build environment (https://github.com/JuliaLang/julia/issues/43614), so the test suite is disabled on aarch64-darwin until that is resolved.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ninjin** [comment]
First of all, thank you for picking up development towards macOS.

On Thu 30 Dec 2021, Samuel Ainsworth wrote:
> 
> Add support for Julia on aarch64-darwin. Unfortunately the upstream test suite is failing even outside the nix build environment (https://github.com/JuliaLang/julia/issues/43614), so the test suite is disabled on aarch64-darwin until that is resolved.

You will need to disable *individual* failing tests by patching them out for macOS – as we have done in the past for Linux [1]. Make sure to reference the upstream issue in the patch(es) so that other maintainers can more easily determine when the patches can safely be removed. Disabling the entire test suite is needlessly risky given the number of Julia-related failures we have seen on macOS in particular.

[1]: https://github.com/NixOS/nixpkgs/blob/release-21.11/pkgs/development/compilers/julia/patches/1.6-bin/0002-nix-Skip-tempname-test-broken-in-sandbox.patch

> - [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))

Once you have tests enabled again, do make sure to set `sandbox = true` as it catches plenty of issues.

The patch itself looks pretty clean. But are you not committing to becoming a maintainer? Neither myself or @7c6f434c have access to macOS for development, so I would really like to have someone reliable that can take on the heavy lifting for new releases and the much lighter duty of version bumps. Otherwise I fear that failures on macOS could delay merges of new Julia versions and version bumps if we commit to supporting it – akin to how the source-based v1.0.x and v1.5.0x are currently stuck in limbo.

Lastly, would it be possible to add macOS support for julia_16-bin to the PR as well? It feels odd if we would support macOS for Stable, but not the LTS.

**Comment by samuela** [comment]
Sure, I'd be happy to add myself as a maintainer if you'd like!

> You will need to disable *individual* failing tests by patching them out for macOS – as we have done in the past for Linux [1]. Make sure to reference the upstream issue in the patch(es) so that other maintainers can more easily determine when the patches can safely be removed. Disabling the entire test suite is needlessly risky given the number of Julia-related failures we have seen on macOS in particular.

This is not impossible, though it is quite onerous as the number of failing tests is non-trivial. I'll take a stab and see what I can come up with.

> Once you have tests enabled again, do make sure to set `sandbox = true` as it catches plenty of issues.

Ok, will do!

> Lastly, would it be possible to add macOS support for julia_16-bin to the PR as well? It feels odd if we would support macOS for Stable, but not the LTS.

I'd be happy to take a stab at aarch64-darwin support for julia_16-bin as well. In the spirit of keeping PRs small, would you mind if we did that in a separate PR though?

**Comment by ninjin** [comment]
On Thu 30 Dec 2021, Samuel Ainsworth wrote:
> 
> Sure, I'd be happy to add myself as a maintainer if you'd like!

Well, you have stuck around testing things out and patching for at least a year. I think you seem like a worthy candidate to handle macOS, no? =)

> > You will need to disable *individual* failing tests by patching them out for macOS – as we have done in the past for Linux [1]. Make sure to reference the upstream issue in the patch(es) so that other maintainers can more easily determine when the patches can safely be removed. Disabling the entire test suite is needlessly risky given the number of Julia-related failures we have seen on macOS in particular.
> 
> This is not impossible, though it is quite onerous as the number of failing tests is non-trivial. I'll take a stab and see what I can come up with.

Yeah, I know it *really* is not fun most of the time and hunting down these issues is about 90% of the time I spend packaging Julia. But as packagers we have to be good citizens and ensure that our end-users get the correct results when running Julia code or we are doing them a disservice by including broken software – a reasonable way to try to accomplish this is to pass the test suite. Likewise, when repackaging Julia we must ensure that end-users do not get the impression that Julia itself is unstable or we risk painting the upstream project in a bad light (this is one of the reasons why repackaging Julia is somewhat frowned upon in the community as several operating systems have repackaged Julia *really* poorly in the past). Lastly, there are really two kinds of bugs: those caused by our environment (Nix) and those that are upstream. For the former, it is our duty as packagers to produce patches for them. For the latter, we *must* report them and confirm that they are indeed upstream bugs as to be good citizens (while also of course determining that it is not our own environment that is causing them).

On the note of bugs, after writing the previous paragraph I spotted that aarch64-darwin is considered to have Tier 3 support by the upstream: “Tier 3: Julia may or may not build. If it does, it is unlikely to pass tests. Binaries may be available in some cases. When they are, they should be considered experimental. Ongoing support is dependent on community efforts.” Could @7c6f434c or someone else that is more senior than I in the Nixpkgs community weigh in on whether this is something that we flag to our end-users? References to how other packages have done this would be welcome. My current intuition tells we that it should probably be marked as broken until the upstream gets into a workable state.

> > Lastly, would it be possible to add macOS support for julia_16-bin to the PR as well? It feels odd if we would support macOS for Stable, but not the LTS.
> 
> I'd be happy to take a stab at aarch64-darwin support for julia_16-bin as well. In the spirit of keeping PRs small, would you mind if we did that in a separate PR though?

Just saw that aarch64-darwin is not supported for v1.6.x, so scratch that request. You are right, aarch64-darwin should absolutely be a separate PR.

**Comment by samuela** [comment]
Ah, I wasn't aware that aarch64-darwin was Tier 3 with limited support. They official official packages for aarch64-darwin on the [Downloads page](https://julialang.org/downloads/) which gave me a false sense of hope. That would certainly explain why things are broken upstream.

I'm also not sure how to best handle this. Should it be marked `broken`? Perhaps it's not even worth packaging it in nixpkgs until it becomes more stable?

**Comment by ninjin** [comment]
On Thu 30 Dec 2021, Samuel Ainsworth wrote:
> 
> Ah, I wasn't aware that aarch64-darwin was Tier 3 with limited support. They official official packages for aarch64-darwin on the [Downloads page](https://julialang.org/downloads/) which gave me a false sense of hope. That would certainly explain why things are broken upstream.

Yes, they honestly should mark those *much* clearer. Preferably close to the download link.

> I'm also not sure how to best handle this. Should it be marked `broken`? Perhaps it's not even worth packaging it in nixpkgs until it becomes more stable?

Hmm… Not an easy question. I would probably suggest holding the PR and – if you are up for it – engaging with the upstream to see if you can help them in any way. Even if you lack the cycles for that, I suspect that sooner or later it *will* stabilise anyway given the popularity of the platform.

**Comment by 7c6f434c** [comment]
It's sort of hard to say also because Julia pre-packages together too many fragile parts (most of which I don't even care about enough to be able to enumerate, as I only care only for the general-purpose base, not the linear-algebra integrations…) 

Not sure if we have a good comparison. LibreOffice is comparably a pain, but there are some rendering differences with upstream tests that we just shrug off as long as they are not too numerous. But you seem to care about fragile parts of Julia giving reasonable results… 

Nixpkgs is really bad at noticing things are not actually binary yes-or-no, so I doubt we have any reasonable way to mark up the status of Julia on Apple M1.

**Comment by samuela** [comment]
Yes, the correctness of Julia's numerics is of paramount importance to me, and a number of those tests are failing on aarch64-darwin independent of the nix build.

I'm going to switch this to a "draft" PR with the intention of revisiting once Julia actually passes its own test suite on aarch64-darwin. In the meantime I'm not sure that I can trust Julia running on aarch64-darwin even if I managed to get it packaged.

**Comment by 7c6f434c** [comment]
Fair enough

**Comment by ninjin** [comment]
Apologies for the slow response.

On Fri 31 Dec 2021, Samuel Ainsworth wrote:
> 
> Yes, the correctness of Julia's numerics is of paramount importance to me, and a number of those tests are failing on aarch64-darwin independent of the nix build.
> 
> I'm going to switch this to a "draft" PR with the intention of revisiting once Julia actually passes its own test suite on aarch64-darwin. In the meantime I'm not sure that I can trust Julia running on aarch64-darwin even if I managed to get it packaged.

I think as an outcome given the circumstances, this is fair. Hopefully it will only be a matter of a month or two at most until we see movement here as I suspect there will be an increasing pressure mounting on the upstream from the rather sizeable body of macOS users.

**Comment by siraben** [comment]
What's the status of this PR?

**Comment by samuela** [comment]
@siraben Upstream still hasn't moved aarch64-linux out of tier 3 AFAIK, so I think the PR is stalled until there's some update on that front. If someone would like to champion this PR regardless of the upstream status, I'd support it but I don't know that I personally would trust running Julia on aarch64-darwin until its support status is changed.

**Comment by siraben** [comment]
Given that Julia is a well-known package used for numerical computation, I think it's best to wait until upstream fixes tests on aarch64-darwin.

**Comment by NickCao** [comment]
We have dropped julia_17-bin, see https://github.com/NixOS/nixpkgs/pull/205584 for the current works.

**Pull request closed without merging**
