### PR TITLE
jprofiler: update icon hash

### LINKED ISSUE #293615: JProfiler build broken
```
error: hash mismatch in fixed-output derivation '/nix/store/nsyqyq4xqb5pp2dg7cifk29nhgnzdg8r-header-product-jprofiler-2x-24bc4d84bd2a4eb641a5c8531758ff7c.png.drv':
         specified: sha256-XUmuqhnNv7mZ3Gb4A0HLSlfiJd5xbCExVsw3hmXHeVE=
            got:    sha256-4T0j2ctHmgWOSCmFG2PZCLJS57nIa5MxmJBpMYzy9FI=
```

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
fixes https://github.com/NixOS/nixpkgs/issues/293615

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by pshirshov — APPROVED** [review]

**Review by wegank — APPROVED** [review]

**Review by freyacodes — APPROVED** [review]
The new hash seems to match

**Comment by dotlambda** [comment]
Can people upload the files and post the respective hash so we can figure out the difference?

**Comment by kirillrdy** [comment]
```
curl 'https://www.ej-technologies.com/assets/content/header-product-jprofiler@2x-24bc4d84bd2a4eb641a5c8531758ff7c.png' --output a.png
nix hash file a.png 
sha256-XUmuqhnNv7mZ3Gb4A0HLSlfiJd5xbCExVsw3hmXHeVE=

```
i've attached a.png 
a

**Comment by freyacodes** [comment]
I ran the same commands as @kirillrdy and got `sha256-4T0j2ctHmgWOSCmFG2PZCLJS57nIa5MxmJBpMYzy9FI=`, which I've attached.
a

**Comment by kirillrdy** [comment]
lol they are indeed different !

different size and 

```
cmp 312238035-3aed28ab-283e-4288-965e-5963edc5ccad.png 314213385-4f664872-ad2e-440d-93f4-15d076d1463c.png 
312238035-3aed28ab-283e-4288-965e-5963edc5ccad.png 314213385-4f664872-ad2e-440d-93f4-15d076d1463c.png differ: byte 36, line 3
```

didn't bother posting hexdump, since they are very different. 

CDN caching ?

**Comment by dotlambda** [comment]
@Mic92 Why was this merged? It will break things for other people.

**Comment by wegank** [comment]
Can we use a web.archive.org link instead?

**Comment by kirillrdy** [comment]
I just tried building master, and it worked, so maybe some sort of CDN cache ? or propagation delay

**Comment by Mic92** [comment]
> @Mic92 Why was this merged? It will break things for other people.

Doesn't seem to break on my machine.

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 293628` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jprofiler</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
@Mic92 between 6th of March and 20th of March people were getting different hashes. 

it works for me now, so unless someone says otherwise, I would just keep it as is

**Comment by dotlambda** [comment]
> > @Mic92 Why was this merged? It will break things for other people.
> 
> Doesn't seem to break on my machine.

You should read this thread.

**Pull request merged**
