### PR TITLE
libjack2: move headers to "dev" outputs

### PR DESCRIPTION
**Pull request by trofi**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
```diff
diff --git a/nixos/modules/programs/rust-motd.nix b/nixos/modules/programs/rust-motd.nix
index d5f1820ba75..9fb392365e6 100644
--- a/nixos/modules/programs/rust-motd.nix
+++ b/nixos/modules/programs/rust-motd.nix
@@ -82,7 +82,7 @@ in {
       timerConfig.OnCalendar = cfg.refreshInterval;
     };
     security.pam.services.sshd.text = mkIf cfg.enableMotdInSSHD (mkDefault (mkAfter ''
-      session optional ${pkgs.pam}/lib/security/pam_motd.so motd=/var/lib/rust-motd/motd
+      session optional ${lib.getLib pkgs.pam}/lib/security/pam_motd.so motd=/var/lib/rust-motd/motd
     ''));
     services.openssh.extraConfig = mkIf (cfg.settings ? last_login && cfg.settings.last_login != {}) ''
       PrintLastLog no
diff --git a/pkgs/applications/audio/csound/default.nix b/pkgs/applications/audio/csound/default.nix
index 6afddb467d0..d7a0357429a 100644
--- a/pkgs/applications/audio/csound/default.nix
+++ b/pkgs/applications/audio/csound/default.nix
@@ -32,7 +32,7 @@ stdenv.mkDerivation rec {
 
   cmakeFlags = [ "-DBUILD_CSOUND_AC=0" ] # fails to find Score.hpp
     ++ lib.optional stdenv.isDarwin "-DCS_FRAMEWORK_DEST=${placeholder "out"}/lib"
-    ++ lib.optional (libjack2 != null) "-DJACK_HEADER=${libjack2}/include/jack/jack.h";
+    ++ lib.optional (libjack2 != null) "-DJACK_HEADER=${lib.getDev libjack2}/include/jack/jack.h";
 
   nativeBuildInputs = [ cmake flex bison gettext ];
   buildInputs = [ libsndfile libsamplerate boost ]
diff --git a/pkgs/applications/audio/nootka/default.nix b/pkgs/applications/audio/nootka/default.nix
index 2b2372c6d87..3ce835138f6 100644
--- a/pkgs/applications/audio/nootka/default.nix
+++ b/pkgs/applications/audio/nootka/default.nix
@@ -28,7 +28,7 @@ stdenv.mkDerivation rec {
   ];
 
   cmakeFlags = [
-    "-DCMAKE_INCLUDE_PATH=${libjack2}/include/jack;${libpulseaudio.dev}/include/pulse"
+    "-DCMAKE_INCLUDE_PATH=${lib.getDev libjack2}/include/jack;${lib.getDev libpulseaudio}/include/pulse"
     "-DENABLE_JACK=ON"
     "-DENABLE_PULSEAUDIO=ON"
   ];
diff --git a/pkgs/applications/audio/polyphone/default.nix b/pkgs/applications/audio/polyphone/default.nix
index 568f3b6ba15..9ab81d2a5c4 100644
--- a/pkgs/applications/audio/polyphone/default.nix
+++ b/pkgs/applications/audio/polyphone/default.nix
@@ -36,7 +36,7 @@ mkDerivation rec {
   qmakeFlags = [
     "DEFINES+=USE_LOCAL_STK"
     "DEFINES+=USE_LOCAL_QCUSTOMPLOT"
-    "INCLUDEPATH+=${libjack2}/include/jack"
+    "INCLUDEPATH+=${lib.getDev libjack2}/include/jack"
   ];
 
   meta = with lib; {
diff --git a/pkgs/development/python-modules/python-pam/default.nix b/pkgs/development/python-modules/python-pam/default.nix
index 22dcf9e467b..d88e8ee0099 100644
--- a/pkgs/development/python-modules/python-pam/default.nix
+++ b/pkgs/development/python-modules/python-pam/default.nix
@@ -21,8 +21,8 @@ buildPythonPackage rec {
 
   postPatch = ''
     substituteInPlace src/pam/__internals.py \
-      --replace 'find_library("pam")' '"${pam}/lib/libpam.so"' \
-      --replace 'find_library("pam_misc")' '"${pam}/lib/libpam_misc.so"'
+      --replace 'find_library("pam")' '"${lib.getLib pam}/lib/libpam.so"' \
+      --replace 'find_library("pam_misc")' '"${lib.getLib pam}/lib/libpam_misc.so"'
   '';
 
   nativeBuildInputs = [
diff --git a/pkgs/misc/screensavers/xtrlock-pam/default.nix b/pkgs/misc/screensavers/xtrlock-pam/default.nix
index b87374df14d..244bb88c91b 100644
--- a/pkgs/misc/screensavers/xtrlock-pam/default.nix
+++ b/pkgs/misc/screensavers/xtrlock-pam/default.nix
@@ -15,7 +15,7 @@ stdenv.mkDerivation {
   buildInputs = [ python2 pam xorg.libX11 ];
 
   configurePhase = ''
-    substituteInPlace .config/options.py --replace /usr/include/security/pam_appl.h ${pam}/include/security/pam_appl.h
+    substituteInPlace .config/options.py --replace /usr/include/security/pam_appl.h ${lib.getDev pam}/include/security/pam_appl.h
     substituteInPlace src/xtrlock.c --replace system-local-login xscreensaver
     python configure --prefix=$out
   '';
diff --git a/pkgs/os-specific/linux/gradm/default.nix b/pkgs/os-specific/linux/gradm/default.nix
index cd99dfa5db8..fda17cfb70b 100644
--- a/pkgs/os-specific/linux/gradm/default.nix
+++ b/pkgs/os-specific/linux/gradm/default.nix
@@ -27,7 +27,7 @@ stdenv.mkDerivation rec {
   preBuild = ''
     substituteInPlace Makefile \
       --replace "/usr/bin/" "" \
-      --replace "/usr/include/security/pam_" "${pam}/include/security/pam_"
+      --replace "/usr/include/security/pam_" "${lib.getDev pam}/include/security/pam_"
 
     substituteInPlace gradm_defs.h \
       --replace "/sbin/grlearn" "$out/bin/grlearn" \
diff --git a/pkgs/servers/http/yaws/default.nix b/pkgs/servers/http/yaws/default.nix
index 7609c6ea545..82c046f9865 100644
--- a/pkgs/servers/http/yaws/default.nix
+++ b/pkgs/servers/http/yaws/default.nix
@@ -11,7 +11,7 @@ stdenv.mkDerivation rec {
     hash = "sha256-F1qhq0SEChWw/EBodXKWTqMNmGoTwP2JgkmfANUFD9I=";
   };
 
-  configureFlags = [ "--with-extrainclude=${pam}/include/security" ];
+  configureFlags = [ "--with-extrainclude=${lib.getDev pam}/include/security" ];
 
   nativeBuildInputs = [ autoreconfHook ];
   buildInputs = [ erlang pam perl ];
diff --git a/pkgs/tools/X11/xpra/default.nix b/pkgs/tools/X11/xpra/default.nix
index f70f2efa071..6afd9668722 100644
--- a/pkgs/tools/X11/xpra/default.nix
+++ b/pkgs/tools/X11/xpra/default.nix
@@ -85,7 +85,7 @@ in buildPythonApplication rec {
     ./fix-122159.patch # https://github.com/NixOS/nixpkgs/issues/122159
   ];
 
-  INCLUDE_DIRS = "${pam}/include";
+  INCLUDE_DIRS = "${lib.getDev pam}/include";
 
   nativeBuildInputs = [
     gobject-introspection
diff --git a/pkgs/tools/misc/timidity/default.nix b/pkgs/tools/misc/timidity/default.nix
index 1f0e68bb9c0..5a75fb52329 100644
--- a/pkgs/tools/misc/timidity/default.nix
+++ b/pkgs/tools/misc/timidity/default.nix
@@ -42,7 +42,7 @@ stdenv.mkDerivation rec {
     "AR=${stdenv.cc.targetPrefix}ar"
   ];
 
-  NIX_LDFLAGS = "-ljack -L${libjack2}/lib";
+  NIX_LDFLAGS = "-ljack -L${lib.getLib libjack2}/lib";
 
   instruments = fetchurl {
     url = "http://www.csee.umbc.edu/pub/midia/instruments.tar.gz";
```

**Comment by trofi** [comment]
Good catch! converting to draft.

**Comment by trofi** [comment]
Proposed `timidity` cleanup as https://github.com/NixOS/nixpkgs/pull/227789

**Comment by trofi** [comment]
Proposed `polyphone` cleanup as https://github.com/NixOS/nixpkgs/pull/227866

**Comment by trofi** [comment]
Proposed `csound` cleanup as https://github.com/NixOS/nixpkgs/pull/230329

**Comment by trofi** [comment]
Proposed `nootka` conversion as https://github.com/NixOS/nixpkgs/pull/230334

**Comment by trofi** [comment]
All the dependencies are sorted. Ready for review.

**Comment by vcunat** [comment]
It's generally good to glance at the `.pc` files when splitting outputs.  (I fixed this one now.)

**Pull request merged**
