### PR TITLE
mediathekview: 13.5.1 -> 13.7.0

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

Version bump. **When testing please make a backup of yout configuration as citing from the release page:**

**Erstellt vor dem Update zwingend ein Backup eurer Konfiguration! Ein Mischbetrieb von 13.7 und älteren Versionen ist ohne Verlust von Downloadhistorie und anderen Parametern NICHT möglich!!!**

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110833` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>mediathekview</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
> Version bump. **When testing please make a backup of yout configuration as citing from the release page:**

Does this require a changelog entry?

**Comment by dotlambda** [comment]
> > Version bump. **When testing please make a backup of yout configuration as citing from the release page:**
> 
> Does this require a changelog entry?

No, why would people ever downgrade their version?

**Review by dotlambda — APPROVED** [review]

**Comment by Moredread** [comment]
> 
> 
> > Version bump. **When testing please make a backup of yout configuration as citing from the release page:**
> 
> Does this require a changelog entry?

I guess in principal it would be nice to document that, but other packages like afaik syncthing and joplin had non-backwards compatible updates without changelog entries.

**Pull request merged**
