### PR TITLE
nixos/tests/keymap: improve keymap tests

### LINKED ISSUE #39330: nixos/tests/keymap: non-deterministic failures
## Issue description

The `keymap` tests fail non-deterministically on hydra, which frequently delays nixos channels.
Applies to master and 18.03. These failures have occured since at least December 2017. 
Some recent examples: 

- master: https://hydra.nixos.org/build/72687103
- 18.03: https://hydra.nixos.org/build/73077967, https://hydra.nixos.org/build/73075854

I believe this is caused by fragile test cases rather than a real problem with the keymaps. Will investigate and try to improve the tests.

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

Fix #39330.  Simplify tests, prevent timeouts and non-deterministic hydra failures.
Hopefully this will stabilize the tests on hydra - let's try and see.

Please backport to 18.03 because failing keymap tests have delayed the channels there as well.

###### Things done

- Simplify and redesign test logic: a single reader script now waits for all test characters to be typed (previously, a new reader script was started on the guest for each character)
- Improve host-guest synchronization to reduce waiting and timeout risks
- Xorg test: wait for xterm window to open (`waitForWindow()`)
- Xorg test: use `xdotool` to make sure xterm has focus (from #33719, thanks @srhb)
- Add some logging to help future debugging
- Verify that all 6 keymap tests pass locally, even when run in parallel with high CPU load (since I don't own a hydra simulator :grinning:)

###### Things that could be done later

- Flatten test data sets  - I chose to keep test data unchanged for now and have nix flatten it
- Add a standard synchronization mechanism to the test framework; having to sync by creating and waiting for marker files is a pain and error-prone, and everyone rolls their own...

---

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg test keymap.colemak

**Comment by adisbladis** [comment]
Works great here even under quite extreme load (load average 18) on my laptop using a https://ark.intel.com/products/95451.

Great work!

**Comment by srhb** [comment]
Looks excellent! Thanks!

**Comment by srhb** [comment]
People of the future, this is the first Hydra evaluation of nixos:release-18.03 with this commit:

https://hydra.nixos.org/eval/1451135

**Comment by srhb** [comment]
https://hydra.nixos.org/build/73238407/nixlog/13

Unfortunately, no dice. Shall I revert?

**Comment by xeji** [comment]
Oops. Please revert on 18.03 while I check it out. Looks like an issue with xdotool and the window manager, will probably have to modify a little for 18.03.

**Comment by srhb** [comment]
The tests are quite often impure. And uh, did someone rerun the tests or did I completely misread that there was an error? My old look shows it's fine now. Am I dreaming?

**Comment by srhb** [comment]
And I'm not sure it looked to me like a deterministic error. Could it be that the property in question does not exist if we ask _too fast_?

**Comment by xeji** [comment]
You're not dreaming, I saw the error too ... But I doubt someone restarted that job. No idea what happened.

> And I'm not sure it looked to me like a deterministic error. Could it be that the property in question does not exist if we ask too fast?

Maybe. The only thing I found in xdotool doc is that `windowactivate` may not work with all window managers.

**Comment by srhb** [comment]
@xeji OK, good! And yes, I saw that too, and I think what's going on is that it doesn't work _yet_ during whatever startup is happening. I can't imagine that the VM would be different between our systems and Hydras on that point.

**Comment by xeji** [comment]
Since I do `waitForWindow` before `xdotool`, the window is already there. But maybe the WM hasn't decorated and set all of the window's properties yet. I could wrap the `xdotool` call in a `waitUntilSucceeds()` loop.  Or use `windowfocus` alternative to `windowactivate`.

**Comment by srhb** [comment]
If `windowfocus` works regardless, that seems like the way to go!

**Comment by srhb** [comment]
(But if we can find a step to actually `waitUntilSucceeds` that makes this work, I think that's more than acceptable!)

**Comment by xeji** [comment]
Well the manpage says about `windowfocus`: 
>    Uses XSetInputFocus which may be ignored by some window managers or programs.

**Comment by srhb** [comment]
That should be testable in the by spawning another window with focus and switching, right?

**Comment by xeji** [comment]
Good idea, I'll do that. 

I haven't seen any case where the old test failed because of losing focus after the second xterm window was removed. Now there's only one fullscreen window. So I wonder if  the `xdotool` is just an extra failsafe that creates more trouble than it prevents...

**Comment by srhb** [comment]
Oh, good point. I forgot about that. In that case, feel free to nuke it! :-) I thought it would help us find a safe spot to start the test, but that may indeed not be the case at all.

**Comment by xeji** [comment]
Let's wait and see how the tests work run on master. I'll do some more experiments and then make an updated version.

**Comment by xeji** [comment]
Thanks again for your help!

**Pull request merged**
