### PR TITLE
virtualbox: Fix build issue due to open-watcom-bin

### PR DESCRIPTION
**Pull request by blitz**
###### Motivation for this change

We've already worked around failing stat() calls in the open-watcom-bin installer by running it in qemu-user. Turns out on some systems this workaround is also needed to run `wlib', the archiver of the Open Watcom toolchain.

This issue manifested itself in broken VirtualBox builds due to `/build/virtualbox/out/linux.amd64/dbgopt/obj/VBoxPcBios32/pci32.obj` not being found by `wlib'. Whether this issue manifests depends on the Linux kernel and sandboxing settings of the machine building the VirtualBox derivation.
 
We just wrap all Open Watcom binaries in qemu-user to avoid this now.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@flokli @tfc @B4dM4n @svanderburg

### CODE REVIEW

**Comment by blitz** [comment]
I've manually tested VirtualBox. It's happily running a Win10 guest.

**Comment by flokli** [comment]
@blitz do you have any idea on why I was still able to build it before this PR, but it fails on some machines?

**Comment by blitz** [comment]
> @blitz do you have any idea on why I was still able to build it before this PR, but it fails on some machines?

@flokli It depends on how the stat system call behaves. The EOVERFLOW case is triggered when certain fields in the legacy `struct stat` cannot represent values. For example, an inode number that doesn't fit in a 16-bit value triggers `EOVERFLOW` for the legacy stat system call: https://elixir.bootlin.com/linux/v5.4.39/source/fs/stat.c#L226 And 16-bit inode numbers seem ridiculously small these days...

There are other paths that trigger EOVERFLOW for stat, but the outcome is the same.

**Comment by flokli** [comment]
Urgh, okay. Thanks for digging down to this!

**Pull request merged**
