### PR TITLE
[gnome] Pantheon: drop dark style preference patch part 2

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

For evince, this is a follow-up of #163828, the previous patch actually still applies but makes no sense to keep it anymore.

For https://github.com/NixOS/nixpkgs/pull/160343#issuecomment-1047582728, I think I will just disable the contract (and ask users to fork [worldofpeace/extra-elementary-contracts](https://github.com/worldofpeace/extra-elementary-contracts) and make one for blueman??? :thinking: ), anyway I expect it is also broken in elementary OS 7...

Also sneak in a nitpick for mutter.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux (evince)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/164705/checks?check_run_id=5601005009 :thinking: 

屏幕截图 2022-03-18 22 02 54

@ofborg build graphviz

**Comment by bobby285271** [comment]
graphviz succeed again...
@ofborg build pantheon.evince

**Comment by bobby285271** [comment]
Looks like some darwin issue (okay this is going to be out-of-scope of this PR)...

@ofborg build glib

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/164705/checks?check_run_id=5602227858
Seems to build fine this time :see_no_evil:

**Comment by bobby285271** [comment]
@ofborg build glib

**Pull request merged**
