### PR TITLE
mesa: 23.3.4 -> 24.0.0

### PR DESCRIPTION
**Pull request by jalil-salame**
## Description of changes

Updated Mesa to 24.0.0

https://docs.mesa3d.org/relnotes/24.0.0.html

Removed backported patches, they have been applied upstream.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
I drafted this, as normally we follow the opening paragraph
> People who are concerned with stability and reliability should stick with a previous release or wait for Mesa 24.0.1.

(and we rarely merge mesa updates directly to `master`)

**Comment by jalil-salame** [comment]
> I drafted this, as normally we follow the opening paragraph
> 
> > People who are concerned with stability and reliability should stick with a previous release or wait for Mesa 24.0.1.

Sorry about that, I just skimmed the changelog. I'm having driver issues so I was a bit overexcited.

At least the PR is here now so nobody else will do this c:.

> (and we rarely merge mesa updates directly to `master`)

Should I rebase on top of `staging` or close the PR and wait for 24.0.1?

**Comment by vcunat** [comment]
Oh, a trivial conflict.  BTW, I don't expect we want to keep those patch files.

**Comment by jalil-salame** [comment]
> Oh, a trivial conflict. BTW, I don't expect we want to keep those patch files.

Fixed c: Thanks for the patience!

**Comment by returntoreality** [comment]
24.0.1 was just released

**Review by LunNova — COMMENTED** [review]
The codec selection flag could be changed to use video-codecs=all which was added in 24

**Comment by jalil-salame** [comment]
> 24.0.1 was just released

I am updating this PR, might take a while because it needs to recompile GCC.

**Comment by vcunat** [comment]
I believe this is sufficient to base and test on a merge-base of master and staging.

**Comment by K900** [comment]
There are more potential quirks here: at the very least, we want to build NVK now, which makes Rust (and a bunch of crates) a proper dependency, and then there's potential implications for musl and cross builds that I'm still looking into.

**Comment by jalil-salame** [comment]
Superseded by #289051

**Pull request closed without merging**
