### PR TITLE
grub2: 2.04-rc1 -> 2.04

### PR DESCRIPTION
**Pull request by herrwiese**
###### Motivation for this change

Stable release, would look nice to have this in 19.09 instead of an RC.

`nix-build -A nixosTests.installer` succeeded (seemed to be the most relevant test case for GRUB); my machine also came up again.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @volth

### CODE REVIEW

**Comment by volth** [comment]
Related https://github.com/NixOS/nixpkgs/issues/61718

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (1 fails, but broken on master)
diff LGTM
binaries seem to work

```
[21 built (1 failed), 258 copied (924.7 MiB), 227.5 MiB DL]
error: build of '/nix/store/xlplllqg0yngg837ccwcr6rg90vsfzrx-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/67622
1 package failed to build:
deepin.deepin-wm

19 package were build:
deepin.dde-api deepin.dde-control-center deepin.dde-daemon deepin.dde-dock deepin.dde-file-manager deepin.dde-launcher deepin.dde-session-ui deepin.deepin-desktop-base deepin.deepin-desktop-schemas deepin.deepin-metacity deepin.deepin-mutter deepin.deepin-wallpapers grub2 grub2_efi grub2_light grub2_pvgrub_image grub2_xen os-prober woeusb
```

**Comment by disassembler** [comment]
@GrahamcOfBorg test installer

**Comment by disassembler** [comment]
rebased. installer test is passing, so merging!

**Pull request merged**
