### PR TITLE
cemu-ti: platform changes

### PR DESCRIPTION
**Pull request by utopiatopia**
CEmu has aarch64 binaries for MacOS and Linux. No reason to disallow it here.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
> CEmu has aarch64 binaries for MacOS and Linux.

So maybe also add aarch64-darwin?

**Comment by myclevorname** [comment]
> However, I’ve installed just Nix on MacOS now, and cemu-ti fails to build (MacOS). I’m not entirely sure if it’s related to aarch64 or it being unable to build with Nix.
Can you send the logs? I do not have a Mac to test it on.

**Comment by utopiatopia** [comment]
> Can you send the logs?

https://gist.github.com/utopiatopia/6deebf18f8a69a486c945c2dedf4d9ed

**Comment by myclevorname** [comment]
I think we should add aarch64-linux, but mark every other architecture as broken for now. I don't know exactly when CEmu would support Qt6.8, but I suspect it won't support Qt 6.8 for a few months.

**Review by myclevorname — APPROVED** [review]
LGTM

**Comment by kirillrdy** [comment]
@utopiatopia can you remove this commit "[Merge branch 'master' into cemu-ti-arch-update](https://github.com/NixOS/nixpkgs/pull/356874/commits/c66eaef307def663c65f1b991104783add13501f)"

**Review by myclevorname — APPROVED** [review]

**Pull request merged**
