### PR TITLE
 jetbrains: 2023.1.1 → 2023.1.2 

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

Ran and tested InteliJ IDEA

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dritter** [comment]
The jetbrains.gateway (https://download.jetbrains.com/idea/gateway/JetBrainsGateway-231.8770.69.tar.gz) seems to be 404..

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 232308` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>jetbrains.gateway</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>bluej</li>
    <li>greenfoot</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.jdk</li>
    <li>jetbrains.jdk.debug</li>
    <li>jetbrains.mps</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Comment by fabianhjr** [comment]
Dropping the gateway change

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 232308` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>bluej</li>
    <li>greenfoot</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.jdk</li>
    <li>jetbrains.jdk.debug</li>
    <li>jetbrains.mps</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Review by dritter — APPROVED** [review]

**Comment by dritter** [comment]
Btw. I just saw there are updates for datagrip, gateway (2023.1.2), phpstorm, Rider and webstorm available as well.

**Comment by fabianhjr** [comment]
gateway update script still broken / 404, included more of the updates.

**Comment by dritter** [comment]
Btw. Gateway 2023.1.2 should work. The correct link is https://download-cdn.jetbrains.com/idea/gateway/JetBrainsGateway-2023.1.2.tar.gz .

And RubyMine has also an update available.

**Comment by fabianhjr** [comment]
Included RubyMine, script still has issues with Gateway

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 232308` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>bluej</li>
    <li>greenfoot</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.jdk</li>
    <li>jetbrains.jdk.debug</li>
    <li>jetbrains.mps</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 232308` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>bluej</li>
    <li>greenfoot</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.jdk</li>
    <li>jetbrains.jdk.debug</li>
    <li>jetbrains.mps</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Pull request merged**
