### PR TITLE
More vulkan updates

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

Fixes vulkan-tools and others. Also, decouples the update cycles of everything but the loader+headers, as upstream already does.

glslang and spirv-tools updates go into staging: https://github.com/NixOS/nixpkgs/pull/229274

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Result of `nixpkgs-review pr 229273` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vulkan-tools-lunarg</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>corectrl</li>
    <li>goverlay</li>
    <li>goverlay.man</li>
    <li>gpu-viewer</li>
    <li>hw-probe</li>
    <li>libsForQt5.kinfocenter</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>lutris-unwrapped.dist</li>
    <li>qmplay2</li>
    <li>vkdt</li>
    <li>vkdt-wayland</li>
    <li>vulkan-extension-layer</li>
    <li>vulkan-tools</li>
    <li>vulkan-validation-layers</li>
    <li>vulkan-validation-layers.headers</li>
  </ul>
</details>

**Comment by K900** [comment]
vulkan-tools-lunarg is still broken with latest validation-layers commit, should probably let upstream fix it.

**Comment by vcunat** [comment]
The staging-next merge still dropped `vulkan-tools-lunarg` package (fails to eval).

**Comment by vcunat** [comment]
But it's the only one: https://hydra.nixos.org/eval/1794433?compare=1794412#tabs-removed

**Comment by K900** [comment]
It's actually broken with the latest validation layers version.

**Comment by expipiplus1** [comment]
Thank you for tidying the update coupling!

**Comment by dev-null-undefined** [comment]
I think this PR should be reverted since the vulkan-validation-layer does not build after the hash update probably because of `spirv-headers` and `spirv-tools` still not having updated to version `1.3.249` and it does not seem like that will happen any time soon.

@vcunat 
@K900

**Comment by K900** [comment]
`vulkan-validation-layers` definitely builds for me on this PR.

**Comment by K900** [comment]
Hmm, that looks like a mismerge. Let me check.

**Comment by dev-null-undefined** [comment]
Fixed in #229749

(Just for linking and history keeping)

**Pull request merged**
