### PR TITLE
make-desktopitem: make genericName optional

### LINKED ISSUE #20624: makeDesktopItem incorrectly requires GenericName
## Issue description

[The spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) says that Desktop Entries are not required to have a GenericName key. However, the handy [makeDesktopItem](https://github.com/NixOS/nixpkgs/blob/a80cacd3ec8582bf3236fcd5031b0715358b3c82/pkgs/build-support/make-desktopitem/default.nix) function requires that it be specified. 

## Technical details

* System: NixOS: `17.03.git.322f5e5 (Gorilla)`
* Nix version:  `nix-env (Nix) 1.11.4`
* Nixpkgs version: `"16.09.877.5b08a40"`

### PR DESCRIPTION
**Pull request by lverns**
###### Motivation for this change

There are several changes in this PR. 

1. Closes #20624
1. Several entries will default to being absent (rather than empty string) when none is passed in.
1. There is no longer an extra newline at the end of the file when no extra entries are passed in.
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"` **I have not done this. It looks like this function gets used in almost 80 different files, so it could be a fairly big rebuild.**
- [ ]  **N/A** Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg eval

**Comment by peterhoeg** [comment]
Is there any particular reason why we are creating the .desktop file under share/applications instead of just in the root of the derivation? The .desktop are always copied into place later as well as processed again later to fix up paths so there isn't much point in having to dig it out from a directory structure several directories deep.

**Comment by lverns** [comment]
@peterhoeg I don't know what the reason for that decision was originally, but I agree that putting it in the root would make more sense.

Unfortunately, that would be a breaking change.

Doing `grep makeDesktopItem -R pkgs -l - | wc -l` on master right now reveals that this function is used in 95 files. All of these occurrences would have to be updated to pull from the new location, but I don't think that sounds like too much work.

Would it make sense to change that in this PR since this PR will cause a rebuild anyway, or would it be better to have such a change in a different PR,  since it really is a different sort of change?

**Comment by peterhoeg** [comment]
I think it makes sense to do it in 2 different PRs but then simply merge them at the same time. ```sed``` should be able to handle 95% of the changes.

**Comment by lverns** [comment]
> I think it makes sense to do it in 2 different PRs but then simply merge them at the same time.

Would the second branch be based on master or on this branch?

If master, then there will be merge conflicts in `pkgs/build-support/make-desktopitem/default.nix` once this PR is merged.

If this branch, then the diff is going to be a bit deceiving until this PR goes through. Also, this branch is so old that we probably can't change all those files and expect to merge back into master without conflict.

My preference: merge this PR and then make a new branch off master to make the `${out}/share/applications` -> `${out}` change.

**Review by samueldr — APPROVED** [review]

**Pull request merged**
