### PR TITLE
perlPackages.CpanelJSONXS: 4.31 -> 4.36

### PR DESCRIPTION
**Pull request by mweinelt**
https://metacpan.org/release/RURBAN/Cpanel-JSON-XS-4.36/source/Changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
- https://github.com/rurban/Cpanel-JSON-XS/issues/208

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.CpanelJSONXS

**Review by stigtsp — APPROVED** [review]
LGTM

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 221794` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>blueberry</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-python</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapp</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>convos</li>
    <li>fgallery</li>
    <li>hw-probe</li>
    <li>hypnotix</li>
    <li>inxi</li>
    <li>perl534Packages.BSONXS</li>
    <li>perl534Packages.Catmandu</li>
    <li>perl534Packages.CpanelJSONXS</li>
    <li>perl534Packages.GraphicsColor</li>
    <li>perl534Packages.MojoliciousPluginStatus</li>
    <li>perl534Packages.MongoDB</li>
    <li>perl534Packages.MooseXStorage</li>
    <li>perl534Packages.MooseXStorageFormatJSONpm</li>
    <li>perl536Packages.BSONXS</li>
    <li>perl536Packages.Catmandu</li>
    <li>perl536Packages.CpanelJSONXS</li>
    <li>perl536Packages.GraphicsColor</li>
    <li>perl536Packages.MojoliciousPluginStatus</li>
    <li>perl536Packages.MongoDB</li>
    <li>perl536Packages.MooseXStorage</li>
    <li>perl536Packages.MooseXStorageFormatJSONpm</li>
    <li>python310Packages.xapp</li>
    <li>python311Packages.xapp</li>
    <li>sticky</li>
    <li>timeshift</li>
    <li>timeshift-minimal</li>
    <li>timeshift-unwrapped</li>
    <li>xed-editor</li>
    <li>xplayer</li>
  </ul>
</details>

**Pull request merged**
