### PR TITLE
watchexec: darwin support

### PR DESCRIPTION
**Pull request by nikivdev**
###### Motivation for this change

`watchexec` wasn't building correctly on macOS. With help of @LnL7 it does.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Anyone knows what I should to to remove the other 3 commits not made by me?

**Comment by Mic92** [comment]
You probably should want to create a new feature branch that only contains the `watchexec` update instead of having multiple unrelated changes for review.

**Comment by Mic92** [comment]
```
git remote add upstream https://github.com/NixOS/nixpkgs
git fetch upstream master
git checkout upstream/master
git checkout -b watchexec
git cherry-pick a999c36b18a07a780f651d696c14ab701faf3d35
git push origin watchexec
```

And then create a new pull request from the watchexec branch.

**Comment by nikitavoloboev** [comment]
Thank you @Mic92. New pr is #46313

**Pull request closed without merging**
