### PR TITLE
mopidy-iris: 3.14.2 -> 3.16.3

### PR DESCRIPTION
**Pull request by rvolosatovs**
###### Motivation for this change
Upstream update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build mopidy-iris

**Comment by yegortimoshenko** [comment]
mopidy-iris now depends on Tornado, I've added it to build inputs along with a small patch that makes it build properly.

**Comment by yegortimoshenko** [comment]
Thanks :-)

**Comment by rvolosatovs** [comment]
https://github.com/NixOS/nixpkgs/pull/39011#issuecomment-381749252
It built and worked perfectly fine for me without the dependency, what did I miss?

**Comment by yegortimoshenko** [comment]
Hm, strange. It didn't build for me without Tornado, and upstream now lists it in `setup.py`: https://github.com/jaedb/Iris/blob/master/setup.py#L30

**Pull request merged**
