### PR TITLE
Make scala versions explicit

### LINKED ISSUE #13620: Scala packages are not versioned deterministically
## Basic info

To make sure that we are on the same page:

* Nix version: https://github.com/NixOS/nixpkgs/commit/ba0582670796acdeeb9ab0001a7edd0b08290d4f
* Nixpkgs version: https://github.com/NixOS/nixpkgs/commit/ba0582670796acdeeb9ab0001a7edd0b08290d4f

## Describe your issue here

I can't compile code using specific versions of Scala.

### Expected result

I can specify buildInputs or package dependencies for specific versions of Scala

### Actual result

I can only reference the current stable release

### PR DESCRIPTION
**Pull request by trane**
Previously the non-determinism of a particular Scala package was an
issue since `scala` pointed to the most recent stable release (which can
change at any time). Likewise, Scala 2.9, 2.10 were also pointing to
some recent stable version of their respective semantic version.

This commit makes the versions explicit, easily gaining that determinism
(much like how the Haskell and Erlang packages are done). For backwards
compatibility the old package pointers of `scala`, `scala_2_9`, and
`scala_2_10` continue to work as they used to.

Fixes #13620

### CODE REVIEW

**Comment by copumpkin** [comment]
Putting the minor version into the filename seems annoying. Now when they release a new minor version, we need to rename the file? I don't see that buying much.

**Comment by trane** [comment]
@copumpkin you don't rename the file, you create a new file - just like is done in other packages like  Erlang or Haskell.

**Comment by copumpkin** [comment]
We generally don't preserve old versions of things though, if we can avoid it. So it doesn't make much sense to me to leave 2.11.7 around if 2.11.8 was released.

**Comment by zimbatm** [comment]
Do they usually break back-compat on tiny releases ?

**Comment by trane** [comment]
There are all sorts of things that can change between releases that are unintended. Further, making explicit what dependencies and version of dependencies one has seems more inline with the nix philosophy.

What if I'm testing builds across multiple environments and some environments have the latest channel and others don't? Regardless of the outcome of the build (being successful or not), I am not testing the same thing everywhere -- to me, this violates one of the core assertions and benefits of running nix.

So, the motivation of this PR is to better align the Scala packages with that explicit, deterministic dependency and versioning that nix provides. Further, to maintain the status-quo (for those that don't want to use the benefits of explicit versioned packages) I've continued the ability to utilize the symlink-like `scalaX` packages.

When a new version of Scala is released the symlink-esque pointers can be updated and no one's code has to change. However, for those of us that want to have tighter guarantees about what version is being used across environments we can have that too!

I'm completely open to an alternative solution to the package versioning problem than multiple files (I stole this idea from the Haskell and Erlang folks). However, for many (including me) the status-quo is not in-line with making dependencies explicit and deterministic - which means I need to provide my own nix channels internally to work-around this problem.

**Comment by zimbatm** [comment]
If you don't use the same checkout of nixpkgs then by definition you're not testing the same thing everywhere. There are a lot of things changing here besides scala that your program might depend on.
The issue right now is that we have an easy mechanism to create per-project shell.nix files, but it doesn't tie to a specific nixpkgs checkout, it would be nice to have that for sure. Note that even if the user is on nixos-15.03 or something, you can still install software from another channel so that's fine.

That being said, I think we *should* package more versions of Scala. There is just a tension not to include too much things if possible.

Usually for libraries we try to only retain the latest stable version or two depending on b/c breakage. For languages it seems like breakage might be more subtle and there is a desire to test the software against different versions. I don't know Scalas' ecosystem enough to determine how useful it is to test against minor version changes or not.

**Comment by trane** [comment]
@zimbatm absolutely if channels aren't the same between environments then you aren't testing the same thing - the per-project shell.nix is a much better example of the issue.

To go further with your comment about channels, by making minor versions explicit, we are able to let the rest of the nixpkgs ecosystem move as it will while maintaining specific packages at the version we intend them to be.

As an alternative example: TravisCI allows me to give the exact version to test again for backward compatibility purposes (even between x.y.z releases). I cannot do a similar thing with builders I provision with nix without maintaining my own internal nix channels.

I appreciate the desire to limit the number of packages that get built and the ease at staying with the most current Scala stable. But, I think there is enough precedent in other packages (Haskell, Erlang) to allow for control at the tiny version level - especially since this doesn't break existing code or usage expectations.

**Comment by zimbatm** [comment]
I would say :+1: given the precedence in other languages (ruby too)

**Comment by copumpkin** [comment]
I'm actually :-1: because I don't think it is actually the "nix way, or at least not what most of nixpkgs does.

In practice, we actively try to discourage keeping multiple (i.e., precise) versions of things around because it creates a combinatorial explosion of configurations to test. Thus in practice, we try to trim down proliferating versions of things (see various attempts at cutting down the number of parallel versions of clang/LLVM, ruby, and so on) unless they're explicitly needed by particular packages that we also want.

So I don't think I've really seen the situation you describe, where people try to name their package files after very specific versions. In practice, most of the commits you see made to nixpkgs are someone making a very small bump to a version and its sha256, without changing the rest of the expression. I don't see people renaming files, creating new files for new versions, or that. And when they do, people try to discourage it. People create top-level aliases for e.g.,  `llvm` that expand to `llvm_37` because if possible we try to keep people not fixed to a particular version. The fewer packages are locked onto a version the easier the mass of packages is to test. Note that what I'm saying is different from version lockdown within a particular git commit, which obviously arises naturally from how Nix works. Instead, I'm saying that by and large, nixpkgs does not lock versions across nixpkgs commits, which is quite different. I see .nix filenames in nixpkgs as treading on the latter situation and thus deviating from nixpkgs common practice, and very precise derivation names (i.e., you end up with `/nix/store/somelonghash-llvm-3.7.1/`) as being in line with it.

Does that make sense? I feel like I'm doing a poor job at communicating a fairly subtle distinction. Perhaps more experienced Nix folks like @domenkozar or @vcunat can chime in to clarify (or correct me if I'm wrong).

**Comment by jagajaga** [comment]
Sorry if I repeat someone but we usually keep several versions of the exact package only if another package needs exact that version.
Like `foo` needs `bar1.0` and there is also `bar2.0` that is used in all other pkgs. Then we will have `bar1.0` and `bar2.0` because we need `foo`. But if there are no pkgs that we want to support with exact version of `bar` then we delete the earliest version. Sorry if I'm wrong but I thing that is the policy.

**Comment by zimbatm** [comment]
Languages are a bit different because developers want to be able to test their code against different versions of the language, so we keep more versions of them than the usual libraries and programs. That being said most of them only include minor releases. Between all the most common languages, only ocaml and haskell seem to be the outliers and also include various tiny releases (and ruby has a few tiny releases but should probably squashed back to minors).

**Comment by trane** [comment]
The only reason I see left to merge this is that testing multiple versions of compilers on the same host without needing to do overrides. Not much of a reason, imo.

I see that for my TravisCI example, that could be done with different nix profiles utilizing pinned channels.

I think it makes sense to add a `scala_2_11` link, though. Thoughts?

**Comment by copumpkin** [comment]
@trane definitely think that at that granularity it makes sense. I'd just avoid going down to a deeper level.

**Comment by trane** [comment]
I guess there is already a `scala_2_11` name, but the file is the `default.nix` file. I think it's safe to say that the `default.nix` file can change to `2.11.nix` (especially with the pending release of 2.12) and we already have the ease of just installing `pkgs.scala` for whatever the most recent version of Scala is (major or minor).

If we have agreement on that I can push up a new commit with `default.nix -> 2.11.nix`.

**Comment by trane** [comment]
I'll close this PR since it seems like things can be resolved outside of this issue.

**Pull request closed without merging**
