### PR TITLE
Moved pyradio from radio/ into audio/ folder

### PR DESCRIPTION
**Pull request by j-steinbach**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/137905

In the end I only moved the *pyradio* package, as it is the only "end-user-application" package and clearly misplaced. 
As ordering and categorizing packages is opinionated, I didn't want to do too much. The *audio* folder also is very broad, but again, see the previous sentence.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

----

## Important

This is the first time I am doing a pull request *"ever"*. I am doing this based on [this guide](https://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/) which @Artturin recommended to me. I am getting a bit overwhelmed with the checklist, so I am just going to blindly create the pull request and hope for the best. Sorry about that.

### CODE REVIEW

**Comment by Artturin** [comment]
The pyradio entry in pkgs/top-level/all-packages.nix has to be changed to point to the new path

**Comment by j-steinbach** [comment]
Thanks for replying! I didn't know about the all-packages.nix file -- TIL. I am going to change it now, but again, this might take some time.

Can you also tell me the command with which I am supposed to build/test this?

Sorry for the troubles.

**Comment by Artturin** [comment]
```
nix-build -A pyradio
```

**Comment by j-steinbach** [comment]
> ```
> nix-build -A pyradio
> ```

```nix
$ nix-build -A pyradio
/nix/store/sx426mxsvj05fdzf6xyayf3ki912xvis-pyradio-0.8.9.9
```

That means it builds, and that I already built it, and it is already in the store?

**Comment by Artturin** [comment]
you only changed the path to the file and did no edit the expression therefore there was no need to rebuild it

**Comment by j-steinbach** [comment]
Thanks for the help and explanations!

**Comment by Artturin** [comment]
fixup the commits with rebase https://git-rebase.io/#fixup

and reword the commit to follow the commit format in [contributing.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes)

```
git rebase -i HEAD~2
```

change them to 
```
reword commithash commitname
fixup commithash commitname
```

**Comment by j-steinbach** [comment]
I think I changed the commit messages correctly, but now I get

```git
error: failed to push some refs to 'github.com:j-steinbach/nixpkgs.git'
hint: Updates were rejected because the tip of your current branch is behind
```

**Comment by Artturin** [comment]
`git push --force`

**Comment by j-steinbach** [comment]
Tbh, this is pretty stressful for only changing some lines of text :octocat:

**Comment by Artturin** [comment]
Dont worry its your first pr, in the future you'll know these things.
We just want to keep the commit history clean

**Comment by j-steinbach** [comment]
No worries, I totally understand :+1: Just that I didn't expect the "learning" overhead to be this big. On the other hand.. the knowledge will definitely be useful in the future.

**Pull request merged**
