### PR TITLE
Wine update

### PR DESCRIPTION
**Pull request by avnik**
###### Motivation for this change

Update wine unstable/staging to recent versions.
Unbreak build, broken by samba3 security assertion

Note: only 32bit build tested

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Thank you!

**Comment by deedrah** [comment]
Could someone cherry pick `wine: replace samba3 with samba4` into nixos-17.09. Without it, the `wineStaging` package is not even building on hydra.

**Comment by avnik** [comment]
@deedrah Don't sure, if wineStaging costs to build on hydra for stable. It updates biweekly (usually) and only in master. Not sure if staging build from month or two ago can be useful.

**Comment by grahamc** [comment]
I backported the samba3/samba4 bit to 17.09: eb085385ba2b5a854b0f9262f70fd0f4dad40196

**Pull request merged**
