### PR TITLE
lmstudio: 0.2.22 -> 0.2.24

### PR DESCRIPTION
**Pull request by cig0**
## Description of changes

- Upstream patch update (0.2.24)
- Updated download links
- Updated maintainers list

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](.))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eeedean** [comment]
We are very close!

Please do squash the 3 separate Commits [lmstudio: 0.2.22 -> 0.2.24](https://github.com/NixOS/nixpkgs/pull/314992/commits/c502cbd0e883e138f5a0d347c44d01e8ada28679), [lmstudio: 0.2.22 -> 0.2.24](https://github.com/NixOS/nixpkgs/pull/314992/commits/7383fdc95014d71555c4922625086c7b7deda1c8), [lmstudio: 0.2.22 -> 0.2.24](https://github.com/NixOS/nixpkgs/pull/314992/commits/84f31b95858289970ff9a539b23f13135242b848) into a single one. You may and should do these changes in a single commit, because they wouldn't work isolated. 

Also ofborg catched one issue: <pre>error: undefined variable 'cig0'</pre>

<details> 
  <summary>you must add a commit first, to fix that</summary>
   <a href="https://github.com/NixOS/nixpkgs/pull/310914/commits/f8c7960cf2fadb08749ec90f4bf30baaa188f7c1">maintainers: add cig0</a> should only add your handle to <a href="https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix">maintainers/maintainer-list.nix</a>. Be aware, that this list must be ordered alphabetically, or one of the checks will fail.
</details>



---

> While cleaning up this mess, I noticed that the folks at LM Studio changed again the format of the download link for the Mac version, removing the revision identifier:
> 
> From https://github.com/NixOS/nixpkgs/pull/310914/files#diff-5932e72431b8e295a889e7c4defdd8aa02221a7f1103665b696e3b344dea3fb9L13 to `https://releases.lmstudio.ai/mac/arm64/0.2.24/latest/LM-Studio-0.2.24-arm64.dmg`.
> 
> We no longer need to add the new variable (until they change the URL again, I guess!).

As the `latest` in the URL does rub me a little wrong, I'll write to lmstudio again, just to be sure, that this link actually will last.

**Comment by cig0** [comment]
@eeedean "Please do squash the 3 separate Commits" got it. Gotcha. When I pushed the changes in separate commits, I did it to clarify the changes at every step. I know now how to do it next time properly :rocket:

Can I add my user to the maintainers' list within this PR, or should I create a separate one?

**Comment by eeedean** [comment]
> @eeedean "Please do squash the 3 separate Commits" Gotcha. When I pushed the changes in separate commits, I did it to clarify the changes at every step. I know now how to do it next time properly 🚀

Great! 😸

> Can I add my user to the maintainers' list within this PR, or should I create a separate one?

You may do that in this PR.

—-

I‘m new, too and needed several attempts at my PR, when I got here 😸

**Comment by cig0** [comment]
@eeedean All lights green -- your turn!

**Comment by eeedean** [comment]
> @eeedean All lights green -- your turn!
> 
> Edit: I missed the Darwin builds 🫣

Haha, yeah those darwin aarch64-builds take a while unfortunately. 

But yeah, LGTM 😁 I‘m optimistic

**Review by eeedean — APPROVED** [review]

**Comment by eeedean** [comment]
@NixOS/nixpkgs-merge-bot merge

**Review by eeedean — CHANGES_REQUESTED** [review]
I just skimmed through [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) again and it states: 
> When adding yourself as maintainer in the same pull request, make a separate commit with the message maintainers: add <handle>. Add the commit **before those making changes to the package or module**. See [Nixpkgs Maintainers](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md) for details.

Therefore, you might want to change the order of the commits to have adding yourself into the maintainers list before doing the changes to the package. 

Also from a practical standpoint it makes sense: The package would be broken in the commits between "adding yourself to the list of maintainers in the package" and "adding yourself into the maintainers-list.nix".

**Comment by cig0** [comment]
> I just skimmed through [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) again and it states:
> 
> > When adding yourself as maintainer in the same pull request, make a separate commit with the message maintainers: add . Add the commit **before those making changes to the package or module**. See [Nixpkgs Maintainers](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md) for details.
> 
> Therefore, you might want to change the order of the commits to have adding yourself into the maintainers list before doing the changes to the package.
> 
> Also from a practical standpoint it makes sense: The package would be broken in the commits between "adding yourself to the list of maintainers in the package" and "adding yourself into the maintainers-list.nix".

:100: -- I should've noticed this.

**Review by eeedean — APPROVED** [review]

**Comment by cig0** [comment]
:face_holding_back_tears:

**Comment by cig0** [comment]
@eeedean Thank you so much for spending time with me. What I learned will be used well, as I plan to help maintain a few other packages.

**Comment by eeedean** [comment]
> @eeedean Thank you so much for spending time with me. What I learned will be used well, as I plan to help maintain a few other packages.

Congratulations to your first contribution and welcome aboard 🚢

**Comment by JustinLex** [comment]
Noob here, should this PR be backported to NixOS 24.05 since the download hash there is broken too?

**Comment by cig0** [comment]
> Noob here, should this PR be backported to NixOS 24.05 since the download hash there is broken too?

Hi Justin, I was thinking about doing so. I'll get back to this later today.

**Pull request merged**
