### PR TITLE
scalapack: 2.1.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
Changelog: http://netlib.org/scalapack/scalapack-2.2.0.html
Enable optional build with ILP64 interface.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build octopus

**Comment by sheepforce** [comment]
Does the ILP64 interface also require MPI to be built with 8 byte integers? Or does it work with standard 4-byter integer MPI? I didn't understand the upstream changes completely.

**Comment by markuskowa** [comment]
> Does the ILP64 interface also require MPI to be built with 8 byte integers? Or does it work with standard 4-byter integer MPI? I didn't understand the upstream changes completely.

The MPI interface usually has a fixed definition with 4 byte integers (there might be an Intel version with 8 byte). Thus, changing BLAS to ILP64 does not affect the MPI Fortran interface. If you build scalapack from this PR with ILP64 support it will pass the tests with an unmodified MPI.

**Comment by sheepforce** [comment]
> The MPI interface usually has a fixed definition with 4 byte integers (there might be an Intel version with 8 byte).

Thank you for the explanation. My confusion was caused by an older attempt to make Scalapack work with 8 byte integers https://github.com/albandil/scalapack-ilp64, that required 8 byte MPI. OpenMPI can be built with 8 byte integers to support it. I've used this long time ago for [GlobalArrays and Molcas](https://gitlab.com/Molcas/OpenMolcas/-/issues/159). Nice to know, that there is now a solution without the need for an extra MPI.

**Comment by sheepforce** [comment]
@GrahamcOfBorg build cp2k

**Review by sheepforce — APPROVED** [review]

**Pull request merged**
