### PR TITLE
cln: fix build on darwin

### PR DESCRIPTION
**Pull request by siraben**
See https://github.com/NixOS/nixpkgs/pull/162265#issuecomment-1100467765

ZHF: #172160

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 172921` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>echidna</li>
    <li>maude</li>
    <li>tamarin-prover</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>ginac</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>cln</li>
    <li>cvc4</li>
  </ul>
</details>

**Comment by risicle** [comment]
This appears to have broken `ginac` on darwin-x86_64: https://hydra.nixos.org/build/177064196

**Comment by risicle** [comment]
Indeed, the output is an empty directory on both darwin aarch64 and x86_64.

**Comment by risicle** [comment]
Propose we revert this because it doesn't _actually_fix the problem and breaks darwin x86_64. This approach produces an empty output because it can't find any `Makefile` because autoconf/automake hasn't been run on the source. I'm also not sure what difference pulling the source from git would make.

Interestingly, the author has made several commits to master in the last few days related to ARM assembly, so it's possible some combination of those applied as patches might help things. Could also look to see if there were a way to disable ARM assembly, because reading the commit messages it looks rather like a work in progress.

**Pull request merged**
