### PR TITLE
jupyter: fix missing logos in the default kernel

### PR DESCRIPTION
**Pull request by SomeoneSerge**
###### Motivation for this change

`log-{32x32,64x64}.png` symlinks generated by `jupyter-kernel.create { definitions = default; }` pointed to invalid relative paths; now they are absolute paths

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Flakebi — APPROVED** [review]
Looks good, I can confirm that this fixes the Python logo in notebooks.

**Comment by smancill** [comment]
@SomeoneSerge can you rebase `master`?

**Comment by SomeoneSerge** [comment]
@smancill rebased and removed the formatting commit

**Comment by smancill** [comment]
@ofborg build python310Packages.jupyter

**Comment by smancill** [comment]
A dependency is broken now so we must wait until fixed: https://github.com/NixOS/nixpkgs/pull/186272#issuecomment-1215095181

**Comment by smancill** [comment]
Result of `nixpkgs-review pr 134870` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jupyter</li>
  </ul>
</details>

**Comment by smancill** [comment]
Works:

``` bash
$ ls -lR /nix/store/5i920558b4kzk8iad97z780faxsqxa4k-jupyter-kernels
/nix/store/5i920558b4kzk8iad97z780faxsqxa4k-jupyter-kernels:
total 0
dr-xr-xr-x 3 smancill admin 96 Dec 31  1969 kernels

/nix/store/5i920558b4kzk8iad97z780faxsqxa4k-jupyter-kernels/kernels:
total 0
dr-xr-xr-x 5 smancill admin 160 Dec 31  1969 python3

/nix/store/5i920558b4kzk8iad97z780faxsqxa4k-jupyter-kernels/kernels/python3:
total 4
-r--r--r-- 1 smancill admin 489 Dec 31  1969 kernel.json
lrwxr-xr-x 1 smancill admin 126 Dec 31  1969 logo-32x32.png -> /nix/store/sa9wkdh8p1ivf8z38s8xc94srf1pzl3j-python3-3.10.6-env/lib/python3.10/site-packages/ipykernel/resources/logo-32x32.png
lrwxr-xr-x 1 smancill admin 126 Dec 31  1969 logo-64x64.png -> /nix/store/sa9wkdh8p1ivf8z38s8xc94srf1pzl3j-python3-3.10.6-env/lib/python3.10/site-packages/ipykernel/resources/logo-64x64.png
```

**Pull request merged**
