### PR TITLE
nixos/switch-to-configuration: Improve socket and timer handling, clean up, minor fixes, add test

### LINKED ISSUE #74899: changes to socket units don't restart
https://github.com/NixOS/nixpkgs/pull/73871 attempted to fix this, but there were issues with sockets restarting all the time.

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

This is the second attempt to restart sockets properly.
The last time people were not completely happy so I kind of went over the top here.

cc @alyssais to make sure I don't break cross again
cc @grahamc maybe you could take a look at the Perl if you find time

Fixes #74899
Closes #33661

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) → `switch-test.nix`
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
@GrahamcOfBorg test switchTest

**Review by chrissyjai — APPROVED** [review]

**Review by Mic92 — APPROVED** [review]
Code looks good to me. I am doing some actual testing now.

**Review by Mic92 — APPROVED** [review]
Successfully tested. I will merge this in a few days.

**Comment by primeos** [comment]
Unfortunately this causes the exact same issues as before and I urge to revert it ASAP because it is very annoying (no offense): https://github.com/NixOS/nixpkgs/pull/147609

I'm a bit late to the party as I didn't update in a while as I lacked time to deal with such issues (and I was afraid when I saw this change).

**Comment by aanderse** [comment]
ping @tomberek @nrdxp

**Pull request merged**
