### PR TITLE
python3Packages.ibis-framework: init at 1.2.0

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Adding ibis-framework for a project currently working on

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
Result of `nix-review pr 64996` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>2 package were build:</summary>

  - python37Packages.ibis
  - python37Packages.ibis-framework
</details>

**Comment by costrouc** [comment]
@GrahamcOfBorg build python3Packages.ibis-framework python3Packages.ibis

**Comment by costrouc** [comment]
@GrahamcOfBorg build python3Packages.ibis-framework python3Packages.ibis

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
Diff LGTM
leaf packages

nice :)

**Comment by risicle** [comment]
`nox-review` is happy for me non-nixos linux x86_64

**Pull request merged**
