### PR TITLE
[backport-19.09] yubioath-desktop: 4.3.6 -> 5.0.2

### PR DESCRIPTION
**Pull request by rissson**
###### Motivation for this change

Backporting #81162

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @Mic92

### CODE REVIEW

**Comment by Mic92** [comment]
What was the reason for this backport?

**Comment by rissson** [comment]
> What was the reason for this backport?

Being able to use the new version while being on the 19.09 channel.

**Comment by Mic92** [comment]
We usually only backport bugfixes and security fixes. There are ways of using unstable channels in a stable channel as well or you could add it to an overlay.

**Comment by rissson** [comment]
According to the release notes [1], there have been no security fixes, but there have been some bugfixes

[1] https://developers.yubico.com/yubioath-desktop/Release_Notes.html

**Comment by rissson** [comment]
Should I close this then?

**Pull request closed without merging**
