### PR TITLE
steam: runtime-generated.nix md5->sha256

### PR DESCRIPTION
**Pull request by chris-martin**
###### Motivation for this change
#4491 (md5 sucks)
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
cc @abbradar

**Comment by abbradar** [comment]
The reason because I use md5 is because Runtime [contains a tag file with md5 sums](https://github.com/chris-martin/nixpkgs/blob/16fc6f2254aed359da32d774a82583309b3f1b39/pkgs/games/steam/build-runtime.py#L33). I'm not sure if it's really needed though.

**Comment by abbradar** [comment]
I'll see what happens when you remove the tag file in the weekend and move to sha256 if it's okay.

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/cac553e8e098022a444661c35526562737675bb3

**Pull request closed without merging**
