### PR TITLE
gitlab-runner: fix wrong hash

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

Follow-up of #123871

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zimbatm** [comment]
Result of `nixpkgs-review pr 124033` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitlab-runner</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124033` at 2642f469 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>gitlab-runner</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/tools/continuous-integration/gitlab-runner/default.nix:36:15:
```
   |
36 |   patches = [ ./fix-shell-path.patch ];
   |               ^
```
</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by max-wittig** [comment]
@zimbatm Just for my understanding. How did this happen? Did GitLab swap their tag?

**Comment by petabyteboy** [comment]
Possible. Or the hash was never correct. It will be hard to find out. If @max-wittig has the old FOD in the store still we could get a diff maybe?

**Comment by max-wittig** [comment]
That a look at the screenshot here:

Ran the prefetch command three times and got two different results: https://github.com/NixOS/nixpkgs/pull/123871#issuecomment-846148869

**Comment by zimbatm** [comment]
I missed that. @max-wittig can you run `diffoscope` on both store paths?

**Comment by zimbatm** [comment]
If the output of GitLab is not stable, that's an issue with them and we need to file a bug upstream. That's quite bad and is likely to impact more sources in nixpkgs.

**Comment by zimbatm** [comment]
I'm only getting that hash:
```console
$ GITLAB_RUNNER_VERSION=13.12.0; nix-prefetch-url --unpack https://gitlab.com/gitlab-org/gitlab-runner/-/archive/v$GITLAB_RUNNER_VERSION/gitlab-runner-v$GITLAB_RUNNER_VERSION.tar.gz
path is '/nix/store/0z1r3w6wwja6hazbv8y3ws0clk92chy5-gitlab-runner-v13.12.0.tar.gz'
01ajl7zka5fnph5zcnp3z6ir8xr81wzkam69gxazwjb3nbs642an
```

**Pull request merged**
