### PR TITLE
Add service for glances

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I rudimentarily tested the service on my local device.

The `username` and `password` do not work as expected, will shortly push a commit to disable these options.

### CODE REVIEW

**Comment by lsix** [comment]
Hi,

The service has options to enable or disable many capabilities of glances. However, some of them only makes sense if `glances` has the proper support, and this is not always true since it has many optional dependencies. For instance, `python*Packages.glances`'s `propagatedBuildInputs` argument do not have `python*Packages.docker`, but the `disable-docker` option make it look that it could be enabled by default.

Maybe the options should be limited to the ones that only change something?

**Comment by matthiasbeyer** [comment]
@lsix thanks for pointing this out. I will continue to work on this, so that if a certain switch is enabled, the appropriate dependencies of glances are built into the package.

---

So, this is WIP, don't merge please! :small_airplane:

**Comment by matthiasbeyer** [comment]
The commits I just pushed are _not tested_, but I ask for review here, whether this approach is a good idea or not...

**Comment by FRidh** [comment]
I don't know much about glances, but if you think it makes sense to have a service, go ahead, implement it and maintain it. Just don't get too ambitious with all the options.

Also think about whether it makes sense or not to add optional dependencies to the `propagatedBuildInputs` of the `glances` application. Perhaps it makes more sense to add an environment where `glances` has access to those optional dependencies?

**Comment by FRidh** [comment]
Status update?

**Comment by matthiasbeyer** [comment]
No time atm, but I will rebase to fix merge issues, so others can pick it up easily. Will continue as soon as I have enough free time.

**Pull request closed without merging**
