### PR TITLE
music-player: 0.2.0-alpha.14-unstable-2024-08-24 -> 0.2.0-alpha.14-unstable-2024-10-02

### LINKED ISSUE #348649: Build failure: music-player
### Steps To Reproduce

1. build *music-player*
The following should reproduce it:
```console
nix shell nixpkgs#music-player
``` 
```console
nix-shell -p music-player
```

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/gkm3izbr942v43rwddnyiqwcnx1pcc6d-music-player-0.2.0-alpha.14-unstable-2024-08-24-vendor.tar.gz.drv':
        likely URL: (unknown)
         specified: sha256-JmyuA5p6/7jtNuOMWuAuspYYid+dGOeollIlS0DRCIE=
            got:    sha256-SjGcvrbq9zIFdMf9PkLrCa/fBsJgj+yrz/NGfvua8gE=
error: 1 dependencies of derivation '/nix/store/njz4d5f84phn7xbhdz9hk1rs1f090ywp-music-player-0.2.0-alpha.14-unstable-2024-08-24.drv' failed to build
```

### Additional context

none

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.11-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/elias-ainsworth/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/elias-ainsworth/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/elias-ainsworth/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/elias-ainsworth/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/cfl6rqw64ndbh2m0qapg410jf4xmycia-lix-2.91.0/share`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SigmaSquadron**
Fixes build of unmaintained package for ZHF.

ZHF: #352882

closes #348649
closes #340548

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 353170"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by itepastra** [comment]
--------- Report for 'x86_64-linux' ---------
1 package built:
music-player

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353170`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>music-player</li>
  </ul>
</details>

**Comment by itepastra** [comment]
binary also starts the webui correctly

**Review by itepastra — APPROVED** [review]

**Comment by SigmaSquadron** [comment]
Apparently this package is supposed to have a TUI, but I'm not sure how to build it.

**Comment by SigmaSquadron** [comment]
That's the CLI. I'm referring to the TUI: https://github.com/tsirysndr/music-player/blob/master/preview-tui.png

**Comment by itepastra** [comment]
you need to start the server, and then from a second terminal you do `music-player connect --host localhost` to enter the tui

**Pull request merged**
