### PR TITLE
Misc cleanups of rustc and cargo packaging

### PR DESCRIPTION
**Pull request by Ericson2314**
Hopefully this will make maintenance easier going forward.

### CODE REVIEW

**Comment by iElectric** [comment]
cc @madjar

**Comment by madjar** [comment]
Cool, thanks for that!

**Comment by jagajaga** [comment]
Please note, that we have to update `racer` if we update `rustc`. @madjar @ericson2314

**Comment by jagajaga** [comment]
Amen! :)

**Comment by madjar** [comment]
That's done in 74f15178b169ad63e280e0fd8af21b221c2836a4

**Comment by Ericson2314** [comment]
Wait, in this commit I just changed the way things were packaged, not the versions of what we were packaging. Did racer break anyways?

**Comment by Ericson2314** [comment]
racer currently depends on 0.12. So the note is in the wrong place.

**Pull request merged**
