### PR TITLE
tdesktop: 4.6.2 -> 4.6.3

### PR DESCRIPTION
**Pull request by NickCao**
Release: https://github.com/telegramdesktop/tdesktop/releases/tag/v4.6.3
Changes: https://github.com/telegramdesktop/tdesktop/compare/v4.6.2...v4.6.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tshipenchko** [comment]
Telegram not working since 4.6.2 version. I use nixos-stable and +unstable packages with flakes.
```commandline
$ telegram-desktop -workdir ~/tmp
/run/current-system/sw/bin/telegram-desktop: /nix/store/b13h86pg7lbf6vpc1vwzw6akmakyw1bs-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /run/current-system/sw/bin/telegram-desktop)
/run/current-system/sw/bin/telegram-desktop: /nix/store/b13h86pg7lbf6vpc1vwzw6akmakyw1bs-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/wajjav2jabaaq0laky9bdkmnhxi259wr-openal-soft-1.22.2/lib/libopenal.so.1)
/run/current-system/sw/bin/telegram-desktop: /nix/store/b13h86pg7lbf6vpc1vwzw6akmakyw1bs-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/b541v954rvqb8ab74j1vzxhv456p7k9l-qtbase-6.4.2/lib/libQt6Core.so.6)
/run/current-system/sw/bin/telegram-desktop: /nix/store/b13h86pg7lbf6vpc1vwzw6akmakyw1bs-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/jlx2nfpi73sjb0f3096cly5ik8arw9k9-icu4c-72.1/lib/libicuuc.so.72)
$ steam-run telegram-desktop -workdir ~/tmp
/run/current-system/sw/bin/telegram-desktop: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /run/current-system/sw/bin/telegram-desktop)
/run/current-system/sw/bin/telegram-desktop: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/b541v954rvqb8ab74j1vzxhv456p7k9l-qtbase-6.4.2/lib/libQt6Core.so.6)
```
But, looks like libs are OK
```commandline
$ strings /nix/store/b541v954rvqb8ab74j1vzxhv456p7k9l-qtbase-6.4.2/lib/libQt6Core.so.6 | grep GLIBCXX_3.4.30
GLIBCXX_3.4.30
_ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE@GLIBCXX_3.4.30
$ strings /nix/store/jlx2nfpi73sjb0f3096cly5ik8arw9k9-icu4c-72.1/lib/libicuuc.so.72 | grep GLIBCXX_3.4.30
GLIBCXX_3.4.30
_ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE@GLIBCXX_3.4.30
```

**Comment by tshipenchko** [comment]
I made it to work:
```commandline
$ LD_LIBRARY_PATH=/nix/store/k88zxp7cvd5gpharprhg9ah0vhz2asq7-gcc-12.2.0-lib/lib/libstdc++.so.6 telegram-desktop -workdir ~/tmp
```

**Comment by NickCao** [comment]
Please check your environment variables, namely `$LD_LIBRARY_PATH`, as well as whether `telegram-desktop` and libraries in `/run/opengl-driver` are linked to the same `libstdc++.so.6`.

**Comment by NickCao** [comment]
Backporting tdesktop updates to release-22.11: https://github.com/NixOS/nixpkgs/pull/217154

**Pull request merged**
