### PR TITLE
qemu: 2.11.1 -> 2.12.0

### LINKED ISSUE #39423: qemu 2.12.0 released
## Issue description

Qemu 2.12.0 has released today. We need to update package.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

Bump and  remove obsolete patches. Closes #39423 .

Edit: also include a fix by @dtzWill for musl and remove the now obsolete `qemu-riscv` package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@dtzWill I didn't check the musl patches, feel free to look at them now or fix whatever breaks later :smile:

**Comment by dtzWill** [comment]
> @dtzWill I didn't check the musl patches, feel free to look at them now or fix whatever breaks later 
> 


Thanks for the heads-up, I'll take a look and let you know / file PR to fix it.  I gotta call it for the night, but will take a look in the morning. If there's anyone waiting to see this merged please go ahead, don't block it on my account :).

**Comment by dtzWill** [comment]
FWIW https://github.com/dtzWill/nixpkgs/commit/91b5f5a463f5545fbf4f916b3c624840fcb9f300 adds fix w/musl, I was planning to submit it separately but can probably be added along with if you don't have any objections.

Not sure who else should look at this... @shlevy ? :)

**Comment by shlevy** [comment]
Does this version include the riscv support?

**Comment by dtzWill** [comment]
> Does this version include the riscv support?

I thought so, and looking at the changelog it looks like "yes": https://wiki.qemu.org/ChangeLog/2.12#RISC-V

**Comment by xeji** [comment]
> FWIW dtzWill/nixpkgs@91b5f5a adds fix w/musl, I was planning to submit it separately but can probably be added along with if you don't have any objections.

I'll include your fix here.

**Comment by xeji** [comment]
> Does this version include the riscv support?

Yes, and builds by default:  `qemu-system-riscv32 qemu-system-riscv64`. Didn't test it though.

**Review by dtzWill — APPROVED** [review]
LGTM.

**Comment by xeji** [comment]
Should we remove the separate `qemu-riscv` package then ?

**Comment by shlevy** [comment]
Please do!

**Comment by xeji** [comment]
that ofborg timeout is normal for a full qemu build.

**Pull request merged**
