### PR TITLE
Update php packages

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update php packages to version 7.1.27, 7.2.16 and 7.3.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by etu** [comment]
Changelogs:
http://www.php.net/ChangeLog-7.php#7.1.27
http://www.php.net/ChangeLog-7.php#7.2.16
http://www.php.net/ChangeLog-7.php#7.3.3

PHP should usually be backported to stable, so if you wish to create backport PR's for the 19.03 and 18.09 branch that would be great :-)

**Comment by etu** [comment]
@GrahamcOfBorg build php71 php72 php73

**Comment by etu** [comment]
@Izorkin Maybe focus at the task at hand for this PR? Only the update and make sure that works? Options sure are great, but it's a separate PR.

**Comment by Izorkin** [comment]
@GrahamcOfBorg build php73

**Comment by etu** [comment]
@GrahamcOfBorg build php73-embed php73

**Review by fpletz — APPROVED** [review]

**Comment by etu** [comment]
php73 just did build on #57361 on darwin. So I'll go ahead and merge this.

**Pull request merged**
