### PR TITLE
staging-next: 21.11 iteration 2 - 2021-11-16

### PR DESCRIPTION
**Pull request by jonringer**
Last staging-next iteration for ZHF. Documentation here: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-staging-next-branch

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

*Per the [release schedule](https://discourse.nixos.org/t/lets-have-a-great-21-11-release-cycle/15262/3) we are still restricted to non-breaking changes to staging-next, and the plan is to merge in about a week (Nov 19).*

Previous staging-next PR: https://github.com/NixOS/nixpkgs/pull/144730

### CODE REVIEW

**Review by ttuegel — APPROVED** [review]

**Comment by fabianhjr** [comment]
A lot of failures are propagated from Python 3.9 Hypothesis:

[python3.9-hypothesis-6.23.2](https://hydra.nixos.org/build/158498090/nixlog/1)

**Comment by fabianhjr** [comment]
Seem like there are some Hydra runner issues. https://hydra.nixos.org/build/158470037

**Comment by fabianhjr** [comment]
```
=========================== short test summary info ============================
ERROR tests/test_inotify_buffer.py::test_move_internal_batch - AssertionError...
============= 107 passed, 5 skipped, 1 warning, 1 error in 37.56s ==============
error: builder for '/nix/store/7mdz81lsn0q04dqazn5qib3qndqs0616-python3.9-watchdog-2.1.6.drv' failed with exit code 1;
```

On NixOS x86_64

**Comment by fabianhjr** [comment]
It seems like it was a race condition when doing a home-manager switch with several concurrent builders. Building it directly went ok and completed succesfully.

**Comment by vcunat** [comment]
@tomberek, @nrdxp: merge was originally planned today, but I'm afraid that `staging-next` won't even finish `x86_64-linux` builds by the end of the week.

Now: 2k still succeeding, 41k queued.   Even though there were almost no linux-related rebuilds in the past few days, except for merges from `master`.

**Comment by jonringer** [comment]
@ofborg eval

**Comment by fabianhjr** [comment]
Able to do a nixos rebuild and home-manager switch into staging-next. Everything seems to be working fine. :3

**Comment by vcunat** [comment]
Some python packages regressed apparently (all was tried twice at least), but overall I can't see anything big.  _A few thousand x86_64-darwin builds are still in progress, too._

**Comment by happysalada** [comment]
I've switched my darwin system to this branch 24h ago and no problem so far.

**Pull request merged**
