### PR TITLE
borgbackup: 1.2.3 -> 1.2.4

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Changelog: https://github.com/borgbackup/borg/blob/1.2.4/docs/changes.rst

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @puetzk

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 223318` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>borgbackup</li>
    <li>borgbackup.dist</li>
    <li>borgbackup.doc</li>
    <li>borgbackup.man</li>
    <li>borgmatic</li>
    <li>borgmatic.dist</li>
    <li>emborg (python310Packages.emborg)</li>
    <li>emborg.dist (python310Packages.emborg.dist)</li>
    <li>pika-backup</li>
    <li>python311Packages.emborg</li>
    <li>python311Packages.emborg.dist</li>
    <li>vorta</li>
    <li>vorta.dist</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 223318` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>borgbackup</li>
    <li>borgbackup.dist</li>
    <li>borgbackup.doc</li>
    <li>borgbackup.man</li>
    <li>borgmatic</li>
    <li>borgmatic.dist</li>
    <li>emborg (python310Packages.emborg)</li>
    <li>emborg.dist (python310Packages.emborg.dist)</li>
    <li>pika-backup</li>
    <li>python311Packages.emborg</li>
    <li>python311Packages.emborg.dist</li>
    <li>vorta</li>
    <li>vorta.dist</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
```
borgbackup-x86_64-darwin> _______________________ ArchiverTestCase.test_overwrite ________________________
borgbackup-x86_64-darwin> [gw3] darwin -- Python 3.10.10 /nix/store/a4ivjgjcdk0l4yzylhc1q7acm7abdz6x-python3-3.10.10/bin/python3.10
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_overwrite>
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin>     def test_overwrite(self):
borgbackup-x86_64-darwin>         self.create_regular_file('file1', size=1024 * 80)
borgbackup-x86_64-darwin>         self.create_regular_file('dir2/file2', size=1024 * 80)
borgbackup-x86_64-darwin>         self.cmd('init', '--encryption=repokey', self.repository_location)
borgbackup-x86_64-darwin>         self.cmd('create', self.repository_location + '::test', 'input')
borgbackup-x86_64-darwin>         # Overwriting regular files and directories should be supported
borgbackup-x86_64-darwin>         os.mkdir('output/input')
borgbackup-x86_64-darwin>         os.mkdir('output/input/file1')
borgbackup-x86_64-darwin>         os.mkdir('output/input/dir2')
borgbackup-x86_64-darwin>         with changedir('output'):
borgbackup-x86_64-darwin>             self.cmd('extract', self.repository_location + '::test')
borgbackup-x86_64-darwin> >       self.assert_dirs_equal('input', 'output/input')
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/archiver.py:1557: 
borgbackup-x86_64-darwin> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:189: in assert_dirs_equal
borgbackup-x86_64-darwin>     self._assert_dirs_equal_cmp(diff, **kwargs)
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:238: in _assert_dirs_equal_cmp
borgbackup-x86_64-darwin>     self.assert_equal(d1, d2)
borgbackup-x86_64-darwin> E   AssertionError: Lists differ: ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920183748861000, {}] != ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920183748860000, {}]
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   First differing element 7:
borgbackup-x86_64-darwin> E   1679920183748861000
borgbackup-x86_64-darwin> E   1679920183748860000
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   - ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920183748861000, {}]
borgbackup-x86_64-darwin> E   ?                                                            ^
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   + ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920183748860000, {}]
borgbackup-x86_64-darwin> E   ?                                                            ^
borgbackup-x86_64-darwin> _________ ArchiverTestCase.test_can_read_repo_even_if_nonce_is_deleted _________
borgbackup-x86_64-darwin> [gw0] darwin -- Python 3.10.10 /nix/store/a4ivjgjcdk0l4yzylhc1q7acm7abdz6x-python3-3.10.10/bin/python3.10
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_can_read_repo_even_if_nonce_is_deleted>
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin>     def test_can_read_repo_even_if_nonce_is_deleted(self):
borgbackup-x86_64-darwin>         """Nonce is only used for encrypting new data.
borgbackup-x86_64-darwin>     
borgbackup-x86_64-darwin>         It should be possible to retrieve the data from an archive even if
borgbackup-x86_64-darwin>         both the client and the server forget the nonce"""
borgbackup-x86_64-darwin>         self.create_regular_file('file1', contents=b'Hello, borg')
borgbackup-x86_64-darwin>         self.cmd('init', '--encryption=repokey', self.repository_location)
borgbackup-x86_64-darwin>         self.cmd('create', self.repository_location + '::test', 'input')
borgbackup-x86_64-darwin>         # Oops! We have removed the repo-side memory of the nonce!
borgbackup-x86_64-darwin>         # See https://github.com/borgbackup/borg/issues/5858
borgbackup-x86_64-darwin>         os.remove(os.path.join(self.repository_path, 'nonce'))
borgbackup-x86_64-darwin>         # Oops! The client has lost the nonce too!
borgbackup-x86_64-darwin>         os.remove(os.path.join(self.get_security_dir(), 'nonce'))
borgbackup-x86_64-darwin>     
borgbackup-x86_64-darwin>         # The repo should still be readable
borgbackup-x86_64-darwin>         repo_info = self.cmd('info', self.repository_location)
borgbackup-x86_64-darwin>         assert 'All archives:' in repo_info
borgbackup-x86_64-darwin>         repo_list = self.cmd('list', self.repository_location)
borgbackup-x86_64-darwin>         assert 'test' in repo_list
borgbackup-x86_64-darwin>         # The archive should still be readable
borgbackup-x86_64-darwin>         archive_info = self.cmd('info', self.repository_location + '::test')
borgbackup-x86_64-darwin>         assert 'Archive name: test\n' in archive_info
borgbackup-x86_64-darwin>         archive_list = self.cmd('list', self.repository_location + '::test')
borgbackup-x86_64-darwin>         assert 'file1' in archive_list
borgbackup-x86_64-darwin>         # Extracting the archive should work
borgbackup-x86_64-darwin>         with changedir('output'):
borgbackup-x86_64-darwin>             self.cmd('extract', self.repository_location + '::test')
borgbackup-x86_64-darwin> >       self.assert_dirs_equal('input', 'output/input')
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/archiver.py:3736: 
borgbackup-x86_64-darwin> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:189: in assert_dirs_equal
borgbackup-x86_64-darwin>     self._assert_dirs_equal_cmp(diff, **kwargs)
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:238: in _assert_dirs_equal_cmp
borgbackup-x86_64-darwin>     self.assert_equal(d1, d2)
borgbackup-x86_64-darwin> E   AssertionError: Lists differ: ['file1', '0o100600', 322, 30000, None, 1, 0, 1679920188901433000, {}] != ['file1', '0o100600', 322, 30000, None, 1, 0, 1679920188901432000, {}]
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   First differing element 7:
borgbackup-x86_64-darwin> E   1679920188901433000
borgbackup-x86_64-darwin> E   1679920188901432000
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   - ['file1', '0o100600', 322, 30000, None, 1, 0, 1679920188901433000, {}]
borgbackup-x86_64-darwin> E   ?                                                              ^
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   + ['file1', '0o100600', 322, 30000, None, 1, 0, 1679920188901432000, {}]
borgbackup-x86_64-darwin> E   ?                                                              ^
borgbackup-x86_64-darwin> ______________________ ArchiverTestCase.test_sparse_file _______________________
borgbackup-x86_64-darwin> [gw4] darwin -- Python 3.10.10 /nix/store/a4ivjgjcdk0l4yzylhc1q7acm7abdz6x-python3-3.10.10/bin/python3.10
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_sparse_file>
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin>     def test_sparse_file(self):
borgbackup-x86_64-darwin>         def is_sparse(fn, total_size, hole_size):
borgbackup-x86_64-darwin>             st = os.stat(fn)
borgbackup-x86_64-darwin>             assert st.st_size == total_size
borgbackup-x86_64-darwin>             sparse = True
borgbackup-x86_64-darwin>             if sparse and hasattr(st, 'st_blocks') and st.st_blocks * 512 >= st.st_size:
borgbackup-x86_64-darwin>                 sparse = False
borgbackup-x86_64-darwin>             if sparse and has_seek_hole:
borgbackup-x86_64-darwin>                 with open(fn, 'rb') as fd:
borgbackup-x86_64-darwin>                     # only check if the first hole is as expected, because the 2nd hole check
borgbackup-x86_64-darwin>                     # is problematic on xfs due to its "dynamic speculative EOF preallocation
borgbackup-x86_64-darwin>                     try:
borgbackup-x86_64-darwin>                         if fd.seek(0, os.SEEK_HOLE) != 0:
borgbackup-x86_64-darwin>                             sparse = False
borgbackup-x86_64-darwin>                         if fd.seek(0, os.SEEK_DATA) != hole_size:
borgbackup-x86_64-darwin>                             sparse = False
borgbackup-x86_64-darwin>                     except OSError:
borgbackup-x86_64-darwin>                         # OS/FS does not really support SEEK_HOLE/SEEK_DATA
borgbackup-x86_64-darwin>                         sparse = False
borgbackup-x86_64-darwin>             return sparse
borgbackup-x86_64-darwin>     
borgbackup-x86_64-darwin>         filename = os.path.join(self.input_path, 'sparse')
borgbackup-x86_64-darwin>         content = b'foobar'
borgbackup-x86_64-darwin>         hole_size = 5 * (1 << CHUNK_MAX_EXP)  # 5 full chunker buffers
borgbackup-x86_64-darwin>         total_size = hole_size + len(content) + hole_size
borgbackup-x86_64-darwin>         with open(filename, 'wb') as fd:
borgbackup-x86_64-darwin>             # create a file that has a hole at the beginning and end (if the
borgbackup-x86_64-darwin>             # OS and filesystem supports sparse files)
borgbackup-x86_64-darwin>             fd.seek(hole_size, 1)
borgbackup-x86_64-darwin>             fd.write(content)
borgbackup-x86_64-darwin>             fd.seek(hole_size, 1)
borgbackup-x86_64-darwin>             pos = fd.tell()
borgbackup-x86_64-darwin>             fd.truncate(pos)
borgbackup-x86_64-darwin>         # we first check if we could create a sparse input file:
borgbackup-x86_64-darwin>         sparse_support = is_sparse(filename, total_size, hole_size)
borgbackup-x86_64-darwin>         if sparse_support:
borgbackup-x86_64-darwin>             # we could create a sparse input file, so creating a backup of it and
borgbackup-x86_64-darwin>             # extracting it again (as sparse) should also work:
borgbackup-x86_64-darwin>             self.cmd('init', '--encryption=repokey', self.repository_location)
borgbackup-x86_64-darwin>             self.cmd('create', self.repository_location + '::test', 'input')
borgbackup-x86_64-darwin>             with changedir(self.output_path):
borgbackup-x86_64-darwin>                 self.cmd('extract', '--sparse', self.repository_location + '::test')
borgbackup-x86_64-darwin> >           self.assert_dirs_equal('input', 'output/input')
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/archiver.py:692: 
borgbackup-x86_64-darwin> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:189: in assert_dirs_equal
borgbackup-x86_64-darwin>     self._assert_dirs_equal_cmp(diff, **kwargs)
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:238: in _assert_dirs_equal_cmp
borgbackup-x86_64-darwin>     self.assert_equal(d1, d2)
borgbackup-x86_64-darwin> E   AssertionError: Lists differ: ['sparse', '0o100600', 322, 30000, None, 1, 0, 1679920189288541000, {}] != ['sparse', '0o100600', 322, 30000, None, 1, 0, 1679920189288540000, {}]
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   First differing element 7:
borgbackup-x86_64-darwin> E   1679920189288541000
borgbackup-x86_64-darwin> E   1679920189288540000
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   - ['sparse', '0o100600', 322, 30000, None, 1, 0, 1679920189288541000, {}]
borgbackup-x86_64-darwin> E   ?                                                               ^
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   + ['sparse', '0o100600', 322, 30000, None, 1, 0, 1679920189288540000, {}]
borgbackup-x86_64-darwin> E   ?                                                               ^
borgbackup-x86_64-darwin> ____________________ RemoteArchiverTestCase.test_overwrite _____________________
borgbackup-x86_64-darwin> [gw1] darwin -- Python 3.10.10 /nix/store/a4ivjgjcdk0l4yzylhc1q7acm7abdz6x-python3-3.10.10/bin/python3.10
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> self = <borg.testsuite.archiver.RemoteArchiverTestCase testMethod=test_overwrite>
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin>     def test_overwrite(self):
borgbackup-x86_64-darwin>         self.create_regular_file('file1', size=1024 * 80)
borgbackup-x86_64-darwin>         self.create_regular_file('dir2/file2', size=1024 * 80)
borgbackup-x86_64-darwin>         self.cmd('init', '--encryption=repokey', self.repository_location)
borgbackup-x86_64-darwin>         self.cmd('create', self.repository_location + '::test', 'input')
borgbackup-x86_64-darwin>         # Overwriting regular files and directories should be supported
borgbackup-x86_64-darwin>         os.mkdir('output/input')
borgbackup-x86_64-darwin>         os.mkdir('output/input/file1')
borgbackup-x86_64-darwin>         os.mkdir('output/input/dir2')
borgbackup-x86_64-darwin>         with changedir('output'):
borgbackup-x86_64-darwin>             self.cmd('extract', self.repository_location + '::test')
borgbackup-x86_64-darwin> >       self.assert_dirs_equal('input', 'output/input')
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/archiver.py:1557: 
borgbackup-x86_64-darwin> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:189: in assert_dirs_equal
borgbackup-x86_64-darwin>     self._assert_dirs_equal_cmp(diff, **kwargs)
borgbackup-x86_64-darwin> /nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/testsuite/__init__.py:238: in _assert_dirs_equal_cmp
borgbackup-x86_64-darwin>     self.assert_equal(d1, d2)
borgbackup-x86_64-darwin> E   AssertionError: Lists differ: ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920220790910000, {}] != ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920220790909000, {}]
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   First differing element 7:
borgbackup-x86_64-darwin> E   1679920220790910000
borgbackup-x86_64-darwin> E   1679920220790909000
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   - ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920220790910000, {}]
borgbackup-x86_64-darwin> E   ?                                                           -
borgbackup-x86_64-darwin> E   
borgbackup-x86_64-darwin> E   + ['dir2', '0o40700', 322, 30000, None, 3, 0, 1679920220790909000, {}]
borgbackup-x86_64-darwin> E   ?                                                            +
borgbackup-x86_64-darwin> =============================== warnings summary ===============================
borgbackup-x86_64-darwin> repository.py::NonceReservation::test_commit_nonce_reservation_asserts
borgbackup-x86_64-darwin> repository.py::NonceReservation::test_get_free_nonce_asserts
borgbackup-x86_64-darwin>   /nix/store/cghzyy4g0j4b73vbpdwhv64fyjgiv4wc-python3.10-pytest-7.2.1/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Repository.__del__ at 0x112ad7e20>
borgbackup-x86_64-darwin>   
borgbackup-x86_64-darwin>   Traceback (most recent call last):
borgbackup-x86_64-darwin>     File "/nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/repository.py", line 190, in __del__
borgbackup-x86_64-darwin>       assert False, "cleanup happened in Repository.__del__"
borgbackup-x86_64-darwin>   AssertionError: cleanup happened in Repository.__del__
borgbackup-x86_64-darwin>   
borgbackup-x86_64-darwin>     warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> repository.py::RepositoryHintsTestCase::test_hints_persistence
borgbackup-x86_64-darwin>   /nix/store/cghzyy4g0j4b73vbpdwhv64fyjgiv4wc-python3.10-pytest-7.2.1/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Repository.__del__ at 0x1129bbe20>
borgbackup-x86_64-darwin>   
borgbackup-x86_64-darwin>   Traceback (most recent call last):
borgbackup-x86_64-darwin>     File "/nix/store/mjd41v88vvbpq0gai66z6hw6ncn69ycf-borgbackup-1.2.4/lib/python3.10/site-packages/borg/repository.py", line 190, in __del__
borgbackup-x86_64-darwin>       assert False, "cleanup happened in Repository.__del__"
borgbackup-x86_64-darwin>   AssertionError: cleanup happened in Repository.__del__
borgbackup-x86_64-darwin>   
borgbackup-x86_64-darwin>     warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
borgbackup-x86_64-darwin> 
borgbackup-x86_64-darwin> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
borgbackup-x86_64-darwin> =========================== short test summary info ============================
borgbackup-x86_64-darwin> FAILED archiver.py::ArchiverTestCase::test_overwrite - AssertionError: Lists differ: ['dir2', '0o40700', 322, 30000, None, 3, 0, 1...
borgbackup-x86_64-darwin> FAILED archiver.py::ArchiverTestCase::test_can_read_repo_even_if_nonce_is_deleted - AssertionError: Lists differ: ['file1', '0o100600', 322, 30000, None, 1, 0,...
borgbackup-x86_64-darwin> FAILED archiver.py::ArchiverTestCase::test_sparse_file - AssertionError: Lists differ: ['sparse', '0o100600', 322, 30000, None, 1, 0...
borgbackup-x86_64-darwin> FAILED archiver.py::RemoteArchiverTestCase::test_overwrite - AssertionError: Lists differ: ['dir2', '0o40700', 322, 30000, None, 3, 0, 1...
borgbackup-x86_64-darwin> ===== 4 failed, 1238 passed, 274 skipped, 3 warnings in 177.06s (0:02:57) ======

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 223318` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>borgbackup</li>
    <li>borgbackup.dist</li>
    <li>borgbackup.doc</li>
    <li>borgbackup.man</li>
    <li>emborg (python310Packages.emborg)</li>
    <li>emborg.dist (python310Packages.emborg.dist)</li>
    <li>python311Packages.emborg</li>
    <li>python311Packages.emborg.dist</li>
  </ul>
</details>

**Review by drupol — APPROVED** [review]
LGTM

**Review by drupol — CHANGES_REQUESTED** [review]
Could you please fix the merge conflict so we can move forward?

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
@GrahamcOfBorg build borgbackup

**Review by drupol — APPROVED** [review]

**Pull request merged**
