### PR TITLE
speedtest-rs: fix darwin build

### PR DESCRIPTION
**Pull request by ocfox**
## Description of changes
see https://hydra.nixos.org/build/249599031

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM.
I am currrently running `nixpkgs-review` for darwin.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 288804` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>speedtest-rs</li>
  </ul>
</details>

**Comment by ocfox** [comment]
That's weird, it's normal on my aarch64 darwin, let me see if I'm doing something wrong.

**Comment by ocfox** [comment]
Result of `nixpkgs-review pr 288804` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>speedtest-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 288804` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>speedtest-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> Could you check the log? This shouldn't happen.

Sure ! Here is what I get for `aarch64-darwin`:
```
Executing cargoCheckHook
++ cargo test -j 8 --profile release --target x86_64-apple-darwin --frozen -- --test-threads=8
   Compiling speedtest-rs v0.1.5 (/private/tmp/nix-build-speedtest-rs-0.1.5.drv-1/source)
    Finished release [optimized] target(s) in 2.02s
     Running unittests src/lib.rs (target/x86_64-apple-darwin/release/deps/speedtest_rs-15c9deef790ff056)

running 12 tests
test speedtest::tests::test_construct_share_form ... ok
test distance::tests::test_distance ... ok
test speedtest::tests::test_parse_share_request_response_id ... ok
test speedtest::tests::test_share_url_hash ... ok
test speedtest_csv::tests::test_header_serialize ... ok
test speedtest_config::tests::test_parse_config_xml_83 ... ok
test speedtest_config::tests::test_parse_config_xml ... ok
test speedtest_servers_config::tests::test_parse_speedtest_servers_xml ... ok
test speedtest_servers_config::tests::test_parse_speedtest_servers_xml_with_ignore_servers ... ok
test speedtest_servers_config::tests::test_fastest_server ... ok
test speedtest::tests::test_get_configuration ... FAILED
test speedtest::tests::test_get_server_list_with_config ... FAILED

failures:

---- speedtest::tests::test_get_configuration stdout ----
thread 'speedtest::tests::test_get_configuration' panicked at /private/tmp/nix-build-speedtest-rs-0.1.5.drv-1/speedtest-rs-0.1.5-vendor.tar.gz/mockito/src/server.rs:81:10:
server should be listening
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- speedtest::tests::test_get_server_list_with_config stdout ----
thread 'speedtest::tests::test_get_server_list_with_config' panicked at /private/tmp/nix-build-speedtest-rs-0.1.5.drv-1/speedtest-rs-0.1.5-vendor.tar.gz/mockito/src/server.rs:81:10:
server should be listening


failures:
    speedtest::tests::test_get_configuration
    speedtest::tests::test_get_server_list_with_config

test result: FAILED. 10 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by ocfox** [comment]
ofborg build successed.

**Review by GaetanLepage — APPROVED** [review]
> ofborg build successed.

Oh all right.
`nix build github:ocfox/nixpkgs/speedtest-rs#speedtest-rs -L --refresh --system aarch64-darwin` still fails for me but if it works on ofborg, then I think that we should go on and merge.

**Review by adamcstephens — APPROVED** [review]
Builds for me on aarch64 and x86_64 darwin.

**Comment by Aleksanaa** [comment]
I haven't used macOS, but I'm guessing this has to do with your sandbox settings and some security policies on macOS.

**Comment by wegank** [comment]
Also builds on my machine.

**Pull request merged**
