### PR TITLE
deepin.dde-session-ui: 4.9.11 -> 4.9.12

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

- Update to version 4.9.12
- Revise hard coded paths
- Wrap binaries in `lib/deepin-daemon/`

About packaging deepin for NixOS: https://github.com/NixOS/nixpkgs/issues/59023

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
It appears they removed `dde-dman-portal` 
* https://github.com/linuxdeepin/dde-session-ui/commit/3bd028cf135ad22c784c0146e447ef34a69af768

so patching that should be removed and any `buildInputs` added for it.

* `etc/deepin/greeters.d/00-xrandr`

Appears to be a bash script.
Maybe should be wrapped with it's runtime deps in PATH?

* `bin/deepin-greeter`

Is a bash script that executes everything in `/etc/deepin/greeters.d/`.

And weirdly there's `deepin/greeters.d/lightdm-deepin-greeter` there which just executes `bin/lightdm-deepin-greeter`
Don't know what that's about but it doesn't make any sense to me :rofl:

**Comment by romildo** [comment]
> It appears they removed `dde-dman-portal`
> 
>     * [linuxdeepin/dde-session-ui@3bd028c](https://github.com/linuxdeepin/dde-session-ui/commit/3bd028cf135ad22c784c0146e447ef34a69af768)
> 
> 
> so patching that should be removed and any `buildInputs` added for it.

Done.

>     * `etc/deepin/greeters.d/00-xrandr`
> 
> 
> Appears to be a bash script.
> Maybe should be wrapped with it's runtime deps in PATH?

Replaced `xrandr` and `egrep` by their absolute paths in the script.
 
>     * `bin/deepin-greeter`
> 
> 
> Is a bash script that executes everything in `/etc/deepin/greeters.d/`.
> 
> And weirdly there's `deepin/greeters.d/lightdm-deepin-greeter` there which just executes `bin/lightdm-deepin-greeter`
> Don't know what that's about but it doesn't make any sense to me rofl

It is not that weird. `bin/deepin-greeter` runs `etc/deepin/greeters.d/lightdm-deepin-greeter`, which runs `bin/lightdm-deepin-greeter`.

But `/etc/deepin/greeters.d` is still hard coded in `bin/deepin-greeter`. So it should be replaced by by `$out/etc/deepin/greeters.d`.

**Comment by worldofpeace** [comment]
> But /etc/deepin/greeters.d is still hard coded in bin/deepin-greeter. So it should be replaced by by $out/etc/deepin/greeters.d.

It appears to be some sort of drop ins system and only used in one other place
* https://github.com/linuxdeepin/dde-preload/blob/master/dde-preload.pro#L5

Don't think it's actually used though so it should be fine to patch it like that.

**Comment by romildo** [comment]
> > But /etc/deepin/greeters.d is still hard coded in bin/deepin-greeter. So it should be replaced by by $out/etc/deepin/greeters.d.
> 
> It appears to be some sort of drop ins system and only used in one other place
> 
>     * https://github.com/linuxdeepin/dde-preload/blob/master/dde-preload.pro#L5
> 
> 
> Don't think it's actually used though so it should be fine to patch it like that.

Done in previous commit.

**Review by worldofpeace — APPROVED** [review]
LGTM

**Pull request merged**
