### PR TITLE
quarto: 1.2.478 -> 1.3.450

### PR DESCRIPTION
**Pull request by minijackson**
## Description of changes

And other niceties.

Changelog is hard to get, because "real" release tags are drowned in other automated alpha releases.

Closes #228984 #239401 #243341

Related to #232090 #246365 #237814

Tested using the `quarto-check` test, and by building some of my own documents.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
  </ul>
</details>

### CODE REVIEW

**Comment by MrTarantoga** [comment]
Looks good!

[Log](https://logs.ofborg.org/?key=nixos/nixpkgs.253065&attempt_id=fc5d7af6-ac0d-4a20-99da-39875dfcc88f)

**Review by MrTarantoga — APPROVED** [review]

**Review by MrTarantoga — APPROVED** [review]

**Comment by MrTarantoga** [comment]
Can you sqaush your commits?

**Comment by minijackson** [comment]
@MrTarantoga I've made those 3 commits because I thought they made sense that way, separating unrelated changes

**Comment by MrTarantoga** [comment]
Yep, absolutley fine, but the maintainers always wanted to sqaush the commits before merge.

**Comment by minijackson** [comment]
Which maintainers? I've been a contributor of nixpkgs for quite a while, it's the first time I've heard of squashing unrelated commits as a convention. The [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) suggests otherwise.

**Comment by thiagokokada** [comment]
The way the commits are organized looks good to me.

**Review by thiagokokada — APPROVED** [review]

**Comment by MrTarantoga** [comment]
Was a request, while version update of the RStudio package.

Anyway, good work! Thank you!

**Pull request merged**
