### PR TITLE
libSM: 1.2.2 -> 1.2.3

### PR DESCRIPTION
**Pull request by dtzWill**
https://www.spinics.net/lists/xorg/msg59081.html

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build xorg.libSM

**Comment by grahamc** [comment]
I think I fixed the mac builder.

@GrahamcOfBorg build xorg.libSM

**Comment by FRidh** [comment]
Needs a rebase.

**Comment by dtzWill** [comment]
On Sat, 20 Oct 2018 23:52:23 -0700, Frederik Rietdijk <notifications@github.com> wrote:
> Needs a rebase.

Thanks for letting me know, missed this.

I'm temporarily don't have my normal setup,
but this should be an easy rebase if someone doesn't mind handling it
(thanks and sorry).

If rebase looks bad then just start fresh and bump versions in the nix
file and tarball list, update the sha256 :).

**Comment by xeji** [comment]
rebased on current staging.

**Comment by xeji** [comment]
@GrahamcOfBorg build xorg.libSM

**Comment by xeji** [comment]
darwin failure is unrelated (in openssl).

**Pull request closed without merging**
