### PR TITLE
Haskell Packages: jailbreak strict-io

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by vcunat** [comment]
This causes a full Haskell rebuild.  Maybe move to staging instead to make it easier for Hydra?

**Comment by domenkozar** [comment]
It's not this, it's https://github.com/NixOS/nixpkgs/commit/f32fc9b03e0a5c8152f94ddec01879050df2b988

**Comment by vcunat** [comment]
Almost all of the queued jobs are `haskellPackages.*`, so I assumed this would be the cause...

**Comment by domenkozar** [comment]
Yes, sadly GHC depends on sphinx, which is a python package.

Not sure if we reverting would help much, but go ahead if you think that's beneficial.

**Comment by vcunat** [comment]
It would avoid doing this rebuild twice &ndash; once on master and then again on staging.

**Comment by vcunat** [comment]
I'll leave it.  ATM I don't feel like sacrificing a bit of my time to save (lots of) Hydra's time.

**Pull request merged**
