### PR TITLE
kops_1_15: init at 1.15.0

### PR DESCRIPTION
**Pull request by kampka**
###### Motivation for this change

New package version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @zimbatm

### CODE REVIEW

**Comment by Mic92** [comment]
What is the policy for keeping old versions for this package?

**Comment by kampka** [comment]
> What is the policy for keeping old versions for this package?

I don't think there is one yet. 
Typically the idea is to not force people to upgrade production clusters whenever nixpkgs updates.
I think it's reasonable to adopt the k8s supported versions model here, which boils down to [the lastest three minor versions](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew).
 
That being said, I would keep the existing versions because 1.12 introduces a breaking change and upgrading from <1.12 to >1.12 is not really supported.

**Comment by kampka** [comment]
Weekly reminder that this still needs a review.

**Comment by kampka** [comment]
@Mic92 So how do we make progress here?
This seems like a simple version bump to me, I don't really get why this has to linger here for weeks.

@zimbatm @offlinehacker @ehmry

**Comment by zimbatm** [comment]
let's cleanup the old versions later. Usually we keep the 3 latest

**Pull request merged**
