### PR TITLE
WIP: rewrite hardening in plain nix

### LINKED ISSUE #18995: GCC has unwanted flags
```
andy@xps:~/tmp$ NIX_DEBUG=true gcc
(some good flags for dealing with /nix/store/* and then...)
  -O2
  -D_FORTIFY_SOURCE=2
  -fstack-protector-strong
  --param
  ssp-buffer-size=4
  -fPIC
  -fno-strict-overflow
  -Wformat
  -Wformat-security
  -Werror=format-security
```

These flags should be enabled when compiling nix packages, but they should not be always on for general compiler use.

This has caused a broken debugging experience for me on the project I was working on.

Most projects have a "debug build" that has optimizations off, and this prevents that from working correctly.

NixOS version 16.09pre90254.6b20d5b (Flounder)

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

Doing it in nix makes it more lazy.

See commit messages for more details

Fixes #18995 

**This PR is not ready to merge.**
I post it to get feedback on the changes.
### TODO:
- [ ] Add hardening for other cc derivations
- [ ] Handle pie hardening (probably via `.spec` file for gcc, sadly unsupported on clang)
- [x] Make `all` flag more efficient (see https://github.com/NixOS/nixpkgs/commit/4bf0576a75fce51d0d52b7513e117d7f7a353dd0 for details) 

CC @fpletz @globin  
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by groxxda** [comment]
@fpletz can I help with the remaining todos?

**Comment by fpletz** [comment]
Yes, please start if you can. I will have time again to look at these issues at the weekend. Too much dayjob-stuff to do.

**Comment by groxxda** [comment]
@fpletz can you share your work for spec files somewhere?

**Comment by aneeshusa** [comment]
I'm a big fan of doing more in Nix (see my cmakeFlags/configureFlags PRs), but since this adds more processing to `mkDerivation`, I believe this will require #18660 to allow easy overrides of the hardening flags.

**Comment by aneeshusa** [comment]
We need to keep supporting `"all"` for backwards compatibility right now, but a nice interface improvement we can get is also supporting `hardeningEnable = true` and `hardeningDisable = true`, instead of using `"all"` as a sentinel.

**Comment by groxxda** [comment]
@fpletz I think our best shot to handle pie gracefully is to modify (ld,cc)-wrapper instead of using spec files. Something along [pseudo code]
```
for flag in flags:
  if flag matches "-?-(static|shared)":
    disable_pie = true
if disable_pie:
  flags.remove("-pie")
```
just before the debug print..

**Comment by spacekitteh** [comment]
Cool. How's this coming?

**Comment by bjornfor** [comment]
Friendly bump. Are the remaining TODOs blockers?

**Comment by copumpkin** [comment]
Any progress here?

**Comment by fpletz** [comment]
Closing in favour of #28029.

**Pull request closed without merging**
