### PR TITLE
Add `lib.trivial.orElse`, and tests for `lib.trivial.mapNullable`

### PR DESCRIPTION
**Pull request by h7x4**
###### Description of changes

This is a new function `orElse`, which aims to make nullable mapping through pipes cleaner.

The reason behind the argument ordering, is ease of use with `lib.pipe`, and ease of currying in general. It's consistent with `mapNullable`, and fits it well:

```nix
lib.pipe null [
  (mapNullable (x: x + 1))
  (orElse 1)
];
```

You can find multiple places where it might be worth using, by running `nix-shell -p ripgrep --command "rg 'if .* [!=]= null then'"` in nixpkgs.

Tests for `mapNullabe` were also added, since they were pretty similar.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by infinisil** [comment]
Sounds useful! I'm not 100% sure about the naming, `orElse` isn't bad, but here's some other ideas:
- `mapNullTo`: I like this one, would be even better if `mapNullable` would be named `mapNonNull` though
- `fromNullable`: [Matching Haskell](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Maybe.html#v:fromMaybe)
- `ifNullThen`

**Comment by h7x4** [comment]
> - fromNullable: [Matching Haskell](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Maybe.html#v:fromMaybe)

That's funny.

First thing I did before starting on this PR, was to search hoogle with the type signature to make the names match, and I found [`orElse`](https://hackage.haskell.org/package/ghc-9.6.1/docs/GHC-Data-Maybe.html#v:orElse). But I went ahead without reading its description, which states that it's actually the flipped version of `fromMaybe`.

FWIW I've seen [Java's `Optional`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#orElse-T-), [Scala's `Option`](https://www.scala-lang.org/api/2.12.1/scala/Option.html) also calls it `orElse` and `getOrElse`. I feel like the name flows well in the pipe example, but the naming doesn't really bother me that much. Open to change it.

**Comment by infinisil** [comment]
Hehe I see! Hmm so the `orElse` from Haskell has the opposite argument ordering than the `orElse` here, but I don't think using `fromNullable` is that great, it's not obvious what it does.

My favorite then is `mapNullTo`, I'll also ask @roberth for an opinion on this.

**Comment by roberth** [comment]
> ```nix
> lib.pipe null [
>   (mapNullable (x: x + 1))
>   (orElse 1)
> ];
> ```

Please write for the reader. The following leaves zero questions as to what it means, and it's an order of magnitude faster.

```nix
x: if x == null then 1 else x + 1
```

> `mapNullable`

`Nullable` is not a lawful functor, so I wouldn't call that map. `Nullable t` is very distinct from `Maybe t`/`Option[T]`, being backed by a union type rather than a sum type. Concretely this means that `Just Nothing` is not representable, so information is lost, assumptions are broken and you shouldn't use it to program anything non-trivial.

So for trivial programs, you're better off writing out the if-then-else.
And for non-trivial programs, you should also avoid it because you don't want your readers to make assumptions about how "map" functions behave.

My counterproposal is to remove `mapNullable`. That way we don't need to test it either.

> `mapNullTo`

No! It's not the values that get mapped when we say `map`! It's the _function on items_ that is mapped to a _function on lists_, etc.

**Comment by h7x4** [comment]
> The following leaves zero questions as to what it means

I agree with this, but only for a first time reader. After having read the definition (or just understood) the function once, it's IMO easier to both read and use afterwards. And I would make the argument that this is the case for large parts of lib as well. We could just unwrap a bunch of abstraction to make it easier for first time readers, but this sounds like a bad idea in the long run.

Personally, I feel like this is both common enough and the expansion is bothersome enough to read in the middle of something nontrivial that it is worth abstracting, but I know we disagree about that.

> and it's an order of magnitude faster

I don't get what you mean here. Faster to write, faster to understand, faster to execute?

> No! It's not the values that get mapped when we say map! It's the function on items that is mapped to a function on lists, etc.

I'm not a 100% stable on the formal mathematics behind this so I can't really comment. But do you know of another word to use when talking about mapping values rather than functions? Something like applying, transforming or imaging?

For both correctness and readability, maybe we could use something "less mathematical" like `replaceNullWith`?

> My counterproposal is to remove mapNullable. That way we don't need to test it either.

What do you think @infinisil?

**Comment by infinisil** [comment]
> ```nix
> lib.pipe null [
>   (mapNullable (x: x + 1))
>   (orElse 1)
> ];
> ```
> 
> Please write for the reader. The following leaves zero questions as to what it means, and it's an order of magnitude faster.
> ```nix
> x: if x == null then 1 else x + 1
> ```

After taking another look, I have to agree with @roberth here. The second code sample is a bunch more efficient because it doesn't have to do any function calls, whereas the first one calls 3 functions, Nix notably doesn't do any inlining to make this faster, each function call does have a cost. You could use `NIX_SHOW_STATS=1` for some measurements.

And it's also easier to read, instead of having to understand what `pipe`, `mapNullable` and `orElse` do, one just needs to understand `if` statements. Arguably `if` statements are a bit harder to write and format though (NixOS/rfcs#101 should improve that).

I can imagine it making code that already uses `lib.pipe` easier though. It would be good to have a bunch of real-world code use `orElse` so we could see if it's really necessary.

**Comment by h7x4** [comment]
> You could use NIX_SHOW_STATS=1 for some measurements.

That's nice to know!

Then I think I'll be closing this PR. Should we open an issue or something about the deprecation of `mapNullable`?

**Comment by infinisil** [comment]
I'm not sure if it's worth bothering deprecating `mapNullable` for now. It might not be that useful, but it doesn't bother anybody either. I do remember using it myself a couple times.

**Comment by roberth** [comment]
> calls 3 functions

Make that 10 calls.
 - `lib.pipe`
 - `lib.pipe null`
 - `mapNullable`
 - `x: x + 1`
 - `orElse`
 - `foldl'` (curried primops are a bit more efficient than curried lambdas, so I'll count this once)
 - `reverseApply` 2×
 - `reverseApply x` 2×

... almost all of which allocate closures (`Env`s), and there's the unavoidable list allocation as well.

**Pull request closed without merging**
