### PR TITLE
python311Packages.scikit-build-core: 0.5.1 -> 0.7.0

### PR DESCRIPTION
**Pull request by bcdarwin**
## Description of changes

Routine update.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by natsukium — APPROVED** [review]
The diff looks fine to me.
https://github.com/scikit-build/scikit-build-core/compare/v0.5.1...v0.7.0

**Comment by natsukium** [comment]
@ofborg build python310Packages.scikit-build-core

**Comment by natsukium** [comment]
I guess we need to add `-W ignore::UserWarning` to `pytestFlagsArray` for python=<3.10.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 277769` at ae384d40 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages failed to build:</summary>
  <ul>
    <li>python310Packages.atomman</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward-cpp</li>
    <li>python310Packages.boltztrap2</li>
    <li>python310Packages.coffea</li>
    <li>python310Packages.correctionlib</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.iminuit</li>
    <li>python310Packages.laspy</li>
    <li>python310Packages.laszip</li>
    <li>python310Packages.lightgbm</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.phonopy</li>
    <li>python310Packages.pymatgen</li>
    <li><a href="https://gist.github.com/natsukium/c089ecf72d83e15de4249c8d04bb9693">python310Packages.scikit-build-core</a></li>
    <li>python310Packages.seekpath</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.spglib</li>
    <li>python310Packages.sumo</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.vector</li>
    <li><a href="https://gist.github.com/natsukium/517ba4557b7d4a0da51b30c232e8c1ef">python311Packages.lightgbm</a></li>
    <li>python311Packages.shap</li>
  </ul>
</details>
<details>
  <summary>21 packages built successfully:</summary>
  <ul>
    <li>bitbake-language-server</li>
    <li>professor</li>
    <li>python311Packages.atomman</li>
    <li>python311Packages.awkward</li>
    <li>python311Packages.awkward-cpp</li>
    <li>python311Packages.boltztrap2</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.correctionlib</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.iminuit</li>
    <li>python311Packages.laspy</li>
    <li>python311Packages.laszip</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.phonopy</li>
    <li>python311Packages.pymatgen</li>
    <li>python311Packages.scikit-build-core</li>
    <li>python311Packages.seekpath</li>
    <li>python311Packages.spglib</li>
    <li>python311Packages.sumo</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.vector</li>
  </ul>
</details>

**Comment by bcdarwin** [comment]
@natsukium I've restored part of the previous `postPatch` to address this, but could also change `pytestFlagsArray` if preferred.

**Review by natsukium — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
