### PR TITLE
all-packages.nix: move defaults to package files continues^3

### PR DESCRIPTION
**Pull request by oxij**
# What? Why?

A continuation of #55129, #55732, and #56026. Yet another noop.

# `git log`

- *: move defaults to package file

A whole bunch of these.

# `nix-instantiate` environment

- Host OS: Linux 4.9, SLNOS 19.03
- Nix: nix-env (Nix) 2.1.3
- Multi-user: yes
- Sandbox: yes
- NIXPKGS_CONFIG:

```nix
{
  checkMeta = true;
  doCheckByDefault = true;
}
```

# `nix-env -qaP` diffs

- On x86_64-linux: noop
- On aarch64-linux: noop
- On x86_64-darwin: noop

/cc @7c6f434c from #55129 and @bendlas, @volth, @samueldr from #55732

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg eval

**Comment by dasJ** [comment]
Things that are also changed:

blueman: `withPulseAudio ? config.pulseaudio or stdenv.isLinux` instead of `withPulseAudio = config.pulseaudio or true;`
wxgtk: `withMesa ? libGLSupported` instead of `withMesa = lib.elem stdenv.hostPlatform.system lib.platforms.mesaPlatforms;`
mpv: `stdenv.isLinux` instead of `!stdenv.isDarwin;`

All of this is probably okay, but I wanted to mention it

**Comment by 7c6f434c** [comment]
`libGLSupported` is defined to be precisely the `mesaPlatforms` check.

(The two other things seem to be changes; good ones, in my opinion).

**Comment by oxij** [comment]
@dasJ

> wxgtk

`libGLSupported` is defined as `lib.elem stdenv.hostPlatform.system lib.platforms.mesaPlatforms` in `all-packages.nix` :)

> blueman, mpv

Yes, these are fixes for `system`s not built by hydra and ofborg. Outside Linux (and emulation of Linux by FreeBSD and Illumos) people don't normally run PulseAudio and only Linux (and emulations) has ALSA. But these are a noop for stuff hydra builds.

**Comment by oxij** [comment]
Thanks!

**Comment by dasJ** [comment]
@oxij As I said I think the changes are probably okay, but I wanted to point that out to a potential merger

**Comment by 7c6f434c** [comment]
@dasJ yes, thanks for attentive checking — and I think it was only natural for @oxij to put the reasoning on record if the changes were mentioned.

**Pull request merged**
