### PR TITLE
gnomeExtensions: refactor update script

### PR DESCRIPTION
**Pull request by tu-maurice**
###### Description of changes

The update-extensions.py script downloads extension information once for each
shell version, although one extension version might be used for multiple shell
versions. To reduce the amount of downloads we first select the appropriate
extension version per shell version as done before, then download the
corresponding information once for each selected extension version, and finally
map each shell version to the downloaded information of the selected extension
version.

Pinging @piegamesde because they seem to have written the code.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
CC  @rhoriguchi as de-facto maintainer, please take a look.

----

Out of curiosity, do you have some numbers how many downloads this saves?

**Comment by tu-maurice** [comment]
I just noticed a lot of duplicate versions printed while I was updating that extensions.json locally, and since each download took about a second for me it was a bit infuriating, so I changed it.

I didn't have any numbers to answer your question @piegamesde , so I wrote this handy script which uses the extensions.json as input and counts duplicates in shell_version_map by the version field:

https://gist.github.com/tu-maurice/3d84f3f64981f4a2ce8f2007873710ea

It shows this for my updated local version of the extensions.json

`1833 downloads of which 899 were unwarrented.`

So my answer is: about half.

**Comment by rhoriguchi** [comment]
> CC @rhoriguchi as de-facto maintainer, please take a look.
> 
> Out of curiosity, do you have some numbers how many downloads this saves?

I can't give you a download number, but it takes around 10-20 minutes to update.

**Comment by tu-maurice** [comment]
I think the question was for me :)

**Pull request merged**
