### PR TITLE
libwebsockets: remove runtime reference to GCC (closure size)

### PR DESCRIPTION
**Pull request by vobloeb**
cc @Mindavi @fabaff

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130622` at 1a40d6e3 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built successfully:</summary>
  <ul>
    <li>ardour</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>domoticz</li>
    <li>driftnet</li>
    <li>janus-gateway</li>
    <li>libwebsockets (libwebsockets_4_2)</li>
    <li>libwebsockets_3_1</li>
    <li>libwebsockets_3_2</li>
    <li>mosquitto</li>
    <li>ttyd</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130622` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>ardour</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>domoticz</li>
    <li>driftnet</li>
    <li>janus-gateway</li>
    <li>libwebsockets (libwebsockets_4_2)</li>
    <li>libwebsockets_3_1</li>
    <li>libwebsockets_3_2</li>
    <li>mosquitto</li>
    <li>ttyd</li>
  </ul>
</details>

**Comment by Mindavi** [comment]
I think setting `-DLWS_WITHOUT_TESTAPPS=ON` also would've worked, but I guess this is fine.

**Comment by siraben** [comment]
I think the tests should be kept but the unnecessary references to GCC removed

**Pull request merged**
