### PR TITLE
portfolio-filemanager: init at 0.9.10

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by taku0** [comment]
- Resulting executable filename is `dev.tchx86.Portfolio`. Is this intended?
- I cannot open ZIP files.
- Does this work on macOS? If not, set `meta.platforms`.

**Comment by Artturin** [comment]
> Resulting executable filename is `dev.tchx86.Portfolio`. Is this intended?

yes https://github.com/tchx84/Portfolio/blob/4174bfa1f827d6162b14a7977ef46c9a5f96fbea/src/meson.build#L24

the aur package symlinks it to `portfolio` https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=portfolio-file-manager#n27
i think we should symlink it to `porthfolio-filemanager` since `bin/portfolio` already exists in pkgs.portfolio

**Comment by dotlambda** [comment]
> i think we should symlink it to `portfolio-filemanager` since `bin/portfolio` already exists in pkgs.portfolio

It seems unlikely someone's gonna install both `portfolio` and `portfolio-filemanager`. I'd prefer symlinking it to `portfolio`.

**Comment by dotlambda** [comment]
> * Does this work on macOS?

I doubt it, since libhandy only works on Linux. But once all dependencies are available for macOS, I don't see why this wouldn't work on macOS. I'll set `meta.platforms` anyway.

**Comment by Artturin** [comment]
use `buildPythonApplication` and `python3Packages` instead of `python3.pkgs.` like here https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/misc/flashfocus/default.nix

doesn't start on my pinephone but starts on my nixos pc
```
Traceback (most recent call last):
  File "/nix/store/f9bh9pwgdnpvxyddknhjkh4gsin9yps6-portfolio-0.9.10/lib/python3.8/site-packages/portfolio/main.py", line 61, in do_activate
    win = PortfolioWindow(application=self)
  File "/nix/store/f9bh9pwgdnpvxyddknhjkh4gsin9yps6-portfolio-0.9.10/lib/python3.8/site-packages/portfolio/window.py",line 120, in __init__
    self._setup()
  File "/nix/store/f9bh9pwgdnpvxyddknhjkh4gsin9yps6-portfolio-0.9.10/lib/python3.8/site-packages/portfolio/window.py",line 189, in _setup
    places = PortfolioPlaces()
  File "/nix/store/f9bh9pwgdnpvxyddknhjkh4gsin9yps6-portfolio-0.9.10/lib/python3.8/site-packages/portfolio/places.py",line 56, in __init__
    self._setup()
  File "/nix/store/f9bh9pwgdnpvxyddknhjkh4gsin9yps6-portfolio-0.9.10/lib/python3.8/site-packages/portfolio/places.py",line 102, in _setup
    os.path.basename(self.XDG_DOWNLOAD),
  File "/nix/store/jhac19hl1qq3qgrna4y06v1kyngszlvb-python3-3.8.8/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by dotlambda** [comment]
> use `buildPythonApplication` and `python3Packages` instead of `python3.pkgs.` like here https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/misc/flashfocus/default.nix

No. If you want to override a package, you actually override `python3`. That's why passing `python3` feels more natural. Also, in case you ever need `python3` in the future, this is the way to go to avoid changing the interface for people who override something.

**Comment by dotlambda** [comment]
> doesn't start on my pinephone but starts on my nixos pc

I don't get that at all: `if self._has_permission_for(self.DOWNLOAD_PERMISSION) and self.XDG_DOWNLOAD` should make sure that `self.XDG_DOWNLOAD` is not `None`. Would you mind investigating and filing an upstream issue?
Could it be an issue with mobile-nixos?

**Comment by Artturin** [comment]
oh yeah i dont have the xdg dirs because i just renamed my user so i got a new home \:P
i used `xdg-user-dirs-update` to generate them and now it worked

**Comment by Artturin** [comment]
its been fixed in master https://github.com/tchx84/Portfolio/pull/143

**Review by Artturin — APPROVED** [review]
works on my desktop and pinephone

**Review by samueldr — APPROVED** [review]

**Comment by samueldr** [comment]
I don't see any issues.

I have no opinion about the python3 / buildPythonPackages thing previously mentioned.

**Pull request merged**
