### PR TITLE
odin: dev-2023-08 -> dev-2023-11

### PR DESCRIPTION
**Pull request by znaniye**
## Description of changes

odin: dev-2023-08 -> dev-2023-11
ols: nightly-2023-07-09 -> nightly-unstable-2023-11-04

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 266265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>odin</li>
    <li>ols</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
```
╰─λ ./results/odin/bin/odin version
./results/odin/bin/odin version dev-2023-11
─λ echo hello | ./results/ols/bin/ols
Content-Length: 105

{"jsonrpc": "2.0", "method": "window/logMessage", "params": {"type": 1, "message": "No carriage return"}}Content-Length: 118
```

**Review by fufexan — APPROVED** [review]

**Review by thiagokokada — CHANGES_REQUESTED** [review]
Please fix your commits.

Each package bump should go to a different commit. Also, the commit messages of each commit should follow our [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions).

**Comment by AndersonTorres** [comment]
Do the basics.

**Comment by znaniye** [comment]
> Please fix your commits.
> 
> Each package bump should go to a different commit. Also, the commit messages of each commit should follow our [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions).

ols should be updated simultaneously as it is updated in tandem with the odin compiler, that's why i put the two files changes in the same commit, in the last version of Odin Sandro accepted a PR like mine, but do you want me to change it anyway? no problem too

**Comment by thiagokokada** [comment]
> > Please fix your commits.
> > Each package bump should go to a different commit. Also, the commit messages of each commit should follow our [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions).
> 
> ols should be updated simultaneously as it is updated in tandem with the odin compiler, that's why i put the two files changes in the same commit, in the last version of Odin Sandro accepted a PR like mine (#242632), but do you want me to change it anyway? no problem too

Even in those cases it is better to have separate commits because this ensures that OfBorg will build both packages.

**Pull request closed without merging**
