### PR TITLE
github-cli: init at 0.6.2

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by xeji** [comment]
```
$ ls /nix/store/7043awwgm51xkf8y1qd2aaqajcy3i77y-github-cli-0.6.2/bin
bundle  bundler  gcli  rackup
```

Should the other binaries except `gcli` really be there?

**Comment by offlinehacker** [comment]
Ahh makes, sense, have to fix this.

**Comment by vcunat** [comment]
I wonder if this would make more sense to put into `gitAndTools`, along with `.hub` and others...

**Review by ryantm — CHANGES_REQUESTED** [review]
extra binaries need to be removed

**Comment by mmahut** [comment]
@offlinehacker any update on this?

**Comment by mmahut** [comment]
Closing given lack of activity, reopen this if needed.

**Pull request closed without merging**
