### PR TITLE
redmine: 3.4.8 -> 3.4.9 & 4.0.1 -> 4.0.2

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Minor version bump. I guess technically at this point this is a 19.03 backport as well.

http://www.redmine.org/projects/redmine/wiki/Changelog_3_4
http://www.redmine.org/projects/redmine/wiki/Changelog_4_0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test redmine_3 redmine_4

**Comment by aanderse** [comment]
Note: doesn't build on aarch64-linux because of recurring issues with darcs

**Comment by aanderse** [comment]
@7c6f434c mind taking a look at this PR?

As mentioned above a cherry pick to 19.03 would also be appreciated.

**Comment by 7c6f434c** [comment]
I guess with some imagination I can indeed stretch this as a data integrity (URL escaping!) fix… 98215e4553c

**Pull request merged**
