### PR TITLE
linuxPackages.evdi: 1.14.1 -> 1.14.1-unstable-2024-01-30

### PR DESCRIPTION
**Pull request by illustris**
## Description of changes

Update evdi to fix building on 6.6: https://github.com/DisplayLink/evdi/commit/495e8cffbf62f6809108442999084213b014e9e0

## Things done

I've built and tested with two monitors on kernel version 6.6.10.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by illustris** [comment]
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/279565

21 packages built:
displaylink linuxKernel.packages.linux_4_19.evdi linuxKernel.packages.linux_4_19_hardened.evdi linuxKernel.packages.linux_5_10.evdi linuxKernel.packages.linux_5_10_hardened.evdi linuxKernel.packages.linux_5_15.evdi linuxKernel.packages.linux_5_15_hardened.evdi linuxKernel.packages.linux_5_4.evdi linuxKernel.packages.linux_5_4_hardened.evdi linuxKernel.packages.linux_6_1.evdi linuxKernel.packages.linux_hardened.evdi linuxKernel.packages.linux_6_5.evdi linuxKernel.packages.linux_6_5_hardened.evdi linuxKernel.packages.linux_6_6.evdi linuxKernel.packages.linux_6_6_hardened.evdi linuxKernel.packages.linux_latest_libre.evdi linuxKernel.packages.linux_libre.evdi linuxKernel.packages.linux_lqx.evdi linuxKernel.packages.linux_xanmod.evdi linuxKernel.packages.linux_xanmod_latest.evdi linuxKernel.packages.linux_zen.evdi
```

**Comment by drupol** [comment]
Hello,

I would like to merge this PR, but, I see that there has been newer commit upstream since then.

Do you think you could update your PR, so I can merge it?

**Comment by illustris** [comment]
I will test this with a displaylink dock tomorrow.

```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/279565

3 packages failed to build:
linuxKernel.packages.linux_4_19_hardened.evdi linuxKernel.packages.linux_5_10_hardened.evdi linuxKernel.packages.linux_5_4_hardened.evdi
```

These broken versions are already broken on master: https://hydra.nixos.org/build/247989246

**Comment by drupol** [comment]
Question, shouldn't the `version` be formatted as such (_with a prefix `0-`_): https://github.com/NixOS/nixpkgs/pull/280312/files

**Comment by illustris** [comment]
This seems to be a recent change. I'll update the PR.

**Comment by drupol** [comment]
@illustris Is it ok for you to merge?

**Comment by illustris** [comment]
Yes, tested on a displaylink dock today

**Pull request merged**
