### PR TITLE
python3Packages.ipython: disable clipboard test on darwin

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/157584#issuecomment-1037060879

Probably to big to into master, but easier to test on master. Can be rebased later.

cc @NixOS/darwin-maintainers please test

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Uh, one of the parameters that would better not change hash if added with an empty list :-/  But... with `null` it wouldn't be extremely ugly and it would avoid rebuild except where needed (and failed anyway).

**Comment by mweinelt** [comment]
Wondering if the solution is as simple as

```patch
diff --git a/pkgs/development/interpreters/python/hooks/pytest-check-hook.sh b/pkgs/development/interpreters/python/hooks/pytest-check-hook.sh
index 0f708f88829..26aa614426e 100644
--- a/pkgs/development/interpreters/python/hooks/pytest-check-hook.sh
+++ b/pkgs/development/interpreters/python/hooks/pytest-check-hook.sh
@@ -33,12 +33,12 @@ function pytestCheckPhase() {
 
     # Compose arguments
     args=" -m pytest"
-    if [ -n "$disabledTests" ]; then
+    if [ "${#disabledTests[@]}" -gt 0 ]; then
         disabledTestsString=$(_pytestComputeDisabledTestsString "${disabledTests[@]}")
       args+=" -k \""$disabledTestsString"\""
     fi
 
-    if [ -n "${disabledTestPaths-}" ]; then
+    if [ "${#disabledTestPaths[@]}" -gt 0 ]; then
         eval "disabledTestPaths=($disabledTestPaths)"
     fi
 
```

**Comment by vcunat** [comment]
The solution has to be in evaluation time, i.e. shell can't do it.  On a quick glance, replacing empty lists by `null` values might even be a reasonable default for `mkDerivation` and similar functions.

**Comment by vcunat** [comment]
Anyway, let's try this particular build
@OfBorg build python3Packages.ipython

**Review by risicle — APPROVED** [review]
WFM macos 10.15

**Comment by mweinelt** [comment]
Rebased, sorry for the noise. Need to learn how to do it properly I guess.

**Pull request merged**
