### PR TITLE
oneDNN: 2.0 -> 2.1

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changelog:

https://github.com/oneapi-src/oneDNN/releases/tag/v2.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 113488` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>oneDNN</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Testing another alpha feature:

oneDNN: Ask if ouput path lib (46.2M) could be split with outputs = [ ... "lib" ];

**Comment by danieldk** [comment]
> Testing another alpha feature:
> 
> oneDNN: Ask if ouput path lib (46.2M) could be split with outputs = [ ... "lib" ];

Not sure I follow, this derivation already uses split outputs.

**Comment by SuperSandro2000** [comment]
Right. I think the check requires more work.

**Pull request merged**
