### PR TITLE
Bump powershell

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes: #84454

enables darwin usage

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SRGOM** [comment]
Hi, thanks for this. Sorry I couldn't look earlier (Might sound luddite but I don't check email regularly ... :(  )

**Comment by SRGOM** [comment]
I reviewed: https://github.com/NixOS/nixpkgs/pull/86423/commits/e4bb796e3e16f8186d9ff8ca16bb18134a9345fb 

Instructions for a first time reviewer (such as me):

```
git remote add someRandomName  <repo=https://github.com/jonringer/nixpkgs>
git fetch --depth 2 sameRandomName <commitid=e4bb796e3e16f8186d9ff8ca16bb18134a9345fb>
git checkout <commitid=e4bb796e3e16f8186d9ff8ca16bb18134a9345fb >

```
Checking the diffs in vim with whitespace removed shows that the only changes are:

1)  removing the `-f` flag from rm 
2) making the file extension platform dependant.

I can confirm that this is fine for Linux.

**Review by SRGOM — APPROVED** [review]

**Comment by jonringer** [comment]
Yea, i was able to get it to work fine on Linux as well. I just want to ensure that I'm not causing a regression to darwin, which previously worked.

Wish they would use a newer version of openssl by default. Would make a lot of this a lot easier

**Review by SRGOM — APPROVED** [review]

**Comment by SRGOM** [comment]
Using a passed library and gating the deletion check on non-darwin env.

 Presuming, (somewhat obviously) that you've tested this on Darwin. Approved.

**Review by SRGOM — APPROVED** [review]
I see in `vi` `doInstallCheck` and an `installCheck` added. Approved.

**Comment by jonringer** [comment]
passes on darwin, merging :)

**Comment by dasJ** [comment]
@jonringer Does this qualify for a backport to 20.03? It doesn't eval there because OpenSSL is insecure.

**Comment by SRGOM** [comment]
Don't know the backporting policy but @dasJ you can consider using unstable for powershell.

**Comment by jonringer** [comment]
@dasJ Unless there's a major security vulnerability, I think not issuing another major version would be wise for the release branch

**Pull request merged**
