### PR TITLE
update some coreboot-related packages

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by petabyteboy** [comment]
Some Xen stuff fails to build, I will have a look if this is caused by the seabios update or if it was failing before.

**Comment by petabyteboy** [comment]
cc @tstrobel @gnidorah @cryptix

**Comment by petabyteboy** [comment]
Actually the xen 4.10 packages failed to build even before the seabios update, so we should be ok

**Review by ghost — APPROVED** [review]
updated intelmetool works for me

**Comment by petabyteboy** [comment]
I will replace this with a PR merging all coreboot util packages into one for easier maintenance in the future.

**Comment by petabyteboy** [comment]
superseeded by https://github.com/NixOS/nixpkgs/pull/67836

**Pull request closed without merging**
