### PR TITLE
varnish: update & fix

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
Get our varnish packaging into a better shape. Replaces #131512

cc @risicle 

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fpletz — APPROVED** [review]
Thanks! IMHO we can also backport this like it is to 21.05 due to the security implications. But the release notes changes should be for 21.05 then. What do you think?

**Comment by risicle** [comment]
I note that 6.6 has an EOL of 2022-03-15, which is before when our _next_ release would go EOL. So if we're saying we can't have versions which are EOL, then there seems little point in adding a version that won't make it into a single release.

**Comment by ajs124** [comment]
I totally agree, I just couldn't find a good source for varnish release management, tbh.
I dropped varnish66, everything else should be as before.

**Comment by ajs124** [comment]
> Thanks! IMHO we can also backport this like it is to 21.05 due to the security implications. But the release notes changes should be for 21.05 then. What do you think?

We already have the patches fixing the security issue on the release branch now and upgrading from 6.3.x to 6.5.x is a breaking change IMO, so I'd rather not do it on the release branch.

**Comment by ajs124** [comment]
I don't want to have to rebase this a bunch more times. @risicle do these changes seem alright to you? If so, I'll rebase and merge.

**Comment by risicle** [comment]
Yes, please do!

**Pull request merged**
