### PR TITLE
python: tensorflow: 1.11 -> 1.13

### PR DESCRIPTION
**Pull request by averelld**
###### Motivation for this change
Best thing here is the dropped python3.7 restriction. Not sure about all the old-version cruft, it's not in use, but maybe it's being left in for easier overrides?
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
@averelld to clarify this means that with this commit `python37Packages.tensorflow` will be available?

**Comment by averelld** [comment]
Yes, exactly, "Support for Python3.7 on all operating systems." is new in TF 1.13.

**Comment by averelld** [comment]
Closing in favor of #56515 which is more thorough.

**Comment by jyp** [comment]
The python 3.7 support isn't in #56515 
Do you think that you could rebase your PR over it? @averelld

**Comment by averelld** [comment]
@jyp Sure, here: averelld/nixpkgs@0e06f4c5f30930016413bc472184632872e40577 but there's just the missing if and the new hashes :)

**Pull request closed without merging**
