### PR TITLE
Add mingw32 support libtheora

### PR DESCRIPTION
**Pull request by seanybaggins**
## Description of changes
Add mingw support for libthoera

Part of a larger effort to provide mingw support for qtmultimedia

Relevant for https://github.com/NixOS/nixpkgs/issues/274274

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by seanybaggins** [comment]
@ofborg build pkgs.pkgsCross.mingwW64.libtheora

**Comment by seanybaggins** [comment]
@wegank :)

**Comment by seanybaggins** [comment]
https://github.com/ofborg build pkgs.pkgsCross.mingw32.libtheora

**Comment by seanybaggins** [comment]
@ofborg build pkgs.pkgsCross.mingwW64.libtheora

**Review by wegank — APPROVED** [review]

**Comment by Artturin** [comment]
Please explain why it's needed and if the fix can be upstreamed

**Comment by seanybaggins** [comment]
**Why its needed**
1. Mentioned in the commit message "Part of a larger effort to add mingw support for qtmultimedia"
2. A patch was added so there wasn't a link error. EXPORT doesn't seem to be understood by the linker used in stdenv
3. See linked issue https://github.com/NixOS/nixpkgs/issues/274274

**Can it be upstreamed?**
Yes. Originally got all the overlays working against 23.11. See https://github.com/seanybaggins/qt-package-overalys/tree/bcd044bdba9be492e4694d096edb0bb4e9dbb027

**Comment by wegank** [comment]
The patch is [exactly what MSYS2 does](https://github.com/msys2/MINGW-packages/blob/c36052a370fe048a18d04d3a7f6209c0a751c413/mingw-w64-libtheora/PKGBUILD#L29-L30). Without it, the build fails with

```
/nix/store/fkvahdxdgk0s8576ww08wbb5ffmiws75-x86_64-w64-mingw32-binutils-2.40/bin/x86_64-w64-mingw32-ld: .libs/libtheoradec-1.dll.def:3: syntax error
/nix/store/fkvahdxdgk0s8576ww08wbb5ffmiws75-x86_64-w64-mingw32-binutils-2.40/bin/x86_64-w64-mingw32-ld:.libs/libtheoradec-1.dll.def: file format not recognized; treating as linker script
/nix/store/fkvahdxdgk0s8576ww08wbb5ffmiws75-x86_64-w64-mingw32-binutils-2.40/bin/x86_64-w64-mingw32-ld:.libs/libtheoradec-1.dll.def:2: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:687: libtheoradec.la] Error 1
```

I think the patch can be upstreamed, but upstream doesn't seem to be active: https://github.com/xiph/theora

**Comment by seanybaggins** [comment]
Pinging. Can we get this merged?

**Pull request merged**
