### PR TITLE
arrow-cpp: 9.0.1 -> 11.0.0

### PR DESCRIPTION
**Pull request by tobim**
###### Description of changes

Based on #198805. Fixed the merge conflicts and did another bump to 11.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Closes: #198805

### CODE REVIEW

**Comment by cpcloud** [comment]
LGTM, but the aarch64-linux builds are failing because of arrow's cxx17 requirement.

**Comment by tobim** [comment]
I propose we mark aarch64-linux as broken until that is sorted out. (#209870 and a follow up bump of the default gcc, I think.)

**Comment by tobim** [comment]
I recommend to rebase onto master (with a few conflicts) before running `nixpkgs-review` here.
I rebuilt up to `pyarrow` on staging and had to disable checks for `libarchive`, `e2fsprogs`, and `python3Packages.ephemeral-port-reserve` to get there.

**Comment by veprbl** [comment]
This should be rebased on master.

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 213324` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>24 packages marked as broken and skipped:</summary>
  <ul>
    <li>intensity-normalization</li>
    <li>napari</li>
    <li>python310Packages.boxx</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.caffe</li>
    <li>python310Packages.caffeWithCuda</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dask-jobqueue</li>
    <li>python310Packages.dask-yarn</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.intensity-normalization</li>
    <li>python310Packages.mask-rcnn</li>
    <li>python310Packages.napari</li>
    <li>python310Packages.pywick</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.rl-coach</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.streamz</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python310Packages.zcs</li>
  </ul>
</details>
<details>
  <summary>89 packages failed to build:</summary>
  <ul>
    <li>arrow-cpp</li>
    <li>arrow-glib</li>
    <li>databricks-sql-cli</li>
    <li>easyocr (python310Packages.easyocr)</li>
    <li>gnuradio</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.gnuradio</li>
    <li>gnuradio3_8Packages.grnet</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gnuradio3_9</li>
    <li>gnuradio3_9Packages.gnuradio</li>
    <li>gnuradio3_9Packages.grnet</li>
    <li>gnuradioPackages.gnuradio</li>
    <li>openai-whisper (python310Packages.openai-whisper)</li>
    <li>parquet-tools</li>
    <li>python310Packages.apache-beam</li>
    <li>python310Packages.aplpy</li>
    <li>python310Packages.autofaiss</li>
    <li>python310Packages.batchgenerators</li>
    <li>python310Packages.casa-formats-io</li>
    <li>python310Packages.clifford</li>
    <li>python310Packages.dask</li>
    <li>python310Packages.dask-gateway</li>
    <li>python310Packages.dask-glm</li>
    <li>python310Packages.dask-image</li>
    <li>python310Packages.dask-ml</li>
    <li>python310Packages.dask-mpi</li>
    <li>python310Packages.databricks-sql-connector</li>
    <li>python310Packages.datafusion</li>
    <li>python310Packages.datasets</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.db-dtypes</li>
    <li>python310Packages.devito</li>
    <li>python310Packages.distributed</li>
    <li>python310Packages.dremel3dpy</li>
    <li>python310Packages.embedding-reader</li>
    <li>python310Packages.env-canada</li>
    <li>python310Packages.glymur</li>
    <li>python310Packages.google-cloud-bigquery</li>
    <li>python310Packages.handout</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.image-match</li>
    <li>python310Packages.imagecorruptions</li>
    <li>python310Packages.imageio</li>
    <li>python310Packages.intake</li>
    <li>python310Packages.intake-parquet</li>
    <li>python310Packages.moviepy</li>
    <li>python310Packages.napari-console</li>
    <li>python310Packages.napari-svg</li>
    <li>python310Packages.pandas-stubs</li>
    <li>python310Packages.pims</li>
    <li>python310Packages.psd-tools</li>
    <li>python310Packages.pyarrow</li>
    <li>python310Packages.pyfftw</li>
    <li>python310Packages.pyvista</li>
    <li>python310Packages.recordlinkage</li>
    <li>python310Packages.runway-python</li>
    <li>python310Packages.scikitimage</li>
    <li>python310Packages.sfepy</li>
    <li>python310Packages.slicedimage</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.sparse</li>
    <li>python310Packages.spectral-cube</li>
    <li>python310Packages.stanza</li>
    <li>python310Packages.stumpy</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.tensorly</li>
    <li>python310Packages.test-tube</li>
    <li>python310Packages.tifffile</li>
    <li>python310Packages.tokenizers</li>
    <li>python310Packages.transformers</li>
    <li>python311Packages.apache-beam</li>
    <li>python311Packages.autofaiss</li>
    <li>python311Packages.databricks-sql-connector</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datasets</li>
    <li>python311Packages.db-dtypes</li>
    <li>python311Packages.embedding-reader</li>
    <li>python311Packages.google-cloud-bigquery</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.pandas-stubs</li>
    <li>python311Packages.pyarrow</li>
    <li>python311Packages.recordlinkage</li>
    <li>python311Packages.tokenizers</li>
    <li>python311Packages.transformers</li>
    <li>streamlit</li>
    <li>thrift</li>
  </ul>
</details>

**Comment by veprbl** [comment]
^ failed on python3.10-cffi

**Comment by tobim** [comment]
> This should be rebased on master.

Rebased and retargeted now.

> ^ failed on python3.10-cffi

Can you try again?

**Comment by veprbl** [comment]
> > ^ failed on python3.10-cffi
> 
> Can you try again?

That won't work until #214010 lands on master.

**Review by veprbl — APPROVED** [review]
Diff LGTM

**Comment by wegank** [comment]
@veprbl Would you please test if the standard workaround of using `gcc12Stdenv` and passing `-lgcc` to `NIX_LDFLAGS` on aarch64-linux works?

**Comment by veprbl** [comment]
> @veprbl Would you please test if the standard workaround of using `gcc12Stdenv` and passing `-lgcc` to `NIX_LDFLAGS` on aarch64-linux works?

This looks like quite a rabithole. Are you a user of arrow-cpp on aarch64?

**Comment by wegank** [comment]
> > @veprbl Would you please test if the standard workaround of using `gcc12Stdenv` and passing `-lgcc` to `NIX_LDFLAGS` on aarch64-linux works?
> 
> This looks like quite a rabithole. Are you a user of arrow-cpp on aarch64?

I'm maintaining `python3Packages.pyvista`, which [seems to be affected](https://gist.github.com/f18754a479d225070832cb69e931766f) somehow.

**Comment by veprbl** [comment]
```
% nix why-depends --derivation nixpkgs#python3Packages.pyvista nixpkgs#arrow-cpp
/nix/store/qnqv1zcbs3vhba4i110l7qpsqxpj9f0m-python3.10-pyvista-0.37.0.drv
└───/nix/store/y258hn1sbvyxd68xvchkiimsiy8hydjs-python3.10-imageio-2.25.0.drv
    └───/nix/store/zx2p0s1ga5911z825s7bv3mr4j5c5r60-python3.10-tifffile-2022.10.10.drv
        └───/nix/store/qydnm6d29sg1zjjn9570yig4jyx0nk3n-python3.10-dask-2023.1.0.drv
            └───/nix/store/pzrwychaqf79l5yf8r1ysdlh00c1fwlh-python3.10-pyarrow-9.0.0.drv
                └───/nix/store/pb4lndv3brkvnb96q1bq98g65h1b2jjz-arrow-cpp-9.0.0.drv
```

**Comment by tobim** [comment]
`tifffile` needs `dask` for tests only. We can remove that input and the test scaffold will automatically skip the affected tests. I just verified that this change is enough to fix the build.

Should we do this in general, only for the affected platform, or is it a bad idea?

**Comment by wegank** [comment]
> `tifffile` needs `dask` for tests only. We can remove that input and the test scaffold will automatically skip the affected tests. I just verified that this change is enough to fix the build.
> 
> Should we do this in general, only for the affected platform, or is it a bad idea?

There are over 20 packages that depend directly on `python3Packages.dask`, I guess the change is still too specific and doesn't help to unbreak other packages (that I don't maintain).

**Comment by tobim** [comment]
> There are over 20 packages that depend directly on python3Packages.dask, I guess the change is still too specific and doesn't help to unbreak other packages (that I don't maintain).

Let's check how many of those are not optional first.
That said, I wouldn't want to introduce an abstraction just for those 20, let's rather be explicit and remove the `dask` dependency where it isn't needed. Until `aarch64-linux` works again, of course.

**Comment by veprbl** [comment]
@GrahamcOfBorg build python3Packages.pyvista

**Comment by veprbl** [comment]
@GrahamcOfBorg build python3Packages.pyvista

**Comment by veprbl** [comment]
@GrahamcOfBorg build python3Packages.pyvista

**Comment by tobim** [comment]
I learned that arrow gained support for system jemalloc in https://github.com/apache/arrow/pull/13373. Should we switch to that in this PR still?

**Comment by veprbl** [comment]
@tobim Let's follow up in another PR.

**Pull request merged**
