### PR TITLE
stirling-pdf: 0.30.1 -> 0.33.1

### PR DESCRIPTION
**Pull request by TomaSajt**
https://github.com/Stirling-Tools/Stirling-PDF/releases

https://github.com/Stirling-Tools/Stirling-PDF/releases/tag/v0.32.0
https://github.com/Stirling-Tools/Stirling-PDF/releases/tag/v0.33.0
https://github.com/Stirling-Tools/Stirling-PDF/releases/tag/v0.33.1

The web app opens as expected

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by BonusPlay — APPROVED** [review]
Built on `x86_64-linux`, seems to be working.

**Comment by TomaSajt** [comment]
Rebased on master, since OfBorg seemed to error out for some reason.
Maybe it works correctly now.

**Review by tomodachi94 — COMMENTED** [review]
Could you update this from `gradle_7` to `gradle` or `gradle_8`? Upstream has been using it [since v1.0.1](https://github.com/Stirling-Tools/Stirling-PDF/commit/250c317155a4eca056c9113d0498a99d2f9aa32a), and I'm [trying to remove uses of Gradle 7 to make the removal easier when Gradle 9 is inevitably released](https://github.com/NixOS/nixpkgs/issues/358845).

~~The only reason I ask here is because `deps.json` will need to be updated.~~ (Ignore that, I mixed this up with Maven.) This is **non-blocking**, and I'm happy to make a followup that does the upgrade.

**Review by tomodachi94 — APPROVED** [review]
Lgtm, but please see above.

**Pull request merged**
