### PR TITLE
pyfa: 2.60.2 -> 2.61.0

### PR DESCRIPTION
**Pull request by Daholli**
Refactor to use source files + update to newest version

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ToasterUwU** [comment]
Simple little Question: Have you confirmed the official appimage works via appimage-run?

Last time we had this issue and then fixed it was by using a newer version that had a fix for this issue, because it was upstream. Maybe it is again?

**Comment by Daholli** [comment]
I tried running the new wrapped Image and it didn't work, haven't tried appimage run yet

**Comment by Daholli** [comment]
@ToasterUwU check this out, it is working from source, but I dont know how to get it to work as a `./result/bin/pyfa` but it does work when running it as `./result/bin/pyfa/pyfa.py`

**Comment by paschoal** [comment]
sorry to put one more rock on top of it, it seems there are more dependencies missing.

ran into this error whenever trying to run any of the import functionalities.
```
(pyfa.py:779985): GLib-GIO-ERROR **: 16:43:03.860: No GSettings schemas are installed on the system
```

**Comment by Daholli** [comment]
> sorry to put one more rock on top of it, it seems there are more dependencies missing.
> 
> ran into this error whenever trying to run any of the import functionalities.
> 
> ```
> (pyfa.py:779985): GLib-GIO-ERROR **: 16:43:03.860: No GSettings schemas are installed on the system
> ```

no worries, gonna look into it, just give me some time because this is the first "real" package I have to make

**Comment by paschoal** [comment]
take your time, i'm also experimenting to see if I can help you with it.
will post in case I get anything useful.

**Comment by ToasterUwU** [comment]
I will chime in tommorow as well most likely. Today was plagued by Jellyfin issues beyond my comprehension.

**Comment by paschoal** [comment]
hey, I managed to get a nice packaged stable version running with the following [eve/default.nix](https://github.com/paschoal/dotfiles/blob/master/games/eve/default.nix)
with the gsettings error and the pixbuf warning solved, still need to spruce it up a bit on the installPhase tho.

feel free to copy whatever or let me know and I can add the comments here as suggestions.

**Comment by Daholli** [comment]
> hey, I managed to get a nice packaged stable version running with the following [eve/default.nix](https://github.com/paschoal/dotfiles/blob/master/games/eve/default.nix) with the gsettings error and the pixbuf warning solved, still need to spruce it up a bit on the installPhase tho.
> 
> feel free to copy whatever or let me know and I can add the comments here as suggestions.

That looks really good, should i just close my pr and you open one with these changes?

**Comment by ToasterUwU** [comment]
Im also busy on all ends sadly. So feel free to make a PR for your changes, I will be around to review, but I don't have time do the PR myself.

**Comment by paschoal** [comment]
added the changes at PR [#356622](https://github.com/NixOS/nixpkgs/pull/356622)

**Pull request closed without merging**
