### PR TITLE
rambox: fix build

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Hashes for sencha 6.5.3 vs 6.5.3.6 are the same? Just checking :).

**Comment by gnidorah** [comment]
@dtzWill yep, checked both x64 and i386 targets

**Comment by xeji** [comment]
@GrahamcOfBorg  build rambox

**Comment by gnidorah** [comment]
@xeji no way man. sencha depency is unfree software

**Comment by xeji** [comment]
Anyway, builds fine on my local box :smile:

**Comment by gnidorah** [comment]
@dtzWill Thank you! Could you please merge my friend first PR (trivial two-line change) #42516 His user demand on it - the faster it will be in nixpkgs - the better :smile:

**Pull request merged**
