### PR TITLE
squeekboard: init at unstable-2021-03-09

### PR DESCRIPTION
**Pull request by Artturin**
squeekboard is a virtual keyboard that works on wayland

the stable release v1.12.0 is not used because of this useful commit https://source.puri.sm/Librem5/squeekboard/-/commit/a265427e8ec0bf00ce7fdb7caaff0396d0456599

i tested on x86_64 and aarch64

tagging #88767

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
@archseer @masipcat do either of you want to be added as a maintainer?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116253` at c593f1d3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build (new failures):</summary>
  <ul>
    <li><a href="https://gist.github.com/465556308f2028d1aff9561f8d84e627">squeekboard</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `makeWrapper`.
Near pkgs/applications/accessibility/squeekboard/default.nix:15:3:
```
   |
15 | , makeWrapper
   |   ^
```
</li>
  </ul>
</details>

**Comment by Artturin** [comment]
the fetchCargoTarball.sha256 changed on master? weird
```
installing
hash mismatch in fixed-output derivation '/nix/store/mn01d0jdyvkyq2rvcijxy7n5vy2cqnqv-squeekboard-unstable-2021-03-09-vendor.tar.gz':
  wanted: sha256:0gljbaj9qrsahf651hr6z6r51wpgrhq0ig2ldxi4qzajv08zbcpf
  got:    sha256:1qaqiaxqc4x2x5bd31na4c49vbjwrmz5clmgli7733dv55rxxias
cannot build derivation '/nix/store/nwv7yyvs8c09cfdvfm7vs9cz0iv60014-squeekboard-unstable-2021-03-09.drv': 1 dependencies couldn't be built
```

**Comment by Pacman99** [comment]
Can't you just use `buildRustPackage` and pass cargoUpdateHook to that?
 It looks like that would accomplish the same thing: https://github.com/NixOS/nixpkgs/blob/86c7e9297d57437822ba166df98cc47f17ef255b/pkgs/build-support/rust/default.nix#L65.

Otherwise package looks great!

**Comment by SuperSandro2000** [comment]
> Can't you just use `buildRustPackage` and pass cargoUpdateHook to that?

The package uses meson build system which then is most likely not used.

**Review by SuperSandro2000 — APPROVED** [review]
LGTM

**Comment by Artturin** [comment]
@Pacman99
cargoSetupHook is the proper way to use rust in mixed projects
https://github.com/NixOS/nixpkgs/issues/114659#issuecomment-787458824
https://github.com/NixOS/nixpkgs/pull/114678

**Comment by dotlambda** [comment]
> the stable release v1.12.0 is not used because of this useful commit https://source.puri.sm/Librem5/squeekboard/-/commit/a265427e8ec0bf00ce7fdb7caaff0396d0456599

I think we should package the stable release. It is trivial to apply a patch in an overlay.

**Comment by Artturin** [comment]
@dotlambda if there were major changes since the stable then yes but since theres only been trivial changes then why not save the user a bit of trouble

**Comment by Artturin** [comment]
@SuperSandro2000 merge this, @archseer and @masipcat can add themselves in a separate pr.

**Pull request merged**
