### PR TITLE
enlightenment.efl: enable wayland client support

### LINKED ISSUE #98659: Terminology fails to start on Wayland: Xlib:  extension "DPMS" missing on display ":0"
**Describe the bug**
Setting the `ELM_WAYLAND` variable to `wl`, as suggested [here](https://phab.enlightenment.org/T7439), does nothing. Unsetting `DISPLAY` results in this error:
```
$ terminology
ERR<10921>:ecore_evas ../src/modules/ecore_evas/engines/drm/ecore_evas_drm.c:150 _ecore_evas_drm_init() Failed to init Ecore_Drm2 library
ERR<10921>:ecore_evas ../src/modules/ecore_evas/engines/drm/ecore_evas_drm.c:150 _ecore_evas_drm_init() Failed to init Ecore_Drm2 library
ERR<10921>:elementary ../src/lib/elementary/efl_ui_win.c:5561 _elm_win_finalize_internal() Cannot create window.
ERR<10921>:eo ../src/lib/eo/eo.c:1137 _efl_add_internal_end() Object of class 'Efl.Ui.Win_Legacy' - Not all of the object constructors have been executed.
ERR<10921>:ecore ../src/lib/ecore/ecore.c:792 _ecore_magic_fail() *** ECORE ERROR: Ecore Magic Check Failed!!! in: ecore_evas_callback_selection_changed_set()
ERR<10921>:ecore ../src/lib/ecore/ecore.c:794 _ecore_magic_fail()     Input handle pointer is NULL!
ERR<10921>:ecore ../src/lib/ecore/ecore.c:792 _ecore_magic_fail() *** ECORE ERROR: Ecore Magic Check Failed!!! in: ecore_evas_callback_drop_drop_set()
ERR<10921>:ecore ../src/lib/ecore/ecore.c:794 _ecore_magic_fail()     Input handle pointer is NULL!
ERR<10921>:ecore ../src/lib/ecore/ecore.c:792 _ecore_magic_fail() *** ECORE ERROR: Ecore Magic Check Failed!!! in: ecore_evas_callback_drop_motion_set()
ERR<10921>:ecore ../src/lib/ecore/ecore.c:794 _ecore_magic_fail()     Input handle pointer is NULL!
ERR<10921>:ecore ../src/lib/ecore/ecore.c:792 _ecore_magic_fail() *** ECORE ERROR: Ecore Magic Check Failed!!! in: ecore_evas_callback_drop_state_changed_set()
ERR<10921>:ecore ../src/lib/ecore/ecore.c:794 _ecore_magic_fail()     Input handle pointer is NULL!
ERR<10921>:evas_main ../src/lib/evas/canvas/evas_object_smart.c:746 _efl_canvas_group_efl_object_destructor() efl_canvas_group_del() was not called on this object: 0x4000000076d2 (Efl.Ui.Win_Legacy)
ERR<10921>:elementary ../src/lib/elementary/efl_ui_win.c:6190 elm_win_autodel_set() No widget data for object (nil) ((null))
CRI<10921>:terminology ../src/bin/main.c:581 _start() Could not create window.
```

**Expected behavior**
There are two issues. First, the Enlightenment Foundation Libraries are not complied with Wayland support. Secondly, the `ELM_WAYLAND` variable needs to be set correctly a Wayland environment.

**Notify maintainers**

@matejc @tstrobel @ftrvxmtrx @romildo

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: enlightenment.terminology # + any other Enlightenment package
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

enlightenment.efl: enable wayland client support
enlightenment.efl: use pkg-config instead of the alias pkgconfig 
enlightenment.efl: fix license
enlightenment.efl: remove leftover patch file

Fixes https://github.com/NixOS/nixpkgs/issues/98659

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
Result of `nixpkgs-review pr 99556` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>enlightenment.econnman</li>
    <li>enlightenment.efl</li>
    <li>enlightenment.enlightenment</li>
    <li>enlightenment.ephoto</li>
    <li>enlightenment.evisum</li>
    <li>enlightenment.rage</li>
    <li>enlightenment.terminology</li>
    <li>python27Packages.pythonefl</li>
    <li>python37Packages.pythonefl</li>
    <li>python38Packages.pythonefl</li>
  </ul>
</details>

**Comment by romildo** [comment]
Result of `nixpkgs-review pr 99556` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>enlightenment.econnman</li>
    <li>enlightenment.efl</li>
    <li>enlightenment.enlightenment</li>
    <li>enlightenment.ephoto</li>
    <li>enlightenment.evisum</li>
    <li>enlightenment.rage</li>
    <li>enlightenment.terminology</li>
    <li>python27Packages.pythonefl</li>
    <li>python37Packages.pythonefl</li>
    <li>python38Packages.pythonefl</li>
  </ul>
</details>

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
I'm half expecting some sort of change  in the nixos module?

**Comment by romildo** [comment]
@worldofpeace , thank you for reviewing and merging this PR.

> I'm half expecting some sort of change in the nixos module?

Do you mean changes in the nixos module related to wayland?

This PR does not enable running the Enlightenment DE on wayland yet. It just enables running EFL applications (like terminology) on any DE on wayland, like sway.

**Pull request merged**
