### PR TITLE
nbqa: 1.8.4 -> 1.8.5

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://nbqa.readthedocs.io/en/latest/history.html

cc @l0b0 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 299165` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nbqa</li>
    <li>nbqa.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 299165` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nbqa</li>
    <li>nbqa.dist</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
One test is failing on x86_64-linux

```
    Differences (jupytext --diff {src} {out}) are:
    {diff}
    Please either:
    - open {src} in a text editor, make sure it is up to date, and save it,
    - or delete {src} if not up to date,
    - or increase check margin by adding, say,
    outdated_text_notebook_margin = 5  # default is 1 (second)
    to your jupytext.toml file
                            """.format(
                                    ts_mismatch=ts_mismatch,
                                    src=inputs.path,
                                    out=outputs.path,
                                    diff=diff,
                                ),
                            )
E                           tornado.web.HTTPError: HTTP 400: Bad Request (notebook.ipynb (last modified 2024-03-26 12:58:54.602161+00:00) is more recent than notebook.py (last modified 2024-03-26 12:58:53.533142+00:00)
E                           
E                           Differences (jupytext --diff notebook.py notebook.ipynb) are:
E                           --- notebook.py
E                           +++ notebook.ipynb
E                           @@ -14,3 +14,5 @@
E                            
E                            # A short notebook
E                            
E                           +# New cell
E                           +
E                           Please either:
E                           - open notebook.py in a text editor, make sure it is up to date, and save it,
E                           - or delete notebook.py if not up to date,
E                           - or increase check margin by adding, say,
E                           outdated_text_notebook_margin = 5  # default is 1 (second)
E                           to your jupytext.toml file
E                                                   )
/nix/store/n2d3ys68malq3wr5ajwhhjkzfplk8ig1-python3.11-jupytext-1.16.1/lib/python3.11/site-packages/jupytext/contentsmanager.py:344: HTTPError
------------------------------ Captured log call -------------------------------
WARNING  traitlets:contentsmanager.py:329 notebook.ipynb (last modified 2024-03-26 12:58:54.602161+00:00) is more recent than notebook.py (last modified 2024-03-26 12:58:53.533142+00:00)
WARNING  traitlets:manager.py:740 Notebook notebook.ipynb is not trusted
WARNING  traitlets:contentsmanager.py:329 notebook.ipynb (last modified 2024-03-26 12:58:54.602161+00:00) is more recent than notebook.py (last modified 2024-03-26 12:58:53.533142+00:00)
WARNING  traitlets:manager.py:740 Notebook notebook.ipynb is not trusted
=========================== short test summary info ============================
FAILED tests/integration/contents_manager/test_contentsmanager.py::test_outdated_text_notebook - tornado.web.HTTPError: HTTP 400: Bad Request (notebook.ipynb (last modified...
================= 1 failed, 2893 passed, 134 skipped in 20.70s =================
/nix/store/c8dj731bkcdzhgrpawhc8qvdgls4xfjv-stdenv-linux/setup: line 1578: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/a838qcv6wa3f5dr0a728lgpgdlmwwmrj-python3.11-jupytext-1.16.1.drv' failed with exit code 1;
```

**Comment by GaetanLepage** [comment]
> One test is failing on x86_64-linux

Which tests are those ? Do you get this when building `nbqa` ?

**Comment by a-n-n-a-l-e-e** [comment]
> > One test is failing on x86_64-linux
> 
> Which tests are those ? Do you get this when building `nbqa` ?

https://logs.ofborg.org/?key=nixos/nixpkgs.299165&attempt_id=c8b3ae76-35a4-479c-8519-88a13c3b4eb3

for some reason many of the prereqs are not cached and thus need to be built.  i started to build on my machine and can verify that many packages needed to get built before nbqa. had to kill the build because need my cycles for other things.

**Comment by GaetanLepage** [comment]
> for some reason many of the prereqs are not cached and thus need to be built. i started to build on my machine and can verify that many packages needed to get built before nbqa. had to kill the build because need my cycles for other things.

This weird though. How come the `nixpkgs-review` succeeds then ?
Also, this release only takes care of fixing a test. I really doubt that it introduces a regression.

**Comment by a-n-n-a-l-e-e** [comment]
the test that is failing looks timing related. ` (notebook.ipynb (last modified 2024-03-26 12:58:54.602161+00:00) is more recent than notebook.py (last modified 2024-03-26 12:58:53.533142+00:00)`

@ofborg build nbqa nbqa.passthru.tests

**Comment by GaetanLepage** [comment]
> @ofborg build nbqa nbqa.passthru.tests

Seems to work now !

**Comment by a-n-n-a-l-e-e** [comment]
builds fine on aarch64/x64 darwin

**Pull request merged**
