### PR TITLE
compilers/ghc: grooming various versions

### PR DESCRIPTION
**Pull request by ggreif**
###### Motivation for this change

removing GHC v8.8.1
typofixes and structuredAttrs maintenance 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build ghc
@GrahamcOfBorg build haskellPackages.lens

**Comment by ggreif** [comment]
@GrahamcOfBorg build elmPackages.elm

**Review by peti — CHANGES_REQUESTED** [review]
I would love to merge this PR, but it contains changes to `hackage-packges.nix` that don't belong here, IMHO. Can you please edit the PR to drop all changes to that file?

**Review by peti — APPROVED** [review]
Never mind .... I just cherry-picked the relevant changes into the `haskell-updates` branch as 36d14d053893268ab05d19512a69769208446759 et al.

**Comment by peti** [comment]
Merged to `haskell-updates`.

**Comment by ggreif** [comment]
No idea how I got those `pkgs/development/haskell-modules/hackage-packages.nix` :-o

@peti Thanks for doing this!

**Pull request closed without merging**
