### PR TITLE
lego: 3.0.2 -> 3.2.0

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/nix/store/z9j7v4f265153ark4hvgiq88sgxb33p8-lego-3.0.2	   75075032
/nix/store/m0vy2ysbs0vgifwdq4sxza1ab5xm57qs-lego-3.2.0	   76082072

###### Notify maintainers

cc @andrew-d 

supersede #72952

### CODE REVIEW

**Review by andrew-d — CHANGES_REQUESTED** [review]
This works locally, but it looks like there's some internal-only packages getting built and dropped into the `bin` subdirectory.  Could you add the following line?

```
  subPackages = [ "cmd/lego" ];
```

Confirmed that everything builds and runs successfully with that :point_up: addition.

**Comment by bbigras** [comment]
> Could you add the following line?
> `subPackages = [ "cmd/lego" ];`

Done. Thanks!

**Review by andrew-d — APPROVED** [review]
Thank you!

**Comment by bbigras** [comment]
ping @kalbasit

**Comment by timokau** [comment]
Thanks!

**Pull request merged**
