### PR TITLE
llvm: 3.8.0 -> 3.9.0

### PR DESCRIPTION
**Pull request by gebner**
###### Motivation for this change

LLVM 3.9 should be released within the next few days, so I've begun packaging the release candidate.  I'd like to switch mesa to the new LLVM version soon in order to support the AMD Polaris graphics card, see #17991.  This PR only adds the new LLVM version, but does not change any existing dependencies.

Status: everything builds and seems to work just fine.

Changes from 3.8:
- I disabled the compiler-rt tests in llvm, these require clang source code.
- I adapted the purity patch for clang, there was some refactoring in `Driver/Tools.cpp`.

lldb requires even more build system patches now than before, ~~and I still get the following build error~~ (I have fixed this now):

```
[100%] Linking CXX executable ../../bin/lldb-server
../../lib/liblldbSymbol.a(ClangASTContext.cpp.o):(.data.rel.ro._ZTI22NullDiagnosticConsumer[_ZTI22NullDiagnosticConsumer]+0x10): undefined reference to `typeinfo for clang::DiagnosticConsumer'
../../lib/liblldbSymbol.a(ClangASTImporter.cpp.o):(.data.rel.ro._ZTIN12lldb_private16ClangASTImporter6MinionE[_ZTIN12lldb_private16ClangASTImporter6MinionE]+0x10): undefined reference to `typeinfo for clang::ASTImporter'
../../lib/liblldbPluginExpressionParserClang.a(ClangModulesDeclVendor.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_125StoringDiagnosticConsumerE+0x10): undefined reference to `typeinfo for clang::DiagnosticConsumer'
../../lib/liblldbPluginExpressionParserClang.a(ASTResultSynthesizer.cpp.o):(.data.rel.ro._ZTIN12lldb_private20ASTResultSynthesizerE[_ZTIN12lldb_private20ASTResultSynthesizerE]+0x10): undefined reference to `typeinfo for clang::SemaConsumer'
../../lib/liblldbPluginExpressionParserClang.a(ASTStructExtractor.cpp.o):(.data.rel.ro._ZTIN12lldb_private18ASTStructExtractorE[_ZTIN12lldb_private18ASTStructExtractorE]+0x10): undefined reference to `typeinfo for clang::SemaConsumer'
../../lib/liblldbPluginExpressionParserClang.a(ClangExpressionParser.cpp.o):(.data.rel.ro._ZTIN12lldb_private21ClangExpressionParser25LLDBPreprocessorCallbacksE[_ZTIN12lldb_private21ClangExpressionParser25LLDBPreprocessorCallbacksE]+0x10): undefined reference to `typeinfo for clang::PPCallbacks'
../../lib/liblldbPluginExpressionParserClang.a(ClangExpressionParser.cpp.o):(.data.rel.ro._ZTI29ClangDiagnosticManagerAdapter[_ZTI29ClangDiagnosticManagerAdapter]+0x10): undefined reference to `typeinfo for clang::DiagnosticConsumer'
../../lib/liblldbPluginExpressionParserClang.a(ClangExpressionParser.cpp.o):(.data.rel.ro._ZTIZN12lldb_private21ClangExpressionParser17RewriteExpressionERNS_17DiagnosticManagerEE16RewritesReceiver+0x10): undefined reference to `typeinfo for clang::edit::EditsReceiver'
../../lib/liblldbSymbol.a(ClangExternalASTSourceCommon.cpp.o):(.data.rel.ro._ZTIN12lldb_private28ClangExternalASTSourceCommonE[_ZTIN12lldb_private28ClangExternalASTSourceCommonE]+0x10): undefined reference to `typeinfo for clang::ExternalASTSource'
collect2: error: ld returned 1 exit status
make[3]: *** [tools/lldb-server/CMakeFiles/lldb-server.dir/build.make:543: bin/lldb-server-3.9.0] Error 1
make[2]: *** [CMakeFiles/Makefile2:6280: tools/lldb-server/CMakeFiles/lldb-server.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:6292: tools/lldb-server/CMakeFiles/lldb-server.dir/rule] Error 2
make: *** [Makefile:1371: lldb-server] Error 2
```

~~Does anybody have ideas for lldb?~~  Can anybody test this on Darwin?

cc maintainers @lovek323 @7c6f434c @viric @vlstill 
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gebner** [comment]
Updated to release candidate 3, and fixed the problems with lldb.  Apparently all of [LLVM is built without RTTI](http://lists.llvm.org/pipermail/lldb-dev/2014-January/003160.html), and the half-broken standalone lldb build doesn't pick that up.  Just adding `-fno-rtti` fixed the lldb build.

**Comment by vcunat** [comment]
We should later re-test building mesa after RTTI changes, as there used to be link-time problems similar to those in lldb.

**Comment by gebner** [comment]
The RTTI changes are limited to only lldb.  AFAICT the only reverse dependency in nixpkgs would be coreclr, and that is hardcoded to LLVM 3.6.  The 3.9 lldb itself seems to work, at least you can debug other programs.

**Comment by gebner** [comment]
I think the RTTI problem happens because we do enable RTTI in *LLVM* (since #8289), but we do not enable it in *clang*.  So lldb just looks at llvm, sees that it is built with RTTI, and assumes clang has RTTI as well...

**Comment by copumpkin** [comment]
I wouldn't describe this (in the commit message) as 3.8 -> 3.9, since you aren't (as far as I could tell at a glance) getting rid of 3.8. I'd just say you're adding 3.9.

Either way, much appreciated! Perhaps I'll bump the darwin stdenv to use this one instead of 3.8.

**Comment by dtzWill** [comment]
To get LLDB building on 3.8 (and 3.8.1), I had to add a hardening workaround (see the first commit on #18130).  Since this was only needed after upstream changes not included in this branch were made,
it might be good to double-check if they are needed here as well.

I'm trying to build this now, will let you know how that goes :).

**Comment by dtzWill** [comment]
Yep, rebasing this change onto master causes lldb to fail to build due to same string format issue:

```
[ 89%] Building CXX object source/API/CMakeFiles/liblldb.dir/__/__/scripts/LLDBWrapPython.cpp.o
/nix/tmp/nix-build-lldb-3.9.0rc3.drv-0/lldb-3.9.0rc3.src/build/scripts/LLDBWrapPython.cpp: In function 'PyObject* _wrap_SBError_SetErrorStringWithFormat__SWIG_3(PyObject*, PyObject*)':
/nix/tmp/nix-build-lldb-3.9.0rc3.drv-0/lldb-3.9.0rc3.src/build/scripts/LLDBWrapPython.cpp:21430:70: error: format not a string literal and no format arguments [-Werror=format-security]
     result = (int)(arg1)->SetErrorStringWithFormat((char const *)arg2);
                                                                      ^
```

**Comment by dtzWill** [comment]
(But builds to completion before rebasing onto master :+1:)

**Comment by fpletz** [comment]
This is due to the default hardening flags. You need to set:

    hardeningDisable = [ "format" ];

in `mkDerivation`.

**Comment by gebner** [comment]
Okay, rebased against master and applied @fpletz's fix.  Everything builds again!  Now LLVM only needs to get the release out of the door.

@copumpkin Good point about the commit message.  I think we already had `llvm: 3.7.0 -> 3.8.0`, so I tried to be consistent.  Have you tried building it on Darwin?

**Comment by vcunat** [comment]
There release was just announced!

**Comment by vcunat** [comment]
Updated and staged.

**Comment by andrewrk** [comment]
Thanks for being on top of this everyone! Thanks to this PR I can pull it in my fork and use it to update Zig to LLVM 3.9.0. :+1:

**Comment by gebner** [comment]
Wow this was amazingly fast!  We're even faster than archlinux...

**Pull request closed without merging**
