### PR TITLE
ligo: 0.55.0 -> 0.58.0

### PR DESCRIPTION
**Pull request by ulrikstrid**
###### Description of changes

https://gitlab.com/ligolang/ligo/-/releases/0.57.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Frostman** [comment]
Result of `nixpkgs-review pr 205005` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ligo</li>
  </ul>
</details>

**Review by Frostman — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Please mark broken on aarch64-linux and darwin.

**Comment by ulrikstrid** [comment]
`nix run github:ulrikstrid/nixpkgs/ligo--0_57#ligo -- --help` works on my m1 and old intel based mac.

So should `platforms = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" ];` be a good change?

@SuperSandro2000

**Comment by SuperSandro2000** [comment]
> So should `platforms = [ "x86_64-linux" "aarch64-darwin" ];` be a good change?

I assume this is easily fixable so I would suggest to mark it broken for that platform instead.



> The failure on `x86_64-darwin` is actually in `ocamlPackages.class_group_vdf`, should that be marked broken instead?

yes, please

**Comment by ulrikstrid** [comment]
@SuperSandro2000 is this now correct?

**Review by vbgl — APPROVED** [review]
Shall this be backported to 22.11?

**Comment by ulrikstrid** [comment]
I'm not sure what the criteria is for backporting stuff @vbgl, but I guess it might be a good idea :+1:

**Pull request merged**
