### PR TITLE
drone-cli: 0.8.6 -> 1.2.0

### PR DESCRIPTION
**Pull request by kampka**
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @elohmeier @bricewge

### CODE REVIEW

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build drone-cli

**Comment by c0bw3b** [comment]
Locally it builds and runs on nixos (help message and basic invocation of subcommands resulting in a normal error because I have no config).
Let's retry this though:  @GrahamcOfBorg build drone-cli


One minor thing I notice is the lack of the proper version number in:
```shell
$ ./results/drone-cli/bin/drone -v
drone version 
```
@kampka any idea why?

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build drone-cli

**Comment by kampka** [comment]
Looks like the version is compile in via extra build flag: https://github.com/drone/drone-cli/blob/b9b41aadd0c9e816ac0a5eb54fc486717b7349e8/.drone.sh

We can probably add this via the [`buildFlagsArray`](https://nixos.org/nixpkgs/manual/#build-phase).

**Comment by kampka** [comment]
@c0bw3b should be resolved now. Feel free to test again.
```
./result/bin/drone -v
drone version 1.2.0
```

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build drone-cli

**Review by c0bw3b — APPROVED** [review]
Builds and runs and version is shown properly

**Pull request merged**
