### PR TITLE
linuxPackages.rtl88x2bu: unstable-2023-11-29 -> unstable-2024-05-11

### PR DESCRIPTION
**Pull request by otavio**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
Would you like to bump further to https://github.com/morrownr/88x2bu-20210702/commit/62f3a86a2687fe98bd441e0aff5adf87d95c238a

**Comment by otavio** [comment]
I will look at this tomorrow.

**Comment by jonathan-conder** [comment]
I just ran into issues with this today, thanks for the PR. The hash for that commit is `sha256-gQWk1nhtT0W2dY5uQitWabBGEDfZpmJAoJg+j2ndO00=` in case it helps

**Comment by otavio** [comment]
@NickCao please review.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 318297` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.rtl88x2bu</li>
    <li>linuxPackages_4_19_hardened.rtl88x2bu (linuxKernel.packages.linux_4_19_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_5_10.rtl88x2bu</li>
    <li>linuxPackages_5_10_hardened.rtl88x2bu (linuxKernel.packages.linux_5_10_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_5_15.rtl88x2bu</li>
    <li>linuxPackages_5_15_hardened.rtl88x2bu (linuxKernel.packages.linux_5_15_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_5_4.rtl88x2bu</li>
    <li>linuxPackages_5_4_hardened.rtl88x2bu (linuxKernel.packages.linux_5_4_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_6_1.rtl88x2bu</li>
    <li>linuxPackages_6_1_hardened.rtl88x2bu (linuxKernel.packages.linux_6_1_hardened.rtl88x2bu)</li>
    <li>linuxPackages.rtl88x2bu (linuxKernel.packages.linux_6_6.rtl88x2bu)</li>
    <li>linuxPackages_hardened.rtl88x2bu (linuxPackages_6_6_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_6_8.rtl88x2bu</li>
    <li>linuxPackages_6_8_hardened.rtl88x2bu (linuxKernel.packages.linux_6_8_hardened.rtl88x2bu)</li>
    <li>linuxPackages_latest.rtl88x2bu (linuxKernel.packages.linux_6_9.rtl88x2bu)</li>
    <li>linuxPackages_6_9_hardened.rtl88x2bu (linuxKernel.packages.linux_6_9_hardened.rtl88x2bu)</li>
    <li>linuxPackages_latest-libre.rtl88x2bu (linuxKernel.packages.linux_latest_libre.rtl88x2bu)</li>
    <li>linuxPackages-libre.rtl88x2bu (linuxKernel.packages.linux_libre.rtl88x2bu)</li>
    <li>linuxPackages_lqx.rtl88x2bu (linuxKernel.packages.linux_lqx.rtl88x2bu)</li>
    <li>linuxPackages_xanmod.rtl88x2bu (linuxKernel.packages.linux_xanmod.rtl88x2bu)</li>
    <li>linuxPackages_xanmod_latest.rtl88x2bu (linuxKernel.packages.linux_xanmod_latest.rtl88x2bu ,linuxPackages_xanmod_stable.rtl88x2bu)</li>
    <li>linuxPackages_zen.rtl88x2bu (linuxKernel.packages.linux_zen.rtl88x2bu)</li>
  </ul>
</details>

**Pull request merged**
