### PR TITLE
bun: 1.1.27 -> 1.1.29

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

https://github.com/oven-sh/bun/compare/bun-v1.1.27...bun-v1.1.29

https://github.com/NixOS/nixpkgs/pull/332639#issuecomment-2359963630

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by thilobillerbeck — APPROVED** [review]

**Comment by afh** [comment]
Result of `nixpkgs-review pr 343120` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bun</li>
    <li>helix-gpt</li>
  </ul>
</details>

**Review by afh — APPROVED** [review]

**Comment by uncenter** [comment]
https://github.com/oven-sh/bun/releases/tag/bun-v1.1.29 is out now as well.

**Comment by uncenter** [comment]
Result of `nixpkgs-review pr 343120` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bun</li>
    <li>helix-gpt</li>
  </ul>
</details>

**Review by uncenter — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 343120` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bun</li>
    <li>helix-gpt</li>
  </ul>
</details>

**Comment by afh** [comment]
Result of `nixpkgs-review pr 343120` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bun</li>
    <li>helix-gpt</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]

**Comment by domenkozar** [comment]
I'm getting

```
dyld[55972]: Symbol not found: _ubrk_clone
  Referenced from: /nix/store/1hn8dddmy3l99x502d0fqz901gfk74px-bun-1.1.29/bin/bun
  Expected in: /usr/lib/libicucore.A.dylib
/nix/store/khdyzjph6755ldcld7a4v8fxc5aw3s41-init-bun.sh: line 3: 55972 Abort trap: 6           /nix/store/1hn8dddmy3l99x502d0fqz901gfk74px-bun-1.1.29/bin/bun install --yarn
```

**Comment by domenkozar** [comment]
Seems like it need newer Apple SDK: https://github.com/oven-sh/bun/issues/6035

**Comment by shyim** [comment]
@domenkozar nix downloads the pre-build files, why should it break here 🤔 ?
The nix package works for me Sequoia 15.0.1

**Pull request merged**
