### PR TITLE
opencsg: Darwin support and tidy

### PR DESCRIPTION
**Pull request by thefloweringash**
Regenerate the Makefiles using qmake to set the correct compiler and
use the default installPhase.

###### Motivation for this change

Working towards building openscad for Darwin.

The install name handling here is rather unpleasant. The library is ultimately corrected in the fixup phase by the hook, however the example application is already linked by then. Suggestions for improvement welcome.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thefloweringash** [comment]
Patch sent upstream as https://github.com/floriankirsch/OpenCSG/pull/2

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build openscad

**Comment by thefloweringash** [comment]
@7c6f434c this only fixes opencsg. openscad needs a little more work.

**Comment by 7c6f434c** [comment]
I just wanted to check that rerunning `qmake` doesn't have any side-effects that OpenSCAD would care about.

**Pull request merged**
