### PR TITLE
kanidm: 1.3 is EOL

### PR DESCRIPTION
**Pull request by adamcstephens**
Will merge at end of November.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by oddlama — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
So we are retroactively forcing people to build kanidm from source on a deprecated NixOS version? What's the point of this? What differentiates kanidm from any other software which is EOL by now?

Or is the nixos module just poorly handling updates of kanidm?

**Comment by adamcstephens** [comment]
24.05 may be deprecated but is still receiving security fixes. Therefore I consider it important to correctly reflect the state of upstream, especially for security sensitive projects such as kanidm.

One alternative to what I’ve proposed here is to force upgrade 24.05 to kanidm 1.4, which has breaking changes.

Not sure what the module has to do with version support in the package.

**Comment by Scrumplex** [comment]
I don't think we should touch 24.05 for this unless there is actually a vulnerability. People will upgrade to 24.11 sooner than later anyway.

**Comment by adamcstephens** [comment]
I'm still planning to change 24.05, but not with this PR as-is. I am going to backport #357734

**Comment by adamcstephens** [comment]
y'all win, because I'm too lazy to merge all the multi-version changes by hand.

**Pull request closed without merging**
