### PR TITLE
kitty: 0.16.0 -> 0.17.1

### PR DESCRIPTION
**Pull request by Luflosi**
###### Motivation for this change
https://github.com/kovidgoyal/kitty/releases/tag/v0.17.1

The png2icns patch is no longer needed because kitty will now automatically use `png2icns` when `iconutil` cannot be found.
The zsh completions will now work without needing to invoke them with `source`, which means, that we can just install them like the other shell completions.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by sugar700 — APPROVED** [review]

**Comment by jtojnar** [comment]
https://github.com/kovidgoyal/kitty/releases/tag/v0.17.1 was just released

**Comment by Luflosi** [comment]
Should we skip 0.17.0?

**Comment by jtojnar** [comment]
It is easier to just re-use the same PR. Especially since the release fixes some issues introduced in 0.17.1.

**Comment by Luflosi** [comment]
Ok, I'll just add another commit and change the title then.

**Comment by jtojnar** [comment]
For just minor bump, it is not even necessary to use a separate commit, you can just amend the previous one. Separate commits are only necessary when they improve the clarity by making the incremental diffs smaller.

**Comment by Luflosi** [comment]
Ok, I did that and while I was at it I rebased onto the latest master.

**Review by sugar700 — APPROVED** [review]

**Comment by xfix** [comment]
That was a fast update, when I checked, there was no 0.17.1 release :).

**Pull request merged**
