### PR TITLE
Bazel runtime dependencies in PATH

### PR DESCRIPTION
**Pull request by ylecornec**
###### Description of changes
This PR adds a wrapper around Bazel to ensure tools from `defaultShellPath` are in the PATH, to make them available to repository rules and genrules.

If the `which` tool is missing in particular, this can lead to misleading error messages as reproduced in [this comment](https://github.com/NixOS/nixpkgs/pull/146389#commitcomment-73865801) (since `which python` fails, bazel mistakenly reports that `python` is missing from the environment).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by olebedev — APPROVED** [review]
LGTM if LGT the code owner.

**Review by uri-canva — CHANGES_REQUESTED** [review]
The fix itself looks good, but why does https://github.com/NixOS/nixpkgs/blob/5f2eb57725ce3781e01046ed26ad922d13900402/pkgs/development/tools/build-managers/bazel/python-bin-path-test.nix not reproduce the failure? Can you either add a new test or modify the existing one so it reproduces the failure? Otherwise we'll risk regressing this when we're changing the package in the future.

**Review by uri-canva — APPROVED** [review]

**Comment by uri-canva** [comment]
Thanks for fixing!

**Comment by avdv** [comment]
This should be backported to 22.05 too, right?

**Comment by uri-canva** [comment]
Sorry I'm not sure what the backport criterias are, but the change should be backwards compatible if we want to backport it.

**Pull request merged**
