### PR TITLE
vimPlugins: fix coc-markdownlint and coc-vimlsp

### PR DESCRIPTION
**Pull request by malob**
###### Motivation for this change

I use Nix to manage my Neovim installation (including plugins) and configuration. In my Neovim setup I use `coc.vim`, and plugins for that ecosystem. I noticed some `coc.nvim` plugins that I use, `coc-markdownlint` and `coc-vimlsp`, that are available in `nixpkgs` where not recognized by `coc.nvim` when installed through Nix.

###### Things done

These plugins were being added to `nixpkgs` using the `vim-plugins-names`\\`update.py` mechanism, as opposed to other `coc.nvim` plugins (that were recognized when installed through Nix) that are added through `nodePackages` and `override.nix` for Vim plugins.

To resolve the issue of the two plugins in question not being recognized, I transitioned them to using the latter mechanism.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by malob** [comment]
It's worth noting that there are other `coc.nvim` plugins that might also suffer from the same issue, that I didn't "fix" with this PR since I don't personally use them. They are:

* `coc-clap`
* `coc-denite`
* `coc-explorer`
* `coc-fzf`
* `coc-neco`
* `coc-spell-checker`

**Comment by SuperSandro2000** [comment]
and already a merge conflict.

**Comment by malob** [comment]
Resolved.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 105174 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>3 packages marked as broken and skipped:</summary>  <ul>    <li>rambox-pro</li>    <li>sage</li>    <li>sageWithDoc</li>  </ul></details><details>  <summary>20 packages built:</summary>  <ul>    <li>castnow</li>    <li>create-cycle-app</li>    <li>epgstation</li>    <li>etcher</li>    <li>gtop</li>    <li>joplin</li>    <li>lumo</li>    <li>mirakurun</li>    <li>netlify-cli</li>    <li>parity-ui</li>    <li>pm2</li>    <li>redoc-cli</li>    <li>slack</li>    <li>teleprompter</li>    <li>thelounge</li>    <li>vimPlugins.coc-markdownlint</li>    <li>vimPlugins.coc-prettier</li>    <li>vimPlugins.coc-stylelint</li>    <li>vimPlugins.coc-vimlsp</li>    <li>vscode-extensions.matklad.rust-analyzer</li>  </ul></details>

**Pull request merged**
