### PR TITLE
python3Packages.graphviz: 0.16 -> 0.17

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/xflr6/graphviz/blob/0.17/CHANGES.txt

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`python3Packages.diagrams` tests were already failing but now it fails earlier:

```
ERROR: Could not find a version that satisfies the requirement graphviz<0.17.0,>=0.13.2 (from diagrams)
ERROR: No matching distribution found for graphviz<0.17.0,>=0.13.2
``` 

Don't know how you want to handle that.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 131426` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>bareos</li>
<li>pepper</li>
<li>python38Packages.dask-xgboost</li>
<li>python38Packages.optuna</li>
<li>python39Packages.dask-xgboost</li>
<li>python39Packages.optuna</li>
<li>tribler</li>
</ul>
</details>
<details>

  <summary>6 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>apache-airflow: log was empty</li>
<li>python38Packages.WSME: log was empty</li>
<li>python38Packages.apache-airflow: log was empty</li>
<li>python38Packages.diagrams: log was empty</li>
<li>python39Packages.apache-airflow: log was empty</li>
<li>python39Packages.diagrams: log was empty</li>
  </ul>
</details>
<details>
<summary>
71 packages built:
</summary>
<ul>
<li>beets</li>
<li>beetsExternalPlugins.alternatives</li>
<li>beetsExternalPlugins.copyartifacts</li>
<li>beetsExternalPlugins.extrafiles</li>
<li>ceph (ceph-dev)</li>
<li>ceph-client</li>
<li>ceph-csi</li>
<li>flexget</li>
<li>home-assistant</li>
<li>libceph</li>
<li>mnemosyne</li>
<li>python38Packages.amqtt</li>
<li>python38Packages.catboost</li>
<li>python38Packages.cherrypy</li>
<li>python38Packages.consonance</li>
<li>python38Packages.dissononce</li>
<li>python38Packages.graphviz</li>
<li>python38Packages.hbmqtt</li>
<li>python38Packages.junos-eznc</li>
<li>python38Packages.mxnet</li>
<li>python38Packages.objgraph</li>
<li>python38Packages.pyalgotrade</li>
<li>python38Packages.pylxd</li>
<li>python38Packages.pyro-ppl</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-aer</li>
<li>python38Packages.qiskit-aqua</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.qiskit-ignis</li>
<li>python38Packages.qiskit-terra</li>
<li>python38Packages.retworkx</li>
<li>python38Packages.roombapy</li>
<li>python38Packages.skidl</li>
<li>python38Packages.soco</li>
<li>python38Packages.streamz</li>
<li>python38Packages.transitions</li>
<li>python38Packages.ws4py</li>
<li>python38Packages.xdot</li>
<li>python38Packages.xgboost</li>
<li>python38Packages.yowsup</li>
<li>python39Packages.amqtt</li>
<li>python39Packages.catboost</li>
<li>python39Packages.cherrypy</li>
<li>python39Packages.consonance</li>
<li>python39Packages.dissononce</li>
<li>python39Packages.graphviz</li>
<li>python39Packages.junos-eznc</li>
<li>python39Packages.mxnet</li>
<li>python39Packages.objgraph</li>
<li>python39Packages.pyalgotrade</li>
<li>python39Packages.pylxd</li>
<li>python39Packages.pyro-ppl</li>
<li>python39Packages.qiskit</li>
<li>python39Packages.qiskit-aer</li>
<li>python39Packages.qiskit-aqua</li>
<li>python39Packages.qiskit-ibmq-provider</li>
<li>python39Packages.qiskit-ignis</li>
<li>python39Packages.qiskit-terra</li>
<li>python39Packages.retworkx</li>
<li>python39Packages.roombapy</li>
<li>python39Packages.skidl</li>
<li>python39Packages.soco</li>
<li>python39Packages.streamz</li>
<li>python39Packages.transitions</li>
<li>python39Packages.ws4py</li>
<li>xdot (python39Packages.xdot)</li>
<li>python39Packages.xgboost</li>
<li>python39Packages.yowsup</li>
<li>qemu_full</li>
<li>sabnzbd</li>
<li>sambaFull (samba4Full)</li>
</ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131426` at a57ca294 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/8ae73890010898d3c754f7d845d9dd23">apache-airflow</a></li>
    <li><a href="https://gist.github.com/4788682785359bf42c41e45efdc1f827">pepper</a></li>
    <li><a href="https://gist.github.com/91f5f928efc719a7eddb20dc739636ca">python38Packages.WSME</a></li>
    <li><a href="https://gist.github.com/6489be7968212b54ca15aa486023a013">python38Packages.apache-airflow</a></li>
    <li><a href="https://gist.github.com/a933ccfb8930eb261490fa92b6ae90e7">python38Packages.dask-xgboost</a></li>
    <li><a href="https://gist.github.com/23721d3a4e109f9cc298e44201640aea">python38Packages.diagrams</a></li>
    <li><a href="https://gist.github.com/b23e23cfdab80af9d4e358a8d8b46eb5">python39Packages.apache-airflow</a></li>
    <li><a href="https://gist.github.com/9bc4987558b21f2eed84240b36618921">python39Packages.dask-xgboost</a></li>
    <li><a href="https://gist.github.com/b9107fb2f25b91a06c0b73d54d535486">python39Packages.diagrams</a></li>
  </ul>
</details>
<details>
  <summary>23 packages skipped due to time constraints:</summary>
  <ul>
    <li>bareos</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>home-assistant</li>
    <li>libceph</li>
    <li>python38Packages.catboost</li>
    <li>python38Packages.optuna</li>
    <li>python38Packages.pyro-ppl</li>
    <li>python38Packages.qiskit</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>52 packages built successfully:</summary>
  <ul>
    <li>beets</li>
    <li>beetsExternalPlugins.alternatives</li>
    <li>beetsExternalPlugins.copyartifacts</li>
    <li>beetsExternalPlugins.extrafiles</li>
    <li>flexget</li>
    <li>mnemosyne</li>
    <li>python38Packages.amqtt</li>
    <li>python38Packages.cherrypy</li>
    <li>python38Packages.consonance</li>
    <li>python38Packages.dissononce</li>
    <li>python38Packages.graphviz</li>
    <li>python38Packages.hbmqtt</li>
    <li>python38Packages.junos-eznc</li>
    <li>python38Packages.mxnet</li>
    <li>python38Packages.objgraph</li>
    <li>python38Packages.pyalgotrade</li>
    <li>python38Packages.pylxd</li>
    <li>python38Packages.qiskit-terra</li>
    <li>python38Packages.retworkx</li>
    <li>python38Packages.roombapy</li>
    <li>python38Packages.skidl</li>
    <li>python38Packages.soco</li>
    <li>python38Packages.transitions</li>
    <li>python38Packages.ws4py</li>
    <li>python38Packages.xdot</li>
    <li>python38Packages.xgboost</li>
    <li>python38Packages.yowsup</li>
    <li>python39Packages.amqtt</li>
    <li>python39Packages.cherrypy</li>
    <li>python39Packages.consonance</li>
    <li>python39Packages.dissononce</li>
    <li>python39Packages.graphviz</li>
    <li>python39Packages.junos-eznc</li>
    <li>python39Packages.mxnet</li>
    <li>python39Packages.objgraph</li>
    <li>python39Packages.pyalgotrade</li>
    <li>python39Packages.pylxd</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>python39Packages.qiskit-terra</li>
    <li>python39Packages.retworkx</li>
    <li>python39Packages.roombapy</li>
    <li>python39Packages.skidl</li>
    <li>python39Packages.soco</li>
    <li>python39Packages.transitions</li>
    <li>python39Packages.ws4py</li>
    <li>xdot (python39Packages.xdot)</li>
    <li>python39Packages.xgboost</li>
    <li>python39Packages.yowsup</li>
    <li>sabnzbd</li>
    <li>tribler</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by SuperSandro2000** [comment]
> `python3Packages.diagrams` tests were already failing but now it fails earlier:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement graphviz<0.17.0,>=0.13.2 (from diagrams)
> ERROR: No matching distribution found for graphviz<0.17.0,>=0.13.2
> ```
> 
> Don't know how you want to handle that.

It can probably be fixed with https://github.com/mingrammer/diagrams/pull/561 but since the package only breaks in a different way I am going to merge it anyway.

**Pull request merged**
