### PR TITLE
normcap: 0.5.4 -> 0.5.6

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

Diff: https://github.com/dynobo/normcap/compare/refs/tags/v0.5.4...v0.5.5

fixes https://hydra.nixos.org/build/258438950 ZHF https://github.com/NixOS/nixpkgs/issues/309482

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by getchoo** [comment]
Result of `nixpkgs-review pr 309955` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>normcap</li>
    <li>normcap.dist</li>
  </ul>
</details>

**Review by getchoo — APPROVED** [review]

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 309955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>normcap</li>
    <li>normcap.dist</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
I can't get the application to work on my Sway system, but that seems to be a bug with the tool itself.

**Comment by Scrumplex** [comment]
I have submitted an upstream fix here: https://github.com/dynobo/normcap/pull/640

Perhaps we can backport this to fix `normcap` on Wayland desktops besides GNOME.

**Review by cafkafk — COMMENTED** [review]
> I can't get the application to work on my Sway system, but that seems to be a bug with the tool itself.

Was it always broken or did this update break it?

**Comment by Scrumplex** [comment]
It was first introduced by https://github.com/dynobo/normcap/commit/6b6e3516a33375bbdd82ae65fd0d8ec1b06184c4, which is only part of 0.5.5

**Review by cafkafk — CHANGES_REQUESTED** [review]
> It was first introduced by [dynobo/normcap@6b6e351](https://github.com/dynobo/normcap/commit/6b6e3516a33375bbdd82ae65fd0d8ec1b06184c4), which is only part of 0.5.5

We should maybe close this PR and create an issue instead tracking this instead until https://github.com/dynobo/normcap/pull/640 is merged?

**Comment by pbsds** [comment]
Lets wait for the next bump, fetching a soon-merged patch will only stop r-ryantm for the next bump. Drafting this i believe is easier than making an issue.

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 309955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>normcap</li>
    <li>normcap.dist</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]
Builds and runs fine on Sway!

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 309955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>normcap</li>
    <li>normcap.dist</li>
  </ul>
</details>

**Review by cafkafk — APPROVED** [review]
also works on xmonad :)

**Pull request merged**
