### PR TITLE
tmp-luks: init at version 0.9pre

### PR DESCRIPTION
**Pull request by ts468**
builds successfully on local machine

### CODE REVIEW

**Comment by jagajaga** [comment]
We don't write the word `version` in the commit name... :ice_cream:

**Comment by ts468** [comment]
@jagajaga, sorry, I misunderstood the CONTRIBUTING.md.

**Comment by jagajaga** [comment]
Resolve conflicts with current master.

**Comment by ts468** [comment]
Should be fine now.

**Pull request merged**
