### PR TITLE
autojump: rework

### PR DESCRIPTION
**Pull request by yurrriq**
###### Motivation for this change

Modernize the package, fix fish completion, and update URLs.

- `fetchurl` -> `fetchFromGitHub`
- Update URLs: joelthelion -> wting
- `mkdir` + `cp` -> `install`
- Use `-z` flag to set `zshshare_dir`
- Add me to `meta.maintainers`
- Use `rec`-ursive `version` instead of `let`
- `meta`: `with stdenv.lib; ...`

**N.B.** I've only tested `fish` completions.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build autojump

**Comment by the-kenny** [comment]
Until now the recommended way of activating `autojump` on NixOS was the following:

```
if type "autojump-share" > /dev/null; then
  source "$(autojump-share)"/autojump.zsh > /dev/null
fi
```

This PR removes the `autojump-share` script (which was there to dynamically get location of `$out/share`). Is there a replacement?

**Comment by yurrriq** [comment]
I'm not a Z shell user, and as I (poorly) stated above, I only tested on fish, but now the site functions are installed to `$out/share/zsh/site-functions/`, so that should Just Work™, right?

**Comment by the-kenny** [comment]
Actually you're right. I totally missed that. Thanks!

**Comment by yurrriq** [comment]
Awesome!

**Comment by Janiczek** [comment]
How can I make this work with `bash`? Currently I'm not sure what to put into my `~/.bashrc` instead of the `autojump-share` script. Do I need to have `bash-completions` installed?

**Comment by yurrriq** [comment]
@Janiczek, I believe so. If you use the `programs.bash` module, its option `enableCompletion` defaults to `true`, so It Should Just Work™. I'm a fish user, so YMMV.

**Comment by Janiczek** [comment]
Sorry, a stupid question of a Nix beginner :slightly_smiling_face: Can I do that with Nix installed in Ubuntu (I'm not on NixOS)? Do I use `programs.bash` module if I just `nix-env -iA nixpkgs.bash`? (If the answer to both is no, can I make this somehow work on Nix itself?)

**Comment by cdepillabout** [comment]
I'm a bash user.  Now that the `autojump-share` function has been removed, I'll need to make sure to source `$out/etc/profile.d/autojump.sh` on startup so that my `PROMPT_COMMAND` will be updated automatically.

How does Nix handle that?  If there are any `profile.d/*` files, do these automatically get sourced by `/etc/profile`?

I currently don't have a `/etc/profile.d/` directory, so I'm wondering how this works?  I tried to look in `nixpkgs` to figure out how `/etc/profile.d/` is handled, but I couldn't really find anything.

Will this just be handled automatically?

(Note, this is something completely different than autocompletion.)

**Comment by bfortz** [comment]
For users of oh-my-zsh in nixos systems, the autojump plugin is searched for in /run/current-system/sw/shared/autojump/. In 18.03, I disabled the plugin and used autojump-share in my .zshrc. With #47334 the right links are created when programs.autojump.enabled is set to true and the oh-my-zsh autojump plugin works like a charm.

**Comment by jabarszcz** [comment]
Nixos beginner here.
It seems that bash completions are lazily loaded (since [this commit](https://github.com/NixOS/nixpkgs/pull/32534/commits/9988224c2a1632ae9ee9ab0ba19b79e014d4f681)) and thus that `autojump.bash` is no longer sourced by default. I added `programs.bash.interactiveShellInit = "source /run/current-system/sw/share/autojump/autojump.bash";` and it seems to work, although I am not sure that it is the best way to do things.

**Comment by bfortz** [comment]
The best option imo would be to have autojump.bash loaded automatically when programs.autojump.enable is set (and the same should apply to zsh - this would even remove the need for the oh-my-zsh autojump plugin). I will investigate this when I find time.

**Pull request merged**
