### PR TITLE
smatch: move to by-name and modernize derivation

### PR DESCRIPTION
**Pull request by momeemt**
## Description of changes

- Removed `with lib;` (ref: https://github.com/NixOS/nixpkgs/issues/208242)
- Formatted via nixfmt-rfc-style
- Removed `rec` (ref: https://nix.dev/guides/best-practices#recursive-attribute-set-rec)
- Moved `pkgs/development/tools/analysis` to `pkgs/by-name`

I also add myself to the maintainer list of this package, as it was empty.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Aleksanaa — COMMENTED** [review]
Please split into `move to pkgs/by-name`, `format` and `refactor`. Git is unable to track moved files now.

**Comment by momeemt** [comment]
> Please split into `move to pkgs/by-name`, `format` and `refactor`. Git is unable to track moved files now.

@aleksaana Thanks for reviewing. Which should I split into two commits, or two pull-requests?

**Comment by Aleksanaa** [comment]
> @aleksaana Thanks for reviewing. Which should I split into two commits, or two pull-requests?

Three commits. I asked to split because you edited too much that git doesn't recognize it as a moved file, but a separated one. (https://github.com/NixOS/nixpkgs/pull/343686/commits/55535d9e81ce1b04b08feb49df32ca8bb37c15e7) So someone browsing history will get lost.

**Comment by momeemt** [comment]
> > @aleksaana Thanks for reviewing. Which should I split into two commits, or two pull-requests?
> 
> 
> 
> Three commits. I asked to split because you edited too much that git doesn't recognize it as a moved file, but a separated one. (https://github.com/NixOS/nixpkgs/pull/343686/commits/55535d9e81ce1b04b08feb49df32ca8bb37c15e7) So someone browsing history will get lost.

Understood the reason, I'll do it. Thank you for teaching me.

**Comment by momeemt** [comment]
I split it into these commits.

**Pull request merged**
