### PR TITLE
wheel-inspect: init at 1.7.0

### PR DESCRIPTION
**Pull request by ayazhafiz**
###### Motivation for this change

Adds [`wheel-inspect`](https://github.com/jwodder/wheel-inspect) and its missing dependencies to Nixpkgs.

I need to use this in my professional work, thought I would upstream it to nixpkgs.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - N/A since this is an initialization
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@siraben my first contribution to your love :)

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 144064` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python38Packages.entry-points-txt</li>
    <li>python38Packages.headerparser</li>
    <li>python38Packages.wheel-filename</li>
    <li>python38Packages.wheel-inspect</li>
    <li>python39Packages.entry-points-txt</li>
    <li>python39Packages.headerparser</li>
    <li>python39Packages.wheel-filename</li>
    <li>python39Packages.wheel-inspect</li>
  </ul>
</details>

**Comment by siraben** [comment]
LGTM, utilities and importing the library works.
```ShellSession
[nix-shell:~/.../nixpkgs-review/pr-144064]$ wheel2json /tmp/wheel_inspect-1.7.0-py3-none-any.whl
{
    "abi": [
        "none"
    ],
    "arch": [
        "any"
    ],
    "buildver": null,
...
[nix-shell:~/.../nixpkgs-review/pr-144064]$ python3
Python 3.8.11 (default, Oct 18 2021, 19:44:41) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wheel_inspect import inspect_wheel
>>> inspect_wheel('/tmp/wheel_inspect-1.7.0-py3-none-any.whl')
{'filename': 'wheel_inspect-1.7.0-py3-none-any.whl', 'project': 'wheel_inspect', 'version': '1.7.0', 'buildver': None, 'pyver': ['py3'], 'abi': ['none'], 'arch': ['any'], 'file': {'size': 20316, 'digests': {'md5': '5b787e96d71042ce5536e51c46a8db94', 'sha256': '69b34de1f4464ddfc76280c4563e4afc644de2c88e3ae6882f030afdad3d73e4'}}, 'dist_info': {'record': [{'path': 'wheel_inspect/__init__.py', 'digests': {'sha256': 'fZoO7mIlB9PnBQmojzlRUiY3yyNv0oC8XrHZRI7TQ5M'}, 'size': 1025}, {'path': 'wheel_inspect/__main__.py', 'digests': {'sha256': 'U6B0HuaRLQc9SXLvGnytMzxvBLzjS5IYimRFYbDtVv4'}, 'size': 376}, {'path': 'wheel_inspect/classes.py', 'digests': {'sha256': 'CdScWAKd5B3iA6Dty4q9NlbaQk56H-RCfvGOlHPXCm0'}, 'size': 7125}, {'path': 'wheel_inspect/errors.py', 'digests': {'sha256': '5PcCXqW0v9h0DBv3v3TPREvUUmeuUxG-DzEcyxA889k'}, 'size': 8834}, {'path': 'wheel_inspect/inspecting.py', 'digests': {'sha256': 'fe9VWnx8P12jDwLdcze7Ob5BoGhsAQybcZ4Z0NiDSKE'}, 'size': 7594}, {'path': 'wheel_inspect/metadata.py', 'digests': {'sha256': 'juGH9HBdb4e08WVit0zKUiQaP8tatbieJ84_JzJbcbg'}, 'size': 1941}, {'path': 'wheel_inspect/record.py', 'digests': {'sha256': 'Ai3noVc7k1yG0dpjN0lX94ZsnMTAh2_AV6nMgdsZFAE'}, 'size': 3425}, {'path': 'wheel_inspect/schema.py', 'digests': {'sha256': 'trvLNTpvGYjdTg2R2WkVIRNsaaM3x2fDUgmoZqj_3zw'}, 'size': 12953}, {'path': 'wheel_inspect/util.py', 'digests': {'sha256': 'hGm6tMvsyq4oKJumHUCXeFm13Jj4Z2qOEzvkH5vnMEo'}, 'size': 4713}, {'path': 'wheel_inspect/wheel_info.py', 'digests': {'sha256': 'P2NZSi_6KtuxZtCXAtsIsnWLytw58_ZoWklkgx5MVZs'}, 'size': 2345}, {'path': 'wheel_inspect-1.7.0.dist-info/LICENSE', 'digests': {'sha256': 'TJPsugenJltlQn0FHPj1gj4_oxA9hsdYDSNBVWacacA'}, 'size': 1095}, {'path': 'wheel_inspect-1.7.0.dist-info/METADATA', 'digests': {'sha256': 'hFubGwRJTdcwyOi4jE1NsVUZksWTyZQzpcxZ0wVaZmE'}, 'size': 13800}, {'path': 'wheel_inspect-1.7.0.dist-info/WHEEL', 'digests': {'sha256': 'EVRjI69F5qVjm_YgqcTXPnTAv3BfSUr0WVAHuSP3Xoo'}, 'size': 92}, {'path': 'wheel_inspect-1.7.0.dist-info/entry_points.txt', 'digests': {'sha256': 'fqJPsljFaWRzPdYMreNAf0zg8GSQE0Tgh8_XOzL85lo'}, 'size': 60}, {'path': 'wheel_inspect-1.7.0.dist-info/top_level.txt', 'digests': {'sha256': 'Cz2n0fdOaOfDcl0g6x4t_DEWzWZYYRcFASrgxW0v_WE'}, 'size': 14}, {'path': 'wheel_inspect-1.7.0.dist-info/RECORD', 'digests': {}, 'size': None}], 'metadata': {'metadata_version': '2.1', 'name': 'wheel-inspect', 'version': '1.7.0', 'summary': 'Extract information from wheels', 'home_page': 'https://github.com/jwodder/wheel-inspect', 'author': 'John Thorvald Wodder II', 'author_email': 'wheel-inspect@varonathe.org', 'license': 'MIT', 'project_url': [{'label': 'Source Code', 'url': 'https://github.com/jwodder/wheel-inspect'}, {'label': 'Bug Tracker', 'url': 'https://github.com/jwodder/wheel-inspect/issues'}, {'label': 'Say Thanks!', 'url': 'https://saythanks.io/to/jwodder'}], 'keywords': '*.dist-info,dist-info,package metadata,packages,pep427,wheel', 'platform': [], 'classifier': ['Development Status :: 4 - Beta', 'Programming Language :: Python :: 3 :: Only', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'License :: OSI Approved :: MIT License', 'Intended Audience :: Developers', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: System :: Software Distribution'], 'requires_python': '~=3.6', 'description_content_type': 'text/x-rst', 'requires_dist': [{'name': 'attrs', 'url': None, 'extras': [], 'specifier': '>=18.1', 'marker': None}, {'name': 'entry-points-txt', 'url': None, 'extras': [], 'specifier': '~=0.1.0', 'marker': None}, {'name': 'headerparser', 'url': None, 'extras': [], 'specifier': '~=0.4.0', 'marker': None}, {'name': 'packaging', 'url': None, 'extras': [], 'specifier': '>=17.1', 'marker': None}, {'name': 'readme-renderer', 'url': None, 'extras': [], 'specifier': '~=24.0', 'marker': None}, {'name': 'wheel-filename', 'url': None, 'extras': [], 'specifier': '~=1.1', 'marker': None}], 'description': {'length': 12281}}, 'wheel': {'wheel_version': '1.0', 'generator': 'bdist_wheel (0.35.1)', 'root_is_purelib': True, 'tag': ['py3-none-any']}, 'entry_points': {'console_scripts': {'wheel2json': {'module': 'wheel_inspect.__main__', 'attr': 'main', 'extras': []}}}, 'top_level': ['wheel_inspect']}, 'valid': True, 'derived': {'description_in_body': True, 'description_in_headers': False, 'readme_renders': True, 'keywords': ['*.dist-info', 'dist-info', 'package metadata', 'packages', 'pep427', 'wheel'], 'keyword_separator': ',', 'dependencies': ['attrs', 'entry-points-txt', 'headerparser', 'packaging', 'readme-renderer', 'wheel-filename'], 'modules': ['wheel_inspect', 'wheel_inspect.__main__', 'wheel_inspect.classes', 'wheel_inspect.errors', 'wheel_inspect.inspecting', 'wheel_inspect.metadata', 'wheel_inspect.record', 'wheel_inspect.schema', 'wheel_inspect.util', 'wheel_inspect.wheel_info']}}
```

**Review by siraben — APPROVED** [review]

**Review by siraben — CHANGES_REQUESTED** [review]
@ayazhafiz please fix trailing whitespace (see Checks)

**Review by ayazhafiz — COMMENTED** [review]
@siraben should be resolved now.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 144064` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python38Packages.entry-points-txt</li>
    <li>python38Packages.headerparser</li>
    <li>python38Packages.wheel-filename</li>
    <li>python38Packages.wheel-inspect</li>
    <li>python39Packages.entry-points-txt</li>
    <li>python39Packages.headerparser</li>
    <li>python39Packages.wheel-filename</li>
    <li>python39Packages.wheel-inspect</li>
  </ul>
</details>

**Comment by siraben** [comment]
thanks ❤️

**Pull request merged**
