### PR TITLE
dgraph: 1.0.17 -> 20.03.3

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaghavSood** [comment]
I've opened #89719 to move dgraph to v20.03.03, as that is the latest version installed by https://get.dgraph.io, used by the installation instructions in the [dgraph docs](https://dgraph.io/downloads).

**Comment by zowoq** [comment]
I can bump this to 20.03, I'd prefer that we keep this as it has other improvements.

**Comment by RaghavSood** [comment]
Actually, I would suggest we keep this as 1.2.5, and I can patch over your shell completion fixes and update my PR to add dgraph_20_03 as a separate package - there might be breaking changes from v1->v20, and it makes sense to keep the default at 1.2.5

**Comment by zowoq** [comment]
Updated to 20.03

**Comment by zowoq** [comment]
Upstream switched to calver after 1.2.2 so I don't think a separate package is needed.

**Comment by RaghavSood** [comment]
I think building with make might cause issues with the git revision flags

**Comment by zowoq** [comment]
> I think building with make might cause issues with the git revision flags

It seems fine? It does complain that `git` isn't available during the build but we're using `BUILD_VERSION` which is passed through to ldflags.

https://github.com/dgraph-io/dgraph/blob/v20.03.3/Makefile
https://github.com/dgraph-io/dgraph/blob/v20.03.3/dgraph/Makefile.

**Review by sigma — APPROVED** [review]

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 89642` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- dgraph
</details>

**Review by bhipple — APPROVED** [review]

**Pull request merged**
