### PR TITLE
suitesparse: 5.4.0 → 5.7.1 + clean up

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Also had split (e.g. GEGL depends only on umfpack) in the works but it does not make sense to delay it.

cc @knedlsepp @ttuegel @jluttine 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Upstream also now [suggests](https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/1) to link against Intel MKL instead of OpenBLAS but it is just something they discovered recently, not a regression. As such, I will not touch that until we know more.

**Review by knedlsepp — APPROVED** [review]
Thanks for giving this a good cleanse.

**Comment by knedlsepp** [comment]
Interesting findings about MKL/OpenBLAS. I guess we probably care about the licensing quite a bit so the swap wouldn't be all that straightforward anyway.

**Comment by knedlsepp** [comment]
Was graphblas part of suitesparse before? I remember seeing quite a few log messages as part of the build.

**Comment by jtojnar** [comment]
Yes it was. It is also what made the build take so long.

**Comment by jtojnar** [comment]
I have spent a couple hours and purged it completely (see the commit message).

It builds both with and without cuda.

Now only checking the `makeFlags` if they are still needed remains but I have spent too much time on this already.

In the future we might clean the expression even further:

* I have opened an upstream issue to allow us to remove the Makefile editing: https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/25
* Darwin dylib names might be fixed on master: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/f6daae26ee391e475e2295e77c839aa7c1a8b784

**Review by edwtjo — APPROVED** [review]

**Review by jonringer — COMMENTED** [review]
imo, the suitesparse commits should be squashed.

falls under the small fixup clause of `if you have commits pkg-name: oh, forgot to insert whitespace: squash commits in this case.`  https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches

**Comment by jtojnar** [comment]
IMHO it make sense to have structural and functional changes in separate commits, not only for reviewing but also for making sense of it when blaming files.

**Comment by jonringer** [comment]
there is a lot going on, and I don't have enough context on how these applications are meant to behave, to have much of an opinion.

the diff LGTM, so I'll defer to your preference.

**Review by jonringer — APPROVED** [review]

**Comment by jtojnar** [comment]
I would like to hear from @ttuegel who introduced the merged `libsuitesparse.so` if they still have some need for it. If there is no response, we should merge it after a week.

**Pull request merged**
