### PR TITLE
scalafix: 0.9.0 -> 0.10.0, completions, setup-hook instead of jdk

### PR DESCRIPTION
**Pull request by dtzWill**
###### Description of changes

* https://github.com/scalacenter/scalafix/releases/tag/v0.10.0

* Shell completions

NOTE: I'm honestly unsure the significance of pinning to a scala version
tag (which I bump from 2.12.7 -> 2.13.8), so someone familiar with this
please take a look :).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
(grabbed setup-hook fixup from #171067)

**Comment by dtzWill** [comment]
Note installCheck doesn't run currently, FWIW, see #166730 for fixing this in packages tree-wide.

**Comment by Tomahna** [comment]
Tested on nixos, seems to work fine however I've not used scalafix for a while now.

LGTM.

**Review by Tomahna — APPROVED** [review]

**Comment by dtzWill** [comment]
I have not looked into why it's pinned to java8, leaving alone for now.

**Comment by dtzWill** [comment]
Thanks for the review!

**Pull request merged**
