### PR TITLE
Staging next 2022-03-23

### LINKED ISSUE #166306: Inkscape fails to build on x86_64-darwin
### Describe the bug

See the [Hydra build failing the nixpkgs:trunk:unstable job](https://hydra.nixos.org/build/171114239):

```
[839/1006] Building CXX object src/CMakeFiles/inkscape_base.dir/style.cpp.o
FAILED: src/CMakeFiles/inkscape_base.dir/style.cpp.o 
/nix/store/cvz17hkb0wpbsyx58l4zcaamqs2bhlmz-clang-wrapper-11.1.0/bin/clang++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DHAVE_CONFIG_H -DWITH_CSSBLEND -DWITH_CSSCOMPOSITE -DWITH_MESH -DWITH_SVG2 -Dinkscape_base_EXPORTS -I/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/build/src -I/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/src -I/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339 -I/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/build/include -I/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/src/3rdparty/adaptagrams -isystem /nix/store/63kwin2fgn75gifvyw4ll1p7apcl61id-glib-2.72.0-dev/include/glib-2.0 -isystem /nix/store/j5ljn0cxh1pg2906217477swf8h34223-glib-2.72.0/lib/glib-2.0/include -isystem /nix/store/yq7zb9ab5j8zwjycbq1pka562f5f25zf-pango-1.50.6-dev/include/pango-1.0 -isystem /nix/store/w2kp0czx9hd53mq5kd9gh0acb5ysvw6w-harfbuzz-3.3.2-dev/include/harfbuzz -isystem /nix/store/ja09rl9a90jcjnlmmr130b5m76c5z56r-libsoup-2.74.2-dev/include/libsoup-2.4 -isystem /nix/store/6wrqyhsij3cc1d18dk0n3g3555khjp71-poppler-glib-22.03.0-dev/include/poppler -isystem /nix/store/8l4fgi8jx4kr1n0vnsp0q9izxd5a5f1j-librevenge-0.0.4/include/librevenge-0.0 -isystem /nix/store/28dcg5cia7y0nj6msi5gcf068wg2klxa-libwpg-0.3.3/include/libwpg-0.3 -isystem /nix/store/1nfq6641dyapwwvdf9ph1wna8qk9sr6b-libvisio-0.1.7-dev/include/libvisio-0.1 -isystem /nix/store/iych9mrjnhj5n9kkrzkh50fsa56hi26q-libcdr-0.1.6/include/libcdr-0.1 -isystem /nix/store/dip52q07kxfxi8y29rr63c783gv3417v-gtk+3-3.24.33-dev/include/gtk-3.0 -isystem /nix/store/qg48ifvr5an4g42qaki89swg7fnwhya2-atk-2.36.0-dev/include/atk-1.0 -isystem /nix/store/4hq3i5yp8qlyi4hhwg2chb45fq3c3sfg-gdk-pixbuf-2.42.8-dev/include/gdk-pixbuf-2.0 -isystem /nix/store/l9aw1w85sffhc1w6did8f6f7bda9smwi-gtk-mac-integration-3.0.1/include/gtkmacintegration -isystem /nix/store/94n817nj55qv1icj933rj0gf4cyhhcn1-glibmm-2.66.2-dev/include/giomm-2.4 -isystem /nix/store/yf15dyg5c229bj5b4vsb48kny4wwyk6d-glibmm-2.66.2/lib/giomm-2.4/include -isystem /nix/store/94n817nj55qv1icj933rj0gf4cyhhcn1-glibmm-2.66.2-dev/include/glibmm-2.4 -isystem /nix/store/yf15dyg5c229bj5b4vsb48kny4wwyk6d-glibmm-2.66.2/lib/glibmm-2.4/include -isystem /nix/store/vhh9brdbws5c0b5ygzlslvd50vipr9f9-libsigc++-2.10.8/include/sigc++-2.0 -isystem /nix/store/vhh9brdbws5c0b5ygzlslvd50vipr9f9-libsigc++-2.10.8/lib/sigc++-2.0/include -isystem /nix/store/indb1fvl5cdkq2kz0kj2nq4dflcplj2m-gtkmm-3.24.5-dev/include/gtkmm-3.0 -isystem /nix/store/v2g2khwmwwp3wjyizg7f0paxbs1q5pd9-gtkmm-3.24.5/lib/gtkmm-3.0/include -isystem /nix/store/indb1fvl5cdkq2kz0kj2nq4dflcplj2m-gtkmm-3.24.5-dev/include/gdkmm-3.0 -isystem /nix/store/v2g2khwmwwp3wjyizg7f0paxbs1q5pd9-gtkmm-3.24.5/lib/gdkmm-3.0/include -isystem /nix/store/dip52q07kxfxi8y29rr63c783gv3417v-gtk+3-3.24.33-dev/include/gtk-3.0/unix-print -isystem /nix/store/hsr1hsb23scwlfh1lr456cm4arh3hi7p-atkmm-2.28.2-dev/include/atkmm-1.6 -isystem /nix/store/4nahfi7pqxm88ms0xmr05rli58xlq2v2-atkmm-2.28.2/lib/atkmm-1.6/include -isystem /nix/store/9qps6qrln13s0jc996cs67hclvvq5lvf-cairomm-1.14.3-dev/include/cairomm-1.0 -isystem /nix/store/j9a8wlpjvjdn8magy5gm6ws06hqfa68l-cairomm-1.14.3/lib/cairomm-1.0/include -isystem /nix/store/9gn4iihhn1kb7wgjvhkkfj9rsifpyk7j-pangomm-2.46.2-dev/include/pangomm-1.4 -isystem /nix/store/1kgvh1b8yg7p8i61a2rvsqn1b1s63v8r-pangomm-2.46.2/lib/pangomm-1.4/include -isystem /nix/store/2pnymg9dw0z1p1hpc08m4ibdiz2c8rk8-libxml2-2.9.13-dev/include/libxml2 -isystem /nix/store/gi8mcwhd7rhslav6zcr5qzyj072pklrp-lib2geom-1.1-dev/include/2geom-1.1.0 -DG_DISABLE_ASSERT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Werror=format -Werror=format-security -Wno-switch -O3 -DNDEBUG -fPIC   -fPIC -fdiagnostics-color -std=gnu++17 -MD -MT src/CMakeFiles/inkscape_base.dir/style.cpp.o -MF src/CMakeFiles/inkscape_base.dir/style.cpp.o.d -o src/CMakeFiles/inkscape_base.dir/style.cpp.o -c /tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/src/style.cpp
/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/src/style.cpp:687:13: error: cannot initialize a parameter of type 'int *' with an rvalue of type 'void *'
            g_warning_once("attribute 'clip-path' given as CSS");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/63kwin2fgn75gifvyw4ll1p7apcl61id-glib-2.72.0-dev/include/glib-2.0/glib/gmessages.h:490:9: note: expanded from macro 'g_warning_once'
    if (g_atomic_int_compare_and_exchange (&G_PASTE (_GWarningOnceBoolean, __LINE__), \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/63kwin2fgn75gifvyw4ll1p7apcl61id-glib-2.72.0-dev/include/glib-2.0/glib/gatomic.h:160:44: note: expanded from macro 'g_atomic_int_compare_and_exchange'
    __atomic_compare_exchange_n ((atomic), (void *) (&(gaicae_oldval)), (newval), FALSE, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST) ? TRUE : FALSE; \
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/nix-build-inkscape-1.1.2.drv-0/inkscape-1.1.2_2022-02-04_0a00cf5339/src/style.cpp:698:13: error: cannot initialize a parameter of type 'int *' with an rvalue of type 'void *'
            g_warning_once("attribute 'mask' given as CSS");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/63kwin2fgn75gifvyw4ll1p7apcl61id-glib-2.72.0-dev/include/glib-2.0/glib/gmessages.h:490:9: note: expanded from macro 'g_warning_once'
    if (g_atomic_int_compare_and_exchange (&G_PASTE (_GWarningOnceBoolean, __LINE__), \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/63kwin2fgn75gifvyw4ll1p7apcl61id-glib-2.72.0-dev/include/glib-2.0/glib/gatomic.h:160:44: note: expanded from macro 'g_atomic_int_compare_and_exchange'
    __atomic_compare_exchange_n ((atomic), (void *) (&(gaicae_oldval)), (newval), FALSE, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST) ? TRUE : FALSE; \
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
ninja: build stopped: subcommand failed.
```

### Notify maintainers

cc @jtojnar @NixOS/darwin-maintainers

### PR DESCRIPTION
**Pull request by vcunat**
workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
constitutents: https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next

Previous staging-next: https://github.com/NixOS/nixpkgs/pull/161366

### CODE REVIEW

**Comment by NickCao** [comment]
ping @jtojnar, will gnome branch be ready within this cycle, (and if the version bump fixes build with meson 0.61)?

**Comment by jtojnar** [comment]
Yes, it fixes the Meson issue for the GNOME packages that were updated.

Today is the [release date](https://wiki.gnome.org/FortyTwo), and I have not seen any issues during a brief testing in a VM, so it might theoretically be good to go. But it would still be nice to have more people test it.

**Comment by vcunat** [comment]
Probably, though I don't expect many affected builds to happen in the next few hours.

**Comment by NickCao** [comment]
It seems that `elfutils` fails its test and is bring down everything.

**Comment by vcunat** [comment]
#160259

**Comment by mweinelt** [comment]
Correct.

```
848091a52b734f2fb30c0e185befc31a2f3733de is the first bad commit
commit 848091a52b734f2fb30c0e185befc31a2f3733de
Merge: ab0e692ac7d d6525567585
Author: Vladimír Čunát <v@cunat.cz>
Date:   Wed Mar 23 08:32:39 2022 +0100

    Merge #160259: separateDebugInfo: Use --strip-unneeded
    
    ...into staging

 .../setup-hooks/separate-debug-info.sh             |  2 +-
 pkgs/development/libraries/libpsl/default.nix      |  2 ++
 .../analysis/valgrind/debug-info-from-env.patch    | 31 ++++++++++++++++++++++
 .../tools/analysis/valgrind/default.nix            |  6 +++++
 4 files changed, 40 insertions(+), 1 deletion(-)
 create mode 100644 pkgs/development/tools/analysis/valgrind/debug-info-from-env.patch
bisect found first bad commit%    
```

**Comment by vcunat** [comment]
Sigh, openssl seems broken on both darwin platforms:
- https://hydra.nixos.org/log/j1xrg7iihy5hnhc69hjzr7x7wvd8h6sm-curl-7.82.0.drv
- https://hydra.nixos.org/log/0a98sm7zbbah3rpya511lqlwh5x29vmf-libcxxabi-11.1.0.drv

**Comment by yu-re-ka** [comment]
Video playback is broken in Firefox and Chromium, running in sway.
Using a Chromium from master does not fix it, so probably something related to the compositor or drm stack.

**Comment by yu-re-ka** [comment]
> Video playback is broken in Firefox and Chromium, running in sway. Using a Chromium from master does not fix it, so probably something related to the compositor or drm stack.

Nevermind, this was not related to any staging-next changes. Just some pulseaudio/pipewire issue and the video playback waiting for audo sync 😅

**Comment by vcunat** [comment]
I switched the `staging-small` jobset to this branch to get basic coverage before merging.  Right now the -small channel would get blocked on:
- [ ] some missing dependencies in installer tests (quite recurring issue): 
  https://hydra.nixos.org/eval/1753111#tabs-still-fail

**Comment by fabianhjr** [comment]
@vcunat, seems like a temp networking issue:

```
machine # error: unable to download 'https://salsa.debian.org/debian/keyutils/raw/4cecffcb8e2a2aa4ef41777ed40e4e4bcfb2e5bf/debian/patches/Make-build-reproducible.patch': Couldn't resolve host name (6)
machine # error: builder for '/nix/store/f450ks5xaq790h43nc5r78x69cr4721q-Make-build-reproducible.patch.drv' failed with exit code 1
```

**Comment by mweinelt** [comment]
> @vcunat, seems like a temp networking issue:
> 
> ```
> machine # error: unable to download 'https://salsa.debian.org/debian/keyutils/raw/4cecffcb8e2a2aa4ef41777ed40e4e4bcfb2e5bf/debian/patches/Make-build-reproducible.patch': Couldn't resolve host name (6)
> machine # error: builder for '/nix/store/f450ks5xaq790h43nc5r78x69cr4721q-Make-build-reproducible.patch.drv' failed with exit code 1
> ```

It looks to me like the failed DNS resolution is intended, because it is sandboxed.

**Comment by jtojnar** [comment]
> python2.2-pycairo, dependency of gimp, fails to build

https://github.com/NixOS/nixpkgs/issues/167216

**Comment by NANASHI0X74** [comment]
Hey guys, the manual doesn't really tell me about what needs to happen or at what times staging-next gets merged into main. When can we expect this to be merged? since nixpkgs-unstable has been blocked for nine days at this point

**Comment by mweinelt** [comment]
There are still regressions we need to take care of before this can get merged. See for example https://github.com/NixOS/nixpkgs/pull/165406#issuecomment-1087232711.

**Comment by NANASHI0X74** [comment]
> There are still regressions we need to take care of before this can get merged. See for example [#165406 (comment)](https://github.com/NixOS/nixpkgs/pull/165406#issuecomment-1087232711).

thanks 😅
I don't really know how to read the hydra jobs... Can you see the remaining issues in there?
Guess I should read the hydra documentation, right? 🙃😄

**Comment by Artturin** [comment]
> keyutils

i'll make a pr that inlines this in postPatch

**Comment by mweinelt** [comment]
> > 
> 
> ```
> machine # error: unable to download 'https://salsa.debian.org/debian/keyutils/raw/4cecffcb8e2a2aa4ef41777ed40e4e4bcfb2e5bf/debian/patches/Make-build-reproducible.patch': Couldn't resolve host name (6)
> machine # error: builder for '/nix/store/f450ks5xaq790h43nc5r78x69cr4721q-Make-build-reproducible.patch.drv' failed with exit code 1
> ```
> 
> i'll make a pr that inlines this in postPatch

The real question is why this started failing after it has been there for three years, so you'll be creating a workaround, not a fix.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/167346

**Comment by vcunat** [comment]
- [ ] `coq*` [is blocked](https://hydra.nixos.org/build/172080411) due to older `ocaml` not dealing with glibc-2.34 update.  Maybe ocaml versions are too old anyway?  /cc coq maintainers: @roconnor, @thoughtpolice, @vbgl, @Zimmi48.

**Comment by Zimmi48** [comment]
There are patches available for glibc-2.34 for all OCaml versions. See the patch files added in most directories of https://github.com/ocaml/opam-repository/tree/master/packages/ocaml-base-compiler in https://github.com/ocaml/opam-repository/commit/05035330325eb132d95446aecab07eddd88f110a.

**Comment by vbgl** [comment]
Thanks Théo for digging this up. Are you going to do a PR? If not, please let me know and I’ll do it ASAP.

**Comment by Zimmi48** [comment]
@vbgl No sorry, I am very short of time this week.

**Comment by vcunat** [comment]
Let's defer fixing the rest to `master`.

**Comment by vcunat** [comment]
Here you can see (transitive) build regressions for the three main platforms, total about two thousand: https://hydra.nixos.org/eval/1753470#tabs-now-fail
(for `@NANASHI0X74` or anyone)

**Comment by winterqt** [comment]
Seemingly, a change in this iteration is causing #167854, and I have absolutely no clue what change could be the culprit. Not sure if the correct route is to disable/patch the test for it to complete or not, I guess it depends on what change is causing this.

**Comment by sternenseemann** [comment]
This iteration seems to break `buildRustPackage` derivations that have an empty list of dependencies, e.g. `elfcat`. This is because the behavior of `cargo vendor` changed.

Before (first line is stderr of course):

```
To use vendored sources, add this to your .cargo/config.toml for this project:

[source.vendored-sources]
directory = "elfcat-1.0-vendor.tar.gz"
```

After (what you see is stderr, stdout is empty):

```
There is no dependency to vendor in this project.
```

This breaks the `cargo-vendor-normalise` script.

**Pull request merged**
