### PR TITLE
nixos/tests/gitlab: Add additional test cases

### PR DESCRIPTION
**Pull request by yayayayaka**
###### Description of changes
This PR implements the following additional test cases for gitlab:
- Creating regular users
- git clone over ssh and http
- git push over ssh
- Forking projects
- Creating and merging Merge Requests
- Opening and closing issues.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by yayayayaka — COMMENTED** [review]
I just discovered the `wait_until_succeeds` function.

In my test I had included delays all over the place because Gitlab's processing of requests is too slow to catch up. Marking as draft again to make some refactoring.

**Comment by yu-re-ka** [comment]
@ofborg eval

**Comment by yu-re-ka** [comment]
Oh, meh. The editorconfig checks are not done through ofborg. Maybe amend the last commit and force-push to restart the pipeline.

**Comment by zowoq** [comment]
The actions can be restarted manually, follow the details link and the re-run button is at the top.

https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

**Comment by yu-re-ka** [comment]
Okay. The only concern I would have is the additional time needed to run those tests, and that it might timeout in Hydra. For now it's probably fine since the new tests only take a little more time compared to the GitLab startup and backup/restore test. But we should keep an eye on that if we want to add more test cases in the future.

**Comment by talyz** [comment]
The tests fail on hydra either way, since the disk image exceeds the maximum output size (see https://hydra.nixos.org/build/174962912, for example). It's definitely a good idea to keep an eye on the time it takes to run the tests, though - if they timeout on ofBorg or our machines, they're not very useful either.

**Pull request merged**
