### PR TITLE
rapid-photo-downloader: 0.9.18 -> 0.9.34

### PR DESCRIPTION
**Pull request by callahad**
###### Description of changes

- Updates rapid-photo-downloader from 0.9.18 to 0.9.34. ([changelog](https://github.com/damonlynch/rapid-photo-downloader/blob/v0.9.34/CHANGES.md))
    - Major changes: support for iOS devices, better support for high DPI displays, drops dependency on rawkit which is unmaintained.
- Packages new dependency python3Packages.pyheif (https://github.com/carsales/pyheif)
- Packages new dependency python3Packages.show-in-file-manager (https://github.com/damonlynch/showinfilemanager)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marmay** [comment]
For me, this also fixes https://github.com/NixOS/nixpkgs/issues/208249

Maybe this should be backported to 22.11?

**Review by wegank — APPROVED** [review]

**Comment by Nebucatnetzer** [comment]
Would it be possible to have some sort of test if the application even starts?

**Comment by callahad** [comment]
We could try to invoke `rapid-photo-downloader --detailed-version` which at
least tries to initialize enough of the application that, iirc, it was
failing before this PR.

**Comment by Nebucatnetzer** [comment]
Might be worth a try.
Would be a shame if an update of another package breaks it again without anyone noticing.

**Comment by Nebucatnetzer** [comment]
BTW. is it just me or does this version take a really long time to start?
It seems to hang at the following step at each start:

```
DEBUG    Rebuilding photo combobox entries...
```

**Comment by dcarosone** [comment]
> We could try to invoke `rapid-photo-downloader --detailed-version` which at least tries to initialize enough of the application that, iirc, it was failing before this PR.

In #210262 I suggested usage / `--help` for the same purpose, and yes, `--{detailed,}-version` fail.

**Comment by Nebucatnetzer** [comment]
Any test is better than none.

**Comment by callahad** [comment]
I have added a minimal test, as requested, and force-pushed the branch.

I have verified that the test catches startup failures related to `gobject-introspection` and `strictDeps`.

The only change from the previously reviewed state is:

```patch
diff --git a/pkgs/applications/graphics/rapid-photo-downloader/default.nix b/pkgs/applications/graphics/rapid-photo-downloader/default.nix
index 5c99ab3d2cc..706992e2961 100644
--- a/pkgs/applications/graphics/rapid-photo-downloader/default.nix
+++ b/pkgs/applications/graphics/rapid-photo-downloader/default.nix
@@ -28,7 +28,12 @@ mkDerivationWith python3Packages.buildPythonApplication rec {
 
   # Package has no generally usable unit tests.
   # The included doctests expect specific, hardcoded hardware to be present.
-  doCheck = false;
+  # Instead, we just make sure the program runs enough to report its version.
+  checkPhase = ''
+    export XDG_DATA_HOME=$(mktemp -d)
+    export QT_QPA_PLATFORM=offscreen
+    $out/bin/rapid-photo-downloader --detailed-version
+  '';
 
   # NOTE: Without gobject-introspection in buildInputs and strictDeps = false,
   #       launching fails with:
```

**Comment by Nebucatnetzer** [comment]
Sounds great, thanks a ton for your work @callahad

**Comment by dcarosone** [comment]
What is necessary to get this approved / merged?  @FRidh @jonringer @jfrankenau

**Comment by dcarosone** [comment]
#180566 can be closed in favour of this / when this is merged

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 207166` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python310Packages.pyheif</li>
    <li>python310Packages.show-in-file-manager</li>
    <li>python311Packages.pyheif</li>
    <li>python311Packages.show-in-file-manager</li>
    <li>rapid-photo-downloader</li>
  </ul>
</details>

**Pull request merged**
