### PR TITLE
google-chrome: move independently of `chromium`, add jnsgruk as maintainer, remove leftover `google-chrome-{beta,dev}` code paths

### PR DESCRIPTION
**Pull request by emilylange**
## Description of changes

Please see the commit message bodies for details.

Security label, because this also contains the security fixes from #308358 (version 124.0.6367.118).

Thanks a lot @jnsgruk! :)
Feel free to ping me from time to time if you need help. I can't promise I'll respond (something something already at capacity) but don't feel like you are completely on your own.

I believe this will be extremely low maintenance (e.g. build fixes), besides the very frequent version bumps.

And @r-ryantm will likely help you as well :)

Though please keep in mind, that you need to add the backport label to all update PRs.

Ref #306010

cc @jnsgruk @primeos

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) 
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jnsgruk** [comment]
LGTM, assuming the test skipping/failures is normal?

**Review by jnsgruk — APPROVED** [review]

**Comment by emilylange** [comment]
> LGTM, assuming the test skipping/failures is normal?

Do you mean ofborg?
ofborg does not build unfree packages.
And `google-chrome` is unfree.

**Comment by jnsgruk** [comment]
Nice, then all good from my side!

**Comment by jnsgruk** [comment]
Result of `nixpkgs-review pr 308383` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>google-chrome</li>
    <li>netflix</li>
  </ul>
</details>

**Pull request merged**
