### PR TITLE
Eclipse modular

### PR DESCRIPTION
**Pull request by DamienCassou**
Continue the work started in #10852 by @muradu as he does not seem to take care of the comments there.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks, really nice! I was thinking about picking this up myself but haven't had the time recently.

I'm intending to do some work to allow simultaneous installation of several Eclipses (e.g., having both Scala-IDE and vanilla Eclipse installed at the same time) and would like to base that work on these improvements.

**Comment by DamienCassou** [comment]
I will merge that soon if nobody comments. Should I squash to get 1 commit?

**Comment by rycee** [comment]
I'm OK with either squashed or non-squashed. If you prefer to squash then I'd suggest adding a "Suggested-by: muradu" line to the commit message to add credit.

**Pull request merged**
