### PR TITLE
Adding elasticsearch8 to pkgs

### PR DESCRIPTION
**Pull request by sith-lord-vader**
###### Description of changes

Added Elasticsearch 8 (v8.6.1) package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtrees** [comment]
I am quite interested in this. What's the current status?

**Comment by abathur** [comment]
@sith-lord-vader are you still interested in advancing this?

**Comment by abathur** [comment]
Tentatively closing. Happy to reopen if you're still interested.

**Comment by Zaczero** [comment]
for people OK with doing manual install (8.17.2-linux-x86_64):

```nix
  elasticsearch' = with pkgs; stdenv.mkDerivation {
    pname = "elasticsearch";
    version = "8.17.2";
    src = fetchurl {
      url = "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.2-linux-x86_64.tar.gz";
      hash = "sha256-ayqi8UasO9p58hHSvx4T7/Ep5Q1dBJQeUTchIPoPv0c=";
    };
    patches = [ ./es-home-6.x.patch ];
    postPatch = ''
      substituteInPlace bin/elasticsearch-env --replace \
        "ES_CLASSPATH=\"\$ES_HOME/lib/*\"" \
        "ES_CLASSPATH=\"$out/lib/*\""

      substituteInPlace bin/elasticsearch-cli --replace \
        "ES_CLASSPATH=\"\$ES_CLASSPATH:\$ES_HOME/\$additional_classpath_directory/*\"" \
        "ES_CLASSPATH=\"\$ES_CLASSPATH:$out/\$additional_classpath_directory/*\""
    '';
    nativeBuildInputs = [ makeWrapper ] ++ lib.optional (!stdenv.hostPlatform.isDarwin) autoPatchelfHook;
    buildInputs = [ jre_headless util-linuxMinimal zlib ];
    runtimeDependencies = [ zlib ];
    installPhase = ''
      mkdir -p $out
      cp -R bin config lib modules plugins $out

      chmod +x $out/bin/*

      substituteInPlace $out/bin/elasticsearch \
        --replace 'bin/elasticsearch-keystore' "$out/bin/elasticsearch-keystore"

      wrapProgram $out/bin/elasticsearch \
        --prefix PATH : "${lib.makeBinPath [ util-linuxMinimal coreutils gnugrep ]}" \
        --set ES_JAVA_HOME "${jre_headless}"

      wrapProgram $out/bin/elasticsearch-plugin \
        --set ES_JAVA_HOME "${jre_headless}"
    '';
  };
```

you will need es-home-6.x.patch file from here https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/search/elasticsearch/es-home-6.x.patch

**Pull request closed without merging**
