### PR TITLE
haskellPackages.insert-ordered-containers: fix build

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Fix build package haskellPackages.insert-ordered-containers

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg build haskellPackages.insert-ordered-containers

**Comment by teto** [comment]
tested on my customized nixos-unstable (168d1031af4916354491a1b1dd103258cfd26c0e) but I get this :
```
unpacking source archive /nix/store/jrvhviygv1is89b7icqpsbbdf906acp3-jsprim-1.4.1.tgz
applying patch /nix/store/wwrwknavn8zmss326gq4hf4wxdgijwpj-insert-ordered-containers-fix-test.patch
patching file insert-ordered-containers.cabal
Hunk #1 FAILED at 21.
Hunk #2 FAILED at 70.
2 out of 2 hunks FAILED -- saving rejects to file insert-ordered-containers.cabal.rej
unpacking source archive /nix/store/ybi9kzivaj2f7n677ijm4nn45w275658-left-pad-1.3.0.tgz
note: keeping build directory '/tmp/nix-build-insert-ordered-containers-0.2.2.drv-1'
```
should I upgrade to master, add 8.6.4 to the patch ?

**Comment by Izorkin** [comment]
Checked patch in rev 168d1031af4 (latest nixos-unstable) - worked build

**Comment by teto** [comment]
yep didn't realize your commit removed the patch. For some reason home-manager didn't build with your patch, I have to investigate... tried to build just haskellPackages.insert-ordered-containers and it looked good. I am not confident enough in haskell to merge it but looks good.

**Review by teto — APPROVED** [review]

**Pull request merged**
