### PR TITLE
vowpalwabbit: fix build against boost-python.

### PR DESCRIPTION
**Pull request by danieldk**
Patch setup.py to look for libboost_python{Major}{Minor}. This fixes the build in unstable and 18.09.

###### Motivation for this change

Going through the list of #45960 I found that the Vowpal Wabbit Python module does not compile. This fixes compilation with Python 2.7 and 3.6.

Note: for some reason, boost is added to the build environment without boost-python, unless I explicitly add `python.pkgs.boost` as a dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danieldk** [comment]
The added commit should also fix the build on Darwin (tested on macOS 10.14 beta).

**Comment by xeji** [comment]
@GrahamcOfBorg build python2Packages.vowpalwabbit python3Packages.vowpalwabbit

**Comment by xeji** [comment]
This never built on aarch64 according to hydra logs, so would you please mark it as broken on aarch64 to get rid of one more failure?

**Comment by danieldk** [comment]
Ok, marked it broken on aarch64.

**Comment by xeji** [comment]
backported in  46f4a934dcc..b4479796e30

**Pull request merged**
