### PR TITLE
linux_6_4: drop (EOL)

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

It's still in kernels-org.json, because even if I remove it the update script will keep putting it back, but nothing references it, and it'll be removed from that file when kernels are next updated after it's been delisted from kernel.org.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by K900 — APPROVED** [review]

**Review by RaitoBezarius — APPROVED** [review]
Kernel: :heavy_check_mark:.
ZFS: :heavy_check_mark:.

**Comment by alyssais** [comment]
Hmm, not sure what to do about bcachefs.  Anybody know if https://github.com/NixOS/nixpkgs/pull/256638 is ready to go?

**Comment by RaitoBezarius** [comment]
> Hmm, not sure what to do about bcachefs. Anybody know if #256638 is ready to go?

I think it's 80-90% done, but isn't our bcachefs kernel some special 6.4-rebased tree of Kent?

**Comment by Mic92** [comment]
> Hmm, not sure what to do about bcachefs. Anybody know if #256638 is ready to go?

If we would drop it now, people would have to stick on the current nixpkgs revision as it would leave no way to upgrade the system when running on bcachefs. This seems worse than having the EOL kernel for a while longer and still being able to upgrade all other userspace software.

**Review by Ma27 — APPROVED** [review]
As soon as #256638 is on master, this should be good to go IMHO.

We'll also need a strategy for testing_bcachefs on 23.05 because this needs to be backported as well.

**Comment by alyssais** [comment]
I've fixed linux_testing_bcachefs by just inlining the linux_6_4 definition in its definition.  That way we don't keep the kernel around otherwise, but also don't break bcachefs while it's being updated.

**Comment by RaitoBezarius** [comment]
Good to go for me.

**Pull request merged**
