### PR TITLE
vimPlugins.lspsaga-nvim-original, add winbar-nvim

### PR DESCRIPTION
**Pull request by onsails**
This PR adds back lspsaga-nvim which was switched to a fork when the original plugin stopped maintenance. Now its maintainer is back, so does the plugin in nixpkgs

### CODE REVIEW

**Comment by figsoda** [comment]
maybe it is better to name it something like `lspsaga-nvim-glepnir` or `lspsaga-nvim-original`?

**Comment by onsails** [comment]
fixed, also added winbar-nvim plugin

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 205831` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.calendar</li>
  </ul>
</details>
<details>
  <summary>51 packages built:</summary>
  <ul>
    <li>vimPlugins.Navigator-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.calendar-vim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.dracula-vim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.ghcid</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lspsaga-nvim-original</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-luapad</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.vim-dasht</li>
    <li>vimPlugins.vim-jsdoc</li>
    <li>vimPlugins.winbar-nvim</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]
changes lgtm, just waiting for ofborg

**Pull request merged**
