### PR TITLE
jenkins: 2.93 -> 2.94

### PR DESCRIPTION
**Pull request by earldouglas**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
I wonder if it would be better if nixpkgs tracked Jenkins LTS releases. Currently we're tracking the weekly releases in both NixOS master and release-17.09, and it feels like a bit too much (IMHO). LTS releases get major updates every 12 weeks, followed by bug and security fixes.

https://jenkins.io/download/

Thoughs?

**Comment by earldouglas** [comment]
I'm fine with that, although I would want to make sure that LTS updates include all the latest security patches, which come frequently.

Is there anything bad about frequent updates to the Jenkins derivation, other than it feels noisy and costs PR review time?

**Comment by bjornfor** [comment]
Yes, LTS is supposed to get security fixes.

I get the feeling that the weekly updates also introduce bugs and security issues. (Just skimming through the changelogs.)

**Comment by earldouglas** [comment]
@bjornfor See #34948 for switching to LTS.

**Comment by coretemp** [comment]
A *good* solution to this issue is one where the last *50* releases of Jenkins can be installed via a binary method and *every* git version could be built from source by simply passing an optional parameter to the package. Since new versions come out each week, the only way to support this is if some daemon would push updates to the Jenkins expression automatically to nixpkgs.

Jenkins upstream cannot be trusted to consistently produce versions that are usable in production.

Once that infrastructure is in place, we can do automated upgrades of Jenkins that don't require any human in the loop anymore. 

The current approach in which a single version is sanctioned as being the best for every user of Jenkins does not match real world operations.

This PR is just a symptom of not having enough options. Instead of removing an option (the last weekly release), please do PRs which *add* options and expand capabilities.

**Comment by earldouglas** [comment]
> *every* git version could be built from source by simply passing an optional parameter to the package

As a start, I think this should be doable via a combination of #30588 and a package override.

**Pull request merged**
