### PR TITLE
pythonPackages.colorlog: 2.6.1 -> 3.1.0

### PR DESCRIPTION
**Pull request by dotlambda**
The disabled tests fail:

```
=================================== FAILURES ===================================
_____________________________ test_logging_module ______________________________

test_logger = <function test_logger.<locals>.function at 0x7ffff180ed08>

    def test_logging_module(test_logger):
>       test_logger(logging)

colorlog/tests/test_logging.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
colorlog/tests/conftest.py:36: in function
    assert_log_message(logger.debug, 'a debug message', capsys),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_function = <function debug at 0x7ffff2d92840>, message = 'a debug message'
capsys = <_pytest.capture.CaptureFixture object at 0x7ffff2a67550>

    def assert_log_message(log_function, message, capsys):
        """Call a log function and check the message has been output."""
        log_function(message)
        out, err = capsys.readouterr()
        # Print the output so that py.test shows it when a test fails
        print(err, end='', file=sys.stderr)
        # Assert the message send to the logger was output
>       assert message in err, 'Log message not output to STDERR'
E       AssertionError: Log message not output to STDERR
E       assert 'a debug message' in ''

colorlog/tests/conftest.py:22: AssertionError
------------------------------ Captured log call -------------------------------
conftest.py                 17 DEBUG    a debug message
_____________________________ test_colorlog_module _____________________________

test_logger = <function test_logger.<locals>.function at 0x7ffff180ed90>

    def test_colorlog_module(test_logger):
>       test_logger(colorlog)

colorlog/tests/test_logging.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
colorlog/tests/conftest.py:36: in function
    assert_log_message(logger.debug, 'a debug message', capsys),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_function = <function debug at 0x7ffff2abc400>, message = 'a debug message'
capsys = <_pytest.capture.CaptureFixture object at 0x7ffff2a67be0>

    def assert_log_message(log_function, message, capsys):
        """Call a log function and check the message has been output."""
        log_function(message)
        out, err = capsys.readouterr()
        # Print the output so that py.test shows it when a test fails
        print(err, end='', file=sys.stderr)
        # Assert the message send to the logger was output
>       assert message in err, 'Log message not output to STDERR'
E       AssertionError: Log message not output to STDERR
E       assert 'a debug message' in ''

colorlog/tests/conftest.py:22: AssertionError
------------------------------ Captured log call -------------------------------
logging.py                  33 DEBUG    a debug message
__________________________ test_colorlog_basicConfig ___________________________

test_logger = <function test_logger.<locals>.function at 0x7ffff180ef28>

    def test_colorlog_basicConfig(test_logger):
        colorlog.basicConfig()
>       test_logger(colorlog.getLogger())

colorlog/tests/test_logging.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
colorlog/tests/conftest.py:36: in function
    assert_log_message(logger.debug, 'a debug message', capsys),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_function = <bound method Logger.debug of <RootLogger root (WARNING)>>
message = 'a debug message'
capsys = <_pytest.capture.CaptureFixture object at 0x7ffff17d2550>

    def assert_log_message(log_function, message, capsys):
        """Call a log function and check the message has been output."""
        log_function(message)
        out, err = capsys.readouterr()
        # Print the output so that py.test shows it when a test fails
        print(err, end='', file=sys.stderr)
        # Assert the message send to the logger was output
>       assert message in err, 'Log message not output to STDERR'
E       AssertionError: Log message not output to STDERR
E       assert 'a debug message' in ''

colorlog/tests/conftest.py:22: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG:root:a debug message
===================== 3 failed, 24 passed in 0.19 seconds ======================
```
I don't understand what the problem is.
Maybe @FRidh can help.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Seems like a valid bug in their code.

**Comment by dotlambda** [comment]
I just opened borntyping/python-colorlog#56.

**Comment by dotlambda** [comment]
All issues are resolved.

**Comment by FRidh** [comment]
@GrahamcOfBorg build pythonPackages.colorlog python3Packages.colorlog

**Pull request merged**
