### PR TITLE
libvterm-neovim: 0.3.2 -> 0.3.3

### LINKED ISSUE #332: Build fails
```nix
error: builder for '/nix/store/y5v26pz21gmjph5gzy74jwx9zkwa8m7y-neovim-unwrapped-a5629ab.drv' failed with exit code 1;
       last 10 log lines:
       >   Could NOT find Libvterm: Found unsuitable version "0.3", but required is at
       >   least "0.3.3" (found
       >   /nix/store/flm0i7lbg0msqgdrkpgn69hxc2brb7p0-libvterm-neovim-0.3.2/include)
       > Call Stack (most recent call first):
       >   /nix/store/5h0akwq4cwlc3yp92i84nfgcxpv5xv79-cmake-3.26.4/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
       >   cmake/FindLibvterm.cmake:23 (find_package_handle_standard_args)
       >   src/nvim/CMakeLists.txt:31 (find_package)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/y5v26pz21gmjph5gzy74jwx9zkwa8m7y-neovim-unwrapped-a5629ab.drv'.
error: 1 dependencies of derivation '/nix/store/2pl3v4jpa5hwr0xa5gxh9m05cmjsb8lp-neovim-a5629ab.drv' failed to build
```

### PR DESCRIPTION
**Pull request by mrtnvgr**
## Description of changes

This PR updates `libvterm-neovim` package to 0.3.3 version.

Previous [source link](http://www.leonerd.org.uk/code/libvterm/) does not contain new version of this package.

Closes nix-community/neovim-nightly-overlay#332

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by traxys** [comment]
I see there already has been a merged PR targeting  `staging` for this: https://github.com/NixOS/nixpkgs/pull/257287

Though it's nearly a month old now, so staging seems to be lagging quite far

**Comment by mrtnvgr** [comment]
> I see there already has been a merged PR targeting  `staging` for this: https://github.com/NixOS/nixpkgs/pull/257287
> 
> Though it's nearly a month old now, so staging seems to be lagging quite far

Thank you, should I close this PR?

**Comment by traxys** [comment]
> > I see there already has been a merged PR targeting  `staging` for this: #257287
> > Though it's nearly a month old now, so staging seems to be lagging quite far
> 
> Thank you, should I close this PR?

I think, but I'm not really sure (I was just trying the same problem as you)

**Comment by teto** [comment]
There was a recent change to where the library lives so a PR might still make sense but it should target staging (dont forget to mark this as draft when doing so) https://github.com/neovim/neovim/commit/8405649f92a8a8eb254944eca15e8b0169cbb6fb .
This means the upstream neovim flake might be broken for a while unless a temporary patch exists. Can be fixed in the non-official overlay too.

**Comment by mrtnvgr** [comment]
fixed

**Pull request closed without merging**
