### PR TITLE
librewolf: add meta.mainProgram attribute

### PR DESCRIPTION
**Pull request by Guanran928**
## Description of changes
add meta.mainProgram attribute
it might or might not work

```
nixpkgs on  librewolf-mainprogram > nix build .#librewolf
nixpkgs on  librewolf-mainprogram took 12s > ./result/bin/librewolf
``` 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mattmelling** [comment]
`librewolf` will already run from `nix run nixpkgs#librewolf`.  See [nix run documentation](https://github.com/NixOS/nix/blob/2afe2e4fbc329c15a63e409c4ea71d845c56a712/src/nix/run.md?plain=1#L44).

**Comment by Guanran928** [comment]
> `librewolf` will already run from `nix run nixpkgs#librewolf`. See [nix run documentation](https://github.com/NixOS/nix/blob/2afe2e4fbc329c15a63e409c4ea71d845c56a712/src/nix/run.md?plain=1#L44).

I got this warning while trying to use LibreWolf with [nixpak](https://github.com/nixpak/nixpak)
```
building the system configuration...
warning: Git tree '/home/guanranwang/Documents/Projects/git-repos/github.com/Guanran928/flake' is dirty
trace: warning: getExe: Package "librewolf-unwrapped-119.0-5" does not have the meta.mainProgram attribute. We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold. If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away. Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
```

**Review by MikaelFangel — APPROVED** [review]
LGTM

**Comment by MikaelFangel** [comment]
@mattmelling I think that the documentation on nix run is a bit outdated because the assumption that pname and mainProgram is the same has been deprecated as can be seen in @Guanran928 warning message. (It can be found on line 149 in meta.nix last time I checked) ☺️

**Review by katexochen — APPROVED** [review]

**Comment by mattmelling** [comment]
> @mattmelling I think that the documentation on nix run is a bit outdated because the assumption that pname and mainProgram is the same has been deprecated

Thanks, TIL!

**Pull request merged**
