### PR TITLE
jfbview: 0.5.4 -> 0.5.5

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update generated by https://github.com/ryantm/nix-update tools. These checks were done:

- built on NixOS
- Warning: no binary found that responded to help or version flags. (This warning appears even if the package isn't expected to have binaries.)
- directory tree listing: https://gist.github.com/d0c7d347a8f411b60cafc2bc64a3bb19

### CODE REVIEW

**Comment by xeji** [comment]
This package  was marked broken in #36654 , but has recently been fixed according to upstream maintainer. @ryantm how does your tool handle packages marked as broken? Did it really successfully build this before making the PR (according to ofborg above it's still marked as broken). 
But in this case it might be worth trying to see if it builds with `broken=false`.

**Comment by ryantm** [comment]
@xeji I think my bot might be using my nixpkgs config which has

```
allowUnfree = true;
allowBroken = true;
```
in it.

It really successfully built it. See the directory tree listing for what is in the result.

**Comment by xeji** [comment]
Cool. Builds and seems to work. 
In  general, what do you think is the best way to handle this (probably rare) case: 
- let the bot set  `broken=false` after a successful build ?
- add a note in the PR that is requires human intervention ?
- just do nothing and hope someone notices before merging that `broken=true` ?

**Comment by ryantm** [comment]
I prefer the human intervention approach. I can use nix eval to check that broken is set and warn about it in the PR text.

**Comment by xeji** [comment]
Think so too. If it was broken it should be manually tested before merging.

**Comment by xeji** [comment]
Please remove these lines before merging, package is no longer broken:

```
# incompatible with latest mupdf, see https://github.com/jichu4n/JFBView/issues/17
broken = true;
```

**Comment by ryantm** [comment]
@xeji done.

**Pull request merged**
