### PR TITLE
Update awscli Package to 1.9.6

### PR DESCRIPTION
**Pull request by polynomial**
- Needed for apigateway interaction
- Requires botocore 1.3.6

### CODE REVIEW

**Comment by copumpkin** [comment]
Are you working against master? I think you might conflict with https://github.com/NixOS/nixpkgs/commit/21488c6e60882db7f4de5f874833e53a2b1cf7e1

**Comment by domenkozar** [comment]
@polynomial could you rebase on top of current master?

**Comment by domenkozar** [comment]
ping @polynomial

**Comment by domenkozar** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/8a84a8019341d7933cfa00647255e3c523cf997d

**Comment by copumpkin** [comment]
@domenkozar wow, you're on fire. I was just digging up this ticket so I could update it myself :smile:

**Pull request closed without merging**
