### PR TITLE
Revert "mullvad-vpn: 2022.2 -> 2022.3"

### PR DESCRIPTION
**Pull request by figsoda**
Reverts NixOS/nixpkgs#185983

https://github.com/NixOS/nixpkgs/pull/185983#issuecomment-1214323193

### CODE REVIEW

**Comment by figsoda** [comment]
It's working for me, but perhaps it's better to revert first and then investigate the issue

**Comment by felschr** [comment]
I'm not sure, I also run `dnscrypt-proxy2` & have some extra IPv6 configuration. It could be something specific with my configuration. Could also be related to #183295, even though I only started getting this issue with 2022.3, while 2022.2 was working fine for me.

**Comment by felschr** [comment]
Here are my logs:

<details>
  <summary><code>/var/log/mullvad-vpn/daemon.log</code></summary>

```
[2022-08-14 11:39:13.818][mullvad_api::address_cache][DEBUG] Loading API addresses from /var/cache/mullvad-vpn/api-ip-address.txt
[2022-08-14 11:39:13.818][mullvad_api][ERROR] Error: Failed to load cached API addresses. Falling back on bundled address
Caused by: Failed to parse the address cache file
[2022-08-14 11:39:13.818][mullvad_api::address_cache][DEBUG] Using API address: [REDACTED]:443
[2022-08-14 11:39:13.818][mullvad_api::availability][DEBUG] Suspending API requests
[2022-08-14 11:39:13.818][mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
[2022-08-14 11:39:13.818][mullvad_relay_selector][DEBUG] Reading relays from /var/cache/mullvad-vpn/relays.json
[2022-08-14 11:39:13.827][mullvad_relay_selector][DEBUG] Reading relays from /nix/store/47rmljgck3hfc4wcl06lp350sk4b7633-mullvad-vpn-2022.2/share/mullvad/resources/relays.json
[2022-08-14 11:39:13.837][mullvad_relay_selector][INFO] Initialized with 870 cached relays from 2022-08-14 09:28:37.708
[2022-08-14 11:39:13.844][mullvad_api::availability][DEBUG] Pausing background API requests
[2022-08-14 11:39:13.844][mullvad_daemon::account_history][INFO] Opening account history file in /etc/mullvad-vpn/account-history.json
[2022-08-14 11:39:13.844][mullvad_api::access][DEBUG] Fetching access token for an account
[2022-08-14 11:39:13.844][mullvad_daemon::target_state][DEBUG] No cached target state to load
[2022-08-14 11:39:13.844][talpid_core::firewall][INFO] Resetting firewall policy
[2022-08-14 11:39:13.844][talpid_core::firewall::imp][DEBUG] Removing table and chain from netfilter
[2022-08-14 11:39:13.844][mullvad_daemon::version_check][DEBUG] Loading version check cache from /var/cache/mullvad-vpn/version-info.json
[2022-08-14 11:39:13.844][mullvad_daemon::version_check][WARN] Error: Unable to load cached version info
Caused by: Clearing version check cache due to a version mismatch
[2022-08-14 11:39:13.844][mullvad_api::availability][DEBUG] Unsuspending API requests
[2022-08-14 11:39:14.006][mullvad_api::availability][DEBUG] Resuming background API requests
[2022-08-14 11:39:14.037][mullvad_relay_selector::updater][DEBUG] Relay list is up-to-date
[2022-08-14 11:39:14.809][mullvad_daemon::management_interface][DEBUG] get_account_history
[2022-08-14 11:39:14.810][mullvad_daemon::management_interface][DEBUG] get_tunnel_state
[2022-08-14 11:39:14.815][mullvad_daemon::management_interface][DEBUG] get_tunnel_state
[2022-08-14 11:39:14.817][mullvad_daemon::management_interface][DEBUG] set_block_when_disconnected(true)
[2022-08-14 11:39:14.817][mullvad_daemon::settings][DEBUG] Writing settings to /etc/mullvad-vpn/settings.json
[2022-08-14 11:39:14.824][mullvad_daemon::management_interface][DEBUG] Broadcasting new settings
[2022-08-14 11:39:14.824][talpid_core::firewall][INFO] Applying firewall policy: Blocked. Allowing LAN. Allowing endpoint 45.83.222.100:443/TCP
[2022-08-14 11:39:14.826][mullvad_daemon::management_interface][DEBUG] get_settings
[2022-08-14 11:39:14.826][mullvad_daemon::management_interface][DEBUG] set_dns_options(DnsOptions { state: Default, default_options: DefaultDnsOptions { block_ads: true, block_trackers: true, block_malware: true, block_adult_content: false, block_gambling: false }, custom_options: CustomDnsOptions { addresses: [] } })
[2022-08-14 11:39:14.829][mullvad_daemon::management_interface][DEBUG] set_allow_lan(true)
[2022-08-14 11:39:14.831][mullvad_daemon::management_interface][DEBUG] set_enable_ipv6(true)
[2022-08-14 11:39:14.832][mullvad_daemon::management_interface][DEBUG] get_device
[2022-08-14 11:39:14.833][mullvad_daemon::management_interface][DEBUG] update_relay_settings
[2022-08-14 11:39:14.835][mullvad_daemon::management_interface][DEBUG] get_relay_locations
[2022-08-14 11:39:14.837][mullvad_daemon::management_interface][DEBUG] update_relay_settings
[2022-08-14 11:39:14.839][mullvad_daemon::management_interface][DEBUG] get_settings
[2022-08-14 11:39:14.839][mullvad_daemon::management_interface][DEBUG] get_account_history
[2022-08-14 11:39:14.839][mullvad_daemon::management_interface][DEBUG] get_account_data
[2022-08-14 11:39:14.839][mullvad_daemon::management_interface][DEBUG] update_device
[2022-08-14 11:39:14.841][mullvad_daemon::management_interface][DEBUG] get_current_location
[2022-08-14 11:39:14.841][mullvad_api::rest][ERROR] Error: HTTP request failed
Caused by: Hyper error
Caused by: error trying to connect: Network is unreachable (os error 101)
Caused by: Network is unreachable (os error 101)
[2022-08-14 11:39:14.841][mullvad_api::rest][ERROR] Error: HTTP request failed
Caused by: Hyper error
Caused by: error trying to connect: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
[2022-08-14 11:39:14.841][mullvad_daemon][WARN] Unable to fetch GeoIP location: Error: Hyper error
Caused by: error trying to connect: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
[2022-08-14 11:39:14.845][mullvad_daemon::management_interface][DEBUG] get_relay_locations
[2022-08-14 11:39:14.884][mullvad_daemon::management_interface][DEBUG] get_current_version
[2022-08-14 11:39:14.924][mullvad_daemon::device][DEBUG] The current device is still valid
[2022-08-14 11:39:46.444][mullvad_daemon::management_interface][DEBUG] connect_tunnel
[2022-08-14 11:39:46.444][mullvad_daemon][DEBUG] Target state Unsecured => Secured
[2022-08-14 11:39:46.445][mullvad_relay_selector][INFO] Selected relay de21-wireguard at [REDACTED]
[2022-08-14 11:39:46.445][talpid_core::firewall][INFO] Applying firewall policy: Connecting to [REDACTED]/UDP, Allowing LAN, interface: none. Allowing endpoint [REDACTED]/TCP
[2022-08-14 11:39:46.446][mullvad_daemon][DEBUG] New tunnel state: Connecting { endpoint: TunnelEndpoint { endpoint: Endpoint { address: [REDACTED], protocol: Udp }, tunnel_type: Wireguard, proxy: None, obfuscation: None, entry_endpoint: None }, location: Some(GeoIpLocation { ipv4: None, ipv6: None, country: "[REDACTED]", city: Some("[REDACTED]"), latitude: [REDACTED], longitude: [REDACTED], mullvad_exit_ip: true, hostname: Some("[REDACTED]"), bridge_hostname: None, entry_hostname: None, obfuscator_hostname: None }) }
[2022-08-14 11:39:46.448][talpid_core::tunnel::wireguard][DEBUG] Using kernel WireGuard implementation
[2022-08-14 11:39:46.448][talpid_core::firewall][INFO] Applying firewall policy: Connecting to [REDACTED]/UDP over "wg-mullvad" (ip: [REDACTED], v4 gw: [REDACTED], v6 gw: Some([REDACTED])), Allowing LAN. Allowing endpoint [REDACTED]/TCP
[2022-08-14 11:39:46.449][talpid_core::routing::imp::imp][DEBUG] Adding routes: {RequiredRoute { prefix: V4(Ipv4Network { addr: [REDACTED], prefix: 32 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 254 }, RequiredRoute { prefix: V6(Ipv6Network { addr: [REDACTED], prefix: 128 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 254 }}
[2022-08-14 11:39:46.499][talpid_core::routing::imp::imp][DEBUG] Adding routes: {RequiredRoute { prefix: V4(Ipv4Network { addr: 0.0.0.0, prefix: 0 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 1836018789 }, RequiredRoute { prefix: V6(Ipv6Network { addr: ::, prefix: 0 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 1836018789 }}
[2022-08-14 11:39:46.499][talpid_core::firewall][INFO] Applying firewall policy: Connected to [REDACTED]/UDP over "wg-mullvad" (ip: [REDACTED],[REDACTED], v4 gw: [REDACTED], v6 gw: Some([REDACTED])), Allowing LAN
[2022-08-14 11:39:46.500][talpid_core::dns][INFO] Setting DNS servers to [REDACTED]
[2022-08-14 11:39:46.501][talpid_core::dns::imp::static_resolv_conf][DEBUG] No DNS state backup to restore
[2022-08-14 11:39:46.501][talpid_core::dns::imp][DEBUG] Managing DNS via /etc/resolv.conf
[2022-08-14 11:39:46.501][mullvad_daemon][DEBUG] New tunnel state: Connected { endpoint: TunnelEndpoint { endpoint: Endpoint { address: [REDACTED], protocol: Udp }, tunnel_type: Wireguard, proxy: None, obfuscation: None, entry_endpoint: None }, location: Some(GeoIpLocation { ipv4: None, ipv6: None, country: "[REDACTED]", city: Some("[REDACTED]"), latitude: [REDACTED], longitude: [REDACTED], mullvad_exit_ip: true, hostname: Some("[REDACTED]"), bridge_hostname: None, entry_hostname: None, obfuscator_hostname: None }) }
[2022-08-14 11:39:46.503][mullvad_daemon::management_interface][DEBUG] get_current_location
[2022-08-14 11:39:47.442][mullvad_daemon::management_interface][DEBUG] disconnect_tunnel
[2022-08-14 11:39:47.442][mullvad_daemon][DEBUG] Target state Secured => Unsecured
[2022-08-14 11:39:47.442][talpid_core::dns][INFO] Resetting DNS
[2022-08-14 11:39:47.442][talpid_core::routing::imp::imp][DEBUG] Clearing routes
[2022-08-14 11:39:47.443][mullvad_daemon][DEBUG] New tunnel state: Disconnecting(Nothing)
[2022-08-14 11:39:47.443][talpid_core::tunnel::wireguard::wireguard_kernel::netlink_tunnel][ERROR] Failed to remove WireGuard device: Failed to delete device
[2022-08-14 11:39:47.443][talpid_core::tunnel::wireguard][ERROR] Error: Failed to stop tunnel
Caused by: Failed to start wireguard tunnel
[2022-08-14 11:39:47.443][talpid_core::tunnel_state_machine::connecting_state][DEBUG] Tunnel monitor exited with block reason: None
[2022-08-14 11:39:47.446][talpid_core::firewall][INFO] Applying firewall policy: Blocked. Allowing LAN. Allowing endpoint 45.83.222.100:443/TCP
[2022-08-14 11:39:47.447][mullvad_daemon][DEBUG] New tunnel state: Disconnected
[2022-08-14 11:39:47.450][mullvad_daemon::management_interface][DEBUG] get_current_location
[2022-08-14 11:39:47.450][mullvad_api::rest][ERROR] Error: HTTP request failed
Caused by: Hyper error
Caused by: error trying to connect: Network is unreachable (os error 101)
Caused by: Network is unreachable (os error 101)
[2022-08-14 11:39:47.450][mullvad_api::rest][ERROR] Error: HTTP request failed
Caused by: Hyper error
Caused by: error trying to connect: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
[2022-08-14 11:39:47.450][mullvad_daemon][WARN] Unable to fetch GeoIP location: Error: Hyper error
Caused by: error trying to connect: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
[2022-08-14 11:39:52.397][mullvad_daemon::management_interface][DEBUG] set_block_when_disconnected(false)
[2022-08-14 11:39:52.397][mullvad_daemon::settings][DEBUG] Writing settings to /etc/mullvad-vpn/settings.json
[2022-08-14 11:39:52.412][mullvad_daemon::management_interface][DEBUG] Broadcasting new settings
[2022-08-14 11:39:52.412][talpid_core::firewall][INFO] Resetting firewall policy
[2022-08-14 11:39:52.412][talpid_core::firewall::imp][DEBUG] Removing table and chain from netfilter
[2022-08-14 11:42:25.689][mullvad_daemon::management_interface][DEBUG] connect_tunnel
[2022-08-14 11:42:25.689][mullvad_daemon][DEBUG] Target state Unsecured => Secured
[2022-08-14 11:42:25.689][mullvad_relay_selector][INFO] Selected relay de21-wireguard at [REDACTED]
[2022-08-14 11:42:25.690][talpid_core::firewall][INFO] Applying firewall policy: Connecting to [REDACTED]/UDP, Allowing LAN, interface: none. Allowing endpoint [REDACTED]/TCP
[2022-08-14 11:42:25.691][mullvad_daemon][DEBUG] New tunnel state: Connecting { endpoint: TunnelEndpoint { endpoint: Endpoint { address: [REDACTED], protocol: Udp }, tunnel_type: Wireguard, proxy: None, obfuscation: None, entry_endpoint: None }, location: Some(GeoIpLocation { ipv4: None, ipv6: None, country: "[REDACTED]", city: Some("[REDACTED]"), latitude: [REDACTED], longitude: [REDACTED], mullvad_exit_ip: true, hostname: Some("[REDACTED]"), bridge_hostname: None, entry_hostname: None, obfuscator_hostname: None }) }
[2022-08-14 11:42:25.692][talpid_core::tunnel::wireguard][DEBUG] Using kernel WireGuard implementation
[2022-08-14 11:42:25.692][talpid_core::firewall][INFO] Applying firewall policy: Connecting to [REDACTED]/UDP over "wg-mullvad" (ip: [REDACTED],[REDACTED], v4 gw: [REDACTED], v6 gw: Some([REDACTED])), Allowing LAN. Allowing endpoint [REDACTED]/TCP
[2022-08-14 11:42:25.692][talpid_core::routing::imp::imp][DEBUG] Adding routes: {RequiredRoute { prefix: V6(Ipv6Network { addr: fc00:bbbb:bbbb:bb01::1, prefix: 128 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 254 }, RequiredRoute { prefix: V4(Ipv4Network { addr: [REDACTED], prefix: 32 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 254 }}
[2022-08-14 11:42:25.743][talpid_core::routing::imp::imp][DEBUG] Adding routes: {RequiredRoute { prefix: V4(Ipv4Network { addr: 0.0.0.0, prefix: 0 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 1836018789 }, RequiredRoute { prefix: V6(Ipv6Network { addr: ::, prefix: 0 }), node: RealNode(Node { ip: None, device: Some("wg-mullvad") }), table_id: 1836018789 }}
[2022-08-14 11:42:25.743][talpid_core::firewall][INFO] Applying firewall policy: Connected to [REDACTED]/UDP over "wg-mullvad" (ip: [REDACTED],[REDACTED], v4 gw: [REDACTED], v6 gw: Some([REDACTED])), Allowing LAN
[2022-08-14 11:42:25.744][talpid_core::dns][INFO] Setting DNS servers to [REDACTED]
[2022-08-14 11:42:25.744][talpid_core::dns::imp::static_resolv_conf][DEBUG] No DNS state backup to restore
[2022-08-14 11:42:25.744][talpid_core::dns::imp][DEBUG] Managing DNS via /etc/resolv.conf
[2022-08-14 11:42:25.745][mullvad_daemon][DEBUG] New tunnel state: Connected { endpoint: TunnelEndpoint { endpoint: Endpoint { address: [REDACTED], protocol: Udp }, tunnel_type: Wireguard, proxy: None, obfuscation: None, entry_endpoint: None }, location: Some(GeoIpLocation { ipv4: None, ipv6: None, country: "[REDACTED]", city: Some("[REDACTED]"), latitude: [REDACTED], longitude: [REDACTED], mullvad_exit_ip: true, hostname: Some("[REDACTED]"), bridge_hostname: None, entry_hostname: None, obfuscator_hostname: None }) }
[2022-08-14 11:42:25.747][mullvad_daemon::management_interface][DEBUG] get_current_location
[2022-08-14 11:42:37.276][mullvad_daemon::management_interface][DEBUG] disconnect_tunnel
[2022-08-14 11:42:37.276][mullvad_daemon][DEBUG] Target state Secured => Unsecured
[2022-08-14 11:42:37.276][talpid_core::dns][INFO] Resetting DNS
[2022-08-14 11:42:37.277][talpid_core::routing::imp::imp][DEBUG] Clearing routes
[2022-08-14 11:42:37.277][mullvad_daemon][DEBUG] New tunnel state: Disconnecting(Nothing)
[2022-08-14 11:42:37.277][talpid_core::tunnel::wireguard::wireguard_kernel::netlink_tunnel][ERROR] Failed to remove WireGuard device: Failed to delete device
[2022-08-14 11:42:37.277][talpid_core::tunnel::wireguard][ERROR] Error: Failed to stop tunnel
Caused by: Failed to start wireguard tunnel
[2022-08-14 11:42:37.277][talpid_core::tunnel_state_machine::connecting_state][DEBUG] Tunnel monitor exited with block reason: None
[2022-08-14 11:42:37.277][talpid_core::firewall][INFO] Resetting firewall policy
[2022-08-14 11:42:37.277][talpid_core::firewall::imp][DEBUG] Removing table and chain from netfilter
[2022-08-14 11:42:37.277][mullvad_daemon][DEBUG] New tunnel state: Disconnected
[2022-08-14 11:42:37.291][mullvad_daemon::management_interface][DEBUG] get_current_location
[2022-08-14 11:42:37.291][mullvad_api::rest][ERROR] Error: HTTP request failed
Caused by: Hyper error
Caused by: error trying to connect: Network is unreachable (os error 101)
Caused by: Network is unreachable (os error 101)
[2022-08-14 11:48:28.747][mullvad_daemon::shutdown::platform][DEBUG] Process received signal: [Term]
[2022-08-14 11:48:28.747][talpid_core::dns][INFO] Resetting DNS
[2022-08-14 11:48:28.747][talpid_core::tunnel_state_machine][DEBUG] Exiting tunnel state machine loop
[2022-08-14 11:48:28.750][mullvad_daemon::device][DEBUG] Account manager has stopped
[2022-08-14 11:48:28.750][talpid_core::tunnel_state_machine][INFO] Tunnel state machine shut down
[2022-08-14 11:48:28.752][mullvad_daemon][INFO] Mullvad daemon is quitting
[2022-08-14 11:48:28.755][mullvad_daemon::management_interface][INFO] Management interface shut down
[2022-08-14 11:48:29.252][mullvad_daemon][DEBUG] Process exiting with code 0
```
</details>

**Review by felschr — APPROVED** [review]
Alright, let's revert this. It seems to be an upstream issue:
https://github.com/mullvad/mullvadvpn-app/issues/3841

**Comment by SuperSandro2000** [comment]
> perhaps it's better to revert first and then investigate the issue

Not really. We should first understand what and how something is broken and then try to understand it instead of blindly reverting an update. If we fail to understand why something is broken then it is fine to revert an update.

> Alright, let's revert this. It seems to be an upstream issue:
> [mullvad/mullvadvpn-app#3841](https://github.com/mullvad/mullvadvpn-app/issues/3841)

If there is an upstream issue that is generally affecting the software then this is a good reason to revert an update. Even better would be if we added a comment so that we know a certain version if broken and we shouldn't update to it again.

**Pull request merged**
