### PR TITLE
virtualbox: Fetch patches from the bug tracker.

### PR DESCRIPTION
**Pull request by ambrop72**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Synthetica9** [comment]
You can probably remove the comments pointing to the tickets now, I'd say it's clear from the URL

**Comment by ambrop72** [comment]
It's not obvious how to get to the ticket, one would need to go hunting for the bug tracker URL and entering a ticker number extracted from the attachment URL.

**Comment by veprbl** [comment]
Why do we want to do this? Since the patches are already in our git, there isn't any benefit to switch to fetching them because the price is already paid.

**Comment by ambrop72** [comment]
Well there were complaints that they should be fatched, so if this is merged they will be :) I suppose it would benefit channel users which don't get nixpkgs via git. If this is not needed I can close this PR.

**Comment by veprbl** [comment]
> Well there were complaints

Where can we see those?

**Comment by ambrop72** [comment]
https://github.com/NixOS/nixpkgs/pull/60943#discussion_r282875857
Anyway either merge this, or close it.

**Comment by veprbl** [comment]
Yes, that's right, in the future please try to use `fetchpatch` whenever possible. It is too late to switch now, because, as I said, those patches are already in nixpkgs git repo. Also it's not a big deal since they are tiny files anyway. Thank you for the effort, though!

**Pull request closed without merging**
