### PR TITLE
python3Packages.httplib2: disable darwin incompatible test

### LINKED ISSUE #163535: azure-core fails tests on darwin
### Describe the bug

azure-core is failing to build on my local darwin (x86_64) installation, with 8 tests consistently failing. There's a lot of log output, but here's the tail of it.
```
=========================== short test summary info ============================
FAILED tests/test_rest_polling.py::test_put_operation_location_polling_fail
FAILED tests/test_rest_polling.py::test_put_location_polling_fail - azure.cor...
FAILED tests/test_rest_polling.py::test_patch_operation_location_polling_fail
FAILED tests/test_rest_polling.py::test_patch_location_polling_fail - azure.c...
FAILED tests/async_tests/test_rest_polling_async.py::test_put_operation_location_polling_fail
FAILED tests/async_tests/test_rest_polling_async.py::test_put_location_polling_fail
FAILED tests/async_tests/test_rest_polling_async.py::test_patch_operation_location_polling_fail
FAILED tests/async_tests/test_rest_polling_async.py::test_patch_location_polling_fail
========== 8 failed, 223 passed, 838 deselected, 7 warnings in 12.82s ==========
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x105563ac0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x105a2c100>, 13.31424405)]']
connector: <aiohttp.connector.TCPConnector object at 0x1055637f0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1058da2e0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1059f7c40>, 13.39427915)]']
connector: <aiohttp.connector.TCPConnector object at 0x1058da310>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10561fbe0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x105a2c8e0>, 13.433029846)]']
connector: <aiohttp.connector.TCPConnector object at 0x10589d160>
```
[(full logs)](https://github.com/NixOS/nixpkgs/files/8220609/log.txt)

### Steps To Reproduce

```nix build nixpkgs#python39Packages.azure-core``` on darwin (x86_64) (or against commit `d8cbebf2e95da44192e43552351c1ac65653392f`) (also fails in python310Packages)

### Notify maintainers

@jonringer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs-22.05pre346086.e5a50e8f299"`
 - nixpkgs: `/nix/store/30v8bmg615qsdbf2rq9ly53ryw0axjx0-source`
```

### PR DESCRIPTION
**Pull request by jonringer**
###### Description of changes

closes #163535

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build azure-cli

**Comment by happysalada** [comment]
I thought this had been previously disabled.
Thank you for the fix!

**Comment by malob** [comment]
@jonringer, happy to see this land on `master`, but just a heads up this fix was already done on staging in #162257, in case it needs to be reverted on that branch now that it's on `master`

**Comment by malob** [comment]
Also this did not resolve #163535 for me on `aarch64-darwin` (still waiting to see if the build for `x86_64-darwin` succeeds, but I doubt it will from previous tests I've run with this fix applied.)

**Comment by jonringer** [comment]
> Also this did not resolve #163535 for me on `aarch64-darwin` (still waiting to see if the build for `x86_64-darwin` succeeds, but I doubt it will from previous tests I've run with this fix applied.)

Interesting...

```
[11:55:11] jon@Jonathans-Mac-mini ~/projects/nixpkgs (fix-httplib2)
$ nix-build -A python3Packages.azure-core
/nix/store/k1xh7lygw6pkdfyi6apl3n2bk8bl7fa6-python3.9-azure-core-1.21.1
[11:55:28] jon@Jonathans-Mac-mini ~/projects/nixpkgs (fix-httplib2)
$ uname -a
Darwin Jonathans-Mac-mini.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```

**Comment by jonringer** [comment]
as for the staging vs master. Since this was already broken on master, it wasn't really introducing any more rebuilds, as there was no successful builds to begin with.

**Comment by malob** [comment]
@jonringer, here's the output on my machine:
```console
❯ nix build .#python3Packages.azure-core
error: builder for '/nix/store/chdvdv8l8pli3fhmvc81k1qjq0vzfxm7-python3.9-azure-core-1.21.1.drv' failed with exit code 1;
       last 10 log lines:
       > Unclosed client session
       > client_session: <aiohttp.client.ClientSession object at 0x103de7640>
       > Unclosed connector
       > connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x103dafa60>, 10.94721475)]']
       > connector: <aiohttp.connector.TCPConnector object at 0x103de74f0>
       > Unclosed client session
       > client_session: <aiohttp.client.ClientSession object at 0x103b5e220>
       > Unclosed connector
       > connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x103eed7c0>, 10.961111833)]']
       > connector: <aiohttp.connector.TCPConnector object at 0x103b5e940>
       For full logs, run 'nix log /nix/store/chdvdv8l8pli3fhmvc81k1qjq0vzfxm7-python3.9-azure-core-1.21.1.drv'.

❯ uname -a
Darwin MaloBookPro 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64 arm Darwin
```

Where those 8 tests are still the culprit for me:
```
=========================== short test summary info ============================
FAILED tests/test_rest_polling.py::test_put_operation_location_polling_fail
FAILED tests/test_rest_polling.py::test_put_location_polling_fail - azure.cor...
FAILED tests/test_rest_polling.py::test_patch_operation_location_polling_fail
FAILED tests/test_rest_polling.py::test_patch_location_polling_fail - azure.c...
FAILED tests/async_tests/test_rest_polling_async.py::test_put_operation_location_polling_fail
FAILED tests/async_tests/test_rest_polling_async.py::test_put_location_polling_fail
FAILED tests/async_tests/test_rest_polling_async.py::test_patch_operation_location_polling_fail
FAILED tests/async_tests/test_rest_polling_async.py::test_patch_location_polling_fail
========== 8 failed, 223 passed, 838 deselected, 9 warnings in 10.67s ==========
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x103e0c2e0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x103dcc4c0>, 10.898959458)]']
connector: <aiohttp.connector.TCPConnector object at 0x103e0c580>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x103de7640>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x103dafa60>, 10.94721475)]']
connector: <aiohttp.connector.TCPConnector object at 0x103de74f0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x103b5e220>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x103eed7c0>, 10.961111833)]']
connector: <aiohttp.connector.TCPConnector object at 0x103b5e940>
```

**Comment by choco** [comment]
Not sure if it's useful but I can confirm that on my M1 MacBook I get the same error and failing tests as @malob

**Comment by malob** [comment]
Chatted with @jonringer about this and I'm going to file a PR in the next hour or so disable the offending tests.

**Pull request merged**
