### PR TITLE
git: 2.11.1 -> 2.12.0

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
What's up with the signature of the commit?

**Comment by NeQuissimus** [comment]
That is a very good question, I did not change anything... Let me investigate...

**Comment by NeQuissimus** [comment]
Weird... I just `git reset`, `git commit`, `git push -f` and now it says everything is good...

**Comment by grahamc** [comment]
Merged in 7611525c008408be64b99e5b0517820cc578bde8

**Pull request closed without merging**
