### PR TITLE
pythonPackages.sphinx: 1.7.9 -> 1.8.2

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

A new sphinx release is out, sage needs patching.

@FRidh

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build python27Packages.sphinx python36Packages.sphinx

**Comment by timokau** [comment]
The python3 build fails because the dependency `pycodestyle` fails. That bisecting puts the cause of that at the upgrade from python 3.6.6 to python 3.6.7 (241bab3a5ed2f21d544dc66144f08f9ae203beb4).

**Comment by timokau** [comment]
Rebased, python3 issue still present.

**Comment by timokau** [comment]
Fails due to `python3.7-simplejson` now though.

**Comment by timokau** [comment]
@FRidh bisecting shows that c1e003ff2f8a43189d48b7194ec8556aa3d88641 (reduce amount of warnings when building with `buildPhyton`) broke the cython build. They test some verbose output. Example failures:

```
----------------------------------------------------------------------
File "/build/Cython-0.29/TEST_TMP/0/run/c/cdivision_CEP_516/cdivision_CEP_516.so", line ?, in cdivision_CEP_516.__test__.complex_ex>
Failed example:
    complex_expression(-150, 20, 19, -7)
Expected:
    verbose_call(20)
    division with oppositely signed operands, C and Python semantics differ
    verbose_call(19)
    division with oppositely signed operands, C and Python semantics differ
    -2
Got:
    verbose_call(20)
    division with oppositely signed operands, C and Python semantics differ
    verbose_call(19)
    -2
```

```
Failed example:
    div_int_c_warn(-17, 10)
Expected:
    division with oppositely signed operands, C and Python semantics differ
    -1
Got:
    -1
```

**Comment by timokau** [comment]
Okay should be good to go now. python3 build is still failing because the cython dependency fails on python3. That is because I messed up the cython upgrade. Didn't test it on python3 where it now needs the pycodestyle dependency for tests. I'll fix that in a separate PR.

@Synthetica9 I had to switch the pname to capital instead, which you changed recently. That is because pypi lists it with the capital name. Why did you change it initially?

**Comment by timokau** [comment]
Rebased. @FRidh (I still don't know what the policy for non-trivial python package changes is)

**Comment by timokau** [comment]
Rebased again. Ping @FRidh

**Comment by bgamari** [comment]
@FRidh, indeed it would be great to have this upstream.

**Comment by FRidh** [comment]
This got hidden in the long pile of review requests/mentions. I added a Sphinx update in https://github.com/NixOS/nixpkgs/pull/54186.

**Pull request closed without merging**
