### PR TITLE
libva, libva-utils and vaapiIntel: 2.0.0 -> 2.1.0 (VA-API: 1.0.0 -> 1.1.0)

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

General update. Note the API bump.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
@globin - should we send this via staging?

**Comment by fpletz** [comment]
Yep, to staging with this mass rebuild. :)

**Review by fpletz — APPROVED** [review]

**Comment by peterhoeg** [comment]
Are there other large rebuilds pending with which this should be merged to avoid rebuilding the world twice?

**Comment by vcunat** [comment]
Also /cc maintainer @garbas.

**Pull request merged**
