### PR TITLE
manuskript: fix broken Python dependencies, add me as maintainer

### PR DESCRIPTION
**Pull request by StillToad**
Pin the Python version for the manuskript package to 3.11 to fix broken dependencies. Also adding me as a maintainer.

## Description of changes

Manuskript previously used `python3Packages`, which defaulted to Python 3.12 or higher, causing a crash on startup. Pinning the version to 3.11 (`python311Packages`) resolves this issue. Manuskript is orphaned and has been for some time, so I'm adding myself as a maintainer.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gador** [comment]
`manuskript` builds for me locally on current `master` without changes.  
Please check locally and report back if this isn't the case for you. Also if you would still like to add yourself as maintainer, I'd be happy to merge after you drop the other commits :+1:

**Comment by StillToad** [comment]
> `manuskript` builds for me locally on current `master` without changes. Please check locally and report back if this isn't the case for you. Also if you would still like to add yourself as maintainer, I'd be happy to merge after you drop the other commits 👍

manuskript builds, but i wasn't able to launch it without pinning to python311Packages:
`📁 nixpkgs 🌿 manuskript-fix 💞  
🕒 01:52 PM💖 manuskript -v
Qt: Session management error: None of the authentication protocols specified are supported
INFO> Logging to file: /home/strawbee/.local/share/manuskript/manuskript/logs/2024-07-22_13-52-59_manuskript#520164.log
INFO> Operating System: Linux-6.6.41-x86_64-with-glibc2.39
INFO> Hardware: x86_64 / 
INFO> Running from unpackaged source code.
INFO> Manuskript 0.16.1 (Python 3.12.4)
INFO> * PyQt 5.15.9 (compiled against Qt 5.15.14)
INFO>   * Qt 5.15.14 (runtime)
INFO> * lxml.etree 5.2.2.0
INFO>   * libxml   2.12.7 (compiled: 2.12.7)
INFO>   * libxslt  1.1.41 (compiled: 1.1.41)
INFO> * pyEnchant N/A (libenchant: N/A)
INFO> * pySpellChecker N/A
INFO> * Symspellpy N/A
INFO> * Markdown N/A
INFO> Web rendering engine: QTextEdit
INFO> Preferred translation: ['en-US', 'en', 'en-Latn-US'] (based on available ui languages)
INFO> Using the builtin translation. (U.S. English)
Fatal Python error: Segmentation fault

Current thread 0x00007fafff8fb740 (most recent call first):
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/models/outlineModel.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/models/__init__.py", line 5 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/load_save/version_0.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/loadSave.py", line 9 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1415 in _handle_fromlist
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/mainWindow.py", line 18 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 995 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/main.py", line 177 in prepare
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/../manuskript/main.py", line 308 in run
  File "/nix/store/1k5imkl28cjsr5f6zh6nppxy2s18wxc2-manuskript-0.16.1/bin/.manuskript-wrapped", line 14 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtXml, PyQt5.QtWebChannel, PyQt5.QtTest, PyQt5.QtSvg, PyQt5.QtSql, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtQuick, PyQt5.QtQuickWidgets, PyQt5.QtPrintSupport, PyQt5.QtOpenGL, PyQt5.QtDBus, lxml._elementpath, lxml.etree (total: 17)
[1]    520164 segmentation fault (core dumped)  manuskript -v
`

**Comment by gador** [comment]
interesting. I wasn't able to find any pointers at the upstream project, nor any patches. I guess it is the easiest way to use the older `python311Packages`.
Please don't use a specific version on `manuskript` but change it in `top-level/all-packages.nix` like so:
```
  manuskript = libsForQt5.callPackage ../applications/editors/manuskript {
    python3Packages = python311Packages;
  };
```
If you can re-arrange your commit history like so would be awesome:

1. maintainers: add strawbee
2. manuskript: override python version
3. manuskript: add strawbee as maintainer

**Comment by StillToad** [comment]
> interesting. I wasn't able to find any pointers at the upstream project, nor any patches. I guess it is the easiest way to use the older `python311Packages`. Please don't use a specific version on `manuskript` but change it in `top-level/all-packages.nix` like so:
> 
> ```
>   manuskript = libsForQt5.callPackage ../applications/editors/manuskript {
>     python3Packages = python311Packages;
>   };
> ```
> 
> If you can re-arrange your commit history like so would be awesome:
> 
> 1. maintainers: add strawbee
> 2. manuskript: override python version
> 3. manuskript: add strawbee as maintainer

I *think* that should do it. I've not really used git on a project with more than a few members before, so this has very much been a learning experience.

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 329075` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>manuskript</li>
</ul>
</details>

**Review by gador — APPROVED** [review]
Changes LGTM! Thank you for your work!

**Pull request merged**
