### PR TITLE
programs/bash: install nix-bash-completions if completion is enabled

### PR DESCRIPTION
**Pull request by hedning**
###### Motivation for this change

Enable completion for the Nix command line tools when bash completion is enabled.

The completion scripts should be pretty solid now, and I think it would be good for the user experience to install it automatically when the user have toggled `programs.bash.enableCompletion`.

###### Things done

Removed spotty nixops completion, which wasn't ready for prime time, from nix-bash-completions.

Added a note to the 18.03 changelog.

Tested VMs with `nixos-rebuild build-vm` configured with `programs.bash.enableCompletion` turned on and off.

cc @bjornfor 

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Thank you! I love being able to complete Nix commands!

**Comment by Mic92** [comment]
Do we have those enabled on the live cd? I think we should.

**Comment by oxij** [comment]
Would be nice to do the same for zsh, I think.

**Comment by oxij** [comment]
Ah, ignore the previous comment.

`nixos/modules/programs/zsh/zsh.nix` already does it.

**Comment by hedning** [comment]
@Mic92 `programs.bash.enableCompletion` is false by default, and it doesn't look like it's turned on explicitly in any of the cd configs.

I agree that it would be good to turn it on for the cd.

**Pull request merged**
