### PR TITLE
shotcut: 21.03.21 -> 21.09.20 and clarify license

### PR DESCRIPTION
**Pull request by hrhino**
###### Motivation for this change

This works with newer `mtl++`. License is `gpl3Plus`: https://github.com/mltframework/shotcut/blob/master/src/abstractproducerwidget.cpp#L1-L17

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by woffs — APPROVED** [review]
Seems to work. Note that meanwhile a new release v21.09.13 is out

**Comment by hrhino** [comment]
Oh, thanks for the heads-up. I put it in draft because I was having trouble exporting videos &mdash; does that work for you?

**Comment by woffs** [comment]
you are right; it tries to execute melt-7 which does not exist; https://github.com/woffs/nixpkgs/commit/9a6e971b25ce45bd037a651a99fbb50b6599047f would fix that

**Comment by hrhino** [comment]
Thanks! Added you as `Co-Authored-By`.

**Comment by woffs** [comment]
Looks good to me, export is working. I'd suggest to update to 21.09.20 and then let it be merged.

**Comment by hrhino** [comment]
Updated; re-tested a handful of things (import `mp4`, import `jpg`, blur filter, playlist, crop, rearrange, save, load, export); seems to work fine.

**Review by woffs — APPROVED** [review]

**Review by bobby285271 — APPROVED** [review]
Builds, runs (x86_64 NixOS).

**Pull request merged**
