### PR TITLE
veracrypt: 1.22 -> 1.23 / truecrypt: remove and alias to veracrypt

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Update `veracrypt` to latest version 1.23
[Release notes](https://www.veracrypt.fr/en/Release%20Notes.html) : **nothing** critical security-wise

cc @dsferruzza for testing and review

\+
TrueCrypt has been retired (upstream) for a while now and the source archive we pointed to is **gone**. Moreover the VeraCrypt fork is available, maintained and fixes issues previous audits found in TrueCrypt.
Cryptsetup is also able to mount TC volumes.
This PR proposes to remove the (broken) package and keep an alias to point to the backward-compatible fork VeraCrypt.
 - [x] the change is **documented** in 19.03 release notes

------

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
I forgot to explain the removal of the wxGUI switch in `veracrypt` : in fact it was never working (build failing if set to false).

To build VeraCrypt text-only you still need wxGTK **and** you need to rebuild wxGTK without GUI too...
See https://sourceforge.net/p/veracrypt/tickets/30/
So this is totally unpractical and it won't reduce the closure size...

Moreover, the normal build provides **both** GUI and text-only interfaces so it is perfectly usable in pure CLI contexts already. The NOGUI build doesn't make much sense in the end.

**Comment by dsferruzza** [comment]
Hi @c0bw3b !
Thanks for this PR!

This makes sense for me to remove TrueCrypt: VeraCrypt is more mature/secure/tested and can mount TC volumes. Not to mention TrueCrypt has been abandoned years ago...

I have 2 questions about ce67a63dbec461ff91723b3037f015c28c701c07:
1. You remove code that allowed to build VC without GUI support (to use it via CLI); why?
2. Why did you changed the license? It seems that the `VeraCrypt License` is still the one (https://www.veracrypt.fr/code/VeraCrypt/tree/License.txt).

Also, for my culture, what is the `install` command you used in the `installPhase` script?

Have a nice day!

**Comment by c0bw3b** [comment]
Hello @dsferruzza 

All good questions so here we go:

1. I explained the reason to remove the wxGUI build switch [in my comment above](https://github.com/NixOS/nixpkgs/pull/49074#issuecomment-432799041) : basically setting `NOGUI=1` was not sufficient to build VC with text-only interface **and** the normal build exposes **both** GUI and text UI (`veracrypt --text --help` for example or short form `veracrypt -t -h`) so it usable via CLI even when built with wxGTK

2. Licensing: [official website explains](https://www.veracrypt.fr/en/VeraCrypt%20License.html) that VC is dual-licensed under `Apache License 2.0` and `TrueCrypt License version 3.0`. I added both in our package definition to translate this dual-licensing. Moreover, since the TC license is not really considered a free/FLOSS license, adding the ASL2 gives us some 'warranty' that we can indeed redistribute VeraCrypt as a free software

3. `install` is just a coreutils command that is useful for packaging because it allows to set rights, modes, owners and create directories as well as copying files. Basically does the same thing as mkdir+cp+chown but I favor one-liners commands 😸 

Nice day to you too and thanks for reviewing.

/cc @ryantm too as maintainer of truecrypt

**Review by ryantm — APPROVED** [review]
Looks good to me. You might consider allowing the `wxGUI` to be passed in, but if it is, failing with a nicer error message.

**Comment by c0bw3b** [comment]
Technically feasible but I can't see a use case where this would be useful (a boolean switch that would just make the build fail).
Keeping in mind that it was already failing up to now, so anyone trying to do it out of tree would see the build failure.

Thank you for the review and the approval nonetheless! @ryantm

**Pull request merged**
