### PR TITLE
chromium: drop inactive maintainers, CODEOWNERS: init chromium

### PR DESCRIPTION
**Pull request by emilylange**
## Description of changes

Our [`./maintainers/README.md`](https://github.com/NixOS/nixpkgs/blob/67402e9e6654882bebe2c504bbff2fa3457568ab/maintainers/README.md#how-to-lose-maintainer-status) has a section titled "How to lose maintainer
status", which describes an "inactivity measure":

Maintainers how haven't reacted to "package-related notifications" for more than 3 months can be removed.

All those 4 maintainers (@primeos, @thefloweringash, @squalus, @michaeladler) that are getting dropped as part of this commit haven't responded to any such notifications (mostly review pings) for at least 3 months.

I'll wait at least 1 week, just as [`./maintainers/README.md`](https://github.com/NixOS/nixpkgs/blob/67402e9e6654882bebe2c504bbff2fa3457568ab/maintainers/README.md#how-to-lose-maintainer-status) recommends, before merging this.

This also adds me as the only GitHub CODEOWNER, a feature that requires write/commit access, for the package itself and the VM test (but not the nixos module), because ofborg pings are still somewhat unreliable.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by networkException — APPROVED** [review]

**Review by matdibu — APPROVED** [review]

**Review by thefloweringash — APPROVED** [review]

**Comment by michaeladler** [comment]
Fine with me you guys have been doing a tremendous job so I didn't feel the need to become active :)

**Comment by emilylange** [comment]
Please don't feel like I want you all gone.

It's just that it's been quite discouraging (at least for me) to see you all getting pinged all the time and not even a single sign of life.

Simply put, I did not expect reactions from you to this PR at all. Thanks! :)

But I also get that one might have better things to do now.

@squalus for example, seems to have moved to `librewolf` (judging from their past PRs).

I would rather want to keep those as maintainers, that feel able to bump chromium from time to time (and maybe even fix stuff if issues arise), than to artificially reduce the maintainer count.

**Review by squalus — APPROVED** [review]

**Comment by michaeladler** [comment]
No offense taken! In fact I've switched to Firefox because Chromium seems to be the new Flash player these days ;)

**Comment by primeos** [comment]
Hey there, sorry for not responding for quite a while!... :o I basically had the problem that I had way too much going on this year (at least mostly due to nice things) and my time management really "crashed". My Nixpkgs work really started suffering. I couldn't keep up with update feeds and notifications anymore and I also hid a bug where Chromium would cause 100% CPU usage (but only one core, IIRC) due to too many open GitHub tabs (basically my TODO list). This had been coming for a while as I had plenty of time as a student and picked up lots of packages (including Chromium and I even had to maintain LLVM a bit for Chromium) but unfortunately I didn't manage to drop packages in time so it all happened really abrupt when I didn't return to Nixpkgs/GitHub after a vacation (as it became too draining, especially with being 10+ days behind). Anyway, I wish I could've handled the transition better but unfortunately I also fear that we don't really have good Nixpkgs processes for such developments.

I'm now planning on catching up during the holidays and returning to Nixpkgs but with way less packages.

Removing me as Chromium maintainer is completely fine as I'm quite sure that I couldn't keep up anymore. I'm really glad that we finally have some new maintainers - thank you all! I could offer to help with reviews though if that would help (no promises but I should have enough time once I remove myself from the other packages I don't really use/maintain anymore).

> you all have been doing a tremendous job

+1 from me! :)

> It's just that it's been quite discouraging (at least for me) to see you all getting pinged all the time and not even a single sign of life.

Yeah, sorry about that...
That said, I was at least still reachable via Matrix (and hopefully also via Email) - it would've been nice if you'd reached out there as well (given that we already had a brief Matrix chat) but I get that there were probably more important things and I hope that means that I did at least not miss any major questions where I should've helped.

> Simply put, I did not expect reactions from you to this PR at all. Thanks! :)

Hehe, yeah, in my case it's due to the timing/holidays but it's often the case that "old" maintainers are basically passive maintainers where they still read the notifications but only step in if they feel that there's a need to. In the case of Chromium we also used `meta.maintainers` for testers to get notified about new PRs and for users of non-x86 architectures to also get notified about issues (e.g., in case they only apply to certain architectures). I documented this in [README.md](https://github.com/NixOS/nixpkgs/blob/ff1380cb3a936bc84d04059ca842af957f3ab513/pkgs/applications/networking/browsers/chromium/README.md#maintainers) but I see that it has become quite a bit outdated, unfortunately...

> But I also get that one might have better things to do now.

Yes, unfortunately... I still love NixOS/Nixpkgs but I had to prioritize/sacrifice due to "lack" of time (: (and Nixpkgs became quite a strain once I wasn't able to easily keep up anymore)

> In fact I've switched to Firefox because Chromium seems to be the new Flash player these days ;)

As an aside, IMO the web has become way out of hand (i.e., is broken) and all browsers suck with no real hope on the horizon. Chromium sucks because of Google and I lost hope in Firefox/Mozilla when they fired their future (Servo (and Rust) developers). Some links in case someone is interested:
- https://drewdevault.com/2020/03/18/Reckless-limitless-scope.html (impossible to implement the web correctly / securely / at all)
- https://drewdevault.com/2016/05/11/In-Memoriam-Mozilla.html (Mozilla becoming "bad" as well)
- https://drewdevault.com/2017/12/16/Firefox-is-on-a-slippery-slope.html (some past Mozilla incidents)
- https://drewdevault.com/2020/10/22/Firefox-the-embarassment-of-FOSS.html (quite some issues...)
  - https://calpaterson.com/mozilla.html (Firefox usage is down 85% despite Mozilla's top exec pay going up 400%)
- https://en.wikipedia.org/wiki/Mozilla_Corporation#Google (no current data but I feel like at this point Google is only interested to keep Firefox alive to avoid antitrust (anti-monopoly law) issues)

I wish there was hope on the horizon but I don't really see it... :(
So I guess all browsers suck and I'll keep using the ones that suck the least for my use-cases (not many web engines to choose from anyway).
At least ad blocking still works for now :) (to end on a happy note :D)

**Review by primeos — CHANGES_REQUESTED** [review]
I'm fine with the changes but it'd be nice if we could update/sync https://github.com/NixOS/nixpkgs/blob/ff1380cb3a936bc84d04059ca842af957f3ab513/pkgs/applications/networking/browsers/chromium/README.md#maintainers as well while we're at it.

**Review by primeos — APPROVED** [review]
LGTM now, thanks again! :)

**Pull request merged**
