### PR TITLE
xen: 4.19.0-unstable-2024-11-12 → 4.19.1

### PR DESCRIPTION
**Pull request by SigmaSquadron**
Upgrades Xen to 4.19.1.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 362847"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SigmaSquadron** [comment]
oh no

```console
RPATH of binary /nix/store/dipycyfl8jp8vq8sz6n1adxmh6wajdbg-xen-4.19.1/lib/ocaml/5.2.1/site-lib/xeneventchn/dllxeneventchn_stubs.so contains a forbidden reference to /build/
```

**Comment by SigmaSquadron** [comment]
It is possible that the issue lies in [`2d02d54cce38a7a556c38ccd1523bbd6ca749b33`](https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=2d02d54cce38a7a556c38ccd1523bbd6ca749b33).

**Comment by SigmaSquadron** [comment]
welcome back `vagrant` to the land of <del>the living</del> working packages!

---

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362847`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>qubes-core-vchan-xen</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 65 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>docker-machine-kvm2</li>
    <li>fdroidserver</li>
    <li>fdroidserver.dist</li>
    <li>garble</li>
    <li>gnome-boxes</li>
    <li>guestfs-tools</li>
    <li>htcondor</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libguestfs-with-appliance.guestfsd</li>
    <li>libguestfs.guestfsd</li>
    <li>librenms</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt-glib.dev</li>
    <li>libvirt-glib.devdoc</li>
    <li>libvmi</li>
    <li>libvmi.dev</li>
    <li>libvmi.lib</li>
    <li>mgmt</li>
    <li>minikube</li>
    <li>multipass</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl538Packages.SysVirt</li>
    <li>perl538Packages.SysVirt.devdoc</li>
    <li>perl540Packages.SysVirt</li>
    <li>perl540Packages.SysVirt.devdoc</li>
    <li>prometheus-libvirt-exporter</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.libvirt</li>
    <li>python311Packages.libvirt.dist</li>
    <li>python311Packages.xen</li>
    <li>python311Packages.xen.boot</li>
    <li>python311Packages.xen.dev</li>
    <li>python311Packages.xen.doc</li>
    <li>python311Packages.xen.man</li>
    <li>python312Packages.guestfs</li>
    <li>python312Packages.guestfs.dist</li>
    <li>python312Packages.libvirt</li>
    <li>python312Packages.libvirt.dist</li>
    <li>xen (python312Packages.xen)</li>
    <li>xen.boot (python312Packages.xen.boot)</li>
    <li>xen.dev (python312Packages.xen.dev)</li>
    <li>xen.doc (python312Packages.xen.doc)</li>
    <li>xen.man (python312Packages.xen.man)</li>
    <li>qemu_xen</li>
    <li>qemu_xen.debug</li>
    <li>qemu_xen.ga</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
    <li>rubyPackages_3_2.ruby-libvirt</li>
    <li>rubyPackages_3_4.ruby-libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-v2v</li>
    <li>virt-viewer</li>
    <li>xen-guest-agent</li>
  </ul>
</details>

**Review by philiptaron — APPROVED** [review]

**Comment by SigmaSquadron** [comment]
`xtf` tests will fail since our `qemu-dm`... doesn't exist, but my usual battery of PV(H) VMs work.

**Comment by SigmaSquadron** [comment]
The patch included in this PR will be upstreamed into Xen soon.
I don't think it warrants a 4.19.2, so we'll just fetchpatch it when it's up.

**Review by hehongbo — APPROVED** [review]

**Comment by philiptaron** [comment]
@SigmaSquadron is this ready to merge?

**Comment by SigmaSquadron** [comment]
@philiptaron Yes.

**Pull request merged**
