### PR TITLE
mastodon: use fetchFromGitHub, fix shellcheck hints

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ooliver1** [comment]
Tested docker-compose.

---

Result of `nixpkgs-review pr 238836` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mastodon</li>
  </ul>
</details>

**Review by ooliver1 — APPROVED** [review]

**Comment by meatballhat** [comment]
@SuperSandro2000 If you happen to see this ❤️ Switching to assuming a source repo on github means that we can't use the update script with our [fork of glitch-soc on gitlab](https://gitlab.com/tootcat/glitch) What do you think about moving back to using `--url` (or supporting both 😬)? A very understandable answer would be "don't use this update script" 🙇🏼

**Comment by SuperSandro2000** [comment]
I am not sure if we should support this usecase as it would make the update script a bit more complex and with every change we would need to think about how it would impact you. How about you just copy the script and adopt it to your needs? Then we can't break it unexpectedly. 😬

**Comment by meatballhat** [comment]
@SuperSandro2000 yep! I'll do that. Thank you ❤️

**Comment by benaryorg** [comment]
Somehow I feel like the complexity this adds to anyone wanting to use a fork that is not hosted on a central platform is not worth it. This breaks deployment for a large variety of forks, and the fediverse bubble is specifically known to prefer self-hosted solutions over centralized US based corporate deployments. The complexity argument is negligible too IMHO since a git repository is always a git repository no matter where it's hosted while GitHub is a specific vendor tie-in. Any other custom fetch script (GitLab, SourceHut, etc.) all support using the plain *fetchgit* too.

**Comment by SuperSandro2000** [comment]
Yeah, but using fetchgit is slower and more prune to reproducible issues. Using GitHubs zip download does not have those problems.

You can always work with normal overlays which offer you way more freedom to adjust Mastodon however you like. I am doing that myself, too, and adding a custom skin on top for which I added runHook to all phases to make that simpler. See https://github.com/SuperSandro2000/nixos-modules/blob/master/modules/mastodon.nix#L21

Mastodon shouldn't really be more special than other packages that are often customized.

**Pull request merged**
