### PR TITLE
Add Prometheus 2 service in parallel with 1.x version (continuation)

### PR DESCRIPTION
**Pull request by jbgi**
###### Motivation for this change
Continuation of the work done by @azazel75 in #49802, addressing remaining review points.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by basvandijk** [comment]
@jbgi I just pushed a commit which registers the `prometheus2` test. So now we should be able to instruct:

@GrahamcOfBorg test prometheus prometheus2

**Comment by basvandijk** [comment]
I added the changes around Prometheus to the 19.09 release notes. I think this is ready to be merged now. If nobody objects I'll merge after the checks are green.

**Comment by basvandijk** [comment]
@jbgi @fpletz I was thinking of adding https://github.com/NixOS/nixpkgs/commit/d4dcde92c02fdb742207c14e10b213ba9f642851 to this PR to add a bit more backwards compatibility by keeping the `services.prometheus.dataDir` directory. This might allow this PR to be backported to 19.03. What do you think? If you agree with the commit, I'll add it to the PR and update the 19.09 release notes accordingly.

**Comment by jbgi** [comment]
@basvandijk thanks! backporting this PR would be great indeed. Just a minor nitpick about `isNull` being deprecated.

**Comment by basvandijk** [comment]
Thanks for the heads-up regarding the deprecation of `isNull`. What should I use instead?

**Comment by jbgi** [comment]
@basvandijk just `== null` or `!= null`.

**Comment by basvandijk** [comment]
Thanks. I just pushed these commits to this PR. Will merge after the checks are green.

@GrahamcOfBorg test prometheus prometheus2

**Pull request merged**
