### PR TITLE
vscode-extensions.nvarner.typst-lsp: fix hash

### PR DESCRIPTION
**Pull request by drupol**
Issue introduced in #273141

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@GrahamcOfBorg build vscode-extensions.nvarner.typst-lsp

**Review by GaetanLepage — APPROVED** [review]
Thanks for the fix !

**Comment by drupol** [comment]
Looks like there's another issue while building `typst-lsp` !

**Comment by GaetanLepage** [comment]
> Looks like there's another issue while building `typst-lsp` !

Indeed... Is it because of the recent GCC update ? (I heard there has been one).

**Comment by GaetanLepage** [comment]
```
b5ff56aec743b9c83609fc0e26a6c439ee27f0df is the first bad commit
commit b5ff56aec743b9c83609fc0e26a6c439ee27f0df
Merge: 7c846b760dc0 84536849e642
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Sun Dec 10 00:02:18 2023 +0000

    Merge master into staging-next

 pkgs/applications/audio/ladspa-sdk/default.nix     |    2 +
 pkgs/applications/audio/vgmstream/default.nix      |    4 +-
 pkgs/applications/blockchains/oxen/default.nix     |   67 -
 pkgs/applications/editors/setzer/default.nix       |    4 +-
 .../editors/vscode/extensions/default.nix          |    4 +-
 pkgs/applications/graphics/openboard/default.nix   |   14 +-
 pkgs/applications/misc/girara/default.nix          |    4 +-
 pkgs/applications/misc/hugo/default.nix            |    6 +-
 pkgs/applications/misc/tippecanoe/default.nix      |    4 +-
 .../networking/cluster/kaniko/default.nix          |    4 +-
 .../networking/cluster/openshift/default.nix       |    9 +-
 .../instant-messengers/webex/default.nix           |    6 +-
 .../networking/mailreaders/neomutt/default.nix     |   13 +-
 pkgs/applications/office/homebank/default.nix      |    4 +-
 .../version-management/deepgit/default.nix         |    4 +-
 pkgs/applications/video/mpv/scripts/buildLua.nix   |   30 +-
 pkgs/applications/video/mpv/scripts/default.nix    |    2 +-
 pkgs/applications/video/mpv/scripts/uosc.nix       |   50 +-
 pkgs/by-name/br/bruno/package.nix                  |    4 +-
 pkgs/by-name/de/debianutils/package.nix            |    4 +-
 pkgs/by-name/fr/framework-system-tools/Cargo.lock  | 1312 --------------------
 pkgs/by-name/fr/framework-system-tools/package.nix |   45 -
 pkgs/by-name/fr/framework-tool/package.nix         |    4 +-
 pkgs/by-name/tr/trealla/package.nix                |    4 +-
 pkgs/by-name/ux/uxn/package.nix                    |    6 +-
 pkgs/by-name/vi/vimix-cursors/package.nix          |   55 +
 pkgs/development/interpreters/wamr/default.nix     |   12 +-
 .../development/libraries/clucene-core/default.nix |   35 -
 pkgs/development/libraries/clucene-core/gcc6.patch |  146 ---
 .../python-modules/bugwarrior/default.nix          |    2 +-
 .../python-modules/jsbeautifier/default.nix        |    4 +-
 .../python-modules/labelbox/default.nix            |    4 +-
 .../development/python-modules/logbook/default.nix |    4 +-
 .../python-modules/protonup-ng/default.nix         |    3 +-
 pkgs/development/tools/ginkgo/default.nix          |    4 +-
 .../tools/language-servers/typst-lsp/Cargo.lock    | 1107 ++++++++---------
 .../tools/language-servers/typst-lsp/default.nix   |    6 +-
 pkgs/development/tools/misc/runme/default.nix      |    6 +-
 pkgs/development/tools/misc/slint-lsp/default.nix  |    6 +-
 pkgs/development/tools/nwjs/default.nix            |  163 ++-
 pkgs/development/tools/pyenv/default.nix           |    4 +-
 pkgs/development/tools/vultr-cli/default.nix       |    6 +-
 pkgs/games/unciv/default.nix                       |    4 +-
 pkgs/os-specific/linux/kernel/common-config.nix    |   34 +-
 pkgs/os-specific/linux/nvidia-x11/default.nix      |    6 +-
 pkgs/servers/plex/raw.nix                          |    6 +-
 pkgs/servers/snac2/default.nix                     |    4 +-
 pkgs/tools/misc/wakapi/default.nix                 |    6 +-
 pkgs/tools/security/libmodsecurity/default.nix     |    4 +-
 pkgs/tools/security/vals/default.nix               |    6 +-
 pkgs/tools/system/zenith/Cargo.lock                | 1057 ++++++++--------
 pkgs/tools/system/zenith/default.nix               |    8 +-
 pkgs/top-level/aliases.nix                         |    3 +
 pkgs/top-level/all-packages.nix                    |   10 +-
 54 files changed, 1403 insertions(+), 2922 deletions(-)
 delete mode 100644 pkgs/applications/blockchains/oxen/default.nix
 delete mode 100644 pkgs/by-name/fr/framework-system-tools/Cargo.lock
 delete mode 100644 pkgs/by-name/fr/framework-system-tools/package.nix
 create mode 100644 pkgs/by-name/vi/vimix-cursors/package.nix
 delete mode 100644 pkgs/development/libraries/clucene-core/default.nix
 delete mode 100644 pkgs/development/libraries/clucene-core/gcc6.patch
```

**Comment by kothavade** [comment]
Getting an error as well:
```
Error: failed to get `anyhow` as a dependency of package `typst-lsp v0.12.0 (/private/tmp/nix-b>

Caused by:
  failed to load source for dependency `anyhow`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to update replaced source registry `crates-io`

Caused by:
  failed to parse manifest at `/private/tmp/nix-build-typst-lsp-0.12.0.drv-0/cargo-vendor-dir/t>

Caused by:
  error inheriting `lints` from workspace root manifest's `workspace.lints`

Caused by:
  failed to find a workspace root
```

**Comment by GaetanLepage** [comment]
> Getting an error as well:

Fixed by #274631 which has been merged and should [make its way to the unstable channels soon](https://nixpk.gs/pr-tracker.html?pr=274631).

**Pull request merged**
