### PR TITLE
mpv: better script integration (script dependencies)

### PR DESCRIPTION
**Pull request by Profpatsch**
Followup to #14040.

Scripts for mpv are lua files that modify its behaviour.
Some of them require that mpv is built with certain features enabled,
e.g. the convert script in this commit requires encoding support.

Tested by checking whether the convert script outputs the right options for mpv.

There are still three TODOs for this WIP:
- [x] <s>patch out the `scripts` option in the mpv derivation (but: `wrapProgram` is not stack-able, what to do?)</s>
- [x] remove `mpvWithScripts` in favor of the `scripts` argument
- [x] file an upstream bug that scripts are silently ignored in some cases (_c.f._ #14040)
  - done, https://github.com/mpv-player/mpv/issues/3211
- [x] make sure ffmpeg is compiled with the correct options (_c.f._ #15930)
  - will be fixed with #15930

### CODE REVIEW

**Comment by edolstra** [comment]
I'm not really in favour of such wrappers because they have no discoverability, and no way to use them from `nix-env`. Might be better to keep them out of Nixpkgs until we have some mechanism for supporting plugins in a general way. (There is a vague item about this in Nix UI improvements plan @ https://gist.github.com/edolstra/efcadfd240c2d8906348.)

**Comment by groxxda** [comment]
Can we use waf from nixpkgs?
Out of scope of this PR, but can we enable hardware decoding (vaapi) by default?

**Comment by Profpatsch** [comment]
@edolstra We are working on creating a version that doesn’t need the function and uses the script attribute to set mpv up correctly.

**Comment by Profpatsch** [comment]
Okay, from my side this is ready for merging!

**Comment by Profpatsch** [comment]
cc @fpletz @Fuuzetsu @aszlig Merge pwease? :)

**Comment by Mic92** [comment]
@Profpatsch if you rebase it against master, I will merge it.

**Comment by Profpatsch** [comment]
I noticed this might need a bit more thought.

**Pull request closed without merging**
