### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

---

This is the follow-up to #207604. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 208126` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>getoptions</li>
    <li>openvino</li>
    <li>python310Packages.openvino</li>
    <li>python39Packages.openvino</li>
  </ul>
</details>
<details>
  <summary>52 packages failed to build:</summary>
  <ul>
    <li>actionlint</li>
    <li>haskellPackages.ascii-caseless</li>
    <li>haskellPackages.ghcide</li>
    <li>haskellPackages.ghcide-bench</li>
    <li>haskellPackages.ghcide-test-utils</li>
    <li>haskellPackages.hls-alternate-number-format-plugin</li>
    <li>haskellPackages.hls-cabal-fmt-plugin</li>
    <li>haskellPackages.hls-cabal-plugin</li>
    <li>haskellPackages.hls-call-hierarchy-plugin</li>
    <li>haskellPackages.hls-change-type-signature-plugin</li>
    <li>haskellPackages.hls-class-plugin</li>
    <li>haskellPackages.hls-code-range-plugin</li>
    <li>haskellPackages.hls-eval-plugin</li>
    <li>haskellPackages.hls-explicit-fixity-plugin</li>
    <li>haskellPackages.hls-explicit-imports-plugin</li>
    <li>haskellPackages.hls-explicit-record-fields-plugin</li>
    <li>haskellPackages.hls-floskell-plugin</li>
    <li>haskellPackages.hls-gadt-plugin</li>
    <li>haskellPackages.hls-hlint-plugin</li>
    <li>haskellPackages.hls-module-name-plugin</li>
    <li>haskellPackages.hls-ormolu-plugin</li>
    <li>haskellPackages.hls-pragmas-plugin</li>
    <li>haskellPackages.hls-qualify-imported-names-plugin</li>
    <li>haskellPackages.hls-refactor-plugin</li>
    <li>haskellPackages.hls-refine-imports-plugin</li>
    <li>haskellPackages.hls-rename-plugin</li>
    <li>haskellPackages.hls-retrie-plugin</li>
    <li>haskellPackages.hls-stylish-haskell-plugin</li>
    <li>haskellPackages.hls-test-utils</li>
    <li>haskellPackages.incipit</li>
    <li>haskellPackages.jacinda</li>
    <li>haskellPackages.libgraph</li>
    <li>haskellPackages.pandoc-vimhl</li>
    <li>haskellPackages.paynow-zw</li>
    <li>haskellPackages.pinned-warnings</li>
    <li>haskellPackages.polysemy-chronos</li>
    <li>haskellPackages.polysemy-conc</li>
    <li>haskellPackages.polysemy-log</li>
    <li>haskellPackages.polysemy-log-di</li>
    <li>haskellPackages.polysemy-process</li>
    <li>haskellPackages.polysemy-resume</li>
    <li>haskellPackages.polysemy-test</li>
    <li>haskellPackages.polysemy-time</li>
    <li>haskellPackages.shake-futhark</li>
    <li>haskellPackages.sparse-linear-algebra</li>
    <li>haskellPackages.type-operators</li>
    <li>haskellPackages.union-find</li>
    <li>hledger-check-fancyassertions</li>
    <li>jacinda</li>
    <li>nix-info-tested</li>
    <li>passExtensions.pass-checkup</li>
    <li>shellcheck</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>carp</li>
    <li>futhark</li>
    <li>git-brunch (haskellPackages.git-brunch)</li>
    <li>hadolint</li>
    <li>haskell.compiler.ghc94 (haskell.compiler.ghc944)</li>
    <li>haskell.compiler.native-bignum.ghc94 (haskell.compiler.native-bignum.ghc944)</li>
    <li>haskellPackages.ShellCheck</li>
    <li>haskellPackages.cassava-megaparsec</li>
    <li>haskellPackages.clerk</li>
    <li>haskellPackages.futhark</li>
    <li>haskellPackages.graphmod</li>
    <li>haskellPackages.hadolint</li>
    <li>haskellPackages.hie-compat</li>
    <li>haskellPackages.hiedb</li>
    <li>haskellPackages.hledger</li>
    <li>haskellPackages.hledger-interest</li>
    <li>haskellPackages.hledger-lib</li>
    <li>haskellPackages.hledger-stockquotes</li>
    <li>haskellPackages.hledger-ui</li>
    <li>haskellPackages.hledger-web</li>
    <li>haskellPackages.hls-graph</li>
    <li>haskellPackages.hls-plugin-api</li>
    <li>haskellPackages.iconv</li>
    <li>haskellPackages.incipit-base</li>
    <li>haskellPackages.incipit-core</li>
    <li>haskellPackages.monomer-hagrid</li>
    <li>hledger</li>
    <li>hledger-interest</li>
    <li>hledger-ui</li>
    <li>hledger-web</li>
    <li>ledger-autosync</li>
  </ul>
</details>

**Comment by maralorn** [comment]
@siraben 
I am uncertain if those nixpkgs-review postings have any use on haskell-updates PR. We have our own hydra job to find issues. Did you do this on purpose or didn’t you just look very closely at what PR you are targeting?

**Comment by roberth** [comment]
@maralorn looks like hls has updated

```
error: assertion '((super).haskell-language-server.version == "1.8.0.0")' failed

       at /nix/store/bsc1q73zkqzjqpq3aiksy9wqzq9qrpg7-source/pkgs/development/haskell-modules/configuration-nix.nix:699:32:
       
```

Should 52962fa0a8cc7b8d34b8870047444d9459c7ce05 be reverted or modified?

**Comment by maralorn** [comment]
@roberth I am working on it.

**Comment by siraben** [comment]
@maralorn this was mistargeted, I was running a script that ran nixpkgs-review automatically based on some criteria with the rebuild count.

**Comment by sternenseemann** [comment]
@ofborg build haskellPackages.haskell-language-server

**Pull request merged**
