### PR TITLE
Small Updates

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

grc: 1.12 -> 1.13
udiskie: 2.2.0 -> 2.3.2
stella: 6.5.1 -> 6.5.2

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114895` at 7a6be9dc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/77e243eca618287716ca36e7108f401c">grc</a></li></li>
    <li><a href="https://gist.github.com/8f513fc7308fc98e21d91074ed46acb9">stella</a></li></li>
    <li><a href="https://gist.github.com/3e6da5d2586128088562a1102b6f0c8d">udiskie</a></li></li>
  </ul>
</details>

**Comment by AndersonTorres** [comment]
How can I call this bot directly?

**Comment by SuperSandro2000** [comment]
> How can I call this bot directly?

You can't. @rmcgibbo

**Comment by rmcgibbo** [comment]
It's on my TODO list. Is that an important feature for you?

**Comment by AndersonTorres** [comment]
No, it isn't. This was mostly out of curiousity.

Do the bot automatically runs after a commit update, like the ofborg?

**Comment by SuperSandro2000** [comment]
> Do the bot automatically runs after a commit update, like the ofborg?

It only runs once if not other nixpkgs-review was run for that platform.

**Pull request merged**
