### PR TITLE
Update pkgs

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

This updates a bunch of packages where I'm the current maintainer.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Built locally with nox-review. Applied to master (b0237f767e51f4068117bf4aa0f8ffb8aef652d6 and parents). You had comment about why tests were disabled for "rtv". I added that comment into the expression as well.

**Comment by bjornfor** [comment]
How well have these been tested? Should I backport to release-17.09 right away?

**Comment by matthiasbeyer** [comment]
@bjornfor I wouldn't backport them, I guess. The updates are too small IMO.

**Comment by bjornfor** [comment]
Ok. I backported only sqlitebrowser (bec8a34469794c7251f26e174723efb99fa87999).

**Pull request closed without merging**
