### PR TITLE
efl: add version 1.20.2

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update to new versions:

- [Enlightenment DR 0.21.9 Release](https://www.enlightenment.org/news/e0.21.9_release)
- Python-EFL 1.20.0 Release
- [EFL 1.20.2 release](https://www.enlightenment.org/news/efl-1.20.2)
- [EFL 1.20.1 release](https://www.enlightenment.org/news/efl-1.20.1)

For new keep also EFL 1.19.x because EPhoto does not work with EFL 1.20.x yet.

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Check the Travis log, this seems to break `ephoto`

**Comment by romildo** [comment]
> Check the Travis log, this seems to break `ephoto`

I have asked on #e and have got the answer:

> yeah there was a wrong include in ephoto, it should work for ephoto-git

[Ephoto: Remove unneccessary header.](https://git.enlightenment.org/apps/ephoto.git/commit/?id=b76a54bd3ee93fe9d529e577251a1d5fc6b32d1a)

**Comment by romildo** [comment]
> Check the Travis log, this seems to break `ephoto`

I have asked on #e and have got the answer:

> yeah there was a wrong include in ephoto, it should work for ephoto-git

[Ephoto: Remove unnecessary header.](https://git.enlightenment.org/apps/ephoto.git/commit/?id=b76a54bd3ee93fe9d529e577251a1d5fc6b32d1a)

But apparently it does not work.

**Comment by NeQuissimus** [comment]
hmm, so we can't just include that patch in ephoto?

**Comment by romildo** [comment]
With the patch ephot compiles, but does not run.

Marking this PR as work in progress for now.

**Comment by romildo** [comment]
I think the PR is ready for committing.

I am keeping two versions of `efl`: the current one (1.19.1) for `ephoto`, and the new one (1.20.2). When a new release of `ephoto` which works with 1.20.x is available, we can drop version 1.19.1.

**Pull request merged**
