### PR TITLE
tailscale: ignore tailscale link when using networkd

### PR DESCRIPTION
**Pull request by twitchyliquid64**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by danderson — APPROVED** [review]
Fancy! Looks reasonable to me.

**Review by danderson — APPROVED** [review]
LGTM again, to appease github who thinks I still need to review this.

**Comment by bbigras** [comment]
I was using `systemd.network.networks` with tailscale to set `dns` for some work `domains`. Not anymore :cry: 

[This update broke my workflow!](https://xkcd.com/1172/) (I think).

I'm not 100% sure yet, but I think having this new `50-tailscale` prevent me from adding another network matching the same name.

It seems I need to do `"50-tailscale" = pkgs.lib.mkForce {`

**Comment by danderson** [comment]
Sorry, Tailscale really needs to be in full control of its network interface, it's not going to work right if networkd is trying to muscle in on configuration. It might have accidentally worked previously, but it's definitely not a supported config for upstream Tailscale.

As an alternative, you could create a `dummy` interface and configure DNS on that. If all you care about is DNS, search domains and nameserver configs will still apply, and won't interfere with Tailscale's operation.

**Pull request merged**
