### PR TITLE
Fix many gstreamer packages on Darwin

### PR DESCRIPTION
**Pull request by nh2**
* [ ] Based on #54398, merge that first.

###### Motivation for this change

See commit messages.

Darwin evaluation was accidentally broken in the past.

One commit fixes the evaluation, the other one fixes as many packages to build with as many features as I had time to fix.

A couple things still don't work, for example the `gst-rtsp-server` example executables print `WARNING **: ... failed to create element 'rtpbin', check your installation` when you try to connect to play the stream, but we'll have to figure that out separately.

I'm not an OSX user, I just want to make #54398 as useful as possible.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nh2** [comment]
Amended to fix build of `gst-validate` on Darwin that upstream just made based on my issue reporting in IRC: https://gitlab.freedesktop.org/gstreamer/gst-devtools/merge_requests/95/diffs

**Comment by worldofpeace** [comment]
Still needed @nh2 ?

Not sure what to think with all the conflicts.

**Comment by nh2** [comment]
I don't currently have my Darwin machine around (but will have soon).

Unless #70690 wants to incorporate my fixes before I get a chance :)

**Comment by nh2** [comment]
> I don't currently have my Darwin machine around (but will have soon).

Well looks like I was wrong, support for that Macbook Air ends at OSX 10.10 (thanks planned obsolescence for perfectly fast hardware, Apple! :-1:), and we only support >= 10.12 since https://matthewbauer.us/blog/darwin-stdenv-update.html

> Unless #70690 wants to incorporate my fixes before I get a chance :)

I think this can be closed, becase around https://github.com/NixOS/nixpkgs/pull/70690#issuecomment-553846018 I see my commit from this PR cherry-picked.

It doesn't seem to update all the files I do here, but that's probably OK.

**Pull request closed without merging**
