### PR TITLE
marwaita-manjaro: 1.6 -> 1.8

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update to version [1.8](https://github.com/darkomarko42/Marwaita-manjaro/releases/tag/1.8)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by hugolgst — APPROVED** [review]
Result of `nixpkgs-review pr 108421`
```
1 package updated:
marwaita-manjaro (1.6 → 1.8)

1 package built:
marwaita-manjaro
```

LGTM

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 108421` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>marwaita-manjaro</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 108421` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>marwaita-manjaro</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 108421` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>marwaita-manjaro</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by romildo** [comment]
> Result of `nixpkgs-review pr 108421` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 1 package marked as broken and skipped:
> 
>     * marwaita-manjaro

I do not have access to a darwin machine to test on it.
I do not see any details in https://github.com/NixOS/nixpkgs/pull/108421/checks about building on darwin.
So I do not know why it fails on darwin.

@SuperSandro2000  any clues?

Should the platform to this package be restricted to linux?

**Comment by SuperSandro2000** [comment]
> > Result of `nixpkgs-review pr 108421` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> > 1 package marked as broken and skipped:
> > ```
> > * marwaita-manjaro
> > ```
> 
> I do not have access to a darwin machine to test on it.
> I do not see any details in [#108421 (checks)](https://github.com/NixOS/nixpkgs/pull/108421/checks) about building on darwin.
> So I do not know why it fails on darwin.
> 
> @SuperSandro2000 any clues?
> 
> Should the platform to this package be restricted to linux?

It is marked as broken because ``gtk-engines-2.20.2`` is. It is fine like this.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108421` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>marwaita-manjaro</li>
</ul>
</details>

**Comment by romildo** [comment]
> > > Result of `nixpkgs-review pr 108421` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> > > 1 package marked as broken and skipped:
> > > ```
> > > * marwaita-manjaro
> > > ```
> > 
> > 
> > I do not have access to a darwin machine to test on it.
> > I do not see any details in [#108421 (checks)](https://github.com/NixOS/nixpkgs/pull/108421/checks) about building on darwin.
> > So I do not know why it fails on darwin.
> > @SuperSandro2000 any clues?
> > Should the platform to this package be restricted to linux?
> 
> It is marked as broken because `gtk-engines-2.20.2` is. It is fine like this.

Is this kind of failure easy to spot? How would one easily discover for himself that `gtk-engines-2.20.2` is the cause here?

**Pull request merged**
