### PR TITLE
selenium: 2.52.0 -> 3.6.0

### PR DESCRIPTION
**Pull request by jraygauthier**
Also brings into scope the `geckodriver` on which it depends.

###### Motivation for this change

Selenium was incompatible with latest firefox version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Related to #30186.

### CODE REVIEW

**Comment by disassembler** [comment]
Can you move both of these to `../development/python-modules` and use `callPackage`? We're trying to move away from having a bunch of package definitions in the top-level python file.

**Comment by jraygauthier** [comment]
@disassembler : done.

**Comment by jraygauthier** [comment]
As requested, moved selenium into its own file.

Also moved geckodriver into its own file and changeset and compiled it instead of taking binaries.

Added missing meta and multiple littles fixes.

**Comment by jraygauthier** [comment]
I just looked at the *unsucessful checks* reported by travis. Those are totally unrelated. Odd.

**Comment by disassembler** [comment]
a `nox-review` showed `inginious` as the only failing build, and it appears that's failing on master anyways. I'm good with this, merging!

**Comment by jraygauthier** [comment]
Thanks.

**Pull request merged**
