### PR TITLE
python3Packages.qiskit: 0.18.2 -> 0.19.1

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change
Bumps metapackage and subcomponents according to https://qiskit.org/documentation/release_notes.html

Also fixes ``python3Packages.qiskit-aqua`` breakage on master. Tried to bisect to figure out what caused the breakage but couldn't diagnose. Closest I got was maybe ``pythonPackages.ipykernel``??

Closes #87432.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 87631` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
<br>- python38Packages.qiskit-ibmq-provider
</details>
<details>
  <summary>11 packages built:</summary>
<br>- python37Packages.qasm2image
<br>- python37Packages.qiskit
<br>- python37Packages.qiskit-aer
<br>- python37Packages.qiskit-aqua
<br>- python37Packages.qiskit-ibmq-provider
<br>- python37Packages.qiskit-ignis
<br>- python37Packages.qiskit-terra
<br>- python38Packages.qiskit-aer
<br>- python38Packages.qiskit-aqua
<br>- python38Packages.qiskit-ignis
<br>- python38Packages.qiskit-terra
</details>

**Comment by drewrisinger** [comment]
Don't merge. qiskit-ibmq-provider shouldn't be broken. Will also update dependency pythonPackages.pylatexenc, just released a new version

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/87631
14 packages built:
python27Packages.pylatexenc python37Packages.pylatexenc python37Packages.qasm2image python37Packages.qiskit python37Packages.qiskit-aer python37Packages.qiskit-aqua python37Packages.qiskit-ibmq-provider python37Packages.qiskit-ignis python37Packages.qiskit-terra python38Packages.pylatexenc python38Packages.qiskit-aer python38Packages.qiskit-aqua python38Packages.qiskit-ignis python38Packages.qiskit-terra
```

**Comment by drewrisinger** [comment]
Thanks @jonringer for the quick merge.

**Comment by jonringer** [comment]
I was busy with personal stuff, you just happened to catch me at a good time! :)

**Pull request merged**
