### PR TITLE
zfsUnstable: 2.1.12 -> 2.2.0-rc2

### PR DESCRIPTION
**Pull request by numinit**
###### Description of changes

New ZFS release candidate compatible up to Linux 6.4 supporting things like block cloning and SIMD SHA-2 implementations.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Too many people depend on zfs unstable for the latest kernel, 2.2.0-rc2 is excessively dangerous IMHO, we should wait until 2.2.0 is really released.

**Comment by RaitoBezarius** [comment]
We could bump unstable to 2.1.13 instead if you want.

**Comment by numinit** [comment]
Hmmm. I see the risk. Perhaps we ought to have a zfsBleedingEdge that's gated behind a "you'd better know what you're doing" flag somewhere.

**Comment by RaitoBezarius** [comment]
Yeah, I believe it's better to leave this open until 2.2.0 is out and often NixOS contributors tested it by applying this patch locally.

**Comment by numinit** [comment]
Flagging as draft so we can revisit when 2.2 is out for real.

**Comment by GGG-KILLER** [comment]
I don't think getting an rc is risky considering that zfsUnstable used to point to the staging branch commits.

As a zfsUnstable user I'd rather have this point to 2.2.0-rc.3 so that I can securely use it with a 6.4 kernel than have it be a stable version even when it has unstable in its name.

**Comment by RaitoBezarius** [comment]
> I don't think getting an rc is risky considering that zfsUnstable used to point to the staging branch commits which don't even have a proper release.

> As a zfsUnstable user I'd rather have this point to 2.2.0-rc.3 so that I can securely use it with a 6.4 kernel than have it be a stable version even when it explicitly says unstable in its name.

That's not how `zfsUnstable` was built and used in the past.

**Comment by GGG-KILLER** [comment]
> 

I remember often seeing zfsUnstable pointing to `-staging` branches' commit in the past.

But after searching for a bit I realized `-staging` branches come after the `-release` ones, so in this case it makes sense to keep in 2.1.x, I apologize for the confusion.

**Comment by RaitoBezarius** [comment]
Superseded by #246163, we will probably merge #246300 first for now. Please reopen if you think I missed something.

**Pull request closed without merging**
