### PR TITLE
python3Packages.green: fix tests

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 138221` at d272fdaa run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>passExtensions.pass-audit</li>
    <li>python38Packages.green</li>
    <li>python39Packages.green</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/green/default.nix:40:3:
```
   |
40 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/python-modules/green/default.nix:23:5:
```
   |
23 |     ./tests.patch
   |     ^
```
</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
```
Error in green.test.test_integration.TestFinalizer.test_finalizer
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/nix/store/jrk1k88kc168qz7sabxwkz3zzmdrq23d-python3.9-green-3.3.0/lib/python3.9/site-packages/green/test/test_integration.py", line 53, in test_finalizer
    output = subprocess.run(
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/subprocess.py", line 1980, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/subprocess.py", line 1178, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/nix/store/jrk1k88kc168qz7sabxwkz3zzmdrq23d-python3.9-green-3.3.0/bin/green', '--finalizer=test_finalizer0.msg', '--maxtasksperchild=1']' timed out after 10 seconds
```

I can reproduce this failure.

**Comment by dotlambda** [comment]
> I can reproduce this failure on a machine with high core count (64).

That's certainly due to https://github.com/CleanCut/green/blob/ac9cd5ff007ee131e97f70c49c763f79f06ebf5a/green/test/test_integration.py#L28.
What should we do about it? We can skip the test entirely or ask upstream to use a fixed number instead of twice the number of CPUs.

**Comment by dotlambda** [comment]
@mweinelt Please try again. I just made the patch get rid of the timeout.

**Pull request merged**
