### PR TITLE
clojure: 1.8.0 -> 1.9.0.273, new tools!

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Instead of ad-hoc wrapper around Clojure jar, this uses new Clojure CLI, see: https://clojure.org/guides/deps_and_cli

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
ack, @yegortimoshenko I merged a different clojure PR! Would you like to rebase this against master?

**Comment by orivej** [comment]
Oh well, no one between #32527, #32700 and this PR wants to build Clojure from source.

**Comment by yegortimoshenko** [comment]
@orivej I'll do that!

**Comment by yegortimoshenko** [comment]
@orivej Done, check it out. It does not build actual Clojure from source, because it's only a dependency of `clojure-tools` (which is what is packaged here), but it does build `clojure-tools` from source.

Even if we do build Clojure from source, new tooling fetches all project dependencies from Maven, so it will be replaced with a Maven version.

To build Maven artifacts from source, we would need something much more advanced.

**Comment by yegortimoshenko** [comment]
@grahamc Rebased!

**Comment by orivej** [comment]
That's dismaying, I'll see if I can fix it.

`clj` does not work when `rlwrap` is not available in PATH and #32527 has fixed that, but I don't mind if we don't because the error message is clear (“Please install rlwrap for command editing or use "clojure" instead.”), the dependency is optional and it introduces dependencies absent from the `clojure` closure.

**Comment by jerith666** [comment]
I also ended up concluding that the existing maven support in nix wasn't quite ready for primetime, and that `mvn dependency:go-offline` was incomplete.  So I took a similar approach of first running the build outside of nix and then capturing the state of the local repo.  However in my approach that bootstrapping build is done once outside of the nix expression and produces a declarative description of what's needed.  See https://github.com/NixOS/nixpkgs/issues/19741#issuecomment-346225816 and following for details.

**Comment by yegortimoshenko** [comment]
@jerith666 I think it'd be very burdensome to maintain.

Double build isn't very important to fix as Java projects build fast. It is be possible to fix this problem replacing project files with some dummies so that plugins would trigger and package a fake jar (`package` presumably being the only phase we're interested in).

**Comment by jerith666** [comment]
I'm not sure it's any more burdensome.  In both cases, if any dependency changes, you have to re-run the build outside of nix and capture a new blob of data about the new dependencies -- in your approach, a combined checksum, in mine an exploded-out list of checksums.  But either way you just drop in the new generated thing and move on.

If you have a bunch of maven builds, though, my approach lets you share all their shared dependencies in the nix store.

**Comment by yegortimoshenko** [comment]
> I'm not sure it's any more burdensome. In both cases, if any dependency changes, you have to re-run the build outside of nix [...]

You just invalidate `fetchMaven` `sha256`, and run `nix-build`. It will try to fetch (and currently, build), then it will show the new checksum. No need to do anything outside of Nix.

> If you have a bunch of maven builds, though, my approach lets you share all their shared dependencies in the nix store.

Most dependencies end up in uberjars. Also, Nix can dedupe these jars via `nix-store --optimize` if necessary.

Replacing (reimplementing) native Maven fetcher is a bad idea: your fetcher won't handle classifiers, Maven repositories other than Central, exclusions, and probably a whole bunch of other  corner cases: https://maven.apache.org/plugins/maven-dependency-plugin/usage.html

**Comment by yegortimoshenko** [comment]
@orivej 

> clj does not work when rlwrap is not available in PATH and #32527 has fixed that, but I don't mind if we don't because the error message is clear (“Please install rlwrap for command editing or use "clojure" instead.”), the dependency is optional and it introduces dependencies absent from the clojure closure (readline and ncurses).

What if we move `clj` to a separate derivation (or output)?

**Pull request closed without merging**
