### PR TITLE
cmake: 3.21.2 -> 3.22.1

### PR DESCRIPTION
**Pull request by trofi**
https://cmake.org/cmake/help/latest/release/3.22.html

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
changelog LGTM but not very confident by myself right now

**Review by jonringer — CHANGES_REQUESTED** [review]
looks like a patch needs to be updated for darwin

cc @NixOS/darwin-maintainers

**Comment by r-burns** [comment]
Can we also use this rebuild as an opportunity to apply that patch unconditionally?

**Comment by winterqt** [comment]
> looks like a patch needs to be updated for darwin

I'm trying to build `cmake` from this PR to resolve this (on `aarch64-darwin`), but I'm getting an error while building `automake`:

```
/nix/store/814ql2bfkwdfb73rmd9fi3d9vfdjhcap-bootstrap-tools/bin/bash ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..  -I. -I. -I.. -I.. -Iglib -DIN_LIBTEXTSTYLE -DLIBXML_STATIC    -I./libcroco  -DDEPENDS_ON_LIBICONV=1   -g -O2 -c -o printf-frexpl.lo printf-frexpl.c
help2man: can't get `--help' info from aclocal-1.16
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:3741: doc/aclocal-1.16.1] Error 127
error: builder for '/nix/store/362537cgjg3gz74g4d3wvx533c0vc48n-automake-1.16.5.drv' failed with exit code 2;
```

**Comment by r-burns** [comment]
Can you try cherry-picking this bump back to master (prior to https://github.com/NixOS/nixpkgs/commit/cb292462cfad8f2c8abfec898d590f542ead8309)?

**Comment by winterqt** [comment]
@r-burns Just to confirm, cb3f4892e93588e951b3ac27be1a01f71e5579b0 would be a valid commit to cherry pick this to, right?

**Comment by r-burns** [comment]
I'd expect better luck using something on master with a known-working darwin stdenv; builds based on staging commits can be confounded by existing failures

**Comment by winterqt** [comment]
Hm. what would be the best way to find that? Right now my first thought is to just find a commit before the automake bump and try it.

It's naive but I can't think of anything better off the top of my head. Maybe looking at the commit Hydra builds successfully before the time that it was committed is ideal? Not sure.

**Comment by r-burns** [comment]
You could try rebasing onto `git merge-base master cb292462cfad8f2c8abfec898d590f542ead8309`. But TBH it doesn't really need to be prior to cb292462cfad8f2c8abfec898d590f542ead8309, just not include it, so current master is probably fine.

**Comment by jonringer** [comment]
> Can we also use this rebuild as an opportunity to apply that patch unconditionally?

the PR is already targeting staging, so anything is on the table :)

**Comment by winterqt** [comment]
Patch updated, waiting on build to make sure I didn't screw anything up.

How exactly should I commit the updated patch, though? i.e. do I use the output of `git diff`, or `git format-patch` (as the original author did)? Only issue with the latter is that I guess I'd change the author info to the original author? Not sure.

**Comment by trofi** [comment]
> How exactly should I commit the updated patch? i.e. do I use the output of git diff, or git format-patch (as the original author did)? Only issue with the latter is that I guess I'd change the author info to the original author? Not sure.

Do you have permissions to push to this branch? (Don't know how one would do that in GitHub).

Feel free to attach `git format-patch` commit against `nixpkgs` and I'll apply it with `git am` as is for this branch.

**Comment by winterqt** [comment]
I was talking about generating the updated patch file, as the original author used `git format-patch`, and I'd do the same but I'm not sure if it's okay for me to take the credit so to speak in the author field, or if I should change the author field to the original author, or what.

**Comment by r-burns** [comment]
Oh I see, I usually leave the author info in place but I don't think it's very important for a trivial patch. When I add a new patch I usually try to keep it minimal, like the other patches in this directory.

**Comment by winterqt** [comment]
Got it, thanks.

Should I use `git diff` or `git format-patch`? Using the latter would allow me to maintain the description as to why the patch is needed that the original patch file has. (I'm not sure if we have a standard as to which to use to generate patches.)

**Comment by r-burns** [comment]
No standard in place I'm aware of, either should be fine. I usually just go with git diff.

**Comment by winterqt** [comment]
@trofi Here's a patch that you can apply onto of this branch: https://gist.github.com/winterqt/5e987134a16d8f3e5bfb768128eb110b.

**Comment by trofi** [comment]
> @trofi Here's a patch that you can apply onto of this branch: https://gist.github.com/winterqt/5e987134a16d8f3e5bfb768128eb110b.

Thank you! Applied as is and squashed into initial commit.

**Comment by prusnak** [comment]
> Thank you! Applied as is and squashed into initial commit.

The patch is not referenced from `pkgs/development/tools/build-managers/cmake/default.nix`

**Comment by trofi** [comment]
> The patch is not referenced from `pkgs/development/tools/build-managers/cmake/default.nix`

I think it's used in `pkgs/development/tools/build-managers/cmake/default.nix:  ++ lib.optional (stdenv.isDarwin && isBootstrap) ./remove-systemconfiguration-dep.patch`

**Comment by uri-canva** [comment]
@ofborg build cmake

**Comment by uri-canva** [comment]
The darwin builds timed out so I triggered them again, testing the change locally in the meantime.

**Comment by uri-canva** [comment]
It's timing out building llvm 11, but it's built successfully on trunk: https://hydra.nixos.org/build/160256197, can you rebase the PR?

**Comment by uri-canva** [comment]
It's timing out building llvm, but I see it is building successfully on trunk https://hydra.nixos.org/build/160256197, either the version bump causes a performance regression or maybe this is something that affects ofborg and not hydra. Darwin ofborg and hydra are slightly different, but I don't remember the specifics.

**Comment by trofi** [comment]
Rebased against current `staging`.

**Comment by uri-canva** [comment]
Builds and runs successfully on `x86_64-darwin` locally running on Monterey, still building on `aarch64-darwin`.

**Comment by uri-canva** [comment]
I'll keep building on the M1, but I suspect it will build correctly, and even if it doesn't I wouldn't want to block merging this for it.
The bigger issue the `x86_64-darwin` build of `llvm_11` timing out on ofborg, hopefully once it's merged it's going to build fine in hydra and then ofborg builds can get it from the cache.

@NixOS/darwin-maintainers does anyone know more about this?

**Comment by uri-canva** [comment]
`aarch64-darwin` builds and runs correctly on Monterey too.

**Comment by uri-canva** [comment]
I'm not sure what the process is for merging into staging though so I'll leave that to someone else.

**Comment by trofi** [comment]
Meanwhile `3.22.1` released. Rebased to and updated to that version instead.

**Pull request merged**
