### PR TITLE
nix-serve-ng: add to top-level packages

### LINKED ISSUE #190161: Package request: nix-serve-ng
**Project description**

> nix-serve-ng, a backwards-compatible Haskell rewrite of [nix-serve](https://github.com/edolstra/nix-serve) (a service for hosting a /nix/store as a binary cache). It provides better reliability and performance than nix-serve (ranging from ≈ 1.5× to 32× faster).

https://www.haskellforall.com/2022/09/nix-serve-ng-faster-more-reliable-drop.html

**Metadata**

* homepage URL: https://github.com/aristanetworks/nix-serve-ng
* source URL: https://github.com/aristanetworks/nix-serve-ng
* license: bsd3
* platforms: linux

### PR DESCRIPTION
**Pull request by ivan**
###### Description of changes

This fixes https://github.com/NixOS/nixpkgs/issues/190161

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
It doesn't build on darwin. It appears that `hsc2hs` calls the C compiler rather than the C++ one.
`-std=c++17` is required for compiling against Nix.
Perhaps `clang++` can be passed as the `--cc`: https://ghc.gitlab.haskell.org/ghc/doc/users_guide/utils.html#writing-haskell-interfaces-to-c-code-hsc2hs
cc @Gabriella439

**Comment by Gabriella439** [comment]
@roberth: I created an upstream issue here documenting what I know: https://github.com/aristanetworks/nix-serve-ng/issues/13

The short answer is that I think macOS should be disabled as a supported platform for `nix-serve-ng` until that issue is resolved.  I'm unaware of a workaround, but I believe the issue is with `hsc2hs` itself and not the choice of C compiler (although I might be not understanding what you're suggesting)

**Comment by roberth** [comment]
@Gabriella439

> I believe the issue is with `hsc2hs` itself

It doesn't look that way to me. The log suggests that `hsc2hs` invoked `clang` instead of `clang++` and the error looks like it comes from the `clang` subprocess; note the extra `error: ` prefix.

This is why I think the problem might be worked around by passing `--cc clang++`, to make `hsc2hs` call a compiler command that does accept the C++ options.
This tricked worked for Cabal when its C++ support was incomplete, so it may work for hsc2hs as well.

**Comment by Gabriella439** [comment]
@roberth: How do you override the C compiler that Cabal or GHC uses?  I couldn't find a relevant Cabal configuration setting nor a GHC option for doing this.  The closest thing I could find was this open ticket: https://github.com/haskell/cabal/issues/1325

**Comment by roberth** [comment]
@Gabriella439 I think the problem is that `hsc2hs` calls the wrong compiler command, which is why I thought `hsc2hs --cc clang++` might help.

If it really is ghc calling the C compiler, then you could hack around it [like here](https://github.com/hercules-ci/hercules-ci-agent/blob/hercules-ci-agent-0.9.8/hercules-ci-cnix-store/hercules-ci-cnix-store.cabal#L50-L51), but I haven't needed that solution since GHC 8.10. (but I don't use hsc2hs either)

**Comment by Gabriella439** [comment]
That worked!  I have the fix up here: https://github.com/aristanetworks/nix-serve-ng/pull/14

Thanks!

**Comment by Gabriella439** [comment]
So the bad news is that we can't upload `nix-serve-ng` to Hackage, yet, because Darwin builds require Cabal format version 3.6 (for `hsc2hs-options`) and Hackage doesn't accept Cabal format versions newer than 3.0.  So until Hackage supports that you'd have to depend on `nix-serve-ng` from the GitHub repository if you want to support Darwin

**Review by roberth — APPROVED** [review]

**Comment by roberth** [comment]
Merged because the actual change was independent of the problem with darwin.

It seems that for darwin we'll need some sort of override?

**Pull request merged**
