### PR TITLE
sudo: support insults (but don't enable by default)

### PR DESCRIPTION
**Pull request by nckx**
I'm sorry. I've tried.

I've tried for the past half-year to get used to a system that doesn't scold me when I fat-finger my own password. That lets me simply try again - without strongly suggesting I should probably sober up first. Even _apologising_ for my balderdash with a meek:

```
Sorry, try again.
```

I have failed.

This allows insults to be enabled in `sudoers` if desired.

### CODE REVIEW

**Comment by copumpkin** [comment]
Thanks!11!1!! This is a key feature that has prevented me and many others from using NixOS for the past several years. I am so glad that I can finally use the operating system I've been wanting to try for so long!

**Comment by nckx** [comment]
Thanks :+1: It was several weeks of hard work, but all worth it in the end.

**Comment by nckx** [comment]
Sadly, this adds 1.6MB to sudo which is a bit much.

This probably belongs in `stdenv` anyway.

**Comment by oxij** [comment]
Why not add this as a configurable option to the package? I would add
`insultsSupport` to the arguments there and then add some kind of option
to NixOS config to override this option in nixpkgs.

**Comment by copumpkin** [comment]
Are you not merging this?

**Comment by nckx** [comment]
@copumpkin: patience! Rome wasn't built in a day.

@oxij:

> Why not add this as a configurable option to the package? I would add
`insultsSupport` to the arguments there

You read my mind! Almost. Hold tight for `withInsults` 2.0.

> and then add some kind of option to NixOS config to override this option in nixpkgs.

Now you're just being silly.

**Comment by copumpkin** [comment]
I expect there to be a NixOS option to pipe my `sudo` insults through `cowsay` and `lolcat` by the end of this. Can there be? Pretty please?

**Comment by nckx** [comment]
...why optional?

_This was an actual feature request. From an actual user. It was flagged as "important". I can't help but feel you're not taking them seriously. >:-(_

**Comment by copumpkin** [comment]
No, my feature request is serious as well!

**Pull request closed without merging**
