### PR TITLE
Gitolite update

### LINKED ISSUE #7340: nixos-rebuild fails with "gitolite-init Fatal: fingerprinting failed for..."
I don't know much more than this:

```
Apr 12 18:37:13 lucy gitolite-init-start[28302]: FATAL: fingerprinting failed for 'keydir/<somehash>-gitolite-admin.pub'
```

and [some stackoverflow thread](http://stackoverflow.com/questions/10736767/getting-fatal-object-is-corrupted-when-pushing-to-a-remote-repo/10744027#10744027) but I don't know how to fix this.

### PR DESCRIPTION
**Pull request by Lassulus**
Update version to 3.6.3
This will also fix: https://github.com/NixOS/nixpkgs/issues/7340

### CODE REVIEW

**Comment by lethalman** [comment]
cc @thoughtpolice

**Comment by Lassulus** [comment]
any updates on this? are we still waiting for thoughtpolice?

**Comment by pSub** [comment]
Looks good to me. @lethalman do you see any problems with this PR? Otherwise I would say we should merge and revert in case of problems.

**Comment by pSub** [comment]
Ah, sorry closing. I hit the wrong button.

**Comment by thoughtpolice** [comment]
LGTM, sorry for the delay.

**Comment by matthiasbeyer** [comment]
Just to clearify: This did not solve #7340 for me, _yet_. I'm a bit stalled, though, as I cannot rebuild my system atm.

**Pull request merged**
