### PR TITLE
autoflake: depend on tomli for older pythons

### PR DESCRIPTION
**Pull request by yajo**
###### Description of changes

As you can see in https://github.com/PyCQA/autoflake/pull/138, TOML support is added using python 3.11's builtin `tomllib`. However, for older Python versions, they use `tomli`. Thus, it must be included for those versions.

@moduon MT-2798
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@yuriaisaka

### CODE REVIEW

**Comment by natsukium** [comment]
This PR causes 1000+ rebuilds, you must send the PR to staging instead of the master branch.
and `python3Packages.autoflake` is appropriate for the commit message and the PR title.

**Comment by yajo** [comment]
Thanks for the review, it's all attended.

**Comment by yajo** [comment]
Hello! This one should be ready to merge. Could you please give it another review? Thanks!

**Comment by natsukium** [comment]
@mweinelt @fabaff
Would you please check this PR?
It seems to be a fine patch.

**Comment by yajo** [comment]
Ping! This one is simple and obvious IMHO. Could it be merged please?

**Pull request merged**
