### PR TITLE
guile: 3.0.9 -> 3.0.10

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://www.gnu.org/software/guile/news/gnu-guile-3010-released.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Looks like this can target master?

**Comment by trofi** [comment]
Switched to `master`.

**Comment by wegank** [comment]
@ofborg build guile guile.passthru.tests

**Review by drupol — APPROVED** [review]

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 323532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>spring</li>
    <li>springLobby</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>gnat11</li>
    <li>gnat11.info</li>
    <li>gnat11.man</li>
    <li>python311Packages.abjad</li>
    <li>python311Packages.abjad.dist</li>
    <li>python312Packages.abjad</li>
    <li>python312Packages.abjad.dist</li>
  </ul>
</details>
<details>
  <summary>160 packages built:</summary>
  <ul>
    <li>akku</li>
    <li>alire</li>
    <li>ao (libfive ,python311Packages.libfive)</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>clevis</li>
    <li>clevis.man</li>
    <li>coreboot-toolchain.aarch64</li>
    <li>coreboot-toolchain.arm</li>
    <li>coreboot-toolchain.i386</li>
    <li>coreboot-toolchain.nds32le</li>
    <li>coreboot-toolchain.ppc64</li>
    <li>coreboot-toolchain.riscv</li>
    <li>coreboot-toolchain.x64</li>
    <li>denemo</li>
    <li>dico</li>
    <li>disarchive</li>
    <li>disorderfs</li>
    <li>eepers</li>
    <li>emacsPackages.ada-mode</li>
    <li>fetch-scm</li>
    <li>freetalk</li>
    <li>gash</li>
    <li>gash-utils</li>
    <li>ghdl (ghdl-mcode)</li>
    <li>ghdl-llvm</li>
    <li>gnat (gnat12 ,gnat12Packages.gnat ,gnatPackages.gnat)</li>
    <li>gnat-bootstrap (gnat-bootstrap12)</li>
    <li>gnat-bootstrap11</li>
    <li>gnat.info (gnat12.info ,gnat12Packages.gnat.info ,gnatPackages.gnat.info)</li>
    <li>gnat.man (gnat12.man ,gnat12Packages.gnat.man ,gnatPackages.gnat.man)</li>
    <li>gnatPackages.gnatcoll-core (gnat12Packages.gnatcoll-core)</li>
    <li>gnatPackages.gnatcoll-db2ada (gnat12Packages.gnatcoll-db2ada)</li>
    <li>gnatPackages.gnatcoll-gmp (gnat12Packages.gnatcoll-gmp)</li>
    <li>gnatPackages.gnatcoll-iconv (gnat12Packages.gnatcoll-iconv)</li>
    <li>gnatPackages.gnatcoll-lzma (gnat12Packages.gnatcoll-lzma)</li>
    <li>gnatPackages.gnatcoll-omp (gnat12Packages.gnatcoll-omp)</li>
    <li>gnatPackages.gnatcoll-postgres (gnat12Packages.gnatcoll-postgres)</li>
    <li>gnatPackages.gnatcoll-python3 (gnat12Packages.gnatcoll-python3)</li>
    <li>gnatPackages.gnatcoll-readline (gnat12Packages.gnatcoll-readline)</li>
    <li>gnatPackages.gnatcoll-sql (gnat12Packages.gnatcoll-sql)</li>
    <li>gnatPackages.gnatcoll-sqlite (gnat12Packages.gnatcoll-sqlite)</li>
    <li>gnatPackages.gnatcoll-syslog (gnat12Packages.gnatcoll-syslog)</li>
    <li>gnatPackages.gnatcoll-xref (gnat12Packages.gnatcoll-xref)</li>
    <li>gnatPackages.gnatcoll-zlib (gnat12Packages.gnatcoll-zlib)</li>
    <li>gnatPackages.gnatinspect (gnat12Packages.gnatinspect)</li>
    <li>gnatprove (gnatPackages.gnatprove)</li>
    <li>gprbuild (gnatPackages.gprbuild)</li>
    <li>gnatPackages.gprbuild-boot (gnat12Packages.gprbuild-boot)</li>
    <li>gnatPackages.xmlada (gnat12Packages.xmlada)</li>
    <li>gnat13 (gnat13Packages.gnat)</li>
    <li>gnat13.info (gnat13Packages.gnat.info)</li>
    <li>gnat13.man (gnat13Packages.gnat.man)</li>
    <li>gnat13Packages.gnatcoll-core</li>
    <li>gnat13Packages.gnatcoll-db2ada</li>
    <li>gnat13Packages.gnatcoll-gmp</li>
    <li>gnat13Packages.gnatcoll-iconv</li>
    <li>gnat13Packages.gnatcoll-lzma</li>
    <li>gnat13Packages.gnatcoll-omp</li>
    <li>gnat13Packages.gnatcoll-postgres</li>
    <li>gnat13Packages.gnatcoll-python3</li>
    <li>gnat13Packages.gnatcoll-readline</li>
    <li>gnat13Packages.gnatcoll-sql</li>
    <li>gnat13Packages.gnatcoll-sqlite</li>
    <li>gnat13Packages.gnatcoll-syslog</li>
    <li>gnat13Packages.gnatcoll-xref</li>
    <li>gnat13Packages.gnatcoll-zlib</li>
    <li>gnat13Packages.gnatinspect</li>
    <li>gnat13Packages.gnatprove</li>
    <li>gnat13Packages.gprbuild</li>
    <li>gnat13Packages.gprbuild-boot</li>
    <li>gnat13Packages.xmlada</li>
    <li>gnat14</li>
    <li>gnat14.info</li>
    <li>gnat14.man</li>
    <li>gnome.aisleriot</li>
    <li>gnu-shepherd</li>
    <li>gnucash</li>
    <li>guile (guile_3_0)</li>
    <li>guile-aspell</li>
    <li>guile-avahi</li>
    <li>guile-cairo</li>
    <li>guile-chickadee</li>
    <li>guile-commonmark</li>
    <li>guile-config</li>
    <li>guile-fibers</li>
    <li>guile-gcrypt</li>
    <li>guile-git</li>
    <li>guile-gnutls</li>
    <li>guile-goblins</li>
    <li>guile-hall</li>
    <li>guile-json</li>
    <li>guile-lib</li>
    <li>guile-lzlib</li>
    <li>guile-lzma</li>
    <li>guile-ncurses</li>
    <li>guile-opengl</li>
    <li>guile-quickcheck</li>
    <li>guile-reader</li>
    <li>guile-sdl2</li>
    <li>guile-semver</li>
    <li>guile-sjson</li>
    <li>guile-sqlite3</li>
    <li>guile-ssh</li>
    <li>guile-zlib</li>
    <li>guile-zstd</li>
    <li>guile.dev (guile_3_0.dev)</li>
    <li>guile.info (guile_3_0.info)</li>
    <li>guix</li>
    <li>gwrap</li>
    <li>haunt</li>
    <li>kakounePlugins.kakoune-rainbow</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>lepton-eda</li>
    <li>libchop</li>
    <li>libctl</li>
    <li>libmatheval</li>
    <li>lilypond</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lilypond-with-fonts</li>
    <li>lsh</li>
    <li>luksmeta</li>
    <li>mcron</li>
    <li>ocserv</li>
    <li>pinentry-rofi</li>
    <li>powerjoular</li>
    <li>python311Packages.cocotb</li>
    <li>python311Packages.cocotb.dist</li>
    <li>python311Packages.meep</li>
    <li>python311Packages.myhdl</li>
    <li>python311Packages.myhdl.dist</li>
    <li>python312Packages.cocotb</li>
    <li>python312Packages.cocotb.dist</li>
    <li>python312Packages.libfive</li>
    <li>python312Packages.meep</li>
    <li>python312Packages.myhdl</li>
    <li>python312Packages.myhdl.dist</li>
    <li>scheme-bytestructures</li>
    <li>skribilo</li>
    <li>slibGuile</li>
    <li>solfege</li>
    <li>tang</li>
    <li>tang.man</li>
    <li>trackballs</li>
    <li>weechat</li>
    <li>weechat-unwrapped</li>
    <li>weechat-unwrapped.guile</li>
    <li>weechat-unwrapped.lua</li>
    <li>weechat-unwrapped.man</li>
    <li>weechat-unwrapped.perl</li>
    <li>weechat-unwrapped.php</li>
    <li>weechat-unwrapped.python</li>
    <li>weechat-unwrapped.ruby</li>
    <li>weechat-unwrapped.tcl</li>
    <li>xbindkeys</li>
    <li>yosys-ghdl</li>
    <li>zrythm</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 323532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>spring</li>
    <li>springLobby</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>ao (libfive ,python311Packages.libfive)</li>
    <li>coreboot-toolchain.aarch64</li>
    <li>coreboot-toolchain.riscv</li>
    <li>gnat11</li>
    <li>gnat11.info</li>
    <li>gnat11.man</li>
    <li>python311Packages.abjad</li>
    <li>python311Packages.abjad.dist</li>
    <li>python312Packages.abjad</li>
    <li>python312Packages.abjad.dist</li>
  </ul>
</details>
<details>
  <summary>159 packages built:</summary>
  <ul>
    <li>akku</li>
    <li>alire</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>clevis</li>
    <li>clevis.man</li>
    <li>coreboot-toolchain.arm</li>
    <li>coreboot-toolchain.i386</li>
    <li>coreboot-toolchain.nds32le</li>
    <li>coreboot-toolchain.ppc64</li>
    <li>coreboot-toolchain.x64</li>
    <li>denemo</li>
    <li>dico</li>
    <li>disarchive</li>
    <li>disorderfs</li>
    <li>eepers</li>
    <li>emacsPackages.ada-mode</li>
    <li>fetch-scm</li>
    <li>freetalk</li>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>gash</li>
    <li>gash-utils</li>
    <li>ghdl (ghdl-mcode)</li>
    <li>ghdl-llvm</li>
    <li>gnat (gnat12 ,gnat12Packages.gnat ,gnatPackages.gnat)</li>
    <li>gnat-bootstrap (gnat-bootstrap12)</li>
    <li>gnat-bootstrap11</li>
    <li>gnat.info (gnat12.info ,gnat12Packages.gnat.info ,gnatPackages.gnat.info)</li>
    <li>gnat.man (gnat12.man ,gnat12Packages.gnat.man ,gnatPackages.gnat.man)</li>
    <li>gnatPackages.gnatcoll-core (gnat12Packages.gnatcoll-core)</li>
    <li>gnatPackages.gnatcoll-db2ada (gnat12Packages.gnatcoll-db2ada)</li>
    <li>gnatPackages.gnatcoll-gmp (gnat12Packages.gnatcoll-gmp)</li>
    <li>gnatPackages.gnatcoll-iconv (gnat12Packages.gnatcoll-iconv)</li>
    <li>gnatPackages.gnatcoll-lzma (gnat12Packages.gnatcoll-lzma)</li>
    <li>gnatPackages.gnatcoll-omp (gnat12Packages.gnatcoll-omp)</li>
    <li>gnatPackages.gnatcoll-postgres (gnat12Packages.gnatcoll-postgres)</li>
    <li>gnatPackages.gnatcoll-python3 (gnat12Packages.gnatcoll-python3)</li>
    <li>gnatPackages.gnatcoll-readline (gnat12Packages.gnatcoll-readline)</li>
    <li>gnatPackages.gnatcoll-sql (gnat12Packages.gnatcoll-sql)</li>
    <li>gnatPackages.gnatcoll-sqlite (gnat12Packages.gnatcoll-sqlite)</li>
    <li>gnatPackages.gnatcoll-syslog (gnat12Packages.gnatcoll-syslog)</li>
    <li>gnatPackages.gnatcoll-xref (gnat12Packages.gnatcoll-xref)</li>
    <li>gnatPackages.gnatcoll-zlib (gnat12Packages.gnatcoll-zlib)</li>
    <li>gnatPackages.gnatinspect (gnat12Packages.gnatinspect)</li>
    <li>gnatprove (gnatPackages.gnatprove)</li>
    <li>gprbuild (gnatPackages.gprbuild)</li>
    <li>gnatPackages.gprbuild-boot (gnat12Packages.gprbuild-boot)</li>
    <li>gnatPackages.xmlada (gnat12Packages.xmlada)</li>
    <li>gnat13 (gnat13Packages.gnat)</li>
    <li>gnat13.info (gnat13Packages.gnat.info)</li>
    <li>gnat13.man (gnat13Packages.gnat.man)</li>
    <li>gnat13Packages.gnatcoll-core</li>
    <li>gnat13Packages.gnatcoll-db2ada</li>
    <li>gnat13Packages.gnatcoll-gmp</li>
    <li>gnat13Packages.gnatcoll-iconv</li>
    <li>gnat13Packages.gnatcoll-lzma</li>
    <li>gnat13Packages.gnatcoll-omp</li>
    <li>gnat13Packages.gnatcoll-postgres</li>
    <li>gnat13Packages.gnatcoll-python3</li>
    <li>gnat13Packages.gnatcoll-readline</li>
    <li>gnat13Packages.gnatcoll-sql</li>
    <li>gnat13Packages.gnatcoll-sqlite</li>
    <li>gnat13Packages.gnatcoll-syslog</li>
    <li>gnat13Packages.gnatcoll-xref</li>
    <li>gnat13Packages.gnatcoll-zlib</li>
    <li>gnat13Packages.gnatinspect</li>
    <li>gnat13Packages.gnatprove</li>
    <li>gnat13Packages.gprbuild</li>
    <li>gnat13Packages.gprbuild-boot</li>
    <li>gnat13Packages.xmlada</li>
    <li>gnat14</li>
    <li>gnat14.info</li>
    <li>gnat14.man</li>
    <li>gnome.aisleriot</li>
    <li>gnu-shepherd</li>
    <li>gnucash</li>
    <li>guile (guile_3_0)</li>
    <li>guile-aspell</li>
    <li>guile-avahi</li>
    <li>guile-cairo</li>
    <li>guile-chickadee</li>
    <li>guile-commonmark</li>
    <li>guile-config</li>
    <li>guile-fibers</li>
    <li>guile-gcrypt</li>
    <li>guile-git</li>
    <li>guile-gnutls</li>
    <li>guile-goblins</li>
    <li>guile-hall</li>
    <li>guile-json</li>
    <li>guile-lib</li>
    <li>guile-lzlib</li>
    <li>guile-lzma</li>
    <li>guile-ncurses</li>
    <li>guile-opengl</li>
    <li>guile-quickcheck</li>
    <li>guile-reader</li>
    <li>guile-sdl2</li>
    <li>guile-semver</li>
    <li>guile-sjson</li>
    <li>guile-sqlite3</li>
    <li>guile-ssh</li>
    <li>guile-zlib</li>
    <li>guile-zstd</li>
    <li>guile.dev (guile_3_0.dev)</li>
    <li>guile.info (guile_3_0.info)</li>
    <li>guix</li>
    <li>gwrap</li>
    <li>haunt</li>
    <li>kakounePlugins.kakoune-rainbow</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>lepton-eda</li>
    <li>libchop</li>
    <li>libctl</li>
    <li>libmatheval</li>
    <li>lilypond</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lilypond-with-fonts</li>
    <li>lsh</li>
    <li>luksmeta</li>
    <li>mcron</li>
    <li>ocserv</li>
    <li>pinentry-rofi</li>
    <li>powerjoular</li>
    <li>python311Packages.cocotb</li>
    <li>python311Packages.cocotb.dist</li>
    <li>python311Packages.meep</li>
    <li>python311Packages.myhdl</li>
    <li>python311Packages.myhdl.dist</li>
    <li>python312Packages.cocotb</li>
    <li>python312Packages.cocotb.dist</li>
    <li>python312Packages.libfive</li>
    <li>python312Packages.meep</li>
    <li>python312Packages.myhdl</li>
    <li>python312Packages.myhdl.dist</li>
    <li>scheme-bytestructures</li>
    <li>skribilo</li>
    <li>slibGuile</li>
    <li>solfege</li>
    <li>tang</li>
    <li>tang.man</li>
    <li>trackballs</li>
    <li>weechat</li>
    <li>weechat-unwrapped</li>
    <li>weechat-unwrapped.guile</li>
    <li>weechat-unwrapped.lua</li>
    <li>weechat-unwrapped.man</li>
    <li>weechat-unwrapped.perl</li>
    <li>weechat-unwrapped.php</li>
    <li>weechat-unwrapped.python</li>
    <li>weechat-unwrapped.ruby</li>
    <li>weechat-unwrapped.tcl</li>
    <li>xbindkeys</li>
    <li>yosys-ghdl</li>
    <li>zrythm</li>
  </ul>
</details>

**Comment by drupol** [comment]
I guess we can merge this one?

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 323532` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>gnucash</li>
    <li>guile-chickadee</li>
    <li>pinentry-rofi</li>
    <li>zrythm</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.abjad</li>
    <li>python311Packages.abjad.dist</li>
    <li>python312Packages.abjad</li>
    <li>python312Packages.abjad.dist</li>
  </ul>
</details>
<details>
  <summary>63 packages built:</summary>
  <ul>
    <li>akku</li>
    <li>ao (libfive ,python311Packages.libfive)</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>dico</li>
    <li>disarchive</li>
    <li>fetch-scm</li>
    <li>freetalk</li>
    <li>gash</li>
    <li>gash-utils</li>
    <li>gnu-shepherd</li>
    <li>guile (guile_3_0)</li>
    <li>guile-aspell</li>
    <li>guile-avahi</li>
    <li>guile-cairo</li>
    <li>guile-commonmark</li>
    <li>guile-config</li>
    <li>guile-fibers</li>
    <li>guile-gcrypt</li>
    <li>guile-git</li>
    <li>guile-gnutls</li>
    <li>guile-goblins</li>
    <li>guile-hall</li>
    <li>guile-json</li>
    <li>guile-lib</li>
    <li>guile-lzlib</li>
    <li>guile-lzma</li>
    <li>guile-ncurses</li>
    <li>guile-opengl</li>
    <li>guile-quickcheck</li>
    <li>guile-reader</li>
    <li>guile-sdl2</li>
    <li>guile-semver</li>
    <li>guile-sjson</li>
    <li>guile-sqlite3</li>
    <li>guile-ssh</li>
    <li>guile-zlib</li>
    <li>guile-zstd</li>
    <li>guile.dev (guile_3_0.dev)</li>
    <li>guile.info (guile_3_0.info)</li>
    <li>haunt</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>libmatheval</li>
    <li>lilypond</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lilypond-with-fonts</li>
    <li>mcron</li>
    <li>python312Packages.libfive</li>
    <li>scheme-bytestructures</li>
    <li>skribilo</li>
    <li>slibGuile</li>
    <li>weechat</li>
    <li>weechat-unwrapped</li>
    <li>weechat-unwrapped.guile</li>
    <li>weechat-unwrapped.lua</li>
    <li>weechat-unwrapped.man</li>
    <li>weechat-unwrapped.perl</li>
    <li>weechat-unwrapped.python</li>
    <li>weechat-unwrapped.ruby</li>
    <li>weechat-unwrapped.tcl</li>
  </ul>
</details>

**Pull request merged**
