### PR TITLE
aws-workspaces: 4.6.0.4187 -> 2023.0.4395

### PR DESCRIPTION
**Pull request by dylanmtaylor**
## Description of changes

*THIS IS A MAJOR, BREAKING CHANGE TO THIS PACKAGE.*

This is a work in progress and it is not ready to be reviewed or merge yet. Now that Amazon is building against Ubuntu 22.04 which has modern OpenSSL support (see #210452), it makes sense to rebase against this Ubuntu version. Unfortunately, in the newer client, only WSP workspaces are supported, which is a major breaking change. It seems like all of the new workspaces use the WSP protocol though, so this will be beneficial to the largest number of users. There is no repo for the jammy packages (yet, anyways), so I renamed the file and uploaded it to archive.org so we could version it. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
I could use help on this PR.  I am having trouble with auto patchelf failing on libjbig.so.0. I added jbigkit to the build but it looks like I can't use libjbig.a in a manual patchelf command:

    patchelf --replace-needed libjbig.so.0 libjbig.so $out/bin/workspacesclient/dcv/libtiff.so.6

The error is:

error: auto-patchelf could not satisfy dependency libjbig.a wanted by /nix/store/b3qmd2g0a3d5p85kisznnyccv5l3420i-aws-workspaces-2023.0.4395/bin/workspacesclient/dcv/libtiff.so.6

I looked in the files for jbigkit and we don't have a .so file there. It doesn't work with the libjbig.a file that is present. I'm not sure how to make this software work on the new version.

**Comment by mausch** [comment]
Wow, [Ubuntu 20.04 will apparently keep using OpenSSL 1.1.1 even after OpenSSL's EOL](https://answers.launchpad.net/ubuntu/+source/openssl/+question/706785).

**Comment by dylanmtaylor** [comment]
> Wow, [Ubuntu 20.04 will apparently keep using OpenSSL 1.1.1 even after OpenSSL's EOL](https://answers.launchpad.net/ubuntu/+source/openssl/+question/706785).

Correct, that's how long term support typically works - they backport fixes rather than upgrade packages. This means 22.04 will be the only LTS release supported by Amazon workspaces with the new openssl.

**Comment by RohanHart** [comment]
> I could use help on this PR. I am having trouble with auto patchelf failing on libjbig.so.0. I added jbigkit to the build but it looks like I can't use libjbig.a in a manual patchelf command:
> 
> ```
> patchelf --replace-needed libjbig.so.0 libjbig.so $out/bin/workspacesclient/dcv/libtiff.so.6
> ```
> 
> The error is:
> 
> error: auto-patchelf could not satisfy dependency libjbig.a wanted by /nix/store/b3qmd2g0a3d5p85kisznnyccv5l3420i-aws-workspaces-2023.0.4395/bin/workspacesclient/dcv/libtiff.so.6
> 
> I looked in the files for jbigkit and we don't have a .so file there. It doesn't work with the libjbig.a file that is present. I'm not sure how to make this software work on the new version.

Debian patch the Makefile to enable building the shared object https://sources.debian.org/src/jbigkit/2.1-6.1/debian/patches/improve-upstream-Makefiles.diff

**Pull request closed without merging**
