### PR TITLE
geant4 overhaul

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Update geant4 expression to conform to usual practices used in nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
@xeji I think this is a good PR and at very least it doesn't break evaluation. Could you please merge this?

**Comment by xeji** [comment]
Changes LGTM. But I would limit to `platforms.linux` as it doesn't look like this will build for Darwin (and I cannot find any evidence it ever did). 

What's the difference between this and your previous  #40618 ?

**Comment by veprbl** [comment]
@xeji No problem, fixed. There is no difference with previous PR.

**Comment by xeji** [comment]
Just to get it back on page 1, I see :wink:

**Comment by veprbl** [comment]
4 months...

**Comment by xeji** [comment]
Let's ignore the timeout, the build succeeded the first time.

**Comment by veprbl** [comment]
@xeji Thank you so much!

**Pull request merged**
