### PR TITLE
selinux: 2.7 -> 2.9

### PR DESCRIPTION
**Pull request by lblasc**
#### Motivation for this change

Bump to latest. Part of: #66528

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

Closes: #56965

### CODE REVIEW

**Comment by veprbl** [comment]
Should this also update libsemanage, semodule-utils, checkpolicy, policycoreutils? See #56965

cc @e-user

**Comment by lblasc** [comment]
@veprbl I wasn't aware of #56965, thx. Updated packages you requested.

**Comment by e-user** [comment]
I think we can close #56965 if this gets merged.

**Comment by lblasc** [comment]
Can someone please take a look ? cc @aanderse @jtojnar @Mic92

**Comment by aanderse** [comment]
@lblasc I hope this gets merged soon. Unfortunately I'm not familiar enough to know all the implications and merge this. From a quick glance it looks fine. Thanks for your work on this.

@veprbl are you familiar enough to sign off and merge this?

**Comment by veprbl** [comment]
@aanderse No I'm not. My take on this is that we review this as a normal package update.

@GrahamcOfBorg build libsepol libselinux selinux-sandbox selinux-python semodule-utils libsemanage policycoreutils checkpolicy

**Comment by aanderse** [comment]
@veprbl sounds good. @disassembler @lheckemann @veprbl - I'll leave it up to one of you to merge at this point then.

**Pull request merged**
