### PR TITLE
waybar: 0.9.17 -> 0.9.18

### PR DESCRIPTION
**Pull request by teutat3s**
https://github.com/Alexays/Waybar/releases/tag/0.9.18

Added `cava` module.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rodrgz** [comment]
Cava is here: https://github.com/NixOS/nixpkgs/blob/bc04cd1b3db4e19358e6b10b9dce6dad37c6d818/pkgs/applications/audio/cava/default.nix

But the waybar module is using cava v0.8.4 from the https://github.com/LukashonakV/cava fork that built as a shared library.
https://github.com/Alexays/Waybar/blob/master/subprojects/cava.wrap

**Comment by teutat3s** [comment]
> Cava is here: https://github.com/NixOS/nixpkgs/blob/bc04cd1b3db4e19358e6b10b9dce6dad37c6d818/pkgs/applications/audio/cava/default.nix
> 
> But the waybar module is using cava v0.8.4 from the https://github.com/LukashonakV/cava fork that built as a shared library. https://github.com/Alexays/Waybar/blob/master/subprojects/cava.wrap

Addressed in https://github.com/NixOS/nixpkgs/commit/4492a5f972ca5d5552caa7d99141290b3d889f07

**Review by rodrgz — APPROVED** [review]
The cava module is working fine!

**Comment by rhoriguchi** [comment]
I've tried to use this with hyprland but I'm getting an error. I've also tried version `0.9.17` with the same error, version `0.9.16` works.

Error message in question:
image

**Pull request merged**
