### PR TITLE
bombsquad: fix hash mismatch

### LINKED ISSUE #360190: Build failure: bombsquad
## Steps To Reproduce

1. build bombsquad on x86_64
2. hash does not match

## Build log

<details>

<summary>Build Log</summary>

```
BombSquad_Linux_x86_64_1.7.37.tar.gz> trying https://files.ballistica.net/bombsquad/builds/BombSquad_Linux_x86_64_1.7.37.tar.gz
BombSquad_Linux_x86_64_1.7.37.tar.gz>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
BombSquad_Linux_x86_64_1.7.37.tar.gz>                                  Dload  Upload   Total   Spent    Left  Speed
BombSquad_Linux_x86_64_1.7.37.tar.gz> 100 54.8M  100 54.8M    0     0  27291      0  0:35:08  0:35:08 --:--:-- 39686
error: hash mismatch in fixed-output derivation '/nix/store/205gjcm7407jwx4v86isqykf0i9c63xw-BombSquad_Linux_x86_64_1.7.37.tar.gz.drv':
         specified: sha256-jrExsqaM6uhnKMGPkJJTsKt2Imek+YDI2soSP/kfPj0=
            got:    sha256-aujLYzFcKaW0ff7sRdyJ6SvSQowafWVbmwycQfDQUYY=
error: 1 dependencies of derivation '/nix/store/dnndlnwlkk7kiqwvvgmrk5g9gwjz6hfm-bombsquad-1.7.37.drv' failed to build
```

</details>

## Metadata

```
 nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.10, NixOS, 25.05 (Warbler), 25.05.20241128.251e822`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/6adv0yxjghqny1ip70j1piib30fkqldg-source`
```
## Notify maintainers

@SyedAhkam 
@coffeeispower 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ghost**
Fixes #360190

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Do we know what happened?

**Comment by SyedAhkam** [comment]
Damn, thanks @aucub for handling this.

Upstream recently has been acting weird: they update existing releases with new build artifacts which cause the hash mismatch

**Comment by SyedAhkam** [comment]
Even ryantm bot cannot help here because the version number remains the same

**Comment by drupol** [comment]
Can we ping the author of bombsquad here? Maybe we should ask him to avoid this very bad practice in the future?

**Comment by SyedAhkam** [comment]
sure. CC: @efroemling

**Review by sedbytes — APPROVED** [review]

**Pull request merged**
