### PR TITLE
nexus: 3.52.0-01 -> 3.62.0-01

### PR DESCRIPTION
**Pull request by s1341**
Update nexus. On the way, move from binary based derivation to a source-building derivation. This should allow for more flexibility in the future, including allowing plugins to be built.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by zaninime** [comment]
Nice! Great job in moving this to building from source. Looking at the change, how is the yarn lock v1 generated? Are you considering automating this process through an update script so that we get "free" updates for that too?

**Comment by s1341** [comment]
There is a comment decribing how to generate the yarn.lock. I don't think it's worth automating as it is literaly a single operation.

**Comment by zaninime** [comment]
I don't think it's a blocker for this PR, but the reasoning to avoid automating it is IMHO poor. Also updating a binary package is only "one operation" (clone nixpkgs, zero out the hash, update the version, run the build, copy-paste the updated hash), but when there are 80k packages to regularly update, having it automated makes sense, especially as there's a bot that does it. Nexus shouldn't be an exception.

To update the `yarn.lock`, it looks like to me that:

1. `git`, `node` and `yarn` must be at a minimum present
2. the correct version of the nexus source to be cloned in a folder
3. `cd` in that folder
4. run `yarn` / `yarn install` there
5. copy the resulting `yarn.lock` in the right dir in nixpkgs

If you have a look at other update scripts, you see they take similar steps in doing custom update processes.

Also related to the `yarn.lock`: how do we ensure the generated one is equivalent / compatible with the official v2? Is there some form of automated test that can be run?

**Comment by s1341** [comment]
Can you point me at an example update script so that I can crib?

**Comment by s1341** [comment]
@zaninime ?

**Comment by zaninime** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/sharedown/update.sh as an example.

**Comment by wegank** [comment]
Done in #312510.

**Pull request closed without merging**
