### PR TITLE
Fix parsed static desktop items by allowing "true" | "false"

### PR DESCRIPTION
**Pull request by toastal**
I was trying to update the mailreader Himalaya which uses a *.desktop
file in their Git repository `cp`’d over in the build step. This
*should* be supported however, the new code from the GitHub merge
request #161374, the desktop file fails on `Terminal=true` saying the
value must be a boolean or none. This makes sense, but the way this
configuration file is parsed, `true` is not considered a boolean. This
is interesting because the `boolOrNullToString` checks for boolean type
then immediately casts to string. My quick & dirty solution is to check
if the string is specifically `true` or `false` and if so, allow it.

Additionally `nixpkgs-fmt` was ran, because these are the `nixpkgs`.

### CODE REVIEW

**Comment by toastal** [comment]
> If you're copying the file over as a file, `makeDesktopItem` shouldn't be involved at all. If you're including it as Nix code, you can use Nix types.

@K900 I'm not a Nix expert in the slightest. Here's the problem point in that repository:

https://github.com/soywod/himalaya/blob/master/flake.nix#L44-L45
```bash
mkdir -p $out/share/applications/
cp assets/himalaya.desktop $out/share/applications/
```

By adding this additional `value == "true" || value == "false"` line, the build starts working again. I can't tell you any more specifics about the situation (whether or not the file is parsed,or at what point it is parsed) other than the derivation no longer works after the change to `make-desktopitem.nix`.

**Comment by K900** [comment]
`makeDesktopItem` shouldn't be involved here whatsoever. Can you try building it with `--show-trace` to see where it's invoked?

**Comment by toastal** [comment]
```
       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/pkgs/build-support/make-desktopitem/default.nix:93:60:

           92|   # need to be escaped. There are currently none in nixpkgs though, so this is OK.
           93|   renderLine = name: value: if value != null then "${name}=${value}" else null;
             |                                                            ^
           94|

       … while evaluating 'renderLine'

       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/pkgs/build-support/make-desktopitem/default.nix:93:22:

           92|   # need to be escaped. There are currently none in nixpkgs though, so this is OK.
           93|   renderLine = name: value: if value != null then "${name}=${value}" else null;
             |                      ^
           94|

       … from call site

       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/lib/attrsets.nix:259:16:

          258|   mapAttrsToList = f: attrs:
          259|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          260|

       … while evaluating anonymous lambda

       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/lib/attrsets.nix:259:10:

          258|   mapAttrsToList = f: attrs:
          259|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          260|

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/pkgs/build-support/make-desktopitem/default.nix:100:25:

           99|       (lib.mapAttrsToList renderLine)
          100|       (builtins.filter (v: !isNull v))
             |                         ^
          101|       (builtins.concatStringsSep "\n")

       … from call site

       … while evaluating 'reverseApply'

       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/lib/trivial.nix:62:27:

           61|   pipe = val: functions:
           62|     let reverseApply = x: f: f x;
             |                           ^
           63|     in builtins.foldl' reverseApply val functions;

       … from call site

       at /nix/store/1083282v145l24mlr4irm5vabdpzaxbk-source/lib/trivial.nix:63:8:

           62|     let reverseApply = x: f: f x;
           63|     in builtins.foldl' reverseApply val functions;
             |        ^
           64|

       … while evaluating 'pipe'
```

... and keeps going.

**Comment by K900** [comment]
The failing derivation here is `line-messenger-app.desktop`, which presumably originates in your config somewhere, as it's not in nixpkgs.

**Comment by toastal** [comment]
And if we look at the *.desktop file in question: https://github.com/soywod/himalaya/blob/master/assets/himalaya.desktop

```
Terminal=true
```

**Comment by K900** [comment]
Then you're going to want to change it to `terminal = false` (literal `false`, not the string `"false"`), and `categories = ["Chat"]` (a list instead of one string. Also, you can drop `type = "Application"` as that's the default anyway.

**Comment by toastal** [comment]
I had done the Chat already... but haven't pushed to my remote in a while. This is all resolved now. Thanks. 

I was equally confused why a copied file would have failed here....

**Comment by K900** [comment]
No problem, and sorry for the breakage.

**Pull request closed without merging**
