### PR TITLE
nixos/{opendkim,rspamd}: Fix CapabilityBoundingSet option

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

An empty list results in no CapabilityBoundingSet at all, an empty
string however will set `CapabilityBoundingSet=`, which represents a
closed set.

Related: #120617

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@GrahamcOfBorg test rspamd

**Comment by tnias** [comment]
I applied the patches and my setup seems to work just fine.

Maybe @nlewo could check if nixos-mailserver tests still work.

**Comment by nlewo** [comment]
@tnias thanks for the ping. Yep, I will run the SNM test suite with this patch applied.

**Comment by nlewo** [comment]
SNM test suites are green with this patch.

**Review by nlewo — APPROVED** [review]
I let this PR open few more days before merging it.

**Pull request merged**
