### PR TITLE
dbus: [WIP] new version and socket activation

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

**This is WIP** - as it requires significant recompilation, my poor laptop is currently adding to global warming. I will be back with an update once I actually manage to run this.

This PR supersedes  #18222.

We now socket activate dbus, which means it will be launched on demand.

There is no longer any reason to launch it manually from the various startup scripts and the services.xserver.startDbusSession has thus been deprecated.

This also removes the need for the configurable option in #18222.

This is upstream's recommended way to run dbus.

cc: @ttuegel @lethalman @edolstra 
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
New version is already in staging

**Comment by peterhoeg** [comment]
Thanks, but we still need the additional ```configure``` flags to get the unit files. If this PR has a chance to make it for 16.09, maybe we should hold off merging the new dbus version from staging to master until everything is OK here?

**Comment by peterhoeg** [comment]
I can confirm that this PR works properly with KDE in a VM. I'm currently trying with XFCE but that will be another few hours before it's ready...

**Comment by domenkozar** [comment]
Let's also test what happens if you restart the dbus while desktop manager is running

**Comment by peterhoeg** [comment]
I've just tried the following, which works perfectly fine:

```sh
systemctl --user reload dbus
```

**But**, this isn't quite as good:

```sh
systemctl --user restart dbus
```

While the dbus service restarts correctly, everything that was activated using dbus activation is no longer running (kuiserver5, kglobalaccel, kscreen_backend_launcher). The desktop otherwise runs but of course the services provided by those 3 daemons are no longer available.

I think there are 2 points here:

a) In general the user dbus service shouldn't be restarted, which is why we set ```reloadIfChanged = true```.

b) In the long run, dbus will not spawn services itself, but instead use systemd for spawning (the system level dbus instance does this). I have a few services here running like that (kwalletd5, kdeconnect) and they do survive the dbus restart.

**Comment by peterhoeg** [comment]
I've just tried with xfce and restarting dbus restarts the session.

But without socket activation (and thus not using systemd to keep track of the service), killing dbus kills the xfce session, but as it isn't being auto-spawned, I'm left with just the desktop image and nothing else.

So we're actually better off with socket activation.

**Comment by peterhoeg** [comment]
Any concerns about this? And are we too late for 16.09?

**Comment by ttuegel** [comment]
> Any concerns about this? And are we too late for 16.09?

If this is ready, I can merge it into staging. It's probably too late for 16.09 because it won't even be in master for some time, but I leave the final determination there to @domenkozar.

**Comment by domenkozar** [comment]
It depends on the outcome of https://github.com/NixOS/nixpkgs/issues/16514

If we decide to restart dbus on upgrade, I'd like to have this included since it improves the impact of restart.

**Comment by peterhoeg** [comment]
@domenkozar - that's unrelated.

This PR relates to socket activation of the **user** dbus instance, whereas #16514 has to do with restarting the **system** dbus instance.

**Comment by domenkozar** [comment]
@peterhoeg I thought user dbus instance is also restarted if dbus is upgraded/restarted. Is that not right?

**Comment by peterhoeg** [comment]
They should be unrelated. I'll do some digging.

**Comment by peterhoeg** [comment]
I've just tried in a VM. You can go wild on the system instance - it doesn't touch the user instance when restarted.

**Comment by Mic92** [comment]
what is the state of this pull request?

**Comment by peterhoeg** [comment]
Most of this has already been merged in a separate PR. I'll clean this up and either close or resubmit.

**Comment by mmahut** [comment]
@peterhoeg Any update on this pull request?

**Comment by peterhoeg** [comment]
We can close this.

**Pull request closed without merging**
