### PR TITLE
Add nginx perl modules

### PR DESCRIPTION
**Pull request by tekeri**
###### Motivation for this change
Allows Nginx to have perl modules.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @thoughtpolice @7c6f434c @fpletz @globin

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Was Perl in the runtime closure before?

**Comment by tekeri** [comment]
@7c6f434c No, it is new dependency.
Does this commit need some change?

**Comment by 7c6f434c** [comment]
Then maybe create a way (like overriding `perl` argument to `null` or something) to build without perl? Nginx sounds like something useful on closure-size-conscious VMs and also small cross-compilation targets where Perl might not be reliable yet.

**Comment by tekeri** [comment]
Right, got it.
Then should `perl` be opt-in or opt-out?

**Comment by 7c6f434c** [comment]
I would prefer opt-in unless a specific feature/set of features implemented as Perl modules and planned for packaging sound useful enough.

**Comment by tekeri** [comment]
I understand :)
Any other problem?

**Comment by 7c6f434c** [comment]
I am not sure if there is a cheap example of a perl module to add as a NixOS test for Nginx or not. (Or maybe it is a part of your larger Perl strategy and I will see it in a week…)

**Comment by tekeri** [comment]
I don't have a small perl module suitable for NixOS test since perl_module support is just needed for my private module (single file)...

FYI the following code can be used to run a perl module.
```
commonHttpConfig = ''
      ...
      perl_modules ${ nginx }/lib/perl5;
      perl_modules ${ makePerlPath [ HTTPDate ] };
      perl_modules ${ makePerlPath [ PHPSerialization ] };
      perl_modules ${ makePerlPath [ URI ] };
      perl_modules ${ ./perl_modules };
      perl_require my_private_module.pm;
      ...
'';
(...).locations."= /test".extraConfig = ''perl my_private_module::handler;'';
```

**Comment by 7c6f434c** [comment]
Maybe add `perl = null` at the toplevel then.

**Comment by tekeri** [comment]
@7c6f434c Could you check new commit?

**Comment by tekeri** [comment]
@7c6f434c Thanks!

**Pull request merged**
