### PR TITLE
nodePackages.coc-diagnostic: init at 0.9.0

### PR DESCRIPTION
**Pull request by expipiplus1**
Also add as Vim plugin

Also update node packages from generate.sh

Have Tested vim plugin, haven't tested every other node plugin

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by expipiplus1** [comment]
I followed the instructions in the nodePackges readme, but isn't it a bit odd that to add this package I end up updating all the node packages?

**Comment by jonringer** [comment]
> I followed the instructions in the nodePackges readme, but isn't it a bit odd that to add this package I end up updating all the node packages?

this is done so that the node packages can be "shared" with other packages which also use node packages

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 100822 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages marked as broken and skipped:</summary>  <ul>    <li>image_optim</li>    <li>ripcord</li>  </ul></details><details>  <summary>13 packages built:</summary>  <ul>    <li>emojione</li>    <li>epgstation</li>    <li>joplin</li>    <li>lumo</li>    <li>mirakurun</li>    <li>netlify-cli</li>    <li>redoc-cli</li>    <li>thelounge</li>    <li>twemoji-color-font</li>    <li>vimPlugins.coc-diagnostic</li>    <li>vimPlugins.coc-prettier</li>    <li>vimPlugins.coc-stylelint</li>    <li>wasm-text-gen</li>  </ul></details>

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
