### PR TITLE
 samba: 4.6.11 -> 4.7.4 

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Things done
updated samba and then made it compile again

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build samba

**Comment by ikervagyok** [comment]
@grahamc: do you have a Mac to test 'acl' on it? Did it even work before? I would test it, if I had a Mac, but I don't.

**Comment by rnhmjoj** [comment]
> Did it even work before?

No, it didn't. `acl` has been a build input of samba since the package was first added to nixpkgs.

ACL are a POSIX feature and darwin is only "mostly POSIX". However looking into the build system of `acl` darwin is at least handled so we could try to enable it ([currently](https://github.com/NixOS/nixpkgs/commit/40879a95ee017d45eb49d54ef9ca89651ea4ac39#diff-b638742180d93c1ff81afe06abd91dc0) its platforms are restricted to Linux) and see if it builds. Ideally it could be set to `platforms.unix`.

**Comment by ikervagyok** [comment]
Yeah, but I didn't find an 'it works officially' commit, so I didn't push the issue of changing it's status to 'platforms.unix'

**Pull request merged**
