### PR TITLE
emacs: add currently compiling package dirs to load-path

### PR DESCRIPTION
**Pull request by collares**
###### Motivation for this change

See item 1 in https://github.com/nix-community/emacs-overlay/issues/74#issuecomment-751131321. The "emacsHookDone=1" part is admittedly very hacky, suggestions are appreciated. (Edit: No longer hacky, see below)

###### Things done

- Built on platform(s)
   - [x] NixOS

### CODE REVIEW

**Comment by collares** [comment]
@adisbladis @alyssais @tadfisher I noticed that ofborg didn't add a reviewer for this, so I am tagging people that worked on this recently to get the ball rolling. Feel free to ignore this if you don't have time or just don't want to do it :)

If you want to test this locally, please use an updated gccemacs version since I was hitting a bug was fixed upstream today. The current version on emacs-overlay is fine.

**Comment by tadfisher** [comment]
> The "emacsHookDone=1" part is admittedly very hacky, suggestions are appreciated.

You could split `addToEmacsLoadPath`, `addToEmacsNativeLoadPath`, and `addEmacsVars` into a separate file (e.g. `emacs-funcs.sh`) and source it from both `setupHook` and `postInstall`.

```nix
{
  setupHook = ''
    source ${./emacs-funcs.sh}

    if [[ ! -v emacsHookDone ]]; then
      emacsHookDone=1

      # If this is for a wrapper derivation, emacs and the dependencies are all
      # run-time dependencies. If this is for precompiling packages into bytecode,
      # emacs is a compile-time dependency of the package.
      addEnvHooks "$hostOffset" addEmacsVars
      addEnvHooks "$targetOffset" addEmacsVars
    fi
  '';

  postInstall = ''
    # Make sure the current package's elisp files are in load-path, otherwise
    # (require 'file-b) from file-a.el in the same package will fail.
    source ${./emacs-funcs.sh}
    addEmacsVars "$out"

    # ...
  '';
}
```

So basically rename `setup-hook.sh` so maintainers don't get confused and move the hook install into `setupHook` in the derivation.

**Comment by tadfisher** [comment]
Can you also try removing the ```--eval=\"(add-to-list 'comp-eln-load-path \\\"$out/share/emacs/native-lisp/\\\")\"``` stanza from the native compile command and compare the output?

**Comment by collares** [comment]
Thanks for the great refactoring idea! Since setupHook expects a file name and not the file's contents, I had to sprinkle writeText in a few places. Let me know if this is a bad idea :) Even then, I believe the refactored approach is much cleaner.

I get a bunch of (error "Cannot find suitable directory for output in `comp...") errors when removing the --eval stanza. I believe this happens because addToEmacsNativeLoadPath tests if $nativeDir is a directory before it gets created by the native compilation process.

**Comment by tadfisher** [comment]
@adisbladis Can you take a look at this?

**Comment by collares** [comment]
There were some merge conflicts, but I've now rebased my commit. @adisbladis, sorry for pinging you again :)

**Pull request merged**
