### PR TITLE
houdini: 18.0 -> 18.5

### PR DESCRIPTION
**Pull request by kwohlfahrt**
###### Motivation for this change

Version bump.

There is a regression compared to the previous version - now, the license server (`sesinetd`) must be started manually before Houdini itself (even for non-commercial licenses). I'm not sure if this is an upstream change since the license server has been re-written in this release, or a Nix-related issue. Has anybody tested this on non-NixOS?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131349` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>houdini</li>
  </ul>
</details>

**Comment by kwohlfahrt** [comment]
@siraben could you show a bit more of the log from your build? It works for me, so I suspect you did not fetch the installer from https://sidefx.com.

Unfortunately it is not possible to do this automatically, since it requires agreeing to license conditions, so you need to download the installer manually and add it to the Nix store. Somebody did find an FTP host of the installers, but it didn't work reliably for me in #81113, so I haven't included it now. I might experiment a bit more with it in a separate PR.

**Comment by AndersonTorres** [comment]
??

**Comment by happysalada** [comment]
This PR seems to break hydra evaluation for master https://github.com/NixOS/nixpkgs/runs/3467340116

**Comment by happysalada** [comment]
I think libudev should be `udev`

**Comment by marsam** [comment]
this PR broke the evaluation https://github.com/NixOS/nixpkgs/runs/3467340116, `libudev` is not defined. 
Fixed on https://github.com/NixOS/nixpkgs/pull/136246

**Pull request merged**
