### PR TITLE
ARM changes for the Jetson TK1 (and other multiplatform boards)

### PR DESCRIPTION
**Pull request by dezgeg**
These add the platform for hardfloat-capable ARMv7 boards that can boot with the `multi_v7_defconfig` kernel configuration. This can successfully build and boot on the nVIDIA Jetson TK1, apart from the boot script generator which I'm still working on.

Even though this touches the kernel stuff this didn't cause any recompiles on x86.

cc @viric @ambrop72 @Jookia (hopefully I won't break your setups :)

### CODE REVIEW

**Comment by Jookia** [comment]
Thanks for the notification!

This breaks my boot script generator which I'm working on. I've also made a patch on my local copy that changes kernelDTB from a boolean to a string allowing me to copy specific DTBs to be booted on. This is then used to generate a uEnv.txt file which specifies the initrd, kernel, root and DTB to boot. I plan to have this system working for the majority of the ARM platforms before I try and push it upstream.

If my work is in the same area as yours I'd be happy to talk and possibly join efforts.

**Comment by dezgeg** [comment]
This is my boot script generator in its current form: https://github.com/dezgeg/nixpkgs/commit/296a8f7d09b3579fc138901ca764764be74e3ca6

It copies the kernels, initrds and DTBs (currently every available DTB) to `/boot/kernels`, generates an `/boot/extlinux/extlinux.conf` of this form, directly suitable for U-Boot:

````
TIMEOUT 50

LABEL NixOS - Default (2015-06-07 13:01 - 15.05.git.d9e5a9dM)
  LINUX ../kernels/5dc9l85nvk0d3k6q622r2jm5jcch8801-linux-4.0.1-zImage
  INITRD ../kernels/kjdwl13fcjklmfz555r0vgnfgnr6a0cs-initrd-initrd
  FDTDIR ../kernels/5dc9l85nvk0d3k6q622r2jm5jcch8801-linux-4.0.1-dtbs
  APPEND systemConfig=/nix/store/q6qig44lc8a8x13xrpngxpsvajkkakc5-nixos-15.05.git.d9e5a9dM init=/nix/store/q6qig44lc8a8x13xrpngxpsvajkkakc5-nixos-15.05.git.d9e5a9dM/init loglevel=4 console=ttyS0,115200n8

LABEL NixOS - Configuration 2 (2015-06-07 13:01 - 15.05.git.d9e5a9dM)
  LINUX ../kernels/5dc9l85nvk0d3k6q622r2jm5jcch8801-linux-4.0.1-zImage
  INITRD ../kernels/kjdwl13fcjklmfz555r0vgnfgnr6a0cs-initrd-initrd
  FDTDIR ../kernels/5dc9l85nvk0d3k6q622r2jm5jcch8801-linux-4.0.1-dtbs
  APPEND systemConfig=/nix/store/q6qig44lc8a8x13xrpngxpsvajkkakc5-nixos-15.05.git.d9e5a9dM init=/nix/store/q6qig44lc8a8x13xrpngxpsvajkkakc5-nixos-15.05.git.d9e5a9dM/init loglevel=4 console=ttyS0,115200n8

LABEL NixOS - Configuration 1 (2015-06-07 12:51 - 15.05.git.d9e5a9dM)
  LINUX ../kernels/5dc9l85nvk0d3k6q622r2jm5jcch8801-linux-4.0.1-zImage
  INITRD ../kernels/kjdwl13fcjklmfz555r0vgnfgnr6a0cs-initrd-initrd
  FDTDIR ../kernels/5dc9l85nvk0d3k6q622r2jm5jcch8801-linux-4.0.1-dtbs
  APPEND systemConfig=/nix/store/i2ffqp1d0ip326yi2khgfl6fddzpww9i-nixos-15.05.git.d9e5a9dM init=/nix/store/i2ffqp1d0ip326yi2khgfl6fddzpww9i-nixos-15.05.git.d9e5a9dM/init loglevel=4 console=ttyS0,115200n8
````

I believe the `extlinux.conf` format is what upstream U-Boot is in progress of migrating to for cross-distro booting (here's the documentation: http://git.denx.de/?p=u-boot.git;a=blob;f=doc/README.distro;hb=refs/heads/master ). At least my U-Boot for Jetson can boot that out-of-the-box, and I believe the same is for at least RPi2 and Beaglebone.

**Comment by Jookia** [comment]
Interesting! This is certainly MUCH better than what I was working on. On a bit of an offtopic note, does U-Boot allow booting scripts through this?

**Comment by viric** [comment]
Great to see this! I will try to update the u-boot in my sheevaplug and boot it with a multi_v5_defconfig. As for me, it can be merged.

**Comment by dezgeg** [comment]
@Jookia I believe the distro scripts look for both `extlinux/extlinux.conf` and `boot.scr.uimg`, where the latter is a script wrapped with `mkuimage`. Also, I think an extlinux menu entry can have  `LOCALBOOT`  tag which runs some predefined command from the U-Boot environment.

**Comment by Jookia** [comment]
I see. Thanks for explaining!

**Comment by viric** [comment]
One thing I encountered was the requirement to supply LOADADDR in "make uImage" building linux. It seems that you didn't need that. Is that the case? Do you use "make uImage"?

**Comment by dezgeg** [comment]
Nope, zImage.

**Comment by viric** [comment]
and then bootloader packs the zImage with uimage?

**Comment by viric** [comment]
Ah wait, I see that extlinux goes with zImage. Great.

**Pull request merged**
