### PR TITLE
vimPlugin : Update vim plugin lsp-zero-nvim to use the repository default branch `v3.x`

### PR DESCRIPTION
**Pull request by suvash**
…(not main)

The vim plugin lsp-zero-nvim, has a branch assigned for each release, instead of `main`, the current release branch being `v3.x`. The repository also uses this as the current default branch.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by suvash** [comment]
As mentioned by the author of this plugin [in a discussion](https://github.com/VonHeikemen/lsp-zero.nvim/issues/338) in the plugin repository itself

> Whoever packages lsp-zero for nixpkgs should update the commit hash to something in the v3.x branch.

It's tiny diff., and I'm already using the `3.x` branch based input for my own environment.

**Review by ambroisie — COMMENTED** [review]
This does not include the `generated.nix` modification.

(NOTE: Is there even a way to run the `update` for a single package? That would be very useful)

**Comment by suvash** [comment]
@GaetanLepage I see that you've been involved in merging several vim plugin related changes, so perhaps you're well suited to verify/complete this change. 🙌🏽

**Comment by GaetanLepage** [comment]
Indeed, you now need to run `GITHUB_API_TOKEN=<your_token> nix run -f . vimPluginsUpdater`.
This will make sure that all the vim plugins (and the treesitter parsers) are up to date.

As you see, you will need to [create a GitHub token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) with at least the `public_repo` access.

**Comment by teto** [comment]
GITHUB_API_TOKEN should not be necessary if you set --proc=1

> (NOTE: Is there even a way to run the update for a single package? That would be very useful)

@ambroisie this is the dream. Not implemented yet sadly and not trivial IMO.

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by suvash** [comment]
@ambroisie @GaetanLepage I've updated the PR with the generated automatic commits, produced after running `GITHUB_TOKEN=XXXX nix run -f . vimPluginsUpdater` !

**Review by ambroisie — APPROVED** [review]

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 266100` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>158 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bigfile-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.clang_complete</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.codeium-vim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.copilot-lua</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.elixir-tools-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.godbolt-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lsp-zero-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.modicator-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lilypond-suite</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-snippy</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-spider</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.arduino</li>
    <li>vimPlugins.nvim-treesitter-parsers.awk</li>
    <li>vimPlugins.nvim-treesitter-parsers.bitbake</li>
    <li>vimPlugins.nvim-treesitter-parsers.chatito</li>
    <li>vimPlugins.nvim-treesitter-parsers.dtd</li>
    <li>vimPlugins.nvim-treesitter-parsers.erlang</li>
    <li>vimPlugins.nvim-treesitter-parsers.gitattributes</li>
    <li>vimPlugins.nvim-treesitter-parsers.gleam</li>
    <li>vimPlugins.nvim-treesitter-parsers.go</li>
    <li>vimPlugins.nvim-treesitter-parsers.gpg</li>
    <li>vimPlugins.nvim-treesitter-parsers.janet_simple</li>
    <li>vimPlugins.nvim-treesitter-parsers.kotlin</li>
    <li>vimPlugins.nvim-treesitter-parsers.kusto</li>
    <li>vimPlugins.nvim-treesitter-parsers.markdown</li>
    <li>vimPlugins.nvim-treesitter-parsers.markdown_inline</li>
    <li>vimPlugins.nvim-treesitter-parsers.mlir</li>
    <li>vimPlugins.nvim-treesitter-parsers.perl</li>
    <li>vimPlugins.nvim-treesitter-parsers.poe_filter</li>
    <li>vimPlugins.nvim-treesitter-parsers.purescript</li>
    <li>vimPlugins.nvim-treesitter-parsers.ssh_config</li>
    <li>vimPlugins.nvim-treesitter-parsers.swift</li>
    <li>vimPlugins.nvim-treesitter-parsers.tlaplus</li>
    <li>vimPlugins.nvim-treesitter-parsers.udev</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.nvim-treesitter-parsers.xml</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-project-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-ui-select-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.venn-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-just</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-monokai-tasty</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-themis</li>
    <li>vimPlugins.vim_current_word</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by suvash** [comment]
> GITHUB_API_TOKEN should not be necessary if you set --proc=1, also you can pass it as an argument `--github-token=gh_XXX` (mentioning it here since it appears in the help and is less magical than an env variable)

Btw @teto , I blindly tried passing in the --proc=1 and --github-token=xxxx as args to nix run, but it didn't work, so I used the env var instead. Anywhere I can look up how that's supposed to work ?

**Comment by teto** [comment]
@suvash it would have been easier if you had just shared the command your ran, my guess is that you passed the args after the "update" command.
`nix run .#vimPluginsUpdater -- --proc=10 --github-token=$GITHUB_TOKEN update` run from a nixpkgs checkout works for me.

**Pull request merged**
