### PR TITLE
qt5: Drop qt-5.9

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Nothing is depending on the 5.9 branch of Qt anymore.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @ttuegel @bkchr @peterhoeg

### CODE REVIEW

**Comment by peterhoeg** [comment]
5.9 is the latest LTS - I think we should keep carrying it.

**Comment by bkchr** [comment]
I'm for dropping it, but if we keep it, we should update it.

**Comment by ttuegel** [comment]
> 5.9 is the latest LTS - I think we should keep carrying it.

In the past, I have advocated for keeping the latest branch and the latest LTS branch as these are what Qt upstream officially supports. There are other reasons to keep it: some people use Nix for Qt development, for instance. So I would prefer to keep it until a new LTS comes out.

**Comment by adisbladis** [comment]
I agree. I didn't think of that 5.9 was an LTS.

**Pull request closed without merging**
