### PR TITLE
alot: Use bundled theme files

### PR DESCRIPTION
**Pull request by kirelagin**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kirelagin** [comment]
Ping @geistesk, @FRidh, @jonringer.

**Comment by kirelagin** [comment]
Rebased onto master. Also, I guess, now ping @edibopp.

**Review by oxzi — APPROVED** [review]
Tested this PR successfully.

Without the `XDG_DATA_DIRS` environmental variable, `alot` now checks at the correct location within the nix store for theme files.

Sorry for this delay, btw. It would also be nice for further PRs to briefly explain the effects of the proposed changes.

**Review by milibopp — APPROVED** [review]
I guess, I should have checked for open issues, when I took over maintenance ;)

Thanks for the review @geistesk, looks good to me. But I'm not allowed to merge.

**Review by jonringer — APPROVED** [review]
diff LGTM

```
https://github.com/NixOS/nixpkgs/pull/85607
2 packages built:
alot python37Packages.alot
```

**Pull request merged**
