### PR TITLE
xorgserver: 1.17.4 -> 1.18.0

### PR DESCRIPTION
**Pull request by k0ral**
Successfully built locally.

### CODE REVIEW

**Comment by vcunat** [comment]
Well, this isn't as easy ATM, as the fglrx driver doesn't yet support the new server ABI, I think.

**Comment by heydojo** [comment]
fglrx is holding this back. We need an override for xserver 1.17 which we can use in os-specific/ati-drivers or we wait until AMD patch fglrx for xserver 1.18 or fglrx is marked as broken.

**Comment by vcunat** [comment]
I suppose there's no estimate when they start support it (upstream at least)?

**Comment by heydojo** [comment]
I guess they should in their next release. However I would not be able to confirm that.
The ABI change was announced many months ago..
I think amdgpu is supposed to stop this kind of thing in the future but it does not help people with cards only supported by catalyst.

**Comment by domenkozar** [comment]
Debian has removed fglrx: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811031

**Comment by vcunat** [comment]
See https://github.com/NixOS/nixpkgs/pull/15639

**Pull request closed without merging**
