### PR TITLE
openjdk8: 1.8.0_242 -> 1.8.0_265

### PR DESCRIPTION
**Pull request by jerith666**
Note that a `-ga` tag hasn't appeared in the aarch64 repo, so I had to use `b01`.  :-/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Is this the same as #94573 ?

**Comment by jerith666** [comment]
Yep.  cc @asbachb .

**Comment by asbachb** [comment]
It seems that you got the aarch64 hashes right. So let's usw this one instead of mine.

**Review by NeQuissimus — APPROVED** [review]

**Comment by asbachb** [comment]
I guess we should backport this to 20.03 as well.

**Comment by NeQuissimus** [comment]
@asbachb Would you be able to do that for me? :) Thx!

**Comment by asbachb** [comment]
@NeQuissimus 

8: https://github.com/NixOS/nixpkgs/pull/94868
11: https://github.com/NixOS/nixpkgs/pull/94603

**Pull request merged**
