### PR TITLE
libgpiod 2.0.1 -> 2.0.1  change hash to the correct one

### PR DESCRIPTION
**Pull request by adminy**
## Description of changes

```
error: hash mismatch in fixed-output derivation '/nix/store/ja3gla5v2svjvw14spaqdsizbrimnj9s-libgpiod-2.0.1.tar.gz.drv':
         specified: sha256-M68o6YheNXZrDYu6u7pEvyPt2tXhTkVZD3Kv/AXYXA8=
            got:    sha256-tu2lU1YWCo5zkG49SOlZ74EpZ4fXZJdbEPJX6WYGaOk=
```
Seems like the hash was computed incorrectly.

## Things done
Updated the hash to be the expected one.

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
Please format your commit message according to CONTRIBUTING.md and use the checklist in the pull request template. Thank you.

**Comment by adminy** [comment]
@expipiplus1 sorry to bother you with it again, but can we merge this one too? Thanks

**Review by NickCao — APPROVED** [review]

**Review by newAM — APPROVED** [review]
Hash is good now.  Builds on x86_64-linux and aarch64-linux.  `pkgsCross.aarch64-multiplatform.libgpiod` also builds from a `x86_64-linux` host.

**Comment by kirillrdy** [comment]
@adminy greetings !

I am just wondering about

` Tested compilation of all packages that depend on this change using nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD". Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)`

While this PR fixes hash, there are still packages broken by version bump, running `nixpkgs-review` should have indicated this.

Please don't worry, as I am not trying to do any blaming or anything like that. I am just trying to understrand what went wrong with the process. We can always fix broken builds :-) but preventing them in the first place is even better :-)

**Comment by adminy** [comment]
Sorry @kirillrdy, I'm very new to nix, I followed the hash generation steps and for some reason that gave me a different hash. I didn't run `nixpkgs-review` command. Didn't know of its existence, not sure why I was in such a rush, not knowing my way around I made lots of mistakes along the way. But I'm making progress on my nix journey, now I know lots of things I didn't know at the time.

**Pull request merged**
