### PR TITLE
chia: 1.2.10 -> 1.2.11

### PR DESCRIPTION
**Pull request by bbjubjub2494**
###### Motivation for this change
https://github.com/Chia-Network/chia-blockchain/releases/tag/1.2.11

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lourkeur** [comment]
An issue w/ clvm-rs:
```
Executing maturinBuildHook
++ env CC_x86_64-unknown-linux-gnu=/nix/store/s5hkav7whndbfz0szshpb46h4idqdq9a-gcc-wrapper-10.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/s5hkav7whndbfz0szshpb46h4>
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error: error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

The vendor sha256 was updated...

**Comment by lourkeur** [comment]
watch me break everything by bumping `watchdog` :roll_eyes:

**Comment by lourkeur** [comment]
Result of `nixpkgs-review pr 144733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>chia</li>
    <li>python38Packages.chiapos</li>
    <li>python38Packages.clvm-rs</li>
    <li>python38Packages.dnspythonchia</li>
    <li>python39Packages.chiapos</li>
    <li>python39Packages.clvm-rs</li>
    <li>python39Packages.dnspythonchia</li>
  </ul>
</details>

**Comment by lourkeur** [comment]
poke @Atemu

**Review by Atemu — CHANGES_REQUESTED** [review]
```
[nix-shell:~/.cache/nixpkgs-review/pr-144733]$ chia
Traceback (most recent call last):
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/bin/.chia-wrapped", line 6, in <module>
    from chia.cmds.chia import main
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/cmds/chia.py", line 17, in <module>
    from chia.cmds.plotters import plotters_cmd
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/cmds/plotters.py", line 2, in <module>
    from chia.plotters.plotters import call_plotters
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/plotters/plotters.py", line 5, in <module>
    from chia.plotters.bladebit import get_bladebit_install_info, plot_bladebit
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/plotters/bladebit.py", line 10, in <module>
    from chia.plotting.create_plots import resolve_plot_keys
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/plotting/create_plots.py", line 10, in <module>
    from chia.daemon.keychain_proxy import KeychainProxy, connect_to_keychain_and_validate, wrap_local_keychain
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/daemon/keychain_proxy.py", line 5, in <module>
    from chia.cmds.init_funcs import check_keys
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/cmds/init_funcs.py", line 9, in <module>
    from chia.consensus.coinbase import create_puzzlehash_for_pk
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/consensus/coinbase.py", line 6, in <module>
    from chia.wallet.puzzles.p2_delegated_puzzle_or_hidden_puzzle import puzzle_for_pk
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py", line 22, in <module>
    from chia.types.blockchain_format.program import Program
  File "/nix/store/nzcfyyj39xl0mc2vg5vc2z3vdk8wvlf9-chia-1.2.11/lib/python3.9/site-packages/chia/types/blockchain_format/program.py", line 10, in <module>
    from clvm_rs import STRICT_MODE, deserialize_and_run_program2, serialized_length, run_generator
  File "/nix/store/1ycs97r0nwa88i1zv88hs3y4nxs3m0nh-python3.8-clvm_rs-0.1.15/lib/python3.8/site-packages/clvm_rs/__init__.py", line 1, in <module>
    from .clvm_rs import *
ModuleNotFoundError: No module named 'clvm_rs.clvm_rs'
```

**Comment by Atemu** [comment]
Well, that's odd. I simply ran nixpkgs-review on the PR and that's what I got. Re-running it right now didn't change anything.

First time I've ever seen a WOMM bug in Nix!

Could you try running `nixpkgs-review pr 144733`?

**Comment by lourkeur** [comment]
Not WOMM, I reproduced it. It seems to only occur on `nixpkgs-review`, which I could not use from where I was previously. What I think could be a lead is that we both are hitting `/nix/store/1ycs97r0nwa88i1zv88hs3y4nxs3m0nh-python3.8-clvm_rs-0.1.15`: a 3.8 path in a 3.9 derivation. Investigating...

<details>
<summary>trace</summary>

```
Traceback (most recent call last):
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/bin/.chia-wrapped", line 6, in <module>
    from chia.cmds.chia import main
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/cmds/chia.py", line 17, in <module>
    from chia.cmds.plotters import plotters_cmd
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/cmds/plotters.py", line 2, in <module>
    from chia.plotters.plotters import call_plotters
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/plotters/plotters.py", line 5, in <module>
    from chia.plotters.bladebit import get_bladebit_install_info, plot_bladebit
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/plotters/bladebit.py", line 10, in <module>
    from chia.plotting.create_plots import resolve_plot_keys
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/plotting/create_plots.py", line 10, in <module>
    from chia.daemon.keychain_proxy import KeychainProxy, connect_to_keychain_and_validate, wrap_local_keychain
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/daemon/keychain_proxy.py", line 5, in <module>
    from chia.cmds.init_funcs import check_keys
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/cmds/init_funcs.py", line 9, in <module>
    from chia.consensus.coinbase import create_puzzlehash_for_pk
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/consensus/coinbase.py", line 6, in <module>
    from chia.wallet.puzzles.p2_delegated_puzzle_or_hidden_puzzle import puzzle_for_pk
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py", line 22, in <module>
    from chia.types.blockchain_format.program import Program
  File "/nix/store/qxxayh3283jphkkvfdnz6awgybv8y9kw-chia-1.2.11/lib/python3.9/site-packages/chia/types/blockchain_format/program.py", line 10, in <module>
    from clvm_rs import STRICT_MODE, deserialize_and_run_program2, serialized_length, run_generator
  File "/nix/store/1ycs97r0nwa88i1zv88hs3y4nxs3m0nh-python3.8-clvm_rs-0.1.15/lib/python3.8/site-packages/clvm_rs/__init__.py", line 1, in <module>
    from .clvm_rs import *
ModuleNotFoundError: No module named 'clvm_rs.clvm_rs'
```

**Comment by lourkeur** [comment]
The error only occurs in `nixpkgs-review` because `PYTHONPATH` injects the 3.8 modules. `env PYTHONPATH= chia` succeeds, and my production setup has been running this derivation for a week without this issue manifesting. @Atemu are you ok with handwaving this for now?

**Review by Atemu — APPROVED** [review]
Looks like that's a [known nixpkgs-review issue](https://github.com/Mic92/nixpkgs-review/issues/194).

**Pull request merged**
