### PR TITLE
openobserve: 0.9.1 -> 0.10.1

### PR DESCRIPTION
**Pull request by camelpunch**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
Thank you !

**Comment by camelpunch** [comment]
Apologies, I'm a bit new to this. Where do I go to see the ofborg failure? I'm assuming I can skip the test in `checkFlags`?

Some things I tried:

- Looking in the PR's checks - all green
- Googling for "nixpkgs ofborg", then clicking the ofborg GitHub page's [website link](https://monitoring.ofborg.org/dashboard/db/ofborg) - a dead Grafana page
- Reading about how to run the tests locally and deciding I might be in for a long wait!

**Comment by kirillrdy** [comment]
@camelpunch you can see failure here

image

https://logs.ofborg.org/?key=nixos/nixpkgs.306393&attempt_id=fc581ad6-5e47-4bf5-a2b0-a0f84cb22597

I've tried locally and test pass for me, so maybe its a flaky test.

trying again @GrahamcOfBorg build openobserve

**Comment by happysalada** [comment]
If its a flaky test and build is broken currently, lets just merge then.
This is pre 1.0 software anyways. If we learn something doesnt work well we can add a fix for it in the mext release. The next release is out anyways.
Its more valuable to just get feedback on the release i think.

**Comment by kirillrdy** [comment]
@happysalada failed in ofborg second time, i guess we can just disable that test

**Comment by camelpunch** [comment]
@happysalada I've pushed what I think is the correct test disable flag.

**Comment by risicle** [comment]
> This is pre 1.0 software anyways

It's not a safe assumption that we can treat "pre 1.0" software any different to anything else - there are hundreds of packages which are heavily depended upon that are "pre 1.0".

**Comment by happysalada** [comment]
Right, this package is relatively new though, and there is no module for it yet. 
Ill definitely take your point of trying to keep things stable for it though !

**Pull request merged**
