### PR TITLE
bazarr: 1.0.3 -> 1.1.1

### PR DESCRIPTION
**Pull request by andreisergiu98**
###### Description of changes
Closes https://github.com/NixOS/nixpkgs/pull/174364

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Unable to start it 
```
Bazarr starting...
Traceback (most recent call last):
  File "/nix/store/hgmlikh171g4za2rc13lmnq8hnp65s2l-bazarr-1.1.1/share/bazarr-1.1.1/bazarr/main.py", line 21, in <module>
    from init import *  # noqa E402
  File "/nix/store/hgmlikh171g4za2rc13lmnq8hnp65s2l-bazarr-1.1.1/share/bazarr-1.1.1/bazarr/init.py", line 26, in <module>
    restore_from_backup()
  File "/nix/store/hgmlikh171g4za2rc13lmnq8hnp65s2l-bazarr-1.1.1/share/bazarr-1.1.1/bazarr/utilities/backup.py", line 89, in restore_from_backup
    restore_config_path = os.path.join(get_restore_path(), 'config.ini')
  File "/nix/store/hgmlikh171g4za2rc13lmnq8hnp65s2l-bazarr-1.1.1/share/bazarr-1.1.1/bazarr/utilities/backup.py", line 28, in get_restore_path
    os.makedirs(restore_dir)
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/nix/store/hgmlikh171g4za2rc13lmnq8hnp65s2l-bazarr-1.1.1/share/bazarr-1.1.1/data'
Bazarr exited.
```

Also it would be good to specify sourceProvenance (or not sure how it is called) in the meta part to note that this is using binary sources

**Comment by andreisergiu98** [comment]
@onny I added the source provenance, and bumped it to 1.1.1. To start bazarr you have to specify a writable location for the config like this `bazarr  --config '/var/lib/bazarr'` otherwise, it will try to write into nix store.

**Comment by onny** [comment]
Result of `nixpkgs-review pr 187158` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bazarr</li>
  </ul>
</details>

**Comment by onny** [comment]
Result of `nixpkgs-review pr 187158` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bazarr</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Pull request merged**
