### PR TITLE
onlyoffice-bin_latest: 8.0.0 -> 8.1.0

### PR DESCRIPTION
**Pull request by leon-erd**
## Description of changes

I dont know why the automatic update did not trigger. Is there a problem with the update script?
Changelog: https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#810
Onlyoffice was split into `onlyoffice-bin` and `onlyoffice-bin_latest` because versions after `7.2` were broken on wlroots (see https://github.com/NixOS/nixpkgs/pull/285888). However, first reports indicate that wlroots support is fixed in `8.1.0` (see https://github.com/ONLYOFFICE/DesktopEditors/issues/1208#issuecomment-2192315566). So maybe there is no need anymore for the `7.2` version?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

@nh2 @GTrunSec @fin444 

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> So maybe there is no need anymore for the `7.2` version?

If that is true, we should drop the old version.

**Comment by fin444** [comment]
Too lazy to set up a WM on my NixOS install, but I live-booted Manjaro Sway and it works great there.

However, 8.0.1 also works in that setup - possibly fixed from wlroots end?

**Comment by leon-erd** [comment]
On my hyprland machine `8.1.0` and `8.0.1` also both work. But hyprland is kinda detached from wlroots now

**Comment by fin444** [comment]
Hyprland implemented their own patches for this issue, so it's not suitable to test

**Pull request merged**
