### PR TITLE
haskell generic-builder: Support installing internal libs.

### LINKED ISSUE #32980: Adapt haskell builder to new Setup register behavior with internal libraries
From https://www.haskell.org/cabal/users-guide/installing-packages.html#cmdoption-setup-register-gen-pkg-config:

> This option outputs a directory if the package requires multiple registrations: this can occur if internal/convenience libraries are used. These configuration file names are sorted so that they can be registered in order.

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #32980.

### CODE REVIEW

**Comment by shlevy** [comment]
Note: tests are still running locally and this is a mass-rebuild, @peti  do we just use staging for mass-haskell rebuilds these days?

**Comment by shlevy** [comment]
Already found some bugs, please hold 😄

**Comment by shlevy** [comment]
OK, I've tested the current locally by only enabling it for `haddock-library_1_4_4` on my `haskell-ide-engine` PR, now going to test with it enabled for all haskell and will leave it overnight.

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

(sorry for the noise, master was broken by a merge)

**Comment by shlevy** [comment]
OK was able to fully build ghc-ide-engine, including `haddock-library_1_4_4` with its internal libraries, on top of this PR.

**Comment by peti** [comment]
I'm waiting for the ghc-rebuilds to finish on Hydra. Once those changes are verified, then I'll tackle this subject.

**Comment by peti** [comment]
Pushed to test branch as 84d16e7400d89acd9c49bf3c60d9279be39b9273. Builds are running at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates.

**Pull request merged**
