### PR TITLE
Improvements to Hydra module

### PR DESCRIPTION
**Pull request by ericsagnes**
## Honor ids

Hydra related users were ignoring `uid` and `gid` defined in `nixos/modules/misc/ids.nix`.
## buildMachinesFiles

Currently `nix.buildMachines` remotes are listed in "Machine Status" and enabled in "Manage machines" but won't be used because `hydra.buildMachinesFiles` is empty by default.

This adds `/etc/nix/machines` in the default `hydra.buildMachinesFiles` so remotes defined in`nix.buildMachines` are used without explicit configuration.

cc @domenkozar 
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
Ah, that's why our hydra was building only locally with the hydra module from nixpkgs. :frowning:

Thanks a lot! Let's wait for some more feedback but big :+1: from me.

**Comment by domenkozar** [comment]
I wonder why do we have to change the default comparing to upstream Hydra? https://github.com/NixOS/hydra/blob/master/hydra-module.nix#L168

Pinning of uids will be unnecessary once https://github.com/NixOS/nixpkgs/issues/14148 is fixed

**Comment by fpletz** [comment]
Digging into this some more, I found that https://github.com/NixOS/hydra/commit/74dfcc84e9c2a40765c78ebd82650af55e027501 introduced this. This breaks the old behaviour which was to just use `/etc/nix/machines`. I think this should also be fixed (add the default value) in upstream hydra.

**Comment by ericsagnes** [comment]
I suppose upstream Hydra has the same issue. 

```
NIX_REMOTE_SYSTEMS = concatStringsSep ":" cfg.buildMachinesFiles;
```

So if `buildMachinesFiles` is empty, `NIX_REMOTE_SYSTEMS` will be empty too.

On the other hand, Hydra uses `/etc/nix/machines` when `NIX_REMOTE_SYSTEMS` is empty, see  https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/Helper/Nix.pm#L306

So if I understand the code correctly, current default behavior is that Hydra web interface list machines defined in `/etc/nix/machines` but the builder will not use it as `NIX_REMOTE_SYSTEMS` is empty.

**Comment by domenkozar** [comment]
@ericsagnes could you also fix `NIX_REMOTE_SYSTEMS` and we'll merge this here meanwhile?

**Comment by ericsagnes** [comment]
Added a PR upstream: https://github.com/NixOS/hydra/pull/372.

**Comment by domenkozar** [comment]
Thanks! Ideally we'd fix uid/gid collisions in https://github.com/NixOS/nixpkgs/issues/14148, but let's merge this for now.

**Pull request merged**
