### PR TITLE
youtube-dl-gui: init at 0.4

### LINKED ISSUE #69334: Package youtube-dl-gui
**Project description**
A cross platform front-end GUI of the popular youtube-dl written in wxPython.

This makes the awesome commandline tool usable for more people!

Most repositories use the package name **youtube-dl-gui**, so i recommend to use it tool. https://repology.org/project/youtube-dl-gui/versions

Schould be quiet easy to package.

**Metadata**

* homepage URL: https://mrs0m30n3.github.io/youtube-dl-gui/
* source URL: https://github.com/MrS0m30n3/youtube-dl-gui
* license: The Unlicense
* platforms: unix, linux, darwin, ... (Python)

### PR DESCRIPTION
**Pull request by alexarice**
###### Motivation for this change
Fixes  #69334

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@davidak

### CODE REVIEW

**Comment by alexarice** [comment]
@GrahamcOfBorg build youtube-dl-gui

**Review by davidak — CHANGES_REQUESTED** [review]
Code looks good.

Have you tested it? It seems not to work.

**Comment by davidak** [comment]
I was able to run the program, add URLs to download, but when i hit start,

it "download latest youtube-dl" (should use packaged) and tries to download the videos. That fails.

Screenshot from 2019-09-25 02-00-35

Screenshot from 2019-09-25 02-05-05

**Comment by alexarice** [comment]
I tested it briefly and thought it worked. I did see the downloading youtube-dl but then it went away when I added `youtube-dl` to propagated build inputs. Maybe mine had just managed to already download it and it needs to be added to the path instead. I'll have an investigate

**Comment by alexarice** [comment]
I've had a look and this finds it's `youtube-dl` program using it's config file and I can't see any nice way to be able to pass config items in as the config file lives in the home directory. Not sure what is the best way to solve this

**Comment by alexarice** [comment]
Ideally we want a way we could force config options from the command line, as when we could make a wrapper that supplies the correct path to the youtube-dl program

**Comment by davidak** [comment]
The best solution would be an upstream solution to disable automatic updates at buildtime since we want always our packaged version. I will create an issue there.

I think this state is usable and can be merged. It can later be improved.

Thanks for your work!

**Review by davidak — APPROVED** [review]
good for now

**Comment by alexarice** [comment]
I'll make a comment in the code and remove `youtube-dl` from propagatedBuildInputs as it doesn't find it anyway

**Comment by alexarice** [comment]
was going to make an issue but https://github.com/MrS0m30n3/youtube-dl-gui/issues/380 is worrying.
On a side note did you manage to test the ffmpeg stuff?

**Comment by davidak** [comment]
>MrS0m30n3/youtube-dl-gui#380 is worrying.

oh no. then we might not add an unmaintained package with issue.

I hope there will be an active fork or another GUI.

>did you manage to test the ffmpeg stuff?

no. but i did now.

I selected "mp3" as format and added a youtube video. It was downloaded 100% as webm and then status error. I can play the webm, but it has no image, just audio. Same with vorbis and m4a.

When selecting webm, the video has no audio.

mp4 works. it is the default.

maybe the ffmpeg package is missing codecs?

**Comment by Lassulus** [comment]
failing for me with:
```
builder for '/nix/store/jqn38icyy79rd0l3whwkdav3ddmn4ih2-python2.7-youtube-dl-gui-0.4.drv' failed with exit code 1; last 10 log lines:
  unpacking sources
  unpacking source archive /nix/store/77qdqidp5adszh8p86xgm26wwdmki2kc-source
  source root is source
  setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/youtube_dl_gui/widgets.py
  patching sources
  configuring
  no configure script, doing nothing
  building
  Executing setuptoolsBuildPhase
  No module named wx
cannot build derivation '/nix/store/c55bf68ads4q1vmk8031fc27d42znq1k-env.drv': 1 dependencies couldn't be built
```

**Comment by davidak** [comment]
There is still no popular, maintained fork. We should just close this.

**Comment by pbogdan** [comment]
There's https://github.com/axcore/tartube for anyone looking for alterantives.

**Pull request closed without merging**
