### PR TITLE
gopass: switch to go_1_18_3

### PR DESCRIPTION
**Pull request by kraem**
###### Description of changes

Introducing `go_1_18_3` and pinning gopass to it due to gopass being broken on go 1.18.4 (https://github.com/gopasspw/gopass/issues/2280)

cc @zowoq @Mic92 @rvolosatovs @sikmir 

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kraem** [comment]
Found https://github.com/NixOS/nixpkgs/pull/181281#issuecomment-1190172668 after submitting this pr indicating we should just wait for 1.18.5. Feel free to close this pr if it's unwanted :+1:

**Comment by zowoq** [comment]
This would be better:

```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 49772490ff0..1e9110509e3 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -2584,15 +2584,38 @@ with pkgs;
 
   go-audit = callPackage ../tools/system/go-audit { };
 
-  gopass = callPackage ../tools/security/gopass { };
+  gopass = callPackage ../tools/security/gopass {
+    # pinned due to https://github.com/gopasspw/gopass/issues/2280
+    # when go_1_18 is bumped to 1.18.5 please remove __buildGo1183Module
+    buildGoModule = __buildGo1183Module;
+  };
 
-  gopass-hibp = callPackage ../tools/security/gopass/hibp.nix { };
+  gopass-hibp = callPackage ../tools/security/gopass/hibp.nix {
+    buildGoModule = __buildGo1183Module;
+  };
 
-  gopass-jsonapi = callPackage ../tools/security/gopass/jsonapi.nix { };
+  gopass-jsonapi = callPackage ../tools/security/gopass/jsonapi.nix {
+    buildGoModule = __buildGo1183Module;
+  };
 
-  git-credential-gopass = callPackage ../tools/security/gopass/git-credential.nix { };
+  git-credential-gopass = callPackage ../tools/security/gopass/git-credential.nix {
+    buildGoModule = __buildGo1183Module;
+  };
 
-  gopass-summon-provider = callPackage ../tools/security/gopass/summon.nix { };
+  gopass-summon-provider = callPackage ../tools/security/gopass/summon.nix {
+    buildGoModule = __buildGo1183Module;
+  };
+
+  __buildGo1183Module = darwin.apple_sdk_11_0.callPackage ../development/go-modules/generic {
+    go = buildPackages.go_1_18.overrideAttrs (_: rec {
+      version = "1.18.3";
+      doCheck = false;
+      src = fetchurl {
+        url = "https://go.dev/dl/go${version}.src.tar.gz";
+        sha256 = "sha256-ABI4bdy7XzNQ5AfGeZI4EdvSg/zcQhckkxYUqELsvC0=";
+      };
+    });
+  };
 
   gosh = callPackage ../tools/security/gosh { };
 
```

TBH I'd rather people just use a olderver nixpkgs revision for `gopass`, etc where it is building with 1.18.3.

**Comment by kraem** [comment]
Makes sense. Sorry about the noise.

**Comment by flokli** [comment]
@zowoq I'm not sure when go_1_18_15 will get released, but I'd rather see your non-obstrusive workaround shown in https://github.com/NixOS/nixpkgs/pull/182327#issuecomment-1191356536 shipped than keeping the build in nixpkgs master broken.

**Comment by flokli** [comment]
PR up at https://github.com/NixOS/nixpkgs/pull/182784, PTAL.

**Comment by zowoq** [comment]
> I'm not sure when go_1_18_15 will get released

Couple of weeks. Could also backport the fix so it would be fixed in the next staging cycle.

> I'd rather see your non-obstrusive workaround shown in https://github.com/NixOS/nixpkgs/pull/182327#issuecomment-1191356536 shipped than keeping the build in nixpkgs master broken.

If waiting for the next staging cycle isn't acceptable I'd like to see that some other attempt at fixing this before we resort  to adding another top-level `buildGoModule` (and building another `go`) for what is basically just variants of one broken package.

**Comment by zowoq** [comment]
Not sure if they are relevant to `gopass`, etc but 1.18.4 contains several security fixes so using 1.18.3 for any reason doesn't seem like a good idea.

**Comment by sikmir** [comment]
> If waiting for the next staging cycle isn't acceptable

I think waiting for go 1.18.5 is OK, I've just added `nixos-22.05` input to my flake configuration and got gopass working, while having all other packages from `nixos-unstable`.

**Pull request closed without merging**
