### PR TITLE
bazel_6: Fix empty bzlmod lock file

### LINKED ISSUE #273500: bazel_6: `MODULE.bazel.lock` file is empty
### Describe the bug
Using Bazel from nixpkgs in a project with bzlmod enabled, and `--lockfile_mode=update` the generated `MODULE.bazel.lock` file does only contain an empty JSON object.

### Steps To Reproduce
1. `git clone https://github.com/bazelbuild/examples.git`
2. `cd examples/bzlmod/01-depend_on_bazel_module`
3. `rm .bazelversion`
4. `nix run nixpkgs#bazel_6 -- mod deps --lockfile_mode=update`

```console
$ nix run nixpkgs#bazel_6 version
Build label: 6.4.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
$ ls -lh MODULE.bazel.lock
-rw-r--r-- 1 claudio users 3 Dec 11 09:02 MODULE.bazel.lock
$ head MODULE.bazel.lock
{}
```

### Expected behavior

The generated lock file should be equivalent to the file generated by a vanilla Bazel distribution binary:
```console
$ bazel version
Bazelisk version: v1.16.0
Starting local Bazel server and connecting to it...
Build label: 6.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 17:07:43 2023 (1697735263)
Build timestamp: 1697735263
Build timestamp as int: 1697735263
$  bazel mod deps --lockfile_mode=update
<root> (example@0.0.1)

 checking cached actions
$ ls -lh ls -lh MODULE.bazel.lock 
-rw-r--r-- 1 root root 75K Dec 11 08:07 MODULE.bazel.lock
$ head MODULE.bazel.lock
{
  "lockFileVersion": 3,
  "moduleFileHash": "47f831d13c88b71ebfb233245e6e8c208f8d2e09b51e780699178a31ccf165dd",
  "flags": {
    "cmdRegistries": [
      "https://bcr.bazel.build/"
    ],
    "cmdModuleOverrides": {},
    "allowedYankedVersions": [],
    "envVarAllowedYankedVersions": "",
```

### Additional context

See also https://github.com/bazelbuild/bazel/issues/19672 where the same problem was reported for Bazel from homebrew.

The formula from homebrew is here:
https://github.com/Homebrew/homebrew-core/blob/fda88ddb4c8ea04adcfa001c56a1b35aebd64e86/Formula/b/bazel.rb

### Notify maintainers

@NixOS/bazel 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20231128.7c4c205`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-21.11.336182.a25df4c2b79"`
 - nixpkgs: `/etc/nixpkgs`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by avdv**
## Description of changes

This works around an issue with bootstrapping bazel from scratch, see
https://github.com/bazelbuild/bazel/issues/20501

Fixes #273500

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by uri-canva — CHANGES_REQUESTED** [review]
There's a better fix available upstream, can we use that? https://github.com/bazelbuild/bazel/pull/20587

**Comment by avdv** [comment]
> There's a better fix available upstream, can we use that? [bazelbuild/bazel#20587](https://github.com/bazelbuild/bazel/pull/20587)

Yes, saw that and I'll update the PR.

**Comment by avdv** [comment]
I have incorporated the patch from https://github.com/bazelbuild/bazel/pull/20612 and added a regression test adapted from #262152

**Review by uri-canva — APPROVED** [review]

**Comment by avdv** [comment]
> It's the execlog parser though, not bazel itself, so maybe we can just stop building it.

:+1:  I added a commit which skips this step on darwin.

**Review by uri-canva — APPROVED** [review]

**Review by uri-canva — CHANGES_REQUESTED** [review]
Back to you, sorry.

**Comment by avdv** [comment]
> Back to you, sorry.

My bad. Seems like I fixed it this time, builds and tests are green on x86_64-darwin.

**Comment by avdv** [comment]
@uri-canva could you have a look again, please?

**Comment by avdv** [comment]
closing, superseded by https://github.com/NixOS/nixpkgs/pull/283480

**Pull request closed without merging**
