### PR TITLE
roslyn-ls: 4.12.0-3.24470.4 -> 4.13.0-3.24577.4

### PR DESCRIPTION
**Pull request by konradmalik**
https://github.com/dotnet/vscode-csharp/releases/tag/v2.59.14

Also removed dotnet 6 and 7 from the combined sdk because they are EOL and started to show up as insecure (they need to be explicitly added to 'permittedInsecurePackages').

While dotnet 6 is removed from nix dependencies and the package no longer triggers "insecure" warnings, dotnet 6 nuget dependencies are generated and locked in deps.nix. This is because upstream relies on net6.0 still. Though, I don't think  this is a big pain because net6.0 won't be updated anymore in nixpkgs, so it won't trigger unnecessary roslyn-ls deps.nix changes.

I've tried to add the below to `dotnetFlags`:
```
    "-p:NetRoslynBuildHostNetCoreVersion=net8.0"
```
which removes dotnet 6 nuget dependencies from deps.nix, but the compilation fails. I guess we can only remove this after upstream stops relying on net6.0 in: https://github.com/dotnet/roslyn/blob/6cc106c0eaa9b0ae070dba3138a23aeab9b50c13/eng/targets/TargetFrameworks.props#L20

I guess the current solution is fine for now.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
Take a look at what I did here:

https://github.com/NixOS/nixpkgs/pull/361563/files#diff-a70a7b06dd87a3e3e5fb4233ac8418a17a8068b9ce926eb40674b28b3276d336R15

Instead of combining the SDKs, we use a single SDK and pull the packages in from the others.

This should fix the insecure warning without requiring the packages in the lock file.

**Comment by konradmalik** [comment]
@corngood hmm, I'm not sure if I did something wrong, but see deps.nix in 7863243a0cb59db5fc053716b9a01816fcf63f8c
looks like it now even includes deps from SDK 9.0 for some reason... 🤔

**Comment by corngood** [comment]
> Edit: ahh I think this is because // replaces keys, right? So we should add sdk_9 twice. First as the main SDK, second as the packages source.

Yeah, that's right.  Pulling packages in this way is a bit of a hack, but there's no helper to do it yet, and it's better than requiring the SDK itself.

**Comment by corngood** [comment]
@konradmalik I'd like to backport this to 24.11, but it has a minor version update.

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases

> ✔️ Minor versions with new functionality, but no breaking changes

What's your recommendation as maintainer?  I suspect it's probably okay, but I just wanted to confirm.

**Review by corngood — APPROVED** [review]

**Comment by konradmalik** [comment]
there should not be any breaking changes - the lsp works as before, with editors it worked before, using the same protocol as before, so backporting should be safe

**Comment by corngood** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357963`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>roslyn-ls</li>
  </ul>
</details>

**Pull request merged**
