### PR TITLE
python3Packages.discordpy: fix libopus path on Darwin

### PR DESCRIPTION
**Pull request by al3xtjames**
###### Description of changes

Darwin uses .dylib as the extension for dynamic libraries (unlike Linux which uses .so). Replace the hardcoded extension with stdenv.hostPlatform.extensions.sharedLibrary to fix Opus support on darwin.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 243765` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.discordpy</li>
    <li>python310Packages.discordpy.dist</li>
    <li>python311Packages.discordpy</li>
    <li>python311Packages.discordpy.dist</li>
  </ul>
</details>

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 243765` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.discordpy</li>
    <li>python310Packages.discordpy.dist</li>
    <li>python311Packages.discordpy</li>
    <li>python311Packages.discordpy.dist</li>
  </ul>
</details>

**Review by tjni — APPROVED** [review]
LGTM. I verified too that libopus.so is a symlink to libopus.so.0 on Linux.

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 243765` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.discordpy</li>
    <li>python310Packages.discordpy.dist</li>
    <li>python311Packages.discordpy</li>
    <li>python311Packages.discordpy.dist</li>
  </ul>
</details>

```sh
$ tree /nix/store/47y0r8swcngkh49vv9imk2n8pz4s30yw-libopus-1.4
/nix/store/47y0r8swcngkh49vv9imk2n8pz4s30yw-libopus-1.4
└── lib
    ├── libopus.0.dylib
    └── libopus.dylib -> libopus.0.dylib
```

Result of `nixpkgs-review pr 243765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.discordpy</li>
    <li>python310Packages.discordpy.dist</li>
    <li>python311Packages.discordpy</li>
    <li>python311Packages.discordpy.dist</li>
  </ul>
</details>

```sh
$ tree /nix/store/gkviniiy5h717lwqhb3kv29v3blbq77v-libopus-1.4
/nix/store/gkviniiy5h717lwqhb3kv29v3blbq77v-libopus-1.4
└── lib
    ├── libopus.so -> libopus.so.0
    ├── libopus.so.0 -> libopus.so.0.9.0
    └── libopus.so.0.9.0
```

**Review by sikmir — APPROVED** [review]

**Pull request merged**
