### PR TITLE
[20.09] chromium: 89.0.4389.90 -> 89.0.4389.114

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

Backport of #118133. If someone has the time/resources to build `nixosTests.chromium` that would be welcome (my build host is currently running a few other time-consuming builds).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
❯ nix-build -j1 nixos/tests/chromium.nix
error: Package ‘chromium-beta-90.0.4430.51’ in /home/hexa/git/nixos/master/pkgs/applications/networking/browsers/chromium/browser.nix:72 is marked as broken, refusing to evaluate.
```

**Comment by mweinelt** [comment]
Fails reproducibly for me.

```
configuring
Done. Made 15864 targets from 2665 files in 10714ms
building
ninja: Entering directory `out/Release'
[1717/1717] LINK ./mksnapshot.stampstampassembler.o[Kn.o.ooKKK)fault)
ninja: Entering directory `out/Release'
[3/3] LINK ./chrome_sandboxome_sandbox/sandbox.o_linux.o
ninja: Entering directory `out/Release'
[6429/44266] CXX obj/third_party/angle/libANGLE_base/MemoryProgramCache.otogen.oltins.o[Klt)efault)lt)lt)[Kt)[K[Ke:default)[Kt)ult)model-legacy.js
../../third_party/angle/src/libANGLE/MemoryProgramCache.cpp:24:9: warning: 'USE_SYSTEM_ZLIB' macro redefined [-Wmacro-redefined]
#define USE_SYSTEM_ZLIB
        ^
<command line>:48:9: note: previous definition is here
#define USE_SYSTEM_ZLIB 1
        ^
1 warning generated.
[6522/44266] CXX obj/third_party/angle/src/libANGLE/renderer/vulkan/angle_vulkan_backend/vk_internal_shaders_autogen.oain/linux/unbundle:default)efault)
../../third_party/angle/src/libANGLE/renderer/vulkan/vk_internal_shaders_autogen.cpp:13:9: warning: 'USE_SYSTEM_ZLIB' macro redefined [-Wmacro-redefined]
#define USE_SYSTEM_ZLIB
        ^
<command line>:38:9: note: previous definition is here
#define USE_SYSTEM_ZLIB 1
        ^
1 warning generated.
[6595/44266] CC obj/third_party/fontconfig/fontconfig/fcxml.od/theme_support:theme_support-typescript(//build/toolchain/linux/unbundle:default)[K)
../../third_party/fontconfig/src/src/fcxml.c:3609:6: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
            strerror_r (errno_, ebuf, BUFSIZ);
            ^~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~
1 warning generated.
client_loop: send disconnect: Broken pipe
error: unexpected end-of-file
builder for '/nix/store/mwj5jx4nimybx00hq7vhqmi7ldkrmmfl-chromium-unwrapped-89.0.4389.114.drv' failed with exit code 1
cannot build derivation '/nix/store/zfbrsfz1fxqdhk8diyx74nvwp3zv4yk4-chromium-89.0.4389.114.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vdz323f2l5lhw6f58pj8y9ivcc4nd4gd-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d2ghc972s3rhvrh3rxvwwz8776w4ihdy-nixos-system-machine-20.09pre-git.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dyypk3x8hg27hjqj87s1ymk889f66fya-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mgfjnrrbqb1mpnyrzh6h23wz7igh4glw-nixos-test-driver-chromium-stable.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7pjib5ydzbyrbb21vndyx0glycbqz213-vm-test-run-chromium-stable.drv': 1 dependencies couldn't be built
error: build of '/nix/store/7pjib5ydzbyrbb21vndyx0glycbqz213-vm-test-run-chromium-stable.drv' failed
```

**Comment by primeos** [comment]
That's unfortunate but `error: unexpected end-of-file` is hopefully due to disk-space or inode limits (e.g. an issue when building with /tmp on tmpfs, IIRC). Anyway, huge thanks for trying to build it.

**Comment by mweinelt** [comment]
Oh, that may well be. I can extend the disk space right now.

**Comment by primeos** [comment]
Ok, strange :o Maybe I can try to reproduce it in a few hours / tomorrow. I also missed the `client_loop: send disconnect: Broken pipe` which is strange as well (IIRC I've only/mostly seen this for SSH disconnects).

**Comment by primeos** [comment]
`nixosTests.chromium` succeeded on my test system:

```
# i5-6500 CPU
real    595m53.702s
user    2213m56.490s
sys     73m33.081s
```

**Comment by mweinelt** [comment]
```
/nix/store/jsbbhwx2rnnv22d1ks0xw7bqg0d0wn4s-vm-test-run-chromium-stable
```

Yup, built it locally on my build host and that worked.

**Pull request merged**
