### PR TITLE
discourse: 2.6.5 -> 2.7.0

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
Update Discourse to the latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ryantm — APPROVED** [review]

**Review by dpausp — APPROVED** [review]

**Comment by dpausp** [comment]
LGTM. Updated my test system from 2.6.5, tested: posting, Wiki editing, changing settings, sending mails, and backup.

**Comment by ryantm** [comment]
Has anyone tried importing a backup yet? I had a backup from version 2.7.0.beta7 that I tried to import to 2.7.0 and got an error:

```
[2021-05-25 17:16:19] Restoring dump file... (this may take a while)
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] set_config
[2021-05-25 17:16:19] ------------
[2021-05-25 17:16:19] (1 row)
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] SET
[2021-05-25 17:16:19] CREATE TABLE
[2021-05-25 17:16:19] CREATE SEQUENCE
[2021-05-25 17:16:19] ALTER SEQUENCE
[2021-05-25 17:16:19] CREATE TABLE
[2021-05-25 17:16:19] CREATE SEQUENCE
[2021-05-25 17:16:19] ALTER SEQUENCE
[2021-05-25 17:16:19] CREATE TABLE
[2021-05-25 17:16:19] CREATE SEQUENCE
[2021-05-25 17:16:19] ALTER SEQUENCE
[2021-05-25 17:16:19] CREATE TABLE
[2021-05-25 17:16:19] ERROR:  syntax error at or near "AS"
[2021-05-25 17:16:19] LINE 2:     AS integer
[2021-05-25 17:16:19] ^
[2021-05-25 17:16:19] EXCEPTION: psql failed:             ^
```

**Comment by dpausp** [comment]
I have another instance running 2.7.0.beta5, I can try restoring a backup from there into a new installation later.

**Comment by ryantm** [comment]
It's possible backups from the beta version are just not compatible with the stable version.

**Comment by ryantm** [comment]
https://meta.discourse.org/t/restoring-backup-fails-in-win10-ubuntu-development-environment/86893/12 found this post with the same error message, I think it may be different versions of postgresql.

Exporting server docker container
```
# /usr/lib/postgresql/13/bin/postmaster --version
postgres (PostgreSQL) 13.2 (Debian 13.2-1.pgdg100+1)
```

Importing NixOS server

```
/nix/store/b264ng9g5dnsqjcwyz226cyd2zp29vm3-postgresql-9.6.21/bin/postgres
```

**Comment by ryantm** [comment]
Setting `services.postgresql.package = pkgs.postgresql_13;` got me farther along in the import

New error:
```
[2021-05-26 18:26:41] Remapping 'https://SITENAME1.example.com' 'https://SITENAME2.example.com'
[2021-05-26 18:26:44] Restoring uploads, this may take a while...
[2021-05-26 18:26:44] EXCEPTION: No such file or directory - rsync
```

**Comment by ryantm** [comment]
https://github.com/ryantm/nixpkgs/commit/4c5cdac952160f075cedc56a5053281413965e57 fixes the rsync issue during import and my import worked!

**Comment by talyz** [comment]
@ryantm Added your fix and warning about mismatching postgres versions. I don't think we can really dictate which version is used, since the user may already have a postgres instance for something else which could then break or have older discourse backups which would likely require an older postgres version for restoration. The alternative I can see is making it an assertion and adding an option to override the assertion.

**Comment by talyz** [comment]
Thinking about it, the second alternative is probably better, since it stops people from performing a potentially destructive upgrade. I'll implement that instead.

**Comment by jonringer** [comment]
looks like aarch64 is broken from ruby packages: 
```
LoadError: Could not open library '/nix/store/hbnd096d0yhgsxgv142xm3agn56j1vh5-ruby2.7.3-mini_suffix-0.3.2/lib/ruby/gems/2.7.0/gems/mini_suffix-0.3.2/vendor/libpsl.x86_64.so': /nix/store/hbnd096d0yhgsxgv142xm3agn56j1vh5-ruby2.7.3-mini_suffix-0.3.2/lib/ruby/gems/2.7.0/gems/mini_suffix-0.3.2/vendor/libpsl.x86_64.so: cannot open shared object file: No such file or directory.
```
Do you mind removing it as a platform?

**Review by ryantm — APPROVED** [review]

**Comment by talyz** [comment]
@jonringer I've pushed a fix to make it find the file instead, but I don't have any aarch64 machine to test on, so ofborg will have to tell us if it worked.

**Comment by jonringer** [comment]
looks like the service was able to start in this case for the tests.

why it timed out? not sure.

**Comment by talyz** [comment]
Yeah. It probably timed out because the aarch64 system is really slow. I've had that affect the reliability of the test previously, too.

**Pull request merged**
