### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by hedning** [comment]
[valgrind is failing again](https://hydra.nixos.org/build/85398314/nixlog/1), so looks like #51107 didn't do it's job. I'm guessing the change never reaches `Makefile.in` as the tarball ships with it readymade.

**Comment by jtojnar** [comment]
Yup autoreconfHook will be needed.

**Comment by hedning** [comment]
Some test failures:

- [ ] [`python3.pkgs.pyjwt`](https://hydra.nixos.org/build/85423136).  Reverting bcf736b325cbc577ed083995366396656e93e96c fixed the issue.  28cdb6e841b9098517c2a7957454437387ca887d fixes the build with pytest-3.9.0 so we shouldn't need to use pytest_37 

- [ ] [`libcouchbase`](https://hydra.nixos.org/build/85451720) fails a test, reproducable locally. Touched by openssl upgrade: ae29a9e688845f276c60aa48e3d8426a2b9b2d6d

**Comment by hedning** [comment]
qemu is broken due to [spice](https://hydra.nixos.org/build/85419784) (link to the first broken build):
```
/nix/store/8rnh2n15w4wlz14wlg41b7mh8xjwjmsm-binutils-2.30/bin/ld: cannot find -lgssapi_krb5
/nix/store/8rnh2n15w4wlz14wlg41b7mh8xjwjmsm-binutils-2.30/bin/ld: cannot find -lkrb5
/nix/store/8rnh2n15w4wlz14wlg41b7mh8xjwjmsm-binutils-2.30/bin/ld: cannot find -lk5crypto
/nix/store/8rnh2n15w4wlz14wlg41b7mh8xjwjmsm-binutils-2.30/bin/ld: cannot find -lcom_err
```
Adding `libkrb5` fixes the build, but `spice` shouldn't really need to depend on `libkrb5` directly. It won't add to the closure size though I guess.

Grepping for `-lkrb5` on the requisites returns a bunch of hits on `cyrus_sasl` .la files ([Looks similar to the hunspell/mythes issue](https://github.com/NixOS/nixpkgs/issues/51297)). `cyres_sasl-2.1.26` on master only have two .la files with -lkrb5 compared to `2.1.27`. I'm guessing that's the cause.

Any thoughts? A general solution to avoid picking up stuff from .la files when pgk-config files are available would be good, though not sure if it's doable?

**Comment by hedning** [comment]
Some reproducible failures (new compared against [trunk](https://hydra.nixos.org/eval/1493389)):

- [ ] [libmemcached](https://hydra.nixos.org/build/85464574/nixlog/1) complains about missing `-lkrb5` just like `spice`

- [ ] [nss_pam_ldapd](https://hydra.nixos.org/build/85464844/nixlog/1): the failing code block is [hidden behind `HAVE_GSS_KRB5_CCACHE_NAME`](https://arthurdejong.org/git/nss-pam-ldapd/tree/nslcd/cfg.c#n573), which configure sets, `checking for gss_krb5_ccache_name... yes`. This isn't the case on [master](https://hydra.nixos.org/build/84916884/nixlog/1). Most likely the same root cause as `spice` ie. `cyrus_sasl` upgrade.  Adding `libkrb5`  fixes this build too, but shouldn't really be necessary.

- [ ] [notmuch](https://hydra.nixos.org/build/85476622/nixlog/1) failing tests. Looks lke a python version mixup, no idea where it gets hold of python3 though. Switching to python3 fixes the build, but I would guess there might be stuff depending on the python2 bindings?

- [ ] [syncthing](https://hydra.nixos.org/build/85417361/nixlog/1) [syncthing-relay](https://hydra.nixos.org/build/85420508/nixlog/1)

- [ ]  [gnustep.base](https://hydra.nixos.org/build/85403714/nixlog/1) complains about `libffi`  not working

- [ ]  [gtkgnutella](https://hydra.nixos.org/build/85478711/nixlog/1)

**Comment by pbogdan** [comment]
The `xfsprogs` update seems to break the LVM installer test. Looks to be an instance of https://bugzilla.redhat.com/show_bug.cgi?id=1575797 that's been patched in grub http://git.savannah.gnu.org/cgit/grub.git/commit/?id=cda0a857dd7a27cd5d621747464bfe71e8727fff.

**Comment by FRidh** [comment]
@hedning thanks for reporting issues here. I think that's good to do, though I think we should only focus on the blocking type of issues. Minor breakage is dealt with on master. A failing test is not good, though that might be handled more swiftly on master as well.

This merge will cause a lot more breakage of Python packages due to package set updates which includes some broken updates as well.

**Comment by nyanloutre** [comment]
There is a breakage introduced by the pyqt update (5.10 -> 5.11), the sip package must be handeled differently to be able to import the module.

I did some investigation here : https://github.com/NixOS/nixpkgs/pull/49400#issuecomment-444536504

**Comment by grahamc** [comment]
I'm noticing the staging jobset on hydra hasn't run since November 27 ,and it hasn't even finished. Is there a jobset I don't know about? I'm concerned maybe something has broken in the shuffle here.

**Comment by grahamc** [comment]
Answer, yes: https://hydra.nixos.org/jobset/nixpkgs/staging-next :)

**Comment by copumpkin** [comment]
@FRidh is this merge likely to happen soon? I'm waiting for the awscli/boto3/botocore updates and might manually transplant them over to master if this branch is going to take a while. There's no fundamental reason I think to bundle those with the rest of these updates, right?

**Comment by hedning** [comment]
Looks like it comes from here: https://github.com/NixOS/nixpkgs/pull/51960, probably targeted at master by a mistake.

**Pull request merged**
