### PR TITLE
treewide: Per RFC45, remove all unquoted URLs

### PR DESCRIPTION
**Pull request by OmnipotentEntity**
###### Motivation for this change

Per [RFC45](https://github.com/NixOS/rfcs/pull/45), unquoted URL syntax is deprecated.  Unfortunately, I was unaware of this, and myself along with probably many other newer contributors really form habits around packages that are already in the repository.

So this pull request aims to clean up the vast majority of these unquoted strings.  So that people learning learn the newer habits, and so that when an automated message comes along, we won't all be drowning in warnings.

This pull request should contain no changes other than quoting previously unquoted strings.  If you see something in this PR that does not fit that criteria, please flag me, and I'll fix it.  Because this is only fixing quotes on strings, this change should not actually cause any rebuilds, if it does, that is also a bug.

Unfortunately, while I have performed various sorts of static analysis on this PR, it is far too large for any single person to verify and test.  I also expect it to need to be fixed for merge conflicts.  If you are a maintainer interested in merging this PR, please flag me down on IRC, and I'll fix up the latest merge conflicts for you right before you want to merge.  I will also keep it refreshed at a rate of at least once per day while under review.

### CODE REVIEW

**Comment by OmnipotentEntity** [comment]
If I missed an unquoted string (most likely within a list or as a sub field) please let me know as well, and I will quote it.

**Comment by bhipple** [comment]
Nice!  Since this diff is enormous and you're willing/prepared to handle merge conflicts, I'm assuming it's done by a script?  It might be useful to publish the script on a gist as well, so that it can be reviewed alongside the actual diff.

**Comment by OmnipotentEntity** [comment]
Actually, it was done by hand with the aid of grep and vim macros.

**Comment by zimbatm** [comment]
Is there any way to extend ofborg so this can be done on a per-PR basis and slowly trickle into nixpkgs?

**Comment by 7c6f434c** [comment]
>Is there any way to extend ofborg so this can be done on a per-PR basis and slowly trickle into nixpkgs?

Automated updates by r-ryantm do quote URLs they encounter in the file, so I was planning for this flow to run out before advocating further measures.

**Comment by Mic92** [comment]
I suppose there could be also a github action to add those commits.

**Comment by OmnipotentEntity** [comment]
> so I was planning for this flow to run out before advocating further measures.

That's fair, but now that I just up and did most of the repository, do you have an objection?

**Comment by 7c6f434c** [comment]
>That's fair, but now that I just up and did most of the repository, do you have an objection?

First of all, thanks for your effort.

Of course, the current state is not the state to merge (ofborg reports rebuilds right now, although fortunately very few). I would not ask anyone to do so much effort manually (and we know automated tooling based on hnix would have a few corner cases with failed evaluation), but as you have heroically done that, I am slightly in favour of merging it. But I remember people objecting to huge-churn global fix, and while I do not fully agree with them, I also do not have convincing arguments to make them in favour.

BTW, if you manually resolve conflicts, how many conflicts do you need to resolve (normalised per 24h, say)? This is a piece of data that was purely hypothetical in the previous discussions (as collecting this requires a lot of effort, we did not expect an effort like yours being done by hand), and would at least prevent the discussion of unquantified hypotheticals.

**Comment by grahamc** [comment]
One question I have is how do we verify the diff? Perhaps some looking at the patch and validating the diff comes down to the addition of two `"`s?

**Comment by Infinisil** [comment]
As already mentioned in the RFC, I already implemented tooling to do this fully automatically, based on [hnix](https://github.com/haskell-nix/hnix) and with a test suite: https://github.com/Infinisil/nix-quote-urls.

This fully parses the Nix files and does replacement based on the AST node, not on strings. As such I'm very confident that it should work very well without false negative or positives, and I'd be in favor of using it instead. Since recently it also supports verification, which can be used by ofborg to check that no unquoted urls are used.

**Comment by bhipple** [comment]
Perhaps you should run the tool and `diff` the result against this PR.  Then we'd have two independent implementations checking the diff :)

**Comment by 7c6f434c** [comment]
>This fully parses the Nix files and does replacement based on the AST node, not on strings. As such I'm very confident that it should work very well without false negative or positives, and I'd be in favor of using it instead. 

Hmmm. Last PR with nixpkgs-fmt over Nixpkgs showed that hnix has some differences with Nix about exact possibilities in unquoted URLs…

**Comment by OmnipotentEntity** [comment]
> BTW, if you manually resolve conflicts, how many conflicts do you need to resolve (normalised per 24h, say)? 

Thus far it's been a total of two.  One I resolved prior to pushing which crept in while I was actually performing the work.  The second was the one I resolved earlier today.  I had expected between 6-10/day, but it seems to be far fewer.

> This fully parses the Nix files and does replacement based on the AST node, not on strings. As such I'm very confident that it should work very well without false negative or positives, and I'd be in favor of using it instead. Since recently it also supports verification, which can be used by ofborg to check that no unquoted urls are used.

That's wonderful.  It is, of course, the correct way to do it.  My way was just a hack way that I decided to spend a boring afternoon on.  If you do decide to run it and make a pull request, I would be interested in a diff between the two.

>  (ofborg reports rebuilds right now, although fortunately very few)

I'll look into that and fix them.

**Comment by jtojnar** [comment]
How many conflicts are there with staging? We merge master periodically into staging but the other direction has been stuck for a month due to hydra issues.

**Comment by OmnipotentEntity** [comment]
I got in touch with infinisil on IRC and was able to compare his automatic tool against my hand cranked madness, and they mostly agree. His tool caught more URLs than mine, so I've added those.  We had a few merge conflicts between the two approaches due to white space handling, those are resolved.

However, his tool did expose a bug in a particular package.  So far I have left that string alone for the time being, and I'll someone submit a PR to fix the bug instead.

Other than those errata, both approaches are in agreement.

**Comment by OmnipotentEntity** [comment]
@jtojnar there are 17 conflicts with staging.

**Comment by OmnipotentEntity** [comment]
@grahamcofborg eval

please and thank you

**Comment by FRidh** [comment]
> How many conflicts are there with staging? We merge master periodically into staging but the other direction has been stuck for a month due to hydra issues.

Right. These merge conflicts are annoying and right now is especially a bad time because it's been stuck.

**Comment by 7c6f434c** [comment]
@FRidh does staging being stuck make matters too bad if master → staging merges still happen and the number of conflicts is apparently ~ ten per week?

**Comment by jtojnar** [comment]
It would matter if the staging diverged too much. Fortunately it did not so we can merge this to master and then merge master to staging-next and resolve conflicts there.

**Comment by Mic92** [comment]
I can also recommend for people often doing these merges to do:

```
$ git config --global rerere.enabled true
```

This way you can already record merge conflict solution up front and they will be replayed once you are doing the actual merge: https://git-scm.com/book/en/v2/Git-Tools-Rerere

**Comment by OmnipotentEntity** [comment]
Good morning.

Fixed 4 conflicts this morning, and added one more pair of quotations around a new bare URL that snuck in.

**Comment by bhipple** [comment]
For what it's worth, I'm in favor of merging this provided we can get OfBorg down to 0 computed rebuilds.  @OmnipotentEntity you should be able to run this to tell you what's changing, once it's not in a conflicted state:

```
nix run -I nixpkgs=channel:nixos-unstable nixpkgs.nixpkgs-review -c nixpkgs-review pr 83909
```
If there are some packages that require a legitimate rebuild due to the quoting somehow, let's do those in their own PR and merge that first.  

---

Some extra context: a couple weeks ago, I updated the [nixpkgs-update](https://github.com/ryantm/nixpkgs-update) bot to start quoting homepage URLs when it updates.  
You can read more about that here: https://discourse.nixos.org/t/steps-towards-even-more-pr-automation/5634/11.  Here's an example of it doing its thing:

https://github.com/NixOS/nixpkgs/pull/83984

It always pings [RFC 45](https://github.com/NixOS/rfcs/pull/45) when it makes a change, so if you scroll to the bottom you can see it's updated hundreds of packages in the past couple weeks.  Over time this would, if left on its own, slowly take care of most of NixPkgs.

I was also planning on adding a PR validation to [OfBorg](https://github.com/NixOS/ofborg), so that it would remind PR contributors/maintainers and slowly ratchet in the change.  Even once we've done everything, I think that should still be in-place regardless to prevent backsliding.  I haven't gotten to that yet, but if you (or someone else) is interested in hacking on some Rust I think it'd be great contribution (pending agreement from @grahamc).

**Comment by OmnipotentEntity** [comment]
This version triggers no rebuild. @bhipple 

I'll open a second PR for the stuff that does.

**Comment by OmnipotentEntity** [comment]
@GrahamcOfBorg eval

I suspect the internal error had something to do with github being flaky a few hours back.

**Comment by OmnipotentEntity** [comment]
Good morning.  I have fixed the merge conflicts for today.  One merge conflict due to changed URL.

**Comment by grahamc** [comment]
GitHub keeps breaking their API in incompatible ways :(

**Comment by OmnipotentEntity** [comment]
One conflict for today, renamed commit per @bhipple.

**Comment by OmnipotentEntity** [comment]
Fixed 23 packages this morning. That's more like it!

3 due to a removed patches
4 due to updating adjacent metadata
8 generated files updated (generated with bareURLs)
3 files removed entirely
3 due to marking package as broken or partially broken
1 due to the URL directly changing
1 due to whitespace differences (indenting fixed)

Additionally, 5 pkgs that were either just added or previously correct had bare URLs introduced, they were also fixed.

**Comment by OmnipotentEntity** [comment]
Three conflicts fixed today.  Fixed one new bare URL in the new commits.

Question.  Would you like me to restructure this commit into smaller batch commits (like 1000 apiece) and/or keep the daily merge fixes, then rebase at the end?  Will that help with the review process? @bhipple @grahamc @FRidh ?

**Comment by OmnipotentEntity** [comment]
@GrahamcOfBorg eval

**Comment by grahamc** [comment]
I'm not sure, to be honest. Such a large change is ... well, a very large change. Even broken up in to 15 PRs, it is quite significant. I'm not sure who will have the guts to press the merge button :) Something like this and #84122 I can only really imagine happening nicely over time, gradually converging to the "correct" format. I am just one person, though.

**Comment by OmnipotentEntity** [comment]
Fixed 6 conflicts:

5 changed homepage URLs (3 committed as bare URLs)
1 changed description

Fixed 1 newly pushed bare URLs.

**Comment by 7c6f434c** [comment]
Re: who could review this — @Infinisil by comparing with the automated version, I guess. 

Thanks a lot for detailed and frequent reports on merge conflicts. With just the automated tool, we were never sure how much merge churn there is

**Comment by OmnipotentEntity** [comment]
Fixed 7 conflicts:

1 whitespace change in adjacent line
3 files entirely deleted
1 indentation adjustment
2 URLs changed

No new bare URLs were committed today.

**Comment by OmnipotentEntity** [comment]
Fixed 8 conflicts: (Total commit size: 15410 -> 15387)

2 due to updating adjacent metadata
4 changed URLs
2 due to simplified nix expressions on adjacent lines (cleanup)

**Comment by OmnipotentEntity** [comment]
Fixed 3 conflicts (Total commit size 15387 -> 15373)

2 files removed entirely
1 changed URL

**Comment by bhipple** [comment]
If you send a PR with just the `lib/` and `nixos/` subdirs, I can review and merge that; then we're down to just the huge `pkgs/` subdir (which the bot is slowly reducing in scope, at least).

**Comment by Mic92** [comment]
I splitted the diff of aaf2b1e7e5bc9ebf7af2adc853c0c5c0880a0da5 into smaller 10000 lines chunks:

- [ ] [splitai.txt](https://github.com/NixOS/nixpkgs/files/4462345/splitai.txt)
- [ ] [splitah.txt](https://github.com/NixOS/nixpkgs/files/4462346/splitah.txt)
- [ ] [splitag.txt](https://github.com/NixOS/nixpkgs/files/4462347/splitag.txt)
- [ ] [splitaf.txt](https://github.com/NixOS/nixpkgs/files/4462348/splitaf.txt)
- [ ] [splitae.txt](https://github.com/NixOS/nixpkgs/files/4462349/splitae.txt)
- [ ] [splitad.txt](https://github.com/NixOS/nixpkgs/files/4462350/splitad.txt)
- [ ] [splitac.txt](https://github.com/NixOS/nixpkgs/files/4462351/splitac.txt)
- [ ] [splitab.txt](https://github.com/NixOS/nixpkgs/files/4462352/splitab.txt)
- [x] [splitaa.txt](https://github.com/NixOS/nixpkgs/files/4462353/splitaa.txt)

Pick a random one and post if you have reviewed it.

**Comment by Mic92** [comment]
Cherry-picked into 84cf00f98031e93f389f1eb93c4a7374a33cc0a9
I had to fix the merge conflict with doctl.

**Comment by OmnipotentEntity** [comment]
Thanks!

**Comment by grahamc** [comment]
:partying_face:

**Pull request closed without merging**
