### PR TITLE
mercurial: don't propagate frameworks

### PR DESCRIPTION
**Pull request by LnL7**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mickk-on-cpp** [comment]
Could this have introduced the following double quoting in the Mercurial wrapper:

```bash
$ less $(command -v hg)                 
#! /nix/store/65l6hr8snf4v823f974k97jc65i7bhvf-bash-4.4-p12/bin/bash -e
export TK_LIBRARY='"/nix/store/gwzzcr61sk5arbi9vzh2c3pnz4k2z930-tk-8.6.6/lib/tk8.6"'
export HG='"/nix/store/6ji054br1di9iwm4md73gr8p12lvp60y-mercurial-4.3.2/bin/hg"'
export PATH='"/nix/store/gwzzcr61sk5arbi9vzh2c3pnz4k2z930-tk-8.6.6/bin"'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/6ji054br1di9iwm4md73gr8p12lvp60y-mercurial-4.3.2/bin/.hg-wrapped"  "${extraFlagsArray[@]}" "$@"
```

Note the `export HG='"…"'` pattern of double quoting. This makes the variables point at the wrong things—I ran into this because my editor script for committing uses `"$HG"`.

Out of curiosity I ran a search for e.g. `^export\s+\w+='"` (as well as one for `""`) in my store and there’s actually quite a couple of hits. Is there an outstanding issue for this?

**Comment by LnL7** [comment]
No, this only changes `$out/nix-support/propagated-build-inputs`.

**Comment by LnL7** [comment]
@mickk-on-cpp Don't think I've seen extra quoting like this before for wrappers [mercurial/default.nix](https://github.com/LnL7/nixpkgs/blob/b3facac2cd6785a61f2eb30f5f7334ee30ee50e9/pkgs/applications/version-management/mercurial/default.nix#L38-L39). Should be safe to remove if you look at other usages of wrapProgram https://search.nix.gsc.io/?q=wrapProgram.

**Comment by mickk-on-cpp** [comment]
Sorry for the noise, I have opened #33625.

**Comment by LnL7** [comment]
No problem. 😃

**Pull request merged**
