### PR TITLE
Add vim-visual-multi, fix order, update plugins

### PR DESCRIPTION
**Pull request by rvolosatovs**
###### Motivation for this change
Add https://github.com/mg979/vim-visual-multi vim plugin, fix plugin ordering and update the plugins

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
Could you sort the plugins before the update ? otherwise next update's diff will be bigger (I fear).

**Comment by rvolosatovs** [comment]
@teto done, but that did not influence the generated code.

**Comment by teto** [comment]
This is the report from nix-review:
```
Result of `nix-review pr 60202` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>16 package were build:</summary>

  - vimPlugins.nerdtree (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.YouCompleteMe (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.airline (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.ale (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.denite (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.fugitive (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.polyglot (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.rhubarb (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.targets-vim (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-go (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-grepper (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-lsc (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-markdown (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-pandoc (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-puppet (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
  - vimPlugins.vim-visual-multi (vimPlugins.denite-nvim ,vimPlugins.The_NERD_tree ,vimPlugins.vim-airline ,vimPlugins.vim-fugitive ,vimPlugins.vim-polyglot ,vimPlugins.vim-rhubarb ,vimPlugins.youcompleteme)
</details>

```
which looks ok so I want to merge. @Mic92 I wonder about the `error: build log of '/nix/store/wk88ns0zsszylkknfvdv4amj3qnkrdck-vimplugin-vim-fugitive-2019-04-24.drv' is not available` line here. Should I care ?
```
$ git worktree add /home/teto/.cache/nix-review/pr-60202/nixpkgs ee48e784574a823cce58456301b29b988db71ce5
Préparation de l'arbre de travail (HEAD détachée ee48e784574)
Extraction des fichiers: 100% (18930/18930), fait.
HEAD est maintenant à ee48e784574 Merge pull request #60194 from xrelkd/update/tmux
$ nix-env -f /home/teto/.cache/nix-review/pr-60202/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 661384ec605a1bd9441b3242b157d8dc7eb4de1b
La fusion automatique a réussi ; stoppée avant la validation comme demandé
$ nix-env -f /home/teto/.cache/nix-review/pr-60202/nixpkgs -qaP --xml --out-path --show-trace --meta
$ nix build --no-link --keep-going --max-jobs 4 --option build-use-sandbox true -f /home/teto/.cache/nix-review/pr-60202/build.nix
[31 built, 32 copied (1482.3 MiB), 290.9 MiB DL]
https://github.com/NixOS/nixpkgs/pull/60202
16 package were build:
vimPlugins.nerdtree vimPlugins.YouCompleteMe vimPlugins.airline vimPlugins.ale vimPlugins.denite vimPlugins.fugitive vimPlugins.polyglot vimPlugins.rhubarb vimPlugins.targets-vim vimPlugins.vim-go vimPlugins.vim-grepper vimPlugins.vim-lsc vimPlugins.vim-markdown vimPlugins.vim-pandoc vimPlugins.vim-puppet vimPlugins.vim-visual-multi

[0.0 MiB DL]
error: build log of '/nix/store/wk88ns0zsszylkknfvdv4amj3qnkrdck-vimplugin-vim-fugitive-2019-04-24.drv' is not available
$ nix-shell /home/teto/.cache/nix-review/pr-60202/shell.nix

```

**Review by timokau — APPROVED** [review]
Looks like an artifact of `nix-review`. While I'd be interested in the cause, no reason to hold the merge in my opinion. Feel free to merge if you agree @teto

**Comment by teto** [comment]
(always stalking you @timokau :p )

**Comment by timokau** [comment]
Rather the other way around this time, congrats on your commit bit :)

**Pull request merged**
