### PR TITLE
mosquitto: 2.0.11 -> 2.0.12

### PR DESCRIPTION
**Pull request by LeSuisse**
###### Motivation for this change

https://github.com/eclipse/mosquitto/blob/v2.0.12/ChangeLog.txt

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>domoticz</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>mosquitto</li>
  </ul>
</details>

`domoticz` is already broken on master.

### CODE REVIEW

**Comment by risicle** [comment]
Ugh similar problems to last time we bumped, on macos 10.15:

```
[ 91%] Linking C shared module mosquitto_dynamic_security.so
Undefined symbols for architecture x86_64:
  "_mosquitto_broker_publish", referenced from:
      _dynsec_control_callback in plugin.c.o
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in plugin.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in plugin.c.o
  "_mosquitto_calloc", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
  "_mosquitto_client_id", referenced from:
      _dynsec_auth__basic_auth_callback in auth.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_clients__process_delete in clients.c.o
      _dynsec_clients__process_disable in clients.c.o
      _dynsec_clients__process_enable in clients.c.o
      _dynsec_clients__process_set_id in clients.c.o
      _dynsec_clients__process_set_password in clients.c.o
```

**Comment by LeSuisse** [comment]
It was supposed to be fixed in this release that's why I removed the patch https://github.com/eclipse/mosquitto/issues/2277 :cry:

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64.`nixosTests.mosquitto` passes.

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
