### PR TITLE
rubyPackages: Unremove `mail`

### PR DESCRIPTION
**Pull request by Julow**
###### Description of changes

The `mail` gem has been removed in https://github.com/NixOS/nixpkgs/pull/168543 because it was only a dependency of the gem `rails` which has been commented out.

This gem is used by notmuch vim bindings.

The first commit is self-contained but I also added an update commit because I had run the update script. The second commit can be dropped if it is problematic.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
ofborg is complaining.

**Comment by Julow** [comment]
Should be solved by the rebase.

**Review by AndersonTorres — APPROVED** [review]

**Comment by vcunat** [comment]
FYI, `.gpgme` package broke, at least on Hydra: https://hydra.nixos.org/eval/1790698#tabs-now-fail

**Comment by AndersonTorres** [comment]
How? 
ruby-gpgme required pkg-config but this is not in the expression...

**Comment by Julow** [comment]
This is caused by the update commit, reverted in https://github.com/NixOS/nixpkgs/pull/216647

**Pull request merged**
