### PR TITLE
tomcat updates

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
- long overdue version bumps
- drop [unsupported versions](https://en.wikipedia.org/wiki/Apache_Tomcat#Releases) which should have been dropped long ago
- add missing version
- [update maintainers list](https://github.com/NixOS/nixpkgs/pull/84377#discussion_r409917670)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by ecoughlan** [comment]
This also dropped 8.5.x (actually tomcat8 was just 8.5) which is not EOL, and doesn't even have an announced EOL afaik.

**Comment by clhodapp** [comment]
Tomcat 8 isn't end-of-life. Its end of life is in 2024. See https://tomcat.apache.org/tomcat-85-eol.html#:~:text=2022%2D12%2D13%20End%20of,end%20on%2031%20March%202024.

It's likely that the EOL announcement for 8.0 was interpreted to mean that the entire 8.x series was done for but 8.5 is still creaking along strong.

**Comment by aanderse** [comment]
Given how far we lag behind upstream releases, the fact that upstream releases are usually security fixes, and that we have no maintainers I probably should have just removed all versions in this PR.

🤷‍♂️

**Comment by clhodapp** [comment]
Haha fair point.

Perhaps there should be a stronger push for only having things that can be kept up to date through automation in nixpkgs.

**Comment by aanderse** [comment]
Or packages which have dedicated maintainers that regularly maintain their packages. There are people who do this well.

**Pull request merged**
