### PR TITLE
keycloak: 16.1.0 -> 17.0.1 (quarkus)

### PR DESCRIPTION
**Pull request by ngerstle**
###### Description of changes

This updates keycloak from 16.1.0 to 17.0.1, which is a more significant change involving a switch from wildfly to quarkus, necessitating a change in the build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ngerstle** [comment]
@talyz - is a change to the nixos module for keycloak in the same PR acceptable, or should it be split into a different PR?

**Comment by talyz** [comment]
I'm also working on packaging the quarkus version and was planning on making all the changes at once in the same commit. I'm pretty far along in the process - the tests are working. The admin console doesn't yet, though and I'm not sure why yet. Also, a lot of cleanup of the module is still needed, but the core functionality is there.

**Comment by ngerstle** [comment]
The change should enable quite a bit of cleanup- I started working on a
version of the module with the `kc.sh start -h` options in addition to the
nixos specific options.

It was unclear to me from the quarkus upgrade guide whether the existing
plugins will continue to work, I haven't come along far enough to check.

I'm guessing you've made more progress- I'll keep going, but just ping me
for review, I'm eager to see what you're doing.

**Comment by ngerstle** [comment]
closed given https://github.com/NixOS/nixpkgs/pull/166602 & https://github.com/NixOS/nixpkgs/pull/167748 ; https://github.com/NixOS/nixpkgs/pull/167378 with the updated quarkus based keycloak module is ready as well.

**Pull request closed without merging**
