### PR TITLE
nixos/tests: fix switchTest

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes failures like https://hydra.nixos.org/build/168083601/nixlog/102, as well as https://github.com/NixOS/nixpkgs/pull/159187#issuecomment-1051005649

### CODE REVIEW

**Comment by ncfavier** [comment]
@ofborg test switchTest

**Comment by ncfavier** [comment]
Nope, both issues still present.

**Comment by vcunat** [comment]
Well, I'm still getting another problem even with this PR:
```
machine # [   55.922029] nixos[2645]: finished switching to system configuration /nix/store/ach2gr8ss9mxvkjy050qm7q77iqm53a3-nixos-system-machine-22.05.git.35ea9035c1d
(finished: must succeed: /nix/store/nd0g7xz7hwpl011s7kjzx69r1hym6hs4-nixos-system-machine-22.05.git.35ea9035c1d/specialisation/unitWithBackslashModified/bin/switch-to-configuration test 2>&1, in 4.32 seconds)
The haystack that will cause the following exception is:
---
stopping the following units: escaped\x2ddash.service
activating the configuration...
setting up /etc...
setting up tmpfiles
starting the following units: escaped\x2ddash.service
the following new units were started: logrotate.service
---
Test "services" failed with error: "Unexpected string 'the following new units were started:' was found"
cleanup
kill machine (pid 9)
machine # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/bin/python3.9)
(finished: cleanup, in 0.03 seconds)
kill vlan (pid 7)
kill vlan (pid 8)
```

**Comment by ncfavier** [comment]
I only removed the first occurrence of `assert_lacks(out, "the following new units were started:")` because that seemed to make the test succeed on my end, but clearly this is an imperfect workaround. Maybe the easiest is just to disable the logrotate service in the entire test?

**Comment by martinetd** [comment]
It illustrates a real problem with the service (in my opinion), let's fix logrotate :)

The following fixes it for me:
```
diff --git a/nixos/modules/services/logging/logrotate.nix b/nixos/modules/services/logging/logrotate.nix
index 77e4fc395981..082cf92ff4ef 100644
--- a/nixos/modules/services/logging/logrotate.nix
+++ b/nixos/modules/services/logging/logrotate.nix
@@ -167,7 +167,6 @@ in
 
     systemd.services.logrotate = {
       description = "Logrotate Service";
-      wantedBy = [ "multi-user.target" ];
       startAt = "hourly";
 
       serviceConfig = {

```

And logrotate.timer is still enabled,  so the service will run every hour as expected... It can still start randomly during the test, but you won't get the "new units has been started" as it won't be started directly by the switch so I think test won't fail.

I'll submit this as a PR with a new test in nixosTests.logrotate to make sure the timer stays enabled, just need to figure out how to wait for the service to have run automatically after a date change...

**Comment by ncfavier** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/pull/161929

**Pull request closed without merging**
