### PR TITLE
[22.05] Unbreak conan (upgrade pyjwt, conan)

### PR DESCRIPTION
**Pull request by bjornfor**
###### Description of changes
Conan doesn't build anymore on nixos-22.05 due to broken dependencies. This change backports fixes from nixpkgs-unstable to unbreak it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
I ran nixpkgs-review and from what I can tell this PR fixes `conan` and breaks no new packages.

**Review by dotlambda — COMMENTED** [review]
I'd rather not bump pyjwt and instead remove conan's version pin.

**Comment by jonringer** [comment]
As far as i can tell, the pyjwt update should be pretty harmless: https://github.com/jpadilla/pyjwt/releases

I think I would rather see the conan bump in `release-22.05` to unbreak it, and then the pyjwt commits can target staging-22.05

**Review by jonringer — APPROVED** [review]
LGTM

**Comment by bjornfor** [comment]
@jonringer: thanks!

**Comment by vcunat** [comment]
The pyjwt update [isn't liked by homeassistant](https://hydra.nixos.org/build/183293075).  There might be more, though all hopefully trivial to resolve.  /cc e.g. @mweinelt I guess and /cc PR #180752

**Comment by vcunat** [comment]
... and it also caused a [few python packages](https://hydra.nixos.org/eval/1770957?filter=python3&compare=1770478) to miss module `six`, though I have no idea why.

**Comment by mweinelt** [comment]
Backported three commits where we propagated six on master.

**Comment by vcunat** [comment]
These shown here are certainly regressions incoming now to 22.05.

**Comment by mweinelt** [comment]
The way `six` is propagated on `release-22.05` is 
 - flickrapi → requests-oauthlib → pyjwt → ecdsa → six
 - homeconnect → requests-oauthlib → pyjwt → ecdsa → six
 - globus-sdk → pyjwt → ecdsa → six

And sure enough … ecdsa still propagates `six` on `staging-next-22.05`, but it was removed from `pyjwt`, so that broke that chain.

**Comment by jonringer** [comment]
Interesting, not sure why I was able to build so many downstream packages. I just killed the last build because the test suite was going on an hour+.

**Pull request merged**
