### PR TITLE
Fix idris gcc builds on darwin and disable broken package

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/45960

The `lens` package is really weird: It succeeds on linux without problems, but fails on darwin with [an error that indicates a missing standard library constructor](https://hydra.nixos.org/build/80235644/nixlog/1/tail). I therefore marked it as broken on darwin.

The other change this PR has is to use `gccStdenv` to build all idris packages instead of the normal stdenv. This is because of [such errors](https://hydra.nixos.org/build/80313988/nixlog/1/tail), both the clang warnings and the gcc missing error. Since gcc seems to be the standard to use in a Makefile for idris packages, it makes sense to use `gccStdenv` here I think.

This fixes the build for `curses`, `eternal` and `mhd` on darwin

Ping @mpickering @brainrape 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build idrisPackages.curses idrisPackages.eternal idrisPackages.mhd idrisPackages.recursion_schemes idrisPackages.html idrisPackages.config

**Comment by Infinisil** [comment]
The above failure with `idrisPackages.config` seems to disappear from time to time, see also [the hydra job](https://hydra.nixos.org/job/nixpkgs/trunk/idrisPackages.config.x86_64-darwin). I'll investigate this later. I just built it for this PR to show that a couple other idris packages still work.

**Comment by LnL7** [comment]
Usually they build fine with clang, but unlike with Xcode our clang doesn't have `gcc`/`g++` shims. This means builds have to honor the CC/CXX environment variables in order to find the correct compiler instead of hardcoding binary names.

> NOTE in some packages do depend on gcc specific features, for those cases `gccStdenv` can be used.

**Comment by Infinisil** [comment]
Needs a different fix, will open a new PR if I can come up with a nicer one.

**Pull request closed without merging**
