### PR TITLE
icu4c: fix #20954: icu_54_1 package does not compile

### LINKED ISSUE #20954: icu_54_1 package does not compile
## Issue description

The icu_54_1 package fails to compile at the patching step. Some of the patches issue warnings, others fail completely.

### Steps to reproduce

Install icu_54_1: `nix-env -iA nixos.icu_54_1`. The build process will fail.

## Technical details

* System: NixOS: 16.09
* Nix version: 1.11.4
* Nixpkgs version: 16.09.1202.2a97055

### PR DESCRIPTION
**Pull request by savannidgerinel**
###### Motivation for this change

icu4c-54.1 doesn't actually need (and cannot accept) the patches that icu4c-57.1 needs. Instead of fixing it, since we know that icu4c-54.1 is vulnerable and tests show that only zoom-us depends on it and that zoom-us seems to work with icu4c-57.1, we simply remove that older version and make zoom-us depend on the newer one.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Looks good to me. Whether keeping icu54 building is a good idea is another matter (last I looked it's known to be vulnerable). It's only used by the zoom.us client, however, so it doesn't make too much of a difference.

**Comment by savannidgerinel** [comment]
For what it's worth, I was able to run zoom-us with icu-57.1 and could discern no difference in behaviour vs icu-54.1.

**Comment by joachifm** [comment]
Ah, cool, then I suggest removing icu54 instead of fixing it :) If you care to, you could open a second PR, leaving this one open in case somebody disagrees with me.

**Comment by grahamc** [comment]
I'm 👍 on dumping icu_54_1, seeing as it is vulnerable / out of date, and a maintenance burden.

**Comment by savannidgerinel** [comment]
Should I create a different bug for dumping icu_54_1, or keep it in this branch under this particular bug? (Solution for icu_54_1 doesn't build: dump icu_54_1)

**Comment by joachifm** [comment]
In the interest of keeping things simple, let's just go ahead and remove icu54. Generally, if there are alternative solutions, separate PRs would make sense. (Note: it's fine to create PRs without having a corresponding issue).

**Comment by grahamc** [comment]
savannidgerinel <notifications@github.com> writes:

> Should I create a different bug for dumping icu_54_1, or keep it in
> this branch under this particular bug? (Solution for icu_54_1 doesn't
> build: dump icu_54_1)

You can reuse this branch / PR I think, just make sure to squash your
commits in to a single commit.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
