### PR TITLE
gitkraken: Respect NIXOS_OZONE_WL

### PR DESCRIPTION
**Pull request by hacker1024**
## Description of changes

This adds Electron flags to use Wayland to GitKraken when `NIXOS_OZONE_WL` is set, as is done for Chromium and many other electron apps.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by skorpy2009** [comment]
@xNWDD @evanjs @arkivm please have a look

**Comment by skorpy2009** [comment]
Hey @wegank could you please have a look. Thank you!

**Review by wegank — APPROVED** [review]

**Comment by nicolas-goudry** [comment]
@kirillrdy I don’t really understand why this is needed since it’s currently working fine (well, at least for me).

However, the app is also working fine with these changes, so I guess it _should_ be ok.

Are we sure that we need to set these options though? Looking at the [recipe in the source repository](https://github.com/hacker1024/nixpkgs/blob/9b3d2a0c370a0d58e00f186c0b320df917475522/pkgs/applications/version-management/gitkraken/default.nix#L13) for this PR, I can see that the version is quite old (9.5.1 released on June 2023).
My point being that it would be great to know what motivated this change in the first place.

**Comment by hacker1024** [comment]
> Are we sure that we need to set these options though? Looking at the [recipe in the source repository](https://github.com/hacker1024/nixpkgs/blob/9b3d2a0c370a0d58e00f186c0b320df917475522/pkgs/applications/version-management/gitkraken/default.nix#L13) for this PR, I can see that the version is quite old (9.5.1 released on June 2023).
My point being that it would be great to know what motivated this change in the first place.

This change is still relevant - it launches GitKraken using Wayland (instead of XWayland) when the `NIXOS_OZONE_WL` environment variable is set, which is expected of most compatible Electron apps in Nixpkgs.

I have rebased on master.

**Comment by hacker1024** [comment]
> For the purpose of satisfying my curiosity, did you see any performance improvements while running GitKraken with wayland instead of xwayland?

I haven't tried to measure, but there's not much of a difference in my experience.

My main reasons for using Wayland are better support for multi-monitor mixed DPI setups, and NVIDIA, where XWayland can have graphical issues or performance issues working around them.

**Review by nicolas-goudry — APPROVED** [review]

**Pull request merged**
