### PR TITLE
bird-lg: fix proxy service script

### PR DESCRIPTION
**Pull request by Tchekda**
###### Description of changes

There was an error where the last lines of the service script were missing the  `\` and so the script wouldn't start.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yonghan** [comment]
not sure how to submit bug report but the syntax for bird-lg-go should be something like this, according to [xddxdd/bird-lg-go](https://github.com/xddxdd/bird-lg-go#frontend):
`./frontend \
      --servers="Gigs<gigsgigscloud>,Hostdare<hostdare>" \
      --domain=dn42.lantian.pub`

arguments shall be followed by the `=` sign and parameters shall be enclosed in quotation marks `" "`.

The service script has arguments followed by whitespace and parameters are not in quotation marks.

**Comment by Tchekda** [comment]
> not sure how to submit bug report but the syntax for bird-lg-go should be something like this, according to [xddxdd/bird-lg-go](https://github.com/xddxdd/bird-lg-go#frontend): `./frontend \ --servers="Gigs<gigsgigscloud>,Hostdare<hostdare>" \ --domain=dn42.lantian.pub`
> 
> arguments shall be followed by the `=` sign and parameters shall be enclosed in quotation marks `" "`.
> 
> The service script has arguments followed by whitespace and parameters are not in quotation marks.

Will fix that, thx for the report

**Comment by Tchekda** [comment]
@yonghan can you please check because it's still working on my side

**Review by yonghan — APPROVED** [review]
works now. it may work without quotes but quotes are required with ipv6 addresses.

**Comment by e1mo** [comment]
Oh, I've totally overlooked this when doing #226169. Sorry! But with that one merged, I think this can be closed. But thank you anyways for this PR.

**Pull request closed without merging**
