### PR TITLE
tree-sitter: 0.20.8 -> 0.20.9

### PR DESCRIPTION
**Pull request by polarmutex**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
should this go to staging ? I've noticed that past update went to master https://github.com/NixOS/nixpkgs/pull/225148  cc @teto

**Comment by teto** [comment]
It triggers more rebuilds than the previous PR and while these are not the biggest plugins (rebuilds grammars, neovim which in turn triggers plugin rebuilds), if we are not in a hurry it's best to target staging I would say

**Comment by teto** [comment]
@polarmutex would you mind retargeting staging please ? 
neovim 's HEAD bumped the requirement to use this version so I would like to fix neovim's flake:
https://github.com/neovim/neovim/blob/4f788f78f8b2d59a76b1a54a40af0c478eb3f929/cmake.deps/deps.txt#L60

**Comment by willruggiano** [comment]
Is there a reason for not doing `cargoLock.lockFile = "${src}/Cargo.lock";`, rather than copying the entire Cargo.lock file into nixpkgs? Just curious because I typically do that in my personal flakes.

**Comment by kirillrdy** [comment]
> Is there a reason for not doing `cargoLock.lockFile = "${src}/Cargo.lock";`, rather than copying the entire Cargo.lock file into nixpkgs? Just curious because I typically do that in my personal flakes.

`${src}/Cargo.lock` will require `src` derivation to be built, which is not allowed in hydra to speed up evaluation

you can read me https://nixos.org/manual/nix/stable/language/import-from-derivation

**Comment by willruggiano** [comment]
> > Is there a reason for not doing `cargoLock.lockFile = "${src}/Cargo.lock";`, rather than copying the entire Cargo.lock file into nixpkgs? Just curious because I typically do that in my personal flakes.
> 
> `${src}/Cargo.lock` will require `src` derivation to be built, which is not allowed in hydra to speed up evaluation
> 
> you can read more https://nixos.org/manual/nix/stable/language/import-from-derivation

Thanks for the pointer!

**Comment by Kranzes** [comment]
@ofborg eval

**Comment by Kranzes** [comment]
ofborg is failing to eval, anyone able to handle this?
also I don't think targeting master is such a bad idea in this case, this has been blocking neovim nightly for over 2 weeks and I doubt a minor version like this will break much.

**Comment by Kranzes** [comment]
ugh I accidentally merged it into staging after deciding with other people to send it straight to master :expressionless:

**Comment by kirillrdy** [comment]
@Kranzes may I ask who did you talk to ? I just saw this https://github.com/NixOS/nixpkgs/pull/287907

**Comment by Kranzes** [comment]
> @Kranzes may I ask who did you talk to ? I just saw this #287907

I believe @K900 and/or @samueldr

**Comment by Kranzes** [comment]
it's basically impossible to run nixpkgs-review on a PR like this, it just dies/freezes after like 2 hours. So you kinda just have to look at the changed paths in ofborg and decide if any of them are actually critical.

**Comment by polarmutex** [comment]
how ofter does staging get merged into master?

**Comment by kirillrdy** [comment]
this was last merge https://github.com/NixOS/nixpkgs/pull/285983
you can follow links in description to find previous mergers

**Pull request merged**
