### PR TITLE
dnglab: init at 0.5.0

### LINKED ISSUE #193967: Missing Package: DNGLab - A camera RAW to DNG file format converter
**Project description**
DNGLab - A camera RAW to DNG file format converter

Command line tool to convert camera RAW files to Digital Negative Format (DNG).

**Metadata**

* homepage URL: n/a
* source URL: https://github.com/dnglab/dnglab
* license: GNU Lesser General Public License v2.1
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by dit7ya**
###### Description of changes
Resolves #193967.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fee1-dead — APPROVED** [review]

**Comment by fee1-dead** [comment]
Result of `nixpkgs-review pr 194082` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dnglab</li>
  </ul>
</details>

**Comment by xave** [comment]
Certainly. I'm on Darwin. What's the best command to run? The one above tells me "Has to be executed from nixpkgs repository".

**Comment by IvarWithoutBones** [comment]
> Certainly. I'm on aarch64-darwin. What's the best command to run? The one above tells me "Has to be executed from nixpkgs repository".

This should do the trick: `nix run github:dit7ya/nixpkgs/dnglab#dnglab`

**Comment by xave** [comment]
> > Certainly. I'm on aarch64-darwin. What's the best command to run? The one above tells me "Has to be executed from nixpkgs repository".
> 
> This should do the trick: `nix run github:dit7ya/nixpkgs/dnglab#dnglab`

I have a pretty stock nix setup, and don't have the experimental features set. 

```error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override```. 

Note sure what the best way to do this is. The following led to it also asking me to do something with nix flakes.

`nix --extra-experimental-features nix-command run github:dit7ya/nixpkgs/dnglab#dnglab`

**Comment by dit7ya** [comment]
`nix --extra-experimental-features nix-command --extra-experimental-features flakes run github:dit7ya/nixpkgs/dnglab#dnglab` should work in that case @xave.

**Comment by xave** [comment]
> `nix --extra-experimental-features nix-command --extra-experimental-features flakes run github:dit7ya/nixpkgs/dnglab#dnglab` should work in that case @xave.

Just tried it. 

Got `error: hash mismatch in fixed-output derivation '/nix/store/<hash>-source.drv'`

**Comment by xave** [comment]
Is there any update here?

**Review by drupol — APPROVED** [review]

**Pull request merged**
