### PR TITLE
teams: 1.3.00.30857 -> 1.4.00.4855

### PR DESCRIPTION
**Pull request by liff**
###### Motivation for this change

New version is available from [the download site](https://www.microsoft.com/en-us/microsoft-teams/download-app).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by liff** [comment]
The program starts fine and presents the login screen but as I am no longer actively using Teams, that’s as far as I can test.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115979` at 34d58344 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/e7982b8352ce99204103a13aa38046f4">teams</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/networking/instant-messengers/teams/default.nix:45:3:
```
   |
45 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by liff** [comment]
Thanks, Robert :)

**Review by devhell — APPROVED** [review]
LGTM, tested it with my org and works as expected. Thank you! :+1:

**Pull request merged**
