### PR TITLE
ferdi: 5.6.2 -> 5.6.3

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

ChangeLog: https://github.com/getferdi/ferdi/releases/tag/v5.6.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 145569` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ferdi</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Minimal testing seems to look fine.

**Review by thiagokokada — APPROVED** [review]

**Comment by SebTM** [comment]
Since this update, I can't open Ferdi by left clicking the icon in the tray menu and even right click in the menu "Show Ferdi" doesn't show the window. Only calling it with dmenu/rofi or from terminal works to open then window when ferdi is running but in minimized to tray.

Running it from terminal and clicking the tray icon show:
`TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at Object.<anonymous> (/nix/store/8f0h8kmzkmvypmy4fzwdiqg3l5blc3vh-ferdi-5.6.3/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1853)` (Fixed in: https://github.com/getferdi/ferdi/releases/tag/v5.6.4-nightly.7)

Should we update to the nightly, revert the update or wait for 5.6.4? :)

**Comment by thiagokokada** [comment]
> Since this update, I can't open Ferdi by left clicking the icon in the tray menu and even right click in the menu "Show Ferdi" doesn't show the window. Only calling it with dmenu/rofi or from terminal works to open then window when ferdi is running but in minimized to tray.
> 
> Running it from terminal and clicking the tray icon show: `TypeError: Cannot read properties of undefined (reading 'isMinimized') at Object.<anonymous> (/nix/store/8f0h8kmzkmvypmy4fzwdiqg3l5blc3vh-ferdi-5.6.3/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1853)` (Fixed in: https://github.com/getferdi/ferdi/releases/tag/v5.6.4-nightly.7)
> 
> Should we update to the nightly, revert the update or wait for 5.6.4? :)

Looking at the changelog from 5.6.3, I think reverting would be a security issue (there was a Electron upgrade in 5.6.3, also some security changes).

So I would prefer to wait 5.6.4, unless this is really an issue for you. Than I think upgrading to nightly would be better.

**Comment by SebTM** [comment]
Thanks for the fast response, sounds reasonable to not downgrade!

Personally I upgraded to the nightly on my machine through an overlay and could provide a PR for it if wanted - but I'm also fine with waiting for 5.6.4 :) Now it's even documented for others having the issue 👍🏻

**Comment by Ma27** [comment]
OK, it doesn't seem as if there's a reasonable way to "inject" the patch into the binary, so I agree that we should wait for the next release.

**Pull request merged**
