### PR TITLE
kubernetes: patch broken go version check

### LINKED ISSUE #35403: Kubernetes broken
## Issue description
#35330 broke building Kubernetes.

```
Detected go version: go version go1.10 linux/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.
```

`all-packages.nix` probably just needs a `go = go_1_9;`.

Edit: Please do make sure the K8s tests work.

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

fixes #35403
patch from https://github.com/kubernetes/kubernetes/pull/58207
already merged upstream - to be removed for next version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build kubernetes

**Comment by xeji** [comment]
No idea what causes failure on darwin. Unable to investigate.

**Comment by Mic92** [comment]
@GrahamcOfBorg build kubernetes

**Comment by Mic92** [comment]
@GrahamcOfBorg test kubernetes

**Pull request merged**
