### PR TITLE
sit: 0.3.2 -> 0.4.0

### PR DESCRIPTION
**Pull request by yrashk**
###### Motivation for this change

New version

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build sit

**Comment by xeji** [comment]
Darwin failure looks like it is missing `libiconv`, which needs to be explicitly listed as in `buildInputs` for darwin (not for linux, since it's provided by glibc).

**Comment by yrashk** [comment]
@xeji I've added libiconv for Darwin

**Comment by yrashk** [comment]
@xeji I've updated the PR.

**Comment by xeji** [comment]
Thanks! Let's see:
@GrahamcOfBorg build sit

**Comment by yrashk** [comment]
This is a known sporadic error in tests associated with invoking gpg -- at times it seems to not be able to connect to its gpg-agent. I've spent many hours on this but so far found no solution.

**Comment by yrashk** [comment]
If it is not sporadic on this host, it might also be that `gpg` there is GnuPG 1.x and there is no `gpg2`

**Comment by xeji** [comment]
Great, at least it builds now but two test cases fail. Don't think it's worth trying to fix them without access to a Mac, so I suggest to disable tests for darwin.

**Comment by yrashk** [comment]
I do have access to a Mac (it doesn't have Nixpkgs yet, though) -- and v0.4.0 passes tests most of the time. So the only thing I'd try to rule out is to check what's the version of GnuPG installed on that host. Any way to do that?

**Comment by xeji** [comment]
None that I know of. 
Anyway, we could also merge it as is and see what happens on hydra.

**Comment by yrashk** [comment]
We can do that. If it still fails, I can send another PR disabling tests on Darwin for the time being.

**Pull request merged**
