### PR TITLE
[staging] rustc: 1.57.0 -> 1.58.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/154935

1 package built:
ripgrep
```

**Review by zowoq — CHANGES_REQUESTED** [review]
File needs to be renamed to `1_58.nix` and updated in `all-packages.nix` as well. See the changes in https://github.com/NixOS/nixpkgs/pull/148358/files

**Comment by alyssais** [comment]
@OfBorg build firefox fd thunderbird

**Comment by zowoq** [comment]
Pushed the `1_57 -> 1_58` changes, building on darwin.

**Comment by jonringer** [comment]
thanks @zowoq 

Yea, that was my bad

**Comment by jonringer** [comment]
Not really sure why we have `rust_M_N` exposed in all-packages. If anyone were to consume those, they would just break when they get updated.

**Comment by zowoq** [comment]
Sometimes we've needed two or three versions to cover musl or legacy firefox stuff, I don't think removing them once they aren't needed has been as problem.

**Comment by jonringer** [comment]
I'm assuming if you cherry-picked this on master, then darwin would be fine.

Going to merge

**Comment by zowoq** [comment]
> I'm assuming if you cherry-picked this on master, then darwin would be fine.

No, it fails. Sorry if my previous comment was ambiguous.

**Comment by jonringer** [comment]
> > I'm assuming if you cherry-picked this on master, then darwin would be fine.
> 
> No, it fails. Sorry if my previous comment was ambiguous.

No, when I first read it wasn't. When I was hitting merge, I lost that context.

I guess I meant to say, "I assume that if the previous version of rust were able to be built, then this would build as well"

**Pull request merged**
