### PR TITLE
boost159: fix build on aarch64-darwin

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Fix build on aarch64-darwin (related: #136643).

The critical change is adding `#include "output.h"` to `make.c` so that the varargs function `out_printf` is not implicitly defined. I thought it best to backport an upstream fix than to include a local fix.

Requires #159990, so opening as a draft.

Getting a patch into `boost-build` was slightly interesting due to the structure here.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by hjones2199 — APPROVED** [review]

**Comment by vs49688** [comment]
Ping on this? I've just hit it.

**Comment by Artturin** [comment]
> Ping on this? I've just hit it.

Please run `nixpkgs-review pr 160000` and post the result or any build failures

**Comment by hjones2199** [comment]
Result of `nixpkgs-review pr 160000` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>rapcad</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>amarok (amarok-kf5)</li>
    <li>boost159 (boost15x)</li>
    <li>cqrlog</li>
    <li>mysql57</li>
    <li>percona-xtrabackup_2_4</li>
    <li>powerdns</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@hjones2199 can you rerun?

**Comment by vs49688** [comment]
`nixpkgs-review` is still running, but `percona-xtrabackup_2_4` fails with:
```
[ 35%] Building C object storage/heap/CMakeFiles/heap_embedded.dir/hp_clear.c.o
In file included from /build/source/storage/innobase/include/ha_prototypes.h:32,
                 from /build/source/storage/innobase/api/api0api.cc:27:
/build/source/storage/innobase/include/univ.i:416:33: error: unnamed scoped enum is not allowed
  416 | #define byte                    unsigned char
      |                                 ^~~~~~~~
/build/source/storage/innobase/include/univ.i:416:33: error: expected identifier before 'unsigned'
In file included from /nix/store/1wbkdhc44n09f6mhdw7y0d8dlkck29m9-gcc-11.2.0/include/c++/11.2.0/pstl/glue_algorithm_defs.h:13,
                 from /nix/store/1wbkdhc44n09f6mhdw7y0d8dlkck29m9-gcc-11.2.0/include/c++/11.2.0/algorithm:74,
                 from /build/source/storage/innobase/include/ut0ut.ic:26,
                 from /build/source/storage/innobase/include/ut0ut.h:626,
                 from /build/source/storage/innobase/include/univ.i:589,
                 from /build/source/storage/innobase/include/ha_prototypes.h:32,
                 from /build/source/storage/innobase/api/api0api.cc:27:
/nix/store/1wbkdhc44n09f6mhdw7y0d8dlkck29m9-gcc-11.2.0/include/c++/11.2.0/functional:979:19: error: expected unqualified-id before ':' token
  979 |   enum class byte : unsigned char;
      |                   ^
[ 35%] Building CXX object storage/myisam/CMakeFiles/myisam_embedded.dir/ha_myisam.cc.o
[ 35%] Building C object storage/heap/CMakeFiles/heap.dir/hp_close.c.o
[ 35%] Building C object storage/heap/CMakeFiles/heap_embedded.dir/hp_close.c.o
In file included from /build/source/storage/innobase/include/ha_prototypes.h:32,
                 from /build/source/storage/innobase/api/api0misc.cc:27:
/build/source/storage/innobase/include/univ.i:416:33: error: unnamed scoped enum is not allowed
  416 | #define byte                    unsigned char
      |                                 ^~~~~~~~
/build/source/storage/innobase/include/univ.i:416:33: error: expected identifier before 'unsigned'
In file included from /nix/store/1wbkdhc44n09f6mhdw7y0d8dlkck29m9-gcc-11.2.0/include/c++/11.2.0/pstl/glue_algorithm_defs.h:13,
                 from /nix/store/1wbkdhc44n09f6mhdw7y0d8dlkck29m9-gcc-11.2.0/include/c++/11.2.0/algorithm:74,
                 from /build/source/storage/innobase/include/ut0ut.ic:26,
                 from /build/source/storage/innobase/include/ut0ut.h:626,
                 from /build/source/storage/innobase/include/univ.i:589,
                 from /build/source/storage/innobase/include/ha_prototypes.h:32,
                 from /build/source/storage/innobase/api/api0misc.cc:27:
/nix/store/1wbkdhc44n09f6mhdw7y0d8dlkck29m9-gcc-11.2.0/include/c++/11.2.0/functional:979:19: error: expected unqualified-id before ':' token
  979 |   enum class byte : unsigned char;
      |                   ^
```

**Comment by vs49688** [comment]
Result of `nixpkgs-review pr 160000` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-documents</li>
    <li>rapcad</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>percona-xtrabackup_2_4</li>
  </ul>
</details>
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>amarok (amarok-kf5)</li>
    <li>boost159 (boost15x)</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.nemo</li>
    <li>cqrlog</li>
    <li>dropbox-cli</li>
    <li>eiciel</li>
    <li>exempi</li>
    <li>gnome-console</li>
    <li>gnome-photos</li>
    <li>gnome.eog</li>
    <li>gnome.file-roller (pantheon.file-roller)</li>
    <li>gnome.gnome-books</li>
    <li>gnome.gnome-boxes</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-user-share</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>img2pdf (python39Packages.img2pdf)</li>
    <li>mate.atril</li>
    <li>mate.caja</li>
    <li>mate.caja-dropbox</li>
    <li>mate.caja-extensions</li>
    <li>mate.caja-with-extensions</li>
    <li>mate.engrampa</li>
    <li>mate.eom</li>
    <li>mate.mate-control-center</li>
    <li>mate.mate-settings-daemon-wrapped</li>
    <li>mate.mate-user-share</li>
    <li>mate.python-caja</li>
    <li>mysql57</li>
    <li>nautilus-open-any-terminal</li>
    <li>ocrmypdf (python39Packages.ocrmypdf)</li>
    <li>pantheon.file-roller-contract</li>
    <li>paperless-ngx</li>
    <li>pdfarranger</li>
    <li>phosh</li>
    <li>python310Packages.img2pdf</li>
    <li>python310Packages.ocrmypdf</li>
    <li>python310Packages.pikepdf</li>
    <li>python310Packages.python-xmp-toolkit</li>
    <li>python39Packages.pikepdf</li>
    <li>python39Packages.python-xmp-toolkit</li>
    <li>tellico</li>
    <li>tracker-miners</li>
  </ul>
</details>

**Comment by Artturin** [comment]
That's  preexisting failure

Ofborg built boost159 on darwin and it worked so ready to merge

**Pull request merged**
