### PR TITLE
Add ngx_pagespeed support to nginx

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by ocharles** [comment]
CC @thoughtpolice @raskin

**Comment by joachifm** [comment]
cc @7c6f434c

**Comment by joachifm** [comment]
This looks abandoned. Close it?

**Comment by garbas** [comment]
@ocharles ping

**Comment by domenkozar** [comment]
`nginx` nixos module changed since dramatically, modules can now be specified as an input. @ocharles are you still interested getting this done?

**Comment by ocharles** [comment]
I am no longer working with this module, so this could be closed. I
probably won't have time to work on this any time soon

**Pull request closed without merging**
