### PR TITLE
armcord: 3.2.5 -> 3.2.6

### LINKED ISSUE #284609: Update request: armcord 3.2.5 → 3.2.6
- Package name: Armcord
- Latest released version: 3.2.6

- Current version on the unstable channel: 3.2.5
- Current version on the stable/release channel: 3.2.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wrmilling 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by juni-purr**
## Description of changes

https://github.com/ArmCord/ArmCord/releases/tag/v3.2.6

Related Issue: https://github.com/NixOS/nixpkgs/issues/284609

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wrmilling** [comment]
Thanks for submitting a PR @kenos1, be sure to collapse it to a single commit for the whole update so it can be merged properly.

**Comment by kenos1** [comment]
Oh whoops, how do I do that?

**Comment by wrmilling** [comment]
Easiest way would be to probably just reset the commits, commit the changes again, and force-push to your branch.

**Comment by kenos1** [comment]
Git push failed

**Review by wrmilling — APPROVED** [review]
Everything looks good once the commits get collapsed.

**Comment by mfrw** [comment]
Result of `nixpkgs-review pr 284669` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>armcord</li>
  </ul>
</details>

**Comment by nyabinary** [comment]
Shouldn't we switch this to use ``makeBinaryWrapper`` instead of ``makeWrapper``?

**Comment by wrmilling** [comment]
> Shouldn't we switch this to use `makeBinaryWrapper` instead of `makeWrapper`?

Spun up a separate PR to keep this one clean to the version upgrade.

**Review by wrmilling — APPROVED** [review]

**Comment by kenos1** [comment]
Ok I think the commits are squashes, should be good to go

**Comment by D3vil0p3r** [comment]
Why checks are failing by:
```
gh: API rate limit exceeded for installation ID 5210592. If you reach out to GitHub Support for help, please include the request ID 9081:746C:2867FF2:5379F5F:65B75622. (HTTP 403)
```

**Review by drupol — APPROVED** [review]

**Pull request merged**
