### PR TITLE
pynitrokey: unpin cryptography, nitrokey-app2: 2.1.5 -> 2.2.2, fix qt somewhat

### PR DESCRIPTION
**Pull request by 999eagle**
## Description of changes

This removes the `meta.broken` attribute from `python3Packages.spsdk` as the update to 2.1.1 enabled using cryptography 42 (see https://github.com/nxp-mcuxpresso/spsdk/blob/2.1.1/requirements.txt#L10) to allow unpinning the `cryptography` dependency in `pynitrokey` and `nitrokey-app2`.
`nitrokey-app2` is also correctly wrapped with the `wrapQtAppsHook` for qt6 and updated to 2.2.2, superseding #287238.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC @panicgh @dotlambda @RaitoBezarius 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by panicgh — COMMENTED** [review]
Result of `nixpkgs-review pr 304110` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>nitrokey-app2</li>
    <li>nitrokey-app2.dist</li>
    <li>pynitrokey</li>
    <li>pynitrokey.dist</li>
  </ul>
</details>

Changes in principle look ok to me, although it seems some GUI elements (buttons?) in the left panel are not displayed. But in principle the application runs and I can access NK3 features.

The first commit's subject line is a bit long. Not sure if that's relevant.

**Comment by 999eagle** [comment]
Wasn't entirely sure whether I should split the first commit into multiple but decided against it as that would've split changes that don't make sense on their own.
Yeah the UI still looks a bit weird but that seems to happen upstream as well. Not entirely sure what (if anything) to do here.

**Review by panicgh — COMMENTED** [review]
There seems to be a problem with spsdk:

```console
$ ./results/pynitrokey/bin/nitropy list
Command line tool to interact with Nitrokey devices 0.4.45
:: 'Nitrokey FIDO2' keys
:: 'Nitrokey Start' keys:
:: 'Nitrokey 3' keys
Critical error:
An unhandled exception occurred
	Exception encountered: ImportError("cannot import name 'StatusCode' from 'spsdk.mboot' (/nix/store/6wjgwmr7qbkppxiy89d5v6hw97dj1f4b-python3.11-spsdk-2.1.1/lib/python3.11/site-packages/spsdk/mboot/__init__.py)")
```

`StatusCode` is defined in spsdk/mboot/error_codes.py so I'm not sure what the problem is.

**Comment by 999eagle** [comment]
huh, that error doesn't occur when building `pynitrokey` directly from the pr. it seems like something on `nixos-unstable` has changed since creating the pr. i'm looking into it

**Comment by 999eagle** [comment]
hm. i have no idea where exactly this problem is coming from. i've tried building `pynitrokey` from this pr branch, from this branch rebased onto `nixos-stable` and from this branch merged into `master`. none of those throws the error you mentioned. running `nixpkgs-review` on any of those three commits does throw the error though despite building the exact same store paths... even running this with `env -i result/bin/nitropy list' works. i think this is some kind of issue with the environment in the review shell `nixpkgs-review` builds.

**Review by panicgh — APPROVED** [review]
Result of `nixpkgs-review pr 304110` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>nitrokey-app2</li>
    <li>nitrokey-app2.dist</li>
    <li>pynitrokey</li>
    <li>pynitrokey.dist</li>
  </ul>
</details>

I confirm the error I reported above appears only when executing nitropy from within the nixpkgs-review shell. When running the store path directly in another shell, everything seems to work correctly.

```console
$ /nix/store/r8w82sdlhldlwvwqvv1fk03fk8q8b0vk-python3.11-pynitrokey-0.4.47/bin/nitropy list
Command line tool to interact with Nitrokey devices 0.4.47
:: 'Nitrokey FIDO2' keys
:: 'Nitrokey Start' keys:
:: 'Nitrokey 3' keys
/dev/hidraw3: Nitrokey 3 XXXX
:: 'Nitrokey Passkey' keys
```

**Pull request merged**
