### PR TITLE
android-studio-full: init

### PR DESCRIPTION
**Pull request by numinit**
## Description of changes

Create the following APIs that bridge the gap between Android Studio and androidenv:

- `androidStudioPackages.<flavor>.withSdk`: Wraps Android Studio in an Android SDK created with androidenv. Exports ANDROID_SDK_ROOT and ANDROID_NDK_ROOT to the environment of the Android Studio process, if detected. This makes new projects default to the androidenv composition instead of needing to download SDKs separately, which causes emulators to break with dynamic linker errors when users try to run Android Studio out of the box on nixpkgs. Since androidenv already solves this problem, this improves the out of the box experience with Android Studio in nixpkgs.
- `androidStudioPackages.<flavor>.full`: Wraps Android Studio in a default "full" SDK composition
- `android-studio-full`: Alias for android-studio.full

Remove the following old androidenv composition:

- `androidenv.androidPkgs_9_0`

Add the following new androidenv composition:

- `androidenv.androidPkgs`

We should probably discuss this API change since it downloads a ton of Android system images, but is a way to have a relatively "full" version of androidPkgs.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by numinit** [comment]
cc: @hadilq @jakubgs

**Comment by hadilq** [comment]
It looks awesome. Thanks

**Review by crertel — APPROVED** [review]

**Comment by alapshin** [comment]
Agree, this looks great. Looking forward to getting it merged

**Review by alapshin — APPROVED** [review]

**Review by alapshin — APPROVED** [review]

**Review by JohnRTitor — APPROVED** [review]

**Review by alapshin — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
Good stuff.

**Comment by numinit** [comment]
A user on the Discord had a problem running the emulator from Android Studio, and it required the unnecessarily complicated solution of instantiating androidenv separately and writing out the local.properties with sdk.dir set. It was so close that I realized we could just wrap it and get the best of both worlds.

**Comment by numinit** [comment]
Only thing I'm not sure about is the changelog, which may require a manual merge.

**Comment by numinit** [comment]
Changelog fixed in https://github.com/NixOS/nixpkgs/pull/320194

**Pull request merged**
