### PR TITLE
firefox{,-bin}: 80.0 -> 80.0.2

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

Update to the latest version of Firefox that was released a few days ago.

- firefox: 82.0 -> 82.0.2
- firefox-bin: 82.0 -> 82.0.2

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested execution of all binary files (usually in `./result/bin/`)

### CODE REVIEW

**Comment by stigtsp** [comment]
Tested `firefox-bin` OK  on `linux x64`

`firefox` fails to build:

<details>

```
/nix/store/8madhhcxhxlf0rrc5hdsk65l206r3cc6-gcc-wrapper-9.3.0/bin/g++ -std=gnu++17 -o Unified_cpp_gfx_layers9.o -c  -I/build/firefox-82.0.2/obj-x86_64-pc-li
nux-gnu/dist/stl_wrappers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/system_wrappers -include /build/firefox-82.0.2/config/gcc_hidden.h -U_FORTIFY_S
OURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -DNDEBUG=1 -DTRIMMED=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DMOZ_APP_VERSION=
82.0.2 -DOS_POSIX=1 -DOS_LINUX=1 -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API -I/build/firefox-82.0.2/gfx/layers -I/build
/firefox-82.0.2/obj-x86_64-pc-linux-gnu/gfx/layers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/ipc/ipdl/_ipdlheaders -I/build/firefox-82.0.2/ipc/chromium/
src -I/build/firefox-82.0.2/ipc/glue -I/build/firefox-82.0.2/docshell/base -I/build/firefox-82.0.2/dom/canvas -I/build/firefox-82.0.2/layout/base -I/build/fir
efox-82.0.2/layout/generic -I/build/firefox-82.0.2/media/libyuv/libyuv/include -I/build/firefox-82.0.2/gfx/skia -I/build/firefox-82.0.2/gfx/skia/skia -I/build
/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include -I/nix/store/jkc8kzi039id5591i9bkhlhp7x15ks2r-nspr-4.29-dev/include -I/nix/store/jkc8kzi039id5591i9bkhlhp
7x15ks2r-nspr-4.29-dev/include -I/nix/store/nb0pk3mfhrap9j4c3fq6nw8kg54pcsr3-nss-3.57-dev/include/nss -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/inc
lude/nss -I/nix/store/jnvzc9ppm1l030mwlramvwisk8svzn9r-zlib-1.2.11-dev/include -I/nix/store/g7zc6b8ng77dllwawins0c2fj5r3272f-pixman-0.38.4/include/pixman-1 -I
/nix/store/7flw8mxs28mk2r1wsnyas1y59j4hjr7a-icu4c-67.1-dev/include -fPIC -DMOZILLA_CLIENT -include /build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/mozilla-confi
g.h -Wall -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wno-invalid-
offsetof -Wduplicated-cond -Wimplicit-fallthrough -Wunused-function -Wunused-variable -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-e
rror=array-bounds -Wno-error=coverage-mismatch -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wno-error=deprecated-copy
 -Wformat -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fno-strict-aliasing -
fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -g -freorder-blocks -O2 -fomit-frame-pointer -funwind-tables -I/bu
ild/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include/cairo -I/build/firefox-82.0.2/widget/gtk/compat-gtk3 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-gli
b-2.64.5-dev/include/gio-unix-2.0 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.64.5-dev/include -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.6
4.5-dev/include/glib-2.0 -I/nix/store/g8qsms0ibvg7cr568jd31ywkgq045vpk-glib-2.64.5/lib/glib-2.0/include -I/nix/store/fn6sjqf47cgalkxgp7dmqi5grp9ifqdm-cairo-1.
16.0-dev/include/cairo -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freet
ype-2.10.2-dev/include -I/nix/store/vx1fsm40kcn7f08rdm5v4cbwm3p5wnlp-pango-1.45.3-dev/include/pango-1.0 -I/nix/store/p8h9gdyifn6fmfd9sv0sgns39dhnkwv3-harfbuzz
-2.7.1-dev/include/harfbuzz -I/nix/store/0dmmvxhqjzg5jlpxqz4qanv2chvdjhlz-gdk-pixbuf-2.40.0-dev/include/gdk-pixbuf-2.0 -I/nix/store/00qqdfygrb886c41lmxxhs04bq
pfp3hp-atk-2.36.0-dev/include/atk-1.0 -I/nix/store/94h5izg9s8g71l3m4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0/unix-print -I/nix/store/94h5izg9s8g71l3m
4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0 -Wno-error=shadow -Wno-maybe-uninitialized  -MD -MP -MF .deps/Unified_cpp_gfx_layers9.o.pp   Unified_cpp_gf
x_layers9.cpp                                                                                                                                                 
  /nix/store/8madhhcxhxlf0rrc5hdsk65l206r3cc6-gcc-wrapper-9.3.0/bin/g++ -std=gnu++17 -o Unified_cpp_gfx_layers8.o -c  -I/build/firefox-82.0.2/obj-x86_64-pc-li
nux-gnu/dist/stl_wrappers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/system_wrappers -include /build/firefox-82.0.2/config/gcc_hidden.h -U_FORTIFY_S
OURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -DNDEBUG=1 -DTRIMMED=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DMOZ_APP_VERSION=
82.0.2 -DOS_POSIX=1 -DOS_LINUX=1 -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API -I/build/firefox-82.0.2/gfx/layers -I/build
/firefox-82.0.2/obj-x86_64-pc-linux-gnu/gfx/layers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/ipc/ipdl/_ipdlheaders -I/build/firefox-82.0.2/ipc/chromium/
src -I/build/firefox-82.0.2/ipc/glue -I/build/firefox-82.0.2/docshell/base -I/build/firefox-82.0.2/dom/canvas -I/build/firefox-82.0.2/layout/base -I/build/fir
efox-82.0.2/layout/generic -I/build/firefox-82.0.2/media/libyuv/libyuv/include -I/build/firefox-82.0.2/gfx/skia -I/build/firefox-82.0.2/gfx/skia/skia -I/build
/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include -I/nix/store/jkc8kzi039id5591i9bkhlhp7x15ks2r-nspr-4.29-dev/include -I/nix/store/jkc8kzi039id5591i9bkhlhp
7x15ks2r-nspr-4.29-dev/include -I/nix/store/nb0pk3mfhrap9j4c3fq6nw8kg54pcsr3-nss-3.57-dev/include/nss -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/inc
lude/nss -I/nix/store/jnvzc9ppm1l030mwlramvwisk8svzn9r-zlib-1.2.11-dev/include -I/nix/store/g7zc6b8ng77dllwawins0c2fj5r3272f-pixman-0.38.4/include/pixman-1 -I
/nix/store/7flw8mxs28mk2r1wsnyas1y59j4hjr7a-icu4c-67.1-dev/include -fPIC -DMOZILLA_CLIENT -include /build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/mozilla-confi
g.h -Wall -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wno-invalid-
offsetof -Wduplicated-cond -Wimplicit-fallthrough -Wunused-function -Wunused-variable -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-e
rror=array-bounds -Wno-error=coverage-mismatch -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wno-error=deprecated-copy
 -Wformat -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fno-strict-aliasing -
fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -g -freorder-blocks -O2 -fomit-frame-pointer -funwind-tables -I/bu
ild/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include/cairo -I/build/firefox-82.0.2/widget/gtk/compat-gtk3 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-gli
b-2.64.5-dev/include/gio-unix-2.0 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.64.5-dev/include -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.6
4.5-dev/include/glib-2.0 -I/nix/store/g8qsms0ibvg7cr568jd31ywkgq045vpk-glib-2.64.5/lib/glib-2.0/include -I/nix/store/fn6sjqf47cgalkxgp7dmqi5grp9ifqdm-cairo-1.
16.0-dev/include/cairo -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freet
ype-2.10.2-dev/include -I/nix/store/vx1fsm40kcn7f08rdm5v4cbwm3p5wnlp-pango-1.45.3-dev/include/pango-1.0 -I/nix/store/p8h9gdyifn6fmfd9sv0sgns39dhnkwv3-harfbuzz
-2.7.1-dev/include/harfbuzz -I/nix/store/0dmmvxhqjzg5jlpxqz4qanv2chvdjhlz-gdk-pixbuf-2.40.0-dev/include/gdk-pixbuf-2.0 -I/nix/store/00qqdfygrb886c41lmxxhs04bq
pfp3hp-atk-2.36.0-dev/include/atk-1.0 -I/nix/store/94h5izg9s8g71l3m4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0/unix-print -I/nix/store/94h5izg9s8g71l3m
4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0 -Wno-error=shadow -Wno-maybe-uninitialized  -MD -MP -MF .deps/Unified_cpp_gfx_layers8.o.pp   Unified_cpp_gf
x_layers8.cpp                                                                                                                                                 
  cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++                                                          
  cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++
  make[3]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/gfx/layers'                                                                       
  make[2]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu'                                                                                  
  make[1]: *** [/build/firefox-82.0.2/config/recurse.mk:34: compile] Error 2                                                                                  
  make[1]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu'                                                                                  
  make: *** [/build/firefox-82.0.2/config/rules.mk:384: default] Error 2                                                                                      
cannot build derivation '/nix/store/ck3p30vx7h9p9clck7mriv8z6bn5g8l4-adoptopenjdk-icedtea-web-1.8.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8cjs439dw4ndgyd03r520462gvni0m5k-firefox-82.0.2.drv': 1 dependencies couldn't be built                                    
cannot build derivation '/nix/store/al4f3hfj8hh7f4jfdx0i52q1w7d3msm1-slimerjs-1.0.0.drv': 1 dependencies couldn't be built                                    
cannot build derivation '/nix/store/zyziz8k38x6fbz0g8lcfhaxhzdvapwa9-env.drv': 3 dependencies couldn't be built

```
</details>

**Comment by andir** [comment]
> Tested `firefox-bin` OK on `linux x64`
> 
> `firefox` fails to build:
> 
> ```
> /nix/store/8madhhcxhxlf0rrc5hdsk65l206r3cc6-gcc-wrapper-9.3.0/bin/g++ -std=gnu++17 -o Unified_cpp_gfx_layers9.o -c  -I/build/firefox-82.0.2/obj-x86_64-pc-li
> nux-gnu/dist/stl_wrappers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/system_wrappers -include /build/firefox-82.0.2/config/gcc_hidden.h -U_FORTIFY_S
> OURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -DNDEBUG=1 -DTRIMMED=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DMOZ_APP_VERSION=
> 82.0.2 -DOS_POSIX=1 -DOS_LINUX=1 -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API -I/build/firefox-82.0.2/gfx/layers -I/build
> /firefox-82.0.2/obj-x86_64-pc-linux-gnu/gfx/layers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/ipc/ipdl/_ipdlheaders -I/build/firefox-82.0.2/ipc/chromium/
> src -I/build/firefox-82.0.2/ipc/glue -I/build/firefox-82.0.2/docshell/base -I/build/firefox-82.0.2/dom/canvas -I/build/firefox-82.0.2/layout/base -I/build/fir
> efox-82.0.2/layout/generic -I/build/firefox-82.0.2/media/libyuv/libyuv/include -I/build/firefox-82.0.2/gfx/skia -I/build/firefox-82.0.2/gfx/skia/skia -I/build
> /firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include -I/nix/store/jkc8kzi039id5591i9bkhlhp7x15ks2r-nspr-4.29-dev/include -I/nix/store/jkc8kzi039id5591i9bkhlhp
> 7x15ks2r-nspr-4.29-dev/include -I/nix/store/nb0pk3mfhrap9j4c3fq6nw8kg54pcsr3-nss-3.57-dev/include/nss -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/inc
> lude/nss -I/nix/store/jnvzc9ppm1l030mwlramvwisk8svzn9r-zlib-1.2.11-dev/include -I/nix/store/g7zc6b8ng77dllwawins0c2fj5r3272f-pixman-0.38.4/include/pixman-1 -I
> /nix/store/7flw8mxs28mk2r1wsnyas1y59j4hjr7a-icu4c-67.1-dev/include -fPIC -DMOZILLA_CLIENT -include /build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/mozilla-confi
> g.h -Wall -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wno-invalid-
> offsetof -Wduplicated-cond -Wimplicit-fallthrough -Wunused-function -Wunused-variable -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-e
> rror=array-bounds -Wno-error=coverage-mismatch -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wno-error=deprecated-copy
>  -Wformat -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fno-strict-aliasing -
> fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -g -freorder-blocks -O2 -fomit-frame-pointer -funwind-tables -I/bu
> ild/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include/cairo -I/build/firefox-82.0.2/widget/gtk/compat-gtk3 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-gli
> b-2.64.5-dev/include/gio-unix-2.0 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.64.5-dev/include -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.6
> 4.5-dev/include/glib-2.0 -I/nix/store/g8qsms0ibvg7cr568jd31ywkgq045vpk-glib-2.64.5/lib/glib-2.0/include -I/nix/store/fn6sjqf47cgalkxgp7dmqi5grp9ifqdm-cairo-1.
> 16.0-dev/include/cairo -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freet
> ype-2.10.2-dev/include -I/nix/store/vx1fsm40kcn7f08rdm5v4cbwm3p5wnlp-pango-1.45.3-dev/include/pango-1.0 -I/nix/store/p8h9gdyifn6fmfd9sv0sgns39dhnkwv3-harfbuzz
> -2.7.1-dev/include/harfbuzz -I/nix/store/0dmmvxhqjzg5jlpxqz4qanv2chvdjhlz-gdk-pixbuf-2.40.0-dev/include/gdk-pixbuf-2.0 -I/nix/store/00qqdfygrb886c41lmxxhs04bq
> pfp3hp-atk-2.36.0-dev/include/atk-1.0 -I/nix/store/94h5izg9s8g71l3m4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0/unix-print -I/nix/store/94h5izg9s8g71l3m
> 4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0 -Wno-error=shadow -Wno-maybe-uninitialized  -MD -MP -MF .deps/Unified_cpp_gfx_layers9.o.pp   Unified_cpp_gf
> x_layers9.cpp                                                                                                                                                 
>   /nix/store/8madhhcxhxlf0rrc5hdsk65l206r3cc6-gcc-wrapper-9.3.0/bin/g++ -std=gnu++17 -o Unified_cpp_gfx_layers8.o -c  -I/build/firefox-82.0.2/obj-x86_64-pc-li
> nux-gnu/dist/stl_wrappers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/system_wrappers -include /build/firefox-82.0.2/config/gcc_hidden.h -U_FORTIFY_S
> OURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -DNDEBUG=1 -DTRIMMED=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DMOZ_APP_VERSION=
> 82.0.2 -DOS_POSIX=1 -DOS_LINUX=1 -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API -I/build/firefox-82.0.2/gfx/layers -I/build
> /firefox-82.0.2/obj-x86_64-pc-linux-gnu/gfx/layers -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/ipc/ipdl/_ipdlheaders -I/build/firefox-82.0.2/ipc/chromium/
> src -I/build/firefox-82.0.2/ipc/glue -I/build/firefox-82.0.2/docshell/base -I/build/firefox-82.0.2/dom/canvas -I/build/firefox-82.0.2/layout/base -I/build/fir
> efox-82.0.2/layout/generic -I/build/firefox-82.0.2/media/libyuv/libyuv/include -I/build/firefox-82.0.2/gfx/skia -I/build/firefox-82.0.2/gfx/skia/skia -I/build
> /firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include -I/nix/store/jkc8kzi039id5591i9bkhlhp7x15ks2r-nspr-4.29-dev/include -I/nix/store/jkc8kzi039id5591i9bkhlhp
> 7x15ks2r-nspr-4.29-dev/include -I/nix/store/nb0pk3mfhrap9j4c3fq6nw8kg54pcsr3-nss-3.57-dev/include/nss -I/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/inc
> lude/nss -I/nix/store/jnvzc9ppm1l030mwlramvwisk8svzn9r-zlib-1.2.11-dev/include -I/nix/store/g7zc6b8ng77dllwawins0c2fj5r3272f-pixman-0.38.4/include/pixman-1 -I
> /nix/store/7flw8mxs28mk2r1wsnyas1y59j4hjr7a-icu4c-67.1-dev/include -fPIC -DMOZILLA_CLIENT -include /build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/mozilla-confi
> g.h -Wall -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wno-invalid-
> offsetof -Wduplicated-cond -Wimplicit-fallthrough -Wunused-function -Wunused-variable -Wno-error=maybe-uninitialized -Wno-error=deprecated-declarations -Wno-e
> rror=array-bounds -Wno-error=coverage-mismatch -Wno-error=free-nonheap-object -Wno-multistatement-macros -Wno-error=class-memaccess -Wno-error=deprecated-copy
>  -Wformat -Wformat-overflow=2 -Werror=implicit-function-declaration -Wno-psabi -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fno-strict-aliasing -
> fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -g -freorder-blocks -O2 -fomit-frame-pointer -funwind-tables -I/bu
> ild/firefox-82.0.2/obj-x86_64-pc-linux-gnu/dist/include/cairo -I/build/firefox-82.0.2/widget/gtk/compat-gtk3 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-gli
> b-2.64.5-dev/include/gio-unix-2.0 -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.64.5-dev/include -I/nix/store/3dzipf2c0flsvm6kvwzzdifpxv5258km-glib-2.6
> 4.5-dev/include/glib-2.0 -I/nix/store/g8qsms0ibvg7cr568jd31ywkgq045vpk-glib-2.64.5/lib/glib-2.0/include -I/nix/store/fn6sjqf47cgalkxgp7dmqi5grp9ifqdm-cairo-1.
> 16.0-dev/include/cairo -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/fwpg7xp5ka281nz4fqvyl8vl88gm1i8k-freet
> ype-2.10.2-dev/include -I/nix/store/vx1fsm40kcn7f08rdm5v4cbwm3p5wnlp-pango-1.45.3-dev/include/pango-1.0 -I/nix/store/p8h9gdyifn6fmfd9sv0sgns39dhnkwv3-harfbuzz
> -2.7.1-dev/include/harfbuzz -I/nix/store/0dmmvxhqjzg5jlpxqz4qanv2chvdjhlz-gdk-pixbuf-2.40.0-dev/include/gdk-pixbuf-2.0 -I/nix/store/00qqdfygrb886c41lmxxhs04bq
> pfp3hp-atk-2.36.0-dev/include/atk-1.0 -I/nix/store/94h5izg9s8g71l3m4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0/unix-print -I/nix/store/94h5izg9s8g71l3m
> 4gdfb4vsifa5320a-gtk+3-3.24.21-dev/include/gtk-3.0 -Wno-error=shadow -Wno-maybe-uninitialized  -MD -MP -MF .deps/Unified_cpp_gfx_layers8.o.pp   Unified_cpp_gf
> x_layers8.cpp                                                                                                                                                 
>   cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++                                                          
>   cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++
>   make[3]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu/gfx/layers'                                                                       
>   make[2]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu'                                                                                  
>   make[1]: *** [/build/firefox-82.0.2/config/recurse.mk:34: compile] Error 2                                                                                  
>   make[1]: Leaving directory '/build/firefox-82.0.2/obj-x86_64-pc-linux-gnu'                                                                                  
>   make: *** [/build/firefox-82.0.2/config/rules.mk:384: default] Error 2                                                                                      
> cannot build derivation '/nix/store/ck3p30vx7h9p9clck7mriv8z6bn5g8l4-adoptopenjdk-icedtea-web-1.8.4.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/8cjs439dw4ndgyd03r520462gvni0m5k-firefox-82.0.2.drv': 1 dependencies couldn't be built                                    
> cannot build derivation '/nix/store/al4f3hfj8hh7f4jfdx0i52q1w7d3msm1-slimerjs-1.0.0.drv': 1 dependencies couldn't be built                                    
> cannot build derivation '/nix/store/zyziz8k38x6fbz0g8lcfhaxhzdvapwa9-env.drv': 3 dependencies couldn't be built
> ```

Please provide more build log. The given example isn't really sufficient to judge why it failed on your machine.

**Comment by andir** [comment]
@GrahamcOfBorg build firefox

**Comment by andir** [comment]
Result of `nixpkgs-review pr 102266` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>dropbox</li>
    <li>dropbox-cli</li>
    <li>firefox-bin-unwrapped</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>mate.caja-dropbox</li>
    <li>slimerjs</li>
  </ul>
</details>

**Comment by vcunat** [comment]
It builds for me.

**Pull request merged**
