### PR TITLE
speechd: introduce minimal variant, use it everywhere, inject big variant impurely

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

TODO: figure out how to default this to false without breaking people.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]
Thanks, i think that looks worth a try.

**Comment by vcunat** [comment]
Now that I think of it, I'm not sure if `services.speechd` is the best place, maybe `programs.speechd`?

I don't care really.  But now when it's new (not even on master yet) such changes are easiest.

**Comment by K900** [comment]
It is conceptually a service, it's just started weird currently. The upcoming next release will be a proper systemd socket activated thing.

**Comment by vcunat** [comment]
Oh, OK.  BTW, another way of saving space would be to default to English only (and perhaps just a single voice) unless you override your `i18n.supportedLocales` or something.

**Comment by NobbZ** [comment]
Something in the changelog would have been nice… Also what are the consequences of force disabling it? I used my system for severel years without it, and have no clue how I had to trigger it right now…

**Comment by K900** [comment]
It's perfectly fine to disable it if you don't need text to speech.

**Comment by NobbZ** [comment]
And why did it get enabled by default without a mention in the changelog?

**Comment by tejing1** [comment]
Which more than 99% of people don't... so why is it enabled by default for everybody?

**Comment by NobbZ** [comment]
Yes, accessibility is important, I agree, though so far there is some random envvar set without any documentation of how to use it nor what programs can actually use it.

The closure doesn't seem to be large in its effect on my system, I still consider the way it gets introduced worth questioning.

**Comment by K900** [comment]
That environment variable gets picked up by libspeechd in applications. The whole thing was actually an attempt to _reduce_ closure size - previously you'd just get speechd as a single package, including the gigabytes of voice data; now individual applications only depend on the library, and the daemon and voice data are separate and late bound, so you can disable them.

**Comment by tejing1** [comment]
So it's enabled for everybody because otherwise people who used it the way it worked before would have it break?

**Comment by K900** [comment]
Indeed, and also because people that rely on screenreaders should be able to use the stock configuration on the installer and on the default system.

**Comment by SuperSandro2000** [comment]
You get rid of it with:

```nix
services.orca.enable = false;
services.speechd.enable = false;
```

**Comment by rnhmjoj** [comment]
I think it would have been better to introduce an `accessibility` top-level option to centralize the default configuration of programs like brltty, orca or speechd. This is yet another undocumented default that's hard to track down.

**Pull request merged**
