### PR TITLE
python3Packages.plugwise: init at 0.8.5

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python module for Plugwise Smiles, Stretch and USB stick

https://github.com/plugwise/python-plugwise

This is a Home Assistant dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110370` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.plugwise: log <a href="https://termbin.com/k9u3">https://termbin.com/k9u3</a></li>
<li>python38Packages.plugwise: log <a href="https://termbin.com/pb8k">https://termbin.com/pb8k</a></li>
<li>python39Packages.plugwise: log <a href="https://termbin.com/87hf">https://termbin.com/87hf</a></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110370` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.plugwise</li>
<li>python38Packages.plugwise</li>
<li>python39Packages.plugwise</li>
</ul>
</details>

**Comment by mweinelt** [comment]
Same as https://github.com/NixOS/nixpkgs/pull/109629#issuecomment-768775218.

**Comment by fabaff** [comment]
Thanks

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
