### PR TITLE
parity: init at 1.6.5

### PR DESCRIPTION
**Pull request by MDeltaX**
Tested on:
NixOS 17.09.git.8f7225c
NixOS 17.09pre104410.65593e6

### CODE REVIEW

**Comment by joachifm** [comment]
Travis fails with hash mismatch error:
> output path ‘/nix/store/3z1pasqk0hg8nc7q1f6cvjarzdpb881c-parity-1.6.4-fetch’ has r:sha256 hash ‘0msgarfvbd0bk7axxwnydqzcfsb8q0ng4y73w3132mn0vl9hv3kx’ when ‘001765dqvrjb07vj3sh3r8lqwmgkbkkcp86n713l8qxa7qnsjddj’ was expected

**Comment by koenigmaximilian** [comment]
No errors on my systems...

**Comment by koenigmaximilian** [comment]
Updated to latest 1.6.5

**Comment by 7c6f434c** [comment]
Hm, tried to test it locally — no hash errors, but the build per se tried to fetch something from GitHub (and failed because of sandboxing)

**Comment by sorpaas** [comment]
Parity needs to have `__noChroot = true;` due to fetching of git dependencies.

**Comment by fpletz** [comment]
Can't these dependencies be prefetched without disabling the chroot?

**Comment by c0bw3b** [comment]
Closing now that #36756 was merged

**Pull request closed without merging**
