### PR TITLE
netdata: 1.9.0 -> 1.10.0

### PR DESCRIPTION
**Pull request by yesbox**
The web_access.patch would no longer apply. It disabled a check that required the static files for the web UI to be owned by the user the daemon runs as (not root, so it doesn't work well with nix).

Besides updating netdata, this commit removes that patch, changes the netdata service config to set the "web files owner/group" option to "root" and adds a test that checks that the web UI is being served.

This allows the web files to be owned by root without patching.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`) - **Only via the service, without the proper config netdata will not run correctly.**
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yesbox** [comment]
Ping maintainer @lethalman.

**Comment by xeji** [comment]
@GrahamcOfBorg  build netdata

**Comment by xeji** [comment]
@GrahamcOfBorg test netdata

**Comment by xeji** [comment]
`nixos/tests/netdata` succeeds locally on x86_64-linux. LGTM.

**Pull request merged**
