### PR TITLE
obsidian: use electron-24 which is not EOL

### PR DESCRIPTION
**Pull request by pmiddend**
###### Description of changes

Obsidian is hard-coded to use electron 21, which is now considered "unsafe" and gives the user an error.

I've upgraded to 24 and quickly started an instance. Seemed to work fine.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pmiddend** [comment]
@ofborg build obsidian

**Comment by johnrichardrinehart** [comment]
Any reason not to bump to `electron_24`?

**Comment by pmiddend** [comment]
> Any reason not to bump to `electron_24`?

It's a good point. Tried it and it works just as well.

**Comment by johnrichardrinehart** [comment]
> > Any reason not to bump to `electron_24`?
> 
> It's a good point. Tried it and it works just as well.

I'm not sure about stability guarantees. So, there might be a good reason not to. But, yeah, it works for me, too. I'd just like to delay this happening, again, for as much as possible.

**Comment by johnrichardrinehart** [comment]
Also, if we go this way it might be good to change the title/issue body (in case people search for this in the future).

**Comment by pmiddend** [comment]
> Also, if we go this way it might be good to change the title/issue body (in case people search for this in the future).

Also an excellent point, I only adapted the commit message, but have now updated the rest as well.

**Comment by johnrichardrinehart** [comment]
@atila @conradmearns @zaninime @qbit

Can we get some eyes on this to get it merged?

**Review by zaninime — APPROVED** [review]

**Comment by qbit** [comment]
I am torn. I feel like we should align as close as possible to what upstream is doing (so we don't introduce nixos-specific issues).

**Comment by pmiddend** [comment]
> I am torn. I feel like we should align as close as possible to what upstream is doing (so we don't introduce nixos-specific issues).

Me, too. I wasn't able to easily figure out what version of electron is used upstream, though.

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 226591` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>obsidian</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Comment by krav** [comment]
> Me, too. I wasn't able to easily figure out what version of electron is used upstream, though.

In Obsidian v1.1.16 on macOS `process.versions.electron` in dev tools reports `18.3.5`. It's also EOL.

**Comment by krav** [comment]
> In Obsidian v1.1.16 on macOS process.versions.electron in dev tools reports 18.3.5. It's also EOL.

Did a fresh install, and now it's `21.4.1`. Seems their autoupdater fails to update electron.

**Comment by johnrichardrinehart** [comment]
@krav I think the ship may have sailed on this one. We can redress if the `nixpkgs` `obsidian` behaves/fails relative to the official version. I'll try to ping the Obsidian devs to bump their `electron` version.

**Comment by johnrichardrinehart** [comment]
According to joethei#4474 (Discord) they're working on a `v24` release and it should be available soon. Better just to wait, I think.

**Pull request merged**
