### PR TITLE
ccal: init at 2.5.3

### PR DESCRIPTION
**Pull request by SharzyL**
###### Description of changes

`ccal` is `cal` but in Chinese calendar

http://ccal.chinesebay.com/ccal.htm

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SharzyL** [comment]
darwin build failed due to hardcoded `g++`, fixing

**Comment by tejing1** [comment]
1. Any particular reason not to use upstream's `make install` and `make install-man`?
2. `ccalpdf` has a `PATH`-based dependency on `ps2pdf`. That should probably be made into an absolute path. The reference to `ccal` in the same script should ideally be absolute as well.

**Comment by tejing1** [comment]
`zettlr` doesn't seem to actually provide `ps2pdf`, so it still fails. `ghostscript` is probably where you want to get it.

Also, adding `$out` to `PATH` in the wrapper will make the reference to `ccal` itself work, even when `ccalpdf` is called without it having been installed. (Such as when doing `${pkgs.ccal}/bin/ccalpdf` in a nix string generating a shell script somewhere)

**Comment by SharzyL** [comment]
Use `ghostscript_headless` since it seems smaller than `ghostscript`. Also add `coreutils` since the script uses `dirname`.

**Comment by tejing1** [comment]
Yeah, `ghostscript_headless` is better. `ccalpdf` works for me now, and the closure size isn't bad.

I don't see the use of `dirname` you're talking about, though. Am I blind?

**Comment by SharzyL** [comment]
`dirname` lies in `ps2pdf`, `ps2pdf14` and `ps2pdfwr`.

Yes this should be handled in `ghostscript` package, let me remove it and pr ghostscript later.

**Review by tejing1 — APPROVED** [review]

**Pull request merged**
