### PR TITLE
chromium: Updates.

### PR DESCRIPTION
**Pull request by ambrop72**
- dev: 48.0.2564.22 -> 49.0.2587.3
- beta: 48.0.2564.23 -> 48.0.2564.41
- stable: 47.0.2526.73 -> 47.0.2526.80

I only tested beta and stable, they build and run.

### CODE REVIEW

**Comment by aristidb** [comment]
I verified that chromium stable builds with chroot.

**Comment by domenkozar** [comment]
It seems to fail though: http://hydra.nixos.org/build/28919105/nixlog/1/raw

**Comment by ambrop72** [comment]
I see, the dev version fails. I may find some time to look into it, but I don't think it is a big issue (no reason to revert).

**Comment by vcunat** [comment]
Reading #12298, what about chromium on 15.09? There's 45.0.2454.93 as the default ATM. I assume popular browsers tend to get quite frequent security fixes...

**Comment by domenkozar** [comment]
@vcunat we should update it also there.

**Comment by ambrop72** [comment]
I confirm that 47.0.2526.106 works fine in 15.09, I have been using it there since I made the pull request.

**Comment by vcunat** [comment]
BTW, how have you been using this "in 15.09"? There aren't just chromium changes in this single file touched by this PR.

**Comment by ambrop72** [comment]
@vcunat, I did my latest Chromium updates on top of 15.09 and the pull requests were just rebased on master.  You should be able to cherry-pick these into 15.09 to bring it up to date: b9093f1c641846882fdced70269a4ee09c2c376b, 03cf5e662746ce00a09c8b050b433357728b14be, 6da327b43367ec13eb21d06f7595856b5c54c363.

**Comment by vcunat** [comment]
I'm build-testing ce809f6 but it takes ages as I don't have any strong machine available this week. @joepie91: do you want to test it?

**Comment by domenkozar** [comment]
@vcunat you want to cherry pick that to 15.09 and test? There is another fix for dev version in a later commit.

**Comment by vcunat** [comment]
What I referenced are cherry-picked commits (3) atop 15.09.

**Comment by joepie91** [comment]
@vcunat I'm running NixOS in a VM with limited RAM (1GB), so I'm not sure I can do a Chromium build without OOMing.

**Comment by vcunat** [comment]
I tested it on a few pages and pushed.

**Pull request merged**
