### PR TITLE
raspberrypifw: 1.20200601 -> 1.20200902

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Noticed it was out of date.

cc. @samueldr

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TredwellGit — CHANGES_REQUESTED** [review]
`sha256` needs to be updated.

**Comment by lovesegfault** [comment]
@TredwellGit Fixed! Thanks!

**Comment by ajs124** [comment]
Why are the `platforms` restricted on this package? It only downloads and unpacks an image?

**Comment by TredwellGit** [comment]
From https://nixos.org/manual/nixpkgs/unstable/#chap-packageconfig:
>The package isn't intended to run on the given system, as none of its meta.platforms match the given system.

This package is only intended to run on Raspberry Pis so this seems correct. Unless meta.platforms is about building instead of running. In any case not relevant to this pull request.

**Comment by ajs124** [comment]
Yeah, it prevents building on x86. I can open another issue/PR about this.

I just noticed it here, because building it for reviewing on x86 requires setting `allowUnsupportedSystem` and this package doesn't really build anything.

This package is also also on other architectures, if you want to access these files, e.g. to serve them via PXE or just to copy them onto an SD card for a raspberry pi.

**Comment by lovesegfault** [comment]
> Yeah, it prevents building on x86. I can open another issue/PR about this.
> 
> I just noticed it here, because building it for reviewing on x86 requires setting `allowUnsupportedSystem` and this package doesn't really build anything.
> 
> This package is also also on other architectures, if you want to access these files, e.g. to serve them via PXE or just to copy them onto an SD card for a raspberry pi.

Right, I did `NIXPKGS_ALLOW_UNSUPPORTED=1 nix-build ...`

**Comment by hax404** [comment]
rel https://github.com/NixOS/nixpkgs/pull/97258

**Pull request closed without merging**
