### PR TITLE
python3Packages.jupytext: fix tests

### PR DESCRIPTION
**Pull request by AluisioASG**
###### Motivation for this change

Due to improper sandboxing, I didn't notice the failed tests while upgrading jupytext in #121648.  The errors come from `jupyter_core` so the same fix is used here as there: set `$HOME` to a writable directory.

@bhipple @rmcgibbo this should fully build now, I'd appreciate if you could double-check it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122469` at 66e5f116 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.jupytext</li>
    <li>python39Packages.jupytext</li>
  </ul>
</details>

**Review by rmcgibbo — APPROVED** [review]
Builds fine for me. There's probably a way to shoe-horn this into pytestCheckHook by using a preCheck to set HOME, but I think this is perfectly clear.

```
Result of `nixpkgs-review pr 122469` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.jupytext</li>
    <li>python39Packages.jupytext</li>
  </ul>
</details>
```

**Review by bhipple — CHANGES_REQUESTED** [review]
Thanks for fixing this!  You can actually leave the `pytestFlagsArray` as you had it, and just add this single line.  Then it all builds:

```diff
diff --git a/pkgs/development/python-modules/jupytext/default.nix b/pkgs/development/python-modules/jupytext/default.nix
index e3de451cfe1..8a5abeae786 100644
--- a/pkgs/development/python-modules/jupytext/default.nix
+++ b/pkgs/development/python-modules/jupytext/default.nix
@@ -44,7 +44,8 @@ buildPythonPackage rec {
     jupyter_client
     notebook
   ];
-  # pre-commit tests require a Git repository.
+  # pre-commit tests require a Git repository; other tests expect $HOME to be set.
+  HOME = "$TMPDIR";
   pytestFlagsArray = [ "--ignore-glob='tests/test_pre_commit_*.py'" ];
   pythonImportsCheck = [ "jupytext" "jupytext.cli" ];
 

```

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 122469 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>python38Packages.jupytext</li>    <li>python39Packages.jupytext</li>  </ul></details>

**Pull request merged**
