### PR TITLE
[Backport release-24.05] factorio: 2.0.8 -> 2.0.10

### PR DESCRIPTION
**Pull request by bmillwood**
Backports:
- #350528 (also includes moving to the by-name hierarchy + nixfmt + some update.py refactoring)
- #350727
- #350802
- #350980

(My stopping point here is based on what's convenient for me to test, since I happen to already have downloaded 2.0.10 locally. I plan to open another PR after this is merged for the rest of the version updates, but didn't want to mix them all into one big thing.)

I've tested this (or rather, this rebased onto nixos-24.05, without all the other pending release-24.05 changes) locally to ensure both `factorio-space-age` and `factorio_1` (= `factorio`) both start up OK.

91d76e30124dd06d836fd603722d4f71d80b567a required me to update my `allowUnfreePredicate`, which I assume isn't a big deal?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by priegger** [comment]
* The diff lgtm. Thanks a lot!
* I tested the regular and experimental versions of 1.x, 2.x and space-age as well as the demo.

Have not tested the headless versions yet.

**Comment by bmillwood** [comment]
> * The diff lgtm. Thanks a lot!
> * I tested the regular and experimental versions of 1.x, 2.x and space-age as well as the demo.
> 
> Have not tested the headless versions yet.
> 
> Edit: I have not used the headless version(s) in a while, I don't have the time to test them at the moment.

out of curiosity, what testing do you do? I ask partly because I think when I tested 1.x it ate my achievements file (it didn't like reading the 2.x one, so it replaced it with a fresh one)

**Comment by priegger** [comment]
> > * The diff lgtm. Thanks a lot!
> > * I tested the regular and experimental versions of 1.x, 2.x and space-age as well as the demo.
> > 
> > Have not tested the headless versions yet.
> > Edit: I have not used the headless version(s) in a while, I don't have the time to test them at the moment.
> 
> out of curiosity, what testing do you do? I ask partly because I think when I tested 1.x it ate my achievements file (it didn't like reading the 2.x one, so it replaced it with a fresh one)

Thanks for asking, sorry I did not give more details. I only did minimal testing, started a new game and played some seconds. I did not test compatibility to existing data, since I don't have any.

Thanks for bringing this up.

**Comment by bmillwood** [comment]
> > > * The diff lgtm. Thanks a lot!
> > > * I tested the regular and experimental versions of 1.x, 2.x and space-age as well as the demo.
> > > 
> > > Have not tested the headless versions yet.
> > > Edit: I have not used the headless version(s) in a while, I don't have the time to test them at the moment.
> > 
> > 
> > out of curiosity, what testing do you do? I ask partly because I think when I tested 1.x it ate my achievements file (it didn't like reading the 2.x one, so it replaced it with a fresh one)
> 
> Thanks for asking, sorry I did not give more details. I only did minimal testing, started a new game and played some seconds. I did not test compatibility to existing data, since I don't have any.
> 
> Thanks for bringing this up.

to be clear, that's enough for me, although also it's not necessarily my opinion that matters 😅

**Review by FliegendeWurst — APPROVED** [review]

**Comment by bmillwood** [comment]
(FWIW, now that nixos-24.11 is out, I think it's still OK to merge this, but I won't be making any more 24.05 backports)

**Pull request merged**
