### PR TITLE
fractal: enable gstreamer-good support

### PR DESCRIPTION
**Pull request by uninsane**
gstreamer-good is in the legacy `fractal` package, seems to have been overlooked in the `fractal-next` port. providing this enables fractal to play inline video -- else the following output is observed for messages containing video:

```
ERROR fractal::components::video_player::imp: Error playing video: Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.
Your GStreamer installation is missing a plug-in.
../gst/playback/gsturidecodebin.c(1049): no_more_pads_full (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0:
no suitable plugins found:
../gst/playback/gstdecodebin2.c(4704): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: Quicktime (video/quicktime, variant=(string)iso)
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lelgenio** [comment]
@uninsane, Could you please check if you can still build `fractal-next`, based on the latest master?

The build timeouts in CI and also when I run `nixpkgs-review` locally. It seems it's not caused by this PR, as this problem is already present in master.

**Comment by schuelermine** [comment]
The build times were about 30 minutes, or at least very long, before the timeouts happened, I think

**Comment by uninsane** [comment]
`fractal-next` builds for me on master. as mentioned, it's lengthy: about 2 hours on a mid-range desktop, because rustc uses only a single core when linking it. you can rebuild it in about 5 minutes using an overlay like this:

```nix
nixpkgs.overlays = [(self: super: {
  fractal-next = super.fractal-next.override (upstream:
    nativeBuildInputs = upstream.nativeBuildInputs ++ [
      git  # only necessary when profile is development or hack
    ];

    mesonFlags = upstream.mesonFlags ++ [
      # profile: default, beta, development, hack.
      # - default causes a 2hr+ build, 98% of that being `rustc fractal` using a single core
      # - development has the same problem
      # - hack brings the build down to ~5 minutes, because it doesn't pass --release to cargo
      #   - it still has rustc using only ~4 cores typical
      "-Dprofile=hack"
    ];
  );
})]
```

**Comment by schuelermine** [comment]
Can you rebase this to after e9ca6038eb5f4398fc57feb4084b7df4afaa6d7d?

**Comment by uninsane** [comment]
> Can you rebase this to after [e9ca603](https://github.com/NixOS/nixpkgs/commit/e9ca6038eb5f4398fc57feb4084b7df4afaa6d7d)?

that was merged into staging. ping me again once it's merged into master?

in the meantime i rebased to f1818b1041cea87a8d7ecc969eed692d0688eb9f & it still builds cleanly, at least.

**Comment by schuelermine** [comment]
Sorry for not approving earlier, but Fractal 5 has now been merged. Feel free to use this diff to update (GitHub wouldn’t let me upload it as a file)

```patch
diff --git a/pkgs/applications/networking/instant-messengers/fractal/default.nix b/pkgs/applications/networking/instant-messengers/fractal/default.nix
index d0723653e159..fd96316a0943 100644
--- a/pkgs/applications/networking/instant-messengers/fractal/default.nix
+++ b/pkgs/applications/networking/instant-messengers/fractal/default.nix
@@ -72,6 +72,7 @@ stdenv.mkDerivation rec {
     gstreamer
     gst-plugins-base
     gst-plugins-bad
+    gst-plugins-good
   ]);
 
   passthru = {
```

**Comment by uninsane** [comment]
rebased for fractal 5

**Review by blitz — APPROVED** [review]

**Review by schuelermine — APPROVED** [review]

**Pull request merged**
