### PR TITLE
vesktop: vendor esbuild

### PR DESCRIPTION
**Pull request by vgskye**
## Description of changes
vendor esbuild for vesktop

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vgskye** [comment]
why was ofborg trying to build electron again
@ofborg build vesktop

**Comment by getchoo** [comment]
im not exactly what this is for, as the current package seems to build and work fine. is there an issue i'm missing that's resolved by doing this?

**Comment by vgskye** [comment]
aarch64

**Comment by getchoo** [comment]
ah i haven't built it on there yet so i hadn't come across it

i think a better solution might be continuing to follow the lockfile, as the arch's we're targeting here are already specified in upstream's `pnpm-lock.yaml` and can be downloaded on aarch64 systems. the only reason this doesn't happen now is due to the deps already being cached by their outputHash, which will only be for x86_64 at the moment. to get around this, you can build the pnpm-deps attribute with no substitutors on aarch64 and add the resulting hash to the expression. i have a full example of this [here](https://github.com/getchoo/nixpkgs/commit/1e7ccdabd1633c72c1ce91dc472bc90f717167d0) - the only other change needed is a glob for the unpacked directory since it appears to use the name of the architecture on non-x86_64 platforms. 

maybe we could cherry pick that here and add hashes for the other architectures as needed? :p

**Comment by vgskye** [comment]
vendoring esbuild was the approach taken by many node/electron packages in nixpkgs, so I took that route.

**Comment by getchoo** [comment]
i think in this case following the lockfile would be better just for simplicity sake and it would also be easier for us to expand platform support in the future (with stuff like darwin for example)

**Comment by vgskye** [comment]
fair

**Pull request closed without merging**
