### PR TITLE
nextcloud: 12.0.0 -> 12.0.2, nextcloud-news-updater: 9.0.2 -> 10.0.0

### PR DESCRIPTION
**Pull request by schneefux**
Updated to the latest versions.

Also removed myself as maintainer because I do not have enough time to update the packages in a timely manner.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
Do maintainers have to guarantee that they update packages in a timely manner? I certainly cannot do that for the packages I'm maintaining. I don't think the packages will be updated more timely if you remove yourself as maintainer :-) The maintainers entry is a list after all, so there can be multiple maintainers.

**Comment by bjornfor** [comment]
Anyway, I think maintainer removal deserves separate commit(s). So I edited the commits so that they do only what they say (version bump), and merged to master (777075295686c7aa529362c1d3d3456f9efd918f and parent).

Please open a separate PR if you really want to be removed as maintainer :-)

**Comment by schneefux** [comment]
Alright, you can keep me ^-^ Do you have a page that explains the tasks and responsibilities of a maintainer? Would be encouraging to have it in the contributor guide :)

**Comment by bjornfor** [comment]
> Alright, you can keep me ^-^

Yay!

> Do you have a page that explains the tasks and responsibilities of a maintainer?

Not that I know of.

**Pull request closed without merging**
