### PR TITLE
pulumi: 3.90.1 -> 3.93.0

### PR DESCRIPTION
**Pull request by Trundle**
## Description of changes

New upstream releases:
* [3.91.0](https://github.com/pulumi/pulumi/releases/tag/v3.91.0)
* [3.91.1](https://github.com/pulumi/pulumi/releases/tag/v3.91.1)
* [3.92.0](https://github.com/pulumi/pulumi/releases/tag/v3.92.0)
* [3.93.0](https://github.com/pulumi/pulumi/releases/tag/v3.93.0)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Trundle** [comment]
Result of `nixpkgs-review pr 267316` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>pulumi</li>
    <li>pulumiPackages.pulumi-language-go</li>
    <li>pulumiPackages.pulumi-language-nodejs</li>
    <li>pulumiPackages.pulumi-language-python</li>
    <li>python310Packages.pulumi</li>
    <li>python310Packages.pulumi-aws</li>
    <li>python310Packages.pulumi-aws.dist</li>
    <li>python310Packages.pulumi.dist</li>
    <li>python311Packages.pulumi</li>
    <li>python311Packages.pulumi-aws</li>
    <li>python311Packages.pulumi-aws-native</li>
    <li>python311Packages.pulumi-aws-native.dist</li>
    <li>python311Packages.pulumi-aws.dist</li>
    <li>python311Packages.pulumi-azure-native</li>
    <li>python311Packages.pulumi-azure-native.dist</li>
    <li>python311Packages.pulumi-command</li>
    <li>python311Packages.pulumi-command.dist</li>
    <li>python311Packages.pulumi-random</li>
    <li>python311Packages.pulumi-random.dist</li>
    <li>python311Packages.pulumi.dist</li>
  </ul>
</details>

**Comment by teto** [comment]
I often have pulumi complain about wrong versions for the sdks, shouldn't we update them at the same time as pulumi ?

**Comment by Trundle** [comment]
Which SDKs do you mean? The Python SDK shares the same source and is updated with this PR and I'm not aware of others (in nixpkgs). That doesn't mean there aren't any others, but they aren't on my radar so far.

**Comment by bhavitsharma** [comment]
Hey, is it possible to merge this PR? There are a couple of fixes that I am waiting for in the latest version of pulumi :)

**Comment by bhavitsharma** [comment]
@Trundle @veehaitch @teto sorry for the ping again guys, is there any way it can merged?

**Pull request merged**
