### PR TITLE
home-assistant: 0.77.3 -> 0.80.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @peterhoeg

### CODE REVIEW

**Comment by peterhoeg** [comment]
.2 is already out

**Comment by peterhoeg** [comment]
Working fine here.

**Comment by peterhoeg** [comment]
@dotlambda  - actually, I tested the .2 version and didn't realize this was PR was changed to .3

The override of ```voluptuous-serialize``` doesn't work as it uses ```fetchFromGitHub``` and not ```fetchPyPi``` so you cannot call ```src.override```:

```
while evaluating the attribute 'src.name' at /home/peter/src/active/nixpkgs_unstable/pkgs/servers/home-assistant/default.nix:57:9:
while evaluating the attribute 'src.override' at /home/peter/src/active/nixpkgs_unstable/pkgs/development/python-modules/voluptuous-serialize/default.nix:10:3:
attribute 'override' missing, at /home/peter/src/active/nixpkgs_unstable/pkgs/servers/home-assistant/default.nix:57:15
```

There are no other users of ```voluptuous-serialize``` so we can probably get away with just updating that straight to 2.0.0 and dropping the override.

**Comment by dotlambda** [comment]
How's that possible? I replaced `fetchFromGitHub` by `fetchPypi` in e964c2dda6.

**Comment by peterhoeg** [comment]
Ahh, because that commit hadn't made it into unstable.

**Pull request merged**
