### PR TITLE
taskwarrior3: 3.0.2 -> 3.1.0

### PR DESCRIPTION
**Pull request by aktaboot**
## Description of changes

taskwarrior3 is failing after the rustc version bump to 1.79

the fix is in this commit:
https://github.com/GothenburgBitFactory/taskwarrior/commit/82e645b9293caa09c9bc85809b4a78296077846b

but I bumped to the latest commit of taskwarrior3
 

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
is this reported upstream? I would not fix an upstream issue by packaging something off of the master branch of the software, but rather by waiting for them to publish a release that fixes the issue...

**Comment by willhansen** [comment]
> after the rustc version bump to 1.79
Can we just require the last version that works?

**Comment by debling** [comment]
Taskwarrior [v3.1.0](https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v3.1.0) launched today, could it be bumped to this version instead of an unstable one?

I tested on nix-darwin, and it works the same way, since the patch you mentioned is in the 3.1.0 release. For testing, I only had to bump the commit rev and the hashes, below are the modifications:

```diff
diff --git a/pkgs/by-name/ta/taskwarrior3/package.nix b/pkgs/by-name/ta/taskwarrior3/package.nix
index 508ea5a31..4632ffe60 100644
--- a/pkgs/by-name/ta/taskwarrior3/package.nix
+++ b/pkgs/by-name/ta/taskwarrior3/package.nix
@@ -15,12 +15,12 @@
 }:
 stdenv.mkDerivation rec {
   pname = "taskwarrior";
-  version = "3.0.2-unstable-2024-07-29";
+  version = "3.1.0";
   src = fetchFromGitHub {
     owner = "GothenburgBitFactory";
     repo = "taskwarrior";
-    rev = "70714e8ca06ac66962c527a86fc23addef76d35a";
-    hash = "sha256-Zxex9+USC8tGbfNgYjqdXH8/JXgsVEguUYGK8te3EtU=";
+    rev = "v3.1.0";
+    hash = "sha256-iKpOExj1xM9rU/rIcOLLKMrZrAfz7y9X2kt2CjfMOOQ=";
     fetchSubmodules = true;
   };
 
@@ -51,7 +51,7 @@ stdenv.mkDerivation rec {
     name = "${pname}-${version}-cargo-deps";
     inherit src;
     sourceRoot = src.name;
-    hash = "sha256-UTq1PgMDgMSOAzJRUt/3q+z39TwLPpH6XoMG8yZQVgo=";
+    hash = "sha256-L+hYYKXSOG4XYdexLMG3wdA7st+A9Wk9muzipSNjxrA=";
   };
   cargoRoot = "./";
   preConfigure = ''
```

**Review by eljamm — APPROVED** [review]
Result of `nixpkgs-review pr 331377` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>taskwarrior3</li>
  </ul>
</details>

**Comment by donovanglover** [comment]
Thanks for testing. Merging.

**Pull request merged**
