### PR TITLE
ahoviewer: 1.4.9 -> 1.5.0; add useUnrar option

### PR DESCRIPTION
**Pull request by xzfc**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build ahoviewer

**Comment by matthewbauer** [comment]
"unrar" is unfree. Can you see if it's possible to get rid of unrar in buildInputs? (try --disable_rar in configureFlags)

**Comment by xzfc** [comment]
@GrahamcOfBorg build ahoviewer

**Comment by xzfc** [comment]
@GrahamcOfBorg build ahoviewer

**Comment by xzfc** [comment]
@matthewbauer I've added `useUnrar` option to the package, defaulted to `false`.
Do not know why @GrahamcOfBorg ignores my commands.

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build ahoviewer

**Pull request merged**
