### PR TITLE
ncdu: pie for darwin builds

### PR DESCRIPTION
**Pull request by tarc**
Fix broken darwin compilation. The issue started after the 2.2.2 -> 2.3 update (0b6d39590921).

ncdu defaults pie to false while zig requires it to be true for darwin.

## Description of changes

Add option for ncdu to set pie in the zig build and default it to true if `stdenv.isDarwin`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 249722` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ncdu</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]

**Comment by tarc** [comment]
Result of `nixpkgs-review pr 249722` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ncdu</li>
  </ul>
</details>

**Comment by marcusramberg** [comment]
Would be nice to see this merged.

**Review by sebastianblunt — APPROVED** [review]

**Comment by tarc** [comment]
Hello, @pSub  and @rodrgz. You guys were added as required reviewers to this PR of mine, fixing ncdu compilation for Darwin targets.

I'm new to the Nixpkgs reviewing process (and to Nix/NixOs), so I wonder if you were supposed to be here as required reviewers...

**Review by kubeliv — APPROVED** [review]

**Comment by nagy** [comment]
> while zig requires it to be true for darwin.

@AndersonTorres would it make sense to include this into `zig.hook`? I could imagine that this eventually affects other packages as well, that default to pie=false. If you agree, then we could remove this argument from this package.

**Comment by sebastianblunt** [comment]
I'm not an expert on zig but I think the `pie` build option is specific to ncdu. It's defined in the ncdu build file, and at least minizign fails to build with `-Dpie=true`: `error: Invalid option: -Dpie`

**Comment by AndersonTorres** [comment]
That being said, this expression should not expose `pie` as option.

Indeed I believe much of these things will be solved only after 1.0.

**Pull request merged**
