### PR TITLE
linux_testing: 5.13-rc6 -> 5.14-rc1

### PR DESCRIPTION
**Pull request by arcnmx**
###### Motivation for this change

[release notes](https://lwn.net/Articles/862565/)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ymatsiuk — CHANGES_REQUESTED** [review]
Could you please update to rc7 and sqash all the commits (except nvidia patch) to one `linux-testing: 5.13-rc6 -> 5.14-rc7`

**Review by ymatsiuk — APPROVED** [review]
Runs smooth for me 👍🏻 Thanks.

**Comment by zhaofengli** [comment]
Well, 5.14 [came out today](https://lwn.net/Articles/867706/). Maybe we should change this PR to `linux_5_14: init at 5.14.0`?

**Comment by arcnmx** [comment]
superseded by #142511

**Pull request closed without merging**
