### PR TITLE
linux_hardened: make hardened patchset less picky

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

The hardened patches include the root Makefile, so they can add the
-hardened1 string to the end of the version. Unfortunately, they include
a context string which causes them to always fail to match if the minor
version is bumped.

In some cases, it's possible to fuzzy-apply the old patchset against a
newer minor version of the kernel. To accommodate this, we use
patchutils (as from e.g. fetchpatch) to strip all the context lines
from the root Makefile's patch only. This is probably a little more
aggressive than necessary: we only really want to do this for the first
few lines in the Makefile, but this is easiest and there aren't usually
any other changes to the file.

We could also just drop the patch to the Makefile, but this would remove
the -hardened string entirely from the kernel build, which probably
isn't desirable.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
@ofborg test hardened

**Review by NeQuissimus — APPROVED** [review]

**Comment by ajs124** [comment]
It might be a better idea to "just" keep the hardened kernels on a different set of versions from the mainline ones.

Not sure how hard that would be to implement though.

**Comment by 8573** [comment]
> It might be a better idea to "just" keep the hardened kernels on a different set of versions from the mainline ones.

See also: #140281. Also, I don't think this change and that change are mutually exclusive.

**Comment by Ma27** [comment]
> See also: #140281. Also, I don't think this change and that change are mutually exclusive.

I just opened https://github.com/NixOS/nixpkgs/pull/141100 where the update script takes care of it. I'm not sure if we really want to "blindly" apply patches for kernel versions where these aren't tested.

**Pull request closed without merging**
