### PR TITLE
staging stabilization

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

https://hydra.nixos.org/eval/1459406?compare=trunk

There's a significant amount of new failures on staging.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ttuegel** [comment]
A major source of failures is `rustc` (now needed for `librsvg`) which has a `checkPhase` failure I cannot reproduce locally.

**Comment by LnL7** [comment]
https://github.com/NixOS/nixpkgs/commit/b22cc53db147cdbfe84ffbc344143bf1e8c1e515

**Comment by Mic92** [comment]
@ttuegel do you have a link for the rust failure?

**Comment by LnL7** [comment]
FYI. There's some discussion going on in #nixos-dev

**Pull request closed without merging**
