### PR TITLE
rhc: remove

### PR DESCRIPTION
**Pull request by manveru**
###### Motivation for this change

This application is deprecated since 2016 and won't build on current Ruby versions: https://github.com/openshift/rhc

That's why I think it's safe to remove, since it's been marked as broken in February 2018.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
cc @szczyp

**Review by worldofpeace — APPROVED** [review]
:+1: , we should remove deprecated software whenever we can do so feasibly.

**Comment by Ma27** [comment]
With `NIXPKGS_ALLOW_BROKEN=1` it still builds for me (I get a lot of deprecations warnings with Ruby 2.5 though), so I suggest that we keep the attribute in `all-packages.nix` for now:

``` nix
{
  # ...
  rhc = throw ''
    `rhc` has been removed as it's marked as broken since 2018-02 and 
    officially abandoned by upstream.
  '';
}
```

**Comment by worldofpeace** [comment]
> With `NIXPKGS_ALLOW_BROKEN=1` it still builds for me (I get a lot of deprecations warnings with Ruby 2.5 though), so I suggest that we keep the attribute in `all-packages.nix` for now:
> 
> ```nix
> {
>   # ...
>   rhc = throw ''
>     `rhc` has been removed as it's marked as broken since 2018-02 and 
>     officially abandoned by upstream.
>   '';
> }
> ```

Yeah, having a message would be helpful. Though I think that should be in `aliases.nix`.

**Comment by manveru** [comment]
I added the alias, tried to keep it as short as the other ones. Does this look OK for you?

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
@manveru thanks!

**Pull request merged**
