### PR TITLE
chromium: 66.0.3359.139 -> 66.0.3359.181

### PR DESCRIPTION
**Pull request by YorikSar**
###### Motivation for this change

Already landed on master, need to backport to stable as it contains several security fixes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by YorikSar** [comment]
CC @bendlas @vcunat @matthewbauer

**Comment by vcunat** [comment]
I'm building the default version locally to test a little.

**Comment by YorikSar** [comment]
FYI I've built it on VM, copied and ran locally on my 18.03, it opened several sites just fine. Didn't test it further though.

**Review by vcunat — APPROVED** [review]
Briefly used, seems OK.

**Pull request merged**
