### PR TITLE
Linux bump default LLVM to 11

### PR DESCRIPTION
**Pull request by toonn**
###### Motivation for this change

#126411 bumps the default version of LLVM for x86_64 Darwin, which is tied to the stdenv. This brings it in line with aarch64-darwin but takes it out of sync with the default LLVM for Linux. This is not ideal because fixes for one LLVM version could introduce failures for another version, which would require introducing branching on the LLVM version to resolve.

This PR builds on #126411 and is currently mostly to get a Hydra evaluation for Linux to see how much work bumping would take.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by toonn** [comment]
Just rebased on staging-next since all the release-related stuff has cooled down and the bump on Darwin seems to have gone into staging-next OK. Here's [a new comparison](https://hydra.nixos.org/eval/1732639?compare=staging-next&full=0#tabs-now-fail).

**Comment by sternenseemann** [comment]
Seems like 400 potential new regressions compared to current master? <https://hydra.nixos.org/eval/1732639?compare=trunk#tabs-now-fail>

**Comment by toonn** [comment]
@sternenseemann, yep, what number of failures would be considered good enough? Should I rebase this on master or staging-next again to get a more recent comparison? The staging-next evaluation this one is based on has even more failures [when compared to trunk](https://hydra.nixos.org/eval/1732110?compare=trunk&full=0).

**Comment by toonn** [comment]
So, in [this staging-next comparison](https://hydra.nixos.org/eval/1734441?compare=1732587), from ~ two weeks ago, the main cause of failures seemed to be ispc. This has since been worked around in 981170a so I rebased the branch again.

How do we move this forward? Last comparison we had 23 newly introduced failures as compared to staging-next. Is the goal/requirement to introduce 0 new failures?

**Comment by vcunat** [comment]
No, even `staging-next` -> `master` merges don't target zero regressions, though it's nice when they get very low.  If it's like 23 and nothing important stands out, I think it's OK to merge to `staging` and a further round of reduction can be done during `staging-next` builds.

**Comment by toonn** [comment]
Ok, so [this is the comparison for the previous evaluation](https://hydra.nixos.org/eval/1737780?compare=1737553).
The only thing that stands out to me is Blender. Which is still failing because of ispc, so I looked for the most recent evaluation where ispc succeeds and started [a new evaluation](https://hydra.nixos.org/eval/1738738?compare=1737785) to make sure.

This confirmed that I did indeed break ispc. Turns out when removing the LLVM 11 specific arguments I removed `stdenv = llvmPackages_11.stdenv` from the arguments for ispc. I was probably thinking about the darwin stdenv too much, which does use LLVM. [The next evaluation should have even fewer failures](https://hydra.nixos.org/eval/1738777?compare=1737785) 🤞.

**Comment by toonn** [comment]
The ispc failure (and Blender) is fixed now. Zcash was also using an LLVM stdenv but seems to work fine with a GNU stdenv so I'm not sure that's still necessary? @vcunat was so kind as to check that `webkitgtk_4_1` does indeed build, I'm not sure why it failed on Hydra (OOM?).

I believe this means there's no more serious failures so this is ready for review/testing.

**Comment by toonn** [comment]
@alyssais, @sternenseemann, @vcunat, I believe this is ready for review.

**Review by sternenseemann — APPROVED** [review]
Haven't checked if relying on the default version in all cases is wise (depends on the package), but probably doesn't matter in the grand scheme of things (every default LLVM update will need careful checking for regressions).

**Comment by toonn** [comment]
My motivation for using the default is an assumption that most things that explicitly specify LLVM 11 probably do so because the default isn't recent enough.

**Review by jonringer — APPROVED** [review]
According to the hydra eval, most failures are related to the recent python310 bump

```
# nix-review-tool output
x86_64-linux python3.10-unittest2-1.1.0 | 91
x86_64-linux python3.10-debugpy-1.5.1 | 58
x86_64-linux python3.10-imagecodecs-lite-2019.12.3 | 29
x86_64-linux python3.10-eventlet-0.33.0 | 27
x86_64-linux sybil-2.0.1 | 19
x86_64-linux python3.10-pytest-4.6.11 | 18
x86_64-linux python3.10-semver-2.13.0 | 17
x86_64-linux python3.9-pygame-2.1.0 | 14
x86_64-linux python3.10-tensorflow-tensorboard-2.6.0 | 12
x86_64-linux webkitgtk-2.34.3 | 11
x86_64-linux python3.10-mpi4py-3.0.3 | 9
x86_64-linux python3.10-commoncode-30.0.0 | 9
x86_64-linux python3.10-sanic-21.9.3 | 9
x86_64-linux python3.10-cssutils-2.3.0 | 8
x86_64-linux python3.10-unicodedata2-13.0.0-2 | 7
x86_64-linux python3.10-mocket-3.10.3 | 7
```

**Review by mweinelt — APPROVED** [review]
Current comparison against trunk looks very good indeed.

**Comment by toonn** [comment]
Thanks, @jonringer and @mweinelt!

**Pull request merged**
