### PR TITLE
maintainers/teams: add podman team 

### PR DESCRIPTION
**Pull request by zowoq**
Initial discussion in https://github.com/NixOS/nixpkgs/pull/84168#issuecomment-608306834

cc @saschagrunert @vdemeester

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by saschagrunert — APPROVED** [review]
LGTM :+1:

**Comment by FRidh** [comment]
Good to see more maintainer teams!

**Comment by FRidh** [comment]
Could you give feedback on https://github.com/NixOS/nixpkgs/issues/75275? I assume you use those builders.

**Review by jtojnar — APPROVED** [review]

**Comment by worldofpeace** [comment]
Added a @NixOS/podman team for all of you.
(and did invites)

**Comment by zowoq** [comment]
Seems like some of the teams don't work for requesting reviews?

NixOS/{ACME,Freedesktop,GNOME} are able to be used but can't select podman/php?

**Comment by worldofpeace** [comment]
@zowoq I asked @grahamc to add nixpkgs to the repos' (since you have to be a admin to do this)

**Comment by zowoq** [comment]
> @zowoq I asked @grahamc to add nixpkgs to the repos' (since you have to be a admin to do this)

Ping @grahamc
____

Also, I noticed that some teams have a profile picture set, could we add the podman logo please?

podman

**Comment by grahamc** [comment]
done!

**Comment by zowoq** [comment]
Thanks!

**Pull request merged**
