### PR TITLE
[new] Add apvlv pdf reader

### PR DESCRIPTION
**Pull request by ardumont**
- Build locally ok
- installed in nix store and runs ok
- Default pdf when none is specified in cli:

screenshot_2015-06-06_19-39-01
- When opening one:

screenshot_2015-06-06_19-40-15

### CODE REVIEW

**Comment by ardumont** [comment]
Hello,

Missing the magic words, please.

And thanks for your time.

Cheers,

**Comment by Fuuzetsu** [comment]
Why is the 0.1.5 release from https://github.com/naihe2010/apvlv/releases not being used? As I understand you went with the release listed on http://naihe2010.github.io/apvlv/ ; it's probably better to use the GitHub release as it seems more recent and such sites are often out of date.

Aside from that it looks good to me. Not sure if the chmod is needed but I haven't checked.

**Comment by ardumont** [comment]
Hello,

> Why is the 0.1.5 release from https://github.com/naihe2010/apvlv/releases not being used? As I understand you went with the release listed on http://naihe2010.github.io/apvlv/ ; it's probably better to use the GitHub release as it seems more recent and such sites are often out of date.

[I tried with the latest release from github first](https://github.com/ardumont/nixpkgs/commit/612d9f69e1edf1f1b4b1d938fb26b7bbd896b248).
It compiles (with gtk3 and some other dependencies).
But it does not run correctly (freeze, or the window to open the file to open does simply not appear).

> Aside from that it looks good to me.

Cool.

> Not sure if the chmod is needed but I haven't checked.

I will double check.

Cheers,

**Comment by ardumont** [comment]
> > Not sure if the chmod is needed but I haven't checked.

> I will double check.

It is not. Removed.

Thanks

**Pull request merged**
