### PR TITLE
xonotic: fix a couple of bugs

### PR DESCRIPTION
**Pull request by fps**
- Build all three binaries (sdl, glx, server)
- build player UID infrastructure
- locate and add more libraries looked up at runtime:
  - fix font (uses the xonolonium font now) (libfreetype)
  - add libtheora/enc/dev libvorbis/enc/file 
- copy public key over to installation directory, so player UIDs work

this looks to me now like a mostly functioning version of xonotic. The build is linux specific though

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kloenk** [comment]
I don't see the reason to revert to one package, instead of the 3, which saves a lot of hydra storage.

CC @petabyteboy

**Comment by fps** [comment]
My aim here was to get a working xonotic package for myself. I originally had a comment in the PR stating that I do not expect this to be merged in this form - it somehow got lost during my fumbling with PR (I don't do that too often ;)). But maybe the maintainers of the original package can take inspiration from the changes and use it to fix the one in nixpkgs.

**Comment by Kloenk** [comment]
Which branch are you using? Unstable has a reworked xonotic (different than 20.03). The xonotic from unstable/master is working on my side. What is you problem with xonotic?

**Comment by fps** [comment]
I used the default.nix from master. The biggest issues:

- Player UID tracking (for keeping player stats and records in defrag) not working
- Xolonium font missing

**Comment by Kloenk** [comment]
Freetype is not marked missing via ldd. Will it help to supply it as build input, or is there some type of compile flag to include it?

How to build source/d0_blind_id? is the key available in the source so we can just copy it?

I would like to stay with a build from source, and also don't include the xonotic data in the cache because it would get massive.

**Comment by fps** [comment]
Oh and i just confirmed that 

cl_capturevideo 1

works now to capture videos during the game.. Which doesn't work in the original derivation either because libvorbis/theora/ogg are not linked against and patchElf'ed in (they are looked up at runtime).

**Comment by fps** [comment]
> Freetype is not marked missing via ldd. Will it help to supply it as build input, or is there some type of compile flag to include it?
> 
> How to build source/d0_blind_id? is the key available in the source so we can just copy it?
> 
> I would like to stay with a build from source, and also don't include the xonotic data in the cache because it would get massive.

The derivation in my PR _is_ a build from source. I'm using the Makefile shipped with the release zip (which ships the source as well). try with

<pre>
nix-build -E 'with import <nixpkgs> {}; pkgs.callPackage ./xonotic.nix {}' 
</pre>

**Comment by Kloenk** [comment]
If I see it correctly we can build the key with this command (from the download root):
~~~
( cd source/d0_blind_id && ./configure --enable-static --disable-shared $(RIJNDAELDETECT_CONFIGURE) )
make -C source/d0_blind_id
~~~

This could help as to still have the three different xonotic versions. Also for download time I would prefer to stick to the source zip, as it's much smaller.

**Comment by fps** [comment]
Yeah, that command builds the d0_blind_id library which is needed for player UIDs to work. Additionally the public key key_0.d0pk needs to be copied over to the right location during install.

There is also the quakeC (gmqcc) compiler shipped with the source which needs to be built, too, for the quakeC code to be built from source. For that to succeed the shebang in source/qcsrc/tools/qcc.sh needs to be patched and the PATH set during the buildPhase.

Like I said. I can take the time later tonight to move all the fixes over to the original xonotic derivation.

**Comment by fps** [comment]
I will open a new PR with the updated expression

**Comment by fps** [comment]
https://github.com/NixOS/nixpkgs/pull/90282

**Pull request closed without merging**
