### PR TITLE
passage: unstable-2022-05-01 -> 1.7.4a2

### PR DESCRIPTION
**Pull request by MarkusZoppelt**
## Description of changes

Changelog: https://github.com/FiloSottile/passage/compare/1262d308f09db9b243513a428ab4b8fb1c30d31d...1.7.4a2

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Ma27** [comment]
> This package does not have releases

Tags seem to exist though: https://github.com/FiloSottile/passage/releases/tag/1.7.4a2

**Comment by MarkusZoppelt** [comment]
> Tags seem to exist though: https://github.com/FiloSottile/passage/releases/tag/1.7.4a2

Thanks for the info!

I updated my commit. The hash was generated via
    
    nix-prefetch-url https://github.com/FiloSottile/passage/archive/refs/tags/1.7.4a2.zip

and then converted via

    nix hash to-sri 0a5l5nrhrr2vjjsgdcf424fxdmg0sfy117ys69imnq9ff5pan6s4 --type sha256

Is that correct? Sorry, I'm not very familiar with updating nixpkgs.

Appreciate the help!

**Comment by Ma27** [comment]
Looks good.
One question though: the test files are from a BSD3 licensed repo. Can we actually use that here (IANAL)?

**Comment by Ma27** [comment]
Hi!

Sorry for not getting back earlier.

> I updated my commit. The hash was generated via

The approach is correct, you just picked the wrong URL: `fetchFromGitHub` uses the `.tar.gz` download, not the `.zip` one. Also, the tag doesn't have a `v` in front of the version.

If unsure, you can usually obtain the URL like this:

```
$ nix eval -f . passage.src.url
"https://github.com/FiloSottile/passage/archive/1.7.4a2.tar.gz"
```

from the root of a nixpkgs checkout.

However, usually it's easier to just set `hash` to `lib.fakeHash` and run `nix-build`, then Nix will determine the correct hash:

```
building '/nix/store/fzkc5nvp895k1qdlcppdz4ym9asrgy42-source.drv'...

trying https://github.com/FiloSottile/passage/archive/1.7.4a2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19537    0 19537    0     0  30309      0 --:--:-- --:--:-- --:--:-- 30309
unpacking source archive /build/1.7.4a2.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/fzkc5nvp895k1qdlcppdz4ym9asrgy42-source.drv':
        likely URL: https://github.com/FiloSottile/passage/archive/1.7.4a2.tar.gz
         specified: sha256-RBurbnEuYVtjMtqfELzT4NXWHRHEsfa0lFvkDLMttCg=
            got:    sha256-tGHJFzDc2K117r5EMFdKsfw/+EpdZ0qzaExt+RGI4qo=
error: 1 dependencies of derivation '/nix/store/7nrslbldxgbrjliq2f884hyn78zyzb5f-passage-1.7.4a2.drv' failed to build
```

The approach here is called TOFU (trust on first use), you trust that the initial download is correct and after that you ensure that everybody else can reproduce the same result by specifying the content hash of the tarball.

Nothing to be done from your end though, I already force-pushed a fix to your branch.

**Review by Ma27 — APPROVED** [review]
Upstream diff looks good, seems fine on my machine.

Will await CI and merge then.

**Pull request merged**
