### PR TITLE
bedtools: 2.29.0 -> 2.29.1

### PR DESCRIPTION
**Pull request by jbedo**
###### Motivation for this change

New bedtools release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build bedtools

**Comment by markuskowa** [comment]
The build fails on darwin (can't find gcc).

**Comment by jbedo** [comment]
This was the case prior to the version bump. Should be fixed in a separate pull request though?

**Comment by markuskowa** [comment]
A separate commit is sufficient.

**Comment by markuskowa** [comment]
Thanks for fixing it.

**Pull request merged**
