### PR TITLE
librnd, pcb-rnd, sch-rnd init

### PR DESCRIPTION
**Pull request by hzeller**
## Description of changes

Provide sch-rnd and pcb-rnd including the base library it needs

  * librnd: init at 4.3.0  (base library needed for pcb-rnd and sch-rnd)
  * sch-rnd: init at 1.0.6 (Schematic editor http://repo.hu/projects/sch-rnd )
  * pcb-rnd: init at 3.1.5 (PCB editor http://repo.hu/projects/pcb-rnd )
  * camv-rnd: init at 1.1.4 (gerber viewer http://www.repo.hu/projects/camv-rnd )

The releases are on *.tar.gz on the authors website (preferred to fetch releases from for resource use); active development happens in subversion, so provide options for users to also choose an unstable commit to get a current development version.

Three separate commits for each packaqge, but included in this PR.

The programs have features that are available as plug-ins; the default plug-ins are auto-configured with the script provided from upstream, but future work will make sub-packages that contain each plug-in for a more fine-grained installation by the user. This baseline commit makes it possible to start developing that solution as we need e.g. `librnd` first.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hzeller** [comment]
@ofborg build pcb-rnd sch-rnd

**Comment by hzeller** [comment]
Adding @fricklerhandwerk as Igor (who wrote this software) mentioned that you once were in contact w.r.t. nix packaging.

Igor is not happy to have it all bundled together in one package, and would like to have the plug-ins separate. How this can be done, would need to be discussed, as I could see how to package things as separate sub-packages `pcb-rnd.foobarplugin`, but then, since NixOS does not have the concept of 'metapackages' that bundle together a set of choices, this might be tricky. So for now, as first step, I compile all plugins and put them in the respective package.

But maybe there is something else possible that I don't know yet as relative Nix-noob, so I'd like to have some advice for future suggestions.

**Comment by fricklerhandwerk** [comment]
The usual pattern for such a scenario would be adding `passthru.withPlugins = ps: ...` and accommodating the plugins maybe under `passthru.plugins`.

**Comment by hzeller** [comment]
Ah, never worked with passthru anything. What would be a good canonical example of a project with plugins where a subset of plugins should be bundled by default while others would be optional nix packages containing additional plugins @fricklerhandwerk ? I might need some inspiration :)

**Comment by fricklerhandwerk** [comment]
I recommend grepping the Nixpkgs source for `withPackages =` or `withPlugins =` (and variants thereof) and explore the code from there to find working examples.

**Comment by hzeller** [comment]
Sorry, went into summer vacation in-between, so didn't have time to work on the plugins transition yet. Hopefully in the next few days. Changed this to be a Draft-PR in the meantime.

**Comment by hzeller** [comment]
Ups, I messed up my git. Closing.

**Pull request closed without merging**
