### PR TITLE
pythonPackages.jsonrpclib-pelix: Remove moredread as maintainer

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

See https://github.com/NixOS/nixpkgs/issues/54249

In short, I don't feel comfortable to maintain such a security critical dependency for a cryptocurrency package (`electrum` etc.) at the moment.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Moredread** [comment]
cc @ehmry @joachifm @np

**Comment by jonringer** [comment]
security concerns are largely an upstream issue, all we can do is mark that there are known vulnerabilities, apply patches, or bump the version.

If you don't feel comfortable maintaining it, then I can remove you

**Comment by Moredread** [comment]
Mhh, it looks it isn't a dependency anymore. https://github.com/spesmilo/electrum/issues/4825 https://github.com/spesmilo/electrum/commit/5df5aaa96d35acb854cb7e7098e5ef23e85c751e

**Comment by jonringer** [comment]
if you still want to be removed, let me know, or close the PR if you're fine with continuing on :)

**Comment by veprbl** [comment]
> Mhh, it looks it isn't a dependency anymore. [spesmilo/electrum#4825](https://github.com/spesmilo/electrum/issues/4825) [spesmilo/electrum@5df5aaa](https://github.com/spesmilo/electrum/commit/5df5aaa96d35acb854cb7e7098e5ef23e85c751e)

Should we remove the whole fork then?

**Comment by Moredread** [comment]
The electrum change hasn't been released yet. But after that I think we can remove , as it isn't used anywhere else jsonrpclib-pelix and modern alternatives exist for the package.

**Comment by jonringer** [comment]
electron-cash also mentions it,
```
$ rg jsonrpclib-pelix
pkgs/top-level/python-packages.nix
2577:  jsonrpclib-pelix = callPackage ../development/python-modules/jsonrpclib-pelix {};

pkgs/applications/misc/electron-cash/default.nix
17:    jsonrpclib-pelix

pkgs/applications/misc/electrum/ltc.nix
27:    jsonrpclib-pelix

pkgs/applications/misc/electrum/default.nix
65:    jsonrpclib-pelix

pkgs/development/python-modules/jsonrpclib-pelix/default.nix
7:  pname = "jsonrpclib-pelix";
19:    homepage = https://pypi.python.org/pypi/jsonrpclib-pelix/;
```

**Comment by Moredread** [comment]
:/ OK in that case please remove me after all please. :)

**Pull request merged**
