### PR TITLE
gpgme: 1.16.0 -> 1.17.0

### PR DESCRIPTION
**Pull request by trofi**
Among other things fixes build against glibc-2.34.

changelog: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=NEWS;hb=refs/tags/gpgme-1.17.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Could you fix the commit message to 1.16.0? I've changed the PR title.

**Comment by trofi** [comment]
> Could you fix the commit message to 1.16.0? I've changed the PR title.

Good point! Updated commit message from `1.6.0` to `1.16.0`.

**Comment by risicle** [comment]
Does this include the python 3.10 support from #155384 ?

**Comment by trofi** [comment]
No, the `python310Packages.gpgme` still fails as:

```
gpgme> checking for a Python interpreter with version >= 2.7... none
gpgme> checking for a Python interpreter with version >= 3.4... none
gpgme> checking for a Python interpreter with version >= 3.5... none
gpgme> checking for a Python interpreter with version >= 3.6... none
gpgme> checking for a Python interpreter with version >= 3.7... none
gpgme> checking for a Python interpreter with version >= 3.8... none
gpgme> checking for a Python interpreter with version >= 3.9... none
gpgme> checking for a Python interpreter with version >= all... none
gpgme> configure: error:
gpgme> ***
gpgme> *** Please install the python development packages.
```

**Comment by SuperSandro2000** [comment]
Why did you close this? We want both PRs actually.

**Comment by trofi** [comment]
I assumed another change would update the version. Thanks for handling this!

**Pull request closed without merging**
