### PR TITLE
letsencrypt: 0.1.0 -> 0.1.1-corrected

### PR DESCRIPTION
**Pull request by benley**
The /usr/bin/sw_vers thing is pretty weird, but afaict that is really where sw_vers lives in the darwin stdenv.

### CODE REVIEW

**Comment by copumpkin** [comment]
Why `-corrected`?

1. It breaks `nix-env`'s horrible version parsing, which looks at the last hyphen in the name string.
2. We patch packages all the time to make them build properly. Doesn't seem worth putting that into the version modifier.

More broadly, this won't work with sandbox builds enabled. It also reduces the determinism of the build, and honestly the project shouldn't care what machine it's built on. Even more oddly, it's only pulling out the first component of the OS version, which has been 10 for the past 15 years and will likely stay that way for a while longer.

I'd just patch [le_util.py](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/le_util.py#L232-L237) to set `os_ver = "10";` and ignore `sw_vers` altogether. If we put it in the `stdenv`, we'd make it return a constant deterministic value anyway.

**Comment by benley** [comment]
That `-corrected` is really the tag they use for the release - apparently the first v0.1.1 release tag was broken and had to be redone.  Maybe we can keep the package as 0.1.1 and just use the v0.1.1-corrected tag to fetch the source.

I'll just patch le_util.py as you suggest - that does sound like a better idea than using sw_vers.

**Comment by copumpkin** [comment]
Ah, sorry about the `-corrected` thing! I misunderstood :smile: 

Either way, with the hyphen in there, it'll still break `nix-env`'s understanding of the version (it'll think the package is called `letsencrypt-0.11` with version `corrected`). I hate that version parsing logic. We should really kill it across all our packages, but it's tricky.

**Comment by vcunat** [comment]
> It breaks nix-env's horrible version parsing, which looks at the last hyphen in the name string.

That's not what the version parsing is like. It breaks at *the first hyphen followed by a non-letter*. For docs see [nix manual's section on nix-env](http://nixos.org/nix/manual/#sec-nix-env), part `--upgrade` / versions.

**Comment by copumpkin** [comment]
Oh, didn't realize that, thanks! Still horrible to have it parse at all,
but a bit better than I though :)

**Comment by nckx** [comment]
@benley: this breaks `simp_le`, which can no longer find `acme`.

```
Processing ./simp_le-0-py2-none-any.whl
Collecting acme==0.1.0 (from simp-le==0)
  Could not find a version that satisfies the requirement acme==0.1.0 (from simp-le==0) (from versions: )
No matching distribution found for acme==0.1.0 (from simp-le==0)
builder for â€˜/nix/store/nzs2jl8jzhix60mjks3vr5442xb2q0jh-python2.7-simp_le-20151207.drvâ€™ failed with exit code 1
```

**Comment by benley** [comment]
Ah, thanks for the reminder about this PR - I need to get it updated

**Comment by zimbatm** [comment]
Just updated @benley 's patch but it's not perfect

**Comment by benley** [comment]
closing this one in favor of #13467

**Pull request closed without merging**
