### PR TITLE
elixir: default 1.7.4 -> 1.9.0

### PR DESCRIPTION
**Pull request by yorickvP**
###### Motivation for this change

New releases should probably update the default.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yorickvP** [comment]
@GrahamcOfBorg build rabbitmq-server

**Comment by yorickvP** [comment]
Seems like this change has no effect except for people using `nix-shell -p elixir` (or `nix-env`).

**Comment by yorickvP** [comment]
@grahamcofbord build rabbitmq-server

**Comment by yorickvP** [comment]
@GrahamcOfBorg build rabbitmq-server

**Comment by Profpatsch** [comment]
I’m not the right person to review this, can you ping the relevant maintainers?

**Comment by yorickvP** [comment]
cc: @ankhers @LnL7 @ejpcmac

**Review by ankhers — APPROVED** [review]

**Pull request merged**
