### PR TITLE
n8n: add WEBHOOK_URL environment variable

### PR DESCRIPTION
**Pull request by gmemstr**
###### Description of changes

The WEBHOOK_URL options is only able to be set through environment variables. Was considering adding a more generic "environment" parameter but wasn't sure the best way to approach this.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Janik-Haag — COMMENTED** [review]
In case you still want to add a generic way take a look at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/continuous-integration/woodpecker/server.nix#L18-L32 
most things are already defined at least once in nixpkgs you can easily find those by grepping through your local repo with something like ripgrep 

If you don't want to add a generic way, then this this looks fine to me.

**Comment by gmemstr** [comment]
Most other things can be configured with the configuration JSON so I'm okay with keeping this as is honestly.

**Review by Janik-Haag — APPROVED** [review]

**Comment by Janik-Haag** [comment]
Pinging freezboy for review since they made the init for this module

**Comment by Janik-Haag** [comment]
I will merge this If they don't respond in one or two weeks.

**Comment by Janik-Haag** [comment]
@ofborg build n8n.passthru.tests

**Comment by Janik-Haag** [comment]
Hm ci tests fail for some reason :( did you test the module changes locally? If not do you need instructions on how to do so? Btw feel free to ask questions, I'm usually happy to help :D

**Comment by gmemstr** [comment]
Huh, interesting. It seems like because of the unfree license it's being skipped?

**Comment by Janik-Haag** [comment]
Oh yeah you are right, I should have taken a closer look :see_no_evil:

**Comment by Janik-Haag** [comment]
Tests build fine locally, I will give this a few more days and if no one complains merge it.

**Comment by gmemstr** [comment]
@Janik-Haag Just wanted to follow up on this :eyes: Doesn't seem like anyone objects

**Pull request merged**
