### PR TITLE
libfabric: revert to 1.15.1

### LINKED ISSUE #212220: `python3Packages.mpi4py` fails tests with segfault on unstable
### Describe the bug

`python3Packages.mpi4py` fails the build, because running the tests terminates with a segfault on unstable.

```
running test
[hwloc/linux] failed to find sysfs cpu topology directory, aborting linux discovery.
[hwloc/linux] failed to find sysfs cpu topology directory, aborting linux discovery.
[1674458416.055205] [localhost:611  :0]       tcp_iface.c:816  UCX  ERROR opendir(/sys/class/net) failed: No such file or directory
[0@localhost] Python 3.10 (/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin/python3.10)
[0@localhost] MPI 3.1 (Open MPI 4.1.4)
[0@localhost] mpi4py 3.1.4 (/nix/store/va7lbji2dfwdgc1ndqzazbrip1bnvcc1-python3.10-mpi4py-3.1.4/lib/python3.10/site-packages/mpi4py)
....s........................................................................................................................................................................................................................................................................................................................ssssssssssssssssssssssss..............................................................ss...................................................................ssssssssssss............................................................sss.......................................................................................................................................................................................................s.....................................s.sss..s....s............sssssssss......ssssssssssssssssssssssssss.................ssssssssssssssssss......sss...s...s..................................................................................................................................................................s...s...............[localhost:611  :0:611] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:    611) ====
 0 0x000000000003dbf0 __GI___sigaction()  ???:0
 1 0x00000000000bf40d mca_btl_ofi_acswap()  ???:0
 2 0x0000000000207433 ompi_osc_rdma_compare_and_swap()  ???:0
 3 0x00000000000a7936 PMPI_Compare_and_swap()  ???:0
 4 0x00000000000d8d4d __pyx_pw_6mpi4py_3MPI_3Win_61Compare_and_swap()  ???:0
 5 0x00000000001dd26d method_vectorcall_VARARGS_KEYWORDS()  ???:0
 6 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
 7 0x00000000001e827f _PyEval_Vector()  ???:0
 8 0x000000000011ecd8 method_vectorcall()  ???:0
 9 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
10 0x00000000001e827f _PyEval_Vector()  ???:0
11 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
12 0x00000000001e827f _PyEval_Vector()  ???:0
13 0x000000000011ec42 method_vectorcall()  ???:0
14 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
15 0x00000000001e827f _PyEval_Vector()  ???:0
16 0x0000000000129642 _PyObject_Call_Prepend()  ???:0
17 0x000000000016ab49 slot_tp_call()  ???:0
18 0x00000000000bcc84 _PyObject_MakeTpCall.localalias()  ???:0
19 0x000000000006f42c _PyEval_EvalFrameDefault()  ???:0
20 0x00000000001e827f _PyEval_Vector()  ???:0
21 0x000000000011ec42 method_vectorcall()  ???:0
22 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
23 0x00000000001e827f _PyEval_Vector()  ???:0
24 0x0000000000129642 _PyObject_Call_Prepend()  ???:0
25 0x000000000016ab49 slot_tp_call()  ???:0
26 0x00000000000bcc84 _PyObject_MakeTpCall.localalias()  ???:0
27 0x000000000006f42c _PyEval_EvalFrameDefault()  ???:0
28 0x00000000001e827f _PyEval_Vector()  ???:0
29 0x000000000011ec42 method_vectorcall()  ???:0
30 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
31 0x00000000001e827f _PyEval_Vector()  ???:0
32 0x0000000000129642 _PyObject_Call_Prepend()  ???:0
33 0x000000000016ab49 slot_tp_call()  ???:0
34 0x00000000000bcc84 _PyObject_MakeTpCall.localalias()  ???:0
35 0x000000000006f42c _PyEval_EvalFrameDefault()  ???:0
36 0x00000000001e827f _PyEval_Vector()  ???:0
37 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
38 0x00000000001e827f _PyEval_Vector()  ???:0
39 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
40 0x00000000001e827f _PyEval_Vector()  ???:0
41 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
42 0x00000000001e827f _PyEval_Vector()  ???:0
43 0x000000000011ecd8 method_vectorcall()  ???:0
44 0x0000000000070cf2 _PyEval_EvalFrameDefault()  ???:0
45 0x00000000001e827f _PyEval_Vector()  ???:0
46 0x000000000011ecd8 method_vectorcall()  ???:0
47 0x0000000000070cf2 _PyEval_EvalFrameDefault()  ???:0
48 0x00000000001e827f _PyEval_Vector()  ???:0
49 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
50 0x00000000001e827f _PyEval_Vector()  ???:0
51 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
52 0x00000000001e827f _PyEval_Vector()  ???:0
53 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
54 0x00000000001e827f _PyEval_Vector()  ???:0
55 0x00000000000cea08 PyVectorcall_Call.localalias()  ???:0
56 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
57 0x00000000001e827f _PyEval_Vector()  ???:0
=================================
/nix/store/8ppzfvsc14b8v1fbsyzpgi0nmmv1yjz3-setuptools-check-hook/nix-support/setup-hook: line 4:   611 Segmentation fault      /nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin/python3.10 nix_run_setup test
```

Complete build log: [nix.log](https://github.com/NixOS/nixpkgs/files/10477510/nix.log)

### Steps To Reproduce

```
nix build github:NixOS/nixpkgs/676c80dcc2f0ba780c8ab204f92c5abd69fa1245#python3Packages.mpi4py
```

### Expected behavior
Build succeeds.

### Screenshots
N/A

### Additional context
N/A

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-56-generic, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(henri): `"nixpkgs"`
 - nixpkgs: `/home/henri/.nix-defexpr/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by markuskowa**
###### Description of changes
Libfabric seems to introduce subtle errors, which are picked up by the test phase of `python3Packges.mpi4py`.
This may, however, also affect other packages, but is not detected during the build (i.e. any test). 
Since there is no patch or solution at moment, I suggest reverting to the latest known working version until a fix is available.

Closes https://github.com/NixOS/nixpkgs/issues/212220

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wegank — CHANGES_REQUESTED** [review]
The mpi4py failure seems specific to x86_64-linux on Hydra, so I'm not in favour of reverting it. Meanwhile, is it a coincidence that the `enablePsm2` and `enableOpx` flags are also specific to x86_64-linux?

**Review by bzizou — COMMENTED** [review]
MPI generally uses specific networking interfaces and may need some tuning at runtime. It frequently fails if the runtime options are not adapted to the code and the hardware configuration. So, I think that the failure should be analyzed upstream before trying to downgrade the libfabric that should normally not be used on a testing host that does not have low latency networking interfaces . I made some suggestions in the #212220 issue

**Comment by markuskowa** [comment]
@wegank While the package is not restricted to `x86_64-linux` it may in practice almost exclusively be used on `x86_64-linux`. The actual use cases is mostly to provide support for Intel OmniPath interfaces (@bzizou correct if I am wrong).

@bzizou I agree that the problem should be solved upstream. IMHO openmpi should work with its default settings and not cause segfaults. Right now `libfabric` leaves mpi4py in broken state.

What is the suggestion to fix it?

**Comment by markuskowa** [comment]
@wegank I am strongly in favor of reverting the update if we can not get a proper patch. IMHO do not see the point in updating packages at all cost here. It causes a breakage of mpi4py, which is a blocker at the moment for everyone relying on that package.

**Comment by wegank** [comment]
Does the package work with `enableOpx = false` on x86_64-linux? I can't find a machine to test it on now, but if it doesn't, I guess I'm OK to revert it.

**Comment by markuskowa** [comment]
> Does the package work with `enableOpx = false` on x86_64-linux? I can't find a machine to test it on now, but if it doesn't, I guess I'm OK to revert it.

The Opx switch has no effect on the failure. I tested different combinations and came to the conclusion that it is a bug that was introduced somewhere are after version 1.15.1 I tried to track down the exact version by bisecting `libfabric` but failed (there is another bug before which causes the test to hang instead).

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build python3Packages.mpi4py

**Pull request merged**
