### PR TITLE
home-assistant: 0.91.4 -> 0.92.2

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://www.home-assistant.io/blog/2019/04/24/release-92/

This was a complex update due to home-assistant/home-assistant#22699.
The `parse-requirements.py` script needed quite some changes to account for the new `manifest.json`. But the new code turned out shorter than the old one.
I also have completely rewritten the code that accounts for the `platform = "component"` way of configuration. The respective commit (d280603bd18cb27ce2e6bf6a0f8a163d8568214f) should be backported. This will make it rather useless to use `autoExtraComponents` with a pre-0.92 version of Home Assistant. Is this something that should be possible?

Due to the extensive changes, I invite everyone to test thoroughly. Please bear in mind that you will need to apply d280603bd18cb27ce2e6bf6a0f8a163d8568214f to your nixpkgs checkout if you build your system from one of the release channels.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @netixx

### CODE REVIEW

**Comment by dotlambda** [comment]
This breaks transifex-client, which requires `python-slugify<3.0.0`.

cc @etu

**Comment by etu** [comment]
> This breaks transifex-client, which requires `python-slugify<3.0.0`.

Sigh, that damn package. It probably doesn't require that really. It has made lots of absurd claims in the past. I'll look into this tomorrow at work (in about 8-9 hours or so). I already patch the package to get rid of some of the absurd claims of required versions of deps. But yeah, I need it so I'll fix it somehow.

**Comment by peterhoeg** [comment]
A number of platforms failed to initialize for me:

 - darksky
 - pushover
 - broadlink
 - onkyo

```
Error setting up platform pushover

Traceback (most recent call last):
  File "/nix/store/1zvaffg7c9n2nwyqsfnsram172h8jqal-homeassistant-0.92.0/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 71, in async_setup_platform
    platform.get_service, hass, p_config, discovery_info)
  File "/nix/store/kimimvhimclyfzlncpg36zjni3wn70nq-python3-3.7.3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/1zvaffg7c9n2nwyqsfnsram172h8jqal-homeassistant-0.92.0/lib/python3.7/site-packages/homeassistant/components/pushover/notify.py", line 26, in get_service
    from pushover import InitError
ModuleNotFoundError: No module named 'pushover'
```

**Comment by peterhoeg** [comment]
Ahh wait, while this is the package used, the module is still the one from stable and thus without the mentioned commit.

**Comment by etu** [comment]
@dotlambda I have tested building transifex locally, and changing this line: https://github.com/NixOS/nixpkgs/blob/7e2eb72407934c44cf72694772d346c684a35673/pkgs/tools/text/transifex-client/default.nix#L20 is enough to get it to work. I did set it to 4.0.0 locally.

**Comment by dotlambda** [comment]
@etu I have added a commit making the suggested change.

**Comment by dotlambda** [comment]
> A number of platforms failed to initialize for me:
> 
> * darksky
> * pushover
> * broadlink
> * onkyo

Since all of these use the `platform = ...` way of configuration, we should be fine once the commit is applied.

**Comment by FRidh** [comment]
Feel free to merge into staging once it's ready.

**Comment by dotlambda** [comment]
@peterhoeg Did you try again?

**Comment by peterhoeg** [comment]
I didn't, no, and I will not be able to do so before the weekend.

**Comment by juaningan** [comment]
I ve tried to add:

```
sensor = [ {                   
      platform = "darksky";         
      api_key = "APIKEY";
      monitored_conditions = [                                                
        "temperature"  
        "humidity"  
      ]; 
    } ]; 
```

but didnt install dependent packages (python-forecastio).

**Comment by dotlambda** [comment]
@juaningan I tested your config and added `builtins.trace` to see which packages are added to `componentBuildInputs`. `python-forecastio` was one of them. Are you sure your NixOS system is built from a Nixpkgs checkout with 38a6d3c0426c0d6f37ae814ba49c7c6d2912f27b apllied?

**Comment by juaningan** [comment]
yes, I'm using

```
let                                                      
  unstable = import (builtins.fetchTarball {
     url = https://github.com/dotlambda/nixpkgs/archive/home-assistant-0.92.tar.gz;
  }) {};                           
in 
services.home-assistant.package = unstable.home-assistant
```

anyways I will double check.

**Comment by juaningan** [comment]
Tried again:

``ModuleNotFoundError: No module named 'forecastio'``

If I add the component in extra packages then works.

**Comment by dotlambda** [comment]
The nixpkgs version used to build your *system*, not the one Home Assistant is built from, must include the patch. That's because it's the NixOS module's task to detect the used components.
Maybe we could change this so that the package is passed `autoExtraComponents` and `config`.

**Comment by juaningan** [comment]
I understand, I really like to select which packages I prefer bleeding edge in my system without affecting system wide. So I can keep with my workaround. Or do you know how can I override only that module?

**Comment by dotlambda** [comment]
That patch will be backported to 19.03, so you won't have to change anything. But for testing, you have to build from a local nixpkgs checkout of your channel with the patch appied.

**Comment by dotlambda** [comment]
I'll merge on 2019-05-05 20:00 UTC if there's no further comment until then.

**Pull request merged**
