### PR TITLE
stdenv preHook: only define $NIX_ENFORCE_PURITY if it hasn't yet been…

### PR DESCRIPTION
**Pull request by timbertson**
Note: **mass rebuild** - I'm not sure how such changes usually work, does it get merged into staging in order to coincide with other mass rebuilds?

This came out of #13532 - the obvious mechanism for opting out of `NIX_ENFORCE_PURITY` is to define `NIX_ENFORCE_PURITY = false;` in your derivation, but that doesn't work because it's _always_ set to `1` in the `stdenv` preHook. To override it, you have to override the entire preHook, which also implicitly drops whatever else was in the `preHook` (I hope it wasn't important!).

Unfortunately, I wasn't able to test my changes - I started a build and it got somewhere, but since this is a mass rebuild type change, I had to give up before I saw the built results. I think it should work fine, but would appreciate someone more familiar with the stdenv (particularly the ordering of events between the preHook and other environment variables being set) to conform.

### CODE REVIEW

**Comment by zimbatm** [comment]
Hey @timbertson can you re-submit the PR against staging ? github doesn't let us change that after the fact.

**Comment by timbertson** [comment]
No worries, rebased against staging in #13583

**Comment by timbertson** [comment]
Sorry @dezgeg , missed your comment. The only failure I could see in your lik was related to daylight saving's time, so that seems unrelated. How did you get that link though? I'd like to check the results for my staging PR, if possible...

**Comment by dezgeg** [comment]
It's not a comment for your changes, GitHub is just showing that since you rebased the branch against staging and this PR has master as the target branch (so it will show anything in staging that's not in master as "related" to this PR). Don't worry about it.

**Pull request closed without merging**
