### PR TITLE
ruff: 0.1.7 -> 0.1.8, ruff-lsp: 0.0.45 -> 0.0.47

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog ruff: https://github.com/astral-sh/ruff/releases/tag/v0.1.8
Changelog ruff-lsp: https://github.com/astral-sh/ruff-lsp/releases/tag/v0.0.47

cc @figsoda @kalekseev 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
I took a look at potential breakages because people lint their scripts with ruff and I would suggest to remove the following:
- https://github.com/NixOS/nixpkgs/blob/cfb8505a8fefe7a57f392f85ce9d9dbe9066a6ef/pkgs/development/python-modules/diffusers/default.nix#L102
- https://github.com/NixOS/nixpkgs/blob/cfb8505a8fefe7a57f392f85ce9d9dbe9066a6ef/pkgs/development/python-modules/weasel/default.nix (not sure why black or pre-commit are there either) #274096

and maybe remove those:
- https://github.com/NixOS/nixpkgs/blob/cfb8505a8fefe7a57f392f85ce9d9dbe9066a6ef/nixos/modules/image/repart.nix#L172-L174

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>46 packages built:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.diffusers</li>
    <li>python310Packages.diffusers.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.weasel</li>
    <li>python310Packages.weasel.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.weasel</li>
    <li>python311Packages.weasel.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
I added a commit to remove the one in `diffusers`.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.weasel</li>
    <li>python310Packages.weasel.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.weasel</li>
    <li>python311Packages.weasel.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg build python3.pkgs.diffusers

**Comment by SomeoneSerge** [comment]
I'm maybe confused by github. Is my understanding correct that the first nixpkgs-review had succeeded before the diffusers commit came in? I.e. that there were no breakages after all and that it wasn't necessary to remove ruff from the check inputs?

I'm also asking because I don't know why was ruff put there in the first place

**Comment by SuperSandro2000** [comment]
> Is my understanding correct that the first nixpkgs-review had succeeded before the diffusers commit came in?

Both nixpkgs-review build all packages successful. 

> I.e. that there were no breakages after all and that it wasn't necessary to remove ruff from the check inputs?

It reduces the amount of rebuilds triggered and by that potential breakages when bumping linters. It is nice that people want to keep high quality code but if we update e.g. black and a new rule breaks many things that is just plain annoying and unnecessary. Hence if the linters are not touching our code, the rule of thumb is to always remove them to keep maintenance required lower.

> I'm also asking because I don't know why was ruff put there in the first place

It is listed in the projects requirements.txt as a dev input.

**Comment by SomeoneSerge** [comment]
Ok, so it's not so much about the update as about tidying up? Anyway looks like we should disable `tests/others/test_check_copies.py::CopyCheckTester::test_is_copy_consistent` in diffusers too

**Comment by SuperSandro2000** [comment]
> Ok, so it's not so much about the update as about tidying up?

Yes

> Anyway looks like we should disable `tests/others/test_check_copies.py::CopyCheckTester::test_is_copy_consistent` in diffusers too

Oh yes. The tests before always timed out so I assumed they will just continue to work. Calling linters in tests is especially prone to errors when upgrades happen.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.diffusers</li>
    <li>python310Packages.diffusers.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.weasel</li>
    <li>python310Packages.weasel.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.weasel</li>
    <li>python311Packages.weasel.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.testers.runNixOSTest-example</li>
    <li>tests.trivial-builders.references</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.diffusers</li>
    <li>python310Packages.diffusers.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.diffusers</li>
    <li>python310Packages.diffusers.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.diffusers</li>
    <li>python310Packages.diffusers.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274092` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pydantic-settings</li>
    <li>python310Packages.pydantic-settings.dist</li>
    <li>python311Packages.pydantic-settings</li>
    <li>python311Packages.pydantic-settings.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python310Packages.diffusers</li>
    <li>python310Packages.diffusers.dist</li>
    <li>python310Packages.pytest-examples</li>
    <li>python310Packages.pytest-examples.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Pull request merged**
