### PR TITLE
Emacs e2wm and window-layout

### PR DESCRIPTION
**Pull request by ashalkhakov**
These are some packages from MELPA.

Hopefully this patch is OK. I'm still having issues with proper rebasing (my laptop is old and I can't afford rebuilding everything, but then there is the issue of rebasing my patches to the upstream/master branch). Or, it's just that other commiters are so fast I can't keep up with their pace. :)

### CODE REVIEW

**Comment by jagajaga** [comment]
Rebase your PR :)

**Comment by Fuuzetsu** [comment]
ping

**Comment by nbp** [comment]
@jagajaga The merge commit does not seems to be needed any more, can we cherry-pick this change?

**Comment by jagajaga** [comment]
@nbp we do not have `pkgs/top-level/emacs-melpa-packages.nix` nowadays.

**Pull request closed without merging**
