### PR TITLE
quassel: Start after its databases

### PR DESCRIPTION
**Pull request by Mathnerd314**
Like in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701943

### CODE REVIEW

**Comment by wkennington** [comment]
This assumes that the database is running on the same system and that
quassel can't deal with an outage of the database. This should really be
handled upstream in quassel if it is really an issue but it should be an
okay temporary workaround.

**Comment by Mathnerd314** [comment]
Maybe you're right; I think what I really need is https://github.com/quassel/quassel/commit/09b9df73ca9decca2555f1d0024806cfd090ea5a.

**Comment by kini** [comment]
@Mathnerd314 Out of curiosity, how are you using the NixOS module such that this became a problem for you? As far as I can see, the NixOS module doesn't even support non-sqlite backends, so I don't see what problem is solved by making it wait for PostgreSQL / MySQL to launch. For that matter, I don't think quassel upstream even has a MySQL backend at all. (I ask because I'm hoping to edit the module to allow switching to the PostgreSQL backend.)

**Comment by Mathnerd314** [comment]
I set up Quassel with PostgreSQL, roughly along the lines of https://bugs.quassel-irc.org/projects/1/wiki/PostgreSQL (start postgres, create database account, configure quassel to use that account). It was all by hand though and I don't have the commands I used.

Lately I've been using IRCCloud though, so Quassel is inactive.

**Pull request merged**
