### PR TITLE
add config.environment.ld-linux

### PR DESCRIPTION
**Pull request by volth**
Add option to install symlink to `ld-linux(8)` system-wide to allow running unmodified ELF binaries.

It might be useful to run games or executables distributed inside jar files as discussed
https://discourse.nixos.org/t/runtime-alternative-to-patchelf-set-interpreter/3539
https://discourse.nixos.org/t/running-binaries-without-fhs-and-patchelf/1828

It is the third concession to FHS after `/bin/sh` and `/usr/bin/env`,
but unlike `config.environment.binsh` and `config.environment.usrbinenv` this new option is disabled by default

cc @

### CODE REVIEW

**Comment by aszlig** [comment]
@volth: Hm, what about something like this:

```nix
{ pkgs, ... }:

{
  # x86_64-only, but you get the idea ;-)
  environment.shellAliases.run-ld = "${pkgs.stdenv.glibc}/lib/ld-linux-x86-64.so.2";
}
```

Of course, this won't work if the program in question uses `execve` afterwards, but in general, we could provide it as a wrapper command instead so we don't need to pollute `/lib` and `/lib64`.

**Comment by volth** [comment]
>   x86_64-only, but you get the idea ;-)

In an interactive session I could run `patchelf --set-interpreter` :)

It is for the cases when the ELF-executable is a dropper extracted (for example by a java program) to /tmp and immediately run, so it is difficult to alter it's command line or run `patchelf` between those two events.

**Comment by aszlig** [comment]
@volth: You don't need to alter the executable for that, or is there an intermediate `execve`?

**Comment by aszlig** [comment]
The reason why I'm not a fan of this is because if someone has that enabled, results could differ between Nix builds and outside, so we might need to ask another question when supporting people like "did you check whether `environment.ld-linux` is disabled?" - and who knows how many people will enable this option once it gets merged...

**Comment by volth** [comment]
> results could differ between Nix builds and outside,

yes, I was just thinking about what should be inside Nix builds, but from the point that I will need `/lib64/ld-linux-x86-64.so.2` inside Nix build too, even in sandbox mode.
Because what that java software (`scalapb`) dropping is binaries of various versions of protobuf compiler...

so, probably, `environment.ld-linux` should be always `on` inside Nix builds, even if it is `off` outside (and the same for `/bin/sh` and `/usr/bin/env` which could be set to `null`)

**Comment by aszlig** [comment]
@volth: That would make it even more problematic because it could introduce glibc version conflicts if the package that has been built is for a newer version while it's using an older runtime version from `/lib`.

**Comment by volth** [comment]
Inside Nix build it could be `${glibc}/lib64/ld-linux-x86-64.so.2` using `glibc` from build inputs (and **off** if there is no `glibc` in build inputs)
And probably the same for `/bin/sh` -> `${bash}/bin/sh`

**Comment by volth** [comment]
Oh, there is already `--option extra-sandbox-paths`

**Comment by aszlig** [comment]
@volth: Hm, I probably don't quite get what your goal is with Nix and RTLD (it's also way past bedtime for me), but I was assuming you want RTLD to be available by default on all Nix machines. So yeah, if it's just for a quick hack then you could use `extra-sandbox-paths`, but I guess we're going off-topic now.

As for this PR, what about doing something similar to to FHSUserEnv and just bind-mount RTLD as a small wrapper, so it's like `run-ld` from above but with support for `execve`?

**Comment by volth** [comment]
> but I was assuming you want RTLD to be available by default on all Nix machines

No, only where a maven build runs, so 
 * on a workstation outside Nix and
 * on all machines inside Nix 

The second is doable by `extra-sandbox-paths`, but RTLD at a predictable location would be desirable too to avoid doing something like `
nix-build --option extra-sandbox-paths /lib64/ld-linux-x86-64.so.2=$(nix-build -E "import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/release-19.09.tar.gz).glibc")/lib64/ld-linux-x86-64.so.2` because a remote builder machine might not have `<nixpkgs>` - it builds compiled `.drv`)

The problem could be seen as two smaller (keeping aside the gamers which want /lib/ld-linux.so too for the reasons I cannot explain).

1. how to locate RTLD on a NixOS machine ?
It is not in `/lib`, it is not even in `/run/current-system`. It cannot be used in `patchelf --set-interpreter`. Any attempt to get to RTLD (including all you have proposed) requires support in system-wide configuration.

2. If we have to to something system-wide, why should it be hooking `execve` or placing RTLD into some NixOS-only place, why not to put RTLD to its legacy place in /lib then ?

**Comment by edolstra** [comment]
I've reverted this in 26aba55951a, see https://github.com/NixOS/nixpkgs/pull/78798 for discussion of a similar PR.

**Comment by dtzWill** [comment]
FWIW this change was noisy for me: seemed to complain about missing files/directories on (every?) `nixos-rebuild switch`?

Curious--why the change from `--ignore-fail-on-non-empty` to `-p || true`?

-----

Possibly related, looks like this option was broken for the past 12 years? Linky:
* https://lists.gnu.org/archive/html/bug-coreutils/2020-01/msg00029.html
* (thread continued) https://lists.gnu.org/archive/html/bug-coreutils/2020-02/msg00000.html

**Comment by volth** [comment]
> Curious--why the change from `--ignore-fail-on-non-empty` to `-p || true`?

It is not relevant to the topic, just small fix for the case of `environment.usrbinenv` gets flipped from false to true.
 `--ignore-fail-on-non-empty` does ignore, well, failure when `/usr/bin` is not empty, but in the case above `/usr/bin` does not exist. And it is the reason for `rm` (ant then `nixos-rebuild switch`) to fail

**Comment by volth** [comment]
Can someone with admin right put the PS back to OPEN or DRAFT state?
It has been reverted in `master` but remains a source for cherry-picking for those who like to see it in their nixpkgs forks, and its MERGED state prevents to work on it (for example to fix #79439)

**Comment by zimbatm** [comment]
I don't know that it's possible to do that with GitHub. Better to send another fresh PR, or store the code in another fork of nixpkgs?

**Comment by purkhusid** [comment]
@volth I've been testing this on my machine. Is there any way to make the linker find libraries outside the nixstores? E.g. I've symlinked gcc into /lib but the linker only searches in the nixstore. I'm trying to make this work without configuring LD_LIBRARY_PATH but having a hard time.

**Comment by volth** [comment]
@purkhusid try `patchelf --print-rpath executable-file`, it will show the paths where libraries are looked for (and `patchelf --set-rpath ...` to change)

**Pull request merged**
