### PR TITLE
arandr: 0.1.9 -> 0.1.10

### PR DESCRIPTION
**Pull request by endgame**
###### Motivation for this change

Closes #60456 - this PR does the version bump but we also need to add some deps and switch python version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Zer0-** [comment]
I built and ran arandr from this branch, looks good to me.

**Review by Zer0- — APPROVED** [review]

**Comment by c0bw3b** [comment]
Tested locally too and it works as intended.
It's missing some icons in the toolbar though, and it logs warnings
```shell
(arandr:32601): Gtk-WARNING **: 17:16:25.179: Error loading theme icon 'document-new' for stock: Icon 'document-new' not present in theme Adwaita
(arandr:32601): Gtk-WARNING **: 17:16:25.180: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita
(arandr:32601): Gtk-WARNING **: 17:16:25.180: Error loading theme icon 'document-save-as' for stock: Icon 'document-save-as' not present in theme Adwaita
```

**Comment by Zer0-** [comment]
c0bw3b, [this thread](https://github.com/NixOS/nixpkgs/pull/43150#issuecomment-450060363) regarding icons is relevant.

**Comment by Ma27** [comment]
Built and tested locally :+1: 
Also great that another package uses gtk3 and gets rid of python2!

> c0bw3b, this thread regarding icons is relevant.

We had a similar discussion in #53857, in the end I guess that it should be fine to install GNOME's icon themes globally.

**Comment by Ma27** [comment]
@endgame thanks!

**Comment by vbgl** [comment]
Global installation of the icon set ([as described in that discussion](https://github.com/NixOS/nixpkgs/pull/43150#issuecomment-450060363)) fixes the missing icons.

However, the GTK dialog boxes do not work: trying to open a file (through the Layout → Open menu or through the keyboard shortcut) results in a pathetic crash:

> (arandr:28747): GLib-GIO-ERROR **: 08:12:27.103: No GSettings schemas are installed on the system

**Comment by endgame** [comment]
Thanks @vbgl . I have tried to fix this in https://github.com/NixOS/nixpkgs/pull/61738 , are you able to test it?

**Pull request merged**
