### PR TITLE
opencv3: darwin compatibility

### PR DESCRIPTION
**Pull request by acowley**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The bulk of this change is the addition of darwin framework dependencies,
and that the 3rd party image format libraries all build from the OpenCV
source tree on darwin by default. We must manually prevent this, as
the in-tree OpenEXR library (at least) does not work properly.

The added bzip2 dependency when building contrib (a non-default option)
affects non-darwin systems, but is, I think, necessary for all
platforms.

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]

**Comment by acowley** [comment]
I just found an issue with install names that I may as well sort out in this PR.

**Comment by acowley** [comment]
And now it's ready!

**Comment by grahamc** [comment]
Not sure if you recent changes fixed this or not (rebuilding,) but:

```
[ 94%] Linking CXX shared library ../../lib/libopencv_videostab.dylib
[ 94%] Built target opencv_videostab
[ 94%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
[ 94%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/wobble_suppression.cpp.o
[ 94%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/stabilizer.cpp.o
Scanning dependencies of target opencv_python2
[ 95%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
/tmp/nix-build-opencv-3.1.0.drv-0/opencv-3.1.0-src/modules/python/src2/cv2.cpp:6:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
[ 94%] Linking CXX shared library ../../lib/libopencv_videostab.dylib
[ 94%] Built target opencv_videostab
[ 94%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
1 error generated.
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/build.make:176: modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3792: modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
builder for ‘/nix/store/0sjbgm1cs64z7ql7rvrhb6sk2saqxnjh-opencv-3.1.0.drv’ failed with exit code 2
error: build of ‘/nix/store/0sjbgm1cs64z7ql7rvrhb6sk2saqxnjh-opencv-3.1.0.drv’ failed
The invocation of "nix-build -A python35Packages.opencv3 -A opencv3 -A python27Packages.opencv3 /Users/graham/.nox/nixpkgs" failed```

**Comment by acowley** [comment]
No, I wouldn't expect them to help with that. Building with `enablePython = true;` works, so it's not totally hopeless. Before opening this PR, I had been using a more complicated OpenCV build against python3 and python27, but it was too tightly coupled to be useful outside of a carefully constructed environment.

One issue I've seen is that OpenCV wants Python2.7 to build with, and it scours the machine trying to find one. I'm trying a build now that unconditionally pulls in Python 2.7, so that the `python35Packages.opencv3` package can substitute itself in for the generic `pythonPackages` argument without interfering with the python-2.7 used during the build. We'll see if that works, but we should make this a separate PR since it wouldn't be darwin specific and other people would need to chime in.

**Comment by acowley** [comment]
@grahamc My test with building with two `pythonPackage`s seems to have worked. After changing the opencv3 package to support that, I was able to do,

```
nix-shell --pure -p python35Packages.opencv3
$ python3
Python 3.5.2 (default, Oct  1 2016, 17:04:44) 
[GCC 4.2.1 Compatible Clang 3.7.1 (tags/RELEASE_371/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.1.0'
>>> 
```

with the caveat that my `PYTHONPATH` had a python 2.7 reference that `--pure` didn't get rid of so I had to manually prune that off.

So my suggestion above works, but it does unconditionally pull `python27Packages` into the `opencv3` build.

**Comment by grahamc** [comment]
Hrmm.. I wonder if I'm misunderstanding. I also replicated the issue in just building opencv3.

**Comment by acowley** [comment]
Sorry for the confusion. What I suggested requires a separate change to the `opencv3` package. I'd like to get this current PR merged before opening that one, but you can try it out: here is the [definition](https://gist.github.com/acowley/97c528c8bf60ef561c968666c8230781) I'll PR after this one to see if there are objections.

**Comment by acowley** [comment]
I was just rebuilding on a fresh pull from `nixpkgs-unstable` and had to cherry pick this branch to get `opencv3` building. Is there anything I can do to get it un-stuck?

**Comment by bjornfor** [comment]
@acowley: Why did you close?

**Comment by acowley** [comment]
@bjornfor: While this patch works for me, something else will be required for general use. 

@LnL7 suggested (on IRC) that the build only works when Python is enabled, but making Python a required input is perhaps not strictly necessary so some extra tinkering with the build steps is needed.

**Comment by LnL7** [comment]
I think it's probably fine to just enable it by default, or even remove the option.

**Pull request closed without merging**
