### PR TITLE
zig: init at 0.1.1

### PR DESCRIPTION
**Pull request by andrewrk**
###### Motivation for this change
Add zig compiler to NixOS

###### Things done

tested compiling something

cc @dtzWill

### CODE REVIEW

**Comment by joachifm** [comment]
The ci job fails with

> error: while querying the derivation named ‘zig-0.1.1’:
while evaluating the attribute ‘cmakeFlags’ of the derivation ‘zig-0.1.1’ at /tmp/nix-build-nixpkgs-tarball-18.03pre1234.abcdef.drv-0/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating the attribute ‘cc.libc.dev’ at /tmp/nix-build-nixpkgs-tarball-18.03pre1234.abcdef.drv-0/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:100:12:
attribute ‘dev’ missing, at /tmp/nix-build-nixpkgs-tarball-18.03pre1234.abcdef.drv-0/nixpkgs/pkgs/development/compilers/zig/default.nix:17:31

**Comment by andrewrk** [comment]
do you know why that error happened? it worked for me when I tested it. do you have a suggestion for how to fix? I just need the path to libc include directory.

**Comment by joachifm** [comment]
It only happens when evaling the tarball for darwin, so I guess `cc.libc` is not uniform across all the archs. You can try using `getDev stdenv.cc.libc` or `stdenv.cc.libc_dev` (the same thing), they should be more robust than accessing `.dev` directly.

**Comment by dtzWill** [comment]
LGTM!

When trying to build [Tetris](https://github.com/andrewrk/tetris) it's not obvious how to tell zig where to find libraries and such.

Would it make sense / be reasonable to (only in Nix-built zig, perhaps) patch Zig to understand NIX_CFLAGS_COMPILE and similar?

(I see it takes clang-like arguments such as `-isystem` and `-dirafter`, maybe a wrapper like cc-wrapper would be better?)

Just a thought and is less about packaging Zig (this PR) and more about packaging things written in Zig :).

**Comment by andrewrk** [comment]
@joachifm I changed it to `stdenv.cc.libc_dev`. It evaluates to the same expression on NixOS.

**Comment by andrewrk** [comment]
From the macos build log:

```
In file included from /tmp/nix-build-zig-0.1.1.drv-0/zig-0.1.1-src/deps/lld/COFF/Config.h:13:
In file included from /nix/store/pqwvpnqhskx1h1mkwcbf3713rdnzgg7f-llvm-5.0.0/include/llvm/ADT/StringRef.h:13:
/nix/store/pqwvpnqhskx1h1mkwcbf3713rdnzgg7f-llvm-5.0.0/include/llvm/ADT/STLExtras.h:20:10: fatal error: 'algorithm' file not found
#include <algorithm> // for std::all_of
 ^~~~~~~~~~~
```

Do we need to manually pass in libstdc++ or something? (the other platforms built successfully)

**Pull request merged**
