### PR TITLE
kde-frameworks: 5.38 -> 5.39

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Regular scheduled update. Haven't built everything yet as I need to try that out on a desktop instead of the anemic laptop.

Cc: @adisbladis @ttuegel 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ttuegel** [comment]
Just off the top of my head, we also need to cherry-pick this commit:
https://cgit.kde.org/ktexteditor.git/commit/?id=aeebeadb5f5955995c17de56cf83ba7166a132dd

**Comment by adisbladis** [comment]
@peterhoeg I actually started on this before you made the PR :) Have been running on frameworks 5.39 without any hiccups for the last few days.

**Comment by adisbladis** [comment]
@peterhoeg I saw that you added `digikam-5.7.0`, this was already merged in master (https://github.com/NixOS/nixpkgs/commit/27b7192726e565b463fd5af74842a6d0287fec48).

**Comment by peterhoeg** [comment]
Running ```nox-review wip``` so I should know more in a few hours. Thanks for your feedback @adisbladis and @ttuegel .

**Comment by peterhoeg** [comment]
> Have been running on frameworks 5.39 without any hiccups for the last few days.

digikam keeps failing when I run ```nox-review wip``` complaining about a missing ```gitversion.h```. Did you experience that @adisbladis ?

**Comment by bkchr** [comment]
@peterhoeg do you still have these problems? I tried `nix-build -A digikam` with your commits and that worked for me.

**Comment by peterhoeg** [comment]
It's ok now, so I'm merging this. Thanks @bkchr

**Pull request merged**
