### PR TITLE
llvmPackages_11: Fix cross-compilation for i686 

### PR DESCRIPTION
**Pull request by peperunas**
Expose `ix86` family builtins.

Co-Authored-By: John Ericson <git@JohnEricson.me>

###### Description of changes
This issue is part of a series of bugfixes to improve the i686 cross-compilation pipeline.

Tracking issue: https://github.com/NixOS/nixpkgs/issues/195967

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
This has to target staging due to the mass rebuilds.

**Comment by alyssais** [comment]
2000ae54295e601a08ec13ea5057557a30b9a13a has broken rust-bindgen:

```
% bindgen /tmp/bind.h
/tmp/bind.h:1:10: fatal error: 'stdlib.h' file not found
/tmp/bind.h:1:10: fatal error: 'stdlib.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/main.rs:52:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(bind.h just contains `#include <stdlib.h>`.)

**Comment by alyssais** [comment]
Proposing revert of the problematic commit in https://github.com/NixOS/nixpkgs/pull/200587.

**Comment by Ericson2314** [comment]
We should try to not let the LLVMs drift apart with this. We probably should also look into having upstream support the other `i.86` ones.

**Comment by alyssais** [comment]
Yeah, that was something else that worried me when I saw this PR. Changes like this need to be applied to all applicable LLVM versions.

**Pull request merged**
