### PR TITLE
jetbrains: 2024.1 -> 2024.1.1; plugins update

### PR DESCRIPTION
**Pull request by ryansname**
## Description of changes

Ran the `update_bin.py` script
```
jetbrains.gateway: 2024.1.1 -> 2024.1.1
jetbrains.goland: 2024.1 -> 2024.1.1
jetbrains.idea-community: 2024.1 -> 2024.1.1
jetbrains.idea-ultimate: 2024.1 -> 2024.1.1
jetbrains.pycharm-community: 2024.1 -> 2024.1.1
jetbrains.pycharm-professional: 2024.1 -> 2024.1.1
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
  - [x] Tested Intellij Ultimate
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pyrox0** [comment]
Could you please run the update script again? There's an update to `jetbrains.gateway` that's causing build failures(see #309383) that would be solved by this.

**Comment by ryansname** [comment]
@pyrox0 I reset and reran the script, the updates now include gateway 2024.1.1 -> 2024.1.1. Not sure if amending or pushing additional commits is preferred, so let me know if you want it to be a separate commit instead of the amend that I did

**Comment by pyrox0** [comment]
Amend is just fine! Testing these now, but everything looks good.

**Review by pyrox0 — APPROVED** [review]
Tested, things seem good to me.

**Comment by Garmelon** [comment]
It took me a bit to figure out why my `environment.systemPackages = [ pkgs.jetbrains.idea-community ];` version number did not match the version number from the package or this PR, but the reason is this:

https://github.com/NixOS/nixpkgs/blob/eb53d91b4388cf9d631ceeea5941824d5f1c09a6/pkgs/applications/editors/jetbrains/default.nix#L182

And this:

https://github.com/NixOS/nixpkgs/blob/eb53d91b4388cf9d631ceeea5941824d5f1c09a6/pkgs/applications/editors/jetbrains/source/default.nix#L5-L13

Compare the build number with the one listed here:

https://github.com/NixOS/nixpkgs/blob/eb53d91b4388cf9d631ceeea5941824d5f1c09a6/pkgs/applications/editors/jetbrains/bin/versions.json#L43-L50

Until somebody puts in the effort to update the source build, the easy fix is to switch to `pkgs.jetbrains.idea-community-bin`.

**Pull request merged**
