### PR TITLE
python.pkgs.thumbor: fix package

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Motivation for this change
Unbreak thumbor.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
I'm having a weird issue where `argparse` is included in `propagatedBuildInputs` for `thumbor` but `nix-build` is complaining that it cannot find it. Has anyone seen this before?

**Comment by changlinli** [comment]
Argparse got removed from nixpkgs. You're probably running into 49edb1138a0a2ba1f43d54859b4f4a263e99a679

**Comment by vaibhavsagar** [comment]
I don't understand, other packages seem to be using `argparse` in the same way too. How would I fix this?

**Comment by changlinli** [comment]
Depends on the exact error you're getting. Take a look at #26411 for an example of a package that had to change because of the `argparse` removal. Is the error you're getting actually coming from `nix-build` or from a Python build tool that `nix-build` calls?

**Comment by vaibhavsagar** [comment]
Thanks @changlinli, that was very helpful 😄

**Pull request merged**
