### PR TITLE
python-packages: new attrdict-2.0.0 package

### PR DESCRIPTION
**Pull request by desiderius**
A dict with attribute-style access.

### CODE REVIEW

**Comment by pSub** [comment]
Looks good to me, but could you remove the empty lines in the meta-section.

**Comment by desiderius** [comment]
Sure, sorry about that.

**Comment by pSub** [comment]
Thanks. If you squash your commits into one commit I will merge.

**Comment by desiderius** [comment]
Done, thank you for your patience.

**Comment by pSub** [comment]
You're welcome, thanks for your efforts.

**Pull request merged**
