### PR TITLE
Python: update numpy and scipy

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Regular updates. Unfortunately we cannot merge yet because there's quite a lot of test failures. Therefore, I think we need to wait for at least a Pandas update but possibly also a Cython update.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
why is it a mass rebuild?

**Comment by FRidh** [comment]
numpy causes also non-python packages to be rebuild.

**Comment by FRidh** [comment]
anyway, i push this eventually to staging

**Comment by FRidh** [comment]
I've pushed these commits to master because it doesn't look like staging is going to be merged anytime soon.

**Pull request closed without merging**
