### PR TITLE
tippecanoe: init at 1.34.3

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change

https://github.com/mapbox/tippecanoe

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sikmir** [comment]
@GrahamcOfBorg build tippecanoe

**Comment by risicle** [comment]
`nix-review` happy for me, macos 10.13 & non-nixos linux x86_64. Binaries appear to work.

**Comment by jtojnar** [comment]
@GrahamcOfBorg build tippecanoe

**Comment by jtojnar** [comment]
Would it make sense to run tests by setting `doCheck = true;`?

**Comment by sikmir** [comment]
> Would it make sense to run tests by setting `doCheck = true;`?

Added.

**Pull request merged**
