### PR TITLE
Add missing Plover deps

### PR DESCRIPTION
**Pull request by edef1c**
###### Motivation for this change
This fixes plover.dev crashing at startup due to missing `pkg_resources` and `qtbase`, and adds the optional `dbus-python` dependency to plover.stable.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @twey @KoviRobi

### CODE REVIEW

**Comment by KoviRobi** [comment]
- [x] plover.stable: add missing dbus dependency verified, it does indeed look for dbus and cannot find it.
- [x] plover.dev: add missing setuptools dependency. It is indeed a runtime dependency on setuptools, seems fine
- [ ] plover.dev: apply wrapQtApp doesn't seem to work for me, when cherry-picked onto nixpkgs-19.09 (not sure if something changed on master, will try but it probably requires me to compile stuff)
   ```
   wrapping `/nix/store/8pc09hxqw1rm7l1iqcypaza8w7ca50js-python3.6-plover-4.0.0.dev8/bin/plover'...
   /nix/store/7skkd4n1kmkl9dmql1219fqwxbjcas81-stdenv-linux/setup: line 100: wrapQtApp: command not found
   builder for '/nix/store/bbw7c8674mcsy3d5mgigx9558y7jvaii-python3.6-plover-4.0.0.dev8.drv' failed with exit code 127
   error: build of '/nix/store/bbw7c8674mcsy3d5mgigx9558y7jvaii-python3.6-plover-4.0.0.dev8.drv' failed
   ```

**Comment by KoviRobi** [comment]
After looking at openshot-qt, I have some success with https://github.com/KoviRobi/nixpkgs/commit/a41f4a7ed7201c9897913d2d30a7a1ff0771b7ff but the program seems to be double wrapped, perhaps it's worth looking at rapid-photo-downloader? Also https://github.com/NixOS/nixpkgs/issues/65399 seems relevant

**Comment by KoviRobi** [comment]
Also, and this is my mistake with 5a0665846ed4f3c742b3ff1c7336b0b387f180b7 but we should probably use buildPythonApplication not buildPythonPackage. Not sure if it should be a different PR or not.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
@KoviRobi Is correct in that you need to use https://github.com/KoviRobi/nixpkgs/commit/a41f4a7ed7201c9897913d2d30a7a1ff0771b7ff. The issue was `wrapQtAppsHook` wasn't added, and `mkDerivationWith` will add this automatically to `nativeBuildInputs`.

Also correct in that, we should be using `buildPythonApplication` and not `buildPythonPackage`. Unless it really is being used as a python module.

Lastly, we have pinned python version's here (specifically `python36Packages`).
Is this strictly needed? Or can we use `python2Packages` `&&` `python3Packages`.

**Comment by edef1c** [comment]
I skimmed a bunch of the files `rg -l python (rg -l dontWrapQtApps)` yielded, and found https://github.com/NixOS/nixpkgs/blob/f203d50d09052792866f926e7c2d3b3bf76d3388/pkgs/games/anki/default.nix, which yielded a better technique to avoid double-wrapping.

**Review by worldofpeace — APPROVED** [review]
LGTM, though I'm not sure if it's my setup but I cannot start it (dev version)
```
DisplayConnectionError: Can't connect to display ":0": No protocol specified
```
Gnome 3 x11

**Comment by edef1c** [comment]
> ```
> DisplayConnectionError: Can't connect to display ":0": No protocol specified
> ```

I wrote [a little Perl script to check if there were any environment variables that affected it](https://gist.github.com/edef1c/4dda02dbb9e7973700b7eb6e4c47f5de). I could reproduce this by running it with `rm -rf /tmp/home && mkdir /tmp/home && env -i DISPLAY=:0 HOME=/tmp/home result/bin/plover`, but not if I added `cp ~/.Xauthority /tmp/home` into the mix. I'm not sure how to reproduce this on anything remotely resembling a normal system.

**Review by worldofpeace — APPROVED** [review]
Couldn't reproduce aforementioned issue in a vm.
I believe my system's Xauthority is broken somewhat.

**Pull request merged**
