### PR TITLE
ati-drivers: package update

### PR DESCRIPTION
**Pull request by edwtjo**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
That's not a nice way to use `makeLibraryPath`. I'd suggest something like below, though it would still be better if someone checked running with the result before we merge it.
```nix
let # to fix highlighting
LD_LIBRARY_PATH = with xorg; stdenv.lib.makeLibraryPath
  [ libXrandr libXrender libXext libX11 libXinerama libSM libICE stdenv.cc.cc ];
```

**Comment by edwtjo** [comment]
Well the patch itself is fine, I'm running it now. I can cherry pick the better version after I've tried it out if you like.

**Comment by vcunat** [comment]
Probably best fix this properly. Note that `extraDRIlibs` is also broken, but it's possible it's not needed (anymore).

**Comment by edwtjo** [comment]
It seems we still need `extraDRIlibs`, I at least got most applications going by this small change. It still isn't good since GLX doesn't seem supported on my card anymore, I'll try to do some more digging.

**Comment by edwtjo** [comment]
Upgrading the driver didn't help my case so there is likely some problem with the builder as the card should be supported.

**Comment by edwtjo** [comment]
Fixed in 046ee5ac3ffbc7e5daa706bd3ad405bd30c7aad5

**Pull request closed without merging**
