### PR TITLE
Fix neovim.override

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

Follow up of  to fix people configuring neovim via `neovim.override`. 
It temporarily disables the `plugins` option introduced in https://github.com/NixOS/nixpkgs/pull/120445 until we have a better testing infra

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]
These tests don't really check whether the configuration itself works. I use the vader plugin to test syntax and indentation of vim-nix, wrapping these customised vim packages in a test that runs some basic check could catch if things don't get applied.

**Comment by teto** [comment]
@Lnl7 yes it is temporary to list usecases, i analyze the result manually. 
I had started https://github.com/NixOS/nixpkgs/pull/117285/ to check the infrastructure and I like how home-manager checks against a reference implementation https://github.com/nix-community/home-manager/blob/master/tests/modules/programs/neovim/plugin-config.nix

**Comment by LnL7** [comment]
Ah alright, well vader might be a bit overkill since there doesn't need to be all that much logic in vim itself. Checking whether a plugin is loaded or a variable is set can probably done straight from the cli.

As an example here's something I found to capture the output of a variable.
```sh
$ nvim -e +"let g:hello = 'Hello World'" +"redir>>/dev/stdout | echo g:hello | redir END" -scq!

Hello World
```

**Comment by thatsmydoing** [comment]
I tried this and it does not fix it for me. I use just the `neovim` package without overriding which I expect to not add a `-u <config file>` option to the wrapper and just use my neovim config in the standard directories.

**Comment by teto** [comment]
@thatsmydoing I introduced a `wrapRc` argument to make the wrapping of neovim-wunwrapped easier to use but it may have been set to a wrong value when using the legacyWrapper. I've pushed a possible fix. Could you share your config ?

**Comment by jmc-figueira** [comment]
I had neovim configured through the `programs.neovim` module and I can confirm that it also broke the configuration.

My config is as follows:

```Nix
    neovim = {
      enable = true;
      defaultEditor = true;
      configure = {
        packages.myVimPackage = with pkgs.vimPlugins; {
          start = [
            vim-airline
            vim-airline-themes
            vim-airline-clock
            # FixCursorHold missing
            # Fern missing
            # nerdfont
            # fern-renderer-nerdfont
            # fern-git-status
            # glyph-palette
            direnv-vim
            vim-fugitive
            vim-gitgutter
            vim-polyglot
            coc-nvim
            # coc-rust-analyzer
            # coc-clangd
            coc-java
            coc-vimtex
            vimtex
            vim-grammarous
            pear-tree
            tagbar
            vim-startify
            vim-crates
            # rust-doc missing
          ];

          opt = [
            onedark-vim
          ];
        };      
        
        # Missing the fern configs
        customRC = ''
          syntax on
          set termguicolors
          packadd! onedark-vim
          colorscheme onedark
          filetype plugin indent on
          set encoding=utf-8
          set title
          set number relativenumber
          set hidden

          augroup numbertoggle
            autocmd!
            autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
            autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
          augroup END

          au TermOpen * setlocal nonumber norelativenumber
          au BufEnter * if &buftype == 'terminal' | :startinsert | endif

                let g:vimtex_compiler_latexmk = {
                  \ 'options' : [
                  \    '-shell-escape',
                  \    '-verbose',
                  \    '-file-line-error',
                  \    '-synctex=1',
                  \    '-interaction=nonstopmode',
                  \ ],
                  \}

          let g:vimtex_view_method = 'zathura'

          let g:airline_powerline_fonts = 1
                let g:airline_theme='onedark'
                let g:airline_detect_modified=1
                let g:airline_detect_crypt=1
                let g:airline_detect_paste=1
                let g:airline_detect_spell=1
                let g:airline_detect_spelllang=1
                let g:airline_detect_iminsert=1
                let g:airline_inactive_collapse=1
                let g:airline#extensions#tabline#enabled = 1
                let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
                let g:airline#extensions#clock#format = '%a %d/%m/%Y %H:%M'

          if has('nvim')
            autocmd BufRead Cargo.toml call crates#toggle()
          endif

          nmap <silent> <Leader>t :TagbarToggle<CR>
        '';
      };
```

**Comment by teto** [comment]
@jmc-figueira I've just tested with this MR and your config worked fine. Make sure to pull the latest version.

**Comment by jmc-figueira** [comment]
Sorry to bother again, but, while I was able to successfully load my configuration again by using an override (with the package from master), I wasn't able to do so through the module (by setting `package = master-pkgs.neovim-unwrapped`). It is a minor issue, all things considered, but I thought I'd better report it anyhow.

**Pull request merged**
