### PR TITLE
linux-firmware: remove FOD

### PR DESCRIPTION
**Pull request by flokli**
This being a FOD seems to only have historical reasons. Remove the source.nix file, as well as the custom update script, and FOD.

Simply making this a normal input-addressed derivation, with a version being interpolated makes this easy to update with update-source-version.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
It being a FOD reduces the amount of rebuilds across arches somewhat significantly. We should be a little careful here.

**Comment by flokli** [comment]
> It being a FOD reduces the amount of rebuilds across arches somewhat significantly. We should be a little careful here.

Can you elaborate? `linux-firmware` itself isn't really consumed by any other derivations, except in things like ISO images etc - which usually change all the time anyways.

**Comment by wegank** [comment]
> It being a FOD reduces the amount of rebuilds across arches somewhat significantly. We should be a little careful here.

There are less than 10 rebuilds, though, so I think the change is fine.

**Comment by Mic92** [comment]
So the saving would be 3 instead of 1 copy if we had the FOD in our binary cache.
Uncompressed it's 

```
du -sh --apparent-size ./results/linux-firmware/
1.1G    ./results/linux-firmware/
```

and compressed: `376M    ./archive.tar.xz`

**Comment by flokli** [comment]
No, assuming the store path contents are the same, all three store paths would have the same NarHash, and point to the same NAR.

**Comment by Mic92** [comment]
Well. In that case, we should just avoid the complex code and merge this pull request.

**Review by fpletz — APPROVED** [review]

**Pull request merged**
