### PR TITLE
nixos/systemd-stage-1: include modprobe confg in initrd

### PR DESCRIPTION
**Pull request by oxalica**
###### Description of changes

We are doing so [currently](https://github.com/NixOS/nixpkgs/blob/9547123258f69efd92b54763051d6dc7f3bfcaca/nixos/modules/system/boot/stage-1.nix#L392-L394), to make `boot.extraModprobeConfig`, `boot.blacklistedKernelModules` and etc applied on drivers loaded in initrd stage.

The implementation seems ugly, but accessing `config.environment.etc."modprobe.d/nixos.conf"` while it's not set would cause evaluation error. `null` is also invalid in that place.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Shawn8901** [comment]
i have copied the respective line of code to my own flake, and it seems to work fine. Thanks for bringing back my modprobe.conf :)
About the check: if i understand it right the modprobe file we are loading here is created in any case, [if we are not running a container](https://github.com/NixOS/nixpkgs/blob/c9389643ae662834fd584ffa1898dc52956e1fba/nixos/modules/system/boot/modprobe.nix#L42), and that should not need a initrd, or am i wrong?
So is the null link more a theoretical thing, or how you archived it that its not present?

btw: i am just an end-consumer here and asking stupid questions :grin:

**Comment by oxalica** [comment]
> About the check: if i understand it right the modprobe file we are loading here is created in any case, [if we are not running a container](https://github.com/NixOS/nixpkgs/blob/c9389643ae662834fd584ffa1898dc52956e1fba/nixos/modules/system/boot/modprobe.nix#L42), and that should not need a initrd, or am i wrong?
> So is the null link more a theoretical thing, or how you archived it that its not present?

Technically, users could override it to be empty I think? And I don't want to couple the initrd module and the modprobe module. The conditions in two files might change over time.

**Comment by flokli** [comment]
@oxalica is there a way you could cover this with a VM test somehow?

**Comment by oxalica** [comment]
@flokli The test is added. It would fail without this PR.

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
