### PR TITLE
vimPlugins: add vim-molokai-delroth and vim-jinja-languages

### PR DESCRIPTION
**Pull request by seirl**
###### Description of changes

1. Added the following vim plugins:

  - https://github.com/delroth/vim-molokai-delroth -> a custom vim colorscheme with accessibility fixes
  - https://github.com/seirl/vim-jinja-languages -> a syntax plugin for jinja templates of various programming languages, not just HTML.

2. Removed an unused vim plugin from a deleted GitHub repository (was required for the update script to run): https://github.com/jose-elias-alvarez/minsnip.nvim

3. Updated generated.nix following the procedure in https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs-adding-new-plugins-to-nixpkgs
4. Updated nvim-treesitter following the same procedure

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 235055` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.sg-nvim</li>
  </ul>
</details>
<details>
  <summary>106 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.autoclose-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-lua</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.firenvim</li>
    <li>vimPlugins.floating-input-nvim</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lspsaga-nvim-original</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.monokai-pro-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-dart</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.neotest-rspec</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-parsers.corn</li>
    <li>vimPlugins.nvim-treesitter-parsers.gleam</li>
    <li>vimPlugins.nvim-treesitter-parsers.ocamllex</li>
    <li>vimPlugins.nvim-treesitter-parsers.php</li>
    <li>vimPlugins.nvim-treesitter-parsers.scala</li>
    <li>vimPlugins.nvim-ts-rainbow2</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.other-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-manix</li>
    <li>vimPlugins.term-edit-nvim</li>
    <li>vimPlugins.tint-nvim</li>
    <li>vimPlugins.tmux-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-fetch</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-jinja-languages</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-molokai-delroth</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.wiki-vim</li>
  </ul>
</details>

**Comment by seirl** [comment]
Ah, thanks for catching that, for some reason I missed this in the report. I fixed the hash that was making it break, here's the new report:

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>107 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.autoclose-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-lua</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.firenvim</li>
    <li>vimPlugins.floating-input-nvim</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lspsaga-nvim-original</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.monokai-pro-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-dart</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.neotest-rspec</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-parsers.corn</li>
    <li>vimPlugins.nvim-treesitter-parsers.gleam</li>
    <li>vimPlugins.nvim-treesitter-parsers.ocamllex</li>
    <li>vimPlugins.nvim-treesitter-parsers.php</li>
    <li>vimPlugins.nvim-treesitter-parsers.scala</li>
    <li>vimPlugins.nvim-ts-rainbow2</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.other-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.sg-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-manix</li>
    <li>vimPlugins.term-edit-nvim</li>
    <li>vimPlugins.tint-nvim</li>
    <li>vimPlugins.tmux-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-fetch</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-jinja-languages</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-molokai-delroth</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.wiki-vim</li>
  </ul>
</details>

**Comment by figsoda** [comment]
I've manually added back minsnip.nvim for backwards compatibility, I'll merge this when CI is done

**Comment by seirl** [comment]
> I've manually added back minsnip.nvim for backwards compatibility, I'll merge this when CI is done

Thanks. Maybe it would be worth adding a note in the README that 404 repositories should be added as overrides?

**Comment by figsoda** [comment]
I think the goal is for the update script to be able to handle things like this

**Review by figsoda — APPROVED** [review]

**Pull request merged**
