### PR TITLE
clightning: 0.11.2 -> 0.12.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Description of changes

- version update: https://github.com/ElementsProject/lightning/releases/tag/v0.12.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
cc @jonasnick @erikarvstedt for testing

**Comment by erikarvstedt** [comment]
The build fails on `x86_64-linux` ([build log](https://gist.github.com/f1b9df83480a9c3545c6dc8edf59f85a)).

**Comment by prusnak** [comment]
@erikarvstedt seems that the build failed because of the network error in the CI

**Comment by prusnak** [comment]
@GrahamcOfBorg build clightning

**Comment by erikarvstedt** [comment]
The build is generally broken on Linux, I can reproduce it locally.

**Comment by erikarvstedt** [comment]
Yes, the log is from my local build.

**Comment by prusnak** [comment]
> Yes, the log is from my local build.

That's really weird that the network error is reproducible.

**Comment by erikarvstedt** [comment]
On Linux, Nix builds run in a sandbox where network access is unavailable.

**Comment by prusnak** [comment]
> On Linux, Nix builds run in a sandbox where network access is unavailable.

Ah, that makes sense. I build aarch64-linux in Docker on macOS.

**Comment by prusnak** [comment]
I removed the rust-related stuff in de2ae287d56322cc8ab53e23563bc840a4ffa1dc so we can update the base package first and we can deal with rust-related build failures later.

**Comment by erikarvstedt** [comment]
The build works now.
It seems that clightning now ships with plugins that are built with rust. These should be built with `buildRustPackage`, which uses a separate fixed output drv to fetch cargo deps.

**Comment by prusnak** [comment]
> It seems that clightning now ships with plugins that are built with rust.

Yes, I am aware of this. Let's address this in the subsequent PRs. I tried several approaches using `rustPlatform.buildRustPackage` and `cargoDeps = rustPlatform.fetchCargoTarball { }` but ultimately failed and run out of time I wanted to give to this update PR.

**Review by jonasnick — APPROVED** [review]
Works for me on Arch Linux. The man pages appear in the `result/` directory as in previous versions of clightning and are readable with `man`. Addressing the rust issue in subsequent PRs sgtm.

**Pull request merged**
