### PR TITLE
leftwm: 0.4.2 -> 0.5.1

### PR DESCRIPTION
**Pull request by adamcstephens**
Diff: https://github.com/leftwm/leftwm/compare/0.4.2...0.5.1

Changelog: https://github.com/leftwm/leftwm/blob/0.5.1/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adamcstephens** [comment]
Version is reported incorrectly as 0.4.2 still. Reported upstream https://github.com/leftwm/leftwm/issues/1177

**Comment by VuiMuich** [comment]
Hi, thanks for being so quick. I was also preparing a PR as I wanted to add myself as a package maintainer, if you like you could add me (using `vuimuich`).
Also I thought of changing `sha256` to `hash` and `cargoSha256` to `cargoHash` as this seems to be the preferred way, when the hash string is in form of `sha256-..` and I wanted to install the man page that can be found in `leftwm/doc/leftwm.1` but for some reason I got eval issues in local builds and hadn't yet time to sort things out.

**Review by yanganto — APPROVED** [review]

**Comment by adamcstephens** [comment]
@VuiMuich I addressed most of your suggestions. I'll leave updating maintainers to you though. :)

**Comment by VuiMuich** [comment]
> @VuiMuich I addressed most of your suggestions. I'll leave updating maintainers to you though. :)

Nice! Thanks.
Just one thing, to keep it in sync with the main release (see upstream issue report leftwm/leftwm#1177) I'd suggest to do directly 0.4.2 -> 0.5.1

**Comment by adamcstephens** [comment]
Looks good now @VuiMuich !

**Comment by VuiMuich** [comment]
Thanks! Thes PR here looks good to me as well now.

**Review by yanganto — APPROVED** [review]

**Pull request merged**
