### PR TITLE
nixos/journalwatch: add package option

### LINKED ISSUE #314365: Build failure: Journalwatch NixOS module
### Steps To Reproduce

1. Add `services.journalwatch.enable = true;` to the NixOS configuration.
2. Use nixos-rebuild to build NixOS.

### Build log

```
       error: attribute 'journalwatch' missing

       at /nix/store/ahw94rjmyxb9ylz5kzxmj47g88srxhbr-source/nixos/modules/services/logging/journalwatch.nix:243:24:

          242|         StateDirectoryMode = "0750";
          243|         ExecStart = "${pkgs.python3Packages.journalwatch}/bin/journalwatch mail";
             |                        ^
          244|         # lowest CPU and IO priority, but both still in best-effort class to prevent starvation

```

### Additional context

According to the Nixpkgs search, there should be the packages python312Packages.journalwatch and python311Packages.journalwatch

in the Nixpkgs unstable branch. I just checked the master branch and I haven't been able to find those. I could only find pkgs.journalwatch.

That's fine, but then it means the journalwatch module needs to be updated. Perhaps this is related to #313450

### Metadata

I won't add the Metadata since I'm in the process of building NixOS, so the result would be incorrect anyway.

I'm on Nixpkgs commit 1388fbc714d01ec8280585c31fb6073a8fa590d6

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Fixes #314365.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
marked for backport as the packaging change was made before the branchoff

**Review by Aleksanaa — APPROVED** [review]

**Comment by fabaff** [comment]
@eclairevoyant, thanks for the fix.

**Comment by emmanuelrosa** [comment]
This works.

Thanks :)

**Review by matthiasbeyer — APPROVED** [review]
I ran into https://github.com/NixOS/nixpkgs/issues/314365 as well and this looks like a fix for it, yes!

**Pull request merged**
