### PR TITLE
eva: 0.3.0 -> 0.3.0-2, add figsoda as a maintainer

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

I'm not sure why the version didn't change, but this is a new version as both the github tag and crate version have recent updates

switched to fetchCrate because github version has outdated Cargo.lock

https://github.com/NerdyPepper/eva

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Calling that `0.3.0 -> 0.3.0` is really confusing. If you apply these kinds of changes, please actually describe what you do in your commit message.

**Review by nrdxp — APPROVED** [review]
Nice catch, thanks. As @Ma27 points out though, if you could maybe just rename the commit message, and maybe even the package version something like `0.3.0-2` or something similar.

**Comment by figsoda** [comment]
> 0.3.0-2

looks like this is what arch is doing too, I will update the version to 0.3.0-2

**Comment by nrdxp** [comment]
> looks like this is what arch is doing too

yeah I shameless stole the convetion from arch, probably shoulda mentioned that :sweat_smile:

**Review by nrdxp — APPROVED** [review]

**Pull request merged**
