### PR TITLE
nixos/sudo: default rule should be first

### LINKED ISSUE #87555: extraRules is overridden by default value
**Describe the bug**
In Nix configuration file, user’s specification of [`security.sudo.extraRules`](https://nixos.org/nixos/options.html#security.sudo.extrarules) will be overridden by the default rules. Default is specified in

https://github.com/NixOS/nixpkgs/blob/29d0e684afcc1a3f4d5a5c60a483ba4c719c73f6/nixos/modules/security/sudo.nix#L176-L180

**To Reproduce**
1. Set any rule in `extraRules`.
2. Apply the rules by running `nixos-rebuild switch` 

**Expected behavior**
In `/etc/sudoers`, the rules I define should be after the default rules.

**Screenshots**
I see that my rules are before the default rules, so it has lower precedence.

**Additional context**
I found this issue when installing from scratch.

**Notify maintainers**
No maintainer found. @lschuermann made #33905 which might be related.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1795.d6c1b566b77 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - security
```

### PR DESCRIPTION
**Pull request by cole-h**
In /etc/sudoers, the last-matched rule will override all
previously-matched rules. Thus, make the default rule show up first (but
still allow some wiggle room for a user to `mkBefore` it), before any
user-defined rules.

###### Motivation for this change

Addresses #87555. I'll backport this to 20.03 after this gets merged (or whoever merges this can take care of that for me; I don't mind either way, but that might be easier than waiting for me to follow up).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by elohmeier — APPROVED** [review]

**Comment by lschuermann** [comment]
@grahamcofborg test sudo

**Review by lschuermann — APPROVED** [review]
Looks good. Handling sudo rules is tricky, this achieves the expected behavior.

**Comment by emilazy** [comment]
Could something be added to the test for this, say by setting `extraRules` to something that overrides the default and checking that `sudo(1)` behaves accordingly?

**Comment by cole-h** [comment]
If somebody more familiar with `sudo` and its configuration would like to write that test case in a follow-up, I'd be delighted. I tried my hand at it and failed, but I'd like to get this merged sooner rather than later so as to resolve the linked issue.

Sorry it took me so long to get back to this.

**Pull request merged**
