### PR TITLE
cbfstool: init at git-2015-07-09

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
Depends on PR #8722.

**Comment by lethalman** [comment]
Not sure about the `flex -> lex` symlink. What about instead patching this package?

**Comment by ts468** [comment]
I just found that, e.g., Debian has a symlink flex -> lex, and so I thought it might be of general interest. But I'm absolutely fine with patching cbfstool as well if that is preferred!

**Comment by lethalman** [comment]
@ts468 given it's the only package assuming there's a "lex" binary, yes I'd say patch only this package.

**Pull request merged**
