### PR TITLE
bazel: 0.22.0 -> 0.23.2

### PR DESCRIPTION
**Pull request by uri-canva**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by uri-canva** [comment]
Not sure if this is going to be any different from #56587, worth a shot.

**Review by marsam — APPROVED** [review]

**Comment by xeji** [comment]
@GrahamcOfBorg build bazel bazel-deps bazel-watcher

**Comment by uri-canva** [comment]
Looks like the same issue as the other PR.

**Comment by uri-canva** [comment]
Will close the PR to not give the impression I'm working on this at the moment, might try at some point. cc @groodt

**Comment by groodt** [comment]
Thanks @uri-canva 

For anybody interested. I've tested using this derivation on my own fairly large build on linux and Darwin and it currently works as expected.

Got a link to the latest error for me to confirm if I can reproduce? On my Darwin machine, it currently builds, but I've never tried sandbox. I'll have to give it a try.

**Comment by uri-canva** [comment]
See the checks tab.

**Comment by uri-canva** [comment]
This probably would have been fine on hydra, see https://github.com/NixOS/nixpkgs/pull/58147 on why it was failing on ofborg.

**Comment by Profpatsch** [comment]
We merged 0.24.

**Pull request closed without merging**
