### PR TITLE
pythonPackages.spyder_3: drop

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 127846` at 8e34ca49 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d3c6cf339950f9553cdbef12cddd15f2">cq-editor</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by marcus7070** [comment]
This will force nixpkgs to drop CQ-editor and CadQuery. That has to be done eventually, but I was hoping to wait until they broke.

**Comment by marcus7070** [comment]
CQ-editor fails:

```
> ./result/bin/cq-editor -h                                                                                                                                                            
Traceback (most recent call last):
  File "/nix/store/c4n390mriwxgpl4lv4cf9kcm6clypvq0-cq-editor-0.1.1/bin/.cq-editor-wrapped", line 6, in <module>
    from cq_editor.__main__ import main
  File "/nix/store/c4n390mriwxgpl4lv4cf9kcm6clypvq0-cq-editor-0.1.1/lib/python3.7/site-packages/cq_editor/__main__.py", line 12, in <module>
    from .main_window import MainWindow
  File "/nix/store/c4n390mriwxgpl4lv4cf9kcm6clypvq0-cq-editor-0.1.1/lib/python3.7/site-packages/cq_editor/main_window.py", line 7, in <module>
    from .widgets.editor import Editor
  File "/nix/store/c4n390mriwxgpl4lv4cf9kcm6clypvq0-cq-editor-0.1.1/lib/python3.7/site-packages/cq_editor/widgets/editor.py", line 1, in <module>
    from spyder.widgets.sourcecode.codeeditor import  CodeEditor
ModuleNotFoundError: No module named 'spyder.widgets.sourcecode'
```

checkPhase could probably be `cq-editor -h`, it's rudimentary but at least would have picked this one up.

I'll see if I can make a patch that lets us use spyder 4.

**Comment by marcus7070** [comment]
> checkPhase could probably be `cq-editor -h`, it's rudimentary but at least would have picked this one up.

I'm wrong, checkPhase can not be `cq-editor -h`, that still requires graphics.

I don't have write access to your fork, so here's a patch that will let v0.1.1 use spyder4.
[spyder4.patch.txt](https://github.com/NixOS/nixpkgs/files/6699028/spyder4.patch.txt)

**Comment by dotlambda** [comment]
> I don't have write access to your fork, so here's a patch that will let v0.1.1 use spyder4.

Thanks, I'll use that for now. CQ-editor should be updated to 0.2 though.

**Comment by dotlambda** [comment]
Did you obtain the patch from some upstream commit so we can use `fetchpatch`?

**Comment by marcus7070** [comment]
The changes needed for spyder4 compatibility came from here: https://github.com/CadQuery/CQ-editor/pull/195

That didn't apply cleanly so I wrote that patch myself.

Regarding CQ-editor v0.2, that version replaces pythonocc with OCP, which we don't have in nixpkgs. I do have it in a flake, which I think is the more appropriate place for it: https://github.com/marcus7070/cq-flake

Are you using CQ or is this just housekeeping?

**Comment by dotlambda** [comment]
> Regarding CQ-editor v0.2, that version replaces pythonocc with OCP, which we don't have in nixpkgs. I do have it in a flake, which I think is the more appropriate place for it: https://github.com/marcus7070/cq-flake

Since we do have CQ-editor in Nixpkgs, I think it should be updated or removed.



> Are you using CQ or is this just housekeeping?

Just housekeeping.

**Review by marcus7070 — APPROVED** [review]

**Pull request merged**
