### PR TITLE
nixos/mysql: declarative users & databases

### PR DESCRIPTION
**Pull request by florianjacob**
using Unix socket authentication, ensured on every rebuild.

###### Motivation for this change
I want to be able to declaratively manage the MySQL / MariaDB databases and users I need for the standard web apps like wordpress, nextcloud, piwik et cetera. This can be used by end users as well as package maintainer.

This helps #29031 by allowing to easily create a MySQL user for backing up, with reduced permissions.

This goes in the direction of and could supersede #6963 , but with scope reduced to local, Unix socket authenticated users.

I tried to circumvent the issue of un-synchronized state between nix configuration and actual databases by calling this **ensure**Databases / **ensure**Users and making it clear that this only ensures the databases and users are *there*, but does nothing to delete or rename databases and users or to reduce permissions that were once given. This will be up to the user, to prevent e.g. accidental deletion of databases and generally breaking things.

(Also, I don't even know how the state of which databases existed before and after rebuilds could be diffed and updated accordingly.)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by davidak** [comment]
:+1: Looks good, thanks!

**Review by fadenb — APPROVED** [review]
LGTM
~~I did not yet test it on a system with existing DBs and users but will try to to that later today.~~
Works exactly as expected :+1:

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
Thanks!

**Comment by danbst** [comment]
I don't use MySQL, but I've stumbled on this:

```
... IDENTIFIED WITH ${if mysql == pkgs.mariadb then "unix_socket" else "auth_socket"};"
```

I think it's a bit flaky check. What if I use `mariadb` from nixpkgs-unstable, but rest of the system is nixos-17.09? It will be detected as `mysql`. Perhaps better to check `(builtins.parseDrvName (mysql.name)).name == "mariadb"`

**Comment by florianjacob** [comment]
@danbst you're totally right, did not think about that case. Your proposal with parseDrvName sounds much better, and should be a drop-in replacement for the current condition. Do you want to pose the PR, or should I do it?

**Comment by ravloony** [comment]
This is cool. I'm going to use this in https://github.com/NixOS/nixpkgs/pull/31475 instead of the stateful workaround I have now.

**Comment by florianjacob** [comment]
@ravloony thank you! Yes, looks like a good fit. And more usage examples in NixOS services apart from [mysql-backup](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/backup/mysql-backup.nix#L87) will probably help more people discovering and adopting this. 😄

**Comment by ravloony** [comment]
@florianjacob Done. Feel free to have a look and see if there is anything I could do better.

**Pull request merged**
