### PR TITLE
qt5: 5.15.0 -> 5.15.2

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Qt5.15.1 brought 400 bug fixes and Qt5.15.2 anoyther batch of 176, so let's take advantage of it.

Update done using the script in maintainers/scripts

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Follow-up to https://github.com/NixOS/nixpkgs/pull/102216. Please see the comments there.

**Comment by poelzi** [comment]
I have regular crashes in some programs because auf 5.15.0 regressions.

**Comment by freezeboy** [comment]
Maybe it is safer to close this one

**Comment by unclechu** [comment]
@freezeboy Sorry, could you clarify please why did you close it?

**Comment by freezeboy** [comment]
As the other pr is struggling with the patches i guess this one is not worth the effort

**Comment by poelzi** [comment]
It does not make sense to go to 5.15.1 when 5.15.2 is already available.

**Comment by ttuegel** [comment]
Qt 5.15.1 has some serious regressions (reported by Plasma upstream) and I would strongly prefer to go straight to Qt 5.15.2.

**Comment by freezeboy** [comment]
@ttuegel Ok for me but I can't run nixpkgs-review, so if someone can check this version is ok, it will help.

I rebased on my machine and started a build of qt5 to be sure that at least the lib is building

**Comment by ttuegel** [comment]
> I can't run nixpkgs-review, so if someone can check this version is ok, it will help.

I'm building now. The staging branch is badly broken right now, so I cherry-picked onto master for testing. If it works there, I'd say it's good enough to go into staging.

**Comment by poelzi** [comment]
Whats the progress here ? I have regular crashes due this buggy qt 5.15.0 and I start to get really annoyed by the slow progress of getting patch level updates into the tree.
Despite the fact I love nix, this is an perfect example why major distributions like ubuntu are way more stable and enterprise ready then NixOS and I can only suggest it with half a heart and will mention pain like this will come to everyone interested in nixos..... unfortuntelly :-/

**Comment by freezeboy** [comment]
I didn't receive any feedback from the build process, so still waiting in case there is a problem.

**Comment by ttuegel** [comment]
I'm going to close this in favor of #106118. We should consolidate our efforts there because it is the most complete of the Qt 5.15 update pull requests.

**Pull request closed without merging**
