### PR TITLE
v2ray: 4.37.3 -> 4.38.3

### PR DESCRIPTION
**Pull request by servalcatty**
###### Motivation for this change
4.37.3 -> 4.38.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by karolchmist** [comment]
Result of `nixpkgs-review pr 121500` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>v2ray</li>
  </ul>
</details>

**Review by karolchmist — APPROVED** [review]

**Comment by karolchmist** [comment]
It builds and I could run `v2ray` which produced this output:
```
[nix-shell:~/.cache/nixpkgs-review/pr-121500]$ v2ray
V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.4 linux/amd64)
A unified platform for anti-censorship.
2021/05/13 17:42:39 Using config from STDIN
2021/05/13 17:42:39 [Info] main/jsonem: Reading config: stdin:
```

Not sure how to test it more.... But it seems to work fine.

**Comment by servalcatty** [comment]
@karolchmist 
> Not sure how to test it more.

There is a test `v2ray.tests.simple-vmess-proxy-test` which covers a common use case. When it builds, it should work.

**Comment by karolchmist** [comment]
> @karolchmist
> 
> > Not sure how to test it more.
> 
> There is a test `v2ray.tests.simple-vmess-proxy-test` which covers a common use case. When it builds, it should work.

Nice, it worked :+1: Some last lines:

```
machine: waiting for TCP port 80
machine # Connection to localhost (::1) 80 port [tcp/http] succeeded!
(0.10 seconds)
machine: waiting for TCP port 1080
machine # Connection to localhost (127.0.0.1) 1080 port [tcp/socks] succeeded!
(0.02 seconds)
machine: must succeed: curl --fail --max-time 10 --proxy http://localhost:1080 http://localhost
machine # [    6.911231] v2ray-start[760]: 2021/05/14 06:08:52 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
(0.08 seconds)
(7.43 seconds)
test script finished in 7.53s
cleaning up
killing machine (pid 10)
(0.00 seconds)
/nix/store/2qpzvpdp1mp51zxqxiwjmq0hy69igzr4-vm-test-run-v2ray
```

**Pull request merged**
