### PR TITLE
xorg: allow overriding via overrideScope' for 18.09

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Backport of #45328. Good so any other xorg backports during 18.09's tenure don't hit major merge conflicts. No hashes changed.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ericson2314** [comment]
I don't understand this failure. Don't no-aliases checks post-date 18.03?

**Comment by Ericson2314** [comment]
CC @thefloweringash

**Comment by samueldr** [comment]
@Ericson2314 eval issues fixed in #48692; there were fixes in master that were not present in 18.09; and the check was just recently merged in ofborg.

**Comment by Ericson2314** [comment]
Thanks!!

**Comment by Ericson2314** [comment]
From Only inter https://gist.github.com/GrahamcOfBorg/c2bd575b88acf19b42b364f6738a3b09 the only real change is due to `xeyes` getting an extra `xproto` dep. Seems fine to me.

**Pull request merged**
