### PR TITLE
taskell: 1.3.2 -> 1.4.2

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

https://github.com/smallhadroncollider/taskell/issues/33

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Works here! Should we bump to 1.4.2 while we're at it?

**Comment by matthiasbeyer** [comment]
lol. Yes, I'm on it.

**Comment by matthiasbeyer** [comment]
hmh,... having problems with cache.nixos.org SSL cert... maybe a bit later...

**Comment by BenBals** [comment]
##### Reviewed points

- [ ] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on Linux nixos-beb 4.19.34 #1-NixOS SMP Fri Apr 5 20:33:17 UTC 2019 x86_64 GNU/Linux
- [x] executables tested on Linux nixos-beb 4.19.34 #1-NixOS SMP Fri Apr 5 20:33:17 UTC 2019 x86_64 GNU/Linux
- [ ] `meta.description` is set and fits guidelines
- [ ] `meta.license` fits upstream license
- [ ] `meta.platforms` is set
- [ ] `meta.maintainers` is set
- [ ] build time only dependencies are declared in `nativeBuildInputs`
- [ ] source is fetched using the appropriate function
- [ ] phases are respected
- [ ] patches that are remotely available are fetched with `fetchpatch`

##### Possible improvements

##### Comments

**Comment by matthiasbeyer** [comment]
taskell 1.4.2 fails for me:

```
rm ~/.config/taskell/*
./result/bin/taskell 
taskell: /home/user/.config/taskell/config.ini: hGetContents: invalid argument (invalid byte sequence)
```

Reverting latest change.

**Comment by BenBals** [comment]
The current state of the PR builds and executes fine for me. (Though I have no actual taskell data to test it on. It creates a new file and edits it fine.)

**Comment by matthiasbeyer** [comment]
OK, maybe problems with my test VM

**Comment by matthiasbeyer** [comment]
It was indeed an error in my setup, some weird encoding stuff.

Ready to merge from my POV.

**Comment by matthiasbeyer** [comment]
@GrahamcOfBorg build taskell

**Comment by dtzWill** [comment]
(1.4.3? ^_^)

**Comment by matthiasbeyer** [comment]
Oh damn. Okay, maybe I have time tomorrow. Can we please merge this, I'll open a new PR for the next update asap.

**Comment by dtzWill** [comment]
Sure!

**Pull request merged**
