### PR TITLE
blobfuse: 1.0.1-RC-Preview -> 1.0.2

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by jbgi** [comment]
could we backport the package to 18.03?

**Comment by Mic92** [comment]
Backport should be ok. This package was added after the nixos release.

**Comment by Mic92** [comment]
@GrahamcOfBorg build blobfuse

**Comment by Mic92** [comment]
backport:

[detached HEAD 1fbf13265e4] blobfuse: init at 1.0.1-RC-Preview (#39073)
 Author: Jean-Baptiste Giraudeau <jb@giraudeau.info>
 Date: Sat Apr 28 00:58:40 2018 +0200
 3 files changed, 30 insertions(+)
 create mode 100644 pkgs/tools/filesystems/blobfuse/default.nix
[detached HEAD 758144ea44c] blobfuse: 1.0.1-RC-Preview -> 1.0.2
 Author: Jean-Baptiste Giraudeau <jb.giraudeau@lombardodier.com>
 Date: Mon May 7 09:31:02 2018 +0200
 1 file changed, 3 insertions(+), 3 deletions(-)

**Pull request merged**
