### PR TITLE
Pantheon updates 2020-07-07

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
This has a side effect of changing the pantheon session to start the accessibility service not using the xdg autostart.

@ofborg test pantheon
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FeddiGhani** [comment]
Make some clean startup loading screen for nixOS

**Comment by worldofpeace** [comment]
@ofborg test pantheon

**Comment by worldofpeace** [comment]
> Make some clean startup loading screen for nixOS

pardon?

**Comment by worldofpeace** [comment]
appcenter update depends on https://github.com/NixOS/nixpkgs/pull/92204

**Comment by worldofpeace** [comment]
elementary-files update is omitted because it depends on https://github.com/NixOS/nixpkgs/pull/92592

**Comment by worldofpeace** [comment]
Going to pass on the appcenter update because libhandy update is difficult atm https://github.com/NixOS/nixpkgs/pull/92204#issuecomment-654946111

**Comment by worldofpeace** [comment]
@ofborg test pantheon

**Pull request merged**
