### PR TITLE
clipgrab: supply yt-dlp dependency from nixpkgs

### LINKED ISSUE #160331: Clipgrab is missing youtube-dl
### Describe the bug
When started, ClipGrab always want to download youtube-dl. When after that, ClipGrab never finds the video and stays stuck on «please wait while ClipGrab downloads video info» (translated from french).

### Steps To Reproduce
1. ... `nix-env -i clipgrab` or configuration.nix
2. ... Start ClipGrab
3. ...

### Expected behavior
youtube-dl dependency should be accessible, and video info should be fetched

### Screenshots

image

image

### Notify maintainers
@r-ryantm 
@LeSuisse 
@prusnak 
@siraben 

### Metadata

```console
~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.94, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.11, nixos-21.11.335665.0f316e4d72d"`
 - channels(jalil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by ozkutuk**
Fixes  #160331

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
I think we should inform upstream about this issue, and potentially get a proper fix (making it possible to disable the download without manually patching src)

**Comment by ozkutuk** [comment]
I feel hesitant about about reaching out as the code is not hosted on any public code collaboration platform and the official forum seems to be dead (returns 404). Only possible communication channel seems to be their support e-mail.

**Comment by IvarWithoutBones** [comment]
Ah, that makes sense :+1:

**Review by IvarWithoutBones — APPROVED** [review]
Binary works, thanks for the work :)

Result of `nixpkgs-review pr 160773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>clipgrab</li>
  </ul>
</details>

**Pull request merged**
