### PR TITLE
[next] libgit2_1_6: init at 1.6.4

### PR DESCRIPTION
**Pull request by figsoda**
Some packages still depend on libgit2 1.6

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tjni — APPROVED** [review]

**Review by Azd325 — APPROVED** [review]

**Comment by linsui** [comment]
Could you please also add jami to this MR? I thought it also requires libgit2 2.16. See https://hydra.nixos.org/build/229965246.

**Review by Azd325 — APPROVED** [review]

**Comment by vcunat** [comment]
jami got fixed by fa3ea76bdc0 and builds already: https://hydra.nixos.org/build/230406259

**Comment by vcunat** [comment]
Same with all the other packages as well, so I assume this PR won't be needed anymore.

gql still fails on [x86_64-darwin](https://hydra.nixos.org/build/230434487) but that probably won't get helped by libgit2 changes

**Comment by figsoda** [comment]
> gql still fails on [*-darwin](https://hydra.nixos.org/build/230434487) but that probably won't get helped by libgit2 changes (instead, the Security framework should be provided)

It requires the Security framework when used with libgit2 1.7 because it is falling back to the vendored version of libgit2 and not using the libgit2 dependency at all: https://github.com/NixOS/nixpkgs/pull/247398#issuecomment-1666624298. This patch fixes it on darwin as shown by ofborg.

> Same with all the other packages in this PR as well, so I assume this PR won't be needed anymore.

Same for `gex`, which was already fixed by adding the Security framework, but this is a better fix because the libgit2 dependency actually does something

The same applies to nix-init. The package already builds, but was not linking to libgit2, and downgrading libgit2 fixes the linking issue.

pygit2 is already using libgit2 1.6, I just lifted the override to top level

I will remove jami since that seems to be caused by a libgit2 bug that has been patched now

**Pull request merged**
