### PR TITLE
yubioath-flutter: 6.1.0 -> 6.2.0

### PR DESCRIPTION
**Pull request by afh**
###### Description of changes

This is a follow-up on #228372 with a kind request to @Lassulus to test the changes on my behalf on Linux.

❓ Is it possible to make the `substituteInPlace` more generic by using a regex, e.g.: `--replace 'yubikey-manager = ".*"'…`

ℹ️ I'm not sure whether the `vendorHash` would need / benefit from an update too.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lassulus** [comment]
```
error: builder for '/nix/store/j92zv22vpqglrb2swsknyqayrsvx4w0q-yubioath-flutter-helper-6.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > Finished creating a wheel...
       > Finished executing pipBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/helper/dist /build/source/helper
       > Processing ./authenticator_helper-0.1.0-py3-none-any.whl
       > Requirement already satisfied: zxing-cpp in /nix/store/lj52z8f3cmlll6bl6sgrmwvi7kcn0a3a-python3.10-zxing_cpp-1.4.0/lib/python3.10/site-packages (from authenticator-helper==0.1.0) (1.4.0)
       > ERROR: Could not find a version that satisfies the requirement yubikey-manager==5.1.0 (from authenticator-helper) (from versions: none)
       > ERROR: No matching distribution found for yubikey-manager==5.1.0
       >
       For full logs, run 'nix log /nix/store/j92zv22vpqglrb2swsknyqayrsvx4w0q-yubioath-flutter-helper-6.2.0.drv'
```

**Comment by afh** [comment]
Probably yes, good find @Aleksanaa. As I'm out and about it'll take me until tomorrow before I'm able to update the PR.

**Comment by Kranzes** [comment]
Can't you relax that's dependency? With pythonRelaxDeps or whatever that's called

**Comment by Lassulus** [comment]
hmm, no changes in build errors but eval now takes 10x longer

```
rror: builder for '/nix/store/bj1fnmxkbw03fbcwdhqj0wlyp922023c-yubioath-flutter-helper-6.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > /build/source/helper
       > Finished executing pipBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/helper/dist /build/source/helper
       > Processing ./authenticator_helper-0.1.0-py3-none-any.whl
       > Requirement already satisfied: zxing-cpp in /nix/store/lj52z8f3cmlll6bl6sgrmwvi7kcn0a3a-python3.10-zxing_cpp-1.4.0/lib/python3.10/site-packages (from authenticator-helper==0.1.0) (1.4.0)
       > ERROR: Could not find a version that satisfies the requirement yubikey-manager==5.1.0 (from authenticator-helper) (from versions: none)
       > ERROR: No matching distribution found for yubikey-manager==5.1.0
       >
       For full logs, run 'nix log /nix/store/bj1fnmxkbw03fbcwdhqj0wlyp922023c-yubioath-flutter-helper-6.2.0.drv'.
```

**Comment by lukegb** [comment]
I think for pythonRelaxDeps to work, you'll need to add the python3.pkgs.pythonRelaxDepsHook to nativeBuildInputs.

**Comment by afh** [comment]
Thanks for the suggestions @lukegb. Where can I learn more about the difference between `python3Packages` and `python3.pkgs`?

**Comment by afh** [comment]
Thanks for the explanation, @lukegb, it verifies my assumption that `pythonPackages` and `python3.pgks` can be used (more or less) interchangeably.

I did try and use only `pythonRelaxDepsHook` without the `python3.pkgs` prefix, yet that failed the tests.

Unfortunately something seems to be missing since the test run for the latest changes with `python3.pkgs. pythonRelaxDepsHook` in `nativeBuildDependencies` fails with: `No matching distribution found for yubikey-manager==5.1.0`.

Any other ideas to approach this?

**Comment by afh** [comment]
Thanks for the explanation, @lukegb, it verifies my assumption that `pythonPackages` and `python3.pgks` can be used (more or less) interchangeably.

I did try and use only `pythonRelaxDepsHook` without the `python3.pkgs` prefix, yet that failed the tests.

Unfortunately something seems to be missing since the test run for the latest changes with `python3.pkgs. pythonRelaxDepsHook` in `nativeBuildDependencies` fails with: `No matching distribution found for yubikey-manager==5.1.0`.

Any other ideas to approach this?

**Comment by lukegb** [comment]
Ah. `pythonRelaxDepsHook` doesn't seem to work for `pyproject` builds.

My advice then is to extend the existing `postPatch` which relaxes dependencies - just adding two new lines following the existing format for `Pillow` (we have 9.4 at the moment, 9.5 is coming in #228493), and for `yubikey-manager` should be enough.

**Comment by Kranzes** [comment]
> Ah. `pythonRelaxDepsHook` doesn't seem to work for `pyproject` builds.
> 
> My advice then is to extend the existing `postPatch` which relaxes dependencies - just adding two new lines following the existing format for `Pillow` (we have 9.4 at the moment, 9.5 is coming in #228493), and for `yubikey-manager` should be enough.

I am clearly seeing it being used across nixpkgs with pyproject.

**Comment by lukegb** [comment]
> > Ah. `pythonRelaxDepsHook` doesn't seem to work for `pyproject` builds.
> > My advice then is to extend the existing `postPatch` which relaxes dependencies - just adding two new lines following the existing format for `Pillow` (we have 9.4 at the moment, 9.5 is coming in #228493), and for `yubikey-manager` should be enough.
> 
> I am clearly seeing it being used across nixpkgs with pyproject.

Oh, you're right. Looking more closely at the implementation, it's because our pname and version don't match our wheel output - we'd have to set pname to `authenticator-helper` and version to `0.1.0` to make it work, which we could do, but that generates a completely useless output path, and it's probably "nicer" to have it tied more closely to the actual yubioath name/version, rather than having a generic name. But maybe that's outweighed by the utility of just using `pythonRelaxDeps` instead of substituteInPlace.

**Comment by afh** [comment]
Thanks everyone for chiming in, very help- and insightful! As a non-native speaker I'm having a bit of trouble "deciphering" the preferred approach from the comments above and kindly request a vote on the issue:

🚀  Change `pname` to `authenticator-helper` and `version` to `0.1.0` and accept a useless output path is generated

👀  add `substituteInPlace` to change the `yubikey-manager` in `pyproject.toml` the `postPatch` phase.

A question about approach :eyes: I have is: Would a change in [`pyproject.toml`](https://github.com/Yubico/yubioath-flutter/blob/main/helper/pyproject.toml) be sufficient or would [`poetry.lock`](https://github.com/Yubico/yubioath-flutter/blob/main/helper/poetry.lock) also need to be changed? If yes, what's the best way to deal with the [referenced hashes](https://github.com/Yubico/yubioath-flutter/blob/main/helper/poetry.lock#L693-L694)?

**Comment by tomodachi94** [comment]
For GitHub magic:

Closes #232092

**Comment by lobre** [comment]
It seems yubioath-flutter still does not build as of today. Would anyone be able to report on the status of this PR? How far is it from being merged? Thanks.

**Comment by lukegb** [comment]
> best

It should still build, and is indeed successfully being built by Hydra. Can you please explain where you're seeing build failures and what system type you're on?

```
[lukegb@totoro:~/Projects/nixpkgs/check-yubioath-builds]$ git rev-parse HEAD
b8392f9eb12070b647d711c3964ebc89c5d34854

[lukegb@totoro:~/Projects/nixpkgs/check-yubioath-builds]$ nix-build -A yubioath-flutter
/nix/store/q162ijbka1rbkxkh9ljvzfhnmwc1mpdv-yubioath-flutter-6.1.0

[lukegb@totoro:~/Projects/nixpkgs/check-yubioath-builds]$ $(nix-build -A nix-info)/bin/nix-info -m
these paths will be fetched (0.28 MiB download, 1.33 MiB unpacked):
  /nix/store/94x80fp2gyj14l6w4b8yn7kkgshifh2a-nix-info
  /nix/store/jids6qqs36p4ds9ghpkcw57kbhp8lbq2-findutils-4.9.0
copying path '/nix/store/jids6qqs36p4ds9ghpkcw57kbhp8lbq2-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/94x80fp2gyj14l6w4b8yn7kkgshifh2a-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.61, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-22.05pre375061.c777cdf5c56"`
 - channels(lukegb): `""`
 - nixpkgs: `/home/lukegb/depot/third_party/nixpkgs`
```

**Comment by lobre** [comment]
> Can you please explain where you're seeing build failures and what system type you're on?

It seems that I can build it correctly now. False positive then, I am not sure what happened last time I tried. Sorry about that.

**Comment by afh** [comment]
Thanks @lukegb and @lobre for checking in on this PR. From your point of view what is necessary in order to move forward here?

**Comment by lukegb** [comment]
I think it's just the :eyes: suggestion, that's mostly what I've been waiting on. I've got some local commits that'll fix this up so I'll push them up to your branch and rebase closer to head.

**Comment by lukegb** [comment]
Thanks again for your contribution and sorry it's taken such a long time to get it landed.

**Comment by afh** [comment]
Thanks for merging, @lukegb. All good, sometimes things take a bit more time and that's perfectly alright, better than moving (too) fast and breaking things :)

**Pull request merged**
