### PR TITLE
khal: 0.7.0 -> 0.8.2

### PR DESCRIPTION
**Pull request by matthiasbeyer**
**Does not build yet, can someone help me investigate?**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by DamienCassou** [comment]
The build is failing

**Comment by matthiasbeyer** [comment]
I know. See initial PR message.

**Comment by matthiasbeyer** [comment]
Fun fact: This builds if you apply the update commit on unstable, but not on master. So I assume this is not my fault... :smile:

**Comment by groxxda** [comment]
I recall there was an issue with python tests not being run by default that got fixed recently.
Could it be that this "builds" on an old version where the tests are simply skipped?

**Comment by FRidh** [comment]
this package needs pytest as testrunner. Add it to `buildInputs` and add
```
checkPhase = ''
  py.test
''

```

**Comment by matthiasbeyer** [comment]
Now requests-toolbelt fails for me.

**Pull request closed without merging**
