### PR TITLE
torcs: anonscm.debian.org has moved

### PR DESCRIPTION
**Pull request by eri451**
###### Motivation for this change
the patch links returned a HTTP error 401 as
anonscm.debian.org moved to a gitlab at salsa.debian.org
I used the non access required download link generated by the new instance
As @worldofpeace suggested in #58978 I used the last commit involving the files.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build torcs

**Comment by eri451** [comment]
Tried to build it on my system, but it failed because of a invalid conversion in OpenALMusicPlayer.cpp

> make[4]: Entering directory '/build/torcs-1.3.7/src/libs/musicplayer'                                                               
> gcc -E  -M -D__DEPEND__ -I/build/torcs-1.3.7/export/include -I/build/torcs-1.3.7 -D_DEFAULT_SOURCE -DSHM -DHAVE_CONFIG_H   SoundStream.cpp OggSoundStream.cpp OpenALMusicPlayer.cpp musicplayer.cpp > .depend                                                          
> g++ -I/build/torcs-1.3.7/export/include -I/build/torcs-1.3.7 -g -O2 -Wall -fPIC -fno-strict-aliasing -O2 -DUSE_RANDR_EXT -DGL_GLEXT_PROTOTYPES -Wall -fPIC -fno-strict-aliasing -O2 -DUSE_RANDR_EXT -DGL_GLEXT_PROTOTYPES  -D_DEFAULT_SOURCE -DSHM -DHAVE_CONFIG_H  -c SoundStream.cpp
> g++ -I/build/torcs-1.3.7/export/include -I/build/torcs-1.3.7 -g -O2 -Wall -fPIC -fno-strict-aliasing -O2 -DUSE_RANDR_EXT -DGL_GLEXT_PROTOTYPES -Wall -fPIC -fno-strict-aliasing -O2 -DUSE_RANDR_EXT -DGL_GLEXT_PROTOTYPES  -D_DEFAULT_SOURCE -DSHM -DHAVE_CONFIG_H  -c OggSoundStream.cpp
> g++ -I/build/torcs-1.3.7/export/include -I/build/torcs-1.3.7 -g -O2 -Wall -fPIC -fno-strict-aliasing -O2 -DUSE_RANDR_EXT -DGL_GLEXT_PROTOTYPES -Wall -fPIC -fno-strict-aliasing -O2 -DUSE_RANDR_EXT -DGL_GLEXT_PROTOTYPES  -D_DEFAULT_SOURCE -DSHM -DHAVE_CONFIG_H  -c OpenALMusicPlayer.cpp
> OpenALMusicPlayer.cpp: In member function 'virtual bool OpenALMusicPlayer::streamBuffer(ALuint)':
> OpenALMusicPlayer.cpp:164:22: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
>   const char* error = '\0';
> 
> make[4]: *** [/build/torcs-1.3.7/Make-default.mk:240: OpenALMusicPlayer.o] Error 1
> make[4]: Leaving directory '/build/torcs-1.3.7/src/libs/musicplayer'
> make[3]: *** [/build/torcs-1.3.7/Make-default.mk:679: subdirs] Error 1
> make[3]: Leaving directory '/build/torcs-1.3.7/src/libs'
> make[2]: *** [/build/torcs-1.3.7/Make-default.mk:679: subdirs] Error 1
> make[2]: Leaving directory '/build/torcs-1.3.7/src'
> make[1]: *** [/build/torcs-1.3.7/Make-default.mk:679: subdirs] Error 1
> make[1]: Leaving directory '/build/torcs-1.3.7'
> make: *** [Makefile:32: restart] Error 2
> builder for '/nix/store/39nqla9fscgp525w8nqq177jc3rsrybp-torcs-1.3.7.drv' failed with exit code 2
> error: build of '/nix/store/39nqla9fscgp525w8nqq177jc3rsrybp-torcs-1.3.7.drv' failed

**Comment by aanderse** [comment]
See https://github.com/NixOS/nixpkgs/pull/59527
Anyone volunteering to raise this issue upstream if it hasn't already been?

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build torcs

**Comment by c0bw3b** [comment]
I added the patch for GCC7 and built it locally on NixOS. Let's check with ofBorg though.

**Pull request merged**
