### PR TITLE
gotosocial: 0.13.0 -> 0.13.2

### LINKED ISSUE #281659: Update request: gotosocial 0.13.0 → 0.13.1
- Package name: gotosocoial
- Latest released version: 0.13.1

- Current version on the unstable channel: 0.13.0
- Current version on the stable/release channel: 0.12.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@misuzu

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jugendhacker**
Version 0.13.2 fixes some less severe security issues (see [1]) so this should be backported.

Replaces #281831
Closes #281659

[1] https://gts.superseriousbusiness.org/@gotosocial/statuses/01HNZ5GF2EM5M899B7RKXYNMH9

## Description of changes

https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.13.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jugendhacker** [comment]
Not sure about the port to stable thing, as this would mean stable would receive a "minor" upgrade (0.12->0.13), but it shouldn't be breaking from what I can see (only database migration which runs automatically and new configuration options which all have sensible default values)

**Review by delroth — APPROVED** [review]
Can't test this so I'd like to see a review from the maintainer, but otherwise LGTM. NixOS tests seem to pass too.

**Comment by delroth** [comment]
@ofborg test gotosocial

**Comment by delroth** [comment]
Looks like the package's tests are flaky, they didn't pass on ofborg. Not sure if that's a new issue with this version bump or if it was already a problem on 0.13.0.

**Comment by jugendhacker** [comment]
The corresponding test file wasn't edited since https://github.com/superseriousbusiness/gotosocial/commit/16275853eb8a43e0b113d476b896de53585c1281 which is already included in 0.13.0-rc1, so my guess is that they were already faulty in 0.13.0

Further more one of the developers confirmed to me [in their matrix chat](https://matrix.to/#/!rRxGvbqttRFxCdsLgU:superseriousbusiness.org/$Hbqdmc3kex_dKJa0AhfOWLrOOvYfSMeXUlC4uJNbnJw?via=superseriousbusiness.org&via=matrix.org&via=pixie.town) that they also observed those test failing sometimes

**Review by misuzu — APPROVED** [review]

**Pull request merged**
