### PR TITLE
openmolcas: remove static libraries in output

### PR DESCRIPTION
**Pull request by markuskowa**
I just noticed that molcas places static libraries in `$out/lib`. Removing these libraries saves 22 MB.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by sheepforce — CHANGES_REQUESTED** [review]
Hmm. If we don't want to drop libraries entirely, I would rather vote for building the shared libs instead of the static ones. They are also much smaller.

How about that one?

```patch
diff --git a/pkgs/applications/science/chemistry/openmolcas/default.nix b/pkgs/applications/science/chemistry/openmolcas/default.nix
index 76192e4d4de9..2b17fb368364 100644
--- a/pkgs/applications/science/chemistry/openmolcas/default.nix
+++ b/pkgs/applications/science/chemistry/openmolcas/default.nix
@@ -101,7 +101,6 @@ stdenv.mkDerivation rec {
 
   cmakeFlags = [
     "-DOPENMP=ON"
-    "-DLINALG=OpenBLAS"
     "-DTOOLS=ON"
     "-DHDF5=ON"
     "-DFDE=ON"
@@ -109,6 +108,8 @@ stdenv.mkDerivation rec {
     (lib.strings.cmakeBool "DMRG" enableQcmaquis)
     (lib.strings.cmakeBool "NEVPT2" enableQcmaquis)
     "-DCMAKE_SKIP_BUILD_RPATH=ON"
+    (lib.strings.cmakeBool "BUILD_STATIC_LIBS" stdenv.hostPlatform.isStatic)
+    (lib.strings.cmakeBool "BUILD_SHARED_LIBS" (!stdenv.hostPlatform.isStatic))
   ] ++ lib.optionals (blas-ilp64.passthru.implementation == "openblas") [
     "-DOPENBLASROOT=${blas-ilp64.passthru.provider.dev}"
     "-DLINALG=OpenBLAS"
```

(I've also noticed the additional `"-DLINALG=OpenBLAS"` at the top of the `cmakeFlags`)

**Comment by markuskowa** [comment]
>> If we don't want to drop libraries entirely, I would rather vote for building the shared libs instead of the static ones. They are also much smaller.

What are these libraries needed for? If they are used by another program, we could put them in them `lib` output?

**Comment by markuskowa** [comment]
Okay, I get it now the shared lib is much smaller.

**Comment by sheepforce** [comment]
Hm, I've noticed them before, yes. The even better solution would be to 

> > > If we don't want to drop libraries entirely, I would rather vote for building the shared libs instead of the static ones. They are also much smaller.
> 
> What are these libraries needed for? If they are used by another program, we could put them in them `lib` output?

Lib output seems a good idea, nevertheless, yes.

**Review by sheepforce — APPROVED** [review]

**Pull request merged**
