### PR TITLE
pyre: init at 0.0.8

### PR DESCRIPTION
**Pull request by teh**
###### Motivation for this change

Working version of https://github.com/NixOS/nixpkgs/pull/40809

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks for packaging this, I've been wanting to try this tool as well. Please do move the expression from `development/compilers` to `development/tools`.

Do you happen to have any experience with https://github.com/Instagram/MonkeyType? Seems quite useful as well.

**Comment by teh** [comment]
Done - also removed some function parameters that I had left in by accident.

Hadn't heard about MonkeyType but looks really interesting, thanks!

**Comment by xeji** [comment]
@GrahamcOfBorg  build pyre

**Comment by bbarker** [comment]
@teh does `nix-locate` (https://unix.stackexchange.com/questions/252224/how-to-find-out-which-not-installed-package-a-file-belongs-to-on-nixos) provide any information about which package provides the file? If not, as a workaround, I can just find out what should be installed in the base OS I'm using (though that wouldn't help me on my NixOS installation).

**Comment by bbarker** [comment]
I think we can likely resolve my above issue: on non NixOS systems, this should be installed through the base OS if possible; otherwise one might need to install `tzdata` through nix and set up the appropriate symbolic links manually. For instance, I installed it via Ubuntu's apt and this was fine. On NixOS, I believe I heard on IRC that installing tzdata, then doing a `rebuild-switch` should do the job, but I haven't tested this as yet.

**Comment by teh** [comment]
I think it's provided here: https://github.com/NixOS/nixpkgs/blob/55bc53d1dd9f99e59a8f218e98b5e484e2e6eae8/nixos/modules/config/timezone.nix

and indeed I have `time.timeZone = "Europe/London";` in my `configuration.nix`. I think this needs to be fixed upstream, but happy to accept PR with patch that stops ocaml logging from failing over if `/etc/localtime` doesn't exist.

**Pull request merged**
