### PR TITLE
python3Packages.py-air-control: 2.1.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2.2.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130046` at 0a368cb5 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/de77943aaa00cb9bac3dfe8d0acaf059">python38Packages.py-air-control-exporter</a></li>
    <li><a href="https://gist.github.com/2229c9d0b7906a9ba03d19b8840709ea">python39Packages.py-air-control</a></li>
    <li><a href="https://gist.github.com/49621cacd234bc09a7b25292bf252179">python39Packages.py-air-control-exporter</a></li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>python38Packages.py-air-control</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `flask`.
Near pkgs/development/python-modules/py-air-control/default.nix:5:3:
```
  |
5 | , flask
  |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by jonringer — COMMENTED** [review]
seeing a lot of failures

```
https://github.com/NixOS/nixpkgs/pull/130046

3 packages failed to build:
python38Packages.py-air-control-exporter python39Packages.py-air-control python39Packages.py-air-control-exporter

1 package built:
python38Packages.py-air-control
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 130046` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python38Packages.py-air-control</li>
    <li>python38Packages.py-air-control-exporter</li>
    <li>python39Packages.py-air-control</li>
    <li>python39Packages.py-air-control-exporter</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.coapthon3</li>
    <li>python39Packages.coapthon3</li>
  </ul>
</details>

**Comment by fabaff** [comment]
#133247 fixes a build failure.

**Pull request closed without merging**
