### PR TITLE
[staging] [security] perl524: 5.24.3 -> 5.24.4; perl526: 5.26.1 -> 5.26.2

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

minor update
bugfixes including 3 CVE
https://metacpan.org/pod/distribution/perl/pod/perl5244delta.pod
https://metacpan.org/pod/distribution/perl/pod/perl5262delta.pod

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build perl524 perl526

**Comment by volth** [comment]
Interesting that it timed out on more powerful ```x86_64``` while succeeded on ```aarch64```

**Comment by xeji** [comment]
Yes, I would have thought rebuilding `gcc` would time out on `aarch64`.

**Comment by xeji** [comment]
Since this contains several CVE fixes I'm going to merge it now.
BTW, should this be backported to 18.03?

**Comment by volth** [comment]
Let's see if there will be some regressions first (I built everything in ```pkgs.perlPackages``` but there are other perl packages (hydra, ...) and packages which have perl programs as build dependencies)

Anyway, these versions are 2+ months old so there is no ugrency

**Pull request merged**
