### PR TITLE
subtitleeditor: add more gst-plugins

### PR DESCRIPTION
**Pull request by ilmari-lauhakangas**
If there is a reason for leaving these out, I would like to learn it.

### CODE REVIEW

**Review by plcplc — COMMENTED** [review]
The only reason I could think of to not include those if if they break the build (or if they are know to occasionally break - I'm not very much in the know about the meaning of the good/bad/ugly distinction of gst plugins).

If it builds, let's have the change included!

**Comment by ilmari-lauhakangas** [comment]
https://gstreamer.freedesktop.org/documentation/additional/splitup.html

> gst-plugins-ugly
> 
> A set of plug-ins that have good quality and correct functionality, but distributing them might pose problems. The license on either the plug-ins or the supporting libraries might not be how we'd like. The code might be widely known to present patent problems.
> 
>     Distributors should check if they want/can ship these plug-ins
>     People writing elements should base their code on these elements

So should there be a condition depending on allowUnfree being true for adding ugly plugins?

**Comment by plcplc** [comment]
I think that if the ugly plugins in nixpkgs are guarded allowUnfree then subtitleeditor should only depend on the ugly plugins if the allowUnfree= true.

That is probably the best we can do.

**Comment by ilmari-lauhakangas** [comment]
Right, I forgot to actually check how it is with ugly as nixpkg :) There is no guard currently: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/gstreamer/ugly/default.nix

**Comment by plcplc** [comment]
Thanks for checking. I think this is a great addition.

This is my first time reviewing a PR on github.. do I need to do anything more to signal my blessings to this?

**Comment by Ekleog** [comment]
I can see no reason not to have this. Let's land, thank you :)

**Pull request merged**
