### PR TITLE
offlineimap: 6.6.0 → 6.6.1

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by bjornfor** [comment]
Nitpick: Even though the unicode arrow looks nice, it makes it more complex to filter package updates out of the commit log. Care to use ASCII arrow next time?

**Comment by bjornfor** [comment]
Pushed to master (fc83959704cd781825af26a15d6388332399a356).

**Comment by DamienCassou** [comment]
@bjornfor ok :-(

**Comment by bjornfor** [comment]
@DamienCassou: Oh, you really like the arrows?

**Comment by DamienCassou** [comment]
In general, I think we should target more Unicode rather than less. But I don't care enough to change the tools and people's habits

**Comment by bjornfor** [comment]
@DamienCassou: I do agree unicode is nice. But isn't there many unicode arrows? I think that at least for the _commit subject line_ it'd be nice to have a standard grep'able pattern. (Just my opinion of course.)

**Comment by DamienCassou** [comment]
I agree that a standard is important.

**Pull request closed without merging**
