### PR TITLE
minetest: 5.5.1 -> 5.6.0

### PR DESCRIPTION
**Pull request by enderger**
###### Description of changes

https://dev.minetest.net/Changelog#5.5.0_.E2.86.92_5.6.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 186160` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>minetest (minetestclient ,minetestclient_5)</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>minetestserver (minetestserver_5)</li>
  </ul>
</details>

**Comment by enderger** [comment]
Result of `nixpkgs-review pr 186160` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>irrlichtmt</li>
    <li>minetest (minetestclient ,minetestclient_5)</li>
    <li>minetestserver (minetestserver_5)</li>
  </ul>
</details>

**Comment by viraptor** [comment]
failure on darwin intel
```
CMake Error at /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:458 (message):
  otool -l failed: 1

  error:
  /nix/store/nq7dispfy6jj8m56963b5w990djs431y-cctools-binutils-darwin-949.0.1/bin/otool:
  can't open file: /usr/lib/libSystem.B.dylib (No such file or directory)

Call Stack (most recent call first):
  /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:527 (get_item_rpaths)
  /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:649 (set_bundle_key_values)
  /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:934 (get_bundle_keys)
  src/cmake_install.cmake:54 (fixup_bundle)
  cmake_install.cmake:98 (include)
```

**Comment by enderger** [comment]
> failure on darwin intel
> 
> ```
> CMake Error at /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:458 (message):
>   otool -l failed: 1
> 
>   error:
>   /nix/store/nq7dispfy6jj8m56963b5w990djs431y-cctools-binutils-darwin-949.0.1/bin/otool:
>   can't open file: /usr/lib/libSystem.B.dylib (No such file or directory)
> 
> Call Stack (most recent call first):
>   /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:527 (get_item_rpaths)
>   /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:649 (set_bundle_key_values)
>   /nix/store/j41rvaxw9c3m8ics8pwhsr4ih525f821-cmake-3.23.2/share/cmake-3.23/Modules/BundleUtilities.cmake:934 (get_bundle_keys)
>   src/cmake_install.cmake:54 (fixup_bundle)
>   cmake_install.cmake:98 (include)
> ```

Looks like that's a sandboxing issue AFAIK, `libSystem` is proprietary and contains the system's `libc`.

**Comment by viraptor** [comment]
I'll try to have a look at that later, but in the meantime maybe someone from @nixos/darwin-maintainers has a quick solution.

**Comment by fpletz** [comment]
@viraptor Please open a separate PR for that. I don't have access to a Darwin system and thus cannot test or fix this.

**Comment by fgaz** [comment]
Looks like this can be backported, there isn't any breaking change

**Pull request merged**
