### PR TITLE
qemu: 5.1.0 -> 5.2.0

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change

Noticed a recent bump to QEMU version.
https://wiki.qemu.org/ChangeLog/5.2

NOTE: build system changed: https://wiki.qemu.org/ChangeLog/5.2#Build_Information

I wasn't sure if some of these options were supposed to be enabled by default, so I included the list here.
<details>
<summary>Options we have/haven't enabled (default build)</summary>

```
                   Install prefix: /nix/store/my667bibrijv2dmagcs517b6w967yi0m-qemu-5.2.0
                   BIOS directory: share/qemu
                    firmware path: /nix/store/my667bibrijv2dmagcs517b6w967yi0m-qemu-5.2.0/share/qemu-firmware
                 binary directory: bin
                library directory: lib
                 module directory: lib/qemu
                libexec directory: libexec
                include directory: include
                 config directory: /etc
            local state directory: /var
                 Manual directory: share/man
                    Doc directory: /nix/store/my667bibrijv2dmagcs517b6w967yi0m-qemu-5.2.0/share/doc/qemu
                  Build directory: /build/qemu-5.2.0/build
                      Source path: /build/qemu-5.2.0
                       GIT binary: git
                   GIT submodules: 
                       C compiler: gcc
                  Host C compiler: gcc
                     C++ compiler: g++
                          ARFLAGS: rv
                           CFLAGS: -O2 -g
                         CXXFLAGS: -O2 -g
                      QEMU_CFLAGS: -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -m64 -mcx16 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv  -Wold-style-declaration -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-psabi -fstack-protector-strong
                     QEMU_LDFLAGS: -Wl,--warn-common -Wl,-z,relro -Wl,-z,now -m64  -fstack-protector-strong
                             make: make
                           python: /nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/bin/python3 (version: 3.8)
                     sphinx-build: YES
                      genisoimage: 
                    slirp support: internal
                             smbd: "/usr/sbin/smbd"
                   module support: NO
                         host CPU: x86_64
                  host endianness: little
                      target list: aarch64-softmmu alpha-softmmu arm-softmmu avr-softmmu cris-softmmu hppa-softmmu i386-softmmu m68k-softmmu microblaze-softmmu microblazeel-softmmu mips-softmmu mips64-softmmu mips64el-softmmu mipsel-softmmu moxie-softmmu nios2-softmmu or1k-softmmu ppc-softmmu ppc64-softmmu riscv32-softmmu riscv64-softmmu rx-softmmu s390x-softmmu sh4-softmmu sh4eb-softmmu sparc-softmmu sparc64-softmmu tricore-softmmu x86_64-softmmu xtensa-softmmu xtensaeb-softmmu aarch64-linux-user aarch64_be-linux-user alpha-linux-user arm-linux-user armeb-linux-user cris-linux-user hppa-linux-user i386-linux-user m68k-linux-user microblaze-linux-user microblazeel-linux-user mips-linux-user mips64-linux-user mips64el-linux-user mipsel-linux-user mipsn32-linux-user mipsn32el-linux-user nios2-linux-user or1k-linux-user ppc-linux-user ppc64-linux-user ppc64le-linux-user riscv32-linux-user riscv64-linux-user s390x-linux-user sh4-linux-user sh4eb-linux-user sparc-linux-user sparc32plus-linux-user sparc64-linux-user x86_64-linux-user xtensa-linux-user xtensaeb-linux-user
                    gprof enabled: NO
                   sparse enabled: NO
                   strip binaries: YES
                         profiler: NO
                     static build: NO
                      SDL support: YES
                SDL image support: YES
                      GTK support: YES
                   GTK GL support: YES
                           pixman: YES
                      VTE support: YES
                     TLS priority: "NORMAL"
                   GNUTLS support: YES
                        libgcrypt: NO
                           nettle: YES
                              XTS: YES
                         libtasn1: NO
                              PAM: NO
                    iconv support: YES
                   curses support: YES
                    virgl support: YES
                     curl support: YES
                  mingw32 support: NO
                    Audio drivers: alsa pa sdl
             Block whitelist (rw): 
             Block whitelist (ro): 
                   VirtFS support: YES
            build virtiofs daemon: YES
                Multipath support: NO
                      VNC support: YES
                 VNC SASL support: NO
                 VNC JPEG support: YES
                  VNC PNG support: YES
                      xen support: NO
                   brlapi support: NO
                    Documentation: YES
                              PIE: YES
                      vde support: YES
                   netmap support: NO
                Linux AIO support: YES
           Linux io_uring support: NO
               ATTR/XATTR support: YES
                    Install blobs: YES
                      KVM support: YES
                      HAX support: NO
                      HVF support: NO
                     WHPX support: NO
                      TCG support: YES
                TCG debug enabled: NO
                  TCG interpreter: NO
              malloc trim support: YES
                     RDMA support: NO
                   PVRDMA support: NO
                      fdt support: internal
                       membarrier: NO
                   preadv support: YES
                        fdatasync: YES
                          madvise: YES
                    posix_madvise: YES
                   posix_memalign: YES
                libcap-ng support: YES
             vhost-kernel support: YES
                vhost-net support: YES
             vhost-crypto support: YES
               vhost-scsi support: YES
              vhost-vsock support: YES
               vhost-user support: YES
    vhost-user-blk server support: YES
            vhost-user-fs support: YES
               vhost-vdpa support: YES
                   Trace backends: log
                    spice support: YES
                      rbd support: NO
                   xfsctl support: NO
                smartcard support: YES
                      U2F support: NO
                           libusb: YES
                    usb net redir: YES
                   OpenGL support: YES
                   OpenGL dmabufs: YES
                 libiscsi support: NO
                   libnfs support: NO
                build guest agent: YES
                  seccomp support: YES
                coroutine backend: ucontext
                   coroutine pool: YES
                debug stack usage: NO
                  mutex debugging: NO
                     crypto afalg: NO
                GlusterFS support: NO
                             gcov: NO
                      TPM support: YES
                   libssh support: NO
                    QOM debugging: YES
             Live block migration: YES
                      lzo support: YES
                   snappy support: YES
                    bzip2 support: YES
                    lzfse support: NO
                     zstd support: NO
                NUMA host support: YES
                          libxml2: NO
                 memory allocator: system
                avx2 optimization: YES
             avx512f optimization: NO
              replication support: YES
                    bochs support: YES
                    cloop support: YES
                      dmg support: YES
                  qcow v1 support: YES
                      vdi support: YES
                    vvfat support: YES
                      qed support: YES
                parallels support: YES
                 sheepdog support: NO
                         capstone: internal
                  libpmem support: NO
                libdaxctl support: NO
                          libudev: YES
                  default devices: YES
                   plugin support: NO
                  fuzzing support: NO
                 thread sanitizer: NO
                         rng-none: NO
                    Linux keyring: YES
```
</details>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arcnmx** [comment]
Would it make sense to add meson as a dep (and `--meson=meson` to configure flags)? qemu source release comes with meson 0.55.3 vendored in the tarball but it seems a little silly to let it use it...

**Comment by drewrisinger** [comment]
Can confirm the libpixman issue. This is causing build errors for some downstream packages from ``qemu`` when reviewing. This might be another patchelf-related issue, see https://github.com/NixOS/nixpkgs/pull/106830. Current list using ``nix-review``:

```
2 packages marked as broken and skipped:
linuxPackages_hardkernel_4_14.virtualbox linuxPackages_hardkernel_latest.virtualbox

2 packages blacklisted:
tests.nixos-functions.nixos-test tests.nixos-functions.nixosTest-test

9 packages failed to build:
libguestfs linuxPackages_5_10.virtualbox linuxPackages_latest-libre.virtualbox linuxPackages_latest_xen_dom0.virtualbox multibootusb python37Packages.guestfs python38Packages.guestfs python39Packages.guestfs vagrant

34 packages built:
alpine-make-vm-image aqemu cloud-init cloud-utils cot linuxPackages-libre.virtualbox linuxPackages.virtualbox linuxPackages_4_14.virtualbox linuxPackages_4_19.virtualbox linuxPackages_4_4.virtualbox linuxPackages_4_9.virtualbox linuxPackages_5_9.virtualbox linuxPackages_hardened.virtualbox linuxPackages_latest_hardened.virtualbox linuxPackages_latest_xen_dom0_hardened.virtualbox linuxPackages_testing_bcachefs.virtualbox linuxPackages_xen_dom0.virtualbox linuxPackages_xen_dom0_hardened.virtualbox linuxPackages_zen.virtualbox open-watcom-bin out-of-tree python37Packages.cot python39Packages.cot qemu qemu-utils qemu_kvm qemu_test qemu_xen qemu_xen-light qtemu virtualbox virtualboxHardened virtualboxHeadless virtualboxWithExtpack
```

**Comment by arcnmx** [comment]
Yeah I'm not sure what's going on because `patchelf` shouldn't actually be necessary for qemu at all? fwiw I hacked around it using patchelf and have been running qemu 5.2.0 for the past few days without issue, but it would be nice to figure out what's actually going on here.

**Comment by drewrisinger** [comment]
@arcnmx I can't say anything about whether ``qemu`` SHOULD have dynamic libraries or not, but it certainly seems to.

After adding ``autoPatchelfHook``, attempting build (note: the downstream failure of ``libguestfs`` relies on ``qemu-kvm``, hence this particular path):
```
$ /nix/store/bvcs7mq94cscy9y5fgcnz2nc5qdczqyx-qemu-5.2.0/bin/qemu-kvm
/nix/store/bvcs7mq94cscy9y5fgcnz2nc5qdczqyx-qemu-5.2.0/bin/qemu-system-x86_64: error while loading shared libraries: libpixman-1.so.0: cannot open shared object file: No such file or directory
$ /nix/store/bvcs7mq94cscy9y5fgcnz2nc5qdczqyx-qemu-5.2.0/bin/.qemu-system-x86_64-wrapped 
/nix/store/bvcs7mq94cscy9y5fgcnz2nc5qdczqyx-qemu-5.2.0/bin/.qemu-system-x86_64-wrapped: error while loading shared libraries: libpixman-1.so.0: cannot open shared object file: No such file or directory
$ ldd /nix/store/bvcs7mq94cscy9y5fgcnz2nc5qdczqyx-qemu-5.2.0/bin/.qemu-system-x86_64-wrapped | grep pixman
        libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fa65853a000)
```
It seems that this dynamic library isn't being patched like the rest. I checked the derivation's ``buildInputs``, and there's DEFINITELY ``libpixman``, which hints that this is again an ``autoPatchelfHook`` error, so waiting on #106830...
Pushing this latest fixup.

**Comment by flokli** [comment]
`qemu_test` fails to build for me:

```
reading sources... [  8%] bitmaps
reading sources... [ 16%] dbus
reading sources... [ 25%] dbus-vmstate
reading sources... [ 33%] index
reading sources... [ 41%] live-block-operations
reading sources... [ 50%] pr-helper
reading sources... [ 58%] qemu-ga
reading sources... [ 66%] qemu-ga-ref
reading sources... [ 75%] qemu-qmp-ref
reading sources... [ 83%] vhost-user
reading sources... [ 91%] vhost-user-gpu
reading sources... [100%] vhost-vdpa

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... qemu-ga.8 { } qemu-ga-ref.7 { } qemu-qmp-ref.7 { } done
build succeeded.

The manual pages are in docs.
glibPreInstallPhase
installing
install flags: install
[2/3] Installing files.sion.h with a meson_exe.py custom command
Installing subdir /build/qemu-5.2.0/qga/run to /var/run
Traceback (most recent call last):
  File "/build/qemu-5.2.0/meson/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/build/qemu-5.2.0/meson/mesonbuild/minstall.py", line 544, in run
    installer.do_install(datafilename)
  File "/build/qemu-5.2.0/meson/mesonbuild/minstall.py", line 361, in do_install
    self.install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/build/qemu-5.2.0/meson/mesonbuild/minstall.py", line 387, in install_subdirs
    d.dirmaker.makedirs(full_dst_dir, exist_ok=True)
  File "/build/qemu-5.2.0/meson/mesonbuild/minstall.py", line 60, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/nix/store/sqcfddc7pr0pj3ckqgq5c8jjqzacj3ac-python3-3.8.6/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/sqcfddc7pr0pj3ckqgq5c8jjqzacj3ac-python3-3.8.6/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var'
FAILED: meson-install
/nix/store/sqcfddc7pr0pj3ckqgq5c8jjqzacj3ac-python3-3.8.6/bin/python3 /build/qemu-5.2.0/meson/meson.py install --no-rebuild
ninja: build stopped: subcommand failed.
builder for '/nix/store/0jlw9qyvw59yax1qkn34z0bjms00s542-qemu-host-cpu-only-for-vm-tests-5.2.0.drv' failed with exit code 1
```

**Review by flokli — CHANGES_REQUESTED** [review]
This fails to build currently.

**Comment by blitz** [comment]
@drewrisinger I also can't build this on NixOS with the same error that @flokli reported.

**Comment by blitz** [comment]
@drewrisinger It might also be a good idea to split the version update from switching the build system, if this is possible.

**Comment by SuperSandro2000** [comment]
@drewrisinger please fix the merge conflict.

**Comment by drewrisinger** [comment]
> @drewrisinger It might also be a good idea to split the version update from switching the build system, if this is possible.

Not easily possible without patching. I get the following error when I try building without ``ninja`` in the ``configurePhase``, I believe: ``ERROR: Cannot find Ninja``.

Currently in process of doing a full ``nix-review`` on this with merge conflicts fixed. Will update & fix build errors once that finishes. Sorry for the delay, winter holidays & work commitments.

**Comment by blitz** [comment]
@drewrisinger Awesome. I gave this a shot and it builds and works. :)

**Review by blitz — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 106988` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages_hardkernel_4_14.virtualbox</li>
<li>linuxPackages_hardkernel_latest.virtualbox</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>aqemu: log <a href="https://termbin.com/oruc">https://termbin.com/oruc</a></li>
<li>qemu_xen: log was empty</li>
  </ul>
</details>
<details>

  <summary>12 packages failed to build and are new build failures:</summary>
  <ul>
<li>linuxPackages-libre.virtualbox: log was empty</li>
<li>linuxPackages_5_10.virtualbox: log <a href="https://termbin.com/g4il">https://termbin.com/g4il</a></li>
<li>(linuxPackages_latest.virtualbox): log was empty</li>
<li>linuxPackages_latest-libre.virtualbox: log <a href="https://termbin.com/mlxc">https://termbin.com/mlxc</a></li>
<li>linuxPackages_latest_hardened.virtualbox: log <a href="https://termbin.com/3ldb">https://termbin.com/3ldb</a></li>
<li>linuxPackages_latest_xen_dom0.virtualbox: log <a href="https://termbin.com/2lnm">https://termbin.com/2lnm</a></li>
<li>linuxPackages_latest_xen_dom0_hardened.virtualbox: log <a href="https://termbin.com/8s5c">https://termbin.com/8s5c</a></li>
<li>linuxPackages_lqx.virtualbox: log <a href="https://termbin.com/2v9d">https://termbin.com/2v9d</a></li>
<li>linuxPackages_zen.virtualbox: log <a href="https://termbin.com/z1aw6">https://termbin.com/z1aw6</a></li>
<li>(qemu_xen_4_10): log was empty</li>
<li>qemu_xen-light: log was empty</li>
<li>(qemu_xen_4_10-light): log was empty</li>
  </ul>
</details>
<details>
<summary>
33 packages built:
</summary>
<ul>
<li>alpine-make-vm-image</li>
<li>cloud-init</li>
<li>cloud-utils</li>
<li>cot (python38Packages.cot)</li>
<li>libguestfs</li>
<li>linuxPackages.virtualbox (linuxPackages_5_4.virtualbox)</li>
<li>linuxPackages_4_14.virtualbox</li>
<li>linuxPackages_4_19.virtualbox</li>
<li>linuxPackages_4_4.virtualbox</li>
<li>linuxPackages_4_9.virtualbox</li>
<li>linuxPackages_5_9.virtualbox</li>
<li>linuxPackages_hardened.virtualbox</li>
<li>linuxPackages_testing_bcachefs.virtualbox</li>
<li>linuxPackages_xen_dom0.virtualbox</li>
<li>linuxPackages_xen_dom0_hardened.virtualbox</li>
<li>multibootusb</li>
<li>open-watcom-bin</li>
<li>out-of-tree</li>
<li>python37Packages.cot</li>
<li>python37Packages.guestfs</li>
<li>python38Packages.guestfs</li>
<li>python39Packages.cot</li>
<li>python39Packages.guestfs</li>
<li>qemu</li>
<li>qemu-utils</li>
<li>qemu_kvm</li>
<li>qemu_test</li>
<li>qtemu</li>
<li>vagrant</li>
<li>virtualbox</li>
<li>virtualboxHardened</li>
<li>virtualboxHeadless</li>
<li>virtualboxWithExtpack</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

virtualboxHeadless:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unused --replace got detected:
```
substituteStream(): WARNING: pattern 'PSHCLFORMATDATA' doesn't match anything in file 'src/VBox/HostServices/SharedClipboard/VBoxSharedClipboardSvc-x11-stubs.cpp'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by austinharris** [comment]
This change doesn't build for me on a darwin system using clang due to the autoPatchElf script not having $READELF defined. I'm not sure the proper fix, but I am trying to build with exporting READELF in preConfigure. @drewrisinger

**Comment by Izorkin** [comment]
Found error in guest-agent:
```
● qemu-guest-agent.service - Run the QEMU Guest Agent
     Loaded: loaded (/nix/store/c7k7nr3r09qysbr5ay1q9n5s0rwgyjdz-unit-qemu-guest-agent.service/qemu-guest-agent.service; linked; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Tue 2021-01-26 22:10:24 MSK; 30s ago
    Process: 1472 ExecStart=/nix/store/ynz6rzp22kp8wqba084x0vjhdzprghr2-qemu-5.2.0-ga/bin/qemu-ga (code=exited, status=0/SUCCESS)
   Main PID: 1472 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out
        CPU: 7ms

янв 26 22:10:24 tech systemd[1]: qemu-guest-agent.service: Succeeded.
янв 26 22:10:24 tech qemu-ga[1472]: 1611688224.261403: critical: failed to write persistent state to /nix/store/ynz6rzp22kp8wqba084x0vjhdzprghr2-qemu-5.2.0-ga/bin/../var/run/qga.state: Failed to create file “/nix/store/ynz6rzp22kp8wqba084x0vjhdzprghr2-qemu-5.2.0-ga/bin/../var/run/qga.state.T2SYX0”: No such file or directory
янв 26 22:10:24 tech qemu-ga[1472]: 1611688224.261416: critical: unable to create state file at path /nix/store/ynz6rzp22kp8wqba084x0vjhdzprghr2-qemu-5.2.0-ga/bin/../var/run/qga.state
янв 26 22:10:24 tech qemu-ga[1472]: 1611688224.261420: critical: failed to load persistent state
янв 26 22:10:24 tech qemu-ga[1472]: 1611688224.261424: critical: error initializing guest agent
янв 26 22:10:24 tech systemd[1]: qemu-guest-agent.service: Scheduled restart job, restart counter is at 5.
янв 26 22:10:24 tech systemd[1]: Stopped Run the QEMU Guest Agent.
янв 26 22:10:24 tech systemd[1]: qemu-guest-agent.service: Start request repeated too quickly.
янв 26 22:10:24 tech systemd[1]: qemu-guest-agent.service: Failed with result 'start-limit-hit'.
янв 26 22:10:24 tech systemd[1]: Failed to start Run the QEMU Guest Agent.
```

**Comment by Izorkin** [comment]
Simple fix:
```
diff --git a/pkgs/applications/virtualization/qemu/default.nix b/pkgs/applications/virtualization/qemu/default.nix
index d83c6d350e2..a9045c900a4 100644
--- a/pkgs/applications/virtualization/qemu/default.nix
+++ b/pkgs/applications/virtualization/qemu/default.nix
@@ -108,6 +108,10 @@ stdenv.mkDerivation rec {
     # this script isn't marked as executable b/c it's indirectly used by meson. Needed to patch its shebang
     chmod +x ./scripts/shaderinclude.pl
     patchShebangs .
+
+    substituteInPlace qga/main.c \
+      --replace '%s/qga.state' '/run/qga.state'
+
   '' + optionalString stdenv.hostPlatform.isMusl ''
     NIX_CFLAGS_COMPILE+=" -D_LINUX_SYSINFO_H"
   '';

```
Create PR or this variant is not suitable?

**Comment by Izorkin** [comment]
qemu-guest-agent fixed in #110927

**Comment by 573** [comment]
Using https://github.com/Mic92/nixos-shell, when I add the line `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` to [vm.nix](https://github.com/Mic92/nixos-shell/blob/93df1dde693635f2573d584c001cc454dd983a1d/examples/vm.nix) and run (using [this](https://github.com/NixOS/nixpkgs/pull/106988/commits/9e403b19a1444b373874b6e9efdd728613c6badc) commit):
```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz make test
```
I get
>rm: cannot remove '/nix/store/60nv5372byadkkwkwvdimmzn4jm9r3d4-qemu-5.2.0/share/applications/qemu.desktop': No such file or directory
[log file](https://gist.githubusercontent.com/573/0f3e1f4c80183da5f6fd7a034d20a6a5/raw/2d4d80f4abb3fd68aa7ce338b4cbc11417fa4db2/rfhpc57x4qlf5scnnkg4iq6xkjvaby5z-qemu-5.2.0.drv.log)

**Pull request merged**
