### PR TITLE
linux: Adds patch for fixing wifi on raspberry pi

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

@kwohlfahrt here we go :)

Ping @Mic92 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bkchr** [comment]
Okay, don't merge. Needs some resolving!

**Comment by bkchr** [comment]
Okay fixed, I needed to adapt the patch to work with 4.19.

**Comment by Synthetica9** [comment]
@bkchr A bit late, but where does this patch come from?

**Comment by Mic92** [comment]
see https://github.com/NixOS/nixpkgs/pull/53694#discussion_r246315399 for sourcee

**Comment by Synthetica9** [comment]
Why not use fetchPatch in that case?

**Comment by Mic92** [comment]
The patch had to be changed slightly.

**Pull request merged**
