### PR TITLE
gitAndTools.gita: 0.8.2 -> 0.9.2

### PR DESCRIPTION
**Pull request by seqizz**
###### Motivation for this change

Version bump, also overriding the pyyaml for python, since the package depends on the new version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
The commit message should tell why the override was necessary.

Or even better: A comment in the sourcecode. So that we know when to remove the override (probably when switching to a newer python version as python3).

**Comment by seqizz** [comment]
Added a comment into the file

**Review by matthiasbeyer — APPROVED** [review]

**Review by c0bw3b — CHANGES_REQUESTED** [review]
`pyyaml` v5.1 is in nixpkgs since #57688 and already in master.
This PR should just bump `gita`

**Comment by seqizz** [comment]
Didn't realize the new version, thanks. Should be OK now.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build gitAndTools.gita

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
