### PR TITLE
gotop: 1.2.9 -> 1.5.0

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Package update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thefloweringash** [comment]
This builds for me on NixOS/aarch64 and Darwin, but my attempts on NixOS/x86_64-linux are causing my nix-daemon to spin at 100% cpu.

**Comment by xeji** [comment]
builds and runs fine on my local x86_64-linux box.

**Review by xeji — APPROVED** [review]

**Comment by xeji** [comment]
> but my attempts on NixOS/x86_64-linux are causing my nix-daemon to spin at 100% cpu.

Since the build succeeded on two other machines, I'd suspect this is some local issue of your system.

**Comment by thefloweringash** [comment]
I can no longer reproduce the issue on the two hosts I was testing on.

**Pull request merged**
