### PR TITLE
boehmgc: 7.6.6 -> 7.6.8

### PR DESCRIPTION
**Pull request by dtzWill**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Hmm, this causes Nix to fail to build:

```
error: build of '/nix/store/hnp4sq1fbcjpjrbdczbpy90nj77l3f65-nix-2.0.4.drv' on 'ssh://wdietz2@presto' failed: builder for '/nix/store/hnp4sq1fbcjpjrbdczbpy90nj77l3f65-nix-2.0.4.drv' failed with exit code 2
builder for '/nix/store/hnp4sq1fbcjpjrbdczbpy90nj77l3f65-nix-2.0.4.drv' failed with exit code 1; last 10 log lines:
    LD     src/nix-collect-garbage/nix-collect-garbage
    LD     src/nix-copy-closure/nix-copy-closure
    LD     src/buildenv/buildenv
    LD     src/nix-channel/nix-channel
    LD     src/build-remote/build-remote
  src/libexpr/eval.o: In function `operator new(unsigned long, GCPlacement, void (*)(void*, void*), void*)':
  /nix/store/1wnijhd418zpapz24bnw1xy000k2bkqp-boehm-gc-7.6.8-dev/include/gc/gc_cpp.h:523: undefined reference to `GC_throw_bad_alloc()'
  collect2: error: ld returned 1 exit status
  make: *** [mk/lib.mk:104: src/libexpr/libnixexpr.so] Error 1
  builder for '/nix/store/hnp4sq1fbcjpjrbdczbpy90nj77l3f65-nix-2.0.4.drv' failed with exit code 2
```

Haven't investigated.

**Comment by dtzWill** [comment]
> warning: unable to download 'https://cache.nixos.org/nar/1x49h2vn3fcpq5rlxjim6lwfcdjpcyk0l20qr8vhw10nyvdjvyfm.nar.xz': Error in the HTTP2 framing layer (16); retrying in 2051 ms
> warning: unable to download 'https://cache.nixos.org/nar/1nbj7b5hrrg2wnsx9k57p7s55gf17r3crq3byc9r9sm825vbk507.nar.xz': HTTP error 200 (curl error: Failure when receiving data from the peer); retrying in 682 ms
> warning: unable to download 'https://cache.nixos.org/nar/1nbj7b5hrrg2wnsx9k57p7s55gf17r3crq3byc9r9sm825vbk507.nar.xz': Timeout was reached (28); retrying in 1147 ms
> warning: unable to download 'https://cache.nixos.org/nar/1x49h2vn3fcpq5rlxjim6lwfcdjpcyk0l20qr8vhw10nyvdjvyfm.nar.xz': Timeout was reached (28); retrying in 4159 ms
> warning: unable to download 'https://cache.nixos.org/nar/1cb8rw2rprr38yx7nhc8gi1nmag1d3qpspznkg7by6v5a10vqbqj.nar.xz': HTTP error 200 (curl error: Timeout was reached); retrying in 1022 ms
> warning: unable to download 'https://cache.nixos.org/nar/1nbj7b5hrrg2wnsx9k57p7s55gf17r3crq3byc9r9sm825vbk507.nar.xz': Timeout was reached (28); retrying in 2408 ms
> error 9 while decompressing xz file
> cannot build derivation '/nix/store/ivdjslg4a2qlzlf2yvnlb9sadm6nin5g-nix-2.1.drv': 2 dependencies couldn't be built
> cannot build derivation '/nix/store/4vgpn3nj5pgvqgs9aw0p1fqfd6msmf33-nix-2.1pre6377_954d1f4d.drv': 3 dependencies couldn't be built
> error: build of '/nix/store/4vgpn3nj5pgvqgs9aw0p1fqfd6msmf33-nix-2.1pre6377_954d1f4d.drv', '/nix/store/ivdjslg4a2qlzlf2yvnlb9sadm6nin5g-nix-2.1.drv' failed

This is no good (and unrelated to this PR)! Looks like it's happening on a non-release version of Nix, `nix --version` on the aarch64 borg builder:

```
nix (Nix) 2.1pre6338_45bcf541
```

@grahamc perhaps we should try either 2.1 (latest release) or bump to latest master?

**Comment by dtzWill** [comment]
Back to this PR:
nix breakage reported earlier no longer occurs, FWIW, may be specific to nix 2.0.4 or something.

**Comment by xeji** [comment]
> Version 7.3 and later require that you download a corresponding (or possibly later) version of libatomic_ops, which should be available in https://github.com/ivmai/libatomic_ops/wiki/Download. The libatomic_ops version corresponding to a particular gc version is the one with the highest version number less than or equal to the gc version number. The current version is also available as gc_source/libatomic_ops-7.6.6.tar.gz.

Sounds like this depends on #46253.

**Comment by dtzWill** [comment]
> Sounds like this depends on #46253.

Good call, not sure it's as critical as it once was -- but let's do this right to be sure.

**Comment by xeji** [comment]
#46253 was merged.
@GrahamcOfBorg build boehmgc

**Comment by 7c6f434c** [comment]
Hm, did this break `asymptote`?

**Comment by dtzWill** [comment]
https://github.com/vectorgraphics/asymptote/commit/38a59370dc5ac720c29e1424614a10f7384b943f

From upstream.  But yes it did.

**Comment by 7c6f434c** [comment]
Good point, I only checked if there was a newer release. Applied in `master`. Thanks for the link.

**Pull request merged**
