### PR TITLE
haskellPackages.graphql-engine: 2.0.5 -> 2.0.7

### PR DESCRIPTION
**Pull request by Lassulus**
I updated the patch to remove mapKeys completely. Since it now also conflicts in some other files and removing it seemed more clean than patching every import.

Hopefully there will be a new release soon, which will also include the new haddock fixes: https://github.com/hasura/graphql-engine/commit/c1bdc993346c3690ed6fe708cf76959e508b24c6

this is the error, which happens during compilation. no idea where the constructors should come from:
```

src-lib/Hasura/Server/Metrics.hs:22:6: error:
    Not in scope: type constructor or class ‘MetricType’
   |
22 |   -> MetricType -- Metric type, e.g. Counter, Gauge
   |      ^^^^^^^^^^

src-lib/Hasura/Server/Metrics.hs:28:20: error:
    Not in scope: data constructor ‘GaugeType’
   |
28 |     "warp_threads" 'GaugeType ()
   |                    ^^^^^^^^^^

src-lib/Hasura/Server/Metrics.hs:31:29: error:
    Not in scope: data constructor ‘GaugeType’
   |
31 |     "websocket_connections" 'GaugeType ()
   |                             ^^^^^^^^^^

src-lib/Hasura/Server/Metrics.hs:34:28: error:
    Not in scope: data constructor ‘GaugeType’
   |
34 |     "active_subscriptions" 'GaugeType ()
   |                            ^^^^^^^^^^

src-lib/Hasura/Server/Metrics.hs:37:32: error:
    Not in scope: data constructor ‘DistributionType’
    Perhaps you meant ‘Distribution’ (imported from System.Metrics)
   |
37 |     "events_fetched_per_batch" 'DistributionType ()
   |                                ^^^^^^^^^^^^^^^^^

src-lib/Hasura/Server/Metrics.hs:40:38: error:
    Not in scope: data constructor ‘GaugeType’
   |
40 |     "num_event_trigger_http_workers" 'GaugeType ()
   |                                      ^^^^^^^^^^

src-lib/Hasura/Server/Metrics.hs:44:24: error:
    Not in scope: data constructor ‘DistributionType’
    Perhaps you meant ‘Distribution’ (imported from System.Metrics)
   |
44 |     "event_queue_time" 'DistributionType ()
   |                        ^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by cdepillabout** [comment]
I took a quick look at this, and my guess is they are now using custom versions of ekg which will need to specially packaged as well:

https://github.com/hasura/graphql-engine/blob/046da3caca6e62f4c24e8437c797d8e00e62d7ce/cabal.project#L70-L78

**Comment by cdepillabout** [comment]
I'd also recommend making a change like this (and then similarly for `ekg`), but this is more just personal preference.  Possibly also add a little more documentation for why these various overrides exist in `configuration-common.nix`:

```diff
diff --git a/pkgs/development/haskell-modules/configuration-common.nix b/pkgs/development/haskell-modules/configuration-common.nix
index 9b6862aa4e5..5da532b87e4 100644
--- a/pkgs/development/haskell-modules/configuration-common.nix
+++ b/pkgs/development/haskell-modules/configuration-common.nix
@@ -1296,12 +1296,15 @@ self: super: {
   # hasura packages need some extra care
   graphql-engine = overrideCabal (super.graphql-engine.override {
     immortal = self.immortal_0_2_2_1;
+    resource-pool = self.hasura-resource-pool;
   }) (drv: {
     patches = [ ./patches/graphql-engine-mapkeys.patch ];
     doHaddock = false;
     version = "2.0.6";
   });
-  pg-client = overrideCabal super.pg-client (drv: {
+  pg-client = overrideCabal (super.pg-client.override {
+    resource-pool = self.hasura-resource-pool;
+  }) (drv: {
     librarySystemDepends = with pkgs; [ postgresql krb5.dev openssl.dev ];
     # wants a running DB to check against
     doCheck = false;
diff --git a/pkgs/development/haskell-modules/non-hackage-packages.nix b/pkgs/development/haskell-modules/non-hackage-packages.nix
index 48ee2ee3a47..6f4f90e353b 100644
--- a/pkgs/development/haskell-modules/non-hackage-packages.nix
+++ b/pkgs/development/haskell-modules/non-hackage-packages.nix
@@ -28,17 +28,11 @@ self: super: {
 
   # hasura graphql-engine is not released to hackage.
   # https://github.com/hasura/graphql-engine/issues/7391
-  #
-  # pg-client and graphql-engine depend on a hasura fork of resource-pool
-  # which is provided by pool.nix
   ci-info = self.callPackage ../misc/haskell/hasura/ci-info.nix {};
-  pg-client = self.callPackage ../misc/haskell/hasura/pg-client.nix {
-    resource-pool = self.callPackage ../misc/haskell/hasura/pool.nix {};
-  };
+  pg-client = self.callPackage ../misc/haskell/hasura/pg-client.nix {};
   graphql-parser = self.callPackage ../misc/haskell/hasura/graphql-parser.nix {};
-  graphql-engine = self.callPackage ../misc/haskell/hasura/graphql-engine.nix {
-    resource-pool = self.callPackage ../misc/haskell/hasura/pool.nix {};
-  };
+  graphql-engine = self.callPackage ../misc/haskell/hasura/graphql-engine.nix {};
+  hasura-resource-pool = self.callPackage ../misc/haskell/hasura/pool.nix {};
 
   # Unofficial fork until PRs are merged https://github.com/pcapriotti/optparse-applicative/pulls/roberth
   # cabal2nix --maintainer roberth https://github.com/hercules-ci/optparse-applicative.git > pkgs/development/misc/haskell/hercules-ci-optparse-applicative.nix
```

**Comment by sternenseemann** [comment]
> You could also look into just using .overrideScope on graphql-engine for the resource-pool override instead of having to also specify it on pg-client. I imagine no one would depend on pg-client by itself.

Overriding in both places (as long as pg-client is exposed) is preferable though imo, as it makes debugging any issues easier.

**Comment by Lassulus** [comment]
Alright, not sure I did it right. felt like I had to compile half of hackage :)
Ideally I want to use overrideCabal and callPackage in the same file. so I don't export all the forked dependencies.
Also I guess there is no use in exporting pg-client?

**Comment by cdepillabout** [comment]
The current state is basically exactly how I was imagining it would look.

All the overrides in `graphql-server` are unfortunate, but there isn't really anything we can do about it since we're not following Stackage Nightly.

I imagine this can probably be marked "Ready for Review"?

**Comment by Lassulus** [comment]
2.0.7 was released, will update this PR shortly

**Comment by Lassulus** [comment]
sadly with 2.0.7 haddock is still failing. so not much changed

**Comment by Lassulus** [comment]
sadly with the new hspec version I'm no longer able to use overrideScope, since it ends in an infinite recursion. will push the new changes though

**Comment by cdepillabout** [comment]
> sadly with the new hspec version I'm no longer able to use overrideScope, since it ends in an infinite recursion.

My guess is that one of the `hspec`-related packages has a test-suite that uses itself, or one of its transitive dependencies.  We often work around this by marking it `dontCheck`.

For instance, this gets it building again (although I haven't actually let it finish building to see if it fails somewhere):

```diff
diff --git a/pkgs/development/haskell-modules/configuration-common.nix b/pkgs/development/haskell-modules/configuration-common.nix
index ad7ff8b29a2..88d586a2bca 100644
--- a/pkgs/development/haskell-modules/configuration-common.nix
+++ b/pkgs/development/haskell-modules/configuration-common.nix
@@ -1295,7 +1295,7 @@ self: super: {
     ekg-json = self.hasura-ekg-json;
     hspec = self.hspec_2_8_3;
     hspec-core = self.hspec-core_2_8_3;
-    hspec-discover = self.hspec-discover_2_8_3;
+    hspec-discover = dontCheck self.hspec-discover_2_8_3;
     tasty-hspec = self.tasty-hspec_1_2;
   })) (drv: {
     patches = [ ./patches/graphql-engine-mapkeys.patch ];
```

One of the unfortunate things about using more recent versions of a package is that you don't get any of the overrides that are already available in Nixpkgs for a package.

For instance, `hspec-core` is marked as `dontCheck` on line 1331 in `configuration-common.nix`.  You'll likely need to mark `hspec-core_2_8_3` as `dontCheck` as well.

**Comment by Lassulus** [comment]
alright, took some time (my store ran full) but this compiles on my system

**Review by cdepillabout — APPROVED** [review]
LGTM, both `haskell-graphql-engine` and `hasura-cli` build on my machine.  (Although because `hspec` is overridden, about half of Hackage needs to build!)

**Pull request merged**
