### PR TITLE
ripasso-cursive: unstable-2019-08-27 -> 0.3.0

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

Updates ripasso-cursive to the latest release. 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alexanderkjall** [comment]
CC @etu

**Comment by etu** [comment]
@GrahamcOfBorg build ripasso-cursive

**Comment by etu** [comment]
Curious, I'm getting the following build failure locally (NixOS x86_64):
```
running 2 tests
test pass::test::get_password_dir_no_env ... ok
test pass::test::get_password_dir ... FAILED

failures:

---- pass::test::get_password_dir stdout ----
thread 'pass::test::get_password_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Generic("failed to locate password directory")', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    pass::test::get_password_dir

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
builder for '/nix/store/rgdqspr9wm7z537a4536jfz0vwr5q4sd-ripasso-cursive-0.2.1.drv' failed with exit code 101
error: build of '/nix/store/rgdqspr9wm7z537a4536jfz0vwr5q4sd-ripasso-cursive-0.2.1.drv' failed
```

But it seems to work on the build bot. The bot managed to build it on both aarch64 and x86_64 linux. So that's fine I guess?

We also have darwin as a new platform, where the build seems to fail. You have the full log here: https://logs.nix.ci/?key=nixos/nixpkgs.72188&attempt_id=abcfb437-2b42-4c2a-8f14-2a6465364206

**Comment by stigtsp** [comment]
> We also have darwin as a new platform, where the build seems to fail. You have the full log here: https://logs.nix.ci/?key=nixos/nixpkgs.72188&attempt_id=abcfb437-2b42-4c2a-8f14-2a6465364206

@alexanderkjall Looks like a problem setting up the test environment? I'll be able to have a look on Darwin tomorrow.

**Comment by stigtsp** [comment]
> I'll be able to have a look on Darwin tomorrow.

Stuck in the snow :snowman_with_snow:

**Comment by stigtsp** [comment]
Thx to @tssm for fixing MacOS build.

Pls don't merge yet. 0.3.0 is out, will update for this new version.

**Comment by stigtsp** [comment]
note: ripasso-cursive builds on macOS with `nix-build -A ripasso-cursive`, but nix-review fails:

```
$ nix-shell -p nix-review --run "nix-review pr 72188"
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/72188/head:refs/nix-review/1
$ git worktree add /Users/user/.cache/nix-review/pr-72188-1/nixpkgs 8d0263863a806af0a6bb66b09d849243e65e6a15
Preparing worktree (detached HEAD 8d0263863a8)
Updating files: 100% (20386/20386), done.
HEAD is now at 8d0263863a8 Merge pull request #74824 from jojosch/dbeaver_6.3.0
$ git merge --no-commit 2523a7f377d8d7fcd09c5e861b6346e162556aed
Auto-merging pkgs/top-level/all-packages.nix
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --max-jobs 4 --option build-use-sandbox true -f /Users/user/.cache/nix-review/pr-72188-1/build.nix
builder for '/nix/store/dd133ml884435n7byw2rgzr71f9gfgyn-source.drv' failed with exit code 1; last 10 log lines:
                                   Dload  Upload   Total   Spent    Left  Speed
  100   129    0   129    0     0    360      0 --:--:-- --:--:-- --:--:--   360
  100  115k    0  115k    0     0   114k      0 --:--:--  0:00:01 --:--:--  210k
  unpacking source archive /private/var/folders/g1/y968ywwx2s9c016g26_dbpcm0000gn/T/nix-build-source.drv-0/release-0.3.0.tar.gz
  dyld: Library not loaded: @rpath/CoreFoundation.framework/Versions/A/CoreFoundation
    Referenced from: /nix/store/rrg9ab9wnnd0n9hkl55miah824vv1xjq-gettext-0.20.1/lib/libintl.8.dylib
    Reason: no suitable image found.  Did find:
   /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation: file system sandbox blocked stat()
  /nix/store/ggw6axmdf4bg17z2pc2zaxpd1fjhsy3d-stdenv-darwin/setup: line 836:   687 Abort trap: 6           tar xf "$fn"
  do not know how to unpack source archive /private/var/folders/g1/y968ywwx2s9c016g26_dbpcm0000gn/T/nix-build-source.drv-0/release-0.3.0.tar.gz
cannot build derivation '/nix/store/zz9jv5havdgas57g382qlmh8drdqwndb-ripasso-cursive-0.3.0-vendor.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vdh81mx9is33q034kpjry94c0nqgzaxw-ripasso-cursive-0.3.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/gqxyd9jpc5lslcyxv22c8cx1igfvjffn-env.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/gqxyd9jpc5lslcyxv22c8cx1igfvjffn-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/72188
1 package failed to build:
ripasso-cursive

[0.0 MiB DL]
error: build log of '/nix/store/vdh81mx9is33q034kpjry94c0nqgzaxw-ripasso-cursive-0.3.0.drv' is not available
$ nix-shell /Users/user/.cache/nix-review/pr-72188-1/shell.nix
```

**Comment by stigtsp** [comment]
On darwin:

Result of `nix-review pr 72188` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were built:</summary>

  - ripasso-cursive
</details>

**Comment by etu** [comment]
@GrahamcOfBorg build ripasso-cursive

**Pull request merged**
