### PR TITLE
ark-pixel-font: dependencies update and fix

### PR DESCRIPTION
**Pull request by TakWolf**
## Description of changes

I am the original maintainer of these python packages. 
They are dependencies of https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name/ar/ark-pixel-font
The config of these packages seems to have some issues, and I have tried to fix them.
But I am not a user of NixOS, I'm not sure if I do the right thing.
These packages require testing and review.

Related to https://github.com/TakWolf/ark-pixel-font/issues/35

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by paparodeo — COMMENTED** [review]
you need to add yourself to https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix otherwise the evaluation breaks trying to resolve `TakWolf`. add a commit to this PR with a commit message: `maintainers: add TakWolf` that adds your info to the `maintainers-list.nix`

**Review by paparodeo — COMMENTED** [review]
`unidata-blocks` is [failing](https://github.com/NixOS/nixpkgs/pull/317143/checks?check_run_id=25883040509)
```
Checking runtime dependencies for unidata_blocks-0.0.11-py3-none-any.whl
  - importlib-resources>=6.4.0 not satisfied by version 6.3.2
  - langcodes>=3.4.0 not satisfied by version 3.3.0
```

<details><summary>can try pythonRelaxDepsHook</summary>

```diff
diff --git a/pkgs/development/python-modules/unidata-blocks/default.nix b/pkgs/development/python-modules/unidata-blocks/default.nix
index bfec08bef886..25ea2a4af322 100644
--- a/pkgs/development/python-modules/unidata-blocks/default.nix
+++ b/pkgs/development/python-modules/unidata-blocks/default.nix
@@ -4,6 +4,7 @@
   fetchPypi,
   pythonOlder,
   pytestCheckHook,
+  pythonRelaxDepsHook,
   nix-update-script,
   hatchling,
   importlib-resources,
@@ -23,12 +24,18 @@ buildPythonPackage rec {
   };
 
   build-system = [ hatchling ];
+  nativeBuildInputs = [ pythonRelaxDepsHook ];
 
   dependencies = [
     importlib-resources
     langcodes
   ];
 
+  pythonRelaxDeps = [
+    "importlib-resources"
+    "langcodes"
+  ];
+
   nativeCheckInputs = [ pytestCheckHook ];
 
   pythonImportsCheck = [ "unidata_blocks" ];
```
</details>

**Comment by h7x4** [comment]
Hello @TakWolf, sorry for my unresponsiveness.

These changes generally look very good, thank you for fixing the packages up.

**Review by h7x4 — APPROVED** [review]
I've built the packages successfully, and the diff looks good to me. Is it ready to merge? @TakWolf

**Comment by TakWolf** [comment]
I think OK, but I'm not an expert for Nix.

Some package are not the latest version, I think it can be resolved in a separate PR

**Pull request merged**
