### PR TITLE
Qt5: 5.9.3 -> 5.10.0

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
I hope that I tackled all required extra packages in other pull requests. (`nox review` is taking ages)

@LnL7 can you try that on Mac?

@ttuegel 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by LnL7 — COMMENTED** [review]
Failure for system: x86_64-darwin

```
/nix/store/cmgjkmgri309v29jxfdfzwzk8i79514y-apple-framework-Foundation/Library/Frameworks/Foundation.framework/Headers/NSPortCoder.h:18:1: warning: method has no return type specified; defaults to 'id' [-Wmissing-method-return-type]
+ portCoderWithReceivePort:(NSPort *)rcvPort sendPort:(NSPort *)sndPort components:(NSArray *)comps NS_DEPRECATED(10_0, 10_7, 2_0, NA);
^
  (id)
qcorewlanengine.mm:290:5: error: type arguments cannot be applied to non-parameterized class 'NSArray'
    NSArray<NSString *> *wifiInterfaces = [CWWiFiClient interfaceNames];
    ^      ~~~~~~~~~~~~
qcorewlanengine.mm:605:5: error: type arguments cannot be applied to non-parameterized class 'NSArray'
    NSArray<NSString *> *wifiInterfaces = [CWWiFiClient interfaceNames];
    ^      ~~~~~~~~~~~~
4 warnings and 2 errors generated.
make[4]: *** [Makefile:2068: .obj/qcorewlanengine.o] Error 1
make[4]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src/plugins/bearer/corewlan'
make[3]: *** [Makefile:46: sub-corewlan-make_first] Error 2
make[3]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src/plugins/bearer'
make[2]: *** [Makefile:78: sub-bearer-make_first] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src/plugins'
make[1]: *** [Makefile:722: sub-plugins-make_first] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
```

**Comment by ttuegel** [comment]
When the Darwin build failure is fixed, I will merge this offline. I have an unmerged fix for a closure-size bug that will also apply here; I'll merge them together to avoid rebuilding the Qt-world twice.

**Comment by bkchr** [comment]
@LnL7 could you try again please?

**Review by LnL7 — COMMENTED** [review]
Failure for system: x86_64-darwin

```
In file included from /nix/store/6fx1x2fzsf03ddrf5lxm5n7f5nnj2jzn-apple-framework-AppKit/Library/Frameworks/AppKit.framework/Headers/AppKit.h:203:
/nix/store/6fx1x2fzsf03ddrf5lxm5n7f5nnj2jzn-apple-framework-AppKit/Library/Frameworks/AppKit.framework/Headers/NSPathComponentCell.h:42:27: warning: 'copy' attribute on property 'image' does not match the property inherited from 'NSCell' [-Wproperty-attribute-mismatch]
@property (copy) NSImage *image;
                          ^
qcocoawindow.mm:1702:29: error: property 'superview' not found on object of type 'id'
        [window.contentView.superview setNeedsDisplay:YES];
                            ^
11 warnings and 1 error generated.
make[4]: *** [Makefile:7439: .obj/qcocoawindow.o] Error 1
make[4]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src/plugins/platforms/cocoa'
make[3]: *** [Makefile:97: sub-cocoa-make_first] Error 2
make[3]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src/plugins/platforms'
make[2]: *** [Makefile:103: sub-platforms-make_first] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src/plugins'
make[1]: *** [Makefile:722: sub-plugins-make_first] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-qtbase-5.10.0.drv-0/qtbase-everywhere-src-5.10.0/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
builder for '/nix/store/qnmpbd6ahqq9pgc0nsb1l5dy639zfkap-qtbase-5.10.0.drv' failed with exit code 2
```

**Comment by LnL7** [comment]
@bkchr This one looks like it might need some debugging, let me know if you want me to look at it.

**Comment by bkchr** [comment]
@LnL7 yeah, it would be nice if you could debug this error.

**Comment by bkchr** [comment]
@LnL7 any updates? :)

**Comment by LnL7** [comment]
Sorry, I've been pretty busy with other stuff.

**Comment by bkchr** [comment]
Okay. 

@ttuegel do you have any Mac OS?

**Comment by LnL7** [comment]
That fixes qtbase, still testing the rest.

**Comment by bkchr** [comment]
👍

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Review by LnL7 — APPROVED** [review]
Darwin builds are ok now, sandboxing doesn't work yet but I don't really want to go down that rabbit hole.

**Comment by LnL7** [comment]
Does an extra qtXX set increase the memory usage by a significant amount? Other evaluations seem to be working fine right now.

**Comment by ttuegel** [comment]
> @ttuegel do you have any Mac OS?

@bkchr No, I have only `x86_64-linux`.

> Does an extra qtXX set increase the memory usage by a significant amount? Other evaluations seem to be working fine right now.

@LnL7 It should not because there are not many packages.

I think we should leave the default Qt 5 version at Qt 5.9.x for now. I have two reasons; one is that Qt 5.9 is an LTS branch, the other is that KDE is still shipping fixes for Qt 5.9 and I suspect Qt 5.10 is going to break things that upstream doesn't even know about yet. I want to re-evaluate this stance after Frameworks 5.42, though.

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Comment by bkchr** [comment]
@ttuegel I saw posts that they already shipped the 5.10 beta for kde neon.

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

:/

**Comment by LnL7** [comment]
From what I can tell this increases the memory usage by almost 200mb causing the evaluator to hit the default heapsize limit.

**Comment by ttuegel** [comment]
> I saw posts that they already shipped the 5.10 beta for kde neon.

Yes, but they haven't shipped any patches for Qt 5.10, which means it isn't ready. In fact, they just had to respin two packages in the Applications release today to patch for Qt 5.9.3, so they obviously aren't caught up yet.

> From what I can tell this increases the memory usage by almost 200mb causing the evaluator to hit the default heapsize limit.

There must be a bug in the package set; there is no way that adding O(10) packages should increase memory use that much!

**Comment by ttuegel** [comment]
> There must be a bug in the package set; there is no way that adding O(10) packages should increase memory use that much!

Hm, it's actually more like O(100) packages because of needing to build libraries with every version of Qt for compatibility. In the long term, I would like to take advantage of the Qt ABI to re-link everything against our latest Qt version; this would drastically cut down on the number of libraries there are to build. In the short term, I think I will just remove `recurseIntoAttrs` from `libsForQt5`.

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Review by ttuegel — APPROVED** [review]

**Comment by ttuegel** [comment]
@bkchr I'm working on merging this now.

**Comment by adisbladis** [comment]
This broke `kimageformats` https://hydra.nixos.org/build/67594049

**Comment by bkchr** [comment]
Fixed in: https://github.com/NixOS/nixpkgs/pull/33927

**Comment by adisbladis** [comment]
There is a whole lot of other breakages too.

@bkchr Could you take a look at these packages:
`akonadi`
`kde`
`kinit`
`kwin`
`kwindowsystem`
`libkscreen`
`plasma-desktop`
`plasma-workspace`

**Comment by bkchr** [comment]
@adisbladis I tested `libkscreen` and `kwindowsystem` and both were downloaded from the cache? I'm on a commit from this morning.

**Comment by adisbladis** [comment]
@bkchr I just greped for usage of `NIX_CFLAGS_COMPILE`.
I know for a fact `plasma-vault` and `kinit` are broken.

**Comment by bkchr** [comment]
Yep, I will look into them, when I got time :)

**Comment by adisbladis** [comment]
Thanks 👍

**Pull request merged**
