### PR TITLE
brave: stable, beta, and nightly + multi-architecture

### PR DESCRIPTION
**Pull request by tstachl**
###### Description of changes

This change adds the beta and nightly builds for brave browser as well as enables multi-platform (arm & x86).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by QuantMint** [comment]
Take a look at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

**Comment by tstachl** [comment]
Will do, thanks 🙏

**Review by anthonyroussel — APPROVED** [review]
Result of `nixpkgs-review pr 197126` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>brave</li>
<li>brave-beta</li>
<li>brave-nightly</li>
</ul>
</details>

**Comment by Occhioverde** [comment]
Apologies for the intrusion, but I would like to ask whether this PR is ready for merging (and if so, when this will be done) as the version of Brave currently available on Nixpkgs is quite dated and bumping it would solve a couple of problems that I encountered.

Thank you very much!

**Comment by tstachl** [comment]
@Occhioverde I started using an overlay to bump the brave version: https://github.com/tstachl/h/blob/master/overlays/default.nix#L11-L17

**Comment by L-as** [comment]
PR looks OK to me but versions should be updated to be the latest. I've tested it locally on the latest nightly on aarch64-linux and it works.

**Comment by m-bdf** [comment]
Hi @tstachl, do you think you could resolve merge conflicts and update Brave versions so we can merge this PR?
Also, squashing all your commits into a single `brave: stable, beta, and nightly + multi-architecture` one (following recommendations from [the CONTRIBUTING doc](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes)) would be super helpful to keep a clean history :)

**Pull request closed without merging**
