### PR TITLE
Updated fcgiwrap's systemd unit to match upstream version.

### PR DESCRIPTION
**Pull request by k0ral**
Current `fcgiwrap` doesn't start on my system because of the following error: `Failed to bind: Address already in use`.
I found that upstream provides a systemd [service](https://github.com/gnosek/fcgiwrap/blob/master/systemd/fcgiwrap.service) and [socket](https://github.com/gnosek/fcgiwrap/blob/master/systemd/fcgiwrap.socket) so I basically aligned nixos with respect to them, and it fixed my issue (provided user/group permissions are set correctly).
There's a small regression though: the module used to allow any kind of socket, while this new version only allows unix sockets.

### CODE REVIEW

**Comment by lethalman** [comment]
I think that's a big regression, as you might have nginx on the host, and fcgiwrap on containers. IIRC I use it this way on my server, have to check though.

**Comment by k0ral** [comment]
I'll update the derivation to fix that regression. It will be more complex, but hopefully completely generic.

**Comment by k0ral** [comment]
Regression fixed. This isn't perfect, but as far as I've tested, it works.

**Comment by lethalman** [comment]
Anyway I wonder why you got that "Failed to bind: Address already in use" anyway, was that using a unix socket? Perhaps the different fcgiwrap processes tried to bind to the same unix socket?

**Comment by lethalman** [comment]
Ah perhaps the problem was on restart. I guess a preStart with rm -f of the unix socket would have worked?

**Comment by k0ral** [comment]
The error came up while using a unix socket, yes. I've just tried adding `ExecStartPre = "rm -f /run/fcgiwrap.sock";` as you suggested, but that doesn't fix it.

**Comment by lethalman** [comment]
I wonder how can multiple fcgiwrap process share the same unix socket with systemd, anyway. Did you test it Like with multiple http connections etc.

**Comment by k0ral** [comment]
I'm not sure how to properly test that, but I've set `services.fcgiwrap.preforkProcesses = 4`, sent multiple HTTP requests concurrently, and everything went fine, does that comply with your requirements ?

On an unrelated note, is there a way to define a sum type in nixlang, and pattern match it ? I'd like to improve the socket parameter to be either a unix socket with a path parameter, or a TCP socket with a URL + port parameter.

**Comment by lethalman** [comment]
You could use nixos types, but it's overkill, don't do it. You can however
check if the socket has prefix tcp or unix.

On Thu, Feb 19, 2015 at 8:39 PM, k0ral <notifications@github.com> wrote:

> I'm not sure how to properly test that, but I've set services.fcgiwrap.preforkProcesses
> = 4, sent multiple HTTP requests concurrently, and everything went fine,
> does that comply with your requirements ?
>
> On an unrelated note, is there a way to define a sum type in nixlang, and
> pattern match it ? I'd like to improve the socket parameter to be either a
> unix socket with a path parameter, or a TCP socket with a URL + port
> parameter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/6440#issuecomment-75120730>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by k0ral** [comment]
I'm using `types.addCheck` for that, are you suggesting there is a better way, or is it ok like that ?

**Comment by k0ral** [comment]
Sorry to push, but is there any reason this PR is still pending validation ? If something is wrong, please let me know and I'll fix accordingly.

**Comment by lethalman** [comment]
Haven't tested it but ok merging.

**Pull request merged**
