### PR TITLE
python310Packages.opencv3: remove

### LINKED ISSUE #74914: Should python3Packages.imutils support opencv4?
**Describe the bug**
Looking at the current derivation of [imutils](https://github.com/NixOS/nixpkgs/blob/bb1013511e1e5edcf314df8321acf2f3c536df0d/pkgs/development/python-modules/imutils/default.nix#L4) it seems opecv's version is set to 3. This makes some code break if you're working on a `opencv4` project, since it'll fall back to version 3.

**To Reproduce**
1. Add `imutils` to an existing `opencv4` project,

Given the following `shell.nix`:
```
{ pkgs ? import <nixpkgs> {} }:

let
  python = pkgs.python37Packages;

  pythonPkgs = with python; [
    opencv4
  ];

  systemPkgs = with pkgs; [
    opencv4
  ];
in
pkgs.mkShell {
  name = "py-env";
  buildInputs = systemPkgs ++ pythonPkgs;
}
```
Verify that's running `openc4`:
```
$ python
Python 3.7.5 (default, Oct 14 2019, 23:08:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.2'
```

Now add `imutils` to `pythonPkgs`:

```
>>> import cv2
>>> cv2.__version__
'3.4.8'
```

**Expected behavior**
The correct version of opencv should be picked. 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.1, NixOS, 20.03pre203904.bb1013511e1 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre203904.bb1013511e1"`
 - channels(usul): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixos.python37Packages.imutils
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by bcdarwin**
## Description of changes

Update all Python packages (and one non-Python package) to use `opencv4` except in the case of `moviepy`, where I removed the optional opencv3 dependence (disabled by default).

See also #256550 where the same was done for non-Python packages (between these two PRs, this leaves only `haskellPackages.{opencv,opencv-extra}`, which are unbuildable as they depend on broken `haskellPackages.repa`, and `opencv3` itself).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 260727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>frigate</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.camelot</li>
    <li>python311Packages.camelot.dist</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>easyocr (python310Packages.easyocr)</li>
    <li>easyocr.dist (python310Packages.easyocr.dist)</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bpycv.dist</li>
    <li>python310Packages.camelot</li>
    <li>python310Packages.camelot.dist</li>
    <li>python310Packages.dremel3dpy</li>
    <li>python310Packages.dremel3dpy.dist</li>
    <li>python310Packages.imagecorruptions</li>
    <li>python310Packages.imagecorruptions.dist</li>
    <li>python310Packages.imantics</li>
    <li>python310Packages.imantics.dist</li>
    <li>python310Packages.imutils</li>
    <li>python310Packages.imutils.dist</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.stytra.dist</li>
    <li>python310Packages.vidstab</li>
    <li>python310Packages.vidstab.dist</li>
    <li>python311Packages.dremel3dpy</li>
    <li>python311Packages.dremel3dpy.dist</li>
    <li>python311Packages.easyocr</li>
    <li>python311Packages.easyocr.dist</li>
    <li>python311Packages.imagecorruptions</li>
    <li>python311Packages.imagecorruptions.dist</li>
    <li>python311Packages.imantics</li>
    <li>python311Packages.imantics.dist</li>
    <li>python311Packages.imutils</li>
    <li>python311Packages.imutils.dist</li>
    <li>python311Packages.vidstab</li>
    <li>python311Packages.vidstab.dist</li>
  </ul>
</details>

**Comment by bcdarwin** [comment]
> Result of `nixpkgs-review pr 260727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package marked as broken and skipped:
> 
>     * frigate
> 
> 
> 2 packages failed to build:
> 
>     * python311Packages.camelot
> 
>     * python311Packages.camelot.dist
> 
> 
> 31 packages built:
> 
>     * easyocr (python310Packages.easyocr)
> 
>     * easyocr.dist (python310Packages.easyocr.dist)
> 
>     * home-assistant-component-tests.dremel_3d_printer
> 
>     * python310Packages.bpycv
> 
>     * python310Packages.bpycv.dist
> 
>     * python310Packages.camelot
> 
>     * python310Packages.camelot.dist
> 
>     * python310Packages.dremel3dpy
> 
>     * python310Packages.dremel3dpy.dist
> 
>     * python310Packages.imagecorruptions
> 
>     * python310Packages.imagecorruptions.dist
> 
>     * python310Packages.imantics
> 
>     * python310Packages.imantics.dist
> 
>     * python310Packages.imutils
> 
>     * python310Packages.imutils.dist
> 
>     * python310Packages.stytra
> 
>     * python310Packages.stytra.dist
> 
>     * python310Packages.vidstab
> 
>     * python310Packages.vidstab.dist
> 
>     * python311Packages.dremel3dpy
> 
>     * python311Packages.dremel3dpy.dist
> 
>     * python311Packages.easyocr
> 
>     * python311Packages.easyocr.dist
> 
>     * python311Packages.imagecorruptions
> 
>     * python311Packages.imagecorruptions.dist
> 
>     * python311Packages.imantics
> 
>     * python311Packages.imantics.dist
> 
>     * python311Packages.imutils
> 
>     * python311Packages.imutils.dist
> 
>     * python311Packages.vidstab
> 
>     * python311Packages.vidstab.dist

python311Packages.camelot builds for me on x86, not sure what the issue is here.

**Comment by lucasew** [comment]
It fails right after start with failed to import setuptools. I will run it again.

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 260727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>frigate</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.camelot</li>
    <li>python311Packages.camelot.dist</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>easyocr (python310Packages.easyocr)</li>
    <li>easyocr.dist (python310Packages.easyocr.dist)</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bpycv.dist</li>
    <li>python310Packages.camelot</li>
    <li>python310Packages.camelot.dist</li>
    <li>python310Packages.dremel3dpy</li>
    <li>python310Packages.dremel3dpy.dist</li>
    <li>python310Packages.imagecorruptions</li>
    <li>python310Packages.imagecorruptions.dist</li>
    <li>python310Packages.imantics</li>
    <li>python310Packages.imantics.dist</li>
    <li>python310Packages.imutils</li>
    <li>python310Packages.imutils.dist</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.stytra.dist</li>
    <li>python310Packages.vidstab</li>
    <li>python310Packages.vidstab.dist</li>
    <li>python311Packages.dremel3dpy</li>
    <li>python311Packages.dremel3dpy.dist</li>
    <li>python311Packages.easyocr</li>
    <li>python311Packages.easyocr.dist</li>
    <li>python311Packages.imagecorruptions</li>
    <li>python311Packages.imagecorruptions.dist</li>
    <li>python311Packages.imantics</li>
    <li>python311Packages.imantics.dist</li>
    <li>python311Packages.imutils</li>
    <li>python311Packages.imutils.dist</li>
    <li>python311Packages.vidstab</li>
    <li>python311Packages.vidstab.dist</li>
  </ul>
</details>

**Comment by bcdarwin** [comment]
I'm unable to reproduce this locally.  (In any case, surely it's not related to opencv.)

**Comment by bcdarwin** [comment]
Pushed an update changing the `camelot` build to use `pyproject` (and explicitly added `setuptools` as a dependency).

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 260727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.camelot</li>
    <li>python311Packages.camelot.dist</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>easyocr (python310Packages.easyocr)</li>
    <li>easyocr.dist (python310Packages.easyocr.dist)</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bpycv.dist</li>
    <li>python310Packages.camelot</li>
    <li>python310Packages.camelot.dist</li>
    <li>python310Packages.dremel3dpy</li>
    <li>python310Packages.dremel3dpy.dist</li>
    <li>python310Packages.imagecorruptions</li>
    <li>python310Packages.imagecorruptions.dist</li>
    <li>python310Packages.imantics</li>
    <li>python310Packages.imantics.dist</li>
    <li>python310Packages.imutils</li>
    <li>python310Packages.imutils.dist</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.stytra.dist</li>
    <li>python310Packages.vidstab</li>
    <li>python310Packages.vidstab.dist</li>
    <li>python311Packages.dremel3dpy</li>
    <li>python311Packages.dremel3dpy.dist</li>
    <li>python311Packages.easyocr</li>
    <li>python311Packages.easyocr.dist</li>
    <li>python311Packages.imagecorruptions</li>
    <li>python311Packages.imagecorruptions.dist</li>
    <li>python311Packages.imantics</li>
    <li>python311Packages.imantics.dist</li>
    <li>python311Packages.imutils</li>
    <li>python311Packages.imutils.dist</li>
    <li>python311Packages.vidstab</li>
    <li>python311Packages.vidstab.dist</li>
  </ul>
</details>

**Comment by bcdarwin** [comment]
For unknown reasons `nixpkgs-review` is adding `/nix/store/yyj8j05h1m5m8hg6pkc8xxvdad05imcw-python3.10-pdfminer-six-20221105` to `propagatedBuildInputs`, which breaks the build somehow due to being the wrong python version.

**Comment by bcdarwin** [comment]
It's because `pdfminer` isn't a Python package as the Python package is `pdfminer-six`, so it gets built with `buildPythonApplication` and `python3 = python310`.

**Review by 2gn — APPROVED** [review]

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 260727` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>easyocr (python310Packages.easyocr)</li>
    <li>easyocr.dist (python310Packages.easyocr.dist)</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bpycv.dist</li>
    <li>python310Packages.camelot</li>
    <li>python310Packages.camelot.dist</li>
    <li>python310Packages.dremel3dpy</li>
    <li>python310Packages.dremel3dpy.dist</li>
    <li>python310Packages.imagecorruptions</li>
    <li>python310Packages.imagecorruptions.dist</li>
    <li>python310Packages.imantics</li>
    <li>python310Packages.imantics.dist</li>
    <li>python310Packages.imutils</li>
    <li>python310Packages.imutils.dist</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.stytra.dist</li>
    <li>python310Packages.vidstab</li>
    <li>python310Packages.vidstab.dist</li>
    <li>python311Packages.camelot</li>
    <li>python311Packages.camelot.dist</li>
    <li>python311Packages.dremel3dpy</li>
    <li>python311Packages.dremel3dpy.dist</li>
    <li>python311Packages.easyocr</li>
    <li>python311Packages.easyocr.dist</li>
    <li>python311Packages.imagecorruptions</li>
    <li>python311Packages.imagecorruptions.dist</li>
    <li>python311Packages.imantics</li>
    <li>python311Packages.imantics.dist</li>
    <li>python311Packages.imutils</li>
    <li>python311Packages.imutils.dist</li>
    <li>python311Packages.vidstab</li>
    <li>python311Packages.vidstab.dist</li>
  </ul>
</details>

**Review by 2gn — APPROVED** [review]

**Pull request merged**
