### PR TITLE
treewide: finalAttrs.doCheck -> finalAttrs.finalPackage.doCheck

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

This will respect `doCheck = false;` overrides, common for cross.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by roberth** [comment]
Doesn't it already?

```
nix-repl> hello.doCheck                                      
true

nix-repl> (hello.overrideAttrs { doCheck = true; }).doCheck
true

nix-repl> (hello.overrideAttrs { doCheck = false; }).doCheck
false

nix-repl> hello                                    
«derivation /nix/store/nvl9ic0pj1fpyln3zaqrf4cclbqdfn1j-hello-2.12.1.drv»

nix-repl> hello.overrideAttrs { doCheck = true; }            
«derivation /nix/store/nvl9ic0pj1fpyln3zaqrf4cclbqdfn1j-hello-2.12.1.drv»

nix-repl> hello.overrideAttrs { doCheck = false; }
«derivation /nix/store/6n4az7cnydvgj1ixk4bmg50vx7nih3xm-hello-2.12.1.drv»


```

Fwiw, it wouldn't work with [cleanAttrs](#217243) when going through `finalPackage`.
Also theoretically you could "fake it" with `passthru` then.

**Comment by roberth** [comment]
Right, I forgot that `mkDerivation` applies some logic between `doCheck` coming in and `doCheck` going out.
Makes sense. It's unfortunate that we don't have a more direct way to access that outgoing `doCheck`, but I don't see a good enough alternative that doesn't massively rewrite `make-derivation.nix`, other than yours!

**Review by roberth — APPROVED** [review]

**Review by SuperSandro2000 — COMMENTED** [review]
This is super unintuitive and I expect that you can create such a PR every 6 months. Can we somehow prevent this or do something to prevent this error or fix the underlying issue?

**Comment by SuperSandro2000** [comment]
It would be a bad idea to set this by default in mkDerivation, would it?

**Comment by pbsds** [comment]
doCheck is by default false as i understand.

**Comment by pbsds** [comment]
We could maybe lift most cross logic out of stdenv.mkDerivation and rather compose it in using overrideAttrs.

**Comment by pbsds** [comment]
But onto something more immediately actionable: are we good to merge this?

**Comment by roberth** [comment]
Yes, thank you for reminding me. Architecture improvements (like I suggested) should follow from things we find problematic in the code, not the opposite where we wait for beautiful elegant whatever before we solve our actual problems.

**Pull request merged**
