### PR TITLE
 nixos/slurm: set slurmd KillMode and add extraConfigPaths

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change

- set slurmd systemd service `KillMode` to `process`: In the standard configuration all jobs are killed when slurmd is restarted (e.g. when the configuration is updated). This is quite disruptive in a production environment. Setting `KillMode=process` kills only slurmd but not slurmstepd and thus not the running job. This is also the standard behavior of the systemd files delivered from slurm.
- add new option `extraConfigPaths`: This allows to add custom config files to slurm configuration. All plugins that come with config files need to be in the same directory as slurm.conf.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
`nixos/tests/slurm.nix` succeeds.
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg test slurm

**Comment by markuskowa** [comment]
@GrahamcOfBorg test slurm

**Comment by Mic92** [comment]
@GrahamcOfBorg build nixosTests.slurm

this is a workaround

**Comment by Mic92** [comment]
The evaluation error you see is now legitimate the same test evaluates locally.

**Comment by markuskowa** [comment]
Sorry, looks like I forgot to push the latest version.

**Comment by Mic92** [comment]
@GrahamcOfBorg build nixosTests.slurm

**Comment by markuskowa** [comment]
This seems to be a timing issue now. The test passes just fine locally.
@GrahamcOfBorg build nixosTests.slurm

**Comment by markuskowa** [comment]
@GrahamcOfBorg build nixosTests.slurm

**Comment by markuskowa** [comment]
I am note sure how to fix this. The test behaves different on my local (NixOS) machine.

**Comment by markuskowa** [comment]
@GrahamcOfBorg build nixosTests.slurm

**Comment by markuskowa** [comment]
It looks like some weird timing issue. The test runs just fine locally. Let's see if waiting for the TCP port to appear helps.

**Comment by markuskowa** [comment]
@GrahamcOfBorg build nixosTests.slurm

**Comment by markuskowa** [comment]
OK, that worked :confetti_ball:. The aarch64 failure is now due to a broken libjpeg-turbo.

**Pull request merged**
