### PR TITLE
openai-whisper-cpp: 1.5.2 -> 1.5.4

### PR DESCRIPTION
**Pull request by amalgame21**
## Description of changes
openai-whisper-cpp: 1.5.2 -> 1.5.4
I would like to make a PR to add `cudaSupport` for 1.5.4 after this is merged.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hughobrien** [comment]
What is the need to store the models locally versus in the `.local/share/whisper` dir?

**Comment by hughobrien** [comment]
Result of `nixpkgs-review pr 279854` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>openai-whisper-cpp</li>
  </ul>
</details>

**Comment by amalgame21** [comment]
Sorry I deleted `models_path` because I was just following the result of the previous commit. 
This is my first ever PR attempt, I will try to patch that out.
May I ask where I can find the `USAGE` section you mentioned so that I can follow?
Do you mean the `Usage` under the Docker section in their main github page?

**Comment by hughobrien** [comment]
Here: https://github.com/ggerganov/whisper.cpp/blob/c46886f5991b0119db5eee76ad75e3801b240e7f/models/download-ggml-model.sh#L60

The current commit is failing with
```
       > applying patch /nix/store/v011mv5sspcjs7j631hdrdbjpg5cn6bv-download-models.patch
       > patching file models/download-ggml-model.sh
       > patch: **** malformed patch at line 21:  models=(
```
Patch files are not so easy to edit due to the metadata needing updating also. If you regenerate it it should work.

**Comment by hughobrien** [comment]
Try this
```
--- a/models/download-ggml-model.sh
+++ b/models/download-ggml-model.sh
@@ -9,18 +9,6 @@
 src="https://huggingface.co/ggerganov/whisper.cpp"
 pfx="resolve/main/ggml"
 
-# get the path of this script
-function get_script_path() {
-    if [ -x "$(command -v realpath)" ]; then
-        echo "$(dirname "$(realpath "$0")")"
-    else
-        local ret="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
-        echo "$ret"
-    fi
-}
-
-models_path="${2:-$(get_script_path)}"
-
 # Whisper models
 models=(
     "tiny.en"
@@ -56,8 +44,8 @@ function list_models {
     printf "\n\n"
 }
 
-if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
-    printf "Usage: $0 <model> [models_path]\n"
+if [ "$#" -ne 1 ]; then
+    printf "Usage: $0 <model>\n"
     list_models
 
     exit 1
@@ -82,8 +70,6 @@ fi
 
 printf "Downloading ggml model $model from '$src' ...\n"
 
-cd "$models_path"
-
 if [ -f "ggml-$model.bin" ]; then
     printf "Model $model already exists. Skipping download.\n"
     exit 0
@@ -105,7 +91,7 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-printf "Done! Model '$model' saved in '$models_path/ggml-$model.bin'\n"
+printf "Done! Model '$model' saved in 'ggml-$model.bin'\n"
 printf "You can now use it like this:\n\n"
-printf "  $ ./main -m $models_path/ggml-$model.bin -f samples/jfk.wav\n"
+printf "  $ ./main -m ggml-$model.bin -f samples/jfk.wav\n"
 printf "\n"
```

**Comment by amalgame21** [comment]
Thank you very much for your help!

**Comment by hughobrien** [comment]
No problem, remember you'll need to squash these commits down also. Something like below if you haven't done it before.
```
git reset --soft origin/master
git add .
git commit -m "openai-whisper-cpp: 1.5.2 -> 1.5.4"
git push -f
```

**Comment by amalgame21** [comment]
Thanks for your reminder!
I am using github webpage only and I need some time to setup git to link to this account to squash those commits.

**Comment by amalgame21** [comment]
wow magic

**Comment by hughobrien** [comment]
Result of `nixpkgs-review pr 279854` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>openai-whisper-cpp</li>
  </ul>
</details>

**Review by hughobrien — APPROVED** [review]

**Review by viraptor — APPROVED** [review]

**Comment by viraptor** [comment]
works on aarch-darwin, thanks

**Pull request merged**
