### PR TITLE
nixos/mautrix-telegram: doc update and cleanup

### PR DESCRIPTION
**Pull request by pacien**
- nixos/mautrix-telegram: add documentation for setting arbitrary secrets
- Revert "nixos/mautrix-telegram: substitute secrets in config file at runtime (#112966)"
- nixos/mautrix-telegram: document JSON env var config

### CODE REVIEW

**Review by CRTified — APPROVED** [review]
The code changes only revert the nix-specific substitution method, so this will be fine. Everything else relies on (new) upstream features, so there is not much that can break. I currently don't have time to test the code.

The upstream documentation does not seem to have anything about `json::` substitutions, but the author of the bridge [describes the format here](https://github.com/mautrix/telegram/issues/584#issuecomment-1250027272) (also linked in the commit messages).

Assuming that @pacien likely tested this modification, I think it is ready to merge.

**Comment by pacien** [comment]
Quoting Carl Richard Theodor Schneider (2022-11-20 21:19:11)
> Assuming that @pacien likely tested this modification, I think it is
> ready to merge.

Yes, I forgot to mention that ; I'm currently running the proposed
changes locally successfully.

**Review by winterqt — APPROVED** [review]
Thanks!

**Comment by winterqt** [comment]
(Out of curiosity, where did the first commit by @CRTified come from? e.g. I don't see another PR it was taken from.)

**Comment by pacien** [comment]
Quoting Winter (2022-11-21 14:47:28)
> (Out of curiosity, where did the first commit by @CRTified come from?
> e.g. I don't see another PR it was taken from.)

It comes from #103347.

**Comment by CRTified** [comment]
And for completeness: My PR got closed as an automatic action in the commit message from https://github.com/NixOS/nixpkgs/pull/201560/commits/6070b99d6a89a0f0b792e2e8405125153a65c6e3.

**Comment by Luflosi** [comment]
This did not work for me at all, see https://github.com/mautrix/telegram/issues/584#issuecomment-1362065846.
Can anyone reproduce the issue?
I put `MAUTRIX_TELEGRAM_BRIDGE_LOGIN_SHARED_SECRET_MAP='json::{"mydomain.com":"mysecret"}'` into the file specified with `environmentFile` and removed the obsolete config file at `/var/lib/mautrix-telegram/config.json`.
After patching `mautrix` with my patch in the linked issue, it seems to work. I wasted several hours trying to create an overlay for `mautrix` because `pkgs/servers/mautrix-telegram/default.nix` also has a python override.

**Pull request merged**
