### PR TITLE
herbstluftwm: use small asciidoc

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srhb** [comment]
cc @ThibautMarty since you changed it to -full in #114566

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117623` at 7a4175c8 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>herbstluftwm</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/applications/window-managers/herbstluftwm/default.nix:43:5:
```
   |
43 |     ./test-path-environment.patch
   |     ^
```
</li>
  </ul>
</details>

**Comment by ThibautMarty** [comment]
LGTM. `asciidoc-full` was required but not anymore.

<details>
<summary>For the record:</summary>
Builds with the patch (or equivalent in `all-packages.nix`) :

- on c0e881852006b132236cbf0301bd1939bb50867e (last `nixpkgs-unstable` containing latest asciidoc package commits):
    - built successfully: pkgsCross.aarch64-multiplatform.herbstluftwm
    - built successfully: herbstluftwm
- on bfc062e4cf4d5be34ad3a26a8f0dd031523230c2 (commit evaluated in hydra that does not contains three latest commits on asciidoc package: e48b0ede04e07de95a7974a7829f9ae4ffd1a334, 2e146c3a6baed521739e941f556a19a1f63c7cbb, fb6c18938b88c3a46b7604d7c2375d9be4e4ffc0):
    - NOT built successfully: herbstluftwm
    ```
    Sourcing pytest-check-hook
    Using pytestCheckPhase
    @nix { "action": "setPhase", "phase": "unpackPhase" }
    unpacking sources
    unpacking source archive /nix/store/1whwrqisb3ig1aya768hh2mmvcv73x9g-herbstluftwm-0.9.1.tar.gz
    source root is herbstluftwm-0.9.1
    setting SOURCE_DATE_EPOCH to timestamp 1609133311 of file herbstluftwm-0.9.1/doc/hlwm-doc.json
    @nix { "action": "setPhase", "phase": "patchPhase" }
    patching sources
    applying patch /nix/store/68i5j28fzg9gfsjvwn14nmbyind0hz2c-test-path-environment.patch
    patching file tests/conftest.py
    Hunk #1 succeeded at 45 (offset 2 lines).
    patching script interpreter paths in doc/gendoc.py
    doc/gendoc.py: interpreter directive changed from "/usr/bin/env python3" to "/nix/store/2wwb85hrvvfzkhrlwcj3pqi60nlbi9cq-python3-3.8.7/bin/python3"
    @nix { "action": "setPhase", "phase": "configurePhase" }
    configuring
    fixing cmake files...
    cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_LOCALEDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/0fmbaq6kj09dra5mm6048dk87c8i7fd3-herbstluftwm-0.9.1-doc/share/doc/Herbstluftwm -DCMAKE_INSTALL_INFODIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/90329rz5jribp7ww8c0agpqpn6ymqr32-herbstluftwm-0.9.1-man/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/include -DCMAKE_INSTALL_SBINDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/wcz8lsibkw2nikdb0bjl22p75lfwahzr-binutils-2.35.1/bin/strip -DCMAKE_RANLIB=/nix/store/wcz8lsibkw2nikdb0bjl22p75lfwahzr-binutils-2.35.1/bin/ranlib -DCMAKE_AR=/nix/store/wcz8lsibkw2nikdb0bjl22p75lfwahzr-binutils-2.35.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1 -DCMAKE_INSTALL_SYSCONF_PREFIX=/nix/store/wpi5dksp2b5vk1y95f0zk7l75k7wp6rr-herbstluftwm-0.9.1/etc 
    -- The C compiler identification is GNU 10.2.0
    -- The CXX compiler identification is GNU 10.2.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /nix/store/fr5gpdf3m2nqq6g3v6x1vvgi7cg6px8b-gcc-wrapper-10.2.0/bin/gcc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /nix/store/fr5gpdf3m2nqq6g3v6x1vvgi7cg6px8b-gcc-wrapper-10.2.0/bin/g++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found X11: /nix/store/4agvahxs45bl614ksxvv3zlnsf9v6nnx-xorgproto-2020.1/include   
    -- Looking for XOpenDisplay in /nix/store/wjz5m03hzggpzjvb5i4vxffrjlh3z66n-libX11-1.7.0/lib/libX11.so;/nix/store/c3y8m27dkr1vs608m11v3x67chwl9za6-libXext-1.3.4/lib/libXext.so
    -- Looking for XOpenDisplay in /nix/store/wjz5m03hzggpzjvb5i4vxffrjlh3z66n-libX11-1.7.0/lib/libX11.so;/nix/store/c3y8m27dkr1vs608m11v3x67chwl9za6-libXext-1.3.4/lib/libXext.so - found
    -- Looking for gethostbyname
    -- Looking for gethostbyname - found
    -- Looking for connect
    -- Looking for connect - found
    -- Looking for remove
    -- Looking for remove - found
    -- Looking for shmat
    -- Looking for shmat - found
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        CMAKE_EXPORT_NO_PACKAGE_REGISTRY
        CMAKE_INSTALL_BINDIR
        CMAKE_INSTALL_DOCDIR
        CMAKE_INSTALL_INCLUDEDIR
        CMAKE_INSTALL_INFODIR
        CMAKE_INSTALL_LIBDIR
        CMAKE_INSTALL_LIBEXECDIR
        CMAKE_INSTALL_LOCALEDIR
        CMAKE_INSTALL_MANDIR
        CMAKE_INSTALL_OLDINCLUDEDIR
        CMAKE_INSTALL_SBINDIR
        CMAKE_POLICY_DEFAULT_CMP0025
    
    
    -- Build files have been written to: /build/herbstluftwm-0.9.1/build
    cmake: enabled parallel building
    @nix { "action": "setPhase", "phase": "buildPhase" }
    building
    build flags: -j4 -l4 SHELL=/nix/store/dskh7v2h3ly3kdkfk3xmjlqql1zr0hnw-bash-4.4-p23/bin/bash
    Scanning dependencies of target doc_man_herbstclient
    Scanning dependencies of target herbstclient
    Scanning dependencies of target herbstluftwm
    Scanning dependencies of target doc_html_herbstluftwm-tutorial
    [  1%] Generating herbstclient.1
    [  2%] Building C object ipc-client/CMakeFiles/herbstclient.dir/main.c.o
    [  4%] Generating herbstluftwm-tutorial.html
    [  5%] Building CXX object src/CMakeFiles/herbstluftwm.dir/main.cpp.o
    [  7%] Building C object ipc-client/CMakeFiles/herbstclient.dir/client-utils.c.o
    [  8%] Building C object ipc-client/CMakeFiles/herbstclient.dir/ipc-client.c.o
    [ 10%] Linking C executable ../herbstclient
    [ 10%] Built target herbstclient
    Scanning dependencies of target doc_man_herbstluftwm
    [ 11%] Generating herbstluftwm.1
    a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/nix/store/w75p6rp8a266f5n5nwqyni2y4k7pc8cl-asciidoc-8.6.9/etc/asciidoc/docbook-xsl/manpage.xsl" "/build/herbstluftwm-0.9.1/build/doc/herbstclient.xml" returned non-zero exit status 127
    make[2]: *** [doc/CMakeFiles/doc_man_herbstclient.dir/build.make:82: doc/herbstclient.1] Error 1
    make[1]: *** [CMakeFiles/Makefile2:243: doc/CMakeFiles/doc_man_herbstclient.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 13%] Building CXX object src/CMakeFiles/herbstluftwm.dir/arglist.cpp.o
    [ 13%] Built target doc_html_herbstluftwm-tutorial
    [ 14%] Building CXX object src/CMakeFiles/herbstluftwm.dir/argparse.cpp.o
    [ 16%] Building CXX object src/CMakeFiles/herbstluftwm.dir/attribute.cpp.o
    [ 17%] Building CXX object src/CMakeFiles/herbstluftwm.dir/byname.cpp.o
    [ 19%] Building CXX object src/CMakeFiles/herbstluftwm.dir/client.cpp.o
    [ 20%] Building CXX object src/CMakeFiles/herbstluftwm.dir/clientmanager.cpp.o
    a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/nix/store/w75p6rp8a266f5n5nwqyni2y4k7pc8cl-asciidoc-8.6.9/etc/asciidoc/docbook-xsl/manpage.xsl" "/build/herbstluftwm-0.9.1/build/doc/herbstluftwm.xml" returned non-zero exit status 127
    make[2]: *** [doc/CMakeFiles/doc_man_herbstluftwm.dir/build.make:82: doc/herbstluftwm.1] Error 1
    make[1]: *** [CMakeFiles/Makefile2:297: doc/CMakeFiles/doc_man_herbstluftwm.dir/all] Error 2
    [ 22%] Building CXX object src/CMakeFiles/herbstluftwm.dir/command.cpp.o
    [ 23%] Building CXX object src/CMakeFiles/herbstluftwm.dir/completion.cpp.o
    [ 25%] Building CXX object src/CMakeFiles/herbstluftwm.dir/decoration.cpp.o
    [ 26%] Building CXX object src/CMakeFiles/herbstluftwm.dir/desktopwindow.cpp.o
    [ 28%] Building CXX object src/CMakeFiles/herbstluftwm.dir/entity.cpp.o
    [ 29%] Building CXX object src/CMakeFiles/herbstluftwm.dir/ewmh.cpp.o
    [ 31%] Building CXX object src/CMakeFiles/herbstluftwm.dir/fixprecdec.cpp.o
    [ 32%] Building CXX object src/CMakeFiles/herbstluftwm.dir/floating.cpp.o
    [ 34%] Building CXX object src/CMakeFiles/herbstluftwm.dir/framedata.cpp.o
    [ 35%] Building CXX object src/CMakeFiles/herbstluftwm.dir/framedecoration.cpp.o
    [ 37%] Building CXX object src/CMakeFiles/herbstluftwm.dir/frameparser.cpp.o
    [ 38%] Building CXX object src/CMakeFiles/herbstluftwm.dir/frametree.cpp.o
    [ 40%] Building CXX object src/CMakeFiles/herbstluftwm.dir/hlwmcommon.cpp.o
    [ 41%] Building CXX object src/CMakeFiles/herbstluftwm.dir/hook.cpp.o
    [ 43%] Building CXX object src/CMakeFiles/herbstluftwm.dir/hookmanager.cpp.o
    [ 44%] Building CXX object src/CMakeFiles/herbstluftwm.dir/ipc-server.cpp.o
    [ 46%] Building CXX object src/CMakeFiles/herbstluftwm.dir/keycombo.cpp.o
    [ 47%] Building CXX object src/CMakeFiles/herbstluftwm.dir/keymanager.cpp.o
    [ 49%] Building CXX object src/CMakeFiles/herbstluftwm.dir/layout.cpp.o
    [ 50%] Building CXX object src/CMakeFiles/herbstluftwm.dir/metacommands.cpp.o
    [ 52%] Building CXX object src/CMakeFiles/herbstluftwm.dir/monitor.cpp.o
    [ 53%] Building CXX object src/CMakeFiles/herbstluftwm.dir/monitordetection.cpp.o
    [ 55%] Building CXX object src/CMakeFiles/herbstluftwm.dir/monitormanager.cpp.o
    [ 56%] Building CXX object src/CMakeFiles/herbstluftwm.dir/mouse.cpp.o
    [ 58%] Building CXX object src/CMakeFiles/herbstluftwm.dir/mousemanager.cpp.o
    [ 59%] Building CXX object src/CMakeFiles/herbstluftwm.dir/mousedraghandler.cpp.o
    [ 61%] Building CXX object src/CMakeFiles/herbstluftwm.dir/namedhook.cpp.o
    [ 62%] Building CXX object src/CMakeFiles/herbstluftwm.dir/object.cpp.o
    [ 64%] Building CXX object src/CMakeFiles/herbstluftwm.dir/panelmanager.cpp.o
    [ 65%] Building CXX object src/CMakeFiles/herbstluftwm.dir/rectangle.cpp.o
    [ 67%] Building CXX object src/CMakeFiles/herbstluftwm.dir/regexstr.cpp.o
    [ 68%] Building CXX object src/CMakeFiles/herbstluftwm.dir/root.cpp.o
    [ 70%] Building CXX object src/CMakeFiles/herbstluftwm.dir/rulemanager.cpp.o
    [ 71%] Building CXX object src/CMakeFiles/herbstluftwm.dir/rules.cpp.o
    [ 73%] Building CXX object src/CMakeFiles/herbstluftwm.dir/settings.cpp.o
    [ 74%] Building CXX object src/CMakeFiles/herbstluftwm.dir/stack.cpp.o
    [ 76%] Building CXX object src/CMakeFiles/herbstluftwm.dir/tag.cpp.o
    [ 77%] Building CXX object src/CMakeFiles/herbstluftwm.dir/tagmanager.cpp.o
    [ 79%] Building CXX object src/CMakeFiles/herbstluftwm.dir/theme.cpp.o
    [ 80%] Building CXX object src/CMakeFiles/herbstluftwm.dir/tilingresult.cpp.o
    [ 82%] Building CXX object src/CMakeFiles/herbstluftwm.dir/tmp.cpp.o
    [ 83%] Building CXX object src/CMakeFiles/herbstluftwm.dir/types.cpp.o
    [ 85%] Building CXX object src/CMakeFiles/herbstluftwm.dir/utils.cpp.o
    [ 86%] Building CXX object src/CMakeFiles/herbstluftwm.dir/x11-types.cpp.o
    [ 88%] Building CXX object src/CMakeFiles/herbstluftwm.dir/x11-utils.cpp.o
    [ 89%] Building CXX object src/CMakeFiles/herbstluftwm.dir/xconnection.cpp.o
    [ 91%] Building CXX object src/CMakeFiles/herbstluftwm.dir/xkeygrabber.cpp.o
    [ 92%] Building CXX object src/CMakeFiles/herbstluftwm.dir/xmainloop.cpp.o
    [ 94%] Linking CXX executable ../herbstluftwm
    [ 94%] Built target herbstluftwm
    make: *** [Makefile:149: all] Error 2
    ```
</details>

**Comment by SuperSandro2000** [comment]
> LGTM. `asciidoc-full` was required but not anymore.

if a feature is required which is not part of the default asciidoc it would be better to enable it explicitly instead of using -full.

**Pull request merged**
