### PR TITLE
elmPackages: share node-env.nix, add elm-live & elm-xref

### PR DESCRIPTION
**Pull request by turboMaCk**
Reusing shared `nix-env` - see [discussion in this PR](https://github.com/NixOS/nixpkgs/pull/43376#discussion_r314977154). I've also added 2 more node tools which seems to be widely used

- elm-live
- elm-xref

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @domenkozar

### CODE REVIEW

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
I see [failure here](https://github.com/NixOS/nixpkgs/pull/67439/checks?check_run_id=204527507) I'm going to investigate and fix the problem - will ping you later.

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
@domenkozar I think I got it. Seems there is some problem with elm-analyse@0.16.4

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
I really can't really express how much I aprichiate that you find time to review all the thing I've generated in past few months in words. You're my OSS hero of the 2019 for sure, thanks <3

**Comment by domenkozar** [comment]
You're welcome - seems like macOS failures are unrelated and due to macos machine issues.

**Pull request merged**
