### PR TITLE
python313: 3.13.0a3 -> 3.13.0a5

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes
https://docs.python.org/3.13/whatsnew/changelog.html#python-3-13-0-alpha-5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 289190` at 3278f8fc run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/f7a8e79697b2340cd152c4f10d634253">python313</a></li>
  </ul>
</details>

**Comment by mweinelt** [comment]
```
dyld[71479]: Library not loaded: /lib/libpython3.13.dylib
  Referenced from: <49A2F269-84BC-380C-9CCD-A0BB4F45CD7F> /nix/store/jvq224fk3rmyf8mknwnlgvkdh9s28bz4-python3-3.13.0a4/bin/python3.13
  Reason: tried: '/lib/libpython3.13.dylib' (no such file), '/usr/local/lib/libpython3.13.dylib' (no such file), '/usr/lib/libpython3.13.dylib' (no such file, not in dyld cache)
/nix/store/zf8hff9bnlfix7l7gjsnv3jc22lxzzxx-stdenv-darwin/setup: line 176: 71478 Broken pipe: 13         find $out -name "*.py"
     71479 Abort trap: 6           | $out/bin/python -m compileall -q -f -x "lib2to3" -i -

**Comment by natsukium** [comment]
It will be fixed in 3.13.0a5. https://github.com/python/cpython/issues/115737

For 3.13.0a4, we need [this patch](https://github.com/python/cpython/commit/074bbec9c4911da1d1155e56bd1693665800b814).
```
(fetchpatch {
  url = "https://github.com/python/cpython/commit/074bbec9c4911da1d1155e56bd1693665800b814.patch";
  hash = "sha256-7H0f54GVXkPsQs1VS8mbyw/9fXYACmJ3TKya6ZXVGhE=";
 })
```

**Comment by mweinelt** [comment]
@ofborg build python313

**Comment by mweinelt** [comment]
Still looks broken on 3.13.0a5

**Comment by natsukium** [comment]
You forgot to push! 😄

**Comment by mweinelt** [comment]
Damn! :facepalm:

**Comment by natsukium** [comment]
Finally, it is possible to disable GIL from Python 3.13.0a5.
https://peps.python.org/pep-0703/
https://github.com/python/cpython/pull/116338

How about adding the following option to make it easier to override?
I have confirmed that the GIL is disabled on x86_64-linux and aarch64-darwin.

```diff
diff --git a/pkgs/development/interpreters/python/cpython/default.nix b/pkgs/development/interpreters/python/cpython/default.nix
index 6f6da043d845..bc717d9f4f41 100644
--- a/pkgs/development/interpreters/python/cpython/default.nix
+++ b/pkgs/development/interpreters/python/cpython/default.nix
@@ -60,6 +60,7 @@
 , static ? stdenv.hostPlatform.isStatic
 , enableFramework ? false
 , noldconfigPatch ? ./. + "/${sourceVersion.major}.${sourceVersion.minor}/no-ldconfig.patch"
+, disableGil ? false
 
 # pgo (not reproducible) + -fno-semantic-interposition
 # https://docs.python.org/3/using/configure.html#cmdoption-enable-optimizations
@@ -405,6 +406,8 @@ in with passthru; stdenv.mkDerivation (finalAttrs: {
     "--enable-shared"
   ] ++ optionals enableFramework [
     "--enable-framework=${placeholder "out"}/Library/Frameworks"
+  ] ++ optionals (disableGil && pythonAtLeast "3.13") [
+    "--disable-gil"
   ] ++ optionals enableOptimizations [
     "--enable-optimizations"
   ] ++ optionals (sqlite != null) [

```

**Comment by mweinelt** [comment]
Sure, feel free to push it on top, but let's start using `lib.enableFeature`.

**Comment by natsukium** [comment]
Fair enough. The negative flag is hard to understand.
 I agree with `enableGIL`.

**Comment by natsukium** [comment]
updated

**Comment by mweinelt** [comment]
@ofborg build "(python313.override { enableGil = false; })"

:crossed_fingers:

**Comment by mweinelt** [comment]
Ouch, the tokenization....

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 289190 --extra-nixpkgs-config '{
  packageOverrides = pkgs: rec {
    python313 = pkgs.python313.override { enableGIL = false; };
  };
}'` at 8837f2fe run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python313</li>
    <li>python313Full</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 289190 --extra-nixpkgs-config '{
  packageOverrides = pkgs: rec {
    python313 = pkgs.python313.override { enableGIL = false; };
  };
}'` at 8837f2fe run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>python313</li>
    <li>python313.debug</li>
    <li>python313Full</li>
    <li>python313Full.debug</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
OK, the GIL changes won't apply due to the refactor. Doing it manually.

**Pull request merged**
