### PR TITLE
{btcpayserver,nbxplorer}: use buildDotnetModule

### PR DESCRIPTION
**Pull request by IvarWithoutBones**
###### Motivation for this change
Done both for consistency, and easier package maintaining.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
Looking at the existing derivation, it probably won't be too difficult :)

Extending the module shouldn't be required, as we can pass the [flags it needs](https://github.com/NixOS/nixpkgs/blob/34590eea1ec939eaa7973a16a5623416d8824e97/pkgs/applications/blockchains/btcpayserver/default.nix#L37) to dotnet using the [`dotnetPhaseFlags`](https://nixos.org/manual/nixpkgs/unstable/#packaging-a-dotnet-application) arrays. We can also append to `makeWrapperArgs` for [it's wrapping](https://github.com/NixOS/nixpkgs/blob/34590eea1ec939eaa7973a16a5623416d8824e97/pkgs/applications/blockchains/btcpayserver/default.nix#L46), as `buildDotnetModule` already runs `makeWrapper` on all binaries.

**Comment by erikarvstedt** [comment]
I'll implement it.

**Comment by IvarWithoutBones** [comment]
LGTM, thanks for the work! I'm happy the function is getting some use :slightly_smiling_face: 

I merged it into the PRs branch, with just 1 change:
```diff
   preInstall = ''
-    gappsWrapperArgs+=(--run "cd $out/lib/btcpayserver")
+    makeWrapperArgs+=(--run "cd $out/lib/btcpayserver")
   '';
```

**Comment by IvarWithoutBones** [comment]
> This doesn't work because `makeWrapperArgs` is not expanded as an array, so all elements except the first (`--run`) are discarded. You'll see this when comparing the resulting `bin/btcpayserver` files. You can use my branch as is.

Oh, I somehow never noticed. I'll revert the change for now, and PR a fix to `buildDotnetModule`.

**Comment by erikarvstedt** [comment]
Can you remove `gappsWrapperArgs`? This specific to the gnome toolchain.

**Review by erikarvstedt — APPROVED** [review]
Ah, got it. Nice work!

Things done: Tested via the [nix-bitcoind VM tests](https://gist.github.com/erikarvstedt/d5b25badb375973d2e34fee7b87a23e3).

**Review by prusnak — CHANGES_REQUESTED** [review]

**Review by erikarvstedt — APPROVED** [review]
Things done: Tested via the [nix-bitcoind VM tests](https://gist.github.com/erikarvstedt/d5b25badb375973d2e34fee7b87a23e3).

**Review by erikarvstedt — CHANGES_REQUESTED** [review]
[Fixup](https://github.com/erikarvstedt/nixpkgs/commits/use/nbxporer-buildDotnetModule-ea-2/). Please see the commit msgs for an explanation.

**Pull request merged**
