### PR TITLE
piper: 0.5.1 -> 0.7

### LINKED ISSUE #187508: piper fails to launch
### Describe the bug

```console
$ piper
(.piper-wrapped:7422): dbind-WARNING **: 21:50:26.443: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/bin/..piper-wrapped-wrapped", line 37, in <module>
    from piper.application import Application
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/application.py", line 4, in <module>
    from .window import Window
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/window.py", line 8, in <module>
    from .mouseperspective import MousePerspective
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/mouseperspective.py", line 5, in <module>
    from .buttonspage import ButtonsPage
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/buttonspage.py", line 6, in <module>
    from .mousemap import MouseMap
  File "/nix/store/px5r52i32qfnvg5vapxaw32ai2gfcb84-piper-0.5.1/lib/python3.10/site-packages/piper/mousemap.py", line 12, in <module>
    gi.require_version("Rsvg", "2.0")
  File "/nix/store/a6p6gmp659yyn4zhhw4k9b147xl2k486-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

Happens regardless of whether or not the `ratbagd` service is active.

### Notify maintainers

@mvnetbiz @r-ryantm

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.11 (Raccoon), 22.11.20220816.762b003`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(sam): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by samhh**
Closes #187508.

###### Description of changes

Adds a missing dependency to `buildInputs`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Additionally, for another PR, the following diff upgrades to 0.6, but I wasn't sure about the two new dependencies:

```diff
diff --git a/pkgs/os-specific/linux/piper/default.nix b/pkgs/os-specific/linux/piper/default.nix
index 9ec4b331d82..3a8133b3c4e 100644
--- a/pkgs/os-specific/linux/piper/default.nix
+++ b/pkgs/os-specific/linux/piper/default.nix
@@ -1,10 +1,10 @@
 { lib, meson, ninja, pkg-config, gettext, fetchFromGitHub, python3
 , wrapGAppsHook, gtk3, glib, desktop-file-utils, appstream-glib, gnome
-, gobject-introspection, librsvg }:
+, gobject-introspection, librsvg, libratbag }:
 
 python3.pkgs.buildPythonApplication rec {
   pname = "piper";
-  version = "0.5.1";
+  version = "0.6";
 
   format = "other";
 
@@ -12,10 +12,12 @@ python3.pkgs.buildPythonApplication rec {
     owner  = "libratbag";
     repo   = "piper";
     rev    =  version;
-    sha256 = "1nfjnsiwg2rs6gkjsxzhr2708i6di149dgwq3cf6l12rxqpb8arj";
+    sha256 = "02x4d4n0078slj2pl0rvgayrrxvna6y6vj8fxfamvazsh5xyfzwk";
   };
 
-  nativeBuildInputs = [ meson ninja gettext pkg-config wrapGAppsHook desktop-file-utils appstream-glib gobject-introspection ];
+  nativeBuildInputs = [
+    meson ninja gettext pkg-config wrapGAppsHook desktop-file-utils appstream-glib gobject-introspection libratbag python3.pkgs.flake8
+  ];
   buildInputs = [
     gtk3 glib gnome.adwaita-icon-theme python3 librsvg
   ];

```

I was unable to get 0.7 to run as there are further dependency changes I don't understand.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can we also fix the double wrapping?

```
 ➜ ./result/bin/piper
./result/bin/piper  ./result/bin/.piper-wrapped             ./result/bin/..piper-wrapped-wrapped
```

**Comment by jtojnar** [comment]
What is the error about new dependencies?

By the way `flake8` should not be needed, it is just for linting the code but the project is missing `required: false` kwarg here:

https://github.com/libratbag/piper/blob/dcec480417c601fcf9c684b2af4552e889eed8dd/meson.build#L122

They probably though `required` defaults to `false` since they are checking if it is found but it defaults to `true`:

https://mesonbuild.com/Reference-manual_functions.html#find_program

**Comment by jtojnar** [comment]
And ratbagd is a runtime dependency that should not be needed here since it needs to be installed through a NIxOS module anyway: https://github.com/libratbag/piper/commit/ceaf4f8a878b0fdb11191eb70a60cc619727c68c

**Comment by samhh** [comment]
The 0.6 diff above fails without ratbagd with:

```
Program ratbagd found: NO

meson.build:20:4: ERROR: Program 'ratbagd' not found or not executable
```

---

An attempted 0.7 atop that fails like so (appstream change made for a similar reason to ratbagd and flake8 - meson dependency checks I'm unfamiliar with):

```diff
commit 01fe406347c765f9a47c6200f7aeeca22ae7a3f5
Author: Sam A. Horvath-Hunt <hello@samhh.com>
Date:   Sun Aug 21 16:07:52 2022 +0100

    WIP

diff --git a/pkgs/os-specific/linux/piper/default.nix b/pkgs/os-specific/linux/piper/default.nix
index 3a8133b3c4e..dc25d3c8e74 100644
--- a/pkgs/os-specific/linux/piper/default.nix
+++ b/pkgs/os-specific/linux/piper/default.nix
@@ -1,10 +1,10 @@
 { lib, meson, ninja, pkg-config, gettext, fetchFromGitHub, python3
-, wrapGAppsHook, gtk3, glib, desktop-file-utils, appstream-glib, gnome
+, wrapGAppsHook, gtk3, glib, desktop-file-utils, appstream, gnome
 , gobject-introspection, librsvg, libratbag }:
 
 python3.pkgs.buildPythonApplication rec {
   pname = "piper";
-  version = "0.6";
+  version = "0.7";
 
   format = "other";
 
@@ -12,11 +12,11 @@ python3.pkgs.buildPythonApplication rec {
     owner  = "libratbag";
     repo   = "piper";
     rev    =  version;
-    sha256 = "02x4d4n0078slj2pl0rvgayrrxvna6y6vj8fxfamvazsh5xyfzwk";
+    sha256 = "0jsvfy0ihdcgnqljfgs41lys1nlz18qvsa0a8ndx3pyr41f8w8wf";
   };
 
   nativeBuildInputs = [
-    meson ninja gettext pkg-config wrapGAppsHook desktop-file-utils appstream-glib gobject-introspection libratbag python3.pkgs.flake8
+    meson ninja gettext pkg-config wrapGAppsHook desktop-file-utils appstream gobject-introspection libratbag python3.pkgs.flake8
   ];
   buildInputs = [
     gtk3 glib gnome.adwaita-icon-theme python3 librsvg

```

```
Configuring piper.gresource.xml with command

data/meson.build:60:0: ERROR: Could not execute command "/build/source/data/generate-piper-gresource.xml.py /build/source/data/piper.gresource.xml.in /build/source/build/data/piper.gresource.xml /build/source/data/svgs".
```

---

Do we want to disable `enable_runtime_dependency_checks` and possibly `enable_tests` in [meson.build](https://github.com/libratbag/piper/blob/7f9834cc5901f790a596bae61e3eb81e63d7c2bd/meson.build)?

**Comment by jtojnar** [comment]
> The 0.6 diff above fails without ratbagd with:
> 
> ```
> Program ratbagd found: NO
> 
> meson.build:20:4: ERROR: Program 'ratbagd' not found or not executable
> ```

Hmm, looks like https://github.com/libratbag/piper/commit/ceaf4f8a878b0fdb11191eb70a60cc619727c68c switched the `required` kwarg to `true` in `find_program('ratbagd')`, which makes no sense when they are later checking `ratbagd.found()`.


> ```
> Configuring piper.gresource.xml with command
> 
> data/meson.build:60:0: ERROR: Could not execute command "/build/source/data/generate-piper-gresource.xml.py /build/source/data/piper.gresource.xml.in /build/source/build/data/piper.gresource.xml /build/source/data/svgs".
> ```

That means you need to add

```
postPatch = ''
  patchShebangs /data/generate-piper-gresource.xml.py
'';
```

and `python3` to `nativeBuildInputs` since the build sandbox does not have `/usr/bin/env`:

https://github.com/libratbag/piper/blob/dcec480417c601fcf9c684b2af4552e889eed8dd/data/generate-piper-gresource.xml.py#L1

> Do we want to disable `enable_runtime_dependency_checks` and possibly `enable_tests` in [meson.build](https://github.com/libratbag/piper/blob/7f9834cc5901f790a596bae61e3eb81e63d7c2bd/meson.build)?

Yeah, probably.

**Comment by samhh** [comment]
Thanks for your help! This diff appears to work for 0.7:

```diff
diff --git a/pkgs/os-specific/linux/piper/default.nix b/pkgs/os-specific/linux/piper/default.nix
index 9ec4b331d82..3dec8f14efc 100644
--- a/pkgs/os-specific/linux/piper/default.nix
+++ b/pkgs/os-specific/linux/piper/default.nix
@@ -4,7 +4,7 @@
 
 python3.pkgs.buildPythonApplication rec {
   pname = "piper";
-  version = "0.5.1";
+  version = "0.7";
 
   format = "other";
 
@@ -12,7 +12,7 @@ python3.pkgs.buildPythonApplication rec {
     owner  = "libratbag";
     repo   = "piper";
     rev    =  version;
-    sha256 = "1nfjnsiwg2rs6gkjsxzhr2708i6di149dgwq3cf6l12rxqpb8arj";
+    sha256 = "0jsvfy0ihdcgnqljfgs41lys1nlz18qvsa0a8ndx3pyr41f8w8wf";
   };
 
   nativeBuildInputs = [ meson ninja gettext pkg-config wrapGAppsHook desktop-file-utils appstream-glib gobject-introspection ];
@@ -25,9 +25,11 @@ python3.pkgs.buildPythonApplication rec {
 
   postPatch = ''
     chmod +x meson_install.sh # patchShebangs requires executable file
-    patchShebangs meson_install.sh
+    patchShebangs meson_install.sh data/generate-piper-gresource.xml.py
   '';
 
+  mesonFlags = [ "-Druntime-dependency-checks=false" "-Dtests=false" ];
+
   meta = with lib; {
     description = "GTK frontend for ratbagd mouse config daemon";
     homepage    = "https://github.com/libratbag/piper";

```

Thoughts?

**Comment by jtojnar** [comment]
`mesonFlags` conventionally belongs to a different place (see https://github.com/jtojnar/nixpkgs-hammering/blob/4d8fcb9bddec74b9250ebb55a75874132dfa2538/explanations/attribute-ordering.md) and it would be better to have one meson flag per line to better facilitate browsing git history but looks good otherwise.

**Comment by SuperSandro2000** [comment]
> By the way `flake8` should not be needed, it is just for linting the code but the project is missing `required: false` kwarg here:

Also if it would be required the better approach would be to patch that out. Linters tend to break over updates which creates extra maintenance work for us.

**Comment by jtojnar** [comment]
I think it is only required due to a mistake and the `required` kwarg of `find_program` should be changed to `false` upstream as rest of the Meson build definition expects.

**Comment by samhh** [comment]
```diff
commit b86323ccff5aa69678cf57bfea872617c42101f6
Author: Sam A. Horvath-Hunt <hello@samhh.com>
Date:   Sun Aug 21 18:09:52 2022 +0100

    piper: 0.5.1 -> 0.7

diff --git a/pkgs/os-specific/linux/piper/default.nix b/pkgs/os-specific/linux/piper/default.nix
index 9ec4b331d82..293425897e9 100644
--- a/pkgs/os-specific/linux/piper/default.nix
+++ b/pkgs/os-specific/linux/piper/default.nix
@@ -4,7 +4,7 @@
 
 python3.pkgs.buildPythonApplication rec {
   pname = "piper";
-  version = "0.5.1";
+  version = "0.7";
 
   format = "other";
 
@@ -12,7 +12,7 @@ python3.pkgs.buildPythonApplication rec {
     owner  = "libratbag";
     repo   = "piper";
     rev    =  version;
-    sha256 = "1nfjnsiwg2rs6gkjsxzhr2708i6di149dgwq3cf6l12rxqpb8arj";
+    sha256 = "0jsvfy0ihdcgnqljfgs41lys1nlz18qvsa0a8ndx3pyr41f8w8wf";
   };
 
   nativeBuildInputs = [ meson ninja gettext pkg-config wrapGAppsHook desktop-file-utils appstream-glib gobject-introspection ];
@@ -23,9 +23,14 @@ python3.pkgs.buildPythonApplication rec {
     gobject-introspection # fixes https://github.com/NixOS/nixpkgs/issues/56943 for now
   ];
 
+  mesonFlags = [
+    "-Druntime-dependency-checks=false"
+    "-Dtests=false"
+  ];
+
   postPatch = ''
     chmod +x meson_install.sh # patchShebangs requires executable file
-    patchShebangs meson_install.sh
+    patchShebangs meson_install.sh data/generate-piper-gresource.xml.py
   '';
 
   meta = with lib; {

```

What's expected behaviour in nixpkgs - should I just push this commit here or raise another PR that depends upon this one?

**Comment by jtojnar** [comment]
A separate commit in this PR is fine.

**Pull request merged**
