### PR TITLE
gh: 2.58.0 -> 2.59.0

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349060`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>emacsPackages.consult-gh</li>
    <li>gh</li>
    <li>gh-f</li>
    <li>gh-notify</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>emacsPackages.consult-gh</li>
    <li>gh</li>
    <li>gh-f</li>
    <li>gh-notify</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>emacsPackages.consult-gh</li>
    <li>gh</li>
    <li>gh-f</li>
    <li>gh-notify</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>emacsPackages.consult-gh</li>
    <li>gh</li>
    <li>gh-f</li>
    <li>gh-notify</li>
  </ul>
</details>

**Review by zowoq — DISMISSED** [review]
> Add update script for automated updates

Update script isn't needed, updates are already automated, please remove it.

**Comment by khaneliman** [comment]
> > Add update script for automated updates
> 
> Update script isn't needed, updates are already automated, please remove it.



> > Add update script for automated updates
> 
> Update script isn't needed, updates are already automated, please remove it.

Sorry, thought it was required for RyanTM updates.. but it seems it's been updating it in the past.

**Comment by zowoq** [comment]
The bot knows how to update normal `stdenv.mkDerivation` packages and some language specific variants: buildGo, buildRust, some types of the node packaging. Update script is usually only needed if the package is complicated or if upstream publishes multiple versions and the bot needs to be told which version to use.

**Comment by Frontear** [comment]
> The bot knows how to update normal `stdenv.mkDerivation` packages and some language specific variants: buildGo, buildRust, some types of the node packaging. Update script is usually only needed if the package is complicated or if upstream publishes multiple versions and the bot needs to be told which version to use.

Without a `passthru.updateScript` attribute, how does the bot know to update? I thought it only attempts updates on a derivation that has that attribute defined

**Comment by zowoq** [comment]
It tries to update everything.

**Pull request merged**
