### PR TITLE
colima: backport from unstable

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Backport Colima to release 21.11.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @zowoq @aaschmid

### CODE REVIEW

**Comment by zowoq** [comment]
Not sure if this may need a newer version of `lima` backported as well?

**Comment by kalbasit** [comment]
> Not sure if this may need a newer version of `lima` backported as well?

Hmm that's a good point. I have not tested colima on Darwin on this branch. @aaschmid would you be able to help me test this on your end? I'm just getting started using it, and won't have enough expertise to say if it worked or if it has not.

**Comment by aaschmid** [comment]
@kalbasit: even though a warning occurs on command line that `lima` greater than 0.7.4 is required and current lima is 0.7.3 (as far as I could see), it worked for me using the package from your branch running a `hello-world` container.

**Comment by kalbasit** [comment]
> @kalbasit: even though a warning occurs on command line that `lima` greater than 0.7.4 is required and current lima is 0.7.3 (as far as I could see), it works running a `hello-world` container.

Thank you for checking @aaschmid. Since a warning is issued, I went ahead and ported over the two commits on master for lima.

**Comment by aaschmid** [comment]
Funktioniert bei mir ohne Warning

**Review by aaschmid — APPROVED** [review]

**Pull request merged**
