### PR TITLE
pythonPackages.praw: 6.0.0 -> 6.3.1

### LINKED ISSUE #64086: python3Packages.praw fails to build on nixos-unstable
## Issue description

I had i3pystatus fail to build because of a pytest error with praw on unstable.
I tried to bump praw from 6.0.0 to 6.3.1 but it requires a new dep websocket-client that doesn't look packaged thus I ended up ditching it from i3pystatus dependencies. Maybe we should do the same upstream and provide a leaner i3pystatus as it's not a core plugin anyway (and fails https://github.com/NixOS/nixpkgs/issues/51810).
https://github.com/praw-dev/praw

### Steps to reproduce
nix build python3Packages.praw -f channel:nixos-unstable

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.0, NixOS, 19.09.git.0a7b2ab (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(teto): `""`
 - channels(root): `""`
 - nixpkgs: `/home/teto/nixpkgs`

### PR DESCRIPTION
**Pull request by jonringer**
#### Motivation for this change
resolves #64086

fixes a broken build

also, updates a package
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

$ nix path-info -Sh ./result
/nix/store/fjwyzg93iwccjnqddg82hd7b8ncy0l1s-python3.7-praw-6.3.1         107.8M

### CODE REVIEW

**Comment by teto** [comment]
@GrahamcOfBorg build python3Packages.praw python27Packages.pyarrow python37Packages.image-match csvs-to-sqlite mpfshell

**Comment by teto** [comment]
seems like we can ignore the https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python27Packages.pyarrow.x86_64-linux ?

**Comment by jonringer** [comment]
I think so, those packages build fine on this branch

```
[06:07:01] jon@jon-desktop /home/jon/projects/nixpkgs (update-praw)
$ nix-build default.nix -A pythonPackages.pyarrow
/nix/store/cfszq8jl26zfwq8vz72s7m7qms020s7c-python2.7-pyarrow-0.13.0
[06:07:13] jon@jon-desktop /home/jon/projects/nixpkgs (update-praw)
$ nix-build default.nix -A python3Packages.pyarrow
/nix/store/xbrinh75ch73b36cdjyfz2771bbfl6qw-python3.7-pyarrow-0.13.0
```

**Comment by jonringer** [comment]
`nix-review pr 64277` fails on 6 packages, but all 6 are broken on master, so I don't think it's a regression

```
[142 built (6 failed), 483 copied (2507.3 MiB), 640.3 MiB DL]
error: build of '/nix/store/qc4p4ciq8dn1ipcfhy14x9m5siqbpgvz-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/64277
6 package failed to build:
appdaemon python27Packages.imbalanced-learn python27Packages.sumo python37Packages.imbalanced-learn python37Packages.sopel python37Packages.sumo

141 package were build:
```

**Comment by teto** [comment]
thanks. Next time I want a package updated, remind me to irritate at you, people say I am really good at it ;)

**Comment by jonringer** [comment]
@teto 4 of those will be fixed by #64303

**Pull request merged**
