### PR TITLE
pythonPackages: fix missing PyPI references

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
* pythonPackages.pyev: drop: PyPI package removed
* pythonPackages.python3pika: drop: unmaintained
* pythonPackages.area53: drop: PyPI package removed
* pythonPackages.eggdeps: fix PyPI name
* pythonPackages.mp2: fix PyPI name
* pythonPackages.mrbob: fix PyPI name
* pythonPackages.pyaudio: fix PyPI name
* pythonPackages.pymysqlsa: fix PyPI name
* pythonPackages.pystache: fix pname
* pythonPackages.setproctitle: fix PyPI name

PD. elpy package was also removed from PyPI https://github.com/jorgenschaefer/elpy/issues/1583, I'm going to remove it in another PR

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
`pname`s should adhere to [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names), e.g. `tl-eggdeps` instead of `tl.eggdeps`. If necessary, the PyPI `pname` can be specified inside `fetchPypi`.

**Comment by dotlambda** [comment]
@FRidh should definitely have a look at this.

**Comment by teto** [comment]
> `pname`s should adhere to [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names), e.g. `tl-eggdeps` instead of `tl.eggdeps`. If necessary, the PyPI `pname` can be specified inside `fetchPypi`.

Isn't dot valid according to the link you mentioned ? `This PEP references the concept of a "normalized" project name. As per PEP 426 the only valid characters in a name are the ASCII alphabet, ASCII numbers, ., -, and _`

**Comment by dotlambda** [comment]
> > `pname`s should adhere to [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names), e.g. `tl-eggdeps` instead of `tl.eggdeps`. If necessary, the PyPI `pname` can be specified inside `fetchPypi`.
> 
> Isn't dot valid according to the link you mentioned ? `This PEP references the concept of a "normalized" project name. As per PEP 426 the only valid characters in a name are the ASCII alphabet, ASCII numbers, ., -, and _`

No, the PEP states
> The name should be lowercased with all runs of the characters ., -, or _ replaced with a single - character.

**Comment by marsam** [comment]
> pnames should adhere to PEP 0503

I didn't know that. Fixed

**Comment by FRidh** [comment]
The attribute names (e.g. `foo` in case of `pythonPackages.foo`) needs to be normalized. This is documented in the manual. The `pname` is typically written how it is on PyPI, but in lowercase. This is not documented. The `pname` that is passed to `fetchPyPi` needs to match to the name of the file that is downloaded. That's why it is sometimes preferred to keep the `pname` in `buildPythonPackage` all lowercase, but in `fetchPyPi` with different casing.

**Comment by jonringer** [comment]
@marsam this has bit rotted quite a lot. Did you want to salvage this PR?

**Comment by FRidh** [comment]
I've rebased and pushed it to staging. Thanks for the reminder @jonringer

**Pull request closed without merging**
