### PR TITLE
keepassxc: enable ssh agent sockets

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
I am mainly interested in macOS:

@GrahamcOfBorg build keepassx-community

**Comment by Mic92** [comment]
@LnL7 so clang complains about os x standard includes?

**Comment by LnL7** [comment]
@Mic92 that's cf-private

Clang is generally more pedantic about things compared to gcc, I usually add something like this.
```nix
{
  NIX_CFLAGS_COMPILE = stdenv.lib.optionalString stdenv.cc.isClang "-Wno-old-style-cast";
}
```

**Comment by Mic92** [comment]
@GrahamcOfBorg build keepassx-community

**Comment by Mic92** [comment]
Seem like some other header is missing:

```
/nix/store/9avjr40zgds5rycm2ndw9imrfpkb3vga-CF-osx-10.10.5-private/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:363:5: error: '__LLP64__' is not defined, evaluates to 0 [-Werror,-Wundef]
```

**Comment by Mic92** [comment]
I have no idea how to fix this.

**Pull request merged**
