### PR TITLE
fprintd: skip PAM related checks as they are timing out

### LINKED ISSUE #298150: Build failure: fprintd-1.94.2
### Steps To Reproduce

1. Checkout `nixos-unstable`.
2. Run `nix build .#fprintd`.

### Build log

https://gist.github.com/alyraffauf/c60e205274d052a758e040c9d762ff2e

### Additional context

Also failed in [Hydra](https://hydra.nixos.org/build/253714077).

### Notify maintainers

@abbradar 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[aly@lavaridge:~] $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by NickCao**
## Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/298150
Hopefully someone would find the root cause.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matejc** [comment]
@x418 its not just your flake. It fails with timeout also for me, with those meson flags.
This has not been fixed

**Comment by matejc** [comment]
@x418 coud you try just building the fprintd `nix-build ./nixpkgs -A fprintd` and then if it is successful, try your flake rebuild as normally?

**Comment by NickCao** [comment]
> I somehow still get build failures, am I doing something wrong? (I'm on unstable)

May you provide the full build log? (copy to a gist)

**Comment by NickCao** [comment]
The two failing tests are `79/513 fprintd:daemon+fprintd+FPrintdVirtualDeviceClaimedTest / FPrintdVirtualDeviceClaimedTest.test_verify_any_finger_no_match` and `80/513 fprintd:daemon+fprintd+FPrintdVirtualDeviceClaimedTest / FPrintdVirtualDeviceClaimedTest.test_verify_any_finger_match`, seems unrelated to this issue. I'm unable to reproduce them on current `nixos-unstable` (commit d8fe5e6c92d0)

**Comment by matejc** [comment]
for me it was:

```
199/513 fprintd:daemon+fprintd+FPrindConcurrentPolkitRequestsTest / FPrindConcurrentPolkitRequestsTest.test_hanging_claim_does_not_block_list
```

**Comment by isiko** [comment]
> > I somehow still get build failures, am I doing something wrong? (I'm on unstable)
> 
> May you provide the full build log? (copy to a gist)

Here you go: https://gist.github.com/isiko/37dff90fdf42a46a90537aaca73f2bfb

**Pull request merged**
