### PR TITLE
Fix mattermost systemd unit

### LINKED ISSUE #22860: Mattermost module does not create postgres database anymore
## Issue description
Something changed in the postgres module such that the mattermost module is now broken.
If you deploy mattermost for the first time, it should set up a postgres database through the ExecStartPre script.  However, this script fails because `psql` cannot connect to the postgres UNIX Domain Socket.  It seems  postgres now listens on tcp instead of unix domain socket.  So the script is not correct anymore

### The Fix:
Force `psql` to connect to `127.0.0.1`. It will then fallback to TCP connection. this is a hack though it seems...

### Steps to reproduce

```
  services.mattermost = {
    enable = true;
  };

```

now run `nixos-rebuild switch`

## Technical details

* System: 
```
[nixos@arianvp:/]$ nixos-version
16.09.1536.dc6a857 (Flounder)
```
* Nix version: (run `nix-env --version`)
```
[nixos@arianvp:/]$ nix-env --version
nix-env (Nix) 1.11.6
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
[nixos@arianvp:/]$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.1229.f52eaf4"
```

### PR DESCRIPTION
**Pull request by arianvp**
Fixes #22860

###### Motivation for this change
The preStart hook of the service file tries to set up a postgres database using the `psql` command.
`psql` connects to Postgres through a unix domain socket that is in `/tmp` .    However, because we have `PrivateTmp=true` , `psql` can never find this domain socket.   Hence the change

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by fpletz — CHANGES_REQUESTED** [review]
I think a better solution would be to keep `PrivateTmp` enabled and either use `-h localhost` if `cfg.localDatabaseCreate` is enabled in the `preStart` hook. Or maybe try `JoinsNamespaceOf` with the postgresql service.

**Comment by Mic92** [comment]
`JoinsNamespaceOf` sound appropriate to me.

**Comment by arianvp** [comment]
That is not possible.  `-h`  needs  a password to authenticate instead of the current user id that runs the command.  `JoinsNamespaceOf` seems like a better solution. let me try this.

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
Thanks!

**Pull request merged**
