### PR TITLE
xfce.mkXfcederivation: Fix ofborg maintainer ping

### LINKED ISSUE #261819: ofborg maintainer ping does not work for mkXfceDerivation packages
### Describe the bug

Looking at my filed [Xfce PRs](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+label%3A%226.topic%3A+xfce%22+author%3Abobby285271) ofborg does not ping `@romildo` in most cases.

### Steps To Reproduce

I am thinking of

```
$ nix-instantiate -E 'with import ./. {}; builtins.unsafeGetAttrPos "version" xfce.xfconf' --eval
null
```

### Expected behavior

ofborg pings people, or the above command does not print `null` (I guess)

### Screenshots

*No response.*

### Additional context

*No response.*

### PR DESCRIPTION
**Pull request by bobby285271**
## Description of changes

I wanna fix https://github.com/NixOS/nixpkgs/issues/261819 but honestly not sure what to do, it looks like by not using recursiveUpdate we are able to get the right result of builtins.unsafeGetAttrPos "version" so let's see what will happen here.

<details>

1. ofborg labels
1. overrides
1. update scripts
1. xfce.xfce4-session.xinitrc
1. 

```
     1  pkgs/desktops/xfce/thunar-plugins/archive/default.nix
     2  pkgs/desktops/xfce/thunar-plugins/media-tags/default.nix
     3  pkgs/desktops/xfce/applications/gigolo/default.nix
     4  pkgs/desktops/xfce/applications/mousepad/default.nix
     5  pkgs/desktops/xfce/applications/orage/default.nix
     6  pkgs/desktops/xfce/applications/parole/default.nix
     7  pkgs/desktops/xfce/applications/ristretto/default.nix
     8  pkgs/desktops/xfce/applications/xfburn/default.nix
     9  pkgs/desktops/xfce/applications/xfce4-dict/default.nix
    10  pkgs/desktops/xfce/applications/xfce4-notifyd/default.nix
    11  pkgs/desktops/xfce/applications/xfce4-screenshooter/default.nix
    12  pkgs/desktops/xfce/applications/xfce4-taskmanager/default.nix
    13  pkgs/desktops/xfce/applications/xfce4-terminal/default.nix
    14  pkgs/desktops/xfce/applications/xfce4-volumed-pulse/default.nix
    15  pkgs/desktops/xfce/applications/xfdashboard/default.nix
    16  pkgs/desktops/xfce/applications/xfce4-panel-profiles/default.nix
    17  pkgs/desktops/xfce/applications/xfce4-screensaver/default.nix
    18  pkgs/desktops/xfce/core/exo/default.nix
    19  pkgs/desktops/xfce/core/garcon/default.nix
    20  pkgs/desktops/xfce/core/libxfce4ui/default.nix
    21  pkgs/desktops/xfce/core/libxfce4util/default.nix
    22  pkgs/desktops/xfce/core/thunar-volman/default.nix
    23  pkgs/desktops/xfce/core/thunar/default.nix
    24  pkgs/desktops/xfce/core/tumbler/default.nix
    25  pkgs/desktops/xfce/core/xfce4-appfinder/default.nix
    26  pkgs/desktops/xfce/core/xfce4-dev-tools/default.nix
    27  pkgs/desktops/xfce/core/xfce4-panel/default.nix
    28  pkgs/desktops/xfce/core/xfce4-power-manager/default.nix
    29  pkgs/desktops/xfce/core/xfce4-session/default.nix
    30  pkgs/desktops/xfce/core/xfce4-settings/default.nix
    31  pkgs/desktops/xfce/core/xfconf/default.nix
    32  pkgs/desktops/xfce/core/xfdesktop/default.nix
    33  pkgs/desktops/xfce/core/xfwm4/default.nix
    34  pkgs/desktops/xfce/panel-plugins/xfce4-battery-plugin/default.nix
    35  pkgs/desktops/xfce/panel-plugins/xfce4-clipman-plugin/default.nix
    36  pkgs/desktops/xfce/panel-plugins/xfce4-cpufreq-plugin/default.nix
    37  pkgs/desktops/xfce/panel-plugins/xfce4-datetime-plugin/default.nix
    38  pkgs/desktops/xfce/panel-plugins/xfce4-netload-plugin/default.nix
    39  pkgs/desktops/xfce/panel-plugins/xfce4-pulseaudio-plugin/default.nix
    40  pkgs/desktops/xfce/panel-plugins/xfce4-verve-plugin/default.nix
    41  pkgs/desktops/xfce/panel-plugins/xfce4-whiskermenu-plugin/default.nix
    42  pkgs/desktops/xfce/panel-plugins/xfce4-xkb-plugin/default.nix
    43  pkgs/desktops/xfce/panel-plugins/xfce4-cpugraph-plugin/default.nix
    44  pkgs/desktops/xfce/panel-plugins/xfce4-time-out-plugin/default.nix
```

</details>

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Actually, it now fails here: https://github.com/NixOS/ofborg/blob/de415d372959b7e6fc6b2f6c95f0c21e5010348d/ofborg/src/maintainers.nix#L31

**Comment by bobby285271** [comment]
Actually, there are ways to test this locally https://github.com/NixOS/nixpkgs/pull/219821#issuecomment-1455961453 but this pr does not work

**Comment by bobby285271** [comment]
`nix-instantiate ofborg/src/maintainers.nix --arg changedattrsjson ./changedattrs.json --arg changedpathsjson ./changedpaths.json --eval` seems to work for me now, trying again.

`changedattrs.json`

```
[["xfce","xfce4-screenshooter"]]
```

`changedpaths.json`

```
["pkgs/desktops/xfce/applications/xfce4-screenshooter/default.nix"]
```

**Review by romildo — APPROVED** [review]
LGTM

**Pull request merged**
