### PR TITLE
README.md: Add merge chance badge

### PR DESCRIPTION
**Pull request by Mathnerd314**
<a href="https://merge-chance.info/target?repo=nixos/nixpkgs">Merge Chance badge</a> 

###### Motivation for this change

It's a cool little badge that might convince people to contribute to Nixpkgs. The numbers seem a little skewed but I checked the [beta version](https://acceptance.merge-chance.info/target?repo=NixOS/nixpkgs) that filters out top contributors and they're similar ( 98.65% / 0.24 days). And [the data](https://acceptance.merge-chance.info/data?repo=nixos%2Fnixpkgs) looks fine.

The only real risk is that the badge's website might die, but the README has had many badges come and go.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I would put it next to the other badges.

**Comment by Mathnerd314** [comment]
OK, moved it to the top.

**Comment by ju1m** [comment]
AFAICS there is currently only 74 PRs taken into account in the data, this is hardly representative of the current ~90000 PR. Will the data size increase over time?
I'm happy if those numbers reflect a reality for some of us, but as far as I'm concerned, for the past two years of my monthly contributions I have not experienced such high "Merge Chance" near that 0.24 days median, except for trivial PRs bumping a minor version or following up a previous big PR whose merge revealed bugs.

Also this badge only counts "PRs made by outsiders (not owners/members)", but in Nixpkgs being a member happened easily and rapidly for me (I was requested to add my name to the maintainers list to get my PR merged), yet it has only given me rights to add tags (after having enabled 2FA), but no rights to merge or else (and as a matter of fact my PRs still remain many **months** reviewed and validated but not merged).

All this to say, it's great to have such metric, but it would be greater (and more meaningful) if we could have them for **more PRs** and **also for members**. Please don't feel obliged or blocked by my request, I don't know if it is an easy task or not to do, it's just a (naive) wish.

**Comment by Mathnerd314** [comment]
Regarding 74 there is an issue open https://github.com/PiotrZakrzewski/merge-chance/issues/4 that might increase it to 100-200 once resolved. I don't think that would change the statistics though.

As far as PRs being open and unmerged, I agree it's a problem - there was a [Discourse thread](https://discourse.nixos.org/t/suggestion-to-help-maintainers-with-nixpkgs-prs-bloat/4794/6) from 2019, and of course the "PRs ready for review" threads see a lot of activity. I haven't looked at it much but the site code is open source, it's probably easy to modify to get different statistics. The outsider detection definitely isn't working right since jonringer is included as a "outsider" contributor but he's actually on the release team.

**Comment by SuperSandro2000** [comment]
Service no longer works.

**Pull request closed without merging**
