### PR TITLE
libqt5pas,lazarus-qt: 3.2-0 -> 3.6-0, init Qt6 variants

### PR DESCRIPTION
**Pull request by OPNA2608**
- `libqt5pas`,`lazarus-qt5`: 3.2-0 -> 3.6-0
  This is needed because the Qt6 code is broken in the currently-packaged version: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40901
- `libqt5pas`: `libsForQt5.mkDerivation` -> `stdenv.mkDerivation`
  In preparation for the next commit, don't depend on Qt5-isms anymore
- `libsForQt5.libqtpas`: Rename from `libqt5pas`
  So the Qt5 and the upcoming Qt6 versions have the same attribute name in reverse dependencies, just in different scopes (`libsForQt5` vs `qt6Packages`). Alias entry added, treewide switch to new name.
- `qt6Packages.libqtpas`: init at 3.6-0
- `lazarus-qt6`: init at 3.6-0
  `lazarus-qt` renamed to `lazarus-qt5`. Alias entry added, treewide switch to new name.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by OPNA2608** [comment]
Ah, this was already attempted with https://github.com/NixOS/nixpkgs/pull/324035, but that one's gone stale. Moving `libqt*pas` to the corresponding Qt scope seems like a good idea though, will copy that (and fix alias-less eval issues).

**Comment by NobbZ** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368201`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 17 packages built:</summary>
  <ul>
    <li>avr-sim</li>
    <li>cqrlog</li>
    <li>cudatext</li>
    <li>cudatext-gtk</li>
    <li>ddrescueview</li>
    <li>doublecmd</li>
    <li>goverlay</li>
    <li>goverlay.man</li>
    <li>kdePackages.libqtpas</li>
    <li>lazarus</li>
    <li>lazarus-qt5</li>
    <li>lazarus-qt6</li>
    <li>lazpaint</li>
    <li>libsForQt5.libqtpas</li>
    <li>peazip</li>
    <li>tomboy-ng</li>
    <li>transgui</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12498820631
**Extra args**: ``

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12498820631


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368201`

---
### `x86_64-darwin`

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368201`

---
### `aarch64-darwin`

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368201`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 17 packages built:</summary>
  <ul>
    <li>avr-sim</li>
    <li>cqrlog</li>
    <li>cudatext</li>
    <li>cudatext-gtk</li>
    <li>ddrescueview</li>
    <li>doublecmd</li>
    <li>goverlay</li>
    <li>goverlay.man</li>
    <li>kdePackages.libqtpas</li>
    <li>lazarus</li>
    <li>lazarus-qt5</li>
    <li>lazarus-qt6</li>
    <li>lazpaint</li>
    <li>libsForQt5.libqtpas</li>
    <li>peazip</li>
    <li>tomboy-ng</li>
    <li>transgui</li>
  </ul>
</details>

**Pull request merged**
