### PR TITLE
Wire desktop bump

### PR DESCRIPTION
**Pull request by toonn**
###### Description of changes

Bump the versions for Linux and Darwin. Tested on Darwin but not Linux.

Usually this is backported to the stable channels, not sure how to request that properly? Wait for merge and then open PRs targeting stable branches?

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Backport is done by throwing a label on the PR and if that fails do it manually.

**Comment by K900** [comment]
Result of `nixpkgs-review pr 196593` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wire-desktop</li>
  </ul>
</details>

**Comment by flokli** [comment]
Downgrading to `3.28.2946` seems to bring the bootup back, without breaking my history at least. Maybe we should revert this, if more people are affected?

**Comment by SuperSandro2000** [comment]
Can you try strace to see if it is a NixOS problem with drivers?

**Comment by toonn** [comment]
Maybe @arianvp or @kiwi run this on Linux and can help with testing?

Opened a revert PR just for the Linux version in #199350.

**Comment by flokli** [comment]
@toonn you only tested this on MacOS?

**Comment by K900** [comment]
I did test it on Linux and it ran far enough to at least show the login screen.

**Comment by flokli** [comment]
It happens after the login screen unfortunately.

**Comment by SuperSandro2000** [comment]
I am not using wire I just tried to be helpful.

**Comment by toonn** [comment]
@flokli, I don't have a Linux machine to test it on. I asked for reviews in #nix multiple times, this is after about a week of waiting for reviews by maintainers. Sandro and K900 tried to help out but aren't users.

Maybe you can take on maintainership, then at least you will get pinged and you can take care of the Linux side? Since right now you're kinda getting notified by the actual breakage, which is suboptimal to say the least.

**Comment by flokli** [comment]
I had @arianvp test this on a non-NixOS chromebook today (with NixGL), and it did work. There must be something odd with my machine, even though I can't pinpoint it.

I'm not sure how to proceed with this. I guess it's fine, considering more people would have complained otherwise (?)

> Maybe you can take on maintainership, then at least you will get pinged and you can take care of the Linux side? 

There's not much I can do, considering this is a binary build, and I run into some crashes on my machine :-/ I also can't easily try if this works with other versions of electron, or if some of the warnings run on startup are patched. Did you have any success in trying to build from source?

**Comment by toonn** [comment]
Ah, sorry to hear. I'll close the revert PR then. I guess you can pin the package until an update fixes it?

I did not have any success no, though that attempt was years ago. I've recently packaged another electron app so I might try this again early next year.

**Comment by flokli** [comment]
Yeah, i guess I'll pin it for the time being, hoping it'll keep working for a while.

**Pull request merged**
