### PR TITLE
html2text: 1.3.2a -> 2.0.0

### PR DESCRIPTION
**Pull request by ajs124**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 112094` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bookworm</li>
    <li>html2text</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package build (see https://github.com/NixOS/nixpkgs/pull/112094#issuecomment-774417586)
- [ ] all depending packages build
- [x] library tested on x86_64

```bash
...ew/pr-112094]$ ./results/html2text/bin/html2text -version
This is html2text, version 2.0.0
[...]
...ew/pr-112094]$ ./results/html2text/bin/html2text convert.html 
****** My First Heading ******
My first paragraph.
...ew/pr-112094]$ ./results/html2text/bin/html2text test.html 
Segmentation fault (core dumped)
```

Looks good to me.

The segmentation fault is caused by the limitations of the tool. Like if you try to convert an actual website instead of content from an e-mail client.

**Review by eikek — APPROVED** [review]
lgtm, thank you

**Comment by SuperSandro2000** [comment]
fails on darwin:

```
builder for '/nix/store/844ar9pw665hxvsrlyswr8dl5l39kaav-html2text-2.0.0.drv' failed with exit code 1; last 9 log lines:
  unpacking sources
  unpacking source archive /nix/store/gah5gc2bdx8qjl8prpxar2ld0fhk8mdq-source
  source root is source
  patching sources
  configuring
  configure flags: --prefix=/nix/store/9adj6vf0i60365cqbqk8gag43fwkl770-html2text-2.0.0
  Checking C++ compiler... use "clang++"
  Checking for socket libraries... no extra libraries required
  Checking for iconv libraries... Error: Could not determine the library for the iconv API.
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112094` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>bookworm</li>
<li>html2text</li>
</ul>
</details>

**Comment by ajs124** [comment]
>     * [x]  package build (see [#112094 (comment)](https://github.com/NixOS/nixpkgs/pull/112094#issuecomment-774417586))
> 
>     * [ ]  all depending packages build
> 
>     * [x]  library tested on x86_64
> 
> 
> ```shell
> ...ew/pr-112094]$ ./results/html2text/bin/html2text -version
> This is html2text, version 2.0.0
> [...]
> ...ew/pr-112094]$ ./results/html2text/bin/html2text convert.html 
> ****** My First Heading ******
> My first paragraph.
> ...ew/pr-112094]$ ./results/html2text/bin/html2text test.html 
> Segmentation fault (core dumped)
> ```
> 
> Looks good to me.
> 
> The segmentation fault is caused by the limitations of the tool. Like if you try to convert an actual website instead of content from an e-mail client.

Does the segmentation fault also happen on the version currently in nixpkgs, for the same input?

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112094` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>html2text: log <a href="https://termbin.com/06xt">https://termbin.com/06xt</a></li>
  </ul>
</details>

**Comment by ajs124** [comment]
I decided to deploy an alternative solution, so I'm going to close this.

**Pull request closed without merging**
