### PR TITLE
ELK: 5.6.1 -> 5.6.5 & add ELK 6.1.0

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

This PR upgrades ELK-5 and adds ELK-6.

The test suite is extended to test both ELK-5 and ELK-6.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
The index level settings are no longer supported in the elasticsearch config, so we might want to remove them from the extraConf example.

**Comment by srhb** [comment]
How did you execute the tests? `nix-build nixos/release.nix -A tests.elk` does not appear to do anything.

**Comment by srhb** [comment]
Something funny is going on with using `"5"` and `"6"` as the names in the attribute set your're mapping over. `"elk5"` and `elk6` works.

**Comment by srhb** [comment]
This appears to be a Nix 1.12 issue only. Nix 1.11 evaluates it just fine.

**Comment by basvandijk** [comment]
Hi @srhb, thank you for the review! 

I removed the index level settings from the example and I changed the test names "5" and "6" to "ELK-5" and "ELK-6" which should enable them to be evaluated on Nix 1.12.

**Comment by basvandijk** [comment]
@fpletz any objections against merging this?

**Comment by basvandijk** [comment]
BTW note that the following succeeds: `nix-shell -p nox --run "nox-review pr 32822`.

**Comment by srhb** [comment]
@basvandijk I was under the impression you were waiting for a specific review. If not, I'm happy to merge this. I've used it myself and it looks good. :)

**Comment by basvandijk** [comment]
@srhb I would appreciate it if you can merge this. Thanks!

I'm also thinking about cherry-picking this on 17.09. I'll open a separate PR for that if you don't beat me to it.

**Comment by srhb** [comment]
Thanks, and please do open a PR for the backport -- I'm unsure on the procedure for adding new major versions back there. :)

**Comment by basvandijk** [comment]
Thanks Sarah!

**Pull request merged**
