### PR TITLE
kde/plasma: 5.25.1 -> 5.25.2

### PR DESCRIPTION
**Pull request by andrevmatos**
###### Description of changes

Update Plasma Desktop to [5.25.2, released in 28/June/2022](https://kde.org/announcements/plasma/5/5.25.2/)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andrevmatos** [comment]
Result of `nixpkgs-review pr 179458` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>193 packages marked as broken and skipped:</summary>
  <ul>
    <li>bluedevil</li>
    <li>breeze-grub</li>
    <li>breeze-gtk</li>
    <li>breeze-plymouth</li>
    <li>breeze-qt5</li>
    <li>buho</li>
    <li>clip</li>
    <li>communicator</li>
    <li>discover</li>
    <li>kactivitymanagerd</li>
    <li>kde-cli-tools</li>
    <li>kde-gtk-config</li>
    <li>kdenlive</li>
    <li>kdeplasma-addons</li>
    <li>kdev-php</li>
    <li>kdev-python</li>
    <li>kdevelop</li>
    <li>kdevelop-unwrapped</li>
    <li>kgamma5</li>
    <li>kinfocenter</li>
    <li>kmenuedit</li>
    <li>krohnkite</li>
    <li>kscreen</li>
    <li>kscreenlocker</li>
    <li>ksshaskpass</li>
    <li>kwallet-pam</li>
    <li>kwayland-integration</li>
    <li>kwin</li>
    <li>kwin-dynamic-workspaces</li>
    <li>kwin-tiling</li>
    <li>kwrited</li>
    <li>libsForQt512.applet-window-buttons</li>
    <li>libsForQt512.bismuth</li>
    <li>libsForQt512.bluedevil</li>
    <li>libsForQt512.breeze-grub</li>
    <li>libsForQt512.breeze-gtk</li>
    <li>libsForQt512.breeze-plymouth</li>
    <li>libsForQt512.breeze-qt5</li>
    <li>libsForQt512.buho</li>
    <li>libsForQt512.clip</li>
    <li>libsForQt512.communicator</li>
    <li>libsForQt512.discover</li>
    <li>libsForQt512.kactivitymanagerd</li>
    <li>libsForQt512.kde-cli-tools</li>
    <li>libsForQt512.kde-gtk-config</li>
    <li>libsForQt512.kde2-decoration</li>
    <li>libsForQt512.kdecoration</li>
    <li>libsForQt512.kdenlive</li>
    <li>libsForQt512.kdeplasma-addons</li>
    <li>libsForQt512.kdev-php</li>
    <li>libsForQt512.kdev-python</li>
    <li>libsForQt512.kdevelop</li>
    <li>libsForQt512.kdevelop-unwrapped</li>
    <li>libsForQt512.kgamma5</li>
    <li>libsForQt512.khotkeys</li>
    <li>libsForQt512.kinfocenter</li>
    <li>libsForQt512.kmenuedit</li>
    <li>libsForQt512.krohnkite</li>
    <li>libsForQt512.kscreen</li>
    <li>libsForQt512.kscreenlocker</li>
    <li>libsForQt512.ksshaskpass</li>
    <li>libsForQt512.ksystemstats</li>
    <li>libsForQt512.kwallet-pam</li>
    <li>libsForQt512.kwayland-integration</li>
    <li>libsForQt512.kwin</li>
    <li>libsForQt512.kwin-dynamic-workspaces</li>
    <li>libsForQt512.kwin-tiling</li>
    <li>libsForQt512.kwrited</li>
    <li>libsForQt512.layer-shell-qt</li>
    <li>libsForQt512.libkscreen</li>
    <li>libsForQt512.libksysguard</li>
    <li>libsForQt512.lightly</li>
    <li>libsForQt512.milou</li>
    <li>libsForQt512.nota</li>
    <li>libsForQt512.oxygen</li>
    <li>libsForQt512.parachute</li>
    <li>libsForQt512.pix</li>
    <li>libsForQt512.plasma-browser-integration</li>
    <li>libsForQt512.plasma-desktop</li>
    <li>libsForQt512.plasma-disks</li>
    <li>libsForQt512.plasma-integration</li>
    <li>libsForQt512.plasma-mobile</li>
    <li>libsForQt512.plasma-nano</li>
    <li>libsForQt512.plasma-nm</li>
    <li>libsForQt512.plasma-pa</li>
    <li>libsForQt512.plasma-sdk</li>
    <li>libsForQt512.plasma-systemmonitor</li>
    <li>libsForQt512.plasma-thunderbolt</li>
    <li>libsForQt512.plasma-vault</li>
    <li>libsForQt512.plasma-workspace</li>
    <li>libsForQt512.plasma-workspace-wallpapers</li>
    <li>libsForQt512.polkit-kde-agent</li>
    <li>libsForQt512.powerdevil</li>
    <li>libsForQt512.qqc2-breeze-style</li>
    <li>libsForQt512.sddm-kcm</li>
    <li>libsForQt512.shelf</li>
    <li>libsForQt512.spectacle</li>
    <li>libsForQt512.systemsettings</li>
    <li>libsForQt512.vvave</li>
    <li>libsForQt512.xdg-desktop-portal-kde</li>
    <li>libsForQt514.applet-window-buttons</li>
    <li>libsForQt514.bismuth</li>
    <li>libsForQt514.bluedevil</li>
    <li>libsForQt514.breeze-grub</li>
    <li>libsForQt514.breeze-gtk</li>
    <li>libsForQt514.breeze-plymouth</li>
    <li>libsForQt514.breeze-qt5</li>
    <li>libsForQt514.buho</li>
    <li>libsForQt514.clip</li>
    <li>libsForQt514.communicator</li>
    <li>libsForQt514.discover</li>
    <li>libsForQt514.kactivitymanagerd</li>
    <li>libsForQt514.kde-cli-tools</li>
    <li>libsForQt514.kde-gtk-config</li>
    <li>libsForQt514.kde2-decoration</li>
    <li>libsForQt514.kdecoration</li>
    <li>libsForQt514.kdenlive</li>
    <li>libsForQt514.kdeplasma-addons</li>
    <li>libsForQt514.kdev-php</li>
    <li>libsForQt514.kdev-python</li>
    <li>libsForQt514.kdevelop</li>
    <li>libsForQt514.kdevelop-unwrapped</li>
    <li>libsForQt514.kgamma5</li>
    <li>libsForQt514.khotkeys</li>
    <li>libsForQt514.kinfocenter</li>
    <li>libsForQt514.kmenuedit</li>
    <li>libsForQt514.krohnkite</li>
    <li>libsForQt514.kscreen</li>
    <li>libsForQt514.kscreenlocker</li>
    <li>libsForQt514.ksshaskpass</li>
    <li>libsForQt514.ksystemstats</li>
    <li>libsForQt514.kwallet-pam</li>
    <li>libsForQt514.kwayland-integration</li>
    <li>libsForQt514.kwin</li>
    <li>libsForQt514.kwin-dynamic-workspaces</li>
    <li>libsForQt514.kwin-tiling</li>
    <li>libsForQt514.kwrited</li>
    <li>libsForQt514.layer-shell-qt</li>
    <li>libsForQt514.libkscreen</li>
    <li>libsForQt514.libksysguard</li>
    <li>libsForQt514.lightly</li>
    <li>libsForQt514.milou</li>
    <li>libsForQt514.nota</li>
    <li>libsForQt514.oxygen</li>
    <li>libsForQt514.parachute</li>
    <li>libsForQt514.pix</li>
    <li>libsForQt514.plasma-browser-integration</li>
    <li>libsForQt514.plasma-desktop</li>
    <li>libsForQt514.plasma-disks</li>
    <li>libsForQt514.plasma-integration</li>
    <li>libsForQt514.plasma-mobile</li>
    <li>libsForQt514.plasma-nano</li>
    <li>libsForQt514.plasma-nm</li>
    <li>libsForQt514.plasma-pa</li>
    <li>libsForQt514.plasma-sdk</li>
    <li>libsForQt514.plasma-systemmonitor</li>
    <li>libsForQt514.plasma-thunderbolt</li>
    <li>libsForQt514.plasma-vault</li>
    <li>libsForQt514.plasma-workspace</li>
    <li>libsForQt514.plasma-workspace-wallpapers</li>
    <li>libsForQt514.polkit-kde-agent</li>
    <li>libsForQt514.powerdevil</li>
    <li>libsForQt514.qqc2-breeze-style</li>
    <li>libsForQt514.sddm-kcm</li>
    <li>libsForQt514.shelf</li>
    <li>libsForQt514.spectacle</li>
    <li>libsForQt514.systemsettings</li>
    <li>libsForQt514.vvave</li>
    <li>libsForQt514.xdg-desktop-portal-kde</li>
    <li>maui-nota</li>
    <li>milou</li>
    <li>oxygen</li>
    <li>plasma-browser-integration</li>
    <li>plasma-desktop</li>
    <li>plasma-integration</li>
    <li>plasma-mobile</li>
    <li>plasma-nano</li>
    <li>plasma-nm</li>
    <li>plasma-pa</li>
    <li>plasma-systemmonitor</li>
    <li>plasma-thunderbolt</li>
    <li>plasma-vault</li>
    <li>plasma-workspace</li>
    <li>plasma-workspace-wallpapers</li>
    <li>polkit-kde-agent</li>
    <li>powerdevil</li>
    <li>qqc2-breeze-style</li>
    <li>sddm-kcm</li>
    <li>shelf</li>
    <li>spectacle</li>
    <li>systemsettings</li>
    <li>vvave</li>
    <li>xdg-desktop-portal-kde</li>
  </ul>
</details>
<details>
  <summary>79 packages built:</summary>
  <ul>
    <li>digikam</li>
    <li>goverlay</li>
    <li>haruna</li>
    <li>kde-rounded-corners</li>
    <li>libsForQt5.applet-window-buttons</li>
    <li>libsForQt5.bismuth</li>
    <li>libsForQt5.bluedevil</li>
    <li>libsForQt5.breeze-grub</li>
    <li>libsForQt5.breeze-gtk</li>
    <li>libsForQt5.breeze-plymouth</li>
    <li>libsForQt5.breeze-qt5</li>
    <li>libsForQt5.buho</li>
    <li>libsForQt5.clip</li>
    <li>libsForQt5.communicator</li>
    <li>libsForQt5.discover</li>
    <li>libsForQt5.kactivitymanagerd</li>
    <li>libsForQt5.kde-cli-tools</li>
    <li>libsForQt5.kde-gtk-config</li>
    <li>libsForQt5.kde2-decoration</li>
    <li>libsForQt5.kdecoration</li>
    <li>libsForQt5.kdenlive</li>
    <li>libsForQt5.kdeplasma-addons</li>
    <li>libsForQt5.kdev-php</li>
    <li>libsForQt5.kdev-python</li>
    <li>libsForQt5.kdevelop</li>
    <li>libsForQt5.kdevelop-unwrapped</li>
    <li>libsForQt5.kgamma5</li>
    <li>libsForQt5.khotkeys</li>
    <li>libsForQt5.kinfocenter</li>
    <li>libsForQt5.kmenuedit</li>
    <li>libsForQt5.krohnkite</li>
    <li>libsForQt5.kscreen</li>
    <li>libsForQt5.kscreenlocker</li>
    <li>libsForQt5.ksshaskpass</li>
    <li>libsForQt5.ksystemstats</li>
    <li>libsForQt5.kwallet-pam</li>
    <li>libsForQt5.kwayland-integration</li>
    <li>libsForQt5.kwin</li>
    <li>libsForQt5.kwin-dynamic-workspaces</li>
    <li>libsForQt5.kwin-tiling</li>
    <li>libsForQt5.kwrited</li>
    <li>libsForQt5.layer-shell-qt</li>
    <li>libsForQt5.libkscreen</li>
    <li>libsForQt5.libksysguard</li>
    <li>libsForQt5.lightly</li>
    <li>libsForQt5.milou</li>
    <li>libsForQt5.nota</li>
    <li>libsForQt5.oxygen</li>
    <li>libsForQt5.parachute</li>
    <li>libsForQt5.pix</li>
    <li>libsForQt5.plasma-browser-integration</li>
    <li>libsForQt5.plasma-desktop</li>
    <li>libsForQt5.plasma-disks</li>
    <li>libsForQt5.plasma-integration</li>
    <li>libsForQt5.plasma-mobile</li>
    <li>libsForQt5.plasma-nano</li>
    <li>libsForQt5.plasma-nm</li>
    <li>libsForQt5.plasma-pa</li>
    <li>libsForQt5.plasma-sdk</li>
    <li>libsForQt5.plasma-systemmonitor</li>
    <li>libsForQt5.plasma-thunderbolt</li>
    <li>libsForQt5.plasma-vault</li>
    <li>libsForQt5.plasma-workspace</li>
    <li>libsForQt5.plasma-workspace-wallpapers</li>
    <li>libsForQt5.polkit-kde-agent</li>
    <li>libsForQt5.powerdevil</li>
    <li>libsForQt5.qqc2-breeze-style</li>
    <li>libsForQt5.sddm-kcm</li>
    <li>libsForQt5.shelf</li>
    <li>libsForQt5.spectacle</li>
    <li>libsForQt5.systemsettings</li>
    <li>libsForQt5.vvave</li>
    <li>libsForQt5.xdg-desktop-portal-kde</li>
    <li>lightly-qt</li>
    <li>lxqt.lxqt-config</li>
    <li>material-kwin-decoration</li>
    <li>plasma-applet-volumewin7mixer</li>
    <li>sierra-breeze-enhanced</li>
    <li>wacomtablet</li>
  </ul>
</details>

**Comment by andrevmatos** [comment]
@peterhoeg could you give a look into this trivial bump, please?

**Comment by peterhoeg** [comment]
There's a lot of broken packages it seems (forget about the ones with earlier qt versions). polkit, powerdevil, etc.

**Comment by andrevmatos** [comment]
@peterhoeg I don't know what you mean. I can see `libsForQt5.polkit-kde-agent` and `libsForQt5.powerdevil` on the list of built packages, and my commit didn't touch broken flags, so anything that was built before, seems to build here as well, and anything which was marked as broken still is. Can you explain better please, or suggest how to fix the broken packages?

**Comment by peterhoeg** [comment]
I meant all the ones without `libsForQt5`. Looks like there something wrong with some aliases then.

**Comment by andrevmatos** [comment]
I don't understand what's the issue. The non-scoped packages are aliases to `plasma5Packages` scope, and both it and `libsForQt5` are aliases for the same scope, `libsForQt515`, so they're all the same scope and packages. Maybe it's a `nixpkgs-review` confusion when posting the results? Either way, I'm using these packages right now as my desktop, and everything seems to be working fine.

**Comment by peterhoeg** [comment]
That was exactly my concern - thanks for clearing it up. By the time this hits unstable .3 is probably going to be out... ;-)

**Pull request merged**
