### PR TITLE
dovecot2: configure dhparams generation for ssl_dh

### PR DESCRIPTION
**Pull request by mkaito**
With v2.3 you are required to provide ssl_dh=</path/to/dh.pem yourself.

Generating Diffie Hellman params takes a lot of entropy, but I'm
hesitant to just enable haveged as well for everyone.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mkaito** [comment]
As far as I can tell, it works. Deployed it on my mail server.

**Comment by Mic92** [comment]
We have `systemd-random-seed` to hopefully circumvent this. Might be only not available on the first early boot.

**Comment by Mic92** [comment]
cc @fpletz

**Comment by qknight** [comment]
@mkaito please have a look at https://github.com/NixOS/nixpkgs/pull/39507 and either use mine or adapt your PR. i'm fine with both.

please backport either the fixed patch (yours) or mine to 18.03 while also merge it into nixpkgs master. thanks!

**Comment by abbradar** [comment]
I'm going to go with @qknight 's PR for now -- yours generates dhparams unconditionally. Also you don't need to add `requires` or `before` to `dovecot2.service` -- dhparams unit makes itself running before service with the same name as the param automatically.

**Comment by mkaito** [comment]
Sure, works for me.

**Pull request closed without merging**
