### PR TITLE
unbound: enable tests

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Re-try of #141830 after I messed up and GitHub added the entire world as a
reviewer.

cc. @andir @r-burns @vcunat

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]

**Comment by vcunat** [comment]
I think it would be nice if someone tried darwin (at least x86) before merging.

**Comment by SuperSandro2000** [comment]
> I think it would be nice if someone tried darwin (at least x86) before merging.

@risicle @figsoda maybe?

**Comment by figsoda** [comment]
I don't have a darwin machine and github is trying hard compiling llvm right now:
https://github.com/figsoda/nixpkgs-test/runs/4120087989?check_suite_focus=true

**Review by andir — APPROVED** [review]
Tested on aarch64-darwin.

**Comment by Mindavi** [comment]
This appears to have broken cross-compilation, since the checkPhase now runs unconditionally. It could be conditioned `stdenv.buildPlatform == stdenv.hostPlatform`, but I can also imagine that not running the `checkPhase` for the second build would be acceptable too. In that case it doesn't complicate the derivation too much.

**Comment by vcunat** [comment]
This broke `unbound-full` build.  I don't get why.  Example: https://hydra.nixos.org/build/158721793

I can't see it as default anywhere, though I suspect it may be popular in the NixOS service.

**Comment by SuperSandro2000** [comment]
Fails while linking

```
libtool: link: gcc -I. -I/nix/store/prmivl5x54am0h20lrhzjpkf3v1cf495-nettle-3.7.3-dev/include/nettle -I/nix/store/svl0db2avck6c9nhkll8pn942lwwwrnb-libevent-2.1.12-dev/include -I/nix/store/x0ydb9015fz78syaprkvaqhdd5hnih5p-expat-2.4.1-dev/include -I/nix/store/qgpv5qmwkdwbk1kwv5gyn3sd9n6dcmi1-hiredis-1.0.2/include -I/nix/store/1m35q3vym6v2wpfm6drlay2hkaqyc3bb-nghttp2-1.43.0-dev/include -DSRCDIR=. -g -O2 -flto -fPIE -pthread -I/nix/store/pz7j4zi1i81n23hzvnzd0xf9lhql1g8m-protobuf-c-1.3.3/include/google -I/nix/store/vg8wpr00jm59jxb04qhpm3sbqcwr8bqm-libsodium-full/include -pie -Wl,-z -Wl,relro -Wl,-z -Wl,now -o testbound .libs/testbound.o .libs/replay.o .libs/fake_event.o .libs/testpkts.o .libs/worker.o .libs/acl_list.o .libs/daemon.o .libs/stats.o .libs/shm_main.o .libs/dns.o .libs/infra.o .libs/rrset.o .libs/dname.o .libs/msgencode.o .libs/as112.o .libs/msgparse.o .libs/msgreply.o .libs/packed_rrset.o .libs/iterator.o .libs/iter_delegpt.o .libs/iter_donotq.o .libs/iter_fwd.o .libs/iter_hints.o .libs/iter_priv.o .libs/iter_resptype.o .libs/iter_scrub.o .libs/iter_utils.o .libs/localzone.o .libs/mesh.o .libs/modstack.o .libs/view.o .libs/outbound_list.o .libs/alloc.o .libs/config_file.o .libs/configlexer.o .libs/configparser.o .libs/fptr_wlist.o .libs/edns.o .libs/locks.o .libs/log.o .libs/mini_event.o .libs/module.o .libs/net_help.o .libs/random.o .libs/rbtree.o .libs/regional.o .libs/rtt.o .libs/dnstree.o .libs/lookup3.o .libs/lruhash.o .libs/slabhash.o .libs/tcp_conn_limit.o .libs/timehist.o .libs/tube.o .libs/winsock_event.o .libs/autotrust.o .libs/val_anchor.o .libs/rpz.o .libs/validator.o .libs/val_kcache.o .libs/val_kentry.o .libs/val_neg.o .libs/val_nsec3.o .libs/val_nsec.o .libs/val_secalgo.o .libs/val_sigcrypt.o .libs/val_utils.o .libs/dns64.o .libs/cachedb.o .libs/redis.o .libs/authzone.o .libs/edns-subnet.o .libs/subnetmod.o .libs/addrtree.o .libs/subnet-whitelist.o .libs/dnstap.o .libs/dnstap.pb-c.o .libs/dnstap_fstrm.o .libs/dtstream.o .libs/dnscrypt.o .libs/respip.o .libs/ub_event.o .libs/keyraw.o .libs/sbuffer.o .libs/wire2str.o .libs/parse.o .libs/parseutil.o .libs/rrdef.o .libs/str2wire.o .libs/strlcat.o .libs/strlcpy.o .libs/arc4random.o .libs/arc4random_uniform.o .libs/arc4_lock.o  -L/nix/store/prmivl5x54am0h20lrhzjpkf3v1cf495-nettle-3.7.3-dev/lib -L/nix/store/svl0db2avck6c9nhkll8pn942lwwwrnb-libevent-2.1.12-dev/lib -L/nix/store/x0ydb9015fz78syaprkvaqhdd5hnih5p-expat-2.4.1-dev/lib -L/nix/store/qgpv5qmwkdwbk1kwv5gyn3sd9n6dcmi1-hiredis-1.0.2/lib -L/nix/store/1m35q3vym6v2wpfm6drlay2hkaqyc3bb-nghttp2-1.43.0-dev/lib -L/nix/store/pz7j4zi1i81n23hzvnzd0xf9lhql1g8m-protobuf-c-1.3.3/lib -L/nix/store/vg8wpr00jm59jxb04qhpm3sbqcwr8bqm-libsodium-full/lib /nix/store/w4cxxnd6n0lpcb5k96sv0bkkh1j4gqmd-libsodium-1.0.18/lib/libsodium.so /nix/store/pz7j4zi1i81n23hzvnzd0xf9lhql1g8m-protobuf-c-1.3.3/lib/libprotobuf-c.so -levent -L/nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/lib -lsystemd -lhogweed -lnettle -lgmp -lhiredis -lnghttp2 -pthread -Wl,-rpath -Wl,/nix/store/w4cxxnd6n0lpcb5k96sv0bkkh1j4gqmd-libsodium-1.0.18/lib -Wl,-rpath -Wl,/nix/store/pz7j4zi1i81n23hzvnzd0xf9lhql1g8m-protobuf-c-1.3.3/lib -Wl,-rpath -Wl,/nix/store/w4cxxnd6n0lpcb5k96sv0bkkh1j4gqmd-libsodium-1.0.18/lib -Wl,-rpath -Wl,/nix/store/pz7j4zi1i81n23hzvnzd0xf9lhql1g8m-protobuf-c-1.3.3/lib -Wl,-rpath -Wl,/nix/store/prmivl5x54am0h20lrhzjpkf3v1cf495-nettle-3.7.3-dev/lib -Wl,-rpath -Wl,/nix/store/svl0db2avck6c9nhkll8pn942lwwwrnb-libevent-2.1.12-dev/lib
/nix/store/js66s0xwjnzg0ggi2lq9bcvlk6x2za13-binutils-2.35.2/bin/ld: /build/testbound.YBhctd.ltrans11.ltrans.o: in function `dtio_output_cb':
/build/unbound-1.13.2/dnstap/dtstream.c:1488: undefined reference to `dtio_disable_brief_write'
```

**Comment by vcunat** [comment]
Yes, it's quite confusing to me, as I only saw it ever declared as a `static` function and used within the same file.  I might suspect some LTO bug/magic or something.

**Comment by vcunat** [comment]
It's surely related to the way we rebuild libunbound to avoid its dependency on openssl.  Note: the failing symbol [seems](https://github.com/NLnetLabs/unbound/blob/release-1.13.2/dnstap/dtstream.c#L1304) conditioned on openssl support.  That's a bit fragile approach in principle, and apparently with added features (getting into configureFlags on that rebuild) and with the tests it finally breaks.

**Comment by vcunat** [comment]
I'd probably suggest that this `preFixup` part (already turned off in some cases) gets also turned off at least in the `unbound-full` case, as there's probably very little benefit in avoiding the openssl dependency in there.  (and we probably can't claim that nettle is so much better than openssl that we really want to prefer it here)

What do you think?

**Comment by SuperSandro2000** [comment]
Sounds like a plan to me.

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/147719

**Pull request merged**
