### PR TITLE
klavaro: 3.11 -> 3.13, espeak support

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

* Update klavaro
* ensure espeak is available
* bump gtkdatabox to latest (and gtk3) as klavaro requires this
  * (gtkdatabox appears otherwise unused in our tree)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
Perhaps espeak support should be optional?

If it's available via PATH it'll work and the increase in closure size is fairly significant actually:

429M -> 1.1GB :(. (I think I'm measuring this properly anyway haha)

Even so personally I'd rather just ship it full and make lives easier for folks who want or need it, but dunno.  Seems a little sad to optimize disk space at the cost of accessibility needs of some users, and unfortunately options aren't particularly discoverable.

----

* Yes, it works from PATH if available, FWIW
* if not available the GUI experience can be a little confusing, as it just silently doesn't work.  Console logs a message including this text: "Espeak not installed, so we'll say nothing" but not sure if folks will see that.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129707` at cea6b7c6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>gtkdatabox</li>
    <li>klavaro</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl2` is a deprecated license, please check if project uses `lgpl2Plus` or `lgpl2Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/gtkdatabox/default.nix:19:5:
```
   |
19 |     license = lib.licenses.lgpl2;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/gtkdatabox/default.nix:16:3:
```
   |
16 |   meta = {
   |   ^
```
</li>
  </ul>
</details>

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 129707` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gtkdatabox</li>
    <li>klavaro</li>
  </ul>
</details>

**Comment by davidak** [comment]
More than 1 GB is a lot for such a simple program. It would be good to document it in longDescription.

I noticed that 2 icons are missing:

Screenshot from 2021-08-02 08-05-14

I installed espeak, but don't hear anything. How should it work?

```
[davidak@gaming:~]$ nix-env -f channel:nixos-unstable -iA espeak
installing 'espeak-ng-1.50'
building '/nix/store/vdszlnjy16h3qnfvdk54yb193rn0vydp-user-environment.drv'...
created 339 symlinks in user environment
```

**Comment by c0bw3b** [comment]
gtkdatabox update is in nixpkgs since
https://github.com/NixOS/nixpkgs/commit/68daf3df1f64cf91cb823c432e71975b7d006da1

But klavaro bump is still relevant

**Comment by dtzWill** [comment]
> I noticed that 2 icons are missing:

I've created a patch that fixes up a bunch of icon names, fixes missing icons for me.  Only the second icon was missing for me, if it's still missing for you I can check what they're trying to look for and we can investigate.
(my patch was driven by what was missing on my system, FWIW)

> I installed espeak, but don't hear anything. How should it work?

I had trouble with this when putting this together, too.  I think you maybe have to use certain modes and such.  Definitely check the 'Speech' checkmark on the main menu GUI (shown on launch).  It's working for me now on '3. Speed' once you get going it seems to read the next word after each space.

Also, presently this bakes the espeak path into the code, so there's no need to install it separately.  This may be worth revisiting, as mentioned above re:impact on closure and honestly I'm not sure how useful this is even for its intended audience.  But I don't know :).

IIRC if we don't patch it in, it'll attempt to find `espeak` from `PATH`.  If not found the experience isn't great, and I think that's partly what I was trying to address here.

> gtkdatabox update is in nixpkgs since [68daf3d](https://github.com/NixOS/nixpkgs/commit/68daf3df1f64cf91cb823c432e71975b7d006da1)
> 
> But klavaro bump is still relevant

Great, thanks for the follow-up.  I've dropped the redundant gtkdatabox bit and updated the PR.  I think I'll submit these included patches upstream, but haven't done so yet and probably won't get to it tonight.

The invalid free fix was a crashing bug that 1)seemed to bork language detection, sometimes guessing my default should be all manner of things 2)caused crashes (or valgrind issues) especially when starting without `~/.config/klavaro`.  Patch is basically fixing a bug with this method where it only updated it's copy of the pointer (string) not the callee's (and also free'd memory the callee still pointed to).

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 129707` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>klavaro</li>
  </ul>
</details>

**Comment by davidak** [comment]
>I've created a patch that fixes up a bunch of icon names

looks good. upstreaming would be good

Screenshot from 2022-03-14 07-37-45

here is still a missing icon

Screenshot from 2022-03-14 07-51-03


>Definitely check the 'Speech' checkmark on the main menu GUI (shown on launch). 

Where should i see it? As you see in the screenshot, there is no such option.

And i don't hear anything. Even with espeak manually installed.

**Comment by dtzWill** [comment]
Submitted upstream, FWIW (judging by other patches posted, I don't expect a quick response but we'll see!):

* https://sourceforge.net/p/klavaro/patches/18/
* https://sourceforge.net/p/klavaro/patches/19/

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 129707` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>klavaro</li>
  </ul>
</details>

**Comment by davidak** [comment]
>Looks like your interface language is not what you're setting -- if those align does it work?

yes, my system language is en and the training language is de.

when i start with `LANG=de_DE.UTF-8 klavaro` and set all to de, it still don't show the speech button

Screenshot from 2022-03-14 16-42-11

When i select language English (C) or English (UK) the button appears. So i guess that's a feature.

Then the speech works, but it's really bad.

**Review by davidak — APPROVED** [review]
Changes look good

Builds, works

**Pull request merged**
