### PR TITLE
openmw-tes3mp: init at 0.6.0

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Multiplayer for TES3:Morrowind based on OpenMW

###### Things done

Please check what applies. Note that these are not hard requirements but mereley serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abbradar** [comment]
Unfortunately `leaveDotGit` makes `fetchgit` nondeterministic now (I have hash mismatches, for example). Can we get by without using it? For example in `ejabberd` I provide `fakegit` which emulates required commands without using `.git`.

P.S.: Next time when you submit such a PR please prepend a warning about being potentially hazardous to people's free time :D

**Comment by gnidorah** [comment]
@abbradar Got rid of that stuff, thank you! It was useful only for further possible invocations tes3mp-deploy.sh by user. This overall doesn't fit nixpkgs way, instead user may just override this package.

**Comment by abbradar** [comment]
More problems: there are invalid symlinks in the installation:

```
lrwxrwxrwx    2 root root      131 Jan  1  1970 tes3mp-server-default.cfg -> /tmp/nix-build-tes3mp-2017-07-20.drv-0/TES3MP-deploy-7ad5339d044368550d061b3765c264cb670b2f39-src/keepers/tes3mp-server-default.cfg
lrwxrwxrwx    2 root root      131 Jan  1  1970 tes3mp-client-default.cfg -> /tmp/nix-build-tes3mp-2017-07-20.drv-0/TES3MP-deploy-7ad5339d044368550d061b3765c264cb670b2f39-src/keepers/tes3mp-client-default.cfg
lrwxrwxrwx 2 root root 113 Jan  1  1970 examples/resources -> /tmp/nix-build-tes3mp-2017-07-20.drv-0/TES3MP-deploy-7ad5339d044368550d061b3765c264cb670b2f39-src/build/resources
```

Because of this `tes3mp-server` doesn't run.

**Comment by abbradar** [comment]
While you are at it, could you also make `/bin` with needed binaries symlinked? That way it could be installed and used from the system profile.

**Comment by abbradar** [comment]
@gnidorah Why close?

**Comment by gnidorah** [comment]
@abbradar Will re-open and notify you when finish on this. Thanks!

**Comment by gnidorah** [comment]
@abbradar This is what works for me. Is `leaveDotGit = false` absolutely required? Because, the build is non-deterministic either way.

Regarding testing, most of servers today do periodic updates by script and run 0.6.0-current, not release. The game seems to use strict revision client-server matching, so only few servers will be available for gameplay. Self hosting and package override are another options, of course.

**Comment by abbradar** [comment]
@gnidorah The problem is that with `leaveDotGit` hashes change constantly (i.e. to build the game one needs to override the hash in nixpkgs to a different one -- each time). That's worse than just being nondeterministic ;_; What do we need `.git` left for?

Anyway thank you for the update; I'll test it shortly!

**Comment by gnidorah** [comment]
@abbradar Oh, didn't know... `.git` is left for revision check, just didn't noticed it until tried to connect to public servers. So it's to add hash info during build https://github.com/TES3MP/TES3MP/blob/master/cmake/GitVersion.cmake
without hash stored you will not able to connect to any public server.
I will add another solution then.

**Comment by abbradar** [comment]
@gnidorah Ah, I got it. You can workaround this by making a fake `git`:

```
  fakegit = writeScriptBin "git" ''
    #! ${stdenv.shell}
    if [ "$*" = "describe --tags --long" ]; then
      echo "${version}-unknown"
    elif [ "$*" = "rev-parse HEAD" ]; then
      if [ "$(dirname "$(pwd)")" = "xml" ]; then
        echo "${xmlRev}"
      else
        echo "${rev}"
      fi
    elif [ "$*" = "rev-parse HEAD:library/xml" ]; then
      echo "${xmlRev}"
    else
      exit 1
    fi
  '';
```

(it's an example from `dfhack`).

**Comment by gnidorah** [comment]
@abbradar Done, thanks!

**Comment by abbradar** [comment]
@gnidorah See https://github.com/gnidorah/nixpkgs/pull/1. I was able to run a server and connect!

**Comment by abbradar** [comment]
@gnidorah Does it work for you with my changes? If yes, I'll merge.

**Comment by gnidorah** [comment]
@abbradar Works fine. Public servers work too (e.g. Dark Side of Chim). Thanks much for you time and help!

**Comment by abbradar** [comment]
Pushed as b5057f713dc84049a8c9c379973fbc87b7bf784a and others. Thank you for your contribution ^_^

**Pull request closed without merging**
