### PR TITLE
plasma5: 5.18.5 -> 5.19.5

### PR DESCRIPTION
**Pull request by Thra11**
###### Motivation for this change

Update to a more recent version of the plasma desktop. #94103. This update looks to be more straightforward than the update to 5.18.5 was, though it's impossible to say for sure until it's had more extensive testing.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ttuegel** [comment]
Thanks! This seems fine, but I'll need a chance to test it. We should wait to merge this until after the branches for NixOS 20.09 are made because Plasma 5.19 is not a long-term support series.

**Comment by worldofpeace** [comment]
We've branched so no problems there.

**Review by nyanloutre — APPROVED** [review]
Tested on my system, it's working great !

**Comment by jakobrs** [comment]
KDE Plasma 5.20 appears to be released: https://kde.org/announcements/plasma-5.20.0

**Comment by jakobrs** [comment]
Tested this on my system and sddm crashes with `hardware.nvidia.prime.offload`. It works when using nouveau instead.

**Comment by peterhoeg** [comment]
@Thra11, any chance you can change this to the latest 5.20.x release? It supposedly has far superior wayland support.

**Comment by Thra11** [comment]
Yes, although I'm having trouble with the `fetch-kde-qt.sh` script:
```
❯ ./maintainers/scripts/fetch-kde-qt.sh pkgs/desktops/plasma-5
--2020-10-31 15:45:14--  https://download.kde.org/stable/plasma/5.20.2/
Resolving download.kde.org (download.kde.org)... 168.119.32.158, 2a01:4f8:242:1ed5::3
Connecting to download.kde.org (download.kde.org)|168.119.32.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html.tmp’

stable/plasma/5.20.2/index.html.tmp                [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.08s   

2020-10-31 15:45:15 (469 KB/s) - ‘stable/plasma/5.20.2/index.html.tmp’ saved [39825]

Loading robots.txt; please ignore errors.
--2020-10-31 15:45:15--  https://download.kde.org/robots.txt
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 404 Not Found
2020-10-31 15:45:15 ERROR 404: Not Found.

Removing stable/plasma/5.20.2/index.html.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=N;O=D
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=N;O=D.tmp’

stable/plasma/5.20.2/index.html?C=N;O=D.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.02s   

2020-10-31 15:45:15 (1.81 MB/s) - ‘stable/plasma/5.20.2/index.html?C=N;O=D.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=N;O=D.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=M;O=A
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=M;O=A.tmp’

stable/plasma/5.20.2/index.html?C=M;O=A.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.02s   

2020-10-31 15:45:15 (2.07 MB/s) - ‘stable/plasma/5.20.2/index.html?C=M;O=A.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=M;O=A.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=S;O=A
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=S;O=A.tmp’

stable/plasma/5.20.2/index.html?C=S;O=A.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.02s   

2020-10-31 15:45:15 (1.96 MB/s) - ‘stable/plasma/5.20.2/index.html?C=S;O=A.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=S;O=A.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=D;O=A
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=D;O=A.tmp’

stable/plasma/5.20.2/index.html?C=D;O=A.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.004s  

2020-10-31 15:45:15 (9.98 MB/s) - ‘stable/plasma/5.20.2/index.html?C=D;O=A.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=D;O=A.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=N;O=A
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=N;O=A.tmp’

stable/plasma/5.20.2/index.html?C=N;O=A.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.06s   

2020-10-31 15:45:15 (693 KB/s) - ‘stable/plasma/5.20.2/index.html?C=N;O=A.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=N;O=A.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=M;O=D
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=M;O=D.tmp’

stable/plasma/5.20.2/index.html?C=M;O=D.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.02s   

2020-10-31 15:45:15 (1.69 MB/s) - ‘stable/plasma/5.20.2/index.html?C=M;O=D.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=M;O=D.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=S;O=D
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=S;O=D.tmp’

stable/plasma/5.20.2/index.html?C=S;O=D.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.02s   

2020-10-31 15:45:15 (2.14 MB/s) - ‘stable/plasma/5.20.2/index.html?C=S;O=D.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=S;O=D.tmp since it should be rejected.

--2020-10-31 15:45:15--  https://download.kde.org/stable/plasma/5.20.2/?C=D;O=D
Reusing existing connection to download.kde.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stable/plasma/5.20.2/index.html?C=D;O=D.tmp’

stable/plasma/5.20.2/index.html?C=D;O=D.tmp        [ <=>                                                                                               ]  38.89K  --.-KB/s    in 0.02s   

2020-10-31 15:45:15 (2.34 MB/s) - ‘stable/plasma/5.20.2/index.html?C=D;O=D.tmp’ saved [39825]

Removing stable/plasma/5.20.2/index.html?C=D;O=D.tmp since it should be rejected.

FINISHED --2020-10-31 15:45:15--
Total wall clock time: 1.1s
Downloaded: 9 files, 350K in 0.3s (1.32 MB/s)
```

**Comment by hamburger1984** [comment]
Suggesting a fix to the fetch-kde-qt.sh in https://github.com/Thra11/nixpkgs/pull/2. Any feedback welcome :)

**Comment by SuperSandro2000** [comment]
I think this should probably target staging.

**Comment by Thra11** [comment]
Thanks to @hamburger1984's work on the fetch scripts, I have made some progress on updating plasma to 5.20. I've created a new PR, #104810 (targeting staging, thanks @SuperSandro2000!), as it's a little more complicated. Currently stuck on a "cycle detected in references" error.

**Comment by Thra11** [comment]
Superseded by #104810, which has been merged.

**Pull request closed without merging**
