### PR TITLE
gnomeExtensions.ddterm: unbreak

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

fixes https://hydra.nixos.org/build/241558776
ZHF https://github.com/NixOS/nixpkgs/issues/265948

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by piegamesde** [comment]
Given that https://github.com/ddterm/gnome-shell-extension-ddterm/commit/0a263a15a6ac82274ebf3e4f6b98e7b226e8188a is the commit that broke it, are you sure this is the best way to fix this?

I am just tempted to simply apply a revert of that commit as a patch for now, and then maybe communicate with upstream for a better solution. CC @jtojnar 

(Btw apologies for the breakage, I didn't properly test the last update before the merge, at least two more extensions need fixups too)

**Comment by pbsds** [comment]
I don't know enough js nor gnome-shell to understand the issue. From what i gather i assume they want to run the script from js with the proper runtime instead of relying on its shebang?

Then a revert is better :+1:

**Comment by jtojnar** [comment]
Yeah, this will not work. The wrapper turns the JS file into an ELF program but ddterm now calls a JS interpreter with the supposed JS file as an argument. That will fail because JS interpreter will not be able to run an ELF program.

Revert and talking to upstream is probably best option. Example from another extension: https://github.com/GSConnect/gnome-shell-extension-gsconnect/commit/71c86dbb1e3434859331de56bbf0bb38560c8baa

**Comment by TheRealGramdalf** [comment]
For reference see:

https://github.com/ddterm/gnome-shell-extension-ddterm/issues/597
https://github.com/NixOS/nixpkgs/issues/259035

**Comment by pbsds** [comment]
The revert would look something like this:
<details>

```diff
index e195ebc9b8e3..ec7148a6763f 100644
--- a/pkgs/desktops/gnome/extensions/extensionOverrides.nix
+++ b/pkgs/desktops/gnome/extensions/extensionOverrides.nix
@@ -1,6 +1,7 @@
 { lib
 , ddcutil
 , easyeffects
+, fetchpatch
 , gjs
 , glib
 , gnome
@@ -49,9 +50,20 @@ super: lib.trivial.pipe super [
   (patchExtension "ddterm@amezin.github.com" (old: {
     nativeBuildInputs = [ gobject-introspection wrapGAppsHook ];
     buildInputs = [ vte ];
+    patches = [
+      (fetchpatch {
+        name = "use-same-gjs-interpreter-when-launching-script.patch";
+        url = "https://github.com/ddterm/gnome-shell-extension-ddterm/commit/0a263a15a6ac82274ebf3e4f6b98e7b226e8188a.diff";
+        hash = "sha256-pU1PbAPMRUvalLn+FxzLEW6EuJBi8hQFeV8iBymjRZc=";
+        revert = true;
+      })
+    ];
     postFixup = ''
+      # fetchpatch strips file permission changes
+      # https://github.com/NixOS/nixpkgs/issues/266556
+      wrapGApp_() { chmod +x "$1" && wrapGApp "$1"; }
       wrapGApp "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm"
-      wrapGApp "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/dependencies-notification.js"
+      wrapGApp_ "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/dependencies-notification.js"
     '';
   }))
```
</details>

while a store-patch is much more succinct, but does not guarantee that the `gappsWrapperArgs[@]` `makeWrapper` arguments take effect.

<details>

```diff
--- a/pkgs/desktops/gnome/extensions/extensionOverrides.nix
+++ b/pkgs/desktops/gnome/extensions/extensionOverrides.nix
@@ -51,7 +51,10 @@ super: lib.trivial.pipe super [
     buildInputs = [ vte ];
     postFixup = ''
       wrapGApp "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm"
-      wrapGApp "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/dependencies-notification.js"
+      substituteInPlace "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/dependencies-notification.js" \
+        --replace \
+          'function get_interpreter() {' \
+          'function get_interpreter() { return "${lib.getExe gjs}";'
     '';
   }))
```
</details>

[This line change](https://github.com/ddterm/gnome-shell-extension-ddterm/commit/0a263a15a6ac82274ebf3e4f6b98e7b226e8188a#diff-22378ea9dd56013e8579f5bc48a0f599955b6d8fe4d67bed5ab6b00ae2ce7a75R122) may indicate that the wrapper is not needed?

**Comment by jtojnar** [comment]
Wrapping will be almost certainly needed if the script uses any typelibs or settings schemas not used by GNOME Shell. If only glib typelibs are used, those should be available in gjs even without any extra environment variables. If the spawned process does not inherit environment variables from GNOME Shell, wrapper will be needed for any settings schemas.

But since it looks like the upstream patch was introduced because of NixOS in the first place, we might want to revert it upstream.

**Comment by piegamesde** [comment]
According to upstream, simply removing the `wrapGApp "$out/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/app/dependencies-notification.js"` should be sufficient, as it is dead code anyways on NixOS given that all dependencies are properly installed.

**Pull request merged**
