### PR TITLE
weather: fix file locations, add python dependency

### PR DESCRIPTION
**Pull request by romildo**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I'm not sure whether we can turn this into a `pythonPackage`, actually?

**Comment by romildo** [comment]
A `pythonPackage` would bring an unneeded additional dependency on `distutils`.

**Comment by matthiasbeyer** [comment]
Works for me, so ACK.

**Comment by fpletz** [comment]
Thanks! Travis build is unrelated.

**Pull request merged**
