### PR TITLE
python3.pkgs.ambee: don't re-distribute package

### LINKED ISSUE #126677: Remove `python3Packages.ambee` package
**Project description**

The Ambee Python package, for which I'm the author, was merged in #126326 (which contains more context) (and was even merged with an incompatible version to make a statement?).

Please revert this decision and remove this package from this project.

Me, as the author of that source, does not want to be distributed in this project in the way it is distributed. Especially considering the way it was handled.

I ask nicely and hopefully can be respectfully honored by this project.

Thank you for your time and consideration.

With kind regards,

Franck Nijhof

### PR DESCRIPTION
**Pull request by Mic92**
Closes https://github.com/NixOS/nixpkgs/issues/126677

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by frenck** [comment]
This incorrectly marks fixing #126677.

#126677 requests removal.

**Comment by Mic92** [comment]
> This incorrectly marks fixing #126677.
> 
> #126677 requests removal.

I disagree, you requested nixpkgs not to re-distribute the package. This change makes the package build only on the end-user machine.

**Comment by frenck** [comment]
> I disagree, you requested nixpkgs not to re-distribute the package.

That was before you just ignored future communication and merged (even worse: an incompatible version).

Please remove it as requested. I don't want anything of myself to be associated with this project as of now.

**Comment by lukegb** [comment]
Locked for now. Please see https://github.com/NixOS/nixpkgs/issues/126677#issuecomment-860071285. Please don't merge this until everyone's had a chance to cool off.

**Pull request closed without merging**
