### PR TITLE
xapianBindings: 1.2.23 -> 1.4.0

### PR DESCRIPTION
**Pull request by joachifm**
The xapianBindings version is now directly tied to the input xapian version, to ensure that they're in synch.

Also, as of this version, sphinx is required to build documentation for the python bindings.

Unfortunately, this fails during sphinx-build with this message

> phinx-1.3.6/bin/sphinx-build -b html -d doctrees -c docs ./docs docs/html
>   File "/nix/store/44yfnh360zs4y9166nszxbax0s604ap3-python2.7-Sphinx-1.3.6/bin/sphinx-build", line 2
>     export PATH=/nix/store/hdny4a03ys50hh56k6z1w3z8sl0hf2ym-python-2.7.12/bin:/nix/store/44yfnh360zs4y9166nszxbax0s604ap3-python2.7-Sphinx-1.3.6/bin:/nix/store/rgg514gp6qgy6qr88937ia2g34qbhgr0-python2.7-docutils-0.12/bin:/nix/store/p5n1lbm3rs3d4bkpq249fg5rs2iw8kp2-python2.7-setuptools-26.1.1/bin:/nix/store/xf1iba7792l5y14l6zl1xvs9ya24mfd7-python2.7-Pygments-2.1.3/bin:/nix/store/ixjj1vbz38mk4sr78x8dv1llkk1prg0f-python2.7-Babel-2.3.4/bin${PATH:+:}$PATH
>               ^
> SyntaxError: invalid syntax

I'm inclined to disable python bindings for now, to get `sup` working again.

### CODE REVIEW

**Comment by joachifm** [comment]
cc @oxij

**Comment by oxij** [comment]
I think I fixed that in the first patch of my
pull/18272-xapianBindings-1.4.0 branch.

See
https://github.com/NixOS/nixpkgs/compare/master...oxij:pull/18272-xapianBindings-1.4.0

Also consider the other two patches.

**Comment by joachifm** [comment]
@oxij looks good to me, thank you

**Comment by joachifm** [comment]
Still some work required to get sup to work, once I have fixed it, I'll pull in your patches into this and merge.

**Comment by joachifm** [comment]
Ugh, seems like the xapian-ruby gem is tied to 1.2.22 only ...

**Comment by oxij** [comment]
Okay, thanks.

**Comment by joachifm** [comment]
I'll merge this anyway, and deal with sup later, looks like it doesn't use `xapianBindings` anyway.

**Pull request merged**
