### PR TITLE
Drop old Flutter versions

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Things done

Drops:
- Flutter 3.13
- Flutter 3.16
- Flutter 3.22
- Flutter 3.23

Updates:
- localsend
- fluffychat
- finamp
- firmware-updater
- flutter324

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
Result of `nixpkgs-review` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages built:</summary>
  <ul>
    <li>ente-auth</li>
    <li>ente-auth.debug</li>
    <li>ente-auth.pubcache</li>
    <li>finamp</li>
    <li>finamp.debug</li>
    <li>finamp.pubcache</li>
    <li>firmware-updater</li>
    <li>firmware-updater.debug</li>
    <li>firmware-updater.pubcache</li>
    <li>flet-client-flutter</li>
    <li>flet-client-flutter.debug</li>
    <li>flet-client-flutter.pubcache</li>
    <li>flutter</li>
    <li>flutterPackages-source.stable</li>
    <li>hover</li>
    <li>localsend</li>
    <li>localsend.debug</li>
    <li>localsend.pubcache</li>
    <li>musicpod</li>
    <li>musicpod.debug</li>
    <li>musicpod.pubcache</li>
    <li>python311Packages.flet</li>
    <li>python311Packages.flet-runtime</li>
    <li>python311Packages.flet-runtime.dist</li>
    <li>python311Packages.flet.dist</li>
    <li>python312Packages.flet</li>
    <li>python312Packages.flet-runtime</li>
    <li>python312Packages.flet-runtime.dist</li>
    <li>python312Packages.flet.dist</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Review by mkg20001 — APPROVED** [review]

**Review by DSeeLP — COMMENTED** [review]
Hey! I just wanted to let you know that I opened a PR to update finamp to 0.9.11-beta 2 weeks ago (#342972). It also updates the Flutter version to 3.24.

**Comment by RossComputerGuy** [comment]
> Hey! I just wanted to let you know that I opened a PR to update finamp to 0.9.11-beta 2 weeks ago

Cool, didn't see that. I'll take a look at it and can merge that then remove it from this PR.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
@DSeeLP dropped the change after the finamp PR was merged.

**Review by DSeeLP — APPROVED** [review]

**Pull request merged**
