### PR TITLE
Fetchdir

### PR DESCRIPTION
**Pull request by Profpatsch**
This PR has two changes that closely build on each other.

First one is a refactor for an often copied list of `impureEnvVars`, which is also needed by the second change.

Second one is a new fetcher called `fetchdir`, that can grab upstream packages that come as http/ftp/… folders, based on wget.
Its functionality can be tested with this example:

``` nix
fetchdir {
    url = "https://userpages.uni-koblenz.de/~krienke/ftp/noarch/geteltorito/";
    sha256 = "0b98hfvbfhgi9sp1f3a2b3k90arzk1pzk4c6g63l1ra7jn6xm9x0";
    cut-dirs = 4;
}
```

cc @aszlig

### CODE REVIEW

**Review by grahamc — APPROVED** [review]
Huge :+1: on these changes.

**Comment by grahamc** [comment]
For clarity I :+1: the first commit. The second commit I don't feel so sure about, as it almost seems better to have specific URLs listed, even if you want several. +0 on the `fetchdir`.

**Comment by Profpatsch** [comment]
@grahamc For reference this is directly used by [a package](https://github.com/NixOS/nixpkgs/pull/18614), in an epic yak-shaving adventure.

**Comment by grahamc** [comment]
I can definitely see your pain here, and can sympathize. :(

Even more, (IMHO) it should only be used if the directory won't change at all, and a _new_ directory will be made with the new release. This fetcher almost guarantees out of date nixpkg repositories will have a broken definition.

**Comment by Profpatsch** [comment]
> This fetcher almost guarantees out of date nixpkg repositories will have a broken definition.

Dou are right, I didn’t consider that. It probably also breaks if timestamps change.
I annotated the fetcher with warning messages.

**Comment by vcunat** [comment]
This conflicts with another PR of yours ;-)

**Comment by Profpatsch** [comment]
Yeah, I split them up so they could be separated from each other.

**Pull request closed without merging**
