### PR TITLE
factorio-experimental, factorio-headless-experimental: 1.0.0 -> 1.1.0

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

Update experimental branch (https://forums.factorio.com/viewtopic.php?f=3&t=91657)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
hash mismatch in fixed-output derivation '/nix/store/ivipxraqpw38zqsqskqcs5fwb10lf4x2-factorio_alpha_x64-1.1.0.tar.xz':
  wanted: sha256:0n00nbh44nyf485jys6pkga3pb9j4zywk0liq6jq99pil6z7na3y
  got:    sha256:0dxi6my1xhwr9178pj13axzhvvn1yc053kc1halc9pl5iqlanipq
cannot build derivation '/nix/store/wpv10mgpja7sdrw3q66h7mpjawcr1yzp-factorio-alpha-1.1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/c0gck6pw770kq1j0j7wg0xdw4xg3554r-env.drv': 1 dependencies couldn't be built
```

Did they already do the reupload for the failed update package?

Anyway. The factory must frow.

**Comment by lukegb** [comment]
> Edit: or this package is not idiot proof. I did not provide any credentials because I am lazy and headless should work without in nixpkgs-review.

Yeah, non-headless needs creds and the f-o error message isn't super helpful...

**Review by erictapen — APPROVED** [review]
Builds for me, thanks!

**Review by elitak — COMMENTED** [review]
lgtm.

**Pull request merged**
