### PR TITLE
tracker-miners, gnome-music: add some gstreamer plugins

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes
Add some gstreamer plugins for extras codecs. I don't know which codecs are added but I'm sure `gst-plugins-good` and `gst-libav` are needed for m4a. However it seems gnome music still doesn't work with m4a.

###### Things done
Add some gstreamer plugins for extras codecs.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
I ran reset manully and now m4a files are detected. It seems the service has some problems. 

```
$ systemctl --user status tracker-extract-3.service 
○ tracker-extract-3.service - Tracker metadata extractor
     Loaded: loaded (/etc/systemd/user/tracker-extract-3.service; linked-runtim>
     Active: inactive (dead)

 PC systemd[1417]: Starting Tracker metadata extractor...
 PC systemd[1417]: Started Tracker metadata extractor.
```

**Comment by linsui** [comment]
gnome-music also need gdt-libva to play m4a files.

**Comment by linsui** [comment]
gnome-music also need gdt-libva to play m4a files.

**Comment by jtojnar** [comment]
What is the output size difference? It might be problematic for the ISO.

**Comment by linsui** [comment]
How to check that? I'm not familiar with it...

**Comment by jtojnar** [comment]
With experimental command `nix path-info -Sh -f . tracker-miners`

**Comment by linsui** [comment]
I get

```
$ nix path-info -Sh -f . tracker-miners --extra-experimental-features nix-command
querying info about missing paths/nix/store/6q9hfiapd2kcxf47hp00y3s5q41lk56v-tracker-miners-3.3.0          1.5G
```

**Comment by jtojnar** [comment]
On master, I get 1.1G, so that looks like 400 MB (36%) increase. We will also need to check how it affect the ISO size.

**Comment by linsui** [comment]
That's pretty large. How to check the ISO size?

**Comment by jtojnar** [comment]
You will need to build the ISO with `nix-build nixos/release.nix -A iso_gnome` and then check the result size.

**Comment by linsui** [comment]
I got exactly the same size. Did I miss somthing?

**Comment by linsui** [comment]
What else can I do?

**Comment by linsui** [comment]
Any update? Since I'm using amberol now I don't need this anymore.

**Comment by jtojnar** [comment]
Looks like gst-libav are pulled in through totem and evince anyway so it will not affect the closure size of the ISO.

Not sure how gstlibav works with regards to tag support and priorities but at least some of the plug-ins are already needed for [writeback support](https://gitlab.gnome.org/GNOME/tracker-miners/-/blob/732fa4b03bff8aaecacfdd0a7dad695d2c90b477/src/tracker-writeback/tracker-writeback-gstreamer.c):

- good for flactag
- bad for id3mux

**Comment by linsui** [comment]
Thanks!

**Pull request merged**
