### PR TITLE
gimp: 2.10.24 → 2.10.28

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
https://gimp.org/news/2021/09/18/gimp-2-10-28-released

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
  CC       gui.o
gui.c:285:36: error: use of undeclared identifier 'GDK_OSX_BIG_SUR'; did you mean 'GDK_OSX_TIGER'?
  if (gdk_quartz_osx_version () >= GDK_OSX_BIG_SUR)
                                   ^~~~~~~~~~~~~~~
                                   GDK_OSX_TIGER
/nix/store/zfafclah6qr545n47kwp5jv44mg2zybv-gtk+-2.24.32-dev/include/gtk-2.0/gdk/gdkquartz.h:46:3: note: 'GDK_OSX_TIGER' declared here
  GDK_OSX_TIGER = 4,
  ^
1 error generated.
```

down to us using an old macos sdk?

**Comment by risicle** [comment]
Actually thinking harder it probably suggests we're using a too-old gtk2.

**Comment by jtojnar** [comment]
Weird, I thought we have already upgraded to [2.24.33](https://gitlab.gnome.org/GNOME/gtk/-/commit/68631945733158f164427db84f01301d7e875763). At least I remember reading some release notes mentioning final GTK2 version :woman_shrugging:

**Comment by risicle** [comment]
Been dreaming about nixpkgs again

**Comment by siraben** [comment]
Related to #101229

**Comment by jtojnar** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/138797

**Pull request merged**
