### PR TITLE
elixir: 1.12.1 -> 1.12.2

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
@ofborg build pleroma

**Comment by turion** [comment]
@ofborg test pleroma

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132434` at 3411c044 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/ff762be2732c47e5bf895735025f6af7">pleroma</a></li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>elixir (elixir_1_12)</li>
    <li>elixir_ls</li>
    <li>mix2nix</li>
    <li>plausible</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/interpreters/elixir/generic-builder.nix:28:3:
```
   |
28 |   name = "${baseName}-${version}";
   |   ^
```

Near pkgs/development/interpreters/elixir/generic-builder.nix:30:10:
```
   |
30 |   inherit src version debugInfo;
   |          ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by turion** [comment]
I'm not sure what the best way to go forward here is. This will break a few builds, I believe, but I don't know how to find out which ones.

**Comment by happysalada** [comment]
Thank you for the PR
The original discussion is here https://github.com/NixOS/nixpkgs/pull/129094
there is a link to a pending PR that provides a fix.
If you have time to test that PR, help is welcome!
(any comments in fact are welcome)

**Comment by happysalada** [comment]
Also forgot to say, if you have anything elixir or erlang related feel free to tag @NixOS/beam and you should get feedback relatively quickly.

**Comment by turion** [comment]
Closed as duplicate of https://github.com/NixOS/nixpkgs/pull/129094. Thanks for the info!

**Pull request closed without merging**
