### PR TITLE
Tribler update

### PR DESCRIPTION
**Pull request by cheecheeo**

### CODE REVIEW

**Comment by pSub** [comment]
Does this work for you? There were previous attempts to update tribler, all some issues. Currently there is #7012 open.

**Comment by cheecheeo** [comment]
@pSub I've successfully searched using the search functionality and downloaded a torrent. There is an intermediate popup that you need to close every once in a while that I haven't addressed.
screenshot from 2015-07-12 21 34 23

**Comment by pSub** [comment]
Sounds great. Thanks!

**Comment by vcunat** [comment]
These warnings are generated by libpng on some images. See e.g. https://wiki.archlinux.org/index.php/Libpng_errors

**Comment by cheecheeo** [comment]
@vcunat Thanks for the tip. Follow up PR:  #8810

**Pull request merged**
