### PR TITLE
buildEnv: Check the content of colliding paths.

### PR DESCRIPTION
**Pull request by aszlig**
Originally wanted to include `ignoreCollisions` in cups-progs, but I think it's better if we use `ignoreCollisions` only if there are _real_ collisions between files with different contents.

Of course, we also check whether the file permissions match, so you get a collision if contents are the same but the permissions are different.

Cc for review to @edolstra and @domenkozar

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Is there any reason not to merge it? Removing ignoreCollisions from ghcWithPackages sounds like a good idea.

**Comment by aszlig** [comment]
It would also reduce the noise printed by `buildEnv'. @edolstra any objections?

**Comment by edolstra** [comment]
Where exactly do we have collisions between binaries with the same name and identical contents?

**Comment by aszlig** [comment]
@edolstra: One thing that comes immediately into my mind would be reducing the noise [while building the `system-path`](https://headcounter.org/hydra/build/645075/nixlog/1/raw). And `ghcWithPackages` as @7c6f434c pointed out already.

**Comment by peti** [comment]
`ghcWithPackages` does not use `ignoreCollisions = true`. Even if it would, I am not aware of any case where identical files would collide.

**Comment by vcunat** [comment]
@aszlig: does this address the problem I see on IRC that a directory won't merge with a valid symlink to a directory?

**Comment by aszlig** [comment]
@vcunat: It doesn't handle directories at all, nor does it dereference symlinks, but the checkCollision could be extended to handle that as well.

**Comment by bennofs** [comment]
:+1: I've had collisions between identical files quite often with texlive if I recall correctly, since texlive symlinks a lot of tools.

**Comment by vcunat** [comment]
Hehe, texlive won't be an issue any longer (also in this respect). I'll post updates to #287 when I get a little further (or request on IRC/mail if you hurry).

**Comment by DamienCassou** [comment]
What is the status of this?

**Comment by domenkozar** [comment]
I'd like to merge this, @aszlig can you rebase?

**Comment by aszlig** [comment]
@domenkozar: Rebased.

**Pull request merged**
