### PR TITLE
python3Packages.js2py: remove

### PR DESCRIPTION
**Pull request by ruby0b**
#348943 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — CHANGES_REQUESTED** [review]
Thank you for tackling this!

The comment/`passthru` stuff in `pyjsparser` should be cleaned up. Maybe there’s a subset of tests we can run without `js2py`?

**Comment by ruby0b** [comment]
Looks like [pyjsparser's tests](https://github.com/PiotrDabkowski/pyjsparser/blob/master/test_runner.py) all use js2py unfortunately

**Review by natsukium — APPROVED** [review]
LGTM

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 349550` at 0f79dd41 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/05c4c82e533ef24a089cf6ad5a955c40">python311Packages.jupysql</a></li>
    <li><a href="https://gist.github.com/natsukium/0d32221f3d1ec2f475e34361fc57048a">python312Packages.jupysql</a></li>
    <li>tandoor-recipes</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>pyload-ng</li>
    <li>python311Packages.django-js-reverse</li>
    <li>python312Packages.django-js-reverse</li>
  </ul>
</details>

**Review by emilazy — APPROVED** [review]
`jupysql` failure looks unrelated. Thanks for tackling this!

**Pull request merged**
