### PR TITLE
python3Packages.poppler-qt5: reduce the amount of patching done to `pyproject.toml`

### PR DESCRIPTION
**Pull request by eduardosm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eduardosm** [comment]
Result of `nixpkgs-review pr 128293` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>frescobaldi</li>
    <li>krop</li>
    <li>python38Packages.poppler-qt5</li>
    <li>python39Packages.poppler-qt5</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128293` at 6c3c539c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>frescobaldi</li>
    <li>krop</li>
    <li>python38Packages.poppler-qt5</li>
    <li>python39Packages.poppler-qt5</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `pythonPackages`.
Near pkgs/development/python-modules/poppler-qt5/default.nix:6:3:
```
  |
6 | , pythonPackages
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `stdenv`.
Near pkgs/development/python-modules/poppler-qt5/default.nix:1:3:
```
  |
1 | { stdenv
  |   ^
```
</li>
  </ul>
</details>

**Comment by eduardosm** [comment]
> 2 suggestions:

Fixed

**Comment by SuperSandro2000** [comment]
@eduardosm is this not required? Why was it added before? Will this cause regressions?

**Comment by eduardosm** [comment]
> @eduardosm is this not required? Why was it added before? Will this cause regressions?

It was added because it was required with sip 5, but sip 6 does not seem to need it. In fact, the current `sip-include-dirs` value is wrong (directory changed after updating sip), so I believe sip 6 is ignoring it (or automatically falling back to the correct one).

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 128293` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>frescobaldi</li>
<li>krop</li>
<li>python38Packages.poppler-qt5</li>
<li>python39Packages.poppler-qt5</li>
</ul>
</details>

**Pull request merged**
