### PR TITLE
helix: 0.6.0 -> 22.03

### PR DESCRIPTION
**Pull request by danth**
###### Description of changes

Updated Helix to version 22.03. [See the changelog.](https://github.com/helix-editor/helix/blob/master/CHANGELOG.md#2203-2022-03-28)

I've disabled the new tree-sitter grammar system because it tries to download things during the build phase.
If the compiled grammars were included as part of the older package we may wish to get this enabled again before merging.

(Also added myself as a maintainer for this package.)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yusdacra** [comment]
> If the compiled grammars were included as part of the older package we may wish to get this enabled again before merging.

This should be done, since otherwise it would break some people's setups (including mine). For this we need an update script that will use git to fetch the grammars and write commit and hashes to a file, then a Nix expression can use these to generate `pkgs.fetchGit` entries, and these then can be built and shipped with the package derivation. This is already done in upstream helix repo like so https://github.com/helix-editor/helix/blob/master/grammars.nix. This should just be adapted to work with nixpkgs, as nixpkgs disallows `builtins.fetchTree` afaik (restricted eval), but if an update script is made this shouldn't be a problem.

**Comment by the-mikedavis** [comment]
We also now publish a tarball that contains the source code with the grammar repositories pre-fetched into `runtime/grammars/sources/` (https://github.com/helix-editor/helix/releases/tag/22.03 `helix-22.03-source.tar.xz`). I think you should be able to build helix from this tarball without `HELIX_DISABLE_AUTO_GRAMMAR_BUILD` set - when all the grammars are checked out at the desired revision, there shouldn't be any network requests.

**Comment by danth** [comment]
@the-mikedavis Thanks, I'll try using the tarball. That makes things much simpler!

**Review by 90-008 — APPROVED** [review]
Looks good to me! The tarball really makes things simpler :slightly_smiling_face:

**Comment by happysalada** [comment]
Thank you!

**Pull request merged**
