### PR TITLE
memo: 0.2 -> 0.4

### PR DESCRIPTION
**Pull request by mrVanDalo**
###### Motivation for this change

Version bump (with some new features)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build memo

**Comment by xeji** [comment]
The new dependency on `pandoc` causes aarch64 build to fail (Haskell is currently broken on aarch64) and increases closure size.  You may want to consider making `pandoc` support optional.

**Comment by mrVanDalo** [comment]
Oh. Yeah I'll create a task for that an will fix that in the next days.

**Comment by xeji** [comment]
Marking this as WIP until then.

**Comment by mrVanDalo** [comment]
@xeji I made pandoc optional. Is there more to do for the aarch64 structure ?

**Comment by xeji** [comment]
@GrahamcOfBorg build memo

**Comment by xeji** [comment]
Thank you, looks good.

**Pull request merged**
