### PR TITLE
firefox: 93.0 -> 94.0; firefox-esr-91: 91.2.0 -> 91.3.0; firefox-esr-78: drop; thunderbird-78: drop

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://www.mozilla.org/en-US/firefox/94.0/releasenotes/
https://www.mozilla.org/en-US/firefox/91.3.0/releasenotes/

Firefox 78 ESR is EOL, so we'll drop it here and now.
- Can't remove nss_3_53 at this point because xmlsec is still using it. Haven't investigated if that is still required.

Same for Thunderbird 78.

Removes rust_1_45.

Supersedes: #136889 (sorry, remembered too late that you started that process already)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Tested:
- firefox-wayland (sway, pipewire)
  - [x] YouTube
  - [x] YouTube Live
  - [x] Webcam
  - [x] Microphone
  - [x] Screensharing (xdg-portal-wlroots)

**Comment by vcunat** [comment]
I switched my main browser to 94; no issues so far.  (x86_64 NixOS, X11)

**Comment by ajs124** [comment]
All releases build for me on x86_64-linux and the nixos tests also still pass.

**Comment by mweinelt** [comment]
Dropped `rust_1_45` and migrated firefox to `llvmPackages_12` (up from `llvmPackages_10`). Because

```
❯ nix-build -A rustPackages.rustc
/nix/store/xb2mi732gsbwjwj2pmpadyk0zii15g0a-rustc-1.55.0
❯ result/bin/rustc -vV
rustc 1.53.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

**Comment by vcunat** [comment]
Should they _always_ be the same?

**Comment by mweinelt** [comment]
Yes, according to https://github.com/NixOS/nixpkgs/blob/26a56abd090ec5c8f4c6c9e1189fbfa4bcb8db3f/pkgs/applications/networking/browsers/firefox/common.nix#L100.

**Comment by vcunat** [comment]
Then should we directly inherit llvmPackages from rustc, via `passthru`?

**Comment by mweinelt** [comment]
I think that did it. No rebuilds required.

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 144219` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.sunpy</li>
    <li>python39Packages.sunpy</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>apacheHttpdPackages.mod_auth_mellon (apacheHttpdPackages_2_4.mod_auth_mellon)</li>
    <li>firefox-esr-unwrapped (firefox-esr-91-unwrapped ,firefoxPackages.firefox-esr-91)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>gnucash</li>
    <li>kmymoney</li>
    <li>lasso</li>
    <li>lexicon</li>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>powerdns-admin</li>
    <li>python38Packages.pysaml2</li>
    <li>python38Packages.python3-saml</li>
    <li>python38Packages.total-connect-client</li>
    <li>python38Packages.xmlsec</li>
    <li>python38Packages.zeep</li>
    <li>python39Packages.pysaml2</li>
    <li>python39Packages.python3-saml</li>
    <li>python39Packages.total-connect-client</li>
    <li>python39Packages.xmlsec</li>
    <li>python39Packages.zeep</li>
    <li>slimerjs</li>
    <li>thunderbird-unwrapped (thunderbirdPackages.thunderbird)</li>
    <li>xmlsec</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
That nixpkgs-review seems very much unrelated to this pull request.

**Review by andir — APPROVED** [review]

**Review by lovesegfault — APPROVED** [review]

**Pull request merged**
