### PR TITLE
check-meta.nix: make non-source consistent with documentation

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

The documentation for `meta.sourceProvenance` in `doc/stdenv/meta.chapter.md` says: "the `meta.sourceProvenance` attribute should be a list containing one or more value..."

Let's update check-meta.nix to require that `meta.sourceProvenance` is a list, as the documentation says, rather than a single element.

Adding two extra keystrokes `[` and `]` when filling out this field is an insignificant burden for package authors, and being able to assume that the `meta.sourceProvenance` field is always a list greatly simplifies any code that acts on the value of this field.  For example, it simplifies the `sourceProvenance` example given in `check-meta.nix`; the simplification is included in this PR.

Since `meta.sourceProvenance` was just merged a few hours ago now is the easiest time to fix this: nobody is using the feature yet.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by a-m-joseph** [comment]
@risicle should be added as a reviewer (am I able to add reviewers to my own PRs?)

**Comment by Artturin** [comment]
> @risicle should be added as a reviewer (am I able to add reviewers to my own PRs?)

Yes it you're a member of the maintainer team which you can join by being a maintenance of a package and accepting the invite

**Comment by a-m-joseph** [comment]
> Yes it you're a member of the maintainer team which you can join by being a maintainer of a package and accepting the invite

Yeah, I really procrastinated a long time before doing [this](https://github.com/NixOS/nixpkgs/pull/178213).

**Comment by a-m-joseph** [comment]
Resolved the merge conflict and squashed.

**Comment by risicle** [comment]
What error does this now give if you assign a single `sourceType` then?

**Comment by amjoseph-nixpkgs** [comment]
```
$ curl -o outpaths.nix https://raw.githubusercontent.com/NixOS/ofborg/released/ofborg/src/outpaths.nix
$ GC_INITIAL_HEAP_SIZE=4g nix-env -f ./outpaths.nix -qaP --no-name --out-path --arg checkMeta true > out-paths
error: value is a set while a list was expected

       at /git/nixpkgs/pkgs/stdenv/generic/check-meta.nix:93:30:

           92|
           93|   isNonSource = sourceTypes: lib.lists.any (t: !t.isSource) sourceTypes;
             |                              ^
           94|
(use '--show-trace' to show detailed location information)
```

**Comment by amjoseph-nixpkgs** [comment]
If you want to see what OfBorg's complaint would look like, see #180036.

**Comment by amjoseph-nixpkgs** [comment]
Rebased.

**Pull request merged**
