### PR TITLE
aws-sam-cli: disable telemetry

### PR DESCRIPTION
**Pull request by stefano-m**
###### Motivation for this change

Since v0.19.0 aws-sam-cli sends telemetry data to AWS[1]. To protect the users'
privacy, we opt-out by default.

[1] https://github.com/awslabs/aws-sam-cli/issues/1272

Cc maintainers @andreabedini @dhl 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stefano-m** [comment]
Example runs:

# Telemetry enabled

Output edited to improve readability.

Note that they assign unique values to:

- requestId
- installationId
- sessionId

```
 ./result-with-telemetry/bin/sam init --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: ^C
Sending Telemetry: {'metrics': 
 [
     {'commandRun': 
      {'awsProfileProvided': False, 
       'debugFlagProvided': True, 
       'region': '',
       'commandName': 'sam init', 
       'duration': 6709, 
       'exitReason': 'Abort', 
       'exitCode': 255, 
       'requestId': '<REDACTED>',
       'installationId': '<REDACTED>',
       'sessionId': '<REDACTED>',
       'executionEnvironment': 'CLI', 
       'pyversion': '3.7.6',
       'samcliVersion': '0.40.0'}
     }
 ]
}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Aborted!
```

# Telemetry disabled

```
 ./result-no-telemetry/bin/sam init --debug
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: ^C
Aborted!
```

**Comment by stefano-m** [comment]
Also note that the installation ID and telemetry options are saved in a configuration file (although the env var takes precedence):

`cat ~/.aws-sam/metadata.json`

```json
{
    "telemetryEnabled": true,
    "installationId": "<REDACTED>"
}
```

**Comment by andreabedini** [comment]
LGTM

**Comment by dhl** [comment]
This is awesome. Thanks for this PR!

**Review by dhl — APPROVED** [review]

**Comment by stefano-m** [comment]
Anything else you need from me to get this merged, please do let me know.

Thanks for the awesome work you are doing on NixOS!

**Comment by dhl** [comment]
Hey @stefano-m, sorry for the delay in getting back to you.

Personally, I am okay with disabling telemetry by default (and thanks for being privacy-conscious!). I gave this a bit more thought and felt that by generating a wrapper around `sam`, it actually removes user's ability to opt into using telemetry, if they need that for whatever reason.

Can we generate the wrapper conditionally, so user's can actually override the default and opt in?

**Comment by stefano-m** [comment]
@dhl I can see your point, although I fail to understand why someone wanted to use telemetry (`aws-sam-cli` even disable it in their tests).

Note that for example `powershell` disables telemetry in the wrapper 
https://github.com/NixOS/nixpkgs/blob/a0ef7ad1d60ee28dced446b5c6dfa1895036468f/pkgs/shells/powershell/default.nix#L34

(Disclosure: I somewhat contributed to those setting with #74516)

If you still prefer to have the option to enable telemetry, I would propose instead that we generate the wrapper with telemetry disabled by default and add a conditional parameter to the derivation to **explicitly** enable telemetry.

Would you be OK with that?

Thanks

**Comment by stefano-m** [comment]
I have just re-read your comment and actually you say

> Can we generate the wrapper conditionally, so user's can actually override the default and opt in?

:man_facepalming: ...

So, yes... I will do that. :bowing_man:

**Comment by dhl** [comment]
@GrahamcOfBorg build aws-sam-cli

**Review by dhl — APPROVED** [review]

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
