### PR TITLE
update ds4drv and dependencies

### PR DESCRIPTION
**Pull request by mbakke**
###### Motivation for this change

Previous version did not work.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Bluetooth support not tested.

### CODE REVIEW

**Comment by mbakke** [comment]
Travis times out due to missing pyside cache. I've run `nox-review` locally and had to disable `pyudev` tests due to the udev ctypes hack and missing `gccxml`. Using `LD_LIBRARY_PATH` will probably remove the need for the pyudev ctypes hack, not sure which is preferrable.

Reverse dependencies passes at least (though evemu did not build on master either) and the current PR Works For Me™.

**Comment by kevincox** [comment]
@mbakke Do you feel that this is ready to merge?

**Comment by mbakke** [comment]
Oh man, I had forgotten about this. I'll fix it up, but need to install Nix first!

**Comment by joachifm** [comment]
A quick glance suggests that ds4drv and pyudev are still relevant. Anybody up for picking them out?

**Pull request closed without merging**
