### PR TITLE
mercurial: 6.0.3 -> 6.1

### PR DESCRIPTION
**Pull request by techknowlogick**
###### Motivation for this change
hg 6.1 has been released

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On nixos x86_64, `tortoisehg` fails to build with:

```
running install tests
test: thg smoke test
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/build/runtime-nixbld'
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
This plugin does not support propagateSizeHints()
This plugin does not support raise()
thg help output was not captured. Seems like package is broken.
```

**Comment by techknowlogick** [comment]
@risicle thanks for reviewing this.

If anyone is also looking into the failure it seems as though the QT errors that are output are potentially a red-herring of sorts, and in fact it appears as though when using hg 6.1 that thg hangs

**Comment by pacien** [comment]
`tortoisehg` fails to start with an error pop-up saying that it's not
compatible with `mercurial` 6.1, making the smoke test fail as expected.

We need to wait for a new `tortoisehg` release, which should arrive soon-ish.

Upstream issue: https://foss.heptapod.net/mercurial/tortoisehg/thg/-/issues/5771

**Comment by techknowlogick** [comment]
Ah, thanks @pacien <3

**Comment by techknowlogick** [comment]
While we wait for a new release, I've added the patch that will allow hg6.1 to be used with thg

**Review by pacien — APPROVED** [review]
Diff looks good to me.

I'm not sure of why the build of the test package is reported as failing on
x86_64-linux. The logs indicate that no test has failed:
https://github.com/NixOS/nixpkgs/pull/162388/checks?check_run_id=5427046884

For aarch64-linux, the build of the main package is failing for the Rust part.
IIRC, Mercurial does not officially support that particular architecture.
However, Mercurial can still be packaged in pure Python. We should probably do
that for that system type.

**Review by pacien — CHANGES_REQUESTED** [review]
tortoisehg 6.1 has been released: https://foss.heptapod.net/mercurial/tortoisehg/thg/-/tags/6.1
It is officially compatible with Mercurial 6.1. The local patch can now be removed.

**Comment by techknowlogick** [comment]
Thanks @pacien, I've now made two commits, one with tortoisehg update, and another with hg update :)

**Review by lukegb — APPROVED** [review]

**Comment by mweinelt** [comment]
This update broke mercurial on aarch64-linux and blocks ~168 jobs on staging-next.

```
   Compiling hg-core v0.1.0 (/build/mercurial-6.1/rust/hg-core)
error[E0308]: mismatched types
   --> hg-core/src/lock.rs:150:44
    |
150 |             let result = libc::gethostname(buffer.as_mut_ptr(), BUFFER_SIZE);
    |                                            ^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

error[E0308]: mismatched types
   --> hg-core/src/lock.rs:154:38
    |
154 |             std::ffi::CStr::from_ptr(buffer.as_mut_ptr()).to_bytes()
    |                                      ^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*mut i8`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hg-core` due to 2 previous errors
error: Cargo failed. Working directory: 'rust/hg-cpython', command: ['cargo', 'rustc', '--release', '--no-default-features', '--features', 'python3', '--'], environment: {'SHELL': '/nix/store/5a50a0gjsznslppq3wk4bvyg9bmfj4l5-bash-5.1-p12/bin/bash', '_PYTHON_HOST_PLATFORM': 'linux-aarch64', 'NIX_BUILD_CORES': '4', 'configureFlags': '--prefix=/nix/store/6h59c3h0ixq6713yfm6ppm5z66iczn79-mercurial-6.1 ', 'PYTHONNOUSERSITE': '1', 'LANGUAGE': 'C', 'PREFIX': '/nix/store/6h59c3h0ixq6713yfm6ppm5z66iczn79-mercurial-6.1', 'shell': '/nix/store/5a50a0gjsznslppq3wk4bvyg9bmfj4l5-bash-5.1-p12/bin/bash', 'depsHostHost': '', 'MAKE_TERMOUT': 'true', 'PYTHONHASHSEED': '0', 'STRINGS': 'strings', 'src': '/nix/store/rv3q9fiigzxjhca3l0142wm9g3il3l5n-mercurial-6.1.tar.gz', 'depsTargetTarget': '', 'cargoDeps': '/nix/store/gqs8hgjjhc23fvamlm1rrjbwjm0bj366-mercurial-6.1-vendor.tar.gz', 'stdenv': '/nix/store/r8gjzsmqwhl53aprp3jqwjh5zqcmhdx7-stdenv-linux', 'PURE': '--rust', 'builder': '/nix/store/5a50a0gjsznslppq3wk4bvyg9bmfj4l5-bash-5.1-p12/bin/bash', 'NIX_CC_WRAPPER_TARGET_HOST_aarch64_unknown_linux_gnu': '1', 'PWD': '/build/mercurial-6.1', 'SOURCE_DATE_EPOCH': '1646149171', 'pname': 'mercurial', 'NIX_ENFORCE_NO_NATIVE': '1', 'MAKEOVERRIDES': '${-*-command-variables-*-}', 'CXX': 'g++', '_': '/nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10/bin/python3', 'TEMPDIR': '/build', 'system': 'aarch64-linux', 'TZ': 'UTC', '_PYTHON_SYSCONFIGDATA_NAME': '_sysconfigdata__linux_aarch64-linux-gnu', 'doInstallCheck': '1', 'HOME': '/homeless-shelter', 'NIX_BINTOOLS': '/nix/store/1ng1r1bqacxmmjfxnias56mib6ryim5v-binutils-wrapper-2.35.2', 'LANG': 'C.UTF-8', 'CARGO_HOME': '/build', 'depsTargetTargetPropagated': '', 'NIX_SSL_CERT_FILE': '/no-cert-file.crt', 'version': '6.1', 'outputs': 'out', 'NIX_STORE': '/nix/store', 'TMPDIR': '/build', 'makeFlags': 'PREFIX=$(out) PURE=--rust', 'LD': 'ld', 'NIX_ENFORCE_PURITY': '1', 'READELF': 'readelf', 'GETTEXTDATADIRS_FOR_BUILD': '/nix/store/zyhp3a6jr8vmlrdmmvim44l5fp2jl2nc-gettext-0.21/share/gettext', 'MFLAGS': '', 'cargoRoot': 'rust', 'doCheck': '', 'NIX_LOG_FD': '2', 'depsBuildBuild': '', 'disallowedReferences': '', 'MAKEFLAGS': ' -- PURE=--rust PREFIX=$$(out) SHELL=/nix/store/5a50a0gjsznslppq3wk4bvyg9bmfj4l5-bash-5.1-p12/bin/bash', 'PYTHONPATH': '/nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10/lib/python3.9/site-packages:/nix/store/8p0i2846pj4yv3hfr0q2rrrczxzwi4ik-python3.9-setuptools-57.2.0/lib/python3.9/site-packages:/nix/store/8dj1zppb8acb4i7j57nx3jxivxbb9qbi-python3.9-docutils-0.17.1/lib/python3.9/site-packages:/nix/store/9f42d75w5b5k2yf37308vx7af3y7n37d-python3.9-fb-re2-1.0.7/lib/python3.9/site-packages', 'TERM': 'xterm-256color', 'SIZE': 'size', 'propagatedNativeBuildInputs': '', 'strictDeps': '1', 'MAKE_TERMERR': 'true', 'lt_cv_deplibs_check_method': 'pass_all', 'AR': 'ar', 'AS': 'as', 'TEMP': '/build', 'SHLVL': '1', 'NIX_BUILD_TOP': '/build', 'NM': 'nm', 'postFixup': 'wrapPythonPrograms\n', 'MAKELEVEL': '1', 'NIX_CFLAGS_COMPILE': ' -frandom-seed=6h59c3h0ix -isystem /nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10/include', 'patches': '', 'postInstall': 'for i in $(cd $out/bin && ls); do\n  wrapProgram $out/bin/$i \\\n    $WRAP_TK\ndone\n\n# copy hgweb.cgi to allow use in apache\nmkdir -p $out/share/cgi-bin\ncp -v hgweb.cgi contrib/hgweb.wsgi $out/share/cgi-bin\nchmod u+x $out/share/cgi-bin/hgweb.cgi\n\ninstallShellCompletion --cmd hg \\\n  --bash contrib/bash_completion \\\n  --zsh contrib/zsh_completion\n', 'buildInputs': '/nix/store/8dj1zppb8acb4i7j57nx3jxivxbb9qbi-python3.9-docutils-0.17.1', 'SSL_CERT_FILE': '/no-cert-file.crt', 'depsBuildTarget': '', 'OBJCOPY': 'objcopy', 'DETERMINISTIC_BUILD': '1', 'out': '/nix/store/6h59c3h0ixq6713yfm6ppm5z66iczn79-mercurial-6.1', 'LC_ALL': 'C', 'STRIP': 'strip', 'XDG_DATA_DIRS': '/nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10/share:/nix/store/zyhp3a6jr8vmlrdmmvim44l5fp2jl2nc-gettext-0.21/share:/nix/store/s45pvw0nzynx96al7hm376rcpiyakzn7-cargo-1.58.1/share:/nix/store/xjg7jz3h70pj20rb3yxjl9c5p09laj5b-patchelf-0.14.3/share', 'TMP': '/build', 'OBJDUMP': 'objdump', 'PATH': '/nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10/bin:/nix/store/zyhp3a6jr8vmlrdmmvim44l5fp2jl2nc-gettext-0.21/bin:/nix/store/s45pvw0nzynx96al7hm376rcpiyakzn7-cargo-1.58.1/bin:/nix/store/l1aapnlrm78jlapmhbzvigf0xx8869rj-rustc-1.58.1/bin:/nix/store/xjg7jz3h70pj20rb3yxjl9c5p09laj5b-patchelf-0.14.3/bin:/nix/store/8wwqp5phmra2jwrm0j6mvr1kdi7s7g8v-gcc-wrapper-9.3.0/bin:/nix/store/qxxm10h05039397bm9syfjp3rx482ls8-gcc-9.3.0/bin:/nix/store/vb463r3prk233qick0vz4fxlzxw7ykhb-glibc-2.33-108-bin/bin:/nix/store/dsi0af36cc1gyic45rap7142zfw8902m-coreutils-9.0/bin:/nix/store/1ng1r1bqacxmmjfxnias56mib6ryim5v-binutils-wrapper-2.35.2/bin:/nix/store/0zrzna6lplz54sz845smr9b2am1x5gzh-binutils-2.35.2/bin:/nix/store/dsi0af36cc1gyic45rap7142zfw8902m-coreutils-9.0/bin:/nix/store/g0y8wb8bxc3pqlh69945vhg0ir4j8ynw-findutils-4.8.0/bin:/nix/store/rm6a522q3cf1ir3wv2932yib9xk3y69v-diffutils-3.8/bin:/nix/store/7v135rm7zpi9zcm16pw92jm8d4gagwxp-gnused-4.8/bin:/nix/store/cq45iizvdgikmsgjxi50kv24429m3qnr-gnugrep-3.7/bin:/nix/store/ax6fbah5mnlispnd57mz9psmnra3j9y5-gawk-5.1.1/bin:/nix/store/c2kil4vgc6bjg0apyhbqzwxxk2snbxf5-gnutar-1.34/bin:/nix/store/yamcsh745r6w4vmadw9wizn3l5xvcfxv-gzip-1.11/bin:/nix/store/yydbmvc2n8s8l8hhag3zf075zlmgj8ki-bzip2-1.0.6.0.2-bin/bin:/nix/store/xi93p6g8jrm4s5ixbiczn424n83kibi4-gnumake-4.3/bin:/nix/store/5a50a0gjsznslppq3wk4bvyg9bmfj4l5-bash-5.1-p12/bin:/nix/store/pg52gp2xfhxwinpxs1qrs8j313jmdg9h-patch-2.7.6/bin:/nix/store/6ngvh4pjr9raz7kcqaijnz1pssk2i4rx-xz-5.2.5-bin/bin', 'propagatedBuildInputs': '/nix/store/9f42d75w5b5k2yf37308vx7af3y7n37d-python3.9-fb-re2-1.0.7 /nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10', 'CC': 'gcc', 'NIX_CC': '/nix/store/8wwqp5phmra2jwrm0j6mvr1kdi7s7g8v-gcc-wrapper-9.3.0', 'NIX_BINTOOLS_WRAPPER_TARGET_HOST_aarch64_unknown_linux_gnu': '1', 'depsBuildTargetPropagated': '', 'depsBuildBuildPropagated': '', 'NIX_INDENT_MAKE': '1', 'CONFIG_SHELL': '/nix/store/5a50a0gjsznslppq3wk4bvyg9bmfj4l5-bash-5.1-p12/bin/bash', 'RANLIB': 'ranlib', 'NIX_HARDENING_ENABLE': 'fortify stackprotector pic strictoverflow format relro bindnow', 'OLDPWD': '/build', 'NIX_LDFLAGS': '-rpath /nix/store/6h59c3h0ixq6713yfm6ppm5z66iczn79-mercurial-6.1/lib  -L/nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10/lib', 'nativeBuildInputs': '/nix/store/hfjq29qh33sc17yf8yix2nzixhns2l6b-python3-3.9.10 /nix/store/8lan44n7vfimlm59ilf02jb3axnd2b38-hook /nix/store/higz0qpbrg7g7vjfnxpcd88vks298rbk-hook /nix/store/78sqh0rz602jgdgbzvnl2dwns009bbd6-python-remove-tests-dir-hook /nix/store/8p0i2846pj4yv3hfr0q2rrrczxzwi4ik-python3.9-setuptools-57.2.0 /nix/store/skafif2k3yfvys05jlpfhm11i1f17v47-python-catch-conflicts-hook /nix/store/s8rsh2lxk3fywfy3h9j5diahgsz2x5cx-python-remove-bin-bytecode-hook /nix/store/lfy802y51yh6amy8j04nnhzjnmwr9vdl-python-imports-check-hook.sh /nix/store/ax5mksjpx8n27m67wvv07rnhw314casg-python-namespaces-hook.sh /nix/store/isb1xhmlmfjq1kk9w06r7jlr3y21vdb7-hook /nix/store/zyhp3a6jr8vmlrdmmvim44l5fp2jl2nc-gettext-0.21 /nix/store/ilwc2dpy4qngfh88mw8wpmsrk2v7577k-install-shell-files /nix/store/rwl3815p0h0s9a3a1bfp910pydspjrgr-cargo-setup-hook.sh /nix/store/s45pvw0nzynx96al7hm376rcpiyakzn7-cargo-1.58.1 /nix/store/l1aapnlrm78jlapmhbzvigf0xx8869rj-rustc-1.58.1', 'name': 'mercurial-6.1', 'depsHostHostPropagated': '', 'PLAT': 'linux-aarch64'}
make: *** [Makefile:69: build] Error 1
builder for '/nix/store/iaad47hy1rbs3vp93jyjqzr1lwjqjk1g-mercurial-6.1.drv' failed with exit code 2
```

**Pull request merged**
