### PR TITLE
crystal: 0.20.5 -> 0.21.0

### PR DESCRIPTION
**Pull request by sifmelcara**
###### Motivation for this change
Update the package.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
The linux build fails for me, not sure what's going wrong https://gist.github.com/LnL7/5a7dcf71e9eb6714c15baf37a7e2892a

**Comment by sifmelcara** [comment]
PR updated to rebase against NixOS/master.
@LnL7 Looks like your build failure is caused by insufficient memory, since crystal need ~3GB memory to build, could you try again and see if it is caused by insufficient memory? thank you!

**Comment by LnL7** [comment]
I have tried to build it a bunch of times and even rebooted once. My build machine has 32G so I would be surprised if it's actually running out of memory.

**Comment by LnL7** [comment]
I got it to pass now, but I'm not sure how stable this will be on hydra.

**Comment by sifmelcara** [comment]
Unfortunately I cannot reproduce the issue, I will report to upstream if I find a machine which can reproduce this issue.

**Comment by Mic92** [comment]
I can build `crystal` with 12GB of RAM, while still desktop applications like chrome. I have also a swap configured, but it was not really used.

**Comment by LnL7** [comment]
I don't have any swap configured, but I've never had issues before including a previous version of crystal.
Either way this is not really an issue if it builds fine on hydra.

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
