### PR TITLE
davinci-resolve: resolving payload request error

### PR DESCRIPTION
**Pull request by jshcmpbll**
###### Description of changes

The payload request form for `davinci-resolve` was changed including a required field for `street` address.

I chose the Chamber of Commerce in Utrecht as the street address since the [NixOS Foundation is registered as a non-profit org there](https://github.com/NixOS/foundation#about-the-foundation)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jshcmpbll** [comment]
closes #242091

**Comment by stelcodes** [comment]
Built this locally and I can confirm that it fixes the download issue 🥳

**Review by jocampbell-exelixis — APPROVED** [review]
LGTM :sweat_smile:

**Comment by LiGoldragon** [comment]
I got:
```
error: hash mismatch in fixed-output derivation '/nix/store/khwq8hl898id8j791blidj053nf1p031-davinci-resolve-src.zip.drv':
         specified: sha256-yUKT1x5LrzdGLDZjZDeTvNgRAzeR+rn18AGY5Mn+5As=
            got:    sha256-u9SD814h/ULy0vXxChZUnko2xZdFCelR9u7UImV6MYo=
```

**Comment by LiGoldragon** [comment]
Fixing the hash returned the original "malformed input" http error.
Will do manual download if I have to and report if I do.

**Comment by sefodopo** [comment]
> I got:
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/khwq8hl898id8j791blidj053nf1p031-davinci-resolve-src.zip.drv':
>          specified: sha256-yUKT1x5LrzdGLDZjZDeTvNgRAzeR+rn18AGY5Mn+5As=
>             got:    sha256-u9SD814h/ULy0vXxChZUnko2xZdFCelR9u7UImV6MYo=
> ```

I can confirm I get the same thing. However, when I change the hash to match the new hash I get the following:

```
error: builder for '/nix/store/xwcz8jyfw0bbb6mbnghcqdjjv596r67g-davinci-resolve-18.1.4.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/blcsw906jgisnksdpa5299a55s3agzka-davinci-resolve-src.zip
       > [/nix/store/blcsw906jgisnksdpa5299a55s3agzka-davinci-resolve-src.zip]
       >   End-of-central-directory signature not found.  Either this file is not
       >   a zipfile, or it constitutes one disk of a multi-part archive.  In the
       >   latter case the central directory and zipfile comment will be found on
       >   the last disk(s) of this archive.
       > unzip:  cannot find zipfile directory in one of /nix/store/blcsw906jgisnksdpa5299a55s3agzka-davinci-resolve-src.zip or
       >         /nix/store/blcsw906jgisnksdpa5299a55s3agzka-davinci-resolve-src.zip.zip, and cannot find /nix/store/blcsw906jgisnksdpa5299a55s3agzka-davinci-resolve-src.zip.ZIP, period.
       > do not know how to unpack source archive /nix/store/blcsw906jgisnksdpa5299a55s3agzka-davinci-resolve-src.zip
       For full logs, run 'nix log /nix/store/xwcz8jyfw0bbb6mbnghcqdjjv596r67g-davinci-resolve-18.1.4.drv'.
error: 1 dependencies of derivation '/nix/store/nizsx4zicz8ph7kds33kz4n2mnhjibd9-davinci-resolve-usr-target.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xc5s44xpwwa3hyfwf261j8h5ma4frpj0-davinci-wrapper.drv' failed to build
error: 1 dependencies of derivation '/nix/store/smn690w10mlkhmshil761xk6gfv1fbx4-davinci-resolve-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qb9sx94480lf5nrg73j1zvi1s6831dan-davinci-resolve-bwrap.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wkai5aa4sw6wjw1qykskv6g9fkk0gd5s-davinci-resolve.drv' failed to build
```

Digging deeper, I find that the zip file in question is not a zip file, but instead a html forbidden page:
```html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

So it would appear that cloudflare is blocking the request somehow.

**Comment by LiGoldragon** [comment]
I'm happy to host the file somewhere, or perhaps this is a good use-case for IPFS url? Those guys are living in the 19th century!

**Comment by davidak** [comment]
>I chose the Chamber of Commerce in Utrecht as the street address since the [NixOS Foundation is registered as a non-profit org there](https://github.com/NixOS/foundation#about-the-foundation).

The foundation has an address. Any reason not to use that? Could they get into trouble?

https://github.com/NixOS/foundation/blob/master/impressum.md

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 242751` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 242751` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by jshcmpbll** [comment]
Completed via #246074.

**Pull request closed without merging**
