### PR TITLE
github-runner: 2.317.0 -> 2.319.0

### LINKED ISSUE #332041: Update request: github-runner: 2.317.0 -> 2.318.0
- Package name: github-runner
- Latest released version: 2.318.0

- Current version on the unstable channel: 2.317.0
- Current version on the stable/release channel: 2.317.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers** @veehaitch @newam @kfollesdal @aanderse @zimbatm

-----

Note for maintainers: Please tag this issue in your PR.

I got the package updated but a ton of tests fail.  Hopefully there's a .net expert here that can help out.

Feel free to use any part of this in a PR: https://github.com/newAM/nixpkgs/commit/6e83ac1b0d4119139e6b89b342959d4c0c5da5f1

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by azahi**
## Description of changes

https://github.com/actions/runner/releases/tag/v2.319.0
https://github.com/actions/runner/compare/v2.317.0...v2.319.0

Closes: #332041

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by azahi** [comment]
SDK version wasn't changed: https://github.com/actions/runner/blob/v2.319.0/src/global.json (assuming this is the correct place to check)

**Review by veehaitch — APPROVED** [review]
Good things come to those who wait. Thanks!

**Review by newAM — APPROVED** [review]
@NixOS/nixpkgs-merge-bot merge

**Comment by arianvp** [comment]
`hash` in `deps.nix` is not supported on 24.05. This means all  the backport PRS from now on will fail to apply. Should we maybe consider `s/hash/sha256` again? Otherwise backport PRs need to be done manually from now on. And given that `github-runners` is a time-sensitive package (It will just break if you don't update quickly enough) that might add too much extra burden.

**Comment by zimbatm** [comment]
yes, we should revert to sha256 for this release.

**Comment by newAM** [comment]
`hash` is now supported in 24.05 (as of a few days ago) we should update the 24.05 branch to `hash`, not the other way around.

**Pull request merged**
