### PR TITLE
neovide: init at ba42855

### PR DESCRIPTION
**Pull request by ck3d**
###### Motivation for this change
Package neovide which fixes following issues

- #111972
- https://github.com/Kethku/neovide/issues/612

Sorry, but I did not try to get latest release 0.7.0 running, since it took me hours to get this version building.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ymatsiuk** [comment]
Thanks! Compiling it now 🙂 

In order to comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) the commit message must be something like: `neovide: init at ba42855`

**Comment by ymatsiuk** [comment]
I'm hitting [this bug](https://github.com/Kethku/neovide/issues/459) under sway 🤷🏻‍♂️ 

```
❯ neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by teto** [comment]
very cool that you tried ! I had tried too but I kept running into runtime issues and reading the tracker/gitter, seems like I was not alone. Sadly seems like this hit me again.
```
(ins)➜ results/neovide/bin/neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
.cache/nixpkgs-review/pr-122998-2 via ❄️  IMPURE (review-shell) took 11s 
(ins)❯ sysctl -w dev.i915.perf_stream_paranoid=0
sysctl: permission denied on key "dev.i915.perf_stream_paranoid"
.cache/nixpkgs-review/pr-122998-2 via ❄️  IMPURE (review-shell) 
(ins)❯ sudo sysctl -w dev.i915.perf_stream_paranoid=0
[sudo] password for teto: 
dev.i915.perf_stream_paranoid = 0
.cache/nixpkgs-review/pr-122998-2 via ❄️  IMPURE (review-shell) 
(ins)➜ results/neovide/bin/neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ck3d** [comment]
I could run this neovide successfully on following three NixOS 20.09 machines:
```
amdgpu1$ vulkaninfo | grep GPU
                GPU id  : 0 (AMD RADV POLARIS10 (LLVM 9.0.1))
```
```
amdgpu2$ vulkaninfo | grep GPU
                GPU id  : 0 (AMD RADV PITCAIRN (LLVM 9.0.1))
```
```
nvidia$ vulkaninfo | grep GPU
                GPU id  : 0 (Quadro M12000)
```

**Comment by ymatsiuk** [comment]
It doesn't work for me on: 
```bash
❯ vulkaninfo | grep GPU
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
		GPU id = 0 (Intel(R) Xe Graphics (TGL GT2))
		GPU id = 1 (llvmpipe (LLVM 11.1.0, 256 bits))
```

**Comment by teto** [comment]
I am happy to merge this even if neovide doesn't work on my machine (I know it's a fiddly software). I wonder if it wouldn't be more readable to have the skia part in its own file ?
Fails on my system with integrated chipset
```
➜ vulkaninfo | grep GPU                                                                                                                                                                       ~
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
		GPU id = 0 (llvmpipe (LLVM 11.1.0, 256 bits))
		GPU id = 1 (Intel(R) UHD Graphics 630 (CFL GT2))
		GPU id = 0 (llvmpipe (LLVM 11.1.0, 256 bits))
		GPU id = 1 (Intel(R) UHD Graphics 630 (CFL GT2))
		GPU id = 0 (llvmpipe (LLVM 11.1.0, 256 bits))
		GPU id = 1 (Intel(R) UHD Graphics 630 (CFL GT2))
		GPU id = 0 (llvmpipe (LLVM 11.1.0, 256 bits))
		GPU id = 1 (Intel(R) UHD Graphics 630 (CFL GT2))
GPU id : 0 (llvmpipe (LLVM 11.1.0, 256 bits)):
GPU id : 1 (Intel(R) UHD Graphics 630 (CFL GT2)):
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
GPU0:
GPU1:
	deviceType     = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
```
I think next versions will work on opengl and may be more tolerant. I can test this with a discrete GPU next week.

**Comment by ck3d** [comment]
Thanks for the hint. I separated the skia dependencies.

**Comment by teto** [comment]
Is it possible to set it up as a plain package ? like in https://github.com/teto/home/blob/master/nixpkgs/overlays/pkgs/neovide/skia.nix (something I copied from someone else)

**Comment by ck3d** [comment]
I did not find a way to pass pre-compiled packages to the Rust package skia-bindings. Starting point is https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build.rs#L79

**Comment by teto** [comment]
ok let's get this in, it can be improved later.

**Comment by bnjmnt4n** [comment]
Hi, just wanted to note that building this on nixos-unstable (https://github.com/NixOS/nixpkgs/commit/ea7d4aa9b8225abd6147339f0d56675d6f1f0fd1) failed for me with the following error while building skia-bindings. Wondered if anyone else has encountered this, or should I open a separate issue for this?

```
error: failed to run custom build command for `skia-bindings v0.35.1`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/skia-bindings-9f2d67ad80a2db44/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SKIA_OFFLINE_SOURCE_DIR
  STARTING OFFLINE BUILD
  cargo:rerun-if-env-changed=SKIA_OFFLINE_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_OFFLINE_GN_COMMAND
  Probing 'python'
  Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_use_gl=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_vulkan=true skia_enable_spirv_validation=false skia_enable_skshaper=true skia_use_icu=true skia_use_system_icu=false skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_harfbuzz=false skia_use_sfntly=false skia_enable_skparagraph=true skia_use_expat=true skia_use_system_expat=false
  Done. Made 76 targets from 36 files in 2261ms
  ninja: Entering directory `/build/source/target/x86_64-unknown-linux-gnu/release/build/skia-bindings-c6613dc34168c33d/out/skia'

  --- stderr
  ninja: fatal: posix_spawn: No such file or directory
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', /build/neovide-20210515-vendor.tar.gz/skia-bindings/build_support/skia.rs:603:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: builder for '/nix/store/2pf74df0x5z47gd1497xgl3j1krl8wv9-neovide-20210515.drv' failed with exit code 101;
```

**Comment by ck3d** [comment]
I used the same revision of nixpkgs but got a different derivation:
```
nix-instantiate -A neovide
/nix/store/4s7wmp7hmmd0i7qjw56zbvbg0l1jgdna-neovide-20210515.drv
```
I could successfully build this derivation.

**Comment by bnjmnt4n** [comment]
Ah, for some reason, running `nix-shell -p neovide` was giving that error, but including this in my NixOS configuration built successfully, and I'm now seeing an identical error to the one mentioned above:

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Thanks for the help, and I'll follow along to the other issue created.

**Comment by martinetd** [comment]
@bnjmnt4n that `ninja: fatal: posix_spawn: No such file or directory` is probably a sandboxing problem, you have no /bin/sh in your build environment (or well, that's what I have... execsnoop --fails ♥)
looks like #124372 / #124215 which is now fixed if you upgrade

**Pull request merged**
