### PR TITLE
borgbackup: 1.1.6 -> 1.1.7

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
> Ran 0 tests in 0.000s

Are there no tests?

**Comment by dotlambda** [comment]
> Are there no tests?

Yes, there are. However, it's not worth the effort to make them run as we have a NixOS test.

**Comment by xeji** [comment]
@GrahamcOfBorg test borgbackup

**Comment by dotlambda** [comment]
Well that's strange. Totally works for me :/

@GrahamcOfBorg test borgbackup

**Comment by xeji** [comment]
Might be a non-deterministic test failure. Let's look at that another time :smile:

**Pull request merged**
