### PR TITLE
nixos/upower: remove package option

### PR DESCRIPTION
**Pull request by worldofpeace**
Haven't had another upower package in nixpkgs since 2a2cb8354ec

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
People can still set their own upower package though. While I dislike having such options when it doesn't make sense, I don't think we can just remove them like that.

**Comment by worldofpeace** [comment]
True, but are you saying if something was justified 5 years ago https://github.com/NixOS/nixpkgs/commit/df95a8cc2f92 and causes rebuilds should have this option?

**Comment by aanderse** [comment]
If you're going to remove an option you should use `mkRemovedOptionModule` too.

**Comment by worldofpeace** [comment]
> mkRemovedOptionModule

Thanks, was wondering if there was something like this.

**Comment by bb010g** [comment]
Aren't package options valuable for users wanting to use non-standard versions in modules but not everywhere, like with a full package override?

**Comment by worldofpeace** [comment]
No proper response here. Closing

**Pull request closed without merging**
