### PR TITLE
Linux kernel updates 2022-06-10

### PR DESCRIPTION
**Pull request by amarshall**
###### Description of changes

I ran:

```
./pkgs/os-specific/linux/kernel/update.sh
nix-build -A linux_4_14.tests -A linux_4_14_hardened.tests -A linux_4_19.tests -A linux_4_19_hardened.tests -A linux_5_10.tests -A linux_5_10_hardened.tests -A linux_5_15.tests -A linux_5_15_hardened.tests -A linux_5_17.tests -A linux_5_17_hardened.tests -A linux_5_18.tests -A linux_5_18_hardened.tests
```

Unsure if there’s anything else that should be run or tested.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Thanks! Going to test and merge.

Next week I can take care of this myself again, was on vacation last week :)

**Review by Ma27 — APPROVED** [review]

**Comment by mweinelt** [comment]
Backports are not arriving in release-21.11 anymore since 2022-05-26.

**Comment by Ma27** [comment]
Yep, later today.

**Comment by Ma27** [comment]
@mweinelt sorry, slightly delayed, but here you go: #177863

**Comment by mweinelt** [comment]
Thanks, I'm somewhat offline right now, can give feedback later tonight if it's needed.

**Pull request merged**
