### PR TITLE
Revert "lib/types: remove loaOf"

### LINKED ISSUE #208123: Newly released unstable small breaks stable nixops
### Steps To Reproduce
1. build `nixos-unstable-small release nixos-23.05pre438170.57dbff4228a`

### Build log
```console
greaka@greaka-arch-desktop ~ % nixops deploy
/nix/store/av5h6kal9lbvpvhvdbj23qqvczaijpf7-python2.7-apache-libcloud-2.8.3/lib/python2.7/site-packages/libcloud/common/google.py:93: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the
next release.
  from cryptography.hazmat.backends import default_backend
trace: warning: The extraArgs argument to eval-config.nix is deprecated. Please set config._module.args instead.
building all machine configurations...
trace: warning: The extraArgs argument to eval-config.nix is deprecated. Please set config._module.args instead.
error: undefined variable 'loaOf' at /nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/share/nix/nixops/gce.nix:405:26
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1003, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/av1ccsx153bhxx97gqnwx3kjw1scdbdl-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 671, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
1 greaka@greaka-arch-desktop ~ %                                                                                                                   :(
```

### Additional context
I updated nixpkgs and now nixops does not work anymore. I don't even use gce, so I'm baffled why it's failing. `nixos-23.05pre437680.aac1f0b25e6` was still working. In both cases I used the same nixops version 1.7. My config did not change and can be found at https://github.com/greaka/ops

### Metadata

```console
greaka@greaka-arch-desktop /git/ops (git)-[master] % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixpkgs-23.05pre438170.57dbff4228a"`
 - channels(greaka): `"nixpkgs-23.05pre438170.57dbff4228a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

This reverts #206809 commit https://github.com/NixOS/nixpkgs/commit/c8c538f2ab2432f2dd1eb637657c1bf5b54a147f.

Reasons:
 - removal did not follow a deprecation process
 - and it hurts nixops 1.7 users: #208123

Closes #208123

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
> removal did not follow a deprecation process

Would like to take this opportunity to ask what is the deprecation process. I searched for "deprecation" in the nixpkgs documentation and did not find it.

**Comment by roberth** [comment]
Good question. I don't think it has been formalized, but a good deprecation process is:
1. introduce the alternative
2. when the alternative is available in all supported versions, add a warning explaining the migration
3. when the warning has been applied in all supported versions, turn the warning into an error, removing the implementation
4. never, or after years, remove the error

**Comment by roberth** [comment]
Here's an example of automating (2): #208168

**Comment by tjni** [comment]
This is a reasonable deprecation process, but I can also see others. Thanks for the pointers on your approach, however. I appreciate it.

**Comment by roberth** [comment]
It usually is, but perhaps if the current thing is horribly broken, we may want to skip to (2) and backport it instead of waiting, but it has to be horrible to warrant that IMO. There are probably other reasons to do it differently that I'm not thinking of.

**Comment by tjni** [comment]
Thanks for fixing this!

**Pull request merged**
