### PR TITLE
Major update of various JetBrains IDEs

### PR DESCRIPTION
**Pull request by matklad**
###### Motivation for this change

Routine update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS (only checked idea community)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build jetbrains.clion jetbrains.goland jetbrains.idea-community jetbrains.idea-ultimate jetbrains.phpstorm jetbrains.pycharm-community jetbrains.pycharm-professional jetbrains.webstorm

**Comment by matklad** [comment]
Verified that CLion and its bundled debuggers work as well!

**Comment by matklad** [comment]
cc @Mic92 because you've merged a couple of other jetbrains updates of mine :-)

**Comment by Mic92** [comment]
Goland fails to build for me.

**Comment by Mic92** [comment]
```console
$ nix-shell -p goland
...
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/lib/jexec
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/rmid
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/keytool
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/unpack200
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/orbd
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/policytool
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/jjs
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/rmiregistry
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/servertool
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/java
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/tnameserv
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/jre64/bin/pack200
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/lib/libpty/linux/x86/libpty.so
shrinking /nix/store/d8a22p9a91ml2xaizjnfah48afg3f7pw-goland-2018.1/goland-2018.1/lib/libpty/linux/x86_64/libpty.so
missing filename
builder for '/nix/store/d1w1x2i25zdivjbbcjcb0i603qmxxx9w-goland-2018.1.drv' failed with exit code 1
error: build of '/nix/store/d1w1x2i25zdivjbbcjcb0i603qmxxx9w-goland-2018.1.drv' failed
```

**Comment by matklad** [comment]
Thanks @Mic92! Updated the postFixUp!

**Comment by Mic92** [comment]
backported to 18.03

**Comment by Infinisil** [comment]
Why is this major update backported? Aren't releases only supposed to get bug and security fixes?

**Comment by Mic92** [comment]
Jetbrains delete old releases and nixos does not cache old tarballs because of the license

**Comment by Infinisil** [comment]
Oh I see :/

**Comment by matklad** [comment]
@Infinisil also, given that JetBrains makes major releases somewhat more often than NixOS (three times per year), it may make sense to do backports to current stable to make these latest versions actually usable on nixos without a hassle. Using

**Comment by matklad** [comment]
... using something like overlays to get latest IntelliJ idea on stable NixOS is not fun (I've tried it, and eventually decided that it's just easier for me personally to send a PR to NixOS once in a while :-) ). Using older IntelliJ is not fun either, because the ides themselves get a ton of updates in major versions, and because authors of third-party plugins often support only the latest release.

**Pull request merged**
