### PR TITLE
buf: 0.43.2 -> 0.44.0

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

Bump buf to `0.44.0`

@raboof

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 130091` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>buf</li>
  </ul>
</details>

**Review by otavio — APPROVED** [review]

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130091` at 852af2e8 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>buf</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/tools/buf/default.nix:22:5:
```
   |
22 |     ./skip_test_requiring_network.patch
   |     ^
```
</li>
  </ul>
</details>

**Review by raboof — APPROVED** [review]
tested on an external project, :+1:

**Comment by raboof** [comment]
> * warning: [missing-patch-comment](https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md)
>   Consider adding a comment explaining the purpose of this patch on the line preceeding.
>   Near pkgs/development/tools/buf/default.nix:22:5:
>   ```
>      |
>   22 |     ./skip_test_requiring_network.patch
>      |     ^
>   ```

Submitted #130102

**Pull request merged**
