### PR TITLE
neovim: bundle treesitter parser for wrapper

### PR DESCRIPTION
**Pull request by ck3d**
## Description of changes

This PR fixes two issues with the bundled treesitter parsers (introduced in #227159):

1. The parsers are outdated and fail with latest nvim-treesitter plugin. (e.g. release date of tree-sitter-c is August 2022)
2. The parsers are already defined in vimPlugins.
3. Changing the parsers causes a rebuild of neovim-unwrapped.
4. Parsers are not needed to build neovim-unwrapped.
5. In case of problems with bundled the parser, I did not expect, a parser was bundled with neovim-unwrapped

This PR moves the parsers from `neovim-unwrapped` derivation to the `neovim` (wrapped) and reuses the parsers in `vimPlugins`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
Neovim must embed a few core parsers, vimdoc etc. When you run an unwrapped neovim, it must by design be able to find the parsers selected for that version of neovim so 4/ is wrong (making 3/ irrelevant). 

> The parsers are outdated and fail with latest nvim-treesitter plugin.

you dont need nvim-treesitter to use tree-sitter with neovims so this eludes me.

> The parsers are already defined in vimPlugins.

these are not the same versions I think: in vimPlugins you find the versions referenced by nvim-treesitter while neovim-unwrapped uses the version from the neovim release.

I think your problem comes from a wrong setup of your treesitter grammars: you must be careful about how you setup your runtimepath such that nvim-treesitter grammars override both the queries and the libraries. I dont like how it's done, I dont think anyone does but this is a neovim experimental feature and people are working towards the versioning of grammar/queries (I hope xD)

**Comment by ck3d** [comment]
My setup is not to complex:
1. Start neovim with enabled highlighter of plugin nvim-treesitter
2. open a c file and then you see lua errors

Finding the issue of an outdated tree-sitter-c parsers, caused some time.

I think the existing design has some flaws:
1. Do not bundle the same package more than once
2. For a wrapped derivation, do not depend on a package, which is not needed during compile time.

**Comment by teto** [comment]
that's because nvim-treesitter brings more recent queries than the grammars installed by neovim-unwrapped so if you use nvim-treesitter, you must also install the grammars specified by nvim-treesitter that match the queries else you use the stable grammars with unstable queries, which results in the errors you see.
Treesitter support is experimental, we should not deteriorate the stable package for the sake of advanced users.

Are you sure you need nvim-treesitter anyway ? the goal for it is to become a lspconfig-like, aka just a list of grammars without any code. You should be able to have a working setup with neovim unstable. If you insist on keeping nvim-treesitter, install up-to-date grammars (either via `:TSInstall` or           via nix with `pkgs.vimPlugins.nvim-treesitter.grammarPlugins.FILETYPE`)/

**Comment by ck3d** [comment]
Thanks for your explanation regarding nvim-treesitter. I could fix the issue on my side.

I think the current solution of bundled parsers has a lot of downsides, as described in the description of this PR.

**Comment by teto** [comment]
Looking at the downsides you mention

> The parsers are outdated and fail with latest nvim-treesitter plugin. (e.g. release date of tree-sitter-c is August 2022)

When you are a software at version X, you dont expect it to use version Y, it's your choice.

> The parsers are already defined in vimPlugins.

those are at a different version than the release, I dont see this as a downside: you have the possibility to install more recent grammars

> Changing the parsers causes a rebuild of neovim-unwrapped.

No it's not you can reference the grammars as neovim plugins and they are installed by the wrapper. 
The thing to look at is to not mismatch queries and grammars. If you use nvim-treesitter, you have to override the default grammars. Maybe that's something we could add to nix but it's more a defect of the plugin. Anyway there is no good solution with treesitter at the moment.

You can reference different versions of the treesitter grammars via: 
```
          (grammarToPlugin pkgs.tree-sitter-grammars.tree-sitter-html) # for devdocs
          pkgs.vimPlugins.nvim-treesitter.grammarPlugins.org
```

> Parsers are not needed to build neovim-unwrapped.

They are, that's how the core neovim developers intended it to be. It helps troubleshooting issues and so on. I think nix users should enjoy the upstream experience using neovim-unwrapped, rather than a "nix" flavor.

**Comment by ck3d** [comment]
Neovim bundles other versions than defined in nixpkgs, see:
https://github.com/neovim/neovim/blob/102a72a21e2b5177516d2d3c44bd464e9b363bb9/cmake.deps/deps.txt#L44

This list has been update upstream, but not in nixpkgs. Our approach is error prone and obviously difficult to maintain.

If you look at the list, you will many more packages, that are pinned, but not on our side. But thus choosing only some tree-sitter parsers are a random choice.

**Comment by teto** [comment]
but you are referencing the development version of neovim ?!
and even then should be picked up by the flake see https://github.com/neovim/neovim/blob/master/contrib/flake.nix.
If it's not the case let's fix the flake. Please dont submit a PR to neovim/neovim though, I've convened with other core neovim contributors to move the flake to https://github.com/nix-community/neovim-nightly-overlay since nix PRs are unrelated to neovim PRs. Happy to have anyone take that over though.
Whatever grammar you use, installing nvim-treesitter will pollute your queries.
@mrcjkb is doing an awesomework to have per grammar install in https://github.com/nvim-neorocks/rocks.nvim/ so please keep an eye on that.

**Comment by ck3d** [comment]
It seems neovim developer solved their problem partly in nixpkgs, but they do not care about the package in nixpkgs.
I still think, my recommended way is easier for the maintainer and the user.

What is your recommendation?

**Comment by teto** [comment]
What are you trying to achieve and why do you need nvim-treesitter in the first place ? 
There is likely several solutions available so knowing your goal helps. 
Btw, I was told that the "main" (experimental) branch of nvim-treesitter stopped overriding queries by default.

**Comment by teto** [comment]
closing this to avoid it being inadventertly merged
nvim-treesitter will stop overriding the default queries in the near future and as nvim-treesitter utilities have been upstreamed, plugins will rely less on it anyway, see for instance https://github.com/nvim-orgmode/orgmode/issues/567
So long term the problem should disappear. 
Short term the solutions are mentioned here and in the linked issues, what we could do instead (and we should probably) is improve the documentation around neovim+treesitter in nixpkgs. PRs welcome.

**Comment by ck3d** [comment]
We still have the problem of outdated bundled treesitter parsers.

**Comment by mrcjkb** [comment]
> We still have the problem of outdated bundled treesitter parsers.

I don't see that as a problem. See [this comment](https://github.com/NixOS/nixpkgs/pull/291678#issuecomment-1965495371):

> you must be careful about how you setup your runtimepath such that nvim-treesitter grammars override both the queries and the libraries

nvim-treesitter is a plugin. How neovim-unwrapped is built shouldn't depend on a plugin.

**Pull request closed without merging**
