### PR TITLE
pkgs/by-name: `testVersion` -> `versionCheckHook` where applicable

### PR DESCRIPTION
**Pull request by getchoo**
## Description of changes

Follow up on #320266

This should help

- Simplify expressions
- Reduce (some) repition/workarounds
- Improve automated testing by making these checks a requirement to
  build
- Maintain consistency between which of these version check
  implementations are used across pkgs/by-name
- Provide more real-world examples of this newly added hook
- Avoid https://github.com/NixOS/nixpkgs/issues/312345 in many places

CC @doronbehar

---

I believe all occurrences of `testVersion` have been either replaced or given a TODO comment, with the exception of
```
clang-tidy-sarif
clippy-sarif
hadolint-sarif
hello
sarif-fmt
shellcheck-sarif
```

The sarif packages have been taken care of in #327451, #327452, #327454, #327455, and #327456 earlier today. `hello` will retain it's use of `testVersion` to serve as an example (as I believe this was the intention, given it was already there)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Two issues I see:
* This gets executed in the build environment rather than a separate test eevironment.
* This basically breaks cross-compilation unless you also have binfmt set up.

**Comment by getchoo** [comment]
> This gets executed in the build environment rather than a separate test eevironment.

This is an "issue" with the hook itself and should have been discussed in #320266. The changes here simply follow the docs [recommendation](https://github.com/NixOS/nixpkgs/blob/7887a3cd00b338d0100d609a7e80abf566337aa0/pkgs/stdenv/generic/make-derivation.nix#L248) of preferring `checkVersionHook`. If you would like to discuss this further, feel free to open a separate issue

> This basically breaks cross-compilation unless you also have binfmt set up, which in turn further restricts the platforms these packages can be built on (and you have to deal with emulation, which presumably you wanted to avoid in the first place if you were cross-compiling...)

As already [mentioned](https://github.com/NixOS/nixpkgs/pull/320266#pullrequestreview-2147943515) in the original PR, the installCheck phase is [disabled](https://github.com/NixOS/nixpkgs/blob/7887a3cd00b338d0100d609a7e80abf566337aa0/pkgs/stdenv/generic/make-derivation.nix#L248) for cross compiled builds. This is not an issue

> Simplification shouldn't introduce incorrect designs

Aside from what you mentioned above...what is incorrect here?

> Unclear

Many packages require workarounds in filtering their output to use `testVersion` -- two examples are [fastfetch](https://github.com/NixOS/nixpkgs/blob/7887a3cd00b338d0100d609a7e80abf566337aa0/pkgs/by-name/fa/fastfetch/package.nix#L157) and [menulibre](https://github.com/NixOS/nixpkgs/blob/7887a3cd00b338d0100d609a7e80abf566337aa0/pkgs/by-name/me/menulibre/package.nix#L53). Other packages also did things similar to the new hook, such as using `--help` to test and/or find a version -- see [dependabot-cli](https://github.com/NixOS/nixpkgs/blob/7887a3cd00b338d0100d609a7e80abf566337aa0/pkgs/by-name/de/dependabot-cli/package.nix#L45) and [flite](https://github.com/NixOS/nixpkgs/blob/7887a3cd00b338d0100d609a7e80abf566337aa0/pkgs/by-name/fl/flite/package.nix#L62) for examples of this

> except r-ryantm and ofborg already build the tests anyway

Many contributors look over this though, and it commonly results in these tests failing in PRs when they could have otherwise been caught earlier. This obviously isn't a knock against `testVersion` or `passthru.tests` in general (making sure contributors are correct is ofborgs job after all), but an advantage here nonetheless

> We should consistently use testVersion imo

Once again, feel free to open another issue to discuss this further. For now, the docs explicitly state `checkVersionHook` should be preferred

> Those builders should be fixed instead

I 100% agree! Until then though, this does avoid the issue

**Comment by eclairevoyant** [comment]
If we're talking about docs, they do say:

> `passthru.tests` have several advantages over running tests during any of the [standard phases](https://github.com/nixos/nixpkgs/blob/master/doc/stdenv/passthru.chapter.md#sec-stdenv-phases):
> * They access the package as consumers would, independently from the environment in which it was built

Build overhead is probably irrelevant, but this is relevant and the point I made above.

**Comment by getchoo** [comment]
>  the independent env is relevant

The hook does [run](https://github.com/NixOS/nixpkgs/blob/45eb64faac1a6fb88d5304bd8f7e8d9e9a4dd442/pkgs/by-name/ve/versionCheckHook/hook.sh#L3) in a clean environment with a different working directory -- which was actually added for similar reasons [here](https://github.com/NixOS/nixpkgs/pull/320266#discussion_r1641912280). Once again though, this feels more like you taking issue with the existence and efficacy of the hook itself rather than this PR specifically. I would highly encourage opening a separate issue to discuss this

**Comment by eclairevoyant** [comment]
Of course, hence I object to a treewide mass rebuild PR that uses it.

**Comment by doronbehar** [comment]
I agree that if our consensus is not strong regarding the hook and the recommendation for it by the docs, perhaps these disagreements should block this PR. Unfortunately the PR that added the hook hasn't received wide attention. @eclairevoyant please open a new discussion in an new issue where you address specific sentences in the docs with which you don't agree, and explain why thoroughly.

**Comment by doronbehar** [comment]
> I object to a treewide mass rebuild PR that uses it if it's not a net benefit.

I partially agree with this argument, but not exactly with how it is phrased: We have a `staging` branch specifically to not really trigger mass rebuilds, because the `staging` receives all the time changes that trigger such mass rebuilds, and sometimes even basic stuff like compilers and `zlib` don't build on it, and eventually in a `staging-next` cycle things stabilize.

I do agree that in terms of potential `master` -> `staging` merge conflicts issues, and also because this PR is so big, it'd be better to only touch here leaf packages that don't trigger mass rebuilds. Also we should remember the main motivation for creating the hook was especially significant for leaf packages:

https://github.com/NixOS/nixpkgs/blob/716331fb51dea939278290ea2b22f5a47cb46104/doc/stdenv/passthru.chapter.md?plain=1#L86-L88

Additionally, running a nixpkgs-review on this PR would be easier if only leaf packages would be touched. Perhaps we should limit this to less then 200 rebuilds? The hard part would be to filter out from the current PR the mass rebuild triggering packages...

See also discussion that started here (which was the seed for the idea of this hook):

https://discourse.nixos.org/t/improve-the-jdk-infrastructure-on-nixpkgs/45678/7

**Comment by pbsds** [comment]
Looking for reviewers for https://github.com/NixOS/nixpkgs/pull/344321 i now discover this discussion. I believe the trade-off between the two is worth considering, but should be at the package maintainers discretion.

**Pull request closed without merging**
