### PR TITLE
llvmPackages_19: 19.1.0-rc3 -> 19.1.0

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

Full LLVM 19.1.0 release

https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by alyssais — APPROVED** [review]
Looks fine — I haven't looked enough to know what the patches do but I trust your judgement there.

**Comment by alyssais** [comment]
Oh, would be good to update llvmPackages_latest.

**Comment by emilazy** [comment]
Looks like it already was?

I’m investigating the `libclc` situation, since Firefox runs into it.

**Comment by RossComputerGuy** [comment]
Yeah, libclc will probably be good once the small improvements PR is merged. I just changed the alias so it didn't distrupt oth people's stuff in the meantime. We can change it back to latest once that PR is merged.

Other than that, anything else should we do or good to merge?

**Comment by emilazy** [comment]
Do you have a link to that PR so I can track it? This seems fine as it is now though.

**Comment by RossComputerGuy** [comment]
Yes, it's #336465

**Comment by emilazy** [comment]
Aha, thanks. I think https://github.com/NixOS/nixpkgs/pull/336465 looks basically good to merge, so maybe you could drop the `libclc` change from this and we can land them both together?

**Comment by RossComputerGuy** [comment]
Maybe, I can only change that after work in like 6 hours lol.

**Pull request merged**
