### PR TITLE
python-neovim: 0.0.38 -> 0.1.7

### PR DESCRIPTION
**Pull request by gilligan**
Recently 2e80f19f39891210a30f2ee214fa2856aeedbf86 upgraded neovim to 0.1.3 which caused some problems for me which I managed to solve after updating python-neovim which was pretty ancient.

Tested on: **OSX**

/cc @garbas

### CODE REVIEW

**Comment by gilligan** [comment]
The CI build fails but log is too long to fit. I have no idea what the actual problem is. Can anyone help me out with this?

**Comment by retrry** [comment]
At the bottom of the page there is a text and link, which lets you access raw log. https://s3.amazonaws.com/archive.travis-ci.org/jobs/125419113/log.txt

**Comment by garbas** [comment]
@gilligan neovim fails to build on python 3.5 and neovim-gui moved to neovim/python-gui

**Comment by gilligan** [comment]
@garbas that is unrelated to updating the neovim python package though? How can I proceed with this?

**Comment by garbas** [comment]
@gilligan if things break when you update something that is related :) to proceed please fix the build of neovim-gui and use the source from https://github.com/neovim/python-gui ... it should be hard to get it up and running.

as for the python3.5 i'm not sure if python 3.5 is supported, if it is then we need to report the problem upstream and disable building for python 3.5 meanwhile. or if python 3.5 is unsupported then we disabled it for this version.

**Comment by gilligan** [comment]
```
The log length has exceeded the limit of 4 MB (this usually means that
 the test suite is raising the same exception over and over).
```
Locally the following succeeds:
```
nix-build -A neovim-pygui -A python27Packages.neovim -A neovim-qt -A neovim ~/nixpkgs
```

Only *caveat*: I did have to disable the neovim python package for python3.5 for this to succeed. I have no idea what the python build problem is all about ;(

**Pull request closed without merging**
