### PR TITLE
 plasma: 5.10.5 -> 5.11.1

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
KDE Plasma feature release!

~~Cryfs support is removed from the new plasma-vault feature as I do not want to package & maintain this.~~

Also had to update Digikam and libqtav as Digikam would not build.

Update (2017-10-18): Bugfix release 5.11.1 was made, PR updated .

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`) (not all but I have tested getting a fully functional desktop)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @ttuegel

### CODE REVIEW

**Comment by bkchr** [comment]
Do you have any problems with SDDM after this update? 
I'm also using qt 5.9.2, but that worked before the update without any problems.

**Comment by adisbladis** [comment]
@bkchr I'm not aware of any problems though I have only tested with auto login.

**Comment by adisbladis** [comment]
@bkchr This only happens with the breeze theme, not with the official sddm themes.

**Comment by bkchr** [comment]
Nice that you can reproduce it. Any idea what could be the problem?

**Comment by peterhoeg** [comment]
We are still using sddm 0.15 while 0.16 was just released so maybe upgrading that as well helps?

**Comment by adisbladis** [comment]
@peterhoeg I tried that and it does not resolve the issue.

**Comment by ttuegel** [comment]
Thanks! I'll check this out in a bit.

Regarding `plasma-vault`, have you checked that it works with `encfs`?

**Comment by adisbladis** [comment]
@ttuegel Yes I tested it out and it works fine.

**Comment by ttuegel** [comment]
@adisbladis I can't see any reason for the segmentation fault in the SDDM greeter, either. It might help if you rebuilt Qt with debugging enabled.

**Comment by peterhoeg** [comment]
With cryfs in master, do you feel like adding back the cryfs support to the vault?

**Comment by bkchr** [comment]
Sddm works on my PC with Nvidia GPU, but on my Laptop with Intel GPU is segfaults. Maybe it is somehow related to the GPU?

**Comment by ttuegel** [comment]
> Maybe it is somehow related to the GPU?

That is possible.

We may need to give serious consideration to dropping SDDM. From reading Mesa bug reports, it turns out that KDE upstream does not test anything involving Xorg and their developers only use Wayland, implying that they do not test SDDM either.

**Comment by adisbladis** [comment]
@peterhoeg I've added back cryfs support to vault. Thanks for the cryfs package :)
@ttuegel I'm also getting the crash with current mesa from master.

**Comment by ttuegel** [comment]
> I'm also getting the crash with current mesa from master.

`master` has `mesa-17.1.10`, but `staging` has `mesa-17.2.2`.

If the crash is fixed with `mesa-17.2.2`, then we can just wait. Otherwise, we will need to file a bug report upstream with KDE.

**Comment by ttuegel** [comment]
Some users have reported that running SDDM with HiDPI enabled causes crashing due to some problem in Qt. The Plasma theme may exercise some bad code path. We should try disabling HiDPI as in sddm/sddm#701.

**Comment by adisbladis** [comment]
@ttuegel Beatiful! That was it.

I applied the fix as a patch changing the default behaviour (hidpi off by default).
I considered just changing the nixos service but felt this was more appropriate and easier to track with the next sddm upgrade when this will hopefully have been fixed.

**Comment by bkchr** [comment]
Ahh that is nice. I have a question regarding Wayland, @ttuegel do you think we could start to enable it in nixos for kde?

**Comment by ttuegel** [comment]
> do you think we could start to enable it in nixos for kde?

Not yet. Just like we have a custom `startkde` script to start an X11 session, we need custom `startplasma` and `startplasmacompositor` scripts.

**Comment by bkchr** [comment]
@adisbladis hmm, for me it still does not work :/ Did you also upgrade your mesa?

**Comment by adisbladis** [comment]
@bkchr No I did not upgrade my mesa. I saw in the `sddm` issue tracker that there are a lot (at least 3) of these issues causing similar symptoms.

**Comment by bkchr** [comment]
@adisbladis I tried to find the commit that is responsible for the linker error. Git bisect says that the following commit is the first one, where the build fails: https://github.com/NixOS/nixpkgs/commit/d32f7f4bb3b6a80fa79f097881b92bcebf702478

This does not look that suspicious ^^

**Comment by adisbladis** [comment]
Updated PR to plasma 5.11.1.
Also applied a commit from @bkchr that disables the gold linker for all things Qt.

This fixes linker errors with `plasma-integration` after `qtuickcontrols2` was added as a dependency.
Presumably fixes some other packages too.

**Comment by ttuegel** [comment]
> hmm, for me it still does not work :/ Did you also upgrade your mesa?

@adisbladis 
I tried again with 4a55bbb, and I still get a blank screen with SDDM, too.

**Comment by adisbladis** [comment]
@ttuegel Interestingly enough I get the same behaviour now after rebasing even with the patch applied so it seems like we have uncovered _yet another_ bug in `sddm`.

**Comment by adisbladis** [comment]
`digikam` and `libqtav` were merged to master, dropped those commits and rebased.

**Comment by ttuegel** [comment]
> we have uncovered yet another bug in sddm.

Nope, we're hitting this QML cache invalidation bug:
https://bugreports.qt.io/browse/QTBUG-62302

You can work around it by removing `/var/lib/sddm/.cache/sddm-greeter/qmlcache`.

I will see about backporting this patch to our Qt. 😃

**Comment by bkchr** [comment]
Ohh nice for finding that!

**Comment by ttuegel** [comment]
Merged in f7de0da188781aea2a4bf2b17e1fbaf8d65925da.

**Comment by peterhoeg** [comment]
Has anybody else been unable to launch KDE since the upgrade to plasma 5.11? I have 2 machines here and while one is perfectly fine, the other just shows a black screen after logging in from sddm. I need to manually wipe /var/lib/sddm/.cache/sddm-greeter/qmlcache for sddm to come up despite @ttuegel ```rm``` in the setup script as well. All I see is ```kded5``` core dumping.

**Comment by bkchr** [comment]
I had the same problem for my laptop, I also needed to rm the directory by hand. But I don't know if I need to do that everytime.

**Comment by ttuegel** [comment]
> the other just shows a black screen after logging in from sddm

This doesn't sound like an issue with the SDDM cache, it sounds like an issue with the qmlcache for Plasma! Do you have any qmlcache directories in $HOME?

**Comment by bkchr** [comment]
Ohh, for me this happened to be SDDM crashing.

**Pull request merged**
