### PR TITLE
python3Packages.sagemaker: 2.24.5 -> 2.25.1

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113955` at b59057f8 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/fe1e3a06b7decc0de7a265f3900b5b91">python37Packages.sagemaker</a></li></li>
    <li><a href="https://gist.github.com/88bf6761b727b1ac7670869fc86fc23e">python38Packages.sagemaker</a></li></li>
    <li><a href="https://gist.github.com/6150b84055de282ebcc619dc6a87170c">python39Packages.sagemaker</a></li></li>
  </ul>
</details>

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 113955` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.sagemaker</li>
    <li>python38Packages.sagemaker</li>
    <li>python39Packages.sagemaker</li>
  </ul>
</details>

**Comment by davidak** [comment]
@NeQuissimus have you tested it?

I tested the one executable and it fails:

```
[nix-shell:~/.cache/nixpkgs-review/pr-113955]$ ./results/python39Packages.sagemaker/bin/sagemaker-upgrade-v2 
pandas failed to import. Analytics features will be impaired or broken.
Traceback (most recent call last):
  File "/nix/store/x1s4anwvpc7ib5a7mr1rxiakphfbplzw-python3.9-sagemaker-2.25.1/bin/.sagemaker-upgrade-v2-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/x1s4anwvpc7ib5a7mr1rxiakphfbplzw-python3.9-sagemaker-2.25.1/lib/python3.9/site-packages/sagemaker/cli/compatibility/v2/sagemaker_upgrade_v2.py", line 79, in main
    _update_file(args.in_file, args.out_file)
  File "/nix/store/x1s4anwvpc7ib5a7mr1rxiakphfbplzw-python3.9-sagemaker-2.25.1/lib/python3.9/site-packages/sagemaker/cli/compatibility/v2/sagemaker_upgrade_v2.py", line 37, in _update_file
    input_file_ext = os.path.splitext(input_file)[1]
  File "/nix/store/8vdzy514gg2frvcxv3zdhx912cch6xd9-python3-3.9.1/lib/python3.9/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Since there seem to be not tests in pypi release, using this at least would be good:

`  pythonImportsCheck = [ "sagemaker" ];`

or could you use the github release und use the tests from it?

**Review by davidak — CHANGES_REQUESTED** [review]
dependency issue, see comment

**Comment by SuperSandro2000** [comment]
Well, keeping tabs open does not always update comments and GitHub decided to show me everything after the build results after I merged this.

**Pull request merged**
