### PR TITLE
mynewt-newt: 1.7.0 -> 1.10.0

### PR DESCRIPTION
**Pull request by StarGate01**
###### Description of changes

This PR updates the Apache MyNewt package (`newt`). The previously explicitly applied patches have since been upstreamed (https://github.com/apache/mynewt-newt/pull/312 , https://github.com/apache/mynewt-newt/pull/343) .

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by StarGate01** [comment]
@pjones @Thra11 do you have any tips or comments for this PR?

**Review by pjones — APPROVED** [review]

**Comment by bobby285271** [comment]
Looks like the darwin build has a regression :eyes: 
https://hydra.nixos.org/job/nixpkgs/trunk/mynewt-newt.x86_64-darwin

It will also be nice to remove the unused `fetchpatch` from args (line 1)

**Comment by StarGate01** [comment]
Appears to be a Go problem, from what I gathered.

```
vendor/github.com/shirou/gopsutil/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 
```

Any ideas on how to fix this? I could set `platforms = platforms.linux;` (?).

**Comment by StarGate01** [comment]
@bobby285271 Darwin appears to build now with the `CGO_ENABLED`patch .

**Comment by bobby285271** [comment]
Thanks!

**Pull request merged**
