### PR TITLE
python3.pkgs.mmcv: fix build

### PR DESCRIPTION
**Pull request by benxiao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
the build is working without this change (on linux-x86_64), could you elaborate a little more what is broken ?

**Comment by benxiao** [comment]
There are two things broken
one is similiar to https://github.com/NixOS/nixpkgs/pull/251151#issuecomment-1692485096

the other one there is a collision of dependency for protobuf. one from torch and another from onnxruntime.  torch uses v4, and onnxruntime uses v3. and the torch ci currently uses v3 as well. not sure what is the best way to fix it. any advice is welcome. @happysalada

**Comment by happysalada** [comment]
How can i trigger the failure locally ? Does the failure only happen on staging next or another branch ?

**Comment by benxiao** [comment]
are you on master?

**Comment by benxiao** [comment]
```git checkout master
nix-build -A python3.pkgs.mmcv
```

**Comment by kirillrdy** [comment]
> How can i trigger the failure locally ? Does the failure only happen on staging next or another branch ?

I can also reproduce the build issue on x86_64-linux

**Comment by happysalada** [comment]
After that latest merge of staging-next, got it. I wasn't on the latest commit.

I've looked a bit at the build process of onnxruntime and it's intense.
They are on protobuf 21, and the compilation will fail trying any tricks to get a different version.
I'd love to be proven wrong here, but I'm guessing we have to wait until onnxruntime updates their dependencies.

I think we can merge the pybind11 addition in the meantime. It doesn't fix the build completely, but it will be required in the future no matter what.

**Comment by benxiao** [comment]
what about downgrade torch to use protobuf3_21, it is the version used in their CI.

**Comment by happysalada** [comment]
looking a bit further, it looks like onnx has switched to protobuf python 4
https://github.com/onnx/onnx/pulls?q=is%3Apr+protobuf+is%3Aclosed
 however trying to build master with protobuf 4 fails on some weird abseil error (after adding abseil to the list of dependencies). 

downgrading the torch propagated build input might break dependents. I don't know how many it will break though, or if it will break any. It feels like that change to downgrade the version is a little backwards, but it might be an acceptable temporary solution.

**Comment by happysalada** [comment]
here is the ci reference for torch https://github.com/pytorch/pytorch/blob/c2ac0da445cfe3d848342926f9cd4422bd35bfe2/.ci/docker/requirements-ci.txt#L133
(better to put it here for reference).

**Comment by kirillrdy** [comment]
builds at 68142254d20256e617f596a5d50f9950f98fa36a

```
nix-build -A python3.pkgs.mmcv
/nix/store/lhbqkvii64kppvi4ffxj0dsq0yppyfsv-python3.11-mmcv-2.1.0
```

**Pull request closed without merging**
