### PR TITLE
efl: 1.17.2 -> 1.18.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update to the new release of EFL.

In version 1.18.0 the Elementary widget toolkit as well as the evas generic loaders and emotion generic players packages were merged into the EFL source tree. Therefore all related Nix packages have to be adapted.
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RamKromberg** [comment]
@romildo Does enlightenment show svg icons properly now? ( https://github.com/NixOS/nixpkgs/issues/16541 )

**Comment by romildo** [comment]
@RamKromberg Enlightenment 0.21.2 with EFL 1.18.0 is showing svg icons properly with the `tyls` command on `terminology`, as can be seen in the screen shot:
enlightenment-terminology-tyls-screenshot

**Comment by romildo** [comment]
Svg icons are also displayed in the file manager:
enlightenment-efm-screenshot

**Comment by RamKromberg** [comment]
@romildo Great! I was pushing commits left and right dancing around the issue in hopes once 16.09 comes out, I'll have a stable enough system to sit on for a couple of week and solve this... And then you just happened to solve it for me :D

Big thanks :)

**Pull request merged**
