### PR TITLE
freshBootstrapTools: refactor to use callPackage style for Darwin

### PR DESCRIPTION
**Pull request by philiptaron**
## Motivation for changes

Removing a top-level `with` in `pkgs/stdenv/darwin/make-bootstrap-tools.nix` (#208242). Providing clarity on the relationship between each of the bootstrap steps for Darwin.

## Description of changes

- [x] Extracted each derivation into its own package.
- [x] On new files, ran `nixfmt`.
- [x] Used explicit attrset building instead of `rec`.

## Things done

On master, ran this command: 

```
nix-instantiate --eval --system x86_64-darwin -A freshBootstrapTools.build.outPath -A freshBootstrapTools.bootstrapTools.outPath -A freshBootstrapTools.bootstrapFiles.unpack.outPath -A freshBootstrapTools.bootstrapFiles.bootstrapTools -A freshBootstrapTools.test.outPath -A freshBootstrapTools.test-pkgs.stdenv.outPath
```

Then, on this branch, ran the same command, and saw no change.

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by emilazy — APPROVED** [review]

**Comment by paparodeo** [comment]
@ofborg build freshBootstrapTools.test

**Review by toonn — APPROVED** [review]
LGTM (haven't tested)

**Comment by philiptaron** [comment]
Drafting this to fix the merge conflict, whatever it is.

**Comment by philiptaron** [comment]
Validated that the outPaths above did not change.

**Pull request merged**
