### PR TITLE
bambu-studio: 01.09.00.70 -> 01.09.07.52

### LINKED ISSUE #339834: Update request: bambu-studio 1.9.0.70 → 1.9.5
- Package name: bambu-studio
- Latest released version: 1.9.5 -- v01.09.05.51 

- Current version on the unstable channel: 1.9.0.70 
- Current version on the stable/release channel: 1.9.0.70 

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@zhaofengli @kirillrdy 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dsluijk**
This PR solves some build issues with Bambu Studio, and updates the version to latest. Fixes #339834.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pinpox** [comment]
@ofborg build bambu-studio

**Review by pinpox — APPROVED** [review]
PR Looks good to me and ofborg build it fine. I have not managed to build it locally since my machine is too weak, so I can't test the functionality.

**Comment by pinpox** [comment]
> @pinpox I've built it locally and although I'm not a bambu studio user basic functionality like slicing, exporting/importing stls and gcode, changing settings etc seems to work ok

I managed to pull it from a CI cache and run it. I only get to the loading screen and see some errors in the terminal:
```
/nix/store/0pzqrih4mv10yrd9pnp8nj8l5wdy7209-orca-slicer-2.1.1/bin/orca-slicer 
[2024-10-30 20:12:07.289284] [0x00007f0b70ba0020] [trace]   Initializing StaticPrintConfigs
add font of HarmonyOS_Sans_SC_Bold returns 1
add font of HarmonyOS_Sans_SC_Regular returns 1
add font of NanumGothic-Regular returns 1
add font of NanumGothic-Bold returns 1
/nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgvfsdbus.so: cannot open shared object file: No such file or directory
Failed to load module: /nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgvfsdbus.so

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.522: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.522: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.524: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.547: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.547: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.547: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.581: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.601: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.641: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.666: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.701: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.724: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.761: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:17.785: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.474: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.553: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.553: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.568: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.568: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.571: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.571: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.572: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.572: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.707: gtk_window_resize: assertion 'height > 0' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.726: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:19.726: gtk_widget_set_size_request: assertion 'width >= -1' failed
/nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgioremote-volume-monitor.so: cannot open shared object file: No such file or directory
Failed to load module: /nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgioremote-volume-monitor.so
/nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgvfsdbus.so: cannot open shared object file: No such file or directory
Failed to load module: /nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgvfsdbus.so
/nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgioremote-volume-monitor.so: cannot open shared object file: No such file or directory
Failed to load module: /nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgioremote-volume-monitor.so

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:21.955: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:21.956: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.160: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.161: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.285: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.285: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.457: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.457: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.619: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.619: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.818: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:22.818: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:23.064: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:23.064: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:23.251: gtk_widget_set_size_request: assertion 'width >= -1' failed

(orca-slicer:367456): Gtk-CRITICAL **: 20:12:23.251: gtk_widget_set_size_request: assertion 'width >= -1' failed
/nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgvfsdbus.so: cannot open shared object file: No such file or directory
Failed to load module: /nix/store/isvpgnnhm3zqh2j2nw6r3f1704590cq0-gvfs-1.54.2/lib/gio/modules/libgvfsdbus.so
```

I'm running `orca-sclicer` but that is based on bambu-studio and uses the same code.

**Comment by jonboh** [comment]
are you sure you got the right output? I get a different output hash for the latest commit of this PR 
image
I get `/nix/store/aww6j23hgs3shz157a7bxxn53cqs6yjz-orca-slicer-2.1.1`
This output seems to work ok

**Comment by a-kenji** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 348091`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>

**Review by a-kenji — APPROVED** [review]
Tested simple functionality, seems to work.

**Pull request merged**
