### PR TITLE
morgen: 2.5.16 -> 2.6.3

### PR DESCRIPTION
**Pull request by thufschmitt**
Semi-automatic update generated by [nixpkgs-update](https://github.com/ryantm/nixpkgs-update) tools.

meta.description for morgen is: "All-in-one Calendars, Tasks and Scheduler"

meta.homepage for morgen is: "https://morgen.so/download"

meta.changelog for morgen is: ""

- Version update

<details>
<summary>
<b>Checks done</b> (click to expand)
</summary>

---

- built on NixOS
- The tests defined in `passthru.tests`, if any, passed
- found 2.6.3 with grep in /nix/store/krc8yiyp620r51zyk5kmn0ykbgjfd6an-morgen-2.6.3
- found 2.6.3 in filename of file in /nix/store/krc8yiyp620r51zyk5kmn0ykbgjfd6an-morgen-2.6.3

---

</details>
<details>
<summary>
<b>Rebuild report</b> (if merged into master) (click to expand)
</summary>

```
1 total rebuild path(s)

1 package rebuild(s)

First fifty rebuilds by attrpath
morgen
```

</details>

<details>
<summary>
<b>Instructions to test this update</b> (click to expand)
</summary>

---

Build yourself:
```
nix-build -A morgen https://github.com/r-ryantm/nixpkgs/archive/380c29d902d9d415d9743a4d3de18c5cd5e447e7.tar.gz
```

After you've downloaded or built it, look at the files and if there are any, run the binaries:
```
ls -la /nix/store/krc8yiyp620r51zyk5kmn0ykbgjfd6an-morgen-2.6.3
ls -la /nix/store/krc8yiyp620r51zyk5kmn0ykbgjfd6an-morgen-2.6.3/bin
```

---

</details>
<br/>

NixPkgs review skipped

---

cc @WolfangAukang for [testing](https://github.com/ryantm/nixpkgs-update/blob/master/doc/nixpkgs-maintainer-faq.md#r-ryantm-opened-a-pr-for-my-pack
age-what-do-i-do).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 206222` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>morgen</li>
  </ul>
</details>

**Comment by thufschmitt** [comment]
@WolfangAukang `morgen` currently depends on `elecron_15` which is marked as insecure. I've opened a parallel PR to fix that (#206215) since it's an orthogonal change.

(sorry for the late reply, I lost track of your comment somehow)

**Review by WolfangAukang — APPROVED** [review]
LGTM

**Comment by wegank** [comment]
Superseded by #213972.

**Pull request closed without merging**
