### PR TITLE
neocities: init at 0.0.18

### PR DESCRIPTION
**Pull request by Infinidoge**
## Description of changes

Packages the neocities CLI. 
The neocities gem is also a Ruby library. However, since I don't know too much about Ruby, I didn't end up packaging the gem as a library.
If I should try and repackage it for both CLI and library, please let me know.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by arthsmn — APPROVED** [review]
LGTM. Also, closes https://github.com/NixOS/nixpkgs/issues/276804.

**Review by aquifolly — APPROVED** [review]

**Comment by arthsmn** [comment]
Can you please use the [by-name category](https://github.com/NixOS/nixpkgs/tree/master/pkgs#category-hierarchy) here? This would make the change to all-packages.nix unneeded.

**Comment by Infinidoge** [comment]
Rebased on master while I'm at it, switching to by-name now. I don't actively use neocities anymore, but since the CLI doesn't update much I don't mind being a maintainer for it. If someone else wants to be a maintainer instead, let me know.

**Comment by raspher** [comment]
closes: #276804

just to link to issue

**Review by arthsmn — APPROVED** [review]

**Pull request merged**
