### PR TITLE
nodejs: use python3 if possible

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

1. Python 2 is EOL so I think we should use python3 by default for the nodejs versions that support it.
2. Allow choosing a nodejs build flavor / version with the `programs.npm.` nixos config.

cc @cillianderoiste @gilligan @cko 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by marsam — APPROVED** [review]
LGTM. I think this can go directly to `master`

**Comment by doronbehar** [comment]
Hmm interesting it doesn't trigger a rebuild of all `nodePackages`. Thanks for your approval @marsam.

**Comment by calbrecht** [comment]
I have declared `nodePackages = pkgs.nodePackages_13_x` in my overlays.
There is no `npm` in `nodePackages_13_x`.
This is inconvenient, especially if i don't want to have npm in my nodePackages at all.
```console
tutnix ~ 
% nixos-rebuild test
building Nix...
building the system configuration...
error: attribute 'npm' missing, at /home/alab/ws/nixpkgs/nixos/modules/programs/npm.nix:19:19
(use '--show-trace' to show detailed location information)
tutnix ~ 
% nix-build \<nixpkgs\> --no-out-link --no-build-output -A nodePackages.npm
error: attribute 'npm' in selection path 'nodePackages.npm' not found
tutnix ~ 
% nix-build \<nixpkgs\> --no-out-link --no-build-output -A nodePackages_10_x.npm
/nix/store/6mkiyvgphqahlzvj6w4f95qpal5jp1gd-node_npm-6.14.4
tutnix ~ 
% nix-build \<nixpkgs\> --no-out-link --no-build-output -A nodePackages_12_x.npm
error: attribute 'npm' in selection path 'nodePackages_12_x.npm' not found
tutnix ~ 
% nix-build \<nixpkgs\> --no-out-link --no-build-output -A nodePackages_13_x.npm
error: attribute 'npm' in selection path 'nodePackages_13_x.npm' not found
```

**Comment by calbrecht** [comment]
@doronbehar maybe you could change this to
```patch
diff --git a/nixos/modules/programs/npm.nix b/nixos/modules/programs/npm.nix
index f101a44587a..52810f526cd 100644
--- a/nixos/modules/programs/npm.nix
+++ b/nixos/modules/programs/npm.nix
@@ -14,9 +14,9 @@ in
       enable = mkEnableOption "<command>npm</command> global config";
 
       package = mkOption {
-        type = types.path;
+        type = types.path or null;
         description = "The npm package version / flavor to use";
-        default = pkgs.nodePackages.npm;
+        default = if hasAttr "npm" pkgs.nodePackages then pkgs.nodePackages.npm else null;
         example = literalExample "pkgs.nodePackages_13_x.npm";
       };
```

**Comment by doronbehar** [comment]
Can't you use:

```nix
    programs.npm.package = pkgs.nodejs_latest;
```

?

> This is inconvenient, especially if i don't want to have npm in my nodePackages at all.

I'm not sure I understand what kind of ability does the current module is missing. If you feel there are missing attributes to some of the `nodePackages`* attribute sets, then please fix it in a different PR. This one is merged & done. I'm afraid I don't have the necessary time to do apply your suggestions my self or review them once made. Then please don't try to request my review :pray: . Thanks.

**Comment by calbrecht** [comment]
I could :) The point is i do not use programs.npm so why should i need to set this?

**Pull request merged**
