### PR TITLE
Refactor Pharo to allow co-installation of VMs

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
@vcunat this is from our discussion on #12388

**Comment by DamienCassou** [comment]
I don't understand what is wrong with travis, it works fine on my computer.

**Comment by globin** [comment]
I get the same error that travis reports. Could you check this again?

**Comment by vcunat** [comment]
> I get the same error that travis reports. Could you check this again?

See https://github.com/NixOS/nixpkgs/commit/0b4c7d42#commitcomment-15500534

It works fine for you because the URL isn't tried again, as you already have something with the correct output hash.

**Comment by DamienCassou** [comment]
@vcunat thanks

**Comment by vcunat** [comment]
Oh, I thought you don't have push rights, but now I see you do. (Hmm, private membership in push-right group in a world-readable repo is such a strange thing... anyone can see that you do/did have the right anyway.)

**Pull request merged**
