### PR TITLE
beamerpresenter: use qt6

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @stiglers-eponym

### CODE REVIEW

**Review by stiglers-eponym — APPROVED** [review]
Everything seems fine, it can be built with Qt5 or Qt6. Thanks for clearing up the build file!

I experienced two problems that are probably related to my broken Nix installation or the dependencies of Qt6 multimedia:
1. In Qt6 I cannot run beamerpresenter with wayland, although I installed qt6.qtwayland. (in xwayland it works)
2. Without installing extra packages for multimedia, the program crashes when it should try to play a video.

**Comment by peterhoeg** [comment]
What's the reason for moving to qt6 instead of sticking to qt5 for a while?

**Comment by stiglers-eponym** [comment]
A comment to @peterhoeg's question:
Independent of Nix, there are only small differences between BeamerPresenter for Qt 5 and Qt 6:
* When playing videos in a loop in Qt 5, you might see a short black frame each time the video is restarted. In Qt 6 a different implementation of the video player avoids that. But probably this is platform dependent.
* Tablet input are handled a bit differently in Qt 5 and Qt 6. Buttons of table input devices might work better in Qt 6. However, this is not yet relevant in version 0.2.2 of BeamerPresenter.
* not relevant for Nix: In Qt>=6.3 there is the option to include Qt PDF as PDF engine.

Conclusion: Releases of BeamerPresenter should run equally well on Qt 5 and Qt 6 and differ only in very specific situations.

**Comment by dotlambda** [comment]
> 1. In Qt6 I cannot run beamerpresenter with wayland, although I installed qt6.qtwayland. (in xwayland it works)

I don't think installing `qtwayland` globally would help. I added it to `buildInputs`. Can you try again?

> 2. Without installing extra packages for multimedia, the program crashes when it should try to play a video.

Which packages? This is not the case on Qt 5? Do you have a PDF I can try this with?

**Comment by dotlambda** [comment]
> What's the reason for moving to qt6 instead of sticking to qt5 for a while?

There's no pressing reason, I just think it's a good idea to start the transition as early as possible.

**Comment by stiglers-eponym** [comment]
> > 1. In Qt6 I cannot run beamerpresenter with wayland, although I installed qt6.qtwayland. (in xwayland it works)
> 
> I don't think installing `qtwayland` globally would help. I added it to `buildInputs`. Can you try again?

Yes, it works now (tested in a fresh new installation of nix).

> > 2. Without installing extra packages for multimedia, the program crashes when it should try to play a video.
> 
> Which packages? This is not the case on Qt 5? Do you have a PDF I can try this with?

In Qt 5 the video would not play, but the program does not crash. I have not tested which packages are required in Nix. It should be Gstreamer and some of its plugins. In Arch I need `gst-plugins-good` and `gst-libav`.

As an example PDF you can use [this example.pdf](https://github.com/NixOS/nixpkgs/files/9023937/example.pdf). It requires a [video file `movie.mp4`](https://user-images.githubusercontent.com/46252273/176793046-6bbc353f-3983-448f-9a53-0f01d5080b57.mp4), which must be called `movie.mp4` and put in the same directory as the PDF. (You could use any mp4 video file for that.)

**Comment by dotlambda** [comment]
I added the dependencies required for video playback and tested that it works.

**Review by stiglers-eponym — APPROVED** [review]
Works on my system, including videos.

**Comment by peterhoeg** [comment]
> There's no pressing reason, I just think it's a good idea to start the
> transition as early as possible.
>

Fair enough. Is anything special needed for qt6 applications under KDE or
do they pick up the regular theme automatically?

>

**Pull request merged**
