### PR TITLE
steam: refactor steam-runtime

### PR DESCRIPTION
**Pull request by Synthetica9**
#### Overview of changes:

- Use JSON instead of Nix for runtime-generated. The fetching of sources
  is done in runtime.nix.
- runtime-generated now only specifies a path within the steamrt mirror,
  instead of the full url.
- Automatically update the version (date) of steam-runtime.
- Add a version to steam-runtime-wrapped.
- Remove runtime-mirror.nix. There was no reference anywhere in nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Synthetica9** [comment]
cc @hrdinka @abbradar

**Comment by c0bw3b** [comment]
@hrdinka @abbradar are you ok to merge this as maintainers?
Seems ready to me.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by Infinisil** [comment]
No activity in over a year, closing for now

**Pull request closed without merging**
