### PR TITLE
kubernetes: 1.9.5 -> 1.20.4

### PR DESCRIPTION
**Pull request by blaggacao**
Replaces https://github.com/NixOS/nixpkgs/pull/109275

Incorporated https://github.com/NixOS/nixpkgs/pull/109275#issuecomment-781963494

/cc @johanot

### CODE REVIEW

**Comment by turion** [comment]
The title should be "kubernetes: 1.19.5 -> 1.20.4" (note 19 instead of 20)

**Comment by srhb** [comment]
@blaggacao Could you please tell us a bit more about this PR? What did you test, and does the patch change require release notes for 21.05, or is it just drop-in identical? I noticed you've started incorporated some discussion on the old PR regarding nixpkgs vs. NixOS compatibility, which makes me unsure of the status of the NixOS module in this PR. Don't get me wrong, I'm not against that discussion on Discourse, but I want to make sure that this isn't a ninja "policy change" that breaks a bunch of prod clusters. :)

**Comment by srhb** [comment]
I've marked myself as a reviewer here because of my concerns outlined above. This is not to say that we can't progress this PR, or the other PR (of course!) but to emphasize that for now, I believe we need to be empathetic to users of the the NixOS module regardless of potential future policy changes on its quality or "soft guarantees of functionality" :)

**Comment by blaggacao** [comment]
@srhb I litterally just did what https://github.com/NixOS/nixpkgs/pull/109275#issuecomment-781963494 suggested. I wanted to move things forward since the other PR is marked as draft.

As CI shows this (and also the old PR) actually break for the same reason. I've not really a clue how to resolve that, though.

**Comment by blaggacao** [comment]
Concede to #114737

**Pull request closed without merging**
