### PR TITLE
kcl: refactor

### LINKED ISSUE #310770: Missing completion for kcl-cli package
### Describe the bug
After installation kcl-cli@0.8.7, shell completion is not available.

### Steps To Reproduce
1. Install kcl-cli@0.8.7
2. Try completion

### Expected behavior
Shell completion should be installed.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@peefy

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-105-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/home/sestegra/.nix-defexpr/channels/nixp
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by selfuryon**
## Description of changes

Hello! Currently, kcl [doesn't work](https://github.com/kcl-lang/kcl/issues/1169#issuecomment-2085246192) properly
<details>
  <summary>Example</summary>
  
```shell
$ nix shell nixpkgs#kcl-cli
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

$ cat main.k 
hello = "KCL"

$  kcl run main.k
Init kcl runtime failed, path:  /home/syakovlev/go
Tip: Have you used a binary version of KCL in your PATH that is not consistent with the KCL Go SDK? You can upgrade or reduce the KCL version or delete the KCL in your PATH
If not, you can run `rm -r /home/syakovlev/go/bin` to fix this issue
panic: unexpected EOF: stderr = Could not start dynamically linked executable: kclvm_cli
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld


goroutine 1 [running]:
kcl-lang.io/kcl-go/pkg/runtime.initRuntime(0xc00093f6d8?)
	kcl-lang.io/kcl-go@v0.8.5/pkg/runtime/init.go:62 +0x42f
kcl-lang.io/kcl-go/pkg/runtime.GetRuntime.func1()
	kcl-lang.io/kcl-go@v0.8.5/pkg/runtime/init.go:26 +0x15
sync.(*Once).doSlow(0x0?, 0x0?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
kcl-lang.io/kcl-go/pkg/runtime.GetRuntime()
	kcl-lang.io/kcl-go@v0.8.5/pkg/runtime/init.go:26 +0x2c
kcl-lang.io/kcl-go/pkg/service.NewKclvmServiceClient()
	kcl-lang.io/kcl-go@v0.8.5/pkg/service/client_kclvm_service.go:21 +0x13
kcl-lang.io/kcl-go/pkg/kcl.runWithHooks({0xc00093f890, 0x0, 0x0}, {0x5cae350, 0x1, 0x1}, {0xc00093faa8, 0x1, 0x1})
	kcl-lang.io/kcl-go@v0.8.5/pkg/kcl/api.go:477 +0x16e
kcl-lang.io/kcl-go/pkg/kcl.run(...)
	kcl-lang.io/kcl-go@v0.8.5/pkg/kcl/api.go:486
kcl-lang.io/kcl-go/pkg/kcl.RunWithOpts({0xc00093faa8?, 0xc00093faa8?, 0xc00093fa58?})
	kcl-lang.io/kcl-go@v0.8.5/pkg/kcl/api.go:373 +0x45
kcl-lang.io/kpm/pkg/api.RunWithOpt(0xc000b87200)
	kcl-lang.io/kpm@v0.8.5/pkg/api/kpm_run.go:89 +0x36a
kcl-lang.io/cli/pkg/options.(*RunOptions).Run(0xc0008f80e0)
	kcl-lang.io/cli/pkg/options/run.go:126 +0x1e9
kcl-lang.io/cli/cmd/kcl/commands.NewRunCmd.func1(0xc00058c400?, {0xc0005a8990?, 0x4?, 0x2263e4c?})
	kcl-lang.io/cli/cmd/kcl/commands/run.go:49 +0x5a
github.com/spf13/cobra.(*Command).execute(0xc00015e908, {0xc0005a8950, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015e608)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	kcl-lang.io/cli/cmd/kcl/main.go:14 +0x1c

```
</details>

The core problem is that `kcl` is a Go program that is coupled with `kclvm_cli` binary to work with kcl itself. The dependency graph looks like this:
`kcl` -> `kclvm_cli` -> `kclvm`, where

* `kclvm` is a library with KCL Language Implementation
* `kclvm_cli` is a low-level cli for working
* `kcl` is a wrapper around `kclvm_cli` which used to work with kcl files

So I did these on this PR:
* Added `kclvm` and `kclvm_cli` packages (mostly got from [here](https://github.com/diefans/kcl-nix))
* Rename `kcl-cli` to just `kcl`. I'm afraid that it would be super confusing to have three KCL-related packages where two of them have `cli` in their names. In all examples the documentation always references the binary as `kcl`, so I believe it's better to call the main package exactly `kcl` too.
* Add shell completion to `kcl` package

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---
@Peefy take a look on that too, pls.

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

Close #310770

### CODE REVIEW

**Comment by selfuryon** [comment]
dunno, why I have ` This PR does not cleanly list package outputs after merging`, and internally the error:
```
error: path '/nix/store/hnaydb7kpmjq1hhds1flah08gwxw26cy-source.drv' is not valid
```

Locally everything is working...

**Comment by selfuryon** [comment]
> dunno, why I have ` This PR does not cleanly list package outputs after merging`, and internally the error:
> 
> ```
> error: path '/nix/store/hnaydb7kpmjq1hhds1flah08gwxw26cy-source.drv' is not valid
> ```
> 
> Locally `kclvm` is working...

Looks like fixed after importing `Cargo.lock` directly to the package. Got the idea from here https://github.com/NixOS/nixpkgs/pull/284172#issuecomment-1913442916

**Comment by selfuryon** [comment]
I leave only `platforms.linux` because `kclvm` can't be compiled on `darwin` platforms, and I don't have `darwin` to check or debug why.

**Comment by aldoborrero** [comment]
@Mic92 @zimbatm can we have some love to this PR :)

**Pull request merged**
