### PR TITLE
shell_gpt: init at 0.7.3

### PR DESCRIPTION
**Pull request by MGlolenstine**
###### Description of changes
Added package for [`shell_gpt`](https://github.com/TheR1D/shell_gpt).
It's a CLI application that provides quick access to the ChatGPT bot.

Tests exist for this package, but they require a ChatGPT token to run, which is asked for interactively, and the token is private.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Thanks for this! feel free to ping me for updates!

also, pro tip, if you add the following to the package, the nix bot will take care of updates for you
```
  passthru = {
    updateScript = nix-update-script { };
  };
```
(optional whenever you have a moment).

**Comment by MGlolenstine** [comment]
I did not know about that!
Does that work for pypi packages only?

**Comment by MGlolenstine** [comment]
I'll keep that in mind for future endeavours; thanks! :)

**Comment by Magellol** [comment]
`shell_gpt` [released](https://github.com/TheR1D/shell_gpt) interesting features as of 0.8 onwards. I was curious if we could update the package version? I'm not sure what is the typical process to get an update in. Thanks!

**Comment by MGlolenstine** [comment]
@Magellol There's an [update PR](https://github.com/NixOS/nixpkgs/pull/225840) currently pending.
Could you give it a glance-over?

**Pull request merged**
