### PR TITLE
`gnomeExtensions.system-monitor`: patch to add `GTop` to the extension's path

### PR DESCRIPTION
**Pull request by Nanotwerp**
## Description of changes
This PR patches `gnomeExtensions.system-monitor`, an extension installed by default as of `GNOME 46`, so that `GTop` is within its path; otherwise, an error occurs when trying to enable this extension.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
@ofborg eval

**Comment by SebTM** [comment]
Did you create an upstream issue/MR and can link it in the code to keep track if it's needed in the future/on future updates?

**Comment by jtojnar** [comment]
This is Nix-specific patch. Not really upstreamable.

**Comment by SebTM** [comment]
Result of `nixpkgs-review pr 310143` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gnomeExtensions.system-monitor</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]

**Comment by jtojnar** [comment]
Thanks for checking.

**Comment by kirillrdy** [comment]
@Nanotwerp for some reason this doesn't fix it for me

```
nix flake info
Last modified: 2024-05-29 11:05:26
Inputs:
└───nixpkgs: github:nixos/nixpkgs/6c25325ec30a566f5c0446ceee61ada081903872
```

image

any hints for debugging ?

**Comment by SebTM** [comment]
@kirillrdy What commit is that you are building from? It's not `064730b54f13497b5a1a91a7f816124d513097e0` from this MR?

I cherry-picked it on unstable to confirm it's working.

**Comment by SebTM** [comment]
Can you let me know you GNOME Shell version? Mine is 46.1

**Comment by SamLukeYes** [comment]
After adding `gnomeExtensions.system-monitor` to `environment.systemPackages`, this fix works in my test vm. It seems this pr only fixes the standalone version of this extension, but not the one shipped with `gnomeExtensions.gnome-shell-extensions`.

**Comment by jtojnar** [comment]
Hmm, looks like that was missed in the [bump](https://github.com/NixOS/nixpkgs/commit/894ad2081f5d991bd9259c1bc5057b4d63b472df).

**Pull request merged**
