### PR TITLE
azure-cli: 2.18.0 -> 2.20.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
routine bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/115983

112 packages built:
appdaemon azure-cli dvc-with-remotes python38Packages.azure-appconfiguration python38Packages.azure-applicationinsights python38Packages.azure-batch python38Packages.azure-core python38Packages.azure-eventgrid python38Packages.azure-functions-devops-build python38Packages.azure-graphrbac python38Packages.azure-identity python38Packages.azure-keyvault python38Packages.azure-keyvault-administration python38Packages.azure-keyvault-certificates python38Packages.azure-keyvault-keys python38Packages.azure-keyvault-secrets python38Packages.azure-loganalytics python38Packages.azure-mgmt-advisor python38Packages.azure-mgmt-apimanagement python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-applicationinsights python38Packages.azure-mgmt-authorization python38Packages.azure-mgmt-batch python38Packages.azure-mgmt-batchai python38Packages.azure-mgmt-billing python38Packages.azure-mgmt-botservice python38Packages.azure-mgmt-cdn python38Packages.azure-mgmt-cognitiveservices python38Packages.azure-mgmt-commerce python38Packages.azure-mgmt-common python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-consumption python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerregistry python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-core python38Packages.azure-mgmt-cosmosdb python38Packages.azure-mgmt-databoxedge python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-datalake-analytics python38Packages.azure-mgmt-datalake-store python38Packages.azure-mgmt-datamigration python38Packages.azure-mgmt-deploymentmanager python38Packages.azure-mgmt-devspaces python38Packages.azure-mgmt-devtestlabs python38Packages.azure-mgmt-dns python38Packages.azure-mgmt-eventgrid python38Packages.azure-mgmt-eventhub python38Packages.azure-mgmt-hanaonazure python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-imagebuilder python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-iothub python38Packages.azure-mgmt-iothubprovisioningservices python38Packages.azure-mgmt-keyvault python38Packages.azure-mgmt-kusto python38Packages.azure-mgmt-loganalytics python38Packages.azure-mgmt-logic python38Packages.azure-mgmt-machinelearningcompute python38Packages.azure-mgmt-managedservices python38Packages.azure-mgmt-managementgroups python38Packages.azure-mgmt-managementpartner python38Packages.azure-mgmt-maps python38Packages.azure-mgmt-marketplaceordering python38Packages.azure-mgmt-media python38Packages.azure-mgmt-monitor python38Packages.azure-mgmt-msi python38Packages.azure-mgmt-netapp python38Packages.azure-mgmt-network python38Packages.azure-mgmt-notificationhubs python38Packages.azure-mgmt-policyinsights python38Packages.azure-mgmt-powerbiembedded python38Packages.azure-mgmt-privatedns python38Packages.azure-mgmt-rdbms python38Packages.azure-mgmt-recoveryservices python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-redhatopenshift python38Packages.azure-mgmt-redis python38Packages.azure-mgmt-relay python38Packages.azure-mgmt-reservations python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-scheduler python38Packages.azure-mgmt-search python38Packages.azure-mgmt-security python38Packages.azure-mgmt-servicebus python38Packages.azure-mgmt-servicefabric python38Packages.azure-mgmt-signalr python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-sqlvirtualmachine python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-mgmt-synapse python38Packages.azure-mgmt-trafficmanager python38Packages.azure-mgmt-web python38Packages.azure-multiapi-storage python38Packages.azure-servicebus python38Packages.azure-servicefabric python38Packages.azure-storage-blob python38Packages.azure-storage-file-share python38Packages.azure-synapse-accesscontrol python38Packages.azure-synapse-artifacts python38Packages.azure-synapse-spark python38Packages.msal python38Packages.msal-extensions python38Packages.msrest python38Packages.msrestazure python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy python38Packages.vsts python38Packages.vsts-cd-manager python39Packages.msal python39Packages.msal-extensions
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115983` at ccf841a4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>112 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/7c8603fba17d475884565758ce298139">appdaemon</a></li></li>
    <li><a href="https://gist.github.com/a5bf77089f69bf1b5528e8c868d0384a">azure-cli</a></li></li>
    <li><a href="https://gist.github.com/d6bfdd68febeaffad39d6fe91ad23608">dvc-with-remotes</a></li></li>
    <li><a href="https://gist.github.com/9a240b24e9e8b7250e4d36254e31d916">python38Packages.azure-appconfiguration</a></li></li>
    <li><a href="https://gist.github.com/3af0d15e9caed043a2840f5ddf9c255e">python38Packages.azure-applicationinsights</a></li></li>
    <li><a href="https://gist.github.com/17e57b12884a93c8b8925a3806954f32">python38Packages.azure-batch</a></li></li>
    <li><a href="https://gist.github.com/a4516ae1142423907ba61358aff585ef">python38Packages.azure-core</a></li></li>
    <li><a href="https://gist.github.com/4962e9fbce4dd6e0d7f17dacdec980a0">python38Packages.azure-eventgrid</a></li></li>
    <li><a href="https://gist.github.com/b9798d0ccee2fc4ec983a89fc629274e">python38Packages.azure-functions-devops-build</a></li></li>
    <li><a href="https://gist.github.com/00670557963a840cd6b579cf0e8e9b6c">python38Packages.azure-graphrbac</a></li></li>
    <li><a href="https://gist.github.com/6c2c53be84d64c6059611b6b2e0f7d80">python38Packages.azure-identity</a></li></li>
    <li><a href="https://gist.github.com/3debfe7dd2c88070c6e584a6beeaef05">python38Packages.azure-keyvault</a></li></li>
    <li><a href="https://gist.github.com/fac934a628e4768943be98157795b7db">python38Packages.azure-keyvault-administration</a></li></li>
    <li><a href="https://gist.github.com/1d16ab55fd2cd085a19d4407e995a326">python38Packages.azure-keyvault-certificates</a></li></li>
    <li><a href="https://gist.github.com/296028cf0032fe47aa490439fa956540">python38Packages.azure-keyvault-keys</a></li></li>
    <li><a href="https://gist.github.com/c5acfa7a6a39d96eee1e950ab4fcde70">python38Packages.azure-keyvault-secrets</a></li></li>
    <li><a href="https://gist.github.com/3c90a23cd2182da1d385796374478d4f">python38Packages.azure-loganalytics</a></li></li>
    <li><a href="https://gist.github.com/ec5f91fcb65e67f8cde0669f0cf32911">python38Packages.azure-mgmt-advisor</a></li></li>
    <li><a href="https://gist.github.com/ea0a85194255d04c3c22196bba5137e0">python38Packages.azure-mgmt-apimanagement</a></li></li>
    <li><a href="https://gist.github.com/fe23ab1dcf5afd220b863e2eb61d15b4">python38Packages.azure-mgmt-appconfiguration</a></li></li>
    <li><a href="https://gist.github.com/1955eafdc6e45482de44d9b607dbf1fb">python38Packages.azure-mgmt-applicationinsights</a></li></li>
    <li><a href="https://gist.github.com/bdc13d9d5a85a589712172b079df8487">python38Packages.azure-mgmt-authorization</a></li></li>
    <li><a href="https://gist.github.com/9c7427a9f00bc33b1b3024a4c8348a32">python38Packages.azure-mgmt-batch</a></li></li>
    <li><a href="https://gist.github.com/ab2439ef062d9a9b1060ec2bc31eed7d">python38Packages.azure-mgmt-batchai</a></li></li>
    <li><a href="https://gist.github.com/152910b121cbddb1e71e15ec21ec9276">python38Packages.azure-mgmt-billing</a></li></li>
    <li><a href="https://gist.github.com/365fd403e7877426d20dbe7cc01a818c">python38Packages.azure-mgmt-botservice</a></li></li>
    <li><a href="https://gist.github.com/9c595871823bb809dc26cd02e19db121">python38Packages.azure-mgmt-cdn</a></li></li>
    <li><a href="https://gist.github.com/d01d146e27c4b75030885a785b16f3d0">python38Packages.azure-mgmt-cognitiveservices</a></li></li>
    <li><a href="https://gist.github.com/35c146b13f56324b17dc1620819796ff">python38Packages.azure-mgmt-commerce</a></li></li>
    <li><a href="https://gist.github.com/6e24dbcc6a6d086ace4c9e34cd46fb4a">python38Packages.azure-mgmt-common</a></li></li>
    <li><a href="https://gist.github.com/85dbe6770e8dcd66b2b4616f5ea1d7a6">python38Packages.azure-mgmt-compute</a></li></li>
    <li><a href="https://gist.github.com/9f66adb50c3548b4bc1f03fbf7bff161">python38Packages.azure-mgmt-consumption</a></li></li>
    <li><a href="https://gist.github.com/ff5d07648292e30093fc1c6019d56a35">python38Packages.azure-mgmt-containerinstance</a></li></li>
    <li><a href="https://gist.github.com/11b28dfc80a6f25c3696be0261ac3bd6">python38Packages.azure-mgmt-containerregistry</a></li></li>
    <li><a href="https://gist.github.com/ebae1b5a5dbd34864ece7b4bd81130cb">python38Packages.azure-mgmt-containerservice</a></li></li>
    <li><a href="https://gist.github.com/72a3d6dcac8fbf900953311c7a6bbd0c">python38Packages.azure-mgmt-core</a></li></li>
    <li><a href="https://gist.github.com/5444e28a5dea7234c9bc676f883d0de8">python38Packages.azure-mgmt-cosmosdb</a></li></li>
    <li><a href="https://gist.github.com/95b01821c571fd134649e0ac3e98f790">python38Packages.azure-mgmt-databoxedge</a></li></li>
    <li><a href="https://gist.github.com/f47c8f8ab13c8e00389a61aab64b4e0c">python38Packages.azure-mgmt-datafactory</a></li></li>
    <li><a href="https://gist.github.com/bb8423f3c0e58a672936fd8b7f8ab75e">python38Packages.azure-mgmt-datalake-analytics</a></li></li>
    <li><a href="https://gist.github.com/f10afc5c4dc321162da63efeeaa1024d">python38Packages.azure-mgmt-datalake-store</a></li></li>
    <li><a href="https://gist.github.com/03c59ec2a1eb311a3fb9663288bb3e29">python38Packages.azure-mgmt-datamigration</a></li></li>
    <li><a href="https://gist.github.com/fb23817bbe8ce22c2153a23647bc7067">python38Packages.azure-mgmt-deploymentmanager</a></li></li>
    <li><a href="https://gist.github.com/9cdf8955cbf94dd4db895d0622794347">python38Packages.azure-mgmt-devspaces</a></li></li>
    <li><a href="https://gist.github.com/3fa668017a1f371f87bb7ff0ffda26ed">python38Packages.azure-mgmt-devtestlabs</a></li></li>
    <li><a href="https://gist.github.com/3c2fa7a9395d7c581543885c2cdd002f">python38Packages.azure-mgmt-dns</a></li></li>
    <li><a href="https://gist.github.com/92a1c031f7527b75f7770826bbcaeafa">python38Packages.azure-mgmt-eventgrid</a></li></li>
    <li><a href="https://gist.github.com/9a7cf35101194877dfb27450ce107652">python38Packages.azure-mgmt-eventhub</a></li></li>
    <li><a href="https://gist.github.com/ace279324ae6d4a766f81666d3149136">python38Packages.azure-mgmt-hanaonazure</a></li></li>
    <li><a href="https://gist.github.com/22be8602794418f4f9a64c92ade817f4">python38Packages.azure-mgmt-hdinsight</a></li></li>
    <li><a href="https://gist.github.com/0e433b1123ad5ee99ee7e7fa61f09398">python38Packages.azure-mgmt-imagebuilder</a></li></li>
    <li><a href="https://gist.github.com/b3eb0f0eab08c4b880c0ad70c3dc4bfe">python38Packages.azure-mgmt-iotcentral</a></li></li>
    <li><a href="https://gist.github.com/d11a64628e7daddfc6510b331d1b3ddc">python38Packages.azure-mgmt-iothub</a></li></li>
    <li><a href="https://gist.github.com/2c357473429ddd0fcd0a5b30d171d4b7">python38Packages.azure-mgmt-iothubprovisioningservices</a></li></li>
    <li><a href="https://gist.github.com/93d70fa8b09794bdf5602e6a392d6d99">python38Packages.azure-mgmt-keyvault</a></li></li>
    <li><a href="https://gist.github.com/418f5bb6d323265436c85d48dccfdea3">python38Packages.azure-mgmt-kusto</a></li></li>
    <li><a href="https://gist.github.com/8b488b19176a65e8dc2ddb6385f695e4">python38Packages.azure-mgmt-loganalytics</a></li></li>
    <li><a href="https://gist.github.com/5ad0d912624ee81913612f37790e1465">python38Packages.azure-mgmt-logic</a></li></li>
    <li><a href="https://gist.github.com/e81d40b68ea0ddd59d40874f4a17fd08">python38Packages.azure-mgmt-machinelearningcompute</a></li></li>
    <li><a href="https://gist.github.com/f7dfa874c93c309a93f56e94e50861ac">python38Packages.azure-mgmt-managedservices</a></li></li>
    <li><a href="https://gist.github.com/55a420f0c44e731cb9af4c4c50caf878">python38Packages.azure-mgmt-managementgroups</a></li></li>
    <li><a href="https://gist.github.com/8731165dcaf6c19625d2b592aef815f8">python38Packages.azure-mgmt-managementpartner</a></li></li>
    <li><a href="https://gist.github.com/bbc2514d0236c934af86b31a53f5989d">python38Packages.azure-mgmt-maps</a></li></li>
    <li><a href="https://gist.github.com/e2e8e5cd262a922b91276b79cba140e4">python38Packages.azure-mgmt-marketplaceordering</a></li></li>
    <li><a href="https://gist.github.com/1f949d5b998833e6d5d67bb9dacde59b">python38Packages.azure-mgmt-media</a></li></li>
    <li><a href="https://gist.github.com/cbc2cc50980e0037ff609a86ab48ccee">python38Packages.azure-mgmt-monitor</a></li></li>
    <li><a href="https://gist.github.com/652c41512a79a513edcfc23df7e898dd">python38Packages.azure-mgmt-msi</a></li></li>
    <li><a href="https://gist.github.com/eb53d12c5d8e0ec213115b314fb892ec">python38Packages.azure-mgmt-netapp</a></li></li>
    <li><a href="https://gist.github.com/02d8b013c327b0ac20927c3d62cc4bba">python38Packages.azure-mgmt-network</a></li></li>
    <li><a href="https://gist.github.com/230172659809e97160b6b234e1e87902">python38Packages.azure-mgmt-notificationhubs</a></li></li>
    <li><a href="https://gist.github.com/a468381cfee999244afb7af9a7537bed">python38Packages.azure-mgmt-policyinsights</a></li></li>
    <li><a href="https://gist.github.com/98b4a73e70997b5dc7c897930aec370d">python38Packages.azure-mgmt-powerbiembedded</a></li></li>
    <li><a href="https://gist.github.com/91e9298ce7c6fef685d42311889d3ee4">python38Packages.azure-mgmt-privatedns</a></li></li>
    <li><a href="https://gist.github.com/212bf90d20c34c8ffe5636fa4d630a6a">python38Packages.azure-mgmt-rdbms</a></li></li>
    <li><a href="https://gist.github.com/6ab476d2b5d4868d0149b316ddfa3b48">python38Packages.azure-mgmt-recoveryservices</a></li></li>
    <li><a href="https://gist.github.com/2333e195f4ed35af1e56d4e827de41a9">python38Packages.azure-mgmt-recoveryservicesbackup</a></li></li>
    <li><a href="https://gist.github.com/91fc19b330fcadf08892abec82aaff05">python38Packages.azure-mgmt-redhatopenshift</a></li></li>
    <li><a href="https://gist.github.com/da58a092bf26970a45ae72ffcf8962ab">python38Packages.azure-mgmt-redis</a></li></li>
    <li><a href="https://gist.github.com/757521700c518eaf638d52382b9619b8">python38Packages.azure-mgmt-relay</a></li></li>
    <li><a href="https://gist.github.com/22296dea35e36f44f1b1272e4ee55aa0">python38Packages.azure-mgmt-reservations</a></li></li>
    <li><a href="https://gist.github.com/a327559b6ab64d7e60f06d4d796eba07">python38Packages.azure-mgmt-resource</a></li></li>
    <li><a href="https://gist.github.com/ba15bbf13ea425e88c40bc3775bdf1d1">python38Packages.azure-mgmt-scheduler</a></li></li>
    <li><a href="https://gist.github.com/63e4402fc8b2548008e1242b8b3de7d8">python38Packages.azure-mgmt-search</a></li></li>
    <li><a href="https://gist.github.com/303e05fcfdb66fdd99d360421f6a9bad">python38Packages.azure-mgmt-security</a></li></li>
    <li><a href="https://gist.github.com/676f489dfaa34c65f9f6c8df46282549">python38Packages.azure-mgmt-servicebus</a></li></li>
    <li><a href="https://gist.github.com/1d0c59d569bf3b5c57cfeecd481b4a4f">python38Packages.azure-mgmt-servicefabric</a></li></li>
    <li><a href="https://gist.github.com/726c62519b5dabfc808c3218dd85d072">python38Packages.azure-mgmt-signalr</a></li></li>
    <li><a href="https://gist.github.com/2126777a42fa07ec523c7d54d04c5698">python38Packages.azure-mgmt-sql</a></li></li>
    <li><a href="https://gist.github.com/765e5d149406a3b012da981f04930e5c">python38Packages.azure-mgmt-sqlvirtualmachine</a></li></li>
    <li><a href="https://gist.github.com/ed1d4f6047c7a99dcab41d647f76ab9d">python38Packages.azure-mgmt-storage</a></li></li>
    <li><a href="https://gist.github.com/d4525761e36b3ffa7dbded48e8275e97">python38Packages.azure-mgmt-subscription</a></li></li>
    <li><a href="https://gist.github.com/1fe078426636383875b85d87cf3db563">python38Packages.azure-mgmt-synapse</a></li></li>
    <li><a href="https://gist.github.com/c0568cb9915197dc73ceb63d2faae827">python38Packages.azure-mgmt-trafficmanager</a></li></li>
    <li><a href="https://gist.github.com/1aa5589cf3d81966ab8ae5a71c96e26c">python38Packages.azure-mgmt-web</a></li></li>
    <li><a href="https://gist.github.com/2ea8b24e8078b6fccb235c5342e74472">python38Packages.azure-multiapi-storage</a></li></li>
    <li><a href="https://gist.github.com/1592982cd66661b1388ea2a147c839d2">python38Packages.azure-servicebus</a></li></li>
    <li><a href="https://gist.github.com/c806391067bf59c9a81c5517a1e0c8a2">python38Packages.azure-servicefabric</a></li></li>
    <li><a href="https://gist.github.com/79e47f3b242e7840bea372a61421b8c7">python38Packages.azure-storage-blob</a></li></li>
    <li><a href="https://gist.github.com/d2a2c7fff5f4297e7e5de9191449ab02">python38Packages.azure-storage-file-share</a></li></li>
    <li><a href="https://gist.github.com/773813134514ad75a8746d460c6ef9dd">python38Packages.azure-synapse-accesscontrol</a></li></li>
    <li><a href="https://gist.github.com/bf548bb5ea2e53b5caa7086a0411d414">python38Packages.azure-synapse-artifacts</a></li></li>
    <li><a href="https://gist.github.com/e7185c638cccd6e0ceda1e9f4e43f6d8">python38Packages.azure-synapse-spark</a></li></li>
    <li><a href="https://gist.github.com/40e4558713b98e662728cc2db5347b6c">python38Packages.msal</a></li></li>
    <li><a href="https://gist.github.com/23f4e3c5077747b1694a719623a077c8">python38Packages.msal-extensions</a></li></li>
    <li><a href="https://gist.github.com/aa467ebac48e95d4caa97e6f9e65d529">python38Packages.msrest</a></li></li>
    <li><a href="https://gist.github.com/dc07b579316fcec4c1ed909d077f9af4">python38Packages.msrestazure</a></li></li>
    <li><a href="https://gist.github.com/cf3ac6d93c2ef97eca3e24acf4597604">python38Packages.snowflake-connector-python</a></li></li>
    <li><a href="https://gist.github.com/7339cde22123493e54d252c4d05b4a68">python38Packages.snowflake-sqlalchemy</a></li></li>
    <li><a href="https://gist.github.com/2338fe2c4ae3a078a419452bedd78db4">python38Packages.vsts</a></li></li>
    <li><a href="https://gist.github.com/3cb95869e9fda8ee50ac4c8f4d3e08c4">python38Packages.vsts-cd-manager</a></li></li>
    <li><a href="https://gist.github.com/62de09d1b2227ce1bfa864d4a42e082e">python39Packages.msal</a></li></li>
    <li><a href="https://gist.github.com/85ec4d78dc43ccf909a19cddf433b345">python39Packages.msal-extensions</a></li></li>
  </ul>
</details>
<details>
  <summary>5 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/azure-multiapi-storage/default.nix:2:3:
```
  |
2 | , fetchpatch
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `isPy3k`.
Near pkgs/development/python-modules/azure-mgmt-compute/default.nix:7:3:
```
  |
7 | , isPy3k
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/azure-mgmt-applicationinsights/default.nix:3:3:
```
  |
3 | , python
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/azure-mgmt-compute/default.nix:4:3:
```
  |
4 | , python
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/azure-multiapi-storage/default.nix:1:8:
```
  |
1 | { lib, python, buildPythonPackage, fetchPypi, isPy27
  |        ^
```
</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
it would be great if you could remove the unused inputs.

**Comment by jonringer** [comment]
applied suggestions

```
https://github.com/NixOS/nixpkgs/pull/115983

112 packages built:
appdaemon azure-cli dvc-with-remotes python38Packages.azure-appconfiguration python38Packages.azure-applicationinsights python38Packages.azure-batch python38Packages.azure-core python38Packages.azure-eventgrid python38Packages.azure-functions-devops-build python38Packages.azure-graphrbac python38Packages.azure-identity python38Packages.azure-keyvault python38Packages.azure-keyvault-administration python38Packages.azure-keyvault-certificates python38Packages.azure-keyvault-keys python38Packages.azure-keyvault-secrets python38Packages.azure-loganalytics python38Packages.azure-mgmt-advisor python38Packages.azure-mgmt-apimanagement python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-applicationinsights python38Packages.azure-mgmt-authorization python38Packages.azure-mgmt-batch python38Packages.azure-mgmt-batchai python38Packages.azure-mgmt-billing python38Packages.azure-mgmt-botservice python38Packages.azure-mgmt-cdn python38Packages.azure-mgmt-cognitiveservices python38Packages.azure-mgmt-commerce python38Packages.azure-mgmt-common python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-consumption python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerregistry python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-core python38Packages.azure-mgmt-cosmosdb python38Packages.azure-mgmt-databoxedge python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-datalake-analytics python38Packages.azure-mgmt-datalake-store python38Packages.azure-mgmt-datamigration python38Packages.azure-mgmt-deploymentmanager python38Packages.azure-mgmt-devspaces python38Packages.azure-mgmt-devtestlabs python38Packages.azure-mgmt-dns python38Packages.azure-mgmt-eventgrid python38Packages.azure-mgmt-eventhub python38Packages.azure-mgmt-hanaonazure python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-imagebuilder python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-iothub python38Packages.azure-mgmt-iothubprovisioningservices python38Packages.azure-mgmt-keyvault python38Packages.azure-mgmt-kusto python38Packages.azure-mgmt-loganalytics python38Packages.azure-mgmt-logic python38Packages.azure-mgmt-machinelearningcompute python38Packages.azure-mgmt-managedservices python38Packages.azure-mgmt-managementgroups python38Packages.azure-mgmt-managementpartner python38Packages.azure-mgmt-maps python38Packages.azure-mgmt-marketplaceordering python38Packages.azure-mgmt-media python38Packages.azure-mgmt-monitor python38Packages.azure-mgmt-msi python38Packages.azure-mgmt-netapp python38Packages.azure-mgmt-network python38Packages.azure-mgmt-notificationhubs python38Packages.azure-mgmt-policyinsights python38Packages.azure-mgmt-powerbiembedded python38Packages.azure-mgmt-privatedns python38Packages.azure-mgmt-rdbms python38Packages.azure-mgmt-recoveryservices python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-redhatopenshift python38Packages.azure-mgmt-redis python38Packages.azure-mgmt-relay python38Packages.azure-mgmt-reservations python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-scheduler python38Packages.azure-mgmt-search python38Packages.azure-mgmt-security python38Packages.azure-mgmt-servicebus python38Packages.azure-mgmt-servicefabric python38Packages.azure-mgmt-signalr python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-sqlvirtualmachine python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-mgmt-synapse python38Packages.azure-mgmt-trafficmanager python38Packages.azure-mgmt-web python38Packages.azure-multiapi-storage python38Packages.azure-servicebus python38Packages.azure-servicefabric python38Packages.azure-storage-blob python38Packages.azure-storage-file-share python38Packages.azure-synapse-accesscontrol python38Packages.azure-synapse-artifacts python38Packages.azure-synapse-spark python38Packages.msal python38Packages.msal-extensions python38Packages.msrest python38Packages.msrestazure python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy python38Packages.vsts python38Packages.vsts-cd-manager python39Packages.msal python39Packages.msal-extensions
```

**Pull request merged**
