### PR TITLE
[24.05] Various Electron backports

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

Manual backport of https://github.com/NixOS/nixpkgs/pull/319252, https://github.com/NixOS/nixpkgs/pull/319415, https://github.com/NixOS/nixpkgs/pull/336036, and https://github.com/NixOS/nixpkgs/pull/335850.

Pending on:

* https://github.com/NixOS/nixpkgs/pull/337312
* https://github.com/NixOS/nixpkgs/pull/337320
* https://github.com/NixOS/nixpkgs/pull/337777
* https://github.com/NixOS/nixpkgs/pull/337787
* https://github.com/NixOS/nixpkgs/pull/337801 and then https://github.com/NixOS/nixpkgs/pull/337947
* https://github.com/NixOS/nixpkgs/pull/337788
* https://github.com/NixOS/nixpkgs/pull/337789 and then https://github.com/NixOS/nixpkgs/pull/337949
* https://github.com/NixOS/nixpkgs/pull/337794
* https://github.com/NixOS/nixpkgs/pull/337797
* https://github.com/NixOS/nixpkgs/pull/338089

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
This actually also marks 27 and 28 as EOL, which are used by the following packages that don’t use them on `master`s:

* `blockbench`
* `lx-music-desktop`
* `ride`
* `feishin`
* `obsidian`
* `webtorrent_desktop`

So there’s some more backporting work to do here. I’ll go PR‐hunting in a bit, but I’d appreciate some help.

**Comment by emilazy** [comment]
(Also I do need to actually either backport the removals or mark the source packages as vulnerable too, of course… Drafting this for now.)

**Comment by emilazy** [comment]
Okay, I *think* I have all the relevant Electron commits in this now, but it could definitely use double‐checking…

I’ll work on getting the PRs for the software this would break backported.

**Comment by emilazy** [comment]
Final diff of the Electron directory compared to `master` now looks benign:

```diff
diff --git a/pkgs/development/tools/electron/binary/default.nix b/pkgs/development/tools/electron/binary/default.nix
index 07637d13e9..b884428cf8 100644
--- a/pkgs/development/tools/electron/binary/default.nix
+++ b/pkgs/development/tools/electron/binary/default.nix
@@ -1,11 +1,8 @@
-let
-  infoJson = builtins.fromJSON (builtins.readFile ./info.json);
-in
-
 { lib, callPackage }:
 
 let
   mkElectron = callPackage ./generic.nix { };
+  infoJson = builtins.fromJSON (builtins.readFile ./info.json);
 in
 lib.mapAttrs' (majorVersion: info:
   lib.nameValuePair
diff --git a/pkgs/development/tools/electron/common.nix b/pkgs/development/tools/electron/common.nix
index 1e86382771..311757ae1b 100644
--- a/pkgs/development/tools/electron/common.nix
+++ b/pkgs/development/tools/electron/common.nix
@@ -16,7 +16,7 @@
 , pipewire
 , libsecret
 , libpulseaudio
-, speechd-minimal
+, speechd
 , info
 }:
 
@@ -49,7 +49,7 @@
 
   src = null;
 
-  patches = base.patches ++ lib.optional (lib.versionOlder info.version "30")
+  patches = base.patches ++ lib.optional (lib.versionAtLeast info.version "29" && lib.versionOlder info.version "30")
     (substituteAll {
       # disable a component that requires CIPD blobs
       name = "disable-screen-ai.patch";
@@ -171,8 +171,10 @@
     use_qt = false;
     v8_builtins_profiling_log_file = "";
     enable_dangling_raw_ptr_checks = false;
+  } // lib.optionalAttrs (lib.versionAtLeast info.version "28") {
     dawn_use_built_dxc = false;
     v8_enable_private_mapping_fork_optimization = true;
+  } // lib.optionalAttrs (lib.versionAtLeast info.version "29") {
     v8_expose_public_symbols = true;
   } // lib.optionalAttrs (lib.versionOlder info.version "31") {
     use_perfetto_client_library = false;
@@ -204,7 +206,7 @@
         stdenv.cc.cc.lib
         libsecret
         libpulseaudio
-        speechd-minimal
+        speechd
       ];
     in
   base.postFixup + ''
```

**Comment by emilazy** [comment]
Okay, I think I tracked down all the relevant PRs to backport. Still some manual ones to tackle and they all need review.

**Comment by emilazy** [comment]
> Final diff of the Electron directory compared to `master` now looks benign:

Or not! Guess I have to backport that change too. I’ll do it tomorrow.

**Comment by emilazy** [comment]
This should actually work now. Apologies for my sloppiness; this is my first time working with the Electron packages.

**Comment by emilazy** [comment]
This should be ready now.

**Comment by teutat3s** [comment]
I'll build this branch on my tower and report back with test results.

**Comment by teutat3s** [comment]
Result of `nixpkgs-review pr 337776` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>electron_27</li>
    <li>electron_28</li>
    <li>electron_29</li>
    <li>electron_29-bin</li>
    <li>kuro</li>
    <li>logseq</li>
    <li>micropad</li>
    <li>passky-desktop</li>
    <li>pocket-casts</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>antares</li>
    <li>deltachat-desktop</li>
    <li>electron-chromedriver_29</li>
    <li>electron-chromedriver_30</li>
    <li>electron_30</li>
    <li>electron_30-bin</li>
    <li>feishin</li>
    <li>lx-music-desktop</li>
    <li>morgen</li>
    <li>teams-for-linux</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
  </ul>
</details>

**Review by teutat3s — APPROVED** [review]

**Comment by emilazy** [comment]
Thanks for checking!

is it expected that `electron-chromedriver_29` isn’t marked as vulnerable? Not really relevant to this PR, though, since it shouldn’t be any different on `master`.

**Pull request merged**
