### PR TITLE
mastodon: create missing static gzip and brotli files

### PR DESCRIPTION
**Pull request by Izorkin**
###### Description of changes
Static gzip files are generated during build of mastodon package, but not for all files. This PR adds creation of missing static files.
Also added support for brotli compression, PR in mastodon - https://github.com/mastodon/mastodon/pull/19025

сс @happy-river @erictapen

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tpwrules** [comment]
You should pass `-n` as well to gzip so it avoids writing the timestamp and the output files are reproducible.

**Comment by Izorkin** [comment]
> You should pass `-n` as well to gzip so it avoids writing the timestamp and the output files are reproducible.

Thanks, update PR.

**Comment by erictapen** [comment]
Thanks.

Do I understand it right that upstream https://github.com/mastodon/mastodon/pull/19025 and this PR are mutually exclusive? If yes I'd rather wait for wether upstream's PR gets merged or not before reviewing this one.

Also I think if either of the two would get merged, we'd need the appropriate nginx config. Could you add that to the module?

**Comment by Izorkin** [comment]
These PRs complement each other.

I'm currently create PR for add brotli compression in nginx.

**Comment by Izorkin** [comment]
Small update and rebased PR.

**Comment by Izorkin** [comment]
Updated and rebased PR.

**Comment by Izorkin** [comment]
> I'm struggling to see how this fixes a NixOS specific problem? Wouldn't this better entirely solved on upstreams side, as you are already partly doing?

I added a PR to upstream to compress files into brotli format. But the scripts in upstream do not compress all files. Сurrent PR adds compression to missing files.

**Comment by erictapen** [comment]
But why wouldn't upstream compress all files? Shouldn't they fix the problem?

**Comment by Izorkin** [comment]
Judging by fact that PR has not yet been adopted, they have little interest in adding such a optimization :( . If you want, service administrator can do it himself. And this optimization will increase installation time of mastodon service.
In our case the package is built once in hydra.

**Comment by Izorkin** [comment]
@erictapen necessary changes have been added to the upstream.
Nothing needs to be changed in this PR, it supplements the changes added to upstream.

**Comment by Izorkin** [comment]
cc @erictapen

**Pull request merged**
