### PR TITLE
metasploit: 6.2.16 -> 6.2.22

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Update to latest upstream release 6.2.22

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by viraptor** [comment]
Both ofborg and me locally are failing on the sqlite3 gem:
```
/nix/store/jm84vm3bmb81kyq435iiqcm3zid9h9vp-ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- mini_portile2 (LoadError)
        from /nix/store/jm84vm3bmb81kyq435iiqcm3zid9h9vp-ruby-2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from extconf.rb:2:in `<main>'
```
Probably not a metasploit issue itself, but stops me from testing. Checking it now...

**Comment by viraptor** [comment]
So the new gemset is not correct. sqlite3 depends on mini_portile2 now. With the dependency added, we get:
```
Building sqlite3-ruby using packaged sqlite3.
2 retrie(s) left for sqlite-autoconf-3390300.tar.gz (Failed to open TCP connection to www.sqlite.org:443 (getaddrinfo: nodename nor servname provided, or not known))
1 retrie(s) left for sqlite-autoconf-3390300.tar.gz (Failed to open TCP connection to www.sqlite.org:443 (getaddrinfo: nodename nor servname provided, or not known))
0 retrie(s) left for sqlite-autoconf-3390300.tar.gz (Failed to open TCP connection to www.sqlite.org:443 (getaddrinfo: nodename nor servname provided, or not known))
Failed to open TCP connection to www.sqlite.org:443 (getaddrinfo: nodename nor servname provided, or not known)
*** extconf.rb failed ***
```
🤦
Sqlite3 gem will need some fixing up.

**Review by viraptor — DISMISSED** [review]
sqlite3 update needs the new dependencies in the gemset.nix + a general fix for the portile online dependency.

**Comment by viraptor** [comment]
sqlite gem fixed in https://github.com/NixOS/nixpkgs/pull/190740 but gemset needs to be updated in this PR

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 190704` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>metasploit</li>
    <li>msfpc</li>
    <li>social-engineer-toolkit</li>
  </ul>
</details>

**Comment by fabaff** [comment]
@ofborg build metasploit msfpc social-engineer-toolkit

**Pull request merged**
