### PR TITLE
qt5.15: refresh patches

### PR DESCRIPTION
**Pull request by K900**
Fixes a bunch of minor annoyances, especially around Wayland.

###### Description of changes

Random assortment of interesting bits:
- https://invent.kde.org/qt/qt/qtbase/-/commit/f7c455bfc88986aea55142cc0890042dbbe1321f
- https://invent.kde.org/qt/qt/qtbase/-/commit/ec68c541a72bde122a1ab5ba89f41b58c370537f
- https://invent.kde.org/qt/qt/qtbase/-/commit/d2068a8108c9ba0168c6f107d2e000c40bd23bdf
- https://invent.kde.org/qt/qt/qtwayland/-/commit/cc377a1dda41d4b668e2aa28b60788f026ef2b7b

And a whole pile of crash fixes.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ttuegel** [comment]
Did you check the version number? I think the KDE patches have been updated to Qt 5.15.5 and we should change the version in `srcs.nix` accordingly.

**Comment by K900** [comment]
I don't think they rebase on top of it, but they seem to have merged it. I'll update the version number in a bit.

**Comment by K900** [comment]
Updated.

**Comment by K900** [comment]
Oops. Fixed eval.

**Comment by K900** [comment]
@ttuegel anything else? I want to get this into yesterday's staging-next.

**Comment by K900** [comment]
I'm just going to make an executive decision and merge this since I just made the next staging cycle much worse with #181198.

**Comment by K900** [comment]
I pushed a fix to -next, are you on the latest commit?

**Pull request merged**
