### PR TITLE
fancontrol: restart service after suspend

### PR DESCRIPTION
**Pull request by eliandoran**
###### Description of changes

A change was done to fancontrol to restart the service in case of failure ([#144210](https://github.com/NixOS/nixpkgs/pull/144210/commits)), however there seem to still be some cases in which fancontrol does not recover properly after stand-by.

According to a comment in [lm-sensors/#172](https://github.com/lm-sensors/lm-sensors/issues/172#issuecomment-674509161), the issue is caused by one of `/sys/class/hwmon/hwmon[n]/pwm[n]_enable` files which change their value from 1 to some other value, indicating a potential kernel/driver problem. The solution is to simply restart fancontrol after sleep, which will cause it to reset the `pwm_enable` flags correctly.

This is done by ~creating a new service (`fancontrol-restart-on-suspend`)~ using `resumeCommands`, which restarts the `fancontrol` service.

Combined with the change with [#144210](https://github.com/NixOS/nixpkgs/pull/144210/commits), most issues regarding fancontrol not recovering after suspend should be solved.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eliandoran** [comment]
@evils , could you please review this PR?

As maintainer (and also #144210), let me know if the implementation is OK for you. If the restart of the service might be a problem, we might put it behind a separate option (e.g. `options.hardware.fancontrol.restart-after-suspend`).

**Comment by evils** [comment]
i'll give it a try tomorrow
i did the restart on-failure because it failed to resume after waking my desktop `systemctl suspend`
i'm slightly surprised that that doesn't cover your stand-by case,
but i guess that's just the perils of partially stopping a system xD

i'm also a bit surprised that there's no more direct way to restart a service after suspend
but if this is the best way, then so be it

do maybe add a comment about why we want to restart it after a suspend

**Comment by evils** [comment]
my fans recovered to their set speed after waking `systemctl suspend` with this change (so it didn't break my use case :)

image

**Comment by eliandoran** [comment]
> i'll give it a try tomorrow i did the restart on-failure because it failed to resume after waking my desktop `systemctl suspend` i'm slightly surprised that that doesn't cover your stand-by case, but i guess that's just the perils of partially stopping a system xD
> 
> i'm also a bit surprised that there's no more direct way to restart a service after suspend but if this is the best way, then so be it
> 
> do maybe add a comment about why we want to restart it after a suspend

Thank you for testing and the feedback. Unfortunately this was the only way to have my fans work after resuming from stand-by. I've added a comment, as well as improved the description of the service a little bit.

**Comment by eliandoran** [comment]
> would this not be done better with a systemd-suspend hook, possible even added to the lm_sensors package with a patch?

@pennae , you're right. It would be better to implement it as a `systemd-suspend` hook. I've found some documentation on how to write the hook, but the only constraint I'm seeing is that I don't know where exactly to define the hook.

I've found in [NixOS Wiki](https://nixos.wiki/wiki/Power_Management) that there is an option called `powerManagement.resumeCommands` which seems to do exactly what we need.

@evils , @pennae , please re-review.

**Review by evils — APPROVED** [review]
thanks

**Pull request merged**
