### PR TITLE
Fix futhark build on Darwin

### PR DESCRIPTION
**Pull request by jacereda**
###### Motivation for this change

Futhark won't build on Darwin and there's duplication (obsolete non-hackage package).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by peti — APPROVED** [review]
:+1:

**Comment by basvandijk** [comment]
Thanks. The following runs successfully on my Mac Book Pro:

```
$(nix-build -A haskellPackages.futhark)/bin/futhark --version
Futhark 0.8.1
git: UNKNOWN @ UNKNOWN (UNKNOWN)
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by Infinisil** [comment]
Can it compile anything on Darwin though? Just run through the first example on https://futhark-lang.org/examples.html

And what was the error on Darwin?

**Comment by jacereda** [comment]
Works for me with the OpenCL backend. Keep in mind you need to pass arguments on stdin.

**Comment by Infinisil** [comment]
Odd, because the wrapping thing is not present at all on Darwin now, no idea how it can still work.

**Comment by jacereda** [comment]
I don't know what you mean, can you elaborate?

**Comment by Infinisil** [comment]
The line in this PR makes it such that on Darwin it uses the unwrapped Futhark package. The wrapping logic under that line will only be applied on non-Darwin. And I added that logic down there to make compiling work, because it didn't work if it wasn't wrapped properly.

**Comment by jacereda** [comment]
Have you tried it on Darwin? What's the error?

**Comment by Infinisil** [comment]
Um, I thought you were on Darwin, because I asked earlier whether it worked on Darwin and you replied that it does..

**Comment by jacereda** [comment]
I'm on Darwin and it does work for me, I was just asking if it was different for you.

The wrapper isn't needed on Darwin. There's no ocl-icd and everything should be available through OpenCL.framework.

**Comment by Infinisil** [comment]
Oh I see, no I'm not on darwin.

@jacereda Do you have `gcc` or `clang` in your `PATH` though? Because that's another thing the wrapper does for you. Try compiling a Futhark program with `export PATH=""` beforehand

**Comment by jacereda** [comment]
It's finding impure dependencies, it will run if you leave /usr/bin in the path.

**Comment by Infinisil** [comment]
Yeah but we don't want impure dependencies in Nix. If somebody doesn't have gcc/clang installed, the program should still run.

**Pull request merged**
