### PR TITLE
blesh: unstable-2022-07-24 -> unstable-2022-07-29, refactor

### PR DESCRIPTION
**Pull request by tars0x9752**
###### Description of changes

**Update**: unstable-2022-07-24 -> unstable-2022-07-29.

**Refactor**: AFAIK it's better to avoid using `leaveDotGit` if it's possible. Because it looks like `leaveDotGit` can potentially break the determinism of the hash.  see: https://github.com/NixOS/nixpkgs/issues/8567#issuecomment-133409465

As for blesh, it require `.git` in build phase but there are pre-built universal tarball releases to begin with, so I think we can use that to avoid build phase and use of `leaveDotGit`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tars0x9752** [comment]
@aiotter 
Hi, Could I have a review? (I'm not trying to rush, just wanted to send you a notice in case you haven't noticed yet.)

As a side note, I found that the current `ble.sh` has a small problem with the `nix develop` command and I made a patch for it. I'll include it in this PR if it's ok. So let me know if you'd like me to do so. More details: https://discourse.nixos.org/t/nix-print-dev-env-command-shows-some-assinments-to-readonly-variables/20916

**Comment by akinomyoga** [comment]
Honestly, I feel that https://github.com/NixOS/nix/pull/6800 must be the right fix.

I'm afraid that the idea that the attempt to overwrite `EPOCHREALTIME` is for reproducibility purposes, which was presented in another thread, is totally wrong. It has never worked because just assigning the value to `EPOCHREALTIME` doesn't have any effect in Bash; the variable should be unset prior to the assignment. If the attempt were on purpose, it shouldn't have been left broken. If one would like to freeze the timestamp embedded in the build results, one should actually set the clock of the host container or system. Even if one correctly unsets and resets EPOCHREALTIME, the result of the `date` command or syscalls wouldn't be affected. I must say it is highly uncommon to use Bash's EPOCHREALTIME to retrieve the timing information used for the builds.

In addition, ble.sh uses the dynamical aspect of EPOCHREALTIME for task scheduling. If it becomes constant, `auto-complete` and `menu-filter` will not function as expected. Anyway, I generally believe that trying to unset and reset EPOCHREALTIME to make it constant is wrong. The reason that I make the variable readonly is to prevent other codes from doing something wrong. In the present case, the problem doesn't arise immediately because `nix develop` doesn't unset the variable, but removing the check could allow some other codes unsetting EPOCHREALTIME.

**Comment by tars0x9752** [comment]
Oh, I was just about to ask you as well and I didn't expect a reply from you. Thanks for the reply!

I basically have the same opinion as you do.  Assigning the value to `EPOCHREALTIME` makes no sense and I guess quite a few people (or maybe zero people) unset `EPOCHREALTIME`. 

However, I think `nix develop` command's behavior should be discussed at NixOS/Nix repostiory and what we should do is how to deal with it (or do nothing) as a package of the Nix/nixpkgs ecosystem. 

The problem is that regardless of whether the behavior of the `nix develop` command is changed or not, the current `nix develop` command gives a warning when it's used with `ble.sh`. And the users can be confused as to why the warning is given in the first place and it could make users to spend all day debugging. (as I did.)

My idea is that it would be more user-friendly to just silence the warning by patching and remove the readonly. Because I assume it's highly uncommon to unset `EPOCHREALTIME` in the first place, as you say. So almost no one gonna unset `EPOCHREALTIME` I guess. And adding a notice like `do not unset EPOCHREALTIME. it will break ble.sh` in README for Nix users would be a compromise for the readonly role. (NOTE: I'm only talking about the nixpkgs's `ble.sh` here, the original `ble.sh` itself should keep the readonly flag.) 

These are my thoughts. Cheers!

---

(A little side-note: Since Bash does not have readonly on it by default, it's possible to unset it in plain Bash even if it's not a good idea. So actually we really need to think carefully about what `nix develop` should behave since `nix develop` is not a opinionated command I think.)

**Comment by aiotter** [comment]
Sorry for a late reply, I wasn't available for a while.
The only thing I worry about is the availability of the tarball. Are you sure that the tarball for `https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly-20220729+a22e145.tar.xz` is available after a new nightly version is released?

**Comment by tars0x9752** [comment]
Thanks for the reply! No need to be sorry. :) 

From what I understand, the contents of `ble-nightly.tar.xz` is kept updated for every nightly build, But `ble-${{ env.blesh_build_pkgver }}.tar.xz` is a permalink and it will not change.

> source code: https://github.com/akinomyoga/ble.sh/blob/a22e14578bb4664ee20fb9e32d1086f386b9853b/.github/workflows/build.yml#L28

So, If I'm not mistaken, the link `https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly-20220729+a22e145.tar.xz` here is a permalink and will not be updated even if a new nightly version is released.

Sorry, I don't remember why I removed check phase here...(maybe a mistake.) I'll put it back anyway.

I'm still new to nixpkgs contributions, so let me know if there's anything weird or missing!

**Comment by ryanong** [comment]
yea, I'm not interested in re-opening it. It seems like you all have better context on the specific error than me anyway. I just got warnings when using it in zsh but didn't actually prevent anything from happening.

**Comment by akinomyoga** [comment]
> yea, I'm not interested in re-opening it. It seems like you all have better context on the specific error than me anyway. I just got warnings when using it in zsh but didn't actually prevent anything from happening.

Thanks for your reply! OK, I think maybe we need someone from the upstream Nix who is familiar with the backgrounds of saved environment/shell variables.

**Comment by tars0x9752** [comment]
Ok, I'm not going to include the patch in this PR and I'll try to send an issue or PR to the NixOS/Nix repository first!

**Comment by tars0x9752** [comment]
FYI:
You may have already noticed, but I had sent an issue and it was fixed immediately. :+1: 

https://github.com/NixOS/nix/pull/6944

**Review by aiotter — APPROVED** [review]
Code LGTM and seems to work properly on macOS x86_64

**Comment by tars0x9752** [comment]
Thanks for checking!

**Comment by aiotter** [comment]
Can anyone merge this PR? Is there something I can do for merging?

**Comment by akinomyoga** [comment]
@tars0x9752 Could you consider the fix of the installation path discussed in the thread https://github.com/nix-community/home-manager/pull/3238#discussion_r985022732 within this PR? What do you think?

**Comment by tars0x9752** [comment]
Oh, Thanks for letting me know! I agree. It should be fixed and I'll do that when I have time. (In fact, I've even used that path in my previous personal [settings](https://github.com/tars0x9752/home/blob/93ce2b5ea273c129c2bd0bc460dd825614013e40/modules/blesh/default.nix#L13).)

**Comment by tars0x9752** [comment]
Fixed and tested on my x86-64 linux machine. :+1:

(Note: I noticed that `blesh-share` previously pointed to the actuall `ble.sh` script file itself instead of the blesh shared folder, but now it points to the blesh shared folder as intended in the comment.

**Review by aiotter — APPROVED** [review]

**Review by akinomyoga — APPROVED** [review]

**Comment by aiotter** [comment]
By the way, I'm using different approach for removing dependency on `.git` directory on my flake file for ble.sh.
Just removing `git submodule update` instruction from makefile in `patchPhase` like this:

```nix
{
  patchPhase = ''
    sed -iE "/git submodule update/d" GNUmakefile
  '';
}
```

I'm not strongly suggesting to move to this approach. Sorry for getting back to the start of this discussion.
One of the pros of this approach is that we can use test phase from makefile. And that of cons is slower time of installation.
It might be better to use a standard patch file from `diff` instead of `sed`.

Does anyone have some thoughts about this? If nobody does, let's go with the current PR.

**Comment by akinomyoga** [comment]
Maybe I can just drop the dependency on `contrib/.git` in the upstream ble.sh. Instead, we can rely on `contrib/contrib.mk`, and actually the current `GNUmakefile` already depends on `contrib/contrib.mk` through the `include` directive.

However, even though we can drop the dependency on `contrib/.git`, `make` still depends on `.git` of the main repository to determine the hash in the version string such as `xxxxxxx` in `0.4.0-devel3+xxxxxxx`.

----

```bash
    sed -iE "/git submodule update/d" GNUmakefile
```

I'm not sure if it is intensional, but the option `-iE` means "*to create a backup file suffixed with `E` and rewrite the file in-place*" (the backup is `GNUmakefileE` in this case). To begin with, `-i` is supported by GNU/BSD sed (with slightly different treatments of the option argument) but not specified by POSIX. I heard the option `-E` of `sed` is in the draft of the next POSIX standard (but somehow I don't have an access to the draft even though I registered myself to the Austing Group mailing list).

**Comment by aiotter** [comment]
It builds without error, and the version string becomes `0.4.0-devel3+` without git. But if this behaviour differs between systems, installing from release seems better.
And no, sed options are not being as intended. `sed -i "" "/git submodule update/d" GNUmakefile` would be correct.

**Comment by akinomyoga** [comment]
> It builds without error, and the version string becomes `0.4.0-devel3+` without git.

The empty hash is unexpected. This has been *just unchecked*, but I'll make it an explicit build error in the next push to the master (cf [`d3a33afd`](https://gitlab.com/akinomyoga/ble.sh/-/commit/d3a33afdfbb1fca6686330c7b336ec7e7d399a62) in the `dev` branch). Also, the commit will drop the build dependency on `contrib/.git`.

**Comment by aiotter** [comment]
Nice. Then the current approach is the best.
Now that `make test` runs not only for Linux but for macOS on GitHub Actions, the lacking tests here produces little concern.
I think this PR is ready to merge.

**Comment by akinomyoga** [comment]
@tars0x9752 @laalsaas I'm not sure why #202369 is merged earlier than this PR, but [this line](https://github.com/NixOS/nixpkgs/blob/d9eb31888b999815e35d9f9d28ef6a0fa51ba993/nixos/modules/programs/bash/blesh.nix#L12) should also be fixed within this PR or in a later one. The current configuration that the script file `ble.sh` and related files are directly put under the data directory `<prefix>/share` is wrong. They will be moved under `<prefix>/share/blesh` by this PR.

@SuperSandro2000 Can you tell what is blocking this PR?

**Comment by tars0x9752** [comment]
I've been away from this for the last few months, so I don't know much about what has happened recently. (Actually I thought this PR wasn't blocked and simply that the maintainer was busy.) Should I check some other PRs besides #202369? 

Also, the upstream blesh version is quite advanced because it has been quite some time since I opened this PR. So closing this PR and make a new PR with the current latest blesh version might be an option. Let me know if I should do so.

**Comment by SuperSandro2000** [comment]
You can just force push an update into this PR, no need to open another one.

**Comment by SuperSandro2000** [comment]
> is merged earlier than this PR

Because the author asked me to review it and there was nothing blocking from being merged.

**Review by SuperSandro2000 — APPROVED** [review]

**Review by aiotter — APPROVED** [review]

**Review by akinomyoga — APPROVED** [review]

**Comment by akinomyoga** [comment]
Thank you for updating the PR to include the update in `nixos/modules/programs/bash/blesh.nix`!

> > Should I check some other PRs besides #202369?
> 
> I cannot answer that for you because I do not keep track of everything that is changing.

#202369 is actually a rework of #201345. Other than that, there are no changes that are directly related to ble.sh.

**Comment by akinomyoga** [comment]
Thanks!

**Pull request merged**
