### PR TITLE
globalprotect-openconnect: use ver rev instead of commit & correct sh…

### LINKED ISSUE #148378: globalprotect-openconnect package installs wrong version
### Describe the bug
globalprotect-openconnect has latest version 1.3.4 on https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=globalprotect-openconnect
but when I try to install it I got version 1.2.5

### Steps To Reproduce
nix-env -iA nixos.globalprotect-openconnect

### Expected behavior
Install latest version 

### Screenshots
image

### Notify maintainers
@jerith666 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[roworu@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.333896.a640d8394f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

That my first time reporting issues, so please tell me if any additional info need to be provided.

### PR DESCRIPTION
**Pull request by Artturin**
…a256

###### Motivation for this change
Closes https://github.com/NixOS/nixpkgs/issues/148378

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jerith666** [comment]
Thanks, will test at work today and report back!

**Review by jerith666 — APPROVED** [review]
Works great to connect to my corporate VPN!

I'm curious why you changed from `qmake` to `cmake` & if that's why the `substituteInPlace` stuff is no longer necessary, but that's just for my own edification -- I checked the resulting files and they definitely point into the store where they should.

**Comment by Artturin** [comment]
> I'm curious why you changed from `qmake` to `cmake` & if that's why the `substituteInPlace` stuff is no longer necessary, but that's just for my own edification -- I checked the resulting files and they definitely point into the store where they should.

The project switched to cmake and at the same time fixed the paths by making cmake set them

**Comment by roworu** [comment]
Thank you so much for quick fix!

**Comment by Artturin** [comment]
> Thank you so much for quick fix! Does it mean, that it is possible now to install latest version of globalprotect-openconnect ? Because I just tried and got v1.2.5 again :(
> 
> @jerith666
> 
> > Works great to connect to my corporate VPN!

this pr https://nixpk.gs/pr-tracker.html?pr=148381

the backport pr https://nixpk.gs/pr-tracker.html?pr=148527

**Pull request merged**
