### PR TITLE
wapiti: 3.1.7 -> 3.1.8

### PR DESCRIPTION
**Pull request by tjni**
## Description of changes

https://github.com/wapiti-scanner/wapiti/compare/3.1.7...3.1.8

The goal is to pick up upstream's change to `pyproject.toml`, which fixes a bug involving duplicate scripts breaking [`installer`](https://installer.pypa.io/en/stable/) when it installs the wheel.

A couple of other changes are needed to dependencies (which I audited from the new pyproject.toml). One thing to call out is that there is a new extra called `ssl` which I could not add because it depends on `sslyze`, which depends on `nassl` and tries to download OpenSSL and build it from source. It's more work than I have time for to untangle that right now.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
@ofborg build wapiti

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 250814` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>

**Comment by tjni** [comment]
Wow, thank you for checking. I think this slipped through because I was testing on aarch64-darwin, and when the hole is punched through the sandbox for localhost, it might also allow arbitrary DNS lookups?

Essentially, [this line](https://github.com/wapiti-scanner/wapiti/blob/e076399f887d340e55e17cb009b88f2401460989/wapitiCore/attack/mod_log4shell.py#L38) creates the `_dns_host` property:
```
try:
    self._dns_host = socket.gethostbyname(dns_endpoint)
except (OSError, TypeError):
    logging.error(f"Error: {dns_endpoint} is not a valid domain name")
    self.finished = True
```
and the new test `test_attack_unifi` is trying to resolve `http://perdu.com/`. I will disable the test.

**Comment by tjni** [comment]
@ofborg build wapiti

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 250814` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
