### PR TITLE
tmuxPlugins.onedark-theme: fix entrypoint

### PR DESCRIPTION
**Pull request by andyrichardson**
###### Motivation for this change

Currently, the resulting target file `/nix/store/zrv5g7p1sy3b59dasxb9sqmr8c9v5lly-tmuxplugin-onedark-theme-unstable-2020-06-07/share/tmux-plugins/onedark-theme.tmux` doesn't exist.

This is because the tmux file name is incorrect.

Current: `onedark-theme.tmux`

Actual: [`tmux-onedark-theme.tmux`](https://github.com/odedlaz/tmux-onedark-theme/blob/master/tmux-onedark-theme.tmux)

CC @sherubthakur @SuperSandro2000

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please change the commit message and PR title to ``tmuxPlugins.onedark-theme: fix entrypoint``

**Comment by austinbutler** [comment]
Was wondering what I had done wrong when the theme didn't take effect. This fix works for me, thanks.

@andyrichardson it seems you've only fixed the PR title and not the commit message, would you please update that?

**Comment by andyrichardson** [comment]
Hey sorry I haven't had time to get around to this yet - my contribution was a 5s change via the site!

Pulling the repo and changing the commit message is a little more involved 😅 will sort it out later but feel free to make another PR and merge the fix if you want 👍

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107817` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>tmuxPlugins.onedark-theme</li>
</ul>
</details>

**Pull request closed without merging**
