### PR TITLE
atom: 1.6.2 -> 1.7.3

### PR DESCRIPTION
**Pull request by romildo**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Please run the resulting Atom. I suspect it will not work. It never has for me anyways.

**Comment by romildo** [comment]
@NeQuissimus It works for me.

**Comment by NeQuissimus** [comment]
@romildo Are you installing this in a fresh environment? If I merge this into my master, Atom starts but will only display a white screen.

**Comment by romildo** [comment]
I have applied the patch on my local copy of the master branch of the `nixpkgs` repository, built with the command

    $ nix-build --option build-use-chroot true -K -A atom

and run with

    $ result/bin/atom pkgs/applications/editors/atom/default.nix

atom-1 7 3 screenshot

**Comment by jagajaga** [comment]
@NeQuissimus worked for me too :)

**Comment by NeQuissimus** [comment]
Must be my environment then, I shall look into this...

**Comment by NeQuissimus** [comment]
@romildo Are you familiar with where Atom drops its data?
I even created a new user to have an empty home directory and this version of Atom still shows an empty screen with "Error: Module did not self-register." in the error console...
I am wondering if Atom has data somewhere outside `~`...

**Comment by romildo** [comment]
@NeQuissimus Sorry, I am not.

**Pull request merged**
