### PR TITLE
libaom: 1.0.0-errata1 -> 2.0.0

### PR DESCRIPTION
**Pull request by primeos**
###### Testing

Tested using `ffmpeg-full` as well as `aomenc` and `aomdec` directly, LGTM.

###### Motivation for this change

There's finally a new release :)

> 2020-05-07 v2.0.0 "Applejack"
>   First official release of libaom.
>   This release includes new real-time mode and SVC support.
> 
>   - Upgrading:
>     AOM_SET_POSTPROC, AOM_CODEC_CAP_POSTPROC and AOM_CODEC_USE_POSTPROC are
>     removed.
> 
>     AOM_SET_DBG_* is removed.
> 
>     Multi-resolution encoding is removed.
> 
>     put_frame and put_slice callbacks are removed.
> 
>   - Enhancements:
>     Full-sweep document update for codec controls.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by kiloreux — APPROVED** [review]

**Comment by primeos** [comment]
@orivej-nixos did you test your changes and will you merge this PR? Please don't just add commits without any comment.

And FYI: Building shared libraries should probably be tested on Darwin again as this apparently caused problems in the past: https://github.com/NixOS/nixpkgs/commit/d349cfee88384b4cc353dba8d1154f230520bcc4

**Comment by orivej** [comment]
@GrahamcOfBorg build ffmpeg_4

**Comment by orivej** [comment]
Yeah, I've lost track of this. I have tested building `ffmpeg-full` and running aomenc on Linux. At the moment I can not test on macOS, I hope the bot will confirm that it builds, since the previous shared lib error was a build failure (https://github.com/NixOS/nixpkgs/pull/52444#issuecomment-450577137).

**Comment by orivej** [comment]
(Building ffmpeg_4 inadvertently tests building libaom due to https://github.com/NixOS/nixpkgs/pull/72941/files#r429495248)

**Comment by orivej-nixos** [comment]
Unfortunately staging was broken [1], I'll temporarily switch to `master`; while building python3.pkgs.cython:
> /nix/store/ri3b04wqx51r3xf2l7z1gz24kr299ks1-python3.7-pkgconfig-1.5.1/nix-support/setup-hook: line 61: export: `NIX_@wrapperName@_TARGET_HOST_@suffixSalt@=1': not a valid identifier

**Comment by orivej-nixos** [comment]
@GrahamcOfBorg build libaom ffmpeg_4

**Comment by orivej** [comment]
aa44ca368a09bf6c487216cb2987d5ddd8d5fece should prevent future libaom updates from triggering a mass rebuild.

**Comment by primeos** [comment]
@orivej Thanks

> aa44ca3 should prevent future libaom updates from triggering a mass rebuild.

Nice, that explains it :) I was surprised that this caused so many rebuilds as IIRC mainly ffmpeg-full depends on it, but I forgot to have a closer look.

**Comment by orivej** [comment]
Aomedia patch submission seems too convoluted. Feel free to submit it as if you wrote it yourself. The only thing I would change is set `exec_prefix` to `${prefix}` (literally, as it was before my patch) in case prefix and exec_prefix are the same, so that other distributions will see the usual `exec_prefix=${prefix}` in their .pc.

**Comment by primeos** [comment]
> Aomedia patch submission seems too convoluted.

Unfortunately :o

> Feel free to submit it as if you wrote it yourself.

Ok, thanks, I'll look into that then.

**Pull request merged**
