### PR TITLE
nixos/python-test-driver: add option to disable the linter without warning

### PR DESCRIPTION
**Pull request by khumba**
###### Motivation for this change

This is to partially address https://github.com/NixOS/nixpkgs/issues/72964.

This follows up from NixOS/nixpkgs#76171 to add a way to disable the linter for
NixOS tests using the Python driver, without printing a warning to the
console, as `skipLint` does.  Linting is skipped if either `skipLint` or
the new `skipLintSilently` option are true, but a warning about skipping
is only printed if `skipLintSilently` is false.

This is meant to allow running tests during development, or outside of
Nixpkgs, without forcing unnecessary work to conform to a style guide
when it's not relevant.

`skipLintSilently` is not meant to be used for merged to Nixpkgs main,
non-feature branches.

I'm open to combining these two parameters or having some other way
to pass them in, I more just want a way to turn off a stream of

    trace: warning: Linting is disabled!
    trace: warning: Linting is disabled!
    trace: warning: Linting is disabled!
    ...

messages I see when building a bunch of tests with linting disabled.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by flokli — CHANGES_REQUESTED** [review]
I'm not sure adding yet another option to disable linting entirely is the right way to approach this, and would rather prefer if we'd have a discussion about how/what linting we want to have in https://github.com/NixOS/nixpkgs/issues/72964.

**Comment by worldofpeace** [comment]
> I'm not sure adding yet another option to disable linting entirely is the right way to approach this, and would rather prefer if we'd have a discussion about how/what linting we want to have in #72964.

I would agree with that

**Comment by khumba** [comment]
Closing as this isn't needed, Black already offers a way with `# fmt: off`.

**Comment by flokli** [comment]
Can you add a small reference to it in the manual? (Maybe add this is for non-nixpkgs usages)

**Comment by khumba** [comment]
Yes, that's a good suggestion!  Will do.

**Pull request closed without merging**
