### PR TITLE
tree-wide: build with openexr 3

### PR DESCRIPTION
**Pull request by yu-re-ka**
## Description of changes

This migrates not everything, but some specific dependency cones that are not mass rebuilds and have interactions with each other.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
At what point is it just time to switch `openexr` to `openexr_3` (keeping `openexr_2`)?

**Comment by yu-re-ka** [comment]
@risicle that is what I proposed at first, but it was rejected by the openexr package maintainer: https://github.com/NixOS/nixpkgs/pull/279061#issuecomment-1879879530

> changing every package that depends on openexr to v3 carte blance without checking the dependencies of each package explicitly seems like a mistake.

**Comment by yu-re-ka** [comment]
Another way would be to change all usages of pkgs.openexr to pkgs.openexr_2, then changing default to pkgs.openexr to point to pkgs.openexr_3, and then selectively migrate things.

**Comment by risicle** [comment]
Not sure what the difference fundamentally ends up being but ok let's do it this way.

I suppose for each one we should check that it's still picking up openexr in case it's an optional dependency and is still just continuing to build happily without it.

**Comment by risicle** [comment]
Honestly I'm really confused about what order you want all these PRs reviewed in.

**Comment by yu-re-ka** [comment]
> Honestly I'm really confused about what order you want all these PRs reviewed in.

I agree it's very chaotic, I still don't have a really clear idea on what the dependencies are for upgrading this dependency. Like upgrading the dependency in openvdb will require it to be updated in openimageio too, or else blender won't build.

So my methodology is to just throw things at the wall and see what sticks. If any of these PRs can be reviewed as not breaking anything, it should be merged, in any order.

**Comment by yu-re-ka** [comment]
14 packages built

alembic blender blender embree embree olive-editor-unstable openimageio openshadinglanguage openvdb prusa-slicer python3.11-OpenUSD super-slicer super-slicer super-slicer

**Comment by yu-re-ka** [comment]
@paperdigits please review :)

**Comment by paperdigits** [comment]
The approach is better, thank you!

**Review by ShaddyDC — APPROVED** [review]
Any reason why you switch to `openexr_3` in the derivations instead of passing that in as the `openexr` attribute? I was under the impression that's generally preferred to make overriding easier.
Apart from that, it looks like `openusd` is working with these changes.

**Comment by yu-re-ka** [comment]
> Any reason why you switch to openexr_3 in the derivations instead of passing that in as the openexr attribute?


Good point, I had no specific reason except being lately used to working on pkgs/by-name/. I changed this to pass the version in all-packages.nix

**Review by Moredread — APPROVED** [review]
Ah, thank you, the changes for prusa-slicer should always have been this way. (I only reviewed this change, I haven't reviewed the rest of the PR)

**Pull request merged**
