### PR TITLE
tutanota-desktop: install from release tarball

### PR DESCRIPTION
**Pull request by WolfangAukang**
###### Motivation for this change

Current `tutanota-desktop` installation is based on its AppImage. The problem is that the download URL does not have any version on it, so in case there is a version update, the installation breaks, unless someone updates the SHA.

This one is based on the tar files on the Github releases. As the download URL has the version, this will be more helpful and will not break when the version is updated.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by timokau — CHANGES_REQUESTED** [review]
Thank you for working on this. I left a few comments.

**Comment by timokau** [comment]
One more tiny nit: The commit message should be imperative. I suggest "tutanota-desktop: install from release tarball".

**Comment by jtrees** [comment]
Thanks again for this. I'm still relatively new to nix so I'm not in a position to review the code. I can, however, confirm that the app builds, launches and appears to work after some brief testing with `nox-review`.

**Review by timokau — CHANGES_REQUESTED** [review]
Looks good :) I left some more feedback / questions but I think this is close to finished.

**Review by timokau — APPROVED** [review]
I just noticed that the commit message does not match the updated PR title, but I'll just take the liberty to change that in a squash&merge.

Thank you for your patience with my reviews :)

**Pull request merged**
