### PR TITLE
crosvm: 104.0 -> 107.1

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by astro — APPROVED** [review]
Works but only if I keep passing `--seccomp-log-failures`. Without it fails on x86_64:
```
[2022-10-03T18:36:28.237798106+02:00 INFO  devices::acpi] Listening on acpi_mc_group of acpi_event family
[2022-10-03T18:36:28.380173248+02:00 ERROR crosvm::crosvm::sys::unix] child xhci controller (pid 1889588) died: signo 17, status 31, code 3
[2022-10-03T18:36:28.380920135+02:00 ERROR devices::proxy] failed write to child device process xhci controller: failed to send packet: Broken pipe (os error 32)
[2022-10-03T18:36:28.381030180+02:00 ERROR devices::proxy] failed to read result of Shutdown from child device process xhci controller: tube was disconnected
[2022-10-03T18:36:28.446001964+02:00 INFO  crosvm] crosvm has exited normally
[2022-10-03T18:36:28.446516208+02:00 INFO  crosvm] exiting with success
```

**Comment by alyssais** [comment]
I've updated this to the latest crosvm, and backported a patch that fixes the sandboxing issue, but there's a new problem, which is that it doesn't build for aarch64.

**Comment by alyssais** [comment]
aarch64 build is fixed, both cross and native.

@astro can you check everything looks okay for you?

**Comment by astro** [comment]
Nice! Works for me on x86_64.

**Review by astro — APPROVED** [review]

**Pull request merged**
