### PR TITLE
python3Packages.polars: 0.18.13 -> 0.19.12

### PR DESCRIPTION
**Pull request by edef1c**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
This looks good to me and the build is passing. Were you looking to do more to take it out of draft ?

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 264373` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.polars</li>
    <li>python310Packages.polars.dist</li>
    <li>python311Packages.polars</li>
    <li>python311Packages.polars.dist</li>
  </ul>
</details>

**Comment by flokli** [comment]
I also tested this, and verified the build on `aarch64-darwin` too.

We ran into some jemalloc-related issues when using it in a jupyter notebook, but that can probably be addressed in a followup.

**Comment by edef1c** [comment]
The jemalloc issues apply to plain Python too, they're just partially suppressed there.
```
> python3 -c 'import polars'
/nix/store/hncw7v8djk0vm5asy0jcggia0k60dhdv-python3-3.11.5-env/lib/python3.11/site-packages/polars/utils/build_info.py:5: UserWarning: polars binary missing!
  from polars.utils.polars_version import get_polars_version
> python3 -c 'import polars.polars'
/nix/store/hncw7v8djk0vm5asy0jcggia0k60dhdv-python3-3.11.5-env/lib/python3.11/site-packages/polars/utils/build_info.py:5: UserWarning: polars binary missing!
  from polars.utils.polars_version import get_polars_version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /nix/store/gsbfr5ar6bki41qwfz6wbrd59z5p9ciw-jemalloc-5.3.0/lib/libjemalloc.so.2: cannot allocate memory in static TLS block
```

Note that the ImportError is suppressed by `__init__.py`:
```
with contextlib.suppress(ImportError):  # Module not available when building docs
    # ensure the object constructor is known by polars
    # we set this once on import

    # we also set other function pointers needed
    # on the rust side. This function is highly
    # unsafe and should only be called once.
    from polars.polars import __register_startup_deps

    __register_startup_deps()
```

**Comment by edef1c** [comment]
We're substituting the vendored jemalloc with our own, but forgetting [a crucial piece of configuration](https://github.com/pola-rs/polars/blob/d4c56a2ad4aa9768b901f890c420f2982aabd5b6/py-polars/Cargo.toml#L95-L96):
```
[target.'cfg(all(target_os = "linux", not(use_mimalloc)))'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
```

**Comment by flokli** [comment]
I successfully built and import it via `polars.polars` (on `aarch64-darwin`):

```
[nix-shell:~/nixpkgs]$ nix-shell -p python3 -p python3.pkgs.polars --run bash
Florians-Air:nixpkgs flokli$ python3
Python 3.10.12 (main, Sep 17 2023, 17:18:18) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars.polars
>>> polars.__version__
'0.19.12'
>>> 
```

**Review by flokli — APPROVED** [review]

**Pull request merged**
