### PR TITLE
navidrome: Use npmConfig and fetchNpmDeps

### PR DESCRIPTION
**Pull request by mweinelt**
Simplifies the moving parts we need to keep around by a lot.

Fixes navidrome wrt #229910.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by squalus — APPROVED** [review]
Awesome. The update script will need to be updated as well.

**Comment by mweinelt** [comment]
> Awesome. The update script will need to be updated as well.

That should be fairly simple. This change is pure gold.

```
 pkgs/servers/misc/navidrome/default.nix             |    23 +-
 pkgs/servers/misc/navidrome/ui/default.nix          |    27 -
 pkgs/servers/misc/navidrome/ui/node-composition.nix |    17 -
 pkgs/servers/misc/navidrome/ui/node-env.nix         |   686 ------
 pkgs/servers/misc/navidrome/ui/node-packages.nix    | 15094 -------------------------------------------------------------------------------------------------------------------------------
 pkgs/servers/misc/navidrome/update.nix              |    28 -
 6 files changed, 18 insertions(+), 15857 deletions(-)
```

**Comment by mweinelt** [comment]
Not quite yet. Unfortunately nix-update does not update the `npmDepsHash`. Will probably have to splice the two builds into one.

**Comment by mweinelt** [comment]
Waiting for feedback on https://github.com/NixOS/nixpkgs/pull/230092/files#r1186722499

**Comment by mweinelt** [comment]
Used the workaround from the mentioned PR to demonstrate that the overall approach works.

**Comment by mweinelt** [comment]
Unfortunately, nix-update does not handle npmDeps either. So likely only handles pure `buildNpmPackage` functions. A new update script it is then.

```
warning: found empty hash, assuming 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
this derivation will be built:
  /nix/store/vsbdmgmgb3bv14r6pr11fwwm5iy7lfmi-navidrome-0.49.2-go-modules.drv
unpacking sources
unpacking source archive /nix/store/npd9d2m40jcrf4aq24mkyap2i0sq712z-source
source root is source
patching sources
/build/source/ui /build/source
Executing npmConfigHook
Configuring npm

ERROR: no dependencies were specified
Hint: set `npmDeps` if using these hooks individually. If this is happening with `buildNpmPackage`, please open an issue.

error: build of '/nix/store/vsbdmgmgb3bv14r6pr11fwwm5iy7lfmi-navidrome-0.49.2-go-modules.drv' on 'ssh://builder' failed: builder for '/nix/store/vsbdmgmgb3bv14r6pr11fwwm5iy7lfmi-navidrome-0.49.2-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/npd9d2m40jcrf4aq24mkyap2i0sq712z-source
       > source root is source
       > patching sources
       > /build/source/ui /build/source
       > Executing npmConfigHook
       > Configuring npm
       >
       > ERROR: no dependencies were specified
       > Hint: set `npmDeps` if using these hooks individually. If this is happening with `buildNpmPackage`, please open an issue.
       >
       For full logs, run 'nix log /nix/store/vsbdmgmgb3bv14r6pr11fwwm5iy7lfmi-navidrome-0.49.2-go-modules.drv'.
error: builder for '/nix/store/vsbdmgmgb3bv14r6pr11fwwm5iy7lfmi-navidrome-0.49.2-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/npd9d2m40jcrf4aq24mkyap2i0sq712z-source
       > source root is source
       > patching sources
       > /build/source/ui /build/source
       > Executing npmConfigHook
       > Configuring npm
       >
       > ERROR: no dependencies were specified
       > Hint: set `npmDeps` if using these hooks individually. If this is happening with `buildNpmPackage`, please open an issue.
       >
       For full logs, run 'nix log /nix/store/vsbdmgmgb3bv14r6pr11fwwm5iy7lfmi-navidrome-0.49.2-go-modules.drv'.
Traceback (most recent call last):
  File "/nix/store/22hih10w96c1s6n68c0xksmb7d2p2ljz-nix-update-0.17.2/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/22hih10w96c1s6n68c0xksmb7d2p2ljz-nix-update-0.17.2/lib/python3.11/site-packages/nix_update/__init__.py", line 290, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/22hih10w96c1s6n68c0xksmb7d2p2ljz-nix-update-0.17.2/lib/python3.11/site-packages/nix_update/update.py", line 340, in update
    update_go_modules_hash(opts, package.filename, package.go_modules)
  File "/nix/store/22hih10w96c1s6n68c0xksmb7d2p2ljz-nix-update-0.17.2/lib/python3.11/site-packages/nix_update/update.py", line 150, in update_go_modules_hash
    target_hash = nix_prefetch(opts, "go-modules")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/22hih10w96c1s6n68c0xksmb7d2p2ljz-nix-update-0.17.2/lib/python3.11/site-packages/nix_update/update.py", line 127, in nix_prefetch
    raise UpdateError(
nix_update.errors.UpdateError: failed to retrieve hash when trying to update navidrome.go-modules

**Comment by mweinelt** [comment]
The build works like this, but the update script likely requires #230991 to work.

**Comment by mweinelt** [comment]
This is currently based on top of #230991, the update script works. Thanks for the help @lilyinstarlight!

**Pull request merged**
