### PR TITLE
airshipper 10.0 -> 14.0

### PR DESCRIPTION
**Pull request by alexplatz**
## Description of changes

https://github.com/veloren/Airshipper/blob/master/CHANGELOG.md

## Things done

- ~~Updated lockfile~~
- Updated default.nix

It's all shiny now. GUI renders on arm.

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
Diff LGTM, lets see what my build tells us.

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 344696` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>airshipper</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Ah, btw... as you don't use the `Cargo.lock` file anymore, you can remove it!

**Comment by alexplatz** [comment]
Looks like you're right, thanks!

**Comment by matthiasbeyer** [comment]
Yeah, now please squash the last commit into the previous one.

**Review by getchoo — APPROVED** [review]
Result of `nixpkgs-review pr 344696` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>airshipper</li>
  </ul>
</details>

**Comment by alexplatz** [comment]
I'm intending to merge this today unless anyone has concerns with the PR

**Review by h7x4 — APPROVED** [review]

**Pull request merged**
