### PR TITLE
python3Packages.{langchain,langgraph}-* fix build errors introduced by mass update 

### LINKED ISSUE #352974: Build failure: python3Packages.langchain* and langgraph* fail to build with versioning failures
### Steps To Reproduce

1. Build, for example, python312Packages.langchain-open
2. Observe it fails at the imports check

Discovered as part of #351868

### Root cause

TL;dr PR #345326 tried to version elements of langchain and langgraph equal to their underlying "core" packages; this broke builds for anything using langchain or langgraph. In other words: langchain-ai's release strategy means we need to download an build each subpackage independently, even if that requires downloading (mostly) the same source over and over. 

1. The langchain packages are built in a monorepo and [released](https://github.com/langchain-ai/langchain/releases) independently, with most of them living in the core langchain codebase. 
2. The version numbers for each package aren't aligned with the core codebase.
3. The existing derivations all try to download the same `langchain-core` codebase then build the appropriate extension. (See, e.g. [langchain-community@47](https://github.com/NixOS/nixpkgs/blob/2b2a8530a8c6461205e0a2c7b839d5c7502454c1/pkgs/development/python-modules/langchain-community/default.nix#L47) 
4. `langchain-core` can have a significantly different version number than the package being built. This leads to incorrect version numbers being assigned during automated updates; and then leads to failures at the dependency-check stage. (See e.g. [langchain-openai@31](https://github.com/NixOS/nixpkgs/blob/2b2a8530a8c6461205e0a2c7b839d5c7502454c1/pkgs/development/python-modules/langchain-openai/default.nix#L31)

So, while you would think that downloading one source package and building all the components from it would make sense, the reality is that we need to download and version each package individually to keep up the per-package version specifiers correct.

### Notify maintainers

@drupol 
@sarahec 
@natsukium
@mweinelt for thoughts on managing as a monorepo with varying lifetimes

I'll submit the appropriate PR(s).

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by sarahec**
#345326 was a mass update that tried to fix duplicate code downloads by setting the versions of all langchain and langgraph packages equal to their underlying "core" package in their source monorepos. Unfortunately, this breaks dependency checking widely and thus broke many  downstream packages. (The various packages in these monorepos have wildly diverging lifetimes and version numbers.)

At the same time, langchain-ai released upgrades to both the langchain and langgraph ecosystem to fix versioning of the langchain-core library.

This update fixes both:
1. Reverts changes from #345326 including version numbers and checkout paths
2. Applies updates as needed to bring up to a consistent, current set.

Fixes #352974

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
thank you for doing this!

**Comment by sarahec** [comment]
> thank you for doing this!

You're welcome! Not how I planned on spending my day, but it needed to be done. Now chasing down any issues in nixpkgs-review before opening for approvals.

**Comment by sarahec** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353002`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 18 packages failed to build:</summary>
  <ul>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.sagemaker</li>
    <li>python311Packages.sagemaker.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.sagemaker</li>
    <li>python312Packages.sagemaker.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 90 packages built:</summary>
  <ul>
    <li>langgraph-cli (python312Packages.langgraph-cli)</li>
    <li>langgraph-cli.dist (python312Packages.langgraph-cli.dist)</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.databricks-sdk</li>
    <li>python311Packages.databricks-sdk.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-ollama</li>
    <li>python311Packages.langchain-ollama.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-duckdb</li>
    <li>python311Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-cli</li>
    <li>python311Packages.langgraph-cli.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.sagemaker-mlflow</li>
    <li>python311Packages.sagemaker-mlflow.dist</li>
    <li>python312Packages.databricks-sdk</li>
    <li>python312Packages.databricks-sdk.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-duckdb</li>
    <li>python312Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
    <li>python312Packages.mlflow</li>
    <li>python312Packages.mlflow.dist</li>
    <li>python312Packages.sagemaker-mlflow</li>
    <li>python312Packages.sagemaker-mlflow.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Build failure causes:
- sagemaker -- fix in #352444 
- mmcv -- No PR found
- mmengine -- No PR found

One or more of the above is a prerequisite for langgraph to build. However, langgraph builds fine from the command line, just not in nixpkgs-review.

**Review by natsukium — APPROVED** [review]
Let's move on. Thanks.

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 353002` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>python311Packages.databricks-sdk</li>
    <li>python311Packages.databricks-sdk.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.sagemaker</li>
    <li>python311Packages.sagemaker-mlflow</li>
    <li>python311Packages.sagemaker-mlflow.dist</li>
    <li>python311Packages.sagemaker.dist</li>
    <li>python312Packages.langgraph-checkpoint-duckdb</li>
    <li>python312Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python312Packages.sagemaker</li>
    <li>python312Packages.sagemaker.dist</li>
  </ul>
</details>
<details>
  <summary>84 packages built:</summary>
  <ul>
    <li>langgraph-cli (python312Packages.langgraph-cli)</li>
    <li>langgraph-cli.dist (python312Packages.langgraph-cli.dist)</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-ollama</li>
    <li>python311Packages.langchain-ollama.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-duckdb</li>
    <li>python311Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-cli</li>
    <li>python311Packages.langgraph-cli.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.databricks-sdk</li>
    <li>python312Packages.databricks-sdk.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
    <li>python312Packages.langgraph.dist</li>
    <li>python312Packages.mlflow</li>
    <li>python312Packages.mlflow.dist</li>
    <li>python312Packages.sagemaker-mlflow</li>
    <li>python312Packages.sagemaker-mlflow.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
@natsukium Final fixes from nixpkgs-review done. Over to you.

**Comment by tobim** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353002`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 16 packages failed to build:</summary>
  <ul>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.sagemaker</li>
    <li>python311Packages.sagemaker.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.sagemaker</li>
    <li>python312Packages.sagemaker.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 90 packages built:</summary>
  <ul>
    <li>langgraph-cli (python312Packages.langgraph-cli)</li>
    <li>langgraph-cli.dist (python312Packages.langgraph-cli.dist)</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.databricks-sdk</li>
    <li>python311Packages.databricks-sdk.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-ollama</li>
    <li>python311Packages.langchain-ollama.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-duckdb</li>
    <li>python311Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-cli</li>
    <li>python311Packages.langgraph-cli.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.sagemaker-mlflow</li>
    <li>python311Packages.sagemaker-mlflow.dist</li>
    <li>python312Packages.databricks-sdk</li>
    <li>python312Packages.databricks-sdk.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-duckdb</li>
    <li>python312Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
    <li>python312Packages.mlflow</li>
    <li>python312Packages.mlflow.dist</li>
    <li>python312Packages.sagemaker-mlflow</li>
    <li>python312Packages.sagemaker-mlflow.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353002`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 16 packages failed to build:</summary>
  <ul>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.sagemaker</li>
    <li>python311Packages.sagemaker.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.sagemaker</li>
    <li>python312Packages.sagemaker.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 90 packages built:</summary>
  <ul>
    <li>langgraph-cli (python312Packages.langgraph-cli)</li>
    <li>langgraph-cli.dist (python312Packages.langgraph-cli.dist)</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.databricks-sdk</li>
    <li>python311Packages.databricks-sdk.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-ollama</li>
    <li>python311Packages.langchain-ollama.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-duckdb</li>
    <li>python311Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-cli</li>
    <li>python311Packages.langgraph-cli.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.sagemaker-mlflow</li>
    <li>python311Packages.sagemaker-mlflow.dist</li>
    <li>python312Packages.databricks-sdk</li>
    <li>python312Packages.databricks-sdk.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-duckdb</li>
    <li>python312Packages.langgraph-checkpoint-duckdb.dist</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
    <li>python312Packages.mlflow</li>
    <li>python312Packages.mlflow.dist</li>
    <li>python312Packages.sagemaker-mlflow</li>
    <li>python312Packages.sagemaker-mlflow.dist</li>
  </ul>
</details>

**Review by tobim — APPROVED** [review]

**Review by drupol — APPROVED** [review]

**Pull request merged**
