### PR TITLE
spotify: 1.0.96.181 -> 1.1.5.153

### PR DESCRIPTION
**Pull request by angristan**
###### Motivation for this change

Wow, Spotify hasn't been updated in a long time! Fonts look much better in this release.

Thanks to the update script, this was a bliss. There was a missing dependency (`libatspi.so.0`) which I fixed thanks to #49636.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
tested locally

**Comment by timokau** [comment]
Did you actually play anything? There's https://github.com/NixOS/nixpkgs/pull/57800, and I don't think anything has changed.

**Comment by angristan** [comment]
You're right I get a SIGSEGV when playing music. @FRidh Can you revert this? Thanks and sorry

**Comment by FRidh** [comment]
Ah, no, that I did not. Reverting...

**Comment by angristan** [comment]
Apparently the snap package has been updated to 1.10: https://www.omgubuntu.co.uk/2019/07/spotify-snap-app-outdated

Time to try again!

**Comment by angristan** [comment]
Same SIGSEGV when playing music, sadly :(

**Comment by timokau** [comment]
Thanks for trying! I wonder if they don't test the builds or just don't care.

At least we're not bound to the latest version anymore since the switch to snapcraft. The latest version isn't that important as long as it still works.

**Pull request merged**
