### PR TITLE
nixos/test-runner: Fix execute() flakiness

### PR DESCRIPTION
**Pull request by dasJ**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) → `switchTest`
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
@tfc any updates to this? I'm starting to feel pressure from the soon to be expected feature freeze

**Review by roberth — APPROVED** [review]

**Comment by fgaz** [comment]
Looks like this PR broke at least one nixos test: #144613

**Comment by vcunat** [comment]
I was bisecting `nixosTests.xfce` now and ended up here (1640359f33; retried a few times on the commit and its parent to confirm).  This currently blocks the nixos-unstable channel.

**Comment by dasJ** [comment]
There's a workaround: #144679

**Comment by roberth** [comment]
@vcunat Fix for xfce is in #144795 now

**Pull request merged**
