### PR TITLE
uboot: 2023.07.20 -> 2024.01

### LINKED ISSUE #286411: Update request: uboot 2023.07.02 → 2024.01
- Package name: U-Boot
- Latest released version: 2024.01

- Current version on the unstable channel: 2023.07.02
- Current version on the stable/release channel: 2023.07.02 

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

CC @bartsch @dezgeg @samueldr @lopsided98

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Kreyren**
Patch removed as i was told that it's not needed anymore and fails to apply:

https://gist.githubusercontent.com/Kreyren/e23ac03d3ac20c64f8f7000460ef0a70/raw/0375e056b6aa483adf166d438cb0ab5759c96248/gistfile1.txt

`ubootOlimexA64Teres1` tested, appears to build without issues:

https://gist.githubusercontent.com/Kreyren/29f96dae67bca0e57fec693768a9f48d/raw/3a4c1ef48cdb6b3f5c9653bb68beb0349e14c210/gistfile1.txt

Fixes: https://github.com/NixOS/nixpkgs/issues/286411

## Things done

- Built on platform(s)
  - [-] x86_64-linux
    - Only `ubootOlimexA64Teres1` through QEMU for aarch64-linux
  - [-] aarch64-linux
  - [-] x86_64-darwin
  - [-] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [-] `sandbox = relaxed`
  - [-] `sandbox = true`
- [-] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [-] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [-] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [-] (Module updates) Added a release notes entry if the change is significant
  - [-] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
Duplicate https://github.com/NixOS/nixpkgs/pull/292757

**Comment by Kreyren** [comment]
> Can you provide more context as to why you state it's not needed anymore? -- @samueldr (https://github.com/NixOS/nixpkgs/pull/297194#issuecomment-2007796947)

https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$NL5MrT07j4Lql7chK5RhKyrz15vR7XmNlwLUGgkeJcI?via=nixos.org&via=matrix.org&via=nixos.dev

Additionally i asked on IRC in the arm room about this and was told that it doesn't seem to be needed anymore since 2024.01, but feel free to correct me if i am wrong as i replaced rpi with olimex products for my use and don't have the option to verify the claims on the hardware itself.

**Comment by lopsided98** [comment]
This looks like the relevant quote:
> KREYREN: you seemed to implemented a patch for raspberry-pi to be able to use bigger kernels in u-boot is that still needed?
> K900: AFAIK yes

which says that it is still needed...

Also, the memory allocation has not changed upstream and I doubt the kernel has gotten smaller, so I'd expect it to still be necessary.

**Comment by Kreyren** [comment]
> Also, the memory allocation has not changed upstream and I doubt the kernel has gotten smaller, so I'd expect it to still be necessary. -- @lopsided98 (https://github.com/NixOS/nixpkgs/pull/297194#issuecomment-2010846684)

Noted, thanks for the correction

**Pull request closed without merging**
