### PR TITLE
igraph: use ctest and skip failing test on macOS

### LINKED ISSUE #228711: MacOS Apple Silicon - igraph 0.10.4 - 328 - example::safelocale (Failed)
## Issue description
```
nix --version
nix (Nix) 2.15.0

ProductName: macOS
ProductVersion: 13.3.1
BuildVersion: 22E261

error: builder for '/nix/store/5ylab67jw0m69y09gb5vv1s9xg61h481-igraph-0.10.4.drv' failed with exit code 2;
       > make[2]: *** [CMakeFiles/Makefile2:2709: tests/CMakeFiles/check.dir/all] Error 2
       > make[2]: Leaving directory '/private/tmp/nix-build-igraph-0.10.4.drv-0/source/build'
       > make[1]: *** [CMakeFiles/Makefile2:2716: tests/CMakeFiles/check.dir/rule] Error 2
       > make[1]: Leaving directory '/private/tmp/nix-build-igraph-0.10.4.drv-0/source/build'
       > make: *** [Makefile:810: check] Error 2
       For full logs, run 'nix-store -l /nix/store/5ylab67jw0m69y09gb5vv1s9xg61h481-igraph-0.10.4.drv'.

328/537 Test #328: example::safelocale.................................***Failed    1.68 sec
Error at src/io/parse_utils.c:155 : Unexpected character '.' while parsing real number. - Parse error.
Test exited abnormally with error: Subprocess aborted
=========================================

CMake Error at /tmp/nix-build-igraph-0.10.4.drv-0/source/etc/cmake/run_legacy_test.cmake:32 (message):
  Exiting test.

99% tests passed, 1 tests failed out of 537

Total Test time (real) =  86.32 sec

The following tests FAILED:
        328 - example::safelocale (Failed)
Errors while running CTest
make[3]: *** [tests/CMakeFiles/check.dir/build.make:71: tests/CMakeFiles/check] Error 8
make[3]: Leaving directory '/private/tmp/nix-build-igraph-0.10.4.drv-0/source/build'
make[2]: *** [CMakeFiles/Makefile2:2709: tests/CMakeFiles/check.dir/all] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-igraph-0.10.4.drv-0/source/build'
make[1]: *** [CMakeFiles/Makefile2:2716: tests/CMakeFiles/check.dir/rule] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-igraph-0.10.4.drv-0/source/build'
make: *** [Makefile:810: check] Error 2
```

## Technical details

```
 nix-shell -p nix-info --run "nix-info -m"
these 3 paths will be fetched (1.01 MiB download, 8.01 MiB unpacked):
  /nix/store/jxs932c96jzaa5n88vgp1vzimd3k2dxq-DarwinTools-1
  /nix/store/4zq9fc233hy1c7agkk9ffn2wr2y30yra-bash-interactive-5.2-p15
  /nix/store/v97x2zbzwpxr2djak6pr2zhvdhn2qqi3-nix-info
copying path '/nix/store/jxs932c96jzaa5n88vgp1vzimd3k2dxq-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/4zq9fc233hy1c7agkk9ffn2wr2y30yra-bash-interactive-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/v97x2zbzwpxr2djak6pr2zhvdhn2qqi3-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

### PR DESCRIPTION
**Pull request by tjni**
## Description of changes

I became bothered by `igraph` failing on my nixpkgs-review runs, which I found from https://github.com/igraph/igraph/issues/2340 is a bug in macOS.

We can still let this package build and use all of its other functionality by using `ctest` directly and excluding the failing test. I took the commands from upstream's [CI workflow](https://github.com/igraph/igraph/blob/master/.azure/build.yml#L75).

Closes https://github.com/NixOS/nixpkgs/issues/228711, because there will no longer be a build failure.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by szhorvat** [comment]
Which macOS versions does Nix usually test with, and when do you plan to move on to macOS 14 after its release?

**Comment by tjni** [comment]
> Which macOS versions does Nix usually test with and when do you plan to move on to macOS 14 after its release?

That's a good question, I don't know. I always thought that it was on an old macOS version since the test was passing on Hydra, but it recently started failing (e.g. https://hydra.nixos.org/build/232479806). I'm going to temporarily modify this PR to call `sw_vers` to see what it says, and I'll also ask on Matrix.

**Comment by tjni** [comment]
From the x86_64-darwin build (which I think is through Rosetta 2), `sw_vers` came up with the following:
```
ProductName:            macOS
ProductVersion:         13.1
BuildVersion:           22C65
```

**Comment by tjni** [comment]
It does look like we are using macOS 13.1 now. Is the bug fixed on macOS 14? If so, I can ask for it, but the timing would be uncertain because there's no well-defined process for it currently that I'm aware of.

**Comment by szhorvat** [comment]
> Is the bug fixed on macOS 14?

I am not actually sure, as I don't have access to that version. However, Apple did respond to my bug report, so I hope they fixed it.  I would suggest revisiting this when macOS 14 is out, to check if the test can be re-enabled.

BTW version 0.10.7 is out now.

**Comment by dotlambda** [comment]
Is all this machinery really worth it? Why not set
```
doCheck = !stdenv.isDarwin
```
until Apple fixes this?

**Pull request closed without merging**
