### PR TITLE
zed-editor: 0.129.2 -> 0.130.6

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.130.6

cc @jansol 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 303233` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 303233` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
`nixpkgs-review` fail on `darwin` when using the nix-community darwin builder:
```
sandbox-exec: pattern serialization length 71524 exceeds maximum (65535)
```

Could someone owning a mac check if this new version builds fine please ?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 303233` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
```
failures:

---- zed::tests::test_disabled_keymap_binding stdout ----
thread 'zed::tests::test_disabled_keymap_binding' panicked at crates/zed/src/zed.rs:664:48:
called `Result::unwrap()` on an `Err` value: Invalid keystroke `cmd-k`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    zed::tests::test_disabled_keymap_binding

test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 3.34s
```

**Comment by jansol** [comment]
> called `Result::unwrap()` on an `Err` value: Invalid keystroke `cmd-k`
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>
>
> failures:
>     zed::tests::test_disabled_keymap_binding
>
> test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 1.29s

Yeah I imagine that'd fail on Linux

**Comment by niklaskorz** [comment]
> `nixpkgs-review` fail on `darwin` when using the nix-community darwin builder:
> 
> ```
> sandbox-exec: pattern serialization length 71524 exceeds maximum (65535)
> ```
> 
> Could someone owning a mac check if this new version builds fine please ?

on it :)

**Comment by GaetanLepage** [comment]
> ```
> failures:
> 
> ---- zed::tests::test_disabled_keymap_binding stdout ----
> thread 'zed::tests::test_disabled_keymap_binding' panicked at crates/zed/src/zed.rs:664:48:
> called `Result::unwrap()` on an `Err` value: Invalid keystroke `cmd-k`
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 
> failures:
>     zed::tests::test_disabled_keymap_binding
> 
> test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 3.34s
> ```

Should we skip this test on Linux ?

**Comment by jansol** [comment]
I think this is really something that upstream should fix. But it should not affect users (much) so it's probably sensible to skip the test until upstream has time to address it.

**Comment by jansol** [comment]
Okay apparently this *does* cause panics for users after updating so let's hold off of this for a bit.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 303233` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 303233` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
What do we do with darwin?

**Comment by niklaskorz** [comment]
> What do we do with darwin?

I'd be fine with working on a fix in a separate PR, and marking darwin as broken in this one for now so it's not blocking the update

**Comment by GaetanLepage** [comment]
I marked it as broken on darwin. Feel free to merge whenever you feel like it @SuperSandro2000, good for me.

**Review by niklaskorz — APPROVED** [review]

**Pull request merged**
