### PR TITLE
rocmPackages_6: init at 6.0.2(?)

### PR DESCRIPTION
**Pull request by ScatteredRay**
## Description of changes

#197885

Upgrading to ROCm 6.0.2

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ScatteredRay** [comment]
Hey, @mschwaig what are you testing out? My [rocm6 branch](https://github.com/ScatteredRay/nixpkgs/tree/rocm6) seems to be building rocmModules_6.rocm-all and the project I'm working on seems to work find against it. Maybe you have something you'd like to test against it?

**Comment by mschwaig** [comment]
I can test `llama-cpp` and `ollama`in the following days. There are also a few small things I noticed, that I could put in a review, if you're ready for that.

**Comment by mschwaig** [comment]
I did some testing now, but I did not get to what I actually wanted to do yet.

By running `nixpkgs-review` I found that the build for `libjpeg-turbo`, which is upstream from `mivisionx-hip` is still failing on your branch. I think it was failing on master a few days ago as well.

I have not gotten to testing `llama-cpp` or `ollama` yet.

The command I ran is
```
nix run github:mic92/nixpks-review -- pr --checkout commit --build-args="--max-jobs 4"  289187
```
The ` --checkout commit` flag is to make sure that the broken `libjpeg-turbo` is not just on the merge target and `--build-args="--max-jobs 4" ` is because I think I run out of RAM without that.

I would like to have one of our branches in a state where everything builds, but it's a pain to test this since I only have 64 GB of RAM on my primary machine right now.
I actually started a run of`nixpkgs-review` in the cloud with 256 GB, but I will abort this now due to the issue with `libjpeg-turbo`.

I think to address this on your branch it would make sense to rebase your work onto a some state of master where all the dependencies of ROCm properly build. Alternatively waiting for a version of master where that build failure is resolved and removing the `-checkout commit` flag would work as well, but that's bad to collaborate on because it's a moving target.

Maybe it makes sense to move this out of the draft stage or do whatever else is required so that hydra can try building it.

**Comment by mschwaig** [comment]
I managed to get a complete run of
```
nix run github:mic92/nixpkgs-review -- rev --build-args="--max-jobs 1" HEAD
```
for this branch now.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>rocmPackages_6.llvm.flang</li>
    <li>rocmPackages_6.llvm.flang.doc</li>
    <li>rocmPackages_6.llvm.flang.info</li>
    <li>rocmPackages_6.llvm.flang.man</li>
    <li>rocmPackages_6.llvm.libclc</li>
    <li>rocmPackages_6.rdc</li>
    <li>rocmPackages_6.rdc.doc</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>rocmPackages_6.migraphx</li>
    <li>rocmPackages_6.miopen-opencl</li>
    <li>rocmPackages_6.mivisionx (rocmPackages_6.mivisionx-hip)</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-opencl</li>
    <li>rocmPackages_6.rocmlir</li>
    <li>rocmPackages_6.rocmlir.external</li>
  </ul>
</details>
<details>
  <summary>87 packages built:</summary>
  <ul>
    <li>rocmPackages_6.clang-ocl</li>
    <li>rocmPackages_6.clr</li>
    <li>rocmPackages_6.clr.icd</li>
    <li>rocmPackages_6.composable_kernel</li>
    <li>rocmPackages_6.half</li>
    <li>rocmPackages_6.hip-common</li>
    <li>rocmPackages_6.hipblas</li>
    <li>rocmPackages_6.hipcc</li>
    <li>rocmPackages_6.hipcub</li>
    <li>rocmPackages_6.hipfft</li>
    <li>rocmPackages_6.hipfort</li>
    <li>rocmPackages_6.hipify</li>
    <li>rocmPackages_6.hiprand</li>
    <li>rocmPackages_6.hipsolver</li>
    <li>rocmPackages_6.hipsparse</li>
    <li>rocmPackages_6.hsa-amd-aqlprofile-bin</li>
    <li>rocmPackages_6.llvm.bintools</li>
    <li>rocmPackages_6.llvm.clang</li>
    <li>rocmPackages_6.llvm.clang-tools-extra</li>
    <li>rocmPackages_6.llvm.clang-tools-extra.doc</li>
    <li>rocmPackages_6.llvm.clang-tools-extra.info</li>
    <li>rocmPackages_6.llvm.clang-tools-extra.man</li>
    <li>rocmPackages_6.llvm.clang-unwrapped</li>
    <li>rocmPackages_6.llvm.clang-unwrapped.doc</li>
    <li>rocmPackages_6.llvm.clang-unwrapped.info</li>
    <li>rocmPackages_6.llvm.clang-unwrapped.man</li>
    <li>rocmPackages_6.llvm.compiler-rt</li>
    <li>rocmPackages_6.llvm.libc</li>
    <li>rocmPackages_6.llvm.libc.doc</li>
    <li>rocmPackages_6.llvm.libcxx</li>
    <li>rocmPackages_6.llvm.libcxx.doc</li>
    <li>rocmPackages_6.llvm.libcxxabi</li>
    <li>rocmPackages_6.llvm.libunwind</li>
    <li>rocmPackages_6.llvm.libunwind.doc</li>
    <li>rocmPackages_6.llvm.lld</li>
    <li>rocmPackages_6.llvm.lld.doc</li>
    <li>rocmPackages_6.llvm.lldb</li>
    <li>rocmPackages_6.llvm.lldb.doc</li>
    <li>rocmPackages_6.llvm.lldb.info</li>
    <li>rocmPackages_6.llvm.lldb.man</li>
    <li>rocmPackages_6.llvm.llvm</li>
    <li>rocmPackages_6.llvm.llvm.doc</li>
    <li>rocmPackages_6.llvm.llvm.info</li>
    <li>rocmPackages_6.llvm.llvm.man</li>
    <li>rocmPackages_6.llvm.mlir</li>
    <li>rocmPackages_6.llvm.openmp</li>
    <li>rocmPackages_6.llvm.openmp.doc</li>
    <li>rocmPackages_6.llvm.openmp.info</li>
    <li>rocmPackages_6.llvm.openmp.man</li>
    <li>rocmPackages_6.llvm.polly</li>
    <li>rocmPackages_6.llvm.polly.doc</li>
    <li>rocmPackages_6.llvm.polly.info</li>
    <li>rocmPackages_6.llvm.polly.man</li>
    <li>rocmPackages_6.llvm.pstl</li>
    <li>rocmPackages_6.llvm.rocmClangStdenv</li>
    <li>rocmPackages_6.miopen (rocmPackages_6.miopen-hip)</li>
    <li>rocmPackages_6.rccl</li>
    <li>rocmPackages_6.rocalution</li>
    <li>rocmPackages_6.rocblas</li>
    <li>rocmPackages_6.rocdbgapi</li>
    <li>rocmPackages_6.rocdbgapi.doc</li>
    <li>rocmPackages_6.rocfft</li>
    <li>rocmPackages_6.rocgdb</li>
    <li>rocmPackages_6.rocm-cmake</li>
    <li>rocmPackages_6.rocm-comgr</li>
    <li>rocmPackages_6.rocm-core</li>
    <li>rocmPackages_6.rocm-device-libs</li>
    <li>rocmPackages_6.rocm-docs-core</li>
    <li>rocmPackages_6.rocm-docs-core.dist</li>
    <li>rocmPackages_6.rocm-runtime</li>
    <li>rocmPackages_6.rocm-smi</li>
    <li>rocmPackages_6.rocm-thunk</li>
    <li>rocmPackages_6.rocminfo</li>
    <li>rocmPackages_6.rocmlir-rock</li>
    <li>rocmPackages_6.rocprim</li>
    <li>rocmPackages_6.rocprofiler</li>
    <li>rocmPackages_6.rocr-debug-agent</li>
    <li>rocmPackages_6.rocsolver</li>
    <li>rocmPackages_6.rocsparse</li>
    <li>rocmPackages_6.rocthrust</li>
    <li>rocmPackages_6.roctracer</li>
    <li>rocmPackages_6.rocwmma</li>
    <li>rocmPackages_6.rpp (rocmPackages_6.rpp-hip)</li>
    <li>rocmPackages_6.rpp-cpu</li>
    <li>rocmPackages_6.rpp-opencl</li>
    <li>rocmPackages_6.tensile</li>
    <li>rocmPackages_6.tensile.dist</li>
  </ul>
</details>

**Comment by ScatteredRay** [comment]
> I think to address this on your branch it would make sense to rebase your work onto a some state of master where all the dependencies of ROCm properly build.

Happy, to do a rebase. I can possibly find the last version that libjpeg-turbo built on, but not sure if there is any reasonable way to find a version that builds all dependents?

> I would like to have one of our branches in a state where everything builds, but it's a pain to test this since I only have 64 GB of RAM on my primary machine right now.

By everything, do you mean everything everything? Or all dependents? I have ~190GBs locally, so could possibly leave something running overnight.

**Comment by mschwaig** [comment]
> > I think to address this on your branch it would make sense to rebase your work onto a some state of master where all the dependencies of ROCm properly build.
> 
> Happy, to do a rebase. I can possibly find the last version that libjpeg-turbo built on, but not sure if there is any reasonable way to find a version that builds all dependents?

You can just use the commit that I started my branch on for the rebase. That's `f459aeeb8d1fa5930e183d0ff40ebfdaa5ffacc6`.
I don't know a good way to 'compute' that, but usually a lot of things break with big merges and then recover over time.
So you can look at how much of nixpkgs actually builds on hydra over time and pick one of the peaks, and there will be a good chance that all of the upstream dependencies are going to build. In this case I was just luckier than you.

> 
> > I would like to have one of our branches in a state where everything builds, but it's a pain to test this since I only have 64 GB of RAM on my primary machine right now.
> 
> By everything, do you mean everything everything? Or all dependents? I have ~190GBs locally, so could possibly leave something running overnight.

`nixpkgs-review` builds packages you touched and every other package that they have a downstream effect on.
The downstream stuff for ROCm is basically nothing, unless you look into setting `config.rocmSupport = true;` for `nixpkgs-review`. I have not looked into that.
> 
> > Maybe it makes sense to move this out of the draft stage or do whatever else is required so that hydra can try building it
> 
> Sounds like I should move this out of draft after I find a rebase target? Sounds good to me.

Yes it you think that everything that's supposed to work is working you can move it out of draft, which signals to people that it's ready to take a look. I don't actually know if this will trigger some infra to actually build it, or if we have to @ a bot for that. I have never worked on a PR that requires so much compute to build before, so I never had to rely on having build results visible online.

**Comment by mschwaig** [comment]
Since so far you did not rebase this branch to get rid of that issue with `libjpeg-turbo` I had a look at the diff between our branches again, and added a few commits with your changes to mine. I hope that's OK for you.

The only changes that I did not take so far where these (diff from my perspective).
```diff
diff --git a/pkgs/development/rocm-modules/6/rocm-runtime/default.nix b/pkgs/development/rocm-modules/6/rocm-runtime/default.nix
index 8c3d0cdc976d..149c9b23c933 100644
--- a/pkgs/development/rocm-modules/6/rocm-runtime/default.nix
+++ b/pkgs/development/rocm-modules/6/rocm-runtime/default.nix
@@ -16,7 +16,7 @@
 
 stdenv.mkDerivation (finalAttrs: {
   pname = "rocm-runtime";
-  version = "6.0.2";
+  version = "6.0.0";
 
   src = fetchFromGitHub {
     owner = "ROCm";
@@ -45,6 +45,7 @@ stdenv.mkDerivation (finalAttrs: {
   postPatch = ''
     patchShebangs image/blit_src/create_hsaco_ascii_file.sh
     patchShebangs core/runtime/trap_handler/create_trap_handler_header.sh
+    patchShebangs image/blit_src/create_hsaco_ascii_file.sh
     patchShebangs core/runtime/blit_shaders/create_blit_shader_header.sh
 
     substituteInPlace CMakeLists.txt \
diff --git a/pkgs/development/rocm-modules/6/rocm-thunk/default.nix b/pkgs/development/rocm-modules/6/rocm-thunk/default.nix
index 99a1d3c542d1..9e88f1c7d9f1 100644
--- a/pkgs/development/rocm-modules/6/rocm-thunk/default.nix
+++ b/pkgs/development/rocm-modules/6/rocm-thunk/default.nix
@@ -10,7 +10,7 @@
 
 stdenv.mkDerivation (finalAttrs: {
   pname = "rocm-thunk";
-  version = "6.0.2";
+  version = "6.0.0";
 
   src = fetchFromGitHub {
     owner = "ROCm";
```

I was under the impression that there would be more differences between our branches. Last time I looked I thought there  were a bunch of different hashes. I did not see a lot of that now, so there's not really a lot that I would ask in a review in terms of code, besides asking why you did https://github.com/NixOS/nixpkgs/pull/287846/commits/23a4e3ba65c66748a912d0434db8b8a2925a7619 and https://github.com/NixOS/nixpkgs/pull/287846/commits/de5d15dd586c3213c2acfac273966267d764b689, since those packages built for me without those changes.

**Comment by mschwaig** [comment]
I rented a VM again to build my PR overnight with `nixpkgs-review` (using `--checkout commit` so changes in master are not taken into account yet).

If everything builds like that I will look at building against master, or move my PR out of draft (if that's OK with you).
If there are still build failures I will ping this thread as well, to see how we can take it over the finish line.

**Comment by mschwaig** [comment]
The build for `migraphx` still fails with the following error:

```
[ 89%] Building CXX object src/targets/gpu/CMakeFiles/migraphx_gpu.dir/reverse.cpp.o
[ 89%] Building CXX object src/targets/gpu/CMakeFiles/migraphx_gpu.dir/rnn_variable_seq_lens.cpp.o
In file included from /build/source/src/targets/gpu/prefuse_ops.cpp:31:
/build/source/src/targets/gpu/include/migraphx/gpu/ck.hpp:33:10: fatal error: 'ck/host/device_gemm_multiple_d.hpp' file not found
#include "ck/host/device_gemm_multiple_d.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/targets/gpu/CMakeFiles/migraphx_gpu.dir/build.make:524: src/targets/gpu/CMakeFiles/migraphx_gpu.dir/prefuse_ops.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:13502: src/targets/gpu/CMakeFiles/migraphx_gpu.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

the only similar file I can find is https://github.com/ROCm/composable_kernel/blob/9ce18b045d6ffa6cfa29134229b422c07984ffb7/include/ck/tensor_operation/gpu/device/device_gemm_multiple_d.hpp, but that does seems like an intentional difference since that file lives in `tensor_operation/gpu/device` and not `host`.

I am not sure how to resolve this situation.

**Comment by mschwaig** [comment]
After the nightly build for https://github.com/NixOS/nixpkgs/pull/287846 there were still a few broken packages.

I fixed some of those build failures, but `migraphx`is still broken and there are still a few other things that I still need to do listed in the top comment.

**Comment by ScatteredRay** [comment]
Thanks for working on that. I've been away for a bit. Going to check it out a bit this weekend.

**Comment by ScatteredRay** [comment]
Took a look through hydra, it looks like 12f69cd4858b6853113ba918119400df8a9e2205 might have been the last successful build of rocmPackages_5 ?

**Comment by mschwaig** [comment]
I have not looked into the specific commit that you mentioned, but `rocmPackages_5.rocprofiler` has been failing on up to date master for me.

I have found the files that were missing from the `migraphx` build. I hope that will run through now.
I have opened my PR for reviews now.

Is it OK for you if I merge some of your changes that way?

**Comment by ScatteredRay** [comment]
> Since my PR has some of your changes I wanted to ask if it would be OK for you if I merge some of your changes that way?

Of course merge away

**Comment by ulrikstrid** [comment]
Hey, I'm currently trying to use this with Ollama, rocblas seems to just get stuck forever on `4 warnings generated when compiling for gfx942`

I'm also running a `nixpkgs-review` on this PR and at least `rocmlir-rock`and `rocmlir` are broken

**Pull request closed without merging**
