### PR TITLE
recapp: init at 1.1.1

### LINKED ISSUE #121067: Package RecApp
**Project description**

> User friendly Open Source screencaster for Linux written in GTK. Using free GStreamer modules and not depend on FFmpeg.

simplescreenrecorder is not that user-friendly and has problems (https://github.com/NixOS/nixpkgs/issues/43434). right now i use OBS, but it's overkill for the task. maybe this is a good alternative

**Metadata**

* homepage URL: https://github.com/amikha1lov/RecApp
* source URL: https://github.com/amikha1lov/RecApp
* license: GPL-3.0-or-later ([source](https://github.com/amikha1lov/RecApp/blob/master/rpm/recapp.spec#L10))
* platforms: linux, more?

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
fixes https://github.com/NixOS/nixpkgs/issues/121067

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>recapp</li>
  </ul>
</details>

**Comment by davidak** [comment]
@dotlambda thanks for packaging it!

For some reason, it does not look like in the screenshots.

Screenshot from 2021-04-29 21-13-18

The option "record window" and "record microphone" is missing.

Maybe it does only work properly on GNOME and not on Pantheon desktop? Or maybe because i run it in a nix-shell?

When i click the "record selection" button, i get this error:

```
/nix/store/68c5b0h2w2ab57sbas1b4m073ik8hlm5-bash-4.4-p23/bin/sh: slop: command not found
Traceback (most recent call last):
  File "/nix/store/7j22c5swgsrdw6gr8kkwx90gimwb5gji-recapp-1.1.1/share/recapp/recapp/window.py", line 198, in on__select_area_button_clicked
    on__select_area(self)
  File "/nix/store/7j22c5swgsrdw6gr8kkwx90gimwb5gji-recapp-1.1.1/share/recapp/recapp/rec.py", line 103, in on__select_area
    if not listCoor[0] or not listCoor[1]:
IndexError: list index out of range
```

---

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.109, NixOS, 20.09.3786.a7ff7a57c96 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.3786.a7ff7a57c96, nixos-hardware, nixos-unstable-21.05pre282015.a73020b2a15"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>recapp</li>
  </ul>
</details>

**Review by davidak — CHANGES_REQUESTED** [review]
add slop

check style issue

**Comment by dotlambda** [comment]
> The option "record window" and "record microphone" is missing.
> 
> Maybe it does only work properly on GNOME and not on Pantheon desktop? Or maybe because i run it in a nix-shell?

I think that's an upstream issue.

> check style issue

What do you mean?

**Comment by dotlambda** [comment]
> The option "record window" and "record microphone" is missing.

Actually, that feature only exists in upstream's master: https://github.com/amikha1lov/RecApp/tree/v1.1.1

**Comment by davidak** [comment]
oh, yeah. that looks like my screenshot and it looks really ugly compared to their new design. we will have it in the next release :)

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>recapp</li>
  </ul>
</details>

**Comment by davidak** [comment]
selecting an area to record now works, but i don't have audio anymore. that definitely worked on the first system i tested

**Comment by dotlambda** [comment]
> but i don't have audio anymore. that definitely worked on the first system i tested

still works for me, also in combination with selecting an area

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>recapp</li>
  </ul>
</details>

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>recapp</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> @dotlambda on what system did you test?

I tested on i3 on unstable.

**Comment by OPNA2608** [comment]
It's doubly-wrapped, please fix that (disable the automatic gapps wrapping hook & add its arguments to the python wrapper's flags list instead iirc)

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>recapp</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> i don't have audio anymore. that definitely worked on the first system i tested

Seems to be a common issue: https://github.com/amikha1lov/RecApp/issues/51
@davidak Were there any other problems remaining?

**Comment by davidak** [comment]
now a have audio. looks good

**Review by davidak — APPROVED** [review]

**Pull request merged**
