### PR TITLE
electron_29-bin: mark as insecure because it's EOL, electron-source.electron_29: remove as it's EOL

### PR DESCRIPTION
**Pull request by emilylange**
## Description of changes

`electron_29` will be EOL tomorrow (2024-08-20), as per <https://www.electronjs.org/docs/latest/tutorial/electron-timelines>.

Packages that depend on `electron_29` and as such will require the user to opt-into the `knownVulnerabilities`.

- [ ] `antares`: @hatch01 https://github.com/NixOS/nixpkgs/pull/335924
- [x] `bitwarden-desktop`: @amarshall https://github.com/NixOS/nixpkgs/pull/337164
- [ ] `breitbandmessung`: @B4dM4n
- [x] `heroic`: @aidalgol #335737
- [ ] `kuro`: @LostAttractor
- [x] `morgen`: @justanotherariel #336026
- [ ] `passky-desktop`: @akkesm
- [ ] `teams-for-linux`: @muscaln @qjoly @chvp https://github.com/NixOS/nixpkgs/pull/337868
- [x] `webcord-vencord`: @FlafyDev @NotAShelf https://github.com/NixOS/nixpkgs/pull/335876

Related: #333907 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NotAShelf** [comment]
I'll take a look at bumping webcord-vencord's electron version - if upstream supports it.

**Comment by emilylange** [comment]
> Not sure I fully understood what I should do.
> Should I create a PR for Antares with the value knownVulnerability set to the same as you for electron29 ?
> Or will nix prevent user automatically because Antares depend in electron29.

If this PR gets merged as is, the following would happen: 

```shell
# nix-build -A antares
error:
       … while evaluating 'strict' to select 'drvPath' on it
         at /builtin/derivation.nix:1:552:
       … while calling the 'derivationStrict' builtin
         at /builtin/derivation.nix:1:208:
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘electron-29.4.5’ in ./pkgs/development/tools/electron/binary/generic.nix:36 is marked as insecure, refusing to evaluate.


       Known issues:
        - Electron version 29.4.5 is EOL

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) for `nixos-rebuild` you can add ‘electron-29.4.5’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "electron-29.4.5"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘electron-29.4.5’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "electron-29.4.5"
              ];
            }
```

> I can also just quickly create a PR to switch to electron30 which seems supported.

That would be great and exactly what I wanted to get across without actually spelling it out.
Sorry for that.

Sometimes it's as simple as keeping the current version and bumping electron, other times it may require upstream to release a newer version.
It's up to the package maintainers to figure out and decide.

**Comment by hatch01** [comment]
#335924
I'm am working on it but facing some issue with the npm deps.

**Comment by SuperSandro2000** [comment]
Lets wait a day or two until we have reviewed and merged the linked PRs. We are in no rush here.

**Comment by SuperSandro2000** [comment]
We are a bit stuck with #330137, so some help is appreciated.

**Comment by emilazy** [comment]
This should be backported to 24.05 after https://github.com/NixOS/nixpkgs/pull/336018, right?

**Comment by emilylange** [comment]
Yes, should get backported.

@ofborg eval

**Comment by hatch01** [comment]
@emilylange my pr for antares (#335924) is ready for review !

**Comment by emilazy** [comment]
Backports in progress:

* https://github.com/NixOS/nixpkgs/pull/337322
* https://github.com/NixOS/nixpkgs/pull/337312
* https://github.com/NixOS/nixpkgs/pull/337320

Seems unlikely we’ll get more PRs beyond the `antares` one in a timely fashion at this point?

**Comment by NotAShelf** [comment]
I can pick one or two programs if maintainers don't respond.

**Comment by emilazy** [comment]
That’d be nice :) But if there’s no active maintainers for a package we’ll probably run into the same situation with them again next time an Electron version goes EOL, so if you don’t want to adopt any of them and no maintainer appears to sort them out it might be better in the long run to let nature take its course.

(Hypocritical of me to say given the amount of time I’ve spent patching abandoned packages for newer FFmpegs lately, though…)

**Review by teutat3s — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by NotAShelf** [comment]
Seeing no maintainers responded, I'll pick up `kuro` and *maybe* `teams-for-linux`. 

Kuro seems to work with electron_30 just fine (despite upstream still providing electron 22, may be a problem in the future). teams-for-linux needs testing.

This should not be considered a blocker though, as I might need a day to create the PRs.

**Comment by emilazy** [comment]
I’ll handle the backport.

**Comment by khaneliman** [comment]
> Seeing no maintainers responded, I'll pick up `kuro` and _maybe_ `teams-for-linux`.
> 
> Kuro seems to work with electron_30 just fine (despite upstream still providing electron 22, may be a problem in the future). teams-for-linux needs testing.
> 
> This should not be considered a blocker though, as I might need a day to create the PRs.

I got an open PR out for `teams-for-linux` raf.

**Pull request merged**
