### PR TITLE
Update Haskell package set to LTS 15.1 (plus other fixes)

### PR DESCRIPTION
**Pull request by peti**
This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on Friday, 2020-02-29 [20:00 CET](http://www.thetimezoneconverter.com/?t=21:00&tz=Berlin). You can watch this live on Twitch at https://www.twitch.tv/peti343.

## TODO

- [x] Switch default compiler to ghc-8.8.2.
- [x] Update list of core libraries and compiler version in `hackage2nix.yaml`.
- [ ] Try to revive `haskell-ci` build.
- [ ] Try running `krank` on our override files.
- [ ] https://github.com/NixOS/docker/pull/13

### CODE REVIEW

**Comment by peti** [comment]
I have to postpone the merging session to the weekend. :-( Hydrated isn't working properly and we have >1000 (bogus) build errors. I can't merge the branch in that state.

Also, to make matters worse, I have a bad cold and rather go to bed early tonight anyway. I'll tackle this PR again over the weekend.

**Comment by domenkozar** [comment]
Please wait before merging this a couple of days so that I can fix my packages.

**Comment by domenkozar** [comment]
@peti seems like the title says LTS-15.0, but this branch is still using LTS-14.x

**Comment by domenkozar** [comment]
@GrahamcOfBorg build cachix

**Comment by peti** [comment]
Next week we'll merge https://github.com/NixOS/nixpkgs/pull/81543.

**Pull request merged**
