### PR TITLE
nushell: 0.93.0 -> 0.94.0

### PR DESCRIPTION
**Pull request by getchoo**
## Description of changes

Diff: https://github.com/nushell/nushell/compare/0.93.0...0.94.0
Release notes: https://www.nushell.sh/blog/2024-05-28-nushell_0_94_0.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PigeonF** [comment]
The `nushellFull` package [attempts to build the `dataframe` feature](https://github.com/getchoo/nixpkgs/blob/9a326e227e49c269e60c894449afb728c114754b/pkgs/top-level/all-packages.nix#L27496), which [has been removed in this nushell release](https://www.nushell.sh/blog/2024-05-28-nushell_0_94_0.html#breaking-changes-toc).

**Review by JoaquinTrinanes — CHANGES_REQUESTED** [review]
With the [`dataframe`](https://github.com/nushell/nushell/pull/12889) and [`extra`](https://github.com/nushell/nushell/pull/12140) features gone, `nushellFull` should probably be removed altogether (or, at least, deprecated).

I don't know what the standard way of doing it is, between [`throw`ing an error message](https://github.com/NixOS/nixpkgs/blob/bebc70c2e74d0f7fffe7638d989bad2d2baf7c05/pkgs/top-level/aliases.nix#L673) informing of the change, showing a warning or just removing it 🤔 

https://github.com/NixOS/nixpkgs/blob/bebc70c2e74d0f7fffe7638d989bad2d2baf7c05/pkgs/top-level/all-packages.nix#L27500

Other than that, it builds fine for me. Thanks!

**Comment by getchoo** [comment]
>  nushellFull should probably be removed altogether (or, at least, deprecated).

totally forgot about the full version! i've aliased to `nushell` with a warning for now. i think it'd be a good idea to fully remove this closer to the release of 24.11 in a few months

backporting this to 24.05 as well since this isn't a breaking change and stable users can be alerted of the deprecation

**Review by JoaquinTrinanes — APPROVED** [review]
Thanks!

**Comment by dairyisscary** [comment]
nice cleanup!

i also noticed this package is not doing it check phase(changed a few months back because of some broken tests in fe856f46a11df0ef160d890fcc94e3e0eded7e50).

```nix
, doCheck ? false
```
can that be changed back to `true` with this release?

**Comment by dairyisscary** [comment]
wow 0.94.1 is also out 👀 https://www.nushell.sh/blog/2024-05-30-nushell_0_94_1.html

**Comment by getchoo** [comment]
> can that be changed back to true with this release?

i tried this when first updating the package but it looks like we still have some failures with xdg dirs :/
i'll try again with 0.94.1

**Comment by giggio** [comment]
Nushell 0.94.1 just came out. https://www.nushell.sh/blog/2024-05-30-nushell_0_94_1.html

**Comment by drupol** [comment]
@getchoo Do you mind updating to the very latest version?

**Comment by dairyisscary** [comment]
I took @getchoo's great work into https://github.com/NixOS/nixpkgs/pull/316690 that has the plugins updated and is version 0.94.1

**Comment by SuperSandro2000** [comment]
see #316690

**Pull request closed without merging**
