### PR TITLE
nixos/btsync: remove

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Remove the btsync module. Bittorrent Sync was renamed to Resilio Sync in
2016, which is supported by the resilio module. Since Resilio Sync had
some security updates since 2016, it is not safe to run Bittorrent Sync
anymore.

I will do a separate PR after this one to remove Bittorrent Sync itself (if there are no objections).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
@danieldk :+1: for me, but I guess you can add a second commit to this PR removing the package, too.

**Review by fpletz — APPROVED** [review]

**Comment by worldofpeace** [comment]
I think it would be best to remove the actual package in this pr as well.
Also adding a `trace` to `aliases.nix` with a message as to why it's removed, essentially that they should use the program that now supersedes it.

Can't remember if there's something similar for nixos modules.

**Comment by davidak** [comment]
Maybe add a line to the release notes in the docs? So when people upgrade and still use this module, they know what to do.

**Comment by danieldk** [comment]
Thanks for the suggestions! I'll incorporate them in this PR.

**Comment by danieldk** [comment]
Ok, I hope all bases are covered now.

**Review by flokli — APPROVED** [review]

**Review by davidak — APPROVED** [review]

**Pull request merged**
