### PR TITLE
oapi-codegen: 1.13.0 -> 1.13.3

### PR DESCRIPTION
**Pull request by sagikazarmark**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — COMMENTED** [review]
It would be nice to link to the changelog in the commit message. Nix-update does so automatically.

**Comment by j4m3s-s** [comment]
Result of `nixpkgs-review pr 246450` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>oapi-codegen</li>
  </ul>
</details>

**Comment by sagikazarmark** [comment]
https://github.com/deepmap/oapi-codegen/releases/tag/v1.13.2

**Comment by sagikazarmark** [comment]
https://github.com/deepmap/oapi-codegen/releases/tag/v1.13.3

**Comment by j4m3s-s** [comment]
@sagikazarmark I think what @dotlambda meant is to include the content of the changelog into the commit body. (or the link to it maybe?).
Otherwise LGTM, thanks for updating it!

**Review by j4m3s-s — APPROVED** [review]

**Comment by j4m3s-s** [comment]
@sagikazarmark Seems another version was released, maybe you should update this PR

**Comment by sagikazarmark** [comment]
Looks like another PR has been merged in the meantime.

**Pull request closed without merging**
