### PR TITLE
glibc: 2.31 -> 2.32

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

This should be targeted against `21.03` or a later release.

Upstream ChangeLog: https://sourceware.org/pipermail/libc-announce/2020/000029.html
Hydra Jobset: https://hydra.nixos.org/jobset/nixpkgs/glibc-232

I already tested a few packages (including several `gcc` versions and `llvm7`) on the [aarch64 community builder](https://github.com/nix-community/aarch64-build-box/) and on my personal `x86_64-linux` builder.

Please note that this is targeted against `staging-next` on purpose. This makes it easier to find new regressions when comparing against the [`staging-next`](https://hydra.nixos.org/jobset/nixpkgs/staging-next) jobset on Hydra.

###### Things done

- [x] Create Hydra jobset (cc @vcunat @FRidh, I guess we can reuse the config of https://hydra.nixos.org/jobset/nixpkgs/glibc-231) 
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [ ] Retarget against `upstream/staging` before merging.
- [ ] Mention sunrpc removal in release-notes

### CODE REVIEW

**Comment by vcunat** [comment]
From a previous glance at announcement, we're still passing two `--enable-obsolete-*` flags that should be gone now.  That also means those parts will be gone, but hopefully noone has been using them anymore.

**Comment by Ma27** [comment]
Thanks for pointing this out, you're absolutely right! In fact, I already removed obsolete sunrpc patches that aren't needed anymore because of one of those flags being removed :+1: 

@vcunat btw, can you add a new Hydra jobset for this, please? :)

**Comment by vcunat** [comment]
[Created](https://hydra.nixos.org/jobset/nixpkgs/glibc-232), for now only x86_64.

**Comment by Ma27** [comment]
Nice, thanks! :)

**Comment by Ma27** [comment]
Btw git (https://hydra.nixos.org/build/125038989) builds locally for me.

**Comment by Ma27** [comment]
> From a previous glance at the announcement, we're still passing two --enable-obsolete-* flags that should be gone now. That also means those parts will be gone, but hopefully noone has been using them anymore.

Well, unfortunately there are some packages using those. Some packages can be fixed by simply adding `libtirpc` (and for `rpcgen` we can use `rpcsvc-proto` which I packaged on this branch), however there are some packages that don't work with this and need fixed like this:

``` nix
mkDerivation {
  /* ... */
  
  NIX_CFLAGS_COMPILE = [ "-I${libtirpc.dev}/include/tirpc" ];
  NIX_LDFLAGS = [ "-ltirpc" ];
}
```

I added a note to the OP to remind myself to mention this in the release-notes.

**Comment by Ma27** [comment]
@vcunat in case you have time to, could you please restart the `git`-build (https://hydra.nixos.org/build/125051048)? I repeatedly managed to build it locally without any issues.

**Comment by vcunat** [comment]
- [x] succeeded

**Comment by vcunat** [comment]
Have you thought about which NixOS release this would be in?  (I haven't looked into how "risky" this PR is.)  #95475

**Comment by Ma27** [comment]
> Have you thought about which NixOS release this would be in? (I haven't looked into how "risky" this PR is.)

Probably 21.03: there are actually quite many packages using this `rpc`-stuff from `glibc` and right now we don't provide a replacement since we don't ship another `rpcgen` (fixed it on this branch in https://github.com/NixOS/nixpkgs/pull/95089/commits/2085f655990d1011bac1a8a95df8cf3be70ecec1), so downstream pkgs relying on this can't really migrate atm.

**Comment by Ma27** [comment]
Fixed a few more things and rebased onto latest `staging-next`. Eval for that is running now.

**Comment by Ma27** [comment]
The new breakage is caused by a regression from `upstream/staging-next` that doesn't seem to be fixed yet:

```
qtquickcontrols> mkdir: cannot create directory '/nix/store/14kfh0l6627kvvvlg29l8nmjmzp33ipa-qtdeclarative-5.14.2-bin/lib/qt-5.14.2/qml/QtQuick/Controls': Permission denied
qtquickcontrols> make[2]: *** [Makefile:1642: install_qmlcacheinst] Error 1
qtquickcontrols> make[2]: Leaving directory '/build/qtquickcontrols-everywhere-src-5.14.2/src/controls'
qtquickcontrols> make[1]: *** [Makefile:64: sub-controls-install_subtargets] Error 2
qtquickcontrols> make[1]: Leaving directory '/build/qtquickcontrols-everywhere-src-5.14.2/src'
qtquickcontrols> make: *** [Makefile:61: sub-src-install_subtargets] Error 2
qtquickcontrols> builder for '/nix/store/0yb3ds49jb1qzmf14xypdqrkqcx7qxm8-qtquickcontrols-5.14.2.drv' failed with exit code 2
```

**Comment by Ma27** [comment]
Rebased onto latest `staging-next` to incorporate the QT fix. Now the ~900 broken packages because of that should be buildable again.

**Review by FRidh — APPROVED** [review]
I think this is ready to merge into *staging*.

**Comment by vcunat** [comment]
Current evaluation is based on a staging-next commit that exactly has evaluation as well: https://hydra.nixos.org/eval/1612151?compare=1611941#tabs-now-fail

I'd hope that the current state is good enough for merging, but we'll see more after the rebuilds progress further.  It certainly does not need to solve regressions in every single package.

**Comment by FRidh** [comment]
If we agree this is ready to go then we could abort the remaining builds.

**Comment by Ma27** [comment]
I'd probably wait until the current evaluation is complete just to be sure. After that I'd rebase this onto `staging` if that's okay for you @vcunat @FRidh  :)

**Comment by vcunat** [comment]
I used the community aarch64 box to build some of the packages modified above, without encountering any failure.  Overall I don't expect noticeable platform-specific issues from the update.

**Comment by Ma27** [comment]
@vcunat great, thanks!

Just rebased onto latest `staging`, resolved one merge-conflict and marked this as ready to review. Feel free to take a final look and merge if nothing else is missing :)

**Pull request merged**
