### PR TITLE
squeekboard: 1.17 -> 1.20

### PR DESCRIPTION
**Pull request by tomfitzhenry**
###### Description of changes

* bump to 1.20

Set `-Dnewer=true` as Debian does, to use a newer non-broken set of
Cargo dependencies: https://gitlab.gnome.org/World/Phosh/squeekboard/-/blob/d19050e06d2ecc5218e50e9ef3a5279afa0daff8/debian/rules#L41

Tested on my Pinephone Pro.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Ofborg failed with
error: hash mismatch in fixed-output derivation '/nix/store/m8w9wx557kkv655sc7nzkhcr0vh01vrx-squeekboard-1.19.0-vendor.tar.gz.drv':
         specified: sha256-zK1O8GYVCtxqPpFBmEMYPCo8LgtY9JAGFMctVdAw+Sk=
            got:    sha256-m1EiqzjG57fExmIlMY1qFS47c5qbb+TlnTIRXNL/hiY=
error: 1 dependencies of derivation '/nix/store/34qag0b6fgxvpsviylxxywyqhv1l0l3j-squeekboard-1.19.0.drv' failed to build

**Comment by Artturin** [comment]
Still fails

**Comment by chuangzhu** [comment]
> The `sha256` of the `cargoDeps` field appears to be changing every so often.

This is because the original `Cargo.lock` is generated from `Cargo.deps`, not `Cargo.deps.newer`, so it gets regenerated each run. This could be solved by upgrading to [v0.20.0](https://gitlab.gnome.org/World/Phosh/squeekboard/-/tags/v1.20.0), which includes a [`Cargo.lock.newer`](https://gitlab.gnome.org/World/Phosh/squeekboard/-/blob/v1.20.0/Cargo.lock.newer) file.

**Review by chuangzhu — APPROVED** [review]
Result of `nixpkgs-review pr 184813` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>squeekboard</li>
  </ul>
</details>

**Comment by Artturin** [comment]
it's not controversial, feel free to add yourself

**Review by Artturin — CHANGES_REQUESTED** [review]
```
[nix-shell:~/.cache/nixpkgs-review/pr-184813]$ ./results/squeekboard/bin/squeekboard-entry
Traceback (most recent call last):
  File "/nix/store/bawdp51jgbvq057ci35gzm1kyi8m78k0-squeekboard-1.20.0/bin/.squeekboard-entry-wrapped", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

adding gobject-introspection to nativeBuildInputs should fix this

**Comment by Artturin** [comment]
maybe not, it'll require python wrapping.

**Pull request merged**
