### PR TITLE
gem-config.mathematical: add lasem to rpath

### PR DESCRIPTION
**Pull request by Twey**
###### Motivation for this change
Without this change, `mathematical` is broken, which breaks (presumably among other things) the `asciidoctor-mathematical` gem.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Twey** [comment]
Bump!

**Comment by Twey** [comment]
@evils I think you might be interested in this one as well?  As it's also to do with asciidoctor.

**Comment by evils** [comment]
thanks but i was mostly interested in getting rid of a dangling symlink

this PR increases the closure size of `asciidoctor`
from `337247856` to `343880800`

though it seems like with the closing of RFC 0064 ReST is the preferred format making this less of a concern

`nixpkgs-review` result:
<details>
  <summary>3 packages failed to build:</summary>
<br>- deepin.dde-file-manager
<br>- deepin.startdde
<br>- rabbitvcs
</details>
<details>
  <summary>99 packages built:</summary>
<br>- adapta-gtk-theme
<br>- almanah
<br>- asciidoctor
<br>- atom
<br>- atom-beta
<br>- awesome
<br>- bat-extras.batgrep
<br>- btrbk
<br>- calls
<br>- cantata
<br>- chrome-gnome-shell
<br>- cinnamon.cinnamon-control-center
<br>- clementine
<br>- clementineUnfree
<br>- deja-dup
<br>- dropbox-cli
<br>- elementary-planner
<br>- empathy
<br>- enlightenment.enlightenment
<br>- esh
<br>- evolution-data-server (evolution_data_server)
<br>- far2l
<br>- feedreader
<br>- folks
<br>- gfbgraph
<br>- gnome-multi-writer
<br>- gnome-online-accounts
<br>- gnome-photos
<br>- gnome-recipes
<br>- gnome2.gvfs
<br>- gnome3.bijiben
<br>- gnome3.cheese
<br>- gnome3.evolution
<br>- gnome3.file-roller
<br>- gnome3.geary
<br>- gnome3.gnome-applets
<br>- gnome3.gnome-books
<br>- gnome3.gnome-boxes
<br>- gnome3.gnome-calendar
<br>- gnome3.gnome-contacts
<br>- gnome3.gnome-control-center
<br>- gnome3.gnome-disk-utility
<br>- gnome3.gnome-documents
<br>- gnome3.gnome-flashback
<br>- gnome3.gnome-initial-setup
<br>- gnome3.gnome-maps
<br>- gnome3.gnome-music
<br>- gnome3.gnome-online-miners
<br>- gnome3.gnome-panel
<br>- gnome3.gnome-session
<br>- gnome3.gnome-shell
<br>- gnome3.gnome-software
<br>- gnome3.gnome-terminal
<br>- gnome3.gnome-todo
<br>- gnome3.gnome-tweak-tool
<br>- gnome3.gnome-user-share
<br>- gnome3.grilo-plugins
<br>- gnome3.gvfs
<br>- gnome3.libgdata
<br>- gnome3.libzapojit
<br>- gnome3.nautilus
<br>- gnome3.nautilus-python
<br>- gnome3.pomodoro
<br>- gnome3.shotwell
<br>- gnome3.totem
<br>- gnome3.tracker-miners
<br>- gnomeExtensions.gsconnect
<br>- hal-flash
<br>- libblockdev
<br>- libndctl
<br>- mate.mate-utils
<br>- newsboat
<br>- pantheon.elementary-calendar
<br>- pantheon.elementary-greeter
<br>- pantheon.elementary-session-settings
<br>- pantheon.extra-elementary-contracts
<br>- pantheon.wingpanel-indicator-datetime
<br>- pantheon.wingpanel-with-indicators
<br>- pmdk
<br>- psensor
<br>- rapid-photo-downloader
<br>- ripgrep
<br>- ripgrep-all
<br>- spaceFM
<br>- styx
<br>- udiskie
<br>- udisks
<br>- usermount
<br>- vifm-full
<br>- weechat
<br>- weechat-unwrapped
<br>- wsjtx
<br>- xfce.gigolo
<br>- xfce.gvfs
<br>- xfce.thunar (xfce.thunar-bare)
<br>- xfce.thunar-archive-plugin
<br>- xfce.thunar-dropbox-plugin
<br>- xfce.xfdesktop
<br>- xmonad_log_applet (xmonad_log_applet_gnome3)
</details>

**Comment by SuperSandro2000** [comment]
@Twey please resolve the merge conflict.

**Comment by dcbaker** [comment]
Any chance of this getting updated? I'm running into this now.

**Pull request closed without merging**
