### PR TITLE
Update grub to latest upstream release

### PR DESCRIPTION
**Pull request by dezgeg**
There has been some upstream activity recently, let's update to the
latest upstream tag. Yes, it's -rc1 but that should be an improvement
over a year-and-a-half olf random git commit.

I guess it could be worth to get this to 17.03? cc @edolstra @globin.

I have tested this on one machine with ext4 rootfs and no separate boot. Also the installer tests I've tried pass. Would be nice to have a bit more testing, though.

### CODE REVIEW

**Comment by dezgeg** [comment]
I gave this a try on the machine I have XFS+Grub and it worked, but didn't fix the problems as in #11650.

**Review by fpletz — APPROVED** [review]

**Comment by grahamc** [comment]
Shall we merge?

**Comment by dezgeg** [comment]
It did not fix my `/boot`-on-XFS problem as I had hoped, so no good reason to get into 17.03. Let's wait .

**Comment by 7c6f434c** [comment]
@dezgeg @grahamc @fpletz I think 17.03 has happened, do we merge it now?

**Comment by orivej** [comment]
grub has been updated to 2.02 in 3317c71c5c629939e434288390c1d26506160d13, but the tests here look useful.

**Comment by fpletz** [comment]
Fixed the merge conflict in the test and pushed it to master.

**Pull request closed without merging**
