### PR TITLE
cargo-edit: 0.4.1 -> 0.4.2

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/killercup/cargo-edit/releases/tag/v0.4.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
```
/nix/store/i94wymlizbhdgdpbjgiaklx3y8hwh1q6-cargo-edit-0.4.1	  45.1M
/nix/store/qk1075rapncsxcp3brc4vkk9wkq7dhk5-cargo-edit-0.4.2	  44.7M
```
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Gerschtli @jb55 @oxalica

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/75052)

### CODE REVIEW

**Review by Gerschtli — APPROVED** [review]
LGTM

**Review by oxalica — APPROVED** [review]
LGTM.

**Comment by killercup** [comment]
Huh, so this didn't build for me on macOS and I had to

```diff
diff --git a/pkgs/tools/package-management/cargo-edit/default.nix b/pkgs/tools/package-management/cargo-edit/default.nix
index 51c6def02c1..bad92e2c1a1 100644
--- a/pkgs/tools/package-management/cargo-edit/default.nix
+++ b/pkgs/tools/package-management/cargo-edit/default.nix
@@ -1,6 +1,6 @@
 { stdenv, lib, darwin
 , rustPlatform, fetchFromGitHub
-, openssl, pkgconfig }:
+, openssl, pkgconfig, libiconv }:
 
 rustPlatform.buildRustPackage rec {
   pname = "cargo-edit";
@@ -16,7 +16,7 @@ rustPlatform.buildRustPackage rec {
   cargoSha256 = "0prd53p20cha2y2qp8dmq0ywd32f6jm8mszdkbi4x606dj9bcgbl";
 
   nativeBuildInputs = lib.optional (!stdenv.isDarwin) pkgconfig;
-  buildInputs = lib.optional (!stdenv.isDarwin) openssl;
+  buildInputs = [ openssl ] ++ lib.optionals stdenv.isDarwin [ libiconv ];
   propagatedBuildInputs = lib.optional stdenv.isDarwin darwin.apple_sdk.frameworks.Security;
 
   meta = with lib; {
```

Can someone verify that this isn't just my broken setup?

**Comment by filalex77** [comment]
@killercup ofBorg had the same issue. I'll patch it now.

**Comment by filalex77** [comment]
@GrahamcOfBorg build cargo-edit

**Comment by filalex77** [comment]
@GrahamcOfBorg build cargo-edit

**Review by Gerschtli — APPROVED** [review]
Built locally and tested binaries, LGTM

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
