### PR TITLE
thunderbird-bin: 38.3.0 -> 38.4.0

### PR DESCRIPTION
**Pull request by taku0**
- Various security fixes
- Fixed issue where messages moves of multiple messages from a maildir folder to an mbox folder failed.

https://www.mozilla.org/en-US/thunderbird/38.4.0/releasenotes/

Unfortunately, Mozilla now provides only SHA512SUMS but not SHA1SUMS, and Nix does not support SHA-512 hash yet, so that I have to download all archives to calculate SHA-256 hashes when updating the sources.nix.

### CODE REVIEW

**Comment by taku0** [comment]
cc: @Fuuzetsu

**Comment by vcunat** [comment]
Nix does support sha-512 already https://github.com/NixOS/nix/issues/679, but it's too new to depend on it. (The addition seems to have been spurred by the Mozilla move.)

**Comment by taku0** [comment]
I didn't notice that. I will update firefox-bin/thunderbird-bin when it is incorporated into stable version of nix.

**Comment by vcunat** [comment]
I think in the next nixos release branch we shall depend on sha-512 support.

**Comment by copumpkin** [comment]
@vcunat @taku0 I was thinking that once sha512 support lands in a dependable manner (i.e., nixpkgs refuses to run with an older Nix), we could actually do an import-from-derivation for firefox and thunderbird.

What I'm thinking is that we would bundle a single fixed-output derivation for the `SHA512SUMS` in every firefox/thunderbird release, then run a simple script that processes that into a JSON/nix file and import that to get the rest of our fixed-output derivation hashes. Is that reasonable? I'd like to reduce the amount of autogenerated code in nixpkgs since it's hard to track where it came from, and we already have a pretty good mechanism in Nix itself for doing that sort of thing.

**Comment by taku0** [comment]
Does import-from-derivation mean something like follows?

```
let
  version = "38.5.0";

  hashesDeriv = stdenv.mkDerivation {
    name = "thunderbird-bin-hashes-${version}";
  
    src = fetchurl {
      url = "http://archive.mozilla.org/pub/thunderbird/releases/${version}/SHA512SUMS";
      sha512 = "...";
    };
  
    phases = "installPhase";
  
    installPhase =
      ''
        # generates nix expression of following form from SHA512SUMS
        # [
        #  { locale = "ar"; arch = "linux-i686"; sha512 = "..."; }
        #  ...
        # ]
      '';
  };

  sources = import ${hashesDeriv}/sources.nix;

  ...

  source = ...;

in

stdenv.mkDerivation {
  name = "thunderbird-bin-${version}";

  src = fetchurl {
    url = "http://download-installer.cdn.mozilla.net/pub/thunderbird/releases/${version}/${source.arch}/${source.locale}/thunderbird-${version}.tar.bz2";
    inherit (source) sha512;
  };

  ...
}
```

It sounds great. Commiting large list of hashes is not nice.

**Comment by vcunat** [comment]
Fetchurl hashes are needed during *evaluation* time. It's considered impolite in nixpkgs when evaluation depends on some derivation results, as it means "building" happens even when you `--dry-run`, etc.

**Comment by copumpkin** [comment]
@taku0 yup, something like that

@vcunat is it that bad? I don't think `nix-env` would trigger the download, right? It would only happen if you did things like a dry-run or forced the derivation? Compared to putting tons of autogenerated crap in our source repository (which is getting hard to manage already with just `haskellPackages`, and will only get worse as we import and autogenerate more package ecosystems), it seems appealing.

**Comment by vcunat** [comment]
Even `nix-env -qas` would do that.

**Pull request merged**
