### PR TITLE
hyprland: 0.45.2 -> 0.46.1;  hyprland-plugins.*: version bumps and update script tweaks

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done
https://github.com/hyprwm/Hyprland/releases/tag/v0.46.0
https://github.com/hyprwm/Hyprland/releases/tag/v0.46.1

Added @fufexan to hyprgraphics maintainers.

Bumped all the available plugins and migrated to use the nix-update-script. It is more stable, from what I've seen. 

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ddogfoodd — COMMENTED** [review]
the plugins failed to build, that's usually the case with hyprland updates right? If so, I would approve.
Otherwise works for me on x86_64-linux

**Comment by khaneliman** [comment]
Updated most of the plugins, some of them have no updates available or are tracking releases and have not been cut.

**Comment by fufexan** [comment]
LGTM. Also, 0.46.1 is out with some windowrules fixes.

**Comment by khaneliman** [comment]
> LGTM. Also, 0.46.1 is out with some windowrules fixes.

Hmm.. don't see the tag yet

**Comment by fufexan** [comment]
Ah, my bad. Vaxry is still in the process of creating the release. And yes, I'd wait for it since 0.46.0 has some broken windowrule matching.

I've also pushed the v0.46.0 tag for hyprland-plugins.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365776`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>hyprlandPlugins.hycov</li>
  </ul>
</details>
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>hyprlandPlugins.hy3</li>
    <li>hyprlandPlugins.hyprfocus</li>
    <li>hyprlandPlugins.hyprsplit</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 22 packages built:</summary>
  <ul>
    <li>grimblast</li>
    <li>hdrop</li>
    <li>hyprland</li>
    <li>hyprland.dev</li>
    <li>hyprland.man</li>
    <li>hyprlandPlugins.borders-plus-plus</li>
    <li>hyprlandPlugins.csgo-vulkan-fix</li>
    <li>hyprlandPlugins.hypr-dynamic-cursors</li>
    <li>hyprlandPlugins.hyprbars</li>
    <li>hyprlandPlugins.hyprexpo</li>
    <li>hyprlandPlugins.hyprgrass</li>
    <li>hyprlandPlugins.hyprscroller</li>
    <li>hyprlandPlugins.hyprspace</li>
    <li>hyprlandPlugins.hyprtrails</li>
    <li>hyprlandPlugins.hyprwinwrap</li>
    <li>hyprshade</li>
    <li>hyprshade.dist</li>
    <li>hyprshot</li>
    <li>nwg-panel</li>
    <li>nwg-panel.dist</li>
    <li>waybar</li>
    <li>xdg-desktop-portal-hyprland</li>
  </ul>
</details>

**Comment by fufexan** [comment]
@khaneliman could you also make a change in `mkHyprlandPlugins`? This line should actually be `hyprland.stdenv.mkDerivation`:
https://github.com/NixOS/nixpkgs/blob/2d56a4c4cedd050b5a0384080903c25d2806073c/pkgs/applications/window-managers/hyprwm/hyprland-plugins/default.nix#L12

I've only noticed it now that hyprland-plugins upstream fails to build even though the dependencies are correct.

**Comment by khaneliman** [comment]
> @khaneliman could you also make a change in `mkHyprlandPlugins`? This line should actually be `hyprland.stdenv.mkDerivation`:
> 
> https://github.com/NixOS/nixpkgs/blob/2d56a4c4cedd050b5a0384080903c25d2806073c/pkgs/applications/window-managers/hyprwm/hyprland-plugins/default.nix#L12
> 
> I've only noticed it now that hyprland-plugins upstream fails to build even though the dependencies are correct.

Makes sense, I was looking at the flake and curious how it was passing around the stdenv.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365776`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>hyprlandPlugins.hycov</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>hyprlandPlugins.hy3</li>
    <li>hyprlandPlugins.hyprfocus</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 23 packages built:</summary>
  <ul>
    <li>grimblast</li>
    <li>hdrop</li>
    <li>hyprland</li>
    <li>hyprland.dev</li>
    <li>hyprland.man</li>
    <li>hyprlandPlugins.borders-plus-plus</li>
    <li>hyprlandPlugins.csgo-vulkan-fix</li>
    <li>hyprlandPlugins.hypr-dynamic-cursors</li>
    <li>hyprlandPlugins.hyprbars</li>
    <li>hyprlandPlugins.hyprexpo</li>
    <li>hyprlandPlugins.hyprgrass</li>
    <li>hyprlandPlugins.hyprscroller</li>
    <li>hyprlandPlugins.hyprspace</li>
    <li>hyprlandPlugins.hyprsplit</li>
    <li>hyprlandPlugins.hyprtrails</li>
    <li>hyprlandPlugins.hyprwinwrap</li>
    <li>hyprshade</li>
    <li>hyprshade.dist</li>
    <li>hyprshot</li>
    <li>nwg-panel</li>
    <li>nwg-panel.dist</li>
    <li>waybar</li>
    <li>xdg-desktop-portal-hyprland</li>
  </ul>
</details>

**Review by fufexan — APPROVED** [review]
LGTM

**Pull request merged**
