### PR TITLE
amdgpu-pro: 16.40 -> 16.50

### PR DESCRIPTION
**Pull request by corngood**
###### Motivation for this change

WIP because this seems to be somewhat unstable on my machine (HAWAII gpu), but it's here in case anyone wants to test it.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by corngood** [comment]
Testing on an R9 290 w/ linux 4.8.13.

I tried steam (32-bit opengl), some games (64-bit opengl), vulkan demos (64-bit), vdpau (64-bit).  That all seemed to work ok.

However after that I ran glxgears, got visual corruption, and after playing with options for a bit eventually locked up the machine (unresponsive except for hw cursor).

I'd appreciate feedback from anyone who can test on other GPUs.

**Comment by grahamc** [comment]
Is glxgears stable on the current version?

**Comment by corngood** [comment]
On my machine, yeah, GL seems to be more stable with 16.40, but vdpau is more stable with 16.50.

Also on 16.40 I couldn't even boot with amdgpu.dal=1 (the default), but it seems to be usable on 16.50.

It would be great if someone could try this on a Polaris GPU or at least something other than CI.  Mine's pretty old, and if this is usable for newer GPUs then it might be worth merging.

**Comment by plchldr** [comment]
Hi, I have a RX 480 and would like to help with this. What exactly do you want tested and how should the config look like besides `services.xserver.videoDrivers` (e.g. kernel version)? I'm not too familiar with what's relevant here.

**Comment by corngood** [comment]
@plchldr Thanks for the help.  Are you comfortable pulling this branch and building from the git repo?  If not, I can walk you through that.

The relevant bits of my config are:
```
  nixpkgs.config.allowUnfree = true;
```
```
  boot.kernelPackages = pkgs.linuxPackages_latest;
```
use latest kernel (4.8.13 currently on my branch).
```
  services.xserver.videoDrivers = [ "amdgpu-pro" ];
```

That should be it.  I have to build my kernel with `DRM_AMDGPU_CIK=y` for CI support, but yours should be fine on a stock kernel.

If you try it on a different kernel version and get errors building the kernel module, just let me know which version it is and I'll take a look.

Once it's running, just test as much of [GL, vdpau, vulkan, OpenCL] as you can.

**Comment by plchldr** [comment]
I'm not sure so that's what I did:
```
git clone https://github.com/corngood/nixpkgs.git
cd nixpkgs/
git checkout amdgpu-pro-update
sudo nixos-rebuild switch -I nixpkgs=./
-> the usual "Permission denied" error ..
sudo rm -rf /var/tmp/*
sudo nixos-rebuild switch -I nixpkgs=./
```
Scores in glmark2 and glxgears improved quite a bit, Dota2 and CS:GO are still working. However Dota2-vulkan doesn't start with the same error as 16.40.
How to test vdpau and OpenCL?

**Comment by corngood** [comment]
That sounds good.  Could you post the output of `glxinfo`, and your kernel version?

You can test vdpau with most media players, for example `mpv --hwdec=vdpau`.  It should print something in stderr about using vdpau and then play the video properly.

You can test vulkan with (in that nixpkgs dir) `nix-build -A vulkan-loader.demos && cd results-demos/bin && ./smoketest` (I hope that's right, I'm not on my pc atm).  You can also run `tri` and `cube` in that directory (optionally with `--validate`).  Note that the `cd` is intentional because these demos require running in the bin dir.

Post whatever logs you have for failures, including the errors from dota2.

You can also run with `VK_LOADER_DEBUG=all` to get a bit more output if failing to load the driver.

As for OpenCL I never really found a canonical test case for it.  Some people have reported using an OpenCL renderer in blender, but that's not exactly light weight.  If you find anything, let me know, but don't worry if you can't test it.

Other than that, it would be nice to confirm that 32-bit opengl works.  You could `nix-build` a 32-bit glxgears, or just run steam.

If opengl works and you don't have major stability problems I think we should merge this.  AMD tend to kill the download links for old drivers without warning.

**Comment by plchldr** [comment]
glxinfo: [http://pastebin.com/vXQBDsAw](http://pastebin.com/vXQBDsAw)
vulkaninfo: [http://pastebin.com/7PfXu5Q9](http://pastebin.com/7PfXu5Q9) (apparently sth. wrong here)
uname -a: `Linux desktop 4.8.7 #1-NixOS SMP Thu Nov 10 15:39:23 UTC 2016 x86_64 GNU/Linux` (`boot.kernelPackages = pkgs.linuxPackages_4_8;`)

For vdpau I did this:
```
$ youtube-dl https://www.youtube.com/watch?v=O2b8Vc5n_L4
$ mpv --hwdec=vdpau NixOS\ als\ Serversystem\ in\ der\ Praxis\ \[Easterhegg\ 2014\]-O2b8Vc5n_L4.mp4
Playing: NixOS als Serversystem in der Praxis [Easterhegg 2014]-O2b8Vc5n_L4.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
Warning: LLVM emitted unknown config register: 0x4
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vdpau).
VO: [opengl] 854x480 vdpau
AV: 00:00:09 / 00:59:39 (0%) A-V:  0.000
[vo/opengl] Mapping hardware decoded surface failed.
AV: 00:00:09 / 00:59:39 (0%) A-V:  0.000
[vo/opengl] Mapping hardware decoded surface failed.
AV: 00:00:10 / 00:59:39 (0%) A-V:  0.000
[vo/opengl] Mapping hardware decoded surface failed.
[...]
```
So it only works for a few seconds.

All 3 vulkan demos looked fine, no errors in log.
I couldn't find any error logs for Dota2, starting it via `steam steam://run/570
` yielded nothing and via bash failed.
Since I've started both Dota2 and CS:GO via Steam, I guess that works.

**Comment by corngood** [comment]
Thanks for the help.  The logs all look good, I just wanted to double check that it was loading the right version.

> it only works for a few seconds

I had this exact problem with 16.40, so possibly not a regression, but weirdly it seemed to work for me on 16.50.

Overall this should be an improvement for people Polaris GPUs, so I've removed the WIP and have no objection to merging this.

**Comment by corngood** [comment]
@vcunat Since you merged the last update, would you mind taking a look?

**Comment by vcunat** [comment]
OK, let me trust you two in this.

**Comment by corngood** [comment]
@plchldr 

I've starting working on 16.60 in case you (or anyone else) want to test it.

#22241 

We can discuss any issues in there.

**Pull request merged**
