### PR TITLE
vcv-rack: Fix broken glfw fork issue

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

The commit we previously used of the glfw fork for Rack disappeared. See https://github.com/NixOS/nixpkgs/issues/71189

It looks like it is easier to patch out that function call, as it isn't needed on Linux. But we still need a newer version of glfw. 

Needs backport to 19.09, as Rack is broken there as well.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by prusnak** [comment]
No, it doesn't work because the `fetchFromGitHub { fetchSubmodules = true; }` tries to fetch the same missing commit.

**Comment by jonringer** [comment]
You could also pre-fetch the other gitmodules

```
[submodule "dep/nanovg"]
	path = dep/nanovg
	url = https://github.com/memononen/nanovg.git
	ignore = untracked
[submodule "dep/nanosvg"]
	path = dep/nanosvg
	url = https://github.com/memononen/nanosvg.git
	ignore = untracked
[submodule "dep/osdialog"]
	path = dep/osdialog
	url = https://github.com/AndrewBelt/osdialog.git
	ignore = untracked
[submodule "dep/oui-blendish"]
	path = dep/oui-blendish
	url = https://github.com/AndrewBelt/oui-blendish.git
	ignore = untracked
[submodule "dep/rtaudio"]
	path = dep/rtaudio
	url = https://github.com/thestk/rtaudio.git
	ignore = untracked
[submodule "dep/glfw"]
	path = dep/glfw
	url = https://github.com/AndrewBelt/glfw.git
	ignore = untracked
```

**Comment by Moredread** [comment]
@jonringer yes, I think that is a good idea, esp. as we only need some of them.

**Comment by Moredread** [comment]
@prusnak thanks, I still had it in my cache.

**Comment by Moredread** [comment]
I've updated the PR. The derivation now pulls the dependencies as via `fetchFromGitHub`, not as submodules.

**Comment by prusnak** [comment]
I confirm that 66eb70321a05c0584bb1b55dcdbe5e3a1f3d24b6 works! :tada: 

I think this is also worth backporting to `19.09` as the package is not possible to install there at the moment.

**Review by Lassulus — APPROVED** [review]
tested with nix-review, started the GUI, logged into my account and clicked around a bit.
Can someone open a backport PR for this?

**Comment by Moredread** [comment]
@Lassulus I created a backport PR with PR #72042

**Pull request merged**
