### PR TITLE
xorg: fix update generation

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
Both e3d3bc66dc496f940b427443b503a67434e115b5 and 1d15641433b97eb1a45a7adec0a0e94600127dfb were done incorrectly.

Also, use python3 in generate-expr-from-tarballs.pl instead of overrides.nix.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
LGTM

**Comment by jonringer** [comment]
getting this failure:
```
builder for '/nix/store/qv6b521sdqv8xpv0mscb0k7vcy59ygds-xf86-video-openchrome-0.6.0.drv' failed with exit code 2; last 10 log lines:
  compilation terminated.
  make[4]: *** [Makefile:424: libchromeXvMC_la-viaLowLevel.lo] Error 1
  make[4]: Leaving directory '/build/xf86-video-openchrome-0.6.0/src/xvmc'
  make[3]: *** [Makefile:503: all-recursive] Error 1
  make[3]: Leaving directory '/build/xf86-video-openchrome-0.6.0/src'
  make[2]: *** [Makefile:368: all] Error 2
  make[2]: Leaving directory '/build/xf86-video-openchrome-0.6.0/src'
  make[1]: *** [Makefile:347: all-recursive] Error 1
  make[1]: Leaving directory '/build/xf86-video-openchrome-0.6.0'
  make: *** [Makefile:278: all] Error 2
builder for '/nix/store/qq727k1dm56y91lqk14lf8p2v9990xa0-xflr5-6.47.drv' failed with exit code 2; last 10 log lines:
        |                ^
  ../xflr5-engine/objects/objects3d/vector3d.h:79:10: note: because 'Vector3d' has user-provided 'void Vector3d::operator=(const Vector3d&)'
     79 |     void operator =(Vector3d const &T)
        |          ^~~~~~~~
  g++ -Wl,-O1 -Wl,-rpath,/nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib -o xflr5 objects/afoil.o objects/afoiltabledlg.o objects/foiltabledelegate.o objects/gridsettingsdlg.o objects/lecircledlg.o objects/splinectrlsdlg.o objects/glrenderwindow.o objects/view3dtestdlg.o objects/globals.o objects/main.o objects/mainframe.o objects/xflr5application.o objects/curve.o objects/graph.o objects/graph_globals.o objects/graphdlg.o objects/spline5.o objects/splinefoil.o objects/aerodatadlg.o objects/ctrltabledelegate.o objects/editpolardefdlg.o objects/lltanalysisdlg.o objects/panelanalysisdlg.o objects/stabpolardlg.o objects/wadvanceddlg.o objects/wpolardlg.o objects/bodygriddlg.o objects/bodyscaledlg.o objects/bodytabledelegate.o objects/bodytransdlg.o objects/editbodydlg.o objects/editobjectdelegate.o objects/editplanedlg.o objects/gl3dbodydlg.o objects/gl3dwingdlg.o objects/inertiadlg.o objects/planedlg.o objects/wingdelegate.o objects/wingscaledlg.o objects/wingseldlg.o objects/importobjectdlg.o objects/manageplanesdlg.o objects/planetabledelegate.o objects/xmlplanereader.o objects/xmlplanewriter.o objects/xmlwpolarreader.o objects/xmlwpolarwriter.o objects/miarex.o objects/objects3d.o objects/gl3dscales.o objects/gllightdlg.o objects/stabviewdlg.o objects/targetcurvedlg.o objects/w3dprefsdlg.o objects/aboutq5.o objects/colorbutton.o objects/editplrdlg.o objects/exponentialslider.o objects/lengthunitdlg.o objects/linebtn.o objects/linecbbox.o objects/linedelegate.o objects/linepickerdlg.o objects/moddlg.o objects/newnamedlg.o objects/objectpropsdlg.o objects/languagewt.o objects/preferencesdlg.o objects/saveoptions.o objects/settings.o objects/units.o objects/polarfilterdlg.o objects/popup.o objects/progressdlg.o objects/renamedlg.o objects/stlexportdialog.o objects/doubleedit.o objects/floateditdelegate.o objects/intedit.o objects/mintextedit.o objects/textclrbtn.o objects/updater.o objects/voidwidget.o objects/waitdlg.o objects/xflscriptexec.o objects/xflscriptreader.o objects/bodyframewt.o objects/bodylinewt.o objects/foildesignwt.o objects/arcball.o objects/gl3dbodyview.o objects/gl3dmiarexview.o objects/gl3dplaneview.o objects/gl3dtestview.o objects/gl3dview.o objects/gl3dwingview.o objects/graphtilewidget.o objects/graphwidget.o objects/inverseviewwidget.o objects/legendwidget.o objects/miarextilewidget.o objects/oppointwidget.o objects/section2dwidget.o objects/wingwidget.o objects/xdirecttilewidget.o objects/batchdlg.o objects/batchthreaddlg.o objects/foilpolardlg.o objects/relistdlg.o objects/xfoiladvanceddlg.o objects/xfoilanalysisdlg.o objects/xfoiltask.o objects/cadddlg.o objects/flapdlg.o objects/foilcoorddlg.o objects/foilgeomdlg.o objects/interpolatefoilsdlg.o objects/ledlg.o objects/nacafoildlg.o objects/tegapdlg.o objects/twodpaneldlg.o objects/managefoilsdlg.o objects/objects2d.o objects/xdirect.o objects/xdirectstyledlg.o objects/xmlpolarreader.o objects/xmlpolarwriter.o objects/foilselectiondlg.o objects/inverseoptionsdlg.o objects/pertdlg.o objects/xinverse.o objects/qrc_scripts.o objects/qrc_images.o objects/qrc_shaders.o objects/qrc_textures.o objects/moc_afoil.o objects/moc_afoiltabledlg.o objects/moc_foiltabledelegate.o objects/moc_gridsettingsdlg.o objects/moc_lecircledlg.o objects/moc_splinectrlsdlg.o objects/moc_glrenderwindow.o objects/moc_view3dtestdlg.o objects/moc_mainframe.o objects/moc_xflr5application.o objects/moc_graphdlg.o objects/moc_aerodatadlg.o objects/moc_ctrltabledelegate.o objects/moc_editpolardefdlg.o objects/moc_lltanalysisdlg.o objects/moc_panelanalysisdlg.o objects/moc_stabpolardlg.o objects/moc_wadvanceddlg.o objects/moc_wpolardlg.o objects/moc_bodygriddlg.o objects/moc_bodyscaledlg.o objects/moc_bodytabledelegate.o objects/moc_bodytransdlg.o objects/moc_editbodydlg.o objects/moc_editplanedlg.o objects/moc_gl3dbodydlg.o objects/moc_gl3dwingdlg.o objects/moc_inertiadlg.o objects/moc_planedlg.o objects/moc_wingdelegate.o objects/moc_wingscaledlg.o objects/moc_wingseldlg.o objects/moc_importobjectdlg.o objects/moc_manageplanesdlg.o objects/moc_planetabledelegate.o objects/moc_miarex.o objects/moc_gl3dscales.o objects/moc_gllightdlg.o objects/moc_stabviewdlg.o objects/moc_targetcurvedlg.o objects/moc_w3drefsdlg.o objects/moc_aboutq5.o objects/moc_editplrdlg.o objects/moc_lengthunitdlg.o objects/moc_linebtn.o objects/moc_linedelegate.o objects/moc_linepickerdlg.o objects/moc_moddlg.o objects/moc_newnamedlg.o objects/moc_objectpropsdlg.o objects/moc_languagewt.o objects/moc_preferencesdlg.o objects/moc_saveoptions.o objects/moc_settings.o objects/moc_units.o objects/moc_polarfilterdlg.o objects/moc_popup.o objects/moc_progressdlg.o objects/moc_renamedlg.o objects/moc_stlexportdialog.o objects/moc_floatrditdelegate.o objects/moc_textclrbtn.o objects/moc_updater.o objects/moc_voidwidget.o objects/moc_waitdlg.o objects/moc_bodyframewt.o objects/moc_bodylinewt.o objects/moc_gl3dtestview.o objects/moc_gl3dview.o objects/moc_graphtilewidget.o objects/moc_graphwidget.o objects/moc_inverseviewwidget.o objects/moc_legendwidget.o objects/moc_miarextilewidget.o objects/moc_oppointwidget.o objects/moc_section2dwidget.o objects/moc_wingwidget.o objects/moc_xdirecttilewidget.o objects/moc_batchdlg.o objects/moc_batchthreaddlg.o objects/moc_foilpolardlg.o objects/moc_relistdlg.o objects/moc_xfoiladvanceddlg.o objects/moc_xfoilanalysisdlg.o objects/moc_cadddlg.o objects/moc_flapdlg.o objects/moc_foilcoorddlg.o objects/moc_foilgeomdlg.o objects/moc_interpolatefoilsdlg.o objects/moc_ledlg.o objects/moc_nacafoildlg.o objects/moc_tegapdlg.o objects/moc_twodpaneldlg.o objects/moc_managefoilsdlg.o objects/moc_xdirect.o objects/moc_xdirectstyleDlg.o objects/moc_foilselectiondlg.o objects/moc_inverseoptionsdlg.o objects/moc_pertdlg.o objects/moc_xinverse.o   -L/nix/store/glkkam5pww4p86x4ksgqfibaazpypmpx-libGL-1.3.2/lib -L../xflr5-engine -lxflr5-engine -L../XFoil-lib -lXFoil /nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib/libQt5OpenGL.so /nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib/libQt5Widgets.so /nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib/libQt5Gui.so /nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib/libQt5Network.so /nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib/libQt5Xml.so /nix/store/sbnzhrb8gkf29si255cmfm8knc6fga6k-qtbase-5.15.0/lib/libQt5Core.so -L/nix/store/7dhs1zj6ll760r8nqf7kxni8p69lwnyp-libglvnd-1.3.2/lib -lGL -lpthread
  /nix/store/cwx9j6ylwfibwdr3zn0y42ckyqfzfsrn-binutils-2.31.1/bin/ld: cannot find -lXFoil
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:896: xflr5] Error 1
  make[1]: Leaving directory '/build/xflr5/xflr5-gui'
  make: *** [Makefile:99: sub-xflr5-gui-make_first] Error 2
```
not sure what was failing to build on staging. But there was ~100 or so build failures (but I've also had issues with my high core count causing some builds to fail)

**Comment by jonringer** [comment]
@GrahamcOfBorg build colord

**Comment by jonringer** [comment]
actually, i was able to build it the second time. not sure anymore

**Review by jonringer — APPROVED** [review]
LGTM

going to validate whether xf86 is broken on current staging, if it is, I'll merge:
```
$ nixpkgs-review pr 103710 --eval local --package-regex 'x.*'
...
https://github.com/NixOS/nixpkgs/pull/103710
14 packages marked as broken and skipped:
xfce.xfce4-vala-panel-appmenu-plugin xmonad_log_applet xmonad_log_applet_gnome3 xorg.xf86videoark xorg.xf86videogeode xorg.xf86videoglide xorg.xf86videoi128 xorg.xf86videonewport xorg.xf86videos3virge xorg.xf86videosavage xorg.xf86videotga xorg.xf86videov4l xorg.xf86videovoodoo xorg.xf86videowsfb

1 package failed to build:
xorg.xf86videoopenchrome

150 packages built:
x11basic x11docker x2goclient x2goserver xarchiver xautoclick xca xcowsay xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-kde xdg-desktop-portal-wlr xdgmenumaker xdot xdotool xdragon xdummy xf86_input_cmt xf86_input_wacom xf86_video_nested xf86_video_nouveau xfce.catfish xfce.exo xfce.garcon xfce.gigolo xfce.gvfs xfce.libxfce4ui xfce.libxfce4util xfce.mousepad xfce.orage xfce.parole xfce.ristretto xfce.terminal xfce.thunar xfce.thunar-archive-plugin xfce.thunar-dropbox-plugin xfce.thunar-volman xfce.tumbler xfce.xfburn xfce.xfce4-appfinder xfce.xfce4-battery-plugin xfce.xfce4-clipman-plugin xfce.xfce4-cpufreq-plugin xfce.xfce4-cpugraph-plugin xfce.xfce4-datetime-plugin xfce.xfce4-dev-tools xfce.xfce4-dict xfce.xfce4-dockbarx-plugin xfce.xfce4-embed-plugin xfce.xfce4-eyes-plugin xfce.xfce4-fsguard-plugin xfce.xfce4-genmon-plugin xfce.xfce4-hardware-monitor-plugin xfce.xfce4-icon-theme xfce.xfce4-mailwatch-plugin xfce.xfce4-mpc-plugin xfce.xfce4-namebar-plugin xfce.xfce4-netload-plugin xfce.xfce4-notes-plugin xfce.xfce4-notifyd xfce.xfce4-panel xfce.xfce4-power-manager xfce.xfce4-pulseaudio-plugin xfce.xfce4-screenshooter xfce.xfce4-sensors-plugin xfce.xfce4-session xfce.xfce4-settings xfce.xfce4-systemload-plugin xfce.xfce4-taskmanager xfce.xfce4-timer-plugin xfce.xfce4-verve-plugin xfce.xfce4-volumed-pulse xfce.xfce4-weather-plugin xfce.xfce4-whiskermenu-plugin xfce.xfce4-windowck-plugin xfce.xfce4-xkb-plugin xfce.xfconf xfce.xfdashboard xfce.xfdesktop xfce.xfwm4 xflr5 xflux-gui xiccd xineLib xineUI xiphos xkbvalidate xkeyboard_config xmind xmloscopy xmonad_log_applet_mate xmonad_log_applet_xfce xneur xonotic xonotic-sdl-unwrapped xorg.setxkbmap xorg.xf86inputevdev xorg.xf86inputjoystick xorg.xf86inputkeyboard xorg.xf86inputlibinput xorg.xf86inputmouse xorg.xf86inputsynaptics xorg.xf86inputvmmouse xorg.xf86inputvoid xorg.xf86videoamdgpu xorg.xf86videoapm xorg.xf86videoast xorg.xf86videoati xorg.xf86videochips xorg.xf86videocirrus xorg.xf86videodummy xorg.xf86videofbdev xorg.xf86videoglint xorg.xf86videoi740 xorg.xf86videointel xorg.xf86videomach64 xorg.xf86videomga xorg.xf86videoneomagic xorg.xf86videonv xorg.xf86videoomap xorg.xf86videoqxl xorg.xf86videor128 xorg.xf86videorendition xorg.xf86videosiliconmotion xorg.xf86videosis xorg.xf86videosisusb xorg.xf86videosuncg6 xorg.xf86videosunffb xorg.xf86videosunleo xorg.xf86videotdfx xorg.xf86videotrident xorg.xf86videovboxvideo xorg.xf86videovesa xorg.xf86videovmware xorg.xf86videoxgi xorg.xinit xorg.xkbcomp xorg.xorgserver xournalpp xp-pen-g430 xpad xpra xprite-editor xrdp xscast xsuspender xvfb_run xwayland xxdiff xygrib
```

**Comment by jonringer** [comment]
other build fails on stagning as well

```
/nix/store/34fl1m68z7f2iqk0zby211i80daf4xb3-libXvMC-1.0.12-dev/include/X11/extensions/XvMClib.h:5:10: fatal error: X11/extensions/Xvlib.h: No such file or directory
    5 | #include <X11/extensions/Xvlib.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:466: libchromeXvMCPro_la-viaXvMC.lo] Error 1
make[4]: *** [Makefile:452: libchromeXvMCPro_la-viaLowLevelPro.lo] Error 1
make[4]: *** [Makefile:438: libchromeXvMC_la-viaXvMC.lo] Error 1
make[4]: Leaving directory '/build/xf86-video-openchrome-0.6.0/src/xvmc'
make[3]: *** [Makefile:503: all-recursive] Error 1
make[3]: Leaving directory '/build/xf86-video-openchrome-0.6.0/src'
make[2]: *** [Makefile:368: all] Error 2
make[2]: Leaving directory '/build/xf86-video-openchrome-0.6.0/src'
make[1]: *** [Makefile:347: all-recursive] Error 1
make[1]: Leaving directory '/build/xf86-video-openchrome-0.6.0'
make: *** [Makefile:278: all] Error 2
builder for '/nix/store/0d8n7qgnc89m7b2i9fhza4772x0c9vak-xf86-video-openchrome-0.6.0.drv' failed with exit code 2
error: build of '/nix/store/0d8n7qgnc89m7b2i9fhza4772x0c9vak-xf86-video-openchrome-0.6.0.drv' failed
```

**Pull request merged**
