### PR TITLE
demjson,j2cli: add top level entry

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117035` at dfacfcd4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/4f312021c03ea69e64bb54dcf4e18a5a">demjson</a></li></li>
    <li><a href="https://gist.github.com/3ff75e34bd5c9df2dad6fa2b450746c9">j2cli</a></li></li>
  </ul>
</details>

**Comment by rmcgibbo** [comment]
With `demjson`, https://pypi.org/project/demjson/#history shows the last release was 6 years ago and the homepage link returns a 404. Is this needed?
j2 seems reasonable. no issue there.

**Comment by SuperSandro2000** [comment]
> With `demjson`, [pypi.org/project/demjson/#history](https://pypi.org/project/demjson/#history) shows the last release was 6 years ago and the homepage link returns a 404. Is this needed?

I could use hsjon for https://github.com/stedolan/jq/wiki/FAQ#relaxed-json but I think we should add an entry anyway if there is a binary.

Oh yeah, they should be python3.

**Comment by rmcgibbo** [comment]
> but I think we should add an entry anyway if there is a binary.

do you want to add a top-level entry for _every_ python package that includes binaries? there are probably a... lot.

**Comment by SuperSandro2000** [comment]
> do you want to add a top-level entry for _every_ python package that includes binaries? there are probably a... lot.

Binaries that someone wants to use, yeah but not now.

**Pull request merged**
