### PR TITLE
[20.03] linux: really remove 5.5

### PR DESCRIPTION
**Pull request by cole-h**
5.5 was removed in https://github.com/NixOS/nixpkgs/commit/aa7c5b02ff2874833ae4a0cad7691ab994d19303,
but this attribute was missed, leading to an evaluation failure for the
nixos-20.03-small channel.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @NeQuissimus: Hope I've done this right. ~~I don't think this would need to be forward-ported, but let me know.~~

https://nix-cache.s3.amazonaws.com/log/i9vglf7w5z13w0d6cya5w623xmvzgdr3-nixos-channel-20.03.1502.d72fcc568d2.drv

### CODE REVIEW

**Comment by samueldr** [comment]
Correct, @cole-h, this is something that isn't dont the same way for stable vs. unstable releases.

**Comment by samueldr** [comment]
I verified locally with the ofborg evaluator, the failure is the release branch failing to eval.

I ran the following on the tip of both branches:

```
.../ofborg/ofborg/src/outpaths.nix
```

And this indeed fixes it.

**Comment by NeQuissimus** [comment]
Oops, my bad!

**Comment by samueldr** [comment]
@NeQuissimus can I propose you add running the (quick) ofborg evaluator as part of your release process?

I'm assuming it's somewhat automated.

This nix expression:

 * https://github.com/NixOS/ofborg/blob/released/ofborg/src/outpaths.nix

Can be run like a script (wild!)

Assuming you end up running some tests at the end of your changes, you could run `.../ofborg/src/outpaths.nix` at the end. It would have failed in this instance.

No one would end up knowing if you don't or can't, though now you know it's a possibility :slightly_smiling_face: .

**Comment by NeQuissimus** [comment]
Roger that :D I really do need to automate these things...

**Comment by samueldr** [comment]
Looks like it's around 6.3GiB "total-vm", I'm never confident with those numbers and how they map to actual RAM use.

Let's run it locally:

```
TIME=\n → exit status: %x\n → user: %U, system: %S, elapsed: %E\n → cpu: %P, max mem: %M, avg mem: %t, unshared: %D\n → I/O: <I:%I O:%O>, sock: <r:%r s:%s>

.../nixpkgs/nixos-20.03 $ time ~/tmp/ofborg/ofborg/src/outpaths.nix --show-trace
...
 → exit status: 0
 → user: 226.35, system: 6.38, elapsed: 8:01.42
 → cpu: 48%, max mem: 21833600, avg mem: 0, unshared: 0
 → I/O: <I:0 O:8>, sock: <r:0 s:0>
```

Ignore the time elapsed, as it was waiting on input in a `less`.

```
  %M   maximum resident set size in KB
```

```
irb(main):002:0> 21833600.0 / 1024 / 1024
=> 20.8221435546875
```

That explains it.

**Pull request merged**
