### PR TITLE
libadwaita: 1.2.2 -> 1.2.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://gitlab.gnome.org/GNOME/libadwaita/-/compare/1.2.2...1.2.3

Changelog: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/1.2.3/NEWS

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]
Changelog looks fine.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 219532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-todo</li>
    <li>pantheon.file-roller</li>
  </ul>
</details>
<details>
  <summary>54 packages failed to build:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>fractal-next</li>
    <li>gnome-browser-connector</li>
    <li>gnome-builder</li>
    <li>gnome-solanum</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter42 (pantheon.mutter)</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>mojave-gtk-theme</li>
    <li>monitor</li>
    <li>newsflash</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pods</li>
    <li>spot</li>
    <li>vala-language-server</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
    <li>wingpanel-indicator-ayatana</li>
  </ul>
</details>
<details>
  <summary>103 packages built:</summary>
  <ul>
    <li>amberol</li>
    <li>ashpd-demo</li>
    <li>authenticator</li>
    <li>bada-bib</li>
    <li>banking</li>
    <li>baobab (gnome.baobab)</li>
    <li>blackbox-terminal</li>
    <li>blanket</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>cambalache</li>
    <li>cavalier</li>
    <li>celluloid</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>citations</li>
    <li>clapper</li>
    <li>contrast</li>
    <li>d-spy</li>
    <li>deja-dup</li>
    <li>denaro</li>
    <li>dialect</li>
    <li>dino</li>
    <li>dippi</li>
    <li>dropbox-cli</li>
    <li>dynamic-wallpaper</li>
    <li>eartag</li>
    <li>easyeffects</li>
    <li>eiciel</li>
    <li>emblem</li>
    <li>emulsion-palette</li>
    <li>endeavour</li>
    <li>eyedropper</li>
    <li>flare-signal</li>
    <li>fragments</li>
    <li>furtherance</li>
    <li>giara</li>
    <li>gnome-console</li>
    <li>gnome-decoder</li>
    <li>gnome-extension-manager</li>
    <li>gnome-firmware</li>
    <li>gnome-frog</li>
    <li>gnome-obfuscate</li>
    <li>gnome-secrets</li>
    <li>gnome-text-editor</li>
    <li>gnome-tour</li>
    <li>gnome.file-roller</li>
    <li>gnome.ghex</li>
    <li>gnome.gnome-bluetooth</li>
    <li>gnome.gnome-calculator</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-characters</li>
    <li>gnome.gnome-chess</li>
    <li>gnome.gnome-clocks</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-font-viewer</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-logs</li>
    <li>gnome.gnome-maps</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-software</li>
    <li>gnome.gnome-sound-recorder</li>
    <li>gnome.gnome-weather</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.polari</li>
    <li>headlines</li>
    <li>icon-library</li>
    <li>iotas</li>
    <li>junction</li>
    <li>karlender</li>
    <li>khronos</li>
    <li>kooha</li>
    <li>libadwaita</li>
    <li>libpanel</li>
    <li>lxi-tools-gui</li>
    <li>malcontent-ui</li>
    <li>metadata-cleaner</li>
    <li>mousai</li>
    <li>nautilus-open-any-terminal</li>
    <li>netease-cloud-music-gtk</li>
    <li>notejot</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.file-roller-contract</li>
    <li>paper-note</li>
    <li>pika-backup</li>
    <li>raider</li>
    <li>rnote</li>
    <li>shortwave</li>
    <li>symbolic-preview</li>
    <li>sysprof</li>
    <li>tagger</li>
    <li>tangram</li>
    <li>text-engine</li>
    <li>textpieces</li>
    <li>video-trimmer</li>
    <li>warp</li>
    <li>watchmate</li>
    <li>whatip</li>
    <li>wordbook</li>
    <li>xdg-desktop-portal-gnome</li>
    <li>zrythm</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
> 54 packages failed to build:

Weird, the diff and the [libversion](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/be4601489607da1e231f6d594a816dfd0a9da120/meson.build#L32) tells me this update shouldn't break things, any logs?

@ofborg test gnome

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 219532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-todo</li>
    <li>pantheon.file-roller</li>
  </ul>
</details>
<details>
  <summary>31 packages failed to build:</summary>
  <ul>
    <li>dropbox-cli</li>
    <li>giara</li>
    <li>gnome.mutter42 (pantheon.mutter)</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>monitor</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>rnote</li>
    <li>wingpanel-indicator-ayatana</li>
  </ul>
</details>
<details>
  <summary>126 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>amberol</li>
    <li>ashpd-demo</li>
    <li>authenticator</li>
    <li>bada-bib</li>
    <li>banking</li>
    <li>baobab (gnome.baobab)</li>
    <li>blackbox-terminal</li>
    <li>blanket</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>cambalache</li>
    <li>cavalier</li>
    <li>celluloid</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>citations</li>
    <li>clapper</li>
    <li>contrast</li>
    <li>d-spy</li>
    <li>deja-dup</li>
    <li>denaro</li>
    <li>dialect</li>
    <li>dino</li>
    <li>dippi</li>
    <li>dynamic-wallpaper</li>
    <li>eartag</li>
    <li>easyeffects</li>
    <li>eiciel</li>
    <li>emblem</li>
    <li>emulsion-palette</li>
    <li>endeavour</li>
    <li>eyedropper</li>
    <li>flare-signal</li>
    <li>fractal-next</li>
    <li>fragments</li>
    <li>furtherance</li>
    <li>gnome-browser-connector</li>
    <li>gnome-builder</li>
    <li>gnome-console</li>
    <li>gnome-decoder</li>
    <li>gnome-extension-manager</li>
    <li>gnome-firmware</li>
    <li>gnome-frog</li>
    <li>gnome-obfuscate</li>
    <li>gnome-secrets</li>
    <li>gnome-solanum</li>
    <li>gnome-text-editor</li>
    <li>gnome-tour</li>
    <li>gnome.file-roller</li>
    <li>gnome.ghex</li>
    <li>gnome.gnome-bluetooth</li>
    <li>gnome.gnome-calculator</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-characters</li>
    <li>gnome.gnome-chess</li>
    <li>gnome.gnome-clocks</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-font-viewer</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-logs</li>
    <li>gnome.gnome-maps</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-software</li>
    <li>gnome.gnome-sound-recorder</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gnome-weather</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnome.polari</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>headlines</li>
    <li>icon-library</li>
    <li>iotas</li>
    <li>junction</li>
    <li>karlender</li>
    <li>khronos</li>
    <li>kooha</li>
    <li>libadwaita</li>
    <li>libpanel</li>
    <li>lxi-tools-gui</li>
    <li>malcontent-ui</li>
    <li>metadata-cleaner</li>
    <li>mojave-gtk-theme</li>
    <li>mousai</li>
    <li>nautilus-open-any-terminal</li>
    <li>netease-cloud-music-gtk</li>
    <li>newsflash</li>
    <li>notejot</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.file-roller-contract</li>
    <li>paper-note</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pika-backup</li>
    <li>pods</li>
    <li>raider</li>
    <li>shortwave</li>
    <li>spot</li>
    <li>symbolic-preview</li>
    <li>sysprof</li>
    <li>tagger</li>
    <li>tangram</li>
    <li>text-engine</li>
    <li>textpieces</li>
    <li>vala-language-server</li>
    <li>video-trimmer</li>
    <li>vimix-gtk-themes</li>
    <li>warp</li>
    <li>watchmate</li>
    <li>whatip</li>
    <li>whitesur-gtk-theme</li>
    <li>wordbook</li>
    <li>xdg-desktop-portal-gnome</li>
    <li>zrythm</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 219532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-todo</li>
    <li>pantheon.file-roller</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gnomeExtensions.easyScreenCast</li>
  </ul>
</details>
<details>
  <summary>156 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>amberol</li>
    <li>ashpd-demo</li>
    <li>authenticator</li>
    <li>bada-bib</li>
    <li>banking</li>
    <li>baobab (gnome.baobab)</li>
    <li>blackbox-terminal</li>
    <li>blanket</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>cambalache</li>
    <li>cavalier</li>
    <li>celluloid</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>citations</li>
    <li>clapper</li>
    <li>contrast</li>
    <li>d-spy</li>
    <li>deja-dup</li>
    <li>denaro</li>
    <li>dialect</li>
    <li>dino</li>
    <li>dippi</li>
    <li>dropbox-cli</li>
    <li>dynamic-wallpaper</li>
    <li>eartag</li>
    <li>easyeffects</li>
    <li>eiciel</li>
    <li>emblem</li>
    <li>emulsion-palette</li>
    <li>endeavour</li>
    <li>eyedropper</li>
    <li>flare-signal</li>
    <li>fractal-next</li>
    <li>fragments</li>
    <li>furtherance</li>
    <li>giara</li>
    <li>gnome-browser-connector</li>
    <li>gnome-builder</li>
    <li>gnome-console</li>
    <li>gnome-decoder</li>
    <li>gnome-extension-manager</li>
    <li>gnome-firmware</li>
    <li>gnome-frog</li>
    <li>gnome-obfuscate</li>
    <li>gnome-secrets</li>
    <li>gnome-solanum</li>
    <li>gnome-text-editor</li>
    <li>gnome-tour</li>
    <li>gnome.file-roller</li>
    <li>gnome.ghex</li>
    <li>gnome.gnome-bluetooth</li>
    <li>gnome.gnome-calculator</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-characters</li>
    <li>gnome.gnome-chess</li>
    <li>gnome.gnome-clocks</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-font-viewer</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-logs</li>
    <li>gnome.gnome-maps</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-software</li>
    <li>gnome.gnome-sound-recorder</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gnome-weather</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter42 (pantheon.mutter)</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnome.polari</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>headlines</li>
    <li>icon-library</li>
    <li>iotas</li>
    <li>junction</li>
    <li>karlender</li>
    <li>khronos</li>
    <li>kooha</li>
    <li>libadwaita</li>
    <li>libpanel</li>
    <li>lxi-tools-gui</li>
    <li>malcontent-ui</li>
    <li>metadata-cleaner</li>
    <li>mojave-gtk-theme</li>
    <li>monitor</li>
    <li>mousai</li>
    <li>nautilus-open-any-terminal</li>
    <li>netease-cloud-music-gtk</li>
    <li>newsflash</li>
    <li>notejot</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.file-roller-contract</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>paper-note</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pika-backup</li>
    <li>pods</li>
    <li>raider</li>
    <li>rnote</li>
    <li>shortwave</li>
    <li>spot</li>
    <li>symbolic-preview</li>
    <li>sysprof</li>
    <li>tagger</li>
    <li>tangram</li>
    <li>text-engine</li>
    <li>textpieces</li>
    <li>vala-language-server</li>
    <li>video-trimmer</li>
    <li>vimix-gtk-themes</li>
    <li>warp</li>
    <li>watchmate</li>
    <li>whatip</li>
    <li>whitesur-gtk-theme</li>
    <li>wingpanel-indicator-ayatana</li>
    <li>wordbook</li>
    <li>xdg-desktop-portal-gnome</li>
    <li>zrythm</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Must have been some problem with my remote builder.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 219532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome.gnome-todo</li>
    <li>pantheon.file-roller</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gnomeExtensions.easyScreenCast</li>
  </ul>
</details>
<details>
  <summary>156 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>amberol</li>
    <li>ashpd-demo</li>
    <li>authenticator</li>
    <li>bada-bib</li>
    <li>banking</li>
    <li>baobab (gnome.baobab)</li>
    <li>blackbox-terminal</li>
    <li>blanket</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>cambalache</li>
    <li>cavalier</li>
    <li>celluloid</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>citations</li>
    <li>clapper</li>
    <li>contrast</li>
    <li>d-spy</li>
    <li>deja-dup</li>
    <li>denaro</li>
    <li>dialect</li>
    <li>dino</li>
    <li>dippi</li>
    <li>dropbox-cli</li>
    <li>dynamic-wallpaper</li>
    <li>eartag</li>
    <li>easyeffects</li>
    <li>eiciel</li>
    <li>emblem</li>
    <li>emulsion-palette</li>
    <li>endeavour</li>
    <li>eyedropper</li>
    <li>flare-signal</li>
    <li>fractal-next</li>
    <li>fragments</li>
    <li>furtherance</li>
    <li>giara</li>
    <li>gnome-browser-connector</li>
    <li>gnome-builder</li>
    <li>gnome-console</li>
    <li>gnome-decoder</li>
    <li>gnome-extension-manager</li>
    <li>gnome-firmware</li>
    <li>gnome-frog</li>
    <li>gnome-obfuscate</li>
    <li>gnome-secrets</li>
    <li>gnome-solanum</li>
    <li>gnome-text-editor</li>
    <li>gnome-tour</li>
    <li>gnome.file-roller</li>
    <li>gnome.ghex</li>
    <li>gnome.gnome-bluetooth</li>
    <li>gnome.gnome-calculator</li>
    <li>gnome.gnome-calendar</li>
    <li>gnome.gnome-characters</li>
    <li>gnome.gnome-chess</li>
    <li>gnome.gnome-clocks</li>
    <li>gnome.gnome-contacts</li>
    <li>gnome.gnome-control-center</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-font-viewer</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-logs</li>
    <li>gnome.gnome-maps</li>
    <li>gnome.gnome-music</li>
    <li>gnome.gnome-session</li>
    <li>gnome.gnome-shell</li>
    <li>gnome.gnome-software</li>
    <li>gnome.gnome-sound-recorder</li>
    <li>gnome.gnome-terminal</li>
    <li>gnome.gnome-tweaks</li>
    <li>gnome.gnome-weather</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter42 (pantheon.mutter)</li>
    <li>gnome.nautilus</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nixos-gsettings-overrides</li>
    <li>gnome.polari</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>headlines</li>
    <li>icon-library</li>
    <li>iotas</li>
    <li>junction</li>
    <li>karlender</li>
    <li>khronos</li>
    <li>kooha</li>
    <li>libadwaita</li>
    <li>libpanel</li>
    <li>lxi-tools-gui</li>
    <li>malcontent-ui</li>
    <li>metadata-cleaner</li>
    <li>mojave-gtk-theme</li>
    <li>monitor</li>
    <li>mousai</li>
    <li>nautilus-open-any-terminal</li>
    <li>netease-cloud-music-gtk</li>
    <li>newsflash</li>
    <li>notejot</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.file-roller-contract</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>paper-note</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>pika-backup</li>
    <li>pods</li>
    <li>raider</li>
    <li>rnote</li>
    <li>shortwave</li>
    <li>spot</li>
    <li>symbolic-preview</li>
    <li>sysprof</li>
    <li>tagger</li>
    <li>tangram</li>
    <li>text-engine</li>
    <li>textpieces</li>
    <li>vala-language-server</li>
    <li>video-trimmer</li>
    <li>vimix-gtk-themes</li>
    <li>warp</li>
    <li>watchmate</li>
    <li>whatip</li>
    <li>whitesur-gtk-theme</li>
    <li>wingpanel-indicator-ayatana</li>
    <li>wordbook</li>
    <li>xdg-desktop-portal-gnome</li>
    <li>zrythm</li>
  </ul>
</details>

**Pull request merged**
