### PR TITLE
mangohud: 0.4.1 → 0.6.1

### PR DESCRIPTION
**Pull request by kira-bruneau**
###### Motivation for this change
Update to the latest version: https://github.com/flightlessmango/MangoHud/releases/tag/v0.6.1. This update fixes MangoHud detection in GOverlay (See https://github.com/NixOS/nixpkgs/pull/121422).

Additional fixes in this commit:
- Add patch from upstream pull request to support specifying `vulkan_datadir` (removes the need to symlink `vulkan-headers` into MangoHud's `$out` directory. See https://github.com/flightlessmango/MangoHud/pull/522).
- Add patch to hard code runtime dependencies
- Add nix-specific workarounds to support 32bit OpenGL & Vulkan applications (See https://github.com/NixOS/nixpkgs/issues/101597)
- Add wrapper to support overlaying Vulkan applications when MangoHud isn't installed

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
  - 64bit OpenGL: `nix-shell -p mesa-demos --run 'mangohud glxgears'`
  - 32bit OpenGL: `nix-shell -p pkgsi686Linux.mesa-demos --run 'mangohud glxgears'`
  - 64bit Vulkan: `nix-shell -p vulkan-tools --run 'mangohud vkcube'`
  - 32bit Vulkan: `nix-shell -p pkgsi686Linux.vulkan-tools --run 'mangohud vkcube'` (relies on new layer loading behaviour: https://github.com/NixOS/nixpkgs/pull/122061)
  **NOTE:** I could only test this on an AMD GPU. It looks like GPU information is obtained for Nvidia GPUs by dynamically loading `libXNVCtrl.so.0`/`libnvidia-ml.so.1` from the system installed Nvidia drivers. I didn't hard code these dependencies because they rely on the specific build of Nvidia drivers that's installed.
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@ZerataX This update includes some new patches which will make maintenance more difficult. I would be happy to also add myself as a maintainer if you want the help.

### CODE REVIEW

**Comment by MetaDark** [comment]
Result of `nixpkgs-review pr 122465` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mangohud</li>
  </ul>
</details>

**Comment by MetaDark** [comment]
Sorry for all the force-pushes. I was trying to reduce the amount of patching required to hardcode the dependencies, and my original approach with `/usr/bin/env` had some problems.

It should be much easier to maintain `hardcode-dependencies.patch` now that I'm hardcoding the binaries through `PATH`.

**Comment by ZerataX** [comment]
oh looks good and yeah I would definitely appreciate if you could add yourself as a maintainer

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 122465` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mangohud</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks sane

Builds, works

tested glxgears: 

```
[nix-shell:~/.cache/nixpkgs-review/pr-122465]$ mangohud glxgears
skipping config: /nix/store/5bx1vwh2v9dxbz5dss3mllrx6q5b7l0n-mesa-demos-8.4.0/bin/MangoHud.conf [ not found ]
skipping config: /home/davidak/.config/MangoHud/glxgears.conf [ not found ]
parsing config: /home/davidak/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Uploading is disabled (permit_upload = 0)
Version: 4.6 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
301 frames in 5.0 seconds = 60.167 FPS
300 frames in 5.0 seconds = 59.912 FPS
...
```

installing it and testing with steam

```
[nix-shell:~/.cache/nixpkgs-review/pr-122465]$ nix-env -f nixpkgs/ -iA mangohud
replacing old 'mangohud-0.4.1'
installing 'mangohud-0.6.1'
building '/nix/store/wzlswsvzpc0a0wfwzm45lvrzvp9n975w-user-environment.drv'...
created 618 symlinks in user environment
```

works with Half-Life 1 (32-bit)
works with CS:Go
works with GemCraft - Chasing Shadows (Proton, global config `MANGOHUD=1`)

**Pull request merged**
