### PR TITLE
Carnix: 0.7.2 -> 0.8.10

### PR DESCRIPTION
**Pull request by P-E-Meunier**
###### Motivation for this change

This new version of Carnix splits its input into two parts:
- crates from crates.io, meant to be included in nixpkgs.
- local crates and a tiny translation of the lockfile (which might get even smaller in the future).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
This change looks pretty good to me. The split makes sense.

First of all how do we plan to maintain our `crates-io.nix` package set?
Have you tested how large the full set would be?

Here a notes regarding the `carnix` command:

- the `carnix nix` subcommand could become a verb like `generate-nix` or `update-nix` or just `generate` so it is more clear what it does
- `carnix build` currently returns:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: None })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

if `cargo` is missing. Not adding cargo to $PATH is fine since it allows to switch between rust from nixpkgs and the rust overlay. However the error message could be more clear what is actually missing.

Is it possible to include help messages on subcommand level?

```console
$ carnix --help
carnix 0.8.5
pmeunier <pe@pijul.org>
Generate a nix derivation set from a cargo registry
USAGE:
    carnix [SUBCOMMAND]
FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
SUBCOMMANDS:
    build       Build project in current directory
    help        Prints this message or the help of the given subcommand(s)
    generate Generate nix expression
    run          
```

`carnix run` is currently doing the same as `carnix build`?

**Comment by gebner** [comment]
`cargo-vendor` and anything that depends on it is currently broken on master because of the [curl-sys build failure](https://hydra.nixos.org/build/74400163/nixlog/1).  I think we should merge this PR now since it fixes the build failure, and add documentation and polishing later.  @P-E-Meunier there is now a merge conflict.

**Comment by Mic92** [comment]
I cherry-picked the build fix into this pull request: https://github.com/NixOS/nixpkgs/pull/40808/files

**Comment by P-E-Meunier** [comment]
> First of all how do we plan to maintain our crates-io.nix package set?

I don't think I'm the one who should decide. A reasonable middle ground could be to maintain it manually, with the caveat that the format might change again in the future (the features code is not yet minimal).

Another option could be to add a command to carnix, that generates the file from a list of packages and versions, with the goal of not importing tons of useless packages into nixpkgs.

Yet another way could be to generate the whole thing from crates.io and put it online somewhere. I don't have the resources (mostly in terms of time) to setup a server now that would keep importing from crates.io (or even better, from the list of packages on GitHub), but I can provide guidance to someone who would want to do that.

> Have you tested how large the full set would be?

No, but I expect it to be quite large. Many parts of the output are still quite verbose.

Another issue is, I'd like to write tests to check that we don't break any package when we change `buildRustCrate`, but I'm not sure how to write tests for nixpkgs.

**Comment by Mic92** [comment]
How did you generate the current list? If we could feed in a list of packages, we have in nixpkgs, we should have the most interesting ones in the list.

**Comment by xeji** [comment]
Looks like there was a temporary merge conflict.
@GrahamcOfBorg eval

**Comment by P-E-Meunier** [comment]
@Mic92: the current list is generated by Carnix, just as before, except that the output is split into two files now.

**Comment by Mic92** [comment]
@P-E-Meunier How would one create a common crates-io.nix file for all `buildRustCrate` packages?

**Comment by P-E-Meunier** [comment]
@Mic92 there are lots of crates with lots of versions on crates.io. Importing them all would yield a fast-changing big file in nixpkgs.

What we could do is to only include the ones that are useful for binaries currently packaged in nixpkgs, which would require (1) some manual work to merge new deps into the file, and (2) automated checks on the nixpkgs repository.

Maybe these two tasks could be included in Carnix, at least (1) seems easy.

**Comment by Mic92** [comment]
I agree we should not have all crate versions in nixpkgs and I also thought about having a list of packages that is used to generate all packages.
Carnix would then need to create one "lockfile" per package the one can import the package from and a big crates-io.nix file that is shared across all packages.
All rust packages that are built that way would then be located into the same directory.

**Comment by gavinrogers** [comment]
@P-E-Meunier is this what became of the following?
https://www.reddit.com/r/rust/comments/649h6m/using_nix_nixos_as_a_build_system_for_rust_and/
The link seems to 404, unless I don't know how to use nest properly.

**Comment by P-E-Meunier** [comment]
There isn't much to "know" about the Nest, but it's now at https://nest.pijul.com/pmeunier/carnix

**Comment by mstone** [comment]
Folks,

Is there any work that remains to be done on this PR before it can be merged? (Or are we still stuck trying to figure out how to handle the crates.io-part of the output)?

Thank you!

Michael

**Comment by jasoncarr0** [comment]
This and https://github.com/NixOS/nixpkgs/pull/39317 have been sitting around for quite a while.
Would it be possible to merge this if we fixed the conflicts? 

There are major bug fixes in both, that are necessary for building other packages (e.g. xi-editor requires the fix for local crates).

**Comment by P-E-Meunier** [comment]
I have a non-conflicting version. Also, Carnix changed a little bit since this pull request, a better option could be that we close this and open a different PR.

**Comment by P-E-Meunier** [comment]
Ok, this PR includes #47976, and is mergeable now.

**Comment by asymmetric** [comment]
Should the title of the PR be updated to mention 0.8.9?

**Comment by sjmackenzie** [comment]
Greets, would be lovely if we could merge this and then figure out other cool nerd-out topics like crate-io.nix. I'm getting some very annoying `cargo-vendor` errors I'd love to solve by running 0.8.9.

**Comment by sjmackenzie** [comment]
Seems `carnix 0.8.9` still blows ups on certain repositories: https://nest.pijul.com/pmeunier/carnix/discussions/14

```
$ carnix -V
carnix 0.8.9

$ carnix generate-nix
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jasoncarr0** [comment]
@sjmackenzie 

I've noticed that there are some repositories it doesn't quite work on yet as well, but since this is a large change, assuming enough issues are worked out, I think it's better to merge it so that bugfixes and features can be accounted for later. We don't want perfection to be the enemy of progress.

**Comment by dywedir** [comment]
@GrahamcOfBorg build carnix cargo-vendor

**Comment by P-E-Meunier** [comment]
I just fixed @sjmackenzie's issue, his example compiles with Carnix 0.8.10. Feel free to report other bugs.

**Comment by jasoncarr0** [comment]
Well, if you're planning on fixing them now then https://github.com/xi-editor/xi-editor was one that previously gave me trouble (since some crates are only local, and not uploaded).

**Comment by sjmackenzie** [comment]
Pierre, thank you so much, I greatly appreciate that! :beers:

**Comment by sjmackenzie** [comment]
Ah wait, @P-E-Meunier just tried to take it for a spin but the patch doesn't pass muster.
```
error: attribute '0.8.10' missing, at /home/stewart/workspace/nixpkgs/pkgs/build-support/rust/carnix.nix:9:12
```

**Comment by sjmackenzie** [comment]
The carnix 0.8.10 executable is generating code without panicking, but the generated code seems to be incorrect.
```
[nix-shell:~/dev/fractalide/rust-cardano]$ carnix build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: undefined variable 'buildRustCrateHelpers' at /home/stewart/dev/fractalide/rust-cardano/Cargo.nix:3:6
```
```
$ carnix generate-nix
Prefetching cardano-0.1.0
nix-prefetch-url returned:
error: unable to download 'https://crates.io/api/v1/crates/cardano/0.1.0/download': HTTP error 404
```

**Comment by sjmackenzie** [comment]
Okay I've found a last little bug in the software (at least for this current flow I'm doing)

To put it briefly:
when Cargo.toml has `crate-type = ["staticlib", "cdylib", "dylib" ]` shared objects are not generated
when Cargo.toml has `crate-type = ["cdylib", "dylib" ]` shared objects are generated

https://nest.pijul.com/pmeunier/carnix/discussions/16

**Comment by sjmackenzie** [comment]
@P-E-Meunier nearly! :-)
```
$ nix-shell -p carnix cargo -I nixpkgs=/home/stewart/dev/fractalide/nixpkgs
error: value is a string while a list was expected, at /home/stewart/dev/fractalide/nixpkgs/pkgs/build-support/rust/build-rust-crate/build-crate.nix:47:39
```

**Comment by P-E-Meunier** [comment]
Yes, you should regenerate your Cargo.nix, the types have changed.

**Comment by sjmackenzie** [comment]
Na mate, I haven't got to the stage to regenerate my Cargo.nix file. It's failing on the stage to get `carnix-0.8.11`. In other words there seems to be a syntax in your most recent patch. Here's the error message https://gist.github.com/GrahamcOfBorg/712adeff95a6d8448d83780b513aa89e

**Comment by sjmackenzie** [comment]
Ah, the error persists: given the most recent patch only changes a comment and code.
(https://github.com/NixOS/nixpkgs/pull/40587/commits/e6e9bb49b9d9e8bd6b67bc60173544e97941192d)
```
$ nix-shell -p carnix cargo -I nixpkgs=/home/stewart/dev/fractalide/nixpkgs
error: value is a string while a list was expected, at /home/stewart/dev/fractalide/nixpkgs/pkgs/build-support/rust/build-rust-crate/build-crate.nix:47:39
```

**Comment by sjmackenzie** [comment]
How very odd, I'm on https://github.com/NixOS/nixpkgs/pull/40587/commits/08d8ff07f1db8532e733017abc2f5c5fb2e32dba and I'm getting  `can't find crate` errors:
```
$ nix-shell -p carnix cargo -I nixpkgs=/home/stewart/dev/fractalide/nixpkgs
...
error: extern location for linked_hash_map does not exist: /nix/store/acpkp8m08szmc018a1x4k5d77rz3pr8y-rust_linked-hash-map-0.4.2/lib/liblinked_hash_map-30c6cccf41.so

error[E0463]: can't find crate for `linked_hash_map`
  --> src/lib.rs:40:1
   |
40 | extern crate linked_hash_map;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0463`.
error: extern location for either does not exist: /nix/store/dimshwfs3cdbv45p6dgyfp8v0yrkd85b-rust_either-1.5.0/lib/libeither-6ff867d1be.so

error[E0463]: can't find crate for `either`
  --> src/lib.rs:27:1
   |
27 | extern crate either;
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors
```

**Comment by P-E-Meunier** [comment]
Thanks @sjmackenzie, and sorry about the multiple failed attempts. I believe it's working now.

**Comment by dywedir** [comment]
@GrahamcOfBorg build carnix cargo-vendor

**Comment by sjmackenzie** [comment]
LGTM! @P-E-Meunier it's always a pleasure using your software mate. Thanks!

**Comment by sjmackenzie** [comment]
@qknight @gebner seems like this is ready to be merged!

**Comment by P-E-Meunier** [comment]
I don't know why buildRustCrateHelpers was removed from the repository, who did it, nor why I wasn't asked to review that change or to update Carnix to take it into account, but I just spent two hours debugging a project that required it, and kept giving me obscure errors.

The code produced by the version of Carnix that's in nixpkgs *requires* that line, and that's actually why it was there.

Maybe a bad git merge is responsible for this situation, since I couldn't find any other information about the change. In any case, we need that line (and that file) back.

The last thing I want is to fight with anyone, because I love everybody, and I know everyone spent lots of time on Nix and Nixpkgs, which is a fantastic project. But I'm a little bit upset, since I invested a substantial amount of time into Carnix to make it work out of the box, and accommodated many feature requests from the community.

**Comment by P-E-Meunier** [comment]
Wait, was this entire PR reverted? Why?

**Comment by tilpner** [comment]
[Seems to be still present](https://github.com/NixOS/nixpkgs/blob/da65cfca0242beed8182b5c8592f890f95a7e5ca/pkgs/build-support/rust/build-rust-crate/helpers.nix)?

**Comment by P-E-Meunier** [comment]
Ok, this is weird. I didn't check it out locally, and only looked at GitHub. I can definitely see it there now, I swear it didn't show up when I wrote that. Thanks.

**Comment by sjmackenzie** [comment]
@P-E-Meunier it's not just you, i've seen similar oddities before; search functionality, Mary Celeste code. Not often, but enough to question my sanity.

**Pull request merged**
