### PR TITLE
python39Packages.google-auth-oauthlib: 0.4.6 -> 0.5.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 165984` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.dm-sonnet</li>
<li>python39Packages.graph_nets</li>
<li>python39Packages.optuna</li>
<li>python39Packages.pywick</li>
<li>python39Packages.rl-coach</li>
<li>python39Packages.shap</li>
<li>python39Packages.skorch</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python39Packages.elegy: log was empty</li>
<li>python39Packages.treex: log was empty</li>
  </ul>
</details>
<details>

  <summary>20 packages failed to build and are new build failures:</summary>
  <ul>
<li>python39Packages.augmax: log was empty</li>
<li>python39Packages.boxx: log was empty</li>
<li>python39Packages.bpycv: log was empty</li>
<li>python39Packages.dm-haiku: log was empty</li>
<li>python39Packages.einops: log was empty</li>
<li>python39Packages.ffcv: log was empty</li>
<li>python39Packages.flax: log was empty</li>
<li>python39Packages.ignite: log was empty</li>
<li>python39Packages.objax: log was empty</li>
<li>python39Packages.optax: log was empty</li>
<li>python39Packages.qiskit: log was empty</li>
<li>python39Packages.qiskit-machine-learning: log was empty</li>
<li>python39Packages.rising: log was empty</li>
<li>python39Packages.slicer: log was empty</li>
<li>python39Packages.spacy-transformers: log was empty</li>
<li>python39Packages.stanza: log was empty</li>
<li>python39Packages.test-tube: log was empty</li>
<li>python39Packages.torch-tb-profiler: log was empty</li>
<li>python39Packages.torchinfo: log was empty</li>
<li>python39Packages.zcs: log was empty</li>
  </ul>
</details>
<details>
<summary>
21 packages built:
</summary>
<ul>
<li>beancount (python39Packages.beancount)</li>
<li>fava</li>
<li>git-annex-remote-googledrive</li>
<li>home-assistant-component-tests.nest</li>
<li>ledger2beancount</li>
<li>python310Packages.beancount</li>
<li>python310Packages.beancount_docverif</li>
<li>python310Packages.drivelib</li>
<li>python310Packages.gcsfs</li>
<li>python310Packages.google-auth-oauthlib</li>
<li>python310Packages.google-nest-sdm</li>
<li>python310Packages.gspread</li>
<li>python310Packages.oauthenticator</li>
<li>python39Packages.beancount_docverif</li>
<li>python39Packages.drivelib</li>
<li>python39Packages.gcsfs</li>
<li>python39Packages.google-auth-oauthlib</li>
<li>python39Packages.google-nest-sdm</li>
<li>python39Packages.gspread</li>
<li>python39Packages.oauthenticator</li>
<li>s3ql</li>
</ul>
</details>

**Comment by samuela** [comment]
This broke 

dm-haiku
optax
pytorch
pytorchWithCuda
tensorflow
tensorflow-bin
tensorflow-datasets
torchvision
flax

and likely many others as was shown in https://github.com/NixOS/nixpkgs/pull/165984#issuecomment-1080044479. Why was this merged? Can you please revert?

**Comment by samuela** [comment]
should be fixed in https://github.com/NixOS/nixpkgs/pull/166027

**Comment by SuperSandro2000** [comment]
> and likely many others as was shown in [#165984 (comment)](https://github.com/NixOS/nixpkgs/pull/165984#issuecomment-1080044479). Why was this merged? Can you please revert?

Because I thought I manually verified locally that this was only a network being flaky. Next time please wait like a day and let me fix the over eagerly version constraints. No need to rush revert this.

**Pull request merged**
