### PR TITLE
add QmidiNet: a MIDI network gateway application

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by jagajaga** [comment]
Have you tested it? Travis fails...

**Comment by magnetophon** [comment]
@jagajaga 
It runs and works on 14.12 32bit.
The problem is https://travis-ci.org/NixOS/nixpkgs/builds/63617650#L1408
Not sure what causes that.

**Comment by jagajaga** [comment]
Test with master, because we had qt update.

**Comment by magnetophon** [comment]
It runs on 15.06 pre, but doesn't transmit midi.
Still investigating...

**Comment by magnetophon** [comment]
tried again, now I have a fully working setup with one box on 14.12 and another on 15.06 pre.

**Comment by magnetophon** [comment]
@jagajaga I'm now sending midi between two 15.06 boxes.

**Comment by jagajaga** [comment]
So it works?

**Comment by magnetophon** [comment]
@jagajaga yup, works smoothly. No idea what the orig problem was.

**Pull request merged**
