### PR TITLE
Fixes for python3.pkgs.{jedi,python-language-server,engineio}

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by Mic92** [comment]
This also unbreaks jedi/python-language-server on 20.03.

**Review by timokau — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/97209
1 package blacklisted:
tests.nixos-functions.nixosTest-test

51 packages failed to build:
datasette dvc-with-remotes google-music-scripts ihaskell paperless python27Packages.jedi python27Packages.pyls-isort python27Packages.python-language-server python37Packages.Nikola python37Packages.asgi-csrf python37Packages.datasette python37Packages.datashader python37Packages.google-music python37Packages.google_cloud_bigquery python37Packages.httpx python37Packages.ipydatawidgets python37Packages.jupytext python37Packages.mask-rcnn python37Packages.nbval python37Packages.onnx python37Packages.optuna python37Packages.robotframework-tools python37Packages.rpy2 python37Packages.runway-python python37Packages.scikit-tda python37Packages.skein python37Packages.snowflake-connector-python python37Packages.snowflake-sqlalchemy python37Packages.spyder python38Packages.Nikola python38Packages.asgi-csrf python38Packages.datashader python38Packages.google-music python38Packages.google_cloud_bigquery python38Packages.httpx python38Packages.ipydatawidgets python38Packages.jupytext python38Packages.nbval python38Packages.onnx python38Packages.robotframework-tools python38Packages.rpy2 python38Packages.runway-python python38Packages.scikit-tda python38Packages.skein python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy spyder sage sageWithDoc streamlit terraform-compliance

415 packages built:
adafruit-ampy appdaemon arion azure-cli cq-editor deeptools docker-compose fdroidserver gdbgui gnome3.accerciser inkcut jira-cli john jupyter nbstripout python37Packages.Pweave python37Packages.altair python37Packages.androguard python37Packages.ansible-kernel python37Packages.azure-applicationinsights python37Packages.azure-batch python37Packages.azure-core python37Packages.azure-eventgrid python37Packages.azure-functions-devops-build python37Packages.azure-graphrbac python37Packages.azure-identity python37Packages.azure-keyvault python37Packages.azure-keyvault-certificates python37Packages.azure-keyvault-keys python37Packages.azure-keyvault-secrets python37Packages.azure-loganalytics python37Packages.azure-mgmt-advisor python37Packages.azure-mgmt-apimanagement python37Packages.azure-mgmt-appconfiguration python37Packages.azure-mgmt-applicationinsights python37Packages.azure-mgmt-authorization python37Packages.azure-mgmt-batch python37Packages.azure-mgmt-batchai python37Packages.azure-mgmt-billing python37Packages.azure-mgmt-botservice python37Packages.azure-mgmt-cdn python37Packages.azure-mgmt-cognitiveservices python37Packages.azure-mgmt-commerce python37Packages.azure-mgmt-common python37Packages.azure-mgmt-compute python37Packages.azure-mgmt-consumption python37Packages.azure-mgmt-containerinstance python37Packages.azure-mgmt-containerregistry python37Packages.azure-mgmt-containerservice python37Packages.azure-mgmt-core python37Packages.azure-mgmt-cosmosdb python37Packages.azure-mgmt-datafactory python37Packages.azure-mgmt-datalake-analytics python37Packages.azure-mgmt-datalake-store python37Packages.azure-mgmt-datamigration python37Packages.azure-mgmt-deploymentmanager python37Packages.azure-mgmt-devspaces python37Packages.azure-mgmt-devtestlabs python37Packages.azure-mgmt-dns python37Packages.azure-mgmt-eventgrid python37Packages.azure-mgmt-eventhub python37Packages.azure-mgmt-hanaonazure python37Packages.azure-mgmt-hdinsight python37Packages.azure-mgmt-imagebuilder python37Packages.azure-mgmt-iotcentral python37Packages.azure-mgmt-iothub python37Packages.azure-mgmt-iothubprovisioningservices python37Packages.azure-mgmt-keyvault python37Packages.azure-mgmt-kusto python37Packages.azure-mgmt-loganalytics python37Packages.azure-mgmt-logic python37Packages.azure-mgmt-machinelearningcompute python37Packages.azure-mgmt-managedservices python37Packages.azure-mgmt-managementgroups python37Packages.azure-mgmt-managementpartner python37Packages.azure-mgmt-maps python37Packages.azure-mgmt-marketplaceordering python37Packages.azure-mgmt-media python37Packages.azure-mgmt-monitor python37Packages.azure-mgmt-msi python37Packages.azure-mgmt-netapp python37Packages.azure-mgmt-network python37Packages.azure-mgmt-notificationhubs python37Packages.azure-mgmt-policyinsights python37Packages.azure-mgmt-powerbiembedded python37Packages.azure-mgmt-privatedns python37Packages.azure-mgmt-rdbms python37Packages.azure-mgmt-recoveryservices python37Packages.azure-mgmt-recoveryservicesbackup python37Packages.azure-mgmt-redhatopenshift python37Packages.azure-mgmt-redis python37Packages.azure-mgmt-relay python37Packages.azure-mgmt-reservations python37Packages.azure-mgmt-resource python37Packages.azure-mgmt-scheduler python37Packages.azure-mgmt-search python37Packages.azure-mgmt-security python37Packages.azure-mgmt-servicebus python37Packages.azure-mgmt-servicefabric python37Packages.azure-mgmt-signalr python37Packages.azure-mgmt-sql python37Packages.azure-mgmt-sqlvirtualmachine python37Packages.azure-mgmt-storage python37Packages.azure-mgmt-subscription python37Packages.azure-mgmt-synapse python37Packages.azure-mgmt-trafficmanager python37Packages.azure-mgmt-web python37Packages.azure-multiapi-storage python37Packages.azure-servicebus python37Packages.azure-servicefabric python37Packages.azure-storage-blob python37Packages.azure-storage-file-share python37Packages.azure-synapse-accesscontrol python37Packages.azure-synapse-spark python37Packages.bash_kernel python37Packages.batchspawner python37Packages.brother python37Packages.bugwarrior python37Packages.caffe python37Packages.chart-studio python37Packages.colorcet python37Packages.cufflinks python37Packages.dash python37Packages.dftfit python37Packages.dockerspawner python37Packages.envisage python37Packages.flask-socketio python37Packages.greatfet python37Packages.holoviews python37Packages.hvplot python37Packages.intake python37Packages.ipdb python37Packages.ipdbplugin python37Packages.ipykernel python37Packages.ipympl python37Packages.ipyparallel python37Packages.ipython python37Packages.ipyvue python37Packages.ipyvuetify python37Packages.ipywidgets python37Packages.jedi python37Packages.jira python37Packages.jupyter python37Packages.jupyter-c-kernel python37Packages.jupyter-sphinx python37Packages.jupyter_client python37Packages.jupyter_console python37Packages.jupyter_core python37Packages.jupyterhub python37Packages.jupyterhub-ldapauthenticator python37Packages.jupyterhub-systemdspawner python37Packages.jupyterhub-tmpauthenticator python37Packages.jupyterlab python37Packages.jupyterlab-git python37Packages.jupyterlab_launcher python37Packages.jupyterlab_server python37Packages.kmapper python37Packages.lammps-cython python37Packages.line_profiler python37Packages.livelossplot python37Packages.mayavi python37Packages.modeled python37Packages.moretools python37Packages.msrest python37Packages.msrestazure python37Packages.nbclient python37Packages.nbconflux python37Packages.nbconvert python37Packages.nbdime python37Packages.nbformat python37Packages.nbmerge python37Packages.nbsmoke python37Packages.nbsphinx python37Packages.nix-kernel python37Packages.notebook python37Packages.notedown python37Packages.oauthenticator python37Packages.papermill python37Packages.phik python37Packages.plotly python37Packages.ptpython python37Packages.pygmo python37Packages.pyls-black python37Packages.pyls-isort python37Packages.pyls-mypy python37Packages.pymatgen python37Packages.pymatgen-lammps python37Packages.pytest-trio python37Packages.python-dotenv python37Packages.python-engineio python37Packages.python-language-server python37Packages.python-socketio python37Packages.qasm2image python37Packages.qiskit python37Packages.qiskit-aer python37Packages.qiskit-aqua python37Packages.qiskit-ibmq-provider python37Packages.qiskit-ignis python37Packages.qiskit-terra python37Packages.qtconsole python37Packages.scapy python37Packages.scikit-bio python37Packages.sopel python37Packages.spyder-kernels python37Packages.spyder-kernels_0_5 python37Packages.spyder_3 python37Packages.sumo python37Packages.trio python37Packages.vega python37Packages.vsts python37Packages.vsts-cd-manager python37Packages.widgetsnbextension python37Packages.zetup python38Packages.Pweave python38Packages.altair python38Packages.androguard python38Packages.ansible-kernel python38Packages.azure-applicationinsights python38Packages.azure-batch python38Packages.azure-core python38Packages.azure-eventgrid python38Packages.azure-functions-devops-build python38Packages.azure-graphrbac python38Packages.azure-keyvault python38Packages.azure-keyvault-certificates python38Packages.azure-keyvault-keys python38Packages.azure-keyvault-secrets python38Packages.azure-loganalytics python38Packages.azure-mgmt-advisor python38Packages.azure-mgmt-apimanagement python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-applicationinsights python38Packages.azure-mgmt-authorization python38Packages.azure-mgmt-batch python38Packages.azure-mgmt-batchai python38Packages.azure-mgmt-billing python38Packages.azure-mgmt-botservice python38Packages.azure-mgmt-cdn python38Packages.azure-mgmt-cognitiveservices python38Packages.azure-mgmt-commerce python38Packages.azure-mgmt-common python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-consumption python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerregistry python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-core python38Packages.azure-mgmt-cosmosdb python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-datalake-analytics python38Packages.azure-mgmt-datalake-store python38Packages.azure-mgmt-datamigration python38Packages.azure-mgmt-deploymentmanager python38Packages.azure-mgmt-devspaces python38Packages.azure-mgmt-devtestlabs python38Packages.azure-mgmt-dns python38Packages.azure-mgmt-eventgrid python38Packages.azure-mgmt-eventhub python38Packages.azure-mgmt-hanaonazure python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-imagebuilder python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-iothub python38Packages.azure-mgmt-iothubprovisioningservices python38Packages.azure-mgmt-keyvault python38Packages.azure-mgmt-kusto python38Packages.azure-mgmt-loganalytics python38Packages.azure-mgmt-logic python38Packages.azure-mgmt-machinelearningcompute python38Packages.azure-mgmt-managedservices python38Packages.azure-mgmt-managementgroups python38Packages.azure-mgmt-managementpartner python38Packages.azure-mgmt-maps python38Packages.azure-mgmt-marketplaceordering python38Packages.azure-mgmt-media python38Packages.azure-mgmt-monitor python38Packages.azure-mgmt-msi python38Packages.azure-mgmt-netapp python38Packages.azure-mgmt-network python38Packages.azure-mgmt-notificationhubs python38Packages.azure-mgmt-policyinsights python38Packages.azure-mgmt-powerbiembedded python38Packages.azure-mgmt-privatedns python38Packages.azure-mgmt-rdbms python38Packages.azure-mgmt-recoveryservices python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-redhatopenshift python38Packages.azure-mgmt-redis python38Packages.azure-mgmt-relay python38Packages.azure-mgmt-reservations python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-scheduler python38Packages.azure-mgmt-search python38Packages.azure-mgmt-security python38Packages.azure-mgmt-servicebus python38Packages.azure-mgmt-servicefabric python38Packages.azure-mgmt-signalr python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-sqlvirtualmachine python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-mgmt-synapse python38Packages.azure-mgmt-trafficmanager python38Packages.azure-mgmt-web python38Packages.azure-multiapi-storage python38Packages.azure-servicebus python38Packages.azure-servicefabric python38Packages.azure-storage-blob python38Packages.azure-storage-file-share python38Packages.azure-synapse-accesscontrol python38Packages.azure-synapse-spark python38Packages.bash_kernel python38Packages.batchspawner python38Packages.brother python38Packages.bugwarrior python38Packages.caffe python38Packages.chart-studio python38Packages.colorcet python38Packages.cufflinks python38Packages.dash python38Packages.dftfit python38Packages.dockerspawner python38Packages.envisage python38Packages.flask-socketio python38Packages.greatfet python38Packages.holoviews python38Packages.hvplot python38Packages.intake python38Packages.ipdb python38Packages.ipdbplugin python38Packages.ipykernel python38Packages.ipympl python38Packages.ipyparallel python38Packages.ipython python38Packages.ipyvue python38Packages.ipyvuetify python38Packages.ipywidgets python38Packages.jedi python38Packages.jira python38Packages.jupyter python38Packages.jupyter-c-kernel python38Packages.jupyter-sphinx python38Packages.jupyter_client python38Packages.jupyter_console python38Packages.jupyter_core python38Packages.jupyterhub python38Packages.jupyterhub-ldapauthenticator python38Packages.jupyterhub-systemdspawner python38Packages.jupyterhub-tmpauthenticator python38Packages.jupyterlab python38Packages.jupyterlab-git python38Packages.jupyterlab_launcher python38Packages.jupyterlab_server python38Packages.kmapper python38Packages.lammps-cython python38Packages.line_profiler python38Packages.livelossplot python38Packages.mayavi python38Packages.modeled python38Packages.moretools python38Packages.msrest python38Packages.msrestazure python38Packages.nbclient python38Packages.nbconflux python38Packages.nbconvert python38Packages.nbdime python38Packages.nbformat python38Packages.nbmerge python38Packages.nbsmoke python38Packages.nbsphinx python38Packages.nix-kernel python38Packages.notebook python38Packages.notedown python38Packages.oauthenticator python38Packages.papermill python38Packages.phik python38Packages.plotly python38Packages.ptpython python38Packages.pygmo python38Packages.pyls-black python38Packages.pyls-isort python38Packages.pyls-mypy python38Packages.pymatgen python38Packages.pymatgen-lammps python38Packages.pytest-trio python38Packages.python-dotenv python38Packages.python-engineio python38Packages.python-language-server python38Packages.python-socketio python38Packages.qasm2image python38Packages.qiskit python38Packages.qiskit-aer python38Packages.qiskit-aqua python38Packages.qiskit-ibmq-provider python38Packages.qiskit-ignis python38Packages.qiskit-terra python38Packages.qtconsole python38Packages.scapy python38Packages.scikit-bio python38Packages.sopel python38Packages.spyder-kernels python38Packages.spyder-kernels_0_5 python38Packages.spyder_3 python38Packages.sumo python38Packages.trio python38Packages.vega python38Packages.vsts python38Packages.vsts-cd-manager python38Packages.widgetsnbextension python38Packages.zetup snakemake tebreak theharvester thonny vimPlugins.jedi-vim
```

**Comment by jonringer** [comment]
@Mic92 not sure why some packages are winding up in "failed" when they are marked broken, in this case `ihaskell` got included erroneously

**Comment by Mic92** [comment]
> @Mic92 not sure why some packages are winding up in "failed" when they are marked broken, in this case `ihaskell` got included erroneously

Is this still a problem after https://github.com/Mic92/nixpkgs-review/commit/69d7f9539ae47a62211d2f8682119a5f4a138637 with nix-review 2.4.0.

**Comment by jonringer** [comment]
correct, i was using 2.4.0

**Pull request merged**
