### PR TITLE
pocketsphinx/sphinxbase/parlatype: remove

### PR DESCRIPTION
**Pull request by armeenm**
###### Description of changes
Remove `pocketsphinx`, `sphinxbase`, `parlatype`, and `haskellPackages.cut-the-crap`. See #169609.

NB: There's probably a better way I should be deprecating a Haskell package; please let me know.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Other than the haskell package removal, LGTM. That probably needs to be done in another way, hopefully @NixOS/haskell can assist with that.

**Comment by sternenseemann** [comment]
The changes to the haskell package set would be rolled back, just leave it as is. The package is marked as broken anyways already and we don't guarantee that anything in there is usable/maintained.

**Comment by armeenm** [comment]
Thanks for your suggestions. Please let me know if there's anything else.

**Comment by Mindavi** [comment]
LGTM.

nixpkgs-review says:

3 packages removed:
parlatype (†2.1) pocketsphinx (†5prealpha) sphinxbase (†5prealpha)

**Pull request merged**
