### PR TITLE
gnome3.20: init at 3.20.0

### PR DESCRIPTION
**Pull request by DamienCassou**
Having fun trying to package Gnome 3.20.
- migrated from pull request: #14290
- issue: #14289

cc @lethalman @vcunat @jgillich 

---

To be done:
- [x] Aisleriot doesn't build ([upstream bug](https://bugzilla.gnome.org/show_bug.cgi?id=764305), but this is not blocking for us) : fixed by making a libcanberra version depending on `gtk+-3.20`
- [ ] Fix commits with `(todo)` in their message
- [x] Enable Google authentication in evolution-data-server (keep it disabled for now)
- [ ] Re-enable empathy (currently commented in both `all-packages.nix` and `gnome3_20/default.nix`)
- [ ] Take care of re-applying recent PR on gnome 3.18
  - [ ] #14573
  - [ ] #14702
  - [ ] #14707
  - [ ] ca717d0d654c11cc59622123251e79bb9ec7142d
- [ ] Make sure  the `nixos-rebuild` output depends on latest libraries:
  
  ``` bash
  $ nix-build nixos/tests/gnome3-gdm.nix
  $ nix-store -qR result
  ```
  - no gtk 3.18
  - no gnome 3.18
  - latest clutter

### CODE REVIEW

**Comment by lethalman** [comment]
Removing mass-rebuild, historically we usually consider mass-rebuild things like openssl or stdenv, not graphical stuff.

**Comment by lethalman** [comment]
In what way doesn't google auth work? It doesn't build or it doesn't work?

**Comment by lethalman** [comment]
Soup is be necessary for gnome-maps: https://github.com/GNOME/gnome-maps/search?utf8=%E2%9C%93&q=soup
It builds because it's javascript, but then at runtime it wouldn't work. Perhaps the patch needs to be updated.

**Comment by DamienCassou** [comment]
@lethalman evolution-data-server won't build (missing dependencies) if Google auth is enabled. I had a look at the missing dependencies and had the impression they were present. I decided to go on and come back later.

@lethalman ok for gnome-maps and libsoup. It's on my todo list.

**Comment by DamienCassou** [comment]
@lethalman @edolstra I've a question about harfbuzz and it's use in gnome3.20's sushi. To make sushi compile, I have to patch its files (see commit 6d0a864):

```diff
+  postConfigure = ''
+    substituteInPlace src/libsushi/sushi-font-widget.h \
+        --replace "<hb-ft.h>" "<harfbuzz/hb-ft.h>"
+    substituteInPlace src/libsushi/sushi-font-widget.c \
+        --replace "<hb-glib.h>" "<harfbuzz/hb-glib.h>"
+  '';
```

Is that an upstream bug? How can it even build for them?

**Comment by vcunat** [comment]
Strange. It should work if they passed "correct" cflags.
```
$ nix-shell -I nixpkgs=. -p pkgconfig -p harfbuzz
$ pkg-config --cflags harfbuzz
-I/nix/store/bvx3xyrcpfdf8rl00kg75cwkcwcardaq-harfbuzz-1.1.2/include/harfbuzz
```

**Comment by DamienCassou** [comment]
@lethalman why do some gnome packages, like tracker, embed the definition of their `src` whereas most others have a `src.nix` autogenerated?

**Comment by lethalman** [comment]
That sushi version doesn't depend on harfbuzz at all, they fixed it on master though: https://github.com/GNOME/sushi/blame/master/configure.ac#L58

**Comment by lethalman** [comment]
@DamienCassou because I didn't transition all the packages to the external src.nix. You can do it.

**Comment by DamienCassou** [comment]
@lethalman the dependency is not specified in the configure script, but the C files depend on harfbuzz header files.

**Comment by lethalman** [comment]
@DamienCassou yes what I said, it's fixed in their master branch.

**Comment by DamienCassou** [comment]
build is finally finished! I will see if I can switch my system and use it now.

**Comment by DamienCassou** [comment]
if someone wants to try re-enabling `gnome3_20.empathy`, that would be great. I give up.

**Comment by DamienCassou** [comment]
Lethalman:
> we must be sure that the nixos-rebuild output does not depend on gtk 3.18 or any of the gnome 3.18 dependencies

how can I do that please?

**Comment by lethalman** [comment]
@DamienCassou `nix-build nixos/tests/gnome3-gdm.nix`, then check with `nix-store -qR result`

**Comment by lethalman** [comment]
Let's keep google auth disabled of e-d-s for now, it requires webkitgtk and json-glib. I'd like to keep less dependencies on webkitgtk. We can re-enable it if someone needs it in the future.

**Comment by jgillich** [comment]
I'm not quite sure what `e-d-s` is, but I probably do...

**Comment by DamienCassou** [comment]
@jgillich e-d-s = evolution-data-server

**Comment by vcunat** [comment]
Nitpick: it's typically better to avoid force-pushing on branches in NixOS/nixpkgs.

**Comment by DamienCassou** [comment]
@vcunat sorry about that. I'm still in a learning phase and I can't do things without doing mistakes. Can I please continue force pushing this time? Next time, I will keep work in my remote.

**Comment by vcunat** [comment]
I think it's not really a problem, at least until someone tries to collaborate on that branch or base stuff on it. (Neither seems likely to happen within a few days.)

**Comment by DamienCassou** [comment]
is it required to update gtkmm from 3.18 to 3.20 right now? I have the impression this triggers a lot of additional required changes (including patching inkscape).

**Comment by vcunat** [comment]
It's likely not required for anything. We were often leaving *mm lagging behind gnome versions.

**Comment by DamienCassou** [comment]
```
$ nix-build nixos/tests/gnome3-gdm.nix
machine# [   41.188876] dhclient[668]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 13
machine: exit status 0
machine: making screenshot ‘screen.png’
machine: sending monitor command: screendump /nix/store/gic3cph6zzczj9n56cn0m0wrwwn1s1q3-vm-test-run-gnome3-gdm/screen.png.ppm
collecting coverage data
machine: running command: test -e /sys/kernel/debug/gcov
machine: exit status 1
syncing
machine: running command: sync
machine: exit status 0
cleaning up
killing machine (pid 66)
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: Could not remove ctl dir '/tmp/nix-build-vm-test-run-gnome3-gdm.drv-0/vde1.ctl': Directory not empty
/nix/store/gic3cph6zzczj9n56cn0m0wrwwn1s1q3-vm-test-run-gnome3-gdm

$ echo $?
1
```

**Comment by lethalman** [comment]
It built fine for me, but it's a different hash: /nix/store/q30zc7r80qxb54gzdf50gak2wci2bshj-vm-test-run-gnome3-gdm

**Comment by vcunat** [comment]
Some nixos derivations (documenation?) capture whole subdirectories of your nixpkgs, so if one has stray files in there, they will change the hashes.

**Comment by lethalman** [comment]
@vcunat did a `git clean -xdf` and the result is the same.

**Comment by lethalman** [comment]
I've added the `nixos/tests/gnome3_20.nix` test. It fails to run gnome shell apparently.

**Comment by DamienCassou** [comment]
@lethalman this is beyond my knowledge and available time right now. Are you ok to carry on this work? I know I only did the simple things but I hope it helps a bit.

**Comment by vcunat** [comment]
The libgit2 update (shared by all packages) broke the older version of libgit2-glib in gnome-3.18. I suppose we should keep these two close to each other, either both outside gnome3 or both in. I expect it should be easiest to keep them shared by all, similarly to glib itself. @lethalman: what do you think?

Otherwise I can't see any significant regressions, so we could merge and continue fixing gnome-3.20 on master.

**Comment by DamienCassou** [comment]
@vcunat thanks for testing. I was a bit afraid of the patch to Inkscape I had to do. I hope there won't be other such regressions. As you suggested earlier, we could also let `*mm` packages behind.

**Comment by vcunat** [comment]
I haven't really tested myself yet &ndash; I just looked at Hydra.

**Comment by lethalman** [comment]
Sure I can jump on this, no problem. Will fix stuff, as soon as gnome-shell works I'll merge.

**Comment by lethalman** [comment]
Squashed all the gnome related things.

**Comment by lethalman** [comment]
Still haven't found the reason why gnome 3.20 doesn't start.

**Comment by DamienCassou** [comment]
@lethalman what about updating gdm to 3.20 as well?

**Comment by lethalman** [comment]
@DamienCassou I've tried 3.16 and 3.18 in the past of course, but failed. Currently I can't even run gnome 3.20, it doesn't start gnome-shell, so trying to use 3.20 is out of question for me. If you want to try it, feel free to but be aware it's a mess.

**Comment by DamienCassou** [comment]
@lethalman ok ok :-). I just thought maybe the problems with gnome 3.20 could be solved with a newer gdm, but I know nothing about that

**Comment by lethalman** [comment]
@DamienCassou yes quite possible. Every gdm version is a different beast. But I'm more worried about gnome 3.20 not working at all :)

**Comment by vcunat** [comment]
Based on your gnome-3.18 testing, I picked a few of your commits to staging in 4d37411b35046b4 (without `-x` as you tend to change the history) &ndash; notably gtk3 and glib major updates.

**Comment by bjornfor** [comment]
Please remember to "rebase" once in a while, so that changes introduced in GNOME 3.18 files, since this branch was started, are not lost. For instance, I had to re-apply ca717d0d654c11cc59622123251e79bb9ec7142d because it was lost during 3.16 -> 3.18.

**Comment by lethalman** [comment]
rebased on current unstable 6d16979, also added the test to the release so we can see it on hydra

**Comment by lethalman** [comment]
Today I finally had some time to track down the issue. It was this bug that has been fixed with gnome-session 3.20.1: https://github.com/GNOME/gnome-session/commit/890a797a2b6c26e752fa74a09d9521bea913c621

**Comment by DamienCassou** [comment]
On June 2, 2016 1:43:30 PM GMT+02:00, Luca Bruno <notifications@github.com> wrote:
>Today I finally had some time to track down the issue. It was this bug
>that has been fixed with gnome-session 3.20.1:
>https://github.com/GNOME/gnome-session/commit/890a797a2b6c26e752fa74a09d9521bea913c621

Thank you Luca. I'm far away from any computer but will try when I come back.
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by lethalman** [comment]
@vcunat merged, I think we can delete the gnome-3.20 jobset.

**Comment by vcunat** [comment]
I tried to delete the jobset and since then hydra.nixos.org stopped working completely :-( I'm really sorry if I triggered it. /cc @edolstra

**Pull request merged**
