### PR TITLE
cdrtools: fix for darwin

### LINKED ISSUE #60357: cdrtools broken on darwin
## Issue description
Cdrtools ([current nixpkg](https://github.com/NixOS/nixpkgs/blob/92a047a6c4d46a222e9c323ea85882d0a7a13af8/pkgs/applications/misc/cdrtools/default.nix)) is compatible with darwin, but doesn't build here with nix yet.  

Removing the incompatible dependencies on `acl` and `libcap` results in a failed build ([full log](https://gist.github.com/Amar1729/09e1be5a36c7ffaa0c66b0758994cff8#file-cdrtools-original-log)). Last few lines:
```
creating xconfig.h
        ==> MAKING SYMLINKS in ./RULES/
        ==> MAKING SYMLINKS in ./TEMPLATES/
sh conf/cc-config.sh cc cc incs/Dcc.i386-darwin
Trying to find cc
Found cc
cc is clang
Making clang the default compiler in 'incs/Dcc.i386-darwin'
        ==> MAKING DIRECTORY "incs/i386-darwin-clang/Inull"
        ==> CONFIGURING RULES "incs/i386-darwin-clang/rules.cnf"
creating cache ./config.cache
checking host system type... x86_64-apple-macosx18.5.0
checking if sh is bash... yes
checking if /bin/sh is bash... yes
checking whether sh -ce is broken... no
checking whether /bin/sh -ce is broken... no
checking whether /bin/bosh is a working shell... no
checking whether /opt/schily/bin/bosh is a working shell... no
checking for cc... clang
checking for gcc... (cached) clang
checking whether the C compiler (clang   -O   -Llibs/i386-darwin-clang -L/usr/local/lib -framework IOKit -framework CoreFoundation) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
RULES/rules.cnf:71: incs/i386-darwin-clang/rules.cnf: No such file or directory
make: *** [RULES/rules.cnf:59: incs/i386-darwin-clang/rules.cnf] Error 1
builder for '/nix/store/2gp07d7nn4pw697y7n6rpkcpw638404s-cdrtools-3.02a06.drv' failed with exit code 2
error: build of '/nix/store/2gp07d7nn4pw697y7n6rpkcpw638404s-cdrtools-3.02a06.drv' failed
```

I've updated the package in the following ways:
- `doBuild=false`
- changed the installPhase to:
  - `make INS_BASE=#{out} INS_RBASE=#{out} DESTDIR=#{out} install`
- included `darwin.IOKit`

Last few lines of current build error:
```
creating xconfig.h
        ==> MAKING "all" ON SUBDIRECTORY "SRCROOT/conf"
make[1]: Entering directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/conf'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/conf'
        ==> MAKING "all" ON SUBDIRECTORY "SRCROOT/inc"
make[1]: Entering directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/inc'
        ==> MAKING "all" ON SUBCOMPONENT "SRCROOT/inc/align_test.mk"
make[2]: Entering directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/inc'
        ==> MAKING DIRECTORY "OBJ/i386-darwin-clang"
        ==> MAKING DIRECTORY "OBJ/i386-darwin-clang/man"
        ==> MAKING DEPENDENCIES "OBJ/i386-darwin-clang/align_test.d"
 ==> COMPILING "OBJ/i386-darwin-clang/align_test.o"
        ==> LINKING "OBJ/i386-darwin-clang/align_test"
ld: warning: directory not found for option '-L../libs/i386-darwin-clang'
ld: warning: directory not found for option '-L../libs/i386-darwin-clang'
        ==> GENERATING include file "../incs/i386-darwin-clang/align.h"
make[2]: Leaving directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/inc'
        ==> MAKING "all" ON SUBCOMPONENT "SRCROOT/inc/avoffset.mk"
make[2]: Entering directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/inc'
        ==> MAKING DEPENDENCIES "OBJ/i386-darwin-clang/avoffset.d"
 ==> COMPILING "OBJ/i386-darwin-clang/avoffset.o"
        ==> LINKING "OBJ/i386-darwin-clang/avoffset"
ld: warning: directory not found for option '-L../libs/i386-darwin-clang'
ld: warning: directory not found for option '-L../libs/i386-darwin-clang'
        ==> GENERATING include file "../incs/i386-darwin-clang/avoffset.h"
/nix/store/jizc4dhwkp8kffbprbl3n9np8ipw6fz8-bash-4.4-p23/bin/bash: line 2: 58797 Segmentation fault: 11  OBJ/i386-darwin-clang/avoffset > ../incs/i386-darwin-clang/avoffset.h
/nix/store/jizc4dhwkp8kffbprbl3n9np8ipw6fz8-bash-4.4-p23/bin/bash: line 2: 58801 Segmentation fault: 11  OBJ/i386-darwin-clang/avoffset > ../incs/i386-darwin-clang/avoffset.h
make[2]: *** [../RULES/rules.inc:50: ../incs/i386-darwin-clang/avoffset.h] Error 139
make[2]: Leaving directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/inc'
make[1]: *** [../RULES/rules.mks:23: all] Error 2
make[1]: Leaving directory '/private/var/folders/zk/t4rzq9t166x94d10mr4r1zl5yb8l3y/T/nix-build-cdrtools-3.02a06.drv-5/cdrtools-3.02/inc'
make: *** [RULES/rules1.dir:25: all] Error 2
builder for '/nix/store/6ib4cmkpr3wz0gil8xmw6alvay4kacys-cdrtools-3.02a06.drv' failed with exit code 2
error: build of '/nix/store/6ib4cmkpr3wz0gil8xmw6alvay4kacys-cdrtools-3.02a06.drv' failed
```

([full log here](https://gist.github.com/Amar1729/09e1be5a36c7ffaa0c66b0758994cff8#file-cdrtools-log))

- [the changes i've tried on my own fork](https://github.com/NixOS/nixpkgs/compare/master...Amar1729:darwin-fix/cdrtools?expand=1)
- [`cdrtools` package in homebrew](https://github.com/Homebrew/homebrew-core/blob/7f5ad53584b5ac137fc4b9b41246180a0e5592dd/Formula/cdrtools.rb) for reference

I'll make a PR if I can figure this out, but some of these issues are stumping me. Hoping someone else has some idea how to fix it.

### Steps to reproduce

1. be on darwin and nixpkgs `master`
2. `nix-build . -A cdrtools`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.5.0, macOS 10.14.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(amar): `"nixpkgs-19.09pre177248.ed1b59a98e7"`
 - nixpkgs: `/Users/amar/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by Amar1729**
###### Motivation for this change

Updated `cdrtools` to compile on darwin. Some recent change to macOS frameworks in nix must have fixed this since I used to not be able to build this at all ( closes #60357 )

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg build cdrtools

**Comment by Amar1729** [comment]
My bad - wrote the `platforms` directive improperly.

**Comment by veprbl** [comment]
@GrahamcOfBorg build cdrtools

**Comment by veprbl** [comment]
@GrahamcOfBorg build cdrtools

**Comment by veprbl** [comment]
Thank you!

**Pull request merged**
