### PR TITLE
[Backport release-23.11] btop: 1.2.13 -> 1.3.0

### PR DESCRIPTION
**Pull request by A-Manning**
## Description of changes

Backports `btop` `1.3.0` to `release-23.11`, with GPU support
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
Does this fix any major bugs that would warrant a backport?

Mere feature additions alone or minor bug fixes usually do not qualify for backports; if you want the latest and greatest at all times, you should be using nixos-unstable.

**Comment by Atemu** [comment]
I cannot reproduce that bug using `nix run github:NixOS/nixpkgs/nixos-23.11#btop`. I also don't see a changelog note pertaining this supposed bug in 1.3.0.

**Comment by ofalvai** [comment]
I think it's platform dependent. The stable channel's version works on my macOS host, but when I tried to use it on a Linux (aarch64) host, I got the above error, then ended up in this thread because using the latest version from unstable solves my problem on Linux.

**Comment by Atemu** [comment]
If it has always been broken on aarch64-linux on 23.11, I'm inclined to leave it at that because aarch64-linux is a lesser supported platform and btop has added quite a few features since that may be breaking. Stable means stable. I'd rather keep an existing bug than to introduce a new one. 

If you can identify a specific patch that we could include to specifically fix that issue without changing anything else about btop, I'd approve of that.

Otherwise I won't be the one to merge this. I won't block the merge of this either though if someone else thinks this fits the criteria of a backport or is uncritical enough to not break the rest of stable.

**Comment by wegank** [comment]
As NixOS 23.11 reaches end-of-life today, this PR is closed as part of the [EOL cleanup](https://nixos.github.io/release-wiki/EOL-Cleanup.html).

**Pull request closed without merging**
