### PR TITLE
nncp: 8.8.3 -> 8.9.0

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

The main improvements for this release are:

* 'nncp-toss' command has '-gen-ack' option.  'nncp-daemon',
  'nncp-caller', 'nncp-call' commands have '-autotoss-gen-ack'
  option.  They automatically generate ACK packets and store
  corresponding 'spool/tx/ack/' references to them, to be able to
  remove them after the transfer.

* 'autotoss-gen-ack' appeared in call configuration.  'ack' section
  appeared in neighbour configuration.

* 'nncp-rm' command has '-ack' option to remove packets referenced by
  stored 'spool/tx/ack/' files generated during tossing.

* Get rid of 'redo' build system during installation, as there are
  virtually none dependencies, just only compilation of the Go code.

* Updated some dependencies.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Result of `nixpkgs-review pr 249064` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>nncp</li>
    <li>nncp.doc</li>
    <li>nncp.info</li>
  </ul>
</details>

**Comment by drupol** [comment]
Cool, waiting for the CI to be done before merging.

**Comment by drupol** [comment]
@ehmry There's a build issue on Darwin, do you know anything about it?

**Comment by ehmry** [comment]
There has always been build issues with NNCP on Darwin. I don't care.

**Comment by drupol** [comment]
@GrahamcOfBorg build nncp

**Comment by drupol** [comment]
@GrahamcOfBorg build nncp

**Comment by ehmry** [comment]
NixOS is a Linux distribution, we don't get blocked by Apple problems. If it doesn't build on Darwin the mark it broken and go away.

**Comment by drupol** [comment]
I will as soon as I get back on my laptop, just before lunch.

**Pull request merged**
