### PR TITLE
kubebox: init at 0.8.0

### LINKED ISSUE #92200: add kubebox
**Project description**
_Terminal and Web console for Kubernetes_

**Metadata**

* homepage URL: https://github.com/astefanutti/kubebox
* source URL: https://github.com/astefanutti/kubebox
* license: mit
* platforms: unix

### PR DESCRIPTION
**Pull request by blaggacao**
(also updates a bunch of other stuff : !fear!)

###### Motivation for this change
Terminal and Web console for Kubernetes
closes #92200

- Useful for prepping shell.nix in k8s projects c/o operations team.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip --against origin/master"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by blaggacao** [comment]
I did literally as told [by the docs](https://raw.githubusercontent.com/NixOS/nixpkgs/master/doc/languages-frameworks/node.section.md): 


> To add a package from NPM to nixpkgs:
>
> 1. Modify `pkgs/development/node-packages/node-packages.json` to add, update
    or remove package entries to have it included in `nodePackages` and
    `nodePackages_latest`.
> 2. Run the script: `(cd pkgs/development/node-packages && ./generate.sh)`.
> 3. Build your new package to test your changes:
    `cd /path/to/nixpkgs && nix-build -A nodePackages.<new-or-updated-package>`.
    To build against the latest stable Current Node.js version (e.g. 14.x):
    `nix-build -A nodePackages_latest.<new-or-updated-package>`
> 4. Add and commit all modified and generated files.

The external effects in `pkgs/development/node-packages/node-packages.nix` however seem scary to the freshman who did it.

**Comment by timokau** [comment]
I'm not comfortable reviewing node PRs. `git shortlog -n pkgs/development/node-packages/` suggests @Mic92 might be a better pick.

**Comment by ludovicc** [comment]
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [ ] package build on Darwin 19.05
- [ ] executables tested on Darwin
- [ ] all depending packages build

##### Possible improvements

Package failed to install on MacOS Darwin.

##### Comments

Logs from nixpkgs-review:

`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 92243"`

```
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/92243/head:refs/nixpkgs-review/1
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 17 (delta 14), reused 17 (delta 14), pack-reused 0
Unpacking objects: 100% (17/17), 41.10 KiB | 443.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
   c4264d0f3a2..67a1c36929c  master               -> refs/nixpkgs-review/0
 + 883fdec768b...c8f6307c5e5 refs/pull/92243/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /Users/lclaude/.cache/nixpkgs-review/pr-92243/nixpkgs 67a1c36929cbbca7eab50469d4689cdde9cc153d
Preparing worktree (detached HEAD 67a1c36929c)
Updating files: 100% (22032/22032), done.
HEAD is now at 67a1c36929c cargo-watch: 7.4.1 -> 7.5.0
$ git merge --no-commit c8f6307c5e56e6c7535cc51bfa604d50140c82ec
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /Users/lclaude/.cache/nixpkgs-review/pr-92243/build.nix
builder for '/nix/store/i70ffwgy44lmnfqcd8y6wqv1pfzpc8mh-racerd-unstable-2019-09-02.drv' failed with exit code 101; last 10 log lines:
     |                                                           ^^

  error: aborting due to 3 previous errors

  For more information about this error, try `rustc --explain E0061`.
  error: could not compile `rustc-ap-rustc_data_structures`.

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
builder for '/nix/store/qbw3rlpjpa2fkk5kc2j517g1hd1gjgkp-lumo-1.10.1.drv' failed with exit code 1; last 10 log lines:
  ../deps/gtest/src/gtest.cc:376:12: warning: missing field 'owner_' initializer [-Wmissing-field-initializers]
  GTEST_API_ GTEST_DEFINE_STATIC_MUTEX_(g_linked_ptr_mutex);
             ^
  ../deps/gtest/include/gtest/internal/gtest-port.h:1949:80: note: expanded from macro 'GTEST_DEFINE_STATIC_MUTEX_'
       ::testing::internal::MutexBase mutex = { PTHREAD_MUTEX_INITIALIZER, false }
                                                                                 ^
  1 warning generated.
  rm 59243553c65631185418c5a71855a7890aad3ea9.intermediate
  make: *** [Makefile:100: node] Error 2
  ....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.
builder for '/nix/store/k85c6kgfl67hvs71xypz75g4hzykbv8v-meguca-unstable-2019-03-12.drv' failed with exit code 2; last 10 log lines:
  cp node_modules/dom4/build/dom4.js node_modules/core-js/client/core.min.js node_modules/core-js/client/core.min.js.map www/js/vendor
  cp: cannot stat 'node_modules/dom4/build/dom4.js': No such file or directory
  cp: cannot stat 'node_modules/core-js/client/core.min.js': No such file or directory
  cp: cannot stat 'node_modules/core-js/client/core.min.js.map': No such file or directory
  make: *** [Makefile:42: client_vendor] Error 1
  make: *** Waiting for unfinished jobs....
  go: github.com/ErikDubbelboer/gspt@v0.0.0-20190125194910-e68493906b83: Get "https://proxy.golang.org/github.com/%21erik%21dubbelboer/gspt/@v/v0.0.0-20190125194910-e68493906b83.mod": dial tcp: lookup proxy.golang.org: no such host
  go: github.com/ErikDubbelboer/gspt@v0.0.0-20190125194910-e68493906b83: Get "https://proxy.golang.org/github.com/%21erik%21dubbelboer/gspt/@v/v0.0.0-20190125194910-e68493906b83.mod": dial tcp: lookup proxy.golang.org: no such host
  make: *** [Makefile:52: server] Error 1
  make: *** [Makefile:49: generate] Error 1
cannot build derivation '/nix/store/gqfh1dsl6idnsjyxv9v53hxkdyrfhpqf-ycmd-2020-02-22.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hz5p2a0z60dp6krpcbp1ybp6qvzlcnir-vimplugin-YouCompleteMe-2020-07-03.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rrgfx5mjyikls09pagbpv769h0wxv9jl-env.drv': 4 dependencies couldn't be built
[106 built (3 failed), 1275 copied (3234.0 MiB), 995.5 MiB DL]
error: build of '/nix/store/rrgfx5mjyikls09pagbpv769h0wxv9jl-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/92243
4 packages failed to build:
lumo meguca vimPlugins.YouCompleteMe ycmd

1 package built:
iosevka
```

**Comment by blaggacao** [comment]
@ludovicc Thanks for your review, I suspect the results you obtained obey to unintended side effects of `(cd pkgs/development/node-packages && ./generate.sh)` - which is the textbook instruction of the node docs.

I was wondering anyhow if generating such huge amount of side effects is a good thing, and this might and in a deadlock, since I've no idea how to tackle this.

Looks like @Mic92 's judgment and opinion could help resolve this.

**Comment by timokau** [comment]
@adisbladis, maybe you could take a look? (again, `git shortlog -n pkgs/development/node-packages/`)

**Comment by timokau** [comment]
Huh, I thought I had implemented an automatic transition here.
/status awaiting_reviewer

**Comment by Mic92** [comment]
I can merge after merge conflicts are resolved.

**Comment by blaggacao** [comment]
@Mic92 Just run generate again. Hope that's ok, now. I hope this huge side effects can be offloaded to a bot some day :smile_cat:

**Comment by blaggacao** [comment]
A friendly reminder, since I might not be able to do a rebase once again. It took 5 hours to download all packages...

**Comment by timokau** [comment]
I'm sorry this PR was missed.

**Comment by blaggacao** [comment]
@timokau No worries, I've read the [motion about node packages](https://discourse.nixos.org/t/call-for-nodepackages-maintainers/9176). I'm also currently no longer interested in `kubebox` since discovering `k9s`.

**Pull request closed without merging**
