### PR TITLE
warp-terminal: 0.2024.11.19.08.02.stable_01 -> 0.2024.11.19.08.02.stable_03

### PR DESCRIPTION
**Pull request by RodEsp**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by 4evy — APPROVED** [review]
Please rebase and rename the commit to `warp-terminal: 0.2024.11.19.08.02.stable_01 -> 0.2024.11.19.08.02.stable_03`

To comply with https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

other that LGTM!

**Comment by RodEsp** [comment]
Thanks @DontEatOreo!

I'll rebase in a few mins when I'm at my computer but in terms of the title, I don't see a difference between what you posted and the current title. But maybe I'm missing something?

**Comment by DontEatOreo** [comment]
The PR title is fine; you just need to rebase the commit. The commit title is the one that *really* matters

**Comment by RodEsp** [comment]
Oooh, I didn't realize the commit needed to have that format too. My bad. Will fix!

**Comment by RodEsp** [comment]
There, that should do it. Thanks again @DontEatOreo!

**Comment by RodEsp** [comment]
Btw, I noticed you've been creating PRs to update `warp` on the `master` branch, should I be doing that instead of `nixos-unstable` too?

**Comment by DontEatOreo** [comment]
Oh, I just noticed...

Please change to target master; the update will arrive at `nixos-unstable` by itself

**Comment by RodEsp** [comment]
👍🏼 thanks

Closed in favor of https://github.com/NixOS/nixpkgs/pull/359940

**Pull request closed without merging**
