### PR TITLE
python3Packages.wagtail: 5.1.3 -> 5.2.2

### PR DESCRIPTION
**Pull request by sephii**
## Description of changes

Upgrade Wagtail to 5.2.2 based on the [original nixpkgs-update PR](https://github.com/NixOS/nixpkgs/pull/266972). Note that Wagtail 5.2 bumped the requirement of `django-modelcluster` to 6.1 so this package has to be upgraded as well.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 273359` at 17eed148 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/b4c0b0939b02a95fea7f6ada94ac253c">python310Packages.wagtail-localize</a></li>
    <li><a href="https://gist.github.com/natsukium/f99096ee93cd171ae064a1b4764283ab">python311Packages.wagtail-localize</a></li>
  </ul>
</details>
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>python310Packages.django-modelcluster</li>
    <li>python310Packages.permissionedforms</li>
    <li>python310Packages.wagtail</li>
    <li>python310Packages.wagtail-factories</li>
    <li>python311Packages.django-modelcluster</li>
    <li>python311Packages.permissionedforms</li>
    <li>python311Packages.wagtail</li>
    <li>python311Packages.wagtail-factories</li>
  </ul>
</details>

**Comment by pbsds** [comment]
same issue is on hydra: https://hydra.nixos.org/build/243672281

Result of `nixpkgs-review pr 273359` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.wagtail-localize</li>
    <li>python310Packages.wagtail-localize.dist</li>
    <li>python311Packages.wagtail-localize</li>
    <li>python311Packages.wagtail-localize.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python310Packages.django-modelcluster</li>
    <li>python310Packages.django-modelcluster.dist</li>
    <li>python310Packages.permissionedforms</li>
    <li>python310Packages.permissionedforms.dist</li>
    <li>python310Packages.wagtail</li>
    <li>python310Packages.wagtail-factories</li>
    <li>python310Packages.wagtail-factories.dist</li>
    <li>python310Packages.wagtail.dist</li>
    <li>python311Packages.django-modelcluster</li>
    <li>python311Packages.django-modelcluster.dist</li>
    <li>python311Packages.permissionedforms</li>
    <li>python311Packages.permissionedforms.dist</li>
    <li>python311Packages.wagtail</li>
    <li>python311Packages.wagtail-factories</li>
    <li>python311Packages.wagtail-factories.dist</li>
    <li>python311Packages.wagtail.dist</li>
  </ul>
</details>


LGTM

**Comment by pbsds** [comment]
The x86_64-darwin error might be a regression however, since it [passes on hydra](https://hydra.nixos.org/build/244072688). @wegank, is opencv float precision issues common on darwin?

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 273359` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.wagtail-localize</li>
    <li>python310Packages.wagtail-localize.dist</li>
    <li>python311Packages.wagtail-localize</li>
    <li>python311Packages.wagtail-localize.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python310Packages.django-modelcluster</li>
    <li>python310Packages.django-modelcluster.dist</li>
    <li>python310Packages.permissionedforms</li>
    <li>python310Packages.permissionedforms.dist</li>
    <li>python310Packages.wagtail</li>
    <li>python310Packages.wagtail-factories</li>
    <li>python310Packages.wagtail-factories.dist</li>
    <li>python310Packages.wagtail.dist</li>
    <li>python311Packages.django-modelcluster</li>
    <li>python311Packages.django-modelcluster.dist</li>
    <li>python311Packages.permissionedforms</li>
    <li>python311Packages.permissionedforms.dist</li>
    <li>python311Packages.wagtail</li>
    <li>python311Packages.wagtail-factories</li>
    <li>python311Packages.wagtail-factories.dist</li>
    <li>python311Packages.wagtail.dist</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by sephii** [comment]
The problem actually comes from building `wagtail`, but it only appears when building the `wagtail-localize` package (I have no idea why). :thinking: 

[This PR](https://github.com/NixOS/nixpkgs/pull/275356) should fix the problem.

**Pull request merged**
