### PR TITLE
perlPackages.{EmailSender,FileFindObjectRule}: fix tests

### PR DESCRIPTION
**Pull request by volth**
It should fix https://github.com/NixOS/nixpkgs/pull/64157#issuecomment-510473907

@ajs124

### CODE REVIEW

**Comment by volth** [comment]
It might be wrong for cross-compilation.

The ```perl``` for shebang's should be ```buildPlatform```'s because the scripts are for the tests running on ```checkPhase```, not for the release
but as now we are exposing ```hostPlatform.perl``` for all perlPackage, it may pick ```hostPlatform.perl``` and run in tests

@matthewbauer

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by ajs124** [comment]
Looks good to me! Thanks for fixing this.

**Comment by volth** [comment]
There is also ```perlPackages.FileFindObjectRule``` which has shebang-files in ```t/sample-data```
I included the fix into this PR

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.EmailSender
@GrahamcOfBorg build perlPackages.FileFindObjectRule
@GrahamcOfBorg build hydra

**Comment by volth** [comment]
oops.
my ```buildPerlModule``` accepts ```preCheck``` but mainline nixpkgs's does not.
So I have to make another PR first

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/pull/64748

Anyway, this could be merged, it does fix ```perlPackages.EmailSender``` immediately
```perlPackages.FileFindObjectRule``` is just postponed until #64748 lands from ```staging``` to ```master```

**Comment by FRidh** [comment]
fixes https://github.com/NixOS/nixpkgs/issues/64838

**Comment by FRidh** [comment]
please squash into two commits

**Comment by volth** [comment]
@FRidh done

**Pull request merged**
