### PR TITLE
sniffglue: add missing `meta.mainProgram` value

### PR DESCRIPTION
**Pull request by xrelkd**
## Description of changes

- sniffglue: migrate to by-name
- sniffglue: add missing `mainProgram` value

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Use `hash` instead of `sha256`.

**Comment by xrelkd** [comment]
@AndersonTorres Updated, thanks for the review.

**Comment by AndersonTorres** [comment]
Squash the commits. They are too small to deserve separation.

**Comment by xrelkd** [comment]
@AndersonTorres Thanks for the review.
Is there anything that I can improve for this PR?

**Comment by AndersonTorres** [comment]
I tried to nixpkgs-review it but there is nothing...

**Comment by xrelkd** [comment]
I could use `nix build '.#sniffglue'` to build it.
```bash
$ nix build '.#sniffglue'

$ file result
result: symbolic link to /nix/store/z8vlzrjnq6k0mmc8sv12d93b36ycgvq8-sniffglue-0.16.0

$ ./result/bin/sniffglue -h
Usage: sniffglue [OPTIONS] [DEVICE]

Arguments:
  [DEVICE]  The device or file to read packets from

Options:
  -p, --promisc                   Set device to promiscuous mode
      --debugging                 Show fully dissected packets with all headers for development
  -j, --json                      Json output (unstable)
  -v, --verbose...                Increase filter sensitivity to show more (possibly less useful) packets.
                                  The default only shows few packets, this flag can be specified multiple times. (maximum: 4)
  -r, --read                      Open a pcap file instead of a device
  -n, --threads <THREADS>         Number of packet parsing threads (defaults to number of cpu cores)
      --insecure-disable-seccomp  Disable syscall filter sandbox, this flag disables security features in sniffglue, please file a bug report if you need this option
  -h, --help                      Print help
```

**Comment by teto** [comment]
there is nothing in nixpkgs-review because nothing changed from nix point of view. Worked for me.

**Pull request merged**
