### PR TITLE
lib/modules: mkRemovedOptionModule: warning instead of error

### PR DESCRIPTION
**Pull request by gebner**
###### Motivation for this change

I want my nixos configuration to work on both unstable and stable.  The option `services.dbus.socketActivated` has been removed because it is now always enabled on unstable.  I still need to set on stable because it defaults to false there.

The comment in `mkRemovedOptionModule` says it should produce a warning and not a hard error.  This PR makes it so.

cc @worldofpeace 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rycee** [comment]
The assertion seems intentionally added by @globin in b08b0bcbbec77046e5a7082177cedc12fbf1dc6c. An alternative would be to do a custom solution in `dbus.nix`?

**Comment by gebner** [comment]
I'm not sure I agree with @globin here.  There are lots of ways an updated module can break your configuration.  See for example the dbus change here which might break if you start dbus manually (as you had to before, if you had an uncommon configuration).

Is there maybe an easy way to only set an option if it is defined?  This would at least help me with my current issue.

**Comment by rycee** [comment]
See the above PR for the custom solution alternative. Dunno which one is best but I imagine @globin had a good reason for changing the behavior.

**Comment by gebner** [comment]
For reference, this is the PR introducing the hard error: #69419

There wasn't much discussion about the change.

**Comment by Infinisil** [comment]
This works to only set options if they exist:
```nix
{ options, ... }: {
  config = optionalAttrs (options ? some.option) {
    some.option = "foo";
  };
}
```

Also related, my https://github.com/NixOS/nixpkgs/pull/97023 will allow assertions to be changed to warnings or silence them completely.

**Comment by gebner** [comment]
Let's get #97023 merged then.

**Pull request closed without merging**
