### PR TITLE
zrythm: 1.0.0-alpha.28.1.3 -> 1.0.0-beta.3.4.1

### PR DESCRIPTION
**Pull request by fogti**
###### Description of changes

https://github.com/zrythm/zrythm/compare/v1.0.0-alpha.28.1.3...v1.0.0-beta.3.4.1

(in contrast to the other previous PRs, this has the `gnome` branch as base, which makes it easier to deal with as it already can rely on the latest GTK4 libraries, including libadwaita v1.2 and libpanel v1.0.alpha1, see also #182618, which should be merged before this can be merged)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage) (excluding latest revision due to lack of up-to-date binary cache and not enough time and memory...)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

#### Blockers

* [X] GTK4.8 (#190222)
* [ ] LibAdwaita 1.2
* [ ] LibPanel 1.0.alpha1
* [X] next sord release/patch to solve zix symbol clashes without static linking
* [ ] Zix (#190724)

### CODE REVIEW

**Comment by zseri** [comment]
@jtojnar @magnetophon this PR shouldn't have the disadvantages of the previous ones, it makes the dependency on bleeding-edge gnome clear, and should also be "standalone" usable in Nix flakes as separate input.

**Comment by zseri** [comment]
(now I just hope this compiles, lol)

**Comment by jtojnar** [comment]
GTK 4 picked to #190222.

**Comment by zseri** [comment]
nixpkgs-review on x86_64-linux:

1 package added:
* zix (init at 2022-09-08)

1 package updated:
* zrythm (1.0.0-alpha.28.1.3 → 1.0.0-beta.3.4.1)

(compilation in progess, 81/119)

**Comment by zseri** [comment]
Backporting this onto `master` would require:
* [ ] GTK-4.8 (#190222)
* [ ] LibAdwaita-1.2
* [ ] LibPanel-1.0.alpha*

**Comment by zseri** [comment]
ok, doesn't work.
```
zrythm-Message: 11:46:03.242: (zrythm_app_startup:955): Starting up...
zrythm-Message: 11:46:03.250: (localization_init:278): preferred lang: 'Deutsch' (de)
zrythm-Message: 11:46:03.265: (localization_init:303): setting locale to de_AT.utf8 (found de_AT.utf8)
zrythm-Message: 11:46:03.270: (plugin_settings_new:654): Plugin settings file at /home/zseri/.local/share/zrythm/plugin-settings.yaml does not exist
zrythm-Message: 11:46:03.270: (user_shortcuts_new:75): User shortcuts file at /home/zseri/.local/share/zrythm/shortcuts.yaml does not exist
zrythm-Message: 11:46:03.270: (object_utils_new:180): object_utils_new: Creating object utils...
zrythm-Message: 11:46:04.089: (create_and_load_lilv_word:191): Creating Lilv World...
Segmentation fault (core dumped)
```

**Comment by zseri** [comment]
ok, mismatching function signatures and symbol clashes explain why this happens lol...

```
[1/11] Compiling C object libsord-0.so.0.16.13.p/src_sord.c.o
FAILED: libsord-0.so.0.16.13.p/src_sord.c.o 
gcc -Ilibsord-0.so.0.16.13.p -I. -I.. -I../include -I../src -I/nix/store/fzw65wi6rx7vmq97n9dk17w3a5d8ngnc-serd-0.30.10/include/serd-0 -I/nix/store/hhnykv9sawn4g6kwi658ypwg24z8xs2b-zix-unstable-2022-09-08-dev/include/zix-0 -fvisibility=hid>
../src/sord.c: In function 'sord_node_hash':
../src/sord.c:156:26: warning: implicit declaration of function 'zix_digest_start' [-Wimplicit-function-declaration]
  156 |   uint32_t        hash = zix_digest_start();
      |                          ^~~~~~~~~~~~~~~~
../src/sord.c:157:10: warning: implicit declaration of function 'zix_digest_add' [-Wimplicit-function-declaration]
  157 |   hash = zix_digest_add(hash, node->node.buf, node->node.n_bytes);
      |          ^~~~~~~~~~~~~~
../src/sord.c: In function 'sord_world_new':
../src/sord.c:204:18: warning: passing argument 1 of 'zix_hash_new' from incompatible pointer type [-Wincompatible-pointer-types]
  204 |     zix_hash_new(sord_node_hash, sord_node_hash_equal, sizeof(SordNode));
      |                  ^~~~~~~~~~~~~~
      |                  |
      |                  uint32_t (*)(const void *) {aka unsigned int (*)(const void *)}
In file included from ../src/sord.c:12:
/nix/store/hhnykv9sawn4g6kwi658ypwg24z8xs2b-zix-unstable-2022-09-08-dev/include/zix-0/zix/hash.h:124:42: note: expected 'ZixAllocator *' {aka 'struct ZixAllocatorImpl *'} but argument is of type 'uint32_t (*)(const void *)' {aka 'unsigned>
  124 | zix_hash_new(ZixAllocator* ZIX_NULLABLE  allocator,
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../src/sord.c:204:34: warning: passing argument 2 of 'zix_hash_new' from incompatible pointer type [-Wincompatible-pointer-types]
  204 |     zix_hash_new(sord_node_hash, sord_node_hash_equal, sizeof(SordNode));
      |                                  ^~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  _Bool (*)(const void *, const void *)
In file included from ../src/sord.c:12:
/nix/store/hhnykv9sawn4g6kwi658ypwg24z8xs2b-zix-unstable-2022-09-08-dev/include/zix-0/zix/hash.h:125:42: note: expected 'ZixKeyFunc' {aka 'const void * (*)(const void *)'} but argument is of type '_Bool (*)(const void *, const void *)'
  125 |              ZixKeyFunc ZIX_NONNULL      key_func,
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../src/sord.c:204:56: warning: passing argument 3 of 'zix_hash_new' makes pointer from integer without a cast [-Wint-conversion]
  204 |     zix_hash_new(sord_node_hash, sord_node_hash_equal, sizeof(SordNode));
      |                                                        ^~~~~~~~~~~~~~~~
      |                                                        |
      |                                                        long unsigned int
In file included from ../src/sord.c:12:
/nix/store/hhnykv9sawn4g6kwi658ypwg24z8xs2b-zix-unstable-2022-09-08-dev/include/zix-0/zix/hash.h:126:42: note: expected 'ZixHashFunc' {aka 'long unsigned int (*)(const void *)'} but argument is of type 'long unsigned int'
  126 |              ZixHashFunc ZIX_NONNULL     hash_func,
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../src/sord.c:204:5: error: too few arguments to function 'zix_hash_new'
  204 |     zix_hash_new(sord_node_hash, sord_node_hash_equal, sizeof(SordNode));
      |     ^~~~~~~~~~~~
In file included from ../src/sord.c:12:
/nix/store/hhnykv9sawn4g6kwi658ypwg24z8xs2b-zix-unstable-2022-09-08-dev/include/zix-0/zix/hash.h:124:1: note: declared here
  124 | zix_hash_new(ZixAllocator* ZIX_NULLABLE  allocator,
      | ^~~~~~~~~~~~
../src/sord.c: In function 'sord_world_free':
../src/sord.c:222:3: warning: implicit declaration of function 'zix_hash_foreach'; did you mean 'zix_hash_free'? [-Wimplicit-function-declaration]
  222 |   zix_hash_foreach(world->nodes, free_node_entry, world);
      |   ^~~~~~~~~~~~~~~~
      |   zix_hash_free
../src/sord.c: In function 'sord_iter_forward':
../src/sord.c:350:38: error: incompatible type for argument 1 of 'zix_btree_iter_is_end'
  350 |     return zix_btree_iter_is_end(iter->cur);
      |                                  ~~~~^~~~~
      |                                      |
      |                                      ZixBTreeIter *
In file included from ../src/sord.c:10:
/nix/store/hhnykv9sawn4g6kwi658ypwg24z8xs2b-zix-unstable-2022-09-08-dev/include/zix-0/zix/btree.h:189:42: note: expected 'ZixBTreeIter' but argument is of type 'ZixBTreeIter *'
  189 | zix_btree_iter_is_end(const ZixBTreeIter i)
      |                       ~~~~~~~~~~~~~~~~~~~^
../src/sord.c:353:58: error: incompatible type for argument 1 of 'zix_btree_get'
  353 |   SordNode**     key     = (SordNode**)zix_btree_get(iter->cur);
      |                                                      ~~~~^~~~~
      |                                                          |
      |                                                          ZixBTreeIter *
```

**Comment by magnetophon** [comment]
Thanks for this PR.
I've taken myself off the reviewers list since it is still WIP, IIUC.
Would you mind adding me back once everything is working?

> Should I put the sord bump into a separate PR?

I'd say yes.

**Pull request closed without merging**
