### PR TITLE
qcoro: 0.6.0 -> 0.7.0

### PR DESCRIPTION
**Pull request by Cynerd**
###### Description of changes
https://github.com/danvratil/qcoro/releases/tag/v0.7.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Smittyvb** [comment]
Result of `nixpkgs-review pr 202367` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>libsForQt5.qcoro</li>
  </ul>
</details>

**Review by syvb — APPROVED** [review]

**Comment by risicle** [comment]
Why staging? This makes it quite painful to review.

**Comment by Cynerd** [comment]
> Why staging? This makes it quite painful to review.

You probably mean why it was based directly on staging and not on a common base with a master. Honestly, my fault. Forgot to rebase it before submitting it. Should I rebase it now?

**Comment by risicle** [comment]
Why staging at all? <100 rebuilds is not a lot.

**Comment by Smittyvb** [comment]
Result of `nixpkgs-review pr 202367` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.neochat</li>
    <li>libsForQt512.spacebar</li>
    <li>libsForQt514.neochat</li>
    <li>libsForQt514.spacebar</li>
    <li>matrique</li>
    <li>neochat</li>
    <li>spectral</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>libsForQt512.qcoro</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>libsForQt5.neochat</li>
    <li>libsForQt5.qcoro</li>
    <li>libsForQt5.spacebar</li>
    <li>libsForQt514.qcoro</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
> Result of `nixpkgs-review pr 202367` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 7 packages marked as broken and skipped:
> 1 package failed to build:
> 4 packages built:

Qt 5.12 and 5.14 will be removed soon (#201765), so LGTM.

**Review by thiagokokada — APPROVED** [review]

**Review by syvb — APPROVED** [review]

**Pull request merged**
