### PR TITLE
luaPackages.luafilesystem: 1.7.0 -> 1.8.0

### PR DESCRIPTION
**Pull request by s-ol**
###### Description of changes

From [offical changelog](http://lunarmodules.github.io/luafilesystem/#history):

> Version 1.8.0 [22/Apr/2020]
>
>* Lua 5.4 support
>* lfs.link and lfs.symlinkattributes now work on Windows
>* MACOSX_DEPLOYMENT_TARGET is configurable in the Makefile
>* Fallback to _POSIX_PATH_MAX when MAXPATHLEN is not avaliable
>* Fixed memory leak in case of realloc failure

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

The second commit is as generated by `./maintainers/scripts/update-luarocks-packages`, but it changes a bunch of package URLs and hashes that I cannot verify make sense. I'm providing it here for the sake of testing, but would prefer either:

-  removing that commit and having a maintainer of the Lua subsystem do a proper bump
- manually commiting only the changes regarding the `luafilesystem` package, where I can vouch for the integrity of the package

### CODE REVIEW

**Comment by s-ol** [comment]
pinging maintainer @flosse and @teto

**Comment by teto** [comment]
thanks. Could you drop the unrelated changes please ? The urls changing is a "bug" of the updater script, but I dont have time to fix it (https://github.com/nix-community/luarocks-nix/ if you want to have a look). Post a nixpkgs-review and we should be good

**Comment by teto** [comment]
so I just noticed that many people are pinged by ofborg for the MR, I am not sure how. I have created a lua entry in maintainers/team-list.nix that references the github lua team so that may be why. Sorry for the unsollicited ping if that's due to my action. Not sure about the mechanism but if confirmed I can fix the issue.

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 197701` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>d-seams</li>
    <li>wordgrinder</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>awesome</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.cassowary</li>
    <li>lua51Packages.cldr</li>
    <li>lua51Packages.fluent</li>
    <li>lua51Packages.ldoc</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luafilesystem</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.penlight</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.cassowary (lua52Packages.cassowary)</li>
    <li>luaPackages.cldr (lua52Packages.cldr)</li>
    <li>luaPackages.fluent (lua52Packages.fluent)</li>
    <li>luaPackages.ldoc (lua52Packages.ldoc)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luafilesystem (lua52Packages.luafilesystem)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.penlight (lua52Packages.penlight)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.cassowary</li>
    <li>lua53Packages.cldr</li>
    <li>lua53Packages.fluent</li>
    <li>lua53Packages.ldoc</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luafilesystem</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.penlight</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.vusted</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.cassowary</li>
    <li>luajitPackages.cldr</li>
    <li>luajitPackages.fluent</li>
    <li>luajitPackages.ldoc</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luafilesystem</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.penlight</li>
    <li>luajitPackages.tl</li>
    <li>luajitPackages.vusted</li>
    <li>luakit</li>
    <li>mudlet</li>
    <li>nvimpager</li>
    <li>prosody</li>
    <li>rehex</li>
    <li>sile</li>
    <li>z-lua</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]
both failing packages are already failing on hydra

**Pull request merged**
