### PR TITLE
ansi-wl-pprint hash correction

### PR DESCRIPTION
**Pull request by sheganinans**
This ansi-wl-pprint bug just keeps biting us! Thanks guys!

### CODE REVIEW

**Comment by sheganinans** [comment]
fails because gcc is missing. works on my machine. anyone else?

**Comment by MP2E** [comment]
Yet another spurious Travis error, this patch looks good to me. :+1: Will merge in soon

**Comment by sheganinans** [comment]
closed?

**Comment by MP2E** [comment]
Yes. Commit was pushed to master

https://github.com/NixOS/nixpkgs/commit/3c7a9194317aa68e64baaab78dd6fb3ff4309495

**Comment by sheganinans** [comment]
Interesting, never seen it done that way! Thanks!

**Pull request closed without merging**
