### PR TITLE
wasilibc: 20190712 -> 20200319

### PR DESCRIPTION
**Pull request by ggreif**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build wasilibc

**Comment by ggreif** [comment]
Looks like `lld` wants some inner structure in the `sysroot`:
```
$ clang-10 --target=wasm32-wasi --sysroot /nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227 fak.c -v -isystem /nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227/include
clang version 10.0.0 
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: /nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/bin
 "/nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/bin/clang-10" -cc1 -triple wasm32-unknown-wasi -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name fak.c -mrelocation-model static -mthread-model posix -mframe-pointer=none -fno-rounding-math -masm-verbose -mconstructor-aliases -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -target-linker-version 450.3 -v -nostdsysteminc -resource-dir /nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/lib/clang/10.0.0 -isystem /nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227/include -isysroot /nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227 -internal-isystem /nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/lib/clang/10.0.0/include -fdebug-compilation-dir /Users/ggreif/motoko -ferror-limit 19 -fmessage-length 185 -fgnuc-version=4.2.1 -fobjc-runtime=gnustep -fno-common -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/39/lr50t0q96tx5qp0mzht34r240000gn/T/fak-9d6bb9.o -x c fak.c
clang -cc1 version 10.0.0 based upon LLVM 10.0.0git default target x86_64-apple-darwin17.7.0
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227/include
 /nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/lib/clang/10.0.0/include
End of search list.
 "/nix/store/qr74zlgry31w5zxp2jm5wrbcxy5rpc8a-lld-10.0.0rc2/bin/wasm-ld" -L/nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227/lib/wasm32-wasi crt1.o /var/folders/39/lr50t0q96tx5qp0mzht34r240000gn/T/fak-9d6bb9.o -lc /nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/lib/clang/10.0.0/lib/wasi/libclang_rt.builtins-wasm32.a -o a.out
wasm-ld: error: cannot open crt1.o: No such file or directory
wasm-ld: error: unable to find library -lc
wasm-ld: error: cannot open /nix/store/ia3qwhkiw45b50j2ggbv1dvjhpai6rs8-clang-10.0.0rc2/lib/clang/10.0.0/lib/wasi/libclang_rt.builtins-wasm32.a: No such file or directory
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```
But `/nix/store/d12iz24a4nk7qwagph4w8fl741yjpnyr-wasilibc-20200227/lib/wasm32-wasi` is empty!

**Comment by siraben** [comment]
Any updates on this?

**Comment by wegank** [comment]
Closed by #168516.

**Pull request closed without merging**
