### PR TITLE
GHC 8.6 fixes and bound relaxation

### PR DESCRIPTION
**Pull request by endgame**
###### Motivation for this change

A haskell project I am working on cannot enter a nix-shell from nixpkgs master. This fixes some of the problems. Some problems are due to ghc 8.6 (e.g., the MonadFail fixes for beam) but some are due to version bounds that have become too tight.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
@GrahamcOfBorg build haskell.packages.ghc844.beam-core

**Comment by endgame** [comment]
@domenkozar I've re-pushed with fixed line endings in the patch files. Can you please ask ofborg to rebuild?

(GHC 8.4.4 will fail because the fix that adds `contravariant` to `aeson`'s deps hasn't landed yet. See #53748)

**Review by peti — CHANGES_REQUESTED** [review]
Can you please report those issues upstream and add the appropriate ticket URLs into the source code next to the override?

**Review by peti — CHANGES_REQUESTED** [review]
Oh, I spoke too early. I now noticed that most patches *have* an upstream ticket URL -- only the one for `servant-docs` didn't. So never mind my previous comment.

However, could you please download the patches you've submitted in PRs from github rather than checking them into the Nixpkgs repository?

**Comment by endgame** [comment]
@peti Thanks for the review. I never filed an upstream bug for `servant-docs`, since phadej, who is maintainer of tdigest and servant, doesn't push new versions or metadata revisions just to fix test depends. See https://github.com/phadej/tdigest/issues/30 . I can add an "until servant-0.whatever is released" comment instead?

As for the beam patches, I think I can make that work. I'll need to fiddle patchFlags, though.

**Comment by peti** [comment]
> I can add an "until servant-0.whatever is released" comment instead?

Yes, that would be nice!

**Comment by endgame** [comment]
@peti I have pushed a new branch with a new comment for servant-docs. I do not have time to re-do the patch files (which I had to assemble from a couple of places which I can't find right now). Is that a blocker for the merge?

**Comment by peti** [comment]
> Is that a blocker for the merge?

No, it's okay. Thank you very much for your efforts. I'll merge these changes into `haskell-updates` first. Then they'll go to `master` once the test builds have succeeded.

**Pull request merged**
