### PR TITLE
Add volume and cd events to acpid configuration

### PR DESCRIPTION
**Pull request by k0ral**
**Warning**: untested change.

### CODE REVIEW

**Comment by globin** [comment]
Thanks :+1:

**Comment by edolstra** [comment]
Hm, this seems extremely specific to me. I mean, why do we have options for these specific keys but not the ~100 other keys? Also, isn't acpid kind of deprecated? Having things happen when keys are pressed seems more like a job for the desktop environment.

**Comment by k0ral** [comment]
For power management, `acpid` can indeed be replaced with `systemd-logind`, but not for some other events (like audio ones), as far as I know.
Delegating this feature to the desktop environment (e.g. with `xbindkeys`) means that headless configurations won't benefit from it, and that sounds unacceptable to me.

Yes, there are many other events handled by `acpid` and not included in this pull request. Yet I believe this change can be useful to many users. The original module was very incomplete, it is now less incomplete, isn't that a good thing ? :)

**Comment by edolstra** [comment]
No, I don't think we should be duplicating every acpid option in the NixOS module system. It would be better to have a single generic option like:
```
services.acpid.events.volume-up = "...shell code...";
```

**Comment by k0ral** [comment]
I see your point. I'll implement it and provide another pull request.

**Pull request merged**
