### PR TITLE
vimPlugins: remove ensime-vim (404)

### PR DESCRIPTION
**Pull request by bandithedoge**

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 150823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.vim-clap</li>
  </ul>
</details>
<details>
  <summary>84 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.ctrlp-vim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.falcon</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.nlua-nvim</li>
    <li>vimPlugins.nui-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lsp-ts-utils</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-context-commentstring</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.package-info-nvim</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.ranger-vim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-coc-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.todo-comments-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-argwrap</li>
    <li>vimPlugins.vim-devicons</li>
    <li>vimPlugins.vim-dispatch</li>
    <li>vimPlugins.vim-helm</li>
    <li>vimPlugins.vim-indexed-search</li>
    <li>vimPlugins.vim-move</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-sleuth</li>
    <li>vimPlugins.vim-startuptime</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by bandithedoge** [comment]
> Result of `nixpkgs-review pr 150823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> 84 packages built:

Works fine for me on x86_64-linux and x86_64-darwin

**Comment by Kranzes** [comment]
> Works fine for me on x86_64-linux and x86_64-darwin
Please run nixpkgs-review with ` --post-result`.

**Comment by bandithedoge** [comment]
Result of `nixpkgs-review pr 150823` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.vim-clap</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
  </ul>
</details>

**Comment by teto** [comment]
any idea what happened to the plugin ?

**Comment by bandithedoge** [comment]
@teto For whatever reason it was removed from GitHub and breaks the update script.

**Pull request merged**
