### PR TITLE
dotnet: package coreclr (from git)

### PR DESCRIPTION
**Pull request by obadz**
cc @lethalman

### CODE REVIEW

**Comment by lethalman** [comment]
What's this coreclr? Is that an alternative mono?

**Comment by obadz** [comment]
Yes, it's the stuff Microsoft has opensourced. The managed libraries can't be built on Linux yet but the runtime itself builds.

**Comment by lethalman** [comment]
Fails to build:
```
Invoking cmake with arguments: "/tmp/nix-build-coreclr-git-8c70800b5e.drv-0/coreclr-8c70800b5e8dc5535c379dec4a6fb32f7ab5e878-src" DEBUG
./build.sh: /tmp/nix-build-coreclr-git-8c70800b5e.drv-0/coreclr-8c70800b5e8dc5535c379dec4a6fb32f7ab5e878-src/src/pal/tools/gen-buildsys-clang.sh: /usr/bin/env: bad interpreter: No such file or directory
Failed to generate native component build project!
builder for ‘/nix/store/yc6khiy7xq6n1as2xb2z3n3gv78n9vyh-coreclr-git-8c70800b5e.drv’ failed with exit code 1
```

You are not using chroot builds?

**Comment by obadz** [comment]
Not sure, it worked doing nix-build -A coreclr for me

**Comment by lethalman** [comment]
@obadz if you aren't sure then you didn't enable chroot builds. If you use nixos, it's easy.

**Comment by obadz** [comment]
Is that all I need to do?

```nix-build --option build-use-chroot true -A coreclr```

**Comment by lethalman** [comment]
@obadz http://nixos.org/nixos/manual/ch-options.html#opt-nix.useChroot

**Comment by obadz** [comment]
Done, give it another try pls.

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
