### PR TITLE
libsignal-ffi: 0.36.1 -> 0.39.2, mautrix-signal: unstable-2023-12-30 -> unstable-2024-01-30

### PR DESCRIPTION
**Pull request by Ma27**
## Description of changes

See the commit messages for more details.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by priegger** [comment]
Installed it some days ago using the module from #277368. After that relaying was broken and I had to trigger a login to signal again (connect the matrix bot to the phone app). I guess this has do be done for some updates and is not unusual.

Everything seems to work (did minor testing for a minute only). I'm running it on a virtual aarch64 server.

With the previous version I had issues forwarding images with text from matrix to signal (text was not forwarded). This seems to be fixed in this version.

Thanks for the update pr @Ma27!

**Comment by Ma27** [comment]
> After that relaying was broken and I had to trigger a login to signal again (connect the matrix bot to the phone app).

Oh, so I'm not the only one who had this issue :sweat_smile: 
That was originally why I started the update, but then I realized that it didn't fix the issue, but since I had it working correctly, I decided to PR it anyways.

**Comment by priegger** [comment]
> > After that relaying was broken and I had to trigger a login to signal again (connect the matrix bot to the phone app).
> 
> Oh, so I'm not the only one who had this issue 😅 That was originally why I started the update, but then I realized that it didn't fix the issue, but since I had it working correctly, I decided to PR it anyways.

I guess it can be expected, since it's pre-release (the Go version of the bridge). If you want to have the pre-release in nixpkgs is not a question to ask since it's already there. If you want to upgrade it though (in case upgrades require the user to re-link and it was no something different going on there)... :shrug: 

I'll stay with this version since it seems to work better for me and the previous version does not like the updated database schema.

Thanks again. :+1:

**Review by niklaskorz — APPROVED** [review]
Works without issues here, thanks! I did not have to reconnect to Signal after the upgrade, it continued operating as before.

**Comment by Ma27** [comment]
> I guess it can be expected, since it's pre-release (the Go version of the bridge). If you want to have the pre-release in nixpkgs is not a question to ask since it's already there. If you want to upgrade it though (in case upgrades require the user to re-link and it was no something different going on there)... 🤷

I'm not sure what you want to tell me here, but I my original assumption was that something's off in _my_ setup and not that this is a general issue with everybody using the package.

Anyways, there are two more approvals (including one from the other maintainer), so I'll go ahead and merge.

**Pull request merged**
