### PR TITLE
pdftk: 3.0.8 -> 3.2.1

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

I did some basic testing by merging two PDFs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105458` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gscan2pdf</li>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>pdftk</li>
  </ul>
</details>

**Comment by 7c6f434c** [comment]
@SuperSandro2000 Any idea if anything can be built on macOS using this version of `gradle`?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Any idea if anything can be built on macOS using this version of `gradle`?

I build something with gradle today which resulted in an hash mismatch.

https://github.com/NixOS/nixpkgs/pull/105590#issuecomment-736693889

**Comment by primeos** [comment]
@SuperSandro2000 in that case it could also work due to [this](https://github.com/NixOS/nixpkgs/pull/105590/files#diff-6055d07eece505268ab5fe931a712118d8bc4ef8de2d484d624ea371a26761c4R54). Anyway, feel free to investigate/fix or ping `@NixOS/darwin-maintainers` (but for `pdftk` it's probably not that important anyway).

**Comment by SuperSandro2000** [comment]
Yeah could be. I probably do not have time for that. I just mark the package broken on darwin for now.

**Pull request merged**
