### PR TITLE
python3X: backport all old releases

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Did not include 3.9 because that would be a mass-rebuild. Let's see whether this is is as well.

**Comment by mweinelt** [comment]
There was one breaking change in these updates, but I don't exactly remember what it was. Was the original reason I stopped backporting them.

Guess i'll have to dig into it.

**Comment by FRidh** [comment]
I think the high amount of rebuilds is via qtwebkit which is using python38.

**Comment by mweinelt** [comment]
Not because we recurse into python310Packages?

**Comment by vcunat** [comment]
So, this is waiting for something?  Or you want it into `staging-22.05`?

**Comment by mweinelt** [comment]
I think staging-22.05 would be the better choice, because I don't see how we would get around the huge rebuild count. Also I'm unsure about breakages, but we'll have to see I guess.

**Comment by vcunat** [comment]
OK.  Should I wait for python 3.9 before starting the `*-linux` rebuilds?

**Comment by mweinelt** [comment]
> There was one breaking change in these updates, but I don't exactly remember what it was. Was the original reason I stopped backporting them.
> 
> Guess i'll have to dig into it.

I think that comment was related to python39 updates, but I missed that there weren't any in this PR. We can try to backport them, sure.

**Pull request merged**
