### PR TITLE
haskell: configuration-common.nix -> overrides.nix

### PR DESCRIPTION
**Pull request by teto**
follow up of https://github.com/NixOS/nixpkgs/issues/121140#issuecomment-843640502 

configuration-common.nix is unclear, prefer to use a similar scheme as
pkgs/misc/vim-plugins/overrides.nix and pkgs/development/lua-modules/overrides.nix ?
for consistency.

I think we could remove initial-packages.nix that is just a redirection towards haskell-packages.nix (why is it there in the first place ?).

I would also like some opinions on renaming hackage-packages.nix . The filename is informational but vimPlugins and lua use `generated` as part of the filename which I like too (it's easy to skip the header at the top of hackages-packages.nix saying it's generated) but:
-  `hackage-generated.nix` could contain just the revision/date of hackage we used
-  `generated-packages.nix` loses the notion of hackage but do we care ?
-  `hackage-generated-packages.nix` is long but it contains everything

###### Motivation for this change
harmonize filenames across language ecosystems

cc @cdepillabout 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
I have a weak argument against this:
When you wanna find all overrides and config entries concerning a package and you `grep <package-name>` your results will be garbled by the hackage-packages file where packages are mentioned very often. But when you use `grep <package-name> configuration-*` you search through all relevant files. These renames would drop this invariant.

Also, if we rename configuration-common we also need a consistent new name for all other configuration-*.nix files.

To be honest, I am not sold on the harmonizing filenames between language package sets. I would be onboard if the renaming is obviously more explicit and intuitive. Putting something like "generated" in the hackage-packages.nix filename sounds smart.

**Comment by teto** [comment]
interesting feedback, do results outside configuration-common matter that much ? (I guess you are interested in configuration-hackage2nix). You could filter hackage-packages.nix out or we could move the file so it isn't taken into account into the grep.
"configuration-overrides.nix" would work too but I find the "configuration" prefix meaningless. These files are not really `config` as I see it (else the whole nixpkgs is),  except maybe for the yaml files.

For more context, maybe it's not something to be tackled on at the haskell level but at the nixpkgs level but when I started out nix I felt like everytime I had to work with the new language in nix I had to start from scratch (I starterd out with the python set and the haskell one works very differently). Maybe the haskell convention should be adopted by others instead of what I am doing here but I liked the "overrides.nix" / "generated.nix" approach better.

**Comment by sternenseemann** [comment]
I also am sceptical. I can sympathize with the idea, but I'm not convinced that moving files around is worth it. Renaming it to overrides arguably makes the situation worse as all `configuration-*` files contain overrides and not all of them belong in `configuration-common.nix`.

Also this would break the little documentation we have at the moment for no real gain. Every language ecosystem is domain specific and will require some getting used to and I think improving our documentation will help that more than renaming files.

I'm still open to renaming `configuration-common.nix` at some point, since the disambiguation from `configuration-nix.nix` could be better tbh. I'd propose holding up on cosmetic changes though until we have the documentation properly in the manual again and a plan how to deal with the resulting outdated youtube tutorials we'd have (currently they are the main documentation on unbreaking haskell packages as far as I am aware).

**Comment by sternenseemann** [comment]
> interesting feedback, do results outside configuration-common matter that much ?

We additional have:

* Platform-specific overrides: `configuration-arm.nix` (in the future probably `configuration-darwin.nix` as well)
* Compiler-specific overrides: `configuration-ghc*`
* Eternal overrides which make packages and nix behave well together: `configuration-nix.nix`
* Day-to-day fixes: `configuration-common.nix`

The latter is touched the most, but not the only important one of those, splitting them up does arguably make the whole affair more maintainable.

**Comment by teto** [comment]
what about changing `configuration` to `overrides` then , e.g., `overrides-common.nix` ? I wouldn't say it's purely cosmetic since the goal is to help onboard new users (I wont argue for hackage-packages.nix since i know it requires heavier frefactoring). And because the documentation is being written maybe on the contrary now is a good time to rename things ? Especially if big changes are on the roadmap ? I have no idea, but I imagine there could be plans to  hackage-packages.nix per ghc version or broken overrides at least, which could justify a new folder hierarchy etc.

As per the videos, you probably refer to https://www.youtube.com/watch?v=KLhkAEk8I20, 1200 views is impressive but maybe it's already outdated since the update hackage process changed in the last few weeks already. I wouldn't let these slow down changes as in practice few users update the haskell ecosystem because it's so bothersome. I would venture it's mostly by the fantastic four in the linked thread ;)

**Comment by teto** [comment]
I suppose this has to wait for the nixpkgs architecture team to edict some rules.

**Pull request closed without merging**
