### PR TITLE
orchis-theme: 2021-06-25 -> 2021-12-13

### PR DESCRIPTION
**Pull request by fufexan**
###### Motivation for this change

Package update. Now the theme includes all variants.
Added new `tweaks` flag for customisation.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by romildo — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@fufexan eval failure

**Comment by fufexan** [comment]
> @fufexan eval failure

I know, but I'm not sure how to fix it.

**Review by romildo — CHANGES_REQUESTED** [review]
Please, fix the assert.

**Comment by romildo** [comment]
_It seems my comment in the my review somehow disappeared._

In your assert, the check is wrong. You are checking if there is any valid tweak in the tweaks list:
```nix
assert lib.assertMsg (builtins.any (x: builtins.elem x tweaks) [ "solid" "compact" "black" "primary" ])
  "You entered a wrong tweak! Valid tweaks are: solid, compact, black, primary.";
```

What you need to do is check if all tweaks in the tweaks list are a valid tweaks. Something like:
```nix
assert lib.assertMsg (builtins.all (x: builtins.elem x [ "solid" "compact" "black" "primary" ]) tweaks)
  "You entered a wrong tweak! Valid tweaks are: solid, compact, black, primary.";
```

Or even with the following assert, which is more precises:
```nix
let
  validTweaks = [ "solid" "compact" "black" "primary" ];
  unknownTweaks = lib.subtractLists validTweaks tweaks;
in
assert lib.assertMsg (unknownTweaks == []) ''
  You entered wrong tweaks: ${toString unknownTweaks}
  Valid tweaks are: ${toString validTweaks}
  '';
```

**Comment by fufexan** [comment]
@romildo oh, that's very helpful! Thanks!

**Review by romildo — APPROVED** [review]
LGTM

**Pull request merged**
