### PR TITLE
materialize: 0.8.1 -> 0.8.3

### PR DESCRIPTION
**Pull request by petrosagg**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
I'm testing this right now.
There seems to be 2 more versions released, any reason you choose this update rather than 0.9.1 ?
https://materialize.com/docs/release-notes/#v0.#.#

**Comment by petrosagg** [comment]
Subsequent versions require rust 1.54. I'm going to update the package as soon as 1.54 lands on master

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 136452` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>materialize</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Thank you for the PR!
Feel free to ping me on the next update, I should be able to test rapidly.

**Comment by petrosagg** [comment]
@happysalada amazing! thanks so much for the review!

**Pull request merged**
