### PR TITLE
onlyoffice-documentserver: 7.2.2 -> 7.3.0

### PR DESCRIPTION
**Pull request by onny**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Tested it locally with nixos-shell and seems to work fine :)

```
{ pkgs, ... }: {

  virtualisation.memorySize = 6000;

  networking.extraHosts = ''
    127.0.0.1 office.localhost
  '';

  services.nextcloud = {
    enable = true;
    package = pkgs.nextcloud25;
    hostName = "localhost";
    config.adminpassFile = "${pkgs.writeText "adminpass" "hunter2"}";
    extraApps = with pkgs.nextcloud25Packages.apps; {
      inherit onlyoffice;
    };
    extraAppsEnable = true;
  };
  services.nginx.virtualHosts."localhost".listen = [ { addr = "127.0.0.1"; port = 8080; } ];

  services.onlyoffice = {
    enable = true;
    hostname = "office.localhost";
  };
  services.nginx.virtualHosts."office.localhost".listen = [ { addr = "127.0.0.1"; port = 8081; } ];

  services.caddy = {
    enable = true;
    virtualHosts = {
      "http://office.localhost".extraConfig = ''
        reverse_proxy http://127.0.0.1:8000 {
          # Required to circumvent bug of Onlyoffice loading mixed non-https content
          header_up X-Forwarded-Proto http
        }
      '';
      "http://localhost".extraConfig = ''
        reverse_proxy http://127.0.0.1:8080
      '';
    };
  };

}
```

image

**Review by wegank — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Ideally we should test this with nginx and to double check if we need to update the headers in the nixos module.

**Comment by bbenno** [comment]
Hi, any plans to officially back port this update to 22.11? I do not spot any breaking changes in the [changelog](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#730).
Furthermore, I just tested v7.3.0 with Nginx reverse proxy: Works for me.

Used config

```
  services = {
    onlyoffice = {
      enable = true;
      hostname = "onlyoffice.<...>.de";
      jwtSecretFile = "<...>";
    };
    nginx.virtualHosts.${config.services.onlyoffice.hostname} = {
      forceSSL = true;
      enableACME = true;
    };
  };
```

**Comment by onny** [comment]
Thank you for testing! I'll go and add a backport label

**Comment by bbenno** [comment]
sry i have to correct myself. there is "something". I am still inspecting it. Sorry for it

**Comment by bbenno** [comment]
BUT I had some other issues:

1) mode bits of `/var/www/onlyoffice/documentserver` are 700, with ownership `onlyoffice:onlyoffice`. This causes an error in my onlyoffice-docservice.service: 
```
onlyoffice-wrapper: [ERROR] [localhost] [docId] [userId] nodeJS - healthCheck error Error: EACCES: permission denied, mkdir '/var/lib/onlyoffice/documentserver/App_Data/cache/files/data'
```
Manual fix: `sudo chmod +x /var/lib/onlyoffice/documentserver`
The folder is created with mentioned permissions (`umask 077`) [here](https://github.com/NixOS/nixpkgs/blob/fab09085df1b60d6a0870c8a89ce26d5a4a708c2/nixos/modules/services/web-apps/onlyoffice.nix#L227-L228).
This issue might have been present even before this update.
Should we alter the prestart script? (I still have not understood in detail why nginx throws an error while caddy seems to work with these permissions.)

2) `onlyoffice-docservice.service` tries to run `/var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t` causing SIGILL due to ONLYOFFICE being located under `/var/lib/` rather than `/var/www/`.

<details><summary>systemd log</summary>

```
 [2023-02-10T11:01:17.566] [ERROR] [localhost] [247610318] [<user>] nodeJS - error spawnAsync Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGILL
     at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:40:23)
     at Object.onceWrapper (events.js:520:26)
     at ChildProcess.emit (events.js:400:28)
     at maybeClose (internal/child_process.js:1088:16)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
     ...
     at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
     at spawnProcess (/snapshot/server/build/server/FileConverter/sources/converter.js)
     at spawnProcess.next (<anonymous>)
     at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
     at ExecuteTask.next (<anonymous>)
     at /snapshot/server/build/server/FileConverter/sources/converter.js
     at Generator.next (<anonymous>)
     at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
 [2023-02-10T11:01:17.567] [ERROR] [localhost] [247610318] [<user>] nodeJS - stdout:
 [2023-02-10T11:01:17.567] [ERROR] [localhost] [247610318] [<user>] nodeJS - stderr:TypeError: Cannot read property 'length' of undefined
     at Object.d.AscCommon.QS.decode.d.AscCommon.QS.decode (<anonymous>:13048:267)
     at r (<anonymous>:12955:20)
     at C.Bq (<anonymous>:12976:452)
     at Object.Bq (<anonymous>:12981:234)
     at Ub.kAd (<anonymous>:10736:45)
     at Ub.kAd (<anonymous>:11025:221)
     at <anonymous>:10677:440
     at ra (<anonymous>:10000:311)
     at Object.H.AscCommon.FSh (<anonymous>:10182:357)
     at Ub.j5 (<anonymous>:10677:401)
 Uncaught TypeError: Cannot read property 'length' of undefined
 #
 # Fatal error in v8::ToLocalChecked
 # Empty MaybeLocal.
 #
 [2023-02-10T11:01:17.567] [ERROR] [localhost] [247610318] [<user>] nodeJS - ExitCode (code=0;signal=SIGILL;error:-80)
```
</details>

I did not find the time yet to investigate further.

**Comment by onny** [comment]
@bbenno Thank you for noticing these issues. We'll have to fix this in an other pull request. I might have a look into it

**Comment by SuperSandro2000** [comment]
Please don't backport any documentserver updates. The package is rather picky and I don't want to have to deal with problems on stable.

**Comment by bbenno** [comment]
> @bbenno Thank you for noticing these issues. We'll have to fix this in an other pull request. I might have a look into it

Sure, and thanks. I would like to support you in any manner. Btw. what are your thoughts about opening issues and document the errors there?

**Comment by SuperSandro2000** [comment]
I am not monitoring issues and usually would not open one in nixpkgs. If you open an issue and want that I see it, then you need to ping me.

Most errors I have seen so far are rooted that upstream assumes to run in their docker container, has usually very bad error handling especially around missing headers and that we cannot elfpatch the binaries.

**Pull request merged**
