### PR TITLE
citrix-workspace: clean up URLs

### PR DESCRIPTION
**Pull request by obadz**
###### Motivation for this change

It's nice to have the old URLs point to the right version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Isn't that a duplicate to https://github.com/NixOS/nixpkgs/pull/140572?

Also, I'm not a maintainer of this package anymore because I can't test it anymore :)

**Comment by obadz** [comment]
Whoops, missed it. I'll rebase to keep the cleanups.

**Comment by obadz** [comment]
Btw that was a proper undetected git merge conflict!

**Review by michaeladler — APPROVED** [review]
LGTM. Makes me wonder how many of these old versions we actually want to keep around. It certainly makes sense to have _some_ older versions, but I guess there should be an upper limit :)

**Comment by obadz** [comment]
Yes every so often someone drops a bunch. But Citrix is finicky so it's nice to have a few handy.

**Pull request merged**
