### PR TITLE
styx and themes: 0.5.0 -> 0.6.0

### PR DESCRIPTION
**Pull request by ericsagnes**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
Fails to build on Darwin, see the Travis log.

**Comment by ericsagnes** [comment]
Thanks for noticing, parsimonious tests were failing on darwin.
#23207 should fix that. ([darwin travis build](https://travis-ci.org/NixOS/nixpkgs/jobs/205479079))

**Comment by fpletz** [comment]
Merged #23207 and restarted travis but still fails. :(

**Comment by ericsagnes** [comment]
Now it is linkchecker tests failing :)
They also fail on [Hydra](http://hydra.nixos.org/job/nixpkgs/trunk/linkchecker.x86_64-darwin), I will try to fix that too.

**Comment by ericsagnes** [comment]
#23208 should fix the linkchecker problem, [travis logs](https://travis-ci.org/NixOS/nixpkgs/builds/205485917).

**Comment by fpletz** [comment]
Here we go again: Travis restarted.

**Comment by fpletz** [comment]
Green. Thanks! :+1:

**Comment by ericsagnes** [comment]
Thanks for merging!

**Pull request merged**
