### PR TITLE
goreleaser: add developer-guy to maintainers list

### PR DESCRIPTION
**Pull request by developer-guy**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I'm one of the active contributors to the GoReleaser project, @caarlos0 can confirm me, and I'd love to be part of the maintainers of the GoReleaser package.

PTAL @c0deaddict @endocrimes @sarcasticadmin @techknowlogick

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]

**Comment by caarlos0** [comment]
> I'm one of the active contributors to the GoReleaser project, @caarlos0 can confirm me, and I'd love to be part of the maintainers of the GoReleaser package.

confirmed! 💜

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
@developer-guy can you add me to the list as well while you're at it?

**Comment by developer-guy** [comment]
of course @caarlos0 but you give me the details like this:

```
    developer-guy = {
      name = "Batuhan Apaydın";
      email = "developerguyn@gmail.com";
      github = "developer-guy";
      githubId = 16693043;
    };
```

**Comment by caarlos0** [comment]
awesome!

Yep, here you go:

```
    caarlos0 = {
      name = "Carlos A Becker";
      email = "carlos@becker.software";
      github = "caarlos0";
      githubId = 245435;
    };
```

**Comment by developer-guy** [comment]
done @caarlos0

**Review by caarlos0 — APPROVED** [review]

**Comment by endocrimes** [comment]
Changes lgtm, not sure if you need to split this into 2 commits (i think you might)

**Review by techknowlogick — APPROVED** [review]

**Comment by developer-guy** [comment]
I've split it into two different commits, thanks for advice!

**Pull request merged**
