### PR TITLE
fix inconsistent caching of VM xchg dirs

### PR DESCRIPTION
**Pull request by erikarvstedt**
xchg is advertised as a bidirectional exchange dir, but file content transfer from host to VM fails due to caching:
If a file is read in the VM and then modified on the host, subsequent re-reads in the VM can yield old, cached data.
This is caused by the use of 9p's `cache=loose` mode that is explicitly meant for read-only mounts.

## TODO
Would it be sensible to use `cache=mmap` [(doc)](https://www.kernel.org/doc/Documentation/filesystems/9p.txt) instead?

## Reproduce
[This script](https://gist.github.com/e3d38fcfa0201c9742092f50d2d297f9) reproduces the bug.

Ping @domenkozar, @aszlig

### CODE REVIEW

**Comment by flokli** [comment]
@JJJollyjim, can you take a look at this?

@erikarvstedt We might also then be able to drop the `sync` commands from the `copy_from_host` method introduced in 798fcaafa4e9212e13c04f101794be83fbd56ba9.

**Comment by flokli** [comment]
It's probably fine to not cache - I doubt there's anything performance critical with a lot of IO exchanged via these folders.

**Comment by erikarvstedt** [comment]
@flokli removing the `sync` in the test driver will lead to bugs in case we add a cached backend in the future. I'll let you decide whether to drop it.

**Comment by flokli** [comment]
> @flokli removing the `sync` in the test driver will lead to bugs in case we add a cached backend in the future. I'll let you decide whether to drop it.

I consider the `sync` a workaround implemented to explicitly flush caches, which hides away the broken caching behaviour. If other applications in the test use `/tmp/xchg` directly, we also can't tell them they need to use `sync`.

If we add back some caching, it should properly invalidate caches on external changes (like an nfs share would do), so we should remove these workarounds - please drop the `sync`.

**Comment by erikarvstedt** [comment]
I had a thorough look at these sync now.
- with xchg dir caching, [this sync](https://github.com/NixOS/nixpkgs/blob/798fcaafa4e9212e13c04f101794be83fbd56ba9/nixos/lib/test-driver/test-driver.py#L621) is needed to commit the VM data to the host. This sync can be removed when removing caching.
- the 3 other syncs in `copy_from_host` and `copy_from_vm` try to transfer host data changes to the VM, but this is pointless (irrespective of xchg dir caching) because 1) syncing in the VM can't possibly pull in host data and 2) 9p is accessing the host filesystem on the cached layer anyways, so even syncing on the host would have no effect in the VM.
(@flokli, would you consider this reasoning to be correct?)

**Comment by flokli** [comment]
I think your reasoning is correct. Can you prefix the second commit, too (`test-driver, virtualization: ` maybe)?

Also, slightly off-topic, but did you see https://github.com/NixOS/nixpkgs/issues/85568?

**Comment by erikarvstedt** [comment]
I'll keep an eye on #85568 and jump in when I see new caching-related issues arise.

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
