### PR TITLE
apache-airflow: init at 1.9.0

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Review by ryantm — DISMISSED** [review]
please resolve merge conflict so we can try building it.

**Comment by offlinehacker** [comment]
@GrahamcOfBorg build airflow

**Comment by samueldr** [comment]
It built locally. Not sure what's usually done for `pypi2nix` packages, there seems to be only one other (`gdbgui`). The other one defines more fields for `meta` in its `default.nix`, though it looks like here everything is accounted for. Maybe @FRidh, @Mic92 or @garbas know more about adding `pypi2nix` packages in nix.

**Review by cawilliamson — APPROVED** [review]

**Comment by cawilliamson** [comment]
I'd love to see this merged - it's certainly been waiting long enough! 👍

**Comment by Mic92** [comment]
Adding 3k lines to the nixpkgs repo is not so nice so.
@cawilliamson you can also add it to [NUR](https://github.com/nix-community/NUR).

**Comment by cawilliamson** [comment]
@Mic92 It's not my commit - I'm just raising the question since it seems to have gone silent for a while.

As for not adding 3k lines - I do kinda get your point there but how else could you really package this for Nix?

**Comment by Mic92** [comment]
The alternative is to re-use packages from `pkgs/top-level/python-packages.nix`

**Comment by offlinehacker** [comment]
Good luck with that and airflow, but yeah i agree this needs a better solution, but currently we don't have one for these cases in nixpkgs as everything is one giant monorepo, which has it's benefits, but also a lot of drawbacks.

**Comment by offlinehacker** [comment]
I'm pretty much annoyed that all nixos, lib and pkgs are in one repo, as i have nix code that does not have anything to do with nixpkgs or nixos and i still have to use this repo.

**Comment by volth** [comment]
I am for merging.
It would allow to update the version following the upstream (there is already ```1.10.3```)

As for the 3k lines, it is not for long time. With ```"Ret-cont" recursive Nix``` (https://github.com/NixOS/rfcs/pull/40) ```pypi2nix``` could be used during the build and those 3k likes would be gone.

**Comment by costrouc** [comment]
I will create a formal package for Apache airflow without pip2nix. Should have this soon as a PR

**Comment by offlinehacker** [comment]
@costrouc nice, what method are you using?

**Comment by costrouc** [comment]
I've written a tool that creates the default.nix and does about 90% of the work. You can use it via "nix-shell -p nixpkgs --run "python-package-init airflow" for example. It makes the creation of theae

**Comment by rasendubi** [comment]
#73074 adds apach-airflow-1.10.5 and has been merged, so I close this.

**Pull request closed without merging**
