### PR TITLE
linux: patch to fix MAP_32BIT crashes, e.g. Haskell

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

Revert a supposed fix the causes a second regression of memory allocation in
the "32 bit" zone.
Such allocations are performed by the GHC RTS linker and some other software.
This regression has particularly affected hercules-ci-agent and nix-serve-ng.
See https://github.com/hercules-ci/hercules-ci-agent/issues/514

I've asked the mailing list whether this is reasonably safe to revert, but the test results speak for themselves as far as the mentioned problem goes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux (though rebuilding due to superficial change)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - This regression does not have a suitable test and I consider this kind of problem infeasible to test for, or too high cost to benefit. I have tested the patch using the hercules-ci-agent flake's `checks.x86_64-linux.agent-functional-test` attribute after extending it to include the patch; see https://github.com/hercules-ci/hercules-ci-agent/issues/514
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Does [`0fa99fdfe1b3`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0fa99fdfe1b38da396d0b2d1496a823bcd0ebea0) not resolve your problem?  Reading the upstream discussion, I think it was supposed to.

**Comment by alyssais** [comment]
Oh, I see.  The regression was later reintroduced after that commit.

**Comment by alyssais** [comment]
Does [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/akpm/mm.git/commit/?h=mm-hotfixes-unstable&id=39bf07d812b888b23983a9443ad967ca9b61551d) solve your problem?

**Review by alyssais — APPROVED** [review]
This is fine with me for now, but in the (unlikely) event it ends up not making it into the mainline, we can't keep it around forever and will have to continue to monitor what happens upstream.

I'd expect it to make it into a stable kernel within the next two weeks, but if you want the patch applied in the meantime we can do it. (It sounds like a very annoying bug.)

**Comment by roberth** [comment]
Yes, this patch does seem to fix the problem and it looks to be a better patch. I'll do a bit more testing and then vendor it.

**Comment by roberth** [comment]
So far so good and I just got a [message from the maple tree author](https://lore.kernel.org/linux-mm/20230515143921.v5ivuipisr4aqppg@revolver/) showing confidence about the patch, and that it will make its way into the upcoming releases.

As you sensed, it is very annoying indeed, so this patch will be very helpful in the meantime.

**Comment by roberth** [comment]
Thank you for the help!

Also, it seems I forgot to vendor it. I'll follow up immediately.

**Comment by roberth** [comment]
Vendoring followup: 
 - https://github.com/NixOS/nixpkgs/pull/232072

**Pull request merged**
