### PR TITLE
 maintainers/team-list: add piotrkwiecinski to php team

### PR DESCRIPTION
**Pull request by piotrkwiecinski**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by aanderse** [comment]
hi @piotrkwiecinski :wave:

are you able to tell us a bit about your motivation to join the `php` team, plans, etc...? thank you!

**Comment by piotrkwiecinski** [comment]
hi @aanderse. I'm a php developer by trade and I'm quite active on github.
I progressively move more configuration to Nix and I would be happy to help with maintenance of PHP related packages.

I have 15 years of commercial experience with PHP/js related projects.
I'm newer to Nix but I understand it better every day.

I can take care of reviewing small package updates for start work on more complex things in near future.

**Review by aanderse — APPROVED** [review]
sounds great!

i'll leave merge to @drupol as he leads the team these days (and does an awesome job at it!)

**Comment by drupol** [comment]
Hey hi!

Usually people get added to that list after showing their interest, through pull requests. Hence partially, the legitimate request from @aanderse.

But OK, let's do an exception here and add you in the team. I couldn't agree more to having more people in the PHP team... especially with all the mess and contributors leaving the community these last days.

Welcome!

**Pull request merged**
