### PR TITLE
ruplacer: init at 0.4.1

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/72971)

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build ruplacer

**Comment by filalex77** [comment]
@mmahut I fixed the MacOS Security thing. r?

**Comment by c0bw3b** [comment]
Checking Darwin build:
@GrahamcOfBorg build ruplacer

**Review by c0bw3b — APPROVED** [review]
Builds and runs

Result of `nix-review pr 72971` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - ruplacer
</details>

---

```console
$ ./results/ruplacer/bin/ruplacer --color always old new -- test.txt 
Patching test.txt
-- This is old
++ This is new

Would perform 1 replacement on 1 matching file
Re-run ruplacer with --go to write these changes to the filesystem
```

**Pull request merged**
