### PR TITLE
cri-o: 1.20.1 -> 1.21.0

### PR DESCRIPTION
**Pull request by saschagrunert**
###### Motivation for this change
Update to the latest release.

cc @NixOS/podman 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117468` at b6d5b09a run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>cri-o</li>
    <li>cri-o-unwrapped</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild`.

Near pkgs/development/go-modules/generic/default.nix:145:5:
```
    |
145 |     buildPhase = args.buildPhase or ''
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/go-modules/generic/default.nix:220:5:
```
    |
220 |     installPhase = args.installPhase or ''
    |     ^
```
</li>
  </ul>
</details>

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by SuperSandro2000** [comment]
somehow the tests failed
@ofborg test cri-o
@ofborg build cri-o

**Comment by zowoq** [comment]
@ofborg test cri-o

**Comment by zowoq** [comment]
https://logs.nix.ci/?key=nixos/nixpkgs.117468&attempt_id=999bf7a8-4688-4c63-a830-f69aa118cb5b
```
trying https://github.com/cri-o/cri-o/archive/v1.20.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120  100   120    0     0    394      0 --:--:-- --:--:-- --:--:--   393
100 12.4M    0 12.4M    0     0  4535k      0 --:--:--  0:00:02 --:--:-- 5760k
unpacking source archive /build/v1.20.2.tar.gz
hash mismatch in fixed-output derivation '/nix/store/2cli1aawsarn7x2la69nh46i026ijjiv-source':
  wanted: sha256:1hv3p0fqcvcd8wagszi646623vqmj9k05w86rzlfjc9asjp4bvja
  got:    sha256:1zyq0p7swbd53cg4k8za9p6apm60ywfvsyrjhxd34qa0pzg2ffs1
```

The hash is correct when I try to build this locally.

**Comment by saschagrunert** [comment]
> Update: hash is now failing locally.

Changed the hash, but for me this is failing locally.

**Comment by SuperSandro2000** [comment]
Hash is still wrong.

**Comment by kvtb** [comment]
Hash is wrong for current `1.20.1` version as well.
Are the upstream guys love to change tags?
Or is there a new non-determinism issue in `fetchFromGitHub`?

**Comment by zowoq** [comment]
`sha256-QTsn3r9AYTJahzJ7vR33wNSrzE3qo0keG6Utrs8F2P8=` for `x86_64-linux`
`sha256-Su5FrtQqMenozwbxAmaSFe8hjCEmfv0UR41thh24Y8M=` for `aarch64-linux`

Weird.

**Comment by saschagrunert** [comment]
I don't think we changed the tag upstream. It seems indeed an architecture related issue.

**Comment by SuperSandro2000** [comment]
Do we need to fetch different sources for different arches?

**Comment by saschagrunert** [comment]
> Do we need to fetch different sources for different arches?

No. How are those hashes being calculated?

**Comment by SuperSandro2000** [comment]
> > Do we need to fetch different sources for different arches?
> 
> No, usually not. How are those hashes being calculated?

after cloning the repo and doing some cleanup the directory is converted into a fixed output derivation IIRC.

**Comment by saschagrunert** [comment]
Updated to v1.21.0

**Pull request merged**
