### PR TITLE
Added BRLTTY package

### PR DESCRIPTION
**Pull request by bramd**

### CODE REVIEW

**Comment by geerds** [comment]
@bramd Did you test your service?

**Comment by geerds** [comment]
@bramd Could you also update our [release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-unstable.xml) for the next stable version? I think the right category would be `Following new services were added since the last release:`. You can see some examples in [older release files](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-1412.xml)

**Comment by bramd** [comment]
@Geerds: Yes, the service works. I might add more configuration options in the future, for now it uses the default BRLTTY configuration which does autodetection and will work for most devices connected via USB.

The service has been added to the release notes.

**Comment by geerds** [comment]
I can't test BRLTTY myself because I don't own such a device but it builds successfully on my machine. So let's merge it. Thank you very much for your work!

**Pull request merged**
