### PR TITLE
bootchart:  0.9 -> 0.14.7;  make pybootchartgui available

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by davidak** [comment]
successfully build on NixOS (64-bit in VirtualBox) :+1: 

we could use that graph to optimize the boot process. :)

**Comment by deepfire** [comment]
@davidak, Note that the new bootchart uses a C-based trace capture mechanism --
bootchartd and bootchart-collector.  It gets built, but it needs to be
integrated into NixOS proper for it to be useful.

Meanwhile, the package only provides the new Python bootchart visualizer
-- pybootchart.

**Comment by bjornfor** [comment]
Worth mentioning systemd-analyze:

```
$ systemd-analyze blame | head
         18.608s munin-node.service
         11.075s jenkins.service
          2.567s systemd-udev-settle.service
          1.734s libvirtd.service
```

It also has a "plot" sub-command, but nothing happened when I tried it. Didn't investigate.

**Comment by bjornfor** [comment]
Ah, it was a permission issue: ```sudo systemd-analyze plot > out.svg``` works.

**Pull request closed without merging**
