### PR TITLE
xorg.xorgserver: 1.20.10 -> 1.20.11

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
https://lists.x.org/archives/xorg-announce/2021-April/003081.html
https://lists.x.org/archives/xorg-announce/2021-April/003080.html

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
nixosTests.i3wm
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/issues/43984

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119340` at c7fba6a4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>58 packages marked as broken and skipped:</summary>
  <ul>
    <li>dockbarx</li>
    <li>gnome3.gnome-books</li>
    <li>gnome3.gnome-documents</li>
    <li>gnunet-gtk</li>
    <li>gtkd</li>
    <li>jucipp</li>
    <li>libsForQt512.discover</li>
    <li>libsForQt512.kde-cli-tools</li>
    <li>libsForQt512.kdeplasma-addons</li>
    <li>libsForQt512.khotkeys</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>201 packages skipped due to time constraints:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>akira-unstable</li>
    <li>almanah</li>
    <li>balsa</li>
    <li>calls</li>
    <li>chrome-gnome-shell</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-control-center</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>127 packages built successfully:</summary>
  <ul>
    <li>alttab</li>
    <li>amtk</li>
    <li>apostrophe</li>
    <li>autokey</li>
    <li>autotiling</li>
    <li>bamf</li>
    <li>banking</li>
    <li>caerbannog</li>
    <li>caffeine-ng</li>
    <li>cage</li>
    <li>cagebreak</li>
    <li>dwl</li>
    <li>feeds</li>
    <li>flashfocus</li>
    <li>formiko</li>
    <li>frame</li>
    <li>fuzzel</li>
    <li>genxword</li>
    <li>giara</li>
    <li>gjs (gnome3.gjs)</li>
    <li>glade (gnome3.glade)</li>
    <li>gnome-passwordsafe</li>
    <li>gnome3.devhelp</li>
    <li>gnome3.gdm</li>
    <li>gnome3.gnome-clocks</li>
    <li>gnome3.gnome-screenshot</li>
    <li>gnome3.gnome-sound-recorder</li>
    <li>gnome3.gnome-weather</li>
    <li>gtksourceview (gnome3.gtksourceview ,gtksourceview3 ,xfce.gtksourceview)</li>
    <li>gtksourceview4 (gnome3.gtksourceview4)</li>
    <li>libdazzle (gnome3.libdazzle)</li>
    <li>meld (gnome3.meld)</li>
    <li>pantheon.mutter (gnome3.mutter334)</li>
    <li>gtg</li>
    <li>i3</li>
    <li>i3-balance-workspace</li>
    <li>i3-layout-manager</li>
    <li>i3-resurrect</li>
    <li>i3-wk-switch</li>
    <li>i3altlayout</li>
    <li>kgx</li>
    <li>kooha</li>
    <li>labwc</li>
    <li>libhandy</li>
    <li>libhandy_0</li>
    <li>lollypop</li>
    <li>metadata-cleaner</li>
    <li>notejot</li>
    <li>ocaml-top</li>
    <li>pa_applet</li>
    <li>pantheon.elementary-dock</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>perl530Packages.Gtk3ImageView</li>
    <li>perl532Packages.Gtk3ImageView</li>
    <li>ping</li>
    <li>portfolio-filemanager</li>
    <li>powerline (python38Packages.powerline)</li>
    <li>python38Packages.dogtail</li>
    <li>python38Packages.ewmh</li>
    <li>python38Packages.i3ipc</li>
    <li>python38Packages.liblarch</li>
    <li>python38Packages.py3status</li>
    <li>python38Packages.pynput</li>
    <li>python38Packages.pystray</li>
    <li>ueberzug (python38Packages.ueberzug)</li>
    <li>python38Packages.xlib</li>
    <li>python38Packages.xvfbwrapper</li>
    <li>python39Packages.dogtail</li>
    <li>python39Packages.ewmh</li>
    <li>python39Packages.i3ipc</li>
    <li>python39Packages.powerline</li>
    <li>python39Packages.py3status</li>
    <li>python39Packages.pynput</li>
    <li>python39Packages.pystray</li>
    <li>python39Packages.ueberzug</li>
    <li>python39Packages.xlib</li>
    <li>python39Packages.xvfbwrapper</li>
    <li>pytrainer</li>
    <li>qt-video-wlr</li>
    <li>rabbitvcs</li>
    <li>raiseorlaunch</li>
    <li>rednotebook</li>
    <li>remarkable-mouse</li>
    <li>safeeyes</li>
    <li>selinux-sandbox</li>
    <li>setzer</li>
    <li>snapper-gui</li>
    <li>sway</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-contrib.inactive-windows-transparency</li>
    <li>sway-unwrapped</li>
    <li>sysprof</li>
    <li>tangram</li>
    <li>virt-manager</li>
    <li>wbg</li>
    <li>wio</li>
    <li>wlroots</li>
    <li>x11docker</li>
    <li>x2goserver</li>
    <li>xf86_input_wacom</li>
    <li>xkb-switch-i3</li>
    <li>xkeysnail</li>
    <li>xorg.xf86inputevdev</li>
    <li>xorg.xf86inputkeyboard</li>
    <li>xorg.xf86inputlibinput</li>
    <li>xorg.xf86inputsynaptics</li>
    <li>xorg.xf86videodummy</li>
    <li>xorg.xf86videovesa</li>
    <li>xorg.xinit</li>
    <li>xorg.xorgserver</li>
    <li>xvfb_run</li>
    <li>xwayland</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Review by lukegb — APPROVED** [review]

**Review by Synthetica9 — APPROVED** [review]
No issues with XWayland on Sway.

**Comment by mjlbach** [comment]
I get a black screen on boot with SDDM/Plasma after this commit.

**Pull request merged**
