### PR TITLE
update linux_latest, add release notes

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change
See discussion at #122438 (on which this pr depends)

~~* this still needs release notes to be written~~
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/122606

**Comment by xaverdh** [comment]
another approach would be to just advise people with zfs to use the stable `linuxPackages`?

**Comment by xaverdh** [comment]
cc @lheckemann for opinions

**Comment by Atemu** [comment]
That or choosing the kernel version manually via e.g. linuxPackages_5_4 etc.

**Comment by lheckemann** [comment]
I use zfs and newer linux versions extensively and agree with the current approach: I want to use the latest kernel I can, and if that means not using the actual latest kernel in nixpkgs, I want to know that (getting an error is a good way to achieve this) and specify it explicitly using a numbered attr as @Atemu suggests.

**Comment by xaverdh** [comment]
Ok, so I updated this pr to bump `linux_latest` and added a word on `linux_latest` + `zfs` in the release notes.

**Review by Atemu — APPROVED** [review]

**Comment by xaverdh** [comment]
So with https://github.com/NixOS/nixpkgs/pull/123401 there is a better solution on the horizon (hopefully). But I somewhat doubt it will make it in before branch, so this is still the way to go?

**Comment by fabianhjr** [comment]
I agree with @lheckemann, rather than delaying the `linux_latest` upgrade ZFS users could fallback to previous versions (lts or 5.11)

**Comment by xaverdh** [comment]
Ok, branch off already happened right? So I opened https://github.com/NixOS/nixpkgs/pull/124281 against master.
I can reopen this pr against the release-21.05 branch if this is desired, or we could wait and hope that zfs will see a stable release soon (https://github.com/openzfs/zfs/pull/12009 was merged a few days ago)?

**Comment by jonringer** [comment]
The latest should reference the latests. If that causes issues for people that use a particular module, then they should pin it according to their needs as other have said.

Even as a zfs user myself, I don't like the idea of preferential treatment toward a particular module, opens the door to prevent a bump to whoever think a module is "block worthy"

**Pull request merged**
