### PR TITLE
Make kodi overrideAttrs and withPackages composable

### PR DESCRIPTION
**Pull request by dwagenk**
###### Description of changes

When using a kodi derivation modified with `overrideAttrs` and adding extensions to it with `withPackages` the changes were discarded and the original unmodified kodi derivation was wrapped together with the extensions.
Fix this by switching kodi to use the `mkDerivation` with `finalAttrs` pattern (described in #119942 and https://nixos.org/manual/nixpkgs/stable/#mkderivation-recursive-attributes).

###### Things done #

For testing I've assebled a little flake
<details><summary>Test-Flake (expand)</summary>
<p>

```nix
{
  description = "test flake for nixpkgs kodi override";

  inputs = {
    nixpkgs.url = github:nixos/nixpkgs/release-22.11;
    flake-utils.url = "github:numtide/flake-utils";
    nix-flake-tests.url = "github:antifuchs/nix-flake-tests";
  };

  outputs = inputs@{ self, nixpkgs, flake-utils, nix-flake-tests }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" ] (system:
      let
        pkgs = import nixpkgs
          {
            localSystem = "${system}";
            overlays = [
              (final: prev: {
                kodi = prev.kodi.overrideAttrs (o: {
                  pname = "test-kodi";
                });
              })
            ];
          };
      in
      {
        packages = {
          inherit (pkgs) kodi;
          kodi-with-addons = pkgs.kodi.withPackages (p: [ p.inputstreamhelper ]);
        };
        checks = {
          kodi = nix-flake-tests.lib.check {
            inherit pkgs;
            tests = {
              testNameStartsWithPName = rec {
                expected = "test-kodi-";
                expr = builtins.substring 0 (builtins.stringLength expected)
                  self.packages.${system}.kodi-with-addons.name;
              };
              testAddonGetsLinked = {
                expected = [ ]; # exact match of regex returns empty list
                expr = builtins.match ".*-kodi-inputstreamhelper-.*"
                  self.packages.${system}.kodi-with-addons.postBuild;
              };
            };
          };
        };
      }
    );
}

```

</p>
</details>

The resulting `kodi-with-addons` derivation includes both, the `pname` changed via `overrideAttrs` as well as the `postBuild` wrapping for the `inputstream` plugin added via `withPackages`.

Running it is possible, finds the plugin and doesn't have any signs of anything being wrong.

- Built on  #platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@dwagenk thanks for contributing this. I'll try and get back to it as soon as I can, though I'm going to prioritize getting the new `kodi` release packaged first. Please be patient with us :bowing_man:

**Comment by aanderse** [comment]
Linking `kodi` update PR for visibility: https://github.com/NixOS/nixpkgs/pull/201835

**Comment by nvmd** [comment]
Proposed changes merged in #304097, thanks!

**Comment by dwagenk** [comment]
Oh, wow, thank you for updating and getting this merged! :tada:

**Pull request closed without merging**
