### PR TITLE
nixos/doc: set groff mdoc os registers properly

### PR DESCRIPTION
**Pull request by pennae**
###### Description of changes

the nixpkgs site-tmac sets doc-default-operating-system and doc-volume-operating-system to Nixpkgs, which is mostly correct but somewhat confusing for Nix*OS* manpages. luckily the previous dance was overly complicated and we can instead just change the registers differently if we detect a nixpkgs groff. this also means we can use plain `.Os` without hard-coding the os as detected by mandoc.

followup from https://github.com/NixOS/nixpkgs/pull/213256#discussion_r1093024815

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
> not sure what to do with that knowledge to be honest. groff was explicitly set to `Nixpkgs` because nixos is just one user of nixpkgs, mandoc went the other way.

@sternenseemann can we make mandoc say "Nixpkgs" too? (The person who originally set that doesn't seem to be active any more.)

**Comment by sternenseemann** [comment]
I'd be fine with that, sure.

**Comment by sternenseemann** [comment]
You mean Nixpkgs?

**Comment by sternenseemann** [comment]
I'd say so! I'd also drop all the shenanigans from the mdoc files and just use the default OS.

If we are too bothered by it I'd make "nixos-versions" of mandoc and groff that are injected into the man viewers via the man-db/mandoc nixos modules (since we can't change it globally via a config file?).

**Pull request closed without merging**
