### PR TITLE
stdenv: Fix error message when checkPhase is missing

### PR DESCRIPTION
**Pull request by nomeata**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you target staging? This change is very little but it rebuilds a lot.

**Comment by nomeata** [comment]
Rebased to `staging`

**Review by jonringer — APPROVED** [review]
I wonder how long this has been this way.

Thanks!

**Comment by nomeata** [comment]
> I wonder how long this has been this way.

Since 50af975d8595c7fce05bc8bbd9db93e3c4cece25, (`git blame` is a squealer)

**Pull request merged**
