### PR TITLE
factorio{,-headless}-experimental: 0.18.34 -> 0.18.36

### PR DESCRIPTION
**Pull request by priegger**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by priegger** [comment]
Result of `nixpkgs-review pr 93525` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- factorio-experimental
<br>- factorio-headless-experimental
</details>

**Comment by bhipple** [comment]
Looks like the hash changed?

```
hash mismatch in fixed-output derivation '/nix/store/qvn9hvxcxrfsinjkn5l67hq1yz1pnm0m-factorio_alpha_x64-0.18.36.tar.xz':
  wanted: sha256:0la4590lf4gssdcf29qm73mz901dnp7cii712fcqw382qh9hbl9q
  got:    sha256:0r94hxmpqcgsjycpc3nf9n84l40g8zxf2kn4mrc0s7rnpymkyynw
```

**Comment by priegger** [comment]
Thanks for reviewing my pr!

factorio-headless-experimental can be downloaded *without* authentication, factorio-experimental can only be downloaded *with* authentication.

Do you have a factorio account/token and do you have it configured?

**Review by erictapen — APPROVED** [review]
Builds for me.

**Comment by bhipple** [comment]
Aha, forgot that this one had to be enabled.  It'd be nice if we could detect that case and give a nicer `assert` error msg, perhaps.  At any rate LGTM :+1:

**Pull request merged**
