### PR TITLE
firmwareLinuxNonfree: 2020-09-18 -> 2020-10-22

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103028` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>firmwareLinuxNonfree</li>
    <li>microcodeAmd</li>
  </ul>
</details>

**Comment by TredwellGit** [comment]
@SuperSandro2000, the maintainer of this package [does not appear to be active](https://github.com/NixOS/nixpkgs/pull/98420). Would you please consider merging this?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000, the maintainer of this package [does not appear to be active](https://github.com/NixOS/nixpkgs/pull/98420). Would you please consider merging this?

I can't merge things.

**Comment by TredwellGit** [comment]
Sorry for bothering you; I should have checked.

**Comment by TredwellGit** [comment]
@NeQuissimus, the maintainer of this package does not appear to be active. Since you update the Linux package, would you please consider merging this?

**Comment by NeQuissimus** [comment]
I'll merge this. I'd feel much better if this had a test ;)

**Comment by TredwellGit** [comment]
This package just provides firmware that is loaded when specific hardware is available; I would write a test, but am unsure how it would work without access to all of that hardware.

This package is updated monthly upstream and since it is required to be updated for new hardware to work and can include security mitigations I would like to ask if it is okay for me to @NeQuissimus message you each month after I prepare the pull request to get it merged in a timely manner unless there is someone else that would be better to contact.

**Pull request merged**
