### PR TITLE
{redshift,gammastep}: do not double wrap & redshift-wlr: remove

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by primeos — APPROVED** [review]
+1 for dropping redshift-wlr.

**Comment by primeos** [comment]
@alpakido may I ask if you're still active as a Nixpkgs maintainer of if we should remove you from the maintainer list (so it looks like we should at least update your information in `all-maintainers.nix` - congratulations btw)?

I wanted to cc you as Redshift maintainer but noticed that your old handle @yegortimoshenko is an org account now and that your last commit seems to be https://github.com/NixOS/nixpkgs/commit/235f4c4a91688175f81797c60872c7c56354c89c.

**Comment by primeos** [comment]
@alpakido a quick reply here would've been nice (resolved now: 719567e91f22de6279269441df85a064d2f11f82 / https://github.com/NixOS/nixpkgs/pull/152985).

**Comment by kira-bruneau** [comment]
Just for reference for anyone who's switching from `redshift-wlr` to `gammastep`, you'll need to specify the executable:
```nix
{
  services.redshift = {
    enable = true;
    package = pkgs.gammastep;
    executable = "/bin/gammastep";
  };
}
```

**Comment by primeos** [comment]
This gives me an idea.

In case someone's interested in improving the module: It might make sense to add `meta.mainProgram` (s. `doc/stdenv/meta.chapter.md`) and let `services.redshift.executable` default to `cfg.package.meta.mainProgram`.

No guarantee that such a PR will be accepted but it sounds like a good idea to me.

**Pull request merged**
