### PR TITLE
jq fix darwin build

### PR DESCRIPTION
**Pull request by Profpatsch**
Fix build of `jq` on darwin

@GrahamcOfBorg build jq

### CODE REVIEW

**Comment by Mic92** [comment]
There is also https://github.com/NixOS/nixpkgs/pull/44200 which seems a proper fix.

**Comment by Profpatsch** [comment]
I’d just merge https://github.com/NixOS/nixpkgs/pull/44228#issuecomment-408885813 instead

**Comment by Mic92** [comment]
But in #44200 tests work also on macOS: https://logs.nix.ci/?key=nixos/nixpkgs.44200&attempt_id=e68c4b9a-6148-4ba2-8558-65d82f14fc6a

**Comment by Profpatsch** [comment]
Closing in favor of #44200

**Pull request closed without merging**
