### PR TITLE
[staging] aliases: fix eval

### PR DESCRIPTION
**Pull request by r-burns**
Due to master->staging semantic merge conflict

Linux 5.12 was removed in master in e55554491df6e7b789d7f3d6a3b354df3575e1c6
but not from the staging aliases in c62f911507977ac67fd5e8547af2d1071c5e0891

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
shouldn't these now throw that they were removed?

**Comment by r-burns** [comment]
I think not, only because the aliases haven't hit master yet. The renaming and aliasing was done in c62f911507977ac67fd5e8547af2d1071c5e0891 which is still in staging.

**Comment by r-burns** [comment]
I ran the ofborg checks locally (https://github.com/NixOS/ofborg#running-meta-checks-locally) which revealed more evaluation errors. It turned out there were some more eval failures after linux_5_12, in the hardened linux packages. These should all be resolved now.

**Comment by vcunat** [comment]
OK, let's not wait.  Evaluation seems to be fixed.

**Pull request merged**
