### PR TITLE
ocsinventory-agent: 2.10.1 -> 2.10.4

### PR DESCRIPTION
**Pull request by anthonyroussel**
https://github.com/OCSInventory-NG/UnixAgent/compare/v2.10.1-MAC...v2.10.4

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by totoroot — COMMENTED** [review]
Hi @anthonyroussel,

I haven't used `ocsinventory-agent` in a while and the update itself looks alright.

If I run `nixpkgs-review` on your PR it seems to build fine, but I'm not sure whether the binary is working as intended.

```
[nix-shell:~/.cache/nixpkgs-review/pr-351733]$ sudo ./results/ocsinventory-agent-x86_64-linux/bin/ocsinventory-agent
Duplicate specification "R|remotedir=s" for option "r"
Duplicate specification "p|password=s" for option "p"
[error] Cannot establish communication : 301 Moved Permanently
```
However, might just be a configuration issue. Have you successfully tested the binary?

The `ipdiscover` binary seems to work fine:

```
[nix-shell:~/.cache/nixpkgs-review/pr-351733]$ sudo ./results/ocsinventory-agent-x86_64-linux/bin/ipdiscover <interface>
<IPDISCOVER>
<H><I>x.x.x.x</I><M>xx:xx:ff:fc:6a:12</M><N>_gateway</N></H>
```

**Comment by anthonyroussel** [comment]
Hi @totoroot,

The binary is working as expected because the OCS Inventory NixOS test is passing

But indeed, there are a few warnings when running ocsinventory-agent:

```
Duplicate specification "R|remotedir=s" for option "r"
Duplicate specification "p|password=s" for option "p"
```

These warnings appear to be related to the GetOpt-Long Perl package.

The GetOpt-Long dependency in nixpkgs was recently upgraded to 2.58 (21th September), which introduced these warnings, see commit https://github.com/nixOS/nixpkgs/commit/dd115b346000967a5602fefa7b1bea6c5f310664

Indeed, since [GetOpt-Long v2.55](https://github.com/sciurius/perl-Getopt-Long/releases/tag/R2.57), GetOpt-Long treats single-letter options as case-sensitive.

However, OCS Inventory Agent uses several single letter options (-p/-P, -r/-R) that don't respect the breaking rule introduced in GetOpt-Long recently. Example: https://github.com/OCSInventory-NG/UnixAgent/blob/v2.10.4/lib/Ocsinventory/Agent/Config.pm#L127.

**Comment by anthonyroussel** [comment]
Looks like 

```nix
postPatch = ''
  substituteInPlace lib/Ocsinventory/Agent/Config.pm \
    --replace-fail "use Getopt::Long;" "use Getopt::Long qw(:config no_ignore_case);"
'';
```

is a resolution.

`no_ignore_case` configuration flag can be passed to `Getopt::Long`

**Comment by anthonyroussel** [comment]
PR opened upstream: https://github.com/OCSInventory-NG/UnixAgent/pull/490

**Review by FliegendeWurst — APPROVED** [review]

**Pull request merged**
