### PR TITLE
Update gnupg21

### PR DESCRIPTION
**Pull request by lsix**
###### Things done
- [X] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
It looks like this deserves a mass-rebuild tag, there are about 3,800 packages being rebuilt.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/16982#-:-KMkWqMNAhruAbAZHAuT:294218084)*

**Comment by grahamc** [comment]
Building locally, I got this error, after a long time:

```
configure:
***
*** You need libgpg-error to build this program.
**  This library is for example available at
***   ftp://ftp.gnupg.org/gcrypt/libgpg-error
*** (at least version 1.24 is required.)
***
configure:
***
*** You need libassuan to build this program.
*** This library is for example available at
***   ftp://ftp.gnupg.org/gcrypt/libassuan/
*** (at least version 2.4.3 (API 2) is required).
***
configure: error: 
***
*** Required libraries not found. Please consult the above messages
*** and install them before running configure again.
***
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/16982#-:-KMkqwf-V7REaZX1Wy8E:-1482586823)*

**Comment by lancelotsix** [comment]
I have updated, it should work but I am still waiting for it to build locally (the libgpg-error update makes the rebuild huge, even just to build gnupg). I’ll update the PR when this is finished and tested.

**Comment by lancelotsix** [comment]
Built, and basic uses of the result works.

**Comment by peti** [comment]
Pushed to `staging`:

* 00e8e4c2ed98ed915e54ee2ee8c402573588adee
* b360982b507f715e71961e44129bc9a60f4b09e1
* 02949b48809f169a0abbb129fadab989052788c0
* d75c43e15c00de060cc0910d30789da195f2ec43

**Pull request closed without merging**
