### PR TITLE
Increase nix-instantiate heap size in eval-release.sh

### PR DESCRIPTION
**Pull request by nlewo**
###### Motivation for this change
Make this script working.
Note, there could be a more clever way to make it working but...

###### Things done
Locally executed.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by LnL7 — COMMENTED** [review]
How I understand it setting a good heap size depends on the available memory of a machine. This makes it impossible to change if necessary.

**Comment by nlewo** [comment]
@LnL7 I don't understand what is exactly the impact of variable, but if I don't set it to 2G, this script fails. Does it work for you without this change?

**Comment by LnL7** [comment]
Setting it to a higher value by default is probably reasonable, but it should still be overridable. eg.

```bash
export GC_INITIAL_HEAP_SIZE=${GC_INITIAL_HEAP_SIZE:-2000000000}
```

**Comment by nlewo** [comment]
@LnL7 Applied.
I'll merge it tomorrow (if nobody complains).

**Pull request merged**
