### PR TITLE
Add macOS support for KeePassXC package

### PR DESCRIPTION
**Pull request by ariutta**
###### Motivation for this change
Make the KeePassXC package work on macOS in addition to Linux

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build keepassx-community

**Comment by bjornfor** [comment]
Please prefix commit messages with "keepassxc: ...".

**Comment by orivej** [comment]
I have added support for macOS in b693f989f65d55d2213c52b716cf26fe60e40ad0 and proposed a fix for `No known features for CXX compiler "Clang" version 4.0.1.` upstream: https://github.com/keepassxreboot/keepassxc/pull/1308 (already merged). I have opted for the app bundle packaging: the app will show in the launcher if ~/Applications is a link to (or contains links into) ~/.nix-profile/Applications. (It can still be launched from console with `open -a keepassxc`. However, both the dock and the open command have severe cash invalidation issues and it was taking me some effort to convince them that they should stop running old binaries after reinstallations of the application. Nevertheless, the first installation is smooth.)

**Comment by orivej** [comment]
I have also added macdeployqt to qttools on darwin in fb349c84e2ccdbf45ef3430392927586b76f4ed9 (on `staging` branch) because it was confusing not to have it, even though with Nixpkgs keepassxc is better without it (because it copies all dependent libraries into the application directory). (It would be nice to upstream an option to disable the use of macdeployqt in keepassxc.)

**Pull request closed without merging**
