### PR TITLE
Chicken egg updates

### PR DESCRIPTION
**Pull request by zilti**
## Description of changes

This updates the list of eggs, as well as removes lsp-server and transducers from the list of broken eggs, since they build, install, and work fine.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zilti** [comment]
Maintainer pings: @corngood @nagy @konst-aa

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 342360` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages marked as broken and skipped:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.chickadee</li>
    <li>chickenPackages_5.chickenEggs.coops-utils</li>
    <li>chickenPackages_5.chickenEggs.hyde</li>
    <li>chickenPackages_5.chickenEggs.hypergiant</li>
    <li>chickenPackages_5.chickenEggs.ipfs</li>
    <li>chickenPackages_5.chickenEggs.pseudo-meta-egg-info</li>
    <li>chickenPackages_5.chickenEggs.pyffi</li>
    <li>chickenPackages_5.chickenEggs.qt-light</li>
    <li>chickenPackages_5.chickenEggs.qwiki</li>
    <li>chickenPackages_5.chickenEggs.scm2wiki</li>
    <li>chickenPackages_5.chickenEggs.sq</li>
    <li>chickenPackages_5.chickenEggs.svnwiki2html</li>
    <li>chickenPackages_5.chickenEggs.system</li>
  </ul>
</details>
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.awful</li>
    <li>chickenPackages_5.chickenEggs.awful-main</li>
    <li>chickenPackages_5.chickenEggs.awful-postgresql</li>
    <li>chickenPackages_5.chickenEggs.awful-salmonella-tar</li>
    <li>chickenPackages_5.chickenEggs.awful-sql-de-lite</li>
    <li>chickenPackages_5.chickenEggs.awful-sqlite3</li>
    <li>chickenPackages_5.chickenEggs.awful-sse</li>
    <li>chickenPackages_5.chickenEggs.awful-ssl</li>
    <li>chickenPackages_5.chickenEggs.awful-static-pages</li>
    <li>chickenPackages_5.chickenEggs.bind</li>
    <li>chickenPackages_5.chickenEggs.bitwise-utils</li>
    <li>chickenPackages_5.chickenEggs.blas</li>
    <li>chickenPackages_5.chickenEggs.concurrent-native-callbacks</li>
    <li>chickenPackages_5.chickenEggs.coops</li>
    <li>chickenPackages_5.chickenEggs.dataframe</li>
    <li>chickenPackages_5.chickenEggs.edward</li>
    <li>chickenPackages_5.chickenEggs.epoxy</li>
    <li>chickenPackages_5.chickenEggs.expat</li>
    <li>chickenPackages_5.chickenEggs.ezxdisp</li>
    <li>chickenPackages_5.chickenEggs.gl-type</li>
    <li>chickenPackages_5.chickenEggs.gl-utils</li>
    <li>chickenPackages_5.chickenEggs.glfw3</li>
    <li>chickenPackages_5.chickenEggs.glls</li>
    <li>chickenPackages_5.chickenEggs.henrietta-cache</li>
    <li>chickenPackages_5.chickenEggs.http-session</li>
    <li>chickenPackages_5.chickenEggs.json-rpc</li>
    <li>chickenPackages_5.chickenEggs.lay</li>
    <li>chickenPackages_5.chickenEggs.lazy-ffi</li>
    <li>chickenPackages_5.chickenEggs.levenshtein</li>
    <li>chickenPackages_5.chickenEggs.locale</li>
    <li>chickenPackages_5.chickenEggs.lsp-server</li>
    <li>chickenPackages_5.chickenEggs.math-utils</li>
    <li>chickenPackages_5.chickenEggs.matrico</li>
    <li>chickenPackages_5.chickenEggs.ncurses</li>
    <li>chickenPackages_5.chickenEggs.noise</li>
    <li>chickenPackages_5.chickenEggs.nrepl</li>
    <li>chickenPackages_5.chickenEggs.opengl</li>
    <li>chickenPackages_5.chickenEggs.pastiche</li>
    <li>chickenPackages_5.chickenEggs.postgresql</li>
    <li>chickenPackages_5.chickenEggs.prometheus</li>
    <li>chickenPackages_5.chickenEggs.random-mtzig</li>
    <li>chickenPackages_5.chickenEggs.slib-charplot</li>
    <li>chickenPackages_5.chickenEggs.sparse-vectors</li>
    <li>chickenPackages_5.chickenEggs.spiffy</li>
    <li>chickenPackages_5.chickenEggs.spiffy-cgi-handlers</li>
    <li>chickenPackages_5.chickenEggs.spiffy-cookies</li>
    <li>chickenPackages_5.chickenEggs.spiffy-directory-listing</li>
    <li>chickenPackages_5.chickenEggs.spiffy-request-vars</li>
    <li>chickenPackages_5.chickenEggs.spiffy-sexpr-log</li>
    <li>chickenPackages_5.chickenEggs.spiffy-uri-match</li>
    <li>chickenPackages_5.chickenEggs.srfi-174</li>
    <li>chickenPackages_5.chickenEggs.srfi-180</li>
    <li>chickenPackages_5.chickenEggs.srfi-19</li>
    <li>chickenPackages_5.chickenEggs.srfi-214</li>
    <li>chickenPackages_5.chickenEggs.srfi-29</li>
    <li>chickenPackages_5.chickenEggs.srfi-60</li>
    <li>chickenPackages_5.chickenEggs.srfi-74</li>
    <li>chickenPackages_5.chickenEggs.srfi-94</li>
    <li>chickenPackages_5.chickenEggs.statistics</li>
    <li>chickenPackages_5.chickenEggs.test-new-egg</li>
    <li>chickenPackages_5.chickenEggs.test-utils</li>
    <li>chickenPackages_5.chickenEggs.toml</li>
    <li>chickenPackages_5.chickenEggs.vectr</li>
    <li>chickenPackages_5.chickenEggs.z3</li>
  </ul>
</details>

**Comment by zilti** [comment]
By the way, what is it with the failing version number checks? E.g. `coops-utils` complains about `coops` being outdated and on version 0.0.0, but that is clearly not the case.

**Comment by corngood** [comment]
This looks good, but the commit summaries should be prefixed with a package name.  Previous update commits used `chickenPackages.chickenEggs`.

> By the way, what is it with the failing version number checks? E.g. coops-utils complains about coops being outdated and on version 0.0.0, but that is clearly not the case.

How do you repro this?

**Comment by zilti** [comment]
> This looks good, but the commit summaries should be prefixed with a package name. Previous update commits used chickenPackages.chickenEggs.

Okay. I renamed the last commit now; I am not sure how to rename earlier ones.

> How do you repro this?

I basically created an .envrc with the packages chicken and chickenPackages_5.chickenEggs.coops-utils, and enabled installation of "broken" packages. This is the output:

```
error: builder for '/nix/store/4af2l77r5rzlkzbbkb6l92ja9jr9mwsa-chicken-coops-utils-2.2.3.drv' failed with exit code 70;
       last 10 log lines:
       > setting SOURCE_DATE_EPOCH to timestamp 1679607780 of file coops-utils-2.2.3/tests/run.scm
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: buildPhase
       > The following installed extensions are outdated, because `coops-utils' requires later versions:
       >
       >   coops (0.0.0 -> 1.3)
       >
       > Do you want to replace the existing extensions? (yes/no/abort)
       > Error: (string->list) bad argument type - not a string: #!eof
       For full logs, run 'nix log /nix/store/4af2l77r5rzlkzbbkb6l92ja9jr9mwsa-chicken-coops-utils-2.2.3.drv'.
error: 1 dependencies of derivation '/nix/store/3dnc30cd6058j11hrw54ph06gl7s8b9g-nix-shell-env.drv' failed to build
```

**Comment by corngood** [comment]
> I am not sure how to rename earlier ones.

Do you mean you're not sure what to rename it to, or you're not sure how to actually do the rename in git?

**Comment by zilti** [comment]
> Do you mean you're not sure what to rename it to, or you're not sure how to actually do the rename in git?

I did manage to rename the last commit I made, but for earlier ones, it seems there's a different approach needed, which I don't know. Seems like it needs some rebase wizardry.

**Comment by corngood** [comment]
> I did manage to rename the last commit I made, but for earlier ones, it seems there's a different approach needed, which I don't know. Seems like it needs some rebase wizardry.

Ah yeah, it's git, so there's a multitude of ways, but here's what I'd do:

`git rebase -i HEAD^^`

This will show both commits in a list, with a `pick` command next to each.  Change the first one to `edit` (or `e`) instead of pick.  Save and exit the editor.

Now it will stop after the first commit.

`git commit --amend`

This is probably what you did to edit the top commit, but now you'll be editing the one before it.  Change the message, save, exit.

`git rebase --continue`

This should finish up the rebase and you'll be ready to force-push.

**Comment by zilti** [comment]
Thanks! Done.

**Review by nagy — APPROVED** [review]
Thanks

**Review by konst-aa — APPROVED** [review]

**Comment by konst-aa** [comment]
🙏

**Pull request merged**
