### PR TITLE
Refactor ~200 package from python-packages.nix -> python-modules

### PR DESCRIPTION
**Pull request by costrouc**
###### Things done

Strictly moving package to `python-modules`. Did not attempt to upgrade package unless it added python 3 support or was broken. Also converted `fetch...` to `fetchPypi` to make future upgrades easier. All packages have been tested in sandbox mode to build properly.

As of the last edit there are ~456 remaining packages.

```
grep "buildPythonPackage" python-packages.nix | wc
    456    2322   18504
```

General steps taken:
 - added any missing meta information (license, description, homepage)
 - `fetch...` -> `fetchPypi`
 - `name = "something-1.0.1";` ->`version="1.0.1"; pname="something";`
 - kept `pkgs` reference (would have taken a lot of time to refactor out)
 - `!isPy27` -> `isPy3k`
 - moved disabled next to version, pname.
 - remove `platforms.all` let `buildPythonPackage` determine

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
I was creating these commits starting from `master` and it looks like it is too far ahead. Not sure what to do. It was 63 commits but grew larger when putting on `staging`.

**Comment by Mic92** [comment]
You also want to rebase this.

**Comment by costrouc** [comment]
This commit does not attempt to update any packages. Only moving them to `python-modules`. I changed the fetch... to `fetchPypi` when possible so that we can update the packages easier in the future.

**Comment by Mic92** [comment]
You can do the following locally:

```
$ git rebase --onto upstream/staging b258a0e51dcea635eb4bdc49d7878774d6f1ee5f 86c673cd9f1e42df0b41eebfca6330718e8f6ea8
$ git push origin +HEAD:costrouc/refactor-to-python-modules
```

In this example `upstream` is the remote name of `https://github.com/NixOS/nixpkgs`

**Comment by costrouc** [comment]
Thank you @Mic92 you were extremely helpful. I am planning to continue moving python packages to `python-modules`. Is this commit too large or can I continue and just merge later?

**Comment by FRidh** [comment]
Thanks a lot! I've rebased and pushed this to staging.

**Comment by FRidh** [comment]
Ohh, the merge conflicts after this change :cry:

**Comment by costrouc** [comment]
@FRidh yes I was very worried about that. Could I do something that would make it easier to merge? I still have about 90 commits to add as well (I am testing them as we speak). I was hoping to check all the `meta` attributes.

**Comment by FRidh** [comment]
Done! 

I don't think there is really anything that can be done. It seems like it is more an issue of timing; there are already quite some package changes in `master` and `staging-next` so I suppose the best moment would be when they've all just been merged together.

Don't let it stop you, go ahead.

**Comment by costrouc** [comment]
Awesome! I will rebase the next 90 commits on the new `staging` in a new PR when I am ready. I am going to have to wait awhile because some of the packages are taking quite some time to build. Thanks for making this easy! Can't wait for the moment when `python-packages.nix` can be truly alphabetical

**Comment by costrouc** [comment]
@Mic92 I've thought about this a bit and I'm thinking that in order to do proper alphabetical sorting we would need the AST representation of the file. This could also be helpful in enforcing a style to files. I really liked your project [pythoninx](https://github.com/Mic92/pythonix) and have played with it. Does [nix/libexpr](https://github.com/NixOS/nix/tree/master/src/libexpr) expose the AST that could somehow be exposed in python? 

Also in regards to sorting I think that normalized sorting would be helpful. For example `Example1_a-sDF` would be sorted as  `example1-a-sdf`.

**Comment by edolstra** [comment]
Once upon a time we had a Stratego program for sorting `all-packages.nix`, using the old SDF grammar to get a syntax tree that includes whitespace/comments. https://github.com/NixOS/nixpkgs/blob/7ee6cf21ea5c4a07499ba4e7cb7834653c77af27/maintainers/scripts/sort-attrs.str

**Pull request closed without merging**
