### PR TITLE
[Backport release-23.11] cuda-modules

### PR DESCRIPTION
**Pull request by ConnorBaker**
> [!Important]
> This PR must be rebased to target `staging-23.11` after the following PRs are merged:
>
> - #273040
>

> [!Important]
> This PR is an amalgamation of changes and subsequent which landed in `master` as part of the work surrounding #256324. This PR includes:
>
> - #256324
> - #273748
> - #270976
> - #270999
> - #267247
> - #273779
> - #273781
> - #273604
> - #271923
> - #273873
>
> PRs to be included once merged:
>
> - #272752
> - #274319
>

## Things done

Backport of #256324.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
I'm not sure I understand whether this fits the backport policy, what is the rationale here?

**Comment by SomeoneSerge** [comment]
Before this gets into a release, the following need to be addressed:

- [ ] https://github.com/NixOS/nixpkgs/issues/273321
- [ ] https://github.com/NixOS/nixpkgs/issues/273674 (https://github.com/NixOS/nixpkgs/issues/272797)
- [ ] Possibly [nsight_systems](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Fqc0zscz1qh0c18mvywd9k4s44n86qngl-nsight_systems-2022.4.2.1.drv/log?via-job=13031ca9-a5ba-4a82-88f3-5a8164d75fa6), not sure about the source yet

**Comment by jonringer** [comment]
> I'm not sure I understand whether this fits the backport policy, what is the rationale here?

It does if there's no regressions. A lot of this work is about improving Nixpkgs + Cuda support, which can be viewed as an additive feature. It should be tested well to ensure that it doesn't introduce any new failures.

**Comment by jonringer** [comment]
cc @NixOS/cuda-maintainers , who would have a good idea of potential regressions

**Comment by ConnorBaker** [comment]
@jonringer excellent point about regression tests -- doubly so for runtime behavior. We don't have anything in the way of tracking performance over time... we're still working on making sure we have enough builders to keep our cache somewhat populated, let alone automated testing or regression detection.

The only runtime tests I have are manual: `cudaPackages.saxpy`, which is really just meant to check that the driver works, and `nix-cuda-test` (https://github.com/ConnorBaker/nix-cuda-test), which has a dinky little ViT model.

@graham33 would you happen to have anything you'd be able to use for regression testing on the 23.11 branch? You're one of the handful of people I know using Nix+CUDA and I'd like to make sure this doesn't cause fires or headaches :)

**Comment by gbpdt** [comment]
> @graham33 would you happen to have anything you'd be able to use for regression testing on the 23.11 branch? You're one of the handful of people I know using Nix+CUDA and I'd like to make sure this doesn't cause fires or headaches :)

(Switching to my other Github ID)

We've started our internal upgrade process to adopt 23.11, which would at least allow us to do some basic testing. We could definitely try to build against your branch and make sure we can get some basic CUDA validation working.

**Comment by SomeoneSerge** [comment]
I mentioned this in the matrix chat, but I'll reiterate here: I don't see a particular rush for backporting these changes to 23.11, unless there's a specific user/customer interested in the new functionality (meaning mostly jetsons) but otherwise limited to using the release branches. I haven't any objections either

**Comment by IlyaNiklyaev** [comment]
Hi 👋 
Our team is interested in this backport to land stable channel 🙂 Yes, we target both jetsons and x86 and we're not ready to switch to unstable.
At the moment we have this PR as a patch over `nixos-23.11`, and it works just fine as we can see (for both x86 and jetson). The only issue is cross-build (`buildPlatform` `x86_64`, `hostPlatform` - `aarch64`, both linux) : I guess we need some additional fixes from `master`, right now I'm trying to figure out the right set of commits.

**Comment by SomeoneSerge** [comment]
Hi @IlyaNiklyaev,

I think backporting new features and breaking interface changes is far from the optimal way to go here:
- it's two months until the next release;
- the PR had (as anticipated) caused a bit of fall out on the unstable which we've been slowly addressing, that it won't be clear what else to backport;
- cross-compilation support actually requires more work anyway (I think @ConnorBaker is iterating on that rn in https://github.com/ConnorBaker/cuda-modules).

I too would like to see a model more like rolling releases with merge trains, but right now it's easier to accept that "new features" take up to 6 months to "stabilize". Wdyt?

**Comment by IlyaNiklyaev** [comment]
Hi @SomeoneSerge,
I think we can't wait until the next release, but I totally understand that there is a lot of moving around this functionality in the unstable which prevents us to just backport all of it. So I'll continue to fix cross-build in our current state (stable 23.11 + the patch from this PR). I think a couple of our fixes would be useful in unstable too :)

**Comment by SomeoneSerge** [comment]
@IlyaNiklyaev I wonder, do you actually "patch" anything, or is it enough to use overlays? E.g.

```nix
inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.11";
inptus.nixpkgs-unstable.url = "...";
outputs = { nixpkgs, nixpkgs-unstable, ... }: {
  packages.x86_64-linux = let pkgs = import nixpkgs { ...; overlays = [(final: prev: {
    cudaPackages = final.callPackage "${nixpkgs-unstable}/pkgs/top-level/cuda-packages.nix" { };
    cudaPackages_XX_Y = ...;
    # ...
  })];
};
```

...might suffice to use the current cudaPackages expressions with the older nixpkgs release

**Comment by IlyaNiklyaev** [comment]
@SomeoneSerge hmm I even haven't tried that. I guess this is a tree-wide change, so it would be much more difficult to apply it as an overlay?
For example, I just tried what you suggested, and got this
```
evaluation aborted with the following error message: 'Function called without required argument "addDriverRunpath" at /nix/store/zafmv50n5r12j0v3cpazsmj2s7v8f5wc-source/pkgs/development/cuda-modules/cuda/overrides.nix:1'
```
So `nixos-23.11` is not compatible with this https://github.com/NixOS/nixpkgs/commit/cfa07014b6af63298365329c8ffc2a132941d985. Ofc I could bisect and try to find some point in unstable's history that will work but it's just much more simpler to take this PR as a patch for now.

**Comment by SomeoneSerge** [comment]
I believe that most of the changes were actually contained to the `cudaPackages*` attributes and to the respective file paths... OOC, I tested `cudaPackages.saxpy` here and it worked: https://github.com/SomeoneSerge/nixos-2311-unstable-cuda/blob/master/mk-overlay.nix

**Comment by wegank** [comment]
As NixOS 23.11 reaches end-of-life today, this PR is closed as part of the [EOL cleanup](https://nixos.github.io/release-wiki/EOL-Cleanup.html).

**Pull request closed without merging**
