### PR TITLE
exiftool: 12.65 -> 12.68

### PR DESCRIPTION
**Pull request by anthonyroussel**
https://github.com/exiftool/exiftool/compare/12.65...12.68

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by cafkafk — COMMENTED** [review]
I'm not done building this but I've had one error so far:

```
error: builder for '/nix/store/hzwrb6vjyw2y8p64dpfk0b6rqq570rdn-paperless-ngx-1.17.2.drv' failed with exit code 1;
       last 10 log lines:
       >
       > paperless/tests/test_settings.py::TestDBSettings::test_db_timeout_with_not_sqlite
       >   /build/source/src/paperless/tests/test_settings.py:340: DeprecationWarning: assertDictContainsSubset is deprecated
       >     self.assertDictContainsSubset(
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED src/paperless_mail/tests/test_mail.py::TestMail::test_handle_mail_account_delete - AssertionError: 0 != 1
       > 1 failed, 771 passed, 13 skipped, 52 warnings in 350.12s (0:05:50)
       > /nix/store/3pfjacvdg9f491lfqc9qb2d0nknx73fb-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
```

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 258383` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>paperless-ngx</li>
  </ul>
</details>
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>digikam</li>
    <li>exiftool (perl538Packages.ImageExifTool)</li>
    <li>exiftool.devdoc (perl538Packages.ImageExifTool.devdoc)</li>
    <li>fgallery</li>
    <li>gcstar</li>
    <li>hugin</li>
    <li>img2pdf (python310Packages.img2pdf)</li>
    <li>img2pdf.dist (python310Packages.img2pdf.dist)</li>
    <li>manga-cli</li>
    <li>mat2 (python310Packages.mat2)</li>
    <li>mat2.dist (python310Packages.mat2.dist)</li>
    <li>megapixels</li>
    <li>metadata-cleaner</li>
    <li>ocrmypdf (python310Packages.ocrmypdf)</li>
    <li>ocrmypdf.dist (python310Packages.ocrmypdf.dist)</li>
    <li>pdfarranger</li>
    <li>pdfarranger.dist</li>
    <li>perl536Packages.ImageExifTool</li>
    <li>perl536Packages.ImageExifTool.devdoc</li>
    <li>phockup</li>
    <li>photofield</li>
    <li>photoprism</li>
    <li>pict-rs</li>
    <li>pict-rs_0_3</li>
    <li>recoll (python310Packages.recoll)</li>
    <li>python311Packages.img2pdf</li>
    <li>python311Packages.img2pdf.dist</li>
    <li>python311Packages.mat2</li>
    <li>python311Packages.mat2.dist</li>
    <li>python311Packages.ocrmypdf</li>
    <li>python311Packages.ocrmypdf.dist</li>
    <li>python311Packages.recoll</li>
    <li>rapid-photo-downloader</li>
    <li>rapid-photo-downloader.dist</li>
    <li>shutter</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>timelapse-deflicker</li>
  </ul>
</details>

**Comment by anthonyroussel** [comment]
@ofborg build exiftool paperless-ngx

**Comment by SuperSandro2000** [comment]
> [exiftool/exiftool@12.65...12.68](https://github.com/exiftool/exiftool/compare/12.65...12.68)

Urgs, is that opencore software or why is the history so bad?

**Review by SuperSandro2000 — APPROVED** [review]

**Review by anthonyroussel — COMMENTED** [review]
`mat2` build fails with exiftool 12.68 because of the new `VideoFullRangeFlag` parameter.

Result of `nixpkgs-review pr 258383` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>8 packages failed to build and are new build failures:</summary>
  <ul>
<li>mat2: <a href="https://termbin.com/dfzg">plain log</a></li>
<li>(python310Packages.mat2): log was empty</li>
<li>mat2.dist: <a href="https://termbin.com/j2fa">plain log</a></li>
<li>(python310Packages.mat2.dist): log was empty</li>
<li>metadata-cleaner: log was empty</li>
<li>paperless-ngx: <a href="https://termbin.com/j37p">plain log</a></li>
<li>python311Packages.mat2: <a href="https://termbin.com/3fto">plain log</a></li>
<li>python311Packages.mat2.dist: <a href="https://termbin.com/ibrv">plain log</a></li>
  </ul>
</details>
<details>
<summary>
33 packages built:
</summary>
<ul>
<li>exiftool (perl538Packages.ImageExifTool)</li>
<li>exiftool.devdoc (perl538Packages.ImageExifTool.devdoc)</li>
<li>fgallery</li>
<li>gcstar</li>
<li>hugin</li>
<li>img2pdf (python310Packages.img2pdf)</li>
<li>img2pdf.dist (python310Packages.img2pdf.dist)</li>
<li>manga-cli</li>
<li>megapixels</li>
<li>ocrmypdf (python310Packages.ocrmypdf)</li>
<li>ocrmypdf.dist (python310Packages.ocrmypdf.dist)</li>
<li>pdfarranger</li>
<li>pdfarranger.dist</li>
<li>perl536Packages.ImageExifTool</li>
<li>perl536Packages.ImageExifTool.devdoc</li>
<li>phockup</li>
<li>photofield</li>
<li>photoprism</li>
<li>pict-rs</li>
<li>pict-rs_0_3</li>
<li>recoll (python310Packages.recoll)</li>
<li>python311Packages.img2pdf</li>
<li>python311Packages.img2pdf.dist</li>
<li>python311Packages.ocrmypdf</li>
<li>python311Packages.ocrmypdf.dist</li>
<li>python311Packages.recoll</li>
<li>rapid-photo-downloader</li>
<li>rapid-photo-downloader.dist</li>
<li>shutter</li>
<li>styx</li>
<li>styx.lib</li>
<li>styx.themes</li>
<li>timelapse-deflicker</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
for mat2, just ignore the test or update the list of expected parameters.
The paperless test looks to be time sensitive, I would just disable it

**Comment by anthonyroussel** [comment]
@ofborg build mat2 metadata-cleaner paperless-ngx

**Review by stigtsp — APPROVED** [review]
LGTM, failures seem unrelated to the exiftool bump.

Result of `nixpkgs-review pr 258383` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>photofield</li>
    <li>rapid-photo-downloader</li>
    <li>rapid-photo-downloader.dist</li>
  </ul>
</details>
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li>digikam</li>
    <li>exiftool (perl538Packages.ImageExifTool)</li>
    <li>exiftool.devdoc (perl538Packages.ImageExifTool.devdoc)</li>
    <li>fgallery</li>
    <li>gcstar</li>
    <li>hugin</li>
    <li>img2pdf (python311Packages.img2pdf)</li>
    <li>img2pdf.dist (python311Packages.img2pdf.dist)</li>
    <li>manga-cli</li>
    <li>mat2 (python311Packages.mat2)</li>
    <li>mat2.dist (python311Packages.mat2.dist)</li>
    <li>megapixels</li>
    <li>metadata-cleaner</li>
    <li>ocrmypdf (python311Packages.ocrmypdf)</li>
    <li>ocrmypdf.dist (python311Packages.ocrmypdf.dist)</li>
    <li>paperless-ngx</li>
    <li>pdfarranger</li>
    <li>pdfarranger.dist</li>
    <li>perl536Packages.ImageExifTool</li>
    <li>perl536Packages.ImageExifTool.devdoc</li>
    <li>phockup</li>
    <li>photoprism</li>
    <li>pict-rs</li>
    <li>pict-rs_0_3</li>
    <li>python310Packages.img2pdf</li>
    <li>python310Packages.img2pdf.dist</li>
    <li>python310Packages.mat2</li>
    <li>python310Packages.mat2.dist</li>
    <li>python310Packages.ocrmypdf</li>
    <li>python310Packages.ocrmypdf.dist</li>
    <li>python310Packages.recoll</li>
    <li>recoll (python311Packages.recoll)</li>
    <li>shutter</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>timelapse-deflicker</li>
  </ul>
</details>

**Pull request merged**
