### PR TITLE
docs: convert packages/linux docbook -> commonmark

### LINKED ISSUE #105257: Convert Linux from Docbook to CommonMark
This issue tracks the conversion of `/doc/builders/packages/linux.xml` from Docbook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Conversion instructions

1. Comment here that you intend to work on it. (Please also post if you stop working on it.)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/builders/packages/index.xml`: change `linux.xml` to `linux.section.xml`.
4. Rename `doc/builders/packages/linux.xml` to `linux.section.md`.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

### PR DESCRIPTION
**Pull request by mmlb**
###### Motivation for this change

Closes #105257, conversion of Docbook Packages for Linux to CommonMark.

@ryantm

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ryantm — APPROVED** [review]
Code and rendering comparison look good; thanks!

**Review by ryantm — CHANGES_REQUESTED** [review]
Sorry, I just noticed the editorconfig was failing. There is some trailing whitespace on line 30 of your md file. Could you remove that?

**Comment by ryantm** [comment]
Closing in favor of #105752 where the trailing whitespace is fixed.

**Comment by mmlb** [comment]
@ryantm Odd, thanks for handling it!

**Pull request closed without merging**
