### PR TITLE
Revert GHC pyopenssl workarounds

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

~~This needs to wait until master is merged into staging~~ Maybe this happened while doing the PR? I am surprised it works now.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
cc @roberth @lovesegfault

**Comment by roberth** [comment]
> ~This needs to wait until master is merged into staging~ Maybe this happened while doing the PR? I am surprised it works now.

I don't understand. What do you mean?

These commits can be reverted when ghc evaluates and builds on aarch64-darwin with a normal `sphinx` build.

```
$ gh pr checkout 179506
[...]

$ nix-instantiate -A ghc --argstr system aarch64-darwin
error: Package ‘python3.10-pyopenssl-22.0.0’ in /home/user/h/nixpkgs/pkgs/development/python-modules/pyopenssl/default.nix:73 is marked as broken, refusing to evaluate.

[...]
```

**Comment by SuperSandro2000** [comment]
> I don't understand. What do you mean?

I was waiting for https://github.com/NixOS/nixpkgs/commit/68da255beca820648a8361e046efc5523aeba5c0 to happen.



> These commits can be reverted when ghc evaluates and builds on aarch64-darwin with a normal `sphinx` build.

Was fixed in https://github.com/NixOS/nixpkgs/pull/179159

**Comment by SuperSandro2000** [comment]
@ofborg build ghc

**Comment by roberth** [comment]
ofborg does not build for `aarch64-darwin`, which is the system type that #179181 was all about.

**Comment by SuperSandro2000** [comment]
> ofborg does not build for `aarch64-darwin`, which is the system type that #179181 was all about.

oh well. We had that a few weeks ago.

**Pull request merged**
