### PR TITLE
Fix PR #193175

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

Unblock channel.

Fixes error introduced as #193175 and cleans up the `config` mess.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
@ofborg test boot.biosCdrom

**Comment by roberth** [comment]
> tests.boot.biosCdrom on aarch64-linux Skipped — No attempt

Expected because 
```
// optionalAttrs (pkgs.stdenv.hostPlatform.system == "x86_64-linux") {
    biosCdrom = makeBootTest "bios-cdrom" {
```

**Comment by roberth** [comment]
> Ugh, sorry about that. OfBorg was happy.

Happens to all of us.

**Comment by alyssais** [comment]
So, do I understand correctly that `config` here was just the `config` value passed in by the module system (the one containing the final values of all NixOS options), and that it ended up just shadowing itself?  And wasn't actually used in at least some of the functions it was passed into?  Trying to follow what this did before makes my head hurt.

**Comment by unbel13ver** [comment]
Sorry for introducing this bug! I actually tested that with
`$ nix-shell -p nixos-generators --run "nixos-generate --format iso --configuration ./iso.nix -o result" -I nixpkgs=<patched nixpkgs>`
where iso.nix is:
```
{ pkgs, modulesPath, lib, ... }: {
  imports = [
    "${modulesPath}/installer/cd-dvd/installation-cd-base.nix"
  ];
  boot.loader.grub.forcei686 = true;
  # use the latest Linux kernel
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.supportedFilesystems = lib.mkForce ["ext4fs"];
}

```

**Comment by roberth** [comment]
> So, do I understand correctly that `config` here was just the `config` value passed in by the module system (the one containing the final values of all NixOS options), and that it ended up just shadowing itself? And wasn't actually used in at least some of the functions it was passed into? Trying to follow what this did before makes my head hurt.

Correct. I've double-checked that `config` is only brought into scope 1. as the (top level) module's module argument, 2. in the two functions that always received the `config` module argument; and nowhere else.

**Review by alyssais — APPROVED** [review]
Thank you for the additional refactor to make this less confusing!

**Comment by roberth** [comment]
> Sorry for introducing this bug! I actually tested that with `$ nix-shell -p nixos-generators --run "nixos-generate --format iso --configuration ./iso.nix -o result" -I nixpkgs=<patched nixpkgs>` where iso.nix is:
> 
> ```
> { pkgs, modulesPath, lib, ... }: {
>   imports = [
>     "${modulesPath}/installer/cd-dvd/installation-cd-base.nix"
>   ];
>   boot.loader.grub.forcei686 = true;
>   # use the latest Linux kernel
>   boot.kernelPackages = pkgs.linuxPackages_latest;
>   boot.supportedFilesystems = lib.mkForce ["ext4fs"];
> }
> ```

I'm surprised that that worked. Maybe something else was also going on.
At least this was caught early. Very early in fact, because the error was discovered by Nix's _static_ scope checking. :nerd_face:

**Pull request merged**
