### PR TITLE
youtube-dl: 2020.12.07 -> 2020.12.09

### PR DESCRIPTION
**Pull request by Luflosi**
###### Motivation for this change
https://github.com/ytdl-org/youtube-dl/releases/tag/2020.12.09

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds via ``nix-review``. ``bomi`` is broken on ``master``.

```
https://github.com/NixOS/nixpkgs/pull/106488
1 package failed to build:
bomi

35 packages built:
catt celluloid curseradio haskellPackages.cut-the-crap jellyfin-mpv-shim jftui kodi-cli lollypop minitube mkchromecast mopidy-youtube mpc-qt mps-youtube mpv persepolis plex-media-player plex-mpv-shim python37Packages.mpv python37Packages.pafy python37Packages.youtube-dl python37Packages.youtube-dl-light python38Packages.mpv python38Packages.pafy youtube-dl youtube-dl-light python39Packages.mpv python39Packages.pafy python39Packages.youtube-dl python39Packages.youtube-dl-light qimgv somafm-cli sublime-music tartube tuijam ytcc
```

**Comment by AndersonTorres** [comment]
What is the problem with `bomi`?

**Comment by drewrisinger** [comment]
@AndersonTorres: end of build log:
cc ``bomi`` maintainer @abbradar 

```
/nix/store/a1hpnpjrxdllbfg179vzj7hnh581sz3c-gcc-wrapper-9.3.0/bin/g++ -c -include release/bomi -pipe -I/nix/store/ag10dkfk5836cbxf3wfd4jl8n54r3fn9-ffmpeg-2.8.17-dev/include -I/nix/store/434d5c8x2jsjlzxh52sw9azx0h44185r-libass-0.15.0/include -I/nix/store/bs6vicmyhls6qh6kv2952zysicrsavcg-libdvdread-6.1.1/include -I/nix/store/yy8gzc2n5jnkv707aj9y806a8yj2ixxf-libdvdnav-6.1.0/include -I/nix/store/ck35ccyczhiyhda6mnc5s3smpmcipniz-libbluray-1.2.1/include -O2 -fvisibility=hidden -I/nix/store/xni10l4g4c51ls05k859fywm6cs8sspv-libchardet-1.0.5/include/chardet -I/nix/store/0fcg2q2rhwivzn4v6jh3bfvgwak1qgj8-glib-2.66.3-dev/include -I/nix/store/0fcg2q2rhwivzn4v6jh3bfvgwak1qgj8-glib-2.66.3-dev/include/glib-2.0 -I/nix/store/iwj5pmz0nnal8k5g3jxmlm4h8rkqf9g0-glib-2.66.3/lib/glib-2.0/include -I/nix/store/b92bxvw4hizsb8kmhjf56mmkjqb9x1h0-libX11-1.7.0-dev/include -I/nix/store/mmdv199syc8mhj5xnyycgfahvxny3wrw-xorgproto-2020.1/include -I/nix/store/hadcvwsfy5n37dx821aysgw7vn33ci0k-libxcb-1.14-dev/include -I/nix/store/xnabsni3bqn9684kh84plxw3vw32l7kh-xcb-util-wm-0.4.1-dev/include -I/nix/store/qjaapnf5xsfw2i8gxlblvlgx3bfsj1f1-alsa-lib-1.2.3-dev/include -D_REENTRANT -I/nix/store/4dcmvca15gikkavwcflwsv9qymi8pgh0-libpulseaudio-13.0-dev/include -I/nix/store/zpga3rkr3ky0sfr9np0vsqx8kb0i6g4f-systemd-246.6-dev/include -I/nix/store/5rlj4czqwzrryj3pf3jacqyiw1bqmmlz-libvdpau-1.4-dev/include -I/nix/store/f4wqmjscb37c57g4di09159kcd78w53l-libva-2.9.1-dev/include -Wno-non-template-friend -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC -DUSING_PCH -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../mpv -I../mpv/build -Ikiss_fft -isystem /nix/store/q77k6msv4x55yxd4c4dx9r9h7b6dm0vm-qtdeclarative-5.15.0-dev/include/QtQuick -isystem /nix/store/7b3adf7pvfqvwq66x6kqz6ci3h8q56k2-qtsvg-5.15.0-dev/include/QtSvg -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtWidgets -isystem /nix/store/3vwmyk434n2pxwq48bms72ayzpy4gldb-qtx11extras-5.15.0-dev/include/QtX11Extras -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtGui -isystem /nix/store/q77k6msv4x55yxd4c4dx9r9h7b6dm0vm-qtdeclarative-5.15.0-dev/include/QtQmlModels -isystem /nix/store/q77k6msv4x55yxd4c4dx9r9h7b6dm0vm-qtdeclarative-5.15.0-dev/include/QtQml -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtNetwork -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtSql -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtXml -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtDBus -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtCore -Irelease -I/nix/store/97136295hqdayx6ibhazviw7kincn8m9-mesa-20.2.3-dev/include -I. -I/nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/mkspecs/linux-g++ -o release/os/os.o os/os.cpp
os/x11.cpp:18:10: fatal error: sys/sysctl.h: No such file or directory
   18 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile.Release:5864: release/os/x11.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/nix-build-bomi-0.9.11.drv-0/source/src/bomi'
make[1]: *** [Makefile:42: release] Error 2
make[1]: Leaving directory '/tmp/nix-build-bomi-0.9.11.drv-0/source/src/bomi'
make: *** [Makefile:40: build/build/bomi/bomi] Error 2
builder for '/nix/store/vfv6afv7cp85himn38pcgrzn7h1zw2sf-bomi-0.9.11.drv' failed with exit code 2
```

**Comment by Mic92** [comment]
> @AndersonTorres: end of build log:
> cc `bomi` maintainer @abbradar
> 
> ```
> /nix/store/a1hpnpjrxdllbfg179vzj7hnh581sz3c-gcc-wrapper-9.3.0/bin/g++ -c -include release/bomi -pipe -I/nix/store/ag10dkfk5836cbxf3wfd4jl8n54r3fn9-ffmpeg-2.8.17-dev/include -I/nix/store/434d5c8x2jsjlzxh52sw9azx0h44185r-libass-0.15.0/include -I/nix/store/bs6vicmyhls6qh6kv2952zysicrsavcg-libdvdread-6.1.1/include -I/nix/store/yy8gzc2n5jnkv707aj9y806a8yj2ixxf-libdvdnav-6.1.0/include -I/nix/store/ck35ccyczhiyhda6mnc5s3smpmcipniz-libbluray-1.2.1/include -O2 -fvisibility=hidden -I/nix/store/xni10l4g4c51ls05k859fywm6cs8sspv-libchardet-1.0.5/include/chardet -I/nix/store/0fcg2q2rhwivzn4v6jh3bfvgwak1qgj8-glib-2.66.3-dev/include -I/nix/store/0fcg2q2rhwivzn4v6jh3bfvgwak1qgj8-glib-2.66.3-dev/include/glib-2.0 -I/nix/store/iwj5pmz0nnal8k5g3jxmlm4h8rkqf9g0-glib-2.66.3/lib/glib-2.0/include -I/nix/store/b92bxvw4hizsb8kmhjf56mmkjqb9x1h0-libX11-1.7.0-dev/include -I/nix/store/mmdv199syc8mhj5xnyycgfahvxny3wrw-xorgproto-2020.1/include -I/nix/store/hadcvwsfy5n37dx821aysgw7vn33ci0k-libxcb-1.14-dev/include -I/nix/store/xnabsni3bqn9684kh84plxw3vw32l7kh-xcb-util-wm-0.4.1-dev/include -I/nix/store/qjaapnf5xsfw2i8gxlblvlgx3bfsj1f1-alsa-lib-1.2.3-dev/include -D_REENTRANT -I/nix/store/4dcmvca15gikkavwcflwsv9qymi8pgh0-libpulseaudio-13.0-dev/include -I/nix/store/zpga3rkr3ky0sfr9np0vsqx8kb0i6g4f-systemd-246.6-dev/include -I/nix/store/5rlj4czqwzrryj3pf3jacqyiw1bqmmlz-libvdpau-1.4-dev/include -I/nix/store/f4wqmjscb37c57g4di09159kcd78w53l-libva-2.9.1-dev/include -Wno-non-template-friend -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC -DUSING_PCH -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../mpv -I../mpv/build -Ikiss_fft -isystem /nix/store/q77k6msv4x55yxd4c4dx9r9h7b6dm0vm-qtdeclarative-5.15.0-dev/include/QtQuick -isystem /nix/store/7b3adf7pvfqvwq66x6kqz6ci3h8q56k2-qtsvg-5.15.0-dev/include/QtSvg -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtWidgets -isystem /nix/store/3vwmyk434n2pxwq48bms72ayzpy4gldb-qtx11extras-5.15.0-dev/include/QtX11Extras -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtGui -isystem /nix/store/q77k6msv4x55yxd4c4dx9r9h7b6dm0vm-qtdeclarative-5.15.0-dev/include/QtQmlModels -isystem /nix/store/q77k6msv4x55yxd4c4dx9r9h7b6dm0vm-qtdeclarative-5.15.0-dev/include/QtQml -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtNetwork -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtSql -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtXml -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtDBus -isystem /nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/include/QtCore -Irelease -I/nix/store/97136295hqdayx6ibhazviw7kincn8m9-mesa-20.2.3-dev/include -I. -I/nix/store/9pq8qqapd9872c2xz1pz9gra8l6rh28s-qtbase-5.15.0-dev/mkspecs/linux-g++ -o release/os/os.o os/os.cpp
> os/x11.cpp:18:10: fatal error: sys/sysctl.h: No such file or directory
>    18 | #include <sys/sysctl.h>
>       |          ^~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [Makefile.Release:5864: release/os/x11.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/tmp/nix-build-bomi-0.9.11.drv-0/source/src/bomi'
> make[1]: *** [Makefile:42: release] Error 2
> make[1]: Leaving directory '/tmp/nix-build-bomi-0.9.11.drv-0/source/src/bomi'
> make: *** [Makefile:40: build/build/bomi/bomi] Error 2
> builder for '/nix/store/vfv6afv7cp85himn38pcgrzn7h1zw2sf-bomi-0.9.11.drv' failed with exit code 2
> ```

Needs a patch: https://wiki.gentoo.org/wiki/Glibc_2.32_porting_notes/sysctl.h_removal

**Comment by Mic92** [comment]
I proposed to remove bomi here: https://github.com/NixOS/nixpkgs/pull/106564

**Comment by Ma27** [comment]
....and why is this relevant? As @drewrisinger correctly stated, the problem exists on master and is therefore not related to this PR.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Ported to stable as 2cfd97255e0b9362334502848eae126763c39e26, 20ffffdb84576ee4c0366302875278c4068bc28e.

**Pull request merged**
