### PR TITLE
pantheon.elementary-files: 6.3.0 -> 6.3.1

### PR DESCRIPTION
**Pull request by bobby285271**
https://github.com/elementary/files/releases/tag/6.3.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg eval
@ofborg test pantheon

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 224918` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>pantheon-tweaks</li>
    <li>pantheon.elementary-files</li>
    <li>pantheon.elementary-files.dev</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

Builds, works

**Comment by davidak** [comment]
Waiting for ofborg tests

**Comment by bobby285271** [comment]
The test has been queued for a day :upside_down_face: I will try to re-trigger them `@ofborg test pantheon` tomorrow, or you might do that [as soon as](https://github.com/NixOS/nixpkgs/pull/224918#issuecomment-1498370701) you found the webkitgtk builds done on hydra (i.e. nothing queued in [here](https://hydra.nixos.org/job/nixpkgs/trunk/webkitgtk.aarch64-linux), [here](https://hydra.nixos.org/job/nixpkgs/trunk/webkitgtk.x86_64-linux), [here](https://hydra.nixos.org/job/nixpkgs/trunk/webkitgtk_4_1.x86_64-linux) and [here](https://hydra.nixos.org/job/nixpkgs/trunk/webkitgtk_4_1.aarch64-linux)). Though I don't expect the test to fail as long as nixpkgs-review is happy.

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Pull request merged**
