### PR TITLE
flyctl: 0.1.104 -> 0.1.112

### PR DESCRIPTION
**Pull request by frontsideair**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by frontsideair** [comment]
Created the PR as draft using gh cli and seems like I can't undraft it now. This is ready.

**Review by techknowlogick — CHANGES_REQUESTED** [review]
I suspect that some ldflags may need to be updated as version information isn't included in the built binary:
```
[nix-shell:~/.cache/nixpkgs-review/pr-263595]$ flyctl version
flyctl v1970.1.1-dev darwin/arm64 Commit: <none> BuildDate: 1970-01-01T00:00:00Z BranchName: dev
```

**Comment by adtya** [comment]
Result of `nixpkgs-review pr 263595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flyctl</li>
  </ul>
</details>

**Comment by adtya** [comment]
It seems that in the latest commit in https://github.com/superfly/flyctl/compare/v0.1.104...v0.1.112 they have changed the ldflag `github.com/superfly/flyctl/internal/buildinfo.version` to `github.com/superfly/flyctl/internal/buildinfo.buildVersion`

**Review by adtya — COMMENTED** [review]
It seems that in the latest commit in https://github.com/superfly/flyctl/compare/v0.1.104...v0.1.112 they have changed the ldflag `github.com/superfly/flyctl/internal/buildinfo.version` to `github.com/superfly/flyctl/internal/buildinfo.buildVersion`

**Comment by frontsideair** [comment]
@adtya Thanks for the heads up! I tried simply changing `version` to `buildVersion`, but it didn't do the trick. I'll investigate more.

**Comment by viraptor** [comment]
Fixed up the naming/tags inhttps://github.com/NixOS/nixpkgs/pull/265437

**Comment by techknowlogick** [comment]
Thanks for your work on this PR @frontsideair 🙏 With @viraptor's linked PR, I'll close this one.

**Pull request closed without merging**
