### PR TITLE
Cleanup pkgs/top-level/python-packages.nix

### PR DESCRIPTION
**Pull request by wizzup**
###### Motivation for this change
This second batch is continuation of  #27379

###### Things done
- [X] Tested using sandboxing : [nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested installation :  tested using [this](https://github.com/NixOS/nixpkgs/pull/27379#issuecomment-315525672) scripts
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Thanks! That one was straight forward to review.

**Comment by Mic92** [comment]
With some regex magic, it might be possible speed up this work (creating files, remove `with self;`, rewrite fetchurl etc).

**Comment by wizzup** [comment]
For python modules, I would love to see automation that fetch metadata from [PyPi](https://pypi.python.org/pypi) directly. 

Like `hackage-packages.nix` for Haskell packages that auto-generated.

**Comment by Mic92** [comment]
Yes there was an attempt to do this here: https://github.com/NixOS/nixpkgs/pull/16005/files#diff-2e1126ffd14680ec965bc0b9576258c4R27

**Pull request merged**
