### PR TITLE
muparser: 2.2.3 -> 2.3.2

### PR DESCRIPTION
**Pull request by trofi**
While at it fixed home page.

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/hgbfbh7mx3dsklx15pq5g16bqvxdxgil-muparser-2.3.2.drv' failed with exit code 1; last 10 log lines:
    Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
  Call Stack (most recent call first):
    /nix/store/gcinad2bdm3fkyxjs73vwqy0pq3wr25m-cmake-3.21.2/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /nix/store/gcinad2bdm3fkyxjs73vwqy0pq3wr25m-cmake-3.21.2/share/cmake-3.21/Modules/FindOpenMP.cmake:544 (find_package_handle_standard_args)
    CMakeLists.txt:27 (find_package)


  -- Configuring incomplete, errors occurred!
  See also "/tmp/nix-build-muparser-2.3.2.drv-0/source/build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/nix-build-muparser-2.3.2.drv-0/source/build/CMakeFiles/CMakeError.log".

```

**Comment by risicle** [comment]
Looks like it just needs `llvmPackages.openmp` supplied to `buildInputs` in the darwin case.

**Comment by trofi** [comment]
Great catch! Also reproducible on linux when clang is enabled:

```
$ nix build --impure --expr 'with import ./.{}; muparser.override { stdenv = clangStdenv; }' -L
...
muparser> CMake Error at /nix/store/q2lj6pxd6sn75fa9pjx9x3jpgxnr6zld-cmake-3.21.2/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
muparser>   Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
```

**Comment by trofi** [comment]
Added openmp from default `llvmPackages` version. Once https://github.com/NixOS/nixpkgs/issues/79818 is fixed we should update it not to pull potentially mismatching `openmp`.

**Comment by trofi** [comment]
Does not seem to happen.

**Pull request closed without merging**
