### PR TITLE
[staging] boost: 1.81 -> 1.86

### PR DESCRIPTION
**Pull request by tobim**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
Seems like a good idea; 1.81 has issues with GCC 14. We should probably backport fixes, but it seems indicative.

**Review by fabianhjr — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says that 3aeb9755e933c27809782891cfbed1660894123e `boost: 1.81 -> 1.86` broke `pkgsi686Linux.boost` build on `staging` as:

```
$ nix build --no-link -f. -L pkgsi686Linux.boost
...
gcc.compile.c++ bin.v2/libs/stacktrace/build/gcc-14/release/x86_32/threading-multi/visibility-hidden/from_exception.o
libs/stacktrace/build/../src/from_exception.cpp:170:2: error: #error On this platform memory leaks are possible if capturing stacktrace from exceptions is enabled and exceptions are thrown concurrently and libc++ runtime is used. Define `BOOST_STACKTRACE_LIBCXX_RUNTIME_MAY_CAUSE_MEMORY_LEAK` to suppress this error if the library would not be used with libc++ runtime (for example, it would be only used with GCC runtime). Otherwise, disable the boost_stacktrace_from_exception library build (for example by `./b2 boost.stacktrace.from_exception=off` option).
  170 | #error On this platform memory leaks are possible if capturing stacktrace from \
      |  ^~~~~

    "g++"   -fvisibility-inlines-hidden -fPIC -m32 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden -march=i686  -DBOOST_ALL_NO_LIB=1 -DBOOST_COBALT_USE_STD_PMR=1 -DNDEBUG   -I"."  -c -o "bin.v2/libs/stacktrace/build/gcc-14/release/x86_32/threading-multi/visibility-hidden/from_exception.o" "libs/stacktrace/build/../src/from_exception.cpp"

...failed gcc.compile.c++ bin.v2/libs/stacktrace/build/gcc-14/release/x86_32/threading-multi/visibility-hidden/from_exception.o...
```

**Comment by tobim** [comment]
I looked into this a bit and I expect this to show up for other platforms as well. If you take a look at the code that produces the error: https://github.com/boostorg/stacktrace/blob/boost-1.86.0/src/from_exception.cpp#L162-L185
You will find that none of this should be evaluated if `BOOST_STACKTRACE_ALWAYS_STORE_IN_PADDING` is set to `0`. That value of that is set at https://github.com/boostorg/stacktrace/blob/boost-1.86.0/src/exception_headers.h#L9-L13.

Does `stdenv.hostPlatform.useLLVM` imply that `libcxx` is used?
If yes we can set `boost.stacktrace.from_exception=off` in that case and `define=BOOST_STACKTRACE_LIBCXX_RUNTIME_MAY_CAUSE_MEMORY_LEAK` otherwise.
If not then I don't know.

**Comment by trofi** [comment]
Yes, at least by default (though `stdenv.cc.libcxx != null` might be a bit more robust):

```
# on x86_64-linux:
nix-repl> stdenv.cc.libcxx
null

nix-repl> pkgsLLVM.stdenv.cc.libcxx
«derivation /nix/store/v2n8l6z08s5pj1k2h72b5kv9gdws34y3-libcxx-x86_64-unknown-linux-gnu-18.1.8.drv»
```

At least building `pkgsLLVM.re2c` results in `libcxx`:

```
$ nix build -f. pkgsLLVM.re2c
$ lddtree result/bin/re2c | fgrep c++
    libc++.so.1 => /nix/store/vv1ml03vyvzk50y9sa53ip0dbg60mvsc-libcxx-x86_64-unknown-linux-gnu-18.1.8/lib/libc++.so.1
    libc++abi.so.1 => /nix/store/vv1ml03vyvzk50y9sa53ip0dbg60mvsc-libcxx-x86_64-unknown-linux-gnu-18.1.8/lib/libc++abi.so.1
```

**Comment by trofi** [comment]
`innoextract` build regressed in `master`. Proposed the fix as:
- https://github.com/NixOS/nixpkgs/pull/367699

**Comment by trofi** [comment]
`wesnoth` build regressed in `master`. Proposed the fix to pin it to older version until there is an upstream support:
- https://github.com/NixOS/nixpkgs/pull/367957

**Comment by trofi** [comment]
`bombono` regressed as well. Proposed the fix bi pinning as:
- https://github.com/NixOS/nixpkgs/pull/402340

**Pull request merged**
