### PR TITLE
dotnet: package v7.0

### PR DESCRIPTION
**Pull request by Infinidoge**
###### Description of changes

Packages the new v7.0 preview version of dotnet (runtime, sdk, etc.)

Since it is a simple change, also added `meta.mainProgram` in `build-dotnet.nix`, since it makes `nix run` function properly.

If these commits should be separated into their own PRs, let me know and I'll close this one and open up new PRs.

Supersedes #169093 (Moved commits to new branch, since I made the mistake of making a PR off of my own master branch)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mdarocha** [comment]
This looks fine. Hovewer, what is nixpkgs policy for having pre-release packages? Shouldn't we wait until 7.0 is officially released before adding it? Or is there a way to mark the package as pre-release?

**Comment by GGG-KILLER** [comment]
If anyone wants to use .NET 7.0 I've created an overlay based on this PR: https://gist.github.com/GGG-KILLER/8431c8fc9b0e57934c83990e5c922b8b

**Comment by Infinidoge** [comment]
Neat, my PR does definitely need updating though.

**Comment by GGG-KILLER** [comment]
> Neat, my PR does definitely need updating though.

Yeah, preview 5 is out and now `buildDotnet` needs `icu`, but other than that it's pretty much done

**Comment by GGG-KILLER** [comment]
@Infinidoge you might want to redo this PR as the way the .NET versions work in nixpkgs has changed (there is now a file for each .NET version) and other previews have been released

**Comment by Infinidoge** [comment]
I'll look into it, but since I don't actively use dotnet anymore, I may just end up closing this PR.

**Comment by GGG-KILLER** [comment]
> I'll look into it, but since I don't actively use dotnet anymore, I may just end up closing this PR.

Would you be okay with me taking up the task of adding .NET 7 to nixpkgs then?
I've been using it for quite a while with an overlay and seems like the current setup we have is enough for it

**Comment by Infinidoge** [comment]
Go right ahead!

I'll close this PR if/when you open your own.

**Comment by GGG-KILLER** [comment]
> Go right ahead!
> 
> I'll close this PR if/when you open your own.

I've opened #187133 that has the new model

**Comment by IvarWithoutBones** [comment]
My apologies, i completely missed this PR when asked for review. I'll try to make sure the followup PR gets merged as soon as possible 👍

**Comment by IvarWithoutBones** [comment]
> This looks fine. Hovewer, what is nixpkgs policy for having pre-release packages? Shouldn't we wait until 7.0 is officially released before adding it? Or is there a way to mark the package as pre-release?

I dont think there is an explicit policy for it. In my opinion its not an issue to add pre-release packages as long as the `version` attribute communicates its a preview release.

**Comment by prusnak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/187133

**Pull request closed without merging**
