### PR TITLE
python310Packages.bitstring: 3.1.9 -> 4.0.1

### PR DESCRIPTION
**Pull request by tjni**
###### Description of changes

https://github.com/scott-griffiths/bitstring/releases/tag/bitstring-4.0.1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
Result of `nixpkgs-review pr 203309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>electrum-grs</li>
    <li>esphome</li>
    <li>esptool</li>
    <li>pynitrokey</li>
    <li>python310Packages.angrop</li>
    <li>python310Packages.cypherpunkpay</li>
    <li>python310Packages.spsdk</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.cypherpunkpay</li>
    <li>python39Packages.spsdk</li>
  </ul>
</details>
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>cantoolz</li>
    <li>chia</li>
    <li>electrum</li>
    <li>electrum-ltc</li>
    <li>home-assistant-component-tests.lifx</li>
    <li>opsdroid</li>
    <li>python310Packages.ailment</li>
    <li>python310Packages.aiolifx</li>
    <li>python310Packages.aiolifx-connection</li>
    <li>python310Packages.aiolifx-effects</li>
    <li>python310Packages.aiolifx-themes</li>
    <li>python310Packages.angr</li>
    <li>python310Packages.angrcli</li>
    <li>python310Packages.bitstring</li>
    <li>python310Packages.cle</li>
    <li>python310Packages.pysml</li>
    <li>python310Packages.pyvex</li>
    <li>python39Packages.ailment</li>
    <li>python39Packages.aiolifx</li>
    <li>python39Packages.aiolifx-connection</li>
    <li>python39Packages.aiolifx-effects</li>
    <li>python39Packages.aiolifx-themes</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.bitstring</li>
    <li>python39Packages.cle</li>
    <li>python39Packages.pysml</li>
    <li>python39Packages.pyvex</li>
    <li>resp-app</li>
  </ul>
</details>

**Comment by bjornfor** [comment]
Some packages fail to build because they specify bitstring<=3.1. Upstream (bitstring) says 3.1.x is still supported, should we keep it as well?

**Comment by tjni** [comment]
Thanks for running `nixpkgs-review`. I'll take a look at those failures and check if the `<=3.1` constraints are necessary.

**Comment by tjni** [comment]
The status of the broken packages:

- electrum-grs: broken because of incompatible `protobuf` version and unrelated to `bitstring` and I couldn't fix it
- esphome: broken only because `esptool` is broken
- esptool: https://github.com/NixOS/nixpkgs/pull/203403
- pynitrokey: broken only because `pythonPackages.spsdk` is broken
- pythonPackages.angrop: broken because of incompatible `angr` version and unrelated to `bitstring`, but will be fixed in https://github.com/NixOS/nixpkgs/pull/203338
- pythonPackages.cypherpunkpay: https://github.com/NixOS/nixpkgs/pull/203341
- pythonPackages.spsdk: https://github.com/NixOS/nixpkgs/pull/203343

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 203309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>electrum-grs</li>
  </ul>
</details>
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>cantoolz</li>
    <li>chia</li>
    <li>electrum</li>
    <li>electrum-ltc</li>
    <li>esphome</li>
    <li>esptool</li>
    <li>esptool_3</li>
    <li>home-assistant-component-tests.lifx</li>
    <li>opsdroid</li>
    <li>pynitrokey</li>
    <li>python310Packages.ailment</li>
    <li>python310Packages.aiolifx</li>
    <li>python310Packages.aiolifx-connection</li>
    <li>python310Packages.aiolifx-effects</li>
    <li>python310Packages.aiolifx-themes</li>
    <li>python310Packages.angr</li>
    <li>python310Packages.angrcli</li>
    <li>python310Packages.angrop</li>
    <li>python310Packages.bitstring</li>
    <li>python310Packages.cle</li>
    <li>python310Packages.cypherpunkpay</li>
    <li>python310Packages.pysml</li>
    <li>python310Packages.pyvex</li>
    <li>python310Packages.spsdk</li>
    <li>python39Packages.ailment</li>
    <li>python39Packages.aiolifx</li>
    <li>python39Packages.aiolifx-connection</li>
    <li>python39Packages.aiolifx-effects</li>
    <li>python39Packages.aiolifx-themes</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.bitstring</li>
    <li>python39Packages.cle</li>
    <li>python39Packages.cypherpunkpay</li>
    <li>python39Packages.pysml</li>
    <li>python39Packages.pyvex</li>
    <li>python39Packages.spsdk</li>
    <li>resp-app</li>
  </ul>
</details>

electrum-grs failure is unrelated:

```
ERROR: Could not find a version that satisfies the requirement protobuf<4,>=3.12 (from electrum-grs) (from versions: none)
ERROR: No matching distribution found for protobuf<4,>=3.12
```

**Review by SuperSandro2000 — APPROVED** [review]

**Review by dotlambda — APPROVED** [review]

**Pull request merged**
