### PR TITLE
g-wrap: 1.9.13 -> 1.9.15 and guile-gnome: 2.16.1 -> 2015/01/23 git

### PR DESCRIPTION
**Pull request by taktoa**
I made a few mistakes and so had to open a new PR.
This should fix the build of guile-gnome-platform.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide in `CONTRIBUTING.md`.

**Comment by taktoa** [comment]
Commits renamed.

**Comment by taktoa** [comment]
Looks like Travis isn't working; curl failed to download the Nix tarball.

**Comment by nckx** [comment]
It does that lately. I've poked it again.

**Pull request merged**
