### PR TITLE
perlPackages.Po4a: fix lib path

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Fix ```Po4a``` paths left after https://github.com/NixOS/nixpkgs/pull/48959

cc @alesguzik @jtojnar

### CODE REVIEW

**Comment by jtojnar** [comment]
Does this make any difference? I removed PERL5LIB from tilix expression and it still produced the same output.

**Comment by volth** [comment]
Maybe removal is an option too :)
if ```perl``` is in ```buildInputs``` $PERL5LIB has to be set by a hook to /lib/perl5/site_perl of all buildInputs  which has such a directory

Anyway ```${perlPackages.Po4a}/lib/perl5``` was a workaround for the bug which #48959 has fixed

**Comment by volth** [comment]
@GrahamcOfBorg build apt

**Comment by volth** [comment]
@GrahamcOfBorg build tilix

**Pull request merged**
