### PR TITLE
flash: 30.0.0.113 -> 30.0.0.134

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

older flash is 404 Not Found

### CODE REVIEW

**Comment by xeji** [comment]
hash mismatch
```
building '/nix/store/bhrywlhnwnbwxcd7k9qpk8yqik3dr0nb-flash_player_npapi_linux.x86_64.tar.gz.drv'...

trying https://fpdownload.adobe.com/get/flashplayer/pdc/30.0.0.134/flash_player_npapi_linux.x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8830k  100 8830k    0     0   849k      0  0:00:10  0:00:10 --:--:--  863k
fixed-output derivation produced path '/nix/store/a6cdgphvd35y5bv62ba3j7q0fwi9jgd1-flash_player_npapi_linux.x86_64.tar.gz' with sha256 hash '0331r5af4zrvwc4h7dp5qyy91dfam5z03yjggls3x04i10nz5myw' instead of the expected hash '08z7a3m0crd9z2rp6cm9q002dpi5vphcgp0607k9wix0sr5zfvyh'
cannot build derivation '/nix/store/awa1z129axzmqzdyk37dq5flb7d2fsz7-flashplayer-30.0.0.134.drv': 1 dependencies couldn't be built
```

**Comment by xeji** [comment]
@cillianderoiste thank you.

**Comment by volth** [comment]
> hash mismatch

Hm, it is not the first time.
It seems that the file is volatile (and in a day or two there will be hash mismatch again)

**Comment by xeji** [comment]
We could use `builtins.fetchurl` which doesn't require a hash. I don't really like that approach but it might be acceptable for a dying, and unfree package.

**Comment by volth** [comment]
Maybe ```builtins.fetchurl``` with checking signature to ensure integrity (I hope they sign the binary packages?)

**Comment by xeji** [comment]
Not sure they do, a quick search turned up nothing that looks like a signature for the linux version.

**Pull request merged**
