### PR TITLE
Add nix packages for plugins for Jenkins + allow using them in the service config.

### PR DESCRIPTION
**Pull request by teh**
I have a script to regenerate the plugin list here: https://github.com/teh/jenkins-plugins-to-nix

I'm planning on improving the script slightly to emit the correct dependencies but as it stands this patch is already quite useful (and tested+ used by us in production) so I decided to do a PR now.

One large downside of this patch is that we do binary downloads of plugins but I don't think we can do much about that until we have Java packaging sorted out.

@coreyoconnor you seem to be the main Jenkins maintainer so pinging you.

### CODE REVIEW

**Comment by jgillich** [comment]
Doesn't the hash change when a plugin gets updated, since it points to the latest version? I think it should fixed versions if possible.

**Comment by coreyoconnor** [comment]
I like the idea and the implementation looks sound except for the issue @jgillich mentioned: The hash of the "latest" plugin will change on upstream update. This is partially an upstream issue. The jenkins download server does not link from "latest" to a folder with a fixed version. A folder with a fixed version is created only when the version is no longer latest.

The links should reference the latest stable version exactly. This would be 1.642. This should be a parameter shared between jenkins and the plugins packages.

Then this would have the same build stability as other packages: Builds are reproducible assuming upstream does not switch the build without changing the version.

**Comment by teh** [comment]
Good points. I updated to point to the latest explicit version.

I'm not sure I understand this comment and what I can change to address it:

> This should be a parameter shared between jenkins and the plugins packages.

Would you mind elaborating?

**Comment by teh** [comment]
@coreyoconnor maybe I should add a -latest link that points to the current version?

**Comment by coreyoconnor** [comment]
Sorry for the delay. :-)
The version that is in the URL for the jenkins.war and the plugins should be, AFAIK, the same. I'd expect the script here:

* https://github.com/teh/jenkins-plugins-to-nix/blob/master/metadata.py#L47

To generate URLs containing the same version value as used for the jenkins.war. Perhaps have the script accept version as an argument?

Also, a link to the jenkins-plugins-to-nix repo contained within the jenkins/default.nix would be nice! Save future developers some time figuring out how to generate the plugins file.

**Comment by teh** [comment]
@coreyoconnor apologies for being so dense but I still don't understand :)

 The jenkins version is `1.643`:

```
  name = "jenkins-${version}";
  version = "1.643";
```

Plugins have their own versions, e.g. `github-api` has version [1.72](https://github.com/teh/nixpkgs/blob/jenkins-boto/pkgs/development/tools/continuous-integration/jenkins-plugins/default.nix#L2903)

Do you want me to rewrite the github version from 1.72 to 1.643? The war URL (http://mirrors.jenkins-ci.org/war/1.643/) seems to contain only one file (jenkins), not a list of plugins tied to that specific version of jenkins.

For the last point: I added a header to the jenkins-plugins/default.nix indicating that the packages are auto-generated, and where to find the script to re-generate them.

**Comment by coreyoconnor** [comment]
Thanks for adding the commentary!

I don't know if what I'm referring to can be resolved without jenkins upstream changing how they manage the plugin uploads. The concern is: Suppose a plugin has a plugin version of 0.1. Can the data at the URL for that plugin change without the version changing? I suspect the plugin data can change without the plugin version changing. This would result in unstable builds: SHA mismatches. A solution that avoids this is what I was looking for.

I was examining 

* https://updates.jenkins-ci.org/1.642/latest/

and assuming the plugins in that directory are tied to jenkins version 1.642. I don't see a clear definition of what plugins are included in the jenkins-version specific directory.

With that considered, I say this change is good to go. :-) Any further refinement looks to require jenkins upstream to assure plugin packages for a given plugin version will not change without the plugin version changing.

**Comment by teh** [comment]
Ah, I hadn't seen that directory, thanks for pointing it out.

Running

```
curl -v https://updates.jenkins-ci.org/1.642/latest/github-api.hpi > /dev/null
```

I get a redirect to:

< Location: https://updates.jenkins-ci.org/download/plugins/github-api/1.72/github-api.hpi

And for an older version of jenkins:

```
curl -v https://updates.jenkins-ci.org/1.554/latest/github-api.hpi > /dev/null
```

It redirects to the same (most recent) github-api:

< Location: https://updates.jenkins-ci.org/download/plugins/github-api/1.72/github-api.hpi

So I don't think we can use this although it would have been nice :/

The correct long term solution IMO is to build each plugin from source (but that requires better java build support, cf e.g. https://github.com/NixOS/nixpkgs/pull/12770)

**Comment by coreyoconnor** [comment]
Hi all,
This patch looks good to me. Objections?
I do not have write access. Any takers on performing the pull?
Thanks!

**Comment by teh** [comment]
For future reference: There's some work on a all-plugin POM file: https://github.com/andresrc/plugin-pom/blob/master/pom.xml but AFAICT from discussions + release log that isn't stable yet.

**Comment by teh** [comment]
Closing to avoid this lingering around. We'll keep this as a patch in our own repo.

**Comment by coreyoconnor** [comment]
What was blocking the pull? I would pull but I do not have write access. Does anybody with write access object to this change?

**Comment by aborsu** [comment]
I actually don't have write access either so we should try pinging someone who does (and I don't know if @bjornfor  has write access.) So @lethalman ??? Or anyone else?

**Comment by bjornfor** [comment]
I have commit access and interest in Jenkins, but too little time :-)

**Comment by bjornfor** [comment]
How big is the generator script that outputs that big list of Jenkins plugins? If it's no bigger than the list it generates, I think it should be included in nixpkgs.

**Comment by bjornfor** [comment]
I think it would be nice if mkJenkinsPlugin was available somewhere in the ```pkgs``` attrset, so that users can use it to define their own plugins. (Yes, I see the function is quite simple, but it's a nice wrapper and example of how to do things.)

**Comment by coreyoconnor** [comment]
Agreed on both: including the generator script in nixpkgs and exposing mkJenkinsPlugins.

**Comment by Fuuzetsu** [comment]
for anyone interested in the future
https://github.com/NixOS/nixpkgs/commit/41ea71a3475174daba0708dae2b365c2dd6f5d30 for service change
https://github.com/Fuuzetsu/jenkinsPlugins2nix for generator

plugins are not added to nixpkgs, you are intended to run the generator yourself. It will recursively pull in dependencies as well.

**Pull request closed without merging**
