### PR TITLE
python-packages: update translationstring 1.1 to 1.3

### PR DESCRIPTION
**Pull request by desiderius**

### CODE REVIEW

**Comment by desiderius** [comment]
The failures in tests is due to a different behavior between CPython and PyPy.

An issue is open on Bitbucket

https://bitbucket.org/zzzeek/mako/issue/238/2-tests-failed-on-pypy-24-25

**Comment by domenkozar** [comment]
Auch, can we disable tests for the time being? And add a comment to the issue

**Comment by desiderius** [comment]
Hello, I disabled the tests for PyPy and added a link to the documentation of the issue.

**Comment by desiderius** [comment]
Hmm, another build failure but this thime I cannot see why (the log reached the 4 Mb limits). Is there a way to improve my workflow before submitting PR for python modules (I just began my journey with NIX) ?

Currently I uses a set of .nix files (one for each python version) with the module that I want to update. Then I uses nix-shell for testing. Obviously, in this manner, I only checks that the updated module can be correctly build...

**Comment by domenkozar** [comment]
`nox-review wip` will build reverse dependencies.

**Comment by lethalman** [comment]
Somebody updated it to 1.3, and it seems to work on pypy: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.pypyPackages.translationstring.x86_64-linux

Closing, please reopen if needed.

**Pull request closed without merging**
