### PR TITLE
qgis: 3.34.3 -> 3.36.0

### PR DESCRIPTION
**Pull request by imincik**
## Description of changes

Update QGIS to the latest version.

List of changes:
* https://changelog.qgis.org/en/qgis/version/3.36

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by imincik** [comment]
I see bunch of deprecation warnings like this in Python console:

```
2024-02-23T21:54:07     WARNING    warning:/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/core/ProcessingConfig.py:37: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead
              class SettingsWatcher(QObject):
             
             traceback: File "", line 1, in 
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 446, in startPlugin
              if not _startPlugin(packageName):
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 426, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/__init__.py", line 11, in classFactory
              from QuickOSM.quick_osm import QuickOSMPlugin
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/quick_osm.py", line 41, in 
              from QuickOSM.quick_osm_processing.provider import Provider
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/quick_osm_processing/provider.py", line 7, in 
              from QuickOSM.quick_osm_processing.advanced.build_query import (
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/quick_osm_processing/advanced/build_query.py", line 9, in 
              from processing.algs.qgis.QgisAlgorithm import QgisAlgorithm
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1126, in _find_and_load_unlocked
              File "", line 241, in _call_with_frames_removed
              File "", line 1176, in _find_and_load
              File "", line 1126, in _find_and_load_unlocked
              File "", line 241, in _call_with_frames_removed
              File "", line 1176, in _find_and_load
              File "", line 1126, in _find_and_load_unlocked
              File "", line 241, in _call_with_frames_removed
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/__init__.py", line 22, in 
              from processing.tools.dataobjects import * # NOQA
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/tools/dataobjects.py", line 41, in 
              from processing.core.ProcessingConfig import ProcessingConfig
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/core/ProcessingConfig.py", line 37, in 
              class SettingsWatcher(QObject):
             
2024-02-23T21:54:07     WARNING    warning:/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/gui/MessageDialog.py:38: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead
              class MessageDialog(BASE, WIDGET):
             
             traceback: File "", line 1, in 
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 446, in startPlugin
              if not _startPlugin(packageName):
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 426, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/__init__.py", line 11, in classFactory
              from QuickOSM.quick_osm import QuickOSMPlugin
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/quick_osm.py", line 41, in 
              from QuickOSM.quick_osm_processing.provider import Provider
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/quick_osm_processing/provider.py", line 7, in 
              from QuickOSM.quick_osm_processing.advanced.build_query import (
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/home/imincik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickOSM/quick_osm_processing/advanced/build_query.py", line 9, in 
              from processing.algs.qgis.QgisAlgorithm import QgisAlgorithm
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1126, in _find_and_load_unlocked
              File "", line 241, in _call_with_frames_removed
              File "", line 1176, in _find_and_load
              File "", line 1126, in _find_and_load_unlocked
              File "", line 241, in _call_with_frames_removed
              File "", line 1176, in _find_and_load
              File "", line 1126, in _find_and_load_unlocked
              File "", line 241, in _call_with_frames_removed
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/__init__.py", line 24, in 
              from processing.tools.general import * # NOQA
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/tools/general.py", line 31, in 
              from processing.core.Processing import Processing
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/core/Processing.py", line 48, in 
              from processing.gui.MessageBarProgress import MessageBarProgress
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/gui/MessageBarProgress.py", line 26, in 
              from processing.gui.MessageDialog import MessageDialog
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/qgis/utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1176, in _find_and_load
              File "", line 1147, in _find_and_load_unlocked
              File "", line 690, in _load_unlocked
              File "", line 940, in exec_module
              File "", line 241, in _call_with_frames_removed
              File "/nix/store/garzj8a8q97c3b3z1ag4s22w9rczrrfi-qgis-unwrapped-3.36.0/share/qgis/python/plugins/processing/gui/MessageDialog.py", line 38, in 
              class MessageDialog(BASE, WIDGET):
             
```

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Is it ok to merge still?

**Comment by imincik** [comment]
k

> Is it ok to merge still?

Yes, I think it is still good to be merged.

**Comment by imincik** [comment]
Thanks for merging @drupol !

**Pull request merged**
