### PR TITLE
Fix imperative containers

### LINKED ISSUE #40355: Imperative containers broken on 18.03/nixos-unstable
## Issue description

I upgraded an imperative container from 17.03 to 18.03 with nixos-unstable on the host: 18.09pre139319.1d9330d63a5 (Jellyfish), and now I can no longer run any nix commands:

```
$ nixos-rebuild -v switch 
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
building Nix...
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
warning: don't know how to get latest Nix
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
building the system configuration...
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
```

```
$ nix-env -iA nixos.hello 
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
```
I also tried creating a fresh container and it breaks in the same way.

## Technical details

`nix-info` on the container fails with:
error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
system: 0, multi-user?: no, error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system
version: 0, error: opening lock file '/nix/var/nix/db/big-lock': Read-only file system

`nix-info` on the host system:
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.0.2, channels(goibhniu): "nixos-18.03pre120540.b8f7027360", channels(root): "nixos-18.09pre139319.1d9330d63a5", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

### PR DESCRIPTION
**Pull request by arianvp**
###### Motivation for this change

When logging into a container by using
  nixos-container root-login
all nix-related commands in the container would fail, as they
tried to modify the nix db and nix store, which are mounted
read-only in the container.  We want nixos-container to not
try to modify the nix store at all, but instead delegate
any build commands to the nix daemon of the host operating system.

This already works for non-root users inside a nixos-container,
as it doesn't 'own' the nix-store, and thus defaults
to talking to the daemon socket at /nix/var/nix/daemon-socket/,
which is bind-mounted to the host daemon-socket, causing all nix
commands to be delegated to the host.

However, when we are the root user inside the container, we have the
same uid as the nix store owner, eventhough it's not actually
the same root user (due to user namespaces). Nix gets confused,
and is convinced it's running in single-user mode, and tries
to modify the nix store directly instead.

By setting `NIX_REMOTE=daemon` in `/etc/profile`, we force nix
to operate in multi-user mode, so that it will talk to the host
daemon instead, which will modify the nix store for the container.

This fixes #40355

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by arianvp** [comment]
cc @flokli 

Also it would be great to have this backported to `18.09`

**Comment by samueldr** [comment]
:+1: for the backport; this is something that could sting some users.

**Comment by flokli** [comment]
@arianvp, @samueldr verified this works. It's a bit tricky, as `nixos-container` wanted to use nixpkgs from my current channel, not from the currently generation I switched to, but I simply abused a nixos test vm to verify manually the steps outlined in https://github.com/NixOS/nixpkgs/issues/40355#issuecomment-388855404 now work.

LGTM, should be merged and backported to 18.09 as well.

**Review by flokli — APPROVED** [review]

**Comment by samueldr** [comment]
Hi!

I am verifying this PR, and it looks like the regression test could be failing to test the regression?

```
git revert 3624bb536244ea99f9f9a6d18ff00bbe4a5204af
time nix-build nixos/tests/containers-imperative.nix
```

And part of the log:

```
- machine: must succeed: nix-instantiate -E 'derivation { name = "empty"; builder = "false"; system = "false"; }'
    machine# [31;1mwarning:[0m you did not specify '--add-root'; the result might be removed by the garbage collector
    machine: exit status 0
```
image

**Comment by arianvp** [comment]
Odd.. works for me now too. Investigating...

**Comment by arianvp** [comment]
Okay @samueldr I fixed it..  `--amend`'ed the last commit with the fix, so'll you'll have to force-pull.

I ran the regression test in the _vm_ instead of the _container_ inside the _vm_.     The regression test should now properly trigger a failure when you revert `3624bb536244ea99f9f9a6d18ff00bbe4a5204af`

**Comment by arianvp** [comment]
P.s. how did you get such pretty log outputs? Mine are a lot more ... verbose

**Comment by flokli** [comment]
@arianvp Take a look at the `result` directory after running the tests

**Comment by samueldr** [comment]
@GrahamcOfBorg test containers-imperative

**Comment by samueldr** [comment]
Backported

 * https://github.com/NixOS/nixpkgs/compare/d0b24be55da0...1ada6fcde10a

**Pull request merged**
