### PR TITLE
firefox-{,bin-}unwrapped: 115.0.3 -> 116.0; firefox-esr-102-unwrapped: 102.13.0esr -> 102.14.0esr; firefox-esr-115-unwrapped: 115.0.3esr -> 115.1.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
https://www.mozilla.org/en-US/firefox/116.0/releasenotes/
https://www.mozilla.org/en-US/firefox/115.1.0/releasenotes/ (still 404 :eyes:)
 → https://www.mozilla.org/en-US/firefox/115.1esr/releasenotes/
https://www.mozilla.org/en-US/firefox/102.14.0/releasenotes/

Migrate the default ESR alias to the 115 ESR series. Removal later, but already prepared in #242865.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Ran the nixos test for all source packages on aarch64-linux and x86_64-linux. Tested Firefox 116.0 (source) manually. Release notes are not up yet and the link for 115.1.0esr is 404.

**Comment by kirillrdy** [comment]
close https://github.com/NixOS/nixpkgs/pull/246381 ?

**Comment by vcunat** [comment]
I noticed a complaint about speech synthesis, pointing to
https://support.mozilla.org/en-US/kb/speechd-setup
(I wasn't trying to do speech synthesis, though.)

**Comment by vcunat** [comment]
However, our `speechd` package currently depends on 2/3 GB of data, so we surely don't want to pull that into `firefox` closure by default.

**Pull request merged**
