### PR TITLE
discourse: 2.9.0.beta1 -> 2.9.0.beta3

### PR DESCRIPTION
**Pull request by talyz**
###### Description of changes
Update `discourse` to the latest beta. Since 2.9.0.beta2, `discourse` requires [building with Ember CLI](https://meta.discourse.org/t/new-installs-will-default-to-ember-cli-builds-in-production/208282), so from now on we have to package the asset building yarn packages.

###### Todo
- [x] Implement yarn package updates in `update.py`
- [x] Update redis option name

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ryantm — APPROVED** [review]
Wow, I'm surprised how simple you were able to make the yarn/ember building! It seems to work great for me.

Probably we should also update the plugins, but that can be a separate PR.

**Comment by talyz** [comment]
Great! I've now added the missing pieces and updated the plugins, so everything should be done.

**Comment by talyz** [comment]
I'll merge this on Monday unless someone objects.

**Comment by dpausp** [comment]
Haven't had time to check it out but I can do it on Monday.

**Comment by talyz** [comment]
Okay, I'll hold off until you've completed your testing.

**Review by dpausp — APPROVED** [review]
Thanks, code changes look good to me! Updated my test system and NixOS Discourse staging from 2.8.0.beta11 (NixOS 21.11). Tested basic posting functionality, backups and the following plugins: discourse-assign, discourse-canned-replies, discourse-checklist, discourse-docs, discourse-solved, discourse-spoiler-alert, discourse-voting.

**Pull request merged**
