### PR TITLE
qhyccd-sdk: add new package

### PR DESCRIPTION
**Pull request by i-am-logger**
This commit adds a new Nix package for the QHYCCD SDK, version 23.01.11. The package includes libraries, header files, and sample code for interfacing with QHYCCD astronomy cameras, and is licensed for non-commercial use only. The package supports both x86-64 and ARM64 architectures, and includes an installation script for setting up the SDK on a system. The package has been successfully tested using nix-build and nix-shell, and has been added to the nixpkgs repository.

### CODE REVIEW

**Comment by realsnick** [comment]
started some work but struggle testing it locally, will appriciate the help

**Comment by AndersonTorres** [comment]
Why are you trying to destroy all-packages.nix?

**Comment by realsnick** [comment]
> Why are you trying to destroy all-packages.nix?

I'll appreciate help with this package.

**Comment by realsnick** [comment]
made a new one https://github.com/NixOS/nixpkgs/pull/254714

**Pull request closed without merging**
