### PR TITLE
stdenv.darwin: bootstrap darwin using updated tools

### LINKED ISSUE #222717: Tracking issue: Update Darwin bootstrap files
I'm opening a tracking issue for updating the [Darwin bootstrap files](https://github.com/NixOS/nixpkgs/blob/32d8946c86d0fb459bcfd4fca2593417d3a54d4c/pkgs/stdenv/darwin/default.nix#L9-L36) to document pending changes, and to see if/when we have enough reasons to perform an update.

The last update was in 2021 as part of #105026. I've been told updates to bootstrap-files are supposed to be rare, and there should be good rationale. Once we have that, plus some thumbs up from @NixOS/darwin-maintainers, we should be able to find help getting tarballs.nixos.org updated via [#infra:nixos.org](https://matrix.to/#/#infra:nixos.org).

Currently pending changes:

- #202347
  This PR changed the structure of the bootstrap files. Currently, there is the main bootstrap-tools archive, plus some separate executables required to unpack it (sh, bzip2, mkdir, cpio). The new structure is just an archive, and uses the builtin Nix support for `.nar.xz` unpacking. The PR contains more rationale, plus there's an [example commit](https://github.com/stephank/nixpkgs/commit/7be022c2f9e9a68c07cefb803612393d7b6849db).

- #166401
  Maybe(?) update LLVM and change arch flags for Apple Silicon.

- Anything else?

Reasons to delay:

- With only the first one above currently on `master`, the pending changes do not significantly affect the resulting stdenv.

Reasons to move forward:

- Maybe we want to resolve the discrepancy in structure (between the bootstrap-tools we build and the bootstrap-tools we fetch) before 23.05?

### LINKED ISSUE #294518: aarch64-darwin bootstrap-tools libc++.1.0.dylib LC_RPATH is wrong
### Describe the bug

noticed in https://github.com/NixOS/nixpkgs/pull/292043#issuecomment-1986740316

filtered output of `otool -l libc++.1.0.dylib` from http://tarballs.nixos.org/stdenv-darwin/aarch64/20acd4c4f14040485f40e55c0a76c186aa8ca4f3/bootstrap-tools.cpio.bz2
```console
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/lib/libc++abi.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1.0.0
Load command 14
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
```

adding the name + path from the above gives us... `@loader_path/../lib/lib/libc++abi.dylib`. there is an extra lib and thus generates an invalid path and makes the lookup of libc++abi.dylib fail.

fix is to generate new bootstrap-tools with the correct paths.

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

- update the hashes and tools needed to extract the bootstrap-tools archive
- unify the x64 and aarch64 unpack process

- second try of https://github.com/NixOS/nixpkgs/pull/295558 but after xz downgrade to 5.4.2
- considered downgrading xz further for tools to 5.2.5 so not have to update again as 5.4.2 has commits from malicious committer but stuck with xz version in nixpkgs
- considered using zstd / gzip for compression of tarball / unpack.nar but nix doesn't support gz for nar files

tools from:
- https://hydra.nixos.org/build/255282138
- https://hydra.nixos.org/build/255281731

testing:
```
maintainers/scripts/bootstrap-files/refresh-tarballs.bash --targets=aarch64-apple-darwin,x86_64-apple-darwin
for sys in aarch64 x86_64; nix-build  -A stdenv --system ${sys}-darwin
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
rebased with staging to get the fix https://github.com/NixOS/nixpkgs/pull/301310 for the format check workflow.

**Review by reckenrode — APPROVED** [review]
Built successfully on x86_64-darwin and aarch64-darwin. lgtm

**Comment by a-n-n-a-l-e-e** [comment]
ping @lovesegfault for tools update (thanks!):  info here https://github.com/NixOS/nixpkgs/pull/301252#issuecomment-2034964774 hopefully no xz backdoors in this round.

**Comment by lovesegfault** [comment]
Uhhh, what? The contributor who got us to include the vulnerable `xz` in the Darwin bootstrap just deleted their account?

I have not uploaded the bootstrap tarballs here. I think perhaps we should revoke the vulnerable ones entirely? Even though AFAIK the xz malware does not do anything when running on Darwin.

cc. @mweinelt @reckenrode @grahamc

**Comment by risicle** [comment]
This was `a-n-n-a-l-e-e`, who is currently explaining on matrix the unrelated reason for deleting their account.

**Comment by mweinelt** [comment]
> Uhhh, what? The contributor who got us to include the vulnerable xz in the Darwin bootstrap just deleted their account?

Let's be careful with any implications or accusations.

**Pull request closed without merging**
