### PR TITLE
vimPlugins.nvim-lastplace: init at 2021-10-15

### PR DESCRIPTION
**Pull request by malob**
###### Description of changes

Updated `vimPlugins` and `chargoSha256` for `maple-bin` in `vim-clap` override. Added `nvim-lastplace`.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by malob** [comment]
Result of `nixpkgs-review pr 177064` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.vim-go</li>
  </ul>
</details>
<details>
  <summary>105 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-treesitter</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.doki-theme-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.ncm2</li>
    <li>vimPlugins.ncm2-jedi</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-lastplace</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-yarp</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.papercolor-theme</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.sqlite-lua</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tagbar</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.ultisnips</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-colorschemes</li>
    <li>vimPlugins.vim-flutter</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-merginal</li>
    <li>vimPlugins.vim-move</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-vp4</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.yats-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 177064` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.vim-go</li>
  </ul>
</details>
<details>
  <summary>105 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-treesitter</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.doki-theme-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.ncm2</li>
    <li>vimPlugins.ncm2-jedi</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-lastplace</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-yarp</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.papercolor-theme</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.sqlite-lua</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tagbar</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.ultisnips</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-colorschemes</li>
    <li>vimPlugins.vim-flutter</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-merginal</li>
    <li>vimPlugins.vim-move</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-vp4</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.yats-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 177064` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>107 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-treesitter</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.doki-theme-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.ncm2</li>
    <li>vimPlugins.ncm2-jedi</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-lastplace</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-yarp</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.papercolor-theme</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.sqlite-lua</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tagbar</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.ultisnips</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-colorschemes</li>
    <li>vimPlugins.vim-flutter</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-javacomplete2</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-merginal</li>
    <li>vimPlugins.vim-move</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-vp4</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.yats-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Review by teto — APPROVED** [review]

**Comment by malob** [comment]
@SuperSandro2000, if this PR looks good to you, a merge would be appreciated :)

**Pull request merged**
