### PR TITLE
rustc: Fix cross build for FreeBSD

### PR DESCRIPTION
**Pull request by rhelmot**
## Description of changes

I ran into two errors trying to build rust packages cross for FreeBSD on staging.

The first was that llvm wouldn't compile, since it was using a guest compiler as the host compiler and it was segfaulting trying to execute min-llvm-tblgen. The fix for this is the second commit.

The second was that rustc wouldn't compile, citing errors about libunwind. As per https://github.com/NixOS/nixpkgs/pull/320472, FreeBSD shouldn't use libunwind.

I believe both of these are simple errors from https://github.com/NixOS/nixpkgs/pull/320432. The day we get FreeBSD CI is the day I will be happy waterfowl.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mic92** [comment]
This is not functional for native compilation, right?

**Comment by rhelmot** [comment]
I haven't tried it native yet

**Comment by rhelmot** [comment]
Works native, as long as you have https://github.com/NixOS/nixpkgs/pull/340913 and https://github.com/NixOS/nixpkgs/pull/335703 merged

**Comment by artemist** [comment]
I don't have permission to change the PR to be on master, only @rhelmot can do that. There's no need to be on staging since this will cause no derivation changes except for cross-compiling to systems with `useLLVM = true`, which was previously broken

**Comment by artemist** [comment]
There's still one more incorrectly overridden stdenv (https://github.com/NixOS/nixpkgs/pull/339909/files#diff-6a40155bf712958e40f1730a5c044872d1f1aba77c903e48137e72a45bfc0396R101) but that seems like a bit of a pain to do that one.

**Comment by Mic92** [comment]
> There's still one more incorrectly overridden stdenv (https://github.com/NixOS/nixpkgs/pull/339909/files#diff-6a40155bf712958e40f1730a5c044872d1f1aba77c903e48137e72a45bfc0396R101) but that seems like a bit of a pain to do that one.

Oh. Did I merge this one too quickly?

**Comment by artemist** [comment]
I think that one is only needed for firefox and a few other packages doing cross-language LTO. I'll deal with it when I come to it and I currently have no way of testing.

**Pull request merged**
