### PR TITLE
forgejo: 7.0.4 -> 7.0.5

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

https://codeberg.org/forgejo/forgejo/releases/tag/v7.0.5

https://codeberg.org/forgejo/forgejo/src/branch/forgejo/RELEASE-NOTES.md#7-0-5

diff: https://codeberg.org/forgejo/forgejo/compare/v7.0.4...v7.0.5

While updating using `nix-update forgejo --version 7.0.5` I this time got this error reproducibly:

```
[…]
Running phase: patchPhase
applying patch /nix/store/z37y57cp2n3fai1sjvr7221k41hprrf5-static-root-path.patch
patching file modules/setting/server.go
applying patch /nix/store/jczl89zs3xlhz4bsrrwrd681mqklimb3-f01dc4b271f54201e60a7c795d784813eac3f7ce.patch
patching file cmd/dump_test.go
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
4 out of 4 hunks ignored -- saving rejects to file cmd/dump_test.go.rej
error: builder for '/nix/store/f24g98pj9lkfy9x0vpq41xjjbbhnsjbg-forgejo-7.0.5-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > source root is source
       > Running phase: patchPhase
       > applying patch /nix/store/z37y57cp2n3fai1sjvr7221k41hprrf5-static-root-path.patch
       > patching file modules/setting/server.go
       > applying patch /nix/store/jczl89zs3xlhz4bsrrwrd681mqklimb3-f01dc4b271f54201e60a7c795d784813eac3f7ce.patch
       > patching file cmd/dump_test.go
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 4 out of 4 hunks ignored -- saving rejects to file cmd/dump_test.go.rej
       For full logs, run 'nix log /nix/store/f24g98pj9lkfy9x0vpq41xjjbbhnsjbg-forgejo-7.0.5-go-modules.drv'.
error: 1 dependencies of derivation '/nix/store/xb0fkn7dpj3dgahrdl0qyx8d43np8d5x-forgejo-7.0.5.drv' failed to build
copying path '/nix/store/brm9jikmbfb7ph9cxzgmvxlvhsixss5f-unit-systemd-udev-settle.service' from 'https://cache.nixos.org'...
building '/nix/store/dzsqb8qs5lj6y3szk0w2s62k3qzxpm30-X-Restart-Triggers-sshd.drv'...
error: 1 dependencies of derivation '/nix/store/p2gkfajw68b2m3kwk0b1arq2bas4n64s-nixos-tmpfiles.d.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3p2vkn820jnxsg4g8v5z5668ynvgzy4f-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/70b9ng125cpvgxg2bgiariwd85g2clkk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7givnx9h9gmnxgscgxswl8bhr9v084vz-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q5afxp6hm9f9vgard18iap0qpc5mdcw7-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qw4i8y08am80d2gcz4zck1y7qiycpbal-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vz3mkxr6ygashphy7fcq5mzx6jvnz787-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/68szvga8rgf1jzsiq67g80yn1d7ynv4w-unit-forgejo-dump.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/78ylqklmg3d509g8ca33vavr67s16vin-unit-forgejo.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lhk534ydyg922giyqjd0k5qkh69y1i08-unit-forgejo.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r709304229nvhg3d0749xyx6kr38hyzr-unit-forgejo.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b9nlf7hm01673rl2hhb5bgl0mdbz37ll-unit-script-forgejo-secrets-start.drv' failed to build
building '/nix/store/9wiwk5y2bmhjx1qvxz2a72bvnv83j1ql-unit-systemd-udev-settle.service.drv'...
building '/nix/store/kar8k49q344z8a5hjzaj94vk0vcgl78v-unit-systemd-update-utmp.service.drv'...
building '/nix/store/01gssqaps442813pxy1jgiaagkcjchf8-unit-systemd-user-sessions.service.drv'...
error: 1 dependencies of derivation '/nix/store/2ykkvdkaib340nxv69x4p623c9r33c6s-nixos-system-server-test.drv' failed to build
copying path '/nix/store/92jnqy9gyvq63cjvrm40mdpj36nmjxdc-unit-systemd-update-utmp.service' from 'https://cache.nixos.org'...
error: 1 dependencies of derivation '/nix/store/c3yf26w8v21zymdc9r3kw36icjbfp5q6-nixos-system-server-test.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sdng5w6p7lzc34lchp7nv9llypfggvn1-nixos-system-server-test.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qaly6qcgrx3z3xfyp9fa0ydd38p1si7c-nixos-test-driver-forgejo-mysql.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kzvz8m4cd9dh5jyn5xh2yq27rkxc3i0a-nixos-test-driver-forgejo-postgres.drv' failed to build
error: 1 dependencies of derivation '/nix/store/psrrxa85f4cbb0pjwl25498yrhnzr6rh-nixos-test-driver-forgejo-sqlite3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gax0bahlb0yvqg44xhk38n2bqwrfw3ql-vm-test-run-forgejo-mysql.drv' failed to build
error: build of '/nix/store/axqmymdy5dg3a26m6v8zqg0x3qi347w3-vm-test-run-forgejo-postgres.drv', '/nix/store/gax0bahlb0yvqg44xhk38n2bqwrfw3ql-vm-test-run-forgejo-mysql.drv', '/nix/store/z5xk44pqlga1pkj5adrwmd6vw23ifdaa-vm-test-run-forgejo-sqlite3.drv' failed
```

These choices are not really choices, but are automatically forcefully negated:

```
[…]
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n]
[…]
```

While running `nix-build --attr pkgs.forgejo.passthru.tests` I get quite the same errors.

PS: I'm not sure how to handle this, but I figured it's better to notify someone than to not do anything about it. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilylange — CHANGES_REQUESTED** [review]
You have to remove the patch that no longer applies (because it's part of the release) first, before running `nix-update` (or the `passthru.updateScript`):

```diff
diff --git a/pkgs/by-name/fo/forgejo/package.nix b/pkgs/by-name/fo/forgejo/package.nix
index 89ed3f098178..5da7541aecfc 100644
--- a/pkgs/by-name/fo/forgejo/package.nix
+++ b/pkgs/by-name/fo/forgejo/package.nix
@@ -65,12 +65,6 @@ buildGoModule rec {
 
   patches = [
     ./static-root-path.patch
-    # Fix TestAddRecursiveExclude go test.
-    # This will be part of the upcoming v7.0.5 release at which point this needs to be removed again.
-    (fetchpatch {
-      url = "https://codeberg.org/forgejo/forgejo/commit/f01dc4b271f54201e60a7c795d784813eac3f7ce.patch";
-      sha256  = "sha256-1lPLVHBad+Fmk+6EFXKuMnmDUl5BkEYJuMkTPfdrCgU=";
-    })
   ];
 
   postPatch = ''
```

**Comment by vrifox** [comment]
@emilylange Oh, I see. Hopefully, everything should be working properly now.

PS: Thanks for not just applying it, I learned quite a lot. :)

**Comment by vrifox** [comment]
Oh, I may have done something wrong again. I am not familiar with the GitHub review process.

**Comment by emilylange** [comment]
@ofborg build forgejo

**Review by emilylange — APPROVED** [review]
Thanks!

**Comment by adamcstephens** [comment]
❯ nix-build -A forgejo.passthru.tests --argstr system aarch64-linux
/nix/store/icy4n8nfxbn7m978l4qkl2hzz3bw8zmm-vm-test-run-forgejo-mysql
/nix/store/ryhv2v4ybq8566j5h53y1hqxxdrs55sf-vm-test-run-forgejo-postgres
/nix/store/5z632wcjrz424ywcg0a739a65i7gjwkc-vm-test-run-forgejo-sqlite3

**Pull request merged**
