### PR TITLE
nodejs: 6.14.3 -> 6.14.4

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by adisbladis** [comment]
@GrahamcOfBorg build nodejs-10_x nodejs-6_x

**Comment by adisbladis** [comment]
It looks like nodejs 10.10.0 requires a newer version of libuv.
This needs to go through staging because of the massive rebuilds caused by a libuv upgrade.

**Comment by marsam** [comment]
Removing "10.9.0 -> 10.10.0" since requires https://github.com/NixOS/nixpkgs/pull/45562 and a bit of work

**Comment by adisbladis** [comment]
@GrahamcOfBorg build nodejs-6_x

**Comment by samueldr** [comment]
Backported to 18.09.

[release-18.09 ad5046d8b82] nodejs: use https for downloading
 Date: Mon Sep 10 22:28:05 2018 -0500
 1 file changed, 1 insertion(+), 1 deletion(-)

[release-18.09 81969394b40] nodejs-6_x: 6.14.3 -> 6.14.4
 Date: Mon Sep 10 22:28:20 2018 -0500
 1 file changed, 2 insertions(+), 2 deletions(-)

**Pull request merged**
