### PR TITLE
python3Packages.tensorflow_2: 2.3.0 -> 2.3.1

### PR DESCRIPTION
**Pull request by OmnipotentEntity**
###### Motivation for this change

Update to latest version of Tensorflow (owing to memory leaks and closed CVEs)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OmnipotentEntity** [comment]
Because ML software in nix is currently in an awful state, I fully expect everything to break on this point release update, because of course it will.

I have tested only that it builds with CUDA 11, and that the derivation has the correct sha for the non CUDA build.

The removed patch was removed because it is merged in this version.

**Review by jonringer — COMMENTED** [review]
To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
```
<pkg-name>: <subject-line>
```
for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

in your case, the commit message should be:
```
python3Packages.tensorflow_2: 2.3.0 -> 2.3.1
```

**Comment by jonringer** [comment]
> Because ML software in nix is currently in an awful state, I fully expect everything to break on this point release update, because of course it will.

ML software in general is in an awful state. There's reasons why Anaconda is a multi-million dollar company, and it's main focus is just making ML not suck.

**Comment by jonringer** [comment]
LGTM after commit message changes

```
https://github.com/NixOS/nixpkgs/pull/104400
4 packages built:
python37Packages.mask-rcnn python37Packages.tensorflow_2 python38Packages.mask-rcnn python38Packages.tensorflow_2
```

**Comment by OmnipotentEntity** [comment]
> in your case, the commit message should be:
> 
> ```
> python3Packages.tensorflow_2: 2.3.0 -> 2.3.1
> ```

d'oh.  Fixed.

**Pull request merged**
