### PR TITLE
Compton: Init at 0.1_beta2

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Motivation for this change
Needed Compton for a rice.

###### Things done
Packaged Compton 0.1_beta2, couldn't build the doc.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
I think compton is available in nixpkgs under the new name picom

**Comment by SCOTT-HAMILTON** [comment]
Oh. Sorry, didn't noticed. Also this one isn't upstream Compton, it's a fork. But it provides a new blur method. Should maybe rename it compton-kawase. (name of the new blur method). But in that case I'm not sure if nixpkgs is the right place for it.

**Comment by jtojnar** [comment]
Yeah, it was renamed in https://github.com/NixOS/nixpkgs/pull/74831

**Comment by jtojnar** [comment]
For dual-kawase, there is this pull request against picom: https://github.com/yshui/picom/pull/382

**Comment by Philipp-M** [comment]
Anyone interested in using a kawase-blur-activated version can simply use an overlay like this:
```nix
{
  nixpkgs.overlays = [
    # add dual kawase blur and rounded corners to picom
    (self: super: {
      picom = super.picom.overrideAttrs (old: {
        src = builtins.fetchTarball {
          url = "https://github.com/ibhagwan/picom/archive/82ecc90b51fa2489d26ef3f08abe1f06efcb53d8.tar.gz";
          sha256 = "0pk1711kd6qqjhghrc73ldjl0m82p53yiiz5acyxvaw55hvm558h";
        };
      });
    })
  ];
}
```
Sooner or later it will be merged to master anyway so I think we should stick with the mainline picom and probably close this PR?

**Comment by SCOTT-HAMILTON** [comment]
Fair enough, I close it.

**Pull request closed without merging**
