### PR TITLE
speedometer: init at 2.8

### PR DESCRIPTION
**Pull request by Baughn**
###### Motivation for this change

Adds a useful bandwidth monitoring CLI tool.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Something's up with how the 'speedometer' program is made (the one without the .py extension):

```
$ ./result/bin/speedometer
Traceback (most recent call last):
  File "/nix/store/rya13rvcr49p2hsnv099143dh7rwam6m-speedometer-2.8/bin/.speedometer-wrapped", line 8, in <module>
    from speedometer import console
  File "/nix/store/rya13rvcr49p2hsnv099143dh7rwam6m-speedometer-2.8/bin/speedometer.py", line 2
    export PATH='/nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14/bin:/nix/store/rya13rvcr49p2hsnv099143dh7rwam6m-speedometer-2.8/bin:/nix/store/i5ig950zqwln4qi8wfaivgp3bjzzl3jz-python2.7-setuptools-38.2.5/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax
```

**Comment by Baughn** [comment]
Agreed. That happened when I rebased it on top of master, however; it worked perfectly on the installed commit. I'm trying to track it down.

**Comment by Baughn** [comment]
The script is broken by commit d945b3e53b14b7e09229e26d5e343482be1dd3e5... somehow.

**Comment by Baughn** [comment]
Two wrapper scripts. One of them works:
```
#! /nix/store/ski5znw2b8bj5qnsncrcq6128hkrwgvq-bash-4.4-p12/bin/bash -e
export PATH='/nix/store/9n2npaz7xy8b4q0a8k28nr3sjzfy625i-python-2.7.14/bin:/nix/store/jw95yh771yqpqkzwr1f6vkwm2790cknv-speedometer-2.8/bin:/nix/store/vq33bxxy9hyv2cj7w0sxlhg3rj0px0kc-python2.7-setuptools-36.7.1/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/jw95yh771yqpqkzwr1f6vkwm2790cknv-speedometer-2.8/bin/.speedometer-wrapped"  "${extraFlagsArray[@]}" "$@"
```

And one of them doesn't.
```
#! /nix/store/nkq0n2m4shlbdvdq0qijib5zyzgmn0vq-bash-4.4-p12/bin/bash -e
export PATH='/nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14/bin:/nix/store/rya13rvcr49p2hsnv099143dh7rwam6m-speedometer-2.8/bin:/nix/store/i5ig950zqwln4qi8wfaivgp3bjzzl3jz-python2.7-setuptools-38.2.5/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/rya13rvcr49p2hsnv099143dh7rwam6m-speedometer-2.8/bin/.speedometer-wrapped"  "${extraFlagsArray[@]}" "$@"
```

As far as I can tell, they're identical.

**Comment by Baughn** [comment]
...wait a second, that's not bash. Why is Python attempting to execute a bash script?

**Comment by Baughn** [comment]
Okay! I think I've figured it out. In short...

Speedometer, upstream, ships with only one meaningful file: speedometer.py, which is what should be packaged as an application. The application is named speedometer. So far, so good, but buildPythonApplication creates two additional files: .speedometer-wrapped and speedometer. The former is a python script wrapping speedometer.py, the latter is a bash script wrapping .speedometer-wrapped.

(At least, I'm assuming that's what does it. Something seems to have parsed speedometer.py in a complex way in order to create it, which is worrying.)

.speedometer-wrapped runs `from speedometer import console`, and that's where it all goes pear-shaped. Python imports prefer files without extension to .py files, so it attempts to import the *bash script*, but it prefers .pyc files to everything else -- which is why this worked prior to commit d945b3e.

I don't think name clashes of this sort are uncommon, so probably that commit should be reverted until the bug is fixed. @FRidh, thoughts?

**Comment by FRidh** [comment]
The `setup.py` is incorrect:
```
    35     'scripts': ['speedometer.py'],
    36     'entry_points': {
    37         'console_scripts': ['speedometer = speedometer:console'],},
```
They create a console script even though the file is already marked as to being installed as a script.

**Comment by Baughn** [comment]
Ah, I see. I'll report it upstream. :)

**Comment by FRidh** [comment]
@Baughn are you going to fix this PR or wait for a new release?

**Comment by Baughn** [comment]
Well, I was hoping for a quick fix from the author, but he seems to be AWOL. Not sure what to do now... fork the repo, maybe.

**Comment by FRidh** [comment]
For in here you could remove the console script line.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build speedometer

**Pull request merged**
