### PR TITLE
linux_testing_bcachefs,bcachefs-tools: 20190123

### PR DESCRIPTION
**Pull request by eadwu**
###### Motivation for this change
Turns out the version have to be in sync in order for `mount -t bcachefs` to work, sad 2 days. `bcachefs format --encrypted` is still broken so yeah.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg test bcachefs

**Comment by hyperfekt** [comment]
How is encrypted format broken for you? I just formatted with encryption, unlocked and mounted so I'm not sure what the problem is. Are you referring to #32279?

**Comment by eadwu** [comment]
Yep, #32279 is pretty much what happened.

**Comment by hyperfekt** [comment]
How tested is this bcachefs version?
It gets stuck on fdatasync for me when trying to install NixOS on it.

**Comment by eadwu** [comment]
I'm running it fine right now, albeit with some changes currently, manually made a patch for the latest kernel stable version (`4.20.7`) since the `bcachefs` repository is somewhat behind on the latest stable. Personally, I tested `linux_testing_bcachefs` before I made the PR, since `bcachefs-tools` and `bcachefs` were out of sync beforehand.

**Comment by hyperfekt** [comment]
Is there a chance you can try to replicate koverstreet/bcachefs#16? If it doesn't occur without encryption you could cherry-pick #30333 (which isn't needed in initramfs and thus only necessary on the ISO used to install).

**Comment by hyperfekt** [comment]
Note that the commit the kernel is picked from has since been amended, as such
```
diff --git a/fs/bcachefs/btree_gc.h b/fs/bcachefs/btree_gc.h
index 1905acfa028a..8af5f841a537 100644
--- a/fs/bcachefs/btree_gc.h
+++ b/fs/bcachefs/btree_gc.h
@@ -109,7 +109,7 @@ static inline bool gc_visited(struct bch_fs *c, struct gc_pos pos)
 
        do {
                seq = read_seqcount_begin(&c->gc_pos_lock);
-               ret = gc_pos_cmp(pos, c->gc_pos) < 0;
+               ret = gc_pos_cmp(pos, c->gc_pos) <= 0;
        } while (read_seqcount_retry(&c->gc_pos_lock, seq));
 
        return ret;
```

**Comment by eadwu** [comment]
I'll try tonight when I have more spare time, though the kernel issue doesn't really affect me right now since I have a patch containing all the commit diffs up to the previous revision (before the amend). As for bumping the revision on nixpkgs, I think it should be safe to assume that a new target for `bcachefs{-tools}` should come out relatively soon.

**Comment by hyperfekt** [comment]
Looks like people should refrain from using zstd for now, see the linked issue. I thought it was just  something weird about my system but looks like that is at fault - I don't think you have to reproduce now that we've found the factor.

**Pull request merged**
