### PR TITLE
Clightning 23.08 clnrest patch

### PR DESCRIPTION
**Pull request by chrisguida**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonasnick — APPROVED** [review]
I can confirm that this PR makes the [nix-bitcoin](https://github.com/fort-nix/nix-bitcoin) test suite pass.

With just #253310, clightning shuts itself down:

```
systemd[1]: Starting clightning.service...
lightningd[21903]: /usr/bin/env: 'python3': No such file or directory
lightningd[21883]: INFO    plugin-clnrest.py: Killing plugin: exited before replying to getmanifest
lightningd[21883]: **BROKEN** plugin-clnrest.py: Plugin marked as important, shutting down lightningd!
```

With this PR, the clnrest plugin is disabled at runtime:

```
INFO    plugin-clnrest.py: Killing plugin: disabled itself: No module named 'gunicorn'
```

**Comment by prusnak** [comment]
Please rebase on top of master. 

Make sure the commit message starts with: "clightning: "

**Comment by chrisguida** [comment]
Rebased and amended.

**Comment by vincenzopalazzo** [comment]
If we are going to merge this version, we should disable the clnrest plugin

**Comment by chrisguida** [comment]
@vincenzopalazzo it disables itself

**Comment by vincenzopalazzo** [comment]
Fine @chrisguida

**Pull request merged**
