### PR TITLE
Add libgee_0_8 and valadoc-unstable

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change
- libhttpseverywhere and valadoc which I am currently packaging require this specific version of libgee.
- valadoc is needed by libhttpseverywhere as well
  ###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Is it necessary to name the attribute of valadoc `valadocUnstable`?

**Comment by sternenseemann** [comment]
Oh, I completely forgot `meta`, gonna fix that.

**Comment by Mic92** [comment]
I think valadoc as attribute is fine, because there is no stable version yet

**Comment by sternenseemann** [comment]
Okay, I added meta info for valadoc and renamed my maintainer handle (I have renamed my github account).

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
