### PR TITLE
Set ALSA_PLUGIN_DIR to mindustry

### PR DESCRIPTION
**Pull request by leiserfg**
Without it, there is no audio.
I tested adding the same variable locally in a wrapper and it works as intended.

### CODE REVIEW

**Comment by leiserfg** [comment]
Fixes #167915

**Review by Mindavi — APPROVED** [review]
Diff LGTM

**Comment by Artturin** [comment]
Please follow our commit convention described in CONTRIBUTING.md

**Comment by leiserfg** [comment]
@Artturin is this the correct format for the message?

**Review by fgaz — APPROVED** [review]
On my machine the audio works both with and without this patch, but if other setups need it then let's merge!

The commit message is ok now

**Pull request merged**
