### PR TITLE
rustc: 1.61.0 -> 1.62.0

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Built fd, firefox, and thunderbird on x86_64-linux.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FliegendeWurst** [comment]
I think `pkgs/development/compilers/rust/1_62.nix` is missing?

**Comment by alyssais** [comment]
> I think `pkgs/development/compilers/rust/1_62.nix` is missing?

Yep, thanks.

**Comment by zowoq** [comment]
Built `fd` on `x86_64-darwin`. (rebased on master)

**Comment by mweinelt** [comment]
Firefox and Firefox-ESR are looking good.

**Comment by vcunat** [comment]
So, what do you usually do with rust packages that regress on rustc update?  I see cargo-deb, git-branchless, rbspy, ruffle, rustracer, sequoia.

**Comment by Mic92** [comment]
I would say, see if there is an update to these otherwise mark them as broken and ping the maintainer.
Rust usually does not have many backwards compatibility problems so packages that break after an update are probably way behind in maintenance.

**Comment by vcunat** [comment]
OK, let me start by pinging `.meta.maintainers` to have a look.  The update and breakage are already contained in nixpkgs master and corresponding three channels.
- [ ] `cargo-deb`: @Br1ght0ne
- [ ] `git-branchless`: @msfjarvis, @nh2, @hmenke
- [ ] `rbspy`: @viraptor
- [ ] `ruffle`: @GovanifY
- [ ] `rustracer`: @jagajaga
- [ ] `sequoia`: @minijackson, @doronbehar

**Comment by msfjarvis** [comment]
`git-branchless` test failure is unrelated to the rustc bump, I've created https://github.com/NixOS/nixpkgs/pull/182370 to fix it.

**Comment by viraptor** [comment]
I raised an issue upstream for `rbspy` https://github.com/rbspy/rbspy/issues/368
If there's no quick response, I'll try to fix them myself. One problem is trivial, the other needs a bit more time.

**Comment by viraptor** [comment]
`rbspy` fix by patch backport in https://github.com/NixOS/nixpkgs/pull/182560

**Pull request merged**
