### PR TITLE
python3Packages.pytest-aiohttp: 0.3.0 -> 1.0.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
[1310646](https://github.com/NixOS/nixpkgs/pull/158848/commits/1310646b430c378f8242e5197ece1e79f5e139d7) is probably needed on staging anyway.

**Comment by dotlambda** [comment]
I put `pytest` in `propagatedBuildInputs` cause wie don't have multiple versions of pytest anymore 🥳

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 158848 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>azure-cli</li>  </ul></details>

**Comment by trofi** [comment]
Bisect claims commit e06dae598a5b88b99fa0334f0e09cf41eeb1fdbf `python3Packages.pytest-aiohttp: 0.3.0 -> 1.0.3` broke `home-assistant` tests in `staging` and `staging-next`:

```
$ nix build -f. home-assistant -L
...
homeassistant> ERROR tests/helpers/test_template.py::test_undefined_variable - assert not fr...
homeassistant> ERROR tests/util/test_timeout.py::test_simple_global_timeout_freeze_with_executor_job
homeassistant> ERROR tests/util/test_timeout.py::test_simple_zone_timeout_freeze_without_timeout_cleanup
homeassistant> ERROR tests/util/test_timeout.py::test_simple_zone_timeout_freeze_without_timeout_cleanup2
homeassistant> ============== 1863 passed, 1362 warnings, 1082 errors in 17.59s ===============
```

**Comment by mweinelt** [comment]
Yep, I got to the same bisect result. Posted this to the matrix room earlier. Will need to do a packageOverride in home-assistant to resolve this.

**Pull request merged**
