### PR TITLE
darwin.cctools: 895 -> 927.0.2

### PR DESCRIPTION
**Pull request by virusdave**
Update the version of `cctools` on darwin.  The older version fails
to work on some modern packages, such as `bazel 1.1`.

###### Motivation for this change
Latest `bazel` package builds, but doesn't work at runtime on darwin, due to this dependency.  When i attempted rerunning the runtime failures using the (newer) system cctools binaries from 927.0.2, they work fine, hence this update PR.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] (*) Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

(*) This command succeeded after the rebase onto `staging`, but i don't believe it did anything interesting.  It certainly didn't build any derivations.

###### Notify maintainers

cc @matthewbauer

### CODE REVIEW

**Comment by FRidh** [comment]
please rebase onto staging

**Comment by virusdave** [comment]
@FRidh done.

**Comment by virusdave** [comment]
Any thoughts on this?

**Comment by FRidh** [comment]
Thanks. I don't know anything about Darwin packages so probably best is to wait for or ping Darwin maintainers that are interested in this.

**Comment by virusdave** [comment]
Friendly ping for @matthewbauer also @alyssais and @volth , "recent" committers.  Would love to get this landed soon if possible.

**Comment by virusdave** [comment]
@FRidh I've pinged all the maintainers and folks who have "recently" changed this derivation, but with no response.  Suggestions on who to ping now / how to get this merged?

**Comment by veprbl** [comment]
@virusdave This PR appears to be a desirable update, however, nixpkgs is a community-driven project and maintainers are volunteers who work on their schedule. I believe, @matthewbauer is the most knowledgeable for reviewing this PR, so let's wait for what he has to say.

If you would like to help us with reviewing the PR, please document carefully what steps did you take to validate your change (we are looking to ensure that nothing is broken by this). From my personal experience, seeing that you did your "homework" helps maintainers to prioritize reviewing your PR over other work.

**Review by LnL7 — COMMENTED** [review]
I don't have experience with bumping cctools so I'm not sure if the version should match the rest of the stdenv and apple SDKs. In which case it might require more testing, other then that it looks good to me.

**Comment by matthewbauer** [comment]
Looks good, have included a few misc iOS fixes on top of it.

**Pull request merged**
