### PR TITLE
steam: update generated runtime dependencies

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

The referenced zenity URL wasn't valid anymore:

```
trying http://repo.steampowered.com/steamrt/pool/main/z/zenity/zenity_3.4.0-0ubuntu4+steamrt2+srt6_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Hmm, so they depub binaries published there? That's a pity, as it effectively breaks users - we now need to worry about backporting this to 20.03 as well I guess?

Can you send them an email, and ask them nicely if they can not do that? ;-)

**Comment by Atemu** [comment]
Yup, I just ran into this while trying to upgrade 20.03.

Does it only affect zenity or are there other packages also affected?

I spot checked a few of 20.03's derivations and, while most of my samples weren't in Steam's repos anymore, they were still available on the abbradar mirror.

Is there any reason why we don't backport changes to runtime-generated.nix to stable in general? (8bd3cf22c2b7f42c4e30b81c5d9c7dcc57d43b92, 877baac95becce52d898642bda8d8d9ade3bd542 and 467a987f0be457683001c38c24c50aa71f58ae4b)

**Comment by Atemu** [comment]
I ran a quick little script on all `.deb`s in my Nix store to find out which ones can't be built anymore:  

```bash
for deb in /nix/store/*.deb ; do nix show-derivation "$deb" | jq 'keys | .[0]' -r ; done | while read drv ; do nix-build --check "$drv" || echo "$drv" >> /tmp/broken ; done
```

```
"/nix/store/90fjshgnbdwf8zkirlsi0d40wslcwnza-libxcb-dri2-0.deb.drv"
"/nix/store/2qzhpphh8a18ql7klgp1cfbgnrga2xbk-libxcb-shape0.deb.drv"
"/nix/store/77alsjgckkhjh5rcrsc84dq57xjkampx-libxcb-xinerama0.deb.drv"
"/nix/store/5fwx5w634v7q9gf5h9qyvhci00yw5rnc-libpixman-1-0.deb.drv"
"/nix/store/61s9fqyvzidz6qn60psy9ddpdx4wgz5p-libldap-2.4-2.deb.drv"
"/nix/store/9zby5xjsh3qcjc6ygjbrk2qv65dzkwms-libhcrypto4-heimdal.deb.drv"
"/nix/store/0bfn9shya6q9x8izi19myzgih0ckiyqf-libgpg-error0.deb.drv"
"/nix/store/an2zg1s550vdahfvx5swj4fqdh4nq50g-libkrb5support0.deb.drv"
"/nix/store/4cbw1pzqz4k8wgqq3ahiajfh17rfr3n2-libxcb-xvmc0.deb.drv"
"/nix/store/5kjlg35c6xiwdsa9z1jz9bwj28rbkjgh-libcg.deb.drv"
"/nix/store/ddzb7knl08244km2h0nrm7w7kph4x8z3-libsdl2-mixer.deb.drv"
"/nix/store/10rc69xvrbmpd7jk0bkii43zllda31v7-libavahi-common3.deb.drv"
"/nix/store/09qd0v7dbp70wgy0lxy3kmvj5k0h7nqh-libasyncns0.deb.drv"
"/nix/store/8s16qbp3k19rjscsh7qgny4h9w28slsk-libasound2-plugins.deb.drv"
"/nix/store/61yh8l49qlih42wx2sq8d5bbx2widnp3-libspeexdsp1.deb.drv"
"/nix/store/f3rdxal48amisys413vfq5zf0yxzy2x9-libgnutls26.deb.drv"
"/nix/store/gngq8xjblivrxrwcyxfibfknxkgbswxj-libcomerr2.deb.drv"
"/nix/store/1z55hf9zmh05cd273gzbcfd25i80nd23-libsqlite3-0.deb.drv"
"/nix/store/6mhfdxw5yqq2w44zfvm1h3xy4riwc7vz-dconf-gsettings-backend.deb.drv"
"/nix/store/4kj1qkf8i0iigqbp29mhpl0675h6mhvn-libvorbis0a.deb.drv"
"/nix/store/1llf5z7a4xml03ls5razhi01h7l1pwmj-libnettle6.deb.drv"
"/nix/store/4dyn20v5rywav47w4yask1jczc6ycf3g-libgudev-1.0-0.deb.drv"
"/nix/store/39yv2qkzgi0jlvyaqg6mjzs94k6zszh3-libxcb-dri3-0.deb.drv"
"/nix/store/7ykzrsrh1pl9rg4rqzg4glv170dngjsw-libmikmod2.deb.drv"
"/nix/store/g9zg1ixklyrxwrgb7qfaz7qkmh7l3085-libtasn1-3.deb.drv"
"/nix/store/5rfv9kmqiv8d2rsn5inz66jsiwq10yw4-libxcb-dri2-0.deb.drv"
```

**Comment by mweinelt** [comment]
> Is there any reason why we don't backport changes to runtime-generated.nix to stable in general? 8bd3cf2, 877baac and 467a987)

I don't know of any, better backport those and have a non-working package.

**Comment by prusnak** [comment]
Was this backported to 20.03?

**Comment by mweinelt** [comment]
No, please do, I'm currently otherwise occupied.

**Comment by prusnak** [comment]
Backport to 20.03 in https://github.com/NixOS/nixpkgs/pull/86619

**Comment by tadfisher** [comment]
Why don't we use the `steamrt-images` snapshots hosted here: https://repo.steampowered.com/steamrt-images-scout/snapshots/

It should be a lot easier to maintain going forward, as we would just dump the image in a directory instead of needing to fetch each steamrt package individually.

**Pull request merged**
