### PR TITLE
mathoid: init at 0.7.2

### PR DESCRIPTION
**Pull request by michaelpj**
`mathoid` is a service that renders mathematical formulae on the
server-side. As such it can be used to e.g. prerender MathJax formulae
rather than relying on doing so on the client. This is very useful if
you want to include them in a non-webpage format.

Of course one does not just Add A Single Node Package. I ran `generate.sh` and it updated various things a little bit, but I think that should be fine.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
isn't it possible to just split into different commits the mathoid update from the rest  via `git add -p` for instance ? would make reverting this peculiar package easier or the node update easier. You may even not want to include the rest of node updates.

**Comment by michaelpj** [comment]
That would require me to know which (transitive) dependencies are the mathoid ones. I'm not sure there's any way for me to know that?

FWIW this seems to be what's happened historically when people have added new node packages.

**Comment by teto** [comment]
another way would be to run an update first, commit and then rerun the update with your commit. One could assume no update in-between.
If node maintainers are fine without the change, then that's ok, I was just trying to increase your odds :p

**Comment by michaelpj** [comment]
I'm no longer using this.

**Pull request closed without merging**
