### PR TITLE
exiv2: enabling tests for real

### PR DESCRIPTION
**Pull request by mmahut**
##### Motivation for this change

Fixes #67453, which disabled all tests by mistake, given I have assumed ``doCheck`` defaults to true if tests are found.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]
LGTM, as soon as the darwin check passes.

**Comment by mmahut** [comment]
Looks like darwin is stuck.

@GrahamcOfBorg build exiv2

**Comment by mmahut** [comment]
@worldofpeace now, the tests are failing on darwin instead of aarch64.

**Comment by mmahut** [comment]
@GrahamcOfBorg build exiv2

**Comment by mmahut** [comment]
@GrahamcOfBorg build exiv2

**Comment by mmahut** [comment]
@GrahamcOfBorg build exiv2

**Comment by mmahut** [comment]
@GrahamcOfBorg build exiv2

**Comment by mmahut** [comment]
Ok, last try and I disable the tests of darwin :)

**Comment by mmahut** [comment]
@GrahamcOfBorg build exiv2

Ok, last try and I disable the tests of darwin :)

**Comment by mmahut** [comment]
@GrahamcOfBorg build exiv2

**Pull request merged**
