### PR TITLE
neovide: 0.12.2 -> 0.13.0

### LINKED ISSUE #312627: Update request: neovide 0.12.2 → 0.13.0
- Package name: neovide
- Latest released version: 0.13.0

- Current version on the unstable channel: 0.12.2
- Current version on the stable/release channel: 0.11.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

- @ck3d 

-----

Note for maintainers: Please tag this issue in your PR.

---
*As an additional note, I am currently working on updating Neovide myself. Part of my plans this summer are to begin giving at least *two* contributions to Nix/NixOS/Nixpkgs each week. I intend to begin maintaining Neovide as part of this goal. Gotta figure out how to A.) apply as a maintainer and B.) figure out if I'm even eligible.* 🙂 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by PriceHiller**
Part of an effort by me over this summer to contribute at least twice a week to NixOS/Nixpkgs/Nix.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---
- Closes #312627

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ck3d** [comment]
Thanks a lot for the PR. It compiles, but it depends on nvim 0.10.0. We should merge this PR after nvim 0.10.0 is availble in nixpkgs.

**Comment by PriceHiller** [comment]
So we're just tracking https://github.com/NixOS/nixpkgs/pull/311047 then?

**Comment by drupol** [comment]
hey!

Thanks for your first PR, great initiative!
I'm inclined to merge this as-is since #311047 is merged, but it seems that the builds on Darwin archs are broken.

Could you investigate a bit? Or update `meta.platforms` accordingly?

Thanks!

**Comment by ck3d** [comment]
Since NixOS 24.05 will be branched soon, I will merge this PR.

**Comment by drupol** [comment]
@ck3d Good!

@PriceHiller or @ck3d Could you investigate on the build failures in a followup PR ?

**Comment by PriceHiller** [comment]
I can take a look later today as time permits. This weekend is turning out to be busier than I anticipated 🙃

**Comment by drupol** [comment]
Great, thank you :+1:

**Comment by PriceHiller** [comment]
@drupol 

After investigating I'm unsure if Neovide has actually been successfully building on `x86_64-darwin` at all. It seems it has had successful builds on `aarch64-darwin` in the past, but the current check is [still pending](https://logs.ofborg.org/?key=nixos/nixpkgs.312630) (?). I'm not too sure how OfBorg works, so I could very well be wrong.

Looking back towards past work on Neovide, the bump from `0.12.1` -> `0.12.2` also failed on `x86_64-darwin` ([See here](https://github.com/NixOS/nixpkgs/pull/284680/checks?check_run_id=20965223762)).

There was some work done to support `aarc64-darwin` though [here](https://github.com/NixOS/nixpkgs/pull/279185).

@ck3d would you be ok with removing `x86_64-darwin` as a supported platform? It seems to have never been really supported in the first place.

Again, not sure what's up with `aarch64-darwin` with OfBorg -- could be just stuck in queue?

**Comment by ck3d** [comment]
I create PR #312936 to remove x86_64-darwin from supported platforms.

**Comment by kirillrdy** [comment]
after this PR neovide doesn't fork by default anymore :shrug: 

running `neovide --fork` works

**Comment by kirillrdy** [comment]
ah i see from release notes

```
The --fork option has been reversed, and --no-fork is now the default. If the old behaviour is desired, you can set the environment variable NEOVIDE_FORK=1
```

**Pull request merged**
