### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Waiting for an evaluation. After that this should go in.
https://hydra.nixos.org/jobset/nixpkgs/staging-next

**Comment by FRidh** [comment]
@vcunat looks like https://github.com/NixOS/nixpkgs/pull/44083 was the culprit. Let's see what needs to be done for @GrahamcOfBorg to prevent merging mass-rebuilds, because this is getting tiring.

**Comment by vcunat** [comment]
Yeah, that one is large, though it has < 5k according to Borg (across all three platforms), so it's probably not the only one.  I agree it's tiring, because of delaying Hydra by days.  I had assumed that those red labels from Borg would be enough for people to notice.

**Comment by vcunat** [comment]
We finally got a staging-next evaluation with new master, so I cancelled those "trunk" jobs and hopefully we can merge soon, getting over this.

**Comment by FRidh** [comment]
@vcunat merged, so we can cancel the current nixpkgs trunk jobs.

**Comment by vcunat** [comment]
I did that.  This week I'm most worried about getting a `trunk-combined` evaluation &ndash; there have been at least a dozen attempts during the past few days but no success, and the channel is at least a week old ATM.

**Pull request merged**
