### PR TITLE
geoclue2: correct sysconfdir

### LINKED ISSUE #52512: geoclue fails to start "Failed to load configuration file 'etc/geoclue/geoclue.conf'"
## Issue description

geoclue fails to start "Failed to load configuration file 'etc/geoclue/geoclue.conf'"

```
Dec 19 01:49:38 b systemd[1]: Starting Location Lookup Service...
Dec 19 01:49:38 b .geoclue-wrappe[14819]: Failed to load configuration file 'etc/geoclue/geoclue.conf': No such file or directory
Dec 19 01:49:38 b systemd[1]: Started Location Lookup Service.
Dec 19 01:49:58 b .geoclue-wrappe[14819]: soup_message_new: assertion 'uri_string != NULL' failed
Dec 19 01:49:58 b .geoclue-wrappe[14819]: soup_message_set_request: assertion 'SOUP_IS_MESSAGE (msg)' failed
Dec 19 01:49:58 b systemd[1]: geoclue.service: Main process exited, code=killed, status=11/SEGV
Dec 19 01:49:58 b systemd[1]: geoclue.service: Failed with result 'signal'.
```

### Steps to reproduce

enabling geoclue2 vai ` services.localtime.enable = true;`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.88, NixOS, 19.03pre162671.44b02b52ea6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(null): `"nixos-19.03pre162412.6449501902c"`
 - channels(root): `"nixos-19.03pre162671.44b02b52ea6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Fix #52512

###### Things done

I've rebuilt my system with this commit and I no longer see:
```
 Failed to load configuration file 'etc/geoclue/geoclue.conf': No such file or directory
```
in the output of `systemctl status geoclue`.

---
cc @jtojnar @dtzWill

### CODE REVIEW

**Comment by matthewbauer** [comment]
Shouldn't sysconfdir be /etc? Otherwise your configuration is read only.

**Comment by worldofpeace** [comment]
We currently aren't modifying/generatating this config file with a NixOS module.

**Comment by jtojnar** [comment]
Even if the NixOS module does not support configuration, users should still be able to use `environment.etc.[…]` option. Since patching it like fwupd is quite simple, I suggest we do that instead.

**Comment by worldofpeace** [comment]
> Even if the NixOS module does not support configuration, users should still be able to use `environment.etc.[…]` option. Since patching it like fwupd is quite simple, I suggest we do that instead.

Yes we can do that, but we'd also need to add
```
environment.etc."geoclue/geoclue.conf".source = "${pkgs.geoclue2}/etc/geoclue/geoclue.conf";
```
to the NixOS module.

Prior to the update to geoclue it was just reading the bundled config within its own prefix.

I actually wasn't going for an improvement.

**Comment by worldofpeace** [comment]
@jtojnar I added integrated your change

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
