### PR TITLE
nixos/anuko-time-tracker: improve module options

### PR DESCRIPTION
**Pull request by michaelshmitty**
###### Description of changes

* Remove unsafe dbinstall.php script: `dbinstall.php` is a script used for database migrations during an upgrade. It should be deleted after an upgrade. This script allows anyone to execute potentially destructive commands on the database and should not be part of a production setup. We'll handle relevant database migrations automatically using a systemd oneshot service if necessary when bumping to future versions.

* Make Nginx virtualhost configurable: This fix allows more customization of the Nginx virtualhost configuration, following the example of [monica](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/monica.nix#L199) and [bookstack](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/bookstack.nix#L197).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by michaelshmitty** [comment]
@Janik-Haag thanks in advance for your time and effort. Some module options (`virtualHost` -> `hostname`, addition of `nginx` option) have changed. I didn't consider fallbacks / deprecation warnings as I assume this is not necessary when the package / service module is still in unstable and not part of a past stable nixos release, is that correct?

**Review by Janik-Haag — COMMENTED** [review]
Changes LGTM; I'm not quite sure about the deprecation warnings, I'm going to ask in the matrix channel about that. You might want to rename the commit to something more meaning full like nixos/anuko-time-tracker: improve module options.

**Comment by michaelshmitty** [comment]
> Changes LGTM; I'm not quite sure about the deprecation warnings, I'm going to ask in the matrix channel about that. You might want to rename the commit to something more meaning full like nixos/anuko-time-tracker: improve module options.

Thanks!
There is more information in the [summary of the commit](https://github.com/NixOS/nixpkgs/pull/240954/commits/884aaa1358683e25acef3721a862eea2eb63d847) (below the first line), but I can update the first line too with your suggestion. Just wanted to make sure you saw the summary.

**Comment by michaelshmitty** [comment]
@Janik-Haag `Improve module options` is better, thanks!

**Comment by Janik-Haag** [comment]
I would change the capitalization of improve to lower case, otherwise this looks good. Matrix said we don't bother with deprecation warnings so this is good to go.

**Comment by michaelshmitty** [comment]
> I would change the capitalization of improve to lower case, otherwise this looks good. Matrix said we don't bother with deprecation warnings so this is good to go.

Done and rebased. Thanks for your time!

**Pull request merged**
