### PR TITLE
rustup: 1.26.0 -> 1.27.1

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

[Required to build with Rust 1.80.](https://github.com/rust-lang/rust/issues/127343)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Bisected the build failure on x86_64-linux to https://github.com/rust-lang/rustup/pull/3340.

**Comment by emilazy** [comment]
Maybe we should just manually bump `time` for now so `rustup` doesn’t break on unstable and figure out how to get 1.27.1 working at a later date? Although it’s slightly concerning just how old our current version is.

**Comment by emilazy** [comment]
Okay, actually this should be pretty easy to get working. Pushed a WIP that should be enough to pass tests on `x86_64-darwin`; going to see if those failures are common to the other platforms too.

**Comment by emilazy** [comment]
Tests that [only fail on `x86_64-darwin` (`sandbox = true`)](https://gist.github.com/emilazy/b8b939d85c0a4ced3ec0c584c0cd3c83):

```
    suite::cli_misc::multi_host_smoke_test
    suite::cli_misc::nightly_backtrack_skips_missing
    suite::cli_misc::rename_rls_before
    suite::cli_misc::run_rls_when_not_installed_for_nightly
    suite::cli_misc::rustc_with_bad_rustup_toolchain_env_var
```

Tests that [only fail on `aarch64-darwin` (`sandbox = relaxed`)](https://gist.github.com/emilazy/82b837a91678aad3bf6ee378c283396f) (after disabling the tests that failed previously but *without* disabling the `x86_64-darwin`‐specific failures):

```
    suite::cli_misc::rustup_failed_path_search
    suite::cli_self_upd::updater_is_deleted_after_running_rustup
    suite::cli_v2::change_override
    suite::cli_v2::install_override_toolchain_from_archive
```

All tests pass on `aarch64-linux`.

I have *no clue* why the Darwin failure sets are disjoint. Tightening the sandbox on `aarch64-darwin` to see if that makes it make any more sense.

**Comment by emilazy** [comment]
Failures on [`aarch64-darwin` (`sandbox = true`)](https://gist.github.com/emilazy/5335e7bad63a36900c600b029494c58f):

```
    suite::cli_misc::custom_toolchain_cargo_fallback_run
    suite::cli_misc::rename_rls_remove
    suite::cli_rustup::rustup_stable_quiet
    suite::cli_self_upd::update_bad_schema
    suite::cli_self_upd::updater_is_deleted_after_running_rustup
    suite::cli_v1::remove_toolchain_then_add_again
```

None of this makes much sense. Nondeterminism? Perhaps we really do need to skip tests on Darwin, after all.

**Comment by emilazy** [comment]
Yeah, running again on `x86_64-darwin`:

```
rustup> failures:
rustup>     suite::cli_exact::default_none
rustup>     suite::cli_misc::toolchains_symlink
rustup>     suite::cli_misc::version_mentions_rustc_version_confusion
rustup>     suite::cli_v2::remove_override_with_multiple_overrides
rustup>     suite::cli_v2::remove_toolchain
```

I’ll just disable tests again on Darwin.

**Comment by emilazy** [comment]
Let’s land this; it should hopefully be a simple version bump and can’t be more broken than `rustup` will be in a few days if we don’t do anything.

**Pull request merged**
