### PR TITLE
graphene-hardened-malloc: 2 -> 6

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@ofborg test hardened latestKernel.hardened

**Comment by NeQuissimus** [comment]
The object size tests do not seem to work properly

**Comment by NeQuissimus** [comment]
@ofborg test hardened latestKernel.hardened

**Comment by NeQuissimus** [comment]
I am not sure how to fix the VM tests, need help :)

**Comment by risicle** [comment]
The VM tests?

**Comment by NeQuissimus** [comment]
@risicle Check the logs for the checks that @ofborg ran

**Comment by risicle** [comment]
This looks like it's https://github.com/NixOS/nixpkgs/blob/909a4ba5fe89fe865f8321ba6cfb5a4350e6ea59/nixos/tests/hardened.nix#L40 failing to build, complaining that

```
/nix/store/cp1sa3xxvl71cypiinw2c62i5s33chlr-binutils-2.35.1/bin/ld: cannot find -lhardened_malloc
```

If you look at the changes in graphene-hardened-malloc between versions 2 and 6, the `test/simple-memory-corruption/` directory seems to have had a number of changes, notably https://github.com/GrapheneOS/hardened_malloc/commit/195bc8c92a0ab2c9c5f39e40cd0cfe4738e9f855, which among other things adds the `-lhardened_malloc` flag in question. I'm guessing here upstream decided to now explicitly link these tests against the hardened malloc lib. Which is a problem for the way the nixos hardened tests try to build/use them because we don't supply them with a built hardened_malloc lib here, instead building them as bare c programs which we will then `LD_PRELOAD` the hardened_malloc into.

I say this as someone who doesn't know much about the nixos hardened tests, I'm just saying what I see.

You could try patching out that new `-lhardened_malloc` line in `test/simple-memory-corruption/Makefile` when built from the nixos tests?

**Comment by risicle** [comment]
Come to think, should consider patching that explicit-linking out in the main package too - the `installCheckPhase` also expects a naive c executable which it then `LD_PRELOAD`s at runtime, in the process attempting to test our `preload-hardened-malloc` wrapper script. Explicitly linking the test binary kinda nullifies the effectiveness of this test.

**Comment by zzywysm** [comment]
The graphene-hardened-malloc project is now up to release 8: https://github.com/GrapheneOS/hardened_malloc/releases/tag/8

**Pull request closed without merging**
