### PR TITLE
kalibrate-rtl: unstable-2013-12-14 -> unstable-2022-02-02

### PR DESCRIPTION
**Pull request by viraptor**
###### Description of changes

Update to a more recent version. It includes darwin support as one of the features.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
cc @bjornfor @markuskowa @etu  (from gitlog)

**Comment by takeda** [comment]
Result of `nixpkgs-review pr 170703` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>kalibrate-rtl</li>
  </ul>
</details>

**Comment by takeda** [comment]
It looks like the change doesn't build under sandbox on linux:

```trying https://github.com/steve-m/kalibrate-rtl/archive/340003eb0846b069c3edef19ed3363b8ac7b5215.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   163  100   163    0     0   1024      0 --:--:-- --:--:-- --:--:--  1025
Warning: Failed to create the file /run/user/0/nix-build-source.drv-0/file:
Warning: Permission denied
^M100   836    0   836    0     0   2711      0 --:--:-- --:--:-- --:--:--  2711
curl: (23) Failure writing output to destination
error: cannot download source from any mirror
```

**Comment by takeda** [comment]
The package actually builds x86_64-linux with sandboxing enable but for some reason it nixpkgs-review fails. It looks though that the failure is on my side as it can't write to a file on my NixOS.

**Review by bjornfor — APPROVED** [review]

**Pull request merged**
