### PR TITLE
add options for build idris package

### PR DESCRIPTION
**Pull request by marcosh**
###### Motivation for this change

It could be helpful to provide additional options to `idris` commands while building, testing and install an `idris` package.

For my specific use case, I need to add a `--log` option to `idris` commands.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ x ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ x ] Ensured that relevant documentation is up to date
- [ x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Infinisil** [comment]
It might be better (though less convenient) to pass options as a list of strings instead of a string directly, such that users don't need to worry about proper escaping (can be done in the code with `lib.escapeShellArgs`).

**Comment by marcosh** [comment]
@Infinisil that seems like a nice suggestion. I updated the code and the docs accordingly

**Comment by Infinisil** [comment]
Could you squash the last commit into the first two? This looks good to merge otherwise

**Comment by marcosh** [comment]
done! Thanks @Infinisil for your feedback!

**Pull request merged**
