### PR TITLE
discord: symlink Discord to discord to be consistent

### PR DESCRIPTION
**Pull request by Artturin**
with distros such as arch

###### Motivation for this change
i have seen many new people ask why `discord` isn't working 
https://github.com/archlinux/svntogit-community/blob/a642afafb12de6b5792aaa68e3b186d63d43e783/trunk/PKGBUILD#L38

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126254` at f0adbd1d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>discord</li>
    <li>discord-canary</li>
    <li>discord-ptb</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/networking/instant-messengers/discord/base.nix:43:3:
```
   |
43 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by jonringer** [comment]
cc some discord users @ryantm @tadeokondrak @zimbatm

**Comment by ryantm** [comment]
Not a Discord app user here. I just use the browser.

**Comment by zimbatm** [comment]
I've been hit by that multiple times as well. It also makes it compatible with `nix run`.

**Pull request merged**
