### PR TITLE
nix-fallback-paths.nix: Update to 2.3.15

### PR DESCRIPTION
**Pull request by edolstra**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
This is much appreciated. Last time, @Ma27 had to improvise this part of the update https://github.com/NixOS/nixpkgs/commit/e66237af154f63998eaf45233763b2e535b78b95

**Comment by Ma27** [comment]
@edolstra doesn't this mean that we should also upgrade nixStable to 2.3.15 in here?

**Comment by edolstra** [comment]
@Ma27 Doesn't have to be in the same PR, they don't have to be in sync.

**Comment by vcunat** [comment]
Any reason why we're still waiting with the update?  I wasn't following this closely, but I at least switched my 21.05 NixOS to 2.3.15 for testing and now opened PR for the bump: https://github.com/NixOS/nixpkgs/pull/132046

**Pull request merged**
