### PR TITLE
skawarePackages.*: Summer 2022 releases

### PR DESCRIPTION
**Pull request by somasis**
###### Description of changes

Currently the execline commit is waiting on some action with regards to the [execline-man-pages/execline version mismatch](https://github.com/NixOS/nixpkgs/pull/168341#issuecomment-1170754392). As it stands the manpages [don't *exactly* match the execline-2.9.0.1 documentation](https://github.com/skarnet/execline/commit/28b89edabbd5ee76147a4aa2ccef94ab60d28c0d#diff-f37c36067a01c281dbc085e84557a8da28499206c460d70d565d3629155a4ea2R22).

Additionally, this also creates s6-portable-utils-man-pages.

https://skarnet.org/lists/skaware/1678.html
https://skarnet.org/lists/skaware/1679.html

```
233e92da966 WIP execline: 2.8.3.0 -> 2.9.0.1
23203dda5b9 skalibs: 2.11.2.0 -> 2.12.0.1
9d3fdb8bf5d s6: 2.11.1.0 -> 2.11.1.2
4d4954f5b68 mdevd: 0.1.5.1 -> 0.1.5.2
8e0a7403c0c s6-linux-init: 1.0.7.3 -> 1.0.8.0
b709ce9f389 s6-portable-utils: 2.2.4.0 -> 2.2.5.0
fcfb74fa759 s6-dns: 2.3.5.3 -> 2.3.5.4
be69068cdab s6-networking: 2.5.1.0 -> 2.5.1.1
88c72138b76 s6-rc: 0.5.3.1 -> 0.5.3.2
d99495b4d9c s6-portable-utils-man-pages: init at 2.2.5.0.1
deb7527d9e5 s6-networking-man-pages: 2.5.1.0.1 -> 2.5.1.1.1
a93a907076e s6-man-pages: 2.11.0.1.1 -> 2.11.1.1.1
1e0258ef45a execline-man-pages: 2.8.3.0.2 -> 2.9.0.0.1
fd7947bf92b s6-linux-utils: 2.5.1.7 -> 2.6.0.0
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
> As it stands the manpages [don't _exactly_ match the execline-2.9.0.1 documentation](https://github.com/skarnet/execline/commit/28b89edabbd5ee76147a4aa2ccef94ab60d28c0d#diff-f37c36067a01c281dbc085e84557a8da28499206c460d70d565d3629155a4ea2R22).

I think this is fine.  The man pages are a different package, and it doesn't make sense to hold back on important bug fixes just because the man page package hasn't released yet.  Is this the only reason this PR is a draft?

**Review by alyssais — APPROVED** [review]
Tested booting/running a system that uses execline, s6, s6-rc, mdevd, and s6-linux-init.  With the execline commit message un-WIPed this is good to merge IMO.

**Comment by somasis** [comment]
I'm away from my computer for a few days unfortunately, so I don't have the ability to amend the execline commit at the moment; that is indeed the only reason that I marked it WIP, otherwise the PR is entirely ready to go. If you want to amend it before I can get around to it later this week, feel free to. :) 

(also, I'd be curious to see that setup if you've got it posted anywhere :))

**Comment by alyssais** [comment]
> (also, I'd be curious to see that setup if you've got it posted anywhere :))

https://spectrum-os.org/git/spectrum :)

**Pull request merged**
