### PR TITLE
pythonPackages.plaid-python: init at 2.3.0

### PR DESCRIPTION
**Pull request by bhipple**
###### Motivation for this change
Using this as a library for other applications that access financial data through Plaid.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bhipple** [comment]
@GrahamcOfBorg build pythonPackages.plaid-python

**Comment by FRidh** [comment]
```
Ran 0 tests in 0.000s
```
No tests are found. Either the test runner cannot find tests and needs to be patched, or there simply are no tests in which case the tests need to be disabled. Do include a comment explaining why the tests are disabled.

**Comment by bhipple** [comment]
I spent a while trying to patch upstream's `setup.py` to run the tests, but wasn't quite able to get there.  It looks like they just run their tests via their Makefile in travis instead of using the proper python packaging tests, so I've marked it as `doCheck = false;` with a comment.

**Comment by FRidh** [comment]
Check their `tox.ini` for what to run.

**Comment by bhipple** [comment]
Ah, I see there's even a section about `py.test` in the the `python.section.md` portion of the manual.  I was able to get the unit tests running with this!  Thanks!

**Comment by FRidh** [comment]
@GrahamcOfBorg build pythonPackages.plaid-python @GrahamcOfBorg build python3Packages.plaid-python

**Pull request merged**
