### PR TITLE
wapiti: 3.0.7 -> 3.0.9

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
https://github.com/wapiti-scanner/wapiti/blob/master/doc/ChangeLog_Wapiti

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 152405` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>opsdroid</li>
  </ul>
</details>
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>agda-pkg</li>
    <li>gnome-keysign</li>
    <li>klaus (python39Packages.klaus)</li>
    <li>magic-wormhole (python39Packages.magic-wormhole)</li>
    <li>pg_activity</li>
    <li>pgcli</li>
    <li>python38Packages.cassandra-driver</li>
    <li>python38Packages.delorean</li>
    <li>python38Packages.flask-common</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.gehomesdk</li>
    <li>python38Packages.gekitchen</li>
    <li>python38Packages.gremlinpython</li>
    <li>python38Packages.humanize</li>
    <li>python38Packages.karton-mwdb-reporter</li>
    <li>python38Packages.klaus</li>
    <li>python38Packages.magic-wormhole</li>
    <li>python38Packages.maya</li>
    <li>python38Packages.mwdblib</li>
    <li>python38Packages.pgcli</li>
    <li>python38Packages.pycron</li>
    <li>python38Packages.radish-bdd</li>
    <li>python38Packages.secure</li>
    <li>python39Packages.cassandra-driver</li>
    <li>python39Packages.delorean</li>
    <li>python39Packages.flask-common</li>
    <li>python39Packages.flower</li>
    <li>python39Packages.gehomesdk</li>
    <li>python39Packages.gekitchen</li>
    <li>python39Packages.gremlinpython</li>
    <li>python39Packages.humanize</li>
    <li>python39Packages.karton-mwdb-reporter</li>
    <li>python39Packages.maya</li>
    <li>python39Packages.mwdblib</li>
    <li>python39Packages.pycron</li>
    <li>python39Packages.radish-bdd</li>
    <li>python39Packages.secure</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>tahoe-lafs</li>
    <li>terraform-compliance</li>
    <li>todoman</li>
    <li>twtxt</li>
    <li>wapiti</li>
  </ul>
</details>

**Comment by applePrincess** [comment]
Result of `nixpkgs-review pr 152405` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>opsdroid</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>agda-pkg</li>
    <li>gnome-keysign</li>
    <li>klaus (python39Packages.klaus)</li>
    <li>magic-wormhole (python39Packages.magic-wormhole)</li>
    <li>pg_activity</li>
    <li>pgcli</li>
    <li>python38Packages.cassandra-driver</li>
    <li>python38Packages.delorean</li>
    <li>python38Packages.flask-common</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.gehomesdk</li>
    <li>python38Packages.gekitchen</li>
    <li>python38Packages.gremlinpython</li>
    <li>python38Packages.humanize</li>
    <li>python38Packages.karton-mwdb-reporter</li>
    <li>python38Packages.klaus</li>
    <li>python38Packages.magic-wormhole</li>
    <li>python38Packages.maya</li>
    <li>python38Packages.mwdblib</li>
    <li>python38Packages.pgcli</li>
    <li>python38Packages.pycron</li>
    <li>python38Packages.radish-bdd</li>
    <li>python38Packages.secure</li>
    <li>python39Packages.cassandra-driver</li>
    <li>python39Packages.delorean</li>
    <li>python39Packages.flask-common</li>
    <li>python39Packages.flower</li>
    <li>python39Packages.gehomesdk</li>
    <li>python39Packages.gekitchen</li>
    <li>python39Packages.gremlinpython</li>
    <li>python39Packages.humanize</li>
    <li>python39Packages.karton-mwdb-reporter</li>
    <li>python39Packages.maya</li>
    <li>python39Packages.mwdblib</li>
    <li>python39Packages.pycron</li>
    <li>python39Packages.radish-bdd</li>
    <li>python39Packages.secure</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>tahoe-lafs</li>
    <li>terraform-compliance</li>
    <li>todoman</li>
    <li>twtxt</li>
  </ul>
</details>

**Comment by applePrincess** [comment]
In my nixpkgs-review it says
```
1 package removed:
wapiti (†3.0.7)
```
instead of update to 3.0.9.

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/152405

1 package failed to build:
opsdroid

52 packages built:
agda-pkg gnome-keysign klaus magic-wormhole pg_activity pgcli python38Packages.cassandra-driver python38Packages.delorean python38Packages.flask-common python38Packages.flower python38Packages.gehomesdk python38Packages.gekitchen python38Packages.gremlinpython python38Packages.humanize python38Packages.karton-mwdb-reporter python38Packages.klaus python38Packages.magic-wormhole python38Packages.maya python38Packages.mwdblib python38Packages.pgcli python38Packages.pycron python38Packages.radish-bdd python38Packages.secure python39Packages.cassandra-driver python39Packages.delorean python39Packages.flask-common python39Packages.flower python39Packages.gehomesdk python39Packages.gekitchen python39Packages.gremlinpython python39Packages.humanize python39Packages.karton-mwdb-reporter python39Packages.maya python39Packages.mwdblib python39Packages.pycron python39Packages.radish-bdd python39Packages.secure sourcehut.buildsrht sourcehut.coresrht sourcehut.dispatchsrht sourcehut.gitsrht sourcehut.hgsrht sourcehut.hubsrht sourcehut.listssrht sourcehut.mansrht sourcehut.metasrht sourcehut.pastesrht sourcehut.todosrht tahoelafs terraform-compliance todoman twtxt
```

**Pull request merged**
