### PR TITLE
turbo: 1.8.8 -> 1.10.7

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

turbo update
This improves the darwin situation but doesn't fix it.
I'm getting
```
 note: Undefined symbols for architecture x86_64:
       >             "_kCFURLVolumeAvailableCapacityForImportantUsageKey", referenced from:
       >                 __RNvXNtNtCslHcQMiiPZF_7sysinfo5apple4diskNtB2_4DiskNtNtB6_6traits7DiskExt7refresh in libsysinfo-55525a15d1d41d57.rlib(sysinfo-55525a15d1d41d57.sysinfo.d076754d-cgu.9.rcgu.o)
       >                 __RNvNtNtCslHcQMiiPZF_7sysinfo5apple4disk9get_disks in libsysinfo-55525a15d1d41d57.rlib(sysinfo-55525a15d1d41d57.sysinfo.d076754d-cgu.9.rcgu.o)
       >           ld: symbol(s) not found for architecture x86_64
```
and I don't know how to fix that.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@dlip let me know what you think. It improves things but it still needs a little push

**Comment by happysalada** [comment]
Actually I've found how to fix the darwin build, this is ready to go.

**Comment by happysalada** [comment]
I noticed an ofborg failure for linux. Trying to change in consequence.
If anyone has time to test linux, I'm happy to make changes.

**Comment by happysalada** [comment]
@dlip I've fixed the linux failures, it's building on all platforms now.

**Review by dlip — APPROVED** [review]

**Comment by dlip** [comment]
LGTM, i don't have a mac to test on but ill trust if it builds it will run :crossed_fingers:

**Pull request merged**
