### PR TITLE
xivlauncher: init at 1.0.0.4

### PR DESCRIPTION
**Pull request by ashkitten**
###### Description of changes

new package: https://github.com/goatcorp/FFXIVQuickLauncher

i haven't checked the buildDotnetModule changes with any other package. hopefully it doesn't break anything but testing is needed.

i'm waiting on some features before i start using this myself, so it's marked as a draft for now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
I ran nixpkgs-review on this and got the following results:

Result of `nixpkgs-review pr 169121` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>alttpr-opentracker</li>
    <li>baget</li>
    <li>depotdownloader</li>
    <li>formula</li>
    <li>netcoredbg</li>
    <li>python-language-server</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>btcpayserver</li>
    <li>discordchatexporter-cli</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>nbxplorer</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pinta</li>
    <li>ryujinx</li>
  </ul>
</details>

---

I also noticed that a decent amount of those failed (such as `depotdownloader`, `netcore-dbg`, etc) with:

```
MSBUILD : error MSB1001: Unknown switch.
Switch: --no-self-contained
```

So it looks like those may need to have an updated version of dotnet or something applied.

---

`ArchiSteamFarm` failed with:

```
Executing dotnetFixupPhase

Builder called die: makeWrapper doesn't understand the arg -p
Backtrace:
169 makeWrapper /nix/store/04pil4bjyxgkgav41n20mh0m9jg92hpj-hook/nix-support/setup-hook
6 wrapDotnetProgram /nix/store/lkrdiz6lj01ykb3ysxzd31yrp7piab0d-dotnet-fixup-hook/nix-support/setup-hook
23 dotnetFixupHook /nix/store/lkrdiz6lj01ykb3ysxzd31yrp7piab0d-dotnet-fixup-hook/nix-support/setup-hook
1373 genericBuild /nix/store/7a7viw9bwgrvj52qdirx1a8rwmc9daxx-stdenv-linux/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh
```

This makes me think that some of those quotes in the hooks may actually be necessary?

---

XIVLauncher itself failed with:

```
Executing dotnetConfigureHook
  Determining projects to restore...
/build/source/src/XIVLauncher.Common.Windows/XIVLauncher.Common.Windows.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.3) [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
/build/source/src/XIVLauncher.Common.Windows/XIVLauncher.Common.Windows.csproj : error NU1102:   - Found 1 version(s) in /nix/store/kykd1ympg7aflyhlr8iybgp2zwi3mp7m-XIVLauncher-nuget-source/lib [ Nearest version: 6.0.0 ] [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
/build/source/src/XIVLauncher.Common.Windows/XIVLauncher.Common.Windows.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64 with version (= 6.0.3) [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
/build/source/src/XIVLauncher.Common.Windows/XIVLauncher.Common.Windows.csproj : error NU1102:   - Found 1 version(s) in /nix/store/kykd1ympg7aflyhlr8iybgp2zwi3mp7m-XIVLauncher-nuget-source/lib [ Nearest version: 6.0.0 ] [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
  Failed to restore /build/source/src/XIVLauncher.Common.Windows/XIVLauncher.Common.Windows.csproj (in 2.08 sec).
/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.3)
/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj : error NU1102:   - Found 1 version(s) in /nix/store/kykd1ympg7aflyhlr8iybgp2zwi3mp7m-XIVLauncher-nuget-source/lib [ Nearest version: 6.0.0 ]
/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64 with version (= 6.0.3)
/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj : error NU1102:   - Found 1 version(s) in /nix/store/kykd1ympg7aflyhlr8iybgp2zwi3mp7m-XIVLauncher-nuget-source/lib [ Nearest version: 6.0.0 ]
  Failed to restore /build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj (in 1.98 sec).
/build/source/src/XIVLauncher.Common/XIVLauncher.Common.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.3) [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
/build/source/src/XIVLauncher.Common/XIVLauncher.Common.csproj : error NU1102:   - Found 1 version(s) in /nix/store/kykd1ympg7aflyhlr8iybgp2zwi3mp7m-XIVLauncher-nuget-source/lib [ Nearest version: 6.0.0 ] [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
/build/source/src/XIVLauncher.Common/XIVLauncher.Common.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64 with version (= 6.0.3) [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
/build/source/src/XIVLauncher.Common/XIVLauncher.Common.csproj : error NU1102:   - Found 1 version(s) in /nix/store/kykd1ympg7aflyhlr8iybgp2zwi3mp7m-XIVLauncher-nuget-source/lib [ Nearest version: 6.0.0 ] [/build/source/src/XIVLauncher.Core/XIVLauncher.Core.csproj]
  Failed to restore /build/source/src/XIVLauncher.Common/XIVLauncher.Common.csproj (in 35 ms).

```

**Comment by ashkitten** [comment]
@cole-h thanks for checking. i think it should be better now? the netcoredbg issue seems to be unrelated.

**Comment by cole-h** [comment]
Indeed, that fixed the builds (excepting netcoredbg, which I think we can ignore for now)! However, XIVLauncher does not start up for me:

```
$ XIVLauncher.Core 
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/nix/store/0pprlpf1c588qwa8zsj88gvkvvd79qnm-dotnet-runtime-6.0.3'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/nix/store/4ffxzpkrjpbifx65cb5y5wpxwz5py4ny-XIVLauncher-1.0.0.1/lib/XIVLauncher/XIVLauncher.Core.runtimeconfig.json' did not specify a framework.
  - If this should be a framework-dependent app, specify the appropriate framework in '/nix/store/4ffxzpkrjpbifx65cb5y5wpxwz5py4ny-XIVLauncher-1.0.0.1/lib/XIVLauncher/XIVLauncher.Core.runtimeconfig.json'.
```

**Comment by ashkitten** [comment]
oops, i hadn't actually tested the binary that time. it should be good now... though i'm annoyed that i have to specify `--no-self-contained` for the build stage here, while it seems to break other dotnet builds

**Comment by cole-h** [comment]
Yep, can confirm it starts up now! A bit busy until this evening, so I'll have to actually test whether or not it works sometime later tonight (or later in the week).

**Comment by goaaats** [comment]
We're still working on this quite heavily (see https://github.com/goatcorp/FFXIVQuickLauncher/milestone/1) but all of the actual game patching/starting/plugin stuff should work fine if you set `XL_NO_SAVE_PASSWORD=true`. Thanks!

**Comment by ashkitten** [comment]
this is ready for review now

**Review by cole-h — APPROVED** [review]
Works great for me! I've been able to launch and play the game as I would in Windows with this. Thanks for packaging it!

(I would like to get Ivar's eyes on the dotnet hook changes, in case they have any opinions, but everything else LGTM.)

**Review by IvarWithoutBones — APPROVED** [review]
I think the issue with dotnet's parsing of command line arguments comes from MSBuild args being delimited with colons, while dotnet arguments are done with spaces. I've tried to fix this before but couldn't find a good fix other than having a seperate `msbuildFlags` array, which is kind of a bad user experience.

Seeing how this didn't break anything in nixpkgs I'm assuming it's fine, so this looks good to me :+1: 

Result of `nixpkgs-review pr 169121` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>alttpr-opentracker</li>
    <li>baget</li>
    <li>btcpayserver</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>formula</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pinta</li>
    <li>python-language-server</li>
    <li>ryujinx</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Pull request merged**
