### PR TITLE
pythonPackages.google-cloud-*: init all 37 modules 

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

I will be doing a lot of development with google-cloud in the coming year. Wanted to make sure that all the google python modules are available. 

###### Things done

Tests are enabled for every package. All pass entirely. Compared to `azure` and `aws` python tools this is the best set of modules I have seen. No circular dependencies, `pytest` and `mock` are the only testing dependencies.

Many modules have been added. Without this python module [initialization tools I made](https://github.com/costrouc/nixpkgs-dev-tools/blob/master/python/python-package-init.py) this would have taken days.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
Google removed a `meta` package that installed all of the packages `google-cloud` is it worth creating a [meta package google-cloud](https://pypi.org/project/google-cloud/) to install all of these without having to specify them individually. Would this be worth adding?

**Comment by costrouc** [comment]
Definitely something that I would be interested looking into. You are talking about doing something similar to how `haskell` is handled in `nixpkgs`? So as of right now I can think of two issues.

1. Currently there is no pattern followed for naming python packages e.g. is it (`google-cloud-datastore` vs `google_cloud_datastore`)? This may break some peoples setups but it would allow automation of package names and searching for packages easier if we had a rule for naming package attributes and folder names. I could see `name.lowercase().replace('_', '-').replace('.', '-') `. My tool had a hard time getting the package names correct.

2. Running tests. I had to manually add all the tests and the dependencies. There are just too many ways that testing is done in python. I can't think of any solution to this problem. But if we are handling updates this might not be a problem.

I think that `1` is the main blocker. We would just need to establish a convention.

**Comment by FRidh** [comment]
1. the naming guideline is to use [normalized names](https://www.python.org/dev/peps/pep-0503/#normalized-names), but many don't follow it.
2. That we indeed cannot automate yet.

For Haskell we generate a whole package set in one file, and then have a file with overrides per Haskell/GHC version. This is something that was discussed in the past as well for Python. In the end, I gave up on that direction. For Haskell we base our package sets on the curated Stackage sets. For Python, such sets don't exist so we need to resolve a stable set first. When resolving, we need to consider all Python versions and platforms. Unfortunately, it is not possible to retrieve PyPI at a certain state, making it even harder to resolve. Now, these problems can be resolved, one by one.

What I was thinking of now was maybe a `generated.nix` and `default.nix` file per package, but I am not sure whether it is worth making this change.

**Comment by costrouc** [comment]
I know this would require a lot of rebuilds and would possibly break people's configuration but I think that getting all the python package names in `nixpkgs` normalized is a first step before update automation could be considered. 

I think that a `generated.nix` is very doable and a great idea! With correct normalized package naming the only thing [this tool](https://github.com/costrouc/nixpkgs-dev-tools/blob/master/python/python-package-init.py)  this tool misses is extra packages and `checkInputs`. `default.nix` would get a lot shorter and simpler to write.

I would be willing to work on normalizing package names.

**Comment by costrouc** [comment]
Bump. Ready for merge. Only added new packages and will allow access to the newer `google-cloud` python apis.

**Comment by costrouc** [comment]
@Mic92 showed me `nix-review` was now able to confirm that all packages work without `nix-build -A <attribute>` over and over. Ready for merge.

**Comment by costrouc** [comment]
Rebased to fix merge conflict. @FRidh is there anything that I can do to help speed up the python modules merge process? Should I ask others for reviews on python contributions? How can I help? I understand you are quite busy and I don't want to make work harder for you. I have tried to combine commits so that the review process is quicker but it doesn't always seem that works. I am committed to `nixpkgs` and I want to see it succeed.

`nix-review` has given me much more confidence in my PRs as before I was `nix-build -A ...` for each attribute manually. So I can say from this point on I will have a much greater assurance that my PRs are good.

**Comment by costrouc** [comment]
@Mic92 do you mind if I ping you on python merge requests that take awhile to merge? Usually @FRidh is the only one that gets pinged.

**Comment by Mic92** [comment]
@costrouc Since I have installed github-refined, I will see pull requests order by last update. This means I will also see older pull request that got updated. I take this list as a priority. I also look at pings but not as regular as this one. Apart from that you can also ask around in IRC. Usually it is also a good idea to keep your pull requests smaller then this one so one can review it faster.

**Comment by costrouc** [comment]
Will do in the future!

**Pull request merged**
