### PR TITLE
elm: add the platform and helpful scripts

### PR DESCRIPTION
**Pull request by abbradar**
cc @peti -- I haven't integrated this into haskell-modules, instead using overrides to add needed packages. Maybe we want to do this some other way?

TODO:
- Documentation
- A way to package elm modules? (don't see any use case for now)

### CODE REVIEW

**Comment by peti** [comment]
This patch looks fine to me. I wonder about two things:

1. Why don't the packages live underneath `pkgs/development/pkgs/development/elm-modules`? Putting them underneath the compiler is unusual in Nixpkgs.

2. What is the reason for duplicating Haskell build expressions like `elm-compiler` rather than using the ones we already have?

**Comment by abbradar** [comment]
1. This is the Elm platform without any Elm packages in Hackage sense (well, there are technically several packages for `elm-reactor`, but they are isolated), consisting of a compiler, a REPL, a debugger and Cabal-like utilities -- I felt that this is more a "compiler" than "modules".
2. The upstream has stopped updating Hackage packages and promotes their own build script which checks out specific git tags and builds a sandbox. I'm using a small Ruby script to generate needed packages from their specification. For instance, `elm-compiler-0.15.1` is not on Hackage.

**Comment by peti** [comment]
Thank you for the explanations! I wish the Elm people would deprecate their package on Hackage if they don't intend to maintain it there anymore.

**Comment by peti** [comment]
Anyway, the code looks fine to me. Merge away if you feel that it's ready. Also, I'm about to push 9e7ce5b to disable the broken Elm variants in the haskellPackages set.

**Comment by doshitan** [comment]
I came up with my own hack to get the latest Elm stuff before I saw this. Your approach is much better (^_^). [My hack is here](https://github.com/doshitan/nixpkgs/commit/bc53238ece011ffbbd36dde13505f2dda453dfc0) if you want to take a look. I kept the Elm packages a part of haskellPackages, just providing versions that sourced from GitHub instead of Hackage.

My only suggestion for this pull request is that `elm-repl` requires both `elm-make` and `nodejs` to exist in it's `$PATH` in order for it to actually work. `elm-repl` has flags to point it at the specific compiler and interpreter binaries you want to use, but being in `$PATH` is good enough (it will look for `elm-make` and `node` or `nodejs` binaries to use by default). [I just used wrapProgram](https://github.com/doshitan/nixpkgs/commit/bc53238ece011ffbbd36dde13505f2dda453dfc0#diff-e8c82ff850fd2758c22d2ade45667b56R137).

**Comment by rehno-lindeque** [comment]
@evancz can probably mark the the Hackage packages as deprecated

**Comment by evancz** [comment]
They are all marked as deprecated.

**Comment by rehno-lindeque** [comment]
Thanks!

**Comment by rehno-lindeque** [comment]
Also paging
* @agrafix wrt `elm-bridge`
* @JoeyEremondi wrt `elm-core-sources` / `elm-build-lib`
* @JustusAdam wrt `elm-init`.

I just noticed your packages was also marked broken in https://github.com/NixOS/nixpkgs/commit/9e7ce5bff5758065a7b2bca58d15dc68ce31864d#diff-8f392bd0e4fd42a66d9e0cd4901ec287R919. Are they deprecated?

I'm sure some of these are still actively maintained on Hackage (not part of the Elm platform). `elm-bridge` was just announced the other day.

These all depend on deprecated packages, so I'm guessing it's safe to mark deprecated:
* `snap-elm` (not included in the commit, but is probably broken)
* @tazjin wrt `elm-yesod`
* @maxsnew wrt `hakyll-elm`

Please mark as deprecated on Hackage if you don't mind.

**Comment by JustusAdam** [comment]
`elm-init` doesn't depend on any elm platform packages.

I personally haven't used any package distribution other than hackage and I'd appreciate if someone could tell me what the canonical way of publishing elm related software is now so I can submit upstream changes to the right place.

**Comment by agrafix** [comment]
@rehno-lindeque `elm-bridge` does not depend on any elm platform packages and is not deprecated.

**Comment by abbradar** [comment]
@peti I believe there was a misunderstanding (correct me if I'm wrong!) -- Elm platform consists only of

* elm-make
* elm-package
* elm-repl
* elm-compiler
* elm-reactor

Other packages are not in the platform (nor in my PR) and their authors still release them on Hackage.

**Comment by abbradar** [comment]
@doshitan Thanks for your advice! I'll fix this, add some documentation and this should be good to go.

**Comment by rehno-lindeque** [comment]
@JustusAdam I think it's probably something you can bring up in the [elm-discuss](https://groups.google.com/forum/#!forum/elm-discuss) mailinglist. We probably want to avoid spamming this PR (but I believe Hackage should be fine as long as you don't depend on Elm platform packages).

**Comment by JoeyEremondi** [comment]
Sorry for the dealy on my part, I just depricated elm-build-lib, it hasn't
been updated in a while, and I'm not sure if anyone is using it.

On Mon, Aug 17, 2015 at 12:32 PM, Nikolay Amiantov <notifications@github.com

**Pull request merged**
