### PR TITLE
avr-*: split avr-gcc-libc into separate packages

### PR DESCRIPTION
**Pull request by mguentner**
###### Motivation for this change

the avr toolchain was broken on master

Issue: #28220

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
  Compiled a small AVR binary.
  CC @danielfullmer Could you please test against your project?
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mguentner** [comment]
Don't pull yet. There are still some dependencies that need to be fixed

**Comment by mguentner** [comment]
The binaries work / compile. I am unsure whether the library path needs to be fixed for avr-gcc / avr-libc or not.

avr-gcc needs specific includes for the microcontroller used. If a `atmega644` is used, the libraries reside in `{AVR}/avr/lib/avr5` and for a `atmega8` in `{AVR}/avr/lib/avr4`.
On traditional distributions, all the avr includes / libraries share a common prefix (like /usr/avr/...).
Since the packages are now separate, this means that one needs to supply these paths for the build
process (as laid out in 6a458c169b86725b6d0b21918bee4526a9289c2f).
The question now is whether there is a way to tell avr-gcc/avr-ld: "*Take this path as your relative path and add the correct path for the respective mcu*"

**Comment by danielfullmer** [comment]
I can confirm that my own project at [danielfullmer/tmk_keyboard](https://github.com/danielfullmer/tmk_keyboard) builds with this PR---with the addition of the mcu-specific CFLAGS as described in 6a458c1. I agree, it would be much more convenient if avr-gcc can just figure out the correct includes as it seemed to do previously.

Also, is this going to change again when @Ericson2314 's  cross-compilation PRs are all merged? It would be nice if whatever interface we expose can remain constant for downstream derivations. For instance, would it be valuable to keep `avrgcclibc` as a convenience wrapper around the individual packages? My cross-compilation knowledge is severely lacking, so I'd be interested in comments on the proper direction for this stuff.

**Review by Ericson2314 — APPROVED** [review]
I hope that once I'm done, we can get rid of this and just use normal gcc + avr libc. Until then, though, this is definitely an improvement. Thanks!

**Comment by mguentner** [comment]
@danielfullmer Thanks for testing!

Let's see whether we can figure out how to get this `avr4`, `avr5` etc. stuff right.

**Pull request merged**
