### PR TITLE
openafs_1_8: Init at 1.8.0 (was: openafs: 1.6.22.3 -> 1.8.0)

### PR DESCRIPTION
**Pull request by spacefrogg**
- Introduce new "server" output holding the server binaries
 - Adapt tsmbac.patch to new build environment
 - Adapt openafs server nixos module accordingly
 - Update upstream CellServDB: 2017-03-14 -> 2018-05-14

###### Motivation for this change

Update to new stable release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build linuxPackages.openafs

**Comment by xeji** [comment]
According to [Hydra logs](https://hydra.nixos.org/job/nixpkgs/trunk/linuxPackages.openafs.aarch64-linux/all) this never built on aarch64, although upstream seems to support ARM.

Please mark the package as broken on aarch64: `meta.broken = stdenv.isAarch64;`

**Comment by spacefrogg** [comment]
@GrahamcOfBorg build linuxPackages.openafs

**Comment by xeji** [comment]
@GrahamcOfBorg build linuxPackages.openafs

**Comment by xeji** [comment]
still broken on aarch64

**Comment by spacefrogg** [comment]
I changed the direction of this PR. The packages openafs and openafs_1_8 are both maintained for a while to allow for a smooth transition (especially for servers) from OpenAFS 1.6 to 1.8.

I introduced nixos options for package selection to further smoothen the transition.

**Comment by spacefrogg** [comment]
I just noticed a bug in the new openafs release. Please don't merge, yet.

**Comment by spacefrogg** [comment]
The bug is fixed. PR is ready to be merged.

**Comment by xeji** [comment]
@GrahamcOfBorg  build linuxPackages.openafs_1_8

**Comment by xeji** [comment]
@GrahamcOfBorg build openafs_1_8

**Pull request merged**
