### PR TITLE
vimPlugins.aider-nvim: init at 2023-10-22

### PR DESCRIPTION
**Pull request by nvimtor**
## Description of changes
Adds a package for the [aider.nvim](https://github.com/joshuavial/aider.nvim) plugin.

This plugin allows you to use [aider](https://github.com/paul-gauthier/aider) within Neovim.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by PerchunPak — CHANGES_REQUESTED** [review]
This plugin depends on `aider-chat`, it is probably a good idea to patch it like here:
https://github.com/NixOS/nixpkgs/blob/3745f505bd20f65c2d71c345c919ef0fb83e1201/pkgs/applications/editors/vim/plugins/overrides.nix#L1489-L1495
Lines, where `aider-chat` is used:

https://github.com/joshuavial/aider.nvim/blob/74a01227271d0ea211f2edafa82028b22d4c2022/lua/helpers.lua#L66

**Comment by nvimtor** [comment]
@PerchunPak Good catch. Unfortunately I don't think there's a Nix package for `aider` so we need to wait for that first, I believe.

**Comment by PerchunPak** [comment]
@nvimtor there is - `aider-chat`

https://github.com/NixOS/nixpkgs/blob/99dc8785f6a0adac95f5e2ab05cc2e1bf666d172/pkgs/by-name/ai/aider-chat/package.nix

**Comment by nvimtor** [comment]
@PerchunPak 

Thanks. I've hit a roadblock. Given this example flake:

```nix
{
  description = "A simple flake with a custom Neovim build";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

		vitorpkgs.url = "github:nvimtor/nixpkgs/aider-nvim";

    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, vitorpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        customNeovim = pkgs.neovim.override {
          configure = {
            packages.myVimPackage = with vitorpkgs.legacyPackages.${system}.vimPlugins; {
              start = [
								aider-nvim
                # Add more plugins here
              ];
            };
          };
        };
      in
      {
        packages.default = customNeovim;
      }
    );
}
```

I get

```
error: builder for '/nix/store/9l8ccbjdralcjy6g3ipqf622c925ammi-aider-chat-0.54.0.drv' failed with exit code 1;
       last 30 log lines:
       >                 if self.input.closed:
       >                     f.set_exception(EOFError)
       >
       >         # Enter raw mode, attach input and attach WINCH event handler.
       >         with self.input.raw_mode(), self.input.attach(
       >             read_from_input_in_context
       >         ), attach_winch_signal_handler(self._on_resize):
       >             # Draw UI.
       >             self._request_absolute_cursor_position()
       >             self._redraw()
       >             self._start_auto_refresh_task()
       >
       >             self.create_background_task(self._poll_output_size())
       >
       >             # Wait for UI to finish.
       >             try:
       > >               result = await f
       > E               EOFError
       >
       > /nix/store/fihchiss2fi8mamqwsfvjpsys2vqqa85-python3.11-prompt-toolkit-3.0.47/lib/python3.11/site-packages/prompt_toolkit/application/application.py:746: EOFError
       > ----------------------------- Captured stdout call -----------------------------
       > Run pip install? (Y)es/(N)o [Yes]:                                   Run pip install? (Y)es/(N)o [Yes]:
       > =========================== short test summary info ============================
       > FAILED tests/basic/test_main.py::TestMain::test_env_file_flag_sets_automatic_variable - EOFError
       > FAILED tests/basic/test_main.py::TestMain::test_false_vals_in_env_file - EOFError
       > FAILED tests/basic/test_main.py::TestMain::test_light_mode_sets_code_theme - EOFError
       > FAILED tests/basic/test_main.py::TestMain::test_main_with_empty_dir_no_files_on_command - EOFError
       > FAILED tests/basic/test_main.py::TestMain::test_true_vals_in_env_file - EOFError
       > FAILED tests/basic/test_main.py::TestMain::test_verbose_mode_lists_env_vars - EOFError
       > ================= 6 failed, 167 passed, 8 deselected in 17.63s =================
       For full logs, run 'nix log /nix/store/9l8ccbjdralcjy6g3ipqf622c925ammi-aider-chat-0.54.0.drv'.
error: 1 dependencies of derivation '/nix/store/1kgbb5r5q3aiwcqm1imyczda4qpwx3vl-vimplugin-aider.nvim-2023-10-22.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yw0rzl96vq0h2pfl47zsll09wk1pd5fw-neovim-0.10.1.drv' failed to build
```

I'm not really sure what to do. I can build `aider-chat` just fine by running `nix-shell -p aider-chat`.

Any ideas?

**Comment by PerchunPak** [comment]
Yeah, it should be fixed in master. See https://github.com/NixOS/nixpkgs/pull/343759

To fix this, just run `git rebase master`

**Comment by nvimtor** [comment]
@PerchunPak done, and it is working fine now

**Review by PerchunPak — APPROVED** [review]
LGTM

CC @GaetanLepage

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

- Command: `nixpkgs-review pr 340370`
- Systems: `x86_64-linux`,`aarch64-linux`,`x86_64-darwin`,`aarch64-darwin`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Pull request merged**
