### PR TITLE
nixos/network-interfaces: Implement the ability to add arbitrary routes

### PR DESCRIPTION
**Pull request by wkennington**
This is currently a work in progress as supporting default routes is probably not quite working. I'd appreciate testers when this code actually evaluates.

### CODE REVIEW

**Comment by jagajaga** [comment]
So what about this PR?

**Comment by wkennington** [comment]
It's completely out of date with the current networks interfaces but it
could be done.

**Comment by rasendubi** [comment]
(triage) @wkennington do you expect to work on this further?

**Comment by wkennington** [comment]
Nope

**Comment by rasendubi** [comment]
I think this can be closed then.

**Comment by joachifm** [comment]
Closing as abandoned.

**Pull request closed without merging**
