### PR TITLE
librecad: remove old 1.x, make 2.x default

### PR DESCRIPTION
**Pull request by bjornfor**
The main point is to make 2.x the default, but I don't think there is much value in 1.x anymore.

CC maintainer @viric.

### CODE REVIEW

**Comment by davidak** [comment]
should `librecad` be a "symlink" to the `librecad2` package, so if someone installed the package "librecad" he get's an update to 2; if the package "librecad2" is installed, one get updates for that.

**Comment by bjornfor** [comment]
@davidak: Yes that is possible. But I think there is little point in the 1.x series anymore, so I didn't do that. But maybe other people feel differently, hence the PR.

With this PR, there will only be "librecad" package and it'll be the latest one.

**Comment by bjornfor** [comment]
@davidak: Oh, right, there is also the possibility to keep the "librecad2" attribute pointing to "librecad", for backwards compatibility. (Maybe that's what you meant?)

**Comment by bjornfor** [comment]
Updated so that no attributes are removed. "librecad" now points to the 2.x version and 1.x is no more.

**Comment by davidak** [comment]
yes, that is what i mean. :+1:

**Comment by bjornfor** [comment]
@davidak :-)

**Comment by bjornfor** [comment]
Pushed to master (10c07911428563236b5248cbef4948baac610a42).

**Pull request closed without merging**
