### PR TITLE
sage: 9.6 -> 9.7

### PR DESCRIPTION
**Pull request by collares**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by collares** [comment]
@ofborg build sage.doc

**Comment by collares** [comment]
@ofborg build sageWithDoc

**Comment by 7c6f434c** [comment]
Looks reasonable… anything to wait for before merging?

**Comment by 7c6f434c** [comment]
So did aarch64 test build timeout literally at the very end of a build step? Painful.

**Comment by collares** [comment]
@7c6f434c It's more annoying than that, even. A bunch of tests which communicate with GAP and Singular using pexpect deadlock on aarch64. Sage sends a command and receives an answer which does not finish with a new command prompt and keeps waiting. From the point of view of the child process, it sent everything and is waiting for a new command. So there are ~20 tests which idle until the ofBorg timeout hits, and it's not always the same tests.

The first time this happened on a PR was in June 25th (https://github.com/NixOS/nixpkgs/pull/178895, but at the time I thought it was the Giac intermittent timeout, which sometimes happens on x86_64 too). It was fine on May 27th (https://github.com/NixOS/nixpkgs/pull/175044). I tried figuring out what changed using an Oracle Cloud machine, but to my surprise even Sage 9.3 tests were hanging on an old Nixpkgs checkout. I can only assume this was always failing on some machines (I think @timokau mentioned something similar when I added a tachyon workaround in #117465) and something must've changed in the ofBorg buildsers in May/June (Kernel? Hardware? Who knows). I filed https://trac.sagemath.org/ticket/34297 with my findings, but I couldn't think of a good way to proceed with the investigation.

As far as I know there are no blockers for merging, and the update was really painless this time as you can see by the diff.

**Comment by 7c6f434c** [comment]
So basically child process sends new prompt before grand-child process sends some more output?

**Pull request merged**
