### PR TITLE
sumneko-lua-language-server: 1.16.0 -> 1.20.2

### PR DESCRIPTION
**Pull request by ck3d**
###### Motivation for this change
Update package to latest version.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119801` at d844469c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>sumneko-lua-language-server</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/sumneko-lua-language-server/default.nix:33:3:
```
   |
33 |   installPhase = ''
   |   ^
```
</li>
    <li>error: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-flags-spaces.md">no-flags-spaces</a>

`ninjaFlags` cannot contain spaces, please use `ninjaFlagsArray` in Bash.

Near pkgs/development/tools/sumneko-lua-language-server/default.nix:24:3:
```
   |
24 |   ninjaFlags = [
   |   ^
```
</li>
  </ul>
</details>

**Comment by mjlbach** [comment]
FWIW, Sumneko version bumps are *not* always a simple merge, there have historically been large [regressions](https://github.com/sumneko/lua-language-server/issues/386) between versions, and the version number increases rather quickly (1.16 is not that old, and is fairly "stable"). I only had a window of 4 hours before this was merged to test, 3.5 of which I was asleep. 

Also the pre and post install hooks are not used in this case, so I'm not sure I agree with the bot.

**Comment by mjlbach** [comment]
@SuperSandro2000 ^

**Comment by SuperSandro2000** [comment]
> Also the pre and post install hooks are not used in this case, so I'm not sure I agree with the bot.

They should be added anyway or some hooks silently fail.

**Pull request merged**
