### PR TITLE
sqlite: 3.39.4 -> 3.40.0

### PR DESCRIPTION
**Pull request by zowoq**
https://www.sqlite.org/releaselog/3_40_0.html

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
As suggestion, can you include `meta.changelog` url?

**Comment by trofi** [comment]
Bisect claims that this update broke 1 `tracker` test seemingly related to some return value from sqlite:

```
$ nix build --no-link -f. -L tracker
...
tracker> 26/37 tracker:core+slow / sparql                              FAIL             1.90s
...
tracker> (/build/tracker-3.4.1/build/tests/core/tracker-sparql-test:2949): Tracker-ERROR **: 12:04:55.395: --- /build/tracker-3.4.1/tests/core/property-paths/alternative-path-3.out    2022-10-26 11:34:53.000000000 +0000
tracker> +++ -  2022-11-19 12:04:55.395358858 +0000
tracker> @@ -1,20 +1,20 @@
tracker> +"Alice"       "55"
tracker> +"Alice"       "56"
tracker> +"Alice"       "7"
tracker> +"Alice"       "78"
tracker>  "Alice"       "Alice"
tracker> -"Alice"       "http://www.w3.org/2000/01/rdf-schema#Resource"
tracker> -"Alice"       "http://xmlns.com/foaf/0.1/Agent"
tracker> -"Alice"       "http://xmlns.com/foaf/0.1/Person"
tracker> -"Alice"       "mailto:alice@work"
tracker> +"Bob" "55"
tracker> +"Bob" "56"
tracker> +"Bob" "7"
tracker> +"Bob" "80"
tracker> +"Bob" "81"
tracker>  "Bob" "Bob"
tracker> -"Bob" "http://www.w3.org/2000/01/rdf-schema#Resource"
tracker> -"Bob" "http://xmlns.com/foaf/0.1/Agent"
tracker> -"Bob" "http://xmlns.com/foaf/0.1/Person"
tracker> -"Bob" "mailto:bob@home"
tracker> -"Bob" "mailto:bob@work"
tracker> +"Eve" "55"
tracker> +"Eve" "56"
tracker> +"Eve" "7"
tracker>  "Eve" "Eve"
tracker> -"Eve" "http://www.w3.org/2000/01/rdf-schema#Resource"
tracker> -"Eve" "http://xmlns.com/foaf/0.1/Agent"
tracker> -"Eve" "http://xmlns.com/foaf/0.1/Person"
tracker> +"Fred"        "55"
tracker> +"Fred"        "56"
tracker> +"Fred"        "7"
tracker> +"Fred"        "84"
tracker>  "Fred"        "Fred"
tracker> -"Fred"        "http://www.w3.org/2000/01/rdf-schema#Resource"
tracker> -"Fred"        "http://xmlns.com/foaf/0.1/Agent"
tracker> -"Fred"        "http://xmlns.com/foaf/0.1/Person"
tracker> -"Fred"        "mailto:fred@edu"
```

**Comment by trofi** [comment]
Filed report upstream as https://gitlab.gnome.org/GNOME/tracker/-/issues/387

**Comment by risicle** [comment]
@trofi in cases like this consider adding the broken package to this package's `passthru.tests`.

**Comment by trofi** [comment]
Good point! Proposed `tracker` addition as https://github.com/NixOS/nixpkgs/pull/205974

**Pull request merged**
