### PR TITLE
ffmpeg: add support for libssh and speex

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Pretty useful.

###### Things done

- [X] Worked before rebase.

### CODE REVIEW

**Comment by xeji** [comment]
That aarch64 error looks transient, lets try again.
@GrahamcOfBorg  build ffmpeg

**Comment by xeji** [comment]
Darwin error is a 504 (Gateway Timeout) accessing the cache, looks unrelated:
```
unable to download 'https://cache.nixos.org/nar/0qcjkw8n1ll86mp785gmkbq2l93z1vy3749mgv2bzcb9a3rcz7rk.nar.xz': HTTP error 504 (curl error: No error)
```

**Comment by oxij** [comment]
Thanks!

**Comment by edolstra** [comment]
Please make this optional and disabled by default. `ffmpeg` is already bloated enough.

**Comment by xeji** [comment]
`ffmpeg` closure before this change: 128838k, after: 129560k. 
The difference is 585k for `libssh` and 116k for `speex`. Not a big deal IMO.

**Pull request merged**
