### PR TITLE
ntpd-rs: migrate to by-name & add updateScript, 1.2.0 -> 1.2.2

### PR DESCRIPTION
**Pull request by getchoo**
## Description of changes

Mainly for @NixOS/nixpkgs-merge-bot

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Lassulus — APPROVED** [review]

**Review by NotAShelf — APPROVED** [review]

**Comment by Lassulus** [comment]
seems like a build-failure?

```
failures:
---- daemon::ntp_source::tests::test_deny_stops_poll stdout ----
thread 'daemon::ntp_source::tests::test_deny_stops_poll' panicked at ntpd/src/daemon/ntp_source.rs:739:9:
assertion failed: timestamp.is_some()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- daemon::ntp_source::tests::test_timeroundtrip stdout ----
thread 'daemon::ntp_source::tests::test_timeroundtrip' panicked at ntpd/src/daemon/ntp_source.rs:698:35:
called `Option::unwrap()` on a `None` value
failures:
    daemon::ntp_source::tests::test_deny_stops_poll
    daemon::ntp_source::tests::test_timeroundtrip
```

**Comment by fpletz** [comment]
Sigh, I hate this testsuite. Builds fine locally.

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
After having disabled the failing tests now new tests failed on ofborg. Disabling testsuite. We always had some flaky tests in ntpd-rs. Upstream needs to fix this before we can enable it again.

**Comment by fpletz** [comment]
Reported upstream: https://github.com/pendulum-project/ntpd-rs/issues/1396

**Pull request merged**
