### PR TITLE
autoPatchelfHook: Fixes/improvements for Android SDK emulator

### PR DESCRIPTION
**Pull request by aszlig**
This is related to #50596, which refactors the `androidenv` implementation.

For patching various ELF files, a similar implementation to `autoPatchelfHook` was introduced there and after talking with @svanderburg, I went on to improve the hook in a way so that it's possible to be also used for `androidenv`, which also makes it less confusing for users having two things doing roughly the same but are named similarly.

Essentially, these changes make it easier to use only the `autoPatchelf` command without automatically patching *all* the build outputs.

For example:

```nix
with import <nixpkgs> {}; stdenv.mkDerivation {
  name = "foo";
  ...
  nativeBuildInputs = [ autoPatchelfHook ];
  dontAutoPatchelf = true;
  postPatch = ''
    autoPatchelf foo
    autoPatchelf --no-recurse bar
  '';
}
```

The `--no-recurse` flag here only patches files within the `bar` directory but not files in subdirectories like `bar/a/b/c`.

In order to make sure these changes do not break existing users of this hook, I've tested it using the following Nix expression and looking for symbol lookup errors:

```nix
with import ./. { config.allowUnfree = true; };

runCommand "test-executables" {
  drvs = [
    anydesk cups-kyodialog3 elasticsearch franz gurobi
    masterpdfeditor oracle-instantclient powershell reaper
    sourcetrail teamviewer unixODBCDrivers.msodbcsql17 virtlyst
    vk-messenger wavebox zoom-us nomachine-client polar-bookshelf
  ];
} ("for i in $drvs; do for b in $i/bin/*; do " +
   "[ -x \"$b\" ] && timeout 10 \"$b\" || :; done; done")
```

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
I have not tested it, but the code and the documentation make sense to me.
The example from your description would also fit well into the documentation.

**Review by Mic92 — APPROVED** [review]

**Comment by svanderburg** [comment]
Great! I'll try to adjust my androidenv pull request later today and see if it works with the new implementation. I'll report back asap!

**Comment by svanderburg** [comment]
I believe I am still having a practical issue while trying to migrate the Android SDK expressions to the autopatchelf hook implementation.

Apparently, to use autoPatchelf, you must refer to the libraries that you want to use (through buildInputs or runtimeDependencies) by providing the Nix store paths of the packages that you want to use. The autopatchelf hook seems to scan the `lib/` sub folders of every Nix store path for the libraries that it needs.

I don't think there is a way to directly refer to library paths (without making an assumption that there is a `lib/` sub folder)? The problem is that the Android SDK also bundles shared libraries residing in weird sub folders inside the same base directory as the executables, e.g. `<basedir>`/lib64`, `<basedir>/lib/qt` etc.

The autopatchelf implementation that I created uses colon separated library paths (as opposed to white space delimited Nix store paths) and can also inspect library sub folders in the same package. Is there also a way to add this kind of flexibility to the autopatchelf hook?

(As a sidenote: my original motivation to use colon separated library paths is that you can use `LD_LIBRARY_PATH` outside a Nix builder environment to automatically make dynamic library references static).

My biggest struggle is to port the expression that patches the Android emulator. It needs external packages, as well as libraries that are bundled with the emulator package itself, as you may probably see while inspecting contents of this file: https://github.com/svanderburg/nix-androidenvtests/blob/nextgen/androidenv/emulator.nix

In the expression, I refer to Nix packages (and use `lib.makeLibraryPath` to compose the paths), but I also specify paths referring to sub directories inside the same package. `autopatchelf` will also inspect these folders for libraries that an executable may need.

Would it also be possible to do something similar with the autoPatchelf command or adjust it in such a way that it can?

**Comment by aszlig** [comment]
> The autopatchelf implementation that I created uses colon separated library paths (as opposed to white space delimited Nix store paths) and can also inspect library sub folders in the same package. Is there also a way to add this kind of flexibility to the autopatchelf hook?

The library subdirectories for the same package are already inspected by autoPatchelfHook:

https://github.com/NixOS/nixpkgs/blob/503b41b9b2d726f10372e3daac713cc2042b8cf0/pkgs/build-support/setup-hooks/auto-patchelf.sh#L174-L177

However, when running `autoPatchelf` manually without the `postFixup` hook, it will only work on the path you've specified.

Maybe it makes sense to add shell function like `addAutoPatchelfSearchPath` (maybe with a shorter), which allows to add the patch to the dependency cache. 

Does that sound good for you?

And would such a function then also recurse into subdirectories or even have the same `--no-recurse` flag?

> My biggest struggle is to port the expression that patches the Android emulator. It needs external packages, as well as libraries that are bundled with the emulator package itself, as you may probably see while inspecting contents of this file: https://github.com/svanderburg/nix-androidenvtests/blob/nextgen/androidenv/emulator.nix

Seperately specifying `libs_i386` and `libs_x86_64` here shouldn't be necessary because `autoPatchelf` will only find compatible libraries or do you see a problem in that approach?

**Comment by svanderburg** [comment]
> Seperately specifying libs_i386 and libs_x86_64 here shouldn't be necessary because autoPatchelf will only find compatible libraries or do you see a problem in that approach?

I don't need the separation, although I would find it nicer to write it separately, but that's just a matter of taste. I can live without it.

Basically, the only problem I have is converting this line in the emulator expression:

```bash
export libs_x86_64=$packageBaseDir/lib64:$packageBaseDir/lib64/qt/lib:$libs_x86_64
```
I want autopatchelf to inspect these two directories shown above in addition to the packages that I provide as buildInputs. These two paths translate to: `$out/libexec/android-sdk/emulator/lib64` and `$out/libexec/android-sdk/emulator/lib64/qt/lib` (as may see, these paths are quite unconventional).

If there's any environment variable (or function) allowing me to provide these paths, so that they get added to the RPATH of the right executables, that will basically fix my problem.

**Comment by aszlig** [comment]
The example you mentioned can be added via:

```bash
cachedDependencies+=( 
  $(find "$out/libexec/android-sdk/emulator/lib64" \
    \! -type d \( -name '*.so' -o -name '*.so.*' \))
)
```

That's a lot of churn, so that's why I mentioned factoring this out into a dedicated function, but this *should* work (haven't tested it though).

**Comment by svanderburg** [comment]
@aszlig Would be nice if you could implement a function wrapper so that I can conveniently add these paths

**Comment by svanderburg** [comment]
Great now it seems to work a lot better. I have managed to make the basic test cases work (deploying an SDK installation with some plugins, building an APK, and launching the emulator).

Unfortunately, when try to compile the `hello-jni` example (that depends on the Android NDK), I'm still running into a problem:

```
setting RPATH to: /nix/store/1fd7ybkplw7cjx6hyiiyvb03abx0l0iz-ncurses-6.1-abi5-compat/lib:/nix/store/1fd7ybkplw7cjx6hyiiyvb03abx0l0iz-ncurses-6.1-abi5-compat/lib
searching for dependencies of prebuilt/linux-x86_64/bin/yasm
searching for dependencies of prebuilt/linux-x86_64/bin/python2
searching for dependencies of prebuilt/linux-x86_64/lib/python2.7/config/python.o
wrong ELF type
builder for '/nix/store/9zvwb63r9pcv4az6q1fsvlj8s5hymv26-ndk-bundle-18.1.5063045.drv' failed with exit code 1
```

Apparently, it recurses into a directory that provides an object file (python.o). `autoPatchelf` tries to patch it. With my `autopatchelf` implementation this file is skipped because I use the `file` command to determine whether a file is an appropriate ELF binary or not. Yours apparently works different. Would it be possible to exclude ordinary `.o` files so that the patch process succeeds?

(As a sidenote: it's really stupid of the Android package maintainers to include this file, but this something we have to live with)

**Comment by aszlig** [comment]
`autoPatchelfHook` was using file as well, see comments in #47222, the problem with `file` however is that it is very slow if you have a large number of files other than ELF files. I'll fix the object files case in a minute.

**Comment by aszlig** [comment]
@svanderburg: Can you provide an output of `readelf -h -l prebuilt/linux-x86_64/lib/python2.7/config/python.o`? I tested with a bunch of object files but couldn't reproduce it.

**Comment by aszlig** [comment]
@svanderburg: Fixed, thanks.

**Review by svanderburg — APPROVED** [review]

**Pull request merged**
