### PR TITLE
glib: add man pages, make bash completion work

### PR DESCRIPTION
**Pull request by wentasah**
###### Description of changes

This contains two commits:
1. The first adds man pages to binaries provided by the glib package.
2. The second moves bash completion scripts to the same output as the respective binaries, which makes the completion work out of the box.

More details in commit messages.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of about 500 depending packages that are affected by this change.
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@ofborg build glib

**Comment by 7c6f434c** [comment]
Hmmm, it looks like this shouldn't fail on Darwin?

**Comment by wentasah** [comment]
Not sure what's going on on Darwin, so I disabled the man pages there.

@ofborg build glib

**Comment by wentasah** [comment]
So now it fails only on aarch64-darwin. Is there a way to compare logs from this ofborg build and some previous successful build? I tried to find the log on hydra, but cannot find anything for aarch64-darwin.

**Comment by wentasah** [comment]
Found the aarch64-darwin logs. I don't see any significant difference between failing and successful build. I tried to rebase on current nixos-unstable to check, whether it helps.

@ofborg build glib

**Comment by wentasah** [comment]
Now it builds everywhere.

**Pull request merged**
