### PR TITLE
installation-cd: Build Graphical ISOs for aarch64

### PR DESCRIPTION
**Pull request by Thra11**
###### Description of changes

Changed installation-graphical-base to only enable `virtualisation.vmware.guest` and `services.xe-guest-utilities` on x86. The VMWare guest module is marked as not supported on aarch64, while the xe-guest-utilities package fails to build on aarch64.

With the changes in this PR, it is possible to build and boot a graphical iso on aarch64, presumably opening up the possiblity of pre-built aarch64 graphical isos from hydra. (See https://discourse.nixos.org/t/arm-graphical-iso-builds/16729)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Thra11** [comment]
Btw, I tested this by creating my-iso-image.nix with the following contents (based on [this guide](https://nixos.org/guides/building-bootable-iso-image.html)):
```
{ pkgs, modulesPath, lib, ... }: {
  imports = [
    "${modulesPath}/installer/cd-dvd/installation-cd-graphical-plasma5-new-kernel.nix"
  ];

  boot.supportedFilesystems = lib.mkForce [ "btrfs" "reiserfs" "vfat" "f2fs" "xfs" "ntfs" "cifs" ];
}
```
and then running
```
nixos-generate --format iso --configuration ./my-iso-image.nix -o result 
```
I then dd'd the result to an SD Card:
```
sudo dd if=result/iso/nixos-22.11.git.75f15399cc2-aarch64-linux.iso of=/dev/XXX status=progress
```
booted from the SD Card, and choose the graphical installer option from the boot menu.

**Comment by Thra11** [comment]
CC @vlinkz @edolstra @samueldr @dezgeg

**Review by samueldr — APPROVED** [review]
I have not tested the resulting builds, but in principle it should *just work*, as there's nothing special with AArch64 systems when they boot with standards-based protocols (UEFI).

Obviously in the real world it will be "YMMV", but just as much as any other distro that *only* supports mainline. The limitations here will be whatever works with the current LTS of Linux. (Which is also true for x86_64!)

**Review by samuela — APPROVED** [review]
changes LGTM

anything else we need to do before merging?

**Comment by mweinelt** [comment]
Seeing an error build the GNOME ISO.

```
$ nix-build nixos/release.nix -A iso_gnome --system aarch64-linux
[...]
error: a 'x86_64-linux' with features {} is required to build '/nix/store/7v9gqlcf6zn9al5b1gl8y4v8rrf2bx5k-loopback.cfg.drv', but I am a 'aarch64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

**Comment by abhillman** [comment]
FWIW I was able to build a gnome image for aarch64 using

```
$ docker run -it --platform linux/arm64 nixos/nix
$ git clone https://github.com/NixOS/nixpkgs.git --depth 1

# fetch and check out the latest release tag
# apply changes to `https://github.com/NixOS/nixpkgs/compare/master...Thra11:nixpkgs:aarch64-graphical-iso` from https://github.com/NixOS/nixpkgs/compare/master...Thra11:nixpkgs:aarch64-graphical-iso

$ nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-graphical-gnome.nix default.nix
```

From there, I was able to run the live image using Mac OS virtualization (i.e. https://developer.apple.com/documentation/virtualization/running_gui_linux_in_a_virtual_machine_on_a_mac)

image


The one curious thing is that I don't think I see the installer auto-launching, which I _think_ it does for `amd64`.

**Comment by Thra11** [comment]
Haven't had time to test it yet, but it looks like @mweinelt's  [commit](https://github.com/NixOS/nixpkgs/commit/9328b7eebf6afbd345f20f5d76b6357f85037506) which is causing the conflicts basically does the same thing as this PR, so we can probably abandon this one now?

**Comment by mweinelt** [comment]
Oh, sorry. Apparently I reviewed this, forgot this and then did it again myself. :facepalm:

**Comment by mweinelt** [comment]
It does not support anything but x86-64-linux.

**Comment by Thra11** [comment]
> Is there any reason why we don't need the vmware/virtualbox stuff anymore?

For clarity, the changes in this PR to only enable them on x86 were required, but Martin has also made those changes in https://github.com/NixOS/nixpkgs/commit/8f366cbfcc62871f481e035984e5932e30d8b0ed and https://github.com/NixOS/nixpkgs/commit/373c1a8e4322ef86f659c29e828b0a82e7df3777.

**Pull request closed without merging**
