### PR TITLE
graalvm-ce: 22.0.0 -> 22.0.1

### PR DESCRIPTION
**Pull request by pan93412**
## Description of changes

Update `graalvm-ce` to 22.0.1, released on 16 Apr. 2024. <https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-22.0.1>

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
    ```
	error: builder for '/nix/store/vk3sjk2lgam2g3sghqn4prdx6xi9qbfl-scala-update-0.2.2.drv' failed with exit code 1;
	       last 10 log lines:
	       > ------------------------------------------------------------------------------------------------------------------------
	       >                         1.0s (3.9% of total time) in 13 GCs | Peak RSS: 1.03GB | CPU load: 0.81
	       > ========================================================================================================================
	       > Failed generating 'scala-update' after 21.4s.
	       > com.oracle.svm.driver.NativeImage$NativeImageError
	       >     at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2258)
	       >   at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1871)
	       >       at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1830)
	       >        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1812)
	       >        at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
	       For full logs, run 'nix log /nix/store/vk3sjk2lgam2g3sghqn4prdx6xi9qbfl-scala-update-0.2.2.drv'.
	error: 1 dependencies of derivation '/nix/store/9licii6ia372g5jwng16yxi62w96dkpp-review-shell.drv' failed to build
	3 packages marked as broken and skipped:
	dapl-native dbqn-native obb
	
	1 package failed to build:
	scala-update
	
	14 packages built:
	babashka babashka-unwrapped bbin certificate-ripper clj-kondo cljfmt clojure-lsp cq graalvm-ce jet neil vscode-extensions.betterthantomorrow.calva yamlscript zprint
    ```
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Frontear** [comment]
Why does this package have an IFD in the `default.nix`? Suppose it's outside the scope of this PR though

**Comment by pan93412** [comment]
> Why does this package have an IFD in the `default.nix`? Suppose it's outside the scope of this PR though

I think it is for making generation more user-friendly? https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/graalvm/community-edition/update.sh

I am not sure about it though. I update it with the script above.

**Comment by pan93412** [comment]
cc @Frontear ask for review – seems like the CI is passed

**Comment by pan93412** [comment]
Duplicate of #327385; closed.

**Pull request closed without merging**
