### PR TITLE
pythonPackages.minikerberos: 0.2.7 -> 0.2.8

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.2.8

Requires also a update of `asysocks`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 109010` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>python37Packages.asysocks</li>
    <li>python37Packages.lsassy</li>
    <li>python37Packages.minikerberos</li>
    <li>python37Packages.msldap</li>
    <li>python37Packages.pypykatz</li>
    <li>python37Packages.winsspi</li>
    <li>python38Packages.asysocks</li>
    <li>python38Packages.lsassy</li>
    <li>python38Packages.minikerberos</li>
    <li>python38Packages.msldap</li>
    <li>python38Packages.pypykatz</li>
    <li>python38Packages.winsspi</li>
    <li>python39Packages.asysocks</li>
    <li>python39Packages.lsassy</li>
    <li>python39Packages.minikerberos</li>
    <li>python39Packages.msldap</li>
    <li>python39Packages.pypykatz</li>
    <li>python39Packages.winsspi</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109010` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
18 packages built:
</summary>
<ul>
<li>python37Packages.asysocks</li>
<li>python37Packages.lsassy</li>
<li>python37Packages.minikerberos</li>
<li>python37Packages.msldap</li>
<li>python37Packages.pypykatz</li>
<li>python37Packages.winsspi</li>
<li>python38Packages.asysocks</li>
<li>python38Packages.lsassy</li>
<li>python38Packages.minikerberos</li>
<li>python38Packages.msldap</li>
<li>python38Packages.pypykatz</li>
<li>python38Packages.winsspi</li>
<li>python39Packages.asysocks</li>
<li>python39Packages.lsassy</li>
<li>python39Packages.minikerberos</li>
<li>python39Packages.msldap</li>
<li>python39Packages.pypykatz</li>
<li>python39Packages.winsspi</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109010` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
18 packages built:
</summary>
<ul>
<li>python37Packages.asysocks</li>
<li>python37Packages.lsassy</li>
<li>python37Packages.minikerberos</li>
<li>python37Packages.msldap</li>
<li>python37Packages.pypykatz</li>
<li>python37Packages.winsspi</li>
<li>python38Packages.asysocks</li>
<li>python38Packages.lsassy</li>
<li>python38Packages.minikerberos</li>
<li>python38Packages.msldap</li>
<li>python38Packages.pypykatz</li>
<li>python38Packages.winsspi</li>
<li>python39Packages.asysocks</li>
<li>python39Packages.lsassy</li>
<li>python39Packages.minikerberos</li>
<li>python39Packages.msldap</li>
<li>python39Packages.pypykatz</li>
<li>python39Packages.winsspi</li>
</ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 109010 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>18 packages built:</summary>  <ul>    <li>python37Packages.asysocks</li>    <li>python37Packages.lsassy</li>    <li>python37Packages.minikerberos</li>    <li>python37Packages.msldap</li>    <li>python37Packages.pypykatz</li>    <li>python37Packages.winsspi</li>    <li>python38Packages.asysocks</li>    <li>python38Packages.lsassy</li>    <li>python38Packages.minikerberos</li>    <li>python38Packages.msldap</li>    <li>python38Packages.pypykatz</li>    <li>python38Packages.winsspi</li>    <li>python39Packages.asysocks</li>    <li>python39Packages.lsassy</li>    <li>python39Packages.minikerberos</li>    <li>python39Packages.msldap</li>    <li>python39Packages.pypykatz</li>    <li>python39Packages.winsspi</li>  </ul></details>

**Pull request merged**
