### PR TITLE
pingu: init at 0.0.3

### PR DESCRIPTION
**Pull request by CactiChameleon9**
###### Description of changes
Pingu is the `ping` command implementation in Go but with colorful output and pingu ascii art
https://github.com/sheepla/pingu

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CactiChameleon9** [comment]
I would like this to be backported, but I am unsure how to add a label as suggested in 21.7.4.1 of the nixpkgs docs

**Comment by onny** [comment]
Result of `nixpkgs-review pr 178963` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pingu</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you for the contribution! Not sure how to ask the bot for backporting this

**Comment by CactiChameleon9** [comment]
Thanks for merging :)
Quick Q, is it standard to become a part of the nixOS organisation - or is it more of an optional thing

**Comment by onny** [comment]
After some time creating and reviewing pull requests I‘ve got invited in https://github.com/NixOS/nixpkgs/issues/50105

**Comment by CactiChameleon9** [comment]
I mean I got sent this:

Screenshot from 2022-09-07 17-53-30

Is it common practice to accept?

**Comment by onny** [comment]
I‘ve just got added but this looks promising.
But being added to NixOS org  doesnt have to mean that you‘ll have commit rights

**Comment by CactiChameleon9** [comment]
I know I would not have commit rights, but I am unsure whether or not to accept. Are all contributors excepted to become part of this organisation?

**Comment by onny** [comment]
It's safe to accept in my opinion. You can always leave. It's like joining a group on Facebook

**Comment by CactiChameleon9** [comment]
Ah, thanks. That makes sense. First time with organisation if you can't tell

**Pull request merged**
