### PR TITLE
apache-airflow: fix build on darwin

### PR DESCRIPTION
**Pull request by smancill**
###### Motivation for this change

Apache Airflow tests fail on Darwin: https://hydra.nixos.org/build/158846836

ZHF: #144627  (@NixOS/nixos-release-managers)

###### Things done

Disable a test that fails on Darwin (I don't know if it can be fixed):

    _______________________ TestCore.test_bash_operator_kill _______________________
    ...
    /nix/store/sg1d6cs4kswr8cjsasfhcbjmhi6gz2g1-python3.9-psutil-5.8.0/lib/python3.9/site-packages/psutil/_psosx.py:431: PermissionError
    ...
    E           psutil.AccessDenied: psutil.AccessDenied (pid=1)

And fix a test that is failing on Hydra because it tries to write to `/tmp`
    
    ________________________ TestCore.test_check_operators _________________________
    ...
    E           sqlite3.OperationalError: attempt to write a readonly database
    ...
    INFO     airflow.hooks.base:base.py:70 Using connection to: id: sqlite_default. Host: /tmp/sqlite_default.db, Port: None, Schema: None, Login: None, Password: None, extra: {}

Patch the database name to use `$TMPDIR` instead. It has been fixed in Apache Airflow 2.2.2 but the commit doesn't apply on top of 2.1.4, and I tried to update the package, but the 2.2.x tarballs (using `fetchFromGitHub`) do not contain any tests, so I gave up.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM

cc @NixOS/darwin-maintainers

**Review by r-burns — APPROVED** [review]
Result of `nixpkgs-review pr 146715` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>apache-airflow (python39Packages.apache-airflow)</li>
    <li>python38Packages.apache-airflow</li>
  </ul>
</details>

**Review by winterqt — APPROVED** [review]
Diff LGTM.

Have you tested that the functionality that is tested (or any functionality for that matter) still works? I'd test myself but I don't know the first thing about Airflow.

**Comment by winterqt** [comment]
Result of `nixpkgs-review pr 146715` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by smancill** [comment]
> Diff LGTM.
> 
> Have you tested that the functionality that is tested (or any functionality for that matter) still works? I'd test myself but I don't know the first thing about Airflow.

I did the [quickstart](https://airflow.incubator.apache.org/docs/apache-airflow/2.1.4/start/local.html) and it worked.

**Comment by reckenrode** [comment]
I think this is fine. The problem doesn’t appear to be related to Airflow itself. The test is enumerating processes and checking the command-lines for the one it wants to kill as part of the test. From what I can tell, the method psutil uses doesn’t always work. According to the [XNU source][1], access to the command-line arguments of other processes is restricted unless you have an entitlement. I ran the snippet in a terminal and got the same `AccessDenied` when it tried to get the command-line arguments of `launchd`. That matches the error in the `nix log` (pid 1 is `launchd`).

[1]: https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/kern/kern_sysctl.c#L1315

**Comment by reckenrode** [comment]
I also get “Nothing to be built.” when trying to run `nixpkgs-review` on aarch64-darwin. Seems to work fine when I specify `--system x86_64-darwin`.

```
2 packages built:
apache-airflow python38Packages.apache-airflow
```

**Review by bhipple — APPROVED** [review]
LGTM

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 146715` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>apache-airflow (python39Packages.apache-airflow)</li>
    <li>python38Packages.apache-airflow</li>
  </ul>
</details>

**Pull request merged**
