### PR TITLE
[WIP] Some work on getting the ARM bootstrap tools working.

### PR DESCRIPTION
**Pull request by ambrop72**
This is an attempt to fix the currently broken cross-compilation of ARM bootstrap tools.

The following fixes are needed before this will compile:
https://github.com/NixOS/nixpkgs/pull/6041
https://github.com/NixOS/nixpkgs/pull/6040
https://github.com/NixOS/nixpkgs/pull/6035
https://github.com/NixOS/nixpkgs/pull/5991
https://github.com/ambrop72/nixpkgs/commit/132f49f417c2f2dfe62fc7f576c18d6896cf064b (see https://github.com/NixOS/nixpkgs/issues/5949 )
https://github.com/NixOS/nixpkgs/pull/6070
https://github.com/ambrop72/nixpkgs/commit/9c337baa75d10413d652da666c855e5ddbfb03ed (see https://github.com/NixOS/nixpkgs/issues/5944 )

### CODE REVIEW

**Comment by bjornfor** [comment]
Reading https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/linux/make-bootstrap-tools-crosspi.nix... Could it be that you built the "build" attribute and not the "unpack" attribute? The latter seems to fixup the /nix/store/eeeeeee.... references.

**Comment by ambrop72** [comment]
Ah yes, I was mistakenly expecting it to work in a chroot.
I've did some more changes, and at this point it seems to be working - by that I mean, I am 10 minutes into a compile of Perl using these bootstrap-tools.

**Comment by bjornfor** [comment]
@ambrop72: Cool!

**Comment by viric** [comment]
I wasn't aware of this work. I'm natively making the arm5tel bootstrap tools, meantime.

**Comment by viric** [comment]
The recipe for bootstrap tools should be updated, I think. The tools built by the native make-bootstrap-tools.nix were updated this October. How are they working for you for the armv7 system? All fine?

**Comment by viric** [comment]
I see we are doing things in parallel. https://github.com/viric/nixpkgs/tree/make_arm_bootstraptools

**Comment by ambrop72** [comment]
@viric I am focusing on the cross bootstrap tools. After all my fixes, they work for armv7 and at least build for armv6. Here's some notes:

- The bootstrap tools unpacking in your branch is before it was changed to use busybox (119ce1ab03d0b3250e9e350f0686e095060014b0). I have fixed it to also use this approach for cross bootstrap-tools as well. In fact the `scripts/unpack-bootstrap-tools-arm.sh` should now be mv'd to `scripts/unpack-bootstrap-tools.sh` but I didn't do to it to avoid native mass rebuild.
- The `make-bootstrap-tools-crosspi.nix` is now a pretty close match to `make-bootstrap-tools.nix`, and I think in the future we can try to consolidate these two into a single file that works for both native and cross.
- The `make-bootstrap-tools-crosspi.nix` now allows easily selecting the exact ARM achitecture to build for (armv6l or armv7l, and armv5tel should be easy to add).

I believe there is value in having working cross-compilation of bootstrap tools. This simplifies porting to new architectures and variants of architectures.

I was specifically having problems using armv6t tools to bootstrap armv7l. The general issue is that the bootstrap gcc is used to build the final glibc. In the mentioned mismatch you end up with glibc compiled for armv6t rather than armv7t.

Finally, I've done fixes specific to armv7t (https://github.com/NixOS/nixpkgs/pull/6077 and https://github.com/NixOS/nixpkgs/pull/6080).

**Comment by ambrop72** [comment]
One more thing, as far as I can tell, the `unpack` code in the native `make-bootstrap-tools.nix` (both current and the older version you're working with)` is dead code only used for the test. The real unpack code is in `default.nix`. If we want the test it should be updated to use the non-dead code.

**Comment by ambrop72** [comment]
Closing in favor of #6184.

**Pull request closed without merging**
