### PR TITLE
bun: 1.0.7 -> 1.0.10

### LINKED ISSUE #265999: Update request: bun 1.0.7 → 1.0.9
- Package name: bun
- Latest released version: 1.0.9

- Current version on the unstable channel: 1.0.7
- Current version on the stable/release channel: 0.6.2

- [*] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@DAlperin @06kellyjac 

People who've also recently updated the package:

@cornedor @BlankParticle 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by cornedor**
## Description of changes

bun: 1.0.7 -> ~~1.0.9~~ 1.0.10

Closes https://github.com/NixOS/nixpkgs/issues/265999

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cornedor** [comment]
1.0.10 has already been released, updated the version again.

**Review by philiptaron — APPROVED** [review]
Changelog: https://github.com/oven-sh/bun/compare/bun-v1.0.7...bun-v1.0.10

**Comment by rupurt** [comment]
You da man @cornedor

**Review by cdmistman — APPROVED** [review]
works for me on aarch64-darwin

**Comment by rupurt** [comment]
Bun v1.0.11 was just released

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 266007` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bun</li>
  </ul>
</details>

**Comment by wegank** [comment]
Please open another PR for the new release, so that we can at least have an upgrade merged...

**Comment by rupurt** [comment]
I've created a nix flake if you need to install a version of bun that's not in the official nix repo yet https://github.com/rupurt/bun-nix

**Pull request merged**
