### PR TITLE
Ghc863 add haskellCompilerName and doc output

### PR DESCRIPTION
**Pull request by teto**
I am trying to use hie with ghc863 as ghc864 is not supported yet but met some problems along the way as ghc863 is missing attributes.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Note that this is ghc863Binary not ghc863. I'm under the impression it was just used for bootstrapping, although you can probably use it for other things as well.

**Comment by teto** [comment]
As a haskell beginner i don t know the diference between the binary version and other. Is the differznce documented anywhere ? Feel free to ignore if the request isn't valid.

**Comment by peti** [comment]
> As a haskell beginner i don t know the diference between the binary version and other.

The binary versions are downloaded from haskell.org for bootstrapping purposes. Their only purpose is to compile the real compiler from source and they are not supposed to be used for anything else.

**Review by peti — COMMENTED** [review]
I'd rather not give users the impression that pre-built binary compilers ought to be used just like the real ones. That compiler is supposed to bootstrap `ghc-8.6.3` and not much else.

:-1:

**Comment by teto** [comment]
I'll close then. thanks for feedback.

**Pull request closed without merging**
