### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by cdepillabout**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

---

This is the follow-up to #185574. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by cdepillabout** [comment]
@Kiwi It looks like brick has updated to version 1.0, which causes matterhorn to break again. In [323f8b5](https://github.com/NixOS/nixpkgs/pull/185755/commits/323f8b5d00065fde1b32af8a737e9b67875d6da2) I removed the matterhorn and brick overrides in order to start trying to get rid of eval errors.

If you wanted to fix this, I suggest first reverting my commit here and building on that revert.  Unless there are patches floating around for matterhorn + brick-1.0, it might just be easiest to generate brick-0.70 and brick-skylight in `extra-packages` in `pkgs/development/haskell-modules/configuration-hackage2nix/main.yaml`, and then use them.

**Comment by sternenseemann** [comment]
> @Kiwi It looks like brick has updated to version 1.0, which causes matterhorn to break again. In [323f8b5](https://github.com/NixOS/nixpkgs/pull/185755/commits/323f8b5d00065fde1b32af8a737e9b67875d6da2) I removed the matterhorn and brick overrides in order to start trying to get rid of eval errors.
> 
> If you wanted to fix this, I suggest first reverting my commit here and building on that revert. Unless there are patches floating around for matterhorn + brick-1.0, it might just be easiest to generate brick-0.70 and brick-skylight in `extra-packages` in `pkgs/development/haskell-modules/configuration-hackage2nix/main.yaml`, and then use them with matterhorn. That will keep us from having to update these overrides everytime a new version of brick is released.

Fixed the problem in [d8bddf3](https://github.com/NixOS/nixpkgs/pull/185755/commits/d8bddf35281fc7b9efffeece0f6530b99bcf61bd).

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by cdepillabout** [comment]
Ugh, NixOS XMonad tests appear to be now failing @NeQuissimus @ivanbrennan @peti:

https://github.com/cdepillabout/nix-haskell-updates-status/tree/815e45c0677d665f25af1799dbd412fd3f781a35

**Comment by cdepillabout** [comment]
@fpletz @kragniz It looks like there is an error on `master` when building `hedgewars`.  It doesn't appear haskell-related: https://hydra.nixos.org/build/187770554/nixlog/4.

**Pull request merged**
