### PR TITLE
nixos-install: clear executable cache after entering chroot

### PR DESCRIPTION
**Pull request by xaverdh**
Clear the cache for executable locations after entering the chroot. The cached locations are no longer valid there.

This ~~hopefully~~ indeed resolves problems with nixos-install failing to find binaries from coreutils as witnessed in https://github.com/NixOS/nixpkgs/issues/241356 fixing it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by poliorcetics** [comment]
@xaverdh first time I'm testing such a PR, how can I declare my nixpkgs as pointing to yours ?

I'm using flakes if that helps.

**Comment by xaverdh** [comment]
> @xaverdh first time I'm testing such a PR, how can I declare my nixpkgs as pointing to yours ?
> 
> I'm using flakes if that helps.

You can build the `nixos-install` script from this pr with
```sh
nix build github:NixOS/nixpkgs/refs/pull/355269/head#nixos-install
```
and then run `./result/bin/nixos-install`

**Comment by poliorcetics** [comment]
Confirmed working on my use case, I don't get the "X not in PATH" error with MR and I get it on regular nixpkgs

**Review by poliorcetics — APPROVED** [review]

**Comment by xaverdh** [comment]
cc @Mic92

**Comment by poliorcetics** [comment]
Using

```nix
    overlays = [
      # <https://github.com/NixOS/nixpkgs/pull/355269>
      (final: super: {
        nixos-install = super.nixos-install.overrideAttrs (old: {
          patches = old.patches or [ ] ++ [ ../patches/nixos-install-no-coreutils-caching.patch ];
        });
      })
    ];
```

with the most recent `nixpkgs-unstable` did not work.

I took the patch from https://github.com/NixOS/nixpkgs/pull/355269.patch

**Comment by xaverdh** [comment]
> Using
> 
> ```nix
>     overlays = [
>       # <https://github.com/NixOS/nixpkgs/pull/355269>
>       (final: super: {
>         nixos-install = super.nixos-install.overrideAttrs (old: {
>           patches = old.patches or [ ] ++ [ ../patches/nixos-install-no-coreutils-caching.patch ];
>         });
>       })
>     ];
> ```
> 
> with the most recent `nixpkgs-unstable` did not work.
> 
> I took the patch from https://github.com/NixOS/nixpkgs/pull/355269.patch
> 
> I may have done something wrong, but I'm unsure what if so

can you see the patch getting applied (in the build output)?

**Comment by xaverdh** [comment]
`ofborg` failure appears unrelated?

**Comment by tom-kuca** [comment]
I run into the issue, [the patch](https://github.com/NixOS/nixpkgs/pull/355269#issuecomment-2527527467) didn't fix it for me. 

Command:
```
sudo ./result/bin/nixos-install --flake '.#voyager' --verbose --debug
```

Output:
```
+ nixos-enter --root /mnt -c '      set -e
      # Clear the cache for executable locations. They were invalidated by the chroot.
      hash -r
      # Create a bind mount for each of the mount points inside the target file
      # system. This preserves the validity of their absolute paths after changing
      # the root with `nixos-enter`.
      # Without this the bootloader installation may fail due to options that
      # contain paths referenced during evaluation, like initrd.secrets.
      # when not root, re-execute the script in an unshared namespace
      mount --rbind --mkdir / "$mountPoint"
      mount --make-rslave "$mountPoint"
      /run/current-system/bin/switch-to-configuration boot
      umount -R "$mountPoint" && (rmdir "$mountPoint" 2>/dev/null || true)'
perl: warning: Setting locale failed.
... perl complains ...
/nix/var/nix/profiles/system/sw/bin/bash: line 10: mount: command not found
```

I see the same error without the patch, only on line 8.

I'm on arch linux. I run into it when I tried to setup a new system using `disko-install`, later I tried `nixos-install` directly.

**Comment by Mic92** [comment]
The original bug fix was for coreutils. Not finding mount might be a different bug.

**Comment by xaverdh** [comment]
@ tom-kuca can you try adding
```sh
. /etc/profile
``` 
right after (or instead of) `hash -r` in that script?

**Comment by tom-kuca** [comment]
@xaverdh It works, the script finishes successfuly.

**Comment by xaverdh** [comment]
here you go: https://github.com/NixOS/nixpkgs/pull/365403

**Pull request merged**
