### PR TITLE
stdenv: Move devhelp books to outputDevdoc

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
For cleaner nix expressions.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Is that some kind of successor to gtk-doc?

**Comment by jtojnar** [comment]
DevHelp is a documentation viewer. It can read content generated by gtk-doc, provided that index file is added to share/devhelp/books.

Currently testing by building `libhttpseverywhere` from #30352 with `fixupPhase` removed.

**Review by vcunat — APPROVED** [review]

**Comment by orivej** [comment]
@jtojnar Could you show `ls /run/current-system/sw/share/devhelp/books` on your system?

**Comment by jtojnar** [comment]
@orivej Personally, I do not have any books installed. We need it for `libhttpseverywhere` (#30352) and other tools which install them.

**Comment by orivej** [comment]
OK, `nix-index` shows that these derivations install devhelp books, currently in `out`: `gnome2.libglademm gnome3.vala libxmlxx libxmlxx3 vala_0_23 vala_0_26 vala_0_28 vala_0_34 vala_0_38`. Please make sure that all of them define `devdoc` output, and update `doc/multiple-output.xml`.

**Comment by jtojnar** [comment]
Done, though I am unable to build it now.

**Comment by jtojnar** [comment]
Also did you accidentally omit `vala_0_32`?

**Comment by orivej** [comment]
> Also did you omit `vala_0_32` accidentally?

I've refreshed `nix-index` before querying, but `nix-locate` did not list `vala_0_32`, don't know why.

**Comment by orivej** [comment]
I think that the part of `doc/multiple-output.xml` that mentions `gtk-doc` should be updated.

**Comment by jtojnar** [comment]
I updated it with the stdenv update.

**Review by orivej — APPROVED** [review]

**Comment by vcunat** [comment]
> I've refreshed `nix-index` before querying, but `nix-locate` did not list `vala_0_32`, don't know why.

@orivej: the directory is there on master.  If you don't define an output for dev docs, they get removed by default.

**Comment by orivej** [comment]
@vcunat I don't see any reason why `vala_0_32` may be absent from `nix-index` while `vala_0_28` et al. are present (and `vala_0_32` is in the binary cache). /cc @bennofs

**Comment by bennofs** [comment]
@vcunat @orivej `gnome3.vala` is the same as `vala_0_32`, and nix-index lists the former one:

```
gnome3.vala.out                                       1 d /nix/store/hjcp5p1w5c5mjqsa75vypcaq398lz9n4-vala-0.32.1/share/devhelp/books
```

**Pull request merged**
