### PR TITLE
steamPackages.steam-runtime: 0.20200720.0 → 0.20201203.1

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
bump the steam-runtime, having issues with crusader kings III

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ryantm — APPROVED** [review]

**Comment by ryantm** [comment]
Result of `nixpkgs-review pr 106393` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>kodiPlugins.steam-launcher</li>
    <li>lutris</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steamcmd</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 106393` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>kodiPlugins.steam-launcher</li>
    <li>lutris</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steamcmd</li>
  </ul>
</details>

**Review by lovesegfault — APPROVED** [review]

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/106393
5 packages built:
kodiPlugins.steam-launcher lutris steam steam-run steamcmd
```

**Comment by jonringer** [comment]
was able to start csgo

**Comment by srhb** [comment]
Should this be backported as well?

**Pull request merged**
