### PR TITLE
Gitlab tools

### PR DESCRIPTION
**Pull request by wucke13**
###### Description of changes
This includes a set of tools required to thoroughly integrate rust projects into GitLab:

+ `gitlab-clippy`, which allows to create a gitlab code quality reports from clippy lints
+ `lcov_cobertura`, which allows to convert llvm lcov coverage reports to the cobertura format required by GitLab
+ `cargo-llvm-cov` to generate lcov coverage data

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wucke13** [comment]
@GrahamcOfBorg build cargo-llvm-cov python3Packages.lcov_cobertura gitlab-clippy

**Comment by wucke13** [comment]
@DieracDelta you mentioned `cargo-llvm-cov` over in https://github.com/taiki-e/cargo-llvm-cov/pull/152 . Maybe I can interest you in reviewing this PR which also includes `cargo-llvm-cov`?

**Comment by wucke13** [comment]
@Lassulus would you mind taking a look? :smiley_cat:

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 192813` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>cargo-llvm-cov</li>
    <li>gitlab-clippy</li>
    <li>python310Packages.lcov_cobertura</li>
    <li>python39Packages.lcov_cobertura</li>
  </ul>
</details>

**Pull request merged**
