### PR TITLE
hidapi: 0.10.1 -> 0.11.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update - https://github.com/libusb/hidapi/releases/tag/hidapi-0.11.0
- switch buildsystem to cmake

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
ping @jonringer @tomberek @nrdxp

**Comment by prusnak** [comment]
@GrahamcOfBorg build hidapi

**Comment by nrdxp** [comment]
Result of `nixpkgs-review pr 142016` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages failed to build:</summary>
  <ul>
    <li>dolphinEmuMaster</li>
    <li>flexoptix-app</li>
    <li>footswitch</li>
    <li>gen-oath-safe</li>
    <li>haskellPackages.hid</li>
    <li>hidapi</li>
    <li>libretro.dolphin</li>
    <li>libu2f-host</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>mixxx</li>
    <li>monado</li>
    <li>monero</li>
    <li>monero-gui</li>
    <li>mspds</li>
    <li>nitrokey-app</li>
    <li>openhmd</li>
    <li>openocd</li>
    <li>openrgb</li>
    <li>oxen</li>
    <li>python38Packages.hid</li>
    <li>python39Packages.hid</li>
    <li>qmk</li>
    <li>tinygo</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager-qt</li>
    <li>yubioath-desktop</li>
  </ul>
</details>

**Comment by prusnak** [comment]
> Result of `nixpkgs-review pr 142016` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

Seeing build log of hidapi would help. 

CI is fubared: https://logs.nix.ci/?key=nixos/nixpkgs.142016&attempt_id=2ce4d9e2-3419-4f0c-9acd-503422f8b739

**Comment by nrdxp** [comment]
hmm, there may just be something up with that nixpkgs review run, because the `hidapi` package actually built just fine and manually rebuilding is a noops since it already exists in the store. Strange.

**Comment by nrdxp** [comment]
hmm, there may just be something up with that nixpkgs review run, because the hidapi package actually built just fine and manually rebuilding is a noops since it already exists in the store. Strange.

**Comment by avdv** [comment]
> macOS: droped support of macOS 10.5 and earlier (#121);

Does this pose any compatibility issues for NixOS on darwin?

**Comment by jonringer** [comment]
cc @NixOS/darwin-maintainers  on darwin build

**Comment by prusnak** [comment]
> Does this pose any compatibility issues for NixOS on darwin?

I don't think so. MacOS 10.5 is super old, EOL was in 2015.

**Review by Artturin — APPROVED** [review]

**Comment by toonn** [comment]
I was trying to run a nixpkgs-review on x86_64-darwin but it looked like I had to build 11k+ packages? One of my substituters has been timing out though, maybe that's the cause?

**Comment by Artturin** [comment]
> I was trying to run a nixpkgs-review on x86_64-darwin but it looked like I had to build 11k+ packages? One of my substituters has been timing out though, maybe that's the cause?

`nixpkgs-review pr 142016 -p hidapi`

**Pull request merged**
