### PR TITLE
python311Packages.sqlalchemy_1_4: init at 1.4.51

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes

The removal of sqlalchemy 1.4.x should have been more graceful, since we forced many applications to create overrides, that went out of date quickly.

Reintroduce at 1.4.51 (released an hour ago) and replace outdated overrides.

This version should not be used in the python package set, only in overrides.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 278396` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>databricks-sql-cli</li>
    <li>databricks-sql-cli.dist</li>
    <li>fabs</li>
    <li>fabs.dist</li>
    <li>fabs.man</li>
    <li>python310Packages.databricks-sql-connector</li>
    <li>python310Packages.databricks-sql-connector.dist</li>
    <li>python310Packages.dataset</li>
    <li>python310Packages.dataset.dist</li>
    <li>python310Packages.oslo-db</li>
    <li>python310Packages.oslo-db.dist</li>
    <li>python310Packages.subunit2sql</li>
    <li>python310Packages.subunit2sql.dist</li>
    <li>python311Packages.databricks-sql-connector</li>
    <li>python311Packages.databricks-sql-connector.dist</li>
    <li>python311Packages.dataset</li>
    <li>python311Packages.dataset.dist</li>
    <li>python311Packages.oslo-db</li>
    <li>python311Packages.oslo-db.dist</li>
    <li>python311Packages.subunit2sql</li>
    <li>python311Packages.subunit2sql.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>mailman</li>
    <li>mailman-hyperkitty</li>
    <li>mailman-hyperkitty.dist</li>
    <li>mailman.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
  </ul>
</details>
<details>
  <summary>165 packages built:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>buildbot</li>
    <li>buildbot-full</li>
    <li>buildbot-ui</li>
    <li>buildbot.dist</li>
    <li>calibre-web</li>
    <li>calibre-web.dist</li>
    <li>csvkit</li>
    <li>csvkit.dist</li>
    <li>cum</li>
    <li>cum.dist</li>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>fit-trackee</li>
    <li>fit-trackee.dist</li>
    <li>instawow</li>
    <li>instawow.dist</li>
    <li>irrd</li>
    <li>irrd.dist</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>ntfy</li>
    <li>ntfy.dist</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>powerdns-admin</li>
    <li>pyCA</li>
    <li>pyCA.dist</li>
    <li>python310Packages.alembic</li>
    <li>python310Packages.alembic.dist</li>
    <li>python310Packages.automx2</li>
    <li>python310Packages.automx2.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.flask-admin</li>
    <li>python310Packages.flask-admin.dist</li>
    <li>python310Packages.flask-dramatiq</li>
    <li>python310Packages.flask-dramatiq.dist</li>
    <li>python310Packages.flask-migrate</li>
    <li>python310Packages.flask-migrate.dist</li>
    <li>python310Packages.geoalchemy2</li>
    <li>python310Packages.geoalchemy2.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.mlflow</li>
    <li>python310Packages.mlflow.dist</li>
    <li>python310Packages.mmcv</li>
    <li>python310Packages.mmcv.dist</li>
    <li>python310Packages.mmengine</li>
    <li>python310Packages.mmengine.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python310Packages.optuna</li>
    <li>python310Packages.optuna.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.spacy-loggers.dist</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.sqlalchemy_1_4</li>
    <li>python310Packages.sqlalchemy_1_4.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.wandb.dist</li>
    <li>python311Packages.alembic</li>
    <li>python311Packages.alembic.dist</li>
    <li>python311Packages.automx2</li>
    <li>python311Packages.automx2.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.flask-admin</li>
    <li>python311Packages.flask-admin.dist</li>
    <li>python311Packages.flask-dramatiq</li>
    <li>python311Packages.flask-dramatiq.dist</li>
    <li>python311Packages.flask-migrate</li>
    <li>python311Packages.flask-migrate.dist</li>
    <li>python311Packages.geoalchemy2</li>
    <li>python311Packages.geoalchemy2.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.optuna.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.sqlalchemy_1_4</li>
    <li>python311Packages.sqlalchemy_1_4.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.wandb</li>
    <li>python311Packages.wandb.dist</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.buildsrht.dist</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.coresrht.dist</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.gitsrht.dist</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hgsrht.dist</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.hubsrht.dist</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.listssrht.dist</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.mansrht.dist</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.metasrht.dist</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.pastesrht.dist</li>
    <li>sourcehut.todosrht</li>
    <li>sourcehut.todosrht.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Remaining failures are on the target branch.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 278396` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>databricks-sql-cli</li>
    <li>databricks-sql-cli.dist</li>
    <li>fabs</li>
    <li>fabs.dist</li>
    <li>fabs.man</li>
    <li>python310Packages.databricks-sql-connector</li>
    <li>python310Packages.databricks-sql-connector.dist</li>
    <li>python310Packages.dataset</li>
    <li>python310Packages.dataset.dist</li>
    <li>python310Packages.oslo-db</li>
    <li>python310Packages.oslo-db.dist</li>
    <li>python310Packages.subunit2sql</li>
    <li>python310Packages.subunit2sql.dist</li>
    <li>python311Packages.databricks-sql-connector</li>
    <li>python311Packages.databricks-sql-connector.dist</li>
    <li>python311Packages.dataset</li>
    <li>python311Packages.dataset.dist</li>
    <li>python311Packages.oslo-db</li>
    <li>python311Packages.oslo-db.dist</li>
    <li>python311Packages.subunit2sql</li>
    <li>python311Packages.subunit2sql.dist</li>
  </ul>
</details>
<details>
  <summary>173 packages built:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>buildbot</li>
    <li>buildbot-full</li>
    <li>buildbot-ui</li>
    <li>buildbot.dist</li>
    <li>calibre-web</li>
    <li>calibre-web.dist</li>
    <li>csvkit</li>
    <li>csvkit.dist</li>
    <li>cum</li>
    <li>cum.dist</li>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>fit-trackee</li>
    <li>fit-trackee.dist</li>
    <li>instawow</li>
    <li>instawow.dist</li>
    <li>irrd</li>
    <li>irrd.dist</li>
    <li>mailman</li>
    <li>mailman-hyperkitty</li>
    <li>mailman-hyperkitty.dist</li>
    <li>mailman.dist</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>ntfy</li>
    <li>ntfy.dist</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>powerdns-admin</li>
    <li>pyCA</li>
    <li>pyCA.dist</li>
    <li>python310Packages.alembic</li>
    <li>python310Packages.alembic.dist</li>
    <li>python310Packages.automx2</li>
    <li>python310Packages.automx2.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.flask-admin</li>
    <li>python310Packages.flask-admin.dist</li>
    <li>python310Packages.flask-dramatiq</li>
    <li>python310Packages.flask-dramatiq.dist</li>
    <li>python310Packages.flask-migrate</li>
    <li>python310Packages.flask-migrate.dist</li>
    <li>python310Packages.geoalchemy2</li>
    <li>python310Packages.geoalchemy2.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.mlflow</li>
    <li>python310Packages.mlflow.dist</li>
    <li>python310Packages.mmcv</li>
    <li>python310Packages.mmcv.dist</li>
    <li>python310Packages.mmengine</li>
    <li>python310Packages.mmengine.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python310Packages.optuna</li>
    <li>python310Packages.optuna.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.spacy-loggers.dist</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.sqlalchemy_1_4</li>
    <li>python310Packages.sqlalchemy_1_4.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.wandb.dist</li>
    <li>python311Packages.alembic</li>
    <li>python311Packages.alembic.dist</li>
    <li>python311Packages.automx2</li>
    <li>python311Packages.automx2.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.flask-admin</li>
    <li>python311Packages.flask-admin.dist</li>
    <li>python311Packages.flask-dramatiq</li>
    <li>python311Packages.flask-dramatiq.dist</li>
    <li>python311Packages.flask-migrate</li>
    <li>python311Packages.flask-migrate.dist</li>
    <li>python311Packages.geoalchemy2</li>
    <li>python311Packages.geoalchemy2.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.optuna.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.sqlalchemy_1_4</li>
    <li>python311Packages.sqlalchemy_1_4.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.wandb</li>
    <li>python311Packages.wandb.dist</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.buildsrht.dist</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.coresrht.dist</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.gitsrht.dist</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hgsrht.dist</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.hubsrht.dist</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.listssrht.dist</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.mansrht.dist</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.metasrht.dist</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.pastesrht.dist</li>
    <li>sourcehut.todosrht</li>
    <li>sourcehut.todosrht.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Comment by zowoq** [comment]
https://hydra.nixos.org/build/246233876/nixlog/1
```
Checking runtime dependencies for buildbot-3.10.1-py3-none-any.whl
  - sqlalchemy<1.5,>=1.3.0 not satisfied by version 1.4.51.dev0
```

https://github.com/NixOS/nixpkgs/blob/87b9bf8ea4bf9f961376e44a2c9d5ea9a5cf9207/pkgs/development/python-modules/sqlalchemy/default.nix#L55-L57

Seems the postPatch is needed for 1_4 so I've opened https://github.com/NixOS/nixpkgs/pull/281060.

**Comment by mweinelt** [comment]
Already merged, since I introduced the workaround for sqlalchemy 2.0 myself.

**Pull request merged**
