### PR TITLE
Add user channels to the default nix path

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

See https://github.com/NixOS/nix/issues/2033

I'll backport upon merge.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [X] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

```
$ nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgsunstable

$ nix-channel --update
unpacking channels...
created 5 symlinks in user environment

$ nix-build '<nixpkgsunstable>' -A gitFull            
/nix/store/9i8vdd4757xnvyflf0fhszjw74cy74ib-git-2.16.2

$ nix run -f '<nixpkgsunstable>' gitFull  

[grahamc@Morbo:~]$ which git
/nix/store/9i8vdd4757xnvyflf0fhszjw74cy74ib-git-2.16.2/bin/git

[grahamc@Morbo:~]$ exit

$ nix-instantiate -E '(import <nixpkgsunstable> {}).gitFull'
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/2iz7n7x4rldrn4dg9s5bg6a3qlxna7ms-git-2.16.2.drv
```

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg test openssh
@GrahamcOfBorg test login
@GrahamcOfBorg test env

**Comment by grahamc** [comment]
The two tests which failed seem due to the hosts not running 2.0. I'll look in to that. In the meantime, this patch works for me and the tests pass locally.

**Comment by vcunat** [comment]
I would probably switch the new line with the first line, because I think (1) per-user NIX_PATH elements should be given preference in comparison to (system-wide) root's elements, and (2) the root's elements should be "together".

**Comment by grahamc** [comment]
Agreed, updated.

**Review by vcunat — APPROVED** [review]
Yes, I think so, including cherry-pick to 18.03.

**Review by shlevy — APPROVED** [review]
:ship:

**Review by infinisil — APPROVED** [review]

**Review by disassembler — APPROVED** [review]

**Comment by vcunat** [comment]
I'm slightly scared of being very hasty about such changes.

@edolstra: can you confirm this wasn't some intentional design decision?  Apparently `nix-env` has `~/.nix-defexpr` used for this purpose, but `$NIX_PATH` feels a much better way (more uniform), so going this way seems good.  I hope we're not missing something.

**Comment by edolstra** [comment]
Well, this change doesn't make `nix-env` use `NIX_PATH`, so nothing really changes wrt `nix-env`.

**Comment by grahamc** [comment]
Update: Choosing not to backport this for now.

**Review by lheckemann — APPROVED** [review]
I like it. I agree it shouldn't be backported though — and this means it should go in the 18.09 release notes, not the 18.03 ones, right?

**Pull request merged**
