### PR TITLE
pythonPackages.jsonschema: 2.6.0 -> 3.0.2

### PR DESCRIPTION
**Pull request by jbaum98**
###### Motivation for this change

Update `jsonschema` to the latest version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @domenkozar

### CODE REVIEW

**Comment by jonringer** [comment]
this breaks around 40 packages, I would hold off for a while until downstream packages have time to bump.

**Comment by worldofpeace** [comment]
Didn't @costrouc already do this and it got merged to python-unstable with other things?

@FRidh You never did explain to me the situation with python-unstable, because I recall when the topic came up of updating this you said we should use that branch.

**Comment by FRidh** [comment]
I use `python-unstable` to check typically selections of commits and force push to that branch.

**Comment by FRidh** [comment]
This is a duplicate.

**Pull request closed without merging**
