### PR TITLE
nixpkgs-check-by-name: 0.1.0 -> 0.1.1

### PR DESCRIPTION
**Pull request by infinixbot**
This is an automated PR to update the version of [nixpkgs-check-by-name](https://github.com/NixOS/nixpkgs-check-by-name), which is used by CI to [check the `pkgs/by-name`](https://github.com/NixOS/nixpkgs/tree/6347cd23dcc2b020dd4ea5bfe5871be35e95ae63/pkgs/by-name#validation) directory. The update was performed by running [`pkgs/test/check-by-name/update-pinned-tool.sh`](https://github.com/NixOS/nixpkgs/tree/6347cd23dcc2b020dd4ea5bfe5871be35e95ae63/pkgs/test/check-by-name#update-pinned-toolsh).
This PR updates the tool to [version 0.1.1](https://github.com/NixOS/nixpkgs-check-by-name/releases/tag/0.1.1).

### CODE REVIEW

**Comment by infinisil** [comment]
We're still [figuring out changelogs](https://github.com/NixOS/nixpkgs-check-by-name/issues/38) for nixpkgs-check-by-name, so for now I'll just briefly mention the main changes manually:
- Print relative paths in Nix expressions the same in all error messages by @willbush in https://github.com/NixOS/nixpkgs-check-by-name/pull/33
- Don't show Nix evaluation stderr if there's no failure, avoiding a bunch of warning traces by @infinisil in https://github.com/NixOS/nixpkgs-check-by-name/pull/35

**Review by philiptaron — APPROVED** [review]
# 🏞️ 
Let's keep it green.

**Comment by infinisil** [comment]
I think I should merge these updates myself, because they have the potential to break CI. It's fine for now though, but I guess we should put this more explicitly in the PR description :)

**Comment by pSub** [comment]
@infinisil: I'm sorry about that. I hope it won't break anything. The PR looked ready for me. Maybe nexttime you want to assign it to yourself. That would've prevented (at least) me from merging it. 😃

**Comment by infinisil** [comment]
No worries, CI seems to work just fine, assigning to me sounds good for next time :)

**Pull request merged**
