### PR TITLE
pythonPackages.*: Disable tests, nasc: Fix compilation with gcc10

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
> nasc: Fix compilation by using gcc9

This should be the last resort. Is it really not possible to stay with 10?

**Comment by SuperSandro2000** [comment]
> This should be the last resort. Is it really not possible to stay with 10?

```
/nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
   32 | #warning \
      |  ^~~~~~~
In file included from /nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/ext/hash_map:64,
                 from ../subprojects/libqalculate/libqalculate/Calculator_p.h:30,
                 from ../subprojects/libqalculate/libqalculate/Calculator-definitions.cc:63:
/nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/backward/hashtable.h: In instantiation of '__gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::size_type __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num_key(const key_type&, std::size_t) const [with _Val = std::pair<Unit* const, bool>; _Key = Unit*; _HashFcn = __gnu_cxx::hash<Unit*>; _ExtractKey = std::_Select1st<std::pair<Unit* const, bool> >; _EqualKey = std::equal_to<Unit*>; _Alloc = std::allocator<bool>; __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::size_type = long unsigned int; __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::key_type = Unit*; std::size_t = long unsigned int]':
/nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/backward/hashtable.h:596:30:   required from '__gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::size_type __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::_M_bkt_num_key(const key_type&) const [with _Val = std::pair<Unit* const, bool>; _Key = Unit*; _HashFcn = __gnu_cxx::hash<Unit*>; _ExtractKey = std::_Select1st<std::pair<Unit* const, bool> >; _EqualKey = std::equal_to<Unit*>; _Alloc = std::allocator<bool>; __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::size_type = long unsigned int; __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::key_type = Unit*]'
/nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/backward/hashtable.h:519:32:   required from '__gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::iterator __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::find(const key_type&) [with _Val = std::pair<Unit* const, bool>; _Key = Unit*; _HashFcn = __gnu_cxx::hash<Unit*>; _ExtractKey = std::_Select1st<std::pair<Unit* const, bool> >; _EqualKey = std::equal_to<Unit*>; _Alloc = std::allocator<bool>; __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::iterator = __gnu_cxx::hashtable<std::pair<Unit* const, bool>, Unit*, __gnu_cxx::hash<Unit*>, std::_Select1st<std::pair<Unit* const, bool> >, std::equal_to<Unit*>, std::allocator<bool> >::iterator; __gnu_cxx::hashtable<_Val, _Key, _HashFcn, _ExtractKey, _EqualKey, _Alloc>::key_type = Unit*]'
/nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/ext/hash_map:213:26:   required from '__gnu_cxx::hash_map<_Key, _Tp, _HashFn, _EqualKey, _Alloc>::iterator __gnu_cxx::hash_map<_Key, _Tp, _HashFn, _EqualKey, _Alloc>::find(const key_type&) [with _Key = Unit*; _Tp = bool; _HashFn = __gnu_cxx::hash<Unit*>; _EqualKey = std::equal_to<Unit*>; _Alloc = std::allocator<bool>; __gnu_cxx::hash_map<_Key, _Tp, _HashFn, _EqualKey, _Alloc>::iterator = __gnu_cxx::hashtable<std::pair<Unit* const, bool>, Unit*, __gnu_cxx::hash<Unit*>, std::_Select1st<std::pair<Unit* const, bool> >, std::equal_to<Unit*>, std::allocator<bool> >::iterator; __gnu_cxx::hash_map<_Key, _Tp, _HashFn, _EqualKey, _Alloc>::key_type = Unit*]'
../subprojects/libqalculate/libqalculate/Calculator-definitions.cc:3432:23:   required from here
/nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/backward/hashtable.h:604:23: error: no match for call to '(const hasher {aka const __gnu_cxx::hash<Unit*>}) (Unit* const&)'
  604 |       { return _M_hash(__key) % __n; }
      |                ~~~~~~~^~~~~~~
ninja: build stopped: subcommand failed.
builder for '/nix/store/bqmbrh4gbgvkdj5wr4x56pnyz6732gkm-nasc-0.7.5.drv' failed with exit code 1
error: build of '/nix/store/bqmbrh4gbgvkdj5wr4x56pnyz6732gkm-nasc-0.7.5.drv' failed
```

but I maybe have found a patch to fix this.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108925` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>gnomecast</li>
<li>python39Packages.cliff</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.cliff: log was empty</li>
<li>python37Packages.worldengine: log <a href="https://termbin.com/j479">https://termbin.com/j479</a></li>
<li>python38Packages.worldengine: log <a href="https://termbin.com/x5zr">https://termbin.com/x5zr</a></li>
<li>python39Packages.worldengine: log <a href="https://termbin.com/dud9">https://termbin.com/dud9</a></li>
  </ul>
</details>
<details>
<summary>
51 packages built:
</summary>
<ul>
<li>afew</li>
<li>lieer (gmailieer)</li>
<li>python37Packages.geopandas</li>
<li>python37Packages.howdoi</li>
<li>python37Packages.keep</li>
<li>python37Packages.notmuch</li>
<li>python37Packages.notmuch2</li>
<li>python37Packages.osmnx</li>
<li>python37Packages.pyls-black</li>
<li>python37Packages.pyls-isort</li>
<li>python37Packages.pyls-mypy</li>
<li>python37Packages.pyls-spyder</li>
<li>python37Packages.python-jsonrpc-server</li>
<li>python37Packages.python-language-server</li>
<li>python37Packages.pytile</li>
<li>python37Packages.scrapy</li>
<li>python37Packages.scrapy-deltafetch</li>
<li>python37Packages.scrapy-fake-useragent</li>
<li>python37Packages.scrapy-splash</li>
<li>python37Packages.three-merge</li>
<li>python38Packages.cliff</li>
<li>python38Packages.geopandas</li>
<li>python38Packages.howdoi</li>
<li>python38Packages.keep</li>
<li>python38Packages.notmuch</li>
<li>python38Packages.notmuch2</li>
<li>python38Packages.osmnx</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyls-black</li>
<li>python38Packages.pyls-isort</li>
<li>python38Packages.pyls-mypy</li>
<li>python38Packages.pyls-spyder</li>
<li>python38Packages.python-jsonrpc-server</li>
<li>python38Packages.python-language-server</li>
<li>python38Packages.pytile</li>
<li>python38Packages.scrapy</li>
<li>python38Packages.scrapy-deltafetch</li>
<li>python38Packages.scrapy-fake-useragent</li>
<li>python38Packages.scrapy-splash</li>
<li>python38Packages.three-merge</li>
<li>python39Packages.howdoi</li>
<li>python39Packages.keep</li>
<li>python39Packages.notmuch</li>
<li>python39Packages.notmuch2</li>
<li>python39Packages.pyhaversion</li>
<li>python39Packages.python-jsonrpc-server</li>
<li>python39Packages.scrapy</li>
<li>python39Packages.scrapy-deltafetch</li>
<li>python39Packages.scrapy-fake-useragent</li>
<li>python39Packages.scrapy-splash</li>
<li>python39Packages.three-merge</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.pyls-spyder:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.pyls-spyder:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108925` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.cliff</li>
</ul>
</details>
<details>

  <summary>6 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.optuna: log was empty</li>
<li>python37Packages.worldengine: log <a href="https://termbin.com/738l">https://termbin.com/738l</a></li>
<li>python38Packages.optuna: log was empty</li>
<li>python38Packages.worldengine: log <a href="https://termbin.com/z0ou">https://termbin.com/z0ou</a></li>
<li>python39Packages.worldengine: log <a href="https://termbin.com/sb4n">https://termbin.com/sb4n</a></li>
<li>swaglyrics: log <a href="https://termbin.com/06n8">https://termbin.com/06n8</a></li>
  </ul>
</details>
<details>
<summary>
56 packages built:
</summary>
<ul>
<li>afew</li>
<li>alot</li>
<li>lieer (gmailieer)</li>
<li>gnomecast</li>
<li>nasc</li>
<li>python37Packages.alot</li>
<li>python37Packages.cliff</li>
<li>python37Packages.guestfs</li>
<li>python37Packages.howdoi</li>
<li>python37Packages.keep</li>
<li>python37Packages.notmuch</li>
<li>python37Packages.notmuch2</li>
<li>python37Packages.pyls-black</li>
<li>python37Packages.pyls-isort</li>
<li>python37Packages.pyls-mypy</li>
<li>python37Packages.pyls-spyder</li>
<li>python37Packages.python-jsonrpc-server</li>
<li>python37Packages.python-language-server</li>
<li>python37Packages.scrapy-deltafetch</li>
<li>python37Packages.scrapy-splash</li>
<li>python37Packages.spyder</li>
<li>python37Packages.swspotify</li>
<li>python37Packages.three-merge</li>
<li>python37Packages.xdot</li>
<li>python38Packages.cliff</li>
<li>python38Packages.guestfs</li>
<li>python38Packages.howdoi</li>
<li>python38Packages.keep</li>
<li>python38Packages.notmuch</li>
<li>python38Packages.notmuch2</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyls-black</li>
<li>python38Packages.pyls-isort</li>
<li>python38Packages.pyls-mypy</li>
<li>python38Packages.pyls-spyder</li>
<li>python38Packages.python-jsonrpc-server</li>
<li>python38Packages.python-language-server</li>
<li>python38Packages.scrapy-deltafetch</li>
<li>python38Packages.scrapy-splash</li>
<li>spyder (python38Packages.spyder)</li>
<li>python38Packages.swspotify</li>
<li>python38Packages.three-merge</li>
<li>xdot (python38Packages.xdot)</li>
<li>python39Packages.alot</li>
<li>python39Packages.guestfs</li>
<li>python39Packages.howdoi</li>
<li>python39Packages.keep</li>
<li>python39Packages.notmuch</li>
<li>python39Packages.notmuch2</li>
<li>python39Packages.pyhaversion</li>
<li>python39Packages.python-jsonrpc-server</li>
<li>python39Packages.scrapy-deltafetch</li>
<li>python39Packages.scrapy-splash</li>
<li>python39Packages.swspotify</li>
<li>python39Packages.three-merge</li>
<li>python39Packages.xdot</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.pyls-spyder:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.pyls-spyder:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108925` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>gnomecast</li>
<li>python37Packages.guestfs</li>
<li>python37Packages.optuna</li>
<li>python38Packages.guestfs</li>
<li>python38Packages.optuna</li>
<li>python39Packages.cliff</li>
<li>python39Packages.guestfs</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>python37Packages.cliff: log was empty</li>
  </ul>
</details>
<details>
<summary>
54 packages built:
</summary>
<ul>
<li>afew</li>
<li>lieer</li>
<li>python37Packages.geopandas</li>
<li>python37Packages.howdoi</li>
<li>python37Packages.keep</li>
<li>python37Packages.notmuch</li>
<li>python37Packages.notmuch2</li>
<li>python37Packages.osmnx</li>
<li>python37Packages.pyls-black</li>
<li>python37Packages.pyls-isort</li>
<li>python37Packages.pyls-mypy</li>
<li>python37Packages.pyls-spyder</li>
<li>python37Packages.python-jsonrpc-server</li>
<li>python37Packages.python-language-server</li>
<li>python37Packages.pytile</li>
<li>python37Packages.scrapy</li>
<li>python37Packages.scrapy-deltafetch</li>
<li>python37Packages.scrapy-fake-useragent</li>
<li>python37Packages.scrapy-splash</li>
<li>python37Packages.three-merge</li>
<li>python37Packages.worldengine</li>
<li>python38Packages.cliff</li>
<li>python38Packages.geopandas</li>
<li>python38Packages.howdoi</li>
<li>python38Packages.keep</li>
<li>python38Packages.notmuch</li>
<li>python38Packages.notmuch2</li>
<li>python38Packages.osmnx</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyls-black</li>
<li>python38Packages.pyls-isort</li>
<li>python38Packages.pyls-mypy</li>
<li>python38Packages.pyls-spyder</li>
<li>python38Packages.python-jsonrpc-server</li>
<li>python38Packages.python-language-server</li>
<li>python38Packages.pytile</li>
<li>python38Packages.scrapy</li>
<li>python38Packages.scrapy-deltafetch</li>
<li>python38Packages.scrapy-fake-useragent</li>
<li>python38Packages.scrapy-splash</li>
<li>python38Packages.three-merge</li>
<li>worldengine-cli (python38Packages.worldengine)</li>
<li>python39Packages.howdoi</li>
<li>python39Packages.keep</li>
<li>python39Packages.notmuch</li>
<li>python39Packages.notmuch2</li>
<li>python39Packages.pyhaversion</li>
<li>python39Packages.python-jsonrpc-server</li>
<li>python39Packages.scrapy</li>
<li>python39Packages.scrapy-deltafetch</li>
<li>python39Packages.scrapy-fake-useragent</li>
<li>python39Packages.scrapy-splash</li>
<li>python39Packages.three-merge</li>
<li>python39Packages.worldengine</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108925` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.cliff</li>
</ul>
</details>
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.optuna: log was empty</li>
<li>python38Packages.optuna: log was empty</li>
<li>swaglyrics: log <a href="https://termbin.com/ii7fm">https://termbin.com/ii7fm</a></li>
  </ul>
</details>
<details>
<summary>
59 packages built:
</summary>
<ul>
<li>afew</li>
<li>alot (python38Packages.alot)</li>
<li>gnomecast</li>
<li>lieer</li>
<li>nasc</li>
<li>python37Packages.alot</li>
<li>python37Packages.cliff</li>
<li>python37Packages.guestfs</li>
<li>python37Packages.howdoi</li>
<li>python37Packages.keep</li>
<li>python37Packages.notmuch</li>
<li>python37Packages.notmuch2</li>
<li>python37Packages.pyls-black</li>
<li>python37Packages.pyls-isort</li>
<li>python37Packages.pyls-mypy</li>
<li>python37Packages.pyls-spyder</li>
<li>python37Packages.python-jsonrpc-server</li>
<li>python37Packages.python-language-server</li>
<li>python37Packages.scrapy-deltafetch</li>
<li>python37Packages.scrapy-splash</li>
<li>python37Packages.spyder</li>
<li>python37Packages.swspotify</li>
<li>python37Packages.three-merge</li>
<li>python37Packages.worldengine</li>
<li>python37Packages.xdot</li>
<li>python38Packages.cliff</li>
<li>python38Packages.guestfs</li>
<li>python38Packages.howdoi</li>
<li>python38Packages.keep</li>
<li>python38Packages.notmuch</li>
<li>python38Packages.notmuch2</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyls-black</li>
<li>python38Packages.pyls-isort</li>
<li>python38Packages.pyls-mypy</li>
<li>python38Packages.pyls-spyder</li>
<li>python38Packages.python-jsonrpc-server</li>
<li>python38Packages.python-language-server</li>
<li>python38Packages.scrapy-deltafetch</li>
<li>python38Packages.scrapy-splash</li>
<li>spyder (python38Packages.spyder)</li>
<li>python38Packages.swspotify</li>
<li>python38Packages.three-merge</li>
<li>worldengine-cli (python38Packages.worldengine)</li>
<li>xdot (python38Packages.xdot)</li>
<li>python39Packages.alot</li>
<li>python39Packages.guestfs</li>
<li>python39Packages.howdoi</li>
<li>python39Packages.keep</li>
<li>python39Packages.notmuch</li>
<li>python39Packages.notmuch2</li>
<li>python39Packages.pyhaversion</li>
<li>python39Packages.python-jsonrpc-server</li>
<li>python39Packages.scrapy-deltafetch</li>
<li>python39Packages.scrapy-splash</li>
<li>python39Packages.swspotify</li>
<li>python39Packages.three-merge</li>
<li>python39Packages.worldengine</li>
<li>python39Packages.xdot</li>
</ul>
</details>

**Pull request merged**
