### PR TITLE
rust-analyzer: 2021-08-09 -> 2021-08-16

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Version bump.
The extension is tested via vscode.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Here is the changelog (not very big)
https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-08-16

**Comment by happysalada** [comment]
I was just a little surprised by the esbuild inclusion, but it looks like they removed rollup in favor of esbuild
https://github.com/rust-analyzer/rust-analyzer/commit/463860439f2c02187793c2d43b649c184a270a9f#diff-9d0d5bb068560b621fd1e980e53c9edaaf9966629337a02732fb4724ce1b108e

The one problem I see with including the binary first, is that you might not use the same version that they use. esbuild is updated relatively frequently and is pre 1.0, so an upgrade of esbuild might break this.

In practice, it's not an issue yet, and I haven't seen any breakage in esbuild recently. So I would say it's fine to keep as is and if we encounter breakage, we can just be reactive about it.

let me test quickly.

**Comment by happysalada** [comment]
Testing now on macos.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 134300` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>fast-cli</li>
    <li>mirakurun</li>
  </ul>
</details>
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>castnow</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>epgstation</li>
    <li>flood</li>
    <li>gtop</li>
    <li>hyperspace-cli</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>mx-puppet-discord</li>
    <li>netlify-cli</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>rust-analyzer</li>
    <li>rust-analyzer-unwrapped</li>
    <li>thelounge</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>zx</li>
  </ul>
</details>

**Comment by happysalada** [comment]
ha, the node-packages was just updated in another PR, would you mind doing a rebase?

**Comment by oxalica** [comment]
> The one problem I see with including the binary first, is that you might not use the same version that they use. esbuild is updated relatively frequently and is pre 1.0, so an upgrade of esbuild might break this.

Do you mean to lock `esbuild` to the version they used? Since `esbuild` is in nixpkgs top level, it would not be preferred to keep multiple versions, unless someone requires one. So before the extension really breaks, I'll keep it using the global `esbuild`.

**Comment by happysalada** [comment]
I wasn't super clear.
Yes there won't be multiple versions of esbuild. The versions can be different therefore when building. There is a chance that it breaks, but I think it's fine to leave it like this until it does break. I don't have a better solution, i was just pointing out that since esbuild is pre 1.0, there could be breakage. I'm happy to address this when this happens.

**Comment by oxalica** [comment]
Regenerated.

**Comment by happysalada** [comment]
Thank you for the PR!

**Pull request merged**
