### PR TITLE
lxqt: 0.12.0 -> 0.13.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update [LXQt](https://lxqt.org/) to version [0.13.0](https://forum.lxqt.org/t/release-lxqt-0-13-0/301).

###### TODO
- [x] Verify that the following change (from the release notes) works:
> Upstream configuration defaults were moved to `/usr/share/lxqt`, and distribution’s overrides can be placed into `/etc/lxqt`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xeji** [comment]
@romildo is this ready to merge now? If yes, please resolve the conflict.

**Comment by romildo** [comment]
> is this ready to merge now? If yes, please resolve the conflict.

@xeji Yes, it is ready to merge.

**Comment by xeji** [comment]
@GrahamcOfBorg build lxqt.lxqt-panel lxqt.lxqt-session pcmanfm-qt lxqt.lxqt-config

**Comment by xeji** [comment]
Thank you!

**Pull request merged**
