### PR TITLE
geany: 1.36.0 -> 1.37.0

### PR DESCRIPTION
**Pull request by frlan**
##### Motivation for this change
New upstream release 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
``platforms = platforms.all;`` can be removed. That is the default.

Can you update the commit message to use a lowercase g?

Also builds fine on darwin.

**Comment by frlan** [comment]
@SuperSandro2000  Done

**Comment by r-burns** [comment]
@SuperSandro2000 platforms.all is needed to build on hydra, https://github.com/NixOS/nixpkgs/pull/99995#discussion_r503282420

**Comment by frlan** [comment]
Re-added it. If it's a default now it will not hurt anyway.

**Comment by SuperSandro2000** [comment]
Sorry about the wrong suggestion. I retraced a miss information from a while ago. r-burns is right.

**Comment by frlan** [comment]
@SuperSandro2000  It's ok with me -- nevermind ;)

**Review by r-burns — APPROVED** [review]
WFM non-nixos linux

**Review by jtojnar — APPROVED** [review]
Ann: https://www.geany.org/news/geany-137-is-out/
Changes: https://www.geany.org/documentation/releasenotes/

**Pull request merged**
