### PR TITLE
bazel_6: 6.3.2 -> 6.4.0

### PR DESCRIPTION
**Pull request by avdv**
## Description of changes

Bazel 6.4.0 is a minor LTS release. It is fully backward compatible with Bazel 6.0 and contains selected changes by the Bazel community and Google engineers.

See https://github.com/bazelbuild/bazel/releases/tag/6.4.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by uri-canva — APPROVED** [review]

**Review by lukegb — APPROVED** [review]

**Comment by avdv** [comment]
Result of `nixpkgs-review pr 262238` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.distrax</li>
    <li>python310Packages.distrax.dist</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.dm-sonnet.dist</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.elegy.dist</li>
    <li>python310Packages.flax</li>
    <li>python310Packages.flax.dist</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.rlax.dist</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.tensorflow-datasets.dist</li>
    <li>python310Packages.tensorflow-probability</li>
    <li>python310Packages.tensorflow-probability.dist</li>
    <li>python310Packages.treeo</li>
    <li>python310Packages.treeo.dist</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.treex.dist</li>
    <li>python310Packages.trfl</li>
    <li>python310Packages.trfl.dist</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python310Packages.vqgan-jax.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.flax</li>
    <li>python311Packages.flax.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.tensorflow-probability</li>
    <li>python311Packages.tensorflow-probability.dist</li>
    <li>python311Packages.treeo</li>
    <li>python311Packages.treeo.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.trfl</li>
    <li>python311Packages.trfl.dist</li>
    <li>python311Packages.vqgan-jax</li>
    <li>python311Packages.vqgan-jax.dist</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>python310Packages.objax</li>
    <li>python310Packages.objax.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python311Packages.objax</li>
    <li>python311Packages.objax.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>145 packages built:</summary>
  <ul>
    <li>bazel (bazel_6)</li>
    <li>envoy</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>pomerium</li>
    <li>python310Packages.aeppl</li>
    <li>python310Packages.aeppl.dist</li>
    <li>python310Packages.aesara</li>
    <li>python310Packages.aesara.dist</li>
    <li>python310Packages.argos-translate-files</li>
    <li>python310Packages.argos-translate-files.dist</li>
    <li>python310Packages.argostranslate</li>
    <li>python310Packages.argostranslate.dist</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.arviz.dist</li>
    <li>python310Packages.augmax</li>
    <li>python310Packages.augmax.dist</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward.dist</li>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.blackjax</li>
    <li>python310Packages.blackjax.dist</li>
    <li>python310Packages.chex</li>
    <li>python310Packages.chex.dist</li>
    <li>python310Packages.coffea</li>
    <li>python310Packages.coffea.dist</li>
    <li>python310Packages.correctionlib</li>
    <li>python310Packages.correctionlib.dist</li>
    <li>python310Packages.ctranslate2</li>
    <li>python310Packages.ctranslate2.dist</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.dask-awkward.dist</li>
    <li>python310Packages.dm-haiku</li>
    <li>python310Packages.dm-haiku.dist</li>
    <li>python310Packages.dm-haiku.testsout</li>
    <li>python310Packages.equinox</li>
    <li>python310Packages.equinox.dist</li>
    <li>python310Packages.faster-whisper</li>
    <li>python310Packages.faster-whisper.dist</li>
    <li>python310Packages.gymnasium</li>
    <li>python310Packages.gymnasium.dist</li>
    <li>python310Packages.jax</li>
    <li>python310Packages.jax.dist</li>
    <li>python310Packages.jaxlib (python310Packages.jaxlib-build ,python310Packages.jaxlibWithoutCuda)</li>
    <li>python310Packages.jaxlib.dist (python310Packages.jaxlib-build.dist ,python310Packages.jaxlibWithoutCuda.dist)</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python310Packages.jaxlibWithCuda.dist</li>
    <li>python310Packages.jaxopt</li>
    <li>python310Packages.jaxopt.dist</li>
    <li>python310Packages.jmp</li>
    <li>python310Packages.jmp.dist</li>
    <li>python310Packages.libretranslate</li>
    <li>python310Packages.libretranslate.dist</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.mplhep.dist</li>
    <li>python310Packages.numpyro</li>
    <li>python310Packages.numpyro.dist</li>
    <li>python310Packages.optax</li>
    <li>python310Packages.optax.dist</li>
    <li>python310Packages.optax.testsout</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.pytensor</li>
    <li>python310Packages.pytensor.dist</li>
    <li>python310Packages.tensorflow-bin</li>
    <li>python310Packages.tensorflow-bin.dist</li>
    <li>python310Packages.translatehtml</li>
    <li>python310Packages.translatehtml.dist</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.uproot.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python311Packages.aeppl</li>
    <li>python311Packages.aeppl.dist</li>
    <li>python311Packages.aesara</li>
    <li>python311Packages.aesara.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.augmax</li>
    <li>python311Packages.augmax.dist</li>
    <li>python311Packages.awkward</li>
    <li>python311Packages.awkward.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.chex</li>
    <li>python311Packages.chex.dist</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.correctionlib</li>
    <li>python311Packages.correctionlib.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.ctranslate2.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.dm-haiku</li>
    <li>python311Packages.dm-haiku.dist</li>
    <li>python311Packages.dm-haiku.testsout</li>
    <li>python311Packages.equinox</li>
    <li>python311Packages.equinox.dist</li>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.faster-whisper.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.jax</li>
    <li>python311Packages.jax.dist</li>
    <li>python311Packages.jaxlib (python311Packages.jaxlib-build ,python311Packages.jaxlibWithoutCuda)</li>
    <li>python311Packages.jaxlib.dist (python311Packages.jaxlib-build.dist ,python311Packages.jaxlibWithoutCuda.dist)</li>
    <li>python311Packages.jaxlibWithCuda</li>
    <li>python311Packages.jaxlibWithCuda.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.jmp</li>
    <li>python311Packages.jmp.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.numpyro</li>
    <li>python311Packages.numpyro.dist</li>
    <li>python311Packages.optax</li>
    <li>python311Packages.optax.dist</li>
    <li>python311Packages.optax.testsout</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
    <li>python311Packages.tensorflow-bin</li>
    <li>python311Packages.tensorflow-bin.dist</li>
    <li>python311Packages.translatehtml</li>
    <li>python311Packages.translatehtml.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
    <li>wyoming-openwakeword</li>
    <li>wyoming-openwakeword.dist</li>
  </ul>
</details>

**Comment by avdv** [comment]
I have updated the fetchAttrs hashes for linux amd64. I have modified hashes for other systems to fake hashes in order to let ofborg build them for me.

Unfortunately, all ofborg builds are failing, but I cannot really see why.

Could somebody provide hashes for envoy and jaxlib for linux aarch64 please?

**Comment by jacobfoard** [comment]
The sha for jaxlib aarch64-linux `sha256-59rv/3RjD8pnveBDZ33xZoNQxLmnhMocsKMgVfYoO70=`

Trying to get the envoy build to run but hitting this error

```
ERROR: An error occurred during the fetch of repository 'com_github_lyft_protoc_gen_star':
   Traceback (most recent call last):
        File "/build/output/external/bazel_gazelle/internal/go_repository.bzl", line 256, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_lyft_protoc_gen_star: fetch_repo: github.com/lyft/protoc-gen-star/v2@v2.0.1: GOPROXY list is not the empty string, but contains no entries
ERROR: /build/source/WORKSPACE:25:25: fetching go_repository rule //external:com_github_lyft_protoc_gen_star: Traceback (most recent call last):
        File "/build/output/external/bazel_gazelle/internal/go_repository.bzl", line 256, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_lyft_protoc_gen_star: fetch_repo: github.com/lyft/protoc-gen-star/v2@v2.0.1: GOPROXY list is not the empty string, but contains no entries
```

Which seems to be related to the go 1.21 sdk & bazel, but I didn't see an obvious fix at a quick glance.

https://github.com/bazelbuild/rules_go/issues/3665

**Comment by avdv** [comment]
> The sha for jaxlib aarch64-linux `sha256-59rv/3RjD8pnveBDZ33xZoNQxLmnhMocsKMgVfYoO70=`

Thank you @jacobfoard.



> Trying to get the envoy build to run but hitting this error

On x86_64-linux, I tried to rebuild envoy on current master (commit 295324df05ab13710f7ded9b4f432de5e97ca3e2) and it failed in a similar way:
```
error: builder for '/nix/store/nk4rx74di8rzfk2w3gmmfh6bz9yhpylz-envoy-1.27.1-deps.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       > ERROR: /build/source/WORKSPACE:25:25: fetching go_repository rule //external:com_github_lyft_protoc_gen_star: Traceback (most recent call last):
       >     File "/build/output/external/bazel_gazelle/internal/go_repository.bzl", line 256, column 17, in _go_repository_impl
       >            fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
       > Error in fail: failed to fetch com_github_lyft_protoc_gen_star: fetch_repo: github.com/lyft/protoc-gen-star/v2@v2.0.1: GOPROXY list is not the empty string, but contains no entries
```
I am adding a workaround...

**Comment by jacobfoard** [comment]
That seems to have helped enough to get the sha for envoy `sha256-AMvAo3PhtvNp5p4XmncRJ5LJm8gu9xXWfWoIrm0qn1A=`.
Unfortunately (or maybe fortunately? 😅), I got the same `com_github_lyft_protoc_gen_star` errors as the [x86 ofborg build](https://logs.ofborg.org/?key=nixos/nixpkgs.262238&attempt_id=ba057cc9-5dc0-43f2-8814-08b7b5d7309b).

**Comment by avdv** [comment]
Yes, that's what I see too. Let me try to resolve this problem in a different way - I'll downgrade go to 1.20.

**Comment by avdv** [comment]
That worked. Now it's only failing the `pythonBinPath` and `pythonBinPathWithNixHacks` tests, but these also fail for master currently:
```
λ git show
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
commit 295324df05ab13710f7ded9b4f432de5e97ca3e2 (HEAD -> master, upstream/master, upstream/HEAD) ┃
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Merge: 62a60025f7b5 663a3c9e9fc0
Author: Nikolay Korotkiy <sikmir@disroot.org>
Date:   Thu Oct 26 08:58:26 2023 +0400
 
    Merge pull request #263379 from r-ryantm/auto-update/grass
    
    grass: 8.3.0 -> 8.3.1
 

☸ scratchb in nixpkgs on  master [$?] 
λ nix-build -A bazel_6.passthru.tests.pythonBinPath
this derivation will be built:
  /nix/store/k1vj1vig6nbplb7s6vc9r7i59i0xss3b-bazel-test-builtin-rules.drv
building '/nix/store/k1vj1vig6nbplb7s6vc9r7i59i0xss3b-bazel-test-builtin-rules.drv'...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //python:bin (1 packages loaded, 0 targets configured)
Analyzing: target //python:bin (33 packages loaded, 127 targets configured)
    Fetching repository @local_config_cc; starting
Analyzing: target //python:bin (33 packages loaded, 127 targets configured)
    currently loading: @local_config_cc//
INFO: Analyzed target //python:bin (39 packages loaded, 305 targets configured).
 checking cached actions
INFO: Found 1 target...
 checking cached actions
[0 / 5] 4 actions, 0 running
    Expanding template external/bazel_tools/.../python/py3wrapper.sh; 0s local
    Expanding template python/bin; 0s local
    [Prepa] BazelWorkspaceStatusAction stable-status.txt
    [Prepa] Creating source manifest for //python:bin
Target //python:bin up-to-date:
[5 / 5] checking cached actions
  bazel-bin/python/bin
[5 / 5] checking cached actions
INFO: Elapsed time: 2.606s, Critical Path: 0.03s
[5 / 5] checking cached actions
INFO: 5 processes: 5 internal.
[5 / 5] checking cached actions
INFO: Build completed successfully, 5 total actions
INFO: Running command line: bazel-bin/python/bin
Traceback (most recent call last):
  File "/build/tmp.kpCeNrJ7gD/.cache/bazel/_bazel_nixbld/2898b59ac5a61dc07e72b28a0e3fa2ab/execroot/our_workspace/bazel-out/k8-fastbuild/bin/python/bin.runfiles/our_workspace/python/bin.py", line 1, in <module>
    from lib import foo
ModuleNotFoundError: No module named 'lib'
error: builder for '/nix/store/k1vj1vig6nbplb7s6vc9r7i59i0xss3b-bazel-test-builtin-rules.drv' failed with exit code 1;
       last 10 log lines:
       > INFO: Elapsed time: 2.606s, Critical Path: 0.03s
       > [5 / 5] checking cached actions
       > INFO: 5 processes: 5 internal.
       > [5 / 5] checking cached actions
       > INFO: Build completed successfully, 5 total actions
       > INFO: Running command line: bazel-bin/python/bin
       > Traceback (most recent call last):
       >   File "/build/tmp.kpCeNrJ7gD/.cache/bazel/_bazel_nixbld/2898b59ac5a61dc07e72b28a0e3fa2ab/execroot/our_workspace/bazel-out/k8-fastbuild/bin/python/bin.runfiles/our_workspace/python/bin.py", line 1, in <module>
       >     from lib import foo
       > ModuleNotFoundError: No module named 'lib'
       For full logs, run 'nix log /nix/store/k1vj1vig6nbplb7s6vc9r7i59i0xss3b-bazel-test-builtin-rules.drv'.
```
Any idea what might have caused this to break?

**Review by uri-canva — APPROVED** [review]

**Comment by avdv** [comment]
> You need to fix up the commits in the PR branch though so they don't end up in master, there's some reverts and fixups still in there.

Done. Also updated the envoy aarch64-linux hash from the ofborg build.

**Pull request merged**
