### PR TITLE
fatresize: 1.0.2 -> 1.1.0

### PR DESCRIPTION
**Pull request by puckipedia**
###### Motivation for this change

New releases :P

Author is the same, they just moved from SF to GitHub.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
[changelog](https://github.com/ya-mouse/fatresize/blob/master/ChangeLog) for reference.

**Comment by ajs124** [comment]
The commit says 1.1.1, but it's actually 1.1.0 in the package, which is correct.

The software actually reports `fatresize 1.0.3 (19800101)` when run, but that's probably an upstream issue.

**Comment by puckipedia** [comment]
woops, my mistake

**Review by ajs124 — APPROVED** [review]

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 99306` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- fatresize
</details>

**Review by bhipple — APPROVED** [review]

**Pull request merged**
