### PR TITLE
stern: 1.30.0 -> 1.31.0

### PR DESCRIPTION
**Pull request by superherointj**
stern: 1.30.0 -> 1.31.0

Release: https://github.com/stern/stern/releases/tag/v1.31.0
    
- nixfmt format
- add version test
- add meta.changelog
- replace sha256 with hash
- order attributes by alphabetical order and phases order
- move to pkgs/by-name

CC @mbode @Preisschild 

## PR ready for review / merge

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 348546` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stern</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 348546` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stern</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 348546` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stern</li>
  </ul>
</details>

**Review by Preisschild — APPROVED** [review]

**Comment by superherointj** [comment]
Thanks @Artturin

**Pull request merged**
