### PR TITLE
jupyter related packages updates 2024-03-10

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Update jupyter-related packages at once to avoid building hundreds of packages over and over again.

This PR is based on the commits generated by the following command.

```
nix search nixpkgs#python311Packages 'ipython|jupyter|notebook' --json | jq -r 'keys | .[]' | cut -d . -f 3,4 | xargs -n 1 nix-update --commit
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 294660` at ece1c4e6 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.elegy</li>
    <li>python311Packages.jupyter-contrib-nbextensions</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.pynitrokey</li>
    <li>python311Packages.spsdk</li>
    <li>python311Packages.treex</li>
    <li>python312Packages.pynitrokey</li>
    <li>python312Packages.spsdk</li>
  </ul>
</details>
<details>
  <summary>38 packages failed to build:</summary>
  <ul>
    <li>nitrokey-app2</li>
    <li>pynitrokey</li>
    <li><a href="https://gist.github.com/natsukium/df2c10c351a20418b2335c0f270a0aab">python311Packages.augmax</a></li>
    <li>python311Packages.cirq</li>
    <li>python311Packages.ffcv</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.jupyterlab-git</li>
    <li><a href="https://gist.github.com/natsukium/e59f4d79a72767b2bd847058c6ac5a42">python311Packages.nbdime</a></li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.pytest-notebook</li>
    <li><a href="https://gist.github.com/natsukium/90974da9a6bc8927dfea491a6686d9eb">python311Packages.pytorch-pfn-extras</a></li>
    <li><a href="https://gist.github.com/natsukium/84ec302c159ed150f1f01daa8fbe158e">python311Packages.scikit-rf</a></li>
    <li><a href="https://gist.github.com/natsukium/7f4031a3e321fc98091fc1b1438227b4">python311Packages.tf2onnx</a></li>
    <li>python312Packages.folium</li>
    <li>python312Packages.ipyvuetify</li>
    <li>python312Packages.jupyter-collaboration</li>
    <li>python312Packages.jupyter-contrib-core</li>
    <li>python312Packages.jupyterlab</li>
    <li>python312Packages.jupyterlab-git</li>
    <li>python312Packages.jupyterlab-lsp</li>
    <li>python312Packages.jupyterlab-server</li>
    <li>python312Packages.jupytext</li>
    <li>python312Packages.mkdocs-jupyter</li>
    <li><a href="https://gist.github.com/natsukium/9a1b1058e1b822fa9e3aa011616cd240">python312Packages.nbconflux</a></li>
    <li>python312Packages.nbdime</li>
    <li>python312Packages.nikola</li>
    <li>python312Packages.nix-kernel</li>
    <li>python312Packages.notebook</li>
    <li>python312Packages.notedown</li>
    <li>python312Packages.paddle2onnx</li>
    <li>python312Packages.pytest-notebook</li>
    <li>python312Packages.qgrid</li>
    <li>python312Packages.weasel</li>
    <li>rocmPackages.mivisionx (rocmPackages.mivisionx-hip)</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-opencl</li>
    <li>tts</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>146 packages built successfully:</summary>
  <ul>
    <li>cantor</li>
    <li>deface</li>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>ihaskell</li>
    <li>jupyter</li>
    <li>jupyter-all</li>
    <li>labplot</li>
    <li>manim</li>
    <li>nbqa</li>
    <li>opsdroid</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.bqplot</li>
    <li>python311Packages.bqscales</li>
    <li>python311Packages.cirq-ft</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.devito</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.dm-haiku</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.einops</li>
    <li>python311Packages.encodec</li>
    <li>python311Packages.experiment-utilities</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastembed</li>
    <li>python311Packages.flax</li>
    <li>python311Packages.insightface</li>
    <li>python311Packages.ipydatawidgets</li>
    <li>python311Packages.ipyparallel</li>
    <li>python311Packages.ipytablewidgets</li>
    <li>python311Packages.ipyvuetify</li>
    <li>python311Packages.jupyter</li>
    <li>python311Packages.jupyter-collaboration</li>
    <li>python311Packages.jupyter-contrib-core</li>
    <li>python311Packages.jupyter-lsp</li>
    <li>python311Packages.jupyter-nbextensions-configurator</li>
    <li>python311Packages.jupyter-server</li>
    <li>python311Packages.jupyter-server-fileid</li>
    <li>python311Packages.jupyter-server-mathjax</li>
    <li>python311Packages.jupyter-sphinx</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterlab</li>
    <li>python311Packages.jupyterlab-lsp</li>
    <li>python311Packages.jupyterlab-server</li>
    <li>python311Packages.jupytext</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.labelbox</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.livelossplot</li>
    <li>python311Packages.memestra</li>
    <li>python311Packages.mkdocs-jupyter</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.nbclassic</li>
    <li>python311Packages.nbconflux</li>
    <li>python311Packages.nbconvert</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbexec</li>
    <li>python311Packages.nbsmoke</li>
    <li>python311Packages.nbsphinx</li>
    <li>python311Packages.nbval</li>
    <li>python311Packages.nikola</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.notebook</li>
    <li>python311Packages.notebook-shim</li>
    <li>python311Packages.notedown</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.onnx</li>
    <li>python311Packages.onnxconverter-common</li>
    <li>python311Packages.onnxmltools</li>
    <li>python311Packages.onnxruntime-tools</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.phik</li>
    <li>python311Packages.pweave</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pydeck</li>
    <li>python311Packages.pygmo</li>
    <li>python311Packages.pyls-memestra</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymoo</li>
    <li>python311Packages.qgrid</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rotary-embedding-torch</li>
    <li>python311Packages.schemdraw</li>
    <li>python311Packages.skl2onnx</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-transformers</li>
    <li>spyder (python311Packages.spyder)</li>
    <li>streamlit (python311Packages.streamlit)</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.thinc</li>
    <li>python311Packages.tsfresh</li>
    <li>python311Packages.unidic</li>
    <li>python311Packages.unstructured-api-tools</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vega</li>
    <li>python311Packages.vqgan-jax</li>
    <li>python311Packages.wasabi</li>
    <li>python311Packages.weasel</li>
    <li>python311Packages.xarray-einstats</li>
    <li>python311Packages.ziafont</li>
    <li>python311Packages.ziamath</li>
    <li>python312Packages.fastembed</li>
    <li>python312Packages.ipyparallel</li>
    <li>python312Packages.jupyter-lsp</li>
    <li>python312Packages.jupyter-server</li>
    <li>python312Packages.jupyter-server-fileid</li>
    <li>python312Packages.jupyter-server-mathjax</li>
    <li>python312Packages.jupyter-sphinx</li>
    <li>python312Packages.labelbox</li>
    <li>python312Packages.livelossplot</li>
    <li>python312Packages.memestra</li>
    <li>python312Packages.nbconvert</li>
    <li>python312Packages.nbdev</li>
    <li>python312Packages.nbexec</li>
    <li>python312Packages.nbsphinx</li>
    <li>python312Packages.nbval</li>
    <li>python312Packages.notebook-shim</li>
    <li>python312Packages.onnx</li>
    <li>python312Packages.onnxconverter-common</li>
    <li>python312Packages.onnxruntime-tools</li>
    <li>python312Packages.pweave</li>
    <li>python312Packages.pygmo</li>
    <li>python312Packages.schemdraw</li>
    <li>python312Packages.thinc</li>
    <li>python312Packages.unidic</li>
    <li>python312Packages.unstructured-api-tools</li>
    <li>python312Packages.wasabi</li>
    <li>python312Packages.ziafont</li>
    <li>python312Packages.ziamath</li>
    <li>quarto</li>
    <li>rocmPackages.migraphx</li>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 294660` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.jupyter-contrib-nbextensions</li>
    <li>python311Packages.jupyter-contrib-nbextensions.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pynitrokey</li>
    <li>python311Packages.pynitrokey.dist</li>
    <li>python311Packages.spsdk</li>
    <li>python311Packages.spsdk.dist</li>
    <li>python312Packages.pynitrokey</li>
    <li>python312Packages.pynitrokey.dist</li>
    <li>python312Packages.spsdk</li>
    <li>python312Packages.spsdk.dist</li>
    <li>rocmPackages.migraphx</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages.mivisionx-opencl</li>
    <li>rocmPackages_5.migraphx</li>
    <li>rocmPackages_5.mivisionx</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
    <li>rstudio</li>
    <li>rstudio-server</li>
  </ul>
</details>
<details>
  <summary>82 packages failed to build:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>deface</li>
    <li>deface.dist</li>
    <li>labplot</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>nitrokey-app2</li>
    <li>nitrokey-app2.dist</li>
    <li>pynitrokey</li>
    <li>pynitrokey.dist</li>
    <li>python311Packages.augmax</li>
    <li>python311Packages.augmax.dist</li>
    <li>python311Packages.cirq</li>
    <li>python311Packages.cirq.dist</li>
    <li>python311Packages.devito</li>
    <li>python311Packages.devito.dist</li>
    <li>python311Packages.ffcv</li>
    <li>python311Packages.ffcv.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.insightface</li>
    <li>python311Packages.insightface.dist</li>
    <li>python311Packages.jupyterlab-git</li>
    <li>python311Packages.jupyterlab-git.dist</li>
    <li>python311Packages.jupytext</li>
    <li>python311Packages.jupytext.dist</li>
    <li>python311Packages.mkdocs-jupyter</li>
    <li>python311Packages.mkdocs-jupyter.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.nbdime</li>
    <li>python311Packages.nbdime.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.pytest-notebook</li>
    <li>python311Packages.pytest-notebook.dist</li>
    <li>python311Packages.pytorch-pfn-extras</li>
    <li>python311Packages.pytorch-pfn-extras.dist</li>
    <li>python311Packages.scikit-rf</li>
    <li>python311Packages.scikit-rf.dist</li>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>python312Packages.folium</li>
    <li>python312Packages.folium.dist</li>
    <li>python312Packages.ipyvuetify</li>
    <li>python312Packages.ipyvuetify.dist</li>
    <li>python312Packages.jupyter-collaboration</li>
    <li>python312Packages.jupyter-collaboration.dist</li>
    <li>python312Packages.jupyter-contrib-core</li>
    <li>python312Packages.jupyter-contrib-core.dist</li>
    <li>python312Packages.jupyterlab</li>
    <li>python312Packages.jupyterlab-git</li>
    <li>python312Packages.jupyterlab-git.dist</li>
    <li>python312Packages.jupyterlab-lsp</li>
    <li>python312Packages.jupyterlab-lsp.dist</li>
    <li>python312Packages.jupyterlab-server</li>
    <li>python312Packages.jupyterlab-server.dist</li>
    <li>python312Packages.jupyterlab.dist</li>
    <li>python312Packages.jupytext</li>
    <li>python312Packages.jupytext.dist</li>
    <li>python312Packages.mkdocs-jupyter</li>
    <li>python312Packages.mkdocs-jupyter.dist</li>
    <li>python312Packages.nbconflux</li>
    <li>python312Packages.nbconflux.dist</li>
    <li>python312Packages.nbdime</li>
    <li>python312Packages.nbdime.dist</li>
    <li>python312Packages.nikola</li>
    <li>python312Packages.nikola.dist</li>
    <li>python312Packages.nix-kernel</li>
    <li>python312Packages.nix-kernel.dist</li>
    <li>python312Packages.notebook</li>
    <li>python312Packages.notebook.dist</li>
    <li>python312Packages.notedown</li>
    <li>python312Packages.notedown.dist</li>
    <li>python312Packages.paddle2onnx</li>
    <li>python312Packages.paddle2onnx.dist</li>
    <li>python312Packages.pytest-notebook</li>
    <li>python312Packages.pytest-notebook.dist</li>
    <li>python312Packages.qgrid</li>
    <li>python312Packages.qgrid.dist</li>
    <li>python312Packages.weasel</li>
    <li>python312Packages.weasel.dist</li>
  </ul>
</details>
<details>
  <summary>237 packages built:</summary>
  <ul>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>jupyter</li>
    <li>jupyter-all</li>
    <li>manim</li>
    <li>manim.dist</li>
    <li>opsdroid</li>
    <li>opsdroid.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.bqplot</li>
    <li>python311Packages.bqplot.dist</li>
    <li>python311Packages.bqscales</li>
    <li>python311Packages.bqscales.dist</li>
    <li>python311Packages.cirq-ft</li>
    <li>python311Packages.cirq-ft.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.einops</li>
    <li>python311Packages.einops.dist</li>
    <li>python311Packages.encodec</li>
    <li>python311Packages.encodec.dist</li>
    <li>python311Packages.experiment-utilities</li>
    <li>python311Packages.experiment-utilities.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.fastembed</li>
    <li>python311Packages.fastembed.dist</li>
    <li>python311Packages.ipydatawidgets</li>
    <li>python311Packages.ipydatawidgets.dist</li>
    <li>python311Packages.ipyparallel</li>
    <li>python311Packages.ipyparallel.dist</li>
    <li>python311Packages.ipytablewidgets</li>
    <li>python311Packages.ipytablewidgets.dist</li>
    <li>python311Packages.ipyvuetify</li>
    <li>python311Packages.ipyvuetify.dist</li>
    <li>python311Packages.jupyter</li>
    <li>python311Packages.jupyter-collaboration</li>
    <li>python311Packages.jupyter-collaboration.dist</li>
    <li>python311Packages.jupyter-contrib-core</li>
    <li>python311Packages.jupyter-contrib-core.dist</li>
    <li>python311Packages.jupyter-lsp</li>
    <li>python311Packages.jupyter-lsp.dist</li>
    <li>python311Packages.jupyter-nbextensions-configurator</li>
    <li>python311Packages.jupyter-nbextensions-configurator.dist</li>
    <li>python311Packages.jupyter-server</li>
    <li>python311Packages.jupyter-server-fileid</li>
    <li>python311Packages.jupyter-server-fileid.dist</li>
    <li>python311Packages.jupyter-server-mathjax</li>
    <li>python311Packages.jupyter-server-mathjax.dist</li>
    <li>python311Packages.jupyter-server.dist</li>
    <li>python311Packages.jupyter-sphinx</li>
    <li>python311Packages.jupyter-sphinx.dist</li>
    <li>python311Packages.jupyter.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.jupyterlab</li>
    <li>python311Packages.jupyterlab-lsp</li>
    <li>python311Packages.jupyterlab-lsp.dist</li>
    <li>python311Packages.jupyterlab-server</li>
    <li>python311Packages.jupyterlab-server.dist</li>
    <li>python311Packages.jupyterlab.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.labelbox</li>
    <li>python311Packages.labelbox.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.livelossplot</li>
    <li>python311Packages.livelossplot.dist</li>
    <li>python311Packages.memestra</li>
    <li>python311Packages.memestra.dist</li>
    <li>python311Packages.nbclassic</li>
    <li>python311Packages.nbclassic.dist</li>
    <li>python311Packages.nbconflux</li>
    <li>python311Packages.nbconflux.dist</li>
    <li>python311Packages.nbconvert</li>
    <li>python311Packages.nbconvert.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.nbexec</li>
    <li>python311Packages.nbexec.dist</li>
    <li>python311Packages.nbsmoke</li>
    <li>python311Packages.nbsmoke.dist</li>
    <li>python311Packages.nbsphinx</li>
    <li>python311Packages.nbsphinx.dist</li>
    <li>python311Packages.nbval</li>
    <li>python311Packages.nbval.dist</li>
    <li>python311Packages.nikola</li>
    <li>python311Packages.nikola.dist</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>python311Packages.notebook</li>
    <li>python311Packages.notebook-shim</li>
    <li>python311Packages.notebook-shim.dist</li>
    <li>python311Packages.notebook.dist</li>
    <li>python311Packages.notedown</li>
    <li>python311Packages.notedown.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>python311Packages.onnx</li>
    <li>python311Packages.onnx.dist</li>
    <li>python311Packages.onnxconverter-common</li>
    <li>python311Packages.onnxconverter-common.dist</li>
    <li>python311Packages.onnxmltools</li>
    <li>python311Packages.onnxmltools.dist</li>
    <li>python311Packages.onnxruntime-tools</li>
    <li>python311Packages.onnxruntime-tools.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.phik</li>
    <li>python311Packages.phik.dist</li>
    <li>python311Packages.pweave</li>
    <li>python311Packages.pweave.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pydeck</li>
    <li>python311Packages.pydeck.dist</li>
    <li>python311Packages.pyls-memestra</li>
    <li>python311Packages.pyls-memestra.dist</li>
    <li>python311Packages.pymoo</li>
    <li>python311Packages.pymoo.dist</li>
    <li>python311Packages.qgrid</li>
    <li>python311Packages.qgrid.dist</li>
    <li>python311Packages.rotary-embedding-torch</li>
    <li>python311Packages.rotary-embedding-torch.dist</li>
    <li>python311Packages.schemdraw</li>
    <li>python311Packages.schemdraw.dist</li>
    <li>python311Packages.skl2onnx</li>
    <li>python311Packages.skl2onnx.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>spyder (python311Packages.spyder)</li>
    <li>spyder.dist (python311Packages.spyder.dist)</li>
    <li>streamlit (python311Packages.streamlit)</li>
    <li>streamlit.dist (python311Packages.streamlit.dist)</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.thinc</li>
    <li>python311Packages.thinc.dist</li>
    <li>python311Packages.tsfresh</li>
    <li>python311Packages.tsfresh.dist</li>
    <li>python311Packages.unidic</li>
    <li>python311Packages.unidic.dist</li>
    <li>python311Packages.unstructured-api-tools</li>
    <li>python311Packages.unstructured-api-tools.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python311Packages.vega</li>
    <li>python311Packages.vega.dist</li>
    <li>python311Packages.wasabi</li>
    <li>python311Packages.wasabi.dist</li>
    <li>python311Packages.weasel</li>
    <li>python311Packages.weasel.dist</li>
    <li>python311Packages.xarray-einstats</li>
    <li>python311Packages.xarray-einstats.dist</li>
    <li>python311Packages.ziafont</li>
    <li>python311Packages.ziafont.dist</li>
    <li>python311Packages.ziamath</li>
    <li>python311Packages.ziamath.dist</li>
    <li>python312Packages.fastembed</li>
    <li>python312Packages.fastembed.dist</li>
    <li>python312Packages.ipyparallel</li>
    <li>python312Packages.ipyparallel.dist</li>
    <li>python312Packages.jupyter-lsp</li>
    <li>python312Packages.jupyter-lsp.dist</li>
    <li>python312Packages.jupyter-server</li>
    <li>python312Packages.jupyter-server-fileid</li>
    <li>python312Packages.jupyter-server-fileid.dist</li>
    <li>python312Packages.jupyter-server-mathjax</li>
    <li>python312Packages.jupyter-server-mathjax.dist</li>
    <li>python312Packages.jupyter-server.dist</li>
    <li>python312Packages.jupyter-sphinx</li>
    <li>python312Packages.jupyter-sphinx.dist</li>
    <li>python312Packages.labelbox</li>
    <li>python312Packages.labelbox.dist</li>
    <li>python312Packages.livelossplot</li>
    <li>python312Packages.livelossplot.dist</li>
    <li>python312Packages.memestra</li>
    <li>python312Packages.memestra.dist</li>
    <li>python312Packages.nbconvert</li>
    <li>python312Packages.nbconvert.dist</li>
    <li>python312Packages.nbdev</li>
    <li>python312Packages.nbdev.dist</li>
    <li>python312Packages.nbexec</li>
    <li>python312Packages.nbexec.dist</li>
    <li>python312Packages.nbsphinx</li>
    <li>python312Packages.nbsphinx.dist</li>
    <li>python312Packages.nbval</li>
    <li>python312Packages.nbval.dist</li>
    <li>python312Packages.notebook-shim</li>
    <li>python312Packages.notebook-shim.dist</li>
    <li>python312Packages.onnx</li>
    <li>python312Packages.onnx.dist</li>
    <li>python312Packages.onnxconverter-common</li>
    <li>python312Packages.onnxconverter-common.dist</li>
    <li>python312Packages.onnxruntime-tools</li>
    <li>python312Packages.onnxruntime-tools.dist</li>
    <li>python312Packages.pweave</li>
    <li>python312Packages.pweave.dist</li>
    <li>python312Packages.schemdraw</li>
    <li>python312Packages.schemdraw.dist</li>
    <li>python312Packages.thinc</li>
    <li>python312Packages.thinc.dist</li>
    <li>python312Packages.unidic</li>
    <li>python312Packages.unidic.dist</li>
    <li>python312Packages.unstructured-api-tools</li>
    <li>python312Packages.unstructured-api-tools.dist</li>
    <li>python312Packages.wasabi</li>
    <li>python312Packages.wasabi.dist</li>
    <li>python312Packages.ziafont</li>
    <li>python312Packages.ziafont.dist</li>
    <li>python312Packages.ziamath</li>
    <li>python312Packages.ziamath.dist</li>
    <li>quarto</li>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM.
It doesn't seem like a major regression is introduced there.

**Review by thomasjm — APPROVED** [review]
Looks okay to me. Only `nbval` stands out to me as a large-ish change--it doesn't seem to have a changelog, but it's been over a year since the last release and there are a number of miscellaneous commits added.

**Comment by natsukium** [comment]
rebased on master since `python-updates` has reached it.

**Pull request merged**
