### PR TITLE
rustRegistry: expose src, 2016-04-02 -> 2016-04-13

### PR DESCRIPTION
**Pull request by jgillich**
src is needed for #14469

### CODE REVIEW

**Comment by trishume** [comment]
I'm not on any team that is allowed to review PRs but this looks good to me :+1:

I assume this is being exposed so that a script can use the new nix prefetch by attribute option to figure out the new SHA?

**Comment by jgillich** [comment]
Yes, exactly.

**Comment by jgillich** [comment]
Totally OT but @rbvermaa would you mind adding me to the NixOS org? I can't manage to catch you in IRC. :(

**Comment by jgillich** [comment]
@abbradar :)

**Comment by abbradar** [comment]
Conflicts.

**Comment by jgillich** [comment]
Oops, fixed.

**Pull request merged**
