### PR TITLE
[RFC] hostbridge and IPv6 for containers

### PR DESCRIPTION
**Pull request by kampfschlaefer**
Hi all,

scratching my own itch I had some ideas on how to a) give nixos containers IPv6 and b) allow declarative containers to join an existing bridge for connectivity.

What I mostly do not like yet: It should be possible to define the network-settings inside the container with `networking.interfaces.eth0.*` instead of defining it from the outside.

So please comment on this, maybe I can rework this into something usable to get IPv6 and bridging to declarative containers.

### CODE REVIEW

**Comment by Profpatsch** [comment]
(triage) cc @aristidb @edolstra @aszlig @chaoflow

**Comment by fpletz** [comment]
Finally got some time to review your changes. Big :+1:, very cool!

Could you maybe group your commits into 2 or 3 commits without the fixes?

**Comment by kampfschlaefer** [comment]
> Could you maybe group your commits into 2 or 3 commits without the fixes?

Will do. Also there is one little detail missing: when host-bridge is used, the vb-* device needs to be deleted to make sure. Got bitten by this unclean exit several times now…

**Comment by kampfschlaefer** [comment]
superseeded by #14018

**Pull request closed without merging**
