### PR TITLE
stdenvBootstrapTools: inherit {cross,local}System

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

It's expected that attributes in the top-level package set will all use that package set, but this wasn't the case for the bootstrap tools. This led some very confusing behaviour:

- `pkgsMusl.stdenvBootstrapTools` would build glibc bootstrap tools

- `stdenvBootstrapTools` was _always_ cross compiled, even if Nixpkgs wasn't, because it always set `crossSystem`.  This also didn't match the behaviour of using make-bootstrap-tools.nix as an entrypoint, where `crossSystem` would default to `null`.

For the Linux stdenv, I've made the ideal fix, which is to make pkgs an argument rather than taking the arguments for pkgs, and then re-importing it.  This means it'll always use exactly the same package set that's calling it, and should also mean faster eval due to not importing Nixpkgs twice.

The Darwin stdenv is more complicated, and I'm not able to easily test it, so I wasn't confident in making the same fix there.  Instead, I've just made sure `crossSystem` and `localSystem` are set to the correct values so they're not always cross compiled and match the parent package set's. It would still be preferable if somebody could make Darwin's make-bootstrap-tools.nix take pkgs as an argument, rather than all the arguments for pkgs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@ofborg build stdenvBootstrapTools

**Review by sternenseemann — APPROVED** [review]

**Comment by alyssais** [comment]
Not sure what happened on aarch64-darwin, let's retry.

@OfBorg build stdenvBootstrapTools

**Comment by thefloweringash** [comment]
> Not sure what happened on aarch64-darwin, let's retry.
> 
> @ofborg build stdenvBootstrapTools

The `unpack` and `test` attributes for the Darwin bootstrap tools seem to be out of date. For `x86_64-darwin`, there's some unnecessary but mostly harmless extra handling of rpaths in `unpack`, but for `aarch64-darwin`, it needs to be more careful to not break the signatures when rewriting the install names of the shipped .dylibs. It's easy enough to fix, but the `test` attribute also needs some attention before it will pass and I've ran out of time for now.

I don't think you need to worry about `aarch64-darwin` for this PR.

**Review by thefloweringash — APPROVED** [review]

**Comment by trofi** [comment]
Looks like this PR caused hydra to silentry drop all the `stdenvBootstrapTools` jobs as it's an empty attrset now, Proposed possible fix: https://github.com/NixOS/nixpkgs/pull/182058

**Pull request merged**
