### PR TITLE
nixos/weechat: backport to 18.09

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

This backports my weechat enhancements to 18.09. It allows users to declaratively specify scripts and configuration in `weechat.override`. Additionally adds a module which runs weechat in a `screen` session which is useful when running weechat on a different server for IRC persistence.

I'm using these changes on top of `release-18.09` since original the PR was merged. This PR adds a new module and doesn't break current weechat package configurations. Please refer to #45728 for the initial discussion regarding the changes and the backport.

/cc @samueldr 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
If this gets into 18.09, #47164 is also needed in order to fix package metadata.

**Comment by Ma27** [comment]
@srhb thanks, fixed:)

**Comment by samueldr** [comment]
Hmm, sorry to ask so much, but could you [`cherry-pick -x` the commits](https://nixos.org/nixpkgs/manual/#idm140737315678544)?

No need to add an additional reason to the messages, here it's just for bookkeeping.

**Comment by vcunat** [comment]
Done as 317ce1b622.

**Pull request closed without merging**
