### PR TITLE
floorp: build with private components, adjust license

### PR DESCRIPTION
**Pull request by Naxdy**
see https://github.com/Floorp-Projects/Floorp-private-components/blob/main/LICENSE

## Description of changes

From versions v11.10.5 -> v11.11.0, Floorp moved some of its bespoke components (most notably its Workspaces feature) to a separate repo, distributed under the "Floorp Shared Source License", which is essentially an unfree redistributable license for the purposes of nixpkgs.

- License: https://github.com/Floorp-Projects/Floorp-private-components/blob/main/LICENSE
- Relevant changes in the main repo: https://github.com/Floorp-Projects/Floorp/compare/5d22e392cfae6bf3f5432528e8019f1a2aa3121f...bd057dfa3d08ee537dcd6a20cd03c416e0452e43
- Relevant changes in the `Floorp-core` repo: https://github.com/Floorp-Projects/Floorp-core/compare/2903aec35fbfe936c8415c92e9c073441d53743c...2b5b78a1886daf531e06f7eb278f0b27e7983e07

This PR enables building with these components, and adjusts Floorp's license to include the new unfree redistributable license accordingly.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Naxdy** [comment]
@christoph-heiss Draft for now because I wanted to get your opinion on this: Instead of updating the `floorp` package to include the new unfree redistributable license, an alternative approach would be to add a new `floorp-unfree` package that includes these components.

My initial thoughts were that including them in the core `floorp` package probably makes more sense, since I'd wager Workspaces are one of the main reason why someone might choose Floorp over vanilla Firefox. Thoughts?

**Comment by christoph-heiss** [comment]
> Instead of updating the `floorp` package to include the new unfree redistributable license, an alternative approach would be to add a new `floorp-unfree` package that includes these components.

Well, the thing is - from a maintainability standpoint, I'd definitely only keep one package. Also having _another_ build for a Firefox fork in the tree significantly burdens Hydra even more, since these are one of the most expensive packages to build, as you can imagine. 

I do not consider myself in really the position to decide that - I think the best would be to drop by in the _Nix Mozilla_ Matrix channel (https://matrix.to/#/#mozilla:nixos.org), link this PR and discuss it there maybe a bit.

In any case, I am **not** willing to maintain any proprietary code/packages, and never will. 
This means someone else has to do that, and that's - especially given this is a browser, so a very security-critical application - sometimes not an easy task. (e.g. timely updates are a must)

Would you be willing to take this over?

**Comment by Naxdy** [comment]
> Would you be willing to take maintainership, regardless of which way we go here?

Hmm, actually, probably not. My work schedule can be unpredictable at times, and I'm afraid of the scenario where upstream makes some big change that breaks the build script and I don't have the time to fix it. Not that unlikely of a scenario, seeing as they're planning on moving from extended support release to rapid releases soon.

I wouldn't mind being _added_ as a maintainer, but I definitely wouldn't want to be the _only_ one for that reason.

Think I'll probably close this PR then for now, but if someone else wants to have the torch, feel free to use this as a base for your own.

-----

In the meantime, if someone stumbles across this wanting workspaces in their Floorp, and also doesn't mind to compile the entire thing from scratch for every update, you can add this in your nix config instead of `pkgs.floorp`:

```nix
(pkgs.wrapFirefox
  (pkgs.floorp-unwrapped.overrideAttrs (old: {
    extraConfigureFlags = (old.extraConfigureFlags or [ ]) ++ [
      "--enable-private-components"
    ];
  }))
  { })
```

Note that this will pull in `unfree` code to your installation!

**Comment by Yeshey** [comment]
>In the meantime, if someone stumbles across this wanting workspaces in their Floorp, and also doesn't mind to compile the entire thing from scratch for every update, you can add this in your nix config instead of pkgs.floorp:

just a note that the snippet doesn't seem to be working anymore, at least for me in x86

```sh
error: builder for '/nix/store/fsqn5c2ibk1gb5lakwrprwk3gvk348zw-floorp-unwrapped-11.26.2.drv' failed with exit code 1;
       last 25 log lines:
       > WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
       >  0:02.30(B Using Python 3.12.10 from /build/mozbuild/srcdirs/source-9e3e83241977/_virtualenvs/build/bin/python(B(B
       >  0:02.30(B checking for vcs source checkout... no(B(B
       >  0:02.33(B checking for a shell... /nix/store/xy4jjgw87sbgwylm5kn047d9gkbhsr9x-bash-5.2p37/bin/bash(B(B
       >  0:02.34(B checking for host system type... x86_64-unknown-linux-gnu(B(B
       >  0:02.35(B checking for target system type... x86_64-unknown-linux-gnu(B(B
       >  0:02.64(B checking whether cross compiling... no(B(B
       >  0:02.73(B checking for the target C compiler... /nix/store/sfpkw15pigyls55nhprw4qk7bdaxb59x-clang-wrapper-19.1.7/bin/clang(B(B
       >  0:02.73(B checking for ccache... not found(B(B
       >  0:02.84(B checking whether the target C compiler can be used... yes(B(B
       >  0:02.84(B checking for the target C++ compiler... /nix/store/sfpkw15pigyls55nhprw4qk7bdaxb59x-clang-wrapper-19.1.7/bin/clang++(B(B
       >  0:02.92(B checking whether the target C++ compiler can be used... yes(B(B
       >  0:02.98(B checking for unwind.h... yes(B(B
       >  0:03.06(B checking for target linker... lld(B(B
       >  0:03.29(B checking for _Unwind_Backtrace... yes(B(B
       >  0:03.31(B Traceback (most recent call last):(B(B
       >  0:03.31(B   File "/build/source/configure.py", line 351, in <module>(B(B
       >  0:03.31(B     sys.exit(main(sys.argv))(B(B
       >  0:03.31(B              ^^^^^^^^^^^^^^(B(B
       >  0:03.31(B   File "/build/source/configure.py", line 141, in main(B(B
       >  0:03.31(B     sandbox.run()(B(B
       >  0:03.31(B   File "/build/source/python/mozbuild/mozbuild/configure/__init__.py", line 569, in run(B(B
       >  0:03.31(B     raise InvalidOptionError(msg)(B(B
       >  0:03.31(B mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-private-components(B(B
       > *** Fix above errors and then restart with "./mach build"
       For full logs, run:
         nix log /nix/store/fsqn5c2ibk1gb5lakwrprwk3gvk348zw-floorp-unwrapped-11.26.2.drv
error: 1 dependencies of derivation '/nix/store/qwz1wwnh063qjl5yr4f1w816xb4g2wr9-floorp-11.26.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kay8gb2b733yldy5wm6lcnl3iwiwr6ya-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m8iah025i0p3617i69108l7b9cbwwsxz-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8di283frwdzw5h67in125arffbhw23pj-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jv0c5bj9lg01cqbv165077m22ladkr9i-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d9ihw32qvfrs0baljf414ymq9pil0fkb-nixos-system-nixos-hyrulecastle-25.05.20250522.55d1f92.drv' failed to build
```

**Pull request closed without merging**
