### PR TITLE
headset: init at 4.0.0

### LINKED ISSUE #172880: Headset: a desktop music player powered by YouTube and Reddit
**Project description**

[Headset](http://headsetapp.co/) is a simple music player for Mac, Windows and Linux with integrated YouTube search, a home screen with popularity list by genres and eras, and best of all, a radio powered by Reddit. Headset takes the songs that are shared in over 80 music subreddits, categorizes them and plays them automatically. It's a great and pretty unique way to find new music as it is chosen by other humans like you and not by algorithms.

**Metadata**

* homepage URL: https://headsetapp.co/
* source URL: https://github.com/headsetapp/headset-electron
* license: mit
* platforms: unix, linux, darwin, windows

### PR DESCRIPTION
**Pull request by muscaln**
###### Description of changes

Fixes #172880

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
There is already version [4.1.1](https://github.com/headsetapp/headset-electron/releases/tag/v4.1.1).

**Comment by superherointj** [comment]
Why are you packaging from .deb instead of sources? Sources is (usually) preferable.

**Comment by onny** [comment]
Result of `nixpkgs-review pr 172904` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>headset</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Current version is: v4.2.1

You should have updated it instead of pushing old software. You certainly could.

**Comment by superherointj** [comment]
Current version is: v4.2.1

**Comment by onny** [comment]
You're right, version should have been updated and I'll do in a separate PR.
Packaging the deb for this kind of application is understandable. Electron apps are not always easy to build.

**Pull request merged**
