### PR TITLE
pythonRelaxDepsHook: fix usage in packages with `-` in pname

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

Fixes issue https://github.com/NixOS/nixpkgs/issues/176695.

When `pname` includes `-` or some other non alpha-numeric characters (with the exception of `.`), the generated `.whl` [file will have its non alpha-numeric characters converted to `_`](https://peps.python.org/pep-0491/#escaping-and-unicode). For example:

- `abc-cde` -> `abc_cde`
- `abc-cde-1.1` -> `abc_cde-1.1`

However we were trying to get the non-normalize name for the file, causing the `pythonRelaxDepsHook` to fail. This PR fixes it by normalizing the `.whl` filename.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @fabaff.

**Comment by thiagokokada** [comment]
@ofborg build archivy gitless python3Packages.testtools python3Packages.pysigma-backend-insightidr

**Comment by thiagokokada** [comment]
Retargeting to `staging` thanks to the huge number of rebuilds.

https://github.com/ofborg build archivy gitless python3Packages.testtools python3Packages.pysigma-backend-insightidr

**Comment by thiagokokada** [comment]
@ofborg build archivy gitless python3Packages.testtools python3Packages.pysigma-backend-insightidr

**Comment by thiagokokada** [comment]
@ofborg eval

**Comment by thiagokokada** [comment]
@ofborg build archivy gitless python3Packages.testtools python3Packages.pysigma-backend-insightidr

**Comment by thiagokokada** [comment]
@ofborg build gitless python3Packages.testtools python3Packages.pysigma-backend-insightidr

**Comment by thiagokokada** [comment]
CC @FRidh

**Comment by FRidh** [comment]
are the failing builds related?

**Comment by thiagokokada** [comment]
> > When pname includes - or some other non alpha-numeric characters...
> 
> The guidelines says that `pname` should be normalized according to PEP 0503. Thus only `-` should be part of a package's `pname` (at least new packages).  

Huh... Ok. Are you saying that we should only convert `-` to `_` them? I can also do this instead, it is just that the current regex should be more complete according to the PEP 0491 guidelines.

**Comment by thiagokokada** [comment]
Can I merge this PR :thinking: ? Is there something that you want to add?

CC @fabaff @FRidh.

**Comment by thiagokokada** [comment]
Fixed one additional (possible) issue.

@ofborg build archivy gitless python3Packages.testtools python3Packages.pysigma-backend-insightidr

**Pull request merged**
