### PR TITLE
cinelerra: unbreak the build (make compatible with gcc10)

### PR DESCRIPTION
**Pull request by iblech**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Why are we using https://github.com/ratopi/CinelerraCV? It looks like https://github.com/cinelerra-cv-team/cinelerra-cv is the actual upstream.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112680` at 39494b2f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/5c66bbd1e622698f4d82b45c190a995b">cinelerra</a></li></li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

pkg-config is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/video/cinelerra/default.nix:38:3:
```
   |
38 |   buildInputs =
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/applications/video/cinelerra/default.nix:20:5:
```
   |
20 |     (fetchpatch {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/video/cinelerra/default.nix:56:5:
```
   |
56 |     license = lib.licenses.gpl2;
   |     ^
```
</li>
  </ul>
</details>

**Comment by iblech** [comment]
Oh! I didn't know that and just trusted the current build description without rechecking. I will take a look!

**Comment by iblech** [comment]
I switched to the canonical upstream (without bumping the revision -- there are just a couple commits and they only pertain comments and such, this way the pull request is easier to trust). I also cleaned up the build description a little bit, but I'd prefer to leave `buildInputs` as it is because I'm not actually a user of cinelerra and hence cannot test functionality. I just wanted to unbreak the build :-)

**Comment by SuperSandro2000** [comment]
Having pkg-config in buildInputs breaks cross compiling and moving it is save for end user applications. If it fails the build fails.

**Comment by iblech** [comment]
Okay, fair. :-) In the new force push, I moved pkg-config and some other seemingly safe autoconf-related inputs over to `nativeBuildInputs`. The binary still starts.

**Pull request merged**
