### PR TITLE
uhdm, surelog 1.83 -> 1.84

### PR DESCRIPTION
**Pull request by hzeller**
## Description of changes

Update both, UHDM and Surelog (that are somewhat version-locked) to 1.84. Two separate commits.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hzeller** [comment]
As discussed in [comment in #311846](https://github.com/NixOS/nixpkgs/pull/311846#issuecomment-2119457410) - also add myself to maintainers (separate commits).

**Comment by hzeller** [comment]
Anyone able to merge ?

**Comment by hzeller** [comment]
(bump)

**Comment by smancill** [comment]
LGTM but could you mark uhdm as broken on Darwin. It seems that it may need some patching.

**Comment by smancill** [comment]
Actually no. Version 1.83 is built on Darwin: https://hydra.nixos.org/build/269303906, so this is a regression

**Comment by thoughtpolice** [comment]
@ofborg build

Let's see if it was a flake (the boost error makes me think this was maybe on a runner with an older version of Nix, since that's a bug that's since been fixed AFAIK.)

**Comment by smancill** [comment]
Result of `nixpkgs-review pr 332963` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>surelog</li>
    <li>yosys-synlig</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>uhdm</li>
  </ul>
</details>

**Comment by smancill** [comment]
Sorry, `uhdm` does build. It's `surelog` the one that has been failing on Darwin, but it was already broken:

https://hydra.nixos.org/job/nixpkgs/trunk/surelog.x86_64-darwin

**Comment by hzeller** [comment]
This got stalled somewhat. Getting back to this; made a new PR #354369

**Pull request closed without merging**
