### PR TITLE
Pin packages to python2

### PR DESCRIPTION
**Pull request by aneeshusa**
###### Motivation for this change

Help prepare for #18185.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @domenkozar

### CODE REVIEW

**Comment by aske** [comment]
Looks good to me, though I don't use `nmap`, so I'm not sure about disabling python and losing default `ndiff` and `zenmap` binaries, maybe a lot of people may want them as a common case? cc @mornfall @thoughtpolice @fpletz

**Comment by fpletz** [comment]
I'm okay with the nmap changes.

**Comment by FRidh** [comment]
please rebase

**Comment by aske** [comment]
I think merge conflict is resolved now (ah, a bit unfortunate that notifications are not generated for force pushes).

**Review by FRidh — APPROVED** [review]

**Comment by aneeshusa** [comment]
Hmm, I thought GitHub recently started sending emails when new commits were pushed, which is why I didn't comment. If that's not the case I will make sure to comment after pushing/rebasing in the future.

**Comment by FRidh** [comment]
GitHub doesn't inform when pushing changes (and I am glad for that). So indeed, just add a comment if you want another review.

**Comment by FRidh** [comment]
by the way, you might want to use the following for `nmap`.

```
let
  pythonEnv = python2.withPackages( ps: with ps; [ ] ++ optionals graphicalSupport [ pygtk pysqlite pygobject2 pycairo ]);
in ...
  buildInputs =  [ libpcap pkgconfig openssl ] ++ optionals pythonSupport pythonEnv ++ optionals graphicalSupport [ libX11 gtk2 ];
```
You should then be able to remove the `wrapProgram`. Anyway, if you would make these changes, please do make it a separate commit.

**Comment by aneeshusa** [comment]
@FRidh That indeed looks nicer, but it seems that the `withPackages` function is relying on the deprecated `lib.closePropagation` function, and I would prefer not to add a new dependency on a deprecated function. I would try to rewrite it myself but I have no idea what `closePropagation` does, so for now I'd like to keep this as-is.

**Comment by FRidh** [comment]
@aneeshusa I wouldn't worry about that. `withPackages` and `buildEnv` will remain.

**Comment by aneeshusa** [comment]
@FRidh I added a new commit that uses `.withPackages` (and also rebased).

**Comment by FRidh** [comment]
I thought this had already been merged.  Anyway, just to be clear, using `.withPackages` isn't necessary. If you've tested it and are confident that it works, then let's use it.

**Comment by aneeshusa** [comment]
@FRidh I've been using the changes in this branch since I made the PR, and I haven't seen any breakage yet, so I feel comfortable that this works.

**Comment by FRidh** [comment]
Good. Since this causes quite some rebuilding I pushed the commits to staging instead.

**Comment by aneeshusa** [comment]
@FRidh FYI it's now possible to change the "base" of a PR (e.g. from master to staging), so in the future please let me/the contributor know so we can change it and the PR status can be shown as "merged" instead of "closed", which I've always found confusing.

**Comment by FRidh** [comment]
@aneeshusa ahh interesting, didn't know that. Will do in the future.

**Pull request closed without merging**
