### PR TITLE
Fix man pages in i3-gaps

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Motivation for this change

The files with the .man extension are asciidoc versions of the man
pages and should not be copied to share/man or mandb complains:

mandb: warning: …/man/man1/i3.man.gz: ignoring bogus filename

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/cc maintainers of i3: @modulistic @fpletz @globin
/cc maintainers of i3-gaps  @fmthoma

### CODE REVIEW

**Comment by DamienCassou** [comment]
I removed one commit because @r-ryantm updated i3-gaps to 4.18.1 in the meantime.

**Review by cole-h — APPROVED** [review]
Diff LGTM. In the `nixpkgs-review` shell, `ls results/i3-gaps/share/man/man1` shows all files are `*.1.gz`, whereas before this fix, they are `*.man.gz`.

```
https://github.com/NixOS/nixpkgs/pull/86294
10 packages built:
i3 i3-gaps i3-layout-manager i3-wk-switch polybarFull python37Packages.i3ipc python37Packages.py3sta
tus python38Packages.i3ipc python38Packages.py3status raiseorlaunch
```

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 86294` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
<br>- i3
<br>- i3-gaps
<br>- i3-layout-manager
<br>- i3-wk-switch
<br>- polybarFull
<br>- python37Packages.i3ipc
<br>- python37Packages.py3status
<br>- python38Packages.i3ipc
<br>- python38Packages.py3status
<br>- raiseorlaunch
</details>

**Comment by DamienCassou** [comment]
@cole-h I changed my PR so it uses `installManPage` as you requested.

**Review by cole-h — APPROVED** [review]
Diff LGTM. Thanks!

```
[12 built, 151 copied (587.8 MiB), 148.4 MiB DL]
https://github.com/NixOS/nixpkgs/pull/86294
10 packages built:
i3 i3-gaps i3-layout-manager i3-wk-switch polybarFull python37Packages.i3ipc python37Packages.py3status python38Packages.i3ipc python38Packages.py3status raiseorlaunch
```

**Pull request merged**
