### PR TITLE
libwebrtc

### PR DESCRIPTION
**Pull request by mkg20001**
###### Motivation for this change

Make telegram calls work again

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mkg20001** [comment]
Currently there's a problem with gclient, as it tries to fetch the source

Possibly creating a git repo out of the source and fetching from there could work, or disabling pulling

**Comment by mkg20001** [comment]
Got the cloning to work, problem is there's a list of deps in ${src}/DEPS that it tries to pull in

Should be possible to take those deps and also create fake git repos

**Comment by mkg20001** [comment]
Working on pre-fetching those deps and then placing them into the right dir in configure

**Comment by conferno** [comment]
we could `fetchpatch` ARCH patches from https://github.com/archlinux/svntogit-community instead of including them into nixpkgs

**Comment by mkg20001** [comment]
I postponed that until I actually get past configure phase

**Comment by primeos** [comment]
> Currently there's a problem with gclient, as it tries to fetch the source

Yeah, that should be the most difficult problem to solve.

> Working on pre-fetching those deps and then placing them into the right dir in configure

That would be very nice if that works out.

If it turns out to be too difficult and if `gclient` fetches the dependencies in a deterministic way (AFAIK all dependencies are either specified via a Git revision (but git-clone isn't deterministic IIRC) or e.g. a hash of the binary to fetch) then you could also write an intermediate fixed-output derivation that takes the `libwebrtc` source and then runs `gclient` to fetch the sources.

**Comment by mkg20001** [comment]
Currently git fetching is done by nix-prefetch-git, but some of the packages have cipd packages as sources specified, I'm not sure how that should be handled

So far I've found that packages require a platform variable, like linux-amd64, which if replaced leads to a package https://chrome-infra-packages.appspot.com/p/infra/tools/luci/isolate/linux-amd64/+/

Then choosing the latest version and downloading that https://chrome-infra-packages.appspot.com/p/infra/tools/luci/isolate/linux-amd64/+/ScErc0J9LrGAd_W-B-h0JC5BGACx-AQrJl4NVezfSAUC gives a zip file

In that particular case I got a binary, I'd either need to patchelf it or create a FHS, right?

This is getting complicated...

**Comment by primeos** [comment]
> In that particular case I got a binary, I'd either need to patchelf it or create a FHS, right?

Yeah, running the `autoPatchelf` command manually might be the best/easiest approach (see `autoPatchelfHook` in https://nixos.org/manual/nixpkgs/stable/#ssec-setup-hooks). There might be an even better approach but I never really looked into those things (/ luckily never needed them much).

> This is getting complicated...

Yeah, unfortunately this'll be a huge PITA to get packaged with Nix :o

**Comment by SuperSandro2000** [comment]
Please fix the pipeline.

**Comment by mkg20001** [comment]
I currently don't have the time to push this forward. PR can be taken over if someone else is willing to finish it

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Pull request closed without merging**
