### PR TITLE
jetbrains: update.py version update

### LINKED ISSUE #166216: CLion build failure
### Describe the bug
CLion 2021.3.3 derivation fails to build.

### Steps To Reproduce
1. Add `jetbrains.clion` to system/user packages
2. `nixos-rebuild`

### Expected behavior
The system rebuilds.

### Screenshots

```
/nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3/clion/bin/format.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/sh"
/nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3/clion/bin/restart.py: interpreter directive changed from "#!/usr/bin/env python" to "/nix/store/hb1lzaisgx2m9n29hqhh6yp6hasplq1v-python3-3.9.10/bin/python"
/nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3/clion/bin/clion.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/sh"
/nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3/clion/plugins/remote-dev-server/bin/launcher.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/sh"
checking for references to /build/ in /nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3...
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
/nix/store/lkk0hf9h4x85mb4lrsf2sh25qm2i4n18-stdenv-linux/setup: line 87: cd: /nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3/clion-2021.3.3: No such file or directory
error: builder for '/nix/store/ywqpaza1v0wpgvfhvp8a54y8j24kvnbw-clion-2021.3.3.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/ihmd0x2870f94lcqiwf8aah1bdczbgys-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jdcs14nj0ysz1rh4y7alxkx1avdy40fm-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5114s9478y1a1rsna05pn2cdk47pma2v-nixos-system-CAPRICA-22.05pre364329.ce8cbe3c01f.drv' failed to build

```

### Additional context

Seems the `clion-$VERSION` folder has been renamed to just `clion`:
```
$ ls -la /nix/store/rpk8vd0habrxqfj7mg29yk56gsyvg1b1-clion-2021.3.3
total 11588
drwxr-xr-x    6 nixbld1 nixbld     4096 Mar 29 19:37 .
drwxrwxr-t 5615 root    nixbld 11833344 Mar 29 19:38 ..
drwxr-xr-x    2 nixbld1 nixbld     4096 Mar 29 19:37 bin
drwxr-xr-x    8 nixbld1 nixbld     4096 Mar 29 19:37 clion
drwxr-xr-x    3 nixbld1 nixbld     4096 Mar 29 19:37 libexec
drwxr-xr-x    3 nixbld1 nixbld     4096 Mar 29 19:37 share
```

### Notify maintainers

@Mic92 @edwtjo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.29, NixOS, 22.05 (Quokka), 22.05pre363214.1d08ea2bd83`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(zane): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by dev-null-undefined**
###### Description of changes

updated JetBrains software versions 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
`jetbrains.clion` does not build for me on 553b2f048a98c8432d04dfa38bb3e295d1b1c504:

```
/nix/store/lkk0hf9h4x85mb4lrsf2sh25qm2i4n18-stdenv-linux/setup: line 87: cd: /nix/store/k7xlbwn1sq4is45spnpydc3waq1mphf7-clion-2021.3.4/clion-2021.3.4: No such file or directory
```

I think #166320 is probably still needed.

**Comment by dev-null-undefined** [comment]
> `jetbrains.clion` does not build for me on [553b2f0](https://github.com/NixOS/nixpkgs/commit/553b2f048a98c8432d04dfa38bb3e295d1b1c504):
> 
> ```
> /nix/store/lkk0hf9h4x85mb4lrsf2sh25qm2i4n18-stdenv-linux/setup: line 87: cd: /nix/store/k7xlbwn1sq4is45spnpydc3waq1mphf7-clion-2021.3.4/clion-2021.3.4: No such file or directory
> ```
> 
> I think #166320 is probably still needed.

Well, now I am confused. What is causing this issue? It works for me. There is no difference in the archive. I have no idea what is happening.

**Comment by bobby285271** [comment]
> What is causing this issue?

I am not sure, how do you build the package? Are you building the package on 553b2f048a98c8432d04dfa38bb3e295d1b1c504 (and is the git tree clean)?

**Comment by dev-null-undefined** [comment]
> > What is causing this issue?
> 
> I am not sure, how do you build the package? Are you building the package on [553b2f0](https://github.com/NixOS/nixpkgs/commit/553b2f048a98c8432d04dfa38bb3e295d1b1c504) (and is the git tree clean)?

You are correct my bad seems like it's indeed still broken my bad I must have been building with unclean git tree I guess. After a hard reset, it fails for me as well.

**Comment by AnatolyPopov** [comment]
Closing this one since it's outdated and upgrade to newer versions is merged in https://github.com/NixOS/nixpkgs/pull/181595

**Pull request closed without merging**
