### PR TITLE
Python: autogenerate PyPI source data

### PR DESCRIPTION
**Pull request by FRidh**
Recently PyPI changed their url scheme. Therefore, when a package is updated the entire url needs to be updated. That was it for me. I think we need a way to autogenerate PyPI source data. See also issue #11587. I recommend we discuss autogenerating PyPI data in this issue, and discuss in this PR only implementation details.

To do:
- [ ] test whether all packages build (https://headcounter.org/hydra/jobset/iElectric/python-wip, ~30 failing)
- [ ] document changes to `buildPythonPackage`
- [ ] announce changes
- [x] integrate meta.description, meta.homepage and meta.license

Possible improvements:
- [ ] add a `pypi ? False` option to determine whether to use PyPI or not. Currently it is determined automatically.
- [ ] parse licenses

Regressions:
- packages that specify both name and version, and have the version already included in the name will show the version twice now.

### CODE REVIEW

**Comment by FRidh** [comment]
cc @domenkozar @grahamc @copumpkin @manveru @garbas

**Comment by FRidh** [comment]
So far it only creates the JSON data. License parsing is something for later.

**Comment by FRidh** [comment]
`buildPythonPackage` now uses by default PyPI. If only a name is given, the latest version is used. If also a version is given, then that version is used. When a `src` is given, that is used instead.

**Comment by copumpkin** [comment]
If this proves to be too gnarly, I was thinking of a more lightweight option, which is to introduced a new `fetchPyPI` fixed-output derivation that we can use for all our `src` attributes, without changing anything else. The fetcher would know how to figure out the correct URL and but would otherwise still produce the same tarballs as we were getting before.

**Comment by FRidh** [comment]
A function like `fetchPyPI` that obtains the url and hash via the JSON API as I do now is indeed a much lighter-weight option. The only downside is having to set the version manually. And it would be a bit more verbose.

Or we could have `fetchPyPI` and also still generate a list with meta-data and available versions per package. I can also leave `buildPythonPackage` untouched and create instead say `buildPyPIPackage` that uses `buildPythonPackage`. 

What we need is to find an agreement on what kind of data we want to have in NIxpkgs and what not. 
And as I think @copumpkin wrote somewhere else as well: do we want to have all packages, or a curated list. In case of the latter it would make sense having to explicitly set the version.

**Comment by copumpkin** [comment]
@FRidh explicitly picking the version doesn't seem overly onerous, since we do it everywhere else. The other question is a much bigger one though 😄

**Comment by FRidh** [comment]
fetchPyPI: 
https://github.com/triton/triton/commit/ffcbbf7211310ac3c3d69e52bf11ef2cba630612

**Comment by FRidh** [comment]
#15007 is an alternative to the PR where I use a separate function, `buildPyPIPackage`, to build a PyPI package. I think that is a better solution.

**Pull request closed without merging**
