### PR TITLE
osu-lazer: 2020.714.0 -> 2020.725.0

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasj19** [comment]
Tested with `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 93726"`.
Builds and runs fine.

I would have an issue with the executable name which is `osu\!` ... we should change it to `osu` or `osu-lazer`

**Comment by oxalica** [comment]
@dasj19
> I would have an issue with the executable name which is osu\! ... we should change it to osu or osu-lazer

It is just the default binary name. I'm not sure if we need to rename it, since there are also many packages having binary names differ from package name.

**Comment by dali99** [comment]
Shouldnt @r-ryantm be able to bump these automatically?

**Comment by dali99** [comment]
@ryantm seems @r-ryantm is failing due to it not having an up to date nixpkgs to edit?

```
2020-07-25T16:55:07 osu-lazer 2020.714.0 -> 2020.717.0 https://repology.org/metapackage/osu-lazer/versions
2020-07-25T16:55:20 FAIL /var/cache/nixpkgs-update/nixpkgs/pkgs/games/osu-lazer/default.nix: openFile: does not exist (No such file or directory)
2020-07-25T16:55:21 osu-lazer 2020.714.0 -> 2020.717 https://repology.org/metapackage/osu-lazer/versions
2020-07-25T16:55:34 FAIL /var/cache/nixpkgs-update/nixpkgs/pkgs/games/osu-lazer/default.nix: openFile: does not exist (No such file or directory)
```

**Comment by oxalica** [comment]
@dali99 Where is the log from? Does @r-ryantm try to auto-update all packages with `updateScript` and `homepage` referring GitHub repo? I'm not sure how the bot works. ([nixpkgs-update](https://github.com/ryantm/nixpkgs-update) doesn't not have details about the bot also)

**Comment by dali99** [comment]
I believe it just updates the url and shasum from the github releases

**Pull request merged**
