### PR TITLE
update 1504.01 -> 1506.00

### PR DESCRIPTION
**Pull request by PyroLagus**
Tested locally and it works.

### CODE REVIEW

**Comment by jagajaga** [comment]
Rename as it said in `CONTRIBUTING.md`.

**Comment by C0DEHERO** [comment]
Huh? rename what?

**Comment by jagajaga** [comment]
Rename commit :)

**Comment by C0DEHERO** [comment]
i thought this was good? or should i rename it to "voxelands: update 1504.01 -> 1506.00"?

**Comment by devhell** [comment]
@C0DEHERO Yes :)

**Comment by jagajaga** [comment]
But without the word `update` :)

**Pull request merged**
