### PR TITLE
llvmPackages_12.compiler-rt: fix build on darwin

### LINKED ISSUE #125449: llvmPackages_12.compiler-rt fails to build on MacOS Mojave
**Describe the bug**
Building `clang_12` or `llvmPackage_12.compiler-rt` fails with:

```
[ 67%] Built target clang_rt.builtins_x86_64_osx
[ 67%] Built target RTfuzzer.osx
make: *** [Makefile:149: all] Error 2
builder for '/nix/store/lllxgbd4k1jr0msbjmi22vl3j15lwj22-compiler-rt-12.0.0.drv' failed with exit code 2
cannot build derivation '/nix/store/g5y336if01gag8vi1mdlsq3l95hsz956-clang-wrapper-12.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/g5y336if01gag8vi1mdlsq3l95hsz956-clang-wrapper-12.0.0.drv' failed
```

**To Reproduce**
1. `nix-env -iA nixpkgs.clang_12`
2. wait until approximately 70% (sometimes a few percent earlier)

**Additional context**
Compilation log for `nix-shell --pure` with only `clang_12`:
[clang_12.txt](https://github.com/NixOS/nixpkgs/files/6588426/clang_12.txt)

Compilation log for `nix-shell --pure` with only `llvmPackages_12.compiler-rt`:
[rt-compiler.txt](https://github.com/NixOS/nixpkgs/files/6588427/rt-compiler.txt)

I had this problem with Sierra with XCode 9.2 also.
I just upgraded to Mojave 10.14.6 and XCode 11.13.1.

**Notify maintainers**

@lovek323 @dtzWill @primeos @matthewbauer

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.11`
 - channels(peterhil): `"darwin"`
 - channels(root): `"nixpkgs-21.05pre290801.7013a0f2791"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: llvmPackages_12.compiler-rt
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Fix: #125449

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Looks like something we may want to try to upstream?

**Comment by veprbl** [comment]
> Looks like something we may want to try to upstream?

Yes: https://reviews.llvm.org/D103598

**Comment by veprbl** [comment]
Before anyone asks, IIRC Phabricator allows stable downloads for patches.

**Comment by veprbl** [comment]
Before anyone asks, IIRC Phabricator doesn't support stable downloads for patches.

**Review by risicle — APPROVED** [review]
Nice - looks sensible, `nixpkgs-review` shows all its reverse dependencies but `openethereum` now build for me, macos 10.15.

**Pull request merged**
