### PR TITLE
prometheus-*: fixes to deal with goPackages multiple-outputs changes

### PR DESCRIPTION
**Pull request by benley**
Everything that uses buildGoPackage is affected by that change :(

### CODE REVIEW

**Comment by wkennington** [comment]
Most of this stuff should be in go-packages by now. I guess we still have a
lot to do for that migration.

**Comment by wkennington** [comment]
Also worth noting is that protobuf.bin should be a nativeBuildInput and not
a regular buildInput. Cross compiling isn't working yet, but I would like
to make it possible eventually.

**Comment by benley** [comment]
Should protobuf (the non-goPackages one) and vim also be moved to nativeBuildinputs as well?

I can start merging these into go-packages.nix after this set of changes, if that is where everything built with Go should live.

**Comment by benley** [comment]
even better, it turns out protobuf.bin isn't even necessary to the build process anymore.

**Comment by wkennington** [comment]
I believe go-packages is the ideal place at this point in time although we still have a lot of legacy stuff we need to clean up.

As for nativeBuildInputs it depends, is it being used by the build machine or by the machine the package is built for. My best guess is that proto would be used by the build and vim called during execution for the end user. By this logic proto is native and vim is a regular buildInput.

**Comment by benley** [comment]
vim was being used during the build, believe it or not.  Something in embed-static.sh used xxd, which apparently comes from vim.

**Comment by benley** [comment]
heh, travis is OOMing now.

**Comment by benley** [comment]
I think I am done messing with this now.

**Pull request merged**
