### PR TITLE
vimPlugins: add palette-nvim and obsidian-nvim

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Add ~~3~~ 2 vim plugins:
- ~~[veil.nvim](https://github.com/willothy/veil.nvim)~~
- [palette.nvim](https://github.com/roobert/palette.nvim)
- [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim)

I manually updated `generated.nix` as the script was failing to pick the latest commit for `nvim-treesitter-textobjects`:
```
1359 plugins were checked, 1 plugin(s) could not be downloaded:

PluginDesc(repo=Repo(nvim-treesitter-textobjects, https://github.com/nvim-treesitter/nvim-treesitter-textobjects/), branch='', alias=''): not well-formed (invalid token): line 48, column 8
Traceback (most recent call last):
  File "/nix/store/70z5xbmynq2jifd18wymcaj3rgi835xh-vim-plugins-updater-0.1/lib/pluginupdate.py", line 718, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/70z5xbmynq2jifd18wymcaj3rgi835xh-vim-plugins-updater-0.1/lib/pluginupdate.py", line 591, in prefetch_plugin
    commit, date = repo.latest_commit()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/70z5xbmynq2jifd18wymcaj3rgi835xh-vim-plugins-updater-0.1/lib/pluginupdate.py", line 69, in f_retry
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/70z5xbmynq2jifd18wymcaj3rgi835xh-vim-plugins-updater-0.1/lib/pluginupdate.py", line 195, in latest_commit
    root = ET.fromstring(xml)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 48, column 8
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 277537` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.palette-nvim</li>
    <li>vimPlugins.veil-nvim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 277537` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>vimPlugins.obsidian-nvim</li>
    <li>vimPlugins.palette-nvim</li>
    <li>vimPlugins.veil-nvim</li>
  </ul>
</details>

**Comment by teto** [comment]
the deprecation notice of veil.nvim worries me a bit, though not a big issue. Do you know if the script failure was transient or sthg else ?

**Comment by GaetanLepage** [comment]
> the deprecation notice of veil.nvim worries me a bit, though not a big issue.

You are right, let's not add it. A nixvim user was asking for it, but I suggested that we wait for the stable rewrite.

>  Do you know if the script failure was transient or sthg else ?

My hypothesis is that it doesn't like the [message of the latest commit of nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/0e2d5bd4cbe75849a013901555d436a48c6680cb).
If this plugin gets a new commit, it might get rid of the error...

**Review by teto — APPROVED** [review]

**Pull request merged**
