### PR TITLE
gtk-vnc: remove gtk2 support, 0.5.3 -> 0.6.0

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

No package was using gtk-vnc with gtk2.
I'm not sure why it even causes rebuild..
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lethalman** [comment]
Why are you removing gtk2 support?

**Comment by groxxda** [comment]
@lethalman it wasn't used anywhere. Should I add it back and only change the default to gtk3 so we don't have to use the override everywhere?

**Comment by Mic92** [comment]
If it is unused, then there is no value in keeping the option.

**Comment by groxxda** [comment]
travis failure is unrelated to my change. (it's fixed by #19132 with which i tested this pr)

**Comment by Mic92** [comment]
thanks.

**Pull request merged**
