### PR TITLE
[18.03] backport trezord: 2.0.19 -> 2.0.24

### PR DESCRIPTION
**Pull request by 1000101**
(cherry picked from commit 10c56c5cfbde7a2180d82e22c35887527b1e909f)

Upgrade of the package.

###### Motivation for this change

Having the latest up-to-date package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build trezord

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
cc @Infinisil  
(determined because they merged #49157)

**Comment by Infinisil** [comment]
Why should this be backported? And in any case, I really think it's too late to backport to 18.03 now. 18.09 maybe, but this change isn't one that needs backporting anyways (unless I'm missing something?).

**Comment by Infinisil** [comment]
From [The release announcement](https://discourse.nixos.org/t/nixos-18-09-jellyfish-released/1076):

> Note that 18.03 is expected to receive important fixes at least until the end of October. Further support is not guaranteed, and shouldn’t be expected.

**Pull request closed without merging**
