### PR TITLE
vscode, vscodium: 1.73.1 -> 1.74.1

### PR DESCRIPTION
**Pull request by bobby285271**
I have `Allow edits and access to secrets by maintainers` enabled and you can push stuff here if you want.

Ofborg failures are (hopefully) not related to this bump:
- https://hydra.nixos.org/job/nixpkgs/trunk/vscode-extensions.vadimcn.vscode-lldb.x86_64-darwin
- https://github.com/NixOS/nixpkgs/pull/159220#issuecomment-1036231572

###### Description of changes

The update is not that trivial probably because of https://github.com/microsoft/vscode/commit/23b25e9d4d3aad79f59a087f25bffb859afea88e.

I guess I will open a PR first and hopefully get some feedback :upside_down_face: 

- Closes #205080
- Closes #205042
- Closes #205074
- Closes #205672
- Closes #205661
- Closes #206324

###### To test

If you use vscode-fhs, please help test vscode-fhs.

For vscode-with-extensions, to test some extensions, e.g. `vscode-extensions.vadimcn.vscode-lldb`, use 

```
nix-build -I nixpkgs=. -E 'with import <nixpkgs> { config = { allowUnfree = true; }; }; vscode-with-extensions.override { vscodeExtensions = with vscode-extensions; [ vadimcn.vscode-lldb ]; }'
```

**Don't just** `nix-build -A vscode-extensions.vadimcn.vscode-lldb`, e.g. the former will fail to eval on f007395f951878c8c0b507f6e8f621d417b90744 but the latter does build.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Launches vscode-fhs, vscode-with-extensions myself

**Comment by linsui** [comment]
VSCodium works for me. Thanks!

image

**Comment by adamcstephens** [comment]
vscode works for me. I am *not* using nix managed extensions though, so didn't test that functionality.

**Comment by SamLukeYes** [comment]
`vscode.fhs` works for me on `x86_64-linux`

**Comment by bobby285271** [comment]
@ofborg build vscodium
@ofborg test vscodium.xorg

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 206007 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package marked as broken and skipped:</summary>  <ul>    <li>vscode-extensions.ms-vscode.go</li>  </ul></details><details>  <summary>245 packages built:</summary>  <ul>    <li>vscode</li>    <li>vscode-extensions.Arjun.swagger-viewer</li>    <li>vscode-extensions.WakaTime.vscode-wakatime</li>    <li>vscode-extensions._1Password.op-vscode</li>    <li>vscode-extensions._2gua.rainbow-brackets</li>    <li>vscode-extensions._4ops.terraform</li>    <li>vscode-extensions.a5huynh.vscode-ron</li>    <li>vscode-extensions.adpyke.codesnap</li>    <li>vscode-extensions.alanz.vscode-hie-server</li>    <li>vscode-extensions.alefragnani.bookmarks</li>    <li>vscode-extensions.alefragnani.project-manager</li>    <li>vscode-extensions.alexdima.copy-relative-path</li>    <li>vscode-extensions.alygin.vscode-tlaplus</li>    <li>vscode-extensions.angular.ng-template</li>    <li>vscode-extensions.antfu.icons-carbon</li>    <li>vscode-extensions.antfu.slidev</li>    <li>vscode-extensions.antyos.openscad</li>    <li>vscode-extensions.apollographql.vscode-apollo</li>    <li>vscode-extensions.arcticicestudio.nord-visual-studio-code</li>    <li>vscode-extensions.arrterian.nix-env-selector</li>    <li>vscode-extensions.asciidoctor.asciidoctor-vscode</li>    <li>vscode-extensions.astro-build.astro-vscode</li>    <li>vscode-extensions.asvetliakov.vscode-neovim</li>    <li>vscode-extensions.attilabuti.brainfuck-syntax</li>    <li>vscode-extensions.azdavis.millet</li>    <li>vscode-extensions.b4dm4n.vscode-nixpkgs-fmt</li>    <li>vscode-extensions.baccata.scaladex-search</li>    <li>vscode-extensions.badochov.ocaml-formatter</li>    <li>vscode-extensions.bbenoist.nix</li>    <li>vscode-extensions.benfradet.vscode-unison</li>    <li>vscode-extensions.betterthantomorrow.calva</li>    <li>vscode-extensions.bierner.emojisense</li>    <li>vscode-extensions.bierner.markdown-checkbox</li>    <li>vscode-extensions.bierner.markdown-emoji</li>    <li>vscode-extensions.bierner.markdown-mermaid</li>    <li>vscode-extensions.bmalehorn.vscode-fish</li>    <li>vscode-extensions.bmewburn.vscode-intelephense-client</li>    <li>vscode-extensions.bodil.file-browser</li>    <li>vscode-extensions.bradlc.vscode-tailwindcss</li>    <li>vscode-extensions.brettm12345.nixfmt-vscode</li>    <li>vscode-extensions.bungcip.better-toml</li>    <li>vscode-extensions.catppuccin.catppuccin-vsc</li>    <li>vscode-extensions.chenglou92.rescript-vscode</li>    <li>vscode-extensions.christian-kohler.path-intellisense</li>    <li>vscode-extensions.cmschuetz12.wal</li>    <li>vscode-extensions.codezombiech.gitignore</li>    <li>vscode-extensions.coenraads.bracket-pair-colorizer</li>    <li>vscode-extensions.coenraads.bracket-pair-colorizer-2</li>    <li>vscode-extensions.coolbear.systemd-unit-file</li>    <li>vscode-extensions.cweijan.vscode-database-client2</li>    <li>vscode-extensions.daohong-emilio.yash</li>    <li>vscode-extensions.dart-code.dart-code</li>    <li>vscode-extensions.dart-code.flutter</li>    <li>vscode-extensions.davidanson.vscode-markdownlint</li>    <li>vscode-extensions.davidlday.languagetool-linter</li>    <li>vscode-extensions.dbaeumer.vscode-eslint</li>    <li>vscode-extensions.denoland.vscode-deno</li>    <li>vscode-extensions.dhall.dhall-lang</li>    <li>vscode-extensions.dhall.vscode-dhall-lsp-server</li>    <li>vscode-extensions.disneystreaming.smithy</li>    <li>vscode-extensions.divyanshuagrawal.competitive-programming-helper</li>    <li>vscode-extensions.donjayamanne.githistory</li>    <li>vscode-extensions.dotjoshjohnson.xml</li>    <li>vscode-extensions.dracula-theme.theme-dracula</li>    <li>vscode-extensions.eamodio.gitlens</li>    <li>vscode-extensions.editorconfig.editorconfig</li>    <li>vscode-extensions.edonet.vscode-command-runner</li>    <li>vscode-extensions.eg2.vscode-npm-script</li>    <li>vscode-extensions.elixir-lsp.vscode-elixir-ls</li>    <li>vscode-extensions.elmtooling.elm-ls-vscode</li>    <li>vscode-extensions.emmanuelbeziat.vscode-great-icons</li>    <li>vscode-extensions.esbenp.prettier-vscode</li>    <li>vscode-extensions.ethansk.restore-terminals</li>    <li>vscode-extensions.eugleo.magic-racket</li>    <li>vscode-extensions.faustinoaq.lex-flex-yacc-bison</li>    <li>vscode-extensions.file-icons.file-icons</li>    <li>vscode-extensions.firefox-devtools.vscode-firefox-debug</li>    <li>vscode-extensions.foam.foam-vscode</li>    <li>vscode-extensions.formulahendry.auto-close-tag</li>    <li>vscode-extensions.formulahendry.auto-rename-tag</li>    <li>vscode-extensions.formulahendry.code-runner</li>    <li>vscode-extensions.foxundermoon.shell-format</li>    <li>vscode-extensions.freebroccolo.reasonml</li>    <li>vscode-extensions.gencer.html-slim-scss-css-class-completion</li>    <li>vscode-extensions.github.codespaces</li>    <li>vscode-extensions.github.copilot</li>    <li>vscode-extensions.github.github-vscode-theme</li>    <li>vscode-extensions.github.vscode-pull-request-github</li>    <li>vscode-extensions.gitlab.gitlab-workflow</li>    <li>vscode-extensions.golang.go</li>    <li>vscode-extensions.grapecity.gc-excelviewer</li>    <li>vscode-extensions.graphql.vscode-graphql</li>    <li>vscode-extensions.gruntfuggly.todo-tree</li>    <li>vscode-extensions.hashicorp.terraform</li>    <li>vscode-extensions.haskell.haskell</li>    <li>vscode-extensions.hookyqr.beautify</li>    <li>vscode-extensions.humao.rest-client</li>    <li>vscode-extensions.ibm.output-colorizer</li>    <li>vscode-extensions.iciclesoft.workspacesort</li>    <li>vscode-extensions.influxdata.flux</li>    <li>vscode-extensions.ionide.ionide-fsharp</li>    <li>vscode-extensions.irongeek.vscode-env</li>    <li>vscode-extensions.james-yu.latex-workshop</li>    <li>vscode-extensions.jdinhlife.gruvbox</li>    <li>vscode-extensions.jebbs.plantuml</li>    <li>vscode-extensions.jkillian.custom-local-formatters</li>    <li>vscode-extensions.jnoortheen.nix-ide</li>    <li>vscode-extensions.jock.svg</li>    <li>vscode-extensions.johnpapa.vscode-peacock</li>    <li>vscode-extensions.jpoissonnier.vscode-styled-components</li>    <li>vscode-extensions.justusadam.language-haskell</li>    <li>vscode-extensions.kahole.magit</li>    <li>vscode-extensions.kamadorueda.alejandra</li>    <li>vscode-extensions.kamikillerto.vscode-colorize</li>    <li>vscode-extensions.kddejong.vscode-cfn-lint</li>    <li>vscode-extensions.kubukoz.nickel-syntax</li>    <li>vscode-extensions.llvm-vs-code-extensions.vscode-clangd</li>    <li>vscode-extensions.lokalise.i18n-ally</li>    <li>vscode-extensions.lucperkins.vrl-vscode</li>    <li>vscode-extensions.mads-hartmann.bash-ide-vscode</li>    <li>vscode-extensions.marp-team.marp-vscode</li>    <li>vscode-extensions.matangover.mypy</li>    <li>vscode-extensions.matklad.rust-analyzer (vscode-extensions.rust-lang.rust-analyzer)</li>    <li>vscode-extensions.mattn.lisp</li>    <li>vscode-extensions.maximedenes.vscoq</li>    <li>vscode-extensions.mechatroner.rainbow-csv</li>    <li>vscode-extensions.mhutchie.git-graph</li>    <li>vscode-extensions.mikestead.dotenv</li>    <li>vscode-extensions.mishkinf.goto-next-previous-member</li>    <li>vscode-extensions.mkhl.direnv</li>    <li>vscode-extensions.ms-azuretools.vscode-docker</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-cs</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-de</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-es</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-fr</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-it</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-ja</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-ko</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-pt-br</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-qps-ploc</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-ru</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-tr</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-zh-hans</li>    <li>vscode-extensions.ms-ceintl.vscode-language-pack-zh-hant</li>    <li>vscode-extensions.ms-dotnettools.csharp</li>    <li>vscode-extensions.ms-kubernetes-tools.vscode-kubernetes-tools</li>    <li>vscode-extensions.ms-pyright.pyright</li>    <li>vscode-extensions.ms-python.python</li>    <li>vscode-extensions.ms-python.vscode-pylance</li>    <li>vscode-extensions.ms-toolsai.jupyter</li>    <li>vscode-extensions.ms-toolsai.jupyter-keymap</li>    <li>vscode-extensions.ms-toolsai.jupyter-renderers</li>    <li>vscode-extensions.ms-toolsai.vscode-jupyter-cell-tags</li>    <li>vscode-extensions.ms-toolsai.vscode-jupyter-slideshow</li>    <li>vscode-extensions.ms-vscode-remote.remote-ssh</li>    <li>vscode-extensions.ms-vscode.PowerShell</li>    <li>vscode-extensions.ms-vscode.anycode</li>    <li>vscode-extensions.ms-vscode.cmake-tools</li>    <li>vscode-extensions.ms-vscode.cpptools</li>    <li>vscode-extensions.ms-vscode.hexeditor</li>    <li>vscode-extensions.ms-vscode.makefile-tools</li>    <li>vscode-extensions.ms-vscode.theme-tomorrowkit</li>    <li>vscode-extensions.ms-vsliveshare.vsliveshare</li>    <li>vscode-extensions.msjsdiag.debugger-for-chrome</li>    <li>vscode-extensions.mskelton.one-dark-theme</li>    <li>vscode-extensions.mvllow.rose-pine</li>    <li>vscode-extensions.naumovs.color-highlight</li>    <li>vscode-extensions.njpwerner.autodocstring</li>    <li>vscode-extensions.ocamllabs.ocaml-platform</li>    <li>vscode-extensions.octref.vetur</li>    <li>vscode-extensions.oderwat.indent-rainbow</li>    <li>vscode-extensions.phoenixframework.phoenix</li>    <li>vscode-extensions.piousdeer.adwaita-theme</li>    <li>vscode-extensions.pkief.material-icon-theme</li>    <li>vscode-extensions.pkief.material-product-icons</li>    <li>vscode-extensions.prisma.prisma</li>    <li>vscode-extensions.rebornix.ruby</li>    <li>vscode-extensions.redhat.java</li>    <li>vscode-extensions.redhat.vscode-xml</li>    <li>vscode-extensions.redhat.vscode-yaml</li>    <li>vscode-extensions.richie5um2.snake-trail</li>    <li>vscode-extensions.rioj7.commandOnAllFiles</li>    <li>vscode-extensions.ritwickdey.liveserver</li>    <li>vscode-extensions.roman.ayu-next</li>    <li>vscode-extensions.rubbersheep.gi</li>    <li>vscode-extensions.rubymaniac.vscode-paste-and-indent</li>    <li>vscode-extensions.ryu1kn.partial-diff</li>    <li>vscode-extensions.sanaajani.taskrunnercode</li>    <li>vscode-extensions.scala-lang.scala</li>    <li>vscode-extensions.scalameta.metals</li>    <li>vscode-extensions.serayuzgur.crates</li>    <li>vscode-extensions.shardulm94.trailing-spaces</li>    <li>vscode-extensions.shd101wyy.markdown-preview-enhanced</li>    <li>vscode-extensions.shyykoserhiy.vscode-spotify</li>    <li>vscode-extensions.silvenon.mdx</li>    <li>vscode-extensions.skellock.just</li>    <li>vscode-extensions.skyapps.fish-vscode</li>    <li>vscode-extensions.slevesque.vscode-multiclip</li>    <li>vscode-extensions.sonarsource.sonarlint-vscode</li>    <li>vscode-extensions.spywhere.guides</li>    <li>vscode-extensions.stefanjarina.vscode-eex-snippets</li>    <li>vscode-extensions.stephlin.vscode-tmux-keybinding</li>    <li>vscode-extensions.stkb.rewrap</li>    <li>vscode-extensions.streetsidesoftware.code-spell-checker</li>    <li>vscode-extensions.sumneko.lua</li>    <li>vscode-extensions.svelte.svelte-vscode</li>    <li>vscode-extensions.svsool.markdown-memo</li>    <li>vscode-extensions.tabnine.tabnine-vscode</li>    <li>vscode-extensions.takayama.vscode-qq</li>    <li>vscode-extensions.tamasfe.even-better-toml</li>    <li>vscode-extensions.theangryepicbanana.language-pascal</li>    <li>vscode-extensions.thenuprojectcontributors.vscode-nushell-lang</li>    <li>vscode-extensions.tiehuis.zig</li>    <li>vscode-extensions.timonwong.shellcheck</li>    <li>vscode-extensions.tobiasalthoff.atom-material-theme</li>    <li>vscode-extensions.tomoki1207.pdf</li>    <li>vscode-extensions.tuttieee.emacs-mcx</li>    <li>vscode-extensions.twxs.cmake</li>    <li>vscode-extensions.tyriar.sort-lines</li>    <li>vscode-extensions.usernamehw.errorlens</li>    <li>vscode-extensions.vadimcn.vscode-lldb</li>    <li>vscode-extensions.valentjn.vscode-ltex</li>    <li>vscode-extensions.viktorqvarfordt.vscode-pitch-black-theme</li>    <li>vscode-extensions.vincaslt.highlight-matching-tag</li>    <li>vscode-extensions.vscjava.vscode-java-debug</li>    <li>vscode-extensions.vscjava.vscode-java-dependency</li>    <li>vscode-extensions.vscjava.vscode-java-test</li>    <li>vscode-extensions.vscjava.vscode-maven</li>    <li>vscode-extensions.vscjava.vscode-spring-initializr</li>    <li>vscode-extensions.vscodevim.vim</li>    <li>vscode-extensions.vspacecode.vspacecode</li>    <li>vscode-extensions.vspacecode.whichkey</li>    <li>vscode-extensions.wholroyd.jinja</li>    <li>vscode-extensions.wingrunr21.vscode-ruby</li>    <li>vscode-extensions.wix.vscode-import-cost</li>    <li>vscode-extensions.xadillax.viml</li>    <li>vscode-extensions.xaver.clang-format</li>    <li>vscode-extensions.xyz.local-history</li>    <li>vscode-extensions.yzhang.markdown-all-in-one</li>    <li>vscode-extensions.zhuangtongfa.material-theme</li>    <li>vscode-extensions.zxh404.vscode-proto3</li>    <li>vscode-fhs</li>    <li>vscode-with-extensions</li>    <li>vscodium</li>    <li>vscodium-fhs</li>  </ul></details>

**Comment by m911t** [comment]
this seems to break the title bar on wayland

**Comment by donferi** [comment]
My vscode loads without extensions in `1.74.1`.

Do I need to change the syntax, I see a comment on the description but I'm not sure if it's related or not. I do something like this on my config:

```nix
{ pkgs, ... }:

with pkgs.vscode-extensions;

[
  asvetliakov.vscode-neovim
  bbenoist.nix
  brettm12345.nixfmt-vscode
  dbaeumer.vscode-eslint
];
```

**Pull request merged**
