### PR TITLE
plasma-workspace: fix patch

### PR DESCRIPTION
**Pull request by nyanloutre**
###### Motivation for this change
Patch wasn't applied entirely because of a line number error in a diff header (see L84)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nyanloutre** [comment]
@GrahamcOfBorg build nixosTests.plasma5

**Comment by nyanloutre** [comment]
I pushed everything needed for the plasma5 test to https://nyanloutre.cachix.org/

**Review by vcunat — APPROVED** [review]
Seems good.  I don't understand why `patch` doesn't error out on this, as various others kinds of errors are caught.

**Comment by nyanloutre** [comment]
@vcunat: `patch` didn't throw an error and failed silently while `git apply` immediately returned an error

**Comment by vcunat** [comment]
Maybe it's worth reporting upstream.

**Comment by dtzWill** [comment]
(sorry for the breakage folks, thanks for the fix! :+1:)

**Pull request merged**
