### PR TITLE
ocamlPackages.lablgtk3: propagate gtk3

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
In this specific to ocaml-top or does it affect all programs built with `lablgtk3`?

**Comment by marsam** [comment]
oh, it affects all dependents of `lablgtk3`. I think we could propagage `gtk3` :
```diff
--- c/pkgs/development/ocaml-modules/lablgtk3/default.nix
+++ i/pkgs/development/ocaml-modules/lablgtk3/default.nix
@@ -12,8 +12,7 @@ buildDunePackage rec {
   };
 
   nativeBuildInputs = [ pkgconfig ];
-  buildInputs = [ gtk3 ];
-  propagatedBuildInputs = [ cairo2 ];
+  propagatedBuildInputs = [ gtk3 cairo2 ];
 
   meta = {
     description = "OCaml interface to GTK 3";
```

**Comment by vbgl** [comment]
This makes sense.

**Comment by marsam** [comment]
I've updated the PR to propagate gtk3.

Also, I noticed `ocamlgraph` places its binaries incorrectly, I'm going to fix it in another PR
```
$ lsd $(nix-build -A ocamlPackages.ocamlgraph)
🗁 l4fpbhclpnh37w96kr2kna631wlw0cyp-ocamlgraph-1.8.8
├── 🗁 lib
│  └── 🗁 ocaml
│     └── 🗁 4.10.0
│        └── 🗁 site-lib
│           └── 🗁 ocamlgraph
│              ├── 🗋 builder.mli
│              ⋮
│              ├── 🗋 xDot.mli
│              └── 🗋 xDotDraw.mli
└── 🗁 nix
   └── 🗁 store
      └── 🗁 l4fpbhclpnh37w96kr2kna631wlw0cyp-ocamlgraph-1.8.8
         └── 🗁 bin
            ├── 🗋 graph-editor
            ├── 🗋 graph-editor.byte
            ├── 🗋 graph-editor.opt
            ├── 🗋 graph-viewer
            ├── 🗋 graph-viewer.byte
            └── 🗋 graph-viewer.opt
```

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocaml-top coq_8_11

**Comment by vbgl** [comment]
BTW, I think I have a patch ready somewhere for ocamlgraph…

**Pull request merged**
