### PR TITLE
nixos/pipewire: Use formats.json, stricter typing and break up extremely long lines.

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change

The upstream pipewire config is written in an almost, but not quite JSON format. The parser accepts standard JSON, though, so we don't need to write our file in the same nonstandard version.

The typing for all config options is changed from `types.attrs`, which behaves poorly when the option is set from multiple locations, to the `formats.json`-type.

Also, rewrite some very long one-liners for improved readability.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jansol — CHANGES_REQUESTED** [review]
This is something I've been wanting to do for a while but pipewire's config parser fails to read JSON generated by Nix. If this is merged right now it'll just break every pipewire installation out there with no way to generate an actually working config.

[This commit](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/34800dc0191a4ee7a329eeb361a6f2ccf4a75176) fixes the parser, but is not part of any release yet.

**Review by jansol — CHANGES_REQUESTED** [review]
The same changes should also be done to the main pipewire module.

**Comment by talyz** [comment]
> This is something I've been wanting to do for a while but pipewire's config parser fails to read JSON generated by Nix. If this is merged right now it'll just break every pipewire installation out there with no way to generate an actually working config.

Ah, I see. I just tried it with a few variations of my own config and it works fine with it. I guess it might be because it's prettified by `jq`, or I was just lucky. In any case, we could just apply the fix as a patch or hold off with this until it's in a release.

> The same changes should also be done to the main pipewire module.

Oh, of course. I didn't even think to check it.. I'll do the same there!

**Comment by talyz** [comment]
@jansol Applied the changes to the main module too and added the patch. As stated earlier, I don't need it for my config to work, and that applies to the main module as well, but better safe than sorry :)

**Comment by jansol** [comment]
Wait, are you replacing the config files with manually edited ones instead of using the module-generated files as is? If the Nix-generated files are run through jq they do indeed work even without the patch, since there is nothing structurally wrong with the files generated by `builtins.toJSON`.

However nix leaves out all whitespace from the generated JSON (since it is not meaningful for the format) and pre-patch pipewire would skip one character after every closing bracket so having no whitespace at all caused it to miss the end of an object if the last element in the object was an array or another object, and parsing the config would fail.

**Comment by talyz** [comment]
No, I'm using what the module generates, but `json.generate` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/pkgs-lib/formats.nix#L40-L46) runs the output of `builtins.toJSON` through `jq` to prettify it.

**Comment by jansol** [comment]
Ooh, okay. I wasn't aware `json.generate` goes that far. Still, it's probably best to keep that patch until the next release, just in case.

**Comment by talyz** [comment]
Agreed. Would you mind if I merged? Is there something left to fix?

**Review by jansol — APPROVED** [review]
I want to test this on my system before giving it the final OK but on the surface this looks good.

**Comment by jansol** [comment]
Appears to work, feel free to merge whenever!

**Pull request merged**
