### PR TITLE
ft2-clone: 1.69 -> 1.71

### PR DESCRIPTION
**Pull request by fgaz**
## Description of changes

Drops the patches that have been integrated upstream

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Don't have access to my Darwin nor my usual Linux system for awhile. I can test on aarch64-linux in afew hours, will see if Darwin OfBorg is happy with it at that point.

**Comment by OPNA2608** [comment]
GitHub on mobile doesn't let me put down a comment at a code like, but maybe move the expression from `mkDerivation rec {` to `mkDerivation (finalAttrs: {` style while you're changing things?

**Comment by fgaz** [comment]
I plan to change it treewide (on the packages I maintain) soon, so I didn't do it in this pr since I'm not touching that line

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 259155` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ft2-clone</li>
  </ul>
</details>

**Review by cafkafk — APPROVED** [review]

**Review by OPNA2608 — APPROVED** [review]
Can't run `nixpkgs-review` on current hardware. Builds & works on aarch64-linux. Darwin CI is also happy, so LGTM. :slightly_smiling_face:

**Comment by JoNilsson** [comment]
This is awesome!

**Comment by fgaz** [comment]
@JoNilsson you might be interested in #81815 :)

**Pull request merged**
