### PR TITLE
Backport Mesa 21.1.x to 21.05

### LINKED ISSUE #123446: Mesa 21.0: VAAPI recording broken
**Describe the bug**

VAAPI records repeated frames (see upstream bug report).

upstream fix: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9995

**To Reproduce**
1. ... open OBS
2. ... try recording using VAAPI (possible AMD hardware required?)
3. ... watch replay

**Expected behavior**
full FPS.

**Notify maintainers**

@primeos @vcunat 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by afrepues**
###### Motivation for this change

Mesa 21.1 brings fixes to Nouveau bugs that [affect Sway](https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-or-a-blank-screen-on-nouveau) (make it unusable in my case).

With Mesa 21.1 Sway works fine in my machine (Lenovo ThinkPad W530 w/Nvidia Quadro K1000M (GK107GLM)).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Sounds OK, at least in principle.  We were even tentatively planning to get mesa 21.1.

This 21.1.4 [has been](https://hydra.nixos.org/job/nixpkgs/trunk/mesa.x86_64-linux) on master for over two weeks.  I hope we haven't missed some significant breakage (e.g. hidden by another master fix).

**Comment by afrepues** [comment]
I am OK with dropping the last commit (21.1.3 -> 21.1.4), let me know.

**Comment by vcunat** [comment]
I'd rather keep it.

@primeos: any opinion on whether to keep mesa on llvm 11 or switch it to 12 with this update?  (_Only_ for mesa, I mean.  On NixPkgs master you switched _latest [a month ago](https://hydra.nixos.org/job/nixpkgs/trunk/llvmPackages_latest.llvm.x86_64-linux).)  Related: #130529.

**Comment by primeos** [comment]
Good question... I'd be fine with it either way but would probably leave it on LLVM 11 for now (e.g. in case we forgot to backport some fixes (cross-compilation, etc.) for LLVM 12 to nixos-stable but it also has a bit of a drawback as we didn't test that combination (mesa+llvm_11) on nixos-unstable).

**Comment by vcunat** [comment]
It probably did get some testing: mesa-21.1.2 with llvm-11.1.0 [was](https://hydra.nixos.org/job/nixpkgs/trunk/mesa.x86_64-linux) on NixPkgs master for about nine days.  I didn't look into channel history, but I'm confident it was there for at least a few days, as we're managing to keep the channels quite fresh these weeks.

**Pull request merged**
