### PR TITLE
RFC: drop nodejs-4_x and packages

### PR DESCRIPTION
**Pull request by gilligan**
###### Motivation for this change

Currently we are still maintaining versions `0.10`, `4_x` and `6_x`. Since October `6_x` is the active LTS release. I see no good reason to keep maintaining 4.x (See [LTS Schedule](https://github.com/nodejs/LTS)). As for `0.10` that might be of use for some legacy projects I suppose.

What are your thoughts on this @svanderburg and @LnL7 ?

I also need some help with this PR. I think `pkgs/development/node-packages/*` needs some work. The `generate` script was still referring to non-existing v5 packages and the v0.10 refers to v4 composition files. The generation for 6.x is missing entirely.

Can you help me out with that @svanderburg ?

### CODE REVIEW

**Comment by NeQuissimus** [comment]
0.10 was removed in #19665 
Are there leftovers?

**Comment by svanderburg** [comment]
Not that I have any personal objections, but my employer still relies on
having Node.js 4.x available.

Perhaps, since Node js 6.x is the new LTS release, we should make this the
default version. I believe atm Node.js 4.x is still the default.

**Comment by gilligan** [comment]
@svanderburg alright - so lets keep 4.x around and set 6.x as default version exposed by `nodejs`. Can you update that generate shell script to generate packages for `6.x` ?

**Comment by gilligan** [comment]
@NeQuissimus ooops- you are absolutely right of course - nodejs 0.10 is gone already. My bad ;)

**Comment by gilligan** [comment]
This will be solved by #19980

**Pull request closed without merging**
