### PR TITLE
input-leap: update to edaa634

### PR DESCRIPTION
**Pull request by vancluever**
## Description of changes

This is just an update of input-leap to the latest master. This includes some notable changes, including a bugfix for clipboard updates and screen switches, see https://github.com/input-leap/input-leap/pull/1640

It also looks like development cadence is picking back up so this might want to be tracked a bit tighter.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vancluever** [comment]
cc @shymega @KoviRobi @phryneas @Twey - just a non-urgent poke for visibility to maintainers. :slightly_smiling_face:

**Comment by shymega** [comment]
I would rather keep this as the last bump. Ideally, we [The Input Leap devs] don't want people to run from Git, and my draft PR will show a warning in the event the binary is built from an untagged Git reference.

In the future, we want to make more regular releases, but for now, I think a bump is OK, but just for one last time...

**Comment by vancluever** [comment]
:+1: yeah makes sense @shymega, just mainly updating after moving my homebrew tap back to upstream after the clipboard bugfix was shipped. If anything else is super needed after this folks can always use an overlay/other override of their choice.

**Comment by Twey** [comment]
It's not unheard of in nixpkgs to have alternative versions for packages under heavy development — one stable and one unstable.  Maybe if we want to allow this level of churn we should package it alongside the more stable version, though I suspect it will create some noise in PRs.

**Comment by shymega** [comment]
> It's not unheard of in nixpkgs to have alternative versions for packages under heavy development — one stable and one unstable. Maybe if we want to allow this level of churn we should package it alongside the more stable version, though I suspect it will create some noise in PRs.

Yeah, I suppose we don't want too much noise, but I'm open to two packages.

**Comment by sersorrel** [comment]
fwiw, input-leap 2023-05-24 currently fails to build on unstable (see https://github.com/input-leap/input-leap/pull/1670):

```
error: builder for '/nix/store/5b7a772g5ndvbn61m2w2nc2rfvqird11-input-leap-unstable-2023-05-24.drv' failed with exit code 2;
       last 20 log lines:
       >       |     ~~~~~^~~~~~~~~~~~~~~~~
       > [ 84%] Linking CXX executable ../../bin/guiunittests
       > /build/source/src/lib/platform/PortalRemoteDesktop.cpp: In member function 'void inputleap::PortalRemoteDesktop::cb_session_started(GObject*, GAsyncResult*)':
       > /build/source/src/lib/platform/PortalRemoteDesktop.cpp:122:36: error: too few arguments to function 'int xdp_session_connect_to_eis(XdpSession*, GError**)'
       >   122 |     fd = xdp_session_connect_to_eis(session);
       >       |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
       > In file included from /nix/store/dfmxwvczf0gvhwz0n49nvi196cp6xw29-libportal-0.7.1-dev/include/libportal/portal.h:35,
       >                  from /build/source/src/./lib/platform/PortalRemoteDesktop.h:26,
       >                  from /build/source/src/lib/platform/PortalRemoteDesktop.cpp:18:
       > /nix/store/dfmxwvczf0gvhwz0n49nvi196cp6xw29-libportal-0.7.1-dev/include/libportal/remote.h:203:11: note: declared here
       >   203 | int       xdp_session_connect_to_eis    (XdpSession  *session,
       >       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~
       > make[2]: *** [src/lib/platform/CMakeFiles/platform.dir/build.make:370: src/lib/platform/CMakeFiles/platform.dir/PortalRemoteDesktop.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > [ 84%] Linking CXX executable ../../bin/input-leap
       > [ 84%] Built target guiunittests
       > make[1]: *** [CMakeFiles/Makefile2:667: src/lib/platform/CMakeFiles/platform.dir/all] Error 2
       > make[1]: *** Waiting for unfinished jobs....
       > [ 84%] Built target input-leap
       > make: *** [Makefile:166: all] Error 2
       For full logs, run 'nix log /nix/store/5b7a772g5ndvbn61m2w2nc2rfvqird11-input-leap-unstable-2023-05-24.drv'.
```

**Comment by shymega** [comment]
Yes, that bug has been fixed now. I'm going to push an update to this PR for the latest commit, then we can look at approving it for merge.

**Comment by shymega** [comment]
When I tried to add a Nix Flake to Input Leap from this derivation, I encountered numerous compile bugs. I'm unsure why it works on Nixpkgs, but not on Input Leap. I've also been thinking, Input Leap does support x86_64-darwin, so should we address that in later PRs?

**Comment by vancluever** [comment]
> EDIT: Thought I could, but I can't. I've been added to Nixpkgs though... @vancluever have you allowed maintainer edits? My changes were a rebase against `master`, and bumping the commit.

I wonder if it was due to the rebase (GH might not like it when you force-push against other forks). I just made the updates over here and tested the build, looks good!

**Comment by shymega** [comment]
> > EDIT: Thought I could, but I can't. I've been added to Nixpkgs though... @vancluever have you allowed maintainer edits? My changes were a rebase against `master`, and bumping the commit.
> 
> I wonder if it was due to the rebase (GH might not like it when you force-push against other forks). I just made the updates over here and tested the build, looks good!

Shouldn't be. I can force-push to PRs on Input Leap, I think it's just this PR. GitHub shouldn't care. 

I can't build it locally yet, `libei` is an issue. There's also been a 0.2.0 release of `libei` recently.

**Comment by vancluever** [comment]
> EDIT: I'm not a _committer_, that's the issue. I'm a maintainer, but I haven't got commit/push access. That'll be it.

Gotcha! Yeah wasn't too sure how it works on forks.

Happy to keep the PR up to date or pass it over, whatever's easier! Interestingly enough it _does_ build on this side fully. Any logs of what you're seeing?

**Comment by shymega** [comment]
> > EDIT: I'm not a _committer_, that's the issue. I'm a maintainer, but I haven't got commit/push access. That'll be it.
> 
> Gotcha! Yeah wasn't too sure how it works on forks.
> 
> Happy to keep the PR up to date or pass it over, whatever's easier! Interestingly enough it _does_ build on this side fully. Any logs of what you're seeing?

Yeah, that's the issue - push access.

I tried using the `libsForQt5` function with `.callPackage` - I'll try again later when I pull the latest rebase, but what commands are you using to build? I copied the current committed derivation to Input Leap locally for a Flake, but I had to make several changes, including for Avahi.

**Comment by vancluever** [comment]
> what commands are you using to build?

Literally just `nix build .#input-leap` from the nixpkgs repo. That should do everything needed to build.

Building on `x86_64-linux` currently.

**Comment by shymega** [comment]
OK, it works now. I realised what I was doing wrong. I think we should look into targeting `x86_64-darwin` soon - then maybe long-term, `aarch64-*` targeting once Input Leap is ready.

**Comment by shymega** [comment]
I think we should move our discussions over to #277183, as that PR now takes into account the XDG Desktop File change in the repository.

Voting to close this issue in favour of #277183.

**Comment by vancluever** [comment]
@shymega sounds good. I'll close this one and let yall take the lead!

**Pull request closed without merging**
