### PR TITLE
maintainers: remove andrew-d as a maintainer

### PR DESCRIPTION
**Pull request by andrew-d**
I am deeply saddened at the fact that I need to do this. I have no interest in re-litigating everything that has happened over the past weeks and months, but I want to make my position(s) extremely clear:

The thought of any of my work contributing to someone's death by drone makes me feel physically ill.

Recent communications from senior members of the NixOS community have made it clear that leadership is unaware or uninterested in the basics of how to run and moderate a community in a way that is resilient to bad actors. The recent post by @edolstra is oblivious, and gives me no confidence that the Nix/NixOS community is a place that I want to remain involved in going forward. I am thus choosing to remove myself from such a community.

I also hereby resign from the ACME team.

See also: #307033

### CODE REVIEW

**Review by ryantm — APPROVED** [review]

**Comment by hraban** [comment]
Thank you Andrew and good luck :)

**Comment by vcunat** [comment]
> The thought of any of my work contributing to someone's death by drone makes me feel physically ill.

I'm afraid that with open-source it's fundamentally impossible to control who uses it and for what purposes, especially with such versatile tools like Nix*.  (sure, that property does have down-sides)

_I don't mean to troll.  I'm sad from everything.  Either way, if people don't feel like contributing... there's no need for any kind of argumentation.  But I still couldn't help myself and commented._

**Comment by SuperSandro2000** [comment]
I thought the same immediately but didn't want to say anything out of fear of more straining discussions. 

The fundamental core of free and open source software is, that you can't control who uses it or not. Licenses which try to control who uses a software, are not considered free.

**Comment by andrew-d** [comment]
@vcunat and @SuperSandro2000 - you are both of course correct, and I take no offense. I would not advocate for preventing people from using open-source software via changing licenses, but in my personal opinion, there is a marked difference between the general case ("all governments run Linux on their servers") and the specific.

I don't pretend to be perfect, nor do I expect anyone else to agree with my particular line(s) in the sand, but combined with the broader governance and community management issues (which I will not reiterate or re-litigate), this was the correct choice for me.

**Pull request merged**
