### PR TITLE
modemmanager: 1.18.6 -> 1.18.10

### PR DESCRIPTION
**Pull request by amaxine**
###### Description of changes
https://lists.freedesktop.org/archives/modemmanager-devel/2022-April/009249.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Hmm, what does this mean for us:

>   * A new connection status dispatcher setup is provided, where users can provide custom scripts that will be called on bearer connect/disconnect events. This dispatcher will make the netifd integration in openwrt work much better, as we'll be able to report network-initiated disconnections cleanly to netifd.
> 
>     There are no default connection status dispatcher scripts installed, but it's suggested distributions make sure the following directories exist:
>       - ${sysconfdir}/ModemManager/connection.d/
>       - ${libdir}/ModemManager/connection.d/

**Comment by maxeaubrey** [comment]
I somehow blanked on that when reading the changelog. As I understand, if we don't expose it it's just a feature no one can use - not replacing any existing functionality.

I suppose what we need to do here is give users a way to provide scripts via the module.

**Comment by jtojnar** [comment]
Looks like it is a no-op when the directory does not exist:

https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/blob/a8b9058a0c00dcaf6bde5fc7032e7f59169dd914/src/mm-dispatcher-connection.c#L205-206

**Comment by jtojnar** [comment]
I took the liberty of rebasing and further updating in hope it fixes https://github.com/NixOS/nixpkgs/pull/182618 but the test_ccwa_response still fails.

**Comment by jtojnar** [comment]
Confirmed that cherry-picking the glib 2.72.3 → 2.73.2 update breaks the tests on this branch.

**Pull request merged**
