### PR TITLE
processing3: init at 3.3.7

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

New version of Processing.
Better to say "new branch" - it is not compatible with ```Processing 2```
Kind of ```Python 2``` vs. ```Python 3```

### CODE REVIEW

**Comment by disassembler** [comment]
@GrahamcOfBorg eval

**Comment by volth** [comment]
@disassembler, this won;t eval, it requires ```allowUnfree=true```. It is just for human feedback.

**Comment by volth** [comment]
@roosemberth Please test this. It works for me on ```Plasma5``` (the default NixOS desktop), the startup problem happens only with ```XFCE``` so it might be irrelevant to ```Processing```

**Comment by roosemberth** [comment]
works for me (Xmonad)

**Comment by volth** [comment]
let's merge?

**Comment by volth** [comment]
@Mic92

**Pull request merged**
