### PR TITLE
lib.sources: docs, tests, refactoring

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

 - Start documenting `lib.sources` in the manual
 - Improve maintainability with tests
 - Add `sources.trace` for debugging
 - Refactor `cleanSourceWith` to support `trace` and future functions like #112083 

Perhaps unlike that pr, these changes should be uncontroversial and can hopefully be merged soon, to deliver some of its benefits and to simplify that pr.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
Rendered:

Screenshot from 2021-05-29 16-10-17

**Comment by NorfairKing** [comment]
Haven't been able to confirm this yet, but it looks like this breaks a workflow in which the `src` is a nonexistent path.

**Comment by roberth** [comment]
> Haven't been able to confirm this yet, but it looks like this breaks a workflow in which the `src` is a nonexistent path.

Some _spacebar heating_ vibes here. How did it work and what did you use it for?

I don't think I can reproduce it using primitives in the Nix 2.4 repl, but maybe I'm overlooking something.

```console
nix-repl> builtins.filterSource (_: _: false) ./this-does-not-exist    
error (ignored): error: bad archive: input doesn't look like a Nix archive
error: getting status of '/home/user/h/nixpkgs/this-does-not-exist': No such file or directory

nix-repl> builtins.path { path = ./this-does-not-exist; filter = _: _: false; }
error (ignored): error: bad archive: input doesn't look like a Nix archive
error: getting status of '/home/user/h/nixpkgs/this-does-not-exist': No such file or directory

```

**Comment by NorfairKing** [comment]
@roberth 

> Some spacebar heating vibes here.

Yes I thought the same when I found it :D

I also wasn't able to reproduce with a repl, so I'll stop commenting about it here and work around the issue.

**Comment by NorfairKing** [comment]
In case anyone else runs into this: you can work around this issue by using `pkgs.emptyDirectory` instead of a nonexistent directory.

**Pull request merged**
