### PR TITLE
elixir_1_11: init at 1.11.0

### PR DESCRIPTION
**Pull request by mtanzi**
###### Motivation for this change

Set elixir_1_11 as default elixir version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cw789** [comment]
Hi @mtanzi. Cool thanks.

In 1.11.nix `minimumOTPVersion` could still be "21".
→ https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

**Comment by mtanzi** [comment]
> Hi @mtanzi. Cool thanks.
> 
> In 1.11.nix `minimumOTPVersion` could still be "21".
> → https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

Thanks @cw789, well spotted! I will fix that 👍

**Comment by cw789** [comment]
Tested via `nixpkgs-review pr 99883`.
```
2 packages built:
elixir elixir_1_10
```

Execution of `elixir --version` is fine.
```
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.0 (compiled with Erlang/OTP 22)
```

**Comment by fritzblue** [comment]
@mtanzi @cw789 Where did this land? :smile:

**Comment by mtanzi** [comment]
@fritzblue I am hoping someone is going to merge it soon 😅 🤞

**Comment by cw789** [comment]
Hey @havvy @couchemar @ankhers @filalex77.
Is anyone available for review to speedup getting this PR merged?

**Review by ankhers — APPROVED** [review]
Looks good.

**Comment by afontaine** [comment]
Result of `nixpkgs-review pr 99883` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>elixir (elixir_1_11)</li>
  </ul>
</details>

**Comment by ajs124** [comment]
@r-ryantm just openend #99883, which is probably a duplicate of this. Although it upgrades to 1.11.1 instead of 1.11.0, so that might be something you might also want to do here.

**Comment by mtanzi** [comment]
@ajs124 I've updated the PR with the latest elixir (v1.11.1) 👍

**Comment by cw789** [comment]
`nixpkgs-review pr 99883` → build elixir (elixir_1_11) ✔

```
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 22)
```

**Pull request merged**
