### PR TITLE
heroic: init at 1.10.3

### PR DESCRIPTION
**Pull request by WolfangAukang**
###### Motivation for this change

#131620. Only thing that I have no idea on how to solve is `[2:1203/105250.437442:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Did you try building Heroic from source first? Building from source is always preferred in nixpkgs.

**Comment by WolfangAukang** [comment]
> Did you try building Heroic from source first? Building from source is always preferred in nixpkgs.

Yes, already did, but never could do it. If someone can build it from source, specially being a JS project, then I could close this and favor the other one.

**Comment by SuperSamus** [comment]
#109733 can also be closed.

**Comment by pmarreck** [comment]
I installed Heroic, installed a game "Plague Tale: Innocence" to test it, on running the game with proton 7.0 the game failed to launch, I saw 2 errors in the logs, "***stack smashing detected***" and it also couldn't find python3.

I guess my question is not so much that, since I can run it elsewhere, but as a 1-month-in-or-so Nix noob, do you guys use any test suites to verify that things continue to work? (I'm guessing a test for something GUI-driven like Heroic might be difficult but not impossible, but I'm also wondering if the commandline `legendary` underneath is ever tested, or if anything in general ever is, or if "successful build with exit 0" is considered the only necessary "test"...)

**Pull request merged**
