### PR TITLE
firefox: update

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
Upstream releases.

Contains #91746.

`firefox-esr-68` doesn't build. Looks like it's incompatible with the new `nss/nspr`.
The other 3 packages seem to build and work fine.

cc @andir

### CODE REVIEW

**Comment by vcunat** [comment]
Again, most of this didn't need to wait for mass rebuilds, so I picked them to master and 20.03 (with like a minute of using for each combination).

**Comment by ajs124** [comment]
Yeah, the only thing that needs the mass rebuild is the 77 -> 78 bump. Another problem is that esr-68 doesn't seem to compile with the nss 3.54.

**Comment by vcunat** [comment]
Ah, right, we'll still have to do something about that problem.

**Comment by jtojnar** [comment]
Is that also an issue with .10esr?

**Comment by vcunat** [comment]
Yes, I did test with that one.

**Comment by pstn** [comment]
Please mark this as a security upgrade. The list for firefox [is not short](https://www.mozilla.org/en-US/security/advisories/mfsa2020-24/)

**Pull request closed without merging**
