### PR TITLE
KDE Plasma 5.4, Frameworks 5.15, and Applications 15.08

### PR DESCRIPTION
**Pull request by ttuegel**
This pull request updates all our KDE 5 packages to the latest available versions. It is the culmination of my work re-packaging KDE 5 and Qt 5.5. The major changes are as follows:
- Plasma 5.3.2 -> 5.4.2
- Frameworks 5.10 -> 5.15
- Applications 15.04.3 -> 15.08.2
- KDE and Qt package expressions conform to the conventions used throughout Nixpkgs. I believe this will open these expressions up to new contributors.
- KDE 5 and Qt 5.5 applications are wrapped so that they work correctly outside the KDE desktop. Any such application that does not work should be considered a bug and warrants a GitHub Issue.

KDE and Qt applications now use wrappers _very_ extensively. To forestall controversy on this change, let me point out that introducing the wrappers fixed unrelated bugs in several packages that I had long-ago given up on fixing. In other words, there is clear empirical evidence that these wrappers are a significant improvement.

So much for the good news, on to the bad. I have intentionally left a large number of KDE Applications packages un-packaged. There are too many for me to be the sole maintainer. I will continue to maintain the ones I consider "essential" for a working desktop, including the localization packages, and I will continue to maintain the ones I use. There are 248 packages in KDE Applications, I simply cannot test them all. It would be dishonest for me to list myself as the maintainer, and it would be a waste of my time to package programs that aren't going to be maintained. The silver lining is, many of the KDE Applications are re-released KDE 4 applications, so we won't really lose that many packages. I hope other developers will step in to fill the void, now that I have simplified the KDE packaging process. I plan to continue maintaining the other 178 KDE packages.

I will leave this PR open to collect comments and suggestions.

### CODE REVIEW

**Comment by copumpkin** [comment]
Oh man, look at all that delicious deleted code. :+1: for that alone, but I don't know anything about KDE so I'll shut up now.

**Comment by bjornfor** [comment]
@ttuegel: I don't run KDE 5, but I appreciate the work that went into this. I also look forward to the qt5 improvements you have here :-)

**Comment by joelmo** [comment]
Thank you, looking forward to try it! :)

**Comment by domenkozar** [comment]
`error: attribute ‘license’ missing, at /home/travis/build/NixOS/nixpkgs/pkgs/applications/kde-apps-15.08/oxygen-icons.nix:10:15`

**Comment by ttuegel** [comment]
@domenkozar Thanks! I got bit by the `license` vs. `licenses` thing.

**Comment by vcunat** [comment]
KDE5 stuff hasn't yet been called stable by us, so merging this to master without larger testing seems fine to me.

I'm really looking forward to installing standalone KDE apps, after all those years installing whole KDE5 without really using it.

**Comment by ttuegel** [comment]
I haven't received any serious complaints--or indeed any complaints at all--so I will proceed with merging this.

**Pull request merged**
