### PR TITLE
buildkite-agent: 2.6.6 -> 2.6.9

### PR DESCRIPTION
**Pull request by rvl**
###### Motivation for this change

Various upstream bug fixes.

https://github.com/buildkite/agent/releases/tag/v2.6.7
https://github.com/buildkite/agent/releases/tag/v2.6.8
https://github.com/buildkite/agent/releases/tag/v2.6.9

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
@GrahamcOfBorg build buildkite-agent

**Comment by domenkozar** [comment]
cc @rvl

**Comment by rvl** [comment]
On my machine:
```
checking for references to /tmp/nix-build-buildkite-agent-2.6.9.drv-0 in /nix/store/9pzysxn3jzrqj8gnjbrbvh3v6i2m79jk-buildkite-agent-2.6.9...
```

I think it might be finding `/build` due to the name of this package.

**Comment by zimbatm** [comment]
@GrahamcOfBorg build buildkite-agent

**Pull request merged**
