### PR TITLE
bear: 2.4.2 -> 3.0.1

### PR DESCRIPTION
**Pull request by Atemu**
Bear has been completely redone, this is basically a new package

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
CMake Error at /nix/store/d92w6yzgr7zcy69h1askyzpq988w39f1-cmake-3.18.2/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/nix/store/ppfvi0cfcpdr83klw5kx6si2l260n1gh-gcc-wrapper-9.3.0/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /build/source/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/nix/store/8b1waa7x32dgdd66dfkgj0aiw1ny6yay-gnumake-4.3/bin/make cmTC_31b31/fast && /nix/store/8b1waa7x32dgdd66dfkgj0aiw1ny6yay-gnumake-4.3/bin/make  -f CMakeFiles/cmTC_31b31.dir/build.make CMakeFiles/cmTC_31b31.dir/build
    make[1]: Entering directory '/build/source/build/CMakeFiles/CMakeTmp'
    make[1]: /bin/sh: No such file or directory
    make[1]: *** [CMakeFiles/cmTC_31b31.dir/build.make:84: CMakeFiles/cmTC_31b31.dir/testCCompiler.c.o] Error 127
    make[1]: Leaving directory '/build/source/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_31b31/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
See also "/build/source/build/CMakeFiles/CMakeError.log".
```

**Comment by doronbehar** [comment]
It should be supported on Darwin: https://formulae.brew.sh/formula/bear

**Comment by Atemu** [comment]
@SuperSandro2000 Where are you building this? Is your Sandbox on? It builds fine for me on NixOS. 

@doronbehar Oh, didn't catch that platforms = unix. Brew has the older v2.4.4 though which is still python-based. Maybe we should keep that around for Darwin users as the linker is failing to find some symbols for v3 on Darwin.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Where are you building this? Is your Sandbox on? It builds fine for me on NixOS.

Nix on Debian. /bin/sh is a symlink to /bin/dash which could cause those failures. I also don't have sandbox enabled anymore.

darwin:
```
Undefined symbols for architecture x86_64:
  "std::__1::__fs::filesystem::path::__compare(std::__1::basic_string_view<char, std::__1::char_traits<char> >) const", referenced from:
      report::operator==(report::Command const&, report::Command const&) in Report.cc.o
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [libreport/CMakeFiles/report_unit_test.dir/build.make:109: libreport/report_unit_test] Error 1
make[4]: *** [CMakeFiles/Makefile2:1385: libreport/CMakeFiles/report_unit_test.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 36%] Built target sys_a
[ 36%] Built target rpc_a
make[3]: *** [Makefile:160: all] Error 2
make[2]: *** [CMakeFiles/BearSource.dir/build.make:133: subprojects/Stamp/BearSource/BearSource-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:250: CMakeFiles/BearSource.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

**Comment by danieldk** [comment]
> Nix on Debian. /bin/sh is a symlink to /bin/dash which could cause those failures. I also don't have sandbox enabled anymore.

Your nixpkgs-review outputs across various PRs are very useful :+1: , but they should definitely be done with sandboxing enabled. Otherwise you can get strange errors like this. Also without sandboxing, the build can also succeed even if the derivation is incorrect. E.g. the derivation could be missing dependencies, but they work fine without sandboxing, because system libraries are picked up.

**Review by doronbehar — APPROVED** [review]

**Pull request merged**
