### PR TITLE
added dependency to systemd

### PR DESCRIPTION
**Pull request by Mikilio**
###### Description of changes

Fix for issue #39140

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chkno** [comment]
This bakes the path to systemd into nixos-enter at nixos-enter's build time.  I'm worried that the path to system might change between nixos-enter's build time and its run time -- for example, if the user updates channels in the install environment.

Instead of changing PATH and finding systemd-tmpfiles with a PATH lookp, consider specifying the full path to systemd-tmpfiles as $system/sw/bin/systemd-tmpfiles .  This follows the convention used elsewhere in nixos-enter, which includes the ability to set $system via the --system flag.

Also, it would be great to have a test that could have caught this.  I appear to have somehow neglected to submit the tests linked in https://github.com/NixOS/nixpkgs/issues/39140#issuecomment-589905207 (oops!), but they would not have caught this problem because the nixos-installer has a systemd-tmpfiles in its PATH.  It's the users trying to install from environments like Kimsufi's rescue environment that don't have systemd stuff in PATH that were exposed to this error.  But setting up a new installer test from a wierd but realistic environment is ~1000x more work than just making this fix, so don't let that block merge of this PR.

Thanks for fixing this!

**Comment by Mikilio** [comment]
This is my first pull request to this repo, so I'm sorry if I'm not familiar with common practices here:
Do you want me to revert my changes and substitute `systemd-tmpfiles` with a full path instead? Or has this already been done?

**Comment by chkno** [comment]
Fantastic!  Welcome!

Concretely, I mean that [this change](https://github.com/chkno/nixpkgs/commit/3ca48bf6953a834c0dddd38ab706528c7c3a21c4) would be a better way to fix this problem than the changes this PR is currently proposing.

Mechanically, I meant to suggest that you change this PR to propose that change instead, by force-pushing https://github.com/Mikilio/nixpkgs to be a single commit that makes that change.  One way to do that would be to `git reset --hard HEAD^`, make that change, commit, and force-push.

Alternatively, if you prefer, I could propose that change as a new PR.

(I introduced this bug in https://github.com/NixOS/nixpkgs/pull/80769 .  Thank you for identifying the problem and helping get it fixed.)

**Comment by Mikilio** [comment]
Ok! Since I agree with your points I'll change my PR. Thanks for the advice!

**Comment by chkno** [comment]
Great!

Next, among other things, that "Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md)." checkbox in the PR template is meant to encourage good, uniform commit messages.  So please skim that, look at the commit messages of [some other commits in that place](https://github.com/NixOS/nixpkgs/commits/master/nixos/modules/installer/tools), change your commit message to follow those conventions (concretely: such as with `git commit --amend`), and force push again.

And thanks for bearing with the get-to-know-the-project-conventions first-PR back-and-forth.  :)

**Comment by Mikilio** [comment]
Thank you for the guidance!

**Review by chkno — APPROVED** [review]

**Review by ncfavier — APPROVED** [review]
This change looks good so I'm going to merge now, but I'm curious why the chosen route was to make nixos-enter create its own `/tmp`, instead of simply fixing TMPDIR in nixos-install? By that point we've [already created](https://github.com/NixOS/nixpkgs/blob/7e159b1a6745f4d00f77aed23f007e134b0e9fb8/nixos/modules/installer/tools/nixos-install.sh#L138) a temporary directory under the mountpoint, so `TMPDIR=${TMPDIR#"$mountPoint"} nixos-enter ...` should suffice?

Calling `systemd-tmpfiles` in the nixos-enter environment also has the annoying side-effect that it prints a bunch of red warnings like
```
/etc/tmpfiles.d/systemd.conf:23: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory
```
because `/etc/machine-id` does not exist in the mounted root.

EDIT: I see now that creating `/tmp` in nixos-enter is needed for nix-build to work.

**Pull request merged**
