### PR TITLE
nushell: as login shell via module

### PR DESCRIPTION
**Pull request by cafkafk**
## Description of changes
Pls ignore for now

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Nyabinary** [comment]
Is this stale? @cafkafk

**Comment by cafkafk** [comment]
> Is this stale? @cafkafk

Lowkey yea, I mean, this is enough to have nu as a login shell IIRC, but I was planning to add nushell completion support but just got very very busy with other stuff.

If you just need this for login I can mark it as ready for review.

**Comment by Nyabinary** [comment]
> > Is this stale? @cafkafk
> 
> Lowkey yea, I mean, this is enough to have nu as a login shell IIRC, but I was planning to add nushell completion support but just got very very busy with other stuff.
> 
> If you just need this for login I can mark it as ready for review.

Yea you can make the other pr later :3

**Comment by Nyabinary** [comment]
This wouldn't work correctly as is according to K900, since it ignores stuff like environment.variables, it needs a full on module.

**Comment by Abdillah** [comment]
For loading env vars (sourcing bash's), I uses this plugin https://github.com/tesujimath/nu_plugin_bash_env.

**Comment by gabevenberg** [comment]
what could work would be to launch bash/another POSIX shell and immediately `exec` into nu?

**Comment by cafkafk** [comment]
I'm not gonna work on this for the foreseeable future, so I'll close this for now.

**Pull request closed without merging**
