### PR TITLE
evince: enable all features

### PR DESCRIPTION
**Pull request by gebner**
###### Motivation for this change

I could no longer open postscript files in evince.  While I was at it, I also enabled all other formats (DVI, XPS, PDF multimedia) as well as the nautilus extension.  (The only features not enabled now are the browser plugin, the API docs, and the thumbnail cache.)

There is a *slight* increase in closure size (probably due to the gstreamer/nautilus dependency):
```
 nix path-info -shS result/ (which evince)   Mon 25 Mar 2019 03:35:30 PM CET
/nix/store/kd01ji4sb5pgnrjs3lzvgi3c279f1mjd-evince-3.30.2         11.2M  954.3M
/nix/store/rcy2ii19gx1mkqxzvr20jkj2jdzp83n1-evince-3.30.2         11.0M  420.4M
```

Many of these dependencies are probably already in the system closure (e.g. nautilus depends on gstreamer as well).  We could add an `evinceLight` version that disables some/most features.

cc @jtojnar @vcunat

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gebner** [comment]
The postscript fix needs to be backported to the release branch as well.

**Review by worldofpeace — COMMENTED** [review]
We've began work on getting [gnome 3.32](https://github.com/NixOS/nixpkgs/pull/57027/commits/8184c316fe8b6240b61d5832f336ad0a35f67e41) so this will conflict with that.

I don't see too much of a problem with this aside from enabling the nautilus plugin by default.
(nautilus isn't present everywhere this is used)

I'd also like to enable meson for this (that'll change all the flags).

**Comment by worldofpeace** [comment]
> The postscript fix needs to be backported to the release branch as well.

Does that mean you want this change for 19.03 directly?

You should probably make this pr against 19.03 then, as my comment above won't be a problem.

**Comment by gebner** [comment]
> > The postscript fix needs to be backported to the release branch as well.
> Does that mean you want this change for 19.03 directly?
> You should probably make this pr against 19.03 then, as my comment above won't be a problem.

Postscript support used to work in 18.09; so I'd like to see this regression fixed soon and also for the 19.03 release.

I could make one PR just for the postscript fix for master/19.03, and then make the other changes against the 3.32 branch (including meson migration if you want).  @worldofpeace Does that work for you?

**Comment by gebner** [comment]
> I don't see too much of a problem with this aside from enabling the nautilus plugin by default.  (nautilus isn't present everywhere this is used)

Evince should work just fine even if you don't use nautilus.  The flag just builds an extension for nautilus, which shows additional file properties.

Are you concerned about the increase in closure size?  I don't really need the extension, but it is an easy addition which is hard to build otherwise.

**Comment by jtojnar** [comment]
Can we wait with this until GNOME 3.32 is merged? The expression was
massively rewritten.

Moreover, we do not actually want Evince to depend on Nautilus, we would
need to move the module to a separate output as Deja Dup does, I think.

**Comment by worldofpeace** [comment]
My actual problem with the extension can be seen at https://github.com/NixOS/nixpkgs/issues/32817.
We're yet to implement that, which is why I think it was disabled.

Though I think we should be fine to fix this just for 19.03

**Comment by worldofpeace** [comment]
:smile: Looks like we responded at the same time.

**Comment by gebner** [comment]
Ok, I pushed just the postscript bugfix to 19.03 and master now.  I'll make a new PR against gnome-3.32 that enables the other backends but keeps the nautilus extension disabled for now.

**Pull request closed without merging**
