### PR TITLE
nixos/nginx: filter more options when listening has quic

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

Those options can also only be set once.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Izorkin** [comment]
This block is only used for unsupported options:
 - ssl
 - http2
 - proxy_protocol
Information from source code:
http://hg.nginx.org/nginx/file/tip/src/http/ngx_http_core_module.c#l4308

**Comment by Izorkin** [comment]
Maybe then ask the developers? - nginx@nginx.org or https://trac.nginx.org/nginx/
Can you give a minimal test example to check?

**Comment by SuperSandro2000** [comment]
> Can you give a minimal test example to check?

Basically my server blocks start like this:

```
        server {
                listen 0.0.0.0:443 quic default_server reuseport ;
                listen 0.0.0.0:443 ssl default_server reuseport backlog=1024 deferred fastopen=256;
                listen [::]:443 quic default_server reuseport ;
                listen [::]:443 ssl default_server reuseport backlog=1024 deferred fastopen=256;
```

Without this patch the quic line would also have backlog and deferred which doesn't work and breaks nginx from properly working.

I have those options because of https://github.com/SuperSandro2000/nixos-modules/blob/master/modules/nginx.nix#L130-L156

I don't plan to contact upstream about this since this is a problem in our templating.

**Comment by Izorkin** [comment]
Reproduced error with parameters `fastopen=1024` `deferred`:
```
  [alert] 2360#2360: setsockopt(TCP_FASTOPEN, 1024) 192.168.252.221:443 failed, ignored (92: Protocol not available)
  [alert] 2360#2360: setsockopt(TCP_DEFER_ACCEPT, 1) for 192.168.252.221:443 failed, ignored (92: Protocol not available)
```
Here can immediately see that they are used only in the TCP protocol.
An error in nginx using the `backlog=1024` parameter could not be reproduced. Maybe this works with QUIC?

**Comment by SuperSandro2000** [comment]
> An error in nginx using the `backlog=1024` parameter could not be reproduced. Maybe this works with QUIC?

I'v just tested this again and you are right. backlog works.

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
Got a response from the developers. They will be adding a patch to Nginx shortly.
```
# HG changeset patch
# User Sergey Kandaurov <pluknet@nginx.com>
# Date 1703084664 -14400
#      Wed Dec 20 19:04:24 2023 +0400
# Node ID 5bbdc197980929a82e70c9accfe3f3d3692e6071
# Parent  a35f1bd4ffb651b28ef47b9b14779753071140a4
HTTP/3: added more compatibility checks for "listen ... quic".

Now "fastopen", "backlog", "accept_filter", "deferred", and "so_keepalive"
parameters are not allowed with "quic" in the "listen" directive.
```

**Comment by Izorkin** [comment]
hmm, it doesn’t seem to work, with this variant the error does not occur:
```
      listen = [
        { addr = "0.0.0.0"; port = 443; extraParameters = [ "deferred" "quic" "ssl" ]; }
      ];
```

**Comment by SuperSandro2000** [comment]
Those options are filtered out. If you take a look in the nginx config, you should end up just with quic.

```
nix-repl> inCompatibleParameters = [ "accept_filter" "backlog" "deferred" "fastopen" "http2" "proxy_protocol" "so_keepalive" "ssl" ]
nix-repl> isCompatibleParameter = param: !(lib.any (p: lib.hasPrefix p param) inCompatibleParameters)
lib.filter isCompatibleParameter [ "deferred" "quic" "ssl" ]
[ "quic" ]
```

**Comment by Izorkin** [comment]
It’s strange, but in my example the result is like this:
```
  server {
    listen 0.0.0.0:443 deferred quic ssl;
    server_name peertube.local ;
    http3 on;
    http3_hq on;
```

**Comment by SuperSandro2000** [comment]
You need to use the services.nginx.virtualHosts.<name>.quic option, otherwise it won't work.

**Comment by Izorkin** [comment]
Yes, i have quic enabled.
Do you have a test case? Maybe i configured wrong.

**Comment by SuperSandro2000** [comment]
> Do you have a test case? Maybe i configured wrong.

Not easily :/

but I I am getting the following:
```
                listen 0.0.0.0:443 quic default_server reuseport ;
                listen 0.0.0.0:443 ssl default_server reuseport backlog=1024 deferred fastopen=256;
                listen [::]:443 quic default_server reuseport ;
                listen [::]:443 ssl default_server reuseport backlog=1024 deferred fastopen=256;
                server_name _ ;
                http2 on;
                http3 on;
                http3_hq off;
```

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
Ok.

**Comment by SuperSandro2000** [comment]
I am setting it via this module https://github.com/SuperSandro2000/nixos-modules/blob/master/modules/nginx.nix#L148

Maybe that helps you figure out why it isn't working for you.

**Review by RaitoBezarius — APPROVED** [review]

**Pull request merged**
