### PR TITLE
nixos/test-driver: Add Junit XML report creation

### PR DESCRIPTION
**Pull request by hertrste**
## Description of changes

This MR adds the possibility to generate Junit XML reports when running NixOS integration tests. Reports can be generated by adding `--junit-xml=<outfile>` to the NixOS test driver invocation. These reports can be evaluated by various tools e.g. gitlab and could help identify failing tests easier and get the corresponding log output of the failing test faster.

## Things done

The logging facilities of the NixOS test driver are refactored. There is an AbstractLogger interface and the existing logger is split into terminal and XML logging. A CompositeLogger allows the composition of multiple loggers. This allows restoring the old logging behavior of logging to the terminal and XML simultaneously. It was taken care that the existing logging is not changed at all, in order to not break anything for users relying on the format of the existing logging output.

Further, a JunitXML logger is added which can be activated via arguments to the test driver invocation. The new logger allows the creation of JunitXML reports listing success or failure of the subtests of the integration test. This allows for quick evaluation which subtest has failed.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tfc** [comment]
When we emailed about this topic, i suggested an implementation that follows the composite pattern. I apologize if we had a misunderstanding as this could be the result of me expressing myself clumsily, but the code in this PR does not really reflect the discussion from my perspective.

The concrete steps to follow the pattern, that is best to extend in the future, would be:

1. Create an abstract logger class
2. Implement the original logger in terms of this interface
3. Create an XML logger in terms of this interface
4. Create a composite logger in terms of this interface. This logger would simply keep a list of loggers and forward everything it gets to those
5. The test driver composes random combinations of loggers inside the composite logger, led by command line parameters

This has the following advantages:

- The logger class does not even have to know what XML is
- Because of this, the test driver would not need to include xml libs by default and additional supported loggers can be defined *after* the original logger implementation, as well as in different files/projects
  - Including XML alone does not hurt. Right now. But with these code changes we open the door towards more different logger implementations, and I'd like to make this easy to extend for other users who have different logging requirements.
- We can have a future where companies who use the test driver, implement their private logger implementations at home and simply inject them without the upstream implementation knowing about it.

Please also note that there are good and configurable/composable production logging frameworks in Python that already implement this logic. We might be duplicating this work with this effort, so we should have a little bit of analysis what existing library should be reused for this.

**Comment by hertrste** [comment]
I have refactored the logging facilities to simply allow new loggers and composing them. I have also separated the concerns of logging to the terminal and the old XML creation.

I would argue against using external logging libraries because of our special requirements regarding the subtest and nested calls. Further, I want to avoid changing the existing log output as people may rely on it.

Please have another look.

**Comment by tfc** [comment]
This is a great improvement. I'd love to see one last change: 

`AbstractLogger` that is subclassed by `TerminalLogger`, `XMLLogger`, and `JUnitXMLLogger`, does not have to have the same interface as `CompositeLogger`. If `AbstractLogger` implementations keep implementing the *bare minimum* of functionality (e.g. only `nested` but not `subtest`), we can enrich the CompositeLogger with all the extra non-atomic functionality and end up with less duplicate logic.

Can you please do that?

**Comment by tfc** [comment]
Whoa i did not know that there was no setup.py before... this PR makes no sense. need to investigate

**Comment by hertrste** [comment]
> AbstractLogger that is subclassed by TerminalLogger, XMLLogger, and JUnitXMLLogger, does not have to have the same interface as CompositeLogger. If AbstractLogger implementations keep implementing the bare minimum of functionality (e.g. only nested but not subtest), we can enrich the CompositeLogger with all the extra non-atomic functionality to build on top of the abstract core functionality and end up with less duplicate logic.

I simplified the `AbstractLogger` interface a bit by removing the `print_serial_logs(self, enable: bool)` function which is now only available in the `CompositeLogger`.

Unfortunately, I think removing the `subtest` call from the AbstractLogger is not possible, because the new `JunitXMLLogger` needs to differentiate between `subtest` and `nested` calls.
It would be possible to extend the `nested`  function to receive the type of nesting e.g. `nested(message, NestedType.SUBTEST)`, `nested(message, NestedType.GENERIC)` but I am not sure if this increases readability or improves the API instead of having the 2 function calls separately.

**Comment by tfc** [comment]
@ofborg test login

**Review by tfc — APPROVED** [review]

**Comment by nikstur** [comment]
@wegank since this shouldn't be a breaking change It should be fine to merge before the branch off. Do you disagree? Otherwise I'm inclined to merge.

**Review by wegank — APPROVED** [review]

**Review by messemar — APPROVED** [review]

**Pull request merged**
