### PR TITLE
git: 2.3.0 -> 2.3.1

### PR DESCRIPTION
**Pull request by k0ral**
Cc maintainers: @the-kenny @wmertens @peti 

I didn't have the opportunity to test it, though.

### CODE REVIEW

**Comment by lethalman** [comment]
Assigning mass rebuild, git is used by fetchgit and chromium needs to be recompiled. Better go into staging.

**Comment by peti** [comment]
Personally, I'm not merging PRs that say "I didn't test this".

Anyway, my understanding of the `mass-rebuild'  label is that it's for patches that change `stdenv`. A git update certainly causes many rebuilds, but it's not a `stdenv` change and the majority of builds in Nixpkgs will be unaffected by this update.

**Comment by peti** [comment]
Anyway ... merged to staging.

**Comment by edolstra** [comment]
Yeah, Git updates can go straight to master.

**Pull request closed without merging**
