### PR TITLE
compiler-rt: apply armv6l patches to llvm >= 15 where applicable

### PR DESCRIPTION
**Pull request by symphorien**
Fixes armv6 build of compiler-rt.

the patches were written for
https://github.com/NixOS/nixpkgs/pull/205176 but not kept for llvm >= 15

cc @lopsided98 as the author of https://github.com/NixOS/nixpkgs/pull/205176

tested by cross compiling only.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
Are all the patch files copies of each other?

**Comment by symphorien** [comment]
no there are 3 versions of it: the original for llvm <= 14, an intermediary one for 15 16 17 18 and the latest one for 19 and 20.

**Comment by RossComputerGuy** [comment]
> intermediary one for 15 16 17 18 and the latest one for 19 and 20.

Wdym by intermediary? Are the ones for 15+ the same exact file?

**Comment by symphorien** [comment]
I mean nothing special by intermediary.
There are three distinct patches.
```
$  md5sum pkgs/development/compilers/llvm/**/armv6-scudo-libatomic.patch
e179fdad601bc6cb60cf7a2587354b6b  pkgs/development/compilers/llvm/15/compiler-rt/armv6-scudo-libatomic.patch
e179fdad601bc6cb60cf7a2587354b6b  pkgs/development/compilers/llvm/16/compiler-rt/armv6-scudo-libatomic.patch
e179fdad601bc6cb60cf7a2587354b6b  pkgs/development/compilers/llvm/17/compiler-rt/armv6-scudo-libatomic.patch
e179fdad601bc6cb60cf7a2587354b6b  pkgs/development/compilers/llvm/18/compiler-rt/armv6-scudo-libatomic.patch
ba8b03aef2c271c484275408c1a30b33  pkgs/development/compilers/llvm/19/compiler-rt/armv6-scudo-libatomic.patch
f2e6764468ceca1f4d5b29fa16b92553  pkgs/development/compilers/llvm/common/compiler-rt/armv6-scudo-libatomic.patch
ba8b03aef2c271c484275408c1a30b33  pkgs/development/compilers/llvm/git/compiler-rt/armv6-scudo-libatomic.patch
```

**Comment by RossComputerGuy** [comment]
Yeah, I was just wondering because there's work to slim down our patches by removing duplicates and changing `getVersionFile` to branch based on the file path and version.

**Comment by symphorien** [comment]
ping @RossComputerGuy

**Comment by RossComputerGuy** [comment]
Please update `getVersionFile` to handle duplicates and remove duplicate patches. The PR which implemented that was merged so you'll have to rebase.

**Comment by symphorien** [comment]
done

**Review by RossComputerGuy — APPROVED** [review]

**Pull request merged**
