### PR TITLE
wireshark: 2.4.6 -> 2.4.7

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

This is a bugfix release. See https://www.wireshark.org/docs/relnotes/wireshark-2.4.7.html for
release information.

Once merged, I’ll port it to 18.03.

I’ll work shortly into updating master to the 2.6 branch.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg build wireshark-gtk wireshark-cli

**Comment by xeji** [comment]
`wireshark-gtk` didn't build anymore (assertion failure) because 48a1345eaa1c added `withQt = true;` to `wireshark` in `top-level/all-packages.nix`. Fixed this in 382c20912ede5e0da7c3e0addd803762ef68f48c

**Comment by xeji** [comment]
@GrahamcOfBorg  build wireshark-qt wireshark-gtk

**Comment by jtojnar** [comment]
Hmm, we should probably fix the other issues listed in the commit too.

**Comment by xeji** [comment]
Agree. Sorry I didn't see your comments in 48a1345eaa1c57727f980fcdca0650a1311a485f,  I looked at it locally...

**Comment by xeji** [comment]
`wireshark-gtk` builds fine locally, so I think this can be merged.

**Comment by lsix** [comment]
It took me quite some time to rebuild wireshark-gtk to check it. I also got it working properly. Thanks @xeji

**Pull request merged**
