### PR TITLE
 nixos-render-docs: use packageOverrides to construct python packages 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by pennae — APPROVED** [review]
tested with all our as-yet-unmerged code, works fine. thank you!

**Review by pennae — CHANGES_REQUESTED** [review]
unfortunately this breaks `myst-parser` tests:
```
=========================== short test summary info ============================
FAILED tests/test_renderers/test_myst_config.py::test_cmdline[28-linkify] - SystemExit: 1
FAILED tests/test_renderers/test_myst_config.py::test_cmdline[38-gfm-strikethrough] - SystemExit: 1
FAILED tests/test_renderers/test_myst_config.py::test_cmdline[56-gfm-disallowed-html] - SystemExit: 1
FAILED tests/test_renderers/test_myst_config.py::test_cmdline[83-gfm-autolink] - SystemExit: 1
FAILED tests/test_sphinx/test_sphinx_builds.py::test_extended_syntaxes - ModuleNotFoundError: Linkify enabled but not installed.
=== 5 failed, 936 passed, 7 skipped, 67 deselected, 18782 warnings in 5.73s ====
```
and in doing so also breaks every single homeassistant test (which make up the bulk of the rebuild count)

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 should this go through python-updates or straight to master?

There is no current python-updates run, so not currently.

**Review by pennae — APPROVED** [review]
had to change a dependency name to all-lowercase to fix the build, but now everything seems to work fine.

nixpkgs-review says:
```
3 packages marked as broken and skipped:
apache-airflow python310Packages.apache-airflow python311Packages.apache-airflow

1 package blacklisted:
nixos-install-tools
```

**Comment by SuperSandro2000** [comment]
You know who recently renamed that package? 😅 

<---

**Pull request merged**
