### PR TITLE
dar: 2.5.9 -> 2.5.14

### PR DESCRIPTION
**Pull request by Izorkin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg build dar

**Comment by 7c6f434c** [comment]
Hm, it actually did build on Darwin before the change https://hydra.nixos.org/build/69374844

**Comment by Izorkin** [comment]
Bugs - macOS build failure - https://sourceforge.net/p/dar/bugs/201/

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build dar

**Pull request merged**
