### PR TITLE
rabbitmq-server: 3.8.9 -> 3.9.1

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
@ofborg build rabbitmq-server.passthru.tests

**Comment by turion** [comment]
When testing locally, I get this error:

```
machine # [   24.878486] rabbitmq-server[793]: 2021-08-02 13:24:19.644473+00:00 [info] <0.224.0> starting Ra system: coordination in directory: /var/lib/rabbitmq/mnesia/rabbit@machine/coordination/rabbit@machine
machine # [   24.883546] rabbitmq-server[793]: 2021-08-02 13:24:19.650333+00:00 [erro] <0.269.0> Failed to create Ra data directory at '/var/lib/rabbitmq/mnesia/rabbit@machine/coordination/rabbit@machine', file system operation error: enospc
machine # [   24.921967] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>   crasher:
machine # [   24.923496] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     initial call: supervisor:ra_system_sup/1
machine # [   24.926501] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     pid: <0.269.0>
machine # [   24.929435] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     registered_name: []
machine # [   24.932840] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     exception exit: {error,"Ra could not create its data directory. See the log for details."}
machine # [   24.938194] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>       in function  ra_system_sup:init/1 (src/ra_system_sup.erl, line 42)
machine # [   24.950649] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>       in call from supervisor:init/1 (supervisor.erl, line 330)
machine # [   24.958274] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>       in call from gen_server:init_it/2 (gen_server.erl, line 423)
machine # [   24.963844] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>       in call from gen_server:init_it/6 (gen_server.erl, line 390)
machine # [   24.970728] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     ancestors: [ra_systems_sup,ra_sup,<0.189.0>]
machine # [   24.974244] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     message_queue_len: 0
machine # [   24.977462] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     messages: []
machine # [   24.980304] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     links: [<0.194.0>]
machine # [   24.983537] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     dictionary: []
machine # [   24.985619] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     trap_exit: true
machine # [   24.987508] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     status: running
machine # [   24.989706] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     heap_size: 1598
machine # [   24.992597] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     stack_size: 29
machine # [   24.994446] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>     reductions: 3299
machine # [   24.996239] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>   neighbours:
machine # [   25.001043] rabbitmq-server[793]: 2021-08-02 13:24:19.650767+00:00 [erro] <0.269.0>
machine # [   25.004381] rabbitmq-server[793]: 2021-08-02 13:24:19.771451+00:00 [noti] <0.44.0> Application mnesia exited with reason: stopped
machine # [   25.006273] rabbitmq-server[793]: BOOT FAILED
machine # [   25.007135] rabbitmq-server[793]: 2021-08-02 13:24:19.771763+00:00 [erro] <0.224.0>
machine # [   25.008394] rabbitmq-server[793]: 2021-08-02 13:24:19.771763+00:00 [erro] <0.224.0> BOOT FAILED
machine # [   25.009717] rabbitmq-server[793]: 2021-08-02 13:24:19.771763+00:00 [erro] <0.224.0> ===========
machine # [   25.011099] rabbitmq-server[793]: 2021-08-02 13:24:19.771763+00:00 [erro] <0.224.0> Exception during startup:
machine # [   25.012549] rabbitmq-server[793]: 2021-08-02 13:24:19.771763+00:00 [erro] <0.224.0>
machine # [   25.013692] rabbitmq-server[793]: 2021-08-02 13:24:19.771763+00:00 [erro] <0.224.0> error:{badmatch,{error,{{error,"Ra could not create its data directory. See the log for details."},{child,undefined,coordination,{ra_system_sup,start_link,[#{data_dir => "/var/lib/rabbitmq/mnesia/rabbit@machine/coordination/rabbit@machine",name => coordination,names => #{closed_mem_tbls => ra_coordination_log_closed_mem_tables,directory => ra_coordination_directory,directory_rev => ra_coordination_directory_reverse,log_ets => ra_coordination_log_ets,log_meta => ra_coordination_log_meta,log_sup => ra_coordination_log_sup,open_mem_tbls => ra_coordination_log_open_mem_tables,segment_writer => ra_coordination_segment_writer,server_sup => ra_coordination_server_sup_sup,wal => ra_coordination_log_wal,wal_sup => ra_coordination_log_wal_sup},segment_max_entries => 4096,wal_compute_checksums => true,wal_data_dir => "/var/lib/rabbitmq/mnesia/rabbit@machine/coordination/rabbit@machine",wal_max_batch_size => 4096,wal_max_entries => undefined,wal_max_size_bytes => 64000000,wal_sync_method => datasync,wal_write_strategy => default}]},permanent,false,infinity,supervisor,[ra_system_sup]}}}}
```

Is `/var/` readonly in the test system?

**Comment by turion** [comment]
This is really strange. The tests fail only locally!

**Comment by turion** [comment]
Stranger even, I now can't reproduce the failure anymore. Nevermind.

**Comment by turion** [comment]
Here is a hint:

```
machine # [   32.475751] rabbitmq-server[799]: 2021-08-02 13:45:54.253144+00:00 [info] <0.295.0> Enabling free disk space monitoring
machine # [   32.477911] rabbitmq-server[799]: 2021-08-02 13:45:54.253202+00:00 [info] <0.295.0> Disk free limit set to 50MB
machine # [   32.515528] rabbitmq-server[799]: 2021-08-02 13:45:54.292539+00:00 [info] <0.295.0> Free disk space is insufficient. Free bytes: 14336000. Limit: 50000000
machine # [   32.518810] rabbitmq-server[799]: 2021-08-02 13:45:54.292688+00:00 [warn] <0.291.0> disk resource limit alarm set on node rabbit@machine.
machine # [   32.521763] rabbitmq-server[799]: 2021-08-02 13:45:54.292688+00:00 [warn] <0.291.0>
machine # [   32.527227] rabbitmq-server[799]: 2021-08-02 13:45:54.292688+00:00 [warn] <0.291.0> **********************************************************
machine # [   32.531241] rabbitmq-server[799]: 2021-08-02 13:45:54.292688+00:00 [warn] <0.291.0> *** Publishers will be blocked until this alarm clears ***
machine # [   32.533509] rabbitmq-server[799]: 2021-08-02 13:45:54.292688+00:00 [warn] <0.291.0> **********************************************************
```

The amount of free space is different though on CI than on my local machine. So probably the amount of free disk space is not deterministic, and can sometimes be too little that the disk is full (and thus the failure from above occurs).

**Comment by turion** [comment]
If anyone knows how to increase the VM disk size, feel free to help me out. I don't understand it.

**Comment by SuperSandro2000** [comment]
> If anyone knows how to increase the VM disk size, feel free to help me out. I don't understand it.

https://github.com/NixOS/nixpkgs/blob/419f03859dba357456ecce936b386cb0658cd75e/nixos/tests/graylog.nix#L7

**Comment by turion** [comment]
Setting this to a reasonable value (1 GB) fixes it and makes the test less brittle.

**Comment by turion** [comment]
@ofborg build rabbitmq-server.passthru.tests

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132416` at b0f33d7c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>rabbitmq-server</li>
  </ul>
</details>
<details>
  <summary>6 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '`dirname $0`/rabbitmq-env' doesn't match anything in file '/nix/store/nzdf9jgb0v6j1vnngy48mpdh51bdpiib-rabbitmq-server-3.9.1/sbin/rabbitmq-server'
Near pkgs/servers/amqp/rabbitmq-server/default.nix:65:0:
```
   |
65 |     description = "An implementation of the AMQP messaging protocol";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

docbook_xml_dtd_45 is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/amqp/rabbitmq-server/default.nix:20:3:
```
   |
20 |   buildInputs =
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

xmlto is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/amqp/rabbitmq-server/default.nix:20:3:
```
   |
20 |   buildInputs =
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

docbook-xsl-nons is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/amqp/rabbitmq-server/default.nix:20:3:
```
   |
20 |   buildInputs =
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

rsync is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/amqp/rabbitmq-server/default.nix:20:3:
```
   |
20 |   buildInputs =
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

zip is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/amqp/rabbitmq-server/default.nix:20:3:
```
   |
20 |   buildInputs =
   |   ^
```
</li>
  </ul>
</details>

**Comment by risicle** [comment]
Excellent! I can close #132242...

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64. `nixosTests.rabbitmq` passes.

**Comment by turion** [comment]
Yes, seems 3.9 is happier with newer elixir & OTP versions.

**Pull request merged**
