### PR TITLE
terragrunt: 0.16.6 -> 0.17.2

### PR DESCRIPTION
**Pull request by stephengroat**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
@GrahamcOfBorg build terragrunt

**Comment by timokau** [comment]
Poor ofborg is probably just overworked, looks like a transient failure.

@GrahamcOfBorg build terragrunt

**Comment by Mic92** [comment]
This happens quite often for go because it spawns workers based on the number of cpus, which happens to be quite high on our aarch64 builder.

**Comment by timokau** [comment]
Ah good to know. We probably should fix that some time.

**Comment by stephengroat** [comment]
fyi https://github.com/NixOS/nixpkgs/pull/50036#issuecomment-437590116 seems like the same type of failure
```
github.com/terraform-providers/terraform-provider-spotinst/vendor/github.com/posener/complete/cmd/install
# github.com/terraform-providers/terraform-provider-spotinst/vendor/github.com/mitchellh/hashstructure
runtime: failed to create new OS thread (have 6 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

**Comment by timokau** [comment]
Well lets assume the best then. Thank you @stephengroat!

**Pull request merged**
