### PR TITLE
python3Packages.priority: remove patch

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Remove patch to fix build (https://hydra.nixos.org/build/153048278).

- Switch to `pytestCheckHook`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 139217` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.aioh2</li>
    <li>python39Packages.aioh2</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.hypercorn</li>
    <li>python38Packages.priority</li>
    <li>python39Packages.hypercorn</li>
    <li>python39Packages.priority</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 139217` at f599141c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/4e49136fee23b9d1d8c4776fa9bfe93d">python38Packages.aioh2</a></li>
    <li><a href="https://gist.github.com/615b8ad26bfc13b87742b7ca0f20d1b9">python39Packages.aioh2</a></li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>python38Packages.hypercorn</li>
    <li>python38Packages.priority</li>
    <li>python39Packages.hypercorn</li>
    <li>python39Packages.priority</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by samuela — APPROVED** [review]
Is there a reason the patch is no longer needed?

**Comment by mweinelt** [comment]
Duplicate of #138598.

**Comment by mweinelt** [comment]
> Is there a reason the patch is no longer needed?

Follow the link in the comment above it. The issue was resolved upstream, which made the patch obsolete.

**Pull request closed without merging**
