### PR TITLE
Python packages.fluidasserts

### PR DESCRIPTION
**Pull request by kamadorueda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM
commits LGTM

failure is an upstream issue
```
[12 built (1 failed), 27 copied (158.2 MiB), 3.3 MiB DL]
error: build of '/nix/store/sfglznhrmqaryvp7i50sxwdg5marn9sa-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/80828
1 package failed to build:
python38Packages.pywinrm

8 package built:
fluidasserts python27Packages.pywinrm python37Packages.graphql-core python37Packages.graphql-server-core python37Packages.promise python37Packages.pywinrm python38Packages.graphql-core python38Packages.promise
```

failure:
```
    /nix/store/9nh4qk8zjgzqlnzj6hp5n1nkyzicss4x-python3.8-unittest2-1.1.0/lib/python3.8/site-packages/unittest2/compatibility.py:143: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
      class ChainMap(collections.MutableMapping):
```

**Comment by kamadorueda** [comment]
@jonringer in the last force push I disabled pywinrm for py38 so now the nix-review passes

**Review by jonringer — APPROVED** [review]
LGTM

```
[1 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/80828
8 package built:
fluidasserts python27Packages.pywinrm python37Packages.graphql-core python37Packages.graphql-server-core python37Packages.promise python37Packages.pywinrm python38Packages.graphql-core python38Packages.promise
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build fluidasserts python27Packages.pywinrm python37Packages.graphql-core python37Packages.graphql-server-core python37Packages.promise python37Packages.pywinrm python38Packages.graphql-core python38Packages.promise

**Comment by jonringer** [comment]
@kamadorueda do you care about fluidasserts being available on the release channel?

It's still broken on `release-20.03`

**Comment by kamadorueda** [comment]
@jonringer where do you see that info? last time I reviewed some hydra logs and adjusted the package to pass

**Comment by kamadorueda** [comment]
@jonringer alright! although it seems to be the previous hard-pinned-dependencies problem

https://hydra.nixos.org/build/113405614/nixlog/1

i'll keep an eye on it

**Comment by jonringer** [comment]
it does, but if your use case only includes unstable, then I'm not sure how much benefit you will get

**Comment by strager** [comment]
@kamadorueda In this PR, you introduced graphql-core and graphql-server-core. These packages depend on the rx package. I am upgrading the rx package as a part of my PR (#71166). graphql-core has a release (3.1.0) which is compatible with rx version 3, but graphql-server-core does not yet have a release which is compatible. With my unmerged PR, the graphql-core (and thus the graphql-server-core) builds are broken.

I don't see any use of graphql-server-core or graphql-core in this PR. fluidasserts doesn't seem to depend on these packages.

I see a few options:

1. upgrade rx from 1.6 to 3.0; upgrade graphql-core to 3.1.0; upgrade graphql-server-core to an unreleased version
2. upgrade rx from 1.6 to 3.0; upgrade graphql-core to 3.1.0; delete graphql-server-core
3. upgrade rx from 1.6 to 3.0; delete graphql-core; delete graphql-server-core
4. add rx 3.0 along-side rx 1.6; have graphql-core use rx 1.6 and have twitch-python use rx 3.0

Let me know what you recommend. I am leaning toward option 2.

**Comment by jonringer** [comment]
fluidasserts has been broken for over a month, I would say just do upgrade of rx to 3.0, and mark `graphql-server-core` as broken.

**Pull request merged**
