### PR TITLE
iso-image: slim down UEFI El Torito image

### PR DESCRIPTION
**Pull request by tpwrules**
###### Description of changes

UEFI firmware does not have to be able to read ISO9660 filesystems, so the El Torito mechanism provides a way to specify an embedded FAT32 image which contains files the UEFI firmware itself must be able to read, such as UEFI executables. Once GRUB starts and reads its configuration, it can access the ISO9660 filesystem to load other files.

This change removes the unused kernel, initrd, and GRUB font files from the El Torito image, but keeps the GRUB configuration and UEFI executables. Other distribution ISOs, such as Ubuntu 20.04, Fedora 35, and Windows 10 work this way too. This saves 24MiB on x86_64 and 61MiB on aarch64 ISOs.

You can test this change by pulling this branch, running `nix-build ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux`, and `dd`ing the created `result/iso/*.iso` to a flash drive. Given the wide variety of UEFI implementations, more testing is smart.

cc: @samueldr

###### Things done

- Tested booting NixOS and rEFInd on the following systems
  - QEMU x86_64 CDROM and USB (NixOS tests)
  - MacBook Pro (Retina, 13-inch, Early 2015)
  - Lenovo Thinkpad P52
  - ASUS P9X79
  - U-Boot 2022.04-rc4 (AArch64)

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Artturin — APPROVED** [review]
used ventoy boot the iso on `t440p` uefi and `msi mag x570 tomahawk` uefi

**Comment by Artturin** [comment]
Can you do a blame and find what commits those were added in?

**Comment by tpwrules** [comment]
Oops, I thought I commented on that. The kernel and initrd have been in the El Torito image since EFI support was introduced back in 2012: https://github.com/NixOS/nixpkgs/blob/097c656361f597f36be798b8b2d50c34446dea5a/modules/installer/cd-dvd/iso-image.nix#L131-L134

I don't think it was absolutely necessary then either.

**Comment by Artturin** [comment]
the PR description should be in the commit message too

**Comment by Artturin** [comment]
Tested on v3 771g 2012 asus laptop

**Pull request merged**
