### PR TITLE
emacs-packages: Drop deprecated package sets

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
These have been deprecated for a long time and I think we are doing our users a disservice by still keeping them around.

I tried porting over all packages that were not in any generated sets but some of these are broken.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @mdorman @thoughtpolice @peti @samuelrivas @etu 

Note that I've left all derivations on purpose. I will make a follow up PR taking care of those once this one is merged.

### CODE REVIEW

**Comment by adisbladis** [comment]
I think the release note could be better, any suggestions?

**Comment by oxij** [comment]
I like the idea (and simplicity) of dropping `emacsPackages` and renaming `emacsPackagesNg -> emacsPackages` in a single PR, but

- I see some `emacsPackages` vanishing without a trace from attrsets (e.g. `scalaMode*`) while their nix files are left in the working tree (I assume they just have different names in MELPA, but then this PR leaves garbage around),
- also, I think, there should be aliases for all the old names.

**Comment by adisbladis** [comment]
@oxij I made a note of that `Note that I've left all derivations on purpose. I will make a follow up PR taking care of those once this one is merged.`

And while I'm a fan of aliases for backwards compat the current names we have are not matching well to the emacs ecosystem and I would rather drop them once and for all than having to keep aliases around for an eternity.

**Comment by oxij** [comment]
Well, leaving garbage in the tree until some later PR seems counterproductive to me.

IMHO, ideally, this would be done as a bunch of separate commits replacing old `emacsPackages` with aliases in `emacsPackagesNg` (while removing the original ad-hoc expressions), followed by a rename `emacsPackagesNg -> emacsPackages`.

But given that nobody did that for two+ years, one big rename, as done here, is probably fine. But only when done with aliases.

> And while I'm a fan of aliases for backwards compat the current names we have are not matching well to the emacs ecosystem and I would rather drop them once and for all than having to keep aliases around for an eternity.

Well, yes, but sudden drops of attributes are uber-annoying when you need to build the same `configuration.nix` against several revisions of `nixpkgs`. Which is a rather common use case: e.g., you want to build against both latest release and `master`, you want to bisect over a span of revisions of `nixpkgs`, etc etc.

**Comment by bendlas** [comment]
currently running my system on this PR .. everything seems fine, so far. I have been on emacsPackagesNg for some time though ..

**Comment by adisbladis** [comment]
> Well, leaving garbage in the tree until some later PR seems counterproductive to me.

OK fair enough, I've dropped all old packages in this PR.

I'm still on the fence about aliases, I don't think that the bisect use case is a good enough reason.
I'd like others to chime in with an opinion on this too.

I aim to merge this before the 19.09 release.

**Comment by oxij** [comment]
> OK fair enough, I've dropped all old packages in this PR.

Thanks.

> I'm still on the fence about aliases, I don't think that the bisect use case is a good enough reason.

But isn't the ability to build the same `configuration.nix` against 19.03, master, and future 19.09 a good reason?

**Review by etu — APPROVED** [review]

**Review by talyz — APPROVED** [review]

**Comment by adisbladis** [comment]
cc @ttuegel @bendlas @matthewbauer

**Comment by bendlas** [comment]
I'm a believer in the "don't break api" principle, so if somebody is willing to comb through the package sets, I'm for leaving the aliases in place, along with a deprecation warning.

**Comment by adisbladis** [comment]
I have added the requested aliases, even though I'm personally not a fan.

**Comment by samuelrivas** [comment]
Although they are actually different packages, so that might not be a good idea after all

**Comment by samuelrivas** [comment]
I just went ahead and fixed `colorThemeSoloarized`: https://github.com/NixOS/nixpkgs/pull/68768

**Pull request merged**
