### PR TITLE
[20.03] element-{web,desktop}: backport version bump & rename

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Backports the rename of `riot-{web,desktop}` to `element` (#93134, #93303, #93308) that has happened during the update to `1.7`. Also added some warnings to advertise the use of `pkgs.element*` and to mention removed feature-flags (where the features are now available by default in `element`).

Rationale for backport: for the matrix subsystem on NixOS we've established a backport-by-default policy to remain up-to-date with the `matrix.org` infrastructure several months ago (previosuly we experienced compat-issues with their infrastructure occasionally). Several people (including me) from the Nix-matrix channel are already using `element-web` at `1.7` on NixOS systems (on both unstable and 20.03) without having any issues (while using and while migrating to it), so we currently consider this backport as doable.

cc @NixOS/backports @claudiiii 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
As suggested by @pacien, we should do the migration now on 20.03 and only have `element*` available on 20.09. For this, I opened #93774

**Comment by Ma27** [comment]
Hmm right, `lib.warn` doesn't work in `aliases.nix`. Will fix this before merging.

**Comment by claudiiii** [comment]
Since Electron 9 is not in 20.03 but Electron 8 is, it might be worthwhile to use that, at least for the backport.

**Review by bachp — APPROVED** [review]

**Comment by Ma27** [comment]
Latest push should fix eval, also using `electron_8` for `riot-desktop` now.

**Comment by Ma27** [comment]
@NixOS/backports any objctions?

**Comment by worldofpeace** [comment]
No objections @Ma27

**Review by worldofpeace — APPROVED** [review]
Haven't tested, but I believe this was okay.

**Pull request merged**
