### PR TITLE
pycharm: 2017.1 -> 2017.1.2 -> 2017.1.3 [release 17.03]

### PR DESCRIPTION
**Pull request by drdaeman**
###### Motivation for this change

This is the same as https://github.com/NixOS/nixpkgs/pull/25673, but done against the `release-17.03` branch instead of `master`, as things were moved around on `master` (`idea` was renamed to `jetbrains`)

Please merge, as otherwise `pycharm-professional` isn't available for 17.03 (version 2017.1 tarball was removed by vendor).

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
LGTM, I'd like for the maintainers to chime in on whether the commits that move stuff around can be picked to release as well to reduce the friction involved in updating stuff.

**Comment by edwtjo** [comment]
@joachifm this rename of idea -> jetbrains? I think that it could be cherry-picked, it's just bikeshedding.

**Comment by drdaeman** [comment]
Just a note: PyCharm was recently updated to 2017.1.3, so this PR is a little bit outdated ;) Even more so if s/idea/jetbrains/ is going to get cherry-picked into `release-17.03` - if this is the case, this PR should be closed.

I'll make a new PR for 2017.1.3, against the `master` branch in some minutes. Currently testing it. If anyone's going to work on PyCharm, please consider checking it out as well.

----

Either way, what I'm worried about is that 2017.1 tarball is not available anymore so I had to comment out `idea.pycharm-professional` from my `configuration.nix`'s `environment.systemPackages`. 17.03 needs an update.

**Comment by drdaeman** [comment]
In case you'll decide against cherry-picking idea->jetbrains rename, I've updated this PR with 2017.1.3 as well.

**Comment by edwtjo** [comment]
cp:ed with: f0c4be2873d40b3c116ce64660d0a609c782b1d5 958443e0147f24cfbfb020062bf6aec8bc7a44a5 d56d0ab956e70baf7e35514189befbf3e1785d7a b50009158b480d776a7395c3164b6540b985409e

**Pull request closed without merging**
