### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change
https://hydra.nixos.org/jobset/nixpkgs/staging-next

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
https://github.com/NixOS/nixpkgs/pull/84660 should probably be included in this.

**Comment by vcunat** [comment]
There are apparently some python regressions that break e.g. [nixops](https://hydra.nixos.org/build/116501746).  One way might be to migrate anything important away from python2 anyway...

**Comment by FRidh** [comment]
Probably best to drop nixops in Nixpkgs since it's changed quite a bit upstream cc @adisbladis @GrahamcOfBorg

**Comment by vcunat** [comment]
I fixed it somehow in 312e903; feel free to improve.

**Review by vcunat — APPROVED** [review]
[On Hydra](https://hydra.nixos.org/eval/1582513?compare=1582510) it looks good.  About a third of darwin packages still hasn't been finished, but that risk seems acceptable &ndash; on the other hand we have security fixes inside.

**Comment by adisbladis** [comment]
@FRidh A new release of NixOps is still pretty far away, in the mean time we need the current release.

If you'd like I can try to repackage the current release using Poetry/poetry2nix so NixOps won't be blocking any progression in `pythonPackages`?

**Comment by vcunat** [comment]
I fixed the build of `pyopenssl` which was blocking it, so `nixops` builds now and I don't expect you need to hurry with anything.

**Comment by petabyteboy** [comment]
I could neet some help with #85668. Both parent commits of this merge commit work fine, but waybar built from the merge commit does not (starts up fine but doesn't show the bar). Any idea what could cause this?

**Pull request merged**
