### PR TITLE
qgis: 3.10.11 → 3.10.13, mark unbroken

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
* update to 3.10.12 (LTR)
* unbroke (build without QtWebKit)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Is removing qtwebkit still needed? https://github.com/NixOS/nixpkgs/pull/104474

**Comment by sikmir** [comment]
> Is removing qtwebkit still needed? #104474

You are right, updated.

**Review by lsix — COMMENTED** [review]
Hi.

This looks good to me.

however, qgis-3.10.13 seems to be out. Would you mind  including this upgrade to your MR ?

Thanks.

**Comment by sikmir** [comment]
@lsix updated.

**Review by lsix — APPROVED** [review]
LGTM.

I have built & tested it.

Thanks!

**Pull request merged**
