### PR TITLE
nixos/qemu-vm: default memorySize 384 -> 1024

### PR DESCRIPTION
**Pull request by Artturin**
the default hasn't been changed since 2009
this can improve our test performances

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Opinions on setting it to `2047`? 2047 instead of 2048 because i saw this comment
```nixos/tests/nexus.nix:      { virtualisation.memorySize = 2047; # qemu-system-i386 has a 2047M limit```

**Comment by ck3d** [comment]
I would update the default only, when all tests have to set higher memory sizes.
But if we really wan to update, then we should also remove all memory size configurations which are less than the new value.

**Comment by Artturin** [comment]
> But if we really wan to update, then we should also remove all memory size configurations which are less than the new value.

I am going to do that

**Comment by mohe2015** [comment]
I would think that this should not increase physical memory usage if the VM is not using it. Because then I think it's fine and could lead to a speedup

**Comment by Artturin** [comment]
> I would think that this should not increase physical memory usage if the VM is not using it. Because then I think it's fine and could lead to a speedup

yeah it only increases the max amount the vm can use but doesn't reserve it all

**Comment by talyz** [comment]
> Opinions on setting it to `2047`? 2047 instead of 2048 because i saw this comment `nixos/tests/nexus.nix: { virtualisation.memorySize = 2047; # qemu-system-i386 has a 2047M limit` https://bugs.launchpad.net/maas-test/+bug/1257891

Sounds good to me, considering it shouldn't consume more memory for tests that don't use it.

**Review by roberth — APPROVED** [review]
This is very sensible.

I should note that VM memory usage probably expands quite quickly because of the disk cache, but I find it hard to imagine that even reserving 1GB _per physical core_ would not be feasible today. So :+1: 

This is similar to https://github.com/NixOS/nixpkgs/pull/144788 but for memory instead of disk.

**Comment by Artturin** [comment]
missed some memorySize <1024's

**Pull request merged**
