### PR TITLE
nheko: 0.10.0 -> 0.10.1-1

### PR DESCRIPTION
**Pull request by azahi**
###### Description of changes

Fixes a build failure https://hydra.nixos.org/build/190031815

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
Thanks for the fix. Works well.

---

Result of `nixpkgs-review pr 190714` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nheko</li>
  </ul>
</details>

**Comment by symphorien** [comment]
crashes for me when closing the window (so actually it works when I try to use it...)
```
Error: signal 11:
result/bin/nheko[0x9568cb]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(+0x3dbf0)[0x7f0f44b8abf0]
/nix/store/lk84rvw52b46wwp9wv7z4py0d348dx93-qtbase-5.15.5-bin/lib/qt-5.15.5/plugins/platformthemes/libqgtk3.so(+0x1a6be)[0x7f0f326af6be]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x23888)[0x7f0ef05e5888]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x242ad)[0x7f0ef05e62ad]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x25e81)[0x7f0ef05e7e81]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x26097)[0x7f0ef05e8097]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x12dfb)[0x7f0ef05d4dfb]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x12ef3)[0x7f0ef05d4ef3]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x12ef3)[0x7f0ef05d4ef3]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(+0x3e4ca5)[0x7f0f47160ca5]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x382e5)[0x7f0ef041f2e5]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(+0x3e3ef5)[0x7f0f4715fef5]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x38665)[0x7f0ef041f665]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/25kbm12ni04mr25mslr47xad8wfa2iwg-qtdeclarative-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so(+0x1a7e1)[0x7f0ef80247e1]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(+0x3e535e)[0x7f0f4716135e]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x38125)[0x7f0ef041f125]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x384a5)[0x7f0ef041f4a5]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(_ZN10QQuickViewD2Ev+0x45)[0x7f0f47063fe5]
result/bin/nheko(main+0xd56)[0x58e466]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(+0x2924e)[0x7f0f44b7624e]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(__libc_start_main+0x89)[0x7f0f44b76309]
result/bin/nheko[0x58ed15]
Error: signal 6:
result/bin/nheko[0x9568cb]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(+0x3dbf0)[0x7f0f44b8abf0]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(+0x8abc7)[0x7f0f44bd7bc7]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(raise+0x16)[0x7f0f44b8ab46]
result/bin/nheko[0x956981]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(+0x3dbf0)[0x7f0f44b8abf0]
/nix/store/lk84rvw52b46wwp9wv7z4py0d348dx93-qtbase-5.15.5-bin/lib/qt-5.15.5/plugins/platformthemes/libqgtk3.so(+0x1a6be)[0x7f0f326af6be]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x23888)[0x7f0ef05e5888]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x242ad)[0x7f0ef05e62ad]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x25e81)[0x7f0ef05e7e81]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x26097)[0x7f0ef05e8097]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x12dfb)[0x7f0ef05d4dfb]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x12ef3)[0x7f0ef05d4ef3]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/Qt/labs/platform/libqtlabsplatformplugin.so(+0x12ef3)[0x7f0ef05d4ef3]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(+0x3e4ca5)[0x7f0f47160ca5]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x382e5)[0x7f0ef041f2e5]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(+0x3e3ef5)[0x7f0f4715fef5]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x38665)[0x7f0ef041f665]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/25kbm12ni04mr25mslr47xad8wfa2iwg-qtdeclarative-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so(+0x1a7e1)[0x7f0ef80247e1]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(+0x3e535e)[0x7f0f4716135e]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x38125)[0x7f0ef041f125]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x78)[0x7f0f456b33d8]
/nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/lib/libQt5Core.so.5(_ZN7QObjectD2Ev+0x3b4)[0x7f0f456be184]
/nix/store/jmrv3kxpihai23k7mvflr6x7j28ajgrz-qtquickcontrols2-5.15.5-bin/lib/qt-5.15.5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so(+0x384a5)[0x7f0ef041f4a5]
/nix/store/yv17rn8s32y7r0c2dv4m1nwhbl31sw4b-qtdeclarative-5.15.5/lib/libQt5Quick.so.5(_ZN10QQuickViewD2Ev+0x45)[0x7f0f47063fe5]
result/bin/nheko(main+0xd56)[0x58e466]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(+0x2924e)[0x7f0f44b7624e]
/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib/libc.so.6(__libc_start_main+0x89)[0x7f0f44b76309]
result/bin/nheko[0x58ed15]
zsh: abort (core dumped)  result/bin/nheko
```

**Comment by azahi** [comment]
> crashes for me when closing the window (so actually it works when I try to use it...)

I can't reproduce that. You log doesn't say much tho, could you run nheko through something like `strace`?

**Comment by greydot** [comment]
> crashes for me when closing the window (so actually it works when I try to use it...)

Can't reproduce this either. Built nheko from this PR rebased on the latest `master` branch.

**Review by rapenne-s — APPROVED** [review]
Works on NixOS amd64

**Comment by rapenne-s** [comment]
No issue for me, thank you for the update.

**Pull request merged**
