### PR TITLE
Jetbrains plugins

### LINKED ISSUE #189183: Jetbrains IDEs with plugins?
**Project description**
I feel it would be beneficial for extensions to be in the store instead of/in addition to the regular mechanism. For example, #188488 adds a dependency which most people won't use, but is a pain to set up otherwise, and I doubt go is the only extension where this is the case.

I'm planning on doing this myself, but made this issue because I have other things to work on first.

### PR DESCRIPTION
**Pull request by GenericNerdyUsername**
###### Description of changes

This commit adds support for declarative plugins (including ones which need patching) and some helper functions for fetching them from https://plugins.jetbrains.com. Untested on darwin. Closes #189183 .

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by rien — COMMENTED** [review]
I'm have successfully used this PR to add [GitHub Copilot to IntelliJ and Clion in my own setup](https://github.com/rien/nixos-config/blob/3c97851e1874c6a05b5d459a858bb1591bf45f54/modules/intellij.nix#L33-L104). Thanks!

It is a bit unwieldy to use the functions here though, maybe an interface like this would be more ergonomic:
```nix
with pkgs.jetbrains;
let 
  copilot = mkJetbrainsPlugin {
     src = fetchJetbrainsPlugin {
       id = "1234";
       hash = "....";
     };
    buildInputs = with pkgs; [ patchelf gcc-unwrapped  ];
    build = ''
      # ... additional build steps
    '';
  };
in idea-ultimate.withPlugins [ copilot ]
```

Also, instead of adding exceptions for `specialPlugins`, we could provide a collection of plugins (`pkgs.jetbrains.plugins.copilot` for example).

What do you think?

**Comment by ktor** [comment]
Hi @GenericNerdyUsername, thank you for the PR!! I've applied it already with overlays based on:

1. https://github.com/rien/nixos-config/blob/3c97851e1874c6a05b5d459a858bb1591bf45f54/modules/intellij.nix#L33-L104 and
2. https://discourse.nixos.org/t/clion-github-copilot-fails-to-login/22197/4?u=ktor

To install GitHub copilot for idea-ultimate and it works like a charm! :)

Here is the overlay: https://github.com/ktor/nixos/commit/35f4071faab696b2a4d86643726c9dd3e4293964

**Comment by rien** [comment]
> How would that interface get the hash of the api response? Would there be a way to make nix ignore impure derivations if its only dependency is content addressed? As long as updating plugins/adding new plugins isn't too hard, I think the plugin list would work.

I think this is usually done by creating an `update`-script which would generate pure input-url's (+ their hashes) to use with `fetchUrl`. So the first step (`getUrl`) would have to be done by that script.

**Comment by GenericNerdyUsername** [comment]
I've added the update script and reworked how you add plugins, though I'm really tired and have definitely missed something, I'm just putting this out there so other people can suggest improvements or use it

**Comment by GenericNerdyUsername** [comment]
Whats stopping this from getting merged?

**Comment by jys1670** [comment]
Thank you for your effort! Everything works as expected on my x86_64 laptop.
I've also tried your [overlay](https://gitlab.com/genericnerdyusername/jetbrains-updater/) that adds JCEF support to JDK, it solved markdown preview issues in Clion.
As for slow merges - sadly that's common for complicated changes, to speed things up it is worth messaging few
active reviewers in nixos matrix or mentioning this PR in "PRs ready for review" once again.

**Comment by kouyk** [comment]
> Whats stopping this from getting merged?

maintainers don't seem to be merging jetbrains related PRs, all of them seems to have been stalled for a while now. furthermore darwin users aren't really reviewing or helping to diagnose build issues

**Comment by not-matthias** [comment]
+1 on this. I'd love to not have to use a 3rd party flake to be able to use Github Copilot.

**Pull request closed without merging**
