### PR TITLE
emacs generic: add `libXi` in `buildInputs` when `withXinput2`

### PR DESCRIPTION
**Pull request by W95Psp**
Without the library `libXi`, buulding Emacs with `--with-xinput2` has no effect. This can be observed by looking up the variable `system-configuration-features` in Emacs: with `libXi` the feature is enabled, without it is not.

## Description of changes
Add library `libXi` in `buildInputs` whenever `withXinput2` is `true`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AndersonTorres — COMMENTED** [review]
.

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Reword the commit:

```
emacs: add missing `libXì  dependency when enabling `withXinput2`


Without libXi, the configure flag `--with-xinput2` has no effect.

This can be verified by looking up the variable `system-configuration-features` in Emacs.
```

**Review by AndersonTorres — APPROVED** [review]

**Comment by dschrempf** [comment]
FYI, the Xinput2 issue was mentioned on the Emacs mailing list: https://lists.gnu.org/archive/html/emacs-devel/2023-09/msg00815.html.

**Comment by AndersonTorres** [comment]
Backporting Emacs isn't being easy nowadays...

**Pull request merged**
