### PR TITLE
python: grpcio: 1.9.1 -> 1.12.0

### PR DESCRIPTION
**Pull request by lopsided98**
Updates grpcio to the latest version.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lopsided98** [comment]
cc @FRidh

**Comment by xeji** [comment]
@GrahamcOfBorg  build python27Packages.grpcio python36Packages.grpcio

**Comment by FRidh** [comment]
```
Ran 0 tests in 0.000s
```
No tests are found. Either the test runner cannot find tests and needs to be patched, or there simply are no tests in which case the tests need to be disabled. Do include a comment explaining why the tests are disabled.

**Comment by orivej** [comment]
The current version is 1.9.1, not 1.9.0.

**Comment by lopsided98** [comment]
Grpc has tests, but they are not included in the package on PyPi. This has not changed since the previous version (see: https://hydra.nixos.org/build/74606746/nixlog/2/tail). I can disable the check phase, but I don't really see why that is necessary.

**Comment by xeji** [comment]
It would be nicer to disable the tests but let's not hold the bump because of housekeeping.

**Pull request merged**
