### PR TITLE
tailscale: init at 0.94-236.

### PR DESCRIPTION
**Pull request by danderson**
###### Motivation for this change

Tailscale is a mesh VPN service that I want to run on my NixOS machines. This change adds the package derivation. A future change will add a corresponding NixOS module (or I can add it to this change if you prefer).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [n/a] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [n/a] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [n/a] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danderson** [comment]
@GrahamcOfBorg eval

**Comment by danderson** [comment]
Right now the package can't start in nixos, due to missing runtime dependencies. Fixing that tomorrow, but in the meantime it should still be usable from plain nix.

**Comment by tazjin** [comment]
@danderson Since the client is now [open-sourced](https://github.com/tailscale/tailscale) (congrats, btw!), would it make sense to drop this PR in favour of one that builds the client instead?

**Comment by danderson** [comment]
Heh, you're quick on the mark :)

Yes, it makes complete sense to drop this in favor of an OSS derivation.

In fact, it makes even _more_ sense for me to wait on a nix pkg until we're replaced relaynode (old, prototype code that we currently ship for linux) with tailscaled (shiny, new, more featured code that we don't ship yet). I'll close this and make a new PR when tailscaled is ready to ship :)

**Comment by danderson** [comment]
Oh, you already built the OSS version as tailscaled!

Hmm. I think I'd prefer to delay "official" Nix/NixOS support by a couple of days, until I have a few more changes ready in tailscaled (to avoid having to do data migrations and other nonsense later on).

**Comment by tazjin** [comment]
Totally reasonable! I'm just excited to be able to play with it now, but I did end up adding the relaynode subcommand to get things to work.

Didn't you also already make a NixOS module? I thought I saw that somewhere :thinking:

**Comment by danderson** [comment]
I started making a nixos submodule in another branch of my nixpkgs fork, but it was dependent on this PR. I don't think there's anything left to clean up on the nixpkgs side.

If you want the commit for yourself, it's at https://github.com/danderson/nixpkgs/commit/46aa3313c2eae5bda129e222077d0741695fc746 . No promises that it works, I don't think I got as far as "does this even run" :)

**Comment by martinbaillie** [comment]
Glad I found this as I was about to package up a Tailscale derivation myself! Do we think the Tailscale codebase at a stage now where a PR makes sense? (happy to help)

**Comment by danderson** [comment]
I think so. I've been meaning to get to it, but I keep getting distracted with other things :). I'll file an issue in the tailscale repo and cc you on it, there's a little bit of complexity around version stamps that we need to figure out.

**Pull request closed without merging**
