### PR TITLE
maestral-gui: 1.2.1 -> 1.3.1

### PR DESCRIPTION
**Pull request by SFrijters**
###### Motivation for this change

Upstream update.
Also added some missing requirements.

Note that the 1.3 release was a bit messy according to https://github.com/SamSchott/maestral/issues/250#issuecomment-739510048, hence the overrides for `watchdog` and `survey`. I tried to follow other similar occurrences in `python-packages.nix` but maybe this is not the way to go?

```
$ nix-shell -p nixpkgs-review --run "nixpkgs-review rev maestral-1.3"
[...]
6 packages added:
python37Packages.survey (init at 3.1.1) python37Packages.wrapio (init at 0.3.8) python38Packages.survey (init at 3.1.1) python38Packages.wrapio (init at 0.3.8) python39Packages.survey (init at 3.1.1) python39Packages.wrapio (init at 0.3.8)

4 packages updated:
maestral (1.2.1 → 1.3.1) maestral-gui (1.2.1 → 1.3.1) python37Packages.maestral (1.2.1 → 1.3.1) python38Packages.maestral (1.2.1 → 1.3.1)
[...]
9 packages built:
maestral maestral-gui python37Packages.maestral python37Packages.survey python37Packages.wrapio python38Packages.survey python38Packages.wrapio python39Packages.survey python39Packages.wrapio
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106361` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>maestral (python38Packages.maestral)</li>
    <li>maestral-gui</li>
    <li>python37Packages.maestral</li>
    <li>python37Packages.survey</li>
    <li>python37Packages.wrapio</li>
    <li>python38Packages.survey</li>
    <li>python38Packages.wrapio</li>
    <li>python39Packages.survey</li>
    <li>python39Packages.wrapio</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
```
python38Packages.wrapio.log                                                                                                                                                                 109:Ran 0 tests in 0.000s                                                                                                                                                                                                                                                                                                                                                               python39Packages.wrapio.log                                                                                                                                                                 109:Ran 0 tests in 0.000s                                                                                                                                                                                                                                                                                                                                                               python38Packages.survey.log                                                                                                                                                                 131:Ran 0 tests in 0.000s                                                                                                                                                                                                                                                                                                                                                               python37Packages.survey.log                                                                                                                                                                 131:Ran 0 tests in 0.000s                                                                                                                                                                                                                                                                                                                                                               python39Packages.survey.log                                                                                                                                                                 131:Ran 0 tests in 0.000s                                                                                                                                                                                                                                                                                                                                                               python37Packages.wrapio.log                                                                                                                                                                 109:Ran 0 tests in 0.000s  
```

Please add ``doCheck = false;`` and pythonImportsCheck.

**Comment by SFrijters** [comment]
@SuperSandro2000 Done, rebased the changes into the init commits.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106361` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>maestral (python38Packages.maestral)</li>
    <li>maestral-gui</li>
    <li>python37Packages.maestral</li>
    <li>python37Packages.survey</li>
    <li>python37Packages.wrapio</li>
    <li>python38Packages.survey</li>
    <li>python38Packages.wrapio</li>
    <li>python39Packages.survey</li>
    <li>python39Packages.wrapio</li>
  </ul>
</details>

**Pull request merged**
