### PR TITLE
all-cabal-hashes: update snapshot to Hackage at 2018-09-04T11:59:40Z

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
cc @peti

**Comment by vaibhavsagar** [comment]
cc @basvandijk, who I think is one of the new maintainers of the Haskell infrastructure in Nixpkgs.

**Comment by basvandijk** [comment]
Thanks! I tested the change using:
```
$ nix-build --no-out-link -E 'with (import ./. {}); haskellPackages.callHackage "hsdns" "1.7.1" {}'
```

**Comment by vaibhavsagar** [comment]
My pleasure :smile:

**Pull request merged**
