### PR TITLE
[21.05] chromium: 93.0.4577.82 -> 94.0.4606.54

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

Backport of #138843.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 139220` at 2347b9a7 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/b33267d10c23da3d491a17cc9e7f0776">chromium</a></li>
    <li><a href="https://gist.github.com/ebb3ca4c4cda7a4e047b902996ab83eb">puppeteer-cli</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by primeos** [comment]
@rmcgibbo does the bot ignore `meta.broken` (https://github.com/NixOS/nixpkgs/pull/136640 and https://github.com/NixOS/nixpkgs/pull/139220/checks?check_run_id=3692312454) and is that intended?

**Comment by rmcgibbo** [comment]
@primeos: I think the bot does whatever Mic92/nixpkgs-review does, and I think there the `meta.broken` attribute is just ignored. https://github.com/Mic92/nixpkgs-review/search?q=meta Not totally sure though.

**Comment by primeos** [comment]
@rmcgibbo: Strange, AFAIK nixpkgs-review does normally handle meta.broken accordingly (unless that has changed recently). It's no big deal though - just an FYI in case this is unintended ;)

---

The VM test succeeded:
/nix/store/jx1nkh6qbyyk46lmfpad6dy0w15nz799-vm-test-run-chromium-stable

**Pull request merged**
