### PR TITLE
python3Packages.pymavlink: 2.4.14 -> 2.4.15

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Updates pymavlink to the latest version. Tested `MAVExplorer.py` from `mavproxy`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120139` at cf4d2930 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>mavproxy</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.pymavlink</li>
    <li>python39Packages.pymavlink</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/pymavlink/default.nix:20:5:
```
   |
20 |     license = licenses.lgpl3;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/pymavlink/default.nix:18:0:
```
   |
18 |     description = "Python MAVLink interface and utilities";
   | ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Can we fetchFromGitHub to have tests?

**Comment by lopsided98** [comment]
> Can we fetchFromGitHub to have tests?

See here: https://github.com/NixOS/nixpkgs/pull/75640#discussion_r357930735. I added `pythonImportsCheck` though.

**Comment by SuperSandro2000** [comment]
> > Can we fetchFromGitHub to have tests?
> 
> See here: [#75640 (comment)](https://github.com/NixOS/nixpkgs/pull/75640#discussion_r357930735). I added `pythonImportsCheck` though.

Please add a comment with that info for future reviewers.

**Comment by lopsided98** [comment]
Ok, done.

**Pull request merged**
