### PR TITLE
jami: 20230323.0 -> 20230619.1

### PR DESCRIPTION
**Pull request by linsui**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
I was thought that this version requires a fix for https://bugreports.qt.io/browse/QTBUG-113484 in Qt 6.5.2. However, Qt 6.5.2 doesn't fix the bug. Instead it's fixed in https://git.jami.net/savoirfairelinux/jami-client-qt/-/commit/5f98f7cdc60d9525ed9ab953b0feb91ca8ed9036. And the bug which actually causes a crash in this version is fixed by the postPatch.

**Review by NickCao — APPROVED** [review]

**Comment by doronbehar** [comment]
@linsui could you take a look on the build error of this package in `staging-next`? Here's a build log:

https://hydra.nixos.org/build/229965246

**Comment by linsui** [comment]
Looks like it's broken by https://github.com/NixOS/nixpkgs/pull/243981.

**Comment by doronbehar** [comment]
- https://github.com/NixOS/nixpkgs/pull/247549

**Comment by linsui** [comment]
Sorry, I forgot to comment here. It's included in https://github.com/NixOS/nixpkgs/pull/247408.

**Pull request merged**
