### PR TITLE
mdbook: upgrade cargo fetcher and cargoSha256

### PR DESCRIPTION
**Pull request by bhipple**
Infra upgrade as part of #79975; ran `nixpkgs-review wip` successfully.

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build mdbook

**Comment by bhipple** [comment]
@worldofpeace I actually did have this script posting that comment automatically in the previous iteration, but per comment from @grahamc himself it's not necessary!

I think posting it kicks the builder to start building instantly, while otherwise it should eventually come through and do it on its own.  Let's wait and see on https://github.com/NixOS/nixpkgs/pull/80399, which has currently been open for 5 minutes with no OfBorg signs of life . . .

**Comment by grahamc** [comment]
image

**Comment by grahamc** [comment]
ofborg's builds aren't poll-based, the builds are triggered once the evaluations complete.

**Comment by grahamc** [comment]
Side note: it used to be required to trigger the builds for any PR where the person opening the PR wasn't pre-approved. ofborg now automatically builds all PRs, no matter who opens them.

**Comment by bhipple** [comment]
Right, but the "Some checks haven't completed yet" (or any status/signs of life at all) didn't pop up for ~25 minutes.  It'd be nice if ofborg immediately set the status as pending on PR opens, so those impatient humans don't try to poke it unnecessarily!  

(If you post the comment, it instantly sets the status to pending, at which point you know to just sit tight.)

**Review by jonringer — APPROVED** [review]
LGTM
shows usage

```
https://github.com/NixOS/nixpkgs/pull/80395
1 package built:
mdbook
```

**Pull request merged**
