### PR TITLE
kde_workspace: Adds missing buildInputs

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
Progress on: https://github.com/NixOS/nixpkgs/issues/28643

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
I think @ttuegel is planning on removing all KDE4 bits.

**Comment by bkchr** [comment]
Ahh, okay, I was unsure about that. But, I also think it is better to remove kde4 :)

**Comment by ttuegel** [comment]
The plan is to remove the last KDE4 packages in December 2017 because at that time, KDE will stop updating kdelibs4. Until then, I have been removing pieces that are no longer needed. If `kde_workspace` is not required by any other package, we should just remove it; otherwise, we should get it back in working condition for now.

**Comment by bkchr** [comment]
I think kde telepathy is the last package that depends on kde_workspace.

**Comment by ttuegel** [comment]
Then we should probably remove both. Neither KDE Telepathy, nor Telepathy itself, have been maintained for some time.

**Comment by fpletz** [comment]
Obsolete due to #29369.

**Pull request closed without merging**
