### PR TITLE
openshot-qt: 2.0.7 -> 2.1.0

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change

Use the latest version.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
This package can actually be installed with setuptools using `buildPythonApplication`.

**Comment by tohl** [comment]
Frederik Rietdijk <notifications@github.com> writes:
> This package can actually be installed with setuptools using
> buildPythonApplication.

Maybe it could be implemented using buildPythonApplication but I did not
figure that out and doing it directly actually worked for me.

@bjornfor: openshot-qt worked for me at the time.  There were some
changes to qt or so recently and it crashes since then.  If your changes
make openshot-qt useable again, I would welcome it.  Otherwise, I would
recommend a cli based melt (mlt nix package) which works very well.

**Comment by FRidh** [comment]
@tohl

I manage to build it with `buildPythonApplication` after patching the source to not write any configuration files in $HOME. However, it can't seem to run without any configuration files. That's just...really bad.

If you want to use this package, I recommend you inform upstream not to write to the users $HOME folder from the `setup.py` file, and also that, when running `openshot-qt` they should *check* whether configuration files are present and if not create them, instead of just aborting.

**Comment by tohl** [comment]
Good find, thanks.  Somehow the few python applications I tried to
package were really bad in this regard.  Unfortunatelly, I am not going
to use openshot-qt and spent my time on the upstream issues so whoever
is interested in it should make the necessary changes to keep it up to
date.  Shall I remove myself as a maintainer?  I guess removing the
whole package would be a shame in case somebody finds it useful.

**Comment by bjornfor** [comment]
@tohl: Thanks for the tip about ```mlt```. According to upstream, there are tons of fixes in this version. I've not used openshot before, but managed to crash the new version pretty quickly. The older version (2.0.7) had the same crashes, so I figured why not update (the old version doesn't have _any_ support, better use latest).

**Pull request merged**
