### PR TITLE
clightning: 0.10.1 -> 0.10.2

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update
- https://github.com/ElementsProject/lightning/releases/tag/v0.10.2

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jb55** [comment]
fails to build for me bacause of mrkd it looks like:
` $ nix-review pr 144537`
```
builder for '/nix/store/dkivy7sslkc5rr1yb63df6hq25xk3lmz-clightning-0.10.2.drv' failed with exit code 2; last 10 log lines:
  printgen wire/peer_printgen.c
  tools/generate-wire.py --page impl tools/test/test_gen.h test_type < tools/test/test_cases > tools/test/test_gen.c.tmp.c
  printgen wire/channel_type_printgen.c
  echo '#include "test_gen.h"' > tools/test/print_gen.c
  tools/generate-wire.py -P --page impl tools/test/print_gen.h test_type < tools/test/test_cases >> tools/test/print_gen.c
  mrkd doc/lightning-cli.1.md
  /nix/store/phqa311klldrcbwid1i22dwnpfc9dnma-bash-5.1-p8/bin/bash: line 1: mrkd: command not found
  make: *** [doc/Makefile:107: doc/lightning-cli.1] Error 127
  make: *** Waiting for unfinished jobs....
  rm tools/test/test_gen.c.tmp.c
cannot build derivation '/nix/store/g70vq1w5cmfcv9hds2i0qxj0bf7lzds5-review-shell.drv': 1 dependencies couldn't be built
error: build of '/nix/store/g70vq1w5cmfcv9hds2i0qxj0bf7lzds5-review-shell.drv' failed
```

**Comment by prusnak** [comment]
Packaged mrkd in fea921d, updated clightning to use mrkd in 9ee3139.

Test build pending.

**Comment by prusnak** [comment]
@grahamcofborg mrkd clightning

**Comment by jb55** [comment]
lgtm!

**Pull request merged**
