### PR TITLE
nodePackages.prisma: 4.13.0 -> 5.0.0

### PR DESCRIPTION
**Pull request by aqrln**
###### Description of changes

* Update `prisma-engines` and `nodePackages.prisma` to 5.0.0: https://github.com/prisma/prisma/releases/tag/5.0.0
* Add myself as a maintainer

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ivan** [comment]
cc maintainers @pimeys @tomhoule @ivan (in the future, @ everyone on the list or they probably won't see it)

**Review by ivan — COMMENTED** [review]
This seems to be working fine for me on x86_64 NixOS 23.05, but I didn't test with NixOS master.

**Comment by aqrln** [comment]
> (in the future, @ everyone on the list or they probably won't see it)

Ah, got it, thanks for the tip.

FWIW, Julius (pimeys) is not working at Prisma anymore so I'm not sure if he's still interested in being a maintainer of the nix package (I can contact him and ask if he'd rather prefer to be removed from the list), and Tom is on sabbatical right now, so you are most probably the only maintainer who can review the PR at the moment.

> This seems to be working fine for me on x86_64 NixOS 23.05, but I didn't test with NixOS master.

I prepared the PR a bit hastily on darwin, I can test it properly on both aarch64 and x86_64 NixOS later today.

**Review by Jolg42 — APPROVED** [review]

**Comment by aqrln** [comment]
Rebased to resolve the conflict in the maintainers list.

**Review by Jolg42 — APPROVED** [review]

**Comment by aqrln** [comment]
Tested this on NixOS, turns out that without `PRISMA_MIGRATION_ENGINE_BINARY` env var Prisma CLI still tries to modify its own directory where it downloads the engines even though `PRISMA_SCHEMA_ENGINE_BINARY` is set:

```
Error: Can't write to /nix/store/1q4ky0y9n112qrj4apn15x3p229f1fsy-prisma-5.0.0/lib/node_modules/prisma/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.
```

Setting both `PRISMA_SCHEMA_ENGINE_BINARY` and `PRISMA_MIGRATION_ENGINE_BINARY` fixes this, but expectedly prints a deprecation warning:

```
prisma:warn Both PRISMA_SCHEMA_ENGINE_BINARY and PRISMA_MIGRATION_ENGINE_BINARY are specified, PRISMA_SCHEMA_ENGINE_BINARY takes precedence. PRISMA_MIGRATION_ENGINE_BINARY is deprecated.
```

I think this is fine as a workaround for now since there's unfortunately already a bunch of warnings anyway on NixOS that are useless and/or wrong, even in the current version on `master` and `nixpkgs-unstable`:

```
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
Warning Precompiled engine files are not available for nixos.
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
```

I'll open an issue for us upstream, and once this is fixed, we can remove the deprecated env var from `postInstall` here.

**Comment by aqrln** [comment]
@ivan this is now built and tested on `aarch64-linux`, `x86_64-linux` and `aarch64-darwin`

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 243100` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prisma-engines</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
In the future, we should move this out of nodePackages

**Pull request merged**
