### PR TITLE
terraform-providers: add passthru.updateScript 

### PR DESCRIPTION
**Pull request by zowoq**
###### Description of changes

Assuming this actually works it may be a bit noisy with multiple daily PRs but with one provider update per PR (built by ofborg automatically) it shouldn't be too much hassle. Will still need to do an occasional manual update for any broken providers.

cc @Mic92 @zimbatm 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]
Ok, let's try it

**Comment by zowoq** [comment]
I'll leave this as a draft until ofborg is fixed.

**Comment by zowoq** [comment]
@ryantm Do we need to do something else for `nixpkgs-update` here? I can't see anything in the `r.ryantm` logs since this was merged?

**Comment by zowoq** [comment]
https://r.ryantm.com/log/terraform-providers.ibm/2022-10-01.log

Not sure why it failed, works with `maintainers/scripts/update.nix`.

That the bot only tried the update because it found it on repology is unexpected, thought it would go through all of `terraform-providers.*` and create PRs for any that ran the `updateScript` successfully.

**Comment by zowoq** [comment]
Going back to using the action: https://github.com/NixOS/nixpkgs/pull/194825

**Pull request merged**
