### PR TITLE
Arcan updates

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 310831` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>arcan</li>
    <li>arcan-all-wrapped</li>
    <li>arcan-wrapped</li>
    <li>cat9</li>
    <li>cat9-wrapped</li>
    <li>durden</li>
    <li>durden-wrapped</li>
    <li>pipeworld-wrapped</li>
    <li>prio-wrapped</li>
    <li>xarcan</li>
  </ul>
</details>

**Comment by useranon350** [comment]
I am curious why this is still using the upstream Tracy and not the forked one currently referenced in the arcan clone.sh. Is the clone.sh out of date?

**Comment by AndersonTorres** [comment]
TBH i did not notice it is now using an in-house copy.

**Comment by useranon350** [comment]
tracy worked for me by disabling libunwind using TRACY_LIBUNWIND_BACKTRACE.

**Comment by AndersonTorres** [comment]
It looks like a workaround rather than a real fixup.

**Comment by useranon350** [comment]
> It looks like a workaround rather than a real fixup. I will keep it this way.

Yes, but it allows keeping Tracy support mostly functional, with only the libunwind backtraces not working. It should also be solvable by correctly adding libunwind to the build/runtime dependencies, but I don't know enough about Nix to debug why the obvious approach was not working.

**Comment by AndersonTorres** [comment]
Is there any serious lack of functionality by not building it with Tracy support?

**Comment by useranon350** [comment]
You cannot use Tracy to debug problems and have to recompile it with print-logging to get equivalent information.

**Comment by AndersonTorres** [comment]
Well, first, debugging is not a thing everyone will be interested. 
Second, ideally it will not affect the regular usage.

Third, let's suppose the Arcan devs require Tracy support in order to send a complete bug report.
Then it looks clear to me that Tracy without Libunwind is not acceptable.

I will ask upstream on Discord before taking any extra action.
As a "workaround", I will try the upstream Tracy as before.

**Comment by AndersonTorres** [comment]
```
       > Cloning Fossil https://chiselapp.com/user/letoram/repository/arcan [c01fceef633c2e61] into /nix/store/835dqzmzrs7xz1hl99iy0iqh7r59b3px-fossil-archive
       > Unable to verify SSL cert from chiselapp.com
       >   subject:   CN = chiselapp.com
       >   issuer:    C = US, O = Let's Encrypt, CN = R11
       >   notBefore: 2024-06-09 03:40:05 UTC
       >   notAfter:  2024-09-07 03:40:04 UTC
       >   sha256:    6cc834918e340d11bef923b212de10c0523e34d756b216a23a68613d53d7fd94
       > accept this cert and continue (y/N/fingerprint)?
       > SSL cert declined
       > Clone done, wire bytes sent: 0  received: 0  remote:
       > server returned an error - clone aborted
       For full logs, run 'nix log /nix/store/mwa8xcynfz1awzw51bggw120m97gdcwp-fossil-archive.drv'.
```

**Comment by pbsds** [comment]
> ```
>        > Cloning Fossil https://chiselapp.com/user/letoram/repository/arcan [c01fceef633c2e61] into /nix/store/835dqzmzrs7xz1hl99iy0iqh7r59b3px-fossil-archive
>        > Unable to verify SSL cert from chiselapp.com
>        >   subject:   CN = chiselapp.com
>        >   issuer:    C = US, O = Let's Encrypt, CN = R11
>        >   notBefore: 2024-06-09 03:40:05 UTC
>        >   notAfter:  2024-09-07 03:40:04 UTC
>        >   sha256:    6cc834918e340d11bef923b212de10c0523e34d756b216a23a68613d53d7fd94
>        > accept this cert and continue (y/N/fingerprint)?
>        > SSL cert declined
>        > Clone done, wire bytes sent: 0  received: 0  remote:
>        > server returned an error - clone aborted
>        For full logs, run 'nix log /nix/store/mwa8xcynfz1awzw51bggw120m97gdcwp-fossil-archive.drv'.
> ```

Still getting this, perhaps `fetchfossil` needs `SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt"`?

**Comment by AndersonTorres** [comment]
How can this be done?

**Comment by pbsds** [comment]
I tested, and `fetchfossil` already does this properly...

**Comment by pbsds** [comment]
I tested the date in the builder, it is within the range. Firefox sees the same certificate on http and accepts it...

**Comment by AndersonTorres** [comment]
A bug in fetchfossil?

**Comment by AndersonTorres** [comment]
Google returned this:

https://groups.google.com/g/comp.lang.tcl/c/fgAfAFfiHPo?pli=1
https://fossil-scm.org/forum/forumpost/4f137684b0fc77af4d635ad60d790e8d56849a2b2a2ebc4c9d87ef8dac28c425
https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce

**Comment by AndersonTorres** [comment]
For now I will  revert  (?) to the older GitHub.

**Comment by AndersonTorres** [comment]
cat9 and durden: I forgot them!

**Comment by pbsds** [comment]
It also seems to include some WIP commit, please ping me when you consider the PR ready :)

**Comment by AndersonTorres** [comment]
@ofborg build arcan-all-wrapped

**Comment by AndersonTorres** [comment]
@ofborg build arcan-all-wrapped

**Comment by AndersonTorres** [comment]
Now it's fine! @pbsds

**Comment by pbsds** [comment]
where is `letoram-tracy` used?

**Comment by AndersonTorres** [comment]
> where is `letoram-tracy` used?
It can be optionally used as an alternative to `tracy`.

Should it be more explicit, e.g. a flag?

**Comment by pbsds** [comment]
Perhaps make the `sources` import a default in the `callPackage` args which thus in turn can leverage the `.override` interface? Then `arcan.override (old: { tracy = old.sources.letoram-tracy; })` becomes possible

**Comment by AndersonTorres** [comment]
`sources` as an argument? Nice!

**Pull request merged**
