### PR TITLE
ansible: 2.9.12 -> 2.10.0; ansible_2_7: drop

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/ansible/ansible/blob/v2.10.0/changelogs/CHANGELOG-v2.10.rst#v2-10-0

Dropping 2.7 as per https://access.redhat.com/support/policy/updates/ansible-engine. I thought we had time until v2.10.0 was released, as the EOL previously was given as:

>  After the release of Ansible Engine 2.10 (Approx. 8-12 months after GA) 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
actions LGTM

However, it appears that `ansible_2_10` no longer installs the "ansible" module, and instead just installs "ansible_base". Not sure if this is an upstream bug, but it breaks all of the other ansible packages

```
https://github.com/NixOS/nixpkgs/pull/95683
7 packages failed to build:
ansible-lint python27Packages.pytest-ansible python37Packages.ansible-kernel python37Packages.ansible-lint python37Packages.pytest-ansible python38Packages.ansible-kernel python38Packages.pytest-ansible

7 packages built:
ansible ansible_2_9 kargo python27Packages.ansible python37Packages.ansible python37Packages.ansible-runner python38Packages.ansible-runner
```

ansible 2.10 site-packages:
```
[nix-shell:/home/jon/.cache/nixpkgs-review/pr-95683]$ ls ./results/ansible/lib/python3.8/site-packages/ansible
ansible/                       ansible_base-2.10.0.dist-info/ ansible_test/
```

**Comment by jonringer** [comment]
This appears to have been intentional: https://github.com/ansible/ansible/commit/2268a37d4d1ee93e7eb1b2eec656251f263adcf2#diff-2eeaed663bd0d25b7e608891384b7298

I would say, keep the 2.9 version in `python-modules` and use an overrideAttrs to create the `2_10` version. Until the related ansible packages have updated to using the latest ansible

**Comment by mweinelt** [comment]
Updated.

**Review by jonringer — APPROVED** [review]
diff LGTM
```
https://github.com/NixOS/nixpkgs/pull/95683
1 package built:
ansible
```

**Pull request merged**
