### PR TITLE
ffmpeg: 2.7.1 -> 2.7.2

### PR DESCRIPTION
**Pull request by andrewrk**
I tested with nix-build -A ffmpeg-full and nix-build -A ffmpeg.

cc @codyopel @Fuuzetsu

### CODE REVIEW

**Comment by garbas** [comment]
ffmpeg causes quite a rebuild (/me looking at travis)

**Comment by Fuuzetsu** [comment]
@vcunat why the mass-rebuild label? It's basically KDE and few other packages. In the past we just merged without the staging roundtrip I believe.

**Comment by vcunat** [comment]
I certainly have no strong opinion on this. It seems impossible (and likely useless) to draw a distinct line anyway.

**Comment by Fuuzetsu** [comment]
I'm just going to press merge if that's fine with you then.

**Pull request merged**
