### PR TITLE
python311Packages.spacy: 3.7.3 -> 3.7.4

### PR DESCRIPTION
**Pull request by sarahec**
## Description of changes

1. Updated version 3.7.3 to 3.7.4. Fixes a TypeError exception when using multiprocessing.
2. Re-enabled pytest with a fix for the `ModuleNotFoundError` -- see #255262 for details.
3. Excluded a small number of tests that use the network. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sarahec** [comment]
`nixpkgs-review` was blocked by an unrelated build error: #290983. Pending PR #290984 fixes it.

**Comment by sarahec** [comment]
FYI @GaetanLepage @fabaff

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289693` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Switching to a draft while I sort out the broken packages

**Review by sarahec — COMMENTED** [review]
`textacy` build solved by filing #290984

**Review by sarahec — COMMENTED** [review]
`textnets` build solved by filing #291938

**Comment by GaetanLepage** [comment]
> Switching to a draft while I sort out the broken packages

Rebasing on `master` should be enough.

**Comment by sarahec** [comment]
Rebase onto master: done.  However, dependency `textnets` still isn't building; [#291938](https://github.com/NixOS/nixpkgs/pull/291938) fixes it and is awaiting review.

**Comment by sarahec** [comment]
The updated `thinc` requirement was merged, so we don't have to patch that in the derivation anymore.

**Comment by sarahec** [comment]
One more fix: I was able to re-enable tests now that a know fix exists for testing Cythonized code. (Thanks to @natsukium for the help!)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289693` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
LGTM ! Everything builds fine.

Thanks @sarahec and @natsukium !

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289693` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Hmmm `textnets` is building on darwin on `master`... This PR seems to break it though...

**Comment by sarahec** [comment]
> Hmmm `textnets` is building on darwin on `master`... This PR seems to break it though...

It appears to be that `pytorch` isn't building and it's a dependency. See the [ofborg](https://logs.ofborg.org/?key=nixos/nixpkgs.291938&attempt_id=45c5ea85-3141-4688-9edb-156de3f98bc9) log. (From `textnets` yesterday.) The rest of the build log looks fine.

**Comment by GaetanLepage** [comment]
Oh wait... I guess that it is a builder problem ^^
```
=========================== short test summary info ============================
FAILED tests/test_textnets.py::test_plot_layout - MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)
FAILED tests/test_textnets.py::test_plot_projected - MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)
FAILED tests/test_textnets.py::test_plot_backbone - MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)
FAILED tests/test_textnets.py::test_plot_scaled - MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)
FAILED tests/test_textnets.py::test_plot_filtered - MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)
============ 5 failed, 25 passed, 1 deselected, 3 warnings in 4.94s ============
```

**Review by natsukium — APPROVED** [review]
LGTM, thanks for your awesome work!

**Pull request merged**
