### PR TITLE
slack: 4.34.115 -> 4.34.120

### PR DESCRIPTION
**Pull request by SebTM**
## Description of changes

Includes not further specified security-update (https://slack.com/intl/de-de/release-notes/linux) with following specification:

> This release includes security improvements. Updating is recommended. | Some security improvements. Upgrading will provide users with security benefits.

Might need a Backport to 23.05 also. // cc @delroth

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delroth** [comment]
How about the versions for other platforms? Did they not get an update?

**Comment by SebTM** [comment]
> How about the versions for other platforms? Did they not get an update?

They did, fixed - unsure about the message but seems unreasonable to skip security-updates because release-numbers are out-of-sync if that has no different impact?

**Review by bjornfor — APPROVED** [review]

**Review by delroth — APPROVED** [review]
Change looks fine and builds on x86_64-linux. Could wait for ofborg eval to complete out of caution, but given the diff, I find it very unlikely that anything would break.

**Comment by delroth** [comment]
Also, since this isn't mentioned otherwise in this PR: usually r-ryantm and the updaterScript would take care of those bumps, but it seems like this particular `update.sh` bails out if Linux and Darwin versions are not in sync (not sure why?). This is why no auto-update PR from r-ryantm got created for this version bump.

**Comment by bjornfor** [comment]
Result of `nixpkgs-review pr 257135` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>slack</li>
  </ul>
</details>

**Comment by SebTM** [comment]
> (not sure why?).
@delroth If you agree with it I would create an MR to remove this limitation

Can also take care of the backport-MR if you like to

**Comment by delroth** [comment]
Please do! (feel free to cc me for reviews)

**Pull request merged**
