### PR TITLE
oraclejdk: remove version 10

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

Oracle JDK 10 is no longer supported in favor of JDK 11. Oracle JDK 11 is not free of charge (except for development, testing, prototyping, or demonstration), and free users are guided to use OpenJDK 11.

Alternative: #47321

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
```
error: while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/.gc-of-borg-outpaths.nix:39:12, called from undefined position:
while evaluating 'g' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/attrsets.nix:267:19, called from undefined position:
while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/top-level/release-lib.nix:121:38, called from undefined position:
while evaluating 'isDerivation' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/attrsets.nix:296:18, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/top-level/release-lib.nix:123:10:
while evaluating 'callPackageWith' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/customisation.nix:108:35, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/top-level/all-packages.nix:7992:17:
while evaluating 'makeOverridable' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/customisation.nix:67:24, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/customisation.nix:112:8:
undefined variable 'jdk10' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/top-level/all-packages.nix:7995:14
```

**Comment by jbgi** [comment]
Can we wait for `openjdk11` to be packaged and merged (someone working on it?) before merging this one?

**Comment by taku0** [comment]
`eclipses` and `bazel_jdk10` depend on `jdk10`. Maybe we should wait for `openjdk11` and/or mark jdk 10 as insecure (#47321) before merging this PR.

**Comment by jerith666** [comment]
started hacking on `openjdk11` at https://github.com/jerith666/nixpkgs/tree/jdk11; not building yet

**Comment by NeQuissimus** [comment]
@jerith666 I'd be very interested in JDK11. Can you make your progress a PR, so it's easier to review? I'll try to help where I can.

**Comment by taku0** [comment]
Added AdoptOpenJDK binary package (#48322).

@jerith666 how about using AdoptOpenJDK build script? https://github.com/AdoptOpenJDK/openjdk-build

**Comment by flokli** [comment]
`jdk10` from `all-packages` is also set to `oraclejdk10` on aarch32 and aarch64.

**Comment by jerith666** [comment]
Okay, I've opened #48326 with what I have so far.  It builds, but still has major TODOs associated with it.  Any help is of course appreciated!  :)

**Comment by fpletz** [comment]
Rebased on top of current master and fixed conflicts.

**Comment by fpletz** [comment]
I'd say let's merge this into master but keep `oraclejdk10` marked as vulnerable from #47321 in 18.09.

**Pull request merged**
