### PR TITLE
renderdoc: fix build failing due to pyside2 requiring python <3.11

### PR DESCRIPTION
**Pull request by irealis**
Should fix the renderdoc build failing with `error: pyside2 not supported for interpreter python3.11` by simply setting it to use python310 instead of latest.

## Things done
- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Benjamin-L** [comment]
Result of `nixpkgs-review pr 263547` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>renderdoc</li>
  </ul>
</details>

I tested the binary with a few traces and it seems to work.

Not sure whether pinning an older python version for application packages is a standard thing to do, but I don't see any other options here. Upstream doesn't intend to add python 3.11 support to pyside2. In order to get renderdoc working with 3.11 it would need to be using pyside6, which would require porting renderdoc to qt6. Unlikely to happen any time soon.

**Review by olivia-fl — APPROVED** [review]

**Comment by lilyinstarlight** [comment]
> Upstream doesn't intend to add python 3.11 support to pyside2.

They actually added support in 5.15.11 earlier this month according to the release notes and Qt PySide issue tracker

Does this package work with #263599 which relaxes the Python 3.10 requirement on `python3Packages.pyside2`?

**Comment by Benjamin-L** [comment]
Good catch! I just tested it with #263599 and it seems to work.

**Comment by lilyinstarlight** [comment]
@irealis Thank you for your contribution! It looks like this might be incidentally fixed by that other PR given pyside2 was just erroneously (ish) limited to Python<=3.10

Do you think you could test and see if renderdoc works on master now for you too since #263599 was merged?

**Comment by irealis** [comment]
Yep, works fine with the changes in #263599. Tested renderdoc briefly and it seems to work fine.

**Pull request closed without merging**
