### PR TITLE
helix-gpt: 0.15 -> 0.25

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

just an update to latest and addition of the aarch64-darwin platform.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
@jpaju do you want to help with the aarch64-darwin hash ? 
(I can also wait for the ci to give me the correct hash upon failure, but if you have time).

**Comment by jpaju** [comment]
Sure, I can do that! To be honest, I'm not entirely sure how to get the hash. Can you give some advice on that? 😇

**Comment by happysalada** [comment]
Of course !
Checkout this branch locally, and try to build helix-gpt on a darwin machine. It will complain of a sha mismatch. The first sha will be aaaaaa , i need the second sha.

Let me know if you need help with any of the details.

Another way could be to run nixpkgs review and paste the failure output, this works as well.

**Comment by jpaju** [comment]
Alright, I cloned the repo and checked out this branch (on M2 Pro Macbook). Then ran:
```
$ cd pkgs/by-name/he/helix-gpt/
$ nix-build -E 'with import <nixpkgs> {}; callPackage ./package.nix {}'
```

The output was:
```
warning: found empty hash, assuming 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
these 3 derivations will be built:
  /nix/store/dmrck22rj9wd1snq955knff12msc8qb7-source.drv
  /nix/store/2yzvlhplkgsfv29brpc6gfin1br0ay8q-helix-gpt-node_modules-0.25.drv
  /nix/store/s5m9sa2w105j54rcm7j6iww12m4cq6wh-helix-gpt-0.25.drv

...

error: hash mismatch in fixed-output derivation '/nix/store/2yzvlhplkgsfv29brpc6gfin1br0ay8q-helix-gpt-node_modules-0.25.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-y8ETFWSg+czhyslKc7muTFRu2q+7eeVyZ7Tea/VCUWY=
error: 1 dependencies of derivation '/nix/store/s5m9sa2w105j54rcm7j6iww12m4cq6wh-helix-gpt-0.25.drv' failed to build
```

So the hash is `y8ETFWSg+czhyslKc7muTFRu2q+7eeVyZ7Tea/VCUWY=`, right?

**Comment by happysalada** [comment]
oh very interesting, the hash is the same as for x86_64-darwin, that should make updates much easier.
I've made the fix, you can test if you want (but it should be fine).

**Comment by jpaju** [comment]
I pulled the updates and it works (at least on my machine 😄). Identical hashes are actually quite interesting, maybe Bun builds binaries for Mac that are run with Rosetta on ARM-based machines 🤷

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 286046` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>helix-gpt</li>
  </ul>
</details>

**Pull request merged**
