### PR TITLE
libglvnd: 1.6.0 -> 1.7.0

### PR DESCRIPTION
**Pull request by Kiskae**
https://gitlab.freedesktop.org/glvnd/libglvnd/-/releases/v1.7.0

## Description of changes

Only change that actually affects nixpkgs is
- [EGL/libeglcurrent: fix crash on library unload](https://gitlab.freedesktop.org/glvnd/libglvnd/-/commit/1f9aff18ba3519ee00b7afa4dfb7ad846f014176)

https://gitlab.freedesktop.org/glvnd/libglvnd/-/compare/v1.6.0...v1.7.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kiskae** [comment]
I'm not sure why this derivation is marked as available for darwin, considering it is not supported and `libGL` has a specific behavior override for darwin.

In addition the meson build file explicitly says it isn't supported:
```meson
if host_machine.system() in ['darwin', 'windows']
  error('Host OS: @0@ is unsupported.'.format(host_machine.system()))
endif
```

**Comment by Kiskae** [comment]
It appears that darwin never had the required assembly for full support and that was made explicit in the build a few months ago, added `badPlatforms` with a link to an active merge request for future updates.

**Comment by Kiskae** [comment]
@vcunat you merged the previous update and I heard primeos is quite busy at the moment. So could you take a look?

**Comment by vcunat** [comment]
It seems to build on darwin at least
https://hydra.nixos.org/job/nixpkgs/trunk/libglvnd.x86_64-darwin
https://hydra.nixos.org/job/nixpkgs/trunk/libglvnd.aarch64-darwin

**Comment by vcunat** [comment]
The darwin error path is only added in 1.7.0 and in build via meson which we don't use (here yet).  But it's quite possible that the darwin builds aren't useful anyway.  They certainly aren't used as the OpenGL provider by default, contrary to our linux builds.

**Comment by vcunat** [comment]
We do have older darwin-specific part in our libglvnd expression, so presumably the combination wasn't completely useless at some point.

**Comment by Kiskae** [comment]
Yeah I just realized meson isn't being used and the errors I saw was the `llvm` build timing out ofborg.

I should probably add a `badPlatforms` for static compilation, since that explicitly isn't supported by glvnd.

I'm not sure what the darwin-specific code is used for and I suspect it is because of other packages depending on `libglvnd` while they actually should depend on `libGL`. But its probably fine to leave alone for now.

**Pull request merged**
