### PR TITLE
milkytracker: adopt, 1.03.00 -> 1.04.00

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Description of changes

~~Does not work yet: https://github.com/milkytracker/MilkyTracker/issues/316~~
Issue is resolved.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by coderofsalvation** [comment]
Hi opna, is it correct that you have some sort of darwin builder setup?

**Comment by OPNA2608** [comment]
> what would a terminal-snippet in milkytracker's README.md look like to setup a dev-environment for milkytracker devs which already have nix installed

`nix-shell '<nixpkgs>' -A milkytracker` will drop you into a shell with all inputs for the `milkytracker` derivation from your `nixpkgs` channel.

For maintenance on your end though, it might make sense to instead have a version of the `default.nix` in your repo. Or a `shell.nix` for more granular control over the shell. Or a `flake.nix` for the fancy new way of doing all of these things.

I'd recommend you join one of the [Nix/Nixpkgs/NixOS communities](https://nixos.org/community/), this might not be the best place to ask these questions.

**Comment by OPNA2608** [comment]
Building on Darwin requires a real Xcode installation for `ibtool`, which I unfortunately don't have on my macOS system. Hoping that I can get it done via only Ofborg's build tests, otherwise we'll go back to Linux-only.

**Comment by OPNA2608** [comment]
Ofborg says
```
Compiling /tmp/nix-build-milkytracker-1.04.00.drv-0/source/src/tracker/cocoa/resources/Application.xib
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
make[2]: *** [src/tracker/CMakeFiles/tracker.dir/build.make:1517: src/tracker/MilkyTracker.app/Contents/MacOS/MilkyTracker] Error 1
```
So back to Linux-only we go. :cry:

**Pull request merged**
