### PR TITLE
updates pythonPackages.channels and dependencies

### PR DESCRIPTION
**Pull request by lsix**
###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@lsix thanks for moving the files. If I am correct we always use `<package>default.nix` in Nixpkgs instead of `<package>.nix`.

**Comment by lsix** [comment]
Yes, this is what is done across `nixpkgs`. I do not know why I had the impression that `pkgs/development/python-modules` did not follow that rule. I’ll change that ASAP.

**Comment by lsix** [comment]
@FRidh updated. I still have a `nox-review pr` running, I’ll update the WIP  tag once it finishes.

**Comment by lsix** [comment]
@FRidh I have removed the twisted related updates for the time beings since it too much thinks get broken. I’ll work on it separately. The channels / daphne part is ok.

**Pull request merged**
