### PR TITLE
google-cloud-sdk: 222 -> 229

### PR DESCRIPTION
**Pull request by dtzWill**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
@dtzWill Looks like it builds fine; did you test it? Do you want to merge it before the feature freeze?

**Comment by dtzWill** [comment]
I don't know how to test it properly, sorry.  I don't have a need for merging before branch personally.

**Comment by periklis** [comment]
Why not version 235?

**Comment by dtzWill** [comment]
It wasn't out when I wrote this PR, probably? :)

(agreed might as well move to 235)

**Comment by c0bw3b** [comment]
Obsolete since #59129

**Pull request closed without merging**
