### PR TITLE
python3{8,9}Packages.scikit-learn: 1.0.1 -> 1.0.2

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
currently does not build on hydra and there is a [new release](https://github.com/scikit-learn/scikit-learn/releases/tag/1.0.2)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
i am not sure about backporting, because for 21.11 it does not build as well...

**Comment by drewrisinger** [comment]
@Stunkymonkey nixos-21.11 is on ``scikit-learn==0.24.1``, so it feels outside the scope of this PR (or any automatic backport). Bumping it to v1.0.X might require the change to go through staging, and that's above my paygrade whether that should happen.

**Comment by Stunkymonkey** [comment]
Thanks for clarification. I did not see your PR. If it is fixed, i am against back porting.

**Comment by FRidh** [comment]
@GrahamcOfBorg build python3.pkgs.scikitlearn

**Comment by FRidh** [comment]
This PR should indeed not be backported as a fix for 0.24 is already in 21.11.

**Comment by Stunkymonkey** [comment]
@FRidh builds on all platforms.

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commit LGTM
* [x] Builds via ofborg on all platforms

**Pull request merged**
