### PR TITLE
home-assistant-cli: init at 0.3.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @peterhoeg @fpletz 
Feel free to notify other Home Assistant users, this seems like a nice addition to the ecosystem.

### CODE REVIEW

**Comment by peterhoeg** [comment]
I had this on my list to package, so :+1: from here!

**Comment by fpletz** [comment]
Cool! :+1:

**Comment by peterhoeg** [comment]
I can't build it here - install tests fail. Only works with ```doCheck = false;```.

**Comment by fpletz** [comment]
Weird, worked for me.

**Comment by dotlambda** [comment]
I don't see any issue: https://hydra.nixos.org/eval/1496677?filter=home-assistant&compare=1496636&full=

@peterhoeg Do you have a log?

**Comment by peterhoeg** [comment]
On unstable with the commit cherry-picked:

https://gist.github.com/peterhoeg/138ef25d816ae458435d7cec89683d2a

**Pull request merged**
