### PR TITLE
python312Packages.triton*: 3.0.0 -> 3.1.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Diff: https://github.com/triton-lang/triton/compare/91f24d87e50cb748b121a6c24e65a01187699c22...cf34004b8a67d290a962da166f5aa2fc66751326

Changelog: [one day maybe](https://github.com/triton-lang/triton/issues/3535)

cc @SomeoneSerge

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DerDennisOP** [comment]
lgtm

**Comment by GaetanLepage** [comment]
It builds lol. First try X)

**Comment by SomeoneSerge** [comment]
```
❯ nom build -I nixpkgs=https://github.com/GaetanLepage/nixpkgs/archive/openai-triton.tar.gz -f "<nixpkgs>" python3Packages.triton.gpuCheck
...
triton-pytest> FAILED language/test_line_info.py::test_line_info[dot_combine] - subprocess.CalledProcessError: Command '['/nix/store/97ba8v5ffpm7r7z8grpaqj...
triton-pytest> FAILED language/test_subprocess.py::test_print[device_print_large-int32] - assert False
triton-pytest> FAILED operators/test_flash_attention.py::test_op[True-True-dtype0-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[True-True-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[True-False-dtype0-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[True-False-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[False-True-dtype0-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[False-True-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[False-False-dtype0-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED operators/test_flash_attention.py::test_op[False-False-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
triton-pytest> FAILED tools/test_aot.py::test_compile_link_matmul_no_specialization - subprocess.CalledProcessError: Command '['./test', '/build/tmpd7xmo9c2/a.cs...
triton-pytest> FAILED tools/test_aot.py::test_compile_link_matmul - subprocess.CalledProcessError: Command '['./test', '/build/tmph4nb393y/a.cs...
triton-pytest> FAILED tools/test_aot.py::test_launcher_has_no_available_kernel - AssertionError: assert -11 == -6
triton-pytest> FAILED tools/test_aot.py::test_compile_link_autotune_matmul - subprocess.CalledProcessError: Command '['./test_0', '/build/tmp0g352yw6/a....
triton-pytest> === 23 failed, 9134 passed, 2196 skipped, 181 warnings in 1224.10s (0:20:24) ===
error: builder for '/nix/store/gvcldv6vz16xkr2cpjrwp3a76isg00ph-triton-pytest-3.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED operators/test_flash_attention.py::test_op[True-False-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
       > FAILED operators/test_flash_attention.py::test_op[False-True-dtype0-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
       > FAILED operators/test_flash_attention.py::test_op[False-True-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
       > FAILED operators/test_flash_attention.py::test_op[False-False-dtype0-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
       > FAILED operators/test_flash_attention.py::test_op[False-False-dtype1-2-4-512-128] - triton.runtime.errors.OutOfResources: out of resource: shared memory, Requi...
       > FAILED tools/test_aot.py::test_compile_link_matmul_no_specialization - subprocess.CalledProcessError: Command '['./test', '/build/tmpd7xmo9c2/a.cs...
       > FAILED tools/test_aot.py::test_compile_link_matmul - subprocess.CalledProcessError: Command '['./test', '/build/tmph4nb393y/a.cs...
       > FAILED tools/test_aot.py::test_launcher_has_no_available_kernel - AssertionError: assert -11 == -6
       > FAILED tools/test_aot.py::test_compile_link_autotune_matmul - subprocess.CalledProcessError: Command '['./test_0', '/build/tmp0g352yw6/a....
       > === 23 failed, 9134 passed, 2196 skipped, 181 warnings in 1224.10s (0:20:24) ===
       For full logs, run 'nix log /nix/store/gvcldv6vz16xkr2cpjrwp3a76isg00ph-triton-pytest-3.1.0.drv'.
┏━ 1 Errors: 
┃ error: builder for '/nix/store/gvcldv6vz16xkr2cpjrwp3a76isg00ph-triton-pytest-3.1.0.drv' failed with exit code 1;
┣━ Dependency Graph showing 1 of 2 roots:
┃          ┌─ ✔ triton-llvm-19.1.0-rc1 ⏱ 55m57s
┃       ┌─ ✔ python3.12-triton-3.1.0 ⏱ 5m0s
┃       ├─ ✔ magma-2.7.2 ⏱ 1h10m27s
┃    ┌─ ✔ python3.12-torch-2.4.1 ⏱ 1h30m28s
┃ ┌─ ✔ python3-3.12.6-env ⏱ 2s
┃ ├─ ⏸ source
┃ ⚠ triton-pytest-3.1.0 failed with exit code 1 after ⏱ 20m27s in checkPhase
```

No regression compares to the previous PR

**Comment by GaetanLepage** [comment]
> No regression compares to the previous PR

Is it sarcastic or was this test really already broken ?

**Comment by SomeoneSerge** [comment]
> Is it sarcastic or was this test really already broken ?

An understandable confusion! Yes it was broken, which I just took as a given since we've never run the pytest suite before ("pytorch is our test"):

> ... https://github.com/NixOS/nixpkgs/pull/328247#issuecomment-2411955895
> I currently observe about 20 tests failing and spitting out junk: https://gist.github.com/SomeoneSerge/f9bd9ececc3a16438bd087edadf0fef4

The "OutOfResource" parts can be probably put in disabledTests, but iirc a few tests spat out outright gibberish

**Comment by DerDennisOP** [comment]
> > Is it sarcastic or was this test really already broken ?
> 
> An understandable confusion! Yes it was broken, which I just took as a given since we've never run the pytest suite before ("pytorch is our test"):
> 
> > ... [#328247 (comment)](https://github.com/NixOS/nixpkgs/pull/328247#issuecomment-2411955895)
> > I currently observe about 20 tests failing and spitting out junk: https://gist.github.com/SomeoneSerge/f9bd9ececc3a16438bd087edadf0fef4
> 
> The "OutOfResource" parts can be probably put in disabledTests, but iirc a few tests spat out outright gibberish

OutOfResource works for me, I guess you need more resources. If I build it on 64C/128T CPU with a GPU piped into the nix builder it works.

**Review by DerDennisOP — APPROVED** [review]

**Review by SomeoneSerge — APPROVED** [review]

**Comment by SomeoneSerge** [comment]
> The "OutOfResource" Tests work for me, I guess you need more resources. If I build it on 64C/128T CPU with a GPU piped into the nix builder it works.

🥲 24G VRAM too little, rtx 3090 too old

May I ask what your GPU is?

**Comment by SomeoneSerge** [comment]
> GPU: 1x H100

Maybe we should consider marking tests with a grading of "system features", e.g. based on vram size (e.g. `"cuda-80gb"`). We're not doing that yet because there would be many orthogonal dimensions, like cuda capabilities. An alternative is to hard-code GPU names for derivations where it matters

**Comment by DerDennisOP** [comment]
> > GPU: 1x H100
> 
> Maybe we should consider marking tests with a grading of "system features", e.g. based on vram size (e.g. `"cuda-80gb"`). We're not doing that yet because there would be many orthogonal dimensions, like cuda capabilities. An alternative is to hard-code GPU names for derivations where it matters

in my [nix-ai](https://git.wavelens.io/public/nix-ai) project, I'm using hard-coded GPU names. Its not optimal but the best solution I could find.

**Pull request merged**
