### PR TITLE
upower: 0.99.7 -> 0.99.8

### PR DESCRIPTION
**Pull request by dtzWill**
Bump.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jtojnar — COMMENTED** [review]
Could we ask upstream to upload the tarball to the server? GitLab URLs are not predictable.

**Comment by jtojnar** [comment]
The autogenerated tarballs are just git snapshots, these artefacts are most likely dost tarball

**Comment by jtojnar** [comment]
I would rather if we could use predictable tarball location, opened an issue upstream: https://gitlab.freedesktop.org/upower/upower/issues/80

**Comment by c0bw3b** [comment]
On top of it, 0.99.8 has regressions with [accessing udev events](https://gitlab.freedesktop.org/upower/upower/commit/fe356951a9d45fee73036aaa72661f0319dffba3) and [keyboard backlight support](https://gitlab.freedesktop.org/upower/upower/commit/0a9d9ab4949effb20e77aa52e7b4ee07e776fc0d).

One alternative ([taken from Arch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/upower)) would be to `fetchgit` and `fetchpatch` from the repo clone at https://cgit.freedesktop.org/upower/

**Comment by dtzWill** [comment]
Closing in favor of #49395 (which I believe includes fixes for the mentioned regressions).

**Pull request closed without merging**
