### PR TITLE
python3Packages.spdx-tools: 0.7.1 -> 0.8.0

### PR DESCRIPTION
**Pull request by tobim**
## Description of changes

https://github.com/spdx/tools-python/releases/tag/v0.8.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 248286` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>python310Packages.scancode-toolkit</li>
    <li>python310Packages.scancode-toolkit.dist</li>
    <li>python311Packages.scancode-toolkit</li>
    <li>python311Packages.scancode-toolkit.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.spdx-tools</li>
    <li>python310Packages.spdx-tools.dist</li>
    <li>python311Packages.spdx-tools</li>
    <li>python311Packages.spdx-tools.dist</li>
  </ul>
</details>

**Comment by tobim** [comment]
`scancode-toolkit` has an open PR: https://github.com/nexB/scancode-toolkit/pull/3456.
I didn't find anything for `checkov`.
Should we just wait?

**Comment by fabaff** [comment]
`checkov` is released every often. I guess that it's only a matter of time to get support for `spdx-tools` >= 0.8.

https://github.com/bridgecrewio/checkov/issues/5428

In a worth-case scenario I will override `spdx-tools` for `checkov`.

**Comment by fabaff** [comment]
`checkov` has no support for `spdx-tool>=0.8.0`.

**Pull request merged**
