### PR TITLE
pkgs/stdenv/darwin: move bootstrap files definitions to bootstrap-fil…

### PR DESCRIPTION
**Pull request by trofi**
…es/ directory

The change moves definition of bootstrap files slightly closer to `linux` structure to eventually allow those to update in bulk: https://github.com/NixOS/nixpkgs/issues/253713

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
On `linux` host tested the following, it's a no-op:

    $ nix build -f. hello --argstr system x86_64-darwin; nix build -f. hello --argstr system aarch64-darwin;

My mild worry is on `inherit (localSystem) system;`. I think it's removal should be a no-op on `darwin` as well. But mentioning it just in case.

**Review by reckenrode — APPROVED** [review]
`nix-instantiate . -A stdenv` returns the same paths for aarch64- and x86_64-darwin before and after cherry-picking this PR onto master. More alignment with Linux is usually a good thing. LGTM

**Comment by lovesegfault** [comment]
@ofborg eval

**Review by toonn — APPROVED** [review]
I think `<nix/fetchurl.nix>` refers to [this fetchurl.nix](https://github.com/NixOS/nix/blob/44a0d044832050cc419d844e73b8e021b0643357/src/libexpr/fetchurl.nix#L4)? And that indicates the `system` argument as obsolete, so it's probably safe to drop.

LGTM

**Pull request merged**
