### PR TITLE
matrix-synapse: 1.39.0 -> 1.40.0

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Motivation for this change

https://github.com/matrix-org/synapse/releases/tag/v1.40.0

###### Things done

I tested the updated method for creating the `homeserver` executable and it is working on my local machine.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ma27 — CHANGES_REQUESTED** [review]
The test is failing:

```
serverpostgres # [    7.829342] matrix-synapse-pre-start[919]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 16: import: command not found
serverpostgres # [    7.830922] matrix-synapse-pre-start[920]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 17: import: command not found
serverpostgres # [    7.832440] matrix-synapse-pre-start[921]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 18: import: command not found
serverpostgres # [    7.834346] matrix-synapse-pre-start[922]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 19: from: command not found
serverpostgres # [    7.835843] matrix-synapse-pre-start[923]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 21: from: command not found
serverpostgres # [    7.837369] matrix-synapse-pre-start[924]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 22: from: command not found
serverpostgres # [    7.838910] matrix-synapse-pre-start[925]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 23: from: command not found
serverpostgres # [    7.840128] matrix-synapse-pre-start[926]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 24: from: command not found
serverpostgres # [    7.841611] matrix-synapse-pre-start[927]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 26: import: command not found
serverpostgres # [    7.843014] matrix-synapse-pre-start[928]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 27: import: command not found
serverpostgres # [    7.844254] matrix-synapse-pre-start[929]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: line 28: from: command not found
serverpostgres # [    7.845611] matrix-synapse-pre-start[918]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/homeserver: line 29: syntax error near unexpected token `('
serverpostgres # [    7.847239] matrix-synapse-pre-start[918]: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/.homeserver-wrapped: /nix/store/4yx53c2gzh4vck6n27sb17jg88nhq45i-matrix-synapse-1.40.0/bin/homeserver: line 29: `from synapse.api.urls import ('

```

Seems as if `$out/bin/homeserver` (the wrapper) tries to execute the wrapped script as bash code.

**Review by Ma27 — CHANGES_REQUESTED** [review]
The current PYTHONPATH-hack seems wrong to me since the module injects another PYTHONPATH which contains additional plugins. In my case this e.g. breaks the LDAP integration which I enabled via `plugins = [ config.services.matrix-synapse.package.plugins.matrix-synapse-ldap3 ];`

**Comment by ajs124** [comment]
The (hacky) solution I came up with was to add this: `sed -i -e '1i#!/usr/bin/env python3' synapse/app/homeserver.py` to `postPatch`. Feel free to take it, if you don't have any better/cleaner solution.

**Comment by Ma27** [comment]
Fixed the problem. cc @ajs124 @sumnerevans

**Comment by sumnerevans** [comment]
LGTM!

**Pull request merged**
