### PR TITLE
libsForQt5.quazip: 0.9.1 -> 1.1

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

Update quazip!

Technically the upstream maintainer says that 1.x and 0.x should be packaged separately, but with only a few* fixes, all currently working* packages can be made to build with Quazip 1.x.

Obsoletes https://github.com/NixOS/nixpkgs/pull/103254.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
Result of `nixpkgs-review pr 121463` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>ideamaker</li>
    <li>screencloud</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>gmic-qt-krita</li>
    <li>keepassxc</li>
    <li>krita</li>
    <li>libsForQt5.quazip (libsForQt515.quazip ,plasma5Packages.quazip)</li>
    <li>libsForQt512.quazip</li>
    <li>libsForQt514.quazip</li>
    <li>nomacs</li>
    <li>openboard</li>
    <li>qmapshack</li>
    <li>teamspeak_client</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121463` at beca3d2c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>ideamaker</li>
    <li>screencloud</li>
  </ul>
</details>
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>gmic-qt-krita</li>
    <li>krita</li>
  </ul>
</details>
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>keepassxc</li>
    <li>libsForQt5.quazip (libsForQt515.quazip ,plasma5Packages.quazip)</li>
    <li>libsForQt512.quazip</li>
    <li>libsForQt514.quazip</li>
    <li>nomacs</li>
    <li>openboard</li>
    <li>qmapshack</li>
    <li>teamspeak_client</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/applications/gis/qmapshack/default.nix:24:5:
```
   |
24 |     "${src}/FindPROJ4.patch"
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/quazip/default.nix:20:3:
```
   |
20 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

**Comment by Mindavi** [comment]
Result of `nixpkgs-review pr 121463` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>ideamaker</li>
    <li>screencloud</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>gmic-qt-krita</li>
    <li>keepassxc</li>
    <li>krita</li>
    <li>libsForQt5.quazip (libsForQt515.quazip ,plasma5Packages.quazip)</li>
    <li>libsForQt512.quazip</li>
    <li>libsForQt514.quazip</li>
    <li>nomacs</li>
    <li>openboard</li>
    <li>qmapshack</li>
    <li>teamspeak_client</li>
  </ul>
</details>

I tried nomacs and it's zip functionality (or at least, I tried to ensure I used that). Everything seems to work fine for nomacs.

Other checks:

- [x] keepassxc: runs and opens password database
- [x] gmic_krita_qt: runs, gives warning that don't appear to be related to quazip
- [x] krita: runs, crashes with segfault on shutdown (probably unrelated though?)
- [x] qmapshack: runs
- [ ] teamspeak_client: ./results/teamspeak_client/bin/ts3client: error while loading shared libraries: /nix/store/fw6542lhdfyzhkwn9d41q53gavnvmglw-quazip-1.1/lib/libquazip5.so: cannot open shared object file: No such file or directory -> should be `libquazip1-qt5.so`

<details><summary>Crash log krita (shutdown crash)</summary>

```
[nix-shell:~/.cache/nixpkgs-review/pr-121463]$ ./results/krita/bin/krita
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
QObject::startTimer: Timers cannot have negative intervals
/nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/krita-python-libs/krita added to PYTHONPATH
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
Segmentation fault (core dumped)
```

</details>

**Comment by lukegb** [comment]
I think possibly my declaring ideamaker as broken was a bit premature; I was testing on a system with broken OpenGL and didn't realise until just now. I'm doing some more testing (oops)

Thanks for the review!

**Comment by Mindavi** [comment]
Result of `nixpkgs-review pr 121463` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>ideamaker</li>
    <li>screencloud</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>gmic-qt-krita</li>
    <li>keepassxc</li>
    <li>krita</li>
    <li>libsForQt5.quazip (libsForQt515.quazip ,plasma5Packages.quazip)</li>
    <li>libsForQt512.quazip</li>
    <li>libsForQt514.quazip</li>
    <li>nomacs</li>
    <li>openboard</li>
    <li>qmapshack</li>
    <li>teamspeak_client</li>
  </ul>
</details>

I tried nomacs and it's zip functionality (or at least, I tried to ensure I used that). Everything seems to work fine for nomacs.

Other checks:

- [x] keepassxc: runs and opens password database
- [x] gmic_krita_qt: runs, gives warning that don't appear to be related to quazip
- [x] krita: runs, crashes with segfault on shutdown (probably unrelated though?)
- [x] qmapshack: runs
- [ ] teamspeak_client: ./results/teamspeak_client/bin/ts3client: error while loading shared libraries: /nix/store/fw6542lhdfyzhkwn9d41q53gavnvmglw-quazip-1.1/lib/libquazip5.so: cannot open shared object file: No such file or directory -> should be `libquazip1-qt5.so`

<details><summary>Crash log krita (shutdown crash)</summary>

```
[nix-shell:~/.cache/nixpkgs-review/pr-121463]$ ./results/krita/bin/krita
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
qt.gui.icc: fromIccProfile: Invalid ICC profile - invalid white-point
QPngHandler: Failed to parse ICC profile
QObject::startTimer: Timers cannot have negative intervals
/nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/krita-python-libs/krita added to PYTHONPATH
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:127: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:132: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:102: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:76: TypeError: Cannot read property 'imageForButton' of null
qrc:/touchstrip.qml:81: TypeError: Cannot read property 'imageForButton' of null
Segmentation fault (core dumped)
```

</details>

<details><summary>Crash log krita (shutdown crash), valgrind</summary>

```
==19088== Invalid read of size 4
==19088==    at 0x73BE0E3: QString::~QString() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C2385: QMapNode<long long, QString>::destroySubTree() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C23DD: QMapNode<long long, QString>::destroySubTree() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C25E6: QMapData<long long, QString>::destroy() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C276B: QMap<long long, QString>::~QMap() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x9F5EBF5: __cxa_finalize (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==    by 0x73BA4E2: ??? (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x400FD46: _dl_fini (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/ld-2.32.so)
==19088==    by 0x9F5E5E6: __run_exit_handlers (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==    by 0x9F5E799: exit (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==    by 0x9F47DF3: (below main) (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==  Address 0x361a25a0 is not stack'd, malloc'd or (recently) free'd
==19088== 
==19088== 
==19088== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==19088==  Access not within mapped region at address 0x361A25A0
==19088==    at 0x73BE0E3: QString::~QString() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C2385: QMapNode<long long, QString>::destroySubTree() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C23DD: QMapNode<long long, QString>::destroySubTree() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C25E6: QMapData<long long, QString>::destroy() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x73C276B: QMap<long long, QString>::~QMap() (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x9F5EBF5: __cxa_finalize (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==    by 0x73BA4E2: ??? (in /nix/store/4rqhrccgh54x6y8412hc8cj373whxvpg-krita-4.4.3/lib/libkritawidgetutils.so.20.0.0)
==19088==    by 0x400FD46: _dl_fini (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/ld-2.32.so)
==19088==    by 0x9F5E5E6: __run_exit_handlers (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==    by 0x9F5E799: exit (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==    by 0x9F47DF3: (below main) (in /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc-2.32.so)
==19088==  If you believe this happened as a result of a stack
==19088==  overflow in your program's main thread (unlikely but
==19088==  possible), you can try to increase the size of the
==19088==  main thread stack using the --main-stacksize= flag.
==19088==  The main thread stack size used in this run was 16777216.
==19088== 
==19088== HEAP SUMMARY:
==19088==     in use at exit: 17,394,950 bytes in 33,634 blocks
==19088==   total heap usage: 8,100,757 allocs, 8,067,123 frees, 3,213,587,322 bytes allocated
==19088== 
==19088== LEAK SUMMARY:
==19088==    definitely lost: 15,008 bytes in 296 blocks
==19088==    indirectly lost: 7,160,818 bytes in 10,341 blocks
==19088==      possibly lost: 1,301,632 bytes in 416 blocks
==19088==    still reachable: 8,917,492 bytes in 22,581 blocks
==19088==                       of which reachable via heuristic:
==19088==                         newarray           : 80 bytes in 2 blocks
==19088==         suppressed: 0 bytes in 0 blocks
==19088== Rerun with --leak-check=full to see details of leaked memory
==19088== 
==19088== Use --track-origins=yes to see where uninitialised values come from
==19088== For lists of detected and suppressed errors, rerun with: -s
==19088== ERROR SUMMARY: 26257 errors from 1875 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

</details>

Note that I'm not using krita, and these errors / crashes seem unrelated (but maybe good to check if it was already so crashy).

**Review by Mindavi — CHANGES_REQUESTED** [review]
I'd suggest to look at the teamspeak client (I'm not using it, but can imagine that some people use it). Otherwise, looks good to me.

**Comment by lukegb** [comment]
> I'd suggest to look at the teamspeak client (I'm not using it, but can imagine that some people use it). Otherwise, looks good to me.

Yeah, I'm one of the maintainers for it. I should probably at least make sure my _own_ changes don't break it ;)

**Comment by lukegb** [comment]
Ran ts3client, joined a server, seemed to work.

**Review by Mindavi — APPROVED** [review]

**Pull request merged**
