### PR TITLE
retroarch: update cores

### PR DESCRIPTION
**Pull request by kolbycrouch**
###### Motivation for this change

Cores for RetroArch were old and incomplete. Added most missing cores and updated existing ones.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthewbauer** [comment]
Looks good!

**Comment by matthewbauer** [comment]
@grahamcofborg build  libretro

**Comment by kolbycrouch** [comment]
I noticed a build failure during the check for one of the cores, and I've fixed it locally now.

A couple of cores are broken and I forgot to mark them as such. 

Should I wait for this to review or submit a new PR and get this one closed?

**Comment by aanderse** [comment]
Please amend your commit and continue with this PR.

**Comment by kolbycrouch** [comment]
> Please amend your commit and continue with this PR.

Alright, I think I did it properly. Hopefully this fixes things.

**Comment by aanderse** [comment]
@kolbycrouch I should have been more explicit. At this point can you please squash into a single commit? I'll try to compile these all and test a few in the next couple days.

If anyone else gets around to it before me please comment what you compiled and tested.

**Comment by kolbycrouch** [comment]
> @kolbycrouch I should have been more explicit. At this point can you please squash into a single commit? I'll try to compile these all and test a few in the next couple days.
> 
> If anyone else gets around to it before me please comment what you compiled and tested.

Sure thing. Sorry I've been gone from my machine all weekend, I'll try to get this done soon.

I have a question before I do though. Is marking cores that fail to build as "broken" the proper method?

I enable all cores via nixpkgs.config.retroarch and doing that causes nixos-rebuild to fail.

**Comment by aanderse** [comment]
Yeah marking a package that won't compile as `broken` is what you should do in this scenario. Thanks!

**Comment by kolbycrouch** [comment]
Well, I've deleted my old fork and made a new one which apparently isn't the proper method.

Now this PR is referencing an unknown repository.

Is there a way to fix this or must I open a new PR?

**Comment by aanderse** [comment]
@kolbycrouch this appears to be your scenario: https://stackoverflow.com/a/53383772

**Comment by kolbycrouch** [comment]
@aanderse I did as you suggested. It worked for bringing back my old fork, and I was able to squash the commits. However, github still says it's trying to merge from an unknown repository, and the only solutions for that I've found online were to close the PR and start a new one. Is this what I should do?

**Comment by aanderse** [comment]
@kolbycrouch yeah I don't know and I'm not going to put any time and energy into it. Please go ahead and create a new PR.

Future readers: answers on how to fix this appreciated.

**Pull request closed without merging**
