### PR TITLE
Update all skaware packages (s6, s6-rc, execline etc)

### PR DESCRIPTION
**Pull request by svanderburg**
###### Motivation for this change

This pull request updates all [skaware software packages](https://skarnet.org/software), most notably: the `s6` supervising system, the underlying libraries and related tools.

I have successfully tested this against my work in progress branch of the very experimental [nix-processmgmt](https://github.com/svanderburg/nix-processmgmt) framework that adds `s6-rc` support: https://github.com/svanderburg/nix-processmgmt/tree/s6-rc

In addition to updating all the packages to their latest versions, I have also packaged `s6-linux-init` that depends on newer versions of `execline` and `skalibs`.

I have commit access to Nixpkgs, but since I'm still a relative newbie to `s6`, I'd like the community to take a look at this update first, just to be sure that I don't break anything important.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110381` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>fdtools: log <a href="https://termbin.com/6bxy">https://termbin.com/6bxy</a></li>
  </ul>
</details>
<details>
<summary>
12 packages built:
</summary>
<ul>
<li>execline (skawarePackages.execline)</li>
<li>nsss (skawarePackages.nsss)</li>
<li>s6 (skawarePackages.s6)</li>
<li>s6-dns (skawarePackages.s6-dns)</li>
<li>s6-linux-init (skawarePackages.s6-linux-init)</li>
<li>s6-linux-utils (skawarePackages.s6-linux-utils)</li>
<li>s6-networking (skawarePackages.s6-networking)</li>
<li>s6-portable-utils (skawarePackages.s6-portable-utils)</li>
<li>s6-rc (skawarePackages.s6-rc)</li>
<li>sdnotify-wrapper (skawarePackages.sdnotify-wrapper)</li>
<li>skalibs (skawarePackages.skalibs)</li>
<li>utmps (skawarePackages.utmps)</li>
</ul>
</details>

**Comment by svanderburg** [comment]
@SuperSandro2000 I just tried building `fdtools` locally, and it seems to work for me. If I look at the output log of the build above, the I see that the log is truncated. This suggests there is an infrastructure problem, not a build problem.

**Comment by SuperSandro2000** [comment]
I think this is the error:

```
Making compile/host/vc-switch
/nix/store/wcz8lsibkw2nikdb0bjl22p75lfwahzr-binutils-2.35.1/bin/ld: ./compile/host/vc-switch.o: in function `main':
vc-switch-linux.c:(.text.startup+0x182): undefined reference to `pathexec0'
collect2: error: ld returned 1 exit status

Making include/fdtools.h

Making library/fdtools.a
```

**Comment by svanderburg** [comment]
@SuperSandro2000 Ah I see, the output is indeed a bit weird. I think I can provide a fix for this.

**Comment by svanderburg** [comment]
@SuperSandro2000 I have patched `fdtools` to make it compile against the latest `skalibs`. Some preliminary tests show that the package works.

The upstream maintainer does not seem to offer a newer version, so maybe we can submit the patch.

@Profpatsch I'm not a `fdtools` user and I have noticed that you are the maintainer. Let me know if there are any objections in getting this pull request integrated.

**Review by bqv — APPROVED** [review]
My testing proves successful - I'm satisfied

**Comment by Profpatsch** [comment]
Thanks for doing this, I started last week but was a bit off-put by the execline exec changes. Checking …

**Comment by Profpatsch** [comment]
Can we move the updates into one commit with the content of https://www.mail-archive.com/skaware@list.skarnet.org/msg01510.html as the commit description? Then add the s6-linux-init as a commit on top. Makes blaming a lot easier, and they are conceptually one bump.

**Comment by Profpatsch** [comment]
Let me do it

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build skawarePackages

**Comment by Profpatsch** [comment]
Everything looks reasonably buildy-looking, let’s merge.

**Comment by svanderburg** [comment]
@Profpatsch Thanks! Squashing all the package update commits looks fine to me. All that I needed was the `s6-linux-init` pacakge :P

**Pull request merged**
