### PR TITLE
citrix-receiver: decomission in favor of citrix-workspace.

### PR DESCRIPTION
**Pull request by obadz**
Already documented in #64645

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Ma27 @FRidh

### CODE REVIEW

**Review by FRidh — APPROVED** [review]

**Review by Ma27 — COMMENTED** [review]
Change itself seems fine :+1: 

But can you please mention this in the changelog for 19.09 and remove the references to `citrix_receiver` in `doc/package-specific-user-notes.xml`? :)

**Comment by lheckemann** [comment]
Should this be backported to 19.09?

**Comment by Ma27** [comment]
Yes since citrix-receiver 13.10 for Linux will be EOLed in december 2019: https://www.citrix.de/support/product-lifecycle/milestones/receiver.html

Would've done it anyway as soon as my review is addressed :)

**Comment by obadz** [comment]
@Ma27, updated as requested.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Thanks! Backported as aac955909943a271ad0ef70f2da4e6ab16eb961f.

**Pull request merged**
