### PR TITLE
super-productivity: update electron to version 13, as 11 is EOL

### PR DESCRIPTION
**Pull request by Ekleog**
This is more or less a backport of https://github.com/NixOS/nixpkgs/pull/148162/commits/61d5e58435cca65f085217600c730fdd4110ecaf , but keeping the changes minimal as we're on a release branch.

Built and tested on NixOS 21.11

### CODE REVIEW

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/158555
FYI electron 13 is also marked as EOL two days ago.

**Comment by Ekleog** [comment]
Hmm so my testing shows electron 14 not actually being able to run the current super-productivity version (it freezes on the startup screen). Do you have opinions on how to fix this? I guess there's no other choice but to update super-productivity itself too, even though that's not really stable...

**Comment by prusnak** [comment]
You can still install packages marked as insecure via `NIXPKGS_ALLOW_INSECURE=1`.

**Comment by Ekleog** [comment]
Right, but if it's what we're suggesting to people running on the stable channel then why bother marking the electron package as insecure in the first place? Electron isn't even a user-facing program, so if we recommend people on stable to use NIXPKGS_ALLOW_INSECURE then the insecure warning would be useful for basically only people who use electron to develop apps, and these people are probably going to be the least touched by the insecure marking.

**Comment by Ekleog** [comment]
Well, I'm landing this already given it's an incremental improvement; if someone else wants to take over backporting super-productivity to 21.11 I'd be more than happy to review the backport but it may take me some time to get to it on my own.

**Pull request merged**
