### PR TITLE
latte-dock: 0.10.4 -> unstable-2022-09-06

### PR DESCRIPTION
**Pull request by greydot**
###### Description of changes
Version bump.

I also remade the autostart patch, since the old one didn't apply properly anymore.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by greydot** [comment]
bump?

**Comment by onny** [comment]
Thank you for this work. The homepage URL seems to be outdated? I guess the project source repo has been moved

**Comment by greydot** [comment]
It might've. Given that it's been a while since the last release, I suppose it would make sense to switch to `master` branch instead.

**Comment by greydot** [comment]
Ok, I bumped it to the latest git code. It seems to have new Plasma features support, like accent colour, as well as Wayland thingies. I haven't tested this with Wayland, but it works with X11 just fine.

**Comment by onny** [comment]
Please change version (in src, commit and PR title) to `unstable-XXXX-XX-XX`

**Comment by benley** [comment]
I'm going to remove myself from the maintainers list for this package - I haven't used latte-dock for quite a while so I'm not really useful for testing it.

**Comment by greydot** [comment]
> Please change version (in src, commit and PR title) to `unstable-XXXX-XX-XX`

Done.

**Comment by Eliot00** [comment]
> Ok, I bumped it to the latest git code. It seems to have new Plasma features support, like accent colour, as well as Wayland thingies. I haven't tested this with Wayland, but it works with X11 just fine.

I'm using latte-dock 0.10.4, right click the dock and choose `Add widget` crashes latte-dock, and I can't use left-click to open a new application instance.

I wonder if these problems still exist on the latest version？

**Comment by onny** [comment]
Sorry for noticing this so late but I guess latte-dock has moved to the KDE source repository https://invent.kde.org/plasma/latte-dock
We should prefer this source since I guess GitHub is only a mirror. Further there are newer stable tagged release 10.4.8. Would be really cool if you can upgrade to this :)

**Comment by greydot** [comment]
> Sorry for noticing this so late but I guess latte-dock has moved to the KDE source repository https://invent.kde.org/plasma/latte-dock We should prefer this source since I guess GitHub is only a mirror.

Done.

> Further there are newer stable tagged release 10.4.8. Would be really cool if you can upgrade to this :)

Do you mean v0.10.8, perchance? It's already 7 months old and doesn't include the wayland changes and plasma 5.25 support. It would be more wise to stick to the latest git code until a new release arrives.

**Comment by greydot** [comment]
bump?

**Comment by greydot** [comment]
more bump?

**Comment by onny** [comment]
Result of `nixpkgs-review pr 176895` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>latte-dock</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you, really good update :)

**Pull request merged**
