### PR TITLE
odoo: 16.20230722 -> 16.20231024

### LINKED ISSUE #256520: Update request: odoo 20230317 → 20230921
- Package name: Odoo
- Latest released version: 16.0.20230921

- Current version on the unstable channel: 16.0.20230722
- Current version on the stable/release channel: 15.0.20230317

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mkg20001 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by FliegendeWurst**
## Description of changes

Simple package update.

Fixes #256520

cc @samip5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samip5** [comment]
It might be worth to instead update it to 20231015 aka the current month's nightly.

**Comment by FliegendeWurst** [comment]
> It might be worth to instead update it to 20231015 aka the current month's nightly.

The official Dockerfile still uses 20230925 https://raw.githubusercontent.com/odoo/docker/master/16.0/Dockerfile

**Comment by FliegendeWurst** [comment]
Updated to the latest version.

**Comment by mkg20001** [comment]
Result of `nixpkgs-review pr 260842` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
