### PR TITLE
Add astronvim plugins

### LINKED ISSUE #311887: Package request: astronvim
**Project description**

Astronvim is a well-known NeoVim distribution. 

**Metadata**

* homepage URL: https://astronvim.com/
* source URL: https://github.com/AstroNvim/AstroNvim
* license: GPL-3.0
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by PerchunPak**
Feel free to propose a better PR name

Closes #311887

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PerchunPak** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368283`

---
### `x86_64-linux`
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by PerchunPak** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368283`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 7 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 7 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 7 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 7 packages built:</summary>
  <ul>
    <li>vimPlugins.astrocore</li>
    <li>vimPlugins.astrolsp</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.astroui</li>
    <li>vimPlugins.mason-null-ls-nvim</li>
    <li>vimPlugins.mason-nvim-dap-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by vbrandl** [comment]
I'd like to use astronvim with NixOS but I'm not quite sure how to go from here...
Is it enough to simply add the `astro*` vimPlugins to my NixOS/homemanager configuration and put the astronvim template in `~/.config/nvim`?

**Comment by PerchunPak** [comment]
> I'd like to use astronvim with NixOS but I'm not quite sure how to go from here... Is it enough to simply add the `astro*` vimPlugins to my NixOS/homemanager configuration and put the astronvim template in `~/.config/nvim`?

Yes, this is exactly how you are supposed to use it with nix

**Comment by vbrandl** [comment]
Thank you. Works like a charm. For full reproducibility, I guess the proper way is to fork the AstroNvim template repo, add my customization and tell homemanager to clone my template repo into `~/.config/nvim`?

**Comment by PerchunPak** [comment]
Much better way would be to store your nvim configuration alongside NixOS config

```nix
home.file.".config/nvim".source = ./my-nvim-config;
```

**Comment by vbrandl** [comment]
I have another machine that doesn't run NixOS (or nix and homemanager) and I'd like to have the same AstroNvim configuration on both machines. So I guess a fork of the template repo that I can use on both machines makes more sense for me. 

Otherwise I agree your solution is simpler.

**Comment by jtliang24** [comment]
I tried adding the 5 vimplugins into my Home Manager config and it errored with:

```
building '/nix/store/ydpnkr90r2q48qhx0pkjjak2zpf83vav-home-manager-path.drv'...
error: collision between `/nix/store/apbbakv89mnp6hrnrkpjv2rwlgjm3jxi-vimplugin-astrolsp-2025-04-22/CHANGELOG.md' and `/nix/store/bybk8x2x1n4pw025kc2hmqwap8d8iyfk-vimplugin-astrocore-2025-04-30/CHANGELOG.md'
error: builder for '/nix/store/ydpnkr90r2q48qhx0pkjjak2zpf83vav-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/apbbakv89mnp6hrnrkpjv2rwlgjm3jxi-vimplugin-astrolsp-2025-04-22/CHANGELOG.md' and `/nix/store/bybk8x2x1n4pw025kc2hmqwap8d8iyfk-vimplugin-astrocore-2025-04-30/CHANGELOG.md'
       For full logs, run 'nix log /nix/store/ydpnkr90r2q48qhx0pkjjak2zpf83vav-home-manager-path.drv'.
error: 1 dependencies of derivation '/nix/store/9prysprkvz457pnfraacms7r9kfpfrd0-home-manager-generation.drv' failed to build
```

**Comment by gabyx** [comment]
Where can I find this astronvim template? It would be nice to habe some documentation how to use this?

**Comment by PerchunPak** [comment]
> Where can I find this astronvim template? It would be nice to habe some documentation how to use this?

git clone https://github.com/AstroNvim/template

**Pull request merged**
