### PR TITLE
faiss: 1.7.2 -> 1.7.4

### PR DESCRIPTION
**Pull request by SomeoneSerge**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SomeoneSerge** [comment]
I think I'll get https://github.com/NixOS/nixpkgs/pull/168380 through first

**Comment by SomeoneSerge** [comment]
Result of `nixpkgs-review pr 224083` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.autofaiss</li>
    <li>python310Packages.autofaiss.dist</li>
    <li>python311Packages.autofaiss</li>
    <li>python311Packages.autofaiss.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>faiss (python310Packages.faiss)</li>
    <li>faiss.demos (python310Packages.faiss.demos)</li>
    <li>faissWithCuda</li>
    <li>faissWithCuda.demos</li>
    <li>python310Packages.pytorch-metric-learning</li>
    <li>python310Packages.pytorch-metric-learning.dist</li>
    <li>python311Packages.faiss</li>
    <li>python311Packages.faiss.demos</li>
  </ul>
</details>

**Comment by SomeoneSerge** [comment]
Result of `nixpkgs-review pr 224083 --extra-nixpkgs-config '{ cudaCapabilities = [ "8.6" ]; cudaSupport = true; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.pytorch-metric-learning</li>
    <li>python310Packages.pytorch-metric-learning.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>faiss (faissWithCuda ,python310Packages.faiss)</li>
    <li>faiss.demos (faissWithCuda.demos ,python310Packages.faiss.demos)</li>
    <li>python310Packages.autofaiss</li>
    <li>python310Packages.autofaiss.dist</li>
    <li>python311Packages.autofaiss</li>
    <li>python311Packages.autofaiss.dist</li>
    <li>python311Packages.faiss</li>
    <li>python311Packages.faiss.demos</li>
  </ul>
</details>

**Comment by SomeoneSerge** [comment]
###### Failed derivations

<details>


- [ ] python3.10-pytorch-metric-learning-2.0.1.drv (derivation hash: fagyjw5vjjw5yl6wayhx0k6kmnflx159)
  - https://gist.github.com/SomeoneSerge/219f906f9597e45f6386e5579cf6588b


</details>

**Comment by NickCao** [comment]
v1.7.4 is released: https://github.com/facebookresearch/faiss/releases/tag/v1.7.4

**Comment by SomeoneSerge** [comment]
Result of `nixpkgs-review pr 224083 --extra-nixpkgs-config '{ cudaCapabilities = [ "8.6" ]; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>faiss (python310Packages.faiss)</li>
    <li>faiss.demos (python310Packages.faiss.demos)</li>
    <li>faissWithCuda</li>
    <li>faissWithCuda.demos</li>
    <li>python310Packages.autofaiss</li>
    <li>python310Packages.autofaiss.dist</li>
    <li>python310Packages.pytorch-metric-learning</li>
    <li>python310Packages.pytorch-metric-learning.dist</li>
    <li>python311Packages.autofaiss</li>
    <li>python311Packages.autofaiss.dist</li>
    <li>python311Packages.faiss</li>
    <li>python311Packages.faiss.demos</li>
  </ul>
</details>

**Comment by SomeoneSerge** [comment]
Hmm, the passthru tests. I'll push with `format = "other";` and see the new logs

**Review by NickCao — APPROVED** [review]

**Pull request merged**
