### PR TITLE
fwupdate: remove

### PR DESCRIPTION
**Pull request by zowoq**
> https://github.com/rhboot/fwupdate
>
>*This project is no longer supported.*
>
>All code has been merged directly into the [fwupd](https://github.com/fwupd/fwupd) project.
>
>Please switch to that.

cc @jtojnar

### CODE REVIEW

**Comment by jtojnar** [comment]
Not sure the alias is a good idea. It is not a drop-in replacement. Removal sounds good.

**Comment by zowoq** [comment]
Changed the alias to a throw.

**Comment by jtojnar** [comment]
The commit message should be updated as well.

**Comment by zowoq** [comment]
Fixed.

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
