### PR TITLE
elm: fix patch hashes

### PR DESCRIPTION
**Pull request by doshitan**
Hit these mismatches while attempting to build the new Elm stuff.
cc @abbradar

### CODE REVIEW

**Comment by vcunat** [comment]
Oh, could this be some `fetchpatch` imperfection? Does someone have the patches matching the current hashes so I can verify it and try to fix it?

**Comment by abbradar** [comment]
Strange -- I have just reran `nix-prefetch-url` and got old hashes.

https://abbradar.net/me/pub/af517f2ffe15f8ec1d8c38f01ce188bbdefea47a.patch
https://abbradar.net/me/pub/ca4d91d3fc7c6f72aa802d79fd1563ab5f3c4f2c.patch

**Comment by vcunat** [comment]
But `fetchpatch` changes the files to clean sources of non-determinism. @abbradar: assuming you determined the hashes this way before your commit, they were always wrong (i.e. noone else would succeed unless using nix-prefetch-url on them by hand).

**Comment by abbradar** [comment]
@vcunat Aha, that's my mistake!

**Comment by peti** [comment]
@vcunat, how would one determine the hash properly when fetchPatch is used?

**Comment by vcunat** [comment]
I know of no other simple way than to fetch it with any hash and use the one from the message.

**Pull request merged**
