### PR TITLE
perlPackages.X11XCB: fix broken dependencies

### PR DESCRIPTION
**Pull request by sigprof**
## Description of changes

`perlPackages.X11XCB` did not actually work, giving errors when trying to use the module:
1. `Can't locate XS/Object/Magic.pm in @INC ... at /nix/store/.../X11/XCB.pm line 18.`
   The problem is that `XSObjectMagic` was listed only in `buildInputs`, but it is actually a runtime dependency, so it should be listed in `propagatedBuildInputs` instead.  Although this error can be worked around by adding `XSObjectMagic` to the dependencies of the package which uses the module, it does not look like a proper way to fix the problem.
   Fix: Moved `XSObjectMagic` from `buildInputs` to `propagatedBuildInputs`.
2. `Can't load '/nix/store/.../X11/XCB/XCB.so' for module X11::XCB: /nix/store/.../X11/XCB/XCB.so: undefined symbol: xcb_randr_get_panning_reply ...`
   The problem is that `NIX_CFLAGS_LINK` did not contain `-lxcb-randr` (and also `-lxcb-xkb`, which then resulted in `undefined symbol: xcb_xkb_set_indicator_map`).
   Fix: Added `-lxcb-randr -lxcb-xkb` to `NIX_CFLAGS_LINK`.

The fixed module can now be used to run the `i3` test suite.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
  (there are no executable binaries in this package, but the module works at least for running the `i3` tests)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Cc: @stigtsp

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sigprof** [comment]
Result of `nixpkgs-review pr 294728` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages built:</summary>
  <ul>
    <li>autotiling</li>
    <li>autotiling.dist</li>
    <li>flashfocus</li>
    <li>flashfocus.dist</li>
    <li>i3</li>
    <li>i3-balance-workspace</li>
    <li>i3-balance-workspace.dist</li>
    <li>i3-layout-manager</li>
    <li>i3-resurrect</li>
    <li>i3-resurrect.dist</li>
    <li>i3-rounded</li>
    <li>i3-rounded.debug</li>
    <li>i3-swallow</li>
    <li>i3-swallow.dist</li>
    <li>i3-wk-switch</li>
    <li>i3.debug</li>
    <li>i3a</li>
    <li>i3a.dist</li>
    <li>i3altlayout</li>
    <li>i3altlayout.dist</li>
    <li>kitti3</li>
    <li>kitti3.dist</li>
    <li>nwg-displays</li>
    <li>nwg-displays.dist</li>
    <li>nwg-panel</li>
    <li>nwg-panel.dist</li>
    <li>nwg-wrapper</li>
    <li>nwg-wrapper.dist</li>
    <li>perl536Packages.X11XCB</li>
    <li>perl536Packages.X11XCB.devdoc</li>
    <li>perl538Packages.X11XCB</li>
    <li>perl538Packages.X11XCB.devdoc</li>
    <li>polybarFull</li>
    <li>powerline (python311Packages.powerline)</li>
    <li>powerline.dist (python311Packages.powerline.dist)</li>
    <li>python311Packages.i3ipc</li>
    <li>python311Packages.i3ipc.dist</li>
    <li>python311Packages.py3status</li>
    <li>python311Packages.py3status.dist</li>
    <li>raiseorlaunch</li>
    <li>raiseorlaunch.dist</li>
    <li>sway-assign-cgroups</li>
    <li>sway-contrib.inactive-windows-transparency</li>
    <li>xkb-switch-i3</li>
  </ul>
</details>

**Comment by sigprof** [comment]
The only package which directly depends on `perlPackages.X11XCB` is `i3`, and the only place where `i3` actually uses the `X11::XCB` module is the test suite, but the execution of tests in `i3` is currently disabled — probably that's why the breakage had not been noticed.

**Comment by stigtsp** [comment]
On a sidenote: I've been thinking about a sort of pythonImportsCheck for perlPackages to find these kinds of problems. Maybe something like:

```
perlUseCheck = ["X11::XCB"];
```

That effectively runs something like:

```
perl -MX11::XCB -E 'say $X11::XCB::VERSION'
```

**Review by stigtsp — APPROVED** [review]
LGTM, thanks!

Tested using `X11::XCB`, works.

**Pull request merged**
