### PR TITLE
libinput: 1.1.6 -> 1.2.0

### PR DESCRIPTION
**Pull request by colemickens**

### CODE REVIEW

**Comment by codyopel** [comment]
@colemickens 

libinput 1.1.8 is out

**Comment by colemickens** [comment]
Thanks for catching that @codyopel. (How did you notice? Do you follow the ML? It seems the freedesktop.org page still doesn't list the new release.)

I've updated the commit to update to 1.1.8.

**Comment by colemickens** [comment]
I think the build is fine, it's just taking too long and Travis is killing it. This should be safe to merge.

**Comment by iyzsong** [comment]
1.2.0 is just out today :-)

**Comment by colemickens** [comment]
Updated

**Comment by fpletz** [comment]
As nobody objects and it builds fine, I think we're should just merge. Thanks!

**Pull request merged**
