### PR TITLE
python3Packages.discordpy: 1.7.3 -> 2.0.0

### PR DESCRIPTION
**Pull request by MayNiklas**
###### Description of changes
Discord.py 2.0.0 was released tonight.
This release is quite important, since it's compatible to a newer API version & adds support for a lot of features, Discord has added over the last few years.

2.0.0 can have breaking changes. The process of migrating to v2 got described here:
https://discordpy.readthedocs.io/en/stable/migrating.html

The release notes got posted on the official Discord server.
Later they can be found on this page (I'm asking the dev to add them there too): https://discordpy.readthedocs.io/en/stable/whats_new.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
The `substituteInPlace` for `aiohttp` seems to be [out-dated](https://github.com/Rapptz/discord.py/blob/master/requirements.txt#L1).

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 187260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.discordpy</li>
    <li>python39Packages.discordpy</li>
  </ul>
</details>

**Comment by MayNiklas** [comment]
> The `substituteInPlace` for `aiohttp` seems to be [out-dated](https://github.com/Rapptz/discord.py/blob/master/requirements.txt#L1).

You're right! Fixed that.

**Review by IvarWithoutBones — APPROVED** [review]
Thanks, LGTM

Result of `nixpkgs-review pr 187260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.discordpy</li>
    <li>python39Packages.discordpy</li>
  </ul>
</details>

**Pull request merged**
