### PR TITLE
linuxPackages.nvidia_x11_{legacy340,legacy470}: add patches for recent kernels

### PR DESCRIPTION
**Pull request by Kiskae**
## Description of changes

- 340 branch:
  - update https://github.com/archlinux-jerry/nvidia-340xx patches
- 470 branch:
  - add https://gist.github.com/joanbm/2ec3c512a1ac21f5f5c6b3c1a4dbef35 for kernel 6.6

In addition I believe the proprietary driver by itself is not affected by the `symbol_get` changes in the 6.6 kernel, but it only affects their other modules that are supposed to hook into the gpu driver: https://github.com/NVIDIA/gds-nvidia-fs/commit/fe75b1ba88d070ebc0c6f60dd8eb342307bf07e5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kiskae** [comment]
Result of `nixpkgs-review pr 255749` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by Kiskae** [comment]
Result of `nixpkgs-review pr 255749 --extra-nixpkgs-config '{ nvidia.acceptLicense = true; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy340.bin</li>
  </ul>
</details>
<details>
  <summary>98 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy340 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy340)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy340.bin (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy340.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy470.bin (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy470.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy470.lib32 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy470.lib32)</li>
    <li>linuxKernel.packages.linux_6_4.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_4.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_6_4.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_4.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_6_4.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_6_4_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_4_hardened.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_6_4_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_4_hardened.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_6_4_hardened.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470.lib32</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy340 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy340)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy340.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy340.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy470.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy470.lib32)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy340.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy470.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy470.lib32</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]

**Comment by smunix** [comment]
@Kiskae - could this patch have caused the error below? 

> error: hash mismatch in fixed-output derivation '/nix/store/cv6w2d9sw53vy678jdh4rapb8s70kixl-nvidia-470xx-fix-linux-6.6.patch.drv':
         specified: sha256-pOYlL5wYfeJsq9EX8zhn/CkNm4ZocNSns5N5pAuIuow=
            got:    sha256-gdV+a+JFzQX8MzRz9eb4gVbnOfTWN+Ds9sOeyIBN5y0=
error: 1 dependencies of derivation '/nix/store/915qs8fgfcz1rwdbclkmx6wfagzzcsly-nvidia-x11-470.199.02-6.1.54.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9d76z1av5nv6dm1rchsdaznpy3wqnc51-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d08d7q8rm4iwzbvmfaiv6aglf7pqfafh-linux-6.1.54-modules.drv' failed to build

**Comment by Kiskae** [comment]
@smunix Could you run the following command?

```console
nix-prefetch-url https://gist.github.com/joanbm/2ec3c512a1ac21f5f5c6b3c1a4dbef35/raw/615feaefed2de3a28bd12fe9783894b84a7c86e4/nvidia-470xx-fix-linux-6.6.patch | xargs nix hash to-sri --type sha256
```

On my machine this returns the same hash as this commit, so if you get a different result then gist is not returning the same file for you.

```console
path is '/nix/store/3i4w9912swzbp5lyc8zg9527w7ivws4m-nvidia-470xx-fix-linux-6.6.patch'
sha256-pOYlL5wYfeJsq9EX8zhn/CkNm4ZocNSns5N5pAuIuow=
```

**Comment by smunix** [comment]
Strange, I get the same result:

```sh
~> nix-prefetch-url https://gist.github.com/joanbm/2ec3c512a1ac21f5f5c6b3c1a4dbef35/raw/615feaefed2de3a28bd12fe9783894b84a7c86e4/nvidia-470xx-fix-linux-6.6.patch | xargs nix hash to-sri --type sha256        09/21/2023 07:40:28 AM
path is '/nix/store/3i4w9912swzbp5lyc8zg9527w7ivws4m-nvidia-470xx-fix-linux-6.6.patch'
sha256-pOYlL5wYfeJsq9EX8zhn/CkNm4ZocNSns5N5pAuIuow=
~> nix --version                                                                                                                                                                                               09/21/2023 07:40:31 AM
nix (Nix) 2.17.0
```

**Comment by Kiskae** [comment]
Then it is difficult to tell what is going on without being able to inspect what nix is hashing, but the root cause isn't this PR.

**Comment by Kiskae** [comment]
Turns out the interplay between `nix-prefetch-url` and fixed-hash derivations made me think the hash was correct, when `fetchpatch` produces a different result.

https://github.com/NixOS/nixpkgs/pull/256555

**Pull request merged**
