### PR TITLE
mesa: fix build Aarch64

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Was failing like

```
meson.build:21:0: ERROR: Options "imx" are not in allowed choices: ", auto, kmsro, radeonsi, r300, r600, nouveau, freedreno, swrast, v3d, vc4, etnaviv, tegra, i915, svga, virgl, swr, panfrost, iris, lima"
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @eadwu

**Comment by worldofpeace** [comment]
huh darwin is failing to configure at
```
meson.build:368:4: ERROR: Problem encountered: Cannot build GLX support without X11 platform support and at least one OpenGL API
```

**Comment by eadwu** [comment]
Removing the option should be fine while for the darwin error, from what I'm reading it seems to originate from here [1]. If we don't want to change `-Dglx` for darwin then there should be a non-zero amount of gallium or dri drivers, `-Ddri-drivers= -Dgallium-drivers= -Dvulkan-drivers=` [2].

[1] https://gitlab.freedesktop.org/mesa/mesa/blob/19.1/meson.build#L315
[2] https://hydra.nixos.org/build/95553754/log

**Comment by matthewbauer** [comment]
> Removing the option should be fine while for the darwin error, from what I'm reading it seems to originate from here [1]. If we don't want to change `-Dglx` for darwin then there should be a non-zero amount of gallium or dri drivers, `-Ddri-drivers= -Dgallium-drivers= -Dvulkan-drivers=` [2].
> 
> [1] https://gitlab.freedesktop.org/mesa/mesa/blob/19.1/meson.build#L315
> [2] https://hydra.nixos.org/build/95553754/log

That looks like a mesa issue. The whole point of the appledri is to have GLX without building opengl drivers. Otherwise you wouldn't be building anything at all[1]. For now it's probably okay for this to be broken, luckily not much macOS stuff uses it right now (it only makes sense if you are using XQuartz as well).

[1] https://gitlab.freedesktop.org/mesa/mesa/blob/19.1/src/glx/apple/RELEASE_NOTES

Issue filed at https://bugs.freedesktop.org/show_bug.cgi?id=111016

**Comment by worldofpeace** [comment]
Thanks for filing an issue upstream @matthewbauer.
I agree it's fine to leave it broken for darwin.

Let's merge :sparkles:

**Comment by vcunat** [comment]
Well, this probably blocks merging to master, due to breaking a few thousand [darwin builds](https://hydra.nixos.org/eval/1529292?compare=1528940).  Lemme try this: https://github.com/NixOS/nixpkgs/pull/64500

**Pull request merged**
