### PR TITLE
maestral: fix tests

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

a3f1b8c2ad99ceccb1f1f995ea4f9e72704423fd broke the tests.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The gui part still seems to be broken.

```
$ ./results/maestral-gui/bin/maestral_qt 
Traceback (most recent call last):
  File "/nix/store/qv01jrz8l25jzj2hshpz1nkxbg0alc4g-maestral-qt-1.5.3/bin/.maestral_qt-wrapped", line 6, in <module>
    from maestral_qt.__main__ import main
  File "/nix/store/qv01jrz8l25jzj2hshpz1nkxbg0alc4g-maestral-qt-1.5.3/lib/python3.10/site-packages/maestral_qt/__main__.py", line 7, in <module>
    from maestral_qt.main import run
  File "/nix/store/qv01jrz8l25jzj2hshpz1nkxbg0alc4g-maestral-qt-1.5.3/lib/python3.10/site-packages/maestral_qt/main.py", line 37, in <module>
    from maestral.errors import KeyringAccessError
ModuleNotFoundError: No module named 'maestral.errors'

**Comment by SFrijters** [comment]
maestral-gui 1.6.3 requires PyQt6 which is not yet available in nixpkgs as far as I'm aware.
The update to 1.6.x was held back before https://github.com/NixOS/nixpkgs/pull/166064 .

**Comment by peterhoeg** [comment]
The GUI version requires the CLI version, correct. I don't think they necessarily need to be the same version (I guess it depends on the changes), but yes, we cannot bump -gui until we get pyqt6 which is currently WIP. I've been running 1.6.3 for  a while locally (I don't use the GUI) but hadn't submitted it for nixpkgs due to the pyqt6 issue. In any case, without this PR *both* the cli and gui versions are broken.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 183963 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>3 packages built:</summary>  <ul>    <li>maestral (python310Packages.maestral)</li>    <li>maestral-gui</li>    <li>python39Packages.maestral</li>  </ul></details>

**Pull request merged**
