### PR TITLE
gcc: Refactor treatment of configure flags

### PR DESCRIPTION
**Pull request by bgamari**
Previously configureFlags was defined as one giant interpolated string. Here we
refactor this definition to instead use the usual stdenv string
combinators. This seems more in-line with the average nixpkgs expression
and it seems a bit more natural to things of these as lists of flags
rather than monolithic strings.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bgamari** [comment]
I still need to test this but putting it up to make sure that the direction is acceptable. I can do the same for gcc 7 in due course.

**Comment by Ericson2314** [comment]
This is great!

**Comment by vcunat** [comment]
Certainly 👍 for the direction.

**Review by LnL7 — APPROVED** [review]

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixos/pr-31292

**Comment by aneeshusa** [comment]
I'm always happy to see more in the vein of #15799 :)

**Comment by bgamari** [comment]
How should I interpret the Travis failure? It looks to me like it just failed due to a conflict.

**Comment by Ericson2314** [comment]
@bgamari Travis fails for us, especially with mass rebuilds, so I wouldn't worry. The nixborg builds failures look spurious, so if you want to convert the other GCCs I think this is ready to go!.

**Review by bgamari — COMMENTED** [review]
Alright, I've rebased this and finished porting the remaining compiler versions.

**Comment by Ericson2314** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixos/pr-31292

**Comment by Ericson2314** [comment]
Build looks good enough to me, thanks @bgamari!

**Pull request merged**
