### PR TITLE
nextcloud: init at 22.0.0; 21.0.2 -> 21.0.3; 20.0.7 -> 20.0.11

### PR DESCRIPTION
**Pull request by bbenno**
###### Motivation for this change

Bump to the latest minor version of v21 at the time of making this PR.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
@bbenno hehe, I was also about to work on this :) Is it okay if I push the Nextcloud 20 update to your branch as well? :)

**Comment by bbenno** [comment]
> 
> 
> @bbenno hehe, I was also about to work on this :) Is it okay if I push the Nextcloud 20 update to your branch as well? :)

^^ nice

Sure! Go ahead

**Comment by Kranzes** [comment]
> @bbenno hehe, I was also about to work on this :) Is it okay if I push the Nextcloud 20 update to your branch as well? :)

Also Nextcloud 22 :^)

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129620` at 765c1b31 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>nextcloud21</li>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Comment by Ma27** [comment]
> Also Nextcloud 22 :^)

Seen it, already working on it.

**Comment by Ma27** [comment]
While this needs a backport (including a backport for Nextcloud 22), I'd prefer to do it manually since we'll need different settings in the module and I'm not sure yet what to do about nextcloud19 (which I should've removed before 21.05, but I forgot about it :/ ).

Hence setting the 'needs: port to stable` label, but not the one for the GH actions.

**Pull request merged**
