### PR TITLE
tixati: 2.67 -> 2.72

### PR DESCRIPTION
**Pull request by bcc32**
###### Motivation for this change

Upgrading tixati to version 2.72

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Package closure size increased from 166689224 to 167160088 (+0.28%).

### CODE REVIEW

**Review by evils — APPROVED** [review]
LGTM, thanks
i'm kinda surprised @r-ryantm (bot) hasn't updated this yet

**Comment by ryantm** [comment]
the bot doesn't make new PRs if one is already open: https://github.com/NixOS/nixpkgs/pull/81639

**Comment by volth** [comment]
> the bot doesn't make new PRs if one is already open: #81639

Who should merge bot's PR?
The bot on its second pass few days after?

**Comment by evils** [comment]
@bcc32 did you mean to close this PR?

**Comment by bcc32** [comment]
Oh no!  I didn't mean to do that, I meant to rename the branch, but it looks like GitHub PRs don't support that.  I'll open a new PR with the same contents.  (No option to reopen on my end.)

**Pull request closed without merging**
