### PR TITLE
virtualboxHeadless: Fix build

### PR DESCRIPTION
**Pull request by knedlsepp**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by knedlsepp** [comment]
@GrahamcOfBorg build virtualboxHeadless

**Comment by flokli** [comment]
@knedlsepp thanks for the PR!

I'm a bit confused however, from my understanding, the virtualbox vm tests should set `virtualisation.virtualbox.headless = true;`, which should cause a headless virtualbox to be used - so we should have run into this bug already.

@ambrop72, any ideas?

**Comment by knedlsepp** [comment]
@flokli: That's kind of interesting. I was simply going through the [most recent list of failed hydra builds](https://hydra.nixos.org/eval/1522829?filter=virtualbox&compare=1522819&full=#tabs-still-fail) and saw that [nixpkgs:trunk:virtualboxHeadless](https://hydra.nixos.org/build/94212809) was failing because of  a missing `<GL/gl.h>` header.

**Review by vcunat — APPROVED** [review]

**Comment by vcunat** [comment]
Yes, the test code is confusing and perhaps test something else than intended: https://github.com/NixOS/nixpkgs/commit/78cd9f8ebc36#r33865313 but I don't think that should stop this PR.

**Comment by flokli** [comment]
@vcunat you're right - didn't want to stall this PR, just forgot about it. Thanks for following up!

**Pull request merged**
