### PR TITLE
haskellPackages fourmolu 0.10.0.0 -> 0.10.1.0

### PR DESCRIPTION
**Pull request by tmcl**
###### Description of changes

Upgrade fourmolu-0.10.0.0 -> fourmolu-0.10.1.0 (in haskell packages). This was a bugfix release for fourmolu https://github.com/fourmolu/fourmolu/releases/tag/v0.10.1.0 that was previously in nixpkgs but got removed during an upgrade of hackage and a fix for haskell-language-server.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
Thanks!

Would you be able to rebase this on the `haskell-updates` branch?  And also check that all the expected HLSes still compile?  (I just want to make sure that changing this version doesn't break HLS)

**Comment by tmcl** [comment]
Thanks @cdepillabout. I have rebased it but I hope I haven't accidentally pinged the wrong people by doing it.

I can confirm that haskell.packages.ghc944.haskell-language-server and  haskell.packages.ghc92.haskell-language-server successfully built with this change before I rebased. But post rebase I'm getting a spurious error 'error: Check if 'bad bounds' was resolved in lucid 2.11.20230408 and update or remove this' and a requirement to rebuild GHC, I don't know if there's any cache available?

**Comment by tmcl** [comment]
No worries @maralorn 

There we go, fixed the base.

**Comment by maralorn** [comment]
Excellent!

**Pull request merged**
