### PR TITLE
Backport Qt 5.5 improvements to release-15.09

### PR DESCRIPTION
**Pull request by bjornfor**
These are all generic Qt 5.5 improvements that I could find on master that isn't in the stable branch.

EDIT: Ready for merge.

### CODE REVIEW

**Comment by bjornfor** [comment]
I haven't run nox-review yet (low disk-space and I have some other CPU hogging processes on my system today). But one of the goals of this PR was to be able to use Qt 5.5 in QtCreator, and that doesn't work. It fails the same way on master*:

```
$ ./result/bin/qtcreator
file:///nix/store/zmpf6ydrjdydd85wh6splpywv6aj4782-qtcreator-3.4.2/share/qtcreator/welcomescreen/welcomescreen.qml:31:1: module "QtQuick" is not installed 
     import QtQuick 2.1 
     ^
```

This breaks the welcome screen (all white / blank).

\* I use the following patch to build qtcreator with qt55:

```patch
diff --git a/pkgs/development/qtcreator/default.nix b/pkgs/development/qtcreator/default.nix
index 8dabd33..f920226 100644
--- a/pkgs/development/qtcreator/default.nix
+++ b/pkgs/development/qtcreator/default.nix
@@ -16,7 +16,7 @@ stdenv.mkDerivation rec {
     sha256 = "1asbfphws0aqs92gjgh0iqzr1911kg51r9al44jxpfk88yazjzgm";
   };
 
-  buildInputs = [ makeWrapper qtLib.base qtLib.script qtLib.quickcontrols qtLib.declarative ];
+  buildInputs = [ makeWrapper qtLib.qtbase qtLib.qtscript qtLib.qtquickcontrols qtLib.qtdeclarative ];
 
   doCheck = false;
 
@@ -45,7 +45,7 @@ stdenv.mkDerivation rec {
     Categories=Qt;Development;IDE;
     __EOF__
     # Wrap the qtcreator binary
-    addToSearchPath QML2_IMPORT_PATH "${qtLib.quickcontrols}/lib/qt5/qml"
+    addToSearchPath QML2_IMPORT_PATH "${qtLib.qtquickcontrols}/lib/qt5/qml"
     wrapProgram $out/bin/qtcreator \
       --prefix QT_PLUGIN_PATH : "$QT_PLUGIN_PATH" \
       --prefix QML_IMPORT_PATH : "$QML_IMPORT_PATH" \
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index a91d3da..e682ea2 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -8107,7 +8107,7 @@ let
   });
 
   qtcreator = callPackage ../development/qtcreator {
-    qtLib = qt54;
+    qtLib = qt55;
     withDocumentation = true;
   };
 
```

**Comment by bjornfor** [comment]
qtcreator wrapper on master:

```
$ cat ./result/bin/qtcreator
#! /nix/store/xag5ayq906w9zhlxs8wayv4kvpiyqphq-bash-4.3-p42/bin/bash -e
export QT_PLUGIN_PATH=/nix/store/msack3cmh2p7kf5bcp26cqkwaky7rlyx-qtbase-5.4.2/lib/qt5/plugins:/nix/store/8bx376rlb148x6r3l2d4khmmfidblwh8-qttools-5.4.2/lib/qt5/plugins:/nix/store/87a2w6l3zzq1639fvsqzpxhpafpkvdrf-qtdeclarative-5.4.2/lib/qt5/plugins:/nix/store/k5r82x2xkqszjmqkq56zzgdi7n1scchm-qtsvg-5.4.2/lib/qt5/plugins:/nix/store/2wx1xyd3c8diwxv0j8xkzi6hz52qsg34-qtwebkit-5.4.2/lib/qt5/plugins:/nix/store/4zmw4j52c12c687m26gc9q524imwbw1d-qtlocation-5.4.2/lib/qt5/plugins:/nix/store/0anpmz654yfsaz5ygjv8x4xp3ghkd2rs-qtmultimedia-5.4.2/lib/qt5/plugins:/nix/store/xzbza4qh0f8adlsf955896bkv2spyk2b-qtsensors-5.4.2/lib/qt5/plugins${QT_PLUGIN_PATH:+:}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH=/nix/store/87a2w6l3zzq1639fvsqzpxhpafpkvdrf-qtdeclarative-5.4.2/lib/qt5/qml:/nix/store/2wx1xyd3c8diwxv0j8xkzi6hz52qsg34-qtwebkit-5.4.2/lib/qt5/qml:/nix/store/4zmw4j52c12c687m26gc9q524imwbw1d-qtlocation-5.4.2/lib/qt5/qml:/nix/store/0anpmz654yfsaz5ygjv8x4xp3ghkd2rs-qtmultimedia-5.4.2/lib/qt5/qml:/nix/store/xzbza4qh0f8adlsf955896bkv2spyk2b-qtsensors-5.4.2/lib/qt5/qml:/nix/store/g18b9lxwr023m2l0iq2a1l89c9c0z184-qtquickcontrols-5.4.2/lib/qt5/qml${QML2_IMPORT_PATH:+:}$QML2_IMPORT_PATH
exec -a "$0" /nix/store/k65jp38x3v6k1cxxmwil9s717mgynd9i-qtcreator-3.4.2/bin/.qtcreator-wrapped "${extraFlagsArray[@]}" "$@"
```

qtcreator on master + build with qt55 (see patch in previous post):

```
$ cat ./result/bin/qtcreator
#! /nix/store/xag5ayq906w9zhlxs8wayv4kvpiyqphq-bash-4.3-p42/bin/bash -e
export QML2_IMPORT_PATH=/nix/store/8nzfzjd1ihkv7djl9wyasj96gzjr7mrb-qtquickcontrols-5.5.0/lib/qt5/qml${QML2_IMPORT_PATH:+:}$QML2_IMPORT_PATH
exec -a "$0" /nix/store/zmpf6ydrjdydd85wh6splpywv6aj4782-qtcreator-3.4.2/bin/.qtcreator-wrapped "${extraFlagsArray[@]}" "$@"
```

**Comment by bjornfor** [comment]
Ah, it's missing qtdeclarative. This works:

```
QML2_IMPORT_PATH=/nix/store/mvcib9a1dwyq8w7dma1pnpi53h7n3snx-qtdeclarative-5.5.0/lib/qt5/qml/ ./result/bin/qtcreator
```

**Comment by bjornfor** [comment]
I added qtdeclarative to qtcreator in ff4d8513b435cbb9858a6e714f5e50e0d9ae069a. CC @ttuegel.

**Comment by bjornfor** [comment]
nox-review succeeded locally.

**Comment by bjornfor** [comment]
According to nox-review (which completed successfully), it only touches these derivations:
qtcreator stellarium teamspeak_client qt5Full. I also tested qtcreator with qt55 (local change). It works.

I think it's ready for merge.

**Comment by bjornfor** [comment]
Any objections?

**Comment by ttuegel** [comment]
Looks good to me. Thanks!

**Pull request merged**
