### PR TITLE
go-ethereum: 1.10.26 -> 1.11.5

### PR DESCRIPTION
**Pull request by doubledup**
###### Description of changes

Release notes:
https://github.com/ethereum/go-ethereum/releases/tag/v1.11.5

###### Things done

I haven't run `nixos/tests/geth.nix` as it fails when not on Linux: `error: assertion '(stdenv).isLinux' failed`.

Also testing dependent packages with `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` fails.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jakubgs** [comment]
Why not https://github.com/ethereum/go-ethereum/releases/tag/v1.11.4 ?

**Comment by jakubgs** [comment]
Actuallly, `1.11.5` is already out with support for Shanghai upgrade:

>Geth v1.11.5 enables the Shanghai upgrade on Wednesday, April 12, 2023 10:27:35 PM UTC

https://github.com/ethereum/go-ethereum/releases/tag/v1.11.5

Can we maybe get `1.11.5` into `master` before the 10th?

**Comment by jakubgs** [comment]
For those that want `1.11.5` before this gets merged sometime in the next 2-3 months you can use this:
```nix
# Can't use overrideAttrs due to how buildGoModule overwrites arguments.
pkgs.go-ethereum.override {
  buildGoModule = args: pkgs.buildGo120Module ( args // rec {
    version = "1.11.5";

    src = pkgs.fetchFromGitHub {
      owner = "ethereum";
      repo = args.pname;
      rev = "v${version}";
      sha256 = "sha256-QFqPAWW0L9cSBvnDwJKtwWT2jZFyr+zhYaS+GF/nQ9g=";
    };

    vendorSha256 = "sha256-Y1srOcXZ4rQ0QIQx4LdYzYG6goGk6oO30C+OW+s81z4=";

    subPackages = [
      "cmd/ethkey"
      "cmd/clef"
      "cmd/geth"
      "cmd/utils"
    ];
  });
}
```
Narrowed down `subPackages` since most of it is useless to most people.

**Comment by doubledup** [comment]
@jakubgs Apologies, I've been away for the last 2 weeks. Happy to switch to `1.11.5`, I'll sort that out today.

> Why not 1.11.4?

I went for `1.11.0` on the assumption that we should have derivations for all versions of a package, but looking at previous PRs it seems this isn't the case. Having all versions of a package available can help limit complexity & risk when upgrading. Though now I see this would significantly increase the workload for updating every package and only benefit very risk-averse users.

If smaller version bumps are needed, is the right way to set up an override similar to the one you've given for `1.11.5`?

**Comment by jakubgs** [comment]
>we should have derivations for all versions of a package

No, that's not how it should work. If Nixpkgs held all versions of all packages it would be ridiculously big. It's already big enough while holding only the most recent versions. If people need a specific version they should indeed just override, or ping `nixpkgs` they use to a specific commit or a fork they've created.

**Comment by doubledup** [comment]
Testing dependent packages with `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` fails, seems like a MySQL package for Common Lisp so I'm not sure it's related to this change.

```
nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 29 (delta 12), reused 15 (delta 9), pack-reused 2
Unpacking objects: 100% (29/29), 16.95 KiB | 159.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
   d59c85209d3..64a5b00d023  master     -> refs/nixpkgs-review/0
$ git worktree add /Users/daviddunn/.cache/nixpkgs-review/rev-e0205290f5319e219401a6ecbc5d42ac3e93112a/nixpkgs 64a5b00d0235a6abd85f0ed5e33775ab6febd9db
Preparing worktree (detached HEAD 64a5b00d023)
Updating files: 100% (34337/34337), done.
HEAD is now at 64a5b00d023 Merge pull request #224462 from wegank/scalp-mirror
$ nix-env --option system aarch64-darwin -f /Users/daviddunn/.cache/nixpkgs-review/rev-e0205290f5319e219401a6ecbc5d42ac3e93112a/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
error:
       … while querying the derivation named 'cl-mysql-20200610-git'

       … while evaluating the attribute 'nativeLibs' of the derivation 'cl-mysql-20200610-git'

       at /Users/daviddunn/.cache/nixpkgs-review/rev-e0205290f5319e219401a6ecbc5d42ac3e93112a/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:302:7:

          301|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          302|       name =
             |       ^
          303|         let

       error: attribute 'mysql-client' missing

       at /Users/daviddunn/.cache/nixpkgs-review/rev-e0205290f5319e219401a6ecbc5d42ac3e93112a/nixpkgs/pkgs/development/lisp-modules/ql.nix:59:22:

           58|     cl-mysql = super.cl-mysql.overrideLispAttrs (o: {
           59|       nativeLibs = [ pkgs.mysql-client ];
             |                      ^
           60|     });
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/cli/__init__.py", line 301, in main
    return cast(str, args.func(args))
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/cli/rev.py", line 12, in rev_command
    return review_local_revision(f"rev-{commit}", args, commit)
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 497, in review_local_revision
    review.review_commit(builddir.path, args.branch, commit, staged)
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 263, in review_commit
    self.start_review(self.build_commit(branch_rev, reviewed_commit, staged), path)
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 147, in build_commit
    base_packages = list_packages(
  File "/nix/store/q76l69048llcd3p6q4zzb8maj4f69j82-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 335, in list_packages
    subprocess.run(cmd, stdout=tmp, check=True)
  File "/nix/store/n3qask6wrby75704dz3vcwnd3f9vkab8-python3-3.10.9/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-env', '--option', 'system', 'aarch64-darwin', '-f', '/Users/daviddunn/.cache/nixpkgs-review/rev-e0205290f5319e219401a6ecbc5d42ac3e93112a/nixpkgs', '-qaP', '--xml', '--out-path', '--show-trace', '--no-allow-import-from-derivation']' returned non-zero exit status 1.
```

**Pull request merged**
