### PR TITLE
pango,gtk3,gtk4,libadwaita: update

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change

- [x] authenticator – already broken
- [x] metadata-cleaner – works
- [x] notejot ­– #153022
- [x] kooha – fixed dep lookup, works
- [x] clapper – no warnings but crashes when playing
- [x] khronos – works
- [x] mousai – works
- [x] spot – works
- [x] shortwave – marked as broken
- [x] gnome-todo – updated to master
- [x] xdg-desktop-portal-gnome – works
- [x] ashpd-demo – marked as broken

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — APPROVED** [review]
The diff looks good to me

**Comment by jtojnar** [comment]
`gnome-todo` is also broken like `notejot`:

```
(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.455: Error building template class 'GtdWindow' for an instance of type 'GtdWindow': .:0:0 Invalid property: AdwLeaflet.can-swipe-back

(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.455: gtk_list_box_bind_model: assertion 'GTK_IS_LIST_BOX (box)' failed

(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.455: gtk_menu_button_set_menu_model: assertion 'GTK_IS_MENU_BUTTON (menu_button)' failed

(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.455: gtk_menu_button_get_popover: assertion 'GTK_IS_MENU_BUTTON (menu_button)' failed

(gnome-todo:171718): Adwaita-WARNING **: 21:59:03.456: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(gnome-todo:171718): Adwaita-WARNING **: 21:59:03.457: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.457: gtk_popover_menu_add_child: assertion 'GTK_IS_POPOVER_MENU (popover)' failed

(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.480: gtk_stack_add_named: assertion 'GTK_IS_STACK (stack)' failed

(gnome-todo:171718): Gtk-CRITICAL **: 21:59:03.507: gtk_stack_add_named: assertion 'GTK_IS_STACK (stack)' failed

```

**Comment by jtojnar** [comment]
Checked all libadwaita apps and updated them or marked them as broken when no update (not even in git) is available. notejot is done separately in #153022

**Comment by jtojnar** [comment]
Oops, I forgot to fix the libportal builds: https://github.com/NixOS/nixpkgs/pull/153225

**Comment by mikroskeem** [comment]
Seems like this verison bump broke gtk3 building on aarch64-darwin - https://gist.github.com/mikroskeem/4ea02750a77d30f6ba9b25cb4d803ebf

**Pull request merged**
