### PR TITLE
xlife: init at 6.7.5

### PR DESCRIPTION
**Pull request by djanatyn**
###### Motivation for this change
There are a few different branches of `xlife` development. This is the `6.7 (2013)` branch, documented in the development history on the homepage:
* http://litwr2.atspace.eu/xlife/XLIFE-DEVELOPMENT.html

It appears to be the most recent development branch available.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I've also added the `hpndSellVariant` license that this application uses. I've done the same in a previous PR: #103518

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Fails to build for me.
```
configuring
configuring with imake: ''
imake -DUseInstalled -I/nix/store/xj92pflviva2kd0frrq6ya40pcnryhgq-imake-1.0.8/lib/X11/config
/nix/store/xj92pflviva2kd0frrq6ya40pcnryhgq-imake-1.0.8/bin/xmkmf: line 53:    13 Aborted                 (core dumped) imake $imake_defines $args
```

**Comment by djanatyn** [comment]
@SuperSandro2000 I couldn't reproduce this build error.

I wonder if there is an issue in the Imakefile: https://sourceforge.net/p/xlife-cal/xlife/HEAD/tree/trunk/Imakefile

The closest I could find to that error was this Red Hat Bugzilla thread: https://bugzilla.redhat.com/show_bug.cgi?id=1605031

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103884` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>xlife</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103884` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by SuperSandro2000** [comment]
Builds now. No idea why it failed earlier.

**Pull request merged**
