### PR TITLE
thunderbird, thunderbird-bin: 52.9.1 -> 60.0 

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- various improvements and fixes

https://www.thunderbird.net/en-US/thunderbird/60.0/releasenotes/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by taku0** [comment]
Now, ready to merge :smiley:.

**Comment by timokau** [comment]
@GrahamcOfBorg build thunderbird thunderbird-bin

@samueldr why do you think this should be backported?

**Comment by vcunat** [comment]
Backport: I don't know if 52.x is to be maintained much longer, but I'd expect we should wait for 60.1 at least, according to information from the web:
> Thunderbird version 60.0 is only offered as direct download from thunderbird.net and not as upgrade from Thunderbird version 52 or earlier. A future version 60.1 will provide updates from earlier versions.

**Comment by samueldr** [comment]
> @samueldr why do you think this should be backported?

The [current set of general guidelines for backports](https://gist.github.com/grahamc/c60578c6e6928043d29a427361634df6#what-to-backport) list thunderbird specifically. This also would be subject to the "Extremely security-sensitive software" (imho) even if it wasn't named.

Though, as @vcunat seems to have found, it looks like this isn't (yet) an upgrade to version 52. It can then probably wait until it becomes one (as stated by upstream).

**Review by vcunat — APPROVED** [review]
Seems to run OK for me.

**Pull request merged**
