### PR TITLE
WIP: darktable: add version 2.0.0

### PR DESCRIPTION
**Pull request by ikervagyok**
also make it optional, as once darktable is updated, there's problems going back to version 1.6

see: `http://www.darktable.org/2015/12/darktable-2-0-released/`
`when updating from the currently stable 1.6.x series, please bear in mind that your edits will be preserved during this process, but it will not be possible to downgrade from 2.0 to 1.6.x any more.`

### CODE REVIEW

**Comment by lancelotsix** [comment]
I have a branch where I did update to darktable-2: https://github.com/lancelotsix/nixpkgs/commit/5354617c9096ae22aa4221782007b2539c369344

Here are the major differences:
1) In `pugixml`, instead of using `NIX_CFLAGS_COMPILE` to have `-fPIC`, you should add `-DUILD_SHARED_LIBS=ON` which is present for the exact purpose of providing dynamic libraries
2) works perfectly without overriding `NIX_CFLAGS_COMPILE`
3) I am not sure that darktable-1.x has to be maintained in nixpkgs. If yes, I would say that it would make more sense to have `pkgs.darktable` reference the 2.x branch, and add a `pkgs.darktable1` to maintain older versions

**Comment by nckx** [comment]
> 3) I am not sure that darktable-1.x has to be maintained in nixpkgs. [If yes, ...]

:+1:

**Comment by nckx** [comment]
Also: I'm on Windows now so can't check, but please check whether NixOS's `system.stateVersion` applies here.

Unlikely, but I thought I'd bring it up.

**Comment by lancelotsix** [comment]
@nckx Do you mean introducing something like this in `pkgs/top-level/all-packages.nix`?

```nix
darktable1 = …;
darktable2 = …;
darktable = if (versionAtLeast config.system.stateVersion "16.xx") then darktable2 else darktable1;
```

My approach would be to just have darktable-2 here. It will end up in the unstable channel, which is here for that. The 1.x version will continue to be present in `nixos-15.09` for users who require a stable solution.

@ikervagyok (in reply to https://github.com/lancelotsix/nixpkgs/commit/5354617c9096ae22aa4221782007b2539c369344#commitcomment-15354657), feel free to cherry-pick from https://github.com/lancelotsix/nixpkgs/commit/b547cd59f30c3eace42b5e630d2e62cd7db1d872 (this one also removes the `libraw1394` dependency) and add an independent commit to introduce `osm-gps-map` in the package set

**Comment by nckx** [comment]
> Do you mean introducing something like this in pkgs/top-level/all-packages.nix? [...]

Something like that.

> My approach would be to just have darktable-2 here. It will end up in the unstable channel, which is here for that. The 1.x version will continue to be present in nixos-15.09 for users who require a stable solution.

Sure. I also prefer a single (well-tested) version over bitrotting 'choices' that aren't; just wanted to consider the possible alternatives so no-one can complain afterwards.

**Comment by globin** [comment]
superseeded by #12633

**Pull request closed without merging**
