### PR TITLE
openmw: ffmpeg_3 -> ffmpeg

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

#120705 

Cc: @abbradar 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123607` at f9cdbd7b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/fc8187f19acd8c09071cf0fdf123f9e1">openmw-tes3mp</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>openmw</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by peterhoeg** [comment]
tes3 was fixed up as well while at it. The launcher scripts are done separately now to avoid having to rebuild everything in case of changes to either lua or launcher scripts.

**Review by dotlambda — APPROVED** [review]

**Comment by davitgog** [comment]
can we change ffmpeg to ffmpeg_4 because sound files don't work when openmw is built with ffmpeg, which is version 5.1 now, my issue is well described [here](https://forum.openmw.org/viewtopic.php?t=7734). I tested and building with ffmpeg_4 fixes the issue and sound works as expected in game.

**Comment by dotlambda** [comment]
@davitgog https://gitlab.com/OpenMW/openmw/-/issues/6631 was closed, maybe we just need to update openmw?

**Comment by davitgog** [comment]
@dotlambda 0.48 also fixes the ffmpeg 5 issue. Already tested it.

**Pull request merged**
