### PR TITLE
dxvk: 1.10.3 -> 2.0

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

Creating this as a draft PR until after the 22.11 release.

DXVK 2.0 release notes: https://github.com/doitsujin/dxvk/releases/tag/v2.0

DXVK is pinned to 1.10.3 on Darwin because MoltenVK does not support Vulkan 1.3 or enough extensions for DXVK 2.0 to work with it. Alas, it’s not as easy anymore as just lying about extension support.

I was able to build and test that the `setup_dxvk.sh` script still works. Unfortunately, I do not have access to any Linux machines with capable GPUs to test the functionality beyond that.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
Taking this out of draft now that 22.11 is out.

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 200618` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dxvk</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
Curiosity: Do we have this in store only for people to easily copy it inside their WINEPREFIX? We can't even use it with the `setup* --symlink` unless you add it to an impure directory like `hardware.opengl.extraPackages` or a FHS…

**Comment by reckenrode** [comment]
> Curiosity: Do we have this in store only for people to easily copy it inside their WINEPREFIX? We can't even use it with the `setup* --symlink` unless you add it to an impure directory like `hardware.opengl.extraPackages` or a FHS…

More or less, right now. The `bin` output makes the DLLs available if someone wants to write a derivation for a Windows game. I have a FFXIV one that does that, though I’m not sure about upstreaming it into nixpkgs.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
