### PR TITLE
gitlab: 15.11.6 -> 16.0.1

### PR DESCRIPTION
**Pull request by yayayayaka**
As always, each major version bump comes with a long list of deprecations/breaking changes.

The NixOS GitLab maintainers have spotted the following breaking changes so far:
- [PostgreSQL 12 is deprecated](https://docs.gitlab.com/ee/update/deprecations.html#postgresql-12-deprecated)
- [Use of third party container registries is deprecated](https://docs.gitlab.com/ee/update/deprecations.html#use-of-third-party-container-registries-is-deprecated) (in our case `pkgs.docker-distribution`)
- [Configuring Redis config file paths using environment variables is deprecated](https://docs.gitlab.com/ee/update/deprecations.html#configuring-redis-config-file-paths-using-environment-variables-is-deprecated)
- [Ruby dependencies have been removed in gitaly](https://gitlab.com/groups/gitlab-org/-/epics/2862)
- Various parts of gitlab now need `getconf` in their path, because the `prometheus-client-mmap` gem shells out to that.

###### Description of changes
- [x] Assert PostgreSQL >=13.6
- [x] Mention new PostgreSQL requirement in the release notes
- [x] Review and merge #233266
- [x] Update the gitlab module to use the gitlab-container-registry instead
- [x] Update redis configuration
- [x] Remove ruby dependencies in gitaly
- [x] Fix missing getconf

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yayayayaka** [comment]
I have added a `services.gitlab.registry.package` option defaulting to `pkgs.docker-distribution` and `pkgs.gitlab-container-registry` for `system.stateVersion`s >=23.11.

A warning for GitLab >=16.0 module users will be added to ask them to switch to gitlab's container registry fork (and back up their state before doing that).

Packages built for `x86_64-linux` and the NixOS test has passed. Rebased against master and marking this now as ready for review :)

**Comment by yu-re-ka** [comment]
I would prefer if the docker registry module would not be duplicated, as long as they are similar. Both maintenance-wise and evaluation performance wise.

**Comment by yayayayaka** [comment]
Good point. I could add a `services.dockerRegistry.package` option instead.

**Comment by yayayayaka** [comment]
I have added a package option to `services.dockerRegistry` in [dfa3775](https://github.com/NixOS/nixpkgs/pull/233904/commits/dfa37752da945916de77bdaecc07220c6db91772) and adapted the gitlab module. Looks much cleaner now.

**Review by yu-re-ka — APPROVED** [review]

**Comment by yu-re-ka** [comment]
@mweinelt @RaitoBezarius  This will have to be backported to 23.05, since 15.x is not provided with security updates for the whole duration of the 23.05 release cycle, and I would say this is possible according to the backporting criteria `Security critical applications (E.g. firefox)`.

However how do 23.05 release notes entries work at this point?

**Comment by mweinelt** [comment]
> However how do 23.05 release notes entries work at this point?

Into master and then backport, because otherwise the copy of rl-2305 on master would run out of sync.

**Pull request merged**
