### PR TITLE
haskellPackages.hnix: unbreak

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
Yes, situation is explained in:
https://github.com/haskell-nix/hnix/issues/921#issuecomment-832556733

In short:
> It was done deliberately, because some instances were upstreamed to `ref-tf`, so to not have clashing instances and to get notification when `ref-tf` would do the relese - the bounds were put such.

**Comment by cdepillabout** [comment]
It looks like there was an error, but the build was able to continue for some reason:

```
[30 of 50] Compiling Nix.Fresh        ( src/Nix/Fresh.hs, dist/build/Nix/Fresh.o, dist/build/Nix/Fresh.dyn_o )

src/Nix/Fresh.hs:72:10: error:
    Duplicate instance declarations:
      instance MonadAtomicRef (ST s) -- Defined at src/Nix/Fresh.hs:72:10
      instance [safe] MonadAtomicRef (ST s)
        -- Defined in ‘Control.Monad.Ref’
   |
72 | instance MonadAtomicRef (ST s) where
   |          ^^^^^^^^^^^^^^^^^^^^^
```

Looks like `MonadAtomicRef (ST s)` was defined twice.

**Comment by sternenseemann** [comment]
Unfortunately, we can't pin ref-tf to < 0.5 since it is part of stackage already (maybe hnix should be added to stackage again…). Thus I've backported <https://github.com/haskell-nix/hnix/pull/918> which fixes the issue.

**Review by maralorn — APPROVED** [review]
I mean this probably could have been done with fetchPatch, but since we will rip this out on the next hnix release, I don‘t care.

Let’s merge as soon as it builds.

**Comment by sternenseemann** [comment]
> I mean this probably could have been done with fetchPatch, but since we will rip this out on the next hnix release, I don‘t care.

It can't unless you apply like 5 intermediate patches since the PR patch doesn't apply.

**Comment by maralorn** [comment]
> > I mean this probably could have been done with fetchPatch, but since we will rip this out on the next hnix release, I don‘t care.
> 
> It can't unless you apply like 5 intermediate patches since the PR patch doesn't apply.

I had a look at it and thought it could be done by preprocessing the patch to only apply to those two files.

**Comment by sternenseemann** [comment]
> I had a look at it and thought it could be done by preprocessing the patch to only apply to those two files.

Nope `src/Nix/Fresh.hs` doesn't apply because the comment above the instance was updated in the mean time.

**Comment by Anton-Latukha** [comment]
> Unfortunately, we can't pin ref-tf to < 0.5 since it is part of stackage already (maybe hnix should be added to stackage again…). Thus I've backported [haskell-nix/hnix#918](https://github.com/haskell-nix/hnix/pull/918) which fixes the issue.

No, sorry, it not seem possible in thee near future. & please don't contribute it, project is not ready NOR in backwards support stage while Stackage is created & designed for stable projects. If HNix is on Stackage - because of big breakages & current slow cadence - maintaining HNix in Stackage & Nixpkgs would be a headache to all 3.

I can not promise Stackage stability, we can not even promise Hackage-Nixpkgs stability, at least because `hnix-store-core` has infra of very rigid code that hammered with nails to `cryptohash-sha512` which is a sinking ship abandoned by captain https://github.com/haskell-hvr/cryptohash-sha512/pull/5, since nor I nor other managed to change it - I already tried to rewrite that part several times, but so far was not able to replace it, do what is possible.

**Comment by sternenseemann** [comment]
Ack. We'll just keep on duct taping it together in here as it is almost critical infrastructure at this point.

**Pull request merged**
