### PR TITLE
aflplusplus: 2.64c -> 4.06c

### PR DESCRIPTION
**Pull request by Mindavi**
###### Description of changes

https://github.com/AFLplusplus/AFLplusplus/releases/tag/4.06c

Lots of changes between the versions.

Based on work started here: https://github.com/NixOS/nixpkgs/pull/211189

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lopsided98** [comment]
Should be updated to 4.06c (I tested this and no changes are required beside updating version number and hash), and perhaps LLVM 15 as well (not tested).

**Comment by lopsided98** [comment]
I also noticed these lines in the build log:
```
substituteStream(): WARNING: pattern '../qemu-mode/unsigaction/unsigaction32.so' doesn't match anything in file 'test/test-qemu-mode.sh'
substituteStream(): WARNING: pattern '../qemu-mode/unsigaction/unsigaction64.so' doesn't match anything in file 'test/test-qemu-mode.sh'
```

**Comment by Mindavi** [comment]
Ok, updated. I think this is good to go now.

**Comment by Mindavi** [comment]
Glad that I can finally cross this off my todo list :)

**Pull request merged**
