### PR TITLE
libreoffice-still: 7.5.9.2 -> 7.6.5.2, libreoffice-fresh: 7.6.4.1 -> 24.2.0.3, libreoffice-bin: 7.6.4 -> 7.6.5

### LINKED ISSUE #291896: Package request: update libreoffice packages
Hello

1. Is it possible to update versions of libreoffice? @7c6f434c @tricktron 
7c6f434c@mail.ru

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=libreoffice

Current versions based on website are (https://www.libreoffice.org/download/download-libreoffice/)

**7.6.5**
**7.6.4**
7.5.9
**24.2.0**

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
fixes https://github.com/NixOS/nixpkgs/issues/291896
cc @KCynk

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
A test case of libreoffice-still fails:
```
[_RUN_____] testFootnoteConnect::TestBody
file:///build/libreoffice-7.6.5.2//sw/qa/core/text/data//footnote-connect.fodt:
testFootnoteConnect::TestBody finished in: 326ms
porrst.cxx:85:Assertion
Test name: (anonymous namespace)::testFloattableAnchorHeight::TestBody
equality assertion failed
- Expected: 1
- Actual  : 2

Failures !!!
Run: 57   Failure total: 1   Failures: 1   Errors: 0

Error: a unit test failed, please do one of:

make CppunitTest_sw_core_text CPPUNITTRACE="gdb --args"
    # for interactive debugging on Linux
make CppunitTest_sw_core_text VALGRIND=memcheck
    # for memory checking
make CppunitTest_sw_core_text DEBUGCPPUNIT=TRUE
    # for exception catching

You can limit the execution to just one particular test by:

make CPPUNIT_TEST_NAME="testXYZ" ...above mentioned params...

make[1]: *** [/build/libreoffice-7.6.5.2/solenv/gbuild/CppunitTest.mk:130: /build/libreoffice-7.6.5.2/workdir/CppunitTest/sw_core_text.test] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:291: build] Error 2
```
Any ideas?

**Comment by dotlambda** [comment]
I also don't understand the libreoffice-fresh build failure because we do have `zlib` in `buildInputs`.

**Comment by 7c6f434c** [comment]
Strictly speaking `zlib` being in `buildInputs` is more about `ld` not complaining about failing to find `libz`, here I guess `-lz` is not passed where it should be? Almost tempted to just enfoce `-lz` via `NIX_LDFLAGS`…

**Comment by K900** [comment]
Bumping this, we probably don't want to ship 24.05 with an ancient Libreoffice...

**Comment by tricktron** [comment]
@dotlambda I started applying the hints of @7c6f434c and with some more tests disabled libreoffice-still and libreoffice-fresh should build again. Here is the diff:

```diff
diff --git a/pkgs/applications/office/libreoffice/default.nix b/pkgs/applications/office/libreoffice/default.nix
index e8229b528e53..c1a6354237e1 100644
--- a/pkgs/applications/office/libreoffice/default.nix
+++ b/pkgs/applications/office/libreoffice/default.nix
@@ -309,7 +309,8 @@ in stdenv.mkDerivation (finalAttrs: {
     sed -e '/CPPUNIT_TEST(testTdf115013);/d' -i sw/qa/extras/uiwriter/uiwriter.cxx
     # rendering-dependent test
     # tilde expansion in path processing checks the existence of $HOME
-    sed -e 's@OString sSysPath("~/tmp");@& return ; @' -i sal/qa/osl/file/osl_File.cxx
+    sed -e '/CPPUNIT_TEST(getFileURLFromSystemPath_001);/d' -i sal/qa/osl/file/osl_File.cxx
+    sed -e '/CPPUNIT_TEST(getFileURLFromSystemPath_001_81);/d' -i sal/qa/osl/file/osl_File.cxx
     # fails on systems using ZFS, see https://github.com/NixOS/nixpkgs/issues/19071
     sed -e '/CPPUNIT_TEST(getSystemPathFromFileURL_005);/d' -i './sal/qa/osl/file/osl_File.cxx'
     # rendering-dependent: on my computer the test table actually doesn't fit…
@@ -386,18 +387,21 @@ in stdenv.mkDerivation (finalAttrs: {
     sed -e '/CPPUNIT_ASSERT_EQUAL(17, nEndRunPos);/d' -i './vcl/qa/cppunit/text.cxx'
     sed -e '/CPPUNIT_ASSERT_EQUAL(22, nEndRunPos);/d' -i './vcl/qa/cppunit/text.cxx'
 
+    sed -e '/CPPUNIT_TEST(testApng);/d' -i './vcl/qa/cppunit/png/PngFilterTest.cxx'
+
     # testReqIfTable fails since libxml2: 2.10.3 -> 2.10.4
     sed -e 's@.*"/html/body/div/table/tr/th".*@//&@' -i sw/qa/extras/htmlexport/htmlexport.cxx
   '' /* This to avoid using /lib:/usr/lib at linking */ + ''
     sed -i '/gb_LinkTarget_LDFLAGS/{ n; /rpath-link/d;}' solenv/gbuild/platform/unxgcc.mk
 
-    find -name "*.cmd" -exec sed -i s,/lib:/usr/lib,, {} \;
-  '' + optionalString stdenv.isAarch64 ''
-    sed -e '/CPPUNIT_TEST(testStatisticalFormulasFODS);/d' -i './sc/qa/unit/functions_statistical.cxx'
-  '' + optionalString (variant == "fresh") ''
+    # started to fail from version 7.6.5.2
     sed -e '/CPPUNIT_ASSERT_EQUAL(static_cast<size_t>(1), pPage3Objs->size());/d' -i './sw/qa/core/text/porrst.cxx'
     sed -e '/CPPUNIT_ASSERT(pPage4Objs);/d' -i './sw/qa/core/text/porrst.cxx'
     sed -e '/CPPUNIT_ASSERT_EQUAL(static_cast<size_t>(1), pPage4Objs->size());/d' -i './sw/qa/core/text/porrst.cxx'
+
+    find -name "*.cmd" -exec sed -i s,/lib:/usr/lib,, {} \;
+  '' + optionalString stdenv.isAarch64 ''
+    sed -e '/CPPUNIT_TEST(testStatisticalFormulasFODS);/d' -i './sc/qa/unit/functions_statistical.cxx'
   '';
 
   makeFlags = [ "SHELL=${bash}/bin/bash" ];
@@ -516,6 +520,8 @@ in stdenv.mkDerivation (finalAttrs: {
     wrapQtAppsHook
   ];
 
+  NIX_LDFLAGS = "-lz";
+
   buildInputs = with xorg; finalAttrs.passthru.gst_packages ++ [
     ArchiveZip
     CoinMP
```

Otherwise you can also look at my branch for the three additional commits: https://github.com/NixOS/nixpkgs/compare/master...tricktron:nixpkgs:libreoffice-7.6.5.

Could you add these changes and then we could give ofborg a spin and see if it builds?

**Comment by K900** [comment]
I've root caused most of those tests on my branch last night, I'll try to push it up later today.

**Comment by K900** [comment]
Pushed my WIP branch: https://github.com/NixOS/nixpkgs/pull/312998

libreoffice-fresh-qt6 should at least build on that, I'll confirm everything tomorrow

**Comment by K900** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/312998.

**Pull request closed without merging**
