### PR TITLE
python-packages/power: Fix build due to falsely declared dependency.

### PR DESCRIPTION
**Pull request by ambrop72**
This is relevant for master and release-16.03.

### CODE REVIEW

**Comment by joachifm** [comment]
Travis error looks legit:
```
  File "/tmp/nix-build-python3.5-power-1.2.drv-0/power-1.2/power/win32.py", line 9, in <module>

    from ctypes import Structure, wintypes, POINTER, windll, WinError, pointer, WINFUNCTYPE

  File "/nix/store/ln2cn6g6rf116vaq1fgngaqzpzfq495x-python3-3.5.1/lib/python3.5/ctypes/wintypes.py", line 20, in <module>

    class VARIANT_BOOL(ctypes._SimpleCData):

ValueError: _type_ 'v' not supported

builder for ‘/nix/store/b97b169wh2xms79qk8vgh4agfv0xk57f-python3.5-power-1.2.drv’ failed with exit code 1

error: build of ‘/nix/store/b97b169wh2xms79qk8vgh4agfv0xk57f-python3.5-power-1.2.drv’ failed
```

**Comment by ambrop72** [comment]
This is a Python3 specific issue, it seems fixed upstream (https://github.com/Kentzo/Power/commits/master). I'll try a bump to version 1.4.

**Comment by ambrop72** [comment]
I changed the pull request to an update to 1.4 instead. On my system it builds both for Python 2.7 and 3.4. But I really only care about the 2.7 so that Pronterface works.

**Comment by joachifm** [comment]
If python3 is a problem, you could also simply disable it for the time being, just include an explanatory note.

**Comment by ambrop72** [comment]
I see there's still an error with Python 3.5 (but not 3.4). I've disable the tests, this should make it pass (I think the tests can't work because they want access to real power information).

**Pull request merged**
