### PR TITLE
Isabelle: 2020 -> 2021

### PR DESCRIPTION
**Pull request by jvanbruegge**
###### Motivation for this change

The new version has serveral improvements and is out since april

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jvanbruegge** [comment]
The polyml update was necessary for isabelle, otherwise the theories would not build. I've put it in a separate commit

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130583` at 9111bd40 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>isabelle</li>
    <li>tlaps</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/a12e297b1257eb1f663fd09357db6f04">hol</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>polyml</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by jvanbruegge** [comment]
`hydra-check` tells me that `hol` is broken on aarch64 for some time now, so this build failure is expected

**Comment by jvanbruegge** [comment]
I've now added a .desktop entry for isabelle too. The file is generated and placed correctly, but I am fairly new to nixos, so I don't know how to test that it is correct. It does not show up in my rofi when running `nix-build -A isabelle`

**Comment by siraben** [comment]
@jvanbruegge thanks for the update. Currently building Isabelle 2021 from this PR. Are you familiar enough with `holmake` to help get CakeML to build? I have an attempt [here](https://github.com/siraben/nixpkgs/commit/b509f2c3a52752d38b26219410ae651b69bceb2b) but I'm currently stuck on the lack of documentation on `holmake`.

**Comment by jvanbruegge** [comment]
Sorry, no idea

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130583` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>hol</li>
    <li>isabelle</li>
    <li>polyml</li>
    <li>tlaps</li>
  </ul>
</details>

**Comment by siraben** [comment]
Thanks!

**Pull request merged**
