### PR TITLE
remove openstack

### PR DESCRIPTION
**Pull request by FRidh**
The openstack Python packages are broken, outdated and unmaintained.
This commit removes the packages.

To do:
- [ ] remove modules
- [ ] remove tests

### CODE REVIEW

**Comment by FRidh** [comment]
Original PR is https://github.com/NixOS/nixpkgs/pull/10399.

**Comment by makefu** [comment]
oslo* packages are required by tempest-lib -> sqlalchemy_migrate -> buildbot

Removing would mean a chain-reaction of removals of packages. At least buildbot received an update within the last weeks

**Comment by makefu** [comment]
and here we are once again, 4 months later :)
unfortunately the PR now has a lot of conflicts, i will retry what you have done 👍

**Comment by FRidh** [comment]
Closing because #32637 is merged.

**Pull request closed without merging**
