### PR TITLE
signald: 0.19.1 -> 0.23.0

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes
__Note:__ I guess it'd make sense to backport, but perhaps we should do it in a less invasive way, i.e. without having to migrate all your data. OTOH I'm not sure if it's a good idea to cherry-pick db migrations from later versions as it'd perhaps cause issues on later upgrades, so I'm open for suggestions.

Replaces/Closes #174256

Needed because the CA of a signal server seems to have changed[1] which has caused the following errors to appear while trying to send messages from Matrix (via `mautrix-signal` and subsequently `signald`):

    ⚠ Your message was not bridged:
    org.whispersystems.signalservice.api.push.exceptions.PushNetworkException,
    javax.net.ssl.SSLHandshakeException,
    sun.security.validator.ValidatorException,
    sun.security.provider.certpath.SunCertPathBuilderException:
    org.whispersystems.signalservice.api.push.exceptions.PushNetworkException:
    javax.net.ssl.SSLHandshakeException:
    PKIX path building failed:
    sun.security.provider.certpath.SunCertPathBuilderException:
    unable to find valid certification path to requested target

Migration can be performed by running a command like

    $ signald \
        -d /var/lib/signald/data \
        --database sqlite:/var/lib/signald/db \
        -s /run/signald/signald.sock \
        --migrate-data

before starting signald itself.

ChangeLogs:

* https://gitlab.com/signald/signald/-/blob/main/releases/0.20.0.md
* https://gitlab.com/signald/signald/-/blob/main/releases/0.21.0.md
* https://gitlab.com/signald/signald/-/blob/main/releases/0.22.0.md
* https://gitlab.com/signald/signald/-/blob/main/releases/0.22.1.md
* https://gitlab.com/signald/signald/-/blob/main/releases/0.22.2.md
* https://gitlab.com/signald/signald/-/blob/main/releases/0.23.0.md

[1] https://gitlab.com/signald/signald/-/blob/main/releases/0.23.0.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Flakebi** [comment]
I get a hash-mismatch:
```
error: hash mismatch in fixed-output derivation '/nix/store/8vnd53mwx5wqalv7dnw5xn9syiyc9a7r-signald-deps-0.23.0.drv':
         specified: sha256-ANiNDdTuCuDEH5zUPsrVF6Uegdq3zVsMv+uMtYRX0jE=
            got:    sha256-6VpKKj4FrPwj5M/2OWmN/fq/naJmxKGOFNR1fhtX0mo=
```

With the fixed hash, signald works again for me.

**Comment by Ma27** [comment]
@flakebi Cannot reproduce and the CI also agrees with the hash I pushed.

A few things that might've caused this: did you cherry-pick the commit onto another branch before building? From which country did you perform the requests? (Perhaps a different CDN is at fault, but I really hope it's not the case although I observed it once).

Can you perhaps share the fixed-output-path of `signald-deps` so that we can diff for the actual changes that caused the mismatch on your end?

**Comment by Flakebi** [comment]
Building the branch of this PR works fine, I got the mismatch when running `nixpkgs-review` :)

**Comment by Ma27** [comment]
> Building the branch of this PR works fine, I got the mismatch when running nixpkgs-review :)

Ok... which attribute path exactly failed? Can you give me a command, please?

> Edit: When I build the PR branch first and then try nixpkgs-review, it works fine, I guess that’s because the hash with the (incorrect) hash is already in my store now.

Yes. You can remove it again with either `nix-collect-garbage` or `nix-store --delete`.

**Review by Flakebi — APPROVED** [review]
When I tried back then, the command was `nixpkgs-review pr 198121`.
But I can’t reproduce it anymore when merging this into `nixos-unstable`, I also get `sha256-ANiNDdTuCuDEH5zUPsrVF6Uegdq3zVsMv+uMtYRX0jE=` as the correct hash now.

**Comment by ajs124** [comment]
Maybe the migration steps should be mentioned in the release notes for 22.11

**Comment by Ma27** [comment]
You're right, sorry. Will file a PR later for that, thanks for pointing this out! :)

**Pull request merged**
