### PR TITLE
Port elk initdb kafka

### PR DESCRIPTION
**Pull request by tfc**
###### Motivation for this change

#72828

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @worldofpeace @flokli

### CODE REVIEW

**Comment by tfc** [comment]
@GrahamcOfBorg test initdb elk kafka

**Comment by flokli** [comment]
`initdb` is missing from `all-tests.nix`. Also, it might make sense to just include this with the other postgresql tests.

**Comment by tfc** [comment]
>  Also, it might make sense to just include this with the other postgresql tests.

Do you mean including in the sense of grouping it into another existing postgres test file or giving it a similar name like the others?

**Comment by flokli** [comment]
Whatever you feel to be more appropriate. Personally, I'd say it's small enough to just group it into an existing test.

**Comment by tfc** [comment]
> Whatever you feel to be more appropriate. Personally, I'd say it's small enough to just group it into an existing test.

Oh, you mean actually putting the code into the test script of an existing test. That makes sense, too. I am on it.

**Comment by tfc** [comment]
@flokli done, please have a look.

**Comment by tfc** [comment]
@GrahamcOfBorg test postgres

**Comment by tfc** [comment]
@GrahamcOfBorg test postgresql

**Review by flokli — APPROVED** [review]

**Pull request merged**
