### PR TITLE
python312Packages.protobuf5: 5.27.2 -> 5.28.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

~~Adopt the same logic as for `python312Packages.protobuf4` by syncing the version to the one of the associated `protobuf` library.~~

cc @SuperSandro2000 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338157` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>mitmproxy (python312Packages.mitmproxy)</li>
    <li>mitmproxy.dist (python312Packages.mitmproxy.dist)</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.mitmproxy</li>
    <li>python311Packages.mitmproxy.dist</li>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.protobuf5</li>
    <li>python311Packages.protobuf5.dist</li>
    <li>python312Packages.protobuf5</li>
    <li>python312Packages.protobuf5.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338157` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>mitmproxy (python312Packages.mitmproxy)</li>
    <li>mitmproxy.dist (python312Packages.mitmproxy.dist)</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.mitmproxy</li>
    <li>python311Packages.mitmproxy.dist</li>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.protobuf5</li>
    <li>python311Packages.protobuf5.dist</li>
    <li>python312Packages.protobuf5</li>
    <li>python312Packages.protobuf5.dist</li>
  </ul>
</details>

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
protobuf 4 used the source code from the protobuf package. With protobuf 5 this is no longer possible, so taking the version from it is not really necessary. See https://github.com/protocolbuffers/protobuf/commit/5722aeffcad72e9a335a3ec7985858dfa31477be for details

We should probably add a comment though, to sync the packages up.

**Comment by GaetanLepage** [comment]
> protobuf 4 used the source code from the protobuf package. With protobuf 5 this is no longer possible, so taking the version from it is not really necessary. See [protocolbuffers/protobuf@5722aef](https://github.com/protocolbuffers/protobuf/commit/5722aeffcad72e9a335a3ec7985858dfa31477be) for details

I am well aware of this as @SomeoneSerge and I have spent a few hours fighting to build newer versions of the protobuf python package from source despite them removing `setup.py`.
Unfortunately, bazel eventually won the fight and we silently gave up on this.

I am happy that you went with adding the pypi version as at least, we have it now.



> taking the version from it is not really necessary.

Sure, this is not strictly needed now, but I would prefer to hard-code the sync whether than to rely on a comment.
Though, I can also add a comment to warn about updating the hash of the python derivation.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338157` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>mitmproxy (python312Packages.mitmproxy)</li>
    <li>mitmproxy.dist (python312Packages.mitmproxy.dist)</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.mitmproxy</li>
    <li>python311Packages.mitmproxy.dist</li>
    <li>python311Packages.protobuf5</li>
    <li>python311Packages.protobuf5.dist</li>
    <li>python312Packages.protobuf5</li>
    <li>python312Packages.protobuf5.dist</li>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338157` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>mitmproxy (python312Packages.mitmproxy)</li>
    <li>mitmproxy.dist (python312Packages.mitmproxy.dist)</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.mitmproxy</li>
    <li>python311Packages.mitmproxy.dist</li>
    <li>python311Packages.protobuf5</li>
    <li>python311Packages.protobuf5.dist</li>
    <li>python312Packages.protobuf5</li>
    <li>python312Packages.protobuf5.dist</li>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>

**Comment by SomeoneSerge** [comment]
To be clear, it's not impossible, we "just" need to get bazel build for the source tarball to work. If we use the tarball I'm very much uncomfortable keeping `sourceProvenance = [ fromSource ]`

**Comment by SuperSandro2000** [comment]
Bazel is known for being notorious distro hostile and I personally really dislike using any of my time for it.

> If we use the tarball I'm very much uncomfortable keeping sourceProvenance = [ fromSource ]

That doesn't matter as long as the tarball doesn't contain precompiled shared objects which I don't think it does.

**Comment by SuperSandro2000** [comment]
> Sure, this is not strictly needed now, but I would prefer to hard-code the sync whether than to rely on a comment.
Though, I can also add a comment to warn about updating the hash of the python derivation.

I don't because at some point it will be forgotten to update and we won't notice it because of FODs. Also the releases don't necessarily need to be in sync. So this will just cause trouble in the end.

**Comment by GaetanLepage** [comment]
> I don't because at some point it will be forgotten to update and we won't notice it because of FODs. Also the releases don't necessarily need to be in sync. So this will just cause trouble in the end.

Ok fair enough, I simply updated the package.
Let us try to avoid having problems later indeed !

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338157` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>mitmproxy (python312Packages.mitmproxy)</li>
    <li>mitmproxy.dist (python312Packages.mitmproxy.dist)</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.mitmproxy</li>
    <li>python311Packages.mitmproxy.dist</li>
    <li>python311Packages.protobuf5</li>
    <li>python311Packages.protobuf5.dist</li>
    <li>python312Packages.protobuf5</li>
    <li>python312Packages.protobuf5.dist</li>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338157` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>mitmproxy (python312Packages.mitmproxy)</li>
    <li>mitmproxy.dist (python312Packages.mitmproxy.dist)</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.mitmproxy</li>
    <li>python311Packages.mitmproxy.dist</li>
    <li>python311Packages.protobuf5</li>
    <li>python311Packages.protobuf5.dist</li>
    <li>python312Packages.protobuf5</li>
    <li>python312Packages.protobuf5.dist</li>
    <li>wapiti</li>
    <li>wapiti.dist</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
