### PR TITLE
rambox: 0.6.3 -> 0.6.6

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build rambox

**Comment by Mic92** [comment]
Currently have an issue with whatsapp though: https://github.com/ramboxapp/community-edition/issues/2207#issuecomment-483605784

**Comment by mrVanDalo** [comment]
Checked it (unsing `nix-review pr 59701`) on my 18.09 and it works.

**Comment by Ma27** [comment]
Built and tested locally :+1:

**Comment by Ma27** [comment]
@Mic92 thanks!

**Comment by Ma27** [comment]
Backported as 70546dbd6b8bda434c960d52f68a2737891e2938.

**Pull request merged**
