### PR TITLE
hydra_unstable: 2022-06-16 -> 2022-06-30

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
This fixes declarative jobsets with dynamic runcommand enabled: https://github.com/NixOS/hydra/pull/1230

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
Hm, weird how it failed in ofborg. Let's give it another try.

@ofborg build

@ofborg test

**Comment by NickCao** [comment]
> Hm, weird how it failed in ofborg. Let's give it another try.
> 
> @ofborg build
> 
> @ofborg test

Likely a over strict timeout, this happened too the last time: https://github.com/NixOS/nixpkgs/pull/177884

**Comment by Mindavi** [comment]
I have a dirty hack locally to increase timeouts, but it's not really ideal...

**Review by Mindavi — APPROVED** [review]

**Comment by Mindavi** [comment]
Behold:

```patch
diff --git a/pkgs/development/tools/misc/hydra/unstable.nix b/pkgs/development/tools/misc/hydra/unstable.nix
index 709af8f4485..5f280da546c 100644
--- a/pkgs/development/tools/misc/hydra/unstable.nix
+++ b/pkgs/development/tools/misc/hydra/unstable.nix
@@ -211,6 +211,19 @@ stdenv.mkDerivation rec {
 
   enableParallelBuilding = true;
 
+  postPatch = ''
+      # Change 5s timeout for init to 30s
+        substituteInPlace t/lib/HydraTestContext.pm \
+          --replace 'expectOkay(5, ("hydra-init"));' 'expectOkay(30, ("hydra-init"));'
+
+        for file in t/**; do
+          echo fixing up $file
+          substituteInPlace $file \
+            --replace 'use warnings;' 'use warnings; \
+# HARNESS-TIMEOUT-EVENT 240'
+        done
+  '';
+
   preCheck = ''
     patchShebangs .
     export LOGNAME=''${LOGNAME:-foo}
```

The yath / Test2 harness thingey should accept this to change the default timeout from 60 seconds to 240 seconds. The hydra-init was also timing out for me when I was hacking on this while my PC was overloaded.

**Comment by NickCao** [comment]
> The yath / Test2 harness thingey should accept this to change the default timeout from 60 seconds to 240 seconds. The hydra-init was also timing out for me when I was hacking on this while my PC was overloaded.

Can't the timeout be set globally in some sort of entrypoint?

**Comment by Mindavi** [comment]
Not that I could find, I looked at the documentation for quite a while but it wasn't easy to dig through. This seems the only way. You cannot even use an env variable AFAICT...

But of course, this stuff should be more of an upstream thing to handle, if we apply a patch like this I wouldn't want to carry it forever.

**Comment by NickCao** [comment]
I stressed my laptop out, still cannot reproduce the timeouts in tests, I believe the default time out of 60 seconds should be long enough. I do reproduce the timeout in hydra-init, and let's see if ofborg is happy with this patch only.

**Comment by Mindavi** [comment]
Yeah, think I was basically 'lucky' that I could produce that, just the one patch seems to make ofborg happy already.

**Pull request merged**
