### PR TITLE
ipfs service: Fix dataDir being ignored

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change

IPFS uses the environment variable `IPFS_PATH` to determine where to look for it's data, which wasn't set previously therefore ignoring the `dataDir` attribute.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mguentner** [comment]
Ref: #21992

**Comment by Mic92** [comment]
What is your opinion on that? @mguentner

**Comment by Infinisil** [comment]
There should also be added some note that TCP port 4001 optimally should be opened.

**Comment by mguentner** [comment]
That looks good to me, I am still not sure what to do with #21992. IMHO the IPFS_PATH should only be visible in the context of the daemon.

**Comment by Infinisil** [comment]
I tested this now and it works with as is with the folder permissions, I'm not sure why though. I tested pinning and adding.

I'm not sure how PR's are handled exactly, #21992 has the same intention as this one, but doesn't actually work. With this PR `IPFS_PATH` is indeed only visible to the daemon and the systemd services.

**Comment by Infinisil** [comment]
I just noticed something that was wrong all along: In the `ipfs-start` service, the script checks for `${cfg.dataDir}/.ipfs` to already exists. But that folder never even gets generated by `ipfs init`. The confusion probably came from the default value `~/.ipfs`.

Instead we should check for `${cfg.dataDir}/config`, as [the main implementation does](https://github.com/ipfs/go-ipfs/blob/a6e96e6c99c4240427af6c3bd9a9ca1b4cea99b4/repo/fsrepo/fsrepo.go#L194-#L203). I'm going to open a new PR for that when I get the time.

**Pull request merged**
