### PR TITLE
mesa: fix intel-clc not taking disabled

### LINKED ISSUE #314457: Build failure: pkgsCross.gnu64.mesa
### Steps To Reproduce

1. build `pkgsCross.gnu64.mesa`

### Build log

```
mesonConfigurePhase flags: --prefix=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0 --libdir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/lib --libexecdir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/libexec --bindir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/bin --sbindir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/sbin --includedir=/nix/store/mh16gxvqnhxmlyg1w63lj0flrhw0cpyc-mesa-x86_64-unknown-linux-gnu-24.1.0-dev/include --mandir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/share/man --infodir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/share/info --localedir=/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/share/locale -Dauto_features=enabled -Dwrap_mode=nodownload --buildtype=plain --cross-file=/nix/store/zr093aj44614ygmsh8w1mhyj7apzjvr0-cross-file.conf --sysconfdir=/etc --datadir=/nix/store/wbqckknyckk1k79fh9vgi08ws2zkk3sb-mesa-x86_64-unknown-linux-gnu-24.1.0-drivers/share -Db_ndebug=true -Ddri-search-path=/run/opengl-driver/lib/dri -Dplatforms=x11\,wayland -Dgallium-drivers=swrast\,asahi -Dvulkan-drivers=swrast -Ddri-drivers-path=/nix/store/wbqckknyckk1k79fh9vgi08ws2zkk3sb-mesa-x86_64-unknown-linux-gnu-24.1.0-drivers/lib/dri -Dvdpau-libs-path=/nix/store/wbqckknyckk1k79fh9vgi08ws2zkk3sb-mesa-x86_64-unknown-linux-gnu-24.1.0-drivers/lib/vdpau -Domx-libs-path=/nix/store/wbqckknyckk1k79fh9vgi08ws2zkk3sb-mesa-x86_64-unknown-linux-gnu-24.1.0-drivers/lib/bellagio -Dva-libs-path=/nix/store/wbqckknyckk1k79fh9vgi08ws2zkk3sb-mesa-x86_64-unknown-linux-gnu-24.1.0-drivers/lib/dri -Dd3d-drivers-path=/nix/store/wbqckknyckk1k79fh9vgi08ws2zkk3sb-mesa-x86_64-unknown-linux-gnu-24.1.0-drivers/lib/d3d -Dgallium-nine=false -Dosmesa=true -Dmicrosoft-clc=disabled -Dgbm-backends-path=/run/opengl-driver/lib/gbm:/nix/store/vz7qmp20z3jr2bv3yv3p2v7zbhiwi8yi-mesa-x86_64-unknown-linux-gnu-24.1.0/lib/gbm -Dandroid-libbacktrace=disabled -Dglvnd=true -Dintel-clc=disabled -Dgallium-opencl=icd -Dopencl-spirv=true -Dgallium-rusticl=true -Dclang-libdir=/nix/store/d4nbdy4n0dcl36dsb0dr5sv3kb4m8wn7-clang-x86_64-unknown-linux-gnu-17.0.6-lib/lib -Dvideo-codecs=all -Dvulkan-layers=device-select\,overlay\,intel-nullhw -Dgallium-va=disabled -Dgallium-vdpau=disabled -Dgallium-xa=disabled -Dandroid-libbacktrace=disabled -Dlibunwind=disabled -Dlmsensors=disabled
The Meson build system
Version: 1.4.0
Source dir: /build/source
Build dir: /build/source/build
Build type: cross build

meson.build:21:0: ERROR: Value "disabled" (of type "string") for combo option "Build the intel-clc compiler or use a system version." is not one of the choices. Possible choices are (as string): "enabled", "system", "auto".

A full log can be found at /build/source/build/meson-logs/meson-log.txt
```

### Additional context

On Asahi but the Mesa derivation is based on upstream and this is during a cross compile so Asahi stuff shouldn't effect this in this context. It seems `-Dintel-clc=disabled` is no longer valid.

### Notify maintainers

@primeos @vcunat

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-linux"`
 - host os: `Linux 6.8.9-asahi, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

Fixes Mesa cross compiling for gnu64 when on aarch64 and on Asahi.

Fixes #314457

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
We don't support building arbitrary versions of packages in Nixpkgs.  This should either be worked around downstream, or you can wait for #306791.

**Review by K900 — CHANGES_REQUESTED** [review]
We absolutely should not be merging this without the rest of Mesa 24.1 changes, especially since it takes a staging cycle to implement.

**Comment by alyssais** [comment]
(To work around this downstream in an overlay, you could use `filterAttrs` to filter out Nixpkgs' intel-clc option, and then append your own.)

**Comment by RossComputerGuy** [comment]
This PR doesn't fix my actual problem. https://github.com/tpwrules/nixos-apple-silicon/pull/203 fixes my actual problem.

**Pull request closed without merging**
