### PR TITLE
maintainers: remove jfrankenau

### PR DESCRIPTION
**Pull request by katexochen**
They seem to be inactive and not responsive regarding the packages they maintain.

- Last commit >4 years ago: https://github.com/NixOS/nixpkgs/commits/master/?author=jfrankenau
- Last review nearly 4 years ago: https://github.com/jfrankenau?tab=overview&from=2021-12-01&to=2021-12-31
- 202 PRs mentioning them, only 9 reviews years ago: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+jfrankenau

I'll add an issue for the unmaintained packages as soon as this PR is approved.

**Please wait at least 1 week before merging this, so the have time to react, see [maintainer policy](https://github.com/NixOS/nixpkgs/tree/master/maintainers#how-to-lose-maintainer-status)**

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by IogaMaster — APPROVED** [review]

**Comment by OPNA2608** [comment]
> **see [maintainer policy](https://github.com/NixOS/nixpkgs/tree/master/maintainers#how-to-lose-maintainer-status)**

You forgot to request a review from them.

> Removing the maintainer happens by making a PR on the package, **adding that person as a reviewer**, and then waiting a week for a reaction.

**Comment by katexochen** [comment]
> You forgot to request a review from them.
> 
> > Removing the maintainer happens by making a PR on the package, **adding that person as a reviewer**, and then waiting a week for a reaction.

Good point. I somehow expected CI to tag them, but makes sense it doesn't know that I think about it.

**Review by bjornfor — APPROVED** [review]

**Review by jfrankenau — APPROVED** [review]
LGTM. While I still use NixOS on my servers, I don't use it as my main desktop OS anymore. I've been already thinking about removing myself from the maintainers list but as most of those pull requests have been automated, it didn't seem too urgent.

**Comment by katexochen** [comment]
Thanks @jfrankenau for the work you did back then! Come back anytime. ❤️

**Pull request merged**
