### PR TITLE
conftest: return to less ldflags

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

Go back to just injecting the version

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS (x86_64)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 104293` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>conftest</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> Go back to just injecting the version

This explains what you are doing but not why. Do you just want to clean it up or is it causing issues? Just curious.

**Comment by 06kellyjac** [comment]
`-s` is an ld flag to strip but the patch phase (or maybe a different phase) does that anyway. `-w` is a flag I've seen a lot but I wasn't super knowledgable about.
Apparently the ldflag `-s` can strip a bit more thoroughly than `strip` so I guess it could be left in. `-w` apparently removes "DWARF generation" which would save a small amount too.

I guess they could stay in...
I'll try compare the two sizes with and without

**Comment by SuperSandro2000** [comment]
> size reduction is nothing to stick your nose up at.

It is. If we would that treewide it would be a bad decision.

``-s -w`` strip debugging information we don't need. It is fine to have them. We have them 103 times in nixpkgs (https://github.com/NixOS/nixpkgs/search?q=-ldflags%3D-s+-w) and it should probably be a default.

This PR should be closed.

**Comment by 06kellyjac** [comment]
> size reduction is nothing to stick your nose up at.

Means it's a significant size reduction


Yeah it'd be nice to have them default but I think you should be able to turn them off to

**Pull request closed without merging**
