### PR TITLE
kubernetes: fix startup by setting systemd as cgroup driver

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/108960#issuecomment-770993006

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
I don't know if this is difficult, but could we have a test for those cases :thinking: ?

**Comment by Mic92** [comment]
> I don't know if this is difficult, but could we have a test for those cases thinking ?

There is a test for kubernetes. I am sure it broke in the process.

**Comment by petabyteboy** [comment]
We could add the kubernetes test to docker.pussthru.tests.

**Review by ghost — APPROVED** [review]
I can confirm this fixes the kubernetes NixOS tests.

**Review by roberth — CHANGES_REQUESTED** [review]
Seems like the right fix because it also improves stability according to the docs, but does require instructions in the release notes, because of the following:

> Changing the cgroup driver of a Node that has joined a cluster is strongly not recommended.
If the kubelet has created Pods using the semantics of one cgroup driver, changing the container runtime to another cgroup driver can cause errors when trying to re-create the Pod sandbox for such existing Pods. Restarting the kubelet may not solve such errors.

> If you have automation that makes it feasible, replace the node with another using the updated configuration, or reinstall it using automation.

  -- https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

**Comment by petabyteboy** [comment]
We could decide it based on the stateVersion in the module and set the system to use the old cgroup API if it's an old stateVersion.

**Comment by Mic92** [comment]
> Seems like the right fix because it also improves stability according to the docs, but does require instructions in the release notes, because of the following:
> 
> > Changing the cgroup driver of a Node that has joined a cluster is strongly not recommended.
> > If the kubelet has created Pods using the semantics of one cgroup driver, changing the container runtime to another cgroup driver can cause errors when trying to re-create the Pod sandbox for such existing Pods. Restarting the kubelet may not solve such errors.
> 
> > If you have automation that makes it feasible, replace the node with another using the updated configuration, or reinstall it using automation.
> 
> -- [kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers)

Not sure when I get back to this. When somebody else beat me to write the release notes I will cherry-pick from there.

**Comment by Mic92** [comment]
Closing this for now for someone else to pick up.

**Pull request closed without merging**
