### PR TITLE
nyxt: 2.0.0 -> 2.2.3

### PR DESCRIPTION
**Pull request by bhankas**
###### Motivation for this change
Upstream update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Fails to build https://logs.nix.ci/?key=nixos/nixpkgs.127906&attempt_id=5a411908-0dcc-4e67-b1b8-c28bd13a07ab

**Comment by p3s** [comment]
> Fails to build https://logs.nix.ci/?key=nixos/nixpkgs.127906&attempt_id=5a411908-0dcc-4e67-b1b8-c28bd13a07ab

Build successful and working.

**Comment by SuperSandro2000** [comment]
I think it boils down to ``Symbol "WEBKIT-SCRIPT-DIALOG-REF" not found in the CL-WEBKIT2 package.``

@ofborg build nyxt

**Comment by johnrichardrinehart** [comment]
Output of `nix log /nix/store/<derivation-path>.drv`
```
mkdir: cannot create directory '/homeless-shelter': Permission denied
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/1rcb941nfbd3hn6ncfpxmxn5zgkv2wib-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
glibPreInstallPhase
@nix { "action": "setPhase", "phase": "installPhase" }
installing
cp: cannot stat 'LICENCE': No such file or directory
cp: cannot stat 'LICENSE': No such file or directory
cp: cannot stat 'COPYING': No such file or directory
cp: cannot stat 'README': No such file or directory
cp: cannot stat 'README.html': No such file or directory
cp: cannot stat 'README.md': No such file or directory
cp: cannot stat 'readme.html': No such file or directory
/nyxt.asd /nix/store/8f9pbwnzj47qjj7hnfcgs93pzjyxjhx3-lisp-nyxt-2.2.3/lib/common-lisp/nyxt/nyxt-ubuntu-package.asd 96 ckage.asd
/nyxt.asd /nix/store/8f9pbwnzj47qjj7hnfcgs93pzjyxjhx3-lisp-nyxt-2.2.3/lib/common-lisp/nyxt/nyxt.asd 81 /nyxt.asd
This is SBCL 2.1.9.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
WARNING: System definition file #P"/nix/store/rivlj3ic2znyqv9rsa0g4hmw41z78afz-lisp-calispel-20170830-git/lib/common-lisp/calispel/calispel.asd" contains definition for system "calispel-test". Please only define "calispel" and secondary systems with a name starting with "calispel/" (e.g. "calispel/test") in that file.
WARNING: System definition file #P"/nix/store/v19zc2mz5372xhymajkbghndiwvswzi5-lisp-cl-json-20141217-git/lib/common-lisp/cl-json/cl-json.asd" contains definition for system "cl-json.test". Please only define "cl-json" and secondary systems with a name starting with "cl-json/" (e.g. "cl-json/test") in that file.
WARNING: System definition file #P"/nix/store/p8v1v1cj9r7shmpvl38135khdxlvhvb7-lisp-cl-ppcre-unicode-cl-ppcre-20190521-git/lib/common-lisp/cl-ppcre-unicode/cl-ppcre-unicode.asd" contains definition for system "cl-ppcre-unicode-test". Please only define "cl-ppcre-unicode" and secondary systems with a name starting with "cl-ppcre-unicode/" (e.g. "cl-ppcre-unicode/test") in that file.
WARNING: System definition file #P"/nix/store/i33qd1l7xc0hxsqbfn6dbmcqpmhp6pg1-lisp-s-xml-20150608-git/lib/common-lisp/s-xml/s-xml.asd" contains definition for system "s-xml.test". Please only define "s-xml" and secondary systems with a name starting with "s-xml/" (e.g. "s-xml/test") in that file.
WARNING: System definition file #P"/nix/store/i33qd1l7xc0hxsqbfn6dbmcqpmhp6pg1-lisp-s-xml-20150608-git/lib/common-lisp/s-xml/s-xml.asd" contains definition for system "s-xml.examples". Please only define "s-xml" and secondary systems with a name starting with "s-xml/" (e.g. "s-xml/test") in that file.
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                              {1004AD0173}>:
  Component ASDF/USER::CL-QRENCODE not found, required by #<SYSTEM "nyxt">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1004AD0173}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component ASDF/USER::CL-QRENCODE not found, required by #<SYSTEM "nyxt"> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* Component ASDF/USER::CL-QRENCODE not found, required by #<SYSTEM "nyxt">)
2: (INVOKE-DEBUGGER Component ASDF/USER::CL-QRENCODE not found, required by #<SYSTEM "nyxt">)
3: (ERROR ASDF/FIND-COMPONENT:MISSING-DEPENDENCY :REQUIRED-BY #<ASDF/SYSTEM:SYSTEM "nyxt"> :REQUIRES ASDF/USER::CL-QRENCODE)
4: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "nyxt"> ASDF/USER::CL-QRENCODE NIL)
5: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1003170B2B}>)
6: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
7: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
8: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {1002EDDA63}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> NIL)
9: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {100316D33B}>)
10: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
11: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
12: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {1002EDDA63}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> NIL)
13: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10031681DB}>)
14: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
15: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
16: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {1002EDDA63}> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> T)
17: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10030028FB}>)
18: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
19: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
20: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {1002EDDA63}> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> T)
21: ((LAMBDA NIL :IN ASDF/PLAN:MAKE-PLAN))
22: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
23: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt">)
24: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
25: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt">) [fast-method]
26: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:COMPILE-OP :NYXT)
27: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
28: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:COMPILE-OP :NYXT) [fast-method]
29: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10048FDE1B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
30: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
31: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100320DC1B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
32: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:COMPILE-OP :NYXT) [fast-method]
33: (ASDF/OPERATE:COMPILE-SYSTEM :NYXT)
34: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:COMPILE-SYSTEM :NYXT) #<NULL-LEXENV>)
35: (SB-IMPL::SIMPLE-EVAL-PROGN-BODY ((ASDF/OPERATE:COMPILE-SYSTEM :NYXT) (ASDF/OPERATE:LOAD-SYSTEM :NYXT) (ASDF/OPERATE:OPERATE (QUOTE ASDF/BUNDLE:COMPILE-BUNDLE-OP) :NYXT) (IGNORE-ERRORS (ASDF/OPERATE:OPERATE (QUOTE ASDF/INTERFACE::DEPLOY-ASD-OP) :NYXT))) #<NULL-LEXENV>)
36: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (ASDF/OPERATE:COMPILE-SYSTEM :NYXT) (ASDF/OPERATE:LOAD-SYSTEM :NYXT) (ASDF/OPERATE:OPERATE (QUOTE ASDF/BUNDLE:COMPILE-BUNDLE-OP) :NYXT) (IGNORE-ERRORS (ASDF/OPERATE:OPERATE (QUOTE ASDF/INTERFACE::DEPLOY-ASD-OP) :NYXT))) #<NULL-LEXENV>)
37: (EVAL (PROGN (ASDF/OPERATE:COMPILE-SYSTEM :NYXT) (ASDF/OPERATE:LOAD-SYSTEM :NYXT) (ASDF/OPERATE:OPERATE (QUOTE ASDF/BUNDLE:COMPILE-BUNDLE-OP) :NYXT) (IGNORE-ERRORS (ASDF/OPERATE:OPERATE (QUOTE ASDF/INTERFACE::DEPLOY-ASD-OP) :NYXT))))
38: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(load \"/nix/store/izhk74kqws2d4b1xh76vrjhdja62w8iy-cl-wrapper-script/lib/common-lisp/asdf/build/asdf.fasl\")") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (15535)) 
  (progn
    (setf asdf:*source-registry-parameter*
      '(:source-registry
        (:tree "/nix/store/0bahjaz1m17x6ss1h1kh5f3caf4wh8zp-lisp-stefil-20181210-git/lib/common-lisp/stefil")
(:tree "/nix... {100157000F}>) (:EVAL . "(progn
      (asdf:compile-system :nyxt)
(asdf:load-system :nyxt)
(asdf:operate (quote asdf::compile-bundle-op) :nyxt)
(ignore-errors (asdf:operate (quote asdf::deploy-asd-op) :nyxt))

      )") (:EVAL . "(quit)") (:QUIT)))
39: (SB-IMPL::TOPLEVEL-INIT)
40: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
41: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
42: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by peterhoeg** [comment]
We carry 2.2.3 now (although it's broken).

**Pull request closed without merging**
