### PR TITLE
gmic, gmic-qt: switch to opencv3

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
opencv2 is essentially EOL and has security concerns

opencv is reportedly only used for webcam input in `gmic`, and I've successfully managed to get webcam pictures with this built against `opencv3`.

Reverse dependencies `gimpPlugins.gmic` and `gimp-with-plugins` seem to be already broken on master.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jtojnar** [comment]
Could you open an upstream issue/PR about switching to OpenCV 4?

**Comment by risicle** [comment]
Good idea.

**Comment by risicle** [comment]
There already seems to be noise around building with opencv4 https://github.com/dtschump/gmic/issues/166

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
