### PR TITLE
wl-mirror: 0.14.2 -> 0.15.0

### PR DESCRIPTION
**Pull request by Ferdi265**
## Description of changes

This PR updates wl-mirror to release [0.15.0](https://github.com/Ferdi265/wl-mirror/releases/tag/v0.15.0); notable new features are the `--fullscreen` and `--fullscreen-output` options.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@Synthetica9 @twitchyliquid64 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GetPsyched — CHANGES_REQUESTED** [review]
Could you please update this?
```patch
- description = "Mirrors an output onto a Wayland surface.";
+ description = "Mirrors an output onto a Wayland surface";
```
Perhaps even matching the upstream description:

> A simple Wayland output mirror client

Following: https://nixos.org/manual/nixpkgs/stable/#var-meta-description

**Comment by GetPsyched** [comment]
Result of `nixpkgs-review pr 277710` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wl-mirror</li>
  </ul>
</details>

**Comment by Ferdi265** [comment]
> Could you please update this?
> 
> ```diff
> - description = "Mirrors an output onto a Wayland surface.";
> + description = "Mirrors an output onto a Wayland surface";
> ```
> 
> Perhaps even matching the upstream description:
> 
> > A simple Wayland output mirror client
> 
> Following: https://nixos.org/manual/nixpkgs/stable/#var-meta-description

updated

**Comment by Ferdi265** [comment]
now matches upstream description

**Comment by Ferdi265** [comment]
now split into two commits, looks cleaner IMO

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
