### PR TITLE
pypi-mirror: init at 4.0.6

### PR DESCRIPTION
**Pull request by kamadorueda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
This looks more like a CLI tool than a module. How about adding it to `all-packages.nix` (e. g., `pypi-mirror = with python3.pkgs; toPythonApplication python-pypi-mirror;`)?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 134276` at 975dce04 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.python-pypi-mirror</li>
    <li>python39Packages.python-pypi-mirror</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/development/python-modules/python-pypi-mirror/default.nix:21:0:
```
   |
21 |     description = "A script to create a partial PyPI mirror";
   | ^
```
</li>
  </ul>
</details>

**Comment by putchar** [comment]
Result of `nixpkgs-review pr 134276` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.python-pypi-mirror</li>
    <li>python39Packages.python-pypi-mirror</li>
  </ul>
</details>

**Comment by kamadorueda** [comment]
> This looks more like a CLI tool than a module. How about adding it to `all-packages.nix` (e. g., `pypi-mirror = with python3.pkgs; toPythonApplication python-pypi-mirror;`)?

done

**Pull request merged**
