### PR TITLE
signal-desktop: 6.30.2 -> 6.31.0, signal-desktop-beta: 6.31.0-beta.1 -> 6.32.0-beta.1

### PR DESCRIPTION
**Pull request by equirosa**
### Updates

- signal-desktop: https://github.com/signalapp/Signal-Desktop/releases/tag/v6.31.0
- signal-desktop-beta: https://github.com/signalapp/Signal-Desktop/releases/tag/v6.32.0-beta.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by kilianar — APPROVED** [review]
The changes do look good to me. A quick test of the binaries indicates that everything appears to be functioning correctly.

---

Result of `nixpkgs-review pr 256435` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>signal-desktop</li>
    <li>signal-desktop-beta</li>
  </ul>
</details>

**Comment by delroth** [comment]
FWIW the release notes don't explicitly say so, but I've confirmed that the new -beta uses [electron 25.8.1](https://github.com/signalapp/Signal-Desktop/blob/v6.32.0-beta.1/package.json#L272) which is patched.

**Review by delroth — APPROVED** [review]

**Comment by delroth** [comment]
Ugh, can you do the cherry-pick manually and cc me on the PR? Thanks!

**Comment by equirosa** [comment]
On September 21, 2023 8:25:23 AM CST, Pierre Bourdon ***@***.***> wrote:
>Ugh, can you do the cherry-pick manually and cc me on the PR? Thanks!
>

Dang it! I knew I probably had missed some backports before. I'll get that done ASAP

**Comment by equirosa** [comment]
Upon closer inspection, it might be rather difficult to cherry-pick this commit directly, since the versions in `release-23.05` weren't updated from commits in `master`. I'll just make a PR for that branch with the same versions in this one.

**Pull request merged**
