### PR TITLE
ghcHEAD: bump to 8.11.20200403

### PR DESCRIPTION
**Pull request by ggreif**
###### Motivation for this change

Previous status quo was totally outdated

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build haskell.compiler.ghcHEAD

**Comment by ggreif** [comment]
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_09

**Review by peti — APPROVED** [review]
:+1:

**Comment by cdepillabout** [comment]
@ggreif Is this ready to be merged in?

**Comment by ggreif** [comment]
@cdepillabout I guess so. We can iterate if something is missing.

**Pull request merged**
