### PR TITLE
gitea: 1.20.5 -> 1.21.1

### LINKED ISSUE #267517: Update request: gitea 1.20.5 → 1.21.1
- Package name: gitea
- Latest released version: 1.21.1 ([go-gitea/gitea v1.21.1 release](https://github.com/go-gitea/gitea/releases/tag/v1.21.1))

- Current version on the unstable channel: 1.20.5
- Current version on the stable/release channel: 1.19.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**: @disassembler @kolaente @Ma27 @techknowlogick 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by techknowlogick**
## Description of changes

fix https://github.com/NixOS/nixpkgs/issues/267517

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 267531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gitea</li>
    <li>gitea.data</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Comment by adamcstephens** [comment]
This release has multiple breaking changes.

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
I think this update is worth mentioning in the 24.05 release notes.

**Comment by msfjarvis** [comment]
> I think this update is worth mentioning in the 24.05 release notes.

List of breaking changes from the Gitea release notes to hopefully speed this along.

- Custom themes and other assets that were previously stored in `custom/public/*` now belong in `custom/public/assets/*`
- Config option `[server].SSH_AUTHORIZED_KEYS_BACKUP` now defaults to `false`
- New instances of Gitea using MySQL now ignore the `[database].CHARSET` config option and always use the `utf8mb4` charset, existing instances should migrate via the `gitea doctor convert` CLI command
- The CLI was refactored to more strictly enforce parameter ordering, see [here](https://blog.gitea.com/release-of-1.21.0/#%EF%B8%8F-refactor-gitea-cli-25959) for some examples
- The inbuilt SSH server now validates that certificates used in authentication are user certificates and not server certificates, matching the behavior of OpenSSH
- Gitea Actions no longer has a "running" status for commits

**Comment by adamcstephens** [comment]
Result of `nixpkgs-review pr 267531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gitea</li>
    <li>gitea.data</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 267531` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gitea</li>
    <li>gitea.data</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 267531` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gitea</li>
    <li>gitea.data</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 267531` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>gitea</li>
    <li>gitea.data</li>
  </ul>
</details>

**Review by adamcstephens — COMMENTED** [review]
Please add release notes for 24.05 about the breaking changes. Referring to upstream for details is fine with me.

**Comment by SuperSandro2000** [comment]
I think only those two things are relevant, the other changes are minor breaking ones and usually we don't mention them.

> * Custom themes and other assets that were previously stored in `custom/public/*` now belong in `custom/public/assets/*`
> * New instances of Gitea using MySQL now ignore the `[database].CHARSET` config option and always use the `utf8mb4` charset, existing instances should migrate via the `gitea doctor convert` CLI command

Also please update to https://github.com/go-gitea/gitea/releases/tag/v1.21.1

**Comment by adamcstephens** [comment]
There should probably be a backport of 1.20.6 to 23.11 along with bumping master to 1.21.x.

**Comment by LeSuisse** [comment]
Yep see #271552

**Review by SuperSandro2000 — APPROVED** [review]

**Review by chvp — APPROVED** [review]

**Review by LeSuisse — APPROVED** [review]

**Pull request merged**
