### PR TITLE
gitkraken: 9.13.0 -> 10.0.1

### PR DESCRIPTION
**Pull request by nicolas-goudry**
## Description of changes

- updated homepage to point to the specific page about GitKraken Desktop
- updated package description to match the way GitKraken is advertised by Axosoft
- updated the desktop item name to match the rebranding of the app to GitKraken Desktop
- updated the desktop item comment to match what is set on Ubuntu when installing GitKraken Desktop

[Release notes](https://help.gitkraken.com/gitkraken-client/current/#version-10-0-1)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nicolas-goudry** [comment]
Result of `nixpkgs-review pr 312051` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitkraken</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
@nicolas-goudry master is currently frozen from breaking changes, unless other think otherwise, i would delay this until master is unfrozen

**Comment by kirillrdy** [comment]
> How could this be considered as a breaking change though?

it probably isn't, i only saw from release notes that they did some renaming, and bumped a major version number

**Comment by nicolas-goudry** [comment]
Indeed they did rename a few things, improved support for Git executable and fixed some bugs. Aside from the renaming part, nothing is « breaking », and one could argue that renaming things isn’t really a breaking change. Anyway, I’ll wait for the unfreeze :slightly_smiling_face:

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> Is there a known date for the unfreeze? Is it related to the soon to be released 24.05 version of NixOS?

https://togithub.com/NixOS/nixpkgs/issues/303285

**Comment by nicolas-goudry** [comment]
Updated the PR to update GitKraken to v10.0.1 which includes a few bug fixes as well as an update of the bundled git binary (which we replace anyway)

**Comment by nicolas-goudry** [comment]
Result of `nixpkgs-review pr 312051` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitkraken</li>
  </ul>
</details>

**Pull request merged**
