### PR TITLE
firefox: 90.0.2 -> 91.0; firefox-esr-91: init at 91.0esr; firefox-bin: 90.0.2 -> 91.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://www.mozilla.org/en-US/firefox/91.0beta/releasenotes/

###### Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@taku0 Tried to use the firefox-bin updateScript but failed:

```
❯ nix-shell maintainers/scripts/update.nix --argstr package firefox-bin-unwrapped
error: anonymous function at /home/hexa/git/nixos/master/pkgs/applications/networking/browsers/firefox-bin/update.nix:1:1 called without required argument 'name', at /home/hexa/git/nixos/master/pkgs/applications/networking/browsers/firefox-bin/default.nix:189:27
(use '--show-trace' to show detailed location information)
```

**Comment by taku0** [comment]
@mweinelt Thank you for reporting.  Fixed #133246.

**Comment by mweinelt** [comment]
Tested and works, thank you!

**Comment by mweinelt** [comment]
- [x] nixosTests.firefox

- gUM testpage can't access camera/microphone/screenshare on sway/pipewire. Guess I'll have to reboot in a bit to rule out side effects.

  ```
  Uncaught (in promise) ReferenceError: can't access lexical declaration 'fps_number' before initialization
      startMedia http://mozilla.github.io/webrtc-landing/gum_test.html:207
      startScreen http://mozilla.github.io/webrtc-landing/gum_test.html:137
      onclick http://mozilla.github.io/webrtc-landing/gum_test.html:1
  gum_test.html:207:25
      startMedia http://mozilla.github.io/webrtc-landing/gum_test.html:245
      startScreen http://mozilla.github.io/webrtc-landing/gum_test.html:137
      onclick http://mozilla.github.io/webrtc-landing/gum_test.html:1
  ```

- Also for some YouTube videos that work on Firefox 90.0.2 I now get "Your browser can't play this video", e.g. https://www.youtube.com/watch?v=YsBe9BFIjBs
image

**Comment by vcunat** [comment]
Detail: I wonder if we'd better wait with ESR, say for one release cycle (or even have both ESRs for some time).  Either way, ESR 78 probably [ends life](https://wiki.mozilla.org/Release_Management/Calendar) significantly sooner than NixOS 21.05.

**Comment by mweinelt** [comment]
I guess we have to cross that bridge in 21.05, since the last 78esr release will be on 2021-10-05 and we'll likely support 21.05 until the end of 2021.

**Comment by yu-re-ka** [comment]
Is it intended that we change 78.x to build with icu69 as well?

**Comment by mweinelt** [comment]
Good question. Happy accident, though it still seems to work. I ran the `nixosTests.firefox-esr-78` test, but didn't do any further testing.

**Review by yu-re-ka — APPROVED** [review]
If you tested the changes to 78.x as well it looks good 👍🏻

**Review by ajs124 — APPROVED** [review]

**Comment by vcunat** [comment]
```
error: aggregate job 'tested' references non-existent job 'nixos.tests.firefox-esr.x86_64-linux'
```
https://github.com/NixOS/nixpkgs/pull/133388

**Pull request merged**
