### PR TITLE
fetch-cargo-tarball: allow use index mirror

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes

Allow to use a mirror when fetch the crates index. Since GitHub is blocked in mainland China this would be convenient.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I don't understand why this rebuild elfcat but LGTM.

**Comment by linsui** [comment]
Elfcat doesn't have cargo dep. It doesn't build for me so I fix it.

**Review by SuperSandro2000 — COMMENTED** [review]
Can you revert the formatting changes in the last commit? I think then this is good to merge.

**Comment by linsui** [comment]
Done. Thanks!

**Comment by linsui** [comment]
@SuperSandro2000 Kindly ping.

**Comment by bhipple** [comment]
Thanks for this @linsui.  Being able to use internal mirrors is also important in enterprise environments with strict firewalls, too, so it's great to see this feature!

**Comment by linsui** [comment]
Thanks!

**Comment by bhipple** [comment]
Merged since this is strictly better than the status quo, but an idea for follow-up: rather than relying on users to set the impure env var `NIX_CRATES_INDEX` manually, it'd be nice to have integration with `mirrors.nix` to pass this, the way we do for fetchurl.  That gives a more seamlessly automated experience.

https://github.com/NixOS/nixpkgs/blob/24f160cfcde277bcc61abe8a5f89f1e807bdc67f/pkgs/build-support/fetchurl/mirrors.nix

It'd be really nice to have a variable in here `cargoCratesMirrors` or something, with the default just being the 1 true canonical value, and have the cargo fetcher read it from `mirrors.nix`.  Then in your env you check in another mirror to this list and the rest works automatically.

**Comment by linsui** [comment]
> It'd be really nice to have a variable in here cargoCratesMirrors or something, with the default just being the 1 true canonical value, and have the cargo fetcher read it from mirrors.nix. Then in your nixpkgs branch you check-in another mirror to this list and the rest "just works", since the fetcher reads this and sets it in an impure env var automatically.

I didn't understand how it works. Do I need to add the mirror to the file everytime when I want to build a rust package?

**Pull request merged**
