### PR TITLE
rss-bridge: 2022-06-14 -> 2023-03-22

### PR DESCRIPTION
**Pull request by e1mo**
###### Description of changes

https://github.com/RSS-Bridge/rss-bridge/releases/tag/2023-03-22

The new config options don't require any action on the module side, since the config (currently) needs to be [placed manually in the data dir](https://github.com/NixOS/nixpkgs/blob/a64e169e396460d6b5763a1de1dd197df8421688/nixos/modules/services/web-apps/rss-bridge.nix#L45-L48).

###### Things done

[](https://github.com/RSS-Bridge/rss-bridge/releases/tag/2023-03-22)

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by megheaiulian — APPROVED** [review]
~Tested this and it works nicely!~

**Review by megheaiulian — CHANGES_REQUESTED** [review]
In fact because the location of  var declarations has changed the substitutes no longer work.
I had to adjust it this way to properly load the whitelist and config: 

``` 
substituteInPlace lib/RssBridge.php \
   --replace "__DIR__ . '/../config.ini.php'" "getenv('RSSBRIDGE_DATA') . '/config.ini.php'" \
substituteInPlace lib/bootstrap.php \
   --replace "const PATH_CACHE = __DIR__ . '/../cache/';" "define('PATH_CACHE', getenv('RSSBRIDGE_DATA') . '/cache/');" \
   --replace "const WHITELIST = __DIR__ . '/../whitelist.txt';" "define('WHITELIST', getenv('RSSBRIDGE_DATA') . '/whitelist.txt');"

```

Its probably better to use a patch since that fails when it can no longer be applied.

**Comment by e1mo** [comment]
Thanks for catching this @megheaiulian, my bad for missing this!

**Comment by e1mo** [comment]
@ofborg build rss-bridge

**Review by megheaiulian — APPROVED** [review]
Looks good to me!

**Comment by megheaiulian** [comment]
@ofborg 's  error seems unrelated. Maybe a rebase would fix that ?

**Comment by iNecas** [comment]
Seems all green now. Anything's blocking merging this one?

**Comment by e1mo** [comment]
Nothing I'm aware of.

**Comment by megheaiulian** [comment]
Meanwhile rss-bridge has had some minor non change breaking updates. 
Should we update to that in this PR or do it separately?

**Comment by SuperSandro2000** [comment]
Closing in favor of #257641

**Pull request closed without merging**
