### PR TITLE
qt5: 5.11 -> 5.12

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

@LnL7 could you test this on Mac Os?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]
No regressions on darwin.

**Comment by LnL7** [comment]
Err nevermind that was still 5.11, rebuilding...

**Review by ttuegel — APPROVED** [review]
Looks good to me! Do you have the source for the patches in Git somewhere?

**Comment by bkchr** [comment]
@ttuegel No, I don't have the patches in git somewhere. I just make apply them manually and refresh them as needed.

**Comment by bkchr** [comment]
@FRidh did you test it on macos?

**Comment by FRidh** [comment]
no

**Comment by matthewbauer** [comment]
It looks like one of the macOS patches is broken on master:

https://hydra.nixos.org/build/86897293

I think it just needs to be updated>

**Pull request merged**
