### PR TITLE
jellyfin-media-player: 1.10.1 -> 1.11.1

### PR DESCRIPTION
**Pull request by javaes**
## Description of changes
```
Client now uses jellyfin-web provided by server.
```

Solves https://github.com/NixOS/nixpkgs/issues/318121

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by nadir-ishiguro — APPROVED** [review]

**Comment by nadir-ishiguro** [comment]
Result of `nixpkgs-review pr 318854` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jellyfin-media-player</li>
  </ul>
</details>

**Review by nadir-ishiguro — COMMENTED** [review]
I might be wrong but could it be that we still need jellyfin-web to linked? Otherwise, were would the "external" jellyfin-web  jellyfin-media-player is looking for come from?

With 1.10.1, the patches make sure the external nixpkgs version of jellyfin-web gets bundled. That's 10.9.6 right now.

With 1.11.1 in an overlay I get `Web version: 10.9.3`. Same for `Build version` 

My overlay: 
```

    (final: prev: {
      jellyfin-media-player = prev.jellyfin-media-player.overrideAttrs (old: rec {
        pname = "jellyfin-media-player";
        version = "1.11.1";
        src = prev.fetchFromGitHub {
          # inherit pname version;
          owner = "jellyfin";
          repo = "jellyfin-media-player";
          rev = "v${version}";
          sha256 = "sha256-Jsn4kWQzUaQI9MpbsLJr6JSJk9ZSnMEcrebQ2DYegSU=";
        };
        patches = [
          # fix the location of the jellyfin-web path
          ./patches/disable-update-notifications.patch
        ];
        preConfigure = "";
      });
    })
```

**Comment by nadir-ishiguro** [comment]
You wrote:

> Client now uses jellyfin-web provided by server.

The changelog says: 

> This release switches Jellyfin Media Player to always use the external web client so that updates to jellyfin-web take effect immediately instead of when I get a chance to release the application.
> 
> Note: It is normal to have to log into your servers again after installing this update.

Correct me if I'm wrong, but the local jellyfin-media-player still needs access to a local jellyfin-web instance, right?

**Comment by javaes** [comment]
> You wrote:
> 
> > Client now uses jellyfin-web provided by server.
> 
> The changelog says:
> 
> > This release switches Jellyfin Media Player to always use the external web client so that updates to jellyfin-web take effect immediately instead of when I get a chance to release the application.
> > Note: It is normal to have to log into your servers again after installing this update.
> 
> Correct me if I'm wrong, but the local jellyfin-media-player still needs access to a local jellyfin-web instance, right?

No, `jellyfin-web` is not required. The comment you quoted intends to say tat the `jellyfin-media-player` should not need to be updated each time `jellyfin-web` (the web frontend deployed on the server) receives an updated, instead `jellyfin-web` is  fetched directly from the server.

I tested the build by running the resulting binary locally and connecting to one of my jellyfin servers, it works as intended.

**Comment by nadir-ishiguro** [comment]
Cool. Thanks for the explanation

**Pull request merged**
