### PR TITLE
metasploit: 3.3.1 -> 4.14.17

### LINKED ISSUE #8870: metasploit: package needs to be updated
The metasploit package no longer builds.  I've [tried](https://github.com/rdesfo/nixpkgs/commit/81c41d5896b82a70469b989cafb9918d05bb5333#commitcomment-12037805) updating it myself, but I haven't been very successful.

If someone could point out my mistake I would gladly correct it and submit a PR.

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

cc @makefu for testing

fixes #8870

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by TomSmeets** [comment]
When I try to install `msf` on nixos using your branch I get an invalid hash error

```
building path(s) ‘/nix/store/vvzn75zxnl5xrvc6479hn06cs2gpn0ja-metasploit-framework-fd3da8f’
exporting https://github.com/rapid7/metasploit-framework (rev fd3da8f3350d6cf7f0449bf0ead4d51747525c0a) into /nix/store/vvzn75zxnl5xrvc6479hn06cs2gpn0ja-metasploit-framework-fd3da8f
Initialized empty Git repository in /nix/store/vvzn75zxnl5xrvc6479hn06cs2gpn0ja-metasploit-framework-fd3da8f/.git/
remote: Counting objects: 9451, done.        
remote: Compressing objects: 100% (8195/8195), done.        
remote: Total 9451 (delta 1283), reused 3817 (delta 700), pack-reused 0        
Receiving objects: 100% (9451/9451), 24.86 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (1283/1283), done.
From https://github.com/rapid7/metasploit-framework
 * tag               4.14.17    -> FETCH_HEAD
Switched to a new branch 'fetchgit'
output path ‘/nix/store/vvzn75zxnl5xrvc6479hn06cs2gpn0ja-metasploit-framework-fd3da8f’ has r:sha256 hash ‘1r04drq34qfbhmhp0mqnm13vrycr7dcq670zk8xqiif5rhbij6qv’ when ‘100axxiibg5qx3xpv9znxxrkaa8jkcds5ln1qipna696026vvnnq’ was expected
cannot build derivation ‘/nix/store/dqs9zv6pn0ykcffysqjfj9ikwxffa7mc-ruby2.3.4-metasploit-framework-4.14.17.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/a24x99wkbwbalxj2gq3fz1xhp8c784bh-metasploit-bundler-env.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/2qkdkaqhsqkqawi7fpvalsq5axmzwli6-metasploit-framework-4.14.17.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/imxzb8qi1dfcdrnd6npr9vz0sljz86jb-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/l79yyrmici6lwgib1y61027fmk8yyilz-nixos-system-lambda-medion-17.09.git.f3dea82.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/l79yyrmici6lwgib1y61027fmk8yyilz-nixos-system-lambda-medion-17.09.git.f3dea82.drv’ failed
```

**Comment by makefu** [comment]
i can confirm, updating the hash of metasploit-framework to `1r04drq34qfbhmhp0mqnm13vrycr7dcq670zk8xqiif5rhbij6qv` fixes the issue. i will play around a bit with the modules to check everything works

**Comment by makefu** [comment]
Modules show up and the ones i've tested work as expected 👍 

```patch
diff --git a/pkgs/tools/security/metasploit/gemset.nix b/pkgs/tools/security/metasploit/gemset.nix
index c6bf6f27e0..f4e4b91fcd 100644
--- a/pkgs/tools/security/metasploit/gemset.nix
+++ b/pkgs/tools/security/metasploit/gemset.nix
@@ -179,7 +179,7 @@
     source = {
       fetchSubmodules = false;
       rev = "fd3da8f3350d6cf7f0449bf0ead4d51747525c0a";
-      sha256 = "100axxiibg5qx3xpv9znxxrkaa8jkcds5ln1qipna696026vvnnq";
+      sha256 = "1r04drq34qfbhmhp0mqnm13vrycr7dcq670zk8xqiif5rhbij6qv";
       type = "git";
       url = "https://github.com/rapid7/metasploit-framework";
     };
```

**Comment by fpletz** [comment]
Thanks for the update! We still have the wrong hash on master, though:

```
output path ‘/nix/store/x7dgkzib8danf8dyd8siq9jwcs6x8800-metasploit-framework-fd3da8f’ has r:sha256 hash ‘0gjzwrmb1z9wbpbgxmz0bxz63l894vwpv4ixj9nd7acnxfx9027r’ when ‘1r04drq34qfbhmhp0mqnm13vrycr7dcq670zk8xqiif5rhbij6qv’ was expected
cannot build derivation ‘/nix/store/y4h12hzybq02d33f7cd40hi3vdz90qwj-ruby2.3.4-metasploit-framework-4.14.17.drv’: 1 dependencies couldn't be built
```

@Mic92 Do you know why the hash changes? Is the `metasploit-framework` gem in the gemset even necessary?

**Comment by makefu** [comment]
@fpletz it seems like they (rapid7) force-push the release regularly ... I've subscribed to the release feed and in the last between 16. and 21. this happened three times for release `4.11.7`, always at 5:00 AM

**Comment by Mic92** [comment]
What the hack. This is evil.

**Comment by Mic92** [comment]
If we stick to git revision, can they be garbage collected by github, if they are not referenced?

**Comment by Mic92** [comment]
@makefu you fork the repo and we take this as source repo until upstream stops doing strange stuff.

**Comment by makefu** [comment]
@Mic92 it would probably better to pin the git ref to the latest hash in the `Gemfile` and default.nix, right? That way we can stay on upstream but still have stable source inputs.

**Pull request merged**
