### PR TITLE
nixos/acme: support "full.pem" (for lighttpd)

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
Be able to use letsencrypt / ACME certificates with lighttpd on NixOS.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by fpletz — APPROVED** [review]
LGTM but I just noticed that we're not checking if a plugin is enabled before chown/chmodding the pem files.

**Comment by bjornfor** [comment]
@fpletz: It seems the chown/chmod is only done on the selfsigned certificates, and those are created independently of what kind of plugins are enabled. (It may be cleaner if the selfsigned certificates were created based on the selected plugins, but that's a separate issue.)

Another possible concern: The webservers are configured to depend unconditionally on the selfsigned certificates target ("acme-selfsigned-certificates.target"). What happens if ```security.acme.preliminarySelfsigned = false```? I'll test later today.

**Comment by bjornfor** [comment]
>  What happens if security.acme.preliminarySelfsigned = false? I'll test later today.

I grepped the journal for "lighttpd\|systemd" after rebuilding my system with this config. There were no warnings/errors related to missing acme-selfsigned-certificates.target. So I guess we can leave that as is.

**Review by abbradar — APPROVED** [review]
Looks good! `ch{own,mod}`s are indeed done only for self-signed certificates -- we can improve that later but it doesn't seem serious.

**Comment by bjornfor** [comment]
Thanks! Applied to master (7a0e958b972f61b23f93a8e39fee5590aec47348, 6a55fda61e899092a7c73b6b004783bbf1a73773).

**Comment by fpletz** [comment]
Thank you both! :+1:

**Pull request closed without merging**
