### PR TITLE
nvidia-{docker,podman}: update

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
- libnvidia-container: 1.3.3 -> 1.5.0
- nvidia-container-runtime: 3.4.0 -> 3.5.0
- nvidia-container-toolkit: 1.3.0 -> 1.5.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 136958` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nvidia-docker</li>
    <li>nvidia-podman</li>
  </ul>
</details>

**Comment by cpcloud** [comment]
@lovesegfault Do you need me to test this on one of my boxen?

**Comment by lovesegfault** [comment]
> @lovesegfault Do you need me to test this on one of my boxen?

Yeah, that'd be great!

I've been having loads of issues with podman and nvidia support (before and after this patch), docker works fine

**Comment by cpcloud** [comment]
> I've been having loads of issues with podman and nvidia support (before and after this patch), docker works fine

Harumph. I can probably help you bisect that, since it used to work :/

**Comment by cpcloud** [comment]
I am able to execute a simple `nvidia-smi` command before and after this patch with both docker and podman using an upstream nvidia image:

```sh
❯ podman run --runtime nvidia --rm nvidia/cuda:11.2.1-base-ubi7 nvidia-smi --list-gpus
GPU 0: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-16efc9cd-6886-5c12-52f8-2bef887747d9)
```

```sh
❯ docker run --runtime nvidia --rm nvidia/cuda:11.2.1-base-ubi7 nvidia-smi --list-gpus
GPU 0: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-16efc9cd-6886-5c12-52f8-2bef887747d9)
```

I am also able to list devices from an upstream tensorflow image with both docker and podman:

```sh
❯ podman run -e TF_CPP_MIN_LOG_LEVEL=1 -e LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu --runtime nvidia --rm tensorflow/tensorflow:2.4.2-gpu python -c 'import tensorflow as tf; print(tf.config.list_physical_devices("GPU"))'
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

```sh
❯ docker run -e TF_CPP_MIN_LOG_LEVEL=1 -e LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu --runtime nvidia --rm tensorflow/tensorflow:2.4.2-gpu python -c 'import tensorflow as tf; print(tf.config.list_physical_devices("GPU"))'
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Pull request merged**
