### PR TITLE
sudo: backport fix for missing newlines

### PR DESCRIPTION
**Pull request by trofi**
Pull upstream fix for https://bugzilla.sudo.ws/show_bug.cgi?id=1057. Otherwise `sudo` breaks newlines for `stderr` as:

    $ { sudo printf "a\nb\nc\n" >&2; } |& nl
         1  a
                  2 b
                          3 c

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 248742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>charliecloud</li>
    <li>check_zfs</li>
    <li>lxqt.lxqt-sudo</li>
    <li>mysql-workbench</li>
    <li>passExtensions.pass-tomb</li>
    <li>pmbootstrap</li>
    <li>pmbootstrap.dist</li>
    <li>qsudo</li>
    <li>sudo</li>
    <li>tomb</li>
  </ul>
</details>

**Review by marsam — APPROVED** [review]

**Comment by delroth** [comment]
Not sure why it's worth me maintaining this package if stuff is just going to get merged before I get a chance to come back home and review...

**Comment by drupol** [comment]
Hi @delroth ,

I apologize for bypassing you; that was never my intention. Since the issue was introduced in the last pull request, I believed it was urgent to merge this PR as quickly as possible, so I went ahead and hit the big green button. I hope you understand my reasoning.

As a committer, it's common for us to merge trivial things without waiting for a maintainer's approval, but I recognize the importance of communication.

Now that I know you're active (and back from holiday), I will be more careful in the future and less trigger happy!

Thank you for your understanding, hope there's no hard feelings.

**Comment by delroth** [comment]
No hard feelings -- and I happen to not have any objection to this change anyway (thanks @trofi for tracking the root cause, filing the bug upstream, etc.!). The only thing I'd have done differently is get the reproducer added to nixos/tests/sudo.nix, but I'm just going to do this in a follow-up PR instead.

In general when there is an active maintainer I think they should always be involved in reviewing PRs - they're often the ones who will have to deal with the consequences, and they're the ones who know what best to check to validate changes.

It's not even a case of "back from holiday" here fwiw, I was out for a total of 8h yesterday (a weekend day), and I'd seen and read the bug report + fix PR on my phone as it happened. I don't think there was any particular emergency either. Unfortunately this is a case where nixpkgs has again 0 guidelines for what's proper etiquette. It doesn't help that some packages have maintainers listed that are completely inactive (including this one - eelco hasn't maintained this package for years, afaict).

cc @zimbatm who seems interested in non-technical problems in the nix* ecosystem

**Comment by zimbatm** [comment]
@drupol please wait a week before bypassing maintainers. Especially on critical packages like sudo that can have deep implications. But I know you were coming with good intentions.

@delroth do you have any opinions on who to add as a co-maintainer? sudo seems critical enough that adding a second active maintainer might be a good idea.

**Comment by drupol** [comment]
Understood on my side, no worries, I'll pay more attention.

**Pull request merged**
