### PR TITLE
_64gram: 1.1.31 -> 1.1.34 and disable self update

### LINKED ISSUE #334958: Build failure: _64garm
### Steps To Reproduce

1. have `_64gram` in configuration file
2. update

### Build log

```Fish
╭──╴ on NixOS 24.11.0 ❄️  
┆ ~ 
╰─> home-manager switch --flake /etc/nixos/.#hand7s                                                                                                                            was 2m51s ❲✗ ❳ at ❗ 00:01 
error: builder for '/nix/store/dkwf5hgaxyg3fbdli1hf37axrd9a2d8h-64gram-1.1.31.drv' failed with exit code 1;
       last 10 log lines:
       >       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       >   254 |         return FakeAudioDeviceModuleImpl::Create(task_factory, std::move(*boxed_renderer), std::move(*boxed_recorder), options);
       >       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       >   255 |       };
       >       |       ~
       > At global scope:
       > cc1plus: note: unrecognized command-line option '-Wno-unqualified-std-cast-call' may have been intended to silence earlier diagnostics
       > cc1plus: note: unrecognized command-line option '-Wno-ambiguous-reversed-operator' may have been intended to silence earlier diagnostics
       > cc1plus: note: unrecognized command-line option '-Wno-deprecated-volatile' may have been intended to silence earlier diagnostics
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/dkwf5hgaxyg3fbdli1hf37axrd9a2d8h-64gram-1.1.31.drv'.
error: 1 dependencies of derivation '/nix/store/a37mkwp12rrh7ifvym633gxj4cczrjd6-64gram-1.1.31-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iw23x736f0mkwsn4aph90p933l851gb4-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f0wdd58d5005v1z7q3x42q8w6qs5d4x2-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lm8fjyii9775qwj1i72zll308cvn0a4q-home-manager-generation.drv' failed to build
```

### Additional context

i just tried to update my nixos and hm, and got this :D

### Notify maintainers

@clot27 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```Bash

╭──╴ on NixOS 24.11.0 ❄️  
┆ ~ 
╰─> nix-shell -p nix-info --run "nix-info -m"                                                                                                                                            ❲✓ ❳ at ❗ 00:08 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.4-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240811.a58bc8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/h60m1fwahjd2mv6gsg77ji3vb4gpj4dk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by DDoSolitary**
## Description of changes

The old version is incompatible with the current version of tg_owt in nixpkgs, causing build errors.

Fixes #334958.

Also reverted an upstream commit that removed the compile time option to disable self updating.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by clot27** [comment]
Aha, thanks for fixing this, seems like this is what causing issues with ryantm's auto updates too.
64gram has a new update btw

**Review by clot27 — APPROVED** [review]

**Comment by eqfae** [comment]
I'm getting the error as well as wezterm wondering how to configure packages that fail to update to ignore the update and just use the old version.

**Review by s0me1newithhand7s — APPROVED** [review]

**Comment by s0me1newithhand7s** [comment]
> I'm getting the error as well as wezterm wondering how to configure packages that fail to update to ignore the update and just use the old version.

i also tried to pull it from `stable`, but got same error. i wonder why..

**Comment by DDoSolitary** [comment]
@clot27 Thanks, updated to 1.1.34

**Comment by s0me1newithhand7s** [comment]
```Shell
-- Configuring incomplete, errors occurred!
note: keeping build directory '/tmp/nix-build-64gram-1.1.34.drv-0/build'
error: builder for '/nix/store/zadqdqgivfschx0h6dbfnzwiclxqd5zf-64gram-1.1.34.drv' failed with exit code 1;
       last 10 log lines:
       >
       >     adaConfig.cmake
       >     ada-config.cmake
       >
       >   Add the installation prefix of "ada" to CMAKE_PREFIX_PATH or set "ada_DIR"
       >   to a directory containing one of the above files.  If "ada" provides a
       >   separate development package or SDK, be sure it has been installed.
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/zadqdqgivfschx0h6dbfnzwiclxqd5zf-64gram-1.1.34.drv'.
```
erm..

**Comment by DDoSolitary** [comment]
@s0me1newithhand7s The package builds fine on master. It seems that your local nixpkgs is not new enough. Note that the ada dependencies was introduced only a few days ago #331396

**Comment by s0me1newithhand7s** [comment]
> @s0me1newithhand7s The package builds fine on master. It seems that your local nixpkgs is not new enough. Note that the ada dependency was introduced only a few days ago #331396

yep, digged into this and now i run "nixpkgs-review".

**Comment by s0me1newithhand7s** [comment]
```Shell
╭──╴ on NixOS 24.11.0 ❄️  
┆ nixpkgs 
╰─> nix run nixpkgs#nixpkgs-review -- pr 335448 --eval ofborg
```
got
```Shell
━ 1 Errors: 
┃ error: builder for '/nix/store/j781gfmrxqljmmpbk3di2c224yrzn0pn-64gram-1.1.34.drv' failed with exit code 1;
┃        last 10 log lines:
┃        > [1101/1513] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/dialogs/dialogs_inner_widget.cpp.o
┃        > [1102/1513] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_compose_search.cpp.o
┃        > [1103/1513] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_voice_record_bar.cpp.o
┃        > [1104/1513] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/dialogs/dialogs_widget.cpp.o
┃        > /build/source/Telegram/SourceFiles/dialogs/dialogs_widget.cpp: In lambda function:
┃        > /build/source/Telegram/SourceFiles/dialogs/dialogs_widget.cpp:830:28: warning: variable 'row' set but not used [-Wunused-but-set-variable]
┃        >   830 |                 const auto row = controller->activeChatEntryCurrent();
┃        >       |                            ^~~
┃        > [1105/1513] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/history/view/controls/history_view_compose_controls.cpp.o
┃        > ninja: build stopped: subcommand failed.
┃        For full logs, run 'nix log /nix/store/j781gfmrxqljmmpbk3di2c224yrzn0pn-64gram-1.1.34.drv'.
```
seems like telegram-side issue?

**Comment by DDoSolitary** [comment]
@s0me1newithhand7s As ofborg built this package without issues, I'm inclined to believe that it's a problem with your local machine. Your partial log doesn't show the actual error that caused the build failure you can check the full log as suggested by the last log line:

```
For full logs, run 'nix log /nix/store/j781gfmrxqljmmpbk3di2c224yrzn0pn-64gram-1.1.34.drv'.
```

**Review by s0me1newithhand7s — APPROVED** [review]

**Review by clot27 — APPROVED** [review]

**Pull request merged**
