### PR TITLE
ycmd: build with python3

### LINKED ISSUE #64048: PYTHONPATH handling in neovim breaks YouCompleteMe
## Issue description

Here's an `strace` of `nvim` where the YouCompleteMe plugin (running python3 as the plugin host in `nvim`, presumably; see trace below) attempts to start the `ycmd` server (a python2 program):

```
215 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python27.zip", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                
216 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib", {st_mode=S_IFDIR|0555, st_size=134, ...}) = 0                                                                                                                                                                                                                                                       
217 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python27.zip", 0x7fffe1f0f430) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                
218 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                   
219 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib", {st_mode=S_IFDIR|0555, st_size=134, ...}) = 0                                                                                                                                                                                                                                                       
220 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7", 0x7fffe1f0f430) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                   
221 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/plat-linux2", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                       
222 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                   
223 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib", {st_mode=S_IFDIR|0555, st_size=134, ...}) = 0                                                                                                                                                                                                                                                       
224 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/plat-linux2", 0x7fffe1f0f430) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                       
225 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/lib-tk", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                            
226 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                   
227 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib", {st_mode=S_IFDIR|0555, st_size=134, ...}) = 0                                                                                                                                                                                                                                                       
228 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/lib-tk", 0x7fffe1f0f430) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                            
229 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/lib-old", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                           
230 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                   
231 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib", {st_mode=S_IFDIR|0555, st_size=134, ...}) = 0                                                                                                                                                                                                                                                       
232 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/lib-old", 0x7fffe1f0f430) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                           
233 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/lib-dynload", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                       
234 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7", 0x7fffe1f0c3b0) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                                   
235 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib", {st_mode=S_IFDIR|0555, st_size=134, ...}) = 0                                                                                                                                                                                                                                                       
236 stat("/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env/lib/python2.7/lib-dynload", 0x7fffe1f0f430) = -1 ENOENT (No such file or directory)                                                                                                                                                                                                                       
237 write(2, "ImportError", 11)             = 11                                                                                                                                                                                                                                                                                                                                  
238 write(2, ": ", 2)                       = 2                                                                                                                                                                                                                                                                                                                                   
239 write(2, "No module named site", 20)    = 20                                                                                                                                                                                                                                                                                                                                  
240 write(2, "\n", 1)                       = 1                                                                                                                                                                                                                                                                                                                                   
```

It would seem that the neovim package does something such that when a python3 neovim plugin starts a python2 program, the python2 program's idea of `PYTHONHOME` is set to the environment created for the remote plugin host.

This can be confirmed running this in `nvim`:

```
:py import os; print(os.environ['PYTHONHOME'])                                                                                                                                                                                                                                                                                                                                    
```

That will print the `/nix/store/xxwxhdpasj6mcv3mvxdd4n3hyp13izd0-python3-3.7.2-env` path from above.

### Steps to reproduce

```
$ strace -o process_dump -ff nvim
```

Note that the ycm plugin complains about the server shutting down. Look through the traces to see the aforementioned "ImportError: No module named site" message.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.0-17-generic, Ubuntu, 19.04 (Disco Dingo)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixpkgs"`
 - channels(cstrahan): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/cstrahan/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Should resolve  #64048 where nvim and ycmd pythonpaths conflict.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@grahamcofborg build ycmd

**Comment by cstrahan** [comment]
You'll also need to change this line to use `python3` instead of `python`: 
https://github.com/NixOS/nixpkgs/blob/01e07b19967547d93e6ce2008366bc011ae0e358/pkgs/misc/vim-plugins/overrides.nix#L420

**Comment by cstrahan** [comment]
Also, it would seem that YouCompleteMe has changed the name of that variable to `ycm_python_interpreter_path`, so you'll want to check that the above substitution is actually working -- I think you'll need to change the variable name appropriately.

**Comment by jonringer** [comment]
Applied suggestions :)

**Comment by cstrahan** [comment]
Awesome. Sorry it's taken me a while to get back to this, it's been a busy week.

Thanks!

**Pull request merged**
