### PR TITLE
msmtp: 1.6.4 -> 1.6.6 and make it nix friendly

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

I'm not changing any functionality (apart from adding support for logging to the journal), but simply making ```msmtpq``` behave better by fixing paths to ```/nix/store```.

Works as daily driver here.

Cc: @garbas 

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by fpletz — APPROVED** [review]

**Review by garbas — APPROVED** [review]

**Comment by peterhoeg** [comment]
@jwiegley so the new libbsd is in master. Any change on your side?

**Comment by jwiegley** [comment]
Just tried now, no change in the build error.

**Comment by peterhoeg** [comment]
@jwiegley, can you build libbsd on its own?

**Comment by jwiegley** [comment]
No, I cannot.

**Comment by peterhoeg** [comment]
I've opened an issue for this #23434 as I don't see it being related to msmtp.

**Comment by grahamc** [comment]
The issue is `netcat` is an alias to `netcat-openbsd`, which depends on libbsd.

**Comment by peterhoeg** [comment]
That explains it @grahamc, thanks. But the real issue is that libbsd doesn't build on darwin. Any ideas how to troubleshoot that without access to a mac?

**Comment by grahamc** [comment]
I can give you access to a mac? :)

**Comment by peterhoeg** [comment]
@jwiegley - should be OK now. I've changed msmtp to use ```netcat-gnu``` instead to avoid the ```libbsd``` dependency.

**Pull request merged**
