### PR TITLE
ndi: 5.6.0 -> 5.6.1 + update src and fix lib symlink

### PR DESCRIPTION
**Pull request by jshcmpbll**
## Description of changes

The NDI library is currently broken. Adding a couple lines to remove the old bin -> lib symlink and update it with the correct path.

#82617 Brought up the idea of just sourcing the file for the user. I am not entirely sure how to handle the acceptance of NewTek's EULA but figured I'd get this up so others might be able to help contribute on that front.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jshcmpbll** [comment]
## Current bin symlink problem:
```
nixos/nixpkgs git:(master*)git --no-pager diff
diff --git a/pkgs/development/libraries/ndi/version.json b/pkgs/development/libraries/ndi/version.json
index 686abdb2c2b7..c0184c27df7e 100644
--- a/pkgs/development/libraries/ndi/version.json
+++ b/pkgs/development/libraries/ndi/version.json
@@ -1 +1 @@
-{"hash": "sha256:4ff4b92f2c5f42d234aa7d142e2de7e9b045c72b46ad5149a459d48efd9218de", "version": "5.6.0"}
+{"hash": "sha256:0wh5bqy9xx08wnfah92pgs4f6xn6mwfyhwdzbhf5ghkbw8pc7z0w", "version": "5.6.0"}
nixos/nixpkgs git:(master*)export NIXPKGS_ALLOW_UNFREE=1; nix build .#ndi --impure
warning: Git tree '/home/jsh/git/nixos/nixpkgs' is dirty
nixos/nixpkgs git:(master*)ls -la result/bin
total 14493
dr-xr-xr-x 2 root root        7 Dec 31  1969 .
dr-xr-xr-x 7 root root        7 Dec 31  1969 ..
lrwxrwxrwx 1 root root       42 Dec 31  1969 libndi.so.5 -> ../../lib/x86_64-linux-gnu/libndi.so.5.6.1
-r-xr-xr-x 1 root root 23711576 Dec 31  1969 ndi-benchmark
-r-xr-xr-x 1 root root   675736 Dec 31  1969 ndi-directory-service
-r-xr-xr-x 1 root root 26545752 Dec 31  1969 ndi-free-audio
-r-xr-xr-x 1 root root 25236856 Dec 31  1969 ndi-record
```

**Comment by jshcmpbll** [comment]
Linking this issue too since its relevant #219578

**Review by JohnRTitor — CHANGES_REQUESTED** [review]
PR title should be updated to indicate the version change as well.

**Comment by jshcmpbll** [comment]
Updated, thanks @JohnRTitor

**Review by JohnRTitor — APPROVED** [review]
While nixpkgs review did not work, I successfully built with `nix build .#ndi`. It did successfully fetch and installed ndi libs.
image

Successfully built `obs-studio-plugins.obs-ndi` as well.

image

**Comment by JohnRTitor** [comment]
@ofborg build ndi
@ofborg build obs-studio-plugins.obs-ndi

**Review by RossComputerGuy — APPROVED** [review]
image0

**Pull request merged**
