### PR TITLE
fcitx-engines.mozc: 2.17.2313.102.1 -> 2.18.2612.102.1 and other minor fcitx packages updates

### LINKED ISSUE #25228: mozc on fcitx fails to work on Chromium
## Issue description

after a `nixos-rebuild switch --upgrade`, fcitx cannot switch to mozc __only in chromium__.
journalctl gives me
```
Apr 26 11:15:59 dn xsession[1721]: [1964:1964:0426/111559.859723:ERROR:browser_main_loop.cc(279)] Gtk: GModule (/nix/store/9phpwkfbpfp7cwjm00lxz6vy6qbrnkpx fcitx-with-plugins-4.2.9.1/lib/gtk-2.0/2.10.0/immodules/im-fcitx.so) initialization check failed: GLib version too old (micro mismatch)
Apr 26 11:15:59 dn xsession[1721]: [1964:1964:0426/111559.859743:ERROR:browser_main_loop.cc(279)] Gtk: Loading IM context type 'fcitx' failed
```

### Steps to reproduce

```nix
...
i18n.inputMethod = {
  enabled = "fcitx";
  fcitx.engines = with pkgs.fcitx-engines; [ mozc ];
}
...
programs.chromium.enable = true;
...
```

`nixos-rebuild switch --upgrade # with nixos-unstable`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09pre106117.c90998d5cf (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.8

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre106117.c90998d5cf"

* `fcitx --version`

fcitx version: 4.2.9.1

* `chromium --version`

Chromium 57.0.2987.133

### PR DESCRIPTION
**Pull request by ericsagnes**
###### Motivation for this change

_Should_ fix #25228 by updating `fcitx-engines.mozc` to a recent version.
Also introduce a few minor upgrades for other fcitx related packages, namely:

- fcitx-qt5
- fcitx-configtool

Tested in a NixOS VM with a few applications (qutebrowser & chromium).

@mt-caret Could you test this PR and check if it solves the problem you had in chromium?

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mt-caret** [comment]
after cloning 'ericsagnes:pkg-update/fcitx-related' and running `sudo nixos-rebuild switch -I /path/to/repo`, switching input methods still doesn't work in chromium with the same error:
```
Apr 26 20:20:47 dn xsession[1520]: [1766:1766:0426/202047.687897:ERROR:browser_main_loop.cc(279)] Gtk: GModule (/nix/store/5a65dlh0pbnyszq7y2q63ykqq84g08qz-fcitx-with-plugins-4.2.9.1/lib/gt
Apr 26 20:20:47 dn xsession[1520]: [1766:1766:0426/202047.687930:ERROR:browser_main_loop.cc(279)] Gtk: Loading IM context type 'fcitx' faile
```

**Comment by ericsagnes** [comment]
That's puzzling, does the error also happens with other GTK 2 applications, eg geany?

Could you try the configuration in a clean VM to see if it still happens?
For example you can use the configuration http://nixpaste.nixos.tech-meetups.tokyo/eJX3WYR7 and build a VM with the following command:

```sh
$ nixos-rebuild build-vm -I nixpkgs=/path/to/nixpkgs -I nixos-config=/path/to/configuration/file.nix
```

Also, mozc is somehow touchy with its main server, if you did an update and haven't rebooted afterwards, you can try to reboot that sometimes fix strange state problems.

**Comment by mt-caret** [comment]
Installed and tried gedit and got the same sort of error and condition (can't switch input method to mozc)
```
(gedit:8128): Gtk-WARNING **: GModule (/nix/store/5a65dlh0pbnyszq7y2q63ykqq84g08qz-fcitx-with-plugins-4.2.9.1/lib/gtk-3.0/3.0.0/immodules/im-fcitx.so) initialization check failed: GLib version too old (micro mismatch)
(gedit:8128): Gtk-WARNING **: Loading IM context type 'fcitx' failed
```
I'll check if I can reproduce this behavior in a vm.

**Comment by mt-caret** [comment]
Confirmed that the PR fixes the problem with chromium and other gtk-based applications (I tested gedit and slack)! The reason that nixos-rebuild switch wasn't working was a mistake on my part; I was under the assumption that programs.chromium.enable = true; will install chromium, and had completely forgot about installing it in my root profile.

**Pull request merged**
