### PR TITLE
wireguard-tools: 0.0.20190123 -> 0.0.20190227

### PR DESCRIPTION
**Pull request by elseym**
###### Motivation for this change

update wireguard-tools

/cc @kirelagin

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dywedir** [comment]
@GrahamcOfBorg build wireguard-tools linuxPackages.wireguard

**Comment by xeji** [comment]
@GrahamcOfBorg build wireguard-tools linuxPackages.wireguard

**Comment by xeji** [comment]
build failures look like a missing dependency

**Comment by Ma27** [comment]
@elseym when bumping `wireguard-tools`, the kernel module will be affected as well as they share the same source (see `pkgs/os-specific/linux/wireguard/default.nix` for further reference).

I tried to fix the breaking build with the following patch locally:

``` diff
diff --git a/pkgs/os-specific/linux/wireguard/default.nix b/pkgs/os-specific/linux/wireguard/default.nix
index e103de3e1b7..e13828d018a 100644
--- a/pkgs/os-specific/linux/wireguard/default.nix
+++ b/pkgs/os-specific/linux/wireguard/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, kernel, wireguard-tools, perl }:
+{ stdenv, kernel, wireguard-tools, perl, libmnl }:
 
 # module requires Linux >= 3.10 https://www.wireguard.io/install/#kernel-requirements
 assert stdenv.lib.versionAtLeast kernel.version "3.10";
@@ -21,6 +21,8 @@ stdenv.mkDerivation rec {
 
   nativeBuildInputs = [ perl ] ++ kernel.moduleBuildDependencies;
 
+  buildInputs = [ libmnl ];
+
   buildPhase = "make module";
 
   meta = with stdenv.lib; {
```

However it breaks with the following error then:

```
CC      /build/source/src/tools/config.o
  LD      /build/source/src/tools/wg
install: cannot create directory '/usr': Permission denied
make[1]: *** [Makefile:76: install] Error 1
make: *** [Makefile:62: tools-install] Error 2
builder for '/nix/store/r9qpzhaw823c2jq2pz0a7fdv5g2a5956-wireguard-0.0.20190227.drv' failed with exit code 2
error: build of '/nix/store/r9qpzhaw823c2jq2pz0a7fdv5g2a5956-wireguard-0.0.20190227.drv' on 'ssh://builder' failed: builder for '/nix/store/r9qpzhaw823c2jq2pz0a7fdv5g2a5956-wireguard-0.0.20190227.drv' failed with exit code 2
builder for '/nix/store/r9qpzhaw823c2jq2pz0a7fdv5g2a5956-wireguard-0.0.20190227.drv' failed with exit code 1
error: build of '/nix/store/r9qpzhaw823c2jq2pz0a7fdv5g2a5956-wireguard-0.0.20190227.drv' failed
```

This is probaly related to some `make` script missing the proper install prefix. Unless you're faster, I'll have another look at it this weekend :)

**Comment by elseym** [comment]
thank you, @Ma27 ! 🙇 
i'd very much appreciate your help on this.

**Comment by fpletz** [comment]
@GrahamcOfBorg build wireguard-tools linuxPackages.wireguard

**Review by Ma27 — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Pull request merged**
