### PR TITLE
[20.03] softmaker-office: 972 -> 974

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

This update is necessary to make SoftMaker Office build on 20.03, since SoftMaker replaces the tarball of the previous version by the next version.

Changelog:
https://www.softmaker.com/en/servicepacks-office-changelog

(cherry picked from commit d4212f7036fa8016ba1451246e7a9c1b7ca4e453)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
This is already broken:
```
hash mismatch in fixed-output derivation '/nix/store/iwvyyv1by1xypsi8pjh1hxnqi0jx810q-softmaker-office-2018-974-amd64.tgz':
  wanted: sha256:0z1g76lhja92s25x6y0h55wmqza2d3pjbshn5b9rn2784gjgj7hn
  got:    sha256:0j6zm0cbxrcgm7glk84hvvbp4z0ys6v8bkwwhl5r7dbphyi72fw8
cannot build derivation '/nix/store/wjrs28q8jniycsd85lh8l91yfnqvl9n7-softmaker-office-974.drv': 1 dependencies couldn't be built
```

**Comment by danieldk** [comment]
This is starting to become a cat-and-mouse game. While it initially seemed that they were suggesting hosting tarballs elsewhere, they haven't replied to my proposal to either host it by archive.org or in a GitHub repo (through GitHub releases):

https://forum.softmaker.com/viewtopic.php?f=320&t=19327

I am starting to think it might be better to yank Softmaker Office/FreeOffice from master and move this to NUR instead. It simply breaks too often to have these packages in your system configuration.

@romildo any opinions?

I guess I can ask on the SoftMaker forums once more.

**Comment by danieldk** [comment]
Closing in favor of #86452.

**Comment by romildo** [comment]
> I am starting to think it might be better to yank Softmaker Office/FreeOffice from master and move this to NUR instead. It simply breaks too often to have these packages in your system configuration.
> 
> @romildo any opinions?

Even if moved to NUR, the issue will persist. Someone would have to keep the check sums updated. I think I would keep it at nixpkgs and continue to fix it as new versions are released.

**Pull request closed without merging**
