### PR TITLE
Adding some Jane Street packages at version 0.9 (in progress)

### PR DESCRIPTION
**Pull request by Zimmi48**
This pull request is mostly to get comments from OCaml packages (especially Jane Street packages) maintainers.

It seems that Nixpkgs contains lots of Jane Street packages at version 113.33.03.
Recently they have been moving to 0.9 with (it seems) quite a few differences in the way those are compiled / installed.
I need a few of these packages at version 0.9+, among them sexplib.
I have created the builder `newBuildOcamlJane` to generically build any of those packages. I'd appreciate feedback on that.
I've also added a package for sexplib version 0.9.1: at first I just wanted to replace version 113.33.03 with version 0.9.1 but a lot of packages depend on it, so it implies updating many many packages. Also some of the new versions of these packages have new dependencies, so it requires adding new packages as well. I am ready to do it, but I'd like feedback before.

Do you mind the new builder and does it seem OK to you? I probably could have modified the current builder to check if the version is before or after v0.9 but that would have been more complex and would have created unnecessary dependencies.

Do you confirm that updating all those packages (at once) is the way to go?

cc @maurer @ericbmerritt @vbgl

### CODE REVIEW

**Comment by maurer** [comment]
P.S., can someone who has that power retrigger the OSX build? It appears to have failed during the installing nix stage, which I'm 99% sure wasn't this change, but OCaml + OSX tends to have surprising failures so it'd be good to see whether it works.

**Comment by Zimmi48** [comment]
@maurer Thanks for your comment. After some thinking, I reached the same conclusion. Let me add a few other 0.9 packages to this PR so as to confirm that the new builder works fine for all of them.

**Comment by Zimmi48** [comment]
@vbgl Just found out while adding package `core` that you had already added package `base` and a few other at version 0.9. Though, you are not testing for OCaml version >= 4.03.
About the file organization I wonder where this is going, since some Jane Street packages are in `ocaml-modules/` and some others are in sub-directory `janestreet/` (the most recent version being found indifferently in one or the other).

**Comment by Zimmi48** [comment]
My `newOcamlJaneBuilder` was actually not working when building packages with dependencies. I've changed it to something reproducing what @vbgl did in his derivation of `base`.

**Comment by Zimmi48** [comment]
Actually, my new version does not work either (`ppx_optcomp` fails to build). I had incorrectly tested the build on my machine.

**Comment by Zimmi48** [comment]
OK fixed. This was because I was using `buildInputs` instead of `propagatedBuildInputs` for OCaml package dependencies.

**Comment by Zimmi48** [comment]
My approach here does not scale. Here is a better proposal: #25658

**Pull request closed without merging**
