### PR TITLE
twitter-color-emoji: use noto-fonts-emoji’s src

### LINKED ISSUE #72164: Package 'fonttools' requires a different Python: 2.7.17 not in '>=3.6'
**Describe the bug**
Trying to rebuild from git master and it complains about fonttools and python version mismatch.

**To Reproduce**

```
adding 'fonttools-4.0.2.dist-info/RECORD'                                                                                                                                                                                                    
no configure script, doing nothing                                                                                                                                                                                                           
building                                                                                                                                                                                                                                     
build flags: SHELL=/nix/store/zavn4np1jvm79f0rafkv0p1mrag09qkz-bash-4.4-p23/bin/bash KVER=4.19.80 KDIR=/nix/store/3mm0kfp4r46g882pjcxgj46lrnz0zk2q-linux-4.19.80-dev/lib/modules/4.19.80/build                                               
removing build/bdist.linux-x86_64/wheel                                                                                                                                                                                                      
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module                                                                                                                 
make[1]: Entering directory '/build/source/module'                                                                                                                                                                                           
make -C /nix/store/3mm0kfp4r46g882pjcxgj46lrnz0zk2q-linux-4.19.80-dev/lib/modules/4.19.80/build M=$PWD                                                                                                                                       
make[2]: Entering directory '/nix/store/3mm0kfp4r46g882pjcxgj46lrnz0zk2q-linux-4.19.80-dev/lib/modules/4.19.80/build'                                                                                                                        
Finished executing setuptoolsInstallPhase                                                                                                                                                                                                    
installing                                                                                                                                                                                                                                   
Executing pipInstallPhase                                                                                                                                                                                                                    
/build/fonttools-4.0.2/dist /build/fonttools-4.0.2                                                                                                                                                                                           
checking for suffix of executables...                                                                                                                                                                                                        
checking whether we are cross compiling... no                                                                                                                                                                                                
checking for suffix of object files... o                                                                                                                                                                                                     
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Pytho
n 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing ./fonttools-4.0.2-py2-none-any.whl                                                                                                                                                                                                
unpacking sources                                                                                                                                                                                                                            
unpacking source archive /nix/store/4w5rgvcja20scrvhpwv8741i87msjkln-libreoffice-6.2.6.2.tar.xz                                                                                                                                              
ERROR: Package 'fonttools' requires a different Python: 2.7.17 not in '>=3.6'
builder for '/nix/store/9dk2dvnn5dmdfk1lwjsfxq3am7ham20h-python2.7-fonttools-4.0.2.drv' failed with exit code 1                                                                                                                              
building '/nix/store/3dwrilblfm27b5xgdyfzwbiyl1i9gqsg-batchsigner-1.6.3.drv'...                                                                                                                                                              
cannot build derivation '/nix/store/gbhj95nnmkkyambwblri5g04l7pkqihw-noto-fonts-emoji-2018-08-10-unicode11.drv': 1 dependencies couldn't be built                                                                                            
cannot build derivation '/nix/store/vzsgzq61xgilpxzwgn3i4xjgqnqhmqgq-X11-fonts.drv': 1 dependencies couldn't be built                                                                                                                        
cannot build derivation '/nix/store/50wq000ijfqsl5anzg33kw2bxrwc6gg0-fc-00-nixos-cache.conf.drv': 1 dependencies couldn't be built                                                                                                           
cannot build derivation '/nix/store/miqbrnfd9fyz2l5w4lpla9y122wn5wg3-fc-00-nixos-cache.conf.drv': 1 dependencies couldn't be built                                                                                                           
cannot build derivation '/nix/store/pp45z7ghqrf25q6zf720zacbb8jvd3dy-fonts.conf.drv': 1 dependencies couldn't be built                                                                                                                       
cannot build derivation '/nix/store/4mid2nay25310lgkidalc4lbgyzf9qqg-xserver.conf.drv': 1 dependencies couldn't be built                                                                                                                     
building '/nix/store/sfjg4ln6h2knhh9xswmk4jjv87iv7f4p-evdi-2019-10-09.drv'...                                                                                                                                                                
cannot build derivation '/nix/store/ry9gx2zk55g26a9sckzq7i85cwwa7fgw-fontconfig-conf.drv': 1 dependencies couldn't be built                                                                                                                  
building '/nix/store/pki67w7b8082nmfdsaa2q7ab8xryd2si-sshd.conf-validated.drv'...                                                                                                                                                            
building '/nix/store/g1qp94ycc5cj4bq2apzsjahz1br7a6k9-system-generators.drv'...                                                                                                                                                              
cannot build derivation '/nix/store/7f5ab8bhahlil27qv3w8c0z8j843zm3i-system-path.drv': 1 dependencies couldn't be built                                                                                                                      
building '/nix/store/i2r5sqikbi8lzqwsfnfjv54snz72n11d-system-shutdown.drv'...                                                                                                                                                                
building '/nix/store/qr1zadqp8hjp7q7daipw8wfkjv85wr21-torrc.drv'...                                                                                                                                                                          
building '/nix/store/k55mpxqdd5czknjj59nfj2dxkilfjdf1-udev-rules.drv'...                                                                                                                                                                     
building '/nix/store/9lgmdsdi34gl3ii0c35ly8dhnm6f6vdm-udhcp-script.drv'...                                                                                                                                                                   
building '/nix/store/7clz82x8c62c45xsr8xp2pdjawrkvdgj-unit-container-getty-.service.drv'...                                                                                                                                                  
cannot build derivation '/nix/store/znr2bidivrhrgc141nc5698bw71b7737-xserver-wrapper.drv': 1 dependencies couldn't be built                                                                                                                  
cannot build derivation '/nix/store/22qj494sqavywz93yfbsc10k0wnw9r6q-nixos-system-subi-20.03.git.443f1a4.drv': 1 dependencies couldn't be built                                                                                              
error: build of '/nix/store/22qj494sqavywz93yfbsc10k0wnw9r6q-nixos-system-subi-20.03.git.443f1a4.drv' failed
```

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
root@subi:~# nix run nixpkgs.nix-info -c nix-info -m                                                                                                                                                                                         
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.1, NixOS, 20.03.git.4c07c0f (Markhor)`                                                                                                                                                                                
 - multi-user?: `yes`                                                                                                                                                                                                                        
 - sandbox: `yes`                                                                                                                                                                                                                            
 - version: `nix-env (Nix) 2.3`                                                                                                                                                                                                              
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`                                                                                                                                                                             
 - channels(root): `"nixos-20.03pre197483.2bd4f8023bf"`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
* Clean up `twitter-color-emoji`
* Fix #72164 for `emojione` and `twemoji-color-font`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
EmojiOne did fail for me
```
Traceback (most recent call last):
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/bin/.scfbuild-wrapped", line 18, in <module>
    sys.exit(main())
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/lib/python3.7/site-packages/scfbuild/main.py", line 124, in main
Traceback (most recent call last):
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/bin/.scfbuild-wrapped", line 18, in <module>
    return builder.run()
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/lib/python3.7/site-packages/scfbuild/builder.py", line 58, in run
    sys.exit(main())
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/lib/python3.7/site-packages/scfbuild/main.py", line 124, in main
    fforge.add_glyphs(ff_font, svg_filepaths, self.conf)
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/lib/python3.7/site-packages/scfbuild/fforge.py", line 87, in add_glyphs
    u_str = ''.join(map(unichr, u_ids))
NameError: name 'unichr' is not defined
    return builder.run()
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/lib/python3.7/site-packages/scfbuild/builder.py", line 58, in run
    fforge.add_glyphs(ff_font, svg_filepaths, self.conf)
  File "/nix/store/6yl3kmgd09r33xs5gc58v9ihymsw1pkl-scfbuild-1.0.3/lib/python3.7/site-packages/scfbuild/fforge.py", line 87, in add_glyphs
    u_str = ''.join(map(unichr, u_ids))
NameError: name 'unichr' is not defined
make: *** [Makefile:93: build/EmojiOneColor-SVGinOT-OSX.ttf] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by jtojnar** [comment]
@GrahamcOfBorg build twemoji-color-font emojione

**Comment by jtojnar** [comment]
The patch was not being applied. Aargh, foiled by phases` again.

**Comment by jtojnar** [comment]
@GrahamcOfBorg build twemoji-color-font emojione

**Review by worldofpeace — APPROVED** [review]
I could build emojione and twitter-color-emoji.
Not sure about the darwin failures, but this takes too long to test for me to investigate it further.

**Review by FRidh — APPROVED** [review]

**Pull request merged**
