### PR TITLE
Add pim-data-exporter

### PR DESCRIPTION
**Pull request by JohnMH**
###### Motivation for this change
The KDE app pim-data-exporter wasn't listed before, and I needed to copy my config from another machine. Figured other people might find this useful.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Thanks!

**Comment by JohnMHarrisJr** [comment]
Just realized both changed files include tab indentation.. Yikes.

**Comment by Mic92** [comment]
oh, you might want to enable http://editorconfig.org/ in your editor to get the correct settings for nixpkgs

**Comment by JohnMHarrisJr** [comment]
Issue was with my Emacs config, sorry about that.

**Pull request merged**
