### PR TITLE
gcc-arm-embedded: 7-2018-q2-update -> 8-2018-q4-major

### PR DESCRIPTION
**Pull request by prusnak**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by prusnak** [comment]
Related: it might be a good idea to remove all older versions (right now we keep 4.x, 5, 6 and 7) and keep just the latest one (8). I'll amend the commit if @vinymeuh and @rasendubi agree.

**Comment by rasendubi** [comment]
@prusnak I am against this as gcc-arm-embedded versions are not really backward compatible and that manifests in much more ways in embedded projects. (i.e., many embedded projects do not compile or even crash with newer versions of gcc)

FWIW, that was previously discussed at https://github.com/NixOS/nixpkgs/pull/52146

**Comment by rasendubi** [comment]
@GrahamcOfBorg build gcc-arm-embedded

**Comment by prusnak** [comment]
@rasendubi I am fine with keeping all old versions and that's how I did this patch in the first place.

Let's review this as it is then.

**Comment by rasendubi** [comment]
@prusnak sure. I didn't block the PR—just hadn't time to wait for the build to finish. :slightly_smiling_face:

**Pull request merged**
