### PR TITLE
python3Packages.{consonance,yowsup}: fix build; refactor

### PR DESCRIPTION
**Pull request by Moraxyc**
- **python311Packages.consonance: fix build**
- **python311Packages.consonance: refactor**
- **python311Packages.yowsup: fix build**
- **python311Packages.yowsup: refactor**

ZHF: #352882
https://hydra.nixos.org/build/276572780
https://hydra.nixos.org/build/276593511

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354690`

---
### `x86_64-linux`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.yowsup</li>
    <li>python311Packages.yowsup.dist</li>
    <li>python312Packages.yowsup</li>
    <li>python312Packages.yowsup.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.consonance</li>
    <li>python311Packages.consonance.dist</li>
    <li>python312Packages.consonance</li>
    <li>python312Packages.consonance.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`yowsup` seems to have the same protobuf issue as `consonance`.

```bash
error: builder for '/nix/store/jmqw7qynsmyw1vjkzwilm42bhalv85a4-python3.12-yowsup-3.3.0.drv' failed with exit code 2;
       last 25 log lines:
       > E   If you cannot immediately regenerate your protos, some other possible workarounds are:
       > E    1. Downgrade the protobuf package to 3.20.x or lower.
       > E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
       > E   
       > E   More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by Moraxyc** [comment]
this may be a wide issue for packages that are not compatible with the new version of protobuf

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354690`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>python311Packages.consonance</li>
    <li>python311Packages.consonance.dist</li>
    <li>python311Packages.yowsup</li>
    <li>python311Packages.yowsup.dist</li>
    <li>python312Packages.consonance</li>
    <li>python312Packages.consonance.dist</li>
    <li>python312Packages.yowsup</li>
    <li>python312Packages.yowsup.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>python311Packages.consonance</li>
    <li>python311Packages.consonance.dist</li>
    <li>python311Packages.yowsup</li>
    <li>python311Packages.yowsup.dist</li>
    <li>python312Packages.consonance</li>
    <li>python312Packages.consonance.dist</li>
    <li>python312Packages.yowsup</li>
    <li>python312Packages.yowsup.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>python311Packages.consonance</li>
    <li>python311Packages.consonance.dist</li>
    <li>python311Packages.yowsup</li>
    <li>python311Packages.yowsup.dist</li>
    <li>python312Packages.consonance</li>
    <li>python312Packages.consonance.dist</li>
    <li>python312Packages.yowsup</li>
    <li>python312Packages.yowsup.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>python311Packages.consonance</li>
    <li>python311Packages.consonance.dist</li>
    <li>python311Packages.yowsup</li>
    <li>python311Packages.yowsup.dist</li>
    <li>python312Packages.consonance</li>
    <li>python312Packages.consonance.dist</li>
    <li>python312Packages.yowsup</li>
    <li>python312Packages.yowsup.dist</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
LGTM, thanks. ofborg error is referencing derivation that was fixed in your other PR.

**Pull request merged**
