### PR TITLE
gst_all_1.*,python3Packages.gst-python: 1.22.4 -> 1.22.5

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

GStreamer update, including security fixes: https://gstreamer.freedesktop.org/releases/1.22/#1.22.5

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
  - [x] x86_64-linux -> aarch64-linux (cross) (needs #245761)
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
I _think_ the only security-relevant one is `gst-plugins-ugly`

**Comment by lilyinstarlight** [comment]
> I _think_ the only security-relevant one is `gst-plugins-ugly`

That is correct, yep! The only security fix was in the ugly plugin set (for the realmedia transcoding stuff)

**Comment by vcunat** [comment]
Surprisingly, `(gst-plugins-good.override { qt5Support = true; })` broke:
https://hydra.nixos.org/build/229995395/nixlog/3/tail

**Comment by doronbehar** [comment]
Putting here relevant upstream source code links and information:

- `gst-plugins-good` is missing "viv_fb" headers that are found in [`gst-plugins-base` repo](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/tree/1.22.5/subprojects/gst-plugins-base/?ref_type=tags) - dependency of `gst-plugins-good`.
- Description of some relevant meson options: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/1.22.5/subprojects/gst-plugins-base/meson_options.txt#L11
- The meson file that decides whether the "viv_fb" header files will be installed: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/1.22.5/subprojects/gst-plugins-base/gst-libs/gst/gl/meson.build#L932 .

The logic there seems pretty complicated, but we need to figure it out, and make our build install those files.

**Comment by doronbehar** [comment]
This breakage breaks the `nheko` build, a Matrix client many people use.

**Comment by lilyinstarlight** [comment]
@doronbehar I've already mentioned the required upstream PR to fix this in Matrix and intend to make a PR imminently (after this build finishes and I test it)

Basically it was a bad backport in https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4959 with the fix in https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/5083

**Comment by lilyinstarlight** [comment]
Fix opened for staging-next as #247430 and staging-next-23.05 as #247432

**Pull request merged**
