### PR TITLE
flashplayer: 11.2.202.644 -> 24.0.0.186 [Critical security fix]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

Critical security fix:
https://helpx.adobe.com/security/products/flash-player/apsb16-39.html

The version leaped from 11 to 24.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested x86_64 version:
- http://www.adobe.com/software/flash/about/ shows `24,0,0,186 installed`
- Plays sounds
- Plays movie

Issues:

- Should we keep the version 11?
- Is `mm.cfg` still effective?
- How to use `kcm_adobe_flash_player.so`?

### CODE REVIEW

**Comment by grahamc** [comment]
I don't know about mm.cfg or kcm_... but we probably shouldn't keep 11 around. Do we need to solve any problems before this gets merged and backported?

**Comment by taku0** [comment]
As far as I know, it works without any problems. I didn't test advanced features like protected video or video chat.

**Comment by grahamc** [comment]
Sorry for taking so long, @taku0. I'd like to merge this. I think we should delete _11 support, though. Can you test if flashplayer-standalone and the debugger support 24 ok? If yes, I'll merge and backport immediately.

**Comment by taku0** [comment]
@grahamc added debug versions and standalone versions. The standalone versions are now 64 bit rather than 32 bit.

Bad news: the source URLs of debug versions and standalone versions don't contain version numbers (e.g. https://fpdownload.macromedia.com/pub/flashplayer/updaters/24/flash_player_npapi_linux_debug.x86_64.tar.gz), so that the packages will be broken when Adobe updates the archive files.
Minor problem: standalone versions crash with unhandled SIGSEGV when quitting. For other normal operations, it works fine.

We can merge them anyway.

**Review by zimbatm — APPROVED** [review]

**Comment by zimbatm** [comment]
I'm going to remove the flashplayer-11 folder in a subsequent commit

**Comment by vcunat** [comment]
I assume you've found no reason not to have this in 16.09 as well?

**Comment by grahamc** [comment]
Yes Please backport

**Comment by vcunat** [comment]
Tested on 16.09 on some video and game, and pushed.

**Pull request merged**
