### PR TITLE
ocamlPackages.menhir: 20170712 -> 20180530

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build reason

**Comment by Mic92** [comment]
compcert and verasco are also broken.

**Comment by Mic92** [comment]
Is verasco even under active development? http://compcert.inria.fr/verasco/release/
No release since 2016-03-07

**Comment by Mic92** [comment]
@GrahamcOfBorg build compcert

**Comment by vbgl** [comment]
What’s the motivation for this update? Can we avoid breaking things?

**Comment by Mic92** [comment]
I want build my software against the latest version so I can don't need to migrate later because of incompatibilities and I can report upstream bugs. So far only verasco breaks does not build. They seem to have no bug tracker or version control system. Do you know if upstream development is still active there?

**Comment by vbgl** [comment]
Should we wait for a release of CompCert or is the chosen development version good enough?

Marking Verasco as broken seems OK; can you add a comment about requiring some specific `menhir` version? Thanks.

**Comment by Mic92** [comment]
cc @bschommer is the current master we choose stable enough to be included instead of the current HEAD?

**Comment by bschommer** [comment]
For the moment the current version of menhir is stable enough to build CompCert. There will be probably some changes in the near future when the issue described in https://github.com/AbsInt/CompCert/pull/231 is fixed in the upstream version of menhir, but that could still take some time. Concerning verasco @jjhjourdan probably knows more of its status.

**Comment by bschommer** [comment]
Sorry for the misunderstanding, for the Academic releases CompCert on Github are @xavierleroy responsibility, but I think the current master should be nearly stable enough, there are some minor issues, which should be resolved in the next weeks.

**Comment by jhjourdan** [comment]
The development of Verasco is currently in pause and there exists no recent release. Therefore, indeed, it is incompatible with recent versions of Menhir.

Perhaps the package maintainers could create a dependency from Verasco to the old version of Menhir ?

**Comment by Mic92** [comment]
Closed in favor of https://github.com/NixOS/nixpkgs/pull/49349

**Comment by Mic92** [comment]
I don't think we should have unmaintained projects like verasco in nixpkgs so.

**Pull request closed without merging**
