### PR TITLE
matrix-synapse: 1.0.0 -> 1.1.0

### PR DESCRIPTION
**Pull request by mguentner**
###### Motivation for this change

@Ralith @fpletz 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nyanloutre** [comment]
@grahamcofborg build nixosTests.matrix-synapse

**Comment by Ekleog** [comment]
Test failure looks like a spurious timeout of the postgresql unit, let's attempt it again.

@grahamcofborg build nixosTests.matrix-synapse

**Comment by nyanloutre** [comment]
It timed out again :(

**Comment by Ekleog** [comment]
Let's see if it's postgresql that's broken, if not then it's most likely a bug in this PR, potentially with some postgresql activation script or similar.

@GrahamcOfBorg build nixosTests.postgresql

**Comment by mguentner** [comment]
The test runs smoothly on my local machine

**Comment by nyanloutre** [comment]
Same for me, I can run the test successfully on my machine

**Review by bachp — APPROVED** [review]
Deployed and working on my server

**Comment by Ekleog** [comment]
Looks like it works here too.

@grahamc Any idea what could be causing this postgresql timeout on ofborg and seemingly only there, that has been confirmed twice?

**Comment by mguentner** [comment]
I believe we can merge this as multiple people have confirmed that _It works!™_.
The problem with @GrahamcOfBorg seems to be an "Who tests the testers?" issue.

**Comment by Ekleog** [comment]
Sounds like some ofborg builders are running in VMs, which mean the tests may run slower in there. As it sounds like something that's a tester issue indeed and not some impurity, merging :)

**Pull request merged**
