### PR TITLE
nixos/sway: refactoring of `package` option

### PR DESCRIPTION
**Pull request by name-snrl**
## Description of changes

I started using `swayfx` yesterday, but found a discrepancy in the environment variables compared to `sway`. Initially I didn't look at the module implementation and just passed `with pkgs; sway.override { sway-unwrapped = swayfx; };` to `programs.sway.packages` assuming that this would override the package for the module and everything would work as before. In reality, it breaks several options.

So I created this PR where instead of the `defaultSwayPackage` variable that overrides `pkgs.sway`, I use a function that overrideы the user-defined package, but only if the package contains the necessary arguments.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by name-snrl** [comment]
guys @SebTM @primeos @thiagokokada?

**Comment by SebTM** [comment]
LGTM, but currently not using sway so not tested other than nixpkgs-review 👍🏻 

Let me ask two questions here:
 - Is there a way we can extend the tests to cover the changed behavior/catch different behaviors on future changes early?
 - Would it be an option to change the package-option and check if the package supports these overrides and then provide them on the go if the user changes the package?

For the second question it's rather an idea for better/easier UX than a we have to change that to get it merged ✌🏻

**Comment by kira-bruneau** [comment]
Superseded by #270013

**Comment by kira-bruneau** [comment]
Oh oops sorry! Not exactly, something like this is still needed!

**Comment by name-snrl** [comment]
> and apply `wrapSway` to it.

But what if someone wants to pass a packet that swayWrapper should not apply to? Don't think this is a good solution

**Comment by TLATER** [comment]
> > and apply `wrapSway` to it.
> 
> But what if someone wants to pass a packet that swayWrapper should not apply to? Don't think this is a good solution

The wrapper is effectively a noop if you set `wrapperFeatures.base` and `wrapperFeatures.gtk` to false, so I don't think this is an issue at all.

On the flip side, currently you just can't install sway forks that aren't pre-wrapped and expect them to work, which makes no sense.

**Comment by name-snrl** [comment]
> The wrapper is effectively a noop (just swaps sway out with a wrapper that immediately calls sway and does nothing else) if you set `wrapperFeatures.base` and `wrapperFeatures.gtk` to false, so I don't think this is an issue at all

When I was working on this #259066 had not yet been reverted, so there were other options that used `cfg.package` inside.

> On the flip side, currently you just can't install sway forks that aren't pre-wrapped and expect them to work, which kind of defies the purpose of even having a `package` option

Furthermore, even if you set a wrapped fork, the other options will not be applied to your package. At this point, the only thing you can do is write something like this:

```nix
  programs.sway.packages = pkgs.sway.override {
    sway-unwrapped = pkgs.swayfx;
    extraSessionCommands = config.programs.sway.extraSessionCommands;
    extraOptions = config.programs.sway.extraOptions;
    withBaseWrapper = config.programs.sway.wrapperFeatures.base;
    withGtkWrapper = config.programs.sway.wrapperFeatures.gtk;
  };
```

**Comment by TLATER** [comment]
> Furthermore, even if you set a wrapped fork, the other options will not be applied to your package.

[Ah, yeah, you're right](https://github.com/NixOS/nixpkgs/pull/270013/files#diff-ab5748dc9567516fefba8344056b51ec1866adeace380f46e58a7af3d619ea22R32650). `wrapSway` would need to be changed to take the arguments the module needs so this can be done reasonably.

**Comment by name-snrl** [comment]
> [Ah, yeah, you're right](https://github.com/NixOS/nixpkgs/pull/270013/files#diff-ab5748dc9567516fefba8344056b51ec1866adeace380f46e58a7af3d619ea22R32650).

That's not exactly what I meant when I wrote the previous answer. I forgot about that bad PR that added `wrapSway`, without `lib.makeOverridable`. But that can be easily fixed. The problem I was talking about is in the module. Right now, the default value of `programs.sway.package` is an internal variable, not a package, which is then used to apply overrides to it:


https://github.com/NixOS/nixpkgs/blob/fd44c780f0e79e69e6ccde779f9f19c89669f215/nixos/modules/programs/wayland/sway.nix#L29-L47

So if you change `programs.sway.package` to any value, the other module options will not be applied to your package, even if they could be. This is exactly what I meant when I said:

> Furthermore, even if you set a wrapped fork, the other options will not be applied to your package

**Comment by name-snrl** [comment]
@kira-bruneau @primeos @thiagokokada any review/merge? I still think this is good changes. Should I ping someone else for a review?

**Comment by kira-bruneau** [comment]
Oh yep sorry! I was testing this out a couple of weeks ago, but ran into problems and didn't figure out what was wrong. Will try again today though!

**Review by quantenzitrone — APPROVED** [review]
Works on my machine with sway and swayfx (which is wrapped since #273762). 
Code also LGTM.
I stumbled a bit over the `apply` argument to `mkOption`, but it seems to be just yet another underdocumented part of NixOS.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
