### PR TITLE
linuxPackages.broadcom_sta: fix build

### LINKED ISSUE #177798: broadcom_sta still fails to build (again, again) on kernel 5.18
### Describe the bug
Building `broadcom_sta` fails when rebuilding system configuration.

### Steps To Reproduce
`boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];`

### Expected behavior
System configuration should build successfully with `broadcom_sta` on kernel 5.18

### Screenshots
[err.txt](https://github.com/NixOS/nixpkgs/files/8912819/err.txt)
```
[...]
error: builder for '/nix/store/i2nsm53ln23dllrmxgf6cn3zrpan0h6y-broadcom-sta-6.30.223.271-5.18.3.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/qms8zvindb6d6i5ssavjw4zwswynl7sj-kernel-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q2wll0bn3xys3z807d1c5dzbhkh559ss-linux-5.18.3-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0kzp40rnjf1lrixm5jqz9y7szfnwgx0s-nixos-system-Niels-NixOS-22.05.915.9ff91ce2e4c.drv' failed to build
```

### Additional context
This appears to be a repetition of #177480 and #166035.
#177243 doesn't seem to be enough ?

I'm still on 21.11, can upgrade cleanly with its channel, but this happens when I try to rebuild after switching to 22.05 channel
(I did sudo nix-channel --update multiple times)

I'm still on kernel 5.17, but in my configuration.nix, I use the latest one, so I'm trying to upgrade to 5.18

I tried to use the arch patch (for 5.18, not for 5.17) talked about on #177480 but it still doesn't work, didn't checked if the error is the same though

### Notify maintainers
There are no current maintainers.

### Metadata
```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.17.11, NixOS, 21.11 (Porcupine), 21.11.337851.9227bbe4315`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-22.05.915.9ff91ce2e4c"`
 - channels(niels): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

Fixes #177798. It wasn't building due to a re-defined function introduced in `pkgs/os-specific/linux/broadcom-sta/linux-5.17.patch`.

I also formatted all the patches with `git format-patch` so that they're easy to apply on top of an extracted tarball, and added patch metadata so that the commits that result are true to their origins.

Patch `pkgs/os-specific/linux/broadcom-sta/i686-build-failure.patch` is removed as it was already applied.

These derivations now successfully build:

* `linuxKernel.packages.linux_4_19.broadcom_sta`
* `linuxKernel.packages.linux_4_19_hardened.broadcom_sta`
* `linuxKernel.packages.linux_5_10.broadcom_sta`
* `linuxKernel.packages.linux_5_10_hardened.broadcom_sta`
* `linuxKernel.packages.linux_5_15.broadcom_sta`
* `linuxKernel.packages.linux_5_15_hardened.broadcom_sta`
* `linuxKernel.packages.linux_5_4.broadcom_sta`
* `linuxKernel.packages.linux_5_4_hardened.broadcom_sta`
* `linuxKernel.packages.linux_6_1.broadcom_sta`
* `linuxKernel.packages.linux_6_1_hardened.broadcom_sta`
* `linuxKernel.packages.linux_6_6.broadcom_sta`
* `linuxKernel.packages.linux_6_8.broadcom_sta`
* `linuxKernel.packages.linux_6_8_hardened.broadcom_sta`
* `linuxKernel.packages.linux_6_9.broadcom_sta`
* `linuxKernel.packages.linux_6_9_hardened.broadcom_sta`
* `linuxKernel.packages.linux_hardened.broadcom_sta`
* `linuxKernel.packages.linux_latest_libre.broadcom_sta`
* `linuxKernel.packages.linux_libre.broadcom_sta`
* `linuxKernel.packages.linux_lqx.broadcom_sta`
* `linuxKernel.packages.linux_xanmod.broadcom_sta`
* `linuxKernel.packages.linux_xanmod_latest.broadcom_sta`
* `linuxKernel.packages.linux_zen.broadcom_sta`

As I do not have hardware to test this driver out, building will have to do as far as testing is concerned.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by philiptaron** [comment]
I'd appreciate any feedback or pointers on how to format patches for Nixpkgs; I see that #307068 formats them differently than I did here.

**Comment by K900** [comment]
At a glance it looks OK. I have nothing to test it with though, and just generally fuck this driver.

**Comment by philiptaron** [comment]
> just generally fuck this driver.

Fair. I considered dropping it but the number of folks that use it (based on issues) was high enough that I did the build fix.

**Comment by adminy** [comment]
You jinxed it ... Driver is no longer working as intended. No wifi, interface cannot be activated.

**Pull request merged**
