### PR TITLE
libsForQt5.qca-qt5: unbreak on darwin

### PR DESCRIPTION
**Pull request by wegank**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]

**Comment by imincik** [comment]
@wegank , @thiagokokada what is the actual change which made qca-qt5 working on darwin again ?

**Comment by thiagokokada** [comment]
> @wegank , @thiagokokada what is the actual change which makes qca-qt5 working on darwin again ?

I am assuming that we are building Qt 5.15 in darwin now?

**Comment by imincik** [comment]
Great thanks !

**Comment by imincik** [comment]
@lsix @sikmir @erictapen @willcohen - chance to get QGIS on darwin ?

**Comment by willcohen** [comment]
Yes! Two days ago I dusted off #157862 and locally rebased to master (I'm not pushing to the branch so I don't keep spamming darwin-maintainers just yet). Right now I'm at the highly annoying stage of getting all the dylibs to link correctly by manually running `install_name_tool` on every combination of every dylib being referred to from all the random frameworks, but every time I fix one link error I've gotta re-run the whole build, so it's slow going. I hope in the next couple of days that I finally get through it all and can get it to load.

As soon as QGIS actually builds and starts up I'll push the branch and we can hopefully merge that without much fuss. My preference would be to move all the fine-tuning to later PRs -- there's a strong chance that there'll still be little breakages with the various components, but getting something going is better than waiting for every little bit to be ironed out.

**Comment by imincik** [comment]
Great thanks @willcohen .

**Comment by willcohen** [comment]
@imincik any suggestions of how to proceed further based on https://github.com/NixOS/nixpkgs/pull/157862#issuecomment-1379250237 would be much appreciated!

**Pull request merged**
