### PR TITLE
vcpkg: init at 2023-08-02

### PR DESCRIPTION
**Pull request by Guekka**
###### Description of changes

This PR packages vcpkg, [the C++ package manager](vcpkg.io/).
Because a lot of ports assume a FHS environment, it provides a way to replace vcpkg ports with manually installed Nix packages.
I also tried to write a NixOS test, but got stuck because of the lack of internet access.

It is based on [the work of](https://discourse.nixos.org/t/installing-vcpkg-on-macos-using-nix/16852/8) @gracicot.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gracicot** [comment]
Thanks for doing that! I think it's possible to make it so that we don't need those symbolic links, I'll try to find some time soon for that. Should I do a PR on your branch @Guekka ?

**Comment by Guekka** [comment]
> Thanks for doing that! I think it's possible to make it so that we don't need those symbolic links, I'll try to find some time soon for that. Should I do a PR on your branch @Guekka ?

Sure! Thank you for your work too

**Comment by gracicot** [comment]
I swear I'm not dead! I started the improvements on my side.

Basically, vcpkg didn't allow at the time to set the path of the downloads and the path of the install tree separately. Now we'll be able to not do this fiddling with the symbolic links, and have one directory with installed packages in the home directory.

It will enable to do `vcpkg install fmt` without manifest mode, which didn't work with my initial work. I'll try to push as fast as I can, and it the worst case I'll push it as a package improvement.

**Comment by SebTM** [comment]
> I'll try to push as fast as I can, and it the worst case I'll push it as a package improvement.

Thanks and also for the great start on this :)

Different question regarding this: I'm trying to package the protonmail-bridge frontend which is an own package in the end using vcpkg. I adjusted this file https://github.com/ProtonMail/proton-bridge/blob/master/internal/frontend/bridge-gui/bridge-gui/build.sh so far to get until cmake and starting to build. My issue is that it's unable to resolve sentry even Line 81 where it get's installed runs successfully. Do you have an idea?

**Comment by gracicot** [comment]
From what I see you simply need to add the toolchain file with `-DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"` so the installed package are integrated into cmake. The best though would be to run in manifest mode, which is more reliable and more reproducible.

**Comment by SebTM** [comment]
I can try to ask about manifest-mode, but I'm not sure that it's cause of the issue?

I tried your suggestion (thank you) but it still fails with the sentry error or with an vcpkg-root not found error when I tried to set the VCPKG_ROOT to the nix-store installed version instead of the submodule one because I (in all cases) have to use the one in the nix-store as the other one is not executable:
```
zsh: no such file or directory: /home/sebtm/Projects/proton-bridge/internal/frontend/bridge-gui/bridge-gui/../../../../extern/vcpkg/vcpkg
```

```
CMake Error at /home/sebtm/Projects/proton-bridge/extern/vcpkg/scripts/buildsystems/vcpkg.cmake:853 (_find_package):
  Could not find a package configuration file provided by "sentry" with any
  of the following names:

    sentryConfig.cmake
    sentry-config.cmake

  Add the installation prefix of "sentry" to CMAKE_PREFIX_PATH or set
  "sentry_DIR" to a directory containing one of the above files.  If "sentry"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:86 (find_package)
```

```
CMake Error at /nix/store/qghnj7px7cznsdkakilw6c40cbp7mgyh-vcpkg-2023-06-22/share/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (message):
  Could not find .vcpkg-root
Call Stack (most recent call first):
  /nix/store/zhq7gd56lja5c4sxmsppbjx6k387c33v-cmake-3.26.4/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:29 (project)
```

I hope it's fine for you to discuss here otherwise I'm open to move this to an issue but I thought maybe it's a vcpk issue we can figure out. Also I'm not very familiar with the toolchain so happy for any input ✌🏻

**Comment by gracicot** [comment]
Okay @Guekka , I created a PR on your PR, mostly because I lack the confidence in editing nix stuff. Please correct it as you see fit :)

Those changes allow manifest mode to work, and should fix the error you're seeing where it cannot find `.vcpkg-root` and make packages installable from the command line too.

Basically, instead of creating a different root for every vcpkg version, it only creates one. I plan to push PRs on vcpkg-tool repository to add the argument to make vcpkg to pick triplets from the installation root, and another one to set the path of the lock file. With those two PRs, we'll be able to set the vcpkg root to be the nix store install root.

**Comment by SebTM** [comment]
Wasn't able to find the Pull-Request but your forks-branch with the changes and commented on the new commit, I guess we will need some kind of checksum/hash to be calculated out of the dependencies analog to vendorHash with buildGoModules to get this merged in the end? ✌🏻

**Comment by gracicot** [comment]
Hey @Guekka , I ran into problems when using you package, but I don't know enough of nix to be able to diagnose.

When I run `vcpkg install glm`, it is not able to compile anything:
```
$ vcpkg install glm
Computing installation plan...
The following packages will be built and installed:
    glm:arm64-osx -> 0.9.9.8#2
Detecting compiler hash for triplet arm64-osx...
error: while detecting compiler information:
The log file content at "/Users/myuser/.vcpkg/root/buildtrees/detect_compiler/stdout-arm64-osx.log" is:
-- Found external ninja('1.11.1').
-- Configuring arm64-osx-rel
CMake Error at /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /nix/store/3f8r736n0vk9zpg4ya5yk1plmf7i0pdq-cmake-3.26.4/bin/cmake /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/detect_compiler -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/myuser/.vcpkg/root/packages/detect_compiler_arm64-osx -DCMAKE_MAKE_PROGRAM=/nix/store/2mbw6nfbmipcg59afzz71c2c4msrc3k5-ninja-1.11.1/bin/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=arm64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/myuser/.vcpkg/root/ -DZ_VCPKG_ROOT_DIR=/Users/myuser/.vcpkg/root/ -D_VCPKG_INSTALLED_DIR=/Users/myuser/.vcpkg/root/installed -DVCPKG_MANIFEST_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=arm64
    Working Directory: /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/arm64-osx-rel
    Error code: 1
    See logs for more information:
      /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/config-arm64-osx-rel-CMakeCache.txt.log
      /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/config-arm64-osx-rel-out.log
      /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/config-arm64-osx-rel-err.log

Call Stack (most recent call first):
  /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:344 (vcpkg_execute_required_process)
  /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/ports.cmake:147 (include)



error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```

This is because it cannot find the current compiler and it chokes when it tries to detect one from the environment. It also fails to use registries with a ssh git repo address since it cannot find ssh.

I think this is because of `wrapProgram`. If I add `openssh` in the `runtimeDeps` list it can fetch using ssh, but adding the compiler is a bit more complicated since I define a very specific compiler in my `shell.nix` file of my own projects, so vcpkg must use the same.

If I remove `wrapProgram` it works again. Do you have an idea how to fix it in my case and how to make it work with the compiler I defined for my project's nix shell?

**Comment by Guekka** [comment]
> Hey @Guekka , I ran into problems when using you package, but I don't know enough of nix to be able to diagnose.
> 
> When I run `vcpkg install glm`, it is not able to compile anything:
> 
> ```
> $ vcpkg install glm
> Computing installation plan...
> The following packages will be built and installed:
>     glm:arm64-osx -> 0.9.9.8#2
> Detecting compiler hash for triplet arm64-osx...
> error: while detecting compiler information:
> The log file content at "/Users/myuser/.vcpkg/root/buildtrees/detect_compiler/stdout-arm64-osx.log" is:
> -- Found external ninja('1.11.1').
> -- Configuring arm64-osx-rel
> CMake Error at /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
>     Command failed: /nix/store/3f8r736n0vk9zpg4ya5yk1plmf7i0pdq-cmake-3.26.4/bin/cmake /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/detect_compiler -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/myuser/.vcpkg/root/packages/detect_compiler_arm64-osx -DCMAKE_MAKE_PROGRAM=/nix/store/2mbw6nfbmipcg59afzz71c2c4msrc3k5-ninja-1.11.1/bin/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=arm64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/myuser/.vcpkg/root/ -DZ_VCPKG_ROOT_DIR=/Users/myuser/.vcpkg/root/ -D_VCPKG_INSTALLED_DIR=/Users/myuser/.vcpkg/root/installed -DVCPKG_MANIFEST_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=arm64
>     Working Directory: /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/arm64-osx-rel
>     Error code: 1
>     See logs for more information:
>       /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/config-arm64-osx-rel-CMakeCache.txt.log
>       /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/config-arm64-osx-rel-out.log
>       /Users/myuser/.vcpkg/root/buildtrees/detect_compiler/config-arm64-osx-rel-err.log
> 
> Call Stack (most recent call first):
>   /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:344 (vcpkg_execute_required_process)
>   /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
>   /nix/store/qmsk7gnis54kj209cw3ni6rlxm29xksc-vcpkg-2023.06.20/share/vcpkg/scripts/ports.cmake:147 (include)
> 
> 
> 
> error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
> ```
> 
> This is because it cannot find the current compiler and it chokes when it tries to detect one from the environment. It also fails to use registries with a ssh git repo address since it cannot find ssh.
> 
> I think this is because of `wrapProgram`. If I add `openssh` in the `runtimeDeps` list it can fetch using ssh, but adding the compiler is a bit more complicated since I define a very specific compiler in my `shell.nix` file of my own projects, so vcpkg must use the same.
> 
> If I remove `wrapProgram` it works again. Do you have an idea how to fix it in my case and how to make it work with the compiler I defined for my project's nix shell?

The `wrapProgram` call forces vcpkg to use the PATH we gave it. This means it can only use the `gcc` binary we provided in the Nix file
However, I can see two ways to fix that
1. With an overlay, add your specific compiler to the runtime dependencies
2. Instead of using `wrapProgram --set`, we could use `wrapProgram --suffix`. This means it would first look into the current PATH before the default one. This doesn't feel very reproducible, but might be acceptable

What do you think?

**Comment by Guekka** [comment]
Some work was done by gracicot and added to this PR.

The commit history is not yet cleaned up, as this PR is not ready. We still need more discussion: this port feels brittle, do we really want it in the standard repo?

**Comment by Guekka** [comment]
@gracicot You did not add yourself to the |maintainers list](https://github.com/NixOS/nixpkgs/blob/36e8100bf096b1d1d6aaf8df687993f1fcbafa7c/maintainers/maintainer-list.nix)
Please PR against my branch to do it, or just give me the info and I'll do it for you :)

**Comment by Guekka** [comment]
I rebased the PR and added @gracicot to the maintainers list

**Comment by gracicot** [comment]
Hey sorry to leave you without news for a while. I have an idea to make vcpkg much less brittle, and probably on par with the quality that would be expected with a nix package.

Instead of tricking vcpkg into thinking the root is in the home directory, I'm thinking of leaving the root to be in the nix store and telling vcpkg to do filesystem mutation elsewhere. This is possible as far as I know since vcpkg allows to change the location of everything except the license file and the lock file.

The problem is the lock file. An easy solution would be to simply make vcpkg not taking a lock (there's a cmd option for that!), but we could go a step further and implement our own locking with flock or something similar.

**Comment by gracicot** [comment]
> No worries. I think that's a good idea, but it wouldn't make the package less brittle in my opinion
> 
> Personally, I think it is brittle because it will most likely require the user to add an overlay. If the user needs a vcpkg port that is unsupported, they need an overlay to replace it with a Nix package If the user needs a vcpkg port that uses some obscure tool, they need an overlay to add it to the list of runtime dependencies

I see. When I say "less brittle" I'm strictly speaking of the point of view of installing and using vcpkg as a user making a non-nix package, or developing a project that needs vcpkg for development. Making symbolic links in a folder and set the vcpkg root there is kinda janky.

This is why I'll also be looking at other similar package manager to see what compiler do they use: the one from their own derivation or the one in the shell they are used in. I want vcpkg to act like any other package managers in nix. I'll probably study them a bit before committing.

> But as far as I know, there is no way to fix that without biting the bullet and writing a full fledged `vcpkg2nix`

+1, absolutely.

I don't think derivations should use vcpkg to build themselves at all. Yes, we would need vcpkg2nix do build dependencies that are not packaged in nixpkgs directly.

I still think having vcpkg usable in a nix shell or installable on a machine a good start though, even if it's not usable by other derivations for now.

**Comment by gracicot** [comment]
While testing more extensively how vcpkg behaves with the package, I noticed a problem: vcpkg has some runtime dependencies to build packages. For example, a package could need autoconf to be built, or perl, or other things. Even if we add them into the path of the vcpkg executable, it is the cmake executable being used by the user's project that is responsible to find those external programs.

I did some digging around in vcpkg's internals and I can see that `z_vcpkg_find_acquire_program_find_external` doing a normal cmake `find_program`, which ultimately fails if the package was not added the user's shell/flake shell.

I'm thinking right now that it might be reasonable to just leave it like that as other package managers also behave the same way. It's just not very user friendly.

**Pull request closed without merging**
