### PR TITLE
Documentation indexes

### PR DESCRIPTION
**Pull request by oxij**
I believe this closes #8519.

Adding `/share/doc` costs ~nothing, but spares the user from searching in `/nix/store`.

### CODE REVIEW

**Comment by edolstra** [comment]
Please remove `share/doc`. It's kind of useless because it doesn't have a good browseable structure. And adding more stuff to the system profile does have a fairly significant cost. E.g. the symlink tree in /run/current-system/sw/ is already 73 MB on my system, and rebuilding it takes a significant amount of I/O.

**Comment by oxij** [comment]
It adds less than 50 symlinks there on my system with pretty much every
usable core and half of graphical packages installed (because most
packages have everything under `/share/doc/<package-name>` in their
respective outputs and `buildEnv` symlinks to those), but simplifies
documentation browsing a whole lot. I insist that it should be there.

**Comment by jagajaga** [comment]
I agree with @oxij.
:+1: for merging.

**Comment by peti** [comment]
This patch makes info files visible from the *system profile*, but not those from user profiles. Right?

**Comment by edolstra** [comment]
@peti Correct.

**Comment by oxij** [comment]
@peti Ah, right, so, strictly speaking, it doesn't close what you wanted
in #8519. But IMO the correct way to proceed about user profiles is to
patch buildEnv in nix-env in a way similar to this, see my last comment
in https://github.com/NixOS/nixpkgs/pull/8519#issuecomment-131877428.

**Comment by peti** [comment]
@oxij, don't believe that patching `buildenv.pl` the way you suggest would accomplish anything. Every package with info documentation has a `share/info/dir` file -- so if you install two of them into a profile, you'll just get a file conflict. What is required, really, is for all those `dir` files to be merged, and we don't have any mechanism in Nix that could easily do that (and one can debate whether such a mechanism is desirable in the first place).

**Comment by oxij** [comment]
@peti

>  Every package with info documentation has a `share/info/dir` file

That would be strange, because then it would generate a lot conflicts in
system-path `buildEnv` too, which I didn't notice.

  ls /nix/store/*/share/info/dir

shows a handful of packages like that. But they do exists, okay.

(Actually, with this PR merged I would suggest throwing them away in
installPhase.)

> What is required, really, is for all those `dir` files to be merged,
> and we don't have any mechanism in Nix that could easily do that (and
> one can debate whether such a mechanism is desirable in the first
> place).

And I'm suggesting adding a pice of code like
https://github.com/oxij/nixpkgs/commit/c6256c0e3e4292080b8574a483bdfce4b7d81b5f#diff-dcba170e079cd72958889058d01a4a02R142
to nix-env's buildenv. With that one will need to install `texinfo` into
user profile (which is strange, arguably) and the dir file would get
updated with all the info pages installed in that profile.

Merging info/dir files between profiles doesn't seem to be necessary (if
one to believe `man info`).

**Pull request merged**
