### PR TITLE
boehmgc: 8.0.6 -> 8.2.2

### PR DESCRIPTION
**Pull request by ivmai**
https://github.com/ivmai/bdwgc/releases/tag/v8.2.2

Drop mcfgthread.patch (upstreamed).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
@lovesegfault @roberth Not sure what needs to happen here with `boehmgc-coroutine-sp-fallback.patch`?

**Comment by ivmai** [comment]
> @roberth
[nix/boehmgc: Rebase patch](https://github.com/NixOS/nixpkgs/pull/189020/commits/190a5fe56d08fe1474d3975f6c07dbede3d0a6d3)

Right. Some time later, I will consider upstreaming it.

**Review by roberth — APPROVED** [review]
(awaiting ofborg builds on darwin)

**Comment by superherointj** [comment]
Should this target `master` instead of `staging`?

**Comment by ivmai** [comment]
What is the failures reason?

**Comment by roberth** [comment]
The staging branch had a build failure in the aws-sdk-cpp package which is a dependency of the (fresh) nix that would be used by some of the CI tests. Today there's a different failure, in llvm.
These failures don't have boehmgc as a dependency, so this PR did not cause them.

**Comment by lovesegfault** [comment]
Let's let it cook in staging :)

**Comment by stephank** [comment]
Seeing a test failure on `x86_64-darwin`:

```
./test-driver: line 112: 45816 Bus error: 10           "$@" >> "$log_file" 2>&1
FAIL: gctest
```

(not yet had time to investigate further)

**Comment by ivmai** [comment]
> Seeing a test failure on `x86_64-darwin`:
> 
> ```
> ./test-driver: line 112: 45816 Bus error: 10           "$@" >> "$log_file" 2>&1
> FAIL: gctest
> ```
> 
> (not yet had time to investigate further)

Got it. How often? Possible to get the stack trace ?

**Comment by stephank** [comment]
This is some funny business that is unique to Rosetta 2. The test consistently runs fine on a native `x86-64_darwin` machine, but fails sporadically on an M1 targetting Intel. (It does _sometimes_ succeed.)

```
$ ./gctest
Switched to incremental mode
Emulating dirty bits with mprotect/signals
KERN_PROTECTION_FAILURE while world is stopped
Bus error: 10
```

I can't seem to be able to attach lldb. I get `error: process exited with status -1 (Error 1)` with no further output.

**Comment by ivmai** [comment]
> Emulating dirty bits with mprotect/signals
> KERN_PROTECTION_FAILURE while world is stopped

Yes, it is a known issue in the upstream (https://github.com/ivmai/bdwgc/issues/178), first detected in 2017 (probably existed before).
Would be nice if someone fixes it.

**Pull request merged**
