### PR TITLE
qemu: riscv related fixes

### PR DESCRIPTION
**Pull request by dramforever**
Two fixes found when trying to use qemu on riscv.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux (native on x64, and cross x64 to riscv64 with `sdlSupport = false`)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dramforever** [comment]
After some discussion with qemu devs, it seems that the correct thing to do is indeed just not to pass `--cpu`, and let the configure script detect it based on `$CC`.

https://lore.kernel.org/qemu-devel/20230204112502.2558739-1-mjt@msgid.tls.msk.ru/T/

It seems that there is still a bit of problem with regards to cross qemu. I'll come back to it once I get that settled.

**Comment by dramforever** [comment]
cc @figsoda @SuperSandro2000 from #190560 and @NickCao from #147692

**Comment by figsoda** [comment]
the python change lgtm, don't know enough to review the change to `configureFlags`

**Comment by NickCao** [comment]
Had to disable sdl support to test due to dependency failure.

Builds fine crossing from x86_64-linux to riscv64-linux, build/host platform is correctly recognized by build system, qemu-user support is discovered and built.

**Review by NickCao — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg build qemu
@ofborg test qemu

**Pull request merged**
