### PR TITLE
buildFHSEnv: use bubblewrap by default

### PR DESCRIPTION
**Pull request by Atemu**
###### Description of changes

Finally finishing my work from 2020.

The only package in Nixpkgs which still needs chrootenv is quartus-prime now. I therefore consider buildFHSEnvChroot to be deprecated now and only kept for legacy applications.
cc @kwohlfahrt

cc @shlevy for testing zulip; it no longer white-screens for me with bubblewrap.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
I successfully tested basic execution of all affected apps except for:

- arduino-core
- conda
- dropbox
- houdini
- vmware-workstation

Which I could not get to run with or without chrootenv.

**Comment by shlevy** [comment]
Zulip works on this branch, thanks

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Atemu** [comment]
Further testing is probably only possible on unstable. I'll merge after ofBorg eval.

**Comment by natsukagami** [comment]
The new `buildFHSEnv` doesn't support aarch64 (#156244 for `vscode-fhs`), so some of my own packages are broken after this PR.
This seems to come from i686 `ldconfig` being pulled in by default.

**Comment by Atemu** [comment]
@natsukagami the old one did not support it either. aarch64-linux `vscode-fhs` does not eval on 327a9c55a3294d58a28ddc6ca7eac5cd10b55aec which is this PR's base.

**Comment by SuperSandro2000** [comment]
> the failure seems to be related to this upstream issue: [GoogleChromeLabs/bubblewrap#611](https://github.com/GoogleChromeLabs/bubblewrap/issues/611)

Aren't we using https://github.com/containers/bubblewrap ?

**Comment by betaboon** [comment]
> Aren't we using https://github.com/containers/bubblewrap ?

oh. you're right. but seems to boil down to the same problem !?

**Comment by cschierig** [comment]
I use `buildFHSUserEnv` to run neovim with my lua config as many of the language servers expect certain executables in certain places. bubblewrap doesnt't seem to be able to access files and directories owned by root. I discovered this when trying to `sudoedit` my nixos config.

 While the fix for now was to just switch to `buildFHSEnvChroot`,in the long term there probably needs to be a way for software which only works in an fhs environment to access files and directories owned by it.

**Comment by LuisChDev** [comment]
Hi, I second @cschierig here, I was going to ask if there were any plans to allow overriding the read-only mounts (there are none, I believe). Even if you override them by issuing a `--dev-mount` in `extraBwrapArgs`, there is the issue of ownership of the files. The NordVPN CLI client I'm packaging requires an FHS environment (unfree, hardcoded paths) and needs to modify `resolv.conf`. Hopefully we find a solution soon.

**Comment by Atemu** [comment]
@cschierig @LuisChDev please create a new issue on this.

**Comment by pedohorse** [comment]
> I successfully tested basic execution of all affected apps except for:
> 
>     * arduino-core
> 
>     * conda
> 
>     * dropbox
> 
>     * houdini
> 
>     * vmware-workstation
> 
> 
> Which I could not get to run with or without chrootenv.

while updating houdini package - tested and can confirm that houdini package **does not work** with new buildFHSEnv, but does work with buildFHSEnvChroot. reason is unclear for now

**Comment by SuperSandro2000** [comment]
Please provide more details otherwise we cannot assist fixing this.

**Comment by pedohorse** [comment]
Update: houdini package now works fine with new `buildFHSEnv`.

cause for errors were new default flags to bwrap in buildFHSEnv: `--die-with-parent` and `--unshare-pid` that were both interfering with the way houdini wants to work (in short: it spawns some licensing-related processes and expects at least one of them to live after main process exit, and allow multiple program instances to check existence of that process)

**Comment by corngood** [comment]
I just bisected a problem with `gdb` to here:

```
$ $(nix-build --no-out-link --expr 'with import <nixpkgs> {}; buildFHSUserEnv { name = "fhs"; runScript = writeScript "test" "exec ${gdb}/bin/gdb ${hello}/bin/hello -ex r"; }')/bin/fhs
GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/vd7m25a2r2v96ir53nrk8yxv73lnzc9s-hello-2.12.1/bin/hello...
(No debugging symbols found in /nix/store/vd7m25a2r2v96ir53nrk8yxv73lnzc9s-hello-2.12.1/bin/hello)
Starting program: /nix/store/vd7m25a2r2v96ir53nrk8yxv73lnzc9s-hello-2.12.1/bin/hello
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Hello, world!
[Inferior 1 (process 30) exited normally]
[1]  + 1990217 suspended (tty output)
$
```

It seems that signals  from the child process are causing bwrap to suspend.  I haven't dug into it much yet.

**Comment by Atemu** [comment]
@corngood Could you check whether any of bubblewrap's flags affect that issue?

**Comment by corngood** [comment]
Removing `--unshare-pid` fixes it.

**Comment by 06kellyjac** [comment]
Shouldn't something important like this make it into release notes? I guess there's an argument release notes are for nixos rather than nixpkgs helpers but it should be made visible somehow

**Comment by Atemu** [comment]
I opted for mentioning it in the breaking changes for the unstable channel thread because, ideally, the user should not see any change and the rest would be caught by unstable users.

I guess there might be downstream users, so a release note mention could make sense.

**Comment by Atemu** [comment]
I opted for mentioning it in the breaking changes for the unstable channel thread because, ideally, the user should not see any change and the rest would be caught by unstable users.

I guess there might be downstream users, so a release note mention could make sense.

**Comment by RaitoBezarius** [comment]
Please put up a release note for 23.05 for this.

**Comment by RaitoBezarius** [comment]
(this broke Conda to a public user in 23.05-beta.)

**Comment by rnhmjoj** [comment]
Another wandering git bisect user: this change broke software mixing in ALSA (dmix).
It means if you run any application that plays audio inside the FHS environment, it will seize the raw playback device and no other program will be able to use it.
The reason is that by default buildFHSEnv unshares the IPC namespace and breaks the POSIX shared memory [API](https://man7.org/linux/man-pages/man7/shm_overview.7.html), used by ALSA to coordinate processing generating the audio streams.

**Comment by rnhmjoj** [comment]
It can be fixed with just `unshareIpc = false`, but why was this security stuff turned on by default?
As far as I understand, the `buildFHSUserEnv` was never meant to provide isolation/security, it's just about running pre-compiled software on NixOS. This assumption should not have changed when moving from plain chroot to bubblewrap, which is essentially an implementation detail.

**Comment by SuperSandro2000** [comment]
If we get security for free with no drawbacks then why not but if ipc causes usually problems and is turned off for steam and lutris already it might make sense to turn it off by default.

**Comment by rnhmjoj** [comment]
The thing with security is that it never really comes for free. There are trade-offs and you need to know about them: turning on security features without a clear threat model and not telling the end users about is just asking for breakages.

**Comment by Atemu** [comment]
FHSEnvs make no security guarantees, `unshareIpc = false` sounds good to me.

**Pull request merged**
