### PR TITLE
haskellPackages.{crypton,SHA}: disable tests on aarch32

### PR DESCRIPTION
**Pull request by misuzu**
## Description of changes

`crypton` and `SHA` are dependencies of `shellcheck`, which is used by `writeShellApplication`
Upstream issues: https://github.com/kazu-yamamoto/crypton/issues/25 https://github.com/GaloisInc/SHA/issues/16

## Things done

- Built on platform(s)
  - [X] armv7l-linux (native)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@misuzu Thanks for reporting this.

We're generally reluctant to disable tests for security-related Haskell libraries, at least without a confirmation from upstream.

If you could debug exactly why the tests are failing (and prove that the tests are incorrect, not the library itself) on https://github.com/GaloisInc/SHA/issues/16, that would probably help get the upstream maintainer to respond faster.

**Comment by misuzu** [comment]
> If you could debug exactly why the tests are failing (and prove that the tests are incorrect, not the library itself) on [GaloisInc/SHA#16](https://github.com/GaloisInc/SHA/issues/16), that would probably help get the upstream maintainer to respond faster.

Sadly, I have zero knowledge on how to do that. I simply want to use `virtualisation.oci-containers` module (which requires `shellcheck` package) to start my containers on armv7l-linux hardware

**Comment by cdepillabout** [comment]
@misuzu Maybe you could disable the use of `shellcheck` in `writeShellApplication` on `armv7l-linux`, citing this PR?

**Comment by misuzu** [comment]
> @misuzu Maybe you could disable the use of `shellcheck` in `writeShellApplication` on `armv7l-linux`, citing this PR?

https://github.com/NixOS/nixpkgs/pull/266298

**Comment by misuzu** [comment]
Looks like shellcheck-minimal isn't affected, there's no need for this change

**Pull request closed without merging**
