### PR TITLE
goPackages: start restructuring packages

### PR DESCRIPTION
**Pull request by copumpkin**
This is a new scheme that I think avoids a lot of repetition resulting from the fact that the vast majority of the go package ecosystem lives on GitHub, and it's fairly common practice for people to depend on forks
with identical names.

This scheme structures a subset of the go package universe after GitHub namespaces, so all packages are scoped by author and then by repo. In the simplest case, all one needs to provide for a given owner/repo case is an attrset containing the revision and a sha256 for it. One can still obviously add more attributes for more complicated builds.

To save users (and other developers) from having to qualify all package names (like `hashicorp.consul` or `spf13.hugo`), I implemented a simple flattening scheme, where if the package name is unambiguous, one can refer to it unqualified. If it ambiguous, I throw an error explaining the ambiguity, telling the user to use a qualified attribute path.

This change doesn't, as far as I can tell, change any hashes.

If people like the proposal, we can start progressively moving things from the less structured attrset to the more structured one.

cc @wkennington (this is the thing we talked about on IRC) @lethalman @benley and other go contributors.

### CODE REVIEW

**Comment by globin** [comment]
:+1:

**Comment by copumpkin** [comment]
Another thing I like about this is that it standardizes (by construction) the name disambiguation scheme (which I can change if people want, but this seemed very simple).

**Comment by copumpkin** [comment]
Whoops, it looks like I broke some stuff. I'll look into the issues on travis, but this PR should still give you a basic idea of what I'm proposing.

**Comment by zimbatm** [comment]
This is pretty cool.
In the end I think the work to maintain a single plane of packages that all work together is exponential. But I like the implementation it's quite clever.

**Comment by lethalman** [comment]
So now I read that `go-packages.nix`, how do I know what attribute should I use? I either have to nix-repl, or trial and error several times.

**Comment by joachifm** [comment]
Is this still relevant after 1371084ae1f29f8890e65bcc872c1b1eedf17def?

**Comment by copumpkin** [comment]
Less relevant, but I still prefer having a real data model for how the packages are laid out. cc @cstrahan

**Comment by cstrahan** [comment]
My work and @copumpkin's are complementary, I think. I haven't had a
chance to look at this in depth, but I know that I like the end goal.
 
On Thu, Mar 10, 2016, at 10:42 AM, Daniel Peebles wrote:
> Less relevant, but I still prefer having a real data model for how the
> packages are laid out. cc @cstrahan[1]
> —
> Reply to this email directly or view it on GitHub[2].
>
 

Links:

  1. https://github.com/cstrahan
  2. https://github.com/NixOS/nixpkgs/pull/12010#issuecomment-194911677

**Comment by kamilchm** [comment]
@copumpkin what about it after https://github.com/NixOS/nixpkgs/pull/16017?

**Comment by Mic92** [comment]
go-packages.nix is gone.

**Pull request closed without merging**
