### PR TITLE
python3Packages.sphinxext-rediraffe: init at 0.2.7

### PR DESCRIPTION
**Pull request by zmitchell**
## Description of changes

This package is a Sphinx extension used to automatically detect moved pages and automatically generate redirects. It is intended to be used on [nix.dev](https://nix.dev). The repository is here: [sphinxext-rediraffe](https://github.com/wpilibsuite/sphinxext-rediraffe). The package has been tested against a local checkout of [nix.dev](https://nix.dev) that was ported to use `nixpkgs` rather than `poetry2nix` to build the site.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by asymmetric** [comment]
I don’t have the context around how useful this would be for us. I assume you’ve felt the pain?

**Comment by asymmetric** [comment]
@zmitchell are you still interested in maintaining this? (Asking cause you've since moved on from the Docs Team)

**Comment by zmitchell** [comment]
If you’re interested in taking over maintenance be my guest.

**Comment by asymmetric** [comment]
@zmitchell not interested, sorry :)

**Pull request closed without merging**
