### PR TITLE
factorio-headless: 1.1.53 -> 1.1.57

### PR DESCRIPTION
**Pull request by greaka**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by priegger — CHANGES_REQUESTED** [review]
Thanks for the contribution!

According to factorio.com, all versions (stable and experimental) are at 1.1.57 right now. So I think it makes sense to update everything to this version at the same time, not just factorio-headless. Running update.py should do exactly this.

**Comment by priegger** [comment]
Result of `nixpkgs-review pr 168684` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>factorio (factorio-experimental)</li>
    <li>factorio-demo</li>
    <li>factorio-headless (factorio-headless-experimental)</li>
  </ul>
</details>

**Comment by priegger** [comment]
I tested factorio and factorio-headless (just some seconds of gameplay), all seems to work. Thanks again!

@greaka : The commit message needs to reflect the additional updates, maybe something like "factorio*: 1.1.5x -> 1.1.57". Not sure if there's a rule how to handle those "update different versions to the same new version" commit we have here.

**Comment by greaka** [comment]
@priegger I've seen `factorio-*: 1.1.x -> 1.1.y` in the past.
I cannot update the commit message though, my git locks up whenever I try. Maybe it's the size of the repository, idk.
maintainers have rights to edit this branch. Feel free to do so if possible!

**Comment by priegger** [comment]
Factorio is not at 1.1.59 in master, so I'm closing this.

Thanks again @greak. ;-)

**Pull request closed without merging**
