### PR TITLE
xonsh: 0.3.4 -> 0.4.1

### PR DESCRIPTION
**Pull request by vrthra**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
- Disable windows tests that get erroneously executed

### CODE REVIEW

**Comment by rardiol** [comment]
I got some errors when building, but it seems to work anyway.

```
................................................................xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name 'bar' is not defined
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NameError: name 'bar' is not defined
....AssertionError
Could not load xonsh config.
.json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 17 (char 16)
Xonsh config file is not valid JSON.
.total 124
-rw-r--r-- 1 nixbld nixbld 26529 Jan  2  1980 CHANGELOG.rst
-rw-r--r-- 1 nixbld nixbld 14499 Jan  2  1980 CONTRIBUTING.rst
-rw-r--r-- 1 nixbld nixbld    17 Jan  2  1980 MANIFEST.in
-rw-r--r-- 1 nixbld nixbld  1135 Jan  2  1980 README.rst
drwxr-xr-x 1 nixbld nixbld    50 Jun 25 16:45 __pycache__
-rwxr-xr-x 1 nixbld nixbld 11898 Jan  2  1980 amalgamate.py
lrwxrwxrwx 1 nixbld nixbld    13 Jan  2  1980 appveyor.yml -> .appveyor.yml
lrwxrwxrwx 1 nixbld nixbld    12 Jan  2  1980 binstar.yml -> .binstar.yml
drwxr-xr-x 1 nixbld nixbld    64 Jun 25 16:45 build
-rw-r--r-- 1 nixbld nixbld   136 Jan  2  1980 codecov.yml
drwxr-xr-x 1 nixbld nixbld    56 Jun 25 16:45 dist
drwxr-xr-x 1 nixbld nixbld   750 Jan  2  1980 docs
-rw-r--r-- 1 nixbld nixbld  1573 Jan  2  1980 license
-rw-r--r-- 1 nixbld nixbld  3114 Jan  2  1980 logo.txt
drwxr-xr-x 1 nixbld nixbld    24 Jan  2  1980 news
-r--r--r-- 1 nixbld nixbld   164 Jun 25 16:45 nix_run_setup.py
drwxr-xr-x 1 nixbld nixbld    74 Jan  2  1980 recipe
-rwxr-xr-x 1 nixbld nixbld  4919 Jan  2  1980 release.xsh
-rw-r--r-- 1 nixbld nixbld    35 Jan  2  1980 requirements-docs.txt
-rw-r--r-- 1 nixbld nixbld    52 Jan  2  1980 requirements-tests.txt
drwxr-xr-x 1 nixbld nixbld    40 Jan  2  1980 scripts
-rwxr-xr-x 1 nixbld nixbld  7768 Jan  2  1980 setup.py
drwxr-xr-x 1 nixbld nixbld   842 Jun 25 16:46 tests
lrwxrwxrwx 1 nixbld nixbld    11 Jan  2  1980 travis.yml -> .travis.yml
drwxr-xr-x 1 nixbld nixbld  1084 Jun 25 16:45 xonsh
-rwxr-xr-x 1 nixbld nixbld  1540 Jan  2  1980 xonsh-in-docker.py
drwxr-xr-x 1 nixbld nixbld   136 Jun 25 16:45 xonsh.egg-info
drwxr-xr-x 1 nixbld nixbld    74 Jan  2  1980 xontrib
lrwxrwxrwx 1 nixbld nixbld    19 Jan  2  1980 xontribs.json -> xonsh/xontribs.json
.................................................................................Generating LALR tables
WARNING: 92 shift/reduce conflicts
WARNING: 9 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 74 resolved using rule (test_or_star_expr -> test)
WARNING: rejected rule (testlist -> test) in state 74
WARNING: reduce/reduce conflict in state 173 resolved using rule (test_or_star_expr -> test)
WARNING: rejected rule (testlist -> test) in state 173
WARNING: reduce/reduce conflict in state 245 resolved using rule (string_tok -> STRING)
WARNING: rejected rule (subproc_arg_part -> STRING) in state 245
..................................................................................................................................................................................................
xonsh: subprocess mode: command not found: the
Did you mean one of the following?
    tee:  Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tee
    tr:   Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tr)
    sh:   Command (/nix/store/hbgd7mbpylfz6zxj5bkdyi07yag77b8l-bash-4.3-p42/bin/sh)
    tty:  Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tty)
    tac:  Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tac)
KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
.
xonsh: subprocess mode: command not found: the
Did you mean one of the following?
    tee:  Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tee)
    tr:   Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tr)
    sh:   Command (/nix/store/hbgd7mbpylfz6zxj5bkdyi07yag77b8l-bash-4.3-p42/bin/sh)
    tty:  Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tty)
    tac:  Command (/nix/store/6m648r8w4qhqv8c33n09blp389bsvvx4-coreutils-8.25/bin/tac)
KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
.KeyError: 'Unknown environment variable: $XONSH_INTERACTIVE'
........................................................................xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be cr
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
xonsh: $XONSH_TRACEBACK_LOGFILE must be a filepath pointing to a file that either exists and is writable or that can be created.
..............
----------------------------------------------------------------------
Ran 949 tests in 29.496s

OK
```

**Comment by garbas** [comment]
@vrthra any idea why travis build fails?

**Comment by vrthra** [comment]
@garbas @rardiol I noticed the same errors in install test but that did not result in a failed build. But it seems to have something to do with the travis failure. I am investigating.

**Comment by vrthra** [comment]
@garbas @rardiol removing `test_replay.py` lets the builds pass. I checked the replay functionality on its own, and it seems to work.

**Comment by jb55** [comment]
still fails for me on nixos-unstable?
```
wrapping `/nix/store/jd0106mp7zdvg3502k83qj58qhx7jjv9-xonsh-0.4.3/bin/xonsh'...
running install tests
...........................................E
======================================================================
ERROR: test_contexts.test_functor_oneline_onecall_class
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/5kbiq195wl3hgq92lb2ywg8jrnsy7my4-python3.6-nose-1.3.7/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-xonsh-0.4.3.drv-0/xonsh-0.4.3-src/tests/test_contexts.py", line 251, in test_functor_oneline_onecall_class
    check_exec(s, glbs=glbs, locs=None)
  File "/tmp/nix-build-xonsh-0.4.3.drv-0/xonsh-0.4.3-src/tests/tools.py", line 123, in check_exec
    EXECER.exec(input, **kwargs)
  File "/tmp/nix-build-xonsh-0.4.3.drv-0/xonsh-0.4.3-src/xonsh/__amalgam__.py", line 16152, in exec
    transform=transform)
  File "/tmp/nix-build-xonsh-0.4.3.drv-0/xonsh-0.4.3-src/xonsh/__amalgam__.py", line 16120, in compile
    code = compile(tree, filename, mode)
  File "<xonsh-code>", line 3
SyntaxError: name 'x' is assigned to before global declaration

----------------------------------------------------------------------
Ran 44 tests in 0.539s

FAILED (errors=1)
builder for ‘/nix/store/acmmr1h0p0k1qcvqr8fyvd0ssgdly2q9-xonsh-0.4.3.drv’ failed with exit code 1
error: build of ‘/nix/store/acmmr1h0p0k1qcvqr8fyvd0ssgdly2q9-xonsh-0.4.3.drv’ failed
```

**Comment by jb55** [comment]
oops wrong issue

**Comment by jb55** [comment]
hmmm but I still get this error even when I revert d9871f52b49719ce55fcc089fa2cd12c67e9f0d7 ...

**Pull request merged**
