### PR TITLE
google-clasp: use nodePackages."@google/clasp"

### PR DESCRIPTION
**Pull request by malob**
###### Motivation for this change
I wanted to use this package, and the version in `nixpkgs` was out of date and wouldn't build. Seemed to make more sense to put it in `nodePackages` (especially given that the patch no longer applied), so that it would be kept up to date automatically.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
@ofborg test thelounge

**Comment by malob** [comment]
Result of `nixpkgs-review pr 157930` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>lumo</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>epgstation</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>mastodon-bot</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>styx</li>
    <li>thelounge</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-git</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-vimtex</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>yaml-language-server</li>
    <li>zerobin</li>
    <li>zx</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 157930` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>lumo</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>epgstation</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>mastodon-bot</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>styx</li>
    <li>thelounge</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-git</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-vimtex</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>yaml-language-server</li>
    <li>zerobin</li>
    <li>zx</li>
  </ul>
</details>

**Comment by malob** [comment]
Just rebased off of master to address merge conflicts.

**Comment by malob** [comment]
Result of `nixpkgs-review pr 157930` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>deltachat-desktop</li>
    <li>lumo</li>
    <li>mx-puppet-discord</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>epgstation</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>imapnotify</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>n8n</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>theLoungePlugins.themes.abyss</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>zx</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 157930` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>deltachat-desktop</li>
    <li>lumo</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>46 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>epgstation</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>imapnotify</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>theLoungePlugins.themes.abyss</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>zx</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 157930` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
    <li>teleprompter</li>
    <li>timedoctor</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>deltachat-desktop</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>73 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>imapnotify</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>odoo</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.themes.abyss</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>whalebird</li>
    <li>zx</li>
  </ul>
</details>

**Comment by malob** [comment]
@SuperSandro2000, any chance you could review this PR, or poke the appropriate person?

**Pull request merged**
