### PR TITLE
Python: remove 2.6 and 3.3

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

The last maintenance release of Python 2.6 was almost 3 years ago, and that of 3.3 close to 2 years.
A 3.3.7 was planned for February but hasn't seen the light yet.

Since we have 2.7, 3.4, 3.5 and a pre-release of 3.6 I think it is time to move on and get rid of these old versions.

### CODE REVIEW

**Comment by FRidh** [comment]
The reason for a PR against staging is to prevent a merge conflict since staging holds already a larger Python change.

**Comment by garbas** [comment]
what about keeping python26 and only removing python26Packages. while we don't use python26 in nixpkgs i do see this being valuable for develop (and test) packages against multiple python versions.

**Comment by FRidh** [comment]
@garbas `python26` is currently marked as broken. The package set isn't evaluated, so if you keep the one you might as well keep the other as well.

**Comment by domenkozar** [comment]
https://www.python.org/dev/peps/pep-0398/#lifespan

> After that, security updates (source only) will be released until 5 years after the release of 3.3 final, which will be September 2017.

I'd keep 3.3 as someone might need it to support a project.

**Comment by rbvermaa** [comment]
We would like to keep python26 around.

**Comment by FRidh** [comment]
Maybe later then.

**Comment by jgeerds** [comment]
I'm also using python26 (not python26Packages) for one work related project.

**Comment by FRidh** [comment]
Interesting, because Python 2.6 has been broken for quite some time now...

**Pull request closed without merging**
