### PR TITLE
nginxStable: 1.20.2 -> 1.22.0

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
[nginx-1.22.0](https://nginx.org/en/download.html) stable version has been released, incorporating new features and bug fixes from the 1.21.x mainline branch  — including hardening against potential requests smuggling and cross-protocol attacks, [ALPN support](https://nginx.org/en/docs/stream/ngx_stream_ssl_module.html#ssl_alpn) in the stream module, better distribution of connections among worker processes on Linux, support for the PCRE2 library, support for OpenSSL 3.0 and SSL_sendfile(), improved [sendfile](https://nginx.org/en/docs/http/ngx_http_core_module.html#sendfile) handling on FreeBSD, the[ mp4_start_key_frame](https://nginx.org/en/docs/http/ngx_http_mp4_module.html#mp4_start_key_frame) directive, and more.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
Build with pcre2:
```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index d6522bc2186..9351041083c 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -22002,11 +22002,13 @@ with pkgs;
     modules = [ nginxModules.rtmp nginxModules.dav nginxModules.moreheaders ];
     # Use latest boringssl to allow http3 support
     openssl = quictls;
+    pcre = pcre2;
   };

   nginxStable = callPackage ../servers/http/nginx/stable.nix {
     zlib = zlib-ng.override { withZlibCompat = true; };
     openssl = openssl_3_0;
+    pcre = pcre2;
     withPerl = false;
     # We don't use `with` statement here on purpose!
     # See https://github.com/NixOS/nixpkgs/pull/10474#discussion_r42369334
@@ -22016,6 +22018,7 @@ with pkgs;
   nginxMainline = callPackage ../servers/http/nginx/mainline.nix {
     zlib = zlib-ng.override { withZlibCompat = true; };
     openssl = openssl_3_0;
+    pcre = pcre2;
     withKTLS = true;
     withPerl = false;
     # We don't use `with` statement here on purpose!

```

**Comment by Izorkin** [comment]
With current variant error build openresty:
```
openresty> checking for PCRE library ... not found
openresty> checking for PCRE library in /usr/local/ ... not found
openresty> checking for PCRE library in /usr/include/pcre/ ... not found
openresty> checking for PCRE library in /usr/pkg/ ... not found
openresty> checking for PCRE library in /opt/local/ ... not found
openresty> ./configure: error: the HTTP rewrite module requires the PCRE library.
openresty> You can either disable the module by using --without-http_rewrite_module
openresty> option, or install the PCRE library into the system, or build the PCRE library
openresty> statically from the source with nginx by using --with-pcre=<path> option.
openresty> ERROR: failed to run command: sh ./configure --prefix=/nix/store/s7fvc08bpa8byknjjwv4gjddp92adi52-openresty-1.19.9.1/nginx \...

```

**Comment by ajs124** [comment]
hm. do we just want to mark openresty as broken?

**Comment by Izorkin** [comment]
Openresty working with my patch.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Izorkin** [comment]
Update nginx-quic:
```diff
diff --git a/pkgs/servers/http/nginx/quic.nix b/pkgs/servers/http/nginx/quic.nix
index 4db1b19644c..8743d31939b 100644
--- a/pkgs/servers/http/nginx/quic.nix
+++ b/pkgs/servers/http/nginx/quic.nix
@@ -6,8 +6,8 @@
 callPackage ./generic.nix args {
   src = fetchhg {
     url = "https://hg.nginx.org/nginx-quic";
-    rev = "55b38514729b"; # branch=quic
-    sha256 = "sha256-EJ3Fuxb4Z43I5eSb3mzzIOBfppAZ4Adv1yVZWbVCv0A=";
+    rev = "5b1011b5702b"; # branch=quic
+    sha256 = "sha256-q1gsJ6CJ7SD1XLitygnRusJ+exFPFg+B3wdsN+NvuL8=";
   };

   preConfigure = ''

```

**Comment by Izorkin** [comment]
@ajs124 fix test:
```diff
diff --git a/nixos/modules/services/web-servers/nginx/default.nix b/nixos/modules/services/web-servers/nginx/default.nix
index 0c2333399e8..160d76597c8 100644
--- a/nixos/modules/services/web-servers/nginx/default.nix
+++ b/nixos/modules/services/web-servers/nginx/default.nix
@@ -932,7 +932,7 @@ in
         # System Call Filtering
         SystemCallArchitectures = "native";
         SystemCallFilter = [ "~@cpu-emulation @debug @keyring @mount @obsolete @privileged @setuid" ]
-          ++ optionals ((cfg.package != pkgs.tengine) && (!lib.any (mod: (mod.disableIPC or false)) cfg.package.modules)) [ "~@ipc" ];
+          ++ optionals ((cfg.package != pkgs.tengine) && (cfg.package != pkgs.openresty) && (!lib.any (mod: (mod.disableIPC or false)) cfg.package.modules)) [ "~@ipc" ];
       };
     };


```

**Comment by Izorkin** [comment]
@GrahamcOfBorg test nginx-http3

**Review by Izorkin — APPROVED** [review]

**Comment by ajs124** [comment]
hm. maybe we should just get rid of `openresty` and `tengine`. would be good to know if anybody still uses them.

**Pull request merged**
