### PR TITLE
fix node updater

### PR DESCRIPTION
**Pull request by iv-nn**
###### Motivation for this change

The following error since #70974 when running `./generate.sh`:
```
./generate.sh: line 5: cd: /home/user/src/nixpkgs/pkgs/development/node-packages/pkgs/development/node-packages: No such file or directory
```

`$NODE_NIXPKGS_PATH` already points to `/pkgs/development/node-packages`, appending it again makes the path erroneous.

###### Things done

removed duplicate trailing path.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by iv-nn** [comment]
I should probably have opened an issue to discuss this before. It looked like an easy fix but something else must be wrong since now the `composition-v*.nix` contains:
```
nodeEnv = import ../../../../home/user/src/nixpkgs/pkgs/development/node-packages/node-env.nix
```
I don't know enough about `node2nix` to find the issue.

**Comment by iv-nn** [comment]
It seems to be related to the new temp directory used by `generate.sh`, `node2nix` use absolute paths if some of it's parameters are absolute paths.

**Comment by rileyinman** [comment]
+1, I had to revert my generate.sh to an older commit in order to rebase my node-packages PR to master since the new version kept breaking things. In my opinion the previous version should be restored until this new idea can be fully tested.

**Review by mmilata — APPROVED** [review]
Fixes the problem for me:+1:.

**Comment by iv-nn** [comment]
Fixed in 216c58a

**Pull request closed without merging**
