### PR TITLE
gnupg: 2.4.0 -> 2.4.1

### PR DESCRIPTION
**Pull request by afh**
###### Description of changes

Please let me know if this PR's merge base should rather be `master` than `staging`.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by marsam — APPROVED** [review]
LGTM

Release notes: https://dev.gnupg.org/T6454

**Comment by afh** [comment]
Thanks for merging, @vcunat, I look forward to [the ADSK support](https://www.gnupg.org/blog/20230321-adsk.html) GnuPG 2.4.1 brings.

**Comment by vcunat** [comment]
Something around pinentry input changed apparently.  Our VM tests regressed around that point.
https://hydra.nixos.org/build/218897070
https://hydra.nixos.org/build/218931684
Also mentioned on https://github.com/NixOS/nixpkgs/pull/229429#issuecomment-1537795091

**Comment by afh** [comment]
Thanks for raising this, @vcunat, I'll have a look.

**Comment by afh** [comment]
What I gather from the logs is this:

1. `nixos/tests/sway` ([log](https://hydra.nixos.org/build/218931684/nixlog/2)) times out hinting at a configuration or installation issue regarding pinentry.

2. `nixos/tests/gnupg.nix` ([log](https://hydra.nixos.org/build/218897070)) fails due to: `gpg: agent_genkey failed: No pinentry`.

At this point I'm uncertain what the underlying cause is, i.e. is pinentry not installed for some reason or is the gpg-agent misconfigured and it does not find any pinentry binaries.

How can the test environment be inspected for debugging?

* It would be helpful to see the output of `gpgconf --check-programs`
* and the `gpg.conf` and `gpg-agent.conf` files used when running the tests

**Comment by vcunat** [comment]
I'm not very good with NixOS VM tests.  They can be run easily, e.g. `nix-build -QA nixosTests.gnupg` but I know basically nothing about real debugging them.

**Comment by vcunat** [comment]
I noticed a passphrase-related change in 2.4.1, but not like I've looked into details: https://dev.gnupg.org/T6093

**Comment by afh** [comment]
Being on macOS I'll look into spinning up a NixOS VM to run the tests. I'm not sure I see the connection between the pinentry issue and https://dev.gnupg.org/T6093 can you please elaborate bit?

**Comment by vcunat** [comment]
Either way, I think I should ping maintainers of the broken NixOS tests (sway + gnupg): @primeos, @Synthetica9, @rnhmjoj.  Maybe they'll have an idea, too.

**Comment by rnhmjoj** [comment]
I guess this release includes https://dev.gnupg.org/rGeae28f1bd4a5632e8f8e85b7248d1c4d4a10a5ed.
I would revert and postpone the update until the NixOS module is fixed, otherwise gpg is  essentially unusable.

Anyway, please, don't ignore the tests: the gnupg one was even linked to the package.

**Comment by vcunat** [comment]
Hmm, so that was apparently a breaking change?  Merged in a period when breaking changes were disallowed in nixpkgs.

**Comment by afh** [comment]
Thanks for chiming in and providing the additional context, @rnhmjoj very much appreciated. A patch release seemed innocent at the time and I wasn't aware of the profile changes and their implications for NixOS (praises [sandro](https://dev.gnupg.org/p/sandro/) for their comments over on the [GnuPG issue](https://dev.gnupg.org/rGeae28f1bd4a5632e8f8e85b7248d1c4d4a10a5ed)).

I assumed that any tests are triggered run from changes in PRs and would catch any breaking changes, this does not seem to be the case. Where would I need to look to see if nixpkgs changes from a PR break NixOS related tests?

**Comment by vcunat** [comment]
There's no such case for these particular cases.  Changing package like gnupg requires really lots of CPU to even get to building such tests.

**Comment by vcunat** [comment]
So I reverted it to 2.4.0 for now.

**Comment by corngood** [comment]
I didn't see this issue before, but I have a change that adds the units back: #231108.

**Comment by corngood** [comment]
Here's a PR to un-revert this #231110

**Pull request merged**
