### PR TITLE
zettlr: 2.3.0 -> 3.0.2

### PR DESCRIPTION
**Pull request by mimame**
## Description of changes
https://github.com/Zettlr/Zettlr/releases/tag/v3.0.0
https://github.com/Zettlr/Zettlr/releases/tag/v3.0.1
https://github.com/Zettlr/Zettlr/releases/tag/v3.0.2

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by gp2112 — APPROVED** [review]
lgtm

**Comment by yorickvP** [comment]
Looks like this is quite the breaking change. Maybe we should put something in the release notes?

**Comment by devhell** [comment]
Thank you for looking into updating this. Please note, version `3.0.1` has been released meanwhile.

**Review by gp2112 — APPROVED** [review]

**Comment by DeeUnderscore** [comment]
Looks like upstream has released [3.0.2](https://github.com/Zettlr/Zettlr/releases/tag/v3.0.2)

**Review by DeeUnderscore — CHANGES_REQUESTED** [review]
`nixpkgs-review` is failing for me, since `all-packages.nix` uses [a reference to `zettlr-beta`](https://github.com/NixOS/nixpkgs/blob/de59540c5628c678ebf5c30e3c465e11c2b90bba/pkgs/top-level/all-packages.nix#L42096). Please drop it there, too

**Review by gp2112 — APPROVED** [review]

**Review by DeeUnderscore — APPROVED** [review]
Looks good, thanks.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zettlr</li>
  </ul>
</details>

**Comment by devhell** [comment]
Can this be merged, please?

**Review by pbsds — APPROVED** [review]
Result of `nixpkgs-review pr 253676` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zettlr</li>
  </ul>
</details>


- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] all depending packages build
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [x] patches that are remotely available are fetched rather than vendored

**Pull request merged**
