### PR TITLE
python3Packages.pytorch: fix Darwin build by disabling GCD

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

**Request:** could someone with Darwin ofborg privileges trigger a build of `python37Packages.pytorch` and `python38Packages.pytorch`? My MacBook is not fast enough that I want to attempt a full build of PyTorch to test this.

PyTorch 1.6.0 has updated the vendored pthreadpool library, which has recently
added support for Grand Central Dispatch. Unfortunately, it uses functionality
(DISPATCH_APPLY_AUTO) that is only available since macOS 10.13, whereas we are
still using 10.12 libraries.

We can't directly pass through option to vendored libraries, since the setup.py
scripts creates/filters the options that are passed to CMake. So, instead, this
adds a small patch that disables the GCD functionality in pthreadpool.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build python37Packages.pytorch

**Comment by danieldk** [comment]
Thanks @jonringer ! Turns out pthreadpool attempts to use GCD anyway in a header, even if it's configured not to in CMake. So, I have updated the patch to fix this.

I also found that `install_name_tool` was still called on the `dev` output rather than `lib`. I have fixed that as well.

Hopefully it will build now. It would be nice if someone with Darwin privileges could trigger the build again.

**Comment by danieldk** [comment]
Builds successfully on my MacBook now:

```
❯ nix-shell -p 'with import ./default.nix {}; python37.withPackages (ps: with ps; [ pytorch ])'
>>> torch.randn((10,)) @ torch.randn((10,))
tensor(6.7712)
```

So, this is ready for review.

**Comment by jonringer** [comment]
@GrahamcOfBorg build python37Packages.pytorch

**Comment by danieldk** [comment]
Timed out :cry:.

**Pull request merged**
