### PR TITLE
MATE 1.28

### LINKED ISSUE #176089: caja-with-extensions doesn't install .desktop files into $XDG_DATA_DIRS
### Describe the bug
caja-with-extensions doesn't install .desktop files into $XDG_DATA_DIRS

In particular, after installing caja-with-extensions, other applications aren't able to run it when they need to show folder content to the user.

caja package does install .desktop files, and doesn't have this problem.

### Steps To Reproduce
1. `$ nix-shell -p mate.caja-with-extensions`
2. ```$ find `echo $XDG_DATA_DIRS|tr ":" " "` -name 'caja*.desktop'```

no `caja*.desktop` entries found

### Expected behavior
multiple `caja*.desktop` records should be found, like with `caja` package

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.0, NixOS, 22.05 (Quokka), 22.05.379.08950a6e29c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by bobby285271**
This updates the MATE desktop to 1.28

... and fixes #176089 as this rewrites caja-with-extensions and this is now installed by default.

**Status (2024-03-12):**

- ~~There is an known issue that `mate-panel --replace` crashes the panel~~. Fixed in mate-desktop 1.28.2.
- I pushed the mate-wayland-session packaging, **please check the [release notes (in this PR)](https://github.com/NixOS/nixpkgs/pull/289062/files)** for details.

**General ideas:**

- Enable wayland support when possible. 
- As a result of above, we are also enabling in-process support, **which means the applets are not provided as executables**.
- Stay on autotools for now before meson files are properly disted and cause no regressions.

**Useful links:**

- https://pub.mate-desktop.org/rss.xml
- https://pub.mate-desktop.org/releases/1.28/

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build mate.mate-utils

**Comment by bobby285271** [comment]
@ofborg build mate.mate-utils

**Comment by bobby285271** [comment]
@ofborg test mate

**Comment by bobby285271** [comment]
@ofborg build mate

**Comment by bobby285271** [comment]
@ofborg build mate.mate-user-share mate.mate-indicator-applet mate.mate-control-center mate.python-caja mate.mate-utils mate.mate-sensors-applet mate.mate-screensaver mate.mate-applets mate.engrampa mate.caja-extensions mate.atril mate.mate-power-manager mate.mate-panel-with-applets mate.mate-panel mate.mate-media mate.caja-with-extensions mate.caja mate.pluma mate.mozo mate.mate-user-guide mate.mate-terminal mate.mate-system-monitor mate.mate-settings-daemon mate.mate-session-manager mate.mate-polkit mate.mate-notification-daemon mate.mate-menus mate.mate-icon-theme mate.libmateweather mate.mate-calc mate.marco mate.mate-backgrounds mate.eom mate.libmatemixer mate.libmatekbd mate.mate-desktop mate.mate-common

**Comment by bobby285271** [comment]
If you wish to review or testing please do, with the release of both mate-wayland-session 1.28.0 and mate-desktop 1.28.2 I think this is very close to merge.

@ofborg test mate

**Comment by bobby285271** [comment]
@ofborg test mate mate-wayland

**Comment by bobby285271** [comment]
@ofborg test mate mate-wayland

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 289062` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>79 packages built:</summary>
  <ul>
    <li>ayatana-indicator-session</li>
    <li>blueberry</li>
    <li>budgie.budgie-gsettings-overrides</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-python</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.nemo.dev</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapp</li>
    <li>cinnamon.xapp.dev</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>hypnotix</li>
    <li>lightdm-slick-greeter</li>
    <li>mate.atril</li>
    <li>mate.caja</li>
    <li>mate.caja-dropbox</li>
    <li>mate.caja-extensions</li>
    <li>mate.caja-with-extensions</li>
    <li>mate.engrampa</li>
    <li>mate.eom</li>
    <li>mate.libmatekbd</li>
    <li>mate.libmatemixer</li>
    <li>mate.libmateweather</li>
    <li>mate.marco</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-backgrounds</li>
    <li>mate.mate-calc</li>
    <li>mate.mate-common</li>
    <li>mate.mate-control-center</li>
    <li>mate.mate-desktop</li>
    <li>mate.mate-desktop.dev</li>
    <li>mate.mate-gsettings-overrides</li>
    <li>mate.mate-icon-theme</li>
    <li>mate.mate-icon-theme-faenza</li>
    <li>mate.mate-indicator-applet</li>
    <li>mate.mate-media</li>
    <li>mate.mate-menus</li>
    <li>mate.mate-netbook</li>
    <li>mate.mate-notification-daemon</li>
    <li>mate.mate-panel</li>
    <li>mate.mate-panel-with-applets</li>
    <li>mate.mate-polkit</li>
    <li>mate.mate-power-manager</li>
    <li>mate.mate-screensaver</li>
    <li>mate.mate-sensors-applet</li>
    <li>mate.mate-session-manager</li>
    <li>mate.mate-settings-daemon</li>
    <li>mate.mate-settings-daemon-wrapped</li>
    <li>mate.mate-system-monitor</li>
    <li>mate.mate-terminal</li>
    <li>mate.mate-themes</li>
    <li>mate.mate-tweak</li>
    <li>mate.mate-tweak.dist</li>
    <li>mate.mate-user-guide</li>
    <li>mate.mate-user-share</li>
    <li>mate.mate-utils</li>
    <li>mate.mate-wayland-session</li>
    <li>mate.mozo</li>
    <li>mate.pluma</li>
    <li>mate.python-caja</li>
    <li>plata-theme</li>
    <li>python311Packages.xapp</li>
    <li>python312Packages.xapp</li>
    <li>sticky</li>
    <li>timeshift</li>
    <li>timeshift-minimal</li>
    <li>timeshift-unwrapped</li>
    <li>wayfirePlugins.firedecor</li>
    <li>xdg-desktop-portal-xapp</li>
    <li>xed-editor</li>
    <li>xmonad_log_applet_mate</li>
    <li>xplayer</li>
  </ul>
</details>

@ofborg test cinnamon

**Comment by bobby285271** [comment]
@ofborg build mate.pluma

**Comment by romildo** [comment]
At least on my system, downloading the source code is too slow, making the build fail. Maybe after this is merged, we can consider obtaining the sources from the git repository.

**Comment by bobby285271** [comment]
@ofborg test mate mate-wayland

> https://github.com/NixOS/nixpkgs/pull/289062#issuecomment-1994408843

Actually both `pub.mate-desktop.org` and `github.com` are sometimes [hard to access for me](https://en.wikipedia.org/wiki/Great_Firewall), though release tarballs sometimes do simplify the build process. :upside_down_face:

**Comment by romildo** [comment]
Maybe we can avoid the installation of two instances of the caja package:

```console
$ ls /nix/store | sort --key=1.33 | grep -i caja-1.28.0$
6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
qvj22g9igr3d1zv7sb3pqdw1qx5833x2-caja-1.28.0
```
```console
$ nix why-depends --all /run/current-system /nix/store/6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
/nix/store/mn5i6zy97bsym9lfvdamlrds906mbi12-nixos-system-romildo-Mate-Nvidia-24.05.git.3de103dc96d2
├───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
│   ├───/nix/store/4xvypjw2lg0284whgpw3gsbp6ngzw0dv-caja-extensions-1.28.0
│   │   └───/nix/store/6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
│   ├───/nix/store/bpif8ji8fxh4xjxj0g6fm4gwyg5a2cyn-engrampa-1.28.1
│   │   └───/nix/store/6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
│   ├───/nix/store/p6p8fmdpif4ccff4nyw5mawsrm88xywj-caja-with-extensions-1.28.0
│   │   ├───/nix/store/6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
│   │   └───/nix/store/4xvypjw2lg0284whgpw3gsbp6ngzw0dv-caja-extensions-1.28.0
│   ├───/nix/store/pfqv37i7xnj7qmq2457vx4hsha27hncm-mate-control-center-1.28.0
│   │   └───/nix/store/6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
│   ├───/nix/store/vwi5g0nqvdz9m7xr8s3a5gf8r6bxh1rf-atril-1.28.0
│   │   └───/nix/store/6z439d6wqbdik3ah0mwjh6lma33fcivl-caja-1.28.0
│   └───/nix/store/b6s1gjriy3940427lig3azpg4rg95xzx-mate-settings-daemon-wrapped-1.28.0
│       └───/nix/store/pfqv37i7xnj7qmq2457vx4hsha27hncm-mate-control-center-1.28.0
└───/nix/store/s6znx2ag3fgbr1d7n2wb1921530a5vbp-etc
    ├───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
    ├───/nix/store/j7pv9rv35hhl6dk2xl492mikw8wysb88-dbus-1
    │   └───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
    ├───/nix/store/3gd8d5qklvy3ls4yb76f5a1cmvnrjc1g-system-units
    │   ├───/nix/store/ka1ymc93d9626qzm28x2vkwfl01wdrz2-unit-polkit.service
    │   │   └───/nix/store/4x8hb29c7b0l56vhrqwhgvxfjd4lc1yn-X-Restart-Triggers-polkit
    │   │       └───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
    │   └───/nix/store/1rgwbbr5wwp5jl1gd0rmi2dlk376bgh5-unit-dbus.service
    │       └───/nix/store/jj3gby5arl7m35kdmwvjbz0nnqizdv0z-X-Restart-Triggers-dbus
    │           └───/nix/store/j7pv9rv35hhl6dk2xl492mikw8wysb88-dbus-1
    └───/nix/store/ljmvbr4grv2h3fp5fv25wi83yf3xgwvr-user-units
        └───/nix/store/3j9ywl17dfvv36n6b65j0jh1cl09v0rd-unit-dbus.service
            └───/nix/store/jj3gby5arl7m35kdmwvjbz0nnqizdv0z-X-Restart-Triggers-dbus
```

```console
$ nix why-depends --all /run/current-system /nix/store/qvj22g9igr3d1zv7sb3pqdw1qx5833x2-caja-1.28.0
/nix/store/mn5i6zy97bsym9lfvdamlrds906mbi12-nixos-system-romildo-Mate-Nvidia-24.05.git.3de103dc96d2
├───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
│   └───/nix/store/p6p8fmdpif4ccff4nyw5mawsrm88xywj-caja-with-extensions-1.28.0
│       └───/nix/store/qvj22g9igr3d1zv7sb3pqdw1qx5833x2-caja-1.28.0
└───/nix/store/s6znx2ag3fgbr1d7n2wb1921530a5vbp-etc
    ├───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
    ├───/nix/store/j7pv9rv35hhl6dk2xl492mikw8wysb88-dbus-1
    │   └───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
    ├───/nix/store/3gd8d5qklvy3ls4yb76f5a1cmvnrjc1g-system-units
    │   ├───/nix/store/ka1ymc93d9626qzm28x2vkwfl01wdrz2-unit-polkit.service
    │   │   └───/nix/store/4x8hb29c7b0l56vhrqwhgvxfjd4lc1yn-X-Restart-Triggers-polkit
    │   │       └───/nix/store/76m0ggiiydwp5h7k2svsa9j0iqx5l3sd-system-path
    │   └───/nix/store/1rgwbbr5wwp5jl1gd0rmi2dlk376bgh5-unit-dbus.service
    │       └───/nix/store/jj3gby5arl7m35kdmwvjbz0nnqizdv0z-X-Restart-Triggers-dbus
    │           └───/nix/store/j7pv9rv35hhl6dk2xl492mikw8wysb88-dbus-1
    └───/nix/store/ljmvbr4grv2h3fp5fv25wi83yf3xgwvr-user-units
        └───/nix/store/3j9ywl17dfvv36n6b65j0jh1cl09v0rd-unit-dbus.service
            └───/nix/store/jj3gby5arl7m35kdmwvjbz0nnqizdv0z-X-Restart-Triggers-dbus
```

**Comment by bobby285271** [comment]
mate-wayland-session 1.28.3 [GitHub release](https://github.com/mate-desktop/mate-wayland-session/releases/tag/v1.28.3) was made 10 hours ago, I've verified that it uses an [existing tag](https://github.com/mate-desktop/mate-wayland-session/tags) or at least does not affect the source hash.

@ofborg test mate-wayland

> https://github.com/NixOS/nixpkgs/pull/289062#issuecomment-1997707465

I dropped the `withWrapper` option, I agree it looks ugly :sweat_drops:

**Comment by romildo** [comment]
Not everything works on Wayland. For instance, the keyboard shortcuts, or the panel applets I already have on my mate configuration. But I did not explored it very much. Just tried it for some minutes.

But somewhere the authors say mate on Wayland is still experimental. So it is ok to merge this PR, I think.

**Comment by bobby285271** [comment]
Yeah I think Wayfire will only take care of keybindings configured in `wayfire.ini`, e.g. <kbd>Alt</kbd> + <kbd>Tab</kbd>. And applets won't be loaded `grep -Rnr 'Platforms' /run/current-system/sw/share/mate-panel/applets` [does not contain `Wayland`](https://github.com/mate-desktop/mate-panel/blob/83da4d5e069cb428fd8032f4ab5f2e4642910787/mate-panel/panel-addto.c#L426). I am aware of a few more issues e.g. mate-control-center tells you "mate-settings-daemon not running" sometimes but actually m-s-d [crashes](//github.com/mate-desktop/mate-settings-daemon/issues/412#issuecomment-1962051005) due to trying to interact with x11 (e.g. backtrace points to `gdk_x11_atom_to_xatom_for_display`, or `XQueryExtension`, etc), [not able logout](https://github.com/mate-desktop/mate-wayland-session/issues?q=logout+in%3Atitle+is%3Aissue), [hardcoded autostart items](https://github.com/mate-desktop/mate-wayland-session/blob/964343df2889b764d4794cc61069c018bc8f4dbd/session/mate-wayland-components.sh#L49), etc. Let's hope these gets improved in future releases :shrug:

**Review by romildo — APPROVED** [review]

**Pull request merged**
