### PR TITLE
makeWrapper,makeBinaryWrapper: implement `--append-flags`

### PR DESCRIPTION
**Pull request by ncfavier**
I've confirmed that the `teams` wrapper appends the arguments correctly. cc @tricktron @liff @srhb @drupol

### CODE REVIEW

**Review by bergkvist — APPROVED** [review]
The changes look good to me.

**Comment by ncfavier** [comment]
Rebased on staging-next so that the tests have a chance to get built; no changes

**Comment by oxalica** [comment]
Looks the same as #131170.

**Comment by thiagokokada** [comment]
Is there anything blocking this PR :thinking: ?

**Comment by ncfavier** [comment]
I don't think so, apart from the slight rudeness to the author of https://github.com/NixOS/nixpkgs/pull/131170 who had their PR open for a year (sorry!)

**Comment by thiagokokada** [comment]
> I don't think so, apart from the slight rudeness to the author of #131170 who had their PR open for a year (sorry!)

Going to merge it them.

**Pull request merged**
