### PR TITLE
gcc11: 11.3.0 -> 11.4.0

### PR DESCRIPTION
**Pull request by dasJ**
###### Description of changes

Fixes these bugs: https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=11.4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`) → built a hello world
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Doesn't need to go to `staging`, I think.  Could be e.g. `staging-next` as a compromise, I don't know.  /cc @trofi I guess.

**Review by vcunat — CHANGES_REQUESTED** [review]
According to CI, some darwin-specific patches need to be dropped.

**Comment by trofi** [comment]
Yeah, targeting `master` should be totally fine.

`darwin` patches usually need to be updated to include minor version:

```
      ++ optionals stdenv.isDarwin [
        (fetchpatch {
          # There are no upstream release tags in https://github.com/iains/gcc-11-branch.
          # 2d280e7 is the commit from https://github.com/gcc-mirror/gcc/releases/tag/releases%2Fgcc-11.3.0
          url = "https://github.com/iains/gcc-11-branch/compare/2d280e7eafc086e9df85f50ed1a6526d6a3a204d..gcc-11.3-darwin-r2.diff";
          sha256 = "sha256-LFAXUEoYD7YeCG8V9mWanygyQOI7U5OhCRIKOVCCDAg=";
        })
      ]
```

`11.4` tag seems to be present: https://github.com/iains/gcc-11-branch/releases/tag/gcc-11.4-darwin-r0 . Worth a try?

**Comment by vcunat** [comment]
- I don't think this is a big rebuild, so targeting master will make things easier &ndash; in particular, ofBorg builds.
- on (x86_64-)darwin I still see lots of
  ```
  Reversed (or previously applied) patch detected!  Assume -R?
  ```

**Review by trofi — APPROVED** [review]

**Comment by vcunat** [comment]
OfBorg says it fails on aarch64-darwin while it succeeded on Hydra: https://hydra.nixos.org/job/nixpkgs/trunk/gcc11.aarch64-darwin  (x86_64-darwin seems unclear due to timeout)

Though I'm no darwin fan...

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 235728` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>cudaPackages.nvidia_driver</li>
    <li>python310Packages.theanoWithCuda</li>
    <li>python310Packages.theanoWithCuda.dist</li>
    <li>python311Packages.theanoWithCuda</li>
    <li>python311Packages.theanoWithCuda.dist</li>
    <li>sgx-psw</li>
    <li>sgx-sdk</li>
    <li>sgx-ssl</li>
    <li>truecrack-cuda</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>cudaPackages.tensorrt (cudaPackages.tensorrt_8_5_3)</li>
    <li>cudaPackages.tensorrt.dev (cudaPackages.tensorrt_8_5_3.dev)</li>
    <li>cudaPackages.tensorrt_8_5_1</li>
    <li>cudaPackages.tensorrt_8_5_1.dev</li>
    <li>cudaPackages.tensorrt_8_5_2</li>
    <li>cudaPackages.tensorrt_8_5_2.dev</li>
    <li>cudaPackages.tensorrt_8_6_0</li>
    <li>cudaPackages.tensorrt_8_6_0.dev</li>
    <li>katagoTensorRT</li>
    <li>mathematica-cuda</li>
    <li>python310Packages.tensorrt</li>
    <li>python310Packages.tensorrt.dist</li>
    <li>python310Packages.tiny-cuda-nn</li>
    <li>python311Packages.tensorrt</li>
    <li>python311Packages.tensorrt.dist</li>
    <li>tiny-cuda-nn</li>
  </ul>
</details>
<details>
  <summary>143 packages built:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>coreboot-toolchain.aarch64</li>
    <li>coreboot-toolchain.arm</li>
    <li>coreboot-toolchain.i386</li>
    <li>coreboot-toolchain.nds32le</li>
    <li>coreboot-toolchain.ppc64</li>
    <li>coreboot-toolchain.riscv</li>
    <li>coreboot-toolchain.x64</li>
    <li>cudaPackages.backendStdenv</li>
    <li>cudaPackages.cuda_cccl</li>
    <li>cudaPackages.cuda_cudart</li>
    <li>cudaPackages.cuda_cuobjdump</li>
    <li>cudaPackages.cuda_cupti</li>
    <li>cudaPackages.cuda_cuxxfilt</li>
    <li>cudaPackages.cuda_demo_suite</li>
    <li>cudaPackages.cuda_documentation</li>
    <li>cudaPackages.cuda_gdb</li>
    <li>cudaPackages.cuda_memcheck</li>
    <li>cudaPackages.cuda_nsight</li>
    <li>cudaPackages.cuda_nvcc</li>
    <li>cudaPackages.cuda_nvdisasm</li>
    <li>cudaPackages.cuda_nvml_dev</li>
    <li>cudaPackages.cuda_nvprof</li>
    <li>cudaPackages.cuda_nvprune</li>
    <li>cudaPackages.cuda_nvrtc</li>
    <li>cudaPackages.cuda_nvtx</li>
    <li>cudaPackages.cuda_nvvp</li>
    <li>cudaPackages.cuda_sanitizer_api</li>
    <li>cudatoolkit (cudaPackages.cudatoolkit ,cudatoolkit_11)</li>
    <li>cudatoolkit.doc (cudaPackages.cudatoolkit.doc ,cudatoolkit_11.doc)</li>
    <li>cudatoolkit.lib (cudaPackages.cudatoolkit.lib ,cudatoolkit_11.lib)</li>
    <li>cudaPackages.cudnn (cudaPackages.cudnn_8_9)</li>
    <li>cudaPackages.cudnn_8_4</li>
    <li>cudaPackages.cudnn_8_5</li>
    <li>cudaPackages.cudnn_8_6</li>
    <li>cudaPackages.cudnn_8_7</li>
    <li>cudaPackages.cudnn_8_8</li>
    <li>cudaPackages.cutensor</li>
    <li>cudaPackages.cutensor.dev</li>
    <li>cudaPackages.fabricmanager</li>
    <li>cudaPackages.libcublas</li>
    <li>cudaPackages.libcufft</li>
    <li>cudaPackages.libcufile</li>
    <li>cudaPackages.libcurand</li>
    <li>cudaPackages.libcusolver</li>
    <li>cudaPackages.libcusparse</li>
    <li>cudaPackages.libnpp</li>
    <li>cudaPackages.libnvidia_nscq</li>
    <li>cudaPackages.libnvjpeg</li>
    <li>cudaPackages.nccl</li>
    <li>cudaPackages.nccl.dev</li>
    <li>cudaPackages.nsight_compute</li>
    <li>cudaPackages.nsight_systems</li>
    <li>cudaPackages.nvidia_fs</li>
    <li>dmd</li>
    <li>driversi686Linux.amdvlk</li>
    <li>faissWithCuda</li>
    <li>faissWithCuda.demos</li>
    <li>forge</li>
    <li>gcc11</li>
    <li>gcc11.info</li>
    <li>gcc11.man</li>
    <li>gcc11Stdenv</li>
    <li>gfortran11</li>
    <li>gfortran11.info</li>
    <li>gfortran11.man</li>
    <li>gnat11</li>
    <li>gnat11.info</li>
    <li>gnat11.man</li>
    <li>gpu-burn</li>
    <li>gromacsCudaMpi</li>
    <li>gwe</li>
    <li>hip-nvidia</li>
    <li>hip-nvidia.doc</li>
    <li>katagoWithCuda</li>
    <li>librealsenseWithCuda</li>
    <li>librealsenseWithCuda.dev</li>
    <li>magma (magma-cuda ,magma_2_7_1)</li>
    <li>magma_2_6_2</li>
    <li>manaplus</li>
    <li>nvidia-thrust-cuda</li>
    <li>nvtop</li>
    <li>nvtop-nvidia</li>
    <li>openmm</li>
    <li>python310Packages.bitsandbytes</li>
    <li>python310Packages.bitsandbytes.dist</li>
    <li>python310Packages.cupy</li>
    <li>python310Packages.cupy.dist</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python310Packages.jaxlibWithCuda.dist</li>
    <li>python310Packages.numbaWithCuda</li>
    <li>python310Packages.numbaWithCuda.dist</li>
    <li>python310Packages.openai-triton</li>
    <li>python310Packages.openai-triton-bin</li>
    <li>python310Packages.openai-triton-bin.dist</li>
    <li>python310Packages.openai-triton.dist</li>
    <li>python310Packages.openmm</li>
    <li>python310Packages.pycuda</li>
    <li>python310Packages.pycuda.dist</li>
    <li>python310Packages.pynvml</li>
    <li>python310Packages.pynvml.dist</li>
    <li>python310Packages.pyrealsense2WithCuda</li>
    <li>python310Packages.pyrealsense2WithCuda.dev</li>
    <li>python310Packages.tensorflowWithCuda</li>
    <li>python310Packages.tensorflowWithCuda.dist</li>
    <li>python310Packages.torchWithCuda</li>
    <li>python310Packages.torchWithCuda.dev</li>
    <li>python310Packages.torchWithCuda.dist</li>
    <li>python310Packages.torchWithCuda.lib</li>
    <li>python310Packages.torchWithRocm</li>
    <li>python310Packages.torchWithRocm.dev</li>
    <li>python310Packages.torchWithRocm.dist</li>
    <li>python310Packages.torchWithRocm.lib</li>
    <li>python310Packages.torchaudio-bin</li>
    <li>python310Packages.torchaudio-bin.dist</li>
    <li>python310Packages.torchvision-bin</li>
    <li>python310Packages.torchvision-bin.dist</li>
    <li>python310Packages.trainer</li>
    <li>python310Packages.trainer.dist</li>
    <li>python311Packages.cupy</li>
    <li>python311Packages.cupy.dist</li>
    <li>python311Packages.jaxlibWithCuda</li>
    <li>python311Packages.jaxlibWithCuda.dist</li>
    <li>python311Packages.openai-triton</li>
    <li>python311Packages.openai-triton-bin</li>
    <li>python311Packages.openai-triton-bin.dist</li>
    <li>python311Packages.openai-triton.dist</li>
    <li>python311Packages.openmm</li>
    <li>python311Packages.pycuda</li>
    <li>python311Packages.pycuda.dist</li>
    <li>python311Packages.pynvml</li>
    <li>python311Packages.pynvml.dist</li>
    <li>python311Packages.pyrealsense2WithCuda</li>
    <li>python311Packages.pyrealsense2WithCuda.dev</li>
    <li>python311Packages.torchaudio-bin</li>
    <li>python311Packages.torchaudio-bin.dist</li>
    <li>python311Packages.torchvision-bin</li>
    <li>python311Packages.torchvision-bin.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
    <li>xgboostWithCuda</li>
    <li>xpraWithNvenc</li>
    <li>xpraWithNvenc.dist</li>
  </ul>
</details>

**Comment by vcunat** [comment]
`x86_64-darwin` builds for me locally now (timeout on ofBorg); `aarch64-darwin` failed on ofBorg but I hope it won't on Hydra.

**Pull request merged**
