### PR TITLE
home-assistant: 2021.2.1 -> 2021.2.2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.2.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM and builds on amd64

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112446` at 4734f396 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/0fa0d3249a4dabdcabfb42843ebb495a">home-assistant</a></li></li>
  </ul>
</details>

**Comment by mweinelt** [comment]
aarch64 has a failing test, x86_64-linux fails somewhere in the vm test env.

```
=================================== FAILURES ===================================
_____________________________ test_throttle_async ______________________________
[gw30] linux -- Python 3.8.7 /nix/store/akrgx3370c6bl8akpd3j75hzqclicdl4-python3-3.8.7/bin/python3.8
pyfuncitem = <Function test_throttle_async>
    def pytest_pyfunc_call(pyfuncitem):  # type: ignore
        """
        Run coroutines in an event loop instead of a normal function call.
        """
        fast = pyfuncitem.config.getoption("--aiohttp-fast")
        if asyncio.iscoroutinefunction(pyfuncitem.function):
            existing_loop = pyfuncitem.funcargs.get(
                "proactor_loop"
            ) or pyfuncitem.funcargs.get("loop", None)
            with _runtime_warning_context():
                with _passthrough_loop_context(existing_loop, fast=fast) as _loop:
                    testargs = {
                        arg: pyfuncitem.funcargs[arg]
                        for arg in pyfuncitem._fixtureinfo.argnames
                    }
>                   _loop.run_until_complete(pyfuncitem.obj(**testargs))
/nix/store/ix0rsk9sx75vr3g3sk8rgh1bqb6psp8y-python3.8-aiohttp-3.7.3/lib/python3.8/site-packages/aiohttp/pytest_plugin.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/nix/store/akrgx3370c6bl8akpd3j75hzqclicdl4-python3-3.8.7/lib/python3.8/contextlib.py:120: in __exit__
    next(self.gen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    @contextlib.contextmanager
    def _runtime_warning_context():  # type: ignore
        """
        Context manager which checks for RuntimeWarnings, specifically to
        avoid "coroutine 'X' was never awaited" warnings being missed.
    
        If RuntimeWarnings occur in the context a RuntimeError is raised.
        """
        with warnings.catch_warnings(record=True) as _warnings:
            yield
            rw = [
                "{w.filename}:{w.lineno}:{w.message}".format(w=w)
                for w in _warnings
                if w.category == RuntimeWarning
            ]
            if rw:
>               raise RuntimeError(
                    "{} Runtime Warning{},\n{}".format(
                        len(rw), "" if len(rw) == 1 else "s", "\n".join(rw)
                    )
                )
E               RuntimeError: 1 Runtime Warning,
E               /nix/store/ix0rsk9sx75vr3g3sk8rgh1bqb6psp8y-python3.8-aiohttp-3.7.3/lib/python3.8/site-packages/aiohttp/test_utils.py:536:coroutine 'Debouncer._handle_timer_finish' was never awaited
/nix/store/ix0rsk9sx75vr3g3sk8rgh1bqb6psp8y-python3.8-aiohttp-3.7.3/lib/python3.8/site-packages/aiohttp/pytest_plugin.py:138: RuntimeError
```

**Comment by mweinelt** [comment]
@GrahamcOfBorg test home-assistant

**Pull request merged**
