### PR TITLE
chromium: update to 60.0.3112.90 and add flags

### PR DESCRIPTION
**Pull request by bendlas**
###### Motivation for this change

The update commit is the regular stable update + necessary patches.

The build flag commit takes the opportunity to get rid of cruft, to make chromium use a couple of more system dependencies (instead of building its own).
It also adds a couple of build flags, lifted from the arch recipe.

###### Things done

Build in progress, at about 90%, an iteration of this already worked. I'll check the boxes, when finished.

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bendlas** [comment]
__NOPE__ there is a linker error due to `re2` will fix tomorrow ...

**Comment by bendlas** [comment]
Builds and runs now

**Comment by bendlas** [comment]
Updated to latest stable. Still builds and runs. Please merge and cherry-pick to stable

**Comment by globin** [comment]
cc @aszlig

**Comment by Ericson2314** [comment]
I built this sucessfully

**Comment by globin** [comment]
I'm unsure about some of the changes and @aszlig knows more about this.

**Comment by aszlig** [comment]
If I ignore the meaningless commit message, the rest looks good to me :-)

@Ericson2314: Did you also run it and it went without errors in `stderr`?

**Review by aszlig — APPROVED** [review]

**Comment by bendlas** [comment]
Since this isn't backported to stable yet, and regarding the uncertainty about the altered flags: The commits are structured such that only the update commits (`chromium: x -> y`) can be cherry-picked and it should still work. fwiw

**Comment by Ericson2314** [comment]
@aszlig I have no idea; I was building it for someone else.

**Pull request merged**
