### PR TITLE
tree-wide: users.extraUsers -> users.users, users.extraGroups -> users.groups

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
Followup of #42746, now replacing usages of `users.extraUsers` and `users.extraGroups` with `users.users` and `users.groups`.

This is more than a quick search/replace, as there's valid uses for `extraGroups` (either as option in other modules or as `users.users.<name?>.extraGroups`, so please have a very cautious look.
I did run some tests on my machine, but can't run all.

/cc @volth, @xeji 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Looked through all replacements, all good

**Comment by flokli** [comment]
@Infinisil thanks for the review! Are you comfortable merging it then? ;-)

**Comment by Infinisil** [comment]
Sorry I don't have merge rights :). Approval hook gray: reviewer can't merge; approval hook green: reviewer can merge

I mostly leave the reviews so people with merge rights have it easier and know that another pair of eyes has taken a look

**Comment by Infinisil** [comment]
@7c6f434c I actually just asked @edolstra yesterday via IRC, haven't gotten a response yet though :) (sneaky ping)

**Comment by 7c6f434c** [comment]
Often asking @rbvermaa gets a faster reaction on such requests.

**Pull request merged**
