### PR TITLE
vimPlugins: bufferize-vim (init at 2022-06-25), vim-openscad (init at 2022-07-26)

### PR DESCRIPTION
**Pull request by malob**
###### Description of changes

Add two Vim plugins.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by malob** [comment]
Result of `nixpkgs-review pr 203537` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.airline</li>
    <li>vimPlugins.echodoc</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.orgmode</li>
  </ul>
</details>
<details>
  <summary>113 packages built:</summary>
  <ul>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.asynctasks-vim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bufferize-vim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.echodoc-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.jq-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.lsp-format-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neon</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rust-vim</li>
    <li>vimPlugins.satellite-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-colorschemes</li>
    <li>vimPlugins.vim-gh-line</li>
    <li>vimPlugins.vim-gutentags</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-openscad</li>
    <li>vimPlugins.vim-sexp-mappings-for-regular-people</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 203537` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.airline</li>
    <li>vimPlugins.echodoc</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.orgmode</li>
  </ul>
</details>
<details>
  <summary>113 packages built:</summary>
  <ul>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.asynctasks-vim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bufferize-vim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.echodoc-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.jq-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.lsp-format-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neon</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rust-vim</li>
    <li>vimPlugins.satellite-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-colorschemes</li>
    <li>vimPlugins.vim-gh-line</li>
    <li>vimPlugins.vim-gutentags</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-openscad</li>
    <li>vimPlugins.vim-sexp-mappings-for-regular-people</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by figsoda** [comment]
vimPlugins.orgmode is broken, I filed a pr upstream to fix this: https://github.com/nvim-orgmode/orgmode/pull/456, we can update it once its merged or revert it back to when it wasn't broken

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 203537` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.airline</li>
    <li>vimPlugins.echodoc</li>
  </ul>
</details>
<details>
  <summary>121 packages built:</summary>
  <ul>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.asynctasks-vim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bufferize-vim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.echodoc-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.jq-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.lsp-format-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neon</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rust-vim</li>
    <li>vimPlugins.satellite-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.ssr-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-cool</li>
    <li>vimPlugins.vim-gh-line</li>
    <li>vimPlugins.vim-gutentags</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-openscad</li>
    <li>vimPlugins.vim-parinfer</li>
    <li>vimPlugins.vim-sexp-mappings-for-regular-people</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
