### PR TITLE
linux-packages: fix argsOverride

### LINKED ISSUE #314591: Linux kernels - zen, lqx, xanmod and libre - ignore argsOverride
### Describe the bug
Mainline / hardened / testing / ... kernels can be painlessly modified via `argsOverride`:
```
nix-repl> (pkgs.linux.override { argsOverride = { version = "123"; }; }).version       
"123"
```
Sadly, this does not work with a bunch of other kernel variants:
```
nix-repl> (pkgs.linux_zen.override { argsOverride = { version = "123"; }; }).version
"6.9.1"

nix-repl> (pkgs.linux_lqx.override { argsOverride = { version = "123"; }; }).version           
"6.8.10"

nix-repl> (pkgs.linux_xanmod.override { argsOverride = { version = "123"; }; }).version
"6.6.31"

nix-repl> (pkgs.linux_latest-libre.override { argsOverride = { version = "123"; }; }).version
"6.9.1"
```

### Expected behavior
All kernels should honor `argsOverride`

### Additional context
I am not entirely sure how dynamic binding is implemented in kernel stuff, however slightly changing xanmod parts this way 
```diff
diff --git a/pkgs/os-specific/linux/kernel/xanmod-kernels.nix b/pkgs/os-specific/linux/kernel/xanmod-kernels.nix
index 3135eefab984..db8defc1a29e 100644
--- a/pkgs/os-specific/linux/kernel/xanmod-kernels.nix
+++ b/pkgs/os-specific/linux/kernel/xanmod-kernels.nix
@@ -1,23 +1,22 @@
-{ lib, stdenv, fetchFromGitHub, buildLinux, ... } @ args:
+{ lib, stdenv, fetchFromGitHub, buildLinux, variant, ... } @ args:
 
 let
   # These names are how they are designated in https://xanmod.org.
 
   # NOTE: When updating these, please also take a look at the changes done to
   # kernel config in the xanmod version commit
-  ltsVariant = {
-    version = "6.6.31";
-    hash = "sha256-Hs2DjNG7mj4qb1P0u7XAgrNizx8oqs1ot563IvRKnhU=";
-    variant = "lts";
-  };
-
-  mainVariant = {
-    version = "6.8.10";
-    hash = "sha256-lGzZThINyeZrMBDaGVujXB+DzIdfFBo7Z/Bhyj21I2g=";
-    variant = "main";
+  variants = {
+    lts = {
+      version = "6.6.31";
+      hash = "sha256-Hs2DjNG7mj4qb1P0u7XAgrNizx8oqs1ot563IvRKnhU=";
+    };
+    main = {
+      version = "6.8.10";
+      hash = "sha256-lGzZThINyeZrMBDaGVujXB+DzIdfFBo7Z/Bhyj21I2g=";
+    };
   };
 
-  xanmodKernelFor = { version, suffix ? "xanmod1", hash, variant }: buildLinux (args // rec {
+  xanmodKernelFor = { version, suffix ? "xanmod1", hash }: buildLinux (args // rec {
     inherit version;
     modDirVersion = lib.versions.pad 3 "${version}-${suffix}";
 
@@ -55,7 +54,4 @@ let
     };
   } // (args.argsOverride or { }));
 in
-{
-  lts = xanmodKernelFor ltsVariant;
-  main = xanmodKernelFor mainVariant;
-}
+  xanmodKernelFor variants.${variant}
diff --git a/pkgs/top-level/linux-kernels.nix b/pkgs/top-level/linux-kernels.nix
index 24eadff372f1..27ab4e02b362 100644
--- a/pkgs/top-level/linux-kernels.nix
+++ b/pkgs/top-level/linux-kernels.nix
@@ -241,15 +241,15 @@ in {
 
     # This contains the variants of the XanMod kernel
     xanmodKernels = callPackage ../os-specific/linux/kernel/xanmod-kernels.nix {
+      variant = "lts";
       kernelPatches = [
         kernelPatches.bridge_stp_helper
         kernelPatches.request_key_helper
       ];
     };
-
-    linux_xanmod = xanmodKernels.lts;
-    linux_xanmod_stable = xanmodKernels.main;
-    linux_xanmod_latest = xanmodKernels.main;
+    linux_xanmod = xanmodKernels;
+    linux_xanmod_stable = xanmodKernels.override {variant = "main";};
+    linux_xanmod_latest = xanmodKernels.override {variant = "main";};
 
     linux_libre = deblobKernel packageAliases.linux_default.kernel;
 
```
seems to fix  `argsOverride`:
```
nix-repl> (pkgs.linux_xanmod.override { argsOverride = { version = "123"; }; }).version
"123"
```
zen and lqx look similar to xanmod, no idea about libre

### Notify maintainers
Pinging people who seem to update affected packages often
@zzzsyyy @JerrySM64 @K900 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31-xanmod1, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qjn46ly46g7vyrg46k3n7j1f23jfjby0-source/files/nixos-unstable`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AtaraxiaSjel**
## Description of changes

Fixes #314591.

Some linux kernel variants such as zen, lqx, xanmod and libre can't be modified using `argsOverride`.

For example:
```
nix-repl> (pkgs.linux_zen.override { argsOverride = { version = "1.2.3"; }; }).version
"6.10.1"
```

After this PR:
```
nix-repl> (pkgs.linux_zen.override { argsOverride = { version = "1.2.3"; }; }).version         
"1.2.3"
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fpletz — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]
LGTM, although I have not tested these changes myself

**Comment by AtaraxiaSjel** [comment]
Rebased to current master

**Comment by jys1670** [comment]
Thanks for finishing this! Could you fix merge conflict?
I've seen @K900 and @Atemu touching files modified in this PR, perhaps they could help with merging.

**Comment by AtaraxiaSjel** [comment]
@jys1670 thank you! rebased.
@K900 @Atemu can you help with merging, please?

**Comment by K900** [comment]
Have you tested that the update scripts still work?

**Comment by AtaraxiaSjel** [comment]
@K900
Yes, I've tested the update scripts for lqx and zen kernel (update-zen.py).
The linux-libre script didn't work for me even before my PR, as nix-prefetch-svn doesn't print the hash. However, I haven't made any changes that could have broken this script.
Additionally, xanmod does not appear to have an update script, at least not one that I'm aware of?

**Pull request merged**
