### PR TITLE
enpass: fix install to work with browser extensions

### PR DESCRIPTION
**Pull request by guillaumekoenig**
###### Motivation for this change

Enpass is a password manager. Browser extensions in Chrome and Firefox talk to it via websocket, but currently aren't working in NixOS. The issue comes from Enpass looking up the browser process through lsof, with argument the port from the client side (the browser).

Enpass requires lsof to be installed in /usr/bin in order to function correctly. Because the path is hardcoded inside Enpass binary, we try to wrap it in a user fhs compliant environment. Unfortunately this is not sufficient. NixOS uses Linux user namespaces to implement the fhs env, with restricted access to `/proc/*/fd/*` in particular. This prevents lsof to function fully.

This patch bypasses the restriction by talking to lsof outside of the user namespace via named pipe. The browser extensions for Enpass are now working. However a better fix might be to lessen the restrictions in NixOS user namespaces, if appropriate.

Can somebody help with this ? A way to reproduce is by creating a fhs user environment with nix-shell, running it with this `shell.nix` in the current directory :
```
{ pkgs ? import <nixpkgs> {} }:

(pkgs.buildFHSUserEnv {
  name = "test-user-namespacing";
  targetPkgs = pkgs: with pkgs; [ lsof strace ];
}).env
```
Outside of the namespace, lsof sees Firefox connections :
```
[guillaume@nixos:~/Downloads]$ lsof -i|grep firefox
firefox    1149 ...
```
Inside of it it doesn't, strace showing permission denied errors :
```
[guillaume@nixos:~/Downloads]$ nix-shell shell.nix 
test-user-namespacing-chrootenv:guillaume@nixos:~/Downloads$ lsof -i|grep firefox
test-user-namespacing-chrootenv:guillaume@nixos:~/Downloads$ strace lsof -i 2>&1 |grep /proc/1149/fd
open("/proc/1149/fd", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
readlink("/proc/1149/fd/0", 0x7ffec4e23740, 4096) = -1 EACCES (Permission denied)
open("/proc/1149/fdinfo/0", O_RDONLY)   = 5
readlink("/proc/1149/fd/1", 0x7ffec4e23740, 4096) = -1 EACCES (Permission denied)
```

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
If it is only about redirecting executable, you can also use libredirect instead of namespaces.

**Comment by guillaumekoenig** [comment]
It looks like libredirect should do the trick. I'll update the patch soon. Thanks for the tip!

**Comment by guillaumekoenig** [comment]
I updated the branch following your directions. In the end /usr/bin/lsof is not hardcoded in the binary as I had previously thought. Prefixing the lsof path to the PATH environment variable suffices.

There is a twist however, the main app (Enpass) checks that the helper binary (EnpassHelper) is the one expected. It makes sure it has not been tampered with by computing its sha256 sum (see https://discussion.enpass.io/index.php?/topic/104-solved-enpass-52-browser-extension-doesnt-work-on-archlinux/). It fails in our case since we fix the dynamic linker path, modifying the binary. Using libredirect does the trick : the open call for the helper binary is redirected to a copy that has not been tampered with and the check succeeds. The browser extension is then working correctly.

Interestingly, the execve call is not impacted by the redirection (which is what we want, when executed we want the version with the dynamic linker's path fixed). Only the open call is redirected.

**Comment by grahamc** [comment]
This works great, thank you. I'm merging and backporting to fix this behavior on stable, too.

**Comment by grahamc** [comment]
Merged in 0465b1407bc0b69c2b35e281fbafb615715ef280  and backported at a485c8a1f1d0e9ab5bf7951d3661b3ffaf50fd46. Thank you!

**Pull request closed without merging**
