### PR TITLE
deck: 1.40.1 -> 1.40.2

### PR DESCRIPTION
**Pull request by liyangau**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mattpolzin — COMMENTED** [review]
Do you mind adding a `meta.mainProgram` entry since this derivation produces an executable?

**Comment by liyangau** [comment]
Done.

Let's see if I can still use the merge bot after all the checks are done.

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 344763` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>deck</li>
  </ul>
</details>

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 344763` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>deck</li>
  </ul>
</details>

**Review by mattpolzin — APPROVED** [review]

**Comment by mattpolzin** [comment]
My recollection is that mergebot can only be used for PRs created by r-ryantm, but I can hold off on merging this PR so you can give it a try.

**Comment by liyangau** [comment]
My impression of the merge bot is to allow maintainers to quickly release/fix their packages.

If it only works for `PRs created by r-ryantm`, the benefit of using the merge bot is quite limited.  Maintainers has no control when this bot creates the PR after all.

Furthermore, I did not expect to wait so long for ofborg to complete all checks... it has been 8 hours and still in the queue...

**Comment by liyangau** [comment]
@NixOS/nixpkgs-merge-bot merge

**Comment by liyangau** [comment]
> My recollection is that mergebot can only be used for PRs created by r-ryantm, but I can hold off on merging this PR so you can give it a try.

You are right... merge bot can not be used for this PR.

**Pull request merged**
