### PR TITLE
vim: add indent-blankline-nvim

### PR DESCRIPTION
**Pull request by onsails**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
builder for '/nix/store/1mnx827z825psljsbdcgfn0370pnz0x8-maple.drv' failed with exit code 1; last 10 log lines:

  ERROR: cargoSha256 is out of date

  Cargo.lock is not the same in maple-vendor.tar.gz

  To fix the issue:
  1. Use "0000000000000000000000000000000000000000000000000000" as the cargoSha256 value
  2. Build the derivation and wait for it to fail with a hash mismatch
  3. Copy the 'got: sha256:' value back into the cargoSha256 field
```

**Comment by onsails** [comment]
> ```
> builder for '/nix/store/1mnx827z825psljsbdcgfn0370pnz0x8-maple.drv' failed with exit code 1; last 10 log lines:
> 
>   ERROR: cargoSha256 is out of date
> 
>   Cargo.lock is not the same in maple-vendor.tar.gz
> 
>   To fix the issue:
>   1. Use "0000000000000000000000000000000000000000000000000000" as the cargoSha256 value
>   2. Build the derivation and wait for it to fail with a hash mismatch
>   3. Copy the 'got: sha256:' value back into the cargoSha256 field
> ```

resolved

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109641` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>vimPlugins.vim-clap: log was empty</li>
  </ul>
</details>
<details>
<summary>
51 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.Coqtail</li>
<li>vimPlugins.SyntaxRange (vimPlugins.vim-SyntaxRange)</li>
<li>vimPlugins.Tagbar (vimPlugins.tagbar)</li>
<li>vimPlugins.airline (vimPlugins.vim-airline)</li>
<li>vimPlugins.ale</li>
<li>vimPlugins.aniseed</li>
<li>vimPlugins.barbar-nvim</li>
<li>vimPlugins.coc-denite</li>
<li>vimPlugins.coc-explorer</li>
<li>vimPlugins.coc-lua</li>
<li>vimPlugins.coc-nvim</li>
<li>vimPlugins.completion-nvim</li>
<li>vimPlugins.conjure</li>
<li>vimPlugins.denite (vimPlugins.denite-nvim)</li>
<li>vimPlugins.deol-nvim</li>
<li>vimPlugins.deoplete-fish</li>
<li>vimPlugins.deoplete-khard</li>
<li>vimPlugins.deoplete-nvim</li>
<li>vimPlugins.deoplete-tabnine</li>
<li>vimPlugins.fennel-vim</li>
<li>vimPlugins.fern-vim</li>
<li>vimPlugins.fzf-vim</li>
<li>vimPlugins.indent-blankline-nvim</li>
<li>vimPlugins.lh-brackets</li>
<li>vimPlugins.lightline-ale</li>
<li>vimPlugins.lualine-nvim</li>
<li>vimPlugins.neoformat</li>
<li>vimPlugins.neosnippet-snippets</li>
<li>vimPlugins.nvim-dap</li>
<li>vimPlugins.nvim-lspconfig</li>
<li>vimPlugins.nvim-tree-lua</li>
<li>vimPlugins.nvim-treesitter</li>
<li>vimPlugins.nvim-ts-rainbow</li>
<li>vimPlugins.onehalf</li>
<li>vimPlugins.polyglot (vimPlugins.vim-polyglot)</li>
<li>vimPlugins.telescope-nvim</li>
<li>vimPlugins.traces-vim</li>
<li>vimPlugins.verilog_systemverilog-vim</li>
<li>vimPlugins.vim-floaterm</li>
<li>vimPlugins.vim-illuminate</li>
<li>vimPlugins.vim-lsc</li>
<li>vimPlugins.vim-lsp</li>
<li>vimPlugins.vim-oscyank</li>
<li>vimPlugins.vim-puppet</li>
<li>vimPlugins.vim-rsi</li>
<li>vimPlugins.vim-snippets</li>
<li>vimPlugins.vim-vsnip</li>
<li>vimPlugins.vim-yaml</li>
<li>vimPlugins.vimtex</li>
<li>vimPlugins.vista-vim</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109641` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.vim-clap</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109641` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
52 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.Coqtail</li>
<li>vimPlugins.ale</li>
<li>vimPlugins.aniseed</li>
<li>vimPlugins.barbar-nvim</li>
<li>vimPlugins.coc-denite</li>
<li>vimPlugins.coc-explorer</li>
<li>vimPlugins.coc-lua</li>
<li>vimPlugins.coc-nvim</li>
<li>vimPlugins.completion-nvim</li>
<li>vimPlugins.conjure</li>
<li>vimPlugins.denite-nvim</li>
<li>vimPlugins.deol-nvim</li>
<li>vimPlugins.deoplete-fish</li>
<li>vimPlugins.deoplete-khard</li>
<li>vimPlugins.deoplete-nvim</li>
<li>vimPlugins.deoplete-tabnine</li>
<li>vimPlugins.fennel-vim</li>
<li>vimPlugins.fern-vim</li>
<li>vimPlugins.fzf-vim</li>
<li>vimPlugins.indent-blankline-nvim</li>
<li>vimPlugins.lh-brackets</li>
<li>vimPlugins.lightline-ale</li>
<li>vimPlugins.lualine-nvim</li>
<li>vimPlugins.neoformat</li>
<li>vimPlugins.neosnippet-snippets</li>
<li>vimPlugins.nvim-dap</li>
<li>vimPlugins.nvim-lspconfig</li>
<li>vimPlugins.nvim-tree-lua</li>
<li>vimPlugins.nvim-treesitter</li>
<li>vimPlugins.nvim-ts-rainbow</li>
<li>vimPlugins.onehalf</li>
<li>vimPlugins.tagbar</li>
<li>vimPlugins.telescope-nvim</li>
<li>vimPlugins.traces-vim</li>
<li>vimPlugins.verilog_systemverilog-vim</li>
<li>vimPlugins.vim-SyntaxRange</li>
<li>vimPlugins.vim-airline</li>
<li>vimPlugins.vim-clap</li>
<li>vimPlugins.vim-floaterm</li>
<li>vimPlugins.vim-illuminate</li>
<li>vimPlugins.vim-lsc</li>
<li>vimPlugins.vim-lsp</li>
<li>vimPlugins.vim-oscyank</li>
<li>vimPlugins.vim-polyglot</li>
<li>vimPlugins.vim-puppet</li>
<li>vimPlugins.vim-rsi</li>
<li>vimPlugins.vim-snippets</li>
<li>vimPlugins.vim-vsnip</li>
<li>vimPlugins.vim-yaml</li>
<li>vimPlugins.vimtex</li>
<li>vimPlugins.vista-vim</li>
</ul>
</details>

**Pull request merged**
