### PR TITLE
gnomeExtensions: auto-update, fix the patches

### LINKED ISSUE #274659: gnomeExtensions.tophat reports GTop not found on nixos-unstable channel
### Describe the bug
When I trying to use this extension on ```nixos-unstable``` channel, it reports:
```
Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
```

Already tried workaround: https://github.com/fflewddur/tophat/issues/106#issuecomment-1848319826, but it still cause same error.

### Steps To Reproduce
1. Install gnomeExtensions.tophat
2. Logout and login to gnome-shell
3. tophat will not working and report error

### Expected behavior
```gnomeExtensions.tophat``` should not report any error and display correct status on topbar

### Screenshots
图片

### Additional context
There is indeed a related patch for this extension: https://github.com/NixOS/nixpkgs/blob/3dda6d5ed56af34534dd4cdcdd85627df25aec55/pkgs/desktops/gnome/extensions/extensionOverrides.nix#L122C1-L129C6, but for some reason it is not working on unstable channel. Not sure for the cause.

### Notify maintainers

@jtojnar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.6, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #321036: Please add: Tiling Shell (Gnome Extension)
Please add: `Tiling Shell` (Gnome Extension)

https://extensions.gnome.org/extension/7065/tiling-shell/
https://github.com/domferr/tilingshell

### PR DESCRIPTION
**Pull request by honnip**
## Description of changes

Close #321036
Close #320626
Close #274659, close #267160
Close #325325

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Neon-44** [comment]
Hey, this is pretty cool, but the creator of the original Extension said [he'd prefer if we didn't package his Extension](https://github.com/domferr/tilingshell/issues/68#issuecomment-2212487614)

Btw: How did you manage to package it? I tried to understand how, but the readme.md isn't exactly a detailed how-to guide

How do I run buildGnomeExtension.nix and how do I "feed the correct arguments into it"?

**Comment by Yash-Garg** [comment]
> Hey, this is pretty cool, but the creator of the original Extension said [he'd prefer if we didn't package his Extension](https://github.com/domferr/tilingshell/issues/68#issuecomment-2212487614)
> 
> Btw: How did you manage to package it? I tried to understand how, but the readme.md isn't exactly a detailed how-to guide
> 
> How do I run buildGnomeExtension.nix and how do I "feed the correct arguments into it"?

@Neon-44 The data is being mapped from the `extensions.json` file below, it builds all the extensions provided a valid json accordingly.

https://github.com/NixOS/nixpkgs/blob/cfa2c8198e11a7d3a773a4863ae6fb8d8e8a2cd4/pkgs/desktops/gnome/extensions/default.nix#L14-L30

**Comment by Neon-44** [comment]
wait, but the readme said that File was generated automatically and I wasn't supposed to touch that?

Whatever, got it. Will do that next time, thanks :)

**Comment by honnip** [comment]
> wait, but the readme said that File was generated automatically and I wasn't supposed to touch that?

You can the update-extensions.py to generate extensions.json and collisions.json

**Comment by honnip** [comment]
Result of `nixpkgs-review pr 325257` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>88 packages built:</summary>
  <ul>
    <li>gnomeExtensions.airpod-battery-monitor</li>
    <li>gnomeExtensions.alternate-menu-for-hplip2</li>
    <li>gnomeExtensions.autohide-battery</li>
    <li>gnomeExtensions.battery-health-charging</li>
    <li>gnomeExtensions.battery-time</li>
    <li>gnomeExtensions.bluetooth-battery-meter</li>
    <li>gnomeExtensions.bluetooth-quick-connect</li>
    <li>gnomeExtensions.bring-out-submenu-of-power-offlogout-button</li>
    <li>gnomeExtensions.control-monitor-brightness-and-volume-with-ddcutil</li>
    <li>gnomeExtensions.crazy-internet-speed-meter</li>
    <li>gnomeExtensions.custom-command-list</li>
    <li>gnomeExtensions.custom-command-toggle</li>
    <li>gnomeExtensions.custom-osd</li>
    <li>gnomeExtensions.day-progress</li>
    <li>gnomeExtensions.desktop-icons-ng-ding</li>
    <li>gnomeExtensions.dev-container-manager</li>
    <li>gnomeExtensions.disconnect-wifi</li>
    <li>gnomeExtensions.dock-unroll</li>
    <li>gnomeExtensions.downfall</li>
    <li>gnomeExtensions.easyeffects-preset-selector</li>
    <li>gnomeExtensions.emoji-copy</li>
    <li>gnomeExtensions.focus-follows-workspace</li>
    <li>gnomeExtensions.forge</li>
    <li>gnomeExtensions.fuzzy-clock-3</li>
    <li>gnomeExtensions.fw-fanctrl</li>
    <li>gnomeExtensions.gamemode-shell-extension</li>
    <li>gnomeExtensions.github-actions</li>
    <li>gnomeExtensions.gjs-osk</li>
    <li>gnomeExtensions.gmeet</li>
    <li>gnomeExtensions.gnome-hdate</li>
    <li>gnomeExtensions.gpu-supergfxctl-switch</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>gnomeExtensions.happy-appy-hotkey</li>
    <li>gnomeExtensions.highlight-focus</li>
    <li>gnomeExtensions.improved-workspace-indicator</li>
    <li>gnomeExtensions.iso-clock</li>
    <li>gnomeExtensions.just-perfection</li>
    <li>gnomeExtensions.language-switch-button</li>
    <li>gnomeExtensions.lock-keys</li>
    <li>gnomeExtensions.logo-activities</li>
    <li>gnomeExtensions.logo-menu</li>
    <li>gnomeExtensions.lomotion</li>
    <li>gnomeExtensions.luminus-desktop</li>
    <li>gnomeExtensions.luminus-shell</li>
    <li>gnomeExtensions.luminus-shell-y</li>
    <li>gnomeExtensions.move-to-next-screen</li>
    <li>gnomeExtensions.mpris-label</li>
    <li>gnomeExtensions.mythtv</li>
    <li>gnomeExtensions.network-stats</li>
    <li>gnomeExtensions.new-workspace-shortcut</li>
    <li>gnomeExtensions.nordvpn-quick-toggle</li>
    <li>gnomeExtensions.notifications-alert-on-user-menu</li>
    <li>gnomeExtensions.open-bar</li>
    <li>gnomeExtensions.openweather-refined</li>
    <li>gnomeExtensions.paperwm</li>
    <li>gnomeExtensions.persian-calendar</li>
    <li>gnomeExtensions.pin-it</li>
    <li>gnomeExtensions.ping</li>
    <li>gnomeExtensions.printers</li>
    <li>gnomeExtensions.quarter-windows</li>
    <li>gnomeExtensions.quick-settings-audio-panel</li>
    <li>gnomeExtensions.ram_sens</li>
    <li>gnomeExtensions.reading-strip</li>
    <li>gnomeExtensions.recent-items</li>
    <li>gnomeExtensions.rectangle</li>
    <li>gnomeExtensions.respect-do-not-disturb</li>
    <li>gnomeExtensions.rezmon</li>
    <li>gnomeExtensions.rounded-window-corners-reborn</li>
    <li>gnomeExtensions.run-android-emulators</li>
    <li>gnomeExtensions.server-status-indicator</li>
    <li>gnomeExtensions.show-desktop-applet</li>
    <li>gnomeExtensions.signal-shell</li>
    <li>gnomeExtensions.sticky-notes-integration</li>
    <li>gnomeExtensions.switch-workspaces-on-active-monitor</li>
    <li>gnomeExtensions.tiling-shell</li>
    <li>gnomeExtensions.toggle-headphone</li>
    <li>gnomeExtensions.top-panel-note</li>
    <li>gnomeExtensions.tophat</li>
    <li>gnomeExtensions.touch-x</li>
    <li>gnomeExtensions.trainfi</li>
    <li>gnomeExtensions.unmess</li>
    <li>gnomeExtensions.useless-gaps</li>
    <li>gnomeExtensions.vertical-workspaces</li>
    <li>gnomeExtensions.vitals</li>
    <li>gnomeExtensions.vscode-search-provider</li>
    <li>gnomeExtensions.wikiart-wallpaper</li>
    <li>gnomeExtensions.wireless-hid</li>
    <li>gnomeExtensions.xwayland-indicator</li>
  </ul>
</details>

---

<details>
<summary>added/updated/removed</summary>  
18 packages added:
gnomeExtensions.disconnect-wifi (init at 33) gnomeExtensions.dock-unroll (init at 4) gnomeExtensions.fuzzy-clock-3 (init at 2) gnomeExtensions.gamemode-shell-extension (init at 10) gnomeExtensions.iso-clock (init at 1) gnomeExtensions.language-switch-button (init at 2) gnomeExtensions.nordvpn-quick-toggle (init at 2) gnomeExtensions.pin-it (init at 12) gnomeExtensions.ram_sens (init at 3) gnomeExtensions.respect-do-not-disturb (init at 3) gnomeExtensions.rounded-window-corners-reborn (init at 2) gnomeExtensions.show-desktop-applet (init at 7) gnomeExtensions.sticky-notes-integration (init at 2) gnomeExtensions.tiling-shell (init at 18) gnomeExtensions.toggle-headphone (init at 3) gnomeExtensions.top-panel-note (init at 2) gnomeExtensions.trainfi (init at 2) gnomeExtensions.wikiart-wallpaper (init at 6)  
<br /><br />
70 packages updated:
gnomeExtensions.airpod-battery-monitor (10 → 14) gnomeExtensions.alternate-menu-for-hplip2 (35 → 36) gnomeExtensions.autohide-battery (51 → 52) gnomeExtensions.battery-health-charging (61 → 63) gnomeExtensions.battery-time (17 → 18) gnomeExtensions.bluetooth-battery-meter (14 → 18) gnomeExtensions.bluetooth-quick-connect (48 → 50) gnomeExtensions.bring-out-submenu-of-power-offlogout-button (54 → 56) gnomeExtensions.control-monitor-brightness-and-volume-with-ddcutil (5 → 7) gnomeExtensions.crazy-internet-speed-meter (10 → 13) gnomeExtensions.custom-command-list (1 → 3) gnomeExtensions.custom-command-toggle (3 → 6) gnomeExtensions.custom-osd (26 → 28) gnomeExtensions.day-progress (9 → 11) gnomeExtensions.desktop-icons-ng-ding (68 → 69) gnomeExtensions.dev-container-manager (23 → 27) gnomeExtensions.downfall (37 → 38) gnomeExtensions.easyeffects-preset-selector (21 → 22) gnomeExtensions.emoji-copy (21 → 23) gnomeExtensions.focus-follows-workspace (9 → 10) gnomeExtensions.forge (80 → 83) gnomeExtensions.fw-fanctrl (4 → 6) gnomeExtensions.github-actions (142 → 146) gnomeExtensions.gjs-osk (10 → 18) gnomeExtensions.gmeet (10 → 13) gnomeExtensions.gnome-hdate (28 → 29) gnomeExtensions.gpu-supergfxctl-switch (3 → 8) gnomeExtensions.gtk4-desktop-icons-ng-ding (79 → 81) gnomeExtensions.happy-appy-hotkey (8 → 9) gnomeExtensions.highlight-focus (11 → 12) gnomeExtensions.improved-workspace-indicator (20 → 23) gnomeExtensions.just-perfection (28 → 29) gnomeExtensions.lock-keys (57 → 58) gnomeExtensions.logo-activities (11 → 16) gnomeExtensions.logo-menu (30 → 32) gnomeExtensions.lomotion (2 → 3) gnomeExtensions.luminus-desktop (7 → 10) gnomeExtensions.luminus-shell (6 → 8) gnomeExtensions.luminus-shell-y (6 → 9) gnomeExtensions.move-to-next-screen (1 → 2) gnomeExtensions.mpris-label (30 → 32) gnomeExtensions.mythtv (16 → 17) gnomeExtensions.network-stats (20 → 24) gnomeExtensions.new-workspace-shortcut (17 → 19) gnomeExtensions.notifications-alert-on-user-menu (50 → 51) gnomeExtensions.open-bar (30 → 36) gnomeExtensions.openweather-refined (14 → 17) gnomeExtensions.paperwm (112 → 118) gnomeExtensions.persian-calendar (112 → 114) gnomeExtensions.ping (3 → 4) gnomeExtensions.printers (25 → 26) gnomeExtensions.quarter-windows (11 → 12) gnomeExtensions.quick-settings-audio-panel (53 → 57) gnomeExtensions.reading-strip (30 → 32) gnomeExtensions.recent-items (27 → 23) gnomeExtensions.rectangle (18 → 21) gnomeExtensions.rezmon (11 → 16) gnomeExtensions.run-android-emulators (2 → 3) gnomeExtensions.server-status-indicator (23 → 26) gnomeExtensions.signal-shell (7 → 10) gnomeExtensions.switch-workspaces-on-active-monitor (15 → 20) gnome-shell-extension-tophat gnomeExtensions.touch-x (7 → 9) gnomeExtensions.unmess (8 → 9) gnomeExtensions.useless-gaps (16 → 17) gnomeExtensions.vertical-workspaces (62 → 65) gnomeExtensions.vitals (67 → 68) gnomeExtensions.vscode-search-provider (7 → 10) gnomeExtensions.wireless-hid (17 → 18) gnomeExtensions.xwayland-indicator (2 → 3)
<br /><br />
1 package removed:
gnome-shell-extension-admission (†10)
</details>

**Comment by honnip** [comment]
updated again

**Pull request merged**
