### PR TITLE
ghc: add 8.8.3 (copied from 8.8.2)

### PR DESCRIPTION
**Pull request by ggreif**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build haskell.compiler.ghc883

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build haskell.compiler.ghc883

**Review by cdepillabout — APPROVED** [review]
@ggreif LGTM.

Also pinging @peti, @Ericson2314, and @matthewbauer, since I think they do work on the GHC derivations.

**Comment by ggreif** [comment]
Remains to be fixed:
- [ ] squash
- [ ] figure out CI failure

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build haskell.compiler.ghc883

@ggreif The CI failure is probably from some other problem in `haskell-updates`.  It is likely this PR didn't cause it, so you can probably ignore it.

**Pull request merged**
