### PR TITLE
libobjc: 1.8.1 -> 1.9 -> 2.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Builds on #60295, moving to 2.0!

I'm not sure if we want to stick with 1.x or not, hence the two PR's.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
@GrahamcOfBorg build gnustep

**Comment by ajs124** [comment]
2.0 is already on master since #62464. Which coincidentally made SoGo segfault for us after the 19.09 upgrade.

**Comment by dtzWill** [comment]
As mentioned, seems already included.  Thanks, sorry for the stall! :)

**Comment by ajs124** [comment]
I'm honestly not sure bumping was the right thing to do. As noted in #79175, it makes at least some software segfault. I'm not sure anyone else uses libobjc for anything else, so I actually revert the bump in there.

**Pull request closed without merging**
