### PR TITLE
Mono: add vulnerabilities

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

See #39282 for discussion

/cc @viric @thoughtpolice @obadz @vrthra

### CODE REVIEW

**Comment by Mic92** [comment]
see also https://github.com/NixOS/nixpkgs/pull/36711

**Comment by Mic92** [comment]
Updating mono will break some stuff unfortunately.

**Comment by matthewbauer** [comment]
Ok dropped the last commit. Still want to put in knownVulnerabilities

**Comment by Mic92** [comment]
I also tried updating mono last weekend, but it is still wip:
https://github.com/Mic92/nixpkgs/commit/54d32e66be87e5adcec69c6d8fb2c20ca72451a6

**Comment by Mic92** [comment]
In future we should adding so many different versions of mono.

**Comment by ShalokShalom** [comment]
@Mic92  You mean avoiding?

**Comment by Mic92** [comment]
@ShalokShalom yes. updated.

**Pull request merged**
