### PR TITLE
specialisation: limit the allowed characters in specialisation names

### PR DESCRIPTION
**Pull request by r-vdp**
## Description of changes

Since the systemd boot counting PR was merged, dashes in specialisation names cause issues when installing the boot loader entries, since dashes are also used as separator for the different components of the file name of the boot loader entries on disk.

The assertion avoids this footgun which is pretty annoying to recover from.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by r-vdp** [comment]
@ofBorg test nixosTests.nixos-rebuild-specialisations

**Review by flokli — APPROVED** [review]

**Review by K900 — APPROVED** [review]
SGTM

**Comment by K900** [comment]
This broke the ACME test:

> Invalid specialisation names: caddy-change-acme-conf, concurrency-limit, httpd-change-acme-conf, httpd-remove-alias, lego-server, nginx-change-acme-conf, nginx-remove-alias, ocsp-stapling, slow-startup

**Comment by flokli** [comment]
> dashes in specialisation names cause issues when installing the boot loader entries

Looks like we might want to convert these to underscores.

**Comment by vcunat** [comment]
`nixos-unstable` is blocked because of this.  It can't even evaluate, e.g. `nix eval -f. nixosTests.switchTest.outPath`

**Comment by PedroHLC** [comment]
It's interesting this PR, newer than #333857, while having a much more broken solution, got merged first. And even almost hit nixos-unstable.
What went wrong? No research for duplicates before opening it? Wrong/Unrelated committers tagged for reviewing (here and there)? It would be convenient to understand and avoid this in the future.

**Comment by flokli** [comment]
> It's interesting this PR, newer than #333857, while having a broken solution, got merged first. And even almost hit nixos-unstable. What went wrong? No research for duplicates before opening it? Wrong/Unrelated committers tagged for reviewing (here and/or there)? It would be convenient to understand and avoid this in the future.
> 
> Release notes would have been cool. Add a test for "rebuilding-specialisations" too.

I already spoke with @JulienMalka in private and apologized for being a bit too trigger-happy here. Didn't expect this to cause a lot of regressions, and I was wrong. Sorry.

**Pull request merged**
