### PR TITLE
1password-gui: 8.10.40 -> 8.10.46 (beta 8.10.44-21 -> 8.10.48-17)

### PR DESCRIPTION
**Pull request by kittydoor**
Updated 1password to the latest versions of stable and beta based on information from [repology](https://repology.org/project/1password/information).

This is my first contribution to nix, and I am just beginning to take my steps into the world of nix, so I might have gone a very manual path with this or perhaps made some mistakes. Please let me know how to proceed if there are any further steps :)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kittydoor** [comment]
@SebTM you had a comment on issue #338781 regarding a follow up, I assume you got busy so I prepared this PR. I hope it's helpful :)

**Comment by SebTM** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346483`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>_1password-gui</li>
    <li>_1password-gui-beta</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]
Thanks for your contribution - sorry for the delay on my side 🙏🏻 
LGTM - tested it quickly against unstable 👍🏻

**Comment by kittydoor** [comment]
@SebTM thanks a lot! I see now 8.10.48 is out, and I would like to ensure NixOS always has up-to-date versions of 1password. Would you be open to reviewing a contribution for integrating with automatic updates better? If so I'll try to dedicate some time to this :)

**Comment by SebTM** [comment]
Also there is #350364 for review after I merged this one yesterday 🙏🏻

**Pull request merged**
