### PR TITLE
ecl: refactor

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
cleanup with no indirections

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by spacefrogg — APPROVED** [review]
LGTM

**Comment by spacefrogg** [comment]
Result of `nixpkgs-review pr 151542` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ecl_16_1_2</li>
  </ul>
</details>

**Comment by sternenseemann** [comment]
This PR should have seen an approval from the maintainer, @7c6f434c, before merging, since it quite obviously removed a workflow to automatically update ECL used by them.

I want to urge everyone doing “cleanups” in nixpkgs to ask themselves if the given change is *really* necessary and if it improves things. The `ecl` derivation could've made to conform with the `pname`/`version` scheme without regressing this workflow at all.

**Comment by Stunkymonkey** [comment]
in #103997 it was stated to remove this update-method used by 7c6f434c. Therefore in #151363 it was removed.
He is not actively monitoring outdated packages, and only takes action if something is broken.

**Comment by 7c6f434c** [comment]
Yes, I have confirmed in that discussion that now that I do not do frequent mass-updates the annoyance of manual update is rather small.

**Pull request merged**
