### PR TITLE
Cross nixos aarch64 2018 08 05

### PR DESCRIPTION
**Pull request by MarcFontaine**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danbst** [comment]
why is `switch-to-configuration` change reverted?

**Comment by samueldr** [comment]
This looks like an accidental use of the "open PR" function from the branch of another user's fork.

I'll close this, assuming so. If I'm wrong, re-open.

For the record, [I've been gathering fixes for cross-compiling the image](https://github.com/samueldr/cross-system).

**Comment by danbst** [comment]
@samueldr well at least raspberrypi-wireless was an issue I faced, so a fix for that would be awesome.

**Comment by samueldr** [comment]
I *know* for a fact that this PR is old content from @ElvishJerricco. Maybe he could open a PR with the change? Or alternatively you could, @danbst?

I would, but prefer not doing a PR I have not tested personally. Though here the change looks self-contained and safe.

**Pull request closed without merging**
