### PR TITLE
adapt semantics of autopatchelfHook for single files

### LINKED ISSUE #166086: breitbandmessung build fails due to missing command: autoPatchelfFile
### Describe the bug
Installing `breitbandmessung` fails due to missing command `autoPatchelfFile`:
```
$ sudo nixos-rebuild switch
building the system configuration...
error: builder for '/nix/store/bansdpcfz1p3yzrc2y2n61iklbc71z1h-breitbandmessung-3.1.0.drv' failed with exit code 127;
       last 8 log lines:
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > no Makefile, doing nothing
       > glibPreInstallPhase
       > installing
       > /nix/store/lkk0hf9h4x85mb4lrsf2sh25qm2i4n18-stdenv-linux/setup: line 1360: autoPatchelfFile: command not found
       For full logs, run 'nix log /nix/store/bansdpcfz1p3yzrc2y2n61iklbc71z1h-breitbandmessung-3.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/gvkryrkd675vr27y7ypdh8y39gd6nsxq-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lmv2zm0nwpk2n28di81kpfqag9rk86cx-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bk9nv989l6c7rbwzrcmfp9aha6691447-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z1y6yszbvwqbxn0j4j5alh20y71031hp-etc.drv' failed to build
error: error: 1 dependencies of derivation '/nix/store/91kzm0fr5kqjpfrfr3k02kgph4qh3x7a-nixos-system-home-pc-22.05.20220323.1d08ea2.drv' failed to build
```

### Steps To Reproduce
Install `breitbandmessung`, e.g. via `nix run "nixpkgs#breitbandmessung"`.

### Expected behavior
App should build, install & run without errors.

### Notify maintainers
@B4dM4n

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0, NixOS, 22.05 (Quokka), 22.05.20220323.1d08ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - nixpkgs: `/nix/store/hsff9pi1qinxljahr833z0xivr1apx27-source`
```

### PR DESCRIPTION
**Pull request by layus**
###### Description of changes

This is a mass rebuild change for binary packages, albeit it will end up in a no-op (wishing for ca-derivations here).

Follow up of https://github.com/NixOS/nixpkgs/pull/149731. I think the fix is sufficiently small and innocuous, but could help a second look.

Fixes #166086.

/cc @Mic92 @aszlig @Ericson2314 @Artturin as a followup of the initial rewrite.
/cc @felschr for your opinion, and for testing if it indeed works ;-).

### CODE REVIEW

**Review by aszlig — APPROVED** [review]

**Comment by aszlig** [comment]
> This is a mass rebuild change for binary packages

... which IMHO is not a big issue since due to their pre-compiled nature they don't need to be compiled :-)

**Comment by layus** [comment]
> ... which IMHO is not a big issue since due to their pre-compiled nature no time is wasted with compiling :-)

Sadly, sometimes they are not marked as preferLocalBuild and the NoHyDrA option :-).

**Review by felschr — APPROVED** [review]
Change looks good for `breitbandmessung`.

**Review by FRidh — COMMENTED** [review]
I think the change is good, however, I would put a comment there describing why this is needed as, at least to me, it isn't directly apparent when reading the code. Something like "returning the path itself is needed in case it's a file instead of a folder".

**Comment by layus** [comment]
@FRidh Updated with more comments. I could not resist the urge to generalize the code. Now paths can be folders and files. Both are handled transparently by a single new branch in the whole code. Could break code that used to pass files and relied on the fact that they were _ignored_. The fix is to not pass it anymore in that case.

**Comment by RaitoBezarius** [comment]
Can we help get this merged?

**Comment by layus** [comment]
@RaitoBezarius @mmilata Thanks for reminding me this PR. I have rebased and retargeted it in https://github.com/NixOS/nixpkgs/pull/234994.

**Pull request closed without merging**
