### PR TITLE
gitlab-container-registry: init at v3.66.0-gitlab

### PR DESCRIPTION
**Pull request by xanderio**
###### Description of changes

With version 15.8 GitLab deprecates the use of an "external" container registry (in our case `pkgs.docker-distribution`) as mentioned in #212427. The external registry is replaced with a fork that contains extra functionality that GitLab uses internally. See https://gitlab.com/gitlab-org/container-registry/-/blob/master/docs-gitlab/README.md

This PR only add the new package and doesn't touch the NixOS service.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xanderio** [comment]
Result of `nixpkgs-review pr 213552` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitlab-container-registry</li>
  </ul>
</details>

**Comment by dasJ** [comment]
Wouldn't it also make sense to add a `services.dockerRegistry.package` option so this package is easier to use?

**Comment by xanderio** [comment]
I don't know if it is a good idea to continue using `services.dockerRegistry` for this package, as GitLab has already removed the registry mirroring aspect from it's fork. In the future the two packages will probably drift further apart from one another.

**Comment by xanderio** [comment]
And i did an upsi rebasing this, closing this pr and reopening.

**Pull request closed without merging**
