### PR TITLE
llvmPackages: 7.1.0 -> 9.0.1

### PR DESCRIPTION
**Pull request by DieGoldeneEnte**
###### Motivation for this change
As pointed out in #84096 llvmPackages still points to llvm 7.  This commit changes llvmPackages to llvm 9. I chose not to use llvm 10, since it was just released.
Since boost16x is boost 1.69 using clang >7 should work in most cases (<1.69 needs clang <=7).

**This still needs to be tested on darwin!** If you can tell me how to test without darwin machine, I'll compile/fix myself.
On linux all packages building before these changes are still building afterwards.
###### Things done
* `coreclr` now uses clang found in passed llvmPackages, instead of separate argument to ensure all llvm-tools use the same version
* `boost ` has extra assert to catch compiling boost <1.69 with clang >=8 early on. This combination is not possible, because clang removed a feature.
* fixed `irods` and `coreclr` to llvm 7, since both can not be compiled with newer clang (irods needs boost <1.69 and coreclr has problems with clangs internal assembler after version 8)

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by LnL7 — CHANGES_REQUESTED** [review]
This needs more work than just updating, since this is a major change for the darwin ecosystem (similar to bumping gcc for linux).

That said, I have already been preparing changes for the update, these are the initial changes I've made so far https://github.com/LnL7/nixpkgs/commits/llvm-9-update. Last week I also started an evaluation for this to get an overview of the regressions https://hydra.nixos.org/eval/1579054?compare=1575607#tabs-unfinished. The builds have also been delayed for a bit by the 20.03 release. Once that's finished we can asses what should be fixed along with the update before it can be merged.

It's probably a bit early at this point but If you'd like to help in with the effort most of these failures can most likely be reproduced on linux, like some of the fixes you've made already.

**Comment by DieGoldeneEnte** [comment]
@LnL7 I knew this is a big change for darwin, although I don't know the darwin specific packages. I intended to use this PR to pool the effort. I think it would be more useful if I close this PR and you open a [WIP] PR from your branch?
I would just split the change to coreclr and boost into two independent PRs and contribute fixes to your branch.

**Comment by LnL7** [comment]
@DieGoldeneEnte See #85151.

**Comment by DieGoldeneEnte** [comment]
I created #85155 and #85156 for coreclr and boost.
Once the `coreclr` change is merged, I will open a PR to your branch to pin irods and coreclr to llvmPackages_7.

**Pull request closed without merging**
