### PR TITLE
nixos/module/deluge: fix directory ownership.

### PR DESCRIPTION
**Pull request by gleber**
Fixes nixos/tests/deluge.nix test.

The pre-script was failing with 'Permission denied' errors. I have tracked it
down to the unusual permissions on /var/lib/deluge/.config directory tree.
Additionally errors of form "Detected unsafe path transition xxx → yyy during
canonicalization of zzz" were printed by systemd. This makes it work.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Infinisil @domenkozar @ebzzry @davidtwco

### CODE REVIEW

**Comment by gleber** [comment]
@GrahamcOfBorg test deluge

**Review by flokli — CHANGES_REQUESTED** [review]
The change to use tmpfiles.d to manage the directory layout declaratively was intentional.

The error message looks more as if there are some symlinks involved / cf https://github.com/systemd/systemd/blob/master/src/tmpfiles/tmpfiles.c#L883

Can you elaborate on how your filesystem layout looks there?

**Comment by flokli** [comment]
also cc @aanderse

**Comment by aanderse** [comment]
@gleber please paste your `deluge` configuration.

**Comment by gleber** [comment]
@flokli Yes, I suspected that :) The issue is that it does not work for me and the appropriate test in the repo fails on master. I am happy to get it fixed with using `tmpfiles.d`, but my patience ran out when trying to figure out what is going wrong in the systemd land.

@aanderse It is a bit messy, hard to get to get it shared. But the issue is reproducible with `nix-build nixos/tests/deluge.nix`. This PR fixes this test to pass.

I am happy to get hints how to fix it with `tmpfiles.d` mechanisms and update the PR.

**Comment by gleber** [comment]
Closing in favor of #67888

**Pull request closed without merging**
