### PR TITLE
haskell.compiler: port all make/native-bignum GHCs to common expr

### PR DESCRIPTION
**Pull request by sternenseemann**
The common expression is a little messy to avoid rebuilds. It can be cleaned up in a second step.

`9.4.8.fixme.nix` is used temporarily so that git's rename detection gets where common-make-native-bignum.nix is coming from.

8.10.7 keeps its expression since it uses integer-simple which changes the expression's interface. This is unfortunately very annoying to reflect in a common expression.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sternenseemann** [comment]
cc @AlexandreTunstall Hopefully with the file naming shenanigans I've done, it'll be easy to rebase changes onto this. Should make our lives a little easier…

**Comment by AlexandreTunstall** [comment]
My workflow so far has been to `git diff` the changes and then `patch` them onto all the other versions, but this will indeed make changes much less tedious to make, especially when there are several for different commits and they need to be `git add -p` for every file). I'm looking forward to rebasing.

It's a bit unfortunate that this still had to be done despite the deprecation of Make-based builds, but who knows how long Nixpkgs will continue to have these not-so-new versions of GHC.

**Comment by sternenseemann** [comment]
> I'm looking forward to rebasing.

I still need to figure out how this can be made to work properly. Maybe we need to delay renaming `9.4.8.fixme.nix` further, I ran into some trouble earlier.

**Comment by sternenseemann** [comment]
@AlexandreTunstall Indeed, without renaming the file right away, rebasing works fine, so I'll keep it like this until we've merged all outstanding GHC changes.

**Pull request merged**
