### PR TITLE
chromium: 55.0.2883.87 -> 56.0.2924.87 [nixos-stable]

### PR DESCRIPTION
**Pull request by bendlas**
stable update, security fixes

### CODE REVIEW

**Comment by grahamc** [comment]
Thank you! Missed this before :/

**Comment by obadz** [comment]
Looks like that's making the chromium test fail and holding release-16.09… http://hydra.nixos.org/build/47936140/nixlog/1

**Comment by grahamc** [comment]
Restarting the failing test seems to have fixed it. Thanks for the heads up!

**Comment by grahamc** [comment]
Ugh, or not. I thought it had.

**Comment by obadz** [comment]
Are there security updates in this patch that are serious enough that we shouldn't revert it?

**Comment by bendlas** [comment]
I just checked the master log for intermittent commits, that I might have missed. There don't seem to be for chromium. Has something changed in the test suite, that we need to pull in?

The latest hydra build seems to have been deleted from the binary cache. I suppose that's because the it was manually restarted? http://hydra.nixos.org/build/47936180

> Are there security updates in this patch that are serious enough that we shouldn't revert it?
Definitely! https://chromereleases.googleblog.com/2017/01/stable-channel-update-for-desktop.html

**Comment by bendlas** [comment]
There is a commit to the testsuite, that has not yet been applied to stable: cd10e3c4ffa3d6c729aab8778bf6027415025c44

I pushed it to the stable branch, that this PR has been created from

**Comment by grahamc** [comment]
👍 ⚡️ nice work, @bendlas, thank you! /cc @aszlig

**Comment by obadz** [comment]
Nice find, confirmed that it fixed the problem & pushed.

**Comment by obadz** [comment]
(in e76c8ac)

**Pull request merged**
