### PR TITLE
python3Packages.motioneye-client: init at 0.3.6

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python library for motionEye

https://github.com/dermotduffy/motioneye-client

This is a new Home Assistant dependency (> 2021.5.x)

ToDo:

- [x] Update component-packages
- [x] Enable tests

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 121856` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.motioneye-client</li>
    <li>python39Packages.motioneye-client</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121856` at 294a2a99 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.motioneye-client</li>
    <li>python39Packages.motioneye-client</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 121856` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.motioneye-client</li>
    <li>python39Packages.motioneye-client</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
I have been eyeying this one, but sadly motioneye is still stuck on python2.7.

https://github.com/ccrisan/motioneye/blob/795616d15caa24fd35f1d41b37668086e1ce4049/setup.py#L58-L59

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
