### PR TITLE
swiProlog: 9.2.5 -> 9.2.6, update dependencies

### PR DESCRIPTION
**Pull request by matko**
## Description of changes
This updates SWI-Prolog to the latest upstream stable version, 9.2.6. [Changelog](https://www.swi-prolog.org/ChangeLog?branch=stable&from=9.2.5&to=9.2.6)

Additionally, this PR modifies the dependencies to pass SWI-Prolog's self test, which is not passing with the packaging currently in nixpkgs. A special predicate, `check_installation/0`, can be run on a SWI-Prolog install to make it report issues in the installation. This self-test is now all green for `swiPrologWithGui`, and only reports that the gui elements are missing in `swiProlog`.

Changes:
- Import SWI-Prolog 9.2.6
- switch to ninja for building (same as upstream)
- add gperftools for tcmalloc
- include python dependency
- move extra pack install option directory to another name which doesn't clash with standard SWI-Prolog locations
- remove `extraLibraries`, which appears to be a hacky way to inject dependencies like java and odbc. In my view this is fully replaced by the next point.
- add several `withX` options to turn dependencies on or off. The complete list of 'with' variables is now
  - withDb
  - withGui
  - withJava
  - withNativeCompiler (to include gcc and g++ as runtime dependenciess for pack install)
  - withOdbc
  - withPcre
  - withPython
  - withYaml
 
All are true by default, except withGui, which defaults to false.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matko** [comment]
Had to do some force pushes for two issues
- the SWI-Prolog changelog showed that a feature was backported that allows us to cut the explicit dependency to a compiler. I integrated this.
- Subsequently, I had to change this integration to do the right thing on darwin (select clang/clang++ instead of gcc/g++)

**Comment by meditans** [comment]
Hey @matko! Thanks for the changes, LGTM for almost all of them but I'd like you to consider if you would be ok with leaving `extraLibraries` in. We can't know in advance all the dependencies users will want to include, and restricting ourselves to a pre-made list of options will force them to fork the derivation instead of just tweaking the variable, which increases friction.

Case in point, in my system I have:
```
(swiProlog.override {
  extraLibraries = [ emacs29 freetype fontconfig jdk ];
})
```
the emacs stuff is needed for the sweeprolog integration, and jdk because I wanted to do a clojure experiment. The point is that we can't know, and leaving it in is relatively harmless. What do you think?

**Comment by matko** [comment]
Hey @meditans , thanks for your review!
I'm also using sweep, and I never had to add emacs to the dependencies to do so. Why is this necessary? And if it is necessary, shouldn't we have a `withEmacs`?
The other elements in your extraLibraries are now present in the various withXyz flags.

I won't die on this hill but having an attribute to inject arbitrary dependencies does not seem like the right thing to do at all.  Especially because there already is a mechanism for that. If you want to do arbitrary dependency changes you can always do something like
`swiProlog.overrideAttrs { buildInputs = swiProlog.buildInputs ++ [cowsay]; }`.

The problem I see is that it means that apparently there's features in SWI-Prolog that we just won't let people use unless they know the magic set of dependencies that turns them on. In my opinion, one of reasons for packaging software is so that they don't have to know this.

> The point is that we can't know
But surely we can? The set of dependencies that the SWI-Prolog build could potentially use is limited. We know it is not actually going to use cowsay even if we provide it as an extra dependency. So it's just a matter of making sure there's options for all the dependencies it could use.

**Comment by meditans** [comment]
My pleasure @matko. Your reasoning it fine with me, I like the new flags as they document better the intent, I was originally proposing to leave in `extraLibraries` to help users that need a different library and are not aware of the `buildInputs` trick you mentioned.

I don't recall the exact problem for which I needed emacs to be included there, maybe it's not needed anymore? I will check at some point when I return home.

In any case, I just wanted to offer a perspective of why that `extraLibraries` is there, I'm not dying on this hill either :joy:, you can merge either way. Also, you could add yourself to the maintainers of the package if you want, it could be nice if others could ask you for reviews!

**Review by meditans — APPROVED** [review]

**Comment by matko** [comment]
I spent some time looking over the sweep situation. What I understand is that the sweep module that is included in the swipl build will compile just fine without an emacs present, because it includes its own emacs module header and doesn't need to link to emacs.

To my understanding, emacs modules do not actually ever need a runtime dependency to emacs. Instead, emacs injects its environment into the module at load time. This allows compiled dynamic modules for emacs to be pretty flexible about how they are built and who loads them. Lucky us :)

I think it's probably fine to not even include emacs as an optional dependency, given the header file is already there. I would appreciate a confirmation that it works for you without the explicit emacs dependency though, if you're able.

Instead of outright removing the `extraLibraries` attribute, i've now made it so that using it gives you an error with a helpful message to tell you about the with* options and overrideAttrs.

I'll add myself as a maintainer :)

**Comment by matko** [comment]
I have various other fixes I'd like to integrate in this package, but I am unsure if I should just keep pushing them to this PR or wait until this is merged, then open a new PR.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 329891` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>ape</li>
    <li>apeClex</li>
    <li>pakcs</li>
    <li>swiProlog</li>
    <li>swiPrologWithGui</li>
  </ul>
</details>

**Pull request merged**
