### PR TITLE
chromium: 62.0.3202.94 -> 63.0.3239.84

### PR DESCRIPTION
**Pull request by YorikSar**
New stable release with bunch of security fixes and other changes [0]

Also:
* remove patch for dev already landed upstream
* remove patches specific to version 62
* dev is broken again, need to investigate failures

[0] https://chromereleases.googleblog.com/2017/12/stable-channel-update-for-desktop.html

###### Motivation for this change

Stable release update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by YorikSar** [comment]
@bendlas Can you take a look?

**Comment by vcunat** [comment]
More patches can be removed, I suppose?

> trace: WARNING: chromium: stable version 63.0.3239.84 is newer than a patchset bounded at 63. You can safely delete it.

**Comment by YorikSar** [comment]
@vcunat I've removed all leftover version checks that are always true now.

**Comment by vcunat** [comment]
Well, that version built OK for me and during a few minutes of usage found no breakage. (Now I'd have to rebuild.)

**Comment by bendlas** [comment]
Thanks for getting this done and the feedback round, respectively. I'll port it to stable ...

**Comment by copumpkin** [comment]
> dev is broken again, need to investigate failures

Anyone know what's wrong with it?

**Comment by YorikSar** [comment]
@copumpkin Last time it seemed to be that we have snappy library and chromium building with different C++11 ABIs, but I didn't dig further yet.

**Pull request merged**
