### PR TITLE
hammer: bump revision and fix build

### PR DESCRIPTION
**Pull request by azahi**
###### Description of changes

Fix failing build (https://hydra.nixos.org/build/177105199)

ZHF: #172160

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by azahi** [comment]
Result of `nixpkgs-review pr 173880` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hammer</li>
  </ul>
</details>

**Comment by risicle** [comment]
Surely we should update its stated `version`? Current practise appears to be `unstable-yyyy-mm-dd` with the date of the most recent commit.

**Comment by risicle** [comment]
Also it looks like development might have moved to https://gitlab.special-circumstanc.es/hammer/hammer

**Comment by risicle** [comment]
Using

```
  src = fetchzip {
    url = "https://gitlab.special-circumstanc.es/hammer/hammer/-/archive/nightly_20220505/hammer-nightly_20220505.zip";
    sha256 = "0pgkykbqfsj1n96pc67hq65ysi4qgmkl7iwp6pjf26cwgi963in4";
  };
```

it also builds happily for me on macos 10.15.

**Comment by azahi** [comment]
@risicle Done. I've also added myself as a maintainer since there was none.

**Comment by risicle** [comment]
@ofborg eval
@ofborg build

**Comment by risicle** [comment]
I'm getting a mismatched hash.

```
hash mismatch in fixed-output derivation '/nix/store/zm981g2h7z5a3mgcg8wwsy05g4s4gs8f-source':
  wanted: sha256:15wcynz8pgpz23icv184wsbmlgah50ld3c3ci5xbs5qys7qfc3z1
  got:    sha256:0pgkykbqfsj1n96pc67hq65ysi4qgmkl7iwp6pjf26cwgi963in4
```

typo or might upstream be modifying tags etc.?

**Comment by azahi** [comment]
@risicle Sorry, my bad. Should work now tho.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15, nixos x86_64 & aarch64

**Pull request merged**
