### PR TITLE
python3Packages.ciso8601: 2.1.3 -> 2.2.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2.2.0

Change log: https://github.com/closeio/ciso8601/blob/master/CHANGELOG.md#version-220

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 133325` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python38Packages.aioinflux</li>
    <li>python38Packages.ciso8601</li>
    <li>python38Packages.dwdwfsapi</li>
    <li>python38Packages.influxdb-client</li>
    <li>python39Packages.aioinflux</li>
    <li>python39Packages.ciso8601</li>
    <li>python39Packages.dwdwfsapi</li>
    <li>python39Packages.influxdb-client</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133325` at 2ab98e8d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>python38Packages.aioinflux</li>
    <li>python38Packages.ciso8601</li>
    <li>python38Packages.dwdwfsapi</li>
    <li>python38Packages.influxdb-client</li>
    <li>python39Packages.aioinflux</li>
    <li>python39Packages.ciso8601</li>
    <li>python39Packages.dwdwfsapi</li>
    <li>python39Packages.influxdb-client</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by Mic92** [comment]
home-assistant is not happy about this:

```
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/s1691654/.cache/nixpkgs-review/pr-133325-1/build.nix
error: builder for '/nix/store/9y34iprirm9gg9b87ri14rh901x661nz-homeassistant-2021.8.6.drv' failed with exit code 1;
       last 10 log lines:
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./homeassistant-2021.8.6-py3-none-any.whl
       > Requirement already satisfied: astral==2.2 in /nix/store/sckklafrlhv4vj6k8xcwcc5v8ksly30v-python3.9-astral-2.2/lib/python3.9/site-packages (from homeassistant==2021.8.6) (2.2)
       > Requirement already satisfied: async-timeout==3.0.1 in /nix/store/yh54n2i71jfyknpic4fddpxyp6klra7b-python3.9-async-timeout-3.0.1/lib/python3.9/site-packages (from homeassistant==2021
.8.6) (3.0.1)
       > Requirement already satisfied: jinja2==3.0.1 in /nix/store/74bvl18wb5qqbg8qf6qwy8ffsvjlmva7-python3.9-Jinja2-3.0.1/lib/python3.9/site-packages (from homeassistant==2021.8.6) (3.0.1)
       > ERROR: Could not find a version that satisfies the requirement ciso8601==2.1.3 (from homeassistant) (from versions: none)
       > ERROR: No matching distribution found for ciso8601==2.1.3
       For full logs, run 'nix log /nix/store/9y34iprirm9gg9b87ri14rh901x661nz-homeassistant-2021.8.6.drv'.
error: 1 dependencies of derivation '/nix/store/3vnng7szwppm7izdg6zppsmabq862iyc-review-shell.drv' failed to build
```

**Comment by fabaff** [comment]
Part of #135832

**Comment by mweinelt** [comment]
Add an override for home-assistant if it would otherwise break it.

**Comment by fabaff** [comment]
https://github.com/home-assistant/core/pull/56678

**Comment by fabaff** [comment]
Cherry-picked into [`home-assistant`](https://github.com/NixOS/nixpkgs/tree/home-assistant).

**Pull request closed without merging**
