### PR TITLE
makeBinaryWrapper: fix cross-compilation and add test

### LINKED ISSUE #175045: makeBinaryWrapper produces binaries for build instead of host
making a pr fixing cross compilation for some things and found this
```
$ file .xdt-csource-wrapped
.xdt-csource-wrapped: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /nix/store/5gg0aph41cj424z5glbibq5381943his-glibc-aarch64-unknown-linux-gnu-2.34-210/lib/ld-linux-aarch64.so.1, for GNU/Linux 2.6.32, not stripped
$ file xdt-csource
xdt-csource: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped
```

```
nix-repl> pkgsCross.aarch64-multiplatform.stdenv.cc
«derivation /nix/store/hdsxwz94k248f1wmc2npfz8s2qq6c65p-aarch64-unknown-linux-gnu-stage-final-gcc-debug-wrapper-9.3.0.drv»

nix-repl> stdenv.cc
«derivation /nix/store/bl5y9zix1vsdiq6q0lxypggsahb65np5-gcc-wrapper-11.3.0.drv»
```

https://github.com/NixOS/nixpkgs/blob/dbd004ea9bee830402aa410c6b8a0a493efa454b/pkgs/build-support/setup-hooks/make-binary-wrapper/default.nix#L17

@ncfavier @bergkvist @milahu

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes https://github.com/NixOS/nixpkgs/issues/175045

### CODE REVIEW

**Review by sternenseemann — APPROVED** [review]
Not sure what's going on on darwin…

**Comment by ncfavier** [comment]
I was wondering whether `readelf` would work on darwin, but of course not since the produced executables are Mach-O... Maybe we can disable the cross test on darwin?

**Comment by sternenseemann** [comment]
iirc ofborg merges into master first, so try rebasing on master

**Comment by ncfavier** [comment]
Gah, sorry about that.

**Comment by ncfavier** [comment]
So, on `x86_64-darwin` the generated wrapper is a `Mach-O 64-bit x86_64 executable`, and on `aarch64-darwin` it's a `Mach-O 64-bit arm64 executable` (according to `file`)... from which I gather that cross-compilation just isn't working on darwin builders?

Also the non-cross tests apparently fail on `aarch64-darwin`, probably because we're compiling the envcheck program with gcc. Let's try making it a shell script instead.

**Comment by ncfavier** [comment]
OK, disabled the cross test on darwin, things look good now.

**Comment by Mindavi** [comment]
I verified that this works by applying it to the tip of this PR: https://github.com/NixOS/nixpkgs/pull/175998 and checking if the generated binary now is aarch64 again. All good!

**Review by Mindavi — APPROVED** [review]

**Pull request merged**
