### PR TITLE
pythonPackages.mido: init at 1.2.9

### PR DESCRIPTION
**Pull request by mweinelt**
##### Motivation for this change

I got a request for packaging the mido from @piegamesde.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The eval-nixpkgs-tarball failure seems unrelated.

> creating file '/nix/store/603m6dp953vlnl7m3vk0y5lwr1jvqakj-packet-spot-eval-5/pkgs/desktops/gnome-2/platform/libbonobo/default.nix': No space left on device

**Comment by mweinelt** [comment]
@GrahamcOfBorg eval python3Packages.mdio

**Comment by mweinelt** [comment]
@GrahamcOfBorg eval

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 91317 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>7 packages built:</summary><br>- python27Packages.rtmidi-python<br>- python37Packages.mido<br>- python37Packages.python-rtmidi<br>- python37Packages.rtmidi-python<br>- python38Packages.mido<br>- python38Packages.python-rtmidi<br>- python38Packages.rtmidi-python</details>

**Pull request merged**
