### PR TITLE
wofi: fixes bad patch hash

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

Fixes hash inconsistency reported by @wkral : I'm really surprised that files on `paste.sr.ht` have changed, if anybody knows how works SouceHut, I would be glad to be enlighten :).

Related to changes in #83283.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by wkral — APPROVED** [review]
Rebuilt with this change and it works for me. I'm pretty surprised about sourcehut, but I wonder if paste is like snippets or pastebin and things can be edited afterward.

Also thanks for your original fix. Wofi works first time now, where I was previously just launching some GTK application to initialize something before it would work in sway.

**Comment by Elyhaka** [comment]
I'm pretty surprised too, I thought it was a diff generated from a specific commit, and it seems that's not the case.

Glad to read ! :tada:

**Review by erictapen — APPROVED** [review]
Thanks again. Would you be interested in taking maintainership of this package? I don't use it anymore.

**Comment by Elyhaka** [comment]
Yes, no problem for me, I'm using Sway as my daily driver for work ;).

**Review by erictapen — APPROVED** [review]

**Comment by petabyteboy** [comment]
Fixes #83627

**Comment by petabyteboy** [comment]
Is it possible that you copied the hash over from the fetchurl? fetchpatch normalizes the patch and hashes it afterwards, so using fetchpatch will result in a different result than using fetchurl. The hash in the old derivation matches the one from `nix-prefetch-url https://paste.sr.ht/blob/1cbddafac3806afb203940c029e78ce8390d8f49`.

**Comment by Elyhaka** [comment]
I have to say that I'm not sure. I believe I could have done the mistake, indeed.

If you check the previous PR i switched from `fetchurl` to `fetchpatch` at some point, and I believe I kept the same hash. I was building on my system without any issue and I was not aware of this implementation detail. I'm really wondering why it was building (and still builds) on my computer ? I've tried on another computer, and it doesn't work indeed. Is there some kind of cache that uses only the hash to retrieve it ? Is there something I can do to avoid this mistake in the future ?

**Comment by Elyhaka** [comment]
@petabyteboy : I've pushed an update

**Comment by petabyteboy** [comment]
Yes you are correct about the cache. The whole nix store is a giant cache. And both fetchurl and fetchpatch are based on **fixed-output derivations**. This is a special type of derivation where Nix will allow network access, but require the output hash to be known in advance, and after that it will use the hash to address the output in the store.

About how to prevent such problems: It's a bit difficult. If you change an expression (for example the version), you should probably try to replace the hashes that could depend on it with 00000...
For fetchurl and fetchpatch I think there is no solution that allows detecting those mismatches without testing for it.

**Review by ghost — APPROVED** [review]
Builds fine for me now :tada:

**Comment by Elyhaka** [comment]
Thanks, I understand why I've made the mistake and how to not reproduce it:

 - Change the hash with some 0 to be sure it downloads it
 - I will always try on my second computer every derivation before submitting them

Sorry about that !

**Pull request merged**
