### PR TITLE
Remove unreferenced files

### PR DESCRIPTION
**Pull request by pSub**
This commit removes files that are not referenced in nixpkgs anymore. I
have created this list by finding potential candidates using

```
find nixpkgs/pkgs -type d -links 2 | parallel -N 1 'out=`grep -L {}  top-level/all-packages.nix`;  test -n "$out" && echo  {}'
```

and have then searched for those candidates with grep in whole nixpkgs. However I am not sure if it really makes sense to remove all of those, e.g. `pkgs/applications/misc/hello/ex-1`.

### CODE REVIEW

**Comment by edolstra** [comment]
:+1:

**Comment by vcunat** [comment]
- libkolab* can be (optional) dependencies of some KDE4 PIM stuff; I'm unsure about usefulness for ~KDE5 apps. /cc maintainer @phreedom.
- openexr-ctl seems superseded by ctl that we have there.
- We have elsewhere: libgdata, tidy.
- I don't have much idea about those two ruby packages.

**Comment by jagajaga** [comment]
:+1:

**Comment by lethalman** [comment]
Let's do it.

**Pull request merged**
