### PR TITLE
python3Packages.trezor: 0.12.4 -> 0.13.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update + update dependencies

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
seems to be new failiure trezor_agent:

```
error: builder for '/nix/store/3m6by65aqahi216fmp38y0gwbqlxdgw6-python3.8-trezor_agent-0.11.0.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'trezor_agent-0.11.0.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/trezor_agent-0.11.0/dist /build/trezor_agent-0.11.0
       > Processing ./trezor_agent-0.11.0-py3-none-any.whl
       > Requirement already satisfied: libagent>=0.14.0 in /nix/store/2bff0wygksh8ihkimgim3hkn390ga8l0-python3.8-libagent-0.14.1/lib/python3.8/site-packages (from trezor-agent==0.11.0) (0.14.1)
       > ERROR: Could not find a version that satisfies the requirement trezor[hidapi]<0.13,>=0.12.0 (from trezor-agent) (from versions: none)
       > ERROR: No matching distribution found for trezor[hidapi]<0.13,>=0.12.0
       For full logs, run 'nix log /nix/store/3m6by65aqahi216fmp38y0gwbqlxdgw6-python3.8-trezor_agent-0.11.0.drv'.
```

**Comment by prusnak** [comment]
Let's wait with the merge until we test that electrum is compatible with python-trezor 0.13

**Comment by prusnak** [comment]
@GrahamcOfBorg electrum python3Packages.trezor_agent

**Comment by prusnak** [comment]
The CI is showing the following error, but I am unsure why is that. It does not happen for me locally.

```
Cannot nix-instantiate `electrum.passthru.tests' because:
error: attribute 'tests' in selection path 'electrum.passthru.tests' not found
```

**Comment by prusnak** [comment]
@GrahamcOfBorg electrum python3Packages.trezor_agent

**Pull request merged**
