### PR TITLE
poetry: 0.12.17 -> 1.0.0

### PR DESCRIPTION
**Pull request by robertodr**
###### Motivation for this change
Upgrades poetry to its latest released version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jbaum98

### CODE REVIEW

**Review by andir — CHANGES_REQUESTED** [review]
Fails to compile for me. Error is very similar to what ofBorg reports:

````
installing
Executing pipInstallPhase
/build/cleo-0.7.6/dist /build/cleo-0.7.6
Processing ./cleo-0.7.6-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement clikit<0.5.0,>=0.4.0 (from cleo==0.7.6) (from versions: none)
ERROR: No matching distribution found for clikit<0.5.0,>=0.4.0 (from cleo==0.7.6)
builder for '/nix/store/6f6y2vwgwr0zy48pxjphnkb1241wvc4i-python3.7-cleo-0.7.6.drv' failed with exit code 1
```

**Comment by robertodr** [comment]
Yes, this depends on #75873 Should I compact the two PRs into one?

**Comment by jonringer** [comment]
you could also wait for the other get merged

**Comment by jonringer** [comment]
although, seeing as this doesn't have many rebuilds, and the other is already pushing a few hundred, I would just cherry-pick this on top of the other PR

**Comment by robertodr** [comment]
Done, I am closing this one in favor of #75873

**Pull request closed without merging**
