### PR TITLE
dwarf-fortress: 0.44.12 -> 0.47.02

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
The rest of the ecosystem is slowly catching up.

This adds:
 - 0.47.02 compatible dwarf-therapist
 - 0.47.02 compatible df-hack, even if pre-release
 - latest twbt

Then sets the default df package to be the latest.

There might be some instability with the df-hack prelease and an outdated twbt

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@shazow

**Review by shazow — APPROVED** [review]
Confirmed `nix-env -f . -i dwarf-fortress-full` builds as expected on NixOS, dfhack launches with the correct versions.

**Comment by shazow** [comment]
Bonus: Might be worth re-running the `themes/update.sh` if you get a chance, just for fun. :)

**Comment by jonringer** [comment]
did another update, doesn't seem to be any new releases

**Comment by shazow** [comment]
Awesome, thanks!

**Comment by doom3wasagoodgame** [comment]
There've been 2 new releases I think, I tried updating them manually but the process is a bit convoluted for me. Any plans on updating the packages?

**Comment by shazow** [comment]
It's not as hard as it looks. :) If you want to open a PR and ping us for help, I'm happy to help.

https://github.com/NixOS/nixpkgs/pull/79630 is maybe a better reference

Otherwise I'm sure one of us will get to it next time we play it. :D

**Pull request merged**
