### PR TITLE
flutter: 3.3.8 -> 3.7.3

### PR DESCRIPTION
**Pull request by AtaraxiaSjel**
###### Description of changes

Update flutter version. Also we need update yubioath vendorHashes. For some reason this changes breaks yubioath build on aarch64 systems. Can someone help me figure that out? 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AtaraxiaSjel** [comment]
Result of `nixpkgs-review pr 215754` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>flutter</li>
    <li>hover</li>
    <li>yubioath-flutter</li>
  </ul>
</details>

**Comment by AtaraxiaSjel** [comment]
Result of `nixpkgs-review pr 215754` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>yubioath-flutter</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>flutter</li>
    <li>hover</li>
  </ul>
</details>

**Comment by AtaraxiaSjel** [comment]
```
[        ] [ +201 ms] release_bundle_linux-arm64_assets: Starting due to {}
[        ] [+1534 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +4 ms] [ +377 ms] shaderc command: [/build/tmp.CoDzApmuTx/.cache/flutter/artifacts/engine/linux-arm64/impellerc, --sksl, --iplr, --sl=/build/source/build/flutter_assets/shaders/ink_sparkle.frag, --spirv=/build/source/build/flutter_assets/shaders/ink_sparkle.frag.spirv, --input=/nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag, --remap-samplers, --include=/nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders, --include=/build/tmp.CoDzApmuTx/.cache/flutter/artifacts/engine/linux-arm64/shader_lib]
[        ] [+1404 ms] Compilation to SkSL failed.
[   +1 ms]            /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed; Compilation error. 3 error(s) and 1 warning(s).
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile) forced to be (460, core), while in source code it is (320, es)[22m[39m
[31m[   +2 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included file not found. for header name: flutter/runtime_effect.glsl[22m[39m
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' : no matching overloaded function found[22m[39m
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert from ' const float' to ' temp 2-component vector of float'[22m[39m
[        ] [  +71 ms] Persisting file store
[        ] [ +139 ms] Done persisting file store
[   +1 ms] [ +126 ms] Target release_bundle_linux-arm64_assets failed: ShaderCompilerException: Shader compilation of "/nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag" to "/build/source/build/flutter_assets/shaders/ink_sparkle.frag" failed with exit code 1.
[        ]            impellerc stdout:
[        ]            impellerc stderr:
[        ]            Compilation to SkSL failed.
[        ]            /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed; Compilation error. 3 error(s) and 1 warning(s).
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version, profile) forced to be (460, core), while in source code it is (320, es)[22m[39m
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' : Included file not found. for header name: flutter/runtime_effect.glsl[22m[39m
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: 'FlutterFragCoord' : no matching overloaded function found[22m[39m
[31m[   +1 ms] [1m           /nix/store/lh0pa5ih2szla6zrg3ndcr77dylwv42f-flutter-3.7.3-unwrapped/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :  cannot convert from ' const float' to ' temp 2-component vector of float'[22m[39m
[        ]            #0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:202:9)
[        ]            <asynchronous suspension>
[   +1 ms]            #1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:127:25)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:98:3)
[        ]            <asynchronous suspension>
[        ]            #4      BundleLinuxAssets.build (package:flutter_tools/src/build_system/targets/linux.dart:141:29)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
[        ]            <asynchronous suspension>
[   +1 ms]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[   +1 ms]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
[        ]            <asynchronous suspension>
[   +1 ms]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [ +188 ms] "flutter assemble" took 516,913ms.
[        ] [  +73 ms]
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:354:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +28 ms] Running 0 shutdown hooks
[        ] [   +5 ms] Shutdown hooks complete
[        ] [   +5 ms] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[[1m +192 ms[22m] Building Linux application... (completed in 561.6s)
[  +34 ms] "flutter linux" took 569,185ms.
[31m[  +69 ms] [1mBuild process failed[22m[39m
[31m[   +4 ms] [1m[22m[39m
[31m[1m           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)[22m[39m
[31m[1m           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:183:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:86:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           #12     main (package:flutter_tools/executable.dart:91:3)[22m[39m
[31m[1m           <asynchronous suspension>[22m[39m
[31m[1m           [22m[39m
[31m[1m           [22m[39m
[  +33 ms] Running 0 shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +5 ms] exiting with code 1

```

**Comment by NickCao** [comment]
cc @RossComputerGuy as you are working on flutter packaging recently and may lend a helping hand.

**Comment by RossComputerGuy** [comment]
Hmm, I won't be able to look into it until towards the the end of the month but I should be able to help.

**Comment by AtaraxiaSjel** [comment]
Most likely this is an upstream issue: https://github.com/flutter/flutter/issues/116703.
Maybe we can you this workaround: https://github.com/flutter/flutter/issues/116703#issuecomment-1403956612.
I'll try to write a patch, but I don't know if I can do it.

**Comment by gilice** [comment]
https://github.com/NixOS/nixpkgs/commit/a2436fc54d519c0e40de9588e34e3362bf16916a introduced  arm64 on nixos. If I'm correct, this only affects that? 

Although it would be a pretty bad solution, we could temporarily disable it until upstream fixes this issue.

Another solution would be to throw a never flutter version on the NUR until this gets fixed

**Comment by gilice** [comment]
This is weird for another reason, too:

the fix @AtaraxiaSjel linked is just copying the prebuilt shader directory to the flutter path. 
BUT, why does that affect us? we are already pulling in the release from Google (https://github.com/NixOS/nixpkgs/blob/81767d7fa41e8b0400d3c675b9bb4667ceddc1ad/pkgs/development/compilers/flutter/default.nix#L23), not from the git repo!

Is this a case of the flutter tool itself somehow messing up the shaders?

**Comment by AtaraxiaSjel** [comment]
@gilice Yes, this is an upstream problem. Google is not packing the flutter correctly for arm64. We can wait until a new stable version comes out with a fixed package, but it is unknown how quickly they will solve this problem.

**Comment by gilice** [comment]
I am testing this basically full-time on x86_64, everything works fine. The arm64 thing is a shame.

**Comment by gilice** [comment]
did this just break?

```
error: builder for '/nix/store/varcv3marlwkzv49yqbzx2vhi6kf6mqb-flutter-unwrapped-3.7.3.drv' failed with exit code 1;
       last 10 log lines:
       > Hunk #3 succeeded at 299 (offset 1 line).
       > Hunk #4 succeeded at 332 (offset 1 line).
       > Hunk #5 succeeded at 709 (offset 1 line).
       > Hunk #6 succeeded at 719 (offset 1 line).
       > Hunk #7 succeeded at 740 (offset 1 line).
       > applying patch /nix/store/jhbwwixyfra0cchvb646kga9vl6jnc2c-move-cache.patch
       > patching file packages/flutter_tools/lib/src/cache.dart
       > patching file packages/flutter_tools/test/general.shard/artifacts_test.dart
       > Hunk #2 FAILED at 306.
       > 1 out of 2 hunks FAILED -- saving rejects to file packages/flutter_tools/test/general.shard/artifacts_test.dart.rej
       For full logs, run 'nix log /nix/store/varcv3marlwkzv49yqbzx2vhi6kf6mqb-flutter-unwrapped-3.7.3.drv'.
```

**Comment by gilice** [comment]
@ofborg eval

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 215754` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>yubioath-flutter</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flutter (flutterPackages.stable)</li>
  </ul>
</details>

**Comment by wegank** [comment]
@ofborg build yubioath-flutter

**Pull request closed without merging**
