### PR TITLE
awscli2: pin python311

### PR DESCRIPTION
**Pull request by kirillrdy**
## Description of changes

doesn't build with 3.12 

tracking issue https://github.com/aws/aws-cli/issues/8342 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 325207` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>awscli2</li>
    <li>awscli2.dist</li>
    <li>liquidsoap</li>
  </ul>
</details>

**Review by marcusramberg — APPROVED** [review]

**Comment by devusb** [comment]
what about
```
--- a/pkgs/tools/admin/awscli2/default.nix
+++ b/pkgs/tools/admin/awscli2/default.nix
@@ -1,6 +1,6 @@
 { lib
 , stdenv
-, python3
+, python311
 , groff
 , less
 , fetchFromGitHub
@@ -12,6 +12,7 @@
 }:
 
 let
+  python3 = python311;
   py = python3 // {
     pkgs = python3.pkgs.overrideScope (final: prev: {
       sphinx = prev.sphinx.overridePythonAttrs (prev: {
```
instead so as to be compatible with #324786?

**Comment by Aleksanaa** [comment]
There's something called "overriding interface".

**Comment by kirillrdy** [comment]
@devusb https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/README.md#changing-implicit-attribute-defaults

@Aleksanaa https://github.com/NixOS/nixpkgs/pull/324786

**Comment by devusb** [comment]
@kirillrdy ahh gotcha -- makes sense. thanks. I haven't actually used `by-name` much yet.

**Review by devusb — APPROVED** [review]

**Comment by mvillafuertem** [comment]
I have tried to use this change, but when I update `nix flake update` I don't get the latest changes.... any idea how to get the latest changes from the master branch?


```shell

nix flake update

• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/3281bec7174f679eabf584591e75979a258d8c40?narHash=sha256-bBz4/T/zBzv9Xi5XUlFDeosmSNppLaCQTizMKSksAvk%3D' (2024-05-12)
  → 'github:nixos/nixpkgs/ab82a9612aa45284d4adf69ee81871a389669a9e?narHash=sha256-5r0pInVo5d6Enti0YwUSQK4TebITypB42bWy5su3MrQ%3D' (2024-07-07)

```

```shell

nix-channel --list

nixpkgs https://nixos.org/channels/nixpkgs-unstable

```


```shell

error: builder for '/nix/store/9jl3s028w0ck5s7lzx2y4llgq5yphaa3-awscli2-2.17.5.drv' failed with exit code 1;
       last 10 log lines:
       >     from botocore.docs.service import ServiceDocumenter
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/service.py", line 13, in <module>
       >     from botocore.docs.bcdoc.restdoc import DocumentStructure
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/docs/bcdoc/restdoc.py", line 15, in <module>
       >     from botocore.compat import OrderedDict
       >   File "/private/tmp/nix-build-awscli2-2.17.5.drv-0/source/awscli/botocore/compat.py", line 36, in <module>
       >     from botocore.vendored.six.moves import http_client
       > ModuleNotFoundError: No module named 'botocore.vendored.six.moves'
       >
       > ERROR Backend subprocess exited when trying to invoke build_wheel
       For full logs, run 'nix log /nix/store/9jl3s028w0ck5s7lzx2y4llgq5yphaa3-awscli2-2.17.5.drv'.
error: 1 dependencies of derivation '/nix/store/53mgs49ifkgx5kwx2xhqkwh9ywmychqb-bashrc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jiv6gywgw7k7iwhvp56rpv5kfzfc0z97-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6pqxvryafiqj4f7yx1qjvc3lf2xx8xzy-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ljh7xxikpd0al3j2xsxha166bvd93zif-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hr05x612az56ycjnww9xnh0sc5knsix1-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rzb42nvj20x4vhb3p8insva11ff0048l-darwin-system-24.11.20240707.ab82a96+darwin4.0f89b73.drv' failed to build

```

**Comment by devusb** [comment]
This hasn't made it to `nixos-unstable` or `nixpkgs-unstable` yet -- you can watch the progress of this PR to various release channels [here](https://nixpk.gs/pr-tracker.html?pr=325207).

In the meantime, you could use an overlay to override the python version with something like
```
final: prev: {
   awscli2 = prev.awscli2.override {
     python3 = prev.python311;
   };
};
```

**Comment by mvillafuertem** [comment]
> This hasn't made it to `nixos-unstable` or `nixpkgs-unstable` yet -- you can watch the progress of this PR to various channels [here](https://nixpk.gs/pr-tracker.html?pr=325207).
> 
> In the meantime, you could override the python version with something like
> 
> ```
> pkgs.awscli2.override {
>   python3 = pkgs.python311;
> };
> ```

I tried this but it didn't work, good thing it is now on unstable. Thanks

**Pull request merged**
