### PR TITLE
xsv: 0.12.1 -> 0.12.2

### PR DESCRIPTION
**Pull request by mimame**
###### Motivation for this change

Update xsv to the last version

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
I'm unfamiliar with rust, what are the implications of updating the rust registry?

**Comment by mimadrid** [comment]
Hi @joachifm, update the rust registry is mandatory for getting the last version of some dependencies.

**Comment by joachifm** [comment]
The rust registry was updated elsewhere. Can you rebase?

**Comment by joachifm** [comment]
I failed to notice that the sha256 is malformed (one char too many). I've reverted the commit. Please resubmit.

**Comment by mimadrid** [comment]
I'm so sorry. Something was wrong during the rebase :/

**Comment by joachifm** [comment]
@mimadrid no worries, it happens :)

**Pull request merged**
