### PR TITLE
ghc: 9.6.3-binary -> 9.6.4-binary

### PR DESCRIPTION
**Pull request by mpscholten**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sternenseemann** [comment]
Upgrading to 9.6.4 doesn't solve any of our problems, the problem is not a regression that was fixed in 9.6.4, but rather an issue with the bindists of 9.6 as such. The 9.6.4 bindist has a completely new issue (passes unsupported flags to our ld), so it doesn't seem worth it since none of the codegen bugs in .3 seem to affect the GHC bootstrap.

**Comment by TravisWhitaker** [comment]
We run into a different issue with GHC 9.6.4. I'm pretty confident it's hsc2hs's fault. When building the clock package, hsc2hs passes `-no_fixup_chains` to `ld` which isn't present on darwin.

The Nixpkgs-build GHC 9.6.4 doesn't have this problem, so either it's an issue with whatever hsc2hs is in that bindist, or Nixpkgs' is hiding the problem some other way (with a patch or `ld` wrapper or something).

```
Running phase: buildPhase
Preprocessing library for clock-0.8.4..
linking dist/build/System/Clock_hsc_make.o failed (exit code 1)
rsp file was: "dist/build/System/hsc2hscall90742-2.rsp"
command was: /nix/store/0m04cmy32vs1686pzjqajsh50arbv8m4-clang-wrapper-16.0.6/bin/clang dist/build/System/Clock_hsc_make.o dist/build/System/Clock_hsc_utils.o -o dist/build/System/Clock_hsc_make --target=arm64-apple-darwin -Wl,-no_fixup_chains -Wl,-no_warn_duplicate_libraries --target=arm64-apple-darwin -L/nix/store/j3yw5w8pbdv4argnmx7i4i0lvglnh7ll-libcxx-16.0.6/lib -L/nix/store/g9x4r8l8hjk3vfj26k90p3rjc6g8j3i6-libcxxabi-16.0.6/lib -L/nix/store/v7rhm5d36dn6bgcbdc4w3dg8ym3vxb5d-compiler-rt-libc-16.0.6/lib -L/nix/store/7y2jn8rdygiy22rzy66wsz4gvrfn5hh6-apple-framework-CoreFoundation-11.0.0/lib -L/nix/store/cii11dfrz126yb3d03aqyahwq3fanl1g-libobjc-11.0.0/lib -L/nix/store/j1r1hnfk0zn4k44nm6m4a27nka35649n-ghc-binary-9.6.4/lib/ghc-9.6.4/lib/../lib/aarch64-osx-ghc-9.6.4/base-4.18.2.0 -L/nix/store/n7hyb4xfwjdcm87gbisck8pl9c2mp1qs-libiconv-50/lib -liconv -L/nix/store/j1r1hnfk0zn4k44nm6m4a27nka35649n-ghc-binary-9.6.4/lib/ghc-9.6.4/lib/../lib/aarch64-osx-ghc-9.6.4/ghc-bignum-1.3 -L/nix/store/5kg229dp8nb6a2m0hv7g1zl725kxp0nn-gmp-with-cxx-6.3.0/lib -L/nix/store/j1r1hnfk0zn4k44nm6m4a27nka35649n-ghc-binary-9.6.4/lib/ghc-9.6.4/lib/../lib/aarch64-osx-ghc-9.6.4/ghc-prim-0.10.0 -L/nix/store/0z3mx40zc1b2zf8yjlrkk0iyps3yxlil-libffi-3.4.6/lib -L/nix/store/j1r1hnfk0zn4k44nm6m4a27nka35649n-ghc-binary-9.6.4/lib/ghc-9.6.4/lib/../lib/aarch64-osx-ghc-9.6.4/rts-1.0.2 -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -lm -ldl -lffi
error: ld: unknown option: -no_fixup_chains
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by TravisWhitaker** [comment]
Ah @sternenseemann you beat me to it.

Given the 9.6.x bindist issues, do you see a big problem with using the Nixpkgs-built 9.6.4 to bootstrap the 9.8.x GHCs?

**Comment by reckenrode** [comment]
> We run into a different issue with GHC 9.6.4. I'm pretty confident it's hsc2hs's fault. When building the clock package, hsc2hs passes `-no_fixup_chains` to `ld` which isn't present on darwin.

ld64 was upgraded to 951.9 in https://github.com/NixOS/nixpkgs/pull/307880, which is the version shipped with Xcode 15. The `-no_fixup_chains` flag should be supported now. The bindist and bootstrap issue should also be fixed in https://github.com/NixOS/nixpkgs/pull/330559.

**Pull request closed without merging**
