### PR TITLE
python311Packages.pytensor: 2.18.2 -> 2.18.4, python311Packages.pymc: 5.10.1 -> 5.10.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog `pytensor`: https://github.com/pymc-devs/pytensor/releases/tag/rel-2.18.4
Changelog `pymc`: https://github.com/pymc-devs/pymc/releases/tag/v5.10.2

cc @bcdarwin @nidabdella 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
WARNING: `jaxlib` is currently broken on `master`.
Hence I cannot test the build of `pytensor`.

**Comment by wegank** [comment]
`2.18.3 -> 2.18.2` -> `2.18.2 -> 2.18.3`

**Comment by bcdarwin** [comment]
The diff looks fine to me, and I was able to test `pytensor` by dropping `jaxlib` and `jax` from the check inputs, but no such luck with `pymc`. Not sure what the protocol is here.

**Comment by bcdarwin** [comment]
I suppose since upstream broke the hashes of the versions we have in trunk, it'd probably be fine to merge since we're not making things any worse?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 273654` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.pytensor</li>
    <li>python310Packages.pytensor.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 273654` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.pytensor</li>
    <li>python310Packages.pytensor.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
  </ul>
</details>

**Comment by SomeoneSerge** [comment]
Getting a hash mismatch for `"https://github.com/pymc-devs/pytensor/archive/refs/tags/rel-2.18.4.tar.gz` locally

**Comment by SomeoneSerge** [comment]
Oh that was an issue from `master` apaprently:

```
❯ nix build -I nixpkgs=flake:github:NixOS/nixpkgs/master -f '<nixpkgs>' --arg config '{ allowUnfree = true; cudaSupport = true; cudaCapabilities = [ "8.6" ]; cudaEnableForwardCompat = false; }' python311Packages.pytensor
error: hash mismatch in fixed-output derivation '/nix/store/mi35kg7f2nfx83g3wqpqzsz1n6f7048f-source.drv':
         specified: sha256-uB5VT4wP08pOkHlxdPJTXK4j5ubmf+hk5oHYPM6diHM=
            got:    sha256-tYryKYpu4AZBHExeLQ3TG62fsHogoNz+srFaXYtrDm8=
```


I'm also getting issues with the cudaPackages' flag selection logic, but they're certainly not related to this PR:

```
❯ nixpkgs-review pr 273654 --extra-nixpkgs-config '{ cudaSupport = true; cudaCapabilities = [ "8.6" ]; cudaEnableForwardCompat = false; }' --skip-package-regex 'python310.*'
...
       … while calling anonymous lambda

         at /home/ss/.cache/nixpkgs-review/pr-273654-2/nixpkgs/pkgs/development/cuda-modules/flags.nix:222:27:

          221|           requestedJetsonDevices =
          222|             lists.filter (cap: cudaComputeCapabilityToIsJetson.${cap})
             |                           ^
          223|               cudaCapabilities;

       error: attribute '"8.6"' missing

       at /home/ss/.cache/nixpkgs-review/pr-273654-2/nixpkgs/pkgs/development/cuda-modules/flags.nix:222:32:

          221|           requestedJetsonDevices =
          222|             lists.filter (cap: cudaComputeCapabilityToIsJetson.${cap})
             |                                ^
          223|               cudaCapabilities;
       Did you mean one of 3.0, 3.2, 3.5, 3.7 or 5.0?
...
```

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 273654` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.pytensor</li>
    <li>python310Packages.pytensor.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
  </ul>
</details>

**Review by SomeoneSerge — APPROVED** [review]

**Comment by SomeoneSerge** [comment]
Thanks!

**Pull request merged**
