### PR TITLE
mpd: add nfs and smb support

### PR DESCRIPTION
**Pull request by jfrankenau**
###### Motivation for this change

MPD supports so-called [storage plugins](https://www.musicpd.org/doc/user/storage_plugins.html). This allows it to directly access NFS and SMB shares without the need for mounting them and is a useful feature in a satellite setup, see also #41367. To make use of them in NixOS the `services.mpd.musicDirectory` option needs to allow for more than just paths.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @andir

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build mpd

**Comment by xeji** [comment]
Let's run the module test
@GrahamcOfBorg test mpd

**Comment by xeji** [comment]
The test eval error seems unrelated. I just ran the test locally on this branch, looks good.

**Comment by xeji** [comment]
Turns out `libnfs` and `smbclient` have been broken on darwin for a while, so these options should default to false on darwin in order for mpd to build.

**Comment by jfrankenau** [comment]
OK, good to know. I've updated the PR accordingly.

**Comment by xeji** [comment]
@GrahamcOfBorg build mpd

**Review by xeji — APPROVED** [review]
Thanks, LGTM.

**Pull request merged**
