### PR TITLE
freetype: 2.7.1 -> 2.9

### PR DESCRIPTION
**Pull request by mogorman**
###### Motivation for this change
Version bump from 2.7.1 to 2.9, also allows us to get rid of some of these patches that have now been rolled into the repo directly.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by adisbladis** [comment]
Considering the amount of rebuilds could you rebase this on staging?
```
Estimating rebuild amount by counting changed Hydra jobs.
   1150 x86_64-darwin
   4310 x86_64-linux
```

**Comment by mogorman** [comment]
@adisbladis  changed to staging

**Comment by jtojnar** [comment]
See also https://github.com/NixOS/nixpkgs/pull/29704

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/36371

**Pull request closed without merging**
