### PR TITLE
iosevka-comfy: 1.4.0 -> 2.0.0

### PR DESCRIPTION
**Pull request by DamienCassou**
## Description of changes

https://github.com/protesilaos/iosevka-comfy/releases/tag/2.0.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@ofborg build iosevka-comfy

**Review by drupol — CHANGES_REQUESTED** [review]
There are some build failures:

```
    > Running phase: installPhase
       > install: missing destination file operand after '/nix/store/w2nqwcg430h19c3zdzabmln3gn5ys932-iosevka-comfy-2.0.0/share/fonts/truetype'
       > Try 'install --help' for more information.
       For full logs, run 'nix log /nix/store/xavv0ci4hn33zi12fijnaqf9k24j8flv-iosevka-comfy-2.0.0.drv'.
error: build of '/nix/store/0z3rw84q6x3ybid14zmx7g1iz9xkmj1f-iosevka-comfy-wide-2.0.0.drv', '/nix/store/1ask99crkaig12nw69j26rq2f5s0596c-iosevka-comfy-fixed-2.0.0.drv', '/nix/store/31h1cwrbb7rghd0lpkghv008712qqpky-iosevka-comfy-motion-2.0.0.drv', '/nix/store/4p7xj3fnj0mp0asdf93bf7fsvxf440kw-iosevka-comfy-wide-fixed-2.0.0.drv', '/nix/store/55pck5k81hvcjw9c8dw28h60bj2xfq0q-iosevka-comfy-wide-duo-2.0.0.drv', '/nix/store/5pqylf2wvxfsjvf31pr9j6d0bqz59ifc-iosevka-comfy-motion-duo-2.0.0.drv', '/nix/store/95hn7s84k3npifdimdnin65vn217rasz-iosevka-comfy-motion-fixed-2.0.0.drv', '/nix/store/b95dxr2gc4yx79qqqn4zyb1cgk0ms7gv-iosevka-comfy-wide-motion-duo-2.0.0.drv', '/nix/store/hirq2kg7n3jb4yvnhz3as06qm8ssvvbb-iosevka-comfy-duo-2.0.0.drv', '/nix/store/qw2sbc6byika7n5ys33k29zn998ipvsw-iosevka-comfy-wide-motion-2.0.0.drv', '/nix/store/svzcjshnwblz3x5lpqyswylmsd215v3g-iosevka-comfy-wide-motion-fixed-2.0.0.drv', '/nix/store/xavv0ci4hn33zi12fijnaqf9k24j8flv-iosevka-comfy-2.0.0.drv' failed
```

**Comment by DamienCassou** [comment]
@ofborg build iosevka-comfy

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 336594` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>iosevka-comfy.comfy</li>
    <li>iosevka-comfy.comfy-duo</li>
    <li>iosevka-comfy.comfy-fixed</li>
    <li>iosevka-comfy.comfy-motion</li>
    <li>iosevka-comfy.comfy-motion-duo</li>
    <li>iosevka-comfy.comfy-motion-fixed</li>
    <li>iosevka-comfy.comfy-wide</li>
    <li>iosevka-comfy.comfy-wide-duo</li>
    <li>iosevka-comfy.comfy-wide-fixed</li>
    <li>iosevka-comfy.comfy-wide-motion</li>
    <li>iosevka-comfy.comfy-wide-motion-duo</li>
    <li>iosevka-comfy.comfy-wide-motion-fixed</li>
  </ul>
</details>

**Comment by DamienCassou** [comment]
@drupol I fixed the issue by removing the broken `installPhase` and inheriting it instead.

**Comment by drupol** [comment]
@DamienCassou There's no more `installPhase` then?

**Comment by DamienCassou** [comment]
@drupol the `installPhase` is the one of iosevka by default: https://github.com/NixOS/nixpkgs/blob/24.05/pkgs/data/fonts/iosevka/default.nix#L117. It is exactly the same as the one I deleted except that the old directory "ttf/" is now "TTF/".

**Review by drupol — APPROVED** [review]

**Pull request merged**
