### PR TITLE
libmsgpack/libtoxcore/qtox: several related package upgrades

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

This change carries a number of other changes that arose as a consequence of the ```libmsgpack``` change.

```nox-review``` fails but that is because ```pjsip``` fails and thus ```ring-daemon``` which was the case anyway.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Cc: @redbaron @wkennington @viric @jgeerds @akaWolf

**Comment by akaWolf** [comment]
The name of PR does not reflect essence of the PR itself. Pls fix.

**Review by fpletz — APPROVED** [review]

**Comment by orivej** [comment]
utox has been updated in #31072, this PR needs rebasing.

**Comment by orivej** [comment]
qtox hash fails to validate:

> output path ‘/nix/store/h5bq81pk7qxj1d5aa3svsaishmjcxigh-source’ has r:sha256 hash ‘1l1k8s10jj6nm9i33m8xhjwdhikvp7csdp6x1gxjxdj526aak8q9’ when ‘1832ay0167qjc2vvpps507mnb0531y3d3pxmlm5nakvcwjs7vl8d’ was expected

**Comment by peterhoeg** [comment]
No idea what happened here, but fix in 1529295c9b9

**Pull request merged**
