### PR TITLE
 thunderbird, thunderbird-bin: 68.4.2 -> 68.5.0 [High security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- High security fixes
- Other improvements and fixes.

https://www.thunderbird.net/en-US/thunderbird/68.5.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-07/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by taku0** [comment]
For release-19.09: #79918

**Review by vcunat — APPROVED** [review]
Both seem to run fine for me.

On current master some dependencies of `thunderbird` need #79930 to build.

**Review by lovesegfault — APPROVED** [review]
Tested and works :)

**Comment by flokli** [comment]
Thanks! For these fixes, please also file PRs, or ping @NixOS/backports so this will land in 20.03 as well.

**Comment by vcunat** [comment]
Re-tested for 20.03 as well and pushed as 7e10d60c80 and 0ce2f4947.

**Pull request merged**
