### PR TITLE
dune: 1.1.1 -> 1.2.1

### PR DESCRIPTION
**Pull request by Zimmi48**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @vbgl

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build pyre

**Comment by vbgl** [comment]
Please address the regression on linux: this breaks `pyre`. Updating it to a more recent version (say 0.0.14) should help.

**Comment by Zimmi48** [comment]
Sure, sorry I was kind of lazy and should have run `nox-review` before submitting the PR.

**Comment by vbgl** [comment]
Updating `pyre` sure deserves its own commit. And probably its own PR. Thanks.

**Comment by Zimmi48** [comment]
Alright.

**Comment by Zimmi48** [comment]
Should I rebase now that the other PR is merged?

**Pull request closed without merging**
