### PR TITLE
transcribe: init at 8.40

### PR DESCRIPTION
**Pull request by michalrus**
###### Motivation for this change

It’s unsurpassed in the area of transcribing music.
###### Things done
- [x] Tested using sandboxing
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change — _none do_
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by michalrus** [comment]
I’m not really sure from the log, why this PR has failed on Travis. :smiley: Any help?

**Comment by RamKromberg** [comment]
What's wrong with 8.62?

**Comment by michalrus** [comment]
@RamKromberg, he switched to GTK3 and… the interface is messy, to the point of being unusable. =) At least on my (default?) Adwaita theme.

Also, he switched to GStreamer-1.0, and, after adding all the needed deps, there’s still no audio device available in the app…

I can add a `withGtk3` option that will be switched off by default.

Good idea?

**Comment by RamKromberg** [comment]
No idea :D The moment I noticed it's a binary I gave up :D If you're saying the older interface is better, stick to it.
As for the specific audio issue, I looked up the release news\log\notice and it mentioned dropping alsa so I'm guessing it was done in favor of pulseaudio? Anyhow, since I don't know anything about the program, it's a binary, and I have no merge privileges, I get to avoid the whole thing and run away with my tail between my lags :D

Good luck :)

**Pull request merged**
