### PR TITLE
fix few downloads in release-17.09

### PR DESCRIPTION
**Pull request by veprbl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Can you add a note explaining why https://github.com/NixOS/nixpkgs/commit/9bf3273718962320fb5b4b2010d65b8ee5c81d48 is not used instead? It's not clear to me why, anyway.

**Comment by veprbl** [comment]
@joachifm To not have rebuilds caused by change of hash. If this is not important for stable, we can use that of course.

**Comment by joachifm** [comment]
I think for stable the most important thing is to not break/change behavior willy nilly, rebuilds are not an impediment to backporting in general.

**Comment by dtzWill** [comment]
FWIW the ncurses URL (and other "invisible-island" packages) was improved/fixed in #33340, although I suppose additional mirrors for fixed-hash sources doesn't hurt :).

**Review by vcunat — APPROVED** [review]

**Pull request merged**
