### PR TITLE
update to tensorflow 1.13.1

### PR DESCRIPTION
**Pull request by jyp**
###### Motivation for this change

Upstream update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Kjuvi** [comment]
Duplicate: #56424

**Comment by averelld** [comment]
This is better and more complete, so I closed the other PR. But the lifted python 3.7 restriction should be added here, that is like the best new feature, especially since 3.7 is the NixOS default!

**Comment by FRidh** [comment]
Took this and the commit from @averelld and merged them in https://github.com/NixOS/nixpkgs/pull/56669.

**Comment by FRidh** [comment]
cherry-picked to staging-19.03 as well.

**Pull request closed without merging**
