### PR TITLE
pkgs/*: remove unreferenced function arguments

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

cleanup, remove unreferenced function arguments

zero-rebuild change, with the exception of [3 ruby derivations](https://github.com/NixOS/nixpkgs/pull/43869/commits/cd6e2c9642b8e608c905f350cece21141435deef) which use ```./.```

### CODE REVIEW

**Comment by volth** [comment]
Is it possible to see somehow what has @GrahamcOfBorg marked to rebuild (what is reported as ```10.rebuild-darwin: 1-10```  ```10.rebuild-linux: 11-100```) ?

I expected ```10.rebuild-darwin: 0```  ```10.rebuild-linux: 0```

**Comment by volth** [comment]
there was an tab/space issue, but rebuild count is still non zero

**Comment by volth** [comment]
Ah, ```asciidoctor``` has ```gemdir = ./.;```. 
As ```./.``` includes ```./default.nix``` it rebuilds on every ```./default.nix``` change, even in comments

**Comment by Mic92** [comment]
Let's merge it while it's hot

**Comment by volth** [comment]
There is also https://github.com/NixOS/nixpkgs/pull/43863
The same for nixos/* directory

**Comment by adisbladis** [comment]
This broke eval of emacs packages from elpa.

Fixed in 607ae1df1b7ae66baa95bca24bc28ea859a903b9

**Comment by Moredread** [comment]
@volth: how did you find them?

**Comment by volth** [comment]
@Moredread https://github.com/NixOS/nixpkgs/pull/43857#issuecomment-406683771

**Pull request merged**
