### PR TITLE
Use sdl2 for crawl tiles.

### PR DESCRIPTION
**Pull request by FlorentBecker**

### CODE REVIEW

**Comment by MP2E** [comment]
I'll test this when I get back to my work machine, the changes are simple enough, but Travis is reporting an internal compiler error when building abyss.c

https://travis-ci.org/NixOS/nixpkgs/builds/56702688#L1038

Might be spurious, I'll test when I get back

**Comment by FlorentBecker** [comment]
I think it's transient travis trouble: I do have a working crawl-tiles.

**Comment by lethalman** [comment]
@MP2E that's because travis killed gcc while compiling that source file.

**Comment by MP2E** [comment]
Ahh that makes sense. I've tested this on my end and it works well, both in i686 and x86_64. I'll go ahead and merge it in

**Comment by MP2E** [comment]
Looks like this was already pulled into master through another commit

https://github.com/NixOS/nixpkgs/pull/7116

**Pull request closed without merging**
