### PR TITLE
pythonPackages.scipy_1_4: drop

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Versioned attributes in python-packages.nix should be avoided.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by zaninime — APPROVED** [review]

**Comment by zaninime** [comment]
Thanks for fixing it so quickly!

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 127910` at 48eb03aa run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>nanovna-saver</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `mkDerivationWith`.
Near pkgs/applications/science/electronics/nanovna-saver/default.nix:1:8:
```
  |
1 | { lib, mkDerivationWith, wrapQtAppsHook, python3, fetchFromGitHub
  |        ^
```
</li>
    <li>warning: unused-argument

Unused argument: `qtbase`.
Near pkgs/applications/science/electronics/nanovna-saver/default.nix:2:3:
```
  |
2 | , qtbase }:
  |   ^
```
</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@zaninime I added a commit preventing double-wrapping.

**Review by risicle — APPROVED** [review]
Nice. Builds happily, macos 10.15 & nixos x86_64. Can't really test it though without the hardware.

**Pull request merged**
