### PR TITLE
firefox{,-beta,-devedition,-esr-128}-unwrapped: split into separated files

### PR DESCRIPTION
**Pull request by jopejoe1**
## Description of changes
This makes the update script work with firefox beta and devedition, by splitting the versions into separated files so that the script is not failing due to duplicated version strings.

Intending to merge this shortly before branch-off.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
The change refers `update.nix`, but the updater fails to find it's location:

```
$ nix-shell maintainers/scripts/update.nix --argstr package firefox-esr-unwrapped
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nixpkgs-update-script'
         whose name attribute is located at /home/slyfox/dev/git/nixpkgs-master/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'shellHook' of derivation 'nixpkgs-update-script'
         at maintainers/scripts/update.nix:229:3:
          228|   '';
          229|   shellHook = ''
             |   ^
          230|     unset shellHook # do not contaminate nested shells

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: path 'pkgs/applications/networking/browsers/firefox/packages/update.nix' does not exist
```

Missing file or a wrong path?

**Comment by jopejoe1** [comment]
Ahh, messed up the rebase and lost a `.`, will open up a pr to fix that.

**Comment by drupol** [comment]
Hey!

I don't know if this is related but I get this error now:

```
        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
┃ 
┃        error: function 'anonymous lambda' called with unexpected argument 'pipewireSupport'
┃        at /nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source/pkgs/applications/networking/browsers/firefox/packages/firefox.nix:1:1:
┃             1| {
┃              | ^
┃             2|   stdenv,

```

The error is related to this line in my config:

```
        package = (pkgs.wrapFirefox (pkgs.firefox-unwrapped.override { pipewireSupport = true; }) { });
```

**Comment by jopejoe1** [comment]
Just checked that and indeed this pr unitedly broke that feature, will have a fix ready soon.

**Comment by jopejoe1** [comment]
Fixed in #356575

**Pull request merged**
