### PR TITLE
python3Packages.httpx: 0.18.0 -> 0.18.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update httpx to 0.18.2

Change log: https://github.com/encode/httpx/releases/tag/0.18.2

Includes update of packages which depends on `httpx`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by risicle** [comment]
`homeassistant` fails with

```
ERROR: Could not find a version that satisfies the requirement httpx==0.18.0 (from homeassistant) (from versions: none)
ERROR: No matching distribution found for httpx==0.18.0
```

Though I'm guessing you already know that

**Comment by fabaff** [comment]
The next Home Assistant release will require `httpx-0.18.2`.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 132510` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>python38Packages.apache-airflow</li>
    <li>python38Packages.authcaptureproxy</li>
    <li>python38Packages.sunpy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python39Packages.apache-airflow</li>
    <li>python39Packages.authcaptureproxy</li>
    <li>python39Packages.sunpy</li>
    <li>python39Packages.teslajsonpy</li>
    <li>theharvester</li>
  </ul>
</details>
<details>
  <summary>58 packages built:</summary>
  <ul>
    <li>datasette (python39Packages.datasette)</li>
    <li>dyndnsc</li>
    <li>python38Packages.PyRMVtransport</li>
    <li>python38Packages.axis</li>
    <li>python38Packages.datasette</li>
    <li>python38Packages.denonavr</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.elmax</li>
    <li>python38Packages.entrance</li>
    <li>python38Packages.entrance-with-router-features</li>
    <li>python38Packages.envoy-reader</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.ha-philipsjs</li>
    <li>python38Packages.httpx</li>
    <li>python38Packages.httpx-ntlm</li>
    <li>python38Packages.httpx-socks</li>
    <li>python38Packages.ipfshttpclient</li>
    <li>python38Packages.ismartgate</li>
    <li>python38Packages.json-logging</li>
    <li>python38Packages.pylitterbot</li>
    <li>python38Packages.pypoint</li>
    <li>python38Packages.pytest-httpx</li>
    <li>python38Packages.pytest-sanic</li>
    <li>python38Packages.respx</li>
    <li>python38Packages.sanic</li>
    <li>python38Packages.sanic-auth</li>
    <li>python38Packages.sanic-testing</li>
    <li>python38Packages.slowapi</li>
    <li>python38Packages.total-connect-client</li>
    <li>python38Packages.zeep</li>
    <li>python39Packages.PyRMVtransport</li>
    <li>python39Packages.axis</li>
    <li>python39Packages.denonavr</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.elmax</li>
    <li>python39Packages.entrance</li>
    <li>python39Packages.entrance-with-router-features</li>
    <li>python39Packages.envoy-reader</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.ha-philipsjs</li>
    <li>python39Packages.httpx</li>
    <li>python39Packages.httpx-ntlm</li>
    <li>python39Packages.httpx-socks</li>
    <li>python39Packages.ipfshttpclient</li>
    <li>python39Packages.ismartgate</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.pylitterbot</li>
    <li>python39Packages.pypoint</li>
    <li>python39Packages.pytest-httpx</li>
    <li>python39Packages.pytest-sanic</li>
    <li>python39Packages.respx</li>
    <li>python39Packages.sanic</li>
    <li>python39Packages.sanic-auth</li>
    <li>python39Packages.sanic-testing</li>
    <li>python39Packages.slowapi</li>
    <li>python39Packages.total-connect-client</li>
    <li>python39Packages.zeep</li>
    <li>wapiti</li>
  </ul>
</details>

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures on macos 10.15

**Comment by pinpox** [comment]
> `homeassistant` fails with
> 
> ```
> ERROR: Could not find a version that satisfies the requirement httpx==0.18.0 (from homeassistant) (from versions: none)
> ERROR: No matching distribution found for httpx==0.18.0
> ```
> 
> Though I'm guessing you already know that

Having this error aswell. Did you find a fix?

**Comment by mweinelt** [comment]
Home Assistant was updated in #132946 and works. It's possible you are using the unstable channel and that is stuck in an awkward position.

**Comment by pinpox** [comment]
@mweinelt Can you expand on what you mean by stuck in an awkward position? Is that something that is going to be resolved in near future?

**Comment by mweinelt** [comment]
See https://status.nixos.org/. For the a channel to advance its tested set needs to complete. For Unstable that is https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents.

**Pull request merged**
