### PR TITLE
mono: drop minor versions and upgrade to 5.16.0.220

### PR DESCRIPTION
**Pull request by obadz**
###### Motivation for this change

Mono versions have proliferated in nixpkgs. I'm proposing to drop:
* 4.6 - Only used by fsharp 4.1 had known CVE
* 5.0 - Unused
* 5.4 - Only used by keepass but keypass seems to build fine against 5.16
* 5.8 - Only referred to by foundationdb but that also seems to build fine against 5.14
* 5.14 - Upgrade to 5.16 

Cc @jraygauthier who pointed pythonnet to refer to Mono 4.6 (was there a reason?).

Cc mono peeps @kuznero @Mic92 @thoughtpolice @vrthra 

Going forward, I propose that we only maintain the major versions (mono4 & mono5 at this time) to avoid loading hydra with useless builds and have packages randomly pointing to stale versions of mono when they probably don't need to.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by obadz** [comment]
I extracted the libgdiplus updates by @avnik from #36711.

**Comment by Mic92** [comment]
I think you can drop fsharp41 too.

**Comment by Mic92** [comment]
@kuznero do you still maintain fsharp41?

**Comment by obadz** [comment]
I think fsharp is a bit out of scope for this PR.

**Comment by obadz** [comment]
https://github.com/NixOS/nixpkgs/pull/23295/commits/d27768ac1bb06aa4471dc5bcd500a583bd4ece24 from #23295 has an LLVM update as well as a separate build of reference assemblies that would be great to cherry-pick but they're bundled in a mega commit which makes them hard to extract.

**Comment by avnik** [comment]
On Sun, Dec 23, 2018 at 09:28:05AM -0800, jraygauthier wrote:

> > Cc @jraygauthier who pointed pythonnet to refer to Mono 4.6 (was there a reason?).
> 
> none other than it respected the constraint mentioned as comment. I should definitely have pointed it to `mono4` as you did.
> 

Actually all packages using concrete versions of mono should be reviewed,
and probably upgraded/checked on compatibility to recent ones.

**Comment by obadz** [comment]
Does anyone know how to track down this Debian patch from @abbradar's commit?

```nix
    # Use built frameworks instead of pre-built reference assemblies.
    (fetchpatch {
      url = "https://anonscm.debian.org/cgit/pkg-mono/packages/mono.git/patch/?id=3cfd6a21f889eebe24e124c1e96d6d05ed722142";
      sha256 = "1y4y6sks7magxqm34m8ywi6yrgan037nzgkwhrq620sfkddialr4";
    })
```

**Comment by obadz** [comment]
Thanks @samueldr.

The patch no longer applies cleanly and while Mono builds without it, dependencies won't. Here's keepass:

```
        Program.cs(85,18): error CS0518: Predefined type 'System.Object' is not defined or imported
        Program.cs(87,18): error CS0518: Predefined type 'System.Boolean' is not defined or imported
        Program.cs(242,4): error CS0518: Predefined type 'System.Object' is not defined or imported
        Program.cs(242,4): error CS0246: The type or namespace name 'STAThreadAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Program.cs(242,4): error CS0246: The type or namespace name 'STAThread' could not be found (are you missing a using directive or an assembly reference?)
        Program.cs(96,15): error CS0518: Predefined type 'System.Enum' is not defined or imported
        Program.cs(96,15): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(98,11): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(99,20): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(100,11): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(101,16): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(102,15): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(103,11): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(104,13): error CS0518: Predefined type 'System.Int32' is not defined or imported
        Program.cs(105,23): error CS0518: Predefined type 'System.Int32' is not defined or imported

         0 Warning(s)
         38850 Error(s)

Time Elapsed 00:00:11.3447710
builder for '/nix/store/yaivhykbv468mj8ramm0m3bbpmg5919b-keepass-2.40.drv' failed with exit code 1
error: build of '/nix/store/yaivhykbv468mj8ramm0m3bbpmg5919b-keepass-2.40.drv' failed
```

I'm giving up on the "reference assemblies" portion of @abbradar's patch :-(

**Comment by obadz** [comment]
@abbradar, would you mind having a look at 013927f (which is extracted from your PR).

**Comment by obadz** [comment]
@GrahamcOfBorg build keepass fsharp

**Comment by obadz** [comment]
I'll merge tomorrow if no objections and the above build succeeds.

**Comment by thoughtpolice** [comment]
This looks good to me (in particular tweaking the `foundationdb` dep and dropping the old versions). Thanks!

**Review by thoughtpolice — APPROVED** [review]

**Comment by obadz** [comment]
@GrahamcOfBorg build pdfmod

**Pull request merged**
