### PR TITLE
gcc7: Removed java as a target language

### PR DESCRIPTION
**Pull request by Synthetica9**
###### Motivation for this change
As discussed in  #39866

GCC6 is the last GCC release to support Java as a target language. I quote @gebner (https://github.com/NixOS/nixpkgs/pull/39866#discussion_r185733458):

> I think we should remove them completely. AFAICT the only place where we override enableJava et al. is in the gcj6 attribute (which uses gcc6).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Please rebase this on staging.

**Comment by Synthetica9** [comment]
Okay, that was definitely not what I wanted to do

**Comment by Synthetica9** [comment]
@xeji I did `git rebase -i --onto upstream/staging`, what did I do wrong?

**Comment by Synthetica9** [comment]
Okay, so I I think I have it correct now, here's what I did:

```
 ✘  ~/d/nixpkgs   gcc7-nojava   git checkout upstream/staging
Note: checking out 'upstream/staging'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at edc9258e6ec Merge pull request #39897 from r-ryantm/auto-update/dbus
 ~/d/nixpkgs  ➦ edc9258e6ec    git cherry-pick 5ece3d8f19e73a8bac9dc99e1409fbbb21e6ddbe
[detached HEAD 3641b35baee] gcc7: Removed java as a target language
 Date: Thu May 3 13:20:42 2018 +0200
 1 file changed, 8 insertions(+), 59 deletions(-)
 ~/d/nixpkgs  ➦ 3641b35baee    git checkout -b gcc7-nojava-fix 
Switched to a new branch 'gcc7-nojava-fix'
 ~/d/nixpkgs   gcc7-nojava-fix   git push origin gcc7-nojava-fix 
```

The result can be found here: https://github.com/NixOS/nixpkgs/compare/staging...Synthetica9:gcc7-nojava-fix

Should I PR that onto staging? (cc @xeji)

**Pull request closed without merging**
