### PR TITLE
Switch default llvm to 3.5

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
cc @vcunat

**Comment by vcunat** [comment]
I will test it, but it's not a blocker to merging this PR, as I see the mesa dependency is hard-coded to llvm34.

Related: if someone has an idea about activating RTTI generation for LLVM, it might help a lot. I did try defining ``REQUIRES_RTTI=1`` with llvm-3.4.2 as suggested by http://llvm.org/docs/Packaging.html, but I was still getting errors about missing typeinfo of LLVM symbols during link-time http://permalink.gmane.org/gmane.linux.distributions.nixos/15912

**Comment by vcunat** [comment]
Ah, llvm35 itself fails to build for me. I tried current master 038a837 + this PR on x86_64-linux (chrooted nixos).

```
Building CXX object
  CMakeFiles/cmTryCompileExec1439295879.dir/testCXXCompiler.cxx.o

  
  /nix/store/vyasynvcp9jpgbysifya5b4cjknqllb2-gcc-wrapper-4.8.4/bin/g++
  -stdlib=libc++ -o
  CMakeFiles/cmTryCompileExec1439295879.dir/testCXXCompiler.cxx.o -c
  /tmp/nix-build-llvm-3.5.0.drv-0/llvm/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx


  g++: error: unrecognized command line option '-stdlib=libc++'

  make[1]: ***
  [CMakeFiles/cmTryCompileExec1439295879.dir/testCXXCompiler.cxx.o] Error 1

  make[1]: Leaving directory
  `/tmp/nix-build-llvm-3.5.0.drv-0/llvm/build/CMakeFiles/CMakeTmp'

  make: *** [cmTryCompileExec1439295879/fast] Error 2
```

**Comment by vcunat** [comment]
BTW, llvm-3.5.1 is out already.

**Comment by shlevy** [comment]
@vcunat fixed the issue, testing the build locally now. I'll merge once it's working as the X dependency isn't an issue.

No idea about the RTTI stuff, @copumpkin or @gridaphobe?

Would be good to update to 3.5.1 but if there's not an immediate need I'd rather wait until the upcoming darwin churn has calmed down a bit and people aren't using long-term forks any more.

**Comment by vcunat** [comment]
Hmm, our current mesa version fails a test (lp_test_format) when built against llvm-3.5. I won't switch it for now.

**Comment by peti** [comment]
This change breaks all Haskell packages that rely on LLVM because version 3.5 is incompatible with current  versions of GHC: https://github.com/NixOS/nixpkgs/issues/6169.

Failing builds: 
 - http://hydra.cryp.to/build/536535/nixlog/1/raw
 - http://hydra.cryp.to/build/536650/nixlog/1/raw
 - http://hydra.cryp.to/build/536741/log/raw

**Pull request merged**
