### PR TITLE
Haskell: fix binrep package

### PR DESCRIPTION
**Pull request by raehik**
###### Description of changes

Fixes building one of my packages binrep.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
Hey @raehik thanks for your PR and taking over a maintainership!

1. `hackage-packages.nix` is completely autogenerated. To enter yourself as maintainer please enter yourself in the maintainers list in `hackage2nix-configuration/main.yaml` in the same directory. Use `maintainers/scripts/haskell/regenerate-hackage-packages.sh` after that to make sure the result is fine.
2. Please structure the commits a bit more precise, e.g.
    * `maintainers: add raehik`
    * `haskellPackages.binrep: Unmark broken`
    * `haskellPackages.binrep: Add binrep as maintainer`

**Comment by raehik** [comment]
Thanks @maralorn for all the help! Rewrote commits & messages as you said to.

**Comment by cdepillabout** [comment]
@ofborg build haskellPackages.binrep haskellPackages.strongweak haskellPackages.bytepatch

**Comment by cdepillabout** [comment]
@raehik Looks like ofborg is complaining that binrep is still failing to compile because of a version constraint on `refined`: https://github.com/NixOS/nixpkgs/pull/210212/checks?check_run_id=10590830926

Are you able to reproduce this error locally?

**Comment by raehik** [comment]
@cdepillabout yes - as I understand, this PR should wait until we get a Hackage bump, then rebase and should pass? I bumped locally and tested and all was well.

**Pull request merged**
