### PR TITLE
gst_all_1.gst-plugins-rs: 0.10.10 -> 0.10.11

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

GStreamer Rust plugins update. Mostly minor bug fixes: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/0.10.11/CHANGELOG.md#01011-2023-07-20

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
  - [x] x86_64-linux -> aarch64-linux (cross) (needs #245761, #244602, #245124, and #246138)
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
I just pushed a commit that makes the temp-fix from #239681 work on cross until the cargo-c issue is fixed upstream in gst-plugins-rs

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 245743` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>gst_all_1.gst-plugins-rs</li>
    <li>gst_all_1.gst-plugins-rs.dev</li>
    <li>mopidy-bandcamp</li>
    <li>mopidy-bandcamp.dist</li>
    <li>mopidy-iris</li>
    <li>mopidy-iris.dist</li>
    <li>mopidy-jellyfin</li>
    <li>mopidy-jellyfin.dist</li>
    <li>mopidy-local</li>
    <li>mopidy-local.dist</li>
    <li>mopidy-mopify</li>
    <li>mopidy-mopify.dist</li>
    <li>mopidy-mpd</li>
    <li>mopidy-mpd.dist</li>
    <li>mopidy-mpris</li>
    <li>mopidy-mpris.dist</li>
    <li>mopidy-muse</li>
    <li>mopidy-muse.dist</li>
    <li>mopidy-musicbox-webclient</li>
    <li>mopidy-musicbox-webclient.dist</li>
    <li>mopidy-notify</li>
    <li>mopidy-notify.dist</li>
    <li>mopidy-podcast</li>
    <li>mopidy-podcast.dist</li>
    <li>mopidy-scrobbler</li>
    <li>mopidy-scrobbler.dist</li>
    <li>mopidy-somafm</li>
    <li>mopidy-somafm.dist</li>
    <li>mopidy-soundcloud</li>
    <li>mopidy-soundcloud.dist</li>
    <li>mopidy-spotify</li>
    <li>mopidy-spotify.dist</li>
    <li>mopidy-subidy</li>
    <li>mopidy-subidy.dist</li>
    <li>mopidy-tidal</li>
    <li>mopidy-tidal.dist</li>
    <li>mopidy-tunein</li>
    <li>mopidy-tunein.dist</li>
    <li>mopidy-youtube</li>
    <li>mopidy-youtube.dist</li>
    <li>mopidy-ytmusic</li>
    <li>mopidy-ytmusic.dist</li>
  </ul>
</details>

**Review by Janik-Haag — APPROVED** [review]
LGTM; darwin probably works fine aswell since ofborg just timeouts.

**Comment by lilyinstarlight** [comment]
> LGTM; darwin probably works fine aswell since ofborg just timeouts.

Yep, I tested in on the community darwin builder already. Thank you!

**Comment by lilyinstarlight** [comment]
Manual backport is in #246276. I've marked it as draft for now so it can cook on master a bit and make sure no one yells about issues first

**Pull request merged**
