### PR TITLE
dotnet: cleanup; point dotnet-sdk alias to 5.0; remove unsupported SDKs

### LINKED ISSUE #112428: dotnet-sdk should point to the latest LTS
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

`nix search` name: dotnet-sdk

current version: 2.1.810
desired version: 3.1.11

###### Notify maintainers

maintainers: @kuznero

###### Note for maintainers

dotnet-sdk should be updated to 2.1.24, 3.1.11 and 5.0.2, respectively.

More importantly, I think Microsoft now recommends to use version 3 as the default LTS. So, perhaps `nixpkgs.dotnet-sdk` should point to that version instead (if not to 5.0 directly).

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- point dotnet-sdk alias to 5.0
- cleanup by removing unsupported dotnet SDKs (2.1 and 3.0)
- fixes https://github.com/NixOS/nixpkgs/issues/112428

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by samuela — APPROVED** [review]

**Comment by prusnak** [comment]
@kuznero What do you think? Do you like the change?

**Comment by prusnak** [comment]
@IvarWithoutBones what do you think?

**Review by IvarWithoutBones — CHANGES_REQUESTED** [review]
Thanks for the contribution! I really appreciate it. Just a few minor issues:

The manual does stilllseem to mention `netcore` a few times. `nixpkgs-review` Also seems to fail on `evenstore`, is that an regression?

Result of `nixpkgs-review pr 139571` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>eventstore</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>dotnet-aspnetcore</li>
    <li>dotnet-runtime (dotnetCorePackages.runtime_5_0)</li>
    <li>dotnet-sdk</li>
    <li>dotnetCorePackages.runtime_3_1</li>
    <li>wasabiwallet</li>
  </ul>
</details>

**Review by IvarWithoutBones — APPROVED** [review]
LGTM :heart:

**Pull request merged**
