### PR TITLE
cosign: 1.2.0 -> 1.2.1

### PR DESCRIPTION
**Pull request by LeSuisse**
###### Motivation for this change

https://github.com/sigstore/cosign/releases/tag/v1.2.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cosign</li>
  </ul>
</details>

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 138781` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cosign</li>
  </ul>
</details>

**Review by fabaff — COMMENTED** [review]
- [x] package builds (see https://github.com/NixOS/nixpkgs/pull/138781#issuecomment-923777525)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-138781]$ ./results/cosign/bin/cosign version
GitVersion:    (devel)
GitCommit:     unknown
GitTreeState:  unknown
[...]
```

Change looks good to me. The `ldflags` no longer set the version. Not sure if that's a new issue.

**Comment by LeSuisse** [comment]
>Change looks good to me. The `ldflags` no longer set the version. Not sure if that's a new issue.

It looks like it is something we missed in the 1.1.0 release: https://github.com/sigstore/cosign/commit/f83218b01472c43ba313c09166381e107b08598d

I updated the PR to take it into account.

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 138781` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cosign</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
