### PR TITLE
python3Packages.black: 19.03b0 -> 19.10b0

### PR DESCRIPTION
**Pull request by kwohlfahrt**
###### Motivation for this change

Version bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @sveitser

### CODE REVIEW

**Comment by jonringer** [comment]
quite a bit of regressions, please look at the failed packages, pytest-black is the most important:

```
[10 built (8 failed), 186 copied (436.3 MiB), 184.2 MiB DL]
error: build of '/nix/store/ivl1whsa1c6acsq6hnbf854cndwl054m-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/73053
1 package are marked as broken and were skipped:
bareos

26 package failed to build:
ceph ceph-client datasette fava flexget libceph mnemosyne python37Packages.bugseverywhere python37Packages.cheroot python37Packages.cherrypy python37Packages.portend python37Packages.pyalgotrade python37Packages.pytest-black python37Packages.ws4py python37Packages.zerobin python38Packages.bugseverywhere python38Packages.cheroot python38Packages.cherrypy python38Packages.datasette python38Packages.portend python38Packages.pyalgotrade python38Packages.pyls-black python38Packages.pytest-black python38Packages.ws4py python38Packages.zerobin sambaFull

8 package were build:
git-revise python37Packages.black python37Packages.pyls-black python37Packages.stumpy python37Packages.uarray python38Packages.black python38Packages.git-revise python38Packages.uarray
```

**Comment by kwohlfahrt** [comment]
`pytest-black` pins specifically `19.03b`. There's a (stale) PR upstream but no movement in months: https://github.com/shopkeep/pytest-black/pull/29

`pytest-black` pins the version for reasons to do with Pipenv not playing nice with prerelease packages. I've patched this, since it shouldn't affect us - should I also push for this upstream?

**Comment by kwohlfahrt** [comment]
@jonringer could you have another look? With the proposed patches, none of the remaining failures look black-related. I will open a PR upstream for `portend`.

**Comment by jonringer** [comment]
failures seem to be unrelated to package bump

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM

failures are unrelated to this package bump, I'm making PRs to fix them
```
[32 built (7 failed), 587 copied (2080.0 MiB), 487.4 MiB DL]
error: build of '/nix/store/p5jkg3axp157jw1yvw06wwdff1skj8rq-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/73053
1 package are marked as broken and were skipped:
bareos

4 package failed to build:
datasette fava python38Packages.datasette python38Packages.pyls-black

30 package were build:
ceph ceph-client flexget git-revise libceph mnemosyne python37Packages.black python37Packages.bugseverywhere python37Packages.cheroot python37Packages.cherrypy python37Packages.portend python37Packages.pyalgotrade python37Packages.pyls-black python37Packages.pytest-black python37Packages.stumpy python37Packages.uarray python37Packages.ws4py python37Packages.zerobin python38Packages.black python38Packages.bugseverywhere python38Packages.cheroot python38Packages.cherrypy python38Packages.git-revise python38Packages.portend python38Packages.pyalgotrade python38Packages.pytest-black python38Packages.uarray python38Packages.ws4py python38Packages.zerobin sambaFull
```

**Pull request merged**
