### PR TITLE
replace use of `which` with `command -v` in i3 scripts

### PR DESCRIPTION
**Pull request by anderspapitto**
I haven't tested it, but it is modeled off of https://github.com/bjornfor/nixpkgs/commit/74d631502439ec4e17182e0e812eb030e729dc6c

### CODE REVIEW

**Comment by cillianderoiste** [comment]
@anderspapitto if you haven't tested this, what issue does it solve?

**Comment by peti** [comment]
It would be really good to test whether these changes actually work, i.e. the commit message should describe the problem that currently exists. As it is, applying this patches comes with the clear risk of unintended consequences of applying it, but there's no clear advantage to be gained.

**Comment by anderspapitto** [comment]
The motivation for this patch is that when using i3, if the "which" package is not installed (at system or user level) the i3-sensible-* programs will fail. As a result of this, the keybinding for "spawn a terminal" will have no effect, which is pretty confusing until you figure it out.

An alternative approach would be to make i3 depend on "which" at runtime. However I followed the lead of the linked patch in preferring to remove the dependency.

I have also since tested this patch. I am not sure how to have the systemwide services.xserver.windowManager use my local i3 definition, so instead I did this

# built and installed my modified i3
nix-env -i i3 -f /path/to/my/nixpkgs/checkout/default.nix
# uninstalled which
sudo sed -i 's/which/# which/' /etc/nixos/configuration.nix
sudo nixos-rebuild switch
# tested that i3-sensible-terminal and family still work without which
i3-sensible-terminal
# uninstalled my modified i3
nix-env -e i3
# confirmed that i3-sensible-terminal now fails (without my patch)
i3-sensible-terminal

**Comment by peti** [comment]
Thanks a lot for the detailed description of the change!

**Pull request merged**
