### PR TITLE
scaff: init at 0.1.1

### PR DESCRIPTION
**Pull request by jD91mZM2**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ckauhaus** [comment]
@GrahamcOfBorg build scaff

**Comment by jD91mZM2** [comment]
Is a bump allowed?

**Comment by ckauhaus** [comment]
Of course - go ahead

**Comment by ckauhaus** [comment]
What bugs me a bit is potential pkgs tree bloat. The diff is quite huge for such a simple tool.

**Comment by jD91mZM2** [comment]
Understandable! Feel free to close this if you don't see it fitting in nixpkgs :)

**Comment by ckauhaus** [comment]
Even better would be to get it in with less nix code. Is there a possibility to use alternative Rust build support?

**Comment by jD91mZM2** [comment]
Sure! It just takes longer to build, but it's definitely possible. Will do ASAP :)

**Comment by jD91mZM2** [comment]
Finally, done. Apologies for the delay :)

**Comment by ckauhaus** [comment]
@jD91mZM2 The pkg definition is missing a metadata section.

**Comment by jD91mZM2** [comment]
Oh, oops, sorry

**Comment by ckauhaus** [comment]
@jD91mZM2 ping - any news here? Just add a metadata section and it's done.

**Comment by jD91mZM2** [comment]
Oh, I forgot this, thanks for the ping!

**Pull request merged**
