### PR TITLE
Dlang update

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Updating dmd, dtools and dub to newest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
@GrahamcOfBorg build ldc

**Comment by ThomasMader** [comment]
@GrahamcOfBorg build dmd dtools dub

**Comment by Mic92** [comment]
Did you choose the wrong branch here? `NixOS:staging-18.03`

**Comment by ThomasMader** [comment]
I did it on purpose because there is an error somewhere in the c environment preventing dmd to build properly. Since it works on 18.03 I figured it might be better to choose that branch to show everything is working.

**Comment by Mic92** [comment]
but we cherry-pick from master to release branches. Not the other way around.

**Comment by ThomasMader** [comment]
Closing this and creating a new PR based on master.

**Pull request closed without merging**
