### PR TITLE
greenclip: 2.0.1 -> 3.0.2

### PR DESCRIPTION
**Pull request by Tomahna**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/43684
https://github.com/erebe/greenclip/issues/35

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
This file is auto-generated btw, it might still be okay though

**Review by peti — CHANGES_REQUESTED** [review]
This file is generated automatically. Please do not edit it; all you changes will be lost. Note the comment at the top.

**Comment by Tomahna** [comment]
Okay. Is there an action required to upgrade the package then ?

**Comment by peti** [comment]
No action is required. The new version will appear in `master` in a few hours.

**Comment by peti** [comment]
That is a different error. `wordexp-0.2.0.0` does not compile. I'd guess it has trouble coping with ghc 8.4.3. It's probably best to report that issue to upstream, too.

**Pull request closed without merging**
