### PR TITLE
liberation_ttf_v2: 2.00.4 -> 2.1.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

Version update.

Github is showing bigger diff than necessary, because I renamed `pkgs/data/fonts/redhat-liberation-fonts/default.nix` to  `pkgs/data/fonts/liberation-fonts/default.nix`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

Seems bot had a hiccup. Sorry!

**Review by 7c6f434c — APPROVED** [review]
Update looks fine, not merging immediately because rebuild report from ofborg looks strange

**Comment by 7c6f434c** [comment]
@ofborg eval

**Comment by 7c6f434c** [comment]
@grahamc Any idea why, say, `cvc4` is shown as rebuilt? Doesn't depend on either version of Liberation fonts on my system from `master` (and hopefully it shouldn't…)

It is true that OpenJDK and LibreOffice do depend on fonts at the build time.

**Comment by 7c6f434c** [comment]
@prusnak maybe retarget this to `staging`?

**Comment by prusnak** [comment]
retargeted

**Pull request merged**
