### PR TITLE
hydra-unstable: 2020-09-02 -> 2020-10-20

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

* Updates `nixUnstable` and `hydra-unstable` to their latest revisions:

  `hydra-unstable` would require at least https://github.com/NixOS/hydra/pull/815 to fix declarative jobsets. Also applying https://github.com/NixOS/hydra/pull/818 to get it working with the very latest `nixUnstable` (instead of just the one in hydra's `flake.lock`)

* Removed the upgrade path from older Hydra versions due to a schema change:

   Originally implemented in https://github.com/NixOS/nixpkgs/pull/83600 this was used to guide users of Hydra through the DB migration that was necessary after some changes back in February.

  (**Note:** this should **NOT** be backported to 20.09!)

**Note:** I didn't add support for LDAP authentication for Hydra yet, if someone wants to help out, that would be great :) 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
@worldofpeace @jonringer FYI while this PR itself doesn't have to land in 20.09, I'd like to point out that at least https://github.com/NixOS/hydra/pull/815 should be applied on top of current `hydra-unstable` to fix declarative jobsets.

**Comment by jonringer** [comment]
@GrahamcOfBorg test hydra

**Comment by Ma27** [comment]
Oh and btw before merging this, one should take a look at https://github.com/NixOS/hydra/pull/818 which is applied on top before merging :D

**Comment by Ma27** [comment]
Now that  NixOS/hydra#815  is merged, this should be good to go :)

**Comment by Ma27** [comment]
@jonringer I think this should be good to go now :)

**Comment by Ma27** [comment]
@edolstra I'd be in favor of porting this to 20.09 as this contains a fix for declarative jobsets. To achieve this, I'd have to backport your last `nixUnstable` bump as well. Are you fine with that?

**Comment by edolstra** [comment]
@Ma27 Yes, I've just cherry-picked the `nixUnstable` bump.

**Comment by Ma27** [comment]
Ahh great, thanks! :)

**Comment by Ma27** [comment]
Ported to 20.09 as 3095f9cccfbae4a788771e87329fd432c69781d9.

**Pull request merged**
