### PR TITLE
Replace obsolete Haskell code with Haskell NG

### PR DESCRIPTION
**Pull request by peti**
This commit removed the old Haskell infrastructure in lieu of the next generation code. See https://github.com/NixOS/nixpkgs/issues/4941 for an overview of existing NG documentation. The posting http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015591.html, in particular, contains helpful instructions on how to migrate.

Test builds will run at http://hydra.nixos.org/jobset/nixpkgs/pr-7465.

### CODE REVIEW

**Comment by shlevy** [comment]
:+1:

**Comment by MP2E** [comment]
:+1: Glad to see we're getting ready to switch!

**Comment by domenkozar** [comment]
@peti

**Comment by domenkozar** [comment]
@peti do you also plan to update `nixpkgs` manual with some documentation (and delete stuff from wiki)?

**Comment by peti** [comment]
Yes, I'll document the new code as part of this PR. We really need a manual for this stuff.

**Comment by domenkozar** [comment]
\o/

**Comment by robinbb** [comment]
Must 'cabal2nix' be modified to use this?

**Comment by peti** [comment]
@robinbb, `haskellngPackages.cabal2nix` refers to version 2.x of the tool, which generates expressions suitable for use with Haskell NG.

**Comment by robinbb** [comment]
Excellent. Works for me! Thank you, @peti.

**Comment by jraygauthier** [comment]
+1 Very nice job! Good decision.

**Comment by peti** [comment]
The patch set is complete and has been tested. I'll merge soon, probably in the first couple of days in May.

**Comment by pSub** [comment]
:beers:

**Comment by domenkozar** [comment]
@peti can we now disable haskell-updates job on hydra?

**Comment by peti** [comment]
@domenkozar, that job provides binaries for our users. We can remove it if we build those binaries as part of release.nix instead.

**Pull request merged**
