### PR TITLE
Add GHC 8.6.4

### PR DESCRIPTION
**Pull request by pSub**
###### Motivation for this change

Add GHC 8.6.4 to release 19.03. This release fixes a bunch of issues (eg. https://github.com/haskell/haddock/issues/979)

This PR cherry-picks commit 68be6bbc31351a4cf5b6431d746dc390ed29c16c.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pSub** [comment]
@GrahamcOfBorg eval

**Comment by vaibhavsagar** [comment]
Can we also use the latest Stackage LTS that includes GHC 8.6.4: https://www.stackage.org/lts-13.12?

**Comment by pSub** [comment]
Sounds reasonable. @peti do you agree?

**Comment by peti** [comment]
I will synchronize the complete Haskell code in the release branch with master in the next couple of days. So merging this PR is fine albeit probably unnecessary.

**Pull request merged**
