### PR TITLE
reckon: 0.6.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

Particularly nice improvements:
* [fail on unknown account](https://github.com/cantino/reckon/pull/102)
  in interactive mode
* [use - to read from stdin](https://github.com/cantino/reckon/pull/98)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raboof** [comment]
Result of `nixpkgs-review pr 112292` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>reckon</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112292` at e3c67f05 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/5f1b35696dccde5bcb393de87d574327">reckon</a></li></li>
  </ul>
</details>
<details>
  <summary>1 warning produced:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/tools/text/reckon/default.nix:11:3:
```
   |
11 |   installPhase = let
   |   ^
```
</li>
  </ul>
</details>

**Comment by raboof** [comment]
>       `installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Fair enough, updated (though that was already there before this PR :) )

**Comment by SuperSandro2000** [comment]
> Result of `nixpkgs-review pr 112292` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

This is not that useful because it does not validate if you used the right hashes.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112292` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>reckon</li>
</ul>
</details>

**Comment by raboof** [comment]
> > Result of `nixpkgs-review pr 112292` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> This is not that useful because it does not validate if you used the right hashes.

I'm not sure what you mean here?

Thanks for the merge!

**Pull request merged**
