### PR TITLE
treewide/nixos: remove `with lib;` part 12

### PR DESCRIPTION
**Pull request by Stunkymonkey**
## Description of changes

part of #208242

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
Everything looks good. I'm planning on merging after running a few nixosTests.

**Comment by vcunat** [comment]
Again, breaking things.
```
       error: undefined variable 'optional'
       at /nix/store/1jvzqyay4rb8bqyv0jbdwk9wb0frrhfs-source/nixos/modules/services/x11/desktop-managers/xfce.nix:130:10:
          129|     ] # TODO: NetworkManager doesn't belong here
```

**Comment by philiptaron** [comment]
Damn it! Ugh.

**Comment by K900** [comment]
I'm going to ask [the same question I've asked before](https://github.com/NixOS/nixpkgs/pull/335647#issuecomment-2532140116):

> How many of these do we need to explode to realize that we need better testing?

**Comment by Ma27** [comment]
Now that I'm thinking again about this: can somebody explain to me why we're doing it like this in the first place?

Like, new usages of the same pattern will come up so I think the time people "invested" on that would be way better served if tooling was developed that does this reliably and can be used by contributors easily on their new changes (and by maintainers on their code).

Fixing behind everyone's back is something that we'll never be done with given that new usages will arise every now and then (and yes, I consider it a horrible contribution experience if we'd actually block PRs by asking people to... idk... remove `with`s or add spaces between `{}` or what not).

**Comment by vcunat** [comment]
There were more of them, e.g. certmgr.  A suspect list:
https://hydra.nixos.org/eval/1810800#tabs-removed

**Comment by philiptaron** [comment]
I'm clicking the revert button.

**Comment by philiptaron** [comment]
Reverted in https://github.com/NixOS/nixpkgs/pull/369795

**Comment by vcunat** [comment]
Oh, that hydra diff contains multiple of these "remove `with lib;`" pull requests, e.g. `nixosTests.tor` was broken by another one.

**Comment by vcunat** [comment]
Actually, all of the stuff detected by trunk-combined job removals was from other PRs or fixed in the meantime 🤦🏽  as we can see from the eval after merging the revert.

**Comment by philiptaron** [comment]
> Actually, all of the stuff detected by trunk-combined job removals was from other PRs or fixed in the meantime 🤦🏽 as we can see from the eval after merging the revert.

Sigh. I am trying to learn the "mass-evaluate-all-NixOS-tests" strategy that Mic92 [alluded to in the previous PR](https://github.com/NixOS/nixpkgs/pull/335647#issuecomment-2532853130). It took me a few tries to understand the output and how to discern something was already broken vs. newly broken, but I think I got it dialed in.

I've fixed everything that I found in this PR:

- https://github.com/NixOS/nixpkgs/pull/370042

There may be more latent issues for modules without a NixOS test.

**Comment by vcunat** [comment]
Laziness can bite us here?

**Comment by vcunat** [comment]
I suppose I'll make the `nixos-unstable` channel avoid these in-between commits where several services had evaluation issues.

**Pull request merged**
