### PR TITLE
vimPlugins: add bat.vim syntax highlighting colorscheme

### PR DESCRIPTION
**Pull request by voidzero**
###### Description of changes

This PR is to request inclusion of [bat.vim](https://github.com/jamespwilliams/bat.vim), a syntax highlighting plugin for Vim, inspired by the default highlighting of the [bat](https://github.com/sharkdp/bat) command-line tool.

I am not experienced with generating PRs. Please be gentle. Thank you for your consideration of this plugin. One additional question: can this also be added to 22.11?

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
instead of adding the plugin manually, please run the update script with `--add jamespwilliams/bat.vim` instead

**Comment by voidzero** [comment]
@figsoda oh, I missed that, sorry. Do I need to close this PR and create a new one, or can I update this one?

**Comment by figsoda** [comment]
No worries! You can update this one as long as you keep the git history clean with force pushes

**Comment by voidzero** [comment]
Ok, should I use `git revert`? If so, how exactly? Because what I'm trying only gives me errors.

**Comment by figsoda** [comment]
You can do `git reset --hard HEAD~2`, run the update script again with `--add jamespwilliams/bat.vim` and then `git push --force`

**Comment by voidzero** [comment]
Ohh I see. I understood that as "do /not/ use git `push --force`" :sweat_smile: my bad. Updating now. Thanks for your patience.

**Comment by voidzero** [comment]
There we go.

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 209535` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lua54Packages.sqlite</li>
  </ul>
</details>
<details>
  <summary>77 packages built:</summary>
  <ul>
    <li>lua51Packages.sqlite</li>
    <li>lua52Packages.sqlite</li>
    <li>lua53Packages.sqlite</li>
    <li>luajitPackages.sqlite</li>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aniseed</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.bat-vim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.com-cloudedmountain-ide-neovim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.copilot-lua</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lsp-zero-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-snippy</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.vim-abolish</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-tmux-navigator</li>
    <li>vimPlugins.which-key-nvim</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]
lgtm, I will merge once CI passes

**Comment by voidzero** [comment]
@figsoda tyvm. Can this also be added to 22.11?

**Comment by figsoda** [comment]
opened a backport pr: https://github.com/NixOS/nixpkgs/pull/209560

**Pull request merged**
