### PR TITLE
nim: 2.0.4 -> 2.0.6

### PR DESCRIPTION
**Pull request by evelant**
## Description of changes

Update nim from 2.0.4 to 2.0.6

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ehmry** [comment]
This bit from the release notes is odd…
> NOTE: If your program uses threads (--threads:on became the default in the 2.0.x line) please also use the -d:useMalloc switch. This problem will be fixed in a future release, sorry for the inconvenience.

**Comment by marcusramberg** [comment]
> This bit from the release notes is odd…
> 
> > NOTE: If your program uses threads (--threads:on became the default in the 2.0.x line) please also use the -d:useMalloc switch. This problem will be fixed in a future release, sorry for the inconvenience.

Yeah, that is a bit worrying.

**Comment by marcusramberg** [comment]
Result of `nixpkgs-review pr 321092` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>chawan</li>
    <li>eriscmd</li>
    <li>eriscmd.bin</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>base45</li>
    <li>c2nim</li>
    <li>emocli</li>
    <li>hottext</li>
    <li>min</li>
    <li>mosdepth</li>
    <li>nim (nim2)</li>
    <li>nim-atlas</li>
    <li>nim-unwrapped-2</li>
    <li>nim_builder</li>
    <li>nim_lk</li>
    <li>nimble</li>
    <li>nimdow</li>
    <li>nimlangserver</li>
    <li>nimlsp</li>
    <li>nimmm</li>
    <li>nitch</li>
    <li>nitter</li>
    <li>nrpl</li>
    <li>promexplorer</li>
    <li>snekim</li>
    <li>swaycwd</li>
    <li>syndicate_utils</li>
    <li>tridactyl-native</li>
    <li>ttop</li>
  </ul>
</details>

**Comment by pbsds** [comment]
2.0.8 is out https://nim-lang.org//blog/2024/07/03/version-208-released.html

**Comment by xTrayambak** [comment]
It's best that we directly skip to 2.0.8 instead because it claims to fix a lot of problems with 2.0.6 that were caused by a combination with Nim's default allocator and threading support.

**Comment by ehmry** [comment]
Skipped by #326293

**Pull request closed without merging**
