### PR TITLE
nss: refactor into latest and esr

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
This should ease maintenance of firefox while having a supported version for everything else, so the mass rebuilds can go through staging and nss_latest can just be bumped and both can be backported, on the release and one to staging.

cacert still uses nss_latest, so we always have an up to date certificate store.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
> **cacert** still uses nss_latest, so we always have an up to date certificate store.

That's a little confusing sentence.  It has a separately controlled version, and I think it only makes sense to update when the CA list changes, as seen on https://wiki.mozilla.org/NSS:Release_Versions

**Comment by vcunat** [comment]
- `firefox/common.nix`, `thunderbird` and similar: perhaps use the ESR version of NSS for ESR versions of these packages?  My understanding is that the ESR NSS is created primarily to support those, even though I don't recall any issues from us using newer NSS in there.
- I'm not sure what version requirements are there in other packages, but I guess we'll see when we attempt to rebuild them &ndash; and switch to `_latest` where needed.  The most important dependents are chromium- and electron-based, perhaps?

**Comment by ajs124** [comment]
> > **cacert** still uses nss_latest, so we always have an up to date certificate store.
> 
> That's a little confusing sentence. It has a separately controlled version, and I think it only makes sense to update when the CA list changes, as seen on https://wiki.mozilla.org/NSS:Release_Versions

Yes, totally. What I meant by that is that the excellent cacert update script already checks if `nss_latest` is available and uses it, if it is. AFAIR it also checks if the output changed (or something like that) so you wouldn't even need to check the wiki page to know if something changed.

**Comment by ajs124** [comment]
> * `firefox/common.nix`, `thunderbird` and similar: perhaps use the ESR version of NSS for ESR versions of these packages?  My understanding is that the ESR NSS is created primarily to support those, even though I don't recall any issues from us using newer NSS in there.
> 
>     * I'm not sure what version requirements are there in other packages, but I guess we'll see when we attempt to rebuild them – and switch to `_latest` where needed.  The most important dependents are chromium- and electron-based, perhaps?

Does chromium even use nss? When I looked into the package I only saw the DRM plugin using it.
`electron` I seem to remember though. I think I already broke something there once, when I did something with nss.

**Comment by mweinelt** [comment]
@ofborg eval
@ofborg test firefox

**Review by mweinelt — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says `firefox` stopped building on `staging` after eb9c616c79596c9ff43ec9e7ced46c4739a16047 `nss_latest: 3.76.1 -> 3.77`:

```
$ nix build -f. firefox
...
In file included from /build/firefox-98.0.2/security/certverifier/CertVerifier.cpp:14:
/build/firefox-98.0.2/security/manager/ssl/CSTrustDomain.h:50:28: error: no type named 'SignedDigest' in namespace 'mozilla::pkix'
      const mozilla::pkix::SignedDigest& signedDigest,
            ~~~~~~~~~~~~~~~^
...
```

**Comment by mweinelt** [comment]
Can you retest against firefox 99.0?

**Comment by trofi** [comment]
`firefox-99` seems to fail in a very similar way:

```
In file included from Unified_cpp_certverifier0.cpp:47:
/build/firefox-99.0/security/certverifier/OCSPVerificationTrustDomain.cpp:63:11: error: unknown type name 'SignedDigest'
    const SignedDigest& aSignedDigest, Input aSubjectPublicKeyInfo) {
          ^
/build/firefox-99.0/security/certverifier/OCSPVerificationTrustDomain.cpp:74:11: error: unknown type name 'SignedDigest'
    const SignedDigest& aSignedDigest, Input aSubjectPublicKeyInfo) {
          ^
```

**Comment by ajs124** [comment]
I guess eb9c616c79596c9ff43ec9e7ced46c4739a16047 should be alright to revert and just re-revert when Firefox 100, which will require it, arrives?

**Comment by mweinelt** [comment]
Reverted in 79a5b548cc48770c062a6a60503628017ea0855e.

**Comment by vcunat** [comment]
None of these updates needs to get to master fast, right?  (ATM they're not included in the current staging-next iteration.)

**Comment by mweinelt** [comment]
Bump reinstated in #171332 and bumped further to 3.78.

**Pull request merged**
