### PR TITLE
gitlab: 12.10.8 -> 13.0.3

### PR DESCRIPTION
**Pull request by globin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @petabyteboy @flokli

### CODE REVIEW

**Comment by globin** [comment]
@GrahamcOfBorg test gitlab

**Review by talyz — CHANGES_REQUESTED** [review]
Great work! I've done a few manual tests and it seems to work well.

Maybe you could add some comments on the changes that aren't just straight up version upgrades? Like the `gitaly` `gitlab-shell` config moving into `gitaly.toml` with a link to  https://gitlab.com/gitlab-org/gitaly/-/issues/2182. Also, did you make changes to the `upgrade.py` script without commiting them or does it just work now?

**Comment by globin** [comment]
The update script took ages but seems to work.

I just checked how the variables are passed in the gitaly code, didn't see the issue.

**Comment by talyz** [comment]
Okay, interesting.

Ah, I see. Well, it's good to document it for future reference anyway, so I would still suggest adding the link or your own observation. :)

**Comment by talyz** [comment]
[13.0.4](https://about.gitlab.com/releases/2020/06/03/critical-security-release-13-0-4-released) is out. Can you bump this? :)

**Comment by flokli** [comment]
@globin can you address the changes?

I realized there's another security update, 12.10.9, for which I opened https://github.com/NixOS/nixpkgs/pull/89435, so this might need a rebase afterwards.

**Comment by globin** [comment]
very short on time right now,  feel free to take over, also ping @WilliButz, @lheckemann

**Comment by talyz** [comment]
@globin No worries, I'll give it a go today.

**Comment by talyz** [comment]
I couldn't push any changes to this PR, so I opened a new one (#89480).

**Comment by flokli** [comment]
Let's close this one then.

**Pull request closed without merging**
