### PR TITLE
nixos-generate-config: encrypt swap partitions by default

### PR DESCRIPTION
**Pull request by obadz**
###### Motivation for this change

Modify `nixos-generate-config` so that swap partitions are encrypted by defaults, and use a UUID/label insensitive addressing.

Swap Encryption is really the sensible default given the amount of sensitive information that RAM can contain. See also #8277.

cc @edolstra 
###### Things done

Tested with:

```
nix-build '<nixpkgs/nixos>' -A config.system.build.nixos-generate-config &&
  ./result/bin/nixos-generate-config --dir .
```
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aszlig** [comment]
:-1: on this, because first of all this breaks hibernation and second, I'd only make it default if we have *sufficient* NixOS VM test(s) for that. For example which configuration gets generated if you already use LVM or dmcrypt? For these configurations you usually have (or at least *should* have) an encrypted swap device that's using either a derived or a different keyslot for the swap device which you can use to unlock the machine after hibernation.

**Comment by obadz** [comment]
Preserving the hibernation feature for the (I suspect) small subset of users that use it would be nice and I'd certainly be happy to see improvements that make this work (I don't use it myself so can't really work on that).

However, I don't think it should come in the way of what I believe is an important security improvement.

Until the feature that enables hibernation users to use encrypted swap spaces, they'll have to decide whether they'd rather take the security risk or if they need the feature more in which case they can toggle `randomEncryption` to `false`.

**Comment by aszlig** [comment]
@obadz: Well, we should have an option in the template `configuration.nix` then for users to be aware of this and also turn it off.

**Comment by obadz** [comment]
@aszlig: what would this option do?

**Comment by aszlig** [comment]
Either override the `randomEncryption` option with false or note users to set their passphrases if they want hibernation.

**Comment by obadz** [comment]
I don't really like the option that overrides `randonEncryption` to false, but if there is a way to disable the hibernation feature, we could have an assertion that validates that either hibernation is disabled or swaps aren't encrypted?

**Comment by ocharles** [comment]
It sounds like this change is too contenious to be a pull request at the moment, perhaps an RFC should be opened first?

**Comment by primeos** [comment]
(triage) Should an RFC be opened for this? I also think that this would be a good idea but I'm not sure if it would be worth the extra effort. But if we can fix all/most of the issues I don't think we would need an RFC.

> Swap Encryption is really the sensible default given the amount of sensitive information that RAM can contain.

Do we have any sources on this? I don't really think that this is wrong but IIRC programs like OpenSSH, GnuPG, ... should prevent sensitive information (like keys or passwords) from getting swapped so that it actually shouldn't be that bad (but I might be very wrong about this...). Also I'd say that this only makes sense with at least an encrypted home partition and on a fully encrypted system (e.g. via LVM) the swap should already be encrypted and we would loose performance by encrypting it twice (imho we should at least put a note inside the manual that the swap shouldn't be on an already encrypted LVM-VG/PV).

> :-1: on this, because first of all this breaks hibernation

IMHO we should solve that as well, at least by placing a comment in the config file (and in the install part manual).

> I'd only make it default if we have sufficient NixOS VM test(s) for that.

:+1: - I already experienced two problems with encryption (due to advanced use-cases tho). It might easily break some setups in unexpected ways.

Another possible problem could be the performance on old/low-end systems or systems with very fast SSDs (on my system the latter shouldn't be a problem (theoretically) but it could be on other systems).

**Comment by arianvp** [comment]
(triage) since this hasnt moved in over 2 years, shall we close this ?

**Comment by c0bw3b** [comment]
No consensus to make swap encryption the default.

**Pull request closed without merging**
