### PR TITLE
svgbob: fix build

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

See https://hydra.nixos.org/build/102480738

Bumping to latest version (which is 0.4.2 according to Cargo.lock) fixes
the build error. As no dependency changes happened, cargoSha256 doesn't
need to be updated.

ZHF #68361

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by marsam — APPROVED** [review]
Thanks!

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM (no releases tagged on GitHub :( )
executable works

```
[4 built, 4 copied (516.3 MiB), 186.1 MiB DL]
https://github.com/NixOS/nixpkgs/pull/70159
1 package were build:
svgbob
```
```
[nix-shell:~/.cache/nix-review/pr-70159]$ nix path-info -Sh ./results/svgbob
/nix/store/rpw4859ncxi5933aqkgjhrqd6wm1lxqq-svgbob-0.4.2          28.3M
```

**Comment by jonringer** [comment]
I'm not really sure of the proper process to do a backport :( @Ma27

**Comment by Ma27** [comment]
Backported as 2fc4fabd6cf6a6ca5db6fe77c8cb6435cb9d4de8.
I usually do `git cherry-pick -x <commit-id>` and push this to release-19.09 after testing :)

**Pull request merged**
