### PR TITLE
nginx: update to 1.18.0

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update nginxStable and ngiunxMainline to 1.18.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg test nginx nginx-etag nginx-pubhtml nginx-sso

**Comment by Izorkin** [comment]
cc @flokli @aanderse @Mic92 @delroth @jtojnar @danbst

**Comment by jtojnar** [comment]
Changes looking fine: https://nginx.org/en/CHANGES-1.18

**Comment by Izorkin** [comment]
@GrahamcOfBorg test nginx nginx-etag nginx-pubhtml nginx-sso nghttpx

**Comment by Izorkin** [comment]
@GrahamcOfBorg test nghttpx

**Comment by Izorkin** [comment]
@GrahamcOfBorg build nginxStable nginxMainline

**Comment by flokli** [comment]
Ran some tests locally as well. Let's merge this in - thanks!

**Pull request merged**
