### PR TITLE
fwupd: 1.9.12 -> 1.9.13

### PR DESCRIPTION
**Pull request by r-vdp**
## Description of changes

Changelog: https://github.com/fwupd/fwupd/releases/tag/1.9.13

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by amaxine — APPROVED** [review]
Changes look good, thanks.

**Review by MinerSebas — COMMENTED** [review]
This should probebly also include a
```
imports = [(mkRenamedOptionModule [ "services" "fwupd" "enableTestRemote" ] [ "services" "fwupd" "daemonSettings" "TestDevices" ])];
```

**Comment by r-vdp** [comment]
> This should probebly also include a
> ```
> imports = [(mkRenamedOptionModule [ "services" "fwupd" "enableTestRemote" ] [ "services" "fwupd" "daemonSettings" "TestDevices" ])];
> ```

No one should be using this option, it's only useful for automated tests and its only usage site should be in the NixOS VM test.

This is not the setting that you use to enable the lvfs-testing remote, you'd use `extraRemotes` for that.

So I don't think it's necessary to maintain backwards compatibility for this.

**Comment by qbit** [comment]
This broke my config as I was infact using that option :P

**Comment by qbit** [comment]
I don't think you can ever assume an option that was visible via search.nixos.org isn't being used.

https://github.com/qbit/xin/commit/9afe5099ebdf620e7426976d2cfdc9b00296c71e

**Comment by amaxine** [comment]
It is however fair to say that no one's system will be actually broken by this removal, and also that the two options aren't equivalent - except in purpose for running tests 😅

Is it possible to hide options from the manual? This should be "internal only", if such a concept exists in nix.

**Comment by r-vdp** [comment]
Hmm, yeah, the option should've been labelled as internal actually, so that it doesn't show up in the option search.

@qbit you're using this because you're running tests against fwupd? I'd suggest that you use the newly added option in the fwupd config to enable all the testing stuff then, does that work for you?

**Comment by qbit** [comment]
I had it set because the Framework 13 firmware was in beta at the time. Then it just stuck there until now.

I don't personally need it now - but [others are indeed using it](https://github.com/search?q=lang%3Anix+enableTestRemote&type=code) so likely there needs to be a migration path that just doesn't cause a "this option doesn't exist" error.

**Comment by amaxine** [comment]
@qbit that option doesn't enable the lvfs-testing remote, it's used for providing fake real updates to fake devices to test fwupd works. I'm not sure what migration path would even make sense to provide...

See the further up comment by @r-vdp for how to enable additional remotes including the remote that contained early Framework 13 updates.

**Comment by qbit** [comment]
Like I said, I don't need the capabilities anymore.

> I'm not sure what migration path would even make sense to provide...

I'd say at a minimum there should be an error that says `enableTestRemote` has been changed to `TestDevices`. That way users don't have to search for this MR and figure out what happened to break their config.

**Comment by amaxine** [comment]
Follow up in #288122. This option being exposed clearly led to confusion - the remote `fwupd-tests` is not `lvfs-testing` and never served any purpose for real physical hardware. I am opposed to advising people to switch to `TestDevices`, as that perpetuates confusing behaviour and end user use of internal test functionality.

**Pull request merged**
