### PR TITLE
oculante: 0.6.41 -> 0.6.58

### PR DESCRIPTION
**Pull request by nagy**
###### Description of changes

The automatic build got stuck because of the missing perl dependency.

Changelog: https://github.com/woelper/oculante/blob/0.6.54/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
0.6.58 just released: https://github.com/woelper/oculante/releases/tag/0.6.58

**Comment by nagy** [comment]
> 0.6.58 just released: https://github.com/woelper/oculante/releases/tag/0.6.58

Maybe we should let the bot handle that. I want to see If my fix here is helping the bot to get unstuck.

**Comment by NickCao** [comment]
Build is failing on ofborg:
```
       > Caused by:
       >   failed to verify the checksum of `jpegxl-sys v0.8.1+libjxl-0.8.1`
```

**Comment by nagy** [comment]
> Build is failing on ofborg:

That is weird, it used to build for me locally. Could it be that upstream has changed the crate underneath? I have switched it to `0.6.58` , which builds locally again for me.

**Comment by NickCao** [comment]
ofborg happy this time, but it's failing for me locally. Looks like https://github.com/rust-lang/cargo/issues/11412, but the particular version of `jpegxl-sys` is not yanked, strange.

**Comment by NickCao** [comment]
Could still be a cargo bug, would you like to workaround it with `./maintainers/scripts/convert-to-import-cargo-lock.sh oculante`

**Review by NickCao — APPROVED** [review]

**Pull request merged**
