### PR TITLE
numpy/scipy/sqlalchemy: allow defaultversions to be configured

### PR DESCRIPTION
**Pull request by adnelson**
This allows a user to configure at top-level the default versions of numpy, scipy and sqlalchemy. All three are commonly-used libraries, and a package that uses them might also depend on other packages which also use these libraries, in which case the versions must match. This change preserves the existing default versions, while allowing users to configure their own defaults if they need to.

I also added (back) in versions 1.9 of numpy and 0.9 of sqlalchemy.
###### Things done
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
It is possible to set the version with `overridePackages`, its just a bit verbose:
```
newpkgs = pkgs.overridePackages(self: super: rec {
  python35Packages = super.python35Packages.override {
    self = python35Packages // { scipy = python35Packages.scipy_0_16;};
```
https://hydra.nixos.org/build/34655146/download/1/nixpkgs/manual.html#how-to-override-a-python-package

**Comment by adnelson** [comment]
Problem (as I see it) is that other packages in the set which use just `self.scipy` or equivalent as a build input, will still use the one defined in the python package set.

**Comment by FRidh** [comment]
if you use newpkgs that should not be the case.

**Comment by adnelson** [comment]
I'm not sure what newpkgs is.

**Comment by adnelson** [comment]
OK so I looked again at what you had posted and I see what newpkgs is. And although rather convoluted, the overrides did allow me to set the versions of the packages. However, they don't (oddly enough) fix the top-level binding. As in, if I inform nixpkgs that `self.numpy` should be `numpy_1_9`, and then I build `newpkgs.pythonPackages.numpy`, it still builds numpy version 1.10. On the other hand, if I build scipy, which depends on numpy, it uses numpy 1.9 as a dependency. I'm sure I could override things in an even more convoluted fashion, but I wonder if it wouldn't be so bad to take the straightforward approach of setting default versions of these packages. 

If that's strongly opposed, I'd still like to add the expression for version 1.9 of numpy, sqlalchemy version 9, and other changes.

**Comment by FRidh** [comment]
hmm, I thought that method of override was working. Let me have a look at it again.

I'm completely fine with having the older versions of numpy and sqlalchemy in there, as long as you add yourself as maintainer.

**Comment by FRidh** [comment]
How about this one:
```
with import <nixpkgs> {};
with pkgs;

(let
  newpkgs = pkgs.overridePackages(self: super: rec {
    python35Packages = lib.overrideExisting super.python35Packages { numpy = super.python35Packages.numpy_1_10;};
  });
in newpkgs.python35.buildEnv.override {
  extraLibs = with newpkgs.python35Packages; [ numpy numtraits ];
}).env
```

**Comment by adnelson** [comment]
Yeah that works; my personal solution was along the lines of:

```nix
{
  pkgs = let
      nixpkgs = import pkgsPath {};
    in
    nixpkgs.overridePackages(self: super: rec {
      python27Packages = let
        overrides = {
          numpy = python27Packages.numpy_1_9;
          scipy = python27Packages.scipy_0_16;
          sqlalchemy = python27Packages.sqlalchemy_1_0;
        };
      in super.python27Packages.override {
        self = python27Packages // overrides;
      } // overrides;
      python34Packages = let
        overrides = {
          numpy = python34Packages.numpy_1_9;
          scipy = python34Packages.scipy_0_16;
          sqlalchemy = python34Packages.sqlalchemy_1_0;
        };
      in super.python34Packages.override {
        self = python34Packages // overrides;
      } // overrides;
    });
}
```

I mean, let's be honest.... that's super gross. That said, I suppose it might be preferable to adding some specific code for setting versions of just three packages. So, I'm good with that.

Honestly I'm curious why numpy 1.9 and sqlalchemy 9 were removed in the first place. Both of them used to be in nixpkgs, and in the case of sqlalchemy 9, we have still retained two earlier versions (7 and 8), but are skipping 9 for some reason...? :confused: 

I'm fine listing myself as a maintainer, although I have almost no knowledge of sqlalchemy; it's just something I've needed to get a few packages to build.

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/pull/14471 about sqlalchemy cleaning.
We had a lot of versions, and some were not needed anymore. If someone does need an older version, then they need to be explicit about it, and maintain that expression or else it will be dropped again. And, you can always maintain an older version locally, right.

I absolutely agree with you that it doesn't win an award for being a pretty solution, but I don't think its too bad either. I will fix the expression in the documentation by replacing it with the one I wrote above.

**Comment by adnelson** [comment]
Alright cool, well I can probably get away with not using sqlalchemy 9. Dropping numpy 1.9 is a little more dicey but we'll see. I'll clean this PR up, thanks

**Comment by adnelson** [comment]
Ok @FRidh I removed the sqlalchemy 9 expression. I kept numpy 1.9 but added myself as a maintainer on numpy.

**Comment by FRidh** [comment]
@adnelson Could you open new PR's for the individual changes.

**Pull request closed without merging**
