### PR TITLE
mlt: Add rubberband support

### LINKED ISSUE #201654: Kdenlive: cannot set pitch compensation because "MLT must be compiled with the rubberband library"
### Describe the bug
cannot use pitch compensation in kdenlive despite having mlt and rubberband installed/introduced via nix-shell

### Steps To Reproduce
1. open kdenlive
2. add video with audio or just audio
3. right click on audio, select "Change Speed"
4. see that Pitch Compensation is disabled because "MLT must be compiled with the rubberband library"

### Expected behavior

There should be some way to enable this.

### Screenshots
image

### Notify maintainers

kdenlive: @turion 
rubberband: @cillianderoiste @MarcWeber 
mlt: @tohl @peti 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.8, NixOS, 22.11 (Raccoon), 22.11.20221114.dad4de1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(beef): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Adds rubberband support to mlt. Fixes #201654 .

CC @goibhniu @peti

### CODE REVIEW

**Comment by turion** [comment]
I tested locally by going through the reproduction steps of #201654, but now they continue differently:

4. see that Pitch Compensation is __en__abled
5. apply pitch compensation
6. preview ("prehear") the project, indeed the speed is lower now with the same pitch
7. render the project, same result

**Comment by turion** [comment]
For `default.nix` I tested as:

```
$ nix build .#mlt

$ ./result/bin/melt --version
melt 6.26.0
[...]

$ ./result/bin/melt -query "filters" | grep rbpitch
  - rbpitch
```

**Comment by turion** [comment]
@goibhniu @peti @cillianderoiste do you want to review? Otherwise I'll merge soon.

**Review by peti — APPROVED** [review]
👍

**Pull request merged**
