### PR TITLE
python312Packages.elevenlabs: fix meta.changelog

### PR DESCRIPTION
**Pull request by dotlambda**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Atemu — COMMENTED** [review]
Passing through the tag gets an ACK from me but I don't maintain fetchgithub.

Depending on the src's tag is a weird pattern though when the version is readily available.

**Comment by dotlambda** [comment]
> Depending on the src's tag is a weird pattern though when the version is readily available.

Quite the opposite. Some upstreams change from `v${version}` to `version` as you can see in this case and only having to update it in one place is a good thing.

**Review by philiptaron — APPROVED** [review]

**Comment by Atemu** [comment]
> Quite the opposite. Some upstreams change from `v${version}` to `version` as you can see in this case and only having to update it in one place is a good thing.

I agree that the tag should be defined in one place. What I disagree with is depending on the fetcher's internals to achieve this as that tightly couples it to them. Think more about this and you'll see that it's super weird and unnecessary.

Why no use a simple let binding to achieve this? That satisfies DRY, is absolutely declarative and does not depend on what the fetcher does with the tag argument or whether it even has one (remember, overrides exist and not all fetchers have the concept of a tag; people could just pass a plain old path literal into `src`).

Your first patch would simply not be necessary if you didn't depend on the fetcher's internals. I'd still want the patch to be merged but only for introspectability purposes, not for actual use like you've done here.

**Comment by dotlambda** [comment]
> Why not use a simple let binding to achieve this?

How would that work in the context of `finalAttrs`?

**Comment by Atemu** [comment]
If you wanted to expose this as part of the package's API via overrideAttrs, you'd have to make it a mkDerivation argument. I'd question the need to do that though.

Additionally, I personally find overrideAttrs to be the wrong place for external APIs as it's a tool for changing derivation-internal details, not abstract package-specific options.
While not ideal, the regular packag inputs function args (`override`) are more appropriate IMHO. I use those in our ffmpeg package to allow fetching any version of ffmpeg and it's that same interface that is used to construct our 3 ffmpeg versions that we support. All without needing to use finalAttrs or overrideAttrs.

**Comment by philiptaron** [comment]
I want to merge this PR because depending on `tag` is no worse nor no better than depending on `rev`, and only exposing `rev` means that those who _do_ depend on it are likely to have to post-process it back in an awkward way.

I agree with @Atemu that making the meta depend on the src is bad and wrong and shouldn't be done (and where done, should be undone.) The fact remains that *today* a great many packages have this linkage.

We should have this discussion on some other issue than this PR. It seems quite related to the `pname` / `version` discussion that happens in many issues.

**Comment by Atemu** [comment]
> If we don't want to use `src.tag` then we also shouldn't use `src.rev`

Correct.

> but that's very common

Commonality does not imply adequacy.

> I'm happy to change it once there's consensus on removing both.

I don't think we need broad consensus to realise that it's better to not depend on src's internals and stop doing it wherever possible.

> depending on `tag` is no worse nor no better than depending on `rev`,

That's not what's done here. The change is from depending on version to depending on src's internals.

> only exposing `rev` means that those who _do_ depend on it are likely to have to post-process it back in an awkward way

As mentioned, I'm totally fine with exposing it.

> The fact remains that _today_ a great many packages have this linkage.

I don't see how that's an argument to continue doing it.

> We should have this discussion on some other issue than this PR.

Agreed but I'd still prefer if this PR didn't do it.

> It seems quite related to the `pname` / `version` discussion that happens in many issues.

I don't know of this issue you speak of. Could you enlighten me?

That pname+version should be used over name has pretty much been consensus for many years now, so that can't be it.

**Review by philiptaron — CHANGES_REQUESTED** [review]
I think @Atemu has convinced me that we shouldn't include `src.something` in meta tags, starting here.

**Comment by dotlambda** [comment]
I really don't understand the problem with using `src.rev` or `src.tag` but whatever.

> It seems quite related to the `pname` / `version` discussion that happens in many issues.

`repo = pname` is a very different situation since the two only agree accidentally.

**Review by philiptaron — APPROVED** [review]

**Review by Atemu — APPROVED** [review]
Diff LGTM, if this evals to the same thing, we're good.

**Comment by Atemu** [comment]
Ah, it does.

**Pull request merged**
