### PR TITLE
bruno: patch out giflib dependency, format

### LINKED ISSUE #319720: Build failure: bruno on 24.05-darwin
### Steps To Reproduce

- Attempt to build `bruno` on `nixpkgs-24.05-darwin`

Sample shell.nix:
```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixpkgs-24.05-darwin";
  pkgs = import nixpkgs {
    config = {
      allowUnfree = true;
    };
    overlays = [ ];
  };
in

pkgs.mkShellNoCC { packages = [ pkgs.bruno ]; }
```

### Build log

https://gist.github.com/kranners/1aef721fc58bd4e683572e9d475f0e21

### Additional context

This is on an M2 chip, and it seems the issue is with node-canvas not being able to install due to missing giflib.

Building with:
```nix
packages = [
    (pkgs.bruno.overrideAttrs (old: {
      buildInputs = old.buildInputs ++ [
        pkgs.giflib
      ];
    }))
];
```

Fixes this.

### Notify maintainers

@gepbird @kashw2 @lucasew @mattpolzin @water-sucks 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by gepbird**
## Description of changes

Closes #319720.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mattpolzin — CHANGES_REQUESTED** [review]
giflib is actually an optional dependency of canvas and it’s one that Bruno does not use. This fails only on Darwin machines that happen to have giflib installed via Homebrew (at least that’s the situation I’ve seen before). 

In my opinion, this is an upstream issue with how canvas determines whether or not to compile with giflib; it hard codes a home brew lookup into its setup script but then expects that lib to be in the path when building. 

Here’s the full context the last time we looked at the issue: https://github.com/NixOS/nixpkgs/issues/296681

**Comment by mattpolzin** [comment]
I’d be interested in trying to fix canvas’s build from our end by finding a way to stop it from trying to use giflib, but I have not found time to look into patching or replacing somewhere between node dependency download and build.

**Comment by gepbird** [comment]
@mattpolzin thanks for explaining the situation. I'll try patching out the system library lookups from canvas, essentially replacing this code with a `return false`:

https://github.com/Automattic/node-canvas/blob/f934f226fc01b2ccb4554d0056718a24279ac087/util/has_lib.js#L40-L50

I'm not sure how hard it is to do between the dependency downloads and install, but I'll give it a try soon.

**Comment by mattpolzin** [comment]
Another place to potentially patch would be https://github.com/Automattic/node-canvas/blob/f934f226fc01b2ccb4554d0056718a24279ac087/binding.gyp#L24 (change to 'false'). The switch at the bottom of the `has_lib` file uses the same function for Cairo and giflib, the former of which we do want it to build against, so that's a consideration as well.

**Comment by gepbird** [comment]
> The switch at the bottom of the `has_lib` file uses the same function for Cairo and giflib, the former of which we do want it to build against, so that's a consideration as well.

I'd only patch out the part that searches in system paths, it should still be able to find jpeg and rsvg, looking at the above ldconfig check.

But your solution is a nice one liner so I'll try using that, thanks :)

**Comment by gepbird** [comment]
I think we need to provide a custom `npmConfigHook` that doesn't call `npm rebuild`, or patch the current hook if that's possible. I'll look further into it later which may be multiple days.

Other packages that depend on node-canva just accepted to pull these dependencies:

https://github.com/NixOS/nixpkgs/blob/23bcbb6dfd7ba49ef8d9326f4784f5d83545503e/pkgs/development/node-packages/overrides.nix#L466-L475

https://github.com/NixOS/nixpkgs/blob/23bcbb6dfd7ba49ef8d9326f4784f5d83545503e/pkgs/by-name/je/jellyfin-web/package.nix#L12-L16

**Comment by gepbird** [comment]
@ofborg build bruno

**Review by mattpolzin — APPROVED** [review]
Brillant! I tested on `x86_64-darwin` both with and without `giflib` installed via Homebrew and it worked either way.

**Review by kashw2 — APPROVED** [review]

**Comment by mattpolzin** [comment]
Seems like it may not backport cleanly if it builds on another PR that wasn't backported but admittedly I've never paid much attention to how the backporting works. Also maybe that's no big deal and the backport PR just needs to be tweaked when a conflict occurs.

**Comment by gepbird** [comment]
> Seems like it may not backport cleanly if it builds on another PR that wasn't backported but admittedly I've never paid much attention to how the backporting works. Also maybe that's no big deal and the backport PR just needs to be tweaked when a conflict occurs.

Yes, automatic backport will fail and a backport PR with #319938 and #319759 (and possibly other version bumps?) needs to be manually created.

**Review by mattpolzin — APPROVED** [review]
Still looks great to me!

Result of `nixpkgs-review pr 319759` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bruno</li>
  </ul>
</details>

**Pull request merged**
