### PR TITLE
treewide: housekeeping of packages maintained by lucasew

### PR DESCRIPTION
**Pull request by lucasew**
## Description of changes

- Moved the relevant `packages to pkgs/by-name`
- Updated all the packages using `maintainers/update.nix`
- Simplified update logic for cockpit
- Fixed tests of cockpit because it wasn't finding the selenium driver IDK why, worked before
- Replaces https://github.com/NixOS/nixpkgs/pull/262453

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 262852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>python310Packages.orange-canvas-core</li>
    <li>python310Packages.orange-canvas-core.dist</li>
    <li>python310Packages.orange-widget-base</li>
    <li>python310Packages.orange-widget-base.dist</li>
    <li>python310Packages.orange3</li>
    <li>python310Packages.orange3.dist</li>
    <li>python310Packages.qasync</li>
    <li>python310Packages.qasync.dist</li>
    <li>python311Packages.orange-canvas-core</li>
    <li>python311Packages.orange-canvas-core.dist</li>
    <li>python311Packages.orange-widget-base</li>
    <li>python311Packages.orange-widget-base.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
    <li>python311Packages.qasync</li>
    <li>python311Packages.qasync.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>cockpit</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 262852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.orange3</li>
    <li>python310Packages.orange3.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>cockpit</li>
    <li>python310Packages.orange-canvas-core</li>
    <li>python310Packages.orange-canvas-core.dist</li>
    <li>python310Packages.orange-widget-base</li>
    <li>python310Packages.orange-widget-base.dist</li>
    <li>python310Packages.qasync</li>
    <li>python310Packages.qasync.dist</li>
    <li>python311Packages.orange-canvas-core</li>
    <li>python311Packages.orange-canvas-core.dist</li>
    <li>python311Packages.orange-widget-base</li>
    <li>python311Packages.orange-widget-base.dist</li>
    <li>python311Packages.qasync</li>
    <li>python311Packages.qasync.dist</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 262852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.orange3</li>
    <li>python310Packages.orange3.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>cockpit</li>
    <li>python310Packages.orange-canvas-core</li>
    <li>python310Packages.orange-canvas-core.dist</li>
    <li>python310Packages.orange-widget-base</li>
    <li>python310Packages.orange-widget-base.dist</li>
    <li>python310Packages.qasync</li>
    <li>python310Packages.qasync.dist</li>
    <li>python311Packages.orange-canvas-core</li>
    <li>python311Packages.orange-canvas-core.dist</li>
    <li>python311Packages.orange-widget-base</li>
    <li>python311Packages.orange-widget-base.dist</li>
    <li>python311Packages.qasync</li>
    <li>python311Packages.qasync.dist</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 262852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>cockpit</li>
    <li>python310Packages.orange-canvas-core</li>
    <li>python310Packages.orange-canvas-core.dist</li>
    <li>python310Packages.orange-widget-base</li>
    <li>python310Packages.orange-widget-base.dist</li>
    <li>python310Packages.orange3</li>
    <li>python310Packages.orange3.dist</li>
    <li>python310Packages.qasync</li>
    <li>python310Packages.qasync.dist</li>
    <li>python311Packages.orange-canvas-core</li>
    <li>python311Packages.orange-canvas-core.dist</li>
    <li>python311Packages.orange-widget-base</li>
    <li>python311Packages.orange-widget-base.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
    <li>python311Packages.qasync</li>
    <li>python311Packages.qasync.dist</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Nice

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 262852` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>bruno</li>
    <li>cockpit</li>
    <li>python310Packages.orange-canvas-core</li>
    <li>python310Packages.orange-canvas-core.dist</li>
    <li>python310Packages.orange-widget-base</li>
    <li>python310Packages.orange-widget-base.dist</li>
    <li>python310Packages.orange3</li>
    <li>python310Packages.orange3.dist</li>
    <li>python310Packages.qasync</li>
    <li>python310Packages.qasync.dist</li>
    <li>python311Packages.orange-canvas-core</li>
    <li>python311Packages.orange-canvas-core.dist</li>
    <li>python311Packages.orange-widget-base</li>
    <li>python311Packages.orange-widget-base.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
    <li>python311Packages.qasync</li>
    <li>python311Packages.qasync.dist</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
I did not run the new test, but I also didn't see any code prone to breakages here.

**Comment by lucasew** [comment]
> I did not run the new test, but I also didn't see any code prone to breakages here.

The thing that broke on the cockpit test is that it wasn't finding the webdriver and firefox. I only had to hardcode it and now it's working.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
