### PR TITLE
nodePackages.prisma: 5.0.0 -> 5.1.1

### PR DESCRIPTION
**Pull request by thenbe**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thenbe** [comment]
The `nixpkgs-review` command fails (output below). Not sure if this is due to the fact that I've cloned nixpkgs with `--depth=1`.

```
~/nixpkgs
❯ nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/249007
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/249007/head:refs/nixpkgs-review/1
From https://github.com/NixOS/nixpkgs
 * [new ref]             refs/pull/249007/head -> refs/nixpkgs-review/1
$ git worktree add /home/nbe/.cache/nixpkgs-review/pr-249007/nixpkgs a1fa57b4ba546ef8869237ae1341f393cb9b5806
Preparing worktree (detached HEAD a1fa57b4b)
Updating files: 100% (36631/36631), done.
HEAD is now at a1fa57b4b Merge pull request #248987 from r-ryantm/auto-update/numix-icon-theme-circle
$ nix-env --extra-experimental-features no-url-literals --option system x86_64-linux -f /home/nbe/.cache/nixpkgs-review/pr-249007/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
$ git merge --no-commit --no-ff abb3b6330eb95609ff3f765e911ebb87892fb55a
fatal: refusing to merge unrelated histories
https://github.com/NixOS/nixpkgs/pull/249007 failed to build
$ git worktree prune
```

**Comment by aqrln** [comment]
fwiw there's an earlier PR opened by me (I don't mind which of the two gets merged): https://github.com/NixOS/nixpkgs/pull/249148

**Review by aqrln — APPROVED** [review]

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 249007` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prisma-engines</li>
  </ul>
</details>

**Comment by thenbe** [comment]
https://github.com/NixOS/nixpkgs/pull/249148 already has discussions so let's close this and go with that instead.

**Pull request closed without merging**
