### PR TITLE
gollum: add additional dependencies

### LINKED ISSUE #130131: Gollum does not include dependencies for non-default renderers (org-mode etc.)
**Describe the bug**
Gollum [supports a variety of markup languages](https://github.com/gollum/gollum#markups), but the package doesn’t include the relevant gems (notably `org-ruby`).

**To Reproduce**
1. `services.gollum.enable = true;`
2. Make a new page with format set to org-mode
3. `Failed to render page: cannot load such file -- org-ruby`

**Expected behavior**
Ought to render the org markup

**Notify maintainers**
@erictapen 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.11.20210616.0747387 (Porcupine)`
 - multi-user?: `yes`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Closes #130131

###### Things done
added the additional renderers
https://github.com/gollum/gollum#markups
there isn't a way to make these optional as far i can see

effect on closure size
```
thesize /nix/store/j3sp2gh63h0jpxjy4y8vx2hwzrkl6h0w-gollum-5.2.1-gems
536K	/nix/store/j3sp2gh63h0jpxjy4y8vx2hwzrkl6h0w-gollum-5.2.1-gems
536K	total
thesize /nix/store/prlg7hffzj53zq6aj9sb4s9hg4k7jq4b-gollum-5.2.1-gems
624K	/nix/store/prlg7hffzj53zq6aj9sb4s9hg4k7jq4b-gollum-5.2.1-gems
624K	total
```

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
bump

**Comment by erictapen** [comment]
Hey, sorry for the delay. I'm somewhat new to ruby packaging. How did you regenerate the `gemset.nix` and `Gemfile.lock` files?

Also this doesn't completely close the issue, as [Pod and ReStructuredText](https://github.com/gollum/gollum#markups) are still missing, right? Not that those would be necessary to merge this.

**Comment by Artturin** [comment]
> Hey, sorry for the delay. I'm somewhat new to ruby packaging. How did you regenerate the `gemset.nix` and `Gemfile.lock` files?
> 
> Also this doesn't completely close the issue, as [Pod and ReStructuredText](https://github.com/gollum/gollum#markups) are still missing, right? Not that those would be necessary to merge this.

i added the gems to the gemfile and then ran
```
nix-shell -p bundix icu zlib cmake pkg-config openssl
bundix -l
```
in pkgs/applications/misc/gollum
https://nixos.org/manual/nixpkgs/stable/#developing-with-ruby

**Comment by Artturin** [comment]
added perl and python3 to the path so pod and restructuredtext should work now

**Review by erictapen — APPROVED** [review]
Finally found time to test this on my gollum installation. Everything works but ReStructured text, which is due to gollum still demanding Python 2. This should change when we bump gollum to the latest version where this patch is included: https://github.com/gollum/gollum-lib/pull/401

Thanks!

**Pull request merged**
