### PR TITLE
gradle: 7.3.2 -> 7.3.3, 6.9.1 -> 6.9.2, pdftk: 3.3.1 -> 3.3.2

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
See:
 - https://github.com/gradle/gradle/releases/tag/v7.3.3
 - https://github.com/gradle/gradle/releases/tag/v6.9.2
 
 Continuation of my activity as maintainer:
 - https://github.com/NixOS/nixpkgs/pull/150866
 - https://github.com/NixOS/nixpkgs/pull/148176
 - https://github.com/NixOS/nixpkgs/pull/145365
 - https://github.com/NixOS/nixpkgs/pull/143152

### CODE REVIEW

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 151790` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>apkleaks</li>
    <li>diffoscope</li>
    <li>gscan2pdf</li>
    <li>jadx</li>
    <li>mucommander</li>
    <li>pdfchain</li>
    <li>pdftk</li>
    <li>scenebuilder</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>frostwire</li>
    <li>gradle (gradle_7)</li>
    <li>gradle_6</li>
    <li>kotlin-language-server</li>
    <li>ma1sd</li>
    <li>mindustry</li>
    <li>mindustry-server</li>
    <li>mindustry-wayland</li>
    <li>scenic-view</li>
    <li>shattered-pixel-dungeon</li>
    <li>signald</li>
  </ul>
</details>

**Comment by kevincox** [comment]
Only 3 of these are existing failures. Can you take a look?

```
error: build of '/nix/store/1f3w0sy82nwjdf0ihn3svxzfdwz6s8ck-mucommander-0.9.3-3.drv', '/nix/store/6f8zv1hlg36njagn4p4sqviym1nvgy0l-jadx-1.3.0.drv', '/nix/store/y149d5z0d834n5zikya86zfad0b0lv11-apkleaks-2.6.1.drv' failed
```

**Comment by lorenzleutgeb** [comment]
Yeah, these fixed output derivations are annoying me... I fixed `pdftk`, but can only take a look at the others tomorrow.

**Comment by lorenzleutgeb** [comment]
Supersedes #151791

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 151790` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>impressive</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mucommander</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>apkleaks</li>
    <li>diffoscope</li>
    <li>frostwire</li>
    <li>gradle (gradle_7)</li>
    <li>gradle_6</li>
    <li>gscan2pdf</li>
    <li>jadx</li>
    <li>kotlin-language-server</li>
    <li>ma1sd</li>
    <li>mindustry</li>
    <li>mindustry-server</li>
    <li>mindustry-wayland</li>
    <li>pdfchain</li>
    <li>pdftk</li>
    <li>scenebuilder</li>
    <li>scenic-view</li>
    <li>shattered-pixel-dungeon</li>
    <li>signald</li>
  </ul>
</details>

**Review by kevincox — APPROVED** [review]

**Comment by 7c6f434c** [comment]
@ofborg build mucommander

**Comment by 7c6f434c** [comment]
Seems to be failing on Hydra anyway; not sure what update broke things, but probably not this

**Pull request merged**
