### PR TITLE
Virtualbox Guest Additions fix

### PR DESCRIPTION
**Pull request by matthewbauer**
This seems to fix issue #16641 for some people.

### CODE REVIEW

**Comment by basvandijk** [comment]
This patch fixes the problem for me. Can this also be cherry-picked into `release-16.03` please?

Thanks @matthewbauer!

**Comment by matthewbauer** [comment]
I would prefer to just rollback the VirtualBox update to 5.0.12 on release-16.03. We really don't need the newer version in 16.03 AFAICT.

**Comment by basvandijk** [comment]
@matthewbauer don't we actually want the virtualbox 5.0.* releases on 16.03 since they are maintenance releases fixing bugs? (of course in this case it caused a bug...)

**Comment by matthewbauer** [comment]
Either way is fine with me. I'm just not sure if there are more issues introduced with the 5.0.16 update.,

**Comment by basvandijk** [comment]
5.0.20 is running without problems for me.

**Comment by davidak** [comment]
LGTM

please cherry-pick into `release-16.03` for users of newer VirtualBox versions on OS X and Windows.

**Pull request merged**
