### PR TITLE
Python package set changes

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Includes:
- #38207
- #38127 - only minor changes. Bumps will be done later when upgrading the whole set.
- various other commits from @dotlambda (note I force-pushed to this branch)

Hydra evaluation:
- https://hydra.nixos.org/eval/1445747

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
@FRidh I think you forgot to actually include https://github.com/NixOS/nixpkgs/pull/38127.

**Comment by FRidh** [comment]
@dotlambda I did not cherry-pick the change, but made the minor changes myself.

**Comment by FRidh** [comment]
The queue is quite small, so we can likely merge this into staging tonight. After that, I'll push again to this branch major version bumps. They will need fixing though...

**Comment by dotlambda** [comment]
Are you sure? https://github.com/NixOS/nixpkgs/pull/38439/files#diff-52cc11e02612c61c413817fe912f43f5

**Comment by dotlambda** [comment]
Oh sorry, I overlooked

> Bumps will be done later when upgrading the whole set

**Comment by dotlambda** [comment]
Shouldn't we add the bumps I did to the second PR as well?

**Comment by FRidh** [comment]
Its quite unlikely they cause breakage and if they do, its only few to fix.

**Review by dotlambda — APPROVED** [review]

**Comment by dotlambda** [comment]
aioimaplib failure seems to be due to `python3: 3.6.4 -> 3.6.5`. I opened an upstream issue about it: https://github.com/bamthomas/aioimaplib/issues/35

**Comment by dotlambda** [comment]
`cryptacular` also seems to break because of Python 3.6.5:
```
crypt_blowfish-1.2/crypt.h:17:10: fatal error: gnu-crypt.h: No such file or directory
```
Do you know of a change that could be causing this?

**Comment by dotlambda** [comment]
Moinmoin, for example, is not running any tests for me locally (`Ran 0 tests in 0.000s`). I have no idea why that's different from the Hydra build.

**Pull request merged**
