### PR TITLE
mistral-rs: 0.1.18 -> 0.3.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/EricLBuehler/mistral.rs/releases/tag/v0.3.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Waiting for the next release.

https://github.com/NixOS/nixpkgs/pull/319008#issuecomment-2198493045

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Thanks for the release @EricLBuehler.
I will have to find a way around the new `plotly_kaleido` dependency [build script](https://github.com/plotly/plotly.rs/blob/0.9.0/plotly_kaleido/build.rs). Indeed, it involves downloading a binary from GitHub and putting it in `~/.config/kaleido`. This is failing within the sandbox for two reasons:
- Internet access is not available
- Writing to a path such as `~/.config/kaleido` is not possible. (We could temporarily create a fake home to let the script operate, but we would need to move the binary to somewhere else).

**Comment by EricLBuehler** [comment]
> I will have to find a way around the new plotly_kaleido dependency [build script](https://github.com/plotly/plotly.rs/blob/0.9.0/plotly_kaleido/build.rs). Indeed, it involves downloading a binary from GitHub and putting it in ~/.config/kaleido. This is failing within the sandbox for two reasons:

Ah, ok. Perhaps a solution would be to put `plotly` behind a (default on) feature flag, and here you can set default to false and enable the features you want?

**Comment by GaetanLepage** [comment]
> Ah, ok. Perhaps a solution would be to put `plotly` behind a (default on) feature flag, and here you can set default to false and enable the features you want? Is that something that can be done here?

That would be a very nice first step indeed.
Having plotly would require us to patch the `plotly_kaleido` crate and allow for a `KALEIDO_PATH` to be provided by the user.
We could then prepare a nix-friendly `kaleido` derivation and provide it to the build environment using this environment variable.

Would such a change be accepted into the crate @andrei-ng ?

**Comment by andrei-ng** [comment]
> > Ah, ok. Perhaps a solution would be to put `plotly` behind a (default on) feature flag, and here you can set default to false and enable the features you want? Is that something that can be done here?
> 
> That would be a very nice first step indeed. Having plotly would require us to patch the `plotly_kaleido` crate and allow for a `KALEIDO_PATH` to be provided by the user. We could then prepare a nix-friendly `kaleido` derivation and provide it to the build environment using this environment variable.
> 
> Would such a change be accepted into the crate @andrei-ng ?

Yes, feel free to make a proposal and PR. As long as it is seamless for plotly-rs users, all good from my side. Maybe have   the env var  `KALEIDO_PATH` have `~/.config/kaleido` as default and and change it for other situations as needed. I am sure we can find a solution.

**Comment by GaetanLepage** [comment]
> Yes, feel free to make a proposal and PR. As long as it is seamless for plotly-rs users, all good from my side. Maybe have the env var `KALEIDO_PATH` set to `~/.config/kaleido` as default and change it for other situations as needed. I am sure we can find a solution.

Ok, I will try to have a look but can't promise anything.
If the feature is made optional (`--feature plotly`) in `mistral-rs` it could work out for us. cc @EricLBuehler

**Comment by EricLBuehler** [comment]
> If the feature is made optional (--feature plotly) in mistral-rs it could work out for us. cc @EricLBuehler 

@GaetanLepage sounds good. We are going to be releasing v0.2.0 next, so we can include this sort of breaking behavior.

**Comment by EricLBuehler** [comment]
@GaetanLepage, I just merged EricLBuehler/mistral.rs#587 which makes this optional, it can be disabled with `--no-default-features`.

**Comment by GaetanLepage** [comment]
> @GaetanLepage, I just merged [EricLBuehler/mistral.rs#587](https://github.com/EricLBuehler/mistral.rs/pull/587) which makes this optional, it can be disabled with `--no-default-features`.

Great, thanks ! I will be waiting for the next release then.

**Comment by EricLBuehler** [comment]
@GaetanLepage I just released v0.2.0! MSRV is 1.75 still, and you can use `--no-default-features`.

**Comment by GaetanLepage** [comment]
Adding the `--no-default-features` still leads to 
```
error: failed to run custom build command for `plotly_kaleido v0.9.0`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/plotly_kaleido-9082ffa9a1b2ab5c/build-script-build` (exit status: 101)
  --- stderr
  warning: `/build/cargo-vendor-dir/.cargo/config` is deprecated in favor of `config.toml`
  note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
  warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
  note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
      Updating crates.io index
  warning: spurious network error (3 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
  warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
  warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
  error: download of config.json failed

  Caused by:
    failed to download from `https://index.crates.io/config.json`

  Caused by:
    [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
  thread 'main' panicked at /build/cargo-vendor-dir/plotly_kaleido-0.9.0/build.rs:123:10:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Build command used: 
```
cargo build -j 12 --target x86_64-unknown-linux-gnu --offline --profile release --no-default-features
```

**Comment by GaetanLepage** [comment]
> Adding the `--no-default-features` still leads to

@EricLBuehler are you sure that the flag propagates correctly ? I am not too familiar with cargo, so maybe I did something wrong.

**Comment by EricLBuehler** [comment]
@GaetanLepage this may be incorrect. I'll fix it in v0.2.3.

**Comment by EricLBuehler** [comment]
So, it looks like this is kind of strange. I couldn't get it to work with `--no-default--features`...

@andrei-ng do you know of a way to gate the `kaliedo` feature?

**Comment by EricLBuehler** [comment]
@GaetanLepage I just released v0.3.0. It fixed the issue of the plotly feature, but the MSRV is now 1.79. Would this work?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> @GaetanLepage I just released v0.3.0. It fixed the issue of the plotly feature,

It seems to work great, thank you !

> but the MSRV is now 1.79. Would this work?

This is perfectly fine. We are now on rust 1.80.1 :)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 323788` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mistral-rs</li>
  </ul>
</details>

**Review by SuperSandro2000 — COMMENTED** [review]
LGTM

**Comment by andrei-ng** [comment]
> So, it looks like this is kind of strange. I couldn't get it to work with `--no-default--features`...
> 
> @andrei-ng do you know of a way to gate the `kaliedo` feature?

@EricLBuehler 

Somehow, I missed this last message/question. If `kaleido` feature is not specified, there should be no Kaleido download initiated.

Anyhow, I came round to this issue and I have changed the implementation which is basically in line with the earlier discussion. Users can now opt in to manually provide the path to the binary as an environment variable, `KALEIDO_PATH` , if static export image features are required. This is currently available on latest `main` and soon will make it into the latest release. This option is explained succinctly in the [Readme](https://github.com/plotly/plotly.rs?tab=readme-ov-file#kaleido-external-dependency)

**Pull request merged**
