### PR TITLE
Update Boot to 2.4.2

### PR DESCRIPTION
**Pull request by vizanto**
``` clj
(update-in expr [:version] "2.4.2")
```

### CODE REVIEW

**Comment by pSub** [comment]
Please rewrite the commit message according to CONTRIBUTING.md.

**Comment by vizanto** [comment]
Updated commit message.  This stuff should be automated though. :)

**Comment by pSub** [comment]
Btw. you don't have to create a new PR, you can simply force push.

**Comment by vizanto** [comment]
Yes, I just noticed I made a stupid mistake

**Pull request closed without merging**
