### PR TITLE
bump R packages

### LINKED ISSUE #121808: R package update not working
**Describe the bug**
Trying to follow the [steps to update R packages](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/r.section.md). `RScript generate-r-packages.R cran > new` is failing with:

```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 5529 did not have 7 elements
Calls: as.data.table -> read.table -> scan
Execution halted
```

**To Reproduce**
1. checkout NixOS/nixpkgs master
2. navigate to pkgs/development/rmodules
3. `nix-shell generate-shell.nix`
4. `Rscript generate-r-packages.R cran  > cran-packages.nix.new`

**Additional context**

I'm looking to install [RPostgres](https://github.com/r-dbi/RPostgres), released version in nixpkgs is old (1.2.1) and will not install due to bad [`configure`](https://github.com/r-dbi/RPostgres/blob/v1.2.1/configure), which is why I went down this path.

**Notify maintainers**
"@"ing some folks who modified this script:

@TikhonJelvis 
@jbedo 
@peti

### PR DESCRIPTION
**Pull request by Jake-Gillberg**
###### Motivation for this change
Bump R cran packages

Fixes https://github.com/NixOS/nixpkgs/issues/121808

###### Things done
Followed the steps here: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/r.section.md
after un-applying this manual modification to cran-packages.nix: https://github.com/NixOS/nixpkgs/commit/c4d8bd324f2733d8706e932052bb3f2e50d64ed4#diff-c5bd73865d2247e00b3f9c7114f2a739324a6b69aa6981514ec922f740c25872

Looks like this manual modification isn't needed anymore since the bump of cran bumped arrow to 4.0.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121819` at f695a3eb run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.rpy2</li>
    <li>python39Packages.rpy2</li>
  </ul>
</details>

**Comment by jbedo** [comment]
Can you bump bioconductor to 3.12 (line 6 of `generate-r-packages.R`) and regenerate the bioc package set? That's the correct version to use against our R 4.0.4.

**Comment by Jake-Gillberg** [comment]
So uhh. Testing this thing... Anyone have thoughts on a good way to build all of these R packages and compare the failing ones to ones that were failing before this update? (Failing build of RPostgres is what led me down this road in the first place)

**Comment by jbedo** [comment]
There's a test expression in `test-expression.nix` and a [section](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/r.section.md#testing-if-the-nix-expression-could-be-evaluated) in the docs describing it. It actually fails on this pull request, so there's some fixing to be done. Normally I think we just make sure everything evaluates fine and don't explicitly check everything builds (hence the `--dry-run`).

**Comment by Jake-Gillberg** [comment]
Okay, `--dry-run` is working now. Thanks for the pointer! I confirmed that all of the lines I deleted in `default.nix` were references to packages that were removed from the CRAN repository. ((https://cran.microsoft.com/web/packages/rpg/index.html)[https://cran.microsoft.com/web/packages/rpg/index.html], etc.)

Should be good to merge if the standard isn't to build all of these packages?

**Comment by jbedo** [comment]
Yep in general LGTM now, though you'll probably be asked to squash your commits before it's accepted. I don't have merge privileges so will have to wait for somebody else to show up.

**Comment by collares** [comment]
Result of `nixpkgs-review pr 121819` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.rpy2</li>
    <li>python39Packages.cnvkit</li>
    <li>python39Packages.rpy2</li>
    <li>rstudioWrapper</li>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

**Comment by PhDyellow** [comment]
When someone with merge privileges is ready to act on this,  I had the same problem, but I missed this PR. #122409 is a duplicate that also bumps cran and bioc package sets. #122409 adds a few package fixes as well.

I also submitted #122408, which picks whatever version of BioConductor matches the current R version. I just couldn't figure out how to stop it failing the editor_config checks.

Is there a way to merge PRs?

**Review by peti — COMMENTED** [review]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates. Assuming that there's no major breakage, I'll merge the PR later today.

**Pull request merged**
