### PR TITLE
wireguard: 0.0.20190123 -> 0.0.20190406 [backport 19.03]

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build linuxPackages.wireguard

**Comment by Mic92** [comment]
Do not merge yet. Breaks on all kernels:

```
mnlg.c:16:10: fatal error: libmnl/libmnl.h: No such file or directory
 #include <libmnl/libmnl.h>
          ^~~~~~~~~~~~~~~~~
```

**Comment by flokli** [comment]
wireguard-0.0.20190123 seems to be broken with 5.1 kernel, too:

```
copying path '/nix/store/11sc1qdp5zw27k2836c2l8mvvd330a3f-linux-5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/07bp90bwm8gc8sxk0y54h42izk981xv3-source' from 'https://cache.nixos.org'...
copying path '/nix/store/hah16zwyf4glgijym2acrrxx378nac56-linux-5.1-dev' from 'https://cache.nixos.org'...
unpacking sources
unpacking source archive /nix/store/07bp90bwm8gc8sxk0y54h42izk981xv3-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
  CC [M]  /build/source/src/main.o
In file included from <command-line>:0:0:
/build/source/src/compat/compat.h:783:10: fatal error: net/netfilter/nf_nat_core.h: No such file or directory
 #include <net/netfilter/nf_nat_core.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/nix/store/hah16zwyf4glgijym2acrrxx378nac56-linux-5.1-dev/lib/modules/5.1.0/source/scripts/Makefile.build:276: /build/source/src/main.o] Error 1
make[3]: *** [/nix/store/hah16zwyf4glgijym2acrrxx378nac56-linux-5.1-dev/lib/modules/5.1.0/source/Makefile:1571: _module_/build/source/src] Error 2
make[2]: *** [Makefile:169: sub-make] Error 2
make[1]: *** [Makefile:15: __sub-make] Error 2
make: *** [Makefile:36: module] Error 2
builder for '/nix/store/xnz80bh68mij6ca8k9fkgrxa5z7s6rf0-wireguard-0.0.20190123.drv' failed with exit code 2
```

**Comment by flokli** [comment]
Turns out, the 0.0.20190406 breakage was fixed on master in 2c3ab523d3fc47c2bbb1a34e09096e02be884fde, but not backported yet.

Rebased this PR and cherry-picked on top, builds fine for me.

**Comment by mweinelt** [comment]
Successfully compiles and tests are working.

**Pull request merged**
