### PR TITLE
openblas: 0.3.4 -> 0.3.5, rework a bit

### PR DESCRIPTION
**Pull request by dtzWill**
* prefer attributes
* let nix string-ify for us
* bools become the same 1/0, FWIW, in case that matters

###### Motivation for this change

https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.5

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
This needs a rebase after my CC change.

**Comment by dtzWill** [comment]
rebased! Basically same changes but across a few commits to make easier for review, squash as preferred (or LMK and i'll do so).

**Review by markuskowa — APPROVED** [review]

**Comment by dtzWill** [comment]
FWIW #54886 conflicts with this, I resolved it in my tree with this result: https://github.com/dtzWill/nixpkgs/blob/1c5bfc30a7fcf22138adb8f8441d2c40dda201e1/pkgs/development/libraries/science/math/openblas/default.nix

Quick notes about what was done and why: https://github.com/dtzWill/nixpkgs/commit/1c5bfc30a7fcf22138adb8f8441d2c40dda201e1

Thought I'd share for whoever/whenever master and staging get merged.

**Comment by vcunat** [comment]
This commit (1f046700) broke openblas build on aarch64-linux.  (I re-tried the commit itself and its parent.)  Error logs e.g. on Hydra: https://hydra.nixos.org/build/87629037

**Comment by ttuegel** [comment]
Is it related to the `DYNAMIC_ARCH` and `USE_OPENMP` changes?

**Comment by dtzWill** [comment]
Hmm, two things I noticed:

1) While `builtins.toString true` is `"1"`, apparently `builtins.toString false` is `""`.  So the values that used to be "0" are now empty, which likely has a different meaning to openblas's build system.  Sorry, I really thought i checked that :/.

2) Why is fortran a buildPackages like HOSTCC? Is that correct? Whatever the right answer is, we may need to fix/change the prefix used to match its role.

3) I don't know if this is the trouble but FWIW this enables tests in the non-cross case (as usual), we were apparently previously disabling them unless it was cross... which got overridden to disabled by mkDerivation anyway >.<.

Very sorry re:1, although it's a shame because I like this much better.  But broken is worse than ugly! :P

**Comment by vcunat** [comment]
Note: I just merged this into master via c40f2114992.  I didn't feel like attempting to solve this as well, and I guess blas on aarch64 isn't such a big deal, so we might afford to break it temporarily (I hope).

**Comment by vcunat** [comment]
BTW, this darwin error also seems new: https://nix-cache.s3.amazonaws.com/log/agn0dzc87gb4mnrf3kyswr30zbr92kmm-openblas-0.3.5.drv

**Pull request merged**
