### PR TITLE
llm: init at version 0.8

### PR DESCRIPTION
**Pull request by asimpson**
###### Description of changes

[llm](https://github.com/simonw/llm) provides a command line interface to working with various models provided by OpenAI.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by asimpson** [comment]
Keeping this on `v.0.4` for now while I wait for https://github.com/NixOS/nixpkgs/pull/242543 to be merged since `v0.5` requires v2 of pydantic.

**Comment by aldoborrero** [comment]
I was working on adding support to [`llm`](https://github.com/simonw/llm) on my own flake.

The latest version of the code (with support to version `0.11`):

```nix
{
  lib,
  python3Packages,
  fetchPypi,
  fetchFromGitHub,
}: let
  sqlite-utils = python3Packages.buildPythonApplication rec {
    pname = "sqlite-utils";
    version = "3.35.1";

    src = fetchPypi {
      inherit pname version;
      hash = "sha256-4PA+aXawW9t6XFZFSXGg6YD8Ftv9NRK7073KxPDkNw4=";
    };

    doCheck = false;

    propagatedBuildInputs = [
      click-default-group
      sqlite-fts4
      python3Packages.python-dateutil
      python3Packages.pluggy
      python3Packages.tabulate
    ];
  };

  sqlite-fts4 = python3Packages.buildPythonApplication rec {
    pname = "sqlite-fts4";
    version = "1.0.3";

    src = fetchPypi {
      inherit pname version;
      hash = "sha256-eLBe6vZoDp2+2Jhr3gEenAhqBssMkxs899qUwhTokww=";
    };

    doCheck = false;
  };

  click-default-group = python3Packages.buildPythonApplication rec {
    pname = "click-default-group";
    version = "1.2.4";
    format = "flit";

    src = fetchFromGitHub {
      owner = "click-contrib";
      repo = "click-default-group";
      rev = "v${version}";
      sha256 = "sha256-9Vk4LdgLDAWG2YCQPLKR6PIVnULmpOoe7RtS8DgWARo=";
    };

    propagatedBuildInputs = [python3Packages.click];
  };

  sqlite-migrate = python3Packages.buildPythonPackage rec {
    pname = "sqlite-migrate";
    version = "0.1a2";
    format = "pyproject";

    src = fetchPypi {
      inherit pname version;
      sha256 = "sha256-wztAqe3TW0SQ4JX1XPWeA4KNJci5c3fNih97cmlPwRE=";
    };

    nativeBuildInputs = with python3Packages; [setuptools];

    propagatedBuildInputs = [
      sqlite-utils
    ];
  };

  python-ulid = python3Packages.buildPythonApplication rec {
    pname = "python-ulid";
    version = "1.1.0";

    src = fetchPypi {
      inherit pname version;
      sha256 = "sha256-X7XkqR24ypPok4phM2Cz3vKZtg1B+Ecnmow5ybLpxl4=";
    };

    propagatedBuildInputs = [
      python3Packages.setuptools
      python3Packages.pytest
      python3Packages.freezegun
    ];

    preBuild = ''
      cat > setup.py << EOF
      from setuptools import setup
      if __name__ == "__main__":
        setup()
      EOF
    '';
  };

  llm = python3Packages.buildPythonApplication rec {
    pname = "llm";
    version = "0.11";

    src = fetchFromGitHub {
      owner = "simonw";
      repo = pname;
      rev = "refs/tags/${version}";
      hash = "sha256-eIoG92YczxvFEZW1/QElz67iDWGc9IA1i5VwLYXELmQ=";
    };

    propagatedBuildInputs = with python3Packages; [
      click-default-group
      openai
      pip
      pluggy
      pydantic
      pyyaml
      sqlite-migrate
      sqlite-utils
      python-ulid
    ];

    doCheck = false;

    meta = with lib; {
      homepage = "https://github.com/simonw/llm";
      description = "Access large language models from the command-line";
      license = licenses.asl20;
    };
  };
in
  llm
```

From a cursory glance, I see `python-ulid` support has been added to nixpkgs [in this commit](https://github.com/NixOS/nixpkgs/commit/21aa8c0b7e254340afb5cae96c3ec66704bb780f).

Bear in mind, ideally, support should add support as well to the plugins.

**Comment by aldoborrero** [comment]
Just to keep informed, there's an updated effort to bring `llm` and its plugins to the latest version (as of today's writing `0.11`).

I think it's better to close this PR in favor of the new one. I'll add appropiate credit to the maintainer's list once all issues are solved.

**Comment by asimpson** [comment]
No worries, thanks for the update!

**Pull request closed without merging**
