### PR TITLE
firefox-unwrapped: add nss to LD_LIBRARY_PATH

### LINKED ISSUE #78961: Discord can't open links in Firefox
## Issue description
When using current NixOS 19.09 versions for Discord and Firefox, you cannot open links by clicking on them in Discord anymore. 

### Steps to reproduce

Run `nix-shell -p discord --run Discord` while having firefox open.
Log in and attempt to open any link, or perform any interaction that would open a website in firefox. It will fail silently. 
For an error message, press ctrl-shift-i to bring up the inspector and type the following into the console:
```js
child_process = require("child_process")
child_process.execSync("firefox https://example.com")
```
This will fail with an error message like
```
Uncaught Error: Command failed: firefox example.com
XPCOMGlueLoad error for file /nix/store/bzr1jrf17ypd6l1rhxi4zn572sa0288b-firefox-unwrapped-72.0.2/lib/firefox/libxul.so:
/nix/store/002anz2c55ml3hwf2niz42541iwq96gh-nss-3.46.1/lib/libnss3.so: version `NSS_3.47' not found (required by /nix/store/bzr1jrf17ypd6l1rhxi4zn572sa0288b-firefox-unwrapped-72.0.2/lib/firefox/libxul.so)
Couldn't load XPCOM.
```
This error message lead me to the assumption that a libnss version mismatch between Firefox and Discord is to blame, and indeed overriding the libnss version of the discord package to a newer one fixes the problem, so that a derivation built from the expression below can normally open links. 
```nix
with import <nixpkgs> {};

pkgs.discord.override {
    nss = pkgs.nss_3_49_2;
}
```
This fix doesn't seem to have had any negative impact after a few days of running with it.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1965.274e095f761 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1965.274e095f761"`
 - channels(cassidy): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes https://github.com/NixOS/nixpkgs/pull/119434#issuecomment-1188433605, fixes https://github.com/NixOS/nixpkgs/issues/78961

Untested, obviously.

### CODE REVIEW

**Comment by mweinelt** [comment]
It is unclear to me how passing NSS (the network security services) is supposed to fix what you claim it does.

**Comment by ncfavier** [comment]
As mentioned in the linked issues, the problem currently is that Firefox and Discord use different versions of nss (`nss_latest` 3.81 and `nss` 3.68.4 respectively), **and** the Discord wrapper adds its version of nss to LD_LIBRARY_PATH but the Firefox wrapper doesn't, so the Discord one wins and Firefox is unhappy.

Adding `nss_latest` to LD_LIBRARY_PATH in the Firefox wrapper fixes the problem, as can be tested with this overlay:
```nix
self: super: {
  firefox = super.firefox.overrideAttrs (old: {
    libs = old.libs + ":" + lib.makeLibraryPath [ pkgs.nss_latest ];
  });
}
```

Now, the thing I just realised is that adding this to the `firefox-unwrapped` wrapper won't solve the issue, because the `wrapFirefox` wrapper ignores that wrapper and wraps `firefox-unwrapped/bin/.firefox-wrapped` directly. So we'd need to add it to the `wrapFirefox` wrapper instead, but this wrapper is also used by other applications and I'm not sure those applications need or want `nss_latest` in their LD_LIBRARY_PATH...

**Comment by ncfavier** [comment]
Maybe we can add an `extraLibs` argument to `wrapFirefox` and pass `extraLibs = [ nss_latest ];` for firefox.

**Comment by fpletz** [comment]
> Discord wrapper adds its version of nss to LD_LIBRARY_PATH but the Firefox wrapper doesn't, so the Discord one wins and Firefox is unhappy.

Well, then discord is the problem. You would face the same issues ff you open other Firefox-derived browsers or applications depending on NSS for that matter. The solution is not to fix all apps depending on NSS. Can't we use patchelf for discord instead?

**Comment by ncfavier** [comment]
That would be great.

> I don't know much about Discord's packaging but perhaps it would be possible to use autoPatchelfHook instead of setting LD_LIBRARY_PATH?

> autoPatchelfHook will not work for dlopened libraries. Not sure what the ratio of linked/loaded libraries is.

@jtojnar is this still true? From `dlopen(3)`:

> o   (ELF only) If the calling object contains a DT_RUNPATH tag, then the directories listed in that tag are searched.

Since autoPatchelfHook *already* adds nss to discord's DT_RUNPATH, would simply removing nss from LD_LIBRARY_PATH be enough? Could this also be done for other libs?

**Comment by vcunat** [comment]
I believe it doesn't work because it won't detect that a library might be loaded by `dlopen()`.  *Manually* patchelfing (additionally) should work.  Maybe if you avoid some step where it automatically strips "unreferenced" ones.

**Comment by ncfavier** [comment]
```
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/dgzfhhwpsz3idz7j9pzp0qw05skxg7xr-discord-0.0.18/opt/Discord:/nix/store/p7paszzma218x9hpp8423k87dxj6f7nc-glib-2.72.3/lib:/nix/store/lvjcra8rxnss51bk5p67rd9x6pnlsi8r-libxshmfence-1.3/lib:/nix/store/6ddsjj2qjx4fri2akq5xnf25sxhip5p3-nss-3.68.4/lib:/nix/store/gzf7jnpc8c18jfzg4324wrshh1m4kb8v-nspr-4.34/lib:/nix/store/9ph75bbm1zhsz2pdf4k8jgj6wjjpnqlm-atk-2.38.0/lib:/nix/store/0ffdbny15hvzr5byh1fr5caaygim71l9-at-spi2-atk-2.38.0/lib:/nix/store/wcpl6nwja4s3lrcdz1r26vkbrga4p716-dbus-1.14.0-lib/lib:/nix/store/cq2fnzkg5lirbsbsmwnv324hcqw996jl-libdrm-2.4.112/lib:/nix/store/0aczmiyhwmnv5c705008czyb829aaicg-gdk-pixbuf-2.42.8/lib:/nix/store/jwg43f7874jk9a4p15cab6n4125rckhk-gtk+3-3.24.34/lib:/nix/store/d9s895jykbh2945xb6p620z22fkw1nil-pango-1.50.8/lib:/nix/store/wiz2aaxcnz7iv8p3hlhrlmdwymakj15w-cairo-1.16.0/lib:/nix/store/jzyxxfly9wgdrsmc9gcycqqllslhf014-libX11-1.7.2/lib:/nix/store/pidfd5l7z7z96mzzk64p8kd6bvkaz8js-libXcomposite-0.4.5/lib:/nix/store/47ywncbak6wcx3rsgcwdkhnhlmhy1cbh-libXdamage-1.1.5/lib:/nix/store/j14mh1x96wfhbfmp2lg3ysisw8qkn8ax-libXext-1.3.4/lib:/nix/store/dc1aizizzxh2f9aq2hd0fii623z7kc8h-libXfixes-6.0.0/lib:/nix/store/4j6q054h6wbf82d6pks5mbpd7mi23hz9-libXrandr-1.5.2/lib:/nix/store/x3alcyvp8aiglkhh8hry61hwba2mxgbz-expat-2.4.8/lib:/nix/store/wmhh93gh8hd42bdvd2f73nvrjwm8v5hv-libxcb-1.14/lib:/nix/store/gskc4c7hy3q4yvyyby6va8gdxjc2h628-libxkbcommon-1.4.1/lib:/nix/store/mf6r6ynz7xgwjyvj18yiasvsfja29diw-mesa-22.1.4/lib:/nix/store/j03jjz5wfw48mnwv592nc463ndlxa416-alsa-lib-1.2.7.1/lib:/nix/store/28qw3cyf7g1bac8kmgg4dz1hmsmr2qhm-at-spi2-core-2.44.1/lib:/nix/store/qps576jv35898jqj1lxgwi8dmcpdqh7n-cups-2.4.2-lib/lib]
```

nss is already in there.

**Comment by vcunat** [comment]
So if it still doesn't work, could it be that the `dlopen()` is called from some library and not the main executable?  I vaguely remember there was something surprising around that.

**Comment by ncfavier** [comment]
It *does* work if I remove nss from LD_LIBRARY_PATH!

**Comment by ncfavier** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/186603

**Pull request closed without merging**
