### PR TITLE
pg_journal: init at 0.2.0 & fixed some PostgreSQL plugins related issues

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

Triggered by [Discourse: Q: Services logging to stderr preferred over logging to syslog?](https://discourse.nixos.org/t/q-services-logging-to-stderr-preferred-over-logging-to-syslog/588) I packaged the [`pg_journal`](https://github.com/intgr/pg_journal) plugin that logs PostgreSQL messages to the systemd journal.

###### Things done

* packaged `pg_journal` at version 0.2.0 (including some patches)

* fixed some PostgreSQL plugins related issues.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @ocharles as maintainer of the `postgresql` package. Ollie, what do you think?

### CODE REVIEW

**Comment by basvandijk** [comment]
@grahamcofborg test postgresql

**Comment by basvandijk** [comment]
@thoughtpolice this will probably conflict with your #38698.

**Comment by basvandijk** [comment]
@thoughtpolice it's probably best to rebase my work on your #38698 right?

* This commit can probably be dropped since you now have `postgresqlPackages`:
[postgresql: override every plugin with the configured postgresql package](https://github.com/NixOS/nixpkgs/pull/44379/commits/e0c8246170e5cbde37b23bc9557c11970e729ffa)

* You don't seem to be doing what I'm doing in
[postgresql: always create the bin directory in the postgresql-and-plugins derivation]( https://github.com/NixOS/nixpkgs/pull/44379/commits/062d8e9d8f66a677ef83766f71d75d260ee718ec) which fixes https://github.com/NixOS/nixpkgs/issues/22653 so this probably needs to be kept.

* [pg_journal: init at 0.2.0](https://github.com/NixOS/nixpkgs/pull/44379/commits/305398534d231545e56cb2a5e9e8e5de7afbdf79) can just be integrated in your new `pkgs/servers/sql/postgresql/ext` directory.

**Comment by thoughtpolice** [comment]
@basvandijk Yes, I think rebasing it would be appropriate, thank you! I can actually integrate your changes into my branch directly...

In the mean time maybe I should just add my own name to the maintainers field so I'm CC'd in the future... and get done pushing that work in. :)

**Comment by thoughtpolice** [comment]
@basvandijk These changes are now incorporated in my branch in #38698, but I didn't include the PostgreSQL tests you added for `pg_journal` (I still have some WIP changes to update more things before merging.)

**Comment by basvandijk** [comment]
@thoughtpolice thank you!

**Pull request closed without merging**
