### PR TITLE
mautrix-meta: adds maintainer, adds automatic updating

### PR DESCRIPTION
**Pull request by eyJhb**
## Description of changes
Based on my interaction with tulir here https://github.com/mautrix/meta/issues/99 , mautrix-meta should track main instead of the releases, as it seems basically anything else is not really supported, and we don't get releases that often ( https://docs.mau.fi/bridges/general/troubleshooting.html#why-is-the-latest-release-old ).

These changes adds me as maintainer, as I use this package quite a lot, it adds automatic updating of the package to latest unstable, and it bumps the version to latest unstable.

@Rutherther what do you think of tracking latest unstable instead? It seems annoying that it needs to be done, but based on the response from the maintainer, it seems like it's the best way to go about it.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Hmm, the issue referenced in the one you linked to was closed as fixed *before* the latest stable release. I’m wondering if there was just a communication issue here and upstream thought you were running a version other than the most recent stable one? 1.5 months isn’t very long since a release…

**Comment by eyJhb** [comment]
@emilazy I reached out on Matrix afterwards, it is not a communication error. They fully understand that I'm using the latest release, but they don't want to make a new release with the fixes, and maybe, maybe not, 0.3.2 does not contain the fixes (even though as you state, the issue was closed before a release was made). I've added a screenshot with the very short "correspondence" :)

image

Yeah, that statement is also what worries me quite a lot. This might just be an edge case, that's _very_annoying (see screenshot in my linked issue in the first comment), and maybe it's not a problem in the future.

Whatever way we end up going, having the `updateScript` would be nice for the future anyways (we can just change it to track releases, depending on what we figure out here).

I originally opened this PR as a way of getting feedback. Should have been an issue instead maybe, but I've changed the status to reflect it's WIP :)

**Comment by emilazy** [comment]
Okay, if upstream effectively won’t support their stable releases and they have known bugs then we should package unstable. If it breaks because of updates… well… we’re working within the constraints of the authors of the software. If you think this is ready we can merge it. I think we should probably backport to 24.05 too given the evident support policy, though I’m not totally confident.

cc @sumnerevans in case there is anything more to add on the upstream end

**Comment by Rutherther** [comment]
How often does the script get executed? There is supposed to be one release per month based on upstream FAQ. How many times a month will this get a bump - is it worth it?

Though it seems there was no release on 16th of August, so maybe this is the wrong question.

Btw. I don't get this issue since update to 0.3.2

**Comment by eyJhb** [comment]
> How often does the script get executed? There is supposed to be one release per month based on upstream FAQ. How many times a month will this get a bump - is it worth it?
> 
> Though it seems there was no release on 16th of August, so maybe this is the wrong question.
> 
> Btw. I don't get this issue since update to 0.3.2

I think if we're updating using the latest unstable commit, then the updater bot might only call it when a new release is available according to repology. So it might be a quite manual process. However, this might be a quite hasty decision on my side, which was born out of how the maintainer reacted, giving me no information, etc. etc.

There was no update on the 16th of August, and I assume it was because of "some issue/blocker", as is written in the  FAQ as well.

I still have the issue even on 0.3.2 sadly. But it is much better than it was previously :)

-----

I think as of now, I'll remove the latest commit (bumping it to unstable), and I'll keep myself as maintainer together with @Rutherther of course. I'll keep the update script as well, but it will track the releases, instead of latest commit (also given there happens a lot of commits here and there).

In the future we might decide that it should track the latest commit in the branch, but it might then be a good idea to split it up into a `mautrix-meta` and `mautrix-meta_unstable`, or something along those lines.

Does this sound reasonable?

**Comment by Rutherther** [comment]
Thanks for the changes. I noticed we already have passthru assigned, so maybe it would be worth while putting the update script there rather than having separate passthru entry? Or is there a reason why you went this way?

**Comment by eyJhb** [comment]
> Thanks for the changes. I noticed we already have passthru assigned, so maybe it would be worth while putting the update script there rather than having separate passthru entry? Or is there a reason why you went this way?

No reason at all, I put them together now :)

**Review by Rutherther — APPROVED** [review]
Thank you

**Pull request merged**
