### PR TITLE
openxray: make it work again

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Needed after #72199
See https://github.com/OpenXRay/xray-16/issues/518

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Please add the meta information.

**Comment by gnidorah** [comment]
@FRidh to cryptopp? Is that required? openxray is unfree and not built on hydra

**Comment by FRidh** [comment]
indeed for cryptopp. Derivations should have meta information.

**Comment by gnidorah** [comment]
@FRidh Done

**Review by Lassulus — APPROVED** [review]
tested with nix-review, seems to work

**Comment by gnidorah** [comment]
@FRidh @Lassulus thanks!

**Pull request merged**
