### PR TITLE
Switch default openFirewall to false for NixOS services

### PR DESCRIPTION
**Pull request by rapenne-s**
###### Description of changes

openFirewall should be set to false all the time, except for openssh, this avoids surprises to users who may not want to expose an enabled service without explicit consent.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
We could either list the change in the release notes as a breaking action item for users or don't set a default value which will force users to provide a value.

**Comment by rapenne-s** [comment]
> We could either list the change in the release notes as a breaking action item for users or don't set a default value which will force users to provide a value.

I see, a first step would be to not define the value so nixpkgs-unstable users will need to explicitly set it to true or false on their config, and after a while we could set it to false?

**Comment by raphaelr** [comment]
another one https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/kdeconnect.nix

**Comment by aanderse** [comment]
If you're going to do both approaches it might make sense to use `system.stateVersion` and set a `default` value for new versions of NixOS to avoid forcing new users to choose.

Sounds good.

**Comment by aanderse** [comment]
Oh... I just noticed this in the release notes:

> The services.unifi.openPorts option default value of true is now deprecated and will be changed to false in 22.11. Configurations using this default will print a warning when rebuilt.

**Review by Ma27 — APPROVED** [review]
None of these services should render the server running these unreachable, so reverting or fixing should be relatively trivial for an administrator. `stateVersion` is usually used if a change will impact user-data if not deployed correctly (e.g. changes to the postgresql module). Adding an entry to the release-notes should thus be sufficient IMHO (but I wouldn't want to merge it without one).

**Review by tobim — APPROVED** [review]

**Comment by aanderse** [comment]
Thanks for the feedback @Ma27. Let's go with what you said 👍

**Comment by rapenne-s** [comment]
should I add a commit for the releases-notes? I never done that before

**Comment by Ma27** [comment]
Yes, please. In case you don't know how to do it, I usually do this:

* Add a note in `nixos/doc/manual/release-notes/rl-2305.section.md` (below "Backward Incompatibilities")
* run `./nixos/doc/manual/md-to-db.sh`
* Test / Review your changes by running `nix-build nixos/release.nix -A manualHTML.x86_64-linux` and opening via e.g. `firefox ./result/share/doc/nixos/index.html`.

**Pull request closed without merging**
