### PR TITLE
gcc14: 14.1.0 -> 14.2.0

### PR DESCRIPTION
**Pull request by trofi**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 331603` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>fastStdenv</li>
    <li>gcc14</li>
    <li>gcc14.info</li>
    <li>gcc14.man</li>
    <li>gcc14Stdenv</li>
    <li>gccgo14</li>
    <li>gccgo14.info</li>
    <li>gccgo14.man</li>
    <li>gfortran14</li>
    <li>gfortran14.info</li>
    <li>gfortran14.man</li>
    <li>gnat14</li>
    <li>gnat14.info</li>
    <li>gnat14.man</li>
  </ul>
</details>

**Comment by pbsds** [comment]
I reproduced the aarch64-darwin build issue on the nix-commuity darwin builder, the fault is in https://github.com/trofi/nixpkgs/blob/9b6543bd8082f76c75873fe5f5f2284d0eef1efb/pkgs/development/compilers/gcc/patches/default.nix#L149

**Comment by trofi** [comment]
No 14.2.0 patches yet at https://github.com/Homebrew/formula-patches/tree/master/gcc. Can try at https://github.com/iains/gcc-14-branch

**Comment by trofi** [comment]
> No 14.2.0 patches yet at https://github.com/Homebrew/formula-patches/tree/master/gcc. Can try at https://github.com/iains/gcc-14-branch

Updated the patch.

> I reproduced the aarch64-darwin build issue on the nix-commuity darwin builder, the fault is in https://github.com/trofi/nixpkgs/blob/9b6543bd8082f76c75873fe5f5f2284d0eef1efb/pkgs/development/compilers/gcc/patches/default.nix#L149

Please try the updated branch. The patch at least applies on `x86_64-linux`.

**Comment by pbsds** [comment]
the patch applies :+1:

**Pull request merged**
