### PR TITLE
zoom-us: set qt plugin paths in wrapper

### PR DESCRIPTION
**Pull request by tadfisher**
###### Motivation for this change

Set `QT_QPA_PLATFORM_PLUGIN_PATH` and `QT_PLUGIN_PATH` in the wrapper script to address https://github.com/NixOS/nixpkgs/pull/42922#issuecomment-403212690.

Remove `procps` and `pciutils` from `buildInputs` to address https://github.com/NixOS/nixpkgs/pull/42922#pullrequestreview-135203500.

Add myself to maintainers to address https://github.com/NixOS/nixpkgs/pull/42742#issuecomment-403212248.

cc maintainers: @danbst

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danbst** [comment]
Doesn't evaluate
```
error: attribute 'qtcompatversion' missing
```

**Comment by tadfisher** [comment]
@danbst d'oh! Updated.

**Comment by danbst** [comment]
Zoom runs now, but doesn't show GUI. Like, at all, nothing except console output.

I've used debug build (https://ota.zoom.us/Linux/64bit/zoom_withlog_latest_x86_64.tar.xz) and cleared my `~/.zoom`. This is the log
```
zoom started.
[17088:41208873:07-09/00:51:02.838:ERROR:CmmFileName_linux.cc(18)] CreateFolder:/home/danbst/.zoom
[17088:41208873:07-09/00:51:02.886:ERROR:CmmFileName_linux.cc(18)] CreateFolder:/home/danbst/.zoom/data
[17088:41208873:07-09/00:51:02.905:ERROR:zKeyValueTable.cpp(135)] [CZoomKeyValueTable::AttachDB] search table sql failed and create table.
[17088:41208873:07-09/00:51:02.913:ERROR:zKeyValueTable.cpp(135)] [CZoomKeyValueTable::AttachDB] search table sql failed and create table.
[17088:41208873:07-09/00:51:02.918:ERROR:zUserAccountTable.cpp(180)] [CZoomUserAccountTable::NotifyDBNeedUpgrade] search table sql failed.
[17088:41208873:07-09/00:51:02.959:ERROR:zClientActionTable.cpp(54)] [CZoomClientActionTable::AttachDB] search table sql failed.
[17088:41208873:07-09/00:51:02.990:ERROR:zDataEventListeners.cpp(207)] [CZoomDataEventListners::NotifyCreateTable] failed for: 54462256
[17088:41208873:07-09/00:51:02.990:ERROR:zDataEventListeners.cpp(207)] [CZoomDataEventListners::NotifyCreateTable] failed for: 54462704
[17088:41208873:07-09/00:51:03.028:ERROR:zDataEventListeners.cpp(207)] [CZoomDataEventListners::NotifyCreateTable] failed for: 54465664
[17088:41208873:07-09/00:51:03.042:ERROR:zDataEventListeners.cpp(207)] [CZoomDataEventListners::NotifyCreateTable] failed for: 54462256
[17088:41208873:07-09/00:51:03.042:ERROR:zDataEventListeners.cpp(207)] [CZoomDataEventListners::NotifyCreateTable] failed for: 54465664
[17088:41208873:07-09/00:51:03.065:ERROR:zUserAccountTable.cpp(180)] [CZoomUserAccountTable::NotifyDBNeedUpgrade] search table sql failed.
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 54:13:79:91:A6:8F][client: Linux][OS: NixOS 18.09.pre.5da8543 (Jellyfish)][Hardware: CPU Core:2 Frenquency:2.5 G Memory size:15951MB CPU Brand:Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz GPU Brand:][Req ID: ]
[17088:41208873:07-09/00:51:03.145:ERROR:PTApp.cc(562)] [CSBPTAppModuleClient::HandleUrlAction] Failed to parse action for error:4
Linux Client Version is 2.2.128200.0702
QSG_RENDER_LOOP is
XDG_CURRENT_DESKTOP = GNOME;   GDMSESSION = gnome3
Graphics Card Info:: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name: gnome3
[17088:41208873:07-09/00:51:03.498:ERROR:ZoomDiskIORequest.cpp(78)] [DiskIOReq_SimpleReadAll::ProcessJob] Failed to open file:/home/danbst/.zoom/data/zmonitorlog.bin System Error:2
[17088:41208873:07-09/00:51:03.704:ERROR:CmmAudioSessionMgr.cpp(4944)] [CmmAudioSessionMgr::InitAuidoObj()] m_bEnableStereo:0IsUseOriginalSound:0
[17088:41208873:07-09/00:51:04.232:ERROR:SBAutoUpgradeModuleClient.cc(74)] [CSBAutoUpgradeModuleClient::CheckUpdateResponse] state is: 0
[17088:41208873:07-09/00:51:04.232:ERROR:ZAUResponseContent.cpp(61)] [CAUResponseContent::Parse] Miss key or value. [key=Installer-name][value=
[17088:41208873:07-09/00:51:04.232:ERROR:ZAUResponseContent.cpp(61)] [CAUResponseContent::Parse] Miss key or value. [key=ahcab-name][value=
[17088:41208873:07-09/00:51:04.232:ERROR:ZAUResponseContent.cpp(61)] [CAUResponseContent::Parse] Miss key or value. [key=sipcab-name][value=
[17088:41208873:07-09/00:51:04.232:ERROR:ZAUResponseContent.cpp(61)] [CAUResponseContent::Parse] Miss key or value. [key=codesnippet-name][value=
[17088:41208873:07-09/00:51:04.232:ERROR:ZAUResponseContent.cpp(61)] [CAUResponseContent::Parse] Miss key or value. [key=fullcab-name][value=
[17088:41208873:07-09/00:51:04.232:ERROR:ZAUResponseContent.cpp(61)] [CAUResponseContent::Parse] Miss key or value. [key=Package32-name][value=
```

The only difference in output with previous Zoom version is that line:
```
Graphics Card Info:: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
```
previously it was
```
Graphics Card Info::
```

If this is because of some drivers issue, then the question - why it worked before?

**Comment by tadfisher** [comment]
@danbst That's strange. Here's the output when running on my machine:

```
zoom started.
Qt: Session management error: Could not open network socket
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: E4:B3:18:AD:BE:70][client: Linux][OS: NixOS 18.09pre144959.be1461fc0ab (Jellyfish)][Hardware: CPU Core:2 Fre
nquency:2.6 G Memory size:19809MB CPU Brand:Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz GPU Brand:][Req ID: ]                                                   
Linux Client Version is 2.2.128200.0702
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = GNOME;   GDMSESSION = gnome3
Graphics Card Info:: 00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name: gnome3 
qt.scenegraph.general: QSG: basic render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: texture atlas dimensions: 1024x512
qt.scenegraph.general: R/G/B/A Buffers:   8 8 8 8
qt.scenegraph.general: Depth Buffer:      24
qt.scenegraph.general: Stencil Buffer:    8
qt.scenegraph.general: Samples:           -1
qt.scenegraph.general: GL_VENDOR:         Intel Open Source Technology Center
qt.scenegraph.general: GL_RENDERER:       Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
qt.scenegraph.general: GL_VERSION:        3.0 Mesa 18.0.3
qt.scenegraph.general: GL_EXTENSIONS:     GL_ARB_shader_image_load_store GL_EXT_framebuffer_sRGB GL_ARB_vertex_buffer_object GL_ARB_shader_texture_image_sampl
es GL_ARB_shader_stencil_export GL_ARB_ES2_compatibility GL_ATI_texture_float GL_ARB_texture_compression_bptc GL_ARB_pipeline_statistics_query GL_ARB_shading_
language_100 GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_ARB_get_program_binary GL_ARB_texture_query_levels GL_ARB_separate_shader_objects GL_NV_texge
n_reflection GL_ARB_map_buffer_range GL_ARB_texture_compression_rgtc GL_ARB_uniform_buffer_object GL_OES_EGL_image GL_ARB_vertex_program GL_IBM_texture_mirror
ed_repeat GL_EXT_polygon_offset_clamp GL_EXT_separate_specular_color GL_KHR_context_flush_control GL_ARB_multi_bind GL_EXT_draw_instanced GL_ARB_framebuffer_o
bject GL_NV_packed_depth_stencil GL_EXT_texture_compression_rgtc GL_ARB_cull_distance GL_EXT_stencil_wrap GL_EXT_texture_filter_anisotropic GL_INTEL_performan
ce_query GL_ARB_shader_draw_parameters GL_ARB_shader_atomic_counters GL_ARB_stencil_texturing GL_ARB_texture_filter_anisotropic GL_ARB_sample_shading GL_ARB_c
onservative_depth GL_EXT_texture_env_combine GL_EXT_timer_query GL_ARB_shading_language_packing GL_NV_primitive_restart GL_ARB_shader_atomic_counter_ops GL_AM
D_conservative_depth GL_EXT_transform_feedback GL_ARB_vertex_array_object GL_ARB_texture_float GL_ARB_texture_non_power_of_two GL_EXT_texture_sRGB_decode GL_I
NGR_blend_func_separate GL_ARB_shadow GL_ARB_multisample GL_ARB_draw_elements_base_vertex GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_sRGB GL_AR
B_texture_compression GL_EXT_draw_buffers2 GL_ARB_derivative_control GL_ARB_compressed_texture_pixel_storage GL_ARB_texture_view GL_ARB_color_buffer_float GL_
IBM_multimode_draw_arrays GL_ARB_fragment_program GL_ARB_vertex_attrib_binding GL_ARB_clip_control GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanc
ed_coherent GL_SGIS_texture_lod GL_ARB_seamless_cube_map GL_ARB_shader_storage_buffer_object GL_ARB_ES3_compatibility GL_ARB_draw_buffers_blend GL_EXT_stencil
_two_side GL_ATI_draw_buffers GL_ARB_texture_rectangle GL_ARB_polygon_offset_clamp GL_ARB_sync GL_ARB_transform_feedback2 GL_ARB_map_buffer_alignment GL_ARB_t
ransform_feedback3 GL_ARB_vertex_array_bgra GL_ARB_vertex_shader GL_S3_s3tc GL_ARB_debug_output GL_ARB_shader_bit_encoding GL_ARB_texture_storage_multisample 
GL_NV_blend_square GL_ARB_texture_cube_map GL_AMD_draw_buffers_blend GL_EXT_multi_draw_arrays GL_ARB_shader_texture_lod GL_EXT_texture_env_add GL_ANGLE_textur
e_compression_dxt3 GL_ARB_sampler_objects GL_ANGLE_texture_compression_dxt5 GL_EXT_blend_subtract GL_EXT_bgra GL_EXT_texture_snorm GL_ARB_transpose_matrix GL_
ARB_internalformat_query GL_AMD_shader_stencil_export GL_MESA_texture_signed_rgba GL_ARB_texture_cube_map_array GL_EXT_draw_range_elements GL_ARB_provoking_ve
rtex GL_EXT_texture_integer GL_ARB_transform_feedback_instanced GL_ARB_clear_texture GL_ARB_texture_rg GL_EXT_blend_func_separate GL_ARB_fragment_shader GL_AR
B_shader_objects GL_ARB_occlusion_query GL_ARB_shading_language_420pack GL_ARB_depth_texture GL_ARB_shader_image_size GL_ARB_texture_multisample GL_ARB_textur
e_env_add GL_EXT_packed_pixels GL_EXT_texture_rectangle GL_EXT_shader_samples_identical GL_MESA_window_pos GL_EXT_blend_equation_separate GL_SUN_multi_draw_ar
rays GL_ARB_draw_instanced GL_ARB_conditional_render_inverted GL_EXT_vertex_array_bgra GL_ARB_program_interface_query GL_ARB_texture_gather GL_ARB_arrays_of_a
rrays GL_ARB_texture_env_dot3 GL_EXT_fog_coord GL_ARB_compute_shader GL_EXT_abgr GL_EXT_texture_compression_s3tc GL_ARB_robust_buffer_access_behavior GL_ARB_i
nternalformat_query2 GL_EXT_packed_depth_stencil GL_EXT_polygon_offset GL_EXT_texture_cube_map GL_ARB_point_sprite GL_ARB_texture_border_clamp GL_ARB_instance
d_arrays GL_ARB_texture_env_crossbar GL_KHR_debug GL_ARB_buffer_storage GL_ARB_half_float_vertex GL_EXT_texture_compression_dxt1 GL_IBM_rasterpos_clip GL_NV_l
ight_max_exponent GL_NV_conditional_render GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_shader_precision GL_ARB_window_pos GL_EXT_provoking_vertex GL_ARB_point_p
arameters GL_EXT_texture3D GL_ARB_depth_clamp GL_AMD_shader_trinary_minmax GL_EXT_shadow_funcs GL_AMD_seamless_cubemap_per_texture GL_ARB_framebuffer_no_attac
hments GL_ARB_query_buffer_object GL_EXT_rescale_normal GL_KHR_robustness GL_NV_texture_rectangle GL_3DFX_texture_compression_FXT1 GL_ARB_pixel_buffer_object 
GL_MESA_pack_invert GL_NV_texture_env_combine4 GL_SGIS_generate_mipmap GL_EXT_shader_integer_mix GL_EXT_packed_float GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_
blend_equation_separate GL_KHR_texture_compression_astc_ldr GL_EXT_texture_object GL_EXT_texture_env_dot3 GL_EXT_gpu_program_parameters GL_EXT_subtexture GL_E
XT_vertex_array GL_NV_texture_barrier GL_ARB_get_texture_sub_image GL_EXT_framebuffer_multisample GL_ARB_occlusion_query2 GL_NV_depth_clamp GL_SGIS_texture_bo
rder_clamp GL_EXT_blend_color GL_ARB_explicit_uniform_location GL_APPLE_packed_pixels GL_EXT_texture_lod_bias GL_ARB_half_float_pixel GL_EXT_blend_minmax GL_A
RB_texture_query_lod GL_KHR_robust_buffer_access_behavior GL_ARB_shader_ballot GL_ARB_depth_buffer_float GL_ARB_timer_query GL_EXT_point_parameters GL_ARB_tex
ture_rgb10_a2ui GL_ARB_framebuffer_sRGB GL_EXT_texture_edge_clamp GL_ATI_texture_env_combine3 GL_KHR_no_error GL_ARB_transform_feedback_overflow_query GL_ARB_
clear_buffer_object GL_OES_read_format GL_ARB_shader_group_vote GL_ARB_texture_stencil8 GL_ARB_texture_barrier GL_ARB_shader_clock GL_EXT_secondary_color GL_A
RB_robustness GL_ARB_copy_buffer GL_EXT_texture_swizzle GL_APPLE_object_purgeable GL_ARB_texture_mirrored_repeat GL_MESA_shader_integer_functions GL_SGIS_text
ure_edge_clamp GL_ATI_separate_stencil GL_ARB_texture_env_combine GL_EXT_framebuffer_blit GL_EXT_framebuffer_object GL_ARB_fragment_coord_conventions GL_ARB_t
exture_mirror_clamp_to_edge GL_ARB_multitexture GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_storage GL_ARB_copy_image GL_EXT_texture_array GL_ARB_expli
cit_attrib_location GL_EXT_texture GL_ARB_blend_func_extended GL_EXT_pixel_buffer_object GL_ARB_draw_buffers GL_ARB_fragment_program_shadow GL_KHR_texture_com
pression_astc_sliced_3d GL_ARB_invalidate_subdata GL_EXT_texture_shared_exponent GL_ARB_texture_swizzle                                                      
qt.scenegraph.general: Max Texture Size: 16384
qt.scenegraph.general: Debug context:    false
```

I am also running Gnome 3. Do you happen to have a DISPLAY variable set when launching?

**Comment by danbst** [comment]
Yes, :0.

I have now no ideas why GUI isn't shown. However I've tried to inject `autoPatchelfHook` into previous expression and got same result - no GUI. So,
a) either patching ELFs make bad things
b) or absence of following libraries (I had to remove those because I don't know which packages are expected to provide necessary libraries) makes bad things: 
```
    $packagePath/platforms/libqeglfs.so
    $packagePath/platformthemes/libqgtk3.so
    $packagePath/egldeviceintegrations/*.so
    $packagePath/QtQuick/*/*.so
```

**Comment by danbst** [comment]
@matthewbauer does Zoom work for you after this change? Do you see GUI?

**Pull request merged**
