### PR TITLE
Add Waydroid

### PR DESCRIPTION
**Pull request by CajuM**
###### Motivation for this change
Waydroid was requested for packaging at #139140

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 140200` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>libgbinder</li>
    <li>libglibutil</li>
    <li>python38Packages.gbinder-python</li>
    <li>python39Packages.gbinder-python</li>
    <li>waydroid</li>
  </ul>
</details>

**Comment by Mindavi** [comment]
I tried this but got stuck at `sudo waydroid init`, because I'm missing a kernel module.

```
(3232854) [23:15:00] % modprobe binder_linux
(3232854) [23:15:00] run: ['modprobe', 'binder_linux']
modprobe: FATAL: Module binder_linux not found in directory /run/current-system/kernel-modules/lib/modules/5.14.7
(3232854) [23:15:00] Failed to load binder driver
(3232854) [23:15:00] modprobe: FATAL: Module binder_linux not found in directory /run/current-system/kernel-modules/lib/modules/5.14.7
(3232854) [23:15:00] ERROR: Binder node "binder" for waydroid not found
```

Do you have a config to enable that module by chance @CajuM?

**Comment by CajuM** [comment]
try:
```nix
{ boot.kernelPackages = pkgs.linuxPackages_xanmod; }
```

**Comment by samueldr** [comment]
This packaging should probably have included a NixOS module to setup things as needed.

**Comment by CajuM** [comment]
I think Weston should work

**Pull request merged**
