### PR TITLE
backintime-qt4: unbreak

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Derivation marked broken but in fact works as expected

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
You need to restore the `meta` attribute to compile things on hydra. I suggest replacing your commit with a complete revert of 119570cd837505e3fad7688bbf64bef650f34736. You would also need to patch the build system to not try to write to `/nix/store` (see commit message for the original commit)

**Comment by freezeboy** [comment]
ok for the meta flag, but I compiled my version and it didn't try to write to `/nix/store`

**Comment by veprbl** [comment]
cc @mguentner

**Comment by veprbl** [comment]
I don't see any changes [1] since it was marked broken, so why would it be fixed

[1] https://github.com/NixOS/nixpkgs/commits/master/pkgs/applications/networking/sync/backintime

**Comment by veprbl** [comment]
I see following in the build log:
```
#install dbus conf
install -d /nix/store/iinzv04gsbwd8kgil9d0kk0jbv4hgxs1-backintime-qt4-1.1.24/../etc/dbus-1/system.d
install --mode=644 net.launchpad.backintime.serviceHelper.conf /nix/store/iinzv04gsbwd8kgil9d0kk0jbv4hgxs1-backintime-qt4-1.1.24/../etc/dbus-1/system.d
```

**Comment by veprbl** [comment]
Also
```
substituteStream(): WARNING: pattern '="/usr/share' doesn't match anything in file '/nix/store/iinzv04gsbwd8kgil9d0kk0jbv4hgxs1-backintime-qt4-1.1.24/bin/backintime-qt4'
```

**Comment by freezeboy** [comment]
true for the substitute I can remove it
but the install are ... in $out, so what is the problem?

**Comment by veprbl** [comment]
> On Nov 1, 2020, at 10:57 PM, freezeboy <notifications@github.com> wrote:
> 
> ﻿
> true for the substitute I can remove it
> but the install are ... in $out, so what is the problem?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
/nix/store/etc/dbus... is a path pointing inside the store but should not be valid to use. This may work poorly for builds without sandboxing. I’m also not sure how this doesn’t fail in the sandboxed build.

On the other note, if backintime-common is not usable without backintime-qt4, we could delete them as broken.

**Comment by freezeboy** [comment]
Ok, I understand, it would mean add the new branch 1.2 maybe

**Comment by freezeboy** [comment]
Updated to 1.2.1 and qt5, currently, there is a problem running the qt5 app, it complains on a missing QPA plugin:

```
Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb, wayland-org.kde.kwin.qpa.

/nix/store/9rsxqq9n3rkcd3x8828a106d0ngvipb5-backintime-qt5-1.2.1/bin/.backintime-qt-wrapped: line 31: 22774 Aborted                 (core dumped) python3 -Es ${APP_PATH}/app.py "$@"
```

**Comment by veprbl** [comment]
You might need to add an explicit `wrapQtAppsHook` to fix the missing Qt plugin problem

**Comment by veprbl** [comment]
I meant not the hook, but an explicit call to `wrapQtApp` https://nixos.org/manual/nixpkgs/stable/#sec-language-qt

**Comment by freezeboy** [comment]
@veprbl I dont see the changes from your fore-pushed, were they rebased commits ?

**Comment by veprbl** [comment]
@freezeboy Sorry, let me document what I've changed:

* added a missing space in https://github.com/NixOS/nixpkgs/commit/3d39d256e818bc6e0976a9452b4e0e32ef93d0ef#diff-189f4e80141b1b016da37c29f47a856298323b67a906b47c5359a38c0f6c4e21R4
* renamed file from qt5.nix to qt.nix
* changed value of the `name` attribute from `backintime-qt5` to `backintime-qt` so that it matches the name of the package in all-packages.nix
* replaced `qt5.callPackage` with `libsForQt5.callPackage`
* replaced `substituteInPlace configure --replace "/.." ""` with `substituteInPlace configure --replace '"/../etc' '"/etc'` to prevent accidental substitutes

**Pull request merged**
