### PR TITLE
darling-dmg: 1.0.4+git20200427 -> 1.0.4-unstable-2023-07-26

### PR DESCRIPTION
**Pull request by Luflosi**
## Description of changes
This updates darling-dmg. I changed the version scheme to [the recommended](https://github.com/NixOS/nixpkgs/blob/73f6fe486eb62ab351b454c8bc475bd54394724a/pkgs/README.md) and commonly used one.
Also add a NixOS VM test so it's easy to verify that this program still works as expected.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by zoriya** [comment]
Is it only me or is there no binary cache for darling? It's been compiling for one-hour on my machine (using current unstable).

**Comment by Luflosi** [comment]
Why does this package even depend on darling? I don't see it in the list of inputs. Can you please tell me how darling-dmg depends on darling?

**Comment by Luflosi** [comment]
I executed nixpkgs-review again and it did not show darling at all. I also executed `nix-store -qR $(nix-instantiate -A darling-dmg)`, which does not show darling as well. So I have no clue what you mean.

**Comment by SuperSandro2000** [comment]
@NixOS/darwin-maintainers could you give a review?

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 323877` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>darling-dmg</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]

**Comment by khaneliman** [comment]
```bash
./results/darling-dmg/bin/darling-dmg
dyld[75590]: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: <5F4BD456-6488-3220-A79C-B8D8E0F85B3F> /nix/store/qbbpysy6y9bw5p4r4ay3r71svcc19iz3-darling-dmg-1.0.4-unstable-2023-07-26/bin/darling-dmg
  Reason: tried: '/usr/local/lib/libfuse.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/lib/libfuse.2.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

**Comment by emilazy** [comment]
This is a FUSE filesystem for opening a native macOS file format. It’s unclear why you would want to run it on macOS. macFUSE does appear to be packaged and aliased to `fuse`, but it requires a kernel module and stuff, so I don’t know if our packaging is really working and up to date and how you’d use it if so.

If anyone really wants to test it they probably need to [install the non‐free parts of macFUSE from upstream](https://osxfuse.github.io).

**Comment by khaneliman** [comment]
Actually, was too quick I see a dylib missing error on runtime

> This is a FUSE filesystem for opening a native macOS file format. It’s unclear why you would want to run it on macOS. macFUSE does appear to be packaged and aliased to `fuse`, but it requires a kernel module and stuff, so I don’t know if our packaging is really working and up to date and how you’d use it if so.
> 
> If anyone really wants to test it they probably need to [install the non‐free parts of macFUSE from upstream](https://osxfuse.github.io).

Ah, yeah... I see the note in the test case. Thanks.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 323877` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>darling-dmg</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]
LGTM

**Pull request merged**
