### PR TITLE
Owncloud: 8.2.0 -> 8.2.1

### PR DESCRIPTION
**Pull request by Mayeu**
Multiple bug fixes and performance improvement.
Hash directly taken from the Owncloud changelog.

### CODE REVIEW

**Comment by aborsu** [comment]
While you're at it...
  owncloud70 = common {
    versiona = "7.0.11";
    sha256 = "21dd75de4ed832f16f577eb6763d04c663ef13251153ba2e8847e3f5799d2ad2";
  };

**Comment by Mayeu** [comment]
You're right! I did not realized this one was also updated :+1:

**Comment by aborsu** [comment]
@mayeu also, so far we stayed with the branch 7.0 because webdav doesn't seem to be working with 8.x. No idea why yet. Do you also have the problem?

**Comment by Mayeu** [comment]
Ha sorry no clue, I was just looking into the repo to see if somebody already did a Owncloud server package...

I'm in the process of deploying an instance anyway, so I'll try to help on this :)

**Comment by garbas** [comment]
restarted travis job

**Comment by garbas** [comment]
@Mayeu tnx!

**Pull request closed without merging**
