### PR TITLE
quickemu: 4.0 -> 4.3

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes
I thought OVMFFull is needed for secureboot and TPM. But it seems swtpm doesn't work for me. It doesn't work with virt-manager either. So I failed to install win 11 but win 10 works.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FedX-sudo** [comment]
Yes. On my system I have passed-though OVMF Full in an override, and have been unable to get Windows11 to boot. 

Can you provide more info on the other changes? I see no references to socat in the Quickemu docs, and is using `sed` more effective then `wrapprogram` in any way?

**Comment by linsui** [comment]
socat is not documented but [used in the script](https://github.com/quickemu-project/quickemu/blob/d1d7920f0a7a7cf1670f9879e0b49dd877cf7060/quickemu#L1403). I opened [an upstream issue](https://github.com/quickemu-project/quickemu/issues/556). The patch failed to apply so I use sed instead and hope it's more robust. Maybe we should upstream the patch.

**Comment by FedX-sudo** [comment]
I see. Yeah, upsteaming the patch may not be a bad plan. The Quickemu code base is a touch buggy (for good reaon, it's a compilcated thing). Thank you for doing this!

**Review by FedX-sudo — APPROVED** [review]

**Comment by onny** [comment]
Result of `nixpkgs-review pr 191747` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>quickemu</li>
  </ul>
</details>

**Comment by linsui** [comment]
Update to 4.3, also fix the icon path.

**Comment by onny** [comment]
Result of `nixpkgs-review pr 191747` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>quickemu</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Pull request merged**
