### PR TITLE
python312Packages.pylance: skip failing tests on darwin

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Currently failing (on `darwin`) with:
```
=========================== short test summary info ============================
FAILED test_vector_index.py::test_index_with_no_centroid_movement - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED test_vector_index.py::test_index_cast_centroids - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED torch_tests/test_bench_utils.py::test_ground_truth - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED torch_tests/test_data.py::test_iter_over_dataset_fixed_shape_tensor - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED torch_tests/test_data.py::test_iter_over_dataset_fixed_size_lists - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED torch_tests/test_data.py::test_iter_filter - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED torch_tests/test_data.py::test_convert_int_tensors[uint8] - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
FAILED torch_tests/test_data.py::test_convert_int_tensors[int64] - AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
======= 8 failed, 263 passed, 27 skipped, 5 warnings in 95.11s (0:01:35) =======
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341866` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341866` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341866` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341866` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Actually, it was already failing on `x86_64-darwin` before the `aarch64-darwin` breakage that this PR originally targeted.

```
============================= test session starts ==============================
platform darwin -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /private/tmp/nix-build-python3.12-pylance-0.17.0.drv-0/source/python
configfile: pyproject.toml
collected 295 items / 8 deselected / 3 skipped / 287 selected                  

test_arrow.py ...........s..                                             [  4%]
test_datagen.py .s                                                       [  5%]
test_dataset.py ........................................................ [ 25%]
...................................                                      [ 37%]
test_debug.py ....                                                       [ 38%]
test_f16.py .                                                            [ 39%]
test_file.py ..................                                          [ 45%]
test_filter.py ..........                                                [ 48%]
test_fragment.py .............                                           [ 53%]
test_hnsw.py .                                                           [ 53%]
test_indices.py ...sss.Fatal Python error: Fatal Python error: Illegal instructionIllegal instruction



Thread 0xThread 0x0000000200bf02400000000200bf0240 (most recent call first):
 (most recent call first):
  File "/nix/store/wiiccrs0vd1qbh4j6ki9p40xmamsjix3-python3.12-pylance-0.17.0/lib/python3.12/site-packages/lance/indices.py", line 237 in train_ivf
  File /nix/store/9fiaang9cy551rxgsdh0ii9p47ws0bn7-pytest-check-hook/nix-support/setup-hook: line 53: 62902 Illegal instruction: 4  /nix/store/ks8acr22s4iggnmvxydm5czl30racy32-python3-3.12.5/bin/python3.12 -m pytest -k "not test_convert_int_tensors and not test_ground_truth and not test_index_cast_centroids and not test_index_with_no_centroid_movement and not test_iter_filter and not test_iter_over_dataset_fixed_shape_tensor and not test_iter_over_dataset_fixed_size_lists"
```

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341866` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>

**Review by pbsds — APPROVED** [review]
lgtm, waiting for ci

**Pull request merged**
