### PR TITLE
peertube: 6.0.4 -> 6.3.3

### LINKED ISSUE #357286: Update request: peertube 6.0.4 → 6.3.3
## Package Information

- Package name: peertube
- Latest released version: 6.3.3
- Current version on the unstable channel: 6.0.4
- Current version on the stable/release channel: 6.0.4

## Checklist

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@immae  
@Izorkin
@mohe2015
@stevenroose

https://github.com/Chocobozzz/PeerTube/releases/tag/v6.3.3

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by liberodark**
Fix : https://github.com/NixOS/nixpkgs/issues/357286

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by liberodark** [comment]
@ofborg build peertube

**Comment by Izorkin** [comment]
No update nginx configuration?

**Comment by Izorkin** [comment]
Patch:
```diff
diff --git a/nixos/modules/services/web-apps/peertube.nix b/nixos/modules/services/web-apps/peertube.nix
index e3f15f4f438c..86e8403a8008 100644
--- a/nixos/modules/services/web-apps/peertube.nix
+++ b/nixos/modules/services/web-apps/peertube.nix
@@ -511,10 +511,20 @@ in {
           '' + nginxCommonHeaders;
         };

+        locations."~ ^/api/v1/users/[^/]+/imports/import-resumable$" = {
+          tryFiles = "/dev/null @api";
+          priority = 1130;
+
+          extraConfig = ''
+            client_max_body_size 0;
+            proxy_request_buffering off;
+          '' + nginxCommonHeaders;
+        };
+
         locations."~ ^/api/v1/videos/(upload|([^/]+/studio/edit))$" = {
           tryFiles = "/dev/null @api";
           root = cfg.settings.storage.tmp;
-          priority = 1130;
+          priority = 1140;

           extraConfig = ''
             limit_except POST HEAD { deny all; }
@@ -527,7 +537,7 @@ in {
         locations."~ ^/api/v1/runners/jobs/[^/]+/(update|success)$" = {
           tryFiles = "/dev/null @api";
           root = cfg.settings.storage.tmp;
-          priority = 1135;
+          priority = 1150;

           extraConfig = ''
             client_max_body_size 12G;
@@ -537,7 +547,7 @@ in {

         locations."~ ^/api/v1/(videos|video-playlists|video-channels|users/me)" = {
           tryFiles = "/dev/null @api";
-          priority = 1140;
+          priority = 1160;

           extraConfig = ''
             client_max_body_size 6M;
@@ -547,7 +557,7 @@ in {

         locations."@api" = {
           proxyPass = "http://peertube";
-          priority = 1150;
+          priority = 1170;

           extraConfig = ''
             proxy_set_header Host $host;
@@ -685,8 +695,6 @@ in {
             if ($request_method = 'GET') {
               ${nginxCommonHeaders}
               ${nginxCommonHeadersExtra}
-
-              access_log off;
             }

             aio threads;
@@ -722,8 +730,6 @@ in {
             if ($request_method = 'GET') {
               ${nginxCommonHeaders}
               ${nginxCommonHeadersExtra}
-
-              access_log off;
             }

             aio threads;
@@ -759,8 +765,6 @@ in {
             if ($request_method = 'GET') {
               ${nginxCommonHeaders}
               ${nginxCommonHeadersExtra}
-
-              access_log off;
             }

             aio threads;
@@ -796,8 +800,6 @@ in {
             if ($request_method = 'GET') {
               ${nginxCommonHeaders}
               ${nginxCommonHeadersExtra}
-
-              access_log off;
             }

             aio threads;

```

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
Can we not change the formatting?

**Comment by Izorkin** [comment]
I on the contrary find it uncomfortable to read with this formatting :(

**Comment by liberodark** [comment]
Okay, I can cancel it.

**Comment by Izorkin** [comment]
Thanks!

**Review by drupol — CHANGES_REQUESTED** [review]
Nope. Please update the hash.

**Comment by liberodark** [comment]
New PR : https://github.com/NixOS/nixpkgs/pull/358194

**Pull request closed without merging**
