### PR TITLE
Vim plugins bump

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jonringer

### CODE REVIEW

**Comment by lovesegfault** [comment]
```
$ nix build --no-link --keep-going --max-jobs 12 --option build-use-sandbox true -f /home/bemeurer/.cache/nix-review/pr-74612/build.nix
[103 built, 21 copied (782.5 MiB), 174.5 MiB DL]
https://github.com/NixOS/nixpkgs/pull/74612
54 package were built:
vimPlugins.nerdcommenter vimPlugins.YouCompleteMe vimPlugins.airline vimPlugins.alchemist-vim vimPlugins.ale vimPlugins.awesome-vim-colorschemes vimPlugins.calendar vimPlugins.coc-go vimPlugins.coc-lists vimPlugins.coc-nvim vimPlugins.coc-prettier vimPlugins.coc-python vimPlugins.coc-rls vimPlugins.coc-tsserver vimPlugins.coc-yank vimPlugins.dart-vim-plugin vimPlugins.defx-nvim vimPlugins.denite vimPlugins.deol-nvim vimPlugins.deoplete-fish vimPlugins.deoplete-lsp vimPlugins.deoplete-nvim vimPlugins.editorconfig-vim vimPlugins.ensime-vim vimPlugins.falcon vimPlugins.fugitive vimPlugins.fzf-vim vimPlugins.gentoo-syntax vimPlugins.ghcid vimPlugins.gitgutter vimPlugins.gv-vim vimPlugins.lh-brackets vimPlugins.lh-vim-lib vimPlugins.mattn-calendar-vim vimPlugins.ncm2 vimPlugins.ncm2-jedi vimPlugins.neomake vimPlugins.neosnippet-snippets vimPlugins.nvim-yarp vimPlugins.polyglot vimPlugins.rust-vim vimPlugins.semshi vimPlugins.sensible vimPlugins.stylishHaskell vimPlugins.surround vimPlugins.vim-airline-themes vimPlugins.vim-qml vimPlugins.vim-snippets vimPlugins.vim-test vimPlugins.vim-visual-multi vimPlugins.vim-wakatime vimPlugins.vimproc vimPlugins.vimshell vimPlugins.vimtex
```

**Comment by jonringer** [comment]
do you mind squashing the two  commits, they both fall under the category of update

**Comment by lovesegfault** [comment]
@jonringer Done!

**Review by jonringer — APPROVED** [review]
LGTM

```
[104 built, 21 copied (760.5 MiB), 174.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/74612
54 package were built:
vimPlugins.alchemist-vim vimPlugins.ale vimPlugins.awesome-vim-colorschemes vimPlugins.calendar-vim vimPlugins.coc-go vimPlugins.coc-lists vimPlugins.coc-nvim vimPlugins.coc-prettier vimPlugins.coc-python vimPlugins.coc-rls vimPlugins.coc-tsserver vimPlugins.coc-yank vimPcopying azure/cli/command_modules/appconfig/_params.py -> build/lib/lugins.dart-vim-plugin vimPlugins.defx-nvim vimPlugins.denite-nvim vimPlugins.deol-nvim vimPlugins.deoplete-fish vimPlugins.deoplete-lsp vimPlugins.deoplete-nvim vimPlugins.editorconfig-vim vimPlugins.ensime-vim vimPlugins.falcon vimPlugins.fzf-vim vimPlugins.gentoo-syntax vimPlugins.ghcid vimPlugins.gv-vim vimPlugins.lh-brackets vimPlugins.lh-vim-lib vimPlugins.mattn-calendar-vim vimPlugins.ncm2 vimPlugins.ncm2-jedi vimPlugins.neomake vimPlugins.neosnippet-snippets vimPlugins.nerdcommenter vimPlugins.nvim-yarp vimPlugins.rust-vim vimPlugins.semshi vimPlugins.vim-airline vimPlugins.vim-airline-themes vimPlugins.vim-fugitive vimPlugins.vim-gitgutter vimPlugins.vim-polyglot vimPlugins.vim-qml vimPlugins.vim-sensible vimPlugins.vim-snippets vimPlugins.vim-stylish-haskell vimPlugins.vim-surround vimPlugins.vim-test vimPlugins.vim-visual-multi vimPlugins.vim-wakatime vimPlugins.vimproc-vim vimPlugins.vimshell-vim vimPlugins.vimtex vimPlugins.youcompleteme
```

**Pull request merged**
