### PR TITLE
dwarf-fortress: fix build error

### LINKED ISSUE #46914: Can't build dwarf fortress 0.44.12
## Issue description
`rm: cannot remove '/nix/store/wwyq6qv64prpf45prvkzk0m6y2qx336d-dwarf-fortress-env-0.44.12/data/init/init.txt': Permission denied`

Called from here:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/dwarf-fortress/wrapper/default.nix#L45

### Steps to reproduce
`nix-env -iA nixos.dwarf-fortress`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.7, NixOS, 19.03.git.ad755cc (Koi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-19.03pre152634.218ce4de508"`
 - channels(chris): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by Lassulus**
###### Motivation for this change

fix https://github.com/NixOS/nixpkgs/issues/46914

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Lassulus** [comment]
maybe also cherry-pick to 18.09 (no distribution is stable without dwarf-fortress ;))

**Comment by Lassulus** [comment]
pinging maintainers for review
@a1russell @robbinch @roconnor @the-kenny @abbradar @numinit

**Comment by numinit** [comment]
I would prefer that the latest version of the dwarf-fortress package (in master/unstable) gets merged because this has been fixed but apparently didn't make 18.09. TWBT and therapist will be broken in 18.09 too but work in unstable.

**Comment by numinit** [comment]
BTW, can you try unstable and see if it works for you?

**Comment by Lassulus** [comment]
unstable fails for me with: `rm: cannot remove '/nix/store/w6ggm86nimcn4g2cmva3bsha8li24k5v-dwarf-fortress-env-0.44.12/data/init/init.txt': Permission denied`

**Comment by numinit** [comment]
Oh, gotcha, misread the branch you were merging into. I know that there were some issues a while back, but there are apparently more now. 

I will test this in a couple hours, everything makes sense now. 👍

**Comment by joachifm** [comment]
@GrahamcOfBorg build dwarf-fortress

**Comment by numinit** [comment]
Unfortunately I'm currently out of town on a slow connection, and didn't have an 18.09 system until this morning :(

Changes look good though. Will give them a try tonight.

**Review by matthewbauer — APPROVED** [review]
LGTM! Remind me if this isn't merged in a few days.

**Comment by numinit** [comment]
Thanks @matthewbauer!

**Pull request merged**
