### PR TITLE
Switch stdenvs to pure-darwin

### PR DESCRIPTION
**Pull request by pikajude**
This is to go along with my ML message requesting a default stdenv switch to pure-darwin. The reactions have been positive so far!

@edolstra

### CODE REVIEW

**Comment by Ericson2314** [comment]
Should we change the names to `stdenvDarwin` and `stdenvDarwinImpure` or something to reflect the new default?

**Comment by henrytill** [comment]
:+1:

**Comment by codedmart** [comment]
:+1:

**Comment by acowley** [comment]
I already :+1: 'd on the mailing list, but, just in case it can help un-wedge this, here's another :+1: !

It'd be great to get this ball rolling again.

**Comment by copumpkin** [comment]
:+1: :+1: :beers: :beers:

**Comment by benley** [comment]
:trophy: :+1:

**Comment by vcunat** [comment]
You rejoice too early, as the stdenv won't build on Hydra. http://hydra.nixos.org/build/26728682

**Comment by datakurre** [comment]
Does this require patches on top of Nix 1.10? Is https://github.com/NixOS/nix/pull/562 enough?

**Comment by copumpkin** [comment]
@vcunat http://www.nooooooooooooooo.com/

**Comment by copumpkin** [comment]
I think Hydra needs a different nix.conf. Not sure how that sort of thing is managed!

**Comment by rbvermaa** [comment]
@copumpkin what kind of changes does nix.conf need?

**Comment by edolstra** [comment]
Note that the failing derivation (`/nix/store/y3n191kgrrvc4r3rafz5hb919id8njs2-mkdir.drv`) has `system` set to `x86_64-linux`, which I assume should be `x86_64-darwin`. Our Mac does not have sandbox builds enabled BTW.

**Comment by edolstra** [comment]
This is probably due to:
```
pkgs/stdenv/pure-darwin/default.nix:{ system      ? builtins.currentSystem
pkgs/stdenv/pure-darwin/make-bootstrap-tools.nix:{system ? builtins.currentSystem}:
```

**Comment by edolstra** [comment]
Now that pure-darwin is the default, should we get rid of the old darwin stdenv?

**Comment by pikajude** [comment]
@edolstra I'd be fine with leaving it until Apple stops distributing Xcode 6, but the users need to be made aware it won't work on OSes newer than 10.9 or with Xcode 7.

**Pull request merged**
