### PR TITLE
python: Move catch_conflicts.py into subdirectory

### PR DESCRIPTION
**Pull request by johbo**
###### Motivation for this change

Python does add the script's directory into "sys.path". For the case of
"catch_conflicts.py" this means "/nix/store" is added to "sys.path". This can
result in very long delays if the store contains a lot of entries.

I came across the issue on my machine which has about 100,000 entries in /nix/store. The build time for a single python derivation was increased by about 20 seconds due to this problem.

https://docs.python.org/3/library/sys.html#sys.path contains some details that the path of the script is added as first element into sys.path always.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks for checking this out. This is an interesting issue.

Another solution would be to copy the file into the build as is done with `run_setup.py` in `build-python-package-setuptools.nix`. In any case, whatever solution you pick, please explain in the code why its done like that since otherwise someone would likely change it again.

**Comment by johbo** [comment]
Yes, indeed, we could copy it in as well, still it would need a subdirectory, otherwise we get false positives. Out of this thought I came to the conclusion to run this in an empty directory in the store. That's IMO less fragile.

Regarding a comment: Since it's a tricky issue, maybe it's best to put a small README.md into the subdirectory? Then I could explain the reasoning better and if someone wonders what this weird construction is about there is a good chance that it helps to understand the original reasons.

**Comment by FRidh** [comment]
> Yes, indeed, we could copy it in as well, still it would need a subdirectory, otherwise we get false positives. Out of this thought I came to the conclusion to run this in an empty directory in the store. That's IMO less fragile.

If it gets copied in, it would add the build directory to `sys.path`. What kind of false positives are you thinking of? In any case, you're right, having it in a separate directory is the safest.

> Regarding a comment: Since it's a tricky issue, maybe it's best to put a small README.md into the subdirectory? Then I could explain the reasoning better and if someone wonders what this weird construction is about there is a good chance that it helps to understand the original reasons.

You could refer to this PR:

> The file `catch_conflicts.py` is in a subdirectory because, if it isn't, the `/nix/store/` directory is added to `sys.path` causing a delay when building. See https://github.com/NixOS/nixpkgs/pull/23600

**Comment by johbo** [comment]
Since this is flagged as a mass rebuild, does it need special treatment in any way?

**Comment by FRidh** [comment]
@johbo mass-rebuilds go into staging.

Currently Hydra is quite occupied so I'll merge this together with some other Python-related mass-rebuilds (https://github.com/NixOS/nixpkgs/pull/22210).

**Comment by FRidh** [comment]
@vcunat this can go in.

**Comment by vcunat** [comment]
I didn't notice it was against master and had to "move" the commit to staging afterwards, creating a bit of mess.

**Pull request merged**
