### PR TITLE
python3Packages.sqlalchemy_1: init at 1.4.48

### PR DESCRIPTION
**Pull request by rhendric**
###### Description of changes

Overriding to use SQLAlchemy 1 fixes several Python packages that are failing to build with SQLAlchemy 2.

ZHF: #230712

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rhendric** [comment]
CC @ivan-tkatchev and @nyanloutre as maintainers for sqlalchemy-jsonfield and telethon-session-sqlalchemy respectively.

**Review by mweinelt — CHANGES_REQUESTED** [review]
We cannot do this. Python packages propagate their dependencies recursively and there can only be one sqlalchemy in the package set, or else we'll run into conflicts, because there can only be one sqlalchemy in a PYTHONPATH.

Overrides like this are only possible for python applications, but not for libraries that propagate sqlalchemy.

```
pkgs/servers/home-assistant/default.nix
248:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (oldAttrs: rec {

pkgs/applications/misc/privacyidea/default.nix
12:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (oldAttrs: rec {

pkgs/servers/calibre-web/default.nix
11:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (old: rec {

pkgs/applications/misc/pytrainer/default.nix
25:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (old: rec {

pkgs/applications/networking/flexget/default.nix
9:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (old: rec {

pkgs/development/tools/continuous-integration/buildbot/default.nix
8:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (oldAttrs: rec {

pkgs/tools/backup/grab-site/default.nix
6:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (oldAttrs: rec {

pkgs/tools/misc/ntfy/default.nix
20:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (old: rec {

pkgs/tools/text/csvkit/default.nix
8:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (oldAttrs: rec {

pkgs/tools/filesystems/ceph/default.nix
167:      sqlalchemy = super.sqlalchemy.overridePythonAttrs (oldAttrs: rec {

**Comment by rhendric** [comment]
I'm aware there can be only one version of each library in a PYTHONPATH. Any application or library using any of the packages modified here would have to be using SQLAlchemy 1 in any event, as these packages don't work with SQLAlchemy 2. Adding a `sqlalchemy_1` derivation seemed like a good way to support that case; what would you recommend instead? Mark all of the affected packages as broken?

**Comment by mweinelt** [comment]
I'm saying that applications using these libraries need to override sqlalchemy in their python package set. And yes, they are basically `broken = lib.versionAtLeast sqlalchemy "2.0"`.

**Comment by rhendric** [comment]
Got it, will submit that instead.

**Pull request closed without merging**
