### PR TITLE
[23.05] kicad: 7.0.2 -> 7.0.6

### PR DESCRIPTION
**Pull request by ius**
## Description of changes

Backport of (multiple) bugfix updates already in master. There's a small leftover diff to master, but those changes seem related to tests - presumably when the derivation is used to build the development version of Kicad.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

## Additional note

@evils - you seem to have committed recent minor version bumps on master, could you tag future similar PRs for backporting?

### CODE REVIEW

**Comment by evils** [comment]
yea, i've been neglectful about backporting
while i prefer people to use the unstable branch to get the latest KiCad
i should at least keep the stable branch up-to-date without crossing major release boundaries...

**Review by evils — COMMENTED** [review]
note that the versions.nix file is generated by update.sh
the whitespace changes lead me to believe you manually edited this
(you could have just cherry-picked updates and squashed them, or 
ran `update.sh stable`)

the 7.0.7 release is expected on the 15th
if this isn't merged by then i'll do a round of backporting

thanks for indicating a desire for backports :)

**Comment by ius** [comment]
> (you could have just cherry-picked updates and squashed them, or ran `update.sh stable`)

Right, indeed I manually copypasted the diff to master because I didn't feel like cherry picking multiple commits.

Was unaware the `update.sh` script also supports updating stable only. Updated the PR to use `update.sh` output instead.

**Comment by evils** [comment]
looks like that reused the strings as the commits didn't change
you can do `update.sh clean stable` to redo the stable part from scratch

**Comment by ius** [comment]
What a mess. Thanks for being so observant, thought I started over clean - apparently did not.

I _think_ it's okay for real now.

**Review by evils — APPROVED** [review]
looks good, thanks!

**Comment by NickCao** [comment]
@ofborg build kicad

**Pull request merged**
