### PR TITLE
open-webui: 0.2.5 -> 0.3.2

### PR DESCRIPTION
**Pull request by drupol**
diff: https://github.com/open-webui/open-webui/compare/v0.2.5..v0.3.2
changelog: https://github.com/open-webui/open-webui/releases/tag/v0.3.2

I also added a new dependency `extract-msg` because of https://github.com/open-webui/open-webui/commit/f69bc57fed98b4c573836e2a31c354173fc08108

I also removed stuff from `pythonRemoveDeps` since they are now available:
- https://github.com/NixOS/nixpkgs/pull/317142
- https://github.com/NixOS/nixpkgs/pull/317151

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by teto** [comment]
Result of `nixpkgs-review pr 318755` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
  </ul>
</details>

**Comment by drupol** [comment]
@teto what are the build issue care to send a log?

**Comment by teto** [comment]
might be a fluke since it was in a test 
```
Successfully built langchain_core-0.2.1-py3-none-any.whl
Finished creating a wheel...
/build/source/libs/core/dist /build/source/libs/core
Unpacking to: unpacked/langchain_core-0.2.1...OK
Repacking wheel as ./langchain_core-0.2.1-py3-none-any.whl...creating './langchain_core-0.2.1-py3-none-any.whl' and adding 'un>
adding 'langchain_core/__init__.py'
adding 'langchain_core/agents.py'
adding 'langchain_core/caches.py'
adding 'langchain_core/chat_history.py'
adding 'langchain_core/chat_loaders.py'
adding 'langchain_core/chat_sessions.py'
adding 'langchain_core/env.py'
adding 'langchain_core/exceptions.py'
adding 'langchain_core/globals.py'
adding 'langchain_core/memory.py'
adding 'langchain_core/prompt_values.py'
adding 'langchain_core/py.typed'
adding 'langchain_core/retrievers.py'
adding 'langchain_core/stores.py'
adding 'langchain_core/structured_query.py'
adding 'langchain_core/sys_info.py'
adding 'langchain_core/tools.py'
adding 'langchain_core/vectorstores.py'
adding 'langchain_core/_api/__init__.py'
adding 'langchain_core/_api/beta_decorator.py'
adding 'langchain_core/_api/deprecation.py'
adding 'langchain_core/_api/internal.py'
adding 'langchain_core/_api/path.py'
adding 'langchain_core/beta/__init__.py'
adding 'langchain_core/beta/runnables/__init__.py'
adding 'langchain_core/beta/runnables/context.py'
adding 'langchain_core/callbacks/__init__.py'
adding 'langchain_core/callbacks/base.py'
adding 'langchain_core/callbacks/file.py'
...skipping...
            "passthrough": RunnablePassthrough(),
        }
    
        stream = chain.stream({"question": "What is your name?"})
    
        final_value = None
        streamed_chunks = []
        for chunk in stream:
            streamed_chunks.append(chunk)
            if final_value is None:
                final_value = chunk
            else:
                final_value += chunk
    
>       assert streamed_chunks[0] in [
            {"passthrough": prompt.invoke({"question": "What is your name?"})},
            {"llm": "i"},
            {"chat": AIMessageChunk(content="i")},
        ]
E       AssertionError: assert {'chat': AIMessageChunk(content='i', id='run-ced90791-e3fa-4398-8ab7-35b3d95acb24')} in [{'pass>

tests/unit_tests/runnables/test_runnable.py:3263: AssertionError
=============================== warnings summary ===============================
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
tests/unit_tests/prompts/test_few_shot.py:25
  /build/source/libs/core/tests/unit_tests/prompts/test_few_shot.py:25: PytestRemovedIn9Warning: Marks applied to fixtures hav>
  See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
  ```

**Comment by drupol** [comment]
Wild guess, I think it needs: https://github.com/NixOS/nixpkgs/pull/318786

**Review by shivaraj-bh — APPROVED** [review]
Thanks!

**Comment by drupol** [comment]
@ofborg build open-webui

**Pull request merged**
