### PR TITLE
linux_latest: 5.15.12 -> 5.16

### PR DESCRIPTION
**Pull request by alyssais**
The release has been tagged, but the tarball isn't on cdn.kernel.org
yet, so I'm fetching from git.kernel.org.  We should probably switch
to the official tarball once it appears.

I'm doing some further work to update some out-of-tree modules, etc. (see my last few PRs), but will not be blocking this PR for anything out-of-tree.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
It's in the cdn now

**Review by jonringer — APPROVED** [review]
diff LGTM, after we switch back to mirror

```
6 packages failed to build:
linuxPackages_latest.nvidia_x11_beta linuxPackages_latest.nvidia_x11_legacy340 linuxPackages_latest.nvidia_x11_vulkan_beta linuxPackages_latest-libre.nvidia_x11_beta linuxPackages_latest-libre.nvidia_x11_legacy340 linuxPackages_latest-libre.nvidia_x11_vulkan_beta

149 packages built:
bpftools linux-manual linux_latest linux_latest-libre linuxPackages_latest.acpi_call linuxPackages_latest.akvcam linuxKernel.packages.linux_5_16.amdgpu-pro linuxPackages_latest.apfs linuxPackages_latest.asus-ec-sensors linuxPackages_latest.asus-wmi-sensors linuxPackages_latest.batman_adv linuxPackages_latest.bbswitch linuxKernel.packages.linux_5_16.bcc linuxKernel.packages.linux_5_16.bpftrace linuxPackages_latest.broadcom_sta linuxPackages_latest.can-isotp linuxPackages_latest.chipsec linuxPackages_latest.cpupower linuxPackages_latest.cryptodev linuxPackages_latest.ddcci-driver linuxPackages_latest.digimend linuxPackages_latest.dpdk-kmods linuxPackages_latest.facetimehd linuxPackages_latest.fwts-efi-runtime linuxPackages_latest.gcadapter-oc-kmod linuxPackages_latest.hid-nintendo linuxPackages_latest.hyperv-daemons linuxPackages_latest.intel-speed-select linuxPackages_latest.isgx linuxPackages_latest.it87 linuxPackages_latest.jool linuxPackages_latest.liquidtux linuxPackages_latest.lttng-modules linuxPackages_latest.mba6x_bl linuxPackages_latest.mbp2018-bridge-drv linuxPackages_latest.mwprocapture linuxPackages_latest.netatop linuxPackages_latest.nvidia_x11 linuxPackages_latest.nvidia_x11_legacy390 linuxPackages_latest.nvidia_x11_legacy470 linuxPackages_latest.nvidiabl linuxKernel.packages.linux_5_16.oci-seccomp-bpf-hook linuxKernel.packages.linux_5_16.odp-dpdk linuxPackages_latest.openafs linuxPackages_latest.openrazer linuxPackages_latest.perf linuxKernel.packages.linux_5_16.pktgen linuxPackages_latest.ply linuxPackages_latest.r8168 linuxPackages_latest.rr-zen_workaround linuxPackages_latest.rtl8192eu linuxPackages_latest.rtl8814au linuxPackages_latest.rtl8821au linuxPackages_latest.rtl8821ce linuxPackages_latest.rtl8821cu linuxPackages_latest.rtl88x2bu linuxPackages_latest.rtl88xxau-aircrack linuxPackages_latest.rtw89 linuxKernel.packages.linux_5_16.stdenv linuxPackages_latest.sysdig linuxPackages_latest.system76 linuxPackages_latest.system76-acpi linuxPackages_latest.system76-io linuxKernel.packages.linux_5_16.system76-power linuxPackages_latest.systemtap linuxPackages_latest.tmon linuxPackages_latest.tp_smapi linuxPackages_latest.turbostat linuxPackages_latest.tuxedo-keyboard linuxPackages_latest.usbip linuxPackages_latest.v4l2loopback linuxPackages_latest.v86d linuxPackages_latest.veikk-linux-driver linuxPackages_latest.vendor-reset linuxPackages_latest.vhba linuxPackages_latest.virtualbox linuxPackages_latest.virtualboxGuestAdditions linuxKernel.packages.linux_5_16.vm-tools linuxPackages_latest.x86_energy_perf_policy linuxPackages_latest.xpadneo linuxPackages_latest.zenpower linuxPackages_latest-libre.acpi_call linuxPackages_latest-libre.akvcam linuxPackages_latest-libre.apfs linuxPackages_latest-libre.asus-ec-sensors linuxPackages_latest-libre.asus-wmi-sensors linuxPackages_latest-libre.batman_adv linuxPackages_latest-libre.bbswitch linuxPackages_latest-libre.broadcom_sta linuxPackages_latest-libre.can-isotp linuxPackages_latest-libre.chipsec linuxPackages_latest-libre.cpupower linuxPackages_latest-libre.cryptodev linuxPackages_latest-libre.ddcci-driver linuxPackages_latest-libre.digimend linuxPackages_latest-libre.dpdk-kmods linuxPackages_latest-libre.facetimehd linuxPackages_latest-libre.fwts-efi-runtime linuxPackages_latest-libre.gcadapter-oc-kmod linuxPackages_latest-libre.hid-nintendo linuxPackages_latest-libre.hyperv-daemons linuxPackages_latest-libre.intel-speed-select linuxPackages_latest-libre.isgx linuxPackages_latest-libre.it87 linuxPackages_latest-libre.jool linuxPackages_latest-libre.liquidtux linuxPackages_latest-libre.lttng-modules linuxPackages_latest-libre.mba6x_bl linuxPackages_latest-libre.mbp2018-bridge-drv linuxPackages_latest-libre.mwprocapture linuxPackages_latest-libre.netatop linuxPackages_latest-libre.nvidia_x11 linuxPackages_latest-libre.nvidia_x11_legacy390 linuxPackages_latest-libre.nvidia_x11_legacy470 linuxPackages_latest-libre.nvidiabl linuxPackages_latest-libre.openafs linuxPackages_latest-libre.openrazer linuxPackages_latest-libre.perf linuxPackages_latest-libre.ply linuxPackages_latest-libre.r8168 linuxPackages_latest-libre.rr-zen_workaround linuxPackages_latest-libre.rtl8192eu linuxPackages_latest-libre.rtl8814au linuxPackages_latest-libre.rtl8821au linuxPackages_latest-libre.rtl8821ce linuxPackages_latest-libre.rtl8821cu linuxPackages_latest-libre.rtl88x2bu linuxPackages_latest-libre.rtl88xxau-aircrack linuxPackages_latest-libre.rtw89 linuxPackages_latest-libre.sysdig linuxPackages_latest-libre.system76 linuxPackages_latest-libre.system76-acpi linuxPackages_latest-libre.system76-io linuxPackages_latest-libre.systemtap linuxPackages_latest-libre.tmon linuxPackages_latest-libre.tp_smapi linuxPackages_latest-libre.turbostat linuxPackages_latest-libre.tuxedo-keyboard linuxPackages_latest-libre.usbip linuxPackages_latest-libre.v4l2loopback linuxPackages_latest-libre.v86d linuxPackages_latest-libre.veikk-linux-driver linuxPackages_latest-libre.vendor-reset linuxPackages_latest-libre.vhba linuxPackages_latest-libre.virtualbox linuxPackages_latest-libre.virtualboxGuestAdditions linuxPackages_latest-libre.x86_energy_perf_policy linuxPackages_latest-libre.xpadneo linuxPackages_latest-libre.zenpower
```

The nvidia packages are failing due to not being able to find C headers, which is very odd

ecample failure:
```
error: builder for '/nix/store/r0cihj234f1s63q8hbdzv2xkfw4xjrwk-nvidia-x11-495.29.05-5.16.drv' failed with exit code 2;
       last 10 log lines:
       > /build/kernel/common/inc/os-interface.h:40:10: fatal error: stdarg.h: No such file or directory
       >    40 | #include <stdarg.h>
       >       |          ^~~~~~~~~~
       > compilation terminated.
       ```

**Comment by SuperSamus** [comment]
Question from an ignorant, does it make sense to have [hid-nintendo](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/hid-nintendo/default.nix) installable on 5.16+, since it's now included in the kernel?

**Comment by alyssais** [comment]
> Question from an ignorant, does it make sense to have hid-nintendo installable on 5.16+, since it's now included in the kernel?

I don't know — for some modules, it can make sense because you can get a more up to date version of that module.  For others, it isn't even possible.

**Comment by jonringer** [comment]
I don't think module support should be a PR blocker.

There's going to be some pain with bleeding edge kernel updates.

**Review by fabianhjr — APPROVED** [review]
Built and booted:

```
~ cat /proc/version         Mon 10 Jan 2022 10:28:56 AM CST
Linux version 5.16.0 (nixbld@localhost) (gcc (GCC) 10.3.0, GNU ld (GNU Binutils) 2.35.2) #1-NixOS SMP PREEMPT Sun Jan 9 22:55:34 UTC 2022
```

**Comment by alyssais** [comment]
@mweinelt I'd have preferred that be a separate PR, like I did for all the other modules, so that it can be discussed separately e.g. for backporting, but it's not a big deal.

**Comment by mweinelt** [comment]
> @mweinelt I'd have preferred that be a separate PR, like I did for all the other modules, so that it can be discussed separately e.g. for backporting, but it's not a big deal.

Ah I misread what you wrote in the OP, my bad. I even misread that even the older version was successfully built. Doesn't seem to be my day.

**Comment by jonringer** [comment]
It might be a little while for 5.16 support
https://github.com/openzfs/zfs/issues/12926

**Pull request merged**
