### PR TITLE
haskellPackages.hakyll: relax upper bound on warp

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Motivation for this change

See #85670.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build

**Comment by cdepillabout** [comment]
@worldofpeace I may be incorrect about this, but the 20.03 branch that fixes should be merged into is `release-20.03`, not `nixos-20.03`, right?

**Comment by worldofpeace** [comment]
> @worldofpeace I may be incorrect about this, but the 20.03 branch that fixes should be merged into is `release-20.03`, not `nixos-20.03`, right?

nixos-20.03 is the nixos channel. so yes always release-20.03 as per the backporting docs.

**Comment by cdepillabout** [comment]
@worldofpeace Thanks for clearing this up!

---------------------------

@vaibhavsagar Thanks for fixing hakyll.  Looks good so I'm merging in!

**Pull request merged**
