### PR TITLE
ocamlbuild: isStatic -> isMusl for the "pie" hardening check

### PR DESCRIPTION
**Pull request by anmonteiro**
###### Motivation for this change

This aligns this check with the OCaml compiler's: https://github.com/NixOS/nixpkgs/blob/687ed904ecff421958a685d775a72e95d405cec1/pkgs/development/compilers/ocaml/generic.nix#L69

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sternenseemann — APPROVED** [review]

**Comment by r-burns** [comment]
Hey, I think the hardeningDisable here can be removed entirely after https://github.com/NixOS/nixpkgs/pull/135619 (currently in staging), care to give it a try?

I'm okay with merging this as an interim fix, as long as we don't forget to reenable PIE hardening after https://github.com/NixOS/nixpkgs/pull/135619 lands.

**Comment by anmonteiro** [comment]
I tried the staging branch without this fix and still couldn't compile ocamlbuild

**Comment by r-burns** [comment]
Hmm, could you specify what you tried?

Texinfo fails on staging due to https://github.com/NixOS/nixpkgs/issues/139470, but after checking out 445a2455ad7af902e226f50bc550056094365015 and reverting 1165533fc3f52809ff04fc76b4c75a0f8e4947c1 I was able to build pkgsMusl.ocamlPackages.ocamlbuild.

**Comment by anmonteiro** [comment]
I think I might not have selected the right revision earlier. This is indeed working in staging.

**Pull request closed without merging**
