### PR TITLE
[21.05] firefox: 93.0 -> 94.0; firefox-esr-91: 91.2.0esr -> 91.3.0esr; firefox-esr-78: mark insecure; firefox-esr: redirect to firefox-esr-91]

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
Backport #144219 

78 ESR is EOL, redirect everyone to 91 ESR.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
The build of `firefox` (94) fails for me with this:
```
 0:10.73 ERROR: Rust compiler 1.52.1 is too old.
 0:10.73 
 0:10.73 To compile Rust language sources please install at least
 0:10.73 version 1.53.0 of the 'rustc' toolchain (or, if using nightly,
 0:10.73 at least one version newer than 1.53.0) and make sure it is
 0:10.73 first in your path.
 0:10.73 
 0:10.73 You can verify this by typing 'rustc --version'.
 0:10.73 
 0:10.73 If you have the 'rustup' tool installed you can upgrade
 0:10.73 to the latest release by typing 'rustup update'. The
 0:10.73 installer is available from https://rustup.rs/
 0:10.73 
Error running mach:

    ['configure', '--prefix=/nix/store/nqkay9xqrc0biavnf1x37df4qplqsm8w-firefox-unwrapped-94.0', '--enable-application=browser', '--with-system-jpeg', '--with-system-zlib', '--with-system-libevent', '--with-system-libvpx', '--with-system-png', '--with-system-icu', '--enable-system-ffi', '--enable-system-pixman', '--disable-tests', '--disable-necko-wifi', '--disable-updater', '--enable-jemalloc', '--enable-default-toolkit=cairo-gtk3-wayland', '--with-libclang-path=/nix/store/21b8gqffr9cm3mg2sgsw5bkqrqfp4kk2-clang-11.1.0-lib/lib', '--with-system-nspr', '--with-system-nss', '--enable-lto', '--disable-elf-hack', '--enable-linker=lld', '--enable-alsa', '--enable-pulseaudio', '--enable-ffmpeg', '--enable-negotiateauth', '--enable-webrtc', '--disable-crashreporter', '--disable-debug', '--enable-optimize', '--enable-strip', '--enable-release', '--enable-official-branding', '--with-google-location-service-api-keyfile=/build/ga', '--with-google-safebrowsing-api-keyfile=/build/ga']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file configure| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

Exception: Process executed with non-0 exit code 1: ['/nix/store/32q6ryrb860sksdi1al5djg3pgcpq92l-python3-3.8.11/bin/python3', '/build/firefox-94.0/configure.py', '--prefix=/nix/store/nqkay9xqrc0biavnf1x37df4qplqsm8w-firefox-unwrapped-94.0', '--enable-application=browser', '--with-system-jpeg', '--with-system-zlib', '--with-system-libevent', '--with-system-libvpx', '--with-system-png', '--with-system-icu', '--enable-system-ffi', '--enable-system-pixman', '--disable-tests', '--disable-necko-wifi', '--disable-updater', '--enable-jemalloc', '--enable-default-toolkit=cairo-gtk3-wayland', '--with-libclang-path=/nix/store/21b8gqffr9cm3mg2sgsw5bkqrqfp4kk2-clang-11.1.0-lib/lib', '--with-system-nspr', '--with-system-nss', '--enable-lto', '--disable-elf-hack', '--enable-linker=lld', '--enable-alsa', '--enable-pulseaudio', '--enable-ffmpeg', '--enable-negotiateauth', '--enable-webrtc', '--disable-crashreporter', '--disable-debug', '--enable-optimize', '--enable-strip', '--enable-release', '--enable-official-branding', '--with-google-location-service-api-keyfile=/build/ga', '--with-google-safebrowsing-api-keyfile=/build/ga']

  File "/build/firefox-94.0/python/mozbuild/mozbuild/build_commands.py", line 254, in configure
    return driver.configure(
  File "/build/firefox-94.0/python/mozbuild/mozbuild/controller/building.py", line 1526, in configure
    status = self._run_command_in_objdir(
  File "/build/firefox-94.0/python/mozbuild/mozbuild/base.py", line 853, in _run_command_in_objdir
    return self.run_process(cwd=self.topobjdir, **args)
  File "/build/firefox-94.0/python/mach/mach/mixin/process.py", line 174, in run_process
    raise Exception(
```

**Comment by vcunat** [comment]
`firefox-esr` works for me as committed.

**Comment by mweinelt** [comment]
Copied rust_1_55 over into release-21.05.

**Comment by mweinelt** [comment]
Tested `firefox-wayland` on sway/pipewire. LGTM.

**Comment by ajs124** [comment]
91 esr also complains about the rust being too old:
```
 0:10.25 ERROR: Rust compiler 1.45.2 is too old.
 0:10.25 
 0:10.25 To compile Rust language sources please install at least
 0:10.25 version 1.51.0 of the 'rustc' toolchain (or, if using nightly,
 0:10.25 at least one version newer than 1.51.0) and make sure it is
 0:10.25 first in your path.
 0:10.25 
 0:10.25 You can verify this by typing 'rustc --version'.
 0:10.25 
 0:10.25 If you have the 'rustup' tool installed you can upgrade
 0:10.25 to the latest release by typing 'rustup update'. The
 0:10.25 installer is available from https://rustup.rs/
 0:10.25 
Error running mach:

    ['configure', '--prefix=/nix/store/lzf6lb9lzlljb6bln6q49jamj1akya7p-firefox-esr-unwrapped-91.3.0esr', '--enable-application=browser', '--with-system-jpeg', '--with-system-zlib', '--with-system-libevent', '--with-system-libvpx', '--with-system-png', '--with-system-icu', '--enable-system-ffi', '--enable-system-pixman', '--disable-tests', '--disable-necko-wifi'>

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file configure| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

Exception: Process executed with non-0 exit code 1: ['/nix/store/32q6ryrb860sksdi1al5djg3pgcpq92l-python3-3.8.11/bin/python3', '/build/firefox-91.3.0/configure.py', '--prefix=/nix/store/lzf6lb9lzlljb6bln6q49jamj1akya7p-firefox-esr-unwrapped-91.3.0esr', '--enable-application=browser', '--with-system-jpeg', '--with-system-zlib', '--with-system-libevent', '--with-s>

  File "/build/firefox-91.3.0/python/mozbuild/mozbuild/build_commands.py", line 191, in configure
    return driver.configure(
  File "/build/firefox-91.3.0/python/mozbuild/mozbuild/controller/building.py", line 1528, in configure
    status = self._run_command_in_objdir(
  File "/build/firefox-91.3.0/python/mozbuild/mozbuild/base.py", line 845, in _run_command_in_objdir
    return self.run_process(cwd=self.topobjdir, **args)
  File "/build/firefox-91.3.0/python/mach/mach/mixin/process.py", line 176, in run_process
    raise Exception(
```

**Comment by mweinelt** [comment]
Oh nice, they changed that in a minor version then.

**Comment by mweinelt** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/144296/commits/95b508e695d4230da243cf010f23e654ef3930f3.

**Comment by vcunat** [comment]
As I tested before, `-esr-91` would work with rust 1.54.  I'll re-check at least the build now (it's 1.44).

**Comment by mweinelt** [comment]
> As I tested before, `-esr-91` would work with rust 1.54.  I'll re-check at least the build now (it's 1.44).

I pinned 91 and 94 to 1.55.

**Review by ajs124 — APPROVED** [review]

**Pull request merged**
