### PR TITLE
isso: 0.12.4 -> 0.12.5

### PR DESCRIPTION
**Pull request by fgaz**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Why is `cffi` not in `propagatedBuildInputs`?

**Comment by fgaz** [comment]
@dotlambda you're right, it should be in _native_BuildInputs. Fixed.

**Comment by SuperSandro2000** [comment]
> @dotlambda right, buildInputs is the wrong place, it should be in _native_BuildInputs (setup_requires). Fixed.

Wouldn't that cause cross compile issues?

**Comment by fgaz** [comment]
Would it? The manual says setup_requires usually go in nativeBuildInputs: https://nixos.org/manual/nixpkgs/stable/index.html#reference

**Pull request merged**
