### PR TITLE
gcc: Move target libraries to `lib` output when building a cross compiler

### PR DESCRIPTION
**Pull request by eamsden**
###### Motivation for this change
Programs and libraries cross-compiled with nixpkgs gcc often had the entire gcc store path in their closure, since gcc's target libraries wound up in the main store output. See #58501

###### Things done

Adjust `pkgs/development/compilers/gcc/builder.sh` to put target system libraries in the `lib` output.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eamsden** [comment]
@illegalprime this pulls in stuff from your PR #58606. Do you mind if I take over since the last commit to that PR was April of last year?? I'll make sure you're still credited with authorship in the git commits.

@lopsided98 you had an alternate way of fixing this, right? Does it work for armv7l and across gcc versions too? If so maybe we should compare these approaches and pick one to advocate for merging.

**Comment by eamsden** [comment]
@flokli cc

**Comment by lopsided98** [comment]
I'm currently testing my version on armv7l. I don't know of any reason it wouldn't work on other gcc versions, but I haven't tested yet.

**Comment by eamsden** [comment]
@lopsided98 can you publish it as a branch? I'd love to try it out too.

**Comment by lopsided98** [comment]
@eamsden https://github.com/lopsided98/nixpkgs/tree/gcc-separate-output-cross

**Comment by lopsided98** [comment]
I successfully built `pkgsCross.armv7l-hf-multiplatform.hello` with my patch

**Comment by flokli** [comment]
@lopsided98 how does your branch differ from the changes proposed here? Can you elaborate?

**Comment by lopsided98** [comment]
The functional difference is that the libraries are placed in `$lib/$targetConfig/lib` (which is the directory convention using by the GCC build scripts) rather than `$lib/lib`. This requires a minor change to cc-wrapper. Subjectively, I believe it is cleaner because it unifies the handling of the cross and non-cross cases and is therefore easier to reason about.

**Comment by matthewbauer** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/81844

**Comment by eamsden** [comment]
Great. Glad this is fixed :)

**Pull request closed without merging**
