### PR TITLE
pytorch: don't install test binaries

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
du -sh /nix/store/3jgj6mi7dpqqfiax81a1x8mv125nrj56-python3.8-pytorch-1.8.1/lib/python3.8/site-packages/torch/test
113M    /nix/store/3jgj6mi7dpqqfiax81a1x8mv125nrj56-python3.8-pytorch-1.8.1/lib/python3.8/site-packages/torch/test
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 118818` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>python38Packages.shap</li>
<li>python38Packages.skorch</li>
<li>python39Packages.skorch</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python38Packages.pywick: log was empty</li>
<li>python39Packages.pywick: log was empty</li>
  </ul>
</details>
<details>
<summary>
10 packages built:
</summary>
<ul>
<li>python38Packages.ignite</li>
<li>python38Packages.rising</li>
<li>python38Packages.slicer</li>
<li>python38Packages.tensorboardx</li>
<li>python38Packages.test-tube</li>
<li>python39Packages.ignite</li>
<li>python39Packages.rising</li>
<li>python39Packages.slicer</li>
<li>python39Packages.tensorboardx</li>
<li>python39Packages.test-tube</li>
</ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by danieldk** [comment]
Sorry, I have been a bit busy arranging an office and stuff, but I'll try to have a look later today.

**Review by danieldk — CHANGES_REQUESTED** [review]
PyTorch' setup script has options to disable building of tests and installation of tests. I think we should use that instead.

I will do a PR in a few minutes (it requires some other changes as well, since we are not passing options correctly.)

**Comment by danieldk** [comment]
See #118964.

**Pull request closed without merging**
