### PR TITLE
cargo-tree: init at 0.18.0

### PR DESCRIPTION
**Pull request by jD91mZM2**

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build cargo-tree

**Comment by xeji** [comment]
looks like `libiconv` is missing for darwin

**Comment by jD91mZM2** [comment]
@xeji Did I do that correctly?

**Comment by xeji** [comment]
don't we all love this trial-and-error stuff :smile: 
@GrahamcOfBorg build cargo-tree

**Comment by jD91mZM2** [comment]
Failure on x86_64-darwin [(full log)](https://youtu.be/dQw4w9WgXcQ)

Attempted: cargo-tree


<details>
<summary>
Partial log (click to expand)
</summary>
OOPSIE WOOPSIE!! Uwu We made a fucky wucky!! A wittle fucko boingo! The code monkeys at our headquarters are working VEWY HAWD to fix this!
</details>

**Comment by xeji** [comment]
@jD91mZM2 looks like you have been hacked - your fake previous post, which I am going to delete, links "full log" to a youtube URL.

image

**Comment by xeji** [comment]
anyway, the PR ist fine now....

**Comment by jD91mZM2** [comment]
@xeji That was a bad attempt at a joke. The YouTube URL was a rickroll. Sorry :stuck_out_tongue:

**Pull request merged**
