### PR TITLE
vencord: 1.5.7 -> 1.5.8

### PR DESCRIPTION
**Pull request by Scrumplex**
## Description of changes

https://github.com/Vendicated/Vencord/compare/v1.5.7...v1.5.8

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Scrumplex** [comment]
ugh, did I actually base this off an old master

**Review by fwam — APPROVED** [review]

**Review by NotAShelf — APPROVED** [review]

**Comment by NotAShelf** [comment]
why don't we add an update script that gets triggered periodically if this keeps going to be as often as it is?
might save some time

**Comment by Scrumplex** [comment]
> why don't we add an update script that gets triggered periodically if this keeps going to be as often as it is? might save some time

Good idea. I am going to add an update script in a separate PR

**Comment by Scrumplex** [comment]
I actually chose to add it to this PR. I thought it might take me longer to implement.

**Review by NotAShelf — APPROVED** [review]

**Comment by fwam** [comment]
breaks reproducibility imo.

sure, it is the pain in the ass, but at least makes it reproducible.

**Comment by Scrumplex** [comment]
> breaks reproducibility imo.
> 
> sure, it is the pain in the ass, but at least makes it reproducible.

Could you elaborate?

**Comment by fwam** [comment]
> > breaks reproducibility imo.
> > 
> > sure, it is the pain in the ass, but at least makes it reproducible.
> 
> Could you elaborate?

Ah, I actually take it back. My bad.

**Review by fwam — APPROVED** [review]

**Review by NotAShelf — APPROVED** [review]

**Pull request merged**
