### PR TITLE
elvish: a small fixup

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

Fixing version variable in order to properly download the source code.
Also, some minor stylistical modifications and additions.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build elvish

**Review by etu — APPROVED** [review]
Looks good to me :-)

**Review by worldofpeace — CHANGES_REQUESTED** [review]
We might as well also switch to using `pname`.
Also the attribute in the commit msg should be `elvish`.

**Comment by AndersonTorres** [comment]
@worldofpeace can you explain that `pname` thing?

**Comment by AndersonTorres** [comment]
Something more to be done, people?

**Pull request merged**
