### PR TITLE
slack: add libappindicator-gtk3 to rpath

### PR DESCRIPTION
**Pull request by colonelpanic8**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
What's the motivation for this change?

**Comment by IvanMalison** [comment]
It makes it so that slack can supply a appindicator/status-notifier-item tray icon. This will only happen when  

* the user has running in the background enabled
* XDG_CURRENT_DESKTOP='Unity' is set

otherwise, behavior is unaffected.

**Comment by worldofpeace** [comment]
Yep, think plasma also supports Ayatana indicators.

**Comment by IvanMalison** [comment]
> Yep, think plasma also supports Ayatana indicators.

Yes, but if you are referring to the need for:

```
XDG_CURRENT_DESKTOP='Unity
```

That actually has to do with electron (see https://github.com/electron/electron/issues/10427)

**Pull request merged**
