### PR TITLE
Update to tensorflow 1.9

### PR DESCRIPTION
**Pull request by jyp**
###### Motivation for this change
Upstream update.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jyp** [comment]
extends #42783 by @dotlambda

**Comment by dotlambda** [comment]
There's a merge conflict.

**Comment by jyp** [comment]
@dotlambda Oops, I had pushed the merge to the wrong branch. Fixed now.

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.tensorflow python3.pkgs.tensorflow python2.pkgs.tensorflow-tensorboard python.pkgs.tensorflow-tensorboard

**Comment by dotlambda** [comment]
We should probably update `meta.platforms`.

**Pull request merged**
