### PR TITLE
pythonPackages.exchangelib: removed due to prolonged breakage

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
There's about 20 other python modules that have been broken prior to the 20.03 release.

Currently I'm just looking for feedback on what the message and convention should be for doing such removals

cc @FRidh 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
If something haven't built successfully for a long time, I don't expect anyone would even notice the removal.

**Comment by vcunat** [comment]
But why not mention the maintainers: @catern

**Comment by FRidh** [comment]
I know some like to throw when software is (re)moved. I don't find showing warnings important, and I think modules can be removed without a trace. Just indeed cc the listed maintainers.

**Comment by catern** [comment]
Thanks for pinging me, let me give fixing it a try.

**Comment by jonringer** [comment]
> But why not mention the maintainers: @catern

@vcunat because there's about 20 other packages, all with different maintainers. I was more or less looking for feedback that the wording of the error is acceptable, so I could move forward with removing the other packages.

**Comment by vcunat** [comment]
Ah, I see.  Well, I see no harm in trying the process including this step.

**Comment by jonringer** [comment]
I'll make a PR per removal if a maintainer is listed, otherwise I'll make another PR to remove all the unmaintained packages

**Comment by jonringer** [comment]
#95265

**Comment by catern** [comment]
Sorry for the long breakage, but it's fixed now (and upgraded to boot)

**Pull request closed without merging**
