### PR TITLE
nixos networking: add vswitch option

### PR DESCRIPTION
**Pull request by ts468**
Add a configuration option for Open vSwitch that is
similar to the option for the Linux kernel ethernet
bridge.

### CODE REVIEW

**Comment by ts468** [comment]
Could someone maybe help me with adding `vswitch` support to `network-interfaces-systemd.nix` as well, please?

**Comment by edolstra** [comment]
Maybe we should *only* add this to the networkd implementation, given that the "scripted" implementation is on the way out. (Adding more code will just create a maintenance problem.)

**Comment by ts468** [comment]
It seems as `networkd` doesn't have native support for `Open vSwitch`, yet? So we would have to add it as, e.g., unit with network target anyway, or? Or we would have to wait, which I might not have enough patience for ;)

**Comment by offlinehacker** [comment]
Looks good to me, does it also work if you want to enslave bridge interfaces?

**Comment by ts468** [comment]
@offlinehacker Thanks for your review! I don't know if Open vSwitch allows to enslave bridge interfaces. Do you think I should filter bridge interfaces out?

**Comment by offlinehacker** [comment]
No, bridges work fine, we use them.

**Comment by ts468** [comment]
@offlinehacker Could you maybe have another look at the updated version, please?
Also, why is the ovsdb service started with `--private-key=db:Open_vSwitch,SSL,private_key --certificate=db:Open_vSwitch,SSL,certificate --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert\SL,ca_cert`? Are that safe defaults? I'm tempted to add a `extraOvsdbFlags` option to openvswitch where such settings could go into. What do you think?

**Comment by offlinehacker** [comment]
@ts468 i'm not sure why these flags are there, or I don't remember, did I add them? Yes extraOvsdbFlags should be nice :)

**Pull request merged**
