### PR TITLE
gcc: Darwin cross-compiler build fixes

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

Building cross-compilers on Darwin is currently broken. This PR was prompted by #270986, but it does not fix that issue because GCC 8 does not build on aarch64-darwin. qmk will need to be updated to use a newer version of GCC.

All supported GCC versions on Darwin except for GCC 11 on aarch64-darwin should be buildable as cross-compilers.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 271787` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 271787` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>qmk</li>
    <li>qmk.dist</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 271787` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by reckenrode** [comment]
I also confirmed the following `pkgsCross.{avr,gnu64}.buildPackages.gcc` versions built:
* aarch64-darwin: 12 and 13; and
* x86_64-darwin: 6, 7, 8, 9, 10, 11, 12, 13.

**Comment by emilytrau** [comment]
Out of curiosity, why is aarch64-darwin cross compiling broken on gcc11 only?

**Review by emilytrau — APPROVED** [review]
thanks so much for this! lgtm. this will get `qmk` building on `x86_64-darwin` again which is good enough for me. qmk on `aarch64-darwin` has [pretty much never worked](https://hydra.nixos.org/job/nixpkgs/trunk/qmk.aarch64-darwin) and i can look into that later.

**Comment by reckenrode** [comment]
I think this will have to be manually backported due to https://github.com/NixOS/nixpkgs/pull/266193.

**Comment by reckenrode** [comment]
> Out of curiosity, why is aarch64-darwin cross compiling broken on gcc11 only?

It’s broken on that and older. The reason for calling out GCC 11 is the native compiler builds and works on aarch64-darwin.

**Comment by emilytrau** [comment]
Tested QMK builds on x86_64-darwin and ofborg is good. Lets go! 🚀

**Pull request merged**
