### PR TITLE
skopeo: add wrapper

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by edef1c** [comment]
This doesn't describe _at all_ what purpose the wrapper / this PR serves.

**Comment by nlewo** [comment]
@GrahamcOfBorg test docker-tools

**Comment by nlewo** [comment]
It would be nice to set the path at build time, to avoid this wrapper. I created the issue https://github.com/containers/storage/issues/622 to track this.

**Review by nlewo — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by nlewo** [comment]
We could actually build a `storage.conf` file with the path of the `fuse-overlay` binary and make this file the default one at build time. 
- the variable we'd need to set: https://github.com/containers/storage/blob/af9373689503bc923c8e1da2ab8ddcdda1e75a62/store.go#L3400)
- and the configuration value to set: https://github.com/containers/storage/blob/master/storage.conf#L74

**Comment by zowoq** [comment]
> We could actually build a `storage.conf` file with the path of the `fuse-overlay` binary and make this file the default one at build time.

If we change the default path to this file at build time will it still read from `/etc/containers/storage.conf` as well?

**Comment by nlewo** [comment]
@zowoq No, Skopeo will not read the `/etc/containers/storage.conf` file anymore (as it is already the case for the default policy file).

**Comment by zowoq** [comment]
> No, Skopeo will not read the `/etc/containers/storage.conf` file anymore

I don't think that it is a good solution then. `/etc/containers/storage.conf` is used by other programs (and will probably end up being managed by the `virtualization.containers` module) and I don't think it should be ignored.

>  (as it is already the case for the default policy file).

The policy file can now be managed by the `virtualization.containers` module which presents another problem.

**Comment by nlewo** [comment]
But we can still change the policy file path on CLI which doesn't seem to be possible for the `storage.conf` file. Moreover, if `rootless` is enabled, our `storage.conf` file will not be used.
So, forget what I said and let's do it with the wrapper.

**Comment by nlewo** [comment]
`docker-tools` tests depending on Skopeo works fine.

**Comment by zowoq** [comment]
@nlewo Would you have an objection if I sent a PR to remove setting the policy at build time?

It's not very clear (and somewhat surprising TBH) that the config in `/etc/containers/policy.json` will be silently ignored unless `skopeo --policy /etc/containers/policy.json` is used.

`skopeo` does throw a fairly clear error if the file doesn't exist and has an `--insecure-policy` option to ignore the error.

**Comment by nlewo** [comment]
@zowoq When there is no `/etc/containers/policy.json` file, will `skopeo` still be working without having to manually specifying it?

**Comment by zowoq** [comment]
Without a policy file it will stop working but passing `--insecure-policy` will allow it to work.

**Comment by nlewo** [comment]
The user who wants to use Skopeo from nixpkgs would then have to understand what this flag means and why it is needed. So, this is a bit annoying...
What about opening an issue on Skopeo to ask if it could work without this file?

**Comment by zowoq** [comment]
> What about opening an issue on Skopeo to ask if it could work without this file?

This file is used by other tools so I don't see how upstream could special case this tool to work without it by default.

**Comment by zowoq** [comment]
I've opened https://github.com/NixOS/nixpkgs/pull/87821, we can continue discussion there.

**Pull request merged**
