### PR TITLE
pretix: init at 2024.2.0

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes

https://github.com/pretix/pretix
Reinventing ticket presales, one ticket at a time.

Tested:
- [x] ticket pdf
- [x] passbook
- [x] pages (breaks, missing static pages, requires packaging changes)
- [x] reluctant-stripe
- [x] stretchgoals
- [x] hardening

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by 0x4A6F — APPROVED** [review]
Thanks

**Comment by mweinelt** [comment]
Some plugins ship static resources, that need to be picked up by `collectstatic`. This should happen during the pretix build, so plugins are currently being propagated into the pretix build. Unfortunatly that does not seem to be sufficient.

```pytb
ERROR 2024-03-16 00:17:46,096 django.request log Internal Server Error: /control/event/foo/77lm8/pages/
Traceback (most recent call last):
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/nix/store/xyzvnwgbzxin3ks0qnb8w6c3xqsifalh-python3-3.11.8/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/pretix/control/context.py", line 64, in contextprocessor
    request._pretix_control_default_context = _default_context(request)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/pretix/control/context.py", line 84, in _default_context
    for receiver, response in html_head.send(request.event, request=request):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/pretix/base/signals.py", line 108, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/pretix_pages/signals.py", line 95, in html_head_control
    return template.render({})
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/compressor/templatetags/compress.py", line 160, in render
    return self.render_compressed(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/compressor/templatetags/compress.py", line 106, in render_compressed
    return self.render_offline(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    original_content = self.get_original_content(context)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/compressor/templatetags/compress.py", line 146, in get_original_content
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/templatetags/static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/templatetags/static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/templatetags/static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0w3hgdxmfrvmcv1zg4b30gfcq2lf452j-python3-3.11.8-env/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pretix_pages/quill/quill.snow.css'
```

**Comment by mweinelt** [comment]
Deployed and tested with a custom event. Ordered a ticket, received mail, got a PDF ticket, could download a passcode. The packaged plugins work. Pretix without plugins will be cached, but changing them will force a rebuild, since they are propagated into the package, so that their static files can be collected by Django app.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 296180` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>healthchecks</li>
    <li>mailman-web</li>
    <li>mailman-web.dist</li>
    <li>pretalx</li>
    <li>pretalx.dist</li>
    <li>pretalx.static</li>
    <li>pretix</li>
    <li>pretix.dist</li>
    <li>python311Packages.django-allauth-2fa</li>
    <li>python311Packages.django-allauth-2fa.dist</li>
    <li>python311Packages.django-compressor</li>
    <li>python311Packages.django-compressor.dist</li>
    <li>python311Packages.django-libsass</li>
    <li>python311Packages.django-libsass.dist</li>
    <li>python311Packages.django-otp</li>
    <li>python311Packages.django-otp.dist</li>
    <li>python311Packages.django-statici18n</li>
    <li>python311Packages.django-statici18n.dist</li>
    <li>python311Packages.django-two-factor-auth</li>
    <li>python311Packages.django-two-factor-auth.dist</li>
    <li>python311Packages.paypalrestsdk</li>
    <li>python311Packages.paypalrestsdk.dist</li>
    <li>python311Packages.wallet-py3k</li>
    <li>python311Packages.wallet-py3k.dist</li>
    <li>python312Packages.django-allauth-2fa</li>
    <li>python312Packages.django-allauth-2fa.dist</li>
    <li>python312Packages.django-compressor</li>
    <li>python312Packages.django-compressor.dist</li>
    <li>python312Packages.django-libsass</li>
    <li>python312Packages.django-libsass.dist</li>
    <li>python312Packages.django-otp</li>
    <li>python312Packages.django-otp.dist</li>
    <li>python312Packages.django-statici18n</li>
    <li>python312Packages.django-statici18n.dist</li>
    <li>python312Packages.django-two-factor-auth</li>
    <li>python312Packages.django-two-factor-auth.dist</li>
    <li>python312Packages.paypalrestsdk</li>
    <li>python312Packages.paypalrestsdk.dist</li>
    <li>python312Packages.wallet-py3k</li>
    <li>python312Packages.wallet-py3k.dist</li>
    <li>seahub</li>
  </ul>
</details>

**Pull request merged**
