### PR TITLE
nixos/nix: convert buildMachines to an attrset to allow overriding

### PR DESCRIPTION
**Pull request by r-vdp**
## Description of changes

I used `types.either` because submodules are not allowed in `types.coercedTo`. The other alternative is to use `apply`, but I think its use is discouraged.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by flokli** [comment]
Why is there a need for ordering?

The nix manual suggests `speedFactor` should work as a preference system, so I'm a bit confused about where the order does matter...

**Comment by r-vdp** [comment]
I don't think there is a need for ordering, we don't have any explicit ordering when using an attrset, do we? Or maybe I'm missing something?

I want to be able to override though, that's why I'd like this to be an attrset instead of a list.

**Comment by flokli** [comment]
> I don't think there is a need for ordering, we don't have any explicit ordering when using an attrset, do we? Or maybe I'm missing something?
> 
> I want to be able to override though, that's why I'd like this to be an attrset instead of a list.

Sorry, I initially misread.

Though I'm not convinced. The list of machines ultimately is a list for Nix(cpp), so exposing it as an attrset just for the sake of being able to set various aspects of individual builders from different places feels like a workaround for a lack of features in the module system.

I think the cleaner way to solve that usecase would be to write a module downstream, allowing you to have that attrset as config in your module, and then ultimately configuring the Nixpkgs one.

**Comment by r-vdp** [comment]
> > I don't think there is a need for ordering, we don't have any explicit ordering when using an attrset, do we? Or maybe I'm missing something?
> > 
> > I want to be able to override though, that's why I'd like this to be an attrset instead of a list.
> 
> Sorry, I initially misread.
> 
> Though I'm not convinced. The list of machines ultimately is a list for Nix(cpp), so exposing it as an attrset just for the sake of being able to set various aspects of individual builders from different places feels like a workaround for a lack of features in the module system.
> 
> I think the cleaner way to solve that usecase would be to write a module downstream, allowing you to have that attrset as config in your module, and then ultimately configuring the Nixpkgs one.

Yeah, it's just sad to have to copy all the options into my own config and keep them in sync.

**Comment by flokli** [comment]
> Yeah, it's just sad to have to copy all the options into my own config and keep them in sync.

I agree, but it's a bit of an obscure usecase, and requiring everyone to update their builder config just for this is a hard sell.

**Pull request closed without merging**
