### PR TITLE
gnomeExtensions: Auto-update: 26 new, 70 changed.

### PR DESCRIPTION
**Pull request by chkno**
###### Motivation for this change
I added an extension to the Gnome Extensions database and I'd like to use it in Nix.

Also: This is the first mundane update using the new automatic Gnome extension packaging mechanism.  It seems to have gone pretty smoothly.  Kudos and thanks to @piegamesde who created the new mechanism in https://github.com/NixOS/nixpkgs/pull/118232 !

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by piegamesde — CHANGES_REQUESTED** [review]
Great, thank you! I'm actually really happy about how easy it is to review these. The convention with suffixing the name of the author is a good idea in general, but the extension that we had in first should not be renamed due to backwards compatibility.

**Comment by chkno** [comment]
> Great, thank you! I'm actually really happy about how easy it is to review these. The convention with suffixing the name of the author is a good idea in general, but the extension that we had in first should not be renamed due to backwards compatibility.

Ok.  Fixed.

It feels crummy picking one of the _five_ hide-activities-button extensions to get the unqualified `hide-activities-button` name.  It feels like picking a 'winner' in some sense — the power of defaults is very strong.  I haven't vetted any of these extensions or their authors.  But you're right about backwards compatibility; breaking existing configs is also bad.  Turning unqualified names into aliases that emit deprecation warnings when a challenger appears feels like more trouble & churn than it's worth. While slightly arbitrary, I guess "first extension to support gnome-shell 38 or 40 wins the unqualified name" is a good-enough naming policy.  :)

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126412` at f5cec70c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>85 packages built successfully:</summary>
  <ul>
    <li>gnomeExtensions.add-to-desktop</li>
    <li>gnomeExtensions.add-userhost-to-panel</li>
    <li>gnomeExtensions.alphabetical-app-grid</li>
    <li>gnomeExtensions.animation-tweaks</li>
    <li>gnomeExtensions.app-grid-tweaks</li>
    <li>gnomeExtensions.appindicator-support</li>
    <li>gnomeExtensions.applications-menu</li>
    <li>gnomeExtensions.auto-activities</li>
    <li>gnomeExtensions.auto-move-windows</li>
    <li>gnomeExtensions.babar</li>
    <li>gnomeExtensions.bing-wallpaper-changer</li>
    <li>gnomeExtensions.blur-my-shell</li>
    <li>gnomeExtensions.bottom-panel</li>
    <li>gnomeExtensions.clean-system-menu</li>
    <li>gnomeExtensions.coverflow-alt-tab</li>
    <li>gnomeExtensions.cpufreq</li>
    <li>gnomeExtensions.custom-hot-corners-extended</li>
    <li>gnomeExtensions.custom-menu-panel</li>
    <li>gnomeExtensions.customize-ibus</li>
    <li>gnomeExtensions.ddterm</li>
    <li>gnomeExtensions.desktop-icons-neo</li>
    <li>gnomeExtensions.desktop-icons-ng-ding</li>
    <li>gnomeExtensions.e-ink-mode</li>
    <li>gnomeExtensions.eclipse</li>
    <li>gnomeExtensions.espresso</li>
    <li>gnomeExtensions.executor</li>
    <li>gnomeExtensions.floating-dock</li>
    <li>gnomeExtensions.focusli</li>
    <li>gnomeExtensions.force-show-osk</li>
    <li>gnomeExtensions.gamemode</li>
    <li>gnomeExtensions.gnome-40-ui-improvements</li>
    <li>gnomeExtensions.gnome-citeurl-search-provider</li>
    <li>gnomeExtensions.gnome-fuzzy-app-search</li>
    <li>gnomeExtensions.gtile</li>
    <li>gnomeExtensions.hibernate-status-button</li>
    <li>gnomeExtensions.hide-activities-button-nmingori</li>
    <li>gnomeExtensions.hide-top-bar</li>
    <li>gnomeExtensions.hide-workspace-thumbnails</li>
    <li>gnomeExtensions.home-assistant-extension</li>
    <li>gnomeExtensions.ideapad</li>
    <li>gnomeExtensions.ideapad-mode</li>
    <li>gnomeExtensions.kitchen-timer</li>
    <li>gnomeExtensions.krypto</li>
    <li>gnomeExtensions.launch-new-instance</li>
    <li>gnomeExtensions.mumbleping</li>
    <li>gnomeExtensions.mute-spotify-ads</li>
    <li>gnomeExtensions.native-window-placement</li>
    <li>gnomeExtensions.no-title-bar-forked</li>
    <li>gnomeExtensions.non-blocking-switcher</li>
    <li>gnomeExtensions.nordvpn-connect</li>
    <li>gnomeExtensions.notification-centerselenium-h</li>
    <li>gnomeExtensions.notification-counter</li>
    <li>gnomeExtensions.obmin</li>
    <li>gnomeExtensions.panel-world-clock-lite</li>
    <li>gnomeExtensions.places-status-indicator</li>
    <li>gnomeExtensions.removable-drive-menu</li>
    <li>gnomeExtensions.round-robin-tab-order</li>
    <li>gnomeExtensions.run-or-raise</li>
    <li>gnomeExtensions.runcat</li>
    <li>gnomeExtensions.screen-lock</li>
    <li>gnomeExtensions.screenshot-window-sizer</li>
    <li>gnomeExtensions.scroll-panel</li>
    <li>gnomeExtensions.shortcuts-for-apt</li>
    <li>gnomeExtensions.show-desktop-applet</li>
    <li>gnomeExtensions.shutdowntimer</li>
    <li>gnomeExtensions.shutdowntimer-mkrajnak</li>
    <li>gnomeExtensions.spin-down-hard-disk</li>
    <li>gnomeExtensions.switch-two-layouts</li>
    <li>gnomeExtensions.time-awareness</li>
    <li>gnomeExtensions.timezone</li>
    <li>gnomeExtensions.top-panel-notification-icons</li>
    <li>gnomeExtensions.translate-clipboard</li>
    <li>gnomeExtensions.transparent-top-panel</li>
    <li>gnomeExtensions.transparent-window-moving</li>
    <li>gnomeExtensions.ubuntu-appearance-gnome-40</li>
    <li>gnomeExtensions.umi-coin-rate</li>
    <li>gnomeExtensions.user-id-in-top-panel</li>
    <li>gnomeExtensions.user-themes</li>
    <li>gnomeExtensions.vertical-overview</li>
    <li>gnomeExtensions.volume-mixer</li>
    <li>gnomeExtensions.wg-indicator</li>
    <li>gnomeExtensions.window-list</li>
    <li>gnomeExtensions.windownavigator</li>
    <li>gnomeExtensions.workspace-indicator</li>
    <li>gnomeExtensions.you2ber</li>
  </ul>
</details>

**Comment by piegamesde** [comment]
I totally agree with you. But it is how it is, and the alternatives I've considered so far weren't any better (I once tried collision resolution over *all* extensions, but then there were dozens with the same name, and most of them long dead). It's also going to be fun in future updates, because we're probably bound to keep the renames forever. (I commented out the 3.38 renames but that was only possible because I didn't have to care about backwards compatibility yet.)

**Review by piegamesde — APPROVED** [review]

**Comment by wucke13** [comment]
I think this should definitely be backported to 21.05. Many extensions are currently not ready for gnome 4, rendering them rather useless.

**Comment by piegamesde** [comment]
I'm sorry this takes so long! Please rebase on latest master. If you want, you can also run the update script again since it's been a month (in that case, keep them as two separate commits for reviewing)

**Pull request closed without merging**
