### PR TITLE
nixos/zfs: import encrypted datasets by default for zfsUnstable

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

Already works like a charm but needs more documentation.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
For the mean-time, these are the commands, I used to get a bootable encrypted zfs:

```bash
zfs create -o encryption=aes-256-gcm -o keyformat=passphrase -o mountpoint=none zroot/root
zfs create -o mountpoint=legacy -o sync=disabled zroot/root/tmp
zfs create -o mountpoint=legacy -o com.sun:auto-snapshot=true zroot/root/home
zfs create -o mountpoint=legacy -o com.sun:auto-snapshot=true zroot/root/nixos
mount -t zfs zroot/root/nixos /mnt
mkdir /mnt/{home,tmp,boot}
mount /dev/sda1 /mnt/boot/
mount -t zfs zroot/root/home /mnt/home/
mount -t zfs zroot/root/tmp /mnt/tmp/
nixos-generate-config  --root /mnt
nixos-install
```

**Comment by Mic92** [comment]
Reasons why you want fs-encryption over luks: https://sockpuppet.org/blog/2014/04/30/you-dont-want-xts/

**Comment by Mic92** [comment]
At least I added documentation here: https://nixos.wiki/wiki/NixOS_on_ZFS#Encrypted_ZFS

**Comment by CMCDragonkai** [comment]
Does this mean at the moment, for my UEFI setup, I still need a separate EFI boot partition that contains everything needed to boot the encrypted ZFS? Is there any plans to integrate this into the NixOS configuration (as a module) before 18.03 is released.

**Comment by Mic92** [comment]
Yes, you there is no bootloader supporting zfs encryption to my knowledge. No, I don't have any plans to backport this, because:

- There is still not stable zfs version supporting this version
- There is also an ongoing pull request for zfs, that will change the disk format: https://github.com/zfsonlinux/zfs/pull/6864

**Comment by davidblewett** [comment]
@Mic92 just an fyi: that upstream PR was merged February 2: https://github.com/zfsonlinux/zfs/pull/6864#issuecomment-362687293 .

**Comment by Mic92** [comment]
@davidblewett yes, we also put a migration guide on the wiki.

**Comment by jaykru** [comment]
Are encrypted data sets supported now in 19.03? Trying to set this up on a fresh install and getting complaints from the zpool/zfs commands when I try setting the encryption option :(

**Comment by eri451** [comment]
As mensoned in the wiki zfs 0.8 is required. How ever the installer comes with 0.7.13. You can update but the kernel module stays in that Version that does not feature encrytion. Therefore the errors.

**Comment by Mic92** [comment]
@jaykru it will work with nixos unstable or if you build your own zfs installer with zfsUnstable enabled: https://github.com/Mic92/dotfiles/blob/1606c820b82353dbf06884cac5a127e1f92479a5/nixos/images/install-iso.nix#L16
https://github.com/Mic92/dotfiles/blob/master/nixos/images/zfs.nix#L2

**Pull request merged**
