### PR TITLE
nodePackages.fauna-shell: init at 0.11.5

### PR DESCRIPTION
**Pull request by hardselius**
###### Motivation for this change

I need `fauna-shell`. Naturally, as a Nix user, I want to avoid `brew` or `npm install -g`. This seemed like a good opportunity to make my first PR to nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by midchildan — APPROVED** [review]

**Comment by hardselius** [comment]
Thanks for the approval! What's the lead time (ish) for getting this merged?

**Comment by midchildan** [comment]
It's hard to tell. You'd need to get a committer to get this merged, but some PRs get buried because of the sheer number of PRs nixpkgs receives each day. If it's taking more than a few weeks, you might want to drop a comment here: https://discourse.nixos.org/t/prs-already-reviewed/2617/68

**Comment by kevincox** [comment]
Can you resolve the merge conflicts then you can ping me for a merge?

**Comment by hardselius** [comment]
@kevincox Thanks for the merge! 🎉

**Pull request merged**
