### PR TITLE
zoom-us: unset Qt env variables to fix dialog boxes

### PR DESCRIPTION
**Pull request by Yarny0**
###### Motivation for this change

Zoom wouldn't show the "Participants" dialog box when used in a plasma environment; precisely, the dialog box failed to show its content.  The problem doesn't exist in other environments like Gnome or Xfce.  Experiments have shown that clearing the environment variable `QML2_IMPORT_PATH` before calling Zoom fixes the issue.

I suspect the reason to be as follows: While the zoom build recipe is called with `libsForQt5xx.callPackage`, putting `qttools.dev` in zoom's `PATH` is the only connection to nixpkgs' Qt ecosystem.  Zoom brings its own Qt libraries.  Hence it seems to be a good idea to shield zoom from access to nixpkgs' Qt files to avoid problems from version mismatch or similar troubles.  So the commit at hand expands zoom's wrapper script to clear the Qt-related enviornemt variables `QML2_IMPORT_PATH` and `QT_PLUGIN_PATH`.

Original issue report, with some discussion: https://github.com/NixOS/nixpkgs/issues/107495#issuecomment-764538071

Notify maintainers: @danbst @tadfisher @doronbehar
Notify reporter: @miniBill

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

More:

- [x] Tested meeting with video on current nixos-unstable channel, in Xfce and in Plasma (inside VirtualBox): participants lists shows up correctly
- [x] Tested meeting with video and audio on NixOS 20.09, in Xfce and in Plasma (Zoom package build with all dependencies from nixos-unstable, surrounding system NixOS 20.09): participants lists shows up correctly

### CODE REVIEW

**Review by doronbehar — COMMENTED** [review]
> I suspect the reason to be as follows: While the zoom build recipe is called with `libsForQt5xx.callPackage`, putting `qttools.dev` in zoom's `PATH` is the only connection to nixpkgs' Qt ecosystem. Zoom brings its own Qt libraries. Hence it seems to be a good idea to shield zoom from access to nixpkgs' Qt files to avoid problems from version mismatch or similar troubles. So the commit at hand expands zoom's wrapper script to clear the Qt-related enviornemt variables `QML2_IMPORT_PATH` and `QT_PLUGIN_PATH`.

Makes sense to me. I'd like to add though, that this issue is sourced from the fact that in general, the environment of _any_ Plasma user is impure by default in terms of environment variables, and they leak in this case in a manner that's harmful for this application's functionality.

Speaking of qttools, It's possible it can be removed and we can resolve to using normal `callPackage` - it was added to the `$PATH` of the wrapper in 2018 in https://github.com/NixOS/nixpkgs/pull/43426 .

**Comment by Mic92** [comment]
I think this is safe for backporting. Please ping me again when this has hit the nixpkgs unstable channels.

**Comment by miniBill** [comment]
Thank you @Yarny0, I really appreciate you taking the time to investigate and create a fix

**Comment by Yarny0** [comment]
@Mic92

Thanks for merging!

[Mic92](https://github.com/NixOS/nixpkgs/pull/116355#issuecomment-799663701):
> I think this is safe for backporting. Please ping me again when this has hit the nixpkgs unstable channels.

This is now part of `nixos-unstable` channel https://hydra.nixos.org/build/139121498 .

Re backporting: I tested this pull request's changes in NixOS 20.09 in Plasma5 desktop environment, without problems (participants list shows up, audio and video working)

**Comment by Mic92** [comment]
@Yarny0 there you go: https://github.com/NixOS/nixpkgs/pull/116821

**Pull request merged**
