### PR TITLE
curl: 8.3.0 -> 8.4.0

### PR DESCRIPTION
**Pull request by 999eagle**
## Description of changes

https://daniel.haxx.se/blog/2023/10/11/curl-8-4-0/

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
Should this go `master` instead of `staging` since it's a "critical security fix"?

**Comment by 999eagle** [comment]
The current `staging-next` cycle is explicitly waiting for this update to be included there: https://github.com/NixOS/nixpkgs/pull/260159#issuecomment-1754556226

**Review by lheckemann — APPROVED** [review]

**Comment by vcunat** [comment]
This is quite a problem on darwin.  If noone resolves the cascade of breakages by the time Hydra has (darwin?) resources to work on this, I'll revert and take just the patch for now, like on 23.05.

Some discussion was at https://github.com/NixOS/nixpkgs/pull/257792#issuecomment-1761102956
/cc @NixOS/darwin-maintainers

**Comment by vcunat** [comment]
We might temporarily revert https://github.com/curl/curl/commit/6ab7e1990bd548059f08c471d20537bca13c67b6 or something.  The issue is in cyclic dependency on CoreServices from stdenv bootstrapping.

**Pull request merged**
