### PR TITLE
python3Packages.cvxpy: 1.1.8 -> 1.1.10

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changelog:
https://github.com/cvxgrp/cvxpy/releases/tag/v1.1.10

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rmcgibbo — COMMENTED** [review]
I think we can remove `nose` from `checkInputs` given the changelog.

**Comment by danieldk** [comment]
> I think we can remove `nose` from `checkInputs` given the changelog.

Also `six` (not used) and `multiprocess` (only used in examples).

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 113412` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-aqua</li>
    <li>python39Packages.qiskit-ignis</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>python37Packages.cvxpy</li>
    <li>python37Packages.qiskit</li>
    <li>python37Packages.qiskit-aer</li>
    <li>python37Packages.qiskit-aqua</li>
    <li>python37Packages.qiskit-ignis</li>
    <li>python38Packages.cvxpy</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python38Packages.qiskit-ignis</li>
    <li>python39Packages.cvxpy</li>
  </ul>
</details>

**Comment by fabaff** [comment]
I guess that build failures will be fixed if #112854 is merged.

**Comment by rmcgibbo** [comment]
It looks like this died on ofborg eval because of an issue with master that has been reverted. If you force-push something to the branch, I think it  should trigger my bot to test on aarch64 which I'm interested in.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113412` at f0820321 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-aqua</li>
    <li>python39Packages.qiskit-ignis</li>
  </ul>
</details>
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/3afda9e9bf0a110e4ffb694b8c3cc860">python37Packages.cvxpy</a></li></li>
    <li><a href="https://gist.github.com/1882ea6a78ad7cdeff099cf0af8ae724">python37Packages.qiskit</a></li></li>
    <li><a href="https://gist.github.com/d8fb524400061c3b13f254d4c2a019e8">python37Packages.qiskit-aer</a></li></li>
    <li><a href="https://gist.github.com/9c772f96da3a422b8200f4ddc674aa7c">python37Packages.qiskit-aqua</a></li></li>
    <li><a href="https://gist.github.com/8244638e2c6a04040b5e2e1bc00f8620">python37Packages.qiskit-ignis</a></li></li>
    <li><a href="https://gist.github.com/f4931b36a63e285d528ae989b4329201">python38Packages.cvxpy</a></li></li>
    <li><a href="https://gist.github.com/1bc6b348a1c9211e4ba8dacea655ee4e">python38Packages.qiskit</a></li></li>
    <li><a href="https://gist.github.com/042a1f53f658ab90d6d8679a2039f82b">python38Packages.qiskit-aer</a></li></li>
    <li><a href="https://gist.github.com/0fab5def10cbdc90acfef187ffe3e561">python38Packages.qiskit-aqua</a></li></li>
    <li><a href="https://gist.github.com/f80b13a39b9ab6e05100540280136432">python38Packages.qiskit-ignis</a></li></li>
    <li><a href="https://gist.github.com/9ed2b4f8cb79ee21b1e87580c67aaa1e">python39Packages.cvxpy</a></li></li>
  </ul>
</details>

**Pull request merged**
