### PR TITLE
goPackages.inflect: add rev to package name

### PR DESCRIPTION
**Pull request by jgillich**
@copumpkin Also had to update the hash, not too sure why.

### CODE REVIEW

**Comment by copumpkin** [comment]
The hash change is worrying. `fetchFromBitBucket` already uses `fetchzip` to avoid tarball differences. Any idea what changed?

**Comment by copumpkin** [comment]
It looks like the difference is in a `.hg_archival.txt`:

```
repo: 384c8ec3ade621d8deb0126f2b0762b60f930435
node: 8961c3750a47b8c0b3e118d52513b97adf85a7e8
branch: default
latesttag: go.r60
latesttagdistance: 12
changessincelatesttag: 12
```

```
repo: 384c8ec3ade621d8deb0126f2b0762b60f930435
node: 8961c3750a47b8c0b3e118d52513b97adf85a7e8
branch: default
latesttag: go.r60
latesttagdistance: 12
```

Looks like something that needs to be stripped out before `buildFromBitBucket` computes its hash.

**Comment by jgillich** [comment]
@copumpkin Updated with fetchhg :)

**Comment by jgillich** [comment]
@vcunat This PR was actually about the package name and not just about the hash.

**Comment by vcunat** [comment]
Ah, I'm sorry, I was rushing too much. I'll amend it.

**Comment by copumpkin** [comment]
Thank you both! Just don't `--amend` it :smile:

**Comment by vcunat** [comment]
It isn't worth it to force-push in this case, of course.

**Comment by vcunat** [comment]
Added version in 6a51a615b4.

**Comment by jgillich** [comment]
Thanks! I used the rev because that's what most other goPackages are doing, but I guess this works too.

**Pull request closed without merging**
