### PR TITLE
nvidia_x11: fix xorg glx missing lib regression

### PR DESCRIPTION
**Pull request by nathanielbaxter**
77986803a63a95505658e942d5e59d78279f1818 moved some code around in the nvidia build script, which caused it to delete some libs instead of moving them, including libglx which meant that xorg loaded without glx extentions, so RIP vidya games. :)

Maintainer: @vcunat

### CODE REVIEW

**Comment by edolstra** [comment]
GTK 2 is still the default GTK in Nixpkgs, so in the interest of reducing closure size, it's better to use GTK 2 at the moment.

**Comment by vcunat** [comment]
Why I chose gtk3: nvidia-settings needs a flag passed to try gtk2 first. But if we wrap it...

**Comment by vcunat** [comment]
@nathanielbaxter: I don't understand what's the problem. I do have ``lib/xorg/modules/extensions/libglx.so.346.35`` and my ``/var/log/X.0.log`` reports successful loading of the glx module.

**Comment by nathanielbaxter** [comment]
@vcunat 
Whoops, I misinterpreted what the issue was. It's not that it deletes files, but rather when it creates symlinks. [libglx.so doesn't get linked to libglx.so.346.35](https://github.com/NixOS/nixpkgs/blob/77986803a63a95505658e942d5e59d78279f1818/pkgs/os-specific/linux/nvidia-x11/builder.sh#L39). It definitely made xorg not find libglx. This is what I get for trying to fix bugs when tired. :/

**Comment by vcunat** [comment]
Ah, I see why the links have disappeared. I'll look into putting them back. (I'm not sure why it creates a problem for you and not for me, but I guess the links should be there anyway.)

**Comment by nathanielbaxter** [comment]
I agree it's strange, but I can reproduce it on nixpkgs master, and this commit does fix it. I'm running the nixpkgs 3.19 kernel, so maybe that effects it? From the xorg log, it finds a libglx.so library provided by xorg instead of the nvidia one when it tries to ' LoadModule "glx" '. Regardless I'll have another look in the morning, thanks. :)

**Comment by vcunat** [comment]
Thanks a lot for reporting this.

Symlinks are back now, and I tried again to better group the builder code. I didn't realize it's a PR with code and not an issue until I was done :-)

**Comment by vcunat** [comment]
GTK stuff wasn't touched by this yet. @edolstra: I guess the default should be gtk2 only with a wrapper to ensure it? I don't feel strongly about this at all, as the nvidia package is quite heavy by itself, so the added single dependency doesn't seem to make much difference.

**Pull request closed without merging**
