### PR TITLE
tox-node: init at 0.0.7

### PR DESCRIPTION
**Pull request by suhr**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by suhr** [comment]
cast @peterhoeg

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Please split your patch into two commits:

1. Adding yourself as maintainer
1. Adding the package

**Comment by suhr** [comment]
Done. Tell if I have to change the commit message to something else.

**Comment by matthiasbeyer** [comment]
@GrahamcOfBorg build tox-node

**Comment by suhr** [comment]
r?

**Review by matthiasbeyer — APPROVED** [review]
Builds for me.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
@suhr thanks!

**Pull request merged**
