### PR TITLE
nixos/monica: fix email configuration bug

### LINKED ISSUE #345193: Monica module creates an incorrect configuration for sending emails
### Describe the bug

Take a look at this link: https://github.com/NixOS/nixpkgs/blob/e2ba9edc297df26732330b7dfc26f5892b0b01ad/nixos/modules/services/web-apps/monica.nix#L299

The config item should be `MAIL_FROM_ADDRESS` not `MAIL_FROM`.

This is based on this link: https://github.com/monicahq/monica/blob/4.x/docs/installation/mail.md#use-smtp-with-monica

When this module is deployed and you attempt to use the mail feature, it fails with a message about invalid email headers.

### Steps To Reproduce
1. Deploy the Monica module with the mail settings configured to talk to an SMTP service
2. Attempt to invite a new user to Monica
3. Observe the resulting error message

### Expected behavior
I expect Monica to be configured to sent email if I pass in those configuration items

### Screenshots
Screenshot from 2024-09-28 17-10-40

### Additional context
I have not been able to test any other email functions, I'm assuming that no email sending works

### Notify maintainers

@Guekka this is a one-line change, so I can do the PR if you'd rather

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@nixos:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by sehqlr**
This is a one-line change to make Monica's email configuration work, and will close https://github.com/NixOS/nixpkgs/issues/345193. This is my first time contributing to nixpkgsI have not done a lot of testing since I'm not 100% on how to do all of it. I'm more than happy to go through a more rigorous process if need be.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

- **Extra args**: `-p nixosTests.monica`
- **Free space**: true
- **Who asked**: lucasew

**TARGETS**
- **x86_64-linux**: true
- **x86_64-darwin**: false
- **aarch64-darwin**: false

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12448279620

**Comment by lucasew** [comment]
I don't know about the domain of this package.

BTW for a lot of services there is tests, called NixOS tests, that basically work by using a python script to interact with a set of VMs. I'm running one of them for monica.

And a suggestion: there is a naming convention on how to name PRs and commits. This case would be something like `nixos/monica: fix email configuration bug`.

Welcome to nixpkgs!

**Comment by lucasewd** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366946`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.monica</li>
  </ul>
</details>

**Comment by sehqlr** [comment]
> there is a naming convention on how to name PRs and commits

Duly noted, I'll refer back to this commit when needed. Thanks

**Comment by Silver-Golden** [comment]
Came across this issue myself last night, glad to see there is a patch in progress for it.  

Taking a look at the issue @Guekka may want to give the approval for this (I know he said go ahead in the other thread but always good to have it here)

**Comment by Guekka** [comment]
Looks good to me. @sehqlr I see you added your name to maintainers. You can make yourself a maintainer of monica if you want, especially since I no longer use this module

**Review by Guekka — APPROVED** [review]

**Pull request merged**
