### PR TITLE
perlPackages.NetServer: 2.009 -> 2.014

### PR DESCRIPTION
**Pull request by stigtsp**
- Updates Net::Server to 2.014
- Re-enable tests

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
@ofborg test hydra

**Comment by aanderse** [comment]
thanks for updating this

is the intention that this package provides the same functionality that `IOSocketINET6` does? after briefly browsing the docs it looks like it maybe can, though not a drop-in replacement

assuming i have understood the docs correctly what would your thoughts be to resolve https://github.com/NixOS/hydra/issues/1297? sounds like it would require some work on `hydra` itself?

i *really* appreciate you looking at this @stigtsp ❤️

**Comment by stigtsp** [comment]
Hi @aanderse 

Started looking at the problem in https://github.com/NixOS/hydra/issues/1297, this is a part of the solution (but set as a draft since I'll likely do a larger PR). 

Replacing IO::Socket::INET{,6} with IO::Socket::IP seems to be a better approach, as this version of Net::Server supports, but need to look into this in a bit more detail and get som hydra tests up for it.

(We were also looking if it was possible to replace Starman in hydra with some other psgi implementation. Cc @marcusramberg)

**Comment by aanderse** [comment]
ok great, i just wanted to clarify so i understood
again, much appreciated 🙇‍♂️

**Comment by aanderse** [comment]
ok great, i just wanted to clarify so i understood
again, much appreciated 🙇‍♂️

**Pull request closed without merging**
