### PR TITLE
haskellPackages.misfortune: remove patch

### PR DESCRIPTION
**Pull request by ncfavier**
Applied in 0.1.2: https://github.com/ncfavier/misfortune/commit/59fe811f30b3544b71d19276076021bba82d2498

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build haskellPackages.misfortune

**Comment by cdepillabout** [comment]
@ncfavier Thanks! If `misfortune` is something you always want to see working, don't hesitate to add yourself as a maintainer!

**Comment by ncfavier** [comment]
I'm a maintainer for lambdabot which depends on misfortune, so that's covered :)

**Comment by cdepillabout** [comment]
Ah, I see, great :-)

**Pull request merged**
