### PR TITLE
luarocks update

### PR DESCRIPTION
**Pull request by teto**
- luaPackages: update
- bumped luarocks-nix
- luaPackages: update

###### Description of changes

I want to add some packages into the set, this is preliminary work for that

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
so nixpkgs-review gives me 
````
error: hash mismatch in fixed-output derivation '/nix/store/v70rq2i2crkwjsvkwywdc81r9cjvnf1i-source.drv':
         specified: sha256-mY5V3P08CTdRJGIe8QvRFxusQPhpUk89dV3rSQX6/c0=
            got:    sha256-u3Q4xPJ9HFWvUxcru7ACE6tuySVyPwii+Gm9pmrsG4s=
error: 1 dependencies of derivation '/nix/store/1vqpfrrhsb1qyzfy2h6vv8kfsxmj53v4-vimplugin-editorconfig-vim-2022-06-20.drv' failed to build
error: hash mismatch in fixed-output derivation '/nix/store/6rzyf3r2947rg9h1zgjxh50dr5m1i86f-source.drv':
         specified: sha256-w99uiDH/ee5o6cYtCz14QcvjNC33Q36xlDL4+bxY+eg=
            got:    sha256-KvgUJtP0h5UlhwNm09t+uSszTNTt6to/UMQsQLV6V5A=
error: 1 dependencies of derivation '/nix/store/fqdaz8wbxfqcl8frf6rrm4mrdbn3cr7n-vimplugin-flake8-vim-2020-10-20.drv' failed to build
warning: dumping very large path (> 256 MiB); this may run out of memory
error: hash mismatch in fixed-output derivation '/nix/store/3im3df2vwkwj2lcikq4rq44p4yk1qah9-source.drv':
         specified: sha256-uHrIRiq2jGtXOamBvLlU+HVhs9JCUGy3h1HPpu2KBIg=
            got:    sha256-LqVNu9umzY2Xjzwj7F/x3ikS6t4+kclY2sr2uJ9XsPg=
error: 1 dependencies of derivation '/nix/store/6059ws1hadymfwv4wzfy5j9zkr22pfgh-vimplugin-tabnine-vim-2022-02-25.drv' failed to build
error: hash mismatch in fixed-output derivation '/nix/store/s8fng3p3q0aywvl7brsrr0w5ajwk4fyr-source.drv':
         specified: sha256-fKtNvW/j1y0FaN8DRfZpciFN/CCnb0cr6LdVj8tTJD8=
            got:    sha256-SVSLRza2J8YTRTse5klmhpCYnww1dUE0Jln5SLW+aEo=
error: 1 dependencies of derivation '/nix/store/gy5h62xq5ghqpz6jfmyhgrrq7dpra7yl-vimplugin-python-mode-2022-01-28.drv' failed to build
error: hash mismatch in fixed-output derivation '/nix/store/34qjnyzj56917xb1xfikx34sb2hgq8kl-source.drv':
         specified: sha256-c/LCFtdiyoCNCIpoiDaUAl6BC5/Lh5D43+CRuGxNrD4=
            got:    sha256-4CoZecwyKJ4zhnzzxMJNF5nZZKfULrzNarX1PwJV74o=
```

I am not sure why :/

**Comment by teto** [comment]
@Scoder12 would it be possible for you to review ? I am interested in knowing if you can build `vimPlugins.YouCompleteMe vimPlugins.editorconfig-vim vimPlugins.flake8-vim vimPlugins.python-mode vimPlugins.tabnine-vim` with this ? I can on my machine but it failed on a remote builder, which prevents me to merge (otherwise nixpkgs-review returns good results).

**Comment by vcunat** [comment]
These are unrelated.  They don't work on nixpkgs master.

**Comment by teto** [comment]
ok thanks let's merge then. The tag shows it concerns a lot of packages but lua-dependant ones are rather small so targetting master is fine (I think).

**Pull request merged**
