### PR TITLE
nixos/tests/common/acme/server/*: use X.509 v3 certificate

### PR DESCRIPTION
**Pull request by typetetris**
###### Motivation for this change

Some client tls libraries don't accept the server certificate if it isn't a X509 v3 certificate.

I wrote some tests for a library which need that. I want to upstream them eventually.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)). I did `rg -li snakeoil` in `nixos/tests` and run all those:
  - [x] nixos/tests/systemd-networkd-vrf.nix
  - [x] nixos/tests/openssh.nix
  - [x] nixos/tests/prometheus.nix
  - [x] nixos/tests/grafana.nix
  - [x] nixos/tests/sanoid.nix
  - [x] nixos/tests/openstack-image.nix
  - [x] nixos/tests/taskserver.nix
  - [x] nixos/tests/prometheus-exporters.nix
  - [x] nixos/tests/nix-ssh-serve.nix
  - [ ] nixos/tests/ec2.nix
  - [x] nixos/tests/pam-oath-login.nix
  - [x] nixos/tests/gitea.nix
  - [ ] nixos/tests/codimd.nix
  - [x] nixos/tests/buildkite-agents.nix
  - [x] nixos/tests/matrix-synapse.nix
  - [x] nixos/tests/xandikos.nix
  - [ ] nixos/tests/google-oslogin/default.nix
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by typetetris** [comment]
`codimd.nix` just hangs, `ec2.nix` and `google-oslogin/default.nix` fail with errors seemingly unrelated to the certificate change.

**Comment by aszlig** [comment]
@typetetris: Those tests don't even use the acme module or did I miss something here?

**Review by aszlig — APPROVED** [review]

**Comment by typetetris** [comment]
> @typetetris: Those tests don't even use the acme module or did I miss something here?

I actually don't know, those files just contain snakeoil, so I did run them.

**Comment by typetetris** [comment]
Not needed any more.

**Pull request closed without merging**
