### PR TITLE
darktable, wireshark: Fix documentation installation directory

### PR DESCRIPTION
**Pull request by rycee**
Fixes documentation directory. Before the documentation files for these packages would end up directly inside `/share/doc` and now they are placed in `/share/doc/${pname}`.

### CODE REVIEW

**Comment by mrVanDalo** [comment]
looks like the better version of  #72160

**Comment by bjornfor** [comment]
https://cmake.org/cmake/help/v3.16/module/GNUInstallDirs.html says `CMAKE_INSTALL_DOCDIR` defaults to `DATAROOTDIR/doc/PROJECT_NAME`. Don't these projects set `project(NAME)` in their CMakeLists.txt files? Ping upstream?

**Comment by bjornfor** [comment]
Ah, this is a workaround for https://github.com/NixOS/nixpkgs/issues/82304.

**Comment by mrVanDalo** [comment]
I used `nix-review pr 83248`
I could verify the crossed out packages (which are in `results`). The other ones I never used.

- [ ] compactor
- [x] darktable
- [ ] haka
- [ ] ostinato
- [x] termshark
- [ ] wifite2
- [x] wireshark
- [x] wireshark-cli

**Review by mrVanDalo — APPROVED** [review]
It shouldn't impact any functionality. I checked for documentation placement in wireguard and darktable. both look legit.

**Pull request closed without merging**
