### PR TITLE
libimagequant: 4.3.0 -> 4.3.1

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/ImageOptim/libimagequant/compare/4.3.0...4.3.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by 0x61nas — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
actually fails to build

       last 3 log lines:
       > checking pkg-config module imagequant in /nix/store/cic1afrdqkw5lz13ygc36gf7q52kl96r-libimagequant-4.3.1
       > ❌ pkg-config module imagequant exists and has version 4.0.4 when 4.3.1 was expected
       > 1 version mismatches
       For full logs, run 'nix log /nix/store/rqc1hqqij2clradqc6hijs3cw8jip0yj-check-pkg-config-imagequant.drv'.

**Comment by trofi** [comment]
I think it was a bug in `staging` due to erroneous `versionCheck` check, 4af3b807fccfddfceb4aad422018a5f9e8cdb8a0 fixed it. At least the test does not fail for me against `staging` locally.

**Comment by philiptaron** [comment]
I'm building my system using this PR. Small builds worked.

**Review by philiptaron — APPROVED** [review]
Full system build succeeded.

**Review by 0x61nas — APPROVED** [review]
I didn't test it locally, but from the diff view I don't see any issues

**Comment by SuperSandro2000** [comment]
@ofborg build libimagequant

**Pull request merged**
