### PR TITLE
Sonarr & radarr vulnerabilities

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Security vulnerabilities found

Fixes https://github.com/NixOS/nixpkgs/issues/33764
Fixes https://github.com/NixOS/nixpkgs/issues/33763

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by adisbladis** [comment]
cc @fadenb

**Comment by Moredread** [comment]
@adisbladis that was fast XD thanks!

Can you backport it to 17.09 please? I'm just testing if it works on that channel, and let you know in a minute

**Comment by adisbladis** [comment]
@Moredread Yes I was already working on backporting it 👍

Backported in d6815c6990cbc93dcda64d2ffa2f7d969a1759b1 and 89517271fa87e42b233a8c0bf2a3d448e6bae067

**Comment by Moredread** [comment]
Cool, thanks :)

**Pull request merged**
