### PR TITLE
teleport: 12.1.0 -> 12.1.5

### PR DESCRIPTION
**Pull request by justinas**
###### Description of changes

A security release. https://github.com/gravitational/teleport/releases/tag/v12.1.5

We now use `cargoLock` for 12 because of https://github.com/NixOS/nixpkgs/pull/221716 .

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by arianvp — APPROVED** [review]

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64. `passthru.tests` passes.

**Comment by risicle** [comment]
Guessing there isn't much hope for the stable branch given the breadth of changes in https://github.com/gravitational/teleport/pull/23864 and that stable release backports don't appear to be a thing upstream.

**Comment by justinas** [comment]
> Guessing there isn't much hope for the stable branch given the breadth of changes in https://github.com/gravitational/teleport/pull/23864 and that stable release backports don't appear to be a thing upstream.

Sorry, I'm afraid I don't really understand your concern. It seems like the linked PR indicates that the fixes have also been backported to v11 and v10 branches, releases should follow very shortly.

**Comment by risicle** [comment]
Oh I completely misread that then - great news :+1:

**Pull request merged**
