### PR TITLE
pet: init at 0.3.2

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

pet: CLI Snippet Manager. Simple command-line snippet manager, written in Go.

https://github.com/knqyf263/pet

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by ryantm — CHANGES_REQUESTED** [review]

**Comment by kalbasit** [comment]
@GrahamcOfBorg build pet

**Comment by kalbasit** [comment]
@ryantm updated it to use `fetchFromGitHub`, PTAL.

**Comment by ryantm** [comment]
@kalbasit You have to be on an approved list in https://github.com/NixOS/ofborg to issue commands to the bot (security and such!).  @GrahamcOfBorg build pet

**Comment by kalbasit** [comment]
@ryantm I don't understand why would this PR breaks the eval of arena.

```
evaluation aborted with the following error message: 'Package ‘arena-1.1’ in /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-0-gleber.ewr1.nix.ci/pkgs/games/arena/default.nix:62 has an invalid meta attrset:
	 - key 'hydryPlatforms' is unrecognized; expected one of: 
	      ['available', 'badPlatforms', 'branch', 'broken', 'description', 'downloadPage', 'downloadURLRegexp', 'executables', 'homepage', 'hydraPlatforms', 'isBuildPythonPackage', 'isFcitxEngine', 'isGutenprint', 'isIbusEngine', 'knownVulnerabilities', 'license', 'longDescription', 'maintainers', 'name', 'outputsToInstall', 'platforms', 'position', 'priority', 'repositories', 'schedulingPriority', 'tag', 'timeout', 'updateWalker', 'version']
	 - key 'synopsis' is unrecognized; expected one of: 
	      ['available', 'badPlatforms', 'branch', 'broken', 'description', 'downloadPage', 'downloadURLRegexp', 'executables', 'homepage', 'hydraPlatforms', 'isBuildPythonPackage', 'isFcitxEngine', 'isGutenprint', 'isIbusEngine', 'knownVulnerabilities', 'license', 'longDescription', 'maintainers', 'name', 'outputsToInstall', 'platforms', 'position', 'priority', 'repositories', 'schedulingPriority', 'tag', 'timeout', 'updateWalker', 'version'], refusing to evaluate.
```

**Comment by ryantm** [comment]
@kalbasit It probably doesn't, it's much more likely someone broke eval on master. Maybe @peti in https://github.com/NixOS/nixpkgs/commit/2c72d70970baa52d28ab1ce2282d5669b40aa36f

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Comment by ryantm** [comment]
@GrahamcOfBorg build pet

**Review by ryantm — APPROVED** [review]

**Comment by kalbasit** [comment]
@ryantm I see. I rebased over master and pushed again.

**Comment by ryantm** [comment]
For future reference, I think rebasing is unnecessary. 

@GrahamcOfBorg build pet

**Comment by kalbasit** [comment]
@ryantm sounds good, just wanted the record clean for the PR.

**Pull request merged**
