### PR TITLE
Update lemmy UI

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

adding an update script and small cleanups

I need a bit of help from a generous soul running on linux to run the update script and give me the resulting pin.json.

(the ci fails because of removed package.json, it is fixed in the next release, so the ci should pass as soon as I update the pin.json)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by billewanick** [comment]
Tried running the update script and everything works except for the uiYarnDepsSha256
```
{
  "version": "0.13.3",
  "serverSha256": "sha256-Ht+gcNv8gQAQtEuAJ/QH4nNvo+PZogNB09f4eRlvIYg=",
  "serverCargoSha256": "sha256-j/l/muCQefvuuWsi+Iahr1M4V6AUzmxm3pr7cJxw7Ww=",
  "uiSha256": "sha256-uHb+V3zadiHlExpmAdRLoV3F/0mrYrko6RTDJcw9YO4=",
  "uiYarnDepsSha256": "error: fetchYarnDeps requires a hash"
}
```

**Comment by happysalada** [comment]
@billewanick my bad, the fetch sha256 error for yarn had been fixed on master, but not yet in this branch. I just rebased. I should be fine now. (when you have a moment to test again).
Sorry about the oversight.

**Comment by billewanick** [comment]
no worries at all! It now successfully updates the hash
```
{
  "version": "0.13.3",
  "serverSha256": "sha256-Ht+gcNv8gQAQtEuAJ/QH4nNvo+PZogNB09f4eRlvIYg=",
  "serverCargoSha256": "sha256-j/l/muCQefvuuWsi+Iahr1M4V6AUzmxm3pr7cJxw7Ww=",
  "uiSha256": "sha256-uHb+V3zadiHlExpmAdRLoV3F/0mrYrko6RTDJcw9YO4=",
  "uiYarnDepsSha256": "sha256-53sa6uL1+SvhtUtKdS36rBcJVgVXhnNdITWPyauLrx4="
}
```

And `nix-build . -A lemmy-ui` builds great.
This is awesome!

**Review by billewanick — APPROVED** [review]
Such an elegant way to update!
:shipit:

**Comment by happysalada** [comment]
I also love this trick!
The ci seems to have the same problem with the package.json as it did before. We need to include it in the repo.
Last update hopefully.

**Comment by happysalada** [comment]
CI is passing, it's time to merge.
Thank you again for the help Bill!

**Pull request merged**
