### PR TITLE
gnatboot: 11.2.0-4 -> 12.1.0-2

### PR DESCRIPTION
**Pull request by ethindp**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
(Building...)

Diff at least LGTM.

**Review by Mindavi — APPROVED** [review]
LGTM, but seems there are some regressions since https://github.com/NixOS/nixpkgs/pull/177579#issuecomment-1183842384. Haven't looked in detail at those, are you planning to look at those or is this as good as it gets?

**Comment by ethindp** [comment]
@Mindavi I'll look into the coreboot ones. I'm unsure why ghat10/11 is failing to build -- that should work fine. I'm also unsure why the ghdl stuff isn't building; all the ghdl packages built on my system, though ghdl-mcode was not deterministic for some reason.

**Comment by Mindavi** [comment]
The log of nixpkgs-review (I reran it):

<details><summary>nixpkgs-review pr 182414 logs</summary>

```
rick@nixos-asus:~/nixpkgs$ nixpkgs-review pr 182414
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/182414/head:refs/nixpkgs-review/1
remote: Enumerating objects: 3560, done.
remote: Counting objects: 100% (2296/2296), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 3560 (delta 2168), reused 2188 (delta 2108), pack-reused 1264
Receiving objects: 100% (3560/3560), 6.01 MiB | 4.11 MiB/s, done.
Resolving deltas: 100% (2515/2515), completed with 837 local objects.
From https://github.com/NixOS/nixpkgs
   e486b59d6d9..ab403f07d35  master     -> refs/nixpkgs-review/0
$ git worktree add /home/rick/.cache/nixpkgs-review/pr-182414-1/nixpkgs ab403f07d359394c175218f66eac826e91b56565
Preparing worktree (detached HEAD ab403f07d35)
Updating files: 100% (31268/31268), done.
HEAD is now at ab403f07d35 Merge pull request #185261 from r-ryantm/auto-update/opentelemetry-collector
$ git merge --no-commit --no-ff bc640dc8832ed48d8880b36caac99af0558c8536
Auto-merging pkgs/development/compilers/gnatboot/default.nix
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/rick/.cache/nixpkgs-review/pr-182414-1/build.nix
error: builder for '/nix/store/rhp5i7g6vf4192f8h94nkjm370imasgd-gnat-6.5.0.drv' failed with exit code 2;
       last 10 log lines:
       > s-aotase.adb:53:25: error: expected type "System.Atomic_Operations.Test_And_Set.Test_And_Set_Flag"
       > s-aotase.adb:53:25: error: found type "System.Address"
       > make[3]: *** [../../gcc-6.5.0/gcc/ada/gcc-interface/Make-lang.in:119: ada/ali.o] Error 1
       > rm gcc.pod
       > make[3]: Leaving directory '/build/build/gcc'
       > make[2]: *** [Makefile:4390: all-stage1-gcc] Error 2
       > make[2]: Leaving directory '/build/build'
       > make[1]: *** [Makefile:21252: stage1-bubble] Error 2
       > make[1]: Leaving directory '/build/build'
       > make: *** [Makefile:21573: bootstrap] Error 2
       For full logs, run 'nix log /nix/store/rhp5i7g6vf4192f8h94nkjm370imasgd-gnat-6.5.0.drv'.
error: 1 dependencies of derivation '/nix/store/imv60w33qd2b92yzd4sb9s5drmw9ciil-gnat-wrapper-6.5.0.drv' failed to build
error: builder for '/nix/store/5bla30hn3slnfpyd9gl6hag577yd6anh-gnat-9.5.0.drv' failed with exit code 2;
       last 10 log lines:
       > s-aotase.adb:53:25: error: found type "System.Address"
       > make[3]: *** [../../gcc-9.5.0/gcc/ada/gcc-interface/Make-lang.in:140: ada/ali.o] Error 1
       > make[3]: *** Waiting for unfinished jobs....
       > rm gcc.pod
       > make[3]: Leaving directory '/build/build/gcc'
       > make[2]: *** [Makefile:4665: all-stage1-gcc] Error 2
       > make[2]: Leaving directory '/build/build'
       > make[1]: *** [Makefile:22807: stage1-bubble] Error 2
       > make[1]: Leaving directory '/build/build'
       > make: *** [Makefile:23128: bootstrap] Error 2
       For full logs, run 'nix log /nix/store/5bla30hn3slnfpyd9gl6hag577yd6anh-gnat-9.5.0.drv'.
error: 1 dependencies of derivation '/nix/store/af19g6441diwrrar2xkd13kzkdif60dd-gnat-wrapper-9.5.0.drv' failed to build
error: builder for '/nix/store/ynyznb2fl35rh32gmlfkwzpfhfy786pn-gnat-10.4.0.drv' failed with exit code 2;
       last 10 log lines:
       > error: ("/nix/store/wq6f3cxqzip6gv6c9s4za9z48af5sxj8-gnatboot-12.1.0-2/lib/gcc/x86_64-pc-linux-gnu/12.1.0/adalib/i-c.ali" is obsolete and read-only)
       > make[3]: *** [../../gcc-10.4.0/gcc/ada/gcc-interface/Make-lang.in:1012: ada/b_gnat1.adb] Error 5
       > make[3]: *** Waiting for unfinished jobs....
       > rm gcc.pod
       > make[3]: Leaving directory '/build/build/gcc'
       > make[2]: *** [Makefile:4754: all-stage1-gcc] Error 2
       > make[2]: Leaving directory '/build/build'
       > make[1]: *** [Makefile:23249: stage1-bubble] Error 2
       > make[1]: Leaving directory '/build/build'
       > make: *** [Makefile:23570: bootstrap] Error 2
       For full logs, run 'nix log /nix/store/ynyznb2fl35rh32gmlfkwzpfhfy786pn-gnat-10.4.0.drv'.
error: 1 dependencies of derivation '/nix/store/qy3b56q61aymipwk4jw5g5s7fj7l6q3h-gnat-wrapper-10.4.0.drv' failed to build
error: builder for '/nix/store/a4dvmfc4aqvviq78ixg7kydyy6sj5fmk-gnat-11.3.0.drv' failed with exit code 2;
       last 10 log lines:
       > error: ("/nix/store/wq6f3cxqzip6gv6c9s4za9z48af5sxj8-gnatboot-12.1.0-2/lib/gcc/x86_64-pc-linux-gnu/12.1.0/adalib/i-c.ali" is obsolete and read-only)
       > make[3]: *** [../../gcc-11.3.0/gcc/ada/gcc-interface/Make-lang.in:1014: ada/b_gnat1.adb] Error 5
       > make[3]: *** Waiting for unfinished jobs....
       > rm gcc.pod
       > make[3]: Leaving directory '/build/build/gcc'
       > make[2]: *** [Makefile:4791: all-stage1-gcc] Error 2
       > make[2]: Leaving directory '/build/build'
       > make[1]: *** [Makefile:24626: stage1-bubble] Error 2
       > make[1]: Leaving directory '/build/build'
       > make: *** [Makefile:24963: bootstrap] Error 2
       For full logs, run 'nix log /nix/store/a4dvmfc4aqvviq78ixg7kydyy6sj5fmk-gnat-11.3.0.drv'.
error: 1 dependencies of derivation '/nix/store/ihsi8hh96lybzb3knv2v6sys6cib2cxp-gnat-wrapper-11.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nlmagaikdklldrmvazia69qdv9ms1ndx-coreboot-toolchain-aarch64-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/317xm1sjgyfcnbljx1h3rwkzll7ig8h5-coreboot-toolchain-arm-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dkzv1hq2xz9r4w1s5sahq690z8nmhp4f-coreboot-toolchain-i386-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x0nar325j8y1nnv845j4v7kzmir6va3p-coreboot-toolchain-nds32le-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h1rxs6rxmv66vp12qx9vx3y068ymar8i-coreboot-toolchain-ppc64-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/47l7hy84677hny3nv9ymgglhcmq51d10-coreboot-toolchain-riscv-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4zpf5a8qyf3qswyl96p5x1v3anpjplsj-coreboot-toolchain-x64-4.16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2nad3mg8r6wq0bcrg592k2vqrivsmrx0-ghdl-llvm-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/80bxa22b6iibayhvgll5a4jg2sb7qjyr-ghdl-mcode-1.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pza1np5sr1hs7x68lqvzq681hik1w9bx-yosys-ghdl-2021.01.25.drv' failed to build
error: 14 dependencies of derivation '/nix/store/3w38hgxqvfg1rd197gpbip6p8xnxk21x-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/182414

14 packages failed to build:
coreboot-toolchain.aarch64 coreboot-toolchain.arm coreboot-toolchain.i386 coreboot-toolchain.nds32le coreboot-toolchain.ppc64 coreboot-toolchain.riscv coreboot-toolchain.x64 ghdl ghdl-llvm gnat10 gnat11 gnat6 gnat9 yosys-ghdl

20 packages built:
gnat gnatboot gnatcoll-core gnatcoll-db2ada gnatcoll-gmp gnatcoll-iconv gnatcoll-lzma gnatcoll-omp gnatcoll-postgres gnatcoll-python3 gnatcoll-readline gnatcoll-sql gnatcoll-sqlite gnatcoll-syslog gnatcoll-xref gnatcoll-zlib gnatinspect gprbuild gprbuild-boot xmlada

error: build log of '/nix/store/nlmagaikdklldrmvazia69qdv9ms1ndx-coreboot-toolchain-aarch64-4.16.drv' is not available
error: build log of '/nix/store/jz29hm5ldyqq1gwwvjmrmxp2vyxmkvji-coreboot-toolchain-aarch64-4.16' is not available
error: build log of '/nix/store/317xm1sjgyfcnbljx1h3rwkzll7ig8h5-coreboot-toolchain-arm-4.16.drv' is not available
error: build log of '/nix/store/rr5l9b3yyphq1ffxr77lsaccsplchlv3-coreboot-toolchain-arm-4.16' is not available
error: build log of '/nix/store/dkzv1hq2xz9r4w1s5sahq690z8nmhp4f-coreboot-toolchain-i386-4.16.drv' is not available
error: build log of '/nix/store/bhr1qn7cqkj9jl1dykjl8783rspyq434-coreboot-toolchain-i386-4.16' is not available
error: build log of '/nix/store/x0nar325j8y1nnv845j4v7kzmir6va3p-coreboot-toolchain-nds32le-4.16.drv' is not available
error: build log of '/nix/store/9s1xhzhlamrrdg3x2sp8ky47lbahhgya-coreboot-toolchain-nds32le-4.16' is not available
error: build log of '/nix/store/h1rxs6rxmv66vp12qx9vx3y068ymar8i-coreboot-toolchain-ppc64-4.16.drv' is not available
error: build log of '/nix/store/4zlx1s4h60ji6q8zg97n77hvsfswprmg-coreboot-toolchain-ppc64-4.16' is not available
error: build log of '/nix/store/47l7hy84677hny3nv9ymgglhcmq51d10-coreboot-toolchain-riscv-4.16.drv' is not available
error: build log of '/nix/store/q8ivsa30j49lfgdll2waknrvshs9ckip-coreboot-toolchain-riscv-4.16' is not available
error: build log of '/nix/store/4zpf5a8qyf3qswyl96p5x1v3anpjplsj-coreboot-toolchain-x64-4.16.drv' is not available
error: build log of '/nix/store/c26bfblp01q412jwcfqs6lxg5nsgw0pa-coreboot-toolchain-x64-4.16' is not available
error: build log of '/nix/store/80bxa22b6iibayhvgll5a4jg2sb7qjyr-ghdl-mcode-1.0.0.drv' is not available
error: build log of '/nix/store/svzjghcl29rw6cqrpk8hn741y7rbzqhw-ghdl-mcode-1.0.0' is not available
error: build log of '/nix/store/2nad3mg8r6wq0bcrg592k2vqrivsmrx0-ghdl-llvm-1.0.0.drv' is not available
error: build log of '/nix/store/bvyzjfm77alkxwpl8gcdj2x3xfik1jxd-ghdl-llvm-1.0.0' is not available
error: build log of '/nix/store/qy3b56q61aymipwk4jw5g5s7fj7l6q3h-gnat-wrapper-10.4.0.drv' is not available
error: build log of '/nix/store/3pjhv0ziyynqzy0biw05p19wb13b3f33-gnat-wrapper-10.4.0' is not available
error: build log of '/nix/store/ihsi8hh96lybzb3knv2v6sys6cib2cxp-gnat-wrapper-11.3.0.drv' is not available
error: build log of '/nix/store/gnvi2ssmi4ibmw7njvg89sxsz0qwhckb-gnat-wrapper-11.3.0' is not available
error: build log of '/nix/store/imv60w33qd2b92yzd4sb9s5drmw9ciil-gnat-wrapper-6.5.0.drv' is not available
error: build log of '/nix/store/q155hdcnd60pxdkf5gd05avvmv583vl9-gnat-wrapper-6.5.0' is not available
error: build log of '/nix/store/af19g6441diwrrar2xkd13kzkdif60dd-gnat-wrapper-9.5.0.drv' is not available
error: build log of '/nix/store/qxv01ck08nkr618hh1sh14nlg2dbldl7-gnat-wrapper-9.5.0' is not available
error: build log of '/nix/store/pza1np5sr1hs7x68lqvzq681hik1w9bx-yosys-ghdl-2021.01.25.drv' is not available
error: build log of '/nix/store/s2z5w9vrsmqvw4hl85nq0c7q57ys0rkn-yosys-ghdl-2021.01.25' is not available
$ /nix/store/ddfhjajcg6b4pach8hf4nv63kxiyhrxl-nix-2.10.3/bin/nix-shell /home/rick/.cache/nixpkgs-review/pr-182414-1/shell.nix
```

</details>

**Comment by ethindp** [comment]
@Mindavi I genuinely have no idea why that's being caused. I might be wrong but I feel like these errors are specific to the projects in question and not due to the version of Gnat in particular. I don't understand why since coreboot-toolchain builds its own version of gnat, so this shouldn't be happening. I'm not sure how to go about fixing the other failures, unfortunately. It might be worth investigating this in separate PRs.

**Comment by Mindavi** [comment]
Fine with me. Thanks!

**Comment by vcunat** [comment]
Well, older gnat versions won't build now and consequently also some other packages like ghdl: https://hydra.nixos.org/eval/1775085#tabs-now-fail

**Comment by vcunat** [comment]
I think some of these could be pruned (removed or marked as broken), but it's not healthy to keep them trying and failing over longer term.

**Pull request merged**
