### PR TITLE
ocamlPackages.elpi: 1.2.0 -> 1.4.0

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Major update.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.elpi: 1.2.0 -> 1.4.0

**Review by jonringer — APPROVED** [review]
Not sure why ofBorg failed
`$ nix-review pr 63727` passed on NixOS
diff LGTM
```
[3 built, 14 copied (441.1 MiB), 82.6 MiB DL]
https://github.com/NixOS/nixpkgs/pull/63727
1 package were build:
ocamlPackages.elpi
```

**Comment by vbgl** [comment]
The bot failed because my first request to it was wrong…

**Comment by vbgl** [comment]
Closed by #63811.

**Pull request closed without merging**
