### PR TITLE
[Backport release-24.05] bookstack: 24.05.3 -> 24.05.4

### PR DESCRIPTION
**Pull request by HritwikSinghal**
(cherry picked from commit a8f5ef66e5d6e7f03a2c7af026d096372f651c74)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

https://github.com/NixOS/nixpkgs/pull/338990

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Should the test fail?

**Comment by HritwikSinghal** [comment]
> Should the test fail?

`Note this should not necessarily be treated as a hard fail, but a reviewer's attention should be drawn to it and github actions have no way of doing that but to raise a 'failure'`

**Comment by HritwikSinghal** [comment]
i've checked the changes and they match what the latest master should contain. i think this cherry-pick test fails as NixOS 24.04 had bookstack upgrade  v24.05.3 -> v24.05.4 and the unstable had v24.05.2 -> v24.05.4.

So when i cherry-picked it, i used `--strategy-option theirs` and merged the new changes. Should work fine as the final file is same as whats on master.

@SuperSandro2000

**Comment by SuperSandro2000** [comment]
> Note this should not necessarily be treated as a hard fail, but a reviewer's attention should be drawn to it and github actions have no way of doing that but to raise a 'failure'

I know, we are using github status' wrong.

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
   INFO  Discovering packages.  
  laravel/socialite ..................................................... DONE
  laravel/tinker ........................................................ DONE
  nesbot/carbon ......................................................... DONE
  nunomaduro/termwind ................................................... DONE
  socialiteproviders/manager ............................................ DONE
Generated optimized autoload files containing 7344 classes
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading symfony/polyfill-php83 (v1.30.0)
  - Downloading intervention/gif (4.1.0)
  - Downloading firebase/php-jwt (v6.10.1)
 0/3 [>---------------------------]   0%    Failed to download symfony/polyfill-php83 from dist: curl error 6 while downloading https://api.github.com/repos/symfony/polyfill-php83/zipball/dbdcdf1a4dcc2743591f1079d0c35ab1e2dcbbc9: Could not resolve host: api.github.com
    Now trying to download from source
  - Syncing symfony/polyfill-php83 (v1.30.0) into cache
    Failed to download intervention/gif from dist: curl error 6 while downloading https://api.github.com/repos/Intervention/gif/zipball/3a2b5f8a8856e8877cdab5c47e51aab2d4cb23a3: Could not resolve host: api.github.com
    Now trying to download from source
  - Syncing intervention/gif (4.1.0) into cache
    Failed to download firebase/php-jwt from dist: curl error 6 while downloading https://api.github.com/repos/firebase/php-jwt/zipball/500501c2ce893c824c801da135d02661199f60c5: Could not resolve host: api.github.com
    Now trying to download from source
  - Syncing firebase/php-jwt (v6.10.1) into cache
 3/3 [============================] 100%
In Git.php line 473:
                                                                               
  Failed to clone https://github.com/symfony/polyfill-php83.git via https, ss  
  h protocols, aborting.                                                       
                                                                               
  - https://github.com/symfony/polyfill-php83.git                              
    Cloning into bare repository '/build/.cache/composer/vcs/https---github.c  
  om-symfony-polyfill-php83.git'...                                            
    fatal: unable to access 'https://github.com/symfony/polyfill-php83.git/':  
   Could not resolve host: github.com                                          
                                                                               
  - git@github.com:symfony/polyfill-php83.git                                  
    Cloning into bare repository '/build/.cache/composer/vcs/https---github.c  
  om-symfony-polyfill-php83.git'...                                            
    error: cannot run ssh: No such file or directory                           
    fatal: unable to fork                                                      
                                                                               
install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
error: builder for '/nix/store/hpscrkgif0dhzly12pnkmr119acgpmbr-bookstack.drv' failed with exit code 1;
```

**Comment by risicle** [comment]
The cherry-pick weirdness here is because somehow the stable branch ended up with 24.05.3 while master remained on 24.05.2. I would probably just remove the cherry-pick line from the commit message as it's just not closely related enough.

**Pull request closed without merging**
