### PR TITLE
gptfdisk: Backport upstream fix for popt 1.19

### PR DESCRIPTION
**Pull request by amarshall**
###### Description of changes

Existing patch in nixpkgs causes segfault, see
https://github.com/NixOS/nixpkgs/issues/219775. This replaces that with cherry-picks from upstream.

###### Things done

- Tested basic behavior (`sgdisk --version ; sgdisk /dev/sda1`) and both seem to work okay.
- Tested that partitioning operations in gnome disks that previous failed now work.
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

nixpkgs-review output (note that gnomeExtensions.easyScreenCast is failing on base master):
```
121 packages updated:
adapta-gtk-theme almanah bubblemail calls cantata chatty cheese cinnamon-common cinnamon-control-center cinnamon-gsettings-overrides cinnamon-screensaver clementine-unstable cloud-init cloud-utils coreaction corearchiver corefm coregarage corehunt coreimage coreinfo corekeyboard corepad corepaint corepdf corepins corerenamer coreshot corestats corestuff coreterminal coretime coretoppings coreuniverse dde-device-formatter-unstable deepin-album deepin-compressor deepin-image-viewer deepin-music elementary-calendar elementary-greeter elementary-mail elementary-planner elementary-session-settings elementary-tasks endeavour enlightenment eos-installer evolution evolution-data-server evolution-data-server evolution-ews evolution-with-plugins exaile folks geary gfbgraph gnome-applets gnome-browser-connector gnome-browser-connector gnome-calendar gnome-contacts gnome-control-center gnome-disk-utility gnome-flashback gnome-gsettings-overrides gnome-initial-setup gnome-multi-writer gnome-music gnome-notes gnome-online-accounts gnome-online-miners gnome-panel gnome-photos gnome-recipes gnome-session gnome-shell gnome-shell-extension-EasyScreenCast gnome-shell-extension-gsconnect gnome-shell-extension-system-monitor-unstable gnome-terminal gnome-tweaks gptfdisk grilo-plugins gvfs gvfs libblockdev libcsys libgdata libzapojit mailnag mate-utils mojave-gtk-theme monitor nemo nemo-fileroller nemo-python nemo-with-extensions phosh phosh-mobile-settings psensor rabbitvcs rapid-photo-downloader spacefm switchboard-plug-about switchboard-plug-onlineaccounts switchboard-with-plugs totem udiskie udisks udisks2-qt5 usbimager usermount vifm-full vimix-gtk-themes whitesur-gtk-theme wingpanel-applications-menu wingpanel-indicator-datetime wingpanel-with-indicators xmonad-log-applet-gnomeflashback-unstable zpool-auto-expand-partitions

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/amarshall/.cache/nixpkgs-review/rev-90c0d8cf1eedb59247e2c0259832a2f332ebf6ae/build.nix
error: builder for '/nix/store/wq1l8gqv7w136kdg5jabq4z12k0gczyg-gnome-shell-extension-EasyScreenCast-1.7.0.drv' failed with exit code 2;
       last 10 log lines:
       > msgfmt -c locale/ja.po -o locale/ja.mo
       > msgfmt -c locale/pt_BR.po -o locale/pt_BR.mo
       > msgfmt -c locale/ru.po -o locale/ru.mo
       > msgfmt -c locale/uk.po -o locale/uk.mo
       > msgfmt -c locale/vi.po -o locale/vi.mo
       > mkdir -p locale
       > xgettext -k --keyword=_ --keyword=N_ --from-code=UTF-8 --add-comments='Translators:' -o locale/easyscreencast.pot --package-name "EasyScreenCast" prefs.js extension.js selection.js utilwebcam.js
       > intltool-extract --type=gettext/glade Options_UI.glade
       > /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash: line 1: intltool-extract: command not found
       > make: *** [Makefile:62: locale/easyscreencast.pot] Error 127
       For full logs, run 'nix log /nix/store/wq1l8gqv7w136kdg5jabq4z12k0gczyg-gnome-shell-extension-EasyScreenCast-1.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/9zj0g8zh1j7kgb2xvjr9vdc2a7vfr14c-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1rl97hxc2j66avhbqdimnynrgjfix35h-review-shell.drv' failed to build
6 packages marked as broken and skipped:
chrome-gnome-shell elementary-planner gnome2.gvfs mailnagWithPlugins pantheon.elementary-tasks xmonad_log_applet

1 package failed to build:
gnomeExtensions.easyScreenCast

114 packages built:
CuboCore.coreaction CuboCore.corearchiver CuboCore.corefm CuboCore.coregarage CuboCore.corehunt CuboCore.coreimage CuboCore.coreinfo CuboCore.corekeyboard CuboCore.corepad CuboCore.corepaint CuboCore.corepdf CuboCore.corepins CuboCore.corerenamer CuboCore.coreshot CuboCore.corestats CuboCore.corestuff CuboCore.coreterminal CuboCore.coretime CuboCore.coretoppings CuboCore.coreuniverse CuboCore.libcsys adapta-gtk-theme almanah bubblemail calls cantata chatty cinnamon.cinnamon-common cinnamon.cinnamon-control-center cinnamon.cinnamon-gsettings-overrides cinnamon.cinnamon-screensaver cinnamon.nemo cinnamon.nemo-fileroller cinnamon.nemo-python cinnamon.nemo-with-extensions clementine cloud-init cloud-utils deepin.dde-device-formatter deepin.deepin-album deepin.deepin-compressor deepin.deepin-image-viewer deepin.deepin-music deepin.udisks2-qt5 endeavour enlightenment.enlightenment eos-installer evolution evolution-data-server evolution-data-server-gtk4 evolution-ews evolutionWithPlugins exaile folks gfbgraph gnome-browser-connector gnome-multi-writer gnome-online-accounts gnome-photos gnome-recipes gnome.cheese gnome.geary gnome.gnome-applets gnome.gnome-calendar gnome.gnome-contacts gnome.gnome-control-center gnome.gnome-disk-utility gnome.gnome-flashback gnome.gnome-initial-setup gnome.gnome-music gnome.gnome-notes gnome.gnome-online-miners gnome.gnome-panel gnome.gnome-session gnome.gnome-shell gnome.gnome-terminal gnome.gnome-tweaks gnome.gvfs gnome.nixos-gsettings-overrides gnome.totem gnomeExtensions.gsconnect gnomeExtensions.system-monitor gptfdisk grilo-plugins libblockdev libgdata libzapojit mate.mate-utils mojave-gtk-theme monitor pantheon.elementary-calendar pantheon.elementary-greeter pantheon.elementary-mail pantheon.elementary-session-settings pantheon.switchboard-plug-about pantheon.switchboard-plug-onlineaccounts pantheon.switchboard-with-plugs pantheon.wingpanel-applications-menu pantheon.wingpanel-indicator-datetime pantheon.wingpanel-with-indicators phosh phosh-mobile-settings psensor rabbitvcs rapid-photo-downloader spaceFM udiskie udisks usbimager usermount vifm-full vimix-gtk-themes whitesur-gtk-theme zpool-auto-expand-partitions
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ajs124** [comment]
can't this be `fetchpatch`d?

**Comment by lilyinstarlight** [comment]
We could `fetchpatch` from Debian's patch: <https://salsa.debian.org/debian/gdisk/-/raw/0170456c4f021a6d98df7decf4e23d573109ff34/debian/patches/handle-plugged-memory-leak-from-popt>

There's at least a lot of prior art for doing that in nixpkgs to avoid vendoring a patch and their patch looks better than the leaky Fedora patch or the split Arch patch (Gentoo patch is the same as Debian's)

**Comment by unitythemaker** [comment]
That is so stupid. We cannot just fork and edit the code on GitHub because it is on SourceForge right (license things)? I find it a bit strange that distros have resorted to creating patches and workarounds rather than fixing the issue at its source. Is there a reason why the actual owner of this package doesn't fix it?

**Comment by lilyinstarlight** [comment]
> That is so stupid. We cannot just fork and edit the code on GitHub because it is on SourceForge right (license things)? I find it a bit strange that distros have resorted to creating patches and workarounds rather than fixing the issue at its source. Is there a reason why the actual owner of this package doesn't fix it?

It has been fixed for a while now, there just hasn't been a release with the fix in it. All of the distro patches (except maybe the fedora one) are based on the upstream commits

**Pull request merged**
