### PR TITLE
1password-gui: Patch op-ssh-sign to work

### PR DESCRIPTION
**Pull request by Lyndeno**
###### Description of changes

`op-ssh-sign` did not work without being patched like the rest of the binaries. This seems to fix that.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
  - [x] Used `nix build .#_1password-gui`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SebTM** [comment]
Not using this feature so can't verify it, changeset looks reasonable :) 👍🏻

**Review by SebTM — APPROVED** [review]

**Comment by Lyndeno** [comment]
Anything blocking from merging at this time?

**Comment by SebTM** [comment]
> Anything blocking from merging at this time?

Not from me, don't have permission - would appreciate it 👍🏻

**Comment by maxeaubrey** [comment]
I'll hit merge. 1p could use a few more fixups (deduping, adding the shared electron arguments, and wrapping the other helper that's distributed with it, whatever it's supposed to do), but I don't have the time to do it all myself right now.

Thanks for fixing up the commit signing integration.

**Comment by SebTM** [comment]
> deduping
I think we could do something like https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/atom/default.nix here

> adding the shared electron arguments
Can you give me an example? 

> wrapping the other helper that's distributed with it
Why should we wrap the helper (especially 1Password-BrowserSupport,1Password-KeyringHelper) as they are properly working? (or did I get something wrong?)

**Comment by maxeaubrey** [comment]
> Can you give me an example?

I'm talking about `NIXOS_OZONE_WL`, which is helpful if you're running 1p on Wayland and have fractional scaling. I've been relying on it for a while.

> Why should we wrap the helper (especially 1Password-BrowserSupport,1Password-KeyringHelper) as they are properly working? (or did I get something wrong?)

There's also `1Password-HIDHelper`, I'm unclear on its purpose or functionality. We do not currently wrap it.

**Comment by SebTM** [comment]
> There's also `1Password-HIDHelper`, I'm unclear on its purpose or functionality. We do not currently wrap it.

Good question, can't find sth. about it - maybe @savannidgerinel could help out on this?

**Comment by Lyndeno** [comment]
Perhaps it is used for U2F key functionality? I cannot remember if I logged in to my client with my key last time though so I cannot say if it works as is or not.

**Comment by SebTM** [comment]
> Perhaps it is used for U2F key functionality? I cannot remember if I logged in to my client with my key last time though so I cannot say if it works as is or not.

I think we should patchelf it too, but not wrap it until we find someone using/needing it and the need of a wrapper?

**Comment by SebTM** [comment]
> I'm talking about `NIXOS_OZONE_WL`, which is helpful if you're running 1p on Wayland and have fractional scaling. I've been relying on it for a while.

https://github.com/NixOS/nixpkgs/blob/c44d41af6a77b61fd627f6386e018c8ec2c99d16/pkgs/applications/networking/instant-messengers/schildichat/schildichat-desktop.nix#L92

Is this the change you would need? Then I will do the PR for it. Don't use Wayland, so can't reproduce myself.

**Comment by maxeaubrey** [comment]
@SebTM That's indeed the change. If you have the time to do this that would be greatly appreciated, I barely have the time right now to do much outside of trying to review PRs once in a while.

**Pull request merged**
