### PR TITLE
treewide: don't set platforms.unix for buildGoModule

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

In review meta.platforms that is equal to go's default is often stripped. This applies it retro actively to all existing packages.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IndeedNotJames** [comment]
Context: https://github.com/NixOS/nixpkgs/pull/223757#discussion_r1154957960

**Review by RaitoBezarius — CHANGES_REQUESTED** [review]
Please perform a nixpkgs-review to evaluate the damage and if it's small enough, let's merge.

**Comment by IndeedNotJames** [comment]
@RaitoBezarius this change is a no-op. It doesn't actually change anything for `linux` and `darwin`.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius this change is a no-op. It doesn't actually change anything for `linux` and `darwin`.

If it's a real no-op, nixpkgs-review will do no work. :)

**Comment by IndeedNotJames** [comment]
There are merge conflicts, so `-c commit` has to be used.

`nixpkgs-review pr 225362 -c commit` returns:
```
HEAD is now at 689979461ca treewide: don't set platforms.unix for buildGoModule
Nothing to be built.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/225362
```

and the actual report:

---

Result of `nixpkgs-review pr 225362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by RaitoBezarius** [comment]
> There are merge conflicts, so `-c commit` has to be used.
> 
> `nixpkgs-review pr 225362 -c commit` returns:
> 
> ```
> HEAD is now at 689979461ca treewide: don't set platforms.unix for buildGoModule
> Nothing to be built.
> 
> Link to currently reviewing PR:
> https://github.com/NixOS/nixpkgs/pull/225362
> ```
> 
> and the actual report:
> 
> Result of `nixpkgs-review pr 225362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

Awesome, let's fix the merge conflicts and merge.

**Comment by SuperSandro2000** [comment]
Thanks for rebasing!

**Pull request merged**
