### PR TITLE
clojure-lsp: 2021.02.14-19.46.47 -> 2021.04.13-12.47.33

### PR DESCRIPTION
**Pull request by ericdallo**
###### Motivation for this change
Bump clojure-lsp
The new version don't use lein anymore and is not trivial to build from clojure cli, so I'm using the jar again.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ericdallo** [comment]
Result of `nixpkgs-review pr 120092` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>clojure-lsp</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 120092` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>clojure-lsp</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by ericdallo** [comment]
Would you mind merge this please @SuperSandro2000 ?

**Comment by ericdallo** [comment]
Thank you!

**Pull request merged**
