### PR TITLE
turbovnc: init at 2.2.5

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

`turbovnc` is a VNC server + client forked from TightVNC, and made by the makers of `libjpeg-turbo` and `virtualgl`.

A key point about it is that it integrates 3D software rendering via mesa/swrast (in which case `virtualgl` is then unnecessary), allowing to run 3D programs easily on the VNC server.

**How to test:**

To run the server, run either:

* `vncserver`, a wrapper script, which asks to set a password set in your home dir, determines default settings and backgrounds itself
* run what that wrapper script starts (see `ps aux | grep Xvnc`), which looks like e.g.
  ```sh
  Xvnc :4 \
  -httpd /nix/store/4fbj9mlyhw8ypayf0pyyd7zgb831p7gp-turbovnc-2.2.5/share/turbovnc/classes \
  -auth /root/.Xauthority \
  -geometry 1240x900 \
  -depth 24 \
  -rfbwait 120000 \
  -rfbauth ~/.vnc/passwd \
  -x509cert ~/.vnc/x509_cert.pem \
  -x509key ~/.vnc/x509_private.pem \
  -rfbport 5904 \
  -deferupdate 1 \
  -verbose
  ```

Note the port in `-rfbport 5904` and the `:4` to choose a free X display.

(I added the `-verbose`, it's useful to see errors, e.g. I could see in there that software rendering didn't work before I added the path to mesa swrast, such as: `(EE) AIGLX error: dlopen of /var/empty/lib64/dri/swrast_dri.so failed (/var/empty/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory`).

To run the server, run `vncviewer` (it's a GUI, but also accepts CLI arguments).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
CC @siraben @iblech @dtzWill @7c6f434c @viric from a quick git log of who contributed to `tigervnc` and might be able to help with some of the remaining (but optional, since it works) `TODO` comments in the derivations.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113657` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>turbovnc</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
turbovnc:
<details>


perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/tools/admin/turbovnc/default.nix:49:3:

```
   |
49 |   buildInputs = [
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md
</details>
</details>

**Comment by nh2** [comment]
> perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

What about the case that the perl is used at runtime in a hashbang, and pinned with `patchShebangs`?

In that case, should `perl` be a `buildInputs` or `nativeBuildInputs`?

**Comment by iblech** [comment]
I believe that in this case, it should be in `buildInputs`, and the suggestion, though useful in many instances, is misguiding here.

**Comment by iblech** [comment]
This is very good work! Thank you so much for this! I would merge this almost as is, further improvements can always be made.

There is just one thing: The `vncserver` binary doesn't work if xorg.xauth is not in the path. (That's also the case for other vnc servers, such as tightvnc.) Hence you'll need to use something like:

```
wrapProgram $out/bin/vncserver \
      --prefix PATH : ${stdenv.lib.makeBinPath (with xorg; [ xauth ]) }
```

You might also think about adding `twm` on the same line (because this is the default window manager).

Regarding your other question, I believe that `ssh` does need to be in the path for SSH forwarding using the GUI to work. I'm not sure whether we should depend on openssh, however. Firstly, almost anyone has `ssh` in their path, so the issue doesn't actually matter. But secondly, for those who want to abstain from openssh for whatever reason (closure size, preferences for another ssh implementation, ...) we probably should not pull in openssh by force. I'm not sure what's the best solution is.

**Comment by SuperSandro2000** [comment]
> > perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.
> 
> What about the case that the perl is used at runtime in a hashbang, and pinned with `patchShebangs`?
> 
> In that case, should `perl` be a `buildInputs` or `nativeBuildInputs`?

I think it goes to buildInputs. That check might need some more work to have less false positives.

**Comment by SuperSandro2000** [comment]
> wrapProgram $out/bin/vncserver \
>       --prefix PATH : ${stdenv.lib.makeBinPath (with xorg; [ xauth ]) }

stdenv.lib is deprecated. Please use lib instead.

**Comment by nh2** [comment]
> I'm not sure whether we should depend on openssh

I think that's probably fine; it already requires Java (large), Mesa (large) and openssl, from which openssh is not a large step.

So I'm adding it.

> You might also think about adding `twm` on the same line (because this is the default window manager).

Done.

Note that on e.g. nix-on-Ubuntu, the [`~/.vnc/xstartup.turbovnc`](https://github.com/TurboVNC/turbovnc/blob/ffdb57d9/unix/vncserver.in) startup script that [`vncserver` writes](https://github.com/TurboVNC/turbovnc/blob/f39660050547e7e5730a34c358691b6b5ac245a8/unix/vncserver.in#L642) checks for `/usr/bin/gnome-session` and `/etc/X11/xinit/xinitrc` before falling back to `twm`, so I had to move those out of the way to test that it works by default.

**Comment by nh2** [comment]
Ready to merge when ofborg goes green on Linux.

**Comment by nh2** [comment]
Adding a NixOS test in PR #116282.

**Pull request merged**
