### PR TITLE
[21.05] pythonPackages.certifi: does not support python2

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
backport https://github.com/NixOS/nixpkgs/pull/127561

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@NixOS/nixops-committers Merge #127453 if you care about NixOps 1.7.

### CODE REVIEW

**Comment by mweinelt** [comment]
@NixOS/nixops-committers This effectively prevents nixops from being built on 21.05.

```
❯ nom-build -A nixops
error: certifi-2021.05.30 not supported for interpreter python2.7
(use '--show-trace' to show detailed location information)
```

**Comment by devhell** [comment]
> @NixOS/nixops-committers This effectively prevents nixops from being built on 21.05.
> 
> ```
> ❯ nom-build -A nixops
> error: certifi-2021.05.30 not supported for interpreter python2.7
> (use '--show-trace' to show detailed location information)
> ```

Just ran into this. What do you think is the solution to this, other than wait until NixOps 2.0 is released?

**Comment by mweinelt** [comment]
#127453

**Comment by user-b** [comment]
Hello. I'm trying to switch from nixos 20.09 to 21.05 but I can't:

```error: certifi-2021.05.30 not supported for interpreter python2.7```

Tried removing all suspicious packages (including nixops) from configuration.nix but still I can't find which one is still using certifi. What should I do?

Thanks.

**Comment by mweinelt** [comment]
Looking through your system derivation might yield that info.

```
nix-store -q --tree $(nix-instantiate '<nixos/nixos>' -A system)
```

**Comment by jazmit** [comment]
Confirming that I had the same problem on 21.05 and could work around by removing the nixops package from the system config

**Pull request merged**
