### PR TITLE
staging-next 2022-05-18 - last for 22.05

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- important job(s): [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/172729

This is meant to be the last one for 22.05.  Merge was planned on May 22, but I'm quite confident that we won't catch that.

### CODE REVIEW

**Comment by Mindavi** [comment]
I think 5d15a099b94be16ee619053ed6bcbddefd561a19 should be dropped / reverted since gtk was updated to 4.6.4 since: https://github.com/NixOS/nixpkgs/pull/173095.

**Comment by jtojnar** [comment]
Fixed gtk4 in ac7627e62da.

**Comment by vcunat** [comment]
@dasJ: the regression amount is probably low enough now, but aarch64-linux is still missing very many builds (something like 35k now).  _Today's the originally planned moment to merge._

**Comment by vcunat** [comment]
Not a blocker IMO, but let me post it:
- [ ] `dmd` [regressed](https://hydra.nixos.org/build/177684380); maintainers: @ThomasMader, @lionello

**Comment by vcunat** [comment]
Merged really, just bad timing.

**Pull request closed without merging**
