### PR TITLE
Update imapsync to 1.678

### PR DESCRIPTION
**Pull request by robinbb**
- Built on Mac OS X
- Executed imapsync with the less-common '--authmech XOAUTH2'
- Updated Perl dependencies as required

### CODE REVIEW

**Comment by lancelotsix** [comment]
Hi,

Could each added perl package have its own commit separated from the imapsync update commit?

**Comment by robinbb** [comment]
@lancelotsix yes, I would be happy to do this, but I am unclear as to why it is preferable. Will you help me understand?

**Comment by joachifm** [comment]
@robinbb while it does make some sense to bundle addition of dependencies with an update, adding a package is considered logically distinct from updating a package. I find it very helpful to be able to easily scan the commit log to find where a package is added. Bundling adds just a bit more friction to that process and so should be avoided.

**Comment by robinbb** [comment]
@joachifm Okay, understood. I will produce a single PR with multiple commits, one package add/update per commit.

**Comment by joachifm** [comment]
You can force-push to your branch to update the PR

**Pull request closed without merging**
