### PR TITLE
[Golang] Link src root w/package path prefix in nix-shell

### PR DESCRIPTION
**Pull request by ramirez7**
###### Motivation for this change
A `buildGoPackage` derivation does not have its project root
linked correctly in `$GOPATH` within `nix-shell`. This causes
`go build/run/test` to all fail. `$PWD` is on `$GOPATH`, but the
code there is not nested under a directory matching the
import path, so imports fail.

###### Things done
Modify `buildGoPackage`'s `shellHook` to `ln` project root under the package path of directories. **I used `$PWD` for project root, but I'm unsure if there's a better way to do that.**

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ramirez7** [comment]
@matthewbauer @kamilchm Could this get merged? It's the only thing blocking me from using nixpkgs HEAD right now. I pinged you two since you interacted w/my last Go PR :)

**Review by kamilchm — APPROVED** [review]

**Comment by ramirez7** [comment]
@kamilchm I think I have to change this slightly. Instead of `$PWD` I think we should link `src` in case we're `nix-shell`info elsewhere.

**Comment by ramirez7** [comment]
@kamilchm This is good to merge 👍

**Comment by ramirez7** [comment]
This PR has drifted a lot (it got moved to `go-modules` instead of `go-packages` somehow).

Closing in favor of the up-to-date https://github.com/NixOS/nixpkgs/pull/64264

**Pull request closed without merging**
