### PR TITLE
dpkg: fix the build on Darwin

### PR DESCRIPTION
**Pull request by benley**
Borrowed some hints from homebrew's formula.

### CODE REVIEW

**Comment by benley** [comment]
build failure is unrelated to this change (it's devscripts - I'll fix that too)

**Comment by benley** [comment]
This PR now supersedes #10935 as well

**Comment by bjornfor** [comment]
@benley: I tried to merge it, but it appears the packages have been updated to newer versions in the meantime.

I think the only useful bit remaining in this PR is this part from dpkg:

```
+     (stdenv.lib.optionalString stdenv.isDarwin "--disable-linker-optimisations")
+     (stdenv.lib.optionalString stdenv.isDarwin "--disable-start-stop-daemon")
```

(Although I don't know how important that part is.)

Please have a look and either rebase/close/open new PR.

**Comment by benley** [comment]
Thanks for reminding me - I'll take another look at this PR and either update or close it.

**Comment by joachifm** [comment]
@benley ping :)

**Comment by benley** [comment]
revived! I hella forgot about this again.

**Pull request merged**
