### PR TITLE
linux_xanmod, linux_xanmod_latest: 2024-10-04

### PR DESCRIPTION
**Pull request by Shawn8901**
Regular update for xanmod kernels.

Be aware that this updates latest from a 6.10 to 6.11 kernels.

~lts testing from my side still open~

lts variant works fine on my end. 
i can not test main variant due to using zfs on all of my machines and zfs does not support 6.11 yet.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Shawn8901** [comment]
@eljamm FYI, this pushed 6.10 to 6.11, as you had seeked for the EDGE push on https://github.com/NixOS/nixpkgs/pull/342029 you might be interested in that PR.

**Comment by eljamm** [comment]
Thanks @Shawn8901. I'm curious, how do you usually test the kernel? Is there some benchmarking tool that you run or do you just use your system as usual and look for regressions?

**Comment by Shawn8901** [comment]
I am not running latest, so I can not tell for that specifically.
For the main variant I usually cross check my normal workflows / setups and run the kernel most time about a day.
I have 2 different machines (both are interactive ones) that use xanmod, for version changes I test usually on both, for Bugfix bumps I mostly just test on the machine I am using at that time.

**Review by Atemu — APPROVED** [review]
main tested and working.

Did you diff the upstream kconfig for any interesting changes?

**Comment by Atemu** [comment]
> I'm curious, how do you usually test the kernel? Is there some benchmarking tool that you run or do you just use your system as usual and look for regressions?

I usually just run it for a bit and play some games. If it works without a hitch, it's good enough. All we really need to do is verify nothing is horribly wrong.

**Comment by eljamm** [comment]
> I usually just run it for a bit and play some games.

That's what I've also been doing with the main variant and everything seems good so far.

**Review by eljamm — APPROVED** [review]

**Comment by Shawn8901** [comment]
> Did you diff the upstream kconfig for any interesting changes?

I usually check in the history of the config file if there are any separate commits (which was the case in the past, when there had been config changes). Tho I did not do a separate diff between 6.10 and 6.11 configs, but I can check in the evening, if there are other (for me unknown) changes. 

I did that in the past for a LTS variant and there had been quite some diffs between our kernel config and the xanmods, but did not yet find time to take a deeper look on each config (and why we don't activate it)For the LTS variant there are no "new" diffs.

**Pull request merged**
