### PR TITLE
nixos/gitlab-runner: add support for 'docker+machine' and 'docker-ssh+machine' executors

### LINKED ISSUE #108759: gitlab-runner module: the `dockerImage` is also mandatory for the “docker+machine” executor
https://github.com/NixOS/nixpkgs/blob/5000e5707bcd9010669e2ad7da8042dbf68f85c7/nixos/modules/services/continuous-integration/gitlab-runner.nix#L69

This test should also add the `dockerImage` option if it is set, and the executor is “docker+machine”.

### PR DESCRIPTION
**Pull request by misuzu**
Closes: https://github.com/NixOS/nixpkgs/issues/108759

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MartinPotier** [comment]
alternative PR https://github.com/NixOS/nixpkgs/pull/108762

**Review by ghost — APPROVED** [review]
This fixes a bigger class of problems than the other PR, let's keep this one.

**Comment by MartinPotier** [comment]
Tested with success!

**Comment by MartinPotier** [comment]
@misuzu should we invite another reviewer in order to get this merged?

**Pull request merged**
