### PR TITLE
tensorflow-bin_2: 2.1.0 -> 2.3.0

### PR DESCRIPTION
**Pull request by mkg20001**
###### Motivation for this change

After #95824 (tensorflow-build_2 upgrade) tensorflow-bin_2 should be upgraded aswell

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by eadwu — CHANGES_REQUESTED** [review]
Tensorflow 2.3.0 supports Python 3.8

**Comment by mkg20001** [comment]
Currently broken because of a numpy version issue, need to fix that

**Comment by mkg20001** [comment]
```
    # TODO(mihaimaruseac): numpy 1.19.0 has ABI breakage
    # https://github.com/numpy/numpy/pull/15355
```

PR seems merged, not sure but possibly fixed in the next tensorflow release

Only other option is a revert

**Comment by SuperSandro2000** [comment]
Verison in master is already newer.

**Pull request closed without merging**
