### PR TITLE
redmine: 4.1.2 -> 4.2.0

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
version bump: https://www.redmine.org/news/130

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@Mic92 thanks for https://github.com/nix-community/bundix/pull/78 :+1:

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117910` at e5e6a6bf run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/2de1a81e50486ba22b4dda262e64f23f">redmine</a></li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

bundler is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/version-management/redmine/default.nix:23:5:
```
   |
23 |     buildInputs = [ rubyEnv rubyEnv.wrappedRuby rubyEnv.bundler ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/version-management/redmine/default.nix:49:7:
```
   |
49 |       license = licenses.gpl2;
   |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/version-management/redmine/default.nix:29:5:
```
   |
29 |     buildPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/version-management/redmine/default.nix:34:5:
```
   |
34 |     installPhase = ''
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>redmine: <a href="https://termbin.com/xa5m">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/846de9090e294c73be9f9776dd1fb806/raw/index.html">pretty log </a></li>
  </ul>
</details>

**Comment by aanderse** [comment]
@Stekke are you able to update `0001-python3.patch` for `redmine 4.2.0`?

**Comment by Stekke** [comment]
@aanderse Not sure if I can add it to this pull request directly somehow, but it's here: https://github.com/Stekke/nixpkgs/commit/e3a5e3cf02106320b3c425ff4d4e68b54c6ee4b3

**Comment by aanderse** [comment]
Thank you very much!

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
</ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>redmine</li>
</ul>
</details>

**Comment by aanderse** [comment]
@Stekke don't hesitate to add yourself to the list of `redmine` maintainers, if you are interested :smile:

**Comment by Stekke** [comment]
@aanderse Thanks. I feel a bit hesitant to add myself as maintainer because my knowledge of Nix is rather limited.  I hope to read though the Nix pills / other documentation one of these days.

**Pull request merged**
