### PR TITLE
imlib2: 1.7.5 -> 1.8.1

### PR DESCRIPTION
**Pull request by nagy**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
This will need to be re-targeted at the `staging` branch.

**Comment by nagy** [comment]
So I rebase and force push onto `staging` like normally, or is there another way? Because last time I did that, it pulled in a million different people via mention and I want to avoid that.

**Comment by risicle** [comment]
I'm told the trick is documented in #166472

**Comment by nagy** [comment]
It has worked. Thank you.

**Comment by nagy** [comment]
I have updated this to now also support SVG and the HEIF image format. Both of which are recent additions to imlib2.

**Comment by jtojnar** [comment]
Changelog: https://git.enlightenment.org/legacy/imlib2.git/tree/ChangeLog?h=v1.8.1

Also mentioned is LZMA loader.

**Comment by nagy** [comment]
The LZMA Loader is already active

<details>
<summary>Build Output</summary>
<pre>
------------------------------------------------------------------------
imlib2 1.8.1
------------------------------------------------------------------------

Configuration Options Summary:

Image loaders:
 Regular image loaders
  GIF.....................: yes
  HEIF....................: yes
  JPEG....................: yes
  PNG.....................: yes
  SVG.....................: yes
  TIFF....................: yes
  WEBP....................: yes
 Decompressors
  BZIP2...................: yes
  LZMA(XZ)................: yes
  ZLIB....................: yes
 Containers
  ID3.....................: yes

Build for X11.............: yes
Use X MIT-SHM FD-passing..: yes

Use X86 MMX for speed.....: no
Use AMD64 for speed.......: yes

Use visibility hiding.....: yes

Installation path.........: /nix/store/by1584shbcr2vwmlz17mj0lraaapb8af-imlib2-1.8.1

</pre>
</details>

**Comment by risicle** [comment]
On macos 10.15:

```
  CCLD     bz2.la
ld: unknown option: -z
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:741: heif.la] Error 1
make[4]: *** Waiting for unfinished jobs....
  CCLD     lzma.la
ld: unknown option: -z
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Makefile:765: svg.la] Error 1
make[4]: Leaving directory '/private/tmp/nix-build-imlib2-1.8.1.drv-0/imlib2-1.8.1/src/modules/loaders'
make[3]: *** [Makefile:401: all-recursive] Error 1
make[3]: Leaving directory '/private/tmp/nix-build-imlib2-1.8.1.drv-0/imlib2-1.8.1/src/modules'
make[2]: *** [Makefile:401: all-recursive] Error 1
make[2]: Leaving directory '/private/tmp/nix-build-imlib2-1.8.1.drv-0/imlib2-1.8.1/src'
make[1]: *** [Makefile:523: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-imlib2-1.8.1.drv-0/imlib2-1.8.1'
make: *** [Makefile:430: all] Error 2
builder for '/nix/store/9h4qw6713796w2jk1adj4m7qqm8f0b27-imlib2-1.8.1.drv' failed with exit code 2
```

**Comment by risicle** [comment]
Think this is probably caused by the line https://git.enlightenment.org/legacy/imlib2.git/tree/src/modules/loaders/Makefile.am?h=v1.8.1#n110. Darwin clang apparently doesn't support this. So we either patch it out (not fully understanding why it's there) or disable svg on macos.

**Comment by risicle** [comment]
Aha https://git.enlightenment.org/legacy/imlib2.git/commit/src/modules/loaders/Makefile.am?h=v1.8.1&id=ffbd8bbca06f5ea608b8f78e73148515adfa8ecd

**Comment by nagy** [comment]
Should I take out the SVG and HEIF commit? I cannot test on Darwin.

**Comment by risicle** [comment]
No I'd simply disable the svg support `if stdenv.isDarwin` for now. Preferably with a comment explaining why.

We should probably notify upstream of this, but their phabricator instance https://phab.enlightenment.org/ is a bit annoying about getting an account.

**Comment by nagy** [comment]
I have updated it. Lets see if it is right now.

**Comment by risicle** [comment]
@ofborg eval

**Comment by nagy** [comment]
Ofborg seems to fail because it cannot evaluate `passthru.tests` on Darwin. I don't understand, there are no passthru tests defined.

**Comment by risicle** [comment]
#167079 Yes there are :grin: 

It's evaluating the result merged with staging.

Honestly I don't usually expect staging PRs to pass ofborg completely because of the huge volume of rebuilds that can be involved. Though it's usually worth taking a look at them for glaring errors anyway.

I do wonder if we should maybe be using `lib.availableOn` in some way for `passthru.tests`.

**Comment by risicle** [comment]
Hold on... that's not merged yet. Which error were you referring to?

**Comment by nagy** [comment]
From the Ofborg evaluation in this box down below with a click on "Details". https://github.com/NixOS/nixpkgs/pull/166452/checks?check_run_id=5893102214 . It says:

```

Unexpected error: command failed with exit code 1

Attempted: imlib2

The following builds were skipped because they don't evaluate on aarch64-darwin: imlib2.passthru.tests
```

**Comment by risicle** [comment]
Yep I think that's just staging being staging. I think the error message is a bit wrong because it really fails due to its build of many dependencies timing out.

**Comment by vcunat** [comment]
It does not build on *-darwin:
- https://hydra.nixos.org/build/175483955
- https://hydra.nixos.org/build/175573398

**Comment by vcunat** [comment]
Perhaps the workaround should've been tested (e.g. atop master) before merging.

**Comment by risicle** [comment]
Yeah teach me to assume something not tested for 24 days would stay the same.

Guessing one of the existing dependencies now pulls in `librsvg` itself. This is why we should use explicit "enable" flags when we can identify them.

**Comment by risicle** [comment]
For an added treat, upstream's git appears to have just fallen off the face of the earth too.

**Comment by nagy** [comment]
Version 1.9.0 is out already, which may address the issue. I see some mentionings of the svg loader in the changelog. I can make a PR for that as well.

https://sourceforge.net/projects/enlightenment/files/imlib2-src/1.9.0/

**Comment by risicle** [comment]
I've already tried this and it doesn't help.

**Comment by risicle** [comment]
Hold on - I think this may be the HEIF support too...

**Comment by risicle** [comment]
Think I've got this fixed in #171947

@nagy by all means create a 1.9.0 PR though, got to update sometime

**Pull request merged**
