### PR TITLE
linuxPackages.mwprocapture: 1.3.0.4236 -> 1.3.0.4328

### LINKED ISSUE #221187: Build failure: mwprocapture
### Steps To Reproduce

Version V1.3.0.4236 of mwprocapture (the Linux driver for the Magewell Pro Capture family) FTBFS when building against Linux 6.1 or newer.

1. Add `mwProCapture.enable = true;` to `hardware-configuration.nix`
2. Add `boot.kernelPackages = pkgs.linuxPackages_latest;` to `hardware-configuration.nix`
3. `sudo nixos-rebuild switch`

### Build log

```
error: builder for '/nix/store/hc35022db8fd3wg8hyd9y31lmwnal1ph-mwprocapture-1.3.0.4236-6.2.3.drv' failed with exit code 2;
       last 10 log lines:
       >   276 |             if (wChannelValid & 0x02) {
       >       |                ^
       > /build/ProCaptureForLinux_4236/src/sources/avstream/alsa.c:282:9: note: here
       >   282 |         case 1:
       >       |         ^~~~
       > cc1: some warnings being treated as errors
       > make[2]: *** [/nix/store/ma356rq8bjkl6y3dbx12qhnflv1f485k-linux-6.2.3-dev/lib/modules/6.2.3/source/scripts/Makefile.build:252: /build/ProCaptureForLinux_4236/src/sources/avstream/alsa.o] Error 1
       > make[1]: *** [/nix/store/ma356rq8bjkl6y3dbx12qhnflv1f485k-linux-6.2.3-dev/lib/modules/6.2.3/source/Makefile:2021: /build/ProCaptureForLinux_4236/src] Error 2
       > make[1]: Leaving directory '/nix/store/ma356rq8bjkl6y3dbx12qhnflv1f485k-linux-6.2.3-dev/lib/modules/6.2.3/build'
       > make: *** [Makefile:33: all] Error 2
       For full logs, run 'nix log /nix/store/hc35022db8fd3wg8hyd9y31lmwnal1ph-mwprocapture-1.3.0.4236-6.2.3.drv'.
error: 1 dependencies of derivation '/nix/store/k9jfg5rc1znalqyf9gmf73qnq4fda91r-etc-nixos.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fqd3ri0i95snvqmzwrrg6wad6f2giq1a-kernel-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8pap2plygkdhgcg8lsdzaf3fx0jwh0yv-linux-6.2.3-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lnqb6ymr9m17rpz8l5w4l7lhh0kmz32b-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/npjlnky14m5p6y2vn63q9xvhbp3g8ma9-nixos-system-designare-23.05.20230310.0c4800d.drv' failed to build
```

### Additional context

Magewell have released V1.3.0.4328 of the driver to address this issue. I am working on a pull request for nixpkgs.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.3, NixOS, 23.05 (Stoat), 23.05.20230310.0c4800d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by flexiondotorg**
Version V1.3.0.4236 of mwprocapture (the Linux driver for the Magewell Pro Capture family) FTBFS when building against Linux 6.1 or newer.
    
This patch bumps the driver version to 1.3.0.4328 that Magewell published to address this issue. The 1.3.0.4328 release notes state:
    
> Fix problem: driver installation may fail on an operating system with kernel version 6.1 or 6.2.
    
pci.patch has also been dropped as that fix is now applied upstream. Tested using a Magewell Pro Capture Dual HDMI (11080). This fixes #221187

```
total: 2
device path     firmware ver    hardware ver    driver ver      alsa name       device name                   
/dev/video2     1.31            B               1.3.4328        hw:4,0          00:00 Pro Capture Dual HDMI   
/dev/video3     1.31            B               1.3.4328        hw:5,0          00:01 Pro Capture Dual HDMI
```

### CODE REVIEW

**Comment by bobby285271** [comment]
We can probably remove

https://github.com/NixOS/nixpkgs/blob/3da93fd5821fa0c2b76fd636c5f77f8280dbfb76/pkgs/os-specific/linux/mwprocapture/default.nix#L62

/cc  #182590 @superherointj

**Comment by superherointj** [comment]
> We can probably remove
> 
> https://github.com/NixOS/nixpkgs/blob/3da93fd5821fa0c2b76fd636c5f77f8280dbfb76/pkgs/os-specific/linux/mwprocapture/default.nix#L62
> 
> also /cc #182590 @superherointj

Certify to test before removing. Just so doesn't show up as false positives in downstream builds.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 221209` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.mwprocapture</li>
    <li>linuxKernel.packages.linux_5_4_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_6_1.mwprocapture</li>
    <li>linuxKernel.packages.linux_6_1_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_6_2.mwprocapture</li>
    <li>linuxKernel.packages.linux_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_latest_libre.mwprocapture</li>
    <li>linuxKernel.packages.linux_libre.mwprocapture</li>
    <li>linuxKernel.packages.linux_lqx.mwprocapture</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.mwprocapture</li>
    <li>linuxKernel.packages.linux_xanmod.mwprocapture</li>
    <li>linuxKernel.packages.linux_xanmod_latest.mwprocapture</li>
    <li>linuxKernel.packages.linux_xanmod_stable.mwprocapture</li>
    <li>linuxKernel.packages.linux_zen.mwprocapture</li>
    <li>linuxPackages-libre.mwprocapture</li>
    <li>linuxPackages.mwprocapture</li>
    <li>linuxPackages_5_4_hardened.mwprocapture</li>
    <li>linuxPackages_6_1_hardened.mwprocapture</li>
    <li>linuxPackages_hardened.mwprocapture</li>
    <li>linuxPackages_hardkernel_latest.mwprocapture</li>
    <li>linuxPackages_latest-libre.mwprocapture</li>
    <li>linuxPackages_latest.mwprocapture</li>
    <li>linuxPackages_lqx.mwprocapture</li>
    <li>linuxPackages_testing_bcachefs.mwprocapture</li>
    <li>linuxPackages_xanmod.mwprocapture</li>
    <li>linuxPackages_xanmod_latest.mwprocapture</li>
    <li>linuxPackages_xanmod_stable.mwprocapture</li>
    <li>linuxPackages_zen.mwprocapture</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.mwprocapture</li>
    <li>linuxPackages_4_14_hardened.mwprocapture (linuxKernel.packages.linux_4_14_hardened.mwprocapture)</li>
    <li>linuxKernel.packages.linux_4_19.mwprocapture</li>
    <li>linuxPackages_4_19_hardened.mwprocapture (linuxKernel.packages.linux_4_19_hardened.mwprocapture)</li>
    <li>linuxKernel.packages.linux_5_10.mwprocapture</li>
    <li>linuxPackages_5_10_hardened.mwprocapture (linuxKernel.packages.linux_5_10_hardened.mwprocapture)</li>
    <li>linuxKernel.packages.linux_5_15.mwprocapture</li>
    <li>linuxPackages_5_15_hardened.mwprocapture (linuxKernel.packages.linux_5_15_hardened.mwprocapture)</li>
    <li>linuxKernel.packages.linux_5_4.mwprocapture</li>
  </ul>
</details>

**Comment by superherointj** [comment]
> This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:
> 
> https://discourse.nixos.org/t/prs-ready-for-review/3032/1957

@flexiondotorg (Wimpy, I suppose) Why are you asking for more reviews? If we have just reviewed your PR and are waiting for you to make  changes, so we can proceed.

**Comment by superherointj** [comment]
Please, remove:
> broken = kernel.kernelAtLeast "5.16";
And build with `nixpkgs-review` (`nix-shell -p nixpkgs-review`), such as:
> nixpkgs-review pr --post-result 221209

**Comment by flexiondotorg** [comment]
> We can also remove
> 
> https://github.com/NixOS/nixpkgs/blob/3da93fd5821fa0c2b76fd636c5f77f8280dbfb76/pkgs/os-specific/linux/mwprocapture/default.nix#L62

Done :+1:

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 221209` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.mwprocapture</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.mwprocapture</li>
    <li>linuxKernel.packages.linux_4_14_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_4_19.mwprocapture</li>
    <li>linuxKernel.packages.linux_4_19_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_5_10.mwprocapture</li>
    <li>linuxKernel.packages.linux_5_10_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_5_15.mwprocapture</li>
    <li>linuxKernel.packages.linux_5_15_hardened.mwprocapture</li>
    <li>linuxKernel.packages.linux_5_4.mwprocapture</li>
    <li>linuxKernel.packages.linux_6_1.mwprocapture</li>
    <li>linuxKernel.packages.linux_hardened.mwprocapture (linuxKernel.packages.linux_6_1_hardened.mwprocapture)</li>
    <li>linuxKernel.packages.linux_6_2.mwprocapture</li>
    <li>linuxKernel.packages.linux_latest_libre.mwprocapture</li>
    <li>linuxKernel.packages.linux_libre.mwprocapture</li>
    <li>linuxKernel.packages.linux_lqx.mwprocapture</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.mwprocapture</li>
    <li>linuxKernel.packages.linux_xanmod.mwprocapture</li>
    <li>linuxKernel.packages.linux_xanmod_latest.mwprocapture (linuxKernel.packages.linux_xanmod_stable.mwprocapture)</li>
    <li>linuxKernel.packages.linux_zen.mwprocapture</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]
Congratulations for your first PR. Will be merged shortly after CI is done.

**Comment by flexiondotorg** [comment]
> Congratulations for your first PR. Will be merged shortly after CI is done.

Thanks for the help :bow:

**Pull request merged**
