### PR TITLE
electron-mail: init at 4.12.2

### PR DESCRIPTION
**Pull request by Princemachiavelli**
https://github.com/vladimiry/ElectronMail

Tested on x86_64 as that is the only supported architecture by the prebuilt upstream packages. Eventually the package could be updated to build the electron app. 

I tested it on sway desktop environment with 'waybar' as my desktop status bar. This is notable as it seems to be one of the few status bars that has issues displaying some tray icons which is an issue as this package defaults to closing & opening minimized. I think this is a very small edge case that user's can manually fix by editing ~/.config/electron-mail/config.json - I mostly just want to document this issue. 

A future update could expose some settings in config.js & hopefully allow setting the master key. It could change the default behavior to not minimize to avoid the issue mentioned above.

Since this is a new package it should be backported to stable.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please remove the merge commit from the PR.

The init commit should be named ``electron-mail: init at 4.12.2``.

and it would be nice if you have some other contact than GitHub.

**Review by ethancedwards8 — CHANGES_REQUESTED** [review]
@Princemachiavelli the commit should only be `electron-mail: init at 4.12.2`

**Comment by ethancedwards8** [comment]
Result of `nixpkgs-review pr 126523` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>electron-mail</li>
  </ul>
</details>

**Comment by Princemachiavelli** [comment]
OK, everything should be fixed. Thanks for the feedback.

**Review by ethancedwards8 — COMMENTED** [review]
LGTM

**Pull request merged**
