### PR TITLE
kak-lsp: init at 6.0.1

### PR DESCRIPTION
**Pull request by swdunlop**
###### Motivation for this change

enables language server protocol support for Kakoune

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by hedning** [comment]
@GrahamcOfBorg build kak-lsp

**Comment by Infinisil** [comment]
- Can you update the PR with the latest version 6.1.0?
- Use rebasing for fixing conflicts instead of merging, no merge commits should be in the PR
- What's a saml2aws update doing there? Should probably be moved to different PR unless it's relevant for this one

**Comment by aanderse** [comment]
@swdunlop any motivation to continue with this PR?

**Comment by eraserhd** [comment]
This PR is out of date, as we have [kak-lsp 7.0.0](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/kak-lsp/default.nix) merged already.  Someone should close it.

**Comment by aanderse** [comment]
@eraserhd thanks!

**Pull request closed without merging**
