### PR TITLE
opentabletdriver: 0.6.0.4 -> 0.6.1

### LINKED ISSUE #238856: Update request: opentabletdriver 0.6.0.4 → 0.6.1
- Package name: opentabletdriver
- Latest released version: 0.6.1

- Current version on the unstable channel: 0.6.0.4
- Current version on the stable/release channel: 0.6.0.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@thiagokokada

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

Closes: https://github.com/NixOS/nixpkgs/issues/238856

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
@ofborg test opentabletdriver

**Comment by thiagokokada** [comment]
CC @loco-choco for testing.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 239041` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>opentabletdriver</li>
  </ul>
</details>

**Comment by loco-choco** [comment]
> CC @loco-choco for testing.

I was able to build and check that the version being ran is 0.6.1. I still need to do furthers testing with my drawing tablet, but other then that everything looks good to me.

**Comment by loco-choco** [comment]
I now just tested with my Huion HS611 and everything is working as expected, from the driver to the gui.

**Pull request merged**
