### PR TITLE
Add release-notes for unstable revision

### PR DESCRIPTION
**Pull request by abbradar**
This is a followup of a discussion with @wmertens [1] . The idea is to have an "unstable" release notes, which would be copied into new file, cleaned up and started over on each release. Meanwhile one would have where to add notes, so we won't need to write everything from scratch right before a release. I haven't looked into documentation before that; it's possible we've had something like this before somewhere and I've just missed it.

I've also added some first notes to it regarding renames (and new semantics) of some packages. I have a question regarding them -- should I leave old names for compatibility at all, and how should I mark them as "deprecated" if so? For NixOS we have `rename.nix`, but there's no mechanism like this in plain `nixpkgs` AFAIK. For now I've included here a patch to remove old aliases at all -- as one course of action.

A written policy regarding this would be very nice indeed.

1: https://github.com/abbradar/nixpkgs/commit/627f8178b8b779b639a64716dbe13c7a64ad56f0#commitcomment-9611181

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @edolstra @iElectric

**Comment by wmertens** [comment]
:+1:

**Comment by iElectric** [comment]
Is @svanderburg aware of the stream chroot going away?

**Comment by wmertens** [comment]
Merging this as we need more people to add release notes for their changes and is a low impact change. @iElectric the steam chroot isn't gone, it's under steamOriginal now.

**Comment by iElectric** [comment]
:+1:

**Comment by abbradar** [comment]
@wmertens @iElectric not quite like this, the old `steamChroot` with its old semantics is indeed gone (`steamOriginal` is an original package from Valve, another bad name from me), however, all the old infrastructure is in place. This benefits end users a lot (just install and run `steam` as user instead of all `-chrootenv` root-needing scripts), but if one wants to have an old behavior, the actual change is tiny: https://github.com/NixOS/nixpkgs/commit/238fe730b94ee163adfd5133870f30e34e1fc5e6

**Comment by iElectric** [comment]
`steamChroot` is now `steam` afaik

**Comment by abbradar** [comment]
Yes, that's right.

**Comment by abbradar** [comment]
(But also with changed semantics -- I was talking about them when said "gone")

**Pull request merged**
