### PR TITLE
nx: init at 1.0.0

### PR DESCRIPTION
**Pull request by mchalunderscore**
###### Description of changes

- Initialized `nx` at version 1.0.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zendo** [comment]
```
error: builder for '/nix/store/zj2hwwzdlm4wgdqy169f71ss7ldkwbqx-python3.10-randomname-0.1.5.drv' failed with exit code 2;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'setuptools'
       > 
       > 
       For full logs, run 'nix log /nix/store/zj2hwwzdlm4wgdqy169f71ss7ldkwbqx-python3.10-randomname-0.1.5.drv'.
error: 1 dependencies of derivation '/nix/store/q92k9gh82vk303wcikw6vcjsd8yb63lp-python3.10-nx-1.0.0.drv' failed to build
```

**Comment by not-my-segfault** [comment]
> ```
> error: builder for '/nix/store/zj2hwwzdlm4wgdqy169f71ss7ldkwbqx-python3.10-randomname-0.1.5.drv' failed with exit code 2;
>        last 10 log lines:
>        >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>        >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>        >   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
>        >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>        >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>        >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>        >   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
>        > ModuleNotFoundError: No module named 'setuptools'
>        > 
>        > 
>        For full logs, run 'nix log /nix/store/zj2hwwzdlm4wgdqy169f71ss7ldkwbqx-python3.10-randomname-0.1.5.drv'.
> error: 1 dependencies of derivation '/nix/store/q92k9gh82vk303wcikw6vcjsd8yb63lp-python3.10-nx-1.0.0.drv' failed to build
> ```

That's... strange? That's the behaviour I've seen with Wheels disabled, which is why I've set preferWheels in the derivation. It's built fine on my PC and OfBorg seems to be happy too... 🤔

**Comment by not-my-segfault** [comment]
> > ```
> > error: builder for '/nix/store/zj2hwwzdlm4wgdqy169f71ss7ldkwbqx-python3.10-randomname-0.1.5.drv' failed with exit code 2;
> >        last 10 log lines:
> >        >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
> >        >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
> >        >   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
> >        >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> >        >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
> >        >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
> >        >   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
> >        > ModuleNotFoundError: No module named 'setuptools'
> >        > 
> >        > 
> >        For full logs, run 'nix log /nix/store/zj2hwwzdlm4wgdqy169f71ss7ldkwbqx-python3.10-randomname-0.1.5.drv'.
> > error: 1 dependencies of derivation '/nix/store/q92k9gh82vk303wcikw6vcjsd8yb63lp-python3.10-nx-1.0.0.drv' failed to build
> > ```
> 
> That's... strange? That's the behaviour I've seen with Wheels disabled, which is why I've set preferWheels in the derivation. It's built fine on my PC and OfBorg seems to be happy too... 🤔

Also to note - this has been tested on both standard NixOS aarch64 and nix-on-droid

**Comment by RaitoBezarius** [comment]
> Note that there is another [nx](https://nx.dev/) that is reasonably popular, especially compared to the nx in this PR which is only a week old. May cause confusion.

Indeed, I knew about this one only.

Could we get a namespacing of the form `nix-nx` ? And people can alias `nx` if they wish for.

**Comment by necrophcodr** [comment]
@not-my-segfault is this still something you're interested in getting along? There may yet be work to be done, but if not we can just close the PR.

**Comment by not-my-segfault** [comment]
This is fine to be closed for now. I might re-submit sometime into the future

**Pull request closed without merging**
