### PR TITLE
pulumi-bin: 3.3.1 -> 3.4.0

### PR DESCRIPTION
**Pull request by t0yv0**
###### Motivation for this change
Upgrade Pulumi to 3.4.0.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 126378` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Review by austinbutler — APPROVED** [review]

**Review by austinbutler — CHANGES_REQUESTED** [review]
@t0yv0 I think the commit also should match the format that you have in the PR title, can you fix that?

**Comment by t0yv0** [comment]
@austinbutler in case you did not see my thumbs-up - I think it's done now. Thanks for reviewing!

**Review by austinbutler — APPROVED** [review]
Nope, no notifications for reacts. LGTM now.

**Pull request merged**
