### PR TITLE
dotnet: fix --self-contained builds

### PR DESCRIPTION
**Pull request by corngood**
## Description of changes

Builds using `--self-contained` (but not `PublishSingleFile`) would fail with

> Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.

This was due to `singlefilehost` being patched, but not `apphost`.

This PR also adds a test for this build configuration, and sets `LANG` in all tests, to force ICU to be loaded.

FYI @NixOS/dotnet 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
marked draft because this causes errors like:

```
setting RPATH to: /nix/store/c2yb135iv4maadia5f760b3xhbh6jh61-gcc-13.2.0-lib/lib:/nix/store/a2fqd5k8ymb2cadb5awp5b90a5m8acln-gcc-13.2.0-libgcc/lib
auto-patchelf: 4 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency libssl.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
error: auto-patchelf could not satisfy dependency libgssapi_krb5.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
error: auto-patchelf could not satisfy dependency libicui18n.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
error: auto-patchelf could not satisfy dependency libicuuc.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
auto-patchelf failed to find all the required dependencies.
Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
error: builder for '/nix/store/yy8jvn06xzwb457jn0kxbr6vg92xwwyv-inklecate-1.1.1.drv' failed with exit code 1;
       last 10 log lines:
       >     libstdc++.so.6 -> found: /nix/store/c2yb135iv4maadia5f760b3xhbh6jh61-gcc-13.2.0-lib/lib
       >     libgcc_s.so.1 -> found: /nix/store/a2fqd5k8ymb2cadb5awp5b90a5m8acln-gcc-13.2.0-libgcc/lib
       > setting RPATH to: /nix/store/c2yb135iv4maadia5f760b3xhbh6jh61-gcc-13.2.0-lib/lib:/nix/store/a2fqd5k8ymb2cadb5awp5b90a5m8acln-gcc-13.2.0-libgcc/lib
       > auto-patchelf: 4 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libssl.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
       > error: auto-patchelf could not satisfy dependency libgssapi_krb5.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
       > error: auto-patchelf could not satisfy dependency libicui18n.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
       > error: auto-patchelf could not satisfy dependency libicuuc.so wanted by /nix/store/yy4ki3gc6by3l7bqmv8080j2nzwnfnz8-inklecate-1.1.1/lib/inklecate/inklecate
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       For full logs, run 'nix log /nix/store/yy8jvn06xzwb457jn0kxbr6vg92xwwyv-inklecate-1.1.1.drv'.
```

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 304780` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>alttpr-opentracker</li>
    <li>avalonia-ilspy</li>
    <li>galaxy-buds-client</li>
    <li>github-runner</li>
    <li>inklecate</li>
    <li>mqttmultimeter</li>
    <li>wasabibackend</li>
  </ul>
</details>
<details>
  <summary>125 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>am2rlauncher</li>
    <li>audiobookshelf</li>
    <li>azure-functions-core-tools</li>
    <li>bicep</li>
    <li>bililiverecorder</li>
    <li>boogie (dotnetPackages.Boogie)</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>cavalier</li>
    <li>celeste64</li>
    <li>certdump</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore (dotnet-aspnetcore_6 ,dotnetCorePackages.aspnetcore_6_0)</li>
    <li>dotnet-aspnetcore_7 (dotnetCorePackages.aspnetcore_7_0)</li>
    <li>dotnet-aspnetcore_8 (dotnetCorePackages.aspnetcore_8_0)</li>
    <li>dotnet-outdated</li>
    <li>dotnet-runtime (dotnet-runtime_6 ,dotnetCorePackages.runtime_6_0)</li>
    <li>dotnet-runtime_7 (dotnetCorePackages.runtime_7_0)</li>
    <li>dotnet-runtime_8 (dotnetCorePackages.runtime_8_0)</li>
    <li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0 ,dotnetCorePackages.sdk_6_0_4xx)</li>
    <li>dotnet-sdk_7 (dotnetCorePackages.sdk_7_0 ,dotnetCorePackages.sdk_7_0_4xx)</li>
    <li>dotnet-sdk_8 (dotnetCorePackages.sdk_8_0 ,dotnetCorePackages.sdk_8_0_2xx)</li>
    <li>dotnetCorePackages.aspnetcore_9_0</li>
    <li>dotnetCorePackages.dotnet_8.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_8.runtime</li>
    <li>dotnetCorePackages.dotnet_8.sdk</li>
    <li>dotnetCorePackages.dotnet_8.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_8.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_8.vmr</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.runtime_9_0</li>
    <li>dotnetCorePackages.sdk_6_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_3xx</li>
    <li>dotnetCorePackages.sdk_8_0_1xx</li>
    <li>dotnetCorePackages.sdk_9_0 (dotnetCorePackages.sdk_9_0_1xx)</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>garnet</li>
    <li>git-credential-manager</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>ilspycmd</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>kavita</li>
    <li>knossosnet</li>
    <li>libation</li>
    <li>lidarr</li>
    <li>lubelogger</li>
    <li>marksman</li>
    <li>msbuild</li>
    <li>naps2</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>networkminer</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>pablodraw</li>
    <li>parabolic</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>ps3-disc-dumper</li>
    <li>pupdate</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>radarr</li>
    <li>readarr</li>
    <li>roslyn</li>
    <li>roslyn-ls</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>sonarr</li>
    <li>space-station-14-launcher</li>
    <li>technitium-dns-server</li>
    <li>tests.dotnet.project-references</li>
    <li>tests.writers.simple.fsharp</li>
    <li>tests.writers.simple.fsharpNoNugetDeps</li>
    <li>tone</li>
    <li>torrentstream</li>
    <li>vintagestory</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 304780` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>129 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>am2rlauncher</li>
    <li>audiobookshelf</li>
    <li>avalonia-ilspy</li>
    <li>azure-functions-core-tools</li>
    <li>bicep</li>
    <li>bililiverecorder</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>cavalier</li>
    <li>celeste64</li>
    <li>certdump</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore</li>
    <li>dotnet-aspnetcore_7</li>
    <li>dotnet-aspnetcore_8</li>
    <li>dotnet-outdated</li>
    <li>dotnet-runtime</li>
    <li>dotnet-runtime_7</li>
    <li>dotnet-runtime_8</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk_7</li>
    <li>dotnet-sdk_8</li>
    <li>dotnetCorePackages.aspnetcore_9_0</li>
    <li>dotnetCorePackages.dotnet_8.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_8.runtime</li>
    <li>dotnetCorePackages.dotnet_8.sdk</li>
    <li>dotnetCorePackages.dotnet_8.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_8.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_8.vmr</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>dotnetCorePackages.runtime_9_0</li>
    <li>dotnetCorePackages.sdk_6_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_1xx</li>
    <li>dotnetCorePackages.sdk_7_0_3xx</li>
    <li>dotnetCorePackages.sdk_8_0_1xx</li>
    <li>dotnetCorePackages.sdk_9_0</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>garnet</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>ilspycmd</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>kavita</li>
    <li>knossosnet</li>
    <li>libation</li>
    <li>lidarr</li>
    <li>lubelogger</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>naps2</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>networkminer</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>pablodraw</li>
    <li>parabolic</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>ps3-disc-dumper</li>
    <li>pupdate</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>radarr</li>
    <li>readarr</li>
    <li>roslyn</li>
    <li>roslyn-ls</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>sonarr</li>
    <li>space-station-14-launcher</li>
    <li>technitium-dns-server</li>
    <li>tone</li>
    <li>torrentstream</li>
    <li>vintagestory</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Comment by corngood** [comment]
I've dealt with the `auto-patchelf: 4 dependencies could not be satisfied` errors by removing `autoPatchelfHook` from the packages.  I suspect it was meant to solve the same problem, but since only `singlefilehost` and not `apphost` had the dependencies injected, it wasn't actually adding anything to RPATH.

**Review by GGG-KILLER — APPROVED** [review]

**Pull request merged**
