### PR TITLE
Vim plugins update

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 268485` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>109 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.efmls-configs-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.nabla-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg (vimPlugins.neotest)</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-pqf</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-parsers.apex</li>
    <li>vimPlugins.nvim-treesitter-parsers.c</li>
    <li>vimPlugins.nvim-treesitter-parsers.cpp</li>
    <li>vimPlugins.nvim-treesitter-parsers.cuda</li>
    <li>vimPlugins.nvim-treesitter-parsers.glsl</li>
    <li>vimPlugins.nvim-treesitter-parsers.hcl</li>
    <li>vimPlugins.nvim-treesitter-parsers.linkerscript</li>
    <li>vimPlugins.nvim-treesitter-parsers.liquidsoap</li>
    <li>vimPlugins.nvim-treesitter-parsers.php</li>
    <li>vimPlugins.nvim-treesitter-parsers.purescript</li>
    <li>vimPlugins.nvim-treesitter-parsers.python</li>
    <li>vimPlugins.nvim-treesitter-parsers.rust</li>
    <li>vimPlugins.nvim-treesitter-parsers.soql</li>
    <li>vimPlugins.nvim-treesitter-parsers.sosl</li>
    <li>vimPlugins.nvim-treesitter-parsers.sql</li>
    <li>vimPlugins.nvim-treesitter-parsers.ssh_config</li>
    <li>vimPlugins.nvim-treesitter-parsers.t32</li>
    <li>vimPlugins.nvim-treesitter-parsers.templ</li>
    <li>vimPlugins.nvim-treesitter-parsers.terraform</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.nvim-ts-context-commentstring</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.quarto-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.sideways-vim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.substitute-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-alias</li>
    <li>vimPlugins.vim-dadbod-completion</li>
    <li>vimPlugins.vim-just</li>
    <li>vimPlugins.vim-wakatime</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
result of `nixpkgs-review pr 268485` run on aarch64-darwin [1](https://github.com/mic92/nixpkgs-review)
<details>
  <summary>109 packages built:</summary>
  <ul>
    <li>vimplugins.chatgpt-nvim</li>
    <li>vimplugins.schemastore-nvim</li>
    <li>vimplugins.aerial-nvim</li>
    <li>vimplugins.ale</li>
    <li>vimplugins.alpha-nvim</li>
    <li>vimplugins.barbecue-nvim</li>
    <li>vimplugins.catppuccin-nvim</li>
    <li>vimplugins.cmp-dap</li>
    <li>vimplugins.cmp-fuzzy-buffer</li>
    <li>vimplugins.cmp-fuzzy-path</li>
    <li>vimplugins.command-t</li>
    <li>vimplugins.completion-treesitter</li>
    <li>vimplugins.conform-nvim</li>
    <li>vimplugins.crates-nvim</li>
    <li>vimplugins.dropbar-nvim</li>
    <li>vimplugins.efmls-configs-nvim</li>
    <li>vimplugins.feline-nvim</li>
    <li>vimplugins.fuzzy-nvim</li>
    <li>vimplugins.fzf-lua</li>
    <li>vimplugins.gitsigns-nvim</li>
    <li>vimplugins.hardtime-nvim</li>
    <li>vimplugins.haskell-tools-nvim</li>
    <li>vimplugins.hover-nvim</li>
    <li>vimplugins.image-nvim</li>
    <li>vimplugins.lazy-lsp-nvim</li>
    <li>vimplugins.lean-nvim</li>
    <li>vimplugins.leap-ast-nvim</li>
    <li>vimplugins.lsp_signature-nvim</li>
    <li>vimplugins.lspsaga-nvim</li>
    <li>vimplugins.mason-lspconfig-nvim</li>
    <li>vimplugins.material-nvim</li>
    <li>vimplugins.mini-nvim</li>
    <li>vimplugins.molten-nvim</li>
    <li>vimplugins.multicursors-nvim</li>
    <li>vimplugins.nabla-nvim</li>
    <li>vimplugins.neo-tree-nvim</li>
    <li>vimplugins.neodev-nvim</li>
    <li>vimplugins.neogit</li>
    <li>vimplugins.neorg (vimplugins.neotest)</li>
    <li>vimplugins.neotest-haskell</li>
    <li>vimplugins.none-ls-nvim</li>
    <li>vimplugins.nvim-dap</li>
    <li>vimplugins.nvim-dap-python</li>
    <li>vimplugins.nvim-lint</li>
    <li>vimplugins.nvim-lspconfig</li>
    <li>vimplugins.nvim-metals</li>
    <li>vimplugins.nvim-navbuddy</li>
    <li>vimplugins.nvim-navic</li>
    <li>vimplugins.nvim-pqf</li>
    <li>vimplugins.nvim-scrollview</li>
    <li>vimplugins.nvim-tree-lua</li>
    <li>vimplugins.nvim-treesitter</li>
    <li>vimplugins.nvim-treesitter-context</li>
    <li>vimplugins.nvim-treesitter-parsers.apex</li>
    <li>vimplugins.nvim-treesitter-parsers.c</li>
    <li>vimplugins.nvim-treesitter-parsers.cpp</li>
    <li>vimplugins.nvim-treesitter-parsers.cuda</li>
    <li>vimplugins.nvim-treesitter-parsers.glsl</li>
    <li>vimplugins.nvim-treesitter-parsers.hcl</li>
    <li>vimplugins.nvim-treesitter-parsers.linkerscript</li>
    <li>vimplugins.nvim-treesitter-parsers.liquidsoap</li>
    <li>vimplugins.nvim-treesitter-parsers.php</li>
    <li>vimplugins.nvim-treesitter-parsers.purescript</li>
    <li>vimplugins.nvim-treesitter-parsers.python</li>
    <li>vimplugins.nvim-treesitter-parsers.rust</li>
    <li>vimplugins.nvim-treesitter-parsers.soql</li>
    <li>vimplugins.nvim-treesitter-parsers.sosl</li>
    <li>vimplugins.nvim-treesitter-parsers.sql</li>
    <li>vimplugins.nvim-treesitter-parsers.ssh_config</li>
    <li>vimplugins.nvim-treesitter-parsers.t32</li>
    <li>vimplugins.nvim-treesitter-parsers.templ</li>
    <li>vimplugins.nvim-treesitter-parsers.terraform</li>
    <li>vimplugins.nvim-treesitter-parsers.v</li>
    <li>vimplugins.nvim-treesitter-parsers.wing</li>
    <li>vimplugins.nvim-ts-context-commentstring</li>
    <li>vimplugins.nvim-web-devicons</li>
    <li>vimplugins.octo-nvim</li>
    <li>vimplugins.onedarkpro-nvim</li>
    <li>vimplugins.orgmode</li>
    <li>vimplugins.playground</li>
    <li>vimplugins.quarto-nvim</li>
    <li>vimplugins.rainbow-delimiters-nvim</li>
    <li>vimplugins.refactoring-nvim</li>
    <li>vimplugins.rest-nvim</li>
    <li>vimplugins.rustaceanvim</li>
    <li>vimplugins.sideways-vim</li>
    <li>vimplugins.snap</li>
    <li>vimplugins.splitjoin-vim</li>
    <li>vimplugins.ssr</li>
    <li>vimplugins.substitute-nvim</li>
    <li>vimplugins.telescope-cheat-nvim</li>
    <li>vimplugins.telescope-file-browser-nvim</li>
    <li>vimplugins.telescope-frecency-nvim</li>
    <li>vimplugins.telescope-fzf-native-nvim</li>
    <li>vimplugins.telescope-fzf-writer-nvim</li>
    <li>vimplugins.telescope-fzy-native-nvim</li>
    <li>vimplugins.telescope-media-files-nvim</li>
    <li>vimplugins.telescope-nvim</li>
    <li>vimplugins.telescope-symbols-nvim</li>
    <li>vimplugins.telescope-undo-nvim</li>
    <li>vimplugins.telescope-z-nvim</li>
    <li>vimplugins.telescope-zoxide</li>
    <li>vimplugins.text-case-nvim</li>
    <li>vimplugins.typescript-tools-nvim</li>
    <li>vimplugins.unison</li>
    <li>vimplugins.vim-alias</li>
    <li>vimplugins.vim-dadbod-completion</li>
    <li>vimplugins.vim-just</li>
    <li>vimplugins.vim-wakatime</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 268485` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>103 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.efmls-configs-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.nabla-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg (vimPlugins.neotest)</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-pqf</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-parsers.apex</li>
    <li>vimPlugins.nvim-treesitter-parsers.c</li>
    <li>vimPlugins.nvim-treesitter-parsers.cpp</li>
    <li>vimPlugins.nvim-treesitter-parsers.cuda</li>
    <li>vimPlugins.nvim-treesitter-parsers.glsl</li>
    <li>vimPlugins.nvim-treesitter-parsers.hcl</li>
    <li>vimPlugins.nvim-treesitter-parsers.linkerscript</li>
    <li>vimPlugins.nvim-treesitter-parsers.liquidsoap</li>
    <li>vimPlugins.nvim-treesitter-parsers.php</li>
    <li>vimPlugins.nvim-treesitter-parsers.purescript</li>
    <li>vimPlugins.nvim-treesitter-parsers.python</li>
    <li>vimPlugins.nvim-treesitter-parsers.rust</li>
    <li>vimPlugins.nvim-treesitter-parsers.soql</li>
    <li>vimPlugins.nvim-treesitter-parsers.sosl</li>
    <li>vimPlugins.nvim-treesitter-parsers.sql</li>
    <li>vimPlugins.nvim-treesitter-parsers.ssh_config</li>
    <li>vimPlugins.nvim-treesitter-parsers.t32</li>
    <li>vimPlugins.nvim-treesitter-parsers.templ</li>
    <li>vimPlugins.nvim-treesitter-parsers.terraform</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.nvim-ts-context-commentstring</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.quarto-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.sideways-vim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.substitute-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-alias</li>
    <li>vimPlugins.vim-dadbod-completion</li>
    <li>vimPlugins.vim-just</li>
    <li>vimPlugins.vim-wakatime</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 268485 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>109 packages built:</summary>  <ul>    <li>vimPlugins.ChatGPT-nvim</li>    <li>vimPlugins.SchemaStore-nvim</li>    <li>vimPlugins.aerial-nvim</li>    <li>vimPlugins.ale</li>    <li>vimPlugins.alpha-nvim</li>    <li>vimPlugins.barbecue-nvim</li>    <li>vimPlugins.catppuccin-nvim</li>    <li>vimPlugins.cmp-dap</li>    <li>vimPlugins.cmp-fuzzy-buffer</li>    <li>vimPlugins.cmp-fuzzy-path</li>    <li>vimPlugins.command-t</li>    <li>vimPlugins.completion-treesitter</li>    <li>vimPlugins.conform-nvim</li>    <li>vimPlugins.crates-nvim</li>    <li>vimPlugins.dropbar-nvim</li>    <li>vimPlugins.efmls-configs-nvim</li>    <li>vimPlugins.feline-nvim</li>    <li>vimPlugins.fuzzy-nvim</li>    <li>vimPlugins.fzf-lua</li>    <li>vimPlugins.gitsigns-nvim</li>    <li>vimPlugins.hardtime-nvim</li>    <li>vimPlugins.haskell-tools-nvim</li>    <li>vimPlugins.hover-nvim</li>    <li>vimPlugins.image-nvim</li>    <li>vimPlugins.lazy-lsp-nvim</li>    <li>vimPlugins.lean-nvim</li>    <li>vimPlugins.leap-ast-nvim</li>    <li>vimPlugins.lsp_signature-nvim</li>    <li>vimPlugins.lspsaga-nvim</li>    <li>vimPlugins.mason-lspconfig-nvim</li>    <li>vimPlugins.material-nvim</li>    <li>vimPlugins.mini-nvim</li>    <li>vimPlugins.molten-nvim</li>    <li>vimPlugins.multicursors-nvim</li>    <li>vimPlugins.nabla-nvim</li>    <li>vimPlugins.neo-tree-nvim</li>    <li>vimPlugins.neodev-nvim</li>    <li>vimPlugins.neogit</li>    <li>vimPlugins.neorg (vimPlugins.neotest)</li>    <li>vimPlugins.neotest-haskell</li>    <li>vimPlugins.none-ls-nvim</li>    <li>vimPlugins.nvim-dap</li>    <li>vimPlugins.nvim-dap-python</li>    <li>vimPlugins.nvim-lint</li>    <li>vimPlugins.nvim-lspconfig</li>    <li>vimPlugins.nvim-metals</li>    <li>vimPlugins.nvim-navbuddy</li>    <li>vimPlugins.nvim-navic</li>    <li>vimPlugins.nvim-pqf</li>    <li>vimPlugins.nvim-scrollview</li>    <li>vimPlugins.nvim-tree-lua</li>    <li>vimPlugins.nvim-treesitter</li>    <li>vimPlugins.nvim-treesitter-context</li>    <li>vimPlugins.nvim-treesitter-parsers.apex</li>    <li>vimPlugins.nvim-treesitter-parsers.c</li>    <li>vimPlugins.nvim-treesitter-parsers.cpp</li>    <li>vimPlugins.nvim-treesitter-parsers.cuda</li>    <li>vimPlugins.nvim-treesitter-parsers.glsl</li>    <li>vimPlugins.nvim-treesitter-parsers.hcl</li>    <li>vimPlugins.nvim-treesitter-parsers.linkerscript</li>    <li>vimPlugins.nvim-treesitter-parsers.liquidsoap</li>    <li>vimPlugins.nvim-treesitter-parsers.php</li>    <li>vimPlugins.nvim-treesitter-parsers.purescript</li>    <li>vimPlugins.nvim-treesitter-parsers.python</li>    <li>vimPlugins.nvim-treesitter-parsers.rust</li>    <li>vimPlugins.nvim-treesitter-parsers.soql</li>    <li>vimPlugins.nvim-treesitter-parsers.sosl</li>    <li>vimPlugins.nvim-treesitter-parsers.sql</li>    <li>vimPlugins.nvim-treesitter-parsers.ssh_config</li>    <li>vimPlugins.nvim-treesitter-parsers.t32</li>    <li>vimPlugins.nvim-treesitter-parsers.templ</li>    <li>vimPlugins.nvim-treesitter-parsers.terraform</li>    <li>vimPlugins.nvim-treesitter-parsers.v</li>    <li>vimPlugins.nvim-treesitter-parsers.wing</li>    <li>vimPlugins.nvim-ts-context-commentstring</li>    <li>vimPlugins.nvim-web-devicons</li>    <li>vimPlugins.octo-nvim</li>    <li>vimPlugins.onedarkpro-nvim</li>    <li>vimPlugins.orgmode</li>    <li>vimPlugins.playground</li>    <li>vimPlugins.quarto-nvim</li>    <li>vimPlugins.rainbow-delimiters-nvim</li>    <li>vimPlugins.refactoring-nvim</li>    <li>vimPlugins.rest-nvim</li>    <li>vimPlugins.rustaceanvim</li>    <li>vimPlugins.sideways-vim</li>    <li>vimPlugins.snap</li>    <li>vimPlugins.splitjoin-vim</li>    <li>vimPlugins.ssr</li>    <li>vimPlugins.substitute-nvim</li>    <li>vimPlugins.telescope-cheat-nvim</li>    <li>vimPlugins.telescope-file-browser-nvim</li>    <li>vimPlugins.telescope-frecency-nvim</li>    <li>vimPlugins.telescope-fzf-native-nvim</li>    <li>vimPlugins.telescope-fzf-writer-nvim</li>    <li>vimPlugins.telescope-fzy-native-nvim</li>    <li>vimPlugins.telescope-media-files-nvim</li>    <li>vimPlugins.telescope-nvim</li>    <li>vimPlugins.telescope-symbols-nvim</li>    <li>vimPlugins.telescope-undo-nvim</li>    <li>vimPlugins.telescope-z-nvim</li>    <li>vimPlugins.telescope-zoxide</li>    <li>vimPlugins.text-case-nvim</li>    <li>vimPlugins.typescript-tools-nvim</li>    <li>vimPlugins.unison</li>    <li>vimPlugins.vim-alias</li>    <li>vimPlugins.vim-dadbod-completion</li>    <li>vimPlugins.vim-just</li>    <li>vimPlugins.vim-wakatime</li>  </ul></details>

**Pull request merged**
