### PR TITLE
flatpak: support cross compilation

### PR DESCRIPTION
**Pull request by uninsane**
## Description of changes

- `nix-build -A pkgsCross.aarch64-multiplatform.flatpak`
- note that `--enable-selinux-module=no` **was already being inferred** on native builds: grep `nix log $(nix-build -A flatpak)` for `Build selinux module`. `configure` just requires this to be explicit when cross compiling.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Please set strictDeps.

**Comment by uninsane** [comment]
> Please set strictDeps.

@SuperSandro2000 take a look at the commit i just pushed here and let me know if you think it's an improvement or not. `gtk-doc` functions as a library (the binary is linked against it), but it's also a build-time process (`gtkdocize` for the build architecture is used to execute the linked-for-the-host binary and extract the docs from it). so, `strictDeps` requires `gtk-doc` to be both in `nativeBuildInputs` (where it already is) _and_ in `buildInputs`. i think that's technically correct (?), but is enforcing that _helpful_?

FWIW the 1.15.x branch of flatpak migrates to meson, which usually means these things will simplify, but i think that won't be released still for several months.

**Comment by getchoo** [comment]
> i think that's technically correct (?), but is enforcing that helpful?

I'd say so, as it not only makes a clear distinction that it's required at both build and runtime, but also ensures the correct package is used for either (i.e., the gtk-doc library native to the build platform doesn't end up being linked with the binary meant for the ((differing)) host platform)

**Review by getchoo — APPROVED** [review]
needs to be reformatted. otherwise LGTM

**Review by SuperSandro2000 — APPROVED** [review]

**Review by getchoo — APPROVED** [review]

**Comment by uninsane** [comment]
fixed the nixfmt CI check, all lights green :)

btw if GH complains about nixfmt, the fix is `nix run '.#nixfmt-rfc-style' -- pkgs/by-name/fl/flatpak/package.nix`. i wish it would show that in the log instead of just `Error: `

**Review by getchoo — APPROVED** [review]

**Pull request merged**
