### PR TITLE
fish: 3.1.0 -> 3.1.1

### PR DESCRIPTION
**Pull request by cole-h**
https://github.com/fish-shell/fish-shell/compare/3.1.0...3.1.1

The patch we had to use for Apple SDKs was merged upstream, so it can be
dropped. I ran nixpkgs-fmt, and removed the `with stdenv.lib;` scope
expander.

Additionally, did a little bit of cleanup. I plan on refactoring this
more down the line, but this'll do for now.

I finally figured out why we use `fetchurl` for the tagged release: the
published release tarballs contain a version file, which the
`build_tools/git_version_gen.sh` script reads (and uses as the version
if it exists). The other thing it contains are pre-generated docs for
various `fish` builtins. I've expanded the comment to document this so
nobody is as confused as I was when I first saw it. (Though I plan to
change this and add sphinx as a native build input in order to build the
docs ourselves.)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @lilyball: Mind testing on macOS, to ensure we don't run into a similar issue to last time?
cc @Profpatsch: Is the `withTests` stuff still necessary? Can I drop it, or is there something you'd like done with it?

EDIT: I also verified that the NixOS module's patch still applies, but if somebody could determine for certain whether or not anything needs to be fixed there, as well, I'd appreciate it.

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build fish

**Comment by lilyball** [comment]
Build fails on macOS due to https://github.com/fish-shell/fish-shell/commit/d0a67e372c492ffc7c50efa838a19f59077e1de0:

```
  Scanning dependencies of target fish_indent
  [ 95%] Building CXX object CMakeFiles/fish_indent.dir/src/fish_indent.cpp.o
  [ 96%] Building CXX object CMakeFiles/fish_indent.dir/src/print_help.cpp.o
  [ 96%] Linking CXX executable fish_indent
  /nix/store/i9jh1yxfinl0pa5y2c9h2z5i0sdhaf7q-bash-4.4-p23/bin/bash: codesign: command not found
  make[2]: *** [CMakeFiles/fish_indent.dir/build.make:121: fish_indent] Error 127
  make[2]: *** Deleting file 'fish_indent'
  make[1]: *** [CMakeFiles/Makefile2:662: CMakeFiles/fish_indent.dir/all] Error 2
  make: *** [Makefile:147: all] Error 2
```

Since we presumably don't want to break the sandbox just for codesigning (can you even Ad-Hoc codesign without a developer account?) we're going to have to disable it. I'll file an upstream issue about having an official way to turn it off, but until then I guess we can just patch `CMakeLists.txt`.

**Comment by lilyball** [comment]
Upstream issue filed as https://github.com/fish-shell/fish-shell/issues/6952.

**Comment by adisbladis** [comment]
Looks like the code signing was patched out :)
@GrahamcOfBorg build fish

**Comment by Profpatsch** [comment]
Do you want to add yourself as a maintainer?

**Comment by Profpatsch** [comment]
> cc @Profpatsch: Is the `withTests` stuff still necessary? Can I drop it, or is there something you'd like done with it?

The `withTests` can be replaced by putting the test into `passthru.tests` and making it a `runCommand` instead of a string. `withTests` is a primitive that I never got around to upstreaming.

**Comment by lilyball** [comment]
There's now a way on fish master to disable it: https://github.com/fish-shell/fish-shell/commit/3a47db74b068d9b26eb8b8942923257ebc15c366

So we can set that new value on the next release.

**Comment by Profpatsch** [comment]
> Merged #86136 into master.

Would have liked to see the test added first, but maybe somebody can
do that as a followup.

**Comment by cole-h** [comment]
The only reason the test wasn't added was because it fails. I've been working off and on to try and fix it up, but the tempfile appears to never get created: `cat: /build/web_configyaz_apca.html: No such file or directory`.

**Comment by cole-h** [comment]
Test fixed in followup here: https://github.com/NixOS/nixpkgs/pull/86802.

**Comment by Profpatsch** [comment]
Great, thanks

**Pull request merged**
