### PR TITLE
Add mopidy-mpris

### LINKED ISSUE #38758: Mopidy: Include pip modules with the installation of mopidy
## Issue description

It would be nice if like with `services.mopidy.extensionPackages`, one could specify pip modules like `mopidy-mpris`, to allow for including newer modules that don't yet have a native nix package.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131792.becbe4dbe16 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131792.becbe4dbe16"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### PR DESCRIPTION
**Pull request by aidabeorn**
###### Motivation for this change
Add mopidy-mpris so that it can easily be installed with mopidy

closes #38758

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]

**Review by dotlambda — CHANGES_REQUESTED** [review]

**Comment by thorerik** [comment]
I did the changes you said here, but once I ran `nix-build -A mopidy-mpris`, it started pulling in rust, any idea why that would happen?

current, uncommited state: 
https://gist.github.com/thorerik/767ffc9f744cbbe46d690ff18c7f85ad

**Comment by Mic92** [comment]
Maybe because rsvg is written in rust and was about to compile? librsvg-2.42.2

**Comment by dotlambda** [comment]
Did this actually work without the second commit you added?

**Comment by thorerik** [comment]
It built, but I'm unsure how to test it since it should be installed with `services.mopidy.extensionPackages`.

**Comment by dotlambda** [comment]
You can simply add it there, and do
```
nixos-rebuild test -I nixpkgs=path/to/your/local/nixpkgs
```

**Comment by thorerik** [comment]
Thanks, I see there's a lot more to work through here before this is even remotely close to working. I'll close it for now and open a new PR once it's in a more servicable state.

**Pull request closed without merging**
