### PR TITLE
dotnet: add publish and web tests

### PR DESCRIPTION
**Pull request by corngood**
This adds a helper for creating dotnet tests, and adds tests for:

- normal publish and run via wrapper
- aspnetcore web app

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

FYI @NixOS/dotnet 

@ofborg build dotnet-sdk_6.tests dotnet-sdk_7.tests dotnet-sdk_8.tests dotnetCorePackages.dotnet_8.tests

### CODE REVIEW

**Comment by GGG-KILLER** [comment]
By the way, about the SDK + Runtime tests (and maybe even source-built + binary) tests, I think we can add it to `pkgs/test/dotnet` in the future.

**Comment by GGG-KILLER** [comment]
Result of `nixpkgs-review pr 294070` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by GGG-KILLER — APPROVED** [review]
Okay, code seems to do the required basic tests and they all pass. Thank you very much for this!

using
```bash
for package in sdk_6_0 sdk_7_0 sdk_8_0 dotnet_8.sdk; do
    nix-build --attr "pkgs.dotnetCorePackages.$package.passthru.tests" 2>&1 | sed -e "s/^/$package: /";
done
```
these were the result logs: https://gist.github.com/GGG-KILLER/2d5541df5248ac5b6e19115ed9cdde79

**Comment by GGG-KILLER** [comment]
Tests on sdk_9_0 passed however they failed on `dotnet_9.sdk`. Looking at the logs it seems to be something related to crossgen2: https://gist.github.com/GGG-KILLER/2d5541df5248ac5b6e19115ed9cdde79#file-source-build-9-vmr-log

**Comment by corngood** [comment]
Interesting, so your SDK isn't even building.

> /build/MSBuildTempnixbld/tmpd37d9e1d7e4a4139a377bd0b505f6637.exec.cmd: line 2: /build/dotnet-9.0.0-preview.1.24080.9/src/aspnetcore/artifacts/sb/package-cache/microsoft.netcore.app.crossgen2.linux-x64/9.0.0-preview.1.24080.9/tools/crossgen2: cannot execute: required file not found

Usually this has to do with the crossgen executable not being patched.

It seems to be failing on hydra too.  I'll see if I can reproduce it.

**Comment by corngood** [comment]
Hmm, I'm able to build everything properly on latest master.  Let's try:

@ofborg build dotnet-sdk_6.tests dotnet-sdk_7.tests dotnet-sdk_8.tests dotnetCorePackages.dotnet_8.tests dotnetCorePackages.dotnet_9.tests

**Comment by corngood** [comment]
Ah, I misunderstood.  It's failing on hydra due to output size (#294543).  I'll have a look at that.  The `crossgen2` error is probably unrelated, but worrying.

**Pull request merged**
