### PR TITLE
dictd: add Japanese dbs eng2jpn and jpn2eng

### PR DESCRIPTION
**Pull request by miangraham**
###### Description of changes

Added freedict dictionaries for Japanese (eng2jpn and jpn2eng) to the dictd-db collection.

Sourceforge does not have the eng2jpn side, so I'm pulling that one from a pinned version on download.freedict.org.

Built via nixpkgs-review:

```console
$ nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"

$ nix-env --option system x86_64-linux -f /home/ian/.cache/nixpkgs-review/rev-a748f63ca7395046c5856077056fe1033df55018/nixpkgs -qaP --xml --out-path --show-trace --meta
2 packages added:
dictd-db-eng-jpn dictd-db-jpn-eng

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/ian/.cache/nixpkgs-review/rev-a748f63ca7395046c5856077056fe1033df55018/build.nix
2 packages built:
dictdDBs.eng2jpn dictdDBs.jpn2eng
```

Runtime-tested on my nixos system via module config:

```nix
services.dictd = {
  enable = true;
  DBs = with pkgs.dictdDBs; [
    eng2jpn
    jpn2eng
  ];
};
```

Tests:

```console
$ dict -h localhost -D
Databases available:
 dictd-db-eng-jpn English-日本語 (にほんご) FreeDict+WikDict dictionary ver. 2022.04.06
 dictd-db-jpn-eng Japanese-English FreeDict Dictionary ver. 0.1

$ dict -h localhost -d dictd-db-jpn-eng 日本語
1 definition found

From Japanese-English FreeDict Dictionary ver. 0.1 [dictd-db-jpn-eng]:

   [news1]  [nf02]  日本語,  [news1]  [nf02]  にほんご, にっぽんご
  1. (noun (common) (futsuumeishi))
   (nouns which may take the genitive case particle `no')
  {国語・こくご・2}Japanese (language)
  2. (にほんご)
   (noun (common) (futsuumeishi))
   (esp. as a school or university subject)
  Japanese as a second language

$ dict -h localhost -d dictd-db-eng-jpn japanese
2 definitions found

From English-日本語 (にほんご) FreeDict+WikDict dictionary ver. 2022.04.06 [dictd-db-eng-jpn]:

  Japanese //ˌdʒæpəˈniːz// <adj>
  日本の, 日本, 和, 日
  of or relating to Japan

From English-日本語 (にほんご) FreeDict+WikDict dictionary ver. 2022.04.06 [dictd-db-eng-jpn]:

  Japanese //ˌdʒæpəˈniːz// <n>
  1. 日本語, ジャパニーズ
  Japanese language
  2. 日本人, ジャパニーズ
  person of Japan
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@ofborg build dictdDBs.eng2jpn dictdDBs.jpn2eng

**Comment by miangraham** [comment]
@7c6f434c Thanks for the look. I'm pretty green so let me know if there are any good additional reviewers or obvious tweaks I'm missing to move this one forward.

**Comment by 7c6f434c** [comment]
Looks good enough for a pure addition to me, fits the logic how other things are done.

**Comment by miangraham** [comment]
Thanks for the help!

**Pull request merged**
