### PR TITLE
python3Packages.itemloaders: 1.0.3 -> 1.0.4

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build python3Packages.scrapy

**Comment by Dyazz** [comment]
Result of `nixpkgs-review pr 108760` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>python37Packages.itemloaders</li>
    <li>python37Packages.scrapy</li>
    <li>python37Packages.scrapy-deltafetch</li>
    <li>python37Packages.scrapy-fake-useragent</li>
    <li>python37Packages.scrapy-splash</li>
    <li>python38Packages.itemloaders</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
    <li>python39Packages.itemloaders</li>
    <li>python39Packages.scrapy</li>
    <li>python39Packages.scrapy-deltafetch</li>
    <li>python39Packages.scrapy-fake-useragent</li>
    <li>python39Packages.scrapy-splash</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108760` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>python37Packages.itemloaders</li>
<li>python37Packages.scrapy</li>
<li>python37Packages.scrapy-deltafetch</li>
<li>python37Packages.scrapy-fake-useragent</li>
<li>python37Packages.scrapy-splash</li>
<li>python38Packages.itemloaders</li>
<li>python38Packages.scrapy</li>
<li>python38Packages.scrapy-deltafetch</li>
<li>python38Packages.scrapy-fake-useragent</li>
<li>python38Packages.scrapy-splash</li>
<li>python39Packages.itemloaders</li>
<li>python39Packages.scrapy</li>
<li>python39Packages.scrapy-deltafetch</li>
<li>python39Packages.scrapy-fake-useragent</li>
<li>python39Packages.scrapy-splash</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.scrapy-deltafetch:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python37Packages.scrapy-splash:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.scrapy-deltafetch:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.scrapy-splash:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.scrapy-deltafetch:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.scrapy-splash:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 108760` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python37Packages.scrapy</li>
    <li>python37Packages.scrapy-deltafetch</li>
    <li>python37Packages.scrapy-fake-useragent</li>
    <li>python37Packages.scrapy-splash</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
    <li>python39Packages.scrapy</li>
    <li>python39Packages.scrapy-deltafetch</li>
    <li>python39Packages.scrapy-fake-useragent</li>
    <li>python39Packages.scrapy-splash</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.itemloaders</li>
    <li>python38Packages.itemloaders</li>
    <li>python39Packages.itemloaders</li>
  </ul>
</details>

**Pull request merged**
