### PR TITLE
supercollider: 3.11.0 -> 3.11.2

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

This update allows to migrate to Qt5.15

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by freezeboy** [comment]
Related to #104474

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 104431` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python27Packages.foxdot</li>
    <li>python37Packages.foxdot</li>
    <li>python38Packages.foxdot</li>
    <li>sonic-pi</li>
    <li>supercollider</li>
    <li>supercollider_scel</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 104431 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>6 packages built:</summary>  <ul>    <li>python27Packages.foxdot</li>    <li>python37Packages.foxdot</li>    <li>python38Packages.foxdot</li>    <li>sonic-pi</li>    <li>supercollider</li>    <li>supercollider_scel</li>  </ul></details>

**Pull request merged**
