### PR TITLE
rubygems: 2.6.13 -> 2.7.6

### PR DESCRIPTION
**Pull request by manveru**
###### Motivation for this change

https://www.ruby-lang.org/en/news/2018/02/17/multiple-vulnerabilities-in-rubygems/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
@GrahamcOfBorg build ruby

**Comment by zimbatm** [comment]
also cherry-picked to the release-17.09 branch

**Comment by manveru** [comment]
Thanks a lot!

**Comment by risicle** [comment]
> also cherry-picked to the release-17.09 branch

This was a breaking change. Ever since d09e425aea3e09b6cec5c7b05cc0603f6853748b a (fairly boring) app of ours fails with:

```
You have already activated bundler 1.16.1, but your Gemfile requires bundler 1.14.6. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

**Comment by globin** [comment]
This also broke gitlab, I've disabled it on master and release-18.03, this somehow changes the behaviour of gem lookup.

**Comment by globin** [comment]
I'm reverting this on 17.09

**Comment by risicle** [comment]
Nice.

Frustratingly the linked announcement lists fixes and patches for  2.2 -> 2.5, but no 2.6.

**Comment by risicle** [comment]
Oh sorry misread - those are for *ruby* versions 2.2 -> 2.5

**Comment by risicle** [comment]
I was going to have a look-see if debian had a backport of this patch but noticed that interestingly this isn't fixed in even their stable yet https://security-tracker.debian.org/tracker/source-package/ruby2.3

**Comment by risicle** [comment]
Another slightly more extreme possibility would be to bump 17.09's bundler to 1.16.1... don't know what the further repercussions would be though.

**Comment by globin** [comment]
I have a possible fix for gitlab based on manveru's work, will test this more thoroughly this evening and push upstream then.

**Comment by risicle** [comment]
Oh - actually - ignore my previous comment - it turns out it was just because I was *also* injecting `pkgs.bundler` back into my runtime environment, which is of course a version mismatch. If I simply omit that and remove `bundle exec` from my commands, it all seems to work.

**Pull request merged**
