### PR TITLE
virtualbox: 5.2.26 → 5.2.28

### PR DESCRIPTION
**Pull request by artemist**
###### Motivation for this change
VirtualBox is out of date

###### Things done
Update the version and hashes in the package

Note that at the time of posting, the HTTPS update site is down, so it will fail to build unless you manually prefetch it from the HTTP site.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build virtualbox

**Comment by cdepillabout** [comment]
Note that there is also a WIP PR for virtualbox-6:

https://github.com/NixOS/nixpkgs/pull/53120

**Comment by artemist** [comment]
VirtualBox 6.0 is having some trouble with nested virtualization. I may work on fixing that test, but I believe that this is useful as a stop-gap measure.

**Comment by flokli** [comment]
Right, as long as virtualbox 6 seems broken, we should still keep the 5.x variant up to date.

I built different virtualbox flavours and both free and unfree vm tests passed.

Thanks a lot @artemist! This should be backported too IMHO.

**Pull request merged**
