### PR TITLE
poetry: 1.0.0 -> 1.0.1

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Also bumps poetry2nix although not strictly required.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zimbatm** [comment]
I am getting this error:
```
$ nix-build -A poetry
error: opening file '/home/zimbatm/.cache/nixpkgs-review/pr-77437/nixpkgs/pkgs/development/tools/poetry/src.json': No such file or directory
(use '--show-trace' to show detailed location information)
```

**Comment by adisbladis** [comment]
@zimbatm Whoops, forgot to commit some new files.

**Comment by zimbatm** [comment]
tested with nixpkgs-review

**Comment by zimbatm** [comment]
@adisbladis you might want to set the updateScript as well like that: https://github.com/NixOS/nixpkgs/blob/178ac3cb99a2af4e39fa287ce4774ebb608eef1a/pkgs/desktops/pantheon/desktop/wingpanel-indicators/nightlight/default.nix#L26-L30

**Comment by retrry** [comment]
1.0.2 is already released with one PR reverted.

**Comment by adisbladis** [comment]
@retrry I pushed that bump straight to master, it's already there :)

**Comment by retrry** [comment]
I don't want to create issue for stupid questions, but why there are two poetry instances? One is 1.0.2, the other is still 0.2.17? 

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/poetry/default.nix

**Comment by adisbladis** [comment]
@retrry One is manually packaged in the `pythonPackages` set, one is automatically packaged with `poetry2nix` as a separate derivation not tied to what's in `pythonPackages`.

I'm not sure what to do with the one in `pythonPackages`, I don't consider that one a very useful derivation.

**Comment by adisbladis** [comment]
> I don't want to create issue for stupid questions, but why there are two poetry instances? One is 1.0.2, the other is still 0.2.17?
> 
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/poetry/default.nix

@retrry I've made a PR addressing this: https://github.com/NixOS/nixpkgs/pull/77629

**Pull request merged**
