### PR TITLE
fclones: 0.19.0 -> 0.20.1

### PR DESCRIPTION
**Pull request by msfjarvis**
###### Description of changes

Updates fclones to 0.20.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cyounkins** [comment]
In a previous upgrade I had trouble getting the SRI hash. `nix hash` seems to only do SHA256. IIRC running `nix-build` with a bogus SRI hash dumped the correct hexadecimal SHA256 instead of the base64-encoded SRI.

The nixpkgs manual's rust section says:
> cargoHash256 is used for traditional Nix SHA-256 hashes... cargoHash should instead be used for [SRI](https://www.w3.org/TR/SRI/) hashes.

and the section on fetchFromGithub:
> Again, other hash algorithms are also available but sha256 is currently preferred. 

So for fetchFromGithub it's not clear if there is a `hash` attribute.

I think we should use plain sha256 for ease of use right now, but if SRI is The Way, let's change to the `hash` attributes?

**Comment by cyounkins** [comment]
I'm very puzzled that when testing with "nix-review wip" (these changes applied as WIP locally), under `fetchFromGithub`:

`hash = "sha256-3xIJkV/BC+qdMP2vsUr5wIwqzaz2uCV/j6VdC6uvzgY=";` works as expected. This is the hash in the PR.

`hash = "sha256-3xIJkV/BC+qdMP2vsUr5wIwqzaz2uCV/j6VdC6uvzgZ=";` also works! Note that the last letter is different. Huh???

`hash = "sha256-3xIJkV/BC+qdMP2vsUr5wIwqzaz2uCV/j6VdC6uvzgA=";` fails and complains about the mismatch in hex, not base64 SRI.

**Comment by msfjarvis** [comment]
> In a previous upgrade I had trouble getting the SRI hash. `nix hash` seems to only do SHA256. IIRC running `nix-build` with a bogus SRI hash dumped the correct hexadecimal SHA256 instead of the base64-encoded SRI.

`nix to-sri --type sha256 <SHA256>` seems to convert it just fine.

> 
> The nixpkgs manual's rust section says:
> > cargoHash256 is used for traditional Nix SHA-256 hashes... cargoHash should instead be used for [SRI](https://www.w3.org/TR/SRI/) hashes.
> 
> and the section on fetchFromGithub:
> > Again, other hash algorithms are also available but sha256 is currently preferred. 
> 
> So for fetchFromGithub it's not clear if there is a `hash` attribute.
> 
> I think we should use plain sha256 for ease of use right now, but if SRI is The Way, let's change to the `hash` attributes?
> 

I use [nix-update](https://github.com/Mic92/nix-update) to generate these PRs which uses SRI so I'm inclined to believe it is the recommended way and we should stick with it.

I'm not sure what's up with the `hash` and `cargoHash` attributes but what's in the PR correctly breaks when you use a wrong hash anywhere.

**Comment by cyounkins** [comment]
Yeah, so about that footgun...

```
$ nix to-base16 sha256-3xIJkV/BC+qdMP2vsUr5wIwqzaz2uCV/j6VdC6uvzgY=
df1209915fc10bea9d30fdafb14af9c08c2acdacf6b8257f8fa55d0babafce06
$ nix to-base16 sha256-3xIJkV/BC+qdMP2vsUr5wIwqzaz2uCV/j6VdC6uvzgZ=
df1209915fc10bea9d30fdafb14af9c08c2acdacf6b8257f8fa55d0babafce06
```

**Comment by cyounkins** [comment]
I filed a bug about the many-to-one correspondence here: https://github.com/NixOS/nix/issues/6414

> `nix to-sri --type sha256 <SHA256>` seems to convert it just fine.

That works on Nix 2.3.16, but not on 2.5.1! This is exactly why I gave up on SRI before, but I've got it now:

```console
$ nix --version
nix (Nix) 2.5.1

$ nix to-sri --type sha256 000000000000000000000000000000000000000000000000000000000000000
error: 'to-sri' is not a recognised command
Try 'nix --help' for more information.

$ nix hash to-sri --type sha256 000000000000000000000000000000000000000000000000000000000000000
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

$ nix --extra-experimental-features hash to-sri --type sha256 000000000000000000000000000000000000000000000000000000000000000
warning: unknown experimental feature 'hash'
error: 'to-sri' is not a recognised command
Try 'nix --help' for more information.

# gotta supply an argument to the flag

$ nix --extra-experimental-features nix-command hash to-sri --type sha256 0000000000000000000000000000000000000000000000000000000000000000
sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

Anyway, I'll approve the PR since it's working. I'll test nix-update with `hash` and `cargoHash` options and may open an issue there.

Thanks for handling this update!

**Review by cyounkins — APPROVED** [review]

**Pull request merged**
