### PR TITLE
qc: init at 0.0.4

### PR DESCRIPTION
**Pull request by pbek**
###### Description of changes

Adds `qc`, the **QOwnNotes command-line snippet manager**.
https://github.com/qownnotes/qc

You can use the **QOwnNotes command-line snippet manager** to **execute command snippets** stored
in **notes** in [QOwnNotes](https://www.qownnotes.org/) from the command line.

This app is a companion to https://github.com/NixOS/nixpkgs/tree/nixos-22.11/pkgs/applications/office/qownnotes.

Note: The build config is almost the same as https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/pet/default.nix.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pbek** [comment]
@totoroot, do you care to review this too?

**Comment by totoroot** [comment]
Sure, can you add me to the list of maintainers, so that I get pinged automatically in the future?
BTW is it alright if I add you to the maintainers of `qownnotes` as well with the Qt6 PR?

**Comment by pbek** [comment]
Sure and sure!

**Comment by pbek** [comment]
@totoroot, do you think it's an issue that ofborg-eval fails?
https://gist.github.com/GrahamcOfBorg/1672d2ca0c96bd29e94e941b85f1e5b2

**Comment by pbek** [comment]
At least there should be no CI-complains about me not being a maintainer any more. 😉

**Comment by pbek** [comment]
The evaluation runs through now, @totoroot. Would you care to review it?

**Comment by wineee** [comment]
Please squash the commits, thanks!

**Comment by pbek** [comment]
> Please squash the commits, thanks!

I merged master into this branch, am I supposed to squash that too (takes ages)?
And out of curiosity, why just don't use the GitHub feature to squash pull requests (instead of merging them)?

**Comment by wineee** [comment]
Squash manually all the commits  to one： `qc: init at 0.0.4‘， add totoroot as maintainer/improve ldflags don't need  a separate commit

**Comment by pbek** [comment]
> Squash manually all the commits to one： `qc: init at 0.0.4‘， add totoroot as maintainer/improve ldflags don't need a separate commit

I understand all that, @wineee. But at the intial state of the PR I wasn't registered as maintainer on nixpkgs, so I merged master into my PR branch later on. Should I squash the master-merge too? Maybe it's better I create a new PR?

And so out of curiosity, why just don't use the GitHub feature to squash pull requests (instead of merging them) and give it the name `qc: init at 0.0.4`? Wouldn't that solve all issues?

**Comment by wineee** [comment]
1. We should rebase to the master branch instead of merge , I would prefer to drop the `master-merge` commit and rebase again.



3. Use the GitHub feature to squash pull requests seems work， but I rarely seen precedent,   need some help @SuperSandro2000

**Comment by pbek** [comment]
> I would prefer to drop the master-merge commit and rebase again.

since "dropping" of a commit isn't that easy, I'd rather do a new PR 😅 

> Use the GitHub feature to squash pull requests seems work， but I rarely seen precedent, need some help 

Then only thing it did for me in all those years was putting everything the diff in the GitHub PR shows in one single commit where I (as merger) can control the name. I'm doing that a lot when commits of contributors get to "messy" in my projects. 😉

**Comment by pbek** [comment]
Thank you for clarification!

> This is done in order to keep complete commit messages

Ok, this would matter in this case. There is only one applicable commit message: `qc: init at 0.0.4`.

> and GPG signatures intact.

That I understand (given that the requester has signed his commit and added his/her stuff on GitHub directly).

I'll close this PR then in favor of my new PR #229827.

**Pull request closed without merging**
