### PR TITLE
json-directory: mark unbroken

### PR DESCRIPTION
**Pull request by luke-clifton**
As of 1.0.2 json-directory builds

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@luke-clifton Thanks!  Could you rebase this on the `haskell-updates` branch?  We generally ask that all Haskell-related changes go there.

**Comment by winterqt** [comment]
@ofborg build haskellPackages.json-directory

**Comment by cdepillabout** [comment]
@winterqt Asking `ofborg` to build this likely won't work until re-running `maintainers/scripts/haskell/regenerate-hackage-packages.sh`.  @luke-clifton could do that in this PR (which would be easier for us), or one of us would do it after merging into the `haskell-updates` branch (which is currently being tracked in https://github.com/NixOS/nixpkgs/pull/182019).

It is also possible this won't be possible to backport (depending on how much `master` has differed from 22.05 by now).

**Comment by winterqt** [comment]
@cdepillabout Yeah, that makes sense, apologies.

> It is also possible this won't be possible to automatically backport (depending on how much `master` has differed from 22.05 by now).

I removed the label since 22.05 does not have micro version 2 of this package.

**Comment by cdepillabout** [comment]
Ah sorry, I didn't realize you immediately removed it!

**Comment by luke-clifton** [comment]
Close in favour of https://github.com/NixOS/nixpkgs/pull/182207

**Pull request closed without merging**
