### PR TITLE
mpdecimal: split C++ library into separate output

### PR DESCRIPTION
**Pull request by KAction**
maintainers: @KAction

### CODE REVIEW

**Comment by symphorien** [comment]
Looks like c++ headers are not in the c++ output. Is it intended ?

**Comment by KAction** [comment]
Not really intentional, I'd say it is okay. Headers are quite small and probably do not warrant another output to separate C library and headers. C++ library, on other hand, pulls gcc into the closure, so I'd rather have it separately.

**Comment by symphorien** [comment]
Looks like the c++ output does not give access to the headers, though:
```
nix-shell --pure -I nixpkgs=./nixpkgs -p mpdecimal.cxx

[nix-shell:~/.cache/nixpkgs-review/pr-216534-1]$ g++ /tmp/pi.cc
/tmp/pi.cc:36:10: fatal error: decimal.hh: No such file or directory
   36 | #include "decimal.hh"
      |          ^~~~~~~~~~~~
compilation terminated.
```

Also what do you think about adding a libmpdecimalxx alias ?

**Comment by KAction** [comment]
I guess you need to add `-p mpdecimal.out` explicitly to get headers in nix-shell. It works when you put `mpdecimal` into `buildInputs`, though:

```test.nix
with (import ./. { });
stdenv.mkDerivation {
  name = "whatever";
  buildInputs = [ mpdecimal ];
}
```

And with `nix-shell test.nix` `g++` can find headers.

Re `libmpdecimalxx`: can you elaborate? You suggest to have extra name in `all-packages.nix`, in addition to just `mpdecimal`?

**Comment by symphorien** [comment]
It's a question of ux: in the package search, only mpdecimal is listed. 
- if someone wants to package something that depends on the c++ part of mpdecimal, it is very hard to discover that you need to add mpdecimal.cxx to buildInputs. For this reason it would be nice to add an alias
- if some project claims they depend on libmpdecimal++ it would be nice if only adding the alias mentioned above worked without adding mpdecimal (the C part) as well.

(note that only adding the C part finds c++ headers as you noted, but does not link (the library is not there).

Another possibility would be to separate headers into a dev output, and have headers propagate both the C and C++ libs, so linking always works with just mpdecimal.dev for C and C++, but the runtime dependency on c++ does not remain when unused.

**Comment by KAction** [comment]
Okay, let's split headers. So now we have `out` which contains C library, `cxx` which contains C++ library (which depends on `out`), `dev` which contains headers and artificially pulls `out` and `cxx` and `doc` which depends on nothing.

**Comment by symphorien** [comment]
thank you!

**Pull request merged**
