### PR TITLE
bottom: 0.4.7 -> 0.5.1

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you rebase this branch on master to fix the eval error?

**Comment by magnetophon** [comment]
Done, also upgraded to the new release.

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 104444` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bottom</li>
  </ul>
</details>

**Review by berbiche — APPROVED** [review]

**Comment by berbiche** [comment]
@SuperSandro2000 do you know why I wasn't automatically pinged as the maintainer?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 do you know why I wasn't automatically pinged as the maintainer?

IIRC you need to be a member of the org to be pinged via githubs reviewer feature through borg.

**Pull request merged**
