### PR TITLE
nixos/dendrite: remove

### PR DESCRIPTION
**Pull request by mjlbach**
###### Motivation for this change

There are some usability problems around the module re: dynamic user's ability to access protected files (you currently need to copy these into the persistent state directory). I said I'd fix it before the 21.05 branch off, but I could not due to some issues I ran into with systemd.

@dotlambda I'm not going to be able to get LoadCredential working before systemd 248 likely. There are other workarounds to improve the ergonomics of DynamicUser with the TLS/federation keys but not sure if we could get those in before 21.05. I can make a PR un-reverting this which includes the tests/etc.

###### Things done
Remove dendrite, dendrite module, dendrite tests.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
That's sad :(
Did you come across any particular issues when trying systemd credentials?

I think there's no need to remove the package, just the module.

What's @NixOS/nixos-release-managers opinion on this? The rationale is that shipping a broken module is bad because we might have to introduce breaking changes to fix it. That said, the module is working except for `tlsKey` and `tlsCert` options.

**Comment by dotlambda** [comment]
@mjlbach Please add a short rationale to the commit message.

**Comment by mjlbach** [comment]
@dotlambda you should write whatever rationale you want here, and I'll add it to the commit message.

**Comment by mohe2015** [comment]
I'm not using this currently but what about only removing on the release branch (which is not created yet afaik) and keeping in unstable?

**Comment by dotlambda** [comment]
> I'm not using this currently but what about only removing on the release branch (which is not created yet afaik) and keeping in unstable?

That sounds like a good option.

> @dotlambda you should write whatever rationale you want here, and I'll add it to the commit message.

I guess something like "The options tlsKey and tlsCert are broken and fixing them might require breaking changes. Thus the module should not be included in a stable release."

> Re: LoadCredential, I'm running into the same issue as @happysalada does here [systemd/systemd#19604](https://github.com/systemd/systemd/issues/19604)

You could try rebasing your changes on https://github.com/NixOS/nixpkgs/pull/123476 and see if that works.

**Comment by mjlbach** [comment]
> That sounds like a good option.

Ok! I'll file this same PR with that message into 21.05 after branch-off. 

Re: systemd 248, sg, I will try this weekend to get everything running and if it works we can fix the module on nixpkgs-unstable.

**Comment by mohe2015** [comment]
@mjlbach branchoff has happened so you may want to do this now.

**Comment by mjlbach** [comment]
Just did :)

**Pull request closed without merging**
