### PR TITLE
nixos/mosquitto: add bind_interface listener option, fix assertion messages

### LINKED ISSUE #172944: `services.mosquitto`: missing support for `bind_interface` option
### Describe the bug
[`mosquitto.conf`'s documentation](https://mosquitto.org/man/mosquitto-conf-5.html) lists a listener option called `bind_interface` that can be used to listen for incoming network connections only on the specified interface. Unfortunately `services.mosquitto.listener.*.settings` does not accept this option.

### Steps To Reproduce
```nix
{
  services.mosquitto = {
    enable = true;
    listeners = [{
      settings.bind_interface = "tailscale0";
    }];
  };
}
```

### Expected behavior
This should evaluate cleanly.

### Output
```console
> nix flake check
error:
       Failed assertions:
       - Invalid config key services.mosquitto.listener.0.bind_interface.
(use '--show-trace' to show detailed location information)
```

Incidentally, that assertion message drops the `settings` component in the attribute path, it might be nice to fix that.

### Notify maintainers
@pennae

### Metadata

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3.1`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.8.0`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre330171.92204897f3d"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

### PR DESCRIPTION
**Pull request by pennae**
###### Description of changes

the `bind_interface` listener option is not currently supported by the mosquitto module. add that setting and a test for it, and fix assertion messages that mention the wrong attribute path for invalid settings as well.

closes #172944

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lilyball** [comment]
I'm not particularly familiar with how the nixos tests work, but it looks like it's just checking that mosquitto is listening on en0. Surely it should check to make sure it's _not_ listening on any other interface as well (such as the loopback interface)?

**Comment by pennae** [comment]
indeed, the test only checks whether `bind_interface` does something that looks roughly correct (picking addresses from the given interface and listening on those). checking whether mosquitto behaves *exactly* as the docs say would belong in the mosquitto test suite, here we only check whether everything is hooked up correctly that `bind_interface` can work at all. (eg at first we hadn't allowed the AF_NETLINK yet, so the server just didn't start with that setting given)

**Comment by lilyball** [comment]
My concern is that by just checking `eth0` you aren't actually ensuring that `bind_interface` was specified correctly in the mosquitto conf at all. The reason being that a listener block `{ port = 1889; }` will result in `listener 1889`, which will listen on all interfaces including `eth0`. So if the `bind_interface` command is mis-specified (omitted, written wrong, doesn't actually apply to the listener in question, etc) then the test won't catch that.

Or to put it another way, `bind_interface` doesn't mean "bind to this interface", it means "_don't_ bind to any other interface but this one", and so we should be testing that it's not binding to other interfaces. But we do still need the `eth0` test to make sure we're actually listening _somewhere_.

**Comment by lilyball** [comment]
I haven't run it but this new test looks better, thanks.

**Comment by pennae** [comment]
@ofborg test mosquitto

**Comment by pennae** [comment]
@lilyball have you had the chance to test whether this fixes your problem?

**Comment by pennae** [comment]
going to merge this now since this only adds more allowed config keys, the tests pass, and we've already missed the branch-off anyway. once independently verified we can backport as well.

**Comment by lilyball** [comment]
I finally tested this in my local setup and it does appear as though mosquitto is binding just to the interface specified. Thanks!

**Pull request merged**
