### PR TITLE
gi-gdkx11: Default to 3.X version

### PR DESCRIPTION
**Pull request by mdorman**
The newer (4.X) versions require gtk4 which shouldn't be the default.

###### Motivation for this change

Fixes all packages that depend on gi-gdkx11 (which wasn't able to build since gtk4 isn't available in Nix)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peti

### CODE REVIEW

**Comment by cdepillabout** [comment]
@mdorman Thanks for trying to fix this.

However, the `default-package-overrides` section is generated semi-automatically and shouldn't be added to by hand.

I just sent a PR adding a comment to try to clarify this.  Please feel free to comment on this PR if anything is still unclear: https://github.com/NixOS/nixpkgs/pull/76912.

As for `gi-gdkx11`, there isn't a good way to default to an older version of a package that is not on Stackage.  I'd urge you to try to get upstream to the package into Stackage so that we don't have to necessarily do anything here in nixpkgs.

If you wanted to explicitly generate an older version of a package, you can add it to this list: https://github.com/NixOS/nixpkgs/blob/8a4d94c5afbfa218609f62da7fc8185214336a52/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L2494

**Comment by peti** [comment]
> The `default-package-overrides` section is generated semi-automatically and shouldn't be added to by hand.

Note that you *can* edit `default-package-overrides` by hand. The code that generates part of that section from Stackage looks for the comment "# LTS Haskell" and replaces everything that follows it until the end of the section: https://github.com/NixOS/cabal2nix/blob/master/update-stackage.sh#L46-L54.

In other words, if you add manual overrides before that comment, then it should be fine.

**Comment by peti** [comment]
@mdorman, will you update this PR?

**Comment by peti** [comment]
Please feel free to submit an updated PR when the issues pointed out during review are fixed.

**Pull request closed without merging**
