### PR TITLE
python311Packages.azure-storage-blob: 12.17.0 -> 12.18.2 

### PR DESCRIPTION
**Pull request by fabaff**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 257923` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>46 packages failed to build:</summary>
  <ul>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.spacy-loggers.dist</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.wandb.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.wandb</li>
    <li>python311Packages.wandb.dist</li>
  </ul>
</details>
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>appdaemon</li>
    <li>appdaemon.dist</li>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
    <li>barman</li>
    <li>barman.dist</li>
    <li>baserow</li>
    <li>baserow.dist</li>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>python310Packages.adlfs</li>
    <li>python310Packages.adlfs.dist</li>
    <li>python310Packages.azure-storage-blob</li>
    <li>python310Packages.azure-storage-blob.dist</li>
    <li>python310Packages.django-storages</li>
    <li>python310Packages.django-storages.dist</li>
    <li>python310Packages.dvc-azure</li>
    <li>python310Packages.dvc-azure.dist</li>
    <li>python310Packages.fuzzytm</li>
    <li>python310Packages.fuzzytm.dist</li>
    <li>python310Packages.gensim</li>
    <li>python310Packages.gensim.dist</li>
    <li>python310Packages.kbcstorage</li>
    <li>python310Packages.kbcstorage.dist</li>
    <li>python310Packages.natasha</li>
    <li>python310Packages.natasha.dist</li>
    <li>python310Packages.navec</li>
    <li>python310Packages.navec.dist</li>
    <li>python310Packages.pathy</li>
    <li>python310Packages.pathy.dist</li>
    <li>python310Packages.ray</li>
    <li>python310Packages.ray.dist</li>
    <li>python310Packages.slovnet</li>
    <li>python310Packages.slovnet.dist</li>
    <li>python310Packages.smart-open</li>
    <li>python310Packages.smart-open.dist</li>
    <li>python311Packages.adlfs</li>
    <li>python311Packages.adlfs.dist</li>
    <li>python311Packages.azure-storage-blob</li>
    <li>python311Packages.azure-storage-blob.dist</li>
    <li>python311Packages.django-storages</li>
    <li>python311Packages.django-storages.dist</li>
    <li>python311Packages.dvc-azure</li>
    <li>python311Packages.dvc-azure.dist</li>
    <li>python311Packages.fuzzytm</li>
    <li>python311Packages.fuzzytm.dist</li>
    <li>python311Packages.gensim</li>
    <li>python311Packages.gensim.dist</li>
    <li>python311Packages.kbcstorage</li>
    <li>python311Packages.kbcstorage.dist</li>
    <li>python311Packages.natasha</li>
    <li>python311Packages.natasha.dist</li>
    <li>python311Packages.navec</li>
    <li>python311Packages.navec.dist</li>
    <li>python311Packages.pathy</li>
    <li>python311Packages.pathy.dist</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python311Packages.slovnet</li>
    <li>python311Packages.slovnet.dist</li>
    <li>python311Packages.smart-open</li>
    <li>python311Packages.smart-open.dist</li>
    <li>snakemake</li>
    <li>snakemake.dist</li>
    <li>tandoor-recipes</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 257923` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
  </ul>
</details>
<details>
  <summary>26 packages failed to build:</summary>
  <ul>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.spacy-loggers.dist</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.wandb.dist</li>
  </ul>
</details>
<details>
  <summary>89 packages built:</summary>
  <ul>
    <li>appdaemon</li>
    <li>appdaemon.dist</li>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
    <li>barman</li>
    <li>barman.dist</li>
    <li>baserow</li>
    <li>baserow.dist</li>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>python310Packages.adlfs</li>
    <li>python310Packages.adlfs.dist</li>
    <li>python310Packages.azure-storage-blob</li>
    <li>python310Packages.azure-storage-blob.dist</li>
    <li>python310Packages.django-storages</li>
    <li>python310Packages.django-storages.dist</li>
    <li>python310Packages.dvc-azure</li>
    <li>python310Packages.dvc-azure.dist</li>
    <li>python310Packages.fuzzytm</li>
    <li>python310Packages.fuzzytm.dist</li>
    <li>python310Packages.gensim</li>
    <li>python310Packages.gensim.dist</li>
    <li>python310Packages.kbcstorage</li>
    <li>python310Packages.kbcstorage.dist</li>
    <li>python310Packages.natasha</li>
    <li>python310Packages.natasha.dist</li>
    <li>python310Packages.navec</li>
    <li>python310Packages.navec.dist</li>
    <li>python310Packages.pathy</li>
    <li>python310Packages.pathy.dist</li>
    <li>python310Packages.ray</li>
    <li>python310Packages.ray.dist</li>
    <li>python310Packages.slovnet</li>
    <li>python310Packages.slovnet.dist</li>
    <li>python310Packages.smart-open</li>
    <li>python310Packages.smart-open.dist</li>
    <li>python311Packages.adlfs</li>
    <li>python311Packages.adlfs.dist</li>
    <li>python311Packages.azure-storage-blob</li>
    <li>python311Packages.azure-storage-blob.dist</li>
    <li>python311Packages.django-storages</li>
    <li>python311Packages.django-storages.dist</li>
    <li>python311Packages.dvc-azure</li>
    <li>python311Packages.dvc-azure.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.fuzzytm</li>
    <li>python311Packages.fuzzytm.dist</li>
    <li>python311Packages.gensim</li>
    <li>python311Packages.gensim.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.kbcstorage</li>
    <li>python311Packages.kbcstorage.dist</li>
    <li>python311Packages.natasha</li>
    <li>python311Packages.natasha.dist</li>
    <li>python311Packages.navec</li>
    <li>python311Packages.navec.dist</li>
    <li>python311Packages.pathy</li>
    <li>python311Packages.pathy.dist</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.slovnet</li>
    <li>python311Packages.slovnet.dist</li>
    <li>python311Packages.smart-open</li>
    <li>python311Packages.smart-open.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.wandb</li>
    <li>python311Packages.wandb.dist</li>
    <li>snakemake</li>
    <li>snakemake.dist</li>
    <li>tandoor-recipes</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Comment by AkechiShiro** [comment]
Hi @fabaff, thanks for your work, how can we help fix the 26 packages which are broken, is there any way to get more information why they're build fails exactly ?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 257923` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
  </ul>
</details>
<details>
  <summary>30 packages failed to build:</summary>
  <ul>
    <li>baserow</li>
    <li>baserow.dist</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.spacy-loggers.dist</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.wandb.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>85 packages built:</summary>
  <ul>
    <li>appdaemon</li>
    <li>appdaemon.dist</li>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
    <li>barman</li>
    <li>barman.dist</li>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>python310Packages.adlfs</li>
    <li>python310Packages.adlfs.dist</li>
    <li>python310Packages.azure-storage-blob</li>
    <li>python310Packages.azure-storage-blob.dist</li>
    <li>python310Packages.django-storages</li>
    <li>python310Packages.django-storages.dist</li>
    <li>python310Packages.dvc-azure</li>
    <li>python310Packages.dvc-azure.dist</li>
    <li>python310Packages.fuzzytm</li>
    <li>python310Packages.fuzzytm.dist</li>
    <li>python310Packages.gensim</li>
    <li>python310Packages.gensim.dist</li>
    <li>python310Packages.kbcstorage</li>
    <li>python310Packages.kbcstorage.dist</li>
    <li>python310Packages.natasha</li>
    <li>python310Packages.natasha.dist</li>
    <li>python310Packages.navec</li>
    <li>python310Packages.navec.dist</li>
    <li>python310Packages.pathy</li>
    <li>python310Packages.pathy.dist</li>
    <li>python310Packages.ray</li>
    <li>python310Packages.ray.dist</li>
    <li>python310Packages.slovnet</li>
    <li>python310Packages.slovnet.dist</li>
    <li>python310Packages.smart-open</li>
    <li>python310Packages.smart-open.dist</li>
    <li>python311Packages.adlfs</li>
    <li>python311Packages.adlfs.dist</li>
    <li>python311Packages.azure-storage-blob</li>
    <li>python311Packages.azure-storage-blob.dist</li>
    <li>python311Packages.django-storages</li>
    <li>python311Packages.django-storages.dist</li>
    <li>python311Packages.dvc-azure</li>
    <li>python311Packages.dvc-azure.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.fuzzytm</li>
    <li>python311Packages.fuzzytm.dist</li>
    <li>python311Packages.gensim</li>
    <li>python311Packages.gensim.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.kbcstorage</li>
    <li>python311Packages.kbcstorage.dist</li>
    <li>python311Packages.natasha</li>
    <li>python311Packages.natasha.dist</li>
    <li>python311Packages.navec</li>
    <li>python311Packages.navec.dist</li>
    <li>python311Packages.pathy</li>
    <li>python311Packages.pathy.dist</li>
    <li>python311Packages.ray</li>
    <li>python311Packages.ray.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.slovnet</li>
    <li>python311Packages.slovnet.dist</li>
    <li>python311Packages.smart-open</li>
    <li>python311Packages.smart-open.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.wandb</li>
    <li>python311Packages.wandb.dist</li>
    <li>snakemake</li>
    <li>snakemake.dist</li>
    <li>tandoor-recipes</li>
  </ul>
</details>

**Comment by jonringer** [comment]
looks like the build failures went away:

```
https://github.com/NixOS/nixpkgs/pull/257923

4 packages marked as broken and skipped:
python310Packages.dalle-mini python310Packages.dalle-mini.dist python311Packages.dalle-mini python311Packages.dalle-mini.dist

115 packages built:
appdaemon appdaemon.dist azure-cli azure-cli.dist barman barman.dist baserow baserow.dist browsr browsr.dist dvc-with-remotes dvc-with-remotes.dist openai-full openai-full.dist pentestgpt pentestgpt.dist python310Packages.adlfs python310Packages.adlfs.dist python310Packages.azure-storage-blob python310Packages.azure-storage-blob.dist python310Packages.django-storages python310Packages.django-storages.dist python310Packages.dvc-azure python310Packages.dvc-azure.dist python310Packages.fastai python310Packages.fastai.dist python310Packages.fuzzytm python310Packages.fuzzytm.dist python310Packages.gensim python310Packages.gensim.dist python310Packages.k-diffusion python310Packages.k-diffusion.dist python310Packages.kbcstorage python310Packages.kbcstorage.dist python310Packages.langchain python310Packages.langchain.dist python310Packages.natasha python310Packages.natasha.dist python310Packages.navec python310Packages.navec.dist python310Packages.pathy python310Packages.pathy.dist python310Packages.ray python310Packages.ray.dist python310Packages.skrl python310Packages.skrl.dist python310Packages.slovnet python310Packages.slovnet.dist python310Packages.smart-open python310Packages.smart-open.dist python310Packages.spacy python310Packages.spacy-loggers python310Packages.spacy-loggers.dist python310Packages.spacy-lookups-data python310Packages.spacy-lookups-data.dist python310Packages.spacy-transformers python310Packages.spacy-transformers.dist python310Packages.spacy.dist python310Packages.textacy python310Packages.textacy.dist python310Packages.textnets python310Packages.textnets.dist python310Packages.wandb python310Packages.wandb.dist python311Packages.adlfs python311Packages.adlfs.dist python311Packages.azure-storage-blob python311Packages.azure-storage-blob.dist python311Packages.django-storages python311Packages.django-storages.dist python311Packages.dvc-azure python311Packages.dvc-azure.dist python311Packages.fastai python311Packages.fastai.dist python311Packages.fuzzytm python311Packages.fuzzytm.dist python311Packages.gensim python311Packages.gensim.dist python311Packages.k-diffusion python311Packages.k-diffusion.dist python311Packages.kbcstorage python311Packages.kbcstorage.dist python311Packages.natasha python311Packages.natasha.dist python311Packages.navec python311Packages.navec.dist python311Packages.pathy python311Packages.pathy.dist python311Packages.ray python311Packages.ray.dist python311Packages.skrl python311Packages.skrl.dist python311Packages.slovnet python311Packages.slovnet.dist python311Packages.smart-open python311Packages.smart-open.dist python311Packages.spacy python311Packages.spacy-loggers python311Packages.spacy-loggers.dist python311Packages.spacy-lookups-data python311Packages.spacy-lookups-data.dist python311Packages.spacy-transformers python311Packages.spacy-transformers.dist python311Packages.spacy.dist python311Packages.textacy python311Packages.textacy.dist python311Packages.textnets python311Packages.textnets.dist python311Packages.wandb python311Packages.wandb.dist snakemake snakemake.dist tandoor-recipes tts tts.dist
```

**Pull request merged**
