### PR TITLE
dpkg: 1.18.24 -> 1.19.0.4

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Upstream minor release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by NeQuissimus — CHANGES_REQUESTED** [review]
Some of the outputs need but can't find each other:

```bash
/nix/store/jazikx4cvas6xld7x3x4vvqpp9jf3nd7-dpkg-1.19.0.4
[nix] ~/nixpkgs pr-30854 λ ./result/bin/dpkg --status
dpkg: error: unable to execute dpkg-query (dpkg-query): No such file or directory
```

**Comment by adisbladis** [comment]
@NeQuissimus I think this was always a problem when accessing binaries through store-paths rather than through `nix-shell` or in `systemPackages` that sets up `$PATH`.
I'll see what we can do about patching the external process calls.

**Comment by adisbladis** [comment]
Luckily all of these commands are defined in a header file so it was pretty easy to patch :)

**Comment by NeQuissimus** [comment]
Thanks :)

**Pull request merged**
