### PR TITLE
kde-applications: 17.08.3 -> 17.12.0

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Currently building here so will use it as daily driver it for a day or two and if all ok, merge to master.

Follow-up to #31448.

Cc: @adisbladis @bkchr @ttuegel 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gnidorah** [comment]
@peterhoeg Kdelibs is no more. So when doing `nix-shell -p nox --run "nox-review wip"`
```
error: attribute ‘kdelibs’ missing, at /home/gnidorah/tmp/nixpkgs/pkgs/applications/kde/default.nix:41:16
```
Perhaps you should remove all traces of kdelibs and mark packages using it as broken.

**Comment by ttuegel** [comment]
> Perhaps you should remove all traces of kdelibs and fix packages using it (whatever is appropriate: build without kdelibs, mark as broken or even drop)

Any package that still refers to kdelibs should be dropped. We warned everyone 8 months ago that this was going to happen.

**Comment by peterhoeg** [comment]
So this needs a bit of work and as I'll only be able to do that on the weekend, anyone else should please feel free to jump on this if you want.

**Comment by gnidorah** [comment]
@peterhoeg Sure. Check https://github.com/peterhoeg/nixpkgs/pull/1 for progress.

**Comment by gnidorah** [comment]
@peterhoeg Done https://github.com/peterhoeg/nixpkgs/pull/1

**Comment by peterhoeg** [comment]
I'm currently building this merge at the moment to try it out. Once again, thanks a lot @gnidorah for all your work!

**Comment by peterhoeg** [comment]
Working great here. @ttuegel, do you want this to go to staging first or we merge straight to master?

**Comment by ttuegel** [comment]
Straight into master.

**Review by ttuegel — APPROVED** [review]

**Comment by gnidorah** [comment]
@peterhoeg Thanks!

**Pull request merged**
