### PR TITLE
Fix grub for "nodev" targets.

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by wkennington** [comment]
Realistically this should be a value of neither for it to make sense logically. It should give you the same behavior and even prevent any attempted installations of grub for nodev. Unless there is a case where a device is detected and neither of the targets are specified.

**Comment by ts468** [comment]
@wkennington, thanks for the review, I've changed the return value according to your suggestion!

**Comment by lethalman** [comment]
Thanks a lot for the quick response. Works for me. Is it ready to merge?

**Comment by wkennington** [comment]
LGTM

**Comment by lethalman** [comment]
Merged thanks.

**Pull request merged**
