### PR TITLE
Influxdb{2}: fix build with Rust1.83 compat

### PR DESCRIPTION
**Pull request by gador**
Fix current build issue (https://hydra.nixos.org/build/281927328/nixlog/3):

```
   Compiling flux-core v0.154.0 (/build/source/libflux/flux-core)
error: elided lifetime has a name
   --> flux-core/src/ast/walk/mod.rs:183:47
    |
181 | impl<'a> Node<'a> {
    |      -- lifetime `'a` declared here
182 |     #[allow(missing_docs)]
183 |     pub fn from_expr(expr: &'a Expression) -> Node {
    |                                               ^^^^ this elided lifetime gets resolved as `'a`
    |
note: the lint level is defined here
   --> flux-core/src/lib.rs:1:38
    |
1   | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
    |                                      ^^^^^^^^
    = note: `#[deny(elided_named_lifetimes)]` implied by `#[deny(warnings)]`

error: elided lifetime has a name
  --> flux-core/src/parser/mod.rs:44:37
   |
42 | impl<'input> Parser<'input> {
   |      ------ lifetime `'input` declared here
43 |     /// Instantiates a new parser with the given string as input.
44 |     pub fn new(src: &'input str) -> Parser {
   |                                     ^^^^^^ this elided lifetime gets resolved as `'input`

error: could not compile `flux-core` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `flux-core` (lib) due to 2 previous errors
```

fix from https://github.com/influxdata/flux/pull/5516

Also need to disable errors on missing docs

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12495667611

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12495667611


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368122`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>influxdb</li>
    <li>influxdb2</li>
    <li>influxdb2-server</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368122`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>influxdb</li>
    <li>influxdb2</li>
    <li>influxdb2-server</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368122`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>influxdb</li>
    <li>influxdb2</li>
    <li>influxdb2-server</li>
  </ul>
</details>

**Comment by gador** [comment]
`nixosTests.influxdb2` and `nixosTests.influxbd` pass, too

**Comment by girlmaya** [comment]
Will this be backported?

**Comment by lucasew** [comment]
I asked the bot to make the PR

**Comment by girlmaya** [comment]
Thank you

**Pull request merged**
