### PR TITLE
Update mattermost to 5.24.1

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
So I can migrate my server to nixos

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by evils** [comment]
this should close #82172?
that does change the module, but the reason for this is not explained

**Review by mdlayher — COMMENTED** [review]
Please see https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md for the commit message format and such:

```
mattermost: 5.15.0 -> 5.24.1
```

In addition, what's up with the formatting changes? nixfmt?

**Comment by gregf** [comment]
Yes nixfmt, I'll fix the PR soon.

**Review by ali-abrar — COMMENTED** [review]
This is below the [minimum version recommended by mattermost](https://docs.mattermost.com/administration/extended-support-release.html).

**Comment by ryantm** [comment]
We're past this version now. Thanks.

**Pull request closed without merging**
