### PR TITLE
unifiStable: 5.14.23 -> 6.0.43

### PR DESCRIPTION
**Pull request by elseym**
###### Motivation for this change
- update the unifi controller to the latest version. see [changelog](https://community.ui.com/releases/UniFi-Network-Controller-6-0-43/b28bb453-927a-4dd8-82f7-40af28505510).
- remove `unifiBeta` because there is no publicly available beta version of this software

###### Things done
- package software version 6.x as `unifi6`
- package software version 5.x as `unifi5`
- alias `unifi6` as `unifi` and `unifiStable` for backward compatibility
(see discussion for details)

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by elseym** [comment]
@Patryk27 @lukegb @petabyteboy since you participated in previos PRs regarding this package: is it ok for you if we remove `unifiBeta` in order to not maintain a package for a non-public beta version of an unfree piece of software?

**Comment by Patryk27** [comment]
@elseym: sure - if 6.0 hit stable, then imho there's no point in keeping that beta version around anymore :-)

**Comment by petabyteboy** [comment]
6.0 was declared stable a while ago already. I'm okay with changing the names. Some people I know will not be happy about the 5.14.x branch being dropped, but that's Ubnt's decision and not ours.

**Comment by Patryk27** [comment]
> Some people I know will not be happy about the 5.14.x branch being dropped, but that's Ubnt's decision and not ours.

If there are important changes in-between, maybe we could provide `unifi5` that's pinned to `5.14.23`? (same way there's a separate package for `python27` + `python3`)

**Comment by SuperSandro2000** [comment]
Please adjust all-packages.nix to fix the eval error.

**Comment by petabyteboy** [comment]
Can you put the `unifiStable = unifi6` in pkgs/top-level/aliases.nix instead? This will make sure it's not used in nixpkgs itself anymore.

**Comment by elseym** [comment]
thanks for your input. :smile: 

i could not find any information about possible LTS bumps from upstream, afaics 5.6.x is still LTS. i also don't know whether upstream plans to further support the 5.x branch apart from the (really old) LTS release.
the only other current release seems to be 6.0.x, which imho we should maintain as `unifiStable` (possibly rename it to `unifi` for the next release?).
i added a second commit renaming the packages. could this be an appropriate solution?

**Pull request merged**
