### PR TITLE
elasticsearchPlugins: add ingest-attachment

### PR DESCRIPTION
**Pull request by ashkitten**
###### Motivation for this change

needed for using elasticsearch for full text search in nextcloud (https://github.com/nextcloud/fulltextsearch_elasticsearch/wiki). tested it briefly to make sure it works in my use-case.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @offlinehacker

### CODE REVIEW

**Comment by ashkitten** [comment]
so, i realized that this fails with `error: unsupported version 6.8.3 for plugin ingest-attachment` since i rebased it onto master from 19.03... but all of the plugins have the same version for 6.8.3, so they're all broken since https://github.com/NixOS/nixpkgs/commit/3ab433df342c4196a8210fa631ceece9096a445b. shall i fix them in this pull request?

**Comment by offlinehacker** [comment]
I'm not sure who uses them, I was using them when I was still using es on nixos. Can you please update them, looks like someone forgot to update plugins when updating es? Can you also please add comment to elasticsearch that plugins needs to be updated when updating package?

**Comment by ashkitten** [comment]
no problem. i'll also remove the 5.x versions since elasticsearch 5.x has been removed. also, i noticed that some of the plugins use `pkgs.fetchurl` instead of `fetchurl` directly so i'll change those.

**Comment by ashkitten** [comment]
i've pushed some style fixups and stuff as well. if a reviewer wants those split out of this pr i'd be happy to do so.

**Comment by offlinehacker** [comment]
looks good to me lgtm

**Comment by offlinehacker** [comment]
Btw @ashkitten have you tested this with nixos module with latest elasticsearch? Does it work well?

**Comment by ashkitten** [comment]
i've tested it with default elasticsearch and it works for my use case, at least.

**Pull request merged**
