### PR TITLE
go: propagate the apple sdk

### PR DESCRIPTION
**Pull request by zowoq**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
It might be best to hold off on this for now unless there's a pressing need, as the upcoming SDK rework is likely to change this interface again (to something much simpler, thankfully).

**Comment by reckenrode** [comment]
To add some detail and background: `overrideSDK` was added at literally the last minute to 23.11. I had to add it during the final staging-next cycle to fix curl because otherwise it was going to break things propagating frameworks. That version was incomplete. I improved it for 24.05, but I realized during that work it would not be possible to implement it generally. In particular, anything that is a dependency but not an input is invisible to it (e.g., in a hook or a file or a string).

The Darwin refactor will turn the SDK into a normal package. If you need the 11.x SDK, you add `apple-sdk_11` as a build input. If your package exposes the SDK as part of its public API, you can propagate it. This will all work as expected for a normal package. If you need to set the deployment target, you will be able to use `darwinDeploymentTargetHook` to do that.

Another aspect of this is I am reworking how SDKs are built. I have the 10.12 through 14.4 SDKs in my WIP branch. They all build, and they all have source-based components. There’s not going to be a difference in SDKs between Darwin platforms other than what’s available. `xcrun` will also be available in the stdenv, pointing the nixpkg SDK and binaries.

I have a very WIP branch available at https://github.com/reckenrode/nixpkgs/tree/darwin-sdk-refactor. It’s very messy (because I’m using an adapter right now to avoid stdenv bootstraps), but the core of it works. I have successfully built Wine, MoltenVK, RPM, xcbuild, and btop with appropriate SDKs. It’s very unlikely this will land for the next staging-next cycle (because I still have to sort out bootstrapping the stdenv), but it may the one after that, and it will definitely be in 24.11.

**Comment by reckenrode** [comment]
The new SDK stuff is at https://github.com/NixOS/nixpkgs/pull/346043. For Go’s purpose, you’ll want to propagate the minimum SDK and deployment target like I did for Swift in https://github.com/NixOS/nixpkgs/pull/346947.

**Comment by reckenrode** [comment]
If you don’t mind, I added this PR to the follow up tracking list at https://github.com/NixOS/nixpkgs/pull/346043.

**Comment by zowoq** [comment]
@ofborg eval

**Comment by emilazy** [comment]
@ofborg eval

**Comment by emilazy** [comment]
Not sure why ofborg won’t eval. Can you try rebasing this on the latest `staging` to kick it into gear?

**Comment by zowoq** [comment]
Not much point waiting for ofborg, the eval queue is ~90.

**Pull request merged**
