### PR TITLE
python312Packages.sphinx-mdinclude: fix build, 0.6.1 -> 0.6.2

### PR DESCRIPTION
**Pull request by JulianFP**
This package was previously marked as broken because of a version mismatch between the version of mistune it required and the version of mistune nixpkgs provided. This has been resolved upstream since https://github.com/omnilib/sphinx-mdinclude/pull/46. 

Additionally this package also requires sphinx as an explicit dependency since https://github.com/omnilib/sphinx-mdinclude/pull/70 which I added. 

I also updated the package to its newest version while we are at it.

I added myself to the maintainers list since I'm willing to help take care of this package for a while.
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Could you change your commit messages and a PR title from `sphinx-mdinclude` to `python312Packages.sphinx-mdinclude` since this is a python library?

> Commit names of Python libraries should reflect that they are Python libraries, so write for example python311Packages.numpy: 1.11 -> 1.12. It is highly recommended to specify the current default version to enable automatic build by ofborg. Note that pythonPackages is an alias for python27Packages.

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines-contributing-guidelines

**Comment by JulianFP** [comment]
> Could you change your commit messages and a PR title from `sphinx-mdinclude` to `python312Packages.sphinx-mdinclude` since this is a python library?

sure thing, sorry for the oversight. It's changed now

**Review by Atemu — APPROVED** [review]
Diff LGTM and it evidently builds on ofBorg.

@flokli are you okay with @JulianFP adding themselves as a maintainer?

**Comment by JulianFP** [comment]
> @flokli are you okay with @JulianFP adding themselves as a maintainer?

I wrote @flokli an email to the address they specified in maintainer-list.nix on the 13th (over a week ago now). No response yet. I think this should be merged without hearing from them first, after all this unbreaks a package build and it would be great to have this in 24.11. If me adding myself to the maintainers list of this package is a problem then I could also just remove myself again....

**Comment by Atemu** [comment]
> it would be great to have this in 24.11

Btw, this PR would have qualified for a backport at any time, so there is no need to stress out about this.

**Comment by JulianFP** [comment]
> Btw, this PR would have qualified for a backport at any time, so there is no need to stress out about this.

yeah, you are right of course.

Thanks a lot for merging this!

**Pull request merged**
