### PR TITLE
photoqt: 4.2 -> 4.3

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

https://gitlab.com/lspies/photoqt/-/releases/v4.3

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — COMMENTED** [review]
1. Convert `cmakeFlags` to `lib.cmakeBool`s;
2. Why `-DIMAGEMAGICK` is off, while MAGICK_LOCATION was set?
3. what about setting MAGICK_LOCATION as  an `env`?

**Comment by wegank** [comment]
1. Done.
2. Because the package historically uses `graphicsmagick` instead.
3. Done.

**Review by AndersonTorres — COMMENTED** [review]
While trying to run after review, I found that error message - and no app opened:

```text
[nix-shell:~/.cache/nixpkgs-review/pr-292845]$ ./results/photoqt/bin/photoqt 
2024-03-06 10:32:04.760 [W] ::::0: QQmlApplicationEngine failed to load component
2024-03-06 10:32:04.760 [W] PQMainWindow.qml::::91: qrc:/src/qml/PQMainWindow.qml:91:5: Type PQImage unavailable
2024-03-06 10:32:04.760 [W] PQImage.qml::::486: qrc:/src/qml/image/PQImage.qml:486:33: Type PQFaceTagger unavailable
2024-03-06 10:32:04.760 [W] PQFaceTagger.qml::::67: qrc:/src/qml/image/PQFaceTagger.qml:67:9: Type PQMouseArea unavailable
2024-03-06 10:32:04.760 [W] PQMouseArea.qml::::4294967295: qrc:/src/qml/elements/PQMouseArea.qml: module "gtk2" is not installed
```

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 292845` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>photoqt</li>
  </ul>
</details>

**Comment by AndersonTorres** [comment]
```text
[nix-shell:~/.cache/nixpkgs-review/pr-292845-1]$ photoqt
2024-03-08 21:45:52.116 [C] pqc_settings.cpp::int PQCSettings::migrate(QString)::420: WARNING: The current version number needs to be added to the migrate() functions
2024-03-08 21:45:52.126 [C] pqc_shortcuts.cpp::bool PQCShortcuts::migrate(QString)::436: WARNING: The current version number needs to be added to the migrate() functions

PhotoQt v4.3
 > Validating configuration... 
2024-03-08 21:45:52.126 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::589: Error copying default db to tmp file
2024-03-08 21:45:52.126 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::595: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:45:52.126 [W] ::::0: QSqlQuery::exec: database not open
2024-03-08 21:45:52.126 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::602: Error getting list of tables: "No query Unable to fetch row"
 >> Failed: settings db
2024-03-08 21:45:52.146 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::286: Error copying default db to tmp file
2024-03-08 21:45:52.146 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::292: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:45:52.146 [W] ::::0: QSqlQuery::prepare: database not open
2024-03-08 21:45:52.146 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::299: Error getting default columns: "No query Unable to fetch row"
 >> Failed: imageformats db
2024-03-08 21:45:52.146 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsValues()::854: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:45:52.146 [W] ::::0: QSqlQuery::prepare: database not open
2024-03-08 21:45:52.146 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsValues()::860: Error getting default data: "No query Unable to fetch row"
 >> Failed: settings values
 >> Done!

2024-03-08 21:45:52.187 [W] ::::0: QQmlApplicationEngine failed to load component
2024-03-08 21:45:52.187 [W] PQMainWindow.qml::::91: qrc:/src/qml/PQMainWindow.qml:91:5: Type PQImage unavailable
2024-03-08 21:45:52.187 [W] PQImage.qml::::486: qrc:/src/qml/image/PQImage.qml:486:33: Type PQFaceTagger unavailable
2024-03-08 21:45:52.187 [W] PQFaceTagger.qml::::67: qrc:/src/qml/image/PQFaceTagger.qml:67:9: Type PQMouseArea unavailable
2024-03-08 21:45:52.187 [W] PQMouseArea.qml::::4294967295: qrc:/src/qml/elements/PQMouseArea.qml: module "gtk2" is not installed

```

**Comment by wegank** [comment]
Does `photoqt` on master work on your side?

**Comment by AndersonTorres** [comment]
Surprisingly, nope:

```nope
[anderson@hendrix:/tmp/0-PLAY]$ nix run --show-trace --print-build-logs /sources/0-PROJECTOS/nixpkgs/Local-Master#photoqt
2024-03-08 21:53:34.525 [C] pqc_settings.cpp::int PQCSettings::migrate(QString)::420: WARNING: The current version number needs to be added to the migrate() functions
2024-03-08 21:53:34.535 [C] pqc_shortcuts.cpp::bool PQCShortcuts::migrate(QString)::436: WARNING: The current version number needs to be added to the migrate() functions

PhotoQt v4.2
 > Validating configuration... 
2024-03-08 21:53:34.539 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::589: Error copying default db to tmp file
2024-03-08 21:53:34.539 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::595: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:53:34.539 [W] ::::0: QSqlQuery::exec: database not open
2024-03-08 21:53:34.539 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::602: Error getting list of tables: "No query Unable to fetch row"
 >> Failed: settings db
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::286: Error copying default db to tmp file
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::292: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:53:34.544 [W] ::::0: QSqlQuery::prepare: database not open
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::299: Error getting default columns: "No query Unable to fetch row"
 >> Failed: imageformats db
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsValues()::854: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:53:34.544 [W] ::::0: QSqlQuery::prepare: database not open
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsValues()::860: Error getting default data: "No query Unable to fetch row"
 >> Failed: settings values
 >> Done!

2024-03-08 21:53:34.586 [W] ::::0: QQmlApplicationEngine failed to load component
2024-03-08 21:53:34.586 [W] PQMainWindow.qml::::91: qrc:/src/qml/PQMainWindow.qml:91:5: Type PQImage unavailable
2024-03-08 21:53:34.586 [W] PQImage.qml::::478: qrc:/src/qml/image/PQImage.qml:478:33: Type PQFaceTagger unavailable
2024-03-08 21:53:34.586 [W] PQFaceTagger.qml::::67: qrc:/src/qml/image/PQFaceTagger.qml:67:9: Type PQMouseArea unavailable
2024-03-08 21:53:34.586 [W] PQMouseArea.qml::::4294967295: qrc:/src/qml/elements/PQMouseArea.qml: module "gtk2" is not installed
```

**Comment by AndersonTorres** [comment]
Nope, surprisingly:

```
[anderson@hendrix:/tmp/0-PLAY]$ nix run --show-trace --print-build-logs .#photoqt
2024-03-08 21:53:34.525 [C] pqc_settings.cpp::int PQCSettings::migrate(QString)::420: WARNING: The current version number needs to be added to the migrate() functions
2024-03-08 21:53:34.535 [C] pqc_shortcuts.cpp::bool PQCShortcuts::migrate(QString)::436: WARNING: The current version number needs to be added to the migrate() functions

PhotoQt v4.2
 > Validating configuration... 
2024-03-08 21:53:34.539 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::589: Error copying default db to tmp file
2024-03-08 21:53:34.539 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::595: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:53:34.539 [W] ::::0: QSqlQuery::exec: database not open
2024-03-08 21:53:34.539 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsDatabase()::602: Error getting list of tables: "No query Unable to fetch row"
 >> Failed: settings db
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::286: Error copying default db to tmp file
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::292: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:53:34.544 [W] ::::0: QSqlQuery::prepare: database not open
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateImageFormatsDatabase()::299: Error getting default columns: "No query Unable to fetch row"
 >> Failed: imageformats db
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsValues()::854: Error opening default database: "unable to open database file Error opening database"
2024-03-08 21:53:34.544 [W] ::::0: QSqlQuery::prepare: database not open
2024-03-08 21:53:34.544 [W] pqc_validate.cpp::bool PQCValidate::validateSettingsValues()::860: Error getting default data: "No query Unable to fetch row"
 >> Failed: settings values
 >> Done!

2024-03-08 21:53:34.586 [W] ::::0: QQmlApplicationEngine failed to load component
2024-03-08 21:53:34.586 [W] PQMainWindow.qml::::91: qrc:/src/qml/PQMainWindow.qml:91:5: Type PQImage unavailable
2024-03-08 21:53:34.586 [W] PQImage.qml::::478: qrc:/src/qml/image/PQImage.qml:478:33: Type PQFaceTagger unavailable
2024-03-08 21:53:34.586 [W] PQFaceTagger.qml::::67: qrc:/src/qml/image/PQFaceTagger.qml:67:9: Type PQMouseArea unavailable
2024-03-08 21:53:34.586 [W] PQMouseArea.qml::::4294967295: qrc:/src/qml/elements/PQMouseArea.qml: module "gtk2" is not installed
```

**Comment by wegank** [comment]
So this is not a regression of the PR. Which desktop environment does the failure occur on?

**Comment by AndersonTorres** [comment]
I am using Mate. Maybe this is a GNOME-related thing (`module "gtk2" is not installed`).

**Comment by wegank** [comment]
I was using GNOME Wayland. Now that I have MATE installed, it still works...

Capture d’écran 2024-03-13 à 20 32 44

**Comment by AndersonTorres** [comment]
OK, then. 
It should be an issue on my machine - let's ignore for now.

**Review by AndersonTorres — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build photoqt

**Pull request merged**
