### PR TITLE
mixRelease: add flag for stripping debug from BEAM files

### PR DESCRIPTION
**Pull request by NobbZ**
###### Description of changes

Before there was a danger that references have been kept to big closures without
any strong production need for them.

This PR changes `mixRelease` in a way that by default debugging related information
is stripped from the compiled BEAM artifacts.

An assertion makes sure that we can not request to build with debug symbols available,
but request stripping at the same time.

A previous attempt to fix closure sizes has been made as #191200, though this
solution has been considered more practical than rewriting a binary file by tools
foreign to the target ecosystem.

In theory, it should be possible to now also (conditionally) add `erlang` as a
`disallowedReferences`.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

##### `nixpkgs-review`

```
1 package marked as broken and skipped:
pleroma-otp

1 package failed to build:
plausible

2 packages built:
elixir_ls pleroma
```

Plausible failed already before

### CODE REVIEW

**Comment by NobbZ** [comment]
As ofBorg did not assign any reviewers for this, I'll ping who I see in the files blame…

* @happysalada 
* @yu-re-ka 
* @smaximov

**Comment by happysalada** [comment]
This looks good. Let's merge and keep vigilant just in case anyone reports breakage of something.
Thank you for this!

**Comment by erictapen** [comment]
This change turned out to be the culprit of a bug I've been hunting for half a year now: https://framagit.org/framasoft/mobilizon/-/issues/1169

Unfortunately it created extremely cryptic error messages, so that I only by accident discovered the relation to this flag. (I considered bisecting, but never went through with it). For future search engine users this is an excerpt from the log:

```
vm-test-run-mobilizon> server # [   63.635929] systemd[1]: Started Mobilizon federated organization and mobilization platform.
vm-test-run-mobilizon> server # [   63.646999] systemd[1]: Reached target Multi-User System.
vm-test-run-mobilizon> server # [   63.653068] systemd[1]: Startup finished in 5.509s (kernel) + 58.140s (userspace) = 1min 3.649s.
vm-test-run-mobilizon> (finished: waiting for unit mobilizon.service, in 65.16 seconds)
vm-test-run-mobilizon> server: waiting for TCP port 41395
vm-test-run-mobilizon> server # [   73.266810] mobilizon[1324]: 18:09:16.359 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
vm-test-run-mobilizon> server # [   73.575061] mobilizon[1324]: 18:09:16.667 [info] Source for database :city not found: "/var/lib/mobilizon/geo/GeoLite2-City.mmdb"
vm-test-run-mobilizon> server # [   73.917622] mobilizon[1324]: 18:09:17.005 [info] Running Mobilizon.Web.Endpoint with cowboy 2.9.0 at ::1:41395 (http)
vm-test-run-mobilizon> server # [   73.965820] mobilizon[1324]: 18:09:17.058 [info] Access Mobilizon.Web.Endpoint at https://acme.test
vm-test-run-mobilizon> server # [   74.012525] mobilizon[1324]: 18:09:17.103 [notice] Application mobilizon exited: Mobilizon.start(:normal, []) returned an error: shutdown: failed to start child: :cache_ics
vm-test-run-mobilizon> server # [   74.015675] mobilizon[1324]:     ** (EXIT) :invalid_hook
vm-test-run-mobilizon> server # [   75.579636] mobilizon[1324]: {"Kernel pid terminated",application_controller,"{application_start_failure,mobilizon,{{shutdown,{failed_to_start_child,cache_ics,invalid_hook}},{'Elixir.Mobilizon',start,[normal,[]]}}}"}
vm-test-run-mobilizon> server # [   75.589993] mobilizon[1324]: Kernel pid terminated (application_controller) ({application_start_failure,mobilizon,{{shutdown,{failed_to_start_child,cache_ics,invalid_hook}},{'Elixir.Mobilizon',start,[normal,[]]}}})
vm-test-run-mobilizon> server # [   75.599801] mobilizon[1324]:
vm-test-run-mobilizon> server # [   75.610997] mobilizon[1324]: Crash dump is being written to: erl_crash.dump...
vm-test-run-mobilizon> server # [   75.632736] systemd[1]: mobilizon.service: Main process exited, code=exited, status=1/FAILURE
vm-test-run-mobilizon> server # [   75.641682] systemd[1]: mobilizon.service: Failed with result 'exit-code'.
vm-test-run-mobilizon> server # [   75.646329] systemd[1]: mobilizon.service: Consumed 32.703s CPU time, no IO, received 566B IP traffic, sent 566B IP traffic.
vm-test-run-mobilizon> server # [   75.899413] systemd[1]: mobilizon.service: Scheduled restart job, restart counter is at 1.
vm-test-run-mobilizon> server # [   75.902414] systemd[1]: Stopped Mobilizon federated organization and mobilization platform.
vm-test-run-mobilizon> server # [   75.909915] systemd[1]: mobilizon.service: Consumed 32.703s CPU time, no IO, received 566B IP traffic, sent 566B IP traffic.

```

For once I think it would make sense default this to false, due to the hard to understand errors it can produce and as it also caused a similar problem in Pleroma and (apparently) Plausible.

In terms of avoiding this kind of situation in the future, the integration test of Pleroma would have indicated breakage.

**Comment by happysalada** [comment]
Nice find, happy to set the default to false with a comment as to why. Do you have time to make a PR ?

**Pull request merged**
