### PR TITLE
Ghc response fix

### LINKED ISSUE #11762: gcc-wrapper doesn't handle arguments specified in response files
According to https://gcc.gnu.org/wiki/Response_Files, `gcc` reads for every argument of the form `@path` the file `path` and inserts its contents in the command-line array as if those flags had been specified directly. This mechanism is supposed to be used to work around system limitations with regard to command-line length.

The Haskell compiler GHC has [picked up the habit of using those response files](https://github.com/ghc/ghc/commit/296bc70b5ff6c853f2782e9ec5aa47a52110345e) for all its linker arguments, and it's now broken on NixOS as a result, apparently because all kinds of "rpaths" are no longer provided correctly.

My theory is that before that patch, gcc-wrapper would catch the `-L/path/...` style arguments and handle them correctly, but now it no longer does, because those flags are hidden inside of a response file. Does that sound plausible?

Cc: @vcunat

### PR DESCRIPTION
**Pull request by corngood**
###### Motivation for this change

Fixes #11762

Also includes change from @peti to re-enable response files in ghc.

###### Things done

GCC just does primitive unquoting when reading response files, so something like `"-Wl,$ORIGIN"` will be interpreted differently than if it were passed on the command line.

This change just escapes all $ characters in the response file, so they don't get expanded.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by shlevy** [comment]
Please reopen against staging

**Comment by shlevy** [comment]
See http://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-in-bash-how-do-we-know-it

**Comment by corngood** [comment]
Rebased on staging.

@shlevy I suppose backticks could be escaped as well.  Is that what you mean?  I can't think of anything else that would be a problem.  When reading a response file, gcc interprets ', ", \, but not $, `.

**Comment by shlevy** [comment]
Yes, that's what I mean, thanks.

**Comment by shlevy** [comment]
I'm actually wondering if it wouldn't be better to write a new response file with our added args instead... would avoid this issue and potential too-long-command-line issues.

**Comment by peti** [comment]
> Please reopen against staging

Huh? Why staging? I'd prefer this patch to apply to master.

**Comment by shlevy** [comment]
This changes the cc wrapper

**Comment by corngood** [comment]
Writing a response file would help with command length issues (cygwin, maybe others?), but you'd still be interpreting the incoming response file incorrectly unless you deal with $ etc.

gcc actually seems to do this when invoking ld.  If gcc is given any response files, it use a temporary response file with _all_ of the ld args, regardless of length.

**Comment by corngood** [comment]
I guess my point is: writing a temporary response file a sensible idea that will help on platforms with command line limits, at the expense of making the wrapper more complex on all platforms.  Its the added complexity that made me wary of doing it.

**Comment by shlevy** [comment]
Can't you just append to the existing one instead of interpreting it? But yes I agree it's more complex.

**Comment by shlevy** [comment]
If response files could include each other somehow, that would be even better...

**Comment by shlevy** [comment]
I'm happy with either solution but worry we will be back here again in a few months :smile:

**Comment by corngood** [comment]
You can't just append because the wrapper actually drops/modifies arguments.  It also needs to be able to parse the response file properly either way.

Honestly with how complex and fragile the wrapper is, we'll probably be back here every few months regardless. :)

My suggestion is to take this change as-is for now.  Response files were broken in general until recently, so regressions are unlikely outside of ghc.

@peti Do you want to keep your ghc change as part of this, or leave it until later?  I confirmed that ghc (7103 and 801) builds, but I haven't tested it extensively because of the dependency hell unleashed by changing cc-wrapper.

**Comment by peti** [comment]
> This changes the cc wrapper.

Ah. I see.

**Pull request merged**
