### PR TITLE
fetchFromGitHub: fix fetchSubmodules when revision is not hexadecimal

### LINKED ISSUE #21620: nix-prefetch-git: too strict validation
## Issue description

```
    src = fetchFromGitHub {
      owner = "neutrinolabs";
      repo = "xrdp";
      rev = "v0.9.1";
      fetchSubmodules = true;
      sha256 = "1d5n81b8fl21g597aqlcy7d7c4889bcylxgrslw298z7bdjwya0g";
    };
```
does not pass [this validation](https://github.com/NixOS/nixpkgs/blame/47d0d3d46f5520fba39c5376ea5449d51f44635d/pkgs/build-support/fetchgit/nix-prefetch-git#L283) which permits only hex-digits in ```rev```.

```fetchSubmodules = true``` is important, it forces to use ```git``` instead of ```curl```

ping @zimbatm

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Fixes #21620

Both failed examples from #21620 work well now:
```nix
fetchFromGitHub {
  owner = "aerospike";
  repo = "aerospike-server";
  rev = "3.14.0.1";
  sha256 = "1kzkwvir9j9jdlwp8gi9p3wkv3qhbrn62x1mb1xlnrdc7rk32kyn";
  fetchSubmodules = true;
}
```
which failed with ```Bad commit hash or bad reference```

```nix
fetchFromGitHub {
  owner = "aerospike";
  repo = "aerospike-server";
  rev = "refs/tags/3.14.0.1";
  sha256 = "1kzkwvir9j9jdlwp8gi9p3wkv3qhbrn62x1mb1xlnrdc7rk32kyn";
  fetchSubmodules = true;
}
```
which failed with ```invalid character ‘/’ in name ‘aerospike-server-refs/tags/3.14.0.1-src’```

###### Things done
1. use the same ```urlToName``` for ```fetchgit``` and ```fetchFromGitHub``` to avoid producing nix store names containing forbidden characters (for example ```/```) by simplified implementation used in ```fetchFromGitHub``` (```"${repo}-${rev}-src"``` where ```rev``` could be ```"refs/tags/tagname"```).
2. do not fail when ```rev``` containing non-hexadecimal characters, try to interpret it as a tag name.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
github does not display the second commit in the PR branch at https://github.com/NixOS/nixpkgs/pull/26877/commits

all changes are here: https://github.com/NixOS/nixpkgs/compare/master...volth:fetchfromgithub-fix

**Comment by volth** [comment]
Actually, it could be applied without mass-rebuild if ```gitRepoToName``` would be compatible with ```fetchFromGitHub```'s "${repo}-${rev}-scr" in the cases which do not require escaping of forbidden symbols. Currently it is copy-pasted from ```fetchgit```'s which is less popular in nixpkgs, so all ```fetchFromGitHub``` are to rebuild.

**Comment by Mic92** [comment]
If you decide to keep as it is, please rebase the pull request against staging.

**Comment by volth** [comment]
Well, it is going to rebuild a bit less, but anyway a lot of packages.So I rebased it to staging.
Feel free to strip the last commit, it brought almost no value.

**Comment by dezgeg** [comment]
No, either this is no rebuild (since `fetchFromGitHub` is a fixed-output derivation), or that if this breaks hashes, all users of `fetchFromGitHub` need to be updated as well (which is a total nightmare).

**Comment by vcunat** [comment]
@dezgeg: I believe it changes some names.  It certainly is a large rebuild.

**Comment by vcunat** [comment]
Ah, right, hashes started to fail now on Hydra+staging.

**Comment by volth** [comment]
oops.
Seems it is time to write a script to recalc the hashes

**Comment by vcunat** [comment]
Changing too many hashes isn't very nice.  Maybe we would better restrict the change to the problematic cases...

**Comment by volth** [comment]
Isn't better to change ~500 hashes than to support different (and diverging) logic for ```fetchgit``` and ```fetchFromGitHub``` just to prevent changing the hashes?

**Comment by volth** [comment]
@vcunat please, try all 4 commits on staging. it should work how you proposed.

**Comment by vcunat** [comment]
Yes, I think so.  Instead of removing unsafe chars it *might* be good to replace them, but people will probably want to specify `name` explicitly if they care.

**Comment by vcunat** [comment]
Thank you!

**Comment by volth** [comment]
> Yes, I think so. Instead of removing unsafe chars it might be good to replace them, but people will probably want to specify name explicitly if they care.

Something like Č->CZ might have sense to be replaced, but so far the only bad char is '/'
BTW, explicit name is used in some nix packages with the only purpose to fix ```fetchSubmodules```, that should be cleaned up eventually.

**Pull request merged**
