### PR TITLE
deepin.deepin-screen-recorder:  unstable-2023-07-10 -> 6.0.6

### PR DESCRIPTION
**Pull request by wineee**
## Description of changes

https://github.com/linuxdeepin/deepin-screen-recorder/compare/e8ee1e8...f284ff1
```
/nix/store/qx1h6fm6s0pi3zx980bg2q1psvsg7qwd-ffmpeg-6.0-lib/lib/libavcodec.so: undefined symbol: avcodec_get_context_defaults3 fish: Job 1, 'deepin-screen-recorder' terminated by signal SIGSEGV (Address boundary error)
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by symphorien** [comment]
I still have the issue:
```
/nix/store/xkrglrvv4xhv505jbp195b0lclck02lm-ffmpeg-full-6.0-lib/lib/libavcodec.so: undefined symbol: avcodec_get_context_defaults3 Segmentation fault (core dumped)
```
Also can you add a comment in the derivation about the issue you fix by using ffmpeg-full?

**Comment by wineee** [comment]
avcodec_get_context_defaults3 from ffmpeg is deprecated，I'm not sure how the crash is triggered, but deepin-screen-recorder also works without ffmpeg

**Comment by wineee** [comment]
Fixed in https://github.com/linuxdeepin/deepin-screen-recorder/pull/447

**Comment by symphorien** [comment]
you are fetching a commit in a PR. if this PR is rebased (as suggested by the bot), the commit will get GC-ed by github and the patch will become a 404. I suggest we wait for the patch to be merged for some time.

**Comment by wineee** [comment]
crash on ffmpeg 6.0 fix in https://github.com/linuxdeepin/deepin-screen-recorder/pull/463

**Comment by symphorien** [comment]
I get a segmentation fault when clicking on the tray icon to stop screen recording

**Comment by wineee** [comment]
Works fine when ffmpeg not in `PATH`， When I installed ffmpeg 6, it crashed...

**Comment by wineee** [comment]
> I get a segmentation fault when clicking on the tray icon to stop screen recording

should fixed in 6.0.6

**Pull request merged**
