### PR TITLE
 gitversion: init at 5.12.0 

### PR DESCRIPTION
**Pull request by acesyde**
## Description of changes

Add [Gitversion.Tool](https://github.com/GitTools/GitVersion) to the nixpkgs 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Shawn8901** [comment]
Result of `nixpkgs-review pr 289799` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitversion</li>
  </ul>
</details>

**Review by Shawn8901 — APPROVED** [review]
lgtm, just dropped that short tested on a private repo, i can re-test on some work repos tomorrow where we also use gitversion in production

**edit:** as hint you might want to split the commits about adding yourself as maintainer and the package add and the commit message should follow the contribution guidelines (see https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions & https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)

sadly i can not dismiss my approval :(

**Comment by acesyde** [comment]
@Shawn8901 done

**Comment by Shawn8901** [comment]
Can you please switch the order of the commits so that you first add yourself as maintainer and then unit the package? Otherwise the first commit will throw eval errors on bisect or similar activity

**Comment by acesyde** [comment]
> Can you please switch the order of the commits so that you first add yourself as maintainer and then unit the package? Otherwise the first commit will throw eval errors on bisect or similar activity

Sorry, now it's done @Shawn8901

**Review by Shawn8901 — APPROVED** [review]

**Comment by iFreilicht** [comment]
I know you'd rather just get this merged, but I was wondering how I can test this package? I'm not very familiar with .NET, but the package built fine on my mac, and looking at the package it seems the platforms should rather be

```
    platforms = platforms.unix ++ platforms.windows;
```

I tried to just run it, but that didn't seem to work:

```
$ result/bin/dotnet-gitversion
zsh: killed     result/bin/dotnet-gitversion
```

**Comment by acesyde** [comment]
> I know you'd rather just get this merged, but I was wondering how I can test this package? I'm not very familiar with .NET, but the package built fine on my mac, and looking at the package it seems the platforms should rather be
> 
> ```
>     platforms = platforms.unix ++ platforms.windows;
> ```
> 
> I tried to just run it, but that didn't seem to work:
> 
> ```
> $ result/bin/dotnet-gitversion
> zsh: killed     result/bin/dotnet-gitversion
> ```

Hello, I don't understand why `platforms.windows` because currently Nix packages can't be installed directly into the os, just on a subsystem linux.

For the second part have try to execute it into a git repository ?

**Comment by Shawn8901** [comment]
> For the second part have try to execute it into a git repository ?
Yes, cwd in a git repo and execute git version. It will spit out a Semver based on your branches and commits. (So be specific it will spit out a bunch of different variants). How to calculate can be tuned by a configuration (but I see that out of scope for tests here as that is internal logic of gitversion)

**Comment by iFreilicht** [comment]
> Hello, I don't understand why `platforms.windows` because currently Nix packages can't be installed directly into the os, just on a subsystem linux.

nixpkgs itself has support for windows, including POSIX-compatible environments on Windows such as MinGW and Cygwin. The Nix Package Manager doesn't support windows officially yet, but [it is already possible to compile nix on windows and then build packages from nixpkgs with it](https://ternaris.com/lab/nix-on-windows.html#compiling-on-and-for-windows).

There is [ongoing work on Nix to support windows](https://github.com/NixOS/nix/labels/windows), so knowing which packages in nixpkgs *should* work on windows can be very useful for testing.

Of course, this is not required. It seems the package doesn't properly work without additional changes even on macOS, so I doubt it would "just work" on Windows as well.

> For the second part have try to execute it into a git repository ?

> cwd in a git repo and execute git version.

Yes, I tried it in multiple different repos, and got the same error every time. I found this in my system logs:

```
kernel: (AppleSystemPolicy) ASP: Security policy would not allow process: 26376, /nix/store/y25a08bdkd43qfwi4rgczz2r8iv2dkgg-dotnet-gitversion-5.12.0/lib/dotnet-gitversion/dotnet-gitversion
```

I found no results for this error in the discourse or matrix. So yeah, I'd say let's not get hung up on this and get this merged.

**Comment by acesyde** [comment]
> Of course, this is not required. It seems the package doesn't properly work without additional changes even on macOS, so I doubt it would "just work" on Windows as well.

Oh thanks for that, hope I can use nix pkgs on Windows someday

> (AppleSystemPolicy) ASP: Security policy would not allow process

Seems to be related to macos only with the [gatekeeper](https://developer.apple.com/forums/thread/706442), maybe you should allow the process before using it

**Comment by iFreilicht** [comment]
> Seems to be related to macos only with the [gatekeeper](https://developer.apple.com/forums/thread/706442), maybe you should allow the process before using it

Yeah I found out as much. That's not how gatekeeper works, unfortunately. You can't just whitelist the app. MacOS sees the app as broken/dangerous and that must be fixed on the developer side. I guess in our case the issue is one of the ones described in [the help article on how to resolve such problems](https://developer.apple.com/forums/thread/706379).

**Comment by acesyde** [comment]
> > Seems to be related to macos only with the [gatekeeper](https://developer.apple.com/forums/thread/706442), maybe you should allow the process before using it
> 
> Yeah I found out as much. That's not how gatekeeper works, unfortunately. You can't just whitelist the app. MacOS sees the app as broken/dangerous and that must be fixed on the developer side. I guess in our case the issue is one of the ones described in [the help article on how to resolve such problems](https://developer.apple.com/forums/thread/706379).

I'll try to fix it when my macbook arrives (in couple of weekds)

**Comment by Shawn8901** [comment]
isnt just merging it with just linux support right now an option and fix darwin support later? it could be also marked as broken for darwin in case its prefered to mark that it should be usable in theory but not yet working.

**Comment by iFreilicht** [comment]
Yes, absolutely! As I said multiple times, this is not a blocker. I'm just not in a position to merge this.

**Comment by Shawn8901** [comment]
yeah sure :slightly_smiling_face: . I did already approve the PR from my side 3 weeks ago and there is no change since then, and i already posted it on discourse to get some attention, so i dont see what i can do much more.

**Comment by Artturin** [comment]
Resolved conflict

**Pull request merged**
