### PR TITLE
Gnome extensions tophat pathfixes

### PR DESCRIPTION
**Pull request by lugeha**
## Description of changes

The tophat gnome extension needs a few more search path patches for gtop to get settings to work.

## Things done

- Built on platform(s)
  - [*] x86_64-linux

- [*] Tested basic functionality of all binary files (usually in `./result/bin/`)

Add path fixes to prefs.js and lib/shared.js

Options are now available again in the extension.

### CODE REVIEW

**Comment by piegamesde** [comment]
(How) does this interact with the GNOME 45 update?

**Comment by lugeha** [comment]
Does gnome45 change the behaviour of gjs?

**Comment by piegamesde** [comment]
Hi, GNOME 45 finally got merged. Could you please rebase and test again?

**Comment by lugeha** [comment]
Version in nixpkgs isn't even compatible, so... no?

**Comment by piegamesde** [comment]
As of last week, the extension supports Gnome 45 and got updated here in #270315.

**Comment by fernandocarletti** [comment]
Hi! I'm just onboarding on NixOS and had the issue as well. Is this ready to be merged? If not, is there an alternative to the fix? I'm not very familiar with Gnome Extensions but if there is a way I could help with some work on it I'd appreciate some guidance.

**Pull request closed without merging**
