### PR TITLE
linux/6.0: init

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

New upstream release.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Please update linuxPackages_latest.

**Comment by alyssais** [comment]
@OfBorg test latestKernel.login

**Comment by K900** [comment]
Result of `nixpkgs-review pr 194192` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>63 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.perf</li>
    <li>linuxKernel.packages.linux_4_14.perf</li>
    <li>linuxKernel.packages.linux_4_14_hardened.perf</li>
    <li>linuxKernel.packages.linux_4_19.perf</li>
    <li>linuxKernel.packages.linux_4_19_hardened.perf</li>
    <li>linuxKernel.packages.linux_4_9.perf</li>
    <li>linuxKernel.packages.linux_6_0.akvcam</li>
    <li>linuxKernel.packages.linux_6_0.ax99100</li>
    <li>linuxKernel.packages.linux_6_0.can-isotp</li>
    <li>linuxKernel.packages.linux_6_0.dpdk</li>
    <li>linuxKernel.packages.linux_6_0.dpdk-kmods</li>
    <li>linuxKernel.packages.linux_6_0.ena</li>
    <li>linuxKernel.packages.linux_6_0.intel-speed-select</li>
    <li>linuxKernel.packages.linux_6_0.ixgbevf</li>
    <li>linuxKernel.packages.linux_6_0.kvdo</li>
    <li>linuxKernel.packages.linux_6_0.mwprocapture</li>
    <li>linuxKernel.packages.linux_6_0.mxu11x0</li>
    <li>linuxKernel.packages.linux_6_0.ndiswrapper</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_6_0.nvidiabl</li>
    <li>linuxKernel.packages.linux_6_0.openafs</li>
    <li>linuxKernel.packages.linux_6_0.phc-intel</li>
    <li>linuxKernel.packages.linux_6_0.r8125</li>
    <li>linuxKernel.packages.linux_6_0.r8168</li>
    <li>linuxKernel.packages.linux_6_0.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_6_0.rtl8192eu</li>
    <li>linuxKernel.packages.linux_6_0.rtl8723bs</li>
    <li>linuxKernel.packages.linux_6_0.rtl88xxau-aircrack</li>
    <li>linuxKernel.packages.linux_6_0.sch_cake</li>
    <li>linuxKernel.packages.linux_6_0.tbs</li>
    <li>linuxKernel.packages.linux_6_0.vmware</li>
    <li>linuxKernel.packages.linux_6_0.zfs</li>
    <li>linuxKernel.packages.linux_6_0.zfsUnstable</li>
    <li>linuxKernel.packages.linux_latest_libre.akvcam</li>
    <li>linuxKernel.packages.linux_latest_libre.ax99100</li>
    <li>linuxKernel.packages.linux_latest_libre.can-isotp</li>
    <li>linuxKernel.packages.linux_latest_libre.dpdk</li>
    <li>linuxKernel.packages.linux_latest_libre.dpdk-kmods</li>
    <li>linuxKernel.packages.linux_latest_libre.ena</li>
    <li>linuxKernel.packages.linux_latest_libre.intel-speed-select</li>
    <li>linuxKernel.packages.linux_latest_libre.ixgbevf</li>
    <li>linuxKernel.packages.linux_latest_libre.kvdo</li>
    <li>linuxKernel.packages.linux_latest_libre.mwprocapture</li>
    <li>linuxKernel.packages.linux_latest_libre.mxu11x0</li>
    <li>linuxKernel.packages.linux_latest_libre.ndiswrapper</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidiabl</li>
    <li>linuxKernel.packages.linux_latest_libre.openafs</li>
    <li>linuxKernel.packages.linux_latest_libre.phc-intel</li>
    <li>linuxKernel.packages.linux_latest_libre.r8125</li>
    <li>linuxKernel.packages.linux_latest_libre.r8168</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8192eu</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8723bs</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl88xxau-aircrack</li>
    <li>linuxKernel.packages.linux_latest_libre.sch_cake</li>
    <li>linuxKernel.packages.linux_latest_libre.tbs</li>
    <li>linuxKernel.packages.linux_latest_libre.vmware</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs</li>
    <li>linuxKernel.packages.linux_latest_libre.zfsUnstable</li>
    <li>linux_6_0</li>
  </ul>
</details>
<details>
  <summary>22 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_0.apfs</li>
    <li>linuxKernel.packages.linux_6_0.broadcom_sta</li>
    <li>linuxKernel.packages.linux_6_0.evdi</li>
    <li>linuxKernel.packages.linux_6_0.lttng-modules</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_0.prl-tools</li>
    <li>linuxKernel.packages.linux_6_0.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_0.rtlwifi_new</li>
    <li>linuxKernel.packages.linux_6_0.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_latest_libre.apfs</li>
    <li>linuxKernel.packages.linux_latest_libre.broadcom_sta</li>
    <li>linuxKernel.packages.linux_latest_libre.evdi</li>
    <li>linuxKernel.packages.linux_latest_libre.lttng-modules</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.prl-tools</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8821ce</li>
    <li>linuxKernel.packages.linux_latest_libre.rtlwifi_new</li>
    <li>linuxKernel.packages.linux_latest_libre.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>152 packages built:</summary>
  <ul>
    <li>cargo-flamegraph</li>
    <li>linux-doc</li>
    <li>linux-manual</li>
    <li>linuxKernel.kernels.linux_6_0</li>
    <li>linuxKernel.kernels.linux_latest_libre</li>
    <li>linuxKernel.packages.linux_5_10.perf</li>
    <li>linuxKernel.packages.linux_5_10_hardened.perf</li>
    <li>linuxKernel.packages.linux_5_15.perf</li>
    <li>linuxKernel.packages.linux_hardened.perf (linuxKernel.packages.linux_5_15_hardened.perf)</li>
    <li>linuxKernel.packages.linux_5_19.perf</li>
    <li>linuxKernel.packages.linux_5_19_hardened.perf</li>
    <li>linuxKernel.packages.linux_5_4.perf</li>
    <li>linuxKernel.packages.linux_5_4_hardened.perf</li>
    <li>linuxKernel.packages.linux_6_0.acpi_call</li>
    <li>linuxKernel.packages.linux_6_0.amdgpu-pro</li>
    <li>linuxKernel.packages.linux_6_0.asus-ec-sensors</li>
    <li>linuxKernel.packages.linux_6_0.asus-wmi-sensors</li>
    <li>linuxKernel.packages.linux_6_0.batman_adv</li>
    <li>linuxKernel.packages.linux_6_0.bbswitch</li>
    <li>linuxKernel.packages.linux_6_0.chipsec</li>
    <li>linuxKernel.packages.linux_6_0.cpupower</li>
    <li>linuxKernel.packages.linux_6_0.cryptodev</li>
    <li>linuxKernel.packages.linux_6_0.ddcci-driver</li>
    <li>linuxKernel.packages.linux_6_0.dddvb</li>
    <li>linuxKernel.packages.linux_6_0.digimend</li>
    <li>linuxKernel.packages.linux_6_0.facetimehd</li>
    <li>linuxKernel.packages.linux_6_0.fwts-efi-runtime</li>
    <li>linuxKernel.packages.linux_6_0.gcadapter-oc-kmod</li>
    <li>linuxKernel.packages.linux_6_0.hid-ite8291r3</li>
    <li>linuxKernel.packages.linux_6_0.hid-nintendo</li>
    <li>linuxKernel.packages.linux_6_0.hyperv-daemons</li>
    <li>linuxKernel.packages.linux_6_0.isgx</li>
    <li>linuxKernel.packages.linux_6_0.it87</li>
    <li>linuxKernel.packages.linux_6_0.ithc</li>
    <li>linuxKernel.packages.linux_6_0.jool</li>
    <li>linuxKernel.packages.linux_6_0.kvmfr</li>
    <li>linuxKernel.packages.linux_6_0.liquidtux</li>
    <li>linuxKernel.packages.linux_6_0.mba6x_bl</li>
    <li>linuxKernel.packages.linux_6_0.mbp2018-bridge-drv</li>
    <li>linuxKernel.packages.linux_6_0.netatop</li>
    <li>linuxKernel.packages.linux_6_0.new-lg4ff</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_0.oci-seccomp-bpf-hook</li>
    <li>linuxKernel.packages.linux_6_0.openrazer</li>
    <li>linuxKernel.packages.linux_6_0.perf</li>
    <li>linuxKernel.packages.linux_6_0.ply</li>
    <li>linuxKernel.packages.linux_6_0.qc71_laptop</li>
    <li>linuxKernel.packages.linux_6_0.rr-zen_workaround</li>
    <li>linuxKernel.packages.linux_6_0.rtl8189es</li>
    <li>linuxKernel.packages.linux_6_0.rtl8189fs</li>
    <li>linuxKernel.packages.linux_6_0.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_0.rtl8814au</li>
    <li>linuxKernel.packages.linux_6_0.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_0.rtl8821cu</li>
    <li>linuxKernel.packages.linux_6_0.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_6_0.sysdig</li>
    <li>linuxKernel.packages.linux_6_0.system76</li>
    <li>linuxKernel.packages.linux_6_0.system76-acpi</li>
    <li>linuxKernel.packages.linux_6_0.system76-io</li>
    <li>linuxKernel.packages.linux_6_0.system76-power</li>
    <li>linuxKernel.packages.linux_6_0.systemtap</li>
    <li>linuxKernel.packages.linux_6_0.tmon</li>
    <li>linuxKernel.packages.linux_6_0.tp_smapi</li>
    <li>linuxKernel.packages.linux_6_0.turbostat</li>
    <li>linuxKernel.packages.linux_6_0.tuxedo-keyboard</li>
    <li>linuxKernel.packages.linux_6_0.usbip</li>
    <li>linuxKernel.packages.linux_6_0.v4l2loopback</li>
    <li>linuxKernel.packages.linux_6_0.v86d</li>
    <li>linuxKernel.packages.linux_6_0.veikk-linux-driver</li>
    <li>linuxKernel.packages.linux_6_0.vendor-reset</li>
    <li>linuxKernel.packages.linux_6_0.vhba</li>
    <li>linuxKernel.packages.linux_6_0.virtio_vmmci</li>
    <li>linuxKernel.packages.linux_6_0.virtualbox</li>
    <li>linuxKernel.packages.linux_6_0.vm-tools</li>
    <li>linuxKernel.packages.linux_6_0.vmm_clock</li>
    <li>linuxKernel.packages.linux_6_0.x86_energy_perf_policy</li>
    <li>linuxKernel.packages.linux_6_0.xone</li>
    <li>linuxKernel.packages.linux_6_0.xpadneo</li>
    <li>linuxKernel.packages.linux_6_0.zenpower</li>
    <li>linuxKernel.packages.linux_latest_libre.acpi_call</li>
    <li>linuxKernel.packages.linux_latest_libre.asus-ec-sensors</li>
    <li>linuxKernel.packages.linux_latest_libre.asus-wmi-sensors</li>
    <li>linuxKernel.packages.linux_latest_libre.batman_adv</li>
    <li>linuxKernel.packages.linux_latest_libre.bbswitch</li>
    <li>linuxKernel.packages.linux_latest_libre.chipsec</li>
    <li>linuxKernel.packages.linux_latest_libre.cpupower</li>
    <li>linuxKernel.packages.linux_latest_libre.cryptodev</li>
    <li>linuxKernel.packages.linux_latest_libre.ddcci-driver</li>
    <li>linuxKernel.packages.linux_latest_libre.dddvb</li>
    <li>linuxKernel.packages.linux_latest_libre.digimend</li>
    <li>linuxKernel.packages.linux_latest_libre.facetimehd</li>
    <li>linuxKernel.packages.linux_latest_libre.fwts-efi-runtime</li>
    <li>linuxKernel.packages.linux_latest_libre.gcadapter-oc-kmod</li>
    <li>linuxKernel.packages.linux_latest_libre.hid-ite8291r3</li>
    <li>linuxKernel.packages.linux_latest_libre.hid-nintendo</li>
    <li>linuxKernel.packages.linux_latest_libre.hyperv-daemons</li>
    <li>linuxKernel.packages.linux_latest_libre.isgx</li>
    <li>linuxKernel.packages.linux_latest_libre.it87</li>
    <li>linuxKernel.packages.linux_latest_libre.ithc</li>
    <li>linuxKernel.packages.linux_latest_libre.jool</li>
    <li>linuxKernel.packages.linux_latest_libre.kvmfr</li>
    <li>linuxKernel.packages.linux_latest_libre.liquidtux</li>
    <li>linuxKernel.packages.linux_latest_libre.mba6x_bl</li>
    <li>linuxKernel.packages.linux_latest_libre.mbp2018-bridge-drv</li>
    <li>linuxKernel.packages.linux_latest_libre.netatop</li>
    <li>linuxKernel.packages.linux_latest_libre.new-lg4ff</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.openrazer</li>
    <li>linuxKernel.packages.linux_latest_libre.perf</li>
    <li>linuxKernel.packages.linux_latest_libre.ply</li>
    <li>linuxKernel.packages.linux_latest_libre.qc71_laptop</li>
    <li>linuxKernel.packages.linux_latest_libre.rr-zen_workaround</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8189es</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8189fs</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8812au</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8814au</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8821au</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8821cu</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_latest_libre.sysdig</li>
    <li>linuxKernel.packages.linux_latest_libre.system76</li>
    <li>linuxKernel.packages.linux_latest_libre.system76-acpi</li>
    <li>linuxKernel.packages.linux_latest_libre.system76-io</li>
    <li>linuxKernel.packages.linux_latest_libre.systemtap</li>
    <li>linuxKernel.packages.linux_latest_libre.tmon</li>
    <li>linuxKernel.packages.linux_latest_libre.tp_smapi</li>
    <li>linuxKernel.packages.linux_latest_libre.turbostat</li>
    <li>linuxKernel.packages.linux_latest_libre.tuxedo-keyboard</li>
    <li>linuxKernel.packages.linux_latest_libre.usbip</li>
    <li>linuxKernel.packages.linux_latest_libre.v4l2loopback</li>
    <li>linuxKernel.packages.linux_latest_libre.v86d</li>
    <li>linuxKernel.packages.linux_latest_libre.veikk-linux-driver</li>
    <li>linuxKernel.packages.linux_latest_libre.vendor-reset</li>
    <li>linuxKernel.packages.linux_latest_libre.vhba</li>
    <li>linuxKernel.packages.linux_latest_libre.virtio_vmmci</li>
    <li>linuxKernel.packages.linux_latest_libre.virtualbox</li>
    <li>linuxKernel.packages.linux_latest_libre.vmm_clock</li>
    <li>linuxKernel.packages.linux_latest_libre.x86_energy_perf_policy</li>
    <li>linuxKernel.packages.linux_latest_libre.xone</li>
    <li>linuxKernel.packages.linux_latest_libre.xpadneo</li>
    <li>linuxKernel.packages.linux_latest_libre.zenpower</li>
    <li>linuxKernel.packages.linux_libre.perf</li>
    <li>linuxKernel.packages.linux_lqx.perf</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.perf</li>
    <li>linuxKernel.packages.linux_xanmod.perf</li>
    <li>linuxKernel.packages.linux_xanmod_latest.perf</li>
    <li>linuxKernel.packages.linux_xanmod_tt.perf</li>
    <li>linuxKernel.packages.linux_zen.perf</li>
    <li>qtcreator</li>
    <li>systeroid</li>
  </ul>
</details>

**Comment by K900** [comment]
Fixed `perf`, undrafted

**Review by ghost — COMMENTED** [review]
Built on
- [x] powerpc64le-linux
- [x] mips64el-linux (requires `PATA_OCTEON_CF=n`)

**Comment by alyssais** [comment]
@ofborg test latestKernel.login

**Comment by vcunat** [comment]
Or perhaps I should also ask &ndash; it wasn't intentional to keep this from 22.05, right?

**Comment by K900** [comment]
I don't think there's any good reason to.

**Comment by vcunat** [comment]
I'm not sure which you meant (too many negations in our posts).  But my reason for backport is that otherwise what to do with `linux_latest` on 22.05.  Leaving it long on unsupported version doesn't sound right.

**Comment by K900** [comment]
I mean it's good to backport.

**Pull request merged**
