### PR TITLE
sage: fix build by downgrading maxima to 5.45

### PR DESCRIPTION
**Pull request by amesgen**
###### Description of changes

The upgrade of maxima to 5.46 in #219171 broke the sage doctests, see https://github.com/sagemath/sage/issues/33718 for the upstream ticket. Hence, we downgrade maxima for sage, see #57126 as a precursor.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Thanks, this fixes the sage build for me.

**Comment by collares** [comment]
Does downgrading maxima by overriding the 5.46 derivation (instead of copying) work? If so, that might be a better approach since maxima is not upgraded that often. I will experiment here.

**Comment by amesgen** [comment]
> Does downgrading maxima by overriding the 5.46 derivation (instead of copying) work? If so, that might be a better approach since maxima is not upgraded that often. I will experiment here.

It should work in principle, but since #220560, one would e.g. have to re-add that patch. In general, I am happy to switch to override the existing derivation instead of copying the file; I only went ahead with this approach as that is what was done in #57126.

**Comment by collares** [comment]
Yeah, I think that's fair. I'd be happy to defer to other Sage maintainers on this.

**Comment by collares** [comment]
One relevant thing is that the previous PR was pre-#119942, and the feature added there really helps with version overrides.

**Comment by collares** [comment]
Either way, many thanks for helping with Sage maintenance! I will merge this tomorrow if the Sage maintainers haven't reached a conclusion until then.

**Review by timokau — APPROVED** [review]
Looks good to me. Overriding would be possible too, both options have their advantages and disadvantages. Copying is robust, avoids unnecessary breakage due to a moving target. Overriding reduces duplicate code, forces you to re-evaluate whether the override is still necessary when it breaks.

I think as long as we remember to clean up the copy once it is not necessary anymore its fine to go ahead as-is and merge this. I'll leave the decision to you @collares though.

**Comment by collares** [comment]
Given @timokau's comment and the fact that Maxima does not change that much, I think both solutions are roughly equivalent. Therefore, I think it's best to value contributors and go with the current version. Thanks everyone!

**Pull request merged**
