### PR TITLE
 top-level: use callPackages where inheriting packages

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

otherwise those packages cannot be overriden

```
nix-repl> nomad.override
error: attribute 'override' missing

       at «string»:1:1:

            1| nomad.override
             | ^

```

With this change they can be overriden

```
nix-repl> nomad.override
{ __functionArgs = { ... }; __functor = «lambda @ /home/sandro/src/nixpkgs2/lib/trivial.nix:440:19»; }
```

Resubmition because of revert in #281932 because of an oversight of me.

I tested this with
```
NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_NONSOURCE=1 NIXPKGS_ALLOW_BROKEN=1 nix build --impure .#prefetch-yarn-deps .#python3Packages.dash .#ivpn .#ivpn-service .#charles3 .#charles4 .#msrtool .#cbmem .#ifdtool .#intelmetool .#cbfstool .#nvramtool .#superiotool .#ectool .#inteltool .#amdfwtool .#acpidump-all .#coreboot-utils .#garage .#garage_0_8 .#garage_0_9 .#garage_0_8_4 .#garage_0_9_0 .#nextcloud26 .#nextcloud27 .#nextcloud28 .#nomad .#nomad_1_4 .#nomad_1_5 .#nomad_1_6 .#nomad_1_7
```

I used python3Packages.dash instead of fetchYarnDeps because that cannot be directly evaluated.
 
 Please merge this before the next nixos-unstable otherwise we leave configs broken with evaluation errors.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Thanks! If there happens to be another issue, please give me a ping and I take a look into it.

**Comment by RaitoBezarius** [comment]
This should have been backported because this is a bugfix.

**Comment by lilyinstarlight** [comment]
Backport in #297051

**Comment by SuperSandro2000** [comment]
> This should have been backported because this is a bugfix.

Since this was the second try already and fully testing this is kinda cumbersome, I was a bit conservative of backporting.

**Pull request merged**
