### PR TITLE
modules/rosetta: configure nix build sandbox to use rosetta

### PR DESCRIPTION
**Pull request by arianvp**
###### Description of changes

With this we can do x86_64 builds on aarch64

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]

**Comment by 9999years** [comment]
Is there a command I can run on aarch64-darwin to test this by building an x86_64-linux derivation?

**Comment by arianvp** [comment]
I will add a derivation to the PR that can be run for manual testing. I'll add one now

**Comment by arianvp** [comment]
Ah specifically `aarch64-darwin`? Not that I know of. There might be a CLI for `Virtualisation.framework`. I've been using the utm.app GUI to test this.

**Comment by 9999years** [comment]
I'm confused, I thought rosetta was the x86_64 virtualization layer on M1 Macs. Is this for Linux installed on M1 Macs or something?

**Comment by arianvp** [comment]
When running a NixOS VM through `virtualisation.framework` Rosetta is available inside the VM

**Comment by arianvp** [comment]
Given this is not really automatable by test and the way to check is "build any nix derivation" I don't think there is a need to add any further testing code. I'm going to merge as is

**Pull request merged**
