### PR TITLE
radicle: reinit at 1.0.0-rc.8

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
Remove `radicle-{cli,upstream}` and add `radicle-node`.

### Rationale for Removal of `radicle-cli`

The repository [`github:radicle-dev/radicle-cli`](https://github.com/radicle-dev/radicle-cli) that `radicle-cli` builds from, was [last tagged on 2022-08-11](https://github.com/radicle-dev/radicle-cli/releases/tag/v0.6.1) and archived on 2023-05-11.

### Rationale for Removal of `radicle-upstream`

The repository [`github:radicle-dev/radicle-upstream`](https://github.com/radicle-dev/radicle-upstream) that `radicle-upstream` builds from, was [last tagged on 2022-07-29](https://github.com/radicle-dev/radicle-upstream/releases/tag/v0.3.2) and archived on 2022-08-01. The release notes say that it shows "a deprecation notification upon startup". There's a [deprecation/sunsetting notice on community.radworks.org](https://community.radworks.org/t/2962).

#### Source Repository

Development moved from [`github:radicle-dev/radicle-cli`](https://github.com/radicle-dev/radicle-cli) to [`github:radicle-dev/Heartwood`](https://github.com/radicle-dev/heartwood/). However, this repository was archived as the Radicle intensified dogfooding and is now on Radicle itself under [`rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5`](rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5) ([view it via app.radicle.xyz](https://app.radicle.xyz/nodes/ash.radicle.garden/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5)). This is the reason why I decided not to use GitHub but a Radicle node (that is prominent in the community) to fetch sources. It acts as a bridge from the Radicle network to Git over HTTPS. The ref looks a bit weird for technical reasons to do with Radicle itself using Git namespaces.

#### Maintainers

@amesgen, I decided to keep you as maintainer, since you're still contributing to (other parts of) Nixpkgs. Just notify me in case you don't agree.

#### Tests

...are not entirely broken, just flaky. Many unit tests will still execute, and there's a version test. I am working on a NixOS module for Radicle as well, so if I find the time, I might write a NixOS integration test instead of E2E testing via Cargo.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lorenzleutgeb** [comment]
Result of `nixpkgs-review pr 309050` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>radicle-node</li>
  </ul>
</details>

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Comment by lorenzleutgeb** [comment]
@ofborg build radicle-node

**Review by amesgen — COMMENTED** [review]
Note that there is a very similar PR #301511 by @roblabla (apart from the rename and removal of radicle-upstream). It probably makes sense to avoid duplicated work and join forces to modernize radicle.

**Comment by roblabla** [comment]
> No offense to @roblabla, and I still acknowledge that the duplicate effort was unnecessary, but I think this PR is objectively better.

None taken, I agree this PR is better 😄 .

**Comment by lorenzleutgeb** [comment]
@roblabla great! Could you please review and/or test this PR (if and when you have time) and report back? :)

**Comment by roblabla** [comment]
I did some quick testing, and it works great. One thing that seems to be missing is the `rad web` command, used to login with the radicle frontend. This seems to happen because `rad-web` is not being built/distributed for some reason.

This led me to compare our builds from the official distribution. There's another binary missing: radicle-httpd, the frontend for a radicle seed. I guess this might make sense to provide in a separate package though.

**Comment by lorenzleutgeb** [comment]
Yes, my idea was to split this. `radicle-node` should contain what is strictly necessary to run a Radicle node and interact with the Radicle network. Both `rad-web` and `radicle-httpd` are nice to have, but critical.

There also are use-cases where you don't need `radicle-web`, but you *do* need `radicle-httpd`, e.g. when using their VSCode extension. This is why I would suggest to even introduce two separate packages for these components.

The binaries `radicle-node`, and `rad` go together because there's currently no point in using either of them alone, and `git-remote-rad` is IMO not worth packaging separately. So you end up with `radicle-node` as the main, but barebones, thing, and `radicle-httpd` and `radicle-web` both optional.

I'd like to prioritise `radicle-node` however, and want to land this PR without the other components. Keeping the PR smaller hopefully gets it merged faster. And the packages `radicle-cli` and `radicle-upstream` are, quite frankly, useless at the moment anyway, so even adding just `radicle-node` to Nixpkgs is an improvement.

**Review by roblabla — APPROVED** [review]
Sounds like a solid plan to me.

**Comment by FintanH** [comment]
> One thing that seems to be missing is the `rad web` command, used to login with the radicle frontend. This seems to happen because `rad-web` is not being built/distributed for some reason.

I'll also note that the Radicle team has deemed `rad web` as experimental for the time being. So it might be worth waiting until it's more stable anyway :)

**Comment by roblabla** [comment]
> I'll also note that the Radicle team has deemed rad web as experimental for the time being. So it might be worth waiting until it's more stable anyway :)

While that's true, `rad web` is:

- part of the default radicle distribution
- One of the first call to action when you end up on the radicle webapp landing page (connect on the top right)

I don't think it makes sense to deviate from the standard distribution too much, as it will probably surprise people.

**Comment by FintanH** [comment]
> One of the first call to action when you end up on the radicle webapp landing page (connect on the top right)

I believe that's been removed :)

To be clear, I work on the protocol of Radicle, but not the web end of things. Afaik, the web team have deemed `rad web` as experimental.

**Comment by koalalorenzo** [comment]
Do you know if this will be available in 24.05 by any chance? Out of curiosity really :)

**Review by amesgen — APPROVED** [review]

**Comment by lorenzleutgeb** [comment]
> Do you know if this will be available in 24.05 by any chance? Out of curiosity really :)

Please refer to the [Release Schedule](https://github.com/NixOS/nixpkgs/issues/303285) which is a pinned issue. Branch-off is scheduled for 2024-05-22 AoE.

**Pull request merged**
