### PR TITLE
opencv: don't use default /lib64/ when searching for libs

### PR DESCRIPTION
**Pull request by KaiSforza**
See #6925

### CODE REVIEW

**Comment by KaiSforza** [comment]
(Fails because this causes a rebuild of kde4 and it takes too long for output.)

**Comment by lethalman** [comment]
That seems to rebuild a lot of stuff on kde, maybe better for staging.

**Comment by edolstra** [comment]
@lethalman I think this is fine for master - KDE is a small subset of Nixpkgs.

**Comment by vcunat** [comment]
General note: I'm a bit anxious from everyone putting in lots of references like ``${zlib}/lib/libz.so``. At the very least it makes things fragile when splitting packages into multiple outputs. I would think we have pkg-config, libtool, and whatever else to do library and header searches for us. If they don't work (e.g. with cmake), we should fix those tools instead of "hard"-coding similar paths.

**Comment by lethalman** [comment]
@vcunat not all packages use pkgconfig, that's the point.

On Sat, May 9, 2015 at 2:57 PM, Vladimír Čunát <notifications@github.com>
wrote:

> General note: I'm a bit anxious from everyone putting in lots of
> references like ${zlib}/lib/libz.so. At the very least it makes things
> fragile when splitting packages into multiple outputs. I would think we
> have pkg-config, libtool, and whatever else to do library and header
> searches for us. If they don't work (e.g. with cmake), we should fix those
> tools instead of "hard"-coding similar paths.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/7698#issuecomment-100479645>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by KaiSforza** [comment]
@vcunat It looks like this was attempted before, but failed in #7141, due to KDE. I can try to work where @giogadi left off.

**Comment by vcunat** [comment]
Do I understand correctly that in this case the motivation is to stop searching impure paths, not to help it find the nix-packaged stuff?

**Comment by KaiSforza** [comment]
In this PR, the idea is to help it find nix packaged stuff,

The issue linked had the idea to stop searching impure paths, but I don't know if that's going to be possible for certain situations, as you can specify where cmake will look when writing the CMakeLists.txt file, or at least that's my understanding.

**Comment by giogadi** [comment]
@KaiSforza Part of the nix derivation for cmake is to do automatically remove all references to impure paths in the CMakeLists.txt files, so that part shouldn't be an issue. I think the problem is that impure paths are still baked pretty deeply into CMake itself, so it's hard to fish out all the places where they pop up.

**Comment by lethalman** [comment]
Note that it couldn't find jasper includes:
```
Could NOT find Jasper (missing:  JASPER_INCLUDE_DIR)
```

Otherwise I'm fine merging this.

**Comment by KaiSforza** [comment]
Let me check and see what it's looking for. I'm at work currently, don't have access to a fast Linux machine with a GUI at work.

**Comment by bjornfor** [comment]
Is this still relevant? (OpenCV seems to build fine.)

**Pull request closed without merging**
