### PR TITLE
Update vdirsyncer

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Updates both `vdirsyncer` and `pythonPackages.requests_toolbelt`.

### CODE REVIEW

**Comment by DamienCassou** [comment]
please fix the build

**Comment by matthiasbeyer** [comment]
I'd like to, though I don't know what is failing here. Something seems to be wrong with `requests_toolbelt`, but `nix-build -A vdirsyncer` succeeds on my machine... can you maybe give me a pointer what is the issue here?

**Comment by matthiasbeyer** [comment]
Lets see whether this succeeds...

**Comment by matthiasbeyer** [comment]
Seems not to be the case. @DamienCassou AFAICS, the build error is not my fault... as said, it builds wonderfully fine for me. Tell me how to do a pure build, so I can verify this, too.

**Comment by DamienCassou** [comment]
works fine for me as well. Let's try

**Comment by DamienCassou** [comment]
thanks

**Pull request merged**
