### PR TITLE
opencv2: fix clang builds

### PR DESCRIPTION
**Pull request by matteo-pacini**
## Description of changes

OpenCV 2.x relies on some features that have been disabled in C++ 17 (libc++ / Clang).
More about those features here: https://libcxx.llvm.org/UsingLibcxx.html#c-17-specific-configuration-macros

If `clang` is detected, then we add `-std=c++14`  to `CXXFLAGS`.

**Note: the package has no maintainers (!)**

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matteo-pacini** [comment]
@NixOS/darwin-maintainers would be great if anyone could test this on `x86_64-darwin`. 🙏🏻

**Comment by emilazy** [comment]
Result of `nixpkgs-review pr 328702` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>opencv2</li>
    <li>opencv2.dev</li>
  </ul>
</details>

**Review by emilazy — APPROVED** [review]
Looks good, but I hope we can get rid of this package at some point. It has only four reverse dependencies, none of which advertise Darwin support, and one of which is just the binary Mathematica distribution…

**Comment by afh** [comment]
You beat me to it, @emilazy 😅  My x86 machine is still compiling and 🥵

**Comment by afh** [comment]
Result of `nixpkgs-review pr 328702` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>opencv2</li>
    <li>opencv2.dev</li>
  </ul>
</details>

**Review by afh — APPROVED** [review]
Thanks for this, @matteo-pacini 👍

**Comment by matteo-pacini** [comment]
@emilazy I would keep this alive until OpenCV officially deprecates it - it shouldn't receive updates or major changes, so the effort required in maintaining this should be minimal (hopefully!).

If more effort is required in the future, then we should remove it.

**Pull request merged**
