### PR TITLE
microscheme: update to latest release (0.9.1)

### PR DESCRIPTION
**Pull request by bjornfor**
- Don't "externalize url/rev/sha256 to permit easier override".
  Just override 'src' itself. Then you can get the source from anywhere,
  not just git. I needed to touch this anyway, because I want to use
  fetchzip instead of fetchgit for releases (no need to clone repo).
- Latest release has "make install" fixes, simplifies our install.

---

@ardumont: The example you put in the commit message for adding microscheme fails for me, both with this and the previous version. I've stripped the -u and -d flag as I don't have hardware, but I don't think that matters:

```
$ ./result/bin/microscheme -m UNO -ac ./result/share/microscheme/examples/BLINK.ms
Microscheme 0.9.1, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 87 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
/nix/store/df458865akmncpd2qrp4xc3hw8s4gw5z-avr-gcc-libc/lib/gcc/avr/4.8.4/../../../../avr/bin/ld:.s: file format not recognized; treating as linker script
/nix/store/df458865akmncpd2qrp4xc3hw8s4gw5z-avr-gcc-libc/lib/gcc/avr/4.8.4/../../../../avr/bin/ld:.s:1: syntax error
collect2: error: ld returned 1 exit status
>> Warning: Command may have failed. (Exit code 256)
avr-objcopy: '.elf': No such file
>> Warning: Command may have failed. (Exit code 256)
>> Cleaning Up...
>> Finished.
```

```
$ ./result/bin/microscheme -m UNO -ac ./result/share/microscheme/examples/BLINK.ms
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
/nix/store/df458865akmncpd2qrp4xc3hw8s4gw5z-avr-gcc-libc/lib/gcc/avr/4.8.4/../../../../avr/bin/ld:.s: file format not recognized; treating as linker script
/nix/store/df458865akmncpd2qrp4xc3hw8s4gw5z-avr-gcc-libc/lib/gcc/avr/4.8.4/../../../../avr/bin/ld:.s:1: syntax error
collect2: error: ld returned 1 exit status
>> Warning: Command may have failed. (Exit code 256)
avr-objcopy: '.elf': No such file
>> Warning: Command may have failed. (Exit code 256)
>> Cleaning Up...
>> Finished.
```

### CODE REVIEW

**Comment by bjornfor** [comment]
And this is from the release-14.12 branch, where avr-gcc still is on 4.6.3 (but we have the same error):

```
$ ./result/bin/microscheme -m UNO -ac ./result/share/microscheme/examples/BLINK.ms
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
/nix/store/y6k2gyb28a9zk5m5qy84pwn6xg66ancl-avr-gcc-libc/lib/gcc/avr/4.6.3/../../../../avr/bin/ld:.s: file format not recognized; treating as linker script
/nix/store/y6k2gyb28a9zk5m5qy84pwn6xg66ancl-avr-gcc-libc/lib/gcc/avr/4.6.3/../../../../avr/bin/ld:.s:1: syntax error
collect2: ld returned 1 exit status
>> Warning: Command may have failed. (Exit code 256)
avr-objcopy: '.elf': No such file
>> Warning: Command may have failed. (Exit code 256)
>> Cleaning Up...
>> Finished.
```

**Comment by ardumont** [comment]
> Don't "externalize url/rev/sha256 to permit easier override". Just override 'src' itself. Then you can get the source from anywhere, not just git. I needed to touch this anyway, because I want to use fetchzip instead of fetchgit for releases (no need to clone repo).

I did at the time to have code that actually work.

>  Latest release has "make install" fixes, simplifies our install.

Cool.

> @ardumont: The example you put in the commit message for adding microscheme fails for me, both with this and the previous version.

Ok.
I don't know what to answer here.
I tried my code on 2 different nixos installs and both worked up to installing some blink sample on arduino.

--

I'm compiling this code right now to provide you with feedback.
But it's kind of long...

Ok.
It worked.

```sh
# tony at dagobah in ~/repo/perso/nixpkgs on git:microscheme-bump o [21:00:22]
$ nix-env -f . -i microscheme
replacing old ‘microscheme-2015-02-04’
installing ‘microscheme-0.9.1’
building path (s) ‘/nix/store/i7xnawd3f246vxc19lxr02rc88j4azk7-user-environment’
created 6415 symlinks in user environment

# tony at dagobah in ~/repo/perso/nixpkgs on git:microscheme-bump o [21:01:11]
$ microscheme -m UNO -d /dev/ttyACM0 -auc ~/repo/perso/microscheme/examples/BLINK.ms
Microscheme 0.9.1, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 87 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
>> Uploading...

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file "/home/tony/repo/perso/microscheme/examples/BLINK.hex"
avrdude: writing flash (2080 bytes):

Writing | ################################################## | 100% 0.35s

avrdude: 2080 bytes of flash written

avrdude: safemode: Fuses OK (E:00, H:00, L:00)

avrdude done.  Thank you.

>> Cleaning Up...
>> Finished.
```

Using direct sample with the same right as my current user, no warning.

However:

- trying to use the samples installed in the store results in segfault (surely it's permission error)

```sh
# tony at dagobah in ~/repo/perso/nixpkgs on git:microscheme-bump o [21:09:11]
$ microscheme -m UNO -d /dev/ttyACM0 -auc $ (dirname $ (readlink $ (which microscheme)))/../share/microscheme/examples/blink-led-morse.ms
Microscheme 0.9.1, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 86 globals purged! 32 bytes will be reserved.
[1]    21048 segmentation fault  microscheme -m UNO -d /dev/ttyACM0 -auc

```

- trying to use the samples installed in the link `result`, result in warning along the way but still, the sample is installed:

```sh
# tony at dagobah in ~/repo/perso/nixpkgs on git:microscheme-bump o [21:05:45]
$ microscheme -m UNO -d /dev/ttyACM0 -auc ./result/share/microscheme/examples/blink-led-morse.ms
Microscheme 0.9.1, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 86 globals purged! 32 bytes will be reserved.
>> 114 lines compiled OK
>> Assembling...
/nix/store/df458865akmncpd2qrp4xc3hw8s4gw5z-avr-gcc-libc/lib/gcc/avr/4.8.4/../../../../avr/bin/ld:.s: file format not recognized; treating as linker script
/nix/store/df458865akmncpd2qrp4xc3hw8s4gw5z-avr-gcc-libc/lib/gcc/avr/4.8.4/../../../../avr/bin/ld:.s:1: syntax error
collect2: error: ld returned 1 exit status
>> Warning: Command may have failed. (Exit code 256)
avr-objcopy: '.elf': No such file
>> Warning: Command may have failed. (Exit code 256)
>> Uploading...

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file ".hex"
avrdude: can't open input file .hex: No such file or directory
avrdude: read from file '.hex' failed

avrdude: safemode: Fuses OK (E:00, H:00, L:00)

avrdude done.  Thank you.

>> Warning: Command may have failed. (Exit code 256)
>> Cleaning Up...
>> Finished.
```

**Comment by bjornfor** [comment]
@ardumont: Thanks for the feedback. Right... this is weird. Looks like an upstream issue:

```
$ ./result/bin/microscheme -m UNO -ac $PWD/BLINK.ms 
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
>> Cleaning Up...
>> Finished.

$ ./result/bin/microscheme -m UNO -ac BLINK.ms 
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
>> Cleaning Up...
>> Finished.

$ ./result/bin/microscheme -m UNO -ac ./BLINK.ms 
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
/nix/store/y6k2gyb28a9zk5m5qy84pwn6xg66ancl-avr-gcc-libc/lib/gcc/avr/4.6.3/../../../../avr/bin/ld:.s: file format not recognized; treating as linker script
/nix/store/y6k2gyb28a9zk5m5qy84pwn6xg66ancl-avr-gcc-libc/lib/gcc/avr/4.6.3/../../../../avr/bin/ld:.s:1: syntax error
collect2: ld returned 1 exit status
>> Warning: Command may have failed. (Exit code 256)
avr-objcopy: '.elf': No such file
>> Warning: Command may have failed. (Exit code 256)
>> Cleaning Up...
>> Finished.

$ ./result/bin/microscheme -m UNO -ac ./result/share/microscheme/examples/BLINK.ms
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
>> 18 lines compiled OK
>> Assembling...
/nix/store/y6k2gyb28a9zk5m5qy84pwn6xg66ancl-avr-gcc-libc/lib/gcc/avr/4.6.3/../../../../avr/bin/ld:.s: file format not recognized; treating as linker script
/nix/store/y6k2gyb28a9zk5m5qy84pwn6xg66ancl-avr-gcc-libc/lib/gcc/avr/4.6.3/../../../../avr/bin/ld:.s:1: syntax error
collect2: ld returned 1 exit status
>> Warning: Command may have failed. (Exit code 256)
avr-objcopy: '.elf': No such file
>> Warning: Command may have failed. (Exit code 256)
>> Cleaning Up...
>> Finished.

$ ./result/bin/microscheme -m UNO -ac $PWD/result/share/microscheme/examples/BLINK.ms
Microscheme 0.8, (C) Ryan Suchocki
>> Treeshaker: After 4 rounds: 84 globals purged! 22 bytes will be reserved.
Segmentation fault
```

It seems it doesn't handle relative paths, or read-only paths.

**Comment by bjornfor** [comment]
A new upstream release is around the corner. It will fix these issues.

**Comment by bjornfor** [comment]
Pushed to master and release-14.12.

**Comment by bjornfor** [comment]
(After updating to 0.9.2 with the fixes.)

**Pull request closed without merging**
