### PR TITLE
python: enable opt-in parallel build_ext builds for setuptools

### PR DESCRIPTION
**Pull request by cpcloud**
###### Description of changes

Add the ability to enable parallel extension builds in setuptools using `enableParallelBuilding = true`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Changes look good, however, please fix the commits to have one logical change per commit.

**Comment by cpcloud** [comment]
@FRidh done!

**Review by FRidh — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Do you have any other packages in mind where we should definitely set this?

**Comment by cpcloud** [comment]
Not specifically, but anything with setuptools based C extensions is probably eligible. I suspect that trying this on a few cython based packages will yield useful results.

**Comment by SuperSandro2000** [comment]
Could we convert this into a setup hook for cython so that it just works?

**Comment by cpcloud** [comment]
Maybe? It seems somewhat invasive for everything to build this way but maybe it's fine.

**Comment by SuperSandro2000** [comment]
That not a problem if it is save to do for almost any project. If it only works for half of them we shouldn't do it.

**Comment by FRidh** [comment]
> Could we convert this into a setup hook for cython so that it just works?

Cython can be used without setuptools, and setuptools can have a `--parallel` flag without using Cython.

**Comment by wentasah** [comment]
This seems to break xpra. See https://hydra.nixos.org/build/175365335/log. Excerpt:
```
[39/41] Cythonizing xpra/x11/bindings/ximage.pyx
[41/41] Cythonizing xpra/x11/gtk3/gdk_display_source.pyx
usage: nix_run_setup [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: nix_run_setup --help [cmd1 cmd2 ...]
   or: nix_run_setup --help-commands
   or: nix_run_setup cmd --help

error: option --with-vsock--parallel not recognized
```

I hope that the following change fixes that. I'm currently trying to recompile xpra and if it is sucessfull, I'll send a PR with the fix. 

```diff
diff --git a/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh b/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh
index 89a95e98219..c3a4ee7c1a6 100644
--- a/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh
+++ b/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh
@@ -12,7 +12,7 @@ setuptoolsBuildPhase() {
         args+="$setupPyGlobalFlags"
     fi
     if [ -n "$enableParallelBuilding" ]; then
-        setupPyBuildFlags+="--parallel $NIX_BUILD_CORES"
+        setupPyBuildFlags+=" --parallel $NIX_BUILD_CORES"
     fi
     if [ -n "$setupPyBuildFlags" ]; then
         args+="build_ext $setupPyBuildFlags"
```

**Comment by cpcloud** [comment]
Ah, thanks!

**Comment by wentasah** [comment]
Xpra build with the change would take ages, because it rebuilds half of the world. Sending the PR without build testing :-(

**Comment by FRidh** [comment]
> This seems to break xpra. See https://hydra.nixos.org/build/175365335/log. Excerpt:
> 
> ```
> [39/41] Cythonizing xpra/x11/bindings/ximage.pyx
> [41/41] Cythonizing xpra/x11/gtk3/gdk_display_source.pyx
> usage: nix_run_setup [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: nix_run_setup --help [cmd1 cmd2 ...]
>    or: nix_run_setup --help-commands
>    or: nix_run_setup cmd --help
> 
> error: option --with-vsock--parallel not recognized
> ```
> 
> I hope that the following change fixes that. I'm currently trying to recompile xpra and if it is sucessfull, I'll send a PR with the fix.
> 
> ```diff
> diff --git a/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh b/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh
> index 89a95e98219..c3a4ee7c1a6 100644
> --- a/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh
> +++ b/pkgs/development/interpreters/python/hooks/setuptools-build-hook.sh
> @@ -12,7 +12,7 @@ setuptoolsBuildPhase() {
>          args+="$setupPyGlobalFlags"
>      fi
>      if [ -n "$enableParallelBuilding" ]; then
> -        setupPyBuildFlags+="--parallel $NIX_BUILD_CORES"
> +        setupPyBuildFlags+=" --parallel $NIX_BUILD_CORES"
>      fi
>      if [ -n "$setupPyBuildFlags" ]; then
>          args+="build_ext $setupPyBuildFlags"
> ```

Already fixed in https://github.com/NixOS/nixpkgs/pull/170060.

**Pull request merged**
