### PR TITLE
LilyPond: Fix configure error - incorrectly detected fontforge version

### PR DESCRIPTION
**Pull request by tex**
###### Motivation for this change

Fix broken build. It fails on Hydra too.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
I think this can be simplified further, here's what I came up with:

```diff
diff --git a/pkgs/misc/lilypond/default.nix b/pkgs/misc/lilypond/default.nix
index f312cce19d7..36d2d3864be 100644
--- a/pkgs/misc/lilypond/default.nix
+++ b/pkgs/misc/lilypond/default.nix
@@ -1,5 +1,5 @@
 { stdenv, fetchurl, ghostscript, texinfo, imagemagick, texi2html, guile
-, python2, gettext, flex, perl, bison, pkgconfig, dblatex
+, python2, gettext, flex, perl, bison, pkgconfig, autoreconfHook, dblatex
 , fontconfig, freetype, pango, fontforge, help2man, zip, netpbm, groff
 , fetchsvn, makeWrapper, t1utils
 , texlive, tex ? texlive.combine {
@@ -26,11 +26,6 @@ stdenv.mkDerivation rec{
   preConfigure=''
     sed -e "s@mem=mf2pt1@mem=$PWD/mf/mf2pt1@" -i scripts/build/mf2pt1.pl
 
-    # At some point our fontforge had path 2n…-fontforge-2015… and it
-    # confused the version detection…
-    sed -re 's%("[$]exe" --version .*)([|\\] *$)%\1 | sed -re "s@/nix/store/[a-z0-9]{32}-@@" \2%' \
-      -i configure
-
     export HOME=$TMPDIR/home
   '';
 
@@ -48,10 +43,12 @@ stdenv.mkDerivation rec{
 
   buildInputs =
     [ ghostscript texinfo imagemagick texi2html guile dblatex tex zip netpbm
-      python2 gettext flex perl bison pkgconfig fontconfig freetype pango
-      fontforge help2man groff makeWrapper t1utils
+      python2 gettext flex perl bison fontconfig freetype pango
+      fontforge help2man groff t1utils
     ];
+  nativeBuildInputs = [ makeWrapper pkgconfig autoreconfHook ];
 
+  autoreconfPhase = "NOCONFIGURE=1 ./autogen.sh";
   #enableParallelBuilding = true; # fatal error: parser.hh: No such file or directory
 
   meta = with stdenv.lib; {
```

No need to patch in the version anywhere :).  Haven't tried the parallel building, but am glad that it works now :).

**Comment by tex** [comment]
@dtzWill  Thanks for help, I tried autoreconfHook before, but didn't know about NOCONFIGURE=1 which led to problems that I workarounded with the direct use of automake...
The oriignal issue is with the pre-generated configure script - it gets fontforge version correctly, it prints what on screen looks like never version that lowest required but then comparsion goes south probably and error is reported incorrectly. Oh, nice world of build systems and especially autoconf/automake ;-) in this particular case.

**Comment by Infinisil** [comment]
Can you squash the commits?

**Comment by tex** [comment]
Done.

**Comment by Infinisil** [comment]
Ah I didn't notice, add `LilyPond:` as a prefix to your commit message next time.

**Pull request merged**
