### PR TITLE
Fix nixUnstable cross compilation

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

- Bump nixUnstable to latest
- Fix cross compilation by disabling documentation generation.

###### Things done

- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107909` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>disnix</li>
    <li>dydisnix</li>
    <li>nix-update</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

builder for '/nix/store/9yirjf9c1hnihy53kjlr85x3igz5rhi3-nix-2.4pre20201228_abbf9df.drv' failed with exit code 2; last 10 log lines:
+ '[' /private/tmp/nix-build-nix-2.4pre20201228_abbf9df.drv-0/nix-test/user-envs/store/7yv2aa65r6riifjs17a3v33j4mwc7wmi-user-environment = /private/tmp/nix-build-nix-2.4pre20201228_abbf9df.drv-0/nix-test/user-envs/store/7yv2aa65r6riifjs17a3v33j4mwc7wmi-user-environment ']'
+ nix-env -i /private/tmp/nix-build-nix-2.4pre20201228_abbf9df.drv-0/nix-test/user-envs/store/7s318sd6cn6bxl4c9jcjzgjfmj0p4dhn-foo-1.0
installing 'foo-1.0'
error: --- EndOfFile --- nix-env
unexpected EOF reading a line
make: *** [mk/lib.mk:110: tests/user-envs.sh.test] Error 1
make: *** Waiting for unfinished jobs....
ran test tests/gc-runtime.sh... [PASS]
ran test tests/lang.sh... [PASS]
ran test tests/fixed.sh... [PASS]

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107909` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>hydra-unstable</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>disnix</li>
    <li>disnixos</li>
    <li>dydisnix</li>
    <li>nix-update</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

**Comment by matthewbauer** [comment]
That looks x86_64-darwin issue looks like https://github.com/NixOS/nix/issues/3605. I don't think it's gotten worse with this update.

Hydra will need https://github.com/NixOS/hydra/pull/843 and https://github.com/NixOS/hydra/pull/840 to be merged.

**Comment by SuperSandro2000** [comment]
We should think about adding ``strictDeps = true;`` from #107163.

**Comment by alyssais** [comment]
Documentation disable was disabled for cross in #125772, and Nix has been updated well past what this PR does by now, so I think we can close this.

**Pull request closed without merging**
