### PR TITLE
python3Packages.{torch,torch-bin}: 2.1.1 -> 2.1.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Update the torch ecosystem.

cc @teh  @thoughtpolice @tscholak 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by junjihashimoto — APPROVED** [review]
Thx!

**Comment by happysalada** [comment]
not sure why but on latest master, I'm getting a segfault trying to build torch (with cudaSupport)

```
[5307/6573] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/aut
ograd/generated/TraceType_2.cpp.o
torch> FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/generated/TraceTyp
e_2.cpp.o
torch> /nix/store/sfgnb6rr428bssyrs54d6d0vv2avi95c-gcc-wrapper-12.3.0/bin/g++ -DAT_PER_O
PERATOR_HEADERS -DBUILD_ONEDNN_GRAPH -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFOR
M=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE
torch> In file included from /build/source/torch/library.h:68,
torch>                  from /build/source/torch/csrc/autograd/generated/TraceType_2.cpp
torch> /build/source/aten/src/ATen/core/op_registration/op_registration.h: In function ‘
torch> /build/source/aten/src/ATen/core/op_registration/op_registration.h:28:33: interna
torch>    28 | std::unique_ptr<FunctionSchema> inferFunctionSchemaFromFunctor() {
torch>       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch> 0x1bacaf7 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char c
torch>  ???:0
torch> 0x1bad947 internal_error(char const*, ...)
torch>  ???:0
torch> 0xddc3bf crash_signal(int)
torch>  ???:0
torch> 0x9439e3 ggc_set_mark(void const*)
torch>  ???:0
torch> 0x8951e7 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x8956fd gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x896103 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x8961eb gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x896339 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x8960aa gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x895b7e gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x89570b gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x896ebd gt_ggc_mx_lang_decl(void*) [clone .part.0]
torch>  ???:0
torch> 0x896d29 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x8960aa gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x896339 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x8960aa gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x895ffc gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x896072 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> 0x896042 gt_ggc_mx_lang_tree_node(void*)
torch>  ???:0
torch> Please submit a full bug report, with preprocessed source (by using -freport-bug)
torch> Please include the complete backtrace with any bug report.
torch> See <https://gcc.gnu.org/bugs/> for instructions.
torch> [5320/6573] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/laz
y/generated/LazyNativeFunctions.cpp.ocpp.o
```

**Comment by SomeoneSerge** [comment]
@happysalada H'm, I just tried this and got the substitutes from cachix:

```
❯ nix build -I nixpkgs=flake:github:NixOS/nixpkgs/master -f '<nixpkgs>' --arg config '{ cudaSupport = true; allowUnfree = true; }' -L python3Packages.torch --print-out-paths 
/nix/store/d7yql986amkzw0s27fggxnm844cjsvba-python3.11-torch-2.1.2
```

**Comment by happysalada** [comment]
do you have cudaSupport enabled on your machine ?

**Comment by happysalada** [comment]
weird, thank you, I'll post more if I find out what could be causing this.

**Comment by veprbl** [comment]
Can't reproduce on 4cdde2bb35340a5b33e4a04e3e5b28d219985b7e
/nix/store/d7yql986amkzw0s27fggxnm844cjsvba-python3.11-torch-2.1.2 compiles

**Pull request merged**
