### PR TITLE
transmission service: `mkdir -p` and `chmod` the download and incomplete dirs provided by users

### PR DESCRIPTION
**Pull request by umazalakain**

### CODE REVIEW

**Comment by bjornfor** [comment]
There is a possible corner case here. If the user does not specify ```services.transmission.settings.download-dir```, I think (s)he will receive an ugly traceback... Can you test it?

(Nitpick, please keep diffs as small as possible. There are two irrelevant hunks in there.)

**Comment by unaizalakain** [comment]
It builds correctly, `services.transmission.settings.download-dir` defaults to `/var/lib/transmission/Downloads`.

I thought that, while I was at it, I could remote that trailing space.

**Comment by bjornfor** [comment]
But if user sets ```services.transmission.settings = { foo = ...; }``` then ```services.transmission.settings.download-dir``` will not exist. (To check if download-dir exists, try ```cfg.settings ? download-dir```.)

**Comment by unaizalakain** [comment]
I have manually tested it by setting `services.transmission.settings` to the following values:
- `{}`
- `{download-dir = "/tmp/something";}`
- `{incomplete-dir = "/tmp/something";}`
- `{encryption = 1;}`

All of them derive in `download-dir` and `incomplete-dir` being set to their default value unless otherwise specified. From that I understand that one of those magic attribute map merges is happening.

Apart from checking the end result (which seems to indicate that, effectively, it works), how can I debug the build of a derivation and output that `cfg.settings ? download-dir`?

**Comment by devhell** [comment]
Are there plans to merge this?

**Comment by bjornfor** [comment]
I just tested this with a config _not_ specifying download-dir (i.e. relying on the nixos module default). Then it blows up (just like I feared):

```
$ cd $NIXPKGS/nixos
$ nix-build -A config.systemd.units.\"transmission.service\".unit
error: attribute ‘download-dir’ missing, at /home/bfo/nixpkgs/nixos/modules/services/torrent/transmission.nix:86:73
(use ‘--show-trace’ to show detailed location information)
```

@unaizalakain: I think you need to use some form of ```cfg.settings ? download-dir```.

**Comment by bjornfor** [comment]
@unaizalakain: A nice way to debug the unit is like this:

```
$ grep ExecStartPre $(nix-build -A config.systemd.units.\"transmission.service\".unit)/*
these derivations will be built:
  /nix/store/iyfgfrrayb2hgyzdm5wj964hb3m9l6ig-unit-transmission.service.drv
building path(s) ‘/nix/store/wigjz0lbaax65b0yhqki6rrw6qk30555-unit-transmission.service’
ExecStartPre=/nix/store/disi5277lygfj6m7m3ajwvvp9mqdp4la-bash-4.3-p42/bin/bash -c "mkdir -p /var/lib/transmission /var/lib/transmission/.config/transmission-daemon /srv/torrents/ /srv/torrents/.incomplete/ && chmod 770 /var/lib/transmission %{settingsDir} /srv/torrents/ /srv/torrents/.incomplete/ && rm -f /var/lib/transmission/.config/transmission-daemon/settings.json && cp -f /nix/store/hdk094xlxzvbszxdx0hq9avql0laz8rd-settings.json /var/lib/transmission/.config/transmission-daemon/settings.json"
```

**Comment by vcunat** [comment]
Ping.

**Comment by bjornfor** [comment]
Just for the record. I'm a bit unsure whether I like the idea that transmission should be able to create directories outside of /var/lib/transmission ($HOME). I guess there are good arguments both for and against it. But if a working patch is sent, I can merge.

**Comment by unaizalakain** [comment]
I was planning to update the PR this weekend but other stuff came up, it's on my todo list though.

Regarding the creation of dirs outside `/var/lib/transmission`: it's not transmission which creates the dirs, and it requires the user to explicitly say they want to use that dir. If I recall correctly, other services do a similar thing.

**Comment by unaizalakain** [comment]
I solved it by creating a default attribute map with both complete and incomplete download directories and overriding it with user changes. What do you think?

**Comment by bjornfor** [comment]
Looks good. I pushed it to master (09bdfd5c35eb38bd1530f92bdc09574e6adedb28) after fixing a small typo and changing the commit message.

**Comment by unaizalakain** [comment]
Oh, sorry about that, and thanks ;-)

**Pull request closed without merging**
