### PR TITLE
Update Raspberry Pi packages

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Motivation for this change

This supersedes #144649 by @leo60228. Tested by booting an SD image on a Pi Zero 2 W:

```nix
let
  pkgs = import ./. {
    system = "aarch64-linux";
    overlays = [
      (final: super: {
        makeModulesClosure = x:
        super.makeModulesClosure (x // { allowMissing = true; });
      })
    ];
  };
  configuration = { pkgs, modulesPath, ... }: {
    imports = [
      (modulesPath + "/installer/sd-card/sd-image-aarch64-installer.nix")
    ];

    boot.kernelPackages = pkgs.linuxPackages_rpi3;
  };
  nixos = pkgs.nixos configuration;
in nixos.config.system.build.sdImage
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Possibly a dupe of #154389? Also, it might be worth adding `arm_boost=1` to the default `config.txt` so newer Pis get a free overclock.

**Comment by zhaofengli** [comment]
Well, this is what happens when things take too long to merge. Either way, the last two commits need to be cherry-picked for Pi Zero 2 W support.

**Comment by colemickens** [comment]
Note that for the rpi firmware package, I had to switch the fetcher to fetchurl, disable unpacking to avoid some Darwin sha256 mismatch due to FS+unicode issues that I don't understand well enough to explain. You can steal that from my PR if you want the CI to go green for this PR.

**Comment by zhaofengli** [comment]
Should we merge this now?

**Comment by colemickens** [comment]
I'm in favor of merging.

**Comment by ereslibre** [comment]
I own a Raspberry Pi 4 B and a Raspberry Pi Zero 2 W. I have built an sdcard image for them with this two expressions:

- Raspberry Pi 4B: https://gist.github.com/ereslibre/594494ef4403b0e534726308f34f49a9
- Raspberry Pi Zero 2W: https://gist.github.com/ereslibre/6aee16b55f785837f53849b33382a78b

Both generated an `zst` under `sd-image`. Flashed them to sdcards and booted in the right machine.

I can confirm both machines booted fine. I have not done more thorough tests, but I plan to use this images from now on.

Let me know if you want me to do any other tests, or if you want me to streamline some nix expression I have pasted here for you to gather more information.

**Review by samueldr — APPROVED** [review]
Changes look okay.

Approving / Merging on the account of multiple successful reviews.

**Pull request merged**
