### PR TITLE
mariadb: 10.3.18 -> 10.3.20

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Version bump. Replace https://github.com/NixOS/nixpkgs/pull/71713.

Reading the [release notes](https://mariadb.com/kb/en/library/mariadb-10319-release-notes/) I'm left with the impression this bump contains security fixes, but when I actually look at the mentioned CVEs only `mysql` is mentioned... :man_shrugging: 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test mysql

**Comment by aanderse** [comment]
Unsure on `darwin` failure and currently no ability to look into it.

**Review by jonringer — COMMENTED** [review]
remove the darwin optional patch to potentially fix the darwin build. It's failing because the patch was already "successfully" applied (i.e. that commit is now in the source)

**Review by Br1ght0ne — APPROVED** [review]
Works fine on NixOS. Leaving MacOS issues to other maintainers.

**Comment by lilyball** [comment]
I've dug into this on darwin and I can confirm that the patch is already present in this version of mariadb and can simply be removed.

Similarly the patch appears to be present in version 3.1.5 of mariadb-connector-c, which this PR doesn't update but whoever does update that should be aware.

**Comment by jonringer** [comment]
I could do that as part of #71860

**Comment by lilyball** [comment]
```diff
diff --git a/pkgs/servers/sql/mariadb/default.nix b/pkgs/servers/sql/mariadb/default.nix
index dbb7f2e3fff..77413b825c6 100644
--- a/pkgs/servers/sql/mariadb/default.nix
+++ b/pkgs/servers/sql/mariadb/default.nix
@@ -46,12 +46,7 @@ common = rec { # attributes common to both builds
   patches = [
     ./cmake-includedir.patch
     ./cmake-libmariadb-includedir.patch
-  ] ++ optional stdenv.hostPlatform.isDarwin (fetchpatch {
-    url = "https://github.com/MariaDB/mariadb-connector-c/commit/ee91b2c98a63acb787114dee4f2694e154630928.patch";
-    extraPrefix = "libmariadb/";
-    sha256 = "06i865zwyhs9fvrgmargzn09pbg1cmably3c4wifd241bj8ig8qk";
-    stripLen = 1;
-  });
+  ];
 
   cmakeFlags = [
     "-DBUILD_CONFIG=mysql_release"
```

With this diff applied I've gotten past the patch phase and am currently in the process of building.

**Comment by lilyball** [comment]
Build failed:

```
builder for '/nix/store/8pm4jr9cji1yfk6gfbi1bazkssbgbh1a-mariadb-server-10.3.18.drv' failed with exit code 2; last 10 log lines:
        _auth_sha256_client in sha256_pw.c.o
    "_RSA_public_encrypt", referenced from:
        _auth_sha256_client in sha256_pw.c.o
    "_RSA_size", referenced from:
        _auth_sha256_client in sha256_pw.c.o
  ld: symbol(s) not found for architecture x86_64
  clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [libmariadb/CMakeFiles/sha256_password.dir/build.make:84: libmariadb/sha256_password.so] Error 1
  make[1]: *** [CMakeFiles/Makefile2:605: libmariadb/CMakeFiles/sha256_password.dir/all] Error 2
  make: *** [Makefile:152: all] Error 2
cannot build derivation '/nix/store/58axybx0k1gg4svqqh4k25wyaavirj8s-env.drv': 1 dependencies couldn't be built
[0 built (1 failed), 1 copied (68.6 MiB), 62.7 MiB DL]
error: build of '/nix/store/58axybx0k1gg4svqqh4k25wyaavirj8s-env.drv' failed
1 package failed to build:
mariadb
```

**Comment by lilyball** [comment]
Though now I'm wondering why the build failure said `10.3.18`. I used `nix-review` off of the current working tree.

**Comment by lilyball** [comment]
Ok forget that failure. I suspect what happened was `nix-review` just applied my staged changes (removing the patch) on top of the current nixpkgs instead of using the commit I had checked out. That would be explained by a variable named `CRYPT_LIBS` being broken. I'll let you know when my rebuild finishes.

**Comment by Izorkin** [comment]
I am added update MariaDB to 10.3.20 in https://github.com/NixOS/nixpkgs/pull/70924

**Comment by lilyball** [comment]
This build takes a long time and I need to run. I'm cancelling my build, but suffice to say it got well past `sha256_password` (the spurious failure reported before). I'll let ofBorg deal with rebuilding this after the patch is removed, or with building #70924 instead.

**Comment by aanderse** [comment]
@Izorkin I'm not sure what the state of your other PR is, but it has been sitting for a while. Since this is a security update I think it makes sense to have a very simple PR which can be merged quickly and have a backport in good time.

If your other PR is merged before this one that is fine too. Whatever gets security release faster is what we can go with.

@lilyball so this PR should be good to go on `darwin` now that I have updated... maybe? :smile: 

@filalex77 @jonringer @lilyball @Izorkin thanks for feedback so far. I had a busy day and didn't get a chance to respond so I appreciate the work you put in on this :tada:

**Comment by lilyball** [comment]
Looks like ofBorg successfully built this on darwin 🎉

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM

```
https://github.com/NixOS/nixpkgs/pull/73267
1 package are marked as broken and were skipped:
unixODBCDrivers.mysql

49 package were build:
akonadi akregator automysqlbackup diesel-cli digikam kaddressbook kdeApplications.akonadi-calendar kdeApplications.akonadi-contacts kdeApplications.akonadi-import-wizard kdeApplications.akonadi-mime kdeApplications.akonadi-notes kdeApplications.akonadi-search kdeApplications.akonadiconsole kdeApplications.calendarsupport kdeApplications.eventviews kdeApplications.incidenceeditor kdeApplications.kalarm kdeApplications.kalarmcal kdeApplications.kdepim-addons kdeApplications.kdepim-apps-libs kdeApplications.kdepim-runtime kgpg kmail kdeApplications.kmail-account-wizard kdeApplications.kmailtransport kdeApplications.knotes kontact korganizer kdeApplications.libgravatar kdeApplications.libkdepim kdeApplications.libksieve kdeApplications.mailcommon kdeApplications.mailimporter kdeApplications.mbox-importer kdeApplications.messagelib kdeApplications.pim-data-exporter kdeApplications.pim-sieve-editor kdeApplications.pimcommon kmymoney lua51Packages.luadbi-mysql luaPackages.luadbi-mysql lua53Packages.luadbi-mysql luajitPackages.luadbi-mysql mysql shmig snabb trojita zanshin zoneminder
```

**Comment by jonringer** [comment]
@GrahamcOfBorg test mysql

**Comment by jonringer** [comment]
the tests passed locally

**Comment by aanderse** [comment]
Thanks again, all! :tada:

**Comment by aanderse** [comment]
Right... security fixes included. Anyone interested in doing backport? :heart:

**Pull request merged**
