### PR TITLE
gvfs: security fixes

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
See commits

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Is a0da5f16feda323c29850c495acd86dfc8fbb262 not needed?

**Comment by worldofpeace** [comment]
> Is https://gitlab.gnome.org/GNOME/gvfs/commit/a0da5f16feda323c29850c495acd86dfc8fbb262 not needed?

I looked pretty close at the commits assigned for the CVE's and all the commits in https://gitlab.gnome.org/GNOME/gvfs/merge_requests/48/commits are assigned. Since it wasn't a part of the pr it's probably just another improvement.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build gnome3.gvfs gvfs

**Comment by jtojnar** [comment]
Right, did not see it anywhere either. Not including is probably fine.

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
