### PR TITLE
bluespec: unstable-2020.02.09 -> unstable-2020.04.03

### PR DESCRIPTION
**Pull request by flokli**
This bumps bluespec to the latest version, which now doesn't use the
bundled tcl anymore (so we use the nixpkgs-provided one).

STP can also be easily stubbed away, by setting STP_STUB=1.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
This currently still fails in the smoketest:

```
Comparing result of Bluespec Simulation
Some simulator specific difference expected
./mkFibOne.bexe > smoke_test_bluesim.out
Unable to start itcl -- Can't find a usable itcl.tcl in the following directories:
    /nix/store/049inb6w0w1pmm8sa2addwqvg10p75jc-tcl-8.6.9/lib/itcl4.2.0 ./library /build/source/inst/bin/core/../lib/itcl4.2.0 /build/source/inst/bin/core/../library /build/source/inst/bin/core/../../library /build/source/inst/bin/core/../../itcl/library /build/source/inst/bin/core/../../../itcl/library /build/source/inst/bin/core/../../itcl-ng/itcl/library /nix/store/049inb6w0w1pmm8sa2addwqvg10p75jc-tcl-8.6.9/lib /nix/store/049inb6w0w1pmm8sa2addwqvg10p75jc-tcl-8.6.9/lib/itcl4.2.0
This probably means that Itcl/Tcl weren't installed properly.
If you know where the Itcl library directory was installed,
you can set the environment variable ITCL_LIBRARY to point
to the library directory.

./mkFibOne.bexe: exec: line 12: /tcllib/bluespec/bluesim.tcl: not found
make[1]: *** [Makefile:103: smoke_test_bluesim] Error 127
make[1]: *** Waiting for unfinished jobs....
diff mkFibOne.out.expected smoke_test_verilog.out

Bluespec installation looks OK
make[1]: Leaving directory '/build/source/examples/smoke_test'
make: *** [Makefile:34: check] Error 2
builder for '/nix/store/70zx65r4lbmicbabxngybmfmqmrvjas4-bluespec-unstable-2020.04.03.drv' failed with exit code 2
```

**Comment by flokli** [comment]
@thoughtpolice will you be able to take a look at this?

**Comment by thoughtpolice** [comment]
@flokli Yes, very sorry about my latency recently. I've still got some patches I need to submit upstream to Julie before we can move forward here, sorry! I'll try to do that later today.

**Comment by flokli** [comment]
@thoughtpolice no worries, do whenever you have the time for it.

Also, let me know when you need someone reviewing some of these patches :-)

**Review by bhipple — CHANGES_REQUESTED** [review]
Waiting for @thoughtpolice as mentioned above.

**Comment by flokli** [comment]
I won't be able to pick this up any time soon, and just opened #103487.

**Pull request closed without merging**
