### PR TITLE
ecs-agent: 1.14.0 -> 1.18.0-1

### PR DESCRIPTION
**Pull request by andreabedini**
###### Motivation for this change

version update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build ecs-agent

**Comment by xeji** [comment]
download fails, please check source URL (could be a temporary failure)

**Comment by andreabedini** [comment]
@GrahamcOfBorg build ecs-agent
@xeji thx, fixed

**Comment by andreabedini** [comment]
@GrahamcOfBorg build ecs-agent

**Comment by xeji** [comment]
@GrahamcOfBorg build ecs-agent

**Comment by andreabedini** [comment]
<3

**Pull request merged**
