### PR TITLE
aliases: cleanup throws from before 2023-01-01

### PR DESCRIPTION
**Pull request by fabianhjr**
## Things done

```
git diff HEAD~3..HEAD | rg -i preserve         2600ms  Sun 01 Oct 2023 01:44:41 PM CST
   fetchFromGithub = throw "You meant fetchFromGitHub, with a capital H"; # preserve
   fuse2fs = if stdenv.isLinux then e2fsprogs.fuse2fs else null; # Added 2022-03-27 preserve, reason: convenience, arch has a package named fuse2fs too.
   wormhole-rs = magic-wormhole-rs; # Added 2022-05-30. preserve, reason: Arch package name, main binary name
```

```
./maintainers/scripts/rebuild-amount.sh HEAD~3 1473ms  Sun 01 Oct 2023 01:38:16 PM CST
Estimating rebuild amount by counting changed Hydra jobs (parallel=unset).
```

empty output after 6mins

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mindavi — APPROVED** [review]

**Comment by Mindavi** [comment]
Diff looks good and I think it's been long enough for these.

**Comment by Artturin** [comment]
I can't recall if there was a thing about keeping 2 releases worth of throws, the process doesn't seem to be documented anywhere and the last time removing was done it resulted in https://github.com/NixOS/nixpkgs/pull/196001

**Comment by fabianhjr** [comment]
On that revert it seems the issue came more from converting working aliases to throws, examples from 192681:

```
- ConfigArgParse = configargparse; # added 2021-03-18
+ ConfigArgParse = throw "'ConfigArgParse' has been renamed to/replaced by 'configargparse'"; # Converted to throw 2022-09-24
- dateutil = python-dateutil; # added 2021-07-03
+ dateutil = throw "'dateutil' has been renamed to/replaced by 'python-dateutil'"; # Converted to throw 2022-09-24
- diff_cover = diff-cover; # added 2021-07-02
+ diff_cover = throw "'diff_cover' has been renamed to/replaced by 'diff-cover'"; # Converted to throw 2022-09-24
```

and 192870 drops a throw less than a month after creation. In this case these throws have been in aliases for at least 10 months.

**Comment by fabianhjr** [comment]
On than revert the policy seems to be at least 1 release between stages of deprecation.

https://github.com/NixOS/nixpkgs/issues/195702

> Deprecation first needs a warning, then an error, then a removal, each of which separated by at least one release if not more.

So all of these throws should already be in 23.05 and could be removed for 23.11.

**Comment by vcunat** [comment]
For reference, the release wiki [contains](https://nixos.github.io/release-wiki/Feature-Freeze-Announcement.html#pre-release-cleanup) a very conservative step:
> Attributes that can also be safely removed are packages that were broken for more than 2 years.

**Comment by fabianhjr** [comment]
My understanding would be that if something has been broken for that long it could skip the deprecation phases of turning to warning, turning to throw, removing.

**Comment by Mindavi** [comment]
I disagree with 'we need to have a warning first' since we don't have infrastructure and that shouldn't cause stagnation in cleaning up. This process is good enough for now to at least be able to do cleanups. I do agree with aliases in 1 release, then throws in the next, then removal.

**Comment by fabianhjr** [comment]
infinisil comment points to a 1 release requirement for throw removal.

From the release wiki the removal of throws was 1 release as well:

> - Remove old aliases that have been `throw`s for at least one release.

From https://github.com/NixOS/release-wiki/pull/60/commits/392ae703c8f83ec917999cc1b895f880d7e7c352

To recap, this PR removes throws that have been in aliases for over 10 months (at least 1 release) and doesn't convert any working alias to a throw.

I believe this is in line with current deprecation expectations and won't cause (new) downstream breakage.

**Comment by fabianhjr** [comment]
`git show HEAD~2 --unified=0 | rg -v "(throw|@@)"`

```
--- a/pkgs/top-level/aliases.nix
+++ b/pkgs/top-level/aliases.nix
-  nodejs-10_x = nodejs_10; # Added 2022-11-06
-  nodejs-12_x = nodejs_12; # Added 2022-11-06
-  percona-server = percona-server56; # Added 2022-11-01
-  # postgresql
-  postgresql96 = postgresql_9_6;
-  slurm-llnl-full = slurm-full; # renamed July 2017
```

nodejs_10 and nodejs_12 were throws:

```
-  nodejs_10 = throw "nodejs-10_x has been removed. Use a newer version instead."; # Added 2022-05-31
-  nodejs-10_x = nodejs_10; # Added 2022-11-06
-  nodejs_12 = throw "nodejs-12_x has been removed. Use a newer version instead."; # Added 2022-07-04
-  nodejs-12_x = nodejs_12; # Added 2022-11-06
```

precona-server was throw:

```
-  percona-server = percona-server56; # Added 2022-11-01
-  percona-server56 = throw "'percona-server56' has been dropped due to lack of maintenance, no upstream support and security issues"; # Added 2022-11-01
```

postgresql_9_6 was throw:

```
-  postgresql96 = postgresql_9_6;
-  postgresql_9_6 = throw "postgresql_9_6 has been removed from nixpkgs, as this version is no longer supported by upstream"; # Added 2021-12-03
```

slurm-full was throw:

```
-  slurm-full = throw "'slurm-full' has been renamed to/replaced by 'slurm'"; # Converted to throw 2022-02-22
-  slurm-llnl-full = slurm-full; # renamed July 2017
```

HEAD~1 has a lot of multiline throws / aliases to throws. Can't think of a quick check other than manual review of that commit.

HEAD removes a throw from a nixpkgs derivation (gnome2) and results in 0 rebuilds.

**Comment by Mindavi** [comment]
Let's do this! Needs a rebase already so I think it's good to not let this hang for too long 🙂. And we seem to agree here.

**Comment by fabianhjr** [comment]
Solving conflict

**Comment by fabianhjr** [comment]
<details>
<summary>Conflict</summary>

```
diff --cc pkgs/top-level/aliases.nix
index 608e7f5b29a4,0f3375d22d7a..000000000000
--- a/pkgs/top-level/aliases.nix
+++ b/pkgs/top-level/aliases.nix
@@@ -77,56 -65,16 +65,36 @@@ mapAliases (
    alsaPlugins = alsa-plugins; # Added 2021-06-10
    alsaTools = alsa-tools; # Added 2021-06-10
    alsaUtils = alsa-utils; # Added 2021-06-10
-   amazon-glacier-cmd-interface = throw "amazon-glacier-cmd-interface has been removed due to it being unmaintained"; # Added 2020-10-30
-   aminal = throw "aminal was renamed to darktile"; # Added 2021-09-28
-   ammonite-repl = throw "'ammonite-repl' has been renamed to/replaced by 'ammonite'"; # Converted to throw 2022-02-22
-   amuleDaemon = throw "amuleDaemon was renamed to amule-daemon"; # Added 2022-02-11
-   amsn = throw "amsn has been removed due to being unmaintained"; # Added 2020-12-09
-   amuleGui = throw "amuleGui was renamed to amule-gui"; # Added 2022-02-11
    angelfish = libsForQt5.kdeGear.angelfish; # Added 2021-10-06
-   ansible_2_10 = throw "Ansible 2.10 went end of life in 2022/05 and has subsequently been dropped"; # Added 2022-03-30
-   ansible_2_11 = throw "Ansible 2.11 goes end of life in 2022/11 and can't be supported throughout the 22.05 release cycle"; # Added 2022-03-30
    ansible_2_12 = throw "Ansible 2.12 goes end of life in 2023/05 and can't be supported throughout the 23.05 release cycle"; # Added 2023-05-16
-   ansible_2_9 = throw "Ansible 2.9 went end of life in 2022/05 and has subsequently been dropped"; # Added 2022-03-30
-   animbar = throw "animbar has been removed, because it was unmaintained"; # Added 2022-05-26
-   antimicro = throw "antimicro has been removed as it was broken, see antimicrox instead"; # Added 2020-08-06
    antimicroX = antimicrox; # Added 2021-10-31
-   apple-music-electron = throw "'apple-music-electron' is end of life and has been removed, you can use 'cider' instead"; # Added 2022-10-02
-   appleseed = throw "appleseed has been removed, because it was unmaintained"; # Added 2022-05-26
-   arangodb_3_3 = throw "arangodb_3_3 went end of life and has been removed"; # Added 2022-10-08
-   arangodb_3_4 = throw "arangodb_3_4 went end of life and has been removed"; # Added 2022-10-08
-   arangodb_3_5 = throw "arangodb_3_5 went end of life and has been removed"; # Added 2022-10-08
-   ardour_5 = throw "ardour_5 has been removed. see https://github.com/NixOS/nixpkgs/issues/139549"; # Added 2021-09-28
-   arduino_core = throw "'arduino_core' has been renamed to/replaced by 'arduino-core'"; # Converted to throw 2022-02-22
-   arora = throw "arora has been removed"; # Added 2020-09-09
-   asciidocFull = throw "'asciidocFull' has been renamed to/replaced by 'asciidoc-full'"; # Converted to throw 2022-02-22
    aseprite-unfree = aseprite; # Added 2023-08-26
    asls = throw "asls has been removed: abandoned by upstream"; # Added 2023-03-16
-   asterisk_13 = throw "asterisk_13: Asterisk 13 is end of life and has been removed"; # Added 2022-04-06
-   asterisk_15 = throw "asterisk_15: Asterisk 15 is end of life and has been removed"; # Added 2020-10-07
    asterisk_16 = throw "asterisk_16: Asterisk 16 is end of life and has been removed"; # Added 2023-04-19
-   asterisk_17 = throw "asterisk_17: Asterisk 17 is end of life and has been removed"; # Added 2022-04-06
    asterisk_19 = throw "asterisk_19: Asterisk 19 is end of life and has been removed"; # Added 2023-04-19
++<<<<<<< HEAD
 +  at_spi2_atk = throw "'at_spi2_atk' has been renamed to/replaced by 'at-spi2-atk'"; # Converted to throw 2022-02-22
 +  at_spi2_core = throw "'at_spi2_core' has been renamed to/replaced by 'at-spi2-core'"; # Converted to throw 2022-02-22
 +  atom = throw "'atom' has been removed because discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  atom-beta = throw "'atom-beta' has been removed because discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  atomEnv = throw "'atomEnv' has been removed because 'atom' is discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  atomPackages = throw "'atomPackages' has been removed because 'atom' is discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  aucdtect = throw "aucdtect: Upstream no longer provides download urls"; # Added 2020-12-26
 +  audacity-gtk2 = throw "'audacity-gtk2' has been removed to/replaced by 'audacity'"; # Added 2022-10-09
 +  audacity-gtk3 = throw "'audacity-gtk3' has been removed to/replaced by 'audacity'"; # Added 2022-10-09
 +  automoc4 = throw "automoc4 has been removed from nixpkgs"; # Added 2022-05-30
++||||||| parent of 3dc9d4413ac9 (aliases: cleanup throws from before or at 2023-01-01)
++  at_spi2_atk = throw "'at_spi2_atk' has been renamed to/replaced by 'at-spi2-atk'"; # Converted to throw 2022-02-22
++  at_spi2_core = throw "'at_spi2_core' has been renamed to/replaced by 'at-spi2-core'"; # Converted to throw 2022-02-22
++  aucdtect = throw "aucdtect: Upstream no longer provides download urls"; # Added 2020-12-26
++  audacity-gtk2 = throw "'audacity-gtk2' has been removed to/replaced by 'audacity'"; # Added 2022-10-09
++  audacity-gtk3 = throw "'audacity-gtk3' has been removed to/replaced by 'audacity'"; # Added 2022-10-09
++  automoc4 = throw "automoc4 has been removed from nixpkgs"; # Added 2022-05-30
++=======
++>>>>>>> 3dc9d4413ac9 (aliases: cleanup throws from before or at 2023-01-01)
    avldrums-lv2 = x42-avldrums; # Added 2020-03-29
-   avogadro = throw "avogadro has been removed, because it depended on qt4"; # Added 2022-06-12
-   avxsynth = throw "avxsynth was removed because it was broken"; # Added 2021-05-18
    awesome-4-0 = awesome; # Added 2022-05-05
-   aws = throw "aws has been removed: abandoned by upstream. For the AWS CLI maintained by Amazon, see 'awscli' or 'awscli2'"; # Added 2022-09-21
-   awless = throw "awless has been dropped due to the lack of maintenance from upstream since 2018"; # Added 2022-05-30
    aws-okta = throw "aws-okta is on indefinite hiatus. See https://github.com/segmentio/aws-okta/issues/278"; # Added 2022-04-05;
-   axoloti = throw "axoloti has been removed: abandoned by upstream"; # Added 2022-05-13
-   azure-vhd-utils = throw "azure-vhd-utils has been dropped due to the lack of maintenance from upstream since 2018"; # Added 2022-06-03
-   azureus = throw "azureus is now known as vuze and the version in nixpkgs was really outdated"; # Added 2021-08-02
  
    ### B ###
```
</details>

<details>
<summary>Resolution</summary>

```
diff --cc pkgs/top-level/aliases.nix
index 608e7f5b29a4,0f3375d22d7a..000000000000
--- a/pkgs/top-level/aliases.nix
+++ b/pkgs/top-level/aliases.nix
@@@ -77,56 -65,16 +65,20 @@@ mapAliases (
    alsaPlugins = alsa-plugins; # Added 2021-06-10
    alsaTools = alsa-tools; # Added 2021-06-10
    alsaUtils = alsa-utils; # Added 2021-06-10
-   amazon-glacier-cmd-interface = throw "amazon-glacier-cmd-interface has been removed due to it being unmaintained"; # Added 2020-10-30
-   aminal = throw "aminal was renamed to darktile"; # Added 2021-09-28
-   ammonite-repl = throw "'ammonite-repl' has been renamed to/replaced by 'ammonite'"; # Converted to throw 2022-02-22
-   amuleDaemon = throw "amuleDaemon was renamed to amule-daemon"; # Added 2022-02-11
-   amsn = throw "amsn has been removed due to being unmaintained"; # Added 2020-12-09
-   amuleGui = throw "amuleGui was renamed to amule-gui"; # Added 2022-02-11
    angelfish = libsForQt5.kdeGear.angelfish; # Added 2021-10-06
-   ansible_2_10 = throw "Ansible 2.10 went end of life in 2022/05 and has subsequently been dropped"; # Added 2022-03-30
-   ansible_2_11 = throw "Ansible 2.11 goes end of life in 2022/11 and can't be supported throughout the 22.05 release cycle"; # Added 2022-03-30
    ansible_2_12 = throw "Ansible 2.12 goes end of life in 2023/05 and can't be supported throughout the 23.05 release cycle"; # Added 2023-05-16
-   ansible_2_9 = throw "Ansible 2.9 went end of life in 2022/05 and has subsequently been dropped"; # Added 2022-03-30
-   animbar = throw "animbar has been removed, because it was unmaintained"; # Added 2022-05-26
-   antimicro = throw "antimicro has been removed as it was broken, see antimicrox instead"; # Added 2020-08-06
    antimicroX = antimicrox; # Added 2021-10-31
-   apple-music-electron = throw "'apple-music-electron' is end of life and has been removed, you can use 'cider' instead"; # Added 2022-10-02
-   appleseed = throw "appleseed has been removed, because it was unmaintained"; # Added 2022-05-26
-   arangodb_3_3 = throw "arangodb_3_3 went end of life and has been removed"; # Added 2022-10-08
-   arangodb_3_4 = throw "arangodb_3_4 went end of life and has been removed"; # Added 2022-10-08
-   arangodb_3_5 = throw "arangodb_3_5 went end of life and has been removed"; # Added 2022-10-08
-   ardour_5 = throw "ardour_5 has been removed. see https://github.com/NixOS/nixpkgs/issues/139549"; # Added 2021-09-28
-   arduino_core = throw "'arduino_core' has been renamed to/replaced by 'arduino-core'"; # Converted to throw 2022-02-22
-   arora = throw "arora has been removed"; # Added 2020-09-09
-   asciidocFull = throw "'asciidocFull' has been renamed to/replaced by 'asciidoc-full'"; # Converted to throw 2022-02-22
    aseprite-unfree = aseprite; # Added 2023-08-26
    asls = throw "asls has been removed: abandoned by upstream"; # Added 2023-03-16
-   asterisk_13 = throw "asterisk_13: Asterisk 13 is end of life and has been removed"; # Added 2022-04-06
-   asterisk_15 = throw "asterisk_15: Asterisk 15 is end of life and has been removed"; # Added 2020-10-07
    asterisk_16 = throw "asterisk_16: Asterisk 16 is end of life and has been removed"; # Added 2023-04-19
-   asterisk_17 = throw "asterisk_17: Asterisk 17 is end of life and has been removed"; # Added 2022-04-06
    asterisk_19 = throw "asterisk_19: Asterisk 19 is end of life and has been removed"; # Added 2023-04-19
-   at_spi2_atk = throw "'at_spi2_atk' has been renamed to/replaced by 'at-spi2-atk'"; # Converted to throw 2022-02-22
-   at_spi2_core = throw "'at_spi2_core' has been renamed to/replaced by 'at-spi2-core'"; # Converted to throw 2022-02-22
 +  atom = throw "'atom' has been removed because discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  atom-beta = throw "'atom-beta' has been removed because discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  atomEnv = throw "'atomEnv' has been removed because 'atom' is discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
 +  atomPackages = throw "'atomPackages' has been removed because 'atom' is discontinued and deprecated. Consider using 'pulsar', a maintained fork"; # Added 2023-10-01
-   aucdtect = throw "aucdtect: Upstream no longer provides download urls"; # Added 2020-12-26
-   audacity-gtk2 = throw "'audacity-gtk2' has been removed to/replaced by 'audacity'"; # Added 2022-10-09
-   audacity-gtk3 = throw "'audacity-gtk3' has been removed to/replaced by 'audacity'"; # Added 2022-10-09
-   automoc4 = throw "automoc4 has been removed from nixpkgs"; # Added 2022-05-30
    avldrums-lv2 = x42-avldrums; # Added 2020-03-29
-   avogadro = throw "avogadro has been removed, because it depended on qt4"; # Added 2022-06-12
-   avxsynth = throw "avxsynth was removed because it was broken"; # Added 2021-05-18
    awesome-4-0 = awesome; # Added 2022-05-05
-   aws = throw "aws has been removed: abandoned by upstream. For the AWS CLI maintained by Amazon, see 'awscli' or 'awscli2'"; # Added 2022-09-21
-   awless = throw "awless has been dropped due to the lack of maintenance from upstream since 2018"; # Added 2022-05-30
    aws-okta = throw "aws-okta is on indefinite hiatus. See https://github.com/segmentio/aws-okta/issues/278"; # Added 2022-04-05;
-   axoloti = throw "axoloti has been removed: abandoned by upstream"; # Added 2022-05-13
-   azure-vhd-utils = throw "azure-vhd-utils has been dropped due to the lack of maintenance from upstream since 2018"; # Added 2022-06-03
-   azureus = throw "azureus is now known as vuze and the version in nixpkgs was really outdated"; # Added 2021-08-02
  
    ### B ###
```
</details>

**Comment by fabianhjr** [comment]
If no opposition merging tomorrow morning (Americas/México_City) in about 15 hours.

**Pull request merged**
