### PR TITLE
furnace: 0.6pre7 -> 0.6.pre8

### PR DESCRIPTION
**Pull request by kashw2**
## Description of changes

change log: https://github.com/tildearrow/furnace/releases/tag/v0.6pre8

diff: https://github.com/tildearrow/furnace/compare/v0.6pre7...v0.6pre8

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kashw2** [comment]
Result of `nixpkgs-review pr 250293` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>furnace</li>
  </ul>
</details>

**Review by matthiasbeyer — APPROVED** [review]

**Comment by FavoritoHJS** [comment]
i am once again asking why the hell backports aren't the default.

**Comment by matthiasbeyer** [comment]
Not sure whether adding the label works after the PR was merged. Feel free to ping me if it doesn't...

**Comment by OPNA2608** [comment]
> i am once again asking why the hell backports aren't the default.

Because `stable` is supposed to not have the version of every package change all the time, so it is stable? I certainly don't want the version of every package to change on my stable system… That, and I really don't see the point in playing upstream's year-long pre-release game and backporting every new `0.6preX` release, as if they only provided critical bugfixes and not new features or other changes. If these were using semantic versioning and only providing patches, then I wouldn't mind backporting them… :confused:

image

If you always want the newest version of the package, using `nixos-unstable` would be the more logical choice. Either system-wide, or just for this package.

**Pull request merged**
