### PR TITLE
jumanpp: init at 1.02

### PR DESCRIPTION
**Pull request by mt-caret**
###### Motivation for this change

Adds JUMAN++, a morphological analyzer for Japanese.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build jumanpp

**Review by Mic92 — APPROVED** [review]

**Comment by Mic92** [comment]
Can you disable aarch64 for the meantime. the build system passes x86 only compiler flags.

**Comment by Mic92** [comment]
To make it work `-m64` would need to be removed. This could be reported upstream, by somebody with Japanese knowledge...

**Comment by mt-caret** [comment]
I just realized that there was a GitHub repo with much newer code (https://github.com/ku-nlp/jumanpp), I'll get that working first, so please don't merge yet :)

**Comment by mt-caret** [comment]
@Mic92 Everything should be working now (including aarch64 I assume, since the devs have switched to CMake)

**Comment by Mic92** [comment]
@GrahamcOfBorg build jumanpp

**Pull request merged**
