### PR TITLE
python3Packages.aresponses: 2.1.0 -> 2.1.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release

Change log: https://github.com/CircleUp/aresponses#212

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 109616` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>python37Packages.adguardhome</li>
    <li>python37Packages.aresponses</li>
    <li>python37Packages.pyairvisual</li>
    <li>python37Packages.pyipp</li>
    <li>python37Packages.pyiqvia</li>
    <li>python37Packages.pytile</li>
    <li>python37Packages.wled</li>
    <li>python38Packages.adguardhome</li>
    <li>python38Packages.aresponses</li>
    <li>python38Packages.pyairvisual</li>
    <li>python38Packages.pyhaversion</li>
    <li>python38Packages.pyipp</li>
    <li>python38Packages.pyiqvia</li>
    <li>python38Packages.pytile</li>
    <li>python38Packages.wled</li>
    <li>python39Packages.adguardhome</li>
    <li>python39Packages.aresponses</li>
    <li>python39Packages.pyhaversion</li>
    <li>python39Packages.pyipp</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109616` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
19 packages built:
</summary>
<ul>
<li>python37Packages.adguardhome</li>
<li>python37Packages.aresponses</li>
<li>python37Packages.pyairvisual</li>
<li>python37Packages.pyipp</li>
<li>python37Packages.pyiqvia</li>
<li>python37Packages.pytile</li>
<li>python37Packages.wled</li>
<li>python38Packages.adguardhome</li>
<li>python38Packages.aresponses</li>
<li>python38Packages.pyairvisual</li>
<li>python38Packages.pyhaversion</li>
<li>python38Packages.pyipp</li>
<li>python38Packages.pyiqvia</li>
<li>python38Packages.pytile</li>
<li>python38Packages.wled</li>
<li>python39Packages.adguardhome</li>
<li>python39Packages.aresponses</li>
<li>python39Packages.pyhaversion</li>
<li>python39Packages.pyipp</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109616` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>22 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.adguardhome: log was empty</li>
<li>python37Packages.aresponses: log <a href="https://termbin.com/xlk7">https://termbin.com/xlk7</a></li>
<li>python37Packages.pyairvisual: log was empty</li>
<li>python37Packages.pyipp: log was empty</li>
<li>python37Packages.pyiqvia: log was empty</li>
<li>python37Packages.pytile: log was empty</li>
<li>python37Packages.wled: log was empty</li>
<li>python38Packages.adguardhome: log was empty</li>
<li>python38Packages.aresponses: log <a href="https://termbin.com/sm1f">https://termbin.com/sm1f</a></li>
<li>python38Packages.pyairvisual: log was empty</li>
<li>python38Packages.pyhaversion: log was empty</li>
<li>python38Packages.pyipp: log was empty</li>
<li>python38Packages.pyiqvia: log was empty</li>
<li>python38Packages.pytile: log was empty</li>
<li>python38Packages.wled: log was empty</li>
<li>python39Packages.adguardhome: log was empty</li>
<li>python39Packages.aresponses: log <a href="https://termbin.com/lw3s">https://termbin.com/lw3s</a></li>
<li>python39Packages.pyairvisual: log was empty</li>
<li>python39Packages.pyhaversion: log was empty</li>
<li>python39Packages.pyipp: log was empty</li>
<li>python39Packages.pyiqvia: log was empty</li>
<li>python39Packages.wled: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
darwin patch
```diff
diff --git a/pkgs/development/python-modules/aresponses/default.nix b/pkgs/development/python-modules/aresponses/default.nix
index 68d96ea43d6..53353a13788 100644
--- a/pkgs/development/python-modules/aresponses/default.nix
+++ b/pkgs/development/python-modules/aresponses/default.nix
@@ -44,6 +44,8 @@ buildPythonPackage rec {
     "test_passthrough"
   ];

+  __darwinAllowLocalNetworking = true;
+
   pythonImportsCheck = [ "aresponses" ];

   meta = with lib; {
```

**Comment by fabaff** [comment]
> darwin patch

Added, thanks a lot.

**Pull request merged**
