### PR TITLE
 kicad-unstable: 2018-03-10 -> 2018-06-12

### PR DESCRIPTION
**Pull request by bgamari**
###### Motivation for this change

Just an update.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build kicad-unstable

**Comment by xeji** [comment]
Difficult to tell from the log which dependency failed. There's a hash mismatch in the `cmake` build:
```
fixed-output derivation produced path '/nix/store/sylxhlnpa4rzqm2hgz8mdxqq1d19sklh-source' with sha256 hash '1g1wp4w90ag81vrl2l8dxdgn03pqs1ng0ksawiq0imqgda8zry64' instead of the expected hash '1yn5hj5hjnpb5fkzzlyawg62a96fbfvha49305s22dcp95riqvf0'
```
but it continued anyway. Please investigate.

**Comment by bgamari** [comment]
Ahh, indeed; let's try this again.

**Comment by xeji** [comment]
@GrahamcOfBorg build kicad-unstable

**Pull request merged**
