### PR TITLE
[darwin] python3Packages.notebook: disable networking tests on darwin

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
https://hydra.nixos.org/build/160246991/nixlog/1

cc @NixOS/darwin-maintainers 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
I'm seeing the following error running `nixpkgs-review` on aarch64-darwin:
```
[nix-shell:~/dev/nixpkgs]$ nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/148507
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/148507/head:refs/nixpkgs-review/1
remote: Enumerating objects: 1136, done.
remote: Counting objects: 100% (652/652), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1136 (delta 639), reused 642 (delta 634), pack-reused 484
Receiving objects: 100% (1136/1136), 1.02 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (792/792), completed with 265 local objects.
From https://github.com/NixOS/nixpkgs
   99efa507e20..7a75191093d  master                -> refs/nixpkgs-review/0
   c192da17cc4..4ac472338e3  refs/pull/148507/head -> refs/nixpkgs-review/1
$ git worktree add /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs 7a75191093dc6b3c7fd8f3e3fe455c97c5ee5fb8
Preparing worktree (detached HEAD 7a75191093d)
Updating files: 100% (29086/29086), done.
HEAD is now at 7a75191093d Merge pull request #148484 from chuangzhu/image-roll
$ nix-env --option system aarch64-darwin -f /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit --no-ff 4ac472338e374fa969f37b8a93b1e3dc8dd8e2ae
Automatic merge went well; stopped before committing as requested
$ nix-env --option system aarch64-darwin -f /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs -qaP --xml --out-path --show-trace --meta
error: syntax error, unexpected '=', expecting ';'

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/pkgs/development/python-modules/notebook/default.nix:83:32:

           82|   # Some of the tests use localhost networking.
           83|   __darwinAllowLocalNetworking = true;
             |                                ^
           84|

       … while evaluating 'makeOverridable'

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:67:24:

           66|   */
           67|   makeOverridable = f: origArgs:
             |                        ^
           68|     let

       … from call site

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:121:8:

          120|       auto = builtins.intersectAttrs (lib.functionArgs f) autoArgs;
          121|     in makeOverridable f (auto // args);
             |        ^
          122|

       … while evaluating 'callPackageWith'

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:117:35:

          116|   */
          117|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          118|     let

       … from call site

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/pkgs/top-level/python-packages.nix:5247:14:

         5246|
         5247|   notebook = callPackage ../development/python-modules/notebook { };
             |              ^
         5248|

       … while evaluating 'toPythonModule'

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/pkgs/top-level/python-packages.nix:77:20:

           76|   # Convert derivation to a Python module.
           77|   toPythonModule = drv:
             |                    ^
           78|     drv.overrideAttrs( oldAttrs: {

       … from call site

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/pkgs/applications/editors/jupyter/default.nix:14:20:

           13|
           14| with python3.pkgs; toPythonModule (
             |                    ^
           15|   notebook.overridePythonAttrs(oldAttrs: {

       … while evaluating anonymous lambda

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/pkgs/applications/editors/jupyter/default.nix:3:1:

            2|
            3| { python3
             | ^
            4| , jupyter-kernel

       … from call site

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|

       … while evaluating 'makeOverridable'

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:67:24:

           66|   */
           67|   makeOverridable = f: origArgs:
             |                        ^
           68|     let

       … from call site

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:121:8:

          120|       auto = builtins.intersectAttrs (lib.functionArgs f) autoArgs;
          121|     in makeOverridable f (auto // args);
             |        ^
          122|

       … while evaluating 'callPackageWith'

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/lib/customisation.nix:117:35:

          116|   */
          117|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          118|     let

       … from call site

       at /Users/samuelainsworth/.cache/nixpkgs-review/pr-148507/nixpkgs/pkgs/top-level/all-packages.nix:6710:13:

         6709|
         6710|   jupyter = callPackage ../applications/editors/jupyter { };
             |             ^
         6711|
https://github.com/NixOS/nixpkgs/pull/148507 failed to build
$ git worktree prune

[nix-shell:~/dev/nixpkgs]$
```

**Comment by jonringer** [comment]
oops, that's what i get for just "eyballing" the code :/

**Review by samuela — APPROVED** [review]

**Comment by smaret** [comment]
Result of `nixpkgs-review pr 148507` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>36 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.Nikola</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.einops</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python38Packages.qiskit-finance</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.qiskit-ignis</li>
    <li>python38Packages.qiskit-machine-learning</li>
    <li>python38Packages.qiskit-optimization</li>
    <li>python38Packages.skein</li>
    <li>python39Packages.Nikola</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.einops</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-aqua</li>
    <li>python39Packages.qiskit-finance</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.qiskit-optimization</li>
    <li>python39Packages.skein</li>
  </ul>
</details>
<details>
  <summary>40 packages failed to build:</summary>
  <ul>
    <li>jupyter</li>
    <li>python38Packages.ipydatawidgets</li>
    <li>python38Packages.jupyterlab</li>
    <li>python38Packages.jupyterlab-git</li>
    <li>python38Packages.jupytext</li>
    <li>python38Packages.nbclient</li>
    <li>python38Packages.nbdime</li>
    <li>python38Packages.papermill</li>
    <li>python38Packages.scikit-tda</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.atomman</li>
    <li>python39Packages.cufflinks</li>
    <li>python39Packages.ipydatawidgets</li>
    <li>python39Packages.ipympl</li>
    <li>python39Packages.ipyvue</li>
    <li>python39Packages.ipyvuetify</li>
    <li>python39Packages.ipywidgets</li>
    <li>python39Packages.jupyter</li>
    <li>python39Packages.jupyter-sphinx</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab-git</li>
    <li>python39Packages.jupyterlab_launcher</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.kmapper</li>
    <li>python39Packages.lightparam</li>
    <li>python39Packages.nbclassic</li>
    <li>python39Packages.nbclient</li>
    <li>python39Packages.nbdime</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.notebook</li>
    <li>python39Packages.notedown</li>
    <li>python39Packages.papermill</li>
    <li>python39Packages.potentials</li>
    <li>python39Packages.pydeck</li>
    <li>python39Packages.qiskit-nature</li>
    <li>python39Packages.qiskit-terra</li>
    <li>python39Packages.scikit-tda</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.vega</li>
    <li>python39Packages.widgetsnbextension</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>python38Packages.ansible-kernel</li>
    <li>python38Packages.atomman</li>
    <li>python38Packages.cufflinks</li>
    <li>python38Packages.ipympl</li>
    <li>python38Packages.ipyvue</li>
    <li>python38Packages.ipyvuetify</li>
    <li>python38Packages.ipywidgets</li>
    <li>python38Packages.jupyter</li>
    <li>python38Packages.jupyter-sphinx</li>
    <li>python38Packages.jupyterlab_launcher</li>
    <li>python38Packages.kmapper</li>
    <li>python38Packages.lightparam</li>
    <li>python38Packages.nbclassic</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.notebook</li>
    <li>python38Packages.notedown</li>
    <li>python38Packages.potentials</li>
    <li>python38Packages.pydeck</li>
    <li>python38Packages.qiskit-nature</li>
    <li>python38Packages.qiskit-terra</li>
    <li>python38Packages.stytra</li>
    <li>python38Packages.vega</li>
    <li>python38Packages.widgetsnbextension</li>
  </ul>
</details>

**Comment by smaret** [comment]
Here is the error log for `notebook`:
```
error: builder for '/nix/store/wrbzsk6ls7m1rl9ap3x6wp64ma5k14cb-python3.9-notebook-6.4.4.drv' failed with exit code 2;
       last 10 log lines:
       > ERROR notebook/tests/test_files.py - AttributeError: dlsym(RTLD_DEFAULT, GetM...
       > ERROR notebook/tests/test_gateway.py - AttributeError: dlsym(RTLD_DEFAULT, Ge...
       > ERROR notebook/tests/test_notebookapp.py - AttributeError: dlsym(RTLD_DEFAULT...
       > ERROR notebook/tests/test_notebookapp_integration.py - AttributeError: dlsym(...
       > ERROR notebook/tests/test_paths.py - AttributeError: dlsym(RTLD_DEFAULT, GetM...
       > ERROR notebook/tests/test_serverextensions.py - AttributeError: dlsym(RTLD_DE...
       > ERROR notebook/tests/test_traittypes.py - AttributeError: dlsym(RTLD_DEFAULT,...
       > ERROR notebook/tree/tests/test_tree_handler.py - AttributeError: dlsym(RTLD_D...
       > !!!!!!!!!!!!!!!!!!! Interrupted: 19 errors during collection !!!!!!!!!!!!!!!!!!!
       > ================= 2 deselected, 1 warning, 19 errors in 4.06s ==================
```

**Comment by smaret** [comment]
It looks like an upstream bug: https://github.com/jupyterlab/jupyterlab/issues/9863

**Comment by smaret** [comment]
Indeed this was also reported here: https://github.com/NixOS/nixpkgs/issues/136485

**Comment by jonringer** [comment]
@smaret looks look this at least fixes some builds. Going to take this as an improvement :)

**Comment by jonringer** [comment]
the big sur related issues I think are being fixed at the cpython level as well.

**Pull request merged**
