### PR TITLE
k3s_1_29: 1.29.11+k3s1 -> 1.29.12+k3s1

### PR DESCRIPTION
**Pull request by rorosen**
https://github.com/k3s-io/k3s/releases/tag/v1.29.12%2Bk3s1

@NixOS/k3s 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rorosen** [comment]
1 package built:
k3s_1_29

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367386`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>k3s_1_29</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

- **Extra args**: `-p nixosTests.k3s`
- **Free space**: true
- **Who asked**: lucasew

**TARGETS**
- **x86_64-linux**: true
- **x86_64-darwin**: false
- **aarch64-darwin**: false

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12455870704

**Comment by lucasew** [comment]
Let's see if it goes recursive when -p points to an atteset

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

- **Extra args**: `-p nixosTests.k3s.airgap-images -p nixosTests.k3s.auto-deploy -p nixosTests.k3s.containerd-config -p nixosTests.k3s.etcd -p nixosTests.k3s.kubelet-config -p nixosTests.k3s.multi-node -p nixosTests.k3s.single-node`
- **Free space**: true
- **Who asked**: lucasew

**TARGETS**
- **x86_64-linux**: true
- **x86_64-darwin**: false
- **aarch64-darwin**: false

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12455983187

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

- **Extra args**: `-p nixosTests.k3s.airgap-images.k3s_1_29 -p nixosTests.k3s.auto-deploy.k3s_1_29 -p nixosTests.k3s.containerd-config.k3s_1_29 -p nixosTests.k3s.etcd.k3s_1_29 -p nixosTests.k3s.kubelet-config.k3s_1_29 -p nixosTests.k3s.multi-node.k3s_1_29 -p nixosTests.k3s.single-node.k3s_1_29`
- **Free space**: true
- **Who asked**: lucasew

**TARGETS**
- **x86_64-linux**: true
- **x86_64-darwin**: false
- **aarch64-darwin**: false

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12456328150

**Comment by lucasewd** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367386`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 7 tests built:</summary>
  <ul>
    <li>nixosTests.k3s.airgap-images.k3s_1_29</li>
    <li>nixosTests.k3s.auto-deploy.k3s_1_29</li>
    <li>nixosTests.k3s.containerd-config.k3s_1_29</li>
    <li>nixosTests.k3s.etcd.k3s_1_29</li>
    <li>nixosTests.k3s.kubelet-config.k3s_1_29</li>
    <li>nixosTests.k3s.multi-node.k3s_1_29</li>
    <li>nixosTests.k3s.single-node.k3s_1_29</li>
  </ul>
</details>

**Review by lucasew — APPROVED** [review]

**Pull request merged**
