### PR TITLE
sbcl: 1.4.7 -> 1.4.9; tested on nixos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg build sbcl

**Comment by 7c6f434c** [comment]
Any ideas what we need to change for aarch64 to work again? Or is there a reason/way to just disable something related to sb-concurrency?

**Comment by tohl** [comment]
It should work as threads are supported upstream on aarch64-linux and
apart from version bump, there were no changes in nixpkgs connected to
sbcl I think.

Unfortunately I can't see the log at
https://logs.nix.ci/?key=nixos/nixpkgs.42826&attempt_id=3369e726-9c3b-4618-9a3f-2c892eb5de88
as it doesn't work without Javascript.

I also don't have aarch64-linux machine to test this anymore.

It is also possible that sb-concurrency failure is transient.  Could it
be tested by grahamc just on aarch64-linux again?

Otherwise one could disable threadSupport on aarch64-linux.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build sbcl

**Comment by 7c6f434c** [comment]
`sb-concurrency` is a contrib module, it should be possible to nuke just it with less collateral damage than nuking threads completely.

https://gist.githubusercontent.com/7c6f434c/330a2d40f944191688a08ed522d8c77c/raw/15303b7cacccad94842d8c72d73cb67903d3f5d6/sbcl-1.4.9-aarch64.log

Weird results in the module test…

**Comment by 7c6f434c** [comment]
Hm, seems to be repeatable.

**Comment by tohl** [comment]
Michael Raskin <notifications@github.com> writes:
> `sb-concurrency` is a contrib module, it should be possible to nuke
> just it with less collateral damage than nuking threads completely.

probably sed make-target-contrib.sh and touch
obj/asdf-cache/sb-concurrency/test-passed.test-report at the right place

> https://gist.githubusercontent.com/7c6f434c/330a2d40f944191688a08ed522d8c77c/raw/15303b7cacccad94842d8c72d73cb67903d3f5d6/sbcl-1.4.9-aarch64.log

1 out of 25 total tests failed: SB-CONCURRENCY-TEST::FRLOCK.1.

maybe a timing problem

asking on irc #sbcl could give some ideas, e.g. if that is known issue

sometimes sbcl tests don't work on a platform and need to be marked
accordingly, but i would be surprised if this was the case here

sbcl 1.4.7 worked fine, but unfortunatelly i can't bisect this

**Comment by 7c6f434c** [comment]
Hm. Looks like an actual consistency problem. Need to look at upstream ML at some point…

**Comment by 7c6f434c** [comment]
1.4.10 seems to lack this problem (and 1.4.11 breaks Maxima…). With 1.4.10 in `master` I close this as «unclear whether there is an upstream problem»

**Pull request closed without merging**
