### PR TITLE
ffmpeg-full: 4.1.4 -> 4.2

### PR DESCRIPTION
**Pull request by primeos**
Changelog: https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/refs/heads/release/4.2:/Changelog

Configuration flag changes:
https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/n4.1.4..n4.2:/configure

Ignored new configuration flags:
--enable-libaribb24      enable ARIB text and caption decoding via libaribb24 [no]
--enable-pocketsphinx    enable PocketSphinx, needed for asr filter [no]
--enable-cuda-nvcc       enable Nvidia CUDA compiler [no]
--disable-cuda-llvm      disable CUDA compilation using clang [autodetect]
--disable-msa2           disable MSA2 optimizations

The renamed and removed configuration options where not used.

###### Motivation for this change

Update to the latest version (`ffmpeg_4` is already updated) and add proper support for AV1 decoding.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
  - Only `meguca` fails, which is broken on Hydra for quite a while now.
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
Fails on ``darwin`` as we have ```g++: error: unrecognized command line option '-msse4.2'```.

**Comment by primeos** [comment]
@mmahut are you sure that error message was from the build of `ffmpeg-full`? And if so: Could you have a look at it (I don't have a `darwin` system) / provide some additional information?

Also: Did the build of `4.1.4` succeed on your `darwin` setup (at least the `--disable-sse42` option was already present in `4.1.4`)?

The `darwin` build from `ofborg` did succeed: https://github.com/NixOS/nixpkgs/pull/67205/checks?check_run_id=199575061

Only the `aarch64` build was failing, but due to a build failure in a dependency and the build for 4.1.4 was also failing: https://hydra.nixos.org/build/98821440

**Comment by mmahut** [comment]
@primeos it's the ofborg failed build, please see https://github.com/NixOS/nixpkgs/pull/67205/checks?check_run_id=199511562

**Comment by mmahut** [comment]
Sorry, @primeos I meant ``aarch64`` and did not know it is because of a dependency.

**Comment by primeos** [comment]
@mmahut ok, no problem, I tried to fix it, let's see if it works (cannot test it locally atm).

**Comment by primeos** [comment]
ok, it builds on all three platforms now :)

I'll merge it as my manual tests where fine so far (tested all three binaries, playing videos, transcoding videos, etc.).

**Pull request merged**
