### PR TITLE
podman: 1.9.3 -> 2.0.1

### PR DESCRIPTION
**Pull request by zowoq**
https://github.com/containers/libpod/releases/tag/v2.0.0
https://github.com/containers/libpod/releases/tag/v2.0.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Can't reproduce this outside the test, seems like an issue with the test environment and not podman, etc.

We might want to merge the [`containers.conf`](https://github.com/NixOS/nixpkgs/pull/87792) and [automatic `subuid`/`subgid`](https://github.com/NixOS/nixpkgs/pull/86278) PRs with this, the major version bump seems like a good time to have user config changes.

**Comment by zowoq** [comment]
@ofborg test podman

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
Yep, thank you for the updated PR. LGTM

**Review by marsam — APPROVED** [review]

**Comment by zowoq** [comment]
Upstream has darwin builds again so I'll take a look at fixing that in the next couple of days.

**Pull request merged**
