### PR TITLE
openblas: Add enableStatic flag

### PR DESCRIPTION
**Pull request by nh2**
* [x] ~Based on #61614, merge that first.~ Merge #60573 first.

###### Motivation for this change

Building static Haskell executables involving `hmatrix`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nh2** [comment]
Don't merge yet:

This isn't working because our version doesn't have https://github.com/xianyi/OpenBLAS/pull/2038

**Comment by matthewbauer** [comment]
Looks okay! Could you also add the override to ```pkg/top-level/static.nix```?

**Comment by nh2** [comment]
> This isn't working because our version doesn't have [xianyi/OpenBLAS#2038](https://github.com/xianyi/OpenBLAS/pull/2038)

Will be fixed with https://github.com/NixOS/nixpkgs/pull/61614

**Comment by nh2** [comment]
> Looks okay! Could you also add the override to `pkg/top-level/static.nix`?

Added; still compiling though on my machine.

**Comment by nh2** [comment]
@GrahamcOfBorg build pkgsStatic.openblas

**Comment by nh2** [comment]
@matthewbauer `pkgsStatic.openblas` errors out with

```
build flags: SHELL=/nix/store/5p8qcz6i13ymgf80kimhx2g9pb5r5nia-bash-4.4-p23/bin/bash BINARY=64 CC=x86_64-unknown-linux-musl-cc CROSS=1 DYNAMIC_ARCH=1 FC=x86_64-unknown-linux-musl-gfortran HOSTCC=cc INTERFACE64=1 NO_AVX512=1 NO_BINARY_MODE=1 NO_STATIC=1 NUM_THREADS=64 PREFIX=/nix/store/y5nm9bbxmy5vjyhiz9p1kak3gvgirc6m-openblas-0.3.5-x86_64-unknown-linux-musl TARGET=ATHLON USE_OPENMP=1
/nix/store/6k95q6vvnmspf3c0nm8q55sixsvmn9nc-binutils-2.31.1/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
```

even on current `master`.

**Pull request merged**
