### PR TITLE
ec2_hibernate_linux_agent: init at 1.0.0

### PR DESCRIPTION
**Pull request by PsyanticY**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by AmineChikhaoui** [comment]
@GrahamcOfBorg build ec2_hibernate_linux_agent

**Comment by PsyanticY** [comment]
Hey @FRidh can you please have a quick look at this  ^^

**Comment by AmineChikhaoui** [comment]
@GrahamcOfBorg build ec2_hibernate_linux_agent

**Comment by AmineChikhaoui** [comment]
You could probably add `platforms = [ "x86_64-linux" ];` to the meta attribute if it's not supposed to work on aarch64.

**Pull request closed without merging**
