### PR TITLE
doc: remove references to mdDoc in the manual

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

Since https://github.com/NixOS/nixpkgs/pull/237557 was merged, lib.mdDoc has been a no-op. Let's remove the manual entries that recommend it.

The tracking issue is #300735.

## Things done

- [x] `nix-build doc/default.nix`

### CODE REVIEW

**Comment by philiptaron** [comment]
Hrm, I meant to separate `nixos/lib` changes into a separate PR.

**Review by DanielSidhion — APPROVED** [review]
LGTM, didn't see any weird formatting issues.

**Comment by DanielSidhion** [comment]
Given the very specific scope of this PR, I'm going ahead with a merge even though ideally the manual and `nixos/lib` changes should've been done in separate PRs.

**Comment by philiptaron** [comment]
> Given the very specific scope of this PR, I'm going ahead with a merge even though ideally the manual and `nixos/lib` changes should've been done in separate PRs.

Thank you 🙇🏻‍♂️  I wish there was something better that `git push --force-with-lease` to update a PR when rebasing.

**Pull request merged**
