### PR TITLE
nixosTests.nginx-sandbox: remove broken test and move the sandboxing test to the openresty test

### LINKED ISSUE #262251: Build failure: nixosTests.nginx-sandbox
There's many of these

```
vm-test-run-nginx-sandbox> machine # [   47.753580] nginx[1142]: nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
vm-test-run-nginx-sandbox> machine # [   47.756064] nginx[1142]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
vm-test-run-nginx-sandbox> machine # [   47.757756] nginx[1142]:        no field package.preload['resty.core']
vm-test-run-nginx-sandbox> machine # [   47.759275] nginx[1142]:        no file './share/lua/5.1/resty/core.lua'
vm-test-run-nginx-sandbox> machine # [   47.759924] nginx[1142]:        no file './resty/core.lua'
vm-test-run-nginx-sandbox> machine # [   47.760520] nginx[1142]:        no file './resty/core/init.lua'
vm-test-run-nginx-sandbox> machine # [   47.761171] nginx[1142]:        no file './lib/lua/5.1/resty/core.so'
vm-test-run-nginx-sandbox> machine # [   47.761799] nginx[1142]:        no file './resty/core.so'
vm-test-run-nginx-sandbox> machine # [   47.762382] nginx[1142]:        no file './lib/lua/5.1/loadall.so'
vm-test-run-nginx-sandbox> machine # [   47.762981] nginx[1142]:        no file './lib/lua/5.1/resty.so'
vm-test-run-nginx-sandbox> machine # [   47.763601] nginx[1142]:        no file './resty.so'
vm-test-run-nginx-sandbox> machine # [   47.764138] nginx[1142]:        no file './lib/lua/5.1/loadall.so') in /nix/store/v4z4x4w4rmj261vw9jcgwyay6ggqsc6m-nginx.conf:50
vm-test-run-nginx-sandbox> machine # [   47.765782] systemd[1]: nginx.service: Main process exited, code=exited, status=1/FAILURE
vm-test-run-nginx-sandbox> machine # [   47.766602] systemd[1]: nginx.service: Failed with result 'exit-code'.
vm-test-run-nginx-sandbox> machine # [   57.906458] systemd[1]: nginx.service: Scheduled restart job, restart counter is at 5.
vm-test-run-nginx-sandbox> machine # [   57.907267] systemd[1]: nginx.service: Start request repeated too quickly.
vm-test-run-nginx-sandbox> machine # [   57.907994] systemd[1]: nginx.service: Failed with result 'exit-code'.
vm-test-run-nginx-sandbox> machine # [   57.911766] systemd[1]: Failed to start Nginx Web Server.
```

### PR DESCRIPTION
**Pull request by Artturin**
the enableSandbox option of nginx was removed in 535896671b66d308df3ce467c94f8a9fecfdffea

Closes https://github.com/NixOS/nixpkgs/issues/262251

the test fails with

```
vm-test-run-nginx-sandbox> machine # [   47.753580] nginx[1142]: nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
vm-test-run-nginx-sandbox> machine # [   47.756064] nginx[1142]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
vm-test-run-nginx-sandbox> machine # [   57.911766] systemd[1]: Failed to start Nginx Web Server.
```

upstream readme says

> This is a core component of OpenResty. If you are using this module, then you are essentially using OpenResty :)

so why not just use openresty instead of a lua module?

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
Working variant:
```diff
diff --git a/nixos/tests/nginx-sandbox.nix b/nixos/tests/nginx-sandbox.nix
index 92ba30a09cf9..b59d9296e8a1 100644
--- a/nixos/tests/nginx-sandbox.nix
+++ b/nixos/tests/nginx-sandbox.nix
@@ -7,17 +7,8 @@ import ./make-test-python.nix ({ pkgs, ... }: {
   # This test checks the creation and reading of a file in sandbox mode. Used simple lua script.

   nodes.machine = { pkgs, ... }: {
-    nixpkgs.overlays = [
-      (self: super: {
-        nginx-lua = super.nginx.override {
-          modules = [
-            pkgs.nginxModules.lua
-          ];
-        };
-      })
-    ];
     services.nginx.enable = true;
-    services.nginx.package = pkgs.nginx-lua;
+    services.nginx.package = pkgs.openresty;
     services.nginx.virtualHosts.localhost = {
       extraConfig = ''
         location /test1-write {

```

**Comment by Artturin** [comment]
> Working variant:
> 
> ```diff
> diff --git a/nixos/tests/nginx-sandbox.nix b/nixos/tests/nginx-sandbox.nix
> index 92ba30a09cf9..b59d9296e8a1 100644
> --- a/nixos/tests/nginx-sandbox.nix
> +++ b/nixos/tests/nginx-sandbox.nix
> @@ -7,17 +7,8 @@ import ./make-test-python.nix ({ pkgs, ... }: {
>    # This test checks the creation and reading of a file in sandbox mode. Used simple lua script.
> 
>    nodes.machine = { pkgs, ... }: {
> -    nixpkgs.overlays = [
> -      (self: super: {
> -        nginx-lua = super.nginx.override {
> -          modules = [
> -            pkgs.nginxModules.lua
> -          ];
> -        };
> -      })
> -    ];
>      services.nginx.enable = true;
> -    services.nginx.package = pkgs.nginx-lua;
> +    services.nginx.package = pkgs.openresty;
>      services.nginx.virtualHosts.localhost = {
>        extraConfig = ''
>          location /test1-write {
> ```

Is there something relevant being tested that isn't tested by https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/openresty-lua.nix

**Comment by Izorkin** [comment]
Move test to openresty-lua?

**Comment by RaitoBezarius** [comment]
Yeah, I'd appreciate if the test gets moved to openresty stuff.

**Comment by Izorkin** [comment]
> Yeah, I'd appreciate if the test gets moved to openresty stuff.

```diff
diff --git a/nixos/tests/openresty-lua.nix b/nixos/tests/openresty-lua.nix
index b177b3c194d7..9e987398f51d 100644
--- a/nixos/tests/openresty-lua.nix
+++ b/nixos/tests/openresty-lua.nix
@@ -16,6 +16,12 @@ import ./make-test-python.nix ({ pkgs, lib, ... }:

     nodes = {
       webserver = { pkgs, lib, ... }: {
+        networking = {
+          extraHosts = ''
+            127.0.0.1 default.test
+            127.0.0.1 sandbox.test
+          '';
+        };
         services.nginx = {
           enable = true;
           package = pkgs.openresty;
@@ -24,7 +30,7 @@ import ./make-test-python.nix ({ pkgs, lib, ... }:
             lua_package_path '${luaPath};;';
           '';

-          virtualHosts."default" = {
+          virtualHosts."default.test" = {
             default = true;
             locations."/" = {
               extraConfig = ''
@@ -36,6 +42,33 @@ import ./make-test-python.nix ({ pkgs, lib, ... }:
               '';
             };
           };
+
+          virtualHosts."sandbox.test" = {
+            locations."/test1-write" = {
+              extraConfig = ''
+                content_by_lua_block {
+                  local create = os.execute('${pkgs.coreutils}/bin/mkdir /tmp/test1-read')
+                  local create = os.execute('${pkgs.coreutils}/bin/touch /tmp/test1-read/foo.txt')
+                  local echo = os.execute('${pkgs.coreutils}/bin/echo worked > /tmp/test1-read/foo.txt')
+                }
+              '';
+            };
+            locations."/test1-read" = {
+              root = "/tmp";
+            };
+            locations."/test2-write" = {
+              extraConfig = ''
+                content_by_lua_block {
+                  local create = os.execute('${pkgs.coreutils}/bin/mkdir /var/web/test2-read')
+                  local create = os.execute('${pkgs.coreutils}/bin/touch /var/web/test2-read/bar.txt')
+                  local echo = os.execute('${pkgs.coreutils}/bin/echo error-worked > /var/web/test2-read/bar.txt')
+                }
+              '';
+            };
+            locations."/test2-read" = {
+              root = "/var/web";
+            };
+          };
         };
       };
     };
@@ -51,5 +84,18 @@ import ./make-test-python.nix ({ pkgs, lib, ... }:
           f"curl -w '%{{http_code}}' --head --fail {url}"
         )
         assert http_code.split("\n")[-1] == "200"
+
+        # This test checks the creation and reading of a file in sandbox mode.
+        # Checking write in temporary folder
+        webserver.succeed("$(curl -vvv http://sandbox.test/test1-write)")
+        webserver.succeed('test "$(curl -fvvv http://sandbox.test/test1-read/foo.txt)" = worked')
+        # Checking write in protected folder. In sandbox mode for the nginx service, the folder /var/web is mounted
+        # in read-only mode.
+        webserver.succeed("mkdir -p /var/web")
+        webserver.succeed("chown nginx:nginx /var/web")
+        webserver.succeed("$(curl -vvv http://sandbox.test/test2-write)")
+        assert "404 Not Found" in machine.succeed(
+            "curl -vvv -s http://sandbox.test/test2-read/bar.txt"
+        )
       '';
   })

```

**Comment by Artturin** [comment]
Thanks @Izorkin

**Review by Izorkin — APPROVED** [review]

**Pull request merged**
