### PR TITLE
ikiwiki: Fix failing dependency builds

### PR DESCRIPTION
**Pull request by grahamc**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

My theory here is ModuleBuild is a build dependency, but CGI is needed by anything using it.

### CODE REVIEW

**Comment by grahamc** [comment]
# WIP

**Comment by grahamc** [comment]
nox-review pr passed.

**Comment by grahamc** [comment]
I think this needs to be merged to master _and_ 16.03. Should I do anything special to make that possible?

**Comment by joachifm** [comment]
You could open two pull requests

**Comment by domenkozar** [comment]
@grahamc would appreciate if you also open one against 16.03 since cherry-picking is going to be painful :)

**Pull request merged**
