### PR TITLE
vimPlugins: update on 2024-05-16

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Regular update of the vim plugins (first one since [neovim 0.10](https://github.com/NixOS/nixpkgs/pull/311047)).

Noticeable includes:
- https://github.com/NeogitOrg/neogit/pull/978

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 312303` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>147 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.base46</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-treesitter</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.cyberdream-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.distant-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.far-vim</li>
    <li>vimPlugins.flash-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-hoogle-vim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.hardhat-nvim</li>
    <li>vimPlugins.haskell-scope-highlighting-nvim</li>
    <li>vimPlugins.haskell-snippets-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.idris2-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.inc-rename-nvim</li>
    <li>vimPlugins.iron-nvim</li>
    <li>vimPlugins.jsonfly-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.modus-themes-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogen</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest-gtest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.neotest-rspec</li>
    <li>vimPlugins.nerdcommenter</li>
    <li>vimPlugins.nerdtree</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.no-neck-pain-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-osc52</li>
    <li>vimPlugins.nvim-pqf</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-parsers.clojure</li>
    <li>vimPlugins.nvim-treesitter-parsers.diff</li>
    <li>vimPlugins.nvim-treesitter-parsers.earthfile</li>
    <li>vimPlugins.nvim-treesitter-parsers.erlang</li>
    <li>vimPlugins.nvim-treesitter-parsers.idl</li>
    <li>vimPlugins.nvim-treesitter-parsers.php</li>
    <li>vimPlugins.nvim-treesitter-parsers.php_only</li>
    <li>vimPlugins.nvim-treesitter-parsers.sourcepawn</li>
    <li>vimPlugins.nvim-treesitter-parsers.tlaplus</li>
    <li>vimPlugins.nvim-treesitter-parsers.tsx</li>
    <li>vimPlugins.nvim-treesitter-parsers.typescript</li>
    <li>vimPlugins.nvim-treesitter-parsers.typespec</li>
    <li>vimPlugins.nvim-treesitter-parsers.wit</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-treesitter-textsubjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.persistence-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.roslyn-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.scnvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.staline-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-dadbod-completion</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-fzf-coauthorship</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-spirv</li>
    <li>vimPlugins.vim-zettel</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wiki-vim</li>
    <li>vimPlugins.yanky-nvim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 312303` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>147 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.base46</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-treesitter</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.cyberdream-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.distant-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.far-vim</li>
    <li>vimPlugins.flash-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-hoogle-vim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.hardhat-nvim</li>
    <li>vimPlugins.haskell-scope-highlighting-nvim</li>
    <li>vimPlugins.haskell-snippets-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.idris2-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.inc-rename-nvim</li>
    <li>vimPlugins.iron-nvim</li>
    <li>vimPlugins.jsonfly-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.modus-themes-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogen</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest-gtest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.neotest-rspec</li>
    <li>vimPlugins.nerdcommenter</li>
    <li>vimPlugins.nerdtree</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.no-neck-pain-nvim</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-osc52</li>
    <li>vimPlugins.nvim-pqf</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-parsers.clojure</li>
    <li>vimPlugins.nvim-treesitter-parsers.diff</li>
    <li>vimPlugins.nvim-treesitter-parsers.earthfile</li>
    <li>vimPlugins.nvim-treesitter-parsers.erlang</li>
    <li>vimPlugins.nvim-treesitter-parsers.idl</li>
    <li>vimPlugins.nvim-treesitter-parsers.php</li>
    <li>vimPlugins.nvim-treesitter-parsers.php_only</li>
    <li>vimPlugins.nvim-treesitter-parsers.sourcepawn</li>
    <li>vimPlugins.nvim-treesitter-parsers.tlaplus</li>
    <li>vimPlugins.nvim-treesitter-parsers.tsx</li>
    <li>vimPlugins.nvim-treesitter-parsers.typescript</li>
    <li>vimPlugins.nvim-treesitter-parsers.typespec</li>
    <li>vimPlugins.nvim-treesitter-parsers.wit</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-treesitter-textsubjects</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.persistence-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.roslyn-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.scnvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.staline-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-dadbod-completion</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-fzf-coauthorship</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-spirv</li>
    <li>vimPlugins.vim-zettel</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wiki-vim</li>
    <li>vimPlugins.yanky-nvim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 312303` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>35 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.debugprint-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.hardhat-nvim</li>
    <li>vimPlugins.haskell-snippets-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.persistence-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.staline-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.wiki-vim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 312303` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.debugprint-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.hardhat-nvim</li>
    <li>vimPlugins.haskell-snippets-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.persistence-nvim</li>
    <li>vimPlugins.staline-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.wiki-vim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 312303` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.debugprint-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.hardhat-nvim</li>
    <li>vimPlugins.haskell-snippets-nvim</li>
    <li>vimPlugins.lazy-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.noice-nvim</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.persistence-nvim</li>
    <li>vimPlugins.staline-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.wiki-vim</li>
  </ul>
</details>

**Comment by teto** [comment]
I think we can wait a few days for plugins to catch up with neovim 0.10.

**Pull request merged**
