### PR TITLE
python3Packages.pytest-datafiles: Update homepage

### PR DESCRIPTION
**Pull request by edmundmiller**
###### Motivation for this change

Found a wrong link in the documentation of a package

###### Things done

Updated it

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
We fetch from pypi so I think this homepage is correct. Also next time please target master and set the title and commit message according to the contribution guide.

**Comment by Emiller88** [comment]
@SuperSandro2000 Sorry about those just wanted to get the fix in. I thought they were updated from pypi, but it seems like it didn't work out on this one. https://pypi.org/project/pytest-datafiles/ should be the correct pypi link, as you can see the old one doesn't match up with the package name from what I can tell. I'll fix my lack of etiquette if you agree that the current link is incorrect, and change the link to a pypi link instead of gh otherwise feel free to close this.

**Comment by SuperSandro2000** [comment]
Oh yeah. You are right. Can you change the title and commit message to ``python3Packages.pytest-datafiles: Update homepage``

**Comment by Emiller88** [comment]
@SuperSandro2000 Should be good now! Let me know if you need anything else!

**Comment by SuperSandro2000** [comment]
Please target master which I could merge.

**Comment by Emiller88** [comment]
@SuperSandro2000 Sorry I didn't ping you on this. Should be good to go.

**Review by jonringer — APPROVED** [review]

**Pull request merged**
