### PR TITLE
Create embedded directory in pkgs/development/ and move embedded-dev-related software there

### PR DESCRIPTION
**Pull request by pvonmoradi**
###### Motivation for this change
Since `pkgs/development` already contains domain specific directories like `mobile/` and `web/`, I thought it'd be neater to introduce an `embedded/` dir to put packages related to embedded development there. 
This commit only does so for `openocd` but if the community is OK with this move, we can do the same for the following and add commits:  
```
embedded/
├── arduino
│   ├── arduino-ci
│   │   └── default.nix
│   ├── arduino-cli
│   │   └── default.nix
│   ├── arduino-core
│   │   ├── default.nix
│   │   └── downloads.nix
│   ├── arduino-mk
│   │   └── default.nix
│   └── ino
│       └── default.nix
├── blackmagic
│   ├── default.nix
│   └── helper.sh
├── openocd
│   └── default.nix
├── platformio
│   ├── chrootenv.nix
│   ├── core.nix
│   ├── default.nix
│   ├── fix-searchpath.patch
│   ├── missing-udev-rules-nixos.patch
│   └── use-local-spdx-license-list.patch
└── stm32
    ├── betaflight
    │   └── default.nix
    └── inav
        └── default.nix
```

###### Things done
not tested

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
+1 for moving embedded stuff from `tools/misc` to `embedded`

**Review by bjornfor — APPROVED** [review]

**Comment by pvonmoradi** [comment]
Note that these changes are only limited to embedded-related packages inside `pkgs/development/`
Here is what `pkgs/development/embedded/` looks like after these changes:
```
λ tree embedded/
embedded/
├── arduino
│   ├── arduino-ci
│   │   └── default.nix
│   ├── arduino-cli
│   │   └── default.nix
│   ├── arduino-core
│   │   ├── default.nix
│   │   └── downloads.nix
│   ├── arduino-mk
│   │   └── default.nix
│   └── ino
│       └── default.nix
├── avrdude
│   └── default.nix
├── blackmagic
│   ├── default.nix
│   └── helper.sh
├── bossa
│   ├── bin2c.c
│   ├── bossa-no-applet-build.patch
│   └── default.nix
├── cc-tool
│   └── default.nix
├── easypdkprog
│   └── default.nix
├── fpga
│   ├── apio
│   │   └── default.nix
│   ├── ecpdap
│   │   └── default.nix
│   ├── fujprog
│   │   └── default.nix
│   ├── icestorm
│   │   └── default.nix
│   ├── lattice-diamond
│   │   └── default.nix
│   ├── openfpgaloader
│   │   └── default.nix
│   ├── tinyprog
│   │   └── default.nix
│   └── trellis
│       └── default.nix
├── gputils
│   └── default.nix
├── msp430
│   └── mspds
├── openocd
│   └── default.nix
├── platformio
│   ├── chrootenv.nix
│   ├── core.nix
│   ├── default.nix
│   ├── fix-searchpath.patch
│   ├── missing-udev-rules-nixos.patch
│   └── use-local-spdx-license-list.patch
├── stm32
│   ├── betaflight
│   │   └── default.nix
│   ├── inav
│   │   └── default.nix
│   ├── stm32cubemx
│   │   └── default.nix
│   └── stm32flash
│       └── default.nix
├── teensy-loader-cli
│   └── default.nix
├── uisp
│   └── default.nix
└── xc3sprog
    └── default.nix

33 directories, 37 files
```

**Review by prusnak — APPROVED** [review]
LGTM 0 rebuilds

edit: someone just changed `pkgs/development/tools/misc/openfpgaloader/default.nix` so the PR needs to be rebased

**Review by prusnak — APPROVED** [review]

**Comment by pvonmoradi** [comment]
@prusnak @SuperSandro2000 thanks for merging. 
Do you know why the names of contributors got deleted from each project's history?
This way we don't know who to ping in case of problems or updates.

**Comment by SuperSandro2000** [comment]
> Do you know why the names of contributors got deleted from each project's history?

Git history does not follow renames.

**Pull request merged**
