### PR TITLE
 amuled: add option to only build web, add top-level amule-web

### PR DESCRIPTION
**Pull request by arximboldi**
###### Description of changes

This fixes the `amule-daemon` package, which was broken due to mistakes in the Amule CMake code.

It also introduces `amule-web` which also needed some workarounds, as it was failing to build when not built together with some of the other targets included in the codebase.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arximboldi** [comment]
Note: this can also easily be backported to NixOS 22.05, where the package is already marked broken. Should I make a separate PR for that, or is there another (maybe automatic) process for that?

**Comment by QuantMint** [comment]
Can you rebase this? I am getting merge conflicts with nix-review.

**Comment by arximboldi** [comment]
Rebase on top of what?

**Comment by QuantMint** [comment]
> Rebase on top of what? `master` on `nixpkgs`?

yes

**Comment by arximboldi** [comment]
@QuantMint done, thanks. It seems someone marked the package as broken on Darwin. I haven't tried on Darwin so I have not removed the marking there. Rebase done.

**Review by Tungsten842 — APPROVED** [review]
Everything works, thanks for your work

**Comment by SuperSandro2000** [comment]
Please follow the contributing guide when naming your commits.

**Comment by arximboldi** [comment]
@SuperSandro2000 would you like me to ammend the commits before merge?

**Comment by QuantMint** [comment]
> @SuperSandro2000 would you like me to ammend the commits before merge?

You should change the commit names according to: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md

**Comment by arximboldi** [comment]
done

**Review by Tungsten842 — APPROVED** [review]

**Pull request merged**
