### PR TITLE
expat: 2.2.3 -> 2.2.4

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rycee** [comment]
This should be retargeted to staging since it'll cause a mass-rebuild on some platforms.

**Comment by NeQuissimus** [comment]
@rycee done

**Comment by NeQuissimus** [comment]
No idea why code owners were added...

**Comment by rycee** [comment]
Rebased into staging in 4ab93f82364c741c2abc705c1f09618f4e77cec4. Thanks!

**Pull request closed without merging**
