### PR TITLE
nomad: 0.12.3 -> 0.12.7, bump default to 0.12.x

### PR DESCRIPTION
**Pull request by endocrimes**
###### Motivation for this change

New software release and promotion of Nomad 0.12 to be the default Nomad release series.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] ~Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maxeaubrey** [comment]
Result of `nixpkgs-review pr 97918` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nomad (nomad_0_12)</li>
  </ul>
</details>

**Review by amaxine — APPROVED** [review]

**Comment by endocrimes** [comment]
New version got released, this is bumped to 0.12.5 now.

**Comment by endocrimes** [comment]
Bumped again for a security release. Would be great to get this merged.

**Comment by maxeaubrey** [comment]
Result of `nixpkgs-review pr 97918` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nomad</li>
    <li>nomad_0_11</li>
  </ul>
</details>

**Pull request merged**
