### PR TITLE
spice-gtk: 0.37 -> 0.39

### PR DESCRIPTION
**Pull request by tadeokondrak**
###### Motivation for this change

This update fixes issues I've had with display scaling.i

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by quantmint** [comment]
Result of `nixpkgs-review pr 152044` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>gnome.gnome-boxes</li>
    <li>remmina</li>
    <li>spice-gtk</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-viewer</li>
  </ul>
</details>

**Review by jtojnar — CHANGES_REQUESTED** [review]
Looking at [changelog](https://gitlab.freedesktop.org/spice/spice-gtk/-/blob/v0.39/CHANGELOG.md),
- you need to remove the `pulse` meson flag (https://gitlab.freedesktop.org/spice/spice-gtk/-/merge_requests/33)
- capabilities seem to be set correctly in the [NixOS module](https://github.com/NixOS/nixpkgs/blob/8fb76a2ed5493898cf4e14cc2b9109d276f3be6e/nixos/modules/virtualisation/spice-usb-redirection.nix#L20) (https://gitlab.freedesktop.org/spice/spice-gtk/-/merge_requests/42) we might have actually switched to capabilities too early in https://github.com/NixOS/nixpkgs/pull/97826.
- but we will definitely need `-Dusb-acl-helper-dir=${placeholder "out"}/bin` meson flag since we rely on the ACL helper being on `PATH`. (https://gitlab.freedesktop.org/spice/spice-gtk/-/merge_requests/45)
- we might want to add wayland dependencies (https://gitlab.freedesktop.org/spice/spice-gtk/-/merge_requests/45) – perhaps they are propagated by something

**Comment by jtojnar** [comment]
Looks like pulse was not the only removed option:

```
meson.build:4:0: ERROR: Unknown options: "celt051"
```

**Comment by tadeokondrak** [comment]
> Looks like pulse was not the only removed option:

Huh, I didn't see this because it only showed up as a warning. I fixed some other issues:
`usbids` is needed for its `usb.ids` file, but `usbids` doesn't have it (nor a pkg-config file) in nixpkgs.
I use the `hwdata` package instead.

~~`asciidoc` is used in the spice-common subproject~~ which is only used for documentation that doesn't make it to this package, removed

**Comment by jtojnar** [comment]
(We have just merged new Meson version that is more strict.)

**Comment by tadeokondrak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/159340

**Pull request closed without merging**
