### PR TITLE
python3Packages.pyftdi: init at 0.29.4

### PR DESCRIPTION
**Pull request by astro**
###### Motivation for this change

Adds a useful Python library.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by marsam — COMMENTED** [review]
Looks like it requires [Python>=35](https://github.com/eblot/pyftdi/blob/v0.29.2/setup.py#L100). Can you add the following?
```nix
  disabled = pythonOlder "3.5";
```
besides that, LGTM

**Comment by risicle** [comment]
Same results as @marsam for py27 - py37 version works on both non-nixos linux x86_64 and macos 10.13 for me though.

**Comment by astro** [comment]
Thank you. Added that and rebased.

**Comment by astro** [comment]
Sorry to have broken the build with the addition of `pythonOlder`. That is now fixed.

**Comment by marsam** [comment]
@GrahamcOfBorg build python3Packages.pyftdi

**Comment by marsam** [comment]
Tested locally on NixOS. 
Thanks @astro!

**Pull request merged**
