### PR TITLE
libva: 1.7.3 -> 2.0.0

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

The ```vaapi-intel``` driver is released in accordance with ```libva``` releases, so this PR sets up the dependency.

Additionally, the tools previously part of ```libva``` are now a separate ```libva-utils```.

This triggers a lot of rebuilding so I haven't tried it out here yet.

Cc: @garbas 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Please check the eval failure

**Comment by peterhoeg** [comment]
Messed up the final commit cleanup - thanks for noticing @globin. Sorted now.

**Comment by garbas** [comment]
@GrahamcOfBorg eval

**Comment by garbas** [comment]
oh damn wrong PR ... i want to merge this :)

**Comment by vcunat** [comment]
Why merge to master directly when it's tagged by _10.rebuild-linux: 501+_?

**Comment by garbas** [comment]
@vcunat oh shit! i must be more careful, i'll revert and push to staging. would that be ok?

**Comment by orivej** [comment]
Yes.

**Comment by vcunat** [comment]
Moved to staging.

**Comment by vcunat** [comment]
I see the `mpv` build got broken; hopefully upstream already released an update fixing that...  /cc maintainers: @AndersonTorres, @Fuuzetsu, @fpletz.

**Comment by orivej** [comment]
[gst_all_1.gst-vaapi](https://hydra.nixos.org/build/66133972) too: `Requested 'libva < 0.99.0' but version of libva is 1.0.0`.

**Comment by peterhoeg** [comment]
Upstream is recommending carrying both the old and new version - I'll update this to allow for both.

**Comment by orivej** [comment]
It seems that mpv was made compatible with libva 2 in https://github.com/mpv-player/mpv/commit/2ecf240b1cd20875991a5b18efafbe799864ff7f

**Comment by orivej** [comment]
And gst-vaapi 1.12.4 should already be compatible.

**Comment by orivej** [comment]
Updating gst-vaapi in b29c78df662dcd4b2a4022603a5340f2da2c1a68, this fixed the build.

**Comment by orivej** [comment]
Fixed mpv by applying the aforementioned patch in 745be0cb61447c182bd6d1ee53faf159996d7075.

**Comment by vcunat** [comment]
So... we don't need both v1 and v2 (i.e. PR #32796) anymore, right?

**Comment by orivej** [comment]
I don't know why v1 would be needed.

> Upstream is recommending carrying both the old and new version - I'll update this to allow for both.

@peterhoeg Could you post a link?

**Comment by peterhoeg** [comment]
> Could you post a link?

https://github.com/01org/libva/issues/72

**Comment by orivej** [comment]
Thanks! At this point at least free software we package does not need old libva.

**Pull request merged**
