### PR TITLE
hwinfo: 21.23 -> 21.38

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change

Update
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Hello,
I tried to build that and run the binaries produced. `hwinfo` works fine :
>[demo@nixos:~/testbuilds/hwinfo]$ ./result/bin/hwinfo --version
>21.38

But two other commands gives unexpected results :

>[demo@nixos:~/testbuilds/hwinfo]$ ./result/bin/mk_isdnhwdb 
>Cannot open /usr/share/hwinfo/ISDN.CDB.txt as stdin
The path /usr/share does not exist under NixOS.

>[demo@nixos:~/testbuilds/hwinfo]$ ./result/bin/convert_hd
>Can't locate XML/Writer.pm in @INC (you may need to install the XML::Writer module) (@INC contains: /home/demo/.nix-profile/lib/perl5/site_perl /nix/var/nix/profiles/default/lib/perl5/site_perl /run/current-system/sw/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi /run/current-system/sw/lib/perl5/site_perl/5.22.2 /run/current-system/sw/lib/perl5/site_perl /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/site_perl/5.22.2 /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/5.22.2/x86_64-linux-thread-multi /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/5.22.2 .) at ./result/bin/convert_hd line 4.
>BEGIN failed--compilation aborted at ./result/bin/convert_hd line 4.
A Perl module is missing.

**Comment by bjornfor** [comment]
The two other commands, did they work before? (If this PR does not cause regressions, we merge it even if some things are broken.)

**Comment by bobvanderlinden** [comment]
I don't think the other commands ever worked. I wasn't aware they existed nor what their use is (can't find them in man). I can check them out tonight.

**Comment by c0bw3b** [comment]
Those two commands never worked indeed. I did not mean to imply it was a regression of this PR. :)
Just wanted to point that out so we know there is room for improvement in a future PR on this package.

> ]$ nix-env -iA nixos.hwinfo
> [demo@nixos:~/testbuilds]$ hwinfo --version
> 21.23
> ]$ mk_isdnhwdb
> Cannot open /usr/share/hwinfo/ISDN.CDB.txt as stdin
> ]$ convert_hd
> Can't locate XML/Writer.pm in @INC (you may need to install the XML::Writer module) (@INC contains: /home/demo/.nix-profile/lib/perl5/site_perl /nix/var/nix/profiles/default/lib/perl5/site_perl /run/current-system/sw/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi /run/current-system/sw/lib/perl5/site_perl/5.22.2 /run/current-system/sw/lib/perl5/site_perl /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/site_perl/5.22.2 /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/5.22.2/x86_64-linux-thread-multi /nix/store/p7k810475bbk0v9wi418sz8jh3dzlpiz-perl-5.22.2/lib/perl5/5.22.2 .) at /home/demo/.nix-profile/bin/convert_hd line 4.
> BEGIN failed--compilation aborted at /home/demo/.nix-profile/bin/convert_hd line 4.

**Comment by bjornfor** [comment]
Thanks! Pushed to master (d12030d17589bc19686d300748362b82c41950b4) and release-17.03 (d60e77f1c8b8546efb5607fba3d170198312b88c).

**Pull request closed without merging**
