### PR TITLE
python3Packages.python-telegram-bot: fix --with-upstream-urllib3

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Fixes to #86652

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
is there a way to add some testing around this?

**Comment by veprbl** [comment]
@jonringer You can catch the warning:
```
python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.
```

**Review by jonringer — APPROVED** [review]

**Comment by jonringer** [comment]
I don't use the package, so I don't have any strong feeling about it's runtime behaviors

**Comment by veprbl** [comment]
@jonringer Any idea about why upstream is broken https://github.com/python-telegram-bot/python-telegram-bot/blob/5898e1fe7a08c0ef5aa4e69af9090a81a2c34af8/setup.py#L22-L30 ?

**Comment by veprbl** [comment]
I did check that the `packages` list is indeed pruned now, I tried replacing `'telegram.vendor.ptb_urllib3'` with `'telegram.vendor'`, but would still get installed and imported.

**Comment by jonringer** [comment]
> @jonringer Any idea about why upstream is broken https://github.com/python-telegram-bot/python-telegram-bot/blob/5898e1fe7a08c0ef5aa4e69af9090a81a2c34af8/setup.py#L22-L30 ?

seeing as that was done 3 years ago, I'm assuming they had some difficulties with urllib3 breaking them. So they decided to vendor it

**Comment by veprbl** [comment]
Looks like this is some interplay between what is in the "python_telegram_bot.egg-info" of the PyPi package and `include_package_data=True,` option, which makes it install things that are not listed in MANIFEST.in. Not sure how to fix this.

**Pull request merged**
