### PR TITLE
Hydra updates 2

### PR DESCRIPTION
**Pull request by Mindavi**
###### Description of changes

First batch of hydra updates, picked and rebased from https://github.com/NixOS/nixpkgs/pull/160202.

Since tests are now enabled, this gives some confidence in that everything's working ok.

TBD are some other changes in the other PR, but let's get this in first to get started.

Note that the latest version of hydra in this patchset doesn't work with nix_2_4 or nix_2_8 (test failures), so I picked nix_2_6 (others may or may not work too). Hopefully we can update that when we update hydra again.

cc @lheckemann @dasJ 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

<s>Running the nixos test for hydra now...</s> ofborg did that for me, success on x86_64-linux

ZHF: https://github.com/NixOS/nixpkgs/issues/172160 (fixes the hydra build: https://hydra.nixos.org/build/176040460/nixlog/2)

### CODE REVIEW

**Review by lheckemann — APPROVED** [review]

**Comment by lheckemann** [comment]
Nice, thanks for picking this up!

**Comment by 06kellyjac** [comment]
I'm getting `error: undefined variable 'CatalystPluginUnicodeEncoding'` now on my `nixpkgs-review` runs. Is this related?

**Comment by Mindavi** [comment]
Aww, that's an alias apparently. Needs a fixup (maybe I'll have time this evening to pick that up).

https://github.com/NixOS/nixpkgs/blob/117f62e72ef58431d73ad6e903b71938ee13bc61/pkgs/top-level/perl-packages.nix#L25551

**Comment by lheckemann** [comment]
Fixed in #172328 :)

**Comment by sternenseemann** [comment]
This update seems to have broken this widely used way to test evaluate jobsets: `hydra-eval-jobs -I . pkgs/top-level/release-my-jobset.nix`. This has also broken the maintenance scripts in `maintainers/scripts/haskell`. You'll now be greeted with a lot of:

```
error: not an absolute path: '.'
```

Using an absolute path gives you:

```
error: access to canonical path '/nix/store/7c31varbjxw5by94yxhdcpqbmxqdlvd2-user-environment' is forbidden in restricted mode
```

cc @grahamc

**Comment by grahamc** [comment]
What if you pre-canonicalize the path before passing it in?

**Comment by sternenseemann** [comment]
> What if you pre-canonicalize the path before passing it in?

```
hydra-eval-jobs -I $(realpath .) $(realpath pkgs/top-level/release-haskell.nix) >/dev/null
warning: `--gc-roots-dir' not specified
error: access to canonical path '/nix/store/7c31varbjxw5by94yxhdcpqbmxqdlvd2-user-environment' is forbidden in restricted mode
error: access to canonical path '/nix/store/7c31varbjxw5by94yxhdcpqbmxqdlvd2-user-environment' is forbidden in restricted mode
error: access to canonical path '/nix/store/7c31varbjxw5by94yxhdcpqbmxqdlvd2-user-environment' is forbidden in restricted mode
error: access to canonical path '/nix/store/7c31varbjxw5by94yxhdcpqbmxqdlvd2-user-environment' is forbidden in restricted mode
error: access to canonical path '/nix/store/7c31varbjxw5by94yxhdcpqbmxqdlvd2-user-environment' is forbidden in restricted mode
…
```

**Comment by Mindavi** [comment]
Well, that's rather unfortunate 😞. Not sure how we can resolve that other than downgrading or (hopefully) upgrading. Is this issue also present on the tip of master hydra?

Maybe you can check https://github.com/NixOS/nixpkgs/pull/173218 to see if that improves the situation?

**Pull request merged**
