### PR TITLE
python312Packages.pynose: drop due to licensing issues

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes

https://github.com/mdmintz/pynose/issues/16
https://github.com/NixOS/nixpkgs/issues/311054

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
Thanks for this hard work! Offhand, I don't see any issues. However, there may be a bigger problem; in [this Mastodon thread](https://circumstances.run/@mawhrin/112751716246069698) many folks are bringing together a lot of evidence that *multiple Python packages* uploaded by this maintainer are improperly licensed. I'm not sure where to take this next; perhaps it needs to come up in Discourse. While this PR should be merged when it's ready, we may need a more systemic response as well.

**Comment by mweinelt** [comment]
1807 rebuilds across 47 commits is not too bad.

**Comment by dotlambda** [comment]
> For reference, this PR took a bit different approach: #323410

So do https://github.com/NixOS/nixpkgs/pull/325847 and https://github.com/NixOS/nixpkgs/pull/325865.

**Review by dotlambda — COMMENTED** [review]
Please remove the xlib commit: https://github.com/NixOS/nixpkgs/pull/325872

**Comment by dschrempf** [comment]
FYI: The license of `pynose` has been adapted to LGPL-2: https://github.com/mdmintz/pynose/commit/c3aa7424cf49b095c9faac00a36f7643f5a3cdbc.

**Comment by mweinelt** [comment]
Yeah, maybe. But the lost trust needs to be restored, before I'll consider allowing it back in. Right now #325935 looks more interesting to me.

**Comment by mightyiam** [comment]
Thank you, @mweinelt

**Comment by dschrempf** [comment]
Yes, I also want to thank you @mweinelt. This was a fast and professional cleansing.

**Comment by collares** [comment]
One more "thank you @mweinelt" for the prompt response. The upstream response to the licensing issue is simply atrocious.

**Pull request merged**
