### PR TITLE
w3m and ranger fixes

### PR DESCRIPTION
**Pull request by oxij**

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Does it fix the image preview in ranger? I have been trying to do this for quite a while without success.

**Comment by oxij** [comment]
yes, it does

**Comment by rnhmjoj** [comment]
Great! Thank you.

**Comment by oxij** [comment]
travis failed via a network problem, everything builds fine on my machine

**Comment by oxij** [comment]
It is a good time to merge this because KDE depends on w3m and everything in master is being rebuilt anyway. Just saying.
/cc @edolstra @jagajaga

**Comment by jagajaga** [comment]
Can you create a PR against `staging` branch? Because that commits will cause mass rebuild (as you can see here https://travis-ci.org/NixOS/nixpkgs/builds/91351833#L170).

**Comment by oxij** [comment]
Done with #11222.

Btw, I don't get why everyone here is in such a hurry to close issues. This issue should've been closed after this comment, clearly not before the birth of #11222.

**Pull request closed without merging**
