### PR TITLE
python3Packages.imap-tools: 0.37.0 -> 0.38.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113995` at ee1731d3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/02720cc3ef010c27a836d35258f9a6ad">python37Packages.imap-tools</a></li></li>
    <li><a href="https://gist.github.com/754ba3d883f582497d97c0c481a91916">python38Packages.imap-tools</a></li></li>
    <li><a href="https://gist.github.com/a7c7059cf2f5260a5b6f28ce3d31c761">python39Packages.imap-tools</a></li></li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113995` at ee1731d3 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/897662edc95f27451b219750f3bfd21e">python37Packages.imap-tools</a></li></li>
    <li><a href="https://gist.github.com/91fc90ab2407b4407b0379ae0655a50f">python38Packages.imap-tools</a></li></li>
    <li><a href="https://gist.github.com/e9f9950dd3fe72a6d11c11ef308a983d">python39Packages.imap-tools</a></li></li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 113995` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.imap-tools</li>
    <li>python38Packages.imap-tools</li>
    <li>python39Packages.imap-tools</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package built (see https://github.com/NixOS/nixpkgs/pull/113995#issuecomment-783323834)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-113995/results/python38Packages.imap-tools/lib/python3.8/site-packages]$ python
Python 3.7.9 (default, Aug 15 2020, 06:36:35) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imap_tools
>>> with imap_tools.MailBox('mail.fabian-affolter.ch').login(username, password) as mailbox:
...     subjects = [msg.subject for msg in mailbox.fetch()]
... 

[...]
```

Looks good to me.

**Pull request merged**
