### PR TITLE
jetbrains: 2023.1.4 -> 2023.2

### PR DESCRIPTION
**Pull request by dritter**
## Description of changes

jetbrains.phpstorm: 2023.1.4 -> 2023.2
jetbrains.rider: 2023.1.4 -> 2023.2

This also superseeds #246637 , because the plugins are already updated here.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 247219` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.rider</li>
  </ul>
</details>

**Review by raphaelr — CHANGES_REQUESTED** [review]
In jetbrains/default.nix, please replace both instances of `dotnet-sdk_6` with `dotnet-sdk_7`. Otherwise rider doesn't start anymore.

<details>
<summary>Log</summary>

```
/nix/store/llpywjvq8ivdf68ip5a78rq0rk2dlprg-rider-2023.2/rider/lib/ReSharperHost/linux-x64/Rider.Backend --runtimeconfig /nix/store/llpywjvq8ivdf68ip5a78rq0rk2dlprg-rider-2023.2/rider/lib/ReSharperHost/Rider.Backend.netcore.runtimeconfig.json --Port=44061 --enablecpp
You must install or update .NET to run this application.

App: /nix/store/llpywjvq8ivdf68ip5a78rq0rk2dlprg-rider-2023.2/rider/lib/ReSharperHost/linux-x64/Rider.Backend
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: /nix/store/llpywjvq8ivdf68ip5a78rq0rk2dlprg-rider-2023.2/rider/lib/ReSharperHost/linux-x64/dotnet

The following frameworks were found:
  6.0.20 at [/nix/store/llpywjvq8ivdf68ip5a78rq0rk2dlprg-rider-2023.2/rider/lib/ReSharperHost/linux-x64/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=nixos.23.11-x64
```
</details>

**Comment by dritter** [comment]
Result of `nixpkgs-review pr 247219` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.rider</li>
  </ul>
</details>

**Comment by dritter** [comment]
`rider` works now. Well spotted @raphaelr !

**Review by raphaelr — APPROVED** [review]
Rider works

**Comment by YarekTyshchenko** [comment]
Tested rider, works well. Would be good to get this merged.

**Comment by tymscar** [comment]
Works with all the IDEs I maintain. I tried the remote server functionality too and its good!

**Review by tymscar — APPROVED** [review]

**Review by SebTM — APPROVED** [review]
Works fine for me so far 👍🏻

**Comment by raphaelr** [comment]
> Looks like the hydra builds are failing with Output Limit Exceeded: https://hydra.nixos.org/build/134334527#tabs-summary

jetbrains.rider has an unfree license, so it won't be built by Hydra. The linked build is from 2021.

**Comment by YarekTyshchenko** [comment]
Ah, I understand. Still trying to get to grips with the ecosystem. Cool, guess its just the case of waiting for the merge, nothing more that we can do?

**Pull request merged**
