### PR TITLE
subsurface: 4.7.2 -> 4.7.5

### PR DESCRIPTION
**Pull request by bkchr**
Also updates googlemaps to 2017-12-15 and fixes compilation with qt5.10.

###### Motivation for this change
Preparation for qt5.10

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build subsurface

**Comment by adisbladis** [comment]
It seems like you based this on an old master. `subsurface` is already at 4.7.5.

**Comment by yegortimoshenko** [comment]
Still, this includes a compilation fix for Qt5.10 (presumably adding `libXcomposite`.

**Comment by adisbladis** [comment]
@yegortimoshenko It's a good fix. It just has to be rebased on current master with a new commit message.

**Comment by yegortimoshenko** [comment]
GitHub seems to be able to merge it without rebase. New commit message can be supplied when using "Squash and merge".

**Comment by bkchr** [comment]
Thanks for merging it anyway :)

**Comment by bkchr** [comment]
And yeah, the googlemaps upgrade is needed for qt 5.10.

**Comment by flokli** [comment]
@bkchr Does the map widget work for you?

I get
```
qrc:/MapWidget.qml:21: Error: Cannot assign [undefined] to QDeclarativeGeoMapType*
```
during runtime, and only a white map instead of tiles…

Not that into QT, but it seems like the type used in MapWidget.qml:21 [doesn't exist](https://github.com/qt/qtlocation/blob/2b230b0a10d898979e9d5193f4da2e408b397fe3/src/location/maps/qgeomaptype_p.h#L65)…

**Comment by bkchr** [comment]
@flokli are you on Linux or MacOs? The following error seems to be similar: https://github.com/Subsurface-divelog/subsurface/issues/588

Maybe we also need to fix that on our side.

**Comment by flokli** [comment]
@bkchr I'm on NixOS, not MacOS.
```
MapWidget.qml: cannot find a plugin named: googlemaps
```

is also shown in the stdout - sorry, missed this one.

So it looks pretty much the same as the linked issue.

[Build logs](https://nix-cache.s3.amazonaws.com/log/iqc3p8cw352w2lfgwgz0gf403zr76ygp-subsurface-4.7.5.drv) show:
```
-- Cannot find libqtgeoservices_googlemaps.so
```

So yes, this might need patching from our side.

**Pull request merged**
