### PR TITLE
linux: enable RCU_LAZY where supported

### PR DESCRIPTION
**Pull request by K900**
Supposed to save some power at idle.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
@ofborg test simple

**Comment by alyssais** [comment]
Do any other major distros enable it?

**Comment by Artturin** [comment]
other distros for reference
```
aports/testing/linux-asahi/config-asahi.aarch64:CONFIG_RCU_LAZY=y
void-packages/srcpkgs/linux6.2/files/arm64-dotconfig:CONFIG_RCU_LAZY=y
void-packages/srcpkgs/linux6.2/files/x86_64-dotconfig:CONFIG_RCU_LAZY=y
openSUSE/packages/k/kernel-source/kernel-default.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-obs-qa.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-docs.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-zfcpdump.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-syms.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-source.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-vanilla.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/dtb-armv6l.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-lpae.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-debug.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/dtb-riscv64.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/dtb-aarch64.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-64kb.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-kvmsmall.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-obs-build.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/kernel-pae.changes:    - RCU_LAZY=n
openSUSE/packages/k/kernel-source/dtb-armv7l.changes:    - RCU_LAZY=n
svntogit-packages/linux/trunk/config:CONFIG_RCU_LAZY=y
svntogit-packages/linux/repos/core-x86_64/config:CONFIG_RCU_LAZY=y
svntogit-packages/linux-zen/trunk/config:CONFIG_RCU_LAZY=y
svntogit-packages/linux-zen/repos/extra-x86_64/config:CONFIG_RCU_LAZY=y
svntogit-packages/linux-rt/repos/extra-x86_64/config:# CONFIG_RCU_LAZY is not set
svntogit-packages/linux-rt/trunk/config:# CONFIG_RCU_LAZY is not set
```

arch, void, and alpine enable it

**Comment by K900** [comment]
Sniped.

**Review by 06kellyjac — APPROVED** [review]
Reduced energy bill? tyvm

**Review by alyssais — APPROVED** [review]

**Comment by K900** [comment]
We should probably batch this with the next kernel updates cycle though.

**Comment by Artturin** [comment]
> We should probably batch this with the next kernel updates cycle though.

there's a few of these PRs which need to be batched, maybe make a project?

**Comment by K900** [comment]
FWIW I've been running this on my laptop for a bit and there's no obvious change.

**Comment by vcunat** [comment]
Are you sure about i686?
https://hydra.nixos.org/build/220522000

**Comment by K900** [comment]
Fixed (well, tracked down and disabled) in https://github.com/NixOS/nixpkgs/pull/232620

**Pull request merged**
