### PR TITLE
switch-to-configuration-ng: retain escaped content in unit files

### LINKED ISSUE #315602: switch-to-configuration-ng fail to reload encrypted swap unit
### Describe the bug

```
<snip>
Installing Lanzaboote to "/efi"...
Collecting garbage...
Successfully installed Lanzaboote.
Error: Failed to load unit file /etc/systemd/system/mkswap-dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap.service

Caused by:
    3:28 unknown character in \xHH form
warning: error(s) occurred while switching to the new configuration
```

```
> cat /etc/systemd/system/mkswap-dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap.service
[Unit]
After=systemd-modules-load.service
Before=dev-mapper-dev\x2ddisk\x2dbyx2dpartlabel\x2ddiskx2dnvmex2dencryptedSwap.swap shutdown.target
Conflicts=shutdown.target
DefaultDependencies=false
Description=Initialisation of swap device /dev/disk/by-partlabel/disk-nvme-encryptedSwap
RequiresMountsFor=/dev/disk/by-partlabel

[Service]
Environment="DEVICE=/dev/disk/by-partlabel/disk-nvme-encryptedSwap"
Environment="LOCALE_ARCHIVE=/nix/store/fq9vg6rrcrmz07yh5p9ppla83msb9swc-glibc-locales-2.39-52/lib/locale/locale-archive"
Environment="PATH=/nix/store/96n916fc8kvkrj48dsmmqmdwk9c9r0lq-util-linux-2.40.1-bin/bin:/nix/store/fskqxhk5kx3wliw4lm2cp2ccbcx448z6-e2fsprogs-1.47.0-bin/bin:/nix/store/a58v2h6gccdf2f0mk84wq9qvv7hr6q4a-cryptsetup-2.7.1-bin/bin:/nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/bin:/nix/store/jjcsr5gs4qanf7ln5c6wgcq4sn75a978-findutils-4.9.0/bin:/nix/store/28gpmx3z6ss3znd7fhmrzmvk3x5lnfbk-gnugrep-3.11/bin:/nix/store/5zjms21vpxlkbc0qyl5pmj2sidfmzmd7-gnused-4.9/bin:/nix/store/xjiifrz7ha6s29gp0p0j3w0155phxmia-systemd-255.6/bin:/nix/store/96n916fc8kvkrj48dsmmqmdwk9c9r0lq-util-linux-2.40.1-bin/sbin:/nix/store/fskqxhk5kx3wliw4lm2cp2ccbcx448z6-e2fsprogs-1.47.0-bin/sbin:/nix/store/a58v2h6gccdf2f0mk84wq9qvv7hr6q4a-cryptsetup-2.7.1-bin/sbin:/nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/sbin:/nix/store/jjcsr5gs4qanf7ln5c6wgcq4sn75a978-findutils-4.9.0/sbin:/nix/store/28gpmx3z6ss3znd7fhmrzmvk3x5lnfbk-gnugrep-3.11/sbin:/nix/store/5zjms21vpxlkbc0qyl5pmj2sidfmzmd7-gnused-4.9/sbin:/nix/store/xjiifrz7ha6s29gp0p0j3w0155phxmia-systemd-255.6/sbin"
Environment="TZDIR=/nix/store/y6hmqbmbwq0rmx1fzix5c5jszla2pzmp-tzdata-2024a/share/zoneinfo"
X-RestartIfChanged=false
ExecStart=/nix/store/r0drgpi83cwma92bw1233xi2kg3f6qgy-unit-script-mkswap-dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap-start/bin/mkswap-dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap-start 
ExecStop=/nix/store/a58v2h6gccdf2f0mk84wq9qvv7hr6q4a-cryptsetup-2.7.1-bin/bin/cryptsetup luksClose dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap
RemainAfterExit=true
Type=oneshot

[Install]
WantedBy=dev-mapper-dev\x2ddisk\x2dbyx2dpartlabel\x2ddiskx2dnvmex2dencryptedSwap.swap
```

```
> cat /nix/store/r0drgpi83cwma92bw1233xi2kg3f6qgy-unit-script-mkswap-dev-disk-byx2dpartlabel-diskx2dnvmex2
dencryptedSwap-start/bin/mkswap-dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap-start
#!/nix/store/306znyj77fv49kwnkpxmb0j2znqpa8bj-bash-5.2p26/bin/bash
set -e

cryptsetup plainOpen -c aes-xts-plain64 -d /dev/urandom \
 /dev/disk/by-partlabel/disk-nvme-encryptedSwap dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap
mkswap /dev/mapper/dev-disk-byx2dpartlabel-diskx2dnvmex2dencryptedSwap
```

### Steps To Reproduce
```
  system.switch.enableNg = true;
  system.switch.enable = lib.mkForce false;
```

```
doas nixos-rebuild switch --flake .#kaambl
```

### Expected behavior
Rebuild success

### Notify maintainers

@jmbaur

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.11 (Vicuña), 24.11.20240524.bfb7a88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/y9ci3n3czm23yw0xdf4h9bbjdshb2ws6-z71lmgd0ydfnax1b13zbrls5idf1y7ak-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jmbaur**
## Description of changes

By default, the INI parser in `rust-ini` tries to unescape the content it receives, causing issues such as those uncovered in https://github.com/NixOS/nixpkgs/issues/315602. We don't ever need the content to be unescaped for our purposes, so we can configure the parser to retain escape characters.

Fixes #315602

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jmbaur** [comment]
@ofborg test switchTestNg

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 315680` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>switch-to-configuration-ng</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]
This fixed the issue on my end!

**Review by oluceps — APPROVED** [review]

**Comment by Mic92** [comment]
I would like to backport this one, since this is the only known bug, I encountered so far.

**Comment by Atemu** [comment]
It's an experimental feature, so backporting even breaking changes is fine IMHO.

**Pull request merged**
