### PR TITLE
Fix markdown-preview-nvim

### LINKED ISSUE #175524: vimPlugins.markdown-preview-nvim doesn't build after an update because of a missing node dependency
### Steps To Reproduce
1. build `vimPlugins.markdown-preview-nvim`

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/8bawhfmsl3xs4lildgwf8llqcxin2byw-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/gm7v5lr1ng6jaqa3m880wsnrmphzbq8q-fix-node-paths.patch
patching file autoload/health/mkdp.vim
patching file autoload/mkdp/rpc.vim
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
@nix { "action": "setPhase", "phase": "installPhase" }
installing
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13
strip is /nix/store/r7r10qvsqlnvbzjkjinvscjlahqbxifl-gcc-wrapper-11.3.0/bin/strip
patching script interpreter paths in /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13
/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/install.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0d3wgx8x6dxdb2cpnq105z23hah07z7l-bash-5.1-p16/bin/sh"
/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/release.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/0d3wgx8x6dxdb2cpnq105z23hah07z7l-bash-5.1-p16/bin/bash"
checking for references to /build/ in /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13...
@nix { "action": "setPhase", "phase": "installCheckPhase" }
running install tests
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@chemzqm/neovim'
Require stack:
- /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/preloadmodules.js
- /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/load.js
- /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/index.js
- /nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/preloadmodules.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/preloadmodules.js',
    '/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/load.js',
    '/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/lib/app/index.js',
    '/nix/store/hhh0zdi1cyr3n706swpg2c4hbh7j3ll2-vimplugin-markdown-preview.nvim-2022-05-13/app/index.js'
  ]
}
```

### Additional context
I updated the vim plugins in https://github.com/NixOS/nixpkgs/pull/175324 and mistakenly added the new `@chemzqm/neovim` node dependency of markdown-preview-nvim to the generated pkgs/development/node-packages/node-packages.nix, I was informed of the problem [here](https://github.com/NixOS/nixpkgs/pull/175488#issuecomment-1141445954) when someone re-generated that file. I have trouble finding the proper place to add it now, pinging the relevant people to point me in the right direction.

### Notify maintainers
@oxalica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.9-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(dettorer): `"nixgl, nixpkgs, stable-21.11"`
 - nixpkgs: `/home/dettorer/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by Dettorer**
###### Description of changes

Added a missing dependency to markdown-preview-nvim and ran the node packages generate script.

Fixes #175524.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

nixpkgs-review is running, I have some errors due to the large amount of disk space it asks for this PR but I'll try to make it run and post the result. Building `vimPlugins.markdown-preview-nvim` individually works though so that works as a fix.

### CODE REVIEW

**Comment by Dettorer** [comment]
There we go, just had to set `TMPDIR` to something outside of a ramfs and be patient. Everything looks fine to me and ready for review

**Comment by Dettorer** [comment]
Pinging @teto and @dotlambda who helped me and informed me of the problem.

**Review by dotlambda — APPROVED** [review]
LGTM, but this will break again if upstream's dependencies change cause the vim plugin update script doesn't keep it at a certain version.

**Comment by Dettorer** [comment]
Result of `nixpkgs-review pr 175708` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>70 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>breitbandmessung</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>hyperspace-cli</li>
    <li>imapnotify</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>slack</li>
    <li>sloc</li>
    <li>spacevim</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>whalebird</li>
    <li>yaml-language-server</li>
    <li>zx</li>
  </ul>
</details>

**Pull request merged**
