### PR TITLE
kerberos_server: allow choosing MIT or Heimdal

### PR DESCRIPTION
**Pull request by kwohlfahrt**
###### Motivation for this change

Allow using MIT Kerberos as a kerberos server, and add some initial configuration. Related to #29623. 

This is my first PR, let me know if anything is not suitable.

As far as I can tell the upstream kerberos_server service was broken, as it expected binaries to be in `sbin` while they were in `bin` (see ab6c57e). There were previously no tests, this adds some basic smoke tests.

I'm happy to add more configurable options, I've so far just configured what I'm familiar with. In theory it should be possible to serve multiple realms from one server, but I don't need this and haven't been able to get it to work easily so it's not part of this PR.

Adding the usual set of plain-text configuration is difficult, as MIT and Heimdal take slightly different formats of options.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg test kerberos.mit kerberos.heimdal

**Comment by vcunat** [comment]
I think the point here was `krb5-config`, as that needs to keep reference to the headers.  I was focused on the case of `type == "lib"`.

**Comment by kwohlfahrt** [comment]
That makes sense - I will move the other programs back to the default output then unless there is an objection? Should there be separate 'bin' and 'lib' or 'out' and 'lib' outputs or should these go together?

**Comment by vcunat** [comment]
The `type == "lib"` has almost nothing there, and for the other cases it's probably not important to split.

**Comment by eqyiel** [comment]
@kwohlfahrt thanks for making an effort to fix this.

I had some similar changes in mind that I never got around to finishing: https://github.com/eqyiel/nixpkgs/commit/4114381a2dc486bb8ac9afda26a6e863ddaf033c

I'll probably try to apply it on top of your changes at some point :smile_cat:

**Comment by matthewbauer** [comment]
Looks okay to me. Any objections to merging?

**Comment by matthewbauer** [comment]
@GrahamcOfBorg test kerberos_server

**Review by matthewbauer — CHANGES_REQUESTED** [review]
Looks good but we cannot test it until tests.kerberos is in release.nix

**Comment by kwohlfahrt** [comment]
@matthewbauer I've added a line to `release.nix` - is that what you are after?

**Comment by matthewbauer** [comment]
@GrahamcOfBorg test kerberos

**Comment by kwohlfahrt** [comment]
@matthewbauer sorry, should be fixed now. Also I think you need to test `kerberos.mit` and `kerberos.heimdal` rather than just `kerberos`

**Comment by kwohlfahrt** [comment]
Rebased onto latest staging due to conflict. Not sure if I have permissions to run borg tests, so here goes:

@GrahamcOfBorg test kerberos.mit kerberos.heimdal

**Comment by kwohlfahrt** [comment]
OK, seems I can't start borg tests. @matthewbauer could you please test it again and merge if possible?

**Comment by peterhoeg** [comment]
@GrahamcOfBorg test kerberos.mit kerberos.heimdal

**Comment by kwohlfahrt** [comment]
@peterhoeg done, not tested locally yet as it rebased without edits. Will do so this evening.

**Comment by peterhoeg** [comment]
@kwohlfahrt - so building failed. You'll take a look?

**Comment by kwohlfahrt** [comment]
Yes, I am looking into it. It seems unrelated (something to do with libDRM) at first glance, but I'll investigate more.

**Comment by kwohlfahrt** [comment]
@peterhoeg this is building locally now, but Graham has an error that "target branch staging doesn't evaluate" - should I be targeting a different branch?

**Comment by peterhoeg** [comment]
Thanks for doing all this hard work!

The staging part is probably due to the change to ```pkgs/development/libraries/kerberos/krb5.nix``` as I am assuming this will cause a significant amount of rebuilding. 

I will not be able to review this in detail in the near future - the arrival of our twins is imminent now so I'm hoping @vcunat or @FRidh (or others) will be able to dedicate the time this PR deserves.

**Comment by kwohlfahrt** [comment]
This is now rebased, and tests pass locally.

@peterhoeg congratulations!

**Comment by Mic92** [comment]
This was open for too long.

**Comment by kwohlfahrt** [comment]
I think this closes #39424 as well.

**Pull request merged**
