### PR TITLE
dotnet-sdk: 6.0.416 -> 6.0.417, dotnet-sdk_7: 7.0.403 -> 7.0.404, dotnet-sdk_8: 8.0.100-rc.2.23502.2 -> 8.0.100

### PR DESCRIPTION
**Pull request by mdarocha**
## Description of changes

Celebrating the launch of .NET 8.0! 🎉

https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.25/6.0.25.md

https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.14/7.0.14.md

https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.0/8.0.0.md

Marked as security since the above updates fix several CVEs

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@NixOS/dotnet

### CODE REVIEW

**Comment by ratsclub** [comment]
I tested this against a personal project and it works just fine.

**Comment by JamieMagee** [comment]
Result of `nixpkgs-review pr 267617` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tests.writers.simple.fsharp</li>
  </ul>
</details>
<details>
  <summary>117 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>audiobookshelf</li>
    <li>avalonia-ilspy</li>
    <li>bililiverecorder</li>
    <li>boogie (dotnetPackages.Boogie)</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>certdump</li>
    <li>csharp-ls</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore (dotnet-aspnetcore_6 ,dotnetCorePackages.aspnetcore_6_0)</li>
    <li>dotnet-aspnetcore_7 (dotnetCorePackages.aspnetcore_7_0)</li>
    <li>dotnet-aspnetcore_8 (dotnetCorePackages.aspnetcore_8_0)</li>
    <li>dotnet-runtime (dotnet-runtime_6 ,dotnetCorePackages.runtime_6_0)</li>
    <li>dotnet-runtime_7 (dotnetCorePackages.runtime_7_0)</li>
    <li>dotnet-runtime_8 (dotnetCorePackages.runtime_8_0)</li>
    <li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0)</li>
    <li>dotnet-sdk_7 (dotnetCorePackages.sdk_7_0)</li>
    <li>dotnet-sdk_8 (dotnetCorePackages.sdk_8_0)</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>ilspycmd</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>kavita</li>
    <li>lidarr</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>networkminer</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pocket-updater-utility</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>ps3-disc-dumper</li>
    <li>python310Packages.clr-loader</li>
    <li>python310Packages.clr-loader.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.pythonnet</li>
    <li>python310Packages.pythonnet.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.weasel</li>
    <li>python310Packages.weasel.dist</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.weasel</li>
    <li>python311Packages.weasel.dist</li>
    <li>radarr</li>
    <li>readarr</li>
    <li>roslyn</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>space-station-14-launcher</li>
    <li>tests.dotnet.project-references</li>
    <li>tests.writers.simple.fsharpNoNugetDeps</li>
    <li>tone</li>
    <li>vintagestory</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>

**Review by raphaelr — APPROVED** [review]
LGTM

**Review by JamieMagee — APPROVED** [review]

**Comment by lontivero** [comment]
Tested against https://github.com/zkSNACKs/WalletWasabi. Worked okay.

**Review by lontivero — APPROVED** [review]

**Review by ratsclub — APPROVED** [review]

**Comment by AlexeyRaga** [comment]
Can this be merged now?

**Comment by wingi11** [comment]
Really need this...

**Comment by reckenrode** [comment]
Should this have been backported to 23.11 instead of 23.05?

**Comment by MakiseKurisu** [comment]
It was merged before 23.11 release.

**Comment by kirillrdy** [comment]
given 23.11 shipped with 8.0.100-rc.2.23502.2, I don't see why we can't backport 8.0.100

**Pull request merged**
