### PR TITLE
geos: 3.11.2 -> 3.12.0

### PR DESCRIPTION
**Pull request by willcohen**
###### Description of changes

Updated from 3.11.2 to 3.12.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by willcohen** [comment]
Shapely appears broken during nixpkgs-review -- not yet sure if this is due to GEOS or a preexisting failure.

```
error: builder for '/nix/store/zxkldmrggbhlz0iicgbwnfq528iawi8c-python3.10-pygeos-0.14.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_134-geom_234] - Failed: DID NOT RAISE <class 'pygeos.GEOSException'>
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_135-geom_235] - AssertionError: Regex pattern did not match.
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_136-geom_236] - AssertionError: Regex pattern did not match.
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_137-geom_237] - AssertionError: Regex pattern did not match.
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_138-geom_238] - AssertionError: Regex pattern did not match.
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_139-geom_239] - AssertionError: Regex pattern did not match.
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_140-geom_240] - AssertionError: Regex pattern did not match.
       > FAILED pygeos/tests/test_set_operations.py::test_coverage_union_non_polygon_inputs[geom_141-geom_241] - AssertionError: Regex pattern did not match.
       > = 48 failed, 2573 passed, 22 skipped, 1 xfailed, 22 xpassed, 18 warnings in 17.18s =
       > /nix/store/mas4ifv1v6llnqkyxq5w235x0hdq5yq3-stdenv-darwin/setup: line 1606: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/zxkldmrggbhlz0iicgbwnfq528iawi8c-python3.10-pygeos-0.14.drv'.
```

**Comment by imincik** [comment]
Shapely build fails on

```
______________ OperationsTestCase.test_parallel_offset_linestring ______________

self = <tests.test_parallel_offset.OperationsTestCase testMethod=test_parallel_offset_linestring>

    def test_parallel_offset_linestring(self):
        line1 = LineString([(0, 0), (10, 0)])
        left = line1.parallel_offset(5, 'left')
        assert_geometries_equal(left, LineString([(0, 5), (10, 5)]))
        right = line1.parallel_offset(5, 'right')
        assert_geometries_equal(right, LineString([(10, -5), (0, -5)]), normalize=True)
        right = line1.parallel_offset(-5, 'left')
        assert_geometries_equal(right, LineString([(10, -5), (0, -5)]), normalize=True)
        left = line1.parallel_offset(-5, 'right')
        assert_geometries_equal(left, LineString([(0, 5), (10, 5)]))

        # by default, parallel_offset is right-handed
        assert_geometries_equal(line1.parallel_offset(5), right)

        line2 = LineString([(0, 0), (5, 0), (5, -5)])
>       assert_geometries_equal(line2.parallel_offset(2, 'left', resolution=1),
                                LineString([(0, 2), (5, 2), (7, 0), (7, -5)]))
E       AssertionError:
E       Geometries are not equal:
E
E       Not equal to tolerance 1e-07
E        x: array(<LINESTRING (0 2, 5 2, 5.39 1.962, 5.765 1.848, 6.111 1.663, 6.414 1.414, 6....>,
E             dtype=object)
E        y: array(<LINESTRING (0 2, 5 2, 7 0, 7 -5)>, dtype=object)

tests/test_parallel_offset.py:32: AssertionError
```

which is [regression with GEOS 3.12.0](https://github.com/shapely/shapely/issues/1855)

**Comment by jtojnar** [comment]
Bumping shapely in https://github.com/NixOS/nixpkgs/pull/263989

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/pull/263989 was merged.

**Comment by imincik** [comment]
This PR is now replaced with https://github.com/NixOS/nixpkgs/pull/268130 (GEOS 3.12.1)

**Comment by willcohen** [comment]
Thank you!

**Pull request closed without merging**
