### PR TITLE
texlive: 2015 -> 2016

### PR DESCRIPTION
**Pull request by vcunat**
_I finally got from words to deeds._ Please, test your use cases!
- It's today's snapshot.
- TUG mirroring works now. It will slowly start to fail, but I've got a snapshot of all files, so we can fix that up later.
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of **some** binary files (usually in `./result/bin/`)

---

Note: only basic testing has been done so far; also see FIXME items.

### CODE REVIEW

**Comment by jokogr** [comment]
```
error: attribute ‘rotating’ missing, at /home/joko/playground/nixpkgs/pkgs/tools/typesetting/tex/dblatex/default.nix:4:26
```
CTAN reports that "The pack­age is now part of the la­tex-graph­ics bun­dle" (Source: https://www.ctan.org/pkg/rotating?lang=en), is it ok to change this dependency ("rotating") with "graphics"?

**Comment by jokogr** [comment]
I also got:

```
output path ‘/nix/store/wx77rngg1yx1ixbcv8wwkc5msqld7hm2-xassoccnt.tar.xz’ has sha512 hash ‘15rcb708spq8hv65lvccq1vnv4zbsd088g7ng0cydlyl8f3xmi2kk14244md50yzvq41qyfiizvkp72722592j927xn3ndv54vdqrp4’ when ‘2xbc9yxlzszcxc00n75vfq0xdbnh367s64hwcdq9p3jn3h154s6f5rwky54spzh1pxvfrs2hp2qg9mddsxh8an095ksgmp7845fg1ag’ was expected
```

but after running again `sudo nixos-rebuild switch`, it seems to move on...

**Comment by vcunat** [comment]
Thanks, dblatex fixed up. That hash error was likely due to some transient network error, if it disappeared (or some mirrors serve a newer version of that file already).

**Comment by jokogr** [comment]
ok, I'm missing xelatex (and xetex apparently). pdflatex is here, but my work is too dependent to the former.

My relevant systemPackages are the following:

```
    (texlive.combine {
     inherit (texlive) scheme-basic collection-bibtexextra collection-binextra
     collection-fontsrecommended collection-genericextra
     collection-genericrecommended collection-langgreek collection-latex
     collection-latexextra collection-latexrecommended collection-metapost
     collection-publishers collection-science collection-xetex xindy glossaries;
    })
```

**Comment by vcunat** [comment]
The upstream machinery for creating symlinks have changed apparently, so it's overwriting valid links to extra executables by invalid ones (and dead links are auto-cleaned by our code later).

**Comment by avnik** [comment]
@vcunat I have at least one hash mismatch during build process

output path ‘/nix/store/ck5gjbj2zf85bpjrw4vwm0n9cfn456sg-koma-script.tar.xz’ has sha512 hash ‘2lbvzgifrpfkmhvv9pcqpv4mcr3sdb4iv99qmzgwb6lagli0l8c93nzxviw2lclyy0gb69i264wcbs4nl4ax7zsq3a3n4mcjimnlcm2’ when ‘2pbcb0jwlfy76z673sxapb3gaca4hd6i15q7865gh45vkgjvv01x18xps1f15micfakzsccync0wl7mj1x2a0rmb0i006lnqrscs5if’ was expected

I still curious, why  hashes in CTAN changes

**Comment by jokogr** [comment]
@avnik that's because we are using a snapshot of the up-to-date TeX Live tree, where only the latest packages are available. I don't believe it's NixOS fault, perhaps we need to contact with upstream developers, so that they maintain version numbers in their packaging.

**Comment by vcunat** [comment]
@avnik: upstream continuously updates packages in-place. Some yearly snapshots are there but badly accessible (without mirroring).

**Comment by vcunat** [comment]
BTW, I did ask upstream (tldistro ML), and even the yearly snapshots seem too large for them to mirror. Distributions are expected to do so themselves.

**Comment by avnik** [comment]
@vcunat: I see that they use SVN internally, can  fetchsvn give us more stable result? Or may be special downloader for TL stuff, derived from tlmgr?

Another option is returning back to big tarball based snapshots, but use them as unpacked/fixed-output, and populate with symlinks.

**Comment by vcunat** [comment]
The big tarballs have the same release timing and mirroring as the small ones. We do fix output of the unpacked packages (all the thousands of them). AFAIK the svn is for the infrastructure like the common binaries and not for the hundreds of megabytes (compressed) of packages.

**Comment by avnik** [comment]
At least tags and branches have texmf-dist http://tug.org/svn/texlive/tags/texlive-2016.0/Master/texmf-dist/ so it have all "TL packages" stuff

**Comment by avnik** [comment]
Also everything in trunk as well -- http://tug.org/svn/texlive/trunk/Master/texmf-dist/

**Comment by vcunat** [comment]
I see. We could in theory extract individual packages from that with texlive.tlpdb as that contains file lists... 

But anyway, I don't see what we could get. I don't think there's a way to fetch efficiently individual files at individual revisions from svn and it's likely without a mirror as well. And, from later #10026 discussion it's apparently not a problem for us to mirror snapshots of all the compressed packages (and e.g. update them yearly)... maybe not for docs as that's ~1.3 GB but the rest is 0.7 GB.

**Comment by avnik** [comment]
Current way is enough good, as long as files not disappears/changed under foots.

**Comment by vcunat** [comment]
@jokogr: xe(la)tex and other bin/ links should be fine now, as in 2015. Thanks for noticing the problem.

**Comment by vcunat** [comment]
I also uploaded my snapshot to a temporary mirror, so you should no longer get hash mismatches.

**Comment by jokogr** [comment]
@vcunat thanks, my project started compiling... and xindy is broken again!

```
% xindy -V
xindy release: 2.5.1
xindy script version: 1.18
xindy: Could not execute xindy kernel: No such file or directory
```

I think the TeX Live maintainers changed the way xindy is packaged, they don't compile it at all. So, instead of patching `xindy-?.?.?/user-commands/xindy.in` for system's clisp, could you please patch directly `xindy.pl`? I think this will solve it.

Could you also let me know how I could get into the installation environment so that I can help you more directly, with some patches? I mean a command like `nix-shell`, but for texlive-new packages.

Many thanks again for your efforts so far!

**Comment by vcunat** [comment]
@jokogr: xindy fixed up now. For quick building of tex-envs I use commands like:
```
$ nix-build -E 'with import ./. {}; texlive.combine { inherit (texlive) scheme-small xindy; }' -Q
$ ./result/bin/xindy -V
```
while being in the root of a nixpkgs repo checkout. You can `import <nixpkgs> {}` instead to use the default location (given by `$NIX_PATH` etc.).

**Comment by jokogr** [comment]
@vcunat many thanks again for your work, everything seems to be working as expected.

I just need to update `biber` to a newer version, the biblatex version which comes with TeX Live 2016 (3.1?) requires biber 2.2 to work. I will try to make a PR to update the separate package, as you have told me in a previous issue.

**Comment by abbradar** [comment]
@jokogr I've already updated biber in d51ec20a50a3dbce2ef129e3fa65c46a171c3591.

**Comment by jokogr** [comment]
@abbradar many thanks for letting me know, I am on `channels/nixos-unstable` and hadn't noticed it earlier.

**Comment by jokogr** [comment]
@vcunat @abbradar I had to upgrade biber to v2.5 and my dissertation is compiling properly at last! I have made my first PR #16597, let me know if it is ok.

**Comment by jokogr** [comment]
texlive source is no longer available, so `bin.nix` has to be modified:

```
   common = rec {
     src = fetchurl {
-      url = "ftp://tug.org/historic/systems/texlive/${year}/texlive-${year}0523-source.tar.xz";
-      sha512 = "9fdd69d237238385240e918456f54791a38e57b573edf5df839c57e56a00090"
-        + "12b68b7b92298c3e137181325e2be84d7a84e9c7cf41ae9739bb3329d84194564";
+      url = "ftp://tug.org/historic/systems/texlive/${year}/texlive-${year}0523b-source.tar.xz";
+      sha512 = "915fa2f5e2099dd385ef81033db7aafdf09558c0c200fed0748a8a42fd61f69"
+        + "d3eaac9decea334e30981af739dd81061a9b1d6853c7f6d00285fe0be40e26c3e";
     };
```

**Comment by domenkozar** [comment]
@vcunat what's the status on this? Needs more testing?

**Comment by vcunat** [comment]
Yes, more testing. Also, repo size would grow significantly (by almost 2 MB), thanks to upstream migrating to much longer hashes, but I suppose we don't have a nice solution for such problems yet. And there surely are some other minor details, most of which don't need to delay merging.

**Comment by veprbl** [comment]
I've decided to give it a try. I do:
```
nix-env -i texlive-combined-full-2016 -f .
```
and eventually get
```
building path(s) ‘/nix/store/qzf71chdi51pswanqgrmam5qmlsiszqq-texlive-2up-2016’
building path(s) ‘/nix/store/hmckry7gfm1lp72w6p28vldw3lpxppsm-texlive-20160523-source.tar.xz’

trying ftp://tug.org/historic/systems/texlive/2016/texlive-20160523-source.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (78) RETR response: 550
error: cannot download texlive-20160523-source.tar.xz from any mirror
```

**Comment by veprbl** [comment]
I guess it's up to ```s/20160523/20160523b/``` to fix it

**Comment by vcunat** [comment]
Yes, I should add that one among the mirrored stuff to prevent such problems in future.

**Comment by RamKromberg** [comment]
@vcunat Any chance you can throw in lesstif -> motif while you're at it? (https://github.com/NixOS/nixpkgs/issues/17359)

**Comment by vcunat** [comment]
@RamKromberg, yes, if it's that simple.

**Comment by RamKromberg** [comment]
@vcunat Now that Darwin and Linux have both been tested, it should be as straightforward _s/lesstif/foobar/g_.
Besides, I think _"--without-x"_ is probably preventing it from being used anyhow so it's only being evaluate by autoconf.

**Comment by vcunat** [comment]
Generally, xorg font server has been obsoleted for ages by fontconfig. TeX Live does depend on fontconfig so I'd hope it doesn't X for fonts (and I suspect primarily they've got their own way anyway).

Now that I look at this PR, I have `lesstif` in parameters but it isn't passed down to any package so it doesn't even get evaluated :-)

**Comment by RamKromberg** [comment]
> ...obsoleted for ages by fontconfig...

I see. Then I guess it's just for a few of the visual tools then.

> sstif in parameters but it isn't passed down to any package so it

Thanks for confirming that. I figured _"--without-x"_ will make sure that's the case but I couldn't be sure. If you're not going to omit lesstif altogether, I'd still like to see it replaced with motif. Even if it's not being evaluated as is, people might still want to build xdvi and the likes.

Regardless, whichever you decide, you can close https://github.com/NixOS/nixpkgs/issues/17359 when you're done. texlive was the last package holding it back.

Thanks :)

**Comment by RamKromberg** [comment]
Thanks :)

**Comment by domenkozar** [comment]
@vcunat do you think we can get this merged in the next days? I don't mind the extra 2MB as there's no workaround for it yet.

**Comment by vcunat** [comment]
@domenkozar: I thought so a week ago, but ATM it doesn't seem I will catch it.

**Comment by jokogr** [comment]
@vcunat what is missing, could I help you somehow? Your PR is still able to be built (with minor changes) on top of current channels/nixos-unstable.

**Comment by vcunat** [comment]
Hopefully only the two FIXMEs, but I don't remember now. With a bit of refactoring, the sha512 value could be dropped, saving ~1 MB in history.

**Comment by vcunat** [comment]
I'm confident I can fix those and get it into 16.09, even a little later during September, as the current texlive state in master isn't ideal at all AFAIK.

@jokogr, the only related help I can think of: it would be very nice to have an automatic test suite &ndash; a collection of derivations that verifies that particular documents compile fine with respective sets of packages. It's nothing urgent, but it would make any texlive changes easier to merge. Some test cases could be extracted from our past issues already.

**Comment by jokogr** [comment]
@vcunat which past issues were you referring to? Since now I have been testing the TeXLive deployments by compiling my thesis.

I have also tried to apply this PR to current `master` and `channels/nixos-unstable` and it wasn't being applied cleanly, should I do something else? (I've used `curl -L https://github.com/NixOS/nixpkgs/pull/16391.patch | git am`).

**Comment by vcunat** [comment]
@jokogr: I don't remember the issues exactly; there weren't many and they're drowned by many reports of mismatching hashes :-/

Rebasing/picking this PR is no good, better use merge instead, as that's conflict-less with current master.
```
$ git pull --no-rebase git://github.com/NixOS/nixpkgs.git refs/pull/16391/head
```

**Comment by vcunat** [comment]
@edolstra: can we mirror the tarballs? All of them take 2.1 GB. If that's too much, without `*.doc.* *.source.*` it's only ~0.7 GB.

Note: `copy-tarballs.pl` seems to find them, but I'd like to purge their hashes before merging, as they would take excessive amount of space in git history - I want to keep only the unpacked fixed-output sha1s.

**Comment by vcunat** [comment]
ATM I mirror them temporarily on http://lipa.ms.mff.cuni.cz/~cunav5am/nix/texlive-2016/ but I shouldn't even use that machine anymore...

**Comment by vcunat** [comment]
OK, git history churn reduced significantly, and some bugs were fixed. I think this is basically mergeable, except for mirroring those tarballs; 16.09 notification: @domenkozar. Basic tests of mine seem fine.

**Comment by domenkozar** [comment]
Maybe we should create a Hydra jobset for master to test if any packages break?

**Comment by domenkozar** [comment]
Or just put it into staging, then backport to 16.09 once it's good.

**Comment by vcunat** [comment]
Rebuild impact is relatively small and *build*-time breakages unlikely, I think.

**Comment by domenkozar** [comment]
OK, I'm testing my tex stuff.

**Comment by domenkozar** [comment]
@vcunat 

```
! LaTeX Error: File `luatex.def' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: def)

Enter file name: 
! Emergency stop.
<read *> 
   
l.148 ...ned{ver@\Gin@driver}{\input{\Gin@driver}}{}

pandoc: Error producing PDF
```

This previously worked, do you know what's going on?

**Comment by vcunat** [comment]
I don't know, at least not right away.

**Comment by domenkozar** [comment]
@vcunat should these be backwards compatible?

**Comment by domenkozar** [comment]
Here's the diff I had to do to get the project building again:

```
diff --git a/src/doc/default.nix b/src/doc/default.nix
index 673d319..e3529f8 100644
--- a/src/doc/default.nix
+++ b/src/doc/default.nix
@@ -13,7 +13,7 @@ stdenv.mkDerivation rec {
 
   buildInputs = [ ditaa pandoc git
    (texlive.combine {
-      inherit (texlive) scheme-small luatex luatexbase sectsty titlesec cprotect bigfoot titling droid;
+      inherit (texlive) scheme-small luatex luatexbase sectsty titlesec cprotect bigfoot titling droid luatex-def ctablestack;
     })
   ];
```

If we document such changes will be needed, +1 to merge this.

**Comment by vcunat** [comment]
I just found it... you could use just `collection-luatex`. This part seems to be changing upstream and now it's different again from our 2016 version.

**Comment by expipiplus1** [comment]
This worked for all my tex stuff (a few letters, CVs and some pandoc-generated documents) without a problem.

**Comment by jokogr** [comment]
It has also worked with my PhD thesis and a couple of publications (IEEE
templates etc.)

**Comment by edolstra** [comment]
@vcunat I've run
```
./maintainers/scripts/copy-tarballs.pl --expr '(import ./. {}).texlive'
```
but that didn't find many texlive tarballs (only http://lipa.ms.mff.cuni.cz/~cunav5am/nix/texlive-2016/texlive-20160523b-source.tar.xz)...

**Comment by vcunat** [comment]
@edolstra: I'm sorry, I purged the hashes in this PR in the meantime (perhaps a mistake to push it here). It should work on the previous refs, e.g. 3be36a5:
```
$ env AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar maintainers/scripts/copy-tarballs.pl --dry-run --expr '(import ./. {}).texlive'
evaluation returned 7226 tarballs
Net::Amazon::S3: Amazon responded with 403 Forbidden
```

**Comment by vcunat** [comment]
Oh, but that command will make them hash-addressed, won't it? I wanted to avoid those 7k additional hashes in nixpkgs, but if you want them hash-addressed, I see no better way than me adding those hashes afterwards.

**Comment by edolstra** [comment]
I'm probably missing something here. What exactly is the problem here? Note that if the texlive files are not fetched via regular `fetchurl` calls, them it's pointless to mirror them on tarballs.nixos.org.

**Comment by vcunat** [comment]
The problem is that 7k sha512 hashes would take quite a lot of space in nixpkgs (they were in base16 originally, adding ~1 MB). Currently the implementation uses something similar to `fetchzip`, because I wanted the unpacked contents to be fixed-output (as with 2015).

@edolstra: from my point of view it would work well to have `http://tarballs.nixos.org/texlive-2016/${name}.tar.xz`, i.e. "copy the directory as it is". I see a couple of similar references in nixpkgs, but if you only want to support content-addressing for this, I might e.g. add a set of sha1 in base32.

**Comment by vcunat** [comment]
I staged this. We can resolve mirroring a bit later, I suppose. Hashes of the outputs shouldn't change anyway.

**Comment by cmfwyp** [comment]
@vcunat

KOMA-Script [is broken](http://www.komascript.de/release3.20) in the version (3.20) currently on nixos-unstable, but the issue [was fixed in 3.21](https://tex.stackexchange.com/questions/313519/mactex-2016-compile-generates-errors) so it can be fixed by upgrading koma-script to 3.21 in Nixpkgs. I updated `fixedHashes.nix` and `pkgs.nix`, and tried rebuilding only to realize the package gets downloaded from `http://lipa.ms.mff.cuni.cz/~cunav5am/nix/texlive-2016/koma-script.tar.xz`, which is 3.20.

**Comment by vcunat** [comment]
I just took what was in upstream TeX Live 2016; we can individually update such problematic packages, but I don't think I can get to it within a week.

**Comment by domenkozar** [comment]
@vcunat can I ask you to write a changelog entry for this PR?

**Comment by jokogr** [comment]
@vcunat could you also post how one could update manually TeXLive packages? In addition to what @cmfwyp did, I have added a `url` attribute in the `koma-script` of `pkgs.nix`, but still no luck.

**Comment by vcunat** [comment]
It's just a version update, but I can write a simple entry into release notes.

It isn't possible to "just update", because there is no stable location where to download from, at least no in upstream.

**Comment by jokogr** [comment]
@vcunat e.g., if I download from http://ftp.ntua.gr/mirror/ctan/systems/texlive/tlnet/archive/koma-script.tar.xz, it currently has v3.21 as seen in the extracted `tlpkg/tlpobj/koma-script.tlpobj` file (`catalogue-version 3.21`). How to make nix compile this one?

**Comment by cmfwyp** [comment]
@jokogr

My understanding is that we cannot do that because that URL will become version 3.22 as soon as it is released, and then our build will be broken.

Are we able to update the archives on http://lipa.ms.mff.cuni.cz/~cunav5am/nix/texlive-2016 to a newer version? If so, there's the solution.

**Comment by jokogr** [comment]
@cmfwyp I know that's the case, upstream URLs of future versions are going to be identical to the previous ones.

Supposing that I host the updated package on my webserver, so I have a stable location for this version, my question was how to update the respective nix expressions, so that only this package gets updated.

**Pull request merged**
