### PR TITLE
zed-editor: 0.158.2 -> 0.159.5

### PR DESCRIPTION
**Pull request by bbigras**
https://github.com/zed-industries/zed/releases/tag/v0.159.5

nix icons now, yay \o/
image

I hope https://zed.dev/blog/remote-development will works with nix.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bbigras** [comment]
I got `[ERROR] encountered 23 errors resolving licenses, unable to generate output`

**Comment by bbigras** [comment]
https://zed.dev/blog/remote-development seems to work with direnv. zed-editor doesn't seem to like that `~/.ssh/config` is a symlink. Here's a workaround:

```sh
cd ~/.ssh
cp config config2
mv config2 config
chmod 600 config
```

**Comment by GaetanLepage** [comment]
As `staging-next` landed in `master` a few hours ago, I rebased this branch locally and tried to build `zed-editor` on darwin.
Unfortunately it's not possible in the sandbox:
```
these 2 derivations will be built:
  /nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv
  /nix/store/s8lz04gfiqbghxlzvfh8m7wx26gnm7cm-zed-editor-0.159.5.drv
cargo-vendor-dir-aarch64-darwin> building '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' on 'ssh://glepage@darwin-build-box.nix-community.org'
copying 0 paths
error: build of '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' on 'ssh://glepage@darwin-build-box.nix-community.org' failed: error:
              … while waiting for the build environment for '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' to initialize (failed with exit code 1, previous messages: sandbox initialization failed: pattern serialization length 70435 exceeds maximum (65535)|failed to configure sandbox: pattern seriali
zation length 70435 exceeds maximum (65535))

              error: unexpected EOF reading a line
error: builder for '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/s8lz04gfiqbghxlzvfh8m7wx26gnm7cm-zed-editor-0.159.5.drv' failed to build
```

@niklaskorz can you try building it locally please ?

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352420`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Tested locally successfully on `x86_64-linux`.

**Comment by niklaskorz** [comment]
> As `staging-next` landed in `master` a few hours ago, I rebased this branch locally and tried to build `zed-editor` on darwin. Unfortunately it's not possible in the sandbox:
> 
> ```
> these 2 derivations will be built:
>   /nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv
>   /nix/store/s8lz04gfiqbghxlzvfh8m7wx26gnm7cm-zed-editor-0.159.5.drv
> cargo-vendor-dir-aarch64-darwin> building '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' on 'ssh://glepage@darwin-build-box.nix-community.org'
> copying 0 paths
> error: build of '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' on 'ssh://glepage@darwin-build-box.nix-community.org' failed: error:
>               … while waiting for the build environment for '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' to initialize (failed with exit code 1, previous messages: sandbox initialization failed: pattern serialization length 70435 exceeds maximum (65535)|failed to configure sandbox: pattern seriali
> zation length 70435 exceeds maximum (65535))
> 
>               error: unexpected EOF reading a line
> error: builder for '/nix/store/4pc4264zadx6icf77vbivwq7x80cm9dw-cargo-vendor-dir.drv' failed with exit code 1
> error: 1 dependencies of derivation '/nix/store/s8lz04gfiqbghxlzvfh8m7wx26gnm7cm-zed-editor-0.159.5.drv' failed to build
> ```
> 
> @niklaskorz can you try building it locally please ?

Looking into it right now

**Comment by GaetanLepage** [comment]
> Builds fine for me on aarch64-darwin:

Thanks ! I'll merge then.

**Comment by bbigras** [comment]
Thanks everyone!

**Pull request merged**
