### PR TITLE
cypress: 10.3.1 -> 10.8.0

### PR DESCRIPTION
**Pull request by Hoverbear**
###### Description of changes

Update cypress to 10.8.0 using the update script: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/cypress/update.sh

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
Please, fix commit message title:

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

**Comment by Hoverbear** [comment]
Slipped my mind, thanks for the catch!

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 191199` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>polaris</li>
    <li>polaris-web</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cypress</li>
  </ul>
</details>

**Comment by superherointj** [comment]
polaris, polaris-web are already failing on master.

**Comment by superherointj** [comment]
`Cypress` is named in uppercase. Would be relevant to have a dynamic link to lowercase.

**Comment by superherointj** [comment]
image
`meta.mainProgram` is missing

**Review by Craftzman7 — APPROVED** [review]
As long as ofborg comes back it LGTM.

**Comment by Hoverbear** [comment]
@superherointj I added the `meta.mainProgram` change. 

I did not add a link since the existing version in nixpkgs does not have a `cypress` link. Since this is a version upgrade PR, I do not believe it should introduce such a change. I suggest if you would like a lower cased link then you could make such a change in a future PR.

```bash
❯ nix build nixpkgs#cypress

❯ ls result/bin/
Cypress  resources

❯ nix build .#cypress
warning: Git tree '/home/ana/git/nixos/nixpkgs' is dirty

❯ ls result/bin
Cypress  resources
```

**Comment by superherointj** [comment]
> @superherointj I added the `meta.mainProgram` change.

`mainProgram` is unnecessary if `cypress` exist in lowercase (as symlink).

> I did not add a link since the existing version in nixpkgs does not have a `cypress` link.

Exactly because it doesn't exist that a symlink should be added.

> Since this is a version upgrade PR, I do not believe it should introduce such a change. 

It is fine to make changes in upgrades.

> I suggest if you would like a lower cased link then you could make such a change in a future PR.

-.-

**Comment by Hoverbear** [comment]
There are plenty of examples of packages (such as `neovim`) which do not have symlinks in their output for that package name:

```bash
❯ nix build nixpkgs#neovim

❯ ls result/bin/
nvim  nvim-python3  nvim-ruby
```

I do not think this change is necessary for this package upgrade.

**Comment by superherointj** [comment]
> There are plenty of examples of packages (such as `neovim`) which do not have symlinks in their output for that package name

Is Vim application named as `Vim` in **uppercase**? I guess no.

Suggested symlink is to make application available in lowercase. Avoiding the need of `mainProgram`.

**Comment by SuperSandro2000** [comment]
@ofborg build cypress

**Comment by lheckemann** [comment]
@superherointj disagree. We should stick to upstream naming conventions for binaries (even if they're weird) and not disseminate unusual aliases which only work in nixpkgs. mainProgram only is the correct approach here.

**Comment by superherointj** [comment]
> @superherointj disagree. We should stick to upstream naming conventions for binaries (even if they're weird) and not disseminate unusual aliases which only work in nixpkgs. mainProgram only is the correct approach here.

Problem with uppercase is it does not list when auto completing when typing in lower case. And no one knows to type in upper case when looking up something. It is like the application the does not exist. Until the person understand that it is in uppercase.
Uppercase could make sense for Windows but not Linux. Anyway. We diverge then.

**Comment by superherointj** [comment]
> @superherointj disagree. We should stick to upstream naming conventions for binaries (even if they're weird) and not disseminate unusual aliases which only work in nixpkgs. mainProgram only is the correct approach here.

Problem with uppercase is it does not list when auto completing when typing in lower case. And no one knows to type in upper case when looking up something. It is like the application does not exist. Until the person understand that it is in uppercase.

Try: `nix-shell -p cypress`
Then: type: `cy` [TAB]

Notice package name is in lowercase. Why would the application name be in upper case?

I imagine the reason upstream is using uppercase is Windows. Bad habits die hard.

If you stick by that. We diverge then. I stick to my position. Uppercase for application name is problematic.

**Comment by lheckemann** [comment]
Then get upstream to change that, or use a smarter shell. We shouldn't change upstream behaviour where it's not necessary to make it work on NixOS.

**Pull request merged**
