### PR TITLE
vscode-extensions.ms-vscode.cpptools: Use the bundled interpreter for cpptools* 

### LINKED ISSUE #311425: ms-vscode.cpptools fails with Error: EROFS: read-only file system, chmod
### Describe the bug
Open a C++ project in vscode with the `ms-vscode.cpptools` extension installed and see the following in the Extension Host output window:

> 2024-05-13 13:47:33.703 [error] Activating extension ms-vscode.cpptools failed due to an error:
> 2024-05-13 13:47:33.703 [error] Error: EROFS: read-only file system, chmod '/nix/store/3zygrdic6q4wg40lmlb3gbffrgncvdv7-vscode-extensions/share/vscode/extensions/ms-vscode.cpptools/bin/libc.so'

### Steps To Reproduce
1. Open a C++ project in vscode with the `cpptools` extension installed
2. Notice how autocompletion etc. features do not activate.
3. Go to the output window and select the Extension Host and you will see the following:

> [error] Error: EROFS: read-only file system, chmod '/nix/store/3zygrdic6q4wg40lmlb3gbffrgncvdv7-vscode-extensions/share/vscode/extensions/ms-vscode.cpptools/bin/libc.so'

### Expected behavior
The extension should work

### Screenshots
image

### Notify maintainers

@jraygauthier 
@StarGate01 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - channels(root): `"nixos"`
 - channels(jkolb): `""`
 - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by kjeremy**
## Description of changes

Previously `autoPatchelfHook` would stomp on the interpreter for the bundled cpptools* executables. Here we manually run the hook and then explicitly patch the interpreter.

Fixes #311425 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by JohnRTitor — CHANGES_REQUESTED** [review]
Check is failing, could you format the file with `nixfmt-rfc-style`?

**Comment by kjeremy** [comment]
> Check is failing, could you format the file with `nixfmt-rfc-style`?

Done.

**Review by StarGate01 — APPROVED** [review]
LGTM, works in my installation of vscode. I am able to navigate C++ projects properly again.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 314009` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vscode-extensions.ms-vscode.cpptools</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]
LGTM

**Review by StarGate01 — APPROVED** [review]

**Pull request merged**
