### PR TITLE
ocamlPackages.janeStreet: 0.13 → 0.14

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

#106356

This removes `sqlexpr` as it cannot be built with dune 2.

Closes #106344.
Closes #102451.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
Rebased on top of #106752.

**Comment by bcc32** [comment]
I think this update is missing `expect_test_helpers_async` (the successor to `expect_test_helpers`) and `topological_sort`.  Might be missing a few others but those are the ones I noticed when building some personal projects.

**Comment by vbgl** [comment]
Thanks. I’ve just added some of the missing libraries.

**Comment by vbgl** [comment]
Are there objections to merging this?

**Comment by sternenseemann** [comment]
Seems it's possible to enable tests for the `janeStreet` set: <https://github.com/sternenseemann/nixpkgs/commit/26b18e19ebb5b1615a39330caa3a037684c20a8c>

**Comment by sternenseemann** [comment]
I've dabbled around a bit and went through the opam files of the packages. I've noticed the following things

* We could enable tests
* Some `minimumOCamlVersion`s differ from 4.08

I've implemented changes based on that, you can see the changes comparing to your branch [here](https://github.com/vbgl/nixpkgs/compare/ocaml-janestreet-0.14...sternenseemann:ocaml-janestreet-0.14).

I've also changed some dependencies around based on my testing and the opam files, I'm not 100% sure about those, maybe I missed a propagation here or there, I guess a second pair of eyes would help there :)

**Comment by vbgl** [comment]
Thanks a lot! I’ve added your changes to the last commit of this PR.

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 106386` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>244 packages built:</summary>
  <ul>
    <li>acgtk</li>
    <li>coqPackages.coq-elpi</li>
    <li>coqPackages.hierarchy-builder</li>
    <li>dune-release</li>
    <li>eff</li>
    <li>flow</li>
    <li>framac</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>ocaml-crunch</li>
    <li>ocamlPackages.accessor</li>
    <li>ocamlPackages.accessor_async</li>
    <li>ocamlPackages.accessor_base</li>
    <li>ocamlPackages.accessor_core</li>
    <li>ocamlPackages.angstrom</li>
    <li>ocamlPackages.angstrom-async</li>
    <li>ocamlPackages.angstrom-lwt-unix</li>
    <li>ocamlPackages.angstrom-unix</li>
    <li>ocamlPackages.asn1-combinators</li>
    <li>ocamlPackages.async</li>
    <li>ocamlPackages.async_extra</li>
    <li>ocamlPackages.async_find</li>
    <li>ocamlPackages.async_inotify</li>
    <li>ocamlPackages.async_interactive</li>
    <li>ocamlPackages.async_js</li>
    <li>ocamlPackages.async_kernel</li>
    <li>ocamlPackages.async_rpc_kernel</li>
    <li>ocamlPackages.async_sendfile</li>
    <li>ocamlPackages.async_shell</li>
    <li>ocamlPackages.async_smtp</li>
    <li>ocamlPackages.async_ssl</li>
    <li>ocamlPackages.async_unix</li>
    <li>ocamlPackages.base</li>
    <li>ocamlPackages.base_bigstring</li>
    <li>ocamlPackages.base_quickcheck</li>
    <li>ocamlPackages.bignum</li>
    <li>ocamlPackages.bin_prot</li>
    <li>ocamlPackages.biocaml</li>
    <li>ocamlPackages.bistro</li>
    <li>ocamlPackages.bonsai</li>
    <li>ocamlPackages.ca-certs</li>
    <li>ocamlPackages.camlimages</li>
    <li>ocamlPackages.cfstream</li>
    <li>ocamlPackages.cinaps</li>
    <li>ocamlPackages.cohttp</li>
    <li>ocamlPackages.cohttp-async</li>
    <li>ocamlPackages.cohttp-lwt</li>
    <li>ocamlPackages.cohttp-lwt-unix</li>
    <li>ocamlPackages.conduit</li>
    <li>ocamlPackages.conduit-async</li>
    <li>ocamlPackages.conduit-lwt</li>
    <li>ocamlPackages.conduit-lwt-unix</li>
    <li>ocamlPackages.containers</li>
    <li>ocamlPackages.containers-data</li>
    <li>ocamlPackages.core</li>
    <li>ocamlPackages.core_bench</li>
    <li>ocamlPackages.core_extended</li>
    <li>ocamlPackages.core_kernel</li>
    <li>ocamlPackages.cow</li>
    <li>ocamlPackages.crunch</li>
    <li>ocamlPackages.cstruct-sexp</li>
    <li>ocamlPackages.csvfields</li>
    <li>ocamlPackages.curly</li>
    <li>ocamlPackages.delimited_parsing</li>
    <li>ocamlPackages.dns</li>
    <li>ocamlPackages.dns-client</li>
    <li>ocamlPackages.ecaml</li>
    <li>ocamlPackages.eliom</li>
    <li>ocamlPackages.elpi</li>
    <li>ocamlPackages.email_message</li>
    <li>ocamlPackages.encore</li>
    <li>ocamlPackages.expect_test_helpers_async</li>
    <li>ocamlPackages.expect_test_helpers_core</li>
    <li>ocamlPackages.ezjsonm</li>
    <li>ocamlPackages.fiat-p256</li>
    <li>ocamlPackages.fieldslib</li>
    <li>ocamlPackages.functoria</li>
    <li>ocamlPackages.functoria-runtime</li>
    <li>ocamlPackages.git</li>
    <li>ocamlPackages.git-http</li>
    <li>ocamlPackages.git-unix</li>
    <li>ocamlPackages.graphql-cohttp</li>
    <li>ocamlPackages.higher_kinded</li>
    <li>ocamlPackages.httpaf</li>
    <li>ocamlPackages.incr_dom</li>
    <li>ocamlPackages.incr_map</li>
    <li>ocamlPackages.incr_select</li>
    <li>ocamlPackages.incremental</li>
    <li>ocamlPackages.index</li>
    <li>ocamlPackages.ipaddr</li>
    <li>ocamlPackages.ipaddr-cstruct</li>
    <li>ocamlPackages.ipaddr-sexp</li>
    <li>ocamlPackages.irmin</li>
    <li>ocamlPackages.irmin-fs</li>
    <li>ocamlPackages.irmin-git</li>
    <li>ocamlPackages.irmin-graphql</li>
    <li>ocamlPackages.irmin-http</li>
    <li>ocamlPackages.irmin-mem</li>
    <li>ocamlPackages.irmin-pack</li>
    <li>ocamlPackages.irmin-test</li>
    <li>ocamlPackages.irmin-unix</li>
    <li>ocamlPackages.iter</li>
    <li>ocamlPackages.jane-street-headers</li>
    <li>ocamlPackages.js_of_ocaml</li>
    <li>ocamlPackages.js_of_ocaml-compiler</li>
    <li>ocamlPackages.js_of_ocaml-lwt</li>
    <li>ocamlPackages.js_of_ocaml-ocamlbuild</li>
    <li>ocamlPackages.js_of_ocaml-ppx</li>
    <li>ocamlPackages.js_of_ocaml-ppx_deriving_json</li>
    <li>ocamlPackages.js_of_ocaml-tyxml</li>
    <li>ocamlPackages.jst-config</li>
    <li>ocamlPackages.kafka</li>
    <li>ocamlPackages.macaddr</li>
    <li>ocamlPackages.macaddr-cstruct</li>
    <li>ocamlPackages.macaddr-sexp</li>
    <li>ocamlPackages.mdx</li>
    <li>ocamlPackages.metrics-mirage</li>
    <li>ocamlPackages.metrics-unix</li>
    <li>ocamlPackages.mirage</li>
    <li>ocamlPackages.mirage-crypto-pk</li>
    <li>ocamlPackages.mirage-crypto-rng</li>
    <li>ocamlPackages.mirage-crypto-rng-mirage</li>
    <li>ocamlPackages.mirage-logs</li>
    <li>ocamlPackages.mirage-net</li>
    <li>ocamlPackages.mirage-profile</li>
    <li>ocamlPackages.mirage-protocols</li>
    <li>ocamlPackages.mirage-runtime</li>
    <li>ocamlPackages.mirage-stack</li>
    <li>ocamlPackages.mirage-types</li>
    <li>ocamlPackages.mirage-types-lwt</li>
    <li>ocamlPackages.mirage-unix</li>
    <li>ocamlPackages.mtime</li>
    <li>ocamlPackages.mustache</li>
    <li>ocamlPackages.nocrypto</li>
    <li>ocamlPackages.ocaml-compiler-libs</li>
    <li>ocamlPackages.ocaml-r</li>
    <li>ocamlPackages.ocplib-json-typed</li>
    <li>ocamlPackages.ocplib-json-typed-browser</li>
    <li>ocamlPackages.ocplib-json-typed-bson</li>
    <li>ocamlPackages.ocsigen-start</li>
    <li>ocamlPackages.ocsigen-toolkit</li>
    <li>ocamlPackages.ocsigen_server</li>
    <li>ocamlPackages.odoc</li>
    <li>ocamlPackages.opium</li>
    <li>ocamlPackages.opium_kernel</li>
    <li>ocamlPackages.otr</li>
    <li>ocamlPackages.owl</li>
    <li>ocamlPackages.parsexp</li>
    <li>ocamlPackages.patience_diff</li>
    <li>ocamlPackages.pgocaml</li>
    <li>ocamlPackages.pgocaml_ppx</li>
    <li>ocamlPackages.phylogenetics</li>
    <li>ocamlPackages.posixat</li>
    <li>ocamlPackages.ppx_accessor</li>
    <li>ocamlPackages.ppx_assert</li>
    <li>ocamlPackages.ppx_base</li>
    <li>ocamlPackages.ppx_bench</li>
    <li>ocamlPackages.ppx_bin_prot</li>
    <li>ocamlPackages.ppx_cold</li>
    <li>ocamlPackages.ppx_compare</li>
    <li>ocamlPackages.ppx_cstruct</li>
    <li>ocamlPackages.ppx_custom_printf</li>
    <li>ocamlPackages.ppx_deriving_rpc</li>
    <li>ocamlPackages.ppx_enumerate</li>
    <li>ocamlPackages.ppx_expect</li>
    <li>ocamlPackages.ppx_fields_conv</li>
    <li>ocamlPackages.ppx_fixed_literal</li>
    <li>ocamlPackages.ppx_hash</li>
    <li>ocamlPackages.ppx_here</li>
    <li>ocamlPackages.ppx_inline_test</li>
    <li>ocamlPackages.ppx_irmin</li>
    <li>ocamlPackages.ppx_jane</li>
    <li>ocamlPackages.ppx_js_style</li>
    <li>ocamlPackages.ppx_let</li>
    <li>ocamlPackages.ppx_module_timer</li>
    <li>ocamlPackages.ppx_optcomp</li>
    <li>ocamlPackages.ppx_optional</li>
    <li>ocamlPackages.ppx_pattern_bind</li>
    <li>ocamlPackages.ppx_pipebang</li>
    <li>ocamlPackages.ppx_sexp_conv</li>
    <li>ocamlPackages.ppx_sexp_message</li>
    <li>ocamlPackages.ppx_sexp_value</li>
    <li>ocamlPackages.ppx_stable</li>
    <li>ocamlPackages.ppx_string</li>
    <li>ocamlPackages.ppx_typerep_conv</li>
    <li>ocamlPackages.ppx_variants_conv</li>
    <li>ocamlPackages.ppxlib</li>
    <li>ocamlPackages.prof_spacetime</li>
    <li>ocamlPackages.protocol_version_header</li>
    <li>ocamlPackages.ptime</li>
    <li>ocamlPackages.re2</li>
    <li>ocamlPackages.re2_stable</li>
    <li>ocamlPackages.resource_cache</li>
    <li>ocamlPackages.rpclib-lwt</li>
    <li>ocamlPackages.secp256k1</li>
    <li>ocamlPackages.sexp</li>
    <li>ocamlPackages.sexp_diff_kernel</li>
    <li>ocamlPackages.sexp_macro</li>
    <li>ocamlPackages.sexp_pretty</li>
    <li>ocamlPackages.sexp_select</li>
    <li>ocamlPackages.sexplib</li>
    <li>ocamlPackages.sexplib0</li>
    <li>ocamlPackages.shell</li>
    <li>ocamlPackages.shexp</li>
    <li>ocamlPackages.spawn</li>
    <li>ocamlPackages.splay_tree</li>
    <li>ocamlPackages.splittable_random</li>
    <li>ocamlPackages.stdio</li>
    <li>ocamlPackages.textutils</li>
    <li>ocamlPackages.time_now</li>
    <li>ocamlPackages.timezone</li>
    <li>ocamlPackages.tls</li>
    <li>ocamlPackages.topological_sort</li>
    <li>ocamlPackages.torch</li>
    <li>ocamlPackages.tsort</li>
    <li>ocamlPackages.tuntap</li>
    <li>ocamlPackages.typerep</li>
    <li>ocamlPackages.uri</li>
    <li>ocamlPackages.uri-sexp</li>
    <li>ocamlPackages.variantslib</li>
    <li>ocamlPackages.vcaml</li>
    <li>ocamlPackages.vg</li>
    <li>ocamlPackages.virtual_dom</li>
    <li>ocamlPackages.webmachine</li>
    <li>ocamlPackages.x509</li>
    <li>ocamlPackages.xtmpl</li>
    <li>ocamlPackages.yaml</li>
    <li>ocamlPackages.zarith_stubs_js</li>
    <li>ocamlPackages.zstandard</li>
    <li>ocamlformat (ocamlformat_0_15_0)</li>
    <li>ocamlformat_0_11_0</li>
    <li>ocamlformat_0_12</li>
    <li>ocamlformat_0_13_0</li>
    <li>ocamlformat_0_14_0</li>
    <li>ocamlformat_0_14_1</li>
    <li>ocamlformat_0_14_2</li>
    <li>ocamlformat_0_14_3</li>
    <li>patdiff</li>
    <li>python37Packages.bap</li>
    <li>python38Packages.bap</li>
    <li>python39Packages.bap</li>
    <li>satysfi</li>
    <li>stog</li>
    <li>why3</li>
  </ul>
</details>

**Review by sternenseemann — APPROVED** [review]
No objections from my side.

**Pull request merged**
