### PR TITLE
Update my maintainership

### PR DESCRIPTION
**Pull request by kylesferrazza**
###### Motivation for this change
I would like to update my email address, and I no longer have a Canon printer for testing, so I removed myself from `canon-cups-ufr2`.

### CODE REVIEW

**Comment by kylesferrazza** [comment]
Please let me know if you'd rather me leave the maintainers list for `canon-cups-ufr2` as an empty list or keep it as being removed entirely

**Comment by IvarWithoutBones** [comment]
I think an empty list would be best, as an reminder that this package needs a new maintainer.

**Comment by kylesferrazza** [comment]
> I think an empty list would be best, as an reminder that this package needs a new maintainer.

updated

**Review by IvarWithoutBones — APPROVED** [review]
LGTM :+1:

**Pull request merged**
