### PR TITLE
treewide: switch to cargoHash

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

No need (observed) for these packages to have a vendor Cargo.lock. If they for some reason have to use a different Cargo.lock than upstream, they should copy that to the build directory as well, otherwise the build will fail. They don't, so I infer there's no reason to use Cargo.lock.

Related https://github.com/NixOS/nixpkgs/issues/327063

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
I think we could quite tractably automate this treewide: hook into `postPatch`, output a hash of the `Cargo.lock` file, and compare against the `Cargo.lock` in‐tree?

**Comment by jopejoe1** [comment]
Looking at the history of some of theme shows that they had git dependency's at some point but did not switch away from vendoring Cargo.lock files after those where no longer included.

**Comment by minijackson** [comment]
I don't mind either way for my package, but shouldn't we wait for consensus on #327063 before?

**Comment by Aleksanaa** [comment]
> I don't mind either way for my package, but shouldn't we wait for consensus on #327063 before?

I believe we've never made consensus on "regular rust packages should also use Cargo.lock" (no git dependencies, no cargo lock hacks), it is always considered as an anti-pattern

**Comment by minijackson** [comment]
Was it always? For a while I thought `cargoHash` was the anti-pattern, due to the reasons I mentioned in #327063

**Comment by Aleksanaa** [comment]
> Was it always? For a while I thought `cargoHash` was the anti-pattern, due to the reasons I mentioned in #327063

https://nixos.org/manual/nixpkgs/unstable/#rust

As the documentation shows, using `cargoHash` is the recommended way

**Comment by Mic92** [comment]
> Was it always? 

Yes. Otherwise we would have replaced all cargo hashes already. The size of the lock size was always a concern.

**Review by felschr — APPROVED** [review]
As maintainer for `nickel`, I'm good with the change. Similar to the other cases, it was only introduced due to git dependencies upstream which aren't required anymore:
https://github.com/NixOS/nixpkgs/pull/255266/files#r1327205689

**Comment by minijackson** [comment]
Welp, I might have given to much importance to some random messages on the Nixpkgs issue tracker, then. But if that's the case, I do think it's worth updating the documentation. I do see `cargoHash` being presented first, but nowhere do I see it being explicitly recommended over `lockFile` in nixpkgs. Even after re-reading it, I just see the documentation presenting two ways of doing things, each with their pros and cons.

**Comment by Mic92** [comment]
> Welp, I might have given to much importance to some random messages on the Nixpkgs issue tracker, then. But if that's the case, I do think it's worth updating the documentation. I do see `cargoHash` being presented first, but nowhere do I see it being explicitly recommended over `lockFile` in nixpkgs. Even after re-reading it, I just see the documentation presenting two ways of doing things, each with their pros and cons.

Be my guest.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
