### PR TITLE
skopeo: remove the patch by setting a variable at build time

### PR DESCRIPTION
**Pull request by nlewo**
###### Motivation for this change
Just an improvment

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nlewo** [comment]
cc @NeQuissimus @vdemeester

**Review by vdemeester — APPROVED** [review]
LGTM 👍

**Comment by nlewo** [comment]
@NeQuissimus Good to merge for us. Can you have a look?

**Comment by NeQuissimus** [comment]
LGTM, could you bump the version, then I'll try it out and merge?

**Comment by nlewo** [comment]
Tim Steinbach <notifications@github.com> writes:

> LGTM, could you bump the version, then I'll try it out and merge?

Bumped.

**Comment by NeQuissimus** [comment]
@GrahamcOfBorg build skopeo

**Pull request merged**
