### PR TITLE
[20.09]  pythonPackages.pyscreenshot: add missing dependencies 

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

Backport to release-20.09 the following PRs (apparently, this has not been done):

-  #98895
-  #98898
-  #98922

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Adding an imports check

```
diff --git a/pkgs/development/python-modules/pyscreenshot/default.nix b/pkgs/development/python-modules/pyscreenshot/default.nix
index 7967caf6178..dc92239fbbb 100644
--- a/pkgs/development/python-modules/pyscreenshot/default.nix
+++ b/pkgs/development/python-modules/pyscreenshot/default.nix
@@ -28,6 +28,8 @@ buildPythonPackage rec {
   # recursive dependency on pyvirtualdisplay
   doCheck = false;
 
+  pythonImportsCheck = [ "pyscreenshot" ];
+
   meta = with lib; {
     description = "python screenshot";
     homepage = "https://github.com/ponty/pyscreenshot";
```

reveals a missing pillow dependency:

```
Check whether the following modules can be imported: pyscreenshot
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/zwbrw49cj30zhkfybn656jli14fznwp8-python3.8-pyscreenshot-2.2/lib/python3.8/site-packages/pyscreenshot/__init__.py", line 4, in <module>
    from pyscreenshot.childproc import childprocess_backend_version
  File "/nix/store/zwbrw49cj30zhkfybn656jli14fznwp8-python3.8-pyscreenshot-2.2/lib/python3.8/site-packages/pyscreenshot/childproc.py", line 5, in <module>
    from pyscreenshot.imcodec import codec
  File "/nix/store/zwbrw49cj30zhkfybn656jli14fznwp8-python3.8-pyscreenshot-2.2/lib/python3.8/site-packages/pyscreenshot/imcodec.py", line 3, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
builder for '/nix/store/n1ryi6j4mjm17ddjrxs62qfic7z2wnmc-python3.8-pyscreenshot-2.2.drv' failed with exit code 1
```

**Comment by lsix** [comment]
Yes, you are right. I’ll add a PR ASAP to `master` and backport it here once accepted. Meanwhile, I mark this pr as draft.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 99244` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python27Packages.entrypoint2</li>
    <li>python27Packages.pyscreenshot</li>
    <li>python37Packages.entrypoint2</li>
    <li>python37Packages.mss</li>
    <li>python37Packages.pyscreenshot</li>
    <li>python38Packages.entrypoint2</li>
    <li>python38Packages.mss</li>
    <li>python38Packages.pyscreenshot</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Comment by jonringer** [comment]
> Yes, you are right. I’ll add a PR ASAP to `master` and backport it here once accepted. Meanwhile, I mark this pr as draft.

Upstream should also be notified that they aren't declaring a necessary dependency

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 99244 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>8 packages built:</summary>  <ul>    <li>python27Packages.entrypoint2</li>    <li>python27Packages.pyscreenshot</li>    <li>python37Packages.entrypoint2</li>    <li>python37Packages.mss</li>    <li>python37Packages.pyscreenshot</li>    <li>python38Packages.entrypoint2</li>    <li>python38Packages.mss</li>    <li>python38Packages.pyscreenshot</li>  </ul></details>

**Pull request merged**
