### PR TITLE
file-rename: removed redundant packaging

### PR DESCRIPTION
**Pull request by mkgvt**
###### Motivation for this change
The perl implementation of rename (file-rename) was packaged twice. Removing this one eliminates the redundancy.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
The file removed is still referenced elsewhere, resulting in eval failure.

**Comment by mkgvt** [comment]
> The file removed is still referenced elsewhere, resulting in eval failure.
Thanks for giving me a hint where to look. I am a novice at git (and NixOS for that matter). Pointers on how to address this?

**Comment by mkgvt** [comment]
>
>
> I see the problem. I forgot to remove "rename = callPackage
../tools/misc/rename { };" from pkgs/top-level/all-packages.nix. I can do
that. What I don't know how to do is to amend the PR in github with that
change in it. Pointers to documentation?

**Comment by jtojnar** [comment]
You can do `git commit --amend` when you want to add the changes to the last commit. Or you can create a separate commit and the use interactive rebase to combine (fixup) commits together. Then you can force push to your branch to overwrite this.

**Comment by joachifm** [comment]
Hm, are these packages actually the same? Seems to me there are different upstreams, different authors, and different licenses. cc @peterhoeg as the maintainer of the other package.

**Comment by peterhoeg** [comment]
Those are 2 different pieces of software as pointed out by @fridh.

**Pull request closed without merging**
