### PR TITLE
nixos/monero: add dataDir option

### PR DESCRIPTION
**Pull request by j0hax**
###### Motivation for this change

A program with ever-increasing data sizes (blockchain) should have a configurable `dataDir`.

I also fixed a small typo 😃 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Doesn't this service complain that neither [`isNormalUser` nor `isSystemUser`](https://github.com/NixOS/nixpkgs/pull/115332) is set?

**Comment by j0hax** [comment]
@aanderse I would suppose so. I did however build my entire system flake from this branch and it works just fine.

Replacing

```diff
- uid  = config.ids.uids.monero;
+ isSystemUser = true;
```

before a rebuild also seems to work fine.

Is there anything that should be done regarding the GID and UID in `/nixos/modules/misc/ids.nix`?

**Comment by aanderse** [comment]
The convention seems to be to comment out that line, which makes sense, so the `uid` isn't reused, which could cause problems.

Additionally, I believe the `gid` can be removed and commented out as well.

**Comment by aanderse** [comment]
Thanks for your contribution @j0hax :tada:

**Pull request merged**
