### PR TITLE
blanket: 0.6.0 -> 0.7.0

### LINKED ISSUE #308146: Update request: blanket 0.6.0 → 0.7.0
- Package name: blanket
- Latest released version: 0.7.0

- Current version on the unstable channel: 0.6.0
- Current version on the stable/release channel: 0.6.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jsierles onny

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by afh**
## Description of changes

This PR supercedes #308159 and targets `staging-next`, because the changes require a newer `libadwaita`, which is only available with Gnome 46, which in Nix is currently only available on `staging-next`.
Update to 0.7.0 and modernize package as proposed by `nix run github:NixOS/nixfmt`.

Closes #308146

## Things done

Moderni

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
@ofborg build blanket

**Review by JohnRTitor — APPROVED** [review]
LGTM, Ofborg was able to build it successfully. [(1)](https://github.com/NixOS/nixpkgs/pull/308444/checks?check_run_id=24498269700)  [(2)](https://github.com/NixOS/nixpkgs/pull/308444/checks?check_run_id=24498249750)

**Comment by Aleksanaa** [comment]
Hey, could you avoid double wrapping first? Although I've done it in https://github.com/NixOS/nixpkgs/pull/303848 but I guess I won't work on that PR in a week

**Comment by afh** [comment]
Unfortunately this PR was merged before I got a chance to reply to your comment, @Aleksanaa. I'm uncertain whether I fully understand what you mean by "double wrapping", can you provide additional context, please?

**Comment by Aleksanaa** [comment]
Just see my above PR. The nixpkgs manual also mentioned this.

**Comment by afh** [comment]
ℹ️ Double-wrapping was addressed with https://github.com/NixOS/nixpkgs/commit/63c883728f8a2238bfc5e7fab5af0a917a21d3e1

**Pull request merged**
