### PR TITLE
amdgpu_top: init at 0.1.7

### LINKED ISSUE #225331: Package request: amdgpu_top - rusty amd gpu util monitor
**Project description**

>amdgpu_top is tool that display AMD GPU utilization, like [umr](https://gitlab.freedesktop.org/tomstdenis/umr/) or [clbr/radeontop](https://github.com/clbr/radeontop).
The tool displays information gathered from performance counters (GRBM, GRBM2, CP_STAT), sensors, fdinfo, and AMDGPU driver.

Presumably it wouldn't depend on `cudatoolkit` as `nvtop` does, and it's written in that one language. :lobster: 

**Metadata**

* homepage URL: https://github.com/Umio-Yasuno/amdgpu_top
* source URL: https://github.com/Umio-Yasuno/amdgpu_top
* license: **mit**
* platforms:  **linux**

### PR DESCRIPTION
**Pull request by geri1701**
###### Description of changes

Close  #225331

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Tungsten842** [comment]
I am getting this:
```
amdgpu_device_initialize: DRM version is 1.6.0 but this driver is only compatible with 3.x.x.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: -9', src/main.rs:46:49
stack backtrace:
   0:     0x5565a29f671c - <unknown>
   1:     0x5565a2891c2e - <unknown>
   2:     0x5565a2a04e44 - <unknown>
   3:     0x5565a29f64ff - <unknown>
   4:     0x5565a2a0eedf - <unknown>
   5:     0x5565a2a0fa64 - <unknown>
   6:     0x5565a29f6b74 - <unknown>
   7:     0x5565a29f6adc - <unknown>
   8:     0x5565a2a0f2e1 - <unknown>
   9:     0x5565a28179e2 - <unknown>
  10:     0x5565a2817dd2 - <unknown>
  11:     0x5565a286b026 - <unknown>
  12:     0x5565a286baa8 - <unknown>
  13:     0x5565a28363b3 - <unknown>
  14:     0x5565a287809b - <unknown>
  15:     0x7f2eed38face - __libc_start_call_main
  16:     0x7f2eed38fb89 - __libc_start_main@@GLIBC_2.34
  17:     0x5565a2828d05 - <unknown>
  18:                0x0 - <unknown>
```

**Comment by geri1701** [comment]
> Also version v0.1.7-stable has just been released

Thank you very much, an update of the PR is on the way.

As for your error, I can't reproduce it. The package works fine for me on two different systems.

**Comment by colemickens** [comment]
It probably needs the usual touches for Wayland/libX11.

I'm also getting the crash/backtrace though, and opened: https://github.com/Umio-Yasuno/amdgpu_top/issues/11

**Comment by geri1701** [comment]
> TUI mode works great. GUI mode does not seem to be working:

Thank you, I'll take care of the GUI now.

**Comment by geri1701** [comment]
> It probably needs the usual touches for Wayland/libX11.
> 
> I'm also getting the crash/backtrace though, and opened: [Umio-Yasuno/amdgpu_top#11](https://github.com/Umio-Yasuno/amdgpu_top/issues/11)



> It probably needs the usual touches for Wayland/libX11.
> 
> I'm also getting the crash/backtrace though, and opened: [Umio-Yasuno/amdgpu_top#11](https://github.com/Umio-Yasuno/amdgpu_top/issues/11)

Many thanks!

**Pull request merged**
