### PR TITLE
qemu: 7.2.0 -> 8.0.0

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Now that shaderinclude is Python, I don't think we need Perl any more.

- [x] utimensat Darwin fallback patch is commented out because it needs a rebase.  @willcohen, maybe you're able to take a look at this?
- [x] volunteer needed to look into what's going on with the tests on aarch64-darwin

[ETA: 2023-04-19](https://lore.kernel.org/qemu-devel/168142845428.12506.16330418133795838547@amd.com/)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eliandoran** [comment]
Hi @alyssais ,

I'm trying to build this PR on x86_64-linux, but meson fails with a glib dependency check:

```
Did not find CMake 'cmake'
Found CMake: NO
Build-time dependency glib-2.0 found: NO (tried pkgconfig)

../target/hexagon/meson.build:191:4: ERROR: Dependency "glib-2.0" not found, tried pkgconfig
```

Have you encountered this issue on your side? I tried adding `glib` directly to `nativeBuildInputs`, but the issue still occurs.

**Comment by alyssais** [comment]
Right, yes, we need a build-build pkg-config now as well.  Fixed.

**Comment by eliandoran** [comment]
@alyssais , the build now works just fine. Thanks!

**Comment by alyssais** [comment]
The aarch64-linux test failure is nothing to worry about, as it's been failing for a few versions now.  I think the aarch64-darwin test failures are new though, so would be good if somebody could look into that.

**Comment by risicle** [comment]
Failure on macos 10.15:

```
FAILED: libcommon.fa.p/hw_9pfs_9p.c.o 
clang -m64 -mcx16 -Ilibcommon.fa.p -I../dtc/libfdt -Iui -I../ui -I/nix/store/xqj6x6ga84m1x7s1996m8sqimqxc1zkd-pixman-0.42.2/include/pixman-1 -I/nix/store/gq5p8ak25gbqga000837q7lsi4jra32g-libpng-apng-1.6.39-dev/include/libpng16 -I/nix/store/i7pjrdh8z80f0hkxcd31wsc41l6frfyq-spice-protocol-0.14.4/include/spice-1 -I/nix/store/jqyyjv7
clang-11: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
../hw/9pfs/9p.c:1698:36: error: use of undeclared identifier 'UTIME_NOW'
                times[0].tv_nsec = UTIME_NOW;
                                   ^

```

**Comment by alyssais** [comment]
> Failure on macos 10.15:

I think that's due to the patch I commented out, as mentioned in the PR body.

**Comment by willcohen** [comment]
@alyssais Given that 10.13 is now 5+ years old and that SDK bump has ended up being a lot harder than anyone anticipated, I'm wondering if maybe it's time for QEMU to adopt the impure the 11.0 sdk. The list of things that this derivation is having to patch out seems like it's growing. Happy to rebase but just wanted to bring this up as a suggestion first.

**Comment by willcohen** [comment]
@alyssais I no longer have an Intel mac to check this on, but this rebases the single utimensat patch file from v7.2.0 to v8.0.0-rc0. If this cascades to other errors because of other mismatching patch files, happy to readjust as needed!

```
From 2ec149ea3f0046fa83e3be74aca192649a60be47 Mon Sep 17 00:00:00 2001
From: Keno Fischer <keno@juliacomputing.com>
Date: Sat, 16 Jun 2018 20:56:54 -0400
Subject: [PATCH] 9p: darwin: Provide fallback impl for utimensat

This function is new in Mac OS 10.13. Provide a fallback implementation
when building against older SDKs. The complication in the definition comes
having to separately handle the used SDK version and the target OS version.

- If the SDK version is too low (__MAC_10_13 not defined), utimensat is not
  defined in the header, so we must not try to use it (doing so would error).
- Otherwise, if the targetted OS version is at least 10.13, we know this
  function is available, so we can unconditionally call it.
- Lastly, we check for the availability of the __builtin_available macro to
  potentially insert a dynamic check for this OS version. However, __builtin_available
  is only available with sufficiently recent versions of clang and while all
  Apple clang versions that ship with Xcode versions that support the 10.13
  SDK support with builtin, we want to allow building with compilers other
  than Apple clang that may not support this builtin.

Signed-off-by: Keno Fischer <keno@juliacomputing.com>
Signed-off-by: Michael Roitzsch <reactorcontrol@icloud.com>
Signed-off-by: Will Cohen <wwcohen@gmail.com>
---
 hw/9pfs/9p-local.c       |  2 +-
 hw/9pfs/9p-util-darwin.c | 96 ++++++++++++++++++++++++++++++++++++++++
 hw/9pfs/9p-util-linux.c  |  6 +++
 hw/9pfs/9p-util.h        |  8 ++++
 4 files changed, 111 insertions(+), 1 deletion(-)

diff --git a/hw/9pfs/9p-local.c b/hw/9pfs/9p-local.c
index 9d07620235..9c77a431d5 100644
--- a/hw/9pfs/9p-local.c
+++ b/hw/9pfs/9p-local.c
@@ -1081,7 +1081,7 @@ static int local_utimensat(FsContext *s, V9fsPath *fs_path,
         goto out;
     }
 
-    ret = qemu_utimensat(dirfd, name, buf, AT_SYMLINK_NOFOLLOW);
+    ret = utimensat_nofollow(dirfd, name, buf);
     close_preserve_errno(dirfd);
 out:
     g_free(dirpath);
diff --git a/hw/9pfs/9p-util-darwin.c b/hw/9pfs/9p-util-darwin.c
index 95146e7354..74ab2a7f99 100644
--- a/hw/9pfs/9p-util-darwin.c
+++ b/hw/9pfs/9p-util-darwin.c
@@ -145,3 +145,99 @@ int qemu_mknodat(int dirfd, const char *filename, mode_t mode, dev_t dev)
 }
 
 #endif
+
+#ifndef __has_builtin
+#define __has_builtin(x) 0
+#endif
+
+static int update_times_from_stat(int fd, struct timespec times[2],
+                                  int update0, int update1)
+{
+    struct stat buf;
+    int ret = fstat(fd, &buf);
+    if (ret == -1) {
+        return ret;
+    }
+    if (update0) {
+        times[0] = buf.st_atimespec;
+    }
+    if (update1) {
+        times[1] = buf.st_mtimespec;
+    }
+    return 0;
+}
+
+int utimensat_nofollow(int dirfd, const char *filename,
+                       const struct timespec times_in[2])
+{
+    int ret, fd;
+    int special0, special1;
+    struct timeval futimes_buf[2];
+    struct timespec times[2];
+    memcpy(times, times_in, 2 * sizeof(struct timespec));
+
+/* Check whether we have an SDK version that defines utimensat */
+#if defined(__MAC_10_13)
+# if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_13
+#  define UTIMENSAT_AVAILABLE 1
+# elif __has_builtin(__builtin_available)
+#  define UTIMENSAT_AVAILABLE __builtin_available(macos 10.13, *)
+# else
+#  define UTIMENSAT_AVAILABLE 0
+# endif
+    if (UTIMENSAT_AVAILABLE) {
+        return utimensat(dirfd, filename, times, AT_SYMLINK_NOFOLLOW);
+    }
+#endif
+
+    /* utimensat not available. Use futimes. */
+    fd = openat_file(dirfd, filename, O_PATH_9P_UTIL | O_NOFOLLOW, 0);
+    if (fd == -1) {
+        return -1;
+    }
+
+    special0 = times[0].tv_nsec == UTIME_OMIT;
+    special1 = times[1].tv_nsec == UTIME_OMIT;
+    if (special0 || special1) {
+        /* If both are set, nothing to do */
+        if (special0 && special1) {
+            ret = 0;
+            goto done;
+        }
+
+        ret = update_times_from_stat(fd, times, special0, special1);
+        if (ret < 0) {
+            goto done;
+        }
+    }
+
+    special0 = times[0].tv_nsec == UTIME_NOW;
+    special1 = times[1].tv_nsec == UTIME_NOW;
+    if (special0 || special1) {
+        ret = futimes(fd, NULL);
+        if (ret < 0) {
+            goto done;
+        }
+
+        /* If both are set, we are done */
+        if (special0 && special1) {
+            ret = 0;
+            goto done;
+        }
+
+        ret = update_times_from_stat(fd, times, special0, special1);
+        if (ret < 0) {
+            goto done;
+        }
+    }
+
+    futimes_buf[0].tv_sec = times[0].tv_sec;
+    futimes_buf[0].tv_usec = times[0].tv_nsec / 1000;
+    futimes_buf[1].tv_sec = times[1].tv_sec;
+    futimes_buf[1].tv_usec = times[1].tv_nsec / 1000;
+    ret = futimes(fd, futimes_buf);
+
+done:
+    close_preserve_errno(fd);
+    return ret;
+}
diff --git a/hw/9pfs/9p-util-linux.c b/hw/9pfs/9p-util-linux.c
index db451b0784..320697f347 100644
--- a/hw/9pfs/9p-util-linux.c
+++ b/hw/9pfs/9p-util-linux.c
@@ -68,3 +68,9 @@ int qemu_mknodat(int dirfd, const char *filename, mode_t mode, dev_t dev)
 {
     return mknodat(dirfd, filename, mode, dev);
 }
+
+int utimensat_nofollow(int dirfd, const char *filename,
+                       const struct timespec times[2])
+{
+    return utimensat(dirfd, filename, times, AT_SYMLINK_NOFOLLOW);
+}
diff --git a/hw/9pfs/9p-util.h b/hw/9pfs/9p-util.h
index c314cf381d..12d57f3398 100644
--- a/hw/9pfs/9p-util.h
+++ b/hw/9pfs/9p-util.h
@@ -101,6 +101,12 @@ static inline int errno_to_dotl(int err) {
 #define qemu_utimensat  utimensat
 #define qemu_unlinkat   unlinkat
 
+/* Compatibility with old SDK Versions for Darwin */
+#if defined(CONFIG_DARWIN) && !defined(UTIME_NOW)
+#define UTIME_NOW -1
+#define UTIME_OMIT -2
+#endif
+
 static inline void close_preserve_errno(int fd)
 {
     int serrno = errno;
@@ -163,6 +169,8 @@ ssize_t flistxattrat_nofollow(int dirfd, const char *filename,
                               char *list, size_t size);
 ssize_t fremovexattrat_nofollow(int dirfd, const char *filename,
                                 const char *name);
+int utimensat_nofollow(int dirfd, const char *filename,
+                       const struct timespec times[2]);
 
 /*
  * Darwin has d_seekoff, which appears to function similarly to d_off.
-- 
2.39.2
```

**Comment by willcohen** [comment]
@alyssais additionally, re the darwin-aarch64 test failure, looks like its timing out at one hour. the test it's timing out on, number 398/648, is also one of the test that times out at 1500s on its own -- i suspect that unless there's some way to remove these long timeout tests, aarch64's going to always fail at 1 hour going forward.

**Comment by willcohen** [comment]
From running locally:

```
256/648 qemu:qtest+qtest-arm / qtest-arm/qmp-test                                          OK                 0.81s   4 subtests passedassed

Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.

257/648 qemu:qtest+qtest-arm / qtest-arm/qmp-cmd-test                                      OK                12.86s   65 subtests passedssedd

Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.

258/648 qemu:qtest+qtest-arm / qtest-arm/npcm7xx_watchdog_timer-test                       ERROR             48.08s   killed by signal 6 SIGABRT
>>> G_TEST_DBUS_DAEMON=/private/tmp/nix-build-qemu-8.0.0-rc0.drv-0/qemu-8.0.0-rc0/tests/dbus-vmstate-daemon.sh QTEST_QEMU_BINARY=./qemu-system-arm QTEST_QEMU_IMG=./qemu-img MALLOC_PERTURB_=106 /private/tmp/nix-build-qemu-8.0.0-rc0.drv-0/qemu-8.0.0-rc0/build/tests/qtest/npcm7xx_watchdog_timer-test --tap -k
 ✀  
stderr:
../tests/qtest/libqtest.c:193: kill_qemu() detected QEMU death from signal 9 (Killed: 9)

(test program exited with status code -6)

TAP parsing error: Too few tests run (expected 15, got 13)


Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.


259/648 qemu:qtest+qtest-arm / qtest-arm/netdev-socket                                     OK                 5.52s   9 subtests passedassedd

Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.

260/648 qemu:qtest+qtest-avr / qtest-avr/cdrom-test                                        SKIP               0.02s7500s   9 subtests passed

...


Summary of Failures:

258/648 qemu:qtest+qtest-arm / qtest-arm/npcm7xx_watchdog_timer-test              ERROR             48.08s   killed by signal 6 SIGABRT
344/648 qemu:qtest+qtest-aarch64 / qtest-aarch64/readconfig-test                  TIMEOUT         1502.51s   killed by signal 15 SIGTERM
345/648 qemu:qtest+qtest-alpha / qtest-alpha/readconfig-test                      TIMEOUT         1502.50s   killed by signal 15 SIGTERM
364/648 qemu:qtest+qtest-arm / qtest-arm/readconfig-test                          TIMEOUT         1502.51s   killed by signal 15 SIGTERM
374/648 qemu:qtest+qtest-avr / qtest-avr/readconfig-test                          TIMEOUT         1500.00s   killed by signal 15 SIGTERM
386/648 qemu:qtest+qtest-cris / qtest-cris/readconfig-test                        TIMEOUT         1500.01s   killed by signal 15 SIGTERM
398/648 qemu:qtest+qtest-hppa / qtest-hppa/readconfig-test                        TIMEOUT         1500.02s   killed by signal 15 SIGTERM
410/648 qemu:qtest+qtest-i386 / qtest-i386/readconfig-test                        TIMEOUT         1500.02s   killed by signal 15 SIGTERM
422/648 qemu:qtest+qtest-loongarch64 / qtest-loongarch64/readconfig-test          TIMEOUT         1500.02s   killed by signal 15 SIGTERM
429/648 qemu:qtest+qtest-m68k / qtest-m68k/readconfig-test                        TIMEOUT         1500.00s   killed by signal 15 SIGTERM
436/648 qemu:qtest+qtest-microblaze / qtest-microblaze/readconfig-test            TIMEOUT         1500.00s   killed by signal 15 SIGTERM
449/648 qemu:qtest+qtest-microblazeel / qtest-microblazeel/readconfig-test        TIMEOUT         1500.00s   killed by signal 15 SIGTERM
470/648 qemu:qtest+qtest-mips / qtest-mips/readconfig-test                        TIMEOUT         1500.00s   killed by signal 15 SIGTERM
477/648 qemu:qtest+qtest-mips64 / qtest-mips64/readconfig-test                    TIMEOUT         1500.00s   killed by signal 15 SIGTERM
485/648 qemu:qtest+qtest-mips64el / qtest-mips64el/readconfig-test                TIMEOUT         1500.00s   killed by signal 15 SIGTERM
492/648 qemu:qtest+qtest-mipsel / qtest-mipsel/readconfig-test                    TIMEOUT         1500.00s   killed by signal 15 SIGTERM
505/648 qemu:qtest+qtest-nios2 / qtest-nios2/readconfig-test                      TIMEOUT         1500.01s   killed by signal 15 SIGTERM
514/648 qemu:qtest+qtest-or1k / qtest-or1k/readconfig-test                        TIMEOUT         1500.04s   killed by signal 15 SIGTERM
522/648 qemu:qtest+qtest-ppc / qtest-ppc/readconfig-test                          TIMEOUT         1500.04s   killed by signal 15 SIGTERM
533/648 qemu:qtest+qtest-ppc64 / qtest-ppc64/readconfig-test                      TIMEOUT         1500.03s   killed by signal 15 SIGTERM
544/648 qemu:qtest+qtest-riscv32 / qtest-riscv32/readconfig-test                  TIMEOUT         1500.03s   killed by signal 15 SIGTERM
551/648 qemu:qtest+qtest-riscv64 / qtest-riscv64/readconfig-test                  TIMEOUT         1500.04s   killed by signal 15 SIGTERM
605/648 qemu:qtest+qtest-rx / qtest-rx/readconfig-test                            TIMEOUT         1500.04s   killed by signal 15 SIGTERM
612/648 qemu:qtest+qtest-s390x / qtest-s390x/readconfig-test                      TIMEOUT         1500.04s   killed by signal 15 SIGTERM
619/648 qemu:qtest+qtest-sh4 / qtest-sh4/readconfig-test                          TIMEOUT         1500.04s   killed by signal 15 SIGTERM
621/648 qemu:qtest+qtest-sh4eb / qtest-sh4eb/readconfig-test                      TIMEOUT         1500.00s   killed by signal 15 SIGTERM
622/648 qemu:qtest+qtest-sparc / qtest-sparc/readconfig-test                      TIMEOUT         1500.00s   killed by signal 15 SIGTERM
623/648 qemu:qtest+qtest-sparc64 / qtest-sparc64/readconfig-test                  TIMEOUT         1500.00s   killed by signal 15 SIGTERM
624/648 qemu:qtest+qtest-tricore / qtest-tricore/readconfig-test                  TIMEOUT         1500.00s   killed by signal 15 SIGTERM
625/648 qemu:qtest+qtest-x86_64 / qtest-x86_64/readconfig-test                    TIMEOUT         1500.00s   killed by signal 15 SIGTERM
626/648 qemu:qtest+qtest-xtensa / qtest-xtensa/readconfig-test                    TIMEOUT         1500.00s   killed by signal 15 SIGTERM
627/648 qemu:qtest+qtest-xtensaeb / qtest-xtensaeb/readconfig-test                TIMEOUT         1500.00s   killed by signal 15 SIGTERM

Ok:                 550 
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            66  
Timeout:            31  

Full log written to /private/tmp/nix-build-qemu-8.0.0-rc0.drv-0/qemu-8.0.0-rc0/build/meson-logs/testlog.txt
FAILED: meson-internal__test 
/nix/store/1vbh9iwp07ax3y5arpqf7llx12bwpv0h-meson-1.0.0/bin/meson test --no-rebuild --no-stdsplit --print-errorlogs
ninja: build stopped: subcommand failed.
```

**Review by willcohen — APPROVED** [review]

**Comment by alyssais** [comment]
Does qtest-arm/npcm7xx_watchdog_timer-test also fail on 7.2.0 on aarch64-darwin?

**Comment by willcohen** [comment]
Looks like it passes on 7.2.0:

```
257/614 qemu:qtest+qtest-arm / qtest-arm/npcm7xx_watchdog_timer-test                       OK                 7.22s   15 subtests passedssed```

**Comment by alyssais** [comment]
> Looks like it passes on 7.2.0:
> 
> ```
> 257/614 qemu:qtest+qtest-arm / qtest-arm/npcm7xx_watchdog_timer-test                       OK                 7.22s   15 subtests passedssed```
> ```

Okay, that sounds like something we should figure out before the release then, and report upstream if it's not our problem.  Do you have the time to do a bisect?

**Comment by alyssais** [comment]
> @alyssais on the other hand, on aarch64-darwin we also had 1 test failure with 7.2.0, which now appears fixed on 8.0.0, so while the specific test changed, we're trading one SIGABRT for another, so the overall level of failure isn't actually increasing...

Yeah, but since we're still in early RC phase, there's a good chance we could get a report upstream and get to **zero** test failures on aarch64-darwin.

**Comment by willcohen** [comment]
I'll give it a shot!

**Comment by risicle** [comment]
As far as SDK-switching goes, I think we've made a basic effort in the past and it proved to be more complicated than expected. AFAIU code built under the two SDKs doesn't always play together nicely. There will come a point when we have to switch all of x86_64 darwin to the new SDK though.

**Comment by alyssais** [comment]
> @alyssais have you ever done bisecting using this derivation? Subbing in the source archive with a `fetchFromGitHub` fails because QEMU gets mad if you try to do the official build process from a git repo.

Oh right, yeah.  What I do is run `bash scripts/archive-source.sh /tmp/qemu.tar` in my QEMU checkout in between each bisect iteration, and build the package with this diff:

```diff
diff --git i/pkgs/applications/virtualization/qemu/default.nix w/pkgs/applications/virtualization/qemu/default.nix
index c20a2c53d60..797b8da2385 100644
--- i/pkgs/applications/virtualization/qemu/default.nix
+++ w/pkgs/applications/virtualization/qemu/default.nix
@@ -44,10 +44,8 @@ stdenv.mkDerivation rec {
     + lib.optionalString nixosTestRunner "-for-vm-tests";
   version = "7.2.0";
 
-  src = fetchurl {
-    url = "https://download.qemu.org/qemu-${version}.tar.xz";
-    sha256 = "sha256-W0nOJod0Ta1JSukKiYxSIEo0BuhNBySCoeG+hU7rIVc=";
-  };
+  src = /tmp/qemu.tar;
+  sourceRoot = ".";
 
   depsBuildBuild = [ buildPackages.stdenv.cc ];
 
```

**Comment by alyssais** [comment]
Okay, interesting.  So it's just readconfig-test, for different architectures.

**Comment by alyssais** [comment]
@Ofborg test simple cagebreak cloud-init os-prober sway virtualbox

**Comment by alyssais** [comment]
Assuming nobody raises any objections and I don't notice any last minute regressions, I plan to merge this when 8.0.0 final is released (probably today, maybe next week).

**Comment by alyssais** [comment]
@ofborg test simple cage cagebreak cloud-init os-prober sway virtualbox

**Comment by alyssais** [comment]
@ofborg test simple cage cagebreak cloud-init os-prober sway virtualbox

**Pull request merged**
