### PR TITLE
Adding mwlib

### PR DESCRIPTION
**Pull request by ip1981**
Only python modules for a while.

### CODE REVIEW

**Comment by pSub** [comment]
Does this build locally for you. Travis error seems legit for me:

```
File "setup.py", line 11, in <module>
execfile('mwlib/_extversion.py')  # adds 'version' to local namespace
NameError: name 'execfile' is not defined
```

**Comment by vbgl** [comment]
Apparently some libraries require python 2: mwlib-ext, pyparsing1, qserve, sqlite3dbm. You may want to set `disabled = isPy3k` in their derivations.

**Comment by ip1981** [comment]
`$ nix-env  -f ~/nixpkgs -i python2.7-mwlib` works fine. Python 3 is not supported.

**Comment by ip1981** [comment]
Thank @vbgl, updated.

**Pull request merged**
