### PR TITLE
sway: generalize wrapper

### PR DESCRIPTION
**Pull request by raboof**
## Description of changes

Generalize the sway wrapper so it can be used by sway derivatives, like volare.

The idea is that with this change, we could package volare as a flake outside of nixpkgs, but avoid duplicating a lot of the wrapper logic. This is much more complex if you try to do it just with overrides.

Keeping as draft for now since I haven't actually fully tested it yet (currently testing it on a nixpkgs branch, moving to a flake is still on my list)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raboof** [comment]
Tested as described on https://codeberg.org/raboof/volare#installation-on-nixos - seems to work nicely.

**Comment by teto** [comment]
while this looks ok to me, I prefer to let a sway maintainer have the final decision.

**Comment by raboof** [comment]
> while this looks ok to me, I prefer to let a sway maintainer have the final decision.

While I agree with this sentiment in general, the sway maintainers seem pretty inactive (didn't participate in #259066/#263206 for example). If they don't show up in a week or so, I would like to propose to merge this anyway, as it doesn't seem very controversial?

**Comment by raboof** [comment]
wait, I should fix that test failure first...

```
Couldn't find provided session name, sway-unwrapped-1.8.1.desktop, in session package sway-unwrapped-1.8.1-1.8.1:
  /nix/store/v5775a2wqgmfd88hjz165j8yg6lds6yk-sway-unwrapped-1.8.1-1.8.1
error: builder for '/nix/store/dgyjzv1s38lmhdl2k06a11la4ddga1yx-desktops.drv' failed with exit code 1;
       last 2 log lines:
       > Couldn't find provided session name, sway-unwrapped-1.8.1.desktop, in session package sway-unwrapped-1.8.1-1.8.1:
       >   /nix/store/v5775a2wqgmfd88hjz165j8yg6lds6yk-sway-unwrapped-1.8.1-1.8.1
       For full logs, run 'nix log /nix/store/dgyjzv1s38lmhdl2k06a11la4ddga1yx-desktops.drv'.
```

**Comment by raboof** [comment]
Should be fixed now - planning to merge this when ofborg is happy, please comment here if you have any objections

**Pull request merged**
