### PR TITLE
qmk_hid init at 0.1.5

### PR DESCRIPTION
**Pull request by Janik-Haag**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Don't forget the `:` at the commit message:

`qmk_hid: init at 0.1.5`

**Comment by JohnAZoidberg** [comment]
Oh cool :D @Janik-Haag are you actually using it already?

**Comment by Janik-Haag** [comment]
> Oh cool :D @Janik-Haag are you actually using it already?

I just played around with it a bit and packaging was easy so :shrug: 
But the package only contains the cli and not the gui since python packaging in nix is meh when you don't have a "actual python package" with like setuptools or pyproject.toml or something. Looking at the package now I should probably also add udev rules :see_no_evil: 

Nice to see the author of the package comment on my PR :D
If you want further disscusion this is probably not the right place and we should move to matrix or the fediverse :)

**Comment by JohnAZoidberg** [comment]
> Looking at the package now I should probably also add udev rules

udev rules are already supported by `hardware.keyboard.qmk.enable = true`.

> But the package only contains the cli and not the gui since python packaging in nix is meh when you don't have a "actual python package" with like setuptools or pyproject.toml or something.

Oh I should do that. Even though the GUI is more of an afterthought. The python script was just a quick prototype and also serves as a reference for non-rustaceans. 

>  If you want further disscusion this is probably not the right place and we should move to matrix or the fediverse :)
Sure! You can reach me at @johnazoidberg:matrix.org

**Pull request merged**
