### PR TITLE
onlyoffice-documentserver: init at 7.1.1-23; nixos/onlyoffice: init 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Tried to run this on my server and it looks already promising.
```
services.onlyoffice = {
  enable = true;
  port = 8000;
};
```
Is it possible to give the `port` option an default value for services like `spellchecker` and `documentserver` as specified in this table https://helpcenter.onlyoffice.com/installation/docs-community-open-ports.aspx
Just having `services.onlyoffice.enable = true;` and thats it would be fun :D  

When trying to use the module like above I get an error for Nginx because the port 80 is already used by Caddy on my server. Is Nginx required if I just want to have `documentserver` and `spellchecker` module? If Nginx is only required for the example server, I would make it optional and disabled by default.

`onlyoffice-docservice` is failing because it is unable to establish a `postgresql`  connection
```
sql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
```
Could the postgresql backend created automatically on localhost unless specified otherwise?

**Comment by onny** [comment]
Adding an entry to the release notes would be cool too :)

**Comment by SuperSandro2000** [comment]
> Is Nginx required if I just want to have `documentserver` and `spellchecker` module?

We would need to port (almost) all of nginx location rules over to Caddy. I currently don't have the time to look into this so for now you would need to use nginx.

> If Nginx is only required for the example server, I would make it optional and disabled by default.

I think the example server is disabled by default and also not fully functional yet but it is also only required for testing purposes and not for the nextcloud integration which is my main target. I am also not even sure if the spellchecker module is working or included in that package.

> Could the postgresql backend created automatically on localhost unless specified otherwise?

That should already happen. I've added a requires and after to make sure onlyoffice is started after postgresql.

> Adding an entry to the release notes would be cool too :)

I don't really want to because fixing bugs will probably be a pain.

**Comment by onny** [comment]
When trying to setup my OnlyOffice on Nextcloud, `nginx` on the server side gives me following error:
```
Jul 18 16:25:43 piproxy nginx[596334]: 2022/07/18 16:25:43 [error] 596334#596334: *25 open() "/var/lib/onlyoffice/documentserver/App_Data/cache/files/conv_check_252474851_docx/output.docx" failed (13: Permission denied), client: 127.0.0.1, server: office.example.org, request: "GET /cache/files/conv_check_252474851_docx/output.docx/check_252474851.docx?md5=UPRNt9WByKZVFdaqMXfpqw&expires=1658162444&filename=check_252474851.docx HTTP/1.1", host: "office.example.org"
```

**Comment by onny** [comment]
> Edit: Okay probably this is not necessary because I can change the listening port for Nginx directly via
> 
> ```
> nginx.virtualHosts."office.example.org".listen = [{
>   addr = "0.0.0.0";
>   port = 8080;
> }];
> ```

Oh this is though ... Nginx will now run Onlyoffice on http://office.example.org:8080. Now I'm using Caddy as a reverse proxy for the domain https://office.example.org. Unfortunately Nginx will always redirect to http and port 8080. Not sure how to fix this :(

**Comment by onny** [comment]
I'm now running your onlyoffice service in an isolated container with its own network and this works great ;)

I have a Caddy web server which does the SSL certificate stuff for me. It has the domain `office.example.org` which is a reverse proxy to the internal `onlyoffice` container (port 80, non-SSL).

Unfortunately the Nginx web server of the Onlyoffice module seems to redirect to `http://` so I'm not able to use it in Nextcloud:

image

**Comment by onny** [comment]
If I drop this line
```
rewrite ^(\/web-apps\/apps\/(?!api\/).*)$ /${cfg.package.version}$1 redirect;
``` 

I get further, Onlyoffice starts loading but fails with an other error. The file `https://office.example.org/sdkjs/common/AllFonts.js` cannot be found.

**Comment by SuperSandro2000** [comment]
> Oh this is though ... Nginx will now run Onlyoffice on http://office.example.org:8080. Now I'm using Caddy as a reverse proxy for the domain [office.example.org](https://office.example.org). Unfortunately Nginx will always redirect to http and port 8080. Not sure how to fix this :(

I would recommend to only use nginx as a reverse proxy. Probably some of the Headers I set for the proxy are not set from caddy. Those headers are very important for onlyoffice and strange bugs will occur if they are missing.

The url to AllFonts is supposed to be ``https://onlyoffice.example.org/7.1.1-23/sdkjs/common/AllFonts.js``.

Also I would recommend to clear ``/var/lib/onlyoffice``. It can contain stale caches from debugging which can break things.

**Review by aanderse — APPROVED** [review]

**Comment by GaetanLepage** [comment]
Hello !

Thank you very much for porting onlyoffice to NixOS !
Would you know if this will be backported/made available to the `22.05` branch.
Is there anything I could do to help this happen ?

**Comment by SuperSandro2000** [comment]
> Would you know if this will be backported/made available to the `22.05` branch ?
> Is there anything I could do to help this happen ?

Yes, it won't be backported. I am not using stable and I don't want to backport such a brittle software.

**Comment by GaetanLepage** [comment]
Ok, I will use `unstable` for this package then :)

**Comment by dotlambda** [comment]
Could we do some systemd hardening on the service?

**Comment by SuperSandro2000** [comment]
Sure but I was happy to get it working in the first place and then wanted to take a break of it.

**Comment by dotboris** [comment]
For anyone hitting the issue where `onlyoffice` misbehaves when behind a reverse proxy and tries to redirect to the wrong protocol / port, I have a solution / workaround:

```nix
services = {
  onlyoffice = {
    port = 8008;
    enable = true;
    hostname = "example.com";
  };
  nginx.virtualHosts."example.com" = {
    extraConfig = ''
      # Force nginx to return relative redirects. This lets the browser
      # figure out the full URL. This ends up working better because it's in
      # front of the reverse proxy and has the right protocol, hostname & port.
      absolute_redirect off;
    '';
    listen = [
      {
        port = 8009;
        addr = "127.0.0.1";
      }
    ];
  };
};
```

In my case I have `traefik` (https on port 443) -> `nginx` (http on port 8009) -> `onlyoffice` (http on port 8008). When I request `https://example.com` I get redirected to `http://example.com:8009/welcome` (wrong port and protocol). This is an issue with `nginx`. When it performs a redirect it does so by building an absolute URL based on request and or config. I'm not sure what happens under the hood but it ends up picking http as the protocol and 8009 as the port. This matches the server config and not the request.

Setting `absolute_redirect off;` works around this by telling `nginx` to use relative redirects. So instead of trying to redirect `http://example.com:8009/welcome` it just redirects to `/welcome`. This leaves the browser to figure out how to build the final URL. Since it's talking to the first reverse proxy in the chain (`traefik` in my case) it already has the right scheme, host and port in hand and figured out correctly that the final URL should be `https://example.com/welcome`.

**Pull request merged**
