### PR TITLE
mozillavpn: 2.16.1 → 2.19.0

### PR DESCRIPTION
**Pull request by andersk**
## Description of changes

Upgrade the Mozilla VPN client from 2.16.1 to 2.19.0.

https://github.com/mozilla-mobile/mozilla-vpn-client/releases/tag/v2.17.0
https://github.com/mozilla-mobile/mozilla-vpn-client/releases/tag/v2.17.1
https://github.com/mozilla-mobile/mozilla-vpn-client/releases/tag/v2.18.0
https://github.com/mozilla-mobile/mozilla-vpn-client/releases/tag/v2.18.1
https://github.com/mozilla-mobile/mozilla-vpn-client/releases/tag/v2.19.0
https://github.com/mozilla-mobile/mozilla-vpn-client/compare/v2.16.1...v2.19.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flosse** [comment]
I can see only a blank screen :disappointed: 
I can only see a blank screen, whether with version `2.16.1` or `2.17.1`.
Also using a [known workaround](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3353#issuecomment-1733128646) described by an Arch Linux user [does not work](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3353#issuecomment-1757833599).
What can I do?

**Comment by andersk** [comment]
@flosse Maybe try deleting `~/.cache/Mozilla VPN`?

**Comment by flosse** [comment]
> @flosse Maybe try deleting `~/.cache/Mozilla VPN`?

no, unfortunately that changes nothing :disappointed:

**Comment by andersk** [comment]
Hmm. You completely restarted the GUI process right? (The × button doesn’t stop it, it sticks around in the system tray.)

**Comment by pbsds** [comment]
Is the version bump required for the package to work with the upstream service?

**Comment by andersk** [comment]
@pbsds I haven’t checked that but probably not. Why? Bug fixes and performance improvements are a good enough reason to upgrade.

**Comment by pbsds** [comment]
Yes, but i don't think i warrants a backport to 23.05

**Comment by andersk** [comment]
> Yes, but i don't think it warrants a backport to 23.05

Oh sure (I first opened this before the 23.11 release).

**Pull request merged**
