### PR TITLE
bmake: 20200902 -> 20210420

### PR DESCRIPTION
**Pull request by sternenseemann**
* Fix varmod-localtime test by setting TZ to an absolute path to the
  appropriate file in TZDIR. This avoids having an extra patch for musl
  which doesn't support TZDIR at all.
* Move tests into checkPhase by applying patch from alpine
* Fix build with musl by disabling deptgt-delete_on_error test (which I
  haven't debugged myself, just copied this from alpine) and fixing a
  test which fails due to differing output from strerror(3) between musl
  and glibc. Also we need to add a shebang to install-sh, otherwise it
  won't be executed in pkgsMusl.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build pkgsMusl.bmake

**Comment by sternenseemann** [comment]
@ofborg build bmake

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125071` at 10f8f082 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>bmake</li>
    <li>hikari</li>
    <li>kgt</li>
    <li>libfsm</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 125071` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>bmake</li>
    <li>hikari</li>
    <li>kgt</li>
    <li>libfsm</li>
  </ul>
</details>

**Review by siraben — APPROVED** [review]
LGTM, binaries run.

**Pull request merged**
