### PR TITLE
mesa: 23.1.7 -> 23.2.1

### PR DESCRIPTION
**Pull request by colemickens**
## Description of changes

Update to latest stable tagged mesa release.

* https://docs.mesa3d.org/relnotes/23.2.1.html
* https://gitlab.freedesktop.org/mesa/mesa/-/tree/mesa-23.2.1?ref_type=tags

Note, the release notes aren't published yet, but should be available there.

Marking as draft, rebuilding my systems now, will mark as ready if they all build and look okay.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
Please also consider the glslang bump, also targetting staging: https://github.com/NixOS/nixpkgs/pull/256154

Might be nice to get them in together.

**Comment by vcunat** [comment]
I think we'll wait for 23.2.2 because the usual numbers are off by one:
> The goal is that this Wednesday we'll have a final release, which will be tagged 23.2.1 due to an accidental 23.2.0 tag that was created earlier.

**Comment by colemickens** [comment]
I feel like I should know this, but do we have our policy for mesa releases documented? I skimmed the comments in the `mesa/default.nix` and the manual and didn't see it. If I recall, it's something along the lines of waiting for ... odd-numbered bugfix releases? (Which I understand in this case is flipped due to the mis-tag upstream.)

Or is it just any non-initial release of a new major ("minor" semver) version?

**Comment by vcunat** [comment]
I'm not aware of our documentation.  This habit seemed always more about their policy, as they always [say](https://docs.mesa3d.org/relnotes/23.1.0.html)
> Mesa 23.1.0 is a new development release. People who are concerned with stability and reliability should stick with a previous release or wait for Mesa 23.1.1.

**Comment by colemickens** [comment]
Right, right. Ok. I'll go ahead and close this then, just so someone else has the chance to beat me to the punch when 23.2.2 is tagged. Thanks @vcunat.

**Comment by colemickens** [comment]
Ack. Re-opened. So far, Sway, my usual apps, and Halo: Infinite are all working fine. Maybe Halo even noticeably better, but that could be upgrade-itis.

**Comment by trofi** [comment]
> This branch has conflicts that must be resolved

Does not apply to `staging` as is.

**Comment by vcunat** [comment]
I pushed a patch-level update yesterday.

**Comment by jansol** [comment]
Might as well start looking into [23.3.0-rc1](https://lists.freedesktop.org/archives/mesa-dev/2023-October/226071.html). I'm not too convinced that we'll ever see a 23.2.2.

**Comment by vcunat** [comment]
Well, I see 23.2.0-rc1 more than three months ago...

**Comment by returntoreality** [comment]
I think updating to mesa 23.2 would be useful, since it would then be included in nixos 23.11, the final release of mesa 23.3 is probably after the nixos 23.11 release and I don't think mesa is something that would be eligible for backporting.

**Comment by vcunat** [comment]
Yes.  We have backported patch bumps, but not larger updates.  I was already thinking that I'd like to have 23.2 in NixOS 23.11.  At this point I'm still hoping for upstream release within a few days.

**Comment by tormeh** [comment]
According to Phoronix Mesa 23.2 brings default-enabled ray tracing to RADV: https://www.phoronix.com/news/Mesa-23.2.1-Released

It's also enabled on OpenSuSE Tumbleweed: https://software.opensuse.org/package/Mesa
and Ubuntu 23.10: https://answers.launchpad.net/ubuntu/mantic/+source/mesa

**Comment by pearsche** [comment]
This also fixes a rendering bug with chromium-based stuff (browsers, electron)

**Comment by vcunat** [comment]
Well, you know, the primary reason why I felt like stalling this merge was the expected ratio of fixes vs. breakages.

**Comment by K900** [comment]
Superseded by 23.3.1.

**Pull request closed without merging**
