### PR TITLE
libhwy: 1.0.4 -> 1.0.5

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/google/highway/releases/tag/1.0.5

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
`pkgsi686Linux.libhwy` fails 2 tests for problematic precision:

```
The following tests FAILED:
        830 - HwyMathTestGroup/HwyMathTest.TestAllAtanh/EMU128  # GetParam() = 2305843009213693952 (Subprocess aborted)
        854 - HwyMathTestGroup/HwyMathTest.TestAllLog1p/EMU128  # GetParam() = 2305843009213693952 (Subprocess aborted)
```

**Comment by trofi** [comment]
Worked around via `"-DHWY_CMAKE_SSE2=ON"`. Should be good to go.

**Comment by risicle** [comment]
This release contains some useful fixes. Would be nice to backport, but it's also quite a big diff for a point release..

**Comment by vcunat** [comment]
https://hydra.nixos.org/build/229938140/nixlog/1/tail

**Comment by trofi** [comment]
Looking at `libhwy` failure on `aarch64-linux`.

**Comment by trofi** [comment]
Filed upstream issue: https://github.com/google/highway/issues/1613 . Will think a bit about possible workaround. Worst case we could hold `1.0.4` back just for `stdenv.isAarch64` as failure looks SVE-specific.

**Comment by trofi** [comment]
@yu-re-ka proposed the fix in https://github.com/NixOS/nixpkgs/pull/246333

**Pull request merged**
