### PR TITLE
gnuradio.unwrapped: 3.10.7.0 -> 3.10.8.0

### LINKED ISSUE #275427: Update request: gnuradio 3.10.7.0 → 3.10.8.0
- Package name: gnuradio
- Latest released version: 3.10.8.0

- Current version on the unstable channel: 3.10.7.0
- Current version on the stable/release channel:3.10.7.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@doronbehar   
@bjornfor   
@fpletz   
@jiegec  

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jiegec** [comment]
`modtool-newmod-permissions.patch` needs to be rebased.

**Comment by doronbehar** [comment]
Thanks for the notice, refreshed patch, and removed the other patch which was merged upstream. Checked that `configurePhase` passes, but haven't checked full build yet. I may run `nixpkgs-review` in my office after ofborg is green.

**Comment by jiegec** [comment]
> Thanks for the notice, refreshed patch, and removed the other patch which was merged upstream. Checked that `configurePhase` passes, but haven't checked full build yet. I may run `nixpkgs-review` in my office after ofborg is green.

The refreshed patch worked on 3.10, but failed 3.9.

**Comment by doronbehar** [comment]
Haha thanks for the observation!

**Comment by jiegec** [comment]
Result of `nixpkgs-review pr 275645` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>gnuradio</li>
    <li>gnuradio3_9</li>
    <li>gnuradioMinimal (gnuradio3_9Minimal)</li>
    <li>gnuradio3_9Packages.grnet</li>
    <li>gnuradio3_9Packages.osmosdr</li>
    <li>gnuradio3_9Packages.osmosdr.dev</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
Result of `nixpkgs-review pr 275645` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>gnuradio3_9Packages.osmosdr</li>
    <li>gnuradio3_9Packages.osmosdr.dev</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_9</li>
    <li>gnuradioMinimal (gnuradio3_9Minimal)</li>
    <li>gnuradio3_9Packages.grnet</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
The failures are due to `webkitgtk` failing to build from some reason.. These aren't related to the PR.

**Pull request merged**
