### PR TITLE
minimal-bootstrap.findutils: init at 4.4.2

### PR DESCRIPTION
**Pull request by emilytrau**
###### Description of changes

Related #227914

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by emilytrau** [comment]
@ofborg eval

**Review by 06kellyjac — APPROVED** [review]

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 245846` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>minimal-bootstrap.findutils</li>
    <li>minimal-bootstrap.test</li>
  </ul>
</details>

**Comment by davidak** [comment]
My nix daemon might be misconfigured so it thinks my system can't build `i686-linux`.

```
[davidak@gaming:~/code/nixpkgs]$ nix run github:Mic92/nixpkgs-review -- pr --post-result 245846
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/245846/head:refs/nixpkgs-review/1
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 16 (delta 7), reused 9 (delta 7), pack-reused 4
Unpacking objects: 100% (16/16), 274.59 KiB | 2.16 MiB/s, done.
From https://github.com/NixOS/nixpkgs
   e24d9ffc2da7..1b29ae46568e  master                -> refs/nixpkgs-review/0
 + 96672039104b...52ec937b7786 refs/pull/245846/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/davidak/.cache/nixpkgs-review/pr-245846/nixpkgs 1b29ae46568ef048c99d8dda95b3bbb17b6c4ff5
Preparing worktree (detached HEAD 1b29ae46568e)
Updating files: 100% (36477/36477), done.
HEAD is now at 1b29ae46568e Merge pull request #246208 from XYenon/master
$ git merge --no-commit --no-ff 52ec937b7786187feb97c4570839b100745cb1e6
Automatic merge went well; stopped before committing as requested

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/245846

2 packages marked as broken and skipped:
minimal-bootstrap.findutils minimal-bootstrap.test

error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
Posting result comment on https://github.com/NixOS/nixpkgs/pull/245846
$ /run/current-system/sw/bin/nom-shell /home/davidak/.cache/nixpkgs-review/pr-245846/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-245846]$ nix build -f nixpkgs/ minimal-bootstrap.findutils
error: Package ‘tinycc-mes-unstable-2023-04-20’ in «unknown-file» is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-unknown-linux-gnu"
         package.meta.platforms = [
           "i686-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

This leads to an error that might be helpful?

```
[nix-shell:~/.cache/nixpkgs-review/pr-245846]$ nix build -f nixpkgs/ minimal-bootstrap.findutils --impure
error: hash mismatch in fixed-output derivation '/nix/store/rivkjf3vnb267xl9xpjwj8wyzis4y0hs-bash-2.05b.tar.gz.drv':
         specified: sha256-ugPUEpmMxUvQsPLWwyEAln0xNwmK/9wtMubnwRsWP+Q=
            got:    sha256-S/si3tvSbXziBieGKi3JU4wmA/aUgJQSJnQGmguDfnk=
error: 1 dependencies of derivation '/nix/store/cfzyqgmrf2z3yh3jx8a096bj25hx3mbm-bash-2.05b-builder.drv' failed to build
error: 1 dependencies of derivation '/nix/store/36xhz8d1q0abnsn9rq3kkb6pg9r8gy1g-bash-2.05b.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jf3n45sqqaa5n4srsb9jc0j8f1ri0a6w-findutils-4.4.2.drv' failed to build
```

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 245846` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>minimal-bootstrap.findutils</li>
    <li>minimal-bootstrap.test</li>
  </ul>
</details>

**Review by Ericson2314 — APPROVED** [review]

**Pull request merged**
