### PR TITLE
duckdb: 0.8.0 -> 0.8.1

### PR DESCRIPTION
**Pull request by cpcloud**
###### Description of changes

Bump duckdb: 0.8.0 -> 0.8.1
Bump python3Packages.sqlglot: 15.0.0 -> 16.3.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cpcloud** [comment]
Result of `nixpkgs-review pr 238395` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>duckdb</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python310Packages.duckdb</li>
    <li>python310Packages.duckdb-engine</li>
    <li>python310Packages.duckdb-engine.dist</li>
    <li>python310Packages.duckdb.dist</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.ibis-framework.dist</li>
    <li>python310Packages.sqlglot</li>
    <li>python310Packages.sqlglot.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>sbclPackages.duckdb</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Both commit messages lack a motivation, or as CONTRIBUTING.md states it:

> (Motivation for change. Link to release notes. Additional information.)

**Comment by cpcloud** [comment]
Is this a new criteria? I don't remember this requirement from previous PRs. Happy to add it though. Is there anything needed beyond "The motivation for this change is to update the version of `$package`?"

**Comment by cpcloud** [comment]
@mweinelt Are you looking for release notes, or something specific?

**Comment by cpcloud** [comment]
@mweinelt Added links to release notes.

**Comment by mweinelt** [comment]
> Is this a new criteria? I don't remember this requirement from previous PRs. Happy to add it though. Is there anything needed beyond "The motivation for this change is to update the version of `$package`?"

I only consider this a clarification, of what a motivation can be, but that happend in 2022/04. https://github.com/NixOS/nixpkgs/commit/cd00cafaaddb06e4b7075e0ca1562dd8610a9e7a

> @mweinelt Are you looking for release notes, or something more specific?

Yes, I am. Release notes are more or less a good way to understand what changed between two versions, if one does not intend to trawl through the diff. So my thinking is they are crucial to evaluate a package bump, because of dependency changes etc..

**Comment by cpcloud** [comment]
@mweinelt I think this is ready for review.

**Pull request merged**
