### PR TITLE
gcc11: init at 11.1.0

### PR DESCRIPTION
**Pull request by bobrik**
###### Motivation for this change

Pretty much copy-pasted from gcc10 from staging with changed version and sha256.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Synthetica9** [comment]
I think you should also add gcc11Stdenv

(the release of gcc11 was explicitly mentioned by @jonringer in https://discourse.nixos.org/t/21-05-release-schedule/12528)

**Comment by jonringer** [comment]
Adding it is fine, just please don't bump the default gcc until after the release :). Generally there's a lot of breakages as historically some warnings getting promoted to errors, or similar additional strictness additions. .

**Comment by bobrik** [comment]
Added missing `gcc11Stdenv`. I'm not touching the default `stdenv` in any way.

**Review by jonringer — APPROVED** [review]
LGTM

```
$ nix-build -E 'with import ./nixpkgs {}; hello.override { stdenv = gcc11Stdenv; }'
/nix/store/0qjz8255i9ka5gpfr63g1d2h19z5zz8i-hello-2.10
$ ./result/bin/hello --help
Usage: ./result/bin/hello [OPTION]...
Print a friendly, customizable greeting.

  -h, --help          display this help and exit
  -v, --version       display version information and exit

  -t, --traditional       use traditional greeting
  -g, --greeting=TEXT     use TEXT as the greeting message

Report bugs to: bug-hello@gnu.org
GNU Hello home page: <http://www.gnu.org/software/hello/>
General help using GNU software: <http://www.gnu.org/gethelp/>
```

**Comment by vcunat** [comment]
_Well, it's too late to fix the typo in the commit message, too, but it seems not important at all._

**Comment by bobrik** [comment]
Follow-up: #121759.

**Pull request merged**
