### PR TITLE
nixos/nftables: add options for defining chains and flowtables

### PR DESCRIPTION
**Pull request by dblsaiko**
## Description of changes

This adds detailed structured options for nftables for flowtables, chains, most rule expressions and some rule statements. Most of the information about available syntax was gathered from the nft man page including the descriptions for options, and the nft describe command for types.

I have not tested all these options because there is A LOT of them, but a subset that I'm using for my router works.

The syntax is partially pretty awful, for example the nftables expression `ipsec in reqid 1` becomes `ipsec.reqid = [{direction = "in"; match = [1];}];`, but I haven't found a better way for how to map iptables syntax to NixOS options. If you have a better idea, please advise.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by r-vdp** [comment]
Cool, I'll try to find the time to try this out soon!

**Comment by MinerSebas** [comment]
There also exists this https://github.com/thelegy/nixos-nftables-firewall for creating rules in nix. Though that implementation doesn't support every feature of nftables (https://github.com/thelegy/nixos-nftables-firewall/issues/7)

**Comment by rnhmjoj** [comment]
All right, so structured options for configuring the firewall are very cool from a user perspective, however
you've had to add a lot of code with a huge maintanance burder. What I mean is, someone will have to 
keep this in sync with upstream; any kernel/nftables update will have the potential to break the firewall in unpredictable ways.
This will at least require extensive testing to catch possible issues, plus someone to actually fix the issues. Will this be you?

This is more subjective, but another problem is that the way you write the rules deviates considerably from the nftables syntax. So, this will be more like an advanced nftables *frontend*, but it will not replace the stringly-typed `networking.nftables.ruleset` option, which users familiar with nftables may prefer.

I really don't mean to discourage you, but I don't think these changes are worth the associated costs. With a much smaller scope, I could see something like this extending the `networking.firewall` module with a mean to write slightly more complex rules that just opening ports; bringing in the full nftables into NixOS however doesn't seem like a good idea to me.

**Comment by 2xsaiko** [comment]
Yeah, that's true, while I don't think it would be a big issue and upstream breaking changes that would break this would break the "raw" way to write nftables rules too, it is still effort to keep it in sync with available expressions.

I think this could be done without the maintenance effort by just having rules be strings or even list of strings (i.e. `rules = ["tcp dport ssh accept"];`) so my initial goal of being able to extend chains is possible and expressions don't need to be nixos types which would remove a huge part of this code.

If someone wants to pick this up and do that, feel free (I might even do that myself in the future) but I currently don't have the energy to do that so for now I'll keep this in [my modules collection](https://git.sr.ht/~dblsaiko/nix-extras/tree/master/item/nixos/ext/networking/nftables).

**Pull request closed without merging**
