### PR TITLE
fix shell in ammonite package #68151

### LINKED ISSUE #68151: Ammonite "exec" format issue on fish
**Describe the bug**
The ammonite package is broken if a user sets their shell to `fish`.

**To Reproduce**
1. Set the user shell to `fish`

```nix
    users.fabian = {
      isNormalUser = true;
      extraGroups = [ "wheel" ];
      shell = pkgs.fish;
    };
```
2. Install the `ammonite` package (`nix-env -iA nixos.ammonite`
3. Try to run the `amm` executable.

One will get the following error:

```text
Failed to execute process '/home/fabian/.nix-profile/bin/amm'. Reason:
exec: Exec format error
The file '/home/fabian/.nix-profile/bin/amm' is marked as an executable but could not be run by the operating system.
```

However,

```bash
bash
amm
```

works.

**Expected behavior**
Ammonite loads a REPL

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.11, NixOS, 19.03.173426.541d9cce8af (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173426.541d9cce8af"`
 - channels(fabian): `"nixos-unstable-19.09pre191505.7d5375ebf4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: ammonite
```

Maintainer: /cc @NeQuissimus

### PR DESCRIPTION
**Pull request by bbjubjub2494**
###### Motivation for this change
The amm command doesn't work when started from the fish shell because it lacks a shebang.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions (Arch Linux with Arch Linux provided fish)
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"` *No diff detected*
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after) *+8 bytes*
- [x] Ensured that relevant documentation is up to date **Nothing to update AFAICT**
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @NeQuissimus

### CODE REVIEW

**Comment by doom3wasagoodgame** [comment]
Have you considered using `#!/usr/bin/env bash` because `#!/bin/sh` is not always `bash`

**Review by NeQuissimus — APPROVED** [review]

**Comment by lourkeur** [comment]
> Have you considered using `#!/usr/bin/env bash` because `#!/bin/sh` is not always `bash`. Otherwise  LGTM

Good question. Upstream recommends `/usr/bin/env sh` (oddly enough) as a shebang. The shell script[1] looks like it's meant to not only work with any POSIX sh but also with batch.exe. It's very short because the rest of the file is in fact the JAR and I don't see any bashisms. To test this hypothesis further, I passed it to [dash](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/dash/default.nix) and surely enough, ammonite started as usual. Thus I think /bin/sh is appropriate.

[1]
```sh
@ 2>/dev/null # 2>nul & echo off & goto BOF
:
exec /nix/store/qdb4a4qww23a6cb408qi5r7ypmk1c6dp-openjdk-8u222-ga-jre/bin/java -Xmx500m -XX:+UseG1GC $JAVA_OPTS -cp "$0" ammonite.Main --no-remote-logging "$@"
exit

:BOF
@echo off
java -Xmx500m -XX:+UseG1GC %JAVA_OPTS% -cp "%~dpnx0" ammonite.Main %*
exit /B %errorlevel%
PK
... rest of the jar

**Comment by lourkeur** [comment]
I ticked "Tested using sandboxing" because I realised it was on the whole time.

`nix-review` says `No diff detected, stopping review...`

Package closure size:
```
Before
/nix/store/xmap6fl3rglvczvgz946fp83l4mh2wna-ammonite-1.7.4	  431872784
After
/nix/store/2irpkws16m4bbsykzmg8dknapjix59qn-ammonite-1.7.4	  431872792

**Comment by lilyball** [comment]
I've tested this on macOS. Seems to work.

```
> nix-shell -E 'with import ./default.nix {}; mkShell { buildInputs = [ ammonite fish ]; }'
these derivations will be built:
  /nix/store/3gzk5ycx0akp04jr1hfhw5ppmns15ww8-ammonite-1.7.4.drv
these paths will be fetched (293.54 MiB download, 1103.47 MiB unpacked):
  […]

[nix-shell:~/Dev/Nix/nixpkgs]$ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
fish prompt> amm
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/sourceBridge.sc
Compiling (synthetic)/ammonite/predef/frontEndBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Welcome to the Ammonite Repl 1.7.4
(Scala 2.13.1 Java 1.8.0_222)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@
```

**Pull request merged**
