### PR TITLE
vcv-rack: 2.1.2 -> 2.2.0

### PR DESCRIPTION
**Pull request by ddelabru**
###### Description of changes

Rack v2.2.0 features a few dependency changes relative to the previous release. This required pulling in a couple new dependency sources for the build.

The build did manage to apply the existing Makefile patch, but the line numbers / context of the lines in the upstream Makefile have changed, so I decided it was best to update the patch anyway.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ddelabru** [comment]
@nathyong, @jpotier, heads up on this VCV Rack version upgrade.

**Review by nathyong — APPROVED** [review]
Looks good to me. Note that I haven't tested these changes.

**Review by jpotier — APPROVED** [review]
Looks good, tested local build and execution on x86_64-linux with:

```
$ nix build --impure 'github:ddelabru/nixpkgs/vcv-rack#vcv-rack'
$ ./result/bin/Rack
```

All green.

**Comment by jpotier** [comment]
I can also confirm that the build fails for aarch64-linux (tested on the Pinebook Pro)

**Comment by ddelabru** [comment]
> I can also confirm that the build fails for aarch64-linux (tested on the Pinebook Pro)

Hmmm, I'm assuming that v2.1.2 compiles alright on linux-aarch64? I might want to figure out what's causing that issue

**Comment by jpotier** [comment]
> I'm assuming that v2.1.2 compiles alright on aarch64-linux?

My assumption is that it doesn't. I can test this too

**Comment by ddelabru** [comment]
I amended slightly to change out `speex` for `speexdsp` because that seems to be what we really want. I confirmed that it still compiles and runs fine on x86_64-linux with that change.

@jpotier, I don't have an aarch64-linux system, but I did try cross-compiling just now with `NIXPKGS_ALLOW_UNFREE=1 nix-build . -A pkgsCross.aarch64-multiplatform.vcv-rack` in the nixpkgs repo root directory. What happened in my case was that compilation failed because of a known issue with the derivation for `glib`: #201994. If your PineBook build was failing on the same error about `xsltproc` being unavailable when compiling `glib`, hopefully the fixes for that issue that are already waiting to be merged into Nixpkgs will help. Otherwise, maybe when that has been fixed I can rebase my commit and try to cross-compile again to figure out what the actual cause of the issue is.

**Comment by ddelabru** [comment]
> ```
> arch.mk:10: *** Could not determine CPU architecture of aarch64-unknown-linux-gnu. Try hacking around in arch.mk. Stop.
> ```

I wrote my earlier comment before I read this. I'll take a closer look but if it really seems Rack just isn't going to have aarch64 support I'll change the `platforms` to reflect that.

**Comment by ddelabru** [comment]
Potentially good news, @jpotier! It looks like the VCV Rack makefiles are just scanning an architecture string for `arm64` and not detecting the right architecture because in your environment that instruction set is instead called `aarch64`. But `arm64` and `aarch64` are effectively the same thing, so I _think_  I just need to pass an extra flag to `make` in the case that one is building on aarch64-linux.

I amended my commit to conditionally add that flag; see if with this latest version you can build VCV Rack on the Pinebook.

**Comment by ddelabru** [comment]
(Sorry for the noise but I wrote the conditional for the make flags all wrong at first; I amended them so they should hopefully be correct now.)

**Comment by jpotier** [comment]
After your latest changes, the build finishes successfully on the PBP! Nice!

The PBP doesn't have the necessary runtime deps (got an OpenGL is missing error) so Rack won't start. But that's still a pretty good improvement!

**Review by jpotier — APPROVED** [review]

**Pull request merged**
