### PR TITLE
python3Packages.mypy: 0.961 -> 0.971; python3Packages.mypy_extensions: skip failing test on python311

### PR DESCRIPTION
**Pull request by mweinelt**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg build python311.pkgs.mypy python311.pkgs.mypy_extensions

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 191084` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>archivebox</li>
    <li>python310Packages.apache-airflow</li>
    <li>python310Packages.tvdb_api</li>
    <li>python39Packages.apache-airflow</li>
    <li>python39Packages.tvdb_api</li>
    <li>truvari</li>
    <li>tvnamer</li>
  </ul>
</details>
<details>
  <summary>34 packages failed to build:</summary>
  <ul>
    <li>baserow</li>
    <li>cwltool</li>
    <li>dbx</li>
    <li>gnome-keysign</li>
    <li>magic-wormhole (python310Packages.magic-wormhole)</li>
    <li>openai (python310Packages.openai)</li>
    <li>paperless-ngx</li>
    <li>pgadmin4</li>
    <li>powerdns-admin</li>
    <li>python310Packages.duckdb</li>
    <li>python310Packages.duckdb-engine</li>
    <li>python310Packages.gradient</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.lektor</li>
    <li>python310Packages.pandas-stubs</li>
    <li>python310Packages.schema-salad</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-transformers</li>
    <li>spyder (python310Packages.spyder)</li>
    <li>python310Packages.textacy</li>
    <li>python39Packages.duckdb</li>
    <li>python39Packages.duckdb-engine</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.ibis-framework</li>
    <li>python39Packages.lektor</li>
    <li>python39Packages.magic-wormhole</li>
    <li>python39Packages.openai</li>
    <li>python39Packages.pandas-stubs</li>
    <li>python39Packages.schema-salad</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.spyder</li>
    <li>python39Packages.textacy</li>
    <li>tahoe-lafs</li>
  </ul>
</details>
<details>
  <summary>307 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>anime-downloader</li>
    <li>autosuspend</li>
    <li>azure-cli</li>
    <li>barman</li>
    <li>black (python310Packages.black)</li>
    <li>black-macchiato (python310Packages.black-macchiato)</li>
    <li>buildbot (python310Packages.buildbot)</li>
    <li>buildbot-full (python310Packages.buildbot-full)</li>
    <li>buildbot-ui (python310Packages.buildbot-ui)</li>
    <li>buildbot-worker (python310Packages.buildbot-worker)</li>
    <li>buku</li>
    <li>chia</li>
    <li>cmake-format</li>
    <li>cmake-language-server</li>
    <li>coconut (python310Packages.coconut)</li>
    <li>conan</li>
    <li>cryptop</li>
    <li>cura</li>
    <li>cve-bin-tool</li>
    <li>datadog-agent</li>
    <li>datadog-process-agent</li>
    <li>dmarc-metrics-exporter</li>
    <li>dvc-with-remotes</li>
    <li>flitter</li>
    <li>grab-site</li>
    <li>home-assistant-component-tests.bsblan</li>
    <li>home-assistant-component-tests.google_pubsub</li>
    <li>home-assistant-component-tests.nest</li>
    <li>home-assistant-component-tests.plugwise</li>
    <li>home-assistant-component-tests.renault</li>
    <li>home-assistant-component-tests.sia</li>
    <li>isort (python310Packages.isort)</li>
    <li>json-schema-for-humans (python310Packages.json-schema-for-humans)</li>
    <li>mnamer</li>
    <li>mypy (python310Packages.mypy)</li>
    <li>nix-pin</li>
    <li>parsedmarc (python310Packages.parsedmarc)</li>
    <li>pokete</li>
    <li>portmod</li>
    <li>prospector</li>
    <li>pwndbg</li>
    <li>pylint (python310Packages.pylint)</li>
    <li>python310Packages.adlfs</li>
    <li>python310Packages.aiokef</li>
    <li>python310Packages.algebraic-data-types</li>
    <li>python310Packages.angr</li>
    <li>python310Packages.angrcli</li>
    <li>python310Packages.angrop</li>
    <li>python310Packages.applicationinsights</li>
    <li>python310Packages.autobahn</li>
    <li>python310Packages.avro-python3</li>
    <li>python310Packages.azure-identity</li>
    <li>python310Packages.baselines</li>
    <li>python310Packages.betterproto</li>
    <li>python310Packages.bravado-core</li>
    <li>python310Packages.bsblan</li>
    <li>python310Packages.cairo-lang</li>
    <li>python310Packages.cattrs</li>
    <li>python310Packages.chalice</li>
    <li>python310Packages.channels</li>
    <li>python310Packages.channels-redis</li>
    <li>python310Packages.concurrent-log-handler</li>
    <li>python310Packages.daphne</li>
    <li>python310Packages.dataclasses-json</li>
    <li>python310Packages.dataclasses-serialization</li>
    <li>python310Packages.diff-cover</li>
    <li>python310Packages.diofant</li>
    <li>python310Packages.django-storages</li>
    <li>python310Packages.django-stubs</li>
    <li>python310Packages.dragonfly</li>
    <li>python310Packages.fingerprints</li>
    <li>python310Packages.flake8-bugbear</li>
    <li>python310Packages.flake8-import-order</li>
    <li>python310Packages.gcsfs</li>
    <li>python310Packages.gensim</li>
    <li>python310Packages.globus-sdk</li>
    <li>python310Packages.google-cloud-asset</li>
    <li>python310Packages.google-cloud-automl</li>
    <li>python310Packages.google-cloud-bigquery</li>
    <li>python310Packages.google-cloud-bigquery-datatransfer</li>
    <li>python310Packages.google-cloud-bigtable</li>
    <li>python310Packages.google-cloud-container</li>
    <li>python310Packages.google-cloud-datacatalog</li>
    <li>python310Packages.google-cloud-dataproc</li>
    <li>python310Packages.google-cloud-datastore</li>
    <li>python310Packages.google-cloud-dlp</li>
    <li>python310Packages.google-cloud-error-reporting</li>
    <li>python310Packages.google-cloud-iam</li>
    <li>python310Packages.google-cloud-iot</li>
    <li>python310Packages.google-cloud-kms</li>
    <li>python310Packages.google-cloud-language</li>
    <li>python310Packages.google-cloud-monitoring</li>
    <li>python310Packages.google-cloud-os-config</li>
    <li>python310Packages.google-cloud-pubsub</li>
    <li>python310Packages.google-cloud-redis</li>
    <li>python310Packages.google-cloud-secret-manager</li>
    <li>python310Packages.google-cloud-securitycenter</li>
    <li>python310Packages.google-cloud-spanner</li>
    <li>python310Packages.google-cloud-speech</li>
    <li>python310Packages.google-cloud-storage</li>
    <li>python310Packages.google-cloud-tasks</li>
    <li>python310Packages.google-cloud-texttospeech</li>
    <li>python310Packages.google-cloud-translate</li>
    <li>python310Packages.google-cloud-vision</li>
    <li>python310Packages.google-cloud-websecurityscanner</li>
    <li>python310Packages.google-nest-sdm</li>
    <li>python310Packages.hypothesmith</li>
    <li>python310Packages.ics</li>
    <li>python310Packages.immutables</li>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.labgrid</li>
    <li>python310Packages.libcst</li>
    <li>python310Packages.magic-wormhole-mailbox-server</li>
    <li>python310Packages.magic-wormhole-transit-relay</li>
    <li>python310Packages.marshmallow-dataclass</li>
    <li>python310Packages.msal-extensions</li>
    <li>python310Packages.mypy-boto3-builder</li>
    <li>python310Packages.mypy-extensions</li>
    <li>python310Packages.numpy-stl</li>
    <li>python310Packages.pathy</li>
    <li>python310Packages.pixelmatch</li>
    <li>python310Packages.plugwise</li>
    <li>python310Packages.portalocker</li>
    <li>python310Packages.progressbar2</li>
    <li>python310Packages.ptpython</li>
    <li>python310Packages.py-ecc</li>
    <li>python310Packages.py-eth-sig-utils</li>
    <li>python310Packages.pyannotate</li>
    <li>python310Packages.pylama</li>
    <li>python310Packages.pylint-celery</li>
    <li>python310Packages.pylint-django</li>
    <li>python310Packages.pylint-flask</li>
    <li>python310Packages.pylint-plugin-utils</li>
    <li>python310Packages.pyls-flake8</li>
    <li>python310Packages.pyls-isort</li>
    <li>python310Packages.pyls-spyder</li>
    <li>python310Packages.pylsp-mypy</li>
    <li>python310Packages.pynamodb</li>
    <li>python310Packages.pynput</li>
    <li>python310Packages.pysiaalarm</li>
    <li>python310Packages.pysychonaut</li>
    <li>python310Packages.pytest-annotate</li>
    <li>python310Packages.pytest-black</li>
    <li>python310Packages.pytest-isort</li>
    <li>python310Packages.pytest-mypy</li>
    <li>python310Packages.pytest-mypy-plugins</li>
    <li>python310Packages.pytest-pylint</li>
    <li>python310Packages.python-lsp-black</li>
    <li>python310Packages.python-lsp-server</li>
    <li>python310Packages.python-utils</li>
    <li>python310Packages.renault-api</li>
    <li>python310Packages.requests-cache</li>
    <li>python310Packages.scancode-toolkit</li>
    <li>python310Packages.setuptools-lint</li>
    <li>python310Packages.smart-open</li>
    <li>python310Packages.spyse-python</li>
    <li>python310Packages.statmake</li>
    <li>python310Packages.strawberry-graphql</li>
    <li>python310Packages.tatsu</li>
    <li>python310Packages.typed-settings</li>
    <li>python310Packages.typical</li>
    <li>python310Packages.typing-inspect</li>
    <li>python310Packages.zimports</li>
    <li>python39Packages.adlfs</li>
    <li>python39Packages.aiokef</li>
    <li>python39Packages.algebraic-data-types</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.applicationinsights</li>
    <li>python39Packages.autobahn</li>
    <li>python39Packages.avro-python3</li>
    <li>python39Packages.azure-identity</li>
    <li>python39Packages.baselines</li>
    <li>python39Packages.betterproto</li>
    <li>python39Packages.black</li>
    <li>python39Packages.black-macchiato</li>
    <li>python39Packages.bravado-core</li>
    <li>python39Packages.bsblan</li>
    <li>python39Packages.buildbot</li>
    <li>python39Packages.buildbot-full</li>
    <li>python39Packages.buildbot-ui</li>
    <li>python39Packages.buildbot-worker</li>
    <li>python39Packages.cairo-lang</li>
    <li>python39Packages.cattrs</li>
    <li>python39Packages.chalice</li>
    <li>python39Packages.channels</li>
    <li>python39Packages.channels-redis</li>
    <li>python39Packages.coconut</li>
    <li>python39Packages.concurrent-log-handler</li>
    <li>python39Packages.daphne</li>
    <li>python39Packages.dataclasses-json</li>
    <li>python39Packages.dataclasses-serialization</li>
    <li>python39Packages.diff-cover</li>
    <li>python39Packages.diofant</li>
    <li>python39Packages.django-storages</li>
    <li>python39Packages.django-stubs</li>
    <li>python39Packages.dragonfly</li>
    <li>python39Packages.fingerprints</li>
    <li>python39Packages.flake8-bugbear</li>
    <li>python39Packages.flake8-import-order</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.gensim</li>
    <li>python39Packages.globus-sdk</li>
    <li>python39Packages.google-cloud-asset</li>
    <li>python39Packages.google-cloud-automl</li>
    <li>python39Packages.google-cloud-bigquery</li>
    <li>python39Packages.google-cloud-bigquery-datatransfer</li>
    <li>python39Packages.google-cloud-bigtable</li>
    <li>python39Packages.google-cloud-container</li>
    <li>python39Packages.google-cloud-datacatalog</li>
    <li>python39Packages.google-cloud-dataproc</li>
    <li>python39Packages.google-cloud-datastore</li>
    <li>python39Packages.google-cloud-dlp</li>
    <li>python39Packages.google-cloud-error-reporting</li>
    <li>python39Packages.google-cloud-iam</li>
    <li>python39Packages.google-cloud-iot</li>
    <li>python39Packages.google-cloud-kms</li>
    <li>python39Packages.google-cloud-language</li>
    <li>python39Packages.google-cloud-monitoring</li>
    <li>python39Packages.google-cloud-os-config</li>
    <li>python39Packages.google-cloud-pubsub</li>
    <li>python39Packages.google-cloud-redis</li>
    <li>python39Packages.google-cloud-secret-manager</li>
    <li>python39Packages.google-cloud-securitycenter</li>
    <li>python39Packages.google-cloud-spanner</li>
    <li>python39Packages.google-cloud-speech</li>
    <li>python39Packages.google-cloud-storage</li>
    <li>python39Packages.google-cloud-tasks</li>
    <li>python39Packages.google-cloud-texttospeech</li>
    <li>python39Packages.google-cloud-translate</li>
    <li>python39Packages.google-cloud-vision</li>
    <li>python39Packages.google-cloud-websecurityscanner</li>
    <li>python39Packages.google-nest-sdm</li>
    <li>python39Packages.hypothesmith</li>
    <li>python39Packages.immutables</li>
    <li>python39Packages.isort</li>
    <li>python39Packages.json-schema-for-humans</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.labgrid</li>
    <li>python39Packages.libcst</li>
    <li>python39Packages.magic-wormhole-mailbox-server</li>
    <li>python39Packages.magic-wormhole-transit-relay</li>
    <li>python39Packages.marshmallow-dataclass</li>
    <li>python39Packages.msal-extensions</li>
    <li>python39Packages.mypy</li>
    <li>python39Packages.mypy-extensions</li>
    <li>python39Packages.numpy-stl</li>
    <li>python39Packages.parsedmarc</li>
    <li>python39Packages.pathy</li>
    <li>python39Packages.pixelmatch</li>
    <li>python39Packages.plugwise</li>
    <li>python39Packages.portalocker</li>
    <li>python39Packages.progressbar2</li>
    <li>python39Packages.ptpython</li>
    <li>python39Packages.py-ecc</li>
    <li>python39Packages.py-eth-sig-utils</li>
    <li>python39Packages.pyannotate</li>
    <li>python39Packages.pylama</li>
    <li>python39Packages.pylint</li>
    <li>python39Packages.pylint-celery</li>
    <li>python39Packages.pylint-django</li>
    <li>python39Packages.pylint-flask</li>
    <li>python39Packages.pylint-plugin-utils</li>
    <li>python39Packages.pyls-flake8</li>
    <li>python39Packages.pyls-isort</li>
    <li>python39Packages.pyls-spyder</li>
    <li>python39Packages.pylsp-mypy</li>
    <li>python39Packages.pynamodb</li>
    <li>python39Packages.pynput</li>
    <li>python39Packages.pysiaalarm</li>
    <li>python39Packages.pysychonaut</li>
    <li>python39Packages.pytest-annotate</li>
    <li>python39Packages.pytest-black</li>
    <li>python39Packages.pytest-isort</li>
    <li>python39Packages.pytest-mypy</li>
    <li>python39Packages.pytest-mypy-plugins</li>
    <li>python39Packages.pytest-pylint</li>
    <li>python39Packages.python-lsp-black</li>
    <li>python39Packages.python-lsp-server</li>
    <li>python39Packages.python-utils</li>
    <li>python39Packages.renault-api</li>
    <li>python39Packages.requests-cache</li>
    <li>python39Packages.scancode-toolkit</li>
    <li>python39Packages.setuptools-lint</li>
    <li>python39Packages.smart-open</li>
    <li>python39Packages.statmake</li>
    <li>python39Packages.strawberry-graphql</li>
    <li>python39Packages.typed-settings</li>
    <li>python39Packages.typing-inspect</li>
    <li>python39Packages.zimports</li>
    <li>qtile</li>
    <li>remarkable-mouse</li>
    <li>snakemake</li>
    <li>sqlfluff</li>
    <li>streamdeck-ui</li>
    <li>sublime-music</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>thonny</li>
    <li>todoman</li>
    <li>topydo</li>
    <li>ulauncher</li>
    <li>vimPlugins.vim-isort</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>zfs-replicate</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
No obvious regressions from this change, all packages I tested are broken on master.

**Review by SuperSandro2000 — COMMENTED** [review]
LGTM

**Pull request merged**
