### PR TITLE
gnome3.gnome-boxes: add glib-networking

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Saw https://github.com/NixOS/nixpkgs/issues/72579#issuecomment-549644178

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]

**Comment by dtzWill** [comment]
I trust this makes sense if you both are on board, but I was under the impression we intentionally didn't add glib-networking in favor of using a nixos module to make it available at runtime.

(not sure why, but presumably because it makes things work better ;))

Is that not the case, or can someone clarify if you don't mind?
I guess I am wondering why this should have glib-networking when we don't add it to "every gnome application making use of https" (which is many hehe).  Or maybe I've got some details/facts wrong?

Thanks!

**Comment by worldofpeace** [comment]
@dtzWill The issue is the gio module, wrapGAppsHook will add it to `GIO_EXTRA_MODULES`.
Users who run into this aren't using the `glib-networking` module which sets this globally. We have this in the module because not every application is wrapped properly.

Though we'd like to remove that eventually, I think, so the proper solution is to bloat the closure of the app with `glib-networking`.

**Comment by jtojnar** [comment]
Personally, I am not a fan of NixOS modules for adding functionality to apps, especially when the functionality is facilitated by binary files. In addition to being impure, which is yuck, issues can happen even in supposedly ABI stable libraries like gdk-pixbuf.

The module is mostly there precisely for the cases when we miss some application needing to access HTTPS, but not all users have it enabled. And having it enabled covers the missing dependency, furthering its own necessity – not exactly fair.

So for now, we are fixing the missing dependencies. Hopefully, we will disable the module by default soon. Same for other similar env vars like `GDK_PIXBUF_MODULE_FILE` and `GST_PLUGIN_SYSTEM_PATH_1_0`, though in the latter case we should probably convert derivations depending on gstreamer plug-ins into multi-level derivations to avoid rebuilds when adding ugly plugins or something.

Note that the situation with glib-networking might be more complicated as potentially every glib application allowing users to work with files through gio should probably have that included, so that user can open remote files over HTTPS.

**Comment by dtzWill** [comment]
Thank you both for your replies!

I understand much better now.
FWIW I'm in favor of adding glib-networking directly when needed
... I just thought maybe there was a reason to not do so :).

All of this is great information and much appreciated.

Mostly I was asking because I believe I have various
'add glib-networking' commits (that should be revisited I'm sure)
and between this and the NixOS module wanted to pick your brains
about things.. perhaps so its clear if I should send upstream or
admit I was wrong (never! :P) and phase out locally haha.

Thanks all, carry on! O:)

**Pull request merged**
