### PR TITLE
lib: add xor

### PR DESCRIPTION
**Pull request by edef1c**
## Description of changes

This gets clumsily reimplemented in various places, to no useful end.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
`xor` is the same as `!=` for booleans, so we don't even need a new `lib` function :D

**Comment by edef1c** [comment]
> `xor` is the same as `!=` for booleans, so we don't even need a new `lib` function :D

I don't disagree, but explicitly naming it `xor` helps ensure people don't reach for strange hacks. It's not a strict necessity, but more of a UX affordance so silly stuff doesn't get written.

Take a look at the diff for the three different overly-complicated xor impls I came across. Perhaps consider it just filling out the missing piece in `lib.{and,or}` vs `lib.bit{And,Or,Xor}`.

This implementation also ensures that the arguments _are_ in fact booleans by inverting them, which is invariant under xor anyway. It seems easy for `x != y` to accidentally fail to ensure there's not some weird typing going on.

**Comment by infinisil** [comment]
Fair enough, makes sense! Let's have a code comment explaining the `!` though, because that's not obvious. Also I'd appreciate a test or two, see https://github.com/NixOS/nixpkgs/blob/053ab7f57cb02e4e1945618f1e6dba148a5419a5/lib/tests/misc.nix#L205-L215.

**Comment by edef1c** [comment]
> I'd appreciate a test or two

Added, whole truth table and all.

> Let's have a code comment explaining the `!` though, because that's not obvious.

Seems just as obvious to me as the rest, which I suppose means it needs pointing out :p
Comment added.

**Review by infinisil — APPROVED** [review]
Looking good, thanks!

**Pull request merged**
