### PR TITLE
lilypond, denemo: migrate to guile 3

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

Lilypond 2.24.3 and Denemo 2.6.9 support Guile 3. Since Denemo is still at 2.6.0 in nixpkgs, an upstream patch is fetched and modified for the migration to Guile 3.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 276174` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>spring</li>
    <li>springLobby</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>clevis</li>
    <li>clevis.man</li>
    <li>denemo</li>
    <li>disorderfs</li>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>lilypond</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lilypond-with-fonts</li>
    <li>luksmeta</li>
    <li>python310Packages.abjad</li>
    <li>python310Packages.abjad.dist</li>
    <li>python311Packages.abjad</li>
    <li>python311Packages.abjad.dist</li>
    <li>solfege</li>
    <li>tang</li>
    <li>tang.man</li>
  </ul>
</details>

**Comment by yurrriq** [comment]
Thanks, I can test LilyPond, at least. Could you please add a note to the 24.05 release notes?

**Comment by yurrriq** [comment]
Building `lilypond` on `x86_64-linux` (NixOS 23.11):
```
lilypond> configure: WARNING: unrecognized options: --disable-static, --with-urwotf-dir, --with-texgyre-dir
lilypond> 
lilypond> WARNING: Please consider installing optional programs or files:  extractpdfmark (Using GhostScript >= 9.20 together with extractpdfmark can significantly reduce the size of the final PDF files.) pltotf
lilypond> 
lilypond> See INSTALL.txt for more information on how to build LilyPond
lilypond> 
lilypond> Type:
lilypond>     make all       to build LilyPond
lilypond>     make install   to install LilyPond
lilypond>     make help      to see all possible targets
lilypond> 
lilypond> Edit local.make for local Makefile overrides.
lilypond> 
lilypond> See INSTALL.txt and README.md for more information
```

Otherwise it builds fine and works as expected on a personal project. Those warnings were not introduced by this PR.

```
λ lilypond --version
GNU LilyPond 2.24.3 (running Guile 3.0)

Copyright (c) 1996--2023 by
  Han-Wen Nienhuys <hanwen@xs4all.nl>
  Jan Nieuwenhuizen <janneke@gnu.org>
  and others.

This program is free software.  It is covered by the GNU General Public
License and you are welcome to change it and/or distribute copies of it
under certain conditions.  Invoke as `lilypond --warranty' for more
information.
```

**Review by yurrriq — APPROVED** [review]

**Review by yurrriq — CHANGES_REQUESTED** [review]
lgtm, but we should probably add something to the 24.05 release notes

**Review by yurrriq — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
