### PR TITLE
stdenv: simplify a bit using shadowing

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Discussion in https://github.com/NixOS/nixpkgs/pull/39464#discussion_r184478498

/cc @Ericson2314

### CODE REVIEW

**Comment by oxij** [comment]
@GrahamcOfBorg build stdenv

**Review by Ericson2314 — APPROVED** [review]

**Comment by oxij** [comment]
Ping? I'm writing this on top of these patches, so I don't think there should be any problems with this.

**Comment by Ericson2314** [comment]
I didn't know if you wanted to merge them yourself / any further testing.

**Comment by oxij** [comment]
Thanks.

Ah, I see, I don't have commit access, though, so "merge myself" can't happen and, unless specified otherwise, I build all the things I PR on top of "notchb" branch of SLNOS ("Nixpkgs/NixOS That Could Have Been", i.e. mostly Nixpkgs-NixOS-compatible SLNOS) before rebasing/picking to nixpkgs, so I expect them to be working as-is most of the time (things do get out of sync sometimes, though, but then there's OfBorg for the rescue), but being explicit about expectations wouldn't hurt, I agree. I'll try to come up with some way to document those starting from the next PR.

**Pull request merged**
