### PR TITLE
networkmanager: fix path /sbin/modprobe

### LINKED ISSUE #12063: networkmanager tries to execute /sbin/modprobe
I use network-manager to create a wifi-hotspot.

`journalctl --unit network-manager` gives the following:

>Jan 01 11:38:38 nixos NetworkManager[15086]: <error> [1451648318.618482] [NetworkManagerUtils.c:346] nm_utils_modprobe(): modprobe: '/sbin/modprobe ip_tables' failed: Failed to execute child process "/sbin/modprobe" (No such file or directory)

And the same for `/sbin/modprobe ip_tables`, `/sbin/modprobe iptable_nat`, `/sbin/modprobe nf_nat_ftp`, `/sbin/modprobe nf_nat_irc`, `/sbin/modprobe nf_nat_sip`, `/sbin/modprobe nf_nat_tftp`, `/sbin/modprobe nf_nat_pptp`.

The errors were followed by following with

>Jan 01 11:38:39 nixos NetworkManager[15086]: <error> [1451648319.864292] [rdisc/nm-lndp-rdisc.c:68] send_rs(): (wlp2s0): cannot send router solicitation: -101.

The workaround `ln -s /run/current-system/sw/bin/modprobe /sbin/` worked for me for now; I'll try to look into it a little bit more in the next days.

### PR DESCRIPTION
**Pull request by fkz**
this fixes #12063

### CODE REVIEW

**Comment by domenkozar** [comment]
Hmm this is NixOs specific, we should use modprobe package as substitute

**Comment by fkz** [comment]
which is the right package to use, `command-not-found modprobe` outputs `busybox`, `kmod` and `module_init_tools`.

**Comment by fkz** [comment]
ahh, I just saw that it uses `substituteInPlace` in the wrong files with `/run/current-system/sw/sbin/modprobe`. This silently broke when they moved this string into an other file. We should have a `substituteInPlace` which fails when it doesn't replace anything.

**Comment by fkz** [comment]
removed the patch now and use `substituteInPlace` instead. This is still NixOS specific as it already was before.

**Comment by bjornfor** [comment]
Pushed to master (28b3ecac07c7075263f397670f46d8465f00cbaf).

**Pull request closed without merging**
