### PR TITLE
obs-studio-plugins.obs-replay-source: init at 1.6.12

### PR DESCRIPTION
**Pull request by pschmitt**
## Things done

This add [obs-replay-source](https://github.com/exeldro/obs-replay-source), which depends on [libcaption](https://github.com/szatmary/libcaption).

I didn't really know *where* to put the libcaption package, and settled on `pkgs/development/libraries/`. Do let me know if this is inappropriate.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by miangraham** [comment]
Result of `nixpkgs-review pr 252191` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-replay-source</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>libcaption</li>
  </ul>
</details>

**Comment by pschmitt** [comment]
Yeah that's this here package.
I can most def reproduce this and have not the slightest idea how this ever built correctly.

My first attempt at fixing failed though (adding `uthash` to `buildInputs`). I'll open a PR once I manage to fix this.

**Comment by pschmitt** [comment]
```
error: builder for '/nix/store/ypd1hw8xpncra0hr2xyrpm0m776kvaf3-obs-replay-source-1.6.12.drv' failed with exit code 2;
       last 10 log lines:
       > In file included from /nix/store/gvzbyv3srf1svpafwrk7mpq7n50pxdjp-obs-studio-29.1.3/include/obs/obs-internal.h:28,
       >                  from /build/source/replay-filter-async.c:5:
       > /nix/store/gvzbyv3srf1svpafwrk7mpq7n50pxdjp-obs-studio-29.1.3/include/obs/util/uthash.h:24:10: fatal error: uthash/uthash.h: No such file or directory
       >    24 | #include <uthash/uthash.h>
       >       |          ^~~~~~~~~~~~~~~~~
       > compilation terminated.
       > make[2]: *** [CMakeFiles/replay-source.dir/build.make:132: CMakeFiles/replay-source.dir/replay-filter-async.c.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/replay-source.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/ypd1hw8xpncra0hr2xyrpm0m776kvaf3-obs-replay-source-1.6.12.drv'.
```

Guess obs-studio itself is the one missing uthash, not obs-replace-source.

**Comment by miangraham** [comment]
Agreed, I believe it's an obs nix package bug that you're surfacing for the first time from a plugin. Looks like upstream is [vendoring it](https://github.com/obsproject/obs-studio/tree/master/deps/uthash) and their wrapper include file may fail to reference the right .h without some cajoling.

**Pull request merged**
