### PR TITLE
difftastic: fix build with clang 12+

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

Work around https://github.com/NixOS/nixpkgs/issues/166205.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by adamcstephens — APPROVED** [review]
linux builds are cached and this fixes darwin.

---

Result of `nixpkgs-review pr 268190` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>difftastic</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 268190` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>difftastic</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by figsoda** [comment]
Thanks!

**Comment by amjoseph-nixpkgs** [comment]
Hey it looks like somebody spammed nixpkgs with 33 copy-and-pastes of this code:

```
$ rg 'https://github.com/NixOS/nixpkgs/issues/166205' | wc -l
33
```

This is really obnoxious; it means that when there's a bug in the copy-and-pasted code (which there is -- it fails if `stdenv.cc.cc.libcxx` exists but lacks the `cxxabi` subattribute) we need 33 separate fixes!

One of the great powers of Nix is that it provides abstraction, so we can refactor instead of copying and pasting.  Please do that next time, so we can fix ONE bug in ONE place instead of THIRTY-THREE separate copies of the same bug.

**Comment by reckenrode** [comment]
I got a notification complaining that this code has been copy and pasted to different derivations, which appears to have been deleted.

Just to explain: that is intentional. It is a workaround. The proper fix belongs in either cc-wrapper or ld-wrapper. I did not implement that fix because @toonn is already working on it, and I did not want to step on that work, but these issues needed to be fixed to get the LLVM update through the staging-next cycle.

**Pull request merged**
