### PR TITLE
 libsForQt5.fcitx-qt5: fix build 

### LINKED ISSUE #65547: fcitx-qt5 fails to build on unstable
**Describe the bug**
fcitx-qt5 fails to build on unstable:

```
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/include/FcitxQt5/FcitxQtWidgetsAddons/fcitxqtconfiguiplugin.h
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/include/FcitxQt5/FcitxQtWidgetsAddons/fcitxqtconfiguiwidget.h
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/include/FcitxQt5/FcitxQtWidgetsAddons/fcitxqtkeysequencewidget.h
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/include/FcitxQt5/FcitxQtWidgetsAddons/fcitxqtwidgetsaddons_export.h
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/lib/fcitx/libexec/fcitx-qt5-gui-wrapper
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/lib/fcitx/qt/libfcitx-quickphrase-editor5.so
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/ca/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/da/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/de/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/es/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/fr/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/ja/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/ko/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/ru/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/zh_CN/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/vzvzv662ll696q6gkiq7n0p3wqm39wj8-fcitx-qt5-1.2.3/share/locale/zh_TW/LC_MESSAGES/fcitx-qt5.mo
-- Installing: /nix/store/wr3hjs0zry8pphrpjwalgfkgbhkjvf61-qtbase-5.12.3-bin/lib/qt-5.12/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
CMake Error at platforminputcontext/cmake_install.cmake:55 (file):
  file INSTALL cannot copy file
  "/build/source/build/platforminputcontext/libfcitxplatforminputcontextplugin.so"
  to
  "/nix/store/wr3hjs0zry8pphrpjwalgfkgbhkjvf61-qtbase-5.12.3-bin/lib/qt-5.12/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so".
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)


make: *** [Makefile:106: install] Error 1
note: keeping build directory '/tmp/nix-build-fcitx-qt5-1.2.3.drv-1'
builder for '/nix/store/y4szbd4nv02jpn76y04994a8vrayy924-fcitx-qt5-1.2.3.drv' failed with exit code 2
cannot build derivation '/nix/store/sy3swc3ir0slxnn1nk7nixk8bimgyxfh-fcitx-with-plugins-4.2.9.6.drv': 1 dependencies couldn't be built
note: keeping build directory '/tmp/nix-build-neovim-unwrapped-0.3.8.drv-1'
building '/nix/store/pwl8adj7s1b7jysgkasgzhrf47jzqcdp-hwdb.bin.drv'...
building '/nix/store/hgjsf6m833jvwfjadxqd0w6914yqxfvs-nix.conf.drv'...
cannot build derivation '/nix/store/sy7ic06ahid4bzh6qfiz485yzf71jyqa-system-path.drv': 1 dependencies couldn't be built
note: keeping build directory '/tmp/nix-build-nix.conf.drv-1'
note: keeping build directory '/tmp/nix-build-awesome-4.3.drv-1'
note: keeping build directory '/tmp/nix-build-hwdb.bin.drv-0'
note: keeping build directory '/tmp/nix-build-linux-5.1.0-mptcp_v0.96.0.drv-1'
cannot build derivation '/nix/store/rpn24sfm46wakxanbgy5d4fz6il88npr-xsession-wrapper.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hq2530sx0pf27l9iqlwr0k867i89sac7-nixos-system-jedha-19.09.git.4225da7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/hq2530sx0pf27l9iqlwr0k867i89sac7-nixos-system-jedha-19.09.git.4225da7.drv' failed
sudo nixos-rebuild -I  -I nixpkgs=/home/teto/nixpkgs -I  switch  11,44s user 0,90s system 17% cpu 1:10,56 total
```
**To Reproduce**
`nix build libsForQt5.fcitx-qt5  -f ~/nixpkgs `

**Metadata**
nixos unstable

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change

While reviewing another PR, found this was broken due to output path error.

libpinyin was the original derivation that was failing due to the fcitx-qt5 error, I cleaned up an "unused substitutation". Verified the cmake file wasn't making any reference to a fcitx storepath.

EDIT:
Resolves  #65547

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
Can you make `libsForQt5.fcitx-qt5` use `mkDerivaiton` instead of `stdenv.mkDerivation`?

With that this change should be good to merge.

**Comment by jonringer** [comment]
@GrahamcOfBorg build libsForQt5.fcitx-qt5 fcitx-engines.libpinyin

**Review by worldofpeace — APPROVED** [review]

**Comment by teto** [comment]
did you see my comment https://github.com/NixOS/nixpkgs/issues/65547#issuecomment-516009892, setting `qmakeFlags+=" PLUGINDIR=$out/$qtPluginPrefix"` can replace  ```
substituteInPlace platforminputcontext/cmake_install.cmake \
      --replace ${qtbase.out} $out
``` in my short experiment and looks cleaner than a substitute.  Maybe qt5.mkDerivation should set it as well.

**Comment by jonringer** [comment]
in all honesty, i didn't. I made the PR before I saw the issue.

**Comment by worldofpeace** [comment]
I've actually iterated off variants of what you've suggested @teto and that didn't actually fix it.
I'd prefer an actual patch for this, but I think this should be fine since it's consistent with what's done in other packages like this.

**Comment by teto** [comment]
thanks for the fix, I am quite busy now so I just merged it, I will try to push my small fix (first making sure it's a fix xD) later on.

**Comment by Lucus16** [comment]
This build doesn't seem fixed for me, it still fails. When both `.out` and `.bin` are substituted it works fine though.

**Comment by worldofpeace** [comment]
> This build doesn't seem fixed for me, it still fails. When both `.out` and `.bin` are substituted it works fine though.

I've checked this PR out again locally and the build succeeds for me with
`nix-build -A libsForQt5.fcitx-qt5 --check`.

But on https://github.com/NixOS/nixpkgs/commit/525eaf407d4 it does appear broken again,
and that's pretty weird.

Adding another substitution did the trick though
```diff
diff --git a/pkgs/tools/inputmethods/fcitx/fcitx-qt5.nix b/pkgs/tools/inputmethods/fcitx/fcitx-qt5.nix
index ad5b4669498..697c02ee6ab 100644
--- a/pkgs/tools/inputmethods/fcitx/fcitx-qt5.nix
+++ b/pkgs/tools/inputmethods/fcitx/fcitx-qt5.nix
@@ -23,7 +23,8 @@ mkDerivation rec {
 
   preInstall = ''
     substituteInPlace platforminputcontext/cmake_install.cmake \
-      --replace ${qtbase.bin} $out
+      --replace ${qtbase.bin} $out \
+      --replace ${qtbase.out} $out
     substituteInPlace quickphrase-editor/cmake_install.cmake \
       --replace ${fcitx} $out
   '';

```

I'd say it would be best if @teto corrects this or apply the above diff.

**Pull request merged**
