### PR TITLE
eclipse: cleanup (#19723)

### PR DESCRIPTION
**Pull request by goetzst**
###### Motivation for this change

attempt to clean up the mess that is the eclipse management file
Idea:
- sorted packages alpahbetically
- sorted package version (newest first) (makes it easier to add new version)
- added an overview over available eclipse packages
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by NeQuissimus** [comment]
What if we separated the different Eclipses into their own files?

**Comment by groxxda** [comment]
I'm not convinced that this isn't a mess anymore..
Do we really have to keep all the old versions?
I can think of reasons to keep old versions of the __platform__ around, but not for all other eclipse distributions. I'd simply drop them.

Also the header will likely rot very soon :eyes:

**Comment by goetzst** [comment]
> I'm not convinced that this isn't a mess anymore..

Hence the idea of splitting this into different files I guess.

> Do we really have to keep all the old versions?

I'll let you guys fight that out. I'm not that well versed in enterprise usage of legacy packages.

> Also the header will likely rot very soon

Sadly that's probably true. It's also an indication for the fact that the file is still confusing to the point I had to actually add that to give someone a fast way to check how up to date the versions are.

**Comment by groxxda** [comment]
To check how up to date the versions are:
```
nix-env -qaP | grep eclipse
eclipses.eclipse-cpp-36                                   eclipse-cpp-3.6.2
eclipses.eclipse-cpp-37                                   eclipse-cpp-3.7
eclipses.eclipse-cpp-42                                   eclipse-cpp-4.2
eclipses.eclipse-cpp-43                                   eclipse-cpp-4.3.2
eclipses.eclipse-cpp-44                                   eclipse-cpp-4.4.2
eclipses.eclipse-cpp-45                                   eclipse-cpp-4.5.1
eclipses.eclipse-cpp-46                                   eclipse-cpp-4.6.0
jdtsdk                                                    eclipse-JDT-SDK-3.3.2
eclipses.eclipse-modeling-36                              eclipse-modeling-3.6.2
eclipses.eclipse-modeling-46                              eclipse-modeling-4.6
eclipses.eclipse-platform-45                              eclipse-platform-4.5
eclipses.eclipse-platform-451                             eclipse-platform-4.5.1
eclipses.eclipse-platform-452                             eclipse-platform-4.5.2
eclipses.eclipse-platform                                 eclipse-platform-4.6
eclipses.eclipse-scala-sdk-40                             eclipse-scala-sdk-4.0.0
eclipses.eclipse-sdk-35                                   eclipse-sdk-3.5.2
eclipses.eclipse-sdk-36                                   eclipse-sdk-3.6.2
eclipses.eclipse-sdk-37                                   eclipse-sdk-3.7
eclipses.eclipse-sdk-421                                  eclipse-sdk-4.2.1
eclipses.eclipse-sdk-422                                  eclipse-sdk-4.2.2
eclipses.eclipse-sdk-431                                  eclipse-sdk-4.3.1
eclipses.eclipse-sdk-44                                   eclipse-sdk-4.4
eclipses.eclipse-sdk-442                                  eclipse-sdk-4.4.2
eclipses.eclipse-sdk-45                                   eclipse-sdk-4.5
eclipses.eclipse-sdk-451                                  eclipse-sdk-4.5.1
eclipses.eclipse-sdk-452                                  eclipse-sdk-4.5.2
eclipses.eclipse-sdk-46                                   eclipse-sdk-4.6
```
Interestingly, platform is the expression where we only ship one version (at 3 patch levels)..
Since eclipses are not built on hydra, we should probably check which versions don't work anymore.

For example `jdtsdk`'s source is 404......

**Comment by NeQuissimus** [comment]
I would keep `cpp-37`, `cpp-latest` (create from 46), `modeling` (latest), `platform` (latest), `scala-sdk` (and update), `sdk-37` and `sdk-latest` (from 46).

The rest of them should be fine to remove. I would keep the latest 3.x versions to ensure somebody using legacy software does not get bitten by 4.x.

**Comment by groxxda** [comment]
@goetzst are you willing to perform the cleanup? otherwise i'll look into it.

**Comment by goetzst** [comment]
I'll do it, shouldn't be more than deleting some lines. Or do you still want to split each into different files?

**Comment by NeQuissimus** [comment]
Should be fine in one file if we only have 6-7 versions.

**Comment by goetzst** [comment]
OK. I'll clean that up then, do you want me to do the scala update in the same commit as well or should I create an extre PR for that?

**Comment by NeQuissimus** [comment]
Do it all in one PR, separate commits I would suggest.

**Comment by goetzst** [comment]
I removed the header didn't I?

**Comment by goetzst** [comment]
squashed it

**Comment by NeQuissimus** [comment]
Sorry, I clicked the wrong commit, header is gone, yes.

**Comment by goetzst** [comment]
Should have squashed it anyways ^^

**Pull request merged**
