### PR TITLE
vscode-lldb: 1.6.10 -> 1.7.4

### LINKED ISSUE #176697: vscode-extensions.vadimcn.vscode-lldb fails to build
### Steps To Reproduce
1. `nix build nixpkgs#vscode-extensions.vadimcn.vscode-lldb`

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/r76hx9v55jy9qw26fw714k53klinpj43-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/lfx8vn5iarkl3d5b0ayf5avi7pk1sfqh-cmake-build-extension-only.patch
patching file CMakeLists.txt
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/share/doc/CodeLLDB -DCMAKE_INSTALL_INFODIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/include -DCMAKE_INSTALL_SBINDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/cz52w8xf3i1d3xvzpzd9abf7rvpl9017-binutils-2.38/bin/ranlib -DCMAKE_AR=/nix/store/cz52w8xf3i1d3xvzpzd9abf7rvpl9017-binutils-2.38/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/yi49nzrh4qczbrra3xlgw914hajs401g-vscode-extension-vadimcn-vscode-lldb-1.6.10 -DVERSION_SUFFIX= 
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
[0mVersion 1.6.10[0m
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /build/source/build/debuggee
-- Configuring done
-- Generating done
[33mCMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DOCDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_INFODIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_LOCALEDIR
    CMAKE_INSTALL_MANDIR
    CMAKE_INSTALL_NAME_DIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    CMAKE_POLICY_DEFAULT_CMP0025
    CMAKE_SKIP_BUILD_RPATH

[0m
-- Build files have been written to: /build/source/build
cmake: enabled parallel building
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j8 -l8 SHELL=/nix/store/zwjm0gln1vk7x1akpyz0yxjsd1yc46gi-bash-5.1-p16/bin/bash vsix_bootstrap
[ 14%] [34m[1mGenerating extension.js[0m

make[3]: *** [CMakeFiles/extension.dir/build.make:87: extension.js] Error 243
make[2]: *** [CMakeFiles/Makefile2:176: CMakeFiles/extension.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:264: CMakeFiles/vsix_bootstrap.dir/rule] Error 2
make: *** [Makefile:231: vsix_bootstrap] Error 2
```

### Additional context
Stopped working in the past couple of days; not sure exactly when.

### Notify maintainers

@nigelgbanks 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11.20220529.b62ada4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager, nixos"`
 - channels(nick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by NickHu**
###### Description of changes

* Moved npm dependencies out of global `nodePackages` and into a local scope with `node2nix` (this way, updating the package won't require hours to run `./generate.sh`). It wasn't worth having the npm build dependencies in `nodePackages` anyway, as no other package would possibly depend on them.
* Updated LLVM version to https://github.com/vadimcn/llvm-project/tree/codelldb/14.x
	+ Also backported a patch to make LLDB 14 work properly.
* Updater script now doesn't need an argument, and is passed to `passthru.updateScript`. This means that this package can now be automatically updated.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickHu** [comment]
I tested the resulting lldb and it was able to pretty print Rust `Vec` types. However, it didn't seem to print `Option` types at all... Looking at the [manual](https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#rust-language-support), it never says that this is supported...

Does anyone know what the current state of @vadimcn's LLVM fork is? Maybe this is just not supported anymore, and we should be using upstream LLDB 14 instead. @oxalica, perhaps you know?

Also, strangely, running `lldb --version` yields output solely:

```
lldb version 14.0.6
```

so I wasn't able to verify that indeed this derivation builds the codelldb llvm fork, as per:
https://github.com/NickHu/nixpkgs/blob/d8191473dceebb57541ab3b4f5123dbcb40ef1fd/pkgs/applications/editors/vscode/extensions/vscode-lldb/lldb.nix#L27-L31
so it's possible that I didn't override it correctly.

**Comment by NickHu** [comment]
Merging this might fix #160874

**Comment by NickHu** [comment]
Ah, I forgot that `overrideAttrs` doesn't propagate my overriding of `monorepoSrc`, and it was indeed building upstream LLDB 14 previously. https://github.com/NixOS/nixpkgs/pull/191133/commits/018fda22f3d35f913b42e2f233a42bff48cc5f55 addresses this but now it no longer compiles.

**Comment by NickHu** [comment]
I fixed the build, and have verified that the output of `lldb --version` is

```
lldb version 14.0.6
  rust-enabled
```

Should be ready for review now.

**Comment by oxalica** [comment]
`vscode-extensions.vadimcn.vscode-lldb.lldb` now builds the whole LLVM instead of only LLDB, is this intended?

**Comment by NickHu** [comment]
Yes, it's intended. vadimcn's custom LLDB also requires a custom LLVM.

**Pull request merged**
