### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
qtwebengine fails on linux https://hydra.nixos.org/build/110587766

**Comment by FRidh** [comment]
@LnL7 shared-mime-info fails on darwin https://hydra.nixos.org/build/110652935

**Comment by jtojnar** [comment]
Yeah, still https://github.com/NixOS/nixpkgs/pull/74942

**Comment by hedning** [comment]
`qtwebengine` might be a transient failure, I'm was able to build it locally at least.

**Comment by curiousleo** [comment]
I'm keen to see this merged. Is there anything I can help with?

**Pull request merged**
