### PR TITLE
treewide: fix runHook spelling mistakes

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

Found by https://github.com/NixOS/nixpkgs/pull/324444. *When you find a cockroach under the light, there may be countless cockroaches in the dark.*

Even if you do not define these pre and post, as long as you define phase yourself, you should add them. This is for convenience in overriding.

We should probably enforce CI on this.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by AndersonTorres** [comment]
This was/is one of motivations of using modules to define packages.

**Comment by Aleksanaa** [comment]
For others I plan to add them all and enforce CI on it.

**Comment by drupol** [comment]
Why this? https://github.com/NixOS/nixpkgs/compare/f4fb1f5dd286b25689ea7a87bd284cf6e87171d3..b2c8ae28de812c719e91bd074c398e7beb070e40

**Comment by Aleksanaa** [comment]
> Why this? [`f4fb1f5dd286b25689ea7a87bd284cf6e87171d3..b2c8ae28de812c719e91bd074c398e7beb070e40` (compare)](https://github.com/NixOS/nixpkgs/compare/f4fb1f5dd286b25689ea7a87bd284cf6e87171d3..b2c8ae28de812c719e91bd074c398e7beb070e40)

Because this problem is wider than I expected. Many packages aren't just lacking one of runHook, but most are lacking both. I need to come up with a better way to do full treewide changes.

**Comment by drupol** [comment]
But these changes were valid, why not leaving them in?

**Comment by Aleksanaa** [comment]
> But these changes were valid, why not leaving them in?

I don't want to let others go into staging; they are more likely to be fixed in other places and thus causing merge conflicts.

**Comment by AndersonTorres** [comment]
> We should probably enforce CI on this.

This remembers a concept the software engineers call _smell_. Such a repetition of boilerplate code indicates some sneaky problem happening.

**Comment by Aleksanaa** [comment]
> This remembers a concept the software engineers call _smell_. Such a repetition of boilerplate code indicates some sneaky problem happening.

This repo was built by thousands of people. Wherever there is an opportunity for silent mistakes, there are dozens to hundreds of them. The best way is to set boundaries and raise the lower limit.

**Comment by AndersonTorres** [comment]
About CI, a long time ago rmcgibbo created a bot that looked at a PR and ran nixpkgs-hammering over it.
And one of the diagnostics of nixpkgs-hammering was finding runHooks.

Maybe the idea can be resurrected!

**Review by pbsds — APPROVED** [review]

**Comment by pbsds** [comment]
> About CI, a long time ago rmcgibbo created a bot that looked at a PR and ran nixpkgs-hammering over it. And one of the diagnostics of nixpkgs-hammering was finding runHooks.
> 
> Maybe the idea can be resurrected!

I have some stale code somewhere where i ran nixpkgs-hammer on all of nixpkgs. 
https://pvv.ntnu.no/~pederbs/tmp/merged-issues-report-nixpkgs/0396d3b0fb7f/report-hammering.html

It also checked all links to github issues, pull requests and commits to check if it it has been merged and tagged upstream.
https://pvv.ntnu.no/~pederbs/tmp/merged-issues-report-nixpkgs/0396d3b0fb7f/report-upstream.html

I need to revive that at some point, but i've been swamped recently with research work

**Pull request merged**
