### PR TITLE
autoPatchelfHook: add keep_libc flag

### LINKED ISSUE #332533: Build failure: osquery-5.12.2
### Steps To Reproduce

`nix build nixpkgs/50d494e5a4370394af0e09db2a2e864f146ff3b6#legacyPackages.x86_64-linux.osquery`

### Build log

```
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /nix/store/pglcybidbkf4pc3fkiqmjspsfr2xs7h5-osquery-toolchain-bin/usr/bin/clang
-- Check for working C compiler: /nix/store/pglcybidbkf4pc3fkiqmjspsfr2xs7h5-osquery-toolchain-bin/usr/bin/clang - broken
CMake Error at /nix/store/aqckch626lg0vxh41dabyzrq0jx7gdk5-cmake-3.29.6/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/nix/store/pglcybidbkf4pc3fkiqmjspsfr2xs7h5-osquery-toolchain-bin/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-Z4uLEz'
    
    Run Build Command(s): /nix/store/4mwzwdhdiqviz9bsb4i8ngy5j04qkvf5-ninja-1.12.1/bin/ninja -v cmTC_8420a
    [1/2] /nix/store/pglcybidbkf4pc3fkiqmjspsfr2xs7h5-osquery-toolchain-bin/usr/bin/clang    -o CMakeFiles/cmTC_8420a.dir/testCCompiler.c.o -c /build/source/build/CMakeFiles/CMakeScratch/TryCompile-Z4uLEz/testCCompiler.c
    FAILED: CMakeFiles/cmTC_8420a.dir/testCCompiler.c.o 
    /nix/store/pglcybidbkf4pc3fkiqmjspsfr2xs7h5-osquery-toolchain-bin/usr/bin/clang    -o CMakeFiles/cmTC_8420a.dir/testCCompiler.c.o -c /build/source/build/CMakeFiles/CMakeScratch/TryCompile-Z4uLEz/testCCompiler.c
    Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
    ninja: build stopped: subcommand failed.
```
Full log: https://gist.github.com/sgrb/671b2b571d6a38c2755372ce38116906

### Notify maintainers

@znewman01 @nlewo @squalus
### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240708.655a58a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `""`
 - channels(slava): `""`
 - nixpkgs: `/etc/nix/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by squalus**
## Description of changes
    
- Add keep_libc flag to disable the default libc handling. Intended to be used by systemd.
- Add autoPatchelfFlags to autoPatchelfHook for passing arguments to the autoPatchelf script

This reverts part of the change made in #307068 / 80be926.

Fixes #332533

Relevant: #325126

cc @ElvishJerricco @layus 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
This will break systemd initrd, which relies on leaving `glibc` in the rpath of binaries that had it before the autoPatchelfHook.

**Comment by ElvishJerricco** [comment]
actually, it doesn't make sense that `autoPatchelfHook` is causing #332533, because the hook happens in `fixupPhase`, and the error message is in `configurePhase`

**Comment by squalus** [comment]
Updated to accommodate systemd's requirement for different libc handling.

**Comment by squalus** [comment]
Fixes #333710

**Review by ElvishJerricco — COMMENTED** [review]
Other than updating the comment, this looks good to me. I think we can take it out of draft and once the comment is updated we can merge.

**Comment by squalus** [comment]
Added some new comments and adjusted the flag description. I tried to make it easier to understand. Feel free to suggest new language if anything comes to mind.

**Comment by ElvishJerricco** [comment]
@squalus Well, originally, that comment was written to have one numbered bullet point for each of the conditions; the idea being to explain step by step what the loop is doing. So I would have preferred adding another bullet point and clarifying why each of the two libc steps is where it is in the process. Maybe something more like this?

```
            # 1. If a candidate is an absolute path, it is already a
            #    valid dependency if that path exists, and nothing needs
            #    to be done. It should be an error if that path does not exist.
            # 2. If a candidate is found within libc, it should be dropped
            #    and resolved automatically by the dynamic linker, unless
            #    keep_libc is enabled.
            # 3. If a candidate is found in our library dependencies, that
            #    dependency should be added to rpath.
            # 4. If all of the above fail, libc dependencies should still be
            #    considered found. This is in contrast to step 2, because
            #    enabling keep_libc should allow libc to be found in step 3
            #    if possible to preserve its presence in rpath.
```

I dunno. Your call. Whatever you're most happy with is good with me. Just wanted to offer an explanation for why the bullet points were listed that way.

**Comment by squalus** [comment]
@ElvishJerricco Updated to use your suggested language. I think that's more clear. Much appreciated.

**Comment by ElvishJerricco** [comment]
Thanks @squalus! I did a squash merge just to get those comment tweaks all into the one commit.

**Pull request merged**
