### PR TITLE
asciidoc: patchPhase -> postPatch

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116003` at fa6fe18e run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>840 packages marked as broken and skipped:</summary>
  <ul>
    <li>Literate</li>
    <li>OVMF-CSM</li>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>alliance</li>
    <li>ams-lv2</li>
    <li>amule</li>
    <li>amuleDaemon</li>
    <li>amuleGui</li>
    <li>apfelgrid</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>17249 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>Fabric</li>
    <li>MIDIVisualizer</li>
    <li>MMA</li>
    <li>OVMF</li>
    <li>OVMF-secureBoot</li>
    <li>R</li>
    <li>SDL</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>60 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/d27e6f007f7948efd9cd0ecc88f9eb6f">asciidoc</a></li></li>
    <li><a href="https://gist.github.com/d2f9d19cfb47570ba9e8dfed0fc43ffa">cryptsetup</a></li></li>
    <li><a href="https://gist.github.com/04b8eac5352711b179c0d1c2f1609549">desktop-file-utils</a></li></li>
    <li><a href="https://gist.github.com/f14c56209cf4fdbc5ec179f74a5846e1">fontconfig</a></li></li>
    <li><a href="https://gist.github.com/db4f1664c05025bbfdf8408814a644c4">fribidi</a></li></li>
    <li><a href="https://gist.github.com/1bb4d92f66b48f618beeb416948d1ebe">gd</a></li></li>
    <li><a href="https://gist.github.com/a80663eaafe6dfd8dbe139df642274f1">glib</a></li> (gnome2.glib ,gnome3.glib)</li>
    <li><a href="https://gist.github.com/3a4ed427d6faf65839608ebce86abbe0">gtk-doc</a></li> (gnome2.gtkdoc)</li>
    <li><a href="https://gist.github.com/a469a34f273aea47fa6cfff014a9e597">gts</a></li></li>
    <li><a href="https://gist.github.com/0bfd0bacefa945de02564c93ec6610ab">hidapi</a></li></li>
    <li><a href="https://gist.github.com/975e9ff6c7c991bd460730e2aae6660d">libdrm</a></li></li>
    <li><a href="https://gist.github.com/1f18dd7ee81c4b41b3ceabdb86003338">libfido2</a></li></li>
    <li><a href="https://gist.github.com/1917ff546c588f43057dc572ac6d5158">libglvnd</a></li></li>
    <li><a href="https://gist.github.com/2b0527c5cb1111b650ae4939ec016c1b">libmicrodns</a></li></li>
    <li><a href="https://gist.github.com/d9dabe7bf0ce4eca14c919651e4c7912">libsysprof-capture</a></li></li>
    <li><a href="https://gist.github.com/1aaf083b125e692651ecdb3a3becf42f">libusb1</a></li></li>
    <li><a href="https://gist.github.com/a3c7975bc7117a1d9ff536c55ad9a4d1">libva-minimal</a></li></li>
    <li><a href="https://gist.github.com/ac86904f67c1a288610983b445e4acfb">libvdpau</a></li></li>
    <li><a href="https://gist.github.com/f7c5fe04b4f705ce2f15c8ddb335128c">libxkbcommon</a></li> (libxkbcommon_8)</li>
    <li><a href="https://gist.github.com/00a73d63e84028eaabea0e57211f8449">lvm2</a></li></li>
    <li><a href="https://gist.github.com/7d9e5242375753778345fc4b53a2fe13">ninja</a></li></li>
    <li><a href="https://gist.github.com/82d68ea83679d492082942e60b03ad33">openssh</a></li></li>
    <li><a href="https://gist.github.com/b84b89ad681a6cdaedcb6a39db8fd2fc">poppler_data</a></li></li>
    <li><a href="https://gist.github.com/6f6e582f4f23fab570adda51e5716fa9">python38Packages.fontforge</a></li></li>
    <li><a href="https://gist.github.com/b4fe792bba28894766b77b6df84bf89c">shared-mime-info</a></li></li>
    <li><a href="https://gist.github.com/17487ec2a186895fb66aba0694a75db0">systemdMinimal</a></li></li>
    <li><a href="https://gist.github.com/5ea2dacc426dc6cc4a80959a7d7aa791">wayland</a></li></li>
    <li><a href="https://gist.github.com/bd2e673b4e876917d3f5d09324286253">wayland-protocols</a></li></li>
    <li><a href="https://gist.github.com/386dcb94f08b307acdf7df07fe6b531b">xkeyboard_config</a></li> (xorg.xkeyboardconfig)</li>
    <li><a href="https://gist.github.com/a37ec6be3b5f29652e35a1884b3ce9a9">xlibsWrapper</a></li> (xorg.xlibsWrapper)</li>
    <li><a href="https://gist.github.com/14126d7b361d2820a15792c3639a20ce">xorg.libICE</a></li></li>
    <li><a href="https://gist.github.com/78a7122d4f43f64b419eeaeffc3a8849">xorg.libSM</a></li></li>
    <li><a href="https://gist.github.com/9c611d251187215cd78c501420cb53bf">xorg.libX11</a></li></li>
    <li><a href="https://gist.github.com/b1bea629b83784d9cf690f9dfbd5b8c9">xorg.libXScrnSaver</a></li></li>
    <li><a href="https://gist.github.com/9c603537bfbcd17e24fc29a658098a7d">xorg.libXau</a></li></li>
    <li><a href="https://gist.github.com/f3e8fd965dbf3de324d820706be55c12">xorg.libXcomposite</a></li></li>
    <li><a href="https://gist.github.com/4126169daa8cb691c7ca584f8e85e66e">xorg.libXcursor</a></li></li>
    <li><a href="https://gist.github.com/af6677e2f05c296b8b6f3fd6fd8873c7">xorg.libXdamage</a></li></li>
    <li><a href="https://gist.github.com/6db80afe4bcc2e46425b1d83c53b1dd6">xorg.libXdmcp</a></li></li>
    <li><a href="https://gist.github.com/30e9d733c9a2f391ef0b4b48c9d91295">xorg.libXext</a></li></li>
    <li><a href="https://gist.github.com/d669968c188cb16e7d6e269bfad016c1">xorg.libXfixes</a></li></li>
    <li><a href="https://gist.github.com/b622c78de3f398c689461b1ee8cd66f7">xorg.libXft</a></li></li>
    <li><a href="https://gist.github.com/539214b02a9753e5c7d40534accbc265">xorg.libXi</a></li></li>
    <li><a href="https://gist.github.com/5bba68a4c89ca8b38102f336e202f21f">xorg.libXinerama</a></li></li>
    <li><a href="https://gist.github.com/48433b64dff4b11cc4a09ff71ca87976">xorg.libXrandr</a></li></li>
    <li><a href="https://gist.github.com/c434db0439ee7d074bb6015f5070e833">xorg.libXrender</a></li></li>
    <li><a href="https://gist.github.com/57bd86f069455d75a3276d6fa08f4b41">xorg.libXt</a></li></li>
    <li><a href="https://gist.github.com/6eeeddbc04759edb49e20f528939d560">xorg.libXtst</a></li></li>
    <li><a href="https://gist.github.com/2054db51e59c651bebd6ba90a9f7dd78">xorg.libXv</a></li></li>
    <li><a href="https://gist.github.com/5f7400b1f34c9c51cbcdfd5addaf3794">xorg.libXvMC</a></li></li>
    <li><a href="https://gist.github.com/30fbe224339dfa8202dc41ac9bfa8686">xorg.libXxf86vm</a></li></li>
    <li><a href="https://gist.github.com/a06f80f824debae7b20cbf2ecf697b5d">xorg.libxcb</a></li></li>
    <li><a href="https://gist.github.com/8799ec870a49b132d5d5a4068449c093">xorg.libxshmfence</a></li></li>
    <li><a href="https://gist.github.com/453cc8e113578fb1b7b6afe061af70d9">xorg.xcbutil</a></li></li>
    <li><a href="https://gist.github.com/92f68da3e74c9f99d197445d440b5796">xorg.xcbutilimage</a></li></li>
    <li><a href="https://gist.github.com/bb6f6c332c3e4ea71ea2f16fb8f12e30">xorg.xcbutilkeysyms</a></li></li>
    <li><a href="https://gist.github.com/5eb838005ffe61b639979120d03a4683">xorg.xcbutilrenderutil</a></li></li>
    <li><a href="https://gist.github.com/d3f6df29fd753fa69feece8229b9c8f3">xorg.xcbutilwm</a></li></li>
    <li><a href="https://gist.github.com/60f066429d808de9a113160e94191411">xorg.xorgproto</a></li></li>
    <li><a href="https://gist.github.com/562989ae68df4f68a180e9a9dc2d9e3a">zeromq</a></li> (zeromq4)</li>
  </ul>
</details>

**Review by bjornfor — APPROVED** [review]
With this many rebuilds, this should target staging. Otherwise +1.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116003` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>asciidoc</li>
</ul>
</details>

**Pull request merged**
