### PR TITLE
vim plugins: refactor and regenerate

### PR DESCRIPTION
**Pull request by jagajaga**
Now mostly all plugins can be automatically generated.

### CODE REVIEW

**Comment by jagajaga** [comment]
Tested locally. Going to merge this evening.

**Comment by jagajaga** [comment]
@nckx are you ok this that? :)

**Comment by nckx** [comment]
That diff. My eyes.

I'm more than OK with it if it simplifies updates. Why the change to `fetchgit` though? Scripting?

**Comment by jagajaga** [comment]
@nckx because `fetchFromGithub` do not fetch submodules :sad:

**Comment by nckx** [comment]
Ah. Makes sense, now that I think about the implementation... :disappointed:

**Comment by jagajaga** [comment]
@nckx what do you mean?

**Comment by nckx** [comment]
_(Seriously, GitHub? I can't search for "fetchFromGitHub ="?)_

I forgot it's [just a wrapper](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L374) around `fetchurl`. Efficient, but inflexible.

**Comment by jagajaga** [comment]
@nckx around `fetchzip` but that doesn't matter :)

**Comment by nckx** [comment]
s/exams/coffee/g. :coffee:

**Comment by jagajaga** [comment]
@nckx I know that feel, bro :hand:

**Pull request merged**
