### PR TITLE
vscx/ms-vsliveshare-vsliveshare: 1.0.2902 -> 1.0.3629

### PR DESCRIPTION
**Pull request by davegallant**
###### Motivation for this change

This package was months out of date.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112909` at 2c9b6067 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/aa0069bf63d16f3be473429a1f714c5a">vscode-extensions.ms-vsliveshare.vsliveshare</a></li></li>
  </ul>
</details>

**Comment by teto** [comment]
I wonder if it why it stopped working for me. Even with this I can't make it work (it used to).
```
[29243:0212/192431.609953:INFO:CONSOLE(25)] "%cTRACE color: #888 Error: ENOENT: no such file or directory, open '/nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/resources/app/extensions/node_modules/package.json'", source: file:///nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
```
How do you configure it ?

**Comment by Mic92** [comment]
> I wonder if it why it stopped working for me. Even with this I can't make it work (it used to).
> 
> ```
> [29243:0212/192431.609953:INFO:CONSOLE(25)] "%cTRACE color: #888 Error: ENOENT: no such file or directory, open '/nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/resources/app/extensions/node_modules/package.json'", source: file:///nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
> ```
> 
> How do you configure it ?

Sounds like one of the programs is not patchelfd correctly fails to execute. If you setup NIX_LD it might print what program it was trying to execute: https://github.com/Mic92/nix-ld
also `strace -f -e execve` should work.

**Comment by davegallant** [comment]
> I wonder if it why it stopped working for me. Even with this I can't make it work (it used to).
> 
> ```
> [29243:0212/192431.609953:INFO:CONSOLE(25)] "%cTRACE color: #888 Error: ENOENT: no such file or directory, open '/nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/resources/app/extensions/node_modules/package.json'", source: file:///nix/store/15gdwjpd10qnah9ibf22vald3k8x0sng-vscode-1.53.2/lib/vscode/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)
> ```
> 
> How do you configure it ?

You're right. Sharing or joining does not seem to work anymore.

I see this error when trying to join (running with `code --verbose`):

```
[28514:0213/165251.079840:INFO:CONSOLE(618)] "%cTRACE color: #888 CommandService#executeCommand liveshare.joinFromWelcomeContent", source: file:///nix/store/73gcz5gp2cw5bax4xq4kc7w05ys2csc4-vscode-1.53.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (618)
[28514:0213/165251.081206:INFO:CONSOLE(618)] "%c  ERR color: #f33 command 'liveshare.joinFromWelcomeContent' not found: Error: command 'liveshare.joinFromWelcomeContent' not found
    at C._tryExecuteCommand (file:///nix/store/73gcz5gp2cw5bax4xq4kc7w05ys2csc4-vscode-1.53.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:3360)
    at file:///nix/store/73gcz5gp2cw5bax4xq4kc7w05ys2csc4-vscode-1.53.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:3241
    at async c.open (file:///nix/store/73gcz5gp2cw5bax4xq4kc7w05ys2csc4-vscode-1.53.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:619:20963)
    at async d.open (file:///nix/store/73gcz5gp2cw5bax4xq4kc7w05ys2csc4-vscode-1.53.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js:619:22963)", source: file:///nix/store/73gcz5gp2cw5bax4xq4kc7w05ys2csc4-vscode-1.53.0/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (618)
```

**Comment by davegallant** [comment]
Will continue to look into this when time permits.

`vscx/ms-vsliveshare-vsliveshare: 1.0.2902` does not work with vscode > 1.53.

When attempting to authenticate:

image

vscode 1.52.1 still authenticates fine using the older extension.

**Comment by JesusMtnez** [comment]
> Will continue to look into this when time permits.
> 
> `vscx/ms-vsliveshare-vsliveshare: 1.0.2902` does not work with vscode >= 1.53.0.
> 
> When attempting to authenticate:
> 
> image
> 
> `vscx/ms-vsliveshare-vsliveshare: 1.0.2902` still works on vscode 1.52.1.

I am getting the same error trying to use 1.53.1 with liveshare 1.0.3121.

**Comment by jraygauthier** [comment]
Maybe we were a bit prompt to update the vscode package.

Wouldn't it be better if we had a policy to make sure that if one wants to update vscode, he should make sure that at least a minimal set of key companion extensions still work with it, ideally all.

This is the same as making sure that a library's dependee packages still work.

**Comment by jraygauthier** [comment]
Potentially, in the vscode pull request, a checkbox list to companion extensions, with link to newly created issue for each broken extension. Extension maintainers might be added as reviewers to a vscode update PR so that they could help with the job.

**Comment by jraygauthier** [comment]
Otherwise, we get a vscode in unusable state for everyone for some time just to be bleeding edge. I definitely prefer to be functional than bleeding edge.

**Comment by jraygauthier** [comment]
I might take a look at it as well when I get some spare time.

**Comment by teto** [comment]
is there any rule/information regarding the validity of plugins (especially vsliveshare) for vscode ? It seems like Microsoft should be able to tell what versions of liveshare work with what version of vscode. Maybe I am overly optimistic. I thought they were the gods of backwards compatibility.

**Comment by jraygauthier** [comment]
Not certain be it looks like it would be `engines.vscode` in `/nix/store/xxxx-vscode-extensions/share/vscode/extensions/ms-vsliveshare.vsliveshare/package.json`:

```json
{
  "...": {},
  "engines": {
    "vscode": "^1.40.0"
  },
  "...": {},
}
```

**Comment by jraygauthier** [comment]
Might also get some idea looking at the extension's own dependencies (`dependencies` and `devDependencies`) still in the `package.json` file:

```json
{
  "...": {},
  "dependencies": {
    "vscode-debugprotocol": "1.33.0",
    "vscode-extension-telemetry": "0.1.6",
    "vscode-languageserver-protocol": "^3.15.3",
  },
  "devDependencies": {
    "@types/vscode": "1.33.0",
  },
  "...": {}
}
```

(excerpt from the c# extension this time).

**Pull request closed without merging**
