### PR TITLE
hecate: update 0.0.1 -> unstable-2022-05-03

### PR DESCRIPTION
**Pull request by RamKromberg**
updated, viewed and edited a few files on my x86-64.

### CODE REVIEW

**Comment by RamKromberg** [comment]
amended commit title

**Comment by RamKromberg** [comment]
following up on https://github.com/NixOS/nixpkgs/pull/171858, switched to buildGoModule, removed the recursive and the deps.nix.

**Comment by aaronjheng** [comment]
Result of `nixpkgs-review pr 171858` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hecate</li>
  </ul>
</details>

**Review by aaronjheng — APPROVED** [review]

**Comment by RamKromberg** [comment]
closing since it was merged directly in https://github.com/NixOS/nixpkgs/commit/3bcc1359b247fdbe94adf6e72633f91288d329d3

**Pull request closed without merging**
