### PR TITLE
neochat: init at 1.0

### PR DESCRIPTION
**Pull request by mjlbach**
###### Motivation for this change
Neochat is a fork/continuation of spectral and an official KDE project.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Is there a PR for packaging kquickimageeditor that can be cross-linked? Also, this should be marked as a draft in the meantime.

**Comment by mjlbach** [comment]
No PR yet. I was working on one in the process of this and have something locally that I will try to get finished up soon. Thanks for marking it as a draft (I forgot to do that).

**Comment by lovesegfault** [comment]
> No PR yet. I was working on one in the process of this and have something locally that I will try to get finished up soon. Thanks for marking it as a draft (I forgot to do that).

Awesome, feel free to ping me whenever that PR goes up and I'm happy to review/test/merge :)

**Comment by mjlbach** [comment]
@lovesegfault I just pushed everything

**Comment by colemickens** [comment]
Did you already try `mkDerivation`, I have had this suggested to me in the past per the manual: https://nixos.org/manual/nixpkgs/stable/#sec-language-qt but maybe you already tried and then resorted to doing it manually?

**Comment by mjlbach** [comment]
I've updated it to use mkDerivation. I originally used the one from stdenv copying spectral's derivation, I don't think it makes much of a difference. FWIW everything works-ish now apart from icons on non-nixos, and the dark-theme. The QTPLUGIN situation seems to be a known issue with QT packaging and will be resolved by the time this hits nixpkgs-unstable.

**Review by lovesegfault — APPROVED** [review]
LGTM

**Pull request merged**
