### PR TITLE
babelstone-han: 12.1.7 -> 13.0.3

### PR DESCRIPTION
**Pull request by emilazy**
###### Motivation for this change

This font package is currently broken due to the URL pointing to the new version. Not a huge fan of sourcing from an unversioned, breakable link like this, but I guess there's no upstream alternative; Debian caches the source archives, but only has old versions.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilazy** [comment]
(Is there any way to get the `fetchzip` download cached by Hydra, at least, so that the package doesn't break when the font is updated upstream?)

**Comment by emilazy** [comment]
@GrahamcOfBorg build babelstone-han

**Comment by volth** [comment]
Feel free to remove `hydraPlatforms = [];`.
The reason was something like "it is so trivial so there is no reason to build it on hydra"

**Comment by emilazy** [comment]
Updated to allow Hydra builds and also use an Internet Archive snapshot of the zip.

**Review by lukateras — APPROVED** [review]

**Pull request merged**
