### PR TITLE
btcpayserver: 1.3.7 -> 1.4.3

### PR DESCRIPTION
**Pull request by nixbitcoin**
Things done:

* Tested with the [nix-bitcoin VM test](https://gist.github.com/nixbitcoin/13389519fe9ae0a2ee32b2165765d630).

Notes for reviewers: You can verify GPG signatures with `refetch=1 pkgs/applications/blockchains/btcpayserver/update.sh`.

cc @prusnak @erikarvstedt

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build btcpayserver nbxplorer

**Comment by prusnak** [comment]
@GrahamcOfBorg build btcpayserver nbxplorer

**Comment by erikarvstedt** [comment]
The VM test fails for the initial version and for the latest fixup: The `btcpayserver` service exits (with statuc 0) right after starting.

Manual repro inside a nix-bitcoin system:
```
runuser -u btcpayserver -- /nix/store/dngc8vx42wq1qi7y002ifxz026cvx7n7-btcpayserver-1.4.2/bin/btcpayserver --conf='/var/lib/btcpayserver/settings.config' --datadir='/var/lib/btcpayserver'
## Output
info: Configuration:  Data Directory: /var/lib/btcpayserver
info: Configuration:  Configuration File: /var/lib/btcpayserver/settings.config
info: Configuration:  Network: Mainnet
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /var/lib/btcpayserver/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.4.2.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.4.2.0
# Exit with status 0 here
```

**Comment by erikarvstedt** [comment]
Removing line `chains=btc,lbtc` from the btcpayserver config file fixes the service.
So lbct (liquid) support is broken in v1.4.2. I'd wait with the upgrade until this is fixed.

**Comment by nixbitcoin** [comment]
> Removing line `chains=btc,lbtc` from the btcpayserver config file fixes the service. So lbct (liquid) support is broken in v1.4.2. I'd wait with the upgrade until this is fixed.

Yeah, I've been troubleshooting that too. Have you found the issue upstream?

**Comment by erikarvstedt** [comment]
I've [filed a bug report](https://github.com/btcpayserver/btcpayserver/issues/3404).

**Comment by NicolasDorier** [comment]
BTCPayServer doesn't build altcoins support by default, so you need to build with `-C Altcoins-Release`, not `-C Release`. I will make a commit to make the error more user friendly though.

**Comment by NicolasDorier** [comment]
Will make new version today or tomorrow sweeping a few bugs, included the fact you didn't see error message.

**Comment by erikarvstedt** [comment]
@NicolasDorier, thanks for looking into this. The actual bug was in @nixbitcoin's VM test script which didn't properly set `Altcoins-Release`, but this in turn uncovered the log printing bug in btcpayserver.

**Comment by erikarvstedt** [comment]
@NicolasDorier, altcoin support is [disabled by default](https://github.com/NixOS/nixpkgs/blob/bb96e481b317c770281c1bfd9e6face9bfe0888f/pkgs/applications/blockchains/btcpayserver/default.nix#L2) in nixpkgs. In [nix-bitcoin](https://github.com/fort-nix/nix-bitcoin), it's only enabled when liquid (lbtc) support is required.

**Comment by erikarvstedt** [comment]
[Fixup](https://github.com/erikarvstedt/nixpkgs/commits/btcpayserver-1.4.2-ea-2).
This makes the [VM test](https://gist.github.com/c2fcb4562b3b1fd4d5a8e61d4fdf5aec) succeed.
@nixbitcoin, please always run the test before pushing.

**Comment by nixbitcoin** [comment]
Yes, I will be careful about that in the future. I have updated the [original VM test link](https://gist.github.com/nixbitcoin/13389519fe9ae0a2ee32b2165765d630) and it now runs smoothly.

**Review by erikarvstedt — APPROVED** [review]
* [X] The [VM test](https://gist.github.com/nixbitcoin/13389519fe9ae0a2ee32b2165765d630) succeeds :sparkles:

**Comment by NicolasDorier** [comment]
I bumped to 1.4.4 which at least fix the issue of not seeing proper error message if configuration isn't good.

**Pull request merged**
