### PR TITLE
syncthing-gtk: 0.9.2.3 → 0.9.2.7

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
* Move from python-packages to applications
* Some clean ups
* Patch to always use the syncthing binary from nixpkgs – by default, it saves the syncthing path to a config file on first run, which, of course, breaks after update+GC.
* Update to latest version

I was not able to test it fully due to https://github.com/syncthing/syncthing-gtk/issues/379 but it starts at least.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Also syncthing is started on my machine, syncthing-gtk freezes as in the screenshot 
https://dl.thalheim.io/gFnXsN-MjNYWWdmSELIjXw/2017-11-25.vkuux.png

```
(.syncthing-gtk-wrapped:8655): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
I StatusIcon    Using backend StatusIconGTK3 (primary)
(.syncthing-gtk-wrapped:8655): Gtk-WARNING **: Invalid icon size 24
(.syncthing-gtk-wrapped:8655): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/nix/store/m8r32mfxj7xp5k365zk3prjz1fj95i2c-syncthing-gtk-0.9.2.7/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 413, in _rest_connected
    con = sc.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/nix/store/m8r32mfxj7xp5k365zk3prjz1fj95i2c-syncthing-gtk-0.9.2.7/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 413, in _rest_connected
    con = sc.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/nix/store/m8r32mfxj7xp5k365zk3prjz1fj95i2c-syncthing-gtk-0.9.2.7/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 413, in _rest_connected
    con = sc.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
/nix/store/8j8fm38dndhiwillqqr0rahavhdclsjl-python2.7-pygobject-3.24.1/lib/python2.7/site-packages/gi/module.py:178: Warning: cannot register existing type 'RsvgHandle'
  g_type = info.get_g_type()
/nix/store/8j8fm38dndhiwillqqr0rahavhdclsjl-python2.7-pygobject-3.24.1/lib/python2.7/site-packages/gi/module.py:178: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/nix/store/8j8fm38dndhiwillqqr0rahavhdclsjl-python2.7-pygobject-3.24.1/lib/python2.7/site-packages/gi/module.py:212: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
/nix/store/8j8fm38dndhiwillqqr0rahavhdclsjl-python2.7-pygobject-3.24.1/lib/python2.7/site-packages/gi/module.py:226: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  g_type.pytype = wrapper
/nix/store/8j8fm38dndhiwillqqr0rahavhdclsjl-python2.7-pygobject-3.24.1/lib/python2.7/site-packages/gi/module.py:226: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  g_type.pytype = wrapper
```

Do I need to share a folder to sync first?

**Comment by jtojnar** [comment]
@Mic92 Starting the daemon is expected. Sharing a folder should not be necessary. For me, the app freezes even on Ubuntu, it probably communicates with the daemon on the UI thread or something.

**Comment by jtojnar** [comment]
@thanegill, @jokogr I see you have touched this package previously, could you please test this changes?

**Comment by fpletz** [comment]
I've rebased this PR to master and `syncthing-gtk` seems to work for me. It starts the daemon and I can change settings. The icons are broken though.

@jtojnar Should we just merge this instead of #34277?

**Comment by jtojnar** [comment]
I think the icons would be broken in the other PR as well.

Yes, if it works, I would prefer merging this one since it has more fixes.

**Comment by cumber** [comment]
Thanks! I was going to suggest just merging this instead of my PR.

I can confirm that syncthing-gtk built from master now works. I get a bunch of messages on stderr about icons, but in the GUI everything still looks the way I expected it to (I use syncthing-gtk regularly); I don't think that's new, and it doesn't seem to matter.

**Comment by FRidh** [comment]
For next time, please consider squashing certain commits. In this case it adds quite some noise to the Nixpkgs history.

**Pull request merged**
