### PR TITLE
vagrant: 1.9.5 -> 2.0.0

### PR DESCRIPTION
**Pull request by zzamboni**
Upgrade to latest version of Vagrant.

After installation, the following messages appear whenever vagrant runs.
These were already present in previous versions, I'm not sure if/what
to do about them:

```
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
Ignoring wdm-0.1.1 because its extensions are not built.  Try: gem pristine wdm --version 0.1.1
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
I don't see those message with vagrant 1.9.5 on NixOS, but I do with 2.0.0.

**Comment by Mic92** [comment]
Is it possible that those extensions have shared libraries, which are needed to be patched with patchelf?

**Comment by Mic92** [comment]
It looks like ruby 2.3 is now required as the gems are built against `libruby.so.2.3`.

**Comment by Mic92** [comment]
Now the warning messages are gone.

**Comment by zzamboni** [comment]
Thanks for merging - unfortunately I still see the warnings. I am testing this on Darwin (macOS 10.12.6).

There seems to be some problem with linking some of the libraries. For example, the symlink created for libffi is broken:

```
file /nix/store/ciazr0b6ms2blnsli9p92g7axkjqdxyx-vagrant-2.0.0/embedded/lib/libffi.so.6 
/nix/store/ciazr0b6ms2blnsli9p92g7axkjqdxyx-vagrant-2.0.0/embedded/lib/libffi.so.6: broken symbolic link to /nix/store/yx68gbvss8sy0wl2bqi1xc4qqk3prip3-libffi-3.2.1/lib/libffi.so.6
```

Library files in Darwin have extension `.dylib`:

```
ls /nix/store/yx68gbvss8sy0wl2bqi1xc4qqk3prip3-libffi-3.2.1/lib
libffi.6.dylib	libffi.dylib  libffi.la
```

However, simply changing the `ln -s` command at [line 120](https://github.com/zzamboni/nixpkgs/blob/eb8e0eb3520e9f8b45726d382d70670b731a130d/pkgs/development/tools/vagrant/default.nix#L120) doesn't fix it.

Any ideas? I'm afraid I'm still too inexperienced at writing Nix packages to be able to debug this.

**Comment by zzamboni** [comment]
For reference, I saw some similar messages being reported in https://github.com/NixOS/nixpkgs/pull/27293.

**Comment by Mic92** [comment]
Yeah this symlink is non-sense on darwin because darwin does use a different library extension.

**Comment by zzamboni** [comment]
@Mic92 I realized that if we just use the libraries and binaries included with Vagrant instead of replacing them with Nix's (i.e. comment out https://github.com/zzamboni/nixpkgs/blob/master/pkgs/development/tools/vagrant/default.nix#L69-L120), then all the errors go away. Is there a good reason not to do this? Since Vagrant is distributed with all the tools it needs, as long as they are contained within its own installation and used only by itself, why not leave them like this?

**Comment by Mic92** [comment]
@zzamboni you could probably make this assumption on os x to get it working. On NixOS we have to patch libraries anyway, so replacing seems the better choice since we get a control regarding security updates and a smaller package.

**Pull request merged**
