### PR TITLE
tinyproxy: init at 1.8.4

### PR DESCRIPTION
**Pull request by carlosdagos**
###### Motivation for this change

Tinyproxy is great 😄 

This _should_ compile for all platforms.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build tinyproxy

**Comment by xeji** [comment]
Looks like building the manpages fails.

**Review by xeji — CHANGES_REQUESTED** [review]
fix failing builds

**Comment by carlosdagos** [comment]
Thanks for reviewing @xeji, I’ll revisit this and fix the manpages issue

**Comment by xeji** [comment]
Please also make sure you build packages locally with sandboxing enabled. This makes it much more likely that if it builds locally, it will also build on our CI.

**Comment by carlosdagos** [comment]
Managed to reproduce by turning off my internet connection:

```a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/nix/store/s2xd83mkhjmck3jf491mq96ygnrg2q4x-asciidoc-8.6.9/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/nix-build-tinyproxy-1.8.4.drv-0/source/docs/man5/tinyproxy.conf.xml" returned non-zero exit status 5
```

It happens because xsltproc can't find some DTDs (apparently) and reaches to the internet to get them. However just adding a nonet option and a native dependency on docbook_xsl should fix it (testing locally seems fine using NixOS).

Thanks again @xeji

**Comment by xeji** [comment]
@GrahamcOfBorg build tinyproxy

**Comment by xeji** [comment]
Thank you, LGTM now.

> Managed to reproduce by turning off my internet connection:

That's one reason to enable sandboxed builds on your local machine. The sandbox denies network access, so you would have caught this error right away.

**Review by xeji — APPROVED** [review]

**Pull request merged**
