### PR TITLE
wire-desktop: do not force wayland platform in gappsWrapperArgs

### PR DESCRIPTION
**Pull request by MangoIV**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
This unfortunately still does not work.

**Comment by MangoIV** [comment]
I'm confused how gitkraken works then... hmmm, I guess I really need to set up an X env I guess?

**Comment by JohnRTitor** [comment]
You can just set `WAYLAND_DISPLAY` env var to nothing temporarily and run it. It would fall back to XWayland.

**Comment by JohnRTitor** [comment]
CC @jtojnar, as it could be a gapps issue (hopefully not)

**Comment by MangoIV** [comment]
wait it does work for me with `xwayland-satellite`

**Comment by MangoIV** [comment]
to reproduce: 
```bash
xwayland-satellite & 
DISPLAY=:0 NIXOS_OZONE_WL= result/bin/wire-desktop
```
works

**Comment by MangoIV** [comment]
>  It would fall back to XWayland.

my compositor doesn't implement xwayland. I don't use any X apps.

**Comment by MangoIV** [comment]
@JohnRTitor I think you also have to reset `NIXOS_OZONE_WL` when you're testing it.

**Comment by MangoIV** [comment]
> wait it does work for me with xwayland-satellite

You can also see it's xwayland because it looks like someone ran the pixels through a blur filter first :P

**Comment by MangoIV** [comment]
so from my personal testing I think this should work fine on both X and wayland.

**Comment by JohnRTitor** [comment]
> You can also see it's xwayland because it looks like someone ran the pixels through a blur filter first :P

You should run something like `xeyes` (available as `xorg.xeyes`) then move your cursor over the window you want to check. If the eyes are moving, that window is running under X or XWayland, if the eyes are still, it's running under Wayland.

**Comment by JohnRTitor** [comment]
> @JohnRTitor I think you also have to reset `NIXOS_OZONE_WL` when you're testing it.

Same thing. 

image

**Comment by MangoIV** [comment]
> If the eyes are moving, that window is running under X or XWayland, if the eyes are still, it's running under Wayland.

eyes are moving, very scary, hahahaha

**Comment by MangoIV** [comment]
```bash
DISPLAY=:0 NIXOS_OZONE_WL= WAYLAND_DISPLAY= nix run github:nixos/nixpkgs/refs/pull/346189/merge#wire-desktop
```

so this works perfectly fine for me. it also changes resolution in comparison to the wayland version. I don't know what is different between our environments.

**Comment by jtojnar** [comment]
[`${parameter:+word}` bash syntax](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) only expands to word when parameter is set to non-empty. So unless you have `NIXOS_OZONE_WL=1` set, it will not be used.

**Comment by MangoIV** [comment]
@jtojnar thanks for the heads up, yes, we do not expect it to be used because we tried to run it under X, not under wayland :)

**Comment by jtojnar** [comment]
Well, on X it should not expand because `WAYLAND_DISPLAY` won't be set.

**Comment by MangoIV** [comment]
> Well this could be a me specific/Hyprland issue with XWayland.

or some general issue with different envs? I kinda would like to see this resolved before merging, I don't want to cause any further troubles. Else we will probably really have to revert the original change like @toonn proposed.

**Comment by MangoIV** [comment]
thanks for all your troubles though, @JohnRTitor  <3

**Comment by jtojnar** [comment]
I think `--ozone-platform=wayland` is there intentionally so only the change to shell wrapper should remain.

Ideally, `makeBinaryWrapper` would fail loudly when passed a shell code to `--add-flags` but it cannot really know if we want to pass a shell code to it. So the only option I see to fix this wart is deprecating `--add-flags` and introducing two separate `--add-raw-flags` and `--add-quoted-flags`, where `makeBinaryWrapper` would fail with the former.

**Comment by MangoIV** [comment]
> I think --ozone-platform=wayland is there intentionally so only the change to shell wrapper should remain.

it was there intentionally but I tried to do what gitkraken does and it works fine without so I thought I'd roll with it :)

**Comment by toonn** [comment]
Nixpkgs-review and ofBorg seem to agree that these changes don't cause a rebuild, not sure what that's about.

I checked out the PR branch, merged master into it manually and built wire-desktop and now the program opens to the login prompt so the fix seems to be working :+1:

**Comment by MangoIV** [comment]
@1e-1xer could you perhaps give this a try?

**Comment by toonn** [comment]
I tried on X, let's just merge.

**Pull request merged**
