### PR TITLE
i3blocks: 1.4 -> unstable-2019-02-07

### PR DESCRIPTION
**Pull request by ilikeavocadoes**
###### Motivation for this change

Updated i3blocks. The maintainer has stopped publishing releases (last one was 4 years ago), but develops the project actively. Since I'm updating to a commit in the master branch of the project, rather than  a new version number, what should I put as the commit message and version for the package?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by CrazedProgrammer** [comment]
The standard way to do it would be `version = "unstable-YYYY-MM-DD";`, and the commit message `i3blocks: 1.4 -> unstable-YYYY-MM-DD`, with the date referring to the date that the commit was made.

**Review by matthiasbeyer — APPROVED** [review]
I did:

```
git fetch https://github.com/ilikeavocadoes/nixpkgs i3blocks
git checkout FETCH_HEAD
nix-build -A i3blocks
```

And it worked.

**Comment by ilikeavocadoes** [comment]
I updated the version field to `unstable-2019-02-07`. If there is no other suggestions for improvements, this is ready to merge.

**Comment by OlivierMarty** [comment]
What happened to the scripts?

**Comment by OlivierMarty** [comment]
Ah, I see they were removed from upstream: https://github.com/vivien/i3blocks/commit/0e395b983a21b074c6365e34d96865334b994f4b.
I'll consider packaging i3blocks-contrib.

**Pull request merged**
