### PR TITLE
MINC ecosystem

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Motivation for this change

Adds and updates a large set of tools for working with MINC imaging data in several commits, most but not all logically self-contained.  Updates the stale #29782.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [NA] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [NA] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build ezminc minc_tools mni_autoreg arguments bicpl libminc ants EBTKS c3d elastix perlPackages.TextFormat oobicpl minc_widgets perlPackages.MNI-Perllib itk n3 inormalize
```

**Comment by Mic92** [comment]
`c3d` fails on all targets.

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build c3d
```

**Comment by Mic92** [comment]
c3d seems also broken on master : https://hydra.nixos.org/build/72335751/nixlog/2

**Comment by bcdarwin** [comment]
I have tried building c3d from updated sources but the same issue occurs.  Perhaps it should be marked broken for now?

**Comment by Mic92** [comment]
@bcdarwin seems reasonable.

**Comment by Mic92** [comment]
What is the case regarding `elastix`?

**Comment by bcdarwin** [comment]
Elastix updated, build successfully now.

**Comment by bcdarwin** [comment]
@mic92 -- this pull request is going stale again already; is there anything remaining preventing it from being merged?

**Comment by bcdarwin** [comment]
Thanks!!

**Pull request merged**
