### PR TITLE
python312Packages.xarray: 2024.09.0 -> 2024.10.0

### PR DESCRIPTION
**Pull request by natsukium**
Diff: https://github.com/pydata/xarray/compare/refs/tags/v2024.09.0...v2024.10.0

Changelog: https://github.com/pydata/xarray/blob/refs/tags/v2024.10.0/doc/whats-new.rst

preparation for numpy2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 353062` at 60d18ed7 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>tts</li>
  </ul>
</details>
<details>
  <summary>:x: 67 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/46ca5cc4e5c01e6841edc8e3e4791471">private-gpt</a></li>
    <li><a href="https://gist.github.com/natsukium/ef1ffa92ac146da2dff149ff42c6fa27">python311Packages.ax-platform</a></li>
    <li>python311Packages.cltk</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-huggingface</li>
    <li>python311Packages.llama-index-embeddings-ollama</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-graph-stores-nebula</li>
    <li>python311Packages.llama-index-graph-stores-neo4j</li>
    <li>python311Packages.llama-index-graph-stores-neptune</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-llms-ollama</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai-like</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-readers-database</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-s3</li>
    <li>python311Packages.llama-index-readers-twitter</li>
    <li>python311Packages.llama-index-readers-txtai</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-google</li>
    <li>python311Packages.llama-index-vector-stores-postgres</li>
    <li>python311Packages.llama-index-vector-stores-qdrant</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.multiscale-spatial-image</li>
    <li>python311Packages.private-gpt</li>
    <li><a href="https://gist.github.com/natsukium/e20846fffb84617d1b5b21e1f00d943d">python311Packages.pygmt</a></li>
    <li>python311Packages.rio-tiler</li>
    <li><a href="https://gist.github.com/natsukium/3a3fac991633d16b9d9e5d5129c710bf">python311Packages.rioxarray</a></li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.sumo</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textnets</li>
    <li><a href="https://gist.github.com/natsukium/35ca3b7627b2fa10d8115b8cd61ebd0d">python311Packages.vega</a></li>
    <li><a href="https://gist.github.com/natsukium/c6318364847a6d3ef3fd5478a50d8cd1">python311Packages.wandb</a></li>
    <li><a href="https://gist.github.com/natsukium/7019596ec0d0ffead4a47ec9a235775c">python311Packages.wrf-python</a></li>
    <li><a href="https://gist.github.com/natsukium/609f42b95967c108e96e58adae254859">python311Packages.xarray-datatree</a></li>
    <li><a href="https://gist.github.com/natsukium/0d3ef4b60a4e1a40051c833e542c4140">python312Packages.ax-platform</a></li>
    <li>python312Packages.multiscale-spatial-image</li>
    <li><a href="https://gist.github.com/natsukium/c9343839a76ffe3424bd21ad47f9ce41">python312Packages.opensfm</a></li>
    <li><a href="https://gist.github.com/natsukium/28bd3ed521b12cc6974a699a7781ab53">python312Packages.private-gpt</a></li>
    <li><a href="https://gist.github.com/natsukium/d7a2f8470719f0b5620af983247d6232">python312Packages.pygmt</a></li>
    <li>python312Packages.rio-tiler</li>
    <li><a href="https://gist.github.com/natsukium/2b49737a57dc76e317d4f7efb80f635b">python312Packages.rioxarray</a></li>
    <li>python312Packages.sumo</li>
    <li><a href="https://gist.github.com/natsukium/5899b490155b1561ec7ef57925e65d10">python312Packages.vega</a></li>
    <li><a href="https://gist.github.com/natsukium/38c98928cf7eac2fcf4c5ca28def7bf3">python312Packages.wrf-python</a></li>
    <li><a href="https://gist.github.com/natsukium/cb7e758d629b3380ed6e58208ab208cc">python312Packages.xarray-datatree</a></li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 209 packages built:</summary>
  <ul>
    <li>apkleaks</li>
    <li>checkov</li>
    <li>cve-bin-tool</li>
    <li>das</li>
    <li>deeptools</li>
    <li>hp2p</li>
    <li>jadx</li>
    <li>mapproxy</li>
    <li>prowler</li>
    <li>python311Packages.altair</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.basemap</li>
    <li>python311Packages.bqplot</li>
    <li>python311Packages.bqscales</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.catboost</li>
    <li>python311Packages.cf-xarray</li>
    <li>python311Packages.chart-studio</li>
    <li>python311Packages.cmdstanpy</li>
    <li>python311Packages.compressai</li>
    <li>python311Packages.corner</li>
    <li>python311Packages.cufflinks</li>
    <li>python311Packages.dash</li>
    <li>python311Packages.dash-bootstrap-components</li>
    <li>python311Packages.dask-expr</li>
    <li>python311Packages.dask-ml</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.experiment-utilities</li>
    <li>python311Packages.explorerscript</li>
    <li>python311Packages.flowmc</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.geodatasets</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geoparquet</li>
    <li>python311Packages.gradio</li>
    <li>python311Packages.hvplot</li>
    <li>python311Packages.igraph</li>
    <li>python311Packages.inequality</li>
    <li>python311Packages.intake</li>
    <li>python311Packages.ipydatawidgets</li>
    <li>python311Packages.kmapper</li>
    <li>python311Packages.labelbox</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.leidenalg</li>
    <li>python311Packages.libpysal</li>
    <li>python311Packages.mapclassify</li>
    <li>python311Packages.meshtastic</li>
    <li>python311Packages.momepy</li>
    <li>python311Packages.morecantile</li>
    <li>python311Packages.narwhals</li>
    <li>python311Packages.niaarm</li>
    <li>python311Packages.nutpie</li>
    <li>python311Packages.opensfm</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmpythontools</li>
    <li>python311Packages.pandantic</li>
    <li>python311Packages.pandas-stubs</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.plotly</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.prophet</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-pipeline</li>
    <li>python311Packages.pymatgen</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pyproj</li>
    <li>python311Packages.qcodes</li>
    <li>python311Packages.qcodes-contrib-drivers</li>
    <li>python311Packages.reflex</li>
    <li>python311Packages.scikit-tda</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.skops</li>
    <li>python311Packages.skytemple-dtef</li>
    <li>python311Packages.skytemple-files</li>
    <li>python311Packages.skytemple-ssb-debugger</li>
    <li>python311Packages.spatial-image</li>
    <li>python311Packages.streamlit</li>
    <li>python311Packages.streamz</li>
    <li>python311Packages.synergy</li>
    <li>python311Packages.traittypes</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.xarray</li>
    <li>python311Packages.xarray-dataclasses</li>
    <li>python311Packages.xarray-einstats</li>
    <li>python312Packages.altair</li>
    <li>python312Packages.arviz</li>
    <li>python312Packages.basemap</li>
    <li>python312Packages.bqplot</li>
    <li>python312Packages.bqscales</li>
    <li>python312Packages.bsuite</li>
    <li>python312Packages.cartopy</li>
    <li>python312Packages.catboost</li>
    <li>python312Packages.cf-xarray</li>
    <li>python312Packages.chart-studio</li>
    <li>python312Packages.cmdstanpy</li>
    <li>python312Packages.compressai</li>
    <li>python312Packages.corner</li>
    <li>python312Packages.cufflinks</li>
    <li>python312Packages.dash</li>
    <li>python312Packages.dash-bootstrap-components</li>
    <li>python312Packages.dask-expr</li>
    <li>python312Packages.dask-ml</li>
    <li>python312Packages.datashader</li>
    <li>python312Packages.experiment-utilities</li>
    <li>python312Packages.explorerscript</li>
    <li>python312Packages.fastai</li>
    <li>python312Packages.folium</li>
    <li>python312Packages.geodatasets</li>
    <li>python312Packages.geopandas</li>
    <li>python312Packages.geoparquet</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.hvplot</li>
    <li>python312Packages.igraph</li>
    <li>python312Packages.inequality</li>
    <li>python312Packages.intake</li>
    <li>python312Packages.ipydatawidgets</li>
    <li>python312Packages.k-diffusion</li>
    <li>python312Packages.kmapper</li>
    <li>python312Packages.labelbox</li>
    <li>python312Packages.layoutparser</li>
    <li>python312Packages.leidenalg</li>
    <li>python312Packages.libpysal</li>
    <li>python312Packages.llama-index</li>
    <li>python312Packages.llama-index-agent-openai</li>
    <li>python312Packages.llama-index-cli</li>
    <li>python312Packages.llama-index-core</li>
    <li>python312Packages.llama-index-embeddings-gemini</li>
    <li>python312Packages.llama-index-embeddings-google</li>
    <li>python312Packages.llama-index-embeddings-huggingface</li>
    <li>python312Packages.llama-index-embeddings-ollama</li>
    <li>python312Packages.llama-index-embeddings-openai</li>
    <li>python312Packages.llama-index-graph-stores-nebula</li>
    <li>python312Packages.llama-index-graph-stores-neo4j</li>
    <li>python312Packages.llama-index-graph-stores-neptune</li>
    <li>python312Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python312Packages.llama-index-legacy</li>
    <li>python312Packages.llama-index-llms-ollama</li>
    <li>python312Packages.llama-index-llms-openai</li>
    <li>python312Packages.llama-index-llms-openai-like</li>
    <li>python312Packages.llama-index-multi-modal-llms-openai</li>
    <li>python312Packages.llama-index-program-openai</li>
    <li>python312Packages.llama-index-question-gen-openai</li>
    <li>python312Packages.llama-index-readers-database</li>
    <li>python312Packages.llama-index-readers-file</li>
    <li>python312Packages.llama-index-readers-json</li>
    <li>python312Packages.llama-index-readers-llama-parse</li>
    <li>python312Packages.llama-index-readers-s3</li>
    <li>python312Packages.llama-index-readers-twitter</li>
    <li>python312Packages.llama-index-readers-txtai</li>
    <li>python312Packages.llama-index-readers-weather</li>
    <li>python312Packages.llama-index-vector-stores-chroma</li>
    <li>python312Packages.llama-index-vector-stores-google</li>
    <li>python312Packages.llama-index-vector-stores-postgres</li>
    <li>python312Packages.llama-index-vector-stores-qdrant</li>
    <li>python312Packages.llama-parse</li>
    <li>python312Packages.mapclassify</li>
    <li>python312Packages.meshtastic</li>
    <li>python312Packages.momepy</li>
    <li>python312Packages.morecantile</li>
    <li>python312Packages.narwhals</li>
    <li>python312Packages.niaarm</li>
    <li>python312Packages.nutpie</li>
    <li>python312Packages.optuna</li>
    <li>python312Packages.orange3</li>
    <li>python312Packages.osmnx</li>
    <li>python312Packages.osmpythontools</li>
    <li>python312Packages.pandantic</li>
    <li>python312Packages.pandas-stubs</li>
    <li>python312Packages.pdfplumber</li>
    <li>python312Packages.plotly</li>
    <li>python312Packages.plotnine</li>
    <li>python312Packages.prophet</li>
    <li>python312Packages.pyannote-audio</li>
    <li>python312Packages.pyannote-pipeline</li>
    <li>python312Packages.pymatgen</li>
    <li>python312Packages.pyproj</li>
    <li>python312Packages.qcodes</li>
    <li>python312Packages.qcodes-contrib-drivers</li>
    <li>python312Packages.reflex</li>
    <li>python312Packages.scikit-tda</li>
    <li>python312Packages.skops</li>
    <li>python312Packages.skytemple-dtef</li>
    <li>python312Packages.skytemple-files</li>
    <li>python312Packages.skytemple-ssb-debugger</li>
    <li>python312Packages.spacy</li>
    <li>python312Packages.spacy-loggers</li>
    <li>python312Packages.spacy-lookups-data</li>
    <li>python312Packages.spacy-transformers</li>
    <li>python312Packages.spatial-image</li>
    <li>streamlit (python312Packages.streamlit)</li>
    <li>python312Packages.streamz</li>
    <li>python312Packages.synergy</li>
    <li>python312Packages.textacy</li>
    <li>python312Packages.textnets</li>
    <li>python312Packages.traittypes</li>
    <li>python312Packages.wandb</li>
    <li>python312Packages.wktutils</li>
    <li>python312Packages.xarray</li>
    <li>python312Packages.xarray-dataclasses</li>
    <li>python312Packages.xarray-einstats</li>
    <li>quark-engine</li>
    <li>skytemple</li>
    <li>theharvester</li>
    <li>tocpdf</li>
    <li>whisper-ctranslate2</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
Thanks for the detailed nixpkgs-review report :). I'll add that the following packages are indeed regressions according to `hydra-check`:

```
python311Packages.dalle-mini
python311Packages.fastai
python311Packages.k-diffusion
python311Packages.llama-index-agent-openai
python311Packages.llama-index-cli
python311Packages.llama-index-core
python311Packages.llama-index-embeddings-huggingface
python311Packages.llama-index-embeddings-ollama
python311Packages.llama-index-embeddings-openai
python311Packages.llama-index-llms-openai
python311Packages.llama-index-program-openai
python311Packages.llama-index-readers-database
python311Packages.llama-index-readers-file
python311Packages.llama-index-readers-twitter
python311Packages.llama-index-vector-stores-postgres
python311Packages.llama-index-vector-stores-qdrant
python311Packages.multiscale-spatial-image
python311Packages.skrl
python311Packages.spacy
python311Packages.spacy-loggers
python311Packages.spacy-lookups-data
python311Packages.spacy-transformers
python311Packages.textacy
python311Packages.textnets
python311Packages.wandb
python311Packages.xarray-datatree
python312Packages.multiscale-spatial-image
python312Packages.xarray-datatree
```

Among the above, the direct dependencies of `xarray` are:

```
python311Packages.multiscale-spatial-image
python311Packages.xarray-datatree
python312Packages.multiscale-spatial-image
python312Packages.xarray-datatree
```

And `xarray-datatree` can be removed, see https://github.com/xarray-contrib/datatree/releases . And `multiscale-spatial-image` should accommodate to not require it. See https://github.com/spatial-image/multiscale-spatial-image/issues/93 and https://github.com/spatial-image/multiscale-spatial-image/pull/94 . Let's give them a few days to test https://github.com/spatial-image/multiscale-spatial-image/pull/94 .

**Comment by bcdarwin** [comment]
[multiscale-spatial-image 2.0.0 is out](https://github.com/spatial-image/multiscale-spatial-image/releases/tag/v2.0.0)

**Comment by doronbehar** [comment]
Thanks, I think this should be good to go when CI is green.

**Comment by natsukium** [comment]
Thank you!

**Comment by vcunat** [comment]
xarray started to fail some tests, on current `staging-next` branch:
https://hydra.nixos.org/build/281978858/nixlog/1/tail

**Pull request merged**
