### PR TITLE
Refactor alsa-project programs

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
You forgot references in `nixos/**`; apparently they caused evaluation issues: 2ee7814 (unfortunately not discovered by CI)

**Comment by AndersonTorres** [comment]
Oh, my apologies. I have restricted the ripgreps to `pkgs` directory.

But hey, the `aliases.nix` file didn't cover it?

**Comment by vcunat** [comment]
I'm not sure.  Some places run with `allowAliases = false` by default, I suspect.

**Comment by maralorn** [comment]
This PR modified hackage-packages.nix which is an auto-generated file. I only realized by accident that this breaks a number haskellPackages. We will need to change the alias in cabal2nix.

**Comment by drupol** [comment]
Hi, is this something we need to backport to `release-21.05`

**Comment by sternenseemann** [comment]
No, these are breaking changes we should not backport. We could potentially add the new names as aliases for those looking to ease the transition to 21.11.

**Comment by drupol** [comment]
Good, this is what I was expecting. I added a note about that in https://github.com/NixOS/nixpkgs/pull/128484 !

**Pull request merged**
