### PR TITLE
Basic Darwin->Darwin cross support

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

First batch of cleaned-up up history from https://github.com/NixOS/nixpkgs/pull/24983#issuecomment-295479704

Should not change any native hashes, but may break some Haskell cross compiling --- I hope that's OK otherwise there's just going to be too much to merge at once.

Depends on https://github.com/NixOS/nixpkgs/pull/25044 for testing on darwin.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
This looks like it's a mass-rebuild? Definitely should go into staging first then.

**Comment by Ericson2314** [comment]
Only for cross. Native hashes are unchanged. It would be prettier of it were a mass rebuild :).

**Comment by copumpkin** [comment]
It would be helpful, if you can't split this up further, if you summarized what you changed and why. It's pretty hard to review 1200+ lines of diff changing all sorts of core behavior in difficult-to-follow ways.

**Comment by copumpkin** [comment]
Or if there's a high-level description of why and the new design, that would also help. A giant mass of code changing core stdenv stuff is hard though 😄

**Comment by Ericson2314** [comment]
I'll split off the first few lib changes. Those are easy cause they don't change any hashes.

**Comment by Ericson2314** [comment]
Split out tiny cleanup https://github.com/NixOS/nixpkgs/pull/25186 which also doesn't change any hashes.

**Comment by Ericson2314** [comment]
Split out https://github.com/NixOS/nixpkgs/pull/25194, which redefines `stdenv.cross` and replaces a few gcc-related uses invalidated by the new definition.

**Comment by Ericson2314** [comment]
http://hydra.nixos.org/jobset/nixpkgs/pr-25047 for regression test.

**Comment by matthewbauer** [comment]
So how do you test on Darwin? I've tried:

```
$ nix-build pkgs/top-level/release-cross.nix -A rpi.unzip
these derivations will be built:
  /nix/store/v8a9ibjxnwk275a5ly7a6fyv7ma3swdm-unzip-6.0-armv6l-unknown-linux-gnueabi.drv
building path(s) ‘/nix/store/vf1vjls11ss078wa27h8hkmpkm2z2b9n-unzip-6.0-armv6l-unknown-linux-gnueabi’
error: a ‘x86_64-linux’ is required to build ‘/nix/store/v8a9ibjxnwk275a5ly7a6fyv7ma3swdm-unzip-6.0-armv6l-unknown-linux-gnueabi.drv’, but I am a ‘x86_64-darwin’
```

**Comment by Ericson2314** [comment]
@matthewbauer Uh I was using this in conjunction with @shlevy's impure iOS stuff on darwin. As I found when I added the last commit adding some darwin tests, more work will be needed to test purely :(. I'll get to that though.

**Comment by Ericson2314** [comment]
After slaving away to make it hash-preserving I peeled off https://github.com/NixOS/nixpkgs/pull/25227 with...the first commit.

It's a lot of work to make something hash preserving, but whenever I go for it I inevitably find a real bug.

**Comment by Ericson2314** [comment]
And also peeled off https://github.com/NixOS/nixpkgs/pull/25232

**Comment by mmahut** [comment]
Any update on this pull request?

**Comment by mmahut** [comment]
Closing due to lack of activity, feel free to reopen this if needed.

**Pull request closed without merging**
