### PR TITLE
nixos release notes: shift the dates

### PR DESCRIPTION
**Pull request by vcunat**
https://github.com/NixOS/rfcs/pull/80  needed doc changes.  Maybe more are missing, but just these came to my mind right now.  Feel free to formulate differently, etc.

### CODE REVIEW

**Comment by cole-h** [comment]
Might also want to update https://github.com/NixOS/nixpkgs/blob/master/.version.

**Comment by jonringer** [comment]
thank you @vcunat 

according to https://github.com/NixOS/release-wiki/blob/master/src/Release-Process-Walkthrough.md , @cole-h 's suggestions should be the last needed.

**Comment by jonringer** [comment]
I have a pending merge request https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/263 for changing the osinfo-db 

cc @jtojnar

**Comment by jonringer** [comment]
the release not file location should probably also be renamed to avoid confusion

If you want me to take over this responsibility, I can. As I probably should have done this in the first place

**Comment by vcunat** [comment]
The other PR now contains all changes here, so let me close.

**Pull request closed without merging**
