### PR TITLE
nixos/displayManager: slimlock fix (#67350)

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
Allow ```xautolock``` to lock session using ```loginctl lock-session``` and fix ```slimlock``` theme.
See #67350 for details

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by misuzu** [comment]
@adisbladis @edolstra @fpletz please take a look at this.

**Comment by evenbrenden** [comment]
@misuzu did you close this because https://github.com/NixOS/nixpkgs/issues/67350#issuecomment-540223981 was a sufficient fix? I ran into the same issue - `loginctl lock-session` does not trigger `xss-lock` when run as a service because `XDG_SESSION_ID` is not set in the `systemctl` environment (I suppose idle hint management is broken too). I'd like to keep `xss-lock` as a service (and all the safety that comes with it) rather than launching it through `sessionCommands`. This PR does the trick and I also think it's tidy to do it the same way as home-manager does.

Would you consider reopening? Or, alternatively, would you mind if a created a new one based on it?

**Comment by misuzu** [comment]
@evenbrenden slim is no longer in nixpkgs, see at https://github.com/NixOS/nixpkgs/pull/75389

**Comment by evenbrenden** [comment]
> @evenbrenden slim is no longer in nixpkgs, see #75389

I tested with LightDM and it has the same issue.

**Comment by misuzu** [comment]
> would you mind if a created a new one based on it?

Sure, go for it

> I tested with LightDM and it has the same issue.

It might be easier and faster to just patch slimlock

**Pull request closed without merging**
