### PR TITLE
dragonegg: does not build with gcc49

### PR DESCRIPTION
**Pull request by garbas**
https://llvm.org/bugs/show_bug.cgi?id=19847

not sure how to handle this? i guess removing (as in this PR) is one option. maybe somebody can figure this out.

/cc @viric

[Review on Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/9624)

### CODE REVIEW

**Comment by vcunat** [comment]
Have you tried dragonegg-3.6.2?

**Comment by garbas** [comment]
yes... i get 
```
~/d/n/nixpkgs ❯❯❯ nix-build -A dragonegg --option extra-binary-caches https://hydra.nixos.org -K
these derivations will be built:
  /nix/store/m35j648q0mbcmv5376by01klfq96w9sh-dragonegg-3.6.2.drv
building path(s) ‘/nix/store/x955jq2d5451s1j9kz7kvy8vhwdm487f-dragonegg-3.6.2’
unpacking sources
unpacking source archive /nix/store/3gkzlfrvwh8cyb59hvr6ll2q0k4ldhjf-dragonegg-3.6.2.src.tar.xz
source root is dragonegg-3.6.2.src
patching sources
configuring
no configure script, doing nothing
building
make flags: SHELL=/nix/store/548wfw1i43glkx8lkyjmbg59h6127qky-bash-4.3-p39/bin/bash    
Compiling utils/TargetInfo.cpp
Linking TargetInfo
Compiling Aliasing.cpp
/tmp/nix-build-dragonegg-3.6.2.drv-0/dragonegg-3.6.2.src/src/Aliasing.cpp: In function 'llvm::MDNode* describeAliasSet(tree)':
/tmp/nix-build-dragonegg-3.6.2.drv-0/dragonegg-3.6.2.src/src/Aliasing.cpp:140:16: error: 'class llvm::MDNode' has no member named 'replaceAllUsesWith'
       LeafTag->replaceAllUsesWith(getTBAARoot());
                ^
Makefile:140: recipe for target 'Aliasing.o' failed
make: *** [Aliasing.o] Error 1
note: keeping build directory ‘/tmp/nix-build-dragonegg-3.6.2.drv-0’
builder for ‘/nix/store/m35j648q0mbcmv5376by01klfq96w9sh-dragonegg-3.6.2.drv’ failed with exit code 2
error: build of ‘/nix/store/m35j648q0mbcmv5376by01klfq96w9sh-dragonegg-3.6.2.drv’ failed
```

**Comment by vcunat** [comment]
Right, it seems to me the project is slowly dying anyway.

Pushed as c7580cd1 and 15146015d.

**Comment by garbas** [comment]
should i also remove the dragonegg.nix expression altogether?

**Comment by vcunat** [comment]
I don't know. We're leaving old instances of `llvmPackages`, and most of those are likely unused.

**Comment by garbas** [comment]
ok, lets leave it. and _one_day_ we will clean it up :)

**Pull request closed without merging**
