### PR TITLE
ocamlPackages.mirage: init at 3.9.0

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

#23955 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.mirage

**Comment by sternenseemann** [comment]
Might be a good idea to wrap `bin/mirage` to add some runtime dependencies to `PATH` like `dune`.

**Comment by vbgl** [comment]
Might make sense for dune. But won’t you also need ocaml, ocamlfind, ocamlbuild, and a handful of OCaml libraries. It seems futile to try to have them all within the wrapped `mirage`: so, is it better to have some but not all rather than none?

**Comment by sternenseemann** [comment]
Yeah, I'm somewhat torn as well — `mirage` largely relies on stuff that is assumed to be installed *anyways*. Thus the UX for missing runtime dependencies is horrible (it shows it as command failure without any further information and you have to infer the cause from the exit code 127).

I think wrapping here could be harmful because it would limit the users choice of versions which make a difference:

* dune 1 vs. dune 2 (at least for the moment)
* different OCaml versions
* different ways of installing other dependencies (stateful opam, via a nix-shell, from nixpkgs, …) which also would in turn affect ocamlfind

I don't think that it's reasonable requiring users to use overriding to make these choices, so the simplest most user-friendly way seems to be relying on the environment.

**Comment by vbgl** [comment]
Thanks. Let’s merge as is then.

**Pull request merged**
