### PR TITLE
pcre2: patch shebang

### LINKED ISSUE #268542: `pcre2-config` does not have patched shebangs
### Describe the bug

`bin/pcre2-config` has a shebang of `#!/bin/sh`; I think this should be `#!/nix/store/something/bin/sh`.

`pcre2-config` segfaults on my system unless I change the shebang line to point to Nix's sh.

### Steps To Reproduce

```
$ nix build nixpkgs#pcre2.dev
$ head --lines 1 result/bin/pcre2-config
#!/bin/sh
```

### Expected behavior

The shebang should refer to Nix's copy of sh.

### Notify maintainers

@ttuegel 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-90-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixpkgs"`
 - channels(sam): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/sam/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by chewblacka**
## Description of changes
Patch shebang for the `pcre2-config` binary.
Fixes #268542

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by charmoniumQ** [comment]
This PR would fix my issue. Any reviewers available?

**Comment by NickCao** [comment]
I still have no idea why `patchShebangsAuto` hook does not handle this in the first place.

**Comment by NickCao** [comment]
This shows `dontPatchShebangs` is set to `1` for `pcre2`, I suppose it's related to bootstrapping, cc  @dasJ who last touch this part of code.
```
--- a/pkgs/development/libraries/pcre2/default.nix
+++ b/pkgs/development/libraries/pcre2/default.nix
@@ -24,6 +24,11 @@ stdenv.mkDerivation rec {

   outputs = [ "bin" "dev" "out" "doc" "man" "devdoc" ];

+  preUnpack = ''
+    echo $dontPatchShebangs
+    exit 1
+  '';
+
   postFixup = ''
     moveToOutput bin/pcre2-config "$dev"
   '';
```

**Comment by chewblacka** [comment]
Closing because 6 months old

**Pull request closed without merging**
