### PR TITLE
nixos/fish: fix completions patch

### LINKED ISSUE #80423: nixos/modules/programs/fish: completion generator patch does not work with fish 3.1.0 package
**Describe the bug**
When trying to use the nixos module `programs.fish` a patch is applied. This patch however does not match the updated fish package for `3.1.0`.

**To Reproduce**
1. Configuration containing: `programs.fish.enable = true`
2. `nixos-rebuild switch`

**Expected behavior**
The `programs.fish` module should be able to be enabled.

**Additional context**
```
building '/nix/store/flfdj6b0kjl5ncfllibhm4j13whklcxl-find-libs.drv'...
building '/nix/store/y54wzrnzassarw2p3jv361nqpf1hz5x1-fish_patched-completion-generator.drv'...
building '/nix/store/3aw30paxs1v05lbsi8xq1315cbg4if46-fix-bubblewrap-paths.patch.drv'...
unpacking sources
unpacking source archive /nix/store/z08mbgrf14gvv13i1hcw8wwjicdgn3k2-fish-3.1.0/share/fish/tools/create_manpage_completions.py
unpacking source archive /nix/store/z08mbgrf14gvv13i1hcw8wwjicdgn3k2-fish-3.1.0/share/fish/tools/deroff.py
source root is .
patching sources
applying patch /nix/store/r2bsz0sgmxjsm7jvcpmc0z113wfvfnkj-fish_completion-generator.patch
patching file create_manpage_completions.py
Hunk #1 FAILED at 776.
1 out of 1 hunk FAILED -- saving rejects to file create_manpage_completions.py.rej
builder for '/nix/store/y54wzrnzassarw2p3jv361nqpf1hz5x1-fish_patched-completion-generator.drv' failed with exit code 1
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.4, NixOS, 20.09.git.69efb5cd343 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - nixpkgs: master @ 329102c47bd1c68f0acdf4feec64232202948c7a

Maintainer information:
```yaml
module:
- programs.fish
```

### PR DESCRIPTION
**Pull request by cole-h**
###### Motivation for this change

Upstream decided to split the lines we were patching out, so the patch
would fail.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Fix #80423 (hopefully). cc @terlar -- could you test this? I don't have an easy way to test this on NixOS, currently.

### CODE REVIEW

**Comment by GTrunSec** [comment]
it's build failed.

**Comment by cole-h** [comment]
@GTrunSec Could you please post the logs here/somewhere? Otherwise, I can't do anything more to try and fix this.

**Comment by terlar** [comment]
Weird, for me it worked.

**Comment by GTrunSec** [comment]
> Weird, for me it worked.

yeh, it' worked. 

> DIT: The fact that it succeeded for @terlar makes me think either 1) you were just agreeing that this is a problem or 2) you didn't apply this properly (I don't know what the proper way is either, though, which is why I was unable to test it myself).

sorry, when I deleted the building garbage, it worked for me.

**Comment by cole-h** [comment]
No worries, glad it worked! Thanks for trying it out and reporting back :)

**Comment by terlar** [comment]
Who is the owner for this module? Or someone that could make a decision to merge this, feels safe, and won't break stuff more than they currently are on master : )

**Comment by jtojnar** [comment]
Repro:

```
echo '{ ... }: { programs.fish.enable = true; }' > fish-fail.nix
nixos-rebuild build-vm -I nixpkgs=$HOME/Projects/nixpkgs -I nixos-config=fish-fail.nix
```

If you cannot wait for the `nixos-rebuild` to finish, just look for something like

```
these derivations will be built:
  /nix/store/zj2n12p41jrmifr8rrz2af0rzdw5kcvh-fish_patched-completion-generator.drv
```

in the output and run `nix-build /nix/store/zj2n12p41jrmifr8rrz2af0rzdw5kcvh-fish_patched-completion-generator.drv`.

**Review by jtojnar — APPROVED** [review]
Can confirm it fixes the build. Thanks.

**Comment by shyim** [comment]
I am not sure, but it seems so fish installing does not work more.

```
unpacking sources
unpacking source archive /nix/store/z08mbgrf14gvv13i1hcw8wwjicdgn3k2-fish-3.1.0/share/fish/tools/create_manpage_completions.py
unpacking source archive /nix/store/z08mbgrf14gvv13i1hcw8wwjicdgn3k2-fish-3.1.0/share/fish/tools/deroff.py
source root is .
patching sources
applying patch /nix/store/r2bsz0sgmxjsm7jvcpmc0z113wfvfnkj-fish_completion-generator.patch
patching file create_manpage_completions.py
Hunk #1 FAILED at 776.
1 out of 1 hunk FAILED -- saving rejects to file create_manpage_completions.py.rej
```

That's the same edited in this PR :thinking:

**Comment by cole-h** [comment]
You'll have to update your nixpkgs channel in order to get the fix. It was just merged yesterday, so you're probably still on an older revision. The most telltale sign of that is the patch fails at line 776 -- the updated patch is starts much later, at line 844.

**Comment by pmiddend** [comment]
I'm using the latest unstable (commit e2b4abe3c8f) and I'm getting the same error.

**Comment by cole-h** [comment]
If you view the tree at that commit, you can see that this PR has not yet been incorporated: https://github.com/NixOS/nixpkgs/blob/e2b4abe3c8f2e09adfc6a52007841d1b96c89371/nixos/modules/programs/fish_completion-generator.patch.

This means that the commit fixing this is only present on the master branch, and is not on any channels yet. I don't use NixOS, so I cannot give you any other solution than to switch to master until this PR has found its way into `nixos-unstable`.

**Comment by pmiddend** [comment]
@cole-h Alright, thanks for clarifying. I was a little confused by your hint to "update the channel", since it was already updated. But it's fine, I'll simply wait a bit. :)

**Comment by cole-h** [comment]
I could have been a little clearer, sorry ;) It made sense to me because my `nixpkgs` channel is tracking `master`. Hopefully `nixos-unstable` gets bumped sooner rather than later, so you no longer have to deal with this issue!

**Comment by cole-h** [comment]
Just a little update: according to https://howoldis.herokuapp.com/, `nixos-unstable` has advanced to https://github.com/NixOS/nixpkgs/commit/ea79a830dcf, whose tree includes this patch :tada:

**Pull request merged**
