### PR TITLE
Elm 0.19

### LINKED ISSUE #15800: Reduce Elm closure
It's around 1400MB atm: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.elmPackages.elm-compiler.x86_64-linux#tabs-charts

### PR DESCRIPTION
**Pull request by domenkozar**
WIP, it's now stuck trying to download elm packages for reactor.

I won't have time to work on this, hopefully someone can pick it up before 18.09 forks off.

Fixes #15800 

```
$ du -shc $(nix-store -qR /nix/store/hfbq8s60pjgc1j4dklxqsn7g20kmd31g-elm-0.19.0)


26M     /nix/store/rvmrk2ziwvz1rawkx4czriq6v8v1m8g4-glibc-2.27
5.6M    /nix/store/34dzxck5qjs8myz470lc4kxc2243wdr2-gcc-7.3.0-lib
696K    /nix/store/0ivn5z9i5vld64m0rh26v5iarjrad9i5-gmp-6.1.2
132K    /nix/store/bv8rivxx5i5rkwwncn7hnnih2wq9cy13-zlib-1.2.11
3.6M    /nix/store/hc0gl6iihj866n40xnpm8f1iqimdm5sx-openssl-1.0.2o
12M     /nix/store/vg9gmfgk7k9snjrkms00dbnn2ssijxd1-ncurses-6.1
14M     /nix/store/hfbq8s60pjgc1j4dklxqsn7g20kmd31g-elm-0.19.0
62M     total
```

### CODE REVIEW

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages.elm

**Comment by jerith666** [comment]
I tried some things in https://github.com/jerith666/nixpkgs/commit/815b8375c65041137ea0c9ee3c2e1667fc598afd to avoid the http request to https://package.elm-lang.org/all-packages, but it's still happening.  Maybe my flailing will inspire someone else ... ?

**Comment by jerith666** [comment]
Poking around some more in the source code, I think what we're missing is a `versions.dat` file in the root of the `.elm` directory.  This is a serialized `PackageRegistry` object, see https://github.com/elm/compiler/blob/master/builder/src/Deps/Cache.hs.  But it seems the code _might_ be robust to failures _updating_ that cache, it just needs to have _some data_ in there.  So maybe we can just drop a "seed" data into nixpkgs for bootstrapping?

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages.elm

**Comment by domenkozar** [comment]
elm-interface-to-json is not released yet, so only elm-format missing.

**Comment by arianvp** [comment]
Elm-interface-json seems a bit unmaintaned. I suggest just removing it untill they update to elm 0.19.

I tried getting a new elm-format ready with cabal2nix but I was running into dependency he'll because elm-format depends on a too old version of the `indent` package.  Perhaps we could use stack2nix to create a build plan for elm-format?

**Comment by jerith666** [comment]
Maybe the borg build failure is because you haven't fast-forwarded your `elm-0.19-wip` branch to the tip of mine, @domenkozar?  Though that doesn't explain how the darwin build could've succeeded ... ?

**Comment by jerith666** [comment]
I had to do some special handling for `indents` in #38023 ... could that be relevant?  (It was just for ghc 8.0, maybe we also need it for 8.2?)  I don't know enough about nix haskell infrastructure, I could be totally off base ...

**Comment by domenkozar** [comment]
I'd prefer if we fix it upstream, unless it's a major change.

**Comment by arianvp** [comment]
I've already got a fix!  I partially reverted one of your commits

https://github.com/arianvp/nixpkgs/tree/elm-0.19-wip

**Comment by arianvp** [comment]
Could you update this branch to point to my latest version of it?  Then we can let ofborg do its thing and merge.

**Comment by domenkozar** [comment]
Before we merge, we need reproducable updates, right now `versions.dat` is commited verbatim without instructions how to generate it. Same for `packages/elm-elm.nix`. @jerith666 Can you help us here how you got those two files?

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages

**Comment by domenkozar** [comment]
Once we add instructions for `versions.dat` and `packages/elm-elm.nix` this is good to go!

**Comment by jerith666** [comment]
instructions for `versions.dat` and `elm-elm.nix` are in fcabcb2e41a.

**Comment by domenkozar** [comment]
You rock :)

**Pull request merged**
