### PR TITLE
staging-next 2022-07-11

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- important job(s): [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/179844

### CODE REVIEW

**Comment by vcunat** [comment]
- [ ] {UNKNOWN}: aggregate job ‘tested’ failed with the error: nixpkgs.tests.packageTestsForChannelBlockers.curl.withCheck.x86_64-linux: does not exist

**Comment by K900** [comment]
Can we hold this off for a bit, I really want https://github.com/NixOS/nixpkgs/pull/180868 to go in.

**Comment by MatthewCroughan** [comment]
@K900 Along with the PR you linked, it would be excellent if https://github.com/NixOS/nixpkgs/pull/177538 also got merged, as they would fix a lot of cross-compilation errors together.

**Comment by vcunat** [comment]
- [ ] `libsForQt515.qtbase.x86_64-darwin` is perhaps a significant regression?  https://hydra.nixos.org/build/183942859

**Comment by K900** [comment]
https://github.com/NixOS/nixpkgs/pull/181862 may help

**Pull request merged**
