### PR TITLE
bazel.tests: update the protobuf test to the latest protobuf version

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Update the Bazel protobuf test to use the latest stable protobuf version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Profpatsch @guibou @mboes

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build bazel.tests

**Comment by Profpatsch** [comment]
Can’t you use the same packages we use in the bazel update script for that? The protobuf test is in the bazel repo, now?

**Comment by Profpatsch** [comment]
So the bazel `WORKSPACE` file already defines protobuf and dependencies: https://github.com/NixOS/nixpkgs//blob/master/pkgs/development/tools/build-managers/bazel/bazel_3/src-deps.json#L146-L168

We should really run the test against that, otherwise it doesn’t make much sense I think.

**Comment by Profpatsch** [comment]
Closing for now, unless somebody wants to pick this up again.

**Pull request closed without merging**
