### PR TITLE
Test if hibernation works

### PR DESCRIPTION
**Pull request by abbradar**
Related to https://github.com/NixOS/nixpkgs/pull/6675 . This hibernates and resumes properly now, but doesn't reconnect to the backdoor after resume. I have no idea how to fix it; it seems like /dev/ttyS0 is somehow broken after resume. @edolstra ?

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
ping?

**Comment by abbradar** [comment]
Sadly I still have no idea how to make the test reconnect.

**Comment by Fuuzetsu** [comment]
Maybe we should just close and open an issue then.

**Comment by abbradar** [comment]
Yes, I think we should.

**Pull request closed without merging**
