### PR TITLE
numbat: 1.13.0 -> 1.14.0

### PR DESCRIPTION
**Pull request by giomf**
Updated to: https://github.com/sharkdp/numbat/releases/tag/v1.14.0
Also, removed the patch that is not needed anymore since it is included in v1.14.0 now.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by giomf** [comment]
Command: `nixpkgs-review pr 351115`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>numbat</li>
  </ul>
</details>

**Review by Atemu — COMMENTED** [review]
Could you undo the automated format? Whatever that formatter is, it's not the RFC style nixfmt, so it will be redone anyways when the big format happens.

If you want to format yourself before that happens, please use nixfmt-rfc-style and do it in a separate commit.

**Comment by Atemu** [comment]
Your update commit still contains the odd reformat. Please make it just do the update, no reformatting.

Your git user also appears to be wrong in your commit; its email is not connected to your GH account.

**Comment by giomf** [comment]
Yes, I noticed that too. I'm currently working from a different computer, but you were faster than me. 

I don't quite understand the formatting. I have run the nixfmt-rfc-style over it?

**Comment by Atemu** [comment]
The problem is that the update commit still does the format. Please make commits do one logical step rather than two of which the second step is then revised in another commit.

One commit for the update (and only the update) and optionally one commit that does the reformat. The order doesn't matter, though it'd be slightly better if the reformat happened before the update.

**Comment by giomf** [comment]
Yes that make sense.
Thanks for your help. Will do it.

**Review by Atemu — APPROVED** [review]
Diff LGTM and it works in my limited testing

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351115`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>numbat</li>
  </ul>
</details>

**Pull request merged**
