### PR TITLE
nylas-mail-bin: drop package which is no longer supported upstream

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/65657

I didn't bother putting in any release notes because the package seems to have been broken for some time :man_shrugging: 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
> I didn't bother putting in any release notes because the package seems to have been broken for some time man_shrugging

Sounds good @aanderse, can you add a `throw` to `aliases.nix`?

**Comment by aanderse** [comment]
@worldofpeace right... thanks for always being on the ball :smile:

**Comment by worldofpeace** [comment]
> @worldofpeace right... thanks for always being on the ball smile

Thanks, I try to be :smile:

**Review by worldofpeace — APPROVED** [review]
LGTM
```
$ nix-build -A nylas-mail-bin                                                                                                                                        
error: deprecated in 2019-09-11: abandoned by upstream
```

**Pull request merged**
