### PR TITLE
python312Packages.libpwquality: fix build

### PR DESCRIPTION
**Pull request by 06kellyjac**
ZHF: #352882

Follow up from: #346286

- format to match the new standards in nixpkgs
- pull in patches to move from `distutils` which doesn't work in 3.12+ to `setuptools`
  - `setuptools` configuration works for `3.11`, might need to double check for the other python versions we support

I tried to drop the prefix patch all-together and just move the files from wherever they end up to `$py/lib/...` but I didn't manage to in the end

before:

```
S result-py
└── D lib
    └── D python3.11
        └── D site-packages
            ├── F pwquality-1.4.5-py3.11.egg-info
            └── F pwquality.cpython-311-x86_64-linux-gnu.so
```

after:

```
S result-py
└── D lib
    └── D python3.11
        └── D site-packages
            ├── D pwquality-1.4.5-py3.11.egg-info
            │   ├── F dependency_links.txt
            │   ├── F PKG-INFO
            │   ├── F SOURCES.txt
            │   └── F top_level.txt
            └── F pwquality.cpython-311-x86_64-linux-gnu.so
```

I expect this to be non breaking for egg-info but I'm not a python person

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
That's about ~25000 rebuilds! Probably need to do some conditional patches for now, or retarget staging?

**Comment by 06kellyjac** [comment]
I guess if I throw the patch on just the python module rather than normal libpwquality that might cut the dependents.

Is there a good script to check the nixpgkgs tree for dependents?

**Comment by 06kellyjac** [comment]
Ok. There's actually very few mentions of libpwquality but one is systemd which is probably where things start.

I'm not really spotting any usages of the python module so I think the python only patching would do

**Comment by 06kellyjac** [comment]
@wegank @RossComputerGuy 

This PR is back down to 1-10 packages and since we're waiting on some other PRs to release what are your thoughts on merge and backport?

If you'd prefer we could merge this and draft the backport for after the release is officially cut?

**Review by wegank — APPROVED** [review]

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
