### PR TITLE
ostree: support cross compilation

### PR DESCRIPTION
**Pull request by uninsane**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Kiskae — COMMENTED** [review]
It looks like this was added to ostree to work around a bug with clang 7: https://github.com/ostreedev/ostree/commit/fd8795f3874d623db7a82bec56904648fe2c1eb7

Maybe that fix isn't required anymore and this could also be fixed by removing the statement:
```
--replace "INTROSPECTION_SCANNER_ENV" "# DISABLED"
```

**Comment by uninsane** [comment]
> Maybe that fix isn't required anymore and this could also be fixed by removing the statement:
> 
> ```
> --replace "INTROSPECTION_SCANNER_ENV" "# DISABLED"
> ```

yep, this works too. applied ✅

**Comment by Mindavi** [comment]
Instead of this, adding `INTROSPECTION_SCANNER_ENV` to `makeFlags` should also work. Thanks for looking at this!

**Comment by Mindavi** [comment]
I rebased this and applied my suggestion. How do you like that?

(The rebase to hopefully fix eval)

**Comment by Kiskae** [comment]
Does that actually work? Since the makefile does an unconditional set `=` rather than providing a default with `?=`

**Review by Kiskae — APPROVED** [review]
Can confirm `pkgsCross.aarch64-multiplatform.ostree` compiles:
```console
❯ file ./result/bin/ostree 
./result/bin/ostree: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /nix/store/m477n4gfp2kmw637q0swbpcz2cj6d78g-glibc-aarch64-unknown-linux-gnu-2.38-27/lib/ld-linux-aarch64.so.1, for GNU/Linux 3.10.0, not stripped
```

**Pull request merged**
