### PR TITLE
maven: 3.9.6 -> 3.9.8

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

Closes #314980.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 324437` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>apgdiff</li>
    <li>bytecode-viewer</li>
    <li>certificate-ripper</li>
    <li>commafeed</li>
    <li>cryptomator</li>
    <li>digital</li>
    <li>forge-mtg</li>
    <li>gephi</li>
    <li>global-platform-pro</li>
    <li>gol</li>
    <li>h2</li>
    <li>h2.doc</li>
    <li>java-language-server</li>
    <li>jd-cli</li>
    <li>jetbrains.idea-community (jetbrains.idea-community-src)</li>
    <li>jetbrains.idea-community-bin</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.pycharm-community (jetbrains.pycharm-community-src)</li>
    <li>jnr-posix</li>
    <li>joularjx</li>
    <li>jugglinglab</li>
    <li>kotlin-interactive-shell</li>
    <li>kotlin-language-server</li>
    <li>ktfmt</li>
    <li>lemminx</li>
    <li>mariadb-connector-java</li>
    <li>maven (maven3)</li>
    <li>microsoft-identity-broker</li>
    <li>ns-usbloader</li>
    <li>openrefine</li>
    <li>protege</li>
    <li>quark-goldleaf</li>
    <li>runelite</li>
    <li>s3proxy</li>
    <li>scenebuilder</li>
    <li>schemaspy</li>
    <li>slipstream</li>
    <li>sonarlint-ls</li>
    <li>tabula-java</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 324437` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>protege</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>bytecode-viewer</li>
    <li>certificate-ripper</li>
    <li>gol</li>
    <li>h2</li>
    <li>h2.doc</li>
    <li>jugglinglab</li>
    <li>kotlin-language-server</li>
    <li>mariadb-connector-java</li>
    <li>quark-goldleaf</li>
    <li>tabula-java</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 324437` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>protege</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>bytecode-viewer</li>
    <li>certificate-ripper</li>
    <li>digital</li>
    <li>gol</li>
    <li>h2</li>
    <li>h2.doc</li>
    <li>jugglinglab</li>
    <li>kotlin-language-server</li>
    <li>mariadb-connector-java</li>
    <li>quark-goldleaf</li>
    <li>tabula-java</li>
  </ul>
</details>

**Review by h7x4 — APPROVED** [review]
Diff looks good

**Pull request merged**
