### PR TITLE
tidy-html5: fix missing dependency

### PR DESCRIPTION
**Pull request by zimbatm**
xsltproc is used during the build

### CODE REVIEW

**Comment by domenkozar** [comment]
Care to also add `platforms`?

**Comment by zimbatm** [comment]
@domenkozar : Is it better to start with know-working platforms and expand or can I start with platforms.all and then use hydra to detect which platforms are failing ?

**Comment by zimbatm** [comment]
In my case I tested the patch on Darwin only

**Comment by domenkozar** [comment]
Usually it's best to start with known working platforms, so in this case it's darwin and linux.

**Comment by peti** [comment]
Please don't restrict the set of supported platforms unless you *know* that a certain build architecture is unsupported.

**Pull request merged**
