### PR TITLE
brave: 0.69.135 -> 1.0.0

### PR DESCRIPTION
**Pull request by rht**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by Br1ght0ne — APPROVED** [review]
LGTM, works fine on NixOS.

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
browser launches fine

```
[3 built, 1 copied (23.7 MiB), 10.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/73400
1 package were build:
brave
```

**Comment by conferno** [comment]
It would be nice to build `brave` from the sources

**Comment by jonringer** [comment]
agreed, but I'll take pre-built binaries if they work as-intended

**Pull request merged**
