### PR TITLE
treewide: pin zig package in top-level instead of the function

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Description of changes

In order to obtain a more `by-name` -compatible override interface.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Merge conflict, please rebase.

Also, should we move `zig = zig_0_11;` to aliases, so that every `zig` in Nixpkgs is guaranteed to be overridden?

**Comment by AndersonTorres** [comment]
> Also, should we move `zig = zig_0_11;` to aliases, so that every `zig` in Nixpkgs is guaranteed to be overridden?

Since Zig is still too unstable, the rationale we adopted is:

- each package that uses zig should unconditionally set the suitable version for this package at top-level (as shown in this PR);
  - before the by-name hierarchy, we did it inside the expression. Now with by-name, we should do it outside.
- as a convenience (for e.g. `nix-shell` users), the `zig` handler should be set to the latest version we packaged.

I believe setting zig in `aliases.nix` will not be a good move, given the second point above.

**Review by wegank — APPROVED** [review]

**Comment by Aleksanaa** [comment]
I personally don't get the need of pinning it this way, and it makes the version used less obvious. As you have stated it is often not the case that the latest zig version works for all packages (right?), so we can just leave it as-is.

**Comment by AndersonTorres** [comment]
> I personally don't get the need of pinning it this way

This is to keep the [`.override` interface](https://nixos.org/manual/nixpkgs/stable/#sec-pkg-override) uniform and predicatble.

"Why a uniform `.override` interface is useful?"
Because a uniform `.override` interface is easier to override, facilitating the use of [overlays](https://nixos.org/manual/nixpkgs/stable/#sec-overlays-definition) and other methods of customization.

You can look at the Nixpkgs Manual for some interesting examples and concepts:

https://nixos.org/manual/nixpkgs/stable/#sec-overlays-alternatives
https://nixos.org/manual/nixpkgs/stable/#sec-overlays-alternatives-mpi
https://nixos.org/manual/nixpkgs/stable/#usage-1-pkgs.zlib.override

And a code that overrides `zig = prev.zig_0_11;` is way cleaner than `zig_0_9 = prev.zig_0_11;`

> , and it makes the version used less obvious.

How exactly? The version is clearly stated at all-packages.nix.

> As you have stated it is often not the case that the latest zig version works for all packages (right?)

Yes. Zig makes some breaking changes in versions before 1.0, and sometimes the upstream developer did not update his code yet.

Because of it, we had that unwritten rule [I wrote above](https://github.com/NixOS/nixpkgs/pull/307268#issuecomment-2081442441).

> Also people are less likely to override it (for what?), unlike other runtime dependencies

I don't think it is a sufficient reason to reject this patch.
The "less likely" people that want to override it will have an annoyance to deal, and well, _rejecting minorities' concerns_ is not a nice thing.

**Comment by Aleksanaa** [comment]
Short question: will we have things like `callPackage ... { gtk = gtk4; }`?

-----

I find you to be much more adventurous than most of us in dealing with such issues. At present, I even doubt if there is a complete consensus on "keep overriding interface", especially in practice. Can we open an issue first to discuss whether this type of modifications are valuable and whether we should enforce them? If you see an example today, change it, and give your reasons, and tomorrow you see another example, things can get even more confusing if the cycle continues.

**Comment by AndersonTorres** [comment]
> Short question: will we have things like `callPackage ... { gtk = gtk4; }`?

I don't think so. GTK3 and GTK4 are basically inbred forks - different softwares that share a common repo, like Python 2 (abandonware) and 3.

> 
> -----
> 
> I find you to be much more adventurous than most of us in dealing with such issues. At present, I even doubt if there is a complete consensus on "keep overriding interface", especially in practice. 

With Emacs we used some guards in order to warn users about deprecated and renamed parameters.
Hey, the NixOS module system is full of backward-compatibility layers.

So I believe that consistency in the names of inputs is a desirable outcome. The whole system is directed towards it.

> Can we open an issue first

I will open the issue, but I will not condition any PR to it.

**Review by iFreilicht — APPROVED** [review]
I agree with this change. It makes the packages fit the [`by-name` guidelines specific mention of this case](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#changing-implicit-attribute-defaults). As I understand, these were part of the RFC introducing by-name, so I don't think this is the place for re-negotiating that.


I also ran nixpkgs-review on this PR for both x86_64-linux and aarch64-darwin, and no packages were built, proving that no inputs were changed.

Additionally, this blocks https://github.com/NixOS/nixpkgs/pull/308248, which is part of the 24.05 milestone.

**Comment by AndersonTorres** [comment]
Merge conflict. Fuck this shit, I am too tired.

**Pull request closed without merging**
