### PR TITLE
openblas, numpy: fix w/musl

### PR DESCRIPTION
**Pull request by dtzWill**
openblas needs to avoid openmp due to problems across fork,
(this fixes crashes and potentially hanging behavior)

numpy touched up to use fenv.h on non-glibc
as well as avoiding some complex trig functions
so that tests pass.

bump numpy version (minor) while visiting this.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
More on openblas fork: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60035 and search on the openblas issue tracker.  Let's workaround this for now.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build python2Packages.numpy python3Packages.numpy

**Review by FRidh — DISMISSED** [review]
This needs to go into staging.

Also, you'll notice there is already a bump to 1.14.1 of numpy. This additional bump is fine.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build python2Packages.numpy python3Packages.numpy

**Comment by dtzWill** [comment]
Makes me sad to disable openmp but other distributions seem to be doing the same (Alpine) or skipping this version of OpenBlas altogether due to this and other bugs.  At least this seems to work.

**Pull request merged**
