### PR TITLE
simplenote: 1.1.3 -> 1.5.0

### PR DESCRIPTION
**Pull request by tinybeachthor**
###### Motivation for this change

Old version was opening a pop-up, offering an upgrade on each open.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
```
error: while evaluating 'callPackageWith' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/lib/customisation.nix:108:35, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/pkgs/top-level/all-packages.nix:23593:16:
while evaluating 'makeOverridable' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/lib/customisation.nix:67:24, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/lib/customisation.nix:112:8:
anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/pkgs/applications/misc/simplenote/default.nix:1:1 called without required argument 'at_spi2_atk', at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/lib/customisation.nix:69:12
```

Looks like this uses an alias instead of the "actual" attribute name for `at_spi2_atk`?

**Comment by WhoMeNope** [comment]
I am quite lost, no idea why it's failing.
I have added the at_spi2_atk dependancy in the same way as it was added here: #33062

If I compile it on my computer it builds it and works fine.

**Comment by dtzWill** [comment]
That PR is from 2017 hehe :grin:.

Quick grep suggests the hyphenated form is the standard these days (`at-spi2-atk`).

**Comment by aanderse** [comment]
@GrahamcOfBorg build simplenote

**Review by aanderse — APPROVED** [review]
Changes look reasonable. Builds and runs for me locally. LGTM :+1: 
@dtzWill are you OK with this one?

**Comment by mmahut** [comment]
@WhoMeNope do you mind rebasing this?

**Comment by peterhoeg** [comment]
Superseded by #69266

**Pull request closed without merging**
