### PR TITLE
mons: rewrite xrandr path

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

`mons` tries to detect if `xrandr` is installed in the `PATH`, failing otherwise. However, this is not the way that packages are generally packaged in nixpkgs.

This commit changes it to hardcode the path of `xrandr` explicitly instead of depending of `xrandr` being declared in `PATH`.

Also adding myself as maintainer.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @mschneiderwng.

**Comment by baloo** [comment]
You'll want to change your PR title to something like: `mons: rewrite xrandr path`
you will also want to change your second commit to something like: `mons: declare xrandr explicitely ...`

**Comment by thiagokokada** [comment]
@baloo Ops, you're right, I was quite distract while writing the commit message of this PR (and forgot that I had two commits so GitHub did the dumb thing of using the name of branch instead of the commit description).

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114597` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>mons</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
mons:
<details>


warning: missing-patch-comment
Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/tools/misc/mons/default.nix:15:15:

```
   |
15 |   patches = [ ./xrandr.patch ];
   |               ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md
</details>
</details>

**Pull request merged**
