### PR TITLE
treewide: remove package names from prefix of descriptions

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change
Part of #97685.

I edited the files by hand (!), roughly according to these rules

- "X is a(n) ..." -> "A(n) ..."
- "X, a(n) ..." -> "A(n) ..."
- fixed grammatical errors/minor rephrasing
- if the first word referred to a protocol/trademark, did not remove

I had to cleanup whitespace in three files, due to ofborg complaining.
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Some things that may need to be clarified in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) if we want to be consistent across tens of thousands of packages;

- Some descriptions start with definite/indefinite articles (i.e. "a" or "the") or none at all
- Some descriptions consist of more than one independent clause, make it a rule to move into `longDescription`?
- Maintaining neutrality in descriptions, I saw phrases such as "very simple" tool or "highly addictive" game

**Review by jonringer — APPROVED** [review]
LGTM

Thanks for doing this! :)

**Comment by jonringer** [comment]
> Some things that may need to be clarified in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) if we want to be consistent across tens of thousands of packages;
> 
>     * Some descriptions start with definite/indefinite articles (i.e. "a" or "the") or none at all
> 
>     * Some descriptions consist of more than one independent clause, make it a rule to move into `longDescription`?
> 
>     * Maintaining neutrality in descriptions, I saw phrases such as "very simple" tool or "highly addictive" game

Hmm, agreed in general. 

I think the intent is, "does it concisely describe the package". There's a little bit of "literary freedom", but I wouldn't want to be pedantic to the point of dissuading potential contributors.

**Comment by jonringer** [comment]
I don't see anyone violently against this, I think I'll merge this before it gets into merge conflict limbo

**Pull request merged**
