### PR TITLE
writeTextFile: support large files,

### PR DESCRIPTION
**Pull request by MarcWeber**
see https://github.com/NixOS/nix/issues/473

### CODE REVIEW

**Comment by MarcWeber** [comment]
Hashes for small texts don't change. So it should be safe to merge.

**Comment by edolstra** [comment]
There is a danger here that if a store path hash is split across two files, Nix's hash scanner won't see it anymore, so the path won't be correctly detected as a dependency of the combined output...

**Comment by MarcWeber** [comment]
In which use case does that matter? They are buildtime dependencies only, right?

**Comment by lethalman** [comment]
I believe this should be better supported by nix as a primop @edolstra ?

**Comment by lethalman** [comment]
Alternatively would this work?
```
cat <<EOF > "$n"
$text
EOF
```

**Comment by MarcWeber** [comment]
@lethalman Have a look at the other discussion, cat > was suggested and fails for the same reason. I know that it should be a primop, but I needed a solution fast. I know its a hack - but it solves by httpd.conf problem - neither does it change existing hashes.

**Comment by lethalman** [comment]
@MarcWeber if you writeTextFile "${foo} ${bar} ${baz}" and the split happens in between a nix store hash, you lose a runtime dependency.

**Comment by MarcWeber** [comment]
Thanks Eelco! Fixed in https://github.com/NixOS/nix/commit/a70d275f3d25f6e1eb1b6d528ee07ecd7265ada5

**Comment by phunehehe** [comment]
Since NixOS/nixpkgs/pull/6411 isn't usable yet, I'm looking at this as a short-term workaround. However, I don't understand how a split in a hash would be a problem. Does the hash scanner parse the resulting file to determine runtime dependency?

**Comment by lethalman** [comment]
@phunehehe yes

**Comment by phunehehe** [comment]
But in `writeTextFile "${foo} ${bar} ${baz}"`, `foo`, `bar` and `baz` are all build dependencies, which I assume will be correct regardless of this change. Are they not available at runtime?

And BTW `passAsFile` is already in nixUnstable, so I was wrong and NixOS/nixpkgs#6411 should be usable actually.

**Comment by lethalman** [comment]
@phunehehe build deps yes, but if the hash is split later then they won't at runtime.

**Comment by phunehehe** [comment]
Thanks I think I'm getting it. When is this scanning done? During some later stage of building? Please tell me it's not done at run time...

**Comment by lethalman** [comment]
@phunehehe at build time... take some time to learn the basics, I've also wrote a post about it http://lethalman.blogspot.it/2014/08/nix-pill-9-automatic-runtime.html and there's the nix thesis. Let's not clutter this issue further :)

**Comment by wmertens** [comment]
FYI, Nixpkgs in staging now uses passAsFile and I tested it by creating a 1.5MB text file with it.

**Pull request closed without merging**
