### PR TITLE
cadence: init at 0.9.0

### PR DESCRIPTION
**Pull request by bignaux**
###### Things done

I can't fully test it since i don't have yet a proper jack enabled nixos.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build cadence

**Review by xeji — COMMENTED** [review]
Please modify according to nixpkgs [conventions for qt applications](https://nixos.org/nixpkgs/manual/#ssec-qt-applications).

**Comment by bignaux** [comment]
@xeji : fixed.

**Comment by xeji** [comment]
Thank you.
@GrahamcOfBorg build cadence

**Comment by xeji** [comment]
ofborg failure is unrelated (timeout in qtwebengine). Build checked on x86_64-linux locally, seems to run ok.

**Pull request merged**
