### PR TITLE
python3Packages.cozy: remove

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/145592#issuecomment-966878611
https://github.com/NixOS/nixpkgs/pull/145592#issuecomment-972926537

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @MostAwesomeDude @Prillan

### CODE REVIEW

**Comment by dasj19** [comment]
The removal is ok, but should we have an alias that tells the user why the package is gone?
Something like:
`cozy = throw "cozy was removed because ...";`
could go in `pkgs/top-level/python-aliases.nix`

**Comment by Prillan** [comment]
I don't think removing it makes sense. Perhaps moving it and updating python-aliases.nix to mentioned that it was moved instead? (If it being in `python*Packages` is the issue here)

This works today, and breaking it without a way to fix it for end users is not good:
```
$ nix shell nixpkgs#python3Packages.cozy -c cozy -h
usage: cozy [-h] [-S FILE] [-R] [-t N] [-s] [-p P] [--java FILE.java] [--unboxed] [--c++ FILE.h] [--use-qhash]
            [--enforce-well-formed-state-var-boundaries] [--verbose] [--save-solver-testcases PATH]
            [--collection-depth N] [--quantified-encoding] [--skip-stateless-synthesis]
            [--update-numbers-with-deltas] [--no-invariant-preservation-check] [--checked-simplification]
            [--no-deduplicate-subqueries] [--profile] [--no-acceleration-rules] [--eliminate-vars] [--incremental]
            [--no-allow-conditional-state] [--allow-peels] [--allow-big-sets] [--allow-big-maps]
            [--no-allow-int-arith-state] [--nice-children] [--log-dir LOG_DIR] [--save-failed-codegen-inputs PATH]
            [--checkpoint-prefix CHECKPOINT_PREFIX] [--cse]
            [file]

Data structure synthesizer.
[..]
```

Also, why is it bad that it's not on PyPI? I don't understand that argument

**Comment by dotlambda** [comment]
> Perhaps moving it and updating python-aliases.nix to mentioned that it was moved instead? (If it being in `python*Packages` is the issue here)

Go ahead and do that.



> Also, why is it bad that it's not on PyPI? I don't understand that argument

Because `python3Packages.cozy` is supposed to be https://pypi.org/project/Cozy/

**Comment by dotlambda** [comment]
Besides the expectation that `python3Packages.cozy` should be https://pypi.org/project/Cozy/ there is the problem that the current `python3Packages.cozy` is not a Python module (you're not supposed to do `import cozy`) and so should be a top-level attribute. I raised these issues in November and the maintainer didn't seem to be interested in fixing them. If nobody else steps up to do so immediately I will go ahead and merge this.

**Comment by dotlambda** [comment]
> is that something that is documented somewhere?

From https://nixos.org/manual/nixpkgs/unstable/#python:

> Module names usually match their names on pypi.org

**Comment by dotlambda** [comment]
> If you don't want to move it yourself, then not touching it is better than removing it, imo.

I strongly disagree. Having unmaintained packages that don't even follow our standards is a burden to other maintainers and possibly dangerous to users of that package.

**Review by dasj19 — APPROVED** [review]

**Comment by jonringer** [comment]
Why don't we move this up to `all-packages` as `cozy-synthesizer`. Looks like it's intended to be an application.

**Comment by dotlambda** [comment]
> Why don't we move this up to `all-packages` as `cozy-synthesizer`.

Cause nobody seems to be willing to open a PR for that.

**Comment by jonringer** [comment]
cc @MostAwesomeDude , as the maintainer

**Comment by MostAwesomeDude** [comment]
You can remove Cozy entirely if there's nobody presently using it. It's been broken for a bit and there's not yet a good upstream release that we can use.

**Pull request merged**
