### PR TITLE
kanidm: 1.1.0-alpha.9 -> 1.1.0-alpha.10

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/kanidm/kanidm/releases/tag/v1.1.0-alpha.10

includes a commit that fixes openssl 3 compat in the test suite.

>  kanidmd[802]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Running without TLS is not supported! Quitting!

needs work.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Flakebi** [comment]
I have a fix here to use the now required tls: https://github.com/NixOS/nixpkgs/commit/87e3369ad09744455e5e44c1604dd76850d6b360
As the snakeoil cert expired, the patch needs to be rebased upon master for the test to pass.

**Comment by mweinelt** [comment]
Feel free to push it into my branch.

**Comment by Flakebi** [comment]
> Feel free to push it into my branch.

I don’t have permissions to do that :)

> Oh and I think alpha10 requires TLS, not alpha9.

Right, I meant to write alpha10.

**Comment by mweinelt** [comment]
@ofborg test kanidm

**Comment by erictapen** [comment]
I think we'll need release notes here, so people can adapt their setups for the TLS change?

**Comment by mweinelt** [comment]
Can you write some please?

**Comment by Flakebi** [comment]
As it’s a breaking change, I suggest that we wait until after the 22.11 branch-off today.
For the release notes, maybe this?
```
- `kanidm` has been updated to 1.1.0-alpha.10 and now requires a tls certificate and key. It will always start an https and – if enabled – an ldaps server.
```

**Comment by erictapen** [comment]
> As it’s a breaking change, I suggest that we wait until after the 22.11 branch-off today.

As nothing depends on kanidm I'd rather have it in the 22.11 branch? As long as we have a chance it's better to ship the most recent version, right?

**Comment by Flakebi** [comment]
Ok, fine with me :)

**Comment by Flakebi** [comment]
Here’s a commit that adds release notes: https://github.com/NixOS/nixpkgs/commit/d64b9cd11c16680050fd9c03d2cbfa351e9a2aab

- `kanidm` has been updated to 1.1.0-alpha.10 and now requires a tls certificate and key. It will always start an https and – if enabled – an ldaps server and no http and ldap server anymore.

**Comment by Flakebi** [comment]
Sounds like a good idea. I opened #206719 to mount the basedirs by default.

**Pull request merged**
