### PR TITLE
nixos/webhook: add additional hook configuration options

### PR DESCRIPTION
**Pull request by ngerstle**
###### Description of changes

The webhook hook definitions allow for more configuration than expressed in the module. This change adds typed options for some of those hook configuration options.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
This doesn't allow any more configuration than is currently possible, does it? We have a JSON `freeformType`.

**Comment by ngerstle** [comment]
> This doesn't allow any more configuration than is currently possible, does it? We have a JSON `freeformType`.

You are entirely correct- I hadn't come across it before, missed it in `webhook.nix`,  and tend to rely on `https://search.nixos.org/options?` in discovering options.

Do you see any value in adding this? Do you know if there is any work on making `freeFormType` more discoverable (without inspecting option declarations)?

**Comment by ncfavier** [comment]
> Do you see any value in adding this?

The gain is more type-safety, the loss is more options to keep in sync with upstream. See [RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md#part-2-balancing-module-option-count). I don't really have an opinion here.

> making `freeFormType` more discoverable

I don't think there's anything planned, but in this case looking at the [services.webhook.hooks](https://search.nixos.org/options?channel=unstable&show=services.webhook.hooks&from=0&size=50&sort=alpha_asc&type=packages&query=webhook) option itself should be enough to tell you its type and that it accepts things that aren't module options.

**Comment by ngerstle** [comment]
> > Do you see any value in adding this?
> 
> The gain is more type-safety, the loss is more options to keep in sync with upstream. See [RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md#part-2-balancing-module-option-count). I don't really have an opinion here.
> 
> > making `freeFormType` more discoverable
> 
> I don't think there's anything planned, but in this case looking at the [services.webhook.hooks](https://search.nixos.org/options?channel=unstable&show=services.webhook.hooks&from=0&size=50&sort=alpha_asc&type=packages&query=webhook) option itself should be enough to tell you its type and that it accepts things that aren't module options.

I think we may as well close this- hopefully others can discover `freeFormType` more easily.

**Pull request closed without merging**
