### PR TITLE
Revert "Revert "qutebrowser: 2.5.4 -> 3.0.0""

### PR DESCRIPTION
**Pull request by dotlambda**
Reverts NixOS/nixpkgs#251660
A downgrade would lead to data loss.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
- https://github.com/NixOS/nixpkgs/pull/251667

**Comment by amjoseph-nixpkgs** [comment]
See also: https://github.com/NixOS/nixpkgs/pull/251660#issuecomment-1694499288

**Comment by amjoseph-nixpkgs** [comment]
> A downgrade would lead to data loss.

I don't understand what you mean by this.

**Comment by dotlambda** [comment]
Downgrading from pyqt6-webengine to pyqtwebengine leads to data loss afaik. We can't afford to ship the downgrade to nixos-unstable. Let's discuss properly taking doing any action.

**Comment by dotlambda** [comment]
> > A downgrade would lead to data loss.
> 
> I don't understand what you mean by this.

Qt5's webengine can't deal with the SQLite database after migrations were applied

**Comment by dotlambda** [comment]
> Downgrading from pyqt6-webengine to pyqtwebengine leads to data loss afaik. We can't afford to ship the downgrade to nixos-unstable. Let's discuss properly taking doing any action.

Hence I'm merging this now and ask you to wait for comments before making changes, just like @rnhmjoj should have waited before merging https://github.com/NixOS/nixpkgs/pull/250171.

**Comment by amjoseph-nixpkgs** [comment]
> Downgrading from pyqt6-webengine to pyqtwebengine leads to data loss afaik.

No

> If you end up accidentally downgrading from running Qt 6 to Qt 5,
> the underlying Chromium will discard your browsing data (such as
> cookies). **qutebrowser will warn about this while starting**

You get a warning, and even if you ignore it it's just the cookies.


> Hence I'm merging this now and ask you to wait for comments before making changes, just like @rnhmjoj should have waited before merging #250171.

Rules for thee but not for me....

**Comment by dotlambda** [comment]
> > Hence I'm merging this now and ask you to wait for comments before making changes, just like @rnhmjoj should have waited before merging #250171.
> 
> Rules for thee but not for me....

Not true. I'm only undoing something that was done just a second ago.

> > If you end up accidentally downgrading from running Qt 6 to Qt 5,
> > the underlying Chromium will discard your browsing data (such as
> > cookies). **qutebrowser will warn about this while starting**
> 
> You get a warning, and even if you ignore it it's just the cookies.

Exactly, data loss.

**Comment by amjoseph-nixpkgs** [comment]
> Exactly, data loss.

What next, we remove `rm` from `coreutils` because it can be used for `rm -rf`?

If anything, the silent data loss occured when #250171 silently caused an irreversible upgrade to peoples' cookies.  The longer we leave that on `master` the more people will experience this.  By stalling you are causing more of this "data loss".  Frankly it smells like a negotiating tactic.

**Comment by dotlambda** [comment]
> If anything, the silent data loss occured when #250171 silently caused an irreversible upgrade to peoples' cookies. The longer we leave that on `master` the more people will experience this.

The sad news is that #250171 has already made it to nixos-unstable. I think it shouldn't have been merged this fast but we can't do anything about that now.
I'm not saying that having data loss for some people is the worst tradeoff but we should discuss it before taking action.
I'd like to hear your opinion on https://github.com/NixOS/nixpkgs/pull/251671 for example.

> Frankly it smells like stalling as a negotiating tactic while claiming that time is on your side. That's pretty dishonest.

No. I just want to have a discussion first.

**Comment by amjoseph-nixpkgs** [comment]
> we can't do anything about that now.

That is a really sleazy attitude.

> It's not. I just want to have a discussion first.

No, you're stalling to deliberately increase the number of people who've been silently upgraded.

**Comment by dotlambda** [comment]
> > we can't do anything about that now.
> 
> That is a really sleazy attitude.

I don't mean that we can't revert the change. I just mean that some people will inevitably end up with a downgrade if we do.

**Comment by dotlambda** [comment]
> You've declared that nothing can be done.

Nothing can be done about a Qt6 version having made it to nixos-unstable. Stop misinterpreting me on purpose.

**Comment by dotlambda** [comment]
These accusations don't get us further. I'd rather discuss options. Maybe Matrix is the best place for that?

**Comment by samueldr** [comment]
> If anything, the silent data loss occured when #250171 silently caused an irreversible upgrade to peoples' cookies. The longer we leave that on `master` the more people will experience this. By stalling you are causing more of this "cookie loss".

Schema migrations are to be expected when upgrading packages. ***Assuming*** this is a package upgrade, this is a schema migration, and not data loss.

*Reverting* schema migrations / making them forward+backward compatible is left as an issue for upstream to solve, we can't handle every schema out there.

Upstream made this the current version, maintainers upgraded, schemas got migrated. No data loss.

**Pull request merged**
