### PR TITLE
python3Package.mautrix: 0.5.8 -> 0.8.1

### PR DESCRIPTION
**Pull request by Scriptkiddi**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Why would you need this? The only package which actually uses this (`mautrix-telegram`) still requires `<0.6` of this library on its latest stable release (`0.8.2`).

**Comment by Scriptkiddi** [comment]
Its a matrix framework, im using it to write small bots for our matrix server

**Comment by Ma27** [comment]
May I ask what prevents you from using an overlay for now?

**Comment by Scriptkiddi** [comment]
> May I ask what prevents you from using an overlay for now?

Im using an overlay but I figured we should keep packages up to date

**Comment by Ma27** [comment]
> but I figured we should keep packages up to date

That's understandable, but IMHO it's even more important to keep our package-*set* stable than having every single package up-to-date. And in this case, the change would break *existing* stuff.

**Comment by SuperSandro2000** [comment]
I did a PR (#105336) which resolved the broken package and updates mautrix.

**Comment by Ma27** [comment]
> I did a PR (#105336) which resolved the broken package and updates mautrix.

There was no broken package as it wasn't merged or am I misunderstanding you?

**Pull request closed without merging**
