### PR TITLE
Drop unsupported go version 1.10

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
Go 1.10 is unsupported by upstream.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by adisbladis** [comment]
@GrahamcOfBorg build prometheus-snmp-exporter diskrsync prometheus_1 perkeep dnscrypt-proxy2 tmsu notary goa ipget fscrypt

**Comment by adisbladis** [comment]
CC maintainers: @lethalman @kalbasit @waynr @cstrahan @oida @ma27 @pSub @jluttine @vdemeester @willibutz @rushmorem @benley @primeos @fpletz @globin

**Review by vdemeester — APPROVED** [review]
Sounds good to me :+1:

**Comment by WilliButz** [comment]
@GrahamcOfBorg test prometheus-exporters.snmp

LGTM :+1: 
As a sidenote, I personally think we need to drop prometheus1 asap but that's out of scope for this PR and should be done separately :)

**Review by WilliButz — APPROVED** [review]

**Pull request merged**
