### PR TITLE
protonmail-desktop: 1.0.6 -> 1.5.1 / fix update-script

### PR DESCRIPTION
**Pull request by SebTM**
Updated protonmail-desktop to latest release, copied the approach from @massix (kudos 👍🏻) for resources-issue for loading/offline page

Fixed update-script as the sources are now official part of https://github.com/ProtonMail/WebClients and releases not provided via github anymore.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by massix** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356737`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>protonmail-desktop</li>
  </ul>
</details>

**Review by massix — APPROVED** [review]

**Comment by rsniezek** [comment]
Am I missing something here? looks like this no longer supports darwin? Intentionally?

**Comment by SebTM** [comment]
Not intentional, still published by Proton - will need to update the derivation / update-script to work with both but unsure for the moment when I have time to and no darwin to test either so if someone want's to step in here I'm open to it 🙏🏻

**Comment by rsniezek** [comment]
I will try to take a look as well but I also don't have darwin to test it. How about you, @matteo-pacini? You did original darwin support, would you be able to take a look if re-introducing it on top of @SebTM  changes can done?

**Comment by matteo-pacini** [comment]
Apologies for the late reply, busy time of the year.
I am happy to reintroduce Darwin support on top of this, this can be merged, and I can make another PR

**Review by rsniezek — APPROVED** [review]

**Comment by SebTM** [comment]
Updated to latest release, rebased due to treewide change on master, dropped darwin-support in derivation temporary until readded (please also add the update-script for darwin if you do so)

**Comment by massix** [comment]
> Updated to latest release, rebased due to treewide change on master, dropped darwin-support in derivation temporary until readded (please also add the update-script for darwin if you do so)

Hello, I tried launching the last version but it fails on my side:

```
21:30:31.194 (settings) › Some default values were missing, saving settings.
21:30:31.195 (settings) › Some default values were missing, saving settings.
21:30:31.195 (settings) › Some default values were missing, saving settings.

[ the same line repeated at least a hundred times ]

21:30:31.196 (main)     › uncaughtException RangeError: Maximum call stack size exceeded
    at o.processMessage (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:60062)
    at o.logData (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:59443)
    at r.<computed> [as info] (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:60871)
    at t.getSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:336969)
    at t.updateSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:336606)
    at t.getSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:337048)
    at t.updateSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:336606)
    at t.getSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:337048)
    at t.updateSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:336606)
    at t.getSettings (/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar/.webpack/main/index.js:7:337048) null
Unexpected error
Due to an error, the app will close. Try running it again and, if the problem persists, contact us. Information about the error can be found in the application log.
```


I am not sure what the problem could be, and I cannot exclude a problem on my side rather than yours. I will double-check tomorrow using my other laptop.

**Comment by massix** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356737`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>protonmail-desktop</li>
  </ul>
</details>

**Review by massix — APPROVED** [review]

**Review by rsniezek — APPROVED** [review]
works for me on linux

```
--------- Report for 'x86_64-linux' ---------
1 package built:
protonmail-desktop
```

```
 ./results/protonmail-desktop-x86_64-linux/bin/proton-mail
09:48:18.319 (main)     › App start is mac: false is windows: false islinux: true version: 1.5.1 params [
  '/nix/store/0755ah00p2nn7dpv62hkr3dcq7zgj3g1-electron-unwrapped-33.0.2/libexec/electron/electron',
  '/nix/store/imab05ik1381d08mf5h4z81vqbfjj0hp-protonmail-desktop-1.5.1/share/proton-mail/app.asar'
]
09:48:18.325 (main)     › Build info: {"idaTag":"ida-239","buildTag":"ida-239","appVersion":"1.5.1"}
```

**Comment by SebTM** [comment]
Had to rebase again, please re-approve and I will merge it 🙏🏻

**Review by rsniezek — APPROVED** [review]

**Review by rsniezek — APPROVED** [review]

**Pull request merged**
