### PR TITLE
haven-cli: 3.0.7 -> 3.3.4

### PR DESCRIPTION
**Pull request by Kamillaova**
## Description of changes

Updated Haven to 3.3.4, fixed building on x86_64-linux, aarch64-darwin and possibly other systems.

UPD: Marked as broken on x86_64-darwin, reason:
image

ZHF: #309482

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin (bad platform)
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Kamillaova** [comment]
@Ofborg eval

**Comment by Kamillaova** [comment]
> error: cannot open connection to remote store 'daemon': error: reading from file: Connection reset by peer

@ofborg eval

**Comment by Kamillaova** [comment]
wait why is this broken on x86_64-darwin :0

**Review by pbsds — APPROVED** [review]
Result of `nixpkgs-review pr 313229` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>haven-cli</li>
    <li>haven-cli.source</li>
  </ul>
</details>

fixes https://hydra.nixos.org/build/259532567 and https://hydra.nixos.org/build/259494720, marks https://hydra.nixos.org/build/259349475 bad, aarch64-darwin works on hydra (https://hydra.nixos.org/build/259367599) and builds according to author, but ofborg has yet to confirm it at time of writing. Waiting for ofborg

zhf https://github.com/NixOS/nixpkgs/issues/309482

**Comment by Kamillaova** [comment]
Sorry, I forgot to add a comment to `badPlatforms = [ "x86_64-darwin" ];`, maybe wait for the ofborg aarch64-darwin test (how long?), and then add a comment?

**Comment by pbsds** [comment]
IMO it is fine as is

**Comment by Kamillaova** [comment]
Hm, it seems that aarch64-darwin build of hanvend is broken.

It randomly crashes on startup and sometimes doesn't crash at all.

I think it's because of this warning (thrown by havend):
`libunbound was not built with threads enabled - crashes may occur`

And yes, unbound on aarch64-darwin is built without threading support.

https://hydra.nixos.org/build/258917101/nixlog/1 (unbound build log)
```
checking whether pthreads work with -pthread... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
```

**Comment by wegank** [comment]
LGTM. Please open a new PR to mark this as broken on aarch64-darwin, if necessary.

**Pull request merged**
