### PR TITLE
dbqn, dbqn-native: 2021-10-02 -> 2021-10-05 

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Squash the commits.

The only thing I am a bit confused is the `lib.getLib` stuff.
How this differentiates between host and target?

**Comment by sternenseemann** [comment]
> Squash the commits.

I don't see why, each commit builds on its own and contains an atomic change, with added context. Doing it this way improves stuff like bisects etc.

> The only thing I am a bit confused is the lib.getLib stuff.
> How this differentiates between host and target?

That's unrelated to that. We use `getLib` to get the `lib` output of `graalvm11-ce` which contains a symlinks to `glibc` etc. Sadly, we need to pass this explicitly atm (<https://github.com/NixOS/nixpkgs/issues/140544#issuecomment-933995717>).

By default, you always receive the pkgsHostTarget version of any derivation via `callPackage` (in our case target is irrelevant of course, since BQN is interpreted). `nativeBuildInputs` will select the `pkgsBuildHost` version explicitly by accessing its `nativeDrv` attribute.

**Comment by sternenseemann** [comment]
Given that <https://github.com/dzaima/BQN/pull/9> was merged, I'll try to adapt this PR later, we can drop the encoding stuff we do partially since it has been upstreamed.

**Comment by AndersonTorres** [comment]
> I don't see why, each commit builds on its own and contains an atomic change, with added context. Doing it this way improves stuff like bisects etc.

Nixpkgs is not a typical monolytic software like, well, the Linux kernel. Such concerns like "atomic, buildable changes" don't apply here the same way they would apply out there.
Indeed, in a huge kernel like Linux, a single line can require a whole new version - once upon a time a single line was the reason behind a race condition. This is way less likely in Nixpkgs.

The changes you did here are small and with low to no impact. No one of them are bugfixes or require huge rebuilds. The only serious modification here is the closure size shrinking.

Indeed, the one you make for reusing the `build8` script is merely a cleaner way to do the same thing, there is no conceptual difference between the expression before and after this particular modification.

Further, this PR is restricted to one single file, and all these changes were made at the same day by the same person (you). The comments you made in the commit messages are way bigger than each patch, indeed.

This pulverization does not help stuff like bisections. On the contrary, by creating four commits, it would generate 16 possible routes for a bisection - _from one single file modified in one single day by one single person_.

In the event of a bug-hunting, is way easier to read the entire expression and the commit message explaining the modifications instead of the various patches, one for each commit.

**Comment by sternenseemann** [comment]
> Why did you erase the patch with `JDK_JAVA_OPTIONS`?

This has been upstreamed and is now unnecessary, see my comment above (and the linked PR).

**Pull request merged**
