### PR TITLE
fetchtorrent, fetchipfs: default to unfree

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

Let's not _accidentally_ redistribute warez on hydra. This PR marks the tests unfree due to the terms of the test material, must be fixed in a follow-up.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by MatthewCroughan** [comment]
I disagree with this. Bittorrent is a protocol for sending files in a content addressed manner over the internet, it has no relationship to licenses, free or unfree. If you're going to do this, then please also mark other fetchers like IPFS as unfree too. Read some of the discussions that took place in https://github.com/NixOS/nixpkgs/pull/212930#issuecomment-1436013726.

**Comment by adisbladis** [comment]
I would agree with @MatthewCroughan here.
The torrent protocol itself is commonly used for everything from Linux ISOs to warez.
`fetchTorrent` strikes me as a great way to pin Linux ISOs in expressions for longevity.

We also have to be careful about using `fetchurl` not to fetch proprietary non-distributable assets in nixpkgs.

**Comment by pbsds** [comment]
If the source is free then I don' see a problem using fetchtorrent nor fetchipfs. Taking the 5 extra seconds in checking that I do not think is a tall ask.

> Read some of the discussions that took place in https://github.com/NixOS/nixpkgs/pull/212930#issuecomment-1436013726.

The discussion seem to be on functionality, which i don't oppose but much rather welcome.

> then please also mark other fetchers like IPFS as unfree

Great idea!

**Comment by ehmry** [comment]
If we need to ban derivations at hydra than we should have an explicit meta attribute that does that, because "unfree" is a quintessentially vague word that is open for interpretation in any regard.

**Comment by 7c6f434c** [comment]
We do have a narrow-purpose Hydra-banning `meta` entry,  `hydraPlatforms = [];`. Should we ask Hydra-maintaining people whether egress traffic is indeed a reason to default to it?

The is-download-good issues also applies to «is it a safe source» in `fetchurl` if you do not know the true upstream download mirrors…

On the other hand, adding the licenses in the tests is a useful change, is there a PR with just this separately?

**Comment by pbsds** [comment]
> On the other hand, adding the licenses in the tests is an unconditionally useful change, is there a PR with just this separately?

Please view #271562

**Pull request closed without merging**
