### PR TITLE
gn: fix hash

### PR DESCRIPTION
**Pull request by volth**

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build gn.src

**Comment by volth** [comment]
> Now everybody has one's own hash there? Very, very strange.

Seems like a ```fetchgit``` issue

**Comment by YorikSar** [comment]
@volth #46721 should fix this properly.

**Comment by vcunat** [comment]
`leaveDotGit` and maybe also `deepClone` are still non-determinstic IIRC.

**Comment by volth** [comment]
> ```leaveDotGit``` and maybe also ```deepClone``` are still non-determinstic IIRC.

```deepClone``` yes, because submodule might point to tag name or ```master``` of another repo, but ```leaveDotGit``` invoke ```make_deterministic_repo``` https://github.com/NixOS/nixpkgs/blob/ea23a1e/pkgs/build-support/fetchgit/nix-prefetch-git#L235 which apparently does not do what it should

**Pull request merged**
