### PR TITLE
Migrate from qt4 to qt5 [WIP]

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Qt4 is deprecated.

Mixxx can simply be recompiled for Qt5.
OpenMW is also updated from 0.42.0 to 0.43.0 with a slightly newer openscenegraph.
Vanilla openscenegraph is updated from 3.4.0 -> 3.4.1

If you guys think they should be split up into multiple different PRs for the sake of not changing too many things at the same time, let me know.

Cc: @abbradar @aszlig @cillianderoiste @7c6f434c 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
I'm willing to take on some Qt4 apps. List of files mentioning Qt4:

* [ ] nixos/modules/i18n/input-method/uim.nix
* [ ] nixos/modules/programs/ccache.nix
* [ ] nixos/modules/programs/environment.nix
* [ ] pkgs/applications/altcoins/bitcoin-unlimited.nix
* [ ] pkgs/applications/altcoins/bitcoin-xt.nix
* [ ] pkgs/applications/altcoins/btc1.nix
* [ ] pkgs/applications/altcoins/dogecoin.nix
* [ ] pkgs/applications/altcoins/freicoin.nix
* [ ] pkgs/applications/altcoins/litecoin.nix
* [ ] pkgs/applications/altcoins/memorycoin.nix
* [ ] pkgs/applications/altcoins/namecoin.nix
* [ ] pkgs/applications/altcoins/primecoin.nix
* [ ] pkgs/applications/altcoins/zcash/default.nix
* [ ] pkgs/applications/audio/cantata/default.nix
* [ ] pkgs/applications/audio/clementine/default.nix
* [ ] pkgs/applications/audio/faust/faust2alqt.nix
* [ ] pkgs/applications/audio/faust/faust2jaqt.nix
* [ ] pkgs/applications/audio/faust/faust2lv2.nix
* [ ] pkgs/applications/audio/google-musicmanager/default.nix
* [ ] pkgs/applications/audio/hydrogen/default.nix
* [ ] pkgs/applications/audio/jackmix/default.nix
* [ ] pkgs/applications/audio/kid3/default.nix
* [ ] pkgs/applications/audio/mixxx/default.nix
* [ ] pkgs/applications/audio/pianobooster/default.nix
* [ ] pkgs/applications/audio/picard/default.nix
* [ ] pkgs/applications/audio/projectm/default.nix
* [ ] pkgs/applications/audio/puddletag/default.nix
* [ ] pkgs/applications/audio/qmidiroute/default.nix
* [ ] pkgs/applications/audio/qtractor/default.nix
* [ ] pkgs/applications/audio/qtscrobbler/default.nix
* [ ] pkgs/applications/audio/soundscape-renderer/default.nix
* [ ] pkgs/applications/audio/tomahawk/default.nix
* [ ] pkgs/applications/audio/vmpk/default.nix
* [ ] pkgs/applications/display-managers/lightdm/default.nix
* [ ] pkgs/applications/editors/texmacs/default.nix
* [ ] pkgs/applications/editors/texmaker/default.nix
* [ ] pkgs/applications/editors/texstudio/default.nix
* [ ] pkgs/applications/editors/vim/qvim.nix
* [ ] pkgs/applications/gis/qgis/default.nix
* [ ] pkgs/applications/graphics/djview/default.nix
* [ ] pkgs/applications/graphics/fontmatrix/default.nix
* [ ] pkgs/applications/graphics/freecad/default.nix
* [ ] pkgs/applications/graphics/ipe/default.nix
* [ ] pkgs/applications/graphics/leocad/default.nix
* [ ] pkgs/applications/graphics/openscad/default.nix
* [ ] pkgs/applications/graphics/photivo/default.nix
* [ ] pkgs/applications/graphics/qscreenshot/default.nix
* [ ] pkgs/applications/graphics/qtpfsgui/default.nix
* [ ] pkgs/applications/graphics/scantailor/default.nix
* [ ] pkgs/applications/graphics/screencloud/default.nix
* [ ] pkgs/applications/graphics/smartdeblur/default.nix
* [ ] pkgs/applications/misc/bibletime/default.nix
* [ ] pkgs/applications/misc/bitcoinarmory/default.nix
* [ ] pkgs/applications/misc/confclerk/default.nix
* [ ] pkgs/applications/misc/diffpdf/default.nix
* [ ] pkgs/applications/misc/diffpdf/fix_path_poppler_qt4.patch
* [ ] pkgs/applications/misc/doomseeker/default.nix
* [ ] pkgs/applications/misc/electrum-dash/default.nix
* [ ] pkgs/applications/misc/electrum-ltc/default.nix
* [ ] pkgs/applications/misc/evopedia/default.nix
* [ ] pkgs/applications/misc/fbreader/default.nix
* [ ] pkgs/applications/misc/gnuradio/default.nix
* [ ] pkgs/applications/misc/googleearth/default.nix
* [ ] pkgs/applications/misc/keepassx/2.0.nix
* [ ] pkgs/applications/misc/keepassx/default.nix
* [ ] pkgs/applications/misc/librecad/default.nix
* [ ] pkgs/applications/misc/multimon-ng/default.nix
* [ ] pkgs/applications/misc/navipowm/default.nix
* [ ] pkgs/applications/misc/navit/default.nix
* [ ] pkgs/applications/misc/open-pdf-presenter/default.nix
* [ ] pkgs/applications/misc/qlcplus/default.nix
* [ ] pkgs/applications/misc/qmetro/default.nix
* [ ] pkgs/applications/misc/qpdfview/default.nix
* [ ] pkgs/applications/misc/rescuetime/default.nix
* [ ] pkgs/applications/misc/sqliteman/default.nix
* [ ] pkgs/applications/misc/tpmmanager/default.nix
* [ ] pkgs/applications/misc/vym/default.nix
* [ ] pkgs/applications/misc/xautoclick/default.nix
* [ ] pkgs/applications/misc/xkblayout-state/default.nix
* [ ] pkgs/applications/misc/yate/default.nix
* [ ] pkgs/applications/misc/yubioath-desktop/default.nix
* [ ] pkgs/applications/networking/browsers/arora/default.nix
* [ ] pkgs/applications/networking/ike/default.nix
* [ ] pkgs/applications/networking/instant-messengers/blink/default.nix
* [ ] pkgs/applications/networking/instant-messengers/psi/default.nix
* [ ] pkgs/applications/networking/instant-messengers/pybitmessage/default.nix
* [ ] pkgs/applications/networking/instant-messengers/skype-call-recorder/default.nix
* [ ] pkgs/applications/networking/instant-messengers/vacuum/default.nix
* [ ] pkgs/applications/networking/mumble/default.nix
* [ ] pkgs/applications/networking/ostinato/default.nix
* [ ] pkgs/applications/networking/p2p/eiskaltdcpp/default.nix
* [ ] pkgs/applications/networking/remote/teamviewer/default.nix
* [ ] pkgs/applications/networking/remote/x2goclient/default.nix
* [ ] pkgs/applications/networking/sync/backintime/qt4.nix
* [ ] pkgs/applications/office/libreoffice/default.nix
* [ ] pkgs/applications/office/libreoffice/still.nix
* [ ] pkgs/applications/office/qnotero/default.nix
* [ ] pkgs/applications/office/scribus/default.nix
* [ ] pkgs/applications/office/tagainijisho/default.nix
* [ ] pkgs/applications/science/chemistry/avogadro/default.nix
* [ ] pkgs/applications/science/electronics/qfsm/default.nix
* [ ] pkgs/applications/science/electronics/qucs/default.nix
* [ ] pkgs/applications/science/medicine/aliza/default.nix
* [ ] pkgs/applications/science/misc/gplates/default.nix
* [ ] pkgs/applications/science/misc/openmodelica/default.nix
* [ ] pkgs/applications/science/misc/tulip/default.nix
* [ ] pkgs/applications/science/misc/vite/default.nix
* [ ] pkgs/applications/science/robotics/gazebo/default.nix
* [ ] pkgs/applications/search/recoll/default.nix
* [ ] pkgs/applications/version-management/git-and-tools/git-cola/default.nix
* [ ] pkgs/applications/version-management/git-and-tools/svn2git-kde/default.nix
* [ ] pkgs/applications/version-management/guitone/default.nix
* [ ] pkgs/applications/version-management/tortoisehg/default.nix
* [ ] pkgs/applications/video/avidemux/default.nix
* [ ] pkgs/applications/video/avidemux/wrapper.nix
* [ ] pkgs/applications/video/avxsynth/default.nix
* [ ] pkgs/applications/video/clipgrab/default.nix
* [ ] pkgs/applications/video/linuxstopmotion/default.nix
* [ ] pkgs/applications/video/makemkv/default.nix
* [ ] pkgs/applications/video/minitube/default.nix
* [ ] pkgs/applications/video/mythtv/default.nix
* [ ] pkgs/applications/video/natron/default.nix
* [ ] pkgs/applications/video/qgifer/default.nix
* [ ] pkgs/applications/video/recordmydesktop/qt.nix
* [ ] pkgs/applications/video/simplescreenrecorder/default.nix
* [ ] pkgs/applications/video/vlc/default.nix
* [ ] pkgs/development/compilers/eql/default.nix
* [ ] pkgs/development/libraries/aqbanking/gwenhywfar.nix
* [ ] pkgs/development/libraries/attica/default.nix
* [ ] pkgs/development/libraries/audio/suil/default.nix
* [ ] pkgs/development/libraries/avahi/default.nix
* [ ] pkgs/development/libraries/dssi/default.nix
* [ ] pkgs/development/libraries/grantlee/default.nix
* [ ] pkgs/development/libraries/gstreamer/legacy/qt-gstreamer/default.nix
* [ ] pkgs/development/libraries/gstreamer/qt-gstreamer/default.nix
* [ ] pkgs/development/libraries/libbluedevil/default.nix
* [ ] pkgs/development/libraries/libdbusmenu-qt/default.nix
* [ ] pkgs/development/libraries/libechonest/default.nix
* [ ] pkgs/development/libraries/libjreen/default.nix
* [ ] pkgs/development/libraries/liblastfm/default.nix
* [ ] pkgs/development/libraries/libqglviewer/default.nix
* [ ] pkgs/development/libraries/ntrack/default.nix
* [ ] pkgs/development/libraries/opencascade/default.nix
* [ ] pkgs/development/libraries/openscenegraph/default.nix
* [ ] pkgs/development/libraries/phonon/backends/gstreamer.nix
* [ ] pkgs/development/libraries/phonon/backends/vlc.nix
* [ ] pkgs/development/libraries/phonon/default.nix
* [ ] pkgs/development/libraries/physics/geant4/default.nix
* [ ] pkgs/development/libraries/polkit-qt-1/qt-4.nix
* [ ] pkgs/development/libraries/poppler/default.nix
* [ ] pkgs/development/libraries/prison/default.nix
* [ ] pkgs/development/libraries/qimageblitz/default.nix
* [ ] pkgs/development/libraries/qjson/default.nix
* [ ] pkgs/development/libraries/qscintilla/default.nix
* [ ] pkgs/development/libraries/qt-4.x/4.8/default.nix
* [ ] pkgs/development/libraries/qt-4.x/4.8/qmake-hook.sh
* [ ] pkgs/development/libraries/qt-5/modules/qtbase.nix
* [ ] pkgs/development/libraries/qtkeychain/default.nix
* [ ] pkgs/development/libraries/qt-mobility/default.nix
* [ ] pkgs/development/libraries/qtscriptgenerator/default.nix
* [ ] pkgs/development/libraries/qwt/6_qt4.nix
* [ ] pkgs/development/libraries/qwt/default.nix
* [ ] pkgs/development/libraries/qxt/default.nix
* [ ] pkgs/development/libraries/soprano/default.nix
* [ ] pkgs/development/libraries/soqt/default.nix
* [ ] pkgs/development/libraries/strigi/default.nix
* [ ] pkgs/development/libraries/torch/default.nix
* [ ] pkgs/development/libraries/wt/default.nix
* [ ] pkgs/development/python-modules/matplotlib/default.nix
* [ ] pkgs/development/python-modules/pykde4/default.nix
* [ ] pkgs/development/python-modules/pykde4/kdelibs.nix
* [ ] pkgs/development/python-modules/pyqt/4.x.nix
* [ ] pkgs/development/python-modules/pyside/apiextractor.nix
* [ ] pkgs/development/python-modules/pyside/default.nix
* [ ] pkgs/development/python-modules/pyside/generatorrunner.nix
* [ ] pkgs/development/python-modules/pyside/shiboken.nix
* [ ] pkgs/development/python-modules/pyside/tools.nix
* [ ] pkgs/development/r-modules/default.nix
* [ ] pkgs/development/ruby-modules/gem-config/default.nix
* [ ] pkgs/development/tools/analysis/snowman/default.nix
* [ ] pkgs/development/tools/analysis/valkyrie/default.nix
* [ ] pkgs/development/tools/build-managers/cmake/2.8.nix
* [ ] pkgs/development/tools/build-managers/cmake/default.nix
* [ ] pkgs/development/tools/documentation/doxygen/default.nix
* [ ] pkgs/development/tools/misc/automoc4/default.nix
* [ ] pkgs/development/tools/misc/gede/default.nix
* [ ] pkgs/development/tools/misc/xxdiff/default.nix
* [ ] pkgs/development/tools/profiling/oprofile/default.nix
* [ ] pkgs/games/anki/default.nix
* [ ] pkgs/games/anki/fix-paths.patch
* [ ] pkgs/games/gambatte/default.nix
* [ ] pkgs/games/hedgewars/default.nix
* [ ] pkgs/games/holdingnuts/default.nix
* [ ] pkgs/games/mnemosyne/default.nix
* [ ] pkgs/games/openmw/default.nix
* [ ] pkgs/games/pokerth/default.nix
* [ ] pkgs/games/sdlmame/default.nix
* [ ] pkgs/misc/drivers/hplip/3.16.11.nix
* [ ] pkgs/misc/frescobaldi/default.nix
* [ ] pkgs/misc/gnash/default.nix
* [ ] pkgs/os-specific/linux/ffado/default.nix
* [ ] pkgs/os-specific/linux/i7z/default.nix
* [ ] pkgs/os-specific/linux/wpa_supplicant/gui.nix
* [ ] pkgs/os-specific/windows/jom/default.nix
* [ ] pkgs/tools/audio/acoustid-fingerprinter/default.nix
* [ ] pkgs/tools/cd-dvd/unetbootin/default.nix
* [ ] pkgs/tools/graphics/nifskope/default.nix
* [ ] pkgs/tools/graphics/pfstools/default.nix
* [ ] pkgs/tools/graphics/wkhtmltopdf/default.nix
* [ ] pkgs/tools/graphics/zbar/default.nix
* [ ] pkgs/tools/inputmethods/fcitx-engines/fcitx-libpinyin/default.nix
* [ ] pkgs/tools/inputmethods/fcitx/unwrapped.nix
* [ ] pkgs/tools/inputmethods/ibus/ibus-qt.nix
* [ ] pkgs/tools/inputmethods/touchegg/default.nix
* [ ] pkgs/tools/inputmethods/uim/default.nix
* [ ] pkgs/tools/misc/apt-offline/default.nix
* [ ] pkgs/tools/misc/qjoypad/default.nix
* [ ] pkgs/tools/misc/yubikey-personalization-gui/default.nix
* [ ] pkgs/tools/security/meo/default.nix
* [ ] pkgs/tools/security/omapd/default.nix
* [ ] pkgs/tools/text/qshowdiff/default.nix
* [ ] pkgs/top-level/all-packages.nix
* [ ] pkgs/top-level/python-packages.nix

```
git grep qt4 | cut -d: -f1 | sort | uniq | awk '{ print "* [ ] " $0; }'
```

**Comment by yegortimoshenko** [comment]
223 total.

I think we already have Qt5 version of VLC in `libsForQt5.vlc` attribute, but we might want to drop Qt4 version.

` pkgs/tools/inputmethods/*` will all be dropped when Qt4 is removed entirely, and will also remove Qt4 from closure of everyone who uses non-alphabetic writing systems.

LibreOffice will probably land Qt5 in February: https://www.phoronix.com/scan.php?page=news_item&px=LibreOffice-VCL-Qt5

**Comment by orivej** [comment]
It is fine to build applications that support Qt 5 with Qt 5, but is there any reason to stop building applications with Qt 4 that don't (e.g. i7z)? Qt 4 works well and is not going to be removed in any near future.

**Comment by adisbladis** [comment]
@yegortimoshenko Wouldnt it be better to create a tracking issue with that list? I doubt that all of those packages will be handled by this PR.

@orivej I agree with you. I think it may be worth revisiting that question once there are only a few packages depending on Qt4 but for now I don't see any reason to drop Qt4 from packages not supporting Qt5.

**Comment by orivej** [comment]
@peterhoeg The fork of qjoypad that you have found is pretty good, but its UI is a bit deficient compared to its qt4 ancestor. I'd like these pull requests to be merged before we switch: https://github.com/panzi/qjoypad/pull/17 and https://github.com/panzi/qjoypad/pull/18.

**Comment by 7c6f434c** [comment]
Sounds reasonable for `xxdiff`, for `openscenegraph` I am not sure whether `flightgear` or `speed_dreams` care about Qt support in the library. Hopefully they use as much as `openmw`, though.

**Comment by yegortimoshenko** [comment]
@orivej: `i7z-gui` segfaults for me, so I too think we should drop it, if it doesn't work for anyone:

```
$ i7z-gui
i7z DEBUG: i7z version: svn-r77-(20-Nov-2011)
i7z DEBUG: Found Intel Processor
i7z DEBUG:    Stepping 7
i7z DEBUG:    Model a
i7z DEBUG:    Family 6
i7z DEBUG:    Processor Type 0
i7z DEBUG:    Extended Model 2
i7z DEBUG: msr = Model Specific Register
segmentation fault
```

But in other cases, patching application to support Qt5 is preferable.

**Comment by adisbladis** [comment]
@yegortimoshenko Works fine for me. Might be depending on the hardware?

**Comment by orivej** [comment]
Works for me too. It must be run as root, but when it isn't it doesn't segfault, it prints:
```
i7z DEBUG: i7z version: svn-r77-(20-Nov-2011)
i7z DEBUG: Found Intel Processor
i7z DEBUG:    Stepping 3
i7z DEBUG:    Model e
i7z DEBUG:    Family 6
i7z DEBUG:    Processor Type 0
i7z DEBUG:    Extended Model 4
i7z DEBUG: msr = Model Specific Register
i7z DEBUG: Unknown processor, not exactly based on Nehalem, Sandy bridge or Ivy Bridge
i7z DEBUG: msr device files exist /dev/cpu/*/msr
i7z DEBUG: You DONOT have write permissions to msr device files
i7z DEBUG: A solution is to run this program as root
```

**Comment by yegortimoshenko** [comment]
Interesting, `i7z` doesn't segfault for me (output identical to https://github.com/NixOS/nixpkgs/pull/33239#issuecomment-354614219) but `i7z-gui` does.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by peterhoeg** [comment]
No longer relevant.

**Pull request closed without merging**
