### PR TITLE
cozy: 1.0.3 -> 1.1.2

### PR DESCRIPTION
**Pull request by tnias**
###### Motivation for this change

- fancy new UI (https://github.com/geigi/cozy/releases)
- add support for m4a files by adding gst-plugins-bad as dependency

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136097` at ce79d5d9 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>cozy</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `file`.
Near pkgs/applications/audio/cozy-audiobooks/default.nix:14:3:
```
   |
14 | , file
   |   ^
```
</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
The commit and pull request should use the attribute name, not an the directory name. At the same time the path should probably be normalized to just `cozy` as well.

**Comment by tnias** [comment]
I changed the commit messages, PR title and renamed the directory.

**Comment by boppyt** [comment]
Result of `nixpkgs-review pr 136097` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cozy</li>
  </ul>
</details>

**Comment by tomfitzhenry** [comment]
I am using this to listen to audiobooks on my Pinephone, and it works well. Thanks!

**Pull request merged**
