### PR TITLE
python312Packages.pygit2: 1.15.0 -> 1.16.0, tartufo: 5.0.1 -> 5.0.2

### PR DESCRIPTION
**Pull request by fabaff**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 349844` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>git-annex-metadata-gui</li>
    <li>git-annex-metadata-gui.dist</li>
    <li>python311Packages.git-annex-adapter</li>
    <li>python311Packages.git-annex-adapter.dist</li>
    <li>python312Packages.git-annex-adapter</li>
    <li>python312Packages.git-annex-adapter.dist</li>
  </ul>
</details>
<details>
  <summary>75 packages built:</summary>
  <ul>
    <li>charmcraft</li>
    <li>charmcraft.dist</li>
    <li>dvc (python312Packages.dvc)</li>
    <li>dvc.dist (python312Packages.dvc.dist)</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>gitfs</li>
    <li>gitfs.dist</li>
    <li>gitless</li>
    <li>gitless.dist</li>
    <li>mercurialFull</li>
    <li>powerline (python312Packages.powerline)</li>
    <li>powerline.dist (python312Packages.powerline.dist)</li>
    <li>python311Packages.craft-application</li>
    <li>python311Packages.craft-application.dist</li>
    <li>python311Packages.dvc</li>
    <li>python311Packages.dvc-gdrive</li>
    <li>python311Packages.dvc-gdrive.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.dvc.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
    <li>python311Packages.gftools</li>
    <li>python311Packages.gftools.dist</li>
    <li>python311Packages.gto</li>
    <li>python311Packages.gto.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.notobuilder</li>
    <li>python311Packages.notobuilder.dist</li>
    <li>python311Packages.powerline</li>
    <li>python311Packages.powerline.dist</li>
    <li>python311Packages.pygit2</li>
    <li>python311Packages.pygit2.dist</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python312Packages.craft-application</li>
    <li>python312Packages.craft-application.dist</li>
    <li>python312Packages.dvc-gdrive</li>
    <li>python312Packages.dvc-gdrive.dist</li>
    <li>python312Packages.dvc-hdfs</li>
    <li>python312Packages.dvc-hdfs.dist</li>
    <li>python312Packages.dvclive</li>
    <li>python312Packages.dvclive.dist</li>
    <li>python312Packages.gftools</li>
    <li>python312Packages.gftools.dist</li>
    <li>python312Packages.gto</li>
    <li>python312Packages.gto.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.notobuilder</li>
    <li>python312Packages.notobuilder.dist</li>
    <li>python312Packages.pygit2</li>
    <li>python312Packages.pygit2.dist</li>
    <li>python312Packages.scmrepo</li>
    <li>python312Packages.scmrepo.dist</li>
    <li>rockcraft</li>
    <li>rockcraft.dist</li>
    <li>snapcraft</li>
    <li>snapcraft.dist</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.gitsrht.dist</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.listssrht.dist</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.mansrht.dist</li>
    <li>tartufo</li>
    <li>tartufo.dist</li>
    <li>turtle</li>
    <li>turtle.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349844`

---
### `x86_64-linux`
<details>
  <summary>:x: 12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.notobuilder</li>
    <li>python311Packages.notobuilder.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.notobuilder</li>
    <li>python312Packages.notobuilder.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 71 packages built:</summary>
  <ul>
    <li>charmcraft</li>
    <li>charmcraft.dist</li>
    <li>dvc (python312Packages.dvc)</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>dvc.dist (python312Packages.dvc.dist)</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>git-annex-metadata-gui</li>
    <li>git-annex-metadata-gui.dist</li>
    <li>gitfs</li>
    <li>gitfs.dist</li>
    <li>gitless</li>
    <li>gitless.dist</li>
    <li>mercurialFull</li>
    <li>powerline (python312Packages.powerline)</li>
    <li>powerline.dist (python312Packages.powerline.dist)</li>
    <li>python311Packages.craft-application</li>
    <li>python311Packages.craft-application.dist</li>
    <li>python311Packages.dvc</li>
    <li>python311Packages.dvc-gdrive</li>
    <li>python311Packages.dvc-gdrive.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.dvc.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
    <li>python311Packages.gftools</li>
    <li>python311Packages.gftools.dist</li>
    <li>python311Packages.git-annex-adapter</li>
    <li>python311Packages.git-annex-adapter.dist</li>
    <li>python311Packages.gto</li>
    <li>python311Packages.gto.dist</li>
    <li>python311Packages.powerline</li>
    <li>python311Packages.powerline.dist</li>
    <li>python311Packages.pygit2</li>
    <li>python311Packages.pygit2.dist</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python312Packages.craft-application</li>
    <li>python312Packages.craft-application.dist</li>
    <li>python312Packages.dvc-gdrive</li>
    <li>python312Packages.dvc-gdrive.dist</li>
    <li>python312Packages.dvc-hdfs</li>
    <li>python312Packages.dvc-hdfs.dist</li>
    <li>python312Packages.dvclive</li>
    <li>python312Packages.dvclive.dist</li>
    <li>python312Packages.gftools</li>
    <li>python312Packages.gftools.dist</li>
    <li>python312Packages.git-annex-adapter</li>
    <li>python312Packages.git-annex-adapter.dist</li>
    <li>python312Packages.gto</li>
    <li>python312Packages.gto.dist</li>
    <li>python312Packages.pygit2</li>
    <li>python312Packages.pygit2.dist</li>
    <li>python312Packages.scmrepo</li>
    <li>python312Packages.scmrepo.dist</li>
    <li>rockcraft</li>
    <li>rockcraft.dist</li>
    <li>snapcraft</li>
    <li>snapcraft.dist</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.gitsrht.dist</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.listssrht.dist</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.mansrht.dist</li>
    <li>tartufo</li>
    <li>tartufo.dist</li>
    <li>turtle</li>
    <li>turtle.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`diffenator2` failure will be fixed with https://github.com/NixOS/nixpkgs/pull/353085. `langchain-*` with https://github.com/NixOS/nixpkgs/pull/353002.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by fabaff** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349844`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 83 packages built:</summary>
  <ul>
    <li>charmcraft</li>
    <li>charmcraft.dist</li>
    <li>dvc (python312Packages.dvc)</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>dvc.dist (python312Packages.dvc.dist)</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>git-annex-metadata-gui</li>
    <li>git-annex-metadata-gui.dist</li>
    <li>gitfs</li>
    <li>gitfs.dist</li>
    <li>gitless</li>
    <li>gitless.dist</li>
    <li>mercurialFull</li>
    <li>powerline (python312Packages.powerline)</li>
    <li>powerline.dist (python312Packages.powerline.dist)</li>
    <li>python311Packages.craft-application</li>
    <li>python311Packages.craft-application.dist</li>
    <li>python311Packages.dvc</li>
    <li>python311Packages.dvc-gdrive</li>
    <li>python311Packages.dvc-gdrive.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.dvc.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
    <li>python311Packages.gftools</li>
    <li>python311Packages.gftools.dist</li>
    <li>python311Packages.git-annex-adapter</li>
    <li>python311Packages.git-annex-adapter.dist</li>
    <li>python311Packages.gto</li>
    <li>python311Packages.gto.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.notobuilder</li>
    <li>python311Packages.notobuilder.dist</li>
    <li>python311Packages.powerline</li>
    <li>python311Packages.powerline.dist</li>
    <li>python311Packages.pygit2</li>
    <li>python311Packages.pygit2.dist</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python312Packages.craft-application</li>
    <li>python312Packages.craft-application.dist</li>
    <li>python312Packages.dvc-gdrive</li>
    <li>python312Packages.dvc-gdrive.dist</li>
    <li>python312Packages.dvc-hdfs</li>
    <li>python312Packages.dvc-hdfs.dist</li>
    <li>python312Packages.dvclive</li>
    <li>python312Packages.dvclive.dist</li>
    <li>python312Packages.gftools</li>
    <li>python312Packages.gftools.dist</li>
    <li>python312Packages.git-annex-adapter</li>
    <li>python312Packages.git-annex-adapter.dist</li>
    <li>python312Packages.gto</li>
    <li>python312Packages.gto.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.notobuilder</li>
    <li>python312Packages.notobuilder.dist</li>
    <li>python312Packages.pygit2</li>
    <li>python312Packages.pygit2.dist</li>
    <li>python312Packages.scmrepo</li>
    <li>python312Packages.scmrepo.dist</li>
    <li>rockcraft</li>
    <li>rockcraft.dist</li>
    <li>snapcraft</li>
    <li>snapcraft.dist</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.gitsrht.dist</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.listssrht.dist</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.mansrht.dist</li>
    <li>tartufo</li>
    <li>tartufo.dist</li>
    <li>turtle</li>
    <li>turtle.dist</li>
  </ul>
</details>

**Pull request merged**
