### PR TITLE
[22.05] nextcloud25: init (non-breaking)

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes
This is a non-breaking change because the default version installed by `services.nextcloud` remains `pkgs.nextcloud24`, but it gives users a chance to upgrade to v25 on 22.05.

I also left `pkgs.nextcloud23` in here because it will only be dropped in 2022-12 which is also the EOL of 22.05.

The corresponding change in `master` is at
40b7f52b8f4fd63393c1fdb838f022a154a4f2b2 from PR #197386.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dschrempf** [comment]
Hi!

At the moment, when updating `nixpkgs-unstable-small`, I get the following comment:
```
After nextcloud24 is installed successfully, you can safely upgrade
to 25. The latest version available is nextcloud24.
```
which is a bit misleading. Should I change to `nextcloud25` right now, or is it better to wait?

**Comment by dschrempf** [comment]
Hi! Did you see my message? Did the problem arise because the transition to nc25 was incomplete?

**Comment by Ma27** [comment]
> which is a bit misleading

What exactly is misleading? The full warning gives way more context than just the sentence you quoted.

> Should I change to nextcloud25 right now, or is it better to wait?

That's up to you. We only ship supported Nextcloud majors. In case the warning isn't sufficient, there's more context in the documented in the manual: https://nixos.org/manual/nixos/stable/index.html#module-services-nextcloud-pitfalls-during-upgrade

> Did the problem arise because the transition to nc25 was incomplete?

What? Which problem?

Nothing is incomplete here: the thing is - as mentioned in the *full* warning - you cannot upgrade across multiple Nextcloud versions (i.e. when doing 23 -> 25, you need to install 24 first).

**Comment by dschrempf** [comment]
Sorry but I have to disagree. I think my message is clear.

The problem was that the warning told me to update to nc25, while telling me at the same time that the latest available version is nc24. I quoted the relevant part of the warning.

Nothing serious, but something weird. I thought maybe it is just because I caught some inconsistent state between merging pull requests. No offense ment!

**Comment by AkechiShiro** [comment]
I agree the warning is incorrect, it says to update to Nextcloud 25 but using the package pkgs.nextcloud24 doesn't make sense.

**Comment by Ma27** [comment]
> Nothing serious, but something weird. I thought maybe it is just because I caught some inconsistent state between merging pull requests. No offense ment!

No offense from my side either!
Let me try to explain our misunderstanding: "which is a bit misleading" wasn't sufficiently clear to me, it sounded like something about the nature of the warning itself, that's why I was slightly confused because there's quite much context and documentation about how to upgrade Nextcloud.

Only after your third comment I realized that the warning itself had an error, sorry for that! Will file a PR today to fix that, that's indeed a bug.

**Comment by dschrempf** [comment]
Thanks a lot! Sorry for the confusion!

**Comment by Ma27** [comment]
Fix is in #199345, but not mergeable right now because the updates are causing issues for me.

**Pull request merged**
