### PR TITLE
openra: 20181215 -> 20190314 + updated other engine releases and mods

### PR DESCRIPTION
**Pull request by msteen**
###### Motivation for this change
Updated the OpenRA engine releases and updated the mods for which the bleeding edge versions were known to work. Both the updated engine releases and mods have been checked to build and run, although they have not been thoroughly tested (e.g. full play through), because doing so would take too much time.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@grahamcofborg build openra

**Comment by aanderse** [comment]
Thanks @msteen :tada:

**Comment by c0bw3b** [comment]
@msteen @aanderse could you recheck `bleed` build in this?

I got a hash mismatch on my end (with nix-review):
```ini
hash mismatch in fixed-output derivation '/nix/store/2f3hijxy1h9y5n94414brfd0x2m59gg4-source':
  wanted: sha256:19fjzwgmfdf832c6b1x885kaiyck03kpiba0qpsxvps04i7b3vj4
  got:    sha256:0f1fpf37ms8d7fhlh3rjzsxsk9w23iyi3phs2i7g561292d5rk3l
cannot build derivation '/nix/store/ha01dcp1wsniq9zzhd0b1laxa7ngryb5-openra-bleed-8ee1102.drv': 1 dependencies couldn't be built
```

**Comment by aanderse** [comment]
@c0bw3b you are correct. Please see https://github.com/NixOS/nixpkgs/pull/61749

**Pull request merged**
