### PR TITLE
R: 4.2.2 -> 4.2.3

### PR DESCRIPTION
**Pull request by jbedo**
R bump to 4.2.3 with associated bump of CRAN/BioC packages. Awaiting hydra to check package tree:
https://hydra.nixos.org/jobset/nixpkgs/r-updates

nixpkgs-review finds a few broken packages:
```
7 packages failed to build:
python310Packages.cnvkit python310Packages.radian python311Packages.cnvkit python311Packages.radian radianWrapper sage sageWithDoc

20 packages built:
R diffoscope ocamlPackages.ocaml-r postgresql11Packages.plr postgresql12Packages.plr postgresql13Packages.plr postgresql14Packages.plr postgresql15Packages.plr python310Packages.rchitect python310Packages.rpy2 python311Packages.rchitect python311Packages.rpy2 quarto rWrapper rstudio rstudio-server rstudioServerWrapper rstudioWrapper spark spark_3_1
```

The new radian package is failing some tests @savyajha :
```
=========================== short test summary info ============================
FAILED tests/test_reticulate.py::test_multiline - Exception: value is
FAILED tests/test_reticulate.py::test_ctrl_d - Exception: value is
FAILED tests/test_reticulate.py::test_completion - Exception: value is
=================== 3 failed, 12 passed in 89.03s (0:01:29) ====================
```

Sage is failing but looks related:
```
error: builder for '/nix/store/wq833qal3jbiw0bw28bb926f0wx68da1-python3.10-sagelib-9.8.drv' failed with exit code 1;
       last 10 log lines:
       >     aliases[var + "CFLAGS"] = pkgconfig.cflags(lib).split()
       >   File "/nix/store/yvm2g5jdizgq7p7i5nfqidbwgxji9dyk-python3.10-pkgconfig-1.5.5/lib/python3.10/site-packages/pkgconfig/pkgconfig.py", line 144, in cflags
       >     _raise_if_not_exists(package)
       >   File "/nix/store/yvm2g5jdizgq7p7i5nfqidbwgxji9dyk-python3.10-pkgconfig-1.5.5/lib/python3.10/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
       >     raise PackageNotFoundError(package)
       > pkgconfig.pkgconfig.PackageNotFoundError: libpng not found
       > ************************************************************************
       > Error building the Sage library
       > ************************************************************************
       > /nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux/setup: line 1593: pop_var_context: head of shell_variables not a function context
```

Pomegranate also has unrelated failures.

### CODE REVIEW

**Comment by savyajha** [comment]
I run on 22.11 or unstable, and if I override R to 4.2.3 radian builds fine locally. I've never debugged build failures on Hydra, and especially not with PRs. What would be the best way to get to the bottom of this?

**Comment by jbedo** [comment]
Checkout the r-updates branch and try building radian.

**Comment by savyajha** [comment]
@jbedo It seems to build fine for me.

```
[genghiz@Voyager ~/Workspace/nixpkgs]% nixpkgs-review pr -p python310Packages.radian 221546
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/221546/head:refs/nixpkgs-review/1
$ git worktree add /home/genghiz/.cache/nixpkgs-review/pr-221546-2/nixpkgs f6e067692dd122e3d4481b34c9de7f0d4c235141
Preparing worktree (detached HEAD f6e067692dd)
Updating files: 100% (34001/34001), done.
HEAD is now at f6e067692dd Merge pull request #119362 from xworld21/texlive-combine-fix-buildenv
$ git merge --no-commit --no-ff a10887cb3fd7087c006b91197b6eb2b8730eebeb
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/genghiz/.cache/nixpkgs-review/pr-221546-2/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/221546

1 package built:
python310Packages.radian

$ /nix/store/znn8hhrmr3vy06vi80ffwj74rsn5d9af-nix-2.11.1/bin/nix-shell /home/genghiz/.cache/nixpkgs-review/pr-221546-2/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-221546-2]$ which radian
/nix/store/0721kc28c9r8v0pdabjycgrqi9p80vml-python3.10-radian-0.6.4/bin/radian

[nix-shell:~/.cache/nixpkgs-review/pr-221546-2]$ radian
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> q()

[nix-shell:~/.cache/nixpkgs-review/pr-221546-2]$ exit
exit
$ git worktree prune
[genghiz@Voyager ~/Workspace/nixpkgs]% nixpkgs-review pr -p python311Packages.radian 221546
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/221546/head:refs/nixpkgs-review/1
$ git worktree add /home/genghiz/.cache/nixpkgs-review/pr-221546-3/nixpkgs f6e067692dd122e3d4481b34c9de7f0d4c235141
Preparing worktree (detached HEAD f6e067692dd)
Updating files: 100% (34001/34001), done.
HEAD is now at f6e067692dd Merge pull request #119362 from xworld21/texlive-combine-fix-buildenv
$ git merge --no-commit --no-ff a10887cb3fd7087c006b91197b6eb2b8730eebeb
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/genghiz/.cache/nixpkgs-review/pr-221546-3/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/221546

1 package built:
python311Packages.radian

$ /nix/store/znn8hhrmr3vy06vi80ffwj74rsn5d9af-nix-2.11.1/bin/nix-shell /home/genghiz/.cache/nixpkgs-review/pr-221546-3/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-221546-3]$ radian
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> q()

[nix-shell:~/.cache/nixpkgs-review/pr-221546-3]$ exit
exit
$ git worktree prune
```

**Comment by jbedo** [comment]
That's great, thanks for testing! It's probably my old hardware
(westmere).

**Comment by jbedo** [comment]
Well the rPackages tree seems pretty healthy, with the exception of Rhdf5lib which affects 549 packages. I tried patching it to use the nixpkgs supplied hdf5 & libaec but there's some more stuff to fix (rhdf5filters) before rhdf5 builds. Worth fixing before merging? hdf5 is probably important to a large number of users.

**Comment by savyajha** [comment]
HDF5 is quite integral to a lot of stuff. If possible I'd recommend making sure it works.

**Comment by nviets** [comment]
Did the posit mirror work as expected?

**Comment by jbedo** [comment]
@nviets it did, the tree looks pretty good on hydra with the exception of hdf5.

**Comment by bcdarwin** [comment]
Looks great to me.  I wonder how maintainable these patches will be but I guess we'll see.

**Review by bcdarwin — APPROVED** [review]

**Comment by jbedo** [comment]
I did give that some thought, the packages shouldn't change much as they
are mostly just compiling the deps we have in nixpkgs, so I think they
should be fairly maintainable. We can reassess in future if this turns
out to be too difficult to maintain.

**Pull request merged**
