### PR TITLE
ombi: 4.0.1292 -> 4.0.1345

### PR DESCRIPTION
**Pull request by andreisergiu98**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120637` at df61cb05 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>ombi</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/servers/ombi/default.nix:37:3:
```
   |
37 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

makeWrapper is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/ombi/default.nix:35:3:
```
   |
35 |   buildInputs = [ makeWrapper patchelf ];
   |   ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@andreabedini please move makeWrapper into nativeBuildInputs.

**Comment by andreabedini** [comment]
@SuperSandro2000 did you mean to reply to @andreisergiu98 ?

**Comment by andreisergiu98** [comment]
@andreabedini yep, that's what I think.

@SuperSandro2000 I changed the derivation a little bit. I saw on hydra that it doesn't build on darwin because of patchelf. So I added `autoPatchelfHook` and `fixDarwinDylibNames`. I also fixed the test suit because it complained about the default user.

**Review by mkg20001 — APPROVED** [review]

**Pull request merged**
