### PR TITLE
snippetpixie: 1.2.2 -> 1.3.1

### PR DESCRIPTION
**Pull request by ianmjones**
###### Motivation for this change

Updated to latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
> Also ran nixfmt for consistent formatting of future changes.

This is more for general nix code, the style the package had before was formatting specific for expressions in nixpkgs https://github.com/nix-community/nixpkgs-fmt. I'd prefer if you reverted it.

**Comment by ianmjones** [comment]
> > Also ran nixfmt for consistent formatting of future changes.
> 
> This is more for general nix code, the style the package had before was formatting specific for expressions in nixpkgs https://github.com/nix-community/nixpkgs-fmt. I'd prefer if you reverted it.

Sorry about that, did not know there are two styles in play. I've completely reverted formatting changes and ran `nixpkgs-fmt` over the file to ensure it conforms to nixpkgs standards.

**Comment by worldofpeace** [comment]
> over the file to ensure it conforms to nixpkgs standards.

Uhnn, we don't have anything really official for this yet... So you can imagine some sort of impending code style battle :rofl:  (hopefully not)
Myself and my collaborators feel strongly about that style being best aligned for nixpkgs, so I recommend it as much as possible.

**Comment by worldofpeace** [comment]
It seems you using wnck makes this not work with wayland. Guess that's reworking to do in the future.

**Review by worldofpeace — APPROVED** [review]
LGTM

**Comment by ianmjones** [comment]
> It seems you using wnck makes this not work with wayland. Guess that's reworking to do in the future.

Yeah, it's a pain, needed more robust window activation notifications to be able to implement the new trigger key checking for apps that aren't very accessibility savvy, hope to find a better solution in the future.

Thanks for the PR review @worldofpeace, much appreciated.

**Pull request merged**
