### PR TITLE
python3Packages.distro: 1.5.0 -> 1.6.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.6.0

Change log: https://github.com/python-distro/distro/blob/master/CHANGELOG.md#160-2021730

- Enable tests

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132300` at e4c0b56f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d925c8ba541484a1a00cef2791eab93f">awscli2</a></li>
    <li><a href="https://gist.github.com/113bf4131f62105f651762f3d65a1596">certbot</a> (python39Packages.certbot)</li>
    <li><a href="https://gist.github.com/1be72487398bdb783ebde34acfaac56e">chipsec</a></li>
    <li><a href="https://gist.github.com/d0d626103254a96859782a8cb92e45e3">conan</a></li>
    <li><a href="https://gist.github.com/8752168a1004e2755b615cef10be250c">python38Packages.certbot</a></li>
    <li><a href="https://gist.github.com/324fb58662961a267d5a225f9f23a83c">python38Packages.certbot-dns-cloudflare</a></li>
    <li><a href="https://gist.github.com/b9e939f6326b0614dedc35ce53157542">python38Packages.certbot-dns-rfc2136</a></li>
    <li><a href="https://gist.github.com/8813e6163cb81f564bafea91cf86522f">python38Packages.certbot-dns-route53</a></li>
    <li><a href="https://gist.github.com/f51cf0e4358e34a1da2b215408f890ad">python38Packages.qiskit-terra</a></li>
    <li><a href="https://gist.github.com/52159d4f76a2246b6fa7a31f0dfb9db6">python39Packages.certbot-dns-cloudflare</a></li>
    <li><a href="https://gist.github.com/d1592a46a70f068d167dc60c577621a8">python39Packages.certbot-dns-rfc2136</a></li>
    <li><a href="https://gist.github.com/e23fd7268ae168e4867e21731d49a3b4">python39Packages.certbot-dns-route53</a></li>
    <li><a href="https://gist.github.com/e916c997954af36c585dc854d9753d82">python39Packages.qiskit</a></li>
    <li><a href="https://gist.github.com/592fa386dcd70b728fa6748a42e69e56">python39Packages.qiskit-aer</a></li>
    <li><a href="https://gist.github.com/17ddd76ba3e09974d1007f1ede5366dd">python39Packages.qiskit-aqua</a></li>
    <li><a href="https://gist.github.com/d2ed212baf7a4de80fd768bf3f9f833a">python39Packages.qiskit-ibmq-provider</a></li>
    <li><a href="https://gist.github.com/19138cdb24389ebbefde94d1ccae2823">python39Packages.qiskit-ignis</a></li>
    <li><a href="https://gist.github.com/f9358b55bcf024a42f55d54a514866b6">python39Packages.qiskit-terra</a></li>
  </ul>
</details>
<details>
  <summary>12 packages skipped due to time constraints:</summary>
  <ul>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>devpi-client</li>
    <li>home-assistant</li>
    <li>hydra-unstable</li>
    <li>pepper</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>57 packages built successfully:</summary>
  <ul>
    <li>arion</li>
    <li>auto-cpufreq</li>
    <li>blocksat-cli (python39Packages.blocksat-cli)</li>
    <li>breezy (python39Packages.breezy)</li>
    <li>cabal2nix</li>
    <li>cozy</li>
    <li>dep2nix</li>
    <li>distgen</li>
    <li>docker-compose</li>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
    <li>flatpak-builder</li>
    <li>gns3-gui</li>
    <li>gns3-server</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>mate.mate-tweak</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>paperwork</li>
    <li>pastebinit</li>
    <li>python38Packages.blocksat-cli</li>
    <li>python38Packages.breezy</li>
    <li>python38Packages.check-manifest</li>
    <li>python38Packages.distro</li>
    <li>python38Packages.google-compute-engine</li>
    <li>python38Packages.h3</li>
    <li>python38Packages.launchpadlib</li>
    <li>python38Packages.lazr-restfulclient</li>
    <li>python38Packages.line_profiler</li>
    <li>python38Packages.openpaperwork-core</li>
    <li>python38Packages.openpaperwork-gtk</li>
    <li>python38Packages.paperwork-backend</li>
    <li>python38Packages.paperwork-shell</li>
    <li>python38Packages.pc-ble-driver-py</li>
    <li>python38Packages.ruyaml</li>
    <li>python38Packages.scikit-build</li>
    <li>python38Packages.tweedledum</li>
    <li>python38Packages.zulip</li>
    <li>python39Packages.check-manifest</li>
    <li>python39Packages.distro</li>
    <li>python39Packages.h3</li>
    <li>python39Packages.launchpadlib</li>
    <li>python39Packages.lazr-restfulclient</li>
    <li>python39Packages.line_profiler</li>
    <li>python39Packages.openpaperwork-core</li>
    <li>python39Packages.openpaperwork-gtk</li>
    <li>python39Packages.paperwork-backend</li>
    <li>python39Packages.paperwork-shell</li>
    <li>python39Packages.ruyaml</li>
    <li>python39Packages.scikit-build</li>
    <li>python39Packages.tweedledum</li>
    <li>python39Packages.zulip</li>
    <li>ssh-import-id</li>
    <li>tahoe-lafs</li>
    <li>vcstool</li>
    <li>zulip-term</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by risicle** [comment]
On macos 10.15, `awscli2` and `conan` fail with simple version-check failures.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 132300` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages-libre.chipsec</li>
<li>linuxPackages_hardkernel_4_14.chipsec</li>
<li>linuxPackages_hardkernel_latest.chipsec</li>
<li>linuxPackages_latest-libre.chipsec</li>
<li>pepper</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>devpi-client: log was empty</li>
  </ul>
</details>
<details>

  <summary>13 packages failed to build and are new build failures:</summary>
  <ul>
<li>awscli2: log was empty</li>
<li>certbot: log was empty</li>
<li>(python39Packages.certbot): log was empty</li>
<li>certbot-full: log was empty</li>
<li>conan: log was empty</li>
<li>paperwork: log was empty</li>
<li>python38Packages.certbot: log was empty</li>
<li>python38Packages.certbot-dns-cloudflare: log was empty</li>
<li>python38Packages.certbot-dns-rfc2136: log was empty</li>
<li>python38Packages.certbot-dns-route53: log was empty</li>
<li>python39Packages.certbot-dns-cloudflare: log was empty</li>
<li>python39Packages.certbot-dns-rfc2136: log was empty</li>
<li>python39Packages.certbot-dns-route53: log was empty</li>
  </ul>
</details>
<details>
<summary>
92 packages built:
</summary>
<ul>
<li>arion</li>
<li>auto-cpufreq</li>
<li>blocksat-cli (python39Packages.blocksat-cli)</li>
<li>breezy (python39Packages.breezy)</li>
<li>cabal2nix</li>
<li>chipsec</li>
<li>cinnamon.cinnamon-common</li>
<li>cinnamon.cinnamon-gsettings-overrides</li>
<li>cinnamon.cinnamon-screensaver</li>
<li>cozy</li>
<li>dep2nix</li>
<li>distgen</li>
<li>docker-compose</li>
<li>dvc</li>
<li>dvc-with-remotes</li>
<li>flatpak-builder</li>
<li>gns3-gui</li>
<li>gns3-server</li>
<li>haskellPackages.cabal2nix-unstable</li>
<li>home-assistant</li>
<li>hydra-unstable</li>
<li>linuxPackages.chipsec (linuxPackages_5_10.chipsec)</li>
<li>linuxPackages_4_14.chipsec</li>
<li>linuxPackages_4_19.chipsec</li>
<li>linuxPackages_4_4.chipsec</li>
<li>linuxPackages_4_9.chipsec</li>
<li>linuxPackages_5_12.chipsec</li>
<li>linuxPackages_5_13.chipsec (linuxPackages_latest.chipsec)</li>
<li>linuxPackages_5_4.chipsec</li>
<li>linuxPackages_hardened.chipsec</li>
<li>linuxPackages_latest_hardened.chipsec</li>
<li>linuxPackages_lqx.chipsec</li>
<li>linuxPackages_testing_bcachefs.chipsec</li>
<li>linuxPackages_xanmod.chipsec</li>
<li>linuxPackages_zen.chipsec</li>
<li>lutris</li>
<li>lutris-free</li>
<li>lutris-unwrapped</li>
<li>mate.mate-tweak</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-scripts</li>
<li>nix-update-source</li>
<li>pastebinit</li>
<li>python38Packages.blocksat-cli</li>
<li>python38Packages.breezy</li>
<li>python38Packages.check-manifest</li>
<li>python38Packages.distro</li>
<li>python38Packages.google-compute-engine</li>
<li>python38Packages.h3</li>
<li>python38Packages.launchpadlib</li>
<li>python38Packages.lazr-restfulclient</li>
<li>python38Packages.line_profiler</li>
<li>python38Packages.openpaperwork-core</li>
<li>python38Packages.openpaperwork-gtk</li>
<li>python38Packages.paperwork-backend</li>
<li>python38Packages.paperwork-shell</li>
<li>python38Packages.pc-ble-driver-py</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-aer</li>
<li>python38Packages.qiskit-aqua</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.qiskit-ignis</li>
<li>python38Packages.qiskit-terra</li>
<li>python38Packages.ruyaml</li>
<li>python38Packages.scikit-build</li>
<li>python38Packages.tweedledum</li>
<li>python38Packages.zulip</li>
<li>python39Packages.check-manifest</li>
<li>python39Packages.distro</li>
<li>python39Packages.h3</li>
<li>python39Packages.launchpadlib</li>
<li>python39Packages.lazr-restfulclient</li>
<li>python39Packages.line_profiler</li>
<li>python39Packages.openpaperwork-core</li>
<li>python39Packages.openpaperwork-gtk</li>
<li>python39Packages.paperwork-backend</li>
<li>python39Packages.paperwork-shell</li>
<li>python39Packages.qiskit</li>
<li>python39Packages.qiskit-aer</li>
<li>python39Packages.qiskit-aqua</li>
<li>python39Packages.qiskit-ibmq-provider</li>
<li>python39Packages.qiskit-ignis</li>
<li>python39Packages.qiskit-terra</li>
<li>python39Packages.ruyaml</li>
<li>python39Packages.scikit-build</li>
<li>python39Packages.tweedledum</li>
<li>python39Packages.zulip</li>
<li>salt</li>
<li>ssh-import-id</li>
<li>tahoe-lafs</li>
<li>vcstool</li>
<li>zulip-term</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
cerbot:

```
E       DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
....
================= 154 failed, 800 passed, 20 skipped in 31.39s =================
```


conan:

```
> ERROR: Could not find a version that satisfies the requirement distro<=1.5.0,>=1.0.2 (from conan) (from versions: none)
> ERROR: No matching distribution found for distro<=1.5.0,>=1.0.2
```

awcli:

```
> ERROR: Could not find a version that satisfies the requirement distro<1.6.0,>=1.5.0 (from awscli) (from versions: none)
> ERROR: No matching distribution found for distro<1.6.0,>=1.5.0
```

paperwork:

```
tex/latex/lm/omxlmex.fd)

LaTeX Warning: No \author given.

[1{/nix/store/cdh1dzrpzr1xak5lrdgf0rs99rnmvnm0-texlive-combined-2021/share/texm
f-var/fonts/map/pdftex/updmap/pdftex.map} <./data/intro.png>]
Overfull \hbox (9.68018pt too wide) in paragraph at lines 60--61
 [][]

Underfull \hbox (badness 1348) in paragraph at lines 63--68
error: [json.exception.type_error.316] invalid UTF-8 byte at index 35: 0xFC
```

**Comment by fabaff** [comment]
Part of #135832

**Pull request closed without merging**
