### PR TITLE
[DRAFT] libcosmicAppHook: init

### PR DESCRIPTION
**Pull request by nyabinary**
## Description of changes
Adds libcosmicAppHook for libcosmic apps.
Upstreamed from [nixos-cosmic](https://github.com/lilyinstarlight/nixos-cosmic) by @lilyinstarlight 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Please make sure to explain the motivation in the commit message.  At first glance this looks very complicated…

**Comment by nyabinary** [comment]
> Please make sure to explain the motivation in the commit message. At first glance this looks very complicated…

It simplifies building and packaging all apps made with libcosmic, also there is the fact that there was no hook for building libcosmic apps before, so every maintainer freestyled it. This provides a level of standarization.

**Review by winterqt — CHANGES_REQUESTED** [review]
Do you feel comfortable enough maintaining this for Nixpkgs on your own, or are you going to keep plucking changes from Lily's repo?

I feel like lifting this from a perfectly working flake without actually adding it to any existing packages (does it even work with them?) is maybe not the best of ideas.

**Comment by GetPsyched** [comment]
Those are reasonable concerns.

1. I'll most likely be maintaining the hook and other COSMIC related tools with them (will probably have a separate PR to init a COSMIC team, like gnome and kde).
2. The next step is to update all of the existing packages in nixpkgs to use this hook, which is why the PR is still marked as a draft. Both of us are pre-occupied ATM and will get to this as soon as we can.

**Review by Lord-Valen — CHANGES_REQUESTED** [review]
As is, this needs attribution to @lilyinstarlight by inclusion of the nixos-cosmic license.

**Comment by nyabinary** [comment]
Superseded by #339287 #292601

**Pull request closed without merging**
