### PR TITLE
brightbox-image: switch to use the common make-disk-image.nix

### PR DESCRIPTION
**Pull request by copumpkin**
###### Motivation for this change

Avoid duplication. I can't test this unfortunately; @rbvermaa do you have an easy way to test it before we merge? I don't want to break it.

Also, for #24973, I'm curious if you have ideas for what it would mean to write a VM test to simulate Brightbox (which I'd never even heard of until I searched for duplicated image generation code 😄)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by copumpkin** [comment]
Ping @rbvermaa 😄

**Comment by copumpkin** [comment]
Ping @rbvermaa again 😄

**Comment by mmahut** [comment]
Any update on this pull request?

**Comment by mmahut** [comment]
Closing due to lack of activity, feel free to reopen this if needed.

**Pull request closed without merging**
