### PR TITLE
pythonPackages.docker: 4.4.4 -> 5.0.0, docker-compose: 1.28.6 -> 1.29.2

### PR DESCRIPTION
**Pull request by endocrimes**
###### Motivation for this change

docker-compose 1.29.x depends on v5 or newer of the python Docker package. Here we update both together, as older docker-compose is untested with newer python docker packages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130322` at 8fd04c72 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/bae0db774e82f29326325132d85cb698">mlflow-server</a></li>
    <li><a href="https://gist.github.com/df4b7e81b2d9ad6b5e2f342fca55e4b0">python38Packages.flower</a></li>
    <li><a href="https://gist.github.com/94f1a008fe4ffb6fa99f1404d474c287">python38Packages.mlflow</a></li>
    <li><a href="https://gist.github.com/0e840c01972e68827a1a43c0c015473b">python39Packages.flower</a></li>
    <li><a href="https://gist.github.com/42058307e228bb62ba34e7d88d078e20">python39Packages.mlflow</a></li>
  </ul>
</details>
<details>
  <summary>3 packages skipped due to time constraints:</summary>
  <ul>
    <li>python38Packages.tensorboardx</li>
    <li>python39Packages.tensorboardx</li>
    <li>tts</li>
  </ul>
</details>
<details>
  <summary>31 packages built successfully:</summary>
  <ul>
    <li>arion</li>
    <li>aws-sam-cli</li>
    <li>docker-compose</li>
    <li>fdroidserver</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.django-raster</li>
    <li>python38Packages.djmail</li>
    <li>python38Packages.docker</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyter-repo2docker</li>
    <li>python38Packages.moto</li>
    <li>python38Packages.tern</li>
    <li>python39Packages.celery</li>
    <li>python39Packages.django-raster</li>
    <li>python39Packages.djmail</li>
    <li>python39Packages.docker</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyter-repo2docker</li>
    <li>python39Packages.moto</li>
    <li>python39Packages.tern</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by endocrimes** [comment]
Result of `nixpkgs-review pr 130322` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>mlflow-server</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.mlflow</li>
    <li>python39Packages.flower</li>
    <li>python39Packages.mlflow</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>buildbot (python38Packages.buildbot)</li>
    <li>buildbot-full (python38Packages.buildbot-full)</li>
    <li>buildbot-ui (python38Packages.buildbot-ui)</li>
    <li>python38Packages.dockerspawner</li>
    <li>python39Packages.buildbot</li>
    <li>python39Packages.buildbot-full</li>
    <li>python39Packages.buildbot-ui</li>
  </ul>
</details>
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>arion</li>
    <li>aws-sam-cli</li>
    <li>docker-compose (docker_compose)</li>
    <li>fdroidserver</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.django-raster</li>
    <li>python38Packages.djmail</li>
    <li>python38Packages.docker</li>
    <li>python38Packages.jupyter-repo2docker</li>
    <li>python38Packages.moto</li>
    <li>python38Packages.tensorboardx</li>
    <li>python38Packages.tern</li>
    <li>python39Packages.celery</li>
    <li>python39Packages.django-raster</li>
    <li>python39Packages.djmail</li>
    <li>python39Packages.docker</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyter-repo2docker</li>
    <li>python39Packages.moto</li>
    <li>python39Packages.tensorboardx</li>
    <li>python39Packages.tern</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>tts</li>
  </ul>
</details>

**Comment by endocrimes** [comment]
- Looks like buildbot is broken on current master, because nix SQLAlchemy is too new, so not relevant to this PR
- dockerspawner might be flaky? - It built successfully when trying again by hand with `nix-build`, and upstream doesn't specify any version requirements for it, so I'm gonna say this can be ignored.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130322` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>mlflow-server</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.mlflow</li>
    <li>python39Packages.flower</li>
    <li>python39Packages.mlflow</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>buildbot (python38Packages.buildbot)</li>
    <li>buildbot-full (python38Packages.buildbot-full)</li>
    <li>buildbot-ui (python38Packages.buildbot-ui)</li>
    <li>python39Packages.buildbot</li>
    <li>python39Packages.buildbot-full</li>
    <li>python39Packages.buildbot-ui</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>arion</li>
    <li>aws-sam-cli</li>
    <li>docker-compose</li>
    <li>fdroidserver</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.django-raster</li>
    <li>python38Packages.djmail</li>
    <li>python38Packages.docker</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyter-repo2docker</li>
    <li>python38Packages.moto</li>
    <li>python38Packages.tensorboardx</li>
    <li>python38Packages.tern</li>
    <li>python39Packages.celery</li>
    <li>python39Packages.django-raster</li>
    <li>python39Packages.djmail</li>
    <li>python39Packages.docker</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyter-repo2docker</li>
    <li>python39Packages.moto</li>
    <li>python39Packages.tensorboardx</li>
    <li>python39Packages.tern</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>tts</li>
  </ul>
</details>

**Review by amaxine — APPROVED** [review]
The build failures are, as noted, unrelated to the PR. `docker-compose` works fine. :+1:

**Pull request merged**
