### PR TITLE
zchunk: 1.4.0 -> 1.5.1

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 331432` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>microdnf: <a href="https://termbin.com/jrby">plain log</a></li>
<li>python311Packages.conda: log was empty</li>
<li>python312Packages.conda: log was empty</li>
  </ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>python311Packages.conda.dist: log was empty</li>
<li>python312Packages.conda.dist: log was empty</li>
  </ul>
</details>
<details>
<summary>
44 packages built:
</summary>
<ul>
<li>createrepo_c</li>
<li>dnf-plugins-core (python312Packages.dnf-plugins-core)</li>
<li>dnf-plugins-core.man (python312Packages.dnf-plugins-core.man)</li>
<li>dnf4</li>
<li>dnf4.man</li>
<li>dnf4.py</li>
<li>dnf5</li>
<li>dnf5.man</li>
<li>libdnf</li>
<li>libdnf.dev</li>
<li>libdnf.py (python312Packages.libdnf ,python312Packages.libdnf.dev ,python312Packages.libdnf.py)</li>
<li>libmamba</li>
<li>librepo</li>
<li>librepo.dev</li>
<li>librepo.py (python312Packages.librepo ,python312Packages.librepo.dev ,python312Packages.librepo.py)</li>
<li>libsolv</li>
<li>micromamba</li>
<li>python311Packages.conda-libmamba-solver</li>
<li>python311Packages.conda-libmamba-solver.dist</li>
<li>python311Packages.dnf-plugins-core</li>
<li>python311Packages.dnf-plugins-core.man</li>
<li>python311Packages.dnf4</li>
<li>python311Packages.dnf4.man</li>
<li>python311Packages.dnf4.py</li>
<li>python311Packages.libdnf (python311Packages.libdnf.dev ,python311Packages.libdnf.py)</li>
<li>python311Packages.libmambapy</li>
<li>python311Packages.libmambapy.dist</li>
<li>python311Packages.librepo (python311Packages.librepo.dev ,python311Packages.librepo.py)</li>
<li>python312Packages.conda-libmamba-solver</li>
<li>python312Packages.conda-libmamba-solver.dist</li>
<li>python312Packages.dnf4</li>
<li>python312Packages.dnf4.man</li>
<li>python312Packages.dnf4.py</li>
<li>python312Packages.libmambapy</li>
<li>python312Packages.libmambapy.dist</li>
<li>rpm-ostree</li>
<li>rpm-ostree.dev</li>
<li>rpm-ostree.devdoc</li>
<li>rpm-ostree.man</li>
<li>tdnf</li>
<li>zchunk</li>
<li>zchunk.dev</li>
<li>zchunk.lib</li>
<li>zchunk.man</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
createrepo_c:
<details>

warning: EvalError
Cannot evaluate attribute ‘createrepo_c’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
dnf4:
<details>

warning: EvalError
Cannot evaluate attribute ‘dnf4’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
dnf5:
<details>

warning: EvalError
Cannot evaluate attribute ‘dnf5’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
libdnf:
<details>

warning: EvalError
Cannot evaluate attribute ‘libdnf’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
libmamba:
<details>

warning: EvalError
Cannot evaluate attribute ‘libmamba’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
librepo:
<details>

warning: EvalError
Cannot evaluate attribute ‘librepo’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
libsolv:
<details>

warning: EvalError
Cannot evaluate attribute ‘libsolv’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
microdnf:
<details>

warning: EvalError
Cannot evaluate attribute ‘microdnf’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
micromamba:
<details>

warning: EvalError
Cannot evaluate attribute ‘micromamba’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
python311Packages.conda-libmamba-solver.dist:
<details>

got build log for '/nix/store/nfb8s69lz0r49k80vpir6ahw7avb3xyv-python3.11-conda-libmamba-solver-24.7.0-dist' from 'daemon'
When evaluating attribute ‘python311Packages.conda-libmamba-solver.dist’:
warning: python-include-tests
Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/conda-libmamba-solver/default.nix:40:

```
   |
40 |     description = "Libmamba based solver for conda";
   | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md
</details>
python311Packages.conda-libmamba-solver:
<details>

got build log for '/nix/store/m6gb3wrqhnqq5zcma8iwd29qhq24siv6-python3.11-conda-libmamba-solver-24.7.0' from 'daemon'
When evaluating attribute ‘python311Packages.conda-libmamba-solver’:
warning: python-include-tests
Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/conda-libmamba-solver/default.nix:40:

```
   |
40 |     description = "Libmamba based solver for conda";
   | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md
</details>
python312Packages.conda-libmamba-solver.dist:
<details>

got build log for '/nix/store/k8bhaq1smivyq3v9xz8rgq6l0ac0ihpd-python3.12-conda-libmamba-solver-24.7.0-dist' from 'daemon'
When evaluating attribute ‘python312Packages.conda-libmamba-solver.dist’:
warning: python-include-tests
Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/conda-libmamba-solver/default.nix:40:

```
   |
40 |     description = "Libmamba based solver for conda";
   | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md
</details>
python312Packages.conda-libmamba-solver:
<details>

got build log for '/nix/store/1ygs7zdxf77czh60s0x2m080lxkh0i1d-python3.12-conda-libmamba-solver-24.7.0' from 'daemon'
When evaluating attribute ‘python312Packages.conda-libmamba-solver’:
warning: python-include-tests
Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/conda-libmamba-solver/default.nix:40:

```
   |
40 |     description = "Libmamba based solver for conda";
   | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md
</details>
rpm-ostree:
<details>

warning: EvalError
Cannot evaluate attribute ‘rpm-ostree’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
tdnf:
<details>

warning: EvalError
Cannot evaluate attribute ‘tdnf’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
zchunk:
<details>

warning: EvalError
Cannot evaluate attribute ‘zchunk’ in ‘/nix/store/7izz0k8gilnlz4wii96qkq0rb897r9s1-nixpkgs’.
</details>
</details>

**Comment by AndersonTorres** [comment]
Conda error looks unrelated.

**Comment by gador** [comment]
Agreed 👍

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 331432` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>49 packages built:</summary>
  <ul>
    <li>createrepo_c</li>
    <li>dnf-plugins-core (python312Packages.dnf-plugins-core)</li>
    <li>dnf-plugins-core.man (python312Packages.dnf-plugins-core.man)</li>
    <li>dnf4</li>
    <li>dnf4.man</li>
    <li>dnf4.py</li>
    <li>dnf5</li>
    <li>dnf5.man</li>
    <li>libdnf</li>
    <li>libdnf.dev</li>
    <li>libdnf.py (python312Packages.libdnf ,python312Packages.libdnf.dev ,python312Packages.libdnf.py)</li>
    <li>libmamba</li>
    <li>librepo</li>
    <li>librepo.dev</li>
    <li>librepo.py (python312Packages.librepo ,python312Packages.librepo.dev ,python312Packages.librepo.py)</li>
    <li>libsolv</li>
    <li>microdnf</li>
    <li>micromamba</li>
    <li>python311Packages.conda</li>
    <li>python311Packages.conda-libmamba-solver</li>
    <li>python311Packages.conda-libmamba-solver.dist</li>
    <li>python311Packages.conda.dist</li>
    <li>python311Packages.dnf-plugins-core</li>
    <li>python311Packages.dnf-plugins-core.man</li>
    <li>python311Packages.dnf4</li>
    <li>python311Packages.dnf4.man</li>
    <li>python311Packages.dnf4.py</li>
    <li>python311Packages.libdnf (python311Packages.libdnf.dev ,python311Packages.libdnf.py)</li>
    <li>python311Packages.libmambapy</li>
    <li>python311Packages.libmambapy.dist</li>
    <li>python311Packages.librepo (python311Packages.librepo.dev ,python311Packages.librepo.py)</li>
    <li>python312Packages.conda</li>
    <li>python312Packages.conda-libmamba-solver</li>
    <li>python312Packages.conda-libmamba-solver.dist</li>
    <li>python312Packages.conda.dist</li>
    <li>python312Packages.dnf4</li>
    <li>python312Packages.dnf4.man</li>
    <li>python312Packages.dnf4.py</li>
    <li>python312Packages.libmambapy</li>
    <li>python312Packages.libmambapy.dist</li>
    <li>rpm-ostree</li>
    <li>rpm-ostree.dev</li>
    <li>rpm-ostree.devdoc</li>
    <li>rpm-ostree.man</li>
    <li>tdnf</li>
    <li>zchunk</li>
    <li>zchunk.dev</li>
    <li>zchunk.lib</li>
    <li>zchunk.man</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Pull request merged**
