### PR TITLE
~/.xprofile and ~/.xsession can be symbolic links

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
cc @edolstra

**Comment by lethalman** [comment]
Well, better `readlink -f` than `readlink`.

**Comment by edolstra** [comment]
Hm, not sure what the problem is... `test -f` works fine on symlinks, doesn't it?

**Comment by henrytill** [comment]
I've been using an a symlinked `~/.xsession` with no problems.

**Comment by DamienCassou** [comment]
Thanks for reviewing it. I don't know why I had a problem with that :-(. Sorry.

**Pull request closed without merging**
