### PR TITLE
Rstudio upgrade

### PR DESCRIPTION
**Pull request by averelld**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
I built locally and ran the program. I haven't used R in over 10 years... but from the very little I could remember LGTM :+1:

**Comment by aanderse** [comment]
@GrahamcOfBorg build rstudio

**Comment by aanderse** [comment]
@averelld after going through this in more detail I don't see any issues.
If I don't hear anything back from @ehmry, @changlinli, or @ciil in the next day or two we can go ahead and merge.

Thanks for your work on this :+1:

**Review by ciil — APPROVED** [review]
Just tested some of my use cases, nothing broke, so lgtm. Thanks for updating!

**Comment by aanderse** [comment]
@averelld Sorry this took so long. Thanks again! :tada:

**Comment by changlinli** [comment]
Late to the draw, but FWIW everything LGTM as well. My use cases still work. Thanks for the update!

**Comment by aanderse** [comment]
@changlinli always nice to have extra validation. Thanks!

**Pull request merged**
