### PR TITLE
charybdis: support ziplinks by default

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

- Support ziplinks by providing zlib in the context.
- Add myself as a maintainer as I run a small IRC server for a community using Charybdis and build a complicated module on the top of it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Charybdis is unmaintained and you should migrate to Solanum, where ziplinks have been culled.

**Comment by RaitoBezarius** [comment]
> Charybdis is unmaintained and you should migrate to Solanum, where ziplinks have been culled.

I do agree, but I think we can afford very basic maintenance for the next 1-2 months, right? I mean, has your network migrated to Solanum yet? We are soon there.

**Comment by mweinelt** [comment]
We are working on the migration to NixOS and Solanum over at https://codeberg.org/hackint/nixos-config.

What I'm saying is: Sure, you can migrate charybdis here all you want, but don't rely on ziplinks, because they're going to go away once you migrate, which you should.

**Comment by mweinelt** [comment]
Not sure how we can get rid of that CI error.

**Comment by RaitoBezarius** [comment]
> We are working on the migration to NixOS and Solanum over at https://codeberg.org/hackint/nixos-config.
> 
> What I'm saying is: Sure, you can migrate charybdis here all you want, but don't rely on ziplinks, because they're going to go away once you migrate, which you should.

Ah, sorry, misunderstood. You're right, I forgot about that. Hm, do you think it's better to let downstream users do their overrides then? I can just edit it to add myself as a maintainer as I want to be pinged on this derivation anyway.

**Comment by RaitoBezarius** [comment]
> Not sure how we can get rid of that CI error.

I can redo the PR if needed at all.

**Pull request closed without merging**
