### PR TITLE
anydesk: add update script

### PR DESCRIPTION
**Pull request by mkg20001**
###### Motivation for this change

Make it auto-update

###### Things done

Don't know if this is the right way to do things. Also doesn't fully work yet, just the standalone script works if executed in the right folder.

Having some kindof wrapper / wrapper function would be cool.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
> Make it auto-update

This won't happen automatically, see https://discourse.nixos.org/t/questions-regarding-passthru-updatescript/7315 .

If you are still interested in this, you should also read https://nixos.org/nixpkgs/manual/#var-passthru-updateScript .

> Having some kindof wrapper / wrapper function would be cool.

Use a `nix-shell` shebang, as demonstrated in the example of the manual.

**Comment by SuperSandro2000** [comment]
@mkg20001 friendly ping

**Comment by ajs124** [comment]
@r-ryantm already seems to update this, see  #111146

**Comment by ryantm** [comment]
> r-ryantm already seems to update this

Note it fails to update all the platforms.

**Comment by ajs124** [comment]
There is only one platform left.

**Comment by mkg20001** [comment]
I suppose I can close it then. If anyone still thinks this script is necessary, just comment.

**Pull request closed without merging**
