### PR TITLE
nixos/update-users-groups: add support for account expiry

### PR DESCRIPTION
**Pull request by r-vdp**
## Description of changes

Complete  #203792 by adding a NixOS test and fixing the perl script so that it also works for newly created users.

Original PR description:
Add users.users.<name>.expires. This allows giving temporary access to a user to a machine, and not have
to remember to remove it afterwards.

Ping: @zimbatm @RaitoBezarius

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]

**Comment by zimbatm** [comment]
thanks, looks good to go to me.

**Review by fpletz — APPROVED** [review]

**Comment by lopsided98** [comment]
This breaks cross-compiled NixOS because `DateTime` depends on `Testutf8`, which doesn't cross-compile, see: #198548

**Comment by RaitoBezarius** [comment]
I will be going on holidays soon so apologies for not being able to deal with this, @lopsided98 how much realistic do you believe it is to fix the issue? Does it fail cross compilation on *all targets* or only armv7l?

**Comment by lopsided98** [comment]
It should fail on all targets, since it has something to do with the use of miniperl when cross-compiling. Personally, I have observed the failure on armv5tel, armv6l and armv7l.

**Comment by Majiir** [comment]
A commenter [here](https://github.com/NixOS/nixpkgs/issues/198548#issuecomment-1481208988) reports it broken cross-compiling for `aarch64` as well.

**Comment by R-VdP** [comment]
I think we can use `Time::Piece` instead which does cross compile and also offers the needed functions. It's also a smaller library.

I'll test this and make a PR.

**Pull request merged**
