### PR TITLE
Deprecate --install-grub in favor of --install-bootloader for nixos-rebuild

### LINKED ISSUE #14293: nixos-rebuild: --install-grub should be renamed --install-bootloader
I was using gummiboot and struggling to figure out how to reinstall it. This option should be aliased and deprecated in favor of "--install-bootloader" or the like, and the manpage updated to be agnostic of the bootloader selected in configuration.nix, since the correct behavior is already in place (--install-grub reinstalls gummiboot properly).

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #14293

### CODE REVIEW

**Comment by shlevy** [comment]
Note: I haven't yet tested this!

**Comment by shlevy** [comment]
@elitak Can you test?

**Comment by obadz** [comment]
While we are at this, can we make it so that if `NIXOS_INSTALL_BOOTLOADER=0`, then the bootloader is *not* installed?

Right now if `NIXOS_INSTALL_BOOTLOADER=0`, then this line: https://github.com/shlevy/nixpkgs/blob/b4954a8f3802ba545933905428a4288622f28294/nixos/modules/system/boot/loader/grub/install-grub.pl#L515 decides to install the bootloader if any of the other conditions is `true`. That should only be the right behavior if `NIXOS_INSTALL_BOOTLOADER` is empty?

**Comment by obadz** [comment]
LGTM :+1:

**Comment by elitak** [comment]
I cherry-picked the commit and was able to run with `--install-bootloader`. Everything seemed okay, but I didn't do any rigorous testing.

In the manual changes, maybe give a hint for where the "relevant options" are in the options tree.

Thanks for the fix.

**Pull request merged**
