### PR TITLE
youtube-dl: 2020.11.26 -> 2020.11.29

### PR DESCRIPTION
**Pull request by Luflosi**
###### Motivation for this change
https://github.com/ytdl-org/youtube-dl/releases/tag/2020.11.29

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by lukegb — APPROVED** [review]
WFM.

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 105341` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>bomi</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>catt</li>
    <li>celluloid</li>
    <li>curseradio</li>
    <li>haskellPackages.cut-the-crap</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>kodi-cli</li>
    <li>lollypop</li>
    <li>minitube</li>
    <li>mkchromecast</li>
    <li>mopidy-youtube</li>
    <li>mpc-qt</li>
    <li>mps-youtube</li>
    <li>mpv</li>
    <li>persepolis</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>python27Packages.pafy</li>
    <li>python27Packages.youtube-dl</li>
    <li>python27Packages.youtube-dl-light</li>
    <li>python37Packages.mpv</li>
    <li>python37Packages.pafy</li>
    <li>python37Packages.youtube-dl</li>
    <li>python37Packages.youtube-dl-light</li>
    <li>python38Packages.mpv</li>
    <li>python38Packages.pafy</li>
    <li>youtube-dl (python38Packages.youtube-dl)</li>
    <li>youtube-dl-light (python38Packages.youtube-dl-light)</li>
    <li>qimgv</li>
    <li>somafm-cli</li>
    <li>sublime-music</li>
    <li>tartube</li>
    <li>tuijam</li>
    <li>ytcc</li>
  </ul>
</details>

**Comment by RaghavSood** [comment]
bomi is broken on master as well

**Review by RaghavSood — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Thanks! Ported to stable as ae47c79479a086e96e2977c61e538881913c0c08.

**Pull request merged**
