### PR TITLE
flowtime: remove unused dependencies

### PR DESCRIPTION
**Pull request by arthsmn**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Review by pokon548 — APPROVED** [review]
```nixpkgs-review pr --print-result 272124```

1 package built:
flowtime

Result of `nixpkgs-review pr 272124` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flowtime</li>
  </ul>
</details>

**Comment by pbsds** [comment]
Please mark `broken = stdenv.isDarwin`

**Comment by arthsmn** [comment]
@pbsds @SuperSandro2000 isn't it better to use `platforms = platforms.linux` ?

**Comment by CactiChameleon9** [comment]
Was this PR tested? I am getting the following error when launching flowtime:
```
(flowtime:174544): GStreamer-Play-ERROR **: 20:56:06.881: GstPlay: 'playbin' element not found, please check your setup
fish: Job 1, 'flowtime' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by arthsmn** [comment]
> Was this PR tested? I am getting the following error when launching flowtime:
> 
> ```
> (flowtime:174544): GStreamer-Play-ERROR **: 20:56:06.881: GstPlay: 'playbin' element not found, please check your setup
> fish: Job 1, 'flowtime' terminated by signal SIGTRAP (Trace or breakpoint trap)
> ```
> 
> Swapping to flowtime at [0c6d8c7](https://github.com/NixOS/nixpkgs/commit/0c6d8c783336a59f4c59d4a6daed6ab269c4b361) (before this PR) I can launch without any issues.

I'm sorry, I don't know what happened. I created a PR with the fix, reverting the gstreamer part and also adding a missing dependency.

**Pull request merged**
