### PR TITLE
slack: 3.4.2 -> 4.0.0

### PR DESCRIPTION
**Pull request by angristan**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build slack

**Comment by mmahut** [comment]
``slack-black`` fails with:

```
  /nix/store/z31z45vbgirlw8zkkwih3qcf5zwazaw1-stdenv-linux/setup: line 1308: /nix/store/kywhj59jhccivha8gpid98vqg53dpm9x-slack-4.0.0/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js: No such file or directory
```

**Comment by angristan** [comment]
You mean `slack-dark`?

**Comment by mmahut** [comment]
Correct, sorry, typo :)

**Comment by angristan** [comment]
We have a bit of work to do : https://gist.github.com/jonathanlaf/91c52daa07f12ec987952d7c6697dd9c#gistcomment-2970913

https://github.com/LanikSJ/slack-dark-mode/commit/425e93bfcb5810b64cba9d88bcc27ed509f4714c

**Comment by angristan** [comment]
I got this working:

```patch
diff --git a/pkgs/applications/networking/instant-messengers/slack/default.nix b/pkgs/applications/networking/instant-messengers/slack/default.nix
index 47a2131eb5f..64e7c93062a 100644
--- a/pkgs/applications/networking/instant-messengers/slack/default.nix
+++ b/pkgs/applications/networking/instant-messengers/slack/default.nix
@@ -1,7 +1,7 @@
 { theme ? null, stdenv, fetchurl, dpkg, makeWrapper , alsaLib, atk, cairo,
 cups, curl, dbus, expat, fontconfig, freetype, glib , gnome2, gtk3, gdk_pixbuf,
 libappindicator-gtk3, libnotify, libxcb, nspr, nss, pango , systemd, xorg,
-at-spi2-atk, libuuid
+at-spi2-atk, libuuid, nodePackages
 }:
 
 let
@@ -66,7 +66,7 @@ in stdenv.mkDerivation {
     gtk3  # needed for GSETTINGS_SCHEMAS_PATH
   ];
 
-  nativeBuildInputs = [ makeWrapper ];
+  nativeBuildInputs = [ makeWrapper nodePackages.asar ];
 
   dontUnpack = true;
   buildCommand = ''
@@ -93,20 +93,24 @@ in stdenv.mkDerivation {
       --replace /usr/bin/ $out/bin/ \
       --replace /usr/share/ $out/share/
   '' + stdenv.lib.optionalString (theme != null) ''
-    cat <<EOF >> $out/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js
+    asar extract  $out/lib/slack/resources/app.asar $out/lib/slack/resources/app.asar.unpacked
+    cat <<EOF >> $out/lib/slack/resources/app.asar.unpacked/dist/ssb-interop.bundle.js
+    // First make sure the wrapper app is loaded
     document.addEventListener('DOMContentLoaded', function() {
-    let tt__customCss = ".menu ul li a:not(.inline_menu_link) {color: #fff !important;}"
-    $.ajax({
-        url: '${theme}/theme.css',
-        success: function(css) {
-            \$("<style></style>").appendTo('head').html(css + tt__customCss);
-            \$("<style></style>").appendTo('head').html('#reply_container.upload_in_threads .inline_message_input_container {background: padding-box #545454}');
-            \$("<style></style>").appendTo('head').html('.p-channel_sidebar {background: #363636 !important}');
-            \$("<style></style>").appendTo('head').html('#client_body:not(.onboarding):not(.feature_global_nav_layout):before {background: inherit;}');
-        }
+      // Fetch our CSS in parallel ahead of time
+      const cssPath = 'https://raw.githubusercontent.com/caiceA/slack-raw/master/slack-4';
+      let cssPromise = fetch(cssPath).then((response) => response.text());
+
+      // Insert a style tag into the wrapper view
+      cssPromise.then((css) => {
+        let s = document.createElement('style');
+        s.type = 'text/css';
+        s.innerHTML = css;
+        document.head.appendChild(s);
       });
     });
     EOF
+    asar pack  $out/lib/slack/resources/app.asar.unpacked $out/lib/slack/resources/app.asar
   '';
 
   meta = with stdenv.lib; {
```

Source: https://github.com/widget-/slack-black-theme/issues/98#issuecomment-511449693

With `fetch` we should be able to load the file from the theme in `slack-dark`, but I did not get it working yet.

**Comment by Gonzih** [comment]
@angristan you cant use ajax/fetch api on local fs in electron. You might be interested in this fix for slack-dark https://github.com/NixOS/nixpkgs/pull/65156

**Comment by angristan** [comment]
Thanks! This is not enough for Slack 4.0.0 though

**Comment by angristan** [comment]
Since #65156 has been merge I've rebased my branch on master

**Comment by NeQuissimus** [comment]
I think I fixed it

**Comment by NeQuissimus** [comment]
@ofborg build slack slack-dark

**Comment by angristan** [comment]
Yes it is working although the theme is not very good looking

**Comment by mmahut** [comment]
Yes, it's still broken. Some parts are not dark.

**Comment by NeQuissimus** [comment]
But that would be an issue with the theme, not our packaging?!

**Comment by mmahut** [comment]
> But that would be an issue with the theme, not our packaging?!

If I understand it correctly, the "theme" is coming from our packaging.

**Comment by NeQuissimus** [comment]
Right but it's somebody else's code. If it doesn't work correctly, that should be fixed upstream.
In this case, we'll need lacour/slack-night-mode#235

**Comment by mmahut** [comment]
> Right but it's somebody else's code. If it doesn't work correctly, that should be fixed upstream.
> In this case, we'll need [laCour/slack-night-mode#235](https://github.com/laCour/slack-night-mode/issues/235)

I'm little bit confused, who's code is it if not ours? Isn't the https://github.com/NixOS/nixpkgs/blob/500325de6b3140a1c8887ff6bd035ded16eaeba0/pkgs/applications/networking/instant-messengers/slack/default.nix#L104 written by us?

**Comment by angristan** [comment]
@mmahut Indeed I don't think there should be any inline CSS in there since this part is supposed to work for any theme. The actual theme is here though:

https://github.com/NixOS/nixpkgs/blob/500325de6b3140a1c8887ff6bd035ded16eaeba0/pkgs/applications/networking/instant-messengers/slack/dark-theme.nix#L12

**Comment by NeQuissimus** [comment]
That custom css also came from upstream but I agree it should be removed.
If somebody could do that I wouldn't be opposed to merging this and getting the update in.

**Comment by angristan** [comment]
LGTM :+1:

**Comment by mmahut** [comment]
So, if I understand it correctly, the broken theme is an upstream regression, not ours?

**Comment by angristan** [comment]
Yes!

**Pull request merged**
