### PR TITLE
biblatex-check: 2019-11-09 -> 1.0.1

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Update to tagged + official release!

https://github.com/Pezmc/BibLatex-Check/compare/2db50bf94d1480f37edf1b3619e73baf4ef85938...v1.0.1

~While it works as-is on provided test file `input.bib`, also apply a fix
for python3 that is needed to run on various bib files I have around.
(PR submitted)~

EDIT: included in 1.0.1 :tada:

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
Hmm 1.0.0 might not be a proper release, shelving for now.

**Comment by dtzWill** [comment]
Asked upstream, they cut 1.0.1, so update to that and should be good to go! :smile:

**Comment by dtzWill** [comment]
:eyes: :confused:

"added the ofborg-internal-error label"
( https://github.com/NixOS/nixpkgs/pull/157597#event-6284839260 )

...

Now it says I cannot comment at this time? o_O

status.github.com says having issues, okay.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Pull request merged**
