### PR TITLE
tutanota-desktop: init at 3.88.4

### PR DESCRIPTION
**Pull request by WolfangAukang**
###### Motivation for this change

Adding Tutanota official desktop client. Using AppImage for now as I wasn't able to build it through source yet.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtrees** [comment]
I haven't tested this but it looks good! Thank you.

Did you try building it from source btw?

**Comment by WolfangAukang** [comment]
@jtrees FYI, if you get to try it, you might find a warning regarding secret storage. This is intended if you don't have a keychain installed :).

Regarding building from source, I tried, but the main issue I got into is that as this is a JavaScript project, I generally use `node2nix` to build it. One of the problems is that the package lock file has an empty key which makes it unrecognizable. So, if I try to run with only the `package.json`, besides adapting one of the dependencies URLs (the `opsec` library), there is a dependency out of the project reach that fails.

The other option would be getting the `tar` file from the releases section at their repo, but I honestly couldn't execute the binary through NixOS. That's why I went with the AppImage, just to have something done, but in case someone can build it or set up the tar successfully, then it's just a matter of adapting it.

**Comment by jtrees** [comment]
> @jtrees FYI, if you get to try it, you might find a warning regarding secret storage. This is intended if you don't have a keychain installed :).
> 
> Regarding building from source, I tried, but the main issue I got into is that as this is a JavaScript project, I generally use `node2nix` to build it. One of the problems is that the package lock file has an empty key which makes it unrecognizable. So, if I try to run with only the `package.json`, besides adapting one of the dependencies URLs (the `opsec` library), there is a dependency out of the project reach that fails.
> 
> The other option would be getting the `tar` file from the releases section at their repo, but I honestly couldn't execute the binary through NixOS. That's why I went with the AppImage, just to have something done, but in case someone can build it or set up the tar successfully, then it's just a matter of adapting it.

I see. Yes, it's good to have the AppImage as a stop-gap solution. Thanks again.

It is it a bit troubling that such a security-sensitive application cannot be built properly from source though. Did you report the issue upstream?

**Comment by WolfangAukang** [comment]
> It is it a bit troubling that such a security-sensitive application cannot be built properly from source though. Did you report the issue upstream?

Honestly I haven't had the time to do a thorough analysis of the issue. When I tried to use `node2nix`, the only thing I did was comparing the error and seeing the `package.json` of the project, to see if it was something I could fix, but the library having the issue was not listed there. I'd rather pinpoint to the exact issue to avoid getting an immediate closed issue there.

Also, as I'm also trying to port other JS based projects to NixOS, someone provided other options to try building besides `node2nix`. I hope I can get it done this weekend.

**Comment by jtrees** [comment]
Doing a `nox-review pr 139454` gives me a mismatched checksum:

```
hash mismatch in fixed-output derivation '/nix/store/d8nfs5d3cc7fcpzvlagwybxs3m528bzx-tutanota-desktop-3.88.3.AppImage':
  wanted: sha256:1fdszc4rxv0ywmbn3r2l0vzf9dh79sv9a35w2wbhkq78k0khwkih
  got:    sha256:0iv6xvfw0rhamdwy3wvgdakpcc99d94rcs5y0bqwphcr47lwf2rk
```

**Comment by WolfangAukang** [comment]
> Doing a `nox-review pr 139454` gives me a mismatched checksum:

They updated the version (now it is 3.88.4). The main issue is that their AppImage download link goes directly to the release version (no version is specified on the URL), which makes it troublesome if there is an update.

**Pull request merged**
