### PR TITLE
yosys: 0.18 -> 0.19

### PR DESCRIPTION
**Pull request by Luflosi**
###### Description of changes
https://github.com/YosysHQ/yosys/releases/tag/yosys-0.19
Also update abc-verifier to match the version expected by yosys.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
abc-verifier looks like it's failing on aarch64-linux.

**Comment by risicle** [comment]
I'm having getting glasgow's tests to pass on macos 10.15 where they did before:

```
======================================================================
ERROR: test_build (glasgow.applet.interface.analyzer.AnalyzerAppletTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.10-glasgow-unstable-2021-12-12.drv-0/source/software/glasgow/applet/interface/analyzer/__init__.py", line 133, in test_build
    self.assertBuilds()
  File "/private/tmp/nix-build-python3.10-glasgow-unstable-2021-12-12.drv-0/source/software/glasgow/applet/__init__.py", line 232, in assertBuilds
    target.build_plan().execute()
  File "/private/tmp/nix-build-python3.10-glasgow-unstable-2021-12-12.drv-0/source/software/glasgow/target/hardware.py", line 118, in execute
    products  = self.lower.execute_local(build_dir)
  File "/nix/store/5yvg7j5yz0r6yap9p6jd6bv9lp5k3yh6-python3.10-amaranth-0.3/lib/python3.10/site-packages/amaranth/build/run.py", line 98, in execute_local
    subprocess.check_call(["sh", "{}.sh".format(self.script)])
  File "/nix/store/aqz4sk2zbi9gfcqgkmhyv5p258mkzvng-python3-3.10.5/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', 'build_top.sh']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 244 tests in 273.111s

FAILED (errors=1, skipped=7)

```

**Comment by risicle** [comment]
@ofborg build glasgow

**Comment by Luflosi** [comment]
I don't know how to fix these failures. I'll leave this PR as WIP.

**Comment by Luflosi** [comment]
Closing, since #186295 was merged.

**Pull request closed without merging**
