### PR TITLE
WIP: initial packages for LXQt 0.9.0, a light-weight desktop

### PR DESCRIPTION
**Pull request by ellis**

### CODE REVIEW

**Comment by lethalman** [comment]
Very well done thanks. Can you add a nixos test similar to gnome or kde so that I can build the test and see the resulting screenshot? :)

**Comment by ellis** [comment]
@lethalman Sounds like a good thing to do -- I'll look into it over the weekend.

**Comment by bjornfor** [comment]
@ellis: On nix-dev mailing list you mentioned a few know issues, can you list them here?

**Comment by ellis** [comment]
LXQt is a lightweight desktop (http://lxqt.org/).
There are a couple issues with these packages which I haven't solved yet.  In particular:

1. one of the items in the panel menu isn't display, although it's clickable
2. the audio volume applet displays the wrong icon
3. when using xmonad, the panel's program list is empty
4. when using openbox, pressing Alt+Tab often leaves the list of programs open until I press another key (but this might be specific to my system, because I've remapped the Alt key with xmodmap)

**Comment by iyzsong** [comment]
Why not use [release tarballs](http://downloads.lxqt.org/lxqt/0.9.1/) instead of ``fetchgit``?

**Comment by ellis** [comment]
@iyzsong Since you're asking, I guess you're saying that release tarballs are usually better?  Why's that?
I used the git repositories for the following reasons (most important to least):

1. The lxqt developers have a "meta" repository that shows how to build all the projects; so it's easiest to use that as an up-to-date reference.
2. Not all of the packages they recommend are in the release directory anyway.
3. Release tarballs are more likely to disappear.

**Comment by iyzsong** [comment]
I think:
-  Releases should be more stable (for end users) than git repositories, and
   they won't disappear easily, at least ArchLinux use them. :-)
-  Tarballs requires less download time (compare with `git clone').
And we use names like ``foo-git-2015-05-10`` for git packages (see #6539).

**Comment by jagajaga** [comment]
@ellis if release version is not too old, we prefer them. So, please, use them.

**Comment by codyopel** [comment]
You can easily use the tarballs provided by github releases e.g.
`https://github.com/lxde/liblxqt/archive/0.9.0.tar.gz`
On the releases tab of each repo

**Comment by edwtjo** [comment]
Also, use `fetchFromGitHub` if you're changing from `fetchgit` to archives. Release src tarballs never disappear if the rev/tag is still there.

**Comment by ellis** [comment]
Ok, thanks for the information, everyone.  I'll modify the expressions to download release tarballs, and use fetchFromGitHub to get them.

**Comment by domenkozar** [comment]
What's the status of this?

**Comment by ellis** [comment]
@domenkozar Hmm, I was waiting for a stable release of NixOS to come out, because at some point the 'master' branch broke some critical apps (aqbanking for banking and hledger for accounting) for a long time, so I reverted back to 14.12 in June, and I couldn't really work on patches to master anymore.  I see that 15.09 came out yesterday, though -- will give it a try soon!

**Comment by domenkozar** [comment]
Check on status again :)

**Comment by bjornfor** [comment]
LXQt 0.10 is released :-)

**Comment by ellis** [comment]
Yeah, I finally got nixos updated on my system, and started working on LXQt 0.10 this weekend already.

**Comment by ellis** [comment]
As an update: a couple vital features aren't working for me in nixos that used to work in 14.10 (aqbanking with Volksbank and some Qt development libraries), so I find that I'm not using my nixos machine much currently and there's therefore not much opportunity to work on lxqt...  Will look into it again when I have some extra free time or when I can start using nixos full-time again.

**Comment by globin** [comment]
I just tried building acbanking and could not identify any problems:
```
-> % ./result/bin/aqbanking-cli versions                                             ~/dev/nixpkgs
Versions:
 AqBanking-CLI: 5.5.1
 Gwenhywfar   : 4.13.1.0
 AqBanking    : 5.5.1.0
```
Could you open an issue for this with more information and also give more detail on other failures or bugs in order to help fix them.

**Comment by ellis** [comment]
Ok, I'll try to find the time soon.  I already spent quite a few hours trying to troubleshoot it, but didn't make much progress -- seemed related to SSL certificates.

**Comment by ellis** [comment]
Unfortunately, I had to install another distro over nixos, because I urgently required functionality (USB in qemu) that somehow broke after upgrading from 14.10, and I'm currently too pressed for time to troubleshoot my system.  I hope to get back to it eventually, because I loved nixos while I had it running and could get the same system replicated among all my devices.  But for now, I'll close this ticket...

**Pull request closed without merging**
