### PR TITLE
py_slvs: init at 1.0.6

### PR DESCRIPTION
**Pull request by waynevanson**
## Description of changes

A python package that is linked to a fork of solvespace, which implements CAD functionality.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by waynevanson** [comment]
What command should I run build? I've read the contribution.md but couldn't see what I think I'm looking for.

**Comment by waynevanson** [comment]
Looks like the build script needs to be customized, will figure out how to do this eventually.

#303594

**Comment by traverseda** [comment]
```nix
{ lib, blender, python3Packages, pkgs, fetchurl }:

let
  py-slvs = python3Packages.buildPythonPackage rec {
    pname = "py-slvs";
    version = "1.0.6";

    src = python3Packages.fetchPypi {
      pname = "py_slvs";
      version = "1.0.6";
      sha256 = "sha256-U6T/aXy0JTC1ptL5oBmch0ytSPmIkRA8XOi31NpArnI=";
    };

    pyproject = true;

    nativeBuildInputs = with pkgs; [
      swig
    ];

    propagatedBuildInputs = with python3Packages; [
      cmake
      ninja
      setuptools
      scikit-build
    ];

    dontUseCmakeConfigure = true;

    meta = with pkgs.lib; {
      description = "Python binding of SOLVESPACE geometry constraint solver";
      homepage = "https://github.com/realthunder/slvs_py";
      license = licenses.gpl3;
    };
  };

  blenderWithPySlvs = blender.withPackages (p: [py-slvs]);

in
  blenderWithPySlvs
```

Is working for me

**Comment by waynevanson** [comment]
Please use @traverseda PR.

**Pull request closed without merging**
