### PR TITLE
erlang-ls: 0.16.0 -> 0.17.0

### PR DESCRIPTION
**Pull request by dlesl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Thank you for the contribution!
the ci passes, I'm waiting for the build to finish on my machine before merging.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 126911` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>erlang-ls</li>
  </ul>
</details>

**Comment by happysalada** [comment]
[log.gz](https://github.com/NixOS/nixpkgs/files/6653169/log.gz)

**Comment by happysalada** [comment]
I'm having some tests failing on my machine.
Let me know if you want me to have a look or test.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126911` at 020af1c6 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>erlang-ls</li>
  </ul>
</details>
<details>
  <summary>5 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`checkPhase` should probably contain `runHook preCheck` and `runHook postCheck`.

Near pkgs/development/beam-modules/erlang-ls/default.nix:29:3:
```
   |
29 |   checkPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near lib/attrsets.nix:212:41:
```
    |
212 |   nameValuePair = name: value: { inherit name value; };
    |                                         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near lib/attrsets.nix:212:41:
```
    |
212 |   nameValuePair = name: value: { inherit name value; };
    |                                         ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/beam-modules/rebar3-release.nix:92:5:
```
   |
92 |     meta = {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/beam-modules/rebar3-release.nix:44:5:
```
   |
44 |     name = "${name}-${version}";
   |     ^
```

Near pkgs/development/beam-modules/rebar3-release.nix:45:12:
```
   |
45 |     inherit version;
   |            ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> I'm having some tests failing on my machine.
> Let me know if you want me to have a look or test.

Can't reproduce them.

**Comment by Ma27** [comment]
Same here, looks ok to me :)

**Comment by dlesl** [comment]
@happysalada The tests also passed for me on darwin. I'm wondering whether it might be something to do with `epmd`, maybe you had another erlang system with distribution enabled running on your machine?

**Comment by happysalada** [comment]
Yes maybe you're right. We'll know soon enough if there really was a problem.
Thank you for the PR!

**Pull request merged**
