### PR TITLE
vimPlugins: added Rename

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

Add Rename plugin.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jagajaga** [comment]
Please add files here: https://github.com/asymmetric/nixpkgs/blob/c796aad067c1ec47404f4b290c8f86ec514a345f/pkgs/misc/vim-plugins/vim-plugin-names

**Comment by garbas** [comment]
@asymmetric you need to also add file to ``vim-plugin-names`` so that next time somebody tries to update all of the plugins it also updates ``Rename``

**Comment by groxxda** [comment]
I don't really understand the "motivation for this change" 
> The vim plugins were pretty old.

especially since you are adding a pretty old plugin :laughing: 
But the version of this plugin should probably be 2011-08-23:
> Latest commit b240f28  on Aug 23, 2011

**Comment by asymmetric** [comment]
@groxxda motivation changed. I haven't set that date manually - should I change it?

**Comment by groxxda** [comment]
@asymmetric if its generated, leave it as is.

**Pull request merged**
