### PR TITLE
headscale: 0.16.4 -> 0.17.0

### LINKED ISSUE #203446: headscale: 0.16.4 -> 0.17.0
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `headscale`

current version: v0.16.4
desired version: v0.17.0

Link to the new version: https://github.com/juanfont/headscale/releases/tag/v0.17.0

This version upgrade also most likely requires a change to the `headscale` module, as the `log_level` option has been moved.

I am happy to create a PR for this, if desired

###### Notify maintainers

maintainers: @kradalby @06kellyjac @NKJe

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by Misterio77**
###### Description of changes

This PR updates the headscale package to 0.17.0.
It also updates the corresponding module:
- deprecate `logLevel` option (instructing the user to use `settings.log.level` instead), as it has been renamed by upstream (https://github.com/juanfont/headscale/pull/768).
- add a `noisePrivateKey` option as it is now a required setting for
  headscale to run. The legacy `privateKey` should be deprecated in the
  future. (https://github.com/juanfont/headscale/pull/738)

I've also added a NixOS test for the module.

Fixes https://github.com/NixOS/nixpkgs/issues/203446

~Note: There's a few integration tests that are now failing, can we somehow make them work or disable them selectively? For now, I've set `doCheck` to false.~ Fixed!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
https://github.com/juanfont/headscale/blob/eb072a1a74f0bb605d23c31fbe6f26acab99bd3d/integration_cli_test.go#LL32C3-L32C57

Adding `checkFlags = [ "-short" ];` works fine

if you could put it under `ldflags` or `nativeBuildInputs` that'd be good

**Comment by Misterio77** [comment]
> Adding `checkFlags = [ "-short" ];` works fine
> 
> if you could put it under `ldflags` or `nativeBuildInputs` that'd be good

Thank you!

**Comment by Misterio77** [comment]
It seems the `noise.private_key_path` is required (instead of `private_key_path`) now and not set by default.

So I've added an option that defaults to `${dataDir}/noise_private.key` (the option can't be reused as they're not supposed to be the same file https://github.com/juanfont/headscale/issues/526#issuecomment-1079795935).

We can deprecate the legacy one in the future, I think?

**Comment by Frostman** [comment]
Result of `nixpkgs-review pr 203694` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>headscale</li>
  </ul>
</details>

**Comment by kradalby** [comment]
Apologies for the delay, 

The noise path missing from breaking changes, and `-short` flag was a mishap and I have created a PR to get the noise into the changelog. 

As for the module mentioned in #203446, it might be sensible to port the module over to the [RFC0042 Config Options](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md), which is somewhat done through the `services.headscale.settings` option.

I think the way forward would be to deprecate/removed the old options and then merge the new version? As far as I can see, the old module, and 0.16.4 is in 22.11 release which then will stay compatible?

I will try to take a stab at that today, and ask for feedback.

**Comment by Misterio77** [comment]
> I have created a PR to get the noise into the changelog.

Thanks!

> it might be sensible to port the module over to the [RFC0042 Config Options](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md)

Agreed! I was actually thinking about that, but thought it might be better suited for a follow-up PR. 

> As far as I can see, the old module, and 0.16.4 is in 22.11 release which then will stay compatible?

Think so. If we  don't backport it, 22.11 should keep the 0.16.4 and the corresponding older module.

**Comment by kradalby** [comment]
I will start on a separate PR for the module change, I do not know how the backport process works, but when we have both of those parts polished, we can tackle that as a separate problem.

**Comment by kradalby** [comment]
@Misterio77 @06kellyjac 
I have created https://github.com/NixOS/nixpkgs/pull/203938 as draft, I will update the changelog etc now, but would appreciate someone reading and checking if I have made sensible changes.

**Comment by Misterio77** [comment]
Looks great!
Would you prefer we merge this one or yours first?

**Comment by Misterio77** [comment]
CI failure seems unrelated

**Comment by 06kellyjac** [comment]
merging it all into 1 PR feels most sensible to me but whatever works

**Comment by kradalby** [comment]
I'm closing this in favour of #203938, which now contains the important changes from this PR.

**Pull request closed without merging**
