### PR TITLE
abootimg: init at 0.6

### PR DESCRIPTION
**Pull request by flokli**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
right, `blkid.h` might not be available for darwin.

**Comment by xeji** [comment]
Upstream looks  dead, code hasn't been updated since 2011. Are there no actively maintained alternatives?

**Comment by flokli** [comment]
For (re-)assembling images, `mkbootimg` from the Android project can be used, but I'm not aware of something "official" for extraction.
There's [imgtool](http://newandroidbook.com/tools/imgtool.html), but that's just a tarfile linked from its website.

**Comment by xeji** [comment]
Fine, if  `abootimg` still works - the boot image format seems to be very stable :smile:

**Pull request merged**
