### PR TITLE
nixos/pantheon: enable lightdm gtk greeter

### PR DESCRIPTION
**Pull request by worldofpeace**
Pantheon's greeter has numerous issues that cannot be
fixed in a timely manner, and users are better off if they just
didn't use it by default.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
@GrahamcOfBorg test lightdm

**Comment by worldofpeace** [comment]
Looks like the test succeeds here. Locally things still function properly.

So I think I just need feedback on the `warnings` and perhaps the release note itself.

**Comment by lheckemann** [comment]
I've taken the liberty of adding a commit rephrasing the release notes a little, are these changes fine with you?

**Comment by worldofpeace** [comment]
> I've taken the liberty of adding a commit rephrasing the release notes a little, are these changes fine with you?

I appreciated it :+1:

Fixup commit was just the auto-format and not repeating lightdm too much.

##### Screenshot of rendered note
Screenshot from 2019-04-08 16 10 37

**Comment by lheckemann** [comment]
Backported: 9fa96de6099 c7de6984f5c 9db4cedcbf2 55f4df0b3a3

**Comment by worldofpeace** [comment]
Thanks @lheckemann :sparkles:

**Comment by DAC324** [comment]
Hello all,

there is just one weird thing about Pantheon here:

I am using LightDM with lightdm-gtk-greeter. (see https://bbs.archlinux.org/viewtopic.php … 4#p1928724 )

When I log out of the current session, I expect that I get back to the login screen (greeter) asking me to choose my DE and to log in again.

Instead, when using Pantheon, the screen blanks and afterwards, the Pantheon wallpaper reappears but without WingPanel and/or Plank. There is also no right-click menu anymore when clicking on the desktop.

All I can do in this situation is switching to a text console and either kill X or reboot.

As this does not happen with xfce, I assume that there is some Pantheon setting that needs to be corrected.

Thank you very much for any hint in advance and kind regards,
DAC324

**Comment by worldofpeace** [comment]
> Hello all,
> 
> there is just one weird thing about Pantheon here:
> 
> I am using LightDM with lightdm-gtk-greeter. (see https://bbs.archlinux.org/viewtopic.php … 4#p1928724 )
> 
> When I log out of the current session, I expect that I get back to the login screen (greeter) asking me to choose my DE and to log in again.
> 
> Instead, when using Pantheon, the screen blanks and afterwards, the Pantheon wallpaper reappears but without WingPanel and/or Plank. There is also no right-click menu anymore when clicking on the desktop.
> 
> All I can do in this situation is switching to a text console and either kill X or reboot.
> 
> As this does not happen with xfce, I assume that there is some Pantheon setting that needs to be corrected.
> 
> Thank you very much for any hint in advance and kind regards,
> DAC324

Hi, I would recommend that you use pantheon's lightdm greeter as it is tested to work with pantheon and will integrate with the desktop properly. Could you open a new issue with these details? I'm also wondering which release you're on, this PR is for an EOL one which I can't provide support for. This issue does at least ring a bell for me with 20.09 and unstable

**Pull request merged**
