### PR TITLE
nixos/dhcpd: switch to DynamicUser

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change

Primarily, [#55370](https://github.com/NixOS/nixpkgs/issues/55370)

The service can run unprivileged -- by using capabilities -- and the uid/gid can be dynamically allocated since there are only a handful of state files.

This change improves the overall security of the service by leveraging systemd's hardening and getting rids of `nogroup` and the initial root permissions (before the daemon drop privileges).

###### Things done

- [x] Tested via (nixosTests.networking)
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Cool! Since this software is a bit older I'll ask... is there any hard coded checks to ensure the software is run as `root` at all? And everything seems smooth while running this?

**Comment by rnhmjoj** [comment]
I run all the networking tests: most, if not all, involve running dhpcd and they passed. So it seems to be working normally.

**Review by aanderse — APPROVED** [review]
Awesome! :rocket:

**Comment by rnhmjoj** [comment]
The only difference I noticed between running as root and unprivilged is that the daemon expects the `dhpd.leases` file to exists: it doesn't create it. My theory is that the running dhpd process thinks to be the unprivilged child of the initial dhpd process running as root (which in this case doesn't exist) and is probably responsible for some sort of initial setup.
So, before merging I should check this more carefully: it's possible more tasks needs to be performed in the preStart script.

**Comment by rnhmjoj** [comment]
I looked at the source code of dhcpd: there is a check for root only when trying to do a setui/setgid, which is not the case here. Also `dhcp.leases` and the pid file seem to be the only files needed by the daemon.

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test networking

**Comment by rnhmjoj** [comment]
Since 21.11 has passed and we're pretty far from the next release, I'd say this is the best time to try merging this PR.

**Comment by vcunat** [comment]
This commit broke a test and it's now blocking the `nixos-unstable` channel.
https://hydra.nixos.org/build/162575182

**Comment by vcunat** [comment]
This would seem hard for me to debug.  @rnhmjoj: can you (or anyone) have a look at this today, or should I revert it for now?

**Comment by rnhmjoj** [comment]
> should I revert it for now?

Yes, go ahead. I'll look into it.

**Pull request merged**
