### PR TITLE
Kernels 2021-09-03

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Updates

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Diff LGTM, building 5.14.1

**Review by fabianhjr — APPROVED** [review]
Built and running 5.14.1

```
Linux version 5.14.1 (nixbld@localhost) (gcc (GCC) 10.3.0, GNU ld (GNU Binutils) 2.35.1) #1-NixOS SMP Fri Sep 3 08:24:03 UTC 2021
```

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/136235

**Comment by jonringer** [comment]
this seems to have broken the hardened kernels:

```
$ git bisect run nix-build -A linuxPackages_hardened.kernel
error: 1 dependencies of derivation '/nix/store/3lpsg75rilxw9kv2yk4pdmjamppw5bgd-linux-5.10.62.drv' failed to build
f57a2e0bed20c180aca22dae884c3965d70cb13f is the first bad commit
commit f57a2e0bed20c180aca22dae884c3965d70cb13f
Author: Tim Steinbach <tim@nequissimus.com>
Date:   Fri Sep 3 06:53:20 2021 -0400

    linux: 5.10.61 -> 5.10.62

 pkgs/os-specific/linux/kernel/linux-5.10.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
...
```

source of failure:
```
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
```

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/134692#issuecomment-901364516

**Pull request merged**
