### PR TITLE
librewolf: move out of firefox directory

### PR DESCRIPTION
**Pull request by squalus**
This is a proposal for moving Librewolf out of the Firefox directory while still sharing the Firefox build expressions between the two packages. See #160520

- make the firefox common.nix available from the top level as `buildMozillaMach`
- use new `buildMozillaMach` function in librewolf expressions
- minor changes to update script

This doesn't cause any rebuilds.

cc @mweinelt

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Can you import `common` like thunderbird is doing it instead of reworking top-level?

https://github.com/NixOS/nixpkgs/blob/ed32ed96331c213ebc2a0c579008f96efc89dcc9/pkgs/applications/networking/mailreaders/thunderbird/packages.nix#L3-L8

**Comment by squalus** [comment]
> Can you import `common` like thunderbird is doing it instead of reworking top-level?

Yes, I can do that.

I started out doing that but there was some code duplication. In particular, there would have to be an identical top-level newScope call in both places. So I wanted a way to reuse the scope, since I couldn't think of a reason they would be different.

**Comment by mweinelt** [comment]
Okay, I don't have a strong opinion really. Maybe wait for @lovesegfault's opinion.

**Comment by squalus** [comment]
> Okay, I don't have a strong opinion really. Maybe wait for @lovesegfault's opinion.

I'm happy to do it either way. One argument for your proposal is that, maybe Librewolf will fall behind and require a different version of rustc or whatever else goes into the scope. It would be easier to handle this case. And we might want to optimize for this, since we don't want to delay Firefox updates if Librewolf lags.

If we do it with the rework, perhaps Thunderbird should also use the `buildFirefox` function.

**Comment by mweinelt** [comment]
Well, I agree that something like `buildMach` (for mozillas mach build system) would be more meaningful that import common.nix.

**Comment by vcunat** [comment]
`buildWeirdAnimal`

**Comment by squalus** [comment]
> As for `rustc` etc. I expect they're mainly about the `version` attribute passed to `common.nix`. We already maintain some variants because of ESR (and thunderbird also follows ESR schedule). But I'm only guessing what librewolf does here.

This is a good point. `common.nix` already supports an ESR release which is almost certainly older than Librewolf. So far I've seen Librewolf lag by a matter of days, not weeks or months.

**Comment by squalus** [comment]
Rebased and changed the function to `buildMozillaMach`

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
Thank you.

**Pull request merged**
