### PR TITLE
nixos/grafana: Update and add config options

### PR DESCRIPTION
**Pull request by Garmelon**
###### Description of changes

I went through all categories that were already present in the grafana module and added most options from the official docs at https://grafana.com/docs/grafana/v9.5/setup-grafana/configure-grafana/. I also modified the descriptions of some existing options to match the official docs more closely.

I'm not sure if the options whose default value is an empty string (according to https://github.com/grafana/grafana/blob/cb7e18938b8eb6860a64b91aaba13a7eb31bc95b/conf/defaults.ini) should have a default value of `null` instead.

I'm also not sure how to best add an option like `grafana.extraSettings` (which type to use? Do I just `//` it onto the settings module?) or if there shouldn't be one for some reason.

It would be nice if this could be backported to 23.05 stable as I'd like to use some of these options on my server's grafana instance. I'm currently running these changes on my server on 23.05 and haven't noticed any issues (yet :P).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Massive and much needed changes!

**Comment by Garmelon** [comment]
Could this be backported automatically to 23.05 or should I open another PR for that?

**Comment by drupol** [comment]
Job done.

**Comment by timothyklim** [comment]
After this commit my grafana installation with pkgs.mysql80 now cannot start with error:
```
logger=migrator t=2023-06-20T06:05:52.767841772Z level=error msg="alert migration failure: could not get migration log" error="failed to check table existence: Error 1193: Unknown system variable 'tx_isolation'"
```

**Comment by drupol** [comment]
@Garmelon do you mind having a look at this ?

**Comment by Garmelon** [comment]
This appears to be because I set some options to `null` instead of the empty string, which the `.ini` format converts to `option=null` instead of `option=`. I expected the `.ini` format to convert nulls to empty strings for some reason.

This applies to the `isolation_level` option, causing grafana to try to [set it via `tx_isolation`](https://github.com/grafana/grafana/blob/2e350d13bb3cb68057584e30db480f8c837c2433/pkg/services/sqlstore/sqlstore.go#L301) (not `transaction_isolation`, which newer mysql versions understand, [this appears to be fixed on the main branch though](https://github.com/grafana/grafana/blob/d529636bc3dd9c1a091abe6af7aa59cf68de440c/pkg/services/sqlstore/sqlstore.go#L434-L435)). Because of this, the phrase `null` doesn't even appear in the error message.

One possible fix would be to include the empty string in the `type.enum`s. Another would be to somehow replace the `null`s with empty strings right before passing the config into the ini format, though I'm not sure how to do that.

**Comment by Garmelon** [comment]
Yes, that looks useful. I'll try it later today. I could probably change one or two options to lists instead of strings as well (still allowing raw strings in the option though, so should be backwards compatible).

**Pull request merged**
