### PR TITLE
Updating documentation about adding new Vim plugins

### PR DESCRIPTION
**Pull request by malob**
###### Motivation for this change
Documentation about adding Vim plugins to nixpkgs was out of date and scant on details.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
This information is accurate from my own experiences with how vim-plugins are structured.

Thanks for doing this! :)

**Review by teto — APPROVED** [review]

**Comment by malob** [comment]
Anything I can do the to help move this along?

**Comment by jonringer** [comment]
Not sure who to CC, I would find who has commit access and is interested in vim plugins by looking at some of the commits, then ping them. With the volume of PRs, many fall through the cracks :(

**Comment by 7c6f434c** [comment]
Not that I care about Vim plugins…

**Pull request merged**
