### PR TITLE
.github/CODEOWNERS: remove non-committer users/teams

### PR DESCRIPTION
**Pull request by zowoq**
these didn't work anyway and now github warns if they don't have commit access

https://github.com/NixOS/nixpkgs/blob/b71ebb32cedef576181e519380f42d1e2fc5d312/.github/CODEOWNERS

codeowners

### CODE REVIEW

**Comment by teto** [comment]
can't we instead setup the teams so that they have write access ? gnome team implies triage for now for instance.

**Comment by zowoq** [comment]
> can't we instead setup the teams so that they have write access ?

Not with the way we currently use teams as they have members who don't already have write access.

**Comment by teto** [comment]
it's sad that we can use only teams with write access (it is normal according to docs https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

Have you looked for any github ticket to allow teams with RO access  ? 
Maybe we could create a team with write access instead ? like gnome-RW

**Comment by zowoq** [comment]
> Have you looked for any github ticket to allow teams with RO access ?

No.

> Maybe we could create a team with write access instead ? like gnome-RW

Out of scope of this PR, creating new teams (and new types of teams) can be discussed elsewhere.

**Comment by zowoq** [comment]
Now we have another team with commit access definitely seems simpler to just limit this file to users/teams with commit access so we can benefit from the github warnings and avoid any confusion.

**Comment by SuperSandro2000** [comment]
What do you think about pinging the teams so that they know they need to fix this?

**Comment by zowoq** [comment]
> What do you think about pinging the teams so that they know they need to fix this?

There isn't anything to be fixed here, this is basically just cleaning up dead code. The members of the gnome, php and podman teams that that have commit access are already listed here alongside the team. The darwin team has ~45 people, mostly non-committers. I think asking people to add themselves as new darwin codeowners is out of scope for this PR.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
