### PR TITLE
dprint: enable doCheck with some skips

### PR DESCRIPTION
**Pull request by kachick**
Initial discussion: https://github.com/NixOS/nixpkgs/pull/128784#discussion_r663317910

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kachick** [comment]
https://github.com/NixOS/nixpkgs/actions/runs/12202942991/job/34044818593?pr=362498

Looks like other PRs have same errors, treewide CI trouble?

```
building '/nix/store/sdrvzjsnzr200ygf93y9wffjrnxk438r-attrpaths-superset.json.drv'...
error:
       … from call site
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix:183:10:
          182|       [ "pkgsMusl" "stdenv" ]
          183|     ] ++ justAttrNames [] filtered;
             |          ^
          184|

       … while calling 'justAttrNames'
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix:124:25:
          123|   #
          124|   justAttrNames = path: value:
             |                         ^
          125|     let

       … while evaluating a branch condition
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix:155:9:
          154|       result =
          155|         if tried.success
             |         ^
          156|         then tried.value

       … while calling the 'tryEval' builtin
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix:152:15:
          151|       seq = builtins.deepSeq attempt attempt;
          152|       tried = builtins.tryEval seq;
             |               ^
          153|

       … while calling the 'deepSeq' builtin
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix:151:13:
          150|
          151|       seq = builtins.deepSeq attempt attempt;
             |             ^
          152|       tried = builtins.tryEval seq;

       … while calling the 'foldl'' builtin
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix:142:14:
          141|         else if (value.__attrsFailEvaluation or false) then []
          142|         else lib.pipe value [
         6064|   gcc12Stdenv = overrideCC gccStdenv buildPackages.gcc12;
         6065|   gcc13Stdenv = overrideCC gccStdenv buildPackages.gcc13;
             |   ^
         6066|   gcc14Stdenv = overrideCC gccStdenv buildPackages.gcc14;

       … from call site
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/all-packages.nix:6065:17:
         6064|   gcc12Stdenv = overrideCC gccStdenv buildPackages.gcc12;
         6065|   gcc13Stdenv = overrideCC gccStdenv buildPackages.gcc13;
             |                 ^
         6066|   gcc14Stdenv = overrideCC gccStdenv buildPackages.gcc14;

       … while calling 'overrideCC'
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/stdenv/adapters.nix:35:24:
           34|   # Override the compiler in stdenv for specific packages.
           35|   overrideCC = stdenv: cc: stdenv.override {
             |                        ^
           36|     allowedRequisites = null;

       … while evaluating a branch condition
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/all-packages.nix:6051:5:
         6050|   gccStdenv =
         6051|     if stdenv.cc.isGNU
             |     ^
         6052|     then stdenv

       … while evaluating the attribute 'cc.isGNU'
         at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/stdenv/generic/default.nix:168:15:
          [167](https://github.com/NixOS/nixpkgs/actions/runs/12202942991/job/34044818593?pr=362498#step:5:168)|
          [168](https://github.com/NixOS/nixpkgs/actions/runs/12202942991/job/34044818593?pr=362498#step:5:169)|       inherit cc hasCC;
             |               ^
          [169](https://github.com/NixOS/nixpkgs/actions/runs/12202942991/job/34044818593?pr=362498#step:5:170)|

       error: infinite recursion encountered
       at /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/all-packages.nix:6051:8:
         6050|   gccStdenv =
         6051|     if stdenv.cc.isGNU
             |        ^
         6052|     then stdenv
Command exited with non-zero status 1
        Command being timed: "nix-instantiate --eval --strict --json --show-trace /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix -A paths -I /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source --option restrict-eval true --option allow-import-from-derivation false --arg enableWarnings false"
        User time (seconds): 12.96
        System time (seconds): 1.42
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:14.46
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 4952240
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: [183](https://github.com/NixOS/nixpkgs/actions/runs/12202942991/job/34044818593?pr=362498#step:5:184)484
        Voluntary context switches: 130
        Involuntary context switches: 72
        Swaps: 0
        File system inputs: 0
        File system outputs: 336
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
error: builder for '/nix/store/sdrvzjsnzr200ygf93y9wffjrnxk438r-attrpaths-superset.json.drv' failed with exit code 1;
       last 25 log lines:
       >          6052|     then stdenv
       > Command exited with non-zero status 1
       >         Command being timed: "nix-instantiate --eval --strict --json --show-trace /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source/pkgs/top-level/release-attrpaths-superset.nix -A paths -I /nix/store/8hsambh0xsjzlpmys60fm8lp6irvyi3h-source --option restrict-eval true --option allow-import-from-derivation false --arg enableWarnings false"
       >  User time (seconds): 12.96
       >     System time (seconds): 1.42
       >    Percent of CPU this job got: 99%
       >       Elapsed (wall clock) time (h:mm:ss or m:ss): 0:14.46
       >   Average shared text size (kbytes): 0
       >   Average unshared data size (kbytes): 0
       >         Average stack size (kbytes): 0
       >         Average total size (kbytes): 0
       >         Maximum resident set size (kbytes): 4[952](https://github.com/NixOS/nixpkgs/actions/runs/12202942991/job/34044818593?pr=362498#step:5:953)240
       >    Average resident set size (kbytes): 0
       >  Major (requiring I/O) page faults: 0
       >   Minor (reclaiming a frame) page faults: 183484
       >         Voluntary context switches: 130
       >        Involuntary context switches: 72
       >       Swaps: 0
       >       File system inputs: 0
       >  File system outputs: 336
       >       Socket messages sent: 0
       >        Socket messages received: 0
       >    Signals delivered: 0
       >   Page size (bytes): 4096
       >        Exit status: 1
       For full logs, run 'nix log /nix/store/sdrvzjsnzr200ygf93y9wffjrnxk438r-attrpaths-superset.json.drv'.
Error: Process completed with exit code 1.
```

**Comment by kachick** [comment]
https://github.com/NixOS/nixpkgs/pull/349316#issuecomment-2523739949 => https://github.com/NixOS/nixpkgs/pull/362496 ?

**Comment by kachick** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362498`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dprint</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dprint</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dprint</li>
  </ul>
</details>

**Review by phanirithvij — APPROVED** [review]
commit needs to be `dprint: add kachick as maintainer`, otherwise LGTM tested locally

**Comment by kachick** [comment]
>commit needs to be 

```console
> git log --oneline --perl-regexp --grep='^[[:alnum:]]+\b\S+: add \S+ as (a )?maintainer\b' | head -10000 | grep -P '(my)?self' | wc -l
83
```

Agreed 😂

**Comment by kachick** [comment]
>commit needs to be

```console
git log --oneline --perl-regexp --grep='^\S+: add \S+ as (a )?maintainer\b' | head -1000 | ruby -e 'p STDIN.map{ |line| /\b(my)?self\b/.match?(line) }.tally'
{false=>858, true=>142}
```

Agreed!

**Review by Aleksanaa — APPROVED** [review]

**Comment by Aleksanaa** [comment]
@ofborg build dprint

**Review by Aleksanaa — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Tested on `aarch64-darwin`

**Comment by kachick** [comment]
Thanks! :pray:

**Pull request merged**
