### PR TITLE
arrow-cpp_4: init at 4.0.1

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
The arrow-cpp package has since been upgraded to 5.0.0, but 4.0.1 is still necessary for some software. In particular, tensorflow-datasets -> apache-beam -> pyarrow<5.0.0 -> arrow-cpp. I'm working towards packaging tensorflow-datasets which will require this transitive dependency.

I've left the `arrow-cpp` attribute unchaged: it still points to `arrow-cpp_5` so this PR won't cause any breakages.

Random question: in all-packages.nix there is a hack to get it building on i686. Is anyone using arrow-cpp on i686 these days? Could we just drop support for that?

See https://github.com/NixOS/nixpkgs/commit/51b1d4b421740ceddf556b9e425b955d1ca3c53a for more information about the previous upgrade from 4.0.1 -> 5.0.0.

A brief overview of changes, since the git diff isn't especially helpful in this case:
* `default.nix` has been renamed to `generic.nix`
* `4.nix` contains version 4.0.1 and calls `generic.nix`
* `default.nix` contains version 5.0.0 and calls `generic.nix`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137707` at b72e9821 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>arrow-cpp_5</li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>arrow-cpp_4</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchFromGitHub`.
Near pkgs/development/libraries/arrow-cpp/generic.nix:6:3:
```
  |
6 | , fetchFromGitHub
  |   ^
```
</li>
  </ul>
</details>

**Comment by veprbl** [comment]
> Random question: in all-packages.nix there is a hack to get it building on i686. Is anyone using arrow-cpp on i686 these days? Could we just drop support for that?

I do, however not with recent nixpkgs, so I don't mind if we drop the support.

@GrahamcOfBorg build pkgsi686Linux.arrow-cpp

**Comment by samuela** [comment]
Ok, no harm in keeping it! Was just curious

**Comment by veprbl** [comment]
@samuela Unfortunately it doesn't seem to work anymore. I suppose there is a difference in ABI between stdlibc++ from `gcc6` and `gcc10`.

Also I looked at Apache Beam and it doesn't seem like there is a ticket/PR on JIRA or GitHub to support pyarrow 5.0. The previous bump was trivial though: https://github.com/apache/beam/commit/d40abe7d3349aae39a9dcf2cc907d01844391409

**Comment by tobim** [comment]
There is an ongoing issue that gets resurrected by a bot for every release: https://issues.apache.org/jira/browse/BEAM-10582?focusedCommentId=17408252&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17408252

**Comment by risicle** [comment]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Comment by samuela** [comment]
re pyarrow: I have a follow up change on my fork ([commit](https://github.com/samuela/nixpkgs/commit/081923aaa4e8ab486b9033b40fd486cfb7bcf821)) that adds pyarrow_4 and pyarrow_5 versions. Everything seems to build and work fine for me. My plan was to contribute that change upstream after this PR lands.

**Comment by veprbl** [comment]
https://github.com/apache/beam/pull/15588

**Comment by veprbl** [comment]
Superseded by #153780?

**Comment by samuela** [comment]
yeah I'm happy to toss this once we have tensorfow-datasets successfully packaged. that was the original motivation for this PR

**Comment by veprbl** [comment]
I have no doubt it will go well.

**Pull request closed without merging**
