### PR TITLE
Fix FAT32 partition issues on sd-image-based images

### LINKED ISSUE #51150: [aarch64] The sd-image-aarch64 FAT32 partition does not pass `fsck`
## Issue description

Long log here:

 * https://logs.nix.samueldr.com/nixos/2018-11-27#1543351343-1543357884;

It has been reported as broken not only on the download image, but from a nix-built image by two separate users (@tilpner and @timclassic), while the pre-built image has been seen as broken by @bennofs and I.

cc @dezgeg.

### PR DESCRIPTION
**Pull request by samueldr**
###### Motivation for this change

Fixes #51150.

The main issue:

```
[...]
  Bad short file name (.).
  Auto-renaming it.
  Renamed to FSCK0000.000
```

Is already fixed using `mtools-4.0.21`. For `release-18.09` its update will need to be backported (#51159).

* * *

This fixes the seemingly-always-existing issue where the FAT32 partition was subtly broken by `mtools`. It wouldn't pass an `fsck`, even when freshly made. See #51150 for investigation details, and see commit messages for fixes details.

To ensure no regression with regards to the integrity of the boot partition, an `fsck` pass is now made just after copying the files. This will add a negligible amount of time to the whole build process, but will ensure tools will be able to manipulate the boot partition with success.

###### Things done

- ✔️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ✔️ NixOS
   - ⬜ macOS
   - ⬜ other Linux distributions
- ⬜ Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ✔️ Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- ⬜ Tested execution of all binary files (usually in `./result/bin/`)
- ⬜ Determined the impact on package closure size (by running `nix path-info -S` before and after)
- ✔️ Assured whether relevant documentation is up to date
- ✔️ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @dezgeg @tilpner @bennofs

### CODE REVIEW

**Comment by dezgeg** [comment]
Ah cool. I had noticed the `Start (0) does not point to parent` errors at some point last year but since no real world driver actually cares about those fields and as the mtools project didn't have much activity back then, I had ignored the problem.

Might be worth to report the problem with `-b` if the project is active nowadays.

**Comment by dezgeg** [comment]
Also this where this was copy-pasted from should be fixed as well:
````
nixos/modules/installer/cd-dvd/iso-image.nix:      mcopy -bpsvm -i "$out" ./* ::
````

**Comment by samueldr** [comment]
Do you think it should also include the `fsck` pass to validate the FS?

**Comment by dezgeg** [comment]
Yeah, it would be a good idea to have it there as well.

**Pull request merged**
