### PR TITLE
pkgconfig: rename to pkg-config

### PR DESCRIPTION
**Pull request by zimbatm**
Package attrs should map to the pname. It's confusing otherwise.

pkg-config is also the name used by most distributions:

Debian, Homebrew, Guix, OpenSuse

other distributions like FreeBSD ports, Fedora and Arch Linux call it
"pkgconf"

Waiting a few releases to make a tree-wide change to make it easier to
back-port things.

###### Motivation for this change

I keep typing `pkg-config` all the time.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Looks good! This might be one to not put in aliases.nix for a while since it is almost everywhere.

**Comment by jtojnar** [comment]
Hmm, repology displays the same name for nixpkgs: https://repology.org/metapackage/pkg-config/versions

Also a side note: [pkgconf](http://pkgconf.org/) is a competing project that implements pkg-config command for compatibility.

**Comment by vcunat** [comment]
:+1: for alias, one way or another.  I think adding aliases is safe even for the stable branch.  I'm not really certain a mass replace is worth it, but this PR isn't really about that.

**Comment by vcunat** [comment]
Repology displays the "name" attribute, not the attribute name, so that's already "pkg-config".  (uh, how would I better formulate that :)

**Comment by zimbatm** [comment]
Evaluation fails if I move it into aliases.nix, probably because it's an input for the stdenv and aliases.nix only comes after the stdenv bootstrap.

**Pull request merged**
