### PR TITLE
electrs: 0.9.1 -> 0.9.2

### PR DESCRIPTION
**Pull request by erikarvstedt**
#### Things done
- Built and run on `x86_64-linux`.

cc @prusnak

### CODE REVIEW

**Comment by prusnak** [comment]
@erikarvstedt will you please report the rocksdb issue to [electrs upstream](https://github.com/romanz/electrs) please?

**Review by nixbitcoin — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 80521a98acd2f6c3977b33997348b2390b8e850e
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEiDOlIkszv4ojhh+OtgROy6La5dAFAmF/7nUACgkQtgROy6La
5dCH9BAAmi2elsHzk+NYlRo0LLFBBMUwbU4m+419G2AoJWiZ6WRYvzfnj9D66Nxp
bMkeuPqO7IolyKzF6ny54Haq3Vg9dQt993Kdn3jk6DmLbBJLaSpKtzf7jwV77XvW
zvPNoFSO9U2wV2rhlRTxDjGpz8q7RPaQXTM3ot48NknGbSjxGqlqJJ1M+Iujar2E
jKpYKVAdx4PHepqaQcit3vzuyrlROdZIwg4gMCW62P1a8QAuR9lCcJ0wfsxzB0DY
oDOt3mY6H4cBu414cFfk4imDGC21SCekNwoT4aSeLl1YJKwa2cAgYWROiXObJR8c
bCdSrYeP1BhnYsod+wxL3TUWn3gOmbNDD2Lj85gyOmdZMsb2v9l8aiDNo4feTOcJ
e5aqo1J+8kBXh8p2LBPhQSjfb8QvYV6Z1hk2SeP9ulSZ1/1eQmG5bbeROs0M+x4u
jSpxSZZB3DWrk5TYNn5aUtlOwOSHk7iPmkYw2HIAI7wnbi/TDomkdeoAVqi+GqFv
xWG18d3IFuLrrPIhpmZjg3+8NV7YdVKXTSfd8AZsg+9G5qQrcYJaEYZDkXQEP1Nw
l2uySdo7K6ZtKf8OjZYoPRbPu+lfZysm7k0fOYdFObxTzRcuNa9vZw4E9IKBdiCc
00kVCPFI3ow1w0p0kCf4Qe+R7qRlPXRTPt6eBQ3MqyYXI7O9dbs=
=WxSC
-----END PGP SIGNATURE-----
```

**Comment by erikarvstedt** [comment]
[rust-rocksdb/librocksdb-sys](https://github.com/rust-rocksdb/rust-rocksdb/tree/master/librocksdb-sys) is currently tracking `rocksdb version 6.22.1`. I'll notify [romanz/rust-rocksdb](https://github.com/romanz/rust-rocksdb) when upstream upgrades to a compatible version.

**Comment by prusnak** [comment]
@GrahamcOfBorg build electrs

**Pull request merged**
