### PR TITLE
Update jetbrains editors

### PR DESCRIPTION
**Pull request by averelld**
###### Motivation for this change
Update via script. Only idea-ultimate has been tested.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by freezeboy** [comment]
Wouldn't be nice to include the darwin versions at the same time?

**Comment by averelld** [comment]
Right now they aren't packaged afaik. We don't even have 32bit support, but I guess it's worth an issue to add darwin support, there's an old TODO comment about that in the jetbrains-jdk derivation.

**Comment by freezeboy** [comment]
and I haven't looked at the nix expression + the update script, but it would also need quite a refactor to handle both platforms :disappointed:

**Comment by artemist** [comment]
I believe this is ready to be merged, although I don't have the authority to do so.

**Comment by aanderse** [comment]
@edwtjo @loskutov @miltador as listed maintainers for the packages involved here is anything else required from your perspectives to get this merged?

**Comment by averelld** [comment]
This has been sitting around for a while now, but there's also #58478 and #58392 (see the webstorm warning there, I only use Idea).
Also there's a (not required) JDK update here too which could be picked separately.

**Comment by flokli** [comment]
I did build all of them, tried out webstorm and pycharm. Thanks, and sorry for keeping this PR open so long…

**Comment by flokli** [comment]
backported to 19.03 in dd9a78c4aef, 686016b5e4d, d5b1fb99bb1, 4b4b59585c8, 9a66b56a3e6, d1f4e6ef252, e7ec56b2ed1, 107af48a5bd, e8092494fd0, e93b5687b11, 49f2712e480 and 9ebce7f0237.

**Pull request merged**
