### PR TITLE
chromium: 62.0.3202.62 -> 62.0.3202.75

### PR DESCRIPTION
**Pull request by YorikSar**
###### Motivation for this change

New version came and it also contains a security fix.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by YorikSar** [comment]
Builds are not fully tested, only up to start of main build part (836/29358 of third ninja run).

**Comment by YorikSar** [comment]
Builds have finally come through. Stable build works fine, beta/dev fail with:
```
[9062/29358] CXX obj/third_party/webrtc/p2p/rtc_p2p/port.o
FAILED: obj/third_party/webrtc/p2p/rtc_p2p/port.o
g++ -MMD -MF obj/third_party/webrtc/p2p/rtc_p2p/port.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBRTC_ENABLE_PROTOBUF=1 -DWEBRTC_RESTRICT_LOGGING -DHAVE_SCTP -DENABLE_EXTERNAL_AUTH -DHAVE_WEBRTC_VIDEO -DHAVE_WEBRTC_VOICE -DLOGGING_INSIDE_WEBRTC -DUSE_WEBRTC_DEV_BRANCH -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DFEATURE_ENABLE_VOICEMAIL -DGTEST_RELATIVE_PATH -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DFEATURE_ENABLE_VOICEMAIL -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DNO_MAIN_THREAD_WRAPPING -I../.. -Igen -I../../third_party/webrtc_overrides -I../../third_party/webrtc -I/nix/store/kbh1dk6k8chjh853w5d6sadlkdh94j74-glib-2.54.1-dev/include/glib-2.0 -I/nix/store/02nssrw1njxnqpfkib9jyr5s08w6nvkc-glib-2.54.1/lib/glib-2.0/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -std=gnu++14 -Wno-narrowing -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -c ../../third_party/webrtc/p2p/base/port.cc -o obj/third_party/webrtc/p2p/rtc_p2p/port.o
../../third_party/webrtc/p2p/base/port.cc: In member function 'cricket::ConnectionInfo cricket::Connection::stats()':
../../third_party/webrtc/p2p/base/port.cc:1515:68: error: 'round' was not declared in this scope
   stats_.recv_bytes_second = round(recv_rate_tracker_.ComputeRate());
```
Stable branch still works fine, I think we should merge it.

**Comment by Mic92** [comment]
Have you tried to add `port.cc`:

```c
#include <cmath>
```

to the failing file?

**Comment by YorikSar** [comment]
@Mic92 Yes, I've already backported couple of patches from master there.

**Comment by bendlas** [comment]
Pulled into master https://github.com/NixOS/nixpkgs/commit/da3c404e58fad73763b34e1e4a1d798edc15b46b
and stable https://github.com/NixOS/nixpkgs/commit/8945fb1c790a6765ac48e60837311aa9a521c9b9

Thanks for taking care of this and for also including the fixes from previous PR

**Comment by YorikSar** [comment]
@bendlas thanks!

I was hoping to add more patches to finally be able to build dev and beta versions, but you got here first :)
I guess I'll be posting another PR with them. I could probably include dev bump to 64 there as well.

**Comment by bendlas** [comment]
Sure, thank you!
Feel free to tag me right away, in a new PR

**Pull request closed without merging**
