### PR TITLE
mutt: 1.5.23 -> 1.5.24

### PR DESCRIPTION
**Pull request by k0ral**
Successfully built locally.

Cc maintainers: @the-kenny

### CODE REVIEW

**Comment by the-kenny** [comment]
This would break ```mutt-with-sidebar```. I'm not entirely sure how to proceed.

**Comment by the-kenny** [comment]
I think we should wait a few days for the ```-with-sidebar``` guys to release a new patch.

**Comment by vcunat** [comment]
Hmm, still nothing http://www.lunar-linux.org/mutt-sidebar/ (though there are others maintaining similar patches, e.g. https://aur.archlinux.org/packages/mutt-sidebar/)

**Comment by the-kenny** [comment]
I just pushed 47c92a8 with the patchset from Arch. Let me know if this is okay for you (who are using ```mutt-with-sidebar```)

**Pull request closed without merging**
