### PR TITLE
nixos-rebuild: add impure

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
I need to be able to do `--impure` in nixos-rebuild.
I've built my system (flake) with this flag :frowning: 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
Oops, I missed this list originally :D

Should the same be done for `nixos-install`? (Otherwise, you or people in the same situation as you might not be able to reinstall their system.)

**Comment by worldofpeace** [comment]
> Should the same be done for nixos-install? (Otherwise, you or people in the same situation as you might not be able to reinstall their system.)

Totally, will push.

**Comment by worldofpeace** [comment]
Ah wait this probably need (for sure duplicated) documentation. I will push this, but I don't think I'll get to updating nixos-install just yet.

**Comment by worldofpeace** [comment]
Okay docs added.

**Comment by cole-h** [comment]
LGTM :+1:

**Pull request merged**
