### PR TITLE
go_1_14: init at 1.14 and switch to it

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

https://golang.org/doc/go1.14

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

5 package failed to build - same set as in minor go version bump #80506 (related to git2go or not related to go)
act blsd gitAndTools.grv gitaly python38Packages.aria2p

736 package built

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/81071)

### CODE REVIEW

**Comment by Frostman** [comment]
@GrahamcOfBorg build yq-go hugo restic terraform

**Comment by kalbasit** [comment]
@GrahamcOfBorg build yq-go hugo restic terraform jx pet

**Review by kalbasit — APPROVED** [review]

**Comment by rvolosatovs** [comment]
Got this when applying the patch, which may or may not be relevant:
```
$ curl -sL https://github.com/NixOS/nixpkgs/pull/81071.patch | git am
Applying: go_1_14: init at 1.14 and switch to it
/home/rvolosatovs/src/github.com/NixOS/nixpkgs/.git/worktrees/nixos-unstable/rebase-apply/patch:275: space before tab in indent.
 		})
/home/rvolosatovs/src/github.com/NixOS/nixpkgs/.git/worktrees/nixos-unstable/rebase-apply/patch:276: space before tab in indent.
 	}
/home/rvolosatovs/src/github.com/NixOS/nixpkgs/.git/worktrees/nixos-unstable/rebase-apply/patch:277: trailing whitespace.
 
/home/rvolosatovs/src/github.com/NixOS/nixpkgs/.git/worktrees/nixos-unstable/rebase-apply/patch:301: space before tab in indent.
 	// sync tests
/home/rvolosatovs/src/github.com/NixOS/nixpkgs/.git/worktrees/nixos-unstable/rebase-apply/patch:302: space before tab in indent.
 	if goos != "js" { // js doesn't support -cpu=10
warning: squelched 13 whitespace errors
warning: 18 lines add whitespace errors.
```

**Comment by Frostman** [comment]
@rvolosatovs I think it's okay. The patch applies successfully anyway. There are whitespaces in the patch because of the way how it's formatted (it has two chars at the beginning of the line "booked" for +- chars and on the lines where only addition happens you'll have + and whitespace) in combination with tabs usage in Go.

**Review by c00w — APPROVED** [review]
This looks awesome :) - It looks like nothing is getting overridden to go1.13 - do we need to still keep it around?

**Comment by c00w** [comment]
Also you motivated me to go check some of the go 1.12 overrides, so I opened #81159 to get rid of some of them.

**Comment by Frostman** [comment]
@c00w I've been thinking about going through 1.12 first to get rid of it and then consider getting rid of 1.13 as well. Generally, it probably makes sense to keep the last two versions of the compiler, but not sure about it.

**Comment by Mic92** [comment]
In general we should only keep go versions around that are also supported upstream with security updates.

**Comment by c00w** [comment]
Per https://golang.org/doc/devel/release.html#policy - only the last 2 releases are supported (i.e. go 1.12 is no longer supported). I think before go1.13 landed we only had 1 version of go. go 1.12 was kept around because a number of packages didn't work with go 1.13. I don't think there is a lot of benefit to keeping a go version around other than the latest one if we don't need it to build a given package.

**Comment by Frostman** [comment]
@Mic92 @c00w yeah, makes sense. I'll look at the rest of the packages that are currently not yet builds with 1.14.

**Comment by Mic92** [comment]
@Frostman if there are fairly unmaintained it might also an option to remove them from nixpkgs depending on the package.

**Pull request merged**
