### PR TITLE
emacs: fix load-path and native-comp-eln-load-path

### LINKED ISSUE #247804: Emacs creates native-lisp directories unconditionally
### Describe the bug

Emacs will try to create a directory structure like
`share/emacs/native-lisp/29.1-ef7c54ae/` for every path in
`$NIX_PROFILES`. This seems to be because of the code in
`pkgs/applications/editors/emacs/site-start.el`.

On NixOS, the `NIX_PROFILES` environment variable may contain invalid
paths, for example `~/.nix-profile` may not exist. This causes Emacs to
create the full directory structure for that path. This also causes
issues if Nix afterwards wants to create `~/.nix-profile` as a symlink
but it already exists as a directory.

### Steps To Reproduce

```console
$ for i in $NIX_PROFILES; do file $i; done
/run/current-system/sw: symbolic link to /nix/store/d2p2vm19a44pf51c4pcjcw8p9hliv6x4-system-path
/nix/var/nix/profiles/default: symbolic link to /nix/var/nix/profiles/per-user/root/profile
/etc/profiles/per-user/tom: symbolic link to /etc/static/profiles/per-user/tom
/home/tom/.nix-profile: cannot open `/home/tom/.nix-profile' (No such file or directory)

$ emacs
C-x C-e

$ for i in $NIX_PROFILES; do file $i; done
/run/current-system/sw: symbolic link to /nix/store/d2p2vm19a44pf51c4pcjcw8p9hliv6x4-system-path
/nix/var/nix/profiles/default: symbolic link to /nix/var/nix/profiles/per-user/root/profile
/etc/profiles/per-user/tom: symbolic link to /etc/static/profiles/per-user/tom
/home/tom/.nix-profile: directory
```

### Expected behavior

The code in `site-start.el` should filter `NIX_PROFILES` down to only
paths that already exist.

### Additional context

Ideally, `NIX_PROFILES` would only include paths that exist in the first
place, but this is not the case. #241518 also seems related.

### Notify maintainers

@AndersonTorres
@adisbladis
@atemu
@jwiegley
@lovek323
@matthewbauer

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11.20230807.5a8e924`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

### PR DESCRIPTION
**Pull request by jian-lin**
## Description of changes

It is easier to review this PR commit by commit.

See commit messages for more info.

Fixes https://github.com/NixOS/nixpkgs/issues/247804

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jian-lin** [comment]
One of my commit changes https://github.com/NixOS/nixpkgs/commit/a131be8f99862d5fdb34c2aa809c8716493ef56e made by @chasecaleb

**Review by AndersonTorres — APPROVED** [review]
Very nice! Thanks for the effort.

**Review by Vonfry — APPROVED** [review]
diff LGTM

**Comment by ericdallo** [comment]
For some reason this broke my doom-emacs:
```
Unexpected error in Doom’s core: "/home/greg/.config/emacs/lisp/doom-cli.el", (file-missing "Cannot open load file" "No such file or directory" "/nix/store/6kfv9f52nnhvx436r4icmr0nd386sk50-emacs-unstable-with-packages-29.2/share/emacs/site-lisp/site-start")
```

**Comment by jian-lin** [comment]
@ericdallo

> For some reason this broke my doom-emacs

I do not think it is true given that this is a quite old PR and there is no similar report from other doom users.  Does your issue disappear if you revert some commits of this PR?

BTW, your error message reminds me of [this issue][1] and please check my [explanation][2] why you should not wrap Emacs twice.

Anyway, to improve Nixpkgs and help you, a proper issue report should be good.

[1]: https://github.com/NixOS/nixpkgs/issues/267548
[2]: https://github.com/NixOS/nixpkgs/issues/267548#issuecomment-1833505396

**Comment by ericdallo** [comment]
@jian-lin actually there is more people with same problem in doom's discord [here](https://discord.com/channels/406534637242810369/1146434516701941821/1146434516701941821), for now I manually commented out the doom piece of code that relies on site-start since I can't rollback and try that before this PR, but thanks for the help.

**Comment by collares** [comment]
I'm not affected by this issue, but I'll paste the Discord message (dated August 30th, 2023) here for convenience since Discord requires login:

> Hi, I'm running emacs 29 on nixos (with flakes), using a simple setup.
> I'm not managing my doomdir with nixos in any way. As far as I can tell nixos is unaware of doom and doom is unaware of nixos. 
> Using `emacsWithPackages` for things that need it, such as `vterm`
> 
> Now this setup has worked well for a long time. Now suddenly after a nix flake update, which seemingly didn't even update the emacs package at all, the doom cli gives me the following error on startup (full stacktrace attached):
> 
> ```
> Error: doom-core-error ("/home/arne/.emacs.d/lisp/doom-cli.el" (file-missing "Cannot open load file" "No such file or directory" "/nix/store/c4p8maaafb78ph4xyvbw24mmmw201kfx-emacs-with-packages-29.1/share/emacs/site-lisp/site-start"))
> ```
> 
> now the emacs-with-packages directory it wants to access does exist, however, /share/emacs/site-list/site-start are not in that directory
> there are other store paths that do include site-lisp/site-start.
> 
> I believe I've traced it down to this commit: https://github.com/NixOS/nixpkgs/pull/251529/commits/d1720077df3ce1e7fd5d822097b2e4fdb622dcdd
> which is part of this PR: https://github.com/NixOS/nixpkgs/pull/251529
> 
> Essentially, doom looks for `emacs-with-packages` in the store, which used to also symlink the site files, but now it no longer does. cited reason for removal: "I see no reason to symlink this dir."
> We could say the PR was rather inconsiderate, but from what I can tell, I have no idea why doom even looks for `emacs-with-packages`, since it's not even in `load-path` when I launch `emacs -q`
> 
> My main question here is: "what mechanism makes the doom cli look in that path?" I've trawled through the source, but my elisp-fu is not quite there

**Comment by jian-lin** [comment]
I do not have a discord account, so thanks @collares for the paste.  However, that paste does not bring more **facts** than what @ericdallo [said][1] before.  **Fact** is the most important thing in a bug report.  This [node][2] of Emacs manual explains that well.  There is not much I can do without a proper bug report (with a MWE).

[1]: https://github.com/NixOS/nixpkgs/pull/251529#issuecomment-1944586226
[2]: https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html

**Comment by collares** [comment]
@ericdallo I looked at your dotfiles repository, and I think you're misusing home-manager's `program.emacs` option. Try
```
programs.emacs = {
  enable = true;
  package = pkgs.emacs-unstable;
  extraPackages = (epkgs: [ epkgs.vterm ]);
};
```
instead. Your current solution (supplying `(pkgs.emacsPackagesFor pkgs.emacs-unstable).emacsWithPackages (epkgs: [ epkgs.vterm ])` directly to `programs.emacs.package`) is not intended, because home-manager calls `emacsWithPackages` itself to support the `extraPackages` option. Note that `services.emacs` automatically picks up the package chosen in `programs.emacs`, so you don't need to set it there.

(I wonder if the `emacs` symlink was added to allow this use case.)

**Comment by collares** [comment]
The reason this affects Doom specifically is because of the following. For reasons I don't fully understand, Doom calls emacs with `-q --no-site-file` and then manually loads the site files. A comment on `bin/doom` explains it:

```
;; - I intentionally avoid loading site files, so lisp/doom-cli.el can load them
;;   by hand later. There, I can suppress and deal with unhelpful warnings (e.g.
;;   "package cl is deprecated"), "Loading X...DONE" spam, and any other
;;   disasterous side-effects.
;;
;;   But be careful not to use -Q! It implies --no-site-lisp, which omits the
;;   site-lisp directory from `load-path'.
```

`doom-cli.el` then tries to load the site file itself:

```lisp
  (let ((inhibit-message (not init-file-debug)))
    (require 'cl nil t)
    (unless site-run-file
      (let ((site-run-file "site-start")
            (tail load-path)
            (lispdir (expand-file-name "../lisp" data-directory))
            dir)
        (while tail
          (setq dir (car tail))
          (let ((default-directory dir))
            (load (expand-file-name "subdirs.el") t inhibit-message t))
          (unless (string-prefix-p lispdir dir)
            (let ((default-directory dir))
              (load (expand-file-name "leim-list.el") t inhibit-message t)))
          (setq tail (cdr tail)))
        (load site-run-file t inhibit-message))))
```

That is, Doom expects `(load "site-start")` to find site-start.el, but I'm not sure that is guaranteed to work: `load` searches `load-path` (populated via `EMACSLOADPATH` -> `subdirs.el`), while presumably "normal" site-start.el loading is hard-coded to look at `$out/share/emacs/site-lisp/site-start.el`. 

Nevertheless, one may expect it to work if the `load-path` is not too weird, and indeed it works if `EMACSLOADPATH` originally points to `/nix/store/HASH-emacs-packages-deps/share/emacs/site-lisp:`, because this directory contains a `site-start.el` file. But if you use `emacsWithPackages` twice, `EMACSLOADPATH` equals  `/nix/store/HASH-emacs-with-packages-VERSION/share/emacs/site-lisp:` as in the error message. This previously worked due to the `emacs` symlink, but it is unclear if double-applying `emacsWithPackages` twice is a supported use case or if it just worked by accident.

**Comment by ericdallo** [comment]
@collares thank you for the explanation! I'll change my nix config to do that, good to know!

**Pull request merged**
