### PR TITLE
Mailman updates

### PR DESCRIPTION
**Pull request by alyssais**
Targeting staging because some dependencies needed updating and cause a mass rebuild.

importlib-resources no longer build on Python 2.

Upgraded mailman running fine for me.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by globin** [comment]
cc @lheckemann

**Comment by FRidh** [comment]
> importlib-resources no longer build on Python 2. 

We should keep an older compatible version around for Python 2, this is a core package.

**Comment by alyssais** [comment]
>> importlib-resources no longer build on Python 2. 
>
> We should keep an older compatible version around for Python 2, this
> is a core package.

Turns out I misunderstood the build failure anyway.  Fixed now.

**Comment by alyssais** [comment]
Cherry-picked a couple of fixes from master to get this to build on
staging.

**Review by lheckemann — APPROVED** [review]

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Pull request merged**
