### PR TITLE
Node: Init mathjax, threejs

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

I need threejs and mathjax for sagemath. Pinging @svanderburg as I'm unsure how exactly `node2nix` is supposed to be used.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
`nox-review` fails evaluation of `base16-builder` in `node-packages-generated.nix`.

**Comment by timokau** [comment]
Since @svanderburg appears to be unavailable and according to the log you have some experience, could you have a look at this @Ma27?

**Comment by Ma27** [comment]
First of all sorry for the slight delay :see_no_evil: 

The change doens't look entirely correct to me as it seems as there's been a downgrade from 1.5.3 to 1.5.1.

In `pkgs/development/node-packages` you simply have to invoke `./generate.sh` in order to regenerate the package set with the changes you've added.

Regarding `base16-builder`: I'm not entirely sure why this breaks for you as the current Hydra builds seem fine (https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.base16-builder.x86_64-linux), however let's regenerate the package set with `generate.sh` and see if this somehow fixes your issue :-)

**Comment by timokau** [comment]
Thanks for taking a look at this :)

I did generate this pr with `./generate.sh`. Probably the version in the stable channel is outdated. I re-generated it with `node2nix` build from master.

Now nox-review fails building facette with the error "network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443".

Thats probably because node2nix apparently always updates everything.

**Comment by Ma27** [comment]
yeah, seen it, however `facette` seems to be broken on master: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.facette.x86_64-linux/all

**Comment by timokau** [comment]
@grahamcofborg build nodePackages_8_x.mathjax nodePackages_8_x.three

**Comment by Ma27** [comment]
@svanderburg can't we just merge this? According to Hydra `facette` is broken on master as well and the change seems fine IMO %)

**Comment by timokau** [comment]
@svanderburg hasn't answered in 12 days, so I don't think we should wait for his approval right? Especially because these auto-generated files bitrot so fast.

**Comment by Ma27** [comment]
I see, however I don't have commit access, so we'll need a maintainer to merge this :-)

**Comment by timokau** [comment]
Oh, somehow I assumed you did.

@svanderburg Thanks!

**Pull request merged**
