### PR TITLE
stdenv: wrap phase running actions of genericBuild into a function

### PR DESCRIPTION
**Pull request by Ninlives**
###### Description of changes

Provide a `runPhase` function which wraps the phase running action of genericBuild. The new function can be used as an interface by `nix develop`, i.e. `nix develop some#flake --build` may just call `runPhase build`, which makes its behavior more consistent with `nix build`. In preparation of fixing https://github.com/NixOS/nix/issues/6202

###### Things done

Only tested with `nix build nixpkgs#hello` (`ca-derivations` by default when?). If someone has more free computing resources, please help me test the PR.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thufschmitt — APPROVED** [review]
That looks good (although I barely know anything about the intrinsics of stdenv, so don't trust me too much on that).

Wrt https://github.com/NixOS/nix/issues/6202, note however that we probably wouldn't be able to use this for some time as we can't rely on people using a brand new nixpkgs

**Comment by Ninlives** [comment]
Maybe we can use something like `declare -F runPhase > /dev/null && runPhase build || eval "${!buildPhase:-$buildPhase}"` as a starting point, then drop the legacy method once the latest nixpkgs version that does not export `runPhase` enters EOL.

By the way, maybe it is a little bit late now, but IMHO since the implementation of `nix develop` is coupling with `stdenv`, we should standarize a set of stable interface that will be implemented by `stdenv` and can be safely used by externel tools, to avoid more compatibility issues.

**Comment by Artturin** [comment]
Commit name wrong and should target staging, check CONTRIBUTING.md for how to rebase

**Comment by Artturin** [comment]
Commit name wrong and should target staging, check CONTRIBUTING.md for how to rebase

**Comment by Ninlives** [comment]
I've edited the commit name and the target branch, please check.

**Comment by Ninlives** [comment]
Oops, I messed it up, sorry, will fix it later.

**Comment by Artturin** [comment]
This is why I said to read CONTRIBUTING.md as it has instructions. Please open a new pr to avoid spamming people

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/230874

**Pull request closed without merging**
