### PR TITLE
nixos/nzbget: add settings option

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
While the configuration file of `nzbget` is managed by the application itself, `nzbget` allows you to specify overrides of configuration file options via the command line. All things declarative! ...at least when it makes sense :+1:

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by schnusch** [comment]
With the following configuration
```nix
services.nzbget.settings = {
  ControlIP = "127.0.0.1";
  MainDir = "...";
  DestDir = "\${MainDir}/complete";
  DiskSpace = 0;
  "Server1.Name" = "...";
  "Server1.Host" = "...";
  "Server1.Port" = 119;
  "Server1.Username" = "...";
  "Server1.Password" = "...";
  "Server1.Connections" = 2;
};
```
and the default config file all but `ControlIP` are ignored.

**Comment by aanderse** [comment]
@GrahamcOfBorg test nzbget

@schnusch thanks for the ping on this. I have finally come back to this PR and "finished" it, including NixOS tests to ensure the new `settings` option is operating as expected :+1: Give it another test and I believe it should work for you now.

**Comment by aanderse** [comment]
@schnusch any final objections or am I good to merge?

**Comment by KyleOndy** [comment]
> @KyleOndy can you please paste your configuration?

I was working on providing a minimal example, and cannot reproduce it. Let me keep bifurcating my configuration.

**Comment by aanderse** [comment]
Right. From my resume with `nzbget` generally the values do not show up in the web ui, but they do take effect. This can be confirmed with the cli like I do I'm the NixOS test as seen in this PR.

Maybe we should open an issue upstream?

**Comment by KyleOndy** [comment]
@aanderse Interesting! That is very non-obvious behavior. With that knowledge let me see if I can get things working. 

I don't see anything in the [upstraem issue tracker](https://github.com/nzbget/nzbget/issues). I wonder if this is a known issue. This feels like it would be a common use case, and something that would be noticed.

**Pull request merged**
