### PR TITLE
exult: 1.6 -> 1.8

### LINKED ISSUE #189172: exult update available
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: [exult](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/exult/default.nix)

current version: 1.6
desired version: [1.8](https://github.com/exult/exult/releases/tag/v1.8)

###### Notify maintainers

maintainers:

@eelcovisser (hope I got the correct maintainer, sorry if not)

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by azahi**
###### Description of changes

Fixes: #189172

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by azahi** [comment]
@revuwa could you please check if this works for you? I can't test this out because I don't own Ultima 7.

**Comment by revuwa** [comment]
> @revuwa could you please check if this works for you? I can't test this out because I don't own Ultima 7.

Sure - but this is the very first time I do this, so I better tell exactly what I've done:

- git clone https://github.com/NixOS/nixpkgs.git && cd nixpkgs 
- nixpkgs-review pr 189246
- ./results/exult/bin/exult

With the result, that exult (v1.8.0) started and loaded the gamefiles without any issues.
I played a bit; can move, can grab things, can talk to people etc.
I would say it works - so thank you so much at this point.

_BTW I would be glad to give you Ultima 7 as a gift, if you like(?)
E. g. by donating over PayPal or whatever, and you could get it [here](https://www.gog.com/game/ultima_7_complete) (currently on sale €1.49)._

**Comment by azahi** [comment]
> _BTW I would be glad to give you Ultima 7 as a gift, if you like(?)_

Thank you very much for the offer but I'll have to refuse, I'm doing this stuff for fun and I'm just glad I could help 😄

**Comment by onny** [comment]
Result of `nixpkgs-review pr 189246` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>exult</li>
  </ul>
</details>

**Pull request merged**
