### PR TITLE
tpm2-tools: 4.1.3 -> 5.0

### PR DESCRIPTION
**Pull request by baloo**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113246` at 88f8fcfe run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.discover</li>
    <li>libsForQt514.discover</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d98df648ce207e6e07393c131666feb0">fwupd</a></li></li>
    <li><a href="https://gist.github.com/378d17215f3127d4fba71817058d61ca">gnome-firmware-updater</a></li></li>
    <li><a href="https://gist.github.com/3dbd5e2a7a44a5a75d2f3fdfd7061296">libsForQt5.discover</a></li> (libsForQt515.discover ,plasma5Packages.discover)</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/5ecfdd1a85d22a5ddeeb8766dec0321d">tpm2-pkcs11</a></li></li>
    <li><a href="https://gist.github.com/5e62121577c095d56c9fd38920531e3f">tpm2-tools</a></li></li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113246` at 88f8fcfe run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.discover</li>
    <li>libsForQt514.discover</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/f9c8cbcac574121dc8e596a3f2e028a1">fwupd</a></li></li>
    <li><a href="https://gist.github.com/4a55a43e32fc134d27a88f00920844c4">gnome-firmware-updater</a></li></li>
    <li><a href="https://gist.github.com/b34d6fe302a8eb0ca025ccc5615ff2f3">gnome3.gnome-software</a></li></li>
    <li><a href="https://gist.github.com/6df17bc2718eb6ec7748c2fe734bfb97">libsForQt5.discover</a></li> (libsForQt515.discover ,plasma5Packages.discover)</li>
    <li><a href="https://gist.github.com/268db9ee51c8205e63783d003dbcc33d">tpm2-pkcs11</a></li></li>
    <li><a href="https://gist.github.com/99f68fdef0bc9315812ea91639ba0f07">tpm2-tools</a></li></li>
  </ul>
</details>

**Comment by baloo** [comment]
I'm not sure the fwupd build error is related to this change.
If I read the code correctly, the build should be currently broken and would require this change:
```
diff --git a/pkgs/os-specific/linux/firmware/fwupd/default.nix b/pkgs/os-specific/linux/firmware/fwupd/default.nix
index 453d3ab9a47..4cd7070b3c8 100644
--- a/pkgs/os-specific/linux/firmware/fwupd/default.nix
+++ b/pkgs/os-specific/linux/firmware/fwupd/default.nix
@@ -74,6 +74,9 @@ let
   # only redfish for x86_64
   haveRedfish = stdenv.isx86_64;

+  # only use msr if x86 (requires cpuid)
+  haveMSR = isx86;
+
   # # Currently broken on Aarch64
   # haveFlashrom = isx86;
   # Experimental
@@ -196,6 +199,8 @@ let
       "-Dplugin_redfish=false"
     ] ++ lib.optionals haveFlashrom [
       "-Dplugin_flashrom=true"
+    ] ++ lib.optionals (!haveMSR) [
+      "-Dplugin_msr=false"
     ];

     # TODO: wrapGAppsHook wraps efi capsule even though it is not ELF

```

**Comment by jtojnar** [comment]
Quite a few changes:

- https://github.com/tpm2-software/tpm2-tools/releases/tag/4.2
- https://github.com/tpm2-software/tpm2-tools/releases/tag/4.2.1
- https://github.com/tpm2-software/tpm2-tools/releases/tag/4.3.0
- https://github.com/tpm2-software/tpm2-tools/releases/tag/5.0

Do not see anything obviously troublesome.

There are some new tools and also they switched to busybox-style single executable which wrappers might interfere if the executable is a script but that probably is not the case.

**Comment by baloo** [comment]
Yeah, the busybox single executable format was actually what I was looking for. I have a tool that relies on it, and I thought it was easier to just upgrade.

**Pull request merged**
