### PR TITLE
flatpak: 1.10.2 → 1.12.2

### PR DESCRIPTION
**Pull request by shazow**
###### Motivation for this change

Version bump from 1.10.x stable series to the new 1.12.x stable series.

Changes:
- https://github.com/flatpak/flatpak/releases/tag/1.11.1
- https://github.com/flatpak/flatpak/releases/tag/1.11.2
- https://github.com/flatpak/flatpak/releases/tag/1.11.3
- https://github.com/flatpak/flatpak/releases/tag/1.12.0
- https://github.com/flatpak/flatpak/releases/tag/1.12.1
- https://github.com/flatpak/flatpak/releases/tag/1.12.2

Security advisories:
- https://github.com/flatpak/flatpak/security/advisories/GHSA-67h7-w3jq-vh4q

Note that 1.11.x releases were release-candidates for 1.12.

###### Things done

1. Bumped version/hash
2. Removed patches that aren't relevant anymore.
3. Updated paths

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

## Passing tests

- [x] flatpak/test-auth.sh.test
- [x] flatpak/test-basic.sh.test
- [x] flatpak/test-build-update-repo.sh.test
- [ ] flatpak/test-bundle@system-norevokefs.wrap.test
- [ ] flatpak/test-bundle@system.wrap.test
- [ ] flatpak/test-bundle@user.wrap.test
- [x] flatpak/test-completion.sh.test
- [x] flatpak/test-config.sh.test
- [x] flatpak/test-context.test
- [x] flatpak/test-default-remotes.sh.test
- [x] flatpak/test-exports.test
- [x] flatpak/test-extensions.sh.test
- [x] flatpak/test-http-utils.sh.test
- [x] flatpak/test-info@system.wrap.test
- [x] flatpak/test-info@user.wrap.test
- [x] flatpak/test-instance.test
- [x] flatpak/test-oci-registry@system.wrap.test
- [x] flatpak/test-oci-registry@user.wrap.test
- [x] flatpak/test-oci.sh.test
- [x] flatpak/test-override.sh.test
- [x] flatpak/test-portal.test
- [ ] flatpak/test-prune.sh.test
- [x] flatpak/test-repo@system,oldsummary.wrap.test
- [x] flatpak/test-repo@system-norevokefs.wrap.test
- [x] flatpak/test-repo@system.wrap.test
- [x] flatpak/test-repo@user,oldsummary.wrap.test
- [x] flatpak/test-repo@user.wrap.test
- [ ] flatpak/test-run@system,deltas.wrap.test
- [ ] flatpak/test-run@system,nodeltas.wrap.test
- [ ] flatpak/test-run@system-norevokefs,deltas.wrap.test
- [ ] flatpak/test-run@system-norevokefs,nodeltas.wrap.test
- [ ] flatpak/test-run@user,deltas.wrap.test
- [ ] flatpak/test-run@user,nodeltas.wrap.test
- [x] flatpak/test-sideload@system.wrap.test
- [x] flatpak/test-sideload@user.wrap.test
- [x] flatpak/test-subset@system.wrap.test
- [x] flatpak/test-subset@user.wrap.test
- [x] flatpak/test-summaries@system.wrap.test
- [x] flatpak/test-summaries@user.wrap.test
- [x] flatpak/test-unused.sh.test
- [x] flatpak/test-update-portal@system.wrap.test
- [x] flatpak/test-update-portal@user.wrap.test
- [x] flatpak/test-update-remote-configuration@newsummary.wrap.test
- [x] flatpak/test-update-remote-configuration@oldsummary.wrap.test
- [x] flatpak/testcommon.test
- [x] flatpak/testlibrary.test

### CODE REVIEW

**Comment by jtojnar** [comment]
With the changes, it is possible to delete `use-flatpak-from-path.patch` and drop `fetchpatch` from arguments.

We should also check that https://github.com/flatpak/flatpak/commit/a99b748931e6444dadb0d0c8c1565da23f755800 which introduced the `FLATPAK_BINARY` does not conflict with our upstreamed patch https://github.com/flatpak/flatpak/commit/495449daf6d3c072519a36c9e4bc6cc1da4d31db (does not seem to based on the code changes) and that the environment variable applies everywhere it did in `use-flatpak-from-path.patch`.

**Comment by jtojnar** [comment]
Looks like https://github.com/flatpak/flatpak/commit/a99b748931e6444dadb0d0c8c1565da23f755800 should fix both occurrences but it did not update tests to allow `FLATPAK_BINARY=flatpak`.

**Comment by jtojnar** [comment]
Right, forgot about that. Merged now.

Now the only thing remaining is the tests (`nix-build nixos/tests/installed-tests -A flatpak`). We will need the test part of the deleted patch.

**Comment by shazow** [comment]
Btw I've been running this build of flatpak with Steam and Proton 6.3 and seems to work great. (This is otherwise a known issue that Valve's pressurevessel mechanism used in recent Proton versions doesn't work with flatpak 1.10.x.)

**Comment by jtojnar** [comment]
Yeah, just copied what I had in `git stash`, the test name needs to be adjusted as you noticed.

The failure is actually completely unrelated and it is a [common issue](https://nixos.org/manual/nixpkgs/unstable/#ssec-gnome-common-issues-double-wrapped). I even tried to make sure we already do not use `makeWrapper` to preclude it but forgot to check for `wrapGAppsNoGuiHook`, which uses it internally.

GLib based programs typically get the program name from [`g_get_prgname`](https://docs.gtk.org/glib/func.get_prgname.html), which should respect `argv[0]`. Our wrapper scripts use `exec -a` so that the original `argv[0]` will be used. Unfortunately, when we wrap an already wrapped binary it will break because Linux ignores `-a` flag of `exec` when executing a script.

Reusing the existing wrapper should fix that:

```
--- a/pkgs/development/libraries/flatpak/default.nix
+++ b/pkgs/development/libraries/flatpak/default.nix
@@ -179,8 +179,11 @@ stdenv.mkDerivation rec {
     PATH=${lib.makeBinPath [vsc-py]}:$PATH patchShebangs --build subprojects/variant-schema-compiler/variant-schema-compiler
   '';
 
-  postFixup = ''
-    wrapProgram $out/bin/flatpak --set FLATPAK_BINARY flatpak
+  preFixup = ''
+    gappsWrapperArgs+=(
+      # Use flatpak from PATH in exported assets (e.g. desktop files).
+      --set FLATPAK_BINARY flatpak
+    )
   '';
 
   passthru = {
```

https://github.com/flatpak/flatpak/blob/1.12.2/tests/test-basic.sh#L80

**Comment by jtojnar** [comment]
Yeah, that is why I prefer to run each test manually. You could even try to parallelize it:

```patch
--- a/nixos/tests/installed-tests/default.nix
+++ b/nixos/tests/installed-tests/default.nix
@@ -67,7 +67,7 @@ let
             '' +
             ''
               machine.succeed(
-                  "gnome-desktop-testing-runner ${testRunnerFlags} -d '${tested.installedTests}/share'"
+                  "gnome-desktop-testing-runner ${testRunnerFlags} -d '${tested.installedTests}/share' 2>&1"
               )
             '';
         }
--- a/nixos/tests/installed-tests/flatpak.nix
+++ b/nixos/tests/installed-tests/flatpak.nix
@@ -1,6 +1,59 @@
 { pkgs, makeInstalledTest, ... }:
 
+let
+tests = [
+  "flatpak/test-auth.sh.test"
+  "flatpak/test-basic.sh.test"
+  "flatpak/test-build-update-repo.sh.test"
+  "flatpak/test-bundle@system-norevokefs.wrap.test"
+  "flatpak/test-bundle@system.wrap.test"
+  "flatpak/test-bundle@user.wrap.test"
+  "flatpak/test-completion.sh.test"
+  "flatpak/test-config.sh.test"
+  "flatpak/test-context.test"
+  "flatpak/test-default-remotes.sh.test"
+  "flatpak/test-exports.test"
+  "flatpak/test-extensions.sh.test"
+  "flatpak/test-http-utils.sh.test"
+  "flatpak/test-info@system.wrap.test"
+  "flatpak/test-info@user.wrap.test"
+  "flatpak/test-instance.test"
+  "flatpak/test-oci-registry@system.wrap.test"
+  "flatpak/test-oci-registry@user.wrap.test"
+  "flatpak/test-oci.sh.test"
+  "flatpak/test-override.sh.test"
+  "flatpak/test-portal.test"
+  "flatpak/test-prune.sh.test"
+  "flatpak/test-repo@system,oldsummary.wrap.test"
+  "flatpak/test-repo@system-norevokefs.wrap.test"
+  "flatpak/test-repo@system.wrap.test"
+  "flatpak/test-repo@user,oldsummary.wrap.test"
+  "flatpak/test-repo@user.wrap.test"
+  "flatpak/test-run@system,deltas.wrap.test"
+  "flatpak/test-run@system,nodeltas.wrap.test"
+  "flatpak/test-run@system-norevokefs,deltas.wrap.test"
+  "flatpak/test-run@system-norevokefs,nodeltas.wrap.test"
+  "flatpak/test-run@user,deltas.wrap.test"
+  "flatpak/test-run@user,nodeltas.wrap.test"
+  "flatpak/test-sideload@system.wrap.test"
+  "flatpak/test-sideload@user.wrap.test"
+  "flatpak/test-subset@system.wrap.test"
+  "flatpak/test-subset@user.wrap.test"
+  "flatpak/test-summaries@system.wrap.test"
+  "flatpak/test-summaries@user.wrap.test"
+  "flatpak/test-unused.sh.test"
+  "flatpak/test-update-portal@system.wrap.test"
+  "flatpak/test-update-portal@user.wrap.test"
+  "flatpak/test-update-remote-configuration@newsummary.wrap.test"
+  "flatpak/test-update-remote-configuration@oldsummary.wrap.test"
+  "flatpak/testcommon.test"
+  "flatpak/testlibrary.test"
+];
+in
+map
+(test:
 makeInstalledTest {
+  name = "${builtins.replaceStrings ["flatpak/" ".test"] ["" ""] test}";
   tested = pkgs.flatpak;
   withX11 = true;
 
@@ -12,5 +65,6 @@ makeInstalledTest {
     virtualisation.diskSize = 3072;
   };
 
-  testRunnerFlags = "--timeout 3600";
-}
+  testRunnerFlags = "--timeout 3600 ${test}";
+})
+tests
```

Do not forget `--keep-going` flag for `nix-build`. You can get clean logs later using `nix log`.

**Comment by shazow** [comment]
Ah handy for next time.

This is what my run finished with:

```
SUMMARY: total=46; passed=36; skipped=0; failed=10; user=1389.6s; system=1062.0s; maxrss=439840
FAIL: flatpak/test-bundle@system-norevokefs.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-run@system-norevokefs,deltas.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-bundle@user.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-run@system,deltas.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-prune.sh.test (Child process exited with code 1)
FAIL: flatpak/test-run@user,deltas.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-bundle@system.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-run@user,nodeltas.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-run@system,nodeltas.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-run@system-norevokefs,nodeltas.wrap.test (Child process exited with code 1)
```

Is there a reference anywhere for the test failing state before this PR?

**Comment by jtojnar** [comment]
Yeah, opened https://github.com/flatpak/flatpak/pull/4496.

**Comment by shazow** [comment]
Thanks! I'll add a fetchpatch from that PR for now.

**Comment by shazow** [comment]
Confirmed that the tests pass now. What's the next step?

**Comment by jtojnar** [comment]
Nice. Good job.

We can merge once ofborg is done.

**Pull request merged**
