### PR TITLE
bant: 0.1.7 fix changed hash of fixed derivation.

### PR DESCRIPTION
**Pull request by hzeller**
The hash of the fixed derivation changed

If the old derivation with the hash was cached on the system, the build failed with:

```
ERROR: /build/output/external/googletest~1.14.0.bcr.1/BUILD.bazel:80:11: Compiling googletest/src/gtest.cc failed: The include path '/nix/store/p5w6cmwqfvhyaf4vjr7jb18a90icrrr2-openjdk-21.0.3+9/include' references a path outside of the execution root.
ERROR: /build/output/external/abseil-cpp~20240116.2/absl/base/BUILD.bazel:755:11: Compiling absl/base/internal/strerror.cc failed: The include path '/nix/store/p5w6cmwqfvhyaf4vjr7jb18a90icrrr2-openjdk-21.0.3+9/include' references a path outside of the execution root.
```

This indicates that the derivation also bakes in the path of the used JDK, which apparently changed since last time. Quick fix for now: adapt hash, but hopefully there could be a more long-term solution.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by lromor — APPROVED** [review]

**Comment by hzeller** [comment]
@NixOS/bazel Bazel maintainers - are there ways to get these fixed derivations more stable/auto-updated if any of the things bazel puts in the derivation ? I am not sure if this happens if bazel is updated or if a relevant other dependency, such as Java, is updated (the observed error looks like it was due to different java dependencies that were baked into the derivation somehow)

**Review by lromor — APPROVED** [review]

**Review by lromor — APPROVED** [review]

**Comment by hzeller** [comment]
Bazel folks, do you have a suggestion for the changing-hash issue observed and addressed here ?

In any case, a merge by someone with that permission would also be cool.

**Comment by hzeller** [comment]
Adding @fabianhjr as you merged the last PR regarding bant #342177

**Comment by fabianhjr** [comment]
Hi @hzeller, now that it is in by-name you can use the new merge-bot to merge changes :3

https://discourse.nixos.org/t/announcing-nixpkgs-merge-bot/34265

**Comment by fabianhjr** [comment]
@nixpkgs-merge-bot merge

**Comment by fabianhjr** [comment]
@NixOS/nixpkgs-merge-bot merge

**Comment by fabianhjr** [comment]
Oh nvm, I thought it was the case now UnU

**Pull request merged**
