### PR TITLE
git-machete: add test and update script

### PR DESCRIPTION
**Pull request by blitz**
###### Motivation for this change

Add an update script and a simple version test for `git-machete` to allow fearless automatic updates by @r-ryantm.

I've tried out the update script via `nix-shell ./maintainers/scripts/update.nix --argstr package git-machete` and it works for me.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@pawellipski

### CODE REVIEW

**Review by PawelLipski — APPROVED** [review]
FWIW, I'm leaving my approval :)

**Comment by PawelLipski** [comment]
@blitz out of curiosity, how often does @r-ryantm perform its update? is it cronned somehow?

**Comment by blitz** [comment]
> @blitz out of curiosity, how often does @r-ryantm perform its update? is it cronned somehow?

I couldn't recognize a pattern beyond "it eventually comes along". Maybe @ryantm knows? :)

**Comment by ryantm** [comment]
It's basically always trying to make updates, but sometimes it gets stuck building something.

**Comment by SuperSandro2000** [comment]
Also nix-update would handle this without the addition.

**Pull request merged**
