### PR TITLE
nixos/kanidm: fix broken doc links

### PR DESCRIPTION
**Pull request by tuxiqae**
## Description of changes
Fix broken Kanidm docs links, also use documentation portal instead of links to MD pages in GH

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tuxiqae** [comment]
Wasn't sure what to tick since I only made changes to option descriptions.

**Comment by nagy** [comment]
Thanks, can you follow the guidelines for the commit message at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions ?

**Comment by tuxiqae** [comment]
@nagy Fixed (?)

**Comment by nagy** [comment]
Since it is a nixos module it needs the prefix. I would suggest `nixos/kanidm: fix broken doc links`. Also the PR title should be the same, if you only have this one commit.

**Comment by tuxiqae** [comment]
@nagy

**Review by nagy — APPROVED** [review]

**Review by Flakebi — APPROVED** [review]
Thank you!
Looks obviously good to me

**Review by erictapen — APPROVED** [review]
Thanks!

**Pull request merged**
