### PR TITLE
{tvheadend,antennas}: drop

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

See https://github.com/NixOS/nixpkgs/pull/332259. `tvheadend` is stuck on an unmaintained version that depends on FFmpeg 4; upstream recommend that users install the 4.3 development version, which will soon become the 4.4 stable release, but that version is backwards‐incompatible with current configurations, and it seems that nobody is willing to maintain the package and service. Since we have no way of making a decision here and the package and service are effectively unmaintained and headed for permanent bitrot, let’s be honest with our users and drop the code. Hopefully someone will step up to maintain it.

I have also removed `antennas`, as it is intended solely for use with `tvheadend`.

@bachp @Gooxey I see that you have both done work on the `antennas` module, so I assume that you are `tvheadend` users. Would you be willing to take up the mantle of `tvheadend` maintenance and help us decide what to do about 4.3/4.4? I didn’t notice the `antennas` module before now, so I didn’t think to ping you on the original PR, but I’d be very happy to close this in favour of https://github.com/NixOS/nixpkgs/pull/332259 if we can get the package maintained again and get it on a current version.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bachp** [comment]
@emilazy I used antennas in the past together with a TVheadend container. I never used the TVHeadend NixOS module. But I switched to [Threadfin](https://github.com/Threadfin/Threadfin/) in the meantime whichs seems to be better maintained.

So I am OK with the removal of these two modules.

**Review by bachp — DISMISSED** [review]
An entry in the release notes should be added about the removal of these two services and packages

**Comment by emilazy** [comment]
Good point about the release notes! Added.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Please Renee otherwise come fine to merge

**Comment by emilazy** [comment]
Rebased. Still holding out hope that we hear from @pyle or @Gooxey, but I guess we can merge this within a day or so if not.

**Comment by oneingan** [comment]
I use both. I would like to mantain them, but the tvheadend 4.3-unstable version.

**Comment by pyle** [comment]
Sorry for the late response, for tvheadend i have no strong desire or time to maintain it

**Comment by emilazy** [comment]
Thank you for the response all the same!

I’m currently waiting on a reply to https://github.com/NixOS/nixpkgs/pull/332259#issuecomment-2305196447 in the other PR from @oneingan that I hope will let us figure out a sustainable path forward for the package and module. I’ll probably merge this in a few days if I don’t hear back so that it’s not blocking FFmpeg 4 clean‐ups; the package and module can always be re‐added a later date once we figure out maintenance and what to do with them.

**Review by bachp — APPROVED** [review]

**Comment by Gooxey** [comment]
Sorry for the late response. I have no interest in maintaining tvheadend or antennas, as I only know the basics of nix. But I do need these two packages for my server, so examples of how I can continue to use them even if the packages are no longer available would be very helpful.

**Comment by emilazy** [comment]
Thanks for the response, @Gooxey. Overlaying your own package should continue to work even after this PR, although you’d have to copy the NixOS module into your configuration if you use that. I packaged the Git version in https://github.com/NixOS/nixpkgs/pull/332259; if you managed to recreate that with an overlay I’d say you’re qualified to maintain it, but obviously there’s no obligation to :)

Honestly, I would be happy to just merge the update I wrote and leave the package without a maintainer for now, which I assume would make things easier for you in general, but I need someone who knows the software well enough to explain what the backwards incompatibility compared to 4.2 is and how difficult migration would be for users. If you can comment on that it’d be very helpful, as the upstream warnings about “no direct upgrade path from v4.2 to v4.3/v4.4” and the comment in https://github.com/NixOS/nixpkgs/pull/168620 saying “Updating to latest master (aka v4.3) will break configs of most people using v4.2” concern me that it would break as many people’s setups as just removing it for being unmaintained would.

**Comment by Gooxey** [comment]
Leaving the package without a maintainer seems like the best solution. Maybe someone will start maintaining it in the future. But in the meantime, other people who need this package, or at least the module, will not have the unnecessary problems that would be caused by removing both packages.

As for TVHeadend, I have never had anything to do with it and only know that it has something to do with TV channels. I just upgraded an old server from Ubuntu to NixOS. But maybe you could add some kind of switch that would allow you to use either the legacy v4.2 or the latest supported version. In theory, this would satisfy both parties, unless I am forgetting something.

**Comment by emilazy** [comment]
> Leaving the package without a maintainer seems like the best solution. Maybe someone will start maintaining it in the future. But in the meantime, other people who need this package, or at least the module, will not have the unnecessary problems that would be caused by removing both packages.

Keeping 4.2 gives us the problems of having to maintain an old end‐of‐life version of FFmpeg indefinitely when every other working source package in Nixpkgs has been migrated off it. It’s also already taken up limited maintainer resources from the rest of the tree multiple times as changes in other packages have caused it to break and need fixing by people who, like me, have no particular relevant interest or expertise in it. So while I don’t have any inherent objection to leaving the package abandoned for now, we do need to get it off 4.2, and unfortunately it seems like nobody knows enough about Tvheadend to be able to tell us what compatibility risks that would entail or help us mitigate them.

That’s unfortunate, but these kinds of issues are why keeping unmaintained packages around is a liability. I’ve already spent more time on this package than almost any other involved in the mass FFmpeg migration and I’m not sure a resolution is in sight. Hopefully @oneingan will reply to https://github.com/NixOS/nixpkgs/pull/332259#issuecomment-2305196447 soon; otherwise I think the best way forward is to drop the packages for now and revive them when someone who can maintain them steps up.

**Comment by emilazy** [comment]
Merging per https://github.com/NixOS/nixpkgs/pull/332259#issuecomment-2310908045. Hopefully we’ll have 4.3 packaged soon!

**Pull request merged**
