### PR TITLE
[staging-next] rustc: 1.80.0 -> 1.80.1, add zlib dependency on Darwin

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

It's pretty late in the cycle, but 1.80.1 fixes a miscompilation that will otherwise be EXCEPTIONALLY annoying to debug, so we should probably eat the rebuilds.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by alyssais — APPROVED** [review]

**Comment by pdeva** [comment]
for some reason, even though the package says version `1.80.1` cargo itself thinks `1.80.0` is installed:

```
pdeva@code-pdeva → which cargo
/nix/store/jav6m86f97cpj1l5d3waqhq1yz837pxp-cargo-1.80.1/bin/cargo

pdeva@code-pdeva → cargo --version
cargo 1.80.0 (376290515 2024-07-16)
```

**Comment by alyssais** [comment]
Was there a new cargo release, or just rustc?

**Comment by alyssais** [comment]
They usually do, but in this case, the only difference between 1.80.0 and 1.80.1 is two bug fixes in rustc, so I suppose they didn't bother with a new Cargo version that would have been identical to the previous one.

```ShellSession
% nix-shell -I nixpkgs=channel:nixos-unstable -p rustc
these 3 paths will be fetched (223.10 MiB download, 1180.35 MiB unpacked):
  /nix/store/j0n6nfs2jznrxl7r8yq8nvc683v16vxr-llvm-18.1.8-lib
  /nix/store/pzbhqvfp6lxjpb816f3p4gp2nipavv75-rustc-1.80.1
  /nix/store/ch5mgr7p0i47d8f7xbga2r1qdzhxqcnb-rustc-wrapper-1.80.1
copying path '/nix/store/j0n6nfs2jznrxl7r8yq8nvc683v16vxr-llvm-18.1.8-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/pzbhqvfp6lxjpb816f3p4gp2nipavv75-rustc-1.80.1' from 'https://cache.nixos.org'...
copying path '/nix/store/ch5mgr7p0i47d8f7xbga2r1qdzhxqcnb-rustc-wrapper-1.80.1' from 'https://cache.nixos.org'...
% rustc --version                                      
rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball)
```

**Comment by pdeva** [comment]
this is the output when install cargo from rustup outside of nix:


```
$ which cargo
/Users/pdeva/.cargo/bin/cargo

$ cargo version
cargo 1.80.1 (376290515 2024-07-16)

```

**Pull request merged**
