### PR TITLE
wpsoffice: 10.1.0.5672 -> 11.1.0.8865

### PR DESCRIPTION
**Pull request by Ninlives**
###### Motivation for this change

update wpsoffice to latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dguibert @fpletz 
Are you still insterested in maintaining this package?

### CODE REVIEW

**Comment by Ninlives** [comment]
cc @dguibert @fpletz

**Comment by Ninlives** [comment]
@GrahamcOfBorg build wpsoffice

**Comment by FRidh** [comment]
@Ninlives would you like to be the maintainer of this package? It seems its without a maintainer currently.

**Comment by FRidh** [comment]
Please squash your commits.

**Comment by Ninlives** [comment]
@FRidh I'd love to. What do you mean "squash" the commits? Merge them into one single commit? Sorry I'm not familiar with the pull request process.

**Comment by Mic92** [comment]
@Ninlives Yes, squashing makes one commit out of many. You can also just add yourself as a maintainer in the `meta` attribute set and I can squash on merge through the github interface.

**Comment by Ninlives** [comment]
Hi @FRidh @Mic92 , I think I figured it out, please correct me if I made any mistakes.

**Comment by FRidh** [comment]
In the future, don't merge master. Instead, squash and rebase.

**Comment by Mic92** [comment]
I squashed when merging.

**Pull request merged**
