### PR TITLE
dockerTools: Fix streamLayeredImage for symlinks

### LINKED ISSUE #107021: buildLayeredImage has surprising behaviour wrt. symlink paths on different backends
**Describe the bug**
Please see https://github.com/NixOS/nixpkgs/issues/107021#issuecomment-753984110 for a more thorough investigation than this.

~I'm not sure I'd really classify this as a bug, but it is a least surprising behaviour on some docker storage backends, so I'd like to document this. I'm not sure whether docker really has any formal semantics with respect to the loading process.~

The TL;DR: Some `buildLayeredImage`s may be usable on some storage backends but not on others when symlinked paths are involved.

**To Reproduce**

Consider:

```
let
  nixpkgs = builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/e9158eca70ae59e73fae23be5d13d3fa0cfc78b4.tar.gz";
  pkgs = import nixpkgs { config = {}; overlays = []; };

  real = pkgs.writeTextDir "dir/real" "contents";
  symlink = pkgs.runCommandNoCC "symlink" {} ''
    ln -s ${real} $out
  '';
in
pkgs.dockerTools.buildLayeredImage {
  name = "symlink-image";
  contents = [symlink];
}
```

This image fails to load on an ext4/overlayfs setup:

```
49ebdedff0c8: Loading layer [==================================================>]  10.24kB/10.24kB
e12f90c968f3: Loading layer [==================================================>]  10.24kB/10.24kB
Error processing tar file(exit status 1): mkdir /nix/store/58f4852rq2517gayjdc8lnvr6chklsgc-symlink/dir: no such file or directory
```

But succeeds on a zfs-backed docker setup:
```
49ebdedff0c8: Loading layer [==================================================>]  10.24kB/10.24kB
e12f90c968f3: Loading layer [==================================================>]  10.24kB/10.24kB
20125547c15a: Loading layer [==================================================>]  10.24kB/10.24kB
Loaded image: symlink-image:yf3llawsrlqky9cnmpv29hkyys368329
```

I imagine this is because of the storage backend's behaviour wrt. earlier layers' files.

**Expected behavior**
Image loads the same on all backends.

**Additional context**

This was discovered because our docker images became unpullable on some hosts (overlay) but not others (zfs) after crate2nix started using symlinks for tested builds: https://github.com/kolloch/crate2nix/pull/143

@andir might find this interesting. :smile_cat:

### PR DESCRIPTION
**Pull request by srhb**
When archiving `/nix/store/foo` and `foo` is itself a symlink, we must
not traverse the symlink target, but archive the `foo` symlink itself

I think this is sufficient to fix #107021 but I don't know a lot about the streaming mechanics here.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg test docker-tools

**Comment by roberth** [comment]
Could you turn your example from the issue into a regression test?
Those are in `nixos/tests/docker-tools.nix`. You can add the image to `pkgs/build-support/docker/examples.nix` (or a new file for regression test images if you like).

The fix seems to make sense, but I'd appreciate a review by @utdemir.

**Comment by srhb** [comment]
@GrahamcOfBorg test docker-tools

**Comment by roberth** [comment]
@GrahamcOfBorg test docker-tools

**Review by utdemir — APPROVED** [review]
It does look good to me, given the tests pass. And I appreciate the test case.

**Comment by roberth** [comment]
Great! Thank you @srhb and @utdemir!

**Comment by purcell** [comment]
Nice, thanks for this fix! 🏆

**Comment by yurrriq** [comment]
Thank you!

**Pull request merged**
