### PR TITLE
re2c: 3.1 -> 4.0.1

### PR DESCRIPTION
**Pull request by trofi**
Changes:
- https://re2c.org/releases/release_notes.html#release-4-0
- https://re2c.org/releases/release_notes.html#release-4-0-1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jopejoe1 — APPROVED** [review]

**Comment by Izorkin** [comment]
Is it possible to add version 3.1?
Not all applications support version 4.x:
```
genfiles: re2c version 4.0.1 (ok)
genfiles: Generating Zend parser and lexer files
Zend/zend_language_scanner.l:1794:19: warning: escape has no effect: '\*' [-Wuseless-escape]
Zend/zend_language_scanner.l:1798:19: warning: escape has no effect: '\*' [-Wuseless-escape]
bison -l  -v -d Zend/zend_ini_parser.y -o Zend/zend_ini_parser.c
Zend/zend_ini_scanner.l:379:13: warning: escape has no effect: '\.' [-Wuseless-escape]
Zend/zend_ini_scanner.l:379:32: warning: escape has no effect: '\.' [-Wuseless-escape]
Zend/zend_ini_scanner.l:386:27: warning: escape has no effect: '\[' [-Wuseless-escape]
Zend/zend_ini_scanner.l:387:11: warning: escape has no effect: '\[' [-Wuseless-escape]
Zend/zend_ini_scanner.l:654:7: warning: unreachable rule in condition 'INITIAL' (shadowed by rules at lines 401, 476, 486, 557, 633, 638, 643) [-Wunreachable-rules]
Zend/zend_ini_scanner.l:629:50: warning: unreachable rule in condition 'ST_OFFSET' (shadowed by rule at line 575) [-Wunreachable-rules]
Zend/zend_ini_scanner.l:629:50: warning: unreachable rule in condition 'ST_SECTION_VALUE' (shadowed by rule at line 575) [-Wunreachable-rules]
Zend/zend_ini_scanner.l:654:7: warning: unreachable rule in condition 'ST_VALUE' (shadowed by rules at lines 543, 549, 553, 561, 565, 571, 579, 629, 649) [-Wunreachable-rules]
Zend/zend_ini_scanner.l:654:7: warning: unreachable rule in condition 'ST_DOUBLE_QUOTES' (shadowed by rules at lines 584, 589) [-Wunreachable-rules]
Zend/zend_ini_scanner.l:654:7: warning: unreachable rule in condition 'ST_RAW' (shadowed by rules at lines 495, 543, 649) [-Wunreachable-rules]
genfiles: Generating phpdbg parser and lexer files
sapi/phpdbg/phpdbg_lexer.l:80:20: warning: escape has no effect: '\.' [-Wuseless-escape]
sapi/phpdbg/phpdbg_lexer.l:64:0: warning: control flow in condition 'NORMAL' is undefined for strings that match
        '\x22 [\x0\xA]'
        '\x27 [\x0\xA]'
        '\x22 \x22 [\x0\x9-\xA\xD\x20\x23]'
...
```

**Comment by trofi** [comment]
`4.0` Has no incompatible changes compared to `3.1` (/cc @skvadrik to keep me honest).

The only change is a bunch of warnings that were enabled by default. And at a glance the warnings look legitimate and don't seem to report build failures.

Do you see the build failures in` nixpkgs` (or anywhere else)? Which attributes are unhappy?

**Comment by skvadrik** [comment]
> /cc @skvadrik to keep me honest

Confirmed, it's [this change](https://github.com/skvadrik/re2c/commit/87a031fc85ad182a944193ad8579a8ae86912b1b) in re2c that enabled the warnings. They are all worth fixing, as they indicate potential bugs and security issues (especially `-Wundefined-control-flow` which is [documented here](http://re2c.org/manual/basics/warnings/warnings.html#detailed-warnings)). But if needed warnings can be disabled with `-Wno-...`. To verify my words you can run with the previous re2c version passing `-W` option, you should see the same warnings.

**Comment by skvadrik** [comment]
> To verify my words you can run with the previous re2c version passing -W option, you should see the same warnings.

I just checked it myself on [this file](https://github.com/php/php-src/blob/b8ee4c2b19bb6c79b6e6e8f46dc95aedb2a73655/sapi/phpdbg/phpdbg_lexer.l#L4) from the warning message above and I confirm that re2c-4.0.2 and re2c-3.1 with `-W` produce the same output. Looking at the source code, it's a bug in php that should be reported (if not, the generated code may have undefined behavior on some inputs). I'm happy to help fixing it, but I believe further analysis belongs on the php bugtracker.

**Comment by skvadrik** [comment]
I filed https://github.com/php/php-src/issues/17523

**Comment by Izorkin** [comment]
Ok, I thought something was broken.

**Pull request merged**
