### PR TITLE
python3Packages.python-nmap: init at 0.6.4

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
python-nmap is a Python library which helps in using nmap port scanner. It
allows to easily manipulate nmap scan results and will be a perfect tool
for systems administrators who want to automatize scanning task and reports.
It also supports nmap script outputs.

http://xael.org/pages/python-nmap-en.html

Related to #81418 and a Home Assistant dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 115202` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>python37Packages.python-nmap</li>
    <li>python38Packages.python-nmap</li>
    <li>python39Packages.python-nmap</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115202` at 3a1edb71 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/5b4f1ff64c50c8a8bff41f6993e4e67d">python37Packages.python-nmap</a></li></li>
    <li><a href="https://gist.github.com/12651e76dc994b04bc03ebb84994237c">python38Packages.python-nmap</a></li></li>
    <li><a href="https://gist.github.com/59fca1810a4a075e88a85f5636a2079e">python39Packages.python-nmap</a></li></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
```
hash mismatch in fixed-output derivation '/nix/store/a71acnfpyr28ma9fk6darnl1qkbml98a-python-nmap-0.6.4.tar.gz.drv':
  specified: sha256-7EO0YPj94vrtv6bWY+9JWz/WnfhVoTXuvo+KdBwN3mA=
     got:    sha256-XUvO0CTKXe/FdTG+D8p7+BWKmcMw9CNzNU6ndtIReAQ=
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 115202` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.python-nmap</li>
    <li>python38Packages.python-nmap</li>
    <li>python39Packages.python-nmap</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Thanks, @SuperSandro2000

**Pull request merged**
