### PR TITLE
Add support for Rust / Cargo packaging

### PR DESCRIPTION
**Pull request by wizeman**
As I mentioned in a comment in #4568, I continued working on Rust packaging starting from where @madjar left off.

This took me a lot longer and it was a lot harder and hackier than I thought. It's not in a completely finished and polished state, but at least it seems to work now. It allows Nix to build cargo'ed Rust programs with a minimum of fuss, including `cargo` itself, and it should work in a deterministic way.

Note that the `fetch-cargo-deps` script is probably not very robust yet with respect to git checkouts.
Specifically, I have not tested building a Rust program that has a git dependency whose repository has submodules (I would be surprised if this worked without some additional fixes). If anyone has an example of such a program, please let me know and I will fix the script.

As @madjar had mentioned, it would be nice to add a `nix-prefetch-cargo` script and documentation, but even in this state I think it would already be useful to anyone who wants to build Rust programs.

A big thanks to @madjar for his initial work!

### CODE REVIEW

**Comment by jagajaga** [comment]
Looks cool! Going to look deeper later. Thank you!

**Comment by madjar** [comment]
Awesome, thanks for the hard work! There's indeed some very hackish things in there, but that's good enough for now :)

We'll also need to add a paragraph in the documentation about how to package a rust package. I think we should invoke some nixpkgs guru for review, since this is very big.

By the way, what do you think about dropping the rust snapshot after 1.0 is released?

**Comment by wizeman** [comment]
@madjar Which rust snapshot do you mean? I thought that the `rustc` snapshot is needed to build `rustc` itself (in the same way that `cargoSnapshot` is needed to build `cargo`). So I don't see how we can drop it?

**Comment by wizeman** [comment]
Note that I've just noticed that there was a bug and I've just added a fix for it. It turns out that `Cargo.lock` was actually being ignored, causing `depsSha256` to have to be changed whenever `rustRegistry` was updated. See the bug fix's commit comment for more details.

I've also found a way to get rid of the `/proc/self/cwd` hack, however it has a drawback: it depends on a few more internal details of how `cargo` works (specifically, it will require exact knowledge of how `cargo` hashes the registry index URL, and also a couple more details about the directory structure that `cargo fetch` creates).

However, the major benefit is that it would make `buildRustPackage` work on platforms other than Linux, due to getting rid of this platform-specific hack.

I assume this is a worthwhile tradeoff, so if nobody objects I will start working on it tomorrow.

**Comment by madjar** [comment]
@wizeman Oh, sorry, I meant the rustcMaster.

What upstream change would be required to make it cleaner ?

**Comment by wizeman** [comment]
@madjar I think we shouldn't delete `rustcMaster`, as it will be required for people who want to test the `master` release channel (also, at the moment some packages still depend on `rustcMaster`: `racerRust` and `cargo`, and I'm not sure if they will support the stable channel before 1.0 is released).

Regarding making this cleaner, I opened rust-lang/cargo#1334 a few months ago, but it was closed and I was told to simply rely on `cargo fetch`...

**Comment by wizeman** [comment]
Ok, I've fixed a new bug that I found, where the local registry was being ignored because cargo sometimes doesn't seem to like repositories downloaded by `fetchgit`, instead giving out an error that it wasn't able to update.

I'm not sure why this happens sometimes, I've tried to look into it a bit but I just don't know much about git internals and I wasn't looking forward to start digging into the `libgit2` code. After I spent quite some time trying to find a workaround, I found out that if I locally create a new, from scratch, copy of the repository downloaded with `fetchgit`, it will work fine, so even though this is suboptimal, at least it works reliably for now. Hopefully in the future `cargo`/`libgit2` will get fixed and we'll just be able to use `fetchgit` directly.

On the other hand, I finally got rid of the `/proc/self/cwd` hack and I'm quite happy with the results. This means that `buildRustPackage` is now portable to non-Linux architectures.

I also did a few cleanups and I added a bunch of comments explaining what is being done, especially in the `fetch-cargo-deps` script.

Since I was on a roll, I also factored out the patching of the `pkg-config` registry dependency into a more general patching facility, so that in the future we have a global place where we can easily patch dependencies (instead of duplicating all of these patches in each derivation of a Rust program).

**Comment by wmertens** [comment]
Very nice!

Question though, did you involve any Rustaceans in your struggles with
cargo? I'd think they'd be interested in helping with this effort...

**Comment by wizeman** [comment]
> Question though, did you involve any Rustaceans in your struggles with
cargo? I'd think they'd be interested in helping with this effort...

I opened cargo issue 1330 and was then told to open another issue (cargo issue 1334), but in the end there didn't seem to be any interest in what I was proposing...

At this point I'm not even sure what I'd like to propose anymore. Although I'm tempted to want a more traditional approach to packaging Rust libraries, such as what we do for other languages, their suggested use of `cargo fetch` also has its advantages, such as less maintenance burden for distro packagers and more guaranteed compatibility between Rust libraries and Rust programs.

The only major worry I have with the way cargo bundles Rust libraries is the way cargo / rustc wants to statically link almost all library dependencies.

Specifically, I am concerned about the difficulty of ensuring we are not shipping any Rust program with a statically linked library with known security vulnerabilities.

But I'm also thinking that assuming most Rust programs will depend on libraries that are in the `crates.io` registry, it shouldn't be too hard to check that we are not shipping any vulnerable libraries. Especially given that all libraries in the registry are versioned, we could just maintain a registry of security-vulnerable library versions, and during the build of a package we just make sure that "cargo fetch" didn't download any of these vulnerable versions...

It would be more difficult to do this for git-based dependencies, though...

**Comment by jagajaga** [comment]
When are you going to merge this?

**Comment by wizeman** [comment]
Merged.

**Comment by madjar** [comment]
Congratulations!

**Pull request merged**
