### PR TITLE
ccache: update `sha256` to fix hash mismatch

### LINKED ISSUE #316520: Build failure: cacche (aarch64-darwin)
### Steps To Reproduce

Build failure after https://github.com/NixOS/nixpkgs/pull/315714

```
$ nix build github:NixOS/nixpkgs#ccache
error: hash mismatch in fixed-output derivation '/nix/store/slqin5zn20zdhsciqw33bp7g4yhk27m0-source.drv':
         specified: sha256-0T9iJXnDX8LffhB/5hsfBNyZQ211f0lL/7dvTrjmiE0=
            got:    sha256-YHSr2pnk17QEdrIHInXX2eBFN9OGjdleaB41VLaqlnA=
error: 1 dependencies of derivation '/nix/store/gp3rhhflvqj9gsiwnpj1r46zxq0zy0sr-ccache-4.10.drv' failed to build
```

### Build log

```
these 2 derivations will be built:
  /nix/store/gpb62wdf1kp9irnpzfdkhv30xskj7rgf-source.drv
  /nix/store/gp3rhhflvqj9gsiwnpj1r46zxq0zy0sr-ccache-4.10.drv
building '/nix/store/slqin5zn20zdhsciqw33bp7g4yhk27m0-source.drv'...
source> trying https://github.com/ccache/ccache/archive/refs/tags/v4.10.tar.gz
source>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
source>                                  Dload  Upload   Total   Spent    Left  Speed
source>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
source> 100  564k  100  564k    0     0   449k      0  0:00:01  0:00:01 --:--:--  646k
source> unpacking source archive /private/tmp/nix-build-source.drv-0/v4.10.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/slqin5zn20zdhsciqw33bp7g4yhk27m0-source.drv':
         specified: sha256-0T9iJXnDX8LffhB/5hsfBNyZQ211f0lL/7dvTrjmiE0=
            got:    sha256-YHSr2pnk17QEdrIHInXX2eBFN9OGjdleaB41VLaqlnA=
error: 1 dependencies of derivation '/nix/store/gp3rhhflvqj9gsiwnpj1r46zxq0zy0sr-ccache-4.10.drv' failed to build
```

### Additional context

Hoping this isn't another darwin "case sensitivity" issue.

### Notify maintainers

From the PR:
@Nanotwerp
@kira-bruneau 

From ccache:

@kira-bruneau
@r-burns

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.4`
 - channels(n8henrie): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/x44yrfrlx00rsbab7lqc5f71qwjazb56-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Nanotwerp**
## Description of changes
Fixes #316520, an issue introduced by #315714. The `4.10` release of `ccache` was re-tagged, leading to a hash change. This commit replaces the hash from `sha256-0T9iJXnDX8LffhB/5hsfBNyZQ211f0lL/7dvTrjmiE0=` to `sha256-YHSr2pnk17QEdrIHInXX2eBFN9OGjdleaB41VLaqlnA=`. Additionally, the `sha256` parameter of the `fetchFromGitHub` function is replaced by `hash`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kira-bruneau** [comment]
Thanks @Nanotwerp! Yeah... it looks like they re-tagged the release 🥲 - here's the diff:

```diff
diff -r /nix/store/s4yv141wgygcdwnxbz11gisw0wi4kca0-source/cmake/CcacheVersion.cmake /nix/store/k29cgldbyz3sr4hzagz1353hq3mynkjz-source/cmake/CcacheVersion.cmake
25c25
< set(version_info "7e31d0591eee51723266b24b29c111a089cc7958 HEAD -> master, tag: v4.10")
---
> set(version_info "7e31d0591eee51723266b24b29c111a089cc7958 tag: v4.10")
```

**Review by kira-bruneau — APPROVED** [review]

**Comment by n8henrie** [comment]
Result of `nixpkgs-review pr 316524` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>redpanda-server</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>ccache</li>
    <li>ccache.man</li>
    <li>ccacheStdenv</li>
    <li>ccacheWrapper</li>
    <li>monophony</li>
    <li>python311Packages.nuitka</li>
    <li>python311Packages.nuitka.dist</li>
    <li>python312Packages.nuitka</li>
    <li>python312Packages.nuitka.dist</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> The `4.10` release of `ccache` was re-tagged

No, this is due to `git archive` replacing https://github.com/ccache/ccache/blob/v4.10/cmake/CcacheVersion.cmake#L25.
Fixed by https://github.com/NixOS/nixpkgs/pull/316558.

**Comment by Nanotwerp** [comment]
Closing. Superseded by #316558.

**Pull request closed without merging**
