### PR TITLE
plasma5: 5.14.0 -> 5.14.3

### PR DESCRIPTION
**Pull request by bkchr**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
[Announce](https://www.kde.org/announcements/plasma-5.14.2.php) and [full changelog](https://www.kde.org/announcements/plasma-5.14.1-5.14.2-changelog.php)

**Comment by cocreature** [comment]
FWIW, plasma 5.14.3 has been released today: [announcement](https://www.kde.org/announcements/plasma-5.14.3.php) and [changelog](https://www.kde.org/announcements/plasma-5.14.2-5.14.3-changelog.php). I haven’t yet attempted to build or use it on NixOS.

**Comment by bkchr** [comment]
@cocreature ty :) I updated the pull request.

**Comment by bkchr** [comment]
@ttuegel ping

**Comment by ttuegel** [comment]
Sorry for the delay! Thanks!

**Comment by bkchr** [comment]
Np :) Ty for the merge.

**Pull request merged**
