### PR TITLE
rubygems: 2.4.8 -> 2.5.2

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done:
- [x] Tested via `nix.useChroot`.
- [x] Built on platform(s): .
- [ ] Tested compilation of all pkgs that depend on this change.
- [x] Tested execution of binary products.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Closes #11950

### CODE REVIEW

**Comment by lancelotsix** [comment]
:+1:

**Comment by globin** [comment]
This broke the rake call in gitlab:
```
/nix/store/h0bzdyrwwi23j121ma3ynb7p8rm54lbf-gitlab/lib/ruby/gems/2.2.3/bin/rake: line 9: require: command not found
/nix/store/h0bzdyrwwi23j121ma3ynb7p8rm54lbf-gitlab/lib/ruby/gems/2.2.3/bin/rake: line 11: version: command not found
/nix/store/h0bzdyrwwi23j121ma3ynb7p8rm54lbf-gitlab/lib/ruby/gems/2.2.3/bin/rake: line 15: syntax error near unexpected token `('
/nix/store/h0bzdyrwwi23j121ma3ynb7p8rm54lbf-gitlab/lib/ruby/gems/2.2.3/bin/rake: line 15: `  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding'
```

I'd like to revert this? Or do you know a fix?

**Comment by zimbatm** [comment]
Feel free to revert, I'm working on something better :)

**Comment by zimbatm** [comment]
Basically I'm proposing to bundle rubygems with ruby directly, I think it will be more solid like that: #13601

**Comment by zimbatm** [comment]
Are you sure that's the issue by the way ? It looks like rake is evaluated with bash.

**Comment by globin** [comment]
Yes, reverting this commit fixed it, I don't have the time currently to look at this further.

5936d6d

**Comment by globin** [comment]
BTW, this is a case where one should really run nox-review..

**Comment by zimbatm** [comment]
Alright will do, sorry for the regression

**Comment by zimbatm** [comment]
I found the cause of the regression, the patch was somehow nilifying the shebang

**Pull request merged**
