### PR TITLE
Fix KDE packages

### PR DESCRIPTION
**Pull request by ttuegel**
See #11764.

### CODE REVIEW

**Comment by ttuegel** [comment]
I also had to fix up the dependencies for `calamares`. The build is currently failing, but there were so many missing dependencies, I'm unsure if it was broken to begin with.

**Comment by ttuegel** [comment]
I don't know why Travis still has an evaluation error related to this package, so I'm merging this anyway.

**Comment by ttuegel** [comment]
@vcunat Thanks! I couldn't find the maintainer's GitHub username.

**Comment by vcunat** [comment]
In the worst case I'm using github's search on the e-mail address, but here I remembered earlier.

**Comment by ts468** [comment]
@ttuegel I'm sorry if calamares was causing trouble. I know that it was working when I added it, but I'm not currently using it. My plan is to build a nice graphical installer for NixOS using calamares at some point. That's why I hoped we could keep it.

**Comment by vcunat** [comment]
Now the tarball builds so channel isn't blocked by that and calamares fails ATM, but I suppose that's not a significant problem.

**Comment by ttuegel** [comment]
> I know that it was working when I added it, but I'm not currently using it.

Hm, if it used to work, the problem is probably the Qt 5.4 -> Qt 5.5 upgrade. It was actually using a mixture of Qt 5.4 and Qt 5.5 before because all the KDE 5 packages are built with Qt 5.5. I'm a little surprised that didn't cause problems.

> My plan is to build a nice graphical installer for NixOS using calamares at some point.

:+1: I haven't gotten rid of it, it just needed to be moved into `kde5PackagesFun`. That ensures its dependencies are all consistent (same version of Qt, etc.).

**Comment by vcunat** [comment]
Yes, probably the Qt update &ndash; it says:
```
src/libcalamaresui/utils/YamlUtils.h:34:1: error: 'QVariant' does not name a type
```

**Comment by ts468** [comment]
Probably calamares needs an update as well. I'll do that next time someone needs it ;). Thanks for all your efforts!

**Pull request merged**
