### PR TITLE
buildPython*: propagate setuptools

### PR DESCRIPTION
**Pull request by FRidh**
This was accidentally removed in
7e28bf5d8181926e600a222cb70180519d09726. Longer-term, we should not
propagate setuptools though, and let derivations explicitly declare
whether they require setuptools during runtime.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
If we don't encounter too many runtime issues I think we can do without this change.

**Comment by worldofpeace** [comment]
Noticed that this broke `fwupd` (which breaks gnome3 tests).
It runs a script during build and we expected setuptools to be available
```
FAILED: libfwupd/fwupd.map
/build/fwupd-1.2.10/libfwupd/generate-version-script.py LIBFWUPD libfwupd/Fwupd-2.0.gir libfwupd/fwupd.map
Traceback (most recent call last):
  File "/build/fwupd-1.2.10/libfwupd/generate-version-script.py", line 11, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

Adding `setuptools` would be proper, but I'm betting this assumption could be made often.

**Comment by FRidh** [comment]
Yes, it's made more often, but I think we can still fix them on a case by case basis.

**Comment by lheckemann** [comment]
Is this a bugfix which should be backported to 19.09 as well?

**Comment by FRidh** [comment]
For now I would like to avoid merging and backporting it and fix case-by-case. If it turns out to be too much, we can merge this and backport it.

**Comment by Ma27** [comment]
While testing 19.09 I realized that `matrix-synapse` is also affected by this. So I guess it would make sense to create a PR with a fix for `matrix-synapse` against `release-19.09`?

**Comment by FRidh** [comment]
@Ma27 first master, then 19.09

**Comment by worldofpeace** [comment]
@FRidh Should upstream projects have `setuptools` in `install_requires`?

**Comment by FRidh** [comment]
@worldofpeace in my opinion they should if they have a runtime dependency on it.

Setuptools is typically available as its the first thing one installs because its used as build system for 99% of the Python packages out there. Having it as build-system does not mean it should be available as a run-time dependency, although that assumption is made as we're seeing. There isn't really a rule about this, but given that multiple build systems are now supported by upstream, this is something that needs to get attention because it would be silly to keep having these build-systems as runtime dependencies.

**Comment by worldofpeace** [comment]
> @worldofpeace in my opinion they should if they have a runtime dependency on it.
> 
> Setuptools is typically available as its the first thing one installs because its used as build system for 99% of the Python packages out there. Having it as build-system does not mean it should be available as a run-time dependency, although that assumption is made as we're seeing. There isn't really a rule about this, but given that multiple build systems are now supported by upstream, this is something that needs to get attention because it would be silly to keep having these build-systems as runtime dependencies.

Precisely, I'm thinking the same thing here. Plus we have purity so we don't just rely on things being installed.

Would it be worth making some turning points in the python packaging ecosystem? As you've said, the reality of there being multiple builds system makes this assumption on setuptools invalid.

**Comment by FRidh** [comment]
It is something I intend to bring up on https://discuss.python.org/c/packaging but I just haven't gotten to it.

**Comment by flokli** [comment]
The discussion shifted more into adding it explicitly where needed, and with 19.09 released, I assume we won't merge (and backport) this, but fix where broken - so can we close this PR?

**Comment by FRidh** [comment]
Yep, many packages have been fixed so let's close it.

**Comment by flokli** [comment]
@FRidh I still think something should be posted on discuss.python.org/c/packaging though ;-)

**Pull request closed without merging**
