### PR TITLE
pixinsight: disable hydra builds

### PR DESCRIPTION
**Pull request by superherointj**
pixinsight: disable hydra builds

### CODE REVIEW

**Comment by figsoda** [comment]
doesn't it already not build because of its license?
https://hydra.nixos.org/eval/1779991?filter=pixinsight&compare=1779931&full=#tabs-inputs

**Comment by superherointj** [comment]
> doesn't it already not build because of its license? https://hydra.nixos.org/eval/1779991?filter=pixinsight&compare=1779931&full=#tabs-inputs

`nixpkgs-review` still tries to build it. That is how I reached it.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190511` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by figsoda — APPROVED** [review]

**Comment by superherointj** [comment]
Thanks!

**Pull request merged**
