### PR TITLE
ibus-packages.mozc: pin to protobuf 3.6 (fixes build breakage at HEAD)

### PR DESCRIPTION
**Pull request by delroth**
###### Motivation for this change

https://github.com/google/mozc/issues/460

mozc currently doesn't build on trunk: https://hydra.nixos.org/build/92239027

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
cc @7c6f434c did I see you making changes relevant to this?

**Comment by 7c6f434c** [comment]
I fixed a similar but different problem: `protobufc` has unreleased upstream fix for a _different_ `protobuf` API change.

**Comment by grahamc** [comment]
@GrahamcOfBorg build ibus-packages.mozc

**Comment by grahamc** [comment]
turns out it is called:

@GrahamcOfBorg build ibus-engines.mozc

**Comment by delroth** [comment]
Thank you! 👍

**Comment by Arfrever** [comment]
> ###### Motivation for this change
> 
> [google/mozc#460](https://github.com/google/mozc/issues/460)

This would be relevant with Protobuf 3.7.0, but not with Protobuf 3.7.1.

https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.1 says:
> Avoid marking generated C++ messages as final, though we will do this in a future release

**Pull request merged**
