### PR TITLE
postgresqlPackages.pgvecto-rs: 0.3.0 -> 0.4.0

### PR DESCRIPTION
**Pull request by diogotcorreia**
https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.4.0

Switched to the new cargo fetcher as well.

cc @esclear 

I'm thinking we should wait for Immich to support this before merging tho.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by diogotcorreia** [comment]
@wolfgangwalther Should I add `pgvecto-rs_0_3_0` and `pgvecto-rs_0_4_0` as well, then?

I've also opened https://github.com/immich-app/immich/discussions/14280 to track pgvecto-rs 0.4.0 support in Immich.

**Comment by diogotcorreia** [comment]
> Did you actually test Immich with it, btw? Is it failing to build somehow?

Haven't tested it, but it is artificially limited for up to 0.3: https://github.com/immich-app/immich/blob/6ec94f94f1e7d60c83806f775a53dc598030fc32/server/src/constants.ts#L7

Their update to 0.3.0 was just bumping this number (https://github.com/immich-app/immich/pull/11624/), so hopefully it's the same for 0.4.0.
If no one takes a look there in a few days, I can try to see if it works with 0.4.0 after bumping that.

**Comment by diogotcorreia** [comment]
Upstream just re-released 0.4.0 with a new commit 😬 
I'll update the hashes later

**Comment by esclear** [comment]
Yes, that's the second re-release, actually.
Happened before, will probably happen again.

I'd give it a few more days, don't think they'll retag once more.

**Comment by diogotcorreia** [comment]
Updated the hash and ran nixfmt on the file as well (separate commit)

**Comment by happysalada** [comment]
Can you rebase when you have a moment, a PR was just merged which removes old versions of cargo pgrx.
Does this not build with latest cargo pgrx 0.12.6 ? I just hope we dont need to add and maintain another version of cargo pgrx.

**Comment by diogotcorreia** [comment]
Rebased. Removed the conditional for using `pkg-config` on Darwin since all versions are now newer than 0.12.0.

**Comment by esclear** [comment]
Looks good to me, though I can't test / recreate the Darwin-issue.

**Comment by diogotcorreia** [comment]
@wolfgangwalther I've made `openssl` a buildInput on darwin as well, and removed `darwin.apple_sdk.frameworks.Security`. Let me know if it builds or if I need to add `darwin.apple_sdk.frameworks.Security` back (the nixpkgs manual makes it seem like it doesn't do anything anymore :thinking:).

> You may see references to darwin.apple_sdk.frameworks. This is the legacy SDK pattern, and it is being phased out. All packages in darwin.apple_sdk, darwin.apple_sdk_11_0, and darwin.apple_sdk_12_3 are stubs that do nothing. If your derivation references them, you can delete them. The default SDK should be enough to build your package.
>
> Note: the new SDK pattern uses the name apple-sdk to better align with Nixpkgs naming conventions. The legacy SDK pattern uses apple_sdk. You always know you are using the old SDK pattern if the name is apple_sdk.

**Review by wolfgangwalther — APPROVED** [review]
That fixes cargo-pgrx on darwin for me, yes.

timescaledb_toolkit is still broken on darwin, but that's the same on master. In fact it's for the same reason as pgvecto-rs - because cargo-pgrx tries setup a PostgreSQL server listening on localhost in the buildPhase. That fails in the sandbox.

Fixing that is out of scope for this PR, I guess.

**Comment by Ma27** [comment]
Uh is immich already updated? I still get a failing test after having rebased onto master.

**Comment by diogotcorreia** [comment]
> We could try to patch Immich like here: [immich-app/immich#11624 (files)](https://github.com/immich-app/immich/pull/11624/files)

I'll see if it works and do that.

> Not sure which "upgrade issues" are meant here.

Possibly this: https://github.com/tensorchord/pgvecto.rs/pull/617 and https://github.com/tensorchord/pgvecto.rs/issues/616

Seems it has already been sorta fixed, but we will see

**Comment by Ma27** [comment]
cc immich maintainers @dotlambda @jvanbruegge @Scrumplex @Titaniumtown 
If there's a fix landing soon, I'd be fine with leaving that. Otherwise feel free to temporarily revert.

**Pull request merged**
