### PR TITLE
papirus-icon-theme: 20230901 -> 20231101

### PR DESCRIPTION
**Pull request by romildo**
## Description of changes

- Update to version [20231101](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/releases/tag/20231101)
- Add `withElementary` optional argument
- `papirus-icon-theme` does not include _ePapirus_ and _ePapirus-Dark_ themes anymore
- `epapirus-icon-theme` is new and includes all themes
- Remove dependence on `gnome-icon-theme`, as it is not an inherited theme anymore.
- Add update script

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kilianar** [comment]
The update itself looks good to me. The release notes advise splitting the icons into two separate packages if the distro packages the Pantheon desktop (as NixOS does):

> **For package maintainers**
> The default behavior didn't change. The Makefile still installs all the available icon themes. But we recommend two options to deal with ePapirus and ePapirus-Dark themes:
> 1. If your distro supports [Pantheon Desktop](https://en.wikipedia.org/wiki/Elementary_OS#Pantheon_desktop_environment) please split the package to `papirus-icon-theme` (Papirus, Papirus-Dark, Papirus-Light), and  `epapirus-icon-theme` (ePapirus, ePapirus-Dark).  epapirus-icon-theme should have `papirus-icon-theme` as dependency. See example for [deb package](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/635c7bc416edd41b028a328df61ffae4cf053a7c).
> 2. If your distro does **NOT** support [Pantheon Desktop](https://en.wikipedia.org/wiki/Elementary_OS#Pantheon_desktop_environment), please exclude ePapirus and ePapirus-Dark from `papirus-icon-theme` package using EXCLUDE notation: `make EXCLUDE="ePapirus ePapirus-Dark" install`.
>
> This saves up to 17309 inodes and up to 72MB of disk space for your users.

**Comment by romildo** [comment]
> The update itself looks good to me. The release notes advise splitting the icons into two separate packages if the distro packages the Pantheon desktop (as NixOS does):
> 
> > **For package maintainers**
> > The default behavior didn't change. The Makefile still installs all the available icon themes. But we recommend two options to deal with ePapirus and ePapirus-Dark themes:
> > 
> > 1. If your distro supports [Pantheon Desktop](https://en.wikipedia.org/wiki/Elementary_OS#Pantheon_desktop_environment) please split the package to `papirus-icon-theme` (Papirus, Papirus-Dark, Papirus-Light), and  `epapirus-icon-theme` (ePapirus, ePapirus-Dark).  epapirus-icon-theme should have `papirus-icon-theme` as dependency. See example for [deb package](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/635c7bc416edd41b028a328df61ffae4cf053a7c).
> > 2. If your distro does **NOT** support [Pantheon Desktop](https://en.wikipedia.org/wiki/Elementary_OS#Pantheon_desktop_environment), please exclude ePapirus and ePapirus-Dark from `papirus-icon-theme` package using EXCLUDE notation: `make EXCLUDE="ePapirus ePapirus-Dark" install`.
> > 
> > This saves up to 17309 inodes and up to 72MB of disk space for your users.

There is another alternative: add an optional argument `withElementary` (default: false) to the package to decide whether to install or not the elementary set of papirus icons, and add a new entry `epapirus-icon-theme` in `all-packages.nix` with this argument enabled. It is simpler (because we would still have only one simple package to maintain) and it would work well, in my opinion.

@kilianar  What do you think?

**Comment by kilianar** [comment]
I believe following the upstream recommendation to create a package excluding Pantheon-specific icons is worthwhile. The 70MB saved on disk space seems rather significant. Splitting the icons into two packages, utilizing an optinal argument as you explained, appears to be a viable and likely easier-to-maintain solution for nixpkgs.

**Review by kilianar — COMMENTED** [review]
Result of `nixpkgs-review pr 264845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>deepin.deepin-icon-theme</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>catppuccin-papirus-folders</li>
    <li>epapirus-icon-theme</li>
    <li>papirus-icon-theme</li>
    <li>papirus-maia-icon-theme</li>
    <li>papirus-nord</li>
  </ul>
</details>

`deepin.deepin-icon-theme` currently builds successfully on the master branch. However, attempting to build it with the changes in this PR results in the following error:
```
gtk-update-icon-cache: Failed to open file /nix/store/xm0c8fg4x9lcr6pbhg7zyx295br2dxv0-deepin-icon-theme-2023.04.03/share/icons/hicolor/.icon-theme.cache : Permission denied
/nix/store/ppy5gm6r676chda5ig5xgbhr8sb3rfap-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
```

**Comment by romildo** [comment]
> `deepin.deepin-icon-theme` currently builds successfully on the master branch. However, attempting to build it with the changes in this PR results in the following error:
> 
> ```
> gtk-update-icon-cache: Failed to open file /nix/store/xm0c8fg4x9lcr6pbhg7zyx295br2dxv0-deepin-icon-theme-2023.04.03/share/icons/hicolor/.icon-theme.cache : Permission denied
> /nix/store/ppy5gm6r676chda5ig5xgbhr8sb3rfap-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
> ```

`deepin-icon-themes` should not update the icon cache of all icon themes in `$out/share/icons/` after the fix up phase, because at this moment the directories of the parent themes have already been linked there, and they are not writable. So it fails to update the cache of the hicolor icon theme. hicolor is just being added as a parent theme of papirus, which is a parent theme of some of the deepin icon themes.

**Comment by romildo** [comment]
Result of `nixpkgs-review pr 264845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>catppuccin-papirus-folders</li>
    <li>deepin.deepin-icon-theme</li>
    <li>epapirus-icon-theme</li>
    <li>mame</li>
    <li>mame-tools (mame-tools.tools ,mame.tools)</li>
    <li>papirus-icon-theme</li>
    <li>papirus-maia-icon-theme</li>
    <li>papirus-nord</li>
  </ul>
</details>

**Review by kilianar — APPROVED** [review]
Thank you for addressing the issue concerning `deepin.deepin-icon-theme`.

**Pull request merged**
