### PR TITLE
replay-sorcery: init at 0.5.0

### PR DESCRIPTION
**Pull request by kira-bruneau**
###### Motivation for this change
ReplaySorcery is an optional dependency of GOverlay (See #121422) and would be nice to have to record instant replays.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 123045` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>replay-sorcery</li>
  </ul>
</details>

**Comment by legendofmiracles** [comment]
Is it normal for replay-sorcery to have such high CPU usage? I don't remember it being that high on arch.
image

**Comment by MetaDark** [comment]
> Is it normal for replay-sorcery to have such high CPU usage? I don't remember it being that high on arch.

Did you try setting your `audioDevice` to `system`? There's an upstream issue for high CPU in both replay-sorcery & pulseaudio: https://github.com/matanui159/ReplaySorcery/issues/94.

With that change replay-sorcery on my machine drops from ~66% CPU usage to ~2% and pipewire-pulse drops from ~60% to 0%.

> Also, wouldn't it make sense to have a settings option in the module, for modifying the config file?

Yep, that makes sense. I'll add one.

**Review by legendofmiracles — APPROVED** [review]
Thank you so much, for packaging this - You're awesome!

**Comment by kira-bruneau** [comment]
Rebased to use my updated maintainer name: https://github.com/NixOS/nixpkgs/pull/124035

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 123045` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>replay-sorcery</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Changes look good

Builds, starts

not tested the module, but others seem to have

thanks!

**Pull request merged**
