### PR TITLE
pkgs/tools: switch to fetchFromGitHub part 2

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
use fetchFromGitHub

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Could you please replace hash with sha256? Thanks, some scripts fail to updated when no specific hash is declared for example nix-update and nixpkgs-update.

**Comment by Stunkymonkey** [comment]
`sha256` is already deprecated and replaced by `hash`.
i wrote an shell-script to automatically recalculate the hashes.

i perfectly understand why you want the `sha256`.
On the other hand i am not feeling well by being slowed down by software that it is not dependent on. Ideally the software should be updated. if i see it correctly `nix-update` supports it already: [structure](https://github.com/Mic92/nix-update/blob/b167cc623191bc8bb1afbc7f3ab5ac0a039f70dd/nix_update/eval.py#L28), [calculating hashes](https://github.com/Mic92/nix-update/blob/b167cc623191bc8bb1afbc7f3ab5ac0a039f70dd/nix_update/update.py#L54)

**Comment by figsoda** [comment]
> `sha256` is already deprecated and replaced by `hash`.

do you have a link to this?

**Comment by Stunkymonkey** [comment]
> do you have a link to this?

[`An alternative – and supposedly preferred – way of specifying hashes are so-called "SRI hashes".`](https://nixos.wiki/wiki/Nix_Hash)
Sorry I miss-read that. Only preferred. So I can also calculate the sha256. Should i do that for all of them? or just a few?

**Comment by figsoda** [comment]
most people use `sha256` as the attribute name and both sri and the normal form are used in nixpkgs
I don't think we will default to or widely adopt sha512 any time soon, so there isn't much of a downside to just change all the `hash`s to `sha256`s which everything is used to
you don't need to change the hash, `sha256` also accepts the sri form

**Pull request merged**
