### PR TITLE
mesa: 24.0.3 -> 24.0.4

### LINKED ISSUE #301843: Update request: mesa 24.0.3 → 24.0.4
- Package name: mesa
- Latest released version: [24.0.4](https://docs.mesa3d.org/relnotes/24.0.4.html)

- Current version on the unstable channel: 24.0.3
- Current version on the stable/release channel: 23.1.9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@vcunat @primeos 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes
Update mesa: 24.0.3 -> 24.0.4

Remove backport-radeon-crash-fix.patch added in commit 3ecdb722ea76a3b72d375218c93d8a98dd48f75b since [merged into upstream](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28240). 
Closes https://github.com/NixOS/nixpkgs/issues/301843

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Hi, thanks for the contribution. As per the [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#branch-conventions), changes that cause mass rebuilds should go to staging.

Please note the potential issue of mass pings, and the way to rebase that avoids it:
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

Additionally, I'm not sure if there's some other prerequisites given that this is `mesa`, tagging @K900 in case

**Comment by K900** [comment]
The patch can be removed from git, and the PR needs to be retargeted to staging. Otherwise looks OK.

**Comment by K900** [comment]
You need to actually rebase your branch on top of staging and remove the unnecessary commits.

**Comment by JohnRTitor** [comment]
Fixed it. Thanks :D

**Comment by K900** [comment]
@ofborg build mesa

**Comment by LunNova** [comment]
@ofborg build pkgsi686Linux.mesa

**Comment by LunNova** [comment]
Result of `nixpkgs-review pr 301941` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>mesa</li>
    <li>mesa-demos</li>
    <li>mesa.debug</li>
    <li>mesa.dev</li>
    <li>mesa.drivers</li>
    <li>mesa.driversdev</li>
    <li>mesa.opencl</li>
    <li>mesa.osmesa</li>
    <li>mesa.spirv2dxil</li>
    <li>mesa_i686</li>
    <li>mesa_i686.debug</li>
    <li>mesa_i686.dev</li>
    <li>mesa_i686.drivers</li>
    <li>mesa_i686.driversdev</li>
    <li>mesa_i686.osmesa</li>
    <li>mesa_i686.spirv2dxil</li>
  </ul>
</details>

**Review by LunNova — APPROVED** [review]

**Comment by Mic92** [comment]
Mhm. This broke aarch64 cross compilation for me. Haven't tested if it also affects native compilation.

**Comment by Mic92** [comment]
Ok. Clearly a cross-compilation issue:

```
$ file ./mesa-24.0.4/build/src/nouveau/compiler/libnak_ir_proc.so
./mesa-24.0.4/build/src/nouveau/compiler/libnak_ir_proc.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

**Comment by Mic92** [comment]
Upstream issue. Also happens in mesa master.

**Comment by vcunat** [comment]
So, I don't know... keep cross on 24.0.3 for now?

**Comment by Mic92** [comment]
It was actually a bug in meson that triggers in mesa. Here is a fix: https://github.com/NixOS/nixpkgs/pull/299031/commits/e3f6f5742facac13428354c6fca13abac32738e1 will make it a PR.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/302769

**Pull request merged**
