### PR TITLE
nvidia_x11: 390.151 → 390.154, 470.129.06 → 470.141.03, 515.57 → 515.65.01

### PR DESCRIPTION
**Pull request by Kiskae**
###### Description of changes

[Linux, Solaris, and FreeBSD driver 515.65.01 [production branch release]](https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-515-65-01-production-branch-release/222722)
[Linux, Solaris, and FreeBSD driver 470.141.03 [legacy for GKxxx “Kepler” GPUs]](https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-470-141-03-legacy-for-gkxxx-kepler-gpus/222727)
> No release notes for 390.154, appears to be a partial kernel compatibility update

###### Things done

Marked 390 as broken on newer kernels again. The old patches appear to have been partially implemented, but the removed `pci_set_dma_mask` calls are still present, breaking the patches but not actually fixing the build.
Pinging @superherointj since he recently added the patches.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
As kernel has been updated to 5.19, the patch for 5.19 has to be added too:

https://gitlab.com/herecura/packages/nvidia-390xx-dkms/-/raw/herecura/kernel-5.19.patch

It should be straightforward. Did you test that?

**Comment by Kiskae** [comment]
I checked those patches against the source code in the blob. They are all either already fixed through conftest, or the patch no longer applies cleanly, requiring an update before they would work.

The `5.19` patch specifically has been fixed through the `NV_DMA_RESV_ADD_FENCE_PRESENT` conftest.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 184980` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_18_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy390</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy470</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy390</li>
    <li>linuxPackages_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy390</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bumblebee</li>
    <li>linuxPackages_latest-libre.nvidia_x11 (linuxKernel.packages.linux_latest_libre.nvidia_x11)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470)</li>
  </ul>
</details>
<details>
  <summary>65 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>geekbench (geekbench5)</li>
    <li>geekbench4</li>
    <li>gl-gsync-demo</li>
    <li>gwe</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages.nvidia_x11 (linuxKernel.packages.linux_5_15.nvidia_x11)</li>
    <li>linuxPackages.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy390)</li>
    <li>linuxPackages.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy470)</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_5_15_hardened.nvidia_x11)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy390 (linuxPackages_5_15_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy470 (linuxPackages_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11 (linuxKernel.packages.linux_5_18_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_18_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_5_19.nvidia_x11)</li>
    <li>linuxPackages_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_19.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages-libre.nvidia_x11 (linuxKernel.packages.linux_libre.nvidia_x11)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod.nvidia_x11 (linuxKernel.packages.linux_xanmod.nvidia_x11)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>mangohud</li>
    <li>monitor</li>
    <li>nvfancontrol</li>
    <li>primus</li>
    <li>psensor</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 184980` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_18_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy390</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy470</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy390</li>
    <li>linuxPackages_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy390</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bumblebee</li>
    <li>linuxPackages_latest-libre.nvidia_x11 (linuxKernel.packages.linux_latest_libre.nvidia_x11)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470)</li>
  </ul>
</details>
<details>
  <summary>65 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>geekbench (geekbench5)</li>
    <li>geekbench4</li>
    <li>gl-gsync-demo</li>
    <li>gwe</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages.nvidia_x11 (linuxKernel.packages.linux_5_15.nvidia_x11)</li>
    <li>linuxPackages.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy390)</li>
    <li>linuxPackages.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy470)</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_5_15_hardened.nvidia_x11)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy390 (linuxPackages_5_15_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy470 (linuxPackages_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11 (linuxKernel.packages.linux_5_18_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_18_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_5_19.nvidia_x11)</li>
    <li>linuxPackages_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_19.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages-libre.nvidia_x11 (linuxKernel.packages.linux_libre.nvidia_x11)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod.nvidia_x11 (linuxKernel.packages.linux_xanmod.nvidia_x11)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>mangohud</li>
    <li>monitor</li>
    <li>nvfancontrol</li>
    <li>primus</li>
    <li>psensor</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>

**Comment by superherointj** [comment]
bumblebee: mark broken
#185045

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 184980` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages marked as broken and skipped:</summary>
  <ul>
    <li>bumblebee</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_18_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy390</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy470</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy390</li>
    <li>linuxPackages_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy390</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_latest-libre.nvidia_x11 (linuxKernel.packages.linux_latest_libre.nvidia_x11)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470)</li>
  </ul>
</details>
<details>
  <summary>65 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>geekbench (geekbench5)</li>
    <li>geekbench4</li>
    <li>gl-gsync-demo</li>
    <li>gwe</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages.nvidia_x11 (linuxKernel.packages.linux_5_15.nvidia_x11)</li>
    <li>linuxPackages.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy390)</li>
    <li>linuxPackages.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy470)</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_5_15_hardened.nvidia_x11)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy390 (linuxPackages_5_15_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy470 (linuxPackages_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_18.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11 (linuxKernel.packages.linux_5_18_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_18_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_18_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_5_19.nvidia_x11)</li>
    <li>linuxPackages_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_19.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages-libre.nvidia_x11 (linuxKernel.packages.linux_libre.nvidia_x11)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod.nvidia_x11 (linuxKernel.packages.linux_xanmod.nvidia_x11)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod_tt.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_tt.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>mangohud</li>
    <li>monitor</li>
    <li>nvfancontrol</li>
    <li>primus</li>
    <li>psensor</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Comment by Yorwba** [comment]
Should this be backported to `release-22.05` like #173859 was? 

The 470.129.06 driver fails to compile on kernel 5.19 (latest in `release-22.05`), complaining about `dma_resv_add_excl_fence` and suggesting `nv_dma_resv_add_excl_fence` instead. That sounds related to the [comment above](https://github.com/NixOS/nixpkgs/pull/184980#issuecomment-1203725753) about the `NV_DMA_RESV_ADD_FENCE_PRESENT` conftest.

**Comment by Kiskae** [comment]
Looks like `nixpkgs/nixos-22.05#linuxKernels.packages.linux_5_19.nvidia_x11_legacy470` is indeed broken. @thiagokokada triggered a backport on the previous PR so maybe he can have a look?

**Pull request merged**
