### PR TITLE
qtile: 0.19.0 -> 0.20.0

### PR DESCRIPTION
**Pull request by jyooru**
###### Motivation for this change
https://github.com/qtile/qtile/releases/tag/v0.20.0
https://github.com/qtile/qtile/compare/v0.19.0...v0.20.0

https://github.com/flacjacket/pywlroots/compare/v0.14.12...v0.15.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jyooru** [comment]
Tested and works, I am typing this comment from qtile 0.20.0

**Review by chvp — CHANGES_REQUESTED** [review]
I was trying to bump this last night as well, unfortunately the wayland backend does not work (at least not for me). I was going to look into it some more today.

**Comment by jyooru** [comment]
Oh, I completely forgot about qtile's support for wayland! I have not used qtile with wayland before, so I'm not sure how to go about fixing that.

I'm going to close this so you can open another PR.

**Comment by jonringer** [comment]
if qtile wayland wasn't currently working, then I don't see this a regression. Can always bump first, then add wayland later.

**Comment by jonringer** [comment]
If it is a regression, then please @chvp open a pr

**Comment by chvp** [comment]
It is working currently (with version 0.19). I'll open a draft PR, but will not have time until later today.

**Pull request closed without merging**
