### PR TITLE
sonobuoy: 0.16.1 -> 0.19.1

### PR DESCRIPTION
**Pull request by wilsonehusin**
###### Motivation for this change
- Updating Sonobuoy to the latest version
    - Sonobuoy adopted Go modules and therefore this needs to be built with `buildGoModule`
    - Updated repository path as well, referring `vmware-tanzu` instead of `heptio` ([context captured here](https://github.com/NixOS/nixpkgs/pull/70904#issuecomment-557298005))
- Adding myself to maintainer for this package

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notice to other maintainers
cc: @carlosdagos @saschagrunert 

This is my first time contributing to `nixpkgs`. Happy to assist more to ease this update, though if it's anything of the above I'd like to have some references 😃

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by endocrimes** [comment]
Result of `nixpkgs-review pr 100537` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sonobuoy</li>
  </ul>
</details>

**Review by endocrimes — APPROVED** [review]
Welcome to nixos ✨ - LGTM!

**Review by saschagrunert — APPROVED** [review]

**Comment by marsam** [comment]
Thank you for your contribution, and hope to see you again soon!

**Pull request merged**
