### PR TITLE
nixos/tor: fix systemd service

### PR DESCRIPTION
**Pull request by oxij**
Kindly contributed fix to what #39083 apparently broke when fixing what #37827 broke.

- [X] Tested by the original author.
- [X] Tested by me in NixOS VM with control socked and hidden services enabled. It works.

@dotlambda, can you verify it works with your config? Let's try really hard not to break anything this time.

### CODE REVIEW

**Comment by dotlambda** [comment]
I think we should instead run the systemd service as the `tor` user instead of letting Tor switch to that user itself. This also what Arch does: https://git.archlinux.org/svntogit/community.git/tree/trunk/tor.service?h=packages/tor. Do you think that's possible?
The only problem I see is that sometimes people configure bridges to listen on 443 in order to hide the fact they are running a Tor relay. We might have to give the service additional capabilities.

**Comment by oxij** [comment]
> possible?

Probably not, unless you are willing to patch systemd. AFAICS, according to systemd.service(5) and other mentioned manuals, systemd provides no options for specifying file modes for those directories and this patchset sets different modes for different purposes (it makes total sense to hide tor state and onion private keys from prying eyes).

It also has an advantages of being simple, of using standard tools only, and hence of being easily portable between init systems unlike those systemd-specific options (NixOS doesn't care about that latter point, but still).

**Comment by joachifm** [comment]
If the separate service thing works that seems fine to me ... Depending on how tor does its privsep, it *may* even be preferrable to let it do its thing anyway.

An alternative is to set `User`, `RuntimeDirectory`, `StateDirectory` and use `StateDirectoryMode` to restrict visibility into that dir. Or use tmpfiles or something.

**Comment by joachifm** [comment]
Makes sense to me to just merge this & maybe iterate later. Thank you.

**Pull request merged**
