### PR TITLE
Add hypothesis 3.1

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform(s): NixOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

Because updating hypothesis from 1.14.0 to 3.1 is not that easy (see https://github.com/NixOS/nixpkgs/pull/13835), I'm trying a different path here: rename current hypothesis to hypothesis1, change all derivations depending on hypothesis to now depend on `hypothesis1`, add hypothesis 3.1 under the name `hypothesis`.

cc @lancelotsix @domenkozar @FRidh 

---

_Please note, that points are not mandatory, but rather desired._

### CODE REVIEW

**Comment by FRidh** [comment]
Often it is nicer to have one package, `hypothesis`, referring to one of the versions `hypothesis = hypothesis_3` e.g. Anyway, this is fine. Thanks.

Could you add `doCheck = false;` with a note that tests are not included in the archive. It has happened now a couple of times that tests could not be found and the default test runner would break.

**Comment by DamienCassou** [comment]
@FRidh There is already a `doCheck=false` in hypothesis 1.14. I had no test problem in 3.1 so I don't see why I should disable tests there. Could you please tell me a bit more?

**Comment by FRidh** [comment]
@DamienCassou The tests don't fail because the tests are not included in the archive :)

In the last setuptools update there has been a change in how setuptools behaves when calling `python setup.py test`. Often upstream wants us to test explicitly with either `py.test` or `nosetests` instead of using `python setup.py test`. We do this by overriding the checkPhase. This is often forgotten though by contributors. When `setup.py` doesn't mention a test suite runner, then since this setuptools update, it will always run unittest. Before, it would just silently pass (!!).

This is great, because it helps us find cases where we invoke the test runner incorrectly. However, sometimes tests still silently pass with `python setup.py test`. But there have also been cases where errors occurred...

I think it is good to be explicit about the test runner and whether tests work. When it says, `doCheck = False;`, then you know the package is not tested. When it is not `False`, then it might mean it passes tests but you still do not know because of the before mentioned 'bugs'

**Comment by DamienCassou** [comment]
@FRidh I read hypothesis packaging instructions and updated the derivation accordingly. I still have to check everything is fine, but you can already give feedback if you have some.

**Comment by DamienCassou** [comment]
This one seems to be ok. Any feedback?

**Pull request merged**
