### PR TITLE
treewide: mpd_clientlib -> libmpdclient

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
There are a lot of unrelated changes in the treewide commit which make this really hard to review. I would prefer it if the treewide commit only changed the package and the formatting and cleanups would be one commit per packages.

Also treewide changes should be ideally 0 rebuilds.

**Comment by Mic92** [comment]
I can review it anyway.

**Comment by AndersonTorres** [comment]
The rebuilds are maybe because the ordering changes a bit. But the results are essentially the same.

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 112774` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ario</li>
    <li>gjay</li>
    <li>mpdscribble</li>
    <li>polybarFull</li>
  </ul>
</details>

**Pull request merged**
