### PR TITLE
Temporary disable qtile-extras' strava widget tests

### LINKED ISSUE #271610: Build failure: python311Packages.qtile-extras on `nixpkgs/nixos-23.11`
Hello,

I wanted to switch to NixOS 23.11, but this build failure prevented it. I found a workaround (cf *Additional context*), but I am not sure it is very clean (it does not follow what is documented on [search.nixos.org](https://search.nixos.org/options?channel=23.11&show=services.xserver.windowManager.qtile.extraPackages&from=0&size=50&sort=relevance&type=packages&query=services.xserver.windowManager.qtile.extraPackages) and I am quite new to NixOs).

Note: Finally I will not use `qtile-extra` but since I couldn't found help about this problem I wanted to create this issue, it may help other people in the future.

Best regards,
JD

### Steps To Reproduce

Add `qtile-extra` to qtile as explained in the option's documentation: (cf. [services.xserver.windowManager.qtile.extraPackages](https://search.nixos.org/options?channel=23.11&show=services.xserver.windowManager.qtile.extraPackages&from=0&size=50&sort=relevance&type=packages&query=services.xserver.windowManager.qtile.extraPackages)) with `nixpkgs` targeting `nixos-23.11`.

In `configuration.nix`:
```
services.xserver.windowManager.qtile = {
      enable = true;
      backend = "x11";
      extraPackages = python3Packages: with python3Packages; [
        qtile-extras
      ];
};
```

In `flake.nix`:
```
nixpkgs.url = "nixpkgs/nixos-23.11";
```

`flake.lock`:

```
    "nixpkgs": {
      "locked": {
        "lastModified": 1660551188,
        "narHash": "sha256-a1LARMMYQ8DPx1BgoI/UN4bXe12hhZkCNqdxNi6uS0g=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "441dc5d512153039f19ef198e662e4f3dbb9fd65",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

### Build log

```
error: builder for '/nix/store/5v8k9bis2nqkwnskmb8j52pjjba37ccn-python3.11-qtile-extras-0.23.0.drv' failed with exit code 2;
       last 10 log lines:
       > test/widget/test_image.py:134
       >   /build/source/test/widget/test_image.py:134: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
       >     @pytest.mark.flaky(reruns=5)
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > ERROR test/widget/test_strava.py - AttributeError: type object 'Activity' has no attribute 'RUN'
       > !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
       > ================= 125 deselected, 5 warnings, 1 error in 1.93s =================
       > /nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux/setup: line 1559: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/5v8k9bis2nqkwnskmb8j52pjjba37ccn-python3.11-qtile-extras-0.23.0.drv'.
```

### Additional context

I tryed to work around this problem and found a solution:

It works when doing in `configuration.nix`:

```
let
  qtile-extras-bis = pkgs.python310Packages.qtile-extras;
in
...
services.xserver.windowManager.qtile = {
      enable = true;
      backend = "x11";
      extraPackages = python3Packages: with python3Packages; [
        qtile-extras-bis
      ];
};
```

### Notify maintainers

@arjan-s 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.05 (Stoat), 23.05.20231124.1216a5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by kirikaza**
## Description of changes

Fixes #271610 by temporarily disabling tests for Strava widget in qtile-extras.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
this package looks broken. it has disabled tests that cause assertion errors and disabling more tests does not seem like the proper way to move forward. an issue should be filed upstream about this current strava error.

**Comment by kirikaza** [comment]
@TomaSajt yes, of course I can squash them. But anyway the PR has that red cross "No channel PR / This PR is is targeting a channel branch (pull_request)" though the target branch is "release-*". And I don't know what to do with it.

@a-n-n-a-l-e-e My intention is to fix a broken package in the stable (23.11) asap. Except for the strava widget, everything else (i.e. other widgets) work well for me. Surely we need to bump the issue to the upstream developers but I don't know how long it can take.

**Comment by TomaSajt** [comment]
I think you should be targeting master, then create an (automatic) backport to 23.11. See more about this in CONTRIBUTING.md.

**Comment by arjan-s** [comment]
Hi, thank you for looking into this! I'll take care of the upstream issue, but it would be great if this could get merged and backported in the mean time. I can confirm that this does fix the build problem for now.
So if you could update the PR to follow the contributing guidelines that would be great!

**Comment by arjan-s** [comment]
@kirikaza are you still willing to work on this? The build is still failing and your PR fixes it. If you could rebase to master and squash your commits, that would be great!

**Comment by wegank** [comment]
As NixOS 23.11 reaches end-of-life today, this PR is closed as part of the [EOL cleanup](https://nixos.github.io/release-wiki/EOL-Cleanup.html).

**Pull request closed without merging**
