### PR TITLE
chkservice: remove

### PR DESCRIPTION
**Pull request by GetPsyched**
## Description of changes

Was doing treewide changes to nixpkgs and found that this package doesn't even exist on GitHub anymore: https://github.com/linuxenko/chkservice

### CODE REVIEW

**Comment by GetPsyched** [comment]
cc @infinisil (package maintainer)

**Comment by infinisil** [comment]
Cc @layus who originally contributed it, but yeah if upstream is gone I don't think there's a reason to keep it around

**Comment by layus** [comment]
Fine by me, we packaged it as part of a nix-hour project, and figured we might as well upstream it.

**Comment by layus** [comment]
Thanks BTW :-)

**Pull request merged**
