### PR TITLE
nixos/hostapd: remove managementFrameProtection in favour of clearer default

### PR DESCRIPTION
**Pull request by tomfitzhenry**
## Description of changes

This PR removes the option `services.hostapd.radios.<name>.networks.<name>.managementFrameProtection` (MFP), and instead unconditionally sets `ieee80211w=1` (optional) and [`sae_require_mfp=1`](https://w1.fi/cgit/hostap/tree/hostapd/hostapd.conf?id=2d4be0019d9236923d5fe9eac1f7e69c484d5d27#n2060), which requires MFP if SAE is used, and makes MFP optional if WPA2-SHA256 is used.

Motivation for this PR:
* My initial motivation with this PR is that I noticed that even with the [documented legacy profile](https://github.com/NixOS/nixpkgs/blob/8b1ce3a5716fd761f6f1d1f9c647a28fd619732b/nixos/modules/services/networking/hostapd.nix#L155-L164), my Lenovo Thinkpad x230 was unable to connect to the wifi. Setting `managementFrameProtection` to optional allowed my Thinkpad x230 to connect, but it took a lot of debugging to discover that.
* This module has many options, which reflects the complexity of 802.11 and hostapd, but for the sake of simplicity, if we spot an option that we can reasonably remove before 23.11 is released, we should take that. It's much easier to remove this now, and add later if needed, rather than remove it once 23.11 has been released. *When in doubt, leave it out*, [as Joshua Bloch says about API design](https://www.youtube.com/watch?v=aAb7hSCtvGw&t=1476s). :)

Overall, I think this preserves the "secure out-the-box" profile, and offers an easy "legacy" profile, all while exposing a simpler API, with escape hatches (`settings`) for unusual cases if needed.

It's entirely possible I'm missing some subtlety?

@oddlama , thoughts? :)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by oddlama — CHANGES_REQUESTED** [review]
I agree that this is probably a good change, I can't see any downsides doing it that way right now. Although this should definitely get a `mkRemovedOptionModule` to not break existing configs.

**Review by rnhmjoj — APPROVED** [review]
Seems reasonable to me.

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
@ofborg test hostapd

**Comment by rnhmjoj** [comment]
Oof, It's quite tricky because the usual functions do not work. You can use `warnings` to emulate the behavior, like:
```nix
{
    warnings =
      builtins.filter (x: x != null) (
        flip mapAttrsToList cfg.users (name: user:
          if user.passwordFile != null then
            ''The option `users.users."${name}".passwordFile' has been renamed to `users.users."${name}".hashedPasswordFile'.''
          else null)
      );
}
```

**Comment by rnhmjoj** [comment]
It's fine by me.

**Review by oddlama — APPROVED** [review]

**Comment by gauravjuvekar** [comment]
This seems to have broken wpa2 on a raspberry pi 4. 

This config is supposed to work as wpa2-psk (personal)
```
  age.secrets."hostapd_wpa_password".file = ./secrets/hostapd_wpa_password.age;
  services.hostapd.enable = true;
  services.hostapd.radios."wlan0" =
    {
      band = "2g";
      countryCode = "US";
      channel = 7;
      networks."wlan0" =
        {
          ssid = "gaurav-iot";
          authentication =
            {
              mode = "wpa2-sha256";
              wpaPasswordFile = config.age.secrets."hostapd_wpa_password".path;
            };
        };
      wifi4.capabilities = [ "SHORT-GI-20" ];
    };
```

It is detected as an enterprise network in Android with commit 9e7c877de75835018551bbd3029ac4d83f3e31cc

image


With commit 9f7335d44912c5af97e7dc01caba7c6340442f82
image

**Comment by gauravjuvekar** [comment]
Explicitly setting `settings.ieee80211w = "2";` fixes it.

**Comment by ghostbuster91** [comment]
I have raspberry PI 5 and it cannot connect to a nixos router with the current defaults with `WPA-PSK-SHA256`. Forcing `management frame protection (MFP)` by setting `ieee80211w=2` fixes the issue.

**Pull request merged**
