### PR TITLE
python3Packages.ducc0: 0.24.0 -> 0.25.0

### PR DESCRIPTION
**Pull request by phiadaarr**
* python3Packages.ducc0: 0.24.0 -> 0.25.0

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 189100` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.ducc0</li>
    <li>python39Packages.ducc0</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Please fix commit message.

Should have been: `python3Packages.ducc0: 0.24.0 -> 0.25.0`

https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes

**Comment by phiadaarr** [comment]
> Please fix commit message.
> 
> Should have been: `python3Packages.ducc0: 0.24.0 -> 0.25.0`
> 
> https://nixos.org/manual/nixpkgs/unstable/#chap-submitting-changes

Thanks for the heads up!

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 189100` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.ducc0</li>
    <li>python39Packages.ducc0</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Pull request merged**
