### PR TITLE
tor-browser-bundle-bin: 11.0.6 -> 11.0.7

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

Package update (**security**, bugfixes): https://blog.torproject.org/new-release-tor-browser-1107/

> This version includes important security updates to Firefox:
> * https://www.mozilla.org/en-US/security/advisories/mfsa2022-09/
> * https://www.mozilla.org/en-US/security/advisories/mfsa2022-11/
> 
> Tor Browser 11.0.7 updates Firefox on Windows, macOS, and Linux to 91.7.0esr.

Please backport to release-21.11 after merging.

###### Things done

I could not build the i686 version due to a dependency failing.

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
  ```
  1 package updated:
  tor-browser-bundle-bin (11.0.6 → 11.0.7)
  ```
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by panicgh** [comment]
Ping @offlinehacker (maintainer) @lourkeur (reviewer during last update 11.0.4 -> 11.0.6)

**Review by bbjubjub2494 — APPROVED** [review]
LGTM on x86_64

As far as i686 is concerned it's this pre-existing `graphene-hardened-malloc` thing right? I built `legacyPackages.i686-linux.tor-browser-bundle-bin.src` and it's good to go. That meets my requirements.

**Comment by panicgh** [comment]
> As far as i686 is concerned it's this pre-existing `graphene-hardened-malloc` thing right?

right, the error I get is:

```console
nixpkgs$ NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build -A pkgsi686Linux.tor-browser-bundle-bin --max-jobs 1
...
building '/nix/store/j012kzk5knv9vancc81zc7dlgmianb6j-graphene-hardened-malloc-8.drv'...
unpacking sources
unpacking source archive /nix/store/iin4i1895pnmskskz7gi6kni3pacpmb3-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/m28cfj32dsshg5sn9xxnqblykmi1zfnf-bash-5.1-p12/bin/bash
gcc  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt -fstack-clash-protection -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -Werror -march=native -Wmissing-prototypes  -D_GNU_SOURCE -I include -DCONFIG_SEAL_METADATA=false -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=256 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o chacha.o chacha.c
In file included from chacha.h:4,
                 from chacha.c:5:
util.h:39:18: error: '__int128' is not supported on this target
   39 | typedef unsigned __int128 u128;
      |                  ^~~~~~~~
make: *** [<builtin>: chacha.o] Error 1
error: builder for '/nix/store/j012kzk5knv9vancc81zc7dlgmianb6j-graphene-hardened-malloc-8.drv' failed with exit code 2;
       last 10 log lines:
       > no configure script, doing nothing
       > building
       > build flags: SHELL=/nix/store/m28cfj32dsshg5sn9xxnqblykmi1zfnf-bash-5.1-p12/bin/bash
       > gcc  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt -fstack-clash-protection -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -Werror -march=native -Wmissing-prototypes  -D_GNU_SOURCE -I include -DCONFIG_SEAL_METADATA=false -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=256 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o chacha.o chacha.c
       > In file included from chacha.h:4,
       >                  from chacha.c:5:
       > util.h:39:18: error: '__int128' is not supported on this target
       >    39 | typedef unsigned __int128 u128;
       >       |                  ^~~~~~~~
       > make: *** [<builtin>: chacha.o] Error 1
       For full logs, run 'nix log /nix/store/j012kzk5knv9vancc81zc7dlgmianb6j-graphene-hardened-malloc-8.drv'.
error: 1 dependencies of derivation '/nix/store/z6pnrbk191kyc6qhvb66baa03w1lbpfz-tor-browser-bundle-bin-11.0.7.drv' failed to build
```

This is correct as there simply isn't `__int128` on 32-bit. Not sure what to do about it though.

> I built `legacyPackages.i686-linux.tor-browser-bundle-bin.src` and it's good to go.

Correct, I did:

```console
nixpkgs$ nix-build -A pkgsi686Linux.tor-browser-bundle-bin.src
/nix/store/dmlqja99pf5qmh9g56v2054gh1s8v1vp-tor-browser-linux32-11.0.7_en-US.tar.xz
```

@lourkeur If you can, maybe it would be good to also add the security label.

**Comment by panicgh** [comment]
https://blog.torproject.org/new-release-tor-browser-1107/:
> This version includes important security updates to Firefox:
> * https://www.mozilla.org/en-US/security/advisories/mfsa2022-09/
> * https://www.mozilla.org/en-US/security/advisories/mfsa2022-11/
> 
> Tor Browser 11.0.7 updates Firefox on Windows, macOS, and Linux to 91.7.0esr.

@mweinelt: #163194 related

**Pull request merged**
