### PR TITLE
phpfpm: do not run anything as root

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Work phpfpm in rootless mode.

Services who use php-fpm:
- [x] roundcube
- [x] zoneminder
- [x] icingaweb2
- [x] limesurvey
- [x] matomo
- [x] nextcloud
- [x] restya-board
- [x] selfoss
- [x] tt-rss

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
cc @aanderse @Mic92

**Comment by aanderse** [comment]
@Izorkin there are many modules using `phpfpm` I suggest a checklist might be worth making.

**Comment by Izorkin** [comment]
сс @etu

**Comment by etu** [comment]
I've been testing through bits and bobs and yeah, I can't seem to find any breakage. So I think we should pull it in and hope that people report errors if something breaks.

**Comment by aanderse** [comment]
@Izorkin I'm having a few issues with this module now.

Also, I don't recall why the socket location was changed from `/run/phpfpm/` to `/run/phpfpm-${name}`. This is a breaking change and I can't seem to remember the justification for it at the moment. Something to do with permissions?

**Comment by Izorkin** [comment]
> Also, I don't recall why the socket location was changed from `/run/phpfpm/` to `/run/phpfpm-${name}`. This is a breaking change and I can't seem to remember the justification for it at the moment. Something to do with permissions?

To prevent the user "user1" View the contents of the folder / run / phpfpm-example-php73.
Example:
```
sudo ls -lah /run | grep phpfpm
drwxr-x---  2 user1   user1    60 июн 27 22:05 phpfpm-example-php72
drwxr-x---  2 user2   user2    60 июн 27 22:05 phpfpm-example-php73

sudo ls -lah /run/phpfpm-example-php72

drwxr-x---  2 user1   user1    60 июн 27 22:05 .
drwxr-xr-x 22 root    root    620 июн 28 13:28 ..
srw-------  1 user1   user1     0 июн 27 22:05 php72.sock.sock

sudo ls -lah /run/phpfpm-example-php73

drwxr-x---  2 user2   user2    60 июн 27 22:05 .
drwxr-xr-x 22 root    root    620 июн 28 13:28 ..
srw-------  1 user2   user2     0 июн 27 22:05 php73.sock.sock
```

**Comment by Izorkin** [comment]
@aanderse cheked with `RuntimeDirectory = "phpfpm";` and runnig two php-fpm service. Found this error on the second service:

```
php-fpm[712]: [ERROR] unable to bind listening socket for address '/run/phpfpm/php72.sock': Permission denied (13)
php-fpm[712]: [ERROR] FPM initialization failed
php-fpm[712]: [ERROR] unable to bind listening socket for address '/run/phpfpm/php72.sock': Permission denied (13)
php-fpm[712]: [ERROR] FPM initialization failed
```
Full access is granted to the first user.

**Pull request merged**
