### PR TITLE
nixos/modules/system/boot/stage-1.nix: Add support for mounting files encrypted with luks

### PR DESCRIPTION
**Pull request by adrianparvino**
###### Motivation for this change
My use-case is for LiveCDs to have their /nix/store squashfs encrypted using LUKS
See: https://github.com/adrianparvino/NixOSEncryptedLiveCD/blob/e076c58762b334906fee14e3de85c0eb7c82b151/nixos/modules/installer/cd-dvd/iso-image.nix#L515-L520

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
related #54494

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by ivan** [comment]
For the author, reviewers, and committers: this PR was scanned and appears to add a use of the deprecated `types.string`, which emits a warning as of #66346. Before merging, please change this to another type, possibly:

- `types.str` for a single string where merging does not make sense, or cannot work
- `types.lines` for multi-line configuration or scripts where merging is possible
- `types.listOf types.str` for a mergeable list of strings

**Comment by Lassulus** [comment]
closing this, since its very old and has a bunch of conflicts so it probably needs to be re-implemented anyway.

**Pull request closed without merging**
