### PR TITLE
gnome-online-accounts: use wrapGAppsHook instead of own fixup

### LINKED ISSUE #15531: gnome online accounts segfaults when adding my google account
steps:
1. open online accounts
2. add google account
3. enter credentials
4. verify and allow

result:
- google account not listed
- google token stored in password store
- gnome setting app no longer starts (this one is completely surprising)

dmesg output:

```
[224235.429990] audit_printk_skb: 39 callbacks suppressed
[224235.429993] audit: type=1131 audit(1463552940.709:649): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=nscd comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[224235.447545] audit: type=1130 audit(1463552940.727:650): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=nscd comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[224242.780792] traps: pool[16268] trap int3 ip:7f93c6c61ec3 sp:7f93beffc780 error:0
[224242.780807] audit: type=1701 audit(1463552948.330:651): auid=1001 uid=1001 gid=100 ses=9 pid=16268 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[224245.871687] audit: type=1131 audit(1463552951.420:652): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[224265.581491] rejected connection: IN=enp0s25 OUT= MAC=54:ee:75:5a:2f:cb:24:b6:57:9a:f1:44:08:00 SRC=10.10.161.32 DST=10.32.64.238 LEN=60 TOS=0x00 PREC=0x00 TTL=58 ID=22123 DF PROTO=TCP SPT=44287 DPT=113 WINDOW=5840 RES=0x00 SYN URGP=0 
[224268.581167] rejected connection: IN=enp0s25 OUT= MAC=54:ee:75:5a:2f:cb:24:b6:57:9a:f1:44:08:00 SRC=10.10.161.32 DST=10.32.64.238 LEN=60 TOS=0x00 PREC=0x00 TTL=58 ID=22124 DF PROTO=TCP SPT=44287 DPT=113 WINDOW=5840 RES=0x00 SYN URGP=0 
[224274.581344] rejected connection: IN=enp0s25 OUT= MAC=54:ee:75:5a:2f:cb:24:b6:57:9a:f1:44:08:00 SRC=10.10.161.32 DST=10.32.64.238 LEN=60 TOS=0x00 PREC=0x00 TTL=58 ID=22125 DF PROTO=TCP SPT=44287 DPT=113 WINDOW=5840 RES=0x00 SYN URGP=0 
[225710.084761] audit: type=1130 audit(1463554415.562:653): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=cups-browsed comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[227388.338658] audit: type=1130 audit(1463556093.732:654): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[227399.036138] audit: type=1131 audit(1463556104.429:655): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[231775.296196] usb 3-9.3: USB disconnect, device number 30
[232520.162787] traps: bijiben-shell-s[23483] trap int3 ip:7f71466ebec3 sp:7fff519f1e50 error:0
[232520.162804] audit: type=1701 audit(1463561225.306:656): auid=1001 uid=1001 gid=100 ses=9 pid=23483 comm="bijiben-shell-s" exe="/nix/store/lsj30gfpwzj3abrd7ydiyvskgrvx57jx-bijiben-3.18.2/libexec/bijiben-shell-search-provider" sig=5
[232520.244008] traps: pool[23571] trap int3 ip:7f8577fbeec3 sp:7f856fffc780 error:0
[232520.244021] audit: type=1701 audit(1463561225.387:657): auid=1001 uid=1001 gid=100 ses=9 pid=23571 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[232520.509015] traps: pool[23617] trap int3 ip:7fc0f8ef1ec3 sp:7fc0f0ffc780 error:0
[232520.509028] audit: type=1701 audit(1463561225.652:658): auid=1001 uid=1001 gid=100 ses=9 pid=23617 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[232520.720961] traps: pool[23639] trap int3 ip:7f2416e0eec3 sp:7f240effc780 error:0
[232520.720973] audit: type=1701 audit(1463561225.864:659): auid=1001 uid=1001 gid=100 ses=9 pid=23639 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[232522.353523] traps: bijiben-shell-s[23662] trap int3 ip:7fcc0df43ec3 sp:7fff36df4360 error:0
[232525.945287] audit_printk_skb: 23 callbacks suppressed
[232525.945291] audit: type=1325 audit(1463561231.088:666): table=filter family=2 entries=0
[232525.945306] audit: type=1325 audit(1463561231.088:666): table=filter family=10 entries=0
[232525.945315] audit: type=1325 audit(1463561231.088:666): table=raw family=2 entries=0
[232525.945323] audit: type=1325 audit(1463561231.088:666): table=raw family=10 entries=0
[232525.945414] audit: type=1325 audit(1463561231.088:666): table=nat family=2 entries=0
[232525.945426] audit: type=1325 audit(1463561231.088:666): table=mangle family=2 entries=0
[232525.945585] audit: type=1300 audit(1463561231.088:666): arch=c000003e syscall=272 success=yes exit=0 a0=40000000 a1=7ffe2c148680 a2=fffffffffffffff5 a3=7f33415c7690 items=0 ppid=1 pid=23860 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="(ostnamed)" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" key=(null)
[232525.945592] audit: type=1327 audit(1463561231.088:666): proctitle="(ostnamed)"
[232525.978526] audit: type=1130 audit(1463561231.122:667): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[232556.069221] audit: type=1131 audit(1463561261.211:668): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/nix/store/cr6p4x3x4z2sdyd8pfmgymjbv8wpazia-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[237422.422052] traps: bijiben-shell-s[26933] trap int3 ip:7fafa2a10ec3 sp:7fff719ae1a0 error:0
[237422.422070] audit: type=1701 audit(1463566127.329:669): auid=1001 uid=1001 gid=100 ses=9 pid=26933 comm="bijiben-shell-s" exe="/nix/store/lsj30gfpwzj3abrd7ydiyvskgrvx57jx-bijiben-3.18.2/libexec/bijiben-shell-search-provider" sig=5
[237422.545414] traps: pool[27015] trap int3 ip:7f4d4fd2eec3 sp:7f4d47ffc780 error:0
[237422.545429] audit: type=1701 audit(1463566127.452:670): auid=1001 uid=1001 gid=100 ses=9 pid=27015 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[237422.683913] traps: bijiben-shell-s[27046] trap int3 ip:7fb8f4b45ec3 sp:7ffd2bb8b8a0 error:0
[237422.683931] audit: type=1701 audit(1463566127.591:671): auid=1001 uid=1001 gid=100 ses=9 pid=27046 comm="bijiben-shell-s" exe="/nix/store/lsj30gfpwzj3abrd7ydiyvskgrvx57jx-bijiben-3.18.2/libexec/bijiben-shell-search-provider" sig=5
[237422.769288] traps: pool[27074] trap int3 ip:7f99851a4ec3 sp:7f997d3fc780 error:0
[237422.769302] audit: type=1701 audit(1463566127.676:672): auid=1001 uid=1001 gid=100 ses=9 pid=27074 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[237422.972525] traps: pool[27097] trap int3 ip:7f059cb87ec3 sp:7f0594bfc780 error:0
[237425.232782] NOHZ: local_softirq_pending 82
[237425.232902] NOHZ: local_softirq_pending 82
[237427.581583] do_trap: 27 callbacks suppressed
[237427.581587] traps: bijiben-shell-s[27272] trap int3 ip:7fe50bfa1ec3 sp:7ffdfabcb4d0 error:0
[237427.581603] audit: type=1701 audit(1463566132.488:680): auid=1001 uid=1001 gid=100 ses=9 pid=27272 comm="bijiben-shell-s" exe="/nix/store/lsj30gfpwzj3abrd7ydiyvskgrvx57jx-bijiben-3.18.2/libexec/bijiben-shell-search-provider" sig=5
[237427.662610] traps: pool[27303] trap int3 ip:7f80381a0ec3 sp:7f802bffd780 error:0
[237427.662624] audit: type=1701 audit(1463566132.569:681): auid=1001 uid=1001 gid=100 ses=9 pid=27303 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[237428.048497] traps: bijiben-shell-s[27316] trap int3 ip:7ffb2ef75ec3 sp:7ffc92e2bd60 error:0
[237428.048511] audit: type=1701 audit(1463566132.955:682): auid=1001 uid=1001 gid=100 ses=9 pid=27316 comm="bijiben-shell-s" exe="/nix/store/lsj30gfpwzj3abrd7ydiyvskgrvx57jx-bijiben-3.18.2/libexec/bijiben-shell-search-provider" sig=5
[237428.131979] traps: pool[27339] trap int3 ip:7f3723c9cec3 sp:7f371bffc780 error:0
[237428.131994] audit: type=1701 audit(1463566133.039:683): auid=1001 uid=1001 gid=100 ses=9 pid=27339 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
[237430.970200] traps: pool[27356] trap int3 ip:7f2ca6aa2ec3 sp:7f2c9ebfc780 error:0
[237430.970214] audit: type=1701 audit(1463566135.877:684): auid=1001 uid=1001 gid=100 ses=9 pid=27356 comm="pool" exe="/nix/store/wws7c4h7afg4g3kbmrvhmj4mllqdchgg-gnome-online-accounts-3.18.3/libexec/.goa-daemon-wrapped" sig=5
```
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
###### Motivation for this change

fix #15531 

this is my first pr on nixpkgs, please guide wrt testing
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

addresses #15531

### CODE REVIEW

**Comment by lethalman** [comment]
Looks great, thanks and welcome. Would also apply this change to gnome 3.20?

About testing, you can use your repo clone and `nixos-rebuild` against it to test it live on your machine.

**Comment by RonnyPfannschmidt** [comment]
for now i'djust like to test

would it make sense for gnome's `callPackage` to check if derivations that are indeed c packages use the common fixup hook ?

my pr isnt against master, so there is no gnome 3.20 yet, is there a preference on proceeding?

**Comment by bendlas** [comment]
Thanks for working on that issue.

The preferred route for patches is to go into master first and then be cherry-picked onto stable as appropriate (you can note this in the PR description or create a separate PR).

Best create a separate pull request against master, that will include gnome3_20 and edit the description of this PR to make clear it's intended for stable.

Regarding testing: The best course is to work based on the nixos-unstable channel branch, because that's ususally close enough to master to merge cleanly, while you still get the benefit of the binary caches.
Try `nixos-rebuild -I nixpkgs=/your/nixpkgs:nixos=/your/nixpkgs/nixos:nixos-config=/testing/configuration.nix build-vm`
The `-I` flag can also be given by setting `$NIX_PATH` in your shell env, or by `nix.nixPath` in your config.

**Comment by RonnyPfannschmidt** [comment]
will rebase and create a new pr

**Pull request closed without merging**
