### PR TITLE
add sepaxml & fints

### PR DESCRIPTION
**Pull request by elohmeier**
###### Motivation for this change
python modules sepaxml & fints missing in nixpkgs

###### Things done
added the modules, continued on https://github.com/NixOS/nixpkgs/pull/52486

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
mt-940 builds on master. Instead of disabling the tests, please rebase.

**Comment by elohmeier** [comment]
@dotlambda ok, did that!

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python3.pkgs.fints

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python3.pkgs.sepaxml

**Pull request merged**
