### PR TITLE
openmpi: split dev into separate output, reduce closure size

### PR DESCRIPTION
**Pull request by markuskowa**
## Description of changes
Follow up PR to https://github.com/NixOS/nixpkgs/pull/282034

This PR disentangles the dev outputs that rely on the whole compiler tool chain from the parts that are needed at runime.
Note that all build time related binaries, such as the compiler wrappers (e.g. mpicc) are now in the dev output.
For most packages this has little impact on the build process. One now needs to use, for example 
`"${lib.getDev mpi}/bin/mpicc"`, when referring to the full path compiler wrapper.
I did not run nixpkgs-review in full, but have checked (and fixed) numeros packages that directly depend on `mpi`.

Note, that the splitting the dev output requires some (not so nice) patching, since paths to "$dev" are hardcoded
into the libraries for multiple reasons. However, the savings in closure size are dramatic (before/after):

```
/nix/store/yqarhqaf0jcb1j67ql59f1w0dn1bp9b2-openmpi-4.1.6         10.3M  726.0M
/nix/store/m8fdzvnj5kwmp5k195125wnk8c0gzx74-openmpi-4.1.6          9.3M  176.8M
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build  hdf5-mpi scalapack python3Packages.mpi4py

**Comment by sheepforce** [comment]
@GrahamcOfBorg build haskellPackages.mpi-hs cp2k nwchem octopus python3Packages.gpaw

**Comment by sheepforce** [comment]
My nixpkgs-review is still running but there are at least some, although surprisingly few, failures. The most notable from my perspective:

  * hoomd-blue
  * gromacs
  * dbcsr

Otherwise, I'm very happy with a reduced size MPI :+1:

**Comment by markuskowa** [comment]
@sheepforce: gromacs and dbcsr are ok. The build failure of python3Packages.hoomd-blue is unrelated to MPI.

@GrahamcOfBorg build gromacsMpi dbcsr

**Comment by sheepforce** [comment]
Alright then! Can confirm when building locally now, that DBCSR and Gromacs are working. LGTM so far.

**Review by sheepforce — APPROVED** [review]

**Comment by markuskowa** [comment]
@GrahamcOfBorg test slurm

**Pull request merged**
