### PR TITLE
rclone: 1.45 -> 1.46

### PR DESCRIPTION
**Pull request by dywedir**
[changelog](https://rclone.org/changelog/#v1-46-2019-02-09)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @danielfullmer

### CODE REVIEW

**Comment by dotlambda** [comment]
I'm getting errors along the lines of
```
2019/02/09 15:50:20 ERROR : /: Dir.Stat error: couldn't list files: strconv.ParseInt: parsing "true": invalid syntax
```
when accessing a `rclone mount`ed WebDAV remote.

**Comment by danielfullmer** [comment]
@dotlambda That error looks to be addressed here: https://github.com/ncw/rclone/issues/2964 Presumably we can just use the included patch if he doesn't release a new version soon.

Other than that this PR looks fine to me. I've tested briefly with my google drive encrypted mount.

**Comment by dywedir** [comment]
@dotlambda could you please re-check?

**Review by dotlambda — APPROVED** [review]
Works perfectly!

**Pull request merged**
