### PR TITLE
python3Packages.mailman-web: prevent error from crashing eval

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
throwing an error prevents nix-review from evaluating if the package is affected

```
$ nixpkgs-review pr 78754
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/78754/head:refs/nixpkgs-review/1
$ git worktree add /home/jon/.cache/nixpkgs-review/pr-78754-3/nixpkgs f77e057cda60a3f96a4010a698ff3be311bf18c6
Preparing worktree (detached HEAD f77e057cda6)
HEAD is now at f77e057cda6 pythonPackages.pysaml2: fix tests with fixed & now-expired timestamps
$ git merge --no-commit a7b890985513cad46c7a158553890d9b52f11d87
Automatic merge went well; stopped before committing as requested
error: mailman-web requires django < 2.2
(use '--show-trace' to show detailed location information)
nix eval --json (import /nix/store/9yy1gv7az9mqxak6jsqkyppb4g1zvzl0-nixpkgs-review-2.1.1/lib/python3.7/site-packages/nixpkgs_review/nix/evalAttrs.nix /tmp/tmpbcmvt646) failed to run, /tmp/tmpbcmvt646 was stored inspection
https://github.com/NixOS/nixpkgs/pull/78754 failed to build
```

regression introduced in https://github.com/NixOS/nixpkgs/commit/2711c7477db765cabb0cad506bfb1b6f3b1e0fc2
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

```
Nothing changed
https://github.com/NixOS/nixpkgs/pull/79869
$ nix-shell /home/jon/.cache/nixpkgs-review/pr-79869/shell.nix
```

### CODE REVIEW

**Comment by jonringer** [comment]
not actually sure how this is different than buildPythonPackage:
```
if disabled
then throw "${name} not supported for interpreter ${python.executable}"
else
```

**Comment by jonringer** [comment]
actually, I think I know, the if/else in the `web.nix` doesn't actually get touched during evaluation, but rather during instantiation, which is why it's breaking the eval.

I could be wrong

**Comment by lsix** [comment]
That's odd, I actually reproduced the `disabled` implementation for that.

Anyway, if your pattern is better and nicer to the evaluation, it should be used everywhere I used mine in 2711c7477db765cabb0cad506bfb1b6f3b1e0fc2:

- `pkgs/development/python-modules/django-compat/default.nix`
- `pkgs/development/python-modules/mezzanine/default.nix`
- `servers/mail/mailman/web.nix`

**Comment by jonringer** [comment]
not sure if this is the perfect solution, but I should be able to review other packages now

**Comment by jonringer** [comment]
@lsix I did some more research, your approach was fine, i guess nixpkgs-review will be halted if master gets a commit that disables a package, and that commit isn't present in the PR branch.

**Comment by jonringer** [comment]
created an issue https://github.com/Mic92/nixpkgs-review/issues/82

**Comment by jonringer** [comment]
> not sure if this is the perfect solution, but I should be able to review other packages now

Still can't review, unless people rebase their branches

**Pull request merged**
