### PR TITLE
v8: mark vulnerable, move dependents to `nodejs.libv8`

### PR DESCRIPTION
**Pull request by LeSuisse**
## Description of changes

nixpkgs `v8` package is basically unmaintained (no upgrade in 3 years) and it appears we can move all the dependents to `nodejs.liblv8`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nixpkgs-review pr 315851` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>postgresql12JitPackages.plv8</li>
    <li>postgresql13JitPackages.plv8</li>
    <li>postgresql14JitPackages.plv8</li>
    <li>postgresql15JitPackages.plv8</li>
    <li>postgresql16JitPackages.plv8</li>
    <li>postgresqlJitPackages.plv8</li>
    <li>rubyPackages.libv8</li>
    <li>rubyPackages_3_1.libv8</li>
    <li>rubyPackages_3_2.libv8</li>
    <li>rubyPackages_3_3.libv8</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>gitlab</li>
    <li>gitlab-ee</li>
    <li>gollum</li>
    <li>jasp-desktop</li>
    <li>mailcatcher</li>
    <li>postgresql12Packages.plv8</li>
    <li>postgresql13Packages.plv8</li>
    <li>postgresql14Packages.plv8</li>
    <li>postgresqlPackages.plv8 (postgresql15Packages.plv8)</li>
    <li>postgresql16Packages.plv8</li>
    <li>rubyPackages.coffee-script (rubyPackages_3_1.coffee-script)</li>
    <li>rubyPackages.execjs (rubyPackages_3_1.execjs)</li>
    <li>rubyPackages.github-pages (rubyPackages_3_1.github-pages)</li>
    <li>rubyPackages.jekyll-coffeescript (rubyPackages_3_1.jekyll-coffeescript)</li>
    <li>rubyPackages.jekyll-webmention_io (rubyPackages_3_1.jekyll-webmention_io)</li>
    <li>rubyPackages.uglifier (rubyPackages_3_1.uglifier)</li>
    <li>rubyPackages_3_2.coffee-script</li>
    <li>rubyPackages_3_2.execjs</li>
    <li>rubyPackages_3_2.github-pages</li>
    <li>rubyPackages_3_2.jekyll-coffeescript</li>
    <li>rubyPackages_3_2.jekyll-webmention_io</li>
    <li>rubyPackages_3_2.uglifier</li>
    <li>rubyPackages_3_3.coffee-script</li>
    <li>rubyPackages_3_3.execjs</li>
    <li>rubyPackages_3_3.github-pages</li>
    <li>rubyPackages_3_3.jekyll-coffeescript</li>
    <li>rubyPackages_3_3.jekyll-webmention_io</li>
    <li>rubyPackages_3_3.uglifier</li>
    <li>zammad</li>
  </ul>
</details>

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by leona-ya — APPROVED** [review]
Seems good! Actually I'm thinking whether we should just remove the `v8` package altogether?

I also added a backport label to at least 24.05, feel free to remove in case you think that's wrong.

**Comment by LeSuisse** [comment]
> Seems good! Actually I'm thinking whether we should just remove the v8 package altogether?

It's likely what's going to happen in the long run but we can probably have a "grace period" before the definitive removal.

It leaves the door open if someone wants to step up and start maintaining the package if they have a specific use case not covered with `nodejs`/`nodejs.libv8` (yes I'm optimistic :smile: ).

> I also added a backport label to at least 24.05, feel free to remove in case you think that's wrong.

I think it's good, we don't have many other options for 24.05.

**Comment by emilylange** [comment]
Technically and theoretically we could tie `v8` and `chromium` bumps together.

Especially because `v8`'s release cycle is more or less "the latest stable v8 version is whatever chromium stable uses and ships with".

We, the current `chromium.meta.maintainers` (@networkException and I), however, are already at capacity.

So I would heavily prefer the solution with `nodejs.libv8` and simply marking `v8` and insecure and dropping it eventually :)

**Comment by LeSuisse** [comment]
Thanks for the feedback! I also believe that it is a better call to move to `nodejs.libv8` overall.

I'm going to update this PR to add myself as a maintainer `v8` so I can be notified if thing changes. To be honest my goal is either to get people involved or to drop the package before 24.11.

Maintaining Chromium and NodeJs  is already hard enough, I believe we should try to make it as simple as possible.

This includes, in my personal opinion,  not maintaining stuff requiring 1h+ build (on a quite modern build machine) with no active maintainers.

Personal note: maintainer of Chromium and NodeJS stuff you are awesome, thanks a lot for your work ♥️

**Pull request merged**
