### PR TITLE
notmuch: install ruby bindings

### PR DESCRIPTION
**Pull request by arcnmx**
###### Motivation for this change

Previously, the ruby bindings couldn't be used because they weren't actually installed into `$out`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
how does it affect closure size ? shouldn't it be disabled by default (ruby being less popular than e.g. python) ?

**Comment by arcnmx** [comment]
> how does it affect closure size ?

- withRuby: 262.6M
- without: 245M

> shouldn't it be disabled by default (ruby being less popular than e.g. python) ?

I just turned it on by default because it already being built. I don't really care that much, though another option might be to use multiple outputs?

**Comment by teto** [comment]
the difference in size is less than I expected but multiple output sounds nice. I am not the maintainer though so you may want to hear from them before doing extra-work.

**Comment by flokli** [comment]
Multiple outputs sound nice - and I'd personally also be fine if we'd do the same with the python bindings.

**Comment by arcnmx** [comment]
> Multiple outputs sound nice

That seems reasonable yeah.

> I'd personally also be fine if we'd do the same with the python bindings.

despite the package bringing in python/cffi as build inputs, AFAICT the python bindings are actually built separately and aren't part of the package $out anyway. There are two variants:
- the "classic" `pythonPackages.notmuch` from $src/bindings/python
- [notmuch2 cffi bindings](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/mailreaders/alot/notmuch.nix) from $src/bindings/python-cffi, which strangely aren't in pythonPackages (why??)

**Comment by arcnmx** [comment]
@floki / @teto any opinions on ed4ac9fc55a3875cd223a69518e03290d5038497?

**Review by teto — APPROVED** [review]

**Comment by teto** [comment]
Feel free to merge if you feel confident. Looks ok

**Pull request merged**
