### PR TITLE
nixos/dnscrypt-wrapper: use dnscrypt-proxy1

### PR DESCRIPTION
**Pull request by rnhmjoj**
##### Motivation for this change
Fix the dnscrypt-wrapper module. I didn't realise dnscrypt-proxy was completely removed from nixpkgs. This PR add it back in the attribute `dnscrypt-proxy1` and also a test for `dnscrypt-wrapper`, the blame is on me for not having written one before.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test (`nixosTests.dnscrypt-wrapper`)
- [x] Tested compilation of all pkgs that depend on this change (`dnscrypt-proxy1`)
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
@grahamcOfBorg test dnscrypt-wrapper

**Comment by emilazy** [comment]
FWIW, this was removed by @worldofpeace in #78543.

Personally, I'm not sure how I feel about re-packaging a security-sensitive codebase in a memory-unsafe language that's been abandoned by the original owner and hasn't been actively maintained since; a single flick of the scrollbar on the [forked repository](https://github.com/dyne/dnscrypt-proxy/commits/master) gets you back into commits from the original author in 2017, and at least one of the security fixes since seems to have only happened because the [original author dropped in to patch them](https://github.com/dyne/dnscrypt-proxy/pull/6), so I don't think it's a great idea to encourage using it over the new version.

It seems it's only used for [key rotation](https://github.com/NixOS/nixpkgs/blob/c8be03f8297a5f898d6d143038831db03dd1414c/nixos/modules/services/networking/dnscrypt-wrapper.nix#L55-L75); would it be difficult to port this to using dnscrypt-proxy2 instead?

**Comment by rnhmjoj** [comment]
> It seems it's only used for key rotation; would it be difficult to port this to using dnscrypt-proxy2 instead?

That's correct: it's only used to make a connection to localhost so I can't think of any security issue.

Unfortunately yes, It's no possibile to use dnscrypt-proxy2 because the function is simply not implemented. It was added at some [point](https://github.com/DNSCrypt/dnscrypt-proxy/issues/185) but reverted soon [after](https://github.com/DNSCrypt/dnscrypt-proxy/commit/519af2e5323d739b26555ff076f19a4b4c290a0a#diff-882438215b589ae5bb3f1b4ab0f2f512). Apparently the author author doesn't care about dnscrypt that much anymore.

If you are worried about users picking this up over v2 I guess I could move the attribute out of all-packages.nix.

**Comment by emilazy** [comment]
Fair enough; seeing as dnscrypt-wrapper itself is based on the dnscrypt-proxy 1.x code, I don't think it makes much difference security-wise to use it here, though it would be nice in the long run if there was a standalone tool or dnscrypt-wrapper had something upstream, rather than having to keep the package around just for key rotation. I'll let people who actually have commit access decide what they think about the maintenance burden of that, though.

**Comment by flokli** [comment]
Huuuh. I'm also not a fan of introducing a package with known security issues, even if it's just used in a localhost context.

@rnhmjoj Has there been any discussion with upstream about why https://github.com/DNSCrypt/dnscrypt-proxy/commit/519af2e5323d739b26555ff076f19a4b4c290a0a#diff-882438215b589ae5bb3f1b4ab0f2f512 has happened?

Maybe you could explain your usecase, and there's another way, instead of using an unmaintained older package version.

**Comment by emilazy** [comment]
Honestly, while packaging dnscrypt-proxy1 or not is its own decision, its codebase is probably not worth worrying about too much in the context of a dnscrypt-wrapper module, because dnscrypt-wrapper is itself a fork of the dnscrypt-proxy 1.x code that has [barely been touched in years](https://github.com/cofyc/dnscrypt-wrapper/commits/master); the fork of dnscrypt-proxy 1.x re-added in this commit [is not really any less active](https://github.com/dyne/dnscrypt-proxy/commits/master) and I wouldn't be surprised if it actually has security fixes that dnscrypt-wrapper hasn't inherited.

Personally, I think this mostly means that it might not be the greatest idea to have integration with dnscrypt-wrapper upstream, but I feel bad about responding "maybe we should just remove this" when someone has gone out of their way to fix it 😅

**Comment by rnhmjoj** [comment]
> @rnhmjoj Has there been any discussion with upstream about why DNSCrypt/dnscrypt-proxy@519af2e#diff-882438215b589ae5bb3f1b4ab0f2f512 has happened?

No, I don't think so.

> Maybe you could explain your usecase, and there's another way, instead of using an unmaintained older package version.

Yes, I could open an issue but the author expressed the `-verify` feature would better be in an external tool so it doesn't look like there's going to be one in dnscrypt-proxy 2. It's probably better to open an issue in dnscrypt-wrapper, which is directly affected.

In any case I'm pretty sure the only option is to write a tool to verify the keys. I'm probably going to write it myself but it will take time. 

> dnscrypt-wrapper is itself a fork of the dnscrypt-proxy 1.x code that has barely been touched in years; 

Yeah, the world seems to have chosen (once again) the technically messier solution (DNS over HTTP/TLS). I may be the only one still using this but given the program has not been officially deprecated and is still working I don't see why it should be removed.

I'll move the definition of dnscrypt-proxy1 out of `all-packages.nix` to make it only available to dnscrypt-wrapper.

**Comment by rnhmjoj** [comment]
- Moved dnscrypt-proxy1 inside the dnscrypt-wrapper module
- Rebased and fixed conflict
- Opened an issue at https://github.com/cofyc/dnscrypt-wrapper/issues/171

**Comment by rnhmjoj** [comment]
I'm going to merge this since we have agreed that dnscrypt-proxy1 limited to this module is not a security concern and no other solution exists.

I'll also backport the change to 20.03 since the module is broken there.

**Pull request merged**
