### PR TITLE
gstreamer: 1.14.2 -> 1.14.4

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Update gstreamer to the latest version.

###### Things done

Updated all gstreamer packages and successfully built all of them.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lopsided98** [comment]
The ofborg failure seems unrelated.

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by xeji** [comment]
@GrahamcOfBorg eval

**Comment by jtojnar** [comment]
Could you please include these three commits as well?

https://github.com/NixOS/nixpkgs/pull/45950/commits/dad2dc4c23eb6e2456aee04561114df836b738a7
https://github.com/NixOS/nixpkgs/pull/45950/commits/88fd1a5f09cfc57802c65a446a73e01f199f2825
https://github.com/NixOS/nixpkgs/pull/45950/commits/7233361cfa6fcb009dc7e4ca9f07c485e9a71e4d

**Comment by lopsided98** [comment]
@jtojnar ok, done

**Comment by jtojnar** [comment]
@GrahamcOfBorg build gst_all_1 python2.pkgs.gst-python python3.pkgs.gst-python

**Comment by jtojnar** [comment]
gst.-python does not build on Darwin due to https://github.com/NixOS/nixpkgs/issues/40599.

**Comment by jtojnar** [comment]
Thank you.

**Pull request merged**
