### PR TITLE
libcanberra: enable systemd support

### LINKED ISSUE #322774: `canberra-boot` and systemd services are missing from `libcanberra`
### Describe the bug

`canberra-boot`, which is offered by most Linux distributions where `libcanberra` is installed, is not present in NixOS. Its systemd services aren't available either. I'd like to be able to have an easy way to play sounds on boot and shutdown and this seems like the usual way to do it on other Linux distributions :grin: 

### Steps To Reproduce
1. Install `libcanberra` (whether via `nix-env`, `environment.systemPackages` option, etc)

### Expected behavior
`canberra-boot` should be available and executable.
systemd services such as `canberra-system-bootup.service`, `canberra-system-shutdown.service`, and `canberra-system-shutdown-reboot.service` should be available to enable.  

### Notify maintainers

@RossComputerGuy 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240622.a71e967`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.0`
 - nixpkgs: `/nix/store/yqy82fn77fy3rv7lpwa9m11w3a2nnqg5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Fixes #322774

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
This is fine though I think a systemd module might be better so it's easier to change things.

**Comment by eclairevoyant** [comment]
> This is fine though I think a systemd module might be better so it's easier to change things.

Don't know what that means.

> Also, this needs to go to staging.

Yeah, that's why I drafted it when I saw the rebuild labels.

**Comment by RossComputerGuy** [comment]
> > This is fine though I think a systemd module might be better so it's easier to change things.
> 
> Don't know what that means.

I meant to make a NixOS module and use it to add a systemd service.

**Comment by eclairevoyant** [comment]
All I intended with this PR was to fix the build such that the binary and systemd service files are available, which is sufficient to make the requested functionality possible. (i.e. the package can then be added to the appropriate package lists.) I don't know what libcanberra is nor really want to spend the time figuring that out, nor am I prepared to maintain a new module for it.

**Review by RossComputerGuy — APPROVED** [review]

**Comment by eclairevoyant** [comment]
Seems like CI is failing on aarch64-darwin; do you know what the unexpected EOF error means? Or is that the logger itself failing?

**Comment by RossComputerGuy** [comment]
That looks like a Nix error. Also, afaik libcanberra isn't really used outside of Linux.

**Comment by eclairevoyant** [comment]
Should I mark it broken for darwin then? Or does it build on your end?
Seems like there's some darwin-specific handling in the package expression, so I'd rather explicitly flag it broken if it is.

**Comment by RossComputerGuy** [comment]
> Should I mark it broken for darwin then? Or does it build on your end?

Haven't tested it on Darwin. Don't have time right now to boot into macOS on my machine.

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
> Seems like CI is failing on aarch64-darwin; do you know what the unexpected EOF error means? Or is that the logger itself failing?

The build has either been cancelled or the machine has died/rebooted. Your changes shouldn't influce the darwin builds.

**Pull request merged**
