### PR TITLE
earthly: remove maintainer

### LINKED ISSUE #131308: earthly: maintainer disappeared and license became unfree
### Describe the bug
https://github.com/NixOS/nixpkgs/pull/131169#issuecomment-886007895

### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by smancill**
###### Motivation for this change

Maintainer seems to be gone from GitHub. Close #131308.

###### Things done

Leave maintainers empty.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by smancill** [comment]
@davidak the bot just suggested the maintainer account. It seems it was changed from Mdsp9070 to matdsoupe.

Wouldn't that make this PR unnecessary?

**Comment by smancill** [comment]
@matdsoupe I think you should update your maintainer info.

https://github.com/NixOS/nixpkgs/blob/ad8c6f319060a28ac5e9d443d08bd0afb3cfa4f7/maintainers/maintainer-list.nix#L6865-L6874

**Comment by matdsoupe** [comment]
for sure! i will update my username info as same as my gpg key fingerprint that need to be updated too

**Comment by smancill** [comment]
Closing this, maintainer is on GitHub with a different user account.

**Comment by davidak** [comment]
@matdsoupe great that you are not gone!

**Pull request closed without merging**
