### PR TITLE
treewide: don't use spidermonkey attr

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@doronbehar I believe the versions you used weren't correct for all the couchdb stuff.

**Comment by worldofpeace** [comment]
Oh goodness I've pushed the wrong commit. Don't review yet.

**Comment by doronbehar** [comment]
Actually that's exactly what I wanted to further push now. Running ofborg checks locally right now.

**Comment by doronbehar** [comment]
I'm just about to get supper, sorry to leave you out with this and sorry for the slight mess.

**Comment by worldofpeace** [comment]
> I'm just about to get supper, sorry to leave you out with this and sorry for the slight mess.

It's okay. I'd say nixpkgs is the biggest and nicest mess there is :grin:

**Pull request merged**
