### PR TITLE
samba: resurrect cross compilation patch

### PR DESCRIPTION
**Pull request by NickCao**
## Things done
The patch was dropped in https://github.com/NixOS/nixpkgs/pull/328355, but still required for cross compilation.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
Cross build fails with:
```
error: output '/nix/store/1dvanx1bjrxqsvdvrhhrhzh03a958mkn-samba-riscv64-unknown-linux-gnu-4.20.4' is not allowed to refer to the following paths:
         /nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7
```
Investigating.

**Comment by uninsane** [comment]
consider adding a test that covers cross compilation to make it less likely the patch gets dropped again? could just be `passthru.tests.cross = pkgsCross.aarch64-multiplatform.samba`

**Review by uninsane — APPROVED** [review]

**Review by Titaniumtown — APPROVED** [review]
Thank you for this fix!

**Comment by Titaniumtown** [comment]
> Cross build fails with:
> 
> ```
> error: output '/nix/store/1dvanx1bjrxqsvdvrhhrhzh03a958mkn-samba-riscv64-unknown-linux-gnu-4.20.4' is not allowed to refer to the following paths:
>          /nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7
> ```
> 
> Investigating.

I can reproduce this issue.

**Comment by Titaniumtown** [comment]
It still shows up for me. I have no clue :p

I'm trying to build a raspi image.

**Comment by NickCao** [comment]
Maybe you are on the wrong branch/commit, please double check.

**Comment by Titaniumtown** [comment]
You were correct, works perfectly!

**Pull request merged**
