### PR TITLE
phosh: 0.22.0 -> 0.23.0

### PR DESCRIPTION
**Pull request by uninsane**
###### Description of changes

also updated phosh-mobile-settings 0.21.1 -> 0.23.1 while i'm here because they're somewhat coupled (i'm not sure how much phosh-mobile-settings assumes about the phosh installation).

also added `updateScript` to ease future updates:
 ```sh
$ nix-shell maintainers/scripts/update.nix --argstr package phosh
 ```
    
changelog: <https://gitlab.gnome.org/World/Phosh/phosh/-/blob/v0.23.0/debian/changelog>
abbreviated changelog (included inline below): <https://gitlab.gnome.org/World/Phosh/phosh/-/blob/v0.23.0/NEWS>
    
> phosh 0.23.0
> ------------
> Released December 2022
> * New lockscreen plugin for personal/emergency information
> * Allow plugins to have UI to set preferences
> * Ease creating plugin by better examples, improved helpers
>   and less duplication.
> * Switch docs to gi-docgen

###### Things done

**built (but not run) on x86, cross compiled to aarch64, and run/tested on a pinephone.**

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Result of `nixpkgs-review pr 211877` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
  </ul>
</details>

**Comment by onny** [comment]
Result of `nixpkgs-review pr 211877` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.phosh</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Comment by uninsane** [comment]
and thank *you* for the generous review! :-)

**Pull request merged**
