### PR TITLE
slack: 4.4.3 -> 4.7.0 (linux), 4.6.0 -> 4.8.0 (darwin)

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
1. Update to 4.8.0 on darwin ([Slack for Mac - Release Notes](https://slack.com/intl/en-ru/release-notes/mac))
2. Update to 4.7.0 on linux ([Slack for Linux - Release Notes](https://slack.com/intl/en-ru/release-notes/linux))
3. Fix macos download link
4. Use `undmg` hook instead of `/usr/bin/hdiutil` (undmg>=1.0.5 properly handles symlinks now, #94106)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]

**Review by srhb — CHANGES_REQUESTED** [review]
On Linux, it looks like we need more deps, libdrm and mesa it seems:

```
/nix/store/c8m5gvpb4b65pc3rfp9r9mzqxx5ws2jq-slack-4.7.0/lib/slack/slack: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory
```

**Comment by sikmir** [comment]
> On Linux, it looks like we need more deps, libdrm and mesa it seems:
> 
> ```
> /nix/store/c8m5gvpb4b65pc3rfp9r9mzqxx5ws2jq-slack-4.7.0/lib/slack/slack: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory
> ```

Added, try it now.

**Comment by srhb** [comment]
No go, I think they need to be jammed into the rpath :)

**Comment by sikmir** [comment]
> No go, I think they need to be jammed into the rpath :)

Fixed, I hope. I just away from my nixos machine right now, so can't check it.

**Comment by srhb** [comment]
Confirmed, this works on NixOS. I assume you've tested on OS X? :)

**Comment by sikmir** [comment]
> I assume you've tested on OS X? :)

Sure.

**Review by srhb — APPROVED** [review]

**Pull request merged**
