### PR TITLE
procps: 3.3.17 -> 4.0.4

### PR DESCRIPTION
**Pull request by LeSuisse**
## Description of changes

Changes:
https://gitlab.com/procps-ng/procps/-/releases/v4.0.0
https://gitlab.com/procps-ng/procps/-/releases/v4.0.3
https://gitlab.com/procps-ng/procps/-/releases/v4.0.4

## Things done

- Built on platform(s)
  - [x] x86_64-linux (on top of `master`, also built `pkgsStatic` variant)
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by networkhermit** [comment]
Hope this can be merged into 24.05:

```console
❯ sysctl --dry-run --system
sysctl: unrecognized option '--dry-run'
```

Other distros have already use the newer version.

**Comment by typetetris** [comment]
@LeSuisse Appreciate the effort you put in here. You should probably put yourself down as maintainer of procps-ng, too. Because I never really did it. I thought I could invest some time in it, but it was a brainfart, I have to admit. Dunno why https://github.com/NixOS/nixpkgs/commit/59a9165b9dffc35e34304f7b9f8a4cc8edd3564d was merged at all.

I will now try to build myself a 24.05 system with this commit cherry picked on the branch and will report how it goes, but I guess it will take some time compiling, yay.

**Comment by LeSuisse** [comment]
> You should probably put yourself down as maintainer of procps-ng, too. Because I never really did it.

As you wish, I added a commit to the PR :green_heart:

**Comment by typetetris** [comment]
If you don't want to add yourself as maintainer, we should open a ticket about procps being unmaintained, if somebody really merges this PR.
My machine is still compiling, had to abort and restart several times and twiddle with `max-jobs` and `cores` so it doesn't swap ...

**Pull request merged**
