### PR TITLE
stdenv: move overriden stdenv in closure

### LINKED ISSUE #136756: `enableDebugging` does not work anymore: `error: attribute 'override' missing`
### Describe the bug

I tried to build a `nixpkgs` package with debug symbols today and failed. NixOS wiki and nixpkgs repository comments say the following should work:

### Steps To Reproduce

```
$ nix-build -E 'with import <nixpkgs> {}; enableDebugging hello'

error: attribute 'override' missing

       at /nix/store/0skp33kj13x8fyx141qbcfn5q6a4xghw-nixos-21.11pre312407.8a2ec31e224/nixos/pkgs/stdenv/adapters.nix:210:5:

          209|   keepDebugInfo = stdenv:
          210|     stdenv.override (old: {
             |     ^
          211|       mkDerivationFromStdenv = extendMkDerivationArgs old (args: {
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre312407.8a2ec31e224"`
 - channels(slyfox): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by cab404**
Before that, base stdenv passed non-makeOverridable version of itself
inside. This caused it to be lost on package-name.stdenv.

###### Motivation for this change

Make package.stdenv.override work again.

Read commit message for more info.

Fixes #136756

Also I think it does not actually change stdenv in hash-breaking way, so it does not require world-rebuild.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cab404** [comment]
oof, okay, that prompts a lot of buzz.
I just guessed that I've got deep enough in stdenv to be able to review related stuff, so I would like to be a codeowner of that section

**Comment by r-burns** [comment]
Haven't looked at this in depth, but thanks :)

Will this make https://github.com/NixOS/nixpkgs/pull/136804 unnecessary?

**Comment by cab404** [comment]
> Haven't looked at this in depth, but thanks :)
> 
> Will this make #136804 unnecessary?
My solution does not add back `__bootPackages` and `__hatPackages`, so your fix is still probably relevant.

**Comment by rski** [comment]
with this patch, `env NIX_PATH=nixpkgs=$HOME/Code/nix/nixpkgs nix-build -E 'with import<nixpkgs> {}; enableDebugging pkgs.emacs'` starts building for me.
The other derivation that I used to build before the breakage does not however,
```
env NIX_PATH=nixpkgs=$HOME/Code/nix/nixpkgs nix-build -E 'with import<nixpkgs> {}; enableDebugging(firefox.overrideAttrs (old: rec {  name = "myfirefox"; }))'
error: 'wrapper' at /home/rski/Code/nix/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:23:5 called with unexpected argument 'stdenv'

       at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:79:63:

           78|       # Change the result of the function call by applying g to it
           79|       overrideResult = g: makeOverridable (copyArgs (args: g (f args))) origArgs;
```
I used to use this kind of thing to set separateDebugInfo and meta.outputsToInstall. This is with nix2.4 and nixpkgs@d4839a7e572f5ada860ad3b7f0d2d76ebb860ffb + this PR

**Comment by rski** [comment]
actually, with the above setup firefox fails, but emacs does not:
```
env NIX_PATH=nixpkgs=$HOME/Code/nix/nixpkgs nix-build --show-trace -E 'with import<nixpkgs> {}; enableDebugging pkgs.firefox'
error: 'wrapper' at /home/rski/Code/nix/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:23:5 called with unexpected argument 'stdenv'

       at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|

       … while evaluating 'makeOverridable'

       at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:67:24:

           66|   */
           67|   makeOverridable = f: origArgs:
             |                        ^
           68|     let

       … from call site

       at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:77:41:

           76|       # Re-call the function but with different arguments
           77|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                         ^
           78|       # Change the result of the function call by applying g to it

       … while evaluating anonymous lambda

       at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:77:32:

           76|       # Re-call the function but with different arguments
           77|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                ^
           78|       # Change the result of the function call by applying g to it

       … from call site

       at /home/rski/Code/nix/nixpkgs/pkgs/top-level/all-packages.nix:762:26:

          761|   # intended to be used like nix-build -E 'with import <nixpkgs> {}; enableDebugging fooPackage'
          762|   enableDebugging = pkg: pkg.override { stdenv = stdenvAdapters.keepDebugInfo pkg.stdenv; };
             |                          ^
          763|

       … while evaluating 'enableDebugging'

       at /home/rski/Code/nix/nixpkgs/pkgs/top-level/all-packages.nix:762:21:

          761|   # intended to be used like nix-build -E 'with import <nixpkgs> {}; enableDebugging fooPackage'
          762|   enableDebugging = pkg: pkg.override { stdenv = stdenvAdapters.keepDebugInfo pkg.stdenv; };
             |                     ^
          763|

       … from call site

       at «string»:1:26:

            1| with import<nixpkgs> {}; enableDebugging pkgs.firefox
            ```

**Comment by cab404** [comment]
> actually, with the above setup firefox fails, but emacs does not:
> 
> ```
> env NIX_PATH=nixpkgs=$HOME/Code/nix/nixpkgs nix-build --show-trace -E 'with import<nixpkgs> {}; enableDebugging pkgs.firefox'
> error: 'wrapper' at /home/rski/Code/nix/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:23:5 called with unexpected argument 'stdenv'
> 
>        at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:69:16:
> 
>            68|     let
>            69|       result = f origArgs;
>              |                ^
>            70|
> 
>        … while evaluating 'makeOverridable'
> 
>        at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:67:24:
> 
>            66|   */
>            67|   makeOverridable = f: origArgs:
>              |                        ^
>            68|     let
> 
>        … from call site
> 
>        at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:77:41:
> 
>            76|       # Re-call the function but with different arguments
>            77|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
>              |                                         ^
>            78|       # Change the result of the function call by applying g to it
> 
>        … while evaluating anonymous lambda
> 
>        at /home/rski/Code/nix/nixpkgs/lib/customisation.nix:77:32:
> 
>            76|       # Re-call the function but with different arguments
>            77|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
>              |                                ^
>            78|       # Change the result of the function call by applying g to it
> 
>        … from call site
> 
>        at /home/rski/Code/nix/nixpkgs/pkgs/top-level/all-packages.nix:762:26:
> 
>           761|   # intended to be used like nix-build -E 'with import <nixpkgs> {}; enableDebugging fooPackage'
>           762|   enableDebugging = pkg: pkg.override { stdenv = stdenvAdapters.keepDebugInfo pkg.stdenv; };
>              |                          ^
>           763|
> 
>        … while evaluating 'enableDebugging'
> 
>        at /home/rski/Code/nix/nixpkgs/pkgs/top-level/all-packages.nix:762:21:
> 
>           761|   # intended to be used like nix-build -E 'with import <nixpkgs> {}; enableDebugging fooPackage'
>           762|   enableDebugging = pkg: pkg.override { stdenv = stdenvAdapters.keepDebugInfo pkg.stdenv; };
>              |                     ^
>           763|
> 
>        … from call site
> 
>        at «string»:1:26:
> 
>             1| with import<nixpkgs> {}; enableDebugging pkgs.firefox
>             ```
> ```

That does get fixed by adding "..." to wrapper in firefox, alas I am not sure why it was broken in the first place.

**Comment by cab404** [comment]
@rski Fun fact is that enableDebugging was not working in firefox since at least fix-stdenv-override~85240. (enableDebugging hello) worked back then. So I guess that's on firefox side, and will require separate PR.

**Comment by rski** [comment]
hah ok, that's fine then, thanks for checking and thank you so much for trying to fix this

**Comment by cab404** [comment]
@NixOS/nixos-release-managers please?

**Review by balsoft — APPROVED** [review]
The change looks correct; I'm not sure what the policy on updating codeowners is.

**Comment by cab404** [comment]
@Ericson2314, can you please review the change?)

**Comment by symphorien** [comment]
This does not change hashes so it seems low risk for a stdenv change.

**Comment by Artturin** [comment]
Backport after testing it on unstable for a while?

**Comment by symphorien** [comment]
after a while, why not

**Comment by ajs124** [comment]
has a while passed?

**Comment by symphorien** [comment]
Yes I think so, and no issue was linked here in the meantime.

**Pull request merged**
