### PR TITLE
Basic functionality for pure-darwin

### PR DESCRIPTION
**Pull request by pikajude**
Almost all of these commits are @gridaphobe's but he gave me the go-ahead.

When this is merged into master Darwin users should be able to uninstall Xcode and enable chroot in their builds without any negative side effects.

### CODE REVIEW

**Comment by gridaphobe** [comment]
@joelteon how much of your environment are you able to build with this branch? I remember a number of packages breaking due to, e.g. missing `libiconv` dependencies.

**Comment by joelteon** [comment]
@gridaphobe working on that now, after I fix tarball evaluation.

**Comment by iElectric** [comment]
All pythons build now? Awesome!

**Comment by iElectric** [comment]
So #4934 is fixed by this PR?

**Comment by gridaphobe** [comment]
Closing since pure-darwin is now in staging.

**Pull request closed without merging**
