### PR TITLE
rustc: 1.68.2 -> 1.69.0

### PR DESCRIPTION
**Pull request by lblasc**
###### Description of changes

~Pre-release draft, release will happen on 20.04.2023.~

~https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1690-2023-04-20~
https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html

Tested `fd` and `vector` on x86_64-linux both are building fine, looks like https://github.com/rust-lang/rust/pull/107688
is included in this release.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
`pkgs/development/compilers/rust/1_68.nix` needs to be removed.

**Comment by lblasc** [comment]
thx @zowoq , `pkgs/development/compilers/rust/1_68.nix` is removed now.

**Comment by lblasc** [comment]
Built `firefox`, `fd` and `vector` on `x86_64-linux`.

**Comment by zowoq** [comment]
Built passthru.tests on x86_64-darwin.

**Comment by trofi** [comment]
Bisect claims 081c90ff3bfb1212a751122b97bcb99210972e52 `rustc: 1.68.2 -> 1.69.0` broke `evcxr` in `staging`:

```
$ nix build -f. evcxr -L
...
failures:

---- check_for_errors stdout ----
thread 'check_for_errors' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `["warning 1:15-1:20"]`', evcxr/tests/integration_tests.rs:962:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    check_for_errors

test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 260.67s

error: test failed, to rerun pass `-p evcxr --test integration_tests`
```

**Comment by trofi** [comment]
Filed bug upstream as https://github.com/evcxr/evcxr/issues/294

**Pull request merged**
