### PR TITLE
nixos-rebuild-ng: make sure to copy the new closure when doing test or build

### PR DESCRIPTION
**Pull request by r-vdp**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by thiagokokada — CHANGES_REQUESTED** [review]
`--target-host` was not supposed to work with `test` or `build` and is being removed in the next PR: https://github.com/NixOS/nixpkgs/pull/360215.

It is not that we can't make it work, but right now it doesn't in `nixos-rebuild` and I don't want to add new features to `nixos-rebuild-ng` (yet). So this is probably something that needs to be redone later.

**Comment by r-vdp** [comment]
> `--target-host` was not supposed to work with `test` or `build` and is being removed in the next PR: https://github.com/NixOS/nixpkgs/pull/360215.
> 
> It is not that we can't make it work, but right now it doesn't in `nixos-rebuild` and I don't want to add new features to `nixos-rebuild-ng` (yet). So this is probably something that needs to be redone later.

Hmm, I use this all the time with the current implementation and it works just fine.

**Comment by thiagokokada** [comment]
> > `--target-host` was not supposed to work with `test` or `build` and is being removed in the next PR: #360215.
> > It is not that we can't make it work, but right now it doesn't in `nixos-rebuild` and I don't want to add new features to `nixos-rebuild-ng` (yet). So this is probably something that needs to be redone later.
> 
> Hmm, I use this all the time with the current implementation and it works just fine.

Actually this is true, for some reason they decided to do the copy later:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L826-L828

Ok, I think I will put this in https://github.com/NixOS/nixpkgs/pull/360215 instead and if you can help me test that it works would be great.

**Comment by r-vdp** [comment]
This was cherry-picked into 360215.

**Pull request closed without merging**
