### PR TITLE
[WIP] docker, dockerTools: Unpin Go 1.9 (remove Go from Docker closure)

### PR DESCRIPTION
**Pull request by Anton-Latukha**
###### Motivation for this change

Go would not longer going to be present in the Docker closure.

Fixes: 
- [x] "docker has go in its closure, causing a huge closure size increase #41152"
- [x] "reduce docker nix closure (currently 1GB) https://github.com/mozilla-releng/services/issues/1064"

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
It looks like `docker_18_05` should be built with Go 1.10, but `docker_18_03` — with Go 1.9.
https://github.com/docker/docker-ce/blob/v18.03.1-ce/components/engine/Dockerfile.e2e#L2
https://github.com/docker/docker-ce/blob/v18.05.0-ce/components/engine/Dockerfile.e2e#L2
/cc @srhb

**Comment by nlewo** [comment]
@GrahamcOfBorg test docker-tools docker

**Comment by srhb** [comment]
Yes, I think we should still attempt to use the same versions that upstream does.

**Comment by Anton-Latukha** [comment]
I am figuring-out why:
```nix
{  go ? null, go_1_9 ? null }:
rec {
  dockerGen = { ... }:
  let
    docker-containerd = containerd.overrideAttrs (oldAttrs: rec {
      go = (if versionAtLeast version "18.05.5-ce" then go else go_1_9);
      buildInputs = [ removeReferencesTo go btrfs-progs ];
    });
  in
    stdenv.mkDerivation ( rec {
      inherit docker-containerd;
      buildInputs = [ removeReferences go ];
  });

  docker_18_03 = dockerGen rec { ... };

  docker_18_05 = dockerGen rec { ... };
}
```

Makes Go to come back.

**Comment by Anton-Latukha** [comment]
So the main question is: how to manage package version override, so that `removeReferencesTo` works?

Maybe the real question is formulated backwards, and it is a quirk, and we need to change `removeReferencesTo` itself, to work with normal overrides.

**Comment by orivej** [comment]
You don't have to introduce `go_1_9` into `docker/default.nix`, you can simply put this in `all-packages.nix`:
```
  inherit (callPackage ../applications/virtualization/docker { go = go_1_9; })
    docker_18_03;
  inherit (callPackage ../applications/virtualization/docker { go = go_1_10; })
    docker_18_05;
```

**Comment by Anton-Latukha** [comment]
Putting it in `docker/default.nix`, people makes:
* obvious for everyone who looks at `docker`
*  here we work to solve `removeReferencesTo` for overrides.

Putting it in `all-packages.nix` would result in the same:
* I would not track it.
* everyone looks at `docker/default.nix`, and try to figure-out what is going on.
* we return to initial position with Docker closure has Go, while Go 1.10 became gargantuan 1,368,973,064.

**Comment by Anton-Latukha** [comment]
Since `removeReferencesTo` is a cool concept, and at this moment not really used, so we better figure-out how to make it work with overrides of `buildInputs`.

**Comment by Anton-Latukha** [comment]
Closed in favor of: https://github.com/NixOS/nixpkgs/pull/41849
I did not found that solution.

**Pull request closed without merging**
