### PR TITLE
python311Packages.apache-beam: 2.50.0 -> 2.54.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

This is an attempt at fixing (and updating) `apache-beam`. Currently, the tests crash weirdly.

Changelog: https://github.com/apache/beam/releases/tag/v2.54.0

cc @ndl

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
If we disable tests related to pandas, will checkPhase succeed?

**Comment by GaetanLepage** [comment]
> If we disable tests related to pandas, will checkPhase succeed?

The annoying thing is that tests are run in a multi-processing manner. The logs are very unclear and I can't infer what test is broken and how.

**Comment by MaxwellDupre** [comment]
Need to resolve conflicts then can approve.

**Comment by GaetanLepage** [comment]
Requirements are so strict... we will never get this thing to build :/
```
Checking runtime dependencies for apache_beam-2.54.0-cp311-cp311-linux_x86_64.whl
  - dill<0.3.2,>=0.3.1.1 not satisfied by version 0.3.7
  - cloudpickle~=2.2.1 not satisfied by version 3.0.0
  - js2py not installed
  - jsonschema not installed
  - jsonpickle not installed
  - numpy<1.25.0,>=1.14.3 not satisfied by version 1.26.2
  - protobuf!=4.0.*,!=4.21.*,!=4.22.0,!=4.23.*,!=4.24.*,<4.26.0,>=3.20.3 not satisfied by version 4.24.4
  - pyarrow<15.0.0,>=3.0.0 not satisfied by version 15.0.0
  - pyarrow-hotfix not installed
```

**Comment by wegank** [comment]
Done in https://github.com/NixOS/nixpkgs/commit/e32e89b3c73971615f6c010c87f02d8b5d43ecd3?

**Comment by GaetanLepage** [comment]
> Done in [e32e89b](https://github.com/NixOS/nixpkgs/commit/e32e89b3c73971615f6c010c87f02d8b5d43ecd3)?

Indeed, thanks for noticing @wegank !

**Pull request closed without merging**
