### PR TITLE
teleport_16: 16.1.4 -> 16.2.0

### PR DESCRIPTION
**Pull request by kieeps**
## Description of changes

New update of Teleport 16.
Mostly security related fixes in [16.1.8](https://github.com/gravitational/teleport/releases/tag/v16.1.8) and [16.2.0](https://github.com/gravitational/teleport/releases/tag/v16.2.0)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by techknowlogick** [comment]
Result of `nixpkgs-review pr 339830` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
  </ul>
</details>

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
Something seems to be up with the bot. I'm listed as a maintainer for teleport_16, but it seems not to assign any maintainer to reviews for it.

**Comment by kieeps** [comment]
> Something seems to be up with the bot. I'm listed as a maintainer for teleport_16, but it seems not to assign any maintainer to reviews for it.

yea i'm not sure how it usually works :D it's my first contrib here so I'm kind of observing and trying to figure out what comes next :)

**Comment by techknowlogick** [comment]
@kieeps welcome aboard :) You've done everything correctly, I was merely wondering aloud in case someone with access to the bot know whats up.
Next steps are: possibly another maintainer will review on a different architecture, and then a merger will merge. No specific timelines, but there is a thread on the discourse you can post in to get more eyes on the PR if there is ever a time no one reviews within a reasonable period of time.

**Comment by kieeps** [comment]
> @kieeps, welcome aboard! :) You've done everything correctly. I was merely wondering aloud in case someone with access to the bot knows what's up. The next steps are: possibly another maintainer will review a different architecture, and then a merger will merge. There are no specific timelines, but there is a thread on the discourse you can post to get more eyes on the PR if there is ever a time when no one reviews within a reasonable period.

Thanks ^_^

ok i'll keep en eye on it :)

**Review by starsep — APPROVED** [review]

**Comment by fabianhjr** [comment]
Hi and thanks for your contribution @kieeps, per the contributing guidelines dropped the merge commit and squashed your changes into a single commit with commit message `teleport_16: 16.1.4 -> 16.2.0`

https://github.com/NixOS/nixpkgs/blob/dc0609e59ddf6b87c760ad24ba7517cbd8b21ff6/CONTRIBUTING.md#commit-conventions

**Comment by fabianhjr** [comment]
Result of `nixpkgs-review pr 339830` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
  </ul>
</details>

**Review by fabianhjr — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Pull request merged**
