### PR TITLE
opentimestamps: 0.2.1 -> 0.3.0, opentimestamps-client: 0.5.1 -> 0.6.0

### PR DESCRIPTION
**Pull request by erikarvstedt**
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [?] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). ( --> I took the liberty to merge two version bumps into this single commit.)

---

### CODE REVIEW

**Review by dotlambda — COMMENTED** [review]
I'd prefer 2 seperate commits.

**Comment by erikarvstedt** [comment]
I'v split the commits.

As mentioned in my [introductory PR](https://github.com/NixOS/nixpkgs/pull/36414), we can't use pypi for this package. I've added some source comments to clarify this.

By the way, here's a usage example to help reviewing:
```
echo 'data to timestamp' | $(nix-build --no-out-link <dev-nixpkgs> -A opentimestamps-client)/bin/ots stamp
```

**Comment by dotlambda** [comment]
You forgot to use `pname` instead of `name`. The latter will automatically be set to `"${pname}-${version}"` by `buildPython*`.

**Comment by erikarvstedt** [comment]
Thanks for the hint.
There are so many python pkg definitions that explicitly define `name = "${pname}-${version}"` that I thought `pname` was just a convention when using `pypi`. I could prepare a patch to remove all redunant `name` definitions. Would that be helpful?

**Comment by dotlambda** [comment]
> I could prepare a patch to remove all redunant name definitions. Would that be helpful?

I'm not sure it's necessary. There's no huge advantage in having no `name`, so I think it's okay to use it for new/updated packages only.
However, if you feel like doing a PR, don't hesitate.

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.opentimestamps python3.pkgs.opentimestamps opentimestamps-client

@erikarvstedt You should prepend `pythonPackages.` to the message of your first commit.

**Comment by erikarvstedt** [comment]
Fixed. Thanks for your patience!

**Pull request merged**
