### PR TITLE
_1password-gui: 8.10.4 -> 8.10.6

### PR DESCRIPTION
**Pull request by amaxine**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 232718` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>_1password-gui</li>
    <li>_1password-gui-beta</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Review by SebTM — APPROVED** [review]

**Comment by SebTM** [comment]
Tested locally, builds and runs without issues so far.

**Comment by SebTM** [comment]
Does anyone else (not new) encourage an issue with Sway/Wayland and https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/1password-gui/linux.nix#LL135C22-L135C22 that copying regardless of the field and direct or via dot-menu/actions it will not change. The support wasn't sure about it either.

If so can we remove it because I need the option for other tools to be enabled but it breaks for me the UX in 1Password.

**Comment by teutat3s** [comment]
This seems to be an upstream issue: https://1password.community/discussion/comment/624011/#Comment_624011

**Comment by SebTM** [comment]
> This seems to be an upstream issue: https://1password.community/discussion/comment/624011/#Comment_624011
> 
> EDIT: If you don't want to rebuild, you can also
> 
> ```
> unset NIXOS_OZONE_WL
> 1password
> ```

Thanks for pointing out, sometimes it's the overflow of information's/sources to look at to miss something obvious :v:

https://1password.community/discussion/comment/661660/#Comment_661660
As I agree with that comment, should we remove the NIXOS_OZONE_WL handling until fixed?

**Comment by maxeaubrey** [comment]
I'm not sure how I feel about dropping `NIXOS_OZONE_WL` from 1p entirely. I appreciate that this is quite buggy, but also simultaneously for my 1p use cases I've not actually ran into any of those problems. Have you brought it up via their support email? I found their replies there were more helpful when I had appindicator issues with one of the older releases.

That said, 1p does seem super flaky under wayland still, I've not had a crash since I opened this PR (which is not a useful timescale yet really), but prior to that opening quick access did result in a crash about a 3rd of the time. I'm not sure if there's a useful space to put a warning about this into nixos docs.

**Comment by Lyndeno** [comment]
Forgive me if I do not have the right term here. Could we add an "override" to the package to easily allow someone to use and overlay or something to disable the `NIXOS_OZONE_WL` specifically for this package? Perhaps something like `respect_ozone_wl ? true` at the top?

**Comment by maxeaubrey** [comment]
For those interested, I received the following response from 1password support about the recent Wayland issues:

> After speaking with the development team, it appears that xwayland will be required for full 1Password for Linux (desktop app) functionality for the time being. Currently Wayland is not fully supported and is expected to have some issues at this time.

While 1password works just well enough for me under Wayland, it appears that's not the case for quite a lot of people, so a PR removing `NIXOS_OZONE_WL` or adding some sort of warning, or making the wayland flags even more opt-in would not be unwelcome.

**Pull request merged**
