### PR TITLE
maestral-gui: 1.2.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by SFrijters**
###### Motivation for this change

Upstream update.

###### Things done

```
$ nix-shell -p nixpkgs-review --run "nixpkgs-review wip"
[...]
4 package updated:
maestral (1.2.1 → 1.2.2) maestral-qt (1.2.1 → 1.2.2) python3.7-maestral (1.2.1 → 1.2.2) python3.8-maestral (1.2.1 → 1.2.2)
[...]
3 package built:
maestral maestral-gui python37Packages.maestral
```

I'm not sure why it doesn't do the python38Python variant?

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by zyansheep — APPROVED** [review]
It builds correctly, but maestral-qt doesn't play well with nix-review's read-only filesystem. It should work normally though. Maestral cli seems to function properly as well.

**Comment by SFrijters** [comment]
Also tested it with the `dbus-next` update introduced in #103303, seems to work fine.

**Comment by peterhoeg** [comment]
> but maestral-qt doesn't play well with nix-review's read-only filesystem
In what way @zyansheep

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103327` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>maestral (python38Packages.maestral)</li>
    <li>maestral-gui</li>
    <li>python37Packages.maestral</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
What still needs to happen for this to get merged? Rebased it and it now also correctly builds for python39.

```
maestral (1.2.1 → 1.2.2) maestral-qt (1.2.1 → 1.2.2) python3.7-maestral (1.2.1 → 1.2.2) python3.8-maestral (1.2.1 → 1.2.2) python3.9-maestral (1.2.1 → 1.2.2)

warning: unknown setting 'experimental-features'
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/frijters/.cache/nixpkgs-review/rev-f01c236e9bc1dd0126780c449405dda0d02c68f8/build.nix
warning: unknown setting 'experimental-features'
[3 built, 145 copied (237.4 MiB), 41.6 MiB DL]
4 package built:
maestral maestral-gui python37Packages.maestral python39Packages.maestral
```

**Comment by SFrijters** [comment]
Superseded by #106361

**Pull request closed without merging**
