### PR TITLE
fabric-ai: init at 1.4.14

### PR DESCRIPTION
**Pull request by jaredmontoya**
## Description of changes
Created a package for [fabric](https://github.com/danielmiessler/fabric) because the project finally delivered it's promise to switch from python to go.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by chewblacka** [comment]
Closes https://github.com/NixOS/nixpkgs/issues/320031

**Comment by Shlok-Bhakta** [comment]
This works for me. Thanks!

**Comment by vsuharnikov** [comment]
On aarch64-darwin works too

**Comment by NikodemMarek** [comment]
Encountered an isuue `> go: go.mod requires go >= 1.22.5 (running go 1.22.3; GOTOOLCHAIN=local)`
fixed by changing `buildGoModule` to `buildGo123Module`

**Comment by jaredmontoya** [comment]
Is this a darwin problem? builds fine on NixOS.

**Comment by NikodemMarek** [comment]
no, it's not darwin, I'm on nixos unstable

**Comment by jaredmontoya** [comment]
Are you perhaps running an old nixpkgs commit on your system? maybe in the past buildGoModule used 1.22.3 and your nixpkgs is pinned to that version in the flake.lock file.
If so, then this workaround is not necessary because you won't get fabric-ai package in that old nixpkgs instance unless you update.

**Comment by jaredmontoya** [comment]
https://github.com/danielmiessler/fabric/issues/833 is resolved. The project is indeed under the MIT license. I suspect the LICENSE file won't be included in the package until their next release after 2.0 but the license is now confirmed.

**Review by chewblacka — APPROVED** [review]
LGTM

**Comment by jaredmontoya** [comment]
I don't know why it wasn't merged for so long but I guess it's good because something is up with their release versioning because I "updated" this PR from 2.0 to 1.4.14 and it now has a LICENSE file so maybe now it will get merged.

**Review by chewblacka — APPROVED** [review]
LGTM

**Review by abysssol — APPROVED** [review]

**Comment by abysssol** [comment]
Thank you to everyone involved in bringing `fabric` to nixpkgs!

**Pull request merged**
