### PR TITLE
noaa-apt: 1.2.0 -> 1.3.0

### PR DESCRIPTION
**Pull request by trepetti**
###### Motivation for this change

Version bump and making `platforms.all` explicit to make sure hydra builds binary versions: https://github.com/NixOS/nixpkgs/pull/99995#discussion_r503282420

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trepetti** [comment]
Result of `nixpkgs-review pr 100510` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>noaa-apt</li>
  </ul>
</details>

**Review by r-burns — APPROVED** [review]
Works on darwin too. LGTM

**Comment by r-burns** [comment]
Fyi, platforms.all might not be needed for rust packages https://github.com/NixOS/nixpkgs/pull/101745#issuecomment-716413026. Not really cut and dry though so explicit seems good to be on the safe side.

**Review by timokau — APPROVED** [review]
Thanks to both of you!

**Pull request merged**
