### PR TITLE
Terraform 0.9.10

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

Also removes some old versions. Let's only keep minor versions.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
BTW, regarding https://github.com/NixOS/nixpkgs/pull/26907#discussion_r125087488
As ```terraform``` made by the same team and also contains ```Makefile``` among the sources, is there any difference between versions of the package compiled using ```buildGoPackage``` and ```stdenv.mkDerivation``` ?

**Comment by zimbatm** [comment]
We should probably switch to a stdenv.mkDerivation as the build is supposed to be driven by the Makefile. At the moment we can get away with emulating what the Makefile does using the postInstall phase in the terraform project but it's probably going to diverge in the next minor where the plugins are loaded dynamically.

**Comment by Mic92** [comment]
Switching from `buildGoPackage` to `mkDerivation` has the disadvantage, that will contain a runtime reference on the go compiler itself. This is usually cleared by `buildGoPackage`.

**Comment by cstrahan** [comment]
@zimbatm 

@shlevy Pointed out (about a week ago) that Terraform point releases are (supposedly) major, breaking changes: https://github.com/NixOS/nixpkgs/commit/4d2597981dc227dfa2f9ccb167f710bc0371a2b2

@shlevy If we should be retaining a handful of old point releases, perhaps we should indicate that as comments in the relevant places?

**Comment by shlevy** [comment]
@cstrahan Yeah, we should add them back with comments on the ones we want to keep

**Comment by zimbatm** [comment]
How many versions are we supposed to keep? Personally I try to keep track of the latest release, maybe the one before is there are some major incompatibilities.

**Comment by shlevy** [comment]
IMO anything community members stay they're still using that doesn't come with a huge maintenance overhead. So maybe we can put something in a comment for which user(s) are still using the version in question and people interested in cleanup can check in with them if they're still using it?

**Comment by zimbatm** [comment]
It would be easier for users to pin old versions if they are not able to keep up for some reason. Users come and go and might not let us know when they stop using NixOS or terraform.

**Comment by zimbatm** [comment]
@cstrahan @shlevy what versions are you currently using?

**Comment by zimbatm** [comment]
I also noticed that terragrunt hasn't been updated for a while. The new version is compatible with the latest terraform.

**Comment by shlevy** [comment]
We're using terraform 0.9.4 and terragrunt 0.12.15. If we're not OK keeping around old versions, can we at least expose a function that lets us just pass in a version + src hash in the normal case?

**Pull request merged**
