### PR TITLE
timeline: fix build, migrate to wxPython_4_2

### PR DESCRIPTION
**Pull request by wegank**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 221908` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>python310Packages.humblewx</li>
    <li>python310Packages.humblewx.dist</li>
    <li>python311Packages.humblewx</li>
    <li>python311Packages.humblewx.dist</li>
    <li>timeline</li>
  </ul>
</details>

**Comment by davidak** [comment]
Thanks for the fix!

I get an error when i run it.

```
[nix-shell:~/.cache/nixpkgs-review/pr-221908]$ results/timeline/bin/timeline 
Traceback (most recent call last):
  File "/nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0/bin/.timeline-wrapped", line 35, in <module>
    from timelinelib.meta.about import APPLICATION_NAME
  File "/nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0/lib/python3.10/site-packages/timelinelib/meta/about.py", line 22, in <module>
    import wx.adv
  File "/nix/store/ybmj998j1vbnqw856y3nv7ssdb9mnn9m-python3.11-wxPython-4.2.0/lib/python3.11/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/nix/store/ybmj998j1vbnqw856y3nv7ssdb9mnn9m-python3.11-wxPython-4.2.0/lib/python3.11/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ModuleNotFoundError: No module named 'wx._core'
```

**Comment by wegank** [comment]
I guess there are a lot of Python errors under `nixpkgs-review` that are not reproducible outside. Does it work if you run a `nix-build` manually?

**Comment by davidak** [comment]
>I guess there are a lot of Python errors under nixpkgs-review that are not reproducible outside

I remember there are some issues.

I get the same issue when using nix-build inside nixpkgs-review, but when i run it on master, i get the same result, but it works!

```
[nix-shell:~/.cache/nixpkgs-review/pr-221908]$ nix-build nixpkgs/ -A timeline
/nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0

[nix-shell:~/.cache/nixpkgs-review/pr-221908]$ /nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0/bin/timeline 
Traceback (most recent call last):
  File "/nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0/bin/.timeline-wrapped", line 35, in <module>
    from timelinelib.meta.about import APPLICATION_NAME
  File "/nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0/lib/python3.10/site-packages/timelinelib/meta/about.py", line 22, in <module>
    import wx.adv
  File "/nix/store/ybmj998j1vbnqw856y3nv7ssdb9mnn9m-python3.11-wxPython-4.2.0/lib/python3.11/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/nix/store/ybmj998j1vbnqw856y3nv7ssdb9mnn9m-python3.11-wxPython-4.2.0/lib/python3.11/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ModuleNotFoundError: No module named 'wx._core'
```

```
[davidak@gaming:~/code/nixpkgs]$ nix-build . -A timeline
/nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0

[davidak@gaming:~/code/nixpkgs]$ /nix/store/8i3j6z42xqlkbdhig91b83sz4xjkiz96-timeline-2.6.0/bin/timeline 

[davidak@gaming:~/code/nixpkgs]$ echo $?
0
```

So everything is OK here.

**Pull request merged**
