### PR TITLE
`haskell-updates`: update Hackage, in particular `Cabal-3.8.1.0`

### PR DESCRIPTION
**Pull request by peterbecich**
###### Description of changes

produced with
```
./maintainers/scripts/haskell/update-stackage.sh
./maintainers/scripts/haskell/update-hackage.sh
./maintainers/scripts/haskell/regenerate-hackage-packages.sh
```

I am trying to get revision 2 of `Cabal-3.8.1.0` into the package set: https://hackage.haskell.org/package/Cabal-3.8.1.0/revisions/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Looks like we are in good shape and `haskell-updates` can be merged in the next days. After that we'll  start another regular rotation. We are seemingly all a bit short on time at the moment, so things are going a bit slower than usual.

**Comment by peterbecich** [comment]
@sternenseemann , thanks, can we include

```
       pname = "Cabal";
       version = "3.8.1.0";
       sha256 = "0236fddzhalsr2gjbjsk92rgh8866fks28r04g8fbmzkqbkcnr3l";
       revision = "2";
```
https://github.com/NixOS/nixpkgs/blob/645175db2b2ecb4032005b2c24ff023d44cb6320/pkgs/development/haskell-modules/hackage-packages.nix#L2910-L2913 before `haskell-updates` is merged?

Should I slim down this PR to just this single change?

**Comment by sternenseemann** [comment]
See #217111/#219027

**Comment by peterbecich** [comment]
Thanks

**Pull request closed without merging**
