### PR TITLE
haskellPackages.shellFor: fix after recent getHaskellBuildInputs fix.

### LINKED ISSUE #45318: Haskell / shellFor broken due to recent commit
## Issue description
```haskellPackages.shellFor``` now aborts with
```error: value is a list while a set was expected, at /home/choener/tmp/nix/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:236:47```

### Steps to reproduce
on ```release-18.03``` switch between commits
9cbc7363543ebeb5a0182aa171f23bb19332b99f (last working) and
66bd479f261152e99f609e8f6826f30dd13e1d8f (introduces the error for me)

use this ```default.nix``` and ```nix-shell --arg pkgs ~/tmp/nix/nixpkgs -A hsShell```
```
{ pkgs ? <nixpkgs> }:
with (import pkgs {});
with haskell.lib;
with builtins;

{
  hsShell = with haskellPackages; shellFor {
    packages = p: [ p.vector ];
  };
}
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133023.18401b99f3f (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133114.a4e068ff9c8"`
 - channels(choener): `"unstable-18.09pre149415.8395f9aa85e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #45318

### CODE REVIEW

**Comment by shlevy** [comment]
@sellout ping? I don't use `shellFor` myself, would like to have confirmation from a user.

**Comment by choener** [comment]
Both the actual patch commit and the patch on top of git rebase master work for me.

Many thanks,
Christian

**Comment by cocreature** [comment]
Ping :) I can confirm that this fixes things for me (after applying the patch to HEAD) so it would be nice if this could be merged.

**Comment by sellout** [comment]
Hey, sorry. I am in the wilderness. But I don’t think I use shellFor at all either.

**Comment by shlevy** [comment]
Oops, got my wires crossed, meant to ping @ElvishJerricco !

**Pull request merged**
