### PR TITLE
meshcommander: init at 0.8.0-e

### PR DESCRIPTION
**Pull request by tfc**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
I don't feel myself comfortable enough in the NodeJS ecosystem, sorry.

**Comment by marsam** [comment]
Sorry for the delay. Could you follow the steps listed in "To add a package from NPM to nixpkgs" https://nixos.org/nixpkgs/manual/#node.js?
Please ping me if you have any issue

**Comment by tfc** [comment]
@marsam i am a bit late, but i did what you suggested. Thank you for your input.

**Comment by marsam** [comment]
@GrahamcOfBorg build nodePackages.meshcommander 
@GrahamcOfBorg build nodePackages.pyright nodePackages.prettier nodePackages.expo-cli nodePackages.typescript

**Pull request merged**
