### PR TITLE
grafx2: 2.4 -> 2.6

### PR DESCRIPTION
**Pull request by bb010g**
###### Motivation for this change

Upgrading Grafx2 to an actively maintained release, as well as ensuring at least one distribution actually attempts truer source builds of dependencies like recoil.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after): adds 421.7kb
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Upgrades Grafx2 from 2.4 to 2.6, introduces its dependency RECOIL at 4.3.1, and introduces RECOIL's dependency `cito` at the latest release 0.4 and the latest Git revision `8cd935e`.

As I was implementing `grafx2`'s `postFetch` hook to insert a revision version file normally included from tarballs, I noticed that `fetchFromGitHub` is inconsistent in how `postFetch` works due to using either `fetchzip` (uses `postFetch`, so user extends on `extraPostFetch`) or `fetchgit` (extends on `postFetch`). The first commit standardizes `postFetch` over forge fetchers and updates all usages in Nixpkgs as needed.

### CODE REVIEW

**Comment by veprbl** [comment]
Can you please split this into two PR's? Also for `fetchFrom` change, I think, you need to explain *much* more about what you are trying to achieve here. The big diff doesn't help with ease of review, splitting into smaller commits should help. Some other questions: is this change backward compatible? What steps did you already take to ensure this doesn't break anything?

**Comment by risicle** [comment]
Hmm this builds for me on non-nixos linux x86_64 but `grafx2` segfaults for me just after it spawns a window:

```
#0  0x00007ffff79505e7 in __memcpy_ssse3 () from /nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib/libc.so.6
#1  0x0000000000418b9c in GFX2_UpdateRect ()
#2  0x0000000000418f97 in Flush_update ()
#3  0x00000000004769eb in Get_input ()
#4  0x000000000044b176 in Window_clicked_button ()
#5  0x000000000046c740 in Verbose_message ()
#6  0x0000000000407705 in Init_program ()
#7  0x0000000000407f96 in main ()
```

**Comment by veprbl** [comment]
@bb010g Are you still interested in finishing this?

**Comment by miniupnp** [comment]
grafx2 2.7 is out ! ;)

**Comment by bb010g** [comment]
Sorry about the delay. Currently reworking this with better style. First commit (cito) is up at bb010g/nixpkgs@14eb8434e1dbe8d2f71f58003cea85f484156f79 (on the [`bb010g:grafx2-2.6-neo`](https://github.com/bb010g/nixpkgs/commits/grafx2-2.6-neo) branch), and I'll get rid of that branch once Grafx2 is actually included again.

**Comment by miniupnp** [comment]
@bb010g  what's the status ?

**Comment by rapenne-s** [comment]
Could you rebase your work on a recent commit and focus on upgrading grafx2 first?

https://github.com/NixOS/nixpkgs/pull/57739/commits/aed052818925d0a34befcf86355b07eb0b3d9d99 should not be mixed with updating grafx2

**Comment by AndersonTorres** [comment]
Closing as dead.

**Pull request closed without merging**
