### PR TITLE
tesseract: split outputs

### PR DESCRIPTION
**Pull request by Profpatsch**
cc maintainer @viric 

tested manually on nixpkgs

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.pyocr

**Comment by xeji** [comment]
This seems to break pyocr.

**Comment by Profpatsch** [comment]
@xeji: Good catch! I’ve adjusted the input of `pyocr`, but it seems to have problems running the tests now. Can you take a look at it?
cc @aszlig 

@GrahamcOfBorg build python36Packages.pyocr

**Comment by xeji** [comment]
I believe  `pyocr` needs some additional patching in  https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pyocr/paths.patch to use the correct value of `NIX_TESSDATA_PREFIX` everywhere. I don't know the package well enough to know exactly what to look for.

**Pull request closed without merging**
