### PR TITLE
gcc,gcc8: {revert gcc to gcc7, mark gcc8 as broken} on Darwin

### PR DESCRIPTION
**Pull request by Synthetica9**
###### Motivation for this change

See #40038.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
There must still be a job using gcc8. Eval is broken.

**Comment by Synthetica9** [comment]
Let's see how this works

**Comment by Synthetica9** [comment]
:heavy_check_mark:

**Comment by Synthetica9** [comment]
Wait, don't merge this, I'm cherry-picking a0ab41ca96cc632ee8f840e66a27101e73683db2

**Comment by Synthetica9** [comment]
@matthewbauer merge?

**Comment by Laaas** [comment]
Since that issue is closed now, should this be reverted?

**Pull request merged**
