### PR TITLE
weechat: 3.3 -> 3.4.1

### PR DESCRIPTION
**Pull request by schuelermine**
###### Motivation for this change

WeeChat version 3.4 was released on 13-12-2021

###### Things done

The WeeChat version has been bumped to 3.4 (from 3.3)

###### Things to do

After this change, WeeChat fails to build; this needs to be fixed

(I built with `nix build`, version 2.7.0pre20220124_0a70b37)

<details>

<summary> (Click to expand) It fails with the following errors: </summary>

(`[…]` = omitted)
```
No such file or directory - /nix/store/7vl7rzs7vz0pi039nrn3r2hcnjp7r6q2-ruby2.7.5-pygments.rb-2.2.0/lib/ruby/gems/2.7.0/gems/pygments.rb-2.2.0/lib/pygments/mentos.py
  Use --trace for backtrace
[…]
make[2]: *** [doc/de/CMakeFiles/doc-scripting-de.dir/build.make:74: doc/de/weechat_scripting.de.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:2400: doc/de/CMakeFiles/doc-scripting-de.dir/all] Error 2

```

```
No such file or directory - /nix/store/7vl7rzs7vz0pi039nrn3r2hcnjp7r6q2-ruby2.7.5-pygments.rb-2.2.0/lib/ruby/gems/2.7.0/gems/pygments.rb-2.2.0/lib/pygments/mentos.py
  Use --trace for backtrace
make[2]: *** [doc/de/CMakeFiles/doc-user-de.dir/build.make:79: doc/de/weechat_user.de.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:2374: doc/de/CMakeFiles/doc-user-de.dir/all] Error 2
```

</details>

Note also that these logs don’t match the logs I got the first time I built this; there’s likely concurrent jobs running, so I did my best to associate the error messages together into groups

###### Checkboxes

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by schuelermine** [comment]
OK, it needs pygments.rb in order to work

**Comment by schuelermine** [comment]
I think it’s provided by pkgs.asciidoctor.gems."pygments.rb"… but adding that to buildInputs doesn’t work.
I’m gonna get back to this tomorrow.

**Comment by wahjava** [comment]
In my overlay, I just went ahead, and disabled the documentation:

```nix
cmakeFlags = old.cmakeFlags ++ [ "-DENABLE_DOC=OFF" ];
```

**Comment by herbetom** [comment]
There is now a [Version 3.4.1 (security release)](https://weechat.org/news/124/20220313-Version-3.4.1-security-release/) because of [WSA-2022-1](https://weechat.org/doc/security/WSA-2022-1/).

**Comment by herbetom** [comment]
Sorry, i can't help with that. I only noticed that there is a 4.3.1 and that this PR therefore needs a bump.

**Comment by schuelermine** [comment]
The errors thrown are very confusing. It complains that `/nix/store/7vl7rzs7vz0pi039nrn3r2hcnjp7r6q2-ruby2.7.5-pygments.rb-2.2.0/lib/ruby/gems/2.7.0/gems/pygments.rb-2.2.0/lib/pygments/mentos.py` does not exist. But it does! Does it need to be an explicit build input? I’ve tried but it doesn’t work. Where is the build process even getting the path from when it’s not an input?

**Comment by schuelermine** [comment]
Thank you for noting that the new version exists, though!

**Comment by mweinelt** [comment]
Disable the documentation, add a TODO comment to reenable them. We need to get that security update merged asap.

**Comment by schuelermine** [comment]
@mweinelt I have disabled documentation

**Review by lukegb — APPROVED** [review]

**Review by picnoir — APPROVED** [review]

**Comment by ncfavier** [comment]
> The errors thrown are very confusing. It complains that `/nix/store/7vl7rzs7vz0pi039nrn3r2hcnjp7r6q2-ruby2.7.5-pygments.rb-2.2.0/lib/ruby/gems/2.7.0/gems/pygments.rb-2.2.0/lib/pygments/mentos.py` does not exist. But it does! Does it need to be an explicit build input? I’ve tried but it doesn’t work. Where is the build process even getting the path from when it’s not an input?

"No such file or directory" errors on executable files are often caused by missing *interpreters*. In this case, `mentos.py` had an unpatched shebang `#!/usr/bin/env`, which doesn't exist in the Nix sandbox. This is fixed by https://github.com/ncfavier/nixpkgs/commit/4ac0d551bd121ea376ac109a395b4790bcf4c1c6.

**Comment by schuelermine** [comment]
@ncfavier Thank you for the information, and for fixing it!

**Pull request merged**
