### PR TITLE
python3Packages.httpx: 0.23.3 -> 0.24.1

### PR DESCRIPTION
**Pull request by bhipple**
###### Description of changes

https://github.com/encode/httpx/blob/master/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
Would you mind adding a commit updating [`pytest-httpx`](https://github.com/Colin-b/pytest_httpx) to v0.22.0? It seems intended to move in lockstep with `httpx`.

**Comment by tjni** [comment]
As noted in https://github.com/NixOS/nixpkgs/pull/237274, `frogmouth` is also affected and will need its dependency on `httpx` to be relaxed.

**Comment by mweinelt** [comment]
> Would you mind adding a commit updating [`pytest-httpx`](https://github.com/Colin-b/pytest_httpx) to v0.22.0? It seems intended to move in lockstep with `httpx`.

Please also update httpcore for the same reason

**Comment by bhipple** [comment]
Thank you for pushing this along, @mweinelt!  It's much appreciated.  I've had a really busy week at work so I haven't had time to follow-up, and probably won't this week either.

**Comment by bhipple** [comment]
I added the relaxed deps on `frogmouth` as requested.

**Comment by figsoda** [comment]
#240135 updates frogmouth with updates its httpx dependency

**Comment by bhipple** [comment]
I rebased away the changes that have already been merged.  I think the rest is now good for review?

```
dropping b1aeda150799209be82285f9fdf86d291200abbf python310Packages.pytest-httpx: 0.21.3 -> 0.22.0 -- patch contents already upstream
dropping 7a81cb6803390d183924df84f420eded64288ea5 python310Packages.frogmouth: relax dependency on httpx -- patch contents already upstream
```

**Pull request closed without merging**
