### PR TITLE
mattermost: 5.9.0 -> 5.15.0

### PR DESCRIPTION
**Pull request by jslight90**
###### Motivation for this change

Software update

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tomfitzhenry** [comment]
@jslight90 , is this still WIP?

**Comment by jslight90** [comment]
> @jslight90 , is this still WIP?

No, I forgot to update it.  We have about 50 users and have been using 5.15.0 for about 2 months without any issues.

**Comment by bgamari** [comment]
It sounds like this can be merged.

**Review by ryantm — APPROVED** [review]

**Comment by nh2** [comment]
This version did not work for me: https://github.com/NixOS/nixpkgs/issues/89194#issuecomment-636238242

**Pull request merged**
