### PR TITLE
jetbrains: 2024.2.2 -> 2024.2.5

### PR DESCRIPTION
**Pull request by Kek5chen**
## Things done

Ran the updater for the jetbrains tools since some of them were outdated.

jetbrains.clion: 2024.2.2 -> 2024.2.3
jetbrains.ruby-mine: 2024.2.3 -> 2024.2.4
jetbrains.rust-rover: 2024.2.4 -> 2024.2.5
jetbrains.webstorm: 2024.2.4 -> 2024.3
jetbrains.writerside: 2024.2 EAP -> 2024.3 EAP

and a bunch of plugins.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by JohnRTitor — APPROVED** [review]

**Comment by JohnRTitor** [comment]
Hi, you don't *need* to self assign it to indicate you are working on it or the task is set to be completed by you.

As a commiter, I need to look at tens of open PRs daily and I "assign myself" the ones I find I am willing to merge, after testing/building locally.

**Comment by p-rintz** [comment]
This PR renamed the github-copilot plugin to github-copilot-intellij.

Is there an alias that maybe should be placed somewhere?
Because this way current configs fail with an error, since the plugin "github-copilot" is no longer available.

**Comment by JohnRTitor** [comment]
I am not a jetbrains maintainer I am afraid, but since the update script did it it must be that it was changed upstream. 

Perhaps we can add a release notes to 24.11?

**Comment by Kek5chen** [comment]
@p-rintz honestly I think it's better to not create an alias. If in the future a plugin with the old name is created people would start installing that automatically or it wouldn't be available. If they changed it upstream, you have to adjust your configuration to the new definition.

**Comment by Krutonium** [comment]
@Kek5chen Would you be the person to ask to add https://plugins.jetbrains.com/plugin/25594-nix-lsp this plugin?

**Comment by Kek5chen** [comment]
> @Kek5chen Would you be the person to ask to add https://plugins.jetbrains.com/plugin/25594-nix-lsp this plugin?

It's a thing I can do yea. But opening an issue with a request would be more fitting, maybe do that and ping me so I have it on track.

**Pull request merged**
