### PR TITLE
 gscan2pdf: 2.9.1 -> 2.11.1

### PR DESCRIPTION
**Pull request by pacien**
###### Motivation for this change

This updates gscan2pdf to the latest available version, as well as introduce new and unbreak some existing Perl packages.
See individual commit messages for more details.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pacien** [comment]
CC @livnev because this PR solves #68115 and #68116 as well.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113732` at f87bcfb6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>51 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/24d6309209669b87e92e9d4c098248c4">fbmenugen</a></li></li>
    <li><a href="https://gist.github.com/9c7ab40221ed3a9d824499c2fe05deeb">gcstar</a></li></li>
    <li><a href="https://gist.github.com/ee57c372ede142ad73e9bcb5bfdc124f">gscan2pdf</a></li></li>
    <li><a href="https://gist.github.com/bfc3ec00cb5d2656cb9b1813d08c4b9e">pcsctools</a></li></li>
    <li><a href="https://gist.github.com/3c785b91bbaa9b1fbc983b17f4d90af9">perl530Packages.CairoGObject</a></li></li>
    <li><a href="https://gist.github.com/5dd8ebb6c27a8c5383950c1ebdbe794d">perl530Packages.Glib</a></li></li>
    <li><a href="https://gist.github.com/90a1264f19419e00c245f60a24dfc94e">perl530Packages.GlibObjectIntrospection</a></li></li>
    <li><a href="https://gist.github.com/fbeea42722174df729a75fbff7414efc">perl530Packages.Gnome2</a></li></li>
    <li><a href="https://gist.github.com/0cfda0b8d7face5cc0398d6c776a01d1">perl530Packages.Gnome2Canvas</a></li></li>
    <li><a href="https://gist.github.com/cd9ce1c92738e4b0a8c79858f17ca83d">perl530Packages.Gnome2VFS</a></li></li>
    <li><a href="https://gist.github.com/2d46cb07bb416e3b3630f0136f424b1e">perl530Packages.Gnome2Wnck</a></li></li>
    <li><a href="https://gist.github.com/e88b7dd2a672d9d1d4b41ddbe7faf1be">perl530Packages.GooCanvas</a></li></li>
    <li><a href="https://gist.github.com/6c427c0ac65d1b7e6a6155f728b2b257">perl530Packages.GooCanvas2</a></li></li>
    <li><a href="https://gist.github.com/5e8738a5fcda27f75fd5ff42a1224c44">perl530Packages.GraphicsTIFF</a></li></li>
    <li><a href="https://gist.github.com/b6fc6c32dba5c2232350dafda1827614">perl530Packages.Gtk2</a></li></li>
    <li><a href="https://gist.github.com/170b3b981858c0590914a533a78c1496">perl530Packages.Gtk2AppIndicator</a></li></li>
    <li><a href="https://gist.github.com/e7ed2d4101c8cf0043ecae9285997a48">perl530Packages.Gtk2GladeXML</a></li></li>
    <li><a href="https://gist.github.com/a864ea01892df7cf9ef680f0fe1b4833">perl530Packages.Gtk2ImageView</a></li></li>
    <li><a href="https://gist.github.com/ae277ff48a68ad7461a39d9ad0b49bed">perl530Packages.Gtk2TrayIcon</a></li></li>
    <li><a href="https://gist.github.com/057388bf577312590e6aaccf17c35e6e">perl530Packages.Gtk2Unique</a></li></li>
    <li><a href="https://gist.github.com/9ad83d5d14860f5ba961487fe9cf716f">perl530Packages.Gtk3</a></li></li>
    <li><a href="https://gist.github.com/f43523db3f7b53554fb6c8aeda3a4244">perl530Packages.Gtk3ImageView</a></li></li>
    <li><a href="https://gist.github.com/67030c19064475886a386c628083c8ad">perl530Packages.Gtk3SimpleList</a></li></li>
    <li><a href="https://gist.github.com/9748a9584937980790eb1f93e174f6f2">perl530Packages.ImagePNGLibpng</a></li></li>
    <li><a href="https://gist.github.com/6992f340903a43c3cc945aeaaecfb342">perl530Packages.PDFBuilder</a></li></li>
    <li><a href="https://gist.github.com/4ddac46da6d27c83ef49e327f885b9d7">perl530Packages.Pango</a></li></li>
    <li><a href="https://gist.github.com/2df03542cc81343d67854a177e9e454f">perl532Packages.CairoGObject</a></li></li>
    <li><a href="https://gist.github.com/64e3c8e1f9704635a50f16ca5028b7af">perl532Packages.Glib</a></li></li>
    <li><a href="https://gist.github.com/0d493a3f4367d2280c2f635b6ce13307">perl532Packages.GlibObjectIntrospection</a></li></li>
    <li><a href="https://gist.github.com/68e4ce0f9becef15bc5f9b97004c76f7">perl532Packages.Gnome2</a></li></li>
    <li><a href="https://gist.github.com/03f3469967d666ab6954982437fd5c45">perl532Packages.Gnome2Canvas</a></li></li>
    <li><a href="https://gist.github.com/4e07a6f5ee7b2bc32754c103f387781f">perl532Packages.Gnome2VFS</a></li></li>
    <li><a href="https://gist.github.com/66886636e0681a35b502f53928574fe7">perl532Packages.Gnome2Wnck</a></li></li>
    <li><a href="https://gist.github.com/ebf0ba380725435ab82b9a77b92869b0">perl532Packages.GooCanvas</a></li></li>
    <li><a href="https://gist.github.com/dafa6bd6d6ec40c2aacab66ce027d780">perl532Packages.GooCanvas2</a></li></li>
    <li><a href="https://gist.github.com/3c535073e84cf8d571134261de1eb86e">perl532Packages.GraphicsTIFF</a></li></li>
    <li><a href="https://gist.github.com/361fc014e9debbad56d60141a4a82600">perl532Packages.Gtk2</a></li></li>
    <li><a href="https://gist.github.com/59d96eda9e6b4e623259708a58b5522d">perl532Packages.Gtk2AppIndicator</a></li></li>
    <li><a href="https://gist.github.com/6f12d32125bc4a4218783b9ead8a799a">perl532Packages.Gtk2GladeXML</a></li></li>
    <li><a href="https://gist.github.com/2b2033553af1e50c1a1ca333b989a361">perl532Packages.Gtk2ImageView</a></li></li>
    <li><a href="https://gist.github.com/7372eddad59436554a800f3dff36c6f7">perl532Packages.Gtk2TrayIcon</a></li></li>
    <li><a href="https://gist.github.com/afe2a5aa203d65e583a6382bb63feeb9">perl532Packages.Gtk2Unique</a></li></li>
    <li><a href="https://gist.github.com/c064bb4a4bb1915515b43907c031e271">perl532Packages.Gtk3</a></li></li>
    <li><a href="https://gist.github.com/3e672260c4861f20abde3fda1469c622">perl532Packages.Gtk3ImageView</a></li></li>
    <li><a href="https://gist.github.com/c1c6cf452f35a3d91656def47a15f0b9">perl532Packages.Gtk3SimpleList</a></li></li>
    <li><a href="https://gist.github.com/2b3608b919ff3d0e2ef2bda17289167e">perl532Packages.ImagePNGLibpng</a></li></li>
    <li><a href="https://gist.github.com/ef6917d389dc59530a237aaec4e1b545">perl532Packages.PDFBuilder</a></li></li>
    <li><a href="https://gist.github.com/de101aa49f9a59aebe2855923987102d">perl532Packages.Pango</a></li></li>
    <li><a href="https://gist.github.com/006a258f515b8aa03c81ae7d2544cd79">remotebox</a></li></li>
    <li><a href="https://gist.github.com/88d357c451f27ced5e64d7f897b733a6">shutter</a></li></li>
    <li><a href="https://gist.github.com/6acb4890cd153868846f37b610ccb7ba">yarssr</a></li></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113732` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
51 packages built:
</summary>
<ul>
<li>fbmenugen</li>
<li>gcstar</li>
<li>gscan2pdf</li>
<li>pcsctools</li>
<li>perl530Packages.CairoGObject</li>
<li>perl530Packages.Glib</li>
<li>perl530Packages.GlibObjectIntrospection</li>
<li>perl530Packages.Gnome2</li>
<li>perl530Packages.Gnome2Canvas</li>
<li>perl530Packages.Gnome2VFS</li>
<li>perl530Packages.Gnome2Wnck</li>
<li>perl530Packages.GooCanvas</li>
<li>perl530Packages.GooCanvas2</li>
<li>perl530Packages.GraphicsTIFF</li>
<li>perl530Packages.Gtk2</li>
<li>perl530Packages.Gtk2AppIndicator</li>
<li>perl530Packages.Gtk2GladeXML</li>
<li>perl530Packages.Gtk2ImageView</li>
<li>perl530Packages.Gtk2TrayIcon</li>
<li>perl530Packages.Gtk2Unique</li>
<li>perl530Packages.Gtk3</li>
<li>perl530Packages.Gtk3ImageView</li>
<li>perl530Packages.Gtk3SimpleList</li>
<li>perl530Packages.ImagePNGLibpng</li>
<li>perl530Packages.PDFBuilder</li>
<li>perl530Packages.Pango</li>
<li>perl532Packages.CairoGObject</li>
<li>perl532Packages.Glib</li>
<li>perl532Packages.GlibObjectIntrospection</li>
<li>perl532Packages.Gnome2</li>
<li>perl532Packages.Gnome2Canvas</li>
<li>perl532Packages.Gnome2VFS</li>
<li>perl532Packages.Gnome2Wnck</li>
<li>perl532Packages.GooCanvas</li>
<li>perl532Packages.GooCanvas2</li>
<li>perl532Packages.GraphicsTIFF</li>
<li>perl532Packages.Gtk2</li>
<li>perl532Packages.Gtk2AppIndicator</li>
<li>perl532Packages.Gtk2GladeXML</li>
<li>perl532Packages.Gtk2ImageView</li>
<li>perl532Packages.Gtk2TrayIcon</li>
<li>perl532Packages.Gtk2Unique</li>
<li>perl532Packages.Gtk3</li>
<li>perl532Packages.Gtk3ImageView</li>
<li>perl532Packages.Gtk3SimpleList</li>
<li>perl532Packages.ImagePNGLibpng</li>
<li>perl532Packages.PDFBuilder</li>
<li>perl532Packages.Pango</li>
<li>remotebox</li>
<li>shutter</li>
<li>yarssr</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
gcstar:
<details>


perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/misc/gcstar/default.nix:20:3:

```
   |
20 |   buildInputs = with perlPackages; [
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md
</details>
pcsctools:
<details>


Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/security/pcsctools/default.nix:34:5:

```
   |
34 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/tools/security/pcsctools/default.nix:15:3:

```
   |
15 |   buildInputs = [ udev dbus perlPackages.perl pcsclite ];
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md
</details>
remotebox:
<details>


Package does not have a maintainer. Consider adding yourself?

Near pkgs/applications/virtualization/remotebox/default.nix:28:3:

```
   |
28 |   meta = with lib; {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/virtualization/remotebox/default.nix:12:3:

```
   |
12 |   buildInputs = with perlPackages; [ perl Glib Gtk2 Pango SOAPLite ];
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md
`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/virtualization/remotebox/default.nix:15:3:

```
   |
15 |   installPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>
shutter:
<details>


perl is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/graphics/shutter/default.nix:25:3:

```
   |
25 |   buildInputs = [ perlPackages.perl procps gdk-pixbuf librsvg ] ++ perlModules;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md
`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/graphics/shutter/default.nix:27:3:

```
   |
27 |   installPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>
yarssr:
<details>


`gpl1` is a deprecated license, check if project uses `gpl1Plus` or `gpl1Only` and change `meta.license` accordingly.

Near pkgs/applications/misc/yarssr/default.nix:60:5:

```
   |
60 |     license = licenses.gpl1;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/misc/yarssr/default.nix:41:3:

```
   |
41 |   installPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>
</details>

**Review by stigtsp — APPROVED** [review]
LGTM

**Comment by stigtsp** [comment]
@pacien Thx for the contributions!

**Pull request merged**
