### PR TITLE
zfs: 2.0.2 -> 2.0.3

### PR DESCRIPTION
**Pull request by hmenke**
###### Motivation for this change

New upstream release: https://github.com/openzfs/zfs/releases/tag/zfs-2.0.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 112910` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>linuxPackages-libre.zfs</li>
    <li>linuxPackages-libre.zfsUnstable</li>
    <li>linuxPackages_latest-libre.zfs</li>
    <li>linuxPackages_latest-libre.zfsUnstable</li>
    <li>samba4Full</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>libvmi</li>
  </ul>
</details>
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome3.gnome-boxes</li>
    <li>libceph</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>linuxPackages.zfs (linuxPackages.zfsUnstable)</li>
    <li>linuxPackages_4_14.zfs (linuxPackages_4_14.zfsUnstable)</li>
    <li>linuxPackages_4_19.zfs (linuxPackages_4_19.zfsUnstable)</li>
    <li>linuxPackages_4_4.zfs (linuxPackages_4_4.zfsUnstable)</li>
    <li>linuxPackages_4_9.zfs (linuxPackages_4_9.zfsUnstable)</li>
    <li>linuxPackages_5_10.zfs (linuxPackages_5_10.zfsUnstable)</li>
    <li>linuxPackages_hardened.zfs (linuxPackages_hardened.zfsUnstable)</li>
    <li>linuxPackages_latest_hardened.zfs (linuxPackages_latest_hardened.zfsUnstable)</li>
    <li>linuxPackages_latest_xen_dom0.zfs (linuxPackages_latest_xen_dom0.zfsUnstable)</li>
    <li>linuxPackages_latest_xen_dom0_hardened.zfs (linuxPackages_latest_xen_dom0_hardened.zfsUnstable)</li>
    <li>linuxPackages_lqx.zfs (linuxPackages_lqx.zfsUnstable)</li>
    <li>linuxPackages_testing_bcachefs.zfs (linuxPackages_testing_bcachefs.zfsUnstable)</li>
    <li>linuxPackages_xen_dom0.zfs (linuxPackages_xen_dom0.zfsUnstable)</li>
    <li>linuxPackages_xen_dom0_hardened.zfs (linuxPackages_xen_dom0_hardened.zfsUnstable)</li>
    <li>linuxPackages_zen.zfs (linuxPackages_zen.zfsUnstable)</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixopsUnstable</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>python37Packages.guestfs</li>
    <li>python37Packages.libvirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>qemu_full</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_2_5.ruby-libvirt</li>
    <li>rubyPackages_2_7.ruby-libvirt</li>
    <li>sanoid</li>
    <li>terraform-full</li>
    <li>terraform-provider-libvirt (terraform-providers.libvirt)</li>
    <li>vagrant</li>
    <li>virtmanager (virt-manager)</li>
    <li>virtmanager-qt (virt-manager-qt)</li>
    <li>virt-top</li>
    <li>virtviewer (virt-viewer)</li>
    <li>virtlyst</li>
    <li>zfs (zfsUnstable)</li>
    <li>zfstools</li>
  </ul>
</details>

**Comment by hmenke** [comment]
@jonringer I'm using `kernelAtLeast` and `kernelOlder` now to mark ZFS broken on unsupported kernels (supported are 3.10 to 5.10).  What do you think?

**Comment by hmenke** [comment]
@ofborg test zfs.stable zfs.unstable

**Comment by jonringer** [comment]
> @jonringer I'm using `kernelAtLeast` and `kernelOlder` now to mark ZFS broken on unsupported kernels (supported are 3.10 to 5.10). What do you think?

LGTM

**Comment by wizeman** [comment]
I can't easily tell if the kernel compatibility changes are correct, but we should merge 2.0.3 ASAP because 2.0.2 has a serious data corruption issue: https://github.com/openzfs/zfs/issues/11474 https://github.com/openzfs/zfs/pull/11576

**Comment by hmenke** [comment]
In that case we also need a backport.

**Comment by jonringer** [comment]
tests passed

**Pull request merged**
