### PR TITLE
assimp: 5.1.3 → 5.2.5

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stephank** [comment]
Result of `nixpkgs-review pr 209740` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>assimp</li>
    <li>qt6.qt3d (qt6Packages.qt3d)</li>
  </ul>
</details>

While this builds, the `assimp` binary is no longer there. The `lib` output is fine, but the `out` output is empty. Is that expected / also the case on Linux?

**Comment by fabianhjr** [comment]
> Result of `nixpkgs-review pr 209740` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 2 packages built:
> 
> While this builds, the `assimp` binary is no longer there. The `lib` output is fine, but the `out` output is empty. Is that expected / also the case on Linux?

Unsure, it was a version bump due to https://github.com/NixOS/nixpkgs/pull/206907 and only checked compilation.

**Comment by stephank** [comment]
That didn't make a difference, but I tried a Linux build in a VM and it also no longer has the binary.

It looks like the binaries were disabled by default in this commit: https://github.com/assimp/assimp/commit/eee6269cd15b717a6ba6389636e463f03f0c1549

Seems from the linked issue it was a Windows-specific change. Maybe we can re-enable it in our builds?

```
cmakeFlags = [ "-DASSIMP_BUILD_ASSIMP_TOOLS=ON" ];
```

I tried Linux and Darwin builds with this flag, and both produce working binaries.

**Comment by fabianhjr** [comment]
Thanks for looking into it

```
/nix/store/7k7qadw5ikffxg44dh76zvhr7sv4g2ng-assimp-5.2.5
└── bin
    └── assimp
```

**Review by stephank — APPROVED** [review]

**Pull request merged**
