### PR TITLE
mujoco: 3.1.5 -> 3.1.6

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Note: I have pinned the version of the python module to the one of the main package.

cc @samuela @tmplt 

Changelog: https://mujoco.readthedocs.io/en/latest/changelog.html#version-3-1-6-jun-3-2024

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317365` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages marked as broken and skipped:</summary>
  <ul>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317365` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages marked as broken and skipped:</summary>
  <ul>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317365` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317365` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
  </ul>
</details>

**Comment by tmplt** [comment]
No comments on changes, but perhaps add self to list of maintainers? I haven't worked with mujoco as of recent.

I've been thinking about how we manage the pinned deps. Very manual process to check if they are updated. Easy to miss a change. Is it feasible to extract the revs from the source? I'd imagine listing these in a dedicated file rather than inline throughout CMake scripts would be beneficial. Perhats that can be argued for upstream.

**Comment by GaetanLepage** [comment]
> No comments on changes, but perhaps add self to list of maintainers? I haven't worked with mujoco as of recent.

Done.



> I've been thinking about how we manage the pinned deps. Very manual process to check if they are updated. Easy to miss a change. Is it feasible to extract the revs from the source? I'd imagine listing these in a dedicated file rather than inline throughout CMake scripts would be beneficial. Perhats that can be argued for upstream.

I agree, this is quite annoying. There was no change in the deps for this specific update.
Sure, there might be a better way. However, the releases don't happen too often so I don't mind checking.

**Comment by tmplt** [comment]
Additionally (and just to put it down on paper): we should consider building the Python package from source, instead of the pypi tarball.

I'll create an issue for these improvement points and CC.

**Review by samuela — APPROVED** [review]
diff lgtm

**Comment by samuela** [comment]
> I agree, this is quite annoying. There was no change in the deps for this specific update.
Sure, there might be a better way. However, the releases don't happen too often so I don't mind checking.

To this end, perhaps we should add a comment to the derivation (somewhere around `version`) to point out this TODO item when updating.

**Comment by GaetanLepage** [comment]
> To this end, perhaps we should add a comment to the derivation (somewhere around `version`) to point out this TODO item when updating.

Done

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317365` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
  </ul>
</details>

**Comment by pbsds** [comment]
torchrl is annoyingly flaky, https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python311Packages.torchrl.x86_64-linux

LGTM

**Comment by GaetanLepage** [comment]
> Result of `nixpkgs-review pr 317365` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

Interesting... How is torchrl failing on your end ?

**Comment by pbsds** [comment]
It gets stuck and times out when running tests

**Comment by pbsds** [comment]
please view https://github.com/NixOS/nixpkgs/pull/317953

**Pull request merged**
