### PR TITLE
buildGoModule: backport the new Go infrastructure to release 19.03

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

This pull request backports #57080 into release 19.03. #57080 provides a new infrastructure for packaging Go modules without the need to manually package the dependencies. It relies instead on Go's module reproducibility and versioning to compute the dependencies in the early stage of the build.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @NixOS/backports

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build jx pet hugo gotools terminal-parrot todoist hetzner-kube mod

**Comment by lheckemann** [comment]
Why would we need to backport this? It's a breaking change that AFAIU doesn't fix any major functionality or security bugs.

**Comment by kalbasit** [comment]
@lheckemann it's not a breaking change, but instead a new feature. It does make packaging Go modules a lot easier than it currently is. The legacy `buildGoPackage` remains unchanged.

**Comment by Mic92** [comment]
@kalbasit for the backport it might be better to skip migration of existing packages and only backport the function itself.

**Comment by kalbasit** [comment]
@Mic92 sure, I've rebased my pull request and left only commits directly related to `buildGoModule`.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
