### PR TITLE
python3Packages.cirq-core: fix build on aarch64 

### PR DESCRIPTION
**Pull request by sveitser**
## Description of changes

- Skip failing test on aarch64.
- Enable tests that no longer fail.
- Remove broken marker for aarch64-linux.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build python3Packages.cirq-core

**Review by ghost — COMMENTED** [review]
wonder why the new test is failing,  does it fail for linux aarch64 too?


stim failure is unrelated:
```
FAILED glue/zx/stimzx/_text_diagram_parsing_test.py::test_from_text_diagram - AttributeError: module 'networkx' has no attribute 'testing'
```

Result of `nixpkgs-review pr 269945` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.stim</li>
    <li>python310Packages.stim.dist</li>
    <li>python311Packages.stim</li>
    <li>python311Packages.stim.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>python310Packages.cirq</li>
    <li>python310Packages.cirq-aqt</li>
    <li>python310Packages.cirq-aqt.dist</li>
    <li>python310Packages.cirq-core</li>
    <li>python310Packages.cirq-core.dist</li>
    <li>python310Packages.cirq-ft</li>
    <li>python310Packages.cirq-ft.dist</li>
    <li>python310Packages.cirq-google</li>
    <li>python310Packages.cirq-google.dist</li>
    <li>python310Packages.cirq-ionq</li>
    <li>python310Packages.cirq-ionq.dist</li>
    <li>python310Packages.cirq-pasqal</li>
    <li>python310Packages.cirq-pasqal.dist</li>
    <li>python310Packages.cirq-rigetti</li>
    <li>python310Packages.cirq-rigetti.dist</li>
    <li>python310Packages.cirq-web</li>
    <li>python310Packages.cirq-web.dist</li>
    <li>python310Packages.cirq.dist</li>
    <li>python311Packages.cirq</li>
    <li>python311Packages.cirq-aqt</li>
    <li>python311Packages.cirq-aqt.dist</li>
    <li>python311Packages.cirq-core</li>
    <li>python311Packages.cirq-core.dist</li>
    <li>python311Packages.cirq-ft</li>
    <li>python311Packages.cirq-ft.dist</li>
    <li>python311Packages.cirq-google</li>
    <li>python311Packages.cirq-google.dist</li>
    <li>python311Packages.cirq-ionq</li>
    <li>python311Packages.cirq-ionq.dist</li>
    <li>python311Packages.cirq-pasqal</li>
    <li>python311Packages.cirq-pasqal.dist</li>
    <li>python311Packages.cirq-rigetti</li>
    <li>python311Packages.cirq-rigetti.dist</li>
    <li>python311Packages.cirq-web</li>
    <li>python311Packages.cirq-web.dist</li>
    <li>python311Packages.cirq.dist</li>
  </ul>
</details>

<hr>

Result of `nixpkgs-review pr 269945` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.stim</li>
    <li>python310Packages.stim.dist</li>
    <li>python311Packages.stim</li>
    <li>python311Packages.stim.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>python310Packages.cirq</li>
    <li>python310Packages.cirq-aqt</li>
    <li>python310Packages.cirq-aqt.dist</li>
    <li>python310Packages.cirq-core</li>
    <li>python310Packages.cirq-core.dist</li>
    <li>python310Packages.cirq-ft</li>
    <li>python310Packages.cirq-ft.dist</li>
    <li>python310Packages.cirq-google</li>
    <li>python310Packages.cirq-google.dist</li>
    <li>python310Packages.cirq-ionq</li>
    <li>python310Packages.cirq-ionq.dist</li>
    <li>python310Packages.cirq-pasqal</li>
    <li>python310Packages.cirq-pasqal.dist</li>
    <li>python310Packages.cirq-rigetti</li>
    <li>python310Packages.cirq-rigetti.dist</li>
    <li>python310Packages.cirq-web</li>
    <li>python310Packages.cirq-web.dist</li>
    <li>python310Packages.cirq.dist</li>
    <li>python311Packages.cirq</li>
    <li>python311Packages.cirq-aqt</li>
    <li>python311Packages.cirq-aqt.dist</li>
    <li>python311Packages.cirq-core</li>
    <li>python311Packages.cirq-core.dist</li>
    <li>python311Packages.cirq-ft</li>
    <li>python311Packages.cirq-ft.dist</li>
    <li>python311Packages.cirq-google</li>
    <li>python311Packages.cirq-google.dist</li>
    <li>python311Packages.cirq-ionq</li>
    <li>python311Packages.cirq-ionq.dist</li>
    <li>python311Packages.cirq-pasqal</li>
    <li>python311Packages.cirq-pasqal.dist</li>
    <li>python311Packages.cirq-rigetti</li>
    <li>python311Packages.cirq-rigetti.dist</li>
    <li>python311Packages.cirq-web</li>
    <li>python311Packages.cirq-web.dist</li>
    <li>python311Packages.cirq.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`stim` is already failing on master.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 269945` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.stim</li>
    <li>python310Packages.stim.dist</li>
    <li>python311Packages.stim</li>
    <li>python311Packages.stim.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>python310Packages.cirq</li>
    <li>python310Packages.cirq-aqt</li>
    <li>python310Packages.cirq-aqt.dist</li>
    <li>python310Packages.cirq-core</li>
    <li>python310Packages.cirq-core.dist</li>
    <li>python310Packages.cirq-ft</li>
    <li>python310Packages.cirq-ft.dist</li>
    <li>python310Packages.cirq-google</li>
    <li>python310Packages.cirq-google.dist</li>
    <li>python310Packages.cirq-ionq</li>
    <li>python310Packages.cirq-ionq.dist</li>
    <li>python310Packages.cirq-pasqal</li>
    <li>python310Packages.cirq-pasqal.dist</li>
    <li>python310Packages.cirq-rigetti</li>
    <li>python310Packages.cirq-rigetti.dist</li>
    <li>python310Packages.cirq-web</li>
    <li>python310Packages.cirq-web.dist</li>
    <li>python310Packages.cirq.dist</li>
    <li>python311Packages.cirq</li>
    <li>python311Packages.cirq-aqt</li>
    <li>python311Packages.cirq-aqt.dist</li>
    <li>python311Packages.cirq-core</li>
    <li>python311Packages.cirq-core.dist</li>
    <li>python311Packages.cirq-ft</li>
    <li>python311Packages.cirq-ft.dist</li>
    <li>python311Packages.cirq-google</li>
    <li>python311Packages.cirq-google.dist</li>
    <li>python311Packages.cirq-ionq</li>
    <li>python311Packages.cirq-ionq.dist</li>
    <li>python311Packages.cirq-pasqal</li>
    <li>python311Packages.cirq-pasqal.dist</li>
    <li>python311Packages.cirq-rigetti</li>
    <li>python311Packages.cirq-rigetti.dist</li>
    <li>python311Packages.cirq-web</li>
    <li>python311Packages.cirq-web.dist</li>
    <li>python311Packages.cirq.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`stim` will be fixed with #272237

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
