### PR TITLE
systemd user services shouldn't run as root and other "non-interactive" users

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Previously, if root logged in to the console while ```services.kbfs.enable = true;```, systemd would try to spawn the kbfs and keybase units which is probably not what we want.

Since systemd 234 we have been able to specify that a unit should only run for specific users or alternatively "not for system users" which is what this PR does.

As this is a change in existing behaviour, I thought it best to see if anybody would have any issues with this.

Cc:  @carlsverre @np @rvolosatovs @bennofs @fpletz @nequissimus 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edolstra** [comment]
It's debatable whether root should be a non-interactive user. For example, `nixops ssh` logs in as root by default.

**Comment by peterhoeg** [comment]
By "non-interactive" I meant "not a human doing general purpose stuff". I'm not sure if having ```ssh-agent``` running as root has its uses but keybase/kbfs definitely shouldn't be running.

In any case, this PR doesn't change anything about the definition of root - it only disables the 3 mentioned user units for root

**Comment by rvolosatovs** [comment]
I'd say this should be configurable.

**Comment by fpletz** [comment]
There are even more user services where this change would be useful. For instance, btsync, gpg-agent and pulseaudio. Maybe we should give each user service an extra option to set for which users the service is started. On the other hand we do have `ConditionUser` which can be overridden in any NixOS config but this is an implementation detail.

For most user services I agree that it doesn't make much sense to run them as root or other non-interactive users. I think this should be the default for all our user services.

**Review by fpletz — APPROVED** [review]

**Comment by peterhoeg** [comment]
@edolstra - do you still have reservations about this PR?

**Comment by peterhoeg** [comment]
@rvolosatovs you said:

> I'd say this should be configurable

You're saying that we should be able to define per service if it should run for root as well or a global switch of some kind? Can you share some details on your specific use case?

**Comment by rvolosatovs** [comment]
What I had in mind was having something like `runAsRoot` boolean option, or, even better, similar to what @fpletz proposed having something like a `users` option, where you could define the users to run the service for, or, other way round, having a `services` option in user definition, where the services, that should run would be cofigured.
Another idea was that maybe it could be abstracted somehow... like being able to specify non-interactive users, for whom "interactive" services would not get started.

By the way, shouldn't all `systemd.user.services` only run for non-root users anyway?

**Comment by peterhoeg** [comment]
> having something like a users option, where you could define the users to run the service for

That makes sense, but is really just the mechanics of it. What would be the use case for running ```syncthing``` or ```keybase``` as root?

> By the way, shouldn't all systemd.user.services only run for non-root users anyway?

That's what I would say although services ```wantedBy = [ "graphical-session.target" ];``` do not require handling as that target should never be started by root in the first place.

**Comment by mmahut** [comment]
Any update on this pull request?

**Comment by peterhoeg** [comment]
This is safe to merge - the 3 mentioned services should not run as root.

**Pull request merged**
