### PR TITLE
tvnamer: move out of python3Packages and fix requests-cache dependency

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

tvdb_api 3.1.0 doesn't work with our requests-cache so use an older version

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Python packages are not allowed to override their Python dependencies.
Tvnamer seems to be an application though. It should be moved out of `pythonPackages`, use `buildPythonApplication, and override requests-cache using `packageOverrides`.

**Comment by peterhoeg** [comment]
Thanks @dotlambda  - fixed.

**Comment by dotlambda** [comment]
Please add a line in `pkgs/top-level/python-aliases.nix` and choose a more appropriate commit message.

**Comment by peterhoeg** [comment]
In principle, the removal of a python module warrants the addition of an alias but I doubt this was ever used as such so it seems rather pointless. Or am I missing something?

**Comment by dotlambda** [comment]
I would say it's just a thing we always do.

**Pull request merged**
