### PR TITLE
[WIP] Build nixpkgs with gcc 8 by default

### PR DESCRIPTION
**Pull request by vcunat**
Reopened https://github.com/NixOS/nixpkgs/pull/53760

### CODE REVIEW

**Comment by vcunat** [comment]
Unfortunately it will need some work, probably a rebase after the months.

**Comment by fpletz** [comment]
@vcunat Do you intend to work in this? Otherwise I'd like to try to do the rebase.

**Comment by vcunat** [comment]
I do not, at least not immediately.

**Comment by fpletz** [comment]
Rebased. Here is the jobset on Hydra: https://hydra.nixos.org/jobset/nixpkgs/gcc8

**Comment by vcunat** [comment]
BTW, gcc 9 should be already viable as well.  Whole Fedora [has switched](https://fedoraproject.org/wiki/Changes/GCC9) months ago.  Still, it might be easier to do these steps separately, for better grouping of similar problems.

**Comment by tobim** [comment]
I'd like to help with this PR, I hope there is still a chance for 19.09.
Here is a cutout of the most problematic dependencies (generated with [eval-report](https://github.com/samueldr/nix-review-tools)):

name | count
-- | --
aarch64-linux llvm-7.1.0 | 4491
x86_64-linux qtscript-5.12.0 | 444
aarch64-linux perl5.30.0-B-C-1.55 | 330
x86_64-linux qt-4.8.7 | 229
aarch64-linux linux-4.19.51-libre-src | 81
aarch64-linux xapian-1.4.11 | 68
aarch64-linux linux-5.2-rc4 | 64
x86_64-linux qtscript-5.11.3 | 48
aarch64-linux python2.7-httpretty-0.9.6 | 39
aarch64-linux linux-4.9.181 | 28
aarch64-linux linux-4.4.181 | 27
aarch64-linux python3.7-Faker-1.0.7 | 17
aarch64-linux python3.7-notebook-5.7.8 | 15
x86_64-linux python3.7-scikit-learn-0.20.3 | 15
aarch64-linux buildbot_www-2.3.1-py3-none-any.whl | 14
x86_64-linux xen-4.8.3 | 14
x86_64-linux gmime-3.2.3 | 13
aarch64-linux libc++abi-7.1.0 | 12
aarch64-linux llvm-3.8.1 | 12
x86_64-linux python2.7-Faker-1.0.7 | 10
x86_64-linux arrow-cpp-0.13.0 | 10
aarch64-linux epson-inkjet-printer-escpr2-1.0.29-1lsb3.2.src.rpm | 10
aarch64-linux python3.7-pycurl-7.43.0.2 | 10
x86_64-linux cwrap-5.1 | 6
aarch64-linux llvm-4.0.1 | 6
aarch64-linux ucto-v0.9.6 | 5
aarch64-linux buildbot-grid-view-2.3.1.tar.gz | 5
aarch64-linux buildbot-waterfall-view-2.3.1.tar.gz | 5
aarch64-linux nlohmann_json-3.6.1 | 5
aarch64-linux sbcl-1.5.3 | 5

**Comment by tobim** [comment]
For qt4: we could reuse the AUR patch: https://aur.archlinux.org/cgit/aur.git/plain/qt4-gcc8.patch?h=qt4, or do `sed -i` in `postPatch`.
For qt5: 5.12 is fixed in patchlevel 2, latest is 4, we are at .0.
qt-5.11 and lower are not patched and need a similar patch as qt4.

**Comment by tobim** [comment]
llvm should already be fixed thanks to https://github.com/NixOS/nixpkgs/pull/63928.

**Comment by FRidh** [comment]
This is now in staging-next.
https://hydra.nixos.org/eval/1541002

**Comment by vcunat** [comment]
No, it isn't, at least not the current version e7297363c9 :-/  Bitten by the rebasing workflow?

**Comment by vcunat** [comment]
As I'm against history-rewriting on staging-next, I suggest we merge this commit to staging-next and have a careful look at the conflicts and the overall merge result.

**Comment by FRidh** [comment]
Seems we had a gcc8 and gcc-8 branch. I merged the gcc8 branch instead of this gcc-8.

**Comment by vcunat** [comment]
Bad luck; first GitHub decided it got merged even if it didn't, and now this naming confusion.

**Pull request merged**
