### PR TITLE
moltenvk: 1.1.10 -> 1.1.11

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

MoltenVK 1.1.11 changelog: https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.11

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 186705` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>vulkan-caps-viewer</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>ddnet</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>google-amber</li>
    <li>libplacebo</li>
    <li>ncnn</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>vkquake</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
    <li>wgpu-utils</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 186705` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>ddnet</li>
    <li>vulkan-caps-viewer</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>google-amber</li>
    <li>libplacebo</li>
    <li>ncnn</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>vkquake</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
    <li>wgpu-utils</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Neither ddnet nor vulkan-caps-viewer are regressions. ddnet is waiting on some SDK changes before I fix the build. I tried to get vulkan-caps-viewer to build, but it just hangs and continues to allocate memory without showing a window.

**Comment by Mic92** [comment]
@ofborg build darwin.moltenvk

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 186705` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages marked as broken and skipped:</summary>
  <ul>
    <li>airshipper</li>
    <li>ajour</li>
    <li>arcanPackages.arcan</li>
    <li>arcanPackages.xarcan</li>
    <li>beamerpresenter</li>
    <li>cutemaze</li>
    <li>fast-cli</li>
    <li>kaffeine</li>
    <li>lightly-qt</li>
    <li>mojave-gtk-theme</li>
    <li>pcsx2</li>
    <li>puppeteer-cli</li>
    <li>python310Packages.python-vlc</li>
    <li>python39Packages.python-vlc</li>
    <li>qt6Packages.quazip</li>
    <li>sharedown</li>
    <li>sway-contrib.grimshot</li>
    <li>vimix-gtk-themes</li>
    <li>waybar</li>
    <li>whitesur-gtk-theme</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vulkan-caps-viewer</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>darwin.moltenvk</li>
    <li>libplacebo</li>
    <li>vkquake</li>
    <li>vulkan-loader</li>
    <li>wgpu-utils</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
https://github.com/ofborg build darwin.moltenvk

**Comment by reckenrode** [comment]
@ofborg build darwin.moltenvk

**Comment by reckenrode** [comment]
Not sure why the build failed previously, but it looks like it built this time on both x86_64-darwin and aarch64-darwin, so all checks pass now. Before, it was failing to download one of the dependencies only on x86_64-darwin. The HTTP error was 503, so I assume it was a transient GitHub issue.

**Pull request merged**
