### PR TITLE
ddnet 18.1 -> 18.2 (plus one patch to workaround a libcurl problem)

### PR DESCRIPTION
**Pull request by atemp**
## Description of changes

https://ddnet.org/downloads/#18.2
https://github.com/ddnet/ddnet/compare/18.1...18.2

## Runtime libcurl problem and workaround

When testing if found out that there is a problem when comping 18.2 with the latest libcurl in NixOS unstable (8.7.1). This also happens if one builds 18.1 with this libcurl version.

The problem will lead to some libcurl downloads fail but not all. E.g. the flag status in ddnet server browser will not be updated anymore (easily testable by selecting a username with ddnet score 0 and pressing reload in server browser, flag status will stay the same - requires user with some solved maps to test).

Also there are some error messages in the log of the ddnet client, like:
```
2024-05-05 17:20:55 E http: https://master1.ddnet.org/ddnet/15/servers.json failed. libcurl error (23): 
```

I tracked it down and it seems that brotli is the problem. A very simple patch is added to this PR and will disable brotli for this release. ddnet works well with that path.

Sadly i can not fully reproduce this as the problem occurs with the ddnet master server which is not part of this package at all. So it is maybe a combination of the client and server libcurl versions and settings. I asked in ddnet discord bugs room, but no one had any idea.

A friend tested to compile ddnet on arch which uses libcurl 8.7.1 as well, no problems there.

Maybe anyone reading this PR got an idea what the problem might be. Also please advice if the patch is a solution clean enough to merge this or not .

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by shyim** [comment]
I encountered the same problem. Should we maybe directly patch curl? This commit is enough https://github.com/curl/curl/commit/b30d694a027eb771c02a3db0dee0ca03ccab7377

**Comment by shyim** [comment]
fyi: https://github.com/NixOS/nixpkgs/pull/306633

**Comment by atemp** [comment]
> fyi: #306633

oh nice, that means we better just wait until this hits unstable and then i will remove the patch from this PR?

**Review by Scrumplex — APPROVED** [review]

**Comment by atemp** [comment]
it seems the curl fix has not hit unstable yet, i thought is might be a side effect of 24.05 release (very uneducated guess..), so i was waiting for that

what about merging this version with the patch and remove the patch in a later update, when it is no longer needed?

**Comment by ncfavier** [comment]
The fix is in nixos-unstable AFAICT: you can track it [here](https://nixpk.gs/pr-tracker.html?pr=306633) and check that the patch is [there](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/networking/curl/8.7.1-compression-fix.patch).

**Comment by atemp** [comment]
thanks, that helped

the libcurl PR seems to hit unstable now and now it works w/o the workaround, so i removed it

this PR is now really small as usual and works great for me

**Comment by ncfavier** [comment]
Can we skip ahead to 18.3?

**Comment by atemp** [comment]
at first try 18.3 did not compile and right now i have no time to investigate that, so if it does not hurt, lets wait if someone else wants to check that (its something related to `-Werror=format-security`)

**Review by ncfavier — APPROVED** [review]

**Pull request merged**
