### PR TITLE
Update my packages

### PR DESCRIPTION
**Pull request by abbradar**
Checked everything locally; PR for check via Travis, just in case.

### CODE REVIEW

**Comment by abbradar** [comment]
Hm, `folly` builds for me. Do we consider successful `nix-build` with chroot enabled as a good enough test?

**Comment by lethalman** [comment]
Just push your own updates, as long as they don't cause mass rebuilds. Push only if each of them can be built with nix-build in chroot.

**Comment by abbradar** [comment]
Good, Travis worried me but I've tested all of them with nix-build. I'll just push then.

**Comment by vcunat** [comment]
Yes, chrooted builds tend to be more reliable than Travis ATM.

**Pull request merged**
