### PR TITLE
ffmpeg-full: add opencl

### PR DESCRIPTION
**Pull request by justinas**
###### Description of changes

Adds OpenCL support to ffmpeg-full. Tested indirectly via `jellyfin-ffmpeg`: OpenCL filters such as `tonemap_opencl` seem to work (given the GPU drivers are installed).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg eval

**Comment by risicle** [comment]
On macos 10.15, `olive-editor` fails with:

```
Undefined symbols for architecture x86_64:
  "_avcodec_find_encoder", referenced from:
      ExportDialog::add_codec_to_combobox(QComboBox*, AVCodecID) in exportdialog.o
      ExportDialog::vcodec_changed(int) in exportdialog.o
      ExportThread::SetupVideo() in exportthread.o
      ExportThread::SetupAudio() in exportthread.o
      ProxyGenerator::transcode(ProxyInfo const&) in proxygenerator.o
      AdvancedVideoDialog::AdvancedVideoDialog(QWidget*, AVCodecID, VideoCodecParams&) in advancedvideodialog.o
  "_avcodec_flush_buffers", referenced from:
      Cacher::CacheAudioWorker() in cacher.o
      Cacher::Reset() in cacher.o
      Cacher::CacheVideoWorker() in cacher.o
  "_avcodec_receive_packet", referenced from:
      ExportThread::Encode(AVFormatContext*, AVCodecContext*, AVFrame*, AVPacket*, AVStream*) in exportthread.o
      ProxyGenerator::transcode(ProxyInfo const&) in proxygenerator.o
  "_avcodec_send_frame", referenced from:
      ExportThread::Encode(AVFormatContext*, AVCodecContext*, AVFrame*, AVPacket*, AVStream*) in exportthread.o
      ProxyGenerator::transcode(ProxyInfo const&) in proxygenerator.o
ld: symbol(s) not found for architecture x86_64
```

cc @balsoft

**Comment by justinas** [comment]
FWIW, `olive-editor` is currently also failing on `master`, `x86_64-linux`, albeit seemingly due to different reasons. https://hydra.nixos.org/build/180812816

I do not own a Darwin machine so I can not help out much :slightly_frowning_face: The symbols seem to be there, but again, this is not Darwin:

```console
$ nm result/lib/libavcodec.so | grep -e avcodec_find_encoder -e avcodec_flush_buffers -e avcodec_receive_packet -e avcodec_send_frame
  17e780 T avcodec_find_encoder
  17e8c0 T avcodec_find_encoder_by_name
  1b2d70 T avcodec_flush_buffers
  2b8670 T avcodec_receive_packet
  2b83a0 T avcodec_send_frame
```

**Comment by risicle** [comment]
I checked this doesn't occur on master on this system.

**Comment by justinas** [comment]
Perhaps including the OpenCL framework would help for Darwin, a la

```patch
diff --git a/pkgs/development/libraries/ffmpeg-full/default.nix b/pkgs/development/libraries/ffmpeg-full/default.nix
index 408066f90cd..3d1dd99690e 100644
--- a/pkgs/development/libraries/ffmpeg-full/default.nix
+++ b/pkgs/development/libraries/ffmpeg-full/default.nix
@@ -149,6 +149,7 @@
  *  Darwin frameworks
  */
 , Cocoa, CoreAudio, CoreServices, AVFoundation, MediaToolbox
+, OpenCL
 , VideoDecodeAcceleration
 }:
 
@@ -445,6 +446,7 @@ stdenv.mkDerivation rec {
     ++ optional nvenc nv-codec-headers
     ++ optionals stdenv.isDarwin [ Cocoa CoreServices CoreAudio AVFoundation
                                    MediaToolbox VideoDecodeAcceleration
+                                   OpenCL
                                    libiconv ];
 
   buildFlags = [ "all" ]
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 280a79821a3..6dc76be40d4 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -17226,6 +17226,7 @@ with pkgs;
     vid-stab = if stdenv.isDarwin then null else vid-stab;
     inherit (darwin.apple_sdk.frameworks)
       Cocoa CoreServices CoreAudio AVFoundation MediaToolbox
+      OpenCL
       VideoDecodeAcceleration;
   };
 
```

**Comment by risicle** [comment]
Hmm no dice.

**Comment by risicle** [comment]
Hold on...

@ofborg build olive-editor

**Comment by risicle** [comment]
Ok ignore me I think I have some issues with my build machine. Orborg's happy with it.

**Pull request merged**
