### PR TITLE
jetbrains.*: also fetch source for aarch64-linux

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 249659` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by NickCao** [comment]
Nop as of now.

**Comment by tymscar** [comment]
I will review this in more detail tomorrow, but it should fix https://youtrack.jetbrains.com/issue/RUST-12127/Rust-rover-remote-server-needs-a-licence-but-I-cant-get-one

**Comment by wegank** [comment]
> I will review this in more detail tomorrow, but it should fix https://youtrack.jetbrains.com/issue/RUST-12127/Rust-rover-remote-server-needs-a-licence-but-I-cant-get-one

I don't think this is the case: this PR is purely about adding aarch64-linux sources, it doesn't even guarantee support for any product. `jetbrains.rust-rover` will probably fail for patching x86_64 binaries before this PR, and fail for not finding the x86_64-specific folder in the aarch64 tarball afterwards.

**Comment by wegank** [comment]
By the way, @tymscar, would you mind reviewing #246622?

**Comment by wegank** [comment]
Waiting for #260965 before rebasing and merging this PR.

**Comment by tymscar** [comment]
> > I will review this in more detail tomorrow, but it should fix https://youtrack.jetbrains.com/issue/RUST-12127/Rust-rover-remote-server-needs-a-licence-but-I-cant-get-one
> 
> I don't think this is the case: this PR is purely about adding aarch64-linux sources, it doesn't even guarantee support for Nix builds of any product. `jetbrains.rust-rover` will probably fail for being unable to patch x86_64 binaries before this PR, and fail for not finding the x86_64-specific folder in the aarch64 tarball afterwards.
> 
> https://github.com/NixOS/nixpkgs/blob/10a2d008cf8eafbf3069b8503a9d9bcbe3be0cad/pkgs/applications/editors/jetbrains/default.nix#L326-L347
> 
> FYI, there are no rebuilds on platforms other than aarch64-linux: https://gist.github.com/GrahamcOfBorg/d56cf79effd3294fbc84ceb6521b3f54

Oh, fair enough. I dont know about about that to be able to help

**Pull request merged**
