### PR TITLE
nim: include all supporting tools

### PR DESCRIPTION
**Pull request by peterhoeg**
This PR makes a few changes to how things are done:

a) build and install "koch" - the nim make-type tool
b) use "koch" to bootstrap nim
c) build additional supporting tools such as nimble, nimgrep and nimsuggest
d) nim can use other c compilers than gcc, so instead of forcing gcc we use the one from stdenv
e) run the full test suite

We do not need the "nimble" package any longer as it is part of nim

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
```
FAIL: client.nim --gc:boehm -d:useNimRtl
Test "tests/dll/client.nim" in category "dll"
Failure: reExitcodesDiffer
Expected:
exitcode: 0

Gotten:
exitcode: 1

Output:


PASS: nimrtl.nim -d:release --gc:boehm --app:lib -d:createNimRtl
PASS: server.nim -d:release --gc:boehm --app:lib -d:useNimRtl
FAIL: client.nim -d:release --gc:boehm -d:useNimRtl
Test "tests/dll/client.nim" in category "dll"
Failure: reExitcodesDiffer
Expected:
exitcode: 0

Gotten:
exitcode: 1

Output:


```

I get some testing failures. Is the version of boehm compatible with nim or does this error only happen on my machine?

**Comment by peterhoeg** [comment]
All the tests pass here (NixOS).

**Comment by 7c6f434c** [comment]
@Mic92 do the tests fail in the current build if you just add `doCheck = true;`?

**Comment by peterhoeg** [comment]
I don't think the tests can run in the current build as they require the "boch" make-style tool which we are only building with this PR.

**Comment by 7c6f434c** [comment]
A sandboxed x86_84 build has finished succesfully, but some tests have 
failed in the process without failing the build. I am running an x86 
build and there are already test failures and the test run continues, so
I expect the same outcome.

**Comment by Mic92** [comment]
@7c6f434c I actually did not complete the test run.

**Comment by 7c6f434c** [comment]
@Mic92  It is still a clear improvement to have a dozen of ignored test failures compared to being unable to run tests. I thought it breaks the build for you.

**Pull request merged**
