### PR TITLE
nixos/geoip-updater: remove

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

2019-01-01 MaxMind stopped distributing GeoIP v1 databases.
This service does not work since then and its presence in NixOS creates false confidence that the GeoIP databases are still being updated.
But they are not.

Fixing seems a bad option, because a fixed service would provide only GeoIP v2 and thus won't be a replacement for what the service was before and it would require all numerous services which use GeoIP database to update to newer MaxMind library (which is not backward compatible)

So, it would be better if the next service have a different name, for example ```nixos/geoip-v2-updater```.
And broken ```nixos/geoip-updater``` is to be gone to avoid confusions.

Related: https://github.com/NixOS/nixpkgs/issues/53953

### CODE REVIEW

**Comment by Infinisil** [comment]
Needs at least a `mkRemovedOption` for the removed options.

**Comment by danbst** [comment]
I've moved this module to my personal NUR

https://github.com/danbst/nur-packages/commit/5b5a99bce020c04feaef7a0338dadd240fe07557

In general, I agree that this breaks reproducibility in a hard way. And the part where database file is removed generates even more pain.

**Comment by aanderse** [comment]
@volth care to add `mkRemovedOption` so we can merge?

**Comment by dasJ** [comment]
Could be replacable with: https://dev.maxmind.com/geoip/geoipupdate/

**Comment by mmilata** [comment]
FYI even the GeoIPv2 databases will be unavailable starting 2020-01-01: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ You'll be able to get them for free but registration will be needed.

**Comment by dasJ** [comment]
@mmilata Do you know if we're still able to get them with #73767?

**Comment by mmilata** [comment]
@dasJ I think so, though the 0 accountID may stop working I guess?

**Pull request closed without merging**
