### PR TITLE
networkmanager: 1.22.4 -> 1.22.6

### PR DESCRIPTION
**Pull request by worldofpeace**
* also delete unused hardcode-gsettings patch

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/1.22.6/NEWS

###### Things done
Built on master.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
The patch is for network-manager-applet.

**Comment by worldofpeace** [comment]
> The patch is for network-manager-applet.

How funny I forget when I actually wrote the patch :rofl: 
I forced pushed to reorganize the directory.

**Comment by worldofpeace** [comment]
Now that I think of it, I don't need the hardcode patches anymore for wingpanel and switchboard,
* https://github.com/NixOS/nixpkgs/blob/a6e9b59633f4c1e615ff69a454720fb3350bd910/pkgs/desktops/pantheon/desktop/wingpanel/wrapper.nix#L28

**Review by jtojnar — APPROVED** [review]
LGTM.

**Comment by jtojnar** [comment]
IMHO they still make sense for other uses.

Also we should start thinking where we will place [libnma](https://gitlab.gnome.org/GNOME/libnma).

**Pull request merged**
