### PR TITLE
nixos/initrd-network: multiple DHCP fixes

### PR DESCRIPTION
**Pull request by volth**
* acquire DHCP on the interfaces with ```networking.interface.$name.useDHCP == true``` or on all interfaces if ```networking.useDHCP == true``` (was only "eth0", it is ```udhcpc```'s default behaviour)
 * respect ```mtu``` if it was in DHCP answer (it happens in the wild, on some hostings)
 * acquire and set up ```staticroutes``` (unlike others clients, ```udhcpc``` does not do the query by default); this supersedes https://github.com/NixOS/nixpkgs/pull/41829

Shortly, it makes ```initrd-network``` closer to network in stage-2
It fixes the practical cases where ```initrd-network``` has problems while stage-2 works well.

### CODE REVIEW

**Comment by volth** [comment]
> This needs backporting to 18.09

Yes, after review and approval.

There could be some issues found
And perhaps the sed-pipeline might be replaced with something more readable (but there is limited ```busybox```'s shell, not full ```bash```, so it was difficult to iterate over pairs, ```staticroutes``` is a string like "10.0.0.0/8 10.0.0.1 0.0.0.0/0 10.0.0.1", where the odd words are ```target```s and even are ```via```s)

**Comment by grahamc** [comment]
Feels scary to backport.

**Comment by volth** [comment]
I am using also a chunk of scary code to set up static addresses (to avoid dealing with kernel cmdline):
```
    setupStaticAddresses = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = lib.optionals (!config.networking.useDHCP) (
                  lib.flatten (lib.mapAttrsToList (dev: {ipv4, useDHCP, ...}:
                                                    if (builtins.match "eth[0-9]+|en[a-z0-9]+" dev) != null && useDHCP != true then # filter out "tinc.dmz", "eth0.4000", ...
                                                      (map ({address, prefixLength, ...}: "ip address add ${address}/${toString prefixLength} dev ${dev}") ipv4.addresses) ++
                                                      [ "ip link set ${dev} up" ]                                                                                          ++
                                                      (map ({address, prefixLength, ...}: "ip route   add ${address}/${toString prefixLength} dev ${dev}") ipv4.routes   )
                                                    else
                                                      []
                                                  )
                                                  config.networking.interfaces
                              ) ++
                  [
                    ( "ip route add default via ${config.networking.defaultGateway.address}"
                    + lib.optionalString (config.networking.defaultGateway.interface != null) " dev    ${         config.networking.defaultGateway.interface}"
                    + lib.optionalString (config.networking.defaultGateway.metric    != null) " metric ${toString config.networking.defaultGateway.metric   }"
                    )
                  ]
                );
    };
....

          ${lib.foldr (elt: acc: ''
              if ${elt}; then
                echo "INITRD-SSH:" ${lib.escapeShellArg elt}
                ${acc}
              else
                echo "INITRD-SSH:" ${lib.escapeShellArg elt} "failed with code $?"
              fi
          '') "" cfg.setupStaticAddresses}

```

And then DHCP part exactly as in the PR, so it is battle tested during more than month

**Comment by volth** [comment]
> This needs backporting to 18.09

It was not backported but it seems that people needs it in 18.09 (https://github.com/NixOS/nixpkgs/issues/50832)

**Pull request merged**
