### PR TITLE
riot-{web,desktop}: 1.3.3 -> 1.3.5

### PR DESCRIPTION
**Pull request by pacien**
###### Motivation for this change

Updating Riot to the latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @bachp @worldofpeace

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]
LGTM, works.

**Comment by worldofpeace** [comment]
Actually, shouldn't have yarndeps changed further https://github.com/vector-im/riot-web/compare/v1.3.5-rc.3...v1.3.5?

**Comment by pacien** [comment]
> Actually, shouldn't have yarndeps changed further [vector-im/riot-web@v1.3.5-rc.3...v1.3.5](https://github.com/vector-im/riot-web/compare/v1.3.5-rc.3...v1.3.5)?

No, `riot-web/electron_app/yarn.lock` hasn't changed between those releases.

**Comment by worldofpeace** [comment]
I meant shouldn't have https://github.com/pacien/nixpkgs/blob/e32515aa92b3982e26915175339444b4d0c6ef22/pkgs/applications/networking/instant-messengers/riot/riot-desktop-yarndeps.nix changed?

**Comment by pacien** [comment]
> I meant shouldn't have https://github.com/pacien/nixpkgs/blob/e32515aa92b3982e26915175339444b4d0c6ef22/pkgs/applications/networking/instant-messengers/riot/riot-desktop-yarndeps.nix changed?

`riot-desktop-yarndeps.nix` is generated from `riot-web/electron_app/yarn.lock`, not `riot-web/yarn.lock`, which is the one that changed.

**Comment by worldofpeace** [comment]
Understood. Thanks for explaining @pacien :+1:

**Pull request merged**
