### PR TITLE
maxima: various cleanups

### PR DESCRIPTION
**Pull request by omasanori**
###### Motivation for this change

I have done some groundwork to ease not-yet-published update to Maxima 5.44.0. I published these cleanups separate from the update itself to make reviews easier.
I am still new to Nix so while I did my best some changes might not be idiomatic. Any suggestions are welcome!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]

**Review by peti — COMMENTED** [review]
Those gratuitous whitespace changes make it pretty hard to figure out what you've actually changed. I'm not a fan of submissions reformatting the entire file to their personal taste.

**Comment by omasanori** [comment]
Thank you for your reviews, @7c6f434c and @peti!

> Those gratuitous whitespace changes make it pretty hard to figure out what you've actually changed. I'm not a fan of submissions reformatting the entire file to their personal taste.

I am sorry for bother you. I will revise the patch to minimize whitespace changes.

**Comment by omasanori** [comment]
So, the formatting seems closer now. Would you point out if any of these patches are irrelevant to you? I will adopt subsequent patches.

**Comment by omasanori** [comment]
So, I will rework this and Maxima update to make them acceptable. I appologize for my hasty action.

**Pull request closed without merging**
