### PR TITLE
meta.updateWalker: remove because it is not used

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
#103997 removing the documentation about `meta.updateWalker`

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
can someone help me in how to better document this? is running `nixos/doc/manual/md-to-db.sh` needed?

**Comment by ryantm** [comment]
Shouldn't this be in the same PR that removes update-walker.sh? (Assuming we actually do want to remove it, I don't know about it.)

 > is running nixos/doc/manual/md-to-db.sh needed?

No, that's only needed if you change the NixOS docs, not the nixpkgs ones like you have here.

**Comment by Stunkymonkey** [comment]
sure i can include the removal into a single PR. I thought more of splitting it up into multiple PRs

**Comment by Stunkymonkey** [comment]
i just notice, that all additional changes i did are not very helpful for reviewing the PR. Should I remove them?

**Comment by Stunkymonkey** [comment]
i removed all the changes, that were not necessary

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Can you also drop https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/check-meta.nix#L239 and https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/check-meta.nix#L247 ?

**Comment by Stunkymonkey** [comment]
is now removed in the last commit

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by zowoq** [comment]
This seems to have missed a couple of files?
https://github.com/NixOS/nixpkgs/blob/bcd452a5544131d486eac0493002d2341b3af022/pkgs/development/tools/misc/luarocks/default.upstream#L1
https://github.com/NixOS/nixpkgs/blob/30d4848ffc1b6b1768d08d6e5061cab6bcfd7561/pkgs/servers/nosql/apache-jena/fuseki-binary.upstream#L1
___
This is still used in one place, I'd suggest moving into the the same directory. 
https://github.com/NixOS/nixpkgs/blob/bcd452a5544131d486eac0493002d2341b3af022/pkgs/build-support/upstream-updater/urls-from-page.sh#L1
https://github.com/NixOS/nixpkgs/blob/5a17134ebddcb43c90332187e63f2650f1c6a7f5/pkgs/development/lisp-modules/from-quicklisp/barebones-quicklisp-expression.sh#L54 
___

Can also remove these from `.editorconfig`:

https://github.com/NixOS/nixpkgs/blob/3540d008808ab520d432f93353e45992e83a0506/.editorconfig#L70-L72

**Comment by SuperSandro2000** [comment]
@Stunkymonkey can you please take a look at the above comment? I currently miss the time to do that.

**Pull request merged**
