### PR TITLE
nixos/komga: add service hardening and misc format changes.

### PR DESCRIPTION
**Pull request by fsnkty**
## Description of changes
- remove top level with lib;
- use lib.getExe (package already has meta.mainProgram)
- add systemd service hardening ( tested personally but not extensively )

contemplating adding myself to maintainers for if any issues with this aren't caught before merge.
just also don't want to add myself more often than i should and end up taking forever to reply, whats worse?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nu-nu-ko** [comment]
> While the hardening (mostly) seems fine to me komga I'm not sure a `ProtectHome` is a good idea in this case, at least without informing the user, as I can see someone blindly adding mangas/comics/epubs to their home folder and giving groups permissions to komga.

any concern that it may break some existing use case is reason enough to me to remove it, its easy enough to add back in config individually anyway.

will update the commit to remove `ProtectHome`
tomorrow

thanks!

**Review by eclairevoyant — COMMENTED** [review]
Not sure about the `SystemCallFilter` without digging a bit more and testing myself, but the rest of the hardening appears fine at first glance. One bit of feedback so far:

**Comment by eclairevoyant** [comment]
> just also don't want to add myself more often than i should and end up taking forever to reply, whats worse?

Just as you don't need to be a maintainer to create this PR, neither does someone else in the future. If you really want the ping, feel free to add yourself, as the purpose of that is in fact to get pings about issues/PRs. If you find that you're not available to maintain in the future, you can send a PR to remove yourself as well - maintainership is fluid.

**Comment by nu-nu-ko** [comment]
> Not sure about the `SystemCallFilter` without digging a bit more and testing myself, but the rest of the hardening appears fine at first glance. One bit of feedback so far:

been using this for a fair while now, haven't been able to find issues but of course my use case isn't all use cases.
if you can suggest a more conservative replacement or more concrete reason to remove it entirely I'd appreciate it!

> Just as you don't need to be a maintainer to create this PR, neither does someone else in the future. If you really want the ping, feel free to add yourself, as the purpose of that is in fact to get pings about issues/PRs. If you find that you're not available to maintain in the future, you can send a PR to remove yourself as well - maintainership is fluid.

May as well then, don't want to make changes then disappear when they create issues after all, just nerves I guess, I don't wanna get in anyone's way

thanks again!

**Pull request merged**
