### PR TITLE
python311Packages.pyfftw: remove

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Fails with:
```
Running phase: buildPhase
Executing setuptoolsBuildPhase
setup.py:46: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_platform
/build/pyFFTW-0.13.1/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/build/pyFFTW-0.13.1/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 827, in <module>
    setup_package()
  File "setup.py", line 765, in setup_package
    'version': versioneer.get_version(),
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/pyFFTW-0.13.1/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/build/pyFFTW-0.13.1/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/pyFFTW-0.13.1/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by mweinelt** [comment]
Have you tried removing the vendored versioneer.py?

**Comment by GaetanLepage** [comment]
I have just try `rm versioneer.py` in the `postPatch` and added `versioneer` to `build-system`, but this gives the following:

```
Error compiling Cython file:
------------------------------------------------------------
...
# the types supported in this build
_supported_types = []
_supported_nptypes_complex = []
_supported_nptypes_real = []

IF HAVE_SINGLE:
  ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:73:3: Compile-time name 'HAVE_SINGLE' not defined
...
```

The log is much longer.

**Comment by mweinelt** [comment]
Have you tried `cython` instead of `cython_0`?

**Comment by mweinelt** [comment]
I think we can remove it, since it is a leaf package without a maintainer

**Comment by GaetanLepage** [comment]
> I think we can remove it, since it is a leaf package without a maintainer

Done. The only issue is that it is used as an example in the documentation: https://github.com/NixOS/nixpkgs/blob/d3d409146dabaa9a6b769bf069a3eddf471a9714/doc/languages-frameworks/python.section.md?plain=1#L1085

**Comment by mweinelt** [comment]
I wouldn't worry about that too much.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 320488` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
> I wouldn't worry about that too much.

Ok ! Should I merge then ?

**Pull request merged**
