### PR TITLE
python3Packages.cryptography: 3.4.8 -> 35.0.0

### PR DESCRIPTION
**Pull request by cpcloud**
###### Motivation for this change

Upgrade `python3Packages.cryptography` from `3.4.8` to `35.0.0`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
That definitely needs to go into staging, cryptography is at the core of many python packages.

**Comment by cpcloud** [comment]
> That definitely needs to go into staging, cryptography is at the core of many python packages. In fact I wonder if we should wait for the next python-unstable run, depending how much breakage we can expect.

Cool. Are there some guidelines somewhere around going through staging?

**Comment by SuperSandro2000** [comment]
https://github.com/NixOS/nixpkgs/blob/master/doc/contributing/submitting-changes.chapter.md#staging-branch-submitting-changes-staging-branch

**Comment by primeos** [comment]
> In fact I wonder if we should wait for the next python-unstable run, depending how much breakage we can expect.

IIRC Cryptography updates usually caused (very) few breakages in the past so it should probably be fine. The changelog also LGTM: https://cryptography.io/en/latest/changelog/#v35-0-0. However, we could still wait for the next python-unstable run if that would help.

@cpcloud would you mind doing some additional testing (I'm usually trying out a few simple examples and use nixpkgs-review to test (most) Python rebuilds)?

**Comment by SuperSandro2000** [comment]
What do we usually test? home-assistant?

**Comment by risicle** [comment]
Cherry-picked, this builds happily on macos 10.15, python 3.8 & 3.9

**Comment by SuperSandro2000** [comment]
With the exception of python-miio everything required in home-assistant still build successful. I think this can be safely merged without causing to much havoc.

**Comment by mweinelt** [comment]
This update broke `python3Packages.fido2` and `python3Packages.signify` and by extension `home-assistant`. I think we might need to revert it.

**Comment by mweinelt** [comment]
Reverted in #141037 due to breakages in fido2, mitmproxy and a whole lot of downstream packages. We're too close before a release for these kinds of breaking changes.

**Pull request merged**
