### PR TITLE
nixos/nextcloud: make `poolSettings` properly overridable

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
The current `services.nextcloud.poolSettings`-setting doesn't have much
value since setting a custom value discards all default-settings since the
entire default-attrset has the priority of an option-default.

Now all phpfpm-settings declared by this module are set using `mkDefault`,
so a user can override a single value with

    services.nextcloud.poolSettings."pm.max_children" = 23;

Even though `poolSettings` doesn't have an actual default anymore, it
renders the phpfpm-settings as `defaultText` to have them documented in
the manual.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
What happens when I specify `"pm" = "ondemand";` or `"pm" = "static";`? It was a very explicit design decision to toss out all values if the sysadmin specifies anything. I would almost advocate not providing defaults at all, forcing the sysadmin to fill in values... except I love how NixOS always has minimal working examples.

**Comment by Ma27** [comment]
> What happens when I specify "pm" = "ondemand"; or "pm" = "static";?

`"pm" = "dynamic"` has `mkDefault` as priority, so this will override it.

> except I love how NixOS always has minimal working examples

I agree with that.

I have to admit that I don't remember exactly when we added this, but tbh I think that we can drop the entire option if we want an administrator to re-declare all of the options inside, because then I don't see much of a value in it.

**Comment by aanderse** [comment]
Currently it provides a nice default so users don't have to muck around if they just want to get a service up and running. If the service is for personal use the values don't really matter that much. If the service for a "real" or "production" setting there is no way we can provide reasonable defaults because the values will entirely depend on a dozen factors we don't know - simply tweaking one value won't provide much value. So I think the current module covers both scenarios nicely, and as a bonus keeps things simple for me users or users who want a simple self hosted instance.

My 2 cents at least.

**Comment by Ma27** [comment]
Actually you're right. The only setting where leaving it as-is is debatable is `pm = "dynamic";`, but a single setting ain't worth the effort, so I'm going to close this.

**Pull request closed without merging**
