### PR TITLE
pythonPackages.pkgconfig: 1.1.0 -> 1.3.1

### PR DESCRIPTION
**Pull request by catern**
###### Motivation for this change

The new version has a number of bugfixes and useful features. It also now includes the tests in the distribution.

It may cause breakage, though: 

> Version 1.2.0
> Released on November 30th 2016.
> 
> Potential break: switch from result set to list

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by catern** [comment]
See changelog here
https://pypi.python.org/pypi/pkgconfig

**Comment by timokau** [comment]
If the tests are included now, we should probably remove the comment:

```
    # Note that the distributed archive does not actually contain any tests.
    # https://github.com/matze/pkgconfig/issues/9
```

**Comment by FRidh** [comment]
Unless we get to have a Hydra job to test this change, I think we should not backport to 18.03 anymore.

**Comment by timokau** [comment]
I think its pretty likely that the "potential breaking change" breaks some things. I tried to test it myself with `nox-review`, but it ran out of memory.

**Review by dotlambda — COMMENTED** [review]
Would you mind moving this out of `python-packages.nix`?

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.pkgconfig python3.pkgs.pkgconfig

@FRidh Please merge into staging if there are no objections.

**Comment by catern** [comment]
ping @FRidh 

The changes in this pkgconfig version allow me to delete some copy-pasted code in every one of my build scripts, so I'm looking forward to it.

**Comment by timokau** [comment]
Is there anything left to be done before this can be merged into staging? This blocks the sage PR (#39981).

**Comment by FRidh** [comment]
I've included the change in https://github.com/NixOS/nixpkgs/pull/36434.

**Comment by timokau** [comment]
Thanks
I think that's a typo though, #36434 is this pr

**Comment by FRidh** [comment]
@timokau fixed, thanks.

**Pull request closed without merging**
