### PR TITLE
haskellPackages: use makeExtensible

### PR DESCRIPTION
**Pull request by cstrahan**
###### Motivation for this change

This changes the Haskell packages infra to use `makeExtensible`. This is an improvement over the existing overrides mechanism because:

* The existing way isn't consistent with the rest of nixpkgs (the `override` fn taking a `overrides` attr is unique to the haskell packages: `.override { overrides = self: super: { ... }; }`)
* `override` doesn't compose as expected -- that is, in the following incantation, the second `override` drops the changes made in the first `override`: `(ghc.override { ... }).override { ... }`
* Using `makeExtensible` moves us toward a common way to approach the `self: super:` style overrides (`override` has, historically, meant overriding the *inputs* into a drv's expression, whereas `.extends` is intended for OOP-ish overriding of package sets)

@peti if this looks good to you, I'll update the docs before we merge.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @ryantrinkle

### CODE REVIEW

**Comment by cstrahan** [comment]
Simple demonstration of use:

```nix
let pkgs = import <nixpkgs> {};

in

(pkgs.haskell.packages.ghc802.extend (self: super: {
  conduit-extra = pkgs.haskell.lib.overrideCabal super.conduit-extra (drv: {
    src = "${pkgs.fetchFromGitHub {
      owner = "luigy";
      repo = "conduit";
      rev = "aeb20e4eb7f7bfc07ec401c82821cbb04018b571";
      sha256 = "10kz2m2yxyhk46xdglj7wdn5ba2swqzhyznxasj0jvnjcnv3jriw";
    }}/conduit-extra";
  });
})).conduit-extra
```

This will help clean up some of [`reflex-platform`](https://github.com/reflex-frp/reflex-platform/blob/develop/default.nix).

**Comment by cstrahan** [comment]
(I would recommend deprecating the haskell pacakge's `.override` function in the future.)

**Comment by 3noch** [comment]
🎉

**Comment by domenkozar** [comment]
cc @peti - can we merge this today for 17.03? :)

**Comment by domenkozar** [comment]
@cstrahan sorry, I merged some other PRs and this now conflicts. Can you resolve?

**Comment by domenkozar** [comment]
I think we should also update haskell docs with this change.

**Comment by peti** [comment]
> cc @peti - can we merge this today for 17.03? :)

No, please don't. I want to review this properly and I haven't had time yet.

**Comment by cstrahan** [comment]
I should note that, under the hood, `makeExtensible` uses `fix'`. So exchanging `fix'` for `makeExtensible` is completely backwards compatible, and only adds the `extend` attr (e.g. `__unfix__` hasn't been removed). `makeExtensible` was introduced in #15095 to enable easily overriding the kernel package set:

```nix
pkgs.linuxPackages.extend (self: super: {
  kernel = super.kernel.override {
    kernelPatches = super.kernel.kernelPatches ++ [ pkgs.kernelPatches.ubuntu_fan_4_4 ];
  };
});
```

**Comment by peti** [comment]
My understanding is that this patch conflicts in scope with https://github.com/NixOS/nixpkgs/pull/22613, i.e. both patches fix the unexpected lack of nesting in overrideCabal. The difference is just that https://github.com/NixOS/nixpkgs/pull/22613 -- which was merged yesterday -- fixes it internally within the Haskell infrastructure whereas this patch fixes it by, essentially, moving away from our own homegrown overrideCabal function and towards the "standard" extends function provided by lib.

Now, if we"re merging this patch, it seems silly to merge https://github.com/NixOS/nixpkgs/pull/22613 as well, i.e. I'd rather not deprecate and fix overrideCabal at the same time.

Am I interpreting this situation correctly?

**Comment by cstrahan** [comment]
@peti It looks like #22613 is concerned with the composition of overrides *at the package level*, whereas this is concerned with the *extension of the package set* -- so they're complimentary.

This PR makes achieves two things:

1. Make composition of extensions do the right thing (so you can, in stages, extend modify the set), and
2. Make the interface more consistent with the direction that nixpkgs is moving with regard to package set extension (that is, using the `pkgSet.extend (self: super: ...)` construct) -- all while preserving backwards compat with previous uses of the `haskellPackages.override { overrides = self: super: { ... }; })`)

The problem @ryantrinkle et al ran into was that the following psuedo code the second `override` drops any new packages added (or old packages changed) in the first `override`: `(ghc.override { ... }).override { ... }`. That appears to be out of scope of #22613.

**Comment by cstrahan** [comment]
I realize a (potentially) better way to underline the difference/independence of this PR and #22613:

Even with #22613 merged, a chain of `haskellPackages.override`'s will be broken (e.g. the last call wins and any packages added in the initial calls are dropped on the ground) without this PR.

If we revert #22613 and instead merged this PR, a chain of `overrideCabal` would be ill-behaved, but you could still add new packages to the set, and indeed you could also chain `overrideCabal` but with the caveat that you might not get what you expect.

With both PRs, you can both extend the package set *and* compose `overrideCabal` and get the intuitive/expected result.

The two PRs operate at two different levels (modification of an individual package *vs* modification of the haskell package set fixpoint), and both are needed for composition as a whole to work as expected.

**Comment by peti** [comment]
OK, very cool. Thank you for the fix and for the detailed explanations.

**Pull request merged**
