### PR TITLE
gnu-efi: apply patch to fix build on armv6l

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Applies a patch that I have submitted upstream to fix the build on armv6l. In nixpkgs, the build was broken by #72694, but this was really because it revealed an upstream bug.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @kirelagin

### CODE REVIEW

**Comment by lopsided98** [comment]
@GrahamcOfBorg build gnu-efi

**Comment by kirelagin** [comment]
Why not just `arm.*` though?

**Review by matthewbauer — APPROVED** [review]

**Comment by lopsided98** [comment]
I updated the patch to allow any ARM version.

**Comment by Ericson2314** [comment]
@kirelagin You mean apply the patch conditionally? I prefer to unconditionally apply the patches were possible to indicate they are improvements to the code base and not platform-specific hacks; We've had a perception in the past that "more platforms means more mess" and harder maintenance, and I want to counter that by showing stuff gets upstreamed and the code quality goes up.

**Comment by lopsided98** [comment]
@Ericson2314 My original patch had a special case for in the sed expression for armv6 (ie. `armv[67].*`), but I later updated it at @kirelagin's suggestion to just be `armv.*` since there was no real reason to restrict it to certain ARM versions.

I submitted the new version upstream as well, see: https://sourceforge.net/p/gnu-efi/patches/71/

**Pull request merged**
