### PR TITLE
Rename `meson_0_60` to `meson` and update some packages

### PR DESCRIPTION
**Pull request by L-as**
###### Motivation for this change

We currently have two mesons. Replaces #144779.

###### Things done

I do not have enough compute to build this.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Is this aimed to remove the newer Meson?

**Comment by L-as** [comment]
This renames `meson_0_60` to `meson` essentially.

**Comment by AndersonTorres** [comment]
Well, then 'revert' commits are not needed... or are they?

**Comment by L-as** [comment]
Those commits are from the previous PR.

**Comment by L-as** [comment]
Ci passes. Should we merge this?

**Comment by L-as** [comment]
> Are they needed here? It looks like they can be ignored...

Removing them would require rewriting the history.

> Looks like ofborg is complaining.

Where? I only see a green checkmark.

**Comment by alyssais** [comment]
> Removing them would require rewriting the history.

That shouldn't be hard, and I think it would make it much clearer for people looking back to see what happened if we squashed all the reverts and both of the upgrades together.  (It would also be nice to move the package fixes ahead of the meson changes in the PR to avoid having commits where those packages are broken, which would make things easier for people trying to bisect those packages in future.)  I'm happy to volunteer to do that rebase if you want.

> Where? I only see a green checkmark.

[I see the following:](https://logs.nix.ci/?key=nixos/nixpkgs.154172&attempt_id=22f7af76-2f54-47f4-b00f-2ec5cd9c7cdd) (but I'm not sure it's related to Meson)

> Test "paths" failed with error: "command `test -f /testpath-modified` unexpectedly succeeded"

**Comment by L-as** [comment]
I've rewritten the history. I don't think the test failure is related to Meson.

**Review by jtojnar — APPROVED** [review]

**Comment by L-as** [comment]
We probably want to merge this before other PRs introduce more uses of `meson_0_60`.

**Comment by AndersonTorres** [comment]
I'm waiting for ofborg.

**Comment by L-as** [comment]
There seems to be no issues.

**Comment by jtojnar** [comment]
By the way, 0.61.0 has been released.

**Comment by AndersonTorres** [comment]
And, by the way, with huge patch failure:

```
meson> unpacking source archive /nix/store/w7d0bjwsgz2nkiy4akg3hbqw9jvfwazd-meson-0.61.0.tar.gz
meson> source root is meson-0.61.0
meson> setting SOURCE_DATE_EPOCH to timestamp 1641832169 of file meson-0.61.0/setup.cfg
meson> patching sources
meson> applying patch /nix/store/pza7hhm23l5qlkb633di8mrf67jp9lbr-allow-dirs-outside-of-prefix.patch
meson> patching file mesonbuild/coredata.py
meson> Hunk #1 succeeded at 564 (offset 58 lines).
meson> Hunk #2 succeeded at 575 (offset 58 lines).
meson> applying patch /nix/store/dgh2dydb2886zvcsvafpighm1y6i4n27-more-env-vars.patch
meson> patching file mesonbuild/environment.py
meson> applying patch /nix/store/1y6lfavd1bzbmv77p29aw7xaqn30ql9h-gir-fallback-path.patch
meson> patching file mesonbuild/modules/gnome.py
meson> Hunk #1 succeeded at 1092 with fuzz 1 (offset 169 lines).
meson> applying patch /nix/store/xgqaxd31i95mfnj3i0xqa8x9bd0m1vl9-fix-rpath.patch
meson> patching file mesonbuild/backend/backends.py
meson> Hunk #1 FAILED at 456.
meson> 1 out of 1 hunk FAILED -- saving rejects to file mesonbuild/backend/backends.py.rej
error: builder for '/nix/store/j6skcz8987ds6nwjj0v0ss0gl2nxw5ma-meson-0.61.0.drv' failed with exit code 1;
```

**Pull request merged**
