### PR TITLE
plan9port: unmark as broken on darwin

### PR DESCRIPTION
**Pull request by ylh**
###### Motivation for this change

Builds and runs just fine on Darwin with an overlay filtering out the broken attr.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nrdxp** [comment]
Couldn't you apply whatever you are doing in the overlay directly to this PR?

**Comment by sternenseemann** [comment]
Pretty sure their overlay just sets `meta.broken = false`.

**Comment by nrdxp** [comment]
ah okay, I think I misunderstood :sweat_smile: 
I'll gladly merge then, but I'll way for the darwin CI build just to be safe

**Comment by ylh** [comment]
> Pretty sure their overlay just sets `meta.broken = false`.

`meta = lib.filterAttrs (n: _v: n != "broken") meta;`, but yeah, same difference

**Comment by nrdxp** [comment]
if you wanna run nixpkgs-review from your mac, since CI seems to be held up, I'll merge with a successful build. If even that proves difficult, just give me your word that you've personally built and used the package, and we're good :+1:

**Comment by ylh** [comment]
Result of `nixpkgs-review pr 133535` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by polynomialspace** [comment]
oh neat, it breaks on x86_64-darwin but not aarch64-darwin, wonder how that works.

**Pull request merged**
