### PR TITLE
firefox-{beta,devedition}-unwrapped: 119.0b9 -> 120.0b4

### PR DESCRIPTION
**Pull request by jim3692**
## Description of changes

I haven't tried building yet, I will remove the draft flag after giving it a try.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jim3692** [comment]
I may need some help.

Firefox Dev Edition:
```
In file included from /build/firefox-120.0/toolkit/components/remote/nsDBusRemoteClient.cpp:9:
In file included from /build/firefox-120.0/toolkit/components/remote/nsDBusRemoteClient.h:15:
In file included from /build/firefox-120.0/mozobj/dist/include/mozilla/DBusHelpers.h:10:
/build/firefox-120.0/mozobj/dist/system_wrappers/dbus/dbus.h:3:15: fatal error: 'dbus/dbus.h' file not found
#include_next <dbus/dbus.h>
              ^~~~~~~~~~~~~
1 error generated.
make[3]: *** [/build/firefox-120.0/config/rules.mk:690: nsDBusRemoteClient.o] Error 1
```

Firefox Beta:
```
In file included from /build/firefox-120.0/toolkit/components/remote/nsDBusRemoteServer.cpp:8:
In file included from /build/firefox-120.0/toolkit/components/remote/nsDBusRemoteServer.h:13:
In file included from /build/firefox-120.0/mozobj/dist/include/mozilla/DBusHelpers.h:10:
/build/firefox-120.0/mozobj/dist/system_wrappers/dbus/dbus.h:3:15: fatal error: 'dbus/dbus.h' file not found
#include_next <dbus/dbus.h>
              ^~~~~~~~~~~~~
/build/firefox-120.0/toolkit/components/protobuf/src/google/protobuf/generated_message_tctable_lite.cc:1631:10: warning: 'return' will never be executed [-Wunreachable-code-return]
  return Error(PROTOBUF_TC_PARAM_PASS);
         ^~~~~
1 error generated.
make[3]: *** [/build/firefox-120.0/config/rules.mk:690: nsDBusRemoteServer.o] Error 1
```

**Comment by ShalokShalom** [comment]
I did send that a few weeks back to the maintainers by email, and did not get any response yet:

Firefox-beta shows up in the about menu as 119.0b4 and not 119.0b9 for some reason. 
Dev is actually at 119.09 (and I am eagerly awaiting 120 for a patch 😅 )

Thanks a lot for helping 👍🏻

**Comment by ShalokShalom** [comment]
Hello :)

As a newbie, I feel slightly confused: It seems there is already a build committed and merged, but the backport is not?

Since I dont see these builds available for the unstable branch as well. 
Thanks a lot for this contribution 👍🏻

**Comment by jim3692** [comment]
> I did send that a few weeks back to the maintainers by email, and did not get any response yet:
> 
> Firefox-beta shows up in the about menu as 119.0b4 and not 119.0b9 for some reason. Dev is actually at 119.09 (and I am eagerly awaiting 120 for a patch 😅 )
> 
> Thanks a lot for helping 👍🏻

I am waiting for an [audio pitching](https://bugzilla.mozilla.org/show_bug.cgi?id=1844181) fix that Firefox 120 has

**Comment by ShalokShalom** [comment]
We are waiting for Rust 1.70, to backport this otherwise merged build: https://github.com/NixOS/nixpkgs/pull/266750

So can subscribe there, and close this, I suggest ❔

**Comment by jim3692** [comment]
Closed as duplicate of #266735

**Pull request closed without merging**
