### PR TITLE
zellij: 0.8.0 -> 0.10.0

### PR DESCRIPTION
**Pull request by jb55**
Signed-off-by: Matthias Beyer <mail@beyermatthias.de>
Reviewed-by: William Casarin <jb55@jb55.com>
Link: https://lists.sr.ht/~andir/nixpkgs-dev/%3C20210514095219.13010-1-mail@beyermatthias.de%3E

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 123050` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zellij</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Looks good to me, waiting for the CI to pass before merging.

**Comment by happysalada** [comment]
@NixOS/ofborg eval

**Comment by happysalada** [comment]
@GrahamcOfBorg eval

**Comment by happysalada** [comment]
I've tested on darwin, so I will ignore the darwin failures. It seems however that there are some flaky tests.

**Comment by happysalada** [comment]
@GrahamcOfBorg eval

Trying to re-run the evaluation to see if the tests are flaky or if that is a repeatable failure on darwin.

**Comment by happysalada** [comment]
@0x4A6F  @therealansh I just went ahead and merged it since this is a simple version upgrade.
If you want me to wait next time, just let me know.

**Comment by 0x4A6F** [comment]
I'm okay with this procedure. Thanks.

**Pull request merged**
