### PR TITLE
nixos/forgejo: init

### PR DESCRIPTION
**Pull request by Infinidoge**
###### Description of changes

Rebased #206493 to add the service using the already-merged package definition.

There are some pieces left over from the Gitea module (namely the renamed module definitions.)
These could be removed, since it is a new service, however I've gone ahead and left them in so switching from GItea -> Forgejo could just be a single rename in a user's configuration.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Infinidoge** [comment]
If anybody wants to be added as a maintainer to this, please let me know.
I am perfectly fine with maintaining it (and I certainly intend on using it, at least), however I'm not the most familiar with the Gitea/Forgejo codebase.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
I think we should keep this in the gitea module for now. The two programs are still almost identical right now and most of the code would be duplicated.

You can use forgejo by changing ``services.gitea.package`` to the forgejo package and since  ``services.gitea.settings`` is freeform any new setting can be added.

**Comment by trepetti** [comment]
This actually does not work as the gitea service is currently written since the `gitea` binary name is hardcoded in even when the packages are switched out. Forgejo uses a `forgejo` binary.

**Comment by lilyinstarlight** [comment]
> This actually does not work as the gitea service is currently written since the `gitea` binary name is hardcoded in even when the packages are switched out. Forgejo uses a `forgejo` binary.

Perhaps the module can be refactored to use `lib.getExe cfg.package` then everywhere instead of `"${cfg.package}/bin/gitea"` then? I don't see an immediate reason to add a new module for now, especially if it's mostly a copy of the gitea module

**Comment by trepetti** [comment]
Yes, that seems like a good idea. An additional option for a `binaryName` parameter may also do the trick.

**Comment by lilyinstarlight** [comment]
> Yes, that seems like a good idea. An additional option for a `binaryName` parameter may also do the trick.

`lib.getExe` gets the `mainProgram` attr on the package (falling back to the package name if absent), so it should be able to stand in for all intended use-cases. But I also don't feel strongly either way so someone else can argue to include such an option as well

**Comment by trepetti** [comment]
That does seem like the way to go then.

**Comment by Infinidoge** [comment]
Yeah using `getExe` would work.
If we want to look to the future, we could have `services.forgejo` serve as an alias to `services.gitea` with the Forgejo package selected, but I don't know if that is a good idea

**Comment by lilyinstarlight** [comment]
It looks like this has been superseded by #218269. Feel free to re-open a new PR if you had any plans other than just adding `lib.getExe`

**Pull request closed without merging**
