### PR TITLE
copier: 8.1.0 -> 8.3.0

### PR DESCRIPTION
**Pull request by carlthome**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by carlthome** [comment]
Getting

>ImportError: cannot import name 'AfterValidator' from 'pydantic'

at runtime with `nix run .#copier -- --version` so something is missing.

**Comment by carlthome** [comment]
Think it's related to that `copier` now assumes Pydantic 2, so think this is technically blocked by https://github.com/NixOS/nixpkgs/pull/244564

**Comment by carlthome** [comment]
Yup: https://github.com/copier-org/copier/compare/v8.1.0...v8.3.0

**Comment by carlthome** [comment]
Related https://github.com/NixOS/nixpkgs/issues/263228

**Comment by carlthome** [comment]
If anyone is reading this, looking for a work around, here's how you can run the latest `copier` with Nix:

```
nix run github:copier-org/copier -- --version
```

since fortunately upstream already packages their software with Nix.

**Comment by GTrunSec** [comment]
- nix run github:copier-org/copier -- --version
- passed on `x86_64-linux`
```
copier 9.0.1.dev20231121164554+nix.git.50d478e
```

**Review by GTrunSec — APPROVED** [review]

**Comment by carlthome** [comment]
@GTrunSec this should not be merged. Build works but runtime fails.

**Comment by wegank** [comment]
Superseded by #282479.

**Pull request closed without merging**
