### PR TITLE
koboldcpp: Fix Package Build Failure with CUDA Enabled

### PR DESCRIPTION
**Pull request by KiruyaMomochi**
## Description of changes

When attempting to build the latest `koboldcpp` with `cublasSupport` setting to `true`, I encountered the following error:

```
koboldcpp> nvcc fatal   : Value 'sm_sm_89' is not defined for option 'gpu-architecture'
koboldcpp> make: *** [Makefile:228: ggml-cuda.o] Error 1
koboldcpp> make: *** Waiting for unfinished jobs....
```

This PR fixes the following issue by
* Fix the value of `CUDA_DOCKER_ARCH`, and use `cudaFlags.realArches` instead of `cudaFlags.arches`.
* Correct the usage of `makeWrapper`.

### Issue 1: `CUDA_DOCKER_ARCH` Contains Duplicated `sm_` Prefix

The error appears to stem from the `CUDA_DOCKER_ARCH` variable being defined with a duplicated `sm_` prefix. This occurs in the [`makeFlags` definition](https://github.com/NixOS/nixpkgs/blob/79ba441d002128b9685ee9e11de0c6a6037f93d3/pkgs/by-name/ko/koboldcpp/package.nix#L132):

```nix
(lib.optionals cublasSupport "CUDA_DOCKER_ARCH=sm_${builtins.head cudaArches}")
```

The `cudaArches` argument, which defaults to `cudaPackages.cudaFlags.arches`, already includes the `sm_` prefix, as seen [here](https://github.com/NixOS/nixpkgs/blob/c19d62ad2265b16e2199c5feb4650fe459ca1c46/pkgs/development/cuda-modules/flags.nix#L180-L195):

```nix
# realArches :: List String
# The real architectures are physical architectures supported by the CUDA version.
# E.g. [ "sm_75" "sm_86" ]
realArches = archMapper "sm" cudaCapabilities;

# virtualArches :: List String
# The virtual architectures are typically used for forward compatibility, when trying to support
# an architecture newer than the CUDA version allows.
# E.g. [ "compute_75" "compute_86" ]
virtualArches = archMapper "compute" cudaCapabilities;

# arches :: List String
# By default, build for all supported architectures and forward compatibility via a virtual
# architecture for the newest supported architecture.
# E.g. [ "sm_75" "sm_86" "compute_86" ]
arches = realArches ++ lists.optional enableForwardCompat (lists.last virtualArches);
```

On my machine, `cudaFlags.arches` evaluates to:

```shell
$ nix eval github:NixOS/nixpkgs/master#cudaPackages.cudaFlags.arches
[ "sm_60" "sm_61" "sm_70" "sm_75" "sm_80" "sm_86" "sm_89" "sm_90" "sm_90a" "compute_90a" ]
```

As a result, `koboldcpp.makeFlags[-1]` evaluates to `CUDA_DOCKER_ARCH=sm_sm_60`:

```shell
$ nix eval 'github:NixOS/nixpkgs/master#koboldcpp' --apply 'x: (x.override { cublasSupport = true; }).makeFlags'
[ "LLAMA_OPENBLAS=1" "LLAMA_CUBLAS=1" "LLAMA_CLBLAST=1" "LLAMA_VULKAN=1" "" "CUDA_DOCKER_ARCH=sm_sm_60" ]
```

This causes the build to fail since the Makefile is effectively being passed `-arch=sm_sm_XX`:

```makefile
ifdef CUDA_DOCKER_ARCH
    NVCCFLAGS += -Wno-deprecated-gpu-targets -arch=$(CUDA_DOCKER_ARCH)
else
```

### Issue 2: Incorrect Usage of `makeWrapper`

There is also an issue with the usage of `makeWrapper` in the `postFixup` phase:

```shell
$ nix eval --raw nixpkgs#koboldcpp.postFixup  
wrapPythonProgramsIn "$out/bin" "$pythonPath"  
makeWrapper "$out/bin/koboldcpp.unwrapped" "$out/bin/koboldcpp" \  
  --prefix PATH /nix/store/a79hjvwbgnn5xrf571hslxgw987ivj4d-tk-8.6.13/bin --prefix LD_LIBRARY_PATH : "/run/opengl-driver/lib"
```

According to the [comments and definition](https://github.com/NixOS/nixpkgs/blob/989d72f3b56fa33bf0afc99df18370a757eb6c0a/pkgs/build-support/setup-hooks/make-wrapper.sh#L30) in `make-wrapper.sh`, the `--prefix` option requires three arguments:

```
--prefix ENV SEP VAL   : suffix/prefix ENV with VAL, separated by SEP
```

### Note on Further Improvements

It seems that each `-arch` option only supports a single value like `sm_XX`. When using `CUDA_DOCKER_ARCH`, supporting multiple architectures simultaneously becomes challenging.

I am unsure if it would be better to patch the original Makefile to use `cudaPackages.cudaFlags.gencode` instead.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DontEatOreo** [comment]
Hey @KiruyaMomochi thanks for making this PR! I already made a similar PR https://github.com/NixOS/nixpkgs/pull/329426 but it didn't fix the `makeWrapper` issues so, I will close it in favor of yours.

**Comment by SomeoneSerge** [comment]
Result of `nixpkgs-review pr 330038 --extra-nixpkgs-config '{
  cudaSupport = true;
  cudaCapabilities = [
    "7.0"
    "8.0"
    "8.6"
  ];
  cudaEnableForwardCompat = false;
  allowUnfreePredicate =
    p:
    builtins.all (
      license:
      license.free
      || builtins.elem license.shortName [
        "CUDA EULA"
        "cuDNN EULA"
        "cuTENSOR EULA"
        "NVidia OptiX EULA"
      ]
    ) (if builtins.isList p.meta.license then p.meta.license else [ p.meta.license ]);
  permittedInsecurePackages = [
    "electron-24.8.6"
    "zotero-6.0.27"
  ];
}'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by KiruyaMomochi** [comment]
Thank you and sorry for my late response!

**Review by 4evy — APPROVED** [review]
LGTM!

Result of `nixpkgs-review pr 330038 --extra-nixpkgs-config '{ cudaSupport = true; cudaCapabilities = [ "7.0" "8.0" "8.6" ]; cudaEnableForwardCompat = false; allowUnfreePredicate = p: builtins.all ( license: license.free || builtins.elem license.shortName [ "CUDA EULA" "cuDNN EULA" "cuTENSOR EULA" "NVidia OptiX EULA" ] ) (if builtins.isList p.meta.license then p.meta.license else [ p.meta.license ]); permittedInsecurePackages = [ "electron-24.8.6" "zotero-6.0.27" ]; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by SomeoneSerge** [comment]
Yea I just want a runtime test...

**Comment by mirrexagon** [comment]
I checked out and built f0ff29350933140f2d69ef044c11414f74e89df2 - my `~/.config/nixpkgs/config.nix` was just:

```nix
{
  allowUnfree = true;
  cudaSupport = true;
}
```

I ran it as `./result/bin/koboldcpp <a LLaMa 3 8B GGUF file> --usecublas --contextsize 8192 --gpulayers 33` with a GTX 1080 GPU.

`nvidia-smi` reported:

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1080        Off |   00000000:05:00.0 Off |                  N/A |
|  0%   32C    P8             12W /  180W |    6145MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     28930      C   ...lgklv72l-python3-3.12.4/bin/python3       6142MiB |
+-----------------------------------------------------------------------------------------+
```

Generated some stuff, my stats were: 

```
Processing Prompt [BLAS] (7607 / 7607 tokens)
Generating (250 / 250 tokens)
CtxLimit: 7857/8192, Process:25.13s (3.3ms/T = 302.68T/s), Generate:34.71s (138.9ms/T = 7.20T/s), Total:59.85s (4.18T/s)
```

I'm happy with that!

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 330038` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 330038` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Pull request merged**
