### PR TITLE
platforms: use native arch parameters for apple-m1

### PR DESCRIPTION
**Pull request by Atemu**
This should allow clang to better optimise for the only aarch64-darwin CPU µarch

Closes https://github.com/NixOS/nixpkgs/issues/166401

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
@Atemu Can you undraft this so reviewers get pinged?

It'd be great to land this :)

**Comment by Atemu** [comment]
This is untested but sure

**Comment by Atemu** [comment]
Perhaps it only checks x86_64-darwin?

**Comment by Atemu** [comment]
nixpkgs-review reports `28506 packages updated` on aarch64-darwin.

**Comment by lovesegfault** [comment]
IMO we should wait for this staging cycle to end, and then just let this hit staging and see what happens.

I don't think there's another practical way of testing it

**Comment by Atemu** [comment]
We should also do some benchmarks as µarch optimisations don't necessarily result in a performance improvement.

**Comment by vcunat** [comment]
We're about to start another `staging-next` cycle, but I gather that you don't want to merge yet?

**Comment by Atemu** [comment]
It's not clear whether this is an improvement yet. We'd have to actually run some benchmarks to get a picture. [It might very well cause huge regressions rather than improvements](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.19-O3-March-Native).

I also haven't found the time to do any builds yet, so I don't even know whether anything builds with this applied.

**Comment by Atemu** [comment]
Yeah, this doesn't even build anything. Clang doesn't know about `+fp-armv8+neon+zcm+zcz+fullfp16` and yet it is able to use these as target-flags when called differently? I don't understand it.

I'm not sure this is worthwhile pursuing but I'll try to build a few benchmarks with the improved but reduced set.

I'm also not quite sure whether it makes sense to set arch and cpu differently. Shouldn't these flags go in CPU only?

**Comment by Atemu** [comment]
I don't plan on pursuing this any further.

**Pull request closed without merging**
