### PR TITLE
minecraft-launcher: fix broken url

### PR DESCRIPTION
**Pull request by kwannoel**
###### Motivation for this change
The current url is a dead link, unable to fetch from that source.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
Able to compile and start the `minecraft-launcher` binary & play `minecraft`
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
Able to compile and start the `minecraft-launcher` binary & play `minecraft`
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @hyperfekt

**Comment by Infinisil** [comment]
The link works for me:
```
nix-build -A minecraft.src --check
checking outputs of '/nix/store/cxb0ms2b7f1zgncd5hzz3cr4q5g75vx5-minecraft-launcher_2.1.11314.tar.gz.drv'...

trying https://launcher.mojang.com/download/linux/x86_64/minecraft-launcher_2.1.11314.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 70.2M  100 70.2M    0     0  4507k      0  0:00:15  0:00:15 --:--:-- 5353k
/nix/store/83csm2m15w4bncrw0g2ziakgcdby86mp-minecraft-launcher_2.1.11314.tar.gz
```

**Comment by jacereda** [comment]
Could this be backported to 19.09?

**Comment by jacereda** [comment]
Oh sorry, didn't realize it wasn't merged. I can't download from the current URL, I'll try to figure out why.

**Comment by kwannoel** [comment]
> Oh sorry, didn't realize it wasn't merged. I can't download from the current URL, I'll try to figure out why.

Hey it was working for me again. But when it didnt work I used this as a workaround to pull the latest tarball, this may help @jacereda :
```
{ config, lib, pkgs, ... }:

let minecraft = pkgs.minecraft.overrideAttrs (oldAttrs: rec {
    version = "0.0.0.0";
    src = builtins.fetchurl {
      url = "https://launcher.mojang.com/download/Minecraft.tar.gz";
      sha256 = "1cd0mpxqmci3m3y1xh5nbx68z69v0x1jyzc07siwfbxqkrlrddj9";
    };
    });

  in { environment.systemPackages = [ minecraft ]; }
```

**Pull request closed without merging**
