### PR TITLE
update.py: updater vim updater

### LINKED ISSUE #136248: adopt a new format for pkgs/misc/vim-plugins/vim-plugin-names and  maintainers/scripts/luarocks-packages.csv
## Issue description

I am trying to improve the way neovim plugins are handled. Traditionnally vim plugins are written in vimscript which lacks a dependency management system and so vim plugins tended to have no dependencies. There is now a vibrant community writing lua plugins which is a language with better tooling, notably luarocks that allows to specify dependencies in a rockspec file, for instance https://github.com/lewis6991/gitsigns.nvim/blob/main/gitsigns.nvim-scm-1.rockspec#L17.

I've made substantial changes to our lua infrastructure so we can leverage the rockspec in git repos directly (bypassing luarocks.org) in https://github.com/NixOS/nixpkgs/pull/134336.

The format of maintainers/scripts/luarocks-packages.csv has grown into a less practical csv file with format
`name,src,ref,server,version,luaversion,maintainers`
One of the appeal of using csv was that one could comment lines but now that the updater uses the python csv reader, it's not straightforward anymore (the python updater should be changed), also https://github.com/NixOS/nixpkgs/pull/134336#discussion_r690403986 mentioned it was not ideal.

These new neovim plugins tend to be more neovim plugins and so we may need to think where to register those packages, (in
pkgs/misc/vim-plugins/vim-plugin-names or in maintainers/scripts/luarocks-packages.csv ?).
Also pkgs/misc/vim-plugins/vim-plugin-names could use some additional fields like the `maintainers` one.
Overall it would be nice if both files could share a similar format. Some kind of jsonc (with comment support) maybe.

### PR DESCRIPTION
**Pull request by teto**
We want to support plugins on other hosts than github. To ease that I've changed the format of vim-plugin-names to CSV, see https://github.com/NixOS/nixpkgs/issues/136248 for reasoning

A more structured format will allow more features too.
- update.py: updater vim updater
- vimPlugins: update
- kakounePlugins: update

Fixes https://github.com/NixOS/nixpkgs/issues/136248 https://github.com/NixOS/nixpkgs/issues/166007

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
i am afraid it will bitrot and there doesnt seem to be much interest in reviewing.I dont like it but will merge. From a pure nixpkgs user it shouldn't change anything.

**Comment by andrevmatos** [comment]
This currently broke coc-nvim (and possibly other renamings?) on `nixos-unstable-small`

**Comment by andrevmatos** [comment]
Also, even trying to use the renamed plugin, it seems to have stopped working on stable/latest nvim:
```
[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by: yarn install
```

**Comment by andrevmatos** [comment]
@teto #167369

**Comment by teto** [comment]
cool thanks for taking care of it. Sorry for the annoyance.

**Pull request merged**
