### PR TITLE
Emscripten docs: reword and remove mention of `nix-env`

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
Adding @raitobezarius and @matthewbauer to CODEOWNERS to keep track of changes.

really this stuff should move into the source and out of the manual, an effort recently started by @infinisil. but that would require a much larger change touching code, and we didn't want to get into that right now.

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Please remove @matthewbauer as I believe they are not that active anymore in nixpkgs maintenance. I recently removed their CODEOWNER entry for other stuff.

**Comment by infinisil** [comment]
> really this stuff should move into the source and out of the manual

Taking a quick look, all of this looks like user-level documentation, so it should stay in the manual. Only contributor docs should be in the source code.

**Comment by fricklerhandwerk** [comment]
@RaitoBezarius please recheck.

**Review by RaitoBezarius — APPROVED** [review]
LGTM

**Pull request merged**
