### PR TITLE
python311Packages.{boto3,botocore}: 1.33.6 -> 1.34.21

### PR DESCRIPTION
**Pull request by anthonyroussel**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
diff LGTM, reviewed upstream changes to `setup.py`. Only a build failure to take care of:

```
error: builder for '/nix/store/6rfyikc9dkd51sk3n76lgrsmwv2vkr8j-python3.11-boto3-1.34.21.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'boto3-1.33.6.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Successfully built boto3-1.33.6-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for boto3-1.33.6-py3-none-any.whl
       >   - botocore<1.34.0,>=1.33.6 not satisfied by version 1.34.21
       >   - s3transfer<0.9.0,>=0.8.2 not satisfied by version 0.10.0
       For full logs, run 'nix log /nix/store/6rfyikc9dkd51sk3n76lgrsmwv2vkr8j-python3.11-boto3-1.34.21.drv'.
```

**Comment by anthonyroussel** [comment]
> diff LGTM, reviewed upstream changes to `setup.py`. Only a build failure to take care of:
> 
> ```
> error: builder for '/nix/store/6rfyikc9dkd51sk3n76lgrsmwv2vkr8j-python3.11-boto3-1.34.21.drv' failed with exit code 1;
>        last 10 log lines:
>        > adding 'boto3-1.33.6.dist-info/RECORD'
>        > removing build/bdist.linux-x86_64/wheel
>        > Successfully built boto3-1.33.6-py3-none-any.whl
>        > Finished creating a wheel...
>        > Finished executing pypaBuildPhase
>        > Running phase: pythonRuntimeDepsCheckHook
>        > Executing pythonRuntimeDepsCheck
>        > Checking runtime dependencies for boto3-1.33.6-py3-none-any.whl
>        >   - botocore<1.34.0,>=1.33.6 not satisfied by version 1.34.21
>        >   - s3transfer<0.9.0,>=0.8.2 not satisfied by version 0.10.0
>        For full logs, run 'nix log /nix/store/6rfyikc9dkd51sk3n76lgrsmwv2vkr8j-python3.11-boto3-1.34.21.drv'.
> ```

Thanks for the review! I added pythonRelaxDepsHook to boto3 package to fix that.
I will wait for the CI to pass, to rebase this PR against staging (500+ rebuilds)

**Comment by anthonyroussel** [comment]
Fixed moto build by upgrading moto & py-partiql-parser packages

**Comment by anthonyroussel** [comment]
CI pass, rebased PR against staging

**Comment by NickCao** [comment]
Need rebase.

**Comment by anthonyroussel** [comment]
Rebased against staging

**Review by SuperSandro2000 — APPROVED** [review]
Can you do another rebase? I didn't check the changelog of every package and if dependencies changed.

**Comment by mweinelt** [comment]
Dropped the awscrt bump, since staging had a newer version.

**Pull request merged**
