### PR TITLE
pahole: 1.26 -> 1.27

### PR DESCRIPTION
**Pull request by martinetd**
## Description of changes

(Note I don't have enough cpu/disk to build a linux kernel with this, so letting ofborg do the work... Always a bit of a bet on staging. Maybe someday...)

From the release e-mail:

```
        The v1.27 release of pahole and its friends is out, supporting
parallel reproducible builds and encoding kernel kfuncs in BTF, allowing
tools such as bpftrace to enumerate the available kfuncs and obtain its
function signatures and return types.

BTF encoder:

- Inject kfunc decl tags into BTF from the BTF IDs ELF section in the Linux
  kernel vmlinux file.
  
  This allows tools such as bpftools and pfunct to enumerate the available kfuncs
  and to gets its function signature, the type of its return and of its
  arguments. See the example in the BTF loader changes description, below.

- Support parallel reproducible builds, where it doesn't matter how many
  threads are used, the end BTF encoding result is the same.

- Sanitize unsupported DWARF int type with greater-than-16 byte, as BTF doesn't
  support it.

BTF loader:

- Initial support for BTF_KIND_DECL_TAG:

  $ pfunct --prototypes -F btf vmlinux.btf.decl_tag,decl_tag_kfuncs | grep ^bpf_kfunc | head
  bpf_kfunc void cubictcp_init(struct sock * sk);
  bpf_kfunc void cubictcp_cwnd_event(struct sock * sk, enum tcp_ca_event event);
  bpf_kfunc void cubictcp_cong_avoid(struct sock * sk, u32 ack, u32 acked);
  bpf_kfunc u32 cubictcp_recalc_ssthresh(struct sock * sk);
  bpf_kfunc void cubictcp_state(struct sock * sk, u8 new_state);
  bpf_kfunc void cubictcp_acked(struct sock * sk, const struct ack_sample  * sample);
  bpf_kfunc int bpf_iter_css_new(struct bpf_iter_css * it, struct cgroup_subsys_state * start, unsigned
int flags);
  bpf_kfunc struct cgroup_subsys_state * bpf_iter_css_next(struct bpf_iter_css * it);
  bpf_kfunc void bpf_iter_css_destroy(struct bpf_iter_css * it);
  bpf_kfunc s64 bpf_map_sum_elem_count(const struct bpf_map  * map);
  $ pfunct --prototypes -F btf vmlinux.btf.decl_tag,decl_tag_kfuncs | grep ^bpf_kfunc | wc -l
  116
  $

pretty printing:

- Fix hole discovery with inheritance in C++.
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by martinetd** [comment]
ofborg tests passed, yay.
I'm surprise it didn't add Ccs, so here: @bosu

BTW @delroth -- they added `--btf_features=+reproducible_build` to build the BTF output in a consistent manner even with multiple threads; I'll send a patch to enable it by default if SOURCE_DATE_EPOCH is set at which point we'll be able to drop the threading-reproducibility.patch

**Comment by martinetd** [comment]
> BTW @delroth -- they added --btf_features=+reproducible_build to build the BTF output in a consistent manner even with multiple threads; I'll send a patch to enable it by default if SOURCE_DATE_EPOCH is set at which point we'll be able to drop the threading-reproducibility.patch

That wasn't so bad so updated patch. The output is identical to -j1 output from what I could see.

**Comment by martinetd** [comment]
Note this apparently introduces a regression in linux builds with clang with LTO enabled:
- https://lkml.kernel.org/r/20240613214019.GA1423015@thelio-3990X
- https://github.com/acmel/dwarves/issues/53

I don't think we actively do that, but on the other hand there's no strict hurry to merge this either, so let's put this on hold until that is fixed

**Comment by martinetd** [comment]
> Note this apparently introduces a regression in linux builds with clang with LTO enabled:

I was expecting a new release with it but it's been fixed without such ceremony, so I picked the patch up.

Also didn't get any response to the reproducibility patch so resent it by e-mail, let's see how that one goes.. This PR was only waiting for the clang fix, so marked as ready again.

**Comment by vcunat** [comment]
I believe there's no use in pinging Delroth anymore: https://github.com/NixOS/nixpkgs/pull/307173

**Comment by martinetd** [comment]
Doh, thanks for the heads up.
And thanks for merging as well.

FWIW that patch was more or less refused upstream after a few exchanges with upstream, between pahole folks telling me that this belongs in kbuild, and kbuild folks saying this deserves a new .config option... let's just keep that harmless patch around for now.

**Comment by PedroHLC** [comment]
> I don't think we actively do that, but on the other hand there's no strict hurry to merge this either, so let's put this on hold until that is fixed

Maybe I should upstream a kernel built with Clang and LTO (would help to assert our kernel modules build against this scenario), [mine](https://www.nyx.chaotic.cx/#t-t1-packages) broke after this bump :cry:

**Comment by PedroHLC** [comment]
> I don't think we actively do that, but on the other hand there's no strict hurry to merge this either, so let's put this on hold until that is fixed

Maybe I should upstream a kernel built with Clang and LTO (would help to assert our kernel modules build against this scenario), [mine](https://www.nyx.chaotic.cx/#t-t1-packages) broke after this bump :cry: 

**EDIT** Solution is a second patch by Arnaldo: https://lore.kernel.org/all/ZnGZ71a4E29kPrvS@x1/

**Comment by martinetd** [comment]
@PedroHLC doh, sorry... I wish he'd just tagged a fix release instead of posting patches like this :/

especially since on https://github.com/acmel/dwarves/issues/53 someone commented the other patch was enough..

I've just opened https://github.com/NixOS/nixpkgs/pull/331589 - if you could confirm it works manually that'd be great.
Long term I agree a test would be welcome, the bpf nixos test builds the regular kernel as a dependency but we could use a minimal clang kernel build test. Heck, I can't even build a kernel on my machines because we have way too many modules enabled, I need to figure out how to build a minimal virt kernel so I can run these tests properly... but at least ofborg would build it for now!

**Pull request merged**
