### PR TITLE
haskellPackages: Add buildFromCabalSdist (faster, tested)

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

A faster `buildFromSdist`, with tests. For use in out-of-tree projects. Triggered by https://github.com/NixOS/nixpkgs/pull/173800#issuecomment-1133597710

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
@ofborg build tests.haskell.cabalSdist

**Comment by maralorn** [comment]
How common do we think would people encounter breakage if we just changed the existing buildFromSdist?
I am a bit careful with adding more functions with subtle differences to our lib.

Do you have a reason for adding those functions in another file then the original one?

**Comment by roberth** [comment]
> Do you have a reason for adding those functions in another file then the original one?

It needs to access the package set for `buildHaskellPackages.cabal-install`, which is not something we can access in `haskell.lib`, unless there's some trickery I'm not aware of.

> How common do we think would people encounter breakage if we just changed the existing buildFromSdist?

It seems that `cabal sdist` does not support custom `./Setup sdist` behavior, so hypothetically, a package could have its own custom / customized `sdist` logic that the new function won't invoke. This seems unlikely though, as `cabal-install` command users would already be unable to use such custom logic.

**Review by maralorn — APPROVED** [review]
1. I think the implementation is very good, thanks for the test!
2. I realized that my fear of making our library more confusing is 100% a documentation problem and giving the users different options for (even mildly) different usecases is exactly right.

I am okay with merging this. Any objections @NixOS/haskell ?

**Pull request merged**
