### PR TITLE
python3.pkgs.pvlib: add missing build dependencies

### PR DESCRIPTION
**Pull request by tjni**
## Description of changes

These are needed now that https://github.com/NixOS/nixpkgs/pull/248866 is committed.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
@ofborg build python310Packages.pvlib python311Packages.pvlib

**Comment by onny** [comment]
These are a lot of PRs following the python build helper change. Can these be put into one single PR?

**Comment by tjni** [comment]
> These are a lot of PRs following the python build helper change. Can these be put into one single PR?

I don't have a strong opinion on this. This is an artifact of my working process: I would finish one issue, post a PR to get the review and CI machinery started, and then move on to the next one. I'm never sure if I will have the energy to finish the next issue I start working on. I can certainly batch them into larger PRs.

**Comment by onny** [comment]
Maybe it depends on how much Python PRs regarding this issue will follow. Is it more than 30 PRs maybe bundling them would be better

**Comment by tjni** [comment]
There are currently 64 remaining known breakages that I am making my way through in https://github.com/NixOS/nixpkgs/issues/247287. I'll be more mindful of the number of PRs and batch some of them together moving forward.

**Comment by onny** [comment]
Nice, thank you so much for your work

**Review by natsukium — APPROVED** [review]

**Pull request merged**
