### PR TITLE
hipchat: 2.2.1388 -> 4.0.1631

### PR DESCRIPTION
**Pull request by puffnfresh**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS (x86_64)
  - [ ] Linux (x86_64)
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @jgeerds

### CODE REVIEW

**Comment by joachifm** [comment]
Built this locally. Running `result/bin/hipchat` fails, however: `[...] libexec/hipchat/lib/HipChat.bin: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`. Not on NixOS.

Probably not a regression, though.

**Comment by puffnfresh** [comment]
@joachifm does adding mesa on the search path work?

**Comment by joachifm** [comment]
@puffnfresh yep, but then I get other run-time link errors. Anyway, I'm not too concerned, as I don't intend to use hipchat. I doubt this PR caused the issue, so I'm fine with merging it.

**Comment by puffnfresh** [comment]
@joachifm it would be great if you posted the linker problems. I'd love to get this working on more systems than mine.

**Comment by joachifm** [comment]
Sure: https://gist.github.com/joachifm/80443ceca80775e8071e Don't know how useful that is. Looks to me like it can't find qt components. My impression is that some things that should be hardcoded are not.

**Comment by copumpkin** [comment]
Can we have the HipChat server in Nix as well? :smile:

**Comment by puffnfresh** [comment]
@joachifm I'm not sure why, but it seems your /usr/lib is being picked up and it has a different QT version. It's possible that it would work with the last version (by coincidentally sharing the same version of QT) but also possible that it wouldn't, since I don't think I changed anything around that.

@copumpkin yes, we should have all Atlassian software packaged!

**Comment by globin** [comment]
@fpletz is at least working on crowd, confluence and jira

**Pull request merged**
