### PR TITLE
ultrastar-creator/ultrastar-manager: wrapQtAppsHook

### PR DESCRIPTION
**Pull request by Profpatsch**
It was impossible to start them from a nix shell because they were not
wrapped.

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
@Profpatsch If these are purely qt applications then they've already been packaged incorrectly if they fail at runtime.

A qt app should be called with `libsForQt5.callPackage` in `all-packages.nix` and use `mkDerivation` as opposed to `stdenv.mkDerivation`. And that's  the qt specific deriver which automatically adds `wrapQtAppsHook` to `nativeBuildInputs`. Hence if this was packaged correctly there would be no need for such a change.

**Comment by Profpatsch** [comment]
> A qt app should be called with `libsForQt5.callPackage` in `all-packages.nix` and use `mkDerivation` as opposed to `stdenv.mkDerivation`. And that's the qt specific deriver which automatically adds `wrapQtAppsHook` to `nativeBuildInputs`. Hence if this was packaged correctly there would be no need for such a change.

Yeah, but I don’t really care, it has been working apart from that, and I don’t have the time to rewrite this.

**Comment by worldofpeace** [comment]
@Profpatsch Umm, I guess I'll just push the changes then...

**Comment by worldofpeace** [comment]
backported in 24d8fb80c0efd6ca987778d328bbaadfd616392b 8b4fbb8d315f33f4f92b2eaa8a0c24ae6df9076b

**Pull request merged**
