### PR TITLE
ashuffle: 3.4.0 -> 3.10.1

### PR DESCRIPTION
**Pull request by tcbravo**
###### Motivation for this change

Updating to the [latest version](https://github.com/joshkunz/ashuffle/releases), which has a few [additional options](https://github.com/joshkunz/ashuffle#advanced-options-for-specialized-preferences-with---tweak).

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113413` at 3a367a7d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/1e0725056d74a933ee6e2e9ee46dec04">ashuffle</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/meson-cmake.md">meson-cmake</a>

Meson uses CMake as a fallback dependency resolution method and it likely is not necessary here. The message about cmake not being found is purely informational.

Near pkgs/applications/audio/ashuffle/default.nix:24:3:
```
   |
24 |   nativeBuildInputs = [ cmake pkg-config meson ninja ];
   |   ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113413` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>ashuffle</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
ashuffle:
<details>


Meson uses CMake as a fallback dependency resolution method and it likely is not necessary here. The message about cmake not being found is purely informational.

Near pkgs/applications/audio/ashuffle/default.nix:24:3:

```
   |
24 |   nativeBuildInputs = [ cmake pkg-config meson ninja ];
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/meson-cmake.md
</details>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113413` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>ashuffle</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
ashuffle:
<details>


Meson uses CMake as a fallback dependency resolution method and it likely is not necessary here. The message about cmake not being found is purely informational.

Near pkgs/applications/audio/ashuffle/default.nix:24:3:

```
   |
24 |   nativeBuildInputs = [ cmake pkg-config meson ninja ];
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/meson-cmake.md
</details>
</details>

**Comment by tcbravo** [comment]
@SuperSandro2000 While `ashuffle` itself builds with `meson`, its git submodules use `cmake`, so both are needed in `nativeBuildInputs`. See previous discussion here: https://github.com/NixOS/nixpkgs/pull/89186#discussion_r432827075

**Pull request merged**
