### PR TITLE
treewide: remove @sdll from maintainers

### PR DESCRIPTION
**Pull request by trofi**
sdll github handle returns 404. Sasha agreed to remove @sdll
maintainer entry.

Noticed when tried to CC maintainer in https://github.com/NixOS/nixpkgs/issues/138371

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
@ofborg eval

**Comment by figsoda** [comment]
i personally prefer having
```
maintainers = with maintainers; [ ];
```
instead of removing the whole line

**Comment by figsoda** [comment]
cc @aptlin

**Comment by trofi** [comment]
Sounds good. Switched to `maintainers = with maintainers; [ ];`.

Perhaps it's worth backfilling it to all packages and have a warning (or error) to avoid divergence in future?

**Comment by figsoda** [comment]
I think its a good thing to add checks to enforce styling guidelines, but changing mkDerivation for this is probably not worth it

maybe we can have some kind of style lints in ofborg to make sure that at least new packages does it

**Comment by SuperSandro2000** [comment]
> maybe we can have some kind of style lints in ofborg to make sure that at least new packages does it

New package are already blocked in review if no maintainer is added.

**Pull request merged**
