### PR TITLE
super-user-spark 0.3.2.0-dev -> 0.4.0.1

### PR DESCRIPTION
**Pull request by NorfairKing**
###### Motivation for this change

Upgrade.

###### Disclaimer

This is my first contribution and I'm not sure how to test this change. Please help?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @badi

### CODE REVIEW

**Comment by badi** [comment]
Hi! Welcome!

You can test by running 

```
nix-build -A super-user-spark
```

in the root of your nixpkgs checkout (I like adding `--dry-run` to see a plan first).

A successful build will create `$PWD/result` as a symlink to the installation so you can run eg:

```
./result/bin/spark parse ...
```

---

I get the following on a `nix-build`:

```
test/SuperUserSpark/Compiler/Gen.hs:29:10: error:
    • Could not deduce (GenUnchecked a)
        arising from a use of ‘Data.GenValidity.$dmshrinkValid’
      from the context: GenValid a
        bound by the instance declaration
        at test/SuperUserSpark/Compiler/Gen.hs:(29,10)-(30,32)
      Possible fix:
        add (GenUnchecked a) to the context of the instance declaration
    • In the expression:
        Data.GenValidity.$dmshrinkValid @(Deployment a)
      In an equation for ‘shrinkValid’:
          shrinkValid = Data.GenValidity.$dmshrinkValid @(Deployment a)
      In the instance declaration for ‘GenValid (Deployment a)’
   |
29 | instance GenValid a =>
   |          ^^^^^^^^^^^^^...

test/SuperUserSpark/Compiler/Gen.hs:36:10: error:
    • Could not deduce (GenUnchecked a)
        arising from a use of ‘Data.GenValidity.$dmshrinkValid’
      from the context: GenValid a
        bound by the instance declaration
        at test/SuperUserSpark/Compiler/Gen.hs:(36,10)-(37,42)
      Possible fix:
        add (GenUnchecked a) to the context of the instance declaration
    • In the expression:
        Data.GenValidity.$dmshrinkValid @(DeploymentDirections a)
      In an equation for ‘shrinkValid’:
          shrinkValid
            = Data.GenValidity.$dmshrinkValid @(DeploymentDirections a)
      In the instance declaration for ‘GenValid (DeploymentDirections a)’
   |
36 | instance GenValid a =>
   |          ^^^^^^^^^^^^^...
```

**Comment by NorfairKing** [comment]
Alright @badi Great feedback. I just released (on hackage) a new version that doesn't have this build error.
The tests pass for me locally but not on nix, so I turned them off for now.

**Review by badmutex — APPROVED** [review]

**Comment by jlesquembre** [comment]
I think we can close this and continue on #78790

**Comment by jlesquembre** [comment]
I'm closing it, because of #78790. @NorfairKing I see that you don't plan to maintain `super-user-spark`, should we close the other PR as well and remove it from nixpkgs? I'm still using it to manage my dotfiles, probably is a good time to start using `home-manager`

**Comment by NorfairKing** [comment]
@jlesquembre Yes let's remove it from nixpkgs.
Thanks for closing this.

**Comment by jlesquembre** [comment]
Thanks @NorfairKing , I created a PR to remove it: #87379

**Pull request closed without merging**
