### PR TITLE
radicale: 3.1.0 -> 3.1.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/Kozea/Radicale/blob/v3.1.3/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
```
       > FAILED radicale/tests/test_base.py::TestBaseRequests::test_put_whole_calendar
       > FAILED radicale/tests/test_storage.py::TestMultiFileSystem::test_put_whole_calendar_uids_used_as_file_names
```

I'm getting two test failures on x86_64-linux, could you have a look into that?
Also if you want you could add me as maintainer for radicale!

**Comment by dotlambda** [comment]
> I'm getting two test failures on x86_64-linux, could you have a look into that?

See https://github.com/NixOS/nixpkgs/issues/153473. I'm working with @kraem to resolve that issue upstream.



> Also if you want you could add me as maintainer for radicale!

Done.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 155742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>etesync-dav</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>radicale (radicale3)</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 155742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>etesync-dav</li>
    <li>radicale (radicale3)</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@ofborg build radicale etesync-dav
@ofborg test radicale

**Comment by erictapen** [comment]
@dotlambda 
I'm still getting the same test failure for radicale?

```
       > =========================== short test summary info ============================
       > FAILED radicale/tests/test_base.py::TestBaseRequests::test_put_whole_calendar
       > FAILED radicale/tests/test_storage.py::TestMultiFileSystem::test_put_whole_calendar_uids_used_as_file_names
       > ================== 2 failed, 162 passed, 1 skipped in 29.36s ===================

```

**Comment by dotlambda** [comment]
> I'm still getting the same test failure for radicale?

I know, but it's already broken on master. Should we revert to 3.0.6?

**Comment by kraem** [comment]
@dotlambda it's actually patched on upstream master now. should we track master and set a date version?

@erictapen you could patch it like so in the mean time:
```
nixpkgs.overlays = [
  (self: super: {
    radicale3 = super.radicale3.overrideAttrs ( oldAttrs: {
      name = "radicale-${self.radicale3.version}";
      version = "22-02-01";
      src = pkgs.fetchFromGitHub {
        owner = "Kozea";
        repo = "Radicale";
        rev = "580b97fa0f62e802a42f18896498a81fdc93da1a";
        sha256 = "1phvl5k6fqwxqzh5rjrpjk4hcb5h7vp2wiqymzvgc6mchcvdg0v4";
      };
    });
  })
];

```

**Pull request merged**
