### PR TITLE
xfce4-panel: 4.18.2 -> 4.19.0

### PR DESCRIPTION
**Pull request by ghost**
Built on top of PR #223611 (soft dependency, this needs to be merged after, or rebased onto master)

###### Description of changes

libxfce4windowing: init at 4.19.1
    
Update xfce4-panel to 4.19.0, libxfce4windowing is a new dependency (along with gtk-layer-shell).

[xfce4-panel 4.19](https://gitlab.xfce.org/xfce/xfce4-panel/-/blob/master/NEWS)
[libxfce4windowing 4.19.1](https://gitlab.xfce.org/xfce/libxfce4windowing/-/blob/main/NEWS)

@teams.xfce.members: @romildo @muscaln

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
Usually we package only stable releases of xfce components in nixpkgs.
xfce4-panel 4.19 is a development (unstable) version.

**Comment by simplejack-src** [comment]
That seems a sensible default.
However, given the relatively slow rate of releases (XFCE roadmap vs. other DE's) I would also see value in carrying the latest development release. In particular, this is beneficial both for the XFCE project (some downstream users trying development releases and reporting back bugs which then can be fixed and not to make it into the final release), and NixOS (as staging changes here wouldn't popup as stable-bumps-before-release problems).

Given this, I think it may be prudent to have a 'dev-version' attribute in relevant packages (where it would differ from 'version'). Now implementation wise, to keep the derivation churn to a minimum (can't have a 'dev-version' bump causing a rebuild of stable) this would likely require a refactor to the 'sources.nix' paradigm (used in wine and other area of nixpkgs). In addition, I would use a selector attribute 'devVersion ? false' (in the top-level XFCE file) to keep the number of top-level attributes the same (with the downside being no default exposed 'devVersion=true' attribute means no Cachix support).

Thoughts about such a refactor?

[I'm not sure who else to tag as an interested party for such a refactor (only you two are on the maintainers list ;))]

**Comment by romildo** [comment]
Lately I am not having much time to dedicate to this, and I wouldn't go for this refactoring.

But it would be interesting to see what other desktop maintainers think about the idea. For instance, @jtojnar .and @bobby285271

**Comment by jtojnar** [comment]
If the component is trivially swappable and you do not think having a second copy would cause too much extra maintenance burden, sure go for it.

For GNOME, lot of the components are closely coupled so we would need to package almost everything. And when we had multiple versions packaged simultaneously in the past, it was a mess of the expressions slowly diverging. And `git blame` is still confused by the history suddenly stopping when a new version was added.

**Comment by simplejack-src** [comment]
@jtojnar XFCE components in general are loosely coupled (as oppose to your example of GNOME), however, with the way current Linux desktop environments are going (seem to be moving farther apart), it's not difficult to imagine this scenario.

@romildo Your NAK alone to me means this isn't worth the effort (at this time). I know maintainers are already stretched thin, so I wouldn't want to add anything that would make your job harder. Eventually, I hope to add myself to the maintainers list (but I'm busy on too many other projects at the moment). When I am able though, I'll reevaluate and perhaps put this style of a refactor up for consideration again.

Thanks folks,

P.S. @romildo I couldn't tempt you into a quick review/merge of #223611 ?

**Pull request closed without merging**
