### PR TITLE
nextcloud27: 27.1.5 -> 27.1.6, nextcloud26: 26.0.10 -> 26.0.11

### PR DESCRIPTION
**Pull request by AkechiShiro**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I'm running the nixos tests, right now, will EDIT with the results.

EDIT : Test ran successfully, only saw failure on a specific davfs secret command, this may or may not be relevant, I'm not sure but here is a part of the logs where the failure shown up.
```
client # [  101.438824] mount.davfs[1010]: opening /etc/davfs2/secrets failed
```
More logs around this failure : 
```
(finished: must succeed: /nix/store/sn9ahx5b1bccdgr3hcxrsbnrwr72d97a-with-rclone-env /nix/store/0klypggdljipylmpz4xkw7wycn74nfyi-diff-shared-file, in 3.65 seconds)
client: must succeed: cat /mnt/dav/test-shared-file
client # [  101.415158] mount.davfs[1010]: davfs2 1.7.0
client # [  101.438824] mount.davfs[1010]: opening /etc/davfs2/secrets failed
client # [   93.256441] systemd[1]: mnt-dav.automount: Got automount request for /mnt/dav, triggered by 981 (cat)
client # [   93.263887] systemd[1]: Reached target Network is Online.
client # [   93.277429] systemd[1]: Mounting /mnt/dav...
client # [   93.405647] mount.davfs[985]: davfs2 1.7.0
client # [   93.421298] mount.davfs[985]: opening /etc/davfs2/secrets failed
```
---
@Ma27 @bachp @globin @schneefux 

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 283820` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nextcloud26</li>
    <li>nextcloud27</li>
  </ul>
</details>

**Review by bachp — APPROVED** [review]
Deployed on my instance and everthing works.

**Comment by Ma27** [comment]
I'll take a look at the davfs2 thingie, but this isn't related to your change, so I'll merge this now.

**Comment by Ma27** [comment]
> I'll take a look at the davfs2 thingie, but this isn't related to your change, so I'll merge this now.

Now that I think of it, the issue is there for a while (I suspected an unrelated commit to be the cause yesterday) because I think I've seen it already in the past.

Anyways, `/etc/davfs2/secrets` isn't supposed to exist because the test writes its credentials into `/tmp`. No idea why `davfs2` complains, but the file from davfs is clearly readable (otherwise the test would fail), so this is a bug in davfs2 at best and not an issue with this test.

**Pull request merged**
