### PR TITLE
[nomerge] [WIP] make Xen compatible with EFI booting

### PR DESCRIPTION
**Pull request by telent**
This is my attempt at fixing #12225 and it supersedes the attachment in that issue.  I do not claim it's ready for merge yet or even that it works

### CODE REVIEW

**Comment by telent** [comment]
it looks like I have to enhance `gummiboot-builder.py` to include xen-specific config in the same way as `install-grub.pl` does for legacy boots

**Comment by telent** [comment]
This boots and runs under VirtualBox, modulo some kind of framebuffer corruption that makes the console unreadable.  I can't presently use it on real hardware, because my laptop (2012-era Samsung) is now having a major sulk about booting *anything* in EFI mode and I've had to reinstall it using CSM.

That being so, I actually have no immediate use for any of this work.  If anyone wants to pick it up and try it/take it over/report back, all those options are acceptable to me ;-)

```[dan@snot1:~/nixpkgs]$ ls -l /sys/firmware/efi/
total 0
-r--r--r--  1 root root 4096 Jan 11 09:10 config_table
drwxr-xr-x  2 root root    0 Jan  8 16:08 efivars
-r--r--r--  1 root root 4096 Jan 11 09:10 fw_platform_size
-r--------  1 root root 4096 Jan 11 09:10 systab
drwxr-xr-x 52 root root    0 Jan  8 16:08 vars

[dan@snot1:~/nixpkgs]$ ls -l /proc/xen/
total 0
-r--r--r-- 1 root root 0 Jan  8 16:08 capabilities
-rw------- 1 root root 0 Jan  8 16:08 privcmd
-rw------- 1 root root 0 Jan  8 16:08 xenbus
-rw------- 1 root root 0 Jan  8 16:08 xsd_kva
-rw------- 1 root root 0 Jan  8 16:08 xsd_port
```

**Comment by jagajaga** [comment]
Any progress?

**Comment by domenkozar** [comment]
See also https://github.com/jakogut/xen-igvtg-aur/blob/master/xen_efi_build.patch

**Comment by 7c6f434c** [comment]
Apparently the task turned out to be even more complicated than expected… Closing, as I guess any new effort will be different enough to be a new PR.

**Pull request closed without merging**
