### PR TITLE
nodePackages: update

### PR DESCRIPTION
**Pull request by Kranzes**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by dotlambda** [comment]
Are you doing this to update a specific package? If so, I suggest you help us with #229475.

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 266490` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>lighthouse</li>
    <li>wrangler</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>akkoma-frontends.akkoma-fe</li>
    <li>balena-cli</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emojione</li>
    <li>fast-cli</li>
    <li>graphite-cli</li>
    <li>image_optim</li>
    <li>joplin</li>
    <li>lemmy-ui</li>
    <li>lunarvim</li>
    <li>lv_img_conv</li>
    <li>nodehun</li>
    <li>openvscode-server</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>sloc</li>
    <li>snyk</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Review by Luflosi — APPROVED** [review]

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 266490` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>wrangler</li>
  </ul>
</details>
<details>
  <summary>35 packages built:</summary>
  <ul>
    <li>akkoma-frontends.akkoma-fe</li>
    <li>balena-cli</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emojione</li>
    <li>fast-cli</li>
    <li>graphite-cli</li>
    <li>image_optim</li>
    <li>joplin</li>
    <li>lemmy-ui</li>
    <li>lighthouse</li>
    <li>lunarvim</li>
    <li>lv_img_conv</li>
    <li>nodehun</li>
    <li>openvscode-server</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>sloc</li>
    <li>snyk</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Review by dotlambda — APPROVED** [review]

**Pull request merged**
