### PR TITLE
oraclejdk: 8u191 -> 8u201, 8u202 [Security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

Security fixes and other updates.

https://www.oracle.com/technetwork/java/javase/8u201-relnotes-5209271.html
https://www.oracle.com/technetwork/java/javase/8u202-relnotes-5209339.html
https://www.oracle.com/technetwork/security-advisory/cpujan2019-5072801.html#AppendixJAVA

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested only x86_64.

---

### CODE REVIEW

**Review by pSub — CHANGES_REQUESTED** [review]
I think you want to change the build Version in `jdk8cpu-linux.nix` to 202 as well.

**Comment by taku0** [comment]
@pSub 8u201 is a CPU, which contains only security updates, and 8u202 is a PSU, which contains CPU + other updates. They have different version numbers.

**Comment by taku0** [comment]
cc: @volth, @mic92

**Comment by Mic92** [comment]
[detached HEAD c983626f121] oraclejdk: 8u191 -> 8u201, 8u202
 Author: taku0 <mxxouy6x3m_github@tatapa.org>
 Date: Fri Jan 18 21:28:24 2019 +0900
 2 files changed, 7 insertions(+), 7 deletions(-)

**Pull request merged**
