### PR TITLE
 sickgear: 0.24.15 → 0.25.11 

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
@Artturin, encountered the same issue but as far as I can tell it is expected behaviour when not configured. (Also happens with the current version on the main branch)

Best seek or wait for a user or maintainer to test this.

**Comment by Artturin** [comment]
runs

**Comment by rembo10** [comment]
Wait so the SickBeard.py was being copied for the NixOS service. So there was one sickbeard service and depending on the package it would use sickbeard, sickgear or sickrage. So this change breaks the service.

**Comment by rembo10** [comment]
Changing the ExecStart in the service from `${sickbeard}/SickBeard.py` to `${sickbeard}/bin/${sickbeard.pname}`

I think will fix it (sickrage, for example, no longer ships the SickBeard.py file).... so I think this is the best solution? But I'm not 100% sure

**Comment by Artturin** [comment]
sickrage should be changed to install to $out/opt too

**Comment by rembo10** [comment]
I'm working on it now. The newer versions require python3

**Comment by fabianhjr** [comment]
>  So I need to include all of those packages from nix in the build (I only ask because there are a lot of them sweat_smile

If it is overwheliming you could leave the current version (which still had dependencies in `/lib`) and leave the version bump for a future person to do the refactoring.

**Pull request merged**
