### PR TITLE
elm-pages: set files/dirs as +w when copied during elm-init

### PR DESCRIPTION
**Pull request by qbit**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turboMaCk** [comment]
I wonder if you consider trying to upstream this patch? It seems to me that ensuring permissions is something that upstream should consider doing themselves.

**Comment by qbit** [comment]
I thought about it, but I am not entirely sure others will encounter this problem. That said, I think my `walknDo` function could be used to replace that `fx-extra` lib >.>.

**Comment by turboMaCk** [comment]
I think similar problem to what this solves applies to quite a few tools from elmPackages. I have no problem with this fix as is but perhaps it might make sense to think if we can either make it esier for upstreams to avoid this issue or at least for us to patch packages in nixpkgs directly.

**Comment by turboMaCk** [comment]
Sorry @qbit I completely forgot about this PR. Now we've merged other PR that should have addressed this problem.

Personally I would still consider up-streaming these patches in some way. But for now we will just patch it. Don't hesitate to ping me when you need another review. I will try to see it through to the successful merge next time.

**Pull request closed without merging**
