### PR TITLE
flare-signal: 0.9.1 -> 0.10.0

### PR DESCRIPTION
**Pull request by SuperSamus**
Changelog: https://gitlab.com/schmiddi-on-mobile/flare/-/blob/0.9.3/CHANGELOG.md

Diff: https://gitlab.com/schmiddi-on-mobile/flare/-/compare/0.9.1...0.9.3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 250235` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flare-signal</li>
  </ul>
</details>

**Review by dotlambda — COMMENTED** [review]
Linking fails with
```
[2023-08-30T23:52:30Z ERROR libsignal_service::websocket] SignalWebSocket: Websocket error: end of web request stream; socket closing
[2023-08-30T23:52:33Z ERROR libsignal_service::websocket] SignalWebSocket: Websocket error: SignalWebSocket: end of application request stream; socket closing
```

**Comment by SuperSamus** [comment]
It's just a UI bug: after linking, close and reopen Flare, and test with a note to self, you should receive it on the phone.
Also, FYI, linking is *actually* broken on 0.9.1, so having the buggy UI is still an improvement.

**Comment by dotlambda** [comment]
Flare says it's offline after launching it. I was able to receive one message but that disappeared after re-launching flare.
Also, "add conversation" doesn't seem to be doing anything.

**Comment by dotlambda** [comment]
Some things work, so I'm merging this anyway.

**Pull request merged**
