### PR TITLE
bambu-studio: add patches for Boost 1.86

### PR DESCRIPTION
**Pull request by emilazy**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
@ofborg eval

**Comment by dsluijk** [comment]
Haven't build it locally, but I am not sure if this is the right place for these patches. It seems like an issue with Bambu Studio itself, so the patches should be applied there. Or am I missing something?

**Comment by emilazy** [comment]
They are almost all from the [linked upstream PR](https://github.com/bambulab/BambuStudio/pull/3968) that has sadly stalled. Migrating packages to newer versions of Boost helps us cut down on the very large number of Boost versions we currently ship. It would be ideal if they were merged upstream, though, yes, but unfortunately it seems like a lot of PRs aren’t getting upstream attention.

**Comment by jchv** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359120`

---
### `x86_64-linux`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>

**Comment by jchv** [comment]
Diff LGTM, but it seems like some changes with Mesa are breaking the build. If I build the branch as-is it's fine, but rebased onto nixpkgs `master` this happens:

```
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: warning: libtbb.so.2, needed by /nix/store/yh9dva4nxd6aqazbv2yrx2mb6zbq00ba-openvdb-12.0.0/lib/libopenvdb.so, may conflict with libtbb.so.12
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: warning: libglapi.so.0, needed by /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so, not found (try using -rpath or -rpath-link)
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_set_dispatch'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_dispatch_table_size'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_set_context'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_context'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_dispatch'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_proc_address'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_tls_Dispatch'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_tls_Context'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/iar2mvmwp7b0j20pg38ka20wbcfck65b-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_add_dispatch'
       > collect2: error: ld returned 1 exit status
```

Looks like orca-slicer will need its own patching for GCC 14 as it fails on a totally different error, but it's already broken so that's neither here nor there.

(Though the build works fine before rebasing, the resulting build from before rebasing has the interesting property that it can't seem to initialize EGL unless I force it to use llvmpipe; this seems rather odd and I'm not sure what's going on there. I can only imagine it is also somehow related to why the build is currently failing.)

**Review by jchv — APPROVED** [review]
OK, thanks. Now it's working great for me and diff still LGTM. Interestingly, now I don't have to use llvmpipe, either. (Maybe that was caused by linking to OSMesa? Interesting.)

**Comment by jchv** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359120`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
  </ul>
</details>

**Comment by emilazy** [comment]
Yeah apparently OSMesa is effectively forcing software rendering, so I guess upstream worked around a driver bug with it or something in the past? But if it works without then cool.

**Pull request merged**
