### PR TITLE
wired: init at 0.10.6

### LINKED ISSUE #350144: Package request: wired-notify
**Project description**

A rusty notification daemon that's programmable and has interactable layout elements

**Metadata**

* homepage URL: https://github.com/Toqozz/wired-notify
* source URL: https://github.com/Toqozz/wired-notify
* license: MIT
* platforms:  linux
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fccapria**
Fixes #350144.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by zi3m5f — CHANGES_REQUESTED** [review]
Mostly LGTM

**Comment by fccapria** [comment]
Thanks @zi3m5f , i just solved everything.

**Comment by fccapria** [comment]
> Why do you differ from the upstream derivation in https://github.com/Toqozz/wired-notify/blob/master/flake.nix and what about the config and systemd files?

I tried to keep the `package.nix` as clean as possible: I relied on that derivation for the dependencies, but for the rest I left the classic compilation and build process (as the developer himself suggests in the README).
`wired` is a software that is launched as a daemon, similar to `dunst`, also for this reason I avoided copying the service; it is usually launched from the wm config.

Do you suggest including them anyway?

**Review by zi3m5f — CHANGES_REQUESTED** [review]
> I tried to keep the package.nix as clean as possible: I relied on that derivation for the dependencies, but for the rest I left the classic compilation and build process (as the developer himself suggests in the README).
wired is a software that is launched as a daemon, similar to dunst, also for this reason I avoided copying the service; it is usually launched from the wm config.

The developer includes the service in the repo and installs it and the config files here:
https://github.com/Toqozz/wired-notify/blob/043af1d042ebb9a553c7f84a647b75f93175dd4f/flake.nix#L49-L55

> Do you suggest including them anyway?

You don't have to for my approval.
But I think someone using upstreams flake overlay or package directly should be least surprised switching to our nixpkgs version.

**Comment by fccapria** [comment]
@zi3m5f I fixed the `package.nix` but with the rebase I created some problems with the previous commits.
Can you help me with this?

**Comment by fccapria** [comment]
@zi3m5f Thank you, you were super clear and very helpful!
I just committed the correct `package.nix` :)

**Comment by fccapria** [comment]
Just done!

**Review by zi3m5f — APPROVED** [review]

**Comment by fccapria** [comment]
@wegank @zi3m5f  Hi! Do I need more approvals to be merged? How does it work?

**Comment by VuiMuich** [comment]
@fccapria would you be willing to also contribute a relating home-manager module? If not I might have a try in a couple weeks, or so.

**Comment by fccapria** [comment]
> @fccapria would you be willing to also contribute a relating home-manager module? If not I might have a try in a couple weeks, or so.

Honestly I hadn't thought about it because I'm not familiar with writing modules. I'll probably look into it further, maybe write something, but if you'd like to do them, you're welcome! :)

**Pull request merged**
