### PR TITLE
Update jetbrains products

### PR DESCRIPTION
**Pull request by Gerschtli**
###### Motivation for this change

Run the `update.pl` script after manual fixing the src url for MPS.

Tested only `jetbrains.idea-ultimate` which worked.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Would you mind commiting your `update.pl`-fix here as well? :)

**Comment by Gerschtli** [comment]
Unfortunately this was a manual change in the default.nix file. I will work on an improved update script, when I have more time :)

**Comment by liff** [comment]
This looks to be a duplicate of #98194, which was merged.

**Comment by Gerschtli** [comment]
Yes, you are right. Closing this one.

**Pull request closed without merging**
