### PR TITLE
nixos/paperless: openFirewall option

### PR DESCRIPTION
**Pull request by evanrichter**
###### Description of changes

conveniently open the web interface port through the system firewall with the familiar `openFirewall` boolean.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

tagging maintainers :) @erikarvstedt @Flakebi @leona-ya

### CODE REVIEW

**Review by Flakebi — APPROVED** [review]
Thanks, looks good to me!

**Comment by leona-ya** [comment]
I'm not sure if I like this or not. To me, it's like a default to run web services behind a reverse proxy. But I'm fine with adding it if others see a use-case in it.

**Review by bjornfor — CHANGES_REQUESTED** [review]
> allows the web interface port through the system firewall

Please write commit message bodies as full sentences: capitalize first letter and end with a dot.

**Comment by evanrichter** [comment]
> I'm not sure if I like this or not. To me, it's like a default to run web services behind a reverse proxy. But I'm fine with adding it if others see a use-case in it.

For sure, I do that too after I decide on running a service for some time. But for quickly testing services, I like just having the port open on my local network as a convenience.

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Github claims there are code conflicts that must be solved.

**Comment by evanrichter** [comment]
fixed the conflict

**Comment by SuperSandro2000** [comment]
> I'm not sure if I like this or not. To me, it's like a default to run web services behind a reverse proxy. But I'm fine with adding it if others see a use-case in it.

I am thinking the same and I don't think we should promote running paperless without it.

**Comment by bjornfor** [comment]
> > I'm not sure if I like this or not. To me, it's like a default to run web services behind a reverse proxy. But I'm fine with adding it if others see a use-case in it.
> 
> I am thinking the same and I don't think we should promote running paperless without it.

Is paperless a special case? Because if not, I think we should leave it up to end users whether they want to access the service via a reverse proxy or not (and have a convenient openFirewall option to go along with it).

I suggest we merge, because `openFirewall` is a common and convenient option to have for services on NixOS.

**Comment by SuperSandro2000** [comment]
> Is paperless a special case? Because if not, I think we should leave it up to end users whether they want to access the service via a reverse proxy or not (and have a convenient openFirewall option to go along with it).

No, most services that are just plain HTTP do not have an openFirewall option because they don't need one. Also if we take a look at the upstream information available, they recommend using nginx as a reverse proxy to add TLS https://github.com/paperless-ngx/paperless-ngx/wiki/Using-a-Reverse-Proxy-with-Paperless-ngx and I couldn't find an option to do TLS in paperless itself.

In addition to that paperless is a service with very sensible and personal data and sending that unencrypted over the wire is irresponsible and dangerous. I think while it is important to give people freedom, we should prevent them from doing obviously irresponsible things and exposing their most sensitive data over plain text is one of it.

**Comment by bjornfor** [comment]
> No, most services that are just plain HTTP do not have an openFirewall option because they don't need one. 

It's a bit difficult to verify this statement, but the inverse is easy to check: searching for `openFirewall` in `man configuration.nix` shows several HTTP services.

So it seems to me that the argument is that paperless _is_ a special case, because it contains more sensitive data than many other services. I'm repeating myself, but I don't think NixOS can/should decide such things. And what if I want to run the reverse proxy on another host/container? Or what about other sensitive services, like samba? It seems rather arbitrary to me to reject this "openFirewall" instance.

I saw one openFirewall option that had a warning ("be careful!"). Maybe we should add that to paperless?

**Comment by SuperSandro2000** [comment]
Upstream is not recommending this and the usecase is not something we particularly want to support https://github.com/paperless-ngx/paperless-ngx/wiki/Using-a-Reverse-Proxy-with-Paperless-ngx

**Pull request closed without merging**
