### PR TITLE
Python: don't propagate blas

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done
- [x] Tested using sandboxing (`nix-build --option build-use-sandbox true` or [nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@adnelson I've included the numpy = self.numpy here for scipy_0_16

**Comment by FRidh** [comment]
(that's a nice 94 MB in closure size we win there)

**Comment by adnelson** [comment]
So these libraries link statically against openblas? Cool, sounds like a win

**Comment by FRidh** [comment]
Oops. They don't...

**Comment by adnelson** [comment]
OK, so that might be a problem then.....

**Comment by FRidh** [comment]
Yep! Reverted the relevant commits. I guess it's enough for today for me...

**Pull request merged**
