### PR TITLE
mruby: init at 1.4.1

### PR DESCRIPTION
**Pull request by nicknovitski**
I'm surprised it wasn't already in the repository.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- ~[ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)~)
- ~[ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`~
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- ~[ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)~
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by xeji — CHANGES_REQUESTED** [review]
Fix build

**Comment by xeji** [comment]
@GrahamcOfBorg build mruby

**Comment by nicknovitski** [comment]
@xeji Sorry, I was pushing possible fixes in order to easily have the expressions available to a linux build environment, but none of them ended up working

@samueldr Thank you!  Feel free to push those changes, and make yourself a maintainer too; I don't mind the responsibility, but I also don't think of myself as an expert.

**Comment by samueldr** [comment]
> @samueldr Thank you! Feel free to push those changes, and make yourself a maintainer too; I don't mind the responsibility, but I also don't think of myself as an expert.

Don't worry, being an expert isn't in itself required for being a maintainers. Sure it helps, but what's even better is caring for the package and somehow tracking its updates. I hope that, as a user, you'll keep track of mruby updates and provide the PRs as they come.

* * *

@GrahamcOfBorg  build mruby

**Comment by samueldr** [comment]
Oh, interesting how the `LD` thing needs to be conditional. Fixing.

**Review by xeji — APPROVED** [review]

**Pull request merged**
