### PR TITLE
nixos: add programs.wireshark option

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
To be able to use Wireshark as an ordinary user, the 'dumpcap' program
must be installed setuid root. This module module simplifies such a
configuration to simply:

```
programs.wireshark.enable = true;
```

The setuid wrapper is available for users in the 'wireshark' group.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rycee** [comment]
Wonderful! This is exactly what I set up manually. Would much rather just do `programs.wireshark.enable = true;` 👍

**Comment by globin** [comment]
I've changed this to use the setcap wrapper but this removes the possibility to add users to a group to allow this, what do you think?

**Comment by bjornfor** [comment]
@globin: What are the effects of that change? Less damage if dumpcap gets compromised, at the expense of allowing everyone on the system to monitor the packets? Would it be possible to use capabilities _and_ give access only to the 'wireshark' group? (I really like the 'wireshark' group feature.)

**Comment by globin** [comment]
Added support for setting permissions on setcap wrappers and set the permissions accordingly on wireshark. We don't need a static uid/gid as there is no data associated to them.

Are you fine with this?

**Comment by abbradar** [comment]
@globin Without statid gid this would break with `users.mutableUsers = false;` (if I remember correctly, that is).

**Comment by globin** [comment]
I'm quite sure gids never change on a rebuild, so this should work? I thought the problem was moving data from one machine to another and then not having deterministic uids/gids for the service the data belongs to?

**Comment by abbradar** [comment]
Funny, I remember that I needed to set fixed `gid`s when I moved to `mutableUsers = false` but I don't see any such restriction now in the code. If it works then 👍!

**Comment by rycee** [comment]
For what it's worth, I've been successfully using just `users.extraGroups.wireshark = {};` without any explicit group ID for quite some time on my system, also inside nixos-container instances.

**Comment by globin** [comment]
We can always still add it if something breaks, in the worst case one cannot execute wireshark without being root which is what we have right now :)

**Pull request merged**
