### PR TITLE
gohufont: add console version

### PR DESCRIPTION
**Pull request by rnhmjoj**
Requires #9576

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's names following our guide in `CONTRIBUTING.md`.

**Comment by rnhmjoj** [comment]
Is it ok?

**Comment by jagajaga** [comment]
Yes, but now there an additional changes in the PR..

**Comment by rnhmjoj** [comment]
@jagajaga Do I have to make a separate PR for the package I added?

**Comment by jagajaga** [comment]
Yes.

**Comment by rnhmjoj** [comment]
#9576 as been merged. It should build fine now.

**Pull request merged**
