### PR TITLE
Drop libnm-gtk

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
It is not used for anything any more (it was used by GNOME 2 control center).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
I suppose mate also does not use this?

**Comment by worldofpeace** [comment]
This wouldn't affect `nm-connection-editor` right?

**Comment by jtojnar** [comment]
Nope, `nm-connection-editor` uses libnma (modern version of `libnm-gtk` not using `libnm-glib`).

**Comment by jtojnar** [comment]
@Mic92 mate does not seem to depend on `networkmanagerapplet`. If it requires `nm-gtk` optionally, it is not currently enabled, so removing `nm-gtk` should not matter. And if mate maintainers wanted to enable it, it would break with next nm-applet release which will likely remove `nm-gtk`.

**Review by worldofpeace — APPROVED** [review]

**Comment by jerith666** [comment]
I just updated from 083220867c7 to ca2ba44cab4 and my `vpnc`-based vpn stopped working.  The error was: `Error: Connection activation failed: The VPN service 'org.freedesktop.NetworkManager.vpnc' was not installed.`

I reverted this merge and also 9efc9b5d9154e05767485dc4707e360bf0633eee, and it went back to working.

**Comment by jtojnar** [comment]
@jerith666 try https://github.com/NixOS/nixpkgs/pull/46201

**Comment by jerith666** [comment]
Yes, I just found that too!  Thanks!  :)

**Pull request merged**
