### PR TITLE
cryfs: 0.10.2 -> 0.11.1

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Package update.
Upstream now provides a way to use dependencies from nixpkgs ;
except for cryptopp and googletest.
Vendored cryptopp is v8.6.0 in cryfs 0.11.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by c0bw3b** [comment]
Just opening this for review after Christmas holidays. :)

Ping @midchildan for testing on a Darwin platform.
Could you maybe retest locally running the tests? Supposedly all tests using fuse are disabled so maybe they can succeed even on Darwin.

**Comment by midchildan** [comment]
The following change is needed to compile the vendored cyptopp with Clang:

```diff
diff --git a/pkgs/tools/filesystems/cryfs/default.nix b/pkgs/tools/filesystems/cryfs/default.nix
index 446f18661dc..5b927284c49 100644
--- a/pkgs/tools/filesystems/cryfs/default.nix
+++ b/pkgs/tools/filesystems/cryfs/default.nix
@@ -1,6 +1,7 @@
 { lib, stdenv, fetchFromGitHub
 , cmake, pkg-config, python3
 , boost, curl, fuse, openssl, range-v3, spdlog
+, llvmPackages
 # cryptopp and gtest on standby - using the vendored ones for now
 # see https://github.com/cryfs/cryfs/issues/369
 }:
@@ -40,7 +41,11 @@ stdenv.mkDerivation rec {
 
   strictDeps = true;
 
-  buildInputs = [ boost curl fuse openssl range-v3 spdlog ];
+  buildInputs = [ boost curl fuse openssl range-v3 spdlog ]
+    ++ lib.optionals stdenv.cc.isClang [
+      # needed to build the vendored cryptopp
+      llvmPackages.openmp
+    ];
 
   #checkInputs = [ gtest ];
 

```

**Comment by midchildan** [comment]
Unfortunately I'm seeing a regression in Boost that's preventing cryfs from compiling on Darwin. Boost is applying the namespace operator (`::`) on `sigemptyset` and other signal related functions, which are actually implemented as preprocessor macros on Darwin  and therefore not namespaced.

```
In file included from /tmp/nix-build-cryfs-0.11.1.drv-1/source/src/cpp-utils/process/subprocess.cpp:6:
In file included from include/boost/process.hpp:24:
In file included from include/boost/process/async_system.hpp:22:
In file included from include/boost/process/child.hpp:21:
In file included from include/boost/process/detail/child_decl.hpp:30:
include/boost/process/detail/posix/wait_for_exit.hpp:60:7: error: expected unqualified-id
    ::sigemptyset(&sigset);
      ^
```

**Comment by midchildan** [comment]
A bit of searching led me to boostorg/process#55 and #144610. It seems that using a newer version of Boost fixes the problem, so I updated the above patch to use `pkgs.boost17x` instead. After applying the patch, cryfs now builds and the tests pass too.

**Comment by midchildan** [comment]
I've confirmed that creating/mounting/reading/writing encrypted directories work as intended on Darwin.

**Comment by c0bw3b** [comment]
Thanks for those tests. I just pushed an update using `boost17x` by default on all platforms and re-enabling the check phase on Darwing.

**Comment by midchildan** [comment]
I should've mentioned this, but the check phase  can't be enabled for Darwin on Hydra because it requires a full installation of macFUSE. Nixpkgs only includes a compile time stub for libfuse. [Here's ](https://github.com/NixOS/nixpkgs/blob/master/doc/builders/packages/fuse.section.md) a bit of additional context if you're interested.

With Darwin, the check phase for FUSE packages needs to be run locally.

**Comment by veprbl** [comment]
I see on staging-next:
```
error: anonymous function at /nix/store/j5fhw348rsazaxad115xmf1bf683fdsg-source/pkgs/tools/filesystems/cryfs/default.nix:1:1 called with unexpected argument 'boost'
```

@GrahamcOfBorg eval

**Comment by veprbl** [comment]
Fixed on staging-next in a38c345989a936ffaa66fe80235719af4f04e246

**Comment by veprbl** [comment]
However this still regresses on staging-next
https://hydra.nixos.org/build/162001566
I suppose this might need to be included in https://github.com/NixOS/nixpkgs/issues/151469 now

**Pull request merged**
