### PR TITLE
dockutil 2.0.5 -> 3.0.2

### LINKED ISSUE #167449: dockutil 2.0.5 -> 3.0.2
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: dockutil

current version: 2.0.5
desired version: 3.0.2

###### Notify maintainers

maintainers: @tboerger 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by JayRovacsek**
###### Description of changes

Updates the package for dockutil from version 2.0.5 to 3.0.2, change-sets for this update are as described [here](https://github.com/kcrawford/dockutil/compare/2.0.5...3.0.2) notably including a rewrite by the author to a swift version in order to enable users of MacOS 12.3+ where python is no longer packaged by default.

This pull request should close https://github.com/NixOS/nixpkgs/issues/167449 :+1: 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tboerger — COMMENTED** [review]
Maybe you want to replace this with something like this? This structure have already been merged with tools like mysides and is also used within other darwin-specific packages:

```
{ lib, stdenv, fetchurl, libarchive, p7zip }:

stdenv.mkDerivation rec {
  pname = "dockutil";
  version = "3.0.2";

  src = fetchurl {
    url = "https://github.com/kcrawford/dockutil/releases/download/${version}/dockutil-${version}.pkg";
    sha256 = "sha256-F1E36nR+g+0iHWCxi3ErJW7TFTFTTN6E9nlIfTN2aP0=";
  };

  dontBuild = true;
  nativeBuildInputs = [ libarchive p7zip ];

  unpackPhase = ''
    7z x $src
    bsdtar -xf Payload~
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    install -Dm755 usr/local/bin/dockutil -t $out/bin
    runHook postInstall
  '';

  meta = with lib; {
    description = "Tool for managing dock items";
    homepage = "https://github.com/kcrawford/dockutil";
    license = licenses.asl20;
    maintainers = with maintainers; [ tboerger ];
    platforms = platforms.darwin;
  };
}
```

**Comment by JayRovacsek** [comment]
> Maybe you want to replace this with something like this? This structure have already been merged with tools like mysides and is also used within other darwin-specific packages:

Thanks a ton for the speedy feedback @tboerger! The recommended changes work grand, however (and maybe it's my lack of understanding on how the universal Mach-O binarties work (or maybe it's not related to this at all) if the resulting output exists in only `$out/bin` an exit code of 137 is given on execution, compared to `$out/usr/local/bin` and then symlinked to the `$out/bin` location where an exit code of 0 occurs.

I've dug into logs via the Console application and can't see any obvious tail to chase on the error plus redirecting stderr to   either a file or stdout gives no clues on why a 137 error code is given :disappointed: 

Keen to hear if you have a recommendation on how we could resolve this - I've otherwise applied all other recommended changes as per: https://github.com/NixOS/nixpkgs/pull/167488/commits/b0a396b9bf5166304e730d35540fe41b7b833951

**Comment by tboerger** [comment]
There is some wrong formatting/indentation, beside that this looks good to me.

**Comment by tboerger** [comment]
There is some wrong formatting/indentation, beside that this looks good to me.

**Comment by JayRovacsek** [comment]
> There is some wrong formatting/indentation, beside that this looks good to me.

Thanks @tboerger, I've applied a format utilising nixfmt; changes as per: https://github.com/NixOS/nixpkgs/pull/167488/commits/18c178e27cbf4575a1e58bd4c2172884efb34415 - this didn't make too much change so let me know if there's any specific format/lint issues you'd like addressed :+1:

**Review by tboerger — APPROVED** [review]

**Pull request merged**
