### PR TITLE
python: coverage: 4.5.4 -> 5.1

### PR DESCRIPTION
**Pull request by vojta001**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
since this change causes over 500 rebuilds, do you mind targeting the staging branch

```
git rebase --onto=origin/staging HEAD~1
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch

**Comment by vojta001** [comment]
Sorry, my fault. Rebased.

**Comment by vojta001** [comment]
Is there any way one can check the number of rebuilds in advance?

**Comment by jonringer** [comment]
You can do a `nixpkgs-review wip` (assuming your changes aren't committed yet), and it will say how many packages will be rebuilt

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.requests
@GrahamcOfBorg build python38Packages.requests

**Comment by jonringer** [comment]
looks like there's a major regression with cffi in staging right now

**Comment by FRidh** [comment]
This update should be fine by now. If it turns out it breaks (too many) Python packages, we revert in staging-next.

**Pull request merged**
