### PR TITLE
elpi: 1.2.0 -> 1.4.1

### PR DESCRIPTION
**Pull request by CohenCyril**
###### Motivation for this change
Upgrade elpi to latest version

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by CohenCyril** [comment]
@vbgl is it ok?

**Comment by vbgl** [comment]
Does it subsumes #63727?

**Comment by CohenCyril** [comment]
@vbgl It does since this is a derivation for release 1.4.1 from yesterday, but your derivation in #63727 was smaller (I did not try to filter out unused dependencies since 1.2.0)

**Comment by CohenCyril** [comment]
@vbgl now should be strictly one release bump from #63727

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.elpi

**Pull request merged**
