### PR TITLE
nixpkgs manual in CommonMark using sphinx+myst and jupyter-book

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

If we change to CommonMark, I prefer if we go for MyST, as that allows one to fall back to reStructuredText. MyST also comes with plenty of extensions, including internal references which I think are critical.

This PR uses `jupyter-book` which has quite a lot of dependencies. We could also fall back to just Sphinx + MyST, it does not matter much really I think. All in all it seems `jupyter-book` is a nicer ready solution.
https://jupyterbook.org

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

## TODO

- [ ] fix tests of new python packages
- [ ] sphinx setting: elevate warnings to errors (not yet done because pygments somehow doesn't recognize nix markup)
- [x] create a toc
- [x] refer to all existing md docs
- [x] convert remaining docs from docbook to md in a nix build
- [ ] include manual in `release*.nix`
- [x] include functions reference
- [x] send sphinx update through staging :( 
- [x] logo

For the time being we would have two builds, but with basically the same contents.

```
$ nix-build doc-md
```

### CODE REVIEW

**Comment by ryantm** [comment]
What is jupyter-book? Is it really close enough to CommonMark to be in the spirit of RFC 72?

**Comment by FRidh** [comment]
> https://myst-parser.readthedocs.io/en/latest/index.html

Yes, language wise it is just MyST which is a superset of CommonMark https://myst-parser.readthedocs.io/en/latest/index.html.

**Comment by ryantm** [comment]
I don't know much about the various options available, but I have a slight preference for matching whatever Nix is already doing if it is acceptable https://github.com/NixOS/nix/tree/master/doc/manual

**Comment by jonringer** [comment]
if you bump sphinx, I think this will have to go in staging

**Comment by FRidh** [comment]
As far as I can tell everything is now functioning.

We now need to test the impact of the Sphinx upgrade and then send that to staging. Other packages can also be merged after tests are ok.

**Comment by jtojnar** [comment]
One disadvantage of MyST is that the syntax is even more convoluted than XML – we would replace English-like tags for weird and unmemorable combinations of symbols. Using CommonMark with MDX has much more uniform syntax.

**Comment by FRidh** [comment]
> I don't know much about the various options available, but I have a preference for matching whatever Nix is already doing if it is acceptable https://github.com/NixOS/nix/tree/master/doc/manual

I don't see how `mdBook` will handle the large amount of nesting we have. The Nixpkgs manual is significantly bigger, and currently we have it already divided into parts, which both DocBook and `jupyter-book` support. Maybe `mdBook` does as well, I could only find `heading-split-level`.

The reason I went for Sphinx is how customizable it is and the already existing mature ecosystem it has. I also would like to have runnable code-cells like I have [here](https://github.com/FRidh/nix-tutorials) (currently broken).

> One disadvantage of MyST is that the syntax is even more convoluted than XML – we would replace English-like tags with weird and unmemorable combinations of symbols. Using CommonMark with MDX has much more uniform syntax.

I find MDX also appealing. Would you suggest any implementation? Not having looked much further, Gatsby seems to better support more nested contents like ours.

**Comment by FRidh** [comment]
Pandoc-style anchors are not supported, so you will `{#anchor}` appended to the heading . MyST has a different format, as well as the possibility to generate anchors.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
There are a lot of new lines missing to make git happy.

Please complete meta everywhere with maintainer and homepage.

All packages should have a pythonImportsCheck.

Please quote all homepage urls.

Can we fetch from GitHub to enable tests for some of the packages?

**Pull request closed without merging**
