### PR TITLE
osrm-backend: 4.9.1 -> 5.12

### PR DESCRIPTION
**Pull request by nico202**
###### Motivation for this change
Outdated version
@risicle can you check if everything's working? I need to setup mine. Also, can you add yourself as a meta.maintainers (if you are willed to maintain it? I had to search the history)?

Thanks, Nicolò

### CODE REVIEW

**Comment by risicle** [comment]
Excellent that someone's been paying some attention to this - afraid I've been awfully out of touch with osrm since I added this. I'd be willing to add myself as co-maintainer alongside you if you want.

I'll give it a spin - I always wanted to be able to enable the tests for this package, but that looks like a task for another day.

**Comment by nico202** [comment]
I'll set it up the following week, fixing it if needed. Since I never tried it, if it suits my needs it'd be OK for me to be co-maintainers

Nicolò

**Comment by risicle** [comment]
It does indeed seem to work for me in both MLH and CH modes. The only ergonomic nastiness now is due to the removal of the "default profile" patch, now the only quick way of running the `osrm-extract` is something like:

```
$ osrm-extract -p $(dirname $(which osrm-extract))/../share/osrm-backend/profiles/car.lua berlin-latest.osm.pbf
```

how do other packages which install auxiliary files that need to be referenced cope with this?

**Comment by Mic92** [comment]
@GrahamcOfBorg build osrm-backend

**Comment by joachifm** [comment]
Closing in deference to https://github.com/NixOS/nixpkgs/pull/32260

**Pull request closed without merging**
