### PR TITLE
jetbrains: update

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
I also manually updated the part of the MPS download url that is not changed automatically by the updater script.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eyJhb** [comment]
Remember to follow conventions, `jetbrains: 2020.1.3 -> 2020.1.4` both in the PR title and commit messages :)

**Comment by Ma27** [comment]
@eyJhb there are multiple packages with different version bumps. Since the updates are automatically generated, the commit-message is fine IMHO.

**Comment by eyJhb** [comment]
> @eyJhb there are multiple packages with different version bumps. Since the updates are automatically generated, the commit-message is fine IMHO.

My bad, there were a few that weren't the same. Sorry for the disturbance ;)

**Review by ktor — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
@petabyteboy thanks!

**Pull request merged**
