### PR TITLE
proxmox-backup-client: 2.2.1 -> 2.4.1; add man-pages and shell completions

### PR DESCRIPTION
**Pull request by christoph-heiss**
###### Description of changes

Changelog: https://git.proxmox.com/?p=proxmox-backup.git;a=blob;f=debian/changelog;h=89011d4c60cb13cab6d9fec9433a21b7cb6598c3;hb=3da94f2e7429ea1653ed5e61a0f83e67ff02b8be

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by cofob — APPROVED** [review]

**Comment by cofob** [comment]
@averyanalex review please.

**Comment by averyanalex** [comment]
> @averyanalex review please.

I'm sorry, I'm very busy right now, and most likely I'll have time in about a month

**Comment by christoph-heiss** [comment]
Updated the version in the pull request from 2.3.1 to 2.4.1, as that has been released in the meantime and this PR hasn't been reviewed yet.

**Review by cofob — APPROVED** [review]
Everything is fine, we can merge.

**Review by picnoir — APPROVED** [review]
Thanks a lot!

I couldn't find the first two patches origin for sure. Are they coming from Arch? Is this something part of the next release? I can't find them anywhere else.

It's usually preferable to either fetch them from their source, either point to their source in a comment.

That being said, let's not bikeshed this to death. The first one vendor some Rust dependencies, the second one disables some man pages build. It doesn't seem dodgy to me. LGTM.

Trusting @cofob's judgement for the rest. Merging.

-----------------
Result of `nixpkgs-review pr 215812` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>proxmox-backup-client</li>
  </ul>
</details>

**Comment by christoph-heiss** [comment]
> I couldn't find the first two patches origin for sure. Are they coming from Arch? Is this something part of the next release? I can't find them anywhere else.

Yeah, they are coming directly from the [Archlinux AUR package](https://aur.archlinux.org/packages/proxmox-backup-client). Should have specified that, sorry.

> It's usually preferable to either fetch them from their source, either point to their source in a comment.

Good to know, I'll make a new PR some time resolving that, or at the latest with the next version update.

> Merging.

Thanks!

**Comment by NinjaTrappeur** [comment]
> Good to know, I'll make a new PR some time resolving that, or at the latest with the next version update.

Don't sweat it, it's fine, it can wait the next version bump.

**Pull request merged**
