### PR TITLE
gimp: 2.10.12 → 2.10.14

### PR DESCRIPTION
**Pull request by jtojnar**
https://www.gimp.org/news/2019/10/31/gimp-2-10-14-released/

GEGL taken from https://github.com/NixOS/nixpkgs/pull/67576

- [x] Run on NixOS (sandbox)

### CODE REVIEW

**Comment by jtojnar** [comment]
I am seeing the following in the console.

```
Traceback (most recent call last):
  File "/nix/store/cb4y33mrqkmd8aca855kjyks9l9mbkkj-gimp-2.10.12/lib/gimp/2.0/plug-ins/spyro_plus/.spyro_plus.py-wrapped", line 23, in <module>
    import gimpui
  File "/nix/store/cb4y33mrqkmd8aca855kjyks9l9mbkkj-gimp-2.10.12/lib/gimp/2.0/python/gimpui.py", line 33, in <module>
    import gtk, gobject, gimp, gimpcolor
ImportError: No module named gtk
```

It is not a regression, we have it in GIMP 2.10.12 too.

Not sure why that is happening, GIMP itself is wrapped to have `pygtk` in `PYTHONPATH` and spyro does not overwrite the environment variable.

**Comment by jtojnar** [comment]
GEGL fails to build on Darwin:

```
FAILED: subprojects/poly2tri-c/libpoly2tri-c.a
rm -f subprojects/poly2tri-c/libpoly2tri-c.a && ar csr subprojects/poly2tri-c/libpoly2tri-c.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
ninja: build stopped: subcommand failed.
```

**Comment by jtojnar** [comment]
```
../gegl/opencl/cl_gl.h:37:10: fatal error: 'OpenGL/CGLDevice.h' file not found
#include <OpenGL/CGLDevice.h>
         ^~~~~~~~~~~~~~~~~~~~
```

```
jtojnar ,locate CGLDevice.h
{^_^} Couldn't find in any packages
```

:woman_shrugging: @NixOS/darwin-maintainers

**Comment by LnL7** [comment]
nix-index generates it's database based on the derivations for your system, ie. darwin only packages won't be indexed on linux (by default?).
As a general rule of thumb, if you see camel case in headers it's probably a framework.

**Comment by jtojnar** [comment]
@GrahamcOfBorg build gimp

**Comment by jtojnar** [comment]
Thanks.
`gegl` should be `gegl_0_4` and I wonder about all the we libm failures.

**Pull request merged**
