### PR TITLE
pnpm_9: 9.7.0 -> 9.9.0

### PR DESCRIPTION
**Pull request by gepbird**
## Description of changes

Releases:
- https://github.com/pnpm/pnpm/releases/tag/v9.7.1
- https://github.com/pnpm/pnpm/releases/tag/v9.8.0
- https://github.com/pnpm/pnpm/releases/tag/v9.9.0
  - Minor breaking change. This change might result in resolving your peer dependencies slightly differently but we don't expect it to introduce issues.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 334716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>gitbutler</li>
    <li>pot</li>
    <li>surrealist</li>
    <li>vikunja</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>armcord</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>goofcord</li>
    <li>lemmy-ui</li>
    <li>misskey</li>
    <li>n8n</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>postcss-cli</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>syncyomi</li>
    <li>vesktop</li>
    <li>wrangler</li>
    <li>youtube-music</li>
  </ul>
</details>

**Comment by gepbird** [comment]
`gitbutler`, `pot` and `surrealist` fail on master too.

However `vikunja` builds on master but runs out of memory on this PR:
```
vikunja-frontend> <--- Last few GCs --->
vikunja-frontend> 
vikunja-frontend> [1695:0x3079980]   238846 ms: Mark-Compact (reduce) 1810.0 (1850.4) -> 1809.6 (1850.9) MB, 1496.75 / 0.00 ms  (average mu = 0.157, current mu = 0.006) allocation failure; scavenge might not succeed
vikunja-frontend> [1695:0x3079980]   240443 ms: Mark-Compact (reduce) 1810.6 (1850.9) -> 1810.3 (1851.6) MB, 1589.82 / 0.00 ms  (average mu = 0.083, current mu = 0.004) allocation failure; scavenge might not succeed
vikunja-frontend> 
vikunja-frontend> 
vikunja-frontend> <--- JS stacktrace --->
vikunja-frontend> 
vikunja-frontend> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
vikunja-frontend> ----- Native stack trace -----
vikunja-frontend> 
vikunja-frontend>  1: 0xaaae51 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
vikunja-frontend>  2: 0xe30f50 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
vikunja-frontend>  3: 0xe31334 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
vikunja-frontend>  4: 0x1060b57  [node]
vikunja-frontend>  5: 0x10796c9 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
vikunja-frontend>  6: 0x1052337 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
vikunja-frontend>  7: 0x1052f74 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
vikunja-frontend>  8: 0x103229e v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
vikunja-frontend>  9: 0x149bfc0 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
vikunja-frontend> 10: 0x18ddef6  [node]
vikunja-frontend>  ELIFECYCLE  Command failed with exit code 134.
```

@ofborg build vikunja

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 334716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>surrealist</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>armcord</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>gitbutler</li>
    <li>goofcord</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>n8n</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm (pnpm_9)</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>syncyomi</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wrangler</li>
    <li>youtube-music</li>
  </ul>
</details>

`surrealist` fails on master too.

**Comment by MisileLab** [comment]
@gepbird can you edit title's version to pnpm_9: 9.7.0 -> 9.8.0

**Comment by gepbird** [comment]
Updating to 9.9 which might cause breakages: https://github.com/pnpm/pnpm/releases/tag/v9.9.0

**Comment by gepbird** [comment]
No new failures

Result of `nixpkgs-review pr 334716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>surrealist</li>
  </ul>
</details>
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>armcord</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>gitbutler</li>
    <li>goofcord</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>n8n</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>pnpm</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>syncyomi</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wrangler</li>
    <li>youtube-music</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
I didn't realize this PR was open before I opened mine at #339518. Mine got merged faster, sorry :(

**Comment by gepbird** [comment]
No worries, thanks for letting me know.

**Pull request closed without merging**
