### PR TITLE
linux_{4_14,4_19,5_4,5_10,5_13}_hardened: update patches

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
I think we normally split this into one commit per kernel version.

**Comment by lovesegfault** [comment]
@ajs124 split them up

**Comment by lovesegfault** [comment]
@GrahamcOfBorg eval

**Comment by TredwellGit** [comment]
Consider using [update.sh](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/update.sh) next time.

**Comment by lovesegfault** [comment]
> Consider using [update.sh](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/update.sh) next time.

Will do!

**Pull request merged**
