### PR TITLE
bazel: 0.28.1 -> 0.29.0

### PR DESCRIPTION
**Pull request by guibou**
Note: ~~This is a work in progress. It seems to work, but I cannot build `rules_haskell` for now using this, so I'm not sure.~~ See latest comment, this commit is not responsible for rules_haskell breakage.

- Upgraded dependencies
  - dependencies script upgraded to take into account new WORKSPACE
    rules
- Tests now depends on the `distdir`

Runtime bazel now also depends on the `distdir` setting which appears
in the global configuration file. This increases the bazel closure
size by 85 MO for stuffs which can normally be downloaded at runtime
by bazel. However, any invocation of `buildBazelPackage` (such as in
`bazel-watcher`) may fail in nix sandbox if theses files are not
available at runtime.

If this overhead is too important, we may later evolve to a finer
grained solution, where buildBazelPackage declares the list of
necessary dependencies.

###### Motivation for this change

Upstream update.

###### Things done

As said in the commit message, this PR largly increases the size of the bazel closure because now bazel depends on all the `srcDeps` which is, at that time, 85 Mo.

That's a bunch of files that bazel may use at runtime in `buildBazelPackage`.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by guibou** [comment]
The breakage in rules_haskell is due to c4813515ca34e7f2aef73280646c94c4c1b0eb86 which is already in nixpkgs master. So I now consider that my current PR (update to 0.29.0) is not worse than the current status of bazel in nixpkgs.

I'll try to fix rules_haskell later and see if the fix leads to a change in nixpkgs.

@Profpatsch @kalbasit review please.

**Comment by kalbasit** [comment]
@GrahamcOfBorg build bazel bazel.tests

**Comment by mboes** [comment]
I would like to see a review from @aherrmann. He fixed a Python issue recently (see #66718), which seems to have resurfaced. Also see #66723, which should avoid the problem from coming back, but has yet to be merged.

cc @flokli @Profpatsch

**Review by kalbasit — APPROVED** [review]

**Comment by guibou** [comment]
@mboes I don't see the relation between your comment and my PR (and the python issue detailled inside).

I bisected the regression to this commit c481351 which replaced an hardcoded python path (used to launch python executable in `py_binary`) by the original `SearchPath` function from bazel, which is supposed to look for `python` in the `PATH`.

My understanding is that bazel in nixpkgs is not correctly passing the `PATH` environment variable to the python script runner. For now I'm fixing it by manually injecting `PATH`: https://github.com/tweag/rules_haskell/pull/1065/commits/0882c7c36c6977448914e661cd1b2d5c86e90450

My point of view is that I don't think the current PR have anything to do with the error I'm describing (considering that I can observe the same issue with bazel 0.28.1 from nixpkgs master) and that we can merge this PR independently of #66718 and #66723 and any future work done to work on the python path issue.

**Comment by Profpatsch** [comment]
> Runtime bazel now also depends on the distdir setting which appears
> in the global configuration file. This increases the bazel closure
> size by 85 MO for stuffs which can normally be downloaded at runtime
> by bazel. However, any invocation of buildBazelPackage (such as in
> bazel-watcher) may fail in nix sandbox if theses files are not
> available at runtime.

Are you sure this isn’t an upstream regression? It looks highly dubious to me.

**Comment by guibou** [comment]
> > Runtime bazel now also depends on the distdir setting which appears
> > in the global configuration file. This increases the bazel closure
> > size by 85 MO for stuffs which can normally be downloaded at runtime
> > by bazel. However, any invocation of buildBazelPackage (such as in
> > bazel-watcher) may fail in nix sandbox if theses files are not
> > available at runtime.
> 
> Are you sure this isn’t an upstream regression? It looks highly dubious to me.


> > Runtime bazel now also depends on the distdir setting which appears
> > in the global configuration file. This increases the bazel closure
> > size by 85 MO for stuffs which can normally be downloaded at runtime
> > by bazel. However, any invocation of buildBazelPackage (such as in
> > bazel-watcher) may fail in nix sandbox if theses files are not
> > available at runtime.
> 
> Are you sure this isn’t an upstream regression? It looks highly dubious to me.

Apparently bazel is trying to externalize all the rules. You can see here the reference for, amongst others, `rules_cc`: https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L456

Here you can see the discussion for `rules_python`: https://github.com/bazelbuild/bazel/issues/9006 which will be soon used by default, according to the release note: https://blog.bazel.build/2019/08/27/bazel-0.29.0.html

> Added --incompatible_load_python_rules_from_bzl, which will be flipped in a future Bazel version. To migrate, load Python rules from @rules_python. See #9006.

**Comment by aherrmann** [comment]
This seems to be orthogonal to https://github.com/NixOS/nixpkgs/pull/66723, indeed. I've run the shebang tests from that branch on this PR and they passed, so there are no new unpatched shebangs.

> considering that I can observe the same issue with bazel 0.28.1 from nixpkgs master

That's odd, https://github.com/NixOS/nixpkgs/pull/66718 solved the similar issue for me with bazel 0.28.1. I see how https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86 is related. But, it seems that another change in Bazel 0.29 triggers this issue in combination with https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86.

> My understanding is that bazel in nixpkgs is not correctly passing the PATH environment variable to the python script runner. For now I'm fixing it by manually injecting PATH: tweag/rules_haskell@0882c7c

Looking at the `//tests/version-macros` failure, the Python stub template is instantiated with `%python_binary% = "python"`. Bazel has [some logic](https://github.com/bazelbuild/bazel/blob/bb26694806c9a9c2b3f39100ddd4b00e0d8285cd/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L403-L425) to calculate that value based on the Bazel configuration. Maybe nixpkgs should adjust the default config to produce a more sensible value for `%python_binary%` in the context of nixpkgs. If it was an absolute path, then Bazel [wouldn't consult `PATH`](https://github.com/bazelbuild/bazel/blob/bb26694806c9a9c2b3f39100ddd4b00e0d8285cd/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L63-L65).

Alternatively, did you try extending the `defaultShellPath` in `bazel/default.nix` to include the Python interpreter? Bazel seems to assume that `python` is in `PATH`. So, maybe that's another solution to the problem. However, I'm not sure how that plays with Python 2 vs. 3.

Working around the issue downstream in rules sets by extending `PATH` does not seem like a good solution. Most rules sets are not written with nixpkgs in mind.

**Comment by guibou** [comment]
> That's odd, #66718 solved the similar issue for me with bazel 0.28.1. I see how c481351 is related. But, it seems that another change in Bazel 0.29 triggers this issue in combination with c481351.

With bazel 0.28.1 from nixpkgs before or after c481351? I initially thought that the issue was in bazel 0.29, but when I updated rules_haskell to use latest nixpkgs (including bazel 0.28.1 and c481351), I had the same issue.

> Alternatively, did you try extending the defaultShellPath in bazel/default.nix to include the Python interpreter? Bazel seems to assume that python is in PATH. So, maybe that's another solution to the problem. However, I'm not sure how that plays with Python 2 vs. 3.

Not yet, that's indeed a good idea. However I'm afraid of the semantic. The point of c481351 was exactly to avoid an hardcoded python interpreter and instead rely on `PATH` detection, which seems to be the bazel semantic.

I'll try to create a simple reproduction code (i.e.: simpler than rules_haskell) and I'll open a nixpkgs issue. In the meantime I've opened https://github.com/tweag/rules_haskell/issues/1067 which tracks this as a rules_haskell issue and get the same details / conclusion as you did right now. I apologize for duplicate work, I should have put a notification here. I however do agree now that the issue is in nixpkgs and not in rules_haskell.

**Comment by Profpatsch** [comment]
> Here you can see the discussion for `rules_python`: [bazelbuild/bazel#9006](https://github.com/bazelbuild/bazel/issues/9006) which will be soon used by default,

Luckily, it won’t happen for 1.0 yet: https://github.com/bazelbuild/bazel/issues/9006#issuecomment-523195423


> I however do agree now that the issue is in nixpkgs and not in rules_haskell.

Do we merge this PR then, nonetheless?

**Comment by guibou** [comment]
> Do we merge this PR then, nonetheless?

I don't see any reason not to merge it.

**Comment by aherrmann** [comment]
> > That's odd, #66718 solved the similar issue for me with bazel 0.28.1. I see how [c481351](https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86) is related. But, it seems that another change in Bazel 0.29 triggers this issue in combination with [c481351](https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86).
> 
> With bazel 0.28.1 from nixpkgs before or after [c481351](https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86)? I initially thought that the issue was in bazel 0.29, but when I updated rules_haskell to use latest nixpkgs (including bazel 0.28.1 and [c481351](https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86)), I had the same issue.

After https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86, #66718 directly addresses a change from that commit. 

> Not yet, that's indeed a good idea. However I'm afraid of the semantic. The point of [c481351](https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86) was exactly to avoid an hardcoded python interpreter and instead rely on `PATH` detection, which seems to be the bazel semantic.

Yes, that's what I meant by
> However, I'm not sure how that plays with Python 2 vs. 3.

Modifying the Bazel default config to provide a better substitution for `%python_binary%` might be more in line with that.

**Pull request merged**
