### PR TITLE
qgis-ltr: disable PDAL support

### LINKED ISSUE #281266: Build failure: qgis-ltr build is failing after libxml2 upgrade
### Steps To Reproduce

1. build `qgis-ltr` with latest master branch
```
nix-build -A qgis-ltr
```

### Build log

```
/build/source/pdal/XMLSchema.cpp: In member function 'bool pdal::XMLSchema::validate(xmlDocPtr, const std::string&)':
/build/source/pdal/XMLSchema.cpp:257:9: error: invalid conversion from 'void (*)(void*, xmlErrorPtr)' {aka 'void (*)(void*, _xmlError*)'} to 'xmlStructuredErrorFunc' {aka 'void (*)(void*, const _xmlError*)'} [-fpermissive]
  257 |         &SchemaParserStructuredErrorHandler, m_global_context);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         void (*)(void*, xmlErrorPtr) {aka void (*)(void*, _xmlError*)}
In file included from /build/source/pdal/XMLSchema.hpp:50,
                 from /build/source/pdal/XMLSchema.cpp:34:
/nix/store/iqjsxkcdnvvz1bfpq960ygicc5clz9hv-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2/libxml/xmlschemas.h:156:65: note:   initializing argument 2 of 'void xmlSchemaSetParserStructuredErrors(xmlSchemaParserCtxtPtr, xmlStructuredErrorFunc, void*)'
  156 |                                          xmlStructuredErrorFunc serror,
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
[ 39%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/csf/Constraint.cpp.o
[ 39%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/csf/Particle.cpp.o
[ 39%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/csf/Rasterization.cpp.o
[ 39%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/csf/XYZReader.cpp.o
[ 39%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/csf/c2cdist.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/csf/point_cloud.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/delaunator.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/expr/AssignParser.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/expr/AssignStatement.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/expr/BaseParser.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/filters/private/expr/ConditionalExpression.cpp.o
make[2]: *** [CMakeFiles/pdal_base.dir/build.make:2386: CMakeFiles/pdal_base.dir/pdal/XMLSchema.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:739: CMakeFiles/pdal_base.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

### Additional context

`qgis-ltr` is building with the older version of `pdal` (2.5), because it can't build with the latest version (see: https://github.com/qgis/QGIS/pull/54940). Build of `pdal 2.5` started to fail after recent `libxml2` update to version `2.12`.

### Notify maintainers

Notify @NixOS/geospatial 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by imincik**
QGIS-LTR is failing to build with PDAL 2.6.

Currenly used older version of PDAL 2.5 is failing to build with current version
of `libxml2`.

PDAL support can be re-enabled once
https://github.com/qgis/QGIS/pull/54940
is backported.

Closes https://github.com/NixOS/nixpkgs/issues/281266

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by imincik** [comment]
@sikmir , are you OK with this PR to unbreak QGIS-LTR ?

**Review by sikmir — APPROVED** [review]

**Comment by imincik** [comment]
@ofborg build qgis-ltr

**Comment by imincik** [comment]
@ofborg build qgis-ltr

**Comment by imincik** [comment]
@ofborg build qgis-ltr.tests

**Comment by imincik** [comment]
@ofborg test qgis-ltr

**Pull request merged**
