### PR TITLE
linuxPackages.nvidia_x11: 545.29.02 -> 545.29.06

### PR DESCRIPTION
**Pull request by Kiskae**
## Description of changes

- Fixed a regression that prevented setting backlight brightness levels.
- Fixed a bug that could lead to UI corruption in nvidia-installer on systems with more than one initramfs file per kernel.
- Fixed a bug that caused games built on the Source 2 engine to hang when running under Xwayland.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
And the patch can be dropped?

**Comment by Kiskae** [comment]
Result of `nixpkgs-review pr 269262` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>gl-gsync-demo</li>
    <li>gwe</li>
    <li>heroic</li>
    <li>mangohud</li>
    <li>mangohud.doc</li>
    <li>mangohud.man</li>
    <li>monitor</li>
    <li>nvfancontrol</li>
    <li>psensor</li>
  </ul>
</details>
<details>
  <summary>102 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.bin (linuxKernel.packages.linux_6_1_hardened.nvidia_x11.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.firmware (linuxKernel.packages.linux_6_1_hardened.nvidia_x11.firmware)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.lib32 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11.lib32)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta_open)</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.firmware (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.firmware)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.lib32)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta_open)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta_open</li>
    <li>xpraWithNvenc</li>
    <li>xpraWithNvenc.dist</li>
  </ul>
</details>

**Comment by Kiskae** [comment]
@NickCao Yeah, was just waiting for the review to finish before adding that change.

Now we just need to wait for the settings/persistenced sources to be pushed to github.

**Comment by Kiskae** [comment]
Still waiting for official github releases, but I decided to see if I could convince the fetcher to fall back to nvidia's CDN.

The following code works, but depends on the implementation of `fetchFromGithub` using `fetchzip` internally which is kind of cursed:

```nix
  src = let 
    cdn = fetchFromGitHub {
      owner = "NVIDIA";
      repo = "nvidia-settings";
      rev = nvidia_x11.settingsVersion;
      inherit sha256;
    };
  in 
  cdn.override {
    urls = cdn.urls ++ [
      "https://download.nvidia.com/XFree86/nvidia-settings/nvidia-settings-${nvidia_x11.settingsVersion}.tar.bz2"
    ];
    url = "";
    # distributions use different compression, force unpack to guess
    extension = "tar.??";
  };
```

**Comment by NickCao** [comment]
The hack feels really uncomfortable to me, may we just replace `fetchFromGitHub` with `fetchurl`? `fetchFromGithub` is doing url concatenation under the hood anyway.

**Comment by Kiskae** [comment]
That'd be something like:
```nix
fetchFromGithubOrNvidia = { owner, repo, rev, ... }@args:
  let
    args' = builtins.removeAttrs args [ "owner" "repo" "rev" ];
    baseUrl = "https://github.com/${owner}/${repo}";
  in
  fetchzip (args' // {
    urls = [
      "${baseUrl}/archive/${rev}.tar.gz"
      "https://download.nvidia.com/XFree86/${repo}/${repo}-${rev}.tar.bz2"
    ];
    # github and nvidia use different compression algorithms,
    #  use an invalid file extension to force detection.
    extension = "tar.??";
  });
```

**Comment by NickCao** [comment]
And another concern is if their contents do match, which should be the case, but better be safe than sorry.

**Comment by Kiskae** [comment]
> And another concern is if their contents do match, which should be the case, but better be safe than sorry.

As far as I can tell that is the case for these sources, the open-gpu-kernel-modules don't match because the github mirror contains extra `.github` files.

If https://github.com/aaronp24/nvidia-versions is still true, those repositories are literally emptied and overwritten with the tarballs from the cdn for each release.

**Comment by Kiskae** [comment]
Result of `nixpkgs-review pr 269262` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>113 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>gl-gsync-demo</li>
    <li>gwe</li>
    <li>heroic</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.bin (linuxKernel.packages.linux_6_1_hardened.nvidia_x11.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.firmware (linuxKernel.packages.linux_6_1_hardened.nvidia_x11.firmware)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.lib32 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11.lib32)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta_open)</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_5.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_5_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.firmware (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.firmware)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.lib32)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta_open)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta_open</li>
    <li>mangohud</li>
    <li>mangohud.doc</li>
    <li>mangohud.man</li>
    <li>monitor</li>
    <li>nvfancontrol</li>
    <li>psensor</li>
    <li>xpraWithNvenc</li>
    <li>xpraWithNvenc.dist</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]

**Pull request merged**
