### PR TITLE
python310Packages.cattrs: 22.2.0 -> 23.1.2

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Diff: https://github.com/python-attrs/cattrs/compare/v22.2.0...v23.1.2

Changelog: https://github.com/python-attrs/cattrs/blob/v23.1.2/HISTORY.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 246592` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python310Packages.bentoml</li>
    <li>python310Packages.bentoml.dist</li>
    <li>python310Packages.coffea</li>
    <li>python310Packages.coffea.dist</li>
    <li>python311Packages.bentoml</li>
    <li>python311Packages.bentoml.dist</li>
  </ul>
</details>
<details>
  <summary>102 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>anime-downloader</li>
    <li>anime-downloader.dist</li>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>cmake-language-server</li>
    <li>cmake-language-server.dist</li>
    <li>cryptop</li>
    <li>cryptop.dist</li>
    <li>mnamer</li>
    <li>mnamer.dist</li>
    <li>nanoemoji</li>
    <li>nanoemoji.dist</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward-cpp</li>
    <li>python310Packages.awkward-cpp.dist</li>
    <li>python310Packages.awkward.dist</li>
    <li>python310Packages.cattrs</li>
    <li>python310Packages.cattrs.dist</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.dask-awkward.dist</li>
    <li>python310Packages.fontmake</li>
    <li>python310Packages.fontmake.dist</li>
    <li>python310Packages.glyphslib</li>
    <li>python310Packages.glyphslib.dist</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.jedi-language-server.dist</li>
    <li>python310Packages.laspy</li>
    <li>python310Packages.laspy.dist</li>
    <li>python310Packages.laszip</li>
    <li>python310Packages.laszip.dist</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.lsprotocol.dist</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.mplhep.dist</li>
    <li>python310Packages.pygls</li>
    <li>python310Packages.pygls.dist</li>
    <li>python310Packages.pysychonaut</li>
    <li>python310Packages.pysychonaut.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python310Packages.requests-cache</li>
    <li>python310Packages.requests-cache.dist</li>
    <li>python310Packages.scikit-build-core</li>
    <li>python310Packages.scikit-build-core.dist</li>
    <li>python310Packages.statmake</li>
    <li>python310Packages.statmake.dist</li>
    <li>python310Packages.tvdb_api</li>
    <li>python310Packages.tvdb_api.dist</li>
    <li>python310Packages.typed-settings</li>
    <li>python310Packages.typed-settings.dist</li>
    <li>python310Packages.ufo2ft</li>
    <li>python310Packages.ufo2ft.dist</li>
    <li>python310Packages.ufoLib2</li>
    <li>python310Packages.ufoLib2.dist</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.uproot.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python311Packages.awkward-cpp</li>
    <li>python311Packages.awkward-cpp.dist</li>
    <li>python311Packages.cattrs</li>
    <li>python311Packages.cattrs.dist</li>
    <li>python311Packages.fontmake</li>
    <li>python311Packages.fontmake.dist</li>
    <li>python311Packages.glyphslib</li>
    <li>python311Packages.glyphslib.dist</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.jedi-language-server.dist</li>
    <li>python311Packages.laspy</li>
    <li>python311Packages.laspy.dist</li>
    <li>python311Packages.laszip</li>
    <li>python311Packages.laszip.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.pysychonaut</li>
    <li>python311Packages.pysychonaut.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.requests-cache</li>
    <li>python311Packages.requests-cache.dist</li>
    <li>python311Packages.scikit-build-core</li>
    <li>python311Packages.scikit-build-core.dist</li>
    <li>python311Packages.statmake</li>
    <li>python311Packages.statmake.dist</li>
    <li>python311Packages.tvdb_api</li>
    <li>python311Packages.tvdb_api.dist</li>
    <li>python311Packages.typed-settings</li>
    <li>python311Packages.typed-settings.dist</li>
    <li>python311Packages.ufo2ft</li>
    <li>python311Packages.ufo2ft.dist</li>
    <li>python311Packages.ufoLib2</li>
    <li>python311Packages.ufoLib2.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>tvnamer</li>
    <li>tvnamer.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 246592` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.coffea</li>
    <li>python310Packages.coffea.dist</li>
  </ul>
</details>
<details>
  <summary>106 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>anime-downloader</li>
    <li>anime-downloader.dist</li>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>cmake-language-server</li>
    <li>cmake-language-server.dist</li>
    <li>cryptop</li>
    <li>cryptop.dist</li>
    <li>mnamer</li>
    <li>mnamer.dist</li>
    <li>nanoemoji</li>
    <li>nanoemoji.dist</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward-cpp</li>
    <li>python310Packages.awkward-cpp.dist</li>
    <li>python310Packages.awkward.dist</li>
    <li>python310Packages.bentoml</li>
    <li>python310Packages.bentoml.dist</li>
    <li>python310Packages.cattrs</li>
    <li>python310Packages.cattrs.dist</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.dask-awkward.dist</li>
    <li>python310Packages.fontmake</li>
    <li>python310Packages.fontmake.dist</li>
    <li>python310Packages.glyphslib</li>
    <li>python310Packages.glyphslib.dist</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.jedi-language-server.dist</li>
    <li>python310Packages.laspy</li>
    <li>python310Packages.laspy.dist</li>
    <li>python310Packages.laszip</li>
    <li>python310Packages.laszip.dist</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.lsprotocol.dist</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.mplhep.dist</li>
    <li>python310Packages.pygls</li>
    <li>python310Packages.pygls.dist</li>
    <li>python310Packages.pysychonaut</li>
    <li>python310Packages.pysychonaut.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>python310Packages.requests-cache</li>
    <li>python310Packages.requests-cache.dist</li>
    <li>python310Packages.scikit-build-core</li>
    <li>python310Packages.scikit-build-core.dist</li>
    <li>python310Packages.statmake</li>
    <li>python310Packages.statmake.dist</li>
    <li>python310Packages.tvdb_api</li>
    <li>python310Packages.tvdb_api.dist</li>
    <li>python310Packages.typed-settings</li>
    <li>python310Packages.typed-settings.dist</li>
    <li>python310Packages.ufo2ft</li>
    <li>python310Packages.ufo2ft.dist</li>
    <li>python310Packages.ufoLib2</li>
    <li>python310Packages.ufoLib2.dist</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.uproot.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python311Packages.awkward-cpp</li>
    <li>python311Packages.awkward-cpp.dist</li>
    <li>python311Packages.bentoml</li>
    <li>python311Packages.bentoml.dist</li>
    <li>python311Packages.cattrs</li>
    <li>python311Packages.cattrs.dist</li>
    <li>python311Packages.fontmake</li>
    <li>python311Packages.fontmake.dist</li>
    <li>python311Packages.glyphslib</li>
    <li>python311Packages.glyphslib.dist</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.jedi-language-server.dist</li>
    <li>python311Packages.laspy</li>
    <li>python311Packages.laspy.dist</li>
    <li>python311Packages.laszip</li>
    <li>python311Packages.laszip.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.pysychonaut</li>
    <li>python311Packages.pysychonaut.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.requests-cache</li>
    <li>python311Packages.requests-cache.dist</li>
    <li>python311Packages.scikit-build-core</li>
    <li>python311Packages.scikit-build-core.dist</li>
    <li>python311Packages.statmake</li>
    <li>python311Packages.statmake.dist</li>
    <li>python311Packages.tvdb_api</li>
    <li>python311Packages.tvdb_api.dist</li>
    <li>python311Packages.typed-settings</li>
    <li>python311Packages.typed-settings.dist</li>
    <li>python311Packages.ufo2ft</li>
    <li>python311Packages.ufo2ft.dist</li>
    <li>python311Packages.ufoLib2</li>
    <li>python311Packages.ufoLib2.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>tvnamer</li>
    <li>tvnamer.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by happysalada** [comment]
@veprbl it seems that coffea is failing to build. Coul you take a look when you have a moment ?

**Comment by natsukium** [comment]
Sorry, I've fixed coffea in #246949.

**Pull request merged**
