### PR TITLE
cope: remove

### PR DESCRIPTION
**Pull request by NobbZ**
## Description of changes

`cope` upstream is a bunch of wrapper script, which require the same named binary to exist somewhere else in `PATH`.

This design barely works with nixpkgs, and fixing this would probably require a good amount of patching. It is also unclear if the nearly 10 year old wrappers still work for the modern variants of the wrapped tools.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by msanft — APPROVED** [review]
Juding from how the upstream looks like, and a [best-effort search](https://github.com/search?q=lang%3Anix+pkgs.cope+&type=code) on how many dependants this package has, removing it from nixpkgs makes a lot of sense to me.

**Review by pSub — APPROVED** [review]
+1 on the approval of @msanft

**Review by eclairevoyant — APPROVED** [review]
Even [expanding the search](https://github.com/search?q=lang%3Anix+%22+cope%22&type=code), seems most of the usages of "cope" are in comments. Some of them are even commenting out `cope` from their package lists.

And maintaining patches for a 10+ year old codebase is nontrivial.

**Comment by NobbZ** [comment]
`nixpkgs-review` does cause astonishing 0 rebuilds, so I doubt there are any dependees.

**Review by leona-ya — APPROVED** [review]

**Comment by deftdawg** [comment]
Cope actually still works pretty well if it's patched for the warnings, I was running the warnings patch plus my own to make it use nixos's command-not-found.

Applied this overlay for my version @ https://github.com/deftdawg/cope
```
nixpkgs.overlays = [
    # Fix Cope using DeftDawg Version
		(final: prev: {
			cope = prev.cope.overrideAttrs (oldAttrs: {
				version = "unstable-2024-03-27";
        src = pkgs.fetchFromGitHub {
          owner = "deftdawg";
          repo = "cope";
          rev = "ad0c1ebec5684f5ec3e8becf348414292c489175";
          sha256 = "sha256-LMAir7tUkjHtKz+KME/Raa9QHGN1g0bzr56fNxfURQY=";
        };
	});
    })
 ];
```

Bummer to see it go from the official repo, I guess I'll have to roll it into a flake.

**Comment by deftdawg** [comment]
Closing #274361 which was to fix those warnings (opened in Dec'23) and opening #304918 to restore cope.

**Pull request merged**
