### PR TITLE
dart: 2.19.6 -> 3.0.0

### PR DESCRIPTION
**Pull request by hacker1024**
###### Description of changes

This upgrades Dart from 2.19.6 to 3.0.0.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hacker1024** [comment]
For some reason, this seems to break `dart-sass-embedded`. @kira-bruneau?

```
error: builder for '/nix/store/naphmf1vki47v42cbivmmj7lk9rh4lj4-dart-sass-embedded-1.62.1.drv' failed with exit code 69;
       last 7 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/1q84s8r7a16mw1l1gwimqb6vrlzicq8p-source
       > source root is source
       > patching sources
       > configuring
       > Resolving dependencies...
       > Package not available (Could not find git ref '8dddcb7b7db13984fea69fa85438acf30b56b4bb' (fatal: bad object 8dddcb7b7db13984fea69fa85438acf30b56b4bb)).
       For full logs, run 'nix log /nix/store/naphmf1vki47v42cbivmmj7lk9rh4lj4-dart-sass-embedded-1.62.1.drv'.
error: 1 dependencies of derivation '/nix/store/fakjjf4ld7mm3sk89i558w35x1j4fmpx-ruby3.2.2-sass-embedded-1.62.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v9iiqmqyw6zqmwx43hicny7mn7n5ywpp-ruby3.2.2-dartsass-ruby-3.0.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l63ik4agp3mvads40a3fm9x34h8nra9b-ruby3.2.2-dartsass-sprockets-3.0.0.drv' failed to build
error: 3 dependencies of derivation '/nix/store/n0lmg5hyy41ipbkp9rajrqd5i475x9xx-discourse-ruby-env-3.1.0.beta4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jj30k47l41vw5lr8aiknvn1kyf7km35w-wrapped-ruby-discourse-ruby-env-3.1.0.beta4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3ywkdq506lam0vcp9hrj3l46n7m8zkms-discourse-assets-3.1.0.beta4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mgx6brp614kpk71ihjv07df8lgxzbsww-discourse-assets-3.1.0.beta4.drv' failed to build
error: 3 dependencies of derivation '/nix/store/hk6nfsnqdfazq36fp3nvxa30nv9w0qgd-discourse-3.1.0.beta4.drv' failed to build
error: 3 dependencies of derivation '/nix/store/lxdpb32wfn6r41r3ic2rary0m4qwm76s-discourse-3.1.0.beta4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m8d3k2a32rwb91azlib1583y4856pl76-shopware-cli-0.1.62.drv' failed to build
error: 4 dependencies of derivation '/nix/store/abhqdp78dgspjafjvzs9zwiccbsaalhr-review-shell.drv' failed to build
4 packages failed to build:
dart-sass-embedded discourse discourseAllPlugins shopware-cli
```

**Comment by hacker1024** [comment]
Ahh. Looks like `fetch-dart-deps` is going to need some changes.

https://github.com/dart-lang/pub/pull/3791/files#diff-1639c4669c428c26e68cfebd5039a33f87ba568795f2c058c303ca8528f62b77

**Comment by hacker1024** [comment]
@NixOS/flutter

I have added a wrapper script around `Git` that is used when calling `pub get` to spoof revision results.

This solution, however, has the following drawbacks:

- Users must remember to use the `doPubGet` function to make `pub get` calls (though this will be done for them when using provided builders like `buildFlutterApplication`)
- The wrapper logic is coupled tightly with Pub's internal revision checking method. If the command Pub runs changes even slightly, this could break.

Does anyone have any ideas for other ways to fix this issue? If not, this may be the best workaround. I don't think it's possible to modify the files in .git to fake a commit hash.

**Comment by hacker1024** [comment]
Note: All rebuilds now succeed other than `yubioath-flutter`, which has been broken since https://github.com/NixOS/nixpkgs/commit/293ca686108c85dc0b2e78f661e32593db595088.

**Review by shyim — APPROVED** [review]
Thanks! 👍

**Comment by lelgenio** [comment]
How does this fit with https://github.com/NixOS/nixpkgs/pull/229770? If this was merged later, you could just update buildDartApplication.

**Comment by hacker1024** [comment]
> How does this fit with #229770? If this was merged later, you could just update buildDartApplication.

`buildDartApplication` will need to be updated to use the `doPubGet` function.

**Review by kira-bruneau — APPROVED** [review]

**Review by lelgenio — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Pull request merged**
