### PR TITLE
terraform-providers.minio: init at 1.2.0

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
The darwin failure isn't fixable without patching but that isn't easy with generic terraform derivation, simpler to move it out of the json. We can't mark it as broken either unless we add `meta.broken` as a field to the generic one.

@zimbatm Thoughts?

**Comment by zimbatm** [comment]
Do you have more details on the Darwin failure @zowoq?

For now, we assume that all providers support all platforms. In order to add that distinction one would need to : 
* Add an optional `platforms` attribute to the providers.json
* Reflect that onto the provider `meta.platforms` or default to all platforms.
* Change the `terraform.full` to filter out all the providers that don't match the current platform.

**Comment by zowoq** [comment]
> Do you have more details on the Darwin failure

Caused by the darwin LLVM 11 bump from the most recent staging cycle, it has broken a few other darwin packages: https://github.com/NixOS/nixpkgs/commit/775f5098c7b17806aad449d30307c273d67fe127.

**Comment by zowoq** [comment]
Disabling CGO would resolve this, upstream has it disabled it their goreleaser config.

We could probably just disable CGO for all of the providers, I don't think it would cause any problems. I'll take a look at it tomorrow.

```diff
diff --git a/pkgs/applications/networking/cluster/terraform-providers/default.nix b/pkgs/applications/networking/cluster/terraform-providers/default.nix
index 5a546851caa..7b8c13c528a 100644
--- a/pkgs/applications/networking/cluster/terraform-providers/default.nix
+++ b/pkgs/applications/networking/cluster/terraform-providers/default.nix
@@ -21,6 +21,8 @@ let
       deleteVendor = data.deleteVendor or false;
       proxyVendor = data.proxyVendor or false;
 
+      CGO_ENABLED = 0;
+
       # Terraform allow checking the provider versions, but this breaks
       # if the versions are not provided via file paths.
       postBuild = "mv $NIX_BUILD_TOP/go/bin/${data.repo}{,_v${data.version}}";
```

**Comment by zowoq** [comment]
@ofborg eval

**Pull request merged**
