### PR TITLE
kino-1.3.4 fixes; thanks to gentoo

### PR DESCRIPTION
**Pull request by qknight**

### CODE REVIEW

**Comment by codyopel** [comment]
It would be better to fetch the patches from a gentoo mirror than to add them to the repo.

http://www.gtlib.gatech.edu/pub/gentoo/gentoo-x86-portage/media-video/kino/files/

Gentoo now also has a portage mirror on github:
https://github.com/gentoo/gentoo-portage-rsync-mirror/tree/master/media-video/kino/files

**Comment by jagajaga** [comment]
@codyopel why do you think so?

**Comment by codyopel** [comment]
The reason is to not commit patches to the repo that are available for download.  Instead use ```fetchpatch``` or ```fetchurl``` to retrieve the patch, because patches are often not removed from nixpkgs after they are no longer needed or relevant.

**Comment by jagajaga** [comment]
I disagree with you. We have lots of patches and mostly they are from nixpkgs. That's our repo, so let's rely on it.

**Comment by qknight** [comment]
i agree with jagjaga on this issue.

**Pull request merged**
