### PR TITLE
nix-doc,nix-plugin: fix by pinning to nix 2.5 (2.6 breaks)

### PR DESCRIPTION
**Pull request by dtzWill**
###### Description of changes

See:
https://github.com/NixOS/nixpkgs/pull/157618#issuecomment-1059727303

Unbreak the two packages.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
cc https://github.com/shlevy/nix-plugins/issues/10 for nix-plugin .

**Comment by roberth** [comment]
cc @lf- as nix-doc maintainer.

Please update to match the latest nix.

**Review by roberth — APPROVED** [review]

**Review by roberth — CHANGES_REQUESTED** [review]
Please use separate commits. That way ofborg knows what to build. It skipped nix-plugin because it wasn't in the expected place.

**Comment by dtzWill** [comment]
(split into two commits, thanks!)

**Comment by lf-** [comment]
Noted. I will look into this upstream.

**Review by roberth — APPROVED** [review]

**Comment by lf-** [comment]
Hi! Thanks for pinging me. I have fixed the Nix compat issues upstream. For some reason (which I really do not understand; the relevant headers are definitely included), it was not resolving the appropriate functions. I have put in a shim to fix it.

**Pull request merged**
