### PR TITLE
cargo-espflash: 1.7.0 -> 2.0.0

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

I noticed the package was out of date and missing an update script.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@matthiasbeyer let me know if this looks good to you

**Review by matthiasbeyer — APPROVED** [review]
Yes looks good.
What is the nix update script? I've never seen this before...

**Comment by happysalada** [comment]
Have a quick grep at it, its everywhere, its a convenient program that can do most updates.
Adding that line in effect generates automatic update PRs. Those are usually a couple of days late, but they do come.
Feel free to ping me if you need help merging future PRd

**Comment by happysalada** [comment]
@ofborg build cargo-espflash

**Comment by matthiasbeyer** [comment]
> Have a quick grep at it, its everywhere, its a convenient program that can do most updates. Adding that line in effect generates automatic update PRs. Those are usually a couple of days late, but they do come. Feel free to ping me if you need help merging future PRd

I thought the bot automatically does this? At least it is doing so for other packages I maintain which I do not recall to have that line.
Either way, we'll see!

**Comment by happysalada** [comment]
Haha im having the other problem, the bot not wanting to pick up updates.
Some of the rust stuff needs to have a cargo.lock commited, the update script is able to generate it. Ive seen the bot being able to do very simple updates on its own, this script is a more advanced version.
If you find out otherwise, let me know. Maybe things have changed.

**Comment by happysalada** [comment]
hey, just so you know, ofborg was failing, so I added a couple more things to make it happy. I don't have a linux machine to test, but I'm going to try to verify that ofborg passes

**Review by matthiasbeyer — APPROVED** [review]

**Pull request merged**
