### PR TITLE
pythonPackages.ldaptor: run tests

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @lheckemann This completely disables privacyidea-ldap-proxy since that project does not support Python 3 while ldaptor does not support Python 2.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110151` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python37Packages.ldaptor</li>
<li>python38Packages.ldaptor</li>
</ul>
</details>

**Comment by lheckemann** [comment]
This breaks the ldap-proxy part of the privacyidea module, so I'm going to (partially) revert it and run the tests only on py3k.

**Comment by dotlambda** [comment]
> This breaks the ldap-proxy part of the privacyidea module, so I'm going to (partially) revert it and run the tests only on py3k.

But ldaptor does not support Python 2: https://github.com/twisted/ldaptor/blob/v20.1.1/setup.cfg#L22

**Comment by lheckemann** [comment]
Ah yes, I misunderstood. Ugh, I guess the ldap-proxy project is dead.

**Comment by dotlambda** [comment]
You could package an old version of ldaptor for Python 2.

**Comment by lheckemann** [comment]
We're going to need to migrate away from ldap-proxy to an alternative or pick up maintenance for it, since running EOL python isn't a long-term solution either.

**Pull request merged**
