### PR TITLE
Update tribler

### PR DESCRIPTION
**Pull request by gavinrogers**
It wasn't working at all. Now it's working although I'm not 100% gmpy is fully working.

If this can be merged it will be a much better situation to what is in master. I can make any improvements, please leave comments.

### CODE REVIEW

**Comment by wmertens** [comment]
@gavinrogers can you sprinkle some `with pythonPackages` in there, write the full tag name in the fetchgit and squash the commits? Then I think we can merge...

**Comment by lethalman** [comment]
Ok sorry good to know :)

**Comment by vcunat** [comment]
Ping. There seemed to by quite some interest from people with commit access.

**Comment by domenkozar** [comment]
@gavinrogers what's the status on this one?

**Comment by gavinrogers** [comment]
@domenkozar @vcunat had a baby come along so I was a bit busy. I got it mostly working the other day: let's see if my branch builds.

**Comment by gavinrogers** [comment]
I've pushed to my branch: I've fixed everything and it builds but now gmpy isn't found, where before it was. Gotta get some sleep for now though.

**Comment by Fuuzetsu** [comment]
Where are we at? Can we merge, close? See also #7012

**Comment by pSub** [comment]
Closing in favor of #8754.

**Pull request closed without merging**
