### PR TITLE
Facetimehd-Firmware: Update,  add update documentation, add myself as maintainer

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

Update the firmware for facetimehd in accordance to the recent facetimehd kernel module update.

Also @womfoo requested I add myself as a maintainer, so here goes: https://github.com/NixOS/nixpkgs/pull/15708#issuecomment-221775457
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"` (cheese, hangouts, skype, zoom.us, appear.in)
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X]  Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
To be honest I'm not keen on upgrading to unstable to test this properly, but on 16.03 (https://github.com/NixOS/nixpkgs/pull/15708) it works a treat.

**Comment by joachifm** [comment]
@grahamc do you know of any reason it wouldn't work on unstable? If not, I say we go ahead.

**Comment by grahamc** [comment]
No reason I know of.

**Comment by joachifm** [comment]
Cool

**Pull request merged**
