### PR TITLE
openutau: clarify license situation with worldline again

### PR DESCRIPTION
**Pull request by lilyinstarlight**
## Description of changes

It seems the prebuilt worldline files are considered redistributable as part of the project's MIT license. This updates the derivation to reflect that

See https://github.com/stakira/OpenUtau/commit/8b1d8b33557865a87c48e1586b361ea8c287b634

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ashvith10** [comment]
@lilyinstarlight correct me if I'm wrong, but MIT requires that the source code be distributed, and not just the binaries, right? All I see in the repo are the dynamic library files?

**Comment by lilyinstarlight** [comment]
> correct me if I'm wrong, but MIT requires that the source code be distributed, and not just the binaries, right? All I see in the repo are the dynamic library files?

IANAL, but MIT does not actually specify source code in the license text (unlike GPL and similar), just "software and associated documentation files". So while it is unfortunate the source code is not available, I imagine this is probably fine at least within the text of the license

If you are that unsure, though, I can ask in #dev:nixos.org on Matrix to see if anyone else in the project has insight

**Comment by Ashvith10** [comment]
> If you are that unsure, though, I can ask in #dev:nixos.org on Matrix to see if anyone else in the project has insight

I think that would be a  great idea.

**Comment by lilyinstarlight** [comment]
> Is the situation here that some source code is non-free, but there are binaries built from that source code that are MIT licensed?

Yes, that's correct, and they are included in an MIT-licensed repo that the copyright holder has explicitly said covers the binaries

> If so, if we're using the pre-built binaries, we don't need to specify unfree (but we should set `sourceProvenance`), but if we're building from source, the MIT license won't apply to our binaries.

Yep, `meta.sourceProvenance` has been set for these binaries already (and for some of the nuget deps that have native binaries)

**Comment by alyssais** [comment]
We have a bit of a conflict here between two different uses for the Nixpkgs meta.license field here — one is "what are the license terms I have to follow for this software", and the other is "is the software I am using free?".  Setting the license to just MIT is technically correct, but only for the first interpretation of what meta.license means, because the software is certainly not free, and people will rely on allowUnfree to prevent them from accidentally using unfree software, even with permissively licensed binaries.

So I think the best thing to do would be to set the license field to both mit and unfreeRedistributable, and then people can make their own decision about how to interpret that using allowUnfreePredicate, but won't end up accidentally depending on proprietary software.

**Comment by lilyinstarlight** [comment]
I've made the change to `unfreeRedistributable` instead

Note @Ashvith10 that this means Hydra will still not build this package, but that's not really relevant to this PR (and is a much bigger question of whether Hydra should build redistributable packages that are unfree) 🤷🏻‍♀️

**Review by Janik-Haag — APPROVED** [review]

**Pull request merged**
