### PR TITLE
stdenv: show supported and requested platforms when check meta fails

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

I did this a while ago and got annoyed that I had no feedback which platform I did not have support for.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by piegamesde — APPROVED** [review]

**Review by trofi — APPROVED** [review]

**Comment by wegank** [comment]
The PR seems to break `nixpkgs-review`?

**Comment by Artturin** [comment]
another issue https://github.com/NixOS/nixpkgs/pull/222777 , not everything has a meta.platforms

**Comment by wegank** [comment]
We should also remove the platforms in `meta.badPlatforms` from the output.

**Comment by wegank** [comment]
Opened #222792 to fix all of the above issues.

**Comment by amjoseph-nixpkgs** [comment]
> Platforms became more complicated after #212939

Note: platform patterns have been around for over four years, since before #37395.  But before #212939 you couldn't use them in `meta.[bad]platforms`, which prevented us from setting defaults (like `systemdSupport` for `pkgsStatic.*`) accurately.

**Comment by SuperSandro2000** [comment]
> another issue is that not everything has a meta.platforms

Does that not fall back to platforms.linux?

**Comment by Artturin** [comment]
> > another issue is that not everything has a meta.platforms
> 
> Does that not fall back to platforms.linux?
> 
> Also how can ofborg succeed here? Shouldn't the above cases triggered an eval failure.

perhaps same issue as https://github.com/NixOS/nixpkgs/pull/222963 ? (throw instead of abort)

**Pull request merged**
