### PR TITLE
podman: improve runtime patching

### LINKED ISSUE #306398: docker-compose v1 fails to bring up any compose file with podman v5.0
### Describe the bug
`docekr-compose up` v1 fails with
```
ERROR: runtime error: index out of range [0] with length 0
```
with even the trivial `docker-compose.yaml`
```yaml
version: '3.4'
```
when using podman v5.0 as the OCI container backend.

### Steps To Reproduce
1. Use podman 5.0
2. Run `docker-compose up` with a valid `docker-compose.yaml` using `docker-compose_1`

### Expected behavior
`docker-compose` should bring up services specified in the compose file.

### Additional context
[`arion`](https://github.com/hercules-ci/arion) still uses `docker-compose_1` under the hood, so affects deployments using it.

https://github.com/hercules-ci/arion/issues/237

### Notify maintainers
@Frostman
@NixOS/podman 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by the-sun-will-rise-tomorrow**
## Description of changes

Change the approach used to integrate runtimes, in order to:

- Better support macOS
- Make obscure OCI runtimes optional
- Work around a panic due to runtimes having no paths

Fixes #306398.

Context:
- https://github.com/containers/podman/issues/22561
- https://github.com/NixOS/nixpkgs/pull/301553#discussion_r1569433767
- https://github.com/NixOS/nixpkgs/pull/301553#issuecomment-2067548846

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by WxNzEMof** [comment]
@ofborg build podman.passthru.tests

**Comment by WxNzEMof** [comment]
@ofborg build podman.passthru.tests

**Comment by WxNzEMof** [comment]
@heitorPB @kevincox @cyrillzadra @lunik1 Could you test this, please?

**Comment by cyrillzadra** [comment]
I switched my input to your podman fix branch

```
  inputs = {
    nixpkgs = {
#      url = "github:NixOS/nixpkgs/nixos-unstable";
      url = "github:WxNzEMof/nixpkgs/podman-5-fixes";
    };
  };
```

updated my system with

```
nix flake update 
nixos-rebuild switch --flake .#nixos
```

Now executing `curl --unix-socket /var/run/user/1000/podman/podman.sock http://localhost/info` returns a json instead of an 500 error. 👍

**Comment by heitorPB** [comment]
@cyrillzadra Would you be so kind to share the json you got?

**Comment by cyrillzadra** [comment]
> @cyrillzadra Would you be so kind to share the json you got?

```
{
	"ID": "9c377965-fa0a-4871-94a3-6525a141a904",
	"Containers": 65,
	"ContainersRunning": 0,
	"ContainersPaused": 0,
	"ContainersStopped": 62,
	"Images": 112,
	"Driver": "overlay",
	"DriverStatus": [
		[
			"Supports d_type",
			"true"
		],
		[
			"Native Overlay Diff",
			"true"
		],
		[
			"Using metacopy",
			"false"
		],
		[
			"Supports shifting",
			"false"
		],
		[
			"Supports volatile",
			"true"
		],
		[
			"Backing Filesystem",
			"btrfs"
		]
	],
	"Plugins": {
		"Volume": [
			"local"
		],
		"Network": [
			"bridge",
			"macvlan",
			"ipvlan"
		],
		"Authorization": null,
		"Log": [
			"k8s-file",
			"none",
			"passthrough",
			"journald"
		]
	},
	"MemoryLimit": true,
	"SwapLimit": false,
	"CpuCfsPeriod": false,
	"CpuCfsQuota": false,
	"CPUShares": false,
	"CPUSet": false,
	"PidsLimit": true,
	"IPv4Forwarding": false,
	"BridgeNfIptables": false,
	"BridgeNfIp6tables": false,
	"Debug": false,
	"NFd": 11,
	"OomKillDisable": false,
	"NGoroutines": 13,
	"SystemTime": "2024-05-09T15:03:32.83130335+02:00",
	"LoggingDriver": "",
	"CgroupDriver": "systemd",
	"NEventsListener": 0,
	"KernelVersion": "6.6.30",
	"OperatingSystem": "nixos",
	"OSVersion": "24.05",
	"OSType": "linux",
	"Architecture": "amd64",
	"IndexServerAddress": "",
	"RegistryConfig": {
		"AllowNondistributableArtifactsCIDRs": [],
		"AllowNondistributableArtifactsHostnames": [],
		"InsecureRegistryCIDRs": [],
		"IndexConfigs": {},
		"Mirrors": []
	},
	"NCPU": 24,
	"MemTotal": 67282857984,
	"GenericResources": null,
	"DockerRootDir": "/home/user/.local/share/containers/storage",
	"HttpProxy": "",
	"HttpsProxy": "",
	"NoProxy": "",
	"Name": "nixos",
	"Labels": null,
	"ExperimentalBuild": true,
	"ServerVersion": "5.0.2",
	"Runtimes": {
		"crun": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/crun"
		},
		"crun-vm": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/crun-vm"
		},
		"crun-wasm": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/crun-wasm"
		},
		"kata": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/kata-runtime"
		},
		"krun": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/krun"
		},
		"ocijail": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/ocijail"
		},
		"runc": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/runc"
		},
		"runj": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/runj"
		},
		"runsc": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/runsc"
		},
		"youki": {
			"path": "/nix/store/nki3a4ym9nkaadbdwkns1h6ar9jcqgcj-podman-helper-binary-wrapper/bin/youki"
		}
	},
	"DefaultRuntime": "crun",
	"Swarm": {
		"NodeID": "",
		"NodeAddr": "",
		"LocalNodeState": "inactive",
		"ControlAvailable": false,
		"Error": "",
		"RemoteManagers": null
	},
	"LiveRestoreEnabled": false,
	"Isolation": "",
	"InitBinary": "",
	"ContainerdCommit": {
		"ID": "",
		"Expected": ""
	},
	"RuncCommit": {
		"ID": "",
		"Expected": ""
	},
	"InitCommit": {
		"ID": "",
		"Expected": ""
	},
	"SecurityOptions": [
		"name=seccomp,profile=default",
		"name=rootless"
	],
	"ProductLicense": "Apache-2.0",
	"CDISpecDirs": null,
	"Warnings": [],
	"BuildahVersion": "1.35.3",
	"CPURealtimePeriod": false,
	"CPURealtimeRuntime": false,
	"CgroupVersion": "2",
	"Rootless": true,
	"SwapFree": 0,
	"SwapTotal": 0,
	"Uptime": "23h 33m 51.00s (Approximately 0.96 days)"
}
```

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 310182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>out-of-tree</li>
    <li>podman</li>
    <li>podman.man</li>
  </ul>
</details>

**Comment by kevincox** [comment]
This fixes the issue for me.

Is it ready to merge?

**Review by SuperSandro2000 — APPROVED** [review]
LGTM

**Comment by tricktron** [comment]
Builds successfully and fixes the `ERROR: runtime error: index out of range [0] with length 0` on x86_64-linux.

**Comment by kevincox** [comment]
@WxNzEMof is there anything holding this back? It is a pretty major regression so I would like to merge it.

**Comment by WxNzEMof** [comment]
> @WxNzEMof is there anything holding this back?

No.

I would have liked to add a test for this functionality, so it doesn't regress again, but [I don't know how to reproduce it inside a NixOS test](https://github.com/NixOS/nixpkgs/issues/306398#issuecomment-2101278038).

> It is a pretty major regression so I would like to merge it.

Be my guest, we can add the test separately later.

**Comment by kevincox** [comment]
Ok thanks. Unless there are objections soon I will merge later today.

A test would be nice but I think that it can be a separate PR. I would rather it not block the fix.

**Comment by kevincox** [comment]
Thanks @WxNzEMof and everyone else who helped!

**Pull request merged**
