### PR TITLE
gnupg21: 2.1.14 -> 2.1.15

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

The `nox-review` phase reports errors, but those packages also fails to build on master just before this commit (kdevelop, python-gnupg, tclgpg)
###### Things done
- [X] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Pushed to staging in 447207d21d63e285dccdb992751a5e72f339e3e0 already

**Comment by lancelotsix** [comment]
Oh, I did not see it on staging (only checked master, and PRs).

There was a comment on the derivation source: 

```
# gpgsm-linking is fixed by commit (c49c43d7) in the gnupg master branch;
# fix-gpgsm-linking.patch should be dropped after gnupg 2.1.15 is released
patches = [ ./fix-gpgsm-linking.patch ];
```
447207d do not seem to remove it. Locally, master + 447207d cherry-picked fails to build (patch cannot apply). Maybe this should be updated on staging (and then this PR closed).

cc @fpletz

**Comment by lancelotsix** [comment]
Just pushed 9ed6e8a01dae7ee6cd26cb6068bbf2eb8b8ad4ec to staging to remove the obsolete patch.

**Comment by fpletz** [comment]
Thanks for the fix!

**Pull request closed without merging**
