### PR TITLE
Asciidoctor: add pygments.rb (highlighter) to Gemfile

### PR DESCRIPTION
**Pull request by PierreR**
###### Motivation for this change

I use `pygments.rb` to highlight haskell code in adoc file. Maintaining local gem files just to get that feature is a bit of a pain.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by PierreR** [comment]
@zimbatm would you mind reviewing this PR ?

**Comment by zimbatm** [comment]
Sure. Can you add me a sample where pygments.rb is being used? If I remember correctly there are multiple highlighting options available, is pygments.rb the best one?

**Comment by PierreR** [comment]
@zimbatm indeed there are a couple of source highlighter for `asciidoctor`: 
  - highlightjs: builtin (don't require any extra gem) but won't render in pdf (at least not haskell)
  - [coderay:](http://coderay.rubychan.de/) requires a separate gem, many languages not supported (`haskell` as an example)
  - [pygments](http://pygments.org/languages/) : requires a separate gem, many languages supported
  - prettify: don't know much about it but it didn't match my need at the time. I am not sure it is still active.

**Comment by zimbatm** [comment]
Thanks. Let's go with the batteries included route.

**Pull request merged**
