### PR TITLE
lxd: 5.19 -> 5.20

### PR DESCRIPTION
**Pull request by jnsgruk**
## Description of changes

Bump to latest version of LXD 5.20; update license to AGPLv3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jnsgruk** [comment]
Hmm, not sure I understand the ofborg output, package builds fine locally.

**Comment by jnsgruk** [comment]
@ofborg build

**Comment by adamcstephens** [comment]
It's failing to eval on something cuda related, not from this PR. I'm not sure exactly who is working on the fix.

**Comment by adamcstephens** [comment]
This needs a license change, as 5.20 is now agplv3: https://github.com/canonical/lxd/pull/12663

It would have been nice if this was at the top of the release notes, instead of at the bottom of a long unstructured list of changes.

Please rebase off master when updating the license to see if it fixes the eval.

**Review by megheaiulian — APPROVED** [review]

**Review by adamcstephens — CHANGES_REQUESTED** [review]
Please relicense to agplv3. Thanks!

**Comment by jnsgruk** [comment]
> Please relicense to agplv3. Thanks!

Done :)

**Comment by alerque** [comment]
The "relicense" to AGPL3 is not 100% accurate. Canonical employee contributions have been relicensed and future contributions will be under AGPL3 but the *current code base* includes Apache-2 licensed community contributions (lots of them). That makes the current release some unclear dual license situation with a mix of APL2 and AGPL3. Canonical has not properly called out this situation either at the project level nor in the relevant source files.

**Comment by adamcstephens** [comment]
Fair enough, then we should probably put both licenses on an array.

**Comment by jnsgruk** [comment]
@adamcstephens done

**Review by adamcstephens — APPROVED** [review]

**Comment by adamcstephens** [comment]
Incus exists for those who don't want the headache of this license change. 😉

**Pull request merged**
