### PR TITLE
update aws packages

### PR DESCRIPTION
**Pull request by Artturin**
```
nix-update aws-c-auth --commit
nix-update aws-c-common --commit
nix-update aws-c-event-stream --commit
nix-update aws-c-http --commit
nix-update aws-c-mqtt --commit
nix-update aws-c-s3 --commit
nix-update aws-c-compression --commit
nix-update aws-c-io --commit
nix-update aws-checksums --commit
nix-update aws-crt-cpp --commit
nix-update aws-c-sdkutils --commit
nix-update aws-c-cal --commit
nix-update aws-sdk-cpp --commit

```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg build nix

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Artturin** [comment]
@ofborg eval

no rebuild count, weird

**Comment by r-burns** [comment]
I think these updates have gone directly into master in the past - despite the rebuild count there aren't any heavyweight dependers AFAIK unless that has changed recently. Nothing wrong with going to staging to be safe though, it's up to you.

**Comment by Artturin** [comment]
> I think these updates have gone directly into master in the past - despite the rebuild count there aren't any heavyweight dependers AFAIK unless that has changed recently. Nothing wrong with going to staging to be safe though, it's up to you.

The previous time i updated these there were still under 500 rebuilds but now there's 537
```$ rg "x86_64-linux" Changed\ Paths | wc -l
537
```

**Pull request merged**
