### PR TITLE
Revert "lemmy: Support secret options"

### PR DESCRIPTION
**Pull request by adisbladis**
###### Description of changes

Revert "lemmy: Support secret options"

This reverts commit ee5cc38432031b66e7fe395b14235eeb4b2b0d6e (https://github.com/NixOS/nixpkgs/pull/239713).

Merging declarative NixOS configuration with out of store files is something that, afaik, we don't do anywhere else.
This breaks normal purity/reproducibility guarantees offered by the NixOS module system.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jian-lin** [comment]
> Merging declarative NixOS configuration with out of store files is something that, afaik, we don't do anywhere else.

The first 9 results of my search for `jq` in NixOS modules yield two modules which does this: [transmission][transmission] and [invidious][invidious].

> This breaks normal purity/reproducibility guarantees offered by the NixOS module system.

Currently, secrets has to be out of store.  Many modules provide a path option to let users specify a secret which will not be put into the store.  Searching `LoadCredential` in NixOS modules gives you some examples.

I am not sure what your point is.
- Are you against merging two json files and preferring to use `utils.genJqSecretsReplacementSnippet` which I mentioned in https://github.com/NixOS/nixpkgs/pull/239713#discussion_r1243502258 ?
- Are you against managing secrets out of store?

[transmission]: https://github.com/NixOS/nixpkgs/blob/ee5cc38432031b66e7fe395b14235eeb4b2b0d6e/nixos/modules/services/torrent/transmission.nix#L288
[invidious]: https://github.com/NixOS/nixpkgs/blob/ee5cc38432031b66e7fe395b14235eeb4b2b0d6e/nixos/modules/services/web-apps/invidious.nix#L26C18-L26C34

**Comment by happysalada** [comment]
I think we all agree that the ideal solution should be that upstream reads secrets from files, the question is what do we do before that happens ?

**Comment by adisbladis** [comment]
> we do this a whole lot, so much so that there's a utils.genJqSecretsReplacementSnippet helper for exactly this kind of thing. the alternative is to pretty much not have secrets support, which is a lot worse than even a one-off solution like this.

I proofread every single module I use and have never encountered this pattern before.

Regardless of previous usage this is _bad_ as it's not a granular secrets injection feature but overrides the whole darn config.
Despite the option naming implying this is a secrets feature, it's not, it's an impure configuration feature.

**Comment by adisbladis** [comment]
After some discussion in the NixOS Dev matrix channel I've come up with a succinct problem description:
It's a problem of an unbounded impurity vs a bounded one.

The current semantics are "merge declarative NixOS configuration with yeet config" which is too much.
If this was a granularly scoped option _only_ allowing you to point to an impure secret, not an entire config it would be much better.

**Comment by Deric-W** [comment]
I understand your concerns, I threw inspiration from [`services.nextcloud.secretFile`](https://search.nixos.org/options?channel=23.05&show=services.nextcloud.secretFile&from=0&size=50&sort=relevance&type=packages&query=secretFile) which does something similar.
For lemmy it should be possible to limit the secret configuration to the following secrets:

 - `database.uri` (maybe just `database.password`?)
 - `pictrs.api_key`
 - `email.smtp_password`
 - `setup.admin_password`
 
Would it be ok if each secret gets its own option?
I would be willing to work on a new PR.

**Comment by jian-lin** [comment]
FYI, https://github.com/NixOS/nixpkgs/pull/241562

**Pull request closed without merging**
