### PR TITLE
[staging] grpc: override abseil to use same std=c++14 version

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Description of changes

Reported broken on staging on comment: https://github.com/NixOS/nixpkgs/pull/165732#issuecomment-1087058576

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Will that affect 

https://github.com/NixOS/nixpkgs/blob/f9180933cae3dea5546b6954c66da7b77e04ff4c/pkgs/development/libraries/grpc/default.nix#L67-L72

**Comment by sternenseemann** [comment]
That's effectively dead code at this point, since we are defaulting to LLVM 11 or newer for everything but FreeBSD. On FreeBSD it's impossible to reach that point because `cmake` doesn't build anyway. So that shouldn't be a blocking concern for this PR and that code can probably be cleaned up.

I guess we could try
@ofborg pkgsLLVM.grpc
but it'll probably time out.

**Comment by sternenseemann** [comment]
@ofborg  build pkgsLLVM.grpc

**Comment by mweinelt** [comment]
> @ofborg build pkgsLLVM.grpc

```
CMake Warning at cmake/modules/Findc-ares.cmake:18 (find_package):
  Could not find a configuration file for package "c-ares" that is compatible
  with requested version "1.13.0".

  The following configuration files were considered but not accepted:

    /nix/store/nh777bwrcaz6z8rkzcs40xp80kdwsc67-c-ares-config.cmake/c-ares-config.cmake, version: unknown

Call Stack (most recent call first):
  cmake/cares.cmake:42 (find_package)
  CMakeLists.txt:312 (include)


-- Found c-ares: /nix/store/v5nz29zycv7iw9b85nqh1dqxa8hghbx6-c-ares-x86_64-unknown-linux-gnu-1.18.1/include (found suitable version "1.18.1", minimum required is "1.13.0") 
-- Found Protobuf: /nix/store/0dz9js7a5w0jpg4cwnycdlnl4rm3w5jx-protobuf-x86_64-unknown-linux-gnu-3.19.3/lib/libprotobuf.so (found version "3.19.3") 
-- Found PkgConfig: /nix/store/j44iq4s539mfs03ba6mghr9kgpa9h8za-x86_64-unknown-linux-gnu-pkg-config-wrapper-0.29.2/bin/x86_64-unknown-linux-gnu-pkg-config (found version "0.29.2") 
-- Found RE2 via pkg-config.
-- Found OpenSSL: /nix/store/d2mvw2fzpcql6fabj4qiyan30qy1yhwz-openssl-x86_64-unknown-linux-gnu-1.1.1n/lib/libcrypto.so (found version "1.1.1n")  
CMake Error at /nix/store/c5jhgwlnq0782aqxb7brkpxpb56h5bgh-cmake-3.22.3/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.12")
Call Stack (most recent call first):
  /nix/store/c5jhgwlnq0782aqxb7brkpxpb56h5bgh-cmake-3.22.3/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/c5jhgwlnq0782aqxb7brkpxpb56h5bgh-cmake-3.22.3/share/cmake-3.22/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/zlib.cmake:52 (find_package)
  CMakeLists.txt:318 (include)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/3rylbb0vg1ypmjhwk59glvmiamll49q7-grpc-x86_64-unknown-linux-gnu-1.44.0.drv' failed with exit code 1
```

**Comment by fabianhjr** [comment]
```
CMake Warning at cmake/modules/Findc-ares.cmake:18 (find_package):
  Could not find a configuration file for package "c-ares" that is compatible
  with requested version "1.13.0".
```

since this PR is to address `x86_64-linux` `gcc: gcc_10 → gcc_11` breakage that llvm issue seems to be unrelated, though currently present on staging.

Have no way to help since on the platform I am on the issue is not present: `pkgsLLVM.grpc on x86_64-linux — Success`

https://github.com/NixOS/nixpkgs/pull/167129/checks?check_run_id=5886474017

**Comment by sternenseemann** [comment]
> Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.12")

Possibly another zlib cross issue? cc @Mindavi

**Pull request merged**
