### PR TITLE
qemu: 2.2.1 ->  2.4.0

### PR DESCRIPTION
**Pull request by Bevaz**

### CODE REVIEW

**Comment by pSub** [comment]
cc @viric @edolstra

**Comment by domenkozar** [comment]
try running NixOS tests with it.

**Comment by lethalman** [comment]
Building the gnome3 nixos test:

```
install -d -m 0755 "/var"/run
install: cannot create directory '/var': Permission denied
Makefile:415: recipe for target 'install-localstatedir' failed
make: *** [install-localstatedir] Error 1
builder for ‘/nix/store/jlgxi0bnpm2s8hhk2a97h9c4aqr7dn14-qemu-2.4.0-x86-only.drv’ failed with exit code 2
```

**Comment by Bevaz** [comment]
Fixed with Bevaz/nixpkgs@0e0e3c0c08b77a64fc934795dc5d9647fbd58d42

**Comment by lethalman** [comment]
Did run a couple of nixos tests and it seems to work fine. Let's see how it goes, thanks. cc @edolstra

**Pull request merged**
