### PR TITLE
nodePackages.'@captainsafia/legit': init at 2.0.1

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

`legit` is a simple Node.js package which generates `LICENSE` files which makes bootstrapping new projects locally much easier.

__Short note before merging it:__ this package is a scoped package, I built it locally using `nix-build -A "nodePackages.@captainsafia/legit"`. The executable in `./result/bin` is named `legit`.

Since this seems to be the first NPM package in the `nixpkgs` repo which is scoped, I'm unsure whether I'm missing something.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
I would add an alias to `all-packages.nix`:

```
  legit = nodePackages.'@captainsafia/legit';
```

**Comment by Ma27** [comment]
good point, will do later :-)

**Comment by Ma27** [comment]
@Mic92 done...

**Comment by Ma27** [comment]
anything missing here?

**Comment by Ma27** [comment]
rebased onto current master

**Comment by Mic92** [comment]
```
$ legit list
```

is empty, because `/nix/store/87dv738w4kdwc5648vlwz924lskqyyz3-node-_at_captainsafia_slash_legit-2.0.1/lib/node_modules/@captainsafia/legit/licenses` is empty too. Should there be licenses file deployed a long the module?

**Comment by Ma27** [comment]
not sure right now, will test this tonight :-)

**Comment by Ma27** [comment]
@Mic92 when I run `nix-build -A legit` on my local checkout of my `nixpkgs` fork, it seems to work perfectly:

```
→ ./result/bin/legit list                                                                                                                                                                                                       [8260b9c9d2]
agpl-3.0
apache-2.0
bsd-2-clause
bsd-3-clause
epl-1.0
gpl-2.0
gpl-3.0
lgpl-2.1
lgpl-3.0
mit
mpl-2.0
unlicense
```

am I missing something?

**Comment by Mic92** [comment]
Just notices, when I build the package with sandbox enabled, I get the following unhandled error:

```
> @captainsafia/legit@2.0.1 postinstall /nix/store/87dv738w4kdwc5648vlwz924lskqyyz3-node-_at_captainsafia_slash_legit-2.0.1/lib/node_modules/@captainsafia/legit
> mkdir -p licenses && node src/load-licenses.js

{ FetchError: request to https://api.github.com/licenses failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/nix/store/87dv738w4kdwc5648vlwz924lskqyyz3-node-_at_captainsafia_slash_legit-2.0.1/lib/node_modules/@captainsafia/legit/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'FetchError',
  message: 'request to https://api.github.com/licenses failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
(node:675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'forEach' of undefined
npm WARN @captainsafia/legit@2.0.1 No repository field.
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/87dv738w4kdwc5648vlwz924lskqyyz3-node-_at_captainsafia_slash_legit-2.0.1
patching script interpreter paths in /nix/store/87dv738w4kdwc5648vlwz924lskqyyz3-node-_at_captainsafia_slash_legit-2.0.1
```

But it seems that this error can be easily fixed with a download during build.

**Comment by Mic92** [comment]
The licenses from github api can be also downloaded from here: https://github.com/github/choosealicense.com/tree/gh-pages/_licenses

**Comment by Ma27** [comment]
closing for now. Due to a new package format in `node2nix` this change contains huge merge conflicts and lack of time to work on the issues coming with this change.

**Pull request closed without merging**
